{dede:field name='keywords'}复仇者联盟R6DVD英语中字2012美{/dede:field}
{dede:field name='description'}复仇者联盟R6DVD英语中字2012美国科幻迅雷下载、免费下载，复仇者联盟R6DVD英语中字2012美国科幻Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}复仇者联盟R6DVD英语中字2012美国科幻{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-20{/dede:field}
{dede:field name='body'}<p>
	&nbsp;<img border="0" src="/uploads/allimg/c120525/133O0UHI0-20K04.jpg" /></p>
<p>
	【影片原名】The Avengers<br />
	【外文别名】&quot;The Avengers: An IMAX 3D Experience&quot; - International (English title) (IMAX version)<br />
	【中文译名】复仇者联盟/复仇者<br />
	【出品公司】Marvel Enterprises<br />
	【出品年代】2012 年<br />
	【上映日期】2012年5月4日 美国<br />
	【IMDB链接】http://www.bluemv.com<br />
	【IMDB评分】8.9/10 (6,498 votes) Top 250: #194<br />
	【国　　家】美国<br />
	【类　　别】动作/冒险/科幻<br />
	【导　　演】乔斯&middot;韦登 Joss Whedon<br />
	【主　　演】克里斯&middot;埃文斯 Chris Evans ....Steve Rogers / Captain America<br />
	　　　　　　小罗伯特&middot;唐尼 Robert Downey Jr. ....Tony Stark / Iron Man<br />
	　　　　　　克里斯&middot;海姆斯沃斯 Chris Hemsworth ....Thor<br />
	　　　　　　斯嘉丽&middot;约翰逊 Scarlett Johansson ....Natasha Romanoff / Black Widow<br />
	　　　　　　马克&middot;鲁法洛 Mark Ruffalo ....Bruce Banner<br />
	　　　　　　杰瑞米&middot;雷纳 Jeremy Renner ....Clint Barton / Hawkeye<br />
	　　　　　　寇碧&middot;史莫德斯 Cobie Smulders ....Maria Hill<br />
	　　　　　　塞缪尔&middot;杰克逊 Samuel L. Jackson ....Nick Fury<br />
	　　　　　　汤姆&middot;希德勒斯顿 Tom Hiddleston ....Loki<br />
	　　　　　　格温妮丝&middot;帕特洛 Gwyneth Paltrow ....Pepper Potts<br />
	　　　　　　保罗&middot;贝坦尼 Paul Bettany ....Jarvis (voice)<br />
	　　　　　　斯特兰&middot;斯卡斯加德 Stellan Skarsg?rd ....Professor Erik Selvig<br />
	　　　　　　卢&middot;费里诺 Lou Ferrigno ....The Incredible Hulk (voice)<br />
	　　　　　　珍妮&middot;艾加特 Jenny Agutter ....Female council member<br />
	　　　　　　克拉克&middot;格雷格 Clark Gregg ....Agent Phil Coulson</p>
<p>
	<br />
	【内容简介】</p>
<p>
	一股突如其来的强大邪恶势力对地球造成致命威胁,没有任何一个超级英雄能够单独抵挡。长期致力于保护全球安危的神盾局(SHIELD)感到措手不及,其指挥官&ldquo;独眼侠&rdquo;尼克-法瑞(塞缪尔&middot;杰克逊饰)意识到他必须创建一个&ldquo;史上最强&rdquo;的联盟组织,云集各方超级英雄一起发威,才能拯救世界于水深火热,抵御黑暗势力的侵袭。于是由六大超级英雄-&ldquo;钢铁侠&rdquo;、&ldquo;雷神&rdquo;、&ldquo;美国队长&rdquo;、&ldquo;绿巨人&rdquo;、&ldquo;黑寡妇&rdquo;和&ldquo;鹰眼&rdquo;组成的&ldquo;复仇者联盟&rdquo;应运而生。他们各显神通,团结一心,终于战胜了邪恶势力,保证了地球的安全。</p>
<p>
	幕后制作</p>
<p>
	影片预告片中并未出现负责影片发行的迪士尼的标志性城堡,取而代之的则是百年派拉蒙的山峰&mdash;&mdash;这一变化源于2010年十月两家所签订的一份协议,作为失去《复仇者联盟》和《钢铁侠3》全球发行权的补偿,派拉蒙将会获得迪士尼发行《复仇者》影片收入的8%、《钢铁侠3》收入的9%(两者至少1.15亿美元);除此之外,派拉蒙还享有关于这两部影片任何市场推广的唯一署名权,也就是说,虽然迪士尼拥有两部影片全球唯一的发行权,却无法将自己的Logo加到片中。</p>
<p>
	　　迪士尼日前宣布《复仇者联盟》(The Avengers)在英国的片名更改为&quot;Avengers Assemble&quot;,对此官方给出的解释是&ldquo;为了不让观众把影片与英国上世纪60年代的经典剧集《复仇者》以及1998年的同名电影版《复仇者》相混淆&rdquo;。</p>
<p>
	　　超级大混搭</p>
<p>
	虽然说,《复仇者联盟》是一部众多漫画迷和超级英雄迷们翘首以待的电影,但是在其创作者们的心中,这部电影却并不是一个抢手的香饽饽,究其原因其实很简单:太多的英雄、太多不同的超级能力,太难杂糅在一起了。乔恩&middot;费儒,这位开创了《钢铁侠》的大导演曾经一度是本片的导演人选,但是他最终选择了退出。费儒说:&ldquo;我没办法指导这部电影,因为这太难了。我在电影中营造了一个用高科技打造出来的钢铁侠,但是他现在却要和复仇者联盟在一起战斗,这里有托尔这样的神话人物,也有一些和高科技很不搭的超自然能力等等。要把这些元素杂糅在一起其实是很难很难的。在漫画中这样来表现或者没有问题,但是在电影里,这样拍摄我就不行了。&rdquo;</p>
<p>
	　　虽然后来也有人问过影片的监制凯文&middot;费格,希望能把雷神这个碍眼的角色去掉。但是却得到了否定的答案,费格希望做的是一部全景式展示这些漫画人物的影片。随后,制片方找到了曾经拍摄过电视剧和电影版《萤火虫》的乔斯&middot;韦登,让他来指导这部电影。影片中的混搭元素,其实是显而易见的,韦登说:&ldquo;影片有一个非常漫画性的剧本,看上去,这些复仇者联盟的成员似乎就是从各自的电影中走出来的一样。整个这个东西混杂在一起,看上去又傻又有意思。这里有神话人物,有二战的美国大兵也有托尼&middot;斯塔克这样的军火商和独行侠。要把这些人物给放在一起可真不容易。从根本上来说,这群人本不属于一部电影,而现在却要用一个故事把他们串在一起。我觉得,这么一个故事,就成为了电影的重点内容。&rdquo;在影片的风格上,凯文&middot;费格坦承自己想把它拍摄的传统一些,少一些CG内容。他说:&ldquo;60年的那些《复仇者联盟》的漫画给了我很多的影响,我是看着那些漫画长大的一代人。这群人是一家人,是一条战线里的战士。所以,我极想在影片中表现出这些亲情的内容。而画面、特效方面,我并不想把它拍摄成超级大片,一定要有自己的风格和特点。我想,这样的《复仇者联盟》才会得到广大动漫迷的喜爱。&rdquo;</p>
<p>
	　　人物谱和转制3D</p>
<p>
	影片中的人物众多,而且每个人物都是&ldquo;当红明星&rdquo;,加之编剧无法平均分配戏份,所以难免会有&ldquo;厚此薄彼&rdquo;的现象。乔斯&middot;韦登说:&ldquo;电影是遗憾的艺术,无论在什么方面,什么时候,都会留下遗憾。在剧情上,我和编剧们已经做了最大的努力和尝试,已经尽了所有的可能要平均化了,但很遗憾,这是不太现实的一个想法。所以,有些超级英雄只能在这部电影里被当作配角了。不过,这也不会令人失望,因为片中有很多动作戏,虽然有这么多超级英雄在一起,但是这部电影始终还是一部动作片。注意那些大场面的动作戏就好,因为这才是这部电影的血肉。&rdquo;谈及片中的人物,制片人凯文&middot;费格说:&ldquo;这样的电影有一个好处,那就是观众对其中的角色都很熟悉,因为他们看过之前的那些电影,所以不需要我们在这部电影中对这些人物做什么解释或者是解读,我们可以很直接的切入剧情,讲述故事。无论是人物的性格还是他们的立场,早就是人尽皆知的事实。在这种情况下,我们没有什么可回避的,也没有什么太多的废话多要说。直接讲述故事,不用做任何的铺垫,让观众从一开始就看到高潮,一直保持着这种高昂的情绪,这样就好了。&rdquo;</p>
<p>
	　　2011年12月,迪士尼宣布《复仇者联盟》将被转制成3D。关于转制3D,乔斯&middot;韦登表示了一个很审慎的态度。他说:&ldquo;看着工程师把电影转制成3D,是一件很有趣的事情。我很不喜欢那种长镜头的,到处都充满了对白的电影。我喜欢的是那种能让人感觉到身临其境的电影。所以,3D很符合我的审美倾向。说实话,有很多电影并不适合转制成3D。不过3D版本的《复仇者联盟》肯定不令人讨厌。而且有很多场景,的确能让人产生一种置身于电影中的感受。站在这个角度上,3D的《复仇者联盟》让我很是喜爱。&ldquo;</p>
<p>
	　　一个很审慎的态度。他说:&quot;看着工程师把电影转制成3D,是一件很有趣的事情。我很不喜欢那种长镜头的,到处都充满了对白的电影。我喜欢的是那种能让人感觉到身临其境</p>
<p>
	花絮</p>
<p>
	&middot;钢铁侠在片中总是把自己这群盟友称为&ldquo;地球最强&rdquo;(Earth&#39;s mightiest heroes,thatkindofthing)。这句话来源于1963年《复仇者联盟》漫画出版时的标语。而且,这句话也成为了2010年动画版的标题:《复仇者:超级英雄联盟》(TheAvengers: Earth&#39;s Mightiest Heroes)。</p>
<p>
	　　&middot;这是绿巨人和雷神第二次同时出现在同一部影视作品中。他们第一次同台亮相是在1988年的电视电影《绿巨人归来》(The Incredible Hulk Returns)之中。</p>
<p>
	　　&middot;制片人凯文&middot;费格常常把《变形金刚3》拿来和这部电影做比较,他希望《复仇者联盟》能在效果上超过《变3》。</p>
<p>
	　　&middot;影片采用了表演捕捉技术,所以马克&middot;鲁法洛可以自己既扮演绿巨人又扮演变身前的布鲁斯&middot;班纳。在以往的电影中,绿巨人和布鲁斯&middot;班纳要么是由两个演员扮演的,要么绿巨人是完全的CG产物。</p>
<p>
	　　&middot;曾经扮演过绿巨人的爱德华&middot;诺顿原本是本片中绿巨人的扮演者,但是他和漫威漫画之间并没有就此达成协议,从而没能再次扮演这个角色。在诺顿之后,杰昆&middot;菲尼克斯曾是扮演绿巨人的候选人。</p>
<p>
	　　&middot;卢&middot;费里诺在影片中为绿巨人配音,自从1978年以来,他几乎声演了所有真人版的绿巨人影片。</p>
<p>
	　　&middot;为了扮演雷神,克里斯&middot;海姆斯沃斯进行了大量的身体训练和饮食控制。</p>
<p>
	　　&middot;本片导演乔斯&middot;韦登是著名的《X战警》的粉丝。早在1990年代,他就撰写了《X战警》的剧本。不过这个版本的《X战警》未能开拍。在这部电影里,有两句台词出自他撰写的《X战警》的剧本。</p>
<p>
	　　&middot;美国的科学与娱乐交流协会(Science and Entertainment Exchange)为影片提供了科普性的指导。</p>
<p>
	　　&middot;小罗伯特&middot;唐尼在片场总是喜欢穿一件黑色安息日乐队的T恤。而该乐队的歌曲也出现在了《钢铁侠》之中。</p>
<p>
	　　&middot;影片演员阵容中,获得过奥斯卡奖的,足足有9位之多。这足以创下漫画电影的记录了。</p>

<p>
	◎影片截图</p>
<p>
	&nbsp;&nbsp;</p>
<p>
	<img border="0" src="/uploads/allimg/c120525/133O0UJ120-219611.jpg" /></p>
<p>
	<img border="0" src="/uploads/allimg/c120525/133O0UJJ0-22MP.jpg" /></p>
<p>
	<img border="0" src="/uploads/allimg/c120525/133O0UK350-2322A.jpg" /></p>
<p>
	<img border="0" src="/uploads/allimg/c120525/133O0UKa0-24N17.jpg" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="/uploads/allimg/c120525/133O0T31310-42214.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：http://www.xiaozhizhu.net</td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:3441/飘花电影piaohua.com复仇者联盟R6DVD英语中字.rmvb</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O0UL5Z-25J52.jpg{/dede:field}
