{dede:field name='keywords'}豆富小僧DVD中字2011动画迅雷下{/dede:field}
{dede:field name='description'}豆富小僧DVD中字2011动画迅雷下载、免费下载，豆富小僧DVD中字2011动画Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}豆富小僧DVD中字2011动画{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-10-17{/dede:field}
{dede:field name='body'}<p>
	<img alt="" height="360" src="/uploads/allimg/c120525/133O045E330-2b07.jpg" style="cursor: pointer" width="600" /></p>
<p>
	◎译　　名: 豆富小僧<br />
	◎年　　代　2011<br />
	◎国　　家　日本<br />
	◎类　　别　3D卡通<br />
	◎语　　言　日语<br />
	◎字　　幕　幻樱砂之团翻译中文繁体<br />
	◎IMDB评分&nbsp;&nbsp;不祥<br />
	◎文件格式　X264 + AC3<br />
	◎视频尺寸　960X540<br />
	◎片　　长　85 Mins<br />
	◎导　　演：杉井仪三郎&nbsp; &nbsp;Gisaburo Sugii<br />
	◎编　　剧：京极夏彦&nbsp; &nbsp;Natsuhiko Kyougoku<br />
	◎声&nbsp; &nbsp; 优:&nbsp;&nbsp;深田恭子 Ky&amp;ocirc;ko Fukada&mdash;&mdash;豆腐小僧<br />
	&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;武田铁矢 Tetsuya Taketa&mdash;&mdash;达摩<br />
	&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;小池彻平 Teppei Koike&nbsp;&nbsp;<br />
	&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;平野绫 Aya Hirano&nbsp;&nbsp;<br />
	&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;檀丽 Rei Dan&nbsp;&nbsp;<br />
	&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;宫迫博之 Hiroyuki Miyasako<br />
	&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;大泉洋 Yo Oizumi<br />
	&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;春菜爱 Ai Haruna<br />
	◎故事简介：<br />
	&nbsp; &nbsp;&nbsp; &nbsp;大家好，我叫豆富小僧。我的爸爸是妖怪大王见越入道。只要离开手里这个盛着豆腐的盘子，我就会消失。 　　<br />
	&nbsp; &nbsp;&nbsp; &nbsp;这天，我吓唬人不成被朋友们笑话，爸爸因此大发雷霆。我很伤心，想去找妈妈，就和达摩老师一起穿越妖怪森林。不料，走到半路，狡猾的狸猫骗了我们，把我们关进了一间奇怪的屋子里。狸猫族和我们妖怪族已经敌对了几百年，穿戏服的狸猫大王一直等待着能一举消灭妖怪的机会。 　　<br />
	&nbsp; &nbsp;&nbsp; &nbsp;我和达摩老师一块儿做游戏消磨时间。突然，随着一声巨响，屋子塌了，奇特的景象出现在我们面前。原来时光已经过去了两百年，我们正身处于满是高楼和大马路的新世界。这里到处都看不到妖怪，擦肩而过的人们则对我们视而不见。为了寻找妖怪同伴，我们来到了能够望到远处的高塔。在这里，有一个女孩看见了我们。她叫小爱。她没有爸爸，妈妈忙着研究天气的工作，总让她一个人呆着。我们很快成了小爱的朋友。当狸猫攻击我们的时候，小爱救了我们。小爱的勇气让我很感动，可是我也因为自己的没用而感到沮丧。小爱对我说：&ldquo;豆富一定也有属于自己的角色。&rdquo; 　　<br />
	&nbsp; &nbsp;&nbsp; &nbsp;新闻里说台风即将来袭，狸猫大王竟打算趁此机会作怪。决不能眼睁睁地看着小爱生活的城市被吹走。 　　<br />
	&nbsp; &nbsp;&nbsp; &nbsp;终于，我找到了只有我能办到的事情。然而，这也许要付出巨大的代价。<br />
	<br />
	&nbsp;</p>
<p>
	<img alt="" src="/uploads/allimg/c120525/133O045GF-361M.jpg" /></p>

<p>
	[下载地址]：&nbsp;&nbsp;
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:1832/飘花电影piaohua.com豆富小僧DVD中字.mkv</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O045H520-45P1.jpg{/dede:field}
