{dede:field name='keywords'}安妮日记[DVD中英双字]迅雷下载{/dede:field}
{dede:field name='description'}安妮日记[DVD中英双字]迅雷下载、免费下载，安妮日记[DVD中英双字]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}安妮日记[DVD中英双字]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2010-04-19{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://3e:3e@m1.3edyy.com:1465/【3E电影院www.eee4.cc】安妮日记BD中英双字1024x576高清版.rmvb" target=_blank>ftftp://3e:3e@m1.3edyy.com:1465/【3E电影院www.eee4.cc】安妮日记BD中英双字1024x576高清版.rmvb</A></TD></TR></TBODY></TABLE><BR><BR><FONT color=#ff0000 size=2><STRONG>[下载地址]：<IMG src="httftp://www.3edyy.com/templets/img/down.jpg" border=0></STRONG></FONT><BR>
<TABLE style="BORDER-RIGHT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; BORDER-BOTTOM: #cccccc 1px dotted" cellSpacing=0 cellPadding=6 width="95%" align=center border=0>
<TBODY>
<TR>
<TD style="WORD-WRAP: break-word" bgColor=#fdfddf><A href="ftftp://5e:5e@d8.3edyy.com:132/【3E电影院www.eee4.cc】安妮日记.rmvb" target=_blank>ftftp://5e:5e@d8.3edyy.com:132/【3E电影院www.eee4.cc】安妮日记.rmvb</A></TD></TR></TBODY></TABLE></div><ul class="mmlist{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MP612960-42Y2.jpg{/dede:field}
