<?php
$z[0]=Array("field","安妮日记[DVD中英双字]迅雷下载",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","安妮日记[DVD中英双字]迅雷下载、免费下载，安妮日记[DVD中英双字]Gvod高清在线播放，剧情介绍等。",72,208);
$z[1][4]['name']="description";
$z[2]=Array("field","安妮日记[DVD中英双字]",210,269);
$z[2][4]['name']="title";
$z[3]=Array("field","",271,310);
$z[3][4]['name']="writer";
$z[4]=Array("field","",312,351);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-04-19",353,403);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",405,442);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://3e:3e@m1.3edyy.com:1465/【3E电影院www.eee4.cc】安妮日记BD中英双字1024x576高清版.rmvb\" target=_blank>ftftp://3e:3e@m1.3edyy.com:1465/【3E电影院www.eee4.cc】安妮日记BD中英双字1024x576高清版.rmvb</A></TD></TR></TBODY></TABLE><BR><BR><FONT color=#ff0000 size=2><STRONG>[下载地址]：<IMG src=\"httftp://www.3edyy.com/templets/img/down.jpg\" border=0></STRONG></FONT><BR>\r\n<TABLE style=\"BORDER-RIGHT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; BORDER-BOTTOM: #cccccc 1px dotted\" cellSpacing=0 cellPadding=6 width=\"95%\" align=center border=0>\r\n<TBODY>\r\n<TR>\r\n<TD style=\"WORD-WRAP: break-word\" bgColor=#fdfddf><A href=\"ftftp://5e:5e@d8.3edyy.com:132/【3E电影院www.eee4.cc】安妮日记.rmvb\" target=_blank>ftftp://5e:5e@d8.3edyy.com:132/【3E电影院www.eee4.cc】安妮日记.rmvb</A></TD></TR></TBODY></TABLE></div><ul class=\"mmlist",444,1363);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MP612960-42Y2.jpg",1365,1448);
$z[8][4]['name']="litpic";

?>