<?php
$z[0]=Array("field","耶稣受难记BD中英双字1024/1280",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","耶稣受难记BD中英双字1024/1280高清版迅雷下载、免费下载，耶稣受难记BD中英双字1024/1280高清版Gvod高清在线播放，剧情介绍等。",72,236);
$z[1][4]['name']="description";
$z[2]=Array("field","耶稣受难记BD中英双字1024/1280高清版",238,311);
$z[2][4]['name']="title";
$z[3]=Array("field","",313,352);
$z[3][4]['name']="writer";
$z[4]=Array("field","",354,393);
$z[4][4]['name']="source";
$z[5]=Array("field","2012-04-08",395,445);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",447,484);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://3e:3e@vip.eee4.cn:619/[www.eee4.cn提供]耶稣受难记BD中英双字1024x576高清版.rmvb\" target=\"_blank",486,625);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MP21P30-234W.jpg",627,709);
$z[8][4]['name']="litpic";

?>