{dede:field name='keywords'}乌龙戏凤2012HD1280国语中字2012{/dede:field}
{dede:field name='description'}乌龙戏凤2012HD1280国语中字2012最新喜剧迅雷下载、免费下载，乌龙戏凤2012HD1280国语中字2012最新喜剧Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}乌龙戏凤2012HD1280国语中字2012最新喜剧{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-21{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://apollo.s.dpool.sina.com.cn/nd/dataent/moviepic/pics/168/moviepic_6c26b5439364b2ab03ab0c381f89c93c.jpg" /></p>
<p>
	<img border="0" src="http://img2081.poco.cn/mypoco/myphoto/20120222/01/56643687201202220119092790319834189_005.jpg" /></p>
<p>
	<img border="0" src="http://img2081.poco.cn/mypoco/myphoto/20120222/01/56643687201202220119092790319834189_007.jpg" /></p>
<p>
	<img border="0" src="http://img2081.poco.cn/mypoco/myphoto/20120222/01/56643687201202220119092790319834189_006.jpg" /></p>
<p>
	◎译　　名　乌龙戏凤2012/宝岛大爆走/宝岛奇遇记<br />
	◎片　　名　Bang Bang Formosa<br />
	◎年　　代　2012<br />
	◎国　　家　中国台湾<br />
	◎类　　别　喜剧<br />
	◎语　　言　国语/台语<br />
	◎字　　幕　中文<br />
	◎IMDB评分 N/A<br />
	◎IMDB链接 N/A<br />
	◎文件格式　高清720P版BD-RMVB<br />
	◎视频尺寸　1280 x 544<br />
	◎文件大小　1CD 1.05GB<br />
	◎片　　长　99 Mins<br />
	◎导　　演　罗安得 Andy Luo<br />
	◎主　　演　陈怡蓉 Tammy Chen<br />
	　　　　　　澎恰恰 Pon Chia Chia<br />
	　　　　　　苑新雨 Yuan xinyu<br />
	　　　　　　九孔 Jiu Kong<br />
	　　　　　　要润 Jun Kaname<br />
	　　　　　　房思瑜 Siyu Fang<br />
	　　　　　　路斯明 Johnny Lu<br />
	　　　　　　赵立新 Lixin Zhao<br />
	&nbsp;</p>
<p>
	◎简　　介　</p>
<p>
	与同学结伴来到台湾游玩的上海嗲妹谭艳飞（苑新雨饰），活泼单纯、好奇心特别强烈的她被台湾美好的风景吸引，独自寻觅美食，与同伴走散，被人意外绑架。警探（澎恰恰饰）即将退休，为叛逆女儿烦心的他阴差阳错的救了谭艳飞，并负责一路护送她回家。不过这一路上却没有想象的那么顺利，绑架也似乎没有那么简单，摇滚怪客（九孔饰）、妖艳女王（陈怡蓉饰）、白马王子（路斯明饰）等人半路杀出，纠缠笑闹，癫狂追逐，背后的真相究竟是什么？</p>
<p>
	<br />
	◎影片截图</p>

<p>
	<img src="http://img2081.poco.cn/mypoco/myphoto/20120520/14/56643687201205201424584124977629485_002.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 255px; border-top: 0px solid; border-right: 0px solid" /></p>
<p>
	<img src="http://img2081.poco.cn/mypoco/myphoto/20120520/14/56643687201205201424584124977629485_000.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 255px; border-top: 0px solid; border-right: 0px solid" /></p>
<p>
	<img src="http://img2081.poco.cn/mypoco/myphoto/20120520/14/56643687201205201424584124977629485_003.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 255px; border-top: 0px solid; border-right: 0px solid" /></p>
<p>
	<img src="http://img2081.poco.cn/mypoco/myphoto/20120520/14/56643687201205201424584124977629485_001.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 255px; border-top: 0px solid; border-right: 0px solid" /></p>
<p>
	[下载地址]： &nbsp;<img border="0" src="/0701pic/allimg/120110/01223C617-5.jpg" /></p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2863/飘花电影piaohua.com乌龙戏凤2012HD国语中字.rmvb">&nbsp;ftp://dy44:piaohua@dy44.piaohua.com:2863/飘花电影piaohua.com乌龙戏凤2012HD国语中字.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3467/飘花电影piaohua.com乌龙戏凤2012HD国语中字高清.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3467/飘花电影piaohua.com乌龙戏凤2012HD国语中字高清.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3467/飘花电影piaohua.com乌龙戏凤2012HD国语中字高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15N11F-43c8.jpg{/dede:field}
