{dede:field name='keywords'}红场飞龙HD高清迅雷下载，免费下{/dede:field}
{dede:field name='description'}红场飞龙HD高清迅雷下载、免费下载，红场飞龙HD高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}红场飞龙HD高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-11-07{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="/uploads/allimg/c120525/133O02M3060-1b07.jpg" /></p>
<p>
	◎片　　名　Dragon From Russia/Gong chang fei long<br />
	◎译　　名　红场飞龙/泪眼煞星<br />
	◎年　　代　1990<br />
	◎国　　家　中国香港<br />
	◎类　　别　动作<br />
	◎语　　言　普通话<br />
	◎字　　幕　繁体中文<br />
	◎IMDB评分　5.8/10 (202 votes)<br />
	◎IMDB链接　http://www.imdb.com/title/tt0099791<br />
	◎片　　长　94 mins<br />
	◎导　　演　霍耀良 Clarence Fok Yiu-leung<br />
	◎主　　演　Tak Yuen<br />
	　　　　　　Hing Suen<br />
	　　　　　　Dean Shek<br />
	　　　　　　李丽珍 Loretta Lee<br />
	　　　　　　吴家丽 Carrie Ng<br />
	　　　　　　利智 Nina Li Chi<br />
	　　　　　　张曼玉 Maggie Cheung<br />
	　　　　　　许冠杰 Sam Hui<br />
	<br />
	◎简　　介<br />
	<br />
	姚龙因目睹杀人事件，被击晕倒，尽忘旧事。八百龙长老见其健硕，训练他为八百龙杀手。训练期满时同伴被杀身亡，命龙追查真凶&hellip;&hellip;<br />
	久别娱乐圈的许冠杰其金曲深入人心，他主演的电影在当年也相当触目，其中红场飞龙远赴苏联拍摄，演姚龙的许冠杰人型人格，身手敏捷之余更成功的塑造了一个外冷内热的杀手<br />
	<img alt="" src="/uploads/allimg/c120525/133O02M60Z-262D.jpg" style="width: 720px; height: 405px" /><img alt="" src="/uploads/allimg/c120525/133O02MH60-323Y.jpg" style="width: 720px; height: 405px" /><img alt="" src="/uploads/allimg/c120525/133O02MR10-42140.jpg" style="width: 720px; height: 405px" /><br />
	&nbsp;</p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="/uploads/allimg/c120524/133N2Z4FF-102231.jpg" />&nbsp;&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy125:piaohua@dy125.piaohua.com:7141/飘花电影piaohua.com红场飞龙HD国语中字1280高清.rmvb</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O02M9330-51S6.jpg{/dede:field}
