{dede:field name='keywords'}变形金刚1-3部BD国语配音中字102{/dede:field}
{dede:field name='description'}变形金刚1-3部BD国语配音中字1024高清科幻大迅雷下载、免费下载，变形金刚1-3部BD国语配音中字1024高清科幻大Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}变形金刚1-3部BD国语配音中字1024高清科幻大{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-03-17{/dede:field}
{dede:field name='body'}<p>
	<img alt="" height="771" src="http://img208.poco.cn/mypoco/myphoto/20110702/11/56634212201107021127398850809014799_000.jpg" width="500" /></p>

<p>
	<img alt="" height="843" src="http://img.album.pchome.net/54/71/43/96/a779040618a98f114fd5fab8ef848d9b.JPG" style="cursor: pointer" width="600" /></p>
<p>
	&nbsp;<img alt="" src="http://apollo.s.dpool.sina.com.cn/nd/dataent/moviepic/pics/139/moviepic_2553cc37dae71c2d444877dd8f963e4f.jpg" /></p>
<p>
	◎译　　名　变形金刚<br />
	◎片　　名　Transformers<br />
	◎年　　代　2007<br />
	◎国　　家　美国<br />
	◎类　　别　动作/科幻/冒险/喜剧/惊悚<br />
	◎语　　言　国语<br />
	◎字　　幕　中字<br />
	◎IMDB评分 7.8/10 (82,085 votes)<br />
	◎片　　长　144 Mins<br />
	◎导　　演　迈克尔&middot;贝Michael Bay<br />
	◎主　　演　希安&middot;拉博夫 Shia LaBeouf<br />
	　　　　　　乔什&middot;杜哈明 Josh Duhamel<br />
	　　　　　　泰瑞斯&middot;吉布森 Tyrese Gibson<br />
	　　　　　　乔恩&middot;沃伊特 Jon Voight<br />
	　　　　　　梅甘&middot;福克斯 Megan Fox<br />
	　　　　　　瑞切尔&middot;泰勒 Rachael Taylor .....Maggie<br />
	　　　　　　Rachel Taylor .....Maggie<br />
	　　　　　　安东尼&middot;安德森 Anthony Anderson .....Glen<br />
	　　　　　　约翰&middot;特托罗 John Turturro .....Agent Simmons</p>
<p>
	<br />
	◎简　　介　</p>
<p>
	19世纪初，北极圈内：</p>
<p>
	　　Archibald Witwicky船长(维特维奇家族的先祖)在一次灾难中随着巨大的冰块落入深渊，落到了埋藏在冰层之下的一个机器人手掌上。船长醒来后发现机器人的眼睛正注视着他。而这台机器人正是很久以前离开塞伯坦，前往地球寻找火种源(Allspark)的威震天(Megatron)&hellip;&hellip;</p>
<p>
	　　威震天将揭示火种源下落的地图烧刻在船长的眼镜上。眼镜作为船长的遗物一代一代地传到了萨姆(Shia LaBeout饰演)的手里&hellip;&hellip;</p>
<p>
	　　现代社会：</p>
<p>
	　　中东卡塔尔的某个美国空军基地遭到了狂派战士眩晕(Blackout)，他将这个基地完全毁掉，而且还从一台计算机里获得了大量信息。此外，眩晕还释放了巨蝎怪(Scorponok)去追杀Lennox上尉和他的特别行动小队。Lennox上尉与五角大楼取得了联系，美国军方派遣一架战斗机暂时打退了狂派的小规模进攻。</p>
<p>
	　　萨姆&middot;维特维奇(Sam Witwicky)从汽车商手里买到了他的第一辆车，而这辆车恰恰是博派的大黄蜂(Bumblebee)。大黄蜂帮助萨姆赢得了Mikaela的芳心。博派前来寻找Archibald　老船长的眼镜，他们被迫躲藏在萨姆家的后院，因为凶恶的第七防区(Sector 7)的特工突然闯进了萨姆的家&hellip;&hellip;</p>
<p>
	　　影片将会采用五条故事线平行推进，最终汇总的形式。在影片的结尾会有一场博派领袖擎天柱(Optimus Prime)与狂派首领威震天的惊天大战。他们将从胡佛大坝一直杀到洛杉矶&hellip;&hellip;</p>
<p>
	幕后制作：</p>
<p>
	【拍摄缘由】</p>
<p>
	　　2003年，制片人Don Murphy原本想在伊拉克战争爆发后拍摄一部《特种部队G.I.Joe》的电影，但他最终和孩之宝(Hasbro)公司洽谈的却是《变形金刚》的改编权。Tom DeSanto在《X-超人》的出色编剧能力另Don颇为赏识，于是DeSanto就被请来构思最基本的故事主线。同时，Don也在他的个人网站上与众多美国变形金刚迷友讨论这部电影。DeSanto在研究了大量变形金刚动画、漫画后，由衷地感慨道：&ldquo;变形金刚里的人物，虽然大多数是机器人，但个个有血有肉、个性十足&rdquo;，&ldquo;如果能在银屏上展示一辆卡车变形为20英尺高的机器人，那一定是一件前无古人的事情&rdquo;。</p>
<p>
	　　所谓英雄所见略同，梦工厂的斯皮尔伯格(Steven Spielberg)和Lorenzo di Bonaventura对此也有相同的看法。斯皮尔伯格对变形金刚一直很了解，因为在他的孩子小的时候，斯皮尔伯格就经常购买变形金刚玩具给他们玩耍。他认为&ldquo;变形金刚这个概念，足以孕育出一部写实电影&rdquo;。为了改编好Tom DeSanto的基本故事，多名职业电影编剧被请来进一步丰富故事的框架。其中包括Roberto Orci，Alex Kurtzman和John Rogers。甚至连斯皮尔伯格本人也对剧本发表了意见。</p>
<p>
	　　当制片人方刚开始与迈克尔&middot;贝就导演一职进行谈判时，迈克尔&middot;贝觉得这部电影只是一部&ldquo;愚蠢的玩具电影&rdquo;。不过，迈克尔&middot;贝并没有马上拒绝这个邀请，他仔细研究了一下&ldquo;变形金刚&rdquo;系列的来龙去脉，并在2005年四月正式确定担任导演。于是，真人电影风格的变形金刚造型设计也相应地开始了。</p>
<p>
	【名词注解】</p>
<p>
	　　Transformers变形金刚(简称为TF或金刚)</p>
<p>
	　　来自塞伯坦星球Cybertron　的超机械生命体，和一般意义上的&ldquo;人造智能机器人&rdquo;有着本质区别。可以就生存或者战略的需要而把自己的外貌改变为其他事物。他们因意识形态的不同而分裂为两派：博派Aubobot和狂派Decepticon。并以赋予他们生命的火种源Allspark为矛盾焦点，爆发了战争。在对这个种族拥有充分了解之前，人类的秘密军事组织&ldquo;第七防区&rdquo;把他们称为N.B.E.(非生物存在体　Non Biological Entity)。</p>
<p>
	　　为了尽可能体现电影的可信性，在本次，&ldquo;外星机械生命体&rdquo;这个最基础的本质被前所未有地重视。&ldquo;外星人&rdquo;、 &ldquo;alien&rdquo;、&ldquo;异型&rdquo;在外貌上对于我们地球　人来说或许是狰狞可怕的；不过对于他们来说，我们何尝不是脆弱丑陋的纤维包肉团呢？除去外壳，放眼于内在的那颗心，或许对于彼此来说都是一样的熟悉亲切。</p>
<p>
	　　Allspark　火种源</p>
<p>
	　　所谓火种(Spark)就相当于变形金刚的灵魂。在最早的故事中，火种源(Allspark)　是变形金刚火种的来源和归宿地。而电影这里，除了原来的灵魂作用外还包括了提供energon(供变形金刚吸收的能源)的功能。其外形就是一个古怪的正方体。</p>
<p>
	　　Cybertron　塞伯坦</p>
<p>
	　　变形金刚永远的的故乡、母星。曾经因为火种源的到来而辉煌繁荣，但又因为火种源而被卷入长久的战争中，后来还因为与火种源的分离而面临毁灭的危机。在第一部电影中我们对塞伯坦的认识还不多，究竟它的过去和未来会是如何呢？和火种源又有着什么联系呢？</p>
<p>
	　　Protoform　原生体形态</p>
<p>
	　　为了方便在宇宙中独自航行，变形金刚会拟态为彗星的外形。坠落到目的地后会立即扫描当地的机械或者生物，并通过变形来隐藏自己。</p>
<p>
	　　Battle Mode　战斗模式</p>
<p>
	　　变形金刚们在准备进入战斗时，头部会独自变形(例如盖上口罩、面具、额外的装甲等)。所以，真人电影变形金刚的面部造型有两种，普通模式和战斗模式。</p>
<p>
	　　The Sector-Seven　&ldquo;第七防区&rdquo;组织</p>
<p>
	　　人类组织，由美国政府秘密建立，有七名创始人--&ldquo;The First Seven&rdquo;。这些人很清楚变形金刚的存在，但一直把此事向外界保密。他们的职责就是研究这种外星生命，消除一切潜在或者已经出现的威胁。</p>
<p>
	花絮：</p>
<p>
	&middot;迈克尔&middot;贝指导下的机器人造型设计具有鲜明的风格，格外强调机器人运动学和现实工程技术的表现张力。为了增强真实感，迈克尔&middot;贝抛弃了机器人方方正正的块状造型，代之以具有数目众多的细节部件的机器人造型。</p>
<p>
	&middot;在一次变形过程中，机器人的数千块元件会同时运动，从而避免了变形金刚动画片中变形金刚的体积和质量可以随意变小变大这一较难用日常物理解释的现象。此外，风格独特的变形金刚造型也着重显示出了他们来自外星这一根本的特质。</p>
<p>
	&middot;影片的主要实景拍摄开始于2006年五月22日。租用了大量美军的军事交通工具。拍摄地点从胡佛大坝到五角大楼，从加州大城市洛杉矶到加州小城镇若尔图(Rialto)，还在多个美国空军基地辗转，将无数惨烈的宏大场面收入镜头中。</p>
<p>
	&middot;实景拍摄于2006年十月5日结束。</p>
<p>
	&middot;迈克尔&middot;贝在2006年圣诞节期间完成了第一版剪辑片。特效镜头也基本上由工业光魔(ILM)完成。配音和其他后期工作目前正在进行中。</p>
<p>
	&middot;为了宣传好这部真人电影，孩之宝公司也下了很大的手笔，与70多个国家的200多个公司签订了协议。</p>
<p>
	&middot;2006年6月29日，真人电影的第一部预告片在互联网上正式公布。这段片子主要展现了变形金刚攻击欧洲火星探测器小猎犬二号的情节。该预告片主要起到&ldquo;正式公告&rdquo;的作用，画面和情节都不会出现在真正的影片中。</p>
<p>
	&middot; 为了与美国变形金刚迷友界取得紧密互动，派拉蒙举行了一个&ldquo;擎天柱台词竞赛&rdquo;的活动，请迷友为电影中的擎天柱撰写台词，最终获胜者撰写的台词将会出现在影片中。最终&ldquo;自由权利归众生&rdquo;(Freedom is the right of all sentient beings)这一台词获胜。这句话实际上也是擎天柱玩具上的原始座右铭。</p>
<p>
	&middot;2006年十二月20日，真人电影的第二部预告片出现在互联网上。该片反响很大，点击量一下子就突破了《蜘蛛侠3》的纪录。</p>
<p>
	&middot;2007年二月13日，在纽约的玩具展销会上，展示了大约20分钟长的电影片断。片断包括眩晕袭击卡塔尔的基地，萨姆在大黄蜂的帮助下与Mikaela的浪漫约会，在第七防区的特工到来之前呆在萨姆家中的博派以及巨蝎怪与美军的战斗，在观众中反映非常好。</p>
<p>
	&middot; 美国IDW漫画公司从2007年三月起陆续出版变形金刚真人电影的四卷本漫画前传。故事主要反映大黄蜂从塞伯坦星球来到现代地球的经过，威震天来地球寻找火种源的经过以及第七防区的起源。作家Alan Foster将为真人电影撰写前传小说《昨日幽灵》(Ghosts of Yesterday)以及真人电影的小说版。除此之外，还有一些面向低龄儿童的真人电影故事丛书。这些图书都会在真人电影公映前陆续出版，为真人电影的故事营造丰富的前传背景。</p>
<p>
	&middot;Activision正在制作真人电影的对应游戏&ldquo;The Transformers：The Game&rdquo;。该游戏将同时登陆PSP，PS2，PS3，X-Box 360，Wii等主流游戏平台。游戏者可以扮演博派或者狂派中的任何一方，体会不同的乐趣。</p>
<p>
	&middot;计划中的续集有两集之多。演员Shia LaBeouf和配音Peter Cullen已经正式签约。一个新的主要人物，例如声波(Soundwave)和震荡波(Shockwave)</p>

<p>
	【译　　名】变形金刚2:卷土重来/狂派的反击/复仇之战/堕落者的复仇<br />
	【又　　名】变形金刚2：堕落者的复仇<br />
	【英 文 名】Transformers: Revenge of the Fallen<br />
	【发　　行】梦工厂（派拉蒙）DreamWorks Pictures (Paramount)<br />
	【年　　代】2009年<br />
	【国家地区】美国<br />
	【类　　别】动作/冒险/科幻<br />
	【上映时间】2009年6月24日<br />
	【片　　长】150 min<br />
	【电影语言】国语配音<br />
	【字幕语言】中文</p>
<p>
	【视频尺寸】1024x516<br />
	【文件格式】RMVB<br />
	【IMDB评分】7.0/10 (9,455 votes)<br />
	【分　　级】美国PG-13<br />
	【编　　剧】Ehren Kruger 艾里克斯&middot;库兹曼 Alex Kurtzman 罗伯托&middot;奥利奇 Roberto Orci<br />
	【导　　演】迈克尔&middot;贝 Michael Bay<br />
	【主　　演】希亚&middot;拉博夫 Shia LaBeouf ....Sam Witwicky<br />
	　　　　　　梅根&middot;福克斯 Megan Fox ....Mikaela Banes<br />
	　　　　　　乔什&middot;杜哈明 Josh Duhamel ....Captain Lennox<br />
	　　　　　　雨果&middot;维文 Hugo Weaving ....Megatron (voice)<br />
	　　　　　　约翰&middot;特托罗 John Turturro ....Agent Simmons / Voice of Jetfire<br />
	　　　　　　雷恩&middot;威尔森 Rainn Wilson ....College Professor<br />
	　　　　　　伊莎贝尔&middot;卢卡斯 Isabel Lucas ....Alice<br />
	　　　　　　America Olivo ....Frisbee Girl<br />
	　　　　　　泰瑞斯&middot;吉布森 Tyrese Gibson ....USAF Tech Sergeant Epps<br />
	　　　　　　弗兰克&middot;维尔克 Frank Welker ....Soundwave (voice)<br />
	　　　　　　Peter Cullen ....Optimus Prime (voice)<br />
	　　　　　　Mark Ryan ....Bumblebee (voice)<br />
	　　　　　　Darius McCrary ....Jazz (voice)<br />
	　　　　　　马修&middot;马斯登 Matthew Marsden ....Graham<br />
	　　　　　　Samantha Smith ....Sarah Lennox<br />
	　　　　　　格伦&middot;莫肖尔 Glenn Morshower ....General Morshower<br />
	　　　　　　拉蒙&middot;罗德里格兹 Ramon Rodriguez ....Leo<br />
	　　　　　　凯文&middot;杜恩 Kevin Dunn ....Ron Witwicky<br />
	　　　　　　艾伦&middot;希尔 Aaron Hill ....Frat Guy #1<br />
	　　　　　　Reno Wilson ....Frenzy (voice)<br />
	　　　　　　Charles Adler ....Starscream (voice)<br />
	　　　　　　罗伯特&middot;福克沃斯 Robert Foxworth ....Ratchet (voice)<br />
	　　　　　　杰斯&middot;哈梅尔 Jess Harnell ....Ironhide / Barricade (voice)<br />
	　　　　　　Julie White ....Judy Witwicky<br />
	　　　　　　Mike Patton ....Mixmaster (voice)<br />
	　　　　　　迈克尔&middot;帕帕约翰 Michael Papajohn ....Cal<br />
	　　　　　　Katie Lowes ....April the R.A.<br />
	　　　　　　Jareb Dauplaise ....College Frat Guy<br />
	　　　　　　John Benjamin Hickey ....Galloway<br />
	　　　　　　Peter Jason ....Ceo<br />
	　　　　　　Karina Michel ....Reporter<br />
	　　　　　　Spencer Garrett ....Air Force Chief of Staff McCain<br />
	　　　　　　乔纳森&middot;特兰 Jonathon Trent ....Fasbinder<br />
	　　　　　　Caitlin Dulany ....CNN reporter<br />
	　　　　　　Michael Benyaer ....Egyptian Interpol<br />
	　　　　　　Alex Fern&aacute;ndez ....Lt. Colonel Cetas - Joint Chiefs Aide<br />
	　　　　　　Steve Tom ....McClaren Robotics CEO<br />
	　　　　　　Josh Kelly ....Strike Force Member #4<br />
	　　　　　　Rick Cramer ....Diego Garcia #1<br />
	　　　　　　Derek Alvarado ....Joint Op #1<br />
	　　　　　　Kortney Nash ....Mozambiqua<br />
	　　　　　　Howard Walker ....Sharsky<br />
	　　　　　　John Nielsen ....Captain Wilder<br />
	　　　　　　Cornell Womack ....FBI Director<br />
	　　　　　　Sean T. Krishnan ....Yakov<br />
	　　　　　　Kamal Jones ....Smithsonian Guard 2<br />
	　　　　　　Donald Sage Mackay ....Nuclear Submarine Captain<br />
	　　　　　　Jayson Floyd ....Strike Force Member #3<br />
	　　　　　　Joel Lambert ....Strike Force Member #2<br />
	　　　　　　Casey Nelson ....Joint Op #2<br />
	　　　　　　James Harvey Ward ....Sonarman<br />
	　　　　　　Zhubin Rahbar ....Officer<br />
	　　　　　　Ralph Meyering Jr. ....NORAD General<br />
	　　　　　　David Paul Olsen ....Strike Force Member #5<br />
	　　　　　　Jennifer Alden ....Tour Guide (uncredited)<br />
	　　　　　　Kaily Alissano ....College Student (uncredited)<br />
	　　　　　　Cas Anvar ....Egyptian Interpol #1 (uncredited)<br />
	　　　　　　Robert Bizik ....Maitre d&#39; (uncredited)<br />
	　　　　　　Ted Borodaeff ....Mime (uncredited)<br />
	　　　　　　Krista Boshinski ....Pedestrian 2 (uncredited)<br />
	　　　　　　Jerome Ro Brooks ....Guard #5 (uncredited)<br />
	　　　　　　Anthony C. Brown ....Paris Restaurant Patron (uncredited)<br />
	　　　　　　Lee Burkett ....Man in Street (uncredited)<br />
	　　　　　　John Sterling Carter ....CNN Reporter (uncredited)<br />
	　　　　　　Larry Carter ....Security Guard 3 (uncredited)<br />
	　　　　　　Charles Chen ....Mandarin Blogger (uncredited)<br />
	　　　　　　Arnold Chun ....Diego Garcia #2 (uncredited)<br />
	　　　　　　Robert Radlach ....U.S. Congressman (uncredited)<br />
	　　　　　　Shaun Paul Costello ....Pedestrian 1 (uncredited)<br />
	　　　　　　Nick Dash ....FBI Agent (uncredited)<br />
	　　　　　　Victor Harris ....Pentagon worker (uncredited)<br />
	　　　　　　Elbert Traister ....Mandarin Blogger (uncredited)<br />
	　　　　　　Katy Marie Johnson ....Towel Hottie (uncredited)<br />
	　　　　　　Ian Michael Kintzle ....Indie College Guy (uncredited)<br />
	　　　　　　Nora Kirkpatrick ....Beautiful girl (uncredited)<br />
	　　　　　　Mark Kratzer ....Butcher (uncredited)<br />
	　　　　　　Sebastian Lionell ....Soldier (uncredited)<br />
	　　　　　　Aaron Lustig ....CNN reporter (uncredited)<br />
	　　　　　　Yvonne Lu ....Female mandarin blogger (uncredited)<br />
	　　　　　　Pablo Macho Maysonet IV ....College Frat Student (uncredited)<br />
	　　　　　　Sashen Naicker ....Bedouin (uncredited)<br />
	　　　　　　Aaron Norvell ....Air Force Military Police #1 (uncredited)<br />
	　　　　　　Kal Parekh ....Bedouin (uncredited)<br />
	　　　　　　Mark J. Parker ....Parisian #1 (uncredited)<br />
	　　　　　　Charles Pendleton ....News Stand Patron (uncredited)<br />
	　　　　　　Geoffrey M. Reeves ....Strike Team Member (uncredited)<br />
	　　　　　　Anne Reiss ....College Student (uncredited)<br />
	　　　　　　Vincent Riviezzo ....Professor (uncredited)<br />
	　　　　　　Jarrod W. Robbins ....Congressman (uncredited)<br />
	　　　　　　Jason Roehm ....Joint Op #4 (uncredited)<br />
	　　　　　　Jason Sandler ....College Student (uncredited)<br />
	　　　　　　Richard Schimmelpfenneg ....Member of House of Representatives (uncredited)<br />
	　　　　　　Jennifer Wiener ....Mom at College (uncredited)<br />
	　　　　　　Yvetta Young ....Member - House of Representatives (uncredited)<br />
	　　　　　　安东尼&middot;安德森 Anthony Anderson ....Jolt (voice)<br />
	　　　　　　托尼&middot;托德 Tony Todd ....The Fallen (voice)<br />
	　　　　　　Tom Kenny ....Mudflap / Skids (voice)</p>

<p>
	【简　　介】</p>
<p>
	　　距离那场举世震惊的大战已经过去了数年，虽然美国政府宣布此事只是一场与外星人无关的恐怖袭击，但大部分人都明白，这不过只是政府掩盖事实真相的一昧说辞。擎天柱（皮特&middot;库林配音）等变形金刚继续生活在地球上，与人类和平共处，山姆（希亚&middot;拉博夫饰）也已经顺利读完高中，即将进入大学生涯，而米凯拉（梅根&middot;福克斯饰）就没有那么幸运了，异地恋的结果则是山姆把大黄蜂（马克&middot;瑞恩配音）留给了米凯拉。踏进大学校园，山姆对一切事物都感到新鲜，而且还认识了一个漂亮的女同学爱丽丝（伊莎贝尔&middot;卢卡斯饰）。不过在全新的环境里没生活多久的他又陷入了一个令他头疼的境地，他的脑海里常常出现一些莫名其妙的符号，而且似乎冥冥里来自遥远星球的一个声音正在召唤着他&hellip;&hellip;<br />
	　　山姆把这些事情告诉了擎天柱，无奈之下擎天柱告诉了他一个一直隐瞒着的秘密：变形金刚的起源来自于火种源魔方创造的13个变形金刚，而这群变形金刚创造了一种叫做领导模块的东西，它可以无限的吸取太阳的能量，而领导模块也引起了变形金刚的内斗，其中一个名叫堕落金刚的想把它据为己有。为了避免领导模块引起宇宙灾难，初代变形金刚将它藏在了宇宙的某个地方，而堕落金刚一直没有放弃过寻找领导模块，如今，地球成了他的寻找目标。而关于领导模块的秘密，则同山姆手中的火种源碎片有关，里面记载了远古时期变形金刚到访地球的种种线索，而他们前来地球，似乎就是为了留下一张藏宝图，而这藏宝图上记载的，就是领导模块的下落。<br />
	　　山姆与擎天柱将此事告知美国政府，同时博派也做好了战斗准备，严阵以待堕落金刚的到来，全球各国亦罕有的同时联合起来；在另一边，狂派的迷乱（里诺&middot;威尔逊配音）从美国军方基地里偷走了火种源的碎片，用于威震天（雨果&middot;维文配音）的复活。威震天与杀到地球的堕落金刚一起开始大举进攻人类，而这时候山姆也发现，一直以来对他大抛媚眼的爱丽丝，原来也是一个机器人，由于对这一点始料未及，山姆从而陷入了威震天之手。威震天逼迫山姆说出领导模块的下落，为了救出山姆，擎天柱决定用自己的生命来换取山姆的自由，因为还有更重要的事等着山姆去做&hellip;&hellip;</p>

<p>
	◎译　　名　变形金刚3/变形金刚3:月黑之时/变形金刚3:黑月降临(港)<br />
	◎片　　名　Transformers Dark Of The Moon<br />
	◎年　　代　2011<br />
	◎国　　家　美国<br />
	◎类　　别　动作/冒险/科幻<br />
	◎语　　言　正版国语配音中字</p>
<p>
	◎文件格式　XviD + MP3<br />
	◎视频尺寸　1024 x 576<br />
	◎文件大小　1CD<br />
	◎片　　长　157 Mins<br />
	◎导　　演　迈克尔&middot;贝 Michael Bay<br />
	◎主　　演　希亚&middot;拉博夫 Shia LaBeouf&nbsp; ....Sam Witwicky<br />
	　　　　　　罗茜&middot;汉丁顿-惠特莉 Rosie Huntington-Whiteley&nbsp; ....Carly<br />
	　　　　　　乔什&middot;杜哈明 Josh Duhamel&nbsp; ....Major William Lennox<br />
	　　　　　　泰瑞斯&middot;吉布森 Tyrese Gibson&nbsp; ....Robert Epps<br />
	　　　　　　雨果&middot;维文 Hugo Weaving&nbsp; ....Megatron (voice)<br />
	　　　　　　伦纳德&middot;尼莫伊 Leonard Nimoy&nbsp; ....Sentinel Prime (voice) (rumored)<br />
	　　　　　　帕特里克&middot;德姆西 Patrick Dempsey&nbsp; ....Dylan<br />
	　　　　　　约翰&middot;马尔科维奇 John Malkovich&nbsp; ....Bruce<br />
	　　　　　　肯&middot;郑 Ken Jeong<br />
	　　　　　　弗兰西斯&middot;麦克多蒙德 Frances McDormand&nbsp; ....Marissa Faireborn<br />
	　　　　　　艾伦&middot;图代克 Alan Tudyk&nbsp; ....Dutch<br />
	　　　　　　约翰&middot;特托罗 John Turturro&nbsp; ....Simmons<br />
	　　　　　　弗兰克&middot;维尔克 Frank Welker&nbsp; ....Soundwave (voice)<br />
	　　　　　　汤姆&middot;肯尼 Tom Kenny&nbsp; ....Wheelie (voice)<br />
	　　　　　　彼特&middot;库伦 Peter Cullen&nbsp; ....Optimus Prime (voice)</p>
<p>
	◎简　　介　</p>
<p>
	　　第三集里,擎天柱将率领着&ldquo;汽车人&rdquo;继续与第二集失败后卷土重来的&ldquo;霸天虎&rdquo;作战。&ldquo;汽车人&rdquo;与&ldquo;霸天虎&rdquo;被卷入了美苏之间危险的&ldquo;太空竞赛&rdquo;中,地球人山姆又一次要向他的机器人朋友们伸出援助之手。这一集中将会有新的变形金刚登场,包括大反派&ldquo;震荡波(Shockwave)&rdquo;,他在汽车人与霸天虎来到地球鏖战时接管了塞伯坦星球。</p>
<p>
	一句话评论</p>
<p>
	　　惊人的动作场面。 &mdash;&mdash;娱乐在线</p>
<p>
	　　科幻电影里最壮观的一幕出现了。 &mdash;&mdash;《纽约时报》</p>
<p>
	　　故事简单,场面壮观。 &mdash;&mdash;《娱乐周刊》<br />
	花絮<br />
	　　据国外媒体报道，《变形金刚3：月黑之时》（Transformers: Dark of the Moon）将于2011年7月1日上映，某节目前往该片芝加哥片场，带来了不少新鲜的一手资料。<br />
	　　在《变形金刚3》中，希亚&middot;拉伯夫（Shia LaBeouf）所饰演的萨姆（Sam Witwicky）因为两次协助博派汽车人击败狂派飞机人，而成为国家英雄。不过萨姆渴望回归到普通人的生活，并找一个真正爱他这个人，而不只是因为他头上的光环而追他的女孩。幸运的是，他找到了这样的女孩，就是&ldquo;维多利亚秘密&rdquo;内衣模特罗西&middot;汉丁顿&middot;惠特莉（Rosie Huntington-Whiteley）所饰演的卡莉（Carly）。<br />
	　　然而喜欢卡莉的可不止萨姆，卡莉的老板&mdash;&mdash;帕特里克&middot;德姆西（Patrick Dempsey）饰演&mdash;&mdash;也爱上了她，三人展开了一段三角关系。 不过迈克尔&middot;贝（Michael Bay）是不会把他的电影变成争风吃醋的战场的，《变形金刚3》里的战斗依然火爆，仅芝加哥壮丽大道（Magnificent Mile）一场戏，他就动用了200辆废弃汽车，沿着破碎的沥青路面大片堆积，那场面甚是壮观。<br />
	　　尽管依然有爆炸、烟火、军队的直升机，迈克尔&middot;贝这次却特别强调故事。&ldquo;我觉得这次的故事非常丰富&rdquo;，他说，&ldquo;有一种老式电影的风格，就像间谍版的&lsquo;变形金刚&rsquo;&rdquo;。<br />
	　　这次《变形金刚3》使用了3D摄影机，对此主演希亚&middot;拉伯夫还有点不太适应。&ldquo;我不是为3D准备的&rdquo;，他开玩笑说，&ldquo;我是个2D人，你看我长着典型的犹太人鼻子，这用3D拍出来可不好看&rdquo;。<br />
	　　《变形金刚3》将于2011年7月1日上映，希亚&middot;拉伯夫信心满满的说：&ldquo;这是我们拍得最好的一部《变形金刚》，我们有最好的场景、最好的剧本，还有更多的时间拍摄和准备&hellip;&hellip;我们已经吸取教训，它将是一部强的多的电影。&rdquo;<br />
	&nbsp;</p>
<p>
	[下载地址]： &nbsp;<img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" /></p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3018/飘花电影piaohua.com变形金刚1-BD国语配音中字1024高清.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3018/飘花电影piaohua.com变形金刚1-BD国语配音中字1024高清.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3018/飘花电影piaohua.com变形金刚2-BD国语配音中字1024高清.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3018/飘花电影piaohua.com变形金刚2-BD国语配音中字1024高清.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3018/飘花电影piaohua.com变形金刚3-BD国语配音中字1024高清.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3018/飘花电影piaohua.com变形金刚3-BD国语配音中字1024高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O14bN20-229D.jpg{/dede:field}
