{dede:field name='keywords'}林中小屋(尸营旅舍)(诡屋)清晰TS{/dede:field}
{dede:field name='description'}林中小屋(尸营旅舍)(诡屋)清晰TS中字2012最新美国恐怖悬疑惊悚大迅雷下载、免费下载，林中小屋(尸营旅舍)(诡屋)清晰TS中字2012最新美国恐怖悬疑惊悚大Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}林中小屋(尸营旅舍)(诡屋)清晰TS中字2012最新美国恐怖悬疑惊悚大{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-01{/dede:field}
{dede:field name='body'}<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120501/13/56643687201205011350444175114473116_003.jpg" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120501/13/56643687201205011350444175114473116_004.jpg" /></p>
<p>
	◎译　　名　林中小屋 / 尸营旅舍(港) / 诡屋(台) / 林中屋<br />
	◎片　　名　The Cabin in the Woods<br />
	◎年　　代　2012<br />
	◎国　　家　美国<br />
	◎类　　别　悬疑/惊悚/恐怖<br />
	◎语　　言　英语<br />
	◎字　　幕　中字<br />
	◎IMDB评分 7.9/10 (1686 votes)<br />
	◎文件格式　清晰TS-RMVB<br />
	◎视频尺寸　640 x 264<br />
	◎文件大小　1CD 450MB<br />
	◎片　　长　89 mins<br />
	◎导　　演　德鲁&middot;高达 Drew Goddard<br />
	◎主　　演　理查德&middot;詹金斯 Richard Jenkins .... Steve Hadley<br />
	布拉德利&middot;威特福德 Bradley Whitford .... Richard Sitterson<br />
	杰西&middot;威廉斯 Jesse Williams .... Holden McCrea<br />
	克里斯&middot;海姆斯沃斯 Chris Hemsworth .... Curt Vaughan<br />
	Fran Kranz .... Marty Mikalski<br />
	Kristin Nora Connolly .... Dana Polk<br />
	Anna Hutchison .... Jules Louden<br />
	布莱恩&middot;怀特 Brian J. White .... Alex TrumanBrian White)<br />
	Amy Acker .... Wendy Lin<br />
	乔黛尔&middot;弗兰 Jodelle Ferland .... Patience Buckner<br />
	莫尼克&middot;格兰德顿 Monique Ganderton .... Woman inwoods<br />
	Thomas Lenk .... Ronald<br />
	Chelah Horsdal .... Demo Girl<br />
	Terry Chen .... Story Editor<br />
	Dan Payne .... Mathew Buckner<br />
	阿德里安&middot;霍尔莫斯 Adrian Holmes .... Demo#2<br />
	理查德&middot;盖特罗内 Richard Cetrone .... Merman<br />
	Maya Massar .... Mother Buckner<br />
	Nels Lennarson .... Clean man<br />
	Maja Stace-Smith .... Glass Smash Girl</p>
<p>
	◎简　　介　</p>
<p>
	　　一群喧闹的大学生来到了人迹罕至的小树林里，这五个朋友准备在这里度过一个放纵、开心、难忘的周末。根据指示，他们找到了位于树林深处的一个小木屋，准备在这里开始自己的派对。<br />
	　　一开始，一切都很正常，但是到了晚上，这个小木屋里却接连出现了各种各样奇怪的超自然的以及无法解释的事情。而这五个大学生的性命也处在了危难之中--因为他们根本不知道自己面对的是什么，而这些背后还有一个多么庞大的组织在监视这这一切&hellip;&hellip;</p>

<p>
	◎影片截图</p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120501/13/56643687201205011350444175114473116_002.jpg" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120501/13/56643687201205011350444175114473116_000.jpg" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120501/13/56643687201205011350444175114473116_001.jpg" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.net" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3330/飘花电影piaohua.com林中小屋(尸营旅舍)(诡屋)清晰TS中字.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3330/飘花电影piaohua.com林中小屋(尸营旅舍)(诡屋)清晰TS中字.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1564X20-35394.jpg{/dede:field}
