{dede:field name='keywords'}理发师陶德/恶魔理发师/疯狂理发{/dede:field}
{dede:field name='description'}理发师陶德/恶魔理发师/疯狂理发师高清中英双字BD1280迅雷下载、免费下载，理发师陶德/恶魔理发师/疯狂理发师高清中英双字BD1280Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}理发师陶德/恶魔理发师/疯狂理发师高清中英双字BD1280{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-02-09{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://dy241:xiaobajie@222.187.221.241:2011/小八戒电影xiaobajie.com理发师陶德BD中英双字1280高清.rmvb" target="_blank{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MP2913F-3Pa.jpg{/dede:field}
