<?php
$z[0]=Array("field","理发师陶德/恶魔理发师/疯狂理发",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","理发师陶德/恶魔理发师/疯狂理发师高清中英双字BD1280迅雷下载、免费下载，理发师陶德/恶魔理发师/疯狂理发师高清中英双字BD1280Gvod高清在线播放，剧情介绍等。",73,267);
$z[1][4]['name']="description";
$z[2]=Array("field","理发师陶德/恶魔理发师/疯狂理发师高清中英双字BD1280",269,357);
$z[2][4]['name']="title";
$z[3]=Array("field","",359,398);
$z[3][4]['name']="writer";
$z[4]=Array("field","",400,439);
$z[4][4]['name']="source";
$z[5]=Array("field","2012-02-09",441,491);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",493,530);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://dy241:xiaobajie@222.187.221.241:2011/小八戒电影xiaobajie.com理发师陶德BD中英双字1280高清.rmvb\" target=\"_blank",532,686);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MP2913F-3Pa.jpg",688,769);
$z[8][4]['name']="litpic";

?>