{dede:field name='keywords'}2012世界末日[BD中字1024x576高{/dede:field}
{dede:field name='description'}2012世界末日[BD中字1024x576高清版]迅雷下载、免费下载，2012世界末日[BD中字1024x576高清版]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}2012世界末日[BD中字1024x576高清版]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2010-03-14{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://4e:4e@www2.3edyy.com:3869/【3E电影院www.3edyy.com】2012世界末日BD中字1024x576高清版CD1.rmvb" target="_blank{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MPXI30-24911.jpg{/dede:field}
