{dede:field name='keywords'}黑鹰坠落/黑鹰计划BD中英双字102{/dede:field}
{dede:field name='description'}黑鹰坠落/黑鹰计划BD中英双字1024/1280高清迅雷下载、免费下载，黑鹰坠落/黑鹰计划BD中英双字1024/1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}黑鹰坠落/黑鹰计划BD中英双字1024/1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-12-09{/dede:field}
{dede:field name='body'}<p>
	◎译　　名　《黑鹰计划/黑鹰坠落》超真实火暴战争动作大片DVD中英双字800+1024x576高清版（附国语中字版）<br />
	◎片　　名　Black Hawk Down<br />
	◎年　　代　2001<br />
	◎国　　家　美国<br />
	◎类　　别　动作/剧情/战争<br />
	◎语　　言　英语<br />
	◎字　　幕　中英字幕<br />
	◎IMDB评分 7.6/10 (42,555 votes)<br />
	◎文件格式　Bluray-RMVB<br />
	◎视频尺寸　1024 x 576、800x336 (2.38:1)<br />
	◎文件大小　1CD 2.03G<br />
	◎片　　长　02:31:51<br />
	◎导　　演　雷德利&middot;斯科特 Ridley Scott<br />
	◎主　　演　伊万&middot;麦格雷戈 Ewan McGregor .... Spec. John Grimes<br />
	　　　　　　威廉&middot;菲德内尔 William Fichtner .... Sfc. Jeff Sanderson<br />
	　　　　　　乔许&middot;哈奈特 Josh Hartnett .... SSgt. Matt Eversmann<br />
	　　　　　　山姆&middot;夏普德 Sam Shepard .... Maj. Gen William F. Garrison<br />
	　　　　　　汤姆&middot;西斯摩尔 Tom Sizemore .... Lt. Col. Danny McKnight<br />
	　　　　　　艾文&middot;布莱纳 Ewen Bremner .... Spec. Shawn Nelson<br />
	　　　　　　詹森&middot;艾萨克 Jason Isaacs .... Capt. Mike Steele<br />
	　　　　　　Boyd Kestner .... CWO Mike Goffena<br />
	　　　　　　杰里米&middot;皮文 Jeremy Piven .... CWO Cliff &#39;Elvis&#39; Wolcott<br />
	　　　　　　恩里克&middot;莫西亚诺 Enrique Murciano .... Sgt. Lorenzo Ruiz<br />
	　　　　　　Razaaq Adoti .... Yousuf Dahir Mo&#39;alim<br />
	　　　　　　艾里克&middot;巴纳 Eric Bana .... Sfc. Norm &quot;Hoot&quot; Gibson<br />
	　　　　　　Chris Beetem .... Sgt. James &#39;Casey&#39; Joyce<br />
	　　　　　　奥兰多&middot;布鲁姆 Orlando Bloom .... Pfc. Todd Blackburn<br />
	　　　　　　Ty Burrell .... Tim &#39;Wilkie&#39; Wilkinson<br />
	<br />
	【剧情简介】：</p>
<p>
	　　影片忠实还原了1993年索马里战事。本片改编自一个真实的故事，故事发生在1993年10月3日，地点是在政局动荡的非洲国家索马里的首都：摩加迪沙。由美国陆军三角洲部队和游骑兵部队的120名特种精英组成的特别行动小组受命深入摩加迪沙完成双重使命：为当地群众提供人道主义援助，同时捉拿索马里军事的两名高级将领。</p>
<p>
	　　意外发生了，由于准备不足和情报错误，美军陷入了包围。更遭的是，两架运送美军的黑鹰直升机被索马里军队击落，一场原本计划1小时完成的秘密任务衍生成战争事件。其中一架黑鹰上的全部官兵当场死亡，另一架黑鹰的驾驶员陷入索马里军队控制区。被隔绝在摩加迪沙街头的美军一方面焦急地等待救援部队，一方面又要想办法解救黑鹰上的队友。</p>
<p>
	　　黑夜渐渐降临。在充满敌意的城市中，这一小队美军仿佛风雨飘摇中的孤舟，随时会遭遇灭顶之灾。数量不到百人的美军突击队必须对抗5000名以上索马里军人的猛烈攻击，在人数和火力相差50倍的紧张情势下，一场无可避免的战役展开。他们与索马里军队发生了激战，结果美军有18人阵亡，73人受伤，索马里军队有上百人阵亡。一场原本计划1小时完成的突击行动，变成了15小时的漫长煎熬。堆积如山的弹壳洒落在战场上。</p>
<p>
	　　经验丰富的三角洲部队老兵和年轻的游骑兵部队官兵在并肩作战的过程中，弥补了彼此之间的隔阂，领悟到战友之间生死之交的兄弟情谊，也感受到战争的残酷。摩加迪沙之战是美国自越南战争以来持续时间最长的一次地面战争，伤亡也最惨重。美军增员前往救援，并坚持&ldquo;无论生死，所有弟兄都要回来，决不放弃任何一个同胞&rdquo;。</p>

<p>
	【幕　　后】：</p>
<p>
	　　摩加迪沙之战是美国自越南战争以来持续时间最长的一次地面战争，伤亡也最惨重。当时还是新闻记者的马克&middot;鲍顿敏感到这一事件的新闻价值，在事件发生后不久，亲入摩加迪沙采访了许多当事人，写成了内容详实、广受瞩目的纪实报道《Black Hawk Down》。</p>
<p>
	　　在这次行动中，虽然有部分美军是作为联合国维持和平部队为完道主义使命进入摩加迪沙的，但游骑兵部队执行的却是美国的乾涉政策，希望通过捉拿索马里高级军事将领，削弱阿迪迪军的实力，并最终达到推翻阿迪迪的目的。这也是在美军遭到围困后，联合国无法及时派遣救援部队，最终导致对峙双方重大伤亡的原因之一。</p>
<p>
	　　这次事件的悲剧结局促使许多美国人反思自伊拉克战争以来美国的乾涉政策，也引起了好莱坞的注意。因此，当《黑鹰坠落》<a href="http://www.eee4.com/" target="_blank">电影下载</a>即将被搬上银幕的消息被证实后，就有许多人预言这部电影将是2002年奥斯卡最佳影片强有力的竞争者。</p>
<p>
	　　除去题材本身的吸引力，本片的幕前幕后都集中了一大批好莱坞精英。幕前有《珍珠港》男主角乔什&middot;哈奈特和《红磨坊》的伊万&middot;麦奎格等当红小生。幕后更有重量级的制片人杰瑞&middot;布鲁克海默和导演雷德利&middot;斯科特。</p>
<p>
	　　制片人杰瑞&middot;布鲁克海默以监制动作和战争片闻名，他的作品包括《石破天惊》、《极速60秒》和《珍珠港》等。与他合作制片兼导演的是大名鼎鼎的雷德利&middot;斯科特。雷德利曾两次获奥斯卡最佳导演提名，但都失败了，去年虽凭《角斗士》获得了最佳影片，在最佳导演的角逐中依然输给了索德伯格，《黑鹰坠落》是他卷土重来之作，很希望能凭此片摘得桂冠。</p>
<p>
	　　影片剧本曾经三易其稿，最后请来《辛德勒的名单》的编剧泽利安作最后的润色。在正式开拍前，全体演员连同只有几个镜头的小角色都分成三拨分别在美军的三角洲部队、游骑兵部队和黑鹰直升机基地参加5天的军训，除学习部队生活、武器操作和团队精神外，他们还和摩加迪沙之战中阵亡者的战友和亲友交谈，对自己所扮演角色有更感性的了解。由于无法在索马里实地拍摄，全片是在摩洛哥完成的，得到了摩洛哥和美国国防部的全力支持，也使得这部影片能尽可能地完整再现当时的事件真相，连剧中人物的姓名除目前仍在美军服役并付有特殊使命的队员外，都采用了真实姓名。有的影评家甚至建议历史频道用此片代替有关历史记录片，因为相比之下，《黑鹰坠落》<a href="http://www.eee4.com/" target="_blank">迅雷电影下载</a>的描述更加准确、更加翔实。</p>
<p>
	　　这部耗资9500万美元的影片的目的当然不仅仅是为了复述历史，导演雷德利&middot;斯科特说得清楚，它将毫不含糊地说明，美国永远不应该成为一个孤立主义国家，这部影片将使那些只通过CNN的新闻报道了解这次事件的人们睁开双眼。</p>
<p>
	　　本片分别被美国国家影评协会（National Board of Review）及《滚石》杂志评为2001年度十大佳片之一，并获得美国电影学会AFI电影奖4项提名。</p>
<p>
	【一句话评论】：</p>
<p>
	一部前所未有的战争片。&mdash;&mdash;《今日美国》<br />
	影片足以让你目不转睛。&mdash;&mdash;《费城询问者报》<br />
	人物空洞，缺乏情感投入。&mdash;&mdash;《阿波罗导报》</p>
<p>
	【花　　絮】：</p>
<p>
	&middot;片中出现的所有&ldquo;黑鹰&rdquo;和&ldquo;小鸟&rdquo;直升机均属于美军第160特种行动飞行团，多数飞行员都曾参与此次武装行动，而且很多临时演员都是真正的突击队员，</p>
<p>
	&middot;金牌编剧斯蒂夫&middot;泽里安曾参与剧本改编，但未出现在编剧名单中。</p>
<p>
	&middot;最初提议拍摄本片的是导演西蒙&middot;韦斯特，他催促杰瑞&middot;布鲁克海默买下原著的拍摄权，并由自己执导，但后来韦斯特放弃了本片的拍摄计划，去执导了《古墓丽影》。</p>
<p>
	&middot;在真实行动中，有18名三角洲部队和游骑兵部队的士兵阵亡，另外，还有2-14步兵团的一等兵詹姆斯&middot;马丁和第10山地师第41工程营的科内尔&middot;休斯顿中士在战斗中丧生，基地的一名名叫马特&middot;里尔森的士兵也因索马里人的炮击而在两天后丧生。</p>
<p>
	&middot;加里森身后显示的一些图像是来自于当时战场的真实卫星图像。</p>
<p>
	&middot;扮演游骑兵部队士兵的演员在军营受训期间曾在门口收到封匿名信，信中感谢他们做出的努力，并要求他们能如实再现战斗，署名为在战斗中阵亡的全体游骑兵。</p>
<p>
	&middot;一名美军士兵在运送工程中从卡车中掉出的镜头是拍摄时意外发生的。</p>
<p>
	&middot;片中美军士兵的头盔上都标有姓氏，这是导演雷德利&middot;斯科特为观众易于区别人物设计的，因为在相同严实的军装下，每个人看上去都差不多。</p>
<p>
	&middot;伊万&middot;麦格雷戈扮演的角色是虚构的，但知情的人都知道，其实这个角色是源于游骑兵一等兵约翰&middot;斯泰宾斯，他因这次行动而获得了&ldquo;银星&rdquo;奖章。但在2000年，他因对儿童实施性侵犯而被叛30年徒刑。五角大楼后来曾有意告诫编剧更改他的姓名。</p>
<p>
	&middot;影片的初剪版本以艾略特的诗句&ldquo;All our ignorance brings us closer to death&rdquo;开场。</p>
<p>
	&middot;在速降场景中，美国国防部指派了一个排的游骑兵参加拍摄。</p>
<p>
	&middot;本&middot;福斯特在受训期间受伤严重，于是与杰米的角色失之交臂。</p>
<p>
	&middot;雷德利&middot;斯科特曾希望拉塞尔&middot;克劳扮演三角洲部队的班长诺姆，但克劳因要出演《美丽心灵》而无法加盟。</p>

<p>
	【穿帮镜头】：</p>
<p>
	&middot;有个士兵戴着2000年款的太阳镜。</p>
<p>
	&middot;在卫星图像中，一架贝尔UH-1休伊直升机盘旋在城市上空，而实拍画面中却是UH-60&ldquo;黑鹰&rdquo;。</p>
<p>
	&middot;&ldquo;小鸟&rdquo;直升机上没有瞄准系统。</p>
<p>
	&middot;在美军基地的镜头中，可以看到印有摩洛哥空军标志的C-130&ldquo;大力神&rdquo;运输机。</p>
<p>
	&middot;直升机飞行员应该都在左侧。</p>
<p>
	<img src="http://image2.sina.com.cn/ent/d/p/2001-12-29/U1117P28T3D68547F326DT20050511124439.jpg" /></p>
<p>
	【效果截图】：可点击查看原图<br />
	<br />
	<a href="http://i3.6.cn/cvbnm/dc/b4/d9/7687f5022e9f03c363fd07b9604a8844.jpg" target="_blank"><img border="0" src="http://i3.6.cn/cvbnm/dc/b4/d9/7687f5022e9f03c363fd07b9604a8844.jpg" /></a>&nbsp;<br />
	<a href="http://i3.6.cn/cvbnm/e5/9c/f2/1ab8a920e800629a7a0b03e87c675d0c.jpg" target="_blank"><img border="0" src="http://i3.6.cn/cvbnm/e5/9c/f2/1ab8a920e800629a7a0b03e87c675d0c.jpg" /></a>&nbsp;<br />
	<a href="http://i3.6.cn/cvbnm/97/43/3c/5436d01d1e781c7888f312913664c5ef.jpg" target="_blank"><img border="0" src="http://i3.6.cn/cvbnm/97/43/3c/5436d01d1e781c7888f312913664c5ef.jpg" /></a>&nbsp;<br />
	<a href="http://i3.6.cn/cvbnm/30/9b/c0/df1c53a57b0a1c2f1fa65044a2f54eec.jpg" target="_blank"><img border="0" src="http://i3.6.cn/cvbnm/30/9b/c0/df1c53a57b0a1c2f1fa65044a2f54eec.jpg" /></a></p>
<br />
<p>
	2001年美国票房过亿争动作战争大片《黑鹰坠落》DVD中英双字1024x576高清版</p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://4e:4e@www2.eee4.com:339/[3E电影站www.eee4.com]黑鹰坠落DVD中英双字1024x576高清版.rmvb" target="_blank">ftp://4e:4e@www2.eee4.com:339/[3E电影站www.eee4.com]黑鹰坠落DVD中英双字1024x576高清版.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#ooffff" style="word-wrap: break-word">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2295/飘花电影piaohua.com黑鹰坠落BD中英双字1280高清.rmvb ">ftp://dy44:piaohua@dy44.piaohua.com:2295/飘花电影piaohua.com黑鹰坠落BD中英双字1280高清.rmvb </a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<anchor></anchor><a href="ftp://eee4.com:8117@vip14.eee4.com:8117/[3E迅雷电影站www.eee4.com]黑鹰坠落DVD中英双字幕CD1.rmvb" target="_blank">ftp://eee4.com:8117@vip14.eee4.com:8117/[3E迅雷电影站www.eee4.com]黑鹰坠落DVD中英双字幕CD1.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<anchor></anchor><a href="ftp://eee4.com:8117@vip14.eee4.com:8117/[3E迅雷电影站www.eee4.com]黑鹰坠落DVD中英双字幕CD2.rmvb" target="_blank">ftp://eee4.com:8117@vip14.eee4.com:8117/[3E迅雷电影站www.eee4.com]黑鹰坠落DVD中英双字幕CD2.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<anchor></anchor><a href="ftp://eee4.com:8117@vip14.eee4.com:8117/[3E迅雷电影站www.eee4.com]黑鹰坠落DVD中英双字幕CD3.rmvb" target="_blank">ftp://eee4.com:8117@vip14.eee4.com:8117/[3E迅雷电影站www.eee4.com]黑鹰坠落DVD中英双字幕CD3.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<anchor></anchor><a href="ftp://eee4.com:1044@vip11.eee4.com:1044/黑鹰坠落/[3E迅雷电影站www.eee4.com]黑鹰坠落DVD国语配音中字幕.rmvb" target="_blank">ftp://eee4.com:1044@vip11.eee4.com:1044/黑鹰坠落/[3E迅雷电影站www.eee4.com]黑鹰坠落DVD国语配音中字幕.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O16262160-3a26.jpg{/dede:field}
