<?php
$z[0]=Array("field","2006年度十大劲歌金曲颁奖典礼迅",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","2006年度十大劲歌金曲颁奖典礼迅雷下载、免费下载，2006年度十大劲歌金曲颁奖典礼Gvod高清在线播放，剧情介绍等。",73,223);
$z[1][4]['name']="description";
$z[2]=Array("field","2006年度十大劲歌金曲颁奖典礼",225,291);
$z[2][4]['name']="title";
$z[3]=Array("field","",293,332);
$z[3][4]['name']="writer";
$z[4]=Array("field","",334,373);
$z[4][4]['name']="source";
$z[5]=Array("field","2007-01-16",375,425);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>2006年度十大劲歌金曲颁奖典礼于1月13日20点30分举行。此次颁奖礼出席歌手包括: 刘德华、何韵诗、杨千嬅、容祖儿、李克勤、陈奕迅等。本次颁奖典礼由曾志伟和崔建邦主持，新浪音乐全程图文直播此次颁奖典礼<br /><br />thunder://QUFmdHA6Ly8xMTRkeToxMTRkeUAyMTguNzEuMjIzLjE4NjozNTYvL9fb0tVJScf4L9Hds6q74S8yMDA2xOq2yMqutPO+orjovfDH+rDkvbG15MDxLzAxLnJtdmJaWg==/</p>\r\n<p>thunder://QUFmdHA6Ly8xMTRkeToxMTRkeUAyMTguNzEuMjIzLjE4NjozNTYvL9fb0tVJScf4L9Hds6q74S8yMDA2xOq2yMqutPO+orjovfDH+rDkvbG15MDxLzAyLnJtdmJaWg==/</p>",427,961);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c120524/133N3605R20-5M02.jpg",963,1046);
$z[7][4]['name']="litpic";

?>