{dede:field name='keywords'}异星战场高清BD1280迅雷下载，免{/dede:field}
{dede:field name='description'}异星战场高清BD1280迅雷下载、免费下载，异星战场高清BD1280Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}异星战场高清BD1280{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-19{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="/uploads/allimg/c120525/133O0UC930-151V0.jpg" style="width: 440px; height: 600px" /></p>
<p>
	◎译　　名　异星战场/约翰&middot;卡特/火星上的约翰&middot;卡特/异星战场：约翰&middot;卡特传奇/异星战场: 强卡特战记(台)/异星争霸战：尊卡特传奇(港)<br />
	◎片　　名　John Carter&nbsp;&nbsp;&nbsp;&nbsp;<br />
	◎年　　代　2012<br />
	◎国　　家　美国<br />
	◎类　　别　科幻/奇幻/动作/冒险&nbsp;<br />
	◎语　　言　英语<br />
	◎字　　幕　中字<br />
	◎IMDB评分&nbsp; 7.0/10 from 28,615 users<br />
	◎IMDB链接&nbsp; http://www.xiaozhizhu.net/<br />
	◎文件格式　XviD + MP3<br />
	◎视频尺寸　1280 x 720<br />
	◎文件大小　1CD 1.37GB<br />
	◎片　　长　132 Mins<br />
	◎导　　演　安德鲁&middot;斯坦顿 Andrew Stanton<br />
	◎主　　演　泰勒&middot;克奇 Taylor Kitsch&nbsp; &hellip;.John Carter<br />
	　　　　　　琳恩&middot;柯林斯 Lynn Collins&nbsp; &hellip;.Dejah Thoris<br />
	　　　　　　威廉&middot;达福 Willem Dafoe&nbsp; &hellip;.Tars Tarkas<br />
	　　　　　　萨曼莎&middot;莫顿 Samantha Morton&nbsp; &hellip;.Sola<br />
	　　　　　　托马斯&middot;哈登&middot;丘奇 Thomas Haden Church&nbsp; &hellip;.Tal Hajus<br />
	　　　　　　马克&middot;斯特朗 Mark Strong&nbsp; &hellip;.Matai Shang</p>

<p>
	◎简　　介　</p>
<p>
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 　　曾荣获奥斯卡金像奖的著名导演安德鲁&middot;斯坦顿带来全新力作《异星战场》，一部以神秘壮丽的火星为背景的史诗动作冒险巨制。影片根据埃德加&middot;赖斯&middot;巴勒斯于</p>
<p>
	20世纪初创作的经典科幻小说《火星公主》改编，故事 讲述美国内战时期，饱受创伤的前军官约翰&middot;卡特（泰勒&middot;克奇 Taylor Kitsch 饰）无意间穿越到了火星。由于引力不同</p>
<p>
	，约翰成为了力大无穷、弹跳如飞的&ldquo;超人&rdquo;，也因此卷入当地几大族群的冲突，周旋于美丽的公主德佳&middot;索丽斯（琳恩&middot;柯林斯 Lynn Collins 饰），英勇的盟友塔斯&middot;塔卡斯</p>
<p>
	（威廉&middot;达福 Willem Dafoe 饰）与狡猾的敌人萨博&middot;赞恩之间。然而地球上战火纷飞带来的痛苦，早已让约翰无心恋战；虽然几大族群都将他视为能够拯救火星的关键人物，可</p>
<p>
	他真的能抛下过去，担负起保卫人民的重任，拯救这个水深火热的世界，扭转异星战场的命运吗？</p>
<p>
	<img alt="" src="/uploads/allimg/c120525/133O0UE160-1D343.jpg" style="width: 650px; height: 366px" /><img alt="" src="/uploads/allimg/c120525/133O0UF1P-1L259.jpg" style="width: 650px; height: 366px" /><img alt="" src="/uploads/allimg/c120525/133O0UG10-1VJ3.jpg" style="width: 650px; height: 366px" /></p>

<p>
	【下载地址】</p>
<table bgcolor="#0099cc" border="0" cellpadding="10" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				迅雷快传高速下载：http://kuai.xunlei.com/d/ZGFBLQVFAAXC</td>
		</tr>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy125:piaohua@dy125.piaohua.com:8077/飘花电影piaohua.com异星战场DVD中字.rmvb</td>
		</tr>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy125:piaohua@dy125.piaohua.com:8081/飘花电影piaohua.com异星战场BD中字1280高清.rmvb</td>
		</tr>
	</tbody>
</table>
<br />{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O0UH220-192Q0.jpg{/dede:field}
