<?php
$z[0]=Array("field","夺命手术BD中英双字1024/1280高",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","夺命手术BD中英双字1024/1280高清迅雷下载、免费下载，夺命手术BD中英双字1024/1280高清Gvod高清在线播放，剧情介绍等。",72,228);
$z[1][4]['name']="description";
$z[2]=Array("field","夺命手术BD中英双字1024/1280高清",230,299);
$z[2][4]['name']="title";
$z[3]=Array("field","",301,340);
$z[3][4]['name']="writer";
$z[4]=Array("field","",342,381);
$z[4][4]['name']="source";
$z[5]=Array("field","2012-02-13",383,433);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",435,472);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://d28:d28@dm.eee4.com:1205/[3E电影站www.eee4.com]夺命手术DVD中英双字.rmvb\" target=\"_blank",474,606);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MP2950F-29131.jpg",608,691);
$z[8][4]['name']="litpic";

?>