<?php
$z[0]=Array("field","红番区[HD中英双字1024x576高清",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","红番区[HD中英双字1024x576高清版]迅雷下载、免费下载，红番区[HD中英双字1024x576高清版]Gvod高清在线播放，剧情介绍等。",72,230);
$z[1][4]['name']="description";
$z[2]=Array("field","红番区[HD中英双字1024x576高清版]",232,302);
$z[2][4]['name']="title";
$z[3]=Array("field","",304,343);
$z[3][4]['name']="writer";
$z[4]=Array("field","",345,384);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-03-10",386,436);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",438,475);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://4e:4e@m1.3edyy.com:1402/【3E电影院www.3edyy.com】红番区HD中英双字1024x576高清版.rmvb\" target=\"_blank",477,622);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MQ33P-43308.jpg",624,705);
$z[8][4]['name']="litpic";

?>