<?php
$z[0]=Array("field","十三/命13/13搏命游戏/百万杀人",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","十三/命13/13搏命游戏/百万杀人游戏13[BD中英双字1024x576高清版]迅雷下载、免费下载，十三/命13/13搏命游戏/百万杀人游戏13[BD中英双字1024x576高清版]Gvod高清在线播放，剧情介绍等。",72,288);
$z[1][4]['name']="description";
$z[2]=Array("field","十三/命13/13搏命游戏/百万杀人游戏13[BD中英双字1024x576高清版]",290,389);
$z[2][4]['name']="title";
$z[3]=Array("field","",391,430);
$z[3][4]['name']="writer";
$z[4]=Array("field","",432,471);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-04-10",473,523);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",525,562);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://7e:7e@m1.eee4.cc:1594/【3E看看www.3ekk.com】十三[BD中英双字1024x576高清版].rmvb\" target=_blank>ftftp://7e:7e@m1.eee4.cc:1594/【3E看看www.3ekk.com】十三[BD中英双字1024x576高清版].rmvb</A></TD></TR></TBODY></TABLE></div><ul class=\"mmlist",564,844);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MP3D2P-3EE.jpg",846,926);
$z[8][4]['name']="litpic";

?>