{dede:field name='keywords'}故乡之光DVD中字2010纪录片迅雷{/dede:field}
{dede:field name='description'}故乡之光DVD中字2010纪录片迅雷下载、免费下载，故乡之光DVD中字2010纪录片Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}故乡之光DVD中字2010纪录片{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-09-14{/dede:field}
{dede:field name='body'}<p>
	<img alt="" height="848" src="http://sacvs.files.wordpress.com/2011/03/nostalgia-for-the-light_poster.jpg" style="cursor: pointer" width="600" /></p>
<p>
	◎译　　名　故乡之光/渴望光明/怀念星光<br />
	◎片　　名　Nostalgia For The Light<br />
	◎年　　代　2010<br />
	◎国　　家　法国/德国/智利<br />
	◎类　　别　剧情/纪录片<br />
	◎语　　言　西班牙语/英语<br />
	◎字　　幕　中字<br />
	◎IMDB评分 7.5/10 (209 votes)<br />
	◎文件格式　XviD + MP3<br />
	◎视频尺寸　624 x 336<br />
	◎文件大小　1CD<br />
	◎片　　长　90 Mins<br />
	◎导　　演　帕特里克&middot;古兹曼 Patricio Guzm&aacute;n<br />
	◎主　　演　Gaspar Calas ... Himself - Astronomer<br />
	　　　　　　Lautaro N&uacute;?ez ... Himself - Archeologist<br />
	　　　　　　Lu&iacute;s Henr&iacute;quez ... Himself<br />
	　　　　　　Miguel ... Himself - Architect<br />
	　　　　　　Victor Gonz&aacute;lez ... Himself - Engineer<br />
	　　　　　　Vicky Saaveda ... Herself<br />
	　　　　　　Violeta Berrios ... Herself<br />
	　　　　　　George Preston ... Himself - Astronomer<br />
	　　　　　　Valentina Rodr&iacute;guez ... Herself<br />
	　　　　　　<br />
	◎简　　介　<br />
	　　在智利的阿塔卡马沙漠，天文学家探寻宇宙以寻找生命的起源，不远处，当地的妇女正在沙丘中搜寻亲人的尸骸，他们是被皮诺切特独裁政权随意处置和杀害的。导演帕特里克&middot;古兹曼将这两种关于生命的找寻并置在一起，引人深思。<br />
	　　这是一部在海拔3000米的Atacama沙漠拍摄的纪录片。天文学家聚集在那里观测群星。这个地方还因一个原因吸引了众多来访者：地表的干旱能使人类尸体完好无损。除了那些干尸和迷路的探险者的尸体，还有许多政治被关押在这片沙漠中而死去。影片强调了这样的两面性，将天文学家观测繁星寻找外星生命和那些支离破碎的家庭寻找亲人对比。所以影片的政治层面很清晰。<br />
	幕后制作<br />
	　　导演帕特里克&middot;古兹曼的每一部影片都和20世纪智利国家的回忆有关：从他在1975年戛纳影展平行竞赛单元放映的《智利之战》三部曲开始，一直到在2004年非竞赛单元放映的《萨尔瓦多&middot;阿兰德》。《故乡之光》也延续了这一主题，影片面向未来（群星），同时不忘为了赢得独立的代价和那段充满鲜血的痛苦的过去。</p>
<p>
	◎剧　　照　</p>
<p>
	<img alt="" src="/uploads/allimg/c120524/133N42FB60-224R0.jpg" /></p>
<p>
	<img alt="" src="/uploads/allimg/c120524/133N42F9430-2394K.jpg" /></p>
<p>
	[下载地址]： &nbsp;<img border="0" src="/uploads/allimg/c120524/133N2Z4FF-102231.jpg" />
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:1541/飘花电影piaohua.com故乡之光DVD中字.rmvb</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120524/133N42Gb50-24Y36.jpg{/dede:field}
