<?php
$z[0]=Array("field","夜心万万-金希澈迅雷下载，免费",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","夜心万万-金希澈迅雷下载、免费下载，夜心万万-金希澈Gvod高清在线播放，剧情介绍等。",72,196);
$z[1][4]['name']="description";
$z[2]=Array("field","夜心万万-金希澈",198,251);
$z[2][4]['name']="title";
$z[3]=Array("field","",253,292);
$z[3][4]['name']="writer";
$z[4]=Array("field","",294,333);
$z[4][4]['name']="source";
$z[5]=Array("field","2006-08-04",335,385);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",387,424);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://0720/\" target=_blank>ftftp://</A><A href=\"httftp://www.xxjy.org@ftp0.xxjy.org/\" target=_blank>ftp0.xxjy.org/</A>日韩连续剧===连载区===/[小晓家园<A href=\"httftp://www.xxjy.org/\" target=_blank>www.xxjy.org</A>][夜心万万][SBS060717][金希澈朴京林][韩文中字]/[小晓家园<A href=\"httftp://www.xxjy.org]YasimManman.060717.KO_CN.rmvb\" target=_blank>www.xxjy.org]YasimManman.060717.KO_CN.rmvb</A><BR><BR><FONT face=Verdana>2006-07-27 16:59:47 开始连接......<BR>2006-07-27 16:59:47 开始搜索候选资源......<BR>2006-07-27 16:59:50 搜索到40个候选资源<BR>2006-07-27 16:59:50 使用候选资源进行连接......<BR>2006-07-27 16:59:50 开始创建文件......<BR>2006-07-27 16:59:50 文件创建成功，开始下载数据......<BR>2006-07-27 17:00:07 用户取消下载<BR></FONT> <br></div><ul class=\"mmlist",426,1228);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MO60K30-35C0.gif",1230,1312);
$z[8][4]['name']="litpic";

?>