{dede:field name='keywords'}脱衣舞娘大战狼人DVD中字2012英{/dede:field}
{dede:field name='description'}脱衣舞娘大战狼人DVD中字2012英国恐怖喜剧迅雷下载、免费下载，脱衣舞娘大战狼人DVD中字2012英国恐怖喜剧Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}脱衣舞娘大战狼人DVD中字2012英国恐怖喜剧{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-22{/dede:field}
{dede:field name='body'}<p>
	&nbsp;<img border="0" src="/uploads/allimg/c120525/133O0W3UP-1039D.jpg" /></p>
<p>
	&nbsp;</p>
<p>
	&nbsp;<img border="0" src="/uploads/allimg/c120525/133O0W3bP-119430.jpg" /></p>
<p>
	◎译　　名　脱衣舞娘大战人狼/脱衣舞娘大战狼人<br />
	◎片　　名　Strippers vs Werewolves<br />
	◎年　　代　2012<br />
	◎国　　家　英国<br />
	◎类　　别　喜剧/恐怖<br />
	◎语　　言　英语<br />
	◎字　　幕　中文<br />
	◎IMDB评分 4.7/10 from 55 users<br />
	◎IMDB链接 http://www.imdb.com/title/tt1702009<br />
	◎文件格式　DVD-RMVB<br />
	◎视频尺寸　720 x 404<br />
	◎文件大小　1CD 473MB<br />
	◎片　　长　93 Mins<br />
	◎导　　演　乔纳森&middot;格伦德宁 Jonathan Glendening<br />
	◎主　　演　罗伯特&middot;英格兰德 Robert Englund ....Tapper<br />
	　　　　　　莎拉&middot;道格拉斯 Sarah Douglas ....Jeanette<br />
	　　　　　　史蒂文&middot;伯克夫 Steven Berkoff ....Flett<br />
	　　　　　　丽赛特&middot;安东尼 Lysette Anthony ....Jilly<br />
	　　　　　　比利&middot;穆瑞 Billy Murray ....Ferris<br />
	　　　　　　阿兰&middot;福德 Alan Ford ....Harry<br />
	　　　　　　芭芭拉&middot;尼德尔加科娃 Barbara Nedeljakova ....Raven<br />
	　　　　　　露西&middot;萍德 Lucy Pinder ....Vampire Bride<br />
	　　　　　　马丁&middot;康普斯顿 Martin Compston ....Scott<br />
	　　　　　　Joe Egan<br />
	　　　　　　马汀&middot;坎普 Martin Kemp ....Mickey<br />
	　　　　　　西蒙&middot;菲利普斯 Simon Phillips ....Sinclair<br />
	　　　　　　Coralie Rose ....Brandi<br />
	　　　　　　阿黛尔&middot;秀娃 Adele Silva ....Justice<br />
	　　　　　　多米尼克&middot;巴恩斯 Dominic Burns ....Alex<br />
	　　　　　　Rita Ramnani ....Chastity<br />
	　　　　　　Ali Bastion ....Dani<br />
	　　　　　　尼克&middot;内维恩 Nick Nevern ....Franklyn<br />
	　　　　　　Jazz Lintott ....Richard<br />
	　　　　　　Jude Poyer ....Nutt<br />
	　　　　　　Shaun Lucas ....Stripclub businessman<br />
	　　　　　　Lee Asquith-Coe ....Vixens Punter<br />
	　　　　　　Charlie Robinson ....Customer<br />
	　　　　　　Marc Baylis ....Carlos<br />
	　　　　　　Dean Williams ....Mutt<br />
	　　　　　　Hannah Greeno ....Saffron<br />
	　　　　　　Stuart Higgs ....Stripclub businessman customer<br />
	　　　　　　Charlie Bond ....Carrie<br />
	　　　　　　Johnny Lynch ....Relief Barman (uncredited)<br />
	　　　　　　</p>
<p>
	◎简　　介　</p>
<p>
	　　马汀&middot;坎普饰演的狼人米基在一家脱衣舞厅里被一舞女失手杀死。舞厅的老板把尸体藏了起来，但人狼族的首领杰克&middot;费瑞思（比利&middot;穆雷）还是得知了这一消息。在下一个月圆夜来临之前，舞女们必须做好准备迎接人狼族的复仇。</p>
<p>
	　　地点：古尔德福德，脱衣舞俱乐部。舞女贾丝蒂斯为米基单独表演一支舞，后者不仅违反了客人不允许动手动脚的规定，而且张开了獠牙要把贾丝蒂斯吃掉。原来米基是一个狼人。恐慌的的贾丝蒂斯抓起一支银色的钢笔，插入了对方的眼睛，就这么把他杀死了&gt;俱乐部的老板詹妮特见此情形，立刻命令舞女们偷偷把尸体藏好，以便能正常营业。然而麻烦没有就此结束，因为米基背后还有一大群嗜血成性、杀人如麻的狼人族。当米基的尸体被发现之后，狼人族邪恶而充满了魅力的首领杰克&middot;费瑞思发誓要为他复仇。然而杰克并不知道，贾丝蒂斯其实是自己的一位手下斯考特的未婚妻。在一次缠绵过程中，贾丝蒂斯也被变成了吸血鬼&hellip;&hellip;</p>
<p>
	　　《猛鬼街》的标志性人物Robert Englund将在他首部英国电影《脱衣舞娘大战狼人》Strippers vs. Werewolves中上演处女秀。好莱坞传奇人物Robert Englund 将在他的首部英国喜剧恐怖电影《脱衣舞娘大战狼人》中扮演一个阴险狡诈的狼人领袖，该片在5月16日星期一于伦敦附近开拍。</p>
<p>
	<br />
	◎影片截图</p>
<p>
	&nbsp;&nbsp;<img border="0" src="/uploads/allimg/c120525/133O0W410-123959.jpg" /></p>
<p>
	&nbsp;<img border="0" src="/uploads/allimg/c120525/133O0W41610-13J09.jpg" /></p>
	&nbsp;&nbsp;&nbsp;</p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="/uploads/allimg/c120525/133O0T31310-42214.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：http://www.xiaobajie.com</td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:3471/飘花电影piaohua.com脱衣舞娘大战狼人DVD中字.rmvb</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O0W42320-14R00.jpg{/dede:field}
