{dede:field name='keywords'}不友善的海豚纪录片美国国家地理{/dede:field}
{dede:field name='description'}不友善的海豚纪录片美国国家地理迅雷下载、免费下载，不友善的海豚纪录片美国国家地理Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}不友善的海豚纪录片美国国家地理{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-12-04{/dede:field}
{dede:field name='body'}<p>
	<img border="0" src="/uploads/allimg/c120524/133N4935350-1Y616.jpg" style="max-width: 750px; max-height: 750px" /></p>
<p>
	<img border="0" src="/uploads/allimg/c120524/133N49355930-1960G.jpg" style="max-width: 750px; max-height: 750px" /></p>
<p>
	&nbsp;<img border="0" src="/uploads/allimg/c120524/133N4935G50-202303.jpg" style="max-width: 750px; max-height: 750px" /></p>
<p>
	&nbsp;<img border="0" src="/uploads/allimg/c120524/133N4935Q10-213616.jpg" style="max-width: 750px; max-height: 750px" /></p>

<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="/uploads/allimg/c120524/133N2Z4FF-102231.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:2255/飘花电影piaohua.com不友善的海豚纪录片.mkv</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120524/133N493591F-221Z8.jpg{/dede:field}
