{dede:field name='keywords'}地心的納粹高清1280版BD中字2012{/dede:field}
{dede:field name='description'}地心的納粹高清1280版BD中字2012最新美国R级恐怖惊悚大片迅雷下载、免费下载，地心的納粹高清1280版BD中字2012最新美国R级恐怖惊悚大片Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}地心的納粹高清1280版BD中字2012最新美国R级恐怖惊悚大片{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-21{/dede:field}
{dede:field name='body'}<p>
	&nbsp;<img src="http://img170.poco.cn/mypoco/myphoto/20120426/11/56643687201204261154041493748894801_000.jpg" /></p>
<p>
	◎译　　名　地心的纳粹<br />
	◎片　　名　Nazis at the Center of the Earth<br />
	◎年　　代　2012<br />
	◎国　　家　美国<br />
	◎类　　别　恐怖/惊悚<br />
	◎语　　言　英语<br />
	◎字　　幕　中文<br />
	◎IMDB评分 (awaiting 5 votes)<br />
	◎IMDB链接 <a href="http://www.bluemv.com" title="电影下载">http://www.bluemv.com</a><br />
	◎文件格式　高清1280版BD-RMVB<br />
	◎视频尺寸　1280 x 720<br />
	◎文件大小　1CD 863MB<br />
	◎片　　长　90 mins<br />
	◎导　　演　Joseph J. Lawson<br />
	◎主　　演　多米尼克&middot;斯万 Dominique Swain ....Paige Morgan<br />
	　　　　　　Jake Busey ....Adrian Reistad<br />
	　　　　　　Lilan Bowden ....May Yun<br />
	　　　　　　Trevor K&uuml;hn ....Brian Moak<br />
	　　　　　　Christopher Karl Johnson ....Josef Mengele<br />
	　　　　　　Marlene Okner ....Silje Lagesen<br />
	　　　　　　Jordan James Smith ....Nazi Scientist<br />
	　　　　　　Jon Kondelik ....Nazi (voice)<br />
	　　　　　　Max Bird-Ridnell ....Nazi Leader<br />
	　　　　　　Andre Tenerelli ....Aaron Blechman<br />
	　　　　　　Jeff Newman ....Nazi Guard<br />
	　　　　　　Adam Burch ....Mark Maynard<br />
	　　　　　　James Maxwell Young ....Adolf Hitler<br />
	　　　　　　Maria Pallas ....Angela Magliarossa<br />
	　　　　　　Josh Allen ....Lucas Moss<br />
	　　　　　　Samuel Fisher ....Nazi pilot<br />
	　　　　　　Abderrahim Halaimia ....Rahul Jumani<br />
	　　　　　　Maria Pallas ....Angela<br />
	　　　　　　Sean Patrick Watkins ....German Scientist Approaching Luftwaffe Aircraft (uncredited)<br />
	　　　　　　Luke Wdowicz ....Nazi Zombie Guard (uncredited)</p>
<p>
	<br />
	◎简　　介</p>
<p>
	在南极洲的研究人员被一队蒙面突击队员绑架。他们被拖到了很深的地下，隐藏在地球的中心。纳粹的幸存者统统聚集在这里，他们的身体是一堆可怕的烂肉了，可是他们依旧没有放弃，他们复兴第三帝国的梦想。</p>
<p>
	<br />
	幕后制作</p>
<p>
	改编自二战中的真实人物 纳粹医生臭名昭著</p>
<p>
	　　传说臭名昭著的纳粹疯狂科学家约瑟夫&middot;门格尔医生和他的一些党卫军弟兄在二战中逃脱后，到另一个银河系中的不明飞行物上。历史上关于这个&ldquo;死亡天使&rdquo;的传说可谓不胜枚举，即便是79年发现了他的尸体，也仍有很多人并不相信。</p>
<p>
	　　《地心的纳粹》就是根据传说拍摄的一部最新恐怖片，日前《地心的纳粹》首度曝光了影片的一组剧照，影片中的约瑟夫&middot;门格尔和他的盖世太保成为了地下深处的活死人,影片将以蓝光碟的形式发布不在影院上映！</p>
<p>
	◎影片截图</p>
<p>
	&nbsp;<img src="http://img170.poco.cn/mypoco/myphoto/20120426/11/56643687201204261151583232534007620_001.jpg" style="width: 600px; height: 338px" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120426/11/56643687201204261151583232534007620_002.jpg" style="width: 600px; height: 338px" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120426/11/56643687201204261151583232534007620_005.jpg" style="width: 600px; height: 338px" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120426/11/56643687201204261151583232534007620_004.jpg" style="width: 600px; height: 338px" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120426/11/56643687201204261151583232534007620_003.jpg" style="width: 600px; height: 338px" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.netftp//dy44:piaohua@dy44.piaohua.com:3142/" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3300/飘花电影piaohua.com地心的納粹高清1280版BD中字.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3300/飘花电影piaohua.com地心的納粹高清1280版BD中字.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1644R10-532b.jpg{/dede:field}
