{dede:field name='keywords'}食人蚁军团迅雷下载，免费下载，{/dede:field}
{dede:field name='description'}食人蚁军团迅雷下载、免费下载，食人蚁军团Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}食人蚁军团{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2007-01-04{/dede:field}
{dede:field name='body'}<BR>中文名称：食人蚁军团(DVD) <BR>主要演员：吉那.利.诺琳|约翰.阿伦.奈鲁逊|马古.姆利|凯实.库伊古里 <BR>影片导演：克里斯蒂.安 <BR>影片类型：动作片, 恐怖片, 冒险片 <BR>影片产地：欧美<BR>电影来源：www.eee4.com<BR>影片大小：1CD/380MB <BR>影片级别：黄金电影 <BR>影片介绍：<BR>　　进行野生动物植物保护的卡茨达，从借用他的吉普车的客人那里行到了无线联系，急速赶往现场，在途中，与对土地资源进行勘察的女性史那相遇，虽然很快找到了吉普车，却不见了最关键的联系人的身影，一打开吉普车的门，里却有无数只蚂蚁和尸体白骨，实际上这种蚂蚁是吃人的蚂蚁马拉本达，寻求救命的客人残酷地成为了它的美餐，深知危机的他们两个要逃脱蚂蚁群，然后卡茨达被蚂蚁的毒针所螯，躲身的小屋也被蚂蚁所包围--这种凶暴的食人蚁给人类带来了空前的震惊和恐慌，人们对于自然界的这种威协，真的无计可施吗？ <BR><BR><IMG src="http://pic.piaohua.com/0701pic/allimg/080110/0053370.jpg"> 
<P>2008-01-09 03:07:12 开始连接......<BR>2008-01-09 03:07:14 开始搜索候选资源......<BR>2008-01-09 03:07:15 搜索到31个候选资源<BR>2008-01-09 03:07:17 使用候选资源进行连接......<BR>2008-01-09 03:07:20 搜索到26个候选资源<BR>2008-01-09 03:07:23 使用候选资源进行连接......<BR>2008-01-09 03:07:24 文件创建成功，开始下载数据......<BR>2008-01-09 03:07:26 用户取消下载&nbsp;&nbsp; 本文来自 <A href="/index.html" target=_blank>www.eee4.com</A></P>（直接可能无法下载，一律使用<A href="http://pstatic.xunlei.com/about/product/down_xl5.htm" target=_blank>迅雷下载</A>）<BR>木乃伊后高票房恐怖大片《食人蚁军团》DVD中字 － 来自[3E迅雷电影站eee4.com]下载地址：<IMG src="/templets/img/down.jpg" border=0><BR>
<TABLE style="BORDER-RIGHT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; BORDER-BOTTOM: #cccccc 1px dotted" cellSpacing=0 cellPadding=6 width="95%" align=center border=0>
<TBODY>
<TR>
<TD style="WORD-WRAP: break-word" bgColor=#fdfddf><ANCHOR></ANCHOR><A href="ftp://eee4.com:eee4@xl3.eee4.com:8448/食人蚁军团/[3E迅雷电影站www.eee4.com]食人蚁军团[DVD中字].rmvb" target=_blank>ftp://eee4.com:eee4@xl3.eee4.com:8448/食人蚁军团/[3E迅雷电影站www.eee4.com]食人蚁军团[DVD中字].rmvb</A></TD></TR></TBODY></TABLE>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O164L40-4J49.jpg{/dede:field}
