<?php
$z[0]=Array("field","",75,103);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",132,160);
$z[1][4]['name']="typeurl";
$z[2]=Array("field","",166,195);
$z[2][4]['name']="typename";
$z[3]=Array("arclist","\r\n				<li><span>[field:pubdate function=\"MyDate('m-d',@me)\"/]</span><a href=\"[field:arcurl /]\" target=\"_blank\">[field:title /]</a></li>\r\n				 ",215,409);
$z[3][4]['titlelen']="60";
$z[3][4]['row']="18";

?>