{dede:field name='keywords'}银翼杀手[BD中英双字1024x576高{/dede:field}
{dede:field name='description'}银翼杀手[BD中英双字1024x576高清版]迅雷下载、免费下载，银翼杀手[BD中英双字1024x576高清版]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}银翼杀手[BD中英双字1024x576高清版]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2010-04-12{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://3e:3e@d8.3edyy.com:128/【3E电影院www.eee4.cc】银翼杀手BD中英双字1024x576高清版.rmvb" target="_blank{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MQ3414F-23035.jpg{/dede:field}
