{dede:field name='keywords'}天地雄心BD高清国粤双语1024*576{/dede:field}
{dede:field name='description'}天地雄心BD高清国粤双语1024*576迅雷下载、免费下载，天地雄心BD高清国粤双语1024*576Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}天地雄心BD高清国粤双语1024*576{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-09-21{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img165.poco.cn/mypoco/myphoto/20110921/16/62564813201109211626049904100545430_000.jpg" /></p>
<p>
	◎译　　名 Armageddon<br />
	◎片　　名 天地雄心<br />
	◎年　　代 1997<br />
	◎IMDB链接 <a href="http://www.imdb.com/title/tt0183892/">http://www.imdb.com/title/tt0183892/</a><br />
	◎IMDB链接 5.1/10 (164 votes)<br />
	◎国　　家 香港<br />
	◎国　　家 动作/喜剧/恐怖/幻想<br />
	◎片　　长 112分钟<br />
	◎字　　幕 N/A<br />
	◎导　　演 陈嘉上 Gordon Chan<br />
	◎主　　演 刘德华 Andy Lau ....Dr. Tak Ken<br />
	　　　　　　 李嘉欣 Michelle Lee ....Adele<br />
	　　　　　 　黄秋生 Anthony Wong ....Chiu Tai-Pang<br />
	　　　　　 　周宝珊 Jessica Chau<br />
	　　　　　 　王翠玲 Angel Wong<br />
	　　　　　 　黎耀祥 Yiu-Cheung Lai ....(as Yiu Cheung Lai)<br />
	　　　　　 　叶广俭 Kwong Kim Yip<br />
	　　　　 　　Claudia Lau ....Supt. Ivy Yip<br />
	　　　　 　　Michael Lieu<br />
	　　　　 　　Jacky Wong<br />
	　　　　 　　Steven Lau<br />
	　　　　 　　Wai Yin Tse<br />
	　　　　 　　Vincent Chik<br />
	　　　　 　　Michael Ian Lambert ....(as Mike Lambert)<br />
	　　　　 　　Caponio Nunzino<br />
	　　　　 　　Jack Lam<br />
	　　　　 　　Kim Penn ....Sharon (as Kim Maree Penn)<br />
	　　　　 　　Hugo Kwan<br />
	　　　　 　　Takeshi Kokoru ....Mr. Sato<br />
	　　　　 　　金刚 Kong Kim ....(as Kim Kong &#39;Chow Chiu Ki&#39;)<br />
	　　　　 　　谷德昭 Vincent Kok ....T.C.</p>
<p>
	◎简　　介　</p>
<p>
	　　华是香港电脑咨询集团的总裁，亦是香港区三位未来领袖之一，警官秋生被派作保护。另一名未来领袖在严密保护下亦告离奇死亡，华决</p>
<p>
	心调查。</p>
<p>
	　　世界电脑软件大王Bill Gates突然出现找华，Bill也是士大未来领袖之一，Bill以华能见其妻作诱要求借用华人造卫星做联合大行动。华</p>
<p>
	与精英们对Bill展开调查，与秋追寻至布拉格，却受特务阻挠。二人追查至一庄严及神秘的会场，发现其他领袖相继被消灭。Bill要求华加入集</p>
<p>
	团，华拒绝并表示天地万物唯有神才可改变，即与Bill展开智、力对决&hellip;&hellip;</p>
<p>
	　　被誉为十位未来领袖正在香港准备领取特别殊荣，其中一人突然离奇身亡，警方为保护所有未来领袖之安全，特派精英保护。华(刘德华)</p>
<p>
	是香港计算机信息总裁，亦是本港三位未来领袖之一，由警官秋生(黄秋生)作保护。第二名未来领袖在严密保护下亦离奇死亡，华决定调查真相</p>
<p>
	。十大未来领袖之一世界计算机软件大王Bill Gates突然出现找华，要求借用华之人造卫星作联合大行动，华要求解释行动目的，但拒绝并以华</p>
<p>
	能见妻(李嘉欣)作引诱。于是华与精英们对Bill展开调查，发现行动背后隐藏重大秘密&hellip;&hellip;</p>
<p>
	幕后制作</p>
<p>
	　　在电视连续剧《X档案》（The X-Files）的影响下，本片借末世神秘主义打造科幻片类型，然而由于高科技制作需要大资金，影片制作无</p>
<p>
	证满足，因此科幻色彩显得贫瘠。戏剧结构有重大漏洞，给人以拼凑的感觉。比如前半段科学家的离奇死亡牵连出大段科学理论，这与后半段刘</p>
<p>
	德华因思想念李嘉欣被其死而复生引入圈套没有什么关系。本片的特色在于延续了陈嘉上&ldquo;小男人&rdquo;系列中的生活感，人情戏写得出色。刘德华</p>
<p>
	与黄秋生有许多自然即兴，打动观众，真情随处游走的对手戏。黄秋生安慰刘德华，流泪自怨，背着镜头偷偷哭泣，布拉格雪地中互掷雪球，都</p>
<p>
	挖掘出友谊的力量。</p>
<p>
	&nbsp;<img alt="" src="http://img165.poco.cn/mypoco/myphoto/20110921/16/62564813201109211626049904100545430_004.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img165.poco.cn/mypoco/myphoto/20110921/16/62564813201109211626049904100545430_003.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img165.poco.cn/mypoco/myphoto/20110921/16/62564813201109211626049904100545430_002.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img165.poco.cn/mypoco/myphoto/20110921/16/62564813201109211626049904100545430_001.jpg" style="width: 720px; height: 405px" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="&#13;&#10;ftp://dy125:piaohua@dy125.piaohua.com:5012/飘花电影piaohua.com天地雄心BD国粤双语中字1024高清.mkv">ftp://dy125:piaohua@dy125.piaohua.com:5012/飘花电影piaohua.com天地雄心BD国粤双语中字1024高清.mkv </a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1C1FP-4DQ.jpg{/dede:field}
