{dede:field name='keywords'}最后的狮子BD中英双字1024高清20{/dede:field}
{dede:field name='description'}最后的狮子BD中英双字1024高清2011纪录片迅雷下载、免费下载，最后的狮子BD中英双字1024高清2011纪录片Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}最后的狮子BD中英双字1024高清2011纪录片{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-01-08{/dede:field}
{dede:field name='body'}<p>
	<img alt="" height="755" src="/uploads/allimg/c120524/133N49302120-213056.jpg" style="cursor: pointer" width="600" /></p>
<p>
	◎译　　名　最后的狮子<br />
	◎片　　名　The Last Lions<br />
	◎年　　代　2011<br />
	◎国　　家　美国/博茨瓦纳<br />
	◎类　　别　纪录/家庭<br />
	◎语　　言　英语<br />
	◎字　　幕　中英双字<br />
	◎IMDB评分 7.9/10 from 180 users<br />
	◎文件格式　BD-RMVB<br />
	◎视频尺寸　1024 x 576<br />
	◎文件大小　1CD<br />
	◎片　　长　90 Min<br />
	◎导　　演　Dereck Joubert<br />
	◎主　　演　杰瑞米&middot;艾恩斯 Jeremy Irons...Narrator<br />
	<br />
	◎简　　介　<br />
	<br />
	&nbsp; &nbsp; 影片《最后的狮子》讲述了一头雌狮和它的幼崽，以及水牛和其他竞争对手生存传奇。在过去的50年中，狮子的数量从45万头骤减到20万头。德里克和贝弗利&middot;朱伯特用故事和镜头展现了一个了产生共鸣问题，&quot;狮子之母&quot;和它的幼崽会不会成为地球上最后的狮子，人类有没有意识到它们的生存有多么艰难，会不会为此动容，而努力去改变这种状况。<br />
	<br />
	<img alt="" border="0" src="/uploads/allimg/c120524/133N49305310-22W23.jpg" /><br />
	<img alt="" border="0" src="/uploads/allimg/c120524/133N493060-239233.jpg" /></p>
<p>
	[下载地址]： &nbsp;<img border="0" src="/uploads/allimg/c120524/133N2Z4FF-102231.jpg" />
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:2548/飘花电影piaohua.com最后的狮子BD中英双字1024高清2011纪录片.rmvb</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120524/133N4930B0-24YT.jpg{/dede:field}
