{dede:field name='keywords'}碧海蓝天/夜海倾情/夜海情/碧海{/dede:field}
{dede:field name='description'}碧海蓝天/夜海倾情/夜海情/碧海情[BD中英双字1280x720高清版]迅雷下载、免费下载，碧海蓝天/夜海倾情/夜海情/碧海情[BD中英双字1280x720高清版]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}碧海蓝天/夜海倾情/夜海情/碧海情[BD中英双字1280x720高清版]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2009-12-16{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://3e:3e@www2.3edyy.com:954/【3E电影院www.3edyy.com】碧海蓝天BD中英双字1280x720高清版.rmvb" target="_blank{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MQ3255F-5J25.jpg{/dede:field}
