{dede:field name='keywords'}CCTV2007年春节联欢晚会迅雷下载{/dede:field}
{dede:field name='description'}CCTV2007年春节联欢晚会迅雷下载、免费下载，CCTV2007年春节联欢晚会Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}CCTV2007年春节联欢晚会{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2007-03-02{/dede:field}
{dede:field name='body'}<p>2007春节联欢晚会完整清晰版视频&nbsp;</p>
<p><img height="375" alt="" width="500" src="http://pic.piaohua.com/0701pic/allimg/070302/2225120.jpg" /></p>
<p>thunder://QUFmdHA6Ly93ZWJscTAyNTM6d3d3Lnh4ankub3Jn0KHP/rzS1LBAZnRwMTczLnp1eHVhbi5jb20ucnU6MjIxLysrK9fb0tUrKysvW3d3dy53ZWJscS5uZXS0v9PpwNZdQ0NUVjIwMDfE6rS6vdrBqru2ze274S5ybXZiWlo=</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O16104430-3X07.jpg{/dede:field}
