<?php
$z[0]=Array("field","CCTV2007年春节联欢晚会迅雷下载",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","CCTV2007年春节联欢晚会迅雷下载、免费下载，CCTV2007年春节联欢晚会Gvod高清在线播放，剧情介绍等。",73,211);
$z[1][4]['name']="description";
$z[2]=Array("field","CCTV2007年春节联欢晚会",213,273);
$z[2][4]['name']="title";
$z[3]=Array("field","",275,314);
$z[3][4]['name']="writer";
$z[4]=Array("field","",316,355);
$z[4][4]['name']="source";
$z[5]=Array("field","2007-03-02",357,407);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>2007春节联欢晚会完整清晰版视频&nbsp;</p>\r\n<p><img height=\"375\" alt=\"\" width=\"500\" src=\"http://pic.piaohua.com/0701pic/allimg/070302/2225120.jpg\" /></p>\r\n<p>thunder://QUFmdHA6Ly93ZWJscTAyNTM6d3d3Lnh4ankub3Jn0KHP/rzS1LBAZnRwMTczLnp1eHVhbi5jb20ucnU6MjIxLysrK9fb0tUrKysvW3d3dy53ZWJscS5uZXS0v9PpwNZdQ0NUVjIwMDfE6rS6vdrBqru2ze274S5ybXZiWlo=</p>",409,787);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c120525/133O16104430-3X07.jpg",789,873);
$z[7][4]['name']="litpic";

?>