{dede:field name='keywords'}街舞少年DVD迅雷下载，免费下载{/dede:field}
{dede:field name='description'}街舞少年DVD迅雷下载、免费下载，街舞少年DVDGvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}街舞少年DVD{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2007-02-23{/dede:field}
{dede:field name='body'}<p>◆中文片名：街舞少年/舞动激情<br />◆英文片名：Stomp the Yard<br />◆年　　代：2007<br />◆上映日期：2007年1月12日(美国)<br />◆国　　家：美国<br />◆类　　别：剧情/音乐/艺术<br />◆导　　演：塞尔文&middot;怀特(Sylvain White)<br />◆主　　演：哥伦布&middot;肖特(Columbus Short)<br />　　　 梅根&middot;古德(Meagan Good)<br />　　　 莱约(Ne-Yo)<br />　　　 达雷&middot;德维特&middot;汉森(Darrin Dewitt Henson)<br />◆级 别：PG-13(性内容，粗俗的幽默，暴力)<br />◆出 品：索尼<br />◆片 长：115分钟<br />◆语　　言：英语<br />◆字　　幕：无<br />◆压缩格式：CAM-RMVB<br />◆文件大小：2CD 358MB <br />◆剧情简介：舞动街舞激情 <br /><br />　　在洛杉矶的地下街舞世界，DJ威廉姆斯（哥伦布&middot;肖特饰）和弟弟绝对是其中的风流人物。高超的技巧和对街舞的热情，他们的组合几乎打败天下无敌手，但风头过健的他们也引来不少忌恨，因为一次意气之争，弟弟不幸招来杀身之祸。远离伤心之地的DJ决定实现弟弟的梦想，前往亚特兰大的真理大学，并且发誓再不与街舞有任何瓜葛。 <br />　　在这里，DJ不仅认识了美丽的少女帕默尔（梅根&middot;古德饰），也发现了真理大学里流行的一种非裔美国人教友团体的传统舞步&ldquo;Stepping&rdquo;，复杂移动加特殊韵律的团队表演深深吸引了他的注意。然而，就在DJ努力适应校园生活认真学习，并希望和帕默尔有所发展的同时，却被迫再次被拉入了舞蹈世界。 </p>
<div class="Pty738"></div>
<br />　　原来，学校的两个团体都想在全国的&ldquo;Stepping&rdquo;大赛中取得胜利，而DJ的舞蹈天赋和嘻哈风格使他必然成为了这场激烈竞争的争夺对象和获胜筹码。这一次，DJ不仅将面对座无虚席、竞争激烈的竞技舞台，还要战胜自己的阴影，真正和团队合作，重新学会街舞和人生的意义！ <br />-----------------------------------------------------------------<br />◆影片看点：眩目高难华丽派街舞竞技 <br /><br />　　肆意妄为、狂野奔放的街舞魔力在银幕上火辣铺开，你马上会忽略影片万变不离其宗的励志，似曾相识的情节。就像娱乐大片就图个眼球刺激一样，舞蹈电影如此不也就讲究洒脱的动作和精心编排的舞蹈场景么？从成本1300万的《舞出一片天》打破&ldquo;马丁&middot;路德&middot;金日&rdquo;票房记录，到《热力四射》的顺利夺冠，再到前不太久的《舞出我人生》热力逼人掀起淡市热潮，只要舞蹈动作和演员过关，青春舞蹈类题材的票房实在是潜力无穷。 <br />　　说起影片的男女主角哥伦布&middot;肖特和梅根&middot;古德，两位都是肢体功夫相当了得的人物。肖特不仅曾获得过2004年全美年度舞蹈大奖提名，还和小甜甜布兰妮传出过绯闻，娱乐全能的他一度知名度空前，身材傲人、长相甜美的古德则是Hip-hop说唱团体成员，两人早在《热力四射》里就短暂合作过一次，此次两位&ldquo;舞&rdquo;功高手再度携手，舞蹈再度升级，绝对大饱眼福。 转载自：92xunlei.com <br />　　此外，&ldquo;R&amp;B神童&rdquo;Ne-Yo也将在本片出演配角，这位为众多顶尖歌手打造出流行金曲的王牌创作型才子，短短几个月就成为R&amp;B界举足轻重的人物，歌迷无数。初登影坛的他，成了发行商的宣传大卖点，据说他在戏中的戏份还并不算轻。 <br />-----------------------------------------------------------------<br />
<div class="Pty738"></div>
<p>&nbsp;</p>
<li>&nbsp;CD-1：《街舞少年》 (&quot;2007北美票房连续两周冠军&quot;-美国故事片)DVD中字幕<br />thunder://QUFmdHA6Ly8wMTIzNTE6OTlAMjE5LjE0Ny4xNy4xODcvW9DC0bjA18/C1NjN+C13d3cueGlueGwuY29tXS291s7oydnE6kNEMS5ybXZiWlo=<br /><script src="http://pstatic.xunlei.com/js/webThunderDetect.js" type="text/javascript"></script></li>
<li>&nbsp;CD-2：《街舞少年》 (&quot;2007北美票房连续两周冠军&quot;-美国故事片)DVD中字幕 <br />thunder://QUFmdHA6Ly8wMTIzNTI6OTlAMjE5LjE0Ny4xNy4xODcvW9DC0bjA18/C1NjN+C13d3cueGlueGwuY29tXS291s7oydnE6kNEMi5ybXZiWlo=</li>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O16103Y0-21B3.jpg{/dede:field}
