<?php
$z[0]=Array("field","三十姑娘一朵花/女孩梦三十BD中",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","三十姑娘一朵花/女孩梦三十BD中英双字1024/1280高清迅雷下载、免费下载，三十姑娘一朵花/女孩梦三十BD中英双字1024/1280高清Gvod高清在线播放，剧情介绍等。",72,262);
$z[1][4]['name']="description";
$z[2]=Array("field","三十姑娘一朵花/女孩梦三十BD中英双字1024/1280高清",264,350);
$z[2][4]['name']="title";
$z[3]=Array("field","",352,391);
$z[3][4]['name']="writer";
$z[4]=Array("field","",393,432);
$z[4][4]['name']="source";
$z[5]=Array("field","2012-05-03",434,484);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",486,523);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://e37:e37@xl2.eee4.com:9024/[3E电影站www.eee4.com]三十姑娘一朵花BD中英双字.rmvb\" target=\"_blank",525,663);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MOIU20-5DF.jpg",665,745);
$z[8][4]['name']="litpic";

?>