{dede:field name='keywords'}王者之心/崔斯坦和依索德/特里斯{/dede:field}
{dede:field name='description'}王者之心/崔斯坦和依索德/特里斯坦和伊索尔德[HD中英双字1024x576高清版]迅雷下载、免费下载，王者之心/崔斯坦和依索德/特里斯坦和伊索尔德[HD中英双字1024x576高清版]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}王者之心/崔斯坦和依索德/特里斯坦和伊索尔德[HD中英双字1024x576高清版]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2010-03-04{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://3e:3e@m1.3edyy.com:1387/【3E电影院www.3edyy.com】王者之心HD中英双字1024x576高清版.rmvb" target=_blank>ftftp://3e:3e@m1.3edyy.com:1387/【3E电影院www.3edyy.com】王者之心HD中英双字1024x576高清版.rmvb</A></TD></TR></TBODY></TABLE><STRONG><FONT color=#ff0000 size=2>欧美经典火热战争爱情史诗巨片《王者之心》DVD中英字幕[800分辨率]－来自[3E电影站eee4.cc]：<IMG src="httftp://www.3edyy.com/templets/img/down.jpg" border=0><BR></FONT></STRONG>CD1：<BR>
<TABLE style="BORDER-RIGHT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; BORDER-BOTTOM: #cccccc 1px dotted" cellSpacing=0 cellPadding=6 width="95%" align=center border=0>
<TBODY>
<TR>
<TD style="WORD-WRAP: break-word" bgColor=#fdfddf><ANCHOR></ANCHOR><A href="ftftp://d81:d81@ftp.eee4.com:1501/[3E电影站www.eee4.com]王者之心DVD中英双字CD1.rmvb" target=_blank>ftftp://d81:d81@ftp.eee4.com:1501/[3E电影站www.eee4.com]王者之心DVD中英双字CD1.rmvb</A></TD></TR></TBODY></TABLE>CD2：<BR>
<TABLE style="BORDER-RIGHT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; BORDER-BOTTOM: #cccccc 1px dotted" cellSpacing=0 cellPadding=6 width="95%" align=center border=0>
<TBODY>
<TR>
<TD style="WORD-WRAP: break-word" bgColor=#fdfddf><ANCHOR></ANCHOR><A href="ftftp://d81:d81@ftp.eee4.com:1501/[3E电影站www.eee4.com]王者之心DVD中英双字CD2.rmvb" target=_blank>ftftp://d81:d81@ftp.eee4.com:1501/[3E电影站www.eee4.com]王者之心DVD中英双字CD2.rmvb</A></TD></TR></TBODY></TABLE>CD3：<BR>
<TABLE style="BORDER-RIGHT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; BORDER-BOTTOM: #cccccc 1px dotted" cellSpacing=0 cellPadding=6 width="95%" align=center border=0>
<TBODY>
<TR>
<TD style="WORD-WRAP: break-word" bgColor=#fdfddf><ANCHOR></ANCHOR><A href="ftftp://d81:d81@ftp.eee4.com:1501/[3E电影站www.eee4.com]王者之心DVD中英双字CD3.rmvb" target=_blank>ftftp://d81:d81@ftp.eee4.com:1501/[3E电影站www.eee4.com]王者之心DVD中英双字CD3.rmvb</A></TD></TR></TBODY></TABLE></div><ul class="mmlist{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MP600230-54357.jpg{/dede:field}
