{dede:field name='keywords'}风中奇缘BD国语配音中字1024高清{/dede:field}
{dede:field name='description'}风中奇缘BD国语配音中字1024高清经典动画迅雷下载、免费下载，风中奇缘BD国语配音中字1024高清经典动画Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}风中奇缘BD国语配音中字1024高清经典动画{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-04-01{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://ec1.images-amazon.com/images/I/51D605MGK8L._.jpg" /></p>
<p>
	◎译　　名　风中奇缘<br />
	◎片　　名　Pocahontas<br />
	◎年　　代　1995<br />
	◎国　　家　美国<br />
	◎类　　别　动画/冒险/剧情/家庭/历史/歌舞/爱情<br />
	◎语　　言　国语配音<br />
	◎字　　幕　中字<br />
	◎IMDB评分&nbsp; 6.2/10 (42,749 votes)<br />
	◎文件格式　x264 + DTS<br />
	◎视频尺寸　1280 x 720<br />
	◎文件大小　1CD<br />
	◎片　　长　1h 13mn<br />
	◎导　　演　迈克&middot;加布里尔 Mike Gabriel<br />
	　　　　　　埃里克&middot;古德伯格 Eric Goldberg<br />
	◎主　　演　艾琳&middot;贝达 Irene Bedard ....Pocahontas (voice)<br />
	　　　　　　梅尔&middot;吉布森 Mel Gibson ....John Smith (voice)<br />
	　　　　　　约翰&middot;卡西尔 John Kassir ....Meeko (voice)<br />
	　　　　　　拉塞尔&middot;敏斯 Russell Means ....Powhatan (voice)<br />
	　　　　　　克里斯蒂安&middot;贝尔 Christian Bale ....Thomas (voice)<br />
	　　　　　　丹尼&middot;曼 Danny Mann ....Percy (voice)<br />
	　　　　　　比利&middot;康诺利 Billy Connolly ....Ben (voice)<br />
	　　　　　　弗兰克&middot;维尔克 Frank Welker ....Flit (voice)<br />
	　　　　　　吉姆&middot;库宁斯 Jim Cummings ....Powanton/Wise Man/Additional Voices (voice) (uncredited)<br />
	　　　　　　Judy Kuhn ....Pocahontas (singing voice)<br />
	　　　　　　大卫&middot;奥根&middot;斯提尔斯 David Ogden Stiers ....Governor Ratcliffe/Wiggins (voice)<br />
	　　　　　　琳达&middot;亨特 Linda Hunt ....Grandmother Willow (voice)<br />
	　　　　　　Joe Baker ....Lon (voice)<br />
	　　　　　　Michelle St. John ....Nakoma (voice)<br />
	　　　　　　James Apaumut Fall ....Kocoum (voice)<br />
	　　　　　　高登&middot;图托西斯 Gordon Tootoosis ....Kekata (voice)<br />
	◎简　　介</p>
<p>
	　　印第安公主波卡洪塔斯Pocahontas传奇的一生在美国是家喻户晓的故事，迪士尼将这位印第安公主的故事搬上银幕，叙述她救了来到新大陆探险的英国上尉约翰&middot;史密斯John Smith，并且化解了一场异族间的战争。</p>
<p>
	　　在勇敢的上尉约翰&middot;史密斯John Smith率领下，一批来自英国拓荒者到达了美洲大陆，占据了印第安人居住的土地，敲响了美丽的印第安公主波卡洪塔斯和她族人们的警钟，也开始了一个建立在欢笑、爱和忠诚上的故事。约翰&middot;史密斯上尉受伤，美丽善良的公主波卡洪塔斯救了上尉，两个敌对阵营不可思议地产生一对恋人，他们用爱情来对抗自己阵营里的冥顽不灵分子。可爱的浣熊米高和小蜂鸟菲莉快乐地穿梭其间：波卡洪塔斯面临改变一生的决定，又必须避免两军冲突，在充满智慧的柳树婆婆帮助下，她学会了倾听自己心中的声音，并且随著风中的色彩去追寻人生的真谛。</p>
<p>
	<br />
	◎幕后制作</p>
<p>
	　　本片强调与自然界的融合以及族群间的尊重，结局也一改迪士尼过去快乐团圆的传统，Pocahontas 选择了留在家乡带领族人，John Smith 则受伤返回英国，留下了一个令人难以释怀的缺憾。本片当初的首映会是在纽约中央公园举办，在露天的大广场上，近十万人围着八部放映机投射在八层楼高的大萤幕上，场面浩浩荡荡，实在是空前的创举，这也是到目前为止规模最大的一场户外电影首映会。另外本片在１９９８年在美国ＡＢＣ电视频道首播时，还将一段原本从电影中删掉的歌曲情节&ldquo;If I Never Knew You&rdquo;又加了回来，成为更完整的版本</p>
<p>
	　　但片中的所有细节都是虚构的。女主角的造型呈现的是美国人审美标准中的东方美女：又黑又大的眼睛、玫瑰花瓣似的嘴唇、随风飘荡的乌黑长发、肌肉若隐若现的健美身材、还有那双毫不纤细的美腿。影片不仅对主角的形象，而且对故事的每个方面都进行了加工，如被侵略的印第安人是好人，英国侵略者自然是坏人。好人中有一个脾气暴躁的，坏人中也有一个良心发现的回头是岸者。好人代表着&ldquo;保护自然、保护动物&rdquo;等时髦思想，坏人代表着不择手段、掠夺资源的资本原始积累时期弊端。两个敌对阵营不可思议地产生一对恋人，他们用爱情来对抗自己阵营里的冥顽不灵分子。影片的说教味太浓，模式缺乏创新，歌曲也偏拗口。1998年推出续集，副标题是《伦敦之旅》。</p>
<p>
	波卡洪塔斯的真实历史</p>
<p>
	　　波卡洪塔斯（Pocahontas ）的真名是 Matoaka ，波卡洪塔斯其实是她的绰号，意思为&ldquo;嬉戏的&rdquo;、&ldquo;顽皮的&rdquo;。她是波瓦坦（Powhatan ）最爱的一位女儿，波瓦坦是生活于美国弗吉尼亚州的亚尔冈京印地安人（Algonquian Indians，即波瓦坦人）的一位重要酋长。</p>
<p>
	　　波卡洪塔斯只有10岁大时，她的人生被永远的改变了。英国殖民者远渡海洋，并在弗吉尼亚州插上了英国国旗，又以英王的名字命名其新的殖民地为詹姆士镇（Jamestown）。外来殖民者在外观及行为上都不同于原住民。对此，当地的波瓦坦部落自然心存疑惧，一些族人都很害怕或甚至痛恨这些与自己相貌、装束不同的陌生人。但是这位酋长的女儿却满心好奇并友善的想了解新移民的事情，她的温和天性及天生的好奇心得到英国人的喜爱及信任。其中殖民领袖约翰&middot;史密斯（John Smith ，即片中的庄迈斯）上尉则指出她的外表、智慧及友好个性都&ldquo;远远超过了其他的波瓦坦人。&rdquo;</p>
<p>
	　　然而不是所有的波瓦坦人都如波卡洪塔斯一般，1607年11月，史密斯遭捕并被囚禁在酋长波瓦坦的首都威尔沃科莫科村(Werowocomoco)。在史密斯日後的传记故事中，最被人称道的便是波卡洪塔斯救了他的性命，据说当时她不顾自身安危挡在史密斯及行刑者之间，说服她的父亲释放他。但这只是波卡洪塔斯帮助英国朋友的诸多事件中的一件，她常会带食物及礼物给殖民地居民，1608年时，年仅12岁的她经过协调，殖民者同意释放波瓦坦囚犯。接下来的两年，她持续的来回奔波在她的父亲及族人之间，并致力于保护殖民地居民。可是尽管她尽了最大的努力，波瓦坦人及英国人之间的紧张局势仍不停升级，因为原住民对英国人持续夺取他们土地之事忍无可忍。最後，双方终于开战，并展开长达五年的冲突。</p>
<p>
	　　1613年，波卡洪塔斯遭英国人囚禁，英方确信她的父亲会赎回他的女儿并结束战争，但是波瓦坦却没有支付，这使得波卡洪塔斯被当作人质长达一年之久。这是父亲确信英国人不会亏待自己女儿下的考虑，而事实也正是如此，波卡洪塔斯在囚禁期间却倍受礼待，并深受殖民者的喜爱及尊敬。也就是在这段时间，殖民者说服她改信基督教，她因此接受洗礼改名为蕾贝卡（Rebecca）。1614年4月，波卡洪塔斯嫁给詹姆士镇的一位殖民约翰&middot;罗尔夫（John Rolfe ，即《风中奇缘2：伦敦之旅》中的罗强恩），两人于詹姆斯敦的教堂举行婚礼，一年之後更是生有一子，取名为托马斯&middot;罗尔夫（Thomas Rolfe ，片中的汤姆斯便是由此得来）。英国方面希望这段婚姻有助于结束波瓦坦人及殖民之间的战争，而她改变信仰能有助于说服剩馀族人一起改信基督教。</p>
<p>
	　　1616年，两人带着儿子乘船返回英国。在英国两人应邀参加了一个不同寻常的假面舞会，而这场舞会的主人就是詹姆斯国王（King James I ，即片中的詹姆国王一世）和王後（相似情节被应用到《风中奇缘2：伦敦之旅》中）。波卡洪塔斯在英国期间有幸与史密斯上尉再次见面，此时距离他们上次见面已有七年。但正当她准备启程回到弗吉尼亚州时，却身染重病。临终前，她没有哀伤，反而安慰丈夫说：&ldquo;所有人都是要死的，只要孩子活着就够了。&rdquo;她死于1617年3月，一生短暂（死于肺炎，终年22岁），下葬于英国葛文森的圣&middot;乔治教堂（Church of St. George）。身处两个&ldquo;世界&rdquo;的朋友及家人都深感悲痛，而她在英国的早逝也意味着波瓦坦人及殖民之间的永续和平机会的丧失</p>

<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.net/" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3117/飘花电影piaohua.com风中奇缘BD国语配音中字1024高清.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3117/飘花电影piaohua.com风中奇缘BD国语配音中字1024高清.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				&nbsp;<a href="ftp://dy44:piaohua@dy44.piaohua.com:3117/飘花电影piaohua.com风中奇缘BD中字1024高清.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3117/飘花电影piaohua.com风中奇缘BD中字1024高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O151X1F-4Y28.jpg{/dede:field}
