{dede:field name='keywords'}港乐x张敬轩交响音乐会高清中字B{/dede:field}
{dede:field name='description'}港乐x张敬轩交响音乐会高清中字BD1280迅雷下载、免费下载，港乐x张敬轩交响音乐会高清中字BD1280Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}港乐x张敬轩交响音乐会高清中字BD1280{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-02-06{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://www.zaslike.com/files/yesen4pcdmmvsyzv5p0.jpg" /></p>
<p>
	【港乐 x 张敬轩交响音乐会】 当张敬轩遇上香港管弦乐团近两小时完美音乐交流 好歌重绎:</p>
<div>
	<p>
		01.&nbsp;Overture<br />
		02.&nbsp;相对论<br />
		03.&nbsp;Stop&nbsp;the&nbsp;Time<br />
		04.&nbsp;骚灵情歌<br />
		05.&nbsp;只是太爱你<br />
		06.&nbsp;留低锁匙<br />
		07.&nbsp;脉搏奔流<br />
		08.&nbsp;蔓珠莎华<br />
		09.&nbsp;大热<br />
		10.&nbsp;明星<br />
		11.&nbsp;故园花茶<br />
		12.&nbsp;春秋<br />
		13.&nbsp;等了又等<br />
		14.&nbsp;追风筝的孩子<br />
		15.&nbsp;迷失表参道<br />
		16.&nbsp;酷爱<br />
		17.&nbsp;壮举<br />
		18.&nbsp;P.S.&nbsp;I&nbsp;Love&nbsp;You<br />
		19.&nbsp;Deadline<br />
		20.&nbsp;余震<br />
		21.&nbsp;樱花树下<br />
		22.&nbsp;笑忘书<br />
		<img alt="" src="http://www.zaslike.com/files/wh4i57t4x8w5a9ra7fsf.jpg" /><img alt="" src="http://www.zaslike.com/files/jus4iumwnjm01gbyat2.jpg" /></p>
	<p>
		&nbsp;</p>
</div>
<p>
	[下载地址]：<img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" /></p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy241:xiaobajie@222.187.221.241:2007/小八戒电影xiaobajie.com港乐x张敬轩交响音乐会高清中字BD1280.mkv">ftp://dy241:xiaobajie@222.187.221.241:2007/小八戒电影xiaobajie.com港乐x张敬轩交响音乐会高清中字BD1280.mkv</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1CK5P-21606.jpg{/dede:field}
