{dede:field name='keywords'}报信的妞BD1280高清迅雷下载，免{/dede:field}
{dede:field name='description'}报信的妞BD1280高清迅雷下载、免费下载，报信的妞BD1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}报信的妞BD1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-13{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://i54.tinypic.com/2vrsos2.jpg" style="width: 619px; height: 800px" /></p>
<p>
	◎译　　名　报信的妞<br />
	◎片　　名　Repo Chick<br />
	◎年　　代　2009<br />
	◎国　　家　美国<br />
	◎类　　别　喜剧<br />
	◎语　　言　英语<br />
	◎IMDB评分 5.4/10 (96 votes)<br />
	◎IMDB链接 <a class="faqlink" href="http://www.xiaozhizhu.net/">http://www.xiaozhizhu.net/</a><br />
	◎片　　长　88 Mins<br />
	◎导　　演　阿力克斯&middot;考克斯 Alex Cox<br />
	◎主　　演　雅克琳&middot;琼特 Jaclyn Jonet &nbsp;....Repo Chick<br />
	　　　　　　Miguel Sandoval &nbsp;....Arizona Gray<br />
	　　　　　　Del Zamora &nbsp;....Lorenzo<br />
	　　　　　　Alex Feldman &nbsp;....Marco<br />
	　　　　　　科洛&middot;韦伯 Chloe Webb &nbsp;....Sister Duncan<br />
	　　　　　　山德&middot;贝克利 Xander Berkeley &nbsp;....Aldrich De La Chasse<br />
	　　　　　　罗姗娜&middot;阿奎特 Rosanna Arquette &nbsp;....Lola (rumored)<br />
	　　　　　　Robert Beltran &nbsp;....Aguas<br />
	　　　　　　凯伦&middot;布莱克 Karen Black &nbsp;....Aunt de la Chasse (rumored)<br />
	　　　　　　扎恩&middot;迈克拉农 Zahn McClarnon &nbsp;....Savage Dave<br />
	　　　　　　Jenna Zablocki &nbsp;....Eggi<br />
	　　　　　　Danny Arroyo &nbsp;....Sixsixsix<br />
	　　　　　　Jennifer Balgobin &nbsp;....Nevavda<br />
	　　　　　　Zander Schloss &nbsp;....Doctor<br />
	　　　　　　Eddie Velez &nbsp;....Justice &#39;Two-Strikes&#39; Espinoza<br />
	　　　　　　Frances Bay &nbsp;....Grandma De La Chasse<br />
	　　　　　　Bennet Guillory &nbsp;....Rogers<br />
	　　　　　　Olivia Barash &nbsp;....Railroad Op<br />
	　　　　　　Tom Finnegan &nbsp;....Senator Fletcher<br />
	　　　　　　Linda Callahan &nbsp;....Rikki Espinoza<br />
	　　　　　　Karen E. Wright &nbsp;....Colonel<br />
	　　　　　　Cy Carter &nbsp;....Lawyer<br />
	　　　　　　Biff Yeager &nbsp;....Golf Course Guard<br />
	　　　　　　Kari French &nbsp;....Reporter<br />
	　　　　　　Andres Carranza &nbsp;....Journalist<br />
	　　　　　　阿力克斯&middot;考克斯 Alex Cox &nbsp;....Professor<br />
	　　　　　　Danbert Nobacon &nbsp;....Major<br />
	　　　　　　Barney Burman &nbsp;....Captain<br />
	　　　　　　Simon Tams &nbsp;....CIA Op<br />
	　　　　　　Russell Darling &nbsp;....Homeland Security<br />
	　　　　　　Olivia Sandoval &nbsp;....Ad Woman<br />
	　　　　　　Angela Sarafyan &nbsp;....Giggli<br />
	　　　　　　Matt Burch &nbsp;....Freddie Mac Offender<br />
	　　　　　　Froylan Tercero &nbsp;....Freddie Mac Offender<br />
	　　　　　　Lyndah Pizarro &nbsp;....Freddie Mac Offender<br />
	　　　　　　Bingo Gubelman &nbsp;....Marina Deadbeat<br />
	　　　　　　Rey Boemi &nbsp;....Cop #1<br />
	　　　　　　Tod Davies &nbsp;....Phone Deadbeat<br />
	　　　　　　X &nbsp;....Bunker Specialist<br />
	　　　　　　C.J. Izzo &nbsp;....Cop #2<br />
	　　　　　　Charles Scheinblum &nbsp;....Detroit Deadbeat<br />
	　　　　　　Sonia Pizarro &nbsp;....Freddie Mac Offender<br />
	　　　　　　Anthony Ausgang &nbsp;....Marina Deadbeat<br />
	　　　　　　Shelley Campbell &nbsp;....Bunker Doorwoman<br />
	　　　　　　Kelly Jones &nbsp;....Freddie Mac Offender<br />
	　　　　　　Vielmehr Klampre &nbsp;....Bunker Doorman<br />
	　　　　　　Julie Selberg &nbsp;....Phone Deadbeat<br />
	　　　　　　Todd Darling &nbsp;....Freddie Mac Offender (uncredited) (unconfirmed)<br />
	　　　　　　Linda Jensen &nbsp;....Freddie Mac Offender (uncredited) (unconfirmed)<br />
	　　　　　　Anton Sipos &nbsp;....Detroit Deadbeat (uncredited) (unconfirmed)<br />
	　　　　　　<br />
	<br />
	◎简　　介　<br />
	<br />
	　　由于回购小鸡，一个富有的很坏的女孩和她的随行人员Pixxi被混合在一个迂回的绑架阴谋里，威胁要消灭洛杉矶市。<br />
	<br />
	　 &nbsp;本片导演阿历克斯&middot;考克斯出生于英国的利物浦，年轻时为了电影梦想中途离开牛津法学院，转到布里斯托大学学习电影。值得一提的是，他在牛津大学的时候曾与英国前首相托尼&middot;布莱尔是校友。至今为止，阿历克斯已经在20多部电影中出演过角色（最近的一部电影是在伊利亚&middot;伍德主演的《牛津杀手》（The Oxford Murders）中饰演&ldquo;卡尔曼&rdquo;一角）。《报信的妞》是阿历克斯自己首次自编，自导，自己制片以及自己主演的影片。这次走的是喜剧路线，女主角Jaclyn Jonet（饰演Repo Chick）是在2007年曾与阿历克斯在影片《Searchers 2.0》有过合作的前任搭档。<br />
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120511/18/62564813201205111818292169872059272_003.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120511/18/62564813201205111818292169872059272_002.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120511/18/62564813201205111818292169872059272_001.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120511/18/62564813201205111818292169872059272_000.jpg" style="width: 720px; height: 405px" /><br />
	&nbsp;</p>
<p>
	【下载地址】</p>
<table bgcolor="#0099cc" border="0" cellpadding="10" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.net/movie/28310.html" target="_blank">http://www.xiaozhizhu.net/movie/28310.html</a></td>
		</tr>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy125:piaohua@dy125.piaohua.com:8052/飘花电影piaohua.com报信的妞BD中英双字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:8052/飘花电影piaohua.com报信的妞BD中英双字1280高清.rmvb</a></td>
		</tr>
		<tr>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15K9C0-53462.jpg{/dede:field}
