{dede:field name='keywords'}谭咏麟2010再度感动演唱会迅雷下{/dede:field}
{dede:field name='description'}谭咏麟2010再度感动演唱会迅雷下载、免费下载，谭咏麟2010再度感动演唱会Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}谭咏麟2010再度感动演唱会{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-10-08{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="/uploads/allimg/c120525/133O0a44620-15227.jpg" /></p>
<p>
	香港乐坛至尊级巨星谭咏麟于今年七月驾临红馆，举行一连八场「2010再度感动演唱会」。Alan在这个充满怀旧味道的派对上施展浑身解数，不搞无谓噱头，纯粹以好歌会友。他特别为演唱会准备了超过一百首歌曲，令每晚的曲目均有所不同。演唱会全长超过三小时，Alan不单大唱数十首八、九十年代脍炙人口的难忘经典，还献上一些过往未受注意的沧海遗珠，令现场观众如痴如醉。他又提携几位后辈当表演嘉宾，包括乐队Mr.、契仔关楚耀和来自北京的女结他手顾爱宁。演唱会现推出蓝光双碟卡拉OK影音专辑，以1920x1080全高清拍摄，收录逾200分钟震撼红馆现场演绎以及逾半小时演唱会制作花絮，让乐迷再三欣赏、再三感动。</p>
<p>
	<br />
	逾200分钟现场演绎</p>
<p>
	动人好歌包括:<br />
	你知我知/ 今夜情为证/ 我爱雀班/ 80岁后/ 幸运星/ 酒红色的心&hellip;&hellip;</p>
<p>
	热情对唱:<br />
	谭咏麟+ 顾爱宁- 望爱/ 披着羊皮的狼,谭咏麟+ 关楚耀- 成功需苦干<br />
	谭咏麟+ Mr. - 约翰人生/ 暴风女神/ 如果我是陈奕迅</p>
<p>
	<br />
	01. Overture<br />
	02. 你知我知<br />
	03. 魔与道<br />
	04. 俗世洪流<br />
	05. 拥抱<br />
	06. Acoustic M&nbsp;&nbsp; edley 1<br />
	i) 今夜情为证<br />
	ii) 情义俩心知<br />
	iii) 我爱雀斑<br />
	iv) 八十岁后<br />
	07. Acoustic M&nbsp;&nbsp; edley 2<br />
	i) 幸运星<br />
	ii) 永不想你<br />
	iii) 迷痴的心<br />
	iv) 还是你懂得爱我<br />
	08. 酒红色的心<br />
	09. 第一滴泪<br />
	10. 凌晨一吻<br />
	11. 爱你两个人<br />
	12. 一个永远不好的伤口<br />
	13. 望爱 (谭咏麟+ 顾爱宁)<br />
	14. 此刻你在何处<br />
	15. M&nbsp;&nbsp; aggie<br />
	16. 冷傲的化妆<br />
	17. 香港&middot; 香港<br />
	18. 知心当玩偶<br />
	19. 爱情陷阱<br />
	20. 成功需苦干 (谭咏麟+ 关楚耀)<br />
	21. 约翰人生(谭咏麟+ Mr.)<br />
	22. Upbeat M&nbsp;&nbsp; edley: (谭咏麟+ Mr.)<br />
	i) Mr. Tam<br />
	ii) 暴风女神Lorelei<br />
	iii) 世界停顿<br />
	iv) 刺客<br />
	23. 如果我是陈奕迅 (Mr.)<br />
	24. 一首歌一个故事<br />
	25. 忘不了您<br />
	26. 幻影<br />
	27. 爱的根源<br />
	28. 爱在深秋<br />
	29. 一生中最爱</p>
<p>
	<br />
	01. 情凭谁来定错对<br />
	02. 那些感动过人的歌<br />
	03. 披着羊皮的狼 (谭咏麟+ 顾爱宁)<br />
	04. 有泪不轻流<br />
	05. 雨丝．情愁<br />
	06. 爱的逃兵<br />
	07. 也曾相识<br />
	08. 最爱的你<br />
	09. 讲不出再见<br />
	10. 偏爱<br />
	11. 高低一起<br />
	12. 无言感激<br />
	13. M&nbsp;&nbsp;&nbsp; AKING OF&hellip;</p>
<p>
	<img alt="" src="/uploads/allimg/c120525/133O0a4560-23420.jpg" style="width: 720px; height: 405px" /><img alt="" src="/uploads/allimg/c120525/133O0a464P-35956.jpg" style="width: 720px; height: 405px" /><img alt="" src="/uploads/allimg/c120525/133O0a4K30-4NP.jpg" style="width: 720px; height: 405px" /><img alt="" src="/uploads/allimg/c120525/133O0a4UP-5O41.jpg" style="width: 720px; height: 405px" /></p>

<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="/uploads/allimg/c120525/133O0T31310-42214.jpg" />&nbsp;&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy125:piaohua@dy125.piaohua.com:6085/飘花电影piaohua.com谭咏麟2010再度感动演唱会BD中字1280高清.rmvb</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O0a49A0-B0N.jpg{/dede:field}
