<?php
$z[0]=Array("field","百夫长/世纪战魂[BD中英双字1024",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","百夫长/世纪战魂[BD中英双字1024x576+1280x720高清版]迅雷下载、免费下载，百夫长/世纪战魂[BD中英双字1024x576+1280x720高清版]Gvod高清在线播放，剧情介绍等。",73,267);
$z[1][4]['name']="description";
$z[2]=Array("field","百夫长/世纪战魂[BD中英双字1024x576+1280x720高清版]",269,357);
$z[2][4]['name']="title";
$z[3]=Array("field","",359,398);
$z[3][4]['name']="writer";
$z[4]=Array("field","",400,439);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-08-22",441,491);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",493,530);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://6e:6e@m1.eee4.cc:1518/【3e电影网www.eee4.cc】世纪战魂DVD中英双字无水印.rmvb\" target=_blank>ftftp://6e:6e@m1.eee4.cc:1518/【3e电影网www.eee4.cc】世纪战魂DVD中英双字无水印.rmvb</A></TD></TR></TBODY></TABLE><BR><FONT color=#ff0000 size=2><STRONG>[下载地址]：<IMG border=0 src=\"httftp://www.3edyy.com/templets/img/down.jpg",532,895);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MP62M20-214U.jpg",897,979);
$z[8][4]['name']="litpic";

?>