{dede:field name='keywords'}芝加哥打鬼/活死人归来BD1280高{/dede:field}
{dede:field name='description'}芝加哥打鬼/活死人归来BD1280高清迅雷下载、免费下载，芝加哥打鬼/活死人归来BD1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}芝加哥打鬼/活死人归来BD1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-21{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img.funshion.com/attachment/images/664/08967432884DF38C745424DEE8527652.jpg" style="width: 500px; height: 592px" /></p>
<p>
	◎译　　名　芝加哥打鬼<br />
	◎片　　名　The Return of the Living Dead<br />
	◎又　　名 &nbsp;活死人归来/芝加哥打鬼<br />
	◎年　　代　1985-05-15<br />
	◎国　　家　美国<br />
	◎类　　别　恐怖片<br />
	◎语　　言　<br />
	◎字　　幕　<br />
	◎片　　长　91min<br />
	◎导　　演　Dan O&#39;Bannon<br />
	◎主　　演 &nbsp;Clu Gulager &nbsp; &nbsp;<br />
	James Karen &nbsp; &nbsp;<br />
	Don Calfa &nbsp; &nbsp;<br />
	Thom Mathews &nbsp; &nbsp;<br />
	Beverly Randolph<br />
	<br />
	◎官方网站：<a href="http://www.bluemv.com">http://www.bluemv.com</a><br />
	◎简　　介　<br />
	<br />
	　佛瑞迪和法兰克发现了僵尸坟场，结果不小心将美军留下的化学毒气外泄，僵尸全部都复活了，一大群在外游荡的不良少年，成了这些从地底爬出的僵尸所攻击的对象，结果美军携带大批尖端武器展开攻击，但是僵尸愈来愈多&hellip;&hellip;<br />
	&nbsp; &nbsp;佛瑞迪和法兰克发现了僵尸坟场，结果不小心将美军留下的化学毒气外泄，僵尸全部都复活了，一大群在外游荡的不良少年，成了这些从地底爬出的僵尸所攻击的对象，结果美军携带大批尖端武器展开攻击，但是僵尸愈来愈多&hellip;&hellip;。一部典型的僵尸电影，从鬼怪巨匠乔治罗密欧1968年的作品「活死人」所衍生的另一杰作，全片在化妆技巧已达一流水准，气氛塑造完全掌握住观众情绪，上映时可谓热潮不断，十分成功。<br />
	&nbsp; &nbsp;<br />
	僵尸电影的CULT典范作品&mdash;&mdash;《芝加哥打鬼》<br />
	&nbsp; &nbsp;由丹&middot;欧班农执导的《The Return of the Living Dead》，在华语地区几乎从来没有发行过正版音像制品，但若提起《芝加哥打鬼》这个名字，相信国内僵尸CULT电影的粉丝一定会&ldquo;肾上腺素&rdquo;激增。这是一部没有大投资、也没有大明星的典型CULT电影，某种意义上也可视作从僵尸类型片巨匠乔治&middot;罗密欧1968年的作品《活死人》所派生出来的一部衍生电影。即使以现今的眼光来审视，全片在化妆技巧的运用上也已达主流水准，完全弥补了彼时电脑特效技术不足的软肋。<br />
	<br />
	故事始自佛瑞迪和法兰克在地下仓库发现了僵尸储藏罐，结果不小心将美军留下的化学毒气外泄，几番折腾之下，最终竟然导致复活墓地的僵尸全部都从地底下爬了出来。一大群在外游荡的不良少年，成了这些从地底爬出的僵尸所攻击的对象，结果美军携带大批尖端武器展开攻击，但是僵尸愈来愈多&hellip;&hellip; 大多数被称为cult电影的影片，都在最初的影院放映中表现不佳，在赢得大众口碑方面铩羽而归。但在随后的影碟租借及售卖中会一扫颓气，创造与影院上映收入相比更显丰厚的进帐。但导演丹&middot;欧班农在《芝加哥打鬼》中显然对娱乐要素的把握更为准确，尤其是电影中气氛的营造完全掌握住观众情绪，上应时可谓热潮不断，十分成功。以B级片本身的定位来看， 乔治&middot;罗密欧对于血腥暴力镜头和色情裸露镜头的处理，都属于恰到好处的点到即止，满足了一般观众的口味，又不至于太过。倒是喜剧噱头的运用，较好的点缀了整部电影，&ldquo;荤素搭配&rdquo;很是协调。鉴于贝弗利&middot;伦道夫、汤姆&middot;马修斯 、詹姆斯&middot;卡伦等一票主演都是&ldquo;花小钱办大事&rdquo;的主儿，在有限资金的支持下，整部电影还是颇有几幕可撼动眼球的视觉效果混战戏，而结尾的创意只怕是拍摄资金捉襟见肘之下的智慧。<br />
	<br />
	在市面版本的配置上，我们看到的是&ldquo;日二豪华限定收藏版+一区MGM/UA宽屏版+优质中文字幕+中文僵尸字幕+绝版OST&rdquo;的制作，应该说，这已是迄今为止我们所能看到的最好的版本了。米高梅本身经营不善的现状，导致了其虽握有庞大而经典的片库，却奈何无法运作，索尼对这类CULT电影也不怎么待见。日二版的画面修复，在光线充裕之处画面的清晰度还尚可，但暗景部分则有明显的粗糙效果，颗粒感很强，虽不至于影响清晰度，但观赏效果显然打了折扣。至于音效方面，如此热闹的一部戏，也只有杜比音轨的助阵，如果较真儿的话，环绕效果方面也实在是纰漏不少，谈不上细致。不过，相信CULT电影并不会太计较这些，因为米高梅在花絮上做足功课的诚意应该能弥补在正片音画方面的无所作为。就信息量而言，本片的演职员访谈、业内同行访谈和特效设计等环节都是十足二十多分钟的内容，评论音轨和僵尸字幕的娱乐性也相当足够，市面版本的汉化绝对不容错过。而甚少在同类型片中出现的电影原声配乐也得益于国内碟商的制作诚意，被收录其中，作为数码平台上的一款优秀作品，收藏价值甚高。</p>
<p>
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120516/13/62564813201205161334272723111190516_004.jpg" style="width: 650px; height: 366px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120516/13/62564813201205161334272723111190516_003.jpg" style="width: 650px; height: 366px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120516/13/62564813201205161334272723111190516_002.jpg" style="width: 650px; height: 366px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120516/13/62564813201205161334272723111190516_001.jpg" style="width: 650px; height: 366px" /><br />
	<br />
	<br />
	&nbsp;</p>
<p>
	【下载地址】</p>
<table bgcolor="#0099cc" border="0" cellpadding="10" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.net" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy125:piaohua@dy125.piaohua.com:8072/飘花电影piaohua.com芝加哥打鬼BD中字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:8072/飘花电影piaohua.com芝加哥打鬼BD中字1280高清.rmvb</a></td>
		</tr>
		<tr>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1643U20-43140.jpg{/dede:field}
