<?php
$z[0]=Array("field","闪电/私法制裁高清720P,1280*720",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","闪电/私法制裁高清720P 1280*720迅雷下载、免费下载，闪电/私法制裁高清720P 1280*720Gvod高清在线播放，剧情介绍等。",73,227);
$z[1][4]['name']="description";
$z[2]=Array("field","闪电/私法制裁高清720P 1280*720",229,297);
$z[2][4]['name']="title";
$z[3]=Array("field","",299,338);
$z[3][4]['name']="writer";
$z[4]=Array("field","",340,379);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-08-02",381,431);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",433,470);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://dy67:piaohua@dy67.piaohua.com:1022/飘花电影下载站www.piaohua.com闪电720p.mkv",472,593);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MP3N3F-2S94.jpg",595,676);
$z[8][4]['name']="litpic";

?>