{dede:field name='keywords'}跟踪孔令学HD1280高清迅雷下载，{/dede:field}
{dede:field name='description'}跟踪孔令学HD1280高清迅雷下载、免费下载，跟踪孔令学HD1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}跟踪孔令学HD1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-02-12{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://www.hdstar.org/attachments/20120209/20120209114758f15c7360b999537ef30256653ebdd16d.jpg" style="width: 500px; height: 737px" /></p>
<p>
	中 文 名： 跟踪孔令学<br />
	出品时间： 2011年4月30日<br />
	出品公司： 中国中影集团公司<br />
	制片地区： 中国内陆<br />
	导 &nbsp; &nbsp; 演： 张骁<br />
	编 &nbsp; &nbsp; 剧： 白铁军<br />
	制 片 人： 江平<br />
	主 &nbsp; &nbsp; 演： 范伟， 孙宁<br />
	类 &nbsp; &nbsp; 型： 喜剧，悬疑<br />
	拍摄地点： 辽宁 本溪 沈阳<br />
	出 品 人： 韩三平<br />
	总 策 划： 史东明、赵海城<br />
	<br />
	　 &nbsp;《跟踪孔令学》讲的是范伟扮演的语文老师，因为一次在课堂上没收了一个女生的手机，而引发了女生 男友的跟踪事件。虽然都是一群小人物的故事，但发生在孔令学这位普通东北小城市知识分子身上的故事，更能折射出现代社会人与人之间隔阂、猜忌、欠缺安全感等社会问题，极具警醒意义。 　<br />
	<br />
	&nbsp;　由范伟、孙宁、马伊琍主演的黑色惊悚喜剧《跟踪孔令学》将于2011年4月30日正式上映。在影片中，范伟和孙宁继电视剧《老大的幸福》后再度合作，出演银幕情侣。与前一次的难成眷属不同，此次两人以夫妻身份出演电影，但在这对夫妻的生活过程中也出现了不少插曲，在片中范伟竟然与孙宁上演了一幕&ldquo;打戏&rdquo;，最终导致妻子骨折，他自己也痛苦不堪。<br />
	<br />
	　　《跟踪孔令学》是一部黑色幽默惊悚喜剧，归根到底确是一部讲述草根人物的影片。影片拍摄之初，便将目光放在了草根阶层。没有个人英雄主义，没有刀枪剑雨，有的只是一出出让人感动和惊叹的生活场景。据片方介绍，范伟在银幕中一直以各种小人物获得观众认可，因而这次出演教师定然能塑造一个有血有肉的角色。据悉，银幕中专门描述教师的题材很少，而通过惊悚喜剧的形式更少，这次选择这种题材一方面是要送给所有教师一个礼物。另一方面则是因为剧中所描述的小城市教师很能代表草根阶层的生活状态。而范伟也进行了为期20天的教师体验，不光要接受10位退休教师的言传身教，还要到当地学校进行讲课。<br />
	<br />
	　　范伟在片中饰演了一名叫做孔令学的老师，孙宁则饰演他的妻子丽丽。据影片导演张骁介绍，《跟踪孔令学》的剧本就是为范伟量身打造的，男一号自然非他莫属，&ldquo;正在苦于女一号的选择时，范伟推荐了和他在《老大的幸福》中合作过的孙宁。&rdquo;两人在该剧中的合作非常默契，观众也非常希望两人能走到一起。对此范伟戏称自己正是因为在《老大的幸福》中没能和孙宁走到一起，所以才希望通过这次的机会来&ldquo;终成眷属&rdquo;。<br />
	<br />
	&nbsp; &nbsp;&ldquo;虽然我俩终成眷属了，但是这对夫妻也有不幸福的时候。&rdquo;出演一部悬疑喜剧，范伟除了要发挥自己的搞笑功力之外，还要将观众带入影片悬疑的氛围当中。在整部电影中，孔令学都被一个似有似无的社会青年跟踪，他则不停的摆脱那个人。由于心理压力过大，也导致了夫妻生活的矛盾，范伟和孙宁在影片最后竟然戏剧性的上演了一幕&ldquo;打戏&rdquo;，丽丽被孔令学打到了骨折。影片拍摄结束后很久孙宁还不停的感叹：&ldquo;从来没见过范伟如此狰狞的面孔，真的吓了我一跳，原来他演悬疑电影都这么厉害！<br />
	<br />
	　　有着宅男之称的范伟不仅彻夜狂奔五公里，更为在喜剧中体现惊悚挑战心理极限，一度变身&ldquo;惊悚男教师&rdquo;。由于拍摄场地位于东北辽宁本溪市，零下30摄氏度的情况下范伟需要彻夜狂奔，躲避跟踪。&ldquo;路上都是结冰，范伟不光要一路狂奔，甚至还有追车的戏份。&rdquo;片方表示，因为范伟前后奔跑距离超过五公里，所以被剧组笑称为&ldquo;范跑跑&rdquo;。另一方面影片主打惊悚情节，因此作为主演范伟也在心理上遭受折磨。&ldquo;自从拍摄这部影片心跳频率就陡然增高，&rdquo;范伟说，不过他对这种&ldquo;过山车&rdquo;式的心理情绪还挺有兴趣，所以才答应接拍这部电影，但演完之后他却有点心理阴影。<br />
	&nbsp;</p>
<p>
	<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120212/03/62564813201202120310392670312498545_004.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120212/03/62564813201202120310392670312498545_003.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120212/03/62564813201202120310392670312498545_002.jpg" style="width: 720px; height: 405px" /><br />
	&nbsp;</p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>


<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="&#13;&#10;ftp://dy125:piaohua@dy125.piaohua.com:7600/飘花电影piaohua.com跟踪孔令学HD国语中字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:7600/飘花电影piaohua.com跟踪孔令学HD国语中字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O16062610-41950.jpg{/dede:field}
