{dede:field name='keywords'}梦幻珊瑚海：唤醒BD中英双字1024{/dede:field}
{dede:field name='description'}梦幻珊瑚海：唤醒BD中英双字1024高清迅雷下载、免费下载，梦幻珊瑚海：唤醒BD中英双字1024高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}梦幻珊瑚海：唤醒BD中英双字1024高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-10-26{/dede:field}
{dede:field name='body'}<p>
	<img alt="" border="0" src="http://img.album.pchome.net/54/84/39/07/ee97be065fc4fb9f84f5fb8e98b270b4.jpg" /></p>
<p>
	◎中文译名　珊瑚海之梦: 唤醒<br />
	◎影片原名　Coral Sea Dreaming Awaken<br />
	◎出品年代　2010<br />
	◎国　　家　意大利/澳大利亚<br />
	◎类　　别　纪录<br />
	◎语　　言　英语<br />
	◎字　　幕　中英双字<br />
	◎文件格式　BD-RMVB<br />
	◎视频尺寸　1024 x 576<br />
	◎文件大小　1CD<br />
	◎片　　长　1:28:08 (h:m:s)<br />
	◎导　　演　<br />
	◎主　　演　</p>
<p>
	◎简　　介　</p>
<p>
	&nbsp;&nbsp;&nbsp; Thousands of tons of war wreckage sank into the fabled lagoons of the South Pacific islands during the naval and air battles of World War II. But instead of devastating the region&rsquo;s underwater ecology, the detritus of human conflict turned into artificial reefs, upon which fantastic mini-ecosystems took shape. NATURE gives viewers a new perspective on wildlife in the South Pacific when its cameras board the WAR WRECKS OF THE CORAL SEAS.</p>
<p>
	&nbsp;&nbsp;&nbsp; The Solomon Islands and the waters that surround them constitute an enormous battlefield, where 60 years ago U.S. Navy and Marine forces began a monumental assault that eventually would drive Japanese forces northward, back toward their homeland. In addition to its enormous human toll, the fighting left countless ships and aircraft, including fuel and noxious cargo, on the beds of the formerly pristine shallow waters. Surprisingly, however, this intrusion into paradise did not repel wildlife from those waters. Instead, it attracted it.</p>
<p>
	&nbsp;&nbsp;&nbsp; 从在1999年的&ldquo;梦想的珊瑚海&rdquo;的创造者。令人惊叹的电影，打开生命和死亡的大堡礁，澳大利亚Ningaluu礁和珊瑚礁巴布亚新几内亚深处。获奖的著名电影制片人大卫汉南工作了7年来创造这种非凡的水下世界的神奇的录像证据。音乐作曲家的Tania玫瑰。在运动中，你会看到数千种海洋生物的珊瑚礁。</p>
<p>
	&nbsp;&nbsp;&nbsp; 珊瑚海梦 - 醒世非凡超过84分钟，进入生活非常的心脏 - 珊瑚礁 - 和死亡。跨越500万年前和星，地球上最具有异国情调和奇妙的海洋生物，它是一个故事。珊瑚是行星上最伟大的自然建筑师，珊瑚礁享有任何生态系统生物多样性最高的。</p>
<p>
	&nbsp;&nbsp;&nbsp; 艾美奖获奖摄影师大卫汉南已连续7年拍摄，创造我们非凡的海底世界，这个宏伟的见证设置为原始分数由塔尼娅玫瑰。我们满足数以千计的珊瑚礁居民，从古代龟喂鲨鱼，可爱的俾格米人海马和野蛮的海蛞蝓，见证了鳐芭蕾和拉拢章鱼。专门的国家的最先进的高清技术以前所未有的亲密捕获这些生命，展示精心设计的求爱，交配仪式，侵袭，激烈的夜间捕食，自相残杀，化学战。</p>
<p>
	&nbsp;&nbsp;&nbsp; 大卫汉南是著名的不仅为他的电影制作，而且他的电影是由激活的保护。这是他的工作背后的推动力。<br />
	充满异国海洋生物的场景惊人的高清，这是大卫汉南区的最新的水下的杰作，到另一个世界的窗口&ldquo;的先进的虚拟体验状态&rdquo;。</p>
<p>
	&nbsp;&nbsp;&nbsp; 许多序列前从未拍过。有些人可能永远不会被再次拍摄。珊瑚生存的5大灭绝。但他们能否生存呢？</p>
<p>
	&nbsp;&nbsp;&nbsp; 拍摄了三个伟大的珊瑚礁生态系统;超过2000潜水大堡礁，宁哥路珊瑚礁，巴布亚新几内亚，珊瑚海梦 - 醒世是庆祝的珊瑚礁，气候变化和海洋酸化的威胁下。有很多工作要做，以安全守卫这些珍贵的生态系统为子孙后代。而很少的时间来做到这一点。</p>

<p>
	<img alt="" border="0" src="http://img.album.pchome.net/54/84/39/07/19dbb09f5962e0d679b70d061b460b65.jpg" /></p>
<p>
	<img alt="" border="0" src="http://img.album.pchome.net/54/84/39/07/22a8180a80638607532aedca1b47cba7.jpg" /></p>

<p>
	[下载地址]：&nbsp;&nbsp;
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:1914/飘花电影piaohua.com梦幻珊瑚海：唤醒BD中英双字1024高清.rmvb ">ftp://dy44:piaohua@dy44.piaohua.com:1914/飘花电影piaohua.com梦幻珊瑚海：唤醒BD中英双字1024高清.rmvb </a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1C42620-294B.jpg{/dede:field}
