{dede:field name='keywords'}行星地球特别版：雪豹BD中字1024{/dede:field}
{dede:field name='description'}行星地球特别版：雪豹BD中字1024/1280高清纪录片迅雷下载、免费下载，行星地球特别版：雪豹BD中字1024/1280高清纪录片Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}行星地球特别版：雪豹BD中字1024/1280高清纪录片{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-01-28{/dede:field}
{dede:field name='body'}<p>
	◎译　　名　行星地球特别版：雪豹<br />
	◎片　　名　Planet Earth Bonus Snow Leopard<br />
	◎年　　代　2006<br />
	◎国　　家　美国<br />
	◎类　　别　记录片<br />
	◎语　　言　英语<br />
	◎字　　幕　中字<br />
	◎文件格式　BD-RMVB<br />
	◎视频尺寸　1024 x 576/1280x 720<br />
	◎文件大小　1CD<br />
	◎片　　长　48 mins 52 seconds<br />
	◎导　　演　艾雷斯泰&middot;法瑟吉尔 Alastair Fothergill ....(11 episodes, 2006)<br />
	◎编　　剧　大卫&middot;爱登堡 David Attenborough ....(5 episodes, 2006)<br />
	◎主　　演　大卫&middot;爱登堡 David Attenborough .... Narrator<br />
	<br />
	◎简　　介　<br />
	<br />
	　　欢迎来到雄伟的多山的国家巴基斯坦。在这里，在一个僻静的山洞，从窥探隐藏的，是一种对雪豹的庇护 - 该系列最稀有的大型猫科动物，代表最美丽的动物。您将有进入世界未开发的部分难忘的旅程，亲身观看这些优美的动物。每年，雪豹将返回到洞穴，以带领他们的孩子在这里。你可以看到他们如何狩猎，了解他们的习惯和特点。电影 - 试图显示的地方，这是许多人认为危险和荒凉形成了鲜明的美感。<br />
	<br />
	<img alt="" border="0" src="http://img.album.pchome.net/54/85/07/05/4d295133ae20f092fe7af3c853a4417a.jpg" /><br />
	<img alt="" border="0" src="http://img.album.pchome.net/54/85/07/05/ada0f5314218bfb8e0e8737ae8d85a7c.jpg" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2677/飘花电影piaohua.com行星地球特别版：雪豹BD中字1024高清.rmvb">&nbsp;ftp://dy44:piaohua@dy44.piaohua.com:2677/飘花电影piaohua.com行星地球特别版：雪豹BD中字1024高清.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy241:xiaobajie@dy241.piaohua.com:2052/小八戒电影xiaobajie.com行星地球特别版：雪豹中字720p.rmvb">&nbsp;ftp://dy241:xiaobajie@dy241.piaohua.com:2052/小八戒电影xiaobajie.com行星地球特别版：雪豹中字1280.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1CHG0-43200.jpg{/dede:field}
