{dede:field name='keywords'}冰与火/龙之编年史/冰与火：魔龙{/dede:field}
{dede:field name='description'}冰与火/龙之编年史/冰与火：魔龙军团BD高清迅雷下载、免费下载，冰与火/龙之编年史/冰与火：魔龙军团BD高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}冰与火/龙之编年史/冰与火：魔龙军团BD高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-12-12{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img165.poco.cn/mypoco/myphoto/20111210/21/62564813201112102150093719927814399_000.jpg" style="width: 354px; height: 500px" /></p>
<p>
	◎译　　名　冰与火/冰与火：龙之编年史/冰与火：天龙传奇/冰与火：魔龙军团<br />
	◎片　　名　Fire &amp;amp; Ice<br />
	◎年　　代　2008<br />
	◎国　　家　罗马尼亚<br />
	◎类　　别　冒险/奇幻/剧情<br />
	◎语　　言　英语<br />
	◎字　　幕　中字<br />
	◎IMDB评分 &nbsp; 4.3/10 (1,398 votes)<br />
	◎IMDB链接 &nbsp; <a href="http://www.imdb.com/title/tt1135493/" target="_blank">http://www.imdb.com/title/tt1135493/</a><br />
	◎文件格式　X264 + DTS<br />
	◎视频尺寸　1280 x 720<br />
	◎文件大小　1 DVD<br />
	◎片　　长　85 minutes<br />
	◎导　　演　皮托夫 Pitof<br />
	◎主　　演　艾米&middot;阿克 Amy Acker ....Princess Luisa<br />
	　　　　　　汤姆&middot;威斯多姆 Tom Wisdom ....Gabriel<br />
	　　　　　　约翰&middot;里斯-戴维斯 John Rhys-Davies ....Sangimel<br />
	　　　　　　阿诺德&middot;沃斯洛 Arnold Vosloo ....King Augustin<br />
	　　　　　　Oana Pellea ....Queen Remini<br />
	　　　　　　拉兹万&middot;瓦西列斯库 Razvan Vasilescu ....Paxian Ru<br />
	　　　　　　Cabral Ibaka ....Pontiero<br />
	　　　　　　奥维度&middot;尼库勒斯库 Ovidiu Niculescu ....King Quilok<br />
	　　　　　　Loredana Groza ....Lila<br />
	　　　　　　Cristian Motiu<br />
	　　　　　 &nbsp;Roxanna Ravenor ....Village woman (uncredited)<br />
	<br />
	<br />
	◎简　　介<br />
	<br />
	　　在人类与龙族共存的大陆，原本与世无争的火龙，忽然发狂般的攻击喀比亚王国，人民哀鸿遍野，国王奥格斯丁为了让人民免于火魔龙威胁，决定接受邻近强大敌国的并吞条件，但公主露易丝坚决反对，她决定出城找回被放逐的屠龙骑士，无奈屠龙骑士已死&hellip;&hellip;<br />
	　　为了拯救王国、人民，以及恢复屠龙骑士的名誉，屠龙骑士之子盖伯里欧决定唤醒多年前被他父亲封印的冰魔龙，因为这是对抗火魔龙的唯一方法；另一方面，公主露易丝发现这一切竟是大臣与邻国间的阴谋，决心率领军团反抗敌国入侵，一场冰火魔龙相争的殊死战，即将展开</p>
<p>
	<img alt="" src="http://img165.poco.cn/mypoco/myphoto/20111211/17/62564813201112111727454769207835721_006.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img165.poco.cn/mypoco/myphoto/20111211/17/62564813201112111727454769207835721_005.jpg" style="width: 720px; height: 405px" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="&#13;&#10;ftp://dy125:piaohua@dy125.piaohua.com:7293/飘花电影piaohua.com冰与火：魔龙军团BD中字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:7293/飘花电影piaohua.com冰与火：魔龙军团BD中字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15W640-1P10.jpg{/dede:field}
