{dede:field name='keywords'}欢乐合唱团,第三季更新21集[中英{/dede:field}
{dede:field name='description'}欢乐合唱团 第三季更新21集[中英双字]2011主打美剧迅雷下载、免费下载，欢乐合唱团 第三季更新21集[中英双字]2011主打美剧Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}欢乐合唱团 第三季更新21集[中英双字]2011主打美剧{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-18{/dede:field}
{dede:field name='body'}<p>
	<img alt="" border="0" height="1026" jquery1316697193906="2" src="http://t.williamgates.net/image-5FD3_4E7968CB.jpg" style="width: 585px; max-width: 780px; height: 822px" width="588" /></p>
<p>
	【译&nbsp;&nbsp;&nbsp; 　名】： 欢乐合唱团<br />
	【原&nbsp;&nbsp;&nbsp; 　名】： Glee<br />
	【年&nbsp;&nbsp;&nbsp; 　代】： 2009|2010|2011<br />
	【国&nbsp;&nbsp;&nbsp; 　家】： 美国<br />
	【类&nbsp;&nbsp;&nbsp; 　别】： 喜剧<br />
	【语&nbsp;&nbsp;&nbsp; 　言】： 英语<br />
	【首&nbsp;&nbsp;&nbsp; 　播】： 2010年09月21日<br />
	【电&nbsp; 视&nbsp; 台】： Fox<br />
	【IMDB评分】： 8.2/10 (31,240 人评价)<br />
	【集&nbsp;&nbsp;&nbsp; 　数】： 预计 22 集<br />
	【片&nbsp;&nbsp;&nbsp; 　长】： 平均 44 分钟<br />
	【导&nbsp;&nbsp;&nbsp; 　演】：&bull; Ryan Murphy...(8集 2009-2011)<br />
	　　　　　　　 &bull; Brad Falchuk...(7集 2009-2011)<br />
	　　　　　　　 &bull; Elodie Keene...(5集 2009-2010)<br />
	　　　　　　　 &bull; Alfonso Gomez-Rejon...(4集 2010-2011)<br />
	　　　　　　　 &bull; Paris Barclay...(3集 2009-2010)<br />
	　　　　　　　 &bull; Bradley Buecker...(3集 2010-2011)<br />
	　　　　　　　 &bull; John Scott...(2集 2009)<br />
	　　　　　　　 &bull; Carol Banker...(2集 2010-2011)<br />
	　　　　　　　 &bull; Eric Stoltz...(2集 2010-2011)<br />
	【编&nbsp;&nbsp;&nbsp; 　剧】：&bull; Ian Brennan...(45集 2009-2011)<br />
	　　　　　　　 &bull; Brad Falchuk...(45集 2009-2011)<br />
	　　　　　　　 &bull; Ryan Murphy...(45集 2009-2011)<br />
	【演&nbsp;&nbsp;&nbsp; 　员】：&bull; Dianna Agron&nbsp; 饰演&nbsp; Quinn Fabray (45集 2009-2011)<br />
	　　　　　　　 &bull; Chris Colfer&nbsp; 饰演&nbsp; Kurt Hummel (45集 2009-2011)<br />
	　　　　　　　 &bull; Jessalyn Gilsig&nbsp; 饰演&nbsp; Terri Schuester (45集 2009-2011)<br />
	　　　　　　　 &bull; Jane Lynch&nbsp; 饰演&nbsp; Sue Sylvester (45集 2009-2011)<br />
	　　　　　　　 &bull; Jayma Mays&nbsp; 饰演&nbsp; Emma Pillsbury (45集 2009-2011)<br />
	　　　　　　　 &bull; Kevin McHale&nbsp; 饰演&nbsp; Artie Abrams (45集 2009-2011)<br />
	　　　　　　　 &bull; Lea Michele&nbsp; 饰演&nbsp; Rachel Berry (45集 2009-2011)<br />
	　　　　　　　 &bull; Cory Monteith&nbsp; 饰演&nbsp; Finn Hudson (45集 2009-2011)<br />
	　　　　　　　 &bull; Matthew Morrison&nbsp; 饰演&nbsp; Will Schuester (45集 2009-2011)<br />
	　　　　　　　 &bull; Amber Riley&nbsp; 饰演&nbsp; Mercedes Jones (45集 2009-2011)<br />
	　　　　　　　 &bull; Mark Salling&nbsp; 饰演&nbsp; Noah &#39;Puck&#39; Puckerman (45集 2009-2011)<br />
	　　　　　　　 &bull; Jenna Ushkowitz&nbsp; 饰演&nbsp; Tina Cohen-Chang (45集 2009-2011)<br />
	　　　　　　　 &bull; Naya Rivera&nbsp; 饰演&nbsp; Santana Lopez (45集 2009-2011)<br />
	　　　　　　　 &bull; Heather Morris&nbsp; 饰演&nbsp; Brittany Pierce (44集 2009-2011)<br />
	　　　　　　　 &bull; Harry Shum Jr&nbsp; 饰演&nbsp; .Mike Chang (37集 2009-2011)<br />
	　　　　　　　 &bull; Mike O&#39;Malley&nbsp; 饰演&nbsp; Burt Hummel (27集 2009-2011)<br />
	　　　　　　　 &bull; Iqbal Theba&nbsp; 饰演&nbsp; Principal Figgins (27集 2009-2011)</p>
<p>
	&nbsp;<img alt="" border="0" height="98" jquery1316697193906="3" src="http://i.imgur.com/3yKzY.jpg" style="max-width: 780px" width="733" /></p>
<p>
	　McKinley高中合唱团曾有过辉煌的过去，他们是这个领域中的佼佼者。随着岁月的流逝，合唱团绯闻不断，丑闻缠身，很多富有才华的年轻人都悄然离开了。现在，这个合唱团成了&ldquo;南郭先生&rdquo;和孤僻学生的&ldquo;避风港&rdquo;。生性乐观的Will接受了校长交办的这项艰巨任务：重塑McKingley合唱团的形象，创造另一次辉煌。Will并不孤独－－因为他有漂亮女教师Emma Pillsbury（Jayma Mays扮演）的全力辅佐。</p>
<p>
	　　在第二季中将会添加三名新角色</p>
<p>
	　　Glee是FOX电视台2009年秋季档一部以音乐为主题的快节奏幽默喜剧，故事以一个性格乐观的高中教师Will Schuester （Matthew Morrison扮演）原本打算发挥自己的余热投入到一个已经解体的唱诗班中，但是面对他的是招来的都是一群性格各异 的&ldquo;怪人&rdquo;；Mercedes（Amber Riley扮演），不光有很强的说服力还经常把自己当成是歌剧中的首席女主角，Kurt（Chris Colfer扮演）有着男高音般天赋却与大家很难相处，Arty（Kevin McHale扮演）是个酷爱演奏吉他的吉他手，可以天生有点残废 ，不然在音乐界一定有些作为，他的好友Tina（Jenna Ushkowitz扮演）是一个酷爱流行音乐的超级粉丝；Rachel Berry（Lea Michele扮演）也是Will Schuester看中的唯一一个像样的歌手，原本自称自己是未来的歌星，一个十全十美主义者，自从遇见 了Will从好友的橄榄球队招来的Finn Hudson（Cory Monteith扮演）后性格大变，Finn原本是学校橄榄球队的四分卫，长着一张 电影明星的脸，而且自己的女朋友是该校队的拉拉队长Quinn（Dianna Agron扮演），他有一个自满清高并同是球友Puck（Mark Salling扮演），除了面对这些形形色色的演员外Will Schuester的妻子Terri Schuester（Jessalyn Gilsig扮演）为生活而抱 怨也曾为了他成功之路的绊脚石，而且学校拉拉队员教练Sue Sylvester（Jane Lynch扮演）对Will所做的一切感到疑惑，幸好 Will得到了漂亮女教师Emma Pillsbury（Jayma Mays扮演）的帮助，而自己也决心做出成就给世人们看看。</p>
<p>
	&nbsp;[下载地址]：</p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:1661/飘花电影piaohua.com欢乐合唱团第三季01.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:1661/飘花电影piaohua.com欢乐合唱团第三季01.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:1686/飘花电影piaohua.com欢乐合唱团.第三季EP02.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:1686/飘花电影piaohua.com欢乐合唱团.第三季EP02.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:1729/飘花电影piaohua.com欢乐合唱团.第三季EP03.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:1729/飘花电影piaohua.com欢乐合唱团.第三季EP03.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:1991/飘花电影piaohua.com欢乐合唱团.第三季EP04.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:1991/飘花电影piaohua.com欢乐合唱团.第三季EP04.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2108/飘花电影piaohua.com欢乐合唱团.第三季EP05.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2108/飘花电影piaohua.com欢乐合唱团.第三季EP05.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2108/飘花电影piaohua.com欢乐合唱团.第三季EP06.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2108/飘花电影piaohua.com欢乐合唱团.第三季EP06.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2289/飘花电影piaohua.com欢乐合唱团.第三季EP07.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2289/飘花电影piaohua.com欢乐合唱团.第三季EP07.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2289/飘花电影piaohua.com欢乐合唱团.第三季EP08.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2289/飘花电影piaohua.com欢乐合唱团.第三季EP08.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2337/飘花电影piaohua.com欢乐合唱团.第三季EP09.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2337/飘花电影piaohua.com欢乐合唱团.第三季EP09.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2662/飘花电影piaohua.com欢乐合唱团.第三季EP10.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2662/飘花电影piaohua.com欢乐合唱团.第三季EP10.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2738/飘花电影piaohua.com欢乐合唱团.第三季EP11.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2738/飘花电影piaohua.com欢乐合唱团.第三季EP11.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2777/飘花电影piaohua.com欢乐合唱团.第三季EP12.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2777/飘花电影piaohua.com欢乐合唱团.第三季EP12.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2831/飘花电影piaohua.com欢乐合唱团.第三季EP13.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2831/飘花电影piaohua.com欢乐合唱团.第三季EP13.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2868/飘花电影piaohua.com欢乐合唱团.第三季EP14.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2868/飘花电影piaohua.com欢乐合唱团.第三季EP14.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3205/飘花电影piaohua.com欢乐合唱团.第三季EP15.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3205/飘花电影piaohua.com欢乐合唱团.第三季EP15.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3252/飘花电影piaohua.com欢乐合唱团.第三季EP16.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3252/飘花电影piaohua.com欢乐合唱团.第三季EP16.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3299/飘花电影piaohua.com欢乐合唱团.第三季EP17.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3299/飘花电影piaohua.com欢乐合唱团.第三季EP17.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3343/飘花电影piaohua.com欢乐合唱团.第三季EP18.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3343/飘花电影piaohua.com欢乐合唱团.第三季EP18.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3380/飘花电影piaohua.com欢乐合唱团.第三季EP19.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3380/飘花电影piaohua.com欢乐合唱团.第三季EP19.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3442/飘花电影piaohua.com欢乐合唱团.第三季EP20.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3442/飘花电影piaohua.com欢乐合唱团.第三季EP20.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3447/飘花电影piaohua.com欢乐合唱团.第三季EP21.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3447/飘花电影piaohua.com欢乐合唱团.第三季EP21.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1A4960-53530.jpg{/dede:field}
