{dede:field name='keywords'}猫的生活(猫在巴黎)DVD中字2011{/dede:field}
{dede:field name='description'}猫的生活(猫在巴黎)DVD中字2011最新法国犯罪神秘动画大片迅雷下载、免费下载，猫的生活(猫在巴黎)DVD中字2011最新法国犯罪神秘动画大片Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}猫的生活(猫在巴黎)DVD中字2011最新法国犯罪神秘动画大片{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-12-13{/dede:field}
{dede:field name='body'}<p>
	<img src="/uploads/allimg/c120525/133O043K60-11C5.jpg" /></p>
<p>
	<img src="/uploads/allimg/c120525/133O043L620-2AN.jpg" /></p>
<p>
	◎译　　名　猫的生活/猫在巴黎<br />
	◎片　　名　A Cat in Paris<br />
	◎年　　代　2010<br />
	◎国　　家　法国/荷兰/瑞士/比利时<br />
	◎类　　别　动画/犯罪/神秘<br />
	◎语　　言　法语<br />
	◎字　　幕　中文<br />
	◎IMDB评分 7.0/10 (from 267 users)<br />
	◎IMDB链接 http://www.imdb.com/title/tt1673702<br />
	◎文件格式　DVD-RMVB<br />
	◎视频尺寸　640 x 336<br />
	◎文件大小　1CD 314MB<br />
	◎片　　长　61 Mins<br />
	◎导　　演　Jean-Loup Felicioli<br />
	　　　　　　Alain Gagnol<br />
	◎主　　演　多米尼克&middot;布兰科 Dominique Blanc ....Jeanne (voice)<br />
	　　　　　　Bruno Salomone ....Nico (voice)<br />
	　　　　　　让&middot;本奎 Jean Benguigui ....Victor Costa (voice)<br />
	　　　　　　伯纳蒂特&middot;拉方特 Bernadette Lafont ....Zo&eacute;&#39;s Nanny (voice)<br />
	　　　　　　Oriane Zani ....Zo&eacute; (voice)<br />
	　　　　　　Bernard Bouillon ....Lucas (voice)<br />
	　　　　　　Patrick Ridremont ....A gangster (voice)<br />
	　　　　　　Jacques Ramade ....A gangster (voice)<br />
	　　　　　　Jean-Pierre Yvars ....A gangster (voice)<br />
	　　　　　　Patrick Descamps ....A gangster (voice)<br />
	　　　　　　</p>
<p>
	◎简　　介　</p>
<p>
	　　蒂诺是只猫，它有两个栖身之所。白天，它陪伴警察让娜的独生女儿左伊。夜里，它与大盗尼克一起在巴黎的屋顶上飞檐走壁。让娜忙的不可开交，她一边要抓多起珠宝失窃案的来去无踪的盗贼，一边又要监视被头号公敌维克多&middot;柯斯达所觊觎的巨型内罗毕巨人雕像。柯斯达还是杀死一个警察的凶手，这个警察正是让娜的丈夫，左伊的爸爸。悲剧发生以后，左伊便再不发一言。柯斯达和他的同伙被左伊发现的那个夜里，事态极速发展。一场追捕持续到了清晨，所有的人物在此过程中交错，或者互相帮助，或者互相搏斗，一直来到巴黎圣母院的屋顶上。</p>
<p>
	　　一只名叫蒂诺的小猫，看尽巴黎的白天与黑夜。白天，它是小女孩佐伊（Oriane Zani 配音）宠物，每天早上为她带来小礼物。佐伊的父母都是警察，父亲被城中最大的恶棍维克托&middot;科斯塔（Jean Benguigui 配音）杀害，母亲让娜（Dominique Blanc 配音）发誓将科斯塔绳之于法，渐渐忽略了对佐伊的关怀。小佐伊从此封闭了自己，不发一言。每到夜晚，蒂诺便跳出窗户，寻找它另一个生活在黑夜的朋友尼克（Bruno Salomone 配音）。尼克是一个身手敏捷的大盗，他神出鬼没，手法娴熟，不过蒂诺是他唯一的朋友。蒂诺穿梭往来，成为了两个完全不同的人儿间的奇妙纽带。</p>
<p>
	　　某晚，佐伊跟着蒂诺溜出房间，却意外遭遇企图抢劫展览馆石像的科斯塔团伙。佐伊、尼克和让娜纷纷被卷入其中&hellip;&hellip;</p>
<p>
	幕后制作</p>
<p>
	　　《猫的一生》回归原创，全片手工上色，色彩鲜艳饱和，风格上有马蒂斯、莫迪利亚尼、毕加索的影子，很黑色电影，非常不迪士尼。</p>
<p>
	<br />
	◎影片截图</p>

<p>
	<img src="/uploads/allimg/c120525/133O043M530-35563.jpg" /></p>
<p>
	<img src="/uploads/allimg/c120525/133O043N430-46141.jpg" /></p>
<p>
	<img src="/uploads/allimg/c120525/133O043O310-5Z07.jpg" /></p>
<p>
	<img src="/uploads/allimg/c120525/133O043P110-645K.jpg" /></p>

<p>
	[下载地址]：&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:2325/飘花电影piaohua.com猫的生活-猫在巴黎DVD中字.rmvb </td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O043P930-O5J.jpg{/dede:field}
