{dede:field name='keywords'}世界末日(自弹自唱)迅雷下载，免{/dede:field}
{dede:field name='description'}世界末日(自弹自唱)迅雷下载、免费下载，世界末日(自弹自唱)Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}世界末日(自弹自唱){/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2013-03-01{/dede:field}
{dede:field name='body'}<p>
	播放后双击视频&ldquo;全屏&rdquo;</p>
<p>
	<object class="OBJECT" classid="CLSID:22d6f312-b0f6-11d0-94ab-0080c74c7e95" height="350" id="MediaPlayer" width="500"><param name="ShowStatusBar" value="-1" /><param name="Filename" value="http://www.fksz.com/song2/mtv/mm.asf" /></object></p>
<p>
	下载地址</p>
<br />{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O0W212P-C156.gif{/dede:field}
