{dede:field name='keywords'}神秘起源：DC漫画的故事DVD中英{/dede:field}
{dede:field name='description'}神秘起源：DC漫画的故事DVD中英双字迅雷下载、免费下载，神秘起源：DC漫画的故事DVD中英双字Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}神秘起源：DC漫画的故事DVD中英双字{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-06-12{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="/uploads/allimg/c120524/133N4P642F-a622.jpg" style="width: 500px; height: 711px" /></p>
<p>
	◎译　　名　神秘起源：DC漫画的故事/秘密起源:英雄漫画故事<br />
	◎片　　名　Secret Origin The Story of DC Comics<br />
	◎年　　代　2010<br />
	◎国　　家　美国<br />
	◎类　　别　历史/纪录片<br />
	◎语　　言　英语<br />
	◎字　　幕　中英双字幕<br />
	◎IMDB评分 7.6/10 (118 votes)<br />
	◎文件格式　Rmvb<br />
	◎视频尺寸　640 x 360<br />
	◎文件大小　365MB<br />
	◎片　　长　91 Mins<br />
	◎导　　演　Mac Carter<br />
	◎主　　演　瑞安&middot;雷诺兹 Ryan Reynolds ... Narrator<br />
	　　　　　　扎克&middot;施奈德 Zack Snyder ... Himself (archive footage)<br />
	　　　　　　大卫&middot;柯南伯格 David Cronenberg ... Himself (archive footage)<br />
	　　　　　　弗兰克&middot;兰格拉 Frank Langella ... Perry White (archive footage)<br />
	　　　　　　布莱恩&middot;辛格 Bryan Singer ... Himself (archive footage)<br />
	　　　　　　萨姆&middot;亨廷顿 Sam Huntington ... Jimmy Olsen (archive footage)<br />
	　　　　　　玛戈&middot;基德 Margot Kidder ... Lois Lane (archive footage)<br />
	　　　　　　弗朗西斯&middot;劳伦斯 Francis Lawrence ... Himself (archive footage)<br />
	　　　　　　琳达&middot;卡特 Lynda Carter ... Wonder Woman (archive footage)<br />
	　　　　　　弗兰克&middot;米勒 Frank Miller ... Himself (archive footage)<br />
	　　　　　　罗纳德&middot;里根 Ronald Reagan ... Himself (archive footage)<br />
	　　　　　　理查德&middot;唐纳 Richard Donner ... Himself (archive footage)<br />
	　　　　　　乔治&middot;里弗斯 George Reeves ... Clark Kent / Superman (archive footage)</p>
<p>
	◎简　　介　</p>
<p>
	　　这部纪录片将由电影版《绿灯侠》主演瑞安&middot;雷诺兹担当旁白，通过漫画、电影、电视、游戏等多个领域全方位呈现&ldquo;美国超级英雄的摇篮&rdquo;DC漫画75年的发展历程。片中将披露一批从未公开的珍贵档案，还有对部分著名漫画作者的访谈实录，深入展现超人、蝙蝠侠、神奇女侠、闪电侠、绿灯侠诞生的故事。华纳更特邀曾获奥斯卡最佳纪录片提名的《拼字比赛》幕后班底为本片坐镇，由《拼字比赛》导演杰弗里&middot;布里兹出任执行制片人。</p>
<p>
	◎影片截图</p>
<p>
	<img alt="" src="/uploads/allimg/c120524/133N4PA50-103Y0.jpg" style="width: 640px; height: 360px" /></p>
<p>
	<img alt="" src="/uploads/allimg/c120524/133N4PB0F-115I5.jpg" style="width: 640px; height: 360px" /></p>
<p>
	[下载地址]：</p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				ftp://dy172:piaohua@dy172.piaohua.com:200/飘花电影piaohua.com神秘起源.rmvb</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120524/133N4PBD0-12Rb.jpg{/dede:field}
