{dede:field name='keywords'}《咪咁扮嘢》王祖蓝演嘢会/演唱{/dede:field}
{dede:field name='description'}《咪咁扮嘢》王祖蓝演嘢会/演唱会[DVD粤语中字]迅雷下载、免费下载，《咪咁扮嘢》王祖蓝演嘢会/演唱会[DVD粤语中字]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}《咪咁扮嘢》王祖蓝演嘢会/演唱会[DVD粤语中字]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-01-16{/dede:field}
{dede:field name='body'}<IMG src="/uploads/allimg/c120524/133N4RC60-22340.jpg"><BR><BR><BR>◎译　　名　《咪咁扮嘢》王祖蓝演嘢会/演唱会<BR>◎片　　名　Cho Lam Show Off Show<BR>◎年　　代　2010<BR>◎国　　家　香港<BR>◎类　　别　音乐<BR>◎语　　言　粤语<BR>◎字　　幕　中文(部分)<BR>◎IMDB评分 N/A<BR>◎IMDB链接 N/A<BR>◎文件格式　XviD + MP3<BR>◎视频尺寸　576 x 320<BR>◎文件大小　2CD 2 x 50 x 15MB<BR>◎片　　长　151 Min<BR>◎导　　演　<BR>◎主　　演　王祖蓝<BR><BR>◎简　　介　<BR><BR>　　王祖蓝，香港舞台剧演员、电视演员、配音演员、报幕员、电台播音员、主持、司仪、作词、作曲及歌手。小学时就读马鞍山信义学校（与同公司的歌手容祖儿是同班同学），中学就读圣公会曾肇添中学，后升读香港演艺学院，获取戏剧学院一级荣誉艺术学士，主修表演。香港作曲家及作词家协会会员。现为无线电视旗下电影经理人合约艺员及英皇娱乐音乐家唱片旗下合约歌手。2010年反串主持搞笑节目《荃加福禄寿》大受欢迎，人气急升，喜剧才华广受肯定。<BR><BR>　　2010年07月30日至31日在香港伊丽莎伯体育馆举行一连三场《咪咁扮嘢》王祖蓝演嘢会。<BR><BR><BR>
<P>【电影截图】：<BR><BR></P><IMG src="/uploads/allimg/c120524/133N4RE260-3bX.jpg">&nbsp;<BR><IMG src="/uploads/allimg/c120524/133N4RF4F-43602.jpg">&nbsp;<BR><IMG src="/uploads/allimg/c120524/133N4RFR0-55624.jpg">&nbsp;<BR><IMG src="/uploads/allimg/c120524/133N4RG1P-624W.jpg">&nbsp;<BR><IMG src="/uploads/allimg/c120524/133N4RG60-H553.jpg">&nbsp;<BR><IMG src="/uploads/allimg/c120524/133N4RGY0-U648.jpg">&nbsp;<BR><IMG src="/uploads/allimg/c120524/133N4RH1P-bE4.jpg"><BR><BR><BR><BR><BR>【dbank网盘高速下载地址】:<BR>王祖蓝2010年最新演嘢会《咪咁扮嘢》DVD粤语中字<BR><BR>【115网盘高速下载地址】:<BR>王祖蓝2010年最新演嘢会《咪咁扮嘢》DVD粤语中字<BR><BR>王祖蓝2010年最新演嘢会《咪咁扮嘢》DVD粤语中字 [下载地址]：<IMG border=0 src="/uploads/allimg/c120524/133N2Z4FF-102231.jpg"><BR>
<TABLE style="BORDER-BOTTOM: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-RIGHT: #cccccc 1px dotted" border=0 cellSpacing=0 cellPadding=6 width="95%" align=center>
<TBODY>
<TR>
<TD style="WORD-WRAP: break-word" bgColor=#fdfddf>ftp://5e:5e@m1.3edyy.com:1578/【3E看看www.3ekk.com】王祖蓝演唱会[DVD中字].rmvb</TD></TR></TBODY></TABLE>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120524/133N4RHO0-10L06.jpg{/dede:field}
