{dede:field name='keywords'}异形x异种入侵迅雷下载，免费下{/dede:field}
{dede:field name='description'}异形x异种入侵迅雷下载、免费下载，异形x异种入侵Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}异形x异种入侵{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2007-07-17{/dede:field}
{dede:field name='body'}<P>◆中文片名：异形x异种入侵<BR>◆年　　代：2007<BR>◆国家地区：美国<BR>◆类　　别：科幻/灾难/恐怖<BR>◆字　　幕：中文字幕<BR>◆压缩格式：DVD-RMVB<BR>◆文件大小：210MB <BR><BR>◆影片简介：<BR><BR>　　未来地球人类将随时面临天外异种的入侵和威胁，阿兰博士在负责某种天外生物异种的跟踪与研究，此天外生物异种不仅有着强大的杀伤里，而且还可以使地球人类造成致命威胁与毁灭。<BR><BR>　　在一次实验研究中，由于疏忽使此异种重生后而变异，逃出了戒备森严的实验室基地，这种充满杀伤里的天外异种以成倍速度快速增长壮大，地球人类将面临着残酷性的灾难，动用特种部队却难以抵抗其致命攻击，一时间到处都是哭泣与人人都在争相逃命的血腥场面，拯救即将毁灭的地球和无数人类，末日之战即将拉开...... <BR><BR><IMG alt=YiXingX.jpg src="http://www.eee4.com/0701pic/allimg/070717/1339130.jpg" border=0><BR><IMG alt=YiXingX1.jpg src="http://www.eee4.com/0701pic/allimg/070717/1339131.jpg" border=0><BR><IMG alt=YiXingX2.jpg src="http://www.eee4.com/0701pic/allimg/070717/1339132.jpg" border=0><BR><IMG alt=YiXingX3.jpg src="http://www.eee4.com/0701pic/allimg/070717/1339133.jpg" border=0><BR><IMG alt=YiXingX4.jpg src="http://www.eee4.com/0701pic/allimg/070717/1339134.jpg" border=0><BR><IMG alt=YiXingX5.jpg src="http://www.eee4.com/0701pic/allimg/070717/1339135.jpg" border=0></P>
<P>2007-07-17 20:32:11 开始连接......<BR>2007-07-17 20:32:12 开始搜索候选资源......<BR>2007-07-17 20:32:14 搜索到20个候选资源<BR>2007-07-17 20:32:15 使用候选资源进行连接......<BR>2007-07-17 20:32:20 搜索到15个候选资源<BR>2007-07-17 20:32:21 使用候选资源进行连接......<BR>2007-07-17 20:32:21 开始创建文件......<BR>2007-07-17 20:32:23 文件创建成功，开始下载数据......<BR>2007-07-17 20:32:26 用户取消下载&nbsp;&nbsp; 本文来自 www.eee4.com</P>下载地址：<BR>第2集(VCD版)<BR>
<TABLE style="BORDER-RIGHT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; BORDER-BOTTOM: #cccccc 1px dotted" cellSpacing=0 cellPadding=6 width="95%" align=center border=0>
<TBODY>
<TR>
<TD style="WORD-WRAP: break-word" bgColor=#fdfddf><A href="thunder://QUFmdHA6Ly8wNjIyMjk6OTlAMjIyLjE3My43Mi43NS9b0MLRuMDXz8LU2M34LXd3dy54aW54bC5jb21dLdLs0M540uzW1sjrx9Yucm12Ylpa/">《异形x异种入侵》 DVD中字幕(2007美国科幻动作大片)</A> </TD></TR></TBODY></TABLE>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O16493230-222P.jpg{/dede:field}
