{dede:field name='keywords'}泡吧侦探DVD中字2011最新日本动{/dede:field}
{dede:field name='description'}泡吧侦探DVD中字2011最新日本动作历史大片迅雷下载、免费下载，泡吧侦探DVD中字2011最新日本动作历史大片Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}泡吧侦探DVD中字2011最新日本动作历史大片{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-03{/dede:field}
{dede:field name='body'}<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120503/13/56643687201205031355052753690352267_004.jpg" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120503/13/56643687201205031355052753690352267_005.jpg" /></p>
<p>
	【译名】泡吧侦探<br />
	【片名】Phone Call to the Bar<br />
	【年代】2011<br />
	【国家】日本<br />
	【类型】剧情 | 喜剧<br />
	【格式】DVD-RMVB<br />
	【视频】720 x 384 | X264 | 1329 Kbps<br />
	【音频】日语 | AC3 | 448 Kbps<br />
	【体积】657MB | 1CD<br />
	【时间】125 Mins<br />
	【字幕】中文<br />
	【IMDB评分】8.4/10 (9 votes)<br />
	【IMDB链接】<a href="http://www.imdb.com/title/tt1860318">http://www.imdb.com/title/tt1860318</a><br />
	【导演】桥本一<br />
	【演员】松田龙平 | 大泉洋 | 小雪 | 西田敏行<br />
	【剧情】大泉洋饰演一名在北海道札幌红灯区展开活动的私家侦探，松田龙平饰演北海道农业大学的一名助教，在剧中是侦探大泉洋的亲密伙伴。本篇故事主要讲述了泡吧侦探有一天接到一名神秘女子（小雪 饰）的电话，这个电话让他和同伴（松田龙平 饰）卷入了一个危险的新事件。西田敏行将在电影中饰演一名富裕的企业家。</p>
<p>
	<br />
	◎影片截图</p>

<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120503/13/56643687201205031355052753690352267_000.jpg" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120503/13/56643687201205031355052753690352267_003.jpg" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120503/13/56643687201205031355052753690352267_002.jpg" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120503/13/56643687201205031355052753690352267_001.jpg" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.netftp//dy44:piaohua@dy44.piaohua.com:3142/" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3345/飘花电影piaohua.com泡吧侦探DVD中字.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3345/飘花电影piaohua.com泡吧侦探DVD中字.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15A1610-14449.jpg{/dede:field}
