<?php
$z[0]=Array("field","秘社,第一季更新21集[中英双字]2",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","秘社 第一季更新21集[中英双字]2012主打美剧迅雷下载、免费下载，秘社 第一季更新21集[中英双字]2012主打美剧Gvod高清在线播放，剧情介绍等。",73,249);
$z[1][4]['name']="description";
$z[2]=Array("field","秘社 第一季更新21集[中英双字]2012主打美剧",251,330);
$z[2][4]['name']="title";
$z[3]=Array("field","",332,371);
$z[3][4]['name']="writer";
$z[4]=Array("field","",373,412);
$z[4][4]['name']="source";
$z[5]=Array("field","2012-05-05",414,464);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",466,503);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://dy44:piaohua@dy44.piaohua.com:2570/飘花电影piaohua.com秘社第一季01集[中英双字].rmvb",505,633);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MQ0DH0-26250.jpg",635,717);
$z[8][4]['name']="litpic";

?>