{dede:field name='keywords'}古墓丽影2BD中英双字1024/1280高{/dede:field}
{dede:field name='description'}古墓丽影2BD中英双字1024/1280高清迅雷下载、免费下载，古墓丽影2BD中英双字1024/1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}古墓丽影2BD中英双字1024/1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-12-14{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://eee4.com:eee4@xl2.eee4.com:8881/古墓丽影2/[3E迅雷电影站www.eee4.com]古墓丽影2-CD1.rmvb" target="_blank{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MOT5B0-41107.jpg{/dede:field}
