{dede:field name='keywords'}哈尔的移动城堡[HD中英双字1024/{/dede:field}
{dede:field name='description'}哈尔的移动城堡[HD中英双字1024/1280高清版]迅雷下载、免费下载，哈尔的移动城堡[HD中英双字1024/1280高清版]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}哈尔的移动城堡[HD中英双字1024/1280高清版]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-11-23{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://3e:3e@www2.eee4.com:663/[www.eee4.cn提供]哈尔的移动城堡HD中英双字1024x552高清版.rmvb" target="_blank{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MQ21A30-41T6.jpg{/dede:field}
