{dede:field name='keywords'}蓝精灵：圣诞颂歌BD中英双字1024{/dede:field}
{dede:field name='description'}蓝精灵：圣诞颂歌BD中英双字1024高清2011动作短片迅雷下载、免费下载，蓝精灵：圣诞颂歌BD中英双字1024高清2011动作短片Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}蓝精灵：圣诞颂歌BD中英双字1024高清2011动作短片{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-12-26{/dede:field}
{dede:field name='body'}<p>
	<img alt="" height="800" src="/uploads/allimg/c120525/133O04334330-1J626.jpg" width="559" /><br />
	<br />
	<br />
	◎译　　名　蓝精灵：圣诞颂歌<br />
	◎片　　名　The Smurfs A Christmas Carol<br />
	◎年　　代　2011<br />
	◎国　　家　美国<br />
	◎类　　别　动画/短片<br />
	◎语　　言　英语<br />
	◎字　　幕　中英双语字幕<br />
	◎IMDB评分&nbsp;&nbsp;6.1/10 (172 votes)<br />
	◎文件格式　DVD-RMVB<br />
	◎视频尺寸　624 x 352<br />
	◎文件大小　114MB<br />
	◎片　　长　23 Mins<br />
	◎导　　演　Troy Quane<br />
	◎主　　演　杰克&middot;安琪 Jack Angel ....Papa (voice)<br />
	　　　　　　弗莱德&middot;阿米森 Fred Armisen ....Brainy (voice)<br />
	　　　　　　汉克&middot;阿扎利亚 Hank Azaria ....Gargamel (voice)<br />
	　　　　　　Gary Basaraba ....Hefty (voice)<br />
	　　　　　　乔治&middot;洛佩兹 George Lopez ....Grouchy (voice)<br />
	　　　　　　Melissa Sturm ....Smurfette (voice)<br />
	　　　　　　安东&middot;尤金 Anton Yelchin ....Clumsy (voice)<br />
	　　　　　　<br />
	　　　　　　<br />
	<br />
	◎简　　介　<br />
	<br />
	故事中，蓝爸爸和其他蓝精灵唱着圣诞颂歌串门，注意到只有厌厌的家没有装饰。他们上门打听出了什么事，厌厌说他讨厌圣诞节，砰地把门关上，还溅了聪聪一身雪。蓝爸爸回到实验室，希望能发明出让厌厌重新燃起失落的圣诞情绪的东西。<br />
	<br />
	<br />
	<br />
	◎影片截图<br />
	<br />
	<img alt="" height="337" src="/uploads/allimg/c120525/133O04335X0-1WL9.jpg" style="cursor: pointer" width="600" /><br />
	<br />
	<img alt="" height="337" src="/uploads/allimg/c120525/133O0433B10-196415.jpg" style="cursor: pointer" width="600" /><br />
	<br />
	<img alt="" height="337" src="/uploads/allimg/c120525/133O0433H30-201612.jpg" style="cursor: pointer" width="600" /><br />
	<br />
	<img alt="" height="337" src="/uploads/allimg/c120525/133O0433O30-215X5.jpg" style="cursor: pointer" width="600" /><br />
	<br />
	&nbsp;</p>
<p>
	下载地址]：<img border="0" src="http://www.eee4.com/templets/img/down.jpg" /></p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				ftp://dy44:piaohua@dy44.piaohua.com:2445/飘花电影piaohua.com蓝精灵：圣诞颂歌BD中英双字1024高清.mkv</td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				ftp://dy44:piaohua@dy44.piaohua.com:2445/飘花电影piaohua.com蓝精灵之圣诞颂歌.rmvb </td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O04343Z-232034.jpg{/dede:field}
