{dede:field name='keywords'}新岳父大人第ⅠⅡ部BD1280高清中{/dede:field}
{dede:field name='description'}新岳父大人第ⅠⅡ部BD1280高清中字迅雷下载、免费下载，新岳父大人第ⅠⅡ部BD1280高清中字Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}新岳父大人第ⅠⅡ部BD1280高清中字{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-13{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120513/12/17870980201205131211013464405864558_008.jpg" style="width: 650px; height: 910px" /></p>
<p>
	◎译　　名　新岳父大人<br />
	◎片　　名　Father Of The Bride<br />
	◎年　　代　1992<br />
	◎国　　家　美国<br />
	◎类　　别　家庭 / 喜剧<br />
	◎语　　言　英语<br />
	◎IMDB评分 &nbsp; 6.3/10 (30,435 votes)<br />
	◎IMDB链接 &nbsp; <a class="faqlink" href="http://www.imdb.com/title/tt0101862">http://www.imdb.com/title/tt0101862</a><br />
	◎片　　长　125 mins<br />
	◎导　　演　查尔斯&middot;谢尔 Charles Shyer<br />
	◎主　　演　史蒂夫&middot;马丁 Steve Martin .... George Stanley Banks<br />
	　　　　　　黛安娜&middot;基顿 Diane Keaton .... Nina Banks<br />
	　　　　　　B.D.&middot;王 B.D. Wong .... Howard Weinstein<br />
	　　　　　　基兰&middot;卡尔金 Kieran Culkin .... Matty Banks<br />
	　　　　　　马丁&middot;肖特 Martin Short .... Franck Eggelhoffer<br />
	　　　　　　简&middot;埃尔顿 Jane Alden .... voice　　　　　<br />
	<br />
	<br />
	◎简　　介<br />
	<br />
	　　史提夫马丁的[新岳父大人]！看他这次如何诠释一个父亲在女儿出阁前狂夕忐忑不安的心情，又如何让观众捧腹大笑。[新岳父大人]是一部史提大马丁绝不可错过的好戏。<br />
	剧情<br />
	<br />
	　　女儿从欧洲游学归来啦！真是个好消息~~可接下来这个消息，又让我们的史蒂夫&middot;马丁心里不是滋味了--女儿订婚了&hellip;&hellip;难怪有人说：爱情是温馨美丽而又令人愉悦的，除非它发生在你最疼爱的女儿身上；难怪有人认为：女儿的男朋友都是父亲的假想敌。 当爸爸的不由自主地审视自己未来的女婿，总怕人家不合格；同时，也不由自主地反观自己，总怕自己老了。有一回，他一再要求女儿出门时披件外套，女儿都没听话。可人家小伙子一开口，女儿立马把外套披上了。唉，有点醋溜溜的劲儿上来了~~这一切，是不是意味着自己就要失去女儿了呢？<br />
	<br />
	　　有趣的事接连发生，拜访亲家时，好奇的爸爸趁着上洗手间的机会，在房子里东看西看，想摸一摸家底。正巧在抽屉里看到了存折，正想看呢，不料家有忠狗，追得他到了阳台，又逼得他落到了泳池里。天，为了女儿的婚事，他可真是操碎了心。<br />
	<br />
	　　这是个很可爱的老爸，不仅要失去最心爱的女儿，还要付一大笔婚礼费用。一个人250美元，要来527人参加宴会，还要邀请8个丹麦亲戚，意味着要付9个人的往返机票，因为其中一个太胖了要做两个人的位子...<br />
	<br />
	　　&ldquo;不如杀了我&rdquo;他说，立马动员全家开会缩减客人名单，他要取消小儿子唯一的朋友，急得小儿子说：&ldquo;让他来吧，他可以不吃东西。&rdquo;<br />
	<br />
	　　双重打击下的老爸大闹超级市场，与&ldquo;命运&rdquo;作最后徒劳的&ldquo;抵抗&rdquo;，可是女儿总是要嫁人的，婚礼前夜，老爸躺在床上，眼前浮现一幕幕画面，女儿还是个小baby，她戴上学士帽，她出现在楼梯拐角，从扶手滑下，一下扑到老爸爸的怀里...<br />
	<br />
	　　其实，老爸不是吝啬鬼，他只是舍不得女儿，他视婚礼为洪水猛兽，害怕关于婚礼的一切。因为它们的目的只是夺走她，夺走他餐桌对面戴眼镜的小女孩。<br />
	<br />
	　　电影的高潮是一个温馨的大party，一场美丽盛大的婚礼，而失落的老爸并没有被遗忘，很温馨的片子~<br />
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120513/12/17870980201205131211013464405864558_006.jpg" style="width: 640px; height: 360px" /></p>
<p>
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120513/12/17870980201205131211013464405864558_005.jpg" style="width: 640px; height: 360px" /></p>
<p>
	<br />
	&nbsp;</p>
<p>
	导演： 　　Charles Shyer 　　<br />
	主演： 　　斯蒂夫&middot;马丁 Steve Martin 　　<br />
	黛安&middot;基顿 Diane Keaton 　　Martin Short 　　<br />
	类型：家庭 / 喜剧 　　<br />
	更多中文片名：新娘的父亲2 / 新岳父大人之三喜临门 / 呷醋外父2 　　<br />
	片长：106 min 　　<br />
	国家/地区：美国 　　<br />
	对白语言：英语 　　<br />
	发行公司：Falcon 　　<br />
	上映日期：1995年12月8日 美国<br />
	<br />
	剧情梗概：上回，乔治才刚和自己的准女婿斗智斗力，这次，又有什么事让刚当上岳父大人的他头痛不安呢？原来是女儿安妮怀孕了，使乔治再度陷入焦躁恐惧当中，正当乔治稍稍释怀时，又发生了一件让他晕倒的消息，老婆妮娜也怀孕了&hellip;&hellip; 　　当乔治&middot;班克斯（史帝夫&middot;马丁饰）的妻子和新婚不久的女儿同时向他宣布怀孕时，也感到了严重的中年危机。他觉得自己再当一次爸爸，其实有点老了，可还绝没有老到要当外公的地步。正当全家人都焦急地等待孩子出生的时候，乔治&middot;班克斯却走火入魔，不惜一切地试图证明自己依然年轻，依然有魅力，结果出尽泣相，令人捧腹大笑。</p>
<p>
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120513/12/17870980201205131211013464405864558_001.jpg" style="width: 640px; height: 360px" /></p>
<p>
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120513/12/17870980201205131211013464405864558_000.jpg" style="width: 640px; height: 360px" /></p>

<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.net" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy241:piaohua@117.41.229.29:2018/飘花电影piaohua.com新岳父大人第一部1280高清中字.rmvb">ftp://dy241:piaohua@117.41.229.29:2018/飘花电影piaohua.com新岳父大人第一部1280高清中字.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy241:piaohua@117.41.229.29:2018/飘花电影piaohua.com新岳父大人第二部1280高清中字.rmvb">ftp://dy241:piaohua@117.41.229.29:2018/飘花电影piaohua.com新岳父大人第二部1280高清中字.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15KLP-4K63.jpg{/dede:field}
