{dede:field name='keywords'}美国战士/前进巴格达[BD中英双字{/dede:field}
{dede:field name='description'}美国战士/前进巴格达[BD中英双字1280x720高清版]迅雷下载、免费下载，美国战士/前进巴格达[BD中英双字1280x720高清版]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}美国战士/前进巴格达[BD中英双字1280x720高清版]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2010-07-13{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://4e:4e@d8.3edyy.com:170/【3E电影院www.eee4.cc】前进巴格达BD中英双字1280x720高清版.rmvb" target="_blank{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MP624330-3L22.jpg{/dede:field}
