<?php
$z[0]=Array("field","美国战士/前进巴格达[BD中英双字",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","美国战士/前进巴格达[BD中英双字1280x720高清版]迅雷下载、免费下载，美国战士/前进巴格达[BD中英双字1280x720高清版]Gvod高清在线播放，剧情介绍等。",73,257);
$z[1][4]['name']="description";
$z[2]=Array("field","美国战士/前进巴格达[BD中英双字1280x720高清版]",259,342);
$z[2][4]['name']="title";
$z[3]=Array("field","",344,383);
$z[3][4]['name']="writer";
$z[4]=Array("field","",385,424);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-07-13",426,476);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",478,515);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://4e:4e@d8.3edyy.com:170/【3E电影院www.eee4.cc】前进巴格达BD中英双字1280x720高清版.rmvb\" target=\"_blank",517,663);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MP624330-3L22.jpg",665,748);
$z[8][4]['name']="litpic";

?>