<?php
$z[0]=Array("field","卫斯理传奇[BD国语+粤语中字1024",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","卫斯理传奇[BD国语+粤语中字1024x576高清版]迅雷下载、免费下载，卫斯理传奇[BD国语+粤语中字1024x576高清版]Gvod高清在线播放，剧情介绍等。",73,249);
$z[1][4]['name']="description";
$z[2]=Array("field","卫斯理传奇[BD国语+粤语中字1024x576高清版]",251,330);
$z[2][4]['name']="title";
$z[3]=Array("field","",332,371);
$z[3][4]['name']="writer";
$z[4]=Array("field","",373,412);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-05-01",414,464);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",466,503);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://3e:3e@m3.3edyy.com:529/【3E看看www.3ekk.com】卫斯理传奇.1024x576.国粤双语.中文字幕.mkv\" target=_blank>ftftp://3e:3e@m3.3edyy.com:529/【3E看看www.3ekk.com】卫斯理传奇.1024x576.国粤双语.中文字幕.mkv</A></TD></TR></TBODY></TABLE></div><ul class=\"mmlist",505,799);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MQ239340-35W9.jpg",801,884);
$z[8][4]['name']="litpic";

?>