{dede:field name='keywords'}殉难者/殉道者BD1280高清中英双{/dede:field}
{dede:field name='description'}殉难者/殉道者BD1280高清中英双字迅雷下载、免费下载，殉难者/殉道者BD1280高清中英双字Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}殉难者/殉道者BD1280高清中英双字{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-18{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img165.poco.cn/mypoco/myphoto/20120518/00/17870980201205180009089619256204160_000.jpg" style="width: 400px; height: 594px" /></p>
<p>
	◎译　　名　殉难者<br />
	◎片　　名　Martyrs<br />
	◎年　　代　2008<br />
	◎国　　家　法国<br />
	◎类　　别　惊悚/剧情<br />
	◎语　　言　英语<br />
	◎字　　幕　N/A<br />
	◎IMDB评分 7.1/10 2,953 votes<br />
	◎IMDB链接 <a href="http://www.imdb.com/title/tt1029234" target="_blank">http://www.imdb.com/title/tt1029234</a><br />
	◎片　　长　99 Mins<br />
	◎导　　演　巴斯卡&middot;劳吉尔 Pascal Laugier<br />
	◎主　　演　米兰妮&middot;詹姆帕诺米 Myl&egrave;ne Jampano? ....Lucie<br />
	　　　　　　Morjana El Alaoui ....Anna<br />
	　　　　　　朱丽叶特&middot;高斯林 Juliette Gosselin ....Marie<br />
	　　　　　　Mike Chute ....Homme / Bourreau<br />
	　　　　　　Xavier Dolan-Tadros ....Antoine<br />
	　　　　　　Herv&eacute; Desbois ....Orderly<br />
	　　　　　　Catherine B&eacute;gin ....Mademoiselle<br />
	　　　　　　Robert Toupin ....Le p&egrave;re<br />
	　　　　　　Patricia Tulasne ....La m&egrave;re<br />
	　　　　　　Isabelle Chassepps<br />
	　　　　　　Emilie Miskdjian<br />
	　　　　　　Ga lle Cohen ....Femme de main<br />
	　　　　　　Anie Pascale ....La femme<br />
	　　　　　　Jessie Pham ....Lucie Jeune<br />
	　　　　　　Erika Scott ....Anna Jeune<br />
	　　　　　　Louis Thevenon ....Homme de main<br />
	　　　　　　aikanmi......cnm junses<br />
	<br />
	◎简　　介　<br />
	<br />
	　　一名年轻女子寻求报复那个小时候绑架和折磨她的那个坏蛋。就这样，她和一个儿童时期也被人XX过的朋友踏上了报复之路，但是这一切却让她们走上了一条可怕的人间地狱般堕落的旅程。&nbsp;<img alt="" src="http://img165.poco.cn/mypoco/myphoto/20120518/00/17870980201205180003292495588145566_012.jpg" style="width: 640px; height: 360px" /></p>
<p>
	<img alt="" src="http://img165.poco.cn/mypoco/myphoto/20120518/00/17870980201205180003292495588145566_010.jpg" style="width: 640px; height: 360px" /></p>
<p>
	<img alt="" src="http://img165.poco.cn/mypoco/myphoto/20120518/00/17870980201205180003292495588145566_009.jpg" style="width: 640px; height: 360px" /></p>
<p>
	<img alt="" src="http://img165.poco.cn/mypoco/myphoto/20120518/00/17870980201205180003292495588145566_008.jpg" style="width: 640px; height: 360px" /></p>

<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.net" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy241:piaohua@117.41.229.29:2025/飘花电影piaohua.com殉难者BD1280高清中英双字.rmvb">ftp://dy241:piaohua@117.41.229.29:2025/飘花电影piaohua.com殉难者BD1280高清中英双字.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O16000560-1J38.jpg{/dede:field}
