{dede:field name='keywords'}第30届香港电影金像奖颁奖典礼迅{/dede:field}
{dede:field name='description'}第30届香港电影金像奖颁奖典礼迅雷下载、免费下载，第30届香港电影金像奖颁奖典礼Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}第30届香港电影金像奖颁奖典礼{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-04-19{/dede:field}
{dede:field name='body'}<P align=left><IMG id=15564959 src="/uploads/allimg/c120524/133N4PR050-1ST.jpg" md5=""></P>
<P align=left><IMG id=15564960 src="/uploads/allimg/c120524/133N4PRB0-22364.jpg" md5=""></P>
<P align=left><IMG id=15564961 src="/uploads/allimg/c120524/133N4PS0P-39409.jpg" md5=""><BR><BR><IMG src="/uploads/allimg/c120524/133N4PS420-43533.jpg"><BR><BR><BR><BR>4月17日晚，第三十届香港金像奖在香港文化中心举行。《狄仁杰之通天帝国》和《打擂台》成当晚最大赢家，《打擂台》不仅成为最佳影片，也让泰迪罗宾和邵音音两位老牌演员获得最佳男配角和最佳女配角；而《狄仁杰》则包揽了最佳导演在内的6个奖项，刘嘉玲更是凭借该片成为最佳女主角；最佳男主角则被《线人》的主演谢霆锋斩获。<BR><BR>获奖名单　　 </P>
<P align=left>最佳影片 </P>
<DIV class=spctrl></DIV>
<P align=left>　　《打擂台》 </P>
<DIV class=spctrl></DIV>
<P align=left>　　最佳导演 </P>
<DIV class=spctrl></DIV>
<P align=left>　　徐克（《狄仁杰》） </P>
<DIV class=spctrl></DIV>
<P align=left>　　最佳编剧 </P>
<DIV class=spctrl></DIV>
<P align=left>　　彭浩翔、麦曦茵（《志明与春娇》） </P>
<DIV class=spctrl></DIV>
<P align=left>　　最佳男主角 </P>
<DIV class=spctrl></DIV>
<P align=left>　　谢霆锋（《线人》） </P>
<DIV class=spctrl></DIV>
<P align=left>　　最佳女主角 </P>
<DIV class=spctrl></DIV>
<P align=left>　　刘嘉玲（《狄仁杰》） </P>
<DIV class=spctrl></DIV>
<P align=left>　　最佳男配角 </P>
<DIV class=spctrl></DIV>
<P align=left>　　泰迪罗宾（《打擂台》） </P>
<DIV class=spctrl></DIV>
<P align=left>　　最佳女配角 </P>
<DIV class=spctrl></DIV>
<P align=left>　　邵音音（《打擂台》） </P>
<DIV class=spctrl></DIV>
<P align=left>　　最佳新演员 </P>
<DIV class=spctrl></DIV>
<P align=left>　　陈奂仁（《李小龙》） </P>
<DIV class=spctrl></DIV>
<P align=left>　　最佳摄影 </P>
<DIV class=spctrl></DIV>
<P align=left>　　鲍德熹（《孔子之决战春秋》） </P>
<DIV class=spctrl></DIV>
<P align=left>　　最佳剪辑 </P>
<DIV class=spctrl></DIV>
<P align=left>　　张嘉辉（《叶问2》） </P>
<DIV class=spctrl></DIV>
<P align=left>　　最佳美术指导 </P>
<DIV class=spctrl></DIV>
<P align=left>　　赵崇邦（《狄仁杰》） </P>
<DIV class=spctrl></DIV>
<P align=left>　　最佳服装造型设计 </P>
<DIV class=spctrl></DIV>
<P align=left>　　余家安（《狄仁杰》） </P>
<DIV class=spctrl></DIV>
<P align=left>　　最佳动作设计 </P>
<DIV class=spctrl></DIV>
<P align=left>　　洪金宝（《叶问2》） </P>
<DIV class=spctrl></DIV>
<P align=left>　　最佳音响效果 </P>
<DIV class=spctrl></DIV>
<P align=left>　　王丹戎、赵楠（《狄仁杰》） </P>
<DIV class=spctrl></DIV>
<P align=left>　　最佳视觉效果 </P>
<DIV class=spctrl></DIV>
<P align=left>　　李庸基、南相宇（《狄仁杰》） </P>
<DIV class=spctrl></DIV>
<P align=left>　　最佳原创电影音乐 </P>
<DIV class=spctrl></DIV>
<P align=left>　　泰廸罗宾、韦启良（《打擂台》） </P>
<DIV class=spctrl></DIV>
<P align=left>　　最佳原创电影歌曲 </P>
<DIV class=spctrl></DIV>
<P align=left>　　《Here to Stay》（恭硕良《东风破》） </P>
<DIV class=spctrl></DIV>
<P align=left>　　新晋导演 </P>
<DIV class=spctrl></DIV>
<P align=left>　　庄文强（《飞砂风中转》） </P>
<DIV class=spctrl></DIV>
<P align=left>　　最佳亚洲电影 </P>
<DIV class=spctrl></DIV>
<P align=left>　　《告白》（日本） </P>
<DIV class=spctrl></DIV>
<P align=left>　　专业精神奖 </P>
<DIV class=spctrl></DIV>
<P align=left>　　陈自强 </P>
<DIV class=spctrl></DIV>
<P align=left>　　终身成就奖 </P>
<DIV class=spctrl></DIV>
<P align=left>　　黎筱娉<BR><BR><BR></P>
<P><IMG alt="" src="/uploads/allimg/c120524/133N4PSI0-550U.jpg"></P>
<P><IMG alt="" src="/uploads/allimg/c120524/133N4PT420-61621.jpg"><BR><BR></P><BR><BR><BR>【dbank网盘高速下载地址】:<BR>第30届香港电影金像奖颁奖典礼<BR>直击第三十届香港电影金像奖[红地毯]<BR><BR>[下载地址]：<IMG border=0 src="/uploads/allimg/c120524/133N2Z4FF-102231.jpg"><BR>
<TABLE style="BORDER-BOTTOM: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-RIGHT: #cccccc 1px dotted" border=0 cellSpacing=0 cellPadding=6 width="95%" align=center>
<TBODY>
<TR>
<TD style="WORD-WRAP: break-word" bgColor=#fdfddf>ftp://3e:3e@m3.3edyy.com:529/【3E看看www.3ekk.com】直击第三十届香港电影金像奖[红地毯].rmvb</TD></TR></TBODY></TABLE><BR>[下载地址]：<IMG border=0 src="/uploads/allimg/c120524/133N2Z4FF-102231.jpg"><BR>
<TABLE style="BORDER-BOTTOM: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-RIGHT: #cccccc 1px dotted" border=0 cellSpacing=0 cellPadding=6 width="95%" align=center>
<TBODY>
<TR>
<TD style="WORD-WRAP: break-word" bgColor=#fdfddf>ftp://3e:3e@m3.3edyy.com:529/【3E看看www.3ekk.com】第30届香港电影金像奖颁奖典礼.rmvb</TD></TR></TBODY></TABLE>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120524/133N4PT920-O334.jpg{/dede:field}
