{dede:field name='keywords'}预见未来BD中英双字1024/1280高{/dede:field}
{dede:field name='description'}预见未来BD中英双字1024/1280高清迅雷下载、免费下载，预见未来BD中英双字1024/1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}预见未来BD中英双字1024/1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-12-18{/dede:field}
{dede:field name='body'}<br />
<p>
	<img border="0" onload="thumbImg(this)" src="http://img.album.pchome.net/04/72/27/26/ea4c9565432e309172997993f2992236.jpg" /><br />
	英文名：Next<br />
	中文名：预见未来<br />
	年　代：2007<br />
	国　家：美国<br />
	类　别：动作/科幻/惊悚<br />
	语　言：国语<br />
	片　长：96分钟<br />
	导　演：李&middot;塔玛霍利 Lee Tamahori<br />
	主　演：尼古拉斯&middot;凯奇 Nicolas Cage<br />
	　　&nbsp; &nbsp; &nbsp; 朱莉安&middot;摩尔 Julianne Moore<br />
	　　&nbsp; &nbsp; &nbsp; 杰西卡&middot;贝尔 Jessica Biel<br />
	　　&nbsp; &nbsp; &nbsp; 托瑞&middot;奇特尔斯 Tory Kittles<br />
	剧情简介： <br />
	　　拉斯维加斯的魔术表演师克里斯&middot;约翰逊身负一个秘密，他能预知下一刻将要发生的事。这项特异功能既是天赋才华，也是一种令他苦恼不已的诅咒。小时候的他受够了各种测试、政府以及医学研究部门对他的好奇，因此决心隐姓埋名，过普通人的生活。成年后他在赌城的一家低级酒吧靠耍廉价的魔术为生，有时候赌赌小钱赚点外快，尽管他刻意保持低调，却引起了赌场警卫的注意，他们通过监视探头盯住他的一举一动，想发现他每次都能押中宝的秘密。<br />
	　　此同时，政府特工凯尔丽&middot;弗瑞斯也在寻找克里斯的下落。一个恐怖组织威胁要引爆核炸弹，把洛杉矶夷为平地，临危受命的凯尔丽必须找到克里斯，并说服他利用特异功能帮助自己阻止这场浩劫，摧毁恐怖组织的阴谋&hellip;&hellip; <br />
	<img border="0" onload="thumbImg(this)" src="http://img.album.pchome.net/04/72/27/26/ae9f4440d1ce548bd32116ca94fab7a1.jpg" /><br />
	<img border="0" onload="thumbImg(this)" src="http://img.album.pchome.net/04/72/27/26/7267d64a6d9affa581f7a7930995f260.jpg" /><br />
	<img border="0" onload="thumbImg(this)" src="http://img.album.pchome.net/04/72/27/26/c6780cc4b5cb315204d0e667763a35d2.jpg" /><br />
	<img border="0" onload="thumbImg(this)" src="http://img.album.pchome.net/04/72/27/26/4315c9fb49cbfb2dbf70f26acfadb815.jpg" /><br />
	<br />
	<br />
	<img alt="" onload_fckprotectedatt="%20onload%3D%22attachimg(this%2C%20'load')%22" src="http://i3.6.cn/cvbnm/4c/d4/86/6fa03d56464125c8b90a23b1169fa5f1.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 338px; border-top: 0px solid; border-right: 0px solid" /></p>
<p>
	<img alt="" onload_fckprotectedatt="%20onload%3D%22attachimg(this%2C%20'load')%22" src="http://i3.6.cn/cvbnm/f1/13/69/2613b5d7164bfd57d0e1533a1a11f475.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 338px; border-top: 0px solid; border-right: 0px solid" /></p>
<p>

	[美国][科幻][预见未来][DVD-RMVB/331M][国语][尼古拉斯凯奇经典] [下载地址]：<img border="0" src="http://www.eee4.com/templets/img/down.jpg" />
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://3e:3e@xl.eee4.com:268/[3E电影站www.eee4.cn]预见未来[DVD国语版]CD1.rmvb" target="_blank">ftp://3e:3e@xl.eee4.com:268/[3E电影站www.eee4.cn]预见未来[DVD国语版]CD1.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://3e:3e@xl.eee4.com:268/[3E电影站www.eee4.cn]预见未来[DVD国语版]CD2.rmvb" target="_blank">ftp://3e:3e@xl.eee4.com:268/[3E电影站www.eee4.cn]预见未来[DVD国语版]CD2.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://3e:3e@xl.eee4.com:268/[3E电影站www.eee4.cn]预见未来[DVD国语版]CD3.rmvb" target="_blank">ftp://3e:3e@xl.eee4.com:268/[3E电影站www.eee4.cn]预见未来[DVD国语版]CD3.rmvb</a></td>
		</tr>
	</tbody>
</table>
	[下载地址]： &nbsp;<img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" /></p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2369/飘花电影piaohua.com预见未来BD中英双字1024高清.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2369/飘花电影piaohua.com预见未来BD中英双字1024高清.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2369/飘花电影piaohua.com预见未来BD中英双字1280高清.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2369/飘花电影piaohua.com预见未来BD中英双字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15X230-51413.jpg{/dede:field}
