{dede:field name='keywords'}安妮日记[BD中英双字1024x576高{/dede:field}
{dede:field name='description'}安妮日记[BD中英双字1024x576高清版]迅雷下载、免费下载，安妮日记[BD中英双字1024x576高清版]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}安妮日记[BD中英双字1024x576高清版]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2010-04-20{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://3e:3e@m1.3edyy.com:1465/【3E电影院www.eee4.cc】安妮日记BD中英双字1024x576高清版.rmvb" target=_blank>ftftp://3e:3e@m1.3edyy.com:1465/【3E电影院www.eee4.cc】安妮日记BD中英双字1024x576高清版.rmvb</A></TD></TR></TBODY></TABLE></div><ul class="mmlist{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MP612960-42Y2.jpg{/dede:field}
