<?php
$z[0]=Array("field","拯救大兵瑞恩/抢救雷恩大兵/雷霆",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","拯救大兵瑞恩/抢救雷恩大兵/雷霆救兵[BD中英双字1024x576高清版]迅雷下载、免费下载，拯救大兵瑞恩/抢救雷恩大兵/雷霆救兵[BD中英双字1024x576高清版]Gvod高清在线播放，剧情介绍等。",73,287);
$z[1][4]['name']="description";
$z[2]=Array("field","拯救大兵瑞恩/抢救雷恩大兵/雷霆救兵[BD中英双字1024x576高清版]",289,387);
$z[2][4]['name']="title";
$z[3]=Array("field","",389,428);
$z[3][4]['name']="writer";
$z[4]=Array("field","",430,469);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-03-26",471,521);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",523,560);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://3e:3e@m1.3edyy.com:1441/【3E电影院www.eee4.cc】拯救大兵瑞恩BD中英双字1024x576高清版.rmvb\" target=\"_blank",562,711);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MP60S20-4T28.jpg",713,795);
$z[8][4]['name']="litpic";

?>