{dede:field name='keywords'}海贼王剧场版/追寻草帽BD高清迅{/dede:field}
{dede:field name='description'}海贼王剧场版/追寻草帽BD高清迅雷下载、免费下载，海贼王剧场版/追寻草帽BD高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}海贼王剧场版/追寻草帽BD高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-10-04{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="/uploads/allimg/c120525/133O046223F-13R40.jpg" style="width: 700px; height: 994px" /></p>
<p>
	【电影名称】：ONE PIECE 海贼王剧场版/追寻草帽&nbsp;<br />
	【电影类型】：剧场版<br />
	【上映日期】：2011<br />
	【影片语系】：日语<br />
	【导&nbsp;&nbsp;&nbsp; 演】：佐藤宏幸<br />
	【配音演员】：田中真弓 / 中井和哉 / 冈村明美 / 山口胜平 / 平田广明 / 大谷育江 / 山口由里子<br />
	【预览简介】</p>
<p>
	&nbsp;&nbsp; 　路飞出大事了，昨天晚上还在的草帽竟然不翼而飞！路飞小时候曾经遇到过心目中的偶像&mdash;&mdash;大海盗红发香克斯，是香克斯给了他这顶草帽，并和他立下了决定人生目标的约定，对路飞来说，草帽可是比性命还重要的宝贝，无论遭遇何样的危险都不会舍弃它。<br />
	　　路飞发了疯似的四处寻找，终于发现了一头海雕正叼着他的宝贝草帽。<br />
	　　与此同时，乔巴和乌索普在找帽子途中遇到了一艘落难船，他们救了老海盗修奈达。修奈达向他们述说了和草帽有关的惊人故事。<br />
	　　万里阳光号追着翱翔长空的海雕驶入了充满危险的「伟大航路」地带。出现在他们眼前的竟是一座海军基地。草帽海贼团能取回标志性的草帽么？</p>
<p>
	<img alt="" src="/uploads/allimg/c120525/133O04624540-149213.jpg" style="width: 720px; height: 405px" /><img alt="" src="/uploads/allimg/c120525/133O04625550-1511O.jpg" style="width: 720px; height: 405px" /><img alt="" src="/uploads/allimg/c120525/133O0462AF-1D464.jpg" style="width: 720px; height: 405px" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="/uploads/allimg/c120524/133N2Z4FF-102231.jpg" />&nbsp;&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy125:piaohua@dy125.piaohua.com:6040/飘花电影piaohua.com海贼王剧场版追寻草帽BD中字1024高清.rmvb</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O0462K0-1J053.jpg{/dede:field}
