{dede:field name='keywords'}我猜我猜我猜060729迅雷下载，免{/dede:field}
{dede:field name='description'}我猜我猜我猜060729迅雷下载、免费下载，我猜我猜我猜060729Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}我猜我猜我猜060729{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2006-08-17{/dede:field}
{dede:field name='body'}ｍａｔｃｈ情侣档<BR><BR><A href="http://sjb.kan51.com/mcmcm/ys/guess20060729-1.rm">http://sjb.kan51.com/mcmcm/ys/guess20060729-1.rm</A><BR><BR><A href="http://v.kan51.com/4wesd/007/guess20060729-2.rm" target=_blank>http://v.kan51.com/4wesd/007/guess20060729-2.rm</A><BR><BR>2006-07-30 16:05:09 开始连接......<BR>2006-07-30 16:05:09 开始搜索候选资源......<BR>2006-07-30 16:05:11 搜索到26个候选资源<BR>2006-07-30 16:05:11 使用候选资源进行连接......<BR>2006-07-30 16:05:12 原始资源连接成功，得到的文件长度： 61266011<BR>2006-07-30 16:05:12 开始创建文件......<BR>2006-07-30 16:05:12 文件创建成功，开始下载数据......<BR>2006-07-30 16:05:14 用户取消下载<BR> <br>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15C9D0-32635.gif{/dede:field}
