{dede:field name='keywords'}灾难大电影BD中英双字1024/1280{/dede:field}
{dede:field name='description'}灾难大电影BD中英双字1024/1280高清美国搞笑喜剧迅雷下载、免费下载，灾难大电影BD中英双字1024/1280高清美国搞笑喜剧Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}灾难大电影BD中英双字1024/1280高清美国搞笑喜剧{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-03-17{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://e18:e18@dm.eee4.com:1216/[3E电影站www.eee4.com]灾难大电影.rmvb" target="_blank{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MO63N10-1MZ.jpg{/dede:field}
