{dede:field name='keywords'}狮口惊魂迅雷下载，免费下载，Gv{/dede:field}
{dede:field name='description'}狮口惊魂迅雷下载、免费下载，狮口惊魂Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}狮口惊魂{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2007-10-09{/dede:field}
{dede:field name='body'}<p>★中文片名：狮口惊魂<br />★英文片名：Prey<br />★年　　代：2007<br />★上映日期：2007年4月12日(香港)<br />　　　　　　2007年1月30日(DVD美国发行)<br />★国家地区：美国/南非<br />★类　　别：灾难/惊悚/恐怖<br />★导　　演：达雷尔&middot;鲁德Darrell Roodt<br />★主　　演：布丽姬&middot;穆娜 Bridget Moynahan<br />　　　　　&nbsp; 彼得&middot;威勒 Peter Weller<br />　　　　　&nbsp; 布丽姬&middot;穆娜 Bridget Moynahan <br />　　　　&nbsp; 　卡尔莉&middot;斯科罗得 Carly Schroeder<br />★片&nbsp;&nbsp;&nbsp; 长：92分钟<br />★语　　言：英语<br />★字　　幕：中文字幕<br />★迅雷地址：电影天堂www.eee4.com<br />★压缩格式：高清版DVD大碟<br />★剧情简介：</p>
<p><br />　　汤姆一家四口来到南非旅行，让他的新婚妻子爱媚与其子女打好关系，可是由于工作需要，汤临时不能跟他们进入森林，因此爱媚带同14岁大女茜茜及10岁儿子戴维先行出发。森林向导白赖仁驾车，可是就在他们下车散步之时，原来一只狮子已在30码外觊觎着这四个猎物，而另一只女狮也把关拦截着，而剎那之间，白赖仁已被狮口撕成两半，成为两只狮子的午餐！手提DV Cam的积茜嘉，更无意中把这段残酷杀戮如实录像下来&hellip;&hellip;</p>
<p><br />　　就在狮子满足口腹之际，爱媚与子女只能隐藏在车里，等待救援，当然两只狮子又怎会放弃食物！一场人兽厮杀之旅旋即展开，究竟DV Cam记录的下一个猎物会是谁？ </p>
<p><img alt="" border="0" src="http://www.sinaimg.cn/ent/m/2007-09-10/U105P28T3D1710695F326DT20070910190156.jpg" /><br />----------------------------------------------------------------<br />★影片截图：<br /><img alt="" border="0" src="http://img.album.pchome.net/03/67/37/26/d9964c9dab34e8e588ae6dd616949100.jpg" /><br /><img alt="" border="0" src="http://img.album.pchome.net/03/67/37/26/75036b32184263f1e002736c5fd609cf.jpg" /><br /><img alt="" border="0" src="http://img.album.pchome.net/03/67/37/26/c436b406e129db36be9d0ce19875a629.jpg" /><br /><img alt="" border="0" src="http://img.album.pchome.net/04/81/32/55/a2dd80235d04e543403be1fdc27920c0.jpg" /><br /><img alt="" border="0" src="http://img.album.pchome.net/04/81/32/55/7564f9d8624727d12456c8f0843041e4.jpg" /><br /><img alt="" border="0" src="http://img.album.pchome.net/04/81/32/55/75d16d27c86b4d0e76687e75b109c93e.jpg" /></p>
<p>2007-10-09 00:08:10 开始连接......<br />2007-10-09 00:08:12 开始搜索候选资源......<br />2007-10-09 00:08:13 搜索到19个候选资源<br />2007-10-09 00:08:15 使用候选资源进行连接......<br />2007-10-09 00:08:17 搜索到39个候选资源<br />2007-10-09 00:08:19 使用候选资源进行连接......<br />2007-10-09 00:08:21 文件创建成功，开始下载数据......<br />2007-10-09 00:08:22 用户取消下载&nbsp;&nbsp; 本文来自 http://www.eee4.com</p>
选择下载服务器： <br />
<table style="BORDER-RIGHT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; BORDER-BOTTOM: #cccccc 1px dotted" cellspacing="0" cellpadding="6" width="95%" align="center" border="0">
    <tbody>
        <tr>
            <td style="WORD-WRAP: break-word" bgcolor="#fdfddf"><anchor></anchor><a href="thunder://QUFmdHA6Ly9keWdvZDE6ZHlnb2QxQG02Ni5keWdvZC5jb206OTkyNy/ni67lj6Pmg4rprYIvW+eUteW9seWkqeWggnd3dy5keWdvZC5jb21d54uu5Y+j5oOK6a2CRFZELnJtdmJaWg==">07最新上映超血腥灾难大片《狮口惊魂》DVD中字</a></td>
        </tr>
    </tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O16494930-52V3.jpg{/dede:field}
