<?php
$z[0]=Array("field","唐山大地震/余震[真正DVD国语中",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","唐山大地震/余震[真正DVD国语中字]迅雷下载、免费下载，唐山大地震/余震[真正DVD国语中字]Gvod高清在线播放，剧情介绍等。",72,230);
$z[1][4]['name']="description";
$z[2]=Array("field","唐山大地震/余震[真正DVD国语中字]",232,302);
$z[2][4]['name']="title";
$z[3]=Array("field","",304,343);
$z[3][4]['name']="writer";
$z[4]=Array("field","",345,384);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-09-08",386,436);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",438,475);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://3e:3e@d8.3edyy.com:182/【3E看看www.3ekk.com】唐山大地震[真正DVD国语中字].rmvb\" target=_blank>ftftp://3e:3e@d8.3edyy.com:182/【3E看看www.3ekk.com】唐山大地震[真正DVD国语中字].rmvb</A></TD></TR></TBODY></TABLE></P></div><ul class=\"mmlist",477,757);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MPY20P-34923.jpg",759,841);
$z[8][4]['name']="litpic";

?>