<?php
$z[0]=Array("field","亲爱的回家第34集韩雪,胡兵2012",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","亲爱的回家第34集韩雪 胡兵2012热播剧迅雷下载、免费下载，亲爱的回家第34集韩雪 胡兵2012热播剧Gvod高清在线播放，剧情介绍等。",72,236);
$z[1][4]['name']="description";
$z[2]=Array("field","亲爱的回家第34集韩雪 胡兵2012热播剧",238,311);
$z[2][4]['name']="title";
$z[3]=Array("field","",313,352);
$z[3][4]['name']="writer";
$z[4]=Array("field","",354,393);
$z[4][4]['name']="source";
$z[5]=Array("field","2012-03-13",395,445);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",447,484);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://dy44:piaohua@dy44.piaohua.com:2918/飘花电影piaohua.com亲爱的回家.HDTV.01.rmvb",486,608);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MPc3N0-3QD.jpg",610,690);
$z[8][4]['name']="litpic";

?>