<?php
$z[0]=Array("field","大有前途抢先版国语中字方中信",0,69);
$z[0][4]['name']="keywords";
$z[1]=Array("field","大有前途抢先版国语中字方中信 王宝强迅雷下载、免费下载，大有前途抢先版国语中字方中信 王宝强Gvod高清在线播放，剧情介绍等。",71,235);
$z[1][4]['name']="description";
$z[2]=Array("field","大有前途抢先版国语中字方中信 王宝强",237,310);
$z[2][4]['name']="title";
$z[3]=Array("field","",312,351);
$z[3][4]['name']="writer";
$z[4]=Array("field","",353,392);
$z[4][4]['name']="source";
$z[5]=Array("field","2012-05-18",394,444);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",446,483);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://dy44:piaohua@dy44.piaohua.com:3448/飘花电影piaohua.com大有前途抢先版国语中字.rmvb",485,611);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MP0943F-1L33.jpg",613,695);
$z[8][4]['name']="litpic";

?>