{dede:field name='keywords'}传奇人物--股神巴菲特迅雷下载，{/dede:field}
{dede:field name='description'}传奇人物--股神巴菲特迅雷下载、免费下载，传奇人物--股神巴菲特Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}传奇人物--股神巴菲特{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2008-12-01{/dede:field}
{dede:field name='body'}<P>【传奇人物--股神 巴菲特】</P>
<P>&nbsp;&nbsp;&nbsp; 沃伦&#8226;巴菲特(Warren Buffett)1930年8月30日出生在美国内布拉斯加州的奥马哈市。他从小就极具投资意识，1941年，11岁的巴菲特购买了平生第一张股票。1947年，巴菲特进入宾夕法尼亚大学攻读财务和商业管理。两年后，巴菲特考入哥伦比亚大学金融系,拜师于著名投资理论学家本杰明&#8226;格雷厄姆。在格雷厄姆门下,巴菲特如鱼得水。1956年，他回到家乡创办“巴菲特有限公司”。1964年，巴菲特的个人财富达到400万美元，而此时他掌管的资金已高达2200万美元。1965年,35岁的巴菲特收购了一家名为伯克希尔-哈撒韦的纺织企业，1994年底已发展成拥有230亿美元的伯克希尔工业王国，由一家纺纱厂变成巴菲特庞大的投资金融集团。他的股票在30年间上涨了2000倍，而标准普尔500家指数内的股票平均才上涨了近50倍。多年来，在《福布斯》一年一度的全球富豪榜上，巴菲特一直稳居前三名。<BR>他举动都能影响全球市场走势，40年来，他公司取得了4000多倍投资收益率。2008年，他个人富达到620亿美元，成为世界首富。他创造富传奇秘密究竟是什么？巴菲特2008年年末，全球信……</P>
<P><IMG src="http://i3.6.cn/cvbnm/aa/05/c5/1e8e3bfa419c68412dbe409279d167ba.jpg"></P>
<P>【电影截图】：<BR>电影来源：www.eee4.com</P>
<P><IMG src="http://i3.6.cn/cvbnm/93/fb/eb/6385e685faabf23342b62af6dcf515aa.jpg">&nbsp;<BR><IMG src="http://i3.6.cn/cvbnm/45/7b/67/ade7f8dc70bb1a32eff63e1b48ce92cc.jpg">&nbsp;<BR><IMG src="http://i3.6.cn/cvbnm/f4/9e/2a/b6fe71c6725eb031b536c97e9633ea72.jpg">&nbsp;<BR><IMG src="http://i3.6.cn/cvbnm/8a/ab/22/a3121d4b7b963522f7da4b822c1522f2.jpg"></P><p>2008-12-01 12:40:12 开始连接......<br>2008-12-01 12:40:12 开始搜索候选资源......<br>2008-12-01 12:40:12 搜索到22个候选资源<br>2008-12-01 12:40:12 使用候选资源进行连接......<br>2008-12-01 12:40:13 搜索到41个候选资源<br>2008-12-01 12:40:13 使用候选资源进行连接......<br>2008-12-01 12:40:13 文件创建成功，开始下载数据......<br>2008-12-01 12:40:16 用户取消下载&nbsp;&nbsp; 本文来自：www.eee4.com</p>
（直接可能无法下载，一律使用<a href="http://www.eee4.com/soft.htm" target="_blank">迅雷下载</a>）&nbsp;&nbsp;（温馨提示：直接点击下面链接）<br>
【传奇人物--股神巴菲特】 －来自[3E电影站eee4.com]：<IMG src="http://www.eee4.com/templets/img/down.jpg" border=0><br>
<table style="BORDER-RIGHT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; BORDER-BOTTOM: #cccccc 1px dotted" cellspacing="0" cellpadding="6" width="95%" align="center" border="0">
    <tbody>
        <tr>
            <td style="WORD-WRAP: break-word" bgcolor="#fdfddf"><a href="ftp://d88:d88@ftp.eee4.com:1501/[3E电影站www.eee4.com]传奇人物-股神巴菲特.rmvb" target="_blank">ftp://d88:d88@ftp.eee4.com:1501/[3E电影站www.eee4.com]传奇人物-股神巴菲特.rmvb</a></td>
        </tr>
    </tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O161462F-2AT.jpg{/dede:field}
