{dede:field name='keywords'}国家地理:,自然力量BD中英双字10{/dede:field}
{dede:field name='description'}国家地理: 自然力量BD中英双字1024高清美国纪录片迅雷下载、免费下载，国家地理: 自然力量BD中英双字1024高清美国纪录片Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}国家地理: 自然力量BD中英双字1024高清美国纪录片{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-09-03{/dede:field}
{dede:field name='body'}<p>
	◎译　　名　国家地理: 自然力量<br />
	◎片　　名　National Geographic Forces Of Nature<br />
	◎年　　代　2004<br />
	◎国　　家　美国<br />
	◎类　　别　记录/短片<br />
	◎语　　言　英语<br />
	◎字　　幕　中字<br />
	◎文件格式　BD-RMVB<br />
	◎视频尺寸　1024 x 576<br />
	◎文件大小　1CD<br />
	◎片　　长　40 Min<br />
	◎导　　演　<br />
	◎主　　演　</p>
<p>
	◎简　　介　</p>
<p>
	&nbsp;&nbsp;&nbsp; Enjoy National Geographic&#39;s spectacular large-format film from the comfort of your couch. Filled with incredible how-did-they- do-it film footage of nature at its most potent, it&#39;s a powerful image- and music-filled journey of discovery that takes you to the very brink of exploding volcanoes, across rupturing earthquake faults, to the edge of tornadoes, and more.</p>
<p>
	&nbsp;&nbsp;&nbsp; 《自然力量》以其最震撼的镜头向您展示比真实生活还要巨大而清晰的地震、火山、和风暴场景。我们的镜头将会跟随科学家一起走近爆发火山的边缘、火山灰流的足迹、大量被损毁的道路、以及正在向肆虐的风暴行驶的车辆。观众将会与地球上最具破环性的力量面对面，同时从片中获知如何预测自然灾害并为其做准备，以及如何将破坏程度化降低到最小限度。</p>
<p>
	&nbsp; 地动、山摇、天空乌云密布&mdash;&mdash;跟随《自然力量》走近地震、火山和龙卷风的壮烈景观，经历地球上最猛烈的力量。从蒙特塞拉特岛的火山爆发，土耳其惊愕的塌陷，到美国中西部惊骇世人的龙卷风，现代社会全球的自然灾害都一一显现于这部巨幕电影中。本片由国家地理和Graphic Films联合制作，力求呈现震惊世人的大气和地理现象，从而向观众展示自然灾难过后，那些愿意冒生命危险的科学家是如何理解这些自然力量并为日后的防御工作而积累经验的。</p>
<p>
	制&nbsp; 片 人：Paul Novros, George Casey<br />
	执行制片人：Lisa Truitt, Tim Kelly<br />
	导&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 演：George Casey<br />
	摄 影 导演：Sean Casey<br />
	编&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 剧：Mose Richards<br />
	解&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 说：Kevin Bacon<br />
	作&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 曲：Sam Cardon<br />
	编&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 辑：Stephen L.Johnson, ACE<br />
	制 片助 理：Ammiel Najar, Erica Immucci<br />
	线 上制 片：Greg Eliason</p>


<p>
	<img border="0" src="/uploads/allimg/c120524/133N42I550-19437.jpg" style="max-width: 750px; max-height: 750px" /></p>
<p>
	<img border="0" src="/uploads/allimg/c120524/133N42I6030-2S53.jpg" style="max-width: 750px; max-height: 750px" /></p>
<p>
	[下载地址]： &nbsp;<img border="0" src="/uploads/allimg/c120524/133N2Z4FF-102231.jpg" />
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:1476/飘花电影piaohua.com国家地理自然力量BD中英双字1024高清.rmvb</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120524/133N42IAF-3T12.jpg{/dede:field}
