<?php
$z[0]=Array("field","百变星君/百变金刚[BD国粤双语中",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","百变星君/百变金刚[BD国粤双语中英双字1024x576+1280x720高清版]迅雷下载、免费下载，百变星君/百变金刚[BD国粤双语中英双字1024x576+1280x720高清版]Gvod高清在线播放，剧情介绍等。",73,287);
$z[1][4]['name']="description";
$z[2]=Array("field","百变星君/百变金刚[BD国粤双语中英双字1024x576+1280x720高清版]",289,387);
$z[2][4]['name']="title";
$z[3]=Array("field","",389,428);
$z[3][4]['name']="writer";
$z[4]=Array("field","",430,469);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-11-12",471,521);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",523,560);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://3e:3e@d3.3edyy.com:121/【3E电影院www.eee4.org】百变星君.1024x576.国粤双语.中文字幕.mkv\" target=_blank>ftftp://3e:3e@d3.3edyy.com:121/【3E电影院www.eee4.org】百变星君.1024x576.国粤双语.中文字幕.mkv</A></TD></TR></TBODY></TABLE><BR><FONT color=#ff0000 size=2><STRONG>[下载地址]：<IMG border=0 src=\"httftp://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg",562,971);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MQ3D2P-11243.jpg",973,1055);
$z[8][4]['name']="litpic";

?>