<?php
$z[0]=Array("field","源代码/危机解密/启动原始码720P",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","源代码/危机解密/启动原始码720P 1280*720迅雷下载、免费下载，源代码/危机解密/启动原始码720P 1280*720Gvod高清在线播放，剧情介绍等。",73,245);
$z[1][4]['name']="description";
$z[2]=Array("field","源代码/危机解密/启动原始码720P 1280*720",247,324);
$z[2][4]['name']="title";
$z[3]=Array("field","",326,365);
$z[3][4]['name']="writer";
$z[4]=Array("field","",367,406);
$z[4][4]['name']="source";
$z[5]=Array("field","2012-01-31",408,458);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",460,497);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://dy111:piaohua@dy111.piaohua.com:114/飘花电影下载站www.piaohua.com源代码720p.rmvb",499,624);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MOWaZ-443T.jpg",626,706);
$z[8][4]['name']="litpic";

?>