{dede:field name='keywords'}杀手精英/特种精英/灭杀门BD国语{/dede:field}
{dede:field name='description'}杀手精英/特种精英/灭杀门BD国语配音中字1024/1280高清迅雷下载、免费下载，杀手精英/特种精英/灭杀门BD国语配音中字1024/1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}杀手精英/特种精英/灭杀门BD国语配音中字1024/1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-04-26{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://cfile26.uf.tistory.com/image/126AC34A4EAE809C0834A7" style="width: 678px; height: 971px" /></p>
<p>
	【影片原名】Killer Elite<br />
	【中文译名】杀手精英/特种精英(台)/灭杀门(港)<br />
	【出品公司】Omnilab Media<br />
	【出品年代】2011 年<br />
	【上映日期】2011年9月23日 美国<br />
	【影片级别】Canada:14A (Ontario) | South Korea:18 | Ireland:16 | USA:R<br />
	【官方网站】<a href="http://www.preall.com/" target="_blank">http://www.PREALL.com/</a><br />
	【IMDB链接】<a href="http://www.imdb.com/title/tt1448755/" target="_blank">http://www.imdb.com/title/tt1448755/</a><br />
	【IMDB评分】6.7/10 (5506 votes)<br />
	【国　　家】美国/澳大利亚<br />
	【类　　别】动作/惊悚<br />
	【导　　演】加里&middot;麦肯德莱 Gary McKendry<br />
	【主　　演】杰森&middot;斯坦森 Jason Statham &nbsp;....Danny Bryce<br />
	　　　　　　克里夫&middot;欧文 Clive Owen &nbsp;....Spike<br />
	　　　　　　罗伯特&middot;德尼罗 Robert De Niro &nbsp;....Hunter<br />
	　　　　　　伊冯娜&middot;斯特拉霍夫斯基 Yvonne Strahovski &nbsp;....Anne<br />
	　　　　　　格兰特&middot;鲍尔 Grant Bowler &nbsp;....Capt. James Cregg<br />
	　　　　　　多米尼克&middot;珀塞尔 Dominic Purcell &nbsp;....Davies<br />
	　　　　　　阿德沃尔&middot;阿吉纽依-艾格拜吉 Adewale Akinnuoye-Agbaje &nbsp;....The Agent<br />
	　　　　　　迈克尔&middot;多曼 Michael Dorman<br />
	　　　　　　本&middot;门德尔森 Ben Mendelsohn<br />
	　　　　　　阿登&middot;杨 Aden Young<br />
	　　　　　　Firass Dirani<br />
	　　　　　　Daniel Messier &nbsp;....Assassin<br />
	　　　　　　Kristy Barnes Cullen &nbsp;....Supply Room Nurse<br />
	　　　　　　Lachy Hulme<br />
	　　　　　　Birol Tarkan Yildiz &nbsp;....Hasan<br />
	<br />
	<br />
	【内容简介】<br />
	<br />
	<br />
	&nbsp; &nbsp; &nbsp;影片根据真实事件改编，杰森&middot;斯坦森饰演一位前海豹突击队队员，他召集一队人马重新组队，只为营救自己前导师（罗伯特&middot;德尼罗）。而他们最大的敌人就是克里夫&middot;欧文饰演的大恶人。<br />
	<br />
	&nbsp; &nbsp; &nbsp;杰森&middot;斯坦森与克里夫&middot;欧文联袂出演的全新动作大片《杀手精英》再添明星，老将罗伯特&middot;德尼罗也将提枪上阵，三个猛男硬汉组成&ldquo;实力+动作&rdquo;铁三角，使得影片可看性大大加强。 　　<br />
	&nbsp; &nbsp; &nbsp;<br />
	&nbsp; &nbsp; &nbsp;影片《精英杀手》改编自拉尔夫费恩斯的小说《羽人》。</p>
<p>
	<img alt="" src="http://img165.poco.cn/mypoco/myphoto/20111107/14/62564813201111071419173765531585546_003.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img165.poco.cn/mypoco/myphoto/20111107/14/62564813201111071419173765531585546_002.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img165.poco.cn/mypoco/myphoto/20111107/14/62564813201111071419173765531585546_001.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img165.poco.cn/mypoco/myphoto/20111107/14/62564813201111071419173765531585546_000.jpg" style="width: 720px; height: 405px" /><br />
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="&#13;&#10;ftp://dy125:piaohua@dy125.piaohua.com:7153/飘花电影piaohua.com杀手精英HDRip中字1280高清修正字幕.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:7153/飘花电影piaohua.com杀手精英HDRip中字1280高清修正字幕.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3296/飘花电影piaohua.com杀手精英BD国语配音中字1024高清.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3296/飘花电影piaohua.com杀手精英BD国语配音中字1024高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O156392F-252B.jpg{/dede:field}
