{dede:field name='keywords'}X档案1BD中英双字1024/1280高清{/dede:field}
{dede:field name='description'}X档案1BD中英双字1024/1280高清迅雷下载、免费下载，X档案1BD中英双字1024/1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}X档案1BD中英双字1024/1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-12-12{/dede:field}
{dede:field name='body'}<p>
	&nbsp;<img alt="" border="0" src="http://img.album.pchome.net/54/68/95/91/52296662f3fa6b3e64bf46df244be65c.jpg" /></p>
<p>
	◎中文　名　《X档案》1998年欧美票房过亿科幻惊险DVD中英双字1024x576高清版<br />
	◎片　　名　The X Files<br />
	◎年　　代　1998<br />
	◎国　　家　美国<br />
	◎类　　别　科幻/惊险/动作/悬念<br />
	◎语　　言　英语<br />
	◎字　　幕　外挂中文/英语<br />
	◎IMDB评分　6.6/10 (17,176 votes)<br />
	◎IMDB链接　http://www.imdb.com/title/tt0120902/<br />
	◎文件格式　BluRay-RMVB<br />
	◎视频尺寸　1024x576<br />
	◎文件大小　1CD<br />
	◎片　　长　121 Min<br />
	◎导　　演　罗布 鲍曼 (Rob Bowman (I))<br />
	◎主　　演　戴维 杜车夫尼 (David Duchovny) ...... Special Agent Fox Mulder<br />
	　　　　　　翰 内维尔 (John Neville) ...... The Well-Manicured Man<br />
	　　　　　　利恩 安迪生 (Gillian Anderson) ...... Special Agent Dana Scully<br />
	　　　　　　William B. Davis (I) ...... The Cigarette-Smoking Man<br />
	　　　　　　丁 兰多 (Martin Landau) ...... Alvin Kurtzweil, M.D.<br />
	　　　　　　奇 皮莱基 (Mitch Pileggi) ...... Assistant Director Walter Skinner<br />
	　　　　　　奥奎因 (Terry O\&#39;Quinn) ...... Darius Michaud<br />
	<br />
	◎简　　介　<br />
	<br />
	「Ｘ档案－征服未来」是根据克里斯卡特制作的热门影集所改编而来的，剧情描述ＦＢＩ干员穆德和史考莉在调查德州达拉斯一栋办公大楼神秘爆炸案时，不小心被卷入一宗神秘的阴谋之中。<br />
	　　大卫杜契尼饰演本片主角福克斯穆德，其为一名严肃却聪明绝顶的ＦＢＩ干员，他相信外星人的存在，因此致力于调查局内不可解的悬案，而他的搭档黛娜史考莉则是由吉莉安德森所饰演，她是一名医学博士，因此她能对穆德所相信的神秘事件存有怀疑的态度。「Ｘ档案」在二人的诠释之下，一集比一集紧张，一集比一集精采，所有不可解的神秘案件，答案将在「X档案-征服未来」中真相大白。<br />
	　　影集常客米契培利吉饰演ＦＢＩ副局长华特史坚尼、威廉戴卫斯饰演抽雪茄的男人、约翰奈维饰演修饰整洁的男人，以及阴谋论专家一人枪手－－狄恩海格伦、汤姆布莱伍和布鲁斯哈伍。其他<a href="http://www.eee4.com/" target="_blank">迅雷电影下载</a>演员则有金奖得主马丁兰道「艾得伍德」、布莱斯丹纳「艳倒群雌」、杰菲狄蒙「第三类奇迹」、泰瑞欧昆、葛伦希利「急诊室的春天」以及路卡斯布莱克「弹簧刀」。<br />
	　　「Ｘ档案」导演罗伯包曼曾以该影集获得一九九五及一九九七年的金球奖最佳影集奖，并与创始人克里斯卡特拍出一部精采刺激、悬疑紧张的超级强片，同时能满足该影集最忠实的影迷及初次接触「Ｘ档案」魅力的新观众。「Ｘ档案－征服未来」在影集第四、五季的空档拍竣，定于一九九八年暑假上映，该片将解开第五季结局留下的谜底。<br />
	　　大卫杜契夫尼凭「Ｘ档案」影集获得一九九七年金球奖最佳男主角奖提名，并以「Ｘ档案」及「赖瑞山德斯秀」两度获得艾美奖提名。去年他曾演出惊悚动作片「扮演上帝」（直译），他的作品还有「加州杀手」、「卓别林与他的情人」、「爱贝多芬」等片。<br />
	　　吉莲安德森于一九九六年赢得金球奖最佳女主角奖，次年她更赢得金球奖、艾美奖最佳女主角奖。她将出现在莎朗史东的新片「THE MIGHTY」中。</p>

<p>
	【电影截图】：<br />
	电影来源：www.eee4.com<br />
	<a href="http://img.album.pchome.net/54/68/70/87/018391dc8a6d3f6246afbc73de79d8d5.jpg" target="_blank"><img border="0" src="http://img.album.pchome.net/54/68/70/87/018391dc8a6d3f6246afbc73de79d8d5.jpg" /></a>&nbsp;<br />
	<a href="http://img.album.pchome.net/54/68/70/87/81f37ae2ffbe6878794150baeac2ab54.jpg" target="_blank"><img border="0" src="http://img.album.pchome.net/54/68/70/87/81f37ae2ffbe6878794150baeac2ab54.jpg" /></a>&nbsp;<br />
	<a href="http://img.album.pchome.net/54/68/70/87/b7909c7084161b435eec8ef03054f182.jpg" target="_blank"><img border="0" src="http://img.album.pchome.net/54/68/70/87/b7909c7084161b435eec8ef03054f182.jpg" /></a>&nbsp;<br />
	<a href="http://img.album.pchome.net/54/68/70/87/b9937afa52a0cf898b211a8d36339669.jpg" target="_blank"><img border="0" src="http://img.album.pchome.net/54/68/70/87/b9937afa52a0cf898b211a8d36339669.jpg" /></a></p>
<p>
	1998年欧美票房过亿科幻惊险《X档案》DVD中英双字1024x576高清版 <img border="0" src="http://www.eee4.com/templets/img/down.jpg" /></p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://e12:e12@xl2.eee4.com:9219/[3E电影站www.eee4.com]X档案电影版[DVD中英双字1024x576高清版].rmvb" target="_blank">ftp://e12:e12@xl2.eee4.com:9219/[3E电影站www.eee4.com]X档案电影版[DVD中英双字1024x576高清版].rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2311/飘花电影piaohua.comX档案1BD中英双字1280高清.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2311/飘花电影piaohua.comX档案1BD中英双字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15WIZ-33W1.jpg{/dede:field}
