{dede:field name='keywords'}洗黑钱DVD国语中字720P双语甄子{/dede:field}
{dede:field name='description'}洗黑钱DVD国语中字720P双语甄子丹经典动作/高清迅雷下载、免费下载，洗黑钱DVD国语中字720P双语甄子丹经典动作/高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}洗黑钱DVD国语中字720P双语甄子丹经典动作/高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-07-28{/dede:field}
{dede:field name='body'}<p>
	<img border="0" src="http://img.killman.net/-4-/07.27/xiheiqian/01.jpg" /></p>
<p>
	<img border="0" src="http://img.killman.net/-4-/07.27/xiheiqian/02.jpg" /></p>
<p>
	◎中文名: 《洗黑钱》甄子丹 关之琳经典动作大片DVD国语中字<br />
	◎英文名: Tiger Cage II<br />
	◎版本：法二metrofilm修复版<br />
	◎发行日期: 1990年<br />
	◎导演：袁和平<br />
	◎演员：甄子丹 / 关之琳 / 吴大维 / 威龙 / 郑裕玲<br />
	◎地区:：香港<br />
	◎语言:：国语<br />
	◎字幕： 简体中文<br />
	◎文件格式　RMVB<br />
	◎视频尺寸　720 x 384 1280 x 720&nbsp; <br />
	<br />
	◎片　　长　92 Min<br />
	<br />
	◎简介:&nbsp; 粤语国语双音轨<br />
	<br />
	周律师是香港专门负责洗&ldquo;黑钱&rdquo;的中间人，为了独吞一笔巨额赃款，派出杀手去杀害大伟和他的助手乐仔，只有大伟侥幸逃脱了这场劫难，为了给乐仔报仇，洗清嫁祸给自己的罪名，他和余文慧律师和她的手下决定联手对付周，在这对抗的过程中，他们力尽艰辛，几次逃避周律师的追杀，期间，大伟和余文慧发生了感情，后来，余文慧给周律师绑架了，大伟去救余文慧，战斗在一个旧的货舱开始了，在打斗的过<a href="http://www.eee4.com/" target="_blank">电影下载</a>程中，余文慧挣脱了绳索，和大伟联手，余文慧的助手也来助阵，在两人的帮助下，大伟最终为乐仔报了仇并洗清了自己的罪名&hellip;&hellip;</p>

<p>
	<img border="0" src="http://img.killman.net/-4-/07.27/xiheiqian/2.jpg" width="750" /></p>
<p>
	<img border="0" src="http://img.killman.net/-4-/07.27/xiheiqian/4.jpg" width="750" /></p>
<p>
	<img border="0" src="http://img.killman.net/-4-/07.27/xiheiqian/5.jpg" width="750" /></p>
<p>
	<img border="0" src="http://img.killman.net/-4-/07.27/xiheiqian/1.jpg" width="750" /></p>
<p>
	<br />
	◎截图：<br />
	<img border="0" onload="attachimg(this, 'load')" src="http://img.album.pchome.net/54/69/40/75/215581ab5ab4260fb9c761c6292eff85.jpg" />&nbsp;<br />
	<img border="0" onload="attachimg(this, 'load')" src="http://img.album.pchome.net/54/69/40/75/856e757757a248f0c595c806efd4f2c7.jpg" />&nbsp;<br />
	<img border="0" onload="attachimg(this, 'load')" src="http://img.album.pchome.net/54/69/40/75/1a7f17f87df3451df765b7c454f3c30c.jpg" />&nbsp;&nbsp;</p>
<br />
<p>
	&nbsp;甄子丹 关之琳经典动作大片《洗黑钱》DVD国语中字&nbsp; 
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://e10:e10@xl2.eee4.com:9306/[3E电影站www.eee4.com]洗黑钱DVD国语中字.rmvb" target="_blank">ftp://e10:e10@xl2.eee4.com:9306/[3E电影站www.eee4.com]洗黑钱DVD国语中字.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:1140/飘花电影piaohua.com.720p.洗黑钱.mkv">ftp://dy44:piaohua@dy44.piaohua.com:1140/飘花电影piaohua.com.720p.洗黑钱.mkv</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1BU260-1O31.jpg{/dede:field}
