{dede:field name='keywords'}开心魔法BD1280高清迅雷下载，免{/dede:field}
{dede:field name='description'}开心魔法BD1280高清迅雷下载、免费下载，开心魔法BD1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}开心魔法BD1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-01-27{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img165.poco.cn/mypoco/myphoto/20111220/11/56643687201112201155241061071895163_007.jpg" style="width: 500px; height: 700px" /></p>
<p>
	<img alt="" src="http://img165.poco.cn/mypoco/myphoto/20111220/11/56643687201112201155241061071895163_006.jpg" style="width: 500px; height: 722px" /></p>
<p>
	<img alt="" src="http://img165.poco.cn/mypoco/myphoto/20111220/11/56643687201112201155241061071895163_005.jpg" style="width: 500px; height: 718px" /></p>
<p>
	中文名： 开心魔法<br />
	上映日期： 2011年12月1日&nbsp; &nbsp;中国<br />
	出品公司： 天娱传媒、华谊兄弟 、天马影业<br />
	制片地区： 中国香港<br />
	导演： 叶伟信<br />
	编剧： 黄百鸣<br />
	主演： 古天乐， 吴尊， 吴京， 闫妮， 松明<br />
	类型： 青春，奇幻，喜剧<br />
	上映时间： 2011-12-01(中国大陆)<br />
	语言： 粤语<br />
	字幕： 中文<br />
	<br />
	<br />
	剧情简介<br />
	<br />
	　　《开心魔法》跟&ldquo;开心鬼&rdquo;系列没有任何关系，是完全不同的电影，而且这次是青春魔幻喜剧，没有鬼，只有魔法。<br />
	　　【幕后花絮】<br />
	　　该片是龙丹妮回归天娱后再度出击的电影作品，也是天娱与华谊的首度联手。据了解，影片的三个投资团队的分工非常明确，天娱将负责媒体与艺人部分，华谊兄弟负责发行，黄百鸣的天马影业则负责电影制作领域。<br />
	　　27年前，由黄百鸣编剧并主演的&ldquo;开心鬼&rdquo;系列在香港长红不衰。27年后，黄百鸣携手<a href="http://www.anzhuo4.com/" style="color: rgb(0, 0, 0); text-decoration: none;">安卓软件</a>叶伟信拍摄《开心魔法》，不过他表示这部电影跟&ldquo;开心鬼&rdquo;系列没有任何关系，&ldquo;是完全不同的电影，而且这次<a href="http://www.6dtaobao.com/" style="color: rgb(0, 0, 0); text-decoration: none;">淘宝网女装</a>是青春魔幻喜剧，没有鬼，只有魔法。&rdquo;叶伟信则透露说片中的魔法不仅会使用电脑特效来完成，而且还会用到魔术，不过会请哪位魔术大师加盟，他则说要保持神秘。闫妮与黄百鸣曾在《最强喜事》出演情侣，此次再度携手，黄百鸣爆料说闫妮的<a href="http://www.qqtmb.com/" style="color: rgb(0, 0, 0); text-decoration: none;">个性签名</a>待遇颇高，&ldquo;我之前在香港请<a href="http://www.dailiv.com/" style="color: rgb(0, 0, 0); text-decoration: none;">在线代理</a>她吃鲍鱼，喝红酒，她就每天Shopping&hellip;&hellip;&rdquo;闫妮顺势要求涨片酬，没想到遭到黄百鸣的拒绝，&ldquo;谈钱太伤感情了，我们还是谈谈戏吧。&rdquo;至于两人在片中的角色，据黄百鸣介绍说：&ldquo;原本是闫妮演校长，我演教师，但我不想被校长欺负，于是换成了闫妮演教师，我演教授。&rdquo;　<br />
	<br />
	<br />
	◎影片截图<br />
	&nbsp;</p>
<p>
	<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120123/20/62564813201201232011593938626831567_003.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120123/20/62564813201201232011593938626831567_002.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120123/20/62564813201201232011593938626831567_001.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120123/20/62564813201201232011593938626831567_000.jpg" style="width: 720px; height: 405px" /><br />
	&nbsp;</p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>


<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="
ftp://dy125:piaohua@dy125.piaohua.com:7532/飘花电影piaohua.com开心魔法BD国语无字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:7532/飘花电影piaohua.com开心魔法BD国语无字1280高清.rmvb </a></td>
		</tr>
	</tbody>
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="
ftp://dy125:piaohua@dy125.piaohua.com:7532/飘花电影piaohua.com开心魔法BD粤语无字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:7532/飘花电影piaohua.com开心魔法BD粤语无字1280高清.rmvb </a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15911P-15G5.png{/dede:field}
