{dede:field name='keywords'}伊娃BD1280高清迅雷下载，免费下{/dede:field}
{dede:field name='description'}伊娃BD1280高清迅雷下载、免费下载，伊娃BD1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}伊娃BD1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-01{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120430/22/62564813201204302248044999551094806_000.jpg" style="width: 700px; height: 951px" /></p>
<p>
	【影片名称】：Eva<br />
	【中文名称】：伊娃<br />
	【年 &nbsp; &nbsp; &nbsp;代】：2011年<br />
	【国家地区】：西班牙<br />
	【语 &nbsp; &nbsp; &nbsp;言】：西班牙语<br />
	【类 &nbsp; &nbsp; &nbsp;别】：奇幻 / 剧情<br />
	【片 &nbsp; &nbsp; &nbsp;长】：94 分钟<br />
	【上映日期】：2011年10月28日 &nbsp;西班牙<br />
	【IMDB链接】：<a href="http://www.imdb.com/title/tt1298554/" target="_blank">http://www.imdb.com/title/tt1298554/</a><br />
	【IMDB评分】：6.3/10 from 835 users<br />
	【导 &nbsp; &nbsp; &nbsp;演】：凯克&middot;麦罗 Kike Ma&iacute;llo<br />
	【编 &nbsp; &nbsp; &nbsp;剧】：Sergi Belbel &nbsp;....screenplay<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Cristina Clemente &nbsp;....screenplay<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Aintza Serra &nbsp;....screenplay<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Mart&iacute; Roca &nbsp;....screenplay<br />
	【主 &nbsp; &nbsp; &nbsp;演】：克劳迪娅&middot;维加 Claudia Vega &nbsp;....Eva<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;丹尼尔&middot;布鲁赫 Daniel Br&uuml;hl &nbsp;....&Aacute;lex<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;阿尔贝托&middot;阿曼 Alberto Ammann &nbsp;....David<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;路易斯&middot;霍马 Llu&iacute;s Homar &nbsp;....Max<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;玛塔&middot;埃图娜 Marta Etura &nbsp;....Lana<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Sara Rosa Losilla<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Manuel Dueso<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;安娜&middot;卡鲁娃 Anne Canovas &nbsp;....Julia<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Jordi D&iacute;az<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Claudia Vega &nbsp;....Eva<br />
	<br />
	※※※※※※※　剧情简介　※※※※※※※<br />
	<br />
	&nbsp; &nbsp; &nbsp; 10岁的小女孩伊娃（克劳迪娅&middot;维加饰），因一场意外失去母亲后患上了失忆症，她被选为了新型人工智能机器人的模型。天才工程师阿莱克斯（丹尼尔&middot;布鲁赫饰）为此回到了自己的家乡</p>
<p>
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120430/22/62564813201204302246384007255603192_002.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120430/22/62564813201204302246384007255603192_001.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120430/22/62564813201204302246384007255603192_000.jpg" style="width: 720px; height: 405px" /><br />
	<br />
	&nbsp;</p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.net/" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy125:piaohua@dy125.piaohua.com:7998/飘花电影piaohua.com伊娃BD中英双字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:7998/飘花电影piaohua.com伊娃BD中英双字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15950b0-1UG.jpg{/dede:field}
