{dede:field name='keywords'}第39届全美音乐奖颁奖典礼DVD中{/dede:field}
{dede:field name='description'}第39届全美音乐奖颁奖典礼DVD中字迅雷下载、免费下载，第39届全美音乐奖颁奖典礼DVD中字Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}第39届全美音乐奖颁奖典礼DVD中字{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-12-01{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="/uploads/allimg/c120524/133N493D50-39A9.jpg" /></p>
<p>
	【剧名】：第39届全美音乐奖颁奖典礼/Annual American Music Awards 2011<br />
	【类型】：综艺<br />
	【单集片长】：180min<br />
	【资料编译】： 小组长@plx新闻组<br />
	【典礼介绍】</p>
<p>
	Nicki Minaj和Pitbull揭晓了2011年全美音乐奖提名并将现场表演，此外Katy Perry、Pitbull、Chris Brown、Justin Bieber、Maroon 5等将会作为表演嘉宾登场。奖项方面Adele以4项提名领跑，Katy Perry、Lady Gaga、Lil Wayne、Rihanna、Taylor Swift和The Band Perry各自以3项提名紧随其后，获得2项提名的艺人有Beyonce、Bruno Mars、Chris Brown、Jason Aldean、Kanye West、LMFAO、Nicki Minaj和Pitbull。年度最佳艺人奖项则在Adele、Katy Perry、Lady Gaga、Lil Wayne和Taylor Swift中产生。连续第五年，各奖项的得主将由观众在线投票决定，奖项类别分为流行/摇滚、乡村、说唱/嘻哈、灵魂/R&amp;B、另类、当代、拉丁等。</p>

<p>
	<br />
	【提名名单】</p>
<p>
	流行或摇滚乐POP or ROCK MUSIC<br />
	最受欢迎男艺人Favorite Male Artist<br />
	Justin Bieber<br />
	Bruno Mars<br />
	Pitbull</p>
<p>
	最受欢迎女艺人Favorite Female Artist<br />
	Adele<br />
	Lady Gaga<br />
	Katy Perry</p>
<p>
	最受欢迎乐队、两人组或团体Favorite Band, Duo or Group<br />
	LMFAO<br />
	Maroon 5<br />
	OneRepublic</p>
<p>
	最受欢迎专辑Favorite Album<br />
	Adele/21<br />
	Lady Gaga/Born This Way<br />
	Rihanna/Loud</p>
<p>
	<br />
	乡村音乐COUNTRY MUSIC<br />
	最受欢迎男艺人Favorite Male Artist<br />
	Jason Aldean<br />
	Brad Paisley<br />
	Blake Shelton</p>
<p>
	最受欢迎女艺人Favorite Female Artist<br />
	Sara Evans<br />
	Miranda Lambert<br />
	Taylor Swift</p>
<p>
	最受欢迎乐队、两人组或团体Favorite Band, Duo or Group<br />
	The Band Perry<br />
	Zac Brown Band<br />
	Lady Antebellum</p>
<p>
	最受欢迎专辑Favorite Album<br />
	Jason Aldean/My Kinda Party<br />
	The Band Perry/The Band Perry<br />
	Taylor Swift/Speak Now</p>
<p>
	<br />
	说唱/嘻哈音乐RAP/HIP-HOP MUSIC<br />
	最受欢迎艺人Favorite Artist<br />
	Lil Wayne<br />
	Nicki Minaj<br />
	Kanye West</p>
<p>
	最受欢迎专辑Favorite Album<br />
	Jay-Z &amp; Kanye West/Watch The Throne<br />
	Lil Wayne/Tha Carter IV<br />
	Nicki Minaj/Pink Friday</p>
<p>
	<br />
	灵魂乐/R&amp;B音乐SOUL/RHYTHM &amp; BLUES MUSIC<br />
	最受欢迎男艺人Favorite Male Artist<br />
	Chris Brown<br />
	Trey Songz<br />
	Usher</p>
<p>
	最受欢迎女艺人Favorite Female Artist<br />
	Beyonce<br />
	Rihanna<br />
	Kelly Rowland</p>
<p>
	最受欢迎专辑Favorite Album<br />
	Beyonce/4<br />
	Chris Brown/F.A.M.E.<br />
	Rihanna/Loud</p>
<p>
	<br />
	另类摇滚乐/ALTERNATIVE ROCK MUSIC<br />
	最受欢迎艺人Favorite Artist<br />
	The Black Keys<br />
	Foo Fighters<br />
	Mumford &amp; Sons</p>
<p>
	<br />
	当代音乐ADULT CONTEMPORARY MUSIC<br />
	最受欢迎艺人Favorite Artist<br />
	Adele<br />
	Bruno Mars<br />
	Katy Perry</p>
<p>
	<br />
	拉丁音乐LATIN MUSIC<br />
	Favorite Artist<br />
	Enrique Iglesias<br />
	Jennifer Lopez<br />
	Pitbull</p>
<p>
	<br />
	当代灵感音乐CONTEMPORARY INSPIRATIONAL<br />
	最受欢迎艺人Favorite Artist<br />
	Casting Crowns<br />
	Tobymac<br />
	Third Day</p>
<p>
	<br />
	年度最佳艺人ARTIST OF THE YEAR<br />
	Adele<br />
	Lady Gaga<br />
	Lil Wayne<br />
	Katy Perry<br />
	Taylor Swift</p>
<p>
	<br />
	Sprint年度最佳新人Sprint New Artist of the Year</p>
<p>
	流行/摇滚POP/ROCK<br />
	Foster The People<br />
	Hot Chelle Rae</p>
<p>
	乡村COUNTRY<br />
	The Band Perry<br />
	Thompson Square</p>
<p>
	灵魂/R&amp;B SOUL/R&amp;B<br />
	Marsha Ambrosius<br />
	Miguel</p>
<p>
	说唱/嘻哈RAP/HIP-HOP<br />
	LMFAO<br />
	Wiz Khalifa<br />
	下载地址：<img border="0" src="/uploads/allimg/c120524/133N2ZL930-142957.jpg" />
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				</anchor>ftp://dy44:piaohua@dy44.piaohua.com:2226/飘花电影piaohua.com第39届全美音乐奖颁奖典礼DVD中字CD1.rmvb</td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				</anchor><u>ftp://dy44:piaohua@dy44.piaohua.com:2227/飘花电影piaohua.com第39届全美音乐奖颁奖典礼DVD中字CD2.rmvb</u></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120524/133N493DQ0-49112.jpg{/dede:field}
