{dede:field name='keywords'}反抗军/挑战/挑战纳粹BD中英双字{/dede:field}
{dede:field name='description'}反抗军/挑战/挑战纳粹BD中英双字1024/1280高清迅雷下载、免费下载，反抗军/挑战/挑战纳粹BD中英双字1024/1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}反抗军/挑战/挑战纳粹BD中英双字1024/1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-10-29{/dede:field}
{dede:field name='body'}<p>
	<img alt="" border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://i1.sinaimg.cn/ent/d/2008-12-19/U105P28T3D2303151F326DT20081219145209.jpg');" src="http://i1.sinaimg.cn/ent/d/2008-12-19/U105P28T3D2303151F326DT20081219145209.jpg" />&nbsp;<br />
	<img alt="" border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://i3.sinaimg.cn/ent/d/2008-12-19/U105P28T3D2303152F326DT20081219145211.jpg');" src="http://i3.sinaimg.cn/ent/d/2008-12-19/U105P28T3D2303152F326DT20081219145211.jpg" /><br />
	<br />
	&nbsp;</p>
<p>
	◎译　　名　《反抗军/挑战/挑战纳粹/反抗》09丹尼尔&middot;克雷格最新战争大片DVD中英双字1024x550高清版<br />
	◎片　　名　Defiance<br />
	◎年　　代　2009<br />
	◎国　　家　美国<br />
	◎类　　别　动作/剧情/惊悚/战争<br />
	◎语　　言　英语<br />
	◎字　　幕　中英双字<br />
	◎IMDB评分 7.4/10&nbsp; 13,497 vote<br />
	◎文件格式　BD-RMVB<br />
	◎视频尺寸　1024 x 550<br />
	◎文件大小　1CD<br />
	◎片　　长　131min 20sec<br />
	◎导　　演　爱德华&middot;兹威克 Edward Zwick<br />
	◎主　　演　丹尼尔&middot;克雷格 Daniel Craig&nbsp; ....Tuvia Bielski<br />
	　　　　　　杰米&middot;贝尔 Jamie Bell&nbsp; ....Asael Bielski<br />
	　　　　　　艾莉克莎&middot;黛沃洛斯 Alexa Davalos&nbsp; ....Lilka<br />
	　　　　　　列维&middot;施瑞博尔 Liev Schreiber&nbsp; ....Zus Bielski<br />
	　　　　　　Mark Feuerstein&nbsp; ....Malbin<br />
	　　　　　　Mark Margolis&nbsp; ....The Ghetto Elder<br />
	　　　　　　Tomas Arana&nbsp; ....Ben Zion<br />
	　　　　　　George MacKay&nbsp; ....Aron Bielski<br />
	　　　　　　米娅&middot;华希科沃斯卡 Mia Wasikowska&nbsp; ....Chaya<br />
	　　　　　　乔迪&middot;梅 Jodhi May&nbsp; ....Tamara Skedelsky<br />
	　　　　　　Iddo Goldberg&nbsp; ....Yitzchak Shulman<br />
	　　　　　　杰克&middot;科曼 Jacek Koman&nbsp; ....Koscik<br />
	　　　　　　阿兰&middot;柯德勒 Allan Corduner&nbsp; ....Shamon<br />
	　　　　　　萨姆&middot;斯普卢尔 Sam Spruell&nbsp; ....Arkady Lubezanski<br />
	　　　　　　Markus von Lingen&nbsp; ....SS Scout<br />
	　　　　　　Sakalas Uzdavinys&nbsp; ....Lova<br />
	　　　　　　Rolandas Boravskis&nbsp; ....Gramov<br />
	<br />
	◎简　　介　<br />
	<br />
	&nbsp; &nbsp; 本片的剧情取自真实事件，故事来自于第二次世界大战期间的一个游击队传奇。克雷格所饰演的主角出生在波兰的一个犹太家庭里，身为长子的他很快成了家中的一把手。除他之外，家中还有两个弟弟，一家五口人其乐融融，生活倒也平静。但二战的炮火摧毁了一切！1939 年9 月1 日, 法西斯德**用&rdquo;闪电战&rdquo;的手段, 发动了侵略波兰的战争。仅10 多天时间, 就使波军全线溃败, 27 天后首都陷落, 国家灭亡。随着波兰政权的灭亡，纳粹对犹太人疯狂的屠戮紧跟其后。白色死亡的阴影笼罩大地，为了活命，身为长子的主角只身带领两个弟弟从纳粹德国占领的波兰逃往白俄罗斯。为了避开纳粹的追杀，最终遁入荒无人烟的大森林。<br />
	<br />
	&nbsp; &nbsp; 哪里有压迫哪里就有反抗，兄弟三人被当地的群众收留。在国仇家恨的推动下，他们义无反顾地加入前苏联反抗军，举起了抗击纳粹的大旗。俗话说得好，是金子总会发光的，在对抗纳粹出生入死的抗击过程中，主人公磨练出高超的作战技巧和沉稳冷静的性格，逐渐在他身边出现了一批跟随者。最终成长为一个抗击法西斯的游击队长，纳粹灭绝的是人性，对于出没于森林中的游击队，他们展开了疯狂的反扑。而主人公所率领的游击队则利用地形等因素，巧妙地与其周旋。丛林中的生活相当艰苦，危险时刻都会降临，但对自由的向往以及对纳粹的痛恨支持他们一步步走下去，甚至他们还在密林中建立起了一个他们自己的村庄！在二战期间，他们拯救了超过1200多条犹太人的生命，从而成就了一段传奇。</p>
<p>
	影片幕后<br />
	<br />
	&nbsp; &nbsp; 从商业的角度来说，这部影片从头到脚都散发着浓厚的007的跟风气息，不论是主角丹尼尔&middot;克雷格的选取，极其类似的拍摄风格，依然是枪战动作的定位，乃至预告片中镜头的拍摄角度都如此地相似，而原本上映档期紧随007之后，更是将这种跟风气息烘托到了极致。不过最终不知是发行方觉得这样做太露骨还是真有幕后隐情，终究还是推迟了原本的上映档期：于11月9日在Cinerama Dome影院全球首映，12月12日北美全线上映。而推迟后的上映时间为12月31日小规模上映，2009年1月16日正式大规模上映。这样的决定无疑宣告了本片奥斯卡征程的终结，虽然本片挤进奥斯卡评委视线的可能性几乎为零！而官方对于推迟上映时间的解释&mdash;&mdash;经济危机更是让人有一种哭笑不得的感觉，希望本片不要象丹尼尔&middot;克雷格在片中的扮相那样一身沧桑。<br />
	&nbsp; &nbsp;<br />
	&nbsp; &nbsp; 虽然影片处处有007跟风的嫌疑，但影片的导演还是用自己的实际行动来力证自身的清白。导演爱德华&middot;兹威克也算是好莱坞的一线导演了，在他的手下出现了为数不少的佳作。当年堪称经典的《光荣战役》、《燃情岁月》彰显他对于宏大故事题材彪悍的掌控能力，《最后的武士》中又展现出他细腻的人物刻画功底，前些年的《血钻》更是将这两者结合，从而引起广泛的赞誉，也助里昂那多在离开马丁爷爷后继续留住&ldquo;演技天才&rdquo;的头衔。有人说若是没有《美丽心灵》朗-霍华德绝对会在第一时间被归类为商业导演，奥斯卡成就了他艺术与商业通吃的地位。相比之下，爱德华&middot;兹威克并无奥斯卡的黄袍加身，但无人能够否认他能将艺术与商业结合至完美的天赋。而在10月30日开幕的美国电影学会(AFI)电影节上，组委会宣布选择《反抗军》作为闭幕片，相信也是为了向导演表示致敬。<br />
	<br />
	&nbsp; &nbsp; 说到影片的几位主演，除了地球人都知道的丹尼尔&middot;克雷格以外。还有杰米&middot;贝尔以及女主角艾莉克莎&middot;黛沃洛斯，提到杰米&middot;贝尔几乎所有的人都会想到那部让他一举成名的《舞动人生》，再说近点，就是《心灵传输者》中和海登&middot;克里斯滕森演对手戏的小帅哥。其实杰米&middot;贝尔并没有一个很好的家庭环境，他妈妈在16岁的时候就生下了他，而小杰米也从未见过他的父亲。不过他祖母、母亲以及姨妈以及姐姐都是舞者，这也使他能够更多地接触到舞蹈艺术。在这样的生活背景下，他六岁就开始学习舞蹈，当然第一时间接触的自然是芭蕾，但踢踏舞才是他的拿手绝活。这些人生经验的积累终于在《舞动人生》中让杰米&middot;贝尔有了一次完美的爆发，贝尔凭借他扎实地功底通过了七次面试，最终从两千名男孩中脱颖而出。随后的事情便一发不可收拾了，这部电影让无数人为之倾倒，从某种程度上来说影片中的Billy的人生经历就是他自己的一份独白，所以杰米如鱼得水般地将自己融入到了角色中，从而完美到令人惊叹地完成了片中的角色塑造。这样表演让业界没有理由不为这位年仅十四岁的贝尔感到惊叹，2001年他在BAFTA评奖中击败Russell Crowe、Tom Hanks、Michael Douglas以及Geoffrey Rush四位奥斯卡影帝而获得最佳男演员奖，此外也成为继1987年《太阳帝国》的克里斯汀&middot;贝尔之后第二个被美国National Board of Review授予Outstanding Performance by a Young Actor的演员；2001年贝尔还有幸地担任了Giffoni Film Festival的荣誉评审主席。这些荣誉对于一个十四岁的演员来说，简直就是奇迹。<br />
	&nbsp; &nbsp;<br />
	&nbsp; &nbsp; 但对于大多数童星来说，成名作中的倾情出演大多是因为他们碰上<a href="http://www.eee4.com/" target="_blank">电影下载</a>了适合自身的角色而已，所以不过是本色出演从而赋予人物以生命力，说白了就是在表演自己。但要求一个孩子怎样去磨练演技从而适应随后不同的角色的确有些强人所难，所以大多数童星在成名作大红大紫之后都会迅速地转入衰败，更有甚者就此销声匿迹。而对于杰米&middot;贝尔这也他不得不面对的问题，毕竟《舞动人生》过于光辉耀眼。但杰米&middot;贝尔无疑拥有超越同龄人的远见，他立马宣称除了&ldquo;《红磨坊》和《芝加哥》开拍续集，否则他将永远不再电影中跳舞&rdquo;，并且接连接拍了很多不同类型的角色，如《少爷返乡》中的跛脚孩子史迈克，《Deathwatch》中的新兵，《The Chumscrubber》里叛逆的南加州少年等。不出所料，这些角色都没有受到什么重视，但我们可以看出他对于扩展自己银幕戏路的努力，而相信有一天他终将站在好莱坞的第一线。<br />
	<br />
	制作花絮： 新任007的转型之作<br />
	<br />
	&nbsp; &nbsp; 丹尼尔&middot;克雷格，这位刚刚凭借007最新一集风靡全球的男星，为了避免银幕形象定格于007而止步不前，两年来他也接拍了不少其他类型的电影。对于《反抗军》中这个犹太人的角色，丹尼尔&middot;克雷格说：&ldquo;这个故事的主角非常让人敬佩，他一生的经历很传奇。我在拿到剧本的时候很认真的想了一下，这个人物究竟适合不适合自己去演。后来大概是心中的虚荣心作祟（笑），我决定要演这个角色。图维那身上有很多东西，电影中展现了他的信念，还有他对亲情的态度，以及非常浪漫的军旅生涯。初期图维那的生活过得很艰苦，我曾经问导演，这么苦的人，如何&lsquo;浪漫&rsquo;得起来？导演对我说，你要是在那种情况下，你得学会苦中作乐，这样才能生存下去。我觉得导演说得很有道理，因此在影片中，我会经常微笑。这个角色，不但自己要有足够的信心，他也应该带给其他人信心，所以在影片中的图维那，更具有一种领袖气质。&rdquo;<br />
	<br />
	&nbsp; &nbsp; 关于本片所在的年代，还有影片中主角之间的亲情、友情、爱情，丹尼尔&middot;克雷格说：&ldquo;这部电影实在讲了太多的东西，拍的时候我在想，爱德华你怎么才能把那么多故事在那么短的时间里讲清楚？我很喜欢和列维&middot;施瑞博尔、杰米&middot;贝尔合作，他们都是很有趣的人，这次能在银幕上共同演出，我感到非常的开心。影片里，我和列维&middot;施瑞博尔有不少的对手戏，在拍摄的时候我常常对他怒吼，不过都是故事需要，影片外，我倒也经常叫他弟弟，不过他却不叫我哥哥（笑）。这个故事发生在二战时期，那是一段包含很多悲痛的时代，关于犹太人抗击纳粹侵略者的故事也很多，而《反抗军》与众不同的地方，就是讲述了一群非常勇敢的犹太人，他们拿起武器捍卫着自己的尊严，而且多次成功的回击了纳粹，这是非常了不起的人，值得所有人对他们抱以尊敬。&rdquo;<br />
	&nbsp;<br />
	影片简评<br />
	&nbsp;<br />
	&nbsp; &nbsp; 正如我前文所述，虽然从上映日期到影片风格都不禁让人怀疑导演在按007的套路来打造这部影片，但终究怀疑只是怀疑，导演还是用自己的实际行动来证明这部影片的与众不同。要看这部影片，我们还是要从导演自身的风格入手。<br />
	<br />
	&nbsp; &nbsp; 爱德华&middot;兹威克的作品都有两大特点，这些我都在前文提到了，第一是商业与<a href="http://www.eee4.com/" target="_blank">迅雷电影下载</a>艺术相结合的强大天赋；第二是一贯宏大的叙事结构和对人物形象细腻的刻画。先看第一点，从影片的预告片中我们就可以看出，导演力求能够还原真实的历史画面，为了表现出丛林战争的真实环境，根据透漏出的消息，剧组还全体进入立陶宛的森林里拍摄外景，为此几乎所有人都吃尽了苦头。在这样精心地打造下，影片的画面散发着浓厚的沧桑感，艺术带入感相当强。而对于商业性的把握一如既往地表现在大场面和群戏的调度上，兹威克对场面的出色调度和群戏的良好掌控是他的拿手绝活，这也是他作品部部精彩的保证。<br />
	<br />
	&nbsp; &nbsp; 第二点更是爱德华&middot;兹威克的门面招牌。二战大背景的烘托下，影片的故事更呈现出波澜壮阔的美感。二战中的传奇故事，进而影射整个二战欧洲战场，通过一直游击队伍高唱广大人民群众对自由向往的赞歌，以及对法西斯暴政坚决地反抗。正如导演之前的作品，不论是《光荣战役》、《燃情岁月》乃至《最后的武士》和《血钻》，不管剧情架构如何，影片都拥有宏伟的史诗气魄。而从人物方面来说，相比于007无疑这个角色能给丹尼尔&middot;克雷格提供更加广阔的发挥空间。其实我一直很欣赏丹尼尔&middot;克雷格，个人认为他超越布鲁斯南之处在于他没有被邦德这个形象所束缚。想当年肖恩康纳利辞演邦德的理由就是：&ldquo;不想让这个人物束缚住我的手脚&rdquo;，而随后历任邦德在出演007系列后，演绎生涯几乎都在不同程度上受到影响。唯独丹尼尔&middot;克雷格是个例外，出任邦德后他依然不断地在各类影片中塑造各类截然不同的角色，而且也并没有被限制在动作领域，反而更加游刃有余地游走在商业和艺术领域，从这一点来说，丹尼尔&middot;克雷格的确超越了以前的邦德演员。<br />
	<br />
	&nbsp; &nbsp; 而本片的人物拥有更加复杂的个性与人生经历，他既是一个游击队长同时也是一个兄长，对于敌人他要冷酷无情；对于兄弟爱人，他要温柔似水。在战争的重压下，人性的光芒无可比拟。007是一个虚拟的英雄，演员有更加广阔的空间去加入自身的表演理念，可以更加随意地发挥和塑造角色。而真正的史实英雄却有着诸多的限制，更何况不但表现要出人物光辉的一面，还要刻画出他表面下人物性格，其难度之大可想而知。但丹尼尔&middot;克雷格的演技加上兹威克宏大而不失细腻的人物刻画手法，都让我们对这个人物有足够的期待，同样也希望片中出演克雷格两个弟弟的列维&middot;施瑞博尔和杰米&middot;贝尔一样能够上佳的表演。</p>
<p>
	影片截图:<br />
	<br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://img.album.pchome.net/54/69/71/97/9bcb8cb8fb3ef7b1df3f12767156e1e6.jpg');" src="http://img.album.pchome.net/54/69/71/97/9bcb8cb8fb3ef7b1df3f12767156e1e6.jpg" /><br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://img.album.pchome.net/54/69/71/97/2f5103e5d3960ce914f6c1cb0353dd39.jpg');" src="http://img.album.pchome.net/54/69/71/97/2f5103e5d3960ce914f6c1cb0353dd39.jpg" /><br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://img.album.pchome.net/54/69/71/97/1da73e1b076eced8d6f9a57dfa361925.jpg');" src="http://img.album.pchome.net/54/69/71/97/1da73e1b076eced8d6f9a57dfa361925.jpg" /></p>
<p>
	<br />
	<br />
	<b>中文字幕版本截图：</b><br />
	<br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://img.album.pchome.net/54/68/37/76/aa350efe383d4119144da015e18e01e4.jpg');" src="http://img.album.pchome.net/54/68/37/76/aa350efe383d4119144da015e18e01e4.jpg" /><br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://img.album.pchome.net/54/68/37/76/496617f487a5ef090f5b1c59ca0cd75a.jpg');" src="http://img.album.pchome.net/54/68/37/76/496617f487a5ef090f5b1c59ca0cd75a.jpg" /><br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://img.album.pchome.net/54/68/37/76/58827fdecb12afd3629f7001ba03855b.jpg');" src="http://img.album.pchome.net/54/68/37/76/58827fdecb12afd3629f7001ba03855b.jpg" /><br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://img.album.pchome.net/54/68/37/76/c03595d40189fa7372c4866520a03b18.jpg');" src="http://img.album.pchome.net/54/68/37/76/c03595d40189fa7372c4866520a03b18.jpg" /><br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://img.album.pchome.net/54/68/37/76/231234aacb054783fb409294f42a355e.jpg');" src="http://img.album.pchome.net/54/68/37/76/231234aacb054783fb409294f42a355e.jpg" /></p>
<p>
	中英字幕版本截图:<br />
	<br />
	<img alt="" border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://img.album.pchome.net/54/69/71/97/07be5c34a321d31433b671d4c933107d.jpg');" src="http://img.album.pchome.net/54/69/71/97/07be5c34a321d31433b671d4c933107d.jpg" />&nbsp;<br />
	<img alt="" border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://img.album.pchome.net/54/69/71/97/4419ad293f9aee48843ebf48d920e458.jpg');" src="http://img.album.pchome.net/54/69/71/97/4419ad293f9aee48843ebf48d920e458.jpg" />&nbsp;<br />
	<img alt="" border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://img.album.pchome.net/54/69/71/97/dbdab29395395869639b7dc054e8826b.jpg');" src="http://img.album.pchome.net/54/69/71/97/dbdab29395395869639b7dc054e8826b.jpg" />&nbsp;<br />
	<img alt="" border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://img.album.pchome.net/54/69/71/97/ad6b3d76b916296e6d6c5e3de02e95fa.jpg');" src="http://img.album.pchome.net/54/69/71/97/ad6b3d76b916296e6d6c5e3de02e95fa.jpg" /></p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<anchor></anchor><a href="ftp://e18:e18@xl2.eee4.com:9916/[3E电影站www.eee4.com]反抗军CD1.rmvb" target="_blank">ftp://e18:e18@xl2.eee4.com:9916/[3E电影站www.eee4.com]反抗军CD1.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<anchor></anchor><a href="ftp://e18:e18@xl2.eee4.com:9916/[3E电影站www.eee4.com]反抗军CD2.rmvb" target="_blank">ftp://e18:e18@xl2.eee4.com:9916/[3E电影站www.eee4.com]反抗军CD2.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<anchor></anchor><a href="ftp://e24:e24@xl2.eee4.com:9306/[3E电影站www.eee4.com]反抗军DVD中英双字CD1.rmvb" target="_blank">ftp://e24:e24@xl2.eee4.com:9306/[3E电影站www.eee4.com]反抗军DVD中英双字CD1.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<anchor></anchor><a href="ftp://e24:e24@xl2.eee4.com:9306/[3E电影站www.eee4.com]反抗军DVD中英双字CD2.rmvb" target="_blank">ftp://e24:e24@xl2.eee4.com:9306/[3E电影站www.eee4.com]反抗军DVD中英双字CD2.rmvb</a></td>
		</tr>
	</tbody>
</table>
<br />
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://e26:e26@xl2.eee4.com:9306/[3E电影站www.eee4.com]反抗军DVD中英双字1024x550高清版.rmvb" target="_blank">ftp://e26:e26@xl2.eee4.com:9306/[3E电影站www.eee4.com]反抗军DVD中英双字1024x550高清版.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				&nbsp;<a href="ftp://dy44:piaohua@dy44.piaohua.com:1943/飘花电影piaohua.com反抗军BD中英双字1280高清.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:1943/飘花电影piaohua.com反抗军BD中英双字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1625Y50-52231.jpg{/dede:field}
