<?php
$z[0]=Array("field","山地自行车/生命周期/山地自行车",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","山地自行车/生命周期/山地自行车之旅[BD中英双字1024x512高清版]迅雷下载、免费下载，山地自行车/生命周期/山地自行车之旅[BD中英双字1024x512高清版]Gvod高清在线播放，剧情介绍等。",73,287);
$z[1][4]['name']="description";
$z[2]=Array("field","山地自行车/生命周期/山地自行车之旅[BD中英双字1024x512高清版]",289,387);
$z[2][4]['name']="title";
$z[3]=Array("field","",389,428);
$z[3][4]['name']="writer";
$z[4]=Array("field","",430,469);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-03-23",471,521);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",523,560);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://3e:3e@d3.3edyy.com:143/【3E看看www.3ekk.com】山地自行车[BD中英双字1024x512高清版].rmvb\" target=_blank>ftftp://3e:3e@d3.3edyy.com:143/【3E看看www.3ekk.com】山地自行车[BD中英双字1024x512高清版].rmvb</A></TD></TR></TBODY></TABLE></div><ul class=\"mmlist",562,856);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MQ4MR0-4LX.jpg",858,938);
$z[8][4]['name']="litpic";

?>