<?php
$z[0]=Array("field","大人物拿破仑/炸弹的异想世界BD",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","大人物拿破仑/炸弹的异想世界BD中英双字1280高清迅雷下载、免费下载，大人物拿破仑/炸弹的异想世界BD中英双字1280高清Gvod高清在线播放，剧情介绍等。",72,256);
$z[1][4]['name']="description";
$z[2]=Array("field","大人物拿破仑/炸弹的异想世界BD中英双字1280高清",258,341);
$z[2][4]['name']="title";
$z[3]=Array("field","",343,382);
$z[3][4]['name']="writer";
$z[4]=Array("field","",384,423);
$z[4][4]['name']="source";
$z[5]=Array("field","2012-05-04",425,475);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",477,514);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://e42:e42@xl2.eee4.com:9024/[3E电影站www.eee4.com]大人物拿破仑.rmvb\" target=\"_blank",516,642);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MO5K0-41639.jpg",644,725);
$z[8][4]['name']="litpic";

?>