{dede:field name='keywords'}美好2012之春暖花开HD国语中字20{/dede:field}
{dede:field name='description'}美好2012之春暖花开HD国语中字2012中国剧情迅雷下载、免费下载，美好2012之春暖花开HD国语中字2012中国剧情Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}美好2012之春暖花开HD国语中字2012中国剧情{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-17{/dede:field}
{dede:field name='body'}<p>
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120517/16/56643687201205171651161376906478943_004.jpg" /></p>
<p>
	别名:春暖花开<br />
	上映:2012-05-17<br />
	地区:大陆<br />
	类型:剧情<br />
	导演:吕惠洲<br />
	主演:房祖名 / 王思思</p>
<p>
	剧情简介</p>
<p>
	由于父亲身患重病，女儿橙橙放弃了留学的想法，为了不让父亲失望，她谎称自己在伦敦留学，并且找了一个合约男友坎子替她照顾父亲。坎子和搭档定期帮橙橙拍摄照片和视频，技术处理后给橙橙爹看，制造橙橙在英国的假象。 而坎子渐渐喜欢上了橙橙，拿橙橙爹当亲爹来照顾，但这种尴尬的关系让坎子无从表白。 在橙橙爹病危之际，坎子拼尽全力挽救他的生命，但橙橙爹却对一盘记录橙橙童年的录像带念念不忘，最终，在橙橙和坎子的陪伴下，橙橙爹安然离去了。而坎子和橙橙的合约也戛然而止，坎子此时要如何面对这段感情&hellip;&hellip;</p>
<p>
	<br />
	◎影片截图</p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120517/16/56643687201205171651161376906478943_003.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 337px; border-top: 0px solid; border-right: 0px solid" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120517/16/56643687201205171651161376906478943_002.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 337px; border-top: 0px solid; border-right: 0px solid" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120517/16/56643687201205171651161376906478943_001.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 337px; border-top: 0px solid; border-right: 0px solid" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120517/16/56643687201205171651161376906478943_000.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 337px; border-top: 0px solid; border-right: 0px solid" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.netftp//dy44:piaohua@dy44.piaohua.com:3142/" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3444/飘花电影piaohua.com美好2012之春暖花开BD国语中字.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3444/飘花电影piaohua.com美好2012之春暖花开BD国语中字.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15cQP-4T03.jpg{/dede:field}
