<?php
$z[0]=Array("field","被破坏的男人/被毁的男人[DVD中",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","被破坏的男人/被毁的男人[DVD中英双字]迅雷下载、免费下载，被破坏的男人/被毁的男人[DVD中英双字]Gvod高清在线播放，剧情介绍等。",72,238);
$z[1][4]['name']="description";
$z[2]=Array("field","被破坏的男人/被毁的男人[DVD中英双字]",240,314);
$z[2][4]['name']="title";
$z[3]=Array("field","",316,355);
$z[3][4]['name']="writer";
$z[4]=Array("field","",357,396);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-08-24",398,448);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",450,487);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://4e:4e@d8.3edyy.com:178/【3E电影院www.eee4.cc】被破坏的男人DVD中英双字.rmvb\" target=_blank>ftftp://4e:4e@d8.3edyy.com:178/【3E电影院www.eee4.cc】被破坏的男人DVD中英双字.rmvb</A></TD></TR></TBODY></TABLE></div><ul class=\"mmlist",489,759);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MP32N0-21022.jpg",761,843);
$z[8][4]['name']="litpic";

?>