{dede:field name='keywords'}邓紫棋2011香港红馆演唱会BD1280{/dede:field}
{dede:field name='description'}邓紫棋2011香港红馆演唱会BD1280高清迅雷下载、免费下载，邓紫棋2011香港红馆演唱会BD1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}邓紫棋2011香港红馆演唱会BD1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-01-08{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="/uploads/allimg/c120525/133O0a91Q0-161I4.jpg" style="width: 613px; height: 765px" /></p>
<p>
	香港乐坛小天后邓紫棋(G.E.M.)2011年初踏红馆，在5月14日至16日举行第二次个人演唱会《Get Everybody Moving Concert 2011》，<br />
	<br />
	令她以19岁之龄创下了红馆开演唱会最年轻的女艺人纪录。G.E.M.在一连三场的演唱会尽展浑身解数，以雄浑有力的声线演绎出道以来<br />
	<br />
	的成名作和创作歌曲，「等一个他」、「Where Did U Go」、「A.I.N.Y.」、「Get Over You」等等，尽展爆发力的唱功，再显巨肺唱<br />
	<br />
	功和挑战自我的本色。G.E.M.还即兴演绎和载歌载舞，展示她才华洋溢的一面。<br />
	由于反应热烈，《Get Everybody Moving Concert 2011》于9月再次加场两场为Part II，而5月份的红馆个唱Part I更安排于11月在戏<br />
	<br />
	院限时上映，让G.E.M.成为首位将个唱呈现于大银幕的香港歌手。<br />
	预购版附上全彩色G.E.M.演唱会巨型相本。<br />
	<br />
	【片　　源】G.E.M.-Get.Everybody.Moving.Concert.2011.Blu-ray.1080i.AVC.LPCM.DHD-HDRoad<br />
	【文件格式】x264+DTS<br />
	【视频尺寸】1280 x 720<br />
	【文件体积】1.56G<br />
	:专辑曲目<br />
	<br />
	01. 想讲你知<br />
	02. 我不懂爱<br />
	03. 等一个他<br />
	04. The Voice Within 遗失声音<br />
	05. Get Over You<br />
	06. G.E.M.&lsquo;s Jive<br />
	07. 美好的旧时光 In My Heart<br />
	08. 睡公主<br />
	09. 情人<br />
	10. MySecret 我的秘密<br />
	11. Game Over<br />
	12. All About U<br />
	13. Good to be Bad<br />
	14. 寂寞星球的玫瑰<br />
	15. 塞纳河<br />
	16. A.I.N.Y.<br />
	17. Twinkle II<br />
	18. 18<br />
	19. You Raise Me Up<br />
	20. Mascara (烟熏妆)<br />
	21. Just The Way You Are<br />
	22. One Button<br />
	23. Lady Marmalade<br />
	24. Wanna Be Startin&lsquo; Somethin&lsquo;<br />
	25. Don&lsquo;t Stop The Music<br />
	26. Get Everybody Moving<br />
	27. 忐忑<br />
	28. Where Did U Go<br />
	<img alt="" src="/uploads/allimg/c120525/133O0a9320-1I347.jpg" style="width: 720px; height: 405px" /><img alt="" src="/uploads/allimg/c120525/133O0a94230-1R2N.jpg" style="width: 720px; height: 405px" /><br />
	&nbsp;</p>
[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="/uploads/allimg/c120525/133O0T31310-42214.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
<tbody>
<tr>
<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">

ftp://dy125:piaohua@dy125.piaohua.com:7381/飘花电影piaohua.com邓紫棋2011香港红馆演唱会BD中字1280高清.rmvb</td>
</tr>
</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O0a95510-195517.jpg{/dede:field}
