{dede:field name='keywords'}上帝保佑美国DVD中字2012美国剧{/dede:field}
{dede:field name='description'}上帝保佑美国DVD中字2012美国剧情喜剧迅雷下载、免费下载，上帝保佑美国DVD中字2012美国剧情喜剧Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}上帝保佑美国DVD中字2012美国剧情喜剧{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-04-24{/dede:field}
{dede:field name='body'}<p>
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120424/12/56643687201204241215302853324720629_005.jpg" /></p>
<p>
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120424/12/56643687201204241219089773619571018_000.jpg" /></p>
<p>
	◎译　　名 上帝保佑美国/天佑美利坚<br />
	◎片　　名 God Bless America<br />
	◎年　　代　2011<br />
	◎国　　家　美国<br />
	◎类　　别　剧情/喜剧<br />
	◎语　　言　英语<br />
	◎字　　幕　中文<br />
	◎IMDB评分 6.8/10 from 349 users<br />
	◎IMDB链接 <a href="http://www.imdb.com/title/tt1912398">http://www.imdb.com/title/tt1912398</a><br />
	◎文件格式　DVD-RMVB<br />
	◎视频尺寸　720 x 304<br />
	◎文件大小　1CD 528MB<br />
	◎片　　长　104 Mins<br />
	◎导　　演　博卡&middot;格德斯维特 Bobcat Goldthwait<br />
	◎主　　演　Joel Murray &hellip;.Frank<br />
	　　　　　　Tara Lynne Barr &hellip;.Roxy<br />
	　　　　　　Mackenzie Brooke Smith &hellip;.Ava<br />
	　　　　　　Melinda Page Hamilton &hellip;.Alison<br />
	　　　　　　Rich McDonald &hellip;.Brad<br />
	　　　　　　Guerrin Gardner &hellip;.Crystal<br />
	　　　　　　Kellie Ramdhanie &hellip;.Bad Girl #2<br />
	　　　　　　Andrea Harper &hellip;.Mother<br />
	　　　　　　David Mendenhall &hellip;.Father<br />
	　　　　　　Juliana Acosta ....Press Conference Reporter<br />
	　　　　　　Steve Agee ....Crew Member<br />
	　　　　　　Iris Almario ....Reporter<br />
	　　　　　　Aris Alvarado ....Steve Clark<br />
	　　　　　　Carson Aune ....Boy #2<br />
	　　　　　　Dorie Barton ....Tracey<br />
	　　　　　　David Boat ....(voice)<br />
	　　　　　　Kirk Bovill ....Police Captain<br />
	　　　　　　Claude Bragg ....Rich High School Kid<br />
	　　　　　　Romeo Brown ....John Tyler<br />
	　　　　　　Regan Burns ....Michael Dunne<br />
	　　　　　　Aaron Burt ....Jerky Boy #2<br />
	　　　　　　Michael Carbonaro ....Robbie Barkly<br />
	　　　　　　Jack Plotnick ....Party Planner #2<br />
	　　　　　　Brendalyn Richard ....Karen<br />
	　　　　　　Maico Roa ....Press Conference Reporter<br />
	　　　　　　Brad Rowe ....Angry Man<br />
	　　　　　　James Rustin ....Rich Boy<br />
	　　　　　　Nate Scholz ....Paparazzi<br />
	　　　　　　Claudia Serven ....American Superstarz Celebrity<br />
	　　　　　　Dan Spencer ....Doctor<br />
	　　　　　　Sasha Stuber ....Amber<br />
	　　　　　　Christopher Swank ....Office Worker<br />
	　　　　　　Jill Talley ....Sue<br />
	　　　　　　Philip Anthony Traylor ....Security Guard<br />
	　　　　　　Mike Tristano ....Mike<br />
	　　　　　　Tony V. ....Humbert Green<br />
	　　　　　　Sandra Vergara ....Mercedes Paar<br />
	　　　　　　特拉维斯&middot;韦斯特 Travis Wester ....Ed<br />
	　　　　　　Scot Zeller ....Ronald<br />
	　　　　　　Fileena Bahris ....American Superstarz Fan (uncredited)<br />
	　　　　　　Joanne Bahris ....Audience Member (uncredited)<br />
	　　　　　　I. Elijah Baughman ....Bodyguard (uncredited)<br />
	　　　　　　Curt Darwin ....Extra (uncredited)<br />
	　　　　　　Joe Ford ....Extra (uncredited)<br />
	　　　　　　Brittany King ....Extra (uncredited)<br />
	　　　　　　Janine King ....Extra (uncredited)<br />
	　　　　　　Tom Massmann ....Bodyguard (uncredited)<br />
	　　　　　　Eric Salazar ....Patron (uncredited)<br />
	　　　　　　Keith Shawn ....Fan (uncredited)<br />
	　　　　　　Sarah B. Downey ....Office Worker<br />
	　　　　　　Frederick Gourgue ....TMI Camera man<br />
	　　　　　　Lenny Porterfield ....Security Guard<br />
	　　　　　　Nevan Stewart ....Standing Cameraman (uncredited)</p>

<p>
	◎简　　介</p>
<p>
	一位无所事事的的中年男人坐在在家里看电视，真人秀里面的年轻女孩总是贪得无厌，想要得到全世界。中年男人看着这样的青春期女孩感到忍无可忍，开车400米枪杀了无辜的邻家女孩...这个女孩的同学见到恐怖一幕并没有看到害怕，反而觉得这个男人太酷了！两人一拍即合，结伴去大街上继续他们的杀人游戏。</p>
<p>
	<br />
	◎影片截图</p>
<p>
	&nbsp;<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120424/12/56643687201204241215302853324720629_004.jpg" /></p>
<p>
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120424/12/56643687201204241215302853324720629_001.jpg" /></p>
<p>
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120424/12/56643687201204241215302853324720629_003.jpg" /></p>
<p>
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120424/12/56643687201204241215302853324720629_000.jpg" /></p>
<p>
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120424/12/56643687201204241215302853324720629_002.jpg" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.netftp//dy44:piaohua@dy44.piaohua.com:3201/" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3282/飘花电影piaohua.com上帝保佑美国DVD中字.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3282/飘花电影piaohua.com上帝保佑美国DVD中字.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15EMZ-19544.jpg{/dede:field}
