{dede:field name='keywords'}黄羊滩押解HD1280高清迅雷下载，{/dede:field}
{dede:field name='description'}黄羊滩押解HD1280高清迅雷下载、免费下载，黄羊滩押解HD1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}黄羊滩押解HD1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-02-21{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://www.hdstar.org/attachments/20120218/201202181130576d13a13c48d77947d93312f63f913408.jpg" style="width: 450px; height: 253px" /></p>
<p>
	中文片名：黄羊滩押解<br />
	　　国家/地区：中国<br />
	　　导演：安澜<br />
	　　类型：谍战<br />
	<br />
	　由八一电影制片厂拍摄的反映解放战争期间我军谍报人员与敌特份子斗智斗勇的谍战故事的影片《黄羊滩押解》于2011年7月在张家口市下花园区热拍。<br />
	　　黄羊滩，位于张家口市下花园区洋河南岸燕山北麓&mdash;黄羊山脚下，占地40多平方公里，素有京西沙漠城之美誉，是京西唯一的风蚀沙漠。据史书记载，晚唐时晋王李克用，曾在这里养牧过军马。传说宋辽时期的&ldquo;金沙滩&rdquo;战役也发生在此地。解放战争时期这里傅作义各部队之间联系的重要通道。后人根据历史资料创编了电影&mdash;黄羊滩押解。下花园区委书记王忠富为电影题写了片名《黄羊滩押解》。<br />
	<br />
	&nbsp;</p>
<p>
	<img alt="" src="http://www.hdstar.org/attachments/20120218/20120218113140043807be19718a7fa620724e5e7a67f6.jpg" style="width: 650px; height: 1157px" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>


<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="&#13;&#10;ftp://dy125:piaohua@dy125.piaohua.com:7630/飘花电影piaohua.com黄羊滩押解HD国语中字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:7630/飘花电影piaohua.com黄羊滩押解HD国语中字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O151605Z-432W.jpg{/dede:field}
