{dede:field name='keywords'}理查德·哈蒙德：看不见的世界BD{/dede:field}
{dede:field name='description'}理查德·哈蒙德：看不见的世界BD中字1024高清BBC纪录片迅雷下载、免费下载，理查德·哈蒙德：看不见的世界BD中字1024高清BBC纪录片Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}理查德·哈蒙德：看不见的世界BD中字1024高清BBC纪录片{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-06-29{/dede:field}
{dede:field name='body'}<p>
	<img src="/uploads/allimg/c120524/133N4OY0P-15S5.jpg" /></p>
<p>
	◎译　　名　BBC 理查德&middot;哈蒙德：看不见的世界 第一季<br />
	◎片　　名　BBC Richard Hammond&#39;s Invisible Worlds Season 1<br />
	◎年　　代　2010<br />
	◎国　　家　英国<br />
	◎制作发行　BBC One<br />
	◎类　　别　纪录/科技<br />
	◎语　　言　英语<br />
	◎IMDB评分 8.7/10 (90 votes)<br />
	◎文件格式　x264 + AAC<br />
	◎视频尺寸　1024 x 576<br />
	◎文件大小　3CD<br />
	◎片　　长　149 mins 1 seconds<br />
	◎导　　演　理查德&middot;哈蒙德 Richard Hammond</p>
<p>
	<br />
	◎简　　介</p>
<p>
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 理查德&middot;哈蒙德主持的这部《理查德&middot;哈蒙德：视觉外的世界》带领我们观赏那些超出人眼视觉极限的平行宇宙世界，本片利用顶尖科技来探索极限以外的世界，带您进入不可思议的奇妙世界。本片展现的画面美妙至极，超高速摄像机猎奇下的精细影像令人赞叹，理查德&middot;哈蒙德主持的风格老练而幽默，绝对是BBC的精品纪录片！</p>
<p>
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Richard Hammond&#39;s Invisible Worlds Is A Documentary Series Which Sees Richard Taking A Look Into The Parallel Universe That Lies Beyond The Limits Of The Human Eye. The Series Uses The Latest State-of-the-art Technology Available To Discover The World Beyond These Limits.</p>
<p>
	<br />
	1 Speed Limits 速度极限</p>
<p>
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 理查德哈蒙德详细探讨了隐藏在眨眼之间的世界。人类眨眼大约需要50毫秒时间，同时需要大脑用159毫秒的时间来处理信息。在这短短的时间内，有非凡的事情发生，并且被错过了。但是，如果我们突破了这一速度极限会怎样？借助于最新的高速摄影机，理查德开始了超越眼睛极限之旅，去窥探我们所在星球的秘密：稀薄空气可以打碎岩石，水可以穿越金属，最快速的物体正位于我们双脚下方，以及虽然很多人声明并不存在，却最终被捕捉到的壮观天象。</p>
<p>
	2 Out of Sight<br />
	　　<br />
	　　The human eye is a remarkable piece of precision engineering, but it is also extremely limited. Beyond the narrow range o***ht that makes up the familiar colours of the rainbow is a vast spectrum o***ht, entirely unseen.<br />
	　　<br />
	　　But what if we could see beyond the narrow boundaries of our eyes and peer into this invisible realm?<br />
	　　<br />
	　　Richard Hammond does just that, using groundbreaking new imaging technologies to take the viewer on a breathtaking journey of discovery beyond the visible spectrum, seeing the world, quite literally, in a whole new light.<br />
	　　<br />
	　　From death-defying aerial repairmen in the United States using ultraviolet cameras to seek out an invisible force that lurks unseen on power lines, to German scientists unlocking the secrets of animal locomotion with the world&#39;s most powerful moving x-ray camera, to infrared cameras that can finally reveal the secrets within a humble beehive, he shows how new technologies are letting us see our world anew.</p>
<p>
	3 Off the Scale<br />
	　　The human eye can see extraordinary detail, but the eye of a needle held at arm&#39;s length is pretty much at the limit of our vision. Anything smaller is simply invisible, at least to the naked eye.<br />
	　　But what if we could see this hidden world all around us in greater detail and magnification than ever before? How different would our familiar surroundings then seem?<br />
	　　Richard Hammond explores the astonishing miniature universe all around us, revealing that small is not only beautiful, it can also be very, very powerful.<br />
	　　From seeing the microscopic changes to ice crystals that can trigger an avalanche to watching in horror the invisible aftermath of a sneeze on a commuter train and learning how the surface of an ordinary-looking plant hides an astounding secret that will make walking on the moon safer, Richard harnesses cutting-edge technologies to transport the viewer into a spectacular micro realm.</p>
<p>
	<img src="/uploads/allimg/c120524/133N4OY630-2P44.jpg" /></p>
<p>
	<img src="/uploads/allimg/c120524/133N4O93030-35608.jpg" /></p>
<p>
	<img src="/uploads/allimg/c120524/133N4O9340-42S5.jpg" width="650" /></p>
<p>
	&nbsp;<img src="/uploads/allimg/c120524/133N4O93c0-52P9.jpg" /></p>

<p>
	[下载地址]：<img border="0" src="/uploads/allimg/c120524/133N2Z4FF-102231.jpg" />
<table bgcolor="#0099cc" border="0" cellpadding="10" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				</anchor>ftp://dy444:piaohua@dy444.piaohua.com:412/飘花电影piaohua.com看不见的世界BD中字1024高清CD1.rmvb</td>
		</tr>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				</anchor>ftp://dy444:piaohua@dy444.piaohua.com:412/飘花电影piaohua.com看不见的世界BD中字1024高清CD2.rmvb</td>
		</tr>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				</anchor>ftp://dy444:piaohua@dy444.piaohua.com:421/飘花电影piaohua.com看不见的世界BD中字1024高清CD3.rmvb</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120524/133N4O94130-64J3.jpg{/dede:field}
