{dede:field name='keywords'}绝地战警2/坏小子2/重案梦幻组2B{/dede:field}
{dede:field name='description'}绝地战警2/坏小子2/重案梦幻组2BD中英双字1024高清迅雷下载、免费下载，绝地战警2/坏小子2/重案梦幻组2BD中英双字1024高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}绝地战警2/坏小子2/重案梦幻组2BD中英双字1024高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-03-28{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://e4:e4@xl2.eee4.com:9306/[3E电影站www.eee4.com]绝地战警ⅡDVD中英双字CD1.rmvb" target="_blank{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MO522230-39208.jpg{/dede:field}
