<?php
$z[0]=Array("field","生死狙击/狙击生死线BD中英双字1",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","生死狙击/狙击生死线BD中英双字1024/1280高清迅雷下载、免费下载，生死狙击/狙击生死线BD中英双字1024/1280高清Gvod高清在线播放，剧情介绍等。",73,251);
$z[1][4]['name']="description";
$z[2]=Array("field","生死狙击/狙击生死线BD中英双字1024/1280高清",253,333);
$z[2][4]['name']="title";
$z[3]=Array("field","",335,374);
$z[3][4]['name']="writer";
$z[4]=Array("field","",376,415);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-12-18",417,467);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",469,506);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://eee4.com:1044@vip11.eee4.com:1044/[3E迅雷电影站www.eee4.com]生死狙击CD1.rmvb\" target=\"_blank",508,645);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MP2M130-15Y9.jpg",647,729);
$z[8][4]['name']="litpic";

?>