<?php
$z[0]=Array("field","倾城佳话国英双语BD高清中英双字",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","倾城佳话国英双语BD高清中英双字1280迅雷下载、免费下载，倾城佳话国英双语BD高清中英双字1280Gvod高清在线播放，剧情介绍等。",73,235);
$z[1][4]['name']="description";
$z[2]=Array("field","倾城佳话国英双语BD高清中英双字1280",237,309);
$z[2][4]['name']="title";
$z[3]=Array("field","",311,350);
$z[3][4]['name']="writer";
$z[4]=Array("field","",352,391);
$z[4][4]['name']="source";
$z[5]=Array("field","2012-02-15",393,443);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",445,482);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://dy241:xiaobajie@222.187.221.241:2023/小八戒电影xiaobajie.com倾城佳话国英双语BD高清双字1280.mkv\" target=\"_blank",484,639);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MODG10-13047.jpg",641,723);
$z[8][4]['name']="litpic";

?>