<?php
$z[0]=Array("field","苔藓/青苔[DVD中字]迅雷下载，免",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","苔藓/青苔[DVD中字]迅雷下载、免费下载，苔藓/青苔[DVD中字]Gvod高清在线播放，剧情介绍等。",73,203);
$z[1][4]['name']="description";
$z[2]=Array("field","苔藓/青苔[DVD中字]",205,261);
$z[2][4]['name']="title";
$z[3]=Array("field","",263,302);
$z[3][4]['name']="writer";
$z[4]=Array("field","",304,343);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-10-10",345,395);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",397,434);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://3e:3e@d8.3edyy.com:190/【3E电影院www.eee4.org】青苔.rmvb\" target=_blank>ftftp://3e:3e@d8.3edyy.com:190/【3E电影院www.eee4.org】青苔.rmvb</A></TD></TR></TBODY></TABLE></div><ul class=\"mmlist",436,670);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MP335M0-19262.jpg",672,755);
$z[8][4]['name']="litpic";

?>