{dede:field name='keywords'}怒海争锋：极地远征1280高清迅雷{/dede:field}
{dede:field name='description'}怒海争锋：极地远征1280高清迅雷下载、免费下载，怒海争锋：极地远征1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}怒海争锋：极地远征1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-02-05{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://eee4.com:8077@vip14.eee4.com:8077/怒海争锋/[3E迅雷电影站www.eee4.com]怒海争锋CD1.rmvb" target="_blank{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MP5K5P-15b8.jpg{/dede:field}
