{dede:field name='keywords'}时尚王第20集韩剧迅雷下载，免费{/dede:field}
{dede:field name='description'}时尚王第20集韩剧迅雷下载、免费下载，时尚王第20集韩剧Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}时尚王第20集韩剧{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-23{/dede:field}
{dede:field name='body'}<p>
	<img alt="" height="414" src="http://img.album.pchome.net/02/25/03/37/0283641c356a018f7cc0da14270d7d17.jpg" width="750" /></p>
<p>
	[中文剧名]：时尚王<br />
	[韩文剧名]：&#54056;&#49496;&#50773;<br />
	[导&nbsp;&nbsp; 演]：李明佑（王女自鸣鼓）<br />
	[编&nbsp;&nbsp; 剧]：李善美（甜蜜间谍，新近社员，千年之爱，星梦奇缘）/金基浩（无敌的降落伞要员，甜蜜间谍，新近社员，千年之爱，星梦奇缘）</p>
<p>
	[主&nbsp;&nbsp; 演]：刘亚仁 申世京 权侑莉（少女时代） 李济勋<br />
	[放送机构]：韩国SBS<br />
	[类&nbsp;&nbsp;&nbsp; 型]：SBS月火剧<br />
	[播出时间]：2012年3月19日起每周一、二晚21点55分（北京时间20点55分）<br />
	[集&nbsp;&nbsp;&nbsp; 数]：预计16集<br />
	[接档剧集]：工薪族楚汉志<br />
	[官&nbsp;&nbsp;&nbsp; 网]：<br />
	[剧情简介]：讲述了从韩国东大门市场成功走向世界的设计师们的故事。</p>
<p>
	[下载地址]：&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3082/飘花电影piaohua.com时尚王01.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3082/飘花电影piaohua.com时尚王01.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3082/飘花电影piaohua.com时尚王01.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3082/飘花电影piaohua.com时尚王02.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3082/飘花电影piaohua.com时尚王02.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3082/飘花电影piaohua.com时尚王02.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3082/飘花电影piaohua.com时尚王03.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3082/飘花电影piaohua.com时尚王03.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3082/飘花电影piaohua.com时尚王03.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3088/飘花电影piaohua.com时尚王04.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3088/飘花电影piaohua.com时尚王04.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3088/飘花电影piaohua.com时尚王04.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3133/飘花电影piaohua.com时尚王05.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3133/飘花电影piaohua.com时尚王05.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3133/飘花电影piaohua.com时尚王05.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3140/飘花电影piaohua.com时尚王06.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3140/飘花电影piaohua.com时尚王06.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3140/飘花电影piaohua.com时尚王06.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3194/飘花电影piaohua.com时尚王07.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3194/飘花电影piaohua.com时尚王07.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3194/飘花电影piaohua.com时尚王07.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3198/飘花电影piaohua.com时尚王08.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3198/飘花电影piaohua.com时尚王08.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3198/飘花电影piaohua.com时尚王08.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3242/飘花电影piaohua.com时尚王09.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3242/飘花电影piaohua.com时尚王09.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3242/飘花电影piaohua.com时尚王09.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3242/飘花电影piaohua.com时尚王10.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3242/飘花电影piaohua.com时尚王10.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3242/飘花电影piaohua.com时尚王10.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3281/飘花电影piaohua.com时尚王11.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3281/飘花电影piaohua.com时尚王11.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3281/飘花电影piaohua.com时尚王11.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3290/飘花电影piaohua.com时尚王12.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3290/飘花电影piaohua.com时尚王12.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3290/飘花电影piaohua.com时尚王12.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3371/飘花电影piaohua.com时尚王13.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3371/飘花电影piaohua.com时尚王13.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3371/飘花电影piaohua.com时尚王13.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3371/飘花电影piaohua.com时尚王14.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3371/飘花电影piaohua.com时尚王14.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3371/飘花电影piaohua.com时尚王14.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3371/飘花电影piaohua.com时尚王15.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3371/飘花电影piaohua.com时尚王15.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3371/飘花电影piaohua.com时尚王15.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3377/飘花电影piaohua.com时尚王16.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3377/飘花电影piaohua.com时尚王16.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3377/飘花电影piaohua.com时尚王16.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3423/飘花电影piaohua.com时尚王17.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3423/飘花电影piaohua.com时尚王17.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3423/飘花电影piaohua.com时尚王17.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3432/飘花电影piaohua.com时尚王18.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3432/飘花电影piaohua.com时尚王18.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3432/飘花电影piaohua.com时尚王18.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3474/飘花电影piaohua.com时尚王19.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3474/飘花电影piaohua.com时尚王19.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3474/飘花电影piaohua.com时尚王19.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3482/飘花电影piaohua.com时尚王20.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3482/飘花电影piaohua.com时尚王20.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3482/飘花电影piaohua.com时尚王20.rmvb</a></td>
		</tr>
	</tbody>
</table>
<p>
	&nbsp;</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1522K30-3O04.jpg{/dede:field}
