{dede:field name='keywords'}爱封了/我电你HD高清版2011爱情{/dede:field}
{dede:field name='description'}爱封了/我电你HD高清版2011爱情剧情迅雷下载、免费下载，爱封了/我电你HD高清版2011爱情剧情Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}爱封了/我电你HD高清版2011爱情剧情{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-17{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="/uploads/allimg/c120525/133O0V52910-31YI.jpg" /></p>
<p>
	<img src="/uploads/allimg/c120525/133O0V53930-32S15.jpg" /></p>
<p>
	<img src="/uploads/allimg/c120525/133O0V54c0-332Q7.jpg" /></p>
<p>
	◎译　　名　爱封了/我电你<br />
	◎片　　名　I Phone You <br />
	◎年　　代　2011 <br />
	◎国　　家　中国/德国 <br />
	◎类　　别　爱情 <br />
	◎语　　言　汉语普通话<br />
	◎字　　幕　中字<br />
	◎IMDB评分 6.9/10&nbsp;&nbsp;(27 users)<br />
	◎文件格式　RMVB <br />
	◎视频尺寸　720 x 416 <br />
	◎文件大小　1CD 371MB <br />
	◎片　　长　95 mins <br />
	◎导　　演　唐丹&nbsp; &nbsp;Dan Tang<br />
	◎主　　演　江一燕 Yiyan Jiang&nbsp;&nbsp;....Ling Ling<br />
	弗罗里安&middot;卢卡斯 Florian Lukas&nbsp;&nbsp;....Marco<br />
	何冰 Bing He&nbsp;&nbsp;....Boss of Flower Shop<br />
	Nicole Ernst&nbsp;&nbsp;....Immigration Officer<br />
	Annette Frier&nbsp;&nbsp;....Waitress Susi<br />
	Marie Gruber&nbsp;&nbsp;....Homeless Woman<br />
	Heike Hanold<br />
	Aaron Hong Le&nbsp;&nbsp;....Vong<br />
	缇诺&middot;麦威斯 Tino Mewes&nbsp;&nbsp;....Student<br />
	Yung Ngo&nbsp;&nbsp;....Bao<br />
	Fritz Roth&nbsp;&nbsp;....Policeman<br />
	王海珍 Haizhen Wang&nbsp;&nbsp;....Mrs. Guanhao (as Wang Hai Zhen)<br />
	吴大维 David Wu&nbsp;&nbsp;....Yu Guanhao (as Wu Da Wei)<br />
	Alexander Yassin&nbsp;&nbsp;....Alexander<br />
	邓家佳 Jiajia Deng<br />
	<br />
	<br />
	◎简　　介<br />
	<br />
	&nbsp; &nbsp;&nbsp; &nbsp;&nbsp;&nbsp;电影讲述了一名性格直爽的重庆女孩玲儿因偶然相识爱上了一个生活在德国的男人，虽然远隔重洋但始终保持电话联络。随后，玲儿用在花店打工的薪水只身前往德国找寻属于自己的爱情。女孩在冲破迷惘固执看清爱人的真实嘴脸、了解到自己竟无意间成为第三者后，毅然做出了最终选择。<br />
	<br />
	◎电影截图<br />
	<br />
	<br />
	&nbsp;</p>
<p>
	<img src="/uploads/allimg/c120525/133O0V56040-34U08.jpg" style="width: 600px; height: 323px" /></p>
<p>
	<img src="/uploads/allimg/c120525/133O0V5E10-35R24.jpg" style="width: 600px; height: 323px" /></p>
<p>
	<img src="/uploads/allimg/c120525/133O0V5MF-3D962.jpg" style="width: 600px; height: 323px" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:1832/飘花电影piaohua.com我电你DVDscr国语中字.rmvb</td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:3439/飘花电影piaohua.com我电你HD高清版.rmvb</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O0V5V30-3I248.jpg{/dede:field}
