{dede:field name='keywords'}别惹蚂蚁BD1280高清迅雷下载，免{/dede:field}
{dede:field name='description'}别惹蚂蚁BD1280高清迅雷下载、免费下载，别惹蚂蚁BD1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}别惹蚂蚁BD1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-04-21{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://www.luangh.com/up/files/66/The.Ant.2006.png" style="width: 500px; height: 657px" /></p>
<p>
	◎片　　名　 The Ant Bully<br />
	◎译　　名　别惹蚂蚁/蚂蚁不好惹/蚂蚁欺负者/蚂蚁恶少/联合缩小兵/小蚁霸<br />
	◎年　　代　 2006<br />
	◎国　　家　 美国<br />
	◎类　　别　 动画/冒险/喜剧/家庭/奇幻<br />
	◎语　　言　 英语<br />
	◎字　　幕　 中字<br />
	◎IMDB评分　6.0/10 from 13,666 user<br />
	◎IMDB链接　<a href="http://www.imdb.com/title/tt0429589" target="_blank">http://www.imdb.com/title/tt0429589</a><br />
	◎片　　长　01h:29m:03s &nbsp;<br />
	◎导　　演　 约翰&middot;戴维斯 John A. Davis　　　<br />
	◎主　　演　Jake Szymanski .... Nicky<br />
	　　　　　　S. Scott Bullock .... Glow worm<br />
	　　　　　　尼古拉斯&middot;凯奇 Nicolas Cage .... Zoc (voice)<br />
	　　　　　　拉里&middot;塞德尔 Larry Cedar .... Ant #8 (voice)<br />
	　　　　　　艾伦&middot;卡明 Alan Cumming .... Fugax (voice)<br />
	　　　　　　保罗&middot;吉亚玛提 Paul Giamatti .... Stan (voice)<br />
	　　　　　　Myles Jeffrey .... Steve (voice)<br />
	　　　　　　David Kaye .... Ant (voice)<br />
	　　　　　　瑞加纳&middot;金 Regina King .... Kreela (voice)<br />
	　　　　　　Allison Mack .... Tiffany Nickle (voice)<br />
	　　　　　　Ken Mitchroney .... Guard ant<br />
	　　　　　　Ricardo Montalban .... Head of Council (voice)<br />
	　　　　　　切里&middot;奥特莱 Cheri Oteri .... Doreen Nickle (voice)<br />
	　　　　　　朱莉娅&middot;罗伯茨 Julia Roberts .... Hova (voice)<br />
	　　　　　　Clive Robertson .... Wizard Ant (voice)<br />
	　　　　　　<br />
	◎简　　介<br />
	<br />
	&nbsp; &nbsp; &nbsp;频繁的搬家对家里小孩子的成长往往产生巨大的影响，这个故事中的主人公卢卡斯&middot;尼克尔(扎克&middot;泰勒)便是一个此类的典型。刚刚十岁的他虽说具备了所有男孩的淘气天性，但生活环境的市场更换使得他根本无法有什么好朋友可以相伴玩耍、成长。在跟随父母搬到达一个新环境后，因为没有新朋友，经常遭同学欺负，只得整日郁闷在家里独自找乐。这天，后院的小蚂蚁窝成了小卢卡斯玩耍的目标，用手中火力强劲的水枪不停地袭击着眼前的&ldquo;蚂蚁王国&rdquo;，谁知就此惹上了大麻烦。蚂蚁王国果真震怒，蚁后(梅丽尔&middot;斯特里普)亲自发号施令，迅速解决水患，并严厉惩处水患制造者。<br />
	&nbsp; &nbsp;蚂蚁王国的议院最终决定派法力强大的蚂蚁巫师佐克(尼古拉斯&middot;凯奇)亲自出马，将人类小孩卢卡斯变化成蚂蚁一般大小，然后抓回蚂蚁王国听接受审判。结果，被微缩成蚂蚁大小的小卢卡斯被罚做了蚂蚁世界的苦工，通过和蚂蚁一起生活，结识了许多要好的蚂蚁朋友。另外，好心的蚂蚁护士(茱莉娅&middot;罗伯茨)给予了孤独的小卢卡斯更多的悉心关怀，让卢卡斯明白了很多人生道理，小卢卡斯甚至产生了做一辈子快乐蚂蚁的念头&hellip;&hellip;</p>
<p>
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120421/06/62564813201204210623532786571362184_000.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120421/06/62564813201204210623532786571362184_001.jpg" style="width: 720px; height: 405px" /><br />
	<br />
	&nbsp;</p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.net/" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy125:piaohua@dy125.piaohua.com:7863/飘花电影piaohua.com别惹蚂蚁BD中字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:7863/飘花电影piaohua.com别惹蚂蚁BD中字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15194560-51091.jpg{/dede:field}
