{dede:field name='keywords'}凶鬼恶灵/邪恶力量第七季23美剧{/dede:field}
{dede:field name='description'}凶鬼恶灵/邪恶力量第七季23美剧迅雷下载、免费下载，凶鬼恶灵/邪恶力量第七季23美剧Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}凶鬼恶灵/邪恶力量第七季23美剧{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-20{/dede:field}
{dede:field name='body'}<p>
	<img alt="" height="690" src="http://img.album.pchome.net/54/83/85/75/30d468916c2a9aedc39ab57123611d4d.jpg" width="472" /></p>
<p>
	【译 　名】： 邪恶力量|超自然档案|凶鬼恶灵<br />
	【原 　名】： Supernatural<br />
	【年 　代】： 2005-2011<br />
	【国 　家】： 美国<br />
	【类 　别】： 动作|冒险|剧情片|恐怖/灵异|科幻<br />
	【语 　言】： 英语<br />
	【首 　播】： 2011年9月23日（周五晚9点）<br />
	【电 视 台】： The CW ( USA)<br />
	【IMDB评分】： 8.9/10 (19,185 人评价)<br />
	【集 　数】： 预计 22 集<br />
	【片 　长】： 平均 42 分钟<br />
	【导 　演】：&bull; Philip Sgriccia ... (21集, 2006-2011)<br />
	　　　　　　　 &bull; Robert Singer ... (20集, 2005-2011)<br />
	　　　　　　　 &bull; Kim Manners ... (16集, 2005-2008)<br />
	　　　　　　　 &bull; Charles Beeson ... (12集, 2007-2011)<br />
	　　　　　　　 &bull; Mike Rohl ... (8集, 2006-2011)<br />
	　　　　　　　 &bull; Steve Boyum ... (7集, 2006-2010)<br />
	　　　　　　　 &bull; J. Miller Tobin ... (4集, 2007-2009)<br />
	　　　　　　　 &bull; James L. Conway ... (4集, 2009-2010)<br />
	　　　　　　　 &bull; John Showalter ... (4集, 2010-2011)<br />
	　　　　　　　 &bull; Guy Norman Bee ... (3集, 2005-2011)<br />
	　　　　　　　 &bull; Eric Kripke ... (3集, 2007-2011)<br />
	　　　　　　　 &bull; Peter Ellis ... (2集, 2005-2006)<br />
	　　　　　　　 &bull; David Nutter ... (2集, 2005)<br />
	【编 　剧】：&bull; Eric Kripke ... (126集, 2005-2011)<br />
	　　　　　　　 &bull; Sera Gamble ... (24集, 2005-2011)<br />
	　　　　　　　 &bull; Ben Edlund ... (16集, 2006-2011)<br />
	　　　　　　　 &bull; Jeremy Carver ... (12集, 2007-2010)<br />
	　　　　　　　 &bull; Andrew Dabb ... (11集, 2008-2011)<br />
	　　　　　　　 &bull; Daniel Loflin ... (11集, 2008-2011)<br />
	　　　　　　　 &bull; John Shiban ... (9集, 2005-2007)<br />
	　　　　　　　 &bull; Raelle Tucker ... (8集, 2005-2007)<br />
	　　　　　　　 &bull; Cathryn Humphris ... (7集, 2006-2009)<br />
	　　　　　　　 &bull; Julie Siege ... (6集, 2008-2010)<br />
	　　　　　　　 &bull; Adam Glass ... (4集, 2010-2011)<br />
	　　　　　　　 &bull; Nancy Weiner ... (3集, 2009-2010)<br />
	　　　　　　　 &bull; Eric C. Charmelo ... (3集, 2010-2011)<br />
	　　　　　　　 &bull; Brett Matthews ... (3集, 2010-2011)<br />
	　　　　　　　 &bull; Nicole Snyder ... (3集, 2010-2011)<br />
	　　　　　　　 &bull; Richard Hatem ... (2集, 2005)<br />
	　　　　　　　 &bull; Terri Hughes ... (2集, 2005)<br />
	　　　　　　　 &bull; Ron Milbauer ... (2集, 2005)<br />
	　　　　　　　 &bull; Matt Witten ... (2集, 2006-2007)<br />
	　　　　　　　 &bull; Robert Singer ... (2集, 2007-2010)<br />
	　　　　　　　 &bull; Jenny Klein ... (2集, 2009-2010)<br />
	　　　　　　　 &bull; David Reed ... (2集, 2010)<br />
	【演 　员】：&bull; Jared Padalecki 饰演 Sam Winchester (126集, 2005-2011)<br />
	　　　　　　　 &bull; Jensen Ackles 饰演 Dean Winchester (126集, 2005-2011)<br />
	　　　　　　　 &bull; Jim Beaver 饰演 Bobby Singer (42集, 2006-2011)<br />
	　　　　　　　 &bull; Misha Collins 饰演 Castiel (40集, 2008-2011)</p>
<p>
	【简 　介】：</p>
<p>
	《邪恶力量》（Supernatural），又译《凶鬼恶灵》、《狙魔人》、《超自然档案》、《神秘力量》，是由美国WB电视台（现更名为CW电视台）播出的讲述灵异超自然现象的电视剧。在加拿大拍摄。该剧主要是在讲述两兄弟山姆&middot;温彻斯特和迪恩&middot;温彻斯特开着1967年的黑色雪佛兰&ldquo;羚羊&rdquo; 穿梭在美国各处调查超自然或不可思议的事件并与之战斗的故事，大多来自于美国的都市传说和民间传说。</p>
<p>
	&nbsp;</p>
<p>
	[下载地址]： &nbsp;<img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" /></p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2009/飘花电影piaohua.com邪恶力量第七季01.rmvb">&nbsp;ftp://dy44:piaohua@dy44.piaohua.com:2009/飘花电影piaohua.com邪恶力量第七季01.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2009/飘花电影piaohua.com邪恶力量第七季02.rmvb">&nbsp;ftp://dy44:piaohua@dy44.piaohua.com:2009/飘花电影piaohua.com邪恶力量第七季02.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2009/飘花电影piaohua.com邪恶力量第七季03.rmvb">&nbsp;ftp://dy44:piaohua@dy44.piaohua.com:2009/飘花电影piaohua.com邪恶力量第七季03.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2009/飘花电影piaohua.com邪恶力量第七季04.rmvb">&nbsp;ftp://dy44:piaohua@dy44.piaohua.com:2009/飘花电影piaohua.com邪恶力量第七季04.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2009/飘花电影piaohua.com邪恶力量第七季05.rmvb">&nbsp;ftp://dy44:piaohua@dy44.piaohua.com:2009/飘花电影piaohua.com邪恶力量第七季05.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2009/飘花电影piaohua.com邪恶力量第七季06.rmvb">&nbsp;ftp://dy44:piaohua@dy44.piaohua.com:2009/飘花电影piaohua.com邪恶力量第七季06.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2009/飘花电影piaohua.com邪恶力量第七季07.rmvb">&nbsp;ftp://dy44:piaohua@dy44.piaohua.com:2009/飘花电影piaohua.com邪恶力量第七季07.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2124/飘花电影piaohua.com邪恶力量第七季08.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:2124/飘花电影piaohua.com邪恶力量第七季08.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2124/飘花电影piaohua.com邪恶力量第七季08.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2124/飘花电影piaohua.com邪恶力量第七季09.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:2124/飘花电影piaohua.com邪恶力量第七季09.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2124/飘花电影piaohua.com邪恶力量第七季09.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2560/飘花电影piaohua.com邪恶力量第七季10.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:2560/飘花电影piaohua.com邪恶力量第七季10.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2560/飘花电影piaohua.com邪恶力量第七季10.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2560/飘花电影piaohua.com邪恶力量第七季11.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:2560/飘花电影piaohua.com邪恶力量第七季11.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2560/飘花电影piaohua.com邪恶力量第七季11.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2625/飘花电影piaohua.com邪恶力量第七季12.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:2625/飘花电影piaohua.com邪恶力量第七季12.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2625/飘花电影piaohua.com邪恶力量第七季12.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2755/飘花电影piaohua.com邪恶力量第七季13.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:2755/飘花电影piaohua.com邪恶力量第七季13.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2755/飘花电影piaohua.com邪恶力量第七季13.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2800/飘花电影piaohua.com邪恶力量第七季14.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:2800/飘花电影piaohua.com邪恶力量第七季14.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2800/飘花电影piaohua.com邪恶力量第七季14.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2844/飘花电影piaohua.com邪恶力量第七季15.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:2844/飘花电影piaohua.com邪恶力量第七季15.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2844/飘花电影piaohua.com邪恶力量第七季15.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3034/飘花电影piaohua.com邪恶力量第七季16.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3034/飘花电影piaohua.com邪恶力量第七季16.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3034/飘花电影piaohua.com邪恶力量第七季16.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3068/飘花电影piaohua.com邪恶力量第七季17.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3068/飘花电影piaohua.com邪恶力量第七季17.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3068/飘花电影piaohua.com邪恶力量第七季17.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3115/飘花电影piaohua.com邪恶力量第七季18.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3115/飘花电影piaohua.com邪恶力量第七季18.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3115/飘花电影piaohua.com邪恶力量第七季18.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3267/飘花电影piaohua.com邪恶力量第七季19.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3267/飘花电影piaohua.com邪恶力量第七季19.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3267/飘花电影piaohua.com邪恶力量第七季19.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3319/飘花电影piaohua.com邪恶力量第七季20.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3319/飘花电影piaohua.com邪恶力量第七季20.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3319/飘花电影piaohua.com邪恶力量第七季20.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3355/飘花电影piaohua.com邪恶力量第七季21.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3355/飘花电影piaohua.com邪恶力量第七季21.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3355/飘花电影piaohua.com邪恶力量第七季21.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3406/飘花电影piaohua.com邪恶力量第七季22.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3406/飘花电影piaohua.com邪恶力量第七季22.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3406/飘花电影piaohua.com邪恶力量第七季22.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3464/飘花电影piaohua.com邪恶力量第七季23.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3464/飘花电影piaohua.com邪恶力量第七季23.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3464/飘花电影piaohua.com邪恶力量第七季23.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1A63230-55945.jpg{/dede:field}
