<?php
$z[0]=Array("field","星河战队2:联邦英雄BD中英双字10",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","星河战队2:联邦英雄BD中英双字1024/1280高清迅雷下载、免费下载，星河战队2:联邦英雄BD中英双字1024/1280高清Gvod高清在线播放，剧情介绍等。",73,249);
$z[1][4]['name']="description";
$z[2]=Array("field","星河战队2:联邦英雄BD中英双字1024/1280高清",251,330);
$z[2][4]['name']="title";
$z[3]=Array("field","",332,371);
$z[3][4]['name']="writer";
$z[4]=Array("field","",373,412);
$z[4][4]['name']="source";
$z[5]=Array("field","2012-01-07",414,464);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",466,503);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://3e:3e@d8.3edyy.com:162/【3E电影院www.eee4.cc】星河战队2[BD中英双字1024x576高清版].rmvb\" target=\"_blank",505,652);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MOV3040-15244.jpg",654,737);
$z[8][4]['name']="litpic";

?>