<?php
$z[0]=Array("field","天堂执法者,第二季更新23集2011",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","天堂执法者 第二季更新23集2011主打美剧迅雷下载、免费下载，天堂执法者 第二季更新23集2011主打美剧Gvod高清在线播放，剧情介绍等。",72,240);
$z[1][4]['name']="description";
$z[2]=Array("field","天堂执法者 第二季更新23集2011主打美剧",242,317);
$z[2][4]['name']="title";
$z[3]=Array("field","",319,358);
$z[3][4]['name']="writer";
$z[4]=Array("field","",360,399);
$z[4][4]['name']="source";
$z[5]=Array("field","2012-05-18",401,451);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",453,490);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://dy44:piaohua@dy44.piaohua.com:1759/飘花电影piaohua.com天堂执法者第二季01集[中英双字].rmvb",492,626);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MP94GP-24433.jpg",628,710);
$z[8][4]['name']="litpic";

?>