{dede:field name='keywords'}新独臂刀1280*720迅雷下载，免费{/dede:field}
{dede:field name='description'}新独臂刀1280*720迅雷下载、免费下载，新独臂刀1280*720Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}新独臂刀1280*720{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-08-08{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="/uploads/allimg/c120525/133O0352T0-221122.jpg" /><img alt="" src="/uploads/allimg/c120525/133O0352a50-23M54.jpg" /></p>
<p>
	◎片　　名　新独臂刀<br />
	◎译　　名　New One-Armed Swordsman<br />
	◎年　　代　1971<br />
	◎国　　家　中国香港<br />
	◎类　　别　动作<br />
	◎语　　言　国语<br />
	◎字　　幕　无<br />
	◎文件格式　RVMB<br />
	◎视频尺寸　1280 x 720<br />
	◎片　　长　01:28:25.467<br />
	◎导　　演　张彻Cheh Chang<br />
	◎编　　剧　倪匡Kuang Ni<br />
	◎主　　演　姜大卫David Chiang<br />
	　　　　　　狄龙Lung<br />
	　　　　　　谷峰<br />
	　　　　　　郑康业Hong-Yip Cheng<br />
	　　　　　　冯克安Hak On Fung<br />
	　　　　　<br />
	◎简　　介<br />
	　　&nbsp;&nbsp; 远声镖局怀疑&ldquo;鸳鸯双刀&rdquo;雷力（姜大卫）劫了他们的镖，双方争斗起来，黑道人物龙异之</p>
<p>
	突然出现，帮助远声嫖局打败了雷力。雷力自断右臂，到一家小饭店当帮工，退出江湖。虎威山庄</p>
<p>
	的头目靳奋和黑道高手金翼常到这家饭店吃饭，虎威山庄由龙异之控制。一天，他们调戏饭店的邻</p>
<p>
	居巴铁匠的女儿巴蕉。雷力想救她，但因独臂，有心无力。来吃饭的江湖豪侠双刀封俊杰（狄龙）</p>
<p>
	出手救下巴蕉。当晚，巴蕉把自家祖传的宝刀送给雷力，回家途中，巴蕉遭遇靳奋和金翼前来劫她</p>
<p>
	上山。雷力听见巴蕉呼救，持刀相救，封俊杰再次出手救了巴蕉。雷力与封俊杰结为朋友。靳奋和</p>
<p>
	金翼二人回到山庄报告，请出了龙异之。封俊杰不听雷力的劝告，接下龙异之的战书，结果死在龙</p>
<p>
	异之的三节棍下。雷力苦练武功，练成一手三刀，终于杀死龙异之，与巴蕉喜结良缘。</p>

<p>
	<br />
	◎截　　图：</p>
<p>
	&nbsp;<img alt="" src="/uploads/allimg/c120525/133O03530620-2415N.jpg" /><img alt="" src="/uploads/allimg/c120525/133O035320-2554J.jpg" /><img alt="" src="/uploads/allimg/c120525/133O03532W0-261O0.jpg" /><img alt="" src="/uploads/allimg/c120525/133O03533Z-2GJ0.jpg" /><img alt="" src="/uploads/allimg/c120525/133O03534T0-2V5Z.jpg" /></p>
<p>
	[新独臂刀下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="/uploads/allimg/c120524/133N2Z4FF-102231.jpg" />&nbsp;&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="word-break: break-all; line-height: 18px" width="100%">
				ftp://dy195:piaohua@dy195.piaohua.com:1015/飘花电影下载站www.xiaozhizhu.net新独臂刀[国语无字].rmvb</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O03535F-292631.jpg{/dede:field}
