<?php
$z[0]=Array("field","壮志凌云/捍卫战士/比翼神[BD中",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","壮志凌云/捍卫战士/比翼神[BD中英双字1024x576高清版无水印]迅雷下载、免费下载，壮志凌云/捍卫战士/比翼神[BD中英双字1024x576高清版无水印]Gvod高清在线播放，剧情介绍等。",72,278);
$z[1][4]['name']="description";
$z[2]=Array("field","壮志凌云/捍卫战士/比翼神[BD中英双字1024x576高清版无水印]",280,374);
$z[2][4]['name']="title";
$z[3]=Array("field","",376,415);
$z[3][4]['name']="writer";
$z[4]=Array("field","",417,456);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-01-07",458,508);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",510,547);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://3e:3e@www2.3edyy.com:376/【3E电影院www.3edyy.com】壮志凌云BD中英双字1024x576高清版无水印.rmvb\" target=\"_blank",549,703);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MQ331550-12245.jpg",705,789);
$z[8][4]['name']="litpic";

?>