{dede:field name='keywords'}壮志凌云/捍卫战士/比翼神[BD中{/dede:field}
{dede:field name='description'}壮志凌云/捍卫战士/比翼神[BD中英双字1024x576高清版无水印]迅雷下载、免费下载，壮志凌云/捍卫战士/比翼神[BD中英双字1024x576高清版无水印]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}壮志凌云/捍卫战士/比翼神[BD中英双字1024x576高清版无水印]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2010-01-07{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://3e:3e@www2.3edyy.com:376/【3E电影院www.3edyy.com】壮志凌云BD中英双字1024x576高清版无水印.rmvb" target="_blank{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MQ331550-12245.jpg{/dede:field}
