<?php
$z[0]=Array("field","91神雕侠侣/九一神雕侠侣[DVD国",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","91神雕侠侣/九一神雕侠侣[DVD国语＋粤语中字]迅雷下载、免费下载，91神雕侠侣/九一神雕侠侣[DVD国语＋粤语中字]Gvod高清在线播放，剧情介绍等。",72,250);
$z[1][4]['name']="description";
$z[2]=Array("field","91神雕侠侣/九一神雕侠侣[DVD国语＋粤语中字]",252,332);
$z[2][4]['name']="title";
$z[3]=Array("field","",334,373);
$z[3][4]['name']="writer";
$z[4]=Array("field","",375,414);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-01-24",416,466);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",468,505);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://3e:3e@www2.3edyy.com:3876/【3E电影院www.3edyy.com】91神雕侠侣DVD国语中字.rmvb\" target=_blank>ftftp://3e:3e@www2.3edyy.com:3876/【3E电影院www.3edyy.com】91神雕侠侣DVD国语中字.rmvb</A></TD></TR></TBODY></TABLE>粤语：<BR>\r\n<TABLE style=\"BORDER-RIGHT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; BORDER-BOTTOM: #cccccc 1px dotted\" cellSpacing=0 cellPadding=6 width=\"95%\" align=center border=0>\r\n<TBODY>\r\n<TR>\r\n<TD style=\"WORD-WRAP: break-word\" bgColor=#fdfddf><A href=\"ftftp://3e:3e@www2.3edyy.com:3876/【3E电影院www.3edyy.com】91神雕侠侣DVD粤语中字.rmvb\" target=_blank>ftftp://3e:3e@www2.3edyy.com:3876/【3E电影院www.3edyy.com】91神雕侠侣DVD粤语中字.rmvb</A></TD></TR></TBODY></TABLE></div><ul class=\"mmlist",507,1318);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MQ333R0-55402.jpg",1320,1403);
$z[8][4]['name']="litpic";

?>