{dede:field name='keywords'}玩具总动员之夏威夷假期高清BD12{/dede:field}
{dede:field name='description'}玩具总动员之夏威夷假期高清BD1280迅雷下载、免费下载，玩具总动员之夏威夷假期高清BD1280Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}玩具总动员之夏威夷假期高清BD1280{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-01-29{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img165.poco.cn/mypoco/myphoto/20120129/14/17870980201201291458071402749169225_000.jpg" style="width: 422px; height: 296px" /></p>
<p>
	◎译　　名　玩具总动员之夏威夷假期<br />
	◎片　　名　Toy Story Hawaiian Vacation&nbsp; &nbsp;<br />
	◎年　　代　2011<br />
	◎国　　家　美国<br />
	◎类　　别　动画/喜剧/短片<br />
	◎语　　言　英语<br />
	◎字　　幕　N/A<br />
	◎IMDB评分 7.8/10 （382 votes）<br />
	◎IMDB链接 <a href="http://www.imdb.com/title/tt1850374/" target="_blank">http://www.imdb.com/title/tt1850374/</a><br />
	◎视频尺寸　1280 x 720<br />
	◎文件大小　70 MiB<br />
	◎片　　长　6 Mins<br />
	◎导　　演　嘉里&middot;瑞德斯托姆 Gary Rydstrom<br />
	◎主　　演　<br />
	蒂姆&middot;艾伦 Tim Allen ....Buzz Lightyear (voice)<br />
	裘蒂&middot;班森 Jodi Benson ....Barbie (voice)<br />
	汤姆&middot;汉克斯 Tom Hanks ....Woody (voice)<br />
	布莱克&middot;克拉克 Blake Clark ....Slinky Dog (voice)<br />
	琼&middot;库萨克 Joan Cusack ....Jessie (voice)<br />
	提摩西&middot;道尔顿 Timothy Dalton ....Mr. Pricklepants (voice)<br />
	杰夫&middot;格尔林 Jeff Garlin ....Buttercup (voice)<br />
	Estelle Harris ....Mrs. Potato Head (voice)<br />
	邦尼&middot;亨特 Bonnie Hunt ....Dolly (voice)<br />
	迈克尔&middot;基顿 Michael Keaton ....Ken (voice)<br />
	巴德&middot;乐凯 Bud Luckey ....Chuckles (voice)<br />
	约翰&middot;拉岑贝格 John Ratzenberger ....Hamm (voice)<br />
	唐&middot;里克斯 Don Rickles ....Mr. Potato Head (voice)<br />
	Kristen Schaal ....Trixie (voice)<br />
	华莱士&middot;肖恩 Wallace Shawn ....Rex (voice)<br />
	弗兰克&middot;维尔克 Frank Welker ....Bullseye (voice) (uncredited)<br />
	<br />
	<br />
	影片介绍<br />
	<br />
	　　故事讲述了玩具们的新主人邦妮（Bonnie）要和父母去夏威夷度假，这可乐坏了芭比（Barbie）和肯（Ken），这可是他们第一次去热带度假！然而时运不济，他们被意外的拉下了，于是巴斯光年、伍迪和其他的玩具决定在邦妮的房间里打造一个夏威夷，来满足他们的愿望。<br />
	<br />
	<br />
	<br />
	幕后制作<br />
	<br />
	　　《玩具总动员3》大获成功后，皮克斯决定开发一系列的《玩具总动员》小短片来让观众继续看到那些熟悉的角色。《夏威夷假期》是《玩具总动员》系列短片（Toy Story Toons）的首部作品，将在皮克斯2011年年度大戏《赛车总动员2》（Cars 2）前加映。而《玩具总动员》系列短片的第二部作品也已经早早定下了推出日期，第二部短片将在2011年底迪士尼的《木偶》（The Muppets）前加映。<br />
	&nbsp;</p>
<p>
	<br />
	&nbsp;</p>
<p>
	<img alt="" border="0" src="http://img165.poco.cn/mypoco/myphoto/20120129/14/17870980201201291458071402749169225_002.jpg" /></p>
<p>
	<img alt="" border="0" src="http://img165.poco.cn/mypoco/myphoto/20120129/14/17870980201201291458071402749169225_001.jpg" /></p>

<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="&#13;&#10;ftp://dy241:xiaobajie@dy241.piaohua.com:2053/小八戒电影xiaobajie.com玩具总动员之夏威夷假期双字高清BD1280.rmvb">ftp://dy241:xiaobajie@dy241.piaohua.com:2053/小八戒电影xiaobajie.com玩具总动员之夏威夷假期双字高清BD1280.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1B21940-4I20.jpg{/dede:field}
