<?php
$z[0]=Array("field","蜜蜂总动员/蜜蜂电影[DVD中英双",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","蜜蜂总动员/蜜蜂电影[DVD中英双字1024/1280高清版无水印]迅雷下载、免费下载，蜜蜂总动员/蜜蜂电影[DVD中英双字1024/1280高清版无水印]Gvod高清在线播放，剧情介绍等。",72,272);
$z[1][4]['name']="description";
$z[2]=Array("field","蜜蜂总动员/蜜蜂电影[DVD中英双字1024/1280高清版无水印]",274,365);
$z[2][4]['name']="title";
$z[3]=Array("field","",367,406);
$z[3][4]['name']="writer";
$z[4]=Array("field","",408,447);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-08-23",449,499);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",501,538);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://3e:3e@www2.eee4.com:604/[3E电影站www.eee4.com]蜜蜂总动员DVD中英双字1280x720高清版无水印.rmvb\" target=\"_blank",540,693);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MQ1CK0-31441.jpg",695,777);
$z[8][4]['name']="litpic";

?>