{dede:field name='keywords'}非法入侵BD高清迅雷下载，免费下{/dede:field}
{dede:field name='description'}非法入侵BD高清迅雷下载、免费下载，非法入侵BD高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}非法入侵BD高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-10-22{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img165.poco.cn/mypoco/myphoto/20111019/11/62564813201110191207331660344890471_000.jpg" style="width: 700px; height: 1014px" /></p>
<p>
	◎译　　名　侵害/非法入侵<br />
	◎片　　名　Trespass<br />
	◎年　　代　2011<br />
	◎国　　家　美国<br />
	◎类　　别　犯罪/剧情/惊悚<br />
	◎语　　言　英语<br />
	◎字　　幕　中英<br />
	◎IMDB评分 &nbsp;6.4/10<br />
	◎IMDB链接 &nbsp;<a href="http://www.imdb.com/title/tt1674784/" target="_blank">http://www.imdb.com/title/tt1674784/</a><br />
	◎片　　长　91 Mins<br />
	◎导　　演　乔&middot;舒马赫 Joel Schumacher<br />
	◎主　　演　<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;尼古拉斯&middot;凯奇 Nicolas Cage ....Kyle<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 凯姆&middot;吉甘戴 Cam Gigandet ....Jonah Collins<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 妮可&middot;基德曼 Nicole Kidman ....Sarah<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 丽亚娜&middot;莱伯拉托 Liana Liberato ....Avery<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 尼可&middot;托托雷拉 Nico Tortorella ....Jake<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 乔丹娜&middot;斯皮罗 Jordana Spiro<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 达什&middot;米霍克 Dash Mihok<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 本&middot;门德尔森 Ben Mendelsohn<br />
	<br />
	影片介绍<br />
	<br />
	　　一对苦命夫妇被绑架做人质，在筹集赎金的过程中渐渐发现陷入一场阴谋和骗局中<br />
	　　富庶的米勒家被四个冷血罪犯强行闯入，目标是米勒家的财富。夫妇盖尔和莎拉及女儿艾弗莉被困屋中，双方人马各怀鬼胎，不肯妥协。<br />
	<br />
	　　屋中的7人关系错中复杂，当中更牵涉到莎拉和贼人祖的暧昧关系。一场金钱斗争，人人皆陷入背叛、欺骗、诱惑和诡计的漩涡中。盖尔、莎拉和艾弗莉一家了生存、更为了家庭，冒着极大危险作出最后反击</p>
<p>
	<img alt="" src="http://img165.poco.cn/mypoco/myphoto/20111021/18/62564813201110211901124083311428330_003.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img165.poco.cn/mypoco/myphoto/20111021/18/62564813201110211901124083311428330_002.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img165.poco.cn/mypoco/myphoto/20111021/18/62564813201110211901124083311428330_001.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img165.poco.cn/mypoco/myphoto/20111021/18/62564813201110211901124083311428330_000.jpg" style="width: 720px; height: 405px" /></p>

<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="&#13;&#10;ftp://dy125:piaohua@dy125.piaohua.com:7060/飘花电影piaohua.com非法入侵BD中英双字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:7060/飘花电影piaohua.com非法入侵BD中英双字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O16031460-24257.jpg{/dede:field}
