{dede:field name='keywords'}我爱/爱你日韩剧12迅雷下载，免{/dede:field}
{dede:field name='description'}我爱/爱你日韩剧12迅雷下载、免费下载，我爱/爱你日韩剧12Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}我爱/爱你日韩剧12{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-25{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img.album.pchome.net/02/25/03/37/29de390fea3907c1c3d4e5ed59bbfe8d.jpg" /></p>
<p>
	<img src="http://img.funshion.com/attachment/new_images/2011/05-16/17888460_1305515338_209.jpg" width="650" /></p>
<p>
	【中文剧名】：爱你<br />
	【英文剧名】：Love You<br />
	【韩文剧名】：&#44536;&#45824;&#47484; &#49324;&#46993;&#54633;&#45768;&#45796;<br />
	【电视台】：SBS Plus 月火剧（周一周二剧）<br />
	【首 播】：2012年4月16日<br />
	【回 数】：预计16回<br />
	【导 演】：尹柳海 （三姐妹、八月下的雪）<br />
	【编 剧】：金明浩<br />
	【主 演】：金亨俊 李顺才 金允瑞<br />
	【语 言】：韩国语<br />
	【字 幕】：中文<br />
	【格 式】：RMVB/HR-HDTV<br />
	【简 介】：改编自韩国漫画家江草的漫画，被称老年版《真爱至上》。爱情并不是年轻人的专利，片中四位爷爷奶奶温馨又逗趣的演出打破了人们对于黄昏恋的偏见。</p>
<p>
	<br />
	点评： 感人至深! 有人与你牵手走完今生是件幸福无比的事!--</p>
<p>
	执子之手，与子偕老，相濡以沫，温馨动人--</p>
<p>
	中老年必看!青少年也可以看,早受教育!--</p>
<p>
	剧情：改编自韩国漫画家江草的漫画作品，被称老年版《真爱至上》，舞台剧版也曾大受欢迎。爱情并不是年轻人的专利，片中四位爷爷奶奶温馨又逗趣的演出打破了人们对于黄昏恋的偏见。</p>
<p>
	花絮： 老年版《真爱至上》</p>
<p>
	　　影片改编自韩国人气漫画家江草的同名作。2007年该漫画率先在网络上连载，随后实体书一至三册先后出版，截至2008年10月，该系列图书销售突破15万册，并获图书文化大奖。根据漫画改编的舞台剧于2008年4月至2010年在17个城市公演，上座率突破90%，单&ldquo;大学路&rdquo;公演一次就创下15万人次的上座纪录。舞台剧主演江泰基斩获戏剧主演奖，该剧更翻译成日文字幕公演，反应热烈。如此一部经典之作拍成电影自然势在必行。于是，导演秋昌民请来&ldquo;国民爷爷&rdquo;李顺才、尹秀静、宋在河，以及金秀美，这四位年龄相加超过200岁的老戏骨，共同创作了这部反映夕阳之恋的温馨之作。</p>
<p>
	　　此前，秋昌民的喜剧之作《麻婆岛》因出奇制胜地刻画了五位天马行空的老奶奶形象而成为喜闻乐见的合家欢电影。这次，秋昌民再接再厉，又一次选择了反映暮年情怀的温暖戏路，聚焦四位性格迥异，却都对爱充满渴望的老年人，展开了一幕幕逗趣又感人的小故事。秋昌民在发布会上表示，这是一部罗曼史，是献给情人节最好的礼物，爱情不仅是年轻人的专利，也是老年人生活中永不磨灭的闪亮元素，这是一部从5岁到80岁的观众都可以走进影院观看的作品。</p>
<p>
	　　有了四位经验丰富的老戏骨坐镇自然令秋昌民吃了一颗定心丸，但是拍过程中仍难免突发事件。片中本有一处极为重要的点睛一幕，即李顺才饰演的&ldquo;满硕&rdquo;拖着车在下着雪花的胡同遇到尹秀静饰演的&ldquo;伊芬&rdquo;。在漫天飞雪的胡同，两个老人的心渐渐走近，成为片中最浪漫的一幕。然而就是这场预计三天拍完的戏，却需要压缩在一天内完成，原因就是最重要的道具&ldquo;雪&rdquo;的分量不足，根本无法制成排满三天。为了完成这个难以放弃的情节，秋昌民决定带领全剧组在一天内拍完。为了保证质量，李顺才不顾年事已高，超负荷赶工。秋昌民从现场显示器中看到李顺才的表演不禁感动万分，在完成最后一个镜头后，饱含深情地向老人家道了一声&ldquo;辛苦了&rdquo;。李顺才则颇为欣喜地表示，没想到这个年纪还可以演一次&ldquo;爱的告白&rdquo;，再辛苦也心甘情愿。</p>
<p>
	　　该片的配角阵容也相当强大。秋昌民在编写剧本时，已想到用&ldquo;达秀&rdquo;一名命名片中的旧货店老板，后来干脆就请吴达秀亲自出演这个角色。秋昌民事后承认，其实剧本写到那里，脑子里已是吴达秀的样子，索性就&ldquo;将错就错&rdquo;了。另外，最引人瞩目的还有宋智孝阔别两年重归大银幕。此前这个率性女子因全裸出演《霜花店》引起人们关注，成为潜力之星，此次她洗去铅华饰演&ldquo;满硕&rdquo;的孙女，鼓励自己的爷爷大胆示爱，形象温暖贴心。而作为片中唯一的&ldquo;恶角&rdquo;，李文植的表演也相当到位。这位擅长搞笑小人物的黄金&ldquo;甘草&rdquo;再次出色地完成了自己的任务。</p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.netftp//dy44:piaohua@dy44.piaohua.com:3142/" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3383/飘花电影piaohua.com爱你EP01.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3383/飘花电影piaohua.com爱你EP01.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3383/飘花电影piaohua.com爱你EP02.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3383/飘花电影piaohua.com爱你EP02.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3383/飘花电影piaohua.com爱你EP03.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3383/飘花电影piaohua.com爱你EP03.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3383/飘花电影piaohua.com爱你EP04.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3383/飘花电影piaohua.com爱你EP04.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3383/飘花电影piaohua.com爱你EP05.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3383/飘花电影piaohua.com爱你EP05.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3383/飘花电影piaohua.com爱你EP06.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3383/飘花电影piaohua.com爱你EP06.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3383/飘花电影piaohua.com爱你EP07.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3383/飘花电影piaohua.com爱你EP07.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3383/飘花电影piaohua.com爱你EP08.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3383/飘花电影piaohua.com爱你EP08.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3432/飘花电影piaohua.com爱你EP09.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3432/飘花电影piaohua.com爱你EP09.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3437/飘花电影piaohua.com爱你EP10.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3437/飘花电影piaohua.com爱你EP10.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3490/飘花电影piaohua.com爱你EP11.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3490/飘花电影piaohua.com爱你EP11.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3490/飘花电影piaohua.com爱你EP12.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3490/飘花电影piaohua.com爱你EP12.rmvb</a></td>
		</tr>
	</tbody>
</table>
<p>
	&nbsp;</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1A93010-59311.jpg{/dede:field}
