{dede:field name='keywords'}昆虫王国之大联盟迅雷下载，免费{/dede:field}
{dede:field name='description'}昆虫王国之大联盟迅雷下载、免费下载，昆虫王国之大联盟Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}昆虫王国之大联盟{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2008-07-31{/dede:field}
{dede:field name='body'}<P>【译　　名】《昆虫王国之大联盟》经典记录片DVD中字<BR>【片　　名】Discovery Channel Insectia The Grand Alliance<BR>【年　　代】1999<BR>【国　　家】美国<BR>【类　　别】记录/短片<BR>【语　　言】英语<BR>【字　　幕】简体中文<BR>【IMDB评分】8.6/10 (29 votes)<BR>【文件格式】X264 + AC3<BR>【视频尺寸】800 x 448<BR>【电影整理】3E迅雷电影下载站(www.eee4.com)<BR>【文件大小】1CD 159MB<BR>【片　　长】26 mins<BR>【导　　演】German Gutierrez<BR>【主　　演】John Georges Brossard </P>
<P>【简　　介】：</P>
<P>这个就不用我废话了，喜欢收藏Discovery Channel的都知道有多经典！</P>
<P>昆虫，是地球上历史最悠久的生物之一，它们已演化了数百万年，数量胜过世上其他各种生物。3E迅雷<A href="/" target=_blank>电影下载</A>站</P>
<P><IMG src="http://pic.piaohua.com/0701pic/allimg/080730/1817300.jpg"></P>
<P>【电影截图】：<BR>电影来源：www.eee4.com<BR><IMG src="http://pic.piaohua.com/0701pic/allimg/080730/1818070.jpg">&nbsp;<BR><IMG src="http://pic.piaohua.com/0701pic/allimg/080730/1817302.jpg">&nbsp;<BR><IMG src="http://pic.piaohua.com/0701pic/allimg/080730/1818071.jpg">&nbsp;<BR><IMG src="http://pic.piaohua.com/0701pic/allimg/080730/1818072.jpg"></P>
<P>2008-07-30 18:01:12 开始连接......<BR>2008-07-30 18:01:12 开始搜索候选资源......<BR>2008-07-30 18:01:12 搜索到52个候选资源<BR>2008-07-30 18:01:12 使用候选资源进行连接......<BR>2008-07-30 18:01:13 搜索到121个候选资源<BR>2008-07-30 18:01:13 使用候选资源进行连接......<BR>2008-07-30 18:01:13 文件创建成功，开始下载数据......<BR>2008-07-30 18:01:16 用户取消下载&nbsp;&nbsp; 本文来自 <A href="/index.html" target=_blank>www.eee4.com</A></P>（直接可能无法下载，一律使用<A href="/soft.htm" target=_blank>迅雷下载</A>）<BR>经典记录片《昆虫王国之大联盟》DVD中字 －来自[3E迅雷电影站eee4.com]下载地址：<IMG src="/templets/img/down.jpg" border=0><BR>
<TABLE style="BORDER-RIGHT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; BORDER-BOTTOM: #cccccc 1px dotted" cellSpacing=0 cellPadding=6 width="95%" align=center border=0>
<TBODY>
<TR>
<TD style="WORD-WRAP: break-word" bgColor=#fdfddf><ANCHOR></ANCHOR><A href="ftp://eee4.com:8113@vip20.eee4.com:8113/[3E迅雷电影站www.eee4.com]昆虫王国之大联盟DVD中字.rmvb" target=_blank>ftp://eee4.com:8113@vip20.eee4.com:8113/[3E迅雷电影站www.eee4.com]昆虫王国之大联盟DVD中字.rmvb</A></TD></TR></TBODY></TABLE>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1614120-25218.jpg{/dede:field}
