{dede:field name='keywords'}迫在眉睫/迫在眉梢/,燃眉之急[DV{/dede:field}
{dede:field name='description'}迫在眉睫/迫在眉梢/ 燃眉之急[DVD中英双字1280x720高清版]迅雷下载、免费下载，迫在眉睫/迫在眉梢/ 燃眉之急[DVD中英双字1280x720高清版]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}迫在眉睫/迫在眉梢/ 燃眉之急[DVD中英双字1280x720高清版]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-02-08{/dede:field}
{dede:field name='body'}<p>
	【译　　名】《迫在眉睫/迫在眉梢/ 燃眉之急》豪华阵容犯罪惊秫动作大片DVD中英双字1280x720高清版<br />
	【片　　名】John Q<br />
	【年　　代】2002<br />
	【国　　家】美国<br />
	【类　　别】剧情/动作<br />
	【语　　言】英语<br />
	【字幕语言】中文/英文<br />
	【视频尺寸】1280&times;720<br />
	【文件格式】RMVB+AAC<br />
	【IMDB评分】6.6/10&nbsp; &nbsp;26,330 votes<br />
	【IMDB链接】http://www.imdb.com/title/tt0251160<br />
	【片　　长】116 min<br />
	【导　　演】尼克 卡萨维茨 Nick Cassavetes&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;<br />
	【主　　演】丹泽尔&middot;华盛顿 Denzel Washington<br />
	&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;罗伯特&middot;杜瓦尔 Robert DuVall<br />
	　　　　　　安妮&middot;海切 Anne Heche<br />
	　　　　　　詹姆斯&middot;伍兹 James Woods<br />
	　　　　　　艾迪&middot;格里芬 Eddie Griffin<br />
	　　　　　　雷&middot;利奥塔 Ray Liotta　<br />
	<br />
	【简　　介】<br />
	<br />
	&nbsp; &nbsp;约翰&middot;Q&middot;阿奇伯德（丹泽尔&middot;华盛顿）是个工厂里的工人，他工作很卖命也很顾家，可生活依然不富裕。为了养家糊口，妻子丹妮斯也要上班挣钱，夫妻俩因忙碌而使感情日渐淡漠，婚姻几近破裂。他们生活中唯一的亮点，就是9岁的儿子迈克尔。<br />
	　　可不幸总是出其不意地降临到苦命人的身上。一天，迈克尔突然昏到在棒球赛场上，约翰&middot;Q把他送到医院后得知：儿子患有严重的先天性心脏病，需要进行心脏移植手术才能保住性命。<br />
	　　心脏移植手术的费用非常昂贵，而约翰&middot;Q的医疗保险远不足以负担15万美金的手术费。医院的头头（安妮&middot;海切）得知这个情况后，决定把迈克尔从等待移植者的名单中剔除，除非约翰&middot;Q能预付30%的手术费。此举激怒了约翰&middot;Q，在求助于迈克尔的主治医生特纳（詹姆斯&middot;伍兹）<a href="http://www.eee4.com/" target="_blank">电影下载</a>未果的情况下，他愤然持枪闯入了医院的急诊室，绑架了几位医护人员和病人做人质，要求院方立刻为儿子动手术。<br />
	　　然而事情并不像约翰&middot;Q想象的那么简单，面对他的不仅是一群无辜又需要护理的人质，还有一个经验丰富的谈判家（罗伯特&middot;杜瓦尔）和一个想要速战速决的警长（雷&middot;利奥塔）。约翰&middot;Q和警方的对峙还惊动了媒体，全市的大众对这一事态的发展都投以了极大的关注。他们的感情似乎更多倾向于违法者约翰&middot;Q，因为他是当今不近人情的医疗和保险制度的受害者。但大众的同情并不能帮助约翰&middot;Q，他的前途到底如何呢？</p>
<p>
	<img src="http://img.album.pchome.net/54/70/47/68/361c0e3e6acb94de715702602e10678f.jpg" /></p>
<p>
	【电影截图】：可点击查看原图</p>
<br />
<br />
<p>
	<a href="http://img.album.pchome.net/54/70/47/68/c2df9f5ed1033390acbeaf3580c7fbe1.jpg" target="_blank"><img border="0" src="http://img.album.pchome.net/54/70/47/68/c2df9f5ed1033390acbeaf3580c7fbe1.jpg" /></a>&nbsp;<br />
	<a href="http://img.album.pchome.net/54/70/47/68/5c74b1df5d743c7118889cfa25ff5d6a.jpg" target="_blank"><img border="0" src="http://img.album.pchome.net/54/70/47/68/5c74b1df5d743c7118889cfa25ff5d6a.jpg" /></a><br />
	<br />
	<br />
	（一律使用<a href="http://www.eee4.com/soft.htm" target="_blank">迅雷下载</a>）<br />
	豪华阵容犯罪惊秫动作大片《迫在眉梢》DVD中英双字1280x720高清版 [下载地址]：<img border="0" src="http://www.eee4.com/templets/img/down.jpg" /></p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://4e:4e@www2.eee4.com:345/[3E电影站www.eee4.com]迫在眉梢DVD中英双字1280x720高清版.rmvb" target="_blank">ftp://4e:4e@www2.eee4.com:345/[3E电影站www.eee4.com]迫在眉梢DVD中英双字1280x720高清版.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1605Y30-5W57.jpg{/dede:field}
