{dede:field name='keywords'}海上传奇/上海传奇[DVD国语中英{/dede:field}
{dede:field name='description'}海上传奇/上海传奇[DVD国语中英双字/1024x576国语中字]迅雷下载、免费下载，海上传奇/上海传奇[DVD国语中英双字/1024x576国语中字]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}海上传奇/上海传奇[DVD国语中英双字/1024x576国语中字]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-09-26{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://6e:6e@m1.eee4.cc:1513/【3e电影网www.eee4.cc】海上传奇DVD国语中英双字.rmvb" target="_blank{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MQ5114P-53I8.jpg{/dede:field}
