{dede:field name='keywords'}依然是你日韩剧4迅雷下载，免费{/dede:field}
{dede:field name='description'}依然是你日韩剧4迅雷下载、免费下载，依然是你日韩剧4Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}依然是你日韩剧4{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-25{/dede:field}
{dede:field name='body'}<p>
	&nbsp;<img src="http://img.funshion.com/attachment/new_images/2012/05-21/18395589_1337588793_721.jpg" /></p>
<p>
	<img src="http://img.funshion.com/attachment/new_images/2012/05-16/18395589_1337153710_316.jpg" /></p>
<p>
	<img src="http://img.funshion.com/attachment/new_images/2012/05-21/18395589_1337588960_65.jpg" width="650" /></p>
<p>
	&nbsp;</p>
<p>
	导演：朴京烈</p>
<p>
	&bull;演员：<br />
	申恩庆 / 金承秀 / 王彬娜 / 金成恩 / 宋在林 / 朴贞秀</p>
<p>
	&bull;类型：家庭<br />
	&bull;首映：2012年5月21日 韩国<br />
	&bull;又名：&#44536;&#47000;&#46020; &#45817;&#49888; / 依然是你</p>
<p>
	&bull;点评： &ldquo;黑帮老婆&rdquo;申恩庆重出江湖，变身复仇艳妇--</p>
<p>
	<br />
	&bull;剧情： 　《也就是你》讲述的是因假装离婚成为真正离婚女的一个女人为挽留变心的老公和被夺的女儿,和老公的对手进行假装恋爱所展开的一部背叛与复仇的电视剧</p>
<p>
	&bull; 花絮： 《也就是你》是由申恩庆、金承秀、王彬娜、金成恩领衔主演的SBS日播剧 ..</p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaobajie.com/" target="_blank">http://www.xiaobajie.com</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3472/飘花电影piaohua.com依然是你01.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3472/飘花电影piaohua.com依然是你01.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3478/飘花电影piaohua.com依然是你02.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3478/飘花电影piaohua.com依然是你02.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3488/飘花电影piaohua.com依然是你03.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3488/飘花电影piaohua.com依然是你03.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3491/飘花电影piaohua.com依然是你04.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3491/飘花电影piaohua.com依然是你04.rmvb</a></td>
		</tr>
	</tbody>
</table>
<p>
	&nbsp;</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1AXW0-41512.jpg{/dede:field}
