{dede:field name='keywords'}美国战舰修正版DVD中字2012美国{/dede:field}
{dede:field name='description'}美国战舰修正版DVD中字2012美国战争动作惊悚迅雷下载、免费下载，美国战舰修正版DVD中字2012美国战争动作惊悚Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}美国战舰修正版DVD中字2012美国战争动作惊悚{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-16{/dede:field}
{dede:field name='body'}<p>
	<img src="/uploads/allimg/c120525/133O0WQJ0-136393.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 842px; border-top: 0px solid; border-right: 0px solid" /></p>

<p>
	导演： Thunder Levin<br />
	主演：马里奥&middot;范&middot;皮布尔斯 Mario Van Peebles<br />
	卡尔&middot;韦瑟斯 Carl Weathers<br />
	地区：美国　　<br />
	语言：英语<br />
	上映日期：2012-5-15　　<br />
	片长：86min<br />
	类型：惊悚 / 战争<br />
	又名：无</p>
<p>
	剧情简介</p>
<p>
	<br />
	一个神秘的船只对地球发动了战争，而只有在爱荷华州最新建造的美国战舰和船员们可以防止地球大战&hellip;&hellip;</p>
<p>
	相关影讯<br />
	　　在彼得&middot;博格执导的《战舰》即将上映的前夕，同样以战舰为题材的美国电影《美国战舰》也公布预告片与上映时间。从预告片上来看，虽然《美国战舰》并未投入大笔资金，但科幻效果看起来并不比《战舰》差多少。《美国战舰》将于2012年5月15日上映。 　　《战舰》的小成本翻版 　　不知道是有意还是无意，《美国战舰》选在了《战舰》在美国上映就紧跟着上映。虽说《美国战舰》的名气没有《战舰》大，但影片中有美女，有帅哥，还有豪华美军战舰，就连海报也很是气派，看样子它想要和《战舰》一比高下了。《美国战舰》不两种类似的战争题材，不知道到底哪个更精彩呢？我们还是期待《美国战舰》的上映吧。</p>
<p>
	<br />
	◎影片截图</p>
<p>
	<img border="0" src="/uploads/allimg/c120525/133O0WV2P-142L4.jpg" /></p>
<p>
	<img border="0" src="/uploads/allimg/c120525/133O0WVY0-151225.jpg" /></p>
<p>
	<img border="0" src="/uploads/allimg/c120525/133O0WW510-164119.jpg" /></p>
<p>
	<img border="0" src="/uploads/allimg/c120525/133O0WX210-1H4Y.jpg" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="/uploads/allimg/c120525/133O0T31310-42214.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：http://www.xiaozhizhu.net</td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				&nbsp;ftp://dy44:piaohua@dy44.piaohua.com:3432/飘花电影piaohua.com美国战舰修正版DVD中字.rmvb</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O0WXR0-1Q3I.jpg{/dede:field}
