{dede:field name='keywords'}哈姆雷特/王子复仇记[BD中英双字{/dede:field}
{dede:field name='description'}哈姆雷特/王子复仇记[BD中英双字976x720高清版]迅雷下载、免费下载，哈姆雷特/王子复仇记[BD中英双字976x720高清版]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}哈姆雷特/王子复仇记[BD中英双字976x720高清版]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2009-11-09{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://3e:3e@xl.eee4.com:315/[3E电影站www.eee4.cn]哈姆雷特BD中英双字976x720高清版.rmvb" target=_blank>ftftp://3e:3e@xl.eee4.com:315/[3E电影站www.eee4.cn]哈姆雷特BD中英双字976x720高清版.rmvb</A></TD></TR></TBODY></TABLE></div><ul class="mmlist{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MQ302520-19261.jpg{/dede:field}
