<?php
$z[0]=Array("field","时间与城市/视与听[DVD中英双字]",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","时间与城市/视与听[DVD中英双字]迅雷下载、免费下载，时间与城市/视与听[DVD中英双字]Gvod高清在线播放，剧情介绍等。",73,227);
$z[1][4]['name']="description";
$z[2]=Array("field","时间与城市/视与听[DVD中英双字]",229,297);
$z[2][4]['name']="title";
$z[3]=Array("field","",299,338);
$z[3][4]['name']="writer";
$z[4]=Array("field","",340,379);
$z[4][4]['name']="source";
$z[5]=Array("field","2012-05-22",381,431);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",433,470);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://e10:e10@xl2.eee4.com:9306/[3E电影站www.eee4.com]时间与城市.rmvb\" target=\"_blank",472,596);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MP4H3Z-4WP.jpg",598,678);
$z[8][4]['name']="litpic";

?>