{dede:field name='keywords'}时间与城市/视与听[DVD中英双字]{/dede:field}
{dede:field name='description'}时间与城市/视与听[DVD中英双字]迅雷下载、免费下载，时间与城市/视与听[DVD中英双字]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}时间与城市/视与听[DVD中英双字]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-22{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://e10:e10@xl2.eee4.com:9306/[3E电影站www.eee4.com]时间与城市.rmvb" target="_blank{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MP4H3Z-4WP.jpg{/dede:field}
