<?php
$z[0]=Array("field","街头之王/地头蛇/正义悍将/守夜",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","街头之王/地头蛇/正义悍将/守夜人BD中英双字1024/1280高清迅雷下载、免费下载，街头之王/地头蛇/正义悍将/守夜人BD中英双字1024/1280高清Gvod高清在线播放，剧情介绍等。",72,274);
$z[1][4]['name']="description";
$z[2]=Array("field","街头之王/地头蛇/正义悍将/守夜人BD中英双字1024/1280高清",276,368);
$z[2][4]['name']="title";
$z[3]=Array("field","",370,409);
$z[3][4]['name']="writer";
$z[4]=Array("field","",411,450);
$z[4][4]['name']="source";
$z[5]=Array("field","2012-03-17",452,502);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",504,541);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://eee4.com:1044@vip11.eee4.com:1044/街头之王/[3E迅雷电影站www.eee4.com]街头之王DVD.rmvb\" target=\"_blank",543,689);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MO4T4Z-11238.jpg",691,773);
$z[8][4]['name']="litpic";

?>