{dede:field name='keywords'}智人迅雷下载，免费下载，Gvod高{/dede:field}
{dede:field name='description'}智人迅雷下载、免费下载，智人Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}智人{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2008-03-19{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://eee4.com:8055@vip12.eee4.com:8055/智人/[3E迅雷电影站www.eee4.com]智人CD1.rmvb" target=_blank>ftftp://eee4.com:8055@vip12.eee4.com:8055/智人/[3E迅雷电影站www.eee4.com]智人CD1.rmvb</A></TD></TR></TBODY></TABLE>CD2：<BR>
<TABLE style="BORDER-RIGHT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; BORDER-BOTTOM: #cccccc 1px dotted" cellSpacing=0 cellPadding=6 width="95%" align=center border=0>
<TBODY>
<TR>
<TD style="WORD-WRAP: break-word" bgColor=#fdfddf><ANCHOR></ANCHOR><A href="ftftp://eee4.com:8055@vip12.eee4.com:8055/智人/[3E迅雷电影站www.eee4.com]智人CD2.rmvb" target=_blank>ftftp://eee4.com:8055@vip12.eee4.com:8055/智人/[3E迅雷电影站www.eee4.com]智人CD2.rmvb</A></TD></TR></TBODY></TABLE></div><ul class="mmlist{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MP443550-56452.jpg{/dede:field}
