<?php
$z[0]=Array("field","古墓迷途/我们来自未来[DVD国语]",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","古墓迷途/我们来自未来[DVD国语]迅雷下载、免费下载，古墓迷途/我们来自未来[DVD国语]Gvod高清在线播放，剧情介绍等。",73,227);
$z[1][4]['name']="description";
$z[2]=Array("field","古墓迷途/我们来自未来[DVD国语]",229,297);
$z[2][4]['name']="title";
$z[3]=Array("field","",299,338);
$z[3][4]['name']="writer";
$z[4]=Array("field","",340,379);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-03-19",381,431);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",433,470);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://4e:4e@www5.eee4.cc:1427/【3E电影院www.eee4.cc】古墓迷途DVD国语.rmvb\" target=_blank>ftftp://4e:4e@www5.eee4.cc:1427/【3E电影院www.eee4.cc】古墓迷途DVD国语.rmvb</A></TD></TR></TBODY></TABLE></div><ul class=\"mmlist",472,728);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MP60C50-29326.jpg",730,813);
$z[8][4]['name']="litpic";

?>