{dede:field name='keywords'}乔布斯如何改变世界BD中英双字10{/dede:field}
{dede:field name='description'}乔布斯如何改变世界BD中英双字1024高清2011纪录片迅雷下载、免费下载，乔布斯如何改变世界BD中英双字1024高清2011纪录片Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}乔布斯如何改变世界BD中英双字1024高清2011纪录片{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-11-03{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img.killman.net/-4-/11.02/R1/01.jpg" /></p>
<p>
	译　　名　探索频道：乔布斯如何改变世界/天才乔布斯如何改变世界<br />
	片　　名　Discovery Channel : iGenius How Steve Jobs Changed the World<br />
	年　　代　2011<br />
	国　　家　美国<br />
	类　　别　纪录<br />
	语　　言　英语<br />
	字　　幕　中英字幕<br />
	文件格式　HD1024-RMVB<br />
	视频尺寸　1024 x 572<br />
	文件大小　416MB<br />
	片　　长　43 Mins</p>
<p>
	简介：</p>
<p>
	Discovery Channel 将播出一小时乔布斯特别节目!</p>
<p>
	　　根据Inside TV的消息，目前Discovery已经准备要播出Steve Jobs的特别节目 iGenius: How Steve Jobs Changed the World。（史蒂夫&middot;乔布斯如何改变世界）该节目长约一个小时，除了与 NBC的Peacock Productions合作之外，还找来流言终结者的两位主持人Adam Savage 与Jamie Hyneman来主持节目。</p>
<p>
	　　除了介绍Steve Jobs一生的成就之外，节目也采访了许多早期与Steve Jobs创业相关的人物，例如 Homebrew Computer Club的创立成员Lee Felsenstein、跟Steve Jobs一起去印度，并成为Apple最早期员工之一的Daniel Kottke、以及教Jobs与Woz拨打免费电话秘技，之后负责设计Apple II电话电路板（不过从来没拿出去卖）的 John Draper。而音乐家Stevie Wonder 与 Pete Wentz也会在节目里叙述Steve Jobs的创新是如何影响他们的职业生涯。</p>
<p>
	　　《探索频道》将会在今天播出一个为时1小时的特别节目，以此来纪念逝去的苹果联合创始人，前CEO史蒂夫.乔布斯。目前该节目的名称已经定为iGenius：How Steve Jobs Changed the World。</p>
<p>
	　　纪录片将由《流言终结者》的著名主持人Adam Savage和Jamie Hyneman共同主持，他们亲自访问苹果曾经的CEO们，以及一些在苹果历史上的著名人物，并向我们讲述乔布斯是如何通过他的创新精神，一步步的影响着科技圈甚至是全世界。</p>
<p>
	　　Savage这样评价乔布斯：他是一个不同寻常的人，他不会一味的去适合大众所需的产品。他以全新的方式定义了现代数字生活的思考方式：生产力，创造力，音乐，通信，媒体和艺术。他以直接或间接的方式影响着我们所有人的生活。</p>
<p>
	　　iGenius：How Steve Jobs Changed the World于当地时间10月16日晚8点首映，210个国家的地区同步播出。</p>

<p>
	[下载地址]： &nbsp;<img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" /></p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:1986/飘花电影piaohua.com乔布斯如何改变世界BD中英双字1024高清.mkv">&nbsp;ftp://dy44:piaohua@dy44.piaohua.com:1986/飘花电影piaohua.com乔布斯如何改变世界BD中英双字1024高清.mkv</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1C44030-440I.jpg{/dede:field}
