{dede:field name='keywords'}夜巡者/为女守夜HDTVrip中英字幕{/dede:field}
{dede:field name='description'}夜巡者/为女守夜HDTVrip中英字幕英国战争2011迅雷下载、免费下载，夜巡者/为女守夜HDTVrip中英字幕英国战争2011Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}夜巡者/为女守夜HDTVrip中英字幕英国战争2011{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-07-30{/dede:field}
{dede:field name='body'}<p>
	<a href="http://pic0.picsorlinks.com/ph_or_129577_919bac9.jpg" target="_blank"><img border="0" src="http://pic0.picsorlinks.com/ph_bi_129577_919bac9.jpg" /></a></p>
<p>
	<a href="http://pic0.picsorlinks.com/ph_or_129578_b271cbc.jpg" target="_blank"><img border="0" src="http://pic0.picsorlinks.com/ph_bi_129578_b271cbc.jpg" /></a></p>
<p>
	◎译　　名　夜巡者/守夜<br />
	◎片　　名　The Night Watch<br />
	◎年　　代　2011<br />
	◎国　　家　英国<br />
	◎类　　别　战争/剧情<br />
	◎语　　言　英语<br />
	◎字　　幕　中英双字 深影字幕组<br />
	◎IMDB评分 7.0/10 (52 votes)<br />
	◎文件格式　DVD-RMVB<br />
	◎视频尺寸　640 x 352<br />
	◎文件大小　1CD 700MB<br />
	◎片　　长　90 Mins<br />
	◎导　　演　Richard Laxton<br />
	◎编　　剧 Paula Milne / Sarah Waters<br />
	◎主　　演　茱蒂&middot;惠特克 Jodie Whittaker ....</p>
<p>
	安娜&middot;麦克西维尔&middot;马丁 Anna Maxwell Martin ....Kay</p>
<p>
	克莱尔&middot;福伊 Claire Foy ....Helen</p>
<p>
	哈里&middot;崔德威 Harry Treadaway ....Duncan Pearce</p>
<p>
	哈里&middot;崔德威 Harry Treadaway ....Duncan Pearce</p>
<p>
	安娜&middot;威尔逊-琼斯 Anna Wilson-Jones ....Julia Standing</p>
<p>
	Liam Garrigan ....Reggie Nigri</p>
<p>
	克劳德&middot;布拉克利 Claudie Blakley ....Nancy</p>
<p>
	Kenneth Cranham ....Horace Mundy</p>
<p>
	Colin Mace ....Harry Hughes</p>
<p>
	Richard Cambridge ....Policeman</p>
<p>
	◎简　　介　<br />
	故事发生于四十年代动荡的伦敦，讲述了四位年轻的伦敦人因战争而交织的命运。在性道德和社会习俗的障碍被分解之时，凯，海伦，薇薇，邓肯享受着前所未有的性解放和充满激情的幽会。<br />
	影片从1947年战后重建开始讲述，采用倒叙手法，所以影片一开始就可以看到人物的结局，凯失魂落魄的漫游在街头，海伦和薇薇开着婚介所，帮人们解决爱情问题。但他们自己的感情生活却很棘手。海伦深陷于和茱莉亚的同性恋人关系，而薇薇继续与已婚男人私会。薇薇脆弱的弟弟似乎也隐藏着秘密。来找弟弟的神秘男子究竟又是谁。而在街头巧遇凯的薇薇又称曾得过她的大恩惠。这些人之间的关系究竟是如何构建起来的呢？在接下去的讲述中，影片回到了三年前的1944年，随着故事的发展，谜底浮出水面，但又带来了新的谜团...究竟何时才是故事的开始...何时才是结局...（文：深影字幕组@打狗棒）</p>
<p>
	截图：</p>
<p>
	<img border="0" src="http://img.xzz.cc/attachment/photo/Mon_1107/3900_089c1311840299ee3bf6f2398ffce.jpg" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy171:piaohua@dy171.piaohua.com:1111/飘花电影piaohua.com夜巡者HDTVrip.rmvb">&nbsp;&nbsp;</a><a href="ftp://dy171:piaohua@dy171.piaohua.com:1111/飘花电影piaohua.com夜巡者HDTVrip.rmvb">ftp://dy171:piaohua@dy171.piaohua.com:1111/飘花电影piaohua.com夜巡者HDTVrip.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O161P5Z-53G5.jpg{/dede:field}
