{dede:field name='keywords'}超时空要塞F恋离飞翼BD高清迅雷{/dede:field}
{dede:field name='description'}超时空要塞F恋离飞翼BD高清迅雷下载、免费下载，超时空要塞F恋离飞翼BD高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}超时空要塞F恋离飞翼BD高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-10-24{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="/uploads/allimg/c120525/133O04524010-41FQ.jpg" style="width: 700px; height: 700px" /></p>
<p>
	◎译　　名　超时空要塞F . 恋离飞翼<br />
	◎片　　名　Macross.Frontier-The.Wings.of.Goodbye<br />
	◎年　　代　2011<br />
	◎国　　家　日本<br />
	◎类　　别　动画<br />
	◎语　　言　日语<br />
	◎片　　长　115 min<br />
	◎导　　演　河森正治<br />
	◎主　　演<br />
	早乙女アルト，Alto Saotome，声：中村悠一<br />
	シェリル?ノーム，Sheryl Nome，声：远藤绫/歌：May&#39;n<br />
	ランカ?リー，Ranka Lee，声：中岛爱<br />
	ミハエル?ブラウン，Mikhail Blanc，声：神谷浩史<br />
	ルカ?アンジェロ，Luca Anjerony，声：福山润<br />
	松浦ナナセ，声：桑岛法子<br />
	オズマ?リー，Ozma Lee，声：小西克幸<br />
	クラン?クラン，Klein Klan，声：丰口惠<br />
	ネネ?ローラ，NENE ROURA，声：平野绫<br />
	ララミア?レレニア，RARAMIA LELEINIA，声：大村歌佳<br />
	ジェフリー?ワイルダー，Jeffrey Wilder，声：大川透<br />
	カナリア?ベルシュタイン，Canary Belstain，声：桑岛法子<br />
	ボビー?マルゴ，Bobby Malgo，声：三宅健太<br />
	モニカ?ラング，Monica Lange，声：田中理惠<br />
	ミーナ?ローシャン，Mina Roshan，声：平野绫<br />
	ラム?ホア，声：福原香织</p>
<p>
	◎简　　介<br />
	作为《超时空要塞 Frontier》的电影版后篇作品，《超时空要塞 Frontier 恋离飞翼》将接续前篇《超时空要塞 Frontier 虚空歌姬》，作品以电视版的故事作为基础，加入新画面与剪辑，最终的结局也将会与电视版本有所不同。</p>
<p>
	<img alt="" src="/uploads/allimg/c120525/133O0452F20-42XP.jpg" style="width: 720px; height: 405px" /><img alt="" src="/uploads/allimg/c120525/133O0452O60-434927.jpg" style="width: 720px; height: 405px" /><img alt="" src="/uploads/allimg/c120525/133O0452Z-44G31.jpg" style="width: 720px; height: 405px" /></p>
<p>
	&nbsp;</p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="/uploads/allimg/c120524/133N2Z4FF-102231.jpg" />&nbsp;&nbsp;&nbsp;</p>


<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy125:piaohua@dy125.piaohua.com:7082/飘花电影piaohua.com超时空要塞F恋离飞翼BD中字1280高清.rmvb</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O04530130-459319.jpg{/dede:field}
