{dede:field name='keywords'}妙探双龙HD1280高清迅雷下载，免{/dede:field}
{dede:field name='description'}妙探双龙HD1280高清迅雷下载、免费下载，妙探双龙HD1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}妙探双龙HD1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-03-29{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="/uploads/allimg/c120525/133O02E55P-BF0.jpg" /></p>
<p>
	【电影名】：妙探双龙<br />
	　　<br />
	<br />
	<b>【导 演】：</b>刘家荣<br />
	　　<br />
	<br />
	<b>【编 剧】：</b>黄炳耀<br />
	<br />
	<b>【主 演】：</b>苗侨伟<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 罗芙洛<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 汤镇业<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 关秀媚<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 西胁美智子<br />
	　　<br />
	<br />
	<b>【上 映】：</b>1989年<br />
	　　<br />
	<br />
	<b>【地 区】：</b>中国香港<br />
	　　<br />
	<br />
	<b>【类 型】：</b>剧情片<br />
	<br />
	<br />
	<b>【简介】</b><br />
	<br />
	&nbsp; &nbsp; &amp; ;&lt;&lt;妙探双龙&gt;&gt;是一部警匪片。它叙述警探阿胜和戴旧，如何协助FBI女干探保护污点证人和消灭黑帮的故事。美国黑帮份子Ken汤因藏有黑帮犯罪证据，欲作警方污点证人而被黑帮追杀。他的身份被港警方知道，令警探阿胜和戴旧监视和保护他，他俩一时疏忽被汤逃脱了。阿胜和戴旧知汤有一妹便24小时监视她。阿胜被她的身份证号码大全美貌吸引，向她展开热烈追求。美黑帮收买港黑帮鹿川携手一齐追杀汤。鹿川寻汤不获乃掳其妹，阿胜把她救出。汤向FBI派来查辨此案的女干探Cindy报讯，利用她把鹿川及美国黑帮杀手制服拘捕归案。鹿川妹妹西协知兄被捕，来港报仇，伙同美黑帮杀手掳走May，命汤拿罪证来交换，她取得罪证后还要杀汤，在危急间阿胜等及时赶到，救出汤，把西协等匪徒拘捕了。</p>
<p>
	<img alt="" src="/uploads/allimg/c120525/133O02E6320-I531.jpg" style="width: 453px; height: 515px" /></p>
<p>
	<br />
	<br />
	&nbsp;</p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="/uploads/allimg/c120524/133N2Z4FF-102231.jpg" />&nbsp;&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="word-break: break-all; line-height: 18px" width="100%">
				ftp://dy125:piaohua@dy125.piaohua.com:7783/飘花电影piaohua.com妙探双龙HD国语中字1280高清.rmvb</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O02EG40-X1c.jpg{/dede:field}
