{dede:field name='keywords'}X档案2：我要相信BD中英双字1024{/dede:field}
{dede:field name='description'}X档案2：我要相信BD中英双字1024/1280高清迅雷下载、免费下载，X档案2：我要相信BD中英双字1024/1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}X档案2：我要相信BD中英双字1024/1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-12-12{/dede:field}
{dede:field name='body'}<p>
	<br />
	<img alt="" border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://i3.sinaimg.cn/ent/d/2008-07-08/U105P28T3D2092631F326DT20080708141944.jpg');" src="http://i3.sinaimg.cn/ent/d/2008-07-08/U105P28T3D2092631F326DT20080708141944.jpg" /><br />
	<br />
	◎译　　名　《X档案2/X档案：我要相信》08最新科幻大片DVD中英双字<br />
	◎片　　名　The X Files I Want to Believe<br />
	◎年　　代　2008<br />
	◎国　　家　美国/加拿大<br />
	◎类　　别　神秘/科幻<br />
	◎语　　言　英语<br />
	◎字　　幕　中文<br />
	◎IMDB评分 6.2/10&nbsp; 19,085 votes<br />
	◎IMDB链接 http://www.imdb.com/title/tt0443701<br />
	◎文件格式　XviD + MP3<br />
	◎视频尺寸　800 x 336<br />
	◎文件大小　2CD<br />
	◎片　　长　104 min<br />
	◎导　　演　Chris Carter<br />
	◎主　　演　David Duchovny ... Fox Mulder<br />
	　　　　　　Gillian Anderson ... Dana Scully<br />
	　　　　　　Amanda Peet ... ASAC Dakota Whitney<br />
	　　　　　　Billy Connolly ... Father Joseph Crissman<br />
	　　　　　　Xzibit ... Agent Mosley Drummy<br />
	　　　　　　Callum Keith Rennie ... 2nd Abductor (Janke Dacyshyn)<br />
	　　　　　　Adam Godley ... Father Ybarra<br />
	　　　　　　Alex Diakun ... Gaunt Man<br />
	　　　　　　Nicki Aycox ... 2nd Victim<br />
	　　　　　　Fagin Woodcock ... 1st Abductor (Franz Tomczeszyn)<br />
	　　　　　　Marco Niccoli ... Christian Fearon<br />
	　　　　　　Carrie Ruscheinsky ... Margaret Fearon<br />
	　　　　　　Spencer Maybee ... Blair Fearon<br />
	　　　　　　Veronika Hadrava ... Female Assistant<br />
	　　　　　　Denis Krasnogolov ... Male Assistant<br />
	<br />
	◎简　　介　<br />
	<br />
	　　鉴于《X档案》系列电视剧所遗留下的伟大传统和一贯执行的保密态度，新一集电影在内容上仍然维持着相当大的隐蔽性&hellip;&hellip;首先，影片在故事方面完全独立于原著电视剧之外，和任何篇章都没有一丝一毫地联系，但它同时也维系了剧集中最受好评且受人喜爱的一些特色元素，依然从FBI探员福克斯&middot;穆尔德和达娜&middot;斯考莉之间错综复杂的关系入手，不过这一次有所不同，他们那互相扶持又带点暧昧的相处之道会提升至一个全新的层面。惟一不变的，是穆尔德对隐藏起来的事实那不可动摇的诉求之心，至于斯考莉，这个脾气急躁却拥有着别人无法比拟的惊人智慧的医师，则是穆尔德在追求真相的道路上，不可或缺的精神与行为上的支撑，两人的命运有着解不开的紧密联系。<br />
	<br />
	　　另一个重要线索出现在穆尔德那看似有超能力的儿子身上，这个于电视剧第8季中出现的角色，很可能是这一次发生的神秘事件的关键所在。</p>
<p>
	【中英字幕版本】：<br />
	<img src="http://i3.6.cn/cvbnm/28/76/26/91e7bba12f4c8e150c87df67d6d462c4.jpg" />&nbsp;<br />
	<img src="http://i3.6.cn/cvbnm/1e/19/06/a9c3757c5c08c43f958e8d5dae6558c9.jpg" /></p>

<p>
	【中文字幕版本】：<br />
	<br />
	<img alt="" border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://i3.6.cn/cvbnm/cd/57/58/0b2c017b6267fa86373e43503934f6f9.jpg');" src="http://i3.6.cn/cvbnm/cd/57/58/0b2c017b6267fa86373e43503934f6f9.jpg" /><br />
	<img alt="" border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://i3.6.cn/cvbnm/f3/10/ed/457cc8f7ee3b7ace74833f5d9825a7ad.jpg');" src="http://i3.6.cn/cvbnm/f3/10/ed/457cc8f7ee3b7ace74833f5d9825a7ad.jpg" /><br />
	<img alt="" border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://i3.6.cn/cvbnm/6d/82/ea/0a72c2f2a43acb4cecbfc9c229f6b71c.jpg');" src="http://i3.6.cn/cvbnm/6d/82/ea/0a72c2f2a43acb4cecbfc9c229f6b71c.jpg" /><br />
	<img alt="" border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://i3.6.cn/cvbnm/6a/c7/0e/4d9472f4fd16a1c97b8bb8ef55e5f3c1.jpg');" src="http://i3.6.cn/cvbnm/6a/c7/0e/4d9472f4fd16a1c97b8bb8ef55e5f3c1.jpg" /></p>
<p>
	08最新科幻大片《X档案2》DVD中字 －来自[3E电影站eee4.com]：<img border="0" src="http://www.eee4.com/templets/img/down.jpg" /></p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<anchor></anchor><a href="ftp://e64:e64@xl3.eee4.com:1004/[3E电影站www.eee4.com]X档案：我要相信CD1.rmvb" target="_blank">ftp://e64:e64@xl3.eee4.com:1004/[3E电影站www.eee4.com]X档案：我要相信CD1.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<anchor></anchor><a href="ftp://e64:e64@xl3.eee4.com:1004/[3E电影站www.eee4.com]X档案：我要相信CD2.rmvb" target="_blank">ftp://e64:e64@xl3.eee4.com:1004/[3E电影站www.eee4.com]X档案：我要相信CD2.rmvb</a></td>
		</tr>
	</tbody>
</table>
<p>
	08最新科幻大片《X档案2》DVD中英双字 －来自[3E电影站eee4.com]：<img border="0" src="http://www.eee4.com/templets/img/down.jpg" /><br />
	&nbsp;</p>

<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<anchor></anchor><a href="ftp://e65:e65@xl3.eee4.com:1004/[3E电影站www.eee4.com]X档案：我要相信DVD中英双字CD1.rmvb" target="_blank">ftp://e65:e65@xl3.eee4.com:1004/[3E电影站www.eee4.com]X档案：我要相信DVD中英双字CD1.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<anchor></anchor><a href="ftp://e65:e65@xl3.eee4.com:1004/[3E电影站www.eee4.com]X档案：我要相信DVD中英双字CD2.rmvb" target="_blank">ftp://e65:e65@xl3.eee4.com:1004/[3E电影站www.eee4.com]X档案：我要相信DVD中英双字CD2.rmvb</a></td>
		</tr>
	</tbody>
</table>
<p>
	08最新科幻大片《X档案2》1024/1280高清－来自[3E电影站eee4.com]：<img border="0" src="http://www.eee4.com/templets/img/down.jpg" /></p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<anchor></anchor><a href="ftp://dy44:piaohua@dy44.piaohua.com:2310/飘花电影piaohua.comX档案2：我要相信BD中英双字1024高清.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2310/飘花电影piaohua.comX档案2：我要相信BD中英双字1024高清.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<anchor></anchor><a href="ftp://dy44:piaohua@dy44.piaohua.com:2310/飘花电影piaohua.comX档案2：我要相信BD中英双字1280高清.rmvb"><u>ftp://dy44:piaohua@dy44.piaohua.com:2310/飘花电影piaohua.comX档案2：我要相信BD中英双字1280高清.rmvb</u></a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15WF50-21S7.jpg{/dede:field}
