{dede:field name='keywords'}特务迷城BD国粤双语中字1024/128{/dede:field}
{dede:field name='description'}特务迷城BD国粤双语中字1024/1280高清迅雷下载、免费下载，特务迷城BD国粤双语中字1024/1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}特务迷城BD国粤双语中字1024/1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-04{/dede:field}
{dede:field name='body'}<p>
	&nbsp;<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://img.album.pchome.net/54/68/92/29/f34686345548a8305a6653e9fbb08958.jpg');" src="http://img.album.pchome.net/54/68/92/29/f34686345548a8305a6653e9fbb08958.jpg" /></p>
<p>
	◎译　　名　《特务迷城》香港经典年度华语动作大片DVD粤语、国语中字1024x554高清版<br />
	◎片　　名　The Accidental Spy<br />
	◎年　　代　2001<br />
	◎国　　家　中国香港<br />
	◎类　　别　动作/喜剧/惊悚<br />
	◎语　　言　粤语/英语/法语/韩语/汉语普通话/土耳其语<br />
	◎字　　幕　中字<br />
	◎IMDB评分&nbsp; 5.7/10 (3,415 votes)<br />
	◎文件格式　BD-RMVB<br />
	◎视频尺寸　1024 X 560<br />
	◎文件大小　1CD<br />
	◎片　　长　108 Mins<br />
	◎导　　演　陈德森&nbsp; Teddy Chan&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;<br />
	◎主　　演　成龙&nbsp; Jackie Chan&nbsp; ....Buck Yuen/Jackie Chan<br />
	　　　　　　徐若瑄&nbsp; Vivian Hsu&nbsp; ....Yong&nbsp;<br />
	　　　　　　曾志伟 Eric Tsang&nbsp; ....Many Liu<br />
	　　　　　　金玟 Min Kim&nbsp; ....Carmen Wong (as Kim Min Jeong)<br />
	　　　　　　吴兴国 Wu Hsing-Kuo&nbsp; ....Lee Sang-Zen (as Wu Hsing Kuo)<br />
	　　　　　　张坚庭 Alfred Cheung&nbsp; ....Cheung the Lawyer<br />
	　　　　　　Anthony Rene Jones&nbsp; ....Philip Ashley (as Tony Jones)<br />
	　　　　　　Glory Simon&nbsp; ....TCN Field Reporter<br />
	　　　　　　Bradley James Allan&nbsp; ....Lee&#39;s <a href="http://www.eee4.com/gvod_help.htm" target="_blank">gvod</a>Bodyguard<br />
	　　　　　　张达明 Tat-Ming Cheung&nbsp; ....Tsui<br />
	　　　　　　斯科特&middot;阿金斯 Scott Adkins<br />
	　　　　　　朱茵 Athena Chu&nbsp; ....Woman Interested in Gym Equipment (uncredited)<br />
	　　　　　　Mustafa Presheva&nbsp; ....Italian Mob (uncredited)<br />
	◎简　　介　<br />
	&nbsp;<br />
	　　健身器材店营业员小北（成龙 饰），从小习武，并且有奇异的预感能力，梦想有一天成为特务。小北凭著预感及敏捷的身手，把打劫银行的劫匪当场逮捕，成为报纸的头条新闻人物。私家侦探从报纸的报导，得悉小北是一名孤儿，觉得他可能是一名韩国客户朴元正失散多年的儿子，遂带小北前往去见朴元正的律师，在好奇心的驱使下，小北决定跟随律师到韩国寻找身世之谜。<br />
	<br />
	　　小北在医院见到已经奄奄一息的朴元正，随即过世。之后小北遇上美国某周刊女记者福喜（金玫 饰），从她口中，小北知悉朴氏夫妇本为著名的双重特务，遵循著朴元正的遗言以及在女记者福喜的帮助下，小北从韩国来到土耳其，找到了一笔巨款，并邂逅了一名神秘女子咏（徐若瑄 饰）。正当小北得意忘形之际，却开始遭遇了一连串莫名其<a href="http://www.eee4.com/" target="_blank">迅雷电影下载</a>妙的袭击，令小北意识到身边其实危机四伏。寻亲、遗嘱、巨款&hellip;&hellip;，简单的表象下，另有复杂的内情，凭著敏锐触觉及过人身手，小北发现自己所经历的一切，竟与美国政府科学部失窃的炭疽菌有关，他已经被卷入一场国际组织间的争夺战之中了&hellip;&hellip;<br />
	<br />
	幕后制作<br />
	<br />
	　　这部影片由嘉禾投资1亿7千万港元拍摄，是嘉禾有史以来投资最多的一部影片。严格说来，这部影片并不在成龙的佳作之列，但确实找回了一些成龙在好莱坞主演的电影所欠缺的神采。《特务迷城》与许多其它的大作一样，也选择了国外作为主要场景，比如韩国和土耳其等地的实景拍摄。这部电影其实具有很强的成龙电影的特征，即不管有多重要的政_治因素在其中，成龙从来都采取视而不见的态度，只要维护眼前的进展就可以了，而太多的背景会成为叙事的累赘，简单的对与错往往就是生活的真谛。</p>
<p>
	【电影截图】：<br />
	<img onclick="if(this.width&gt;screen.width-461) window.open('http://img.album.pchome.net/54/68/92/29/949575067c7aad51fea66aa2b23577d1.jpg');" src="http://img.album.pchome.net/54/68/92/29/949575067c7aad51fea66aa2b23577d1.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 325px; border-top: 0px solid; border-right: 0px solid" />&nbsp;<br />
	<img onclick="if(this.width&gt;screen.width-461) window.open('http://img.album.pchome.net/54/68/92/29/6497d104e8216535d810a2ecf976a3d1.jpg');" src="http://img.album.pchome.net/54/68/92/29/6497d104e8216535d810a2ecf976a3d1.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 325px; border-top: 0px solid; border-right: 0px solid" /></p>
<p>
	香港经典年度华语动作大片《特务迷城》DVD粤语中字1024x554高清版 －来自[www.eee4.com]：<img border="0" src="http://www.eee4.com/templets/img/down.jpg" /></p>

<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://e8:e8@xl2.eee4.com:507/[3E电影站www.eee4.com]特务迷城DVD粤语中字1024x554高清版.rmvb" target="_blank">ftp://e8:e8@xl2.eee4.com:507/[3E电影站www.eee4.com]特务迷城DVD粤语中字1024x554高清版.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3345/飘花电影piaohua.com特务迷城BD国粤双语中字1280高清.mkv">ftp://dy44:piaohua@dy44.piaohua.com:3345/飘花电影piaohua.com特务迷城BD国粤双语中字1280高清.mkv</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15A3560-4LO.jpg{/dede:field}
