{dede:field name='keywords'}半熟恋人港台剧7迅雷下载，免费{/dede:field}
{dede:field name='description'}半熟恋人港台剧7迅雷下载、免费下载，半熟恋人港台剧7Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}半熟恋人港台剧7{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-19{/dede:field}
{dede:field name='body'}<p>
	<img src="http://img.funshion.com/attachment/new_images/2012/04-12/18881305_1334216945_505.jpg" width="650" /></p>
<p>
	导演：洪智育</p>
<p>
	&bull;演员：<br />
	路斯明 / 蔡淑臻 / 邱凯伟</p>
<p>
	&bull;类型：爱情<br />
	&bull;首映：2012年4月6日 中国台湾</p>
<p>
	&bull;点评： 蔡淑臻扮空姐怕密闭 路斯明瘦身变宅男--<br />
	&bull;剧情： 黎晓阳人生最闪耀的一刻，就是她大学毕业那年，幸运地考上航空公司的空服员，从此开始了忙碌又平凡的空姐生涯。但是当孟克槐这个男人意外闯入她的世界里，晓阳就像坐上失控的云霄飞车一般，朝向不可知的未来冲去。孟克槐是谁？出身世家，从小被师长视为天才资优生，第一本创作小说就卖了一百万本，他的才华，还有迷人又带点稚气的笑容，让他在短短时间就...</p>
<p>
	<img src="http://img.funshion.com/attachment/new_images/2012/04-12/18881305_1334216942_625.jpg" width="650" /></p>
<p>
	<img src="http://img.funshion.com/attachment/new_images/2012/04-12/18881305_1334216944_855.jpg" width="650" /></p>
<p>
	<img src="http://img.funshion.com/attachment/new_images/2012/04-12/18881305_1334216940_210.jpg" width="650" /></p>
<p>
	<img src="http://img.funshion.com/attachment/new_images/2012/04-12/18881305_1334216941_555.jpg" width="650" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.netftp//dy44:piaohua@dy44.piaohua.com:3125/" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3220/飘花电影piaohua.com半熟恋人01.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3220/飘花电影piaohua.com半熟恋人01.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3220/飘花电影piaohua.com半熟恋人02.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3220/飘花电影piaohua.com半熟恋人02.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3264/飘花电影piaohua.com半熟恋人03.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3264/飘花电影piaohua.com半熟恋人03.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3310/飘花电影piaohua.com半熟恋人04.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3310/飘花电影piaohua.com半熟恋人04.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3354/飘花电影piaohua.com半熟恋人05.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3354/飘花电影piaohua.com半熟恋人05.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3404/飘花电影piaohua.com半熟恋人06.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3404/飘花电影piaohua.com半熟恋人06.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3459/飘花电影piaohua.com半熟恋人07.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3459/飘花电影piaohua.com半熟恋人07.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1A5L0-31B3.jpg{/dede:field}
