<?php
$z[0]=Array("field","呼吸[BD中字1024x576高清版]迅雷",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","呼吸[BD中字1024x576高清版]迅雷下载、免费下载，呼吸[BD中字1024x576高清版]Gvod高清在线播放，剧情介绍等。",73,219);
$z[1][4]['name']="description";
$z[2]=Array("field","呼吸[BD中字1024x576高清版]",221,285);
$z[2][4]['name']="title";
$z[3]=Array("field","",287,326);
$z[3][4]['name']="writer";
$z[4]=Array("field","",328,367);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-02-10",369,419);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",421,458);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://3e:3e@m6.3edyy.com:139/【3E电影院www.3edyy.com】呼吸BD中字1024x576高清版.rmvb\" target=\"_blank",460,598);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MP5c640-41J0.jpg",600,682);
$z[8][4]['name']="litpic";

?>