{dede:field name='keywords'}胜地BD中字1280高清经典纪录片迅{/dede:field}
{dede:field name='description'}胜地BD中字1280高清经典纪录片迅雷下载、免费下载，胜地BD中字1280高清经典纪录片Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}胜地BD中字1280高清经典纪录片{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-09-27{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="/uploads/allimg/c120524/133N42A12P-13I6.jpg" /></p>
<p>
	◎译　　名　胜地<br />
	◎片　　名　The Greatest Places<br />
	◎年　　代&nbsp;&nbsp; 1998<br />
	◎国　　家　美国<br />
	◎类　　别　纪录片<br />
	◎语　　言　英语<br />
	◎字　　幕　中字<br />
	◎IMDB评分&nbsp; 6.1/10 (132 votes)<br />
	◎片　　长　39m:59s<br />
	◎导　　演　Mal Wolfe<br />
	◎主　　演&nbsp;<br />
	◎简　　介　<br />
	&nbsp;&nbsp; IMAX向您展示地球上最壮观的地方<br />
	　地球是太阳系里最缤纷多样的星球，本片耗费巨资拍摄而成。看过本片，你才真正了解地球地貌的鬼斧神工。<br />
	　亚马逊河是地球最大的河流，其流域之广几乎遍布南美洲一半土地。格陵兰这个地球最大的岛屿终年覆盖着冷冷的冰雪，专家估计格陵兰上的冰河每年孕育出一万到一万五千座冰山。此外，本片还展示了马达加斯加岛和尼亚加拉大瀑布等奇异景色。<br />
	&nbsp;</p>
<p>
	<img alt="" src="/uploads/allimg/c120524/133N42E3560-2cQ.jpg" /></p>
<p>
	语中字】<img border="0" src="/uploads/allimg/c120524/133N295542P-105L6.jpg" /> &#65279;</p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="word-wrap: break-word">
				</anchor>ftp://dy44:piaohua@dy44.piaohua.com:1668/飘花电影piaohua.com胜地BD中字1280高清经典纪录片.rmvb</anchor></td>
		</tr>
	</tbody>
</table>
<p>
	
	<p>
		&nbsp;</p>
	</anchor></p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120524/133N42E4260-3D42.jpg{/dede:field}
