<?php
$z[0]=Array("field","美女与野兽BD英国粤三语中英双字",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","美女与野兽BD英国粤三语中英双字1024/1280高清迅雷下载、免费下载，美女与野兽BD英国粤三语中英双字1024/1280高清Gvod高清在线播放，剧情介绍等。",73,253);
$z[1][4]['name']="description";
$z[2]=Array("field","美女与野兽BD英国粤三语中英双字1024/1280高清",255,336);
$z[2][4]['name']="title";
$z[3]=Array("field","",338,377);
$z[3][4]['name']="writer";
$z[4]=Array("field","",379,418);
$z[4][4]['name']="source";
$z[5]=Array("field","2012-04-09",420,470);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",472,509);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://3e:3e@d3.3edyy.com:121/【3E电影院www.eee4.org】美女与野兽.1024x576.英国粤三语.中英字幕.mkv\" target=\"_blank",511,662);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MOH0510-53264.jpg",664,747);
$z[8][4]['name']="litpic";

?>