{dede:field name='keywords'}康熙来了嘉宾周杰伦迅雷下载，免{/dede:field}
{dede:field name='description'}康熙来了嘉宾周杰伦迅雷下载、免费下载，康熙来了嘉宾周杰伦Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}康熙来了嘉宾周杰伦{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2006-08-27{/dede:field}
{dede:field name='body'}<p>康熙来了》取自蔡康永与小S徐熙娣名字的一个字而拼成。每晚收视率为1.2%-1.3%，每周吸引了超过500万观看人次，是台湾收视率最高有线电视台综艺节目。</p>
<h2>下载地址</h2>
<p>（直接可能无法下载，一律使用<a href="http://pstatic.xunlei.com/about/product/down_xl5.htm" target="_blank">迅雷下载</a>）
<table style="WIDTH: 296px; HEIGHT: 35px" cellspacing="0" cellpadding="0" width="296" border="0">
    <tbody>
        <tr>
            <td title="康熙来了嘉宾周杰伦">康熙来了嘉宾周杰伦 (2006-8-16)</td>
            <td title="容量：183MB">183MB</td>
            <td title="格式：RM">RM</td>
            <td title="请用迅雷下载"><a href="ftp://l4.tonepop.net/k/kxll_01.rm" target="_blank">下载</a></td>
        </tr>
    </tbody>
</table>
<br />有漏集自行补充地址，将下载地址末尾替换即可，如： <br />01.rmvb替换为02.rmvb；a.rmvb替换为b.rmvb 等</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O160X940-25030.jpg{/dede:field}
