<?php
$z[0]=Array("field","康熙来了嘉宾周杰伦迅雷下载，免",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","康熙来了嘉宾周杰伦迅雷下载、免费下载，康熙来了嘉宾周杰伦Gvod高清在线播放，剧情介绍等。",73,203);
$z[1][4]['name']="description";
$z[2]=Array("field","康熙来了嘉宾周杰伦",205,261);
$z[2][4]['name']="title";
$z[3]=Array("field","",263,302);
$z[3][4]['name']="writer";
$z[4]=Array("field","",304,343);
$z[4][4]['name']="source";
$z[5]=Array("field","2006-08-27",345,395);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>康熙来了》取自蔡康永与小S徐熙娣名字的一个字而拼成。每晚收视率为1.2%-1.3%，每周吸引了超过500万观看人次，是台湾收视率最高有线电视台综艺节目。</p>\r\n<h2>下载地址</h2>\r\n<p>（直接可能无法下载，一律使用<a href=\"http://pstatic.xunlei.com/about/product/down_xl5.htm\" target=\"_blank\">迅雷下载</a>）\r\n<table style=\"WIDTH: 296px; HEIGHT: 35px\" cellspacing=\"0\" cellpadding=\"0\" width=\"296\" border=\"0\">\r\n    <tbody>\r\n        <tr>\r\n            <td title=\"康熙来了嘉宾周杰伦\">康熙来了嘉宾周杰伦 (2006-8-16)</td>\r\n            <td title=\"容量：183MB\">183MB</td>\r\n            <td title=\"格式：RM\">RM</td>\r\n            <td title=\"请用迅雷下载\"><a href=\"ftp://l4.tonepop.net/k/kxll_01.rm\" target=\"_blank\">下载</a></td>\r\n        </tr>\r\n    </tbody>\r\n</table>\r\n<br />有漏集自行补充地址，将下载地址末尾替换即可，如： <br />01.rmvb替换为02.rmvb；a.rmvb替换为b.rmvb 等</p>",397,1282);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c120525/133O160X940-25030.jpg",1284,1368);
$z[7][4]['name']="litpic";

?>