{dede:field name='keywords'}望夫成龙国粤双语BD高清中字1280{/dede:field}
{dede:field name='description'}望夫成龙国粤双语BD高清中字1280迅雷下载、免费下载，望夫成龙国粤双语BD高清中字1280Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}望夫成龙国粤双语BD高清中字1280{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-02-15{/dede:field}
{dede:field name='body'}<p>
	◎中文片名：《望夫成龙》周星驰香港经典喜剧大片BD国粤语双语中字<br />
	◎英文片名：Love Is Love<br />
	◎出品年代：1990年<br />
	◎国家地区：中国香港<br />
	◎类　　别：爱情/剧情<br />
	◎对白语言：普通话<br />
	◎字　　幕：简体中文<br />
	◎文件格式：rmvb<br />
	◎文件大小：1CD 531M<br />
	◎视频大小：800 x 432/1280 &times; 720<br />
	◎片　　长：01:31:30<br />
	◎导　　演：梁小熊<br />
	◎演　　员：周星驰 吴君如 关秀媚<br />
	◎剧情简介：<br />
	<br />
	　　　乡间长大的石金水与村中酒楼的太子女吴带娣青梅竹马，私定终身。但遭娣父反对，二人私奔，搬到市区共同生活，因为金水工作勤奋受到上司NANCY赏识，加提拔，二人渐生情愫，终导致金水与带娣的婚姻面临破裂危机。带娣伤心欲绝，离家远去&hellip;&hellip;两年后，金水浪子回头寻找带娣，二人终在波折重重之后，再度携手共同努力新生活。</p>
<p>
	<img border="0" onload="attachimg(this, 'load')" onmouseout="function anonymous()&#13;&#10;{&#13;&#10;function anonymous()&#13;&#10;{&#13;&#10;attachimginfo(this, 'attach_105752', 0, event)&#13;&#10;}&#13;&#10;}" onmouseover="function anonymous()&#13;&#10;{&#13;&#10;function anonymous()&#13;&#10;{&#13;&#10;attachimginfo(this, 'attach_105752', 1);attachimg(this, 'mouseover')&#13;&#10;}&#13;&#10;}" src="http://pic.piaohua.com/0701pic/allimg/090102/1013510.jpg" /></p>
<p>
	【电影截图】：<br />
	<img onload="attachimg(this, 'load')" onmouseout="function anonymous()&#13;&#10;{&#13;&#10;function anonymous()&#13;&#10;{&#13;&#10;attachimginfo(this, 'attach_105753', 0, event)&#13;&#10;}&#13;&#10;}" onmouseover="function anonymous()&#13;&#10;{&#13;&#10;function anonymous()&#13;&#10;{&#13;&#10;attachimginfo(this, 'attach_105753', 1);attachimg(this, 'mouseover')&#13;&#10;}&#13;&#10;}" src="http://www.zaslike.com/files/wsfdbbboqhw4wcz6d9ey.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 640px; height: 360px; border-top: 0px solid; border-right: 0px solid" />&nbsp;<br />
	<img onload="attachimg(this, 'load')" onmouseout="function anonymous()&#13;&#10;{&#13;&#10;function anonymous()&#13;&#10;{&#13;&#10;attachimginfo(this, 'attach_105754', 0, event)&#13;&#10;}&#13;&#10;}" onmouseover="function anonymous()&#13;&#10;{&#13;&#10;function anonymous()&#13;&#10;{&#13;&#10;attachimginfo(this, 'attach_105754', 1);attachimg(this, 'mouseover')&#13;&#10;}&#13;&#10;}" src="http://www.zaslike.com/files/wjw2fo8otemwm465smxr.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 640px; height: 360px; border-top: 0px solid; border-right: 0px solid" />&nbsp;<br />
	<img onload="attachimg(this, 'load')" onmouseout="function anonymous()&#13;&#10;{&#13;&#10;function anonymous()&#13;&#10;{&#13;&#10;attachimginfo(this, 'attach_105755', 0, event)&#13;&#10;}&#13;&#10;}" onmouseover="function anonymous()&#13;&#10;{&#13;&#10;function anonymous()&#13;&#10;{&#13;&#10;attachimginfo(this, 'attach_105755', 1);attachimg(this, 'mouseover')&#13;&#10;}&#13;&#10;}" src="http://www.zaslike.com/files/izesdsndxt81h401jcpm.jpg" style="border-bottom: 0px solid; border-left: 0px solid; border-top: 0px solid; border-right: 0px solid" />&nbsp;<br />
	&nbsp;</p>
<p>
	&nbsp;</p>
<p>
	周星驰香港经典喜剧大片《望夫成龙》BD国粤语双语中字<img border="0" src="/templets/img/down.jpg" /></p>

<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy241:xiaobajie@222.187.221.241:2021/小八戒电影xiaobajie.com望夫成龙国粤双语高清中字1280.mkv" target="_blank">ftp://dy241:xiaobajie@222.187.221.241:2021/小八戒电影xiaobajie.com望夫成龙国粤双语高清中字1280.mkv</a></td>
		</tr>
	</tbody>
</table>

<p>
	周星驰香港经典喜剧大片《望夫成龙》DVD国语中字<img border="0" src="/templets/img/down.jpg" /></p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://e27:e27@dm.eee4.com:1216/[3E电影站www.eee4.com]望夫成龙DVD国语中字无水印.rmvb" target="_blank">ftp://e27:e27@dm.eee4.com:1216/[3E电影站www.eee4.com]望夫成龙DVD国语中字无水印.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O151D930-33M1.jpg{/dede:field}
