{dede:field name='keywords'}超级战舰HD高清版2012美国科幻战{/dede:field}
{dede:field name='description'}超级战舰HD高清版2012美国科幻战争迅雷下载、免费下载，超级战舰HD高清版2012美国科幻战争Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}超级战舰HD高清版2012美国科幻战争{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-21{/dede:field}
{dede:field name='body'}<p>
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120422/13/56643687201204221309352137957238357_006.jpg" /></p>
<p>
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120422/13/56643687201204221309352137957238357_004.jpg" /></p>
<p>
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120422/13/56643687201204221309352137957238357_005.jpg" /></p>
<p>
	片名: <a href="http://www.bluemv.com/movie/37370.html">超级战舰</a><br />
	导演: 彼得&middot;博格<br />
	编剧: Jon Hoeber / Erich Hoeber<br />
	主演: 连姆&middot;尼森 / 亚历山大&middot;斯卡斯加德 / 泰勒&middot;克奇 / 乔什&middot;平茨 / 布鲁克琳&middot;黛克 / 蕾哈娜 / 杰西&middot;普莱蒙 / 浅野忠信<br />
	类型: 动作 / 战争 / 科幻 / 惊悚<br />
	官方网站: <a href="http://www.bluemv.com">http://www.bluemv.com</a><br />
	制片国家/地区: 美国<br />
	语言: 英语<br />
	上映日期: 2012-04-11(香港/英国/法国) / 2012-04-18(中国大陆) / 2012-05-18(美国)<br />
	片长: 132分钟<br />
	又名: 超级战舰：异形海战(港) / 战舰</p>
<p>
	<br />
	剧情简介</p>
<p>
	　　故事灵感来自孩之宝同名畅销战棋游戏&ldquo;战舰攻防战&rdquo;， 电影讲述海军中尉Alex（泰勒&middot;克奇 Taylor Kitsch 饰）被上级派往美国飞弹驱逐舰 (USS John Paul Jones) 上履行职务，在一次海上演习时，舰队惊动了隐匿在太平洋深海的外星巨形母舰，来者不 善，人类为保卫地球，力阻浩劫，在海上与外星战舰展开殊死战斗。Alex联同未婚妻（布鲁克琳&middot;黛克 Brooklyn Decker 饰）、任职指挥官的兄长Stone（亚历山大&middot;斯卡斯加德 Alexander Skarsg?rd 饰）、海军士官队友兼武器专家Raikes（蕾哈娜 Rihanna 饰），以及舰队总司令Shane（连姆&middot;尼森 Liam Neeson 饰），率领一众海军舰队，尽力一搏，与来自外太空的外星战舰震撼开战。<br />
	　　《超级战舰》（Battleship）是孩之宝的一款经典玩具，是一种两人玩的桌面游戏，最初在20世纪10年代出现时用笔在纸上画一个表格就可以玩了，后来孩之宝将其发展成电子游戏。电影版由《全民超人汉考克》（Hancock）彼得&middot;伯格（Peter Berg）执导。据介绍，这部电影主要描写人类对抗外星人的故事，风格类似《第九区》（District 9），并且不会&ldquo;跟大潮&rdquo;采用3D摄影机拍摄。　　</p>
<p>
	<br />
	◎影片截图</p>
<p>
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120422/13/56643687201204221309352137957238357_003.jpg" /></p>
<p>
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120422/13/56643687201204221309352137957238357_002.jpg" /></p>
<p>
	&nbsp;<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120422/13/56643687201204221309352137957238357_000.jpg" /></p>
<p>
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120422/13/56643687201204221309352137957238357_001.jpg" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120510/23/56643687201205102325002076270746118_003.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 333px; border-top: 0px solid; border-right: 0px solid" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120510/23/56643687201205102325002076270746118_002.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 333px; border-top: 0px solid; border-right: 0px solid" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120510/23/56643687201205102325002076270746118_001.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 333px; border-top: 0px solid; border-right: 0px solid" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120510/23/56643687201205102325002076270746118_000.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 333px; border-top: 0px solid; border-right: 0px solid" /></p>
<p>
	<img alt="" src="http://img.album.pchome.net/48/32/32/45/1b9b39f0d908814e1060cb49e79e81af.mkv_snapshot_00" style="width: 600px; height: 320px" /></p>
<p>
	<img alt="" src="http://img.album.pchome.net/48/32/32/45/08c22e124be3caed94570ba7f75ccb23.mkv_snapshot_00" style="width: 600px; height: 320px" /></p>
<p>
	&nbsp;<img src="http://img170.poco.cn/mypoco/myphoto/20120514/14/56643687201205141432302145994298550_001.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 338px; border-top: 0px solid; border-right: 0px solid" /></p>
<p>
	&nbsp;<img src="http://img170.poco.cn/mypoco/myphoto/20120514/14/56643687201205141432302145994298550_002.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 338px; border-top: 0px solid; border-right: 0px solid" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.netftp//dy44:piaohua@dy44.piaohua.com:3125/" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3271/飘花电影piaohua.com超级战舰清晰TC中字.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3271/飘花电影piaohua.com超级战舰清晰TC中字.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3373/飘花电影piaohua.com超级战舰DVDscr国语配音.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3373/飘花电影piaohua.com超级战舰DVDscr国语配音.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3388/飘花电影piaohua.com超级战舰1024HD国语版.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3388/飘花电影piaohua.com超级战舰1024HD国语版.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3416/飘花电影piaohua.com超级战舰HD国语配音中字.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3416/飘花电影piaohua.com超级战舰HD国语配音中字.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3416/飘花电影piaohua.com超级战舰无水印HD1280修复版.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3416/飘花电影piaohua.com超级战舰无水印HD1280修复版.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3417/飘花电影piaohua.com超级战舰原声发音中英双字高清版.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3417/飘花电影piaohua.com超级战舰原声发音中英双字高清版.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1502G40-1J13.jpg{/dede:field}
