{dede:field name='keywords'}爱的逃兵HD高清迅雷下载，免费下{/dede:field}
{dede:field name='description'}爱的逃兵HD高清迅雷下载、免费下载，爱的逃兵HD高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}爱的逃兵HD高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-12-03{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img165.poco.cn/mypoco/myphoto/20111202/18/62564813201112021802471982128354432_000.jpg" style="width: 650px; height: 884px" /></p>
<p>
	◎译　　名　爱的逃兵&nbsp;<br />
	◎片　　名　Love Soldier of Fortune<br />
	◎年　　代　1988<br />
	◎地　　区　香港<br />
	◎类　　别　喜剧/爱情<br />
	◎语　　言　国语<br />
	◎字　　幕　中文<br />
	◎文件格式　HD-RMVB<br />
	◎视频尺寸　1280 x 720<br />
	◎片　　长　92 Min<br />
	◎导　　演　冯淬帆 Shui-Fan Fung<br />
	◎主　　演　谭咏麟 Alan *** .....<br />
	　　　　　　张曼玉 Maggie Cheung .....<br />
	　　　　　　冯淬帆 Shui-Fan Fung .....<br />
	　　　　　　苗侨伟 Michael Miu .....<br />
	　　　　　　陈百祥 Pak-cheung Chan .....<br />
	　　　　　　王晶 Jing Wong .....Wong<br />
	　　　　　　黎小田 Siu-Tin Lei<br />
	　　　　　　卢业瑂 Brenda Lo O</p>
<p>
	◎简　　介　<br />
	&nbsp;</p>
<p>
	　　高音楷（谭咏麟 饰）是在一名不懂音乐的钢琴调音师，洋貌俊俏，被公司同时CANDY（吴君如 饰）暗恋，主动向其大献殷勤，闹出不少笑话。然而高音楷为人正派，热爱音乐，只仰慕著名唱片骑师苏诗棣（张曼玉 饰）。媚欲作曲家林雪夫（苗侨伟 饰）生性风流，增想借苏在其家中访问时乘机占便宜，幸好被刚刚在林家调琴的高所搭救，二人自此相识。林为雪前耻在一个大型音乐会上作弄高，幸好高以其音乐天分专业知识力挽狂澜，因此苏对高更有好感。高搬回祖屋住，意外地与太叔公前著名音乐家高山流（冯淬帆 饰）的鬼魂成为知己，为了维持生计，太叔公便将自己的音乐作品交给高代为售卖，不想却一举成全了高，令其一夜之间成为名音乐家，更加博得美人芳心。然而他始终无法坦然面对这种用欺骗方式得来的名利和爱情，最后乃抛去面具，用真面目迎接挑战。&nbsp;&nbsp;<br />
	幕后制作：&nbsp;<br />
	&nbsp;</p>
<p>
	　　影片与诸多商业喜剧相比，文艺气息渐浓。虽说也加以一些诙谐的喜剧桥段丰富影片的戏剧性，更将八十年代的鬼片因素结合进来，但仍旧无法遮掩作品本身的温情气氛。本片是香港著名喜剧红人冯淬帆自己亲自导演，让人意外的是，这个看似疯癫的喜剧人物果真具备了如后来陈可辛一般的文艺家气质，将作品打磨得精精细细，令人或喜或伤、回味无穷，前半段象一般港产城市喜剧一样另人捧腹，后半段真情流露却如文艺剧一般让人哀怨连连，格调还真是跨度不小。谭咏麟以文艺青年的形象示人，一改其往昔笑闹的角色特点，除了精彩的演绎，他更是唱遍了片中全部歌曲，其中那点题的《半梦半醒之间》，则更是在随后流行大江南北，成为被广泛传唱的经典。</p>
<p>
	<img alt="" src="http://img165.poco.cn/mypoco/myphoto/20111202/21/62564813201112022121241991004592711_002.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img165.poco.cn/mypoco/myphoto/20111202/21/62564813201112022121241991004592711_001.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img165.poco.cn/mypoco/myphoto/20111202/21/62564813201112022121241991004592711_000.jpg" style="width: 720px; height: 405px" /></p>

<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="&#13;&#10;ftp://dy241:piaohua@dy241.piaohua.com:1012/飘花电影piaohua.com爱的逃兵HD国语中字1280高清.rmvb">ftp://dy241:piaohua@dy241.piaohua.com:1012/飘花电影piaohua.com爱的逃兵HD国语中字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O151633Z-2O51.jpg{/dede:field}
