<?php
$z[0]=Array("field","烽火岁月[HD国语中字1024x576高",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","烽火岁月[HD国语中字1024x576高清版]迅雷下载、免费下载，烽火岁月[HD国语中字1024x576高清版]Gvod高清在线播放，剧情介绍等。",72,234);
$z[1][4]['name']="description";
$z[2]=Array("field","烽火岁月[HD国语中字1024x576高清版]",236,308);
$z[2][4]['name']="title";
$z[3]=Array("field","",310,349);
$z[3][4]['name']="writer";
$z[4]=Array("field","",351,390);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-03-06",392,442);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",444,481);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://3e:3e@m1.3edyy.com:1395/【3E电影院www.3edyy.com】烽火岁月HD国语中字1024x576高清版.rmvb\" target=_blank>ftftp://3e:3e@m1.3edyy.com:1395/【3E电影院www.3edyy.com】烽火岁月HD国语中字1024x576高清版.rmvb</A></TD></TR></TBODY></TABLE></div><ul class=\"mmlist",483,777);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MP6025Z-25209.jpg",779,862);
$z[8][4]['name']="litpic";

?>