{dede:field name='keywords'}国家地理世界致命动物：太平洋HD{/dede:field}
{dede:field name='description'}国家地理世界致命动物：太平洋HD中字1024高清美国纪录片迅雷下载、免费下载，国家地理世界致命动物：太平洋HD中字1024高清美国纪录片Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}国家地理世界致命动物：太平洋HD中字1024高清美国纪录片{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-01-08{/dede:field}
{dede:field name='body'}<p>
	<img alt="" height="335" id="img_0.37002866024479824" src="/uploads/allimg/c120524/133N492N40-313E9.jpg" width="600" /><br />
	◎片　　名　National.Geographic.Worlds.Deadliest.Animals.Asia.Pacific<br />
	◎译　　名　国家地理.世界致命动物.太平洋<br />
	◎年　　代　2008<br />
	◎影片类型　纪录片<br />
	◎片　　长　47 Mins<br />
	◎国　　家　美国<br />
	◎对白语言　英语<br />
	◎编　　码　720P.HDTV-RMVB<br />
	◎视频尺寸　1024 x 576<br />
	◎文件大小　664MB<br />
	◎简　　介　<br />
	<br />
	　　亚洲是地球上面积最大，人口最稠密的洲陆。人类在这里与最惊人的动物争夺生存空间。西伯利亚和太平洋热带海域有强壮的大型掠食动物，亚洲草原和湿地上有古老有鳞生物，地面上有蛇，树上有狡猾的猴子，其中最让人佩服的是最大陆生食肉动物北极熊。本片将带领观众了解这些动物如何猎食和自卫。<br />
	<img alt="" height="337" id="img_0.3074267619403689" src="/uploads/allimg/c120524/133N492cG0-1W917.jpg" style="cursor: pointer" width="600" /><br />
	<img alt="" height="337" src="/uploads/allimg/c120524/133N49301010-1943N.jpg" style="cursor: pointer" width="600" /></p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:2551/飘花电影piaohua.com国家地理世界致命动物太平洋HD中字1024高清.rmvb</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120524/133N49301640-20IM.jpg{/dede:field}
