{dede:field name='keywords'}胸毛传DVD国语中字2011最新中国{/dede:field}
{dede:field name='description'}胸毛传DVD国语中字2011最新中国爆笑动画大片迅雷下载、免费下载，胸毛传DVD国语中字2011最新中国爆笑动画大片Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}胸毛传DVD国语中字2011最新中国爆笑动画大片{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-10-01{/dede:field}
{dede:field name='body'}<p>
	&nbsp;<img src="http://img165.poco.cn/mypoco/myphoto/20110930/23/56634212201109302339062298526477157_003.jpg" /></p>
<p>
	中文名称： 胸毛传<br />
	英文名称： Sternalia.Lin Legend<br />
	出品： 我叫MT团队<br />
	导演： 核桃<br />
	主演： 林熊猫 叫兽小星 卑鄙马维斯<br />
	片长： 90分钟</p>
<p>
	<br />
	剧情简介：</p>
<p>
	　　本片主要讲述林胸毛，一个普通的小人物在北京如何兼职一个服务员，如何学会与同事交流，如何在帝都生存。 　　&ldquo;大家好我叫林熊猫，你也可以叫俺林胸毛！&rdquo; 　　第一天来帝都看天安门的北漂却被黑车拉到了十三陵，确实给力。难怪小公共司机都对我们的&ldquo;胸毛&rdquo;佩服不已。不知道林胸毛在北京的求职生活会是神马个样子，或许就像剧中由红色部队组合演唱的《累》（引自唱片《中国火 I》）一样：&ldquo;我想坚强，也想倔强，可我没有勇气，意已成灰。光阴似流水，时间那么珍贵，今天你我依旧什么都不会&rdquo;。 　　&ldquo;胸毛&rdquo;年方十九，北漂族，家里蹲大学屋里系毕业，擅长成人漫画，帝都求职中，坐车要有后排大座，打票要看体重身高买两张，背包都要是个MT的，说句实话19岁的林胸毛确实除了吃，P也不会（MS绝技是甩脸）。第二天离开了十三陵再次坐上黑车来到一家制作动画片的小单位应聘，由于画的东东太少儿不宜（不利于青少年的成长= =~!），在老板的暴走下只好选择站门口当了保安。职场中的林胸毛处处碰壁，性格单纯，脑子缺根筋，反应迟钝，除了一张脸长得像臀部，似乎他做什么都是错的~~~ 　　林胸毛也有柔情，对家里的来电却不吐露出生活的艰苦，说一切都好；刚上班第一天因为没有住处只好睡在公司，其间林胸毛翻乱了老板的抽屉（发现了一张&ldquo;女王和五个男人&rdquo;的片子，窃喜之下一播放才发现是圣斗士~~~），老板同情他就将就让他住了一晚，当老板锁门离开后熊猫发现突然内急，却发现没地方大便。。。第二天，同事阿萌（卑鄙马维斯）发现饭盒里有屎，在汽水瓶里有尿。。。~~~（为了顶罪在阿蒙的质问下，胸毛兄很强悍的喝光了瓶中的液体= =~!）后来胸毛吃午饭时又阴差阳错地把大便忘在了饭店里，被东北老板操刀狂追！最后被罚他饭店义务帮工打工，原老板给他发薪。 　　阿萌怀恨在心，派好友&ldquo;叫兽&rdquo;半夜拦住他暴打并勒索走了一百多块钱~~~~~由于没有暂住证，在街头被巡警狂追~~~~~下雨夜为了避雨阴差阳错躲进了&ldquo;发廊&rdquo;（他以为是理发的= =~!）~~~~~送同事小塔回家却发现小塔姐姐就是发廊女~~~~~~ 　　就这样，在一幕幕很二的情节中，胸毛开始了他在北京的辛酸生活~~~~~~</p>
<p>
	<br />
	◎影片截图</p>
<p>
	&nbsp;&nbsp;<img src="http://img165.poco.cn/mypoco/myphoto/20110930/23/56634212201109302339062298526477157_002.jpg" /></p>
<p>
	&nbsp;<img src="http://img165.poco.cn/mypoco/myphoto/20110930/23/56634212201109302339062298526477157_001.jpg" /></p>
<p>
	&nbsp;<img src="http://img165.poco.cn/mypoco/myphoto/20110930/23/56634212201109302339062298526477157_000.jpg" /></p>
<p>
	[下载地址]： &nbsp;<img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" /></p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:1702/飘花电影piaohua.com胸毛传DVD国语中字.rmvb ">ftp://dy44:piaohua@dy44.piaohua.com:1702/飘花电影piaohua.com胸毛传DVD国语中字.rmvb </a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1C21O0-49C2.jpg{/dede:field}
