{dede:field name='keywords'}爱你九周半/九个半星期BD1280高{/dede:field}
{dede:field name='description'}爱你九周半/九个半星期BD1280高清迅雷下载、免费下载，爱你九周半/九个半星期BD1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}爱你九周半/九个半星期BD1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-03-03{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120302/23/62564813201203022349522689080211580_000.jpg" style="width: 650px" /></p>
<p>
	【影片原名】9 1/2 Weeks/nine onehalf weeks<br />
	【中文译名】爱你九周半/九个半星期<br />
	【出品公司】米高梅<br />
	【出品年代】1986 年<br />
	【上映日期】1986年2月14日 意大利<br />
	【影片级别】USA:R<br />
	【IMDB链接】<a href="http://www.imdb.com/title/tt0091635" target="_blank">http://www.imdb.com/title/tt0091635</a><br />
	【IMDB评分】5.5 (16105 votes)<br />
	<br />
	【国　　家】美国<br />
	【类　　别】爱情/剧情<br />
	【导　　演】阿德里安&middot;莱恩<br />
	【主　　演】米基&middot;洛克 Mickey Rourke &nbsp;....John<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;金&middot;贝辛格 Kim Basinger &nbsp;....Elizabeth<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;凯伦&middot;杨 Karen Young &nbsp;....Sue<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;玛格丽特&middot;惠顿 Margaret Whitton &nbsp;....Molly<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;David Margulies &nbsp;....Harvey<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;克里斯汀&middot;芭伦斯基 Christine Baranski &nbsp;....Thea<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;William De Acutis &nbsp;....Ted<br />
	【内容简介】<br />
	<br />
	　　刚与丈夫离婚的伊丽莎白（金&middot;贝辛格 Kim Basinger 饰）是一家画廊的助理，她结识了英俊潇洒的华尔街经理人约翰（米基&middot;洛克 Mickey Rourke 饰）。虽然约翰过分主动和自信的态度让伊丽莎白感到不安，但她却不能完全抵抗约翰的诱惑。他出人意料甚至带有一些疯狂的恋爱方式让她感到新奇和刺激，伊丽莎白发现已无法控制住自己被约翰用各种稀奇古怪的方式激发起的情欲。两人在钟楼上狂野的作爱，装扮成同性恋出入高级餐馆，在家具店的大床上当众调情，直到约翰招来妓女想要三个人共同云雨，伊丽莎白的忍受力终于到达极限&hellip;&hellip;<br />
	　　这部金&middot;贝辛格主演的影片是情色电影的典范之作。导演原本意图深远，想要探讨爱与性的界线，但最终流于形式，或者说影片的形式完全淹没了它的主题。人们津津乐道于那些令人眼花缭乱的场面和层出不穷的花样，而这个俗套的爱情故事，因为叙述的混乱和台词的牵强只得到一声叹息。<br />
	<br />
	【精彩片段赏析】<br />
	　　 &nbsp;镜头一：约翰发出了脱衣令，伊丽莎白顺从了。接着，约翰用白绸缎遮绷了伊丽莎白的双眼。背后的灯光透射出她宽松的半透明白色内衣中坚挺的乳峰。约翰将兴奋起来的伊丽莎白放倒在地面木板上，慢慢解开她的衣扣，摇荡着白色玻璃杯威士忌中的冰块，发出清脆诱惑的声响，拿出冰块将冰水滴入她激荡起伏的胸脯，伊丽莎白开始呻吟。约翰又将冰水滴向她的嘴唇、牙齿，用冰块磨擦她的下巴、脖子、嘴唇、乳头，伊丽莎白颤票着。冰块带着一条冰水划流过她的腹部，冰水流入伊丽莎白丰美的肚脐。最后，冰块在她白色内裤的边缘划拔，缓慢深入，伊丽莎白随着始终伴奏的钢琴乐音欢叫起来&hellip;&hellip;<br />
	　　镜头二：伊丽莎白裸身套着白色浴袍幽幽地走出来，约翰发出了闭眼令。坐在地面木板上，约翰用葡萄、樱桃、草莓、洋葱、辣椒、果冰、威士忌挑逗喂食她，在节奏畅快的广告歌声中，伊丽莎白表现着性感的嘴部动作，自己大口大口地倒入牛奶。约翰打开汽水喷射她，伊丽莎白狂叫着。最后，约翰将瓶中的蜂蜜源源挤向她伸长的鲜艳肉欲舌头上，用蜂蜜涂抹她欲望燃烧的全身，与伊丽莎白激吻&hellip;&hellip;<br />
	　　上述两组以广告特定拍摄手法表现的性爱动作的象征描写，比直接的性动作表现更性感，是世界电影史上最经典的情欲镜头之一，已经成为后来者一再仿效的范本。<br />
	&nbsp;<img alt="" src="http://img165.poco.cn/mypoco/myphoto/20120302/23/62564813201203022337133113103594353_003.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img165.poco.cn/mypoco/myphoto/20120302/23/62564813201203022337133113103594353_002.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img165.poco.cn/mypoco/myphoto/20120302/23/62564813201203022337133113103594353_001.jpg" style="width: 720px; height: 405px" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="&#13;&#10;ftp://dy125:piaohua@dy125.piaohua.com:7680/飘花电影piaohua.com爱你九周半BD中英双字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:7680/飘花电影piaohua.com爱你九周半BD中英双字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15Q3950-55048.jpg{/dede:field}
