{dede:field name='keywords'}殡葬师BD1280高清迅雷下载，免费{/dede:field}
{dede:field name='description'}殡葬师BD1280高清迅雷下载、免费下载，殡葬师BD1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}殡葬师BD1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-04-22{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120421/16/62564813201204211642113697279915132_001.jpg" style="width: 600px; height: 825px" /></p>
<p>
	◎译　　名　殡葬师<br />
	◎片　　名　The Mortician<br />
	◎年　　代　2011<br />
	◎国　　家　英国<br />
	◎类　　别　惊悚<br />
	◎语　　言　英语<br />
	◎IMDB评分 &nbsp;5.2/10 (90 votes)<br />
	◎IMDB链接 &nbsp;<a href="http://www.imdb.com/title/tt1211353/" target="_blank">http://www.imdb.com/title/tt1211353/</a><br />
	◎片　　长　82 mins<br />
	◎导　　演　盖瑞斯&middot;马克西维尔&middot;罗伯茨 Gareth Maxwell Roberts<br />
	◎主　　演　Method Man<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;E&middot;J&middot;波尼拉 E.J. Bonilla ....Noah<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;克鲁兹&middot;桑迪亚哥 Cruz Santiago ....Kane<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;爱德华&middot;福隆 Edward Furlong ....Petrovsky<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Wendell Pierce ....Clinger<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;达什&middot;米霍克 Dash Mihok ....Carver<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Lance E. Nichols ....Auggie<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Katie Knighten ....Chloe<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;安吉利&middot;赞巴拉娜 Angelic Zambrana ....Maria<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;David Jensen ....Officier Laurel<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Dana Fuchs ....Ava<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Randal Reeder ....Officer Hardy<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;朱迪&middot;马特 Judy Marte ....Jenny<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Ann Mckenzie ....Millie<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Blake Michael ....Street Kid<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Luis Da Silva Jr. ....Benny<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Odessa Sykes ....Busy Body<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Jordan Coleman ....Rico<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Anthony Michael Frederick ....SWAT Cop<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Cherie Thibodeaux ....young Millie<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Tiffany J. Billiot ....Missy<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Josh Gates ....Shackles<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Leticia Jimenez ....Luisa Ortiz<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Robert Douthat ....S.W.A.T. Officer<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Vernon Brooks ....Young Mortician<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Moe Bertran ....Sandy<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Kyrt Gates ....Junkie #1<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Idella Johnson ....Mortician&#39;s mama<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Michael &#39;Big 420&#39; Zielinski ....Alfonso<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Corey Nichols ....Junkie #2<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Christoff &#39;Chris Daddy&#39; Williams ....Chris<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Ray Born ....Fat &#39;Redneck&#39; Sherriff<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Michael Broussard ....G<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Austen Daliet ....Ava&#39;s Son<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Geraldine Glenn ....Mrs. Neebs (uncredited)<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Daniel Vincent ....Street Level Drug Dealer (uncredited)<br />
	<br />
	<br />
	<b>影片介绍</b><br />
	<br />
	　　影片是一部黑色城市生活寓言，在一片动荡落败之中，有一个人的生意很好，那就是名为&ldquo;the mortician（殡仪师）&rdquo;的主人公。正在假释期的诺亚成了他的助手，一天，一名年轻女人的尸体被送到，这意外地引起了诺亚的恐慌。the mortician注意到女人的身上纹有波提切利《维纳斯诞生》的纹身，这勾起了他对于母亲的童年的回忆 。<br />
	<br />
	<br />
	<b>幕后制作</b><br />
	<br />
	&nbsp; &nbsp; 影片投入仅为200万美元，但却使用了3D技术拍摄，与那些制造视觉奇观的商业大片不同，3D在这里用来呈现了美国社会最灰暗和丑陋的一面，而看过奥斯卡最佳影片提名的《冬天的骨头》的观众也会对摄影师Michael McDonough的风格有所了解。<br />
	&nbsp;<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120421/21/62564813201204212108215951897882233_008.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120421/21/62564813201204212108215951897882233_007.jpg" style="width: 720px; height: 405px" /></p>
<p>
	【下载地址】</p>
<table bgcolor="#0099cc" border="0" cellpadding="10" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.net" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy125:piaohua@dy125.piaohua.com:7878/飘花电影piaohua.com殉葬师BD中英双字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:7878/飘花电影piaohua.com殉葬师BD中英双字1280高清.rmvb</a></td>
		</tr>
		<tr>
		</tr>
	</tbody>
</table>
<br />{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1630B10-562A.jpg{/dede:field}
