{dede:field name='keywords'}看不见的战争/战争，你所看不到{/dede:field}
{dede:field name='description'}看不见的战争/战争，你所看不到的那面[DVD中字]迅雷下载、免费下载，看不见的战争/战争，你所看不到的那面[DVD中字]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}看不见的战争/战争，你所看不到的那面[DVD中字]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-03-10{/dede:field}
{dede:field name='body'}<P><IMG src="/uploads/allimg/c120524/133N4QN1Z-11P12.jpg"><BR><BR><BR>◎中 文 名　《看不见的战争/战争，你所看不到的那面》2010年英国最新获奖纪录片DVD中字<BR>◎英 文 名　The War You Don't See<BR>◎年　　代　2010<BR>◎国　　家　英国<BR>◎类　　别　纪录片<BR>◎语　　言　英语<BR>◎字　　幕　中文<BR>◎文件格式　XviD + MP3<BR>◎视频尺寸　640 x 352<BR>◎文件大小　1CD 384MB<BR>◎片　　长　94 Min<BR>◎导　　演　约翰·皮格尔 John Pilger<BR>◎主　　演　</P>
<P><BR>◎简　　介　</P>
<P>　　约翰·皮尔格导演。2010英国获奖纪录片。</P>
<P>　　电影从美军在伊拉克枪击路透社记者及误伤平民的一段视频开始，讲述了在美国参与的越南、伊拉克、阿富汗等战争中，官方媒体的报道总是有相当的倾向性。事实上，本片所展示的一些战地记者所获得的第一手资料，第一次让你了解到官媒所报道的战争背后的真相，这是一般人看不见的战争。</P>
<P><BR>　　英国记者约翰·皮尔格（John Pilger）成长於澳洲悉尼，目前定居英国伦敦。他是一位优秀的战地记者、作家与制片家，继电影The War On Democracy（民主之战）后，又一部揭露美国侵略军在伊拉克对平民百姓的屠杀暴行，并且谴责世界主流媒体的虚假报道。<BR><BR><BR></P>
<P>【电影截图】：<BR><BR></P><IMG src="/uploads/allimg/c120524/133N4QN5F-12W09.jpg">&nbsp;<BR><IMG src="/uploads/allimg/c120524/133N4QO140-1324T.jpg">&nbsp;<BR><IMG src="/uploads/allimg/c120524/133N4QOB0-144102.jpg">&nbsp;<BR><IMG src="/uploads/allimg/c120524/133N4QP1P-15HJ.jpg">&nbsp;<BR><IMG src="/uploads/allimg/c120524/133N4QPL0-1DR2.jpg">&nbsp;<BR><IMG src="/uploads/allimg/c120524/133N4QQ2F-1OM4.jpg"><BR><BR><BR><BR><BR>【dbank网盘高速下载地址】:<BR>2010年英国最新获奖纪录片《看不见的战争/战争，你所看不到的那面》DVD中字<BR><BR>2010年英国最新获奖纪录片《看不见的战争/战争，你所看不到的那面》DVD中字 [下载地址]：<IMG border=0 src="/uploads/allimg/c120524/133N2Z4FF-102231.jpg"><BR>
<TABLE style="BORDER-BOTTOM: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-RIGHT: #cccccc 1px dotted" border=0 cellSpacing=0 cellPadding=6 width="95%" align=center>
<TBODY>
<TR>
<TD style="WORD-WRAP: break-word" bgColor=#fdfddf>ftp://3e:3e@m3.3edyy.com:523/【3E看看www.3ekk.com】看不见的战争[DVD中字].rmvb</TD></TR></TBODY></TABLE>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120524/133N4QQ50-1V939.jpg{/dede:field}
