<?php
$z[0]=Array("field","喋血孤城/卫战/常德大血战[DVD国",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","喋血孤城/卫战/常德大血战[DVD国语中字]迅雷下载、免费下载，喋血孤城/卫战/常德大血战[DVD国语中字]Gvod高清在线播放，剧情介绍等。",73,241);
$z[1][4]['name']="description";
$z[2]=Array("field","喋血孤城/卫战/常德大血战[DVD国语中字]",243,318);
$z[2][4]['name']="title";
$z[3]=Array("field","",320,359);
$z[3][4]['name']="writer";
$z[4]=Array("field","",361,400);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-08-24",402,452);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",454,491);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://3e:3e@d8.3edyy.com:178/【3E电影院www.eee4.cc】喋血孤城DVD国语中字.rmvb\" target=_blank>ftftp://3e:3e@d8.3edyy.com:178/【3E电影院www.eee4.cc】喋血孤城DVD国语中字.rmvb</A></TD></TR></TBODY></TABLE></div><ul class=\"mmlist",493,755);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MP635E0-22W5.jpg",757,839);
$z[8][4]['name']="litpic";

?>