<?php
$z[0]=Array("field","不能说的秘密BD国语中字1024/128",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","不能说的秘密BD国语中字1024/1280高清迅雷下载、免费下载，不能说的秘密BD国语中字1024/1280高清Gvod高清在线播放，剧情介绍等。",73,237);
$z[1][4]['name']="description";
$z[2]=Array("field","不能说的秘密BD国语中字1024/1280高清",239,312);
$z[2][4]['name']="title";
$z[3]=Array("field","",314,353);
$z[3][4]['name']="writer";
$z[4]=Array("field","",355,394);
$z[4][4]['name']="source";
$z[5]=Array("field","2012-01-27",396,446);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",448,485);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://3e:3e@d8.3edyy.com:168/【3E电影院www.eee4.cc】不能说的秘密BD中字1024x576高清版.rmvb\" target=\"_blank",487,631);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MOS54Z-1K92.jpg",633,714);
$z[8][4]['name']="litpic";

?>