{dede:field name='keywords'}觉醒BD1280高清迅雷下载，免费下{/dede:field}
{dede:field name='description'}觉醒BD1280高清迅雷下载、免费下载，觉醒BD1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}觉醒BD1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-21{/dede:field}
{dede:field name='body'}<p>
	<img border="0" src="http://img165.poco.cn/mypoco/myphoto/20120312/22/56643687201203122254331293287048374_004.jpg" /></p>
<p>
	◎译　　名　觉醒/搜灵(港)/灵动档案(台)<br />
	◎片　　名　The Awakening<br />
	◎年　　代　2011<br />
	◎国　　家　英国<br />
	◎类　　别　恐怖/惊悚<br />
	◎语　　言　英语<br />
	◎字　　幕　中字<br />
	◎IMDB评分&nbsp;&nbsp; 6.7/10 (1,387 votes)<br />
	◎IMDB链接 <a href="http://www.qqtmb.com/">http://www.qqtmb.com/</a><br />
	◎文件格式　x264 + DTS<br />
	◎视频尺寸　1280 x 720<br />
	◎文件大小　1 DVD<br />
	◎片　　长　01:46:42<br />
	◎官方网站：<a href="http://www.bluemv.com" title="电影下载">http://www.bluemv.com</a><br />
	◎导　　演　尼克&middot;墨菲 Nick Murphy<br />
	◎主　　演　丽贝卡&middot;豪尔 Rebecca Hall ....Florence Cathcart<br />
	　　　　　　多米尼克&middot;威斯特 Dominic West ....Robert Mallory<br />
	　　　　　　伊梅尔达&middot;斯汤顿 Imelda Staunton ....Maud Hill<br />
	　　　　　　Lucy Cohu ....Constance Strickland<br />
	　　　　　　约翰&middot;斯拉普内尔 John Shrapnel ....Reverend Hugh Purslow<br />
	　　　　　　Diana Kent ....Harriet Cathcart<br />
	　　　　　　Richard Durden ....Alexander Cathcart<br />
	　　　　　　Alfie Field ....Victor Parry<br />
	　　　　　　Tilly Vosburgh ....Vera Flood<br />
	　　　　　　Ian Hanmore ....Albert Flood<br />
	　　　　　　Cal Macaninch ....Freddie Strickland<br />
	　　　　　　艾萨克&middot;赫普斯戴德-怀特 Isaac Hempstead-Wright ....Tom<br />
	　　　　　　Anastasia Hille ....Katherine Vandermeer<br />
	　　　　　　Andrew Havill ....George Vandermeer<br />
	　　　　　　约瑟夫&middot;马勒 Joseph Mawle ....Edward Judd<br />
	　　　　　　邵恩&middot;杜里 Shaun Dooley ....Malcolm McNair<br />
	　　　　　　Nicolas Amer ....Edgar Hirstwit<br />
	　　　　　　Steven Cree ....Sergeant Paul Evans<br />
	　　　　　　Ben Greaves-Neil ....Child Impostor<br />
	　　　　　　Sidney Johnston ....John Franklin<br />
	　　　　　　Charlie Callaghan ....Chris Hartley<br />
	　　　　　　Spike White ....Alistair Howell<br />
	　　　　　　James Kirkham ....William Ramsbottom<br />
	　　　　　　Felix Soper ....Julian Dowden<br />
	　　　　　　Daniel Pirrie ....Captain Mills<br />
	　　　　　　Ewan Andrew Walker ....McGorrian<br />
	　　　　　　Andy Callaghan ....Arresting Police Officer<br />
	　　　　　　Andrew Foster ....Removal Man<br />
	　　　　　　Katie Hart ....Katie Forbes<br />
	　　　　　　Adam Thomas Wright ....Tebbitts<br />
	　　　　　　Neil Broome ....School Master (uncredited)<br />
	　　　　　　Terry Swoffer ....The gardener (uncredited)<br />
	　　　　　　Sarah Weldon ....Passerby (uncredited)<br />
	<br />
	◎简　　介<br />
	<b>剧情</b><br />
	　　一所男子寄宿学校学校里闹鬼，科学家弗洛伦斯受命前来揭开事实真相，但她调查到的的每一件事情都指向一个出乎所有人意料的结果。<br />
	<b>一句话评论</b><br />
	扭曲阴暗却不失大气。<br />
	&mdash;&mdash;好莱坞报道<br />
	毛骨悚然，引人入胜的鬼故事。<br />
	&mdash;&mdash;GQ<br />
	很棒的鬼屋故事，丽贝卡&middot;豪尔的表演令人着迷。<br />
	&mdash;&mdash;每日电讯报<br />
	制作精良毫不廉价，并且有着一众演员特别是丽贝卡&middot;豪尔的精彩表演，但对于已经被拍烂了的鬼故事类型来说没有太多新意。<br />
	&mdash;&mdash;《帝国》<br />
	诡异、吓人，尽管有些老套，但凭借着出色的视觉特效以及一战后那股股悲伤沉重的时代感、挥之不去的模棱两可性，这些都让它比一般的同类影片高出不少。<br />
	&mdash;&mdash;《完全电影》<br />
	<b>幕后制作</b><br />
	　　电影将故事背景设定在1921年，那时的英国上下还笼罩着一战失败和死伤无数的悲痛中。现代科学持续快速发展，而宗教信仰和19世纪的唯心论日益被有教养的现代社会所排斥。有太多的伤痛需要抚平，而传统的慰藉方法却遭到了无情的质疑。影片可以归类成英国传统鬼怪传说中关于母亲和孩子的故事，在与世隔绝的乡村背景下，从心理学和理性分析解除人们的恐惧。制片人的David Thompson说，&ldquo;这是一个非常吸引人，原创性很强的剧本，我们都为这将成为<a href="http://www.nod32jihuoma.cn/virus/fangchenmi.html" style="color: rgb(0, 0, 0); text-decoration: none;">身份证号码大全</a>尼克&bull;墨菲的电影处女作而感到激动。他是一位非常杰出的导演，对电影有着非常敏锐的洞察力。&rdquo;<br />
	　　导演尼克&bull;墨菲在英国电视圈小有名气，他执导了多部广受好评的剧集，如2008年的《远古入侵（Primeval）》，以及2009荣获英国电影学院奖的战争剧集《占领（Occupation）》。影片的剧本由墨菲和史蒂芬&bull;沃尔克共同编写，史蒂芬&bull;沃尔克不久前刚刚结束了惊悚连续剧《下一站天国（Afterlife）》的剧本创作。墨菲在片中加入了许多视觉上和心理上的小细节，如弗洛伦斯的装备、相机、录音机、绊网以及火药等，她的烟盒上刻的是别人的名字缩写，表明她对这个人<a href="http://www.2kaba.com/" style="color: rgb(0, 0, 0); text-decoration: none;">绿色软件</a>难以释怀；那个看似平常却很诡异的玩具屋，里面的人物根据弗洛伦斯的一举一动而移动。另外，片中还有对那个年代大男子主义的暗示，以及对战争的深刻理解。<br />
	　　<b>丽贝卡&bull;豪尔：全新的角色 情绪的挑战</b><br />
	　　丽贝卡&bull;豪尔的父亲是英国戏剧导演Sir Peter Hall，母亲是歌剧演员，天生丽质加上从小的家庭熏陶，她在20多岁就开始崭露头角，事业稳步上升，当然这也与她谨慎选择接拍的角色有关系。本片是她第一次在电影中担纲主角。豪尔坦言，有机会当主角是她接拍本片的初衷，她说，&ldquo;我知道这个理由会显得我很肤浅，但是我真的非常希望能够从头到尾完成一部电影。&rdquo;但是由于此前饰演太多安静温柔的角色，所以这次她想接一个&ldquo;又跑又叫、可以挑战身体和情绪极限的角色。&rdquo;<br />
	　　被问到她是否会想象下角色的长相、装扮以及办事风格等时，她表示，其实剧本中对人物的衣着打扮头发长短等这些的描述都非常详细，完全不需要她去过多地考虑。她说，弗洛伦斯这个角色非常具有挑战性，&ldquo;因为人物和故事都非常复杂，还需要从多个层面去表现，拍片时我必须非常清楚自己目前是处在哪个层面。&rdquo; 她认为<a href="http://www.dailiv.com/" style="color: rgb(0, 0, 0); text-decoration: none;">在线代理</a>吸引自己的是女主角经历了一个非常大的转折这点，<br />
	　　虽然是惊悚片，但是她说拍片时完全不害怕，因为尽管影片中表现出来的学校很阴森恐怖，但是实际情况是，片场围着一堆人，会时不时问她感觉怎么样，要不要喝水之类的，完全没有紧张恐怖的气氛。不过对于鬼魂一说，她说自己也没有遇到，所以也不能确定这些事情是否存在。<br />
	　　<b>多面的多米尼克&bull;威斯特</b><br />
	　　他是迷人的新闻主播、莎士比亚笔下恶棍满盈的坏蛋以及英国史上最臭名昭著的连环杀手，很少有演员能像多米尼克&bull;威斯特一样在本年度有着如此的好运气，他先后出演了被称作英国版《广告狂人》的连续剧《演播时刻》以及连续剧《Appropriate Adult》。<br />
	　　多米尼克表示，自己其实不太容易被惊悚片吓到，小时候看<a href="http://www.qqtmb.com/" style="color: rgb(0, 0, 0); text-decoration: none;">个性签名</a>的《电锯惊魂》是他认为很可怕的一部，而再到后来，类似猛鬼街一类的鬼片，他认为其实不可怕，&ldquo;我一直很看好电影《黑暗侵袭》，因为我曾经和该片导演Neil Marshall合作过，但是片中的怪物让整个影片掉价了。不过我确实被电影《灵异孤儿院》吓坏了，非常恐怖。《觉醒》其实在某种程度上很像《灵异孤儿院》，因为故事都是发生在学校，孩子们身上，这往往是最吓人的元素。&rdquo;</p>
<p>
	&nbsp;<img src="http://img165.poco.cn/mypoco/myphoto/20120312/22/56643687201203122254331293287048374_003.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 338px; border-top: 0px solid; border-right: 0px solid" /></p>
<p>
	&nbsp;<img src="http://img165.poco.cn/mypoco/myphoto/20120312/22/56643687201203122254331293287048374_002.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 338px; border-top: 0px solid; border-right: 0px solid" /></p>
<p>
	<img src="http://img165.poco.cn/mypoco/myphoto/20120312/22/56643687201203122254331293287048374_001.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 338px; border-top: 0px solid; border-right: 0px solid" /></p>
<p>
	<img src="http://img165.poco.cn/mypoco/myphoto/20120312/22/56643687201203122254331293287048374_000.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 338px; border-top: 0px solid; border-right: 0px solid" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3000/飘花电影piaohua.com灵动档案1024版BD中英双字.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3000/飘花电影piaohua.com灵动档案1024版BD中英双字.rmvb</a></td>
		</tr>
	</tbody>
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy125:piaohua@dy125.piaohua.com:7746/飘花电影piaohua.com觉醒BD中字1280高清.rmvb">ftpftp://dy125:piaohua@dy125.piaohua.com:7746/飘花电影piaohua.com觉醒BD中字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1645a60-3N21.jpg{/dede:field}
