<?php
$z[0]=Array("field","TVB《美女厨房》第四集迅雷下载",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","TVB《美女厨房》第四集迅雷下载、免费下载，TVB《美女厨房》第四集Gvod高清在线播放，剧情介绍等。",72,208);
$z[1][4]['name']="description";
$z[2]=Array("field","TVB《美女厨房》第四集",210,269);
$z[2][4]['name']="title";
$z[3]=Array("field","",271,310);
$z[3][4]['name']="writer";
$z[4]=Array("field","",312,351);
$z[4][4]['name']="source";
$z[5]=Array("field","2006-08-27",353,403);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p style=\"WORD-BREAK: break-all\">香港/[HK_TVB][美女厨房] <br /><br />由郑中基、谭咏麟还有梁汉文主持的综艺节日《美女厨房》每期来的都是娱乐界叫得上名儿的美女,观众们挤破头也想参加</p>\r\n<h2>下载地址</h2>\r\n<p style=\"WORD-BREAK: break-all\">（直接可能无法下载，一律使用<a href=\"http://pstatic.xunlei.com/about/product/down_xl5.htm\" target=\"_blank\">迅雷下载</a>）\r\n<table style=\"WIDTH: 325px; HEIGHT: 20px\" cellspacing=\"0\" cellpadding=\"0\" width=\"325\" border=\"0\">\r\n    <tbody>\r\n        <tr>\r\n            <td title=\"美女厨房 第四集\">美女厨房 第四集 (2006-8-26)</td>\r\n            <td title=\"容量：218MB\">218MB</td>\r\n            <td title=\"格式：RM\">RM</td>\r\n            <td title=\"请用迅雷下载\"><a href=\"http://221.7.152.66:84/cnc/科教战争综艺/综艺片/港台/美女厨房/美女厨房4.rm\" target=\"_blank\">下载</a></td>\r\n        </tr>\r\n    </tbody>\r\n</table>\r\n<br />有漏集自行补充地址，将下载地址末尾替换即可，如： <br />01.rmvb替换为02.rmvb；a.rmvb替换为b.rmvb 等</p>",405,1388);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c120525/133O160VB0-1K15.jpg",1390,1472);
$z[7][4]['name']="litpic";

?>