{dede:field name='keywords'}天才雷普利BD中英双字BD中英双字{/dede:field}
{dede:field name='description'}天才雷普利BD中英双字BD中英双字1024/1280高清经典爱情剧情迅雷下载、免费下载，天才雷普利BD中英双字BD中英双字1024/1280高清经典爱情剧情Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}天才雷普利BD中英双字BD中英双字1024/1280高清经典爱情剧情{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-02-15{/dede:field}
{dede:field name='body'}<p>
	<img alt="" border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://hdroad.org/bitbucket/month_1102/20110205233449512662.jpg');" src="http://hdroad.org/bitbucket/month_1102/20110205233449512662.jpg" /></p>
<p>
	◎译　　名　天才雷普利/天才聂利/心计<br />
	◎片　　名　The Talented Mr. Ripley<br />
	◎年　　代　1999<br />
	◎国　　家　美国<br />
	◎类　　别　爱情/惊悚/剧情/悬疑/犯罪&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br />
	◎语　　言　英语<br />
	◎字　　幕　中英双字<br />
	◎IMDB评分 7.3/10（65,723 votes）<br />
	◎文件格式　BD-RMVB<br />
	◎视频尺寸　1024 x 576<br />
	◎文件大小　1CD<br />
	◎片　　长　139Mins<br />
	◎导　　演　安东尼&middot;明格拉 Anthony Minghella&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br />
	◎主　　演　马特&middot;达蒙 Matt Damon&nbsp; ....Tom Ripley<br />
	　　　　　　裘德&middot;洛 Jude Law&nbsp; ....Dickie Greenleaf<br />
	　　　　　　格温妮丝&middot;帕特洛 Gwyneth Paltrow&nbsp; ....Marge Sherwood<br />
	　　　　　　凯特&middot;布兰切特 Cate Blanchett&nbsp; ....Meredith Logue<br />
	　　　　　　菲利普&middot;塞默&middot;霍夫曼 Philip Seymour Hoffman&nbsp; ....Freddie Miles<br />
	　　　　　　杰克&middot;达文波特 Jack Davenport&nbsp; ....Peter Smith-Kingsley<br />
	　　　　　　塞吉奥&middot;鲁比尼 Sergio Rubini&nbsp; ....Inspector Roverini<br />
	　　　　　　菲利浦&middot;贝克&middot;霍尔 Philip Baker Hall&nbsp; ....Alvin MacCarron<br />
	　　　　　　史蒂芬妮雅&middot;若卡 Stefania Rocca&nbsp; ....Silvana<br />
	　　　　　　贝佩&middot;费奥雷罗 Beppe Fiorello&nbsp; ....Silvana&#39;s Fianc&eacute;<br />
	　　　　　　詹姆斯&middot;瑞布霍恩 James Rebhorn&nbsp; ....Herbert Greenleaf<br />
	　　　　　　西莉亚&middot;韦斯顿 Celia Weston&nbsp; ....Aunt Joan<br />
	　　　　　　Fiorello&nbsp; ....Fausto (as Rosario Fiorello)<br />
	　　　　　　Ivano Marescotti&nbsp; ....Colonnello Verrecchia<br />
	　　　　　　Anna Longhi&nbsp; ....Signora Buffi<br />
	　　　　　　Alessandro Fabrizi&nbsp; ....Sergeant Baggio<br />
	　　　　　　Lisa Eichhorn&nbsp; ....Emily Greenleaf<br />
	　　　　　　Gretchen Egolf&nbsp; ....Fran<br />
	　　　　　　Jack Willis&nbsp; ....Greenleaf Chaffeur<br />
	　　　　　　Frederick Alexander Bosche&nbsp; ....Fran&#39;s Boyfriend</p>
<p>
	◎简　　介</p>
<p>
	&nbsp;&nbsp;&nbsp; 50年代后期的美国青年汤姆&middot;瑞普利（马特&middot;达蒙）一直向往着能在阳光普照、碧水蓝天的意大利过着年轻而无忧无虑的田园牧歌般的生活。而这正是狄克&middot;格林利夫（裘德&middot;洛）所拥有的。狄克的父亲，一个富有的造船商请里普雷去把他的浪荡子带回美国。</p>
<p>
	&nbsp;&nbsp;&nbsp; 瑞普利受狄克的父亲之托，去意大利把这位大财团继承人，风流的大少爷狄克找回美国。但当瑞普利到了意大利，找到狄克之后，他的初衷完全被这个充满魅力的人改变了。他迷恋这里，迷恋这个年轻人，迷恋这种生活，他渴望变成他在狄克警觉他的用意之后，跟他摊牌了，瑞普利不能承受这种突变和刺激，用船桨击杀了狄克。而后，他离开狄克和他女朋友居住的那个小镇，来到罗马，以狄克的身份混迹于上层社会，但不久，接连有人威胁到假狄克的存在，无法，瑞普利只能接连杀掉这些人。直到最后，在命运的&ldquo;巧合&rdquo;和他自己的&ldquo;努力&rdquo;之下，几乎所有的人都被他蒙混了过去，连狄克的父亲都把财产送给了他。他终于成为了一个真正的&ldquo;贵人&rdquo;。&nbsp;<br />
	　&nbsp;<br />
	　　 《天才瑞普利》改编自女作家帕翠希娅-海丝米斯写于1955年的同名小说，法国导演伦-克莱门特曾于1960年拍摄过一部以瑞普利系列小说为蓝本的《紫色正午》，银色情侣阿兰-德隆与罗密-史奈德的联袂出演曾使这部法国版的&ldquo;瑞普利传奇&rdquo;在当时名噪一时。曾凭《英国病人》夺得九项奥斯卡奖项的大导演安东尼-明格拉在这部美国版的&ldquo;瑞普利传奇&rdquo;中，准确地传达出小说原着中&ldquo;在存在主义与爵士乐盛行的时代背景下，一个孤独无依的人试图改变自己、步入另一社会阶层&rdquo;的主题以及小说着力渲染的&ldquo;幽闭恐怖、非理性&rdquo;的故事氛围。</p>
<p>
	&nbsp; 本片曾在1960年拍成法国片《阳光普照》（Purple Noon）一片，乃英俊小生阿兰&middot;德龙的成名作。在旧版中，导演以一种欧洲式的奔放来呈现青春的邪恶因子，节奏感比较轻灵跳跃；新版较重视情节的堆砌，风格比较刻意和修饰。该片充分展现了导演明格拉的伯乐天才，他启用该片四位主演时，他们均为无名小卒；但影片上映时他们的星云已如日中天。</p>
<p>
	◎制&nbsp;&nbsp;&nbsp; 作</p>
<p>
	&nbsp;&nbsp;&nbsp; 派拉蒙电影公司和米拉麦克斯电影公司似乎是冲着奥斯卡金像奖去的。导演是96年奥斯卡丰收片《英国病人》的安东尼&middot;明格拉，演员阵容中马特&middot;大蒙、格温妮丝&middot;帕尔特洛还有凯特&middot;布兰切特，都是金像奖得主。剧本是由明格拉改编自帕特里西亚&middot;海斯密斯1955年风靡一时的悬疑小说。</p>
<p>
	　　影片的拍摄场景是在罗马，这使得安东尼&middot;明格拉能够捕捉到足够的充满灵感与启示的镜头。这样的镜头在他的《英国病人》中已经备受喜爱，但也造成了明格拉的一个缺陷，就是他的电影有时过于冗长和缓慢。不过这个故事中的惊悚要素有望弥补缺陷，使影片看上去节奏更快，更诱人。</p>
<p>
	<img alt="" border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://img.album.pchome.net/54/83/81/91/998e89fe2c1742bfcee205663b9eceeb.jpg');" src="http://img.album.pchome.net/54/83/81/91/998e89fe2c1742bfcee205663b9eceeb.jpg" /></p>
<p>
	<img alt="" border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://img.album.pchome.net/54/83/81/91/7dd7698a2d24a7be6c58c94041b9c6f3.jpg');" src="http://img.album.pchome.net/54/83/81/91/7dd7698a2d24a7be6c58c94041b9c6f3.jpg" /></p>
<p>
	[下载地址]：<img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" /> </p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="word-wrap: break-word">
				<a href="ftp://dy172:piaohua@dy172.piaohua.com:208/飘花电影piaohua.com天才雷普利BD中英双字1024高清.rmvb">&nbsp;</a><a href="ftp://dy172:piaohua@dy172.piaohua.com:208/飘花电影piaohua.com天才雷普利BD中英双字1024高清.rmvb">ftp://dy172:piaohua@dy172.piaohua.com:208/飘花电影piaohua.com天才雷普利BD中英双字1024高清.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="word-wrap: break-word">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2819/飘花电影piaohua.com天才雷普利BD中英双字1280高清.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:2819/飘花电影piaohua.com天才雷普利BD中英双字1280高清.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2819/飘花电影piaohua.com天才雷普利BD中英双字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15P5P-15310.jpg{/dede:field}
