{dede:field name='keywords'}蝙蝠侠Ⅱ：蝙蝠侠归来高清BD1280{/dede:field}
{dede:field name='description'}蝙蝠侠Ⅱ：蝙蝠侠归来高清BD1280双语配音迅雷下载、免费下载，蝙蝠侠Ⅱ：蝙蝠侠归来高清BD1280双语配音Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}蝙蝠侠Ⅱ：蝙蝠侠归来高清BD1280双语配音{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-01-29{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120129/01/17870980201201290138023474160033491_000.jpg" style="width: 450px; height: 579px" /></p>
<p>
	◎译　　名　蝙蝠侠归来/蝙蝠侠再战风云/蝙蝠侠重现江湖/蝙蝠侠大显神威/蝙蝠侠再现江湖<br />
	◎片　　名　Batman Returns<br />
	◎年　　代　1992<br />
	◎国　　家　美国/英国<br />
	◎类　　别　动作/惊悚/犯罪<br />
	◎语　　言　英语<br />
	◎字　　幕　中英双字<br />
	◎IMDB评分 6.9/10 (62,957 votes)<br />
	◎视频尺寸　1280 x 720<br />
	◎文件大小　1CD<br />
	◎导　　演　蒂姆&middot;波顿 Tim Burton<br />
	◎主　　演　米歇尔&middot;菲佛 Michelle Pfeiffer ....Catwoman/Selina Kyle<br />
	　　　　　　克里斯托弗&middot;沃肯 Christopher Walken ....Max Shreck<br />
	　　　　　　迈克尔&middot;基顿 Michael Keaton ....Batman/Bruce Wayne<br />
	　　　　　　丹尼&middot;德维托 Danny DeVito ....Penguin/Oswald Cobblepot<br />
	　　　　　　道格&middot;琼斯 Doug Jones ....Thin Clown<br />
	　　　　　　西恩&middot;瓦兰 Sean Whalen ....Paperboy (as Sean M. Whalen)<br />
	　　　　　　Michael Gough ....Alfred Pennyworth<br />
	　　　　　　迈克尔&middot;墨菲 Michael Murphy ....The Mayor<br />
	　　　　　　Cristi Conaway ....Ice Princess<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Andrew Bryniarski ....Charles &#39;Chip&#39; Shreck<br />
	　　　　　　Pat Hingle ....Commissioner James Gordon<br />
	　　　　　　文森特&middot;斯卡维利 Vincent Schiavelli ....Organ Grinder<br />
	　　　　　　Rosie O&#39;Connor ....Adorable Little Girl<br />
	　　　　　　Erik Onate ....Aggressive Reporter (as Erik O?ate)<br />
	　　　　　　Joey DePinto ....Shreck Security Guard<br />
	　　　　　　史蒂文&middot;布里尔 Steven Brill ....Gothamite #1<br />
	◎简　　介　<br />
	　　打败了小丑之后，蝙蝠侠又要面对乖戾残疾的企鹅。企鹅因为自幼被父母抛弃，心生怨恨，决定回到哥谭市杀死所有的长子<br />
	，得到整个哥谭市社会的认可，并迫使邪恶的商人马克斯帮助他成为哥谭市市长。两人都试图对付蝙蝠侠。然而，马克斯的女秘<br />
	书西莉娅&middot;凯勒由于洞悉他们的阴谋而遭到谋害，变成了具有和蝙蝠侠同样能力的猫女，成为蝙蝠侠另一强大的对手。在蝙蝠侠<br />
	机智的谋略下，终于战胜了企鹅和猫女的围攻，再度化险为夷拯救了哥谭市。<br />
	　　遭父母遗弃的男婴奥斯瓦尔德长大成人后带着复仇的心理重回纽约为非作歹。野心家马克斯的阴谋被女秘书塞利娜识破。为<br />
	灭口，马克斯被塞利娜推下摩天楼，但塞利娜没有死，变成猫女。马克斯与奥斯瓦尔德互相利用：马克斯帮助奥斯瓦尔德竞选市<br />
	长，奥斯瓦尔德强行通过马克斯建造电厂的计划。他们的对手布鲁斯实际上就是蝙蝠侠。布鲁斯和塞利娜共进晚餐时，奥斯瓦尔<br />
	德在电视上栽赃蝙蝠侠绑架了美女，使他们相互产生猜忌。奥斯瓦尔德趁机指使一群群企鹅运送导弹，企图炸毁纽约。蝙蝠侠诱<br />
	使这些企鹅捣毁了它们主人的巢穴，奥斯瓦尔德落得个作法自毙的下场。<br />
	　　蝙蝠侠韦恩在这一集中的对手是绰号企鹅王的奥斯瓦尔德。心理极度扭曲的企鹅王仇视人类，一心想当上纽约市长，方便他<br />
	的作恶。塞利娜是个美丽女郎，但在穿上猫服后就变成神通广大、亦正亦邪的猫女。猫女在邂逅蝙蝠侠后对他一往情深，为此不<br />
	惜与企鹅王为敌。最后，企鹅大军正式进攻纽约市夺取政权，蝙蝠侠在猫女的协助下打败了罪恶的企鹅王。<br />
	&nbsp;</p>
<p>
	一句话评论<br />
	The Bat, the Cat, the Penguin<br />
	Returns June 19<br />
	&nbsp;</p>
<p>
	幕后制作<br />
	本片是蝙蝠侠系列片的第二集，与第一集风格相同。演员阵容强大，表演出色。</p>

<p>
	<img alt="" border="0" height="324" src="http://img2081.poco.cn/mypoco/myphoto/20120129/01/17870980201201290128554070181973207_001.jpg" width="574" /><img alt="" border="0" src="http://img2081.poco.cn/mypoco/myphoto/20120129/01/17870980201201290128554070181973207_000.jpg" /></p>

<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="&#13;&#10;ftp://dy241:xiaobajie@dy241.piaohua.com:2053/小八戒电影xiaobajie.com蝙蝠侠Ⅱ蝙蝠侠归来中英配音双语字幕高请1280.mkv">ftp://dy241:xiaobajie@dy241.piaohua.com:2053/小八戒电影xiaobajie.com蝙蝠侠Ⅱ蝙蝠侠归来中英配音双语字幕高请1280.mkv </a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O159143F-3A40.jpg{/dede:field}
