{dede:field name='keywords'}三只猴子BD1280高清迅雷下载，免{/dede:field}
{dede:field name='description'}三只猴子BD1280高清迅雷下载、免费下载，三只猴子BD1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}三只猴子BD1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-22{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img.album.pchome.net/54/68/29/09/96cefa3e0d38686f0c6ab75ab8862e81.jpg" style="width: 500px; height: 714px" /></p>
<p>
	◎译　　名　三只猴子<br />
	◎片　　名　Three Monkeys<br />
	◎年　　代　2008<br />
	◎国　　家　土耳其/法国/意大利<br />
	◎类　　别　剧情<br />
	◎语　　言　土耳其语<br />
	◎字　　幕　中字<br />
	◎IMDB评分 &nbsp; 7.2/10 (7,213 votes)<br />
	◎IMDB链接 &nbsp; <a href="http://www.imdb.com/title/tt1233381/" target="_blank">http://www.imdb.com/title/tt1233381/</a><br />
	◎片　　长　01:48:51<br />
	◎导　　演　努里&middot;比格&middot;锡兰 Nuri Bilge Ceylan<br />
	◎主　　演　厄康&middot;吉赛尔 Rifat Sungkar<br />
	　　　　　　Yavuz Bingol ... Ey&uuml;p<br />
	　　　　　　Hatice Aslan ... Hacer<br />
	　　　　　　Ercan Kesal ... Servet<br />
	　　　　　 &nbsp;Cafer K&ouml;se ... Bayram<br />
	　　　　　　G&uuml;rkan Aydin ... The Child<br />
	<br />
	<br />
	◎简　　介<br />
	<br />
	剧情<br />
	<br />
	　　《三只猴子》通过讲述一个家庭的悲剧故事，反映土耳其的社会问题。影片讲述一个政客夜间开车撞倒路人，为了不影响自己的选举，他掏钱让自己的司机去顶罪。司机入狱后，政客引诱了司机的妻子，而这一切，司机的儿子都看在眼里。<br />
	<br />
	幕后制作<br />
	<br />
	【关于影片】<br />
	<br />
	　　锡兰获奖影片《三只猴子》中文片名译自英文片名《Three Monkeys》，出自日本宗教中的&ldquo;三猿像&rdquo;，画中三只猴子，一只捂耳，一只掩嘴，一只蒙眼，喻意&ldquo;不看、不听、不说&rdquo;。<br />
	　　&ldquo;三只猴子&rdquo;也就暗示着生活在同一家庭的三个人，互相怀疑、隐忍、无法坦诚面对：为了钱，父亲瞒着儿子替老板顶罪；母亲瞒着老公和老板发生私情；发现母亲偷情后，儿子瞒着父亲杀掉母亲的情人。影片中最精妙地方在于结局，父亲从狱中出来，发现了妻子的私情，并且知道了儿子是杀人凶手。面对这个局面，他在警察局门口徘徊一圈之后，找到了另外一个更贫苦的咖啡店侍从，让他替儿子顶罪。<br />
	　　故事的背景全由时间不长的旁白交代完成，之后电影开始缓慢地展现母子的日常生活，平静地似乎什么事情都不会发生。然而，再细微的情节和线索也在不断地建构影片，直到它达到最后高潮&mdash;&mdash;情感上的高潮。这也正是土耳其导演努里&middot;比格&middot;锡兰所擅长的，他用镜头去捕获人内心丰沛而含蓄的情感，再像制作标本一般，一丝不苟地抚过绿叶的经脉。<br />
	　　如今没有一个电影人可以暗示人内在的精神状态，就像锡兰所能做的，他们仅能通过摄影机对角色进行外部观察。并且，无论是在长镜头还是在特写镜头中，锡兰偏好让事物充满整个画面，以便将表达的力度上升到最大。独特的调焦和摄影机角度也体现出作者一丝不苟的思考，一些故意的时间延长则营造出了情绪上的紧张。除开对家庭动力的强调，锡兰的新元素还在于营造出了明显的宗教感。<br />
	　　影片也不是没有软肋。比如，妻子Hacer之所以会采取鲁莽轻率的行为而严重威胁了家庭安全的动机是什么？这在片中几乎没有提到，因此显得不大可信。再如，锡兰似乎不大确定如何结束他的影片，因为结局需要他做出选择&mdash;&mdash;哪些主题应该被强调。当然这显得有些吹毛求疵了。《三只猴子》的每一个镜头都像画廊墙上准确悬挂的作品，安静，却充满力量。<br />
	　　本片由《四季无常》的老班底拍摄，画面深刻且意义丰富。为了突出要旨，导演选择了阴郁压抑的色调，甚至不时让画面从一片乌漆巴黑过渡到令人呕吐的呆板绿色。音响效果也非常成功，汽车轮胎在卵石小路上的摩擦声，以及永无停息的海潮，让人物的内心煎熬简直清晰可闻。<br />
	<br />
	【关于导演】<br />
	<br />
	　　努里&middot;比格&middot;锡兰被称作&ldquo;过去十年来最有个性的导演之一&rdquo;，同时，他也是一位名副其实的&ldquo;戛纳幸运儿&rdquo;。1959年出生的锡兰出生于的伊斯坦布尔，2003年，他执导的《远方》(Uzak)在戛纳电影节上一举夺下评审团大奖和最佳男演员两项大奖，此后，他还凭借《气候》一片再度入围戛纳电影节正式竞赛单元。<br />
	　　&ldquo;这部电影讲的是生活，涉及面很广，关乎人的内心世界，&rdquo;锡兰说，&ldquo;我可不想在电影里说教。&rdquo;&ldquo;在生活中，人们常常习惯于视而不见，听而不闻。而这就是我们保护自己不至过于痛苦的方式。&rdquo;<br />
	<br />
	【媒体评论】<br />
	<br />
	　　《三只猴子》首映后，媒体给出评价褒贬不一。《metro》的电影节特刊评价道：&ldquo;每年电影节都有这样一部彻底可以置观众于不顾、冷漠的影片出现，今年它就是《三只猴子》&rdquo;。尤其提到，影片大多数段落都是冗长的沉默，这种叙述方式被滥用，&ldquo;片中的女主人公转头过来，非常缓慢，再用非常长的时间，互相对视对方。那些自然的风声、还有手机电话响起的音乐，都被认为是提供给整个寂静背景下可爱、奢侈的声音想象&rdquo;。<br />
	　　《好莱坞报道》认为，&ldquo;土耳其导演锡兰的电影没有什么秘密，就是那种已经习惯的口味：如同岩石层堆积的一样缓慢的镜头，对于那些有辨识能力的铁杆影迷而言，《三只猴子》和他以前的电影没有什么区别。&rdquo;同时，它还嘲笑地表示，锡兰的影片只有在那些艺术院线内才会被观众期待，辅助的收入就是DVD版权出售，或者成为艺术博物馆内放映的节目。<br />
	　　但是《银幕》杂志热情洋溢地盛赞《三只猴子》是部经典之作，&ldquo;锡兰的新作大胆地叛离了他过去所有影片，内敛、自省地讲述剧情成为一种最好的叙述方式，加上视觉、声效上的完美，成为锡兰的精髓之作&rdquo;。该杂志的10 位国际影评人为《三只猴子》打出2.8 的高分，这也是22 部竞赛片中给出的最高分。<br />
	　　&ldquo;我发现我的影片两极分化很严重，有非常喜欢的，也有很讨厌的，几乎有近千种不同的反应&rdquo;，原本笃定的锡兰有些焦躁不安。他安慰自己，&ldquo;我拍了自己喜欢的片子，表达了想要表达的东西，就足够了，剩下的交给评委会去考虑吧&rdquo;。<br />
	　　锡兰唯一的遗憾就是没有拿到金棕榈大奖。他得奖感言是：&ldquo;这对我来说是个惊喜，谢谢雅各布，谢谢评委。这是个非常好的奖项，我要将这个奖项献给我美丽的国家，我非常热爱它&rdquo;。<br />
	<br />
	花絮<br />
	<br />
	&middot;影片获得第61届戛纳电影节最佳导演奖，经典电影《邦尼和克莱德》中的&ldquo;邦尼&rdquo;费&middot;唐纳薇上台，为《三只猴子》的导演努里&middot;比格&middot;锡兰颁发最佳导演奖。<br />
	<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120521/23/62564813201205212316354260546349609_002.jpg" style="width: 650px; height: 366px" /><img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120521/23/62564813201205212316354260546349609_001.jpg" style="width: 650px; height: 366px" /><img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120521/23/62564813201205212316354260546349609_000.jpg" style="width: 650px; height: 366px" /><br />
	&nbsp;</p>
<p>
	【下载地址】</p>
<table bgcolor="#0099cc" border="0" cellpadding="10" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaobajie.com" target="_blank">http://www.xiaobajie.com</a></td>
		</tr>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy125:piaohua@dy125.piaohua.com:8063/飘花电影piaohua.com三只猴子BD中字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:8063/飘花电影piaohua.com三只猴子BD中字1280高清.rmvb</a></td>
		</tr>
		<tr>
		</tr>
	</tbody>
</table>
<br />{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O149EU0-1V03.jpg{/dede:field}
