{dede:field name='keywords'}天空之城国粤日三语BD高清中字12{/dede:field}
{dede:field name='description'}天空之城国粤日三语BD高清中字1280迅雷下载、免费下载，天空之城国粤日三语BD高清中字1280Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}天空之城国粤日三语BD高清中字1280{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-02-16{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://dy241:xiaobajie@222.187.221.241:2025/小八戒电影xiaobajie.com天空之城日国粤三语BD高清中字1280.mkv" target="_blank{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MQ105110-3A94.jpg{/dede:field}
