{dede:field name='keywords'}亡命夜巴黎/惊狂记高清中英双字B{/dede:field}
{dede:field name='description'}亡命夜巴黎/惊狂记高清中英双字BD1280迅雷下载、免费下载，亡命夜巴黎/惊狂记高清中英双字BD1280Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}亡命夜巴黎/惊狂记高清中英双字BD1280{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-02-11{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://www.zaslike.com/files/popdahibduzueosygmox.jpg" style="width: 467px; height: 600px" /></p>
<p>
	◎译　　名　亡命夜巴黎<br />
	◎片　　名　Frantic&nbsp;&nbsp;<br />
	◎别　　名&nbsp;&nbsp;惊狂记/狂暴/狂乱<br />
	◎年　　代　1988年<br />
	◎导　　演　罗曼&middot;波兰斯基&nbsp; &nbsp;Roman Polanski&nbsp; &nbsp;<br />
	◎主　　演　哈里森&middot;福特/Harrison Ford (I)(美国).... Dr. Richard Walker.(主演)<br />
	&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp;&nbsp;贝蒂&middot;布克利/Betty Buckley.... Sondra Walker.(主演)<br />
	&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp;&nbsp;埃曼纽尔&middot;塞耶/Emmanuelle Seigner.... Michelle.(主演)<br />
	&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp;&nbsp;Djiby Soumare/Djiby Soumare.... Taxi Driver.(主演)<br />
	&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp;&nbsp;Dominique Virton/Dominique Virton.... Desk Clerk.(主演)<br />
	&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp;&nbsp;G&eacute;rard Klein/G&eacute;rard Klein.... Gaillard.(主演)<br />
	&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp;&nbsp;St&eacute;phane D&#39;Audeville/St&eacute;phane D&#39;Audeville.... Bellboy.(主演)<br />
	&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp;&nbsp;Laurent Spielvogel/Laurent Spielvogel.... Hall Porter.(主演)<br />
	&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp;&nbsp;Alain Doutey/Alain Doutey.... Hall Porter.(主演)<br />
	&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp;&nbsp;Jacques Ciron/Jacques Ciron.... Le Grand Hotel Manager.(主演)<br />
	&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp;&nbsp;Roch Leibovici/Roch Leibovici.... Bellboy 2.(主演)<br />
	&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp;&nbsp;Louise Vincent/Louise Vincent.... Tourist.(主演)<br />
	&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp;&nbsp;Patrice Melennec/Patrice Melennec.... Hotel Detective Le Grand Hotel.(主演)<br />
	&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp;&nbsp;Ella Jaroszewicz/Ella Jaroszewicz.... Restroom Attendant.(主演)<br />
	&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp;&nbsp;Jo&euml;lle Lagneau/Jo&euml;lle Lagneau.... Florist.(主演)<br />
	&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp;&nbsp;Jean-Pierre Delage/Jean-Pierre Delage.... Florist.(主演)<br />
	&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp;&nbsp;Marc Dudicourt/Marc Dudicourt.... Cafe Owner.(主演)<br />
	&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp;&nbsp;Artus de Penguern/Artus de Penguern.... Waiter.(主演)<br />
	&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp;&nbsp;多米尼克&middot;皮诺/Dominique Pinon.... Wino.(主演)<br />
	&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp;&nbsp;Richard Dieux/Richard Dieux.... Desk Cop.(主演)<br />
	<br />
	<br />
	◎影片类型　&nbsp;&nbsp;惊悚/悬疑/犯罪&nbsp; &nbsp;&nbsp;&nbsp;<br />
	◎片　　长　&nbsp;&nbsp;120 min<br />
	◎国　　家　&nbsp;&nbsp;美国/法国&nbsp; &nbsp;&nbsp; &nbsp;<br />
	◎对白语言　&nbsp;&nbsp;英语/法语&nbsp; &nbsp;<br />
	◎IMDB链接　<a href="http://www.imdb.com/title/tt0095174/" target="_blank">http://www.imdb.com/title/tt0095174/</a><br />
	◎IMDB评分　6.7/10&nbsp; &nbsp;16,873 votes&nbsp; &nbsp;<br />
	<br />
	<br />
	<br />
	<br />
	◎简　　介　<br />
	&nbsp; &nbsp;&nbsp; &nbsp;&nbsp;&nbsp;<br />
	<br />
	&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;霍克医生和太太从旧金山来到巴黎渡假。在饭店中霍克大夫洗澡时太太突然失踪，有人看到她是被人绑架了，霍克只知道案发前太太在机场拿错了行李。于是他报了案，谁知警方并不配合，他只好孤身一人展开了一连串的追踪，找到了同样错拿行李的一个法国姑娘。至此霍克才明白，绑架他太太的人是要那姑娘从美国带到巴黎的一个飞弹分离及核子弹的引爆装置&hellip;&hellip;<br />
	<br />
	◎影片评价<br />
	<br />
	　　从&quot;星际大战&quot;到现在已有整整二十年, 一个演员要红二十年并不容易, 福特做到了. 而且他不只是红, 他可说是影史的传奇之一. 在影史上最卖座的二十五部片中, 福特主演的片子占了七部, 这是个空前绝后的纪录. 福特有种特别的直觉, 他知道&quot;观众想看什么&quot;. 就像&quot;新龙凤配&quot;中的莱纳斯说的, &quot;我就是知道!&quot; 他一年只拍一部戏, 而且对剧本, 及拍摄情况都有诸多意见, 因为他想给观众最好的.&nbsp;</p>
<p>
	<img alt="" src="http://www.zaslike.com/files/rayq85ru60twx92uskt.jpg" /><img alt="" src="http://www.zaslike.com/files/i4t8ej58n1jmh4ss0kab.jpg" /><img alt="" src="http://www.zaslike.com/files/4i17dmoclg6r2ejd85.jpg" /></p>

<p>
	[下载地址]：&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" width="100%">
				<a href="ftp://dy241:xiaobajie@222.187.221.241:2017/小八戒电影xiaobajie.com惊狂记高清中英双字BD1280.rmvb">ftp://dy241:xiaobajie@222.187.221.241:2017/小八戒电影xiaobajie.com惊狂记高清中英双字BD1280.rmvb</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15054P-344a.jpg{/dede:field}
