{dede:field name='keywords'}醉拳I,HD1280高清,成龙大哥经典{/dede:field}
{dede:field name='description'}醉拳I HD1280高清 成龙大哥经典迅雷下载、免费下载，醉拳I HD1280高清 成龙大哥经典Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}醉拳I HD1280高清 成龙大哥经典{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-12-30{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="/uploads/allimg/c120525/133O10056420-1O461.jpg" style="width: 700px; height: 1023px" /></p>
<p>
	◎ 中文名: 醉拳<br />
	◎ 英文名: Drunken Master<br />
	◎ 资源格式: HDTVRip<br />
	◎ 版本: 粤语/导评<br />
	◎ 发行日期: 1978年<br />
	◎ 导演: 袁和平<br />
	◎ 演员: 成龙 袁小田 黄正利<br />
	◎ 地区: 香港<br />
	◎ 语言: 普通话,粤语<br />
	◎ IMDb: 7.6/10 (6,231 votes)<br />
	◎ IMDB链接：http://www.imdb.com/title/tt0080179/<br />
	<br />
	◎ 剧情简介：<br />
	　　故事描述年青时的黄飞鸿，因年少气盛，终因惹事生非，得罪恶霸李万豪之子，飞鸿之父黄麒英为使不肖子成材，请来老友佛山苏乞儿，经过一年艰苦训练，黄飞鸿已略窥苏乞儿绝学醉八仙的门径，这边厢，李万豪欲将煤矿私自卖给日本人，奸计为麒英撞破，李为达目的不择手段，遂买凶杀麒英，飞鸿一年来所学加上自创招式醉拳得大派用场&hellip;&hellip;<br />
	<img alt="" src="/uploads/allimg/c120525/133O1005P10-1Yb9.jpg" style="width: 720px; height: 405px" /><img alt="" src="/uploads/allimg/c120525/133O1005XP-1942P.jpg" style="width: 720px; height: 405px" /><img alt="" src="/uploads/allimg/c120525/133O1005a50-2013a.jpg" style="width: 720px; height: 405px" /><br />
	&nbsp;</p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="/uploads/allimg/c120525/133O0T31310-42214.jpg" />&nbsp;&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy241:piaohua@dy241.piaohua.com:2013/飘花电影piaohua.com醉拳1HD粤语无字1280高清.rmvb</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O10060F-21R06.jpg{/dede:field}
