{dede:field name='keywords'}神秘博士2010圣诞特别篇：圣诞颂{/dede:field}
{dede:field name='description'}神秘博士2010圣诞特别篇：圣诞颂BD中英双字1024高清迅雷下载、免费下载，神秘博士2010圣诞特别篇：圣诞颂BD中英双字1024高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}神秘博士2010圣诞特别篇：圣诞颂BD中英双字1024高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-12-24{/dede:field}
{dede:field name='body'}<p>
	<img src="http://img.album.pchome.net/54/82/47/56/04cbe5cf2ca423c88eb9d583845c4860.jpg" /><br />
	<br />
	<br />
	◎译　　名　《神秘博士2010圣诞特别篇：圣诞颂》2010年英国最新剧情科幻片HD中英双字<br />
	◎片　　名　Doctor Who 2005 A Christmas Carol 2010 Special<br />
	◎年　　代　2010<br />
	◎国　　家　英国<br />
	◎类　　别　剧情/科幻<br />
	◎语　　言　英语<br />
	◎字　　幕　中英双字<br />
	◎文件格式　HD-RMVB<br />
	◎视频尺寸　624x352<br />
	◎文件大小　1CD<br />
	◎片　　长　61分钟<br />
	◎导　　演　Toby Haynes 托德&middot;海因斯<br />
	◎主　　演　Matt Smith 马特&middot;史密斯 .... The Doctor 博士<br />
	　　　　　　Karen Gillan 凯伦&middot;吉兰 ....Amy Pond 艾米&middot;池<br />
	　　　　　　Arthur Darvil 亚瑟&middot;达维尔 ....Rory 罗维<br />
	　　　　　　Katherine Jenkins 凯瑟琳&middot;詹金斯 .... Abigail<br />
	　　　　　　Michael Gambon 迈克尔&middot;刚本 .... Kazran/Elliot Sardick</p>
<p>
	◎简　　介</p>
<p>
	<br />
	　　博士带着Amy和Rory组成的蜜月小分队在宇宙漫游时遇到一艘载有4000多乘客的太空船，飞船驶到一颗云层密布的行星时几近遇险，能够拯救这4000多生命的，只有掌管着星球云层的Kazran（Michael Gambon饰演）。但是固执的老人却不愿伸出援手&hellip;</p>
<p>
	　　不容错过的还有飞在空中的鲨鱼，冰冻着的美丽姑娘，治愈的歌声，当然还有圣诞之灵以及一切的圣诞元素。</p>
<p>
	　　2010年岁末的神秘博士圣诞特辑，依旧有Matt Smith饰演<a href="http://www.3edyy.com/" target="_blank">电影</a>第11任博士，第五季开始是和前四季不同的新团队制作的，这个Doctor Who 2005系列将继续上演，期待来年的第六季，希望能越拍越好。<br />
	<br />
	<br />
	<img src="http://img.album.pchome.net/54/82/47/56/acc7e7bbd5593ec7719aacdad0c4cefb.jpg" />&nbsp;<br />
	<img src="http://img.album.pchome.net/54/82/47/56/ca695f0847931abcad86759be1b90ccc.jpg" />&nbsp;<br />
	<img src="http://img.album.pchome.net/54/82/47/56/fc2ab71cbd4dd1968d72365c5766f6a9.jpg" /><br />
	<br />
	&nbsp;</p>
<p>
	【电影截图】：<br />
	&nbsp;</p>
<p>
	<img src="http://img.album.pchome.net/54/82/47/56/7be7896ae7dcb092112fa353731b3d82.jpg" />&nbsp;<br />
	<img src="http://img.album.pchome.net/54/82/47/56/7a4e3d94dee95326dbae5cd31653727b.jpg" />&nbsp;<br />
	<img src="http://img.album.pchome.net/54/82/47/56/b262f168429889f0e9e61ac001c00e7c.jpg" />&nbsp;<br />
	<img src="http://img.album.pchome.net/54/82/47/56/723e9b1b11b46f4cd89477a733132ec1.jpg" /><br />
	<br />
	<br />
	<br />
	<img alt="" height="422" src="http://img.album.pchome.net/05/53/66/25/0d48d462694dfb1117759fafc2283f0c.-" width="750" /></p>
<p>
	<img alt="" height="422" src="http://img.album.pchome.net/05/53/66/25/2ad03b10fbd9bb8d4d1ec42e94edc637.-" width="750" /></p>
<p>
	<img alt="" height="422" src="http://img.album.pchome.net/05/53/66/25/5b60521ec61adfcc2a69a5049cffdafe.-" width="750" /><br />
	<br />
	2010年英国最新剧情科幻片《神秘博士2010圣诞特别篇：圣诞颂》HD中英双字 [下载地址]：<img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" /></p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://6e:6e@m3.3edyy.com:512/【3E看看www.3ekk.com】神秘博士2010圣诞特别篇：圣诞颂[HD中英双字].rmvb" target="_blank">ftp://6e:6e@m3.3edyy.com:512/【3E看看www.3ekk.com】神秘博士2010圣诞特别篇：圣诞颂[HD中英双字].rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2430/飘花电影piaohua.com神秘博士2010圣诞特别篇：圣诞颂BD中英双字1024高清.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2430/飘花电影piaohua.com神秘博士2010圣诞特别篇：圣诞颂BD中英双字1024高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15X4950-31E6.jpg{/dede:field}
