{dede:field name='keywords'}变种异煞/千钧一发/特卡BD中英双{/dede:field}
{dede:field name='description'}变种异煞/千钧一发/特卡BD中英双字1280高清迅雷下载、免费下载，变种异煞/千钧一发/特卡BD中英双字1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}变种异煞/千钧一发/特卡BD中英双字1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-01-03{/dede:field}
{dede:field name='body'}<p>
	<img alt="" border="0" height="500" src="http://ecx.images-amazon.com/images/I/51VfE5rU9OL._SS500_.jpg" width="500" /></p>
<p>
	【译　　名】《变种异煞/千钧一发/特卡》高分精彩科幻大片DVD中英双字<br />
	【片　　名】Gattaca<br />
	【年　　代】1997<br />
	【国　　家】美国<br />
	【类　　别】剧情/科幻/惊悚<br />
	【语　　言】英语<br />
	【字　　幕】中英双字<br />
	【IMDB评分】7.7/10 (48,224 votes)<br />
	【文件格式】X264 + AC3<br />
	【视频尺寸】800 X 452<br />
	【电影整理】3E迅雷电影下载站(www.eee4.com)<br />
	【文件大小】3CD 470MB<br />
	【片　　长】106MiN<br />
	【导　　演】Andrew Niccol<br />
	【主　　演】伊桑&middot;霍克 Ethan Hawke&nbsp; ....&nbsp; Vincent Freeman<br />
	　　　　　　裘德&middot;洛 Jude Law&nbsp; ....&nbsp; Jerome Eugene Morrow<br />
	　　　　　　乌玛&middot;瑟曼 Uma Thurman&nbsp; ....&nbsp; Irene Cassini<br />
	　　　　　　阿兰&middot;阿金 Alan Arkin&nbsp; ....&nbsp; Det. Hugo<br />
	　　　　　　欧内斯特&middot;博格宁 Ernest Borgnine&nbsp; ....&nbsp; Caesar<br />
	　　　　　　劳恩&middot;迪恩 Loren Dean&nbsp; ....&nbsp; Anton Freeman<br />
	　　　　　　埃利亚斯&middot;考蒂斯 Elias Koteas&nbsp; ....&nbsp; Antonio Freeman<br />
	　　　　　　Gore Vidal&nbsp; ....&nbsp; Director Josef<br />
	　　　　　　Mason Gamble&nbsp; ....&nbsp; Younger Vincent<br />
	　　　　　　托尼&middot;谢尔博 Tony Shalhoub&nbsp; ....&nbsp; German<br />
	　　　　　　威廉&middot;李&middot;斯科特 William Lee Scott&nbsp; ....&nbsp; Young Anton<br />
	　　　　　　布莱尔&middot;安德伍德 Blair Underwood&nbsp; ....&nbsp; Geneticist<br />
	　　　　　　Carlton Bembry&nbsp; ....&nbsp; Gattaca Hoover<br />
	　　　　　　山德&middot;贝克利 Xander Berkeley&nbsp; ....&nbsp; Dr. Lamar<br />
	　　　　　　Steve Bessen&nbsp; ....&nbsp; Blood-test detective</p>
<p>
	【简　　介】：</p>
<p>
	&nbsp;&nbsp;&nbsp; 在不久的将来，人类是经基因搭配孕育而成，是人中的精英。经自然诞生的人则被视为&ldquo;病人&rdquo;。文森正是这样的人，他为了参加加达卡太空企业的太空计划要假扮精英成员的基因身份，但升空前一星期，任务指挥官被誉为杀疑凶是一病人，文森要设法避过调查员的追查，才能实现梦想。</p>
<p>
	&nbsp;&nbsp;&nbsp; 在这个未来世界，每个人的命运都不再是充满未知。当一个生命刚刚诞生（甚至在他/她刚刚可以被称作生命之时），他/她的人生路径就已基本确定，除非有一些意想不到的非基因因素出现。从基因的角度来说，文森特是个不幸的人。他一出生就被宣布带有一定的基因缺陷，长大后的他将是近视和心脏病患者，更可怕的是：根据基因推断，他只有30年的生命。文森特的父母非常想要一个优秀的儿子，因此用基因优选法为他生了一个弟弟。尽管文森特在成长的过程中事事努力，但仍受到不公正的基因歧视。他喜欢与弟弟进行游泳比赛，事实也证明他并不比弟弟差，然而这一切又有什么用呢？人们相信的只有基因！文森特痴迷于太空，为了实现飞上天去的梦想，他离家出走，历尽人间风雨，最后终于在太空中心找到了一份清洁工的工作。连他自己也不知道，这是否意味着他缩短了离自己梦想的距离。这时，他结识了具有优秀基因但却因意外事故而下身瘫痪的杰罗姆。杰罗姆同意与他交换身份，帮助他完成进入太空的梦想。</p>
<p>
	　　经过一系列精心的准备，文森特终于以杰罗姆的身份成为太空中心的一级领航员。不久他得到通知：一个星期后将踏上飞往泰坦星的征程。做为文森特的幕后支持者，杰罗姆的工作就是每天为他准备应付太空中心严密基因核查的用品，如尿样、血样，甚至毛法、皮屑。而文森特则每天都要在进入太空中心前进行繁琐细致的全身清洗，以免将自己的毛发、皮屑遗落在太空中心。这些不起眼的东西会使他暴露真实身份。</p>
<p>
	　　正当一切都按计划发展之时，太空中心的一位关键人物被谋杀了。警探根据一根含有劣质基因的睫毛，很快就怀疑上了他。</p>
<p>
	　　这天早上，文森特正准备进入办公室，不想却从女友伊莲妮处得到一个令他震惊的坏消息：警探正准备对他进行更深入的基因核查。文森特迅速躲了起来。警探强迫伊莲妮前往文森特的家，文森特暗中立即通知家里的杰罗姆。当警探赶到时，杰罗姆已经用惊人的毅力从地下室爬到楼上的会客厅。警探抽取杰罗姆的静脉血核查基因，结果令他大惑不解：面前这个人的确有着优秀的基因。与此同时，谋杀案的真凶已经归案。而文森特也找到了他多年不见的弟弟&hellip;&hellip;</p>
<p>
	　　文森特终于实现了飞上太空的梦想。在飞船中，他打开杰罗姆临别时送给他的信封，里面是一绺含有杰罗姆优秀基因的头发&hellip;&hellip;此时，杰罗姆也结束了自己的生命&hellip;&hellip;电影编辑整理：(www.eee4.com)</p>
<p>
	高分精彩科幻大片《千钧一发》DVD中英双字 － 来自[3E迅雷电影站eee4.com]下载地址：<img border="0" src="http://www.eee4.com/templets/img/down.jpg" /><br />
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<anchor></anchor><a href="ftp://eee4.com:8116@vip13.eee4.com:8116/[3E迅雷电影站www.eee4.com]千钧一发DVD中英双字CD1.rmvb" target="_blank">ftp://eee4.com:8116@vip13.eee4.com:8116/[3E迅雷电影站www.eee4.com]千钧一发DVD中英双字CD1.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<anchor></anchor><a href="ftp://eee4.com:8116@vip13.eee4.com:8116/[3E迅雷电影站www.eee4.com]千钧一发DVD中英双字CD2.rmvb" target="_blank">ftp://eee4.com:8116@vip13.eee4.com:8116/[3E迅雷电影站www.eee4.com]千钧一发DVD中英双字CD2.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<anchor></anchor><a href="ftp://eee4.com:8116@vip13.eee4.com:8116/[3E迅雷电影站www.eee4.com]千钧一发DVD中英双字CD3.rmvb" target="_blank">ftp://eee4.com:8116@vip13.eee4.com:8116/[3E迅雷电影站www.eee4.com]千钧一发DVD中英双字CD3.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<anchor></anchor><a href="ftp://dy44:piaohua@dy44.piaohua.com:2508/飘花电影piaohua.com特卡BD中英双字1280高清.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2508/飘花电影piaohua.com特卡BD中英双字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15YO40-26143.jpg{/dede:field}
