{dede:field name='keywords'}失踪的宝贝BD1280高清迅雷下载，{/dede:field}
{dede:field name='description'}失踪的宝贝BD1280高清迅雷下载、免费下载，失踪的宝贝BD1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}失踪的宝贝BD1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-04-15{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://i.imgur.com/ZuxLv.jpg" style="width: 366px; height: 468px" /></p>
<p>
	◎译　　名　失踪的宝贝<br />
	◎片　　名　Gone Baby Gone<br />
	◎年　　代　2007<br />
	◎国　　家　美国<br />
	◎类　　别　犯罪/剧情/神秘<br />
	◎语　　言　英语<br />
	◎IMDB评分 8.0/10 (36,616 votes)<br />
	◎IMDB链接 <a class="faqlink" href="http://www.imdb.com/title/tt0452623">http://www.imdb.com/title/tt0452623</a><br />
	◎导　　演　本&middot;阿弗莱克 Ben Affleck<br />
	◎主　　演　卡西&middot;阿弗莱克 Casey Affleck .....Patrick Kenzie<br />
	　　　　　　摩根&middot;弗里曼 Morgan Freeman .....Jack Doyle<br />
	　　　　　　米歇尔&middot;莫娜汉 Michelle Monaghan .....Angela &quot;Angie&quot; Gennaro<br />
	　　　　　　艾德&middot;哈里斯 Ed Harris .....Detective Remy Broussard<br />
	　　　　　　Robert Wahlberg .....Detective O&#39;Malley<br />
	　　　　　　埃米&middot;马迪根 Amy Madigan .....Beatrice McCready<br />
	　　　　　　John Ashton .....Poole<br />
	　　　　　　Mark Margolis .....Leon Trett<br />
	　　　　　　艾米&middot;莱安 Amy Ryan .....Helene McCready<br />
	　　　　　　Michael K. Williams .....Devin<br />
	　　　　　　Titus Welliver .....Lionel McCready<br />
	　　　　　　Allyssa Maurice .....Funeral Mourner<br />
	　　　　　　Edi Gathegi .....Cheese<br />
	　　　　　　Elizabeth Dings .....Police Officer<br />
	　　　　　　Matthew Maher .....Corwin Earle<br />
	<br />
	◎简　　介　<br />
	<br />
	作为最无助、最纯洁的群体，儿童往往会成为容易受到攻击的脆弱对象，这也是为什么父母一定要担当起&ldquo;监护&rdquo;的重任。整个故事都是围绕着一个失踪的4岁小女孩阿曼达&middot;麦克莱展开的，然而到了最后，究竟是什么原因致使阿曼达凭空不见似乎已经不再重要了，因为整个世界其实就是一个关于阶级、腐败、邪恶和无辜的曲折迷宫，也许她只是迷失在了某个拐角处而已。<br />
	　　波士顿一个被称为都切斯特的大型社区里，在那条以坚韧的工人阶级为主要居住群体的街道上，却布满了正在蒙受灾难的破碎家庭和残缺不全的梦想。而阿曼达就是在这里突然悄无声息地失踪了，好像她从未到过这个世界一样。警察似乎总是喜欢在不适当的时候出现，可是当你真正出现状况的时候，却发现完全指望不上他们。同样地，警方也只能对阿曼达这个案子两手一摊，做无奈状&hellip;&hellip;没有比绝望的家人更能体会失去亲人的痛苦了，阿曼达的阿姨和姨父不愿意轻易放弃一个生命，所以他们转而来到一家私人侦探所，委托帕特里克&middot;肯齐和安吉&middot;根纳罗共同调查外甥女的失踪案，因为他们听说帕特里克神通广大--这也是他们寻找阿曼达的最后希望了。<br />
	　　从小在这里长大的帕特里克和安吉是事业上的搭档，也是生活中的恋人，他们决定先从熟悉的邻里环境中入手，再慢慢扩大调查的范围。过程中，他们了解到阿曼达的母亲海琳是一个纯粹的瘾君子，她对毒品的关心程度似乎远胜于女儿的失踪&hellip;&hellip;帕特里克和安吉决定从海琳身上打开突破口，然而当他们顺藤摸瓜地调查了一系列毒品贩子、诈骗犯、虐待儿童的人时，却发现自己竟然也卷进了波士顿最黑暗的心脏地带，在这里，阿曼达的名字似乎变得更加地遥不可及。这个时候，媒体也适时地插手案件，在无情的聚光灯下，似乎没有任何能够隐藏起来的秘密。不堪其扰的探员雷米&middot;布莱森特以及警官杰克&middot;道尔只好同意和帕特里克暂时合作，尽快让案件水落石出，好堵住这些最爱说三道四、引起恐慌的记者的嘴--正像这个案子加诸在情感上的痛苦一样，一切似乎都在慢慢地失控，而阿曼达的命运中悲惨的真相，会把帕特里克带往何处呢？<br />
	　　也许，每个人都想尝试继续自己的生活，但灵魂已经受到了深深的折磨的帕特里克却发现自己的双腿像灌了铅一样，只能待在原地动弹不得，所以他选择按照整个案件的线索，原路返回。重新审视来时路的帕特里克惊讶地发现，自己竟然被引诱至一个由谎言和无法言明的暴力编织起来的强力网中，至于真相，则藏着一个让人震惊的秘密。至此，帕特里克站在道德选择的十字路口中，进退两难，而他同时也会忍不住问自己，到底怎么做才算是&ldquo;伸张正义&rdquo;呢？<br />
	<br />
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120415/03/62564813201204150318043617639487197_001.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120415/03/62564813201204150318043617639487197_000.jpg" style="width: 720px; height: 405px" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.net/" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy125:piaohua@dy125.piaohua.com:7853/飘花电影piaohua.com失踪的宝贝BD中字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:7853/飘花电影piaohua.com失踪的宝贝BD中字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O160GQ0-152J.jpg{/dede:field}
