{dede:field name='keywords'}传说/童话镇欧美剧22迅雷下载，{/dede:field}
{dede:field name='description'}传说/童话镇欧美剧22迅雷下载、免费下载，传说/童话镇欧美剧22Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}传说/童话镇欧美剧22{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-14{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://pic.piaohua.com/0701pic/allimg/120110/1-120110150401U5.jpg" /></p>
<p>
	<img alt="" src="http://pic.piaohua.com/0701pic/allimg/120110/1-120110150409392.jpg" /></p>
<p>
	导演: Mark Mylod<br />
	编剧: Adam Horowitz / Edward Kitsis<br />
	主演: Jennifer Morrison / Jared Gilmore / Ginnifer Goodwin / Josh Dallas / Lana Parrilla / Raphael Sbarge<br />
	类型: 剧情 / 奇幻<br />
	官方网站: <a href="http://beta.abc.go.com/shows/once-upon-a-time/video">http://beta.abc.go.com/shows/once-upon-a-time/video</a><br />
	制片国家/地区: 美国<br />
	语言: 英语<br />
	首播日期: 2011-10-23<br />
	集数: 13<br />
	单集片长: 40<br />
	又名: 传说<br />
	IMDb链接: tt1843230<br />
	剧情简介 &middot; &middot; &middot; &middot; &middot; &middot;<br />
	　　匠心独具的《迷失》(Lost)监制Amam Horowitz与Edward Kitsis大胆地构造了一个全新的幻想国度，让童话与现实世界在这里冲撞。在这里，所有人都过着&ldquo;从此幸福快乐&rdquo;的生活&mdash;&mdash;或者说，每个人都被引导着对这个观念深信不疑。<br />
	　　Emma Swam， 28岁保释保证书收藏家，自婴孩时期被遗弃后就一直独自一人。她知道该如何照顾自己。但是，在她被Henry找上门之后，所有的一切都开始变得不同。这个若干年前被她放弃的儿子现年10岁，正处于绝望之中，需要寻求Emma的帮助。他深信其实Emma来自于另一个世界，是白马王子与白雪公主丢失的女儿。在Henry的童话书中，白马王子与白雪公主为了保护Emma免受邪恶女王的诅咒而把她送走。这个诅咒永远地困住了童话世界、冰冻住了时间，并把那里的人们带来了现代社会。Emma对此自然嗤之以鼻全然不信，但是当她把Hen...</p>
<p>
	[下载地址]：&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2579/飘花电影piaohua.co童话镇01.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:2579/飘花电影piaohua.co童话镇01.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2579/飘花电影piaohua.co童话镇01.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2579/飘花电影piaohua.co童话镇02.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:2579/飘花电影piaohua.co童话镇02.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2579/飘花电影piaohua.co童话镇02.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2579/飘花电影piaohua.co童话镇03.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:2579/飘花电影piaohua.co童话镇03.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2579/飘花电影piaohua.co童话镇03.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2579/飘花电影piaohua.co童话镇04.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:2579/飘花电影piaohua.co童话镇04.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2579/飘花电影piaohua.co童话镇04.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2579/飘花电影piaohua.co童话镇05.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:2579/飘花电影piaohua.co童话镇05.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2579/飘花电影piaohua.co童话镇05.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2579/飘花电影piaohua.co童话镇06.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:2579/飘花电影piaohua.co童话镇06.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2579/飘花电影piaohua.co童话镇06.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2579/飘花电影piaohua.co童话镇07.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:2579/飘花电影piaohua.co童话镇07.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2579/飘花电影piaohua.co童话镇07.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2579/飘花电影piaohua.co童话镇08.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:2579/飘花电影piaohua.co童话镇08.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2579/飘花电影piaohua.co童话镇08.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2638/飘花电影piaohua.co童话镇09.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:2638/飘花电影piaohua.co童话镇09.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2638/飘花电影piaohua.co童话镇09.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2688/飘花电影piaohua.co童话镇10.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:2688/飘花电影piaohua.co童话镇10.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2688/飘花电影piaohua.co童话镇10.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2719/飘花电影piaohua.co童话镇11.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:2719/飘花电影piaohua.co童话镇11.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2719/飘花电影piaohua.co童话镇11.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2831/飘花电影piaohua.co童话镇12.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:2831/飘花电影piaohua.co童话镇12.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2831/飘花电影piaohua.co童话镇12.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2855/飘花电影piaohua.co童话镇13.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:2855/飘花电影piaohua.co童话镇13.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2855/飘花电影piaohua.co童话镇13.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2960/飘花电影piaohua.co童话镇14.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:2960/飘花电影piaohua.co童话镇14.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2960/飘花电影piaohua.co童话镇14.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3001/飘花电影piaohua.co童话镇15.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3001/飘花电影piaohua.co童话镇15.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3001/飘花电影piaohua.co童话镇15.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3040/飘花电影piaohua.co童话镇16.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3040/飘花电影piaohua.co童话镇16.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3040/飘花电影piaohua.co童话镇16.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3077/飘花电影piaohua.co童话镇17.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3077/飘花电影piaohua.co童话镇17.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3077/飘花电影piaohua.co童话镇17.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3128/飘花电影piaohua.co童话镇18.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3128/飘花电影piaohua.co童话镇18.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3128/飘花电影piaohua.co童话镇18.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3276/飘花电影piaohua.co童话镇19.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3276/飘花电影piaohua.co童话镇19.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3276/飘花电影piaohua.co童话镇19.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3327/飘花电影piaohua.co童话镇20.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3327/飘花电影piaohua.co童话镇20.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3327/飘花电影piaohua.co童话镇20.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3367/飘花电影piaohua.co童话镇21.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3367/飘花电影piaohua.co童话镇21.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3367/飘花电影piaohua.co童话镇21.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3419/飘花电影piaohua.co童话镇22.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3419/飘花电影piaohua.co童话镇22.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3419/飘花电影piaohua.co童话镇22.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1A3Z50-35918.jpg{/dede:field}
