{dede:field name='keywords'}勇夺芳心BD1280高清中字迅雷下载{/dede:field}
{dede:field name='description'}勇夺芳心BD1280高清中字迅雷下载、免费下载，勇夺芳心BD1280高清中字Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}勇夺芳心BD1280高清中字{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-07{/dede:field}
{dede:field name='body'}<div>
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120506/00/17870980201205060019081187476919495_008.jpg" style="width: 315px; height: 423px" /></div>
<div id="info">
	导演: 阿迪提亚&middot;乔普拉<br />
	主演: 沙鲁克&middot;汗 / 卡卓儿 / 阿莫瑞什&middot;普瑞<br />
	类型: 喜剧 / 家庭 / 歌舞 / 爱情<br />
	制片国家/地区: 印度</div>
<div>
	IMB：<a title="最新电影" href="http://www.xiaozhizhu.net/">http://www.xiaozhizhu.net/</a><br />
	语言: 北印度语 / 乌尔都语 / 英语 / Punjabi<br />
	上映日期: 1995-10-20<br />
	片长: 189 分钟 / Japan: 183 分钟 / USA: 181 分钟<br />
	IMDb链接: tt0112870<br />
	&nbsp;&nbsp;</div>
<div>
	　　</div>
<div>
	勇夺芳心的剧情简介<br />
	　　Chowdary Baldev Singh（Amrish Puri饰）与妻子Lajjo（Farida Jalal），两个女儿Simran（Kajol饰）和Chutki在伦敦定居。尽管在国外生活了20多年，他仍坚持印度的传统，安排Simran和远在印度旁遮普的朋友的儿子Kuljeet结婚。<br />
	　　Raj（Shahrukh Khan饰），是在伦敦土生土长的印度人，为人吊儿啷当，游手好闲。在一次欧洲旅行时，Raj与Simran偶然相遇，并双双堕入爱河。当Chowdary Baldev Singh发现Simran恋爱之后，决定举家回去印度。Raj也回印度寻找Simran。Raj如何排除万难娶得美人归呢&hellip;</div>
<div>
	&nbsp;</div>
<div>
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120506/00/17870980201205060019081187476919495_006.jpg" style="width: 640px; height: 360px" /></div>
<div>
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120506/00/17870980201205060019081187476919495_002.jpg" style="width: 640px; height: 360px" /></div>
<div>
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120506/00/17870980201205060019081187476919495_000.jpg" style="width: 640px; height: 360px" /><br />
	&nbsp;</div>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.net">http://www.xiaozhizhu.net</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy241:piaohua@117.41.229.29:2002/飘花电影piaohua.com勇夺芳心BD1280高清中字.rmvb">ftp://dy241:piaohua@117.41.229.29:2002/飘花电影piaohua.com勇夺芳心BD1280高清中字.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O150214F-54b9.jpg{/dede:field}
