{dede:field name='keywords'}远足惊魂DVD中字2011恐怖惊悚迅{/dede:field}
{dede:field name='description'}远足惊魂DVD中字2011恐怖惊悚迅雷下载、免费下载，远足惊魂DVD中字2011恐怖惊悚Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}远足惊魂DVD中字2011恐怖惊悚{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-21{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://www.fckb.net/data/attachment/forum/201112/19/201002xslu7fkj8s6w6z7b.jpg" /></p>
<p>
	◎译　　名　远足惊魂<br />
	◎片　　名　The Hike<br />
	◎年　　代　2011<br />
	◎国　　家　英国<br />
	◎类　　别　恐怖/惊悚<br />
	◎语　　言　英语<br />
	◎字　　幕　中字<br />
	◎IMDB评分&nbsp; 3.7/10&nbsp; (264 votes)<br />
	◎IMDB链接：<a href="http://www.bluemv.com">http://www.bluemv.com</a><br />
	◎文件格式　DVD-MKV<br />
	◎视频尺寸　640 x 272<br />
	◎文件大小　1CD-582mb<br />
	◎片　　长　80 mins<br />
	◎导　　演　Rupert Bryan<br />
	◎主　　演　Tamer Hassan ... Dean<br />
	　　　　　　Barbara Nedeljakova ... Torri<br />
	　　　　　　Ben Loyd-Holmes ... Ethan<br />
	　　　　　　Zara Phythian ... Kate<br />
	　　　　　　Daniel Caren ... Johnny<br />
	　　　　　　Dominic Le Moignan ... David<br />
	　　　　　　Jemma Bolt ... Charlie<br />
	　　　　　　Lisa-Marie Long ... Ellie<br />
	　　　　　　Shauna Macdonald ... Helen<br />
	　　　　　　Adam Ray Young ... Mikalos<br />
	　　　　　　Stephanie Siadatan ... Leanne<br />
	　　　　　　Natalie Hughes ... Anja<br />
	　　　　　　Joanne Nuttall ... Harriet<br />
	　　　　　　Kasha Bajor ... Anna</p>
<p>
	◎简　　介　</p>
<p>
	　　一个年轻的女兵凯特从阿富汗退役，服役期间目睹了他男友执行任务时阵亡，对她刺激很大，加上军营中 的谚语：&quot;你要知道何时全身而退&quot;，所以她选择退役并组织了一群年轻貌美的少女到英国乡村丛林里探险 活动，当她们接近目的地&ldquo;日落地&quot;时，遇到了3个很有魅力的登山探险家，她们的计划就改变了，相互之 间眉来眼去。当查理走失后，恐怕的气氛就正式拉开了序幕。被吓坏的女孩们放弃了轻浮，不得不依靠她 们新建的友谊来拯救她们自己。影片选景不错，问题就是剧情比较俗套，如果情节能结合紧密的逻辑，就 会增色不少。</p>
<p>
	<img alt="" src="http://www.fckb.net/data/attachment/forum/201112/19/200954otzb4m999l9gw9zy.jpg" /></p>
<p>
	<img alt="" src="http://www.fckb.net/data/attachment/forum/201112/19/2009578pdoa5bsts5mosja.jpg" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.netftp//dy44:piaohua@dy44.piaohua.com:3142/" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				&nbsp;&nbsp;<a href="ftp://dy44:piaohua@dy44.piaohua.com:3440/飘花电影piaohua.com远足惊魂DVD中字.mkv">ftp://dy44:piaohua@dy44.piaohua.com:3440/飘花电影piaohua.com远足惊魂DVD中字.mkv</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1643P10-31F7.jpg{/dede:field}
