{dede:field name='keywords'}雨果(雨果的冒险)/雨果的秘密DVD{/dede:field}
{dede:field name='description'}雨果(雨果的冒险)/雨果的秘密DVD中英双字2012最新美国奇幻冒险大迅雷下载、免费下载，雨果(雨果的冒险)/雨果的秘密DVD中英双字2012最新美国奇幻冒险大Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}雨果(雨果的冒险)/雨果的秘密DVD中英双字2012最新美国奇幻冒险大{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-02-18{/dede:field}
{dede:field name='body'}<p>
	<img src="http://img165.poco.cn/mypoco/myphoto/20120201/12/56643687201202011237246908253074355_004.jpg" /></p>
<p>
	<img src="http://img165.poco.cn/mypoco/myphoto/20120201/12/56643687201202011237246908253074355_005.jpg" /></p>
<p>
	导演: 马丁&middot;斯科塞斯<br />
	编剧: John Logan / Brian Selznick<br />
	主演: 阿沙&middot;巴特菲尔德 / 科洛&middot;莫瑞兹 / 本&middot;金斯利 / 萨莎&middot;拜伦&middot;科恩 / 裘德&middot;洛 / 雷&middot;温斯顿 / 克里斯托弗&middot;李 / 理查德&middot;格雷弗斯 / 海伦&middot;麦克洛瑞 / 弗朗西斯&middot;德&middot;拉&middot;图瓦<br />
	类型: 剧情 / 悬疑 / 奇幻 / 冒险 / 家庭<br />
	官方网站: <a href="http://www.hugomovie.com/">www.hugomovie.com/</a><br />
	制片国家/地区: 美国<br />
	语言: 英语<br />
	上映日期: 2011-11-23(美国)<br />
	片长: 127分钟<br />
	又名: 雨果的巴黎奇幻历险(港) / 雨果的冒险(台) / 雨果的秘密 / 雨果&middot;卡布里特的发明 / The Invention of Hugo Cabret<br />
	IMDb链接: tt0970179</p>
<p>
	<br />
	剧情简介</p>
<p>
	　　故事发生在上世纪30年代末巴黎一个繁忙火车站，主人公12岁孤儿雨果藏匿与墙壁后的暗窄通道里，会在每个夜晚的烛光下给火车站的27座时钟一丝不苟地上油、校准；死去的父亲给他留下的唯一遗产便是神秘笔记和一台旁人眼中完全是垃圾的机器人，雨果从一本木刻书得知这个机器人可以写字作画&mdash;&mdash;如果有天他能把它修好。<br />
	　　影片其他主要角色包括车站玩具店的老板乔治斯、他的孙女伊莎贝拉，以及另外一个有钱人家的小女孩。雨果为了得到修理机器人的零件到玩具店偷东西，最终发现古怪老板原来就是隐姓埋名的乔治&middot;梅里耶，他的《月球旅行记》是雨果父亲生前最喜欢的电影。</p>
<p>
	<br />
	◎影片截图</p>

<p>
	<img src="http://img165.poco.cn/mypoco/myphoto/20120201/12/56643687201202011237246908253074355_002.jpg" /></p>
<p>
	<img src="http://img165.poco.cn/mypoco/myphoto/20120201/12/56643687201202011237246908253074355_001.jpg" /></p>
<p>
	<img src="http://img165.poco.cn/mypoco/myphoto/20120201/12/56643687201202011237246908253074355_000.jpg" /></p>

<p>
	<img alt="" src="http://img.album.pchome.net/48/32/32/45/7f0d70cca03c5e1e0177a779280d98d1.2011" /></p>

<p>
	<img alt="" src="http://img.album.pchome.net/48/32/32/45/9e7afcc675a65c9067d252fe46846118.2011" /></p>

<p>
	<img alt="" src="http://img.album.pchome.net/48/32/32/45/76c5cb00c8ab673bf5ec9aadf1557053.2011" /></p>
<p>
	<img alt="" src="http://img.album.pchome.net/48/32/32/45/eece65f278b23a97ad9edf13aac0d904.2011" /></p>
<p>
	[下载地址]： &nbsp;<img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" /></p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2731/飘花电影piaohua.com雨果(雨果的冒险)TS中英双字.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2731/飘花电影piaohua.com雨果(雨果的冒险)TS中英双字.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2842/飘花电影piaohua.com雨果的秘密DVD中英双字.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2842/飘花电影piaohua.com雨果的秘密DVD中英双字.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15921P-1G64.jpg{/dede:field}
