{dede:field name='keywords'}特种部队：眼镜蛇的崛起/百战英{/dede:field}
{dede:field name='description'}特种部队：眼镜蛇的崛起/百战英雄/义勇群英之毒蛇风暴[TC国语＋迅雷下载、免费下载，特种部队：眼镜蛇的崛起/百战英雄/义勇群英之毒蛇风暴[TC国语＋Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}特种部队：眼镜蛇的崛起/百战英雄/义勇群英之毒蛇风暴[TC国语＋{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-03-01{/dede:field}
{dede:field name='body'}<p>
	<img src="http://img.album.pchome.net/54/71/09/13/6bff5d812ce12717496d7eea3b1321fa.jpg" /></p>
<p>
	<br />
	◎译　　名　《特种部队：眼镜蛇的崛起/百战英雄/义勇群英之毒蛇风暴》09美国最新动作科幻大片<br />
	◎片　　名　G.I. Joe: Rise of Cobra<br />
	◎上　　映　2009年08月07日<br />
	◎年　　代　2009<br />
	◎国　　家　美国<br />
	◎类　　别　动作/科幻/惊悚/冒险<br />
	◎语　　言　国语配音/ 英语<br />
	◎字　　幕　中英文字幕<br />
	◎IMDB评分 6.3/10 (1,087 votes)&nbsp;<br />
	◎文件格式　XviD + MP3<br />
	◎视频尺寸　624 x 256<br />
	◎文件大小　1CD 49 x 15MB<br />
	◎片　　长　109 Mins<br />
	◎导　　演　斯蒂芬&middot;索莫斯 Stephen Sommers◎主　　演　丹尼斯&middot;奎德 Dennis Quaid ....General Hawk<br />
	　　　　　　查宁&middot;塔图姆 Channing Tatum ....Duke<br />
	　　　　　　西耶娜&middot;米勒 Sienna Miller ....The Baroness<br />
	　　　　　　雷&middot;帕克 Ray Park ....Snake Eyes<br />
	　　　　　　瑞秋&middot;尼科尔斯 Rachel Nichols ....Shana &#39;Scarlett&#39; O&#39;Hara<br />
	　　　　　　约瑟夫&middot;高登-莱维特 Joseph Gordon-Levitt ....Cobra Commander<br />
	　　　　　　阿德沃尔&middot;阿吉纽依-艾格拜吉 Adewale Akinnuoye-Agbaje ....Heavy Duty<br />
	　　　　　　马龙&middot;韦恩斯 Marlon Wayans ....Ripcord<br />
	　　　　　　萨伊德&middot;塔格马奥 Sa&iuml;d Taghmaoui ....Breaker<br />
	　　　　　　李秉宪 Byung-hun Lee ....Storm Shadow<br />
	　　　　　　阿诺德&middot;沃斯洛 Arnold Vosloo ....Zartan<br />
	　　　　　　布兰登&middot;费舍 Brendan Fraser ....<a href="http://www.eee4.cn/" target="_blank">3e</a>Gung Ho<br />
	　　　　　　乔纳森&middot;普雷斯 Jonathan Pryce ....U.S. President<br />
	　　　　　　卡罗莱娜&middot;科库娃 Karolina Kurkova ....Courtney A. Kreiger / Cover girl<br />
	　　　　　　Brittany Alexis Palmer ....Dancer<br />
	　　　　　　David Jean Thomas ....British N.A.T.O. General<br />
	　　　　　　Jabbaar George ....Viper Guard<br />
	　　　　　　Jerald Garner ....Cobra Tech<br />
	　　　　　　Gunner Wright ....Secret Sevice Agent<br />
	　　　　　　Tom Ohmer ....Special Ops Soldier (uncredited)<br />
	　　　　　　克里斯托弗&middot;埃克莱斯顿 Christopher Eccleston ....Destro<br />
	　　　　　　Brandon Soo Hoo ....Young Storm Shadow<br />
	　　　　　　Leo Howard ....Young Snake Eyes<br />
	　　　　　　Michael Benyaer ....Flight Control<br />
	　　　　　　考特妮&middot;弗莱明 Courtney Fleming ....Security Tech<br />
	　　　　　　Gerald Okamura ....The Hard Master<br />
	　　　　　　Elena Evangelo ....Presidential Aide<br />
	　　　　　　Michael Broderick ....Screaming Man<br />
	　　　　　　大卫&middot;莫瑞 David Murray ....McCullen 1641<br />
	　　　　　　Kellie Matteson ....Control Room Tech<br />
	　　　　　　波顿&middot;佩雷兹 Burton Perez ....Bravo<br />
	<br />
	◎分　　级　Not Yet Rated<br />
	◎制作公司　Di Bonaventura Pictures [美国]<br />
	　　　　　　Hasbro Inc. [美国]<br />
	　　　　　　派拉蒙影业公司 [美国]<br />
	　　　　　　The Sommers Company [美国]<br />
	◎发行公司　派拉蒙影业公司 [美国]<br />
	◎官方网站　http://www.gijoemovie.com/<br />
	◎影片成本　N/A<br />
	<br />
	◎简　　介　<br />
	<br />
	　　影片改编自同名美国热门漫画，是派拉蒙继《变形金刚》后又一部根据孩之宝玩具改编的大制作电影，恐怖组织&ldquo;眼镜蛇&rdquo;（Cobra）企图征服世界，美国ZhengFu为了保卫国家而组成了特种部队－－G.I.Joe。杜克领导特种部队，为了抵御邪恶的眼镜蛇头领及其部下，发誓不论何时何地要为自由而战，赴汤蹈火，除暴安良以伸张正义。战斗不断升级，对决一触即发&hellip;&hellip;</p>
<p>
	　　最近，地球上出现了一个极其神秘的恐怖组织，它的名字叫&quot;眼镜蛇&quot;，而让&quot;眼镜蛇&quot;闻名全球的原因，则是源自其对埃菲尔铁塔的一次恐怖行动，在&quot;眼镜蛇&quot;的恐怖轰炸之下，这座法国的标志性建筑物顷刻之间化为乌有。很显然，&quot;眼镜蛇&quot;的这次行动只是一个开始，它向全世界宣告&quot;眼镜蛇&quot;的成立，而他们的目的则隐藏得更深，许多国家开始感到不安，因为他们不知道什么时候&quot;眼镜蛇&quot;的恐怖行径就会落到自己的国家当中，世界陷入了恐慌状态。</p>
<p>
	　　联合国对此也感到大为棘手，因此这时候，总部设在布鲁塞尔的一支秘密行动小组就开始发威了他的威力。这支名为G.I. JOE的特种部队由霍克将军（丹尼斯&middot;奎德饰）担任领头羊，手下高手云集，副指挥官是公爵（查宁&middot;塔图姆饰），参加过越南的他曾经与霍克一起多次出生入死；红发女（蕾切尔&middot;尼科尔斯饰）是一个武术高手，她的身手可不比男人差；除此之外还有专职执行高空任务的开伞索（马龙&middot;韦恩斯饰）、会七国语言的通讯员&ldquo;断路器&rdquo;（萨伊德&middot;塔马乌伊饰）、军火专家&ldquo;重载&rdquo;（阿德沃尔&middot;阿吉纽依－艾格拜吉饰）、沉默寡言的&ldquo;蛇眼&rdquo;（雷&middot;帕克饰）等12名成员。他们开始追查行动，很快查明了&ldquo;眼镜蛇&rdquo;的的阴谋，而他们首先要解决掉的是给&ldquo;眼镜蛇&rdquo;提供军火支持的战争狂人的迪斯特罗（克里斯托弗&middot;埃克莱斯顿饰）。而&ldquo;眼镜蛇&rdquo;组织里也有着不少心狠手辣的铁腕人物，例如外表性感漂亮，心肠却狠毒如蛇蝎的&ldquo;男爵夫人&rdquo;（西耶娜&middot;米勒饰）就是当中的代表人物。除此之外，还有与蛇眼是兄弟的白幽灵（李秉宪饰），他一直在&ldquo;眼镜蛇&rdquo;与G.J. JOE之间摇摆不定。</p>
<p>
	　　G.J. JOE为阻止&quot;眼镜蛇&quot;的阴谋而与其展开大战，随着两方战斗的白热化，原本一直深藏不露的&quot;眼镜蛇&quot;组织头目也逐渐显露出真身，他的真实身份会令G.J. JOE的成员大吃一惊&hellip;&hellip;</p>
<p>
	【剧照】：</p>
<p>
	<img src="http://img.album.pchome.net/54/70/81/43/fe65929eb9bf69ddbbbed0db71664232.jpg" />&nbsp;<br />
	<img src="http://img.album.pchome.net/54/70/81/43/19e96294e5fdadde4a51966c89ac3220.jpg" />&nbsp;<br />
	<img src="http://img.album.pchome.net/54/70/81/43/a9c175d2246b76c50ee586abf7200b3c.jpg" />&nbsp;<br />
	<img src="http://img.album.pchome.net/54/70/81/43/d4724a8d6f3572731cf3286ec29d0213.jpg" />&nbsp;<br />
	<img src="http://img.album.pchome.net/54/70/81/43/f62cd297b60e84155a1d3e24f7c72932.jpg" />&nbsp;<br />
	<img src="http://img.album.pchome.net/54/70/81/43/ccda91e30a44a7d80c28833cb23b164f.jpg" /></p>
<p>
	<br />
	一句话评论</p>
<p>
	一部力图让带着小孩的家长感到满意的、无公害的电影，只是其他观众一定会觉得口味实在太清淡了。<br />
	&mdash;&mdash;《综艺》</p>
<p>
	影片本身能够拍出来就是一件不可思议的事了，因为如此缺乏剧情的故事实在很难想像它变成电影之后会有多少观众卖帐。<br />
	&mdash;&mdash;《纽约时报》</p>
<p>
	可以肯定一点，《特种部队》是有史以来关于战争这类题材中最幼稚的成人电影。<br />
	&mdash;&mdash;FilmShaft.com</p>
<p>
	幕后制作</p>
<p>
	　　动作玩偶变英雄</p>
<p>
	　　G.I. JOE：光是提到这个名字，就会让人想到英雄主义、爱国主义和各种严格的军事训练。孩之宝玩具公司于1964年推出G.I. JOE这个玩偶，立刻就受到数百万小朋友的欢迎。孩之宝玩具公司总裁兼执行长，也是《特种部队：眼镜蛇的崛起》一片的制片布莱恩&middot;戈德诺说：&ldquo;所谓的&lsquo;动作玩偶&rsquo;是个全新的名词，G.I. JOE玩偶推出之前，男孩子绝对不会玩像是芭比娃娃的那种洋娃娃或是小玩偶，但是每个男孩子都想要一个动作英雄玩偶。&rdquo;布莱恩&middot;戈德诺还说：&ldquo;这个系列的玩偶吸引了全球的粉丝，让它在20世纪80年代成为全球最成功的系列玩具。&rdquo;孩之宝玩具公司和惊奇漫画合作，随后推出G.I. JOE特种部队的漫画系列。惊奇漫画的一名年轻编辑赖瑞&middot;哈玛负责这项计划，哈玛说：&ldquo;当时玩具公司这些玩偶只着重在这些玩偶的造型，但是却没有任何故事背景，于是我们就得想出精彩的故事。我们认为这些特种部队队员一定要有敌人才能进行战斗，于是我们发想出一个叫眼镜蛇的神秘组织，他们是漫画中的坏蛋，特种部队则是和他们对立的英雄，于是故事就从这里开始。&rdquo;</p>
<p>
	　　为了将G.I. JOE特种部队搬上银幕，制片人洛伦佐&middot;迪&middot;博纳文图拉又请来《加勒比海盗》三部曲的编剧斯图尔特&middot;比蒂来助阵，将G.I. JOE特种部队的经典角色注入生命。导演斯蒂芬&middot;索莫斯说：&ldquo;很多人从小到大都玩过G.I. JOE特种部队的系列玩偶，而且对漫画和卡通影集的故事非常熟悉，我们有责任忠于这些角色和故事，更不想让二、三十年来的忠实粉丝失望。&ldquo;像《特种部队：眼镜蛇的崛起》这种改编自玩具系列的电影想要成功，不只是必须满足忠实粉丝，也要吸引全新的观众，让他们体验这部电影精彩刺激的冒险。</p>
<p>
	　　执行制片戴维&middot;沃马克说：&ldquo;我们身为电影人，必须服侍两个主人，必须满足忠实粉丝的期望，同时也希望这部电影能够吸引对G.I. JOE特种部队完全不熟悉的观众。&rdquo;导演斯蒂芬&middot;索莫斯知道该怎么同时满足这两种观众群，他说：&ldquo;我们会忠实塑造G.I. JOE特种部队个性鲜明的角色，而且除了从漫画和卡通影集的故事中撷取灵感之外，我们也添加更多故事细节和背景，好让这部电影有一个更完整的故事。&rdquo;编剧斯图尔特&middot;比蒂说：&ldquo;只有G.I. JOE特种部队的故事中才有这种武器，而且是忠实粉丝造就了G.I. JOE特种部队的成功，所以我们必须听粉丝的意见，了解他们的期望，唯一的方法就是自己也成为忠实粉丝。&rdquo;</p>
<p>
	　　逼真细节打造超炫视觉</p>
<p>
	　　虽然导演斯蒂芬&middot;索莫斯曾经执导过规模庞大的冒险动作巨片《木乃伊》、《木乃伊2》，但是拍摄《特种部队：眼镜蛇的崛起》一片的困难更大。《特种部队：眼镜蛇的崛起》的工作人员短时间内搭建了168座布景。许多最大的布景都是在道尼摄影棚内搭建，包括巨大的都市战斗层（位于特种部队的地下基地）、特种部队潜艇、MARS（军备研发中心）的飞弹发射井等。特种部队的地下基地是全片最令人叹为观止的布景。它总共有好几层，艺术指导艾德&middot;维勒说：&ldquo;地下基地包括都市战斗区、海底战争区、指挥中心、像迷宫一样的走廊、医疗室、娱乐休闲室等等。&rdquo;导演桑莫斯说：&ldquo;那座布景超大的，它甚至有一架可以把飞机升到地面的电梯。&rdquo;饰演男爵夫人的西耶娜&middot;米勒说：&ldquo;最神奇的是，这一切都能使用。如果墙壁上有电灯开关，打开来灯就会亮。&rdquo;饰演斯嘉蕾的瑞秋&middot;尼科尔斯也说：&ldquo;这部电影充满了超逼真的细节，绝对会让忠实粉丝看得目不暇给。&rdquo;</p>
<p>
	　　片中的军用车辆全都是工作人员打造出来的，而且同一款车辆必须打造好几辆，因为有些是用来拍外观，有些则是用来拍特技动作或是特效镜头。这些都是G.I.JOE特种部队玩偶系列的忠实粉丝熟悉的车辆或飞机，执行制片戴维&middot;沃马克说：&ldquo;片中出现的各种飞行具、车辆和水底载具多到令人咋舌，而且都是出于导演的想象。片中有&lsquo;狂嚎&rsquo;运输车、MARS军备研发中心打造的下一代战机，还有螳螂号攻击机以及鲨鱼号水底攻击艇。这些全都是为了这部电影从无到有，设计及打造出来的载具。&rdquo;这些军事装备、战机、攻击潜艇等等，都是下一代的科技产品。片中最重要的先进科技就是纳米科技，特种部队和眼镜蛇组织在片中都有用到纳米科技。执行制片艾瑞克&middot;霍森说：&ldquo;最大的挑战是设计出观众没有看过的东西。&rdquo;其实他们不必绞尽脑汁，因为纳米科技已经出现在许多科学期刊，就连《时代杂志》和《新闻周刊》都有相关报导，工作人员只是利用想象力再进一步设计出各式各样的酷炫道具。</p>
<p>
	　　演员要接受严苛的军事训练</p>
<p>
	　　《特种部队：眼镜蛇的崛起》是一部战争动作片，片中使用大量的武器，所以主要演员都接受了武器训练，出乎他们的意料之外，训练的时候用的竟然是实弹。负责训练的R&middot;A&middot;朗德说：&ldquo;他们必须知道实弹射击的感觉是什么，包括射击的后坐力和真正的枪声，他们必须学会怎么装子弹、怎么使用武器、怎么把武器交还给道具师。这一切都很重要。&rdquo;武器训练让演员习惯开枪的后坐力，但是要让他们使用武器时看起来很自然又是另外一回事，于是剧组请来保罗西诺中校教每一个演员真正的士兵是怎么拿枪的。他说：&ldquo;我不希望刚退伍的军人看了这部电影说：&lsquo;他们只是演员&rsquo;我希望他们看了会说：&lsquo;这家伙真的很会用武器&rsquo;。&rdquo;保罗&middot;西诺中校也会指正演员，让他们说出真正的军事术语，并且指出剧本上哪些地方不符合军事训练。他说：&ldquo;我可能会纠正片中士兵和长官说的话有哪里不对，或是片中有提到吉普车的部份。大家都以为陆军还在用吉普车，其实我们从七十年代中期就已经不用吉普车了。&rdquo;</p>
<p>
	　　制作小组很坚持《特种部队：眼镜蛇的崛起》一片的每场戏都要符合军事训练，执行制片艾瑞克&middot;霍森说：&ldquo;G.I.　JOE就代表了美国大兵，所以也代表了美国军方。&rdquo;孩之宝玩具公司总裁兼执行长布莱恩&middot;戈德诺则说：&ldquo;G.I. JOE从一开始就强调英雄主义以及军方每个英勇的男女士兵。这部电影虽然设定在不久的未来，但是仍然根据当今的现实。&rdquo;把《特种部队：眼镜蛇的崛起》拍得让忠实粉丝满意，同时也让不熟悉这个作品的观众看得过瘾并不容易，但是这部电影办到了。编剧斯图尔特&middot;比蒂说：&ldquo;这是一项艰巨的任务，不过我们花了很多工夫确定忠实粉丝会很满意，我们希望他们会说：&lsquo;这是我们这么多年来一直想看的电影。&rsquo;&rdquo;导演斯蒂芬&middot;索莫斯总结说：&ldquo;拍这部电影的过程真的很开心，每天都很好玩，每天都有令人兴奋的时刻。这是一群人每天一起工作，享受拍片的乐趣，我也希望观众能享受这部精采刺激的电影。&rdquo;</p>
<p>
	花絮</p>
<p>
	&middot;原本公爵一角计划让萨姆&middot;沃辛顿出演，但因为拍摄《特种部队》与《阿凡达》冲突，因此最后萨姆&middot;沃辛顿推掉了《特种部队》的片约。</p>
<p>
	&middot;影片开拍后的最初两个月，丹尼斯&middot;奎德就拍完了他所有的戏份。</p>
<p>
	&middot;为了准备出演男爵夫人这个角色，西耶娜&middot;米勒花了四个月的时间来进行体能训练，增加了5磅的肌肉，同时也学会了实弹射击。</p>
<p>
	&middot;查宁&middot;塔图姆原本不想出演这部电影，因为他认为这样的电影是在美化战争。当他看完本片剧本之后，他认为本片更像是一部科幻动作片，因此接拍了本片。</p>
<p>
	【电影截图】：</p>
<p>
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://img.album.pchome.net/54/71/62/77/29eeeb703b5d680f1b8b4189476630c0.jpg');" src="http://img.album.pchome.net/54/71/62/77/29eeeb703b5d680f1b8b4189476630c0.jpg" /><br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://img.album.pchome.net/54/71/62/77/d6b1c0c07eb98303eff2b3b479284228.jpg');" src="http://img.album.pchome.net/54/71/62/77/d6b1c0c07eb98303eff2b3b479284228.jpg" /><br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://img.album.pchome.net/54/71/62/77/d1bf47e5ff5dd7f328d7ecba65bad56c.jpg');" src="http://img.album.pchome.net/54/71/62/77/d1bf47e5ff5dd7f328d7ecba65bad56c.jpg" /><br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://img.album.pchome.net/54/71/62/77/bba7fb04d8eaf688b0b5e089085a1bfe.jpg');" src="http://img.album.pchome.net/54/71/62/77/bba7fb04d8eaf688b0b5e089085a1bfe.jpg" />&nbsp;</p>
<br />
<p>
	（一律使用<a href="http://www.eee4.com/soft.htm" target="_blank">迅雷下载</a>）<br />
	09美国最新动作科幻大片《特种部队：眼镜蛇的崛起》DVD中英双字 [下载地址]：<img border="0" src="http://www.eee4.com/templets/img/down.jpg" /><br />
	CD1：</p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://3e:3e@www2.eee4.com:775/[3E电影站www.eee4.cn]特种部队DVD中英双字CD1.rmvb" target="_blank">ftp://3e:3e@www2.eee4.com:775/[3E电影站www.eee4.cn]特种部队DVD中英双字CD1.rmvb</a></td>
		</tr>
	</tbody>
</table>
<p>
	CD2：</p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://3e:3e@www2.eee4.com:775/[3E电影站www.eee4.cn]特种部队DVD中英双字CD2.rmvb" target="_blank">ftp://3e:3e@www2.eee4.com:775/[3E电影站www.eee4.cn]特种部队DVD中英双字CD2.rmvb</a></td>
		</tr>
	</tbody>
</table>
<br />
<p>
	（一律使用<a href="http://www.eee4.com/soft.htm" target="_blank">迅雷下载</a>）<br />
	09美国最新动作科幻大片《特种部队》1280高清预告片 [推荐观看]：<img border="0" src="http://www.eee4.com/templets/img/down.jpg" /></p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://4e:4e@vip.eee4.cn:626/[www.eee4.cn提供]特种部队1280高清预告片.rmvb" target="_blank">ftp://4e:4e@vip.eee4.cn:626/[www.eee4.cn提供]特种部队1280高清预告片.rmvb</a></td>
		</tr>
	</tbody>
</table>
<br />
<p>
	09美国最新动作科幻大片《特种部队》TC国语抢先版 [不建议下载]：<img border="0" src="http://www.eee4.com/templets/img/down.jpg" /></p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://5e:5e@www2.eee4.com:662/[www.eee4.cn提供]特种部队∶眼镜蛇的崛起TC国语抢先版.rmvb" target="_blank">ftp://5e:5e@www2.eee4.com:662/[www.eee4.cn提供]特种部队∶眼镜蛇的崛起TC国语抢先版.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15924220-52R0.jpg{/dede:field}
