<?php
$z[0]=Array("field","量子启示录[DVD中英双字]迅雷下",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","量子启示录[DVD中英双字]迅雷下载、免费下载，量子启示录[DVD中英双字]Gvod高清在线播放，剧情介绍等。",72,212);
$z[1][4]['name']="description";
$z[2]=Array("field","量子启示录[DVD中英双字]",214,275);
$z[2][4]['name']="title";
$z[3]=Array("field","",277,316);
$z[3][4]['name']="writer";
$z[4]=Array("field","",318,357);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-06-15",359,409);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",411,448);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://3e:3e@d8.3edyy.com:167/【3E电影院www.eee4.cc】量子启示录DVD中英双字.rmvb\" target=_blank>ftftp://3e:3e@d8.3edyy.com:167/【3E电影院www.eee4.cc】量子启示录DVD中英双字.rmvb</A></TD></TR></TBODY></TABLE></div><ul class=\"mmlist",450,716);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MPY0920-1Q59.jpg",718,800);
$z[8][4]['name']="litpic";

?>