<?php
$z[0]=Array("field","隔山有眼/深山大屠杀/魔山2部BD",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","隔山有眼/深山大屠杀/魔山2部BD中英双字1024/1280高清迅雷下载、免费下载，隔山有眼/深山大屠杀/魔山2部BD中英双字1024/1280高清Gvod高清在线播放，剧情介绍等。",72,266);
$z[1][4]['name']="description";
$z[2]=Array("field","隔山有眼/深山大屠杀/魔山2部BD中英双字1024/1280高清",268,356);
$z[2][4]['name']="title";
$z[3]=Array("field","",358,397);
$z[3][4]['name']="writer";
$z[4]=Array("field","",399,438);
$z[4][4]['name']="source";
$z[5]=Array("field","2012-05-10",440,490);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",492,529);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://3e:3e@vip.eee4.cn:618/[www.eee4.cn提供]深山大屠杀1BD中英双字1024x556高清版.rmvb\" target=\"_blank",531,671);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MO441a0-564G.jpg",673,755);
$z[8][4]['name']="litpic";

?>