{dede:field name='keywords'}科学小怪蛋/伊戈尔/异想天开BD中{/dede:field}
{dede:field name='description'}科学小怪蛋/伊戈尔/异想天开BD中英双字1024/1280高清迅雷下载、免费下载，科学小怪蛋/伊戈尔/异想天开BD中英双字1024/1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}科学小怪蛋/伊戈尔/异想天开BD中英双字1024/1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-04-30{/dede:field}
{dede:field name='body'}<p>
	<img src="http://img.album.pchome.net/54/68/29/09/02839a42e7ad2c0540d1af7b5efef7ec.jpg" /></p>
<p>
	◎译　　名　《伊戈尔/异想天开/科学小怪蛋》08最新喜剧大片BD中英双字幕（高清版）<br />
	◎片　　名　Igor<br />
	◎年　　代　2008<br />
	◎国　　家　美国/法国<br />
	◎类　　别　动画/喜剧<br />
	◎语　　言　英语<br />
	◎字　　幕　中英双字<br />
	◎IMDB评分&nbsp; 6.1/10&nbsp; 1,204 votes<br />
	◎文件格式　X264 + AAC<br />
	◎视频尺寸　880 x 478<br />
	◎文件大小　1CD<br />
	◎片　　长　87 mins<br />
	◎导　　演　Anthony Leondis<br />
	◎主　　演　Christian Slater 克里斯汀&middot;史莱特 Christian Slater<br />
	　　　　　　Steve Buscemi 史蒂夫&middot;布西密 Steve Buscemi<br />
	　　　　　　John Cleese 约翰&middot;克立斯 John Cleese<br />
	　　　　　　Jeremy Piven 杰里米&middot;皮文 Jeremy Piven<br />
	　　　　　　Jennifer Coolidge 詹妮佛&middot;库里奇 Jennifer Coolidge<br />
	　　　　　　Jay Leno ....King Malbert (voice)<br />
	　　　　　　Molly Shannon 莫莉&middot;香侬 Molly Shannon<br />
	　　　　　　John Cusack 约翰&middot;库萨克 John Cusack<br />
	　　　　　　Eddie Izzard 艾迪&middot;伊扎德 Eddie Izzard<br />
	　　　　　　Sean Hayes 西恩&middot;海耶斯 Sean Hayes<br />
	　　　　　　Arsenio Hall ....Carl Cristall (voice)<br />
	　　　　　　James Lipton ....Himself<br />
	　　　　　　Paul Vogt ....Fly-headed Guy (voice)<br />
	<br />
	◎简　　介　<br />
	<br />
	　　故事发生在一个充满科学狂人和邪恶发明家的世界里，一个驼背的科学家助手，内向又不自信，还常常被人欺负。他一直梦想能出类拔萃，并赢得一年一度的&ldquo;罪恶科学奖&rdquo;。为此他经过努力研究，终于制造出了一个高大强壮的机器人，只不过完工后却发现，这个成品与自己当初想象的相差甚远&hellip;&hellip;<br />
	<br />
	&nbsp; &nbsp; 邪恶科学竞赛即将开跑，比赛内容是看谁能发明出最厉害的科学怪物！<br />
	<br />
	&nbsp; &nbsp; 一个疯狂科学家的驼背助理Igor一心的梦想就是参加比赛，但他善良的心却无法创造最邪恶的作品，疯狂科学家激励他以「玩游戏来打败邪恶玩具」的心态参加，但当Igor善良的心与邪恶的发明冲突时，让他的发明变成一场精采的冒险&hellip;</p>

<p>
	【电影截图】：<br />
	电影来源：www.eee4.com</p>
<p>
	<br />
	<br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://img.album.pchome.net/54/68/44/87/89e1b48982df2b5282d28e59ab06f884.jpg');" src="http://img.album.pchome.net/54/68/44/87/89e1b48982df2b5282d28e59ab06f884.jpg" />&nbsp;<br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://img.album.pchome.net/54/68/44/87/eeb31ff0da663feedec4b067c0e78184.jpg');" src="http://img.album.pchome.net/54/68/44/87/eeb31ff0da663feedec4b067c0e78184.jpg" />&nbsp;<br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://img.album.pchome.net/54/68/44/87/a122bc13906119ad8df8728b6052ca1f.jpg');" src="http://img.album.pchome.net/54/68/44/87/a122bc13906119ad8df8728b6052ca1f.jpg" />&nbsp;<br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://img.album.pchome.net/54/68/44/87/9ce974cd733b4b7d21d0f390e586caf9.jpg');" src="http://img.album.pchome.net/54/68/44/87/9ce974cd733b4b7d21d0f390e586caf9.jpg" /></p>
<p>
	08最新喜剧大片《科学小怪蛋》BD中英双字幕（高清版） －来自[3E电影站 eee4.com]：<img border="0" src="http://www.eee4.com/templets/img/down.jpg" /></p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://e20:e20@xl2.eee4.com:9916/[3E电影站www.eee4.com]科学小怪蛋BD中英双字高清版.rmvb" target="_blank">ftp://e20:e20@xl2.eee4.com:9916/[3E电影站www.eee4.com]科学小怪蛋BD中英双字高清版.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3320/飘花电影piaohua.com异想天开BD中英双字1024高清.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3320/飘花电影piaohua.com异想天开BD中英双字1024高清.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3320/飘花电影piaohua.com异想天开BD中英双字1024高清.mkv">ftp://dy44:piaohua@dy44.piaohua.com:3320/飘花电影piaohua.com异想天开BD中英双字1024高清.mkv</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3320/飘花电影piaohua.com异想天开BD中英双字1280高清.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3320/飘花电影piaohua.com异想天开BD中英双字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15H3910-541N.jpg{/dede:field}
