{dede:field name='keywords'}三尖树时代(三脚妖之日)高清1280{/dede:field}
{dede:field name='description'}三尖树时代(三脚妖之日)高清1280版BD中字2010英国科幻恐怖动作大迅雷下载、免费下载，三尖树时代(三脚妖之日)高清1280版BD中字2010英国科幻恐怖动作大Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}三尖树时代(三脚妖之日)高清1280版BD中字2010英国科幻恐怖动作大{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-02-18{/dede:field}
{dede:field name='body'}<p>
	<img src="http://img165.poco.cn/mypoco/myphoto/20120218/11/56643687201202181156461901621390531_004.jpg" /></p>

<p>
	◎译　　名　三尖树时代/三脚妖之日/三叶草在行动/三脚树时代<br />
	◎片　　名　The Day of the Triffids<br />
	◎年　　代　2009<br />
	◎国　　家　英国/加拿大<br />
	◎类　　别　动作/恐怖/科幻/惊悚<br />
	◎语　　言　英语<br />
	◎字　　幕　中字<br />
	◎IMDB评分 5.7/10 (1373 votes)<br />
	◎文件格式　高清1280版BD-RMVB<br />
	◎视频尺寸　1280 x 720<br />
	◎文件大小　1CD 822MB<br />
	◎片　　长　93 mins<br />
	◎导　　演　尼克&middot;库帕斯 Nick Copus<br />
	◎主　　演　布赖恩&middot;考克斯 Brian Cox .... Dennis Mason (unconfirmed)<br />
	詹神&middot;普里斯特里 Jason Priestley .... Coker (unconfirmed)<br />
	道格利&middot;斯科特 Dougray Scott .... Bill Mason (unconfirmed)<br />
	乔莉&middot;理查森 Joely Richardson .... Jo Playton (unconfirmed)<br />
	范尼莎&middot;雷德格雷夫 Vanessa Redgrave .... Durrant (unconfirmed)<br />
	艾迪&middot;伊扎德 Eddie Izzard .... Torrence<br />
	艾文&middot;布莱纳 Ewen Bremner .... Walter (unconfirmed)<br />
	肖恩&middot;泰勒 Shane Taylor .... Osman (unconfirmed)<br />
	诺拉-简&middot;努内 Nora-Jane Noone .... Lucy<br />
	Genevieve O&#39;Reilly .... Michelle (unconfirmed)<br />
	托尼&middot;毛德斯莱 Tony Maudsley .... Policeman<br />
	Jenn Murray .... Susan<br />
	Adam Sinclair .... Ashdown<br />
	史蒂文&middot;埃尔德 Steven Elder .... Dr. Kotch<br />
	Forbes KB .... Fighting Blind Man<br />
	Julia Joyce .... Imogen<br />
	Simon Lowe .... The Producer<br />
	William Ilkley .... Jeff (unconfirmed)<br />
	Simon Naylor .... Ged<br />
	Karl Rhodes .... Lay Brother</p>
<p>
	◎简　　介　</p>
<p>
	　　《三角树时代》是英国科幻作家约翰&middot;温德姆（John Wyndham）1951年发表的灾难科幻小说，故事讲述了一场流星雨让绝大多数人类眼睛都瞎了，这时一种基因工程创造的超智能植物&ldquo;三角树&rdquo;乘机发动了对人类的攻击，大肆吞噬人类。<br />
	《三角树时代》1961年曾被英国人搬上过大银幕，1981年又被拍成电视剧，2009年BBC又将其再度制作成电视剧。</p>
<p>
	<br />
	&nbsp;</p>
<p>
	<img src="http://img165.poco.cn/mypoco/myphoto/20120218/11/56643687201202181156461901621390531_000.jpg" style="width: 600px; height: 338px" /></p>

<p>
	<img src="http://img165.poco.cn/mypoco/myphoto/20120218/11/56643687201202181156461901621390531_001.jpg" style="width: 600px; height: 338px" /></p>

<p>
	<img src="http://img165.poco.cn/mypoco/myphoto/20120218/11/56643687201202181156461901621390531_002.jpg" style="width: 600px; height: 338px" /></p>

<p>
	<img src="http://img165.poco.cn/mypoco/myphoto/20120218/11/56643687201202181156461901621390531_003.jpg" style="width: 600px; height: 338px" /></p>

<p>
	[下载地址]： &nbsp;<img border="0" src="/0701pic/allimg/120110/01223C617-5.jpg" /></p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				&nbsp;<a href="ftp://dy44:piaohua@dy44.piaohua.com:2842/飘花电影piaohua.com三尖树时代(三脚妖之日)高清1280版BD中字.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2842/飘花电影piaohua.com三尖树时代(三脚妖之日)高清1280版BD中字.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15920050-54N7.jpg{/dede:field}
