<?php
$z[0]=Array("field","寻枪[HD国语中字1024x576高清版]",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","寻枪[HD国语中字1024x576高清版]迅雷下载、免费下载，寻枪[HD国语中字1024x576高清版]Gvod高清在线播放，剧情介绍等。",73,227);
$z[1][4]['name']="description";
$z[2]=Array("field","寻枪[HD国语中字1024x576高清版]",229,297);
$z[2][4]['name']="title";
$z[3]=Array("field","",299,338);
$z[3][4]['name']="writer";
$z[4]=Array("field","",340,379);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-04-05",381,431);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",433,470);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://3e:3e@d6.3edyy.com:633/【3E看看www.3ekk.com】寻枪HD中字1024x576高清版.rmvb\" target=_blank>ftftp://3e:3e@d6.3edyy.com:633/【3E看看www.3ekk.com】寻枪HD中字1024x576高清版.rmvb</A></TD></TR></TBODY></TABLE></div><ul class=\"mmlist",472,742);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MP3CJ0-29613.jpg",744,826);
$z[8][4]['name']="litpic";

?>