{dede:field name='keywords'}心中的恶魔BD1280高清迅雷下载，{/dede:field}
{dede:field name='description'}心中的恶魔BD1280高清迅雷下载、免费下载，心中的恶魔BD1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}心中的恶魔BD1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-25{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://t.williamgates.net/image-9CCC_4FB2C073.jpg" style="width: 650px; height: 845px" /></p>
<p>
	◎译　　名　心中的恶魔/意大利驱魔揭秘(港)/心魔(台)<br />
	◎片　　名　The Devil Inside<br />
	◎年　　代　2012<br />
	◎国　　家　美国<br />
	◎类　　别　惊悚/恐怖<br />
	◎语　　言　英语<br />
	◎字　　幕　中英双字<br />
	◎IMDB评分 3.6/10 (9,423 votes)<br />
	◎IMDB链接 <a href="http://www.imdb.com/title/tt1560985" target="_blank">http://www.imdb.com/title/tt1560985</a><br />
	◎文件格式　XviD + MP3<br />
	◎视频尺寸　1280x 720<br />
	◎文件大小　1CD 700 MB<br />
	◎片　　长　83 Mins<br />
	◎导　　演　威廉&middot;布伦特&middot;贝尔 William Brent Bell<br />
	◎主　　演　费曼达&middot;安德蕾 Fernanda Andrade &nbsp;....Isabella Rossi<br />
	　　　　　　西蒙&middot;夸特曼 Simon Quarterman &nbsp;....Ben<br />
	　　　　　　伊万&middot;哈尔姆斯 Evan Helmuth &nbsp;....David<br />
	　　　　　　Ionut Grama &nbsp;....Michael<br />
	　　　　　　Suzan Crowley &nbsp;....Maria Rossi<br />
	　　　　　　Bonnie Morgan &nbsp;....Rosa<br />
	　　　　　　Brian Johnson &nbsp;....Lieutenant Dreyfus<br />
	　　　　　　Preston James Hillier &nbsp;....Male Reporter<br />
	　　　　　　达纳&middot;卡尼 D.T. Carney &nbsp;....Detective<br />
	　　　　　　Maud Bonanni &nbsp;....Aunt Sorlini<br />
	　　　　　　Marvin Duerkholz &nbsp;....Luke Castagna<br />
	　　　　　　Marius Florian &nbsp;....Serbian Pimp<br />
	　　　　　　Suzanne &nbsp;....Female Reporter<br />
	　　　　　　Les Mahoney &nbsp;....Coroner<br />
	　　　　　　Talyan Wright &nbsp;....Young Isabella<br />
	　　　　　　Luca Bovelli &nbsp;....Marco Sorlini (uncredited)<br />
	　　　　　　<br />
	<br />
	<br />
	◎简　　介　<br />
	<br />
	　　故事发生在意大利，一位女性被指控涉嫌在一场驱魔仪式中，发狂般谋杀三个人，而她的女儿对事实有所疑惑，为了找出事情的真相，将亲自参与这一系列未经授权的驱魔过程。<br />
	　　很多人被一个恶灵附身；只有她是被多重恶灵附身！1989年，119接到由玛莉亚罗斯（苏珊&middot;克萝蕾 Suzan Crowley 饰）打出的电话，她自首虐杀了3个人。20年后，她的女儿伊莎贝拉（费尔南达&middot;安德拉德 Fernanda Andrade 饰）试着深入挖掘案发当晚的真相，因此前往探视被禁锢在义大利专门治疗犯罪精神病的圣堤诺医院的母亲，以便确认20年前发生的惨绝人寰事件的缘由，究竟是 因母亲心智丧失或是当真被邪魔附身。伊莎贝拉聘请两位年轻驱魔师（赛门&middot;克特曼 Simon Quarterman 与 伊凡&middot;海慕特 Evan Helmuth 饰）利用结合科学和宗教的创新疗法治疗她母亲，迫使他们必须与附身在玛莉亚身上的四种邪恶灵体正面接触。<br />
	<br />
	花絮<br />
	<br />
	&middot;影片在罗马尼亚的布加勒斯特、意大利的罗马和梵蒂冈里取景拍摄。<br />
	<br />
	&middot;洛伦佐&middot;迪&middot;博纳文图拉和史蒂文&middot;施耐德为派拉蒙公司买下了这部电影。<br />
	<br />
	&middot;梵蒂冈开办的&ldquo;驱魔培训班&rdquo;不止吸引了本片的导演，更是吸引了马特&middot;巴格洛。后者特意跑去学习班里学习，并把自己的所见所闻写成了报告文学《仪式：今日之驱魔》。后来，这本纪实性的文学作品被改编成了另一部驱魔题材电影：《仪式》。</p>
<p>
	<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120524/20/62564813201205242019017405027424335_005.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120524/20/62564813201205242019017405027424335_002.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120524/20/62564813201205242019017405027424335_001.jpg" style="width: 720px; height: 405px" /><br />
	&nbsp;</p>
<p>
	【下载地址】</p>
<table bgcolor="#0099cc" border="0" cellpadding="10" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaobajie.com" target="_blank">http://www.xiaobajie.com</a></td>
		</tr>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy125:piaohua@dy125.piaohua.com:8097/飘花电影piaohua.com心中的恶魔BD中英双字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:8097/飘花电影piaohua.com心中的恶魔BD中英双字1280高清.rmvb</a></td>
		</tr>
		<tr>
		</tr>
	</tbody>
</table>
<br />{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1514RF-1BY.jpg{/dede:field}
