<?php
$z[0]=Array("sppage","",0,59);
$z[0][4]['sptype']="full";
$z[0][4]['srul']="1";
$z[0][4]['erul']="5";
$z[1]=Array("previewurl","http://www.piaohua.com/html/zhanzheng/2012/0505/24278.html",61,154);
$z[2]=Array("keywordtrim","",156,193);
$z[3]=Array("descriptiontrim","",195,240);
$z[4]=Array("item","\r\n   {dede:match}<title>[内容]</title>{/dede:match}\r\n   {dede:trim replace=\"\"}_迅雷下载_免费下载_飘花电影网{/dede:trim}\r\n   {dede:function}{/dede:function}\r\n",242,465);
$z[4][4]['field']="title";
$z[4][4]['value']="";
$z[4][4]['isunit']="";
$z[4][4]['isdown']="";
$z[5]=Array("item","\r\n   {dede:match}{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",465,605);
$z[5][4]['field']="writer";
$z[5][4]['value']="";
$z[5][4]['isunit']="";
$z[5][4]['isdown']="";
$z[6]=Array("item","\r\n   {dede:match}{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",605,745);
$z[6][4]['field']="source";
$z[6][4]['value']="";
$z[6][4]['isunit']="";
$z[6][4]['isdown']="";
$z[7]=Array("item","\r\n   {dede:match}发布时间：[内容]<br/>{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",745,907);
$z[7][4]['field']="pubdate";
$z[7][4]['value']="";
$z[7][4]['isunit']="";
$z[7][4]['isdown']="";
$z[8]=Array("item","\r\n   {dede:match}<div id=\"showinfo\">[内容]</div><ul class=\"mmlist\">{/dede:match}\r\n   {dede:trim replace=\"\"}<a([^>]*)>{/dede:trim}\r\n{dede:trim replace=\"\"}</a>{/dede:trim}\r\n{dede:trim replace=\"\"}<font([^>]*)>{/dede:trim}\r\n{dede:trim replace=\"\"}</font>{/dede:trim}\r\n{dede:trim replace=\"\"}<div([^.]*)>{/dede:trim}\r\n{dede:trim replace=\"\"}</div>{/dede:trim}\r\n{dede:trim replace=\"\"}<strong([^>]*)>{/dede:trim}\r\n{dede:trim replace=\"\"}</strong>{/dede:trim}\r\n{dede:trim replace=\"\"}<span([^>]*)>{/dede:trim}\r\n{dede:trim replace=\"\"}</span>{/dede:trim}\r\n{dede:trim replace=\"\"}[{/dede:trim}\r\n{dede:trim replace=\"\"}【{/dede:trim}\r\n   {dede:function}{/dede:function}\r\n",907,1626);
$z[8][4]['field']="body";
$z[8][4]['value']="";
$z[8][4]['isunit']="1";
$z[8][4]['isdown']="1";

?>