{dede:field name='keywords'}影子写手/枪手/代笔作家/影子灭{/dede:field}
{dede:field name='description'}影子写手/枪手/代笔作家/影子灭杀令[DVD中英双字]迅雷下载、免费下载，影子写手/枪手/代笔作家/影子灭杀令[DVD中英双字]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}影子写手/枪手/代笔作家/影子灭杀令[DVD中英双字]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2010-07-21{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://3e:3e@d8.3edyy.com:168/【3E电影院www.eee4.cc】影子写手DVD.rmvb" target="_blank{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MP3213Z-59554.jpg{/dede:field}
