<?php
$z[0]=Array("field","影子写手/枪手/代笔作家/影子灭",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","影子写手/枪手/代笔作家/影子灭杀令[DVD中英双字]迅雷下载、免费下载，影子写手/枪手/代笔作家/影子灭杀令[DVD中英双字]Gvod高清在线播放，剧情介绍等。",72,258);
$z[1][4]['name']="description";
$z[2]=Array("field","影子写手/枪手/代笔作家/影子灭杀令[DVD中英双字]",260,344);
$z[2][4]['name']="title";
$z[3]=Array("field","",346,385);
$z[3][4]['name']="writer";
$z[4]=Array("field","",387,426);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-07-21",428,478);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",480,517);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://3e:3e@d8.3edyy.com:168/【3E电影院www.eee4.cc】影子写手DVD.rmvb\" target=\"_blank",519,642);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MP3213Z-59554.jpg",644,727);
$z[8][4]['name']="litpic";

?>