<?php
$z[0]=Array("field","拯救世界的好人/没问题侠客修理",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","拯救世界的好人/没问题侠客修理世界[DVD中英双字]迅雷下载、免费下载，拯救世界的好人/没问题侠客修理世界[DVD中英双字]Gvod高清在线播放，剧情介绍等。",72,258);
$z[1][4]['name']="description";
$z[2]=Array("field","拯救世界的好人/没问题侠客修理世界[DVD中英双字]",260,344);
$z[2][4]['name']="title";
$z[3]=Array("field","",346,385);
$z[3][4]['name']="writer";
$z[4]=Array("field","",387,426);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-03-01",428,478);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",480,517);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://4e:4e@d8.3edyy.com:223/【3E看看www.3ekk.com】拯救世界的好人[DVD中英双字].rmvb\" target=_blank>ftftp://4e:4e@d8.3edyy.com:223/【3E看看www.3ekk.com】拯救世界的好人[DVD中英双字].rmvb</A></TD></TR></TBODY></TABLE></div><ul class=\"mmlist",519,795);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MQ4E920-5JX.jpg",797,878);
$z[8][4]['name']="litpic";

?>