<?php
$z[0]=Array("field","黄飞鸿之二：男儿当自强[BD国语",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","黄飞鸿之二：男儿当自强[BD国语中字1280x720高清版]迅雷下载、免费下载，黄飞鸿之二：男儿当自强[BD国语中字1280x720高清版]Gvod高清在线播放，剧情介绍等。",72,262);
$z[1][4]['name']="description";
$z[2]=Array("field","黄飞鸿之二：男儿当自强[BD国语中字1280x720高清版]",264,350);
$z[2][4]['name']="title";
$z[3]=Array("field","",352,391);
$z[3][4]['name']="writer";
$z[4]=Array("field","",393,432);
$z[4][4]['name']="source";
$z[5]=Array("field","2009-12-17",434,484);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",486,523);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://3e:3e@www2.3edyy.com:957/【3E电影院www.3edyy.com】黄飞鸿之二男儿当自强BD国语中字1280x720高清版.rmvb\" target=_blank>ftftp://3e:3e@www2.3edyy.com:957/【3E电影院www.3edyy.com】黄飞鸿之二男儿当自强BD国语中字1280x720高清版.rmvb</A></TD></TR></TBODY></TABLE><BR><FONT color=#ff0000 size=2><STRONG>2009/12/18 [下载地址]：<IMG src=\"httftp://www.eee4.cn/templets/img/down.jpg\" border=0></STRONG></FONT><BR>\r\n<TABLE style=\"BORDER-RIGHT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; BORDER-BOTTOM: #cccccc 1px dotted\" cellSpacing=0 cellPadding=6 width=\"95%\" align=center border=0>\r\n<TBODY>\r\n<TR>\r\n<TD style=\"WORD-WRAP: break-word\" bgColor=#fdfddf><A href=\"ftftp://3e:3e@www2.3edyy.com:960/【3E电影院www.3edyy.com】黄飞鸿之男儿当自强[BD国语中字1280x720高清].rmvb\" target=_blank>ftftp://3e:3e@www2.3edyy.com:960/【3E电影院www.3edyy.com】黄飞鸿之男儿当自强[BD国语中字1280x720高清].rmvb</A></TD></TR></TBODY></TABLE></div><ul class=\"mmlist",525,1555);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MQ32J50-1X96.jpg",1557,1639);
$z[8][4]['name']="litpic";

?>