{dede:field name='keywords'}黄飞鸿之二：男儿当自强[BD国语{/dede:field}
{dede:field name='description'}黄飞鸿之二：男儿当自强[BD国语中字1280x720高清版]迅雷下载、免费下载，黄飞鸿之二：男儿当自强[BD国语中字1280x720高清版]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}黄飞鸿之二：男儿当自强[BD国语中字1280x720高清版]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2009-12-17{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://3e:3e@www2.3edyy.com:957/【3E电影院www.3edyy.com】黄飞鸿之二男儿当自强BD国语中字1280x720高清版.rmvb" target=_blank>ftftp://3e:3e@www2.3edyy.com:957/【3E电影院www.3edyy.com】黄飞鸿之二男儿当自强BD国语中字1280x720高清版.rmvb</A></TD></TR></TBODY></TABLE><BR><FONT color=#ff0000 size=2><STRONG>2009/12/18 [下载地址]：<IMG src="httftp://www.eee4.cn/templets/img/down.jpg" border=0></STRONG></FONT><BR>
<TABLE style="BORDER-RIGHT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; BORDER-BOTTOM: #cccccc 1px dotted" cellSpacing=0 cellPadding=6 width="95%" align=center border=0>
<TBODY>
<TR>
<TD style="WORD-WRAP: break-word" bgColor=#fdfddf><A href="ftftp://3e:3e@www2.3edyy.com:960/【3E电影院www.3edyy.com】黄飞鸿之男儿当自强[BD国语中字1280x720高清].rmvb" target=_blank>ftftp://3e:3e@www2.3edyy.com:960/【3E电影院www.3edyy.com】黄飞鸿之男儿当自强[BD国语中字1280x720高清].rmvb</A></TD></TR></TBODY></TABLE></div><ul class="mmlist{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MQ32J50-1X96.jpg{/dede:field}
