{dede:field name='keywords'}铁血北疆曲BD1280高清中字迅雷下{/dede:field}
{dede:field name='description'}铁血北疆曲BD1280高清中字迅雷下载、免费下载，铁血北疆曲BD1280高清中字Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}铁血北疆曲BD1280高清中字{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-21{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="/uploads/allimg/c120525/133O09200c0-94115.jpg" style="width: 300px; height: 456px" /></p>
<p>
	【片　　名】铁血北疆曲<br />
	【英文译名】Song Of Warriors<br />
	【年　　代】2006<br />
	【类　　型】战争<br />
	【国家地区】中国<br />
	【语　　言】汉语普通话<br />
	【上映日期】2006<br />
	【出品公司】北京大正方圆文化传播有限公司<br />
	【片　　长】93 min<br />
	【导　　演】刘子铭<br />
	【编　　剧】孙毅/刘子铭<br />
	【主　　演】周浩东/张澍/甄真/袁忠远<br />
	【官方网站】：http://www.bluemv.com<br />
	　　　　　　<br />
	【剧情介绍】<br />
	<br />
	1946年的科尔沁草原 &nbsp;周浩东饰麦新，同样经历了战火纷飞、水深火热的苦难年代，并且形势更为复杂，在黑恶势力的百般蹂躏下，各族人民进行着艰苦的反抗和斗争。在这样的背景下，麦新临危受命，来到科尔沁草原，带领人民凝聚力量进行斗争。纯真的爱情也光临到这个年轻人身上。英雄泪洒天地间&hellip;&hellip;麦新，用鲜血和过人的胆识以及真挚的感情谱写了生命中最艰苦卓绝的一支战歌&hellip;&hellip;<br />
	<br />
	&nbsp;<img alt="" src="/uploads/allimg/c120525/133O09201I0-109458.jpg" /></p>
<p>
	<img alt="" src="/uploads/allimg/c120525/133O09202420-1191W.jpg" style="width: 640px; height: 360px" /></p>
<p>
	<img alt="" src="/uploads/allimg/c120525/133O09203020-12X20.jpg" style="width: 640px; height: 360px" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="/uploads/allimg/c120525/133O0T31310-42214.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：http://www.xiaozhizhu.net</td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy241:piaohua@117.41.229.29:2002/飘花电影piaohua.com铁血北疆曲BD1280高清中字.rmvb</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O09203H0-136011.jpg{/dede:field}
