<?php
$z[0]=Array("field","志明与春娇,BD国粤双语中字1024/",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","志明与春娇 BD国粤双语中字1024/1280高清迅雷下载、免费下载，志明与春娇 BD国粤双语中字1024/1280高清Gvod高清在线播放，剧情介绍等。",73,243);
$z[1][4]['name']="description";
$z[2]=Array("field","志明与春娇 BD国粤双语中字1024/1280高清",245,321);
$z[2][4]['name']="title";
$z[3]=Array("field","",323,362);
$z[3][4]['name']="writer";
$z[4]=Array("field","",364,403);
$z[4][4]['name']="source";
$z[5]=Array("field","2012-04-01",405,455);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",457,494);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://dy44:piaohua@dy44.piaohua.com:3110/飘花电影piaohua.com春娇与志明志明与春娇2BD1024国语中字.rmvb",496,635);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MOG5640-53O8.jpg",637,719);
$z[8][4]['name']="litpic";

?>