{dede:field name='keywords'}保卫战队之出动喇!朋友!BD1280高{/dede:field}
{dede:field name='description'}保卫战队之出动喇!朋友!BD1280高清迅雷下载、免费下载，保卫战队之出动喇!朋友!BD1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}保卫战队之出动喇!朋友!BD1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-01-27{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120123/17/62564813201201231744151479232096037_000.jpg" style="width: 429px; height: 601px" /></p>
<p>
	电影: 保卫战队之出动喇!朋友! 2011<br />
	Let&#39;s Go! / 小双侠<br />
	<br />
	&nbsp; &nbsp;地区: 香港<br />
	&nbsp; &nbsp;类型: 科幻 / 动作<br />
	&nbsp; &nbsp;总时长: 未知<br />
	&nbsp; &nbsp;上映: 2011-11-10<br />
	<br />
	小双自幼丧父，心里压抑正义，只相信自己的拳头。大鹏是他的唯一好友，时刻妄想保护地球。在宿命般得安排下，小双加入松元集团，遇上率性的安妮，与及断他一臂的魔人邝盛。暗中保护自己多年的神秘人、加上一班村霸好朋友，吹起反击的集结号，他们簇拥小双为领袖，奇迹接肢，向恶人进行复仇。只是，小双这次再出击，一定要打得别有意义，除了要重新拾起<a href="http://www.6dtaobao.com/" style="color: rgb(0, 0, 0); text-decoration: none;">淘宝网女装</a>那份与生俱来的正义感还要迎救当年对父亲见死不救的警员。<br />
	　　朋友，出发吧！&ldquo;一生人总要行一次&rdquo;，二十多个&ldquo;超人&rdquo;，为正义，战斗到最后！</p>
<p>
	<img alt="" src="http://img165.poco.cn/mypoco/myphoto/20120124/08/62564813201201240837191872810842116_003.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img165.poco.cn/mypoco/myphoto/20120124/08/62564813201201240837191872810842116_002.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img165.poco.cn/mypoco/myphoto/20120124/08/62564813201201240837191872810842116_001.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img165.poco.cn/mypoco/myphoto/20120124/08/62564813201201240837191872810842116_000.jpg" style="width: 720px; height: 405px" /><br />
	&nbsp;</p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>


<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="
ftp://dy125:piaohua@dy125.piaohua.com:7535/飘花电影piaohua.com保卫战队之出动喇BD国语无字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:7535/飘花电影piaohua.com保卫战队之出动喇BD国语无字1280高清.rmvb </a></td>
		</tr>
	</tbody>
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="
ftp://dy125:piaohua@dy125.piaohua.com:7535/飘花电影piaohua.com保卫战队之出动喇BD粤语无字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:7535/飘花电影piaohua.com保卫战队之出动喇BD粤语无字1280高清.rmvb </a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15913020-24109.png{/dede:field}
