{dede:field name='keywords'}黑暗物质：黄金罗盘BD中英双字10{/dede:field}
{dede:field name='description'}黑暗物质：黄金罗盘BD中英双字1024/1280高清迅雷下载、免费下载，黑暗物质：黄金罗盘BD中英双字1024/1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}黑暗物质：黄金罗盘BD中英双字1024/1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-22{/dede:field}
{dede:field name='body'}<p>
	&nbsp;<img alt="" border="0" onclick="if(this.width&gt;screen.width-461) window.open('/uploads/allimg/c120525/133O0UTV0-52049.jpg');" src="/uploads/allimg/c120525/133O0UTV0-52049.jpg" /></p>
<p>
	◎译　　名　《黑暗物质：黄金罗盘》07最新科幻巨片DVD中英双字1024x560高清版<br />
	◎别　　名　黑暗物质三部曲之金罗盘/黄金罗盘/魔幻罗盘<br />
	◎片　　名　The Golden Compass<br />
	◎年　　代　2007<br />
	◎国　　家　美国/英国<br />
	◎类　　别　冒险/剧情/家庭/幻想/惊悚<br />
	◎语　　言　英语<br />
	◎字　　幕　中英双字<br />
	◎IMDB评分 6.6/10 (20,071 votes)<br />
	◎文件格式　BD-RMVB<br />
	◎视频尺寸　1024 x 560<br />
	◎文件大小　2CD<br />
	◎片　　长　113 Min<br />
	◎导　　演　克里斯&middot;韦兹 Chris Weitz<br />
	◎主　　演　妮可&middot;基德曼 Nicole Kidman .....Marisa Coulter<br />
	　　　　　　丹尼尔&middot;克雷格 Daniel Craig .....Lord Asriel<br />
	　　　　　　爱娃&middot;格林 Eva Green .....Serafina Pekkala<br />
	　　　　　　达科塔&middot;布鲁&middot;理查兹 Dakota Blue Richards .....Lyra Belacqua<br />
	　　　　　　亚当&middot;戈德利 Adam Godley .....Pantalaimon (voice)<br />
	　　　　　　吉姆&middot;卡特 Jim Carter .....John Faa<br />
	　　　　　　山姆&middot;艾里奥特 Sam Elliott .....Lee Scoresby<br />
	　　　　　　西蒙&middot;迈克伯尼 Simon McBurney .....Fra Pavel<br />
	　　　　　　伊恩&middot;麦柯肖恩 Ian McShane .....Ragnar Sturlusson (voice)<br />
	　　　　　　约翰&middot;赫特 John Hurt<br />
	　　　　　　凯文&middot;贝肯 Kevin Bacon<br />
	　　　　　　艾瑞克&middot;巴纳 Eric Bana<br />
	<br />
	◎简　　介<br />
	<br />
	　　所有的故事都发生在与一个我们的世界平行运转的宇宙空间里，这是一个由巫师统领北部的天空的时代，北极熊才是最勇敢的战士。至于人类，他们每一个人都拥有一个由自己的灵魂幻化成的灵兽，其重要性堪比心脏。<br />
	<br />
	　　掌握着北极命脉的是一个叫&ldquo;主教法庭&rdquo;的神秘组织，近期，他们信心膨胀到想要控制所有的人类，摆在他们面前的惟一障碍，就是一个从上古时代流传至今的神物--金罗盘，这个时代的孩子里，有一个将会注定拥有它。<br />
	<br />
	　　对于年仅12岁的莉拉&middot;贝拉奎亚来说，她似乎还没有感觉到翻天覆地的变化和自己与生俱来的使命，她的叔叔阿斯里尔伯爵将她托付给约旦大学的校长抚养和保护，这个活泼可爱却也世故早熟的小女孩，将校园当成了游乐场，无人看管也颇为逍遥自得，因为她不但拥有一位能够一起闯祸的忠诚好友罗杰，身边还有守护灵&ldquo;潘特莱蒙&rdquo;的陪伴--它是一个很小、可以根据周围情况改变形状的灵兽。<br />
	<br />
	　　然而莉拉的世界在悄无声息地慢慢改变着&hellip;&hellip;<br />
	<br />
	　　阿斯里尔伯爵正着手准备着一场北极之旅，不仅仅为了研究一种名叫&ldquo;尘&rdquo;的神秘物质，他还怀疑位于北极圈的另一边，有一个和自己世界平行的另一个空间，显然，他的研究终将威胁到&ldquo;主教法庭&rdquo;，而他们势必会采取一切措施，包括关闭约旦大学，让阿斯里尔伯爵知难而退。<br />
	<br />
	　　这时，突然发生了多起绑架儿童的神秘事件，传闻他们都被到到了北极&hellip;&hellip;对于莉拉看来，流言就等于事实，因为她的好友罗杰也失踪了。正当莉拉发誓要去世界的尽头拯救罗杰时，一个新面孔出现在学校里，玛丽莎&middot;卡尔特夫人是个极具欺骗性的科学家，同时也是一名环游世界的旅者--不过看起来，她似乎更像是一只伺机而动的母豹。<br />
	<br />
	　　聪明的莉拉很快就发现自己已经成了一个设计好的陷阱的猎物，似乎有人对她的&ldquo;金罗盘&rdquo;觊觎许久，&ldquo;主教法庭&rdquo;也在不惜一切代价找到它。&ldquo;金罗盘&rdquo;是约旦学校的校长作为礼物赠送给莉拉的，它是一个神秘且强大的装置，能够还原事实，说出一切别人想要隐藏或躲在阴影之下的真&nbsp; 相，甚至可以改变未来。<br />
	<br />
	　　莉拉察觉到了卡尔特夫人身上的危险气息，她知道是离开的时候了，因为她不仅要营救罗杰，还要阻止&ldquo;主教法庭&rdquo;的恶行。然而命运注定莉拉此行不会孤独，她受到了喜欢在海上讨生活的部落--杰普顿人的保护，他们的族长是法尔、摩&middot;考斯特和法德&middot;科拉姆。<br />
	<br />
	　　然而作为同盟，杰普顿人可能不是那么值得信赖，但好在莉拉还有女巫塞拉菲娜&middot;帕可拉和德州空军李&middot;斯格斯比的帮助&hellip;&hellip;就这样，莉拉以一种紧急的姿态投身到一个让她飞向天空、横越海洋的历险当中，来到最北边的冰天雪地的狂野之地，在那里，她得到了另一个强大的盟友，一只穿着盔甲的熊，埃欧雷克&middot;伯尔尼松，他发誓要在战斗中帮助她到底，直到她成功。<br />
	<br />
	　　一场大战迫在眉睫，经历改变的不仅仅是莉拉所在的世界，也包括其他与之平行的空间，在好友和盟友的帮助下，还有&ldquo;金罗盘&rdquo;的威力，莉拉必须鼓足十二分勇气，将生平所学全部出来，才有可能阻止那股邪恶的力量...</p>
<p>
	&nbsp;</p>
<p>
	【电影截图】：<br />
	电影来源：www.eee4.com<br />
	<img onclick="if(this.width&gt;screen.width-461) window.open('/uploads/allimg/c120525/133O0UUM0-61391.jpg');" src="/uploads/allimg/c120525/133O0UUM0-61391.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 328px; border-top: 0px solid; border-right: 0px solid" /><br />
	<img onclick="if(this.width&gt;screen.width-461) window.open('/uploads/allimg/c120525/133O0UV450-L0Q.jpg');" src="/uploads/allimg/c120525/133O0UV450-L0Q.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 328px; border-top: 0px solid; border-right: 0px solid" /><br />
	<img onclick="if(this.width&gt;screen.width-461) window.open('/uploads/allimg/c120525/133O0UW0F-S0Q.jpg');" src="/uploads/allimg/c120525/133O0UW0F-S0Q.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 328px; border-top: 0px solid; border-right: 0px solid" /></p>
<p>
	07最新科幻巨片《黑暗物质:黄金罗盘》DVD中英双字1024x560高清版 －来自[3E电影站www.eee4.com]：<img border="0" src="http://www.eee4.com/templets/img/down.jpg" /><br />
	&nbsp;</p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				</anchor>ftp://e25:e25@xl2.eee4.com:9916/[3E电影站www.eee4.com]黄金罗盘[DVD中英双字1024x560高清版]CD1.rmvb</td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				</anchor>ftp://e25:e25@xl2.eee4.com:9916/[3E电影站www.eee4.com]黄金罗盘[DVD中英双字1024x560高清版]CD2.rmvb</td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				</anchor>ftp://dy44:piaohua@dy44.piaohua.com:3472/飘花电影piaohua.com黑暗物质：黄金罗盘BD中英双字1280高清.mkv</td>
		</tr>
	</tbody>
</table>
<p>
	&nbsp;</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O0UX60-10P49.jpg{/dede:field}
