{dede:field name='keywords'}第三季第06代(上)迅雷下载，免费{/dede:field}
{dede:field name='description'}第三季第06代(上)迅雷下载、免费下载，第三季第06代(上)Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}第三季第06代(上){/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2006-08-17{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://ftp.upplay.com/" target=_blank>ftftp://ftp.upplay.com/</A>加勒比社区荣誉出品E142.Love.Letter.SBS060805.KO_CN.rmvb<BR><BR><FONT face=Verdana>2006-08-06 18:43:28 开始连接......<BR>2006-08-06 18:43:28 开始搜索候选资源......<BR>2006-08-06 18:43:34 搜索到46个候选资源<BR>2006-08-06 18:43:34 使用候选资源进行连接......<BR>2006-08-06 18:43:34 开始创建文件......<BR>2006-08-06 18:44:36 文件创建成功，开始下载数据......<BR>2006-08-06 18:44:36 用户取消下载<BR></FONT><BR><BR></SPAN> <br></div><ul class="mmlist{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MO60K30-35C0.gif{/dede:field}
