{dede:field name='keywords'}哈尔的移动城堡[HD中英双字1024/{/dede:field}
{dede:field name='description'}哈尔的移动城堡[HD中英双字1024/1280高清版]迅雷下载、免费下载，哈尔的移动城堡[HD中英双字1024/1280高清版]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}哈尔的移动城堡[HD中英双字1024/1280高清版]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-11-23{/dede:field}
{dede:field name='body'}<p>
	◎译　　名　《哈尔的移动城堡》2004年宫崎骏经典科幻动画片HD中英双字1024x552高清版+DVD国语中字无水印<br />
	◎片　　名　Howls Moving Castle<br />
	◎年　　代　2004<br />
	◎国　　家　日本<br />
	◎类　　别　动画/冒险/剧情/家庭/幻想/爱情/科幻<br />
	◎语　　言　日语、普通话<br />
	◎字　　幕　中文<br />
	◎IMDB评分 8.1/10 (24,499 votes)<br />
	◎IMDB链接 http://www.imdb.com/title/tt0347149<br />
	◎文件格式　HD-RMVB<br />
	◎视频尺寸　1024 x 552&nbsp;&nbsp;<br />
	◎文件大小　1CD<br />
	◎片　　长　01:59:09<br />
	◎导　　演　宫崎骏 Miyazaki Hayao<br />
	　　　　　　Rick Dempsey<br />
	◎主　　演　比利&middot;克里斯托 Billy Crystal ..... Calcifer (voice: English version)<br />
	　　　　　　Ruby Marlowe ..... Additional Voices (voice: English version)<br />
	　　　　　　乔什&middot;哈切森 Josh Hutcherson ..... Markl (voice: English version)<br />
	　　　　　　吉娜&middot;马隆 Jena Malone ..... Lettie (voice: English version)<br />
	　　　　　　Emily Mortimer ..... Young Sophie (voice: English version)<br />
	　　　　　　克里斯汀&middot;贝尔 Christian Bale ..... Howl (voice: English version)<br />
	　　　　　　Liliana Mumy ..... Madge (voice: English version)<br />
	　　　　　　Sofie Gr?b?l ..... Sofie (voice)<br />
	　　　　　　Daran Norris ..... Additional Voices<br />
	　　　　　　大塚明夫 Akio ?tsuka ..... Koku? (voice)<br />
	　　　　　　木村拓哉 Takuya Kimura ..... Hauru (voice)<br />
	　　　　　　Carlos Alazraqui ..... Additional Voices (voice: English version)<br />
	　　　　　　劳伦&middot;巴考尔 Lauren Bacall ..... Witch of the Waste (voice: English version)<br />
	　　　　　　Blythe Danner ..... Madam Suliman (voice: English version)<br />
	　　　　　　Hope Levy ..... Additional Voices (voice: English version)<br />
	　　　　　　倍赏千惠子 Baishou Chieko ..... Sof? (voice)<br />
	　　　　　　美轮明宏 Akihiro Miwa ..... Arechi no Majo (voice)<br />
	　　　　　　Tatsuya Gashuin ..... Karushifa (voice)<br />
	　　　　　　原田大二郎 Daijiro Harada ..... Hin (voice)<br />
	　　　　　　Newell Alexander ..... Additional Voices (voice: English version)<br />
	　　　　　　大泉洋 Yo Oizumi ..... Kakashi no Kabu (voice)<br />
	　　　　　　Crispin Freeman ..... Prince Turnip (voice: English version)<br />
	　　　　　　Susan Blakeslee ..... Additional Voices (voice: English version)<br />
	　　　　　　Will Friedle ..... Additional Voices (voice: English version)<br />
	　　　　　　Jane Alan ..... Honey (voice: English version) (as Mari Devon)<br />
	　　　　　　Rosemary Alexander ..... Additional Voices (voice: English version)<br />
	　　　　　　Richard Steven Horvitz ..... Additional Voices (voice: English version)<br />
	　　　　　　Joel McCrary ..... Additional Voices (voice: English version)<br />
	　　　　　　Jean Simmons ..... Old Sophie (voice: English version)<br />
	　　　　　　Sherry Hursey ..... Additional Voices (voice: English version)<br />
	　　　　　　神木隆之介 Ryunosuke Kamiki ..... Marukuru (voice)<br />
	　　　　　　Leslie Carrara ..... Additional Voices (voice: English version)<br />
	　　　　　　加藤治子 Haruko Kato ..... Sariman (voice)<br />
	　　　　　　Holly Dorff ..... Additional Voices (voice: English version)<br />
	　　　　　　Edie Mirman ..... Additional Voices (voice: English version)<br />
	　　　　　　Pete Renaday ..... Additional Voices (voice: English version) (as Pete Renaday)<br />
	　　　　　　Moosie Drier ..... Additional Voices (voice: English version)<br />
	　　　　　　David Cowgill ..... Additional Voices (voice: English version)<br />
	　　　　　　Warren Sroka ..... Additional Voices (voice: English version)<br />
	　　　　　　Christina MacGregor ..... Additional Voices (voice: English version)<br />
	　　　　　　Mitsunori Isaki ..... Kosh? (voice)<br />
	　　　　　　Mitch Carter ..... Additional Voices (voice: English version)<br />
	　　　　　　Ike Eisenmann ..... Additional Voices (voice: English version)<br />
	　　　　　　Julia Barnett ..... Additional Voices (voice: English version)<br />
	　　　　　　Kristen Rutherford ..... Additional Voices (voice: English version)<br />
	　　　　　　Mark Silverman ..... King (voice: English version)<br />
	　　　　　　<br />
	<br />
	◎简　　介　<br />
	　　<br />
	　宫崎骏的《千与千寻》曾经在日本创造了2340万人次的最高上座率，更获得了美国奥斯卡奖和柏林金熊奖，在全世界范围内掀起了一股观看热潮。<br />
	<br />
	　时隔三年后，宫崎骏又推出了最新作品《哈尔的移动城堡》，故事发生在19世纪末的欧洲，善良可爱的苏菲被恶毒的女巫施下魔咒，从18岁的女孩变成90岁的婆婆，孤单无助的她无意中走入镇外的移动城堡，据说它的主人哈尔以吸取女孩的灵魂为乐，但是事情并没有人们传说的那么可怕，性情古怪的哈尔居然收留了苏菲，两个人在四脚的移动城堡中开始了奇妙的共同生活，一段交织了爱与痛、乐与悲的爱情故事在战火中悄悄展开&hellip;&hellip;</p>
<p>
	<img src="/uploads/allimg/c120525/133O044260F-111341.jpg" /><br />
	<br />
	<br />
	◆详解18婆婆的缘起情动◆<br />
	<br />
	　04年日本动漫界三大巨头宫崎骏、大友克洋和押井守推出的新作品，分别是《哈尔的移动城堡》、《蒸汽男孩》和《攻壳机动队2：无罪》，其中宫崎骏的《哈尔的移动城堡》有幸参加当年威尼斯影展，备受关注：<br />
	<br />
	　○苏菲的家庭背景：苏菲和继母、两个姐姐居住在一个颇有欧洲风情的小镇，继母凡妮依靠制帽的薪水养活一家人，自从女孩们的父亲去世后凡妮无以为继，只好把两个年长的女儿安排到制帽店当学徒，苏菲的两个姐姐莱特和玛莎各有所好，一个宁愿学习包罗万象的巫术，另一个更希望成为一名面包师。她们很快离开这家商店，而一直在旁打下手的小苏菲反倒坚持下来，尽管苏菲也对自己的生活不满，但她仍希望自己制作的每一顶帽子都能令顾客满意。<br />
	<br />
	　○哈尔的可怕传说：一座移动的城堡电影下载漫无目的地从一个地方移动到另一个地方，最近偏偏在小镇附近落脚，人们传说城堡中的邪恶巫师哈尔专门掳掠年青姑娘，然后吸取她们的灵魂，有时甚至还会吃掉姑娘的心。因此，镇民告诫姑娘们远离城堡，避免落入哈尔的魔掌。<br />
	<br />
	　○女巫的恶毒心肠：人的忌妒心是最可怕的，苏菲的制帽手艺相当精湛，这引起了一个巫婆的嫉妒，她利用一种独特的咒语，把苏菲变成了老太婆，而苏菲还不能对任何人透露咒语内容，她索性逃离小镇。<br />
	<br />
	　○ 命中注定的相遇：苏菲苍老又虚弱，艰难地向小镇外走去，夜幕加重了她的负担，由于无法到达另一个城镇，她壮起胆子走向可怕的移动城堡。恰巧哈尔本人不在家，学徒迈克尔也满脸无奈，苏菲不仅成功地进入城堡，还理直气壮地在城堡中过夜。现在的年龄给了苏菲勇气，住下来的她以女管家自居，开始打点城堡的一切。传说中的哈尔回来后，发现堡内变得一尘不染，也只好放任她去住下去。<br />
	<br />
	　○谁会来打破咒语：城堡的动力火焰由一个叫卡西佛的火焰魔掌管，他也和苏菲一样身受咒语不能声张，于是二人达成协议互相帮助发现各自的咒语。而苏菲开始逐渐了解古怪的哈尔，哈尔冰冷的心也被慢慢融化，两个年龄极不相符的人越迅雷电影下载走越近。<br />
	<br />
	◆漂流域仙境的四大突破◆<br />
	<br />
	　①下鱼上城：宫崎骏以前的作品从来没有对机械做过太多复杂设计，而移动城堡的&ldquo;下鱼上城&rdquo;的设计大体上也可以归类于空中楼阁，从设定中隐约透出《天空之城》中空中堡垒拉普达的几分影子，再加上钢铁、烟囱、滑轮和桅杆，也算是宫崎骏绝无仅有的一次新颖尝试。<br />
	<br />
	　②女孩大了：宫崎骏向来钟爱女孩作为动画片的主角，这部《哈尔的移动城堡》也不例外，不过为了忠于同名小说的人物背景设定，苏菲比他所有动画片中的女孩都偏大了一点。<br />
	<br />
	　③采用3D：这部动画片的&ldquo;外景地&rdquo;欧式风味比较浓，背景很像1989年的《魔女宅急便》，风格则是&ldquo;《风之谷》+《天空之城》&rdquo;的结合体，宫崎骏本人也决定在城堡的移动中采用3D技术。<br />
	<br />
	　④魔幻题材：除了秉承宫崎骏的一贯风格外，《哈尔的移动城堡》与他以往的原创不同，题材正好切合时下非常流行的魔幻潮流，故事主题相对来说更加具体。</p>
<p>
	【电影截图】：<br />
	<br />
	<img src="/uploads/allimg/c120525/133O0442FZ-125919.jpg" style="border-right: 0px solid; border-top: 0px solid; border-left: 0px solid; width: 600px; border-bottom: 0px solid; height: 323px" />&nbsp;<br />
	<img src="/uploads/allimg/c120525/133O0442N30-13IP.jpg" style="border-right: 0px solid; border-top: 0px solid; border-left: 0px solid; width: 600px; border-bottom: 0px solid; height: 323px" /></p>
	2004年宫崎骏经典科幻动画《哈尔的移动城堡》HD中英双字1024x552高清版 </p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-right: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-left: #cccccc 1px dotted; border-bottom: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				ftp://3e:3e@www2.eee4.com:663/[www.eee4.cn提供]哈尔的移动城堡HD中英双字1024x552高清版.rmvb</td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-right: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-left: #cccccc 1px dotted; border-bottom: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				ftp://e2:e2@xl2.eee4.com:507/[3E电影站www.eee4.com]哈尔的移动城堡DVD国语配音中字无水印.rmvb</td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-right: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-left: #cccccc 1px dotted; border-bottom: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				ftp://dy44:piaohua@dy44.piaohua.com:2146/飘花电影piaohua.com哈尔的移动城堡BD中字1280高清.rmvb</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O0442UF-14P32.jpg{/dede:field}
