{dede:field name='keywords'}孤儿杀手高清1280版BD中字2011最{/dede:field}
{dede:field name='description'}孤儿杀手高清1280版BD中字2011最新美国恐怖大片迅雷下载、免费下载，孤儿杀手高清1280版BD中字2011最新美国恐怖大片Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}孤儿杀手高清1280版BD中字2011最新美国恐怖大片{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-04-07{/dede:field}
{dede:field name='body'}<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120406/23/56643687201204062335003648699262537_005.jpg" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120406/23/56643687201204062335003648699262537_006.jpg" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120406/23/56643687201204062335003648699262537_004.jpg" /></p>
<p>
	◎译　　名　孤儿杀手<br />
	◎片　　名　The Orphan Killer<br />
	◎年　　代　2011<br />
	◎国　　家　美国<br />
	◎类　　别　恐怖<br />
	◎语　　言　英语<br />
	◎字　　幕　中文<br />
	◎IMDB评分 4.2/10 from 647 users<br />
	◎IMDB链接 <a href="http://www.imdb.com/title/tt1179071">http://www.imdb.com/title/tt1179071</a><br />
	◎文件格式　DVD-RMVB<br />
	◎视频尺寸　720 x 304<br />
	◎文件大小　1CD 425MB<br />
	◎片　　长　1h 22mn<br />
	◎导　　演　马特.法恩斯沃思 Matt Farnsworth<br />
	◎主　　演　黛安福斯特 Diane Foster &hellip; Audrey<br />
	　　　　　　大卫.巴科斯 David Backus &hellip; The Orphan Killer<br />
	　　　　　　马特.法恩斯沃思 Matt Farnsworth &hellip; Mike<br />
	　　　　　　James McCaffrey &hellip; Detective Jones<br />
	　　　　　　John Savage &hellip; Detective Walker<br />
	　　　　　　Karen Young &hellip; Sister Mary<br />
	　　　　　　Charlotte Maier &hellip; Sister Constance</p>
<p>
	<br />
	◎简　　介　</p>
<p>
	<br />
	　　导演间剧中演员的 Matt Farnshorth 是众所周知的新世代导演, 编剧, 漫画家 同时也是位视频艺术家, The Orphan Killer 是他营造出来的新的恐怖杀手, 媲美於70年代的月光光心慌慌,80年代的13号星期五, 及90年代的半夜鬼上床佛莱迪等恐怖杀手, 除了在美国本地外, 本片在欧洲也荣获了不少奖项（共9项大奖）<br />
	可怜孤儿马可斯因为遭逢父母被杀的痛苦记忆, 之後跟妹妹被送进修道院, 因为个性偏激残暴而与妹妹分开,妹妹被当初办案的刑警收养, 从此没有回去看过他....长大後的马可斯, 为了找寻妹妹报仇, 於是便大开杀戒, 於是本片展开了血肉纷飞的历程....</p>

<p>
	<br />
	◎影片截图</p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120406/23/56643687201204062335003648699262537_000.jpg" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120406/23/56643687201204062335003648699262537_001.jpg" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120406/23/56643687201204062335003648699262537_003.jpg" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120406/23/56643687201204062335003648699262537_002.jpg" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120407/11/56643687201204071131474748211703143_001.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 338px; border-top: 0px solid; border-right: 0px solid" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120407/11/56643687201204071131474748211703143_003.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 338px; border-top: 0px solid; border-right: 0px solid" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120407/11/56643687201204071131474748211703143_002.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 338px; border-top: 0px solid; border-right: 0px solid" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120407/11/56643687201204071131474748211703143_000.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 338px; border-top: 0px solid; border-right: 0px solid" /></p>

<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.netftp://dy44:piaohua@dy44.piaohua.com:3160/" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3167/飘花电影piaohua.com孤儿杀手DVD中字.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3167/飘花电影piaohua.com孤儿杀手DVD中字.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3167/飘花电影piaohua.com孤儿杀手高清1280版BD中字.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3167/飘花电影piaohua.com孤儿杀手高清1280版BD中字.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O162Y3F-2Z21.jpg{/dede:field}
