{dede:field name='keywords'}公主日记/麻雀变公主BD中英双字1{/dede:field}
{dede:field name='description'}公主日记/麻雀变公主BD中英双字1024高清迅雷下载、免费下载，公主日记/麻雀变公主BD中英双字1024高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}公主日记/麻雀变公主BD中英双字1024高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-14{/dede:field}
{dede:field name='body'}<p>
	&nbsp;<img src="http://img.album.pchome.net/54/69/30/35/94529c1f5a67ccde3f28f546b1a713c6.jpg" /></p>
<p>
	◆ 片　　名：《公主日记/麻雀变公主》2001年迪斯尼票房过亿青春喜剧DVD中英双字<br />
	◆ 制　　片：惠特尼&middot;休斯敦（Whitney Houston）　<br />
	◆ 导　　演：加里&middot;马歇尔（Garry Marshall）　<br />
	◆ 编　　剧：Meg Cabot　Gina Wendkos　<br />
	◆ 主　　演：安妮&middot;海瑟薇 Anne Hathaway<br />
	　　　　　　茱莉&middot;安德鲁斯 Julie Andrews<br />
	　　　　　　哈克特&middot;埃利桑多 Hector Elizondo<br />
	　　　　　　曼迪&middot;摩尔 Mandy Moore<br />
	◆ 类　　型：喜剧（Comedy）家庭（Family）　　<br />
	◆ 国家地区：USA　<br />
	◆ 语　　言：English<br />
	◆ 发行公司：博伟（Buena Vista）迪斯尼（Disney）　<br />
	◆ 首映日期：2001年8月3日<br />
	◆ 制作成本：$50 + $0 (单位：百万美元)<br />
	◆ 首映票房：$22,862,269.00 (单位：美元)<br />
	◆ 全美票房：$108,248,956.00 (单位：美元)<br />
	◆ 海外票房：$57,100,000.00 (单位：美元)<br />
	◆ 影片评分：<br />
	◆ MPAA定级：G 级<br />
	◆ 片　　长：110 分钟<br />
	◆ 官方网站：http://www.princessdiaries.com/<br />
	◆ 影片简介：<br />
	　　米娅（安妮&middot;海瑟薇）是个土生土长的纽约女孩，她穿着现代前卫，说着只有新新人类才听得懂的时髦语言，总之，她过着一种标准而正常的都市生活。<br />
	　　在米娅年满16岁的时候，她却意外之极地得知自己竟然是一个叫做吉诺维亚的欧洲小国公主！原来，当年米娅的母亲和这个小国家的王储有过一段短命的恋情，米娅就是这段恋情的衍生物，而眼下，毫不知情的她却成了这个小国家<br />
	（一律使用<a href="http://www.eee4.com/soft.htm" target="_blank">迅雷下载</a>）<br />
	唯一合法的王位继承人。<br />
	　　懵懵懂懂的米娅就这样做梦一样地当上了公主，但是自小无拘无束的米娅言谈举止和一国之君自然是差着十万八千里，没办法，吉诺维亚的国母&mdash;&mdash;皇太后（茱莉&middot;安德鲁斯）不得不担任起管教培养小孙女的神圣职责。<br />
	　　素未谋面的祖孙俩开始了朝夕相处的日子，最初两人都看对方不顺眼，但毕竟血浓于水，融合在血液中的亲情让他们渐渐学会了理解和接受彼此的生活方式&hellip;&hellip;<br />
	　　至于最后嘛，当然是个皆大欢喜的团圆结局了。</p>
	【电影截图】：<br />
	<img src="http://farm4.static.flickr.com/3463/3375045184_cc4b4d3377_o.jpg" />&nbsp;<br />
	<img src="http://farm4.static.flickr.com/3557/3375045182_5248940ed5_o.jpg" /></p>
	2001年迪斯尼票房过亿青春喜剧《公主日记》DVD中英双字 －来自[www.eee4.com]：<img border="0" src="http://www.eee4.com/templets/img/down.jpg" /></p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<anchor></anchor><a href="ftp://e7:e7@xl2.eee4.com:9306/[3E电影站www.eee4.com]公主日记DVD中英双字CD1.rmvb" target="_blank">ftp://e7:e7@xl2.eee4.com:9306/[3E电影站www.eee4.com]公主日记DVD中英双字CD1.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<anchor></anchor><a href="ftp://e7:e7@xl2.eee4.com:9306/[3E电影站www.eee4.com]公主日记DVD中英双字CD2.rmvb" target="_blank">ftp://e7:e7@xl2.eee4.com:9306/[3E电影站www.eee4.com]公主日记DVD中英双字CD2.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<anchor></anchor><a href="ftp://dy44:piaohua@dy44.piaohua.com:3414/飘花电影piaohua.com麻雀变公主BD中英双字1024高清.mkv">ftp://dy44:piaohua@dy44.piaohua.com:3414/飘花电影piaohua.com麻雀变公主BD中英双字1024高清.mkv</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15L2460-2H51.jpg{/dede:field}
