{dede:field name='keywords'}玩具总动员3/反斗奇兵3[BD中英双{/dede:field}
{dede:field name='description'}玩具总动员3/反斗奇兵3[BD中英双字1024/1280高清版]迅雷下载、免费下载，玩具总动员3/反斗奇兵3[BD中英双字1024/1280高清版]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}玩具总动员3/反斗奇兵3[BD中英双字1024/1280高清版]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-01-17{/dede:field}
{dede:field name='body'}<p>
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://apollo.s.dpool.sina.com.cn/nd/dataent/moviepic/pics/91/moviepic_f8664118b5e03f77cdd809fbc15f53e4.jpg');" src="http://apollo.s.dpool.sina.com.cn/nd/dataent/moviepic/pics/91/moviepic_f8664118b5e03f77cdd809fbc15f53e4.jpg" /><br />
	<br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://apollo.s.dpool.sina.com.cn/nd/dataent/moviepic/pics/91/moviepic_831b27e0513ab6756eb674d0718655e3.jpg');" src="http://apollo.s.dpool.sina.com.cn/nd/dataent/moviepic/pics/91/moviepic_831b27e0513ab6756eb674d0718655e3.jpg" /><br />
	<br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://apollo.s.dpool.sina.com.cn/nd/dataent/moviepic/pics/91/moviepic_5968c82c72911100de5e683687d10a39.jpg');" src="http://apollo.s.dpool.sina.com.cn/nd/dataent/moviepic/pics/91/moviepic_5968c82c72911100de5e683687d10a39.jpg" /><br />
	<br />
	◎译　　名　玩具总动员3/反斗奇兵3<br />
	◎片　　名　Toy Story 3<br />
	◎年　　代　2010<br />
	◎国　　家　美国<br />
	◎类　　别　动画/冒险/喜剧/家庭/幻想<br />
	◎语　　言　英语<br />
	◎字　　幕　中英双字<br />
	◎IMDB评分 8.9/10 (71,501 votes)<br />
	◎文件格式　BD-RMVB<br />
	◎视频尺寸　1024 x 576<br />
	◎文件大小　1CD<br />
	◎片　　长　103 Min<br />
	◎导　　演　李&middot;昂克里奇 Lee Unkrich<br />
	◎主　　演　汤姆&middot;汉克斯 Tom Hanks....Woody (voice)<br />
	　　　　　　蒂姆&middot;艾伦 Tim Allen....Buzz Lightyear (voice)<br />
	　　　　　　琼&middot;库萨克 Joan Cusack....Jessie (voice)<br />
	　　　　　　尼德&middot;巴蒂 Ned Beatty....Lotso (voice)<br />
	　　　　　　唐&middot;里克斯 Don Rickles....Mr. Potato Head (voice)<br />
	　　　　　　迈克尔&middot;基顿 Michael Keaton....Ken (voice)<br />
	　　　　　　华莱士&middot;肖恩 Wallace Shawn....Rex (voice)<br />
	　　　　　　约翰&middot;拉岑贝格 John Ratzenberger....Hamm (voice)<br />
	　　　　　　Estelle Harris ....Mrs. Potato Head (voice)<br />
	　　　　　　约翰&middot;莫里斯 John Morris....Andy (voice)<br />
	　　　　　　裘蒂&middot;班森 Jodi Benson....Barbie (voice)<br />
	　　　　　　Emily Hahn ....Bonnie (voice)<br />
	　　　　　　Laurie Metcalf ....Andy&#39;s Mom (voice)<br />
	　　　　　　布莱克&middot;克拉克 Blake Clark....Slinky Dog (voice)<br />
	　　　　　　Teddy Newton ....Chatter Telephone (voice)<br />
	　　　　　　巴德&middot;乐凯 Bud Luckey....Chuckles (voice)<br />
	　　　　　　Beatrice Miller ....Molly (voice)<br />
	　　　　　　Javier Fernandez Pena ....Spanish Buzz (voice)<br />
	　　　　　　提摩西&middot;道尔顿 Timothy Dalton....Mr. Pricklepants (voice)<br />
	　　　　　　Lori Alan ....Bonnie&#39;s Mom (voice)<br />
	　　　　　　Charlie Bright ....Young Andy / Peas-in-a-Pod (voice)<br />
	　　　　　　Kristen Schaal ....Trixie (voice)<br />
	　　　　　　杰夫&middot;格尔林 Jeff Garlin....Buttercup (voice)<br />
	　　　　　　邦尼&middot;亨特 Bonnie Hunt....Dolly (voice)<br />
	　　　　　　John Cygan ....Twitch (voice)<br />
	　　　　　　Jeff Pidgeon ....Aliens (voice)<br />
	　　　　　　乌比&middot;戈德堡 Whoopi Goldberg....Stretch (voice)<br />
	　　　　　　杰克&middot;安琪 Jack Angel....Chunk (voice)<br />
	　　　　　　R&middot;李&middot;艾尔米 R. Lee Ermey....Sarge (voice)<br />
	　　　　　　Jan Rabson ....Sparks (voice)<br />
	　　　　　　理查德&middot;坎德 Richard Kind....Bookworm (voice)<br />
	　　　　　　伊瑞克&middot;冯&middot;迪滕 Erik von Detten....Sid (voice)<br />
	<br />
	◎简　　介　<br />
	<br />
	　　《玩具总动员3》讲述的是小男孩安迪已经长大成人，即将离家开始大学生活。一箱子玩具本来想放到阁楼，却被妈妈错捐给一家托儿所，玩具们新的冒险之旅即将展开，除了人类小朋友的蹂躏外，新的友谊与未知的阴谋也在当中展开。但当玩具们得知小主人想要找回他们时，漫漫回家路，冒险才真正地开始了&hellip;&hellip;<br />
	<br />
	　　安弟已经长大成人，正准备离家前往大学，展开新的生活。安弟舍不得巴斯光年和胡迪这些陪伴他十几年的玩具，想把玩具们存入自家阁楼，但安弟的妈妈还是错把玩具们送到了一个全是无法无天的孩子们的幼儿园，这些孩子们迫不及待地将他们的小脏手伸向这些新来的玩具们。 同时玩具们发现他们在幼儿园其实毫无人身自由，玩具&quot;大熊&quot;控制着幼儿园玩具们的命运。于是胡迪决定要带领玩具们离开幼儿园，回到安弟的身边。他们万众一心，开始酝酿一个伟大的逃跑计划，当然，他们将面临的是一次惊险无比的大冒险！<br />
	<br />
	　　安迪已经高中毕业了，即将成为大学生，而他的玩具，包括伍迪、巴斯光年都面临将要被放在阁楼上的命运。在他们被放到阁楼之前，却意外的被丢弃，并被一个清理垃圾的人所捡起。玩具们发现自己被带到了一个当地的日间托儿所，他们必须要在那儿想办法面对一群调皮且粗鲁的学龄前小孩。胡迪打算要带领他的朋友们逃离托儿所，并为自己和他们找到一个新的安身之处。但巴斯光年在一次尝试逃离的行动中受到了损伤，使得整件事情变得更复杂了&hellip;&hellip;<br />
	<br />
	玩具们的主人安迪今年17岁了，马上即将迎来他自己人生中的一个重要阶段&mdash;&mdash;大学。同时，这个变故对于他的玩具们来说也意义重大，也许这将改变他们所有人的命运。正当伍迪和巴斯光年他们为未来担忧的时候，安迪决定仍然保留<a href="http://www.3edyy.com/" target="_blank">电影下载</a>他所有的玩具，并且带着伍迪一起去大学，将剩下的放入阁楼。但是，安迪的母亲却无意中将打包了玩具的箱子扔进了垃圾堆。当玩具们意识到自己置身于垃圾中时，他们都以为是安迪抛弃了他们。牧羊女杰西这时号召大家掌控自己的命运，开始新的生活。于是玩具们跳进了一个前往日托幼儿园的箱子。与此同时，伍迪作为唯一一个安迪的&ldquo;亲随&rdquo;并没有被放入箱子中。当他意识到大家不见了之后，便开始了他自己的拯救行动。但是不幸的是，最后他自己也被困在了箱子中。来到新的环境后玩具们遇到很多新的朋友，同时也有许多并不十分友好的玩具在那里等着给他们制造麻烦。玩具们需要闯过许多难关才能找到回家的路，而首先，伍迪必须让同伴们信服，安迪并没有抛弃他们。<br />
	<br />
	一句话评论<br />
	<br />
	《玩具总动员3》相较于前两部有着更为成熟复杂的故事线索，同时这部3D电影也融合了皮克斯自成立以来的所有心血努力，可谓集大成者。<br />
	&mdash;&mdash;《综艺》<br />
	<br />
	皮克斯并未原地踏步，这是一个在优质的视效、剪辑、3D等技术手段包装下的富含人生哲理的故事。<br />
	&mdash;&mdash;indieWIRE<br />
	<br />
	影片虽然在情感上较前两部稍微沉重阴暗一些，但是导演李&middot;昂克里奇和编剧迈克尔&middot;阿姆特尝试着增加了不少美妙的细节，以保证那些深受大家喜爱的玩具角色们不会被削弱。<br />
	&mdash;&mdash;《好莱坞报道》<br />
	<br />
	幕后制作<br />
	<br />
	&nbsp; &nbsp; &nbsp; 具有里程碑意义的动画系列<br />
	<br />
	　　1995年上映的《玩具总动员》是第一部全部采用CG技术制作的动画片，它不仅仅在动画技术上，也在电影制作艺术上具有重要的里程碑意义。<br />
	<br />
	　　&ldquo;《玩具总动员》在电影历史上有不可磨灭的影响，&rdquo;沃尔特&middot;迪士尼电影公司主席里奇&middot;罗斯说，&ldquo;正是工作室本身的开创精神，使得这部影片不仅仅在技术上，更是在叙事方式上开辟了一片新天地。巴斯光年、胡迪等玩具一下子就赢得了不同年龄段人群的喜爱，其受欢迎程度丝毫不亚于迪士尼那些传统的经典角色。《玩具总动员&lt;/U&gt;》大大拓展了动画电影的受众群体，也重新定义了电影制作的规则，它证明了制作一部能满足各类观众需求的电影是完全可行的。事实上，《玩具总动员》为它后面的电影－－无论动画电影还是真人电影－－树立了一个标杆。&rdquo;<br />
	<br />
	　　所有77分钟激动人心的动画、1561个镜头以及76个手工精心设计的包括人物、玩具和狗在内的角色全部使用电脑制作完成。这部动画片成为1995年收入最高的影片，仅在美国就有接近1.92亿美元的票房收入，全球票房则高达3.62亿美元。《玩具总动员1》获得了最佳原创剧本、最佳原创配乐、最佳原创歌曲三项奥斯卡奖提名。约翰&middot;拉塞特因富有成效地带领皮克斯《玩具总动员》团队制作了第一部电脑动画长片而获得奥斯卡特别成就奖。该片成为电影史上第一部获得奥斯卡最佳原创剧本提名的动画片。此外，该片被美国电影协会选入100部最伟大的美国电影。<br />
	<br />
	　　&ldquo;我记得当我们发布《玩具总动员》的时候，&rdquo;制片人达拉&middot;K&middot;安德森说，&ldquo;史蒂夫&middot;乔布斯说它就是我们的《白雪公主》。当时我们也想&lsquo;嗨，如果《玩具总动员》真达到《白雪公主》那样的高度，成为人人都津津乐道的经典电影，那将是一件多酷的事情。让每个人看了都觉得它讲述的是自己生命中的某一段经历：他们的童年时代，他们的家庭生活。&rsquo;这就是当时我们制作《玩具总动员&lt;/U&gt;》的动机，直到现在也是我们制作每部电影的宗旨。&rdquo;<br />
	<br />
	　　1999年，《玩具总动员2》（皮克斯动画工厂的第三部影片）成为第一部全部使用数字化设计、制作和放映的影片。该片在票房收入上超过了《玩具总动员》，成为动画片历史上第一部续作收入超过前作的影片。该片受到评论界和观众的一致好评，获得奥斯卡最佳原创音乐提名、金球奖两项提名，并获得金球奖音乐及喜剧类最佳影片奖。2009年，采用迪士尼3D数字技术重新制作的《玩具总动员》和《玩具总动员2》<a href="http://www.eee4.cc/" target="_blank">电影下载</a>进行了两场特别连映。<br />
	<br />
	&nbsp; &nbsp; &nbsp; &nbsp; 将三部影片融为一体<br />
	<br />
	　　为了创作《玩具总动员3》，皮克斯几乎召集了创作前两部《玩具总动员》的全部原班人马。除此之外，这次加入李&middot;昂克里奇的导演阵容的有约翰&middot;拉塞特、安德鲁&middot;斯坦顿（参与过《玩具总动员1》和《玩具总动员2》的编剧，编写并导演了《海底总动员》和《机器人瓦力》）、彼特&middot;道格特（《怪物电力公司》和《飞屋历险记》的作者兼导演）、达拉&middot;K&middot;安德森、鲍勃&middot;彼德森和杰夫&middot;皮金。<br />
	<br />
	　　安德森回忆道：&ldquo;我们去了一个名为The Poet&#39;s Loft的地方，就在马林郡的塔玛莉海湾。那里有一间小屋，正是在那里诞生了《玩具总动员1》。当年那部电影完成的时候，约翰给了我们一些瓶子上带有《玩具总动员》标签的红酒作为纪念，这次去的时候安德鲁把那瓶酒也带上了。我们为已经离去的好朋友、好同事乔&middot;兰伏特敬了一杯酒，他是《玩具总动员1》的灵魂。乔很善于创造真实但古怪灵精的角色，并能发掘出属于每个角色的幽默。我们都非常想念他。&rdquo;<br />
	<br />
	　　会议期间，每个参与者都仔细全面地观看了前两部《玩具总动员》，帮助他们重新回到电影描述的世界里。&ldquo;我们的目的当然是制作出能和前两部《玩具》相媲美的影片，&rdquo;　昂克里奇说，&ldquo;在电影史上，能够和第一部作品一样好的续集屈指可数，更别提第三部续集了。我能想到的只有《魔戒3：王者归来》，它看起来真正配得上一部巨作的第三部分。我忽然想说的是：我们应该让这三部《玩具》看起来像一个整体，一起构成一个大的故事。这也是一直以来鼓励我们去创作《玩具总动员3》的动力。&rdquo;<br />
	<br />
	　　将三部影片整合为一体成为《玩具总动员3》的中心思想。会议结束时，团队已经取得了很大的进展。皮克斯的故事大师、剧作家和导演安德鲁&middot;斯坦顿（目前正忙于制作他的第一部真人电影《火星上的约翰&middot;卡特》）负责编写最初的故事框架。　<br />
	<br />
	　　&ldquo;我们很乐观，&rdquo;昂克里奇说，&ldquo;虽然制作一部优秀的电影续集有点让人望而却步，但我们毕竟就是那个创作出了前两部影片的富有创造力的团队。会议的第二天，我们就有了安弟已经长大这个想法，还有胡迪等玩具被送到幼儿园，巴斯光年进入到演示模式这样的想法。在Andrew的主持下，每个与会者都非常兴奋。就这样，迈克尔&middot;阿姆特和我开始认真地着手这部影片的创作。&rdquo;<br />
	<br />
	&nbsp; &nbsp; &nbsp; 真挚的情感和人生体验<br />
	<br />
	　　对于荣获奥斯卡最佳原创剧本提名的剧作家迈克尔&middot;阿姆特来说，与皮克斯动画工厂的合作非常愉快。&ldquo;皮克斯制作的每部新片上映后我都要看，我非常喜欢这些影片，但是我从未想过自己会在那里工作，&rdquo;阿恩特说，&ldquo;作为淘宝网影迷，我对他们的电影有两点非常钦佩，第一，故事的完整性。你几乎很少能看到把每个细节都能构思得如此完整的电影，而皮克斯动画工厂的影片在细节与完整性方面处理得非常好；第二，在皮克斯动画工厂每一部电影的制作过程中，不论是观点镜头、对接镜头，还是镜头运动，你都能感受到喜悦和满足。你会发现你所看的电影正是由那些绝对热爱他们的工作的人完成的。&rdquo;<br />
	<br />
	　　如同皮克斯动画工厂所有伟大的电影一样，最新电影《玩具总动员3》融合了喜剧、动作和真挚的情感，给观众独特的心灵体验，在触动他们内心深处的同时也把他们逗得发笑。影片制作者们汇集了他们自己以及家人的人生体验，以使故事变得更加真实和容易理解。<br />
	<br />
	　　昂克里奇回忆说，把一大袋玩具扔出去的那个关键情节触动了他和家人的心弦，&ldquo;早在我们的孩子出生之前，我和妻子住在西好莱坞的一间公寓，准备搬到帕萨迪纳市，&rdquo;昂克里奇回忆说，&ldquo;搬家的时候我们亲自动手，把东西打包，不要的扔进垃圾袋。而扔垃圾是我的事，我把这些垃圾袋丢到了屋后的大垃圾桶里，包括一个特别大的塑料袋。几个星期后，我们已经在新家安顿好了，我妻子问我是否见过她的填充玩具。她怎么也找不到小时候玩过的那些玩具了，这些玩具她保存了很多年。我问她是放在什么样的盒子里，而她说没有放在盒子里，是放在一个垃圾袋里，非常大的垃圾袋。我心口一阵疼痛，因为我马上明白是怎么回事了，我只能把真相告诉她。我想不通她为什么会把那些玩具放进垃圾袋，而她则对我扔东西前不做检查表示不可理解。这么多年过去了，她仍不肯放过我，让我牢牢记住我扔掉了她喜欢的所有填充玩具。因此，我想到用《玩具总动员3》中的那个场景，就是安弟妈妈把一大垃圾袋玩具拎到路边的情形，来永久纪念我妻子的那些玩具，也从某种程度上证明，她那些被扔进垃圾填埋场的玩具们并没有白白丧命。&rdquo;<br />
	<br />
	　　&ldquo;任何阻扰玩具与他们的主人玩耍的行为都会令玩具们焦虑和担忧，&rdquo;拉塞特解释说，&ldquo;而每一部《玩具总动员》所处理的正是这些担忧。主要来说，在第一部影片中，胡迪担心自己会被新玩具取代。玩具们每年最担心的莫过于两个日子－－圣诞节和小主人的生日。《玩具总动员2》中，玩具们担心自己因为变旧、变破而没有人玩。胡迪则面临要么继续留在安弟身边，要么保持完美光鲜却再也不能被小孩玩的抉择。这是一个深远的话题。在第三部影片中，我们正好赶上处理玩具们最关心的问题－－过时，就是小主人长大了，不再需要他们了。玩具如果被弄坏了，可以修好；如果被弄丢了，可以找回来；如果被偷了，可以救出来。但是如果孩子长大了，不再需要玩具了，那就没有办法了。这也是故事的有趣的演进。&rdquo;<br />
	<br />
	　　&ldquo;这几部影片的秘诀就是每一部都没有企图去重复同样的感情或同样的故事，&rdquo;拉塞特继续道，&ldquo;我们是通过相同的角色，在相同的世界去处理完全不同的事情。正因如此，我们能够探触到一种完全不同的情感。每个人都可以与这些角色联系起来。从玩具的角度去看世界是一回事，而从角色的角度去看这些事就会更加深刻，也更触动人心。观众会把这些事与自己的生活体验联系起来。这部影片表现了完全不同的情感和深度。&rdquo;<br />
	<br />
	花絮<br />
	<br />
	&middot;本片的导演李&middot;昂克里奇曾经是《玩具总动员2》的副导演和《玩具总动员》的剪辑师。<br />
	<br />
	&middot;《玩具总动员3》里出现的角色都有相应的玩具，这些实体玩具都由迪士尼负责制作和发售。华特&middot;迪士尼公司预计本财政年度《玩具总动员3》相关商品销售额将达到24亿美元。<br />
	<br />
	&middot;由于之前两集的配音演员吉姆&middot;法尼于2000年去世了，在《玩具总动员3》里为弹簧狗配音的演员是布莱克&middot;克拉克。<br />
	<br />
	&middot;《玩具总动员3》将以2D、3D、IMAX3D三种形式在北美公映。同时，《玩具总动员3》也是皮克斯的首部IMAX电影。<br />
	<br />
	&middot;2010年3月，在ShoWest电影产业博览会上《玩具总动员3》率先播出了预售片花，反响热烈。<br />
	<br />
	&middot;《玩具总动员3》早在2004年就已经提上的续集制作的议程，但当时公司内部对剧情有着较大分歧。现在的剧本是在皮克斯和迪士尼的共同策划下完成的。<br />
	<br />
	&middot;皮克斯作品标志性的&ldquo;A113&rdquo;在片中出现于安迪妈妈的车牌。<br />
	<br />
	&middot;《玩具总动员3》里的肯娃娃造型是1988年后的新造型。<br />
	<br />
	&middot;在本片确定公映日期之后，《玩具总动员》和《玩具总动员&lt;/U&gt;》重新以3D的形式在2009年进行了3D版重映。这部3D版是通过迪士尼拥有的专利技术&ldquo;Disney Digital 3-D&rdquo;重制而成的立体电影，而《玩具总动员3》则一开始就按照立体电影的要求制作，将代表当今电脑动画最先进的水平。<br />
	<br />
	&middot;影片于2010年1月15日制作完毕，在那一天58位制作动画的共人员和导演李&middot;昂克里奇一起组成了一个迷你步操乐队来庆祝影片的完成。<br />
	<br />
	&middot;参与《玩具总动员3》制作的动画师里，有17名参与过《玩具总动员2》的制作，有4名参与了三部动画的制作。<br />
	<br />
	&middot;为制作影片，本片前后总共绘制了92854个故事板。<br />
	<br />
	&middot;总共有302名配音演员为影片进行了配音。<br />
	<br />
	&middot;安弟的房间有超过300张贴纸。<br />
	<br />
	&middot;安弟房间的里的地图引脚对应的是《玩具总动员3》制作人员的家乡。<br />
	<br />
	&middot;安弟房间的墙上挂着的一些装饰品是本片的艺术协调员埃林&middot;马吉尔在高中时期创作的。<br />
	<br />
	&middot;安弟房间里悬挂着一幅写有&ldquo;P。U。&rdquo;的旗帜，上面的字幕代表是是皮克斯学院，这是匹斯克为员工提高专业素养而培训的地方。<br />
	<br />
	&middot;在安弟的卧室里，隐藏着皮克斯明年推出的动画《汽车总动员2》的字样。<br />
	<br />
	&middot;A113，这个代码再次出现在电影里，这次依然是安弟妈妈的车牌号。不过他的妈妈有一个新的车牌框&mdash;&mdash;老虎的骄傲。这是导演李&middot;昂克里奇的主意，他的家乡在俄亥俄州，在那读高中的时候，吉祥物是老虎。<br />
	<br />
	&middot;披萨行星的开车，首次出现于《玩具总动员》，后来几乎出现在所有皮克斯的电影里，这次《玩具总动员3》里也有，让玩具们颠簸的行驶着。<br />
	<br />
	&middot;为了应景《玩具总动员3》，乐高创造了6英尺6英寸的身高，体重80磅的伍迪，用了超过17200块乐高积木才建成。而巴斯光年则是5英尺3英寸的身高，体重120磅，用了25000多块乐高积木。皮克斯永久保留了巴斯光年和伍迪的玩具。<br />
	<br />
	&middot;伍迪在没戴帽子的时候身高15.18英寸，戴上帽子则是15.93英寸。巴斯光年不戴头盔是11.43英寸，戴上头盔则是11.80英寸。<br />
	<br />
	&middot;伍迪一共有229个面部表情，巴斯光年则是215个。<br />
	<br />
	&middot;抱抱熊一共有3473271根毛发。<br />
	<br />
	&middot;《玩具总动员3》里出现的芭比娃娃是仿照1983年的版本&ldquo;Great Shape Barbie&rdquo;来塑造的　。<br />
	<br />
	&middot;肯在电影里有21套不同的服装。<br />
	<br />
	&middot;安弟依然由约翰&middot;莫里斯配音。其实他已经退出了娱乐圈，十多年来都没参演过影视剧，但依然被皮克斯邀请来继续为安弟配音。剧中的安弟刚上大学，而现实生活里的安弟已经26岁了。<br />
	<br />
	&middot;在《玩具总动员2》里为莫莉配音的是导演李&middot;昂克里奇的女儿汉娜&middot;昂克里奇。而在《玩具总动员3》里，莫莉的配音换成了Beatrice Miller，不过汉娜的声音依然出现在了开场的家庭录像里。<br />
	<br />
	精彩对白<br />
	<br />
	Andy&#39;s Mom:<br />
	[speaking to someone else]<br />
	Andy&#39;s Mom: Andy&#39;s going to college. Can you believe it&nbsp;<br />
	Andy: Mom, I&#39;m not leaving &#39;til Friday.<br />
	Andy&#39;s Mom: [about Andy&#39;s toys in the toy chest] What are you going to do with these old toys&nbsp;<br />
	安迪的妈妈：（同其他人说话）<br />
	安迪的妈妈：&ldquo;安迪要去上大学了。你能相信吗？&rdquo;<br />
	安迪：&ldquo;妈，周五前我都不会走的。&rdquo;<br />
	安迪的妈妈：&ldquo;那么这些旧玩具，你打算怎么处理掉呢？&rdquo;<br />
	<br />
	Sergeant: [Three of Andy&#39;s army men are preparing to jump out the window with parachutes] We&#39;ve done our duty. Andy&#39;s grown up.<br />
	Soldier: Let&#39;s face it. When the trash bags come out, we army guys are the first to go.<br />
	Buzz Lightyear: Trash bags&nbsp;<br />
	Woody: Who said anything about trash bags&nbsp;<br />
	Sergeant: It has been an honor serving with you. Good luck, folks.<br />
	警长：&ldquo;（安迪的军队准备用降落伞跳出窗口）我们完成了应尽的使命，安迪长大了。&rdquo;<br />
	士兵：&ldquo;让我们面对现实吧。当垃圾袋扔出去的时候，我们也该走了。&rdquo;<br />
	巴斯光年：&ldquo;垃圾袋？&rdquo;<br />
	伍迪：&ldquo;谁说有垃圾袋的？&rdquo;<br />
	警长：&ldquo;这是一种你应得的荣誉。祝你好运，伙计。&rdquo;</p>
<p>
	【电影截图】：<br />
	<br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://photo9.zxip.com/albums9/folder18/14189/20101005102441/201010151659101288.jpg');" src="http://photo9.zxip.com/albums9/folder18/14189/20101005102441/201010151659101288.jpg" />&nbsp;<br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://photo9.zxip.com/albums9/folder18/14189/20101005102441/201010151659105842.jpg');" src="http://photo9.zxip.com/albums9/folder18/14189/20101005102441/201010151659105842.jpg" />&nbsp;<br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://photo9.zxip.com/albums9/folder18/14189/20101005102441/20101015165912882.jpg');" src="http://photo9.zxip.com/albums9/folder18/14189/20101005102441/20101015165912882.jpg" /></p>
<br />
<p>
	[下载地址]：<img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" /></p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://4e:4e@m1.eee4.cc:1556/【3E电影院www.eee4.org】玩具总动员3[BD中英双字1024x576高清版].rmvb" target="_blank">ftp://4e:4e@m1.eee4.cc:1556/【3E电影院www.eee4.org】玩具总动员3[BD中英双字1024x576高清版].rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy241:370kk@dy241.piaohua.com:2042/小八戒电影xiaobajie.co玩具总动员3国粤英台四语720p.mkv" target="_blank">ftp://dy241:370kk@dy241.piaohua.com:2042/小八戒电影xiaobajie.co玩具总动员3国粤英台四语720p.mkv</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1B1Y0-55346.jpg{/dede:field}
