{dede:field name='keywords'}叶倩文-吴奇隆--选择迅雷下载，{/dede:field}
{dede:field name='description'}叶倩文-吴奇隆--选择迅雷下载、免费下载，叶倩文-吴奇隆--选择Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}叶倩文-吴奇隆--选择{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2006-08-04{/dede:field}
{dede:field name='body'}<object classid="CLSID:22d6f312-b0f6-11d0-94ab-0080c74c7e95" class="OBJECT" id="MediaPlayer" width="500" height="350" ><param name="ShowStatusBar" value="-1"><param name="Filename" value="http://219.129.239.194/mtv/53331com01/5120.wmv"> 
</embed></object><br /> 
<P>下载地址<BR></P> <br>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120524/133N353DD0-2G248.gif{/dede:field}
