<?php
$z[0]=Array("field","252生存者[DVD粤语中字无水印＋",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","252生存者[DVD粤语中字无水印＋原版]迅雷下载、免费下载，252生存者[DVD粤语中字无水印＋原版]Gvod高清在线播放，剧情介绍等。",72,234);
$z[1][4]['name']="description";
$z[2]=Array("field","252生存者[DVD粤语中字无水印＋原版]",236,308);
$z[2][4]['name']="title";
$z[3]=Array("field","",310,349);
$z[3][4]['name']="writer";
$z[4]=Array("field","",351,390);
$z[4][4]['name']="source";
$z[5]=Array("field","2009-07-09",392,442);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",444,481);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://4e:4e@www2.eee4.com:612/[www.eee4.cn提供]252生存者DVD粤语中字无水印.rmvb\" target=_blank>ftftp://4e:4e@www2.eee4.com:612/[www.eee4.cn提供]252生存者DVD粤语中字无水印.rmvb</A></TD></TR></TBODY></TABLE><BR><FONT color=#ff0000 size=2><STRONG>日本08最新动作大片《252发现幸存者前篇》DVD中字]：<IMG src=\"httftp://www.eee4.com/templets/img/down.jpg\" border=0></STRONG></FONT><BR>\r\n<TABLE style=\"BORDER-RIGHT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; BORDER-BOTTOM: #cccccc 1px dotted\" cellSpacing=0 cellPadding=6 width=\"95%\" align=center border=0>\r\n<TBODY>\r\n<TR>\r\n<TD style=\"WORD-WRAP: break-word\" bgColor=#fdfddf><A href=\"ftftp://e14:e14@dm.eee4.com:1216/[3E电影站www.eee4.com]252发现幸存者前篇.rmvb\" target=_blank>ftftp://e14:e14@dm.eee4.com:1216/[3E电影站www.eee4.com]252发现幸存者前篇.rmvb</A></TD></TR></TBODY></TABLE></div><ul class=\"mmlist",483,1430);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MPVY20-4SY.jpg",1432,1512);
$z[8][4]['name']="litpic";

?>