{dede:field name='keywords'}南方传奇BD中英双字1024/1280高{/dede:field}
{dede:field name='description'}南方传奇BD中英双字1024/1280高清迅雷下载、免费下载，南方传奇BD中英双字1024/1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}南方传奇BD中英双字1024/1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-01-05{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://eee4.com:8113@vip20.eee4.com:8113/[3E迅雷电影站www.eee4.com]南方传奇DVD中英双字.rmvb" target="_blank{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MOV0340-49205.jpg{/dede:field}
