{dede:field name='keywords'}战场的女武神3OVADVD中字2011日{/dede:field}
{dede:field name='description'}战场的女武神3OVADVD中字2011日本动画迅雷下载、免费下载，战场的女武神3OVADVD中字2011日本动画Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}战场的女武神3OVADVD中字2011日本动画{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-09-04{/dede:field}
{dede:field name='body'}<p>
	<img alt="" border="0" src="/uploads/allimg/c120525/133O04E2L0-K4b.jpg" /></p>
<p>
	片名: 战场的女武神3 OVA 戦場のヴァルキュリア3 誰がための銃瘡<br />
	导演: 近藤信宏<br />
	编剧: 大野木寛<br />
	主演: 中村悠一 / 远藤绫 / 浅野真澄<br />
	制片国家/地区: 日本<br />
	语言: 日语<br />
	又名: 战场的女武神3 为了谁的治愈之枪</p>
<p>
	<br />
	剧情简介</p>
<p>
	　　【Staff】<br />
	　　原作：SEGA<br />
	　　监督：近藤信宏<br />
	　　脚本：大野木宽<br />
	　　角色设计：只野和子<br />
	　　音乐：崎元仁<br />
	　　制作：A-1 Pictures<br />
	　　制作协力：Bridge<br />
	　　制作：PROJECT VALKYRIA3<br />
	　　【Cast】<br />
	　　克鲁多?艾文:中村悠一<br />
	　　里埃拉?马尔塞里斯:远藤绫<br />
	　　依姆卡:浅野真澄<br />
	　　古丝路古:桐本琢也<br />
	　　塔巴瓦:山寺宏一<br />
	　　莉迪亚?阿古提:久川綾<br />
	　　齐格:入野自由<br />
	　　威尔金?准特:千叶进步<br />
	　　艾丽西亚?梅鲁吉奥:井上麻里奈<br />
	　　伊萨拉?准特:桑岛法子<br />
	　　拉鲁克?波特尔:江川央生<br />
	　　罗洁:丰口惠<br />
	　　马克西里米安:福山润<br />
	　　赛尔贝利亚?布雷斯:大原沙耶加</p>
<p>
	<br />
	◎影片截图</p>
<p>
	&nbsp;<img alt="" src="/uploads/allimg/c120525/133O04E3c0-W520.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 340px; border-top: 0px solid; border-right: 0px solid" /></p>
<p>
	<img alt="" src="/uploads/allimg/c120525/133O04E4H0-92145.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 340px; border-top: 0px solid; border-right: 0px solid" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="/uploads/allimg/c120524/133N2Z4FF-102231.jpg" />&nbsp;&nbsp;&nbsp;
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:1485/飘花电影piaohua.com战场的女武神3OVADVD中字上篇.rmvb</td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:1486/飘花电影piaohua.com战场的女武神3OVADVD中字下篇.rmvb</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O04E5F-104B3.jpg{/dede:field}
