{dede:field name='keywords'}保镖1992HDTV高清国英双语双字12{/dede:field}
{dede:field name='description'}保镖1992HDTV高清国英双语双字1280高清迅雷下载、免费下载，保镖1992HDTV高清国英双语双字1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}保镖1992HDTV高清国英双语双字1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-02-16{/dede:field}
{dede:field name='body'}<p>
	<img border="0" src="http://img.xzz.cc/attachment/photo/Mon_1107/3861_cd0f13111388896ae1289ff386343.jpg" width="750" /></p>
<p>
	中文片名: 保镖<br />
	英文片名: The Bodyguard<br />
	国家地区: 美国<br />
	影片类型: 爱情片<br />
	资源格式: HR-HDTV<br />
	上影时间: 1992<br />
	导演 Director</p>
<p>
	　　米克&middot;杰克逊 Mick Jackson</p>
<p>
	　　编剧 Writer</p>
<p>
	　　劳伦斯&middot;卡斯丹 Lawrence Kasdan .....(written by)<br />
	对白语言: 英语&nbsp;<br />
	字幕语种: 中英&nbsp;</p>
<p>
	介绍:<br />
	◎译 名 保镖<br />
	◎片 名 The Bodyguard<br />
	◎别 名 护花倾情<br />
	◎年 代 1992<br />
	◎国 家 美国<br />
	◎类 别 剧情/爱情<br />
	◎语 言 英语/普通话<br />
	◎字 幕 中英双语<br />
	◎IMDB评分 5.6/10 (36189 票)<br />
	◎IMDB链接 <a href="http://www.imdb.com/title/tt0103855/">http://www.imdb.com/title/tt0103855/</a><br />
	◎片 长 134 分钟<br />
	◎文件大小 2.04G<br />
	◎格 式 mkv, x264<br />
	◎片 源 The.Bodyguard.1992.HDTV.1080p.x264<br />
	◎分 辨 率 1024 X 576/1280 X 720<br />
	◎导 演 米克&middot;杰克逊 Mick Jackson<br />
	◎主 演 凯文&middot;科斯特纳 Kevin Costner .....Frank Farmer<br />
	惠特尼&middot;休斯顿 Whitney Houston .....Rachel Marron<br />
	比尔&middot;考布斯 Bill Cobbs .....Bill Devaney<br />
	黛比&middot;雷诺斯 Debbie Reynolds .....Herself</p>
<p>
	◎简 介</p>
<p>
	弗兰克&middot;法默是职业保镖，而雷切尔&middot;马罗是全球知名的歌星，歌迷为她疯狂到痴醉的程度。其中的一位给她来信，说要取她的性命，于是，她请来弗兰克做她的保镖。两人虽都是本行业中的佼佼者，但却生活在完全不同的世界里。在弗兰克的信念中，确保雇主的安全就是一切，从不与顾客发生感情上的纠葛。而这次不同，雷切尔的魅力实在无法抵挡，她俩终于坠入爱河。但弗兰克不愿让这种关系干扰他的工作，所以还是与雷切尔保持一定距离。雷切尔对此很生气，直到弗兰克用身体挡住射向她的子弹她才明白，什么叫做真爱。</p>
<p>
	◎剧 情</p>
<p>
	已退职的特工弗兰克始终无法忘记在一次枪战中的痛苦经历。著名黑人女歌星梅伦的经纪人狄克请他去做梅伦的保镖。弗兰克本想拒绝，但看到梅伦5岁大的孩子*****时，他终于答应了。<br />
	梅伦家中还住着她姐姐妮基和保镖托尼。他们经常收到恐吓信，但梅伦却并不知情。弗兰克来到后加强了家中的防护措施，但梅伦对他并无好感。一次汽车跟踪事件使弗兰克确定海伦的生命确实正受到威胁，而梅伦也由此逐渐改变了对他的看法。在演唱会上，梅伦终于发现了恐吓信，狄克只好对她讲了实情。梅伦被歌迷冲下了舞台，多亏弗兰克及时相救才避免了灾难的发生。<br />
	梅伦为了答谢弗兰克而邀请他共进晚餐。两人在舞曲中渐渐陶醉。 梅伦难以抑制心中的感情，与弗兰克产生了密切的关系。梅伦感到在弗兰克身边有一种好感。<br />
	但第二天弗兰克却觉得不该和客户发生感情，两人的关系一下子疏远了。为了报复弗兰克，梅伦甚至与弗兰克的旧同事鲍曼假装亲热，使弗兰克颇为不快。 在乡村别墅，弗兰克又一次救了梅伦。他开始感 到妮基有问题。在逼问下，妮基终于承认是她雇了*****想杀梅伦。*****潜入房间，但却将妮基误认为梅伦而加以杀害。<br />
	梅伦将要出席金像奖的颁奖晚会。弗兰克知道*****一定会乘机下手，叮嘱梅伦要大胆小心。就在梅伦登上舞台时，弗兰克忽然发现了伪装成摄影师的鲍曼，他顿时明白了一切。弗兰克冲上舞台救下了梅伦，自己却中枪倒地。他挣扎着击毙了鲍曼，随即失去了知觉。<br />
	梅伦安全了。弗兰克送她登上飞机去作巡回演出，他已不再是梅伦的保镖。经过心中的激烈斗争，梅伦终于在飞机起飞前的最后一刻跑下了飞机。在风中，梅伦与弗兰克紧紧拥吻在一起。</p>
<p>
	◎相关评论</p>
<p>
	《保镖》在92年的影坛一炮走红，很大原因在于影片选材上的新颖性。它可以说是将惊险、动作、枪战、娱乐和浪漫柔情成功地组合在一起的一部影片。纵观全片，可以看出，《保镖》所注重的不再是紧张刺激的情节发展和激烈的枪战场面，而是花大量的篇幅写人世间的感情，它简直可以说是一部爱情片。<br />
	保镖弗兰克与歌星梅伦原本相互厌恶排斥，但在接触中，梅伦逐渐看到了他身上充满人情温柔的一面，并由此发展到热恋，一个&ldquo;情&rdquo;字贯穿始终。保镖的角色一改沉静冷血的面目，变成一个温文尔雅具有绅士风度的处处充满爱心的人，他为了保护孩子和一个幸福的家庭而甘受指责与冷遇，在危急时刻挺身而出，舍己为人，这种至诚至善的人情演出为影片赢得了巨大的喝彩。<br />
	同时，影片一如既往地走了明星阵容的路子，由影帝凯文&middot;科斯特纳与著名黑人女歌星惠特妮&middot;休斯顿联手出演。凯文&middot;科斯特纳仍旧演了一个热情真挚、不动声色的热血硬汉的形象，刚强勇敢之中不时透露出温馨的生活气息。而惠特妮&middot;休斯顿也表演得大开大阖，挥洒自如，将一个倔强、世俗、高傲但内心善良、渴望爱情的女歌星诠释得淋漓尽致。更值得一提的是，导演大胆创意，将一段真挚热情的爱情放置于两个不同肤色的人身上，并在影片中表现出来。这种肯定的黑白之恋在以往的电影中是并不多见的，导演的创举为影片赢得了大量观众的称赞，成为影片极获成功的一个重要因素。<br />
	&nbsp;<em>保镖的获奖情况<br />
	<br />
	&nbsp; &nbsp;&nbsp;&nbsp;1993年 MTV电影奖(MTV Movie Award) Best Movie - Europe<br />
	<br />
	&nbsp; &nbsp;&nbsp;&nbsp;1993年 MTV电影奖 最佳电影歌曲 惠特尼&middot;休斯顿<br />
	<br />
	&nbsp; &nbsp;&nbsp;&nbsp;1993年 Golden Screen, Germany(Golden Screen) (Warner Bros.)</em><br />
	<br />
	惠特妮&middot;休斯顿不在了，但她的歌声还会继续流传着，愿她在天堂里依旧歌声响亮悦耳！阿门！<br />
	<br />
	&nbsp;</p>
<p>
	<img src="http://img165.poco.cn/mypoco/myphoto/20120215/23/17870980201202152331043897667959259_012.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 640px; height: 360px; border-top: 0px solid; border-right: 0px solid" /></p>
<p>
	<img src="http://img165.poco.cn/mypoco/myphoto/20120215/23/17870980201202152331043897667959259_010.jpg" style="border-bottom: 0px solid; border-left: 0px solid; border-top: 0px solid; border-right: 0px solid" /></p>
<p>
	&nbsp;<img src="http://img165.poco.cn/mypoco/myphoto/20120215/23/17870980201202152331043897667959259_008.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 640px; height: 360px; border-top: 0px solid; border-right: 0px solid" /></p>
<p>
	1280*720版下载地址： &nbsp;<img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" /></p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy241:xiaobajie@222.187.221.241:2024/小八戒电影xiaobajie.com保镖1992HDTV高清国英双语双字1280.mkv">ftp://dy241:xiaobajie@222.187.221.241:2024/小八戒电影xiaobajie.com保镖1992HDTV高清国英双语双字1280.mkv</a></td>
		</tr>
	</tbody>
</table>
<p>
	若以上地址无法下载，请使用以下下载地址：&nbsp;&nbsp;<img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" /></p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy241:xiaobajie@222.187.221.241:2027/小八戒电影xiaobajie.com保镖1992HDTV高清国英双语双字1280.mkv">ftp://dy241:xiaobajie@222.187.221.241:2027/小八戒电影xiaobajie.com保镖1992HDTV高清国英双语双字1280.mkv</a></td>
		</tr>
	</tbody>
</table>
<p>
	1024*576版下载地址： &nbsp;<img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" /></p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:1071/飘花电影piaohua.com保镖HDTV英语对白中英字幕1024高清.mkv">ftp://dy44:piaohua@dy44.piaohua.com:1071/飘花电影piaohua.com保镖HDTV英语对白中英字幕1024高清.mkv</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15PB40-25314.jpg{/dede:field}
