{dede:field name='keywords'}马利和我BD中英双字1024/1280高{/dede:field}
{dede:field name='description'}马利和我BD中英双字1024/1280高清迅雷下载、免费下载，马利和我BD中英双字1024/1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}马利和我BD中英双字1024/1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-21{/dede:field}
{dede:field name='body'}<p>
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('/uploads/allimg/c120525/133O0VDT0-113627.jpg');" src="/uploads/allimg/c120525/133O0VDT0-113627.jpg" /></p>
<p>
	◎译　　名　《马利和我》08美国最新2亿票房可爱狗狗喜剧片DVD中英双字1024x560高清版<br />
	◎片　　名　Marley And Me<br />
	◎年　　代　2008<br />
	◎国　　家　美国<br />
	◎类　　别　喜剧/剧情/家庭/爱情<br />
	◎语　　言　英语<br />
	◎字　　幕　中英双字<br />
	◎IMDB评分 7.2/10 (13,365 votes)<br />
	◎文件格式　BD-RMVB<br />
	◎视频尺寸　1024 x 560<br />
	◎文件大小　1CD<br />
	◎片　　长　112 Minutes<br />
	<br />
	Domestic:&nbsp; $143,099,919&nbsp; &nbsp; 62.3%<br />
	+ Foreign:&nbsp; $86,585,569&nbsp; &nbsp; 37.7%<br />
	--------------------------------------------------------------------------------<br />
	= Worldwide:&nbsp; $229,685,488<br />
	<br />
	◎导　　演　大卫&middot;弗兰科尔 David Frankel<br />
	◎主　　演　詹妮弗&middot;安妮斯顿 Jennifer Aniston<br />
	　　　　　　欧文&middot;威尔逊 Owen Wilson<br />
	　　　　　　海莉&middot;贝内特 Haley Bennett<br />
	　　　　　　艾伦&middot;阿金 Alan Arkin<br />
	　　　　　　埃里克&middot;迪恩 Eric Dane<br />
	　　　　　　Victoria Roman ....Roller Blader<br />
	　　　　　　Keith Hudson ....Big Guy<br />
	　　　　　　Eric Ditman ....Reporter<br />
	　　　　　　内森&middot;甘宝 Nathan Gamble<br />
	　　　　　　Clarke Peters ....Editor<br />
	　　　　　　Haley Hudson ....Debby<br />
	　　　　　　Marc Macaulay ....The Police Officer<br />
	　　　　　　Sandy Martin ....Debbie<br />
	　　　　　　Johann Ben&eacute;t ....Brett Hodgson<br />
	　　　　　　Jimena Hoyos ....Sandra<br />
	　　　　　　Jennifer Wiener ....Reporter<br />
	　　　　　　Bryce Robinson ....Patrick - age 7<br />
	　　　　　　Benjamin Hyland ....Conor - age 5<br />
	<br />
	◎简　　介　<br />
	<br />
	&nbsp; 　约翰&middot;杰罗甘和珍妮&middot;杰罗甘的新婚之夜，一场大雪不期而至。于是，这对新婚夫妇决定离开密歇根州严寒的冬天，前往南方佛罗里达州的西棕榈海岸开始他们的新生活。来到目的地后，他们在当地有竞争关系的两家报社各自找到了记者的工作，并买下了一套房子，开始了他们的婚后生活，一切都是全新的开始。<br />
	<br />
	　　由于不确定自己是否已经做好了养育孩子的准备，约翰便向自己的好友&mdash;&mdash;同时也是报社的同事塞巴斯蒂安倾诉此事。塞巴斯蒂安给约翰提出了一个完美的解决办法，那就是约翰应该送珍妮一只小狗，并表示养狗其实很简单，不外乎散散步、喂喂东西、以及时不时把它放出去耍。<br />
	<br />
	　　黄色拉布拉多犬马利就此进入这个家庭。不知不觉中，杰罗甘夫妇饲养的马利已经从一只可爱的、12磅重小狗长大成了好动的、不安分的、精力充沛的、且重达 100磅的大狗了，因此杰罗甘家遭受到了严重的破坏。它在学校也不服从管教，它的种种劣迹还包括咬破沙发、撞翻垃圾桶、偷吃感恩节的火鸡、毁坏枕头和花园的花、喝马桶里的水、追赶联合包裹服务人员等等。甚至，连约翰送给珍妮的昂贵的新项链也被它狼吞虎咽地吞进了肚里。<br />
	<br />
	　　在马利逐渐长大地过程中，它见证了杰罗甘夫妇度过的起伏跌宕的家庭生活、陪伴他们经历了的工作和家园的变迁，最重要的是它作为家庭成员的一部分见证了这个逐渐成熟起来的家庭所历经的全部挑战和难关。慢慢地，约翰和珍妮意识到，马利&mdash;&mdash;这只世界最调皮捣蛋的狗&mdash;&mdash;已经成了他们情感中最重要的一部分。<br />
	<br />
	　　故事发生在1990年代，杰罗甘夫妇刚刚结婚不久，两人的事业都很成功，一起住在佛罗里达的新房里。夫妇俩原本打算要个孩子，但是又怕自己没经验应付不来，因此打算提前体验一回，先从照顾小狗开始。拉布拉多犬马利就此走进了他们的家庭。马利是个极其多动的小狗，四处惹麻烦，连宠物训练学校都拿它没有办法。但是随着时间的流逝，马利逐渐成为了杰罗甘一家不可缺少的成员。它的纯真、善良，永远对主人无怨无悔的付出，使杰罗甘一家经历了许多美好的瞬间&hellip;&hellip;</p>
<p>
	<br />
	<img alt="" border="0" onload="attachimg(this, 'load')" src="/uploads/allimg/c120525/133O0VE350-129423.jpg" /><br />
	<br />
	&nbsp;&nbsp;&nbsp; 幕后制作<br />
	<br />
	　　改编自畅销小说<br />
	<br />
	　　几年前，当导演大卫&middot;弗兰科尔拿着自己粗剪过的电影《穿普拉达的女王》给他的老板&mdash;&mdash;福克斯2000的主席伊丽莎白&middot;盖伯勒（Elizabeth Gabler）观看后，盖伯勒对影片非常满意，于是便交给大卫&middot;弗兰科尔另外一本畅销书的复印本准备改编成电影。这本书就是《马利和我：和世界上头号捣电影下载蛋狗的在线电影幸福生活》，作者是报纸专栏作家约翰&middot;杰罗甘，书中讲述了他和他的妻子珍妮与拉布拉多寻回犬马利一起生活的经历。这部书出版后不久，马利就以其活泼、生动、忠诚、勇敢的形象而大受读者喜爱，迅速跃居美国各大畅销书排行榜榜首，约翰也因此一炮而红，成为全美最有名的畅销书作家之一。<br />
	<br />
	　　尽管弗兰科尔很喜欢这本书，但他还是很有礼貌地拒绝了把它改编成电影的机会。大卫&middot;弗兰科尔表示&ldquo;书中没有什么矛盾冲突。尽管每章都很吸引人，但只是记录了人们的日常生活。我不知道如何把这些片段整合成一部具有张力并能抓住观众眼球的电影&rdquo;。几个月之后，盖伯勒再次把这个计划交给弗兰科尔，不同的是这次给了他一个实实在在的剧本，剧本的作者是斯科特&middot;弗兰克。这次弗兰科尔的脑海中立刻浮现出了这部影片。&ldquo;斯科特写到剧本里的是一种憧憬与向往的感觉。他不是简单的章节式地、逐字地来翻译原作。他写成了这个关于婚姻的故事&mdash;&mdash;婚姻的摩天轮载着这对夫妇度过了14年多的时间，其中的波折起伏只有这对夫妇自己能够体会。我觉得我所能够拍摄的自传体类型电影就应该是这样，因为它讲述的是一个幸福的已婚作家、与他的狗一起生活在南佛罗里达的故事，同样我也是一个幸福的已婚男人、住在迈阿密（佛罗里达州东南部城市）、有时也要花些时间写作，并且我同样养狗，而且还是5只。&rdquo;同时，弗兰科尔表示自己养的狗狗也都很疯狂，&ldquo;家里的椅子上都有很多6英寸深的洞。所有的床单上都留下了它们嚼咬过的痕迹&rdquo;。<br />
	<br />
	　　别具心裁的主演组合<br />
	<br />
	　　谈起在男女主角的选择上，导演大卫&middot;弗兰科尔首先提到的是电影想要表达的主旨，他表示这部电影想要抓住的主题是快乐的生活本身，而狗在本片中就是幸福的美丽隐喻。&ldquo;狗不会期待未来会怎么样，也不会总是缅怀过去，它们全部都是考虑&lsquo;如何在当前的时时刻刻保持开心快乐&rsquo;。现实生活中的人们恰恰经常忘记这一点。我的妻子说这是她看过的电影中最令人渴望和向往的一部。&rdquo;<br />
	<br />
	　　为了能让男主角很好地捕捉到这种电影想要表达的渴望的感觉，弗兰科尔做出了一个惊人的决定，他选择了欧文&middot;威尔逊。威尔逊之前所扮演的为观众所最熟悉的角色基本都是一些恶搞的、低俗的、搞笑的小丑类的角色（比如在《婚礼傲客》、《大兵保镖》中）。对此，弗兰科尔表示，&ldquo;这部电影对威尔逊来说是一个不错的发展机会。他是一名非常出色的演员，但是没有人真正意识到这一点。在这部电影中你们看到才是真正的威尔逊。尽管很多人并不认同，但他与好莱坞经典明星詹姆斯&middot;斯图尔特有相似之处&rdquo;。<br />
	<br />
	　　对片中的女主角，制片方的建议是詹妮弗&middot;安妮斯顿，弗兰科尔起初认为她不能演好从28岁到40多岁这么大年龄跨度的角色，但是当弗兰科尔与安妮斯顿见面仅数秒钟后，他就认定女主角非她莫属。而且，安妮斯顿在片场的表现令他十分满意，&ldquo;当安妮斯顿与威尔逊合作后，他们之间迅雷电影下载产生了迷人的化学效应，我便知道这部电影拍摄起来将会非常简单了&rdquo;，詹妮弗&middot;安妮斯顿在谈到欧文&middot;威尔逊在片场及本片中的表现时，言语间则充满了敬佩之情。&ldquo;威尔逊在这部电影中的表现太棒了。我从来没见过他饰演这样的角色。他是一个男人、他是一个丈夫、他是一位父亲&hellip;&hellip;他没有什么脾气，也不自我，他很容易合作，并且很有趣&rdquo;。<br />
	<br />
	　　可爱的动物演员<br />
	<br />
	　　在影片的拍摄过程中，马利从幼犬到14岁大小需要有22只狗来饰演。片中马利的大部分戏份是一只年轻的成年狗扮演的，戏份约占整部电影的三分之二，这只狗就是拉布拉多犬&ldquo;克莱德&rdquo;。大卫&middot;弗兰科尔戏称，克莱德被&ldquo;训练&rdquo;得又喧闹又捣蛋，&ldquo;训练员能够让它做我们需要的动作，但是从来没有教过它诸如不要跳到人身上去、不要嚼碎它想嚼的东西之类的事情，基本上，也没有人对它说过&lsquo;不&rsquo;字。它是个能量十足、精力充沛的家伙，杰罗甘表示它和真实的马利简直是一模一样。&rdquo;　而其他的扮演马利的狗狗们被选上是因为它们某一项的特技动作，比如在窗户前嚎叫、在水中转圈等，其中还有一只比较老的狗逼真地演绎出了马利年长后的动作表情。<br />
	<br />
	&nbsp; &nbsp; 　詹妮弗&middot;安妮斯顿与小狗的合作很愉快，她表示，以前的拍摄电影时常听到的&ldquo;与小孩和动物合作很困难&rdquo;的说法，在本片中并不是个问题，她甚至表示这已经是不可能再好的一次经历了。<br />
	<br />
	<img onclick="if(this.width&gt;screen.width-461) window.open('/uploads/allimg/c120525/133O0VEX0-1391O.jpg');" src="/uploads/allimg/c120525/133O0VEX0-1391O.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 333px; border-top: 0px solid; border-right: 0px solid" />&nbsp;<br />
	<img onclick="if(this.width&gt;screen.width-461) window.open('/uploads/allimg/c120525/133O0VF3P-14WX.jpg');" src="/uploads/allimg/c120525/133O0VF3P-14WX.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 333px; border-top: 0px solid; border-right: 0px solid" />&nbsp;<br />
	<img onclick="if(this.width&gt;screen.width-461) window.open('/uploads/allimg/c120525/133O0VG0-15L20.jpg');" src="/uploads/allimg/c120525/133O0VG0-15L20.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 333px; border-top: 0px solid; border-right: 0px solid" /></p>
<p>
	08美国最新可爱狗狗喜剧片《马利和我》DVD中英双字【640分辨率】 －来自[www.eee4.com]：<img border="0" src="http://www.eee4.com/templets/img/down.jpg" /></p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				</anchor>ftp://e6:e6@xl2.eee4.com:9306/[3E电影站www.eee4.com]马利和我DVD中英双字CD1.rmvb</td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				</anchor>ftp://e6:e6@xl2.eee4.com:9306/[3E电影站www.eee4.com]马利和我DVD中英双字CD2.rmvb</td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				ftp://e13:e13@xl2.eee4.com:9306/[3E电影站www.eee4.com]马利和我DVD中英双字1024x560高清版.rmvb</td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				ftp://dy44:piaohua@dy44.piaohua.com:3467/飘花电影piaohua.com马利和我BD中英双字1280高清.rmvb </td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O0VGb0-1O348.jpg{/dede:field}
