<?php
$z[0]=Array("field","机器侠[1024高清+DVD粤语＋国语",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","机器侠[1024高清+DVD粤语＋国语中字无水印]迅雷下载、免费下载，机器侠[1024高清+DVD粤语＋国语中字无水印]Gvod高清在线播放，剧情介绍等。",72,246);
$z[1][4]['name']="description";
$z[2]=Array("field","机器侠[1024高清+DVD粤语＋国语中字无水印]",248,326);
$z[2][4]['name']="title";
$z[3]=Array("field","",328,367);
$z[3][4]['name']="writer";
$z[4]=Array("field","",369,408);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-08-26",410,460);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",462,499);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://3e:3e@xl.eee4.com:242/[3E电影站www.eee4.cn]机器侠DVD粤语中字.rmvb\" target=\"_blank",501,627);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MO925310-1S52.jpg",629,712);
$z[8][4]['name']="litpic";

?>