{dede:field name='keywords'}人类消失后的世界【DVD中字高清{/dede:field}
{dede:field name='description'}人类消失后的世界【DVD中字高清版[880分辨率]】迅雷下载、免费下载，人类消失后的世界【DVD中字高清版[880分辨率]】Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}人类消失后的世界【DVD中字高清版[880分辨率]】{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-21{/dede:field}
{dede:field name='body'}<p>
	◎译　　名　《人类消失后的世界》08最新精彩纪录片BD中字[880分辨率]<br />
	◎片　　名　History Channel Life After People<br />
	◎年　　代　2008<br />
	◎国　　家　美国&nbsp;<br />
	◎类　　别　科学/纪录&nbsp; &nbsp;<br />
	◎语　　言　英语<br />
	◎字　　幕　中字<br />
	◎IMDB评分&nbsp; 7.5/10 (551 votes)<br />
	◎IMDB链接：http://www.bluemv.com<br />
	http://www.bluemv.com ◎视频尺寸　880 x 492<br />
	◎导　　演　David de Vries<br />
	◎主　　演　Struan Rodger ...&nbsp; Himself - Narrator (voice)<br />
	　　　　　　John Anderson ...&nbsp; Himself<br />
	　　　　　　David Brin ...&nbsp; Himself<br />
	　　　　　　Bill Bruninga ...&nbsp; Himself<br />
	　　　　　　Ron Chesser ...&nbsp; Himself<br />
	　　　　　　Ray Coppinger ...&nbsp; Himself<br />
	　　　　　　Eric Doehne ...&nbsp; Himself<br />
	　　　　　　Sergey Gashchak ...&nbsp; Himself<br />
	　　　　　　John Hadidian ...&nbsp; Himself<br />
	　　　　　　Kevin Harrison ...&nbsp; Himself<br />
	　　　　　　Gordon Masterton ...&nbsp; Himself<br />
	　　　　　　Nabil Nasr ...&nbsp; Himself<br />
	　　　　　　Alex Nickson ...&nbsp; Himself<br />
	　　　　　　Stephen R. Palumbi ...&nbsp; Himself (as Steve Palumbi)<br />
	　　　　　　Alan W. Pense ...&nbsp; Himself<br />
	　　　　　　Mary Sackett ...&nbsp; Herself<br />
	　　　　　　Eric Sanderson ...&nbsp; Himself<br />
	<br />
	<br />
	◎简　　介　<br />
	　　该片设定了一个有趣的背景，即：如果从明天开始，全世界60亿人类 集体消失，地球会变成什么模样？<br />
	　　如果人类突然永远地消失了，我们的地球将会怎样？生态系统能否稳定？我们的工业化世界将有什么能幸存下来？什么东西将最快分崩离析？从被毁灭的古代文明，到被自然灾害摧残着的现代城市，历史带给我们回答这些问题的线索，和人类灭绝后许多惊人的、令人深思的东西，尽在2008年1月21日21:00档的历史频道。<br />
	　　百年后，废弃的摩天大楼将会由鸟、老鼠还有植物建设成为&ldquo;垂直的生态系统&rdquo;。也许一个小动物就可以让胡佛大坝水力发电厂倒下。汹涌泛滥的河水、倒塌的桥梁和大厦、重回西部大平原的加利福尼亚灰熊和水牛群：在没有人类的世界里，这些将是视觉的印记。我们的汽车将生锈变形、归于尘土，我们的宠物将被强壮的野生动物抓住吃掉。而人类的绝大多数记录，比如书、照片、唱片呢？它们会很快地失去光彩，失落坏萎，我们在这个星球上生存过的一点点证据都将不复存在。<br />
	　　因为采用了最棒的电影视觉效果，还有工程学、植物学、生态、生物、地质、风土学和考古学等各个领域的顶尖专家支持，《人类消失后的世界》通过最终假定，带我们登上了一次令人惊异的视觉旅程。<br />
	　　1986年切尔诺贝利的核电站事故以及它带来的长远影响，为我们提供了一个有意思的、感性的课题：人类消失后将会发生什么事。《人类消失后的世界》带领观众去到遥远的小岛，在缅因州的海岸附近寻觅废弃的小镇的踪影；在纽约的街道下观察地铁隧道是如何可能成为水汪汪的运河；去蒙大拿州的原野预言熊和狼的命运。<br />
	　　我们人类不会永远存在于这个星球上。现在我们能首次在《人类消失后的世界》详详细细地看到，那一去不复返的世界。</p>
<p>
	<img alt="" border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://images.dvdempire.com/gen/movies/1394457h.jpg');" src="http://images.dvdempire.com/gen/movies/1394457h.jpg" /><br />
	<br />
	【版本一 截图】：<br />
	<br />
	<img alt="" border="0" onload="attachimg(this, 'load')" src="/uploads/allimg/c120524/133N4U4F40-95418.jpg" /><br />
	<img alt="" border="0" onload="attachimg(this, 'load')" src="/uploads/allimg/c120524/133N4U4M50-104153.jpg" /><br />
	<img alt="" border="0" onload="attachimg(this, 'load')" src="/uploads/allimg/c120524/133N4U4RF-119410.jpg" /><br />
	<img alt="" border="0" onload="attachimg(this, 'load')" src="/uploads/allimg/c120524/133N4U4WZ-122434.jpg" /><br />
	<img alt="" border="0" onload="attachimg(this, 'load')" src="/uploads/allimg/c120524/133N4U49320-134500.jpg" /><br />
	<img alt="" border="0" onload="attachimg(this, 'load')" src="/uploads/allimg/c120524/133N4U4b30-1413I.jpg" /></p>

<p>
	【版本二 截图】：</p>
<p>
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('/uploads/allimg/c120524/133N4U500F-155334.jpg');" src="/uploads/allimg/c120524/133N4U500F-155334.jpg" /><br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('/uploads/allimg/c120524/133N4U50B0-1A927.jpg');" src="/uploads/allimg/c120524/133N4U50B0-1A927.jpg" /><br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('/uploads/allimg/c120524/133N4U51260-1MF5.jpg');" src="/uploads/allimg/c120524/133N4U51260-1MF5.jpg" /><br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('/uploads/allimg/c120524/133N4U51V0-1X539.jpg');" src="/uploads/allimg/c120524/133N4U51V0-1X539.jpg" /></p>
<p>
	2009-02-10 16:2212 开始连接......<br />
	2009-02-10 16:2212 开始搜索候选资源......<br />
	2009-02-10 16:2212 搜索到22个候选资源<br />
	2009-02-10 16:2212 使用候选资源进行连接......<br />
	2009-02-10 16:2213 搜索到41个候选资源<br />
	2009-02-10 16:2213 使用候选资源进行连接......<br />
	2009-02-10 16:2213 文件创建成功，开始下载数据......<br />
	2009-02-10 16:2216 用户取消下载&nbsp;&nbsp; 本文来自：www.eee4.com</p>
<p>
	（一律使用迅雷下载）<br />
	08最新记录大片《人类消失后的世界》DVD中文字幕【版本一】 －来自[3E电影站 eee4.com]：<img border="0" src="http://www.eee4.com/templets/img/down.jpg" /></p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="BORDER-RIGHT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; BORDER-BOTTOM: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="WORD-WRAP: break-word">
				ftp://e39:e39@xl2.eee4.com:9024/[3E电影站www.eee4.com]人类消失后的世界.rmvb</td>
		</tr>
	</tbody>
</table>
<br />
<p>
	08最新精彩纪录片《人类消失后的世界》BD中字[880分辨率]&nbsp; 【版本二】－来自[3E电影站 eee4.com]：<img border="0" src="http://www.eee4.com/templets/img/down.jpg" /></p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="BORDER-RIGHT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; BORDER-BOTTOM: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="WORD-WRAP: break-word">
				ftp://e44:e44@xl2.eee4.com:9024/[3E电影站www.eee4.com]人类消失后的世界[高清].rmvb</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120524/133N4U53460-20T18.jpg{/dede:field}
