{dede:field name='keywords'}启示录之七封印/世界末日的七种{/dede:field}
{dede:field name='description'}启示录之七封印/世界末日的七种现象[DVD中字]迅雷下载、免费下载，启示录之七封印/世界末日的七种现象[DVD中字]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}启示录之七封印/世界末日的七种现象[DVD中字]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-03-17{/dede:field}
{dede:field name='body'}<p>
	<img src="http://img.album.pchome.net/54/75/18/14/f67805cb348652a092b6039ffc5ba99e.jpg" /><br />
	<br />
	<br />
	◎译　　名　《启示录之七封印/世界末日的七种现象》09年美国最新精彩纪录片DVD中字<br />
	◎片　　名　7 Signs Of The Apocalypse<br />
	◎年　　代　2009<br />
	◎国　　家　美国<br />
	◎类　　别　记录<br />
	◎语　　言　英语<br />
	◎字　　幕　中文<br />
	◎IMDB评分 6.1/10&nbsp;&nbsp; 67 votes<br />
	◎IMDB链接 http://www.imdb.com/title/tt1328644/<br />
	◎文件格式　XviD + AC3<br />
	◎视频尺寸　608 x 352<br />
	◎文件大小　1CD 49 x 15MB<br />
	◎片　　长　88 mins<br />
	◎导　　演　Tim Prokop<br />
	◎主　　演　Jon Barton ...&nbsp;&nbsp;Himself<br />
	　　　　　　Alina Dorian ...&nbsp;&nbsp;Herself<br />
	　　　　　　Armand Dorian ...&nbsp;&nbsp;Himself<br />
	　　　　　　Joseph<a href="http://www.3edyy.com/" target="_blank">3e</a> Falasca ...&nbsp;&nbsp;Host / Narrator<br />
	<br />
	◎简　　介　<br />
	<br />
	　　战争、饥荒和瘟疫是《圣经启示录》里四个骑士中的三个，他们会让世界走向末日，那么第四个反耶酥的骑士，他正化为人形在我们当中。这个古老的有2000年的预言会实现吗，在今天，人类真的会走向世界末日吗？<br />
	<br />
	视频包含内容可能会让有些观众产生鸭梨...<br />
	建议谨慎观看</p>
<p>
	【电影截图】：<br />
	<br />
	<img src="http://img.album.pchome.net/54/75/18/14/b9c7d229e7968e1592f8e70e33c7ed3c.jpg" />&nbsp;<br />
	<img src="http://img.album.pchome.net/54/75/18/14/69e45390687bf46f1d5ba786a3866393.jpg" />&nbsp;<br />
	<img src="http://img.album.pchome.net/54/75/18/14/883e01a8874f61d93d35dd6011f537ef.jpg" />&nbsp;<br />
	<img src="http://img.album.pchome.net/54/75/18/14/ed4c405720dc229e0ce9f0a12b76d042.jpg" /></p>
<br />
<br />
<br />
<p>
	【115网盘高速下载地址】:(直接点击下面链接)<a href="http://u.115.com/file/t8af5f4488" target="_blank">09年美国最新精彩纪录片《启示录之七封印/世界末日的七种现象》DVD中字</a><br />
	<br />
	09年美国最新精彩纪录片《启示录之七封印/世界末日的七种现象》DVD中字 [下载地址]：<img border="0" src="http://www.3edyy.com/templets/img/down.jpg" /></p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://4e:4e@m1.eee4.cc:1518/【3E电影院www.eee4.cc】启示录之七封印[DVD中字].rmvb" target="_blank">ftp://4e:4e@m1.eee4.cc:1518/【3E电影院www.eee4.cc】启示录之七封印[DVD中字].rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1D04460-34147.jpg{/dede:field}
