{dede:field name='keywords'}新海神号历险记/海神号迅雷下载{/dede:field}
{dede:field name='description'}新海神号历险记/海神号迅雷下载、免费下载，新海神号历险记/海神号Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}新海神号历险记/海神号{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2008-01-17{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://eee4.com:eee4@xl3.eee4.com:8448/海神号/[3E迅雷电影站www.eee4.com]海神号DVD完美中字.rmvb" target="_blank{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MPU210-4a40.jpg{/dede:field}
