<?php
$z[0]=Array("field","新海神号历险记/海神号迅雷下载",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","新海神号历险记/海神号迅雷下载、免费下载，新海神号历险记/海神号Gvod高清在线播放，剧情介绍等。",72,208);
$z[1][4]['name']="description";
$z[2]=Array("field","新海神号历险记/海神号",210,269);
$z[2][4]['name']="title";
$z[3]=Array("field","",271,310);
$z[3][4]['name']="writer";
$z[4]=Array("field","",312,351);
$z[4][4]['name']="source";
$z[5]=Array("field","2008-01-17",353,403);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",405,442);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://eee4.com:eee4@xl3.eee4.com:8448/海神号/[3E迅雷电影站www.eee4.com]海神号DVD完美中字.rmvb\" target=\"_blank",444,592);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MPU210-4a40.jpg",594,675);
$z[8][4]['name']="litpic";

?>