{dede:field name='keywords'}赛罗奥特曼2011剧场版超决战！贝{/dede:field}
{dede:field name='description'}赛罗奥特曼2011剧场版超决战！贝利亚银河帝国DVD中字迅雷下载、免费下载，赛罗奥特曼2011剧场版超决战！贝利亚银河帝国DVD中字Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}赛罗奥特曼2011剧场版超决战！贝利亚银河帝国DVD中字{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-11-13{/dede:field}
{dede:field name='body'}<p>
	<img alt="" height="600" src="/uploads/allimg/c120525/133O044H040-H551.jpg" width="429" /><br />
	<br />
	<img alt="" height="600" src="/uploads/allimg/c120525/133O044I260-XL1.jpg" width="422" /><br />
	<br />
	<img alt="" height="600" src="/uploads/allimg/c120525/133O044J450-c236.jpg" width="430" /><br />
	<br />
	<br />
	中文名： 赛罗奥特曼THEMOVIE超决战！贝利亚银河帝国<br />
	外文名： ウルトラマンゼロ THE MOVIE 超决戦！ベリア蹼银河帝国<br />
	其它译名： The Movie:Super Deciding Fight!The Belial Galactic Empire<br />
	出品时间： 2010年<br />
	出品公司： 圆谷株式会社<br />
	制片地区： 日本<br />
	导演： アベユーイチ<br />
	编剧： アベユーイチ<br />
	制片人： 铃木清<br />
	主演： 小柳友 / 滨田龙臣 / 土屋太凤 / 石桥保 / 南原健朗 / 平泉成<br />
	类型： 特摄、动作、激斗、科幻<br />
	上映时间： 2010年12月23日<br />
	imdb编码： tt1682376<br />
	监制： 圆谷一夫<br />
	主题歌： 运命のしずく～Destiny&#39;s star～<br />
	主题歌演唱： GIRL NEXT DOOR<br />
	语言： 日语<br />
	地位： 奥特曼系列诞生45周年的纪念作品<br />
	<br />
	<br />
	影片简介<br />
	<br />
	　　本作为奥特曼系列诞生45周年的纪念作品。<br />
	　　故事紧接《大怪兽格斗 超银河传说 THE MOVIE》，前作的敌人贝利亚奥特曼复活成为凯撒贝利亚，并建立起贝利亚银河帝国，企图征服宇宙。得知此事的赛罗奥特曼联同一众光之国的奥特曼，以及Mirror Knight、Glenfire、Jean-bot三战士，共同对抗贝利亚银河帝国。<br />
	<br />
	<br />
	<br />
	◎影片截图<br />
	<br />
	<img alt="" height="330" src="/uploads/allimg/c120525/133O044K560-10Y49.jpg" style="cursor: pointer" width="600" /><br />
	<br />
	<img alt="" height="330" src="/uploads/allimg/c120525/133O044L250-1125V.jpg" style="cursor: pointer" width="600" /><br />
	<br />
	<img alt="" height="330" src="/uploads/allimg/c120525/133O044L940-12N58.jpg" style="cursor: pointer" width="600" /><br />
	<br />
	<img alt="" height="330" src="/uploads/allimg/c120525/133O044M630-13S96.jpg" style="cursor: pointer" width="600" /><br />
	<br />
	<img alt="" height="330" src="/uploads/allimg/c120525/133O044N310-144A2.jpg" style="cursor: pointer" width="600" /></p>

<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="/uploads/allimg/c120524/133N2Z4FF-102231.jpg" />&nbsp;&nbsp;&nbsp;
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:2069/飘花电影piaohua.com赛罗奥特曼2011剧场版超决战！贝利亚银河帝国DVD中字.rmvb</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O044N920-154K1.jpg{/dede:field}
