{dede:field name='keywords'}喋血孤城/卫战/常德大血战[BD国{/dede:field}
{dede:field name='description'}喋血孤城/卫战/常德大血战[BD国语中字1024x576+1280x720高清版]迅雷下载、免费下载，喋血孤城/卫战/常德大血战[BD国语中字1024x576+1280x720高清版]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}喋血孤城/卫战/常德大血战[BD国语中字1024x576+1280x720高清版]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2010-11-02{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://3e:3e@d8.3edyy.com:178/【3E电影院www.eee4.cc】喋血孤城DVD国语中字.rmvb" target=_blank>ftftp://3e:3e@d8.3edyy.com:178/【3E电影院www.eee4.cc】喋血孤城DVD国语中字.rmvb</A></TD></TR></TBODY></TABLE><BR><FONT color=#ff0000 size=2><STRONG>[下载地址]：<IMG border=0 src="httftp://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MP635E0-22W5.jpg{/dede:field}
