<?php
$z[0]=Array("field","喋血孤城/卫战/常德大血战[BD国",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","喋血孤城/卫战/常德大血战[BD国语中字1024x576+1280x720高清版]迅雷下载、免费下载，喋血孤城/卫战/常德大血战[BD国语中字1024x576+1280x720高清版]Gvod高清在线播放，剧情介绍等。",72,284);
$z[1][4]['name']="description";
$z[2]=Array("field","喋血孤城/卫战/常德大血战[BD国语中字1024x576+1280x720高清版]",286,383);
$z[2][4]['name']="title";
$z[3]=Array("field","",385,424);
$z[3][4]['name']="writer";
$z[4]=Array("field","",426,465);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-11-02",467,517);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",519,556);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://3e:3e@d8.3edyy.com:178/【3E电影院www.eee4.cc】喋血孤城DVD国语中字.rmvb\" target=_blank>ftftp://3e:3e@d8.3edyy.com:178/【3E电影院www.eee4.cc】喋血孤城DVD国语中字.rmvb</A></TD></TR></TBODY></TABLE><BR><FONT color=#ff0000 size=2><STRONG>[下载地址]：<IMG border=0 src=\"httftp://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg",558,935);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MP635E0-22W5.jpg",937,1019);
$z[8][4]['name']="litpic";

?>