{dede:field name='keywords'}变蝇人/变形人魔BD1280高清迅雷{/dede:field}
{dede:field name='description'}变蝇人/变形人魔BD1280高清迅雷下载、免费下载，变蝇人/变形人魔BD1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}变蝇人/变形人魔BD1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-21{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://218.26.89.158/up/files/83/The.Fly.jpg" style="width: 500px; height: 618px" /></p>
<p>
	◎片　　名　The Fly<br />
	◎译　　名　变蝇人/变形人魔<br />
	◎年　　代　1986<br />
	◎国　　家　英国/加拿大/美国<br />
	◎类　　别　恐怖/科幻/惊悚<br />
	◎语　　言　英语<br />
	◎片　　长　95分钟<br />
	◎IMDB评分 &nbsp;7.5/10 (57,024 votes)<br />
	◎IMDB链接：<a href="http://www.bluemv.com">http://www.bluemv.com</a><br />
	◎导　　演　大卫&middot;柯南伯格 David Cronenberg<br />
	◎主　　演　杰夫&middot;高布伦 Jeff Goldblum....Seth Brundle<br />
	　　　　　 &nbsp; 吉娜&middot;戴维斯 Geena Davis....Veronica Quaife<br />
	　　　　　 &nbsp; John Getz....Stathis Borans<br />
	　　　　　 &nbsp; Joy Boushel....Tawny<br />
	　　　　　 &nbsp; Leslie Carlson....Dr. Brent Cheevers as Les Carlson<br />
	　　　　　 &nbsp; George Chuvalo....Marky<br />
	　　　　　 &nbsp; Michael Copeman....2nd Man in Bar<br />
	　　　　　 &nbsp; 大卫&middot;柯南伯格 David Cronenberg....Gynecologist<br />
	　　　　　 &nbsp; Carol Lazare....Nurse<br />
	　　　　　 &nbsp; Shawn Hewitt....Clerk<br />
	　　　　　　<br />
	　　　　　<br />
	◎简 &nbsp; &nbsp;介<br />
	<br />
	&nbsp; &nbsp; &nbsp; 年轻的科学家塞斯（Jeff Goldblum 饰）刚刚发明一台能传送物体的&ldquo;电动传送机&rdquo;，这台机器能将物体分解，传送完成后再自动合成还原。兴奋不已的塞斯决定亲自体验一下电动传送，于是，他进入了传送仓。不幸的是，一只苍蝇这时也飞进了传送仓，于是，在机器将分解后的塞斯的分子再合成时，将苍蝇的分子也合成到了塞斯的体内。塞斯成了拥有一半苍蝇基因的蝇人。<br />
	<br />
	　　起初，塞斯的身体就像蜘蛛侠一样变得强壮和精力旺盛，他的女友维罗尼卡（Geena Davis 饰）根本不相信男友的鬼话。但是，随着塞斯的身体迅速的渐渐老去，身体开始长毛，牙齿脱落，浑身冒浆，维罗尼卡渐渐接受了这个事实。她并没有遗弃男友，而是和他一起平静的接受了这个事实，即使他变得血肉模糊，她还是和他一起相拥而眠。<br />
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120516/00/62564813201205160012111547685217254_002.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120516/00/62564813201205160012111547685217254_001.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120516/00/62564813201205160012111547685217254_000.jpg" style="width: 720px; height: 405px" /><br />
	&nbsp;</p>
<p>
	【下载地址】</p>
<table bgcolor="#0099cc" border="0" cellpadding="10" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.net" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy125:piaohua@dy125.piaohua.com:8068/飘花电影piaohua.com变蝇人BD中字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:8068/飘花电影piaohua.com变蝇人BD中字1280高清.rmvb</a></td>
		</tr>
		<tr>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O16440220-16136.jpg{/dede:field}
