{dede:field name='keywords'}蓝丝绒/蓝色夜合花BD高清迅雷下{/dede:field}
{dede:field name='description'}蓝丝绒/蓝色夜合花BD高清迅雷下载、免费下载，蓝丝绒/蓝色夜合花BD高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}蓝丝绒/蓝色夜合花BD高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-20{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://i.imgur.com/L11LS.jpg" style="width: 650px; height: 853px" /></p>
<p>
	◎译　　名　蓝丝绒/蓝色夜合花<br />
	◎片　　名　Blue Velvet<br />
	◎年　　代　1986<br />
	◎国　　家　美国<br />
	◎类　　别　犯罪/悬疑/惊悚<br />
	◎IMDB评分 &nbsp;7.8/10 (63775 votes)<br />
	◎IMDB链接&nbsp; <a href="http://www.bluemv.com" target="_blank">http://www.bluemv.com</a><br />
	◎语　　言　英语<br />
	◎字　　幕　N/A<br />
	◎片　　长　120 mins 33 seconds<br />
	◎导　　演　大卫&middot;林奇 David Lynch<br />
	◎主　　演　伊莎贝拉&middot;罗西里尼 Isabella Rossellini &nbsp;....Dorothy Vallens<br />
	　　　　　　凯尔&middot;麦克拉克伦 Kyle MacLachlan &nbsp;....Jeffrey Beaumont (as Kyle Maclachlan)<br />
	　　　　　　丹尼斯&middot;霍珀 Dennis Hopper &nbsp;....Frank Booth<br />
	　　　　　　劳拉&middot;邓恩 Laura Dern &nbsp;....Sandy Williams<br />
	　　　　　　霍普&middot;兰格 Hope Lange &nbsp;....Mrs. Williams<br />
	　　　　　　迪恩&middot;斯托克维尔 Dean Stockwell &nbsp;....Ben<br />
	　　　　　　布拉德&middot;道里夫 Brad Dourif &nbsp;....Raymond<br />
	　　　　　　杰克&middot;南斯 Jack Nance &nbsp;....Paul<br />
	　　　　　　安琪洛&middot;巴达拉曼提 Angelo Badalamenti &nbsp;....Piano Player (as Andy Badale)<br />
	　　　　　　唐纳德&middot;摩尔 Donald Moore &nbsp;....Desk Sergeant<br />
	　　　　　　George Dickerson &nbsp;....Detective Williams<br />
	　　　　　　Priscilla Pointer &nbsp;....Mrs. Beaumont<br />
	　　　　　　Frances Bay &nbsp;....Aunt Barbara<br />
	　　　　　　Jack Harvey &nbsp;....Mr. Beaumont<br />
	　　　　　　Ken Stovitz &nbsp;....Mike<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;J. Michael Hunter &nbsp;....Hunter<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Dick Green &nbsp;....Don Vallens<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Fred Pickler &nbsp;....Yellow Man<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Philip Markert &nbsp;....Dr. Gynde<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Leonard Watkins &nbsp;....Double Ed<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Moses Gibson &nbsp;....Double Ed<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Selden Smith &nbsp;....Nurse Cindy<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Peter Carew &nbsp;....Coroner<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Jon Jon Snipes &nbsp;....Little Donny<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Jean Pierre Viale &nbsp;....Master of Ceremonies<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;A. Michelle Depland &nbsp;....Party Girl<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Michelle Sasser &nbsp;....Party Girl<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Katie Reid &nbsp;....Party GirlSparky &nbsp;....The Dog<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Robert J. Maxwell &nbsp;....Slow Club Customer (uncredited)<br />
	　　　　　　<br />
	◎简　　介　<br />
	<br />
	　　大学生杰弗里回故乡小镇照料患病父亲,回乡途中他意外发现一只人耳。警察威廉斯决定将此案彻查。杰弗里认识了威廉斯的女儿桑迪,二人相爱。桑迪告诉杰弗里案子可能与夜总会歌女有关。杰弗里在夜总会被歌女的美貌和气质所吸引,晚上设法来到她家,偷窥到歌女正被一个叫弗兰克的男人残忍地折磨着。弗兰克是无恶不作的黑道头子,绑架、贩毒、杀人,并且和警长狼狈为奸。弗兰克有性虐待癖,每糟蹋一个人就要在其嘴里塞上一块蓝色丝绒,或从身上割下一样东西留作&ldquo;纪念&rdquo;。 不谙世事的杰弗里这才知道,在自己生活的圈子外,这个典型的美国小镇里,还有如此黑暗的一面,他发现正自己慢慢陷入一个充满谋杀、变态的离奇世界&hellip;&hellip;<br />
	<br />
	<br />
	◎幕后制作<br />
	<br />
	影片<br />
	<br />
	　　充满争议的《蓝丝绒》是剧作家和独立电影导演大卫&middot;林奇一部充满艺术性和诡异气氛的次文化电影(Cult Film)。它平实地描述了在80年代中期,一个典型的美国小镇平静的外表下所隐藏的性、暴力、犯罪和权力。影片中的白天画面是我们所熟悉的小镇风情,带有商标式的&ldquo;美国梦&rdquo;标签,干净而祥和,但是这些背后尽力掩盖的是粗俗与堕落、暴力与反常,以及被强烈压制着的,具有极大杀伤力潜能的性冲动。导演用鲜艳的色彩探索美国中产阶级貌似正常生活下汹涌的污垢暗流。正是因为这部超现实的电影描写了大量反常性行为, 许多评论家批评它比起艺术电影、50年代的怀旧片、青春浪漫爱情剧、黑色电影或悬疑惊怵片而言,都是一种倒退。 &nbsp;<br />
	<br />
	　　尽管电影上映时,很多人嘲笑和鄙视这是一部极端的,黑色的,粗俗和令人厌恶的作品,但是《蓝丝绒》却赢得了不少荣誉:获得国家电影评论协会评出的1986年年度最佳电影、最佳导演、最佳男配角、最佳摄影成就获,同时也获得当年奥斯卡最佳导演提名。 &nbsp;<br />
	<br />
	　　这部恶梦般的电影讲述一个不谙世事的青年,发现了一只被人砍下的残耳,随后卷入一个凶残和颓废邪恶的性关系的勒索事件。两个男性主要角色暗喻出每个人生活中两个截然不同的两极:明亮与黑暗、正常与畸态、美好与邪欲。影片的暴露度并不很高,但影片中所展露的气氛,那种充斥堕落与邪恶的气氛,却让人印象深刻。某种意义上说,这可以看作一部性心理影片。影片的镜头语言看似平淡,含蓄中蕴藏了无穷的寓意,首尾呼应,令人回味。<br />
	<br />
	导演<br />
	<br />
	　　大卫&middot;林奇是当代美国非主流电影的代表人物,其影片以大胆创新且神秘诡异著称。他既是著名的编剧、导演,又是优秀的电视制作、摄影师、和作曲家。他的第一部长片《象人》是70年代著名的独立电影,1986年的《蓝丝绒》成为八十年代令观众着魔的影片经典,大卫&middot;林奇的多数作品,都是以诡秘、暴力、惊悚所著称,这种诡异阴郁、迷茫黑色的风格成为林奇独树一帜的标记。2006年,大卫&middot;林奇在第63届威尼斯国际电影节上被授予终身成就奖。<br />
	<br />
	主演<br />
	<br />
	　　女主角伊莎贝拉&middot;罗西里尼1952年生于意大利罗马,她的母亲是著名影星英格丽&middot;褒曼,父亲则是罗伯托&middot;罗西里尼,有这样难以超越的父母决定,她虽投身演艺界,但在做模特上的成功却远比做演员要辉煌得多。男主角丹尼斯&middot;霍普除在《蓝丝绒》中扮演这个叫人难忘的变态罪犯之外,还在《现代启示录》、《生死时速》和《未来水世界》等影片中也出演过重要角色。1969年,他执导的《逍遥骑士》票房大好,创下美国独立制片史上的一个奇迹。<br />
	<br />
	<br />
	◎花絮<br />
	<br />
	&middot;瓦尔&middot;基尔默原本演出杰弗里的角色,在看了剧本后他认为这是关于&ldquo;色情描写&rdquo;的,虽然他并不希望电影最终就是按照这样的版本拍摄出来的。<br />
	<br />
	&middot;林奇本打算弗兰克在和桃乐茜做爱的那场戏中,让他吸入氦气。<br />
	<br />
	&middot;在初次见面的时候,伊莎贝拉&middot;罗西里尼和凯尔&middot;麦克拉克兰就即兴创作完成了他们所有的对手戏。同一天正好是罗西里尼为角色桃乐茜试镜。<br />
	<br />
	&middot;在拍摄&ldquo;强奸仪式&rdquo;一场戏中,伊莎贝拉&middot;罗西里尼确实是全裸穿着她的那件天鹅绒外套。在电影开始拍摄之前,她的搭档丹尼斯&middot;霍普并不知道这一点,直到另一位男演员把她的腿张开好让他跪在其中。实际上,这场戏是两位演员第一次在一起合作拍摄的。<br />
	<br />
	&middot;杰弗里和弗兰克发疯似的冒着生命危险高速驾车的场景,实际上拍摄的是一辆由舞台管理操纵下摇晃着的静止的汽车。<br />
	<br />
	&middot;在桑迪的卧室,有一幅美国演员蒙哥马利&middot;克利夫特的巨幅照片。<br />
	<br />
	&middot;大卫&middot;林奇把原本时间长度为4个小时的电影中剪出了一个两小时的版本。然而无论怎样努力,剪掉的两个小时的片段再也找不回来了。唯一留下的就是场景中大量的照片。那些丢失的场景现在只有在电影的剧本当中才能读到了。<br />
	<br />
	&middot;电影开始由凯尔&middot;麦克拉克兰发现的那只耳朵,已经被俄勒冈州的波特兰市一家名位电影疯狂的录像店永久收藏。<br />
	<br />
	<br />
	◎穿帮镜头<br />
	<br />
	&middot;连贯性:杰弗里和桑迪在吃饭的时候,可乐杯子突然消失了。<br />
	<br />
	&middot;连贯性:杰弗里的耳环有的时候消失,又重新可以看到。<br />
	<br />
	&middot;桃乐茜第一次在壁橱里发现杰弗里,他正跪在她面前,这时候,杰弗里的手在不同镜头间毫无连贯性地跳跃着。</p>
<p>
	<img alt="" src="http://img165.poco.cn/mypoco/myphoto/20111105/18/62564813201111051819462443558758167_001.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img165.poco.cn/mypoco/myphoto/20111105/18/62564813201111051819462443558758167_000.jpg" style="width: 720px; height: 405px" /><br />
	<br />
	&nbsp;</p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="
ftp://dy125:piaohua@dy125.piaohua.com:7135/飘花电影piaohua.com蓝丝绒BD中字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:7135/飘花电影piaohua.com蓝丝绒BD中字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O150QU0-31032.jpg{/dede:field}
