{dede:field name='keywords'}我的邻居山田君BD国日双语中字10{/dede:field}
{dede:field name='description'}我的邻居山田君BD国日双语中字1024高清迅雷下载、免费下载，我的邻居山田君BD国日双语中字1024高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}我的邻居山田君BD国日双语中字1024高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-03-30{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://images.amazon.com/images/P/B0009MAO3M.01._AA_SCLZZZZZZZ_.jpg" /></p>
<p>
	◎中文片名：《我的邻居山田君》宫崎骏经典动画大片DVD国语配音中字无水印<br />
	◎英文片名：My Neighbors The Yamadas<br />
	◎出品年代：1999<br />
	◎国家地区：日本<br />
	◎类　　别：动画/喜剧<br />
	◎对白语言：普通话<br />
	◎字　　幕：简体中文<br />
	◎文件格式：rmvb<br />
	◎文件大小：1CD 401M<br />
	◎视频大小：800 x 440<br />
	◎片　　长：01:43:40<br />
	◎导　　演：高畑勋<br />
	◎主要演员：Molly.Shannon 富田靖子 中村玉绪<br />
	◎简　　介：</p>
<p>
	　　《我的邻居山田君》讲的是山田一家人的故事，这个日本传统的家庭有着平凡的生活：上班族的父亲，做家庭主妇的母亲，作为长辈的姥姥，孩子是兄妹两个。就是这样千千万万个普通的家庭，过着普通的生活，构成了整个社会。但是如果你仔细地去发掘，也能从中发现无数的温馨、欢乐、忧伤和痛苦。从一个个小故事中体会到生活的真谛。</p>
<p>
	◎背　　景：</p>
<p>
	　　这部片子的拍摄背景，是在宫崎完成《幽灵公主》宣布隐退之后。Ghibli少了这么一个重要人物，水准自然就会让人产生疑问。作为一个庞大的工作室，当然也不能因为某个人的隐退就解散了，工作还是要继续下去。勇于创新和挑战的Ghibli就着手试验制作了本片。</p>
<p>
	　　《我的邻居山田君》的风格区别于以往Ghibli的所有作品&mdash;&mdash;这个故事的原作的绘画风格和《蜡笔小新》<a href="http://www.eee4.com/" target="_blank">迅雷电影下载</a>十分相似，就是不讲究绘画的华丽和细腻，画的甚至有些歪歪扭扭的，但是故事是以内容见长，而不是画面。</p>
<p>
	　　原作的形式是4格漫画，改编成长篇大论当然是不可能了，再加上原作那种&ldquo;歪歪扭扭&rdquo;的作画风格，给了改编动画的Ghibli一个重大的挑战！不过高畑毕竟是大师，Ghibli的能力也不容忽视，呈现在我们眼前的动画，既忠实体现了原作那种&ldquo;歪七扭八&rdquo;的风格，但是又可以看得出来，动画制作人员的确是在上面花费了不比一般精细描绘的动画少的努力工作。象很多偷工减料的片子里面会大量出现的长时间静止画面，简单的平移这样的现象都不会出现！而且可以看到所有的地方都是在动的，甚至，有歪七扭八风格的3D场景出现&mdash;&mdash;这就是剧场版动画的力量！</p>
<p>
	　　在1小时44分钟的时间内，并没有大块的故事结构。而是以片断的形式展示了原作四格漫画中既滑稽又爆笑的情节。 有时节奏相连，有时则是一个个单独的故事，总是让人情不自禁的拍手叫好。 高田勋监督在制作本作品时，舍弃了惯用的透明画材动画， 而是尝试着使用铅笔线与水彩色调的颜色画出了素描般的作品。监督着眼于那个淡淡的没有留在记忆中的生活和反复出现却毫无感觉的事情上， 这个由铅笔画出的山田一家人正是日本家庭的素描。</p>
<p>
	宫崎骏经典动画大片《我的邻居山田君》DVD国语配音中字无水印 －来自[www.eee4.com]：<img border="0" src="http://www.eee4.com/templets/img/down.jpg" /></p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://e2:e2@xl2.eee4.com:507/[3E电影站www.eee4.com]我的邻居山田君DVD国语配音中字无水印.rmvb" target="_blank">ftp://e2:e2@xl2.eee4.com:507/[3E电影站www.eee4.com]我的邻居山田君DVD国语配音中字无水印.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3106/飘花电影piaohua.com我的邻居山田君BD国日双语中字1024高清.mkv">ftp://dy44:piaohua@dy44.piaohua.com:3106/飘花电影piaohua.com我的邻居山田君BD国日双语中字1024高清.mkv</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O151W2F-39155.jpg{/dede:field}
