{dede:field name='keywords'}2016:夜之尽头/地狱BD1280高清迅{/dede:field}
{dede:field name='description'}2016:夜之尽头/地狱BD1280高清迅雷下载、免费下载，2016:夜之尽头/地狱BD1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}2016:夜之尽头/地狱BD1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-07{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120502/08/3088764320120502081115029.jpg" style="width: 700px; height: 954px" /></p>
<p>
	◎译　　名　2016:夜之尽头/地狱<br />
	◎片　　名　Hell<br />
	◎年　　代　2011<br />
	◎国　　家　德国<br />
	◎类　　别　恐怖/科幻/惊悚<br />
	◎语　　言　德语<br />
	◎IMDB评分 &nbsp;6.1/10 (929 votes)<br />
	◎IMDB链接 &nbsp;<a class="faqlink" endcolor="FF6600" href="http://www.imdb.com/title/tt1643222" index="0" startcolor="0066ff" state="OFF" style="color: #0066ff">http://www.imdb.com/title/tt1643222</a><br />
	◎片　　长　89 Mins<br />
	◎导　　演　蒂姆&middot;菲尔巴姆 Tim Fehlbaum<br />
	◎主　　演　汉娜&middot;赫斯普朗 Hannah Herzsprung &nbsp;....Marie<br />
	　　　　　　拉斯&middot;艾丁格 Lars Eidinger &nbsp;....Phillip<br />
	　　　　　　斯坦奇&middot;艾塞克 Stipe Erceg &nbsp;....Tom<br />
	　　　　　　Lisa Vicari &nbsp;....Leonie<br />
	　　　　　　Yoann Blanc<br />
	　　　　　　Marco Calamandrei<br />
	　　　　　　Christoph Gaugler<br />
	　　　　　　安吉拉&middot;温科勒 Angela Winkler<br />
	<br />
	<br />
	<br />
	◎简　　介　<br />
	<br />
	　　在不远的未来，人们熟知的地球已经不复存在。太阳挂在天上用不可思议的热度炙烤着地球已经整整四年时间了。在这种热度的摧残下，地球分成了两块&mdash;&mdash;一块洪水肆虐，一块干旱无比。由于大饥荒，人类到了濒临灭绝的边缘，少数幸存者靠着剩余的事物和水度日。有传闻说，在一些山区，这种情况有所改善，很显然，那里在下雨。<br />
	<br />
	　　玛娜和妹妹莱奥尼想尝试进山碰碰运气，为了能成行，她们找来了菲利普。交易很简单，玛娜用身体换食物和安全。半路上，菲利普的车坏了，而且汽油也用尽了。于是他们找到了一个废弃的加油站，希望能在修好车并找到点补给。在偶遇了一些饿得半死的家伙，而且莱奥尼被劫持为人知之后，菲利普找到了一个叫做汤姆的人，汤姆能把他们的车修好并带他们上山。菲利普同意和汤姆一起开始旅途&mdash;&mdash;虽然同行的姑娘都不是很情愿。<br />
	<br />
	　　事实证明，这一路并不平坦，而且他们的补给一直在莫名其妙地减少。几天的相处之后，玛娜觉得汤姆是一个比菲利普更为可靠的伴侣。可是无情的自然也总会令他陷入僵局和困顿。慢慢地，玛娜发现偷他们补给的人不仅仅是对食物和水感兴趣，它更大的兴趣还在于她本人。但是，如果她希望看到自己妹妹还活着，她就一定要克服自己的恐惧，在没有菲利普的情况下，独自一人面对这太阳的炙热以及抢匪的绑架与威胁。<br />
	<br />
	　　一个巨大的挑战正在慢慢靠近&mdash;&mdash;这是玛娜连做梦都无法料想到的巨大的挑战&hellip;&hellip;</p>
<p>
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120507/07/62564813201205070801442396330647472_002.jpg" style="width: 650px; height: 366px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120507/07/62564813201205070801442396330647472_001.jpg" style="width: 650px; height: 366px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120507/07/62564813201205070801442396330647472_000.jpg" style="width: 650px; height: 366px" /><br />
	<br />
	&nbsp;</p>
<p>
	【下载地址】</p>
<table bgcolor="#0099cc" border="0" cellpadding="10" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.net" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy125:piaohua@dy125.piaohua.com:8026/飘花电影piaohua.com2016夜之尽头BD中字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:8026/飘花电影piaohua.com2016夜之尽头BD中字1280高清.rmvb</a></td>
		</tr>
		<tr>
		</tr>
	</tbody>
</table>
<br />{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15941P-462K.jpg{/dede:field}
