{dede:field name='keywords'}匹夫/匹夫们的战争TC清晰版国语{/dede:field}
{dede:field name='description'}匹夫/匹夫们的战争TC清晰版国语中字2012中国战争迅雷下载、免费下载，匹夫/匹夫们的战争TC清晰版国语中字2012中国战争Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}匹夫/匹夫们的战争TC清晰版国语中字2012中国战争{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-21{/dede:field}
{dede:field name='body'}<p>
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120424/10/56643687201204241021221088879129526_012.jpg" /></p>
<p>
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120424/10/56643687201204241021221088879129526_011.jpg" /></p>
<p>
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120424/10/56643687201204241021221088879129526_010.jpg" /></p>
<p>
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120424/10/56643687201204241021221088879129526_009.jpg" /></p>
<p>
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120424/10/56643687201204241021221088879129526_008.jpg" /></p>
<p>
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120424/10/56643687201204241021221088879129526_007.jpg" /></p>
<p>
	导演: 杨树鹏<br />
	编剧: 杨树鹏 / 张小北 / 老晃<br />
	主演: 黄晓明 / 张译 / 张歆艺 / 王烈 / 包小柏 / 倪景阳 / 马志明 / 孙磊 / 张粤 / 高群书 / 梁静 / 江珊 / 李子雄<br />
	类型: 剧情 / 战争 / 西部<br />
	制片国家/地区: 中国大陆<br />
	语言: 汉语普通话<br />
	上映日期: 2012-04-23(中国大陆)<br />
	片长: 105分钟<br />
	又名: 匹夫们的战争 / 匹夫有责 / An Inaccurate Memoir<br />
	官方网站：<a href="http://www.bluemv.com">http://www.bluemv.com</a><br />
	<br />
	<br />
	剧情简介<br />
	<br />
	　　匪帮首领方有望（黄晓明 饰）绑架了一个新郎官高栋梁（张译 饰），高栋梁的铁血顽强打动了匪帮的&ldquo;小姑奶奶&rdquo;方梓珍（张歆艺 饰），可是，没有人知道，高栋梁不仅仅是一个肉票那么简单&hellip;&hellip;<br />
	<br />
	<br />
	◎影片剧照</p>
<p>
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120424/10/56643687201204241021221088879129526_006.jpg" /><br />
	<br />
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120424/10/56643687201204241021221088879129526_004.jpg" /><br />
	<br />
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120424/10/56643687201204241021221088879129526_005.jpg" /><br />
	<br />
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120424/10/56643687201204241021221088879129526_003.jpg" /><br />
	<br />
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120424/10/56643687201204241021221088879129526_002.jpg" /><br />
	<br />
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120424/10/56643687201204241021221088879129526_001.jpg" /><br />
	<br />
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120424/10/56643687201204241021221088879129526_000.jpg" /><br />
	&nbsp;</p>
<p>
	&nbsp;<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120426/13/56643687201204261355266193736169627_003.jpg" /></p>
<p>
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120426/13/56643687201204261355266193736169627_002.jpg" /></p>
<p>
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120426/13/56643687201204261355266193736169627_000.jpg" /></p>
<p>
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120426/13/56643687201204261355266193736169627_001.jpg" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.netftp//dy44:piaohua@dy44.piaohua.com:3201/" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3280/飘花电影piaohua.com匹夫们的战争TS国语中字.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3280/飘花电影piaohua.com匹夫们的战争TS国语中字.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3297/飘花电影piaohua.com匹夫们的战争TC清晰版国语中字.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3297/飘花电影piaohua.com匹夫们的战争TC清晰版国语中字.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15025510-56164.jpg{/dede:field}
