{dede:field name='keywords'}X-Man_65期迅雷下载，免费下载，{/dede:field}
{dede:field name='description'}X-Man_65期迅雷下载、免费下载，X-Man_65期Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}X-Man_65期{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2006-08-17{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://ftp.upplay.com/" target=_blank>ftftp://ftp.upplay.com/</A>(用关键字加勒比社区搜索)X-Man_第65期_上.rmvb<BR><A href="ftftp://ftp.upplay.com/" target=_blank>ftftp://ftp.upplay.com/</A>(用关键字加勒比社区搜索)X-Man_第65期_下.rmvb<BR><BR><FONT face=Verdana>2006-08-03 17:12:21 开始连接<FONT face=Verdana>@更多请到：u199.com</FONT>......<BR>2006-08-03 17:12:21 开始搜索候选资源......<BR>2006-08-03 17:12:25 搜索到40个候选资源<BR>2006-08-03 17:12:25 使用候选资源进行连接......<BR>2006-08-03 17:12:26 开始下载数据......<BR>2006-08-03 17:12:30 用户取消下载<BR></FONT> <br></div><ul class="mmlist{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MO60K30-35C0.gif{/dede:field}
