<?php
$z[0]=Array("field","X-Man_65期迅雷下载，免费下载，",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","X-Man_65期迅雷下载、免费下载，X-Man_65期Gvod高清在线播放，剧情介绍等。",73,187);
$z[1][4]['name']="description";
$z[2]=Array("field","X-Man_65期",189,237);
$z[2][4]['name']="title";
$z[3]=Array("field","",239,278);
$z[3][4]['name']="writer";
$z[4]=Array("field","",280,319);
$z[4][4]['name']="source";
$z[5]=Array("field","2006-08-17",321,371);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",373,410);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://ftp.upplay.com/\" target=_blank>ftftp://ftp.upplay.com/</A>(用关键字加勒比社区搜索)X-Man_第65期_上.rmvb<BR><A href=\"ftftp://ftp.upplay.com/\" target=_blank>ftftp://ftp.upplay.com/</A>(用关键字加勒比社区搜索)X-Man_第65期_下.rmvb<BR><BR><FONT face=Verdana>2006-08-03 17:12:21 开始连接<FONT face=Verdana>@更多请到：u199.com</FONT>......<BR>2006-08-03 17:12:21 开始搜索候选资源......<BR>2006-08-03 17:12:25 搜索到40个候选资源<BR>2006-08-03 17:12:25 使用候选资源进行连接......<BR>2006-08-03 17:12:26 开始下载数据......<BR>2006-08-03 17:12:30 用户取消下载<BR></FONT> <br></div><ul class=\"mmlist",412,1043);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MO60K30-35C0.gif",1045,1127);
$z[8][4]['name']="litpic";

?>