{dede:field name='keywords'}夜店诡谈/夜店怪谈HD国语中字128{/dede:field}
{dede:field name='description'}夜店诡谈/夜店怪谈HD国语中字1280高清2012最新恐怖惊悚迅雷下载、免费下载，夜店诡谈/夜店怪谈HD国语中字1280高清2012最新恐怖惊悚Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}夜店诡谈/夜店怪谈HD国语中字1280高清2012最新恐怖惊悚{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-21{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://apollo.s.dpool.sina.com.cn/nd/dataent/moviepic/pics/116/moviepic_851fe011cd2ab9a3e34e3138b8e0f53c.jpg" /></p>
<p>
	<img alt="" src="http://apollo.s.dpool.sina.com.cn/nd/dataent/moviepic/pics/116/moviepic_b9818772e83ec17bf554830056a25d33.jpg" /></p>
<p>
	导演: 方亚熙<br />
	主演: 范逸臣 / 邓家佳 / 周秀娜 / 黄义达 / 戚玉武 / 徐洁儿 / 苑琼丹 / 赵英俊<br />
	类型: 惊悚<br />
	制片国家/地区: 中国大陆<br />
	语言: 汉语普通话<br />
	上映日期: 2012-02-10(中国大陆)<br />
	片长: 90分钟<br />
	又名: 夜店鬼谈 / 夜店怪谈<br />
	官方网站：<a href="http://www.bluemv.com" title="电影下载">http://www.bluemv.com</a><br />
	<br />
	<br />
	剧情简介<br />
	<br />
	<br />
	　　万圣节前夜，李为，迪安，小鹿，艾米，紫函来到夜店，每个人各怀心事，大家聚在一起各自讲述了一个诡异古怪、耸人听闻的故事。<br />
	　　&ldquo;失踪&rdquo;。私家侦探李为接受了女客户艾米地委托，寻找她失踪的妹妹艾丽。艾米不久前遭遇离奇车祸，她怀疑丈夫已经杀害了妹妹。午夜，艾米的丈夫夜归，艾米受惊向李为求救。李为根据蛛丝马迹发现，是艾丽与姐夫联手要杀害姐姐艾米。但事实的真相究竟如何，却出乎了所有人的预料。<br />
	　　&ldquo;单行道&rdquo;。与妻子离婚的记者迪安，迫不得已带着女儿去做一个专访。当夜，城市中发生了罕见的天文奇观。迪安在一个单行道中，进入了神秘空间，离奇事件不断发生，迪安来到了20年后。迪安遇到了20年后的女儿婷婷，他和婷婷在为返回20年前的单行道而艰难抉择&hellip;&hellip;<br />
	　　&ldquo;夜勤&rdquo;。小鹿是一个精神病院的护士，今天是她的第一天夜勤。虽然有前辈医生的带领，但同事的古怪行径还是让小鹿有些心惊胆跳。无意中，小... (展开全部) 　　万圣节前夜，李为，迪安，小鹿，艾米，紫函来到夜店，每个人各怀心事，大家聚在一起各自讲述了一个诡异古怪、耸人听闻的故事。<br />
	　　&ldquo;失踪&rdquo;。私家侦探李为接受了女客户艾米地委托，寻找她失踪的妹妹艾丽。艾米不久前遭遇离奇车祸，她怀疑丈夫已经杀害了妹妹。午夜，艾米的丈夫夜归，艾米受惊向李为求救。李为根据蛛丝马迹发现，是艾丽与姐夫联手要杀害姐姐艾米。但事实的真相究竟如何，却出乎了所有人的预料。<br />
	　　&ldquo;单行道&rdquo;。与妻子离婚的记者迪安，迫不得已带着女儿去做一个专访。当夜，城市中发生了罕见的天文奇观。迪安在一个单行道中，进入了神秘空间，离奇事件不断发生，迪安来到了20年后。迪安遇到了20年后的女儿婷婷，他和婷婷在为返回20年前的单行道而艰难抉择&hellip;&hellip;<br />
	　　&ldquo;夜勤&rdquo;。小鹿是一个精神病院的护士，今天是她的第一天夜勤。虽然有前辈医生的带领，但同事的古怪行径还是让小鹿有些心惊胆跳。无意中，小鹿得知了精神病院中的一个惊天秘密。与此同时，所有的精神病人，都被神秘能量唤醒，僵尸般集体出动&hellip;&hellip;　　<br />
	<br />
	<br />
	◎影片截图<br />
	<br />
	<img alt="" file="http://img2081.poco.cn/mypoco/myphoto/20120211/18/56643687201202111847103397555440284_004.jpg" height="400" lazyloaded="true" src="http://img2081.poco.cn/mypoco/myphoto/20120211/18/56643687201202111847103397555440284_004.jpg" style="cursor: pointer" width="600" /><br />
	<br />
	<img alt="" file="http://img2081.poco.cn/mypoco/myphoto/20120211/18/56643687201202111847103397555440284_003.jpg" height="400" lazyloaded="true" src="http://img2081.poco.cn/mypoco/myphoto/20120211/18/56643687201202111847103397555440284_003.jpg" style="cursor: pointer" width="600" /><br />
	<br />
	<img alt="" file="http://img2081.poco.cn/mypoco/myphoto/20120211/18/56643687201202111847103397555440284_002.jpg" height="400" lazyloaded="true" src="http://img2081.poco.cn/mypoco/myphoto/20120211/18/56643687201202111847103397555440284_002.jpg" style="cursor: pointer" width="600" /><br />
	<br />
	<img alt="" file="http://img2081.poco.cn/mypoco/myphoto/20120211/18/56643687201202111847103397555440284_001.jpg" height="400" lazyloaded="true" src="http://img2081.poco.cn/mypoco/myphoto/20120211/18/56643687201202111847103397555440284_001.jpg" style="cursor: pointer" width="600" /><br />
	<img alt="" file="http://img170.poco.cn/mypoco/myphoto/20120316/10/64712859201203161002483744915719405_005.jpg" height="255" lazyloaded="true" src="http://img170.poco.cn/mypoco/myphoto/20120316/10/64712859201203161002483744915719405_005.jpg" style="cursor: pointer" width="600" /><br />
	<img alt="" file="http://img170.poco.cn/mypoco/myphoto/20120316/10/64712859201203161005551760357840268_001.jpg" height="255" lazyloaded="true" src="http://img170.poco.cn/mypoco/myphoto/20120316/10/64712859201203161005551760357840268_001.jpg" style="cursor: pointer" width="600" /><br />
	<img alt="" file="http://img170.poco.cn/mypoco/myphoto/20120316/10/64712859201203161002483744915719405_004.jpg" height="255" lazyloaded="true" src="http://img170.poco.cn/mypoco/myphoto/20120316/10/64712859201203161002483744915719405_004.jpg" style="cursor: pointer" width="600" /><br />
	<img alt="" file="http://img170.poco.cn/mypoco/myphoto/20120316/10/64712859201203161005551760357840268_000.jpg" height="255" lazyloaded="true" src="http://img170.poco.cn/mypoco/myphoto/20120316/10/64712859201203161005551760357840268_000.jpg" style="cursor: pointer" width="600" /><br />
	<img alt="" file="http://img170.poco.cn/mypoco/myphoto/20120316/10/64712859201203161002483744915719405_003.jpg" height="255" lazyloaded="true" src="http://img170.poco.cn/mypoco/myphoto/20120316/10/64712859201203161002483744915719405_003.jpg" style="cursor: pointer" width="600" /><br />
	[下载地址]： &nbsp;<img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" /></p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2800/飘花电影piaohua.com夜店怪谈DVD国语中字.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2800/飘花电影piaohua.com夜店怪谈DVD国语中字.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3035/飘花电影piaohua.com夜店怪谈HD国语中字1280高清.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3035/飘花电影piaohua.com夜店怪谈HD国语中字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O164A060-51952.jpg{/dede:field}
