<?php
$z[0]=Array("field","战略大作战/凯利的英雄[BD中英双",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","战略大作战/凯利的英雄[BD中英双字1280x720高清版]迅雷下载、免费下载，战略大作战/凯利的英雄[BD中英双字1280x720高清版]Gvod高清在线播放，剧情介绍等。",73,261);
$z[1][4]['name']="description";
$z[2]=Array("field","战略大作战/凯利的英雄[BD中英双字1280x720高清版]",263,348);
$z[2][4]['name']="title";
$z[3]=Array("field","",350,389);
$z[3][4]['name']="writer";
$z[4]=Array("field","",391,430);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-07-13",432,482);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",484,521);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://4e:4e@d8.3edyy.com:170/【3E电影院www.eee4.cc】战略大作战BD中英双字1280x720高清版.rmvb\" target=\"_blank",523,669);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MP623H0-2CS.jpg",671,752);
$z[8][4]['name']="litpic";

?>