{dede:field name='keywords'}周杰伦最新歌《千里之外》迅雷下{/dede:field}
{dede:field name='description'}周杰伦最新歌《千里之外》迅雷下载、免费下载，周杰伦最新歌《千里之外》Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}周杰伦最新歌《千里之外》{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2006-09-05{/dede:field}
{dede:field name='body'}<p>资源描述： 屋檐如悬崖风铃如沧海我等燕归来<br />时间被安排演一场意外你悄然走开<br />故事在城外浓雾散不开看不清对白<br />你听不出来风声不存在是我在感慨<br /><br />梦醒来是谁在窗台把结局打开<br />那薄如蝉翼的未来经不起谁来拆<br />我送你离开千里之外你无声黑白<br />沉默年代或许不该太遥远的相爱<br />我送你离开天涯之外你是否还在<br />琴声何来生死难猜用一生去等待<br /><br />闻泪声入林寻梨花白只得一行青苔<br />天在山之外雨落花台我两鬓斑白<br />闻泪声入林寻梨花白只得一行青苔<br />天在山之外雨落花台我等你来<br /><br />一身琉璃白透明着尘埃你无瑕的爱<br />你从雨中来诗化了悲哀我淋湿现在<br />芙蓉水面采船行影犹在你却不回来<br />被岁月覆盖你说的花开过去成空白<br /><br />梦醒来是谁在窗台把结局打开<br />那薄如蝉翼的未来经不起谁来拆<br />我送你离开千里之外你无声黑白<br />沉默年代或许不该太遥远的相爱<br />我送你离开天涯之外你是否还在<br />琴声何来生死难猜用一生...<br /><br />我送你离开千里之外你无声黑白<br />沉默年代或许不该太遥远的相爱<br />我送你离开天涯之外你是否还在<br />琴声何来生死难猜用一生去等待</p>
<p>http://file1.21keke.com/source_movie/%D3%B0%CA%D3/824mv.rm</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120524/133N360Ac0-23545.jpg{/dede:field}
