{dede:field name='keywords'}2012美国综艺第69届电视电影金球{/dede:field}
{dede:field name='description'}2012美国综艺第69届电视电影金球奖颁奖典礼迅雷下载、免费下载，2012美国综艺第69届电视电影金球奖颁奖典礼Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}2012美国综艺第69届电视电影金球奖颁奖典礼{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-01-18{/dede:field}
{dede:field name='body'}<p>
	<img border="0" src="http://img165.poco.cn/mypoco/myphoto/20120117/18/56643687201201171858161349505329522_007.jpg" /></p>
<p>
	中文片名: 第69届电视电影金球奖颁奖典礼<br />
	英文片名: 69th Annual Golden Globes<br />
	资源格式: HDTV-RMVB<br />
	上影时间: 2012-01-16<br />
	主 持: Ricky Gervais<br />
	对白语言: 英语<br />
	字幕语种: 中文</p>
<p>
	介绍:<br />
	被称为&ldquo;奥斯卡前哨&rdquo;的金球奖颁奖礼于1月16日在加州洛杉矶贝弗利山庄希尔顿酒店宴会厅举行。《后人》获最佳剧情片，主演乔治-克鲁尼称帝。马丁-斯科塞斯获最佳导演，梅丽尔-斯特里普封后。《国土》获最佳剧情剧集。</p>
<p>
	<br />
	◎影片截图</p>

<p>
	<img border="0" src="http://img165.poco.cn/mypoco/myphoto/20120117/18/56643687201201171858161349505329522_002.jpg" /></p>
<p>
	<img border="0" src="http://img165.poco.cn/mypoco/myphoto/20120117/18/56643687201201171858161349505329522_000.jpg" /></p>
<p>
	<img border="0" src="http://img165.poco.cn/mypoco/myphoto/20120117/18/56643687201201171858161349505329522_003.jpg" /></p>
<p>
	<img border="0" src="http://img165.poco.cn/mypoco/myphoto/20120117/18/56643687201201171858161349505329522_004.jpg" /></p>

<p>
	[下载地址]： &nbsp;<img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" /></p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2655/飘花电影piaohua.com2012美国综艺第69届电视电影金球奖颁奖典礼1.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2655/飘花电影piaohua.com2012美国综艺第69届电视电影金球奖颁奖典礼1.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2655/飘花电影piaohua.com2012美国综艺第69届电视电影金球奖颁奖典礼2.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2655/飘花电影piaohua.com2012美国综艺第69届电视电影金球奖颁奖典礼2.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1CB160-25591.jpg{/dede:field}
