{dede:field name='keywords'}穿长筒靴的猫HD中字1280高清经典{/dede:field}
{dede:field name='description'}穿长筒靴的猫HD中字1280高清经典动画迅雷下载、免费下载，穿长筒靴的猫HD中字1280高清经典动画Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}穿长筒靴的猫HD中字1280高清经典动画{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-10-15{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://www.dianyingdiguo.com/juzhao/2010-10-6/6824627463.jpg" /></p>
<p>
	◎译　　名　穿长筒靴的猫/靴子猫的真实故事<br />
	◎片　　名　La Veritable Histoire Du Chat Botte FRENCH<br />
	◎年　　代　2009<br />
	◎国　　家　法国<br />
	◎类　　别　动画/喜剧<br />
	◎语　　言　法语<br />
	◎字　　幕　中文<br />
	◎IMDB评分 3.7/10 88 votes<br />
	◎文件格式　X264 + AC3<br />
	◎视频尺寸　1280x720<br />
	◎片　　长　80 Mins<br />
	◎导　　演　J&eacute;r?me Deschamps<br />
	　　　　　　Pascal H&eacute;rold<br />
	◎主　　演　J&eacute;r??me Deschamps ... Le chat (voice)<br />
	　　　　　　Yolande Moreau ... La reine (voice)<br />
	　　　　　　Louise Wallon ... La princesse (voice)<br />
	　　　　　　Arthur Deschamps ... Petit Pierre (voice)<br />
	　　　　　　Jean-Claude Bolle-Reddat ... Le chambellan (voice)<br />
	　　　　　　Atmen Kelif ... Doc Marcel (voice)<br />
	　　　　　　Andr&eacute; Wilms ... L&#39;ogre (voice)</p>
<p>
	◎简　　介　</p>
<p>
	　　电影《穿长靴的猫》（La Veritable histoire du Chatbotte）是由法国MK2电影公司2009年出品的立体动画作品，全片充分发挥法国式创意幽默与音乐上寓意十足的设计。故事叙述因父亲逝世而继承父业的磨坊小主人小皮耶（PetitPierre），也同时继承了一只具有魔力，会说人话，又会唱歌、跳舞逗人开心的可爱长靴猫，而它一切魔力的来源似乎来自于它的一双美丽长靴&hellip;。由于主人小皮耶爱上了美丽的玛侬公主（PrincessManon），因此长靴猫的任务就是要协助主人克服重重困难，摆脱恶毒阴险的国王侍卫与怪物的纠缠，一起赢得公主芳心&hellip;&hellip;而他们究竟会不会成功呢？</p>
<p>
	　　幕后制作</p>
<p>
	　　本片电影原声带特别之处，便是由法国著名的莫瑞提乐团（Moriarty）担任音乐演奏与演唱的工作，他们将许多著名的古典音乐曲目改编为流行音乐，在电影中可听见这些精彩又可爱的改编古典音乐巧妙地结合电影情节，可说是将卡通的娱乐与音乐教育意义发挥到极致的精彩结合。而莫瑞提乐团的女主唱萝丝玛莉（RosemaryMoriarty）慵懒又精准的变化嗓音，更是令人一听便佩服她宽广音域与音色变化的功力；加上全片一共55轨融合音乐与对白的仔细分轨，听者可以在此张原声带中感受到配乐的精湛创意的编曲与仿佛电影重现的氛围</p>

<p>
	<img alt="" src="/uploads/allimg/c120525/133O045N2Z-105314.jpg" /></p>

<p>
	[下载地址]：&nbsp;&nbsp;
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:1819/飘花电影piaohua.com穿长筒靴的猫HD中字1280高清.rmvb</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O045O2F-119435.jpg{/dede:field}
