{dede:field name='keywords'}无畏之心BD中字1280高清迅雷下载{/dede:field}
{dede:field name='description'}无畏之心BD中字1280高清迅雷下载、免费下载，无畏之心BD中字1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}无畏之心BD中字1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-08{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120425/03/64526465201204250319413142064881330_001.jpg" style="width: 700px; height: 1004px" /></p>
<p>
	<img alt="" src="http://i.imgur.com/3uIKH.jpg" style="width: 444px; height: 640px" /></p>
<p>
	【影片原名】Kahaani<br />
	【中文译名】无畏之心<br />
	【出品年代】2012 年<br />
	【上映日期】2012年3月9日 &nbsp; 印度<br />
	【IMDB链接】<a href="http://www.xiaozhizhu.net/" target="_blank">http://www.xiaozhizhu.net/</a><br />
	【IMDB评分】8.4/10 &nbsp;(7,534 votes)<br />
	【国　　家】印度<br />
	【类　　别】惊悚 &nbsp;/ &nbsp;剧情<br />
	【导　　演】Sujoy Ghosh<br />
	【主　　演】薇迪亚.巴兰<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Parambrata Chatterjee<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Nawazuddin Siddiqui<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Dhritiman Chatterjee<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Saswata Chatterjee<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Indraneil Sengupta<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Darshan Jariwala<br />
	<br />
	<br />
	<b>【内容简介】</b><br />
	<br />
	&nbsp; &nbsp; &nbsp;Vidya Bagchi从伦敦来到加尔各答寻找她失踪的丈夫。她怀着七个月的身孕只身来到这个正在庆祝杜尔迦女神节的城市，开始一段艰难残酷的寻夫旅程。她只能依靠自己对丈夫残缺的记忆，当所有人都试图劝说她，她的丈夫并不存在时，所有线索似乎走向了死局。她渐渐意识到，所有事情不是像他们表面看来那样的。整个城市都浸没在谎言中，Vidya决定为了她自己和肚里未出生的孩子&mdash;&mdash;揭开他丈夫失踪的谜团与真相&mdash;&mdash;甚至不惜牺牲她个人的生命。</p>
<p>
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120508/00/62564813201205080046219830564092958_003.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120508/00/62564813201205080046219830564092958_002.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120508/00/62564813201205080046219830564092958_001.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120508/00/62564813201205080046219830564092958_000.jpg" style="width: 720px; height: 405px" /><br />
	<br />
	&nbsp;</p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a title="最新电影" href="http://www.xiaozhizhu.net/" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy125:piaohua@dy125.piaohua.com:8035/飘花电影piaohua.com无畏之心BD中英双字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:8035/飘花电影piaohua.com无畏之心BD中英双字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O150L430-29B8.jpg{/dede:field}
