{dede:field name='keywords'}爱与狗同行迅雷下载，免费下载，{/dede:field}
{dede:field name='description'}爱与狗同行迅雷下载、免费下载，爱与狗同行Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}爱与狗同行{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2008-07-13{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://eee4.com:8113@vip20.eee4.com:8113/[3E迅雷电影站www.eee4.com]爱与狗同行DVD粤语中字.rmvb" target=_blank>ftftp://eee4.com:8113@vip20.eee4.com:8113/[3E迅雷电影站www.eee4.com]爱与狗同行DVD粤语中字.rmvb</A></TD></TR></TBODY></TABLE></div><ul class="mmlist{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MP449250-45645.jpg{/dede:field}
