<?php
$z[0]=Array("field","微观世界/草丛里的居民/点虫虫/",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","微观世界/草丛里的居民/点虫虫/小宇宙[BD中字1024x612高清版]迅雷下载、免费下载，微观世界/草丛里的居民/点虫虫/小宇宙[BD中字1024x612高清版]Gvod高清在线播放，剧情介绍等。",72,280);
$z[1][4]['name']="description";
$z[2]=Array("field","微观世界/草丛里的居民/点虫虫/小宇宙[BD中字1024x612高清版]",282,377);
$z[2][4]['name']="title";
$z[3]=Array("field","",379,418);
$z[3][4]['name']="writer";
$z[4]=Array("field","",420,459);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-01-14",461,511);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",513,550);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://3e:3e@d3.3edyy.com:121/【3E电影院www.eee4.org】微观世界BD中字1024x576高清版.mkv\" target=_blank>ftftp://3e:3e@d3.3edyy.com:121/【3E电影院www.eee4.org】微观世界BD中字1024x576高清版.mkv</A></TD></TR></TBODY></TABLE></div><ul class=\"mmlist",552,832);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MQ45K50-2G32.jpg",834,916);
$z[8][4]['name']="litpic";

?>