<?php
$z[0]=Array("field","刺激惊爆点/非常嫌疑犯/嫌疑惯犯",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","刺激惊爆点/非常嫌疑犯/嫌疑惯犯BD中英双字1024/1280高清迅雷下载、免费下载，刺激惊爆点/非常嫌疑犯/嫌疑惯犯BD中英双字1024/1280高清Gvod高清在线播放，剧情介绍等。",73,273);
$z[1][4]['name']="description";
$z[2]=Array("field","刺激惊爆点/非常嫌疑犯/嫌疑惯犯BD中英双字1024/1280高清",275,366);
$z[2][4]['name']="title";
$z[3]=Array("field","",368,407);
$z[3][4]['name']="writer";
$z[4]=Array("field","",409,448);
$z[4][4]['name']="source";
$z[5]=Array("field","2012-03-18",450,500);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",502,539);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://eee4.com:8116@vip13.eee4.com:8116/[3E迅雷电影站www.eee4.com]非常嫌疑犯DVD中英双字.rmvb\" target=\"_blank",541,688);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MO492J0-24I4.jpg",690,772);
$z[8][4]['name']="litpic";

?>