<?php
$z[0]=Array("field","反抗军/挑战/挑战纳粹BD中英双字",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","反抗军/挑战/挑战纳粹BD中英双字1024/1280高清迅雷下载、免费下载，反抗军/挑战/挑战纳粹BD中英双字1024/1280高清Gvod高清在线播放，剧情介绍等。",73,253);
$z[1][4]['name']="description";
$z[2]=Array("field","反抗军/挑战/挑战纳粹BD中英双字1024/1280高清",255,336);
$z[2][4]['name']="title";
$z[3]=Array("field","",338,377);
$z[3][4]['name']="writer";
$z[4]=Array("field","",379,418);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-10-29",420,470);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",472,509);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://e18:e18@xl2.eee4.com:9916/[3E电影站www.eee4.com]反抗军CD1.rmvb\" target=\"_blank",511,634);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MP55640-5N94.jpg",636,718);
$z[8][4]['name']="litpic";

?>