{dede:field name='keywords'}反抗军/挑战/挑战纳粹BD中英双字{/dede:field}
{dede:field name='description'}反抗军/挑战/挑战纳粹BD中英双字1024/1280高清迅雷下载、免费下载，反抗军/挑战/挑战纳粹BD中英双字1024/1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}反抗军/挑战/挑战纳粹BD中英双字1024/1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-10-29{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://e18:e18@xl2.eee4.com:9916/[3E电影站www.eee4.com]反抗军CD1.rmvb" target="_blank{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MP55640-5N94.jpg{/dede:field}
