{dede:field name='keywords'}钢之炼金术师剧场版BD1280高清迅{/dede:field}
{dede:field name='description'}钢之炼金术师剧场版BD1280高清迅雷下载、免费下载，钢之炼金术师剧场版BD1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}钢之炼金术师剧场版BD1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-02-11{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://www.zaslike.com/files/wjbtgo1qyiobeiv7whi.jpg" /></p>
<p>
	◎译　　名　钢之炼金术师 叹息之丘(米洛斯)的神圣之星<br />
	◎片　　名　钢の錬金术师 嘆きの丘(ミロス)の圣なる星<br />
	◎英文片名　Fullmetal Alchemist The Sacred Star of Milos<br />
	◎年　　代　2011<br />
	◎国　　家　日本<br />
	◎类　　别　剧情 / 动作 / 爱情 / 战争 / 动画 / 冒险<br />
	◎语　　言　日语<br />
	◎字　　幕　中字<br />
	◎IMDB评分 7.2/10&nbsp;&nbsp;(62 votes)<br />
	◎IMDB链接 <a href="http://www.imdb.com/title/tt1776196" id="url_1" target="_blank">http://www.imdb.com/title/tt1776196</a><br />
	◎片　　长　111 Mins<br />
	◎导　　演　村田和也<br />
	◎主　　演　爱德华&#12539;艾尔利克...朴璐美<br />
	　　　　　　阿尔方斯&#12539;艾尔利克...钉宫理恵<br />
	　　　　　　温莉&#12539;洛克贝尔...高本惠<br />
	　　　　　　罗伊&#12539;马斯坦...三木真一郎<br />
	　　　　　　丽莎&#12539;霍克艾...折笠富美子<br />
	　　　　　　阿列克斯&#12539;路易&#12539;阿姆斯特朗...内海贤二<br />
	　　　　　　ジュリア&#12539;クライトン...坂本真绫<br />
	　　　　　　メルビン&#12539;ボイジャー...森川智之<br />
	　　　　　　ミランダ...玉川砂记子<br />
	　　　　　　アラン...星野贵纪<br />
	　　　　　　トニ...川田绅司<br />
	　　　　　　サントス...小杉竜一<br />
	　　　　　　カルロス...吉田敬<br />
	<br />
	◎简　　介　<br />
	<br />
	　　《钢之炼金术师》的故事背景架构在一个炼金术相当发达的世界，炼金术是必须按照&ldquo;等价交换&rdquo;来理解、分解、再构造成立。在此背景之下，想让母亲复活的爱德跟阿尔两兄弟，使用了禁忌的人体炼金术。由于炼成失败使得爱德失去了左脚，阿尔失去了身体。于是爱德牺牲了右手，将阿尔的灵魂安置在盔甲里，而后为了取回失去的东西，他们决定踏上寻找&ldquo;贤者之石&rdquo;的旅程。<br />
	　　 在《钢之炼金术师-叹息之丘的圣星》中，爱德跟阿尔两兄弟目击了逃狱的犯人所施展的强大炼金术，而为了追问更多关于炼金术的事情，于是追着那位犯人来到了古雷达的边境。而在这个过去被称为&ldquo;米洛斯&rdquo;的街道中，爱德与阿尔两人碰上了一名少女，并得知了过去在这里发生的惨剧&hellip;&hellip;<br />
	<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120211/08/62564813201202110855203120955092620_002.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120211/08/62564813201202110855203120955092620_001.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120211/08/62564813201202110855203120955092620_000.jpg" style="width: 720px; height: 405px" /></p>
<p>
	<br />
	&nbsp;</p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>


<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="&#13;&#10;ftp://dy125:piaohua@dy125.piaohua.com:7598/飘花电影piaohua.com钢之炼金术师剧场版BD中字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:7598/飘花电影piaohua.com钢之炼金术师剧场版BD中字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1B25460-2MS.jpg{/dede:field}
