{dede:field name='keywords'}唐伯虎点秋香HD高清国粤闽三语10{/dede:field}
{dede:field name='description'}唐伯虎点秋香HD高清国粤闽三语1024*576迅雷下载、免费下载，唐伯虎点秋香HD高清国粤闽三语1024*576Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}唐伯虎点秋香HD高清国粤闽三语1024*576{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-09-01{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20110830/13/62564813201108301357562467509362328_000.jpg" /></p>
<p>
	【原 片 名】Flirting Scholar<br />
	【中 文 名】唐伯虎点秋香<br />
	【出品年代】1993<br />
	【IMDB链接】<a href="http://www.imdb.com/title/tt0108289" target="_blank">http://www.imdb.com/title/tt0108289</a><br />
	【IMDB评分】7.4/10 (925 votes)<br />
	【国　　家】中国/中国香港<br />
	【类　　别】喜剧/爱情<br />
	【导　　演】李力持 Lik-Chi Lee<br />
	【主　　演】郑佩佩 Pei-pei Cheng ....Madam Wah<br />
	　　　　　　周星驰 Stephen Chow ....Tong Pak Foo<br />
	　　　　　　巩俐 Li Gong ....Chen Heung<br />
	　　　　　　梁家仁 Ka-Yan Leung ....Mo Chong-Yuen<br />
	　　　　　　蓝洁瑛 Kit Ying Lam ....Wife of Tong Pak Foo<br />
	　　　　　　陈辉虹 Fai-hung Chan<br />
	　　　　　　陈百祥 Pak-cheung Chan ....Chuck Chi-Shan<br />
	　　　　　　朱铁和 Tiet Wo Chu<br />
	　　　　　　宣萱 Jessica Hester Hsuan<br />
	　　　　　　谷德昭 Vincent Kok ....Tu Chuen-Chang<br />
	　　　　　　黎彼得 Peter Lai ....Teacher<br />
	　　　　　　林威 Wai Lam ....King Ning<br />
	　　　　　　李健仁 Kin-Yan Lee<br />
	　　　　　　梁荣忠 Wing-Chung Leung<br />
	　　　　　　刘家辉 Chia Hui Liu ....Evil Scholar<br />
	　　　　　　吴镇宇 Francis Ng ....Member of The Four Scholars<br />
	　　　　　　黄一山 Gabriel Wong ....Wah-Man<br />
	　　　　　　黄霑 James Wong ....Mr. Wah<br />
	　　　　　　苑琼丹 King-Tan Yuen ....Shek-Lau<br />
	　　　　　　朱咪咪 Mimi Zhu ....Chussy<br />
	　　　　　　Carol Wan ....Tung Heung<br />
	<br />
	【内容简介】<br />
	<br />
	　　唐伯虎是江南四大才子之首，家有妻妾8人，可妻妾们整日赌博，使唐伯虎豪无幸福可言。一日，唐伯虎遇见华太师府丫鬟秋香，一见倾心，不惜化名入华府为奴以便接近秋香。华夫人夕日与唐伯虎之父有感情瓜葛，痛恨唐家，禁止华府出现唐伯虎的任何东西。秋香爱读唐寅诗集，无意中让华夫人发现，大发雷庭，幸得唐伯虎主动承担责任。宁王欲密谋造反，一直把华太师视为眼中钉，某日亲自带领人马到华府闹事，夺命书生更将华夫人打伤，唐伯虎及时出面化解危险。华夫人发现了唐伯虎的真实身份，将唐关押起来。夺命书生再次上门寻衅，唐伯虎挺身而出，用家传的霸王回马枪捅死夺命书生，报了杀父之仇。最后，华夫人同意将秋香许配给唐伯虎，但结局却&hellip;&hellip;<br />
	<br />
	【幕后制作】<br />
	<br />
	　　本片展示了香港电影人颠覆古典题材的超凡想像力。在这部影片中，各种后现代手法层出不穷，无论是行为艺术绘画、现代打击乐表演、时装模特步态以及充满广告词汇的毒药介绍，再加上&ldquo;面目全非脚&rdquo;一类的搞笑创意，原本斯斯文文的才子佳人戏被全面篡改，令人既兴奋又目瞪口呆。如把长期以来人们心目中风流英俊、才华横溢的江南四大才子刻画成好色庸俗的市井之徒，陈百祥扮演的祝枝山更是有喜欢&ldquo;人妖&rdquo;的嗜好。此片曾遭内地不少影评人批评，甚至曾被大陆媒体评为年度最庸俗电影，周星驰的拥护与反对两派的形成也自此开始。<br />
	<br />
	【精彩对白】<br />
	<br />
	　　禀夫人，小人本住在苏州的城边，家中有屋又有田，生活乐无边，谁知那唐伯虎，他蛮横不留情，勾结官府目无天，占我大屋夺我田，我爷爷跟他来讲理，惨被他一棍来打扁，我奶奶骂他欺善民，反被他捉进了唐府，强*了一百遍，一百遍，最后她悬梁自尽遗恨人间。他还将我父子，逐出了家园，流落到江边，我为救老爹，只有独自行乞在庙前，谁知那唐伯虎，他实在太阴险，知道此情形，竟派人来暗算，把我父子狂殴在市前，小人身壮健，残命得留存，可怜老父他魂归天，为求葬老爹，唯有卖身为奴自作*，一面勤赚钱，一面读书篇，发誓把功名显，手刃仇人意志坚！从此唐寅诗集在身边，我铭记此仇不共戴天！<br />
	<br />
	【华府西门前，唐伯虎和船夫推着木车】<br />
	　　（船夫躺在车上装死）<br />
	　　唐伯虎：街坊邻居们，快来啊，刚出炉的孝子大拍卖，不卖也来看一看啊！<br />
	　　（秋香和华府婢女石榴姐出门）<br />
	　　石榴姐：这位小哥，一大清早就来这里卖身葬父，太不吉利了吧？<br />
	　　唐伯虎：我也不想啊。<br />
	　　秋香：我们好像在哪儿见过吧？你看起来好面善。<br />
	　　唐伯虎：所谓相逢何必曾相识，求求两位姐姐可怜可怜我吧！<br />
	　　石榴姐：真是好惨啊！我们正好缺个下人，我看就－－<br />
	　　（这时又来一个，推着木车，车上六个死人，这人还口吐鲜血，极其悲惨！）<br />
	　　惨人：我好惨啊，卖身葬全家！<br />
	　　唐伯虎：不会吧？！<br />
	　　惨人： 两位姑娘，可怜可怜我吧，我一家六口一晚上全死光了。我身染十级肺痨，半卖半送，你就买了我吧。<br />
	　　秋香：哎呀， 石榴，你看他可怜多了，我们就把他买回华府，好不好？<br />
	　　石榴姐：（哭）那就买他吧。<br />
	　　唐伯虎：姐姐，我先来的哎。<br />
	　　秋香：这不是先来后到的问题嘛。<br />
	　　石榴姐：对呀，人家家里死了六个，你家才死一个。我也很想帮你，可是我真的很为难啊。<br />
	　　唐伯虎：可是我也很惨啊？<br />
	　　石榴姐：你有什么比他更惨的，快说出来啊。<br />
	　　唐伯虎：我&hellip;&hellip;我&hellip;&hellip;这&hellip;&hellip;这&hellip;&hellip;，你看我这几天没有剪指甲了，里面全是黑泥，难道这还不够惨吗？<br />
	　　（惨人的小狗突然死去）<br />
	　　惨人：（痛哭）旺财&hellip;&hellip;旺财&hellip;&hellip;旺财你不能死啊，旺财，你跟了我这么多年，对我有情有义，肝胆相照，但是到了现在我连一顿饱饭都没让你吃过，我对不起你啊，旺财！<br />
	　　（唐伯虎看见一只蟑螂，喊&ldquo;小心啊！&rdquo;，石榴姐一退，将蟑螂踩死了。）<br />
	　　唐伯虎：（悲痛欲绝）小强！小强你怎么了小强？小强，你不能死啊！我跟你相依为命，同甘共苦了这么多年，一直把你当亲生骨肉一样教你养你，想不到今天，白发人送黑发人！<br />
	<br />
	　【趣味对联】<br />
	　　参谋：一乡二里共三夫子不识四书五经六义竟敢教七八九十分大胆<br />
	　　华安：十室九贫凑得八两七钱六分五毫四厘尚且三心二意一等下流<br />
	　　参谋：图画里，龙不吟虎不啸，小小书僮可笑可笑<br />
	　　华安：棋盘里，车无轮马无缰，叫声将军提防提防<br />
	　　参谋：莺莺燕燕翠翠红红处处融融洽洽<br />
	　　华安：雨雨风风花花叶叶年年暮暮朝朝<br />
	　　参谋：十口心思，思君思国思社稷<br />
	　　华安：八目共赏，赏花赏月赏秋香<br />
	　　参谋：我上等威风，显现一身虎胆<br />
	　　华安：你下流卑贱，露出半个龟头<br />
	　　参谋：你家坟头来种树<br />
	　　华安：汝家澡盆杂配鱼<br />
	　　参谋：鱼肥果熟入我肚<br />
	　　华安：你老娘来亲下厨</p>
<p>
	<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20110831/11/62564813201108311150322131479223344_003.jpg" /><img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20110831/11/62564813201108311150322131479223344_004.jpg" style="width: 1280px; height: 714px" /><img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20110831/11/62564813201108311150322131479223344_005.jpg" /><img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20110831/11/62564813201108311150322131479223344_002.jpg" /><br />
	&nbsp;</p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="word-break: break-all; line-height: 18px" width="100%">
				<a href="&#13;&#10;ftp://dy125:piaohua@dy125.piaohua.com:2079/飘花电影piaohua.com唐伯虎点秋香BD高清国粤闽中字1024分辨率.mkv">ftp://dy125:piaohua@dy125.piaohua.com:2079/飘花电影piaohua.com唐伯虎点秋香BD高清国粤闽中字1024分辨率.mkv </a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1C01a0-523E.jpg{/dede:field}
