{dede:field name='keywords'}黑色眼镜蛇DVD中字2012美国动作{/dede:field}
{dede:field name='description'}黑色眼镜蛇DVD中字2012美国动作迅雷下载、免费下载，黑色眼镜蛇DVD中字2012美国动作Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}黑色眼镜蛇DVD中字2012美国动作{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-25{/dede:field}
{dede:field name='body'}<p>
	<img border="0" src="http://img2081.poco.cn/mypoco/myphoto/20120524/13/56643687201205241332451854132949520_006.jpg" /></p>
<p>
	<img border="0" src="http://img2081.poco.cn/mypoco/myphoto/20120524/13/56643687201205241332451854132949520_005.jpg" /></p>
<p>
	◎译　　名 黑色眼镜蛇<br />
	◎片　　名　Black Cobra<br />
	◎年　　代　2012<br />
	◎国　　家　美国<br />
	◎类　　别　动作<br />
	◎语　　言　英语<br />
	◎字　　幕　中文<br />
	◎IMDB评分 Awaiting 5 votes<br />
	◎IMDB链接 <a href="http://www.imdb.com/title/tt1499948">http://www.imdb.com/title/tt1499948</a><br />
	◎文件格式　DVD-RMVB<br />
	◎视频尺寸　720 x 404<br />
	◎文件大小　1CD 447MB<br />
	◎片　　长　1h 28 mn<br />
	◎导　　演　Scott Donovan<br />
	Lilly Melgar<br />
	◎主　　演　凯里-川田博之 Cary-Hiroyuki Tagawa<br />
	　　　　　　T.J. Storm<br />
	　　　　　　Jeff Wolfe</p>
<p>
	<br />
	◎简　　介　</p>
<p>
	斯维&middot;比克是南非的一个普通人，却身怀武术绝技。他最大的梦想就是过上简简单单的生活，但被卷入了为父亲争取自由的斗争。</p>
<p>
	<br />
	◎影片截图</p>
<p>
	&nbsp;<img border="0" src="http://img2081.poco.cn/mypoco/myphoto/20120524/13/56643687201205241332451854132949520_002.jpg" /></p>
<p>
	<img border="0" src="http://img2081.poco.cn/mypoco/myphoto/20120524/13/56643687201205241332451854132949520_004.jpg" /></p>
<p>
	<img border="0" src="http://img2081.poco.cn/mypoco/myphoto/20120524/13/56643687201205241332451854132949520_001.jpg" /></p>
<p>
	<img border="0" src="http://img2081.poco.cn/mypoco/myphoto/20120524/13/56643687201205241332451854132949520_003.jpg" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.netftp//dy44:piaohua@dy44.piaohua.com:3193/" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3493/飘花电影piaohua.com黑色眼镜蛇DVD中字.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3493/飘花电影piaohua.com黑色眼镜蛇DVD中字.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15D04F-552Z.jpg{/dede:field}
