{dede:field name='keywords'}龙眼高清BD1280迅雷下载，免费下{/dede:field}
{dede:field name='description'}龙眼高清BD1280迅雷下载、免费下载，龙眼高清BD1280Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}龙眼高清BD1280{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-04-19{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120419/08/62564813201204190815331947060747338_000.jpg" style="width: 700px; height: 957px" /></p>
<p>
	◎译　　名　龙眼<br />
	◎片　　名　Dragon Eyes<br />
	◎年　　代　2012<br />
	◎国　　家　美国<br />
	◎类　　别　惊悚/动作/犯罪/剧情<br />
	◎语　　言　英语<br />
	◎字　　幕　中字<br />
	◎IMDB评分 &nbsp;5.0/10 from 147 users<br />
	◎IMDB链接 &nbsp;<a href="http://www.imdb.com/title/tt1735862/" target="_blank">http://www.imdb.com/title/tt1735862/</a><br />
	◎导　　演　John Hyams<br />
	◎主　　演　Jean-Claude Van Damme &nbsp; &nbsp; &nbsp; &nbsp;... Tiano<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Peter Weller &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ... Mr. V<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Cung Le &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;... Mr. Hong<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Crystal Mantecon &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ... Rosanna<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Kristopher Van Varenberg &nbsp; &nbsp; &nbsp; &nbsp; ... Sgt. Feldman<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Monica Acosta &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;... Pedestrian<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Luis Da Silva Jr. &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ... Dash<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Jason Mitchell &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ... J-Dog<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Edrick Browne &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;... Antione<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Eddie Rouse &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;... Beach<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Sam Medina &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;... Biggie<br />
	<br />
	◎简　　介　<br />
	<br />
	&nbsp; &nbsp;St. Jude Square is a neighborhood living in fear and despair. The dueling gangs of local kingpins Dash and Antuan terrorize the streets and the citizens live without a shred of hope... until mysterious stranger Ryan Hong arrives in town. He begins to play one gang against the other using his unparalleled martial arts skills, and by calling on the teachings of his brilliant mentor Tiano to find the strength to battle back. However, just as he begins to bring the community under control, Hong is confronted by Mr. V, the town&#39;s ruthless and corrupt police chief. At first Mr. V is impressed by Hong&#39;s skill, but soon sees Hong as a threat to his regime, and the two warriors are locked in a head-to-head battle, pitting the fear and corruption of Mr. V&#39;s regime versus the new beginning Hong represents for the people of St. Jude Square.<br />
	<br />
	&nbsp; &nbsp; St. Jude 广场是一片生活在恐惧和绝望的地区。当地的黑暗势力领军人物Dash和Antuan统治着整个地区，人民生活笼罩在一片阴霾之中。终于有一天，一个神秘的陌生人Ryan Hong (Cung Le饰演)来到这个小镇，他开始用它娴熟的军事手段玩弄当地帮派，还叫来了他的师傅Tiano (Jean-Claude Van Damme)来，一起对抗当地的黑帮。。。<br />
	&nbsp; &nbsp; Hong将要面对的事小镇上残忍而且贪婪的警长。一开始警长被Hong的功夫吸引，但是很快发现他会威胁到自己的统治，一山不容二虎，两个人渐渐的陷入了白热化的斗争当中。Hong最后大获全胜，带领St. Jude广场的人们开始新生活....<br />
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120419/08/62564813201204190812194184831656636_005.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120419/08/62564813201204190812194184831656636_004.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120419/08/62564813201204190812194184831656636_003.jpg" style="width: 720px; height: 405px" /><br />
	&nbsp;</p>
<p>
	【下载地址】</p>
<table bgcolor="#0099cc" border="0" cellpadding="10" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.net" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy125:piaohua@dy125.piaohua.com:7871/飘花电影piaohua.com龙眼BD中字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:7871/飘花电影piaohua.com龙眼BD中字1280高清.rmvb</a></td>
		</tr>
		<tr>
		</tr>
	</tbody>
</table>
<br />{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15624010-5VR.jpg{/dede:field}
