{dede:field name='keywords'}卓别林：淘金记[BD中英双字960x7{/dede:field}
{dede:field name='description'}卓别林：淘金记[BD中英双字960x720高清版]迅雷下载、免费下载，卓别林：淘金记[BD中英双字960x720高清版]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}卓别林：淘金记[BD中英双字960x720高清版]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2010-05-17{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://5e:5e@d8.3edyy.com:157/【3E电影院www.eee4.cc】卓别林：淘金记BD中英双字960x720高清版.rmvb" 

target="_blank{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MQ34U30-19535.jpg{/dede:field}
