{dede:field name='keywords'}堕落天使BD高清1024*576粤语中字{/dede:field}
{dede:field name='description'}堕落天使BD高清1024*576粤语中字迅雷下载、免费下载，堕落天使BD高清1024*576粤语中字Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}堕落天使BD高清1024*576粤语中字{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-08-22{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="/uploads/allimg/c120525/133O034S1P-1Q53.jpg" style="width: 600px; height: 865px" /></p>
<p>
	【译　　名】　堕落天使<br />
	【片　　名】　Fallen Angels<br />
	【年　　代】　1995<br />
	【国　　家】　中国香港<br />
	【类　　别】　喜剧/犯罪/剧情/爱情<br />
	【语　　言】　粤语<br />
	【字幕语言】&nbsp; 中文<br />
	【视频尺寸】&nbsp; 1024&times;576<br />
	【文件格式】RMVB+AAC<br />
	【IMDB评分】 7.3/10 (6,385 votes)<br />
	【IMDB链接】 http://www.imdb.com/title/tt0112913/<br />
	【片　　长】　99 Mins<br />
	【导　　演】　王家卫 Kar Wai Wong<br />
	【主　　演】　黎明 Leon Lai ....Wong Chi-Ming/Killer<br />
	　　　　　　&nbsp; 李嘉欣 Michelle Lee ....The Killer&#39;s Agent (as Michele Reis)<br />
	　　　　　　&nbsp; 金城武 Takeshi Kaneshiro ....He Zhiwu<br />
	　　　　　　&nbsp; 杨采妮 Charlie Yeung ....Charlie/Cherry<br />
	　　　　　　&nbsp; 莫文蔚 Karen Mok ....Punkie/Blondie/Baby</p>
<p>
	<br />
	【简　　介】</p>
<p>
	剧情</p>
<p>
	　　故事由两组人物互相交错的行为组成。都市的夜空下，堕落天使1号是个杀手，一切工作都由天使2号替他安排。他们合作了很长时间，但从未见面。天使3号自从5岁那年吃了一罐过期的凤梨罐头后便不再讲话。他经常半夜撬开别人的店面，做不用本钱的生意。某夜，他遇到天使4号，并把她看作自己的初恋。天使1号发现他渐渐爱上了帮他安排暗杀生意的天使2号，但他却又巧遇旧爱天使5号。天使3号的父亲去世，夜里他反复看父亲生前的录像。被人暴打一顿的天使3号遇到孤身一人的天使2号，于是开摩托车送她回家。两人紧紧贴在一起，分享着短暂的温暖&hellip;&hellip;、</p>
<p>
	<img alt="" src="/uploads/allimg/c120525/133O034T2F-21331.jpg" style="width: 1024px; height: 576px" /><img alt="" src="/uploads/allimg/c120525/133O034U120-3ZB.jpg" /><img alt="" src="/uploads/allimg/c120525/133O034Ua0-46123.jpg" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="/uploads/allimg/c120524/133N2Z4FF-102231.jpg" />&nbsp;&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy125:piaohua@dy125.piaohua.com:2037/飘花电影piaohua.com堕落天使BD高清1024分辨率.rmvb </td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O034VQ0-55628.jpg{/dede:field}
