{dede:field name='keywords'}恐怖游轮/迷失三角洲BD中英双字1{/dede:field}
{dede:field name='description'}恐怖游轮/迷失三角洲BD中英双字1024/1280高清迅雷下载、免费下载，恐怖游轮/迷失三角洲BD中英双字1024/1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}恐怖游轮/迷失三角洲BD中英双字1024/1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-24{/dede:field}
{dede:field name='body'}<p>
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://images.blu-ray.com/movies/covers/7964_front.jpg');" src="http://images.blu-ray.com/movies/covers/7964_front.jpg" /><br />
	<br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://a69.g.akamai.net/n/69/10688/v1/img5.allocine.fr/acmedia/medias/nmedia/18/67/07/79/19160532.jpg');" src="http://a69.g.akamai.net/n/69/10688/v1/img5.allocine.fr/acmedia/medias/nmedia/18/67/07/79/19160532.jpg" /><br />
	<br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://a69.g.akamai.net/n/69/10688/v1/img5.allocine.fr/acmedia/medias/nmedia/18/67/07/79/19160531.jpg');" src="http://a69.g.akamai.net/n/69/10688/v1/img5.allocine.fr/acmedia/medias/nmedia/18/67/07/79/19160531.jpg" /><br />
	<br />
	◎译　　名　恐怖游轮/迷失三角洲<br />
	◎片　　名　Triangle<br />
	◎年　　代　2009<br />
	◎国　　家　英国/澳大利亚<br />
	◎类　　别　神秘/恐怖/惊悚<br />
	◎语　　言　英语<br />
	◎字　　幕　中英双字<br />
	◎IMDB评分 6.6/10&nbsp; 378 votes&nbsp;<br />
	◎文件格式　BD-RMVB<br />
	◎视频尺寸　1024 x 576<br />
	◎文件大小　1CD<br />
	◎片　　长　99 Minutes<br />
	◎导　　演　克里斯托弗&middot;史密斯 Christopher Smith<br />
	◎主　　演　梅利莎&middot;乔治 Melissa George....Jess<br />
	　　　　　　利亚姆&middot;海莫斯沃斯 Liam Hemsworth....Victor<br />
	　　　　　　艾玛&middot;朗 Emma Lung....Heather<br />
	　　　　　　Rachael<a href="http://www.3edyy.com/" target="_blank">3e</a> Carpani ....Sally<br />
	　　　　　　Michael Dorman ....Greg<br />
	　　　　　　Henry Nixon ....Downey<br />
	　　　　　　Joshua McIvor ....Tommy<br />
	<br />
	◎简　　介　<br />
	<br />
	　　洁西和一帮朋友乘游艇出海游玩，但她总有一种有不好的事情发生的感觉。果然，游艇遇到了风暴，于是所有人只好换乘了一辆刚好路过的大游轮来保证安全。可是洁西深信她曾乘坐过这辆大游轮，船上的钟突然停止了，一些恐怖的事情接踵而至&hellip;&hellip;</p>
<p>
	&nbsp;</p>
<p>
	【电影截图】：<br />
	<br />
	<a href="http://photo5.zxip.com/albums5/folder10/7895/20100122145153/20101261222192732.jpg" target="_blank"><img src="http://photo5.zxip.com/albums5/folder10/7895/20100122145153/20101261222192732.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 338px; border-top: 0px solid; border-right: 0px solid" /></a>&nbsp;<br />
	<a href="http://photo5.zxip.com/albums5/folder10/7895/20100122145153/2010126122220277.jpg" target="_blank"><img src="http://photo5.zxip.com/albums5/folder10/7895/20100122145153/2010126122220277.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 338px; border-top: 0px solid; border-right: 0px solid" /></a></p>
<p>
	[下载地址]<img border="0" src="/templets/img/down.jpg" /></p>
<p>
	&nbsp;</p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://3e:3e@www2.3edyy.com:3885/【3E电影院www.3edyy.com】恐怖游轮BD中英双字1024x576高清版无水印.rmvb" target="_blank">ftp://3e:3e@www2.3edyy.com:3885/【3E电影院www.3edyy.com】恐怖游轮BD中英双字1024x576高清版无水印.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3486/飘花电影piaohua.com迷失三角洲BD中英双字1280高清.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3486/飘花电影piaohua.com迷失三角洲BD中英双字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>
<p>
	&nbsp;</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1514440-454M.jpg{/dede:field}
