<?php
$z[0]=Array("field","2022大海啸[DVD中字]迅雷下载，",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","2022大海啸[DVD中字]迅雷下载、免费下载，2022大海啸[DVD中字]Gvod高清在线播放，剧情介绍等。",72,204);
$z[1][4]['name']="description";
$z[2]=Array("field","2022大海啸[DVD中字]",206,263);
$z[2][4]['name']="title";
$z[3]=Array("field","",265,304);
$z[3][4]['name']="writer";
$z[4]=Array("field","",306,345);
$z[4][4]['name']="source";
$z[5]=Array("field","2009-10-16",347,397);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",399,436);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://3e:3e@www2.eee4.com:799/[3E电影站www.eee4.cn]2022大海啸.rmvb\" target=_blank>ftftp://3e:3e@www2.eee4.com:799/[3E电影站www.eee4.cn]2022大海啸.rmvb</A></TD></TR></TBODY></TABLE><BR><FONT color=#ff0000 size=2><STRONG>09泰国最新科幻灾难片《2022大海啸》DVD中字 [<FONT color=#0909f7 size=4>2009/10/16更新</FONT>下载地址]：<IMG src=\"httftp://www.eee4.com/templets/img/down.jpg\" border=0></STRONG></FONT><BR>\r\n<TABLE style=\"BORDER-RIGHT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; BORDER-BOTTOM: #cccccc 1px dotted\" cellSpacing=0 cellPadding=6 width=\"95%\" align=center border=0>\r\n<TBODY>\r\n<TR>\r\n<TD style=\"WORD-WRAP: break-word\" bgColor=#fdfddf><A href=\"ftftp://3e:3e@www2.eee4.com:808/[3E电影站www.eee4.cn]2022大海啸DVD中字.rmvb\" target=_blank>ftftp://3e:3e@www2.eee4.com:808/[3E电影站www.eee4.cn]2022大海啸DVD中字.rmvb</A></TD></TR></TBODY></TABLE></div><ul class=\"mmlist",438,1410);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MPWS0-55104.jpg",1412,1493);
$z[8][4]['name']="litpic";

?>