{dede:field name='keywords'}形影不离1024HD国语中字2012中国{/dede:field}
{dede:field name='description'}形影不离1024HD国语中字2012中国剧情迅雷下载、免费下载，形影不离1024HD国语中字2012中国剧情Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}形影不离1024HD国语中字2012中国剧情{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-06{/dede:field}
{dede:field name='body'}<p>
	<img src="http://img.funshion.com/attachment/new_images/2011/10-25/17888460_1319533991_335.jpg" /></p>
<p>
	<img src="http://img.funshion.com/attachment/new_images/2011/10-25/17888460_1319534024_484.jpg" /></p>
<p>
	&nbsp;<img border="0" height="650" src="http://www.yuxi.gov.cn/UpFile/2012/05/03/2012050308582956/12485829198049.jpg" /></p>
<p>
	片名: 形影不离<br />
	导演: 伍仕贤<br />
	编剧: 伍仕贤<br />
	主演: 吴彦祖 / 龚蓓苾 / 凯文&middot;史派西 / 闫妮 / 张默 / 彼得&middot;斯特曼 / 曾江 / 干露露<br />
	类型: 剧情 / 喜剧 / 悬疑<br />
	制片国家/地区: 中国大陆<br />
	语言: 英语 / 汉语普通话<br />
	上映日期: 2012-05-04(中国大陆)<br />
	片长: 93分钟<br />
	形影不离的剧情简介 &middot; &middot; &middot; &middot; &middot; &middot;<br />
	　　情节曲折的精彩故事发生在中国南部某城市。<br />
	　　29岁的李越（吴彦祖 饰）是某高科技假肢公司一位疲惫不堪、分身乏术的工程师。故事的开始李越试图自杀，却巧被他的老外邻居老查（凯文&middot;史派西 饰）救下，俩人因此成为了好朋友。老查慢慢帮李越解决了工作上的问题和与妻子阿胖&mdash;&mdash;一个极其情绪化的暗访记者（龚蓓苾 饰）&mdash;&mdash;感情中出现的问题&hellip;&hellip;于是李越和老查一起踏上了一段神奇的旅程&hellip;&hellip;<br />
	　　但老查真的只是一个普通的邻居吗？</p>
<p>
	《形影不离》讲述的是发生在中国城市的一个多线索的故成事，兼具爱情、喜剧、动作、悬念元素：吴彦祖扮演一个工作和家里遇到麻烦不断的年轻工程师，他的妻子龚蓓苾是个调查记者，闫妮饰演吴彦祖上司，因公司要上市给吴彦祖带来了不少压力，吴彦祖和一个神秘莫测的美国人（凯文史派西饰演）偶遇后，开始不断发生惊险刺激而笑料百出的场面，&ldquo;失控&rdquo;的他们共同踏上了生命中的一个完全意外的旅途。</p>
<p>
	<img border="0" src="http://pub.chinaunix.net/uploadfile/201205/20120504040721468.jpg" /></p>
<p>
	<img border="0" src="http://photocdn.sohu.com/20120504/Img342357483.jpg" /></p>
<p>
	<img border="0" src="http://photocdn.sohu.com/20120504/Img342357470.jpg" /></p>


<p>
	影片入围了2011年韩国釜山电影节&ldquo;亚洲之窗&rdquo;展映单元，这是伍仕贤导演继《车四十四》、《独自等待》后第三次入围该电影节。</p>

<p>
	<img alt="" src="http://pic.piaohua.com/0701pic/allimg/120506/1-1205060443451G.jpg" style="width: 600px; height: 260px" /></p>
<p>
	<img alt="" src="http://pic.piaohua.com/0701pic/allimg/120506/1-120506044352b5.jpg" style="width: 600px; height: 262px" /></p>
<p>
	<img alt="" height="338" src="http://img.sceper.eu/images/rSsmR.jpg" width="600" /></p>
<p>
	<img alt="" height="338" src="http://img.sceper.eu/images/GR618.jpg" width="600" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.net/">http://www.xiaozhizhu.net</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3360/飘花电影piaohua.com形影不离1024HD国语中字.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3360/飘花电影piaohua.com形影不离1024HD国语中字.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="thunder://QUFodHRwOi8vdGh1bmRlci5mZmR5LmNjLzJGQzNBQzQ0NTJFNzZFODREMzQ5NUZGODRCMjQyNzFGQjZGQkZBQkQv5b2i5b2x5LiN56a7RFZELnJtdmJaWg==/">ftp://dy44:piaohua@dy44.piaohua.com:3360/飘花电影piaohua.com形影不离HD国语中字.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1595Q60-11316.jpg{/dede:field}
