{dede:field name='keywords'}死亡塔BD中字1024分辨率迅雷下载{/dede:field}
{dede:field name='description'}死亡塔BD中字1024分辨率迅雷下载、免费下载，死亡塔BD中字1024分辨率Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}死亡塔BD中字1024分辨率{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-09-19{/dede:field}
{dede:field name='body'}<p>
	◎译　　名　《死亡塔》李小龙精彩动作大片DVD中字<br />
	◎片　　名　Game Of Death II<br />
	◎年　　代　1981<br />
	◎地　　区　中国香港<br />
	◎类　　别　动作/神秘<br />
	◎语　　言　英语<br />
	◎字　　幕　中文<br />
	◎文件格式　XviD + AC3<br />
	◎视频尺寸　640 x 272<br />
	◎电影整理　3E电影下载站(www.eee4.com)<br />
	◎文件大小　2CD 437M<br />
	◎片　　长　95 Min<br />
	◎导　　演　洪金宝 Sammo Hung Kam-Bo 元奎 Corey Yuen<br />
	◎主　　演　李小龙 Bruce Lee .... Billy Lo/Lee Chen-Chiang<br />
	　　　　　　Roy Chao .... Abbot<br />
	　　　　　　Roy Horan .... Lewis<br />
	　　　　　　Jang Lee Hwang .... Chin Ku<br />
	　　　　　　Hoi San Lee .... Monk Fighter<br />
	　　　　　　Casanova Wong .... Korean Fighter<br />
	　　　　　　元彪 Biao Yuen .... Billy Lo/Bobby Lo/Blue Staff Monk (uncredited)<br />
	　　　　　　Shun-Yee Yuen .... Monk (uncredited)<br />
	　　　　　　Tai Chung Kim .... Bobby Lo/Lee Chen-Kuo<br />
	　　　　　　Miranda Austin .... Angel<br />
	<br />
	◎简　　介　<br />
	<br />
	&nbsp; &nbsp; 李振强之世交秦谷突然暴毙，振强对他的死有所怀疑.于葬礼中，忽有直升机在外面强抢棺材，振强死于意外.振强胞弟李振马于佛光室中潜修武艺多年，闻兄长死讯，前向师父请求下山查明真相....</p>
<p>
	<img alt="" border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://i3.6.cn/cvbnm/70/c6/7a/b67e79e588fcbf5fe79b82bf28049eb5.jpg');" src="http://i3.6.cn/cvbnm/70/c6/7a/b67e79e588fcbf5fe79b82bf28049eb5.jpg" />&nbsp;<br />
	<br />
	<br />
	<img alt="" border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://i3.6.cn/cvbnm/af/fb/99/d7efc089c1f8148b4d923f5db438ec56.jpg');" src="http://i3.6.cn/cvbnm/af/fb/99/d7efc089c1f8148b4d923f5db438ec56.jpg" /><br />
	<img alt="" border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://i3.6.cn/cvbnm/40/4d/bf/7542268275241429f7c4f7ce6d40b316.jpg');" src="http://i3.6.cn/cvbnm/40/4d/bf/7542268275241429f7c4f7ce6d40b316.jpg" /><br />
	<img alt="" border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://i3.6.cn/cvbnm/1b/87/18/c94b19145e47fe7d7c1d67e4d9bcd484.jpg');" src="http://i3.6.cn/cvbnm/1b/87/18/c94b19145e47fe7d7c1d67e4d9bcd484.jpg" /><br />
	<img alt="" border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://i3.6.cn/cvbnm/37/c1/14/f2dd587a1affcf64a5a983112f937a46.jpg');" src="http://i3.6.cn/cvbnm/37/c1/14/f2dd587a1affcf64a5a983112f937a46.jpg" /></p>
<p>
	李小龙精彩动作大片《死亡塔》DVD中字</p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<anchor></anchor><a href="ftp://e56:e56@xl2.eee4.com:1003/[3E电影站www.eee4.com]死亡塔DVD中字CD1.rmvb" target="_blank">ftp://e56:e56@xl2.eee4.com:1003/[3E电影站www.eee4.com]死亡塔DVD中字CD1.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<anchor></anchor><a href="ftp://e56:e56@xl2.eee4.com:1003/[3E电影站www.eee4.com]死亡塔DVD中字CD2.rmvb" target="_blank">ftp://e56:e56@xl2.eee4.com:1003/[3E电影站www.eee4.com]死亡塔DVD中字CD2.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<anchor></anchor><a href="ftp://dy44:piaohua@dy44.piaohua.com:1603/飘花电影piaohua.com死亡塔BD中字1024分辨率.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:1603/飘花电影piaohua.com死亡塔BD中字1024分辨率.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1C15Z-26131.jpg{/dede:field}
