{dede:field name='keywords'}蓝精灵/蓝色小精灵BD高清迅雷下{/dede:field}
{dede:field name='description'}蓝精灵/蓝色小精灵BD高清迅雷下载、免费下载，蓝精灵/蓝色小精灵BD高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}蓝精灵/蓝色小精灵BD高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-10-03{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="/uploads/allimg/c120525/133O0462R10-1TE4.jpg" style="width: 445px; height: 635px" /></p>
<p>
	◎译　　名　蓝精灵/蓝色小精灵(台)<br />
	◎片　　名　Smurfs<br />
	◎年　　代　2011<br />
	◎国　　家　美国<br />
	◎类　　别　动画/家庭/奇幻/喜剧<br />
	◎语　　言　英语<br />
	◎字　　幕　中文<br />
	◎IMDB评分 4.2/10(1,032 votes)<br />
	◎IMDB链接 http://www.imdb.com/title/tt0472181<br />
	◎文件格式　XviD + MP3<br />
	◎视频尺寸　1024 x 576<br />
	◎文件大小　1.10G<br />
	◎片　　长　86 Mins<br />
	◎导　　演　拉加&middot;高斯内尔 Raja Gosnell<br />
	◎主　　演　安东&middot;尤金 Anton Yelchin&nbsp; &hellip;.Clumsy (voice)<br />
	　　　　　　凯蒂&middot;派瑞 Katy Perry&nbsp; &hellip;.Smurfette (voice)<br />
	　　　　　　汉克&middot;阿扎利亚 Hank Azaria&nbsp; &hellip;.Gargamel<br />
	　　　　　　乔纳森&middot;温特斯 Jonathan Winters&nbsp; &hellip;.Papa (voice)<br />
	　　　　　　艾伦&middot;卡明 Alan Cumming&nbsp; &hellip;.Gutsy (voice)<br />
	　　　　　　弗莱德&middot;阿米森 Fred Armisen&nbsp; &hellip;.Brainy (voice)<br />
	　　　　　　乔治&middot;洛佩兹 George Lopez&nbsp; &hellip;.Grouchy (voice)</p>

<p>
	◎简　　介</p>
<p>
	邪恶的格格巫突然闯进精灵村庄，受惊的蓝精灵慌失失走避，误闯神秘石洞，在奇异的蓝月亮照耀下竟然穿越结界来到纽约中央公园！一众蓝精灵人生路不熟，只好寄居在一对年轻夫妇家中，他们百厌活泼反应快，搞到屋主晕头转向又无计可施；精灵们首要的任务就是避开格格巫的追捕返回精灵村庄。到底蓝爸爸同蓝妹妹、笨笨、聪聪、厌厌以及勇勇（新角色）能否顺利返家乡呢？</p>
<p>
	<img alt="" src="/uploads/allimg/c120525/133O04629450-193462.jpg" style="width: 720px; height: 405px" /><img alt="" src="/uploads/allimg/c120525/133O04630450-20W49.jpg" style="width: 720px; height: 405px" /><img alt="" src="/uploads/allimg/c120525/133O046312P-21ST.jpg" style="width: 720px; height: 405px" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="/uploads/allimg/c120524/133N2Z4FF-102231.jpg" />&nbsp;&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy125:piaohua@dy125.piaohua.com:5038/飘花电影piaohua.com蓝精灵DVD中字.rmvb</td>
		</tr>
	</tbody>
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy125:piaohua@dy125.piaohua.com:6035/飘花电影piaohua.com蓝精灵BD中字1024高清.rmvb</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O04632110-225927.jpg{/dede:field}
