<?php
$z[0]=Array("field","虹猫蓝兔火凤凰/虹猫蓝兔之功夫",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","虹猫蓝兔火凤凰/虹猫蓝兔之功夫天音寺/虹猫蓝兔之功夫天林寺1280迅雷下载、免费下载，虹猫蓝兔火凤凰/虹猫蓝兔之功夫天音寺/虹猫蓝兔之功夫天林寺1280Gvod高清在线播放，剧情介绍等。",72,286);
$z[1][4]['name']="description";
$z[2]=Array("field","虹猫蓝兔火凤凰/虹猫蓝兔之功夫天音寺/虹猫蓝兔之功夫天林寺1280",288,386);
$z[2][4]['name']="title";
$z[3]=Array("field","",388,427);
$z[3][4]['name']="writer";
$z[4]=Array("field","",429,468);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-11-01",470,520);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",522,559);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://3e:3e@m1.3edyy.com:1383/【3E电影院www.3edyy.com】虹猫蓝兔火凤凰DVD国语.rmvb\" target=\"_blank",561,697);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MQ2094F-1O48.jpg",699,781);
$z[8][4]['name']="litpic";

?>