{dede:field name='keywords'}虹猫蓝兔火凤凰/虹猫蓝兔之功夫{/dede:field}
{dede:field name='description'}虹猫蓝兔火凤凰/虹猫蓝兔之功夫天音寺/虹猫蓝兔之功夫天林寺1280迅雷下载、免费下载，虹猫蓝兔火凤凰/虹猫蓝兔之功夫天音寺/虹猫蓝兔之功夫天林寺1280Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}虹猫蓝兔火凤凰/虹猫蓝兔之功夫天音寺/虹猫蓝兔之功夫天林寺1280{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-11-01{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://3e:3e@m1.3edyy.com:1383/【3E电影院www.3edyy.com】虹猫蓝兔火凤凰DVD国语.rmvb" target="_blank{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MQ2094F-1O48.jpg{/dede:field}
