<?php
$z[0]=Array("field","破茧威龙/监狱风云[DVD中字]迅雷",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","破茧威龙/监狱风云[DVD中字]迅雷下载、免费下载，破茧威龙/监狱风云[DVD中字]Gvod高清在线播放，剧情介绍等。",73,219);
$z[1][4]['name']="description";
$z[2]=Array("field","破茧威龙/监狱风云[DVD中字]",221,285);
$z[2][4]['name']="title";
$z[3]=Array("field","",287,326);
$z[3][4]['name']="writer";
$z[4]=Array("field","",328,367);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-04-20",369,419);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",421,458);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://6e:6e@d8.3edyy.com:133/【3E电影院www.eee4.cc】破茧威龙CD1.rmvb\" target=_blank>ftftp://6e:6e@d8.3edyy.com:133/【3E电影院www.eee4.cc】破茧威龙CD1.rmvb</A></TD></TR></TBODY></TABLE>CD2：<BR>\r\n<TABLE style=\"BORDER-RIGHT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; BORDER-BOTTOM: #cccccc 1px dotted\" cellSpacing=0 cellPadding=6 width=\"95%\" align=center border=0>\r\n<TBODY>\r\n<TR>\r\n<TD style=\"WORD-WRAP: break-word\" bgColor=#fdfddf><A href=\"ftftp://6e:6e@d8.3edyy.com:133/【3E电影院www.eee4.cc】破茧威龙CD2.rmvb\" target=_blank>ftftp://6e:6e@d8.3edyy.com:133/【3E电影院www.eee4.cc】破茧威龙CD2.rmvb</A></TD></TR></TBODY></TABLE></div><ul class=\"mmlist",460,1210);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MQ342020-31F7.jpg",1212,1295);
$z[8][4]['name']="litpic";

?>