<?php
$z[0]=Array("field","s.h.e-触电迅雷下载，免费下载，",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","s.h.e-触电迅雷下载、免费下载，s.h.e-触电Gvod高清在线播放，剧情介绍等。",73,187);
$z[1][4]['name']="description";
$z[2]=Array("field","s.h.e-触电",189,237);
$z[2][4]['name']="title";
$z[3]=Array("field","",239,278);
$z[3][4]['name']="writer";
$z[4]=Array("field","",280,319);
$z[4][4]['name']="source";
$z[5]=Array("field","2006-09-14",321,371);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p><embed name=\"MediaPlayer\" pluginspage=\"http://www.microsoft.com/isapi/redir.dll?prd=windows&amp;sbp=mediaplayer&amp;ar=media&amp;sba=plugin&amp;\" align=\"6\" src=\"http://fmtv.uying.com/200607/0706/s.h.e-触电.wmv\" width=\"350\" height=\"300\" type=\"application/x-mplayer2\" defaultframe=\"datawindow\" invokeurls=\"1\" clicktoplay=\"0\" enablecontextmenu=\"1\" allowscan=\"1\" transparentatstart=\"0\" animationatstart=\"0\" autorewind=\"0\" autostart=\"1\" showcaptioning=\"0\" showgotobar=\"0\" autosize=\"0\" showstatusbar=\"1\" showdisplay=\"0\" showtracker=\"1\" showaudiocontrols=\"1\" showpositioncontrols=\"0\" showcontrols=\"1\" border=\"0\"></embed>&nbsp;</p>\r\n<p>http://fmtv.uying.com/200607/0706/s.h.e-触电.wmv</p>",373,1093);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c120524/133N353DD0-2G248.gif",1095,1178);
$z[7][4]['name']="litpic";

?>