{dede:field name='keywords'}谎言之躯/叛谍同谋/谎言对决BD中{/dede:field}
{dede:field name='description'}谎言之躯/叛谍同谋/谎言对决BD中英双字1024/1280高清迅雷下载、免费下载，谎言之躯/叛谍同谋/谎言对决BD中英双字1024/1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}谎言之躯/叛谍同谋/谎言对决BD中英双字1024/1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-10-31{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://e60:e60@xl2.eee4.com:9306/[3E电影站www.eee4.com]谎言之躯BD中英双字1024x556高清版.rmvb" target="_blank{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MP261T0-2S93.jpg{/dede:field}
