<?php
$z[0]=Array("field","侠盗罗宾汉/侠盗王子罗宾汉[DVD",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","侠盗罗宾汉/侠盗王子罗宾汉[DVD中英双字1024x/1280高清版]迅雷下载、免费下载，侠盗罗宾汉/侠盗王子罗宾汉[DVD中英双字1024x/1280高清版]Gvod高清在线播放，剧情介绍等。",72,274);
$z[1][4]['name']="description";
$z[2]=Array("field","侠盗罗宾汉/侠盗王子罗宾汉[DVD中英双字1024x/1280高清版]",276,368);
$z[2][4]['name']="title";
$z[3]=Array("field","",370,409);
$z[3][4]['name']="writer";
$z[4]=Array("field","",411,450);
$z[4][4]['name']="source";
$z[5]=Array("field","2012-04-02",452,502);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",504,541);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://e7:e7@xl2.eee4.com:507/[3E电影站www.eee4.com]侠盗罗宾汉DVD中英双字1024x576高清版.rmvb\" target=\"_blank",543,689);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MO530K0-31252.jpg",691,774);
$z[8][4]['name']="litpic";

?>