{dede:field name='keywords'}1408幻影凶间/第1408号房间BD中{/dede:field}
{dede:field name='description'}1408幻影凶间/第1408号房间BD中英双字1024高清迅雷下载、免费下载，1408幻影凶间/第1408号房间BD中英双字1024高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}1408幻影凶间/第1408号房间BD中英双字1024高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-17{/dede:field}
{dede:field name='body'}<p>
	&nbsp;<img alt="" src="http://apollo.s.dpool.sina.com.cn/nd/dataent/moviepic/pics/168/moviepic_b20b3083ed319747b81c320e055f83de.jpg" /></p>
<p>
	【译　　名】《1408幻影凶间/第1408号房间》美国07顶级制作票房恐怖惊悚大片DVD中英字幕<br />
	【片　　名】1408<br />
	【年　　代】2007<br />
	【国　　家】美国<br />
	【类　　别】恐怖/惊悚<br />
	【语　　言】英语<br />
	【字　　幕】中英字幕<br />
	【视频尺寸】800 x 336<br />
	【电影来源】3E迅雷电影站(www.eee4.com)<br />
	【文件大小】2CD / 593M<br />
	【片　　长】01:52:23<br />
	【导　　演】米凯尔&middot;哈佛斯特朗姆 Mikael Hafstrom<br />
	【主　　演】约翰&middot;库萨克 John Cusack .....Mike Enslin<br />
	　　　　　　塞缪尔&middot;杰克逊 Samuel L. Jackson .....Mr. Olin<br />
	　　　　　　Mary McCormack .....Lilly<br />
	　　　　　　Andrew Lee Potts .....Jackson/mailbox guy<br />
	　　　　　　Kim Thomson .....Mrs. Palmer<br />
	　　　　　　Len Cariou .....Father<br />
	　　　　　　Jasmine Jessica Anthony .....Gracie<br />
	　　　　　　Drew Powell .....Assistant Hotel Manager/Builder<br />
	　　　　　　Peter Conboy .....Couple coming out of Dolphin Hotel</p>
<p>
	【剧情简介】：</p>
<p>
	　　他不相信，不相信这个世界上有鬼，不相信人死后会有灵魂，不相信上帝&hellip;&hellip;他只相信自己双眼看到的一切，眼见为实，眼睛是鉴别真伪的最有力武器。他是恐怖小说家迈克&middot;安瑟林，在文学界积累的名气则来自于他的作品中对一系列恐怖事件客观而中肯的剖析与见解。电影来源：www.eee4.com</p>
<p>
	　　最近小说界流行着这样一个约定俗成的风向标：只要这本小说是对一个闹鬼的房间或墓地进行不负责任的胡说八道，肯定畅销，因为这种超出正常范围的灵异事件，往往能够满足读者永无止境的猎奇心理。电影来源：www.eee4.com</p>
<p>
	　　迈克最近也在忙叨着一本这种类型的恐怖小说，然而苦于没有供参考的实例，迈克总感觉自己的故事中缺乏相应的灵魂。所以在惊闻发生在纽约海豚酒店的闹鬼事件之后，迈克迅速收拾行囊，登记入住到酒店里，不顾大堂经理奥林先生的警告，硬是住进了那间据说被鬼魂霸占了的1408室，成了这个房间许多年来的第一位客人&hellip;&hellip;其实迈克心里自有他的如意算盘，根据以往的经验，他认为房间的闹鬼事件是经理伙同员工共同捏造出来的假消息，目的很简单，想通过这种方法吸引更多的客人慕名前来，他决定借助发生在这个房间的事件为自己小说结尾的一章提供素材，同时还可以揭发海豚酒店的卑鄙行为，让他们功亏一篑。然而这一次，迈克却彻底地想错了，住在1408室的几个晚上成了他一辈子都挥之不去的梦魇，让他从一个无神论者变成了彻头彻尾的信徒，每一个晚上他都在与恶魔不停地缠斗--对于迈克来说，现在最重要的不是创作出一部畅销小说，而是如何活命。电影来源：www.eee4.com</p>
<p>
	<br />
	<br />
	&nbsp;</p>
<p>
	【电影截图】：<br />
	电影来源：www.eee4.com<br />
	<img src="http://i3.6.cn/cvbnm/88/5e/f5/6ae588a59a34d24cdc09d2006646cdb9.jpg" />&nbsp;<br />
	<img src="http://i3.6.cn/cvbnm/14/d5/bd/1de89e4f35222b2e2915dc87352a4432.jpg" />&nbsp;<br />
	<img src="http://i3.6.cn/cvbnm/cd/82/4c/71437a621d8611c37eace4baf0dd9a82.jpg" /><br />
	<br />
	美国07顶级制作票房恐怖惊悚大片《1048幻影凶间》DVD中英字幕 － 来自[3E迅雷电影站eee4.com]下载地址：<img border="0" src="http://www.eee4.com/templets/img/down.jpg" /><br />
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<anchor></anchor><a href="ftp://eee4.com:eee4@xl3.eee4.com:8448/1408幻影凶间/[3E迅雷电影站www.eee4.com]1408幻影凶间CD1.rmvb" target="_blank">ftp://eee4.com:eee4@xl3.eee4.com:8448/1408幻影凶间/[3E迅雷电影站www.eee4.com]1408幻影凶间CD1.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<anchor></anchor><a href="ftp://eee4.com:eee4@xl3.eee4.com:8448/1408幻影凶间/[3E迅雷电影站www.eee4.com]1408幻影凶间CD2.rmvb" target="_blank">ftp://eee4.com:eee4@xl3.eee4.com:8448/1408幻影凶间/[3E迅雷电影站www.eee4.com]1408幻影凶间CD2.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<anchor></anchor><a href="ftp://dy44:piaohua@dy44.piaohua.com:3441/飘花电影piaohua.com第1408号房间BD中英双字1024高清.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3441/飘花电影piaohua.com第1408号房间BD中英双字1024高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1643G0-1ZZ.jpg{/dede:field}
