{dede:field name='keywords'}阿黛尔皇家艾伯特大厅演唱会BD中{/dede:field}
{dede:field name='description'}阿黛尔皇家艾伯特大厅演唱会BD中字1280高清迅雷下载、免费下载，阿黛尔皇家艾伯特大厅演唱会BD中字1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}阿黛尔皇家艾伯特大厅演唱会BD中字1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-02-25{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="/uploads/allimg/c120524/133N4V4VF-1444b.jpg" style="width: 395px; height: 495px" /></p>
<p>
	&nbsp;&nbsp;中文片名: 阿黛尔皇家艾伯特大厅演唱会<br />
	英文片名: Adele Live At The Royal Albert Hall 2011<br />
	国家地区: 欧美<br />
	音乐类型: 演唱会<br />
	资源格式: mkv<br />
	发行时间: 2011/11/29<br />
	艺人团队: adele<br />
	对白语言: 英语<br />
	字幕语种: 简&nbsp;<br />
	&nbsp;</p>
<p>
	&nbsp;曲目:<br />
	1.Hometown Glory<br />
	2.I ll Be Waiting<br />
	3.Don t You Remember<br />
	4.Turning Tables<br />
	5.Set Fire To The Rain<br />
	6.If It Hadn t Been For Love<br />
	7.My Same<br />
	8.Take It All<br />
	9.Rumour Has It<br />
	10.Right As Rain<br />
	11.One &amp; Only<br />
	12.Lovesong<br />
	13.Chasing Pavements<br />
	14.I Can t Make You Love Me<br />
	15.Make You Feel My Love<br />
	16.Someone Like You<br />
	17.Rolling In The Deep<br />
	<br />
	<img alt="" src="/uploads/allimg/c120524/133N4V49560-15E51.jpg" style="width: 640px; height: 360px" /><img alt="" src="/uploads/allimg/c120524/133N4V501Z-1B554.jpg" style="width: 640px; height: 360px" /><img alt="" src="/uploads/allimg/c120524/133N4V50P-1L460.jpg" style="width: 640px; height: 360px" /></p>
<p>
	[下载地址]：<img border="0" src="/uploads/allimg/c120524/133N2Z4FF-102231.jpg" /></p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				ftp://dy241:xiaobajie@222.187.221.241:2045/小八戒电影xiaobajie.com阿黛尔皇家艾伯特大厅演唱会BD中字1280高清.mkv</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120524/133N4V51420-1X431.jpg{/dede:field}
