{dede:field name='keywords'}高举爱高清1024版BD国语中字2012{/dede:field}
{dede:field name='description'}高举爱高清1024版BD国语中字2012最新上映江若琳、杜汶泽爱情大片迅雷下载、免费下载，高举爱高清1024版BD国语中字2012最新上映江若琳、杜汶泽爱情大片Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}高举爱高清1024版BD国语中字2012最新上映江若琳、杜汶泽爱情大片{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-03-10{/dede:field}
{dede:field name='body'}<p>
	<img src="http://img165.poco.cn/mypoco/myphoto/20120309/18/56643687201203091805432894275616577_007.jpg" /></p>

<p>
	<img src="http://img165.poco.cn/mypoco/myphoto/20120309/18/56643687201203091805432894275616577_008.jpg" /></p>

<p>
	<img src="http://img165.poco.cn/mypoco/myphoto/20120309/18/56643687201203091805432894275616577_005.jpg" /></p>

<p>
	<img src="http://img165.poco.cn/mypoco/myphoto/20120309/18/56643687201203091805432894275616577_006.jpg" /></p>

<p>
	<img src="http://img165.poco.cn/mypoco/myphoto/20120309/18/56643687201203091805432894275616577_004.jpg" /></p>

<p>
	片名: 高举爱<br />
	导演: 邱礼涛<br />
	编剧: 邱礼涛<br />
	主演: 江若琳 / 杜汶泽 / 恬妞 / 徐正曦 / 张颂文 / 恭硕良 / 张同祖 / 小肥<br />
	类型: 剧情 / 爱情<br />
	制片国家/地区: 香港<br />
	语言: 粤语 / 汉语普通话<br />
	上映日期: 2012-03-08(中国大陆)<br />
	片长: 92分钟<br />
	又名: 高举爱情 / Love Lifting</p>
<p>
	<br />
	剧情简介</p>
<p>
	　　乐观的石勇（杜汶泽 Chapman To 饰）最近霉运连连，老婆爱钱婚姻玩完，事业受挫生意落拓，不得已带着全部家当搬到郊区，以前&ldquo;人见人爱花见花开&rdquo;的日子彻底不复返，还被老板娘（恬妞 Niu Tien 饰）等误认为落难老大。就在他失意落寞的时候，忽然发现隔壁的&ldquo;大力妹&rdquo;李丽（江若琳 Elanne kwong 饰），这个性格倔强的姑娘，本是前途无量的举重运动员，因患糖尿病黯然退役，她没有专业技能，只能做搬运工作，每天起得比鸡早干得比牛多，生活依然非常拮据。<br />
	　　两个&ldquo;苦命人&rdquo;同病相怜，一来二去就产生了感情，从此比翼双飞夫唱妇随，翌年就迎来爱情的结晶&mdash;&mdash;胖小子。但是每日忙活在柴米油盐中的李丽，仍然放不下心爱的举重事业，石勇看在眼里记在心上，暗中协调各种关系，帮助妻子完成未遂的心愿。<br />
	　　就这样，一个叱咤商场的精英男，把自己武装成&ldquo;煎炒烹炸样样通，擦抹洗刷全不误&rdquo;的家庭煮夫，支持着爱妻李丽走向举重台&hellip;&hellip;　</p>
<p>
	<br />
	<img src="http://img165.poco.cn/mypoco/myphoto/20120309/18/56643687201203091807496485181222771_000.jpg" style="width: 600px; height: 333px" /></p>
<p>
	<img src="http://img165.poco.cn/mypoco/myphoto/20120309/18/56643687201203091805432894275616577_002.jpg" style="width: 600px; height: 333px" /></p>
<p>
	<img src="http://img165.poco.cn/mypoco/myphoto/20120309/18/56643687201203091805432894275616577_000.jpg" style="width: 600px; height: 333px" /></p>
<p>
	<img src="http://img165.poco.cn/mypoco/myphoto/20120309/18/56643687201203091805432894275616577_003.jpg" style="width: 600px; height: 333px" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2984/飘花电影piaohua.com高举爱高清1024版BD国语中字.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:2984/飘花电影piaohua.com高举爱高清1024版BD国语中字.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2984/飘花电影piaohua.com高举爱高清1024版BD国语中字.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15QQ60-45451.jpg{/dede:field}
