{dede:field name='keywords'}双虎屠龙HD高清迅雷下载，免费下{/dede:field}
{dede:field name='description'}双虎屠龙HD高清迅雷下载、免费下载，双虎屠龙HD高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}双虎屠龙HD高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-11-18{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="/uploads/allimg/c120525/133O0N032P-12148.jpg" /></p>
<p>
	导演: 约翰&middot;福特<br />
	编剧: James Warner Bellah / Willis Goldbeck<br />
	主演: 约翰&middot;韦恩 / 詹姆斯&middot;斯图尔特 / 维拉&middot;迈尔斯 / 李&middot;马文 / 艾德蒙&middot;奥布莱恩<br />
	类型: 剧情 / 爱情 / 西部<br />
	制片国家/地区: 美国<br />
	语言: 英语<br />
	片长: 123 分钟 / Brazil: 124 分钟 / West Germany: 113 分钟(cut version)<br />
	上映日期: 1962-04-22<br />
	IMDb链接: http://www.imdb.com/title/tt0056217/<br />
	IMDb评分: 8.1 (27,645 votes)<br />
	<br />
	剧情简介<br />
	　　一部1962年拍摄的美国西部片。<br />
	　　 年轻律师Ransom来到美国西部小镇，结果却被恶徒Liberty Valance暴打后告知，在西部，枪才是法律。获救后，Ransom指望通过法律将Liberty Valance投入监狱，小镇的人们却不以为然。这些善良的人一样认同&rdquo;枪既法律&ldquo;的西部法则，包括时时帮助Ransom的好汉Tom在内。<br />
	　　 与此同时，Ransom教居民们读书写字，使当地报纸的平庸主编发现了新闻的价值和力量，告诉人们通过手中的选票捍卫自己的权利，带领他们顶住 Liberty的暴力威慑，投选建州从而保住土地和牧场。他的勇气和知识赢得了小镇居民的尊重和喜爱，并且在角斗中由于Tom的暗中相助射死了 Liberty，最终成为建州后的首任州长，后任参议员，有望当选副总统，成了西部的传奇人物。</p>
<p>
	<img alt="" src="/uploads/allimg/c120525/133O0N03A0-2E93.jpg" style="width: 720px; height: 405px" /><img alt="" src="/uploads/allimg/c120525/133O0N045Z-355b.jpg" style="width: 720px; height: 405px" /><img alt="" src="/uploads/allimg/c120525/133O0N05O0-4W91.jpg" style="width: 720px; height: 405px" /><img alt="" src="/uploads/allimg/c120525/133O0N0D30-59349.jpg" style="width: 720px; height: 405px" /><br />
	<br />
	<br />
	&nbsp;</p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="/uploads/allimg/c120525/133O05441630-1Qc7.jpg" />&nbsp;&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy125:piaohua@dy125.piaohua.com:7190/飘花电影piaohua.com双虎屠龙HD中字1280高清.rmvb</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O0N0N60-62247.jpg{/dede:field}
