{dede:field name='keywords'}星际传奇2/漆黑一片2/超世纪战警{/dede:field}
{dede:field name='description'}星际传奇2/漆黑一片2/超世纪战警BD中英双字1024高清迅雷下载、免费下载，星际传奇2/漆黑一片2/超世纪战警BD中英双字1024高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}星际传奇2/漆黑一片2/超世纪战警BD中英双字1024高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-23{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://eee4.com:eee4@xl2.eee4.com:8801/[3E迅雷电影站www.eee4.com]星际传奇2[DVD中英双字]CD1.rmvb" target="_blank{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MO922J0-55542.jpg{/dede:field}
