{dede:field name='keywords'}绝世天劫[HD中英双字1024x576＋1{/dede:field}
{dede:field name='description'}绝世天劫[HD中英双字1024x576＋1280x720高清版]迅雷下载、免费下载，绝世天劫[HD中英双字1024x576＋1280x720高清版]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}绝世天劫[HD中英双字1024x576＋1280x720高清版]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-03-17{/dede:field}
{dede:field name='body'}<p>
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://images.dvdempire.com/gen/movies/3700h.jpg');" src="http://images.dvdempire.com/gen/movies/3700h.jpg" /><br />
	<br />
	◎译　　名　绝世天劫/世界末日/最后决战/大决战<br />
	◎片　　名　Armageddon<br />
	◎年　　代　1998<br />
	◎国　　家　美国<br />
	◎类　　别　动作/剧情/爱情/科幻/惊悚<br />
	◎语　　言　英语<br />
	◎字　　幕　中英双字<br />
	◎IMDB评分 5.7/10 (57,741 votes)<br />
	◎文件格式　HDTV-RMVB<br />
	◎视频尺寸　1024 x 576＋1280x720<br />
	◎文件大小　1CD<br />
	◎片　　长　02:30:54<br />
	◎导　　演　迈克尔&middot;贝 Michael Bay<br />
	◎主　　演　查尔顿&middot;赫斯顿 Charlton Heston .... Narrator (voice)<br />
	　　　　　　斯蒂夫&middot;巴斯米 Steve Buscemi .... Rockhound<br />
	　　　　　　丽芙&middot;泰勒 Liv Tyler .... Grace Stamper<br />
	　　　　　　布鲁斯&middot;威利斯 Bruce Willis .... Harry S. Stamper<br />
	　　　　　　本&middot;阿弗莱克 Ben Affleck .... A.J. Frost<br />
	　　　　　　比利&middot;鲍伯&middot;汤顿 Billy Bob Thornton .... Dan Truman, NASA Administrator<br />
	　　　　　　迈克尔&middot;贝 Michael Bay .... NASA Scientist (uncredited)<br />
	　　　　　　Bodhi Elfman .... Math Guy<br />
	　　　　　　威廉&middot;菲德内尔 William Fichtner .... Colonel William Sharp, Shuttle Freedom Pilot<br />
	　　　　　　尤杜&middot;奇尔 Udo Kier .... Psychologis<br />
	　　　　　　威尔&middot;帕顿 Will Patton .... Charles &#39;Chick&#39; Chapple<br />
	　　　　　　皮特&middot;施特曼 Peter Stormare .... Lev Andropov, Russian Cosmonaut<br />
	　　　　　　迈克尔&middot;克拉克&middot;邓肯 Michael Clarke Duncan .... Jayotis &#39;Bear&#39; Kurleenbear<br />
	　　　　　　Andy Ryan .... Greenpeace Guy<br />
	　　　　　　詹森&middot;艾萨克 Jason Isaacs .... Dr. Ronald Quincy, Research<br />
	<br />
	◎简　　介　<br />
	<br />
	　　美国太空总署发现一颗巨大的陨石正朝地球方向而来，并将在18天之内撞上地球，为了阻止陨石造成人类的毁灭，太空总署想出的方法是派人登陆陨石的表面，并钻洞贯穿至陨石的地心，放入核弹引爆，使之在撞上地球前就先在太空中毁灭，而布鲁斯威利斯饰演的就是身负此重任的钻油井工人的工头，而本艾弗列克不但是他的属下，同时也是布鲁斯威利斯女儿（丽芙.泰勒饰演）的男朋友 ，为了完成此项训练，两人同时接受太空总署的训练，一夕之间从一个打井工人成为太空人及救世英雄。<br />
	<br />
	地球曾一度是恐龙的栖身之地，但一块直径为六千公尺的天外巨石改变了一切，它造成了地球的大爆炸和恐龙的灭绝。这事以前已曾发生，现在或将来也许还会发生。<br />
	<br />
	　 休斯敦。美国太空总署的所有人员穿梭忙碌着，刚发生的意外令每一个人坐立不安：太空空间站突然之间被摧毁，与地面失去了一切联系。工作人员紧张焦急地检查着各种仪器，其中一人指着雷达显示屏惊呼起来：&ldquo;有一大群不明物体向纽约飞去了；&rdquo;纽约市繁华而忙碌。<br />
	<br />
	　 一个黑人小伙儿用单车载着小狗兜风。小狗见到一些出售的恐龙玩具，立即跳过去又撕又咬。卖玩具的胖老板抓起玩具向小狗打去。黑小伙儿见宠物被打，忿忿他说：&ldquo;你敢再打它，我就炸死你！&rdquo;话音未落，一个火球从天而降，正好落在胖老板头上炸开。黑小伙儿也被冲击波掀起挂在大树上，他惊惶地哭喊道：&ldquo;有炸弹，快报警！&rdquo;越来越多的火球向纽约飞来，市区街面上顷刻间成为一片火海。人们四处逃窜，有人惊叫：&ldquo;我们遭空袭了！&rdquo;<br />
	<br />
	　 休斯敦太空总署很快得出了结论，这是一场大规模的陨石雨，破坏力极大。众人一筹莫展，而太空望远镜传回的最新照片更是让人瞠目结舌：一颗直径有德州大小的陨石正向地球飞来，18天后将撞击地球。<br />
	<br />
	　 太空总署负责人卡尔心情沉重他说道：&ldquo;陨石雨只是前奏而已。&rdquo;科学家们紧急磋商，寻求解决办法。卡尔最后总结说：&ldquo;我们只有18无时间，要么是它毁灭我们，要么是我们毁掉它。现在唯一的办法，就是让飞船在陨石上着陆，并让专业人员在陨石上钻一个800米深的洞，放入核弹，炸碎它或是改变它的飞行轨道。<br />
	<br />
	　 现在，当务之急是去找最好的石油钻探工人广哈里在油田工地上忙碌着。他既是油田老板，也是最有经验的钻探师。此刻，钻井最忙碌<a href="http://www.3edyy.com/" target="_blank">电影下载</a>的时分，他手下最得力的青年工人艾吉却不见踪影。哈里急步奔到艾吉的小屋前，推门而入，正见艾吉手忙脚乱地穿衣服：再一看，自己的宝贝女儿丽丝竟然躺在艾吉的床上。哈里怒火中烧，拔出手枪向艾吉射击。艾吉一边躲闪一边高喊：&ldquo;我是真心爱她1&rdquo;丽丝也跑出来向父亲央求：&ldquo;我已经长大了，我爱他，我要嫁给他!&quot;哈里气冲冲地说：&ldquo;不可能我绝不会允许你们&hellip;&hellip;&rdquo;正在这时，几架直升机落在油田平台上。几个军人跑到哈里面前，礼貌他说：&ldquo;哈里先生，为了国家的安全，请立刻跟我们走。请允许我们暂时不讲明理由。&rdquo;<br />
	<br />
	<br />
	　&nbsp; 哈里满腹狐疑地跟他们上了直升机。太空总署里，卡尔早已等候多时，一见哈里，他就和盘托出了陨石飞向地球的情况。他忧心忡忡他说：&ldquo;陨石与地球一旦相撞，世界各国和地球万物将遭受毁灭性的打击，连细菌也不能幸免。就算陨石落入人海中，掀起的滔大巨浪也足以吞没大半个世界，人类也会因撞击所产生的高温而死去。无论怎样，后果都是一 样。&rdquo;<br />
	<br />
	　 两艘飞船顺利进入太中，在俄罗斯空间站补充了燃料和水，两位俄罗斯宇航员也加入了拯救地球人类的行列。两艘飞船向既定的目标飞去。<br />
	<br />
	　 巨大的陨石像一头张牙舞瓜的怪兽，在太空中翻滚移动，缓缓<a href="http://www.eee4.cc/" target="_blank">3E电影院</a>逼近地球。两艘飞船盘旋着向陨石靠拢，无数的小陨石肌点股向飞船袭来。飞船不断地躲闪，不断地靠近、不敢抬头。风暴过后，他们发现了一件令人丧气的事：引爆核弹的遥控器失灵了。要完成任务，唯一的办法是留下一人，用手摁下引爆装置按钮。留谁?有人提议抽签。留下的那根签被艾吉抽到了，他自嘲道：&ldquo;想不到我成了拯球地球的英雄。&rdquo;他又转身对哈里说：&ldquo;告诉丽丝，我永远爱她。&quot;艾吉拉开舱门。走下飞船。<br />
	<br />
	　 就在飞船即将飞离陨石的一瞬间，哈里猛地拉开舱门跳了出去，并一把将艾吉推入飞船，从外面关严了舱门，他隔着舱门对艾吉说：&ldquo;我&middot;直把你当作儿子看待。替我照顾好丽丝。&rdquo;<br />
	<br />
	　 飞船远远地飞离了陨石。哈里通过卫星通讯系统与女儿永诀，他含泪说：&ldquo;我答应你说一定会回来，但我夫信了。好好照顾艾吉。我永远在你们身边。&rdquo;他最后深情地望了一眼地球的方向，仿佛看到春色中童年的丽丝正张着双臂向自己奔来&hellip;&hellip;<br />
	<br />
	　 哈里掘下了引爆按钮。全世界的人们都看到天空中出现了一道奇丽的光环，随即陨石被炸成两段，改变了飞行轨道，与地球搽肩而过。<br />
	<br />
	　 天空中从此多了一颗永远闪光的新星。<br />
	<br />
	影片幕后：<br />
	<br />
	　　《Armageddon》讲述了一个美国英雄式的科幻故事。两架航天飞机同时起飞蔚为壮观。电影的音乐是我所津津乐道的&mdash;&mdash;一曲《Leave on a jet plane》烘托了剧末的悲壮。影片宏观地概述了友情、亲情、爱情。惊人的特技效果塑造出难得的史诗感，令几乎同期上映的《彗星撞地球》相形见绌。本篇唯一的不足是较狭隘的民族主义。<br />
	　　整个故事被高度简单化和模式化，以便腾出篇幅来表现陨石碎片击中地球时的壮观爆炸场面，以及在太空钻洞之旅中安排一波三折的危机，藉以增加紧张刺激的气氛。此外，编导在大肆卖弄映射奇观之余，也不忘加入一些感人的文艺场面，并且刻意将布鲁斯．威利塑造成牺牲自己成全女儿和女婿的悲剧英雄。导演迈克尔．贝将全片泡制得相当热闹，各种娱乐元素堆砌在观众眼前，教人目不暇给，但成绩也仅止于此。</p>
<p>
	【电影截图】：<br />
	<br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://photo5.zxip.com/albums5/folder10/7895/20100301123846/2010331057391930.jpg');" src="http://photo5.zxip.com/albums5/folder10/7895/20100301123846/2010331057391930.jpg" /><br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://photo5.zxip.com/albums5/folder10/7895/20100301123846/201033105740478.jpg');" src="http://photo5.zxip.com/albums5/folder10/7895/20100301123846/201033105740478.jpg" /></p>
<br />
<p>
	[下载地址]：<img border="0" src="http://www.3edyy.com/templets/img/down.jpg" /></p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://4e:4e@m1.3edyy.com:1396/【3E电影院www.3edyy.com】绝世天劫HD中英双字1024x576高清版.rmvb" target="_blank">ftp://4e:4e@m1.3edyy.com:1396/【3E电影院www.3edyy.com】绝世天劫HD中英双字1024x576高清版.rmvb</a></td>
		</tr>
	</tbody>
</table>
<br />
<p>
	[下载地址]：<img border="0" src="/templets/img/down.jpg" /></p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://5e:5e@d8.3edyy.com:157/【3E电影院www.eee4.cc】绝世天劫BD中英双字1280x720高清版.rmvb" target="_blank">ftp://5e:5e@d8.3edyy.com:157/【3E电影院www.eee4.cc】绝世天劫BD中英双字1280x720高清版.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O14bY20-4XL.jpg{/dede:field}
