<?php
$z[0]=Array("field","黑客帝国3：矩阵革命/最后战役/",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","黑客帝国3：矩阵革命/最后战役/帝国革命BD中英双字1024/1280高清迅雷下载、免费下载，黑客帝国3：矩阵革命/最后战役/帝国革命BD中英双字1024/1280高清Gvod高清在线播放，剧情介绍等。",72,286);
$z[1][4]['name']="description";
$z[2]=Array("field","黑客帝国3：矩阵革命/最后战役/帝国革命BD中英双字1024/1280高清",288,386);
$z[2][4]['name']="title";
$z[3]=Array("field","",388,427);
$z[3][4]['name']="writer";
$z[4]=Array("field","",429,468);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-11-01",470,520);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",522,559);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://e24:e24@xl2.eee4.com:1003/[3E电影站www.eee4.com]黑客帝国3[DVD中英双字1024x554版]CD1.rmvb\" target=\"_blank",561,710);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MO9625Z-3W48.jpg",712,794);
$z[8][4]['name']="litpic";

?>