<?php
$z[0]=Array("field","苔藓/青苔[BD中字1024x576高清版",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","苔藓/青苔[BD中字1024x576高清版]迅雷下载、免费下载，苔藓/青苔[BD中字1024x576高清版]Gvod高清在线播放，剧情介绍等。",73,229);
$z[1][4]['name']="description";
$z[2]=Array("field","苔藓/青苔[BD中字1024x576高清版]",231,300);
$z[2][4]['name']="title";
$z[3]=Array("field","",302,341);
$z[3][4]['name']="writer";
$z[4]=Array("field","",343,382);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-01-02",384,434);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",436,473);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://3e:3e@d3.3edyy.com:121/【3E电影院www.eee4.org】苔藓BD中字1024x576高清版.rmvb\" target=_blank>ftftp://3e:3e@d3.3edyy.com:121/【3E电影院www.eee4.org】苔藓BD中字1024x576高清版.rmvb</A></TD></TR></TBODY></TABLE></div><ul class=\"mmlist",475,749);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MP335M0-19262.jpg",751,834);
$z[8][4]['name']="litpic";

?>