{dede:field name='keywords'}邵氏经典猎人香港悬疑1969迅雷下{/dede:field}
{dede:field name='description'}邵氏经典猎人香港悬疑1969迅雷下载、免费下载，邵氏经典猎人香港悬疑1969Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}邵氏经典猎人香港悬疑1969{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-07-28{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20110728/23/62564813201107282322124064852150322_000.jpg" /></p>
<p>
	◎译　　名　Diary.Of.A.Lady.Killer<br />
	◎片　　名　猎人<br />
	◎年　　代　1969<br />
	◎国　　家　香港<br />
	◎类　　别　悬疑<br />
	◎语　　言　国语<br />
	◎字　　幕　简体中文<br />
	◎IMDB评分　awaiting 5 votes<br />
	◎IMDB链接　<a href="http://www.imdb.com/title/tt0445528/">http://www.imdb.com/title/tt0445528/</a><br />
	◎文件格式　XviD+AC3<br />
	◎视频尺寸　672&times;272<br />
	◎文件大小　696.6MB<br />
	◎片　　长　01:36:04<br />
	◎制作公司　邵氏兄弟【中国香港】<br />
	◎发行公司　天映娱乐【中国香港】2003 worldwide DVD<br />
	◎上映日期　1969年5月9日<br />
	◎导　　演　杨树希 Ko Nakahira....as Yeung Shu Hei<br />
	◎编　　剧　杨树希 Ko Nakahira<br />
	◎主　　演　金汉 Han Chin....as Hon Kam<br />
	　　　　　　方盈 Ying Fang<br />
	　　　　　　范丽 Fanny Fan<br />
	　　　　　　李鹏飞 Pengfei Li<br />
	　　　　　　马海伦 Helen Ma<br />
	　　　　　　狄娜 Tina Ti<br />
	　　　　　　杜娟 Margaret Tu Chuan<br />
	　　　　　　方逸华 Mona Fong<br />
	　　　　　　郑文静 Wen Ching Cheng<br />
	　　　　　　朱今 Chin Chu<br />
	　　　　　　吕红 Hung Lu<br />
	　　　　　　文秀 Wen-Hsiu<br />
	　　　　　　李笑丛 Hsiao Chung Li<br />
	　　　　　　尔群 Yi Chun<br />
	　　　　　　黄莎莉 Shali Huang<br />
	　　　　　　吴风 Fung Ng<br />
	　　　　　　夏仪秋 Yee Chau Ha</p>
<p>
	◎简　　介</p>
<p>
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 一男子与女下属有染，后因多名情人被杀而成嫌疑犯，唯一一本猎人日记，却成脱罪证物&hellip;&hellip;<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 你很难想像这是1969年的片子，略带点现代气息的一起栽赃报复案！金汉饰演汽车行的总经理，有钱，有地位，的确还是有点小帅，Lady Killer！呵呵！把玩过的女人以及经过写在日记里头，取名猎人日记！很有趣嘛！嘿嘿！可以看看！</p>
<p>
	◎截　　图</p>
<p>
	<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20110728/23/62564813201107282322124064852150322_003.jpg" style="width: 672px; height: 272px" /><img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20110728/23/62564813201107282322124064852150322_002.jpg" /><img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20110728/23/62564813201107282322124064852150322_001.jpg" /></p>

<p>
	[猎人]下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="&#13;&#10;ftp://dy195:piaohua@dy195.piaohua.com:1000/飘花电影下载站www.xiaozhizhu.net猎人[国语中字].rmvb">ftp://dy195:piaohua@dy195.piaohua.com:1000/飘花电影下载站www.xiaozhizhu.net猎人[国语中字].rmvb </a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1BUN0-23K1.jpg{/dede:field}
