{dede:field name='keywords'}机器人总动员/瓦力[BD中英双字10{/dede:field}
{dede:field name='description'}机器人总动员/瓦力[BD中英双字1024/1280高清版]迅雷下载、免费下载，机器人总动员/瓦力[BD中英双字1024/1280高清版]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}机器人总动员/瓦力[BD中英双字1024/1280高清版]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-09-18{/dede:field}
{dede:field name='body'}<p>
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('/uploads/allimg/c120525/133O04B9240-53X1.jpg');" src="/uploads/allimg/c120525/133O04B9240-53X1.jpg" /></p>
<p>
	◎译　　名　《机器人总动员/大空奇兵&middot;威E/瓦力》高分大片BD中英双字1024x554高清版<br />
	◎片　　名　Wall-E<br />
	◎年　　代　2008<br />
	◎国　　家　美国<br />
	◎类　　别　动画/喜剧/爱情/科幻/冒险/家庭<br />
	◎语　　言　英语<br />
	◎字　　幕　中英双字<br />
	◎IMDB评分 8.7/10 (81,848 votes) Top 250: #32<br />
	◎IMDB链接 http://www.imdb.com/title/tt0910970<br />
	◎文件格式　BD-RMVB<br />
	◎视频尺寸　1024 x 556<br />
	◎文件大小　2CD<br />
	◎片　　长　98 Mins<br />
	<br />
	Domestic:&nbsp; $223,003,468&nbsp; &nbsp; 46.0%<br />
	+ Foreign:&nbsp; $262,000,000&nbsp; &nbsp; 54.0%<br />
	--------------------------------------------------------------------------------<br />
	= Worldwide:&nbsp; $485,003,468&nbsp;<br />
	<br />
	◎导　　演　安德鲁&middot;斯坦顿 Andrew Stanton<br />
	◎主　　演　本&middot;贝尔特 Ben Burtt ....(voice)<br />
	　　　　　　艾丽莎&middot;奈特 Elissa Knight ....Eve<br />
	　　　　　　佛莱德&middot;威拉特 Fred Willard ....Shelby Forthright<br />
	　　　　　　杰夫&middot;格尔林 Jeff Garlin ....Captain (voice)<br />
	　　　　　　John Ratzenberger ....John (voice)<br />
	　　　　　　Kathy Najimy ....Mary (voice)<br />
	　　　　　　西格妮&middot;韦弗 Sigourney Weaver ....Ship&#39;s Computer (voice)<br />
	　　　　　　MacInTalk ....AUTO (voice)<br />
	<br />
	◎简　　介　<br />
	<br />
	　《WALL-E》是《海底总动员》（Finding Nemo）导演安德鲁&middot;斯坦顿（Andrew Stanton）执导的第二部动画片，计划于2008年6月27日上映。<br />
	<br />
	　　影片故事发生在2700年，由于人类无度的破坏环境，地球此时已经成为漂浮在太空中的一个大垃圾球，人类不得已移居到太空船上，并且聘请Buynlarge公司清除地球上的垃圾，等待着有一天垃圾清理完重新回到地球上。<br />
	<br />
	　　于是Buynlarge公司向地球运送了大量机器人来捡垃圾，但是这种机器人并不适合地球的环境，渐渐的都坏掉了，最后只剩下一个机器人还在日复一日的按照预定程序捡垃圾。显然这是个不可能完成的任务。就这么过了几百年，机器人收集了不少人造的物品，其中最让它喜欢的是一盒录像带&mdash;&mdash;芭芭拉&middot;史翠珊主演的歌舞片《你好，多莉！》（Hello, Dolly !）！<br />
	<br />
	　　随着时间的流逝，这个孤独的机器人开始有了自我意识，它渴望有人来陪陪它。有一天一艘飞船差点落在它头顶，一个漂亮的女机器人Eve来到地球负责搜索一些东西，捡垃圾的机器人&ldquo;爱&rdquo;上了Eve，但是它面临着抉择，是随着Eve和飞船离开地球，还是继续按照预设的指令把垃圾捡下去。当然它最后选择和Eve一起离开，飞向太空，不过好戏才刚刚开始&hellip;&hellip;<br />
	<br />
	　　影片片名&ldquo;WALL-E&rdquo;是一个缩写，全称为&ldquo;Waste Allocation Load Lifters - Earth&rdquo;，就是Buynlarge公司派往地球捡垃圾的那些机器人的官方称呼。另外这部影片中还会出现真人演员佛莱德&middot;威拉德（Fred Willard），他将扮演Buynlarge公司总裁，在动画片中出现真人，这在皮克斯也是首次。</p>

<p>
	<img onclick="if(this.width&gt;screen.width-461) window.open('/uploads/allimg/c120525/133O04C0020-AT9.jpg');" src="/uploads/allimg/c120525/133O04C0020-AT9.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 325px; border-top: 0px solid; border-right: 0px solid" /></p>
<p>
	&nbsp;<img onclick="if(this.width&gt;screen.width-461) window.open('/uploads/allimg/c120525/133O04C0420-Ka6.jpg');" src="/uploads/allimg/c120525/133O04C0420-Ka6.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 325px; border-top: 0px solid; border-right: 0px solid" /></p>
<p>
	高分大片《机器人总动员》BD中英双字1024x554高清版</p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				</anchor>ftp://d21:d21@xl2.eee4.com:1105/[3E电影站www.eee4.com]机器人总动员[DVD中英双字1024x554高清版]CD1.rmvb</td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				</anchor>ftp://d21:d21@xl2.eee4.com:1105/[3E电影站www.eee4.com]机器人总动员[DVD中英双字1024x554高清版]CD2.rmvb</td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#ooffff" style="word-wrap: break-word">
				</anchor><u>ftp://dy44:piaohua@dy44.piaohua.com:1591/飘花电影piaohua.com机器人总动员BD中英双字1280高清.rmvb</u></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O04C0Y0-Ya7.jpg{/dede:field}
