{dede:field name='keywords'}仙女/爱上仙女的男人DVD中英双字{/dede:field}
{dede:field name='description'}仙女/爱上仙女的男人DVD中英双字2011爱情奇幻迅雷下载、免费下载，仙女/爱上仙女的男人DVD中英双字2011爱情奇幻Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}仙女/爱上仙女的男人DVD中英双字2011爱情奇幻{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-21{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://pic.piaohua.com/0701pic/allimg/120520/1-120520214640128.jpg" /></p>
<p>
	仙女 La F&eacute;e (2011)<br />
	预告片 导演: Fiona Gordon / Dominique Abel / Bruno Romy<br />
	编剧: Fiona Gordon / Bruno Romy / Dominique Abel<br />
	主演: Dominique Abel / Fiona Gordon / Bruno Romy / Philippe Martz / Vladimir Zongo<br />
	类型: 喜剧 / 爱情 / 奇幻<br />
	制片国家/地区: 法国 / 比利时<br />
	语言: 法语<br />
	片长: 93分钟<br />
	@IBM <a href="http://www.xiaozhizhu.net/" title="最新电影">http://www.xiaozhizhu.net/</a><br />
	又名: 云端求爱记(台) / 仙女出沒请注意 / 爱上仙女的男人 / 童话 / The Fairy</p>
<p>
	剧情简介 &middot; &middot; &middot; &middot; &middot; &middot;<br />
	　　多姆是法国海边旅馆的夜班员工，整日与电视、三明治和讨厌的旅客为伍，一日来了个自称仙女的赤脚女孩费欧娜，大方送给他三个愿望，还保证一定成真。他祈求能有一台摩托车和一辈子用不尽的汽油，却想不出第三个愿望。翌日早晨，门口竟然停着闪亮的新车及盛装打扮等待约会的娇羞美人，情陷爱河的多姆开始在意起对方，却突然发现心上人失踪了，她竟被关进<a href="http://www.xiaozhizhu.net/" style="color: rgb(0,0,0); text-decoration: none">最新电影</a>当地的精神病院，把七彩药丸当零嘴吃&hellip;。为了再续前缘，多姆勇敢闯入医院，乔装胖子把她偷渡出来，可是神奇的女友却在一夜之间大肚子，产下男婴，一连串疯狂的行径和灾难，让他们成为警察关注的焦点，高潮迭起的真爱大作战如火如荼上演&hellip;&hellip;&nbsp;</p>
<p>
	<img alt="" src="http://img011.photo.21cn.com/photos/mark/20120520/o/C1464AF3637EDD75F8FFCAFBE23B41EE.jpg" /></p>
<p>
	<img alt="" src="http://img011.photo.21cn.com/photos/mark/20120520/o/00E679A1BA382AFB4F87077697B73789.jpg" /></p>
<p>
	[下载地址]： &nbsp;<img border="0" src="/0701pic/allimg/120110/01223C617-5.jpg" /></p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3466/飘花电影piaohua.com爱上仙女的男人DVD中英双字.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3466/飘花电影piaohua.com爱上仙女的男人DVD中英双字.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3466/飘花电影piaohua.com爱上仙女的男人DVD中英双字.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15W3460-3V54.jpg{/dede:field}
