{dede:field name='keywords'}辛亥革命清晰版DVD国语中字2011{/dede:field}
{dede:field name='description'}辛亥革命清晰版DVD国语中字2011最新上映成龙/赵文瑄战争历史大片迅雷下载、免费下载，辛亥革命清晰版DVD国语中字2011最新上映成龙/赵文瑄战争历史大片Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}辛亥革命清晰版DVD国语中字2011最新上映成龙/赵文瑄战争历史大片{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-10-12{/dede:field}
{dede:field name='body'}<p>
	<img src="http://img165.poco.cn/mypoco/myphoto/20110924/14/56634212201109241451272988950683232_004.jpg" /></p>
<p>
	<img src="http://img165.poco.cn/mypoco/myphoto/20110924/14/56634212201109241451272988950683232_003.jpg" /></p>
<p>
	中文名： 辛亥革命<br />
	其它译名： 1911<br />
	出品时间： 2011年<br />
	出品公司： 上海东方影视发行有限责任公司<br />
	制片地区： 中国<br />
	导演： 张黎，成龙<br />
	编剧： 王兴东，陈宝光<br />
	制片人： 汪天云，毕述林，王浙滨<br />
	主演： 赵文瑄，孙淳、成龙、姜武，黄志忠，李冰冰<br />
	类型： 历史，战争，剧情<br />
	上映时间： 2011年9月23日<br />
	海外发行： 北京耀莱国际文化产业有限公司<br />
	语言： 汉语普通话</p>
<p>
	<br />
	剧情简介</p>
<p>
	　　晚清末年，内忧外患，中华民族到了危亡之际。改良派维新变法运动的失败，孙中山为首的革命派，决心以革命推翻清政府，建立共和体制。<br />
	　　1895到1910年，革命党人先后发动了多次起义，秋瑾、徐锡麟等一批革命党先驱先后牺牲，革命陷入低潮。<br />
	　　1910年底，孙中山再次在海外召集同盟会骨干，组织力量准在广州发动起义黄兴与徐宗汉假扮夫妇，秘密潜入广州。然而广州之战终因革命党人寡不敌众而告负，林觉民等一大批革命骨干壮烈牺牲，黄兴也身负重伤。徐宗瀚等冒死收葬了烈士遗体72具，葬于广州城外的黄花岗。<br />
	　　经过这次的起义，清政府对革命党人进行了血腥镇压，同时积极寻求与帝国主义的卖国交易。<br />
	　　在四川，清廷又一次丧权辱国的行为，引发了轰轰烈烈的保路运动，湖北新军被紧急抽调前去镇压。在武昌，新军当中的革命党名单泄漏，湖广总督瑞澂开始对名单上的革命党人逐一捕杀，革命形势十分危急，革命党人熊... (展开全部) 　　晚清末年，内忧外患，中华民族到了危亡之际。改良派维新变法运动的失败，孙中山为首的革命派，决心以革命推翻清政府，建立共和体制。<br />
	　　1895到1910年，革命党人先后发动了多次起义，秋瑾、徐锡麟等一批革命党先驱先后牺牲，革命陷入低潮。<br />
	　　1910年底，孙中山再次在海外召集同盟会骨干，组织力量准在广州发动起义黄兴与徐宗汉假扮夫妇，秘密潜入广州。然而广州之战终因革命党人寡不敌众而告负，林觉民等一大批革命骨干壮烈牺牲，黄兴也身负重伤。徐宗瀚等冒死收葬了烈士遗体72具，葬于广州城外的黄花岗。<br />
	　　经过这次的起义，清政府对革命党人进行了血腥镇压，同时积极寻求与帝国主义的卖国交易。<br />
	　　在四川，清廷又一次丧权辱国的行为，引发了轰轰烈烈的保路运动，湖北新军被紧急抽调前去镇压。在武昌，新军当中的革命党名单泄漏，湖广总督瑞澂开始对名单上的革命党人逐一捕杀，革命形势十分危急，革命党人熊秉坤、金兆龙等愤然打响了革命第一枪。经过一夜激战，武昌起义的革命军攻占了总督府，黎元洪被革命军将士紧急推为军政府都督。<br />
	　　武昌起义成功，举国震惊，消息传到美国，孙中山和同盟会成员欢欣鼓舞。立即派黄兴和徐宗汉赶到武昌战场，大大振奋了革命军士气。不惜以热血和生命保卫飘扬着革命红旗的武汉三镇。经过这么多血与火的洗礼，黄兴和徐宗汉的感情不断升华，两人决定结为革命夫妻继续比肩战斗。<br />
	　　风雨飘渺的清廷只好请袁世凯出山，率北洋军镇压革命。袁世凯一方面镇压革命军，另一方面仍试图在各方势力的博弈中，暗地里通过革命党人汪精卫传达与革命党和谈的愿望。<br />
	　　革命的危急关头，孙中山奔赴海外，力排众议，最终说服西方列国财团，不再借贷款支持清廷。<br />
	　　阳夏保卫战打得异常惨烈，黄兴和黎元洪艰难支撑，在各种反动势力的夹击下，黄兴毅然决定率部撤往长江下游，集聚力量，以图大业。<br />
	　　长江战舰在行进中，传来了多省宣布独立的消息，黄兴等备受鼓舞。<br />
	　　自此，革命形势进入了南北对峙的局面，经过多方努力，南北代表唐绍仪和伍廷芳终于坐下来会谈，经过艰难谈判，双方达成共识，支持建立共和政体；经过十八省代表的公开民主选举，孙中山被推选为首任大总统。孙中山表示，只要袁世凯敦促清帝退位，他即可让位，由逼退清让位的人，出任中华民国大总统。<br />
	　　辛亥革命，中华民族付出了巨大的代价，结束了两千八百年的封建统治；开创了亚洲第一个共和体制；写下了人类社会民主主义的新篇章！更向世人展示了一个真理：历史的潮流浩浩荡荡，不可阻挡；顺其者昌，逆其者亡。未来，充满着革命的因素和希望。　　</p>
<p>
	<br />
	◎影片截图</p>
<p>
	&nbsp;<img src="http://img165.poco.cn/mypoco/myphoto/20110924/14/56634212201109241451272988950683232_000.jpg" /></p>
<p>
	<img src="http://img165.poco.cn/mypoco/myphoto/20110924/14/56634212201109241451272988950683232_001.jpg" /></p>
<p>
	<img src="http://img165.poco.cn/mypoco/myphoto/20110924/14/56634212201109241451272988950683232_002.jpg" /></p>
<p>
	<img alt="" height="338" src="http://img165.poco.cn/mypoco/myphoto/20110925/11/56634212201109251131267226014504122_001.jpg" style="cursor: pointer" width="600" /></p>
<p>
	<img alt="" height="338" src="http://img165.poco.cn/mypoco/myphoto/20110925/11/56634212201109251131267226014504122_000.jpg" style="cursor: pointer" width="600" /></p>
<p>
	<img alt="" height="338" src="http://img165.poco.cn/mypoco/myphoto/20110925/11/56634212201109251131267226014504122_003.jpg" style="cursor: pointer" width="600" /></p>
<p>
	<img alt="" border="0" src="http://img165.poco.cn/mypoco/myphoto/20111011/21/56634212201110112110441157247098309_003.jpg" /><br />
	<br />
	<img alt="" border="0" src="http://img165.poco.cn/mypoco/myphoto/20111011/21/56634212201110112110441157247098309_002.jpg" /><br />
	<br />
	<img alt="" border="0" src="http://img165.poco.cn/mypoco/myphoto/20111011/21/56634212201110112110441157247098309_001.jpg" /><br />
	<br />
	<img alt="" border="0" src="http://img165.poco.cn/mypoco/myphoto/20111011/21/56634212201110112110441157247098309_000.jpg" /><br />
	&nbsp;</p>
<p>
	[下载地址]： &nbsp;<img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" /></p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:1649/飘花电影piaohua.com辛亥革命清晰TS国语中字.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:1649/飘花电影piaohua.com辛亥革命清晰TS国语中字.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:1652/飘花电影piaohua.com辛亥革命DVD.rmvb ">ftp://dy44:piaohua@dy44.piaohua.com:1652/飘花电影piaohua.com辛亥革命DVD.rmvb </a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:1800/飘花电影piaohua.com辛亥革命高清版DVD国语中字.rmvb ">ftp://dy44:piaohua@dy44.piaohua.com:1800/飘花电影piaohua.com辛亥革命高清版DVD国语中字.rmvb </a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O162545P-53257.jpg{/dede:field}
