{dede:field name='keywords'}我猜20060820迅雷下载，免费下载{/dede:field}
{dede:field name='description'}我猜20060820迅雷下载、免费下载，我猜20060820Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}我猜20060820{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2006-08-26{/dede:field}
{dede:field name='body'}<p>中文名称：我猜我猜我猜猜猜<br />英文名称：Guess Show<br />电视台：台湾中视<br />主持人：吴宗宪、柳翰雅、杨丞琳<br />地区：台湾<br />语言：普通话<br /><br />《我猜》最大的节目特色就是&ldquo;年轻&rdquo;。早期的《我猜》是以新旧人类对立为题，主持人吴宗宪，后来不论是布景、内容、主持人都改走年轻路线，开始大受新新人类欢迎。尤其是《脑内大革命》，猜不常见的成语这几个单元，立意甚佳，有趣又富教育性，屡创收视高峰，相当难得。制作人年纪虽轻头脑，灵活令《我猜》别具一格。<br />这是台湾王牌主持人吴宗宪的拳头栏目！<br />吴宗宪充满喜悦的说：&ldquo;这个节目是当年我迈向天王的&lsquo;踏脚石&rsquo;，多年来看尽人事变迁，酬劳也从每小时10万（约5000新元）调整到25万（约1万2500新元），我会为了观众，持续把节目做下去！&rdquo;</p>
<h2>下载地址</h2>
<p>（直接可能无法下载，一律使用<a href="http://pstatic.xunlei.com/about/product/down_xl5.htm" target="_blank">迅雷下载</a>）
<table style="WIDTH: 320px; HEIGHT: 20px" cellspacing="0" cellpadding="0" width="320" border="0">
    <tbody>
        <tr>
            <td title="我猜20060820">我猜20060820 (2006-8-26)</td>
            <td title="容量：143MB">143MB</td>
            <td title="格式：RM">RM</td>
            <td title="请用迅雷下载"><a href="http://rm.kan51.com/dsfiis/01/060820.wcwcwcc.rm" target="_blank">下载</a></td>
        </tr>
    </tbody>
</table>
<br />有漏集自行补充地址，将下载地址末尾替换即可，如： <br />01.rmvb替换为02.rmvb；a.rmvb替换为b.rmvb 等</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O160TS0-3bB.jpg{/dede:field}
