{dede:field name='keywords'}盗亦有道HD中字2012韩国动作喜剧{/dede:field}
{dede:field name='description'}盗亦有道HD中字2012韩国动作喜剧迅雷下载、免费下载，盗亦有道HD中字2012韩国动作喜剧Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}盗亦有道HD中字2012韩国动作喜剧{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-04-12{/dede:field}
{dede:field name='body'}<p>
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120412/15/56643687201204121513023150183962620_006.jpg" /></p>
<p>
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120412/15/56643687201204121513023150183962620_005.jpg" /></p>

<p>
	导演: 郑勇基<br />
	编剧: Jeong-woo Park<br />
	主演: 李凡秀 / 金秀路 / 成东日 / 李诗英 / 金子玉 / 高恩美<br />
	类型: 剧情 / 动作<br />
	官方网站: <a href="http://www.honggildong2009.co.kr">www.honggildong2009.co.kr</a><br />
	制片国家/地区: 韩国<br />
	语言: 韩语<br />
	上映日期: 2009-11-26(韩国) / 2012-04-13(中国大陆)<br />
	片长: 117分钟<br />
	又名: 洪吉童的后裔 / 神偷妙探三个半 / Hong Kil-dong&#39;s Descendents</p>
<p>
	剧情简介</p>
<p>
	　　城市中出现一位行踪诡秘、技巧高超的神秘人物，频频将手眼通天的富豪李正民（金秀路 饰）精心藏匿的巨款洗劫一空。黑白通吃的李正民气急败坏，并布下天罗地网，发誓要生擒这个即将使他囊空如洗的神秘人。<br />
	　　这时，生活拮据的当地检察官（成东日 饰）闯入了他的地盘，要挟查处李正民通过行贿、暴力手段垄断市场的罪行。李正民用拉拢 、威胁的手段，混淆视听，使检察官为其抓捕神秘人物。<br />
	　　暗中，乖张多疑的李正民却通过调查，把目标锁定在检察官妹妹（李诗英 饰）的恋人&mdash;&mdash;温文尔雅、风度翩翩的钢琴教师洪武赫（李凡秀 饰）身上。<br />
	　　谁是玩弄富豪于股掌的神秘人？谁是最后的胜利者？亦正亦邪的较量拉开大幕&hellip;&hellip;</p>

<p>
	◎影片截图</p>
<p>
	&nbsp;<img src="http://img170.poco.cn/mypoco/myphoto/20120412/15/56643687201204121513023150183962620_002.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 338px; border-top: 0px solid; border-right: 0px solid" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120412/15/56643687201204121513023150183962620_000.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 338px; border-top: 0px solid; border-right: 0px solid" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120412/15/56643687201204121513023150183962620_001.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 338px; border-top: 0px solid; border-right: 0px solid" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120412/15/56643687201204121513023150183962620_004.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 338px; border-top: 0px solid; border-right: 0px solid" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120412/15/56643687201204121513023150183962620_003.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 338px; border-top: 0px solid; border-right: 0px solid" /></p>

<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.netftp//dy44:piaohua@dy44.piaohua.com:3201/" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3208/飘花电影piaohua.com盗亦有道HD中字.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3208/飘花电影piaohua.com盗亦有道HD中字.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15D2150-1E21.jpg{/dede:field}
