{dede:field name='keywords'}非常人贩3/玩命快递3BD中英双字1{/dede:field}
{dede:field name='description'}非常人贩3/玩命快递3BD中英双字1024/1280高清迅雷下载、免费下载，非常人贩3/玩命快递3BD中英双字1024/1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}非常人贩3/玩命快递3BD中英双字1024/1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-12-10{/dede:field}
{dede:field name='body'}<p>
	<img alt="" border="0" onload_fckprotectedatt="%20onload%3D%22attachimg(this%2C%20'load')%22" src="http://img.album.pchome.net/54/68/81/51/99f1c1e7ea001319f1bbce64217e2a02.jpg" /></p>
<p>
	◎译　　名　《非常人贩3/玩命快递3》08最新刺激动作大片DVD中英双字1024x556高清版<br />
	◎片　　名　Transporter 3<br />
	◎年　　代　2008<br />
	◎国　　家　法国<br />
	◎类　　别　动作/冒险/犯罪/惊悚<br />
	◎语　　言　英语<br />
	◎字　　幕　中英双字<br />
	◎IMDB评分&nbsp;&nbsp;6.0/10&nbsp;&nbsp;13,285 votes<br />
	◎文件格式　BD-RMVB<br />
	◎视频尺寸　1024 x 556<br />
	◎文件大小　1CD<br />
	◎片　　长　104 Minutes<br />
	◎导　　演　奥利维尔&middot;米加顿 Olivier Megaton<br />
	◎主　　演　杰森&middot;斯坦森 Jason Statham&nbsp;&nbsp;....Frank Martin<br />
	　　　　　　罗伯特&middot;克耐普 Robert Knepper<br />
	　　　　　　弗朗西斯&middot;贝尔兰德 Fran?ois Berl&eacute;and&nbsp;&nbsp;....Tarconi<br />
	　　　　　　艾瑞克&middot;艾伯纳尼 Eriq Ebouaney&nbsp;&nbsp;....Ice<br />
	　　　　　　David Atrakchi&nbsp;&nbsp;....Malcom Manville<br />
	　　　　　　Farid Elouardi&nbsp;&nbsp;....Yuri<br />
	　　　　　　Mike Powers&nbsp;&nbsp;....American #1<br />
	　　　　　　Gregory Loffredo&nbsp;&nbsp;....Johnson&#39;s man<br />
	　　　　　　Natalya Rudakova&nbsp;&nbsp;....Valentina<br />
	　　　　　　杰若恩&middot;克拉比 Jeroen Krabb&eacute;&nbsp;&nbsp;....Leonid Vasilev<br />
	　　　　　　Alex Kobold&nbsp;&nbsp;....Leonid&#39;s Aide<br />
	　　　　　　Yann Sundberg&nbsp;&nbsp;....Flag<br />
	　　　　　　David Kammenos&nbsp;&nbsp;....Driver Market<br />
	　　　　　　Silvio Simac&nbsp;&nbsp;....Mighty Joe<br />
	　　　　　　Timo Dierkes<br />
	　　　　　　Eric Moreau&nbsp;&nbsp;....Cameraman<br />
	　　　　　　Michael Bennett&nbsp;&nbsp;....Garage attendant (uncredited)<br />
	<br />
	◎简　　介　<br />
	<br />
	　《非常人贩3》延续了前两部火爆的动作场面，杰森&middot;斯坦森和弗朗西斯&middot;贝尔兰德再次出演弗兰克&middot;马丁和塔科尼，《越狱》中的&ldquo;T-bag&rdquo;罗伯特&middot;克耐普将出演一个新角色。导演人选则从前两部的元奎和路易斯&middot;莱特里尔换成了奥利维尔&middot;米加顿。<br />
	<br />
	　　第三集将继续讲述弗兰克&middot;马丁这位职业押运人的故事，他在巴黎重新开始了他低调、不过问货物内容的押运任务。<br />
	<br />
	　　弗兰克&middot;马丁（杰森&middot;斯坦森饰）这位退役的特种兵，在经历了两次腥风血雨之后，重新回到了法国巴黎，准备在朋友的修车行里混口饭吃，修养生息。不过安顿的日子没过多久，仇家又找上门来，一顿打打杀杀之后，弗兰克&middot;马丁最终还是寡不敌众，倒在对手脚下。醒来之后，弗兰克&middot;马丁发现自己身处一个实验室，而手上却多了个腕表一样的东西。神秘组织的龙头老大约翰森（罗伯特&middot;克耐普饰）告诉弗兰克&middot;马丁，这次他是有求而来。鉴于弗兰克&middot;马丁在托运这一行的知名程度，约翰森需要他帮一个小忙：护送一个女人到达指定地点。如果与女人的距离过远，那么腕表就会爆炸。而如果成功护送到达目的地，那么约翰森就会把腕表除下。<br />
	<br />
	　　弗兰克与车行的铁哥们琢磨了好半天，发现这个腕表确实没法自己除下来，无奈下只好又重操旧业，护送起满头红发的神秘女人。显然这不是一份轻松的差事，约翰森是被警方通缉的罪犯，而警察为了寻找证据，执意要把红发女人带走，弗兰克只得与警察交起手来。这时候，另一个黑帮也想将弗兰克和红发女人置于死地，于是两人在警察和黑社会的双重追捕中，一路杀向终点&hellip;&hellip;</p>
<p>
	<img alt="" border="0" onload="attachimg(this, 'load')" src="http://images.dvdempire.com/gen/movies/1448328h.jpg" /></p>
<p>
	关于影片：<br />
	<br />
	由吕克&middot;贝松监制的&ldquo;非常人贩&rdquo;系列终于拍到了第三部，虽然发行方改变将&ldquo;非3&rdquo;从合拍片变为纯正的法国片，但无论是制作还是拍摄仍是非常的好莱坞。第一男主角仍旧是我们熟悉的杰森&middot;斯坦森，不用说，这一次他在屡屡想退休的念头下，一定又不得不从事了老本行，接了一个危险又艰巨的生意。<br />
	<br />
	值得一提的是，因热播美剧《越狱》大红的&ldquo;T-bag&rdquo;罗伯特&middot;克耐普扮演了《非常人贩3》里的大反派，以其招牌式的阴险毒辣来对付曾经风光无限的玩命&ldquo;快递员&rdquo;，再加上吕克&middot;贝松精彩火<a href="http://www.eee4.com/" target="_blank">迅雷电影下载</a>爆的动作场面，这部电影值得期待。<br />
	<br />
	幕后花絮<br />
	<br />
	&middot;本片在第二集之后，再次回到第一集的拍摄地点法国进行拍摄。<br />
	<br />
	&middot;在影片的拍摄过程中，本集导演奥利维尔&middot;米加顿特地选择了一些在第一集里出现的场景作为致敬。<br />
	<br />
	&middot;在本片中扮演反方男一号的罗伯特&middot;克耐普，是吕克&middot;贝松在观看《越狱》之后才力邀的，甚至剧本中的人物也是为他专门定做。<br />
	<br />
	&middot;影片的公映日期由原定的暑假一直延期至今年的11月，这是因为杰森&middot;斯坦森今年主演了太多动作电影的缘故，甚至片方原本打算延期至明年暑假。</p>
<p>
	【电影截图】：</p>
<p>
	<img alt="" border="0" onload_fckprotectedatt="%20onload%3D%22attachimg(this%2C%20'load')%22" src="http://img.album.pchome.net/54/68/81/51/31e81225c3c0763f80717857cc53840e.jpg" style="width: 675px; height: 373px" /></p>
<p>
	<img alt="" border="0" onload_fckprotectedatt="%20onload%3D%22attachimg(this%2C%20'load')%22" src="http://img.album.pchome.net/54/68/81/51/711b9e5bed60893afeda7e5f40a59e7f.jpg" style="width: 675px; height: 346px" /></p>
<p>
	08最新刺激动作大片《非常人贩3》DVD中字 －来自[www.eee4.com]：<img border="0" src="http://www.eee4.com/templets/img/down.jpg" /></p>

<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://e16:e16@xl2.eee4.com:9219/[3E电影站www.eee4.com]非常人贩3DVD中字.rmvb" target="_blank">ftp://e16:e16@xl2.eee4.com:9219/[3E电影站www.eee4.com]非常人贩3DVD中字.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://e16:e16@xl2.eee4.com:9219/[3E电影站www.eee4.com]非常人贩3DVD中英双字.rmvb" target="_blank">ftp://e16:e16@xl2.eee4.com:9219/[3E电影站www.eee4.com]非常人贩3DVD中英双字.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://e16:e16@xl2.eee4.com:9219/[3E电影站www.eee4.com]非常人贩3[DVD中英双字1024x556高清版].rmvb" target="_blank">ftp://e16:e16@xl2.eee4.com:9219/[3E电影站www.eee4.com]非常人贩3[DVD中英双字1024x556高清版].rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2301/飘花电影piaohua.com非常人贩3BD中英双字1280高清.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2301/飘花电影piaohua.com非常人贩3BD中英双字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O16044W0-31349.jpg{/dede:field}
