{dede:field name='keywords'}顺藤而上的你更新第26集[韩语中{/dede:field}
{dede:field name='description'}顺藤而上的你更新第26集[韩语中字]2011韩国KBS2周末剧迅雷下载、免费下载，顺藤而上的你更新第26集[韩语中字]2011韩国KBS2周末剧Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}顺藤而上的你更新第26集[韩语中字]2011韩国KBS2周末剧{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-22{/dede:field}
{dede:field name='body'}<p>
	<img alt="" border="0" src="http://img.album.pchome.net/02/25/03/37/1806d1a853ca9b2265df838a887afaad.jpg" /></p>
<p>
	[剧 名]:顺藤而上的你<br />
	[播 送]:韩国KBS2<br />
	[类 型]:周末连续剧&nbsp;<br />
	[首 播]:2012年02月25日<br />
	[时 间]:每周六、日晚北京时间20点55分各播放一集<br />
	[接 档]:鹊桥兄弟们<br />
	[导 演]:金亨植《恋爱结婚》<br />
	[编 剧]:朴智恩《逆转的女王》《贤内助女王》《刀手吴水晶》<br />
	[主 演]:金南珠、刘俊相、尹汝贞、姜富子、金相浩、张勇、吴妍书、杨贞雅、姜敏赫、赵允熙、金元俊等<br />
	[简 介]:《顺藤而上的你》讲述了一个热情且有能力，傲气、胜负欲很强，同时很有正义感，对于世界上的事情关心很多的&ldquo;概念女&rdquo;车允熙（金南珠 饰），宣布结婚是不公正的系统，浪费能量与人生。但最后爱上身为医生的完美男人房贵男（刘俊相 饰）后开始180度大转弯的人生，以及想像不到的婆家的登场后发生的波澜起伏的事件。<br />
	演员金南珠出道18年首次出演KBS电视剧.金南珠在继&lt;鹊桥兄弟们&gt;后续于2月首播的KBS新週末剧&lt;顺藤而上&gt;中确定出演.剧中金南珠饰演的是一个热情且有能力的领导女性.傲气以及胜负欲很强,也很有正义感,对于世界上的事情关心很多的&rdquo;概念女&rdquo;.宣佈结婚是不公正的系统,浪费能量与人生,但是最后爱上完美男人后开始180度大转弯的人生.<br />
	电视剧有关人士表示&rdquo;金南珠表示觉得这个角色与自己相似点很多,将表现金南珠特有的演技&rdquo;.<br />
	另外&lt;顺藤而上&gt;中金南珠饰演的角色具有完美的条件之外,见到医生决定结婚但是想像不到的婆家的登场发生了波澜起伏的事件.</p>
<p>
	&nbsp;[下载地址]：<img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" /></p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2896/飘花电影piaohua.com顺藤而上的你01.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2896/飘花电影piaohua.com顺藤而上的你01.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2899/飘花电影piaohua.com顺藤而上的你02.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2899/飘花电影piaohua.com顺藤而上的你02.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2950/飘花电影piaohua.com顺藤而上的你03.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2950/飘花电影piaohua.com顺藤而上的你03.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2974/飘花电影piaohua.com顺藤而上的你04.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2974/飘花电影piaohua.com顺藤而上的你04.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2995/飘花电影piaohua.com顺藤而上的你05.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2995/飘花电影piaohua.com顺藤而上的你05.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3002/飘花电影piaohua.com顺藤而上的你06.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3002/飘花电影piaohua.com顺藤而上的你06.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3036/飘花电影piaohua.com顺藤而上的你07.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3036/飘花电影piaohua.com顺藤而上的你07.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3041/飘花电影piaohua.com顺藤而上的你08.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3041/飘花电影piaohua.com顺藤而上的你08.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3073/飘花电影piaohua.com顺藤而上的你09.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3073/飘花电影piaohua.com顺藤而上的你09.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3077/飘花电影piaohua.com顺藤而上的你10.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3077/飘花电影piaohua.com顺藤而上的你10.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3124/飘花电影piaohua.com顺藤而上的你11.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3124/飘花电影piaohua.com顺藤而上的你11.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3133/飘花电影piaohua.com顺藤而上的你12.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3133/飘花电影piaohua.com顺藤而上的你12.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3179/飘花电影piaohua.com顺藤而上的你13.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3179/飘花电影piaohua.com顺藤而上的你13.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3185/飘花电影piaohua.com顺藤而上的你14.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3185/飘花电影piaohua.com顺藤而上的你14.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3227/飘花电影piaohua.com顺藤而上的你15.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3227/飘花电影piaohua.com顺藤而上的你15.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3231/飘花电影piaohua.com顺藤而上的你16.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3231/飘花电影piaohua.com顺藤而上的你16.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3274/飘花电影piaohua.com顺藤而上的你17.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3274/飘花电影piaohua.com顺藤而上的你17.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3274/飘花电影piaohua.com顺藤而上的你18.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3274/飘花电影piaohua.com顺藤而上的你18.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3323/飘花电影piaohua.com顺藤而上的你19.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3323/飘花电影piaohua.com顺藤而上的你19.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3323/飘花电影piaohua.com顺藤而上的你20.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3323/飘花电影piaohua.com顺藤而上的你20.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3367/飘花电影piaohua.com顺藤而上的你21.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3367/飘花电影piaohua.com顺藤而上的你21.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3408/飘花电影piaohua.com顺藤而上的你22.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3408/飘花电影piaohua.com顺藤而上的你22.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3408/飘花电影piaohua.com顺藤而上的你23.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3408/飘花电影piaohua.com顺藤而上的你23.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3413/飘花电影piaohua.com顺藤而上的你24.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3413/飘花电影piaohua.com顺藤而上的你24.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3465/飘花电影piaohua.com顺藤而上的你25.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3465/飘花电影piaohua.com顺藤而上的你25.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3470/飘花电影piaohua.com顺藤而上的你26.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3470/飘花电影piaohua.com顺藤而上的你26.rmvb</a></td>
		</tr>
	</tbody>
</table>
<p>
	&nbsp;</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1AF440-3D26.jpg{/dede:field}
