{dede:field name='keywords'}少林搭棚大师BD高清国粤双语无字{/dede:field}
{dede:field name='description'}少林搭棚大师BD高清国粤双语无字幕1024*576迅雷下载、免费下载，少林搭棚大师BD高清国粤双语无字幕1024*576Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}少林搭棚大师BD高清国粤双语无字幕1024*576{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-09-19{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img165.poco.cn/mypoco/myphoto/20110918/11/62564813201109181128064192503647381_000.jpg" style="width: 720px; height: 550px" /></p>
<p>
	◎片&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 名&nbsp;&nbsp;&nbsp; 少林搭棚大师<br />
	◎英&nbsp; 文&nbsp;&nbsp; 名&nbsp;&nbsp;&nbsp; Return to the 36th Chamber<br />
	◎年&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 代&nbsp;&nbsp;&nbsp;&nbsp; 1980<br />
	◎国&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 家&nbsp;&nbsp;&nbsp;&nbsp; 中国香港<br />
	◎类&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 别&nbsp;&nbsp;&nbsp;&nbsp; 功夫<br />
	◎语&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 言&nbsp;&nbsp;&nbsp;&nbsp; 普通话/粤语<br />
	◎IMDB评分&nbsp;&nbsp;&nbsp;&nbsp; 7.1/10 (681 votes)<br />
	◎IMDB链接&nbsp;&nbsp;&nbsp;&nbsp; <a href="http://www.imdb.com/title/tt0081494/">http://www.imdb.com/title/tt0081494/</a><br />
	◎片&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 长&nbsp;&nbsp;&nbsp; 102 Min<br />
	◎导&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 演&nbsp;&nbsp;&nbsp; 刘家良<br />
	◎主&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 演&nbsp;&nbsp;&nbsp; 刘家辉<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 惠英红 Kara Hui ....Hung<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 王龙威 Lung Wei Wang ....Boss Wang<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 权永文 Yeong-mun Kwon ....Manchu Warrior (as Kuen Wing-Man)<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 小侯 Hou Hisao ....Chau<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 杨菁菁 Ching-Ching Yeung ....Hsiao-Ching<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 陈思佳 Si Gaai Chan<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 尤翠玲 Tsui Ling Yu<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 邓伟豪 Wei Hao Teng<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 江岛 Tao Chiang<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 京柱 Ching Chu<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 井淼 Miao Ching<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 王清河 Ching-Ho Wang<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 韦白 Wei Pei ....Sun</p>
<p>
	<br />
	【剧情简介】<br />
	　&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 刘家良师傅继《少林三十六房》大获好评后，再下一城以「少林寺」及「三德和尚」为题材拍摄此片。刘家辉今回不再饰演三德和尚，改演城市小滑头仁杰，他假扮&ldquo;三德和尚&rdquo;以锄恶霸王高峰（王龙威饰）气焰，反被识破而遭痛殴。仁杰遂上少林寺要求三德和尚授其功夫，但屡试不果。最后三德允其留在寺中负责搭棚修葺工作，因而仁杰反可以居高临下，一睹三十六房练功全貌，从中习武达三年之久。工程完毕，三德遂驱逐仁杰出寺，仁杰深感不平。但他却不知道自己不知不觉间已练成少林武功，惩恶扬善，故得&ldquo;少林搭棚大师&rdquo;之美名。</p>
<p>
	精彩视点<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 年介66岁的刘家良是著名的导演及武术指导，1950年加入影圈当临时演员及龙虎武师，之后参演超过100部电影。1975年首次执导电影《神打》，继而执导《少林三十六房》，80年代乃刘家良的事业高峰，曾捧红傅声、汪禹和刘家辉等人。<br />
	1999年，刘师傅荣获香港导演会的最高荣誉奖。而刘家良的义弟&mdash;刘家辉，1970年代后期的邵氏打星，凭刘家良的《少林三十六房》走红香港及日本两地。 继《少林三十六房》大获好评后，刘师傅再次以「少林寺」及「三德和尚」为号召拍了《少林搭棚大师》。</p>
<p>
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 刘氏电影的成功以及与众不同，表现在其作品能使武术与情节融为一体。本片即是由刘家良担任导演，以&ldquo;三德和尚&rdquo;文明的刘家辉及著名功夫片演员王龙威携手演出的一部经典动作片。本片是邵氏经典作品&ldquo;少林系列&rdquo;中较为精彩的一部，同时也是《少林三十六房》的续集。影片打斗部分精彩纷呈，演员对白幽默有趣，不失为早期动作片中的经典。</p>
<p>
	&nbsp;<img alt="" src="http://img165.poco.cn/mypoco/myphoto/20110919/07/62564813201109190757091701801406272_004.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img165.poco.cn/mypoco/myphoto/20110919/07/62564813201109190757091701801406272_003.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img165.poco.cn/mypoco/myphoto/20110919/07/62564813201109190757091701801406272_002.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img165.poco.cn/mypoco/myphoto/20110919/07/62564813201109190757091701801406272_001.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img165.poco.cn/mypoco/myphoto/20110919/07/62564813201109190757091701801406272_000.jpg" style="width: 720px; height: 405px" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="&#13;&#10;ftp://dy125:piaohua@dy125.piaohua.com:4043/飘花电影piaohua.com少林搭棚大师国粤双语BD高清1024分辨率.mkv">ftp://dy125:piaohua@dy125.piaohua.com:4043/飘花电影piaohua.com少林搭棚大师国粤双语BD高清1024分辨率.mkv </a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1C10b0-51400.jpg{/dede:field}
