{dede:field name='keywords'}百老汇上空的子弹/子弹横飞百老{/dede:field}
{dede:field name='description'}百老汇上空的子弹/子弹横飞百老汇BD01280高清中字迅雷下载、免费下载，百老汇上空的子弹/子弹横飞百老汇BD01280高清中字Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}百老汇上空的子弹/子弹横飞百老汇BD01280高清中字{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-13{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120513/02/17870980201205130213251982861943290_000.jpg" style="width: 718px; height: 1024px" /></p>
<p>
	◎译　　名　百老汇上空的子弹/子弹横飞百老汇<br />
	◎片　　名　Bullets Over Broadway<br />
	◎年　　代　1994<br />
	◎国　　家　美国<br />
	◎类　　别　喜剧/犯罪<br />
	◎语　　言　英语<br />
	◎字　　幕　N/A<br />
	◎IMDB评分 7.5/10 (16,488 votes)<br />
	◎IMDB链接 <a href="http://www.imdb.com/title/tt0109348/" target="_blank">http://www.imdb.com/title/tt0109348/</a><br />
	◎文件格式　X264 + AC3<br />
	◎视频尺寸　1280 x 720<br />
	◎文件大小　95x50mb<br />
	◎片　　长　1h 38min<br />
	◎导　　演　伍迪&middot;艾伦 Woody Allen<br />
	◎主　　演　约翰&middot;库萨克 John Cusack ....David Shayne<br />
	　　　　　　黛安娜&middot;维斯特 Dianne Wiest ....Helen Sinclair<br />
	　　　　　　珍妮佛&middot;提莉 Jennifer Tilly ....Olive Neal<br />
	　　　　　　查兹&middot;帕尔明特瑞 Chazz Palminteri ....Cheech<br />
	　　　　　　杰克&middot;瓦尔登 Jack Warden ....Julian Marx<br />
	　　　　　　Joe Viterelli ....Nick Valenti<br />
	　　　　　　玛丽&middot;露易斯&middot;帕克 Mary-Louise Parker ....Ellen<br />
	　　　　　　罗伯&middot;莱纳 Rob Reiner ....Sheldon Flender<br />
	　　　　　　崔茜&middot;尤玛 Tracey Ullman ....Eden Brent<br />
	　　　　　　吉姆&middot;布劳德本特 Jim Broadbent ....Warner Purcell<br />
	　　　　　　哈维&middot;费斯特恩 Harvey Fierstein ....Sid Loomis<br />
	　　　　　　埃迪&middot;法可 Edie Falco ....Lorna<br />
	　　　　　　肯&middot;罗伯茨 Ken Roberts ....Theater Well-Wisher<br />
	◎简 　 介<br />
	剧情<br />
	　　二十年代一位在纽约格林威治村的剧作家，经由一位颇具盛名的制片帮忙，获得执导一部百老汇剧作的机会，但先决条件是他必须启用帮派分子的女友担任剧中女配角。然而剧作家心目中已有中意的人选，于是他面临了人情压力和自主的抉择进而发展出一连串出人意表的故事，最后的结果竟然是&hellip;&hellip;<br />
	一句话评论<br />
	A killer comedy!<br />
	The New Comedy From Woody Allen!<br />
	幕后制作<br />
	　　看伍迪&middot;艾伦的电影，你绝对不要指望能笑得出来。因为，伍迪&middot;艾伦的电影都有着深刻而沉重的含义和思考。看完伍迪&middot;艾伦的电影也不要立刻站起来，坐一会儿，就这样坐一会儿。因为他还留给了你一些家庭作业，一些开放性的思考，关于人生、关于生活的。要好好想想，不能偷懒，因为这样的思考能让我们渐渐明白电影真正的含义和导演的一番苦心，因为这样的思考能让我们变得深刻和坚强起来，即使无奈，即使无力改造世界，我们也要坚持自己&hellip;&hellip;伍迪&middot;艾伦不愧是好莱坞历史上不可或缺的一员大将，因为没有他，好莱坞只是一堆漂亮的泡沫而已。</p>
<p>
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120513/02/17870980201205130213251982861943290_006.jpg" style="width: 640px; height: 360px" /></p>
<p>
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120513/02/17870980201205130213251982861943290_005.jpg" /></p>
<p>
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120513/02/17870980201205130213251982861943290_003.jpg" style="width: 640px; height: 360px" /></p>
<p>
	<br />
	<br />
	&nbsp;</p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.net" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy241:piaohua@117.41.229.29:2017/飘花电影piaohua.com百老汇上空的子弹BD01280高清中字.rmvb">ftp://dy241:piaohua@117.41.229.29:2017/飘花电影piaohua.com百老汇上空的子弹BD01280高清中字.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15ab60-14R5.jpg{/dede:field}
