{dede:field name='keywords'}修女也疯狂2高清BD1280迅雷下载{/dede:field}
{dede:field name='description'}修女也疯狂2高清BD1280迅雷下载、免费下载，修女也疯狂2高清BD1280Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}修女也疯狂2高清BD1280{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-04-22{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120421/21/62564813201204212111223444136496654_000.jpg" style="width: 600px; height: 764px" /></p>
<p>
	【原 片 名】Sister Act 2<br />
	【中 文 名】修女也疯狂2<br />
	【出品公司】博伟（Buena Vista）试金石（Touchstone）<br />
	【出品年代】1993年<br />
	【首映日期】1993年12月10日<br />
	【MPAA级别】PG 级<br />
	【IMDB链接】<a class="faqlink" endcolor="FF6600" href="http://www.imdb.com/Title?0108147" index="0" startcolor="0066ff" state="OFF" style="color: #0066ff">http://www.imdb.com/Title?0108147</a><br />
	【IMDB评分】4.5/10 (3,068)<br />
	【国　　家】美国<br />
	【类　　别】喜剧（Comedy）　音乐（Musical）<br />
	【导　　演】Bill Duke<br />
	【主　　演】胡比?戈德堡（Whoopi Goldberg）<br />
	【影片长度】107 Mins<br />
	<br />
	<br />
	【内容简介】<br />
	<br />
	德洛里斯现在已经是拉斯维加斯的一位红歌手。这时候，修女们前来请求她的帮助。原来，她们被调到一所社区教会学校去服务，孩子们的叛逆行为与教会式的古板教育之间产生了水火难容的矛盾。修道院院长希望德洛里斯能够来帮助她们。热心的德洛里斯答应了她们。<br />
	学校里的孩子们很难管教。他们恣意嬉闹，毫无忌惮，德洛里斯也免不了受到他们的捉弄，但她接手音乐班后，还是克服了不少的困难，使学生们逐渐开始理解和喜欢上她了。<br />
	就在这时，德洛里斯无意间发现，学校因为财政困难而面临着被关闭的命运。热情洋溢的德洛里斯开始使出了浑身解数。她领导孩子们成立了合唱团，并且热情地教导和训练他们，以参加州里的教会学校合唱比赛，取得荣誉使学校摆脱困境。<br />
	孩子们在学校的登台演出大获成功。他们终于来到了州里准备参加比赛。其他各个学校精彩的表演使孩子们大为沮丧，在德洛里斯的鼓励下，大家又重新恢复了信心。但就在这个关键时刻，德洛里斯的真正身份暴露了，多亏修道士们的大力帮忙，才使合唱团免遭失去资格的恶运。<br />
	孩子们的感人表现获得了一等奖。学校渡过了重大的生存危机。德洛里斯的热心帮助终于保住了修女和孩子们所热爱的学校。<br />
	<br />
	<br />
	在《修女也疯狂》的第一集大获成功之后，乌比?戈德堡再接再厉，推出了影片的第二集。但其水准比起前一集来却要大为逊色，其票房收入自然也不甚理想，实在令人不能不感到遗憾。<br />
	从剧情上来说，第二集远没有第一集那么出色和吸引人。这一集成了一部完完全全的音乐片，导演抓住片中的每一个时机塞入一个又一个的歌舞表演，使影片成了一个歌舞大杂烩，使人有剧情为歌舞而设不是歌舞为剧情而设的感觉。平心而论，片中的歌唱得也不错，只不过显得太杂乱了一些。各种风格的歌曲都挤出来唱上一唱。而剧情的构架又显得十分松散。于是令人倒胃口也就在所难免了。<br />
	之所以下这样的评语，其实也是与第一集相比较的结果。如果只是为了欣赏歌舞，抱着一种无可无不可的态度去看，那么这部影片也还是可以一看的，毕竟里面的歌还不错。而且看这部影片还有一个好处，就是随便在哪里断开都可以。今天看一半，明天再看另一半，也绝对影响不了观赏的效果。但要认真一点来说，剧情的松散拖迭是这部影片最大的弱点。显然片中也表达了人与人之间互相关心爱护的主题，却也难以因此而称之为优秀。影片的制片人企图以一堆歌舞来吸引观众，其效果却并不理想，他应该明白，要听音乐用音响就行了，又何必特地去电影院呢!<br />
	乌比?戈德堡在影片中的表演还是不错的。其歌喉也颇可称道。只是遇上了一个松散的剧情，演员本身的演技虽好，却也是无济于事了。</p>
<p>
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120421/21/62564813201204212108215951897882233_002.jpg" style="width: 720px; height: 366px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120421/21/62564813201204212108215951897882233_001.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120421/21/62564813201204212108215951897882233_000.jpg" style="width: 720px; height: 405px" /><br />
	<br />
	&nbsp;</p>
<p>
	【下载地址】</p>
<table bgcolor="#0099cc" border="0" cellpadding="10" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.net" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy125:piaohua@dy125.piaohua.com:7877/飘花电影piaohua.com修女也疯狂2BD中字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:7877/飘花电影piaohua.com修女也疯狂2BD中字1280高清.rmvb</a></td>
		</tr>
		<tr>
		</tr>
	</tbody>
</table>
<br />{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15E33P-4M37.jpg{/dede:field}
