<?php
$z[0]=Array("field","机械战警/机器战警/铁甲威龙/威",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","机械战警/机器战警/铁甲威龙/威龙争雄[BD中英双字1024x576高清版]迅雷下载、免费下载，机械战警/机器战警/铁甲威龙/威龙争雄[BD中英双字1024x576高清版]Gvod高清在线播放，剧情介绍等。",72,288);
$z[1][4]['name']="description";
$z[2]=Array("field","机械战警/机器战警/铁甲威龙/威龙争雄[BD中英双字1024x576高清版]",290,389);
$z[2][4]['name']="title";
$z[3]=Array("field","",391,430);
$z[3][4]['name']="writer";
$z[4]=Array("field","",432,471);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-08-17",473,523);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",525,562);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://3e:3e@d8.3edyy.com:174/【3E电影院www.eee4.cc】机械战警BD中英双字1024x576高清版.rmvb\" target=\"_blank",564,708);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MQ3623Z-1K31.jpg",710,792);
$z[8][4]['name']="litpic";

?>