{dede:field name='keywords'}机械战警/机器战警/铁甲威龙/威{/dede:field}
{dede:field name='description'}机械战警/机器战警/铁甲威龙/威龙争雄[BD中英双字1024x576高清版]迅雷下载、免费下载，机械战警/机器战警/铁甲威龙/威龙争雄[BD中英双字1024x576高清版]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}机械战警/机器战警/铁甲威龙/威龙争雄[BD中英双字1024x576高清版]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2010-08-17{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://3e:3e@d8.3edyy.com:174/【3E电影院www.eee4.cc】机械战警BD中英双字1024x576高清版.rmvb" target="_blank{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MQ3623Z-1K31.jpg{/dede:field}
