<?php
$z[0]=Array("field","BBC,摧毁泰坦尼克号的冰山杀手迅",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","BBC 摧毁泰坦尼克号的冰山杀手迅雷下载、免费下载，BBC 摧毁泰坦尼克号的冰山杀手Gvod高清在线播放，剧情介绍等。",73,223);
$z[1][4]['name']="description";
$z[2]=Array("field","BBC 摧毁泰坦尼克号的冰山杀手",225,291);
$z[2][4]['name']="title";
$z[3]=Array("field","",293,332);
$z[3][4]['name']="writer";
$z[4]=Array("field","",334,373);
$z[4][4]['name']="source";
$z[5]=Array("field","2008-01-07",375,425);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",427,464);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://eee4.com:eee4@xl3.eee4.com:8448/冰山杀手/[3E迅雷电影站www.eee4.com]BBC摧毁泰坦尼克号的冰山杀手.rmvb\" target=\"_blank",466,626);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MP43Y60-51251.jpg",628,711);
$z[8][4]['name']="litpic";

?>