{dede:field name='keywords'}国家地理世界致命动物：北美洲HD{/dede:field}
{dede:field name='description'}国家地理世界致命动物：北美洲HD中字1024高清美国纪录片迅雷下载、免费下载，国家地理世界致命动物：北美洲HD中字1024高清美国纪录片Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}国家地理世界致命动物：北美洲HD中字1024高清美国纪录片{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-01-08{/dede:field}
{dede:field name='body'}<p>
	<img alt="" height="335" id="img_0.5818263716300474" src="http://img.album.pchome.net/54/71/41/84/89cae60a75799d2f7314691c759b87bb.jpg" width="600" /><br />
	◎片　　名　National.Geographic.World&#39;s Deadliest Animals：Africa<br />
	◎译　　名　国家地理.世界致命动物.非洲<br />
	◎年　　代　2008<br />
	◎影片类型　纪录片<br />
	◎片　　长　47 Mins<br />
	◎国　　家　美国<br />
	◎对白语言　英语<br />
	◎编　　码　720P.HDTV-RMVB<br />
	◎视频尺寸　1024 x 576<br />
	◎文件大小　969MB<br />
	◎简　　介　<br />
	在北美的每一个角落，无论是高山水下还是丛林深处，大自然都洋溢着勃勃生机。然而，这里同样弥也漫着死亡的气息，危险无处不在。杀戮的游戏随时都可能上演。因为，这里有着北美洲十二种最致命的动物，他们就是所有噩梦的主角，凶残的刽子手。就让我们一起走入北美十二金刚的隐秘世界。<br />
	<img alt="" height="337" id="img_0.9895060240814049" src="http://img.album.pchome.net/54/71/54/18/99e25ebda1ca6860a71073128dfc585b.jpg" style="cursor: pointer" width="600" /><br />
	<img alt="" height="337" id="img_0.3924208867048873" src="http://img.album.pchome.net/54/71/54/18/cb33a3f180c1fdbeb7c64189ba18df21.jpg" style="cursor: pointer" width="600" /></p>
<p>
	[下载地址]： &nbsp;<img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				&nbsp;<a href="ftp://dy44:piaohua@dy44.piaohua.com:2551/飘花电影piaohua.com国家地理世界致命动物北美洲HD中字1024高清.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2551/飘花电影piaohua.com国家地理世界致命动物北美洲HD中字1024高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1C63460-44357.jpg{/dede:field}
