{dede:field name='keywords'}成龙的特技迅雷下载，免费下载，{/dede:field}
{dede:field name='description'}成龙的特技迅雷下载、免费下载，成龙的特技Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}成龙的特技{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2008-01-09{/dede:field}
{dede:field name='body'}<P>【译　　名】《成龙的特技》<BR>【片　　名】Jackie Chan: My Stunts <BR>【年　　代】1999<BR>【国　　家】香港<BR>【类　　别】记录<BR>【语　　言】普通话<BR>【字　　幕】中文<BR>【视频尺寸】512*384<BR>【电影来源】3E迅雷电影下载站(www.eee4.com)<BR>【文件大小】1CD/380MB<BR>【片　　长】96 Min<BR>【导　　演】成龙Jackie Chan<BR>【主　　演】成龙Jackie Chan .....Himself<BR>　　　　　　卢惠光Ken Lo .....Himself - Jackie Chan Stuntman Team<BR>　　　　　　火星Mars .....Himself (Jackie Chan Stuntman Team)</P>
<P>【剧情简介】：</P>
<P>&nbsp;&nbsp;&nbsp; 动作片是世界电影的主流之一, 而$$ID=成龙$$的动作特技是亚洲电影唯一能与美国同类电影抗衡的异军。成龙曾引以为傲的说:"荷里活要靠电脑才能做出的惊险场面, 我则靠自己的真功夫, 而做出来的更加惊险更真实感。"</P>
<P>&nbsp;&nbsp;&nbsp; 成龙特技深入的剖析成龙电影中的动作场面, 背後的拍摄秘技, 他更亲自剖析一些比较难忘的危险特技。任何喜欢成龙动作处片的观众, 都不应该错过这一部 "成龙: 我的特技"。<BR>电影来源：www.eee4.com</P>
<P><IMG src="http://pic.piaohua.com/0701pic/allimg/080109/0235430.jpg" border=0></P>
<P>【电影截图】：<BR>电影来源：www.eee4.com<BR><IMG src="http://pic.piaohua.com/0701pic/allimg/080109/0237030.jpg" border=0><BR><IMG src="http://pic.piaohua.com/0701pic/allimg/080109/0237031.jpg" border=0><BR><IMG src="http://pic.piaohua.com/0701pic/allimg/080109/0235433.jpg" border=0><BR><IMG src="http://pic.piaohua.com/0701pic/allimg/080109/0235434.jpg" border=0></P>
<P>2008-01-09 02:14:12 开始连接......<BR>2008-01-09 02:14:14 开始搜索候选资源......<BR>2008-01-09 02:14:15 搜索到31个候选资源<BR>2008-01-09 02:14:17 使用候选资源进行连接......<BR>2008-01-09 02:14:20 搜索到26个候选资源<BR>2008-01-09 02:14:23 使用候选资源进行连接......<BR>2008-01-09 02:14:24 文件创建成功，开始下载数据......<BR>2008-01-09 02:14:26 用户取消下载&nbsp;&nbsp; 本文来自 <A href="/index.html" target=_blank>www.eee4.com</A></P>（直接可能无法下载，一律使用<A href="http://pstatic.xunlei.com/about/product/down_xl5.htm" target=_blank>迅雷下载</A>）<BR>不可错过的好片《成龙的特技》DVD中字 － 来自[3E迅雷电影站eee4.com]下载地址：<IMG src="/templets/img/down.jpg" border=0><BR>
<TABLE style="BORDER-RIGHT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; BORDER-BOTTOM: #cccccc 1px dotted" cellSpacing=0 cellPadding=6 width="95%" align=center border=0>
<TBODY>
<TR>
<TD style="WORD-WRAP: break-word" bgColor=#fdfddf><ANCHOR></ANCHOR><A href="ftp://eee4.com:eee4@xl3.eee4.com:8448/成龙的特技DVD/[3E迅雷电影站www.eee4.com]成龙的特技DVD.rmvb" target=_blank>ftp://eee4.com:eee4@xl3.eee4.com:8448/成龙的特技DVD/[3E迅雷电影站www.eee4.com]成龙的特技DVD.rmvb</A></TD></TR></TBODY></TABLE>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O16125950-12555.jpg{/dede:field}
