<?php
$z[0]=Array("field","资本主义：一个爱情故事[BD中英",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","资本主义：一个爱情故事[BD中英双字1280x720高清版]迅雷下载、免费下载，资本主义：一个爱情故事[BD中英双字1280x720高清版]Gvod高清在线播放，剧情介绍等。",72,262);
$z[1][4]['name']="description";
$z[2]=Array("field","资本主义：一个爱情故事[BD中英双字1280x720高清版]",264,350);
$z[2][4]['name']="title";
$z[3]=Array("field","",352,391);
$z[3][4]['name']="writer";
$z[4]=Array("field","",393,432);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-03-07",434,484);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",486,523);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://3e:3e@m1.3edyy.com:1396/【3E电影院www.3edyy.com】资本主义：一个爱情故事BD中英双字1280x720高清版.rmvb\" target=_blank>ftftp://3e:3e@m1.3edyy.com:1396/【3E电影院www.3edyy.com】资本主义：一个爱情故事BD中英双字1280x720高清版.rmvb</A></TD></TR></TBODY></TABLE></div><ul class=\"mmlist",525,847);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MQ33JF-36063.jpg",849,931);
$z[8][4]['name']="litpic";

?>