{dede:field name='keywords'}资本主义：一个爱情故事[BD中英{/dede:field}
{dede:field name='description'}资本主义：一个爱情故事[BD中英双字1280x720高清版]迅雷下载、免费下载，资本主义：一个爱情故事[BD中英双字1280x720高清版]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}资本主义：一个爱情故事[BD中英双字1280x720高清版]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2010-03-07{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://3e:3e@m1.3edyy.com:1396/【3E电影院www.3edyy.com】资本主义：一个爱情故事BD中英双字1280x720高清版.rmvb" target=_blank>ftftp://3e:3e@m1.3edyy.com:1396/【3E电影院www.3edyy.com】资本主义：一个爱情故事BD中英双字1280x720高清版.rmvb</A></TD></TR></TBODY></TABLE></div><ul class="mmlist{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MQ33JF-36063.jpg{/dede:field}
