{dede:field name='keywords'}再见老婆日韩剧6迅雷下载，免费{/dede:field}
{dede:field name='description'}再见老婆日韩剧6迅雷下载、免费下载，再见老婆日韩剧6Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}再见老婆日韩剧6{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-23{/dede:field}
{dede:field name='body'}<p>
	<img src="http://img.funshion.com/attachment/new_images/2012/05-08/32694648_1336466696_508.jpg" style="width: 600px; height: 840px" /></p>
<p>
	<img src="http://img.funshion.com/attachment/new_images/2012/05-08/32694648_1336466727_517.jpg" /></p>
<p>
	导演：金平中<br />
	&bull;演员：<br />
	柳时元 / 洪秀贤 / 朴志胤 / 安信源</p>
<p>
	&bull;类型：爱情 / 偶像 / 喜剧<br />
	&bull;首映：2012年5月7日 韩国<br />
	&bull;又名：&#44415;&#48148;&#51060; &#47560;&#45580;</p>
<p>
	&bull;点评： 温柔先生柳时元变拳击手,戏内外遭双重婚变打击--</p>
<p>
	<br />
	&bull;剧情： 《再见，老婆》讲述了一对已经结婚五年开始对彼此产生厌倦感的夫妇，并且因为各自偶遇难忘的旧情人而离婚，在幼稚和遇上各种有趣事件后才发觉对方是真爱的故事。丈夫车胜赫是刚刚结婚时深爱着妻子，但随着时间流逝早已没有了激情，只剩下责任感维持婚姻的男主人公。然而，妻子姜暄雅已经得知单纯还不成熟的丈夫梦想着和初恋情人重逢。于是两人一边同意离婚一边暗中留意对方的动态。一对另类夫妻造就了如此荒唐又浪漫的喜剧故事。</p>
<p>
	&bull; 花絮：目前正在与太太打离婚官司的柳时元与在新剧《再见，老婆》中饰演柳时元妻子的洪秀贤的婚纱剧曝光日前曝光。穿上西装后散发出&ldquo;王子&rdquo;般魅力的柳时元与五官艳丽的洪秀贤看起来十分相配。两人默契十足地摆出多个姿势， 看起来十分甜蜜、温馨。<br />
	遗憾的是，无论是这组婚纱剧照还是该剧的名字《再见，老婆》都对目前正与太太处于离婚诉讼阶段的柳时元来讲，都十分尴尬。网友也纷纷留言表示，这组婚纱剧照虽然看起来很幸福、很甜蜜，但同时又让人觉得很讽刺。</p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.netftp//dy44:piaohua@dy44.piaohua.com:3142/" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3385/飘花电影piaohua.com再见老婆EP01.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3385/飘花电影piaohua.com再见老婆EP01.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3385/飘花电影piaohua.com再见老婆EP02.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3385/飘花电影piaohua.com再见老婆EP02.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3423/飘花电影piaohua.com再见老婆EP03.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3423/飘花电影piaohua.com再见老婆EP03.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3432/飘花电影piaohua.com再见老婆EP04.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3432/飘花电影piaohua.com再见老婆EP04.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3475/飘花电影piaohua.com再见老婆EP05.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3475/飘花电影piaohua.com再见老婆EP05.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3482/飘花电影piaohua.com再见老婆EP06.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3482/飘花电影piaohua.com再见老婆EP06.rmvb</a></td>
		</tr>
	</tbody>
</table>
<p>
	&nbsp;</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1AQP-55155.jpg{/dede:field}
