<?php
$z[0]=Array("field","希望与反抗/索菲·绍尔最后的日",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","希望与反抗/索菲·绍尔最后的日子/帝国大审判[BD中英双字1024x576高清版]迅雷下载、免费下载，希望与反抗/索菲·绍尔最后的日子/帝国大审判[BD中英双字1024x576高清版]Gvod高清在线播放，剧情介绍等。",72,302);
$z[1][4]['name']="description";
$z[2]=Array("field","希望与反抗/索菲·绍尔最后的日子/帝国大审判[BD中英双字1024x576高清版]",304,410);
$z[2][4]['name']="title";
$z[3]=Array("field","",412,451);
$z[3][4]['name']="writer";
$z[4]=Array("field","",453,492);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-03-05",494,544);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",546,583);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://3e:3e@m1.3edyy.com:1389/【3E电影院www.3edyy.com】希望与反抗BD中英双字1024x576高清版.rmvb\" target=_blank>ftftp://3e:3e@m1.3edyy.com:1389/【3E电影院www.3edyy.com】希望与反抗BD中英双字1024x576高清版.rmvb</A></TD></TR></TBODY></TABLE></div><ul class=\"mmlist",585,883);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MP601940-16396.jpg",885,969);
$z[8][4]['name']="litpic";

?>