{dede:field name='keywords'}狱中豪杰/猛男奸狱BD中英双字128{/dede:field}
{dede:field name='description'}狱中豪杰/猛男奸狱BD中英双字1280高清迅雷下载、免费下载，狱中豪杰/猛男奸狱BD中英双字1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}狱中豪杰/猛男奸狱BD中英双字1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-05{/dede:field}
{dede:field name='body'}<p>
	<img src="http://pic.piaohua.com/0701pic/allimg/080810/0946310.jpg" /></p>
<p>
	【译　　名】《狱中豪杰/猛男奸狱》08最新喜剧大片DVD中字<br />
	【片　　名】Big Stan REPACK<br />
	【年　　代】2008<br />
	【国　　家】美国<br />
	【类　　别】喜剧<br />
	【语　　言】英语<br />
	【字　　幕】英文<br />
	【IMDB评分】6.6/10 (373 Votes)<br />
	【文件格式】XviD + MP3<br />
	【视频尺寸】640 x 352<br />
	【电影整理】3E迅雷电影下载站(www.eee4.com)<br />
	【文件大小】1CD 408MB<br />
	【片　　长】104 Min<br />
	【导　　演】罗伯&middot;施奈德 Rob Schneider<br />
	【主　　演】Tsuyoshi Abe&nbsp; .....Dang<br />
	　　　　　　T.J. Amato&nbsp; .....Waiter #1<br />
	　　　　　　Chris Astoyan&nbsp; .....Italian Inmate<br />
	　　　　　　Erik Betts&nbsp; .....Diamond King Gang Member<br />
	　　　　　　大卫&middot;卡拉丁 David Carradine<br />
	　　　　　　Randy Couture<br />
	　　　　　　Barbara Dodd&nbsp; .....Mrs. Darby<br />
	　　　　　　Federico Dordei&nbsp; .....Farib<br />
	　　　　　　Robert Flores&nbsp; .....Lil rob<br />
	　　　　　　Joseph Fossum-Perez&nbsp; .....Latino Gang Member<br />
	　　　　　　Don Frye<br />
	　　　　　　Kevin Gage&nbsp; .....Bullard</p>
<p>
	【简　　介】：</p>
<p>
	　　罗布是一个身体虚弱，讨人厌的肺病患者。在得知自己因为诈骗要被判入狱一段时间后，由于害怕在监狱里会受欺负<br />
	，于是他急忙寻求一个武师的帮助，在短时间内，速成了一些拳脚功夫。入狱以后，罗布因为有功夫在身，所以生活过得<br />
	很滋润，甚至还因为打败了敌对的狱中帮派而被奉为英雄&hellip;&hellip;3E迅雷<a href="/" target="_blank">电影下载</a>站</p>

<p>
	【电影截图】：<br />
	电影来源：www.eee4.com<br />
	<img src="http://pic.piaohua.com/0701pic/allimg/080810/0947150.jpg" />&nbsp;<br />
	<img src="http://pic.piaohua.com/0701pic/allimg/080810/0946471.jpg" />&nbsp;<br />
	<img src="http://pic.piaohua.com/0701pic/allimg/080810/0947250.jpg" />&nbsp;<br />
	<img src="http://pic.piaohua.com/0701pic/allimg/080810/0946582.jpg" /></p>
<p>
	08最新喜剧大片《狱中豪杰》DVD中字 －来自[3E迅雷电影站eee4.com]下载地址：<img border="0" src="/templets/img/down.jpg" /></p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<anchor></anchor><a href="ftp://eee4.com:8114@vip11.eee4.com:8114/[3E迅雷电影站www.eee4.com]狱中豪杰DVD中字.rmvb" target="_blank">ftp://eee4.com:8114@vip11.eee4.com:8114/[3E迅雷电影站www.eee4.com]狱中豪杰DVD中字.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<anchor></anchor><a href="ftp://dy44:piaohua@dy44.piaohua.com:3354/飘花电影piaohua.com猛男奸狱BD中英双字1280高清.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3354/飘花电影piaohua.com猛男奸狱BD中英双字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15I3940-3WT.jpg{/dede:field}
