{dede:field name='keywords'}唐山大地震/余震[DVD国语中字]迅{/dede:field}
{dede:field name='description'}唐山大地震/余震[DVD国语中字]迅雷下载、免费下载，唐山大地震/余震[DVD国语中字]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}唐山大地震/余震[DVD国语中字]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2010-07-27{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://7e:7e@m1.eee4.cc:1513/【3e电影网www.eee4.cc】唐山大地震DVD国语中字.rmvb" target=_blank>ftftp://7e:7e@m1.eee4.cc:1513/【3e电影网www.eee4.cc】唐山大地震DVD国语中字.rmvb</A></TD></TR></TBODY></TABLE></div><ul class="mmlist{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MPY20P-34923.jpg{/dede:field}
