{dede:field name='keywords'}冰河世纪1BD1280英粤台三语高清{/dede:field}
{dede:field name='description'}冰河世纪1BD1280英粤台三语高清版迅雷下载、免费下载，冰河世纪1BD1280英粤台三语高清版Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}冰河世纪1BD1280英粤台三语高清版{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-01-21{/dede:field}
{dede:field name='body'}<p>
	◎中文片名：《冰河世纪1》美国超经典喜剧动画大片DVD/BD1280高清版<br />
	◎英文片名：Ice Age<br />
	◎出品年代：2002<br />
	◎国家地区：美国<br />
	◎类　　别：动画/喜剧<br />
	◎片　　长：01:21:04<br />
	◎导　　演：Carlos Saldanha 克里斯威居<br />
	◎主要演员：Ray.Romano 约翰.莱格扎莫 丹尼斯.劳瑞 高兰.维斯耶克<br />
	◎简　　介：　<br />
	<br />
	　　故事围绕着三只冰河时期的史前动物和一个人类弃婴展开。<br />
	<br />
	　　冰河期使得动物们纷纷迁移寻找食物。心地善良的长毛象--曼菲德、嗜食的树獭--希德、狡猾的剑齿虎--迭哥，这三只性格迥异的动物为了使一个人类的小孩重返家园，竟然聚在了一起，组成了一只临时护送队，踏上了漫漫寻亲路。一路上这三只动物矛盾重生，迭哥心生毒计，想诱领队伍踏入自己族类设下的致命伏击，但在他们共同经历了雪崩、饥荒<a href="http://www.eee4.com/" target="_blank">迅雷电影下载</a>等无数险境之后，这些与严酷环境抗争的经历使迭哥开始对自己的计划动摇了&hellip;&hellip;<br />
	<br />
	【获奖记录】2003奥斯卡奖 最佳动画片提名</p>
<p>
	【电影截图】：<br />
	<br />
	<img alt="" border="0" height="360" src="http://img165.poco.cn/mypoco/myphoto/20120121/01/17870980201201210100122794113567330_008.jpg" width="640" /><img alt="" border="0" src="http://img165.poco.cn/mypoco/myphoto/20120121/01/17870980201201210100122794113567330_006.jpg" /></p>
<p>
	美国超经典喜剧动画大片《冰河世纪1》DVD国语中字无水印版 ：</p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://e14:e14@xl2.eee4.com:9219/[3E电影站www.eee4.com]冰河世纪1国语配音中文字幕无水印版.rmvb" target="_blank">ftp://e14:e14@xl2.eee4.com:9219/[3E电影站www.eee4.com]冰河世纪1国语配音中文字幕无水印版.rmvb</a></td>
		</tr>
	</tbody>
</table>
<p>
	美国超经典喜剧动画大片《冰河世纪1》BD英粤台三语中英双字1280&times;720版 ：</p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy241:xiaobajie@dy241.piaohua.com:2048/小八戒电影xiaobajie.com冰河世纪1英粤台三语720p.mkv" target="_blank">ftp://dy241:xiaobajie@dy241.piaohua.com:2048/小八戒电影xiaobajie.com冰河世纪1英粤台三语720p.mkv</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1B21030-23558.jpg{/dede:field}
