{dede:field name='keywords'}非洲猫科：勇气国度BD中英双字12{/dede:field}
{dede:field name='description'}非洲猫科：勇气国度BD中英双字1280高清2010纪录片迅雷下载、免费下载，非洲猫科：勇气国度BD中英双字1280高清2010纪录片Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}非洲猫科：勇气国度BD中英双字1280高清2010纪录片{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-10-29{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="/uploads/allimg/c120524/133N493YA0-J3S.jpg" /></p>

<p>
	◎译　　名　非洲猫科/非洲猫科：勇气国度/大猫<br />
	◎片　　名　African Cats<br />
	◎年　　代　2010<br />
	◎国　　家　美国<br />
	◎类　　别　纪录片/冒险<br />
	◎语　　言　英语<br />
	◎字　　幕　中英双字<br />
	◎IMDB评分 &nbsp; 7.0/10 (677 votes)<br />
	◎文件格式　X264 + DTS<br />
	◎视频尺寸　1280 x 720<br />
	◎片　　长　89 mins<br />
	◎导　　演　艾雷斯泰&middot;法瑟吉尔 &nbsp; Alastair Fothergill &nbsp; &nbsp;<br />
	　　　　　　基思&middot;斯科利 &nbsp; Keith Scholey<br />
	◎主　　演　塞缪尔&middot;杰克逊 Samuel L. Jackson ....Narrator (voice)<br />
	<br />
	<br />
	◎简 　 介<br />
	<br />
	&nbsp; &nbsp; 这部纪录片从更为人性化的角度来拍摄非洲猫科动物，用唯美和拟人化的角度，讲述了两个家庭、三只大型猫科动物关于爱的故事。<br />
	◎剧　　照　<br />
	<br />
	<img alt="" border="0" src="/uploads/allimg/c120524/133N49393250-SP0.jpg" /><br />
	<br />
	<img alt="" border="0" src="/uploads/allimg/c120524/133N493962Z-94912.jpg" /><br />
	<br />
	<img alt="" border="0" src="/uploads/allimg/c120524/133N493a5F-101E6.jpg" /><br />
	<br />
	<img alt="" border="0" src="/uploads/allimg/c120524/133N493c360-11T33.jpg" /><br />
	<br />
	<img alt="" border="0" src="/uploads/allimg/c120524/133N49401540-12K30.jpg" /><br />
	<br />
	<img alt="" border="0" src="/uploads/allimg/c120524/133N494035P-13VL.jpg" /><br />
	<br />
	<img alt="" border="0" src="/uploads/allimg/c120524/133N494055F-144501.jpg" /><br />
	<img alt="" src="/uploads/allimg/c120524/133N4940I30-151110.jpg" /></p>
<p>
	幕后制作<br />
	<br />
	　　讲述的愿望<br />
	<br />
	　　随着环境问题的进一步加剧，生态学纪录片的地位也越来越高。似乎这些并不仅仅是简单的纪录片，而是一种环境和自然通过导演向人类发出的一种召唤和悲鸣。那些拍摄生态学纪录片的人，可以说无一例外地都是环保人士。迪士尼自然出品的这部生态学纪录片就不仅仅是一部电影，它更是一个环保项目。迪士尼公司将从影片的收益中拿出一部分用于影片外景地的环保事业。<br />
	<br />
	　　影片的两位导演，艾雷斯泰&middot;法瑟吉尔和基思&middot;斯科利，都曾经担任过BBC自然及历史部的要职，80年代就进入BBC工作的他们曾经在著名的生态学纪录片制片人戴维&middot;爱丁保罗夫的手下工作。现在，爱丁保罗夫被世人尊称为博物学家，他以前的这两个手下也先后成为了生态学纪录片业内的顶尖制作人和导演。巧合的是，艾雷斯泰&middot;法瑟吉尔和基思&middot;斯科利都是动物学专业的学生，基思&middot;斯科利还在布里斯托尔大学拿到了自己的动物学博士学位。在本片之前，BBC、国家地理、探索都曾经从不同角度拍摄过大量的非洲猫科动物的纪录片，谈及为什么要跑到肯尼亚，重新拍摄一部讲述猫科动物的纪录片时，艾雷斯泰&middot;法瑟吉尔说：&ldquo;之前的很多纪录片都侧重于科学方面的讲述，比如说猫科动物的食性、它们的咬合力、生态学理论、行为学意义等等。这些纪录片都很优秀，但是少了一些人情味和人性。也就是说，我们以前的纪录片侧重于展示和呈现，而忽略了表达。这些大型猫科动物可会有自己的情感和生活，那么我们为什么不从更为人性化一些的角度来展示它们的生活呢？&rdquo;基思&middot;斯科利说：&ldquo;这就是我们拍摄这部电影的原因，因为我们有这么一种讲述和表达的愿望。我们希望更多的人能从动物世界里看到它们与人类相通的地方，看到那些故事性、情感性、甚至是历史化的内容。而不仅仅只是看到诸如它们在猎食、它们在繁衍、它们在争夺地盘这种行为上的东西。我希望人们能真正理解动物，真正理解动物的情感。&rdquo;<br />
	<br />
	　　狂野非洲<br />
	<br />
	　　影片全片在肯尼亚的马赛玛拉国家公园拍摄，这里是一片稀树大草原。特殊的地理、气候条件造就了这里独一无二的动物种群。在影片长达两周年的拍摄期间，摄制组遇到了很多发生在非洲大陆上的&ldquo;动物奇观&rdquo;，譬如非洲水牛的大规模迁徙、雨季中大大小小的沼泽和水栖爬行动物、各种各样的鸟类等等。<br />
	<br />
	　　对于这样两位生态学纪录片的行家里手来说，这种场面早就屡见不鲜。但是，每当自然界的奇观展示在自己面前的时候，他们还是会惊叹不已。艾雷斯泰&middot;法瑟吉尔说：&ldquo;非洲是一片神奇的土地，每时每刻你都能在镜头里发现令人惊叹的事物。尤其在雨季来临的时候，各种各样的动物都出出现在这片土地上。我认为，每一种动物都有自己的故事，而我们拍摄的不过是千千万万个故事中的一个而已。&rdquo;基思&middot;斯科利则认为他们在两年的拍摄期间已经和动物建立起了难以割舍的情感。他说：&ldquo;当我们来到马赛玛拉，找到药拍摄对象的时候，事情和电影里展示出来的一点都不一样。玛拉那时候还没有出生，它的妈妈还是狮群中的一个既有捕猎技巧的母狮子。后来，她生下了玛拉，自己负了伤。这一家人的生活就相当困难了。整个狮群的首领是毒牙，但是它已经老了。自然界优胜劣汰的原则是亘古不变的，它总会被取代、它的地盘和狮群总是会有新的统治者。所以总会有狮群在觊觎他的地位。这是一场可以说惨烈的大换血，但也是必然的。最后一个家庭是一个猎豹的家庭，我们记录了小猎豹从出生到成熟的全过程。这部电影的主要内容，是讲述了两个家庭、两个母亲的选择。它们都要保护自己的孩子，也都在自然界中挣扎着生存。&rdquo;<br />
	<br />
	　　按照法瑟吉尔的观点，影片用了一种唯美和拟人化的角度，讲述了一个关于爱的故事。他说：&ldquo;我们把力量聚焦在动物身上，让人们看完电影之后由衷地去喜爱它们。我们没有在影片中过多地渲染什么环境污染问题和环保话题，因为在电影结束后，观众肯定会不自觉地想到这些问题的。&rdquo;<br />
	<br />
	　　花　絮<br />
	<br />
	&middot;影片的上映日期是4月22日，这一天是世界地球日。本片导演艾雷斯泰&middot;法瑟吉尔参与执导的另一部生态学纪录片《地球》也曾于2009年的世界地球日在美国上映。<br />
	<br />
	&middot;两位导演在刚刚进入BBC工作的时候，都曾经在著名生态学纪录片制片人戴维&middot;爱丁保罗夫的手下工作过。艾雷斯泰&middot;法瑟吉尔担任过爱丁保罗夫的制片人，而基思&middot;斯科利则是他的研究员。<br />
	<br />
	&middot;当艾雷斯泰&middot;法瑟吉尔还是学生的时候，他就已经拍摄出了自己的第一部电影《在奥卡万戈》（On the Okavango）。奥卡万戈在非洲的博茨瓦纳，是一条河流。它冲击形成的奥卡万戈沼泽是世界上最大的内陆三角洲。<br />
	<br />
	&middot;本片是基思&middot;斯科利的导演处女作。<br />
	<br />
	&middot;影片于2008年8月到2010年10月在肯尼亚拍摄</p>
<p>
	<img alt="" src="/uploads/allimg/c120524/133N49409130-163346.jpg" /></p>
<p>
	&nbsp;<img alt="" src="/uploads/allimg/c120524/133N494095Z-1O505.jpg" /></p>

<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="/uploads/allimg/c120524/133N2Z4FF-102231.jpg" />&nbsp;&nbsp;&nbsp;
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				&nbsp;&nbsp;ftp://dy44:piaohua@dy44.piaohua.com:1943/飘花电影piaohua.com非洲猫科：勇气国度BD中英双字1280高清.rmvb&nbsp;</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120524/133N4940cF-1YG1.jpg{/dede:field}
