
   {dede:match}<div id="showinfo">[ÄÚÈİ]ÏÂÔØµØÖ·{/dede:match}
   {dede:trim replace=''}<a([^>]*)>{/dede:trim}
{dede:trim replace=''}</a>{/dede:trim}
{dede:trim replace=''}<font([^>]*)>{/dede:trim}
{dede:trim replace=''}</font>{/dede:trim}
{dede:trim replace=''}<div([^.]*)>{/dede:trim}
{dede:trim replace=''}</div>{/dede:trim}
{dede:trim replace=''}<strong([^>]*)>{/dede:trim}
{dede:trim replace=''}</strong>{/dede:trim}
{dede:trim replace=''}<span([^>]*)>{/dede:trim}
{dede:trim replace=''}</span>{/dede:trim}
{dede:trim replace=''}[{/dede:trim}
{dede:trim replace=''}¡¾{/dede:trim}
   {dede:function}{/dede:function}
