{dede:field name='keywords'}今晚80后说相声HD国语中字1024高{/dede:field}
{dede:field name='description'}今晚80后说相声HD国语中字1024高清迅雷下载、免费下载，今晚80后说相声HD国语中字1024高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}今晚80后说相声HD国语中字1024高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-10-03{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="/uploads/allimg/c120524/133N49415K0-239353.jpg" /></p>
<p>
	[下载地址]：<img border="0" src="/uploads/allimg/c120524/133N2ZL930-142957.jpg" /></p>


<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				ftp://dy44:piaohua@dy44.piaohua.com:1716/飘花电影piaohua.com今晚80后说相声HD国语中字1024高清.rmvb</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120524/133N49415K0-239353.jpg{/dede:field}
