{dede:field name='keywords'}藏獒多吉DVD国语中字中国大陆动{/dede:field}
{dede:field name='description'}藏獒多吉DVD国语中字中国大陆动画剧情爱情迅雷下载、免费下载，藏獒多吉DVD国语中字中国大陆动画剧情爱情Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}藏獒多吉DVD国语中字中国大陆动画剧情爱情{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-08-18{/dede:field}
{dede:field name='body'}<p>
	<img alt="点击查看下一张" border="0" src="/uploads/allimg/c120524/133N42355H0-14S15.gif" style="background-image: url(http://img2081.poco.cn/mypoco/myphoto/20110818/10/62821378201108181044193376056520649_004_640.jpg); width: 353px; height: 431px" /></p>
<p>
	<img alt="点击查看下一张" border="0" src="/uploads/allimg/c120524/133N42355H0-14S15.gif" style="background-image: url(http://img2081.poco.cn/mypoco/myphoto/20110818/10/62821378201108181044193376056520649_003_640.jpg); width: 290px; height: 565px" /></p>
<p>
	中文名：&nbsp;&nbsp;&nbsp;&nbsp; 藏獒多吉<br />
	外文名：&nbsp;&nbsp;&nbsp;&nbsp; THE TIBETAN DOG<br />
	出品时间：&nbsp;&nbsp;&nbsp;&nbsp; 2011年<br />
	出品公司：&nbsp;&nbsp;&nbsp; 中国电影股份有限公司等<br />
	制片地区：&nbsp;&nbsp;&nbsp;&nbsp; 中国大陆<br />
	导演：&nbsp;&nbsp;&nbsp; 小岛正幸<br />
	编剧：&nbsp;&nbsp;&nbsp;&nbsp; 根据杨志军小说《藏獒》改编<br />
	制片人：&nbsp;&nbsp;&nbsp; 丸山正雄<br />
	主演：&nbsp;&nbsp;&nbsp; 田劲 拉格巴等<br />
	类型：&nbsp;&nbsp;&nbsp;&nbsp; 动画，剧情、爱情<br />
	上映时间：&nbsp;&nbsp;&nbsp;&nbsp; 2011.06.28<br />
	地位：&nbsp;&nbsp;&nbsp;&nbsp; 中日合拍首部动画影片</p>
<p>
	<br />
	剧情介绍：故事发生在很早以前的青藏高原上。少年田劲来到藏区草原投靠父亲，一切都是那么陌生。直到有一天，一只好像从天而降的金色毛发的藏獒出现在他面前&hellip;&hellip;草原上接连发生莫名的事件，连少年田劲与那只藏獒都被卷入其中。在众人的猜疑背后，似乎还有更神秘的情形。那只金色毛发的藏獒究竟在寻找什么？雪山高原上会上演怎样惊天的传奇故事？<br />
	　影片根据销量百万的同名小说改编，故事讲述的是10岁的汉藏混血儿田劲因为母亲病亡，只好奔赴藏区投靠生疏的父亲拉格巴。一天，田劲在草原救了一只金黄色的&ldquo;外来&rdquo;藏獒，田劲将它起名&ldquo;多吉雍直&rdquo;，开始一起生活。然而好景不长，草原上相续出现了人畜遇袭的案件。多吉被误认为凶手，田劲带着多吉雍直一路逃奔，最终来到了雪山。在那里，他们遇到了真正的凶手，真正的战斗才拉开序幕</p>

<p>
	<img alt="点击查看下一张" border="0" src="/uploads/allimg/c120524/133N42355H0-14S15.gif" style="background-image: url(http://img2081.poco.cn/mypoco/myphoto/20110818/10/62821378201108181044193376056520649_002_640.jpg); width: 632px; height: 315px" /></p>
<p>
	&nbsp;<img alt="点击查看下一张" border="0" src="/uploads/allimg/c120524/133N42355H0-14S15.gif" style="background-image: url(http://img2081.poco.cn/mypoco/myphoto/20110818/10/62821378201108181044193376056520649_001_640.jpg); width: 630px; height: 316px" /></p>
<p>
	<img alt="点击查看下一张" border="0" src="/uploads/allimg/c120524/133N42355H0-14S15.gif" style="background-image: url(http://img2081.poco.cn/mypoco/myphoto/20110818/10/62821378201108181044193376056520649_000_640.jpg); width: 631px; height: 318px" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="/uploads/allimg/c120524/133N2Z4FF-102231.jpg" />&nbsp;&nbsp;&nbsp;
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				&nbsp;&nbsp;ftp://dy44:piaohua@dy44.piaohua.com:1326/飘花电影piaohua.com藏獒多吉DVD国语中字.rmvb</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O04N260-1L2V.jpg{/dede:field}
