{dede:field name='keywords'}叛军/秩序和道德DVD中字2011法国{/dede:field}
{dede:field name='description'}叛军/秩序和道德DVD中字2011法国动作迅雷下载、免费下载，叛军/秩序和道德DVD中字2011法国动作Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}叛军/秩序和道德DVD中字2011法国动作{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-04-22{/dede:field}
{dede:field name='body'}<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120422/14/56643687201204221432212777603145303_000.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 814px; border-top: 0px solid; border-right: 0px solid" /></p>
<p>
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120422/14/56643687201204221432212777603145303_001.jpg" /></p>
<p>
	◎译　　名　叛军/秩序和道德<br />
	◎片　　名　L&#39;ordre et la morale/Rebellion<br />
	◎年　　代　2011<br />
	◎国　　家　法国<br />
	◎类　　别　动作/历史<br />
	◎语　　言　法语<br />
	◎字　　幕　中文<br />
	◎上映日期 2011年11月16日<br />
	◎IMDB评分 Ratings: 7.2/10 from 281 users<br />
	◎IMDB链接 <a href="http://www.imdb.com/title/tt1242521/">http://www.imdb.com/title/tt1242521/</a><br />
	◎文件格式　DVD-RMVB<br />
	◎视频尺寸　720 x 404<br />
	◎文件大小　1CD 728MB<br />
	◎片　　长　2h 9mn<br />
	◎导　　演　马修&middot;卡索维茨 Mathieu Kassovitz<br />
	◎主　　演　马修&middot;卡索维茨 Mathieu Kassovitz<br />
	　　　　　　西尔薇&middot;泰斯图德 Sylvie Testud<br />
	　　　　　　亚历山大&middot;斯泰格尔 Alexandre Steiger<br />
	　　　　　　Daniel Martin<br />
	菲利普&middot;托雷顿 Philippe Torreton<br />
	Steeve Une<br />
	Philippe de Jacquelin Dulph&eacute;<br />
	Patrick Fierry<br />
	Jean-Philippe Puymartin<br />
	马立克&middot;兹迪 Malik Zidi</p>
<p>
	◎剧 情</p>
<p>
	　1988年4月，（法属）新喀里多尼亚的乌维阿岛。30名警察被卡纳克人要求独立的组织挟持为人质。法国派出300名军人去恢复秩序。2个男人面对面：法国国家宪兵特勤队的队长菲利普&middot;勒高裘和挟持人质的首脑阿尔方斯&middot;迪亚努。通过两人共同的价值观，他们尝试着通过对话来解决问题。但当时正值总统大选，当关键挑战都是政治方面时，秩序并不总是由道德来支配&hellip;&hellip;</p>

<p>
	◎影片截图</p>


<p>
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120422/14/56643687201204221432212777603145303_004.jpg" /></p>
<p>
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120422/14/56643687201204221432212777603145303_003.jpg" /></p>
<p>
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120422/14/56643687201204221432212777603145303_002.jpg" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.netftp//dy44:piaohua@dy44.piaohua.com:3125/" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3271/飘花电影piaohua.com秩序和道德DVD中字.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3271/飘花电影piaohua.com秩序和道德DVD中字.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15630920-45456.jpg{/dede:field}
