<?php
$z[0]=Array("field","史瑞克的万圣游戏[BD中英双字102",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","史瑞克的万圣游戏[BD中英双字1024/1280高清版]迅雷下载、免费下载，史瑞克的万圣游戏[BD中英双字1024/1280高清版]Gvod高清在线播放，剧情介绍等。",73,253);
$z[1][4]['name']="description";
$z[2]=Array("field","史瑞克的万圣游戏[BD中英双字1024/1280高清版]",255,336);
$z[2][4]['name']="title";
$z[3]=Array("field","",338,377);
$z[3][4]['name']="writer";
$z[4]=Array("field","",379,418);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-10-28",420,470);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",472,509);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://6e:6e@m3.3edyy.com:501/【3E看看www.3ekk.com】史瑞克的万圣游戏[BD中英双字1024x576高清版].rmvb\" target=\"_blank",511,664);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MQ20A50-461S.jpg",666,748);
$z[8][4]['name']="litpic";

?>