<?php
$z[0]=Array("field","法拉利-国家地理-超级工厂[DVD中",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","法拉利-国家地理-超级工厂[DVD中英双字1024x576高清版]迅雷下载、免费下载，法拉利-国家地理-超级工厂[DVD中英双字1024x576高清版]Gvod高清在线播放，剧情介绍等。",73,269);
$z[1][4]['name']="description";
$z[2]=Array("field","法拉利-国家地理-超级工厂[DVD中英双字1024x576高清版]",271,360);
$z[2][4]['name']="title";
$z[3]=Array("field","",362,401);
$z[3][4]['name']="writer";
$z[4]=Array("field","",403,442);
$z[4][4]['name']="source";
$z[5]=Array("field","2009-01-14",444,494);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",496,533);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://e20:e20@xl2.eee4.com:9916/[3E电影站www.eee4.com]超级工厂：法拉利[DVD中英双字1024x576高清版].rmvb\" target=_blank>ftftp://e20:e20@xl2.eee4.com:9916/[3E电影站www.eee4.com]超级工厂：法拉利[DVD中英双字1024x576高清版].rmvb</A></TD></TR></TBODY></TABLE></div><ul class=\"mmlist",535,849);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MP45R20-51S6.jpg",851,933);
$z[8][4]['name']="litpic";

?>