{dede:field name='keywords'}人猿星球BD中英双字1280高清经典{/dede:field}
{dede:field name='description'}人猿星球BD中英双字1280高清经典科幻迅雷下载、免费下载，人猿星球BD中英双字1280高清经典科幻Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}人猿星球BD中英双字1280高清经典科幻{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-12-18{/dede:field}
{dede:field name='body'}<p>
	<img alt="" height="486" src="http://img165.poco.cn/mypoco/myphoto/20111213/23/57196343201112132259135894714691448_037.jpg" width="380" /></p>
<p>
	【译　　名】　人猿星球<br />
	【片　　名】　Planet of the Apes<br />
	【年　　代】　1968<br />
	【国　　家】　美国<br />
	【类　　别】　科幻/动作/剧情<br />
	【语　　言】　英语<br />
	【字幕语言】中文/英文<br />
	【视频尺寸】1280&times;720<br />
	【文件格式】RMVB+AAC<br />
	【IMDB评分】&nbsp;&nbsp;8.0/10(55,862votes)<br />
	【导　　演】　富兰克林&middot;J&middot;沙夫纳<br />
	【主　　演】　Charlton Heston .... George Taylor<br />
	　　　　　　&nbsp; &nbsp;Roddy McDowall .... Cornelius<br />
	　　　　　　&nbsp; &nbsp;Kim Hunter .... Zira<br />
	　　　　　　&nbsp; &nbsp;Maurice Evans .... Dr. Zaius<br />
	　　　　　　&nbsp; &nbsp;James Whitmore .... President of the Assembly<br />
	　　　　　　&nbsp; &nbsp;James Daly .... Dr. Honorious<br />
	　　　　　　&nbsp; &nbsp;Linda Harrison .... Nova<br />
	　　　　　　&nbsp; &nbsp;Robert Gunner .... Landon<br />
	　　　　　　&nbsp; &nbsp;Lou Wagner .... Lucius<br />
	　　　　　　&nbsp; &nbsp;Woodrow Parfrey .... Dr. Maximus<br />
	　　　　　　&nbsp; &nbsp;Jeff Burton .... Dodge<br />
	　　　　　　&nbsp; &nbsp;Buck Kartalian .... Julius<br />
	　　　　　　&nbsp; &nbsp;Norman Burton .... Leader of the hunt<br />
	　　　　　　&nbsp; &nbsp;Wright King .... Dr. Galen<br />
	　　　　　　&nbsp; &nbsp;P<a href="http://www.qqtmb.com/" style="color: rgb(0, 0, 0); text-decoration: none;">Qq</a>aul Lambert .... Minister<br />
	【简　　介】　<br />
	&nbsp; &nbsp;&nbsp;&nbsp;人猿世界是一部具有深刻蕴意的科幻影片，它的结尾被认为是最伟大的构思。影片描述泰勒（海斯顿饰）在太空船里一觉醒来后，着陆在一个陌生的星球上。他发现在这个星球上居住的人类已经变得和动物没什么区别。而类人猿成了这里的统治者。他吃惊地发现这个星球上的猿类有着和人类相近的等级制度，人猿是统治者，猩猩是居中阶层而黑猩猩则是地位最低下的族群。泰勒和人猿科学家吉拉（亨特饰）、考耐利斯（罗迪饰）交上了朋友，但他却受到人猿博士赞斯（毛利斯饰）的百般迫害。最后泰勒<a style="color: rgb(0, 0, 0); text-decoration: none;" href="http://www.112cn.com/">偏方</a>逃出了人猿的控制，但他走在海滩上突然看到了坍塌的自由女神像！原来这个被人猿统治的星球正是多年以后的地球。人类的核大战在很久以前<a href="http://www.anzhuo4.com/" style="color: rgb(0, 0, 0); text-decoration: none;">安卓</a>将一切化为乌有，而大自然在重新进化过程中开了个荒唐的玩笑...<br />
	<img alt="" height="337" src="http://img165.poco.cn/mypoco/myphoto/20111213/23/57196343201112132259135894714691448_036.jpg" style="cursor: pointer" width="600" /><br />
	&nbsp;</p>
<p>
	[下载地址]： &nbsp;<img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" /></p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2362/飘花电影piaohua.com人猿星球BD中英双字1280高清.rmvb ">&nbsp;ftp://dy44:piaohua@dy44.piaohua.com:2362/飘花电影piaohua.com人猿星球BD中英双字1280高清.rmvb </a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15X1220-34957.jpg{/dede:field}
