<?php
$z[0]=Array("field","辛普森一家/辛普森大电影/辛普森",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","辛普森一家/辛普森大电影/辛普森家庭BD中英双字1280高清迅雷下载、免费下载，辛普森一家/辛普森大电影/辛普森家庭BD中英双字1280高清Gvod高清在线播放，剧情介绍等。",73,271);
$z[1][4]['name']="description";
$z[2]=Array("field","辛普森一家/辛普森大电影/辛普森家庭BD中英双字1280高清",273,363);
$z[2][4]['name']="title";
$z[3]=Array("field","",365,404);
$z[3][4]['name']="writer";
$z[4]=Array("field","",406,445);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-12-21",447,497);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",499,536);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://3e:3e@www2.eee4.com:196/[3E电影站www.eee4.com]辛普森一家DVD国语中字无水印.rmvb\" target=\"_blank",538,677);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MQ22X60-23K3.jpg",679,761);
$z[8][4]['name']="litpic";

?>