{dede:field name='keywords'}青蛙公主日韩剧6迅雷下载，免费{/dede:field}
{dede:field name='description'}青蛙公主日韩剧6迅雷下载、免费下载，青蛙公主日韩剧6Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}青蛙公主日韩剧6{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-19{/dede:field}
{dede:field name='body'}<p>
	<img src="http://img.funshion.com/attachment/new_images/2012/03-26/31420354_1332744191_637.jpg" width="650" /></p>
<p>
	<img src="http://img.funshion.com/attachment/new_images/2012/03-26/31420354_1332744193_970.jpg" width="650" /></p>
<p>
	导演：田中亮 / 西坂瑞城 / 光野道夫</p>
<p>
	&bull;演员：<br />
	天海祐希 / 石田ゆり子</p>
<p>
	&bull;类型：爱情<br />
	&bull;首映：2012年4月12日 日本<br />
	&bull;又名：カエルの王女さま</p>
<p>
	&bull;点评： 天海佑希真正最强不是做BOSS,而是唱歌,作为宝冢TOP的她今次回归本业-<br />
	&bull; 剧情： 天海佑希接拍了4月12日开播的富士台新剧《青蛙公主》，讲述一位在美国百老汇遭受挫折的音乐剧女演员，回国以后拯救一个面临解散的由妈妈桑们组成的香颂歌剧团的故事。在剧中她将和一群当地的失业主妇组建合唱团，这还是天海佑希继1995年退出宝冢剧团后，第一次在电视剧中饰演音乐剧演员。天海女王的角色一如既往的伟岸，让我们一起期待这部充满搞笑...</p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.netftp//dy44:piaohua@dy44.piaohua.com:3201/" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3224/飘花电影piaohua.com青蛙公主EP01.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3224/飘花电影piaohua.com青蛙公主EP01.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3264/飘花电影piaohua.com青蛙公主EP02.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3264/飘花电影piaohua.com青蛙公主EP02.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3309/飘花电影piaohua.com青蛙公主EP03.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3309/飘花电影piaohua.com青蛙公主EP03.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3353/飘花电影piaohua.com青蛙公主EP04.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3353/飘花电影piaohua.com青蛙公主EP04.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3403/飘花电影piaohua.com青蛙公主EP05.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3403/飘花电影piaohua.com青蛙公主EP05.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3456/飘花电影piaohua.com青蛙公主EP06.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3456/飘花电影piaohua.com青蛙公主EP06.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1A5U40-44H1.jpg{/dede:field}
