{dede:field name='keywords'}大侦探福尔摩斯2：诡影游戏BD128{/dede:field}
{dede:field name='description'}大侦探福尔摩斯2：诡影游戏BD1280高清迅雷下载、免费下载，大侦探福尔摩斯2：诡影游戏BD1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}大侦探福尔摩斯2：诡影游戏BD1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-04-17{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120416/13/62564813201204161340562466878195507_000.jpg" style="width: 700px; height: 880px" /></p>
<p>
	◎译　　名&nbsp; 大侦探福尔摩斯2：诡影游戏/大侦探福尔摩斯2/福尔摩斯：诡影游戏(台)/神探福尔摩斯：诡影游戏(港)<br />
	◎片　　名　Sherlock Holmes: A Game of&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br />
	◎年　　代　2011<br />
	◎国　　家　美国<br />
	◎类　　别　动作/悬疑/冒险/犯罪/惊悚<br />
	◎语　　言　英语<br />
	◎字　　幕&nbsp;&nbsp;&nbsp; 中字<br />
	◎IMDB评分&nbsp; 7.7/10 from 78,803 users<br />
	◎IMDB链接&nbsp; <a href="http://www.imdb.com/title/tt1515091">http://www.imdb.com/title/tt1515091</a><br />
	◎文件格式　XviD + AC3<br />
	◎视频尺寸&nbsp; 1280&nbsp;x 720<br />
	◎文件大小　1CD 1.26GB<br />
	◎片　　长　128 Mins<br />
	◎导　　演　盖&middot;里奇 Guy Ritchie&nbsp;<br />
	◎主　　演　小罗伯特&middot;唐尼 Robert Downey Jr.&nbsp; &hellip;.Sherlock Holmes&nbsp;&nbsp;<br />
	　　　　　　裘德&middot;洛 Jude Law&nbsp; &hellip;.Dr. John Watson&nbsp;&nbsp;<br />
	　　　　　　劳米&middot;拉佩斯 Noomi Rapace&nbsp; &hellip;.Madam Simza Heron&nbsp;<br />
	　　　　　　瑞秋&middot;麦克亚当斯 Rachel McAdams&nbsp; &hellip;.Irene Adler&nbsp;<br />
	　　　　　　杰瑞德&middot;哈里斯 Jared Harris&nbsp; &hellip;.Professor James Moriarty&nbsp;<br />
	　　　　　　斯蒂芬&middot;弗雷 Stephen Fry&nbsp; &hellip;.Mycroft Holmes&nbsp;&nbsp;&nbsp;</p>

<p>
	◎简　　介　</p>
<p>
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 　　　无论是什么时候，福尔摩斯都是这个世界上最聪明的人，可是距离上个案件结束后6个月，却出现了一个在智力上和福尔摩斯相当的恶棍：莫里亚蒂教授。除了有一</p>
<p>
	个聪明的脑袋外，莫里亚蒂还是一个没有良心和道德的人，这让福尔摩斯陷入了重重的危机。<br />
	　　澳洲皇储突然死亡，虽然莱丝楚德督查在调查之 后认为皇储是自杀的，但是福尔摩斯却认为皇储是一起谋杀案的遇害者。这起震惊世人的谋杀案其实只是莫里亚蒂教授开始自</p>
<p>
	己的黑暗统治的前奏曲而已。发现了凶手蛛丝马迹的福尔摩斯顺着线索追寻了下去，没想到这个线索把他带到了一家小酒馆中。前些年，他和自己的兄长以及华生在这里庆祝过华</p>
<p>
	生的最后一个单身汉之夜。<br />
	　　在这间小酒馆里，福尔摩斯碰到了西姆，她是一个吉普赛的占星巫师，她看到了谋杀案的发生，但是她并没有把一切都告诉福尔摩斯，因为她的占星术使她变成了莫里亚蒂教</p>
<p>
	授的下一个谋杀对象。为了保护住自己的证人，福尔摩斯开始负责其西姆的安全，作为回报西姆则答应要帮助福尔摩斯破案。<br />
	　　一路顺着线索追寻下去的福尔摩斯、西姆和华生穿越了欧洲大陆，从英国来到了法国、德国，最后停在了瑞士。但是莫里亚蒂教授似乎知道福尔摩斯的行踪一般，每次都能提</p>
<p>
	前加害一个无辜者，然后先福尔摩斯一步逃之夭夭。无形之中，他编织出了一张死亡名单，如果他一旦成功，历史将被永久地改写，那么福尔摩斯能成功地阻止莫里亚蒂教授的下</p>
<p>
	一起谋杀案么？</p>
<p>
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120416/09/62564813201204161002031039483420407_003.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120416/09/62564813201204161002031039483420407_002.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120416/09/62564813201204161002031039483420407_001.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120416/09/62564813201204161002031039483420407_000.jpg" style="width: 720px; height: 405px" /></p>
<p>
	【下载地址】</p>
<table bgcolor="#0099cc" border="0" cellpadding="10" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.net" target="_blank">http://www.xiaozhizhu.net</a>&nbsp; <a href="thunder://QUFodHRwOi8vcGljLjY2dm9kLm5ldDo4ODgvMi/lpKfkvqbmjqLnpo/lsJTmkanmlq8yWzEwODBwXUJUK+Wtl+W5lS5yYXJaWg==">大侦探福尔摩斯2[1080p]BT+字幕</a></td>
		</tr>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy125:piaohua@dy125.piaohua.com:7861/飘花电影piaohua.com大侦探福尔摩斯2BD中字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:7861/飘花电影piaohua.com大侦探福尔摩斯2BD中字1280高清.rmvb</a></td>
		</tr>
		<tr>
		</tr>
	</tbody>
</table>
<br />{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1561G30-41264.jpg{/dede:field}
