{dede:field name='keywords'}教父1[BD中英双字1024/1280高清{/dede:field}
{dede:field name='description'}教父1[BD中英双字1024/1280高清版]迅雷下载、免费下载，教父1[BD中英双字1024/1280高清版]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}教父1[BD中英双字1024/1280高清版]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-01-18{/dede:field}
{dede:field name='body'}<p>
	【译　　名】《教父1》美国超经典高分动作大片DVD中英双字1024x576高清版<br />
	【片　　名】The Godfather<br />
	【年　　代】1972<br />
	【国　　家】美国<br />
	【类　　别】动作/剧情/惊悚<br />
	【语　　言】英语<br />
	【字　　幕】中英双字<br />
	【IMDB评分】9.1/10 (318,224 votes)<br />
	【文件格式】X264 + AC3<br />
	【片　　长】177 Mins<br />
	【导　　演】弗朗西斯&middot;福特&middot;科波拉 Francis Ford Coppola<br />
	【主　　演】马龙&middot;白兰度 Marlon Brando .... Don Vito Corleone<br />
	　　　　　　阿尔&middot;帕西诺 Al Pacino .... Michael Corleone<br />
	　　　　　　罗伯特&middot;杜瓦尔 Robert Duvall .... Tom Hagen<br />
	　　　　　　黛安娜&middot;基顿 Diane Keaton .... Kay Adams<br />
	　　　　　　詹姆斯&middot;凯恩 James Caan .... Sonny Corleone<br />
	　　　　　　约翰&middot;凯泽尔 John Cazale .... Fredo<br />
	　　　　　　索菲娅&middot;科波拉 Sofia Coppola .... Michael Francis Rizzi (uncredited)<br />
	　　　　　　斯特林&middot;海登 Sterling Hayden .... Capt. McCluskey<br />
	　　　　　　塔里亚&middot;希雷 Talia Shire .... Connie<br />
	　　　　　　阿贝&middot;维高达 Abe Vigoda .... Sal Tessio<br />
	　　　　　　Richard Conte .... Barzini<br />
	　　　　　　Ron Gilbert .... Usher in bridal party (uncredited)<br />
	　　　　　　Rudy Bond .... Cuneo<br />
	　　　　　　理查德&middot;布赖特 Richard Bright .... Al Neri<br />
	　　　　　　理查德&middot;卡斯特尔诺 Richard S. Castellano .... Clemenza</p>
<p>
	【简　　介】：　</p>
<p>
	　　1945年夏天，美国本部黑手党科莱昂家族首领，&ldquo;教父&rdquo;维托&middot;唐&middot;科莱昂为小女儿康妮举行了盛大的婚礼。&ldquo;教父&rdquo;有三个儿子：好色的长子逊尼，懦弱的次子弗雷德和刚从二战战场回来的小儿子迈克。其中逊尼是&ldquo;教父&rdquo;的得力助手；而迈克虽然精明能干，却对家族的&ldquo;事业&rdquo;没什么兴趣。</p>
<p>
	　　&ldquo;教父&rdquo;是黑手党首领，常干违法的构当。但同时他也是许多弱小平民的保护神，深得人们爱戴。他还有一个准则就是决不贩毒害人。为此他拒绝了毒枭素洛佐的要求，并因此激化了与纽约其它几个黑手党家族的矛盾。圣诞前夕，素洛佐劫持了&ldquo;教父&rdquo;的大女婿汤姆，并派人暗杀&ldquo;教父&rdquo;。&ldquo;教父&rdquo;中枪入院。素洛佐要汤姆设法使逊尼同意毒品买卖，重新谈判。逊尼有勇无谋，他发誓报仇，却无计可施。</p>
<p>
	　　迈克去医院探望父亲，他发现保镖已被收买，而警方亦和素洛佐串通一气。各家族间的火并一触即发。迈克制定了一个计策诱使素洛佐和警长前来谈判。在一家小餐馆内，迈克用事先藏在厕所内的手枪击毙了素洛佐和警长。</p>
<p>
	　　迈克逃到了西西里，在那里他娶了美丽的阿波萝妮亚为妻，过着田园诗般的生活。而此时，纽约各个黑手党家族间的仇杀却越来越激烈。逊尼也被康妮的丈夫卡洛出卖，被人打得千疮百孔。&ldquo;教父&rdquo;伤愈复出，安排各家族间的和解。听到噩耗的迈克也受到了袭击。被收买的保镖法布里奇奥在迈克的车上装了炸弹。迈克虽幸免于难，却痛失爱妻。</p>
<p>
	　　迈克于1951年回到了纽约，并和前女友凯结了婚。日益衰老的&ldquo;教父&rdquo;将家族首领的位置传给了迈克。在&ldquo;教父&rdquo;病故之后，迈克开始了酝酿已久的复仇。他派人刺杀了另两个敌对家族的首领，并亲自杀死了谋害他前妻的法布里奇奥。同时他也命人杀死了卡洛，为逊尼报了仇。</p>
<p>
	　　仇敌尽数剪除。康妮因为丈夫被杀而冲进了家门，疯狂地撕打迈克。迈克冷峻地命人把康妮送进了疯人院。他已经成了新一代的&ldquo;教父&rdquo;&mdash;&mdash;唐&middot;科莱昂。电影编辑整理：(www.eee4.com)</p>
<p>
	<br />
	【一句话评论】：</p>
<p>
	影片中的伟大角色和配乐实在令人难忘。 &mdash;&mdash;《奥斯汀纪事》</p>
<p>
	科波拉打造的经久不衰而无可置疑的杰作。 &mdash;&mdash;《旧金山纪事》</p>
<p>
	一部让人温故知新的电影。 &mdash;&mdash;BBC</p>
<p>
	<br />
	【幕后制作】：</p>
<p>
	　　把马里奥&middot;普佐虚构的纽约黑手党塑造成一个实现美国梦的家族奋斗史，这是科波拉最了不起的地方。影片从40年代末着手往后叙述，极具宏伟的史诗气派，同时又有非常细腻的细节。无论是白兰度饰演的大家长，还是帕西诺的新一代，人物刻画既个性化，又不乏代表性。暴力场面也有如此双重性，既写实，又有歌剧的壮观。事实上，整部影片将一些没有社会内涵的打打杀杀升华为美轮美奂的歌剧，达到黑帮电影的最高境界。片尾洗礼的婴儿是科波拉的亲生女儿。本片荣获第45届奥斯卡最佳影片、最佳男主角、最佳改编剧本。</p>
<p>
	<img src="http://pic.piaohua.com/0701pic/allimg/080921/0343200.jpg" /></p>
<p>
	【电影截图分辨率过大请点击查看】：<br />
	电影来源：www.eee4.com<br />
	<a href="/0701pic/allimg/080921/0343201.jpg" target="_blank"><img src="http://pic.piaohua.com/0701pic/allimg/080921/0343201.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 338px; border-top: 0px solid; border-right: 0px solid" /></a>&nbsp;<br />
	<a href="/0701pic/allimg/080921/0343202.jpg" target="_blank"><img src="http://pic.piaohua.com/0701pic/allimg/080921/0343202.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 338px; border-top: 0px solid; border-right: 0px solid" /></a>&nbsp;<br />
	<a href="/0701pic/allimg/080921/0343203.jpg" target="_blank"><img src="http://pic.piaohua.com/0701pic/allimg/080921/0343203.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 338px; border-top: 0px solid; border-right: 0px solid" /></a>&nbsp;<br />
	<a href="/0701pic/allimg/080921/0343204.jpg" target="_blank"><img src="http://pic.piaohua.com/0701pic/allimg/080921/0343204.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 338px; border-top: 0px solid; border-right: 0px solid" /></a></p>
<p>
	2008-09-21 01:15:12 开始连接......<br />
	2008-09-21 01:15:12 开始搜索候选资源......<br />
	2008-09-21 01:15:12 搜索到52个候选资源<br />
	2008-09-21 01:15:12 使用候选资源进行 连接......<br />
	2008-09-21 01:15:13 搜索到121个候选资源<br />
	2008-09-21 01:15:13 使用候选资源进行连接......<br />
	2008-09-21 01:15:13 文件创建成功，开始下载数 据......<br />
	2008-09-21 01:15:16 用户取消下载&nbsp;&nbsp; 本文来自：www.eee4.com</p>
<p>
	（直接可能无法下载，一律使用<a href="/soft.htm" target="_blank">迅雷下载</a>）<br />
	美国超经典高分动作大片《教父》DVD中英双字1024x576高清版下载地址：<img border="0" src="/templets/img/down.jpg" /><br />
	CD1：</p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<anchor></anchor><a href="ftp://eee4.com:1001@xl2.eee4.com:1001/[3E电影站www.eee4.com]教父[DVD中英双字1024x576高清版]CD1.rmvb" target="_blank">ftp://eee4.com:1001@xl2.eee4.com:1001/[3E电影站www.eee4.com]教父[DVD中英双字1024x576高清版]CD1.rmvb</a></td>
		</tr>
	</tbody>
</table>
<p>
	CD2：</p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<anchor></anchor><a href="ftp://eee4.com:1001@xl2.eee4.com:1001/[3E电影站www.eee4.com]教父[DVD中英双字1024x576高清版]CD2.rmvb" target="_blank">ftp://eee4.com:1001@xl2.eee4.com:1001/[3E电影站www.eee4.com]教父[DVD中英双字1024x576高清版]CD2.rmvb</a></td>
		</tr>
	</tbody>
</table>
<p>
	CD3：</p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<anchor></anchor><a href="ftp://eee4.com:1001@xl2.eee4.com:1001/[3E电影站www.eee4.com]教父[DVD中英双字1024x576高清版]CD3.rmvb" target="_blank">ftp://eee4.com:1001@xl2.eee4.com:1001/[3E电影站www.eee4.com]教父[DVD中英双字1024x576高清版]CD3.rmvb</a></td>
		</tr>
	</tbody>
</table>

<p>
	美国超经典高分动作大片《教父》DVD中英双字1280x720高清版下载地址：</p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<anchor></anchor><a href="ftp://dy241:370kk@dy241.piaohua.com:2044/小八戒电影xiaobajie.com教父I中英双字720p.rmvb" target="_blank">ftp://dy241:370kk@dy241.piaohua.com:2044/小八戒电影xiaobajie.com教父I中英双字720p.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1C33L0-35948.jpg{/dede:field}
