<?php
$z[0]=Array("field","迷城/远雷HD国语中字1280高清迅",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","迷城/远雷HD国语中字1280高清迅雷下载、免费下载，迷城/远雷HD国语中字1280高清Gvod高清在线播放，剧情介绍等。",72,220);
$z[1][4]['name']="description";
$z[2]=Array("field","迷城/远雷HD国语中字1280高清",222,287);
$z[2][4]['name']="title";
$z[3]=Array("field","",289,328);
$z[3][4]['name']="writer";
$z[4]=Array("field","",330,369);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-12-24",371,421);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",423,460);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://3e:3e@m1.3edyy.com:1564/【3E看看www.3ekk.com】迷城[DVD国语中字无水印].rmvb\" target=\"_blank",462,597);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MOO040-26221.jpg",599,681);
$z[8][4]['name']="litpic";

?>