{dede:field name='keywords'}鬼马双星BD1280高清国粤双语迅雷{/dede:field}
{dede:field name='description'}鬼马双星BD1280高清国粤双语迅雷下载、免费下载，鬼马双星BD1280高清国粤双语Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}鬼马双星BD1280高清国粤双语{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-07{/dede:field}
{dede:field name='body'}<div>
	<p>
		<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120506/00/17870980201205060019081187476919495_010.jpg" style="width: 552px; height: 717px" /></p>
	<p>
		◎译　　名　鬼马双星<br />
		◎片　　名　Games&nbsp;Gamblers&nbsp;Play<br />
		◎年　　代　1974<br />
		◎国　　家　中国香港<br />
		◎类　　别　喜剧<br />
		◎语　　言　普通话/粤语<br />
		◎字　　幕　繁体中文/英文<br />
		◎IMDB评分&nbsp;6.5/10&nbsp;(77&nbsp;votes)<br />
		◎IMDB链结&nbsp;<a href="http://www.imdb.com/title/tt0071588">http://www.imdb.com/title/tt0071588</a><br />
		◎片　　长　103&nbsp;Mins<br />
		◎导　　演　许冠文&nbsp;Michael&nbsp;Hui<br />
		◎主　　演　乔宏&nbsp;Roy&nbsp;Chiao<br />
		　　　　　　许冠文&nbsp;Michael&nbsp;Hui<br />
		　　　　　　许冠英&nbsp;Ricky&nbsp;Hui<br />
		　　　　　　许冠杰&nbsp;Sam&nbsp;Hui<br />
		　　　　　　郑君绵&nbsp;Cheng&nbsp;Kwan&nbsp;Min<br />
		　　　　　　冯敬文&nbsp;Ging&nbsp;Man&nbsp;Fung<br />
		　　　　　　何柏光&nbsp;Pak-Kwong&nbsp;Ho<br />
		　　　　　　许绍雄&nbsp;Shiu&nbsp;Hung&nbsp;Hui<br />
		　　　　　　罗兰&nbsp;Lan&nbsp;Law<br />
		　　　　　　吕有慧&nbsp;Lisa&nbsp;Lui<br />
		　　　　　　石天&nbsp;Tean&nbsp;Shek<br />
		　　　　　　丁佩&nbsp;Betty&nbsp;Ting&nbsp;Pei&nbsp;&nbsp;....(as&nbsp;Betty&nbsp;Ting)<br />
		　　　　　　黄霑&nbsp;James&nbsp;Wong<br />
		　　　　　　谢衍&nbsp;Yan&nbsp;Xie<br />
		　　　　　　陈立品&nbsp;Maria&nbsp;Chan<br />
		　　　　　　李昆&nbsp;Kun&nbsp;Li<br />
		　　　　　　Cheung&nbsp;Wah<br />
		　　　　　　陶敏明&nbsp;Ming&nbsp;Ming&nbsp;Taur<br />
		　　　　　　<br />
		◎简　　介　<br />
		<br />
		　　这是香港70年代的典型武打搞笑片。老千邓国文（许冠文&nbsp;饰）经常出入于监狱，狱中无聊时，他经常会表演一些自己的千术以资同仓的犯人解闷。犯人刘俊杰（许冠杰&nbsp;饰）对国文的千术十分佩服，希望出狱后能和他一起合作挣大钱。国文并没有答应，因为老千一般都独来独往。<br />
		<br />
		　　两人出狱后，俊杰组织了一帮老千和国文对赌，国文通过一早买通在场的舞女佩佩将他们击败。俊杰更加佩服国文，再次提出两人合作。国文抵不住他的死缠烂打，终于应承了。两人计划向城中恶霸大哥全下手，为了筹集赌资，他们还参加了电视台的有奖游戏，国文凭借聪明的头脑顺利的赢下了奖金。和大哥全对赌的日子到了。<br />
		<br />
		幕后制作<br />
		<br />
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;当年，许冠文将亲自编写的得意剧本《鬼马双星》交到邵逸夫手中，希望能够同公司合资拍片平分利润，邵逸夫认为要求过分，断然拒绝。许冠杰当时已是嘉禾的签约艺人，嘉禾老板邹文怀答应帮助许氏兄弟创办电影公司。许冠文转投嘉禾。1974年，许冠文与弟弟许冠杰等成立许氏兄弟电影公司，自编自导《鬼马双星》，获得空前成功，在香港的票房高达625万港元，超过李小龙影片以及邵氏同期推出的楚原导演的喜剧片《七十二家房客》，由此引领香港本土鬼马喜剧的新潮流。《鬼马双星》在香港喜剧电影史上和许冠文的创作中，处于承前启后的重要地位。它继承了老式港产笑片结构松散的传统，有许多独立城章的以本土俚语方言编织的笑料堆砌而成；又更加突出了个人表演的作用，精心刻画人物的诙谐性格和搞笑行为，还极具讽刺自省意味。本片贴近港人生活，风趣幽默，当年香港人有一半进到电影院观看这部讲述他们发财梦的电影。1974年，同名唱片&ldquo;鬼马双星&rdquo;与电影同时推出，唱片在东南亚总销量达十五万，破当年纪录，&ldquo;鬼马双星&rdquo;主题曲成为一首在英国BBC电台及香港电台英文台播放的中文歌，歌词&ldquo;人生如赌博，赢输都无时定&rdquo;也成为一些人生活的参考。 <img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120507/22/17870980201205072224421282121355673_005.jpg" /></p>
	<p>
		<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120507/22/17870980201205072224421282121355673_001.jpg" /></p>
	<p>
		<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120507/22/17870980201205072224421282121355673_000.jpg" style="width: 640px; height: 360px" /></p>
</div>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.net" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy241:piaohua@117.41.229.29:2006/飘花电影piaohua.com鬼马双星BD1280高清国粤双语.mkv">ftp://dy241:piaohua@117.41.229.29:2006/飘花电影piaohua.com鬼马双星BD1280高清国粤双语.mkv</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15J21P-32121.jpg{/dede:field}
