{dede:field name='keywords'}赞先生与找钱华HD高清1024*576迅{/dede:field}
{dede:field name='description'}赞先生与找钱华HD高清1024*576迅雷下载、免费下载，赞先生与找钱华HD高清1024*576Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}赞先生与找钱华HD高清1024*576{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-09-11{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20110910/08/62564813201109100841022288733347456_000.jpg" /></p>
<p>
	◎中文　名　赞先生与找钱华<br />
	◎片　　名　Warriors Two<br />
	◎年　　代　1978<br />
	◎地　　区　中国香港<br />
	◎类　　别　喜剧/动作<br />
	◎语　　言　普通话<br />
	◎字　　幕　中文<br />
	◎IMDB评分　7.6/10 （281 votes）<br />
	◎IMDB链接　<a href="http://www.imdb.com/title/tt0078517/">http://www.imdb.com/title/tt0078517/</a><br />
	◎视频尺寸　1024 x 576<br />
	◎导　　演　洪金宝　　　<br />
	◎主　　演　洪金宝 Sammo Hung Kam-Bo .... Fei Chun　<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 卡萨伐 Casanova Wong....Cashier Hua　<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 陈会毅 Billy Chan ....　<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 冯克安 Hark-On Fung .... Mo<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 林正英 Ching-Ying Lam .... Swordsman　<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 梁家仁 Ka-Yan Leung .... Mr. Tsang　<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 刘家荣 Chia Yung Liu .... Chief&#39;s Man　<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 石天 Dean Shek .... Mentor Chiu　<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 曾志伟 Eric Tsang<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 元彪 Biao Yuen ....　<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 李海生 Hoi San Lee　....Ya Chao　<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 钟发 Fat Chung　....Tramp　<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 陈龙 Lung Chan　....Conman　<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 张敏婷 Minting Zhang　<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 杨成五 Tiger Yang　<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 钱升玮 Wellson Chin　<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 钱月笙 Yuet Sang Chin　<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 火星 Mars　<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 崔戊雄 Miu Hung Chui　<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 孟海 Hoi Mang　<br />
	◎简　　介　</p>
<p>
	　　咏春第五代传人佛山名医梁赞（梁家仁饰）为人正直，悬壶济世，深得乡民敬颂。有徒儿肥春（洪金宝饰）性情戆直，找钱华（卡萨伐饰）乃春之朋友，在莫记钱庄任掌柜，钱庄老板莫老庆（冯克安饰）表面为一慈祥老人，实乃退引多年之汪洋大盗。某日，华无意得悉莫有意与七名恶汉合谋，杀掉镇长，夺其权位。当莫发觉华得悉其行动，马上命人追杀，七大汉为首者雷公泰（杨成五饰）精拳术。华幸不死，华母却被莫杀掉，华决心向赞学咏春，为母报仇，华求赞收为徒，习武报仇遭拒，幸得春施计相助，赞后亦因中伏身亡，春决直捣虎穴。　</p>
<p>
	&nbsp;<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20110910/14/62564813201109101435132278031548213_001.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20110910/13/62564813201109101359271984031956493_000.jpg" style="width: 720px; height: 405px" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="&#13;&#10;ftp://dy125:piaohua@dy125.piaohua.com:3009/飘花电影piaohua.com赞先生与找钱华HD高清国语中字1024分辨率.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:3009/飘花电影piaohua.com赞先生与找钱华HD高清国语中字1024分辨率.rmvb </a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1C05960-44V7.jpg{/dede:field}
