<?php
$z[0]=Array("field","十三/命13/13搏命游戏/百万杀人",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","十三/命13/13搏命游戏/百万杀人游戏13[DVD中字]迅雷下载、免费下载，十三/命13/13搏命游戏/百万杀人游戏13[DVD中字]Gvod高清在线播放，剧情介绍等。",72,254);
$z[1][4]['name']="description";
$z[2]=Array("field","十三/命13/13搏命游戏/百万杀人游戏13[DVD中字]",256,338);
$z[2][4]['name']="title";
$z[3]=Array("field","",340,379);
$z[3][4]['name']="writer";
$z[4]=Array("field","",381,420);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-12-11",422,472);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",474,511);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://3e:3e@m1.3edyy.com:1570/【3E看看www.3ekk.com】十三DVD中字.rmvb\" target=_blank>ftftp://3e:3e@m1.3edyy.com:1570/【3E看看www.3ekk.com】十三DVD中字.rmvb</A></TD></TR></TBODY></TABLE></div><ul class=\"mmlist",513,759);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MP3503Z-111B.jpg",761,843);
$z[8][4]['name']="litpic";

?>