{dede:field name='keywords'}惊魂游戏HD国语中字2012恐怖惊悚{/dede:field}
{dede:field name='description'}惊魂游戏HD国语中字2012恐怖惊悚迅雷下载、免费下载，惊魂游戏HD国语中字2012恐怖惊悚Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}惊魂游戏HD国语中字2012恐怖惊悚{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-21{/dede:field}
{dede:field name='body'}<p>
	<img alt="" height="600" src="http://img2081.poco.cn/mypoco/myphoto/20120128/02/56643687201201280208343785332382298_004.jpg" width="360" /></p>
<p>
	<img alt="" height="600" src="http://img2081.poco.cn/mypoco/myphoto/20120128/02/56643687201201280208343785332382298_005.jpg" width="360" /></p>
<p>
	<img alt="" height="600" src="http://img2081.poco.cn/mypoco/myphoto/20120128/02/56643687201201280208343785332382298_002.jpg" width="428" /></p>
<p>
	<img alt="" height="600" src="http://img2081.poco.cn/mypoco/myphoto/20120128/02/56643687201201280208343785332382298_003.jpg" width="395" /></p>
<p>
	<img alt="" height="600" src="http://img2081.poco.cn/mypoco/myphoto/20120128/02/56643687201201280208343785332382298_001.jpg" width="406" /></p>
<p>
	<img alt="" height="600" src="http://img2081.poco.cn/mypoco/myphoto/20120128/02/56643687201201280208343785332382298_000.jpg" width="428" /></p>
<p>
	中文名： 惊魂游戏<br />
	外文名： Harpoon<br />
	制片地区： 中国<br />
	导演： 周耀武<br />
	制片人： 桃子<br />
	类型： 惊悚，悬疑<br />
	主演： 邵兵，莫小棋，朴鲁植，李玲玉，王双宝，赵铭<br />
	片长： 90分钟<br />
	上映时间： 2012年1月24日<br />
	对白语言： 普通话<br />
	官方网站：<a href="http://www.bluemv.com" title="电影下载">http://www.bluemv.com</a><br />
	<br />
	<br />
	剧情简介<br />
	<br />
	　　年轻貌美的莫小棋在剧中饰演一名游戏公司的职员，而胡兵饰演一位沉默寡言的外科医生，他们原本是一对令人艳羡的俊男美女情侣，却接连遭遇了情感信任危机。面临分手边缘的他们决定为修补情感裂痕而前往一座陌生海岛旅行。谁料到，这个看似宁静的海岛后面竟然隐藏着惊人的秘密，一群嗜血杀人狂正在四处寻觅着他们的踪迹，而互相猜忌的他们竟然对此浑然不知，一场密林深处的生死大逃亡由此展开。<br />
	<br />
	<br />
	<br />
	◎影片截图<br />
	<br />
	<img alt="" height="337" src="http://img2081.poco.cn/mypoco/myphoto/20120128/02/56643687201201280208343785332382298_007.jpg" style="cursor: pointer" width="600" /><br />
	<br />
	<img alt="" height="337" src="http://img2081.poco.cn/mypoco/myphoto/20120128/02/56643687201201280208343785332382298_008.jpg" style="cursor: pointer" width="600" /><br />
	<br />
	<img alt="" height="337" src="http://img2081.poco.cn/mypoco/myphoto/20120128/02/56643687201201280208343785332382298_009.jpg" style="cursor: pointer" width="600" /><br />
	<br />
	<img alt="" height="337" src="http://img2081.poco.cn/mypoco/myphoto/20120128/02/56643687201201280208343785332382298_006.jpg" style="cursor: pointer" width="600" /><br />
	[下载地址]：&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="thunder://QUFodHRwOi8vdGh1bmRlci5mZmR5LmNjL0E4RUFDMkE3RDc0MjJCREU0NzEyRTdDQjdGNzdDRjkzRDNCMThGQjQvvqq76tPOz7cucm12Ylpa/">&nbsp;</a><a href="thunder://QUFodHRwOi8vdGh1bmRlci5mZmR5LmNjL0E4RUFDMkE3RDc0MjJCREU0NzEyRTdDQjdGNzdDRjkzRDNCMThGQjQvvqq76tPOz7cucm12Ylpa/">ftp://dy44:piaohua@dy44.piaohua.com:2713/飘花电影piaohua.com惊魂游戏HD国语中字.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15134030-42C4.jpg{/dede:field}
