<?php
$z[0]=Array("field","我为玛丽狂/情迷索玛丽BD中英双",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","我为玛丽狂/情迷索玛丽BD中英双字1024/1280高清迅雷下载、免费下载，我为玛丽狂/情迷索玛丽BD中英双字1024/1280高清Gvod高清在线播放，剧情介绍等。",72,254);
$z[1][4]['name']="description";
$z[2]=Array("field","我为玛丽狂/情迷索玛丽BD中英双字1024/1280高清",256,338);
$z[2][4]['name']="title";
$z[3]=Array("field","",340,379);
$z[3][4]['name']="writer";
$z[4]=Array("field","",381,420);
$z[4][4]['name']="source";
$z[5]=Array("field","2012-02-27",422,472);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",474,511);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://3e:3e@www2.eee4.com:680/[www.eee4.cn提供]我为玛丽狂BD中英双字1280x720高清版.rmvb\" target=\"_blank",513,654);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MOE3020-3H92.jpg",656,738);
$z[8][4]['name']="litpic";

?>