{dede:field name='keywords'}圣安娜奇迹BD1280高清迅雷下载，{/dede:field}
{dede:field name='description'}圣安娜奇迹BD1280高清迅雷下载、免费下载，圣安娜奇迹BD1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}圣安娜奇迹BD1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-22{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://i.minus.com/ioAwmeauWl8Tj.jpg" style="width: 565px; height: 798px" /></p>
<p>
	【片　　名】　Miracle at St. Anna<br />
	【中文译名】　圣安娜奇迹<br />
	【国　　家】　美国 / 意大利<br />
	【上 &nbsp; &nbsp; &nbsp;映】　2008-09-26 美国<br />
	【类　　别】　动作 / 战争 / 剧情 / 惊悚<br />
	【语　　言】　英语 / 德语 / 意大利语<br />
	【字 &nbsp; &nbsp; &nbsp;幕】 &nbsp; 内符中文<br />
	【IMDB评分】 &nbsp;6.0/10 (10,975 votes)<br />
	【IMDB链接】 &nbsp;<a href="http://www.imdb.com/title/tt1046997" target="_blank">http://www.imdb.com/title/tt1046997</a><br />
	【片　　长】　160 min<br />
	【编 &nbsp; &nbsp; &nbsp;剧】 &nbsp; 詹姆斯&middot;麦克布莱德<br />
	【导　　演】　斯派克&middot;李<br />
	【主　　演】 &nbsp; 约翰&middot;特托罗 John Turturro ....Detective Antonio &#39;Tony&#39; Ricci<br />
	　　　　　　 &nbsp; &nbsp;迈克尔&middot;威廉姆斯 Michael K. Williams<br />
	　　　　　　 &nbsp; &nbsp;德瑞克&middot;卢克 Derek Luke ....2nd Staff Sergeant Aubrey Stamps<br />
	　　　　　　 &nbsp; &nbsp;Michael Ealy ....Sergeant Bishop Cummings<br />
	　　　　　　 &nbsp; &nbsp;Robert John Burke ....General Ned Almond<br />
	　　　　　　 &nbsp; &nbsp;Malcolm Goodwin ....Higgins<br />
	　　　　　　 &nbsp; &nbsp;Walt Goggins ....Nokes<br />
	　　　　　　 &nbsp; &nbsp;Omar Benson Miller ....Private First Class Sam Train<br />
	　　　　　　 &nbsp; &nbsp;Omari Hardwick ....Platoon Commander Huggs<br />
	　　　　　　 &nbsp; &nbsp;皮尔佛朗西斯科&middot;法维诺 Pierfrancesco Favino ....Peppi &#39;The Great Butterfly&#39; Grotta<br />
	　　　　　　 &nbsp; &nbsp;Limary Agosto ....Sonia<br />
	　　　　　　 &nbsp; &nbsp;Tory Kittles<br />
	　　　　　　 &nbsp; &nbsp;Valentina Cervi ....Renata<br />
	　　　　　　 &nbsp; &nbsp;Lidia Biondi ....Natalina<br />
	　　　　　　 &nbsp; &nbsp;克里斯汀&middot;伯克 Christian Berkel ....Captain Eicholz<br />
	<br />
	<br />
	圣安娜奇迹的剧情简介 &nbsp; &middot; &middot; &middot; &middot; &middot; &middot;<br />
	　　本片由小说改编而成，讲述了一个发生在二战时意大利托斯卡尼地区的真实事件。1944年，在世界大战欧洲的战场上活跃着一支完全由黑人组成的部队92师。4个来自92师的黑人大兵奥布里&middot;斯坦普斯(德瑞克&middot;卢克饰演)、坡仕普&middot;康明斯(迈克尔&middot;伊尔饰演)、海克特&middot;耐隆(拉慈&middot;阿隆索饰演)和山姆&middot;<br />
	崔恩为了救一个托斯卡尼男孩被围困在一个小村中。当时的意大利是站在法西斯阵营之中，在这个名为圣安娜的村落中美国大兵也同样不如德军受到人们的欢迎和尊敬，在语言不通、怀有敌意的当地人和虎视眈眈的德军的包围中，四个黑人大兵的表现超越了种族、阶级和国别的信念与互助，用勇敢和信仰创造了伟大的奇迹&hellip;&hellip;<br />
	<br />
	<br />
	圣安娜奇迹的影评 &nbsp;&middot; &middot; &middot; &middot; &middot; &middot; (共33条)<br />
	陆川看完&ldquo;圣安娜&rdquo;估计要疯了&mdash;&mdash;他肯定没看过！<br />
	孩子他妈&trade;(Melancholia) &nbsp;<br />
	<br />
	什么是差距？这就是差距！！<br />
	　　战争的惨烈不是靠死人堆出来，同样是屠杀场景，为什么会有这么大的差距？？同样讲人性，为什么又会有这么大差距？？？<br />
	　　<br />
	　　教堂屠杀的场景真把我震撼到了，看战争片从来没看到那么恐惧过。导演用一个又一个镜头给我心灵施压，让我窒息，让我恐惧到颤抖。德国军官一次次威胁，牧师的祈求和众人的祷告，都带来一种压迫感，一种死亡的压迫感。死亡来得很快，一排机枪的扫射后鲜血溅在教堂的墙壁上，侥幸没被打死的垂死挣扎者吃了第二枪终于毙了命，嗷嗷待哺的女婴那清澈的眼睛最后也闭上了。炼狱也不过如此。<br />
	　　<br />
	　　然而后来出现奇迹，一个小德国兵竟然带着两个男孩子逃出来了！让我顿时开朗，那是一种死里逃生后才有的感觉，不能说是开心，人不可能因为在这种情况下逃出来还能保持单纯的高兴的心情的，很少有电影能做出这种感觉的吧？就跟绝大多数经历战场回来的人每天都会做噩梦一样，他们幸存了，但他们不会单纯地因此而感到开心。所以说《南京，南京》的结局用小孩高兴采鲜花来表示幸存后的心情，我是很不能理解的！<br />
	　　<br />
	　　影片是根据小说改编，虽然将近三小时，但作为电影是很难把细节都刻画好的，这是小说改编电影的通病。虽然影片是没多深地挖掘细节，但是我相信看懂影片的人此刻都意会了，其实很多事情也不需讲太明白，内心的共鸣才是最重要的。<br />
	　　<br />
	　　虽然细节较少刻画，但是整体结构还是完整有序的。交代了事情的起因，又扔出了若干个悬疑，最后一气呵成地串到一起讲述了一个完整故事，所有疑惑都一一解答。有插叙有回忆，内容很丰富很完整，把一个战争能碰到的情况几乎全包括了&mdash;&mdash;兄弟情，战友情，亲情，爱情，同情，残酷的战争，死亡，叛徒，凶残的德国鬼子，很SB的指挥官，各有需求的肉体交易&hellip;&hellip;更重要的是黑人作为主角穿插其中，引申出更严峻的问题，种族歧视，作为电影已经很好地呈现出来了。想说原著小说很了不起。影片没有用很漂亮的拍摄手法和精美的剪辑，有些情节的处理也不是特别恰当，但这不能影响整部电影的成绩，毕竟形式只是次要的，它内容实在太丰富了。<br />
	<img alt="" src="http://i.minus.com/ikfTTM4koZRwM.jpg" style="width: 720px; height: 306px" /><img alt="" src="http://i.minus.com/iHOXHxZd6d7Ab.jpg" style="width: 720px; height: 306px" /><img alt="" src="http://i.minus.com/iNqB3W438RGlt.jpg" style="width: 720px; height: 306px" /><img alt="" src="http://i.minus.com/i29Yki6xqY7EA.jpg" style="width: 720px; height: 306px" /><img alt="" src="http://i.minus.com/ibjuFx7m0X743L.jpg" style="width: 720px; height: 306px" /><br />
	&nbsp;</p>
<p>
	【下载地址】</p>
<table bgcolor="#0099cc" border="0" cellpadding="10" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaobajie.com" target="_blank">http://www.xiaobajie.com</a></td>
		</tr>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy125:piaohua@dy125.piaohua.com:8089/飘花电影piaohua.com圣安娜奇迹BD中字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:8089/飘花电影piaohua.com圣安娜奇迹BD中字1280高清.rmvb</a></td>
		</tr>
		<tr>
		</tr>
	</tbody>
</table>
<br />{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15033210-49445.jpg{/dede:field}
