<?php
$z[0]=Array("field","疯狂青蛙迅雷下载，免费下载，Gv",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","疯狂青蛙迅雷下载、免费下载，疯狂青蛙Gvod高清在线播放，剧情介绍等。",73,183);
$z[1][4]['name']="description";
$z[2]=Array("field","疯狂青蛙",185,231);
$z[2][4]['name']="title";
$z[3]=Array("field","",233,272);
$z[3][4]['name']="writer";
$z[4]=Array("field","",274,313);
$z[4][4]['name']="source";
$z[5]=Array("field","2006-08-04",315,365);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<object classid=\"CLSID:22d6f312-b0f6-11d0-94ab-0080c74c7e95\" class=\"OBJECT\" id=\"MediaPlayer\" width=\"500\" height=\"350\" ><param name=\"ShowStatusBar\" value=\"-1\"><param name=\"Filename\" value=\"http://www.20530.com/UUAuth/uu04/10.wmv\"> \n</embed></object><br /> \n<P>下载地址<BR></P> <br>",367,684);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c120524/133N353DD0-2G248.gif",686,769);
$z[7][4]['name']="litpic";

?>