{dede:field name='keywords'}国家地理：大迁徙[BD中字1024x57{/dede:field}
{dede:field name='description'}国家地理：大迁徙[BD中字1024x576高清版]迅雷下载、免费下载，国家地理：大迁徙[BD中字1024x576高清版]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}国家地理：大迁徙[BD中字1024x576高清版]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-01-11{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://3e:3e@d3.3edyy.com:121/【3E电影院www.eee4.org】大迁徙：第01集.1024x576.中文字幕.mkv" target=_blank>ftftp://3e:3e@d3.3edyy.com:121/【3E电影院www.eee4.org】大迁徙：第01集.1024x576.中文字幕.mkv</A></TD></TR></TBODY></TABLE>第02集：<BR>
<TABLE style="BORDER-BOTTOM: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-RIGHT: #cccccc 1px dotted" border=0 cellSpacing=0 cellPadding=6 width="95%" align=center>
<TBODY>
<TR>
<TD style="WORD-WRAP: break-word" bgColor=#fdfddf><A href="ftftp://3e:3e@d3.3edyy.com:121/【3E电影院www.eee4.org】大迁徙：第02集.1024x576.中文字幕.mkv" target=_blank>ftftp://3e:3e@d3.3edyy.com:121/【3E电影院www.eee4.org】大迁徙：第02集.1024x576.中文字幕.mkv</A></TD></TR></TBODY></TABLE>第03集：<BR>
<TABLE style="BORDER-BOTTOM: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-RIGHT: #cccccc 1px dotted" border=0 cellSpacing=0 cellPadding=6 width="95%" align=center>
<TBODY>
<TR>
<TD style="WORD-WRAP: break-word" bgColor=#fdfddf><A href="ftftp://3e:3e@d3.3edyy.com:121/【3E电影院www.eee4.org】大迁徙：第03集.1024x576.中文字幕.mkv" target=_blank>ftftp://3e:3e@d3.3edyy.com:121/【3E电影院www.eee4.org】大迁徙：第03集.1024x576.中文字幕.mkv</A></TD></TR></TBODY></TABLE>第04集：<BR>
<TABLE style="BORDER-BOTTOM: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-RIGHT: #cccccc 1px dotted" border=0 cellSpacing=0 cellPadding=6 width="95%" align=center>
<TBODY>
<TR>
<TD style="WORD-WRAP: break-word" bgColor=#fdfddf><A href="ftftp://3e:3e@d3.3edyy.com:121/【3E电影院www.eee4.org】大迁徙：第04集.1024x576.中文字幕.mkv" target=_blank>ftftp://3e:3e@d3.3edyy.com:121/【3E电影院www.eee4.org】大迁徙：第04集.1024x576.中文字幕.mkv</A></TD></TR></TBODY></TABLE>第05集：<BR>
<TABLE style="BORDER-BOTTOM: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-RIGHT: #cccccc 1px dotted" border=0 cellSpacing=0 cellPadding=6 width="95%" align=center>
<TBODY>
<TR>
<TD style="WORD-WRAP: break-word" bgColor=#fdfddf><A href="ftftp://3e:3e@d3.3edyy.com:121/【3E电影院www.eee4.org】大迁徙：第05集.1024x576.中文字幕.mkv" target=_blank>ftftp://3e:3e@d3.3edyy.com:121/【3E电影院www.eee4.org】大迁徙：第05集.1024x576.中文字幕.mkv</A></TD></TR></TBODY></TABLE>第06集：<BR>
<TABLE style="BORDER-BOTTOM: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-RIGHT: #cccccc 1px dotted" border=0 cellSpacing=0 cellPadding=6 width="95%" align=center>
<TBODY>
<TR>
<TD style="WORD-WRAP: break-word" bgColor=#fdfddf><A href="ftftp://3e:3e@d3.3edyy.com:121/【3E电影院www.eee4.org】大迁徙：第06集.1024x576.中文字幕.mkv" target=_blank>ftftp://3e:3e@d3.3edyy.com:121/【3E电影院www.eee4.org】大迁徙：第06集.1024x576.中文字幕.mkv</A></TD></TR></TBODY></TABLE></div><ul class="mmlist{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MQ45EZ-1W10.jpg{/dede:field}
