{dede:field name='keywords'}暴雨屋DVD中字2011英国恐怖惊悚{/dede:field}
{dede:field name='description'}暴雨屋DVD中字2011英国恐怖惊悚迅雷下载、免费下载，暴雨屋DVD中字2011英国恐怖惊悚Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}暴雨屋DVD中字2011英国恐怖惊悚{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-04-22{/dede:field}
{dede:field name='body'}<p>
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120422/12/56643687201204221240302121548764531_000.jpg" /></p>
<p>
	◎译　　名　暴雨屋<br />
	◎片　　名　Stormhouse<br />
	◎年　　代　2011<br />
	◎国　　家　英国<br />
	◎类　　别　恐怖/惊悚<br />
	◎语　　言　英语<br />
	◎字　　幕　中字<br />
	◎IMDB评分 3.7/10 (269 votes)<br />
	◎文件格式　DVD-RMVB<br />
	◎视频尺寸　640 x 272<br />
	◎文件大小　1CD 438MB<br />
	◎片　　长　86 mins<br />
	◎导　　演　Dan Turner<br />
	◎主　　演　Grant Masters ....Major Anthony Lester<br />
	　　　　　　Patrick Flynn ....Justin Rourke<br />
	　　　　　　Grahame Fox ....Lieutenant Groves<br />
	　　　　　　Munir Khairdin ....Salim Hassan<br />
	　　　　　　Martin Delaney ....Brandon Faber<br />
	　　　　　　James Capel ....Karl Matthews<br />
	　　　　　　Anthony Mark Streeter ....Lance Corporal Rogers<br />
	　　　　　　Frankie Fitzgerald ....Dan Randall<br />
	　　　　　　Andrew Hall ....Minister Duncan McGillis<br />
	　　　　　　Jordan Pitt ....Andy Duggan<br />
	　　　　　　Marlon Williams ....Jones</p>
<p>
	◎简　　介　</p>
<p>
	　　暴雨屋位于地下九层，是英国政府的一个研究灵魂磁场的秘密基地。Hayley在母亲死后发现自己可以和灵魂进行沟通，也由于这个原因，她被上司安排到了暴雨屋进行协助。进入暴雨屋后发现，暴雨屋与外界基本隔绝，并且从他的向导JUSTIN那里得知，他们利用磁场将一个灵魂困在暴雨屋的一间格笼里，并且对它进行研究。Harley急于与那个灵魂交谈，于是一次次接近格笼，不料因一次冲突，不小心将灵魂放出格笼，于是怨灵开始了它的&ldquo;游戏&rdquo;......</p>
<p>
	<br />
	◎影片截图</p>

<p>
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120422/12/56643687201204221240302121548764531_003.jpg" /></p>
<p>
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120422/12/56643687201204221240302121548764531_002.jpg" /></p>
<p>
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120422/12/56643687201204221240302121548764531_001.jpg" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.netftp//dy44:piaohua@dy44.piaohua.com:3125/" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3271/飘花电影piaohua.com暴雨屋DVD中字.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3271/飘花电影piaohua.com暴雨屋DVD中字.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1630SF-12551.jpg{/dede:field}
