<?php
$z[0]=Array("field","巴比伦纪元/生死新纪元/巴比伦密",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","巴比伦纪元/生死新纪元/巴比伦密码BD中英双字1024/1280高清迅雷下载、免费下载，巴比伦纪元/生死新纪元/巴比伦密码BD中英双字1024/1280高清Gvod高清在线播放，剧情介绍等。",73,277);
$z[1][4]['name']="description";
$z[2]=Array("field","巴比伦纪元/生死新纪元/巴比伦密码BD中英双字1024/1280高清",279,372);
$z[2][4]['name']="title";
$z[3]=Array("field","",374,413);
$z[3][4]['name']="writer";
$z[4]=Array("field","",415,454);
$z[4][4]['name']="source";
$z[5]=Array("field","2012-03-17",456,506);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",508,545);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://e25:e25@dm.eee4.com:1216/[3E电影站www.eee4.com]巴比伦纪元[DVD中英双字1024x560高清版]CD1.rmvb\" target=\"_blank",547,700);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MO4U040-23061.jpg",702,785);
$z[8][4]['name']="litpic";

?>