{dede:field name='keywords'}巴比伦纪元/生死新纪元/巴比伦密{/dede:field}
{dede:field name='description'}巴比伦纪元/生死新纪元/巴比伦密码BD中英双字1024/1280高清迅雷下载、免费下载，巴比伦纪元/生死新纪元/巴比伦密码BD中英双字1024/1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}巴比伦纪元/生死新纪元/巴比伦密码BD中英双字1024/1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-03-17{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://e25:e25@dm.eee4.com:1216/[3E电影站www.eee4.com]巴比伦纪元[DVD中英双字1024x560高清版]CD1.rmvb" target="_blank{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MO4U040-23061.jpg{/dede:field}
