{dede:field name='keywords'}敌人DVD中字2011塞尔维亚战争恐{/dede:field}
{dede:field name='description'}敌人DVD中字2011塞尔维亚战争恐怖惊悚迅雷下载、免费下载，敌人DVD中字2011塞尔维亚战争恐怖惊悚Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}敌人DVD中字2011塞尔维亚战争恐怖惊悚{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-04-21{/dede:field}
{dede:field name='body'}<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120420/21/56643687201204202113329283137446067_004.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 873px; border-top: 0px solid; border-right: 0px solid" /></p>

<p>
	◎片　　名　The Enemy<br />
	◎年　　代　2011<br />
	◎国　　家　塞尔维亚/波黑/克罗地亚/匈牙利<br />
	◎类　　别　剧情/战争/恐怖/惊悚<br />
	◎语　　言　塞尔维亚语<br />
	◎字　　幕　中文<br />
	◎IMDB评分 7.2/10 from 185 users<br />
	◎IMDB链接 <a href="http://www.imdb.com/title/tt1517225">http://www.imdb.com/title/tt1517225</a><br />
	◎文件格式　DVD-RMVB<br />
	◎视频尺寸　640 x 272<br />
	◎文件大小　2CD 530MB<br />
	◎片　　长　104 Mins<br />
	◎导　　演　Dejan Zecevic<br />
	◎主　　演　Aleksandar Stojkovic ....Cole<br />
	　　　　　　維克&middot;寇斯提克 Vuk Kostic ....Caki<br />
	　　　　　　提喝米尔&middot;斯塔尼克 Tihomir Stanic ....Daba<br />
	　　　　　　Ljubomir Bandovic ....Sirovina<br />
	　　　　　　Marija Pikic ....Danica<br />
	　　　　　　斯拉夫科&middot;斯提马科 Slavko Stimac ....Vesko<br />
	　　　　　　Dragan Marinkovic ....Lik<br />
	　　　　　　Goran Jokic ....Faruk<br />
	　　　　　　Stefan Bundalo ....Guzica<br />
	　　　　　　Vladimir Djordjevic ....Sivi<br />
	　　　　　　Dusko Mazalica ....Jovica<br />
	　　　　　　</p>
<p>
	◎简　　介　</p>
<p>
	<br />
	Shortly after the peace breaks out in Bosnia an engineering unit is removing mines from the border between the two sides who until recently, were at war. They find a man walled into a basement, apparently waiting for them.</p>
<p>
	Bosnia 1995. Seven days after the Dayton Agreement. A small army engineering squad sweeps for mines in the mountains. In a nearby forsaken factory, partially destroyed during the war, they find a walled-in cellar - and in it a man quietly sitting behind a desk, with an ashtray filled with cigarette butts. No food, no water, no light. He looks like has been waiting for them.</p>
<p>
	The squad brings him back to base, despite his dubious sounding story. He refuses food and drink, continuing to smoke his cigarettes. Returning to the factory, the soldiers find a group of dead people, that they&rsquo;re sure weren&rsquo;t there before. Ambushed, they take a captive and bring him too back to camp. When he sees the man from the cellar he tells the squad they have released the devil himself.</p>
<p>
	Powerful cinematography makes full use of the bleak but beautiful open landscapes and decrepit buildings, alternating the loneliness and claustrophobia of the squad&rsquo;s predicament. Surrounded by minefields, and increasingly strange events, the squad&rsquo;s uncertainty about their strange guest takes them closer and closer to the edge.</p>
<p>
	Bosnia, 1995, the seventh day of peace: an engineering unit is removing mines from the border between the two sides who until recently, were at war. Each of the soldiers is burdened by experiences from the frontline; each is facing his fears in his own way. Some are prone to self-destruction while others are happy to be alive. Some are catatonic due to trauma; others take refuge in prayer...</p>
<p>
	不久后，和平爆发在波斯尼亚工程单位是清除地雷从边境双方谁直到最近，在战争。他们发现一个男人进寨地下室，显然等待他们。波斯尼亚的1995。七天之后，代顿协定。小军工程队扫荡矿在山上。在附近的一个被遗弃的工厂，部分在战争中遭到破坏，他们找到一个没有围墙的酒窖里一个人静静地坐在办公桌后面，用一个烟灰缸满了烟蒂。没有食物，没有水，没有光明。他看起来像是等着他们。球队带来他回到基地，尽管他可疑的冠冕堂皇的故事。他拒绝了食物和饮料，继续抽他的烟。回厂，士兵们发现一群死的人，他们肯定不在之前。伏击，他们把俘虏带他回营地去。当他看到那个男人从地窖里他告诉球员他们发布了魔鬼。强大的电影充分利用了凄美的开放的景观，破旧的建筑物，交替的孤独、幽闭的球队的困境。包围的雷区，并越来越奇怪的事件，球队的不确定性的奇怪的客人带他们接近的边缘。波斯尼亚，1995，第七天的和平：一个工程单位是清除地雷从边境双方谁直到最近，在战争。每个战士是背负着经验的一线；每个面对他的恐惧自己的方式。一些容易自毁当别人快乐的活着。有些紧张造成的创伤；别人投靠祈祷&hellip;</p>

<p>
	◎影片截图</p>
<p>
	&nbsp;<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120420/21/56643687201204202113329283137446067_002.jpg" /></p>
<p>
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120420/21/56643687201204202113329283137446067_003.jpg" /></p>
<p>
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120420/21/56643687201204202113329283137446067_000.jpg" /></p>
<p>
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120420/21/56643687201204202113329283137446067_001.jpg" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.netftp//dy44:piaohua@dy44.piaohua.com:3142/" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3263/飘花电影piaohua.com敌人DVD中字CD1.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3263/飘花电影piaohua.com敌人DVD中字CD1.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3263/飘花电影piaohua.com敌人DVD中字CD2.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3263/飘花电影piaohua.com敌人DVD中字CD2.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O163061F-44224.jpg{/dede:field}
