{dede:field name='keywords'}海云台[BD中字1024x576+1280x720{/dede:field}
{dede:field name='description'}海云台[BD中字1024x576+1280x720高清版]迅雷下载、免费下载，海云台[BD中字1024x576+1280x720高清版]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}海云台[BD中字1024x576+1280x720高清版]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2010-06-08{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://4e:4e@www2.eee4.com:732/[www.eee4.cn提供]海云台DVD中字无水印.rmvb" target=_blank>ftftp://4e:4e@www2.eee4.com:732/[www.eee4.cn提供]海云台DVD中字无水印.rmvb</A></TD></TR></TBODY></TABLE><BR><FONT color=#ff0000 size=2><STRONG>[下载地址]：<IMG border=0 src="httftp://www.3edyy.com/templets/img/down.jpg{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MPXN50-34206.jpg{/dede:field}
