<?php
$z[0]=Array("field","海云台[BD中字1024x576+1280x720",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","海云台[BD中字1024x576+1280x720高清版]迅雷下载、免费下载，海云台[BD中字1024x576+1280x720高清版]Gvod高清在线播放，剧情介绍等。",73,241);
$z[1][4]['name']="description";
$z[2]=Array("field","海云台[BD中字1024x576+1280x720高清版]",243,318);
$z[2][4]['name']="title";
$z[3]=Array("field","",320,359);
$z[3][4]['name']="writer";
$z[4]=Array("field","",361,400);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-06-08",402,452);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",454,491);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://4e:4e@www2.eee4.com:732/[www.eee4.cn提供]海云台DVD中字无水印.rmvb\" target=_blank>ftftp://4e:4e@www2.eee4.com:732/[www.eee4.cn提供]海云台DVD中字无水印.rmvb</A></TD></TR></TBODY></TABLE><BR><FONT color=#ff0000 size=2><STRONG>[下载地址]：<IMG border=0 src=\"httftp://www.3edyy.com/templets/img/down.jpg",493,836);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MPXN50-34206.jpg",838,920);
$z[8][4]['name']="litpic";

?>