{dede:field name='keywords'}荒岛情未了BD国语中字1280高清20{/dede:field}
{dede:field name='description'}荒岛情未了BD国语中字1280高清2012中国悬疑惊悚大片迅雷下载、免费下载，荒岛情未了BD国语中字1280高清2012中国悬疑惊悚大片Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}荒岛情未了BD国语中字1280高清2012中国悬疑惊悚大片{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-04-15{/dede:field}
{dede:field name='body'}<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120413/20/56643687201204132040182319679843168_006.jpg" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120413/20/56643687201204132040182319679843168_005.jpg" /></p>
<p>
	导演: 喻瀚湫<br />
	编剧: 喻瀚湫 / 田晓威<br />
	主演: 陈龙 / 曹曦文 / 蒋小涵 / 戴凌鹏<br />
	类型: 悬疑 / 惊悚 / 冒险<br />
	制片国家/地区: 中国大陆<br />
	语言: 汉语普通话<br />
	上映日期: 2012-04-13(中国大陆)<br />
	片长: 99分钟<br />
	又名: LOST</p>
<p>
	剧情简介</p>
<p>
	　　年青帅气的公司CEO、貌美的女经理、&ldquo;五星级饭店&rdquo;主厨以及一班昔日大学同窗在一次聚会上酒醉驾船出海，谁料到一阵突如其来的风暴将这艘豪华游艇击沉。清醒后的他们背流落到一个无名岛屿，迷失荒岛中的他们面临危机四伏的险境，食物短缺加上寄居的山洞崩塌，然而比环境更险恶的是捉摸不透的人心，为了生存，曾经的同学会变成猎人还是猎物，一场大逃杀即将开始.....</p>

<p>
	<br />
	◎影片截图</p>
<p>
	&nbsp;<img src="http://img170.poco.cn/mypoco/myphoto/20120413/20/56643687201204132040182319679843168_003.jpg" style="width: 600px; height: 338px" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120413/20/56643687201204132040182319679843168_000.jpg" style="width: 600px; height: 338px" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120413/20/56643687201204132040182319679843168_004.jpg" style="width: 600px; height: 338px" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120413/20/56643687201204132040182319679843168_002.jpg" style="width: 600px; height: 338px" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120413/20/56643687201204132040182319679843168_001.jpg" style="width: 600px; height: 338px" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.netftp//dy44:piaohua@dy44.piaohua.com:3201/" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3216/飘花电影piaohua.com荒岛情未了DVD国语中字.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3216/飘花电影piaohua.com荒岛情未了DVD国语中字.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3225/飘花电影piaohua.com荒岛情未了BD中字1280高清.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3225/飘花电影piaohua.com荒岛情未了BD中字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O162c060-14920.jpg{/dede:field}
