{dede:field name='keywords'}实习医生格蕾第八季24美剧迅雷下{/dede:field}
{dede:field name='description'}实习医生格蕾第八季24美剧迅雷下载、免费下载，实习医生格蕾第八季24美剧Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}实习医生格蕾第八季24美剧{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-24{/dede:field}
{dede:field name='body'}<p>
	<img alt="" height="720" src="http://home.17996.com/201109/17/1074049_1316271071wBlW.jpg" width="541" /></p>
<p>
	◆原　　名：Grey&#39;s Anatomy Season 8<br />
	◆译　　名：实习医生格蕾 第八季<br />
	◆演　　员：Ellen Pompeo&nbsp; ...&nbsp; Dr. Meredith Grey<br />
	　　　　　　Sandra Oh&nbsp; ...&nbsp; Dr. Cristina Yang<br />
	　　　　　　Justin Chambers&nbsp; ...&nbsp; Dr. Alex Karev<br />
	　　　　　　Chandra Wilson&nbsp; ...&nbsp; Dr. Miranda Bailey<br />
	　　　　　　James Pickens Jr.&nbsp; ...&nbsp; Dr. Richard Webber<br />
	　　　　　　Patrick Dempsey&nbsp; ...&nbsp; Dr. Derek Shepherd<br />
	　　　　　　Sara Ramirez&nbsp; ...&nbsp; Dr. Callie Torres<br />
	　　　　　　Eric Dane&nbsp; ...&nbsp; Dr. Mark Sloan<br />
	　　　　　　Chyler Leigh&nbsp; ...&nbsp; Dr. Lexie Grey<br />
	◆类　　型：剧情 / 医务<br />
	◆国　　家：美国ABC电视台<br />
	◆语　　言：英语<br />
	◆字　　幕：YDY-YTET字幕组出品中文字幕<br />
	◆简　　介：<br />
	　　第七季最后一幕，Meredith一个人抱着领养的女儿Zola试图联系Derek，而Derek则独自躺在为Meredith而造的那尚未成型的&ldquo;梦想之屋&rdquo;里。第八季很有可能将是两位主演在&ldquo;实习医生格蕾&rdquo;剧组的最后一季，这不禁让观众更加好奇&mdash;&mdash;MerDer曾经坚不可摧的爱情将何去何从？Zola的到来能否让两人重归于好呢？而Meredith那岌岌可危的外科生涯又会如何收场？<br />
	　　新一季里的其他角色也都会面临新的挑战。已怀孕六周的Cristina在家庭和事业之间做出了怎样的选择？为了争夺Chief Resident之位而告发Meredith的 Alex成了众矢之的，他又会怎样挽回与Meredith的友谊以及大家的信任？意外成为Chief Resident的April能否胜任这个职位？<br />
	　　敬请关注伊甸园字幕组精心制作的&ldquo;实习医生格蕾&rdquo;，在饱满的角色和精彩的病例之间，剖析生活、思考人生！<br />
	&nbsp;</p>
<p>
	[下载地址]：&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2565/飘花电影piaohua.com实习医生格蕾第八季01-02集[中英双字].rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:2565/飘花电影piaohua.com实习医生格蕾第八季01-02集[中英双字].rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2565/飘花电影piaohua.com实习医生格蕾第八季01-02集[中英双字].rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2565/飘花电影piaohua.com实习医生格蕾第八季03集[中英双字].rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:2565/飘花电影piaohua.com实习医生格蕾第八季03集[中英双字].rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2565/飘花电影piaohua.com实习医生格蕾第八季03集[中英双字].rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2565/飘花电影piaohua.com实习医生格蕾第八季04集[中英双字].rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:2565/飘花电影piaohua.com实习医生格蕾第八季04集[中英双字].rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2565/飘花电影piaohua.com实习医生格蕾第八季04集[中英双字].rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2565/飘花电影piaohua.com实习医生格蕾第八季05集[中英双字].rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:2565/飘花电影piaohua.com实习医生格蕾第八季05集[中英双字].rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2565/飘花电影piaohua.com实习医生格蕾第八季05集[中英双字].rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2565/飘花电影piaohua.com实习医生格蕾第八季06集[中英双字].rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:2565/飘花电影piaohua.com实习医生格蕾第八季06集[中英双字].rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2565/飘花电影piaohua.com实习医生格蕾第八季06集[中英双字].rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2565/飘花电影piaohua.com实习医生格蕾第八季07集[中英双字].rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:2565/飘花电影piaohua.com实习医生格蕾第八季07集[中英双字].rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2565/飘花电影piaohua.com实习医生格蕾第八季07集[中英双字].rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2565/飘花电影piaohua.com实习医生格蕾第八季08集[中英双字].rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:2565/飘花电影piaohua.com实习医生格蕾第八季08集[中英双字].rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2565/飘花电影piaohua.com实习医生格蕾第八季08集[中英双字].rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2565/飘花电影piaohua.com实习医生格蕾第八季09集[中英双字].rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:2565/飘花电影piaohua.com实习医生格蕾第八季09集[中英双字].rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2565/飘花电影piaohua.com实习医生格蕾第八季09集[中英双字].rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2565/飘花电影piaohua.com实习医生格蕾第八季10集[中英双字].rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:2565/飘花电影piaohua.com实习医生格蕾第八季10集[中英双字].rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2565/飘花电影piaohua.com实习医生格蕾第八季10集[中英双字].rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2642/飘花电影piaohua.com实习医生格蕾第八季11集[中英双字].rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:2642/飘花电影piaohua.com实习医生格蕾第八季11集[中英双字].rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2642/飘花电影piaohua.com实习医生格蕾第八季11集[中英双字].rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2699/飘花电影piaohua.com实习医生格蕾第八季12集[中英双字].rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:2699/飘花电影piaohua.com实习医生格蕾第八季12集[中英双字].rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2699/飘花电影piaohua.com实习医生格蕾第八季12集[中英双字].rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2747/飘花电影piaohua.com实习医生格蕾第八季13集[中英双字].rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:2747/飘花电影piaohua.com实习医生格蕾第八季13集[中英双字].rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2747/飘花电影piaohua.com实习医生格蕾第八季13集[中英双字].rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2796/飘花电影piaohua.com实习医生格蕾第八季14集[中英双字].rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:2796/飘花电影piaohua.com实习医生格蕾第八季14集[中英双字].rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2796/飘花电影piaohua.com实习医生格蕾第八季14集[中英双字].rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2841/飘花电影piaohua.com实习医生格蕾第八季15集[中英双字].rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:2841/飘花电影piaohua.com实习医生格蕾第八季15集[中英双字].rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2841/飘花电影piaohua.com实习医生格蕾第八季15集[中英双字].rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2882/飘花电影piaohua.com实习医生格蕾第八季16集[中英双字].rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:2882/飘花电影piaohua.com实习医生格蕾第八季16集[中英双字].rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2882/飘花电影piaohua.com实习医生格蕾第八季16集[中英双字].rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3030/飘花电影piaohua.com实习医生格蕾第八季17集[中英双字].rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3030/飘花电影piaohua.com实习医生格蕾第八季17集[中英双字].rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3030/飘花电影piaohua.com实习医生格蕾第八季17集[中英双字].rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3205/飘花电影piaohua.com实习医生格蕾第八季18集[中英双字].rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3205/飘花电影piaohua.com实习医生格蕾第八季18集[中英双字].rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3205/飘花电影piaohua.com实习医生格蕾第八季18集[中英双字].rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3239/飘花电影piaohua.com实习医生格蕾第八季19集[中英双字].rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3239/飘花电影piaohua.com实习医生格蕾第八季19集[中英双字].rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3239/飘花电影piaohua.com实习医生格蕾第八季19集[中英双字].rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3265/飘花电影piaohua.com实习医生格蕾第八季20集[中英双字].rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3265/飘花电影piaohua.com实习医生格蕾第八季20集[中英双字].rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3265/飘花电影piaohua.com实习医生格蕾第八季20集[中英双字].rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3353/飘花电影piaohua.com实习医生格蕾第八季21集[中英双字].rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3353/飘花电影piaohua.com实习医生格蕾第八季21集[中英双字].rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3353/飘花电影piaohua.com实习医生格蕾第八季21集[中英双字].rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3353/飘花电影piaohua.com实习医生格蕾第八季22集[中英双字].rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3353/飘花电影piaohua.com实习医生格蕾第八季22集[中英双字].rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3353/飘花电影piaohua.com实习医生格蕾第八季22集[中英双字].rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3402/飘花电影piaohua.com实习医生格蕾第八季23集[中英双字].rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3402/飘花电影piaohua.com实习医生格蕾第八季23集[中英双字].rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3402/飘花电影piaohua.com实习医生格蕾第八季23集[中英双字].rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3489/飘花电影piaohua.com实习医生格蕾第八季24集[中英双字].rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3489/飘花电影piaohua.com实习医生格蕾第八季24集[中英双字].rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3489/飘花电影piaohua.com实习医生格蕾第八季24集[中英双字].rmvb</a></td>
		</tr>
	</tbody>
</table>
<p>
	&nbsp;</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1AW420-12512.jpg{/dede:field}
