{dede:field name='keywords'}狐狸与猎狗2BD高清中英双字1024*{/dede:field}
{dede:field name='description'}狐狸与猎狗2BD高清中英双字1024*576迅雷下载、免费下载，狐狸与猎狗2BD高清中英双字1024*576Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}狐狸与猎狗2BD高清中英双字1024*576{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-08-29{/dede:field}
{dede:field name='body'}<p>
	◎译　　名　狐狸与猎狗2<br />
	◎片　　名　The Fox And The Hound 2<br />
	◎年　　代　2006<br />
	◎国　　家　美国<br />
	◎类　　别　动画/家庭<br />
	◎语　　言　英语<br />
	◎字　　幕　N/A<br />
	◎IMDB评分　5.4/10 (697 votes)<br />
	◎IMDB链接　http://www.imdb.com/title/tt0465997/<br />
	◎片　　长　69 mins<br />
	◎导　　演　Jim Kammerud<br />
	◎主　　演　Jeff Bennett&nbsp; ....Additional Voices<br />
	　　　　　　乔纳什&middot;波波 Jonah Bobo&nbsp; ....Tod<br />
	　　　　　　吉姆&middot;库宁斯 Jim Cummings&nbsp; ....Waylon/Floyd (voice)<br />
	　　　　　　Grey DeLisle&nbsp; ....Various (voice)<br />
	　　　　　　Harrison Fahn&nbsp; ....Copper<br />
	　　　　　　杰夫&middot;福克斯沃西 Jeff Foxworthy&nbsp; ....Lyle<br />
	　　　　　　Vicki Lawrence&nbsp; ....Pumi (voice)<br />
	　　　　　　Reba McEntire&nbsp; ....Dixie<br />
	　　　　　　Rob Paulsen&nbsp; ....Chief<br />
	　　　　　　Krista Swan&nbsp; ....Additional Voices<br />
	　　　　　　帕特里克&middot;斯威兹 Patrick Swayze&nbsp; ....Cash<br />
	　　　　　　露西&middot;泰勒 Russi Taylor&nbsp; ....Various (voice)<br />
	　　　　　　April Winchell&nbsp; ....Various (voice)</p>
<p>
	<br />
	◎简　　介<br />
	　　狐狸陶德和猎犬库伯是一对非常要好的朋友，每当库伯觉得自己一无是处的时候，陶德总会鼓励它重拾信心。后来一个猎狗表演团的主唱离开了，声音条件非常好的库伯得到了重用。然而随着库伯越来越走红，陶德开始心怀妒忌，觉得自己被忽视了，两个动物之间的友谊岌岌可危&hellip;&hellip;</p>
<p>
	<img alt="" src="/uploads/allimg/c120525/133O04E9540-151552.jpg" style="width: 640px; height: 360px" /><img alt="" src="/uploads/allimg/c120525/133O04F0430-163143.jpg" style="width: 640px; height: 360px" /><img alt="" src="/uploads/allimg/c120525/133O04F1040-1I3J.jpg" style="width: 640px; height: 360px" /></p>
<p>
	[下载地址]： &nbsp;<img border="0" src="/uploads/allimg/c120524/133N2Z4FF-102231.jpg" /></p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy67:piaohua@dy67.piaohua.com:1059/飘花电影piaohua.com狐狸与猎狗2BD高清中英双字1024分辨率.rmvb</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O04F1J0-1R3b.jpg{/dede:field}
