{dede:field name='keywords'}八面埋伏/死亡特训/埋伏杀机[HD{/dede:field}
{dede:field name='description'}八面埋伏/死亡特训/埋伏杀机[HD中英双字1024x576高清版]迅雷下载、免费下载，八面埋伏/死亡特训/埋伏杀机[HD中英双字1024x576高清版]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}八面埋伏/死亡特训/埋伏杀机[HD中英双字1024x576高清版]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2010-09-08{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://3e:3e@d8.3edyy.com:181/【3E电影院www.eee4.cc】八面埋伏HD中英双字1024x576高清版.rmvb" 

target="_blank{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MP331E0-23203.jpg{/dede:field}
