<?php
$z[0]=Array("field","八面埋伏/死亡特训/埋伏杀机[HD",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","八面埋伏/死亡特训/埋伏杀机[HD中英双字1024x576高清版]迅雷下载、免费下载，八面埋伏/死亡特训/埋伏杀机[HD中英双字1024x576高清版]Gvod高清在线播放，剧情介绍等。",72,270);
$z[1][4]['name']="description";
$z[2]=Array("field","八面埋伏/死亡特训/埋伏杀机[HD中英双字1024x576高清版]",272,362);
$z[2][4]['name']="title";
$z[3]=Array("field","",364,403);
$z[3][4]['name']="writer";
$z[4]=Array("field","",405,444);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-09-08",446,496);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",498,535);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://3e:3e@d8.3edyy.com:181/【3E电影院www.eee4.cc】八面埋伏HD中英双字1024x576高清版.rmvb\" \r\n\r\ntarget=\"_blank",537,685);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MP331E0-23203.jpg",687,770);
$z[8][4]['name']="litpic";

?>