<?php
$z[0]=Array("field","杀手之王[BD国语+粤语中字1024x5",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","杀手之王[BD国语+粤语中字1024x576高清版]迅雷下载、免费下载，杀手之王[BD国语+粤语中字1024x576高清版]Gvod高清在线播放，剧情介绍等。",73,245);
$z[1][4]['name']="description";
$z[2]=Array("field","杀手之王[BD国语+粤语中字1024x576高清版]",247,324);
$z[2][4]['name']="title";
$z[3]=Array("field","",326,365);
$z[3][4]['name']="writer";
$z[4]=Array("field","",367,406);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-03-16",408,458);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",460,497);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://3e:3e@d3.3edyy.com:121/【3E电影院www.eee4.org】杀手之王.1024x548.国粤双语.中文字幕.mkv\" target=_blank>ftftp://3e:3e@d3.3edyy.com:121/【3E电影院www.eee4.org】杀手之王.1024x548.国粤双语.中文字幕.mkv</A></TD></TR></TBODY></TABLE></div><ul class=\"mmlist",499,793);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MQ3K240-462W.jpg",795,877);
$z[8][4]['name']="litpic";

?>