{dede:field name='keywords'}戴夫号飞船/大卫特大号BD中英双{/dede:field}
{dede:field name='description'}戴夫号飞船/大卫特大号BD中英双字1024/1280高清迅雷下载、免费下载，戴夫号飞船/大卫特大号BD中英双字1024/1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}戴夫号飞船/大卫特大号BD中英双字1024/1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-04-27{/dede:field}
{dede:field name='body'}<p>
	<img src="http://pic.piaohua.com/0701pic/allimg/080806/0945140.jpg" /></p>
<p>
	【译　　名】《戴夫号飞船/大卫特大号》08最新艾迪.墨菲喜剧大片DVD中英双字<br />
	【片　　名】Meet Dave<br />
	【年　　代】2008<br />
	【国　　家】美国<br />
	【类　　别】喜剧/科幻<br />
	【语　　言】英语<br />
	【字　　幕】中英双字<br />
	【视频尺寸】800 x 416<br />
	【电影整理】3E迅雷电影下载站(www.eee4.com)<br />
	【文件大小】2CD 409MB<br />
	【片　　长】90 min<br />
	【导　　演】布莱恩&middot;罗宾斯 Brian Robbins<br />
	【主　　演】艾迪&middot;墨菲 Eddie Murphy&nbsp; .....Dave / Captain<br />
	　　　　　　伊丽莎白&middot;班克斯 Elizabeth Banks&nbsp; .....Gina Morrison<br />
	　　　　　　加布里埃尔&middot;尤尼恩 Gabrielle Union&nbsp; .....No. 3&nbsp; Cultural Officer<br />
	　　　　　　艾德&middot;赫尔姆斯 Ed Helms&nbsp; .....No. 2&nbsp; 2nd In Command<br />
	　　　　　　斯科特&middot;凯恩 Scott Caan&nbsp; .....Dooley<br />
	　　　　　　Brandon Molale&nbsp; .....Security Guard<br />
	　　　　　　贾达&middot;弗雷德兰德 Judah Friedlander&nbsp; .....Engineer<br />
	　　　　　　肖恩&middot;克里斯汀 Shawn Christian&nbsp; .....Lieutenant Left Arm<br />
	　　　　　　Yvette Nicole Brown&nbsp; .....Old Navy Saleswoman<br />
	　　　　　　Smith Cho&nbsp; .....Lieutenant Left Leg<br />
	　　　　　　Stephanie Venditto&nbsp; .....MRI Technician<br />
	　　　　　　Adam Tomei&nbsp; .....No. 35<br />
	　　　　　　爱丽森&middot;阿什莉&middot;阿姆 Allisyn Ashley Arm&nbsp; .....Nerdy Girl</p>
<p>
	【简　　介】：</p>
<p>
	　　作为一个刚刚来到纽约这个大城市的新鲜人来说，戴夫不能不算是一个异类，他看上去总有些不太对头。先不要说他对这个城市有多么不适应，而是他的身体和他的大脑似乎都配合不上。这样的格格不入看似匪夷所思，其实有着一个合理的解释：原来戴夫根本就不是人类，他是被一个微型的外星人按照自己的形象而建造出来的宇宙飞船。艾迪&middot;墨菲就在这部家庭喜剧大片《戴夫号飞船》中扮演两个角色－－人形飞船和微型外星船长。</p>
<p>
	　　让我们先来认识一下戴夫，他大概四十岁左右，样貌还算讨喜，但是着装怪异，他总是身穿一身纯白色的礼服，口袋里插着一块叠得整整齐齐得黑色手绢，让人忍不住回忆起上个世纪70年左右那个迪斯科大行其道的遥远年代。除了着装，戴夫身上还有什么地方不太对劲，让人一眼就能看出他是这个城市里的异客。走在纽约的街道上，他的步伐是那么奇怪，一条腿迈出去老远，而另一条腿却不会跟上，他看起来还真是完全没有办法适应自己的身体。</p>
<p>
	　　而在戴夫的身体里实际上驻扎着一支训练有素的精良部队，尽管这些队员们的平均身高只有一又四分之三英寸高，但是他们所有人都心急火燎地想要指挥这个对于他们来说是个庞然大物的奇怪家伙的一言一行。在戴夫身体的每一个部位，都有一个专业的操作员在使用高科技的手段操纵着他的每一个关节和肌肉，但显然这支队伍的配合还有待于更好的磨合。当戴夫喝下他生平第一口水时，船舱内部立刻变成水漫金山；当戴夫想要试试其他的衣服，一件普通的衬衫成了棉质的怪物差点把他憋死；当戴夫去参加最最普通的体检时，一个简单弯腰动作差点让里面的人拼上老命也做不出；当戴夫参加宴会时，一个他刚刚知道叫做热狗的肉肠让男厕所里发生了大爆炸&hellip;&hellip;电影编辑整理：(www.eee4.com)</p>
<p>
	　　正当戴夫号通过种种身体上的斗争慢慢找到了他的航线之时，所有船员们开始经历一种会给他们带来更加深刻打击的遭遇&mdash;&mdash;感情&mdash;&mdash;这种在他们的星球几乎不存在的东西。戴夫号在改变，不光是从里到外，也包括从外到里&hellip;&hellip;</p>

<p>
	【800 x 416 中英双字幕版本截图】：<br />
	电影来源：www.eee4.com<br />
	<img src="http://pic.piaohua.com/0701pic/allimg/080930/1516520.jpg" />&nbsp;<br />
	<img src="http://pic.piaohua.com/0701pic/allimg/080930/1516521.jpg" />&nbsp;<br />
	<img src="http://pic.piaohua.com/0701pic/allimg/080930/1516522.jpg" />&nbsp;<br />
	<img src="http://pic.piaohua.com/0701pic/allimg/080930/1516523.jpg" />&nbsp;<br />
	<img src="http://pic.piaohua.com/0701pic/allimg/080930/1516524.jpg" />&nbsp;<br />
	<img src="http://pic.piaohua.com/0701pic/allimg/080930/1516525.jpg" /></p>
<p>
	【592 x&nbsp;320 中文字幕版本截图】：<br />
	电影来源：www.eee4.com<br />
	<img src="http://pic.piaohua.com/0701pic/allimg/080806/0945380.jpg" />&nbsp;<br />
	<img src="http://pic.piaohua.com/0701pic/allimg/080806/0946360.jpg" />&nbsp;<br />
	<img src="http://pic.piaohua.com/0701pic/allimg/080806/0945491.jpg" /></p>
<p>
	<img border="0" src="http://img.album.pchome.net/54/71/38/66/9460f39f8c9f8ea5d0b955f958b78033.jpg" style="max-width: 750px; max-height: 750px" /></p>
<p>
	<img border="0" src="http://img.album.pchome.net/54/71/38/66/2771220874ebffb6013a110ac02841c2.jpg" style="max-width: 750px; max-height: 750px" /></p>
<p>
	08最新艾迪.墨菲喜剧大片《戴夫号飞船》R5-R中字【592 x 320 中文字幕版】下载地址：<img border="0" src="/templets/img/down.jpg" /></p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<anchor></anchor><a href="ftp://eee4.com:8114@vip11.eee4.com:8114/[3E迅雷电影站www.eee4.com]戴夫号飞船DVD中字.rmvb" target="_blank">ftp://eee4.com:8114@vip11.eee4.com:8114/[3E迅雷电影站www.eee4.com]戴夫号飞船DVD中字.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<anchor></anchor><a href="ftp://e30:e30@xl2.eee4.com:1002/[3E电影站www.eee4.com]戴夫号飞船DVD中英双字CD1.rmvb" target="_blank">ftp://e30:e30@xl2.eee4.com:1002/[3E电影站www.eee4.com]戴夫号飞船DVD中英双字CD1.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<anchor></anchor><a href="ftp://e30:e30@xl2.eee4.com:1002/[3E电影站www.eee4.com]戴夫号飞船DVD中英双字CD2.rmvb" target="_blank">ftp://e30:e30@xl2.eee4.com:1002/[3E电影站www.eee4.com]戴夫号飞船DVD中英双字CD2.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<anchor></anchor><a href="ftp://dy44:piaohua@dy44.piaohua.com:1344/飘花电影piaohua.com戴夫号飞船1024高清.rmvb"><u>ftp://dy44:piaohua@dy44.piaohua.com:1344/飘花电影piaohua.com戴夫号飞船1024高清.rmvb</u></a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<anchor></anchor><a href="ftp://dy44:piaohua@dy44.piaohua.com:3304/飘花电影piaohua.com戴夫号飞船1280高清.rmvb ">ftp://dy44:piaohua@dy44.piaohua.com:3304/飘花电影piaohua.com戴夫号飞船1280高清.rmvb </a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15G1N0-55128.jpg{/dede:field}
