{dede:field name='keywords'}华沙保卫战/1920华沙之战BD1280{/dede:field}
{dede:field name='description'}华沙保卫战/1920华沙之战BD1280高清迅雷下载、免费下载，华沙保卫战/1920华沙之战BD1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}华沙保卫战/1920华沙之战BD1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-02-17{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://www.kochamwies.pl/images/articles/original/14517_1322815351.jpg" style="width: 650px" /></p>
<p>
	【影片名称】：Bitwa warszawska 1920 / Battle of Warsaw 1920<br />
	【中文名称】：华沙保卫战 / 1920华沙之战<br />
	【年 &nbsp; &nbsp; &nbsp;代】：2011年<br />
	【国家地区】：波兰<br />
	【语 &nbsp; &nbsp; &nbsp;言】：波兰语<br />
	【类 &nbsp; &nbsp; &nbsp;别】：战争<br />
	【片 &nbsp; &nbsp; &nbsp;长】：111 分钟<br />
	【上映日期】：2011年9月30日 &nbsp;波兰<br />
	【IMDB链接】：<a href="http://www.imdb.com/title/tt1783244" target="_blank">http://www.imdb.com/title/tt1783244</a><br />
	【IMDB评分】：4.5/10 &nbsp;(284 users)<br />
	【导 &nbsp; &nbsp; &nbsp;演】：耶尔齐&middot;霍夫曼 Jerzy Hoffman<br />
	【编 &nbsp; &nbsp; &nbsp;剧】：耶尔齐&middot;霍夫曼 Jerzy Hoffman &nbsp;....written by<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Jaroslaw Sok&oacute;l &nbsp;....written by<br />
	【主 &nbsp; &nbsp; &nbsp;演】：达尼尔&middot;奥勒布里斯基 Daniel Olbrychski &nbsp;....Jozef Pilsudski<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 米乔&middot;赞布罗斯基 Michal Zebrowski &nbsp;....Wladyslaw Grabski<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Boguslaw Linda &nbsp;....Boleslaw Wieniawa-Dlugoszowski<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 波利斯&middot;席克 Borys Szyc &nbsp;....Jan<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 亚历山大&middot;多莫加罗夫 Aleksandr Domogarov &nbsp;....Kryszkin<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 沃捷希奇&middot;帕斯佐尼亚克 Wojciech Pszoniak &nbsp;....Maxime Weygand<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Adam Ferency &nbsp;....Bukowski<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Ewa Wisniewska &nbsp;....Ada<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 斯坦尼斯拉娃&middot;塞林斯卡 Stanislawa Celinska &nbsp;....Zosia<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 欧嘉&middot;卡波 Olga Kabo &nbsp;....Sofia Nikolajewna<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 马利安&middot;杰德杰尔 Marian Dziedziel &nbsp;....Tadeusz Rozwadowski<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Wiktor Zborowski &nbsp;....Charles de Gaulle<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 鲁卡兹&middot;加里克奇 Lukasz Garlicki &nbsp;....Ignacy Skorupka<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Ewa Wencel &nbsp;....Wieclawska<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;娜塔莎&middot;尤班斯卡 Natasza Urbanska &nbsp;....Ola<br />
	<br />
	<br />
	<br />
	<b>【幕后制作】</b><br />
	<br />
	&nbsp; &nbsp; &nbsp;波兰首部3D片《华沙保卫战》将于9月23日上映。该片反映了1920年波兰人民抵抗苏联红军入侵的著名战役，造价约830万美元，是波兰史上投入最高的影片之一。夹在世界上两个最好战的大国德国与俄罗斯中间的波兰俗称欧洲&ldquo;垫脚布&rdquo;&mdash;&mdash;谁出门都要踩上一脚。正是一个多灾多难的国家对历史有种特殊的偏好，广从电影票房上来看，波兰史上最为卖座的四部影片《剑与火》、《塔杜斯先生》、《你往何处去》以及《卡廷惨案》全都是以历史事件为题材的影片。波兰人民的大国理想也只有通过电影这种艺术形式才能得到伸张和舒展。而这部《华沙保卫战》虽然没什么出奇之处，但从气势恢宏的预告片看到波兰的诗人、歌女、神父统统揭竿而起，对苏联两位领导人描绘也是&ldquo;举重若轻&rdquo;，倒流露一丝浑不吝的气魄。<br />
	<br />
	<br />
	<br />
	<b>【相关资料】</b><br />
	<br />
	&nbsp; &nbsp; &nbsp;<b>战争简介</b><br />
	<br />
	　　苏波战争，指1920年4&mdash;10月苏维埃俄国与波兰之间的战争。苏波战争是由波兰白军首先挑起。1920年4月25日，波兰白军在协约国的怂恿下，多次拒绝了苏俄政府关于和平谈判解决两国争端的建议，对苏俄发动了进攻。同年5月8日，波军占领乌克兰首府基辅。苏联红军奋起反击，于6月中旬收复了基辅，并越过边界向华沙推进。这时波兰和协约国感到大事不妙。7月12日，英国外交大臣寇松照会苏俄政府，建议俄波媾和，但遭到苏俄拒绝。7月17日，苏联红军继续向华沙进攻。8月20日，英国政府又向苏俄发出最后通牒。但最后通牒并未阻止苏俄进军，反而引起英国公众对政府的愤怒。于是英国不得不劝波兰接受苏俄的停战条件，同意和谈。但这时军事形势发生了变化。由于红军高级指挥员之间对于主攻方向判断出现意见分歧，红军在华沙战役中受到重大挫折，波军转守为攻。1920年10月12日，苏波两国在里加签订停战协定，并缔结了预备和约。和约规定，西乌克兰和西白俄罗斯划归波兰，缔约双方彼此尊重国家主权，并保证不支持任何针对另一方的敌对行动。<br />
	<br />
	&nbsp; &nbsp; &nbsp;<b>战争原因</b><br />
	<br />
	　　在历史上，两国一直存在矛盾。俄国未建立之前，波兰作为当时的强国，在1609－1615年多次进攻俄国。在俄罗斯正式建立后，俄国逐渐开始占据上风。1648－1654年，乌克兰与白俄罗斯开始了反对波兰的斗争，俄罗斯乘机予以支持并经过1654－1657年的战争获得了乌克兰第聂伯河左岸地区，基辅也归属于俄罗斯。随后，俄国3次瓜分波兰。到了一战前夕，波兰实际变成俄国的属国。<br />
	<br />
	&nbsp; &nbsp; &nbsp;<b>战争经过</b><br />
	<br />
	&nbsp; &nbsp; &nbsp;<b>波兰进攻</b><br />
	<br />
	　　当苏俄进行国内战争之际，波兰领导人约瑟夫&middot;毕苏斯基希望乘此大好时机重建大波兰－即包括由波兰、波罗的海三国和乌克兰组成的联邦。1919年4 月，毕苏斯基率领波军对苏俄发动了突然进攻。虽然苏军成立了西方面军与之对抗，但由于国内战线形式危机，白俄武装邓尼金和高尔察克东西对进，能用于抵御波兰人的力量极为有限，致使波军在入侵初期长驱直入，获得极大的成功。4 月底波军占领了立陶宛首府维尔纽斯，5 月间毕苏斯基率5 万军队一路奋战通过加利西亚，7 月17日波军抵达兹布鲁奇河，8 月10日白俄罗斯首府明斯克陷落。1920年5 月7 日，乌克兰首府基辅陷落。但由于此时波军战线已长达1000千米，后勤补给日益困难，已成了强弩之末。而此时的苏维埃社会主义共和国已消灭了邓尼金和高尔察克白军武装，得以腾出手来回击波兰侵略军。5 月20日苏军完成战略反攻准备。 战争不可避免。<br />
	<br />
	&nbsp; &nbsp; &nbsp;<b>苏联反攻</b><br />
	<br />
	　　当时，列夫&middot;达维多维奇&middot;托洛茨基任红军最高指挥部&mdash;苏维埃军事委员会&mdash;主席，谢尔盖&middot;谢尔盖耶维奇&middot;加米涅夫负责前敌总指挥。其兵力编为：西方面军由第3 、第4 、第15、第16集团军和盖汗将军指挥的第3 骑兵军组成，方面军司令员米哈伊尔&middot;尼古拉耶维奇&middot;图哈切夫斯基；西南方面军下辖第12、第14两个集团军和布琼尼率领的骑兵第1 集团军，司令员亚历山大&middot;伊里奇&middot;叶戈罗夫。苏军指挥部的战役目的是彻底消灭入侵波军，并攻占华沙。计划规定，以西方面军和西南方面军两个集团的兵力，密切协同，对华沙实施向心突击。图哈切夫斯基的西方面军担任主攻，沿普里皮亚特河的北侧直扑华沙，而西南方面军在河南侧，配合西方面军行动。与西方面军对峙的是波军第1 、第4 集团军，与西南方面军抗衡的是波军第2 、第3 和第6 三个集团军。双方投入的总兵力，苏军约13万人，而波军有17万人左右。（西方面军作战部队88952人，当面波军74850人；西南方面军42877人，当面波军97360人） 从1920年5月下旬到7月上旬，这两路红军势如破竹、所向披靡。收复乌克兰，基本歼灭波军第3集团军并推进到波兰边境。在南路红军中，有一支骑兵军令波兰军人闻风丧胆，他们从克里半亚半岛北部跃进一千公里，攻克乌克兰首府基辅，再突入三百公里，其军长和政委分别是后来也成为苏联元帅的布琼尼和伏罗希洛夫。这支部队的主要成员就是赫赫有名的哥萨克。（参见伊萨克&middot;巴别尔的经历和他的红色骑兵军）<br />
	<br />
	&nbsp; &nbsp; &nbsp;<b>战争目标</b><br />
	<br />
	&nbsp; &nbsp; &nbsp;<b>保卫祖国</b><br />
	<br />
	　　此时，苏俄政府本可以利用有利形势获得对己方较有利边界线且与波兰缔结和约。然而，准备利用红军高昂士气和当时优势帮助波兰建立苏维埃政权的意见占了上风。对于这场战争，当时的布尔什维克领导人发生了一场激烈的争论。托洛茨基坚决反对，认为成功有赖于支持红军的波兰工人的武装起义，但这是一个不可能实现的前提条件。<br />
	<br />
	&nbsp; &nbsp; &nbsp;<b>输出革命</b><br />
	<br />
	　　不过当时占上风的人认为如果不向其他国家输出马克思主义，革命是难以生存下去的。第一次世界大战结束后的欧洲政治局势不稳定导致了短命的萨克森&ldquo;苏维埃共和国&rdquo;的建立，中欧其他地方的革命活动显示输出革命具有十分有利的条件。对于他们而言，德国是关键，因为他被视为欧洲中心。按照英国军事理论家富勒上校的理解：&ldquo;一旦赢得了他，欧洲其他国家将难以为继，必然被征服。&rdquo;而通往德国的路线，波兰是必经之地。 为了激起西欧革命，苏维埃领导人们力图把正义的战争变成积极的阶级进攻战争，他们对前景充满遐想。他们普遍为战争初期的胜利而鼓舞，认为波兰胜利后是德国，进而有望在整个欧洲取得革命胜利。作为最高领导人的列宁也热情高涨，认为：&ldquo;不能只限于俄国一国革命，只有联合其他许多国家战胜国际资本，才能顺利得把革命进行到底，取得绝对的胜利。&rdquo; 在这个精神的感召下，共产国际二大也向所有国家的工人发出号召，与苏俄和波兰的工人团结一致，&ldquo;为了给衰弱的阶级敌人以最后的一击，为了与俄罗斯工人一道进行争取解放的斗争，努力利用本国剥削者的失败。&rdquo; 与此同时，前俄军总司令--战争英雄布鲁西洛夫骑兵上将在1920年5月7日也发表了&ldquo;告各地所有旧军官书&rdquo;，呼吁&ldquo;值此我国人民生死存亡的历史危急关头，。。。恳请你们捐弃前嫌，积极主动参加红军，。。坚决捍卫我们珍爱的俄罗斯。。。&rdquo;图哈切夫斯基准备在7月6日发动最后一次进攻，力求一战定乾坤。总攻开始前，他发表了著名的热情洋溢充满慷慨激情的1423号命令：&ldquo;革命的工人战士们！请把自己的目光转向西方。在西方决定着世界革命的命运。通过白色波兰的尸体铺着引起世界革命大火的道路。在刺刀上我们将给劳动群众带来和平与幸福。向着西方前进！去进行决定性的战斗，去取得伟大胜利！&rdquo;<br />
	<br />
	&nbsp; &nbsp; &nbsp;<b>战争挫折</b><br />
	<br />
	&nbsp; &nbsp; &nbsp;<b>推进顺利</b><br />
	<br />
	　　经过1个月的作战，红军西方面军向华沙方向推进了500公里，几乎到达华沙门口，隔维斯瓦河与波军对峙，然而未能歼灭波军1、4集团军主力，此时，政治形势需要西南方面军向西南进军，以影响罗马尼亚和匈牙利革命，总司令加米涅夫征求西方面军司令图哈切夫斯基的意见，鉴于力量对比对西方面军有利。图哈切夫斯基不但同意两个方面军分离作战，而且担保他的部队能打下并全歼波军。为此他没有集中所属的4个集团军进行正面攻击，而是集中兵力于右翼，用第4、15集团军向西向南进攻维斯瓦河上的波军据点并渡过该河。他的主要目的是攻击波兰守军侧翼与后方，切断波军通过但泽走廊撤退的道路，进而完成他进攻德国的革命抱负。但这样作也把自己的右翼亮了出来，他丝毫没有想到溃败的波军有反攻的可能性，连前线都没有去视察，在后方300公里的明斯克遥控指挥。<br />
	<br />
	&nbsp; &nbsp; &nbsp;<b>问题凸显</b><br />
	<br />
	　　他也没有看到前线部队的困境，整个西方面军的后勤保障只能依靠3 万余辆征集来的小推车运输。所以当军队快速追歼波军时，缓缓而行的后勤淄重队于作战部队脱节。结果前线部队因各种补给品的短缺而士气下降，抢劫，强奸事件层出不穷，又导致了波兰民族主义的强烈反弹。列宁想拯救被波兰地主贵族压迫的波兰工农，结果波兰工农兵和地主贵族却团结起来，一致抗击俄国人，这场&ldquo;世界革命&rdquo;也就成了一场民族战争、一场宗教战争。<br />
	<br />
	&nbsp; &nbsp; &nbsp;<b>损失惨重</b><br />
	<br />
	　　此时，波军在法国顾问帮助下，新建了第5集团军（约3万人），在先前作战中损失较大的第1、4集团军实力也有所恢复。8月13日，红军的第3、16集团军企图一举突破波军华沙防线但未成功。8月14－16日波军第5集团军利用了红军第3、4、15集团军之间的不协调行动，阻止了这些集团军的进攻，在华沙近郊又阻止了第16集团军的前进。8月16日，波军第3、4集团军直插红军第16集团军侧翼，随后波军各集团军转入全线反攻，导致苏军华沙战役的惨败。此次战役，苏军第4集团军全部、第15集团军2个师和第3骑兵军被迫撤入德国东普鲁士境内被解除武装，15、16集团军基本损失，红军损失大约15万人以及火炮230门、机枪1000余挺。<br />
	<br />
	&nbsp; &nbsp; &nbsp;<b>战争结局</b><br />
	<br />
	　　战争的失败在苏俄领导人中间产生很大震动，1920年9月22－25日在俄共（布）第九次代表会议上激烈讨论战争失败原因以及世界革命前景。图哈切夫斯基就西南方面军在战争中表现提出批评，而该方面军政委斯大林在1920年9月23日专门做了声明，阐述他对战争失败的看法以及解释他的责任。而最高领导人列宁思想处于矛盾状态，一方面觉得战争失败可能是犯了战略错误，但另一方面又认为失败主要还是主观原因；与会的大多数人托洛茨基、季诺维也夫、捷尔任斯基、布哈林、加米涅夫、斯大林等都持上述观点。<br />
	<br />
	　　在最初马恩理论中，就有世界革命思想，不过要求各国无产阶级协调行动，并没有武力输出思想。列宁尽管也认同这个思想，但考虑到俄国是经济文化落后的国家，不具备直接实现社会主义条件，需要西方先进国家援助；如果这些国家也是无产阶级掌权，那不必多言。列宁更希望建立世界社会主义联邦。而俄国革命目标是建立统一的世界苏维埃共和国。而苏波战争则成了苏俄推进世界革命的一次实践。<br />
	<br />
	　　这次实践让苏俄付出了沉重的代价，苏联很快调整了自己的对外政策，由世界革命转为和平共处，与周围的爱沙尼亚、拉脱维亚、芬兰、立陶宛签订了和平条约。1921年3月18日，苏波两国签订了里加条约，为两国的紧张局面划上了一个句号，条约对波兰较有利。当然，约20年后，苏军在1939年在德波战争时&ldquo;在当地人民群众广泛的支持下履行了自己的国际主义义务&rdquo;。同年11月，这两个地区加入苏联，重新并入乌克兰共和国和白俄罗斯共和国。<br />
	<br />
	　　在战争中有16000-20000名苏军战俘因饥病死亡,波兰战俘也有大致同等数量战俘死去.<br />
	<img alt="" src="http://img165.poco.cn/mypoco/myphoto/20120217/09/62564813201202170938046334408131022_003.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img165.poco.cn/mypoco/myphoto/20120217/09/62564813201202170938046334408131022_002.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img165.poco.cn/mypoco/myphoto/20120217/09/62564813201202170938046334408131022_001.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img165.poco.cn/mypoco/myphoto/20120217/09/62564813201202170938046334408131022_000.jpg" style="width: 720px; height: 405px" /><br />
	&nbsp;</p>
<p>
	<br />
	<br />
	&nbsp;</p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="&#13;&#10;ftp://dy125:piaohua@dy125.piaohua.com:7616/飘花电影piaohua.com华沙保卫战BD中字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:7616/飘花电影piaohua.com华沙保卫战BD中字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O162K930-4Ra.jpg{/dede:field}
