{dede:field name='keywords'}勾魂慑魄/面对死亡BD1280高清迅{/dede:field}
{dede:field name='description'}勾魂慑魄/面对死亡BD1280高清迅雷下载、免费下载，勾魂慑魄/面对死亡BD1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}勾魂慑魄/面对死亡BD1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-21{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120423/02/62564813201204230219345893964541307_000.jpg" style="width: 507px; height: 639px" /></p>
<p>
	◎译　　名　勾魂慑魄/面对死亡<br />
	◎片　　名　Histoires extraordinaires<br />
	◎年　　代　1968<br />
	◎国　　家　法国<br />
	◎类　　别　恐怖/神秘<br />
	◎语　　言　法语<br />
	◎字　　幕　英文/中文<br />
	◎IMDB评分 6.4/10 (974 votes)<br />
	◎IMDB 链接 <a href="http://www.bluemv.com" title="电影下载">http://www.bluemv.com</a><br />
	◎片　　长　121 mins<br />
	◎导　 &nbsp;演　<br />
	<br />
	费德里科&middot;费里尼 Federico Fellini segment &amp;quot;Toby Dammit&amp;quot;<br />
	路易&middot;马勒 Louis Malle ....1 segment &amp;quot;William Wilson&amp;quot;<br />
	罗杰&middot;瓦迪姆 Roger Vadim ....2 segment &amp;quot;Metzengerstein&amp;quot;<br />
	<br />
	<br />
	◎主　　演　<br />
	碧姬&middot;芭铎 Brigitte Bardot ....Giuseppina (segment &amp;quot;William Wilson&amp;quot:wink:<br />
	阿兰&middot;德龙 Alain Delon ....William Wilson (segment &amp;quot;William Wilson&amp;quot:wink:<br />
	彼得&middot;方达 Peter Fonda ....Baron Wilhelm (segment &amp;quot;Metzengerstein&amp;quot:wink:<br />
	特伦斯&middot;斯坦普 Terence Stamp ....Toby Dammit (segment &amp;quot;Toby Dammit&amp;quot:wink:<br />
	简&middot;方达 Jane Fonda ....Contessa Frederica (segment &amp;quot;Metzengerstein&amp;quot:wink:<br />
	James Robertson Justice ....Countess&#39; Advisor (segment &amp;quot;Metzengerstein&amp;quot:wink:<br />
	Salvo Randone ....Priest (segment &amp;quot;Toby Dammit&amp;quot:wink:<br />
	Fran&ccedil;oise Pr&eacute;vost ....Friend of Countess (segment &amp;quot;Metzengerstein&amp;quot:wink: (as Francoise Prevost)<br />
	<br />
	<br />
	【影片介绍】<br />
	<br />
	&nbsp; &nbsp;全片分三段。第一段由法国名导罗杰&middot;瓦迪姆导演，简&middot;芳达主演，讲述一个骄横的女伯爵，爱上了一匹被情人的鬼魂附身的凶猛种马的故事。中间一段由马勒执导，讲的是19世纪一个叫威廉&middot;威尔森的年轻人，每次作恶都会被一个和他一模一样的人阻止，最后善恶交锋双重死亡的故事。第三段是由意大利的费里尼执导的《该死的托比》，是根据《不要拿你的头跟魔鬼打赌》改编，讲述一个酗酒的电影明星，为了一部法拉利跑车的片酬，到罗马拍摄一部号称第一部天主教西部片的电影，结果在一条公路上被魔鬼化身的小女孩引向死亡之路。<br />
	<br />
	【幕后花絮】<br />
	<br />
	&nbsp; &nbsp;从题材到风格都偏变态（呵呵呵呵）</p>
<p>
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120422/23/62564813201204222309401621317848216_004.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120422/23/62564813201204222309401621317848216_003.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120422/23/62564813201204222309401621317848216_002.jpg" style="width: 720px; height: 405px" /></p>
<p>
	【下载地址】</p>
<table bgcolor="#0099cc" border="0" cellpadding="10" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.net" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy125:piaohua@dy125.piaohua.com:7880/飘花电影piaohua.com勾魂慑魄BD中英双字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:7880/飘花电影piaohua.com勾魂慑魄BD中英双字1280高清.rmvb</a></td>
		</tr>
		<tr>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1512S20-15320.jpg{/dede:field}
