<?php
$z[0]=Array("field","十分爱HD1280高清迅雷下载，免费",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","十分爱HD1280高清迅雷下载、免费下载，十分爱HD1280高清Gvod高清在线播放，剧情介绍等。",73,199);
$z[1][4]['name']="description";
$z[2]=Array("field","十分爱HD1280高清",201,255);
$z[2][4]['name']="title";
$z[3]=Array("field","",257,296);
$z[3][4]['name']="writer";
$z[4]=Array("field","",298,337);
$z[4][4]['name']="source";
$z[5]=Array("field","2012-02-02",339,389);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",391,428);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://3e:3e@d3.3edyy.com:121/【3E电影院www.eee4.org】十分爱HD粤语中字1024x576高清版.rmvb\" target=\"_blank",430,573);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MOS92F-113R.jpg",575,656);
$z[8][4]['name']="litpic";

?>