{dede:field name='keywords'}时间与城市/视与听[DVD中英双字]{/dede:field}
{dede:field name='description'}时间与城市/视与听[DVD中英双字]迅雷下载、免费下载，时间与城市/视与听[DVD中英双字]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}时间与城市/视与听[DVD中英双字]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-22{/dede:field}
{dede:field name='body'}<p>
	◎译　　名　《时间与城市/视与听》08年度十大佳片DVD中英双字<br />
	◎片　　名　Of Time and the City<br />
	◎年　　代　2008<br />
	◎国　　家　英国<br />
	◎类　　别　记录<br />
	◎语　　言　英语<br />
	◎字　　幕　中英双字幕<br />
	◎IMDB评分 7.5/10 (298 votes)<br />
	◎文件格式　RMVB<br />
	◎视频尺寸　576 x 320<br />
	◎文件大小　1CD 49 x 15MB<br />
	◎片　　长　01:13:51<br />
	◎导　　演　<br />
	◎主　　演　<br />
	◎官方网站：<a href="http://www.bluemv.com">http://www.bluemv.com</a><br />
	◎简　　介　<br />
	<br />
	&nbsp;&nbsp;&nbsp; 利物浦，披头四的故乡，也是导演特伦斯&middot;戴维斯的出生地，这是他写给这座城市的情歌与挽歌，弥漫着浓浓的乡愁，呈现出这城市曾经的模样。特伦斯&middot;戴维斯回到家乡拍摄这部纪录片，捕捉时间在城市身上<a href="http://www.eee4.com/" target="_blank">电影下载</a>施给的魔法，用珍贵影像回溯这个城市的历史，绝佳的音乐选用、诗意念白和惆怅影像，堪称近年独特而感性的风格化纪录片。</p>
<p>
	<img alt="" border="0" onload="attachimg(this, 'load')" src="http://c3.ac-images.myspacecdn.com/images02/57/l_62f9b3b2ce0e4b30afca6bf3dd413d3a.jpg" tmooc_h="1" /></p>
<p>
	【电影截图】：<br />
	<br />
	<img alt="" border="0" onload="attachimg(this, 'load')" src="http://img.album.pchome.net/54/69/38/98/1238792107486a042a959de51be8356fa481db8b85.jpg" tmooc_h="1" /><br />
	<img alt="" border="0" onload="attachimg(this, 'load')" src="http://img.album.pchome.net/54/69/38/98/1238792107c81ca887756c692135cbe871d1c7fd9d.jpg" tmooc_h="1" /><br />
	<img alt="" border="0" onload="attachimg(this, 'load')" src="http://img.album.pchome.net/54/69/38/98/12387921072bd10524128ba6b7eeded6023a8f651d.jpg" tmooc_h="1" /><br />
	<img alt="" border="0" onload="attachimg(this, 'load')" src="http://img.album.pchome.net/54/69/38/98/12387921079466bab57a3805598ebe1d5201470d4d.jpg" tmooc_h="1" /><br />
	<img alt="" border="0" onload="attachimg(this, 'load')" src="http://img.album.pchome.net/54/69/38/98/1238792107c66876d73b7b512742bd3b09c8d1cb88.jpg" tmooc_h="1" /><br />
	<img alt="" border="0" onload="attachimg(this, 'load')" src="http://img.album.pchome.net/54/69/38/98/1238792108d767fb536839120933ad6112ec4edf7f.jpg" tmooc_h="1" /></p>
<br />
<p>
	（一律使用<a href="http://www.eee4.com/soft.htm" target="_blank">迅雷下载</a>）<br />
	08年度十大佳片《时间与城市》DVD中英双字 －来自[www.eee4.com]：<img border="0" src="http://www.eee4.com/templets/img/down.jpg" /></p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://e10:e10@xl2.eee4.com:9306/[3E电影站www.eee4.com]时间与城市.rmvb" target="_blank">ftp://e10:e10@xl2.eee4.com:9306/[3E电影站www.eee4.com]时间与城市.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15054060-11O1.jpg{/dede:field}
