{dede:field name='keywords'}叠影谋杀案BD高清中英双字1024/1{/dede:field}
{dede:field name='description'}叠影谋杀案BD高清中英双字1024/1280高清迅雷下载、免费下载，叠影谋杀案BD高清中英双字1024/1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}叠影谋杀案BD高清中英双字1024/1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-04-23{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20110904/00/62564813201109040030303329779824808_000.jpg" /></p>
<p>
	【影片原名】Copycat<br />
	【中文译名】叠影谋杀案/猎影惊魂/凶手就在门外<br />
	【出品公司】Regency Enterprises<br />
	【出品年代】1995 年<br />
	【上映日期】1995年10月27日 美国<br />
	【影片级别】USA:R (certificate #34118) | Iceland:16 | Finland:K-16 (cut) | Finland:K-18 (uncut) | Australia:M (TV rating)<br />
	【IMDB链接】<a href="http://www.imdb.com/title/tt0112722/">http://www.imdb.com/title/tt0112722/</a><br />
	【IMDB评分】6.5/10 (18,411 votes)<br />
	【国　　家】美国<br />
	【类　　别】犯罪/悬疑/惊悚<br />
	【导　　演】乔恩&middot;阿米尔 Jon Amiel<br />
	【主　　演】西格妮&middot;韦弗 Sigourney Weaver&nbsp; ....Helen Hudson<br />
	　　　　　　霍利&middot;亨特 Holly Hunter&nbsp; ....M.J. Monahan<br />
	　　　　　　德蒙特&middot;莫罗尼 Dermot Mulroney&nbsp; ....Reuben Goetz<br />
	　　　　　　小哈里&middot;康尼克 Harry Connick Jr.&nbsp; ....Daryll Lee Cullum<br />
	　　　　　　威尔&middot;帕顿 Will Patton&nbsp; ....Nicoletti<br />
	　　　　　　约翰&middot;罗斯曼 John Rothman&nbsp; ....Andy<br />
	　　　　　　William McNamara&nbsp; ....Peter Foley<br />
	　　　　　　J.E. Freeman&nbsp; ....Lt. Thomas Quinn<br />
	　　　　　　Shannon O Hurley&nbsp; ....Susan Schiffer<br />
	　　　　　　Bob Greene&nbsp; ....Pachulski<br />
	　　　　　　Tony Haney&nbsp; ....Kerby<br />
	　　　　　　Danny Kovacs&nbsp; ....Kostas<br />
	　　　　　　Tahmus Rounds&nbsp; ....Landis<br />
	　　　　　　Scott DeVenney&nbsp; ....Cop #1<br />
	　　　　　　David Michael Silverman&nbsp; ....Mike</p>
<p>
	【影片长度】123 Mins<br />
	【对白语言】英语<br />
	【内容简介】</p>
<p>
	　　女犯罪心理学家凯伦博士在演讲后遭到杀手威胁。幸亏警察及时赶到,杀手在杀害警察后被捕。凯伦幸免于难,但却因受到惊吓而患恐惧症。她不敢走出家门一步,而只能依靠电脑在家里从事工作。</p>
<p>
	　　一年后,女警探珍妮接手了几起杀人案件,但却无法查出真相。她竭尽全力才说服隐居的凯伦参与此案的调查。经过细节查证,凯伦发现这些案件的凶手是一个专门模仿其他凶杀案的变态杀手。他自称连环杀手,并将被杀对象的资料传送到凯伦的电脑上。杀手还潜入了凯伦的住宅,并留下一本书给凯伦,而这本书则是一年前想杀凯伦而被捕入狱的那个杀手所写的。凯伦很想放弃。但在珍妮的劝阻下,她终于鼓起勇气。她下决心去狱中会见那位杀手,并从他那里得到了资料。</p>
<p>
	　　但当警察包围连环杀手的住宅时,却发现他已经离开了。连环杀手假扮警察闯进了凯伦的家,将凯伦绑了起来,想按照一年前那个杀手的方法对待凯伦。危急之时,珍妮及时赶到,但却中枪倒地。凯伦乘机逃跑,但最终在天台上走投无路。正当凶手要用刀刺杀凯伦时,珍妮击毙了凶手。原来她穿了防弹衣。</p>
<p>
	一句话评论</p>
<p>
	　　One man is copying the most notorious killers in history one at a time. Together, two women must stop him from killing again. Or they re next.</p>
<p>
	幕后制作</p>
<p>
	　　&ldquo;跟观众玩猜谜游戏&rdquo;是令《惊声尖叫》大受年轻观众欢迎的主要原因。本片编导其实更早想出这种与观众互动的噱头,不过他们采用的手法是将恐怖片中最著名的冷血凶手都集中在男主角身上,由他来模仿每个凶手的杀人风格,用不同的方式杀人。</p>
<p>
	&nbsp;<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20110904/00/62564813201109040030303329779824808_002.jpg" style="width: 600px; height: 338px" /></p>
<p>
	<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20110904/00/62564813201109040030303329779824808_001.jpg" style="width: 600px; height: 338px" /></p>

<p>
	<img alt="" border="0" src="http://img.album.pchome.net/48/56/19/44/8bd496ea3000a41cf83bd7a5ab114afc.jpg" /></p>
<p>
	<img alt="" border="0" src="http://img.album.pchome.net/48/56/19/44/e6ff37f43d314a049ee6ef4d5340ac0f.jpg" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="&#13;&#10;ftp://dy125:piaohua@dy125.piaohua.com:2087/飘花电影piaohua.com叠影谋杀案BD高清中英双字1024分辨率.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:2087/飘花电影piaohua.com叠影谋杀案BD高清中英双字1024分辨率.rmvb </a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3275/飘花电影piaohua.com叠影谋杀案BD高清中英双字1280高清.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3275/飘花电影piaohua.com叠影谋杀案BD高清中英双字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O160H430-25A7.jpg{/dede:field}
