{dede:field name='keywords'}心术国产剧第36集2012热播电视剧{/dede:field}
{dede:field name='description'}心术国产剧第36集2012热播电视剧迅雷下载、免费下载，心术国产剧第36集2012热播电视剧Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}心术国产剧第36集2012热播电视剧{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-21{/dede:field}
{dede:field name='body'}<p>
	<img src="http://img.funshion.com/attachment/new_images/2012/05-02/18395589_1335948232_47.jpg" /></p>
<p>
	<img src="http://img.funshion.com/attachment/new_images/2012/01-05/22849942_1325742576_94.jpg" /></p>
<p>
	【片　　名】：心术<br />
	【地　　区】：中国<br />
	【年　　代】：2012<br />
	【类　　型】：现代/都市/医学<br />
	【集　　数】：待定<br />
	【语　　言】：普通话<br />
	【字　　幕】：简体中文<br />
	【导　　演】：<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 杨阳<br />
	【编　　剧】：<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 六六<br />
	【主要角色】：<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 吴秀波　海　清　张嘉译<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 翟天临　韩雨芹　于　毅<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 张子枫　杨　紫　王诗槐</p>

<p>
	<br />
	【剧情简介】：<br />
	&nbsp; 神经外科医生霍思邈因工作繁忙屡屡恋爱失败，感情受挫时，与科室同事美小护的情感发生着微妙地变化，而此时，女演员小芹因母亲生病住院来到医院，霍思邈对她一见钟情，美小护藏起心中真意为霍思邈出谋划策。</p>
<p>
	　　为帮助霍思邈追求小芹，师弟郑艾平为小芹的母亲检查，不想真的在她脑中查出肿瘤。面对不一定非手术治疗不可的情况，霍思邈却坚持进行手术，师兄刘晨曦指责霍思邈此举出于私心，是想要在小芹面前表现，两人不欢而散。</p>
<p>
	　　刘晨曦以&ldquo;仁心仁术&rdquo;受到医生同行和患者的欢迎，他的女儿却身患肾衰竭，正在刘晨曦夫妇焦急等待肾源时，一场车祸让一个女孩濒临死亡，她的肾脏和南南匹配，但女孩的父母拒绝捐献器官，赵文谷过往的追求者&mdash;&mdash;另一个科室的医生决定私自将肾脏取出移植给南南，产生的责任一己承担，而刘晨曦拒绝了这样的做法，为女孩拔管，将女孩完整地还给孩子的父母。霍思邈和郑艾平认为刘晨曦缺乏救自己女儿的担当，然而刘晨曦的话语让两人意识到一颗真正的医者仁心，可刘晨曦女儿却错失了得到肾源的机会。</p>
<p>
	　　小芹母亲的手术顺利进行，开颅后众人发现问题严重，这是一个必要手术的案例，刘晨曦意识到自己对霍思邈的误解，诚挚道歉。而随着小芹母亲痊愈，她和霍思邈的感情也渐渐确立，因为和身为演员的小芹缺乏话题，霍思邈求教于美小护，美小护心中虽有隐隐酸意，却仍不动声色地帮哥们儿出谋划策&hellip;&hellip;</p>
<p>
	　　神经外科里的故事一直在上演着，形形色色的病人，有人黯然离开、有人知恩图报，有人和解，有人纠结致死。刘晨曦和赵文谷坚守着自己的原则和道德，终感动了上天也得到了好报；霍思邈在经历了跟小芹荡气回肠的激情之后，渐渐明白了爱情的真谛，开始了与美小护的恋情。</p>
<p>
	　　他们在自己的生活中成长着，也在和病人的相处中渐渐完善自己的&ldquo;仁心仁术&rdquo;。在女儿痊愈后，刘晨曦向着副教授的职务努力着，在跟一个长期不稳定的女病患以及她的家属的纠缠中，郑艾平从一个住院医生成长为一个主治医生，冷若冰霜的护士孤美人，在得了一场大病之后，明白了如何温暖地关爱病人。</p>
<p>
	　　这些工作在神经外科的医生、护士，在他们各自的人生道路上经历着一次又一次的成长与升华，在医院的大舞台上完善着医界的&ldquo;仁心仁术&rdquo;。</p>
<p>
	<img src="http://img.funshion.com/attachment/new_images/2012/04-28/22849942_1335592010_899.jpg" /></p>
<p>
	<img src="http://img.funshion.com/attachment/new_images/2012/04-28/22849942_1335592011_847.jpg" /></p>
<p>
	<img src="http://img.funshion.com/attachment/new_images/2012/04-28/22849942_1335592004_502.jpg" width="650" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.net/" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3361/飘花电影piaohua.com心术01.HDTV.rmvb">&nbsp;ftp://dy44:piaohua@dy44.piaohua.com:3361/飘花电影piaohua.com心术01.HDTV.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3361/飘花电影piaohua.com心术02.HDTV.rmvb">&nbsp;ftp://dy44:piaohua@dy44.piaohua.com:3361/飘花电影piaohua.com心术02.HDTV.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3361/飘花电影piaohua.com心术03.HDTV.rmvb">&nbsp;ftp://dy44:piaohua@dy44.piaohua.com:3361/飘花电影piaohua.com心术03.HDTV.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3361/飘花电影piaohua.com心术04.HDTV.rmvb">&nbsp;ftp://dy44:piaohua@dy44.piaohua.com:3361/飘花电影piaohua.com心术04.HDTV.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3361/飘花电影piaohua.com心术05.HDTV.rmvb">&nbsp;ftp://dy44:piaohua@dy44.piaohua.com:3361/飘花电影piaohua.com心术05.HDTV.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3361/飘花电影piaohua.com心术06.HDTV.rmvb">&nbsp;ftp://dy44:piaohua@dy44.piaohua.com:3361/飘花电影piaohua.com心术06.HDTV.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3361/飘花电影piaohua.com心术07.HDTV.rmvb">&nbsp;ftp://dy44:piaohua@dy44.piaohua.com:3361/飘花电影piaohua.com心术07.HDTV.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3361/飘花电影piaohua.com心术08.HDTV.rmvb">&nbsp;ftp://dy44:piaohua@dy44.piaohua.com:3361/飘花电影piaohua.com心术08.HDTV.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3369/飘花电影piaohua.com心术09.HDTV.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3369/飘花电影piaohua.com心术09.HDTV.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3369/飘花电影piaohua.com心术09.HDTV.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3369/飘花电影piaohua.com心术10.HDTV.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3369/飘花电影piaohua.com心术10.HDTV.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3369/飘花电影piaohua.com心术10.HDTV.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3398/飘花电影piaohua.com心术11.HDTV.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3398/飘花电影piaohua.com心术11.HDTV.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3398/飘花电影piaohua.com心术11.HDTV.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3398/飘花电影piaohua.com心术12.HDTV.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3398/飘花电影piaohua.com心术12.HDTV.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3398/飘花电影piaohua.com心术12.HDTV.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3398/飘花电影piaohua.com心术13.HDTV.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3398/飘花电影piaohua.com心术13.HDTV.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3398/飘花电影piaohua.com心术13.HDTV.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3398/飘花电影piaohua.com心术14.HDTV.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3398/飘花电影piaohua.com心术14.HDTV.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3398/飘花电影piaohua.com心术14.HDTV.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3398/飘花电影piaohua.com心术15.HDTV.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3398/飘花电影piaohua.com心术15.HDTV.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3398/飘花电影piaohua.com心术15.HDTV.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3398/飘花电影piaohua.com心术16.HDTV.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3398/飘花电影piaohua.com心术16.HDTV.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3398/飘花电影piaohua.com心术16.HDTV.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3398/飘花电影piaohua.com心术17.HDTV.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3398/飘花电影piaohua.com心术17.HDTV.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3398/飘花电影piaohua.com心术17.HDTV.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3398/飘花电影piaohua.com心术18.HDTV.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3398/飘花电影piaohua.com心术18.HDTV.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3398/飘花电影piaohua.com心术18.HDTV.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3406/飘花电影piaohua.com心术19.HDTV.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3406/飘花电影piaohua.com心术19.HDTV.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3406/飘花电影piaohua.com心术19.HDTV.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3406/飘花电影piaohua.com心术20.HDTV.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3406/飘花电影piaohua.com心术20.HDTV.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3406/飘花电影piaohua.com心术20.HDTV.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3410/飘花电影piaohua.com心术21.HDTV.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3410/飘花电影piaohua.com心术21.HDTV.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3410/飘花电影piaohua.com心术21.HDTV.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3410/飘花电影piaohua.com心术22.HDTV.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3410/飘花电影piaohua.com心术22.HDTV.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3410/飘花电影piaohua.com心术22.HDTV.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3422/飘花电影piaohua.com心术23.HDTV.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3422/飘花电影piaohua.com心术23.HDTV.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3422/飘花电影piaohua.com心术23.HDTV.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3422/飘花电影piaohua.com心术24.HDTV.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3422/飘花电影piaohua.com心术24.HDTV.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3422/飘花电影piaohua.com心术24.HDTV.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3429/飘花电影piaohua.com心术25.HDTV.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3429/飘花电影piaohua.com心术25.HDTV.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3429/飘花电影piaohua.com心术25.HDTV.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3429/飘花电影piaohua.com心术26.HDTV.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3429/飘花电影piaohua.com心术26.HDTV.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3429/飘花电影piaohua.com心术26.HDTV.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3436/飘花电影piaohua.com心术27.HDTV.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3436/飘花电影piaohua.com心术27.HDTV.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3436/飘花电影piaohua.com心术27.HDTV.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3436/飘花电影piaohua.com心术28.HDTV.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3436/飘花电影piaohua.com心术28.HDTV.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3436/飘花电影piaohua.com心术28.HDTV.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3447/飘花电影piaohua.com心术29.HDTV.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3447/飘花电影piaohua.com心术29.HDTV.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3447/飘花电影piaohua.com心术29.HDTV.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3447/飘花电影piaohua.com心术30.HDTV.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3447/飘花电影piaohua.com心术30.HDTV.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3447/飘花电影piaohua.com心术30.HDTV.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3452/飘花电影piaohua.com心术31.HDTV.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3452/飘花电影piaohua.com心术31.HDTV.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3452/飘花电影piaohua.com心术31.HDTV.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3452/飘花电影piaohua.com心术32.HDTV.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3452/飘花电影piaohua.com心术32.HDTV.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3452/飘花电影piaohua.com心术32.HDTV.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3463/飘花电影piaohua.com心术33.HDTV.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3463/飘花电影piaohua.com心术33.HDTV.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3463/飘花电影piaohua.com心术33.HDTV.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3463/飘花电影piaohua.com心术34.HDTV.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3463/飘花电影piaohua.com心术34.HDTV.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3463/飘花电影piaohua.com心术34.HDTV.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3466/飘花电影piaohua.com心术35.HDTV.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3466/飘花电影piaohua.com心术35.HDTV.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3466/飘花电影piaohua.com心术35.HDTV.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3466/飘花电影piaohua.com心术36.HDTV.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3466/飘花电影piaohua.com心术36.HDTV.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3466/飘花电影piaohua.com心术36.HDTV.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1AAF-2NR.jpg{/dede:field}
