{dede:field name='keywords'}地狱骑士(导演剪辑版)高清BDRIP{/dede:field}
{dede:field name='description'}地狱骑士(导演剪辑版)高清BDRIP中字2011最新日本科幻恐怖大片迅雷下载、免费下载，地狱骑士(导演剪辑版)高清BDRIP中字2011最新日本科幻恐怖大片Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}地狱骑士(导演剪辑版)高清BDRIP中字2011最新日本科幻恐怖大片{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-01{/dede:field}
{dede:field name='body'}<p>
	&nbsp;<img src="http://img170.poco.cn/mypoco/myphoto/20120501/16/56643687201205011610193613277580619_004.jpg" /></p>
<p>
	◎译　　名　地狱骑士(导演剪辑版)<br />
	◎片　　名　Helldriver<br />
	◎年　　代　2011<br />
	◎国　　家　日本<br />
	◎类　　别　科幻/恐怖<br />
	◎语　　言　日语<br />
	◎字　　幕　中文<br />
	◎IMDB评分 5.5/10 from 318 users<br />
	◎IMDB链接 <a href="http://www.imdb.com/title/tt1653913">http://www.imdb.com/title/tt1653913</a><br />
	◎文件格式　高清BDRIP-RMVB<br />
	◎视频尺寸　624 x 352<br />
	◎文件大小　1CD 687MB<br />
	◎片　　长　117 Mins<br />
	◎导　　演　西村喜广 Yoshihiro Nishimura<br />
	◎主　　演　亚纱美 Asami ....Wall guard<br />
	　　　　　　红井幸秀 Yukihide Benny ....Man on the wall<br />
	　　　　　　Norman England ....Annoyed patron<br />
	　　　　　　福田裕彦 Yasuhiko Fukuda<br />
	　　　　　　Yumiko Hara ....Kika<br />
	　　　　　　泉海 Kai Izumi ....Zombie mom<br />
	　　　　　　岸建太朗 Kentaro Kishi ....(as Kentar? Kishi)<br />
	　　　　　　Mizuki Kusumi ....Nanashi<br />
	　　　　　　Sayako Nakoshi<br />
	　　　　　　村田唯 Yui Murata ....Zombie<br />
	　　　　　　波冈一喜 Kazuki Namioka<br />
	　　　　　　椎名英姬 Eihi Shiina ....Rikka<br />
	　　　　　　Shijimi<br />
	　　　　　　井口薰仁 Gadarukanaru Taka<br />
	　　　　　　田中德摩 Demo Tanaka ....Desperate man in cage<br />
	　　　　　　鸟肌实 Minoru Torihada<br />
	　　　　　　Marc Walkow ....Doctor<br />
	　　　　　　柳忧怜 Y?rei Yanagi ....Taku<br />
	　　　　　　</p>
<p>
	<br />
	◎简　　介　</p>
<p>
	　　由于厌倦了母亲（椎名英姬 饰）和叔叔无休止的杀戮行为，少女宫田喜花（原裕美子 饰）选择逃离这个充满血腥的家庭。可是她很快被母亲找到，并遭到残忍的报复和虐待。正在此时，一颗突然降落的彗星击穿母亲的身体，而母亲更摘除了喜花的心脏。彗星随即散发了覆盖日本东北部的烟尘，所有呼吸了烟尘的人类全部变成嗜血如命的丧尸。3日后，烟尘散尽，日本由于丧尸的存在被分为南北两部分。政客鼓吹丧尸的人权、贪婪的人类利用丧尸的角赚钱、阴谋家妄图夺取大权&hellip;&hellip;整个日本陷入一片混乱之中。</p>
<p>
	　　濒临死亡的喜花则被政客改造成了装备超强动力心脏和武器的人造人，她从昏迷中苏醒，与邪恶的丧尸展开了连番恶战&hellip;&hellip;</p>
<p>
	<br />
	◎影片截图</p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120501/16/56643687201205011610193613277580619_001.jpg" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120501/16/56643687201205011610193613277580619_003.jpg" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120501/16/56643687201205011610193613277580619_000.jpg" /></p>
<p>
	&nbsp;<img src="http://img170.poco.cn/mypoco/myphoto/20120501/16/56643687201205011610193613277580619_002.jpg" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.netftp://dy44:piaohua@dy44.piaohua.com:3327/" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3330/飘花电影piaohua.com地狱骑士(导演剪辑版)高清BDRIP中字.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3330/飘花电影piaohua.com地狱骑士(导演剪辑版)高清BDRIP中字.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15940950-332H.jpg{/dede:field}
