<?php
$z[0]=Array("field","喋血双雄[BD粤语中字1024x560高",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","喋血双雄[BD粤语中字1024x560高清版]迅雷下载、免费下载，喋血双雄[BD粤语中字1024x560高清版]Gvod高清在线播放，剧情介绍等。",72,234);
$z[1][4]['name']="description";
$z[2]=Array("field","喋血双雄[BD粤语中字1024x560高清版]",236,308);
$z[2][4]['name']="title";
$z[3]=Array("field","",310,349);
$z[3][4]['name']="writer";
$z[4]=Array("field","",351,390);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-03-27",392,442);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",444,481);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://5e:5e@m1.3edyy.com:1444/【3E电影院www.eee4.cc】喋血双雄BD粤语中字1024x560高清版.rmvb\" target=\"_blank",483,628);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MQ340920-1X62.jpg",630,713);
$z[8][4]['name']="litpic";

?>