{dede:field name='keywords'}喋血双雄[BD粤语中字1024x560高{/dede:field}
{dede:field name='description'}喋血双雄[BD粤语中字1024x560高清版]迅雷下载、免费下载，喋血双雄[BD粤语中字1024x560高清版]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}喋血双雄[BD粤语中字1024x560高清版]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2010-03-27{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://5e:5e@m1.3edyy.com:1444/【3E电影院www.eee4.cc】喋血双雄BD粤语中字1024x560高清版.rmvb" target="_blank{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MQ340920-1X62.jpg{/dede:field}
