<?php
$z[0]=Array("field","新天生一对HD国语中字1280高清周",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","新天生一对HD国语中字1280高清周渝民 杨幂2012最新喜剧迅雷下载、免费下载，新天生一对HD国语中字1280高清周渝民 杨幂2012最新喜剧Gvod高清在线播放，剧情介绍等。",73,269);
$z[1][4]['name']="description";
$z[2]=Array("field","新天生一对HD国语中字1280高清周渝民 杨幂2012最新喜剧",271,360);
$z[2][4]['name']="title";
$z[3]=Array("field","",362,401);
$z[3][4]['name']="writer";
$z[4]=Array("field","",403,442);
$z[4][4]['name']="source";
$z[5]=Array("field","2012-03-31",444,494);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",496,533);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://dy44:piaohua@dy44.piaohua.com:3109/飘花电影piaohua.com新天生一对HD国语中字1280高清.rmvb",535,667);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MOB0S0-225F.jpg",669,750);
$z[8][4]['name']="litpic";

?>