{dede:field name='keywords'}鬼玩人2/人玩鬼II/尸变2/人玩鬼2{/dede:field}
{dede:field name='description'}鬼玩人2/人玩鬼II/尸变2/人玩鬼2[BD中英双字1024x576高清版]迅雷下载、免费下载，鬼玩人2/人玩鬼II/尸变2/人玩鬼2[BD中英双字1024x576高清版]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}鬼玩人2/人玩鬼II/尸变2/人玩鬼2[BD中英双字1024x576高清版]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2010-12-01{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://3e:3e@d3.3edyy.com:121/【3E电影院www.eee4.org】鬼玩人2[BD中英双字1024x576高清版].rmvb" target=_blank>ftftp://3e:3e@d3.3edyy.com:121/【3E电影院www.eee4.org】鬼玩人2[BD中英双字1024x576高清版].rmvb</A></TD></TR></TBODY></TABLE></div><ul class="mmlist{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MQ3E130-2X34.jpg{/dede:field}
