<?php
$z[0]=Array("field","鬼玩人2/人玩鬼II/尸变2/人玩鬼2",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","鬼玩人2/人玩鬼II/尸变2/人玩鬼2[BD中英双字1024x576高清版]迅雷下载、免费下载，鬼玩人2/人玩鬼II/尸变2/人玩鬼2[BD中英双字1024x576高清版]Gvod高清在线播放，剧情介绍等。",73,279);
$z[1][4]['name']="description";
$z[2]=Array("field","鬼玩人2/人玩鬼II/尸变2/人玩鬼2[BD中英双字1024x576高清版]",281,375);
$z[2][4]['name']="title";
$z[3]=Array("field","",377,416);
$z[3][4]['name']="writer";
$z[4]=Array("field","",418,457);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-12-01",459,509);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",511,548);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://3e:3e@d3.3edyy.com:121/【3E电影院www.eee4.org】鬼玩人2[BD中英双字1024x576高清版].rmvb\" target=_blank>ftftp://3e:3e@d3.3edyy.com:121/【3E电影院www.eee4.org】鬼玩人2[BD中英双字1024x576高清版].rmvb</A></TD></TR></TBODY></TABLE></div><ul class=\"mmlist",550,842);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MQ3E130-2X34.jpg",844,926);
$z[8][4]['name']="litpic";

?>