{dede:field name='keywords'}逃妻七日情BD1280高清迅雷下载，{/dede:field}
{dede:field name='description'}逃妻七日情BD1280高清迅雷下载、免费下载，逃妻七日情BD1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}逃妻七日情BD1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-04-25{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://imgly.net/di-FUNY.jpg" style="width: 580px; height: 745px" /></p>
<p>
	【影片原名】Yang ngai gaw rak<br />
	【外文别名】7 Days to Leave My Wife (International: English title)<br />
	【中文译名】逃妻七日情<br />
	【出品公司】A.G. Entertainment<br />
	【出品年代】2007 年<br />
	【上映日期】2007年3月1日 &nbsp;泰国<br />
	【官方网站】<a class="faqlink" endcolor="FF6600" href="http://www.sevendaysmovie.com/#" index="0" startcolor="0066ff" state="OFF" style="color: #0066ff">http://www.sevendaysmovie.com/#</a><br />
	【IMDB链接】<a class="faqlink" endcolor="FF6600" href="http://www.imdb.com/title/tt0989732" index="0" startcolor="0066ff" state="OFF" style="color: #0066ff">http://www.imdb.com/title/tt0989732</a><br />
	【IMDB评分】7.8/10 (8 votes)<br />
	【国　　家】泰国<br />
	【类　　别】爱情/喜剧<br />
	【导　　演】Torpong Tunkamhang<br />
	【主　　演】Samapon Piyapongsiri ....Yong<br />
	　　　　　　Suwatjanee Chaimusik ....Ngak<br />
	　　　　　　Benjawan Artner ....Pim<br />
	　　　　　　Prinya Rhunprapan ....Hia Lhee<br />
	　　　　　　Jatupon Chompoonit<br />
	　　　　　　Sophia La ....Ganda<br />
	　　　　　　Panissara Phimpru<br />
	◎简　　介　<br />
	勇裕是个平凡再不过的上班族，跟老婆玉儿结缡七年，最近心情开始烦燥难耐，感觉就是俗话的「七年之痒」犯了，每天看着日渐发黄的糟糠妻，勇裕厌倦之心油然而生&hellip;正在此时，公司来了个俗称狐狸精的妖艳美女小萍，也不知看上勇裕哪点的小萍，两个居然就乾材烈火起来&hellip;。<br />
	　　小萍绝对不是省油的灯，郑重要求勇裕跟妻子玉儿分手，被迷惑的他二话不说便决心与妻子分手，但脑中雄雄想到已过世的父亲断气前的遗言：你要一辈子跟玉儿厮守到老，不然做鬼也不放过你，说不定还让你阳萎下半生。正想要大展雄风的勇裕怎麽可能让这麽狼狈，便突发奇想做尽坏事让老婆主动离开自己；不料迷信的玉儿居然听信算命仙的话以为老公着魔，对他更加温柔体贴&hellip;。<br />
	　　勇裕实在无计可施，便决定在七日之内进行逃妻计画&hellip;</p>
<p>
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120424/23/62564813201204242315116871773145780_002.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120424/23/62564813201204242315116871773145780_001.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120424/23/62564813201204242315116871773145780_000.jpg" style="width: 720px; height: 405px" /><br />
	<br />
	&nbsp;</p>
<p>
	【下载地址】</p>
<table bgcolor="#0099cc" border="0" cellpadding="10" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.net" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy125:piaohua@dy125.piaohua.com:7889/飘花电影piaohua.com逃妻七日情BD中字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:7889/飘花电影piaohua.com逃妻七日情BD中字1280高清.rmvb</a></td>
		</tr>
		<tr>
		</tr>
	</tbody>
</table>
<br />{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15E9E0-26424.jpg{/dede:field}
