{dede:field name='keywords'}宗教的荒谬[DVD中字无水印]迅雷{/dede:field}
{dede:field name='description'}宗教的荒谬[DVD中字无水印]迅雷下载、免费下载，宗教的荒谬[DVD中字无水印]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}宗教的荒谬[DVD中字无水印]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-22{/dede:field}
{dede:field name='body'}<p>
	◎译　　名　《宗教的荒谬》美国08最新高分纪录片DVD中字无水印<br />
	◎片　　名　Religulous<br />
	◎年　　代　2008<br />
	◎国　　家　美国<br />
	◎类　　别　记录<br />
	◎语　　言　英语<br />
	◎字　　幕　中文<br />
	◎IMDB评分 7.7/10 7,883 votes<br />
	◎IMDB链接 <a href="http://www.bluemv.com">http://www.bluemv.com</a><br />
	◎文件格式　DVDrip-RMVB<br />
	◎视频尺寸　624 x 352<br />
	◎文件大小　1CD<br />
	◎片　　长　1:41:01<br />
	◎导　　演　拉里&middot;查尔斯 Larry Charles<br />
	◎主　　演　比尔&middot;马赫 Bill Maher<br />
	　　　　　　Jose Luis De Jesus Miranda ....Himself<br />
	　　　　　　Steve Berg ....Himself<br />
	　　　　　　Andrew Newberg ....Himself<br />
	<br />
	◎简　　介　<br />
	<br />
	<br />
	<br />
	美国的喜剧演员比尔&middot;马赫带领观众亲临各种近年来发生宗教事件的现场，展示了穆斯林教、基督教、科学教等的现状。<br />
	<br />
	这部影片的名字是&ldquo;宗教&rdquo;和&ldquo;荒唐&rdquo;两个词的结合，该片以批判的态度审视了基督教、犹太教和伊斯兰教的根源，以<a href="/" target="_blank">电影下载</a>及它们对日常生活和政治领导人的决策和行为的影响。<br />
	<br />
	　　当被问及这部影片想要告诉人们什么时，查尔斯说：&ldquo;你听说的有关宗教的一切显然是荒唐、可笑的，从根本上说非常滑稽。&rdquo;该片颇具迈克尔&middot;摩尔的记录片的感觉，但又有马赫的一种不尊敬和常常亵渎的访谈风格。实际上，在片中对宗教领袖和学者的访谈中，当马赫和查尔斯指出宗教教条和信仰结构中的矛盾和荒谬时，不止一次被吃惊的宣传人员打断。</p>
<p>
	<img alt="" border="0" onload="attachimg(this, 'load')" src="http://pic.piaohua.com/0701pic/allimg/090219/1704040.jpg" />&nbsp;<br />
	<img alt="IPB Image" border="0" name="post_img" src="http://pic.piaohua.com/0701pic/allimg/090219/1704041.jpg" width="560" /></p>
<p>
	【电影截图】：<br />
	电影来源：www.eee4.com<br />
	<br />
	<br />
	<img alt="" border="0" onload="attachimg(this, 'load')" src="http://pic.piaohua.com/0701pic/allimg/090219/1704042.jpg" />&nbsp;<br />
	<img alt="" border="0" onload="attachimg(this, 'load')" src="http://pic.piaohua.com/0701pic/allimg/090219/1704043.jpg" /></p>
<p>
	2009-02-19 12:35:12 开始连接......<br />
	2009-02-19 12:35:12 开始搜索候选资源......<br />
	2009-02-19 12:35:12 搜索到22个候选资源<br />
	2009-02-19 12:35:12 使用候选资源进行连接......<br />
	2009-02-19 12:35:13 搜索到41个候选资源<br />
	2009-02-19 12:35:13 使用候选资源进行连接......<br />
	2009-02-19 12:35:13 文件创建成功，开始下载数据......<br />
	2009-02-19 12:35:16 用户取消下载&nbsp;&nbsp; 本文来自：www.eee4.com</p>
<p>
	（一律使用<a href="/soft.htm" target="_blank">迅雷下载</a>）<br />
	美国08最新高分纪录片《宗教的荒谬》DVD中字 －来自[www.eee4.com]：<img border="0" src="/templets/img/down.jpg" /></p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://e53:e53@xl2.eee4.com:9024/[3E电影站www.eee4.com]宗教的荒谬.rmvb" target="_blank">ftp://e53:e53@xl2.eee4.com:9024/[3E电影站www.eee4.com]宗教的荒谬.rmvb</a></td>
		</tr>
	</tbody>
</table>
<br />
<p>
	美国08最新高分纪录片《宗教的荒谬》DVD中字无水印 －来自[www.eee4.com]：<img border="0" src="/templets/img/down.jpg" /></p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://e53:e53@xl2.eee4.com:9024/[3E电影站www.eee4.com]宗教的荒谬DVD中字无水印.rmvb" target="_blank">ftp://e53:e53@xl2.eee4.com:9024/[3E电影站www.eee4.com]宗教的荒谬DVD中字无水印.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15051H0-32948.jpg{/dede:field}
