<?php
$z[0]=Array("field","唐伯虎点秋香[HD国语＋粤语中字1",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","唐伯虎点秋香[HD国语＋粤语中字1024x576＋1280x720高清版]迅雷下载、免费下载，唐伯虎点秋香[HD国语＋粤语中字1024x576＋1280x720高清版]Gvod高清在线播放，剧情介绍等。",73,275);
$z[1][4]['name']="description";
$z[2]=Array("field","唐伯虎点秋香[HD国语＋粤语中字1024x576＋1280x720高清版]",277,369);
$z[2][4]['name']="title";
$z[3]=Array("field","",371,410);
$z[3][4]['name']="writer";
$z[4]=Array("field","",412,451);
$z[4][4]['name']="source";
$z[5]=Array("field","2009-12-21",453,503);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",505,542);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://3e:3e@www2.3edyy.com:952/【3E电影院www.3edyy.com】唐伯虎点秋香HD国语中字1024x576高清版.rmvb\" target=_blank>ftftp://3e:3e@www2.3edyy.com:952/【3E电影院www.3edyy.com】唐伯虎点秋香HD国语中字1024x576高清版.rmvb</A></TD></TR></TBODY></TABLE><BR><FONT color=#ff0000 size=2><STRONG>1280x720【粤语中字】 [下载地址]：<IMG src=\"httftp://www.3edyy.com/templets/img/down.jpg\" border=0></STRONG></FONT><BR>\r\n<TABLE style=\"BORDER-RIGHT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; BORDER-BOTTOM: #cccccc 1px dotted\" cellSpacing=0 cellPadding=6 width=\"95%\" align=center border=0>\r\n<TBODY>\r\n<TR>\r\n<TD style=\"WORD-WRAP: break-word\" bgColor=#fdfddf><A href=\"ftftp://3e:3e@www2.3edyy.com:964/【3E电影院www.3edyy.com】唐伯虎点秋香HD粤语中字1280x720高清版.rmvb\" target=_blank>ftftp://3e:3e@www2.3edyy.com:964/【3E电影院www.3edyy.com】唐伯虎点秋香HD粤语中字1280x720高清版.rmvb</A></TD></TR></TBODY></TABLE></div><ul class=\"mmlist",544,1558);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MQ325040-44433.jpg",1560,1644);
$z[8][4]['name']="litpic";

?>