{dede:field name='keywords'}志明与春娇,BD国粤双语中字1024/{/dede:field}
{dede:field name='description'}志明与春娇 BD国粤双语中字1024/1280高清迅雷下载、免费下载，志明与春娇 BD国粤双语中字1024/1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}志明与春娇 BD国粤双语中字1024/1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-04-01{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img.album.pchome.net/54/74/50/15/fef68c2fc12def2b2ac0c831b130e0e8.jpg" /></p>
<p>
	导演: 彭浩翔<br />
	编剧: 彭浩翔 / 陆以心<br />
	主演: 杨千嬅 / 余文乐 / 杨幂 / 徐峥 / 谷德昭 / 司徒慧焯 / 陈逸宁 / 郑伊健 / 詹瑞文 / 阎汶宣 / 田蕊妮 / 王馨平 / 郝蕾 / 黄晓明<br />
	类型: 剧情 / 喜剧 / 爱情<br />
	制片国家/地区: 香港 / 中国大陆<br />
	语言: 粤语 / 汉语普通话<br />
	上映日期: 2012-03-29(香港) / 2012-03-30(中国大陆)<br />
	片长: 111分钟<br />
	又名: 志明与春娇2 / Love in the Buff</p>
<p>
	春娇与志明的剧情简介 &middot; &middot; &middot; &middot; &middot; &middot;<br />
	　　张志明（余文乐 饰）与余春娇（杨千嬅 饰）在一起后，恋情也不可避免由热烈转向平淡，几番龃龉过后，二人平平淡淡、不知不觉地分手了。在此之后，志明接受前老板的邀请，和公公前往北京发展，他很快结识了美丽温柔的空姐尚优优（杨幂 饰），一段新的恋情由此展开。另一方面，春娇的化妆品牌决定关掉香港分店，于是她也和娥姐转战北京。曾经的恋人相见自是几多尴尬，而原以为早已平淡和忘却的情感竟在见面的一刻复萌。虽然志明有优优陪伴，春娇也意外邂逅了体贴稳重的SAM（徐峥 饰），但是他们仍然瞒着另一半偷偷见面，他们小心地保持着距离，心又不由自主地向对方靠近。<br />
	　　已是从香港转战北京的爱情，将如何收场&hellip;&hellip;</p>
<p>
	<img alt="" border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://photo6.zxip.com/albums6/folder18/14186/20100701105143/2010718111312188.jpg');" src="http://photo6.zxip.com/albums6/folder18/14186/20100701105143/2010718111312188.jpg" /></p>
<p>
	<img alt="" border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://photo6.zxip.com/albums6/folder18/14186/20100701105143/201071811135368.jpg');" src="http://photo6.zxip.com/albums6/folder18/14186/20100701105143/201071811135368.jpg" /></p>
<p>
	<img alt="" border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://photo6.zxip.com/albums6/folder18/14186/20100701105143/2010718111376190.jpg');" src="http://photo6.zxip.com/albums6/folder18/14186/20100701105143/2010718111376190.jpg" /></p>

<p>
	[下载地址]：&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3110/飘花电影piaohua.com春娇与志明志明与春娇2BD1024国语中字.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3110/飘花电影piaohua.com春娇与志明志明与春娇2BD1024国语中字.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3110/飘花电影piaohua.com春娇与志明志明与春娇2BD1024国语中字.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3113/飘花电影piaohua.com春娇与志明志明与春娇2BD1024国粤双语中字.mkv">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3113/飘花电影piaohua.com春娇与志明志明与春娇2BD1024国粤双语中字.mkv">ftp://dy44:piaohua@dy44.piaohua.com:3113/飘花电影piaohua.com春娇与志明志明与春娇2BD1024国粤双语中字.mkv</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3113/飘花电影piaohua.com春娇与志明志明与春娇2BD国语中字1280高清.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3113/飘花电影piaohua.com春娇与志明志明与春娇2BD国语中字1280高清.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3113/飘花电影piaohua.com春娇与志明志明与春娇2BD国语中字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3113/飘花电影piaohua.com春娇与志明志明与春娇2BD粤语中字1280高清.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3113/飘花电影piaohua.com春娇与志明志明与春娇2BD粤语中字1280高清.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3113/飘花电影piaohua.com春娇与志明志明与春娇2BD粤语中字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15T1330-33E1.jpg{/dede:field}
