{dede:field name='keywords'}神鬼制裁：战争特区[高清预告片]{/dede:field}
{dede:field name='description'}神鬼制裁：战争特区[高清预告片]迅雷下载、免费下载，神鬼制裁：战争特区[高清预告片]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}神鬼制裁：战争特区[高清预告片]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2008-09-11{/dede:field}
{dede:field name='body'}<P>《惩罚者2：战争区》(DVD中文字幕高清晰预告片)<BR>导演： 莱克西·亚历山大 <BR>主演： 雷·斯蒂文森 多米尼克·威斯特 <BR>上映： 2008年9月12日 <BR>类型： 动作片 <BR>地区： 美国 <BR>语言： 英语 <BR>颜色： 彩色 <BR>别名： 复仇者2，制裁者2，神鬼制裁：战争特区<BR><BR>剧情介绍:<BR>　　我们的孤胆英雄“弗兰克·卡斯特”又回来了，这次他要惩罚的是作恶多端的黑帮老大Billy Russoti，后者虽然在弗兰克的“惩罚”下活了下来，但一张脸破相严重，如同一张拼图，一心复仇的Billy Russoti从此化名“拼图”（Jigsaw）开始追杀弗兰克。面对狡猾狠毒的“拼图”，弗兰克别无选择只能只身应战……本片是2004年漫画电影《制裁者》（The Punisher）的续集，不过这次扮演“制裁者”的人不再是托马斯·简（Thomas Jane），而换成了出演过《罗马》（Rome）的雷·斯蒂文森（Ray Stevenson）。</P>
<P><IMG src="/uploads/allimg/c120524/133N360525F-2V945.jpg"></P>
<P>2008-09-11 00:35:12 开始连接......<BR>2008-09-11 00:35:12 开始搜索候选资源......<BR>2008-09-11 00:35:12 搜索到52个候选资源<BR>2008-09-11 00:35:12 使用候选资源进行 连接......<BR>2008-09-11 00:35:13 搜索到121个候选资源<BR>2008-09-11 00:35:13 使用候选资源进行连接......<BR>2008-09-11 00:35:13 文件创建成功，开始下载数 据......<BR>2008-09-11 00:35:16 用户取消下载&nbsp;&nbsp; 本文来自：www.eee4.com</P>（直接可能无法下载，一律使用迅雷下载）<BR>《惩罚者2：战争区》(DVD中文字幕高清晰预告片) －来自[3E迅雷电影站eee4.com]下载地址：<IMG src="/uploads/allimg/c120524/133N2ZL930-142957.jpg" border=0><BR>
<TABLE style="BORDER-RIGHT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; BORDER-BOTTOM: #cccccc 1px dotted" cellSpacing=0 cellPadding=6 width="95%" align=center border=0>
<TBODY>
<TR>
<TD style="WORD-WRAP: break-word" bgColor=#fdfddf></ANCHOR>ftp://eee4.com:8118@vip17.eee4.com:8118/[3E电影站www.eee4.com]惩罚者2：战争区[DVD中文字幕高清晰预告片].rmvb</TD></TR></TBODY></TABLE>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120524/133N360533F-291121.jpg{/dede:field}
