<?php
$z[0]=Array("field","超强台风迅雷下载，免费下载，Gv",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","超强台风迅雷下载、免费下载，超强台风Gvod高清在线播放，剧情介绍等。",73,183);
$z[1][4]['name']="description";
$z[2]=Array("field","超强台风",185,231);
$z[2][4]['name']="title";
$z[3]=Array("field","",233,272);
$z[3][4]['name']="writer";
$z[4]=Array("field","",274,313);
$z[4][4]['name']="source";
$z[5]=Array("field","2008-10-27",315,365);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",367,404);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://e63:e63@xl2.eee4.com:1003/[3E电影站www.eee4.com]超强台风[DVD修正中字（高清晰）]CD1.rmvb\" target=_blank>ftftp://e63:e63@xl2.eee4.com:1003/[3E电影站www.eee4.com]超强台风[DVD修正中字（高清晰）]CD1.rmvb</A></TD></TR></TBODY></TABLE>CD2：<BR>\r\n<TABLE style=\"BORDER-RIGHT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; BORDER-BOTTOM: #cccccc 1px dotted\" cellSpacing=0 cellPadding=6 width=\"95%\" align=center border=0>\r\n<TBODY>\r\n<TR>\r\n<TD style=\"WORD-WRAP: break-word\" bgColor=#fdfddf><ANCHOR></ANCHOR><A href=\"ftftp://e63:e63@xl2.eee4.com:1003/[3E电影站www.eee4.com]超强台风[DVD修正中字（高清晰）]CD2.rmvb\" target=_blank>ftftp://e63:e63@xl2.eee4.com:1003/[3E电影站www.eee4.com]超强台风[DVD修正中字（高清晰）]CD2.rmvb</A></TD></TR></TBODY></TABLE></div><ul class=\"mmlist",406,1273);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MPUcP-3ZB.jpg",1275,1354);
$z[8][4]['name']="litpic";

?>