{dede:field name='keywords'}超强台风迅雷下载，免费下载，Gv{/dede:field}
{dede:field name='description'}超强台风迅雷下载、免费下载，超强台风Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}超强台风{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2008-10-27{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://e63:e63@xl2.eee4.com:1003/[3E电影站www.eee4.com]超强台风[DVD修正中字（高清晰）]CD1.rmvb" target=_blank>ftftp://e63:e63@xl2.eee4.com:1003/[3E电影站www.eee4.com]超强台风[DVD修正中字（高清晰）]CD1.rmvb</A></TD></TR></TBODY></TABLE>CD2：<BR>
<TABLE style="BORDER-RIGHT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; BORDER-BOTTOM: #cccccc 1px dotted" cellSpacing=0 cellPadding=6 width="95%" align=center border=0>
<TBODY>
<TR>
<TD style="WORD-WRAP: break-word" bgColor=#fdfddf><ANCHOR></ANCHOR><A href="ftftp://e63:e63@xl2.eee4.com:1003/[3E电影站www.eee4.com]超强台风[DVD修正中字（高清晰）]CD2.rmvb" target=_blank>ftftp://e63:e63@xl2.eee4.com:1003/[3E电影站www.eee4.com]超强台风[DVD修正中字（高清晰）]CD2.rmvb</A></TD></TR></TBODY></TABLE></div><ul class="mmlist{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MPUcP-3ZB.jpg{/dede:field}
