{dede:field name='keywords'}圈套剧场版3：灵异者大混战/圈套{/dede:field}
{dede:field name='description'}圈套剧场版3：灵异者大混战/圈套电影版3：超能力者大逃杀[DVD中字]迅雷下载、免费下载，圈套剧场版3：灵异者大混战/圈套电影版3：超能力者大逃杀[DVD中字]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}圈套剧场版3：灵异者大混战/圈套电影版3：超能力者大逃杀[DVD中字]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2010-12-15{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://3e:3e@m3.3edyy.com:510/【3E看看www.3ekk.com】圈套剧场版3：灵异者大混战[DVD中字].rmvb" target=_blank>ftftp://3e:3e@m3.3edyy.com:510/【3E看看www.3ekk.com】圈套剧场版3：灵异者大混战[DVD中字].rmvb</A></TD></TR></TBODY></TABLE></div><ul class="mmlist{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MP351060-2I04.jpg{/dede:field}
