<?php
$z[0]=Array("field","圈套剧场版3：灵异者大混战/圈套",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","圈套剧场版3：灵异者大混战/圈套电影版3：超能力者大逃杀[DVD中字]迅雷下载、免费下载，圈套剧场版3：灵异者大混战/圈套电影版3：超能力者大逃杀[DVD中字]Gvod高清在线播放，剧情介绍等。",73,291);
$z[1][4]['name']="description";
$z[2]=Array("field","圈套剧场版3：灵异者大混战/圈套电影版3：超能力者大逃杀[DVD中字]",293,393);
$z[2][4]['name']="title";
$z[3]=Array("field","",395,434);
$z[3][4]['name']="writer";
$z[4]=Array("field","",436,475);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-12-15",477,527);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",529,566);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://3e:3e@m3.3edyy.com:510/【3E看看www.3ekk.com】圈套剧场版3：灵异者大混战[DVD中字].rmvb\" target=_blank>ftftp://3e:3e@m3.3edyy.com:510/【3E看看www.3ekk.com】圈套剧场版3：灵异者大混战[DVD中字].rmvb</A></TD></TR></TBODY></TABLE></div><ul class=\"mmlist",568,858);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MP351060-2I04.jpg",860,943);
$z[8][4]['name']="litpic";

?>