{dede:field name='keywords'}五遁忍术高清迅雷下载，免费下载{/dede:field}
{dede:field name='description'}五遁忍术高清迅雷下载、免费下载，五遁忍术高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}五遁忍术高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-03-25{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="/uploads/allimg/c120525/133O10092c0-14Y03.jpg" style="width: 428px; height: 496px" /></p>
<p>
	◎译　　名　五遁忍术<br />
	◎片　　名　Five Element Ninjas<br />
	◎年　　代　1982<br />
	◎国　　家　香港<br />
	◎类　　别　动作/剧情<br />
	◎语　　言　普通话<br />
	◎IMDB评分 8.0/10 (275 votes)<br />
	◎IMDB链接 http://us.imdb.com/title/tt0084921/<br />
	◎片　　长　107 min<br />
	◎导　　演　张彻<br />
	◎主　　演　龙天翔 Tien Hsiang Lung .....Brother Li<br />
	　　　　　　程天赐 Tien-chi Cheng .....Shao Tien-hao<br />
	　　　　　　罗莽 Meng Lo .....Shi Shang<br />
	　　　　　　陈惠敏 Wai-Man Chan .....Chin Tien Chun (as Hui-Min Chen)<br />
	　　　　　　朱客 Ke Chu .....Kwon Hon<br />
	　　　　　　王力 Li Wang .....Ho Fen<br />
	　　　　　　余太平 Tai Ping Yu<br />
	　　　　　　陈佩茜 Chen Hei Psi .....Mr Kang<br />
	◎简　　介　<br />
	本片由张彻导演爱将罗莽、程天赐及龙天翔领衔主演，倪匡编剧，拍于1982年。故事讲述忍者之王剑渊(陈惠敏 饰)为替败于武林总盟盟主袁增(关锋饰)手下的东瀛武士复仇，率领大批忍者前来中土，摆下「五遁阵」，向袁增挑战。袁增派遣门下八位高手前去破阵，却因对忍术一无所知，全部被杀。剑渊取胜后意犹未足，派出女忍者纯子(陈佩茜 饰)混入总盟作内应，以图称霸武林&hellip;&hellip;<br />
	<img alt="" src="/uploads/allimg/c120525/133O10093T0-15B11.jpg" style="width: 720px; height: 405px" /><img alt="" src="/uploads/allimg/c120525/133O10094910-1DR0.jpg" style="width: 720px; height: 405px" /><img alt="" src="/uploads/allimg/c120525/133O10095a0-1O403.jpg" style="width: 720px; height: 405px" /><br />
	&nbsp;</p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="/uploads/allimg/c120525/133O0T31310-42214.jpg" />&nbsp;&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy125:piaohua@dy125.piaohua.com:7765/飘花电影piaohua.com五遁忍术BD中字1280高清.rmvb</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1009E40-1Rb2.jpg{/dede:field}
