<?php
$z[0]=Array("field","成龙金喜善-无尽的爱MKV1280x544",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","成龙金喜善-无尽的爱MKV1280x544原版MV迅雷下载、免费下载，成龙金喜善-无尽的爱MKV1280x544原版MVGvod高清在线播放，剧情介绍等。",73,239);
$z[1][4]['name']="description";
$z[2]=Array("field","成龙&amp;金喜善-无尽的爱MKV1280x544原版MV",241,320);
$z[2][4]['name']="title";
$z[3]=Array("field","",322,361);
$z[3][4]['name']="writer";
$z[4]=Array("field","",363,402);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-07-23",404,454);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>\r\n	成龙&amp;金喜善-无尽的爱MKV1280x544原版MV</p>\r\n\r\n<p>\r\n	<img border=\"0\" src=\"/uploads/allimg/c120524/133N423M140-1E521.jpg\" width=\"750\" /></p>\r\n<p>\r\n	[下载地址]： &nbsp;<img border=\"0\" src=\"/uploads/allimg/c120524/133N2Z4FF-102231.jpg\" /></p>\r\n<table bgcolor=\"#ff8c00\" border=\"0\" cellpadding=\"5\" cellspacing=\"1\" width=\"100%\">\r\n	<tbody>\r\n		<tr>\r\n			<td bgcolor=\"#ffffbb\" style=\"line-height: 18px; word-break: break-all\" width=\"100%\">\r\n				ftp://dy171:piaohua@dy171.piaohua.com:1065/飘花电影piaohua.com无尽的爱MKV1280x544原版MV.mkv</td>\r\n		</tr>\r\n	</tbody>\r\n</table>",456,1062);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c120524/133N423N30-1J523.jpg",1064,1147);
$z[7][4]['name']="litpic";

?>