{dede:field name='keywords'}成龙金喜善-无尽的爱MKV1280x544{/dede:field}
{dede:field name='description'}成龙金喜善-无尽的爱MKV1280x544原版MV迅雷下载、免费下载，成龙金喜善-无尽的爱MKV1280x544原版MVGvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}成龙&amp;金喜善-无尽的爱MKV1280x544原版MV{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-07-23{/dede:field}
{dede:field name='body'}<p>
	成龙&amp;金喜善-无尽的爱MKV1280x544原版MV</p>

<p>
	<img border="0" src="/uploads/allimg/c120524/133N423M140-1E521.jpg" width="750" /></p>
<p>
	[下载地址]： &nbsp;<img border="0" src="/uploads/allimg/c120524/133N2Z4FF-102231.jpg" /></p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy171:piaohua@dy171.piaohua.com:1065/飘花电影piaohua.com无尽的爱MKV1280x544原版MV.mkv</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120524/133N423N30-1J523.jpg{/dede:field}
