{dede:field name='keywords'}僵尸少爷DVD永恒的经典迅雷下载{/dede:field}
{dede:field name='description'}僵尸少爷DVD永恒的经典迅雷下载、免费下载，僵尸少爷DVD永恒的经典Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}僵尸少爷DVD永恒的经典{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-08-15{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="/uploads/allimg/c120525/133O035030P-231215.jpg" /><img alt="" src="/uploads/allimg/c120525/133O03504140-2492K.jpg" /></p>
<p>
	◎译　　名　僵尸少爷<br />
	◎片　　名　Magic Story<br />
	◎年　　代　2002<br />
	◎国　　家　香港<br />
	◎类　　别　剧情/喜剧/灵幻<br />
	◎语　　言　国语<br />
	◎字　　幕　简体中文<br />
	◎IMDB评分 6.7/10 (1,710 votes)<br />
	◎下载链接 http://www.bt10000.com<br />
	◎文件格式　Rmvb<br />
	◎视频尺寸　720 x 404<br />
	◎文件大小　467MB<br />
	◎片　　长　86 Min<br />
	◎导　　演　刘冰基<br />
	◎主　　演　董骠 火星 孙国明 纪芳玲 太保 黎强权 小奇奇<br />
	　　　　　　<br />
	◎简　　介　</p>
<p>
	　　调皮捣蛋的小僵尸乃僵尸家族的宠儿，某夜突然失去影子，家族成员四出寻觅。僵尸少爷途中</p>
<p>
	遇一青年阿贵，阿贵明知他非人类，拟将他送回家。有一茅山道人，专门利用夜间偷刚死的尸体，</p>
<p>
	练成僵尸为非作歹，无意间得知阿贵有一僵尸仔，乃千方百计欲夺取......</p>

<p>
	<br />
	◎影片截图</p>
<p>
	<img alt="" src="/uploads/allimg/c120525/133O03504950-256106.jpg" /><img alt="" src="/uploads/allimg/c120525/133O03505B0-2C142.jpg" /><img alt="" src="/uploads/allimg/c120525/133O03506360-2J548.jpg" /><img alt="" src="/uploads/allimg/c120525/133O0350G50-2X502.jpg" /></p>

<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="/uploads/allimg/c120524/133N2Z4FF-102231.jpg" />&nbsp;&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="word-break: break-all; line-height: 18px" width="100%">
				ftp://dy125:piaohua@dy125.piaohua.com:2018/飘花电影piaohua.com僵尸少爷[国语中字].rmvb </td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O0350N50-294Z3.jpg{/dede:field}
