<?php
$z[0]=Array("field","铁蹄下的村庄/将要来的人/有人要",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","铁蹄下的村庄/将要来的人/有人要来[DVD中英双字]迅雷下载、免费下载，铁蹄下的村庄/将要来的人/有人要来[DVD中英双字]Gvod高清在线播放，剧情介绍等。",73,257);
$z[1][4]['name']="description";
$z[2]=Array("field","铁蹄下的村庄/将要来的人/有人要来[DVD中英双字]",259,342);
$z[2][4]['name']="title";
$z[3]=Array("field","",344,383);
$z[3][4]['name']="writer";
$z[4]=Array("field","",385,424);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-08-14",426,476);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",478,515);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://7e:7e@m1.eee4.cc:1518/【3E电影院www.eee4.cc】铁蹄下的村庄[DVD中英双字].rmvb\" target=_blank>ftftp://7e:7e@m1.eee4.cc:1518/【3E电影院www.eee4.cc】铁蹄下的村庄[DVD中英双字].rmvb</A></TD></TR></TBODY></TABLE></div><ul class=\"mmlist",517,789);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MP62a20-56341.jpg",791,874);
$z[8][4]['name']="litpic";

?>