<?php
$z[0]=Array("field","卓别林系列（5部）[BD中字960x72",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","卓别林系列（5部）[BD中字960x720高清版]迅雷下载、免费下载，卓别林系列（5部）[BD中字960x720高清版]Gvod高清在线播放，剧情介绍等。",73,243);
$z[1][4]['name']="description";
$z[2]=Array("field","卓别林系列（5部）[BD中字960x720高清版]",245,321);
$z[2][4]['name']="title";
$z[3]=Array("field","",323,362);
$z[3][4]['name']="writer";
$z[4]=Array("field","",364,403);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-08-05",405,455);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",457,494);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://8e:8e@d8.3edyy.com:173/【3E电影院www.eee4.cc】卓别林：城市之光BD中字960x720高清版.rmvb\" target=\"_blank",496,643);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MQ35S30-325Y.jpg",645,727);
$z[8][4]['name']="litpic";

?>