{dede:field name='keywords'}卓别林系列（5部）[BD中字960x72{/dede:field}
{dede:field name='description'}卓别林系列（5部）[BD中字960x720高清版]迅雷下载、免费下载，卓别林系列（5部）[BD中字960x720高清版]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}卓别林系列（5部）[BD中字960x720高清版]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2010-08-05{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://8e:8e@d8.3edyy.com:173/【3E电影院www.eee4.cc】卓别林：城市之光BD中字960x720高清版.rmvb" target="_blank{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MQ35S30-325Y.jpg{/dede:field}
