{dede:field name='keywords'}情谜DVD国语中字舒淇,余文乐2011{/dede:field}
{dede:field name='description'}情谜DVD国语中字舒淇 余文乐2011最新爱情迅雷下载、免费下载，情谜DVD国语中字舒淇 余文乐2011最新爱情Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}情谜DVD国语中字舒淇 余文乐2011最新爱情{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-03-09{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://apollo.s.dpool.sina.com.cn/nd/dataent/moviepic/pics/88/moviepic_bd41db521a7dfb59f235aaffd778ba95.jpg" /></p>

<p>
	中文名: 情谜<br />
	导演: 黎妙雪<br />
	编剧: 黎妙雪 / 厉河<br />
	主演: 舒淇 / 余文乐 / 陈数 / 奚美娟 / 牛萌萌 / 张乃天 / 宋歌 / 阎晓类型: 剧情 / 爱情 / 悬疑<br />
	制片国家/地区: 中国大陆 / 香港<br />
	语言: 汉语普通话<br />
	片长: 105分钟<br />
	又名: 孪爱 / The Second Woman<br />
	<br />
	<br />
	剧情简介<br />
	<br />
	　　惠宝（舒淇 饰）虽然已在剧团中攀上了女二号的位置，但事事受到女一号Amy（陈数 饰）的针对。惠宝在新剧《红梅传奇》的演出并不稳定，到了全国巡演的最后一场更突然病倒，眼看演艺生涯势必受到影响。但就在这时，她的孪生姐姐惠香（舒淇 饰）如鬼魅般飘至，在全团皆不知情下，代替惠宝踏上了舞台，演出还大获好评。<br />
	　　然而，惠宝并没有感谢姐姐，反而盛怒下与男友&mdash;&mdash;也是《红梅传奇》中男一号的阿楠（余文乐 饰）大吵一场，因为她已感到姐姐逐渐迫近的威胁，而且，不单是演出，还有爱情，因为，她已隐隐感觉到&mdash;&mdash;姐姐惠香与阿楠有染。<br />
	　　于是，两姐妹相约在后山的悬崖相见，惠宝咄咄相逼，天空打下了旱雷，仿佛要为这段孽缘来个了结&hellip;&hellip;<br />
	　　就在那天晚上，惠香失踪了，回来的只是如幽灵般的惠宝。隔了数天，警察在海边发现了一件女人的外套，阿楠对惠宝种种奇怪的行径生疑，安排好友KK兄妹明查暗访。最令人震惊的是，连双目失明的惠香母亲（奚美娟 饰），也无法分辨眼前人到底是妹妹还是姐姐！<br />
	　　舞台剧《红梅传奇》即将上演，惠宝不惜手段夺得女主角宝座，虚实交错的真相也将在舞台上上演&hellip;&hellip;<br />
	<br />
	<br />
	◎影片截图<br />
	<br />
	<img alt="" file="http://img165.poco.cn/mypoco/myphoto/20120308/19/56643687201203081951054144011410643_001.jpg" height="337" lazyloaded="true" src="http://img165.poco.cn/mypoco/myphoto/20120308/19/56643687201203081951054144011410643_001.jpg" style="cursor: pointer" width="600" /><br />
	<br />
	<img alt="" file="http://img165.poco.cn/mypoco/myphoto/20120308/19/56643687201203081951054144011410643_000.jpg" height="337" lazyloaded="true" src="http://img165.poco.cn/mypoco/myphoto/20120308/19/56643687201203081951054144011410643_000.jpg" style="cursor: pointer" width="600" /><br />
	<br />
	<img alt="" file="http://img165.poco.cn/mypoco/myphoto/20120308/19/56643687201203081951054144011410643_002.jpg" height="337" lazyloaded="true" src="http://img165.poco.cn/mypoco/myphoto/20120308/19/56643687201203081951054144011410643_002.jpg" style="cursor: pointer" width="600" /><br />
	<br />
	<img alt="" file="http://img165.poco.cn/mypoco/myphoto/20120308/19/56643687201203081951054144011410643_003.jpg" height="337" lazyloaded="true" src="http://img165.poco.cn/mypoco/myphoto/20120308/19/56643687201203081951054144011410643_003.jpg" style="cursor: pointer" width="600" />
	[下载地址]：&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2979/飘花电影piaohua.com情谜DVD国语中字.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:2979/飘花电影piaohua.com情谜DVD国语中字.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2979/飘花电影piaohua.com情谜DVD国语中字.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15QJZ-3P18.jpg{/dede:field}
