<?php
$z[0]=Array("field","金贤哲–还没结婚迅雷下载，免费",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","金贤哲–还没结婚迅雷下载、免费下载，金贤哲–还没结婚Gvod高清在线播放，剧情介绍等。",73,199);
$z[1][4]['name']="description";
$z[2]=Array("field","金贤哲–还没结婚",201,255);
$z[2][4]['name']="title";
$z[3]=Array("field","",257,296);
$z[3][4]['name']="writer";
$z[4]=Array("field","",298,337);
$z[4][4]['name']="source";
$z[5]=Array("field","2007-01-03",339,389);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","金贤哲 &ndash; 还没结婚<br /><br />\r\n<div style=\"FONT-SIZE: 13px\">mms://mmc.daumcast.net/mmc/1/1000/0900196001402m.wmv</div>",391,552);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c120524/133N353DD0-2G248.gif",554,637);
$z[7][4]['name']="litpic";

?>