{dede:field name='keywords'}时间与城市/视与听[DVD中英双字]{/dede:field}
{dede:field name='description'}时间与城市/视与听[DVD中英双字]迅雷下载、免费下载，时间与城市/视与听[DVD中英双字]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}时间与城市/视与听[DVD中英双字]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-22{/dede:field}
{dede:field name='body'}<p>
	◎译　　名　《时间与城市/视与听》08年度十大佳片DVD中英双字<br />
	◎片　　名　Of Time and the City<br />
	◎年　　代　2008<br />
	◎国　　家　英国<br />
	◎类　　别　记录<br />
	◎语　　言　英语<br />
	◎字　　幕　中英双字幕<br />
	◎IMDB评分 7.5/10 (298 votes)<br />
	◎文件格式　RMVB<br />
	◎视频尺寸　576 x 320<br />
	◎文件大小　1CD 49 x 15MB<br />
	◎片　　长　01:13:51<br />
	◎导　　演　<br />
	◎主　　演　<br />
	◎官方网站：http://www.bluemv.com<br />
	◎简　　介　<br />
	<br />
	&nbsp;&nbsp;&nbsp; 利物浦，披头四的故乡，也是导演特伦斯&middot;戴维斯的出生地，这是他写给这座城市的情歌与挽歌，弥漫着浓浓的乡愁，呈现出这城市曾经的模样。特伦斯&middot;戴维斯回到家乡拍摄这部纪录片，捕捉时间在城市身上电影下载施给的魔法，用珍贵影像回溯这个城市的历史，绝佳的音乐选用、诗意念白和惆怅影像，堪称近年独特而感性的风格化纪录片。</p>
<p>
	<img alt="" border="0" onload="attachimg(this, 'load')" src="/uploads/allimg/c120525/133O09625150-312248.jpg" tmooc_h="1" /></p>
<p>
	【电影截图】：<br />
	<br />
	<img alt="" border="0" onload="attachimg(this, 'load')" src="/uploads/allimg/c120525/133O096254F-326362.jpg" tmooc_h="1" /><br />
	<img alt="" border="0" onload="attachimg(this, 'load')" src="/uploads/allimg/c120525/133O09625c0-3331L.jpg" tmooc_h="1" /><br />
	<img alt="" border="0" onload="attachimg(this, 'load')" src="/uploads/allimg/c120525/133O09626210-3492Q.jpg" tmooc_h="1" /><br />
	<img alt="" border="0" onload="attachimg(this, 'load')" src="/uploads/allimg/c120525/133O0962C20-3540E.jpg" tmooc_h="1" /><br />
	<img alt="" border="0" onload="attachimg(this, 'load')" src="/uploads/allimg/c120525/133O0962H40-3D201.jpg" tmooc_h="1" /><br />
	<img alt="" border="0" onload="attachimg(this, 'load')" src="/uploads/allimg/c120525/133O0962M60-3M637.jpg" tmooc_h="1" /></p>
<br />
<p>
	（一律使用迅雷下载）<br />
	08年度十大佳片《时间与城市》DVD中英双字 －来自[www.eee4.com]：<img border="0" src="http://www.eee4.com/templets/img/down.jpg" /></p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				ftp://e10:e10@xl2.eee4.com:9306/[3E电影站www.eee4.com]时间与城市.rmvb</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O0962T0-3a613.jpg{/dede:field}
