{dede:field name='keywords'}红色机尾/炽天之翼DVD中字迅雷下{/dede:field}
{dede:field name='description'}红色机尾/炽天之翼DVD中字迅雷下载、免费下载，红色机尾/炽天之翼DVD中字Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}红色机尾/炽天之翼DVD中字{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-03{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://cdn3b.dvdempire.org/products/03/1610103h.jpg" style="width: 500px; height: 621px" /></p>
<p>
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120503/12/56643687201205031230024142458598487_004.jpg" /></p>
<p>
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120503/12/56643687201205031230024142458598487_005.jpg" /></p>
<p>
	◎译　　名　红色机尾/红色尾翼/红尾巴<br />
	◎片　　名　Red Tails<br />
	◎年　　代　2012<br />
	◎国　　家　美国<br />
	◎类　　别　动作/战争/冒险/剧情/历史<br />
	◎语　　言　英语<br />
	◎字　　幕　英文/西班牙文<br />
	◎IMDB评分 5.8/10 from 5,581 users<br />
	◎IMDB链接 <a href="http://www.imdb.com/title/tt0485985" target="_blank">http://www.imdb.com/title/tt0485985</a><br />
	◎文件格式　XviD + AC3<br />
	◎视频尺寸　640 x 272<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 1280 x 720</p>
<p>
	◎文件大小　2CD 500MB<br />
	◎片　　长　125 Min<br />
	◎导　　演　安东尼&middot;海明威 Anthony Hemingway<br />
	◎主　　演　小库珀&middot;古丁 Cuba Gooding Jr.&nbsp; &hellip;.Major Emanuelle Stance<br />
	　　　　　　泰伦斯&middot;霍华德 Terrence Dashon Howard&nbsp; &hellip;.Colonel A.J. Bullard<br />
	　　　　　　崔斯坦&middot;瓦尔德斯 Tristan Wilds&nbsp; &hellip;.Ray &lsquo;Junior&rsquo; Gannon<br />
	　　　　　　内特&middot;派克 Nate Parker&nbsp; &hellip;.Marty &lsquo;Easy&rsquo; Julian<br />
	　　　　　　伊利亚&middot;凯利 Elijah Kelley&nbsp; &hellip;.Samuel &lsquo;Joker&rsquo; George<br />
	　　　　　　Leslie Odom Jr.&nbsp; &hellip;.Declan &lsquo;Winky&rsquo; Hall<br />
	　　　　　　Kevin Phillips&nbsp; &hellip;.Leon &lsquo;Neon&rsquo; Edwards</p>
<p>
	◎简　　介　</p>
<p>
	　　影片灵感源自真实故事，讲述二战中，美国第一批黑人飞行员组成了一支带有实验性质的特殊的轰炸机护卫队的故事。</p>
<p>
	　　影片讲述了二战中，美国第一批黑人飞行员，克服当时制度和种族上的限制，组成了一支带有实验性质的特殊的轰炸机护卫队&mdash;&mdash;塔斯克基飞行员（Tuskegee Airmen）。他们的飞机上都画着&ldquo;红尾巴&rdquo;，于是这也成为了他们的绰号。&ldquo;红尾巴&rdquo;这支美国军事史上第一支由非裔美国人组成的飞行员编队，因为参加战争培训被派往阿拉巴马州随时准备迎战。在那里，他们经历了猖獗的种族主义和骚扰，他们的飞行和战斗能力曾饱受质疑，但&ldquo;红尾巴&rdquo;在空中卓越的表现，促使空军废除了种族隔离制度。他们在与意大利、德国的冲突中也起到了不可或缺的作</p>
<p>
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120503/12/56643687201205031230024142458598487_000.jpg" /></p>
<p>
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120503/12/56643687201205031230024142458598487_003.jpg" /></p>
<p>
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120503/12/56643687201205031230024142458598487_002.jpg" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.netftp//dy44:piaohua@dy44.piaohua.com:3228/" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3344/飘花电影piaohua.com炽天之翼DVD中字CD1.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3344/飘花电影piaohua.com炽天之翼DVD中字CD1.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3344/飘花电影piaohua.com炽天之翼DVD中字CD2.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3344/飘花电影piaohua.com炽天之翼DVD中字CD2.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1564c30-53118.jpg{/dede:field}
