{dede:field name='keywords'}2011韩国小姐HD中字迅雷下载，免{/dede:field}
{dede:field name='description'}2011韩国小姐HD中字迅雷下载、免费下载，2011韩国小姐HD中字Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}2011韩国小姐HD中字{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-11-10{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20111108/23/46303014201111082307293537202693349_002.jpg" /></p>
<p>
	&nbsp;<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20111108/23/46303014201111082307293537202693349_001.jpg" /></p>
<p>
	&nbsp;<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20111108/23/46303014201111082307293537202693349_000.jpg" /></p>
<p>
	8月4日电 &ldquo;首尔赛区冠军&rdquo;李成慧（Lee Seong-hye）摘得2011韩国小姐桂冠。3日晚7时，在首尔世宗路世宗文化会馆举行的2011韩国小姐选拔赛上，李成慧一举夺魁。金惠善、金艺瑟获选为亚军和季军。</p>
<p>
	&nbsp;</p>

<p>
	[下载地址]： &nbsp;<img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" /></p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				&nbsp;<a href="ftp://dy44:piaohua@dy44.piaohua.com:2045/飘花电影piaohua.com2011韩国小姐HD中字.rmvb ">ftp://dy44:piaohua@dy44.piaohua.com:2045/飘花电影piaohua.com2011韩国小姐HD中字.rmvb </a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1C44V0-54400.jpg{/dede:field}
