{dede:field name='keywords'}虹猫蓝兔火凤凰/虹猫蓝兔之功夫{/dede:field}
{dede:field name='description'}虹猫蓝兔火凤凰/虹猫蓝兔之功夫天音寺/虹猫蓝兔之功夫天林寺1280迅雷下载、免费下载，虹猫蓝兔火凤凰/虹猫蓝兔之功夫天音寺/虹猫蓝兔之功夫天林寺1280Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}虹猫蓝兔火凤凰/虹猫蓝兔之功夫天音寺/虹猫蓝兔之功夫天林寺1280{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-11-01{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="/uploads/allimg/c120525/133O04495320-13V9.jpg" /></p>
<p>
	<img alt="" src="/uploads/allimg/c120525/133O044960Z-23101.jpg" /><br />
	<br />
	<br />
	◎译　　名　虹猫蓝兔火凤凰/虹猫蓝兔之功夫天音寺/虹猫蓝兔之功夫天林寺<br />
	◎片　　名　Hong Mao Lan Tu Huo Feng Huang<br />
	◎年　　代　2010<br />
	◎国　　家　中国<br />
	◎类　　别　动画/武侠<br />
	◎语　　言　普通话<br />
	◎字　　幕　N/A<br />
	◎IMDB评分 N/A<br />
	◎IMDB链接 N/A<br />
	◎文件格式　XviD + MP3<br />
	◎视频尺寸　640 x 352<br />
	◎文件大小　1CD 50 x 15MB<br />
	◎片　　长　84 mins<br />
	◎导　　演　贺梦凡 Mengfan He<br />
	◎主　　演　谢娜 Na Xie&nbsp;&nbsp;....虹猫/小狸<br />
	　　　　　　何炅 Jiong He&nbsp;&nbsp;....多头水怪<br />
	　　　　　　杜海涛 Haitao Du&nbsp;&nbsp;....黑龙<br />
	　　　　　　吴昕 Xin Wu&nbsp;&nbsp;....莎丽<br />
	　　　　　　李维嘉 Vega Ri&nbsp;&nbsp;....跳跳<br />
	<br />
	◎简　　介　<br />
	<br />
	<br />
	<br />
	&nbsp; &nbsp;&nbsp; &nbsp;3000年前，黑龙作乱人间。所幸有天音谷七大音乐圣手合奏，催生凤凰蛋以天籁之音降伏黑龙。而后以数根社石将黑龙封入天音湖中&hellip;&hellip;以后天音谷每隔500年举行一次凤凰大典，加固对黑龙的封印。<br />
	<br />
	　　如今是第六个500年，凤凰待正待涅磐重生。不料大典时天象突变，凤凰涅磐失败化为一枚灵蛋。黑龙趁此良机，欲挣脱兽石的束缚，脱困作乱。要想阻止黑龙，只有去天音谷取出七种乐器，并合奏催开凤凰蛋，以&ldquo;天籁之音&rdquo;降伏黑龙。机缘巧合之下，蓝兔与天音大师在芦花镇碰见正在假扮虹猫表演的魔术师小狸，天音大师索性以他来假扮虹猫&mdash;&mdash;既可以稳定五侠信心，也还可能创造奇迹催生出凤凰。<br />
	<br />
	　　天音谷，对音乐却没有半点天赋的小狸为了扮演虹猫，出尽了洋相，吃尽了苦头&hellip;&hellip;<br />
	<br />
	　　层层重压让小狸最终无法忍受，他决定离开不再假扮虹猫。途中遇多头算计被蓝兔相救。<br />
	<br />
	　　蓝兔的举动让小狸深深感动，他决定重新回去承担起自己的责任。<br />
	<br />
	　　七侠正式开始了催生凤凰的七音合奏。然而，多头却于关键时刻再次扰乱小狸心智，小凤非但没有成为凤凰，反而变成了一只乌鸡。逗逗等五侠十分茫然，&ldquo;冒牌虹猫&rdquo;的身份终于被揭露。但六侠并没有责怪小狸，没有了凤凰的天籁之音，六侠决定拼死一搏，救出虹猫，阻止黑龙脱困作乱。<br />
	<br />
	　　不会武功的小狸和小凤被留了下来，六侠明知不可为而为之的大义让小狸深深感动，而自己的无力感又让小狸深深地自责，他失落极了：&ldquo;自己已经尽全力在做虹猫了，为什么还是不能成功呢？&rdquo;小狸顿悟了，他终于明白：要做最好的自己，要做最好的小狸！他是一个魔术师，他能够用魔术师的方式来协助七侠，让小凤由乌鸡变成真正的凤凰。<br />
	<br />
	　　六侠赶到天音湖，与虹猫会合，同黑龙陷入苦战。然而黑龙威力锐不可挡，七侠不是对手。千钧一发之际，小狸与小凤出现了，小狸用自己的魔术与黑龙展开周旋，并引出黑龙的五味真火，配合七侠，终于助小凤涅磐重生，由乌鸡变成了凤凰！凤凰发出了天籁之音，天地间似乎一下子宁静下来，只剩下凤凰清亮的声音在回响。黑龙终于被降伏了，他成为了一只小蜥蜴。小狸终于成功了，他没有做成虹猫，但他做成了最好的自己，成为了闻名天下的魔术师。</p>
<p>
	<br />
	◎剧　　照　<br />
	<br />
	<img alt="" border="0" onclick="zoom(this)" onload="attachimg(this, 'load')" src="/uploads/allimg/c120525/133O044964P-3L26.jpg" />&nbsp;<br />
	<img alt="" border="0" onclick="zoom(this)" onload="attachimg(this, 'load')" src="/uploads/allimg/c120525/133O044a440-43431.jpg" />&nbsp;<br />
	<img alt="" border="0" onclick="zoom(this)" onload="attachimg(this, 'load')" src="/uploads/allimg/c120525/133O044b2Z-5XI.jpg" />&nbsp;<br />
	<img alt="" border="0" onclick="zoom(this)" onload="attachimg(this, 'load')" src="/uploads/allimg/c120525/133O044c0Z-62311.jpg" />&nbsp;<br />
	<img alt="" border="0" onclick="zoom(this)" onload="attachimg(this, 'load')" src="/uploads/allimg/c120525/133O04500010-H212.jpg" />&nbsp;<br />
	<img alt="" border="0" onclick="zoom(this)" onload="attachimg(this, 'load')" src="/uploads/allimg/c120525/133O04500910-W1a.jpg" />&nbsp;<br />
	<img alt="" border="0" onclick="zoom(this)" onload="attachimg(this, 'load')" src="/uploads/allimg/c120525/133O04501b0-921N.jpg" />&nbsp;<br />
	<img alt="" border="0" onclick="zoom(this)" onload="attachimg(this, 'load')" src="/uploads/allimg/c120525/133O04503040-10P15.jpg" />&nbsp;<br />
	<img alt="" border="0" onclick="zoom(this)" onload="attachimg(this, 'load')" src="/uploads/allimg/c120525/133O0450410-1160R.jpg" />&nbsp;<br />
	<img alt="" border="0" onclick="zoom(this)" onload="attachimg(this, 'load')" src="/uploads/allimg/c120525/133O04504920-1255c.jpg" />&nbsp;<br />
	<img alt="" border="0" onclick="zoom(this)" onload="attachimg(this, 'load')" src="/uploads/allimg/c120525/133O04506110-1393W.jpg" /><br />
	<br />
	幕后制作：<br />
	<br />
	&nbsp;&nbsp;&nbsp; 原定于1月23号公映的武侠励志动画电影《虹猫蓝兔火凤凰》将档期推迟到了2月5日。片方称是为了让更多的大朋友有机会看到这部电影，届时《虹猫蓝兔》将联手更加针对小朋友的《喜羊羊》等动漫影片，为观众送上卡通贺岁大餐。<br />
	<br />
	　　眼下贺岁档的竞争已经进入了白热化阶段，随着寒假的到来，一批动画电影也即将相继上映，《喜羊羊和灰太狼》、《黑猫警长》、《超蛙战士》、《虹猫蓝兔》3E电影院等制作精良的动漫电影将在潜力巨大的儿童市场上展开争夺。&ldquo;从去年《喜羊羊和灰太狼之牛气冲天》的票房成绩就可以看出，动漫题材仍然有不可限量的市场容量，&rdquo;《虹猫蓝兔》的片方负责人同时表示，与其他贺岁片你死我活的争夺不同，在中国处于刚刚起步的动漫电影目前还是良性竞争，几部电影，虽题材相似却也都各有特色，拥有各自不同的受众群，&ldquo;所以每部电影都会有自己的生存空间&rdquo;。<br />
	<br />
	　　对于《虹猫蓝兔火凤凰》档期的推后，导演贺梦凡称做出这个决定是基于对影片内容和主题的考虑，与主打儿童观众的3E电影院《喜羊羊》相比，《虹猫蓝兔》的电影主题要更加深刻，不仅有童趣，还有一定的励志作用。据悉，电影《虹猫蓝兔火凤凰》将以乌鸡变凤凰和平民变英雄两条线索贯穿全片，向观众传达&ldquo;每个人都是一个奇迹&rdquo;这一积极元素。这样影片的观众群就不只是限制于处在寒假中的儿童，还包括已经工作了的白领。&ldquo;所以我们决定把档期改到了2月5日，这样在过年时休假的白领就可以有更多的机会看到我们的影片。&rdquo;<br />
	<br />
	　　据说，曾轶可是在各种争议声中，以淡定与自信之态被投资方相中，得到演绎主题曲的机会。而她身上体现出的&ldquo;做最好的自己&rdquo;精神，恰好与影片主题很契合。对于首次&ldquo;触电&rdquo;献声，曾轶可称，整支歌曲的创作经历就是一次快乐的挑战，因为词曲方面是根据片中主角的成长经历感悟得出的，在创作的过程中也想到了自己的童年。至于自己的&ldquo;绵羊音&rdquo;，她大方表示并不在乎别人的说法，自己还觉得可爱单纯。<br />
	<br />
	　　另外，片方还特意邀请颇有观众缘的&ldquo;快乐家族&rdquo;&mdash;&mdash;何炅、谢娜、杜海涛、李维嘉、吴昕为片中角色配音，发起&ldquo;快乐贺岁&rdquo;总动员。</p>
<p>
	【电影截图】：<br />
	<br />
	<img alt="" border="0" onclick="if(this.width&gt;screen.width-461) window.open('/uploads/allimg/c120525/133O0450F40-149401.jpg');" src="/uploads/allimg/c120525/133O0450F40-149401.jpg" /><br />
	<img alt="" border="0" onclick="if(this.width&gt;screen.width-461) window.open('/uploads/allimg/c120525/133O0450O50-15M08.jpg');" src="/uploads/allimg/c120525/133O0450O50-15M08.jpg" /> <br />
	<img alt="" border="0" onclick="if(this.width&gt;screen.width-461) window.open('/uploads/allimg/c120525/133O0450W20-164413.jpg');" src="/uploads/allimg/c120525/133O0450W20-164413.jpg" /></p>
<br />
<br />
<p>
	2010年国产最新贺岁动画片《虹猫蓝兔火凤凰》DVD国语无字 [下载地址]：<img border="0" src="/uploads/allimg/c120524/133N295542P-105L6.jpg" /></p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				ftp://3e:3e@m1.3edyy.com:1383/【3E电影院www.3edyy.com】虹猫蓝兔火凤凰DVD国语.rmvb</td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				ftp://dy44:piaohua@dy44.piaohua.com:1971/飘花电影piaohua.com虹猫蓝兔火凤凰HD国语中字1280清.rmvb</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O0450950-1H2E.jpg{/dede:field}
