<?php
$z[0]=Array("field","2012:,冰河世纪/2012:冰河时期10",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","2012: 冰河世纪/2012:冰河时期1024/1280高清2011最新灾难科幻片迅雷下载、免费下载，2012: 冰河世纪/2012:冰河时期1024/1280高清2011最新灾难科幻片Gvod高清在线播放，剧情介绍等。",73,285);
$z[1][4]['name']="description";
$z[2]=Array("field","2012: 冰河世纪/2012:冰河时期1024/1280高清2011最新灾难科幻片",287,384);
$z[2][4]['name']="title";
$z[3]=Array("field","",386,425);
$z[3][4]['name']="writer";
$z[4]=Array("field","",427,466);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-09-19",468,518);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",520,557);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://dy172:piaohua@dy172.piaohua.com:209/飘花电影piaohua.com冰河时期.rmvb",559,672);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MO935E0-1L57.jpg",674,756);
$z[8][4]['name']="litpic";

?>