{dede:field name='keywords'}林俊傑,-,只對你說迅雷下载，免{/dede:field}
{dede:field name='description'}林俊傑 - 只對你說迅雷下载、免费下载，林俊傑 - 只對你說Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}林俊傑 - 只對你說{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2006-08-04{/dede:field}
{dede:field name='body'}<P>播放后双击视频“全屏”</P> 
<object classid="CLSID:22d6f312-b0f6-11d0-94ab-0080c74c7e95" class="OBJECT" id="MediaPlayer" width="500" height="350" ><param name="ShowStatusBar" value="-1"><param name="Filename" value="http://grm.cdn.hinet.net/xuite/c/1/9/c/14796266/blog_281108/dv/6173296/6173296.wmv"></embed></object><br /> 
<P>下载地址<BR></P> <br>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120524/133N353DD0-2G248.gif{/dede:field}
