{dede:field name='keywords'}恶魔之语美国恐怖1280x720英语中{/dede:field}
{dede:field name='description'}恶魔之语美国恐怖1280x720英语中字迅雷下载、免费下载，恶魔之语美国恐怖1280x720英语中字Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}恶魔之语美国恐怖1280x720英语中字{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-21{/dede:field}
{dede:field name='body'}<p>
	<img src="http://attachment.yyets.com/attachment/201203/26/1439775_1332789670FQ2r.jpg" /></p>
<p>
	中文片名: 恶魔之语<br />
	英文片名: Sur le seuil<br />
	国家地区: 美国<br />
	影片类型: 恐怖片<br />
	资源格式: DVDrip<br />
	上影时间: 2003<br />
	导　演: &eacute;ric Tessier<br />
	主　演: Michel C&ocirc;t&eacute; .... Dr. Paul Lacasse<br />
	Patrick Huard .... Thomas Roy<br />
	Catherine Florent .... Jeanne Marcoux<br />
	Albert Millaire .... P&egrave;re Lemay<br />
	Jean L&#39;Italien .... Charles Monette<br />
	Jacques Lavall&eacute;e .... Patrick Michaud</p>
<p>
	对白语言: 英语&nbsp;<br />
	字幕语种: 简&nbsp;</p>
<p>
	介绍:<br />
	◎译　　名　恶魔之语<br />
	◎片　　名　Sur le seuil<br />
	◎年　　代　2003<br />
	◎国　　家　加拿大<br />
	◎类　　别　剧情/恐怖/惊悚/动作<br />
	◎语　　言　英语<br />
	◎字　　幕　中字<br />
	◎IMDB评分 6.6/10 (704 votes)<br />
	◎IMDB链接：<a href="http://www.bluemv.com" title="电影下载">http://www.bluemv.com</a><br />
	◎文件格式　BD-MKV<br />
	◎视频尺寸　1280 x 720<br />
	◎文件大小　1CD-990mb<br />
	◎片　　长　95 mins<br />
	◎导　　演　&eacute;ric Tessier<br />
	◎主　　演　Michel C&ocirc;t&eacute; .... Dr. Paul Lacasse<br />
	Patrick Huard .... Thomas Roy<br />
	Catherine Florent .... Jeanne Marcoux<br />
	Albert Millaire .... P&egrave;re Lemay<br />
	Jean L&#39;Italien .... Charles Monette<br />
	Jacques Lavall&eacute;e .... Patrick Michaud<br />
	Jean Pierre Bergeron .... P&egrave;re Boudreault<br />
	Nicolas Canuel .... P&egrave;re Pivot<br />
	Normand D&#39;Amour .... Louis Archambault<br />
	Fr&eacute;d&eacute;rique Collin .... Madame H&eacute;nault<br />
	Annette Garant .... Infirmi&egrave;re Nicole<br />
	Christine Foley .... Claudette Roy<br />
	Alexis B&eacute;lec .... Jeune P&egrave;re Lemay<br />
	保罗&middot;杜塞特 Paul Doucet .... Inspecteur Goulet<br />
	Guy &#39;Borza&#39; Boutet .... Steve<br />
	Anne-Marie Labelle .... Gervaise<br />
	弗雷德裡克.吉尔斯 Fr&eacute;d&eacute;ric Gilles .... Marc Marcoux<br />
	Richard Fr&eacute;chette .... Fernand Lucas<br />
	Martin Dubreuil .... &eacute;douard Villeneuve<br />
	Genevi&egrave;ve Laroche .... Julie Picard</p>
<p>
	◎简　　介　</p>
<p>
	　　Roy是以为著名的恐怖小说家，但是他的小说总能与现实事件挂钩，到底是天下文章一大抄，还是他有预言能力呢？这一切和36年前的教堂大屠杀又有什么关系呢？</p>
<p>
	<br />
	<img src="http://www.fckb.net/data/attachment/forum/201203/25/151436tlekebdvnbxf6zxd.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; border-top: 0px solid; cursor: hand; border-right: 0px solid" title="看原大图" /></p>
<p>
	<img src="http://www.fckb.net/data/attachment/forum/201203/25/151449vh8vkhkv8jcknhhh.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; border-top: 0px solid; cursor: hand; border-right: 0px solid" title="看原大图" /></p>
<p>
	<img src="http://www.fckb.net/data/attachment/forum/201203/25/15144110m6272h007smssm.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; border-top: 0px solid; cursor: hand; border-right: 0px solid" title="看原大图" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3099/飘花电影piaohua.com恶魔之语美国恐怖1280x720英语中字.mkv">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3099/飘花电影piaohua.com恶魔之语美国恐怖1280x720英语中字.mkv">ftp://dy44:piaohua@dy44.piaohua.com:3099/飘花电影piaohua.com恶魔之语美国恐怖1280x720英语中字.mkv</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O164523F-4C35.jpg{/dede:field}
