<?php
$z[0]=Array("field","合法入侵/湖景水坝/湖边的梯田10",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","合法入侵/湖景水坝/湖边的梯田1024/1280高清版迅雷下载、免费下载，合法入侵/湖景水坝/湖边的梯田1024/1280高清版Gvod高清在线播放，剧情介绍等。",73,253);
$z[1][4]['name']="description";
$z[2]=Array("field","合法入侵/湖景水坝/湖边的梯田1024/1280高清版",255,336);
$z[2][4]['name']="title";
$z[3]=Array("field","",338,377);
$z[3][4]['name']="writer";
$z[4]=Array("field","",379,418);
$z[4][4]['name']="source";
$z[5]=Array("field","2012-05-05",420,470);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",472,509);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://3e:3e@vip.eee4.cn:620/[www.eee4.cn提供]合法入侵BD中英双字1024x576高清版.rmvb\" target=\"_blank",511,648);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MP04610-3b29.jpg",650,732);
$z[8][4]['name']="litpic";

?>