{dede:field name='keywords'}情敌大战(特务爱很大)DVD中字201{/dede:field}
{dede:field name='description'}情敌大战(特务爱很大)DVD中字2012最新美国R级动作喜剧爱情大片迅雷下载、免费下载，情敌大战(特务爱很大)DVD中字2012最新美国R级动作喜剧爱情大片Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}情敌大战(特务爱很大)DVD中字2012最新美国R级动作喜剧爱情大片{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-04{/dede:field}
{dede:field name='body'}<p>
	&nbsp;<img src="http://img170.poco.cn/mypoco/myphoto/20120503/13/56643687201205031306076770713946327_005.jpg" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120503/13/56643687201205031306076770713946327_000.jpg" /></p>
<p>
	◎译　　名　情敌大战 / 情敌战争 / 这意味着战争 / 争女特务王(港) / 特务爱很大(台)<br />
	◎片　　名　This Means War<br />
	◎年　　代　2012<br />
	◎国　　家　美国<br />
	◎类　　别　动作/喜剧/爱情<br />
	◎语　　言　英语<br />
	◎字　　幕　中文<br />
	◎IMDB评分 6.7/10 from 15,107 users<br />
	◎IMDB链接 <a href="http://www.imdb.com/title/tt1596350">http://www.imdb.com/title/tt1596350</a><br />
	◎文件格式　DVD-RMVB<br />
	◎视频尺寸　640 x 272<br />
	◎文件大小　1CD 398MB<br />
	◎片　　长　97 Mins</p>

<p>
	◎影片截图</p>
<p>
	&nbsp;塔克（汤姆&middot;哈迪 Tom Hardy 饰）和FDR（克里斯&middot;派恩 Chris Pine 饰）是美国中情局的顶尖探员，两人各自身怀绝技，并且是生死与共的最佳拍档，出任务都是屡屡告捷，即使在工作上一帆风顺，两人都还是大光棍一个，藉由使用交友网站Match.com，他们都找到了自己迷恋不已的对象，认定可长相厮守，万万没 想到的是，这二位挚友竟然连私事都默契十足，爱上同一人:事业有成女强人的萝拉（瑞茜&middot;威瑟斯彭 Reese Witherspoon 饰）。为了赢得美人芳心，兄弟阋墙在所难免，两人各自使出独门看家本领，而萝拉也因他们各自拥独树一格的特有魅力陷入两难，在好友兼损友崔尔丝敲边鼓，究竟她会选择哪位男士担任她的伴侣呢?</p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120503/13/56643687201205031306076770713946327_001.jpg" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120503/13/56643687201205031306076770713946327_004.jpg" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120503/13/56643687201205031306076770713946327_002.jpg" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.netftp//dy44:piaohua@dy44.piaohua.com:3142/" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3344/飘花电影piaohua.com情敌大战(特务爱很大)DVD中字.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3344/飘花电影piaohua.com情敌大战(特务爱很大)DVD中字.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15A2160-25594.jpg{/dede:field}
