{dede:field name='keywords'}丛林儿童1280BD中字2011最新德国{/dede:field}
{dede:field name='description'}丛林儿童1280BD中字2011最新德国冒险剧情大片迅雷下载、免费下载，丛林儿童1280BD中字2011最新德国冒险剧情大片Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}丛林儿童1280BD中字2011最新德国冒险剧情大片{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-17{/dede:field}
{dede:field name='body'}<p>
	&nbsp;<img src="http://img170.poco.cn/mypoco/myphoto/20120517/14/56643687201205171416213930735002326_004.jpg" /></p>
<p>
	◎译　　名　丛林儿童<br />
	◎片　　名　Dschungelkind/Jungle Child/AKA　　　　　 ◎导　　演　罗兰?苏素?里希特 Roland Suso Richter<br />
	◎主　　演　托马斯?克莱舒曼 Thomas Kretschmann<br />
	　　　　　　纳嘉?乌尔 Nadja Uhl<br />
	　　　　　　Michael Baral ....Michael<br />
	　　　　　　Isolde Barth ....Schuldirektorin<br />
	　　　　　　John Keogh ....Alec<br />
	　　　　　　Sina Tkotsch ....Sabine Kuegler - youth<br />
	　　　　　　Claes Bang ....Herb<br />
	　　　　　　Stella Kunkat ....Sabine Kuegler - child<br />
	　　　　　　Martina Ysker ....Junge Dame im Internat<br />
	　　　　　　Tom Ho&szlig;bach<br />
	　　　　　　Milena Tscharntke<br />
	　　　　　　Walter Rizzardini ....Eisverk&auml;ufer<br />
	　　　　　　Tina Engel ....Oma<br />
	　　　　　　Clara Dolny ....Susanne<br />
	　　　　　　Sven Gielnik ....Christian Kuegler - youth<br />
	　　　　　　Emmanuel Simeon ....Auri - child<br />
	　　　　　　Felix Tokwepota ....Auri - youth<br />
	◎年　　代　2011<br />
	◎国　　家　德国<br />
	◎类　　别　剧情/冒险<br />
	◎语　　言　德语<br />
	◎IMDB评分 7.2/10 (50 votes)<br />
	◎IMDB链接 <a href="http://www.imdb.com/title/tt1242543/">http://www.imdb.com/title/tt1242543/</a><br />
	◎片　　长　131 min　　　　　　</p>
<p>
	◎简　　介　</p>
<p>
	故事很独特 原始丛林里的精彩童年让人羡慕嫉妒恨 最受到启发的是土著人对待死亡的看法 由于丛林里死亡太平凡 他们比现在人更会get over 作者说的很好 主要是现代人太自大 觉得什么自己都可以控制 包括亲友爱人的死亡 都以为自己可以做什么 其实人只不过是自然的一部分拉 天命难为的 Machbarkeit只不过是自找......</p>
<p>
	◎关于原著</p>
<p>
	[来自石器时代的女孩?Dschungelkind (莎宾娜?库格勒 Sabine Kuegler)]</p>
<p>
	作者莎宾娜˙库格勒五岁时，随着从事语言研究和传教的父亲，来到西巴布亚原始森林深处「失落的峡谷」中，一个至今还停留在石器时代、传说中的食人族部落。</p>
<p>
	这个金发小姑娘对热带丛林一见钟情。她学习狩猎、攀爬，在鳄鱼出没的河里游泳。她会用弓箭射杀毒蜘蛛，不用火柴就能生火。她吃的是烤昆虫，而不是炸薯条；嘴巴里嚼的不是口香糖，而是蝙蝠翅膀。她认识到，大自然有时是多残酷，人与人之间的仇恨又意味着什么。曾经是食人族的法虞部落，所有的过失都必须用死来偿还，但正是在这样的一个部落，莎宾娜赢得了很多兄弟姐妹。</p>
<p>
	十七岁，莎宾娜˙库格勒被送回瑞士一间寄宿学校就读。这如同一次可怕的切割，「在这里我才学会害怕，」置身现代城市，她必须重新学习如何购物、如何向人问候、如何穿越马路&hellip;&hellip;。如今，她似乎完全适应了，甚至已成为文明社会所谓的经济学家。但她却思乡情切，对丛林深处的家的渴望，不停烧灼着她，她开始问自己：我到底是谁，是法虞人？还是欧洲人？</p>
<p>
	什么是文明？原始的定义又如何？这是一个文明人进入原始部落的故事，也是一个原始人进入文明世界的故事。作者用她独特的生命经验与故事，为我们对文化的想象插上了翅膀，让我们对现代生活有了更多的检视角度。</p>
<p>
	在失落的峡谷里和被遗忘的民族生活在一起，我感到幸福，<br />
	而在世界的另一端，我觉得自己像是个游魂。&mdash;&mdash;莎宾娜˙库格勒</p>
<p>
	<br />
	◎影片截图</p>

<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120517/14/56643687201205171416213930735002326_000.jpg" style="width: 600px; height: 338px" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120517/14/56643687201205171416213930735002326_002.jpg" style="width: 600px; height: 338px" /></p>
<p>
	&nbsp;<img src="http://img170.poco.cn/mypoco/myphoto/20120517/14/56643687201205171416213930735002326_001.jpg" style="width: 600px; height: 338px" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120517/14/56643687201205171416213930735002326_003.jpg" style="width: 600px; height: 338px" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.netftp//dy44:piaohua@dy44.piaohua.com:3142/" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3444/飘花电影piaohua.com丛林儿童1280BD中字.rmvb">&nbsp;ftp://dy44:piaohua@dy44.piaohua.com:3444/飘花电影piaohua.com丛林儿童1280BD中字.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15cM40-3P16.jpg{/dede:field}
