{dede:field name='keywords'}蒸汽男孩/蒸汽少年BD1280高清国{/dede:field}
{dede:field name='description'}蒸汽男孩/蒸汽少年BD1280高清国日双语迅雷下载、免费下载，蒸汽男孩/蒸汽少年BD1280高清国日双语Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}蒸汽男孩/蒸汽少年BD1280高清国日双语{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-21{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120521/23/1787098020120521232832056.jpg" /></p>
<p>
	中文名: 蒸汽男孩<br />
	英文名: Steamboy<br />
	IMDb: 6.9/10 (6,403 votes)<br />
	资源格式: 720P<br />
	发行日期: 2004年10月14日<br />
	导演: 大友克洋 Katsuhiro &amp;Ocirc;tomo演员: 铃木杏 Ann Suzuki ...... James Ray Steam (voice)<br />
	津嘉山正种 Masatane Tsukayama ...... Dr. Eddie Steam (voice)<br />
	中村贺津雄 Katsuo Nakamura ...... Dr. Lloyd Steam (voice)<br />
	小西真奈美 Manami Konishi ...... Scarlett O&#39;Hara (voice)<br />
	儿玉清 Kiyoshi Kodama ...... Robert Stephenson (voice)<br />
	泽村一树 Ikki Sawamura ...... David (voice)<br />
	寺岛进 Susumu Terajima ...... Freddie (voice)<br />
	安娜&middot;帕奎因 Anna Paquin ...... James Ray Steam (voice: English version)<br />
	阿尔弗雷德&middot;莫利纳 Alfred Molina ...... Dr. Eddie Steam (voice: English version)<br />
	帕特里克&middot;斯图尔特 Patrick Stewart ...... Dr. Lloyd Steam (voice: English version)<br />
	Kari Wahlgren ...... Scarlett O&#39;Hara (voice: English version)<br />
	Robin Atkin Downes ...... David (voice: English version)<br />
	David S. Lee ...... Jason (voice: English version)<br />
	Paula J. Newman ...... Emma (voice: English version)<br />
	Moira Quirk ...... Cliff, Tommy, Additional Voices (voice: English ve<br />
	Julian Stone ...... Additional Voices (voice: English version)<br />
	Mark Bramhall ...... Alfred (voice)<br />
	Osamu Saka ...... Army General (voice)<br />
	Kim Thomson ...... Mrs. Steam地区: 日本<br />
	语言: 日语/国语<br />
	<br />
	◆剧情介绍◆<br />
	<br />
	　时间，设定在19世纪中叶，一个开始由蒸汽动力来运转工业产品的时代。<br />
	　舞台，则是正在世界上首次举办万国博览会的英国。<br />
	<br />
	　出生于发明世家的主人公雷，是一名喜欢发明种种匪夷所思的蒸汽机械装置的天才少年。雷的祖父以及父亲也都是极度热衷于研究的发明家，常常为了科学研究和发明探索游走于世界各国。<br />
	<br />
	　这一年英国召开万国博览会在即，在美国研究发明的祖父罗伊德寄给雷一颗神秘的密封金属球，雷因此而突遭一伙身份不明的人的袭击，他们的目的就是想要抢走那颗金属球。雷只好带着金属球，乘上自己发明的单轮自走车踏上逃亡之路。<br />
	<br />
	　为寻求真相雷来到美国，从父亲艾迪口中雷得知，金属球原来是密封了一种神奇的超高压力蒸汽的金属容器。这是一项足以改变人类历史的伟大发明，它既能带动人类工业文明的飞速发展，也能制造出足以毁灭全世界的武器！而派人抢夺蒸汽球的，是美国财阀塞蒙，他妄图独占这项发明并用于军事，借此牟取暴利。<br />
	<br />
	　在祖父和父亲最终因为对科学的理想不同而反目的时候，坚信&ldquo;爷爷并不是为了战争发明这个金属球的！&rdquo;的雷，只好独自一人带着蒸汽球再度开始了逃亡。在漫长的孤独中，雷邂逅了美丽的富家千金斯嘉丽。斯嘉丽是被塞蒙抚养长大的小公主，从小娇生惯养，却偏偏爱上了雷，自愿跟随孤独的雷一起冒险。<br />
	<br />
	　所谓的科学，究竟是人们的希望？还是将会毁灭一切，应该全面禁止的知识？<br />
	　而这项伟大的发明，究竟是可以带给世界幸福的奇迹？还是带来灾难的恶魔的发明？<br />
	　坚信着科学的力量是带给人类幸福的动力，雷最终利用这个蒸汽球升入了太空，摆脱了贪婪的塞蒙的追截，成为名副其实的&ldquo;蒸汽男孩&rdquo;，并由此开始了太空历险&hellip;&hellip;<br />
	--------------------------------------------------------------------------------<br />
	◆即将冲击世界的蒸汽男孩◆<br />
	<br />
	　《蒸汽男孩》是日本动画大师大友克洋的最新力作，这部电影创作历时长达9年，耗资高达24亿日元(折合人民币1亿8100万元左右)，总共绘制出的图片就有18万张之多，更包含400个3D段落，成为了日本历史上历时最久、制作最昂贵的动画电影。<br />
	<br />
	　本片已于7月17日在日本全国上映，还被邀请参加9月的威尼斯电影节，作为电影节的闭幕式电影上映，而续篇的拍摄计划也已基本敲定。<br />
	<br />
	　由于近几年来日本动画电影在世界上的声望大增，所以《蒸汽男孩》也在雄心勃勃地酝酿冲击世界电影市场，目前已决定今年10月分别以配音版和字幕版登陆北美和以英国、法国、意大利为主要目标的部分欧洲市场，以便进军明年的奥斯卡。而《蒸汽男孩》也将成为继《千与千寻》后的第二部在美国公映的日本动画长片。<br />
	--------------------------------------------------------------------------------<br />
	◆天马行空的构想和精致的画面◆<br />
	<br />
	　《蒸汽男孩》是一部典型的大友克洋式的作品，聪明而真诚的少年、因为掌握了一件不可思议足以改变世界的神秘物品，因此被一个神秘的组织不断追截，而卷入了一场奇妙的冒险旅程&hellip;&hellip;<br />
	<br />
	　这样的情节，实际上在日本的少年动漫里比比皆是，并不新鲜。但《蒸汽男孩》却凭借它本身的两大优势让人赞叹不愧为一部上乘之作。<br />
	<br />
	　片中所出现的各种天马行空的道具装置，从喷气式独轮车到超巨型飞船及潜水艇，再从各种精致巧妙绝伦的小设计到用蒸汽防护的铠甲等等，剧中主人公雷逃走时所乘坐的蒸汽自走车，不仅速度可以赶超汽车，甚至可以升降自如。而这些，大部分都是在现实中闻所未闻见所未见，匪夷所思的虚幻之作，令人赞叹大师那丰富绝伦的想象力和构思。<br />
	<br />
	　天马行空的设计和构想，是本片的一大看点。而另一大特色，就是极为精致的一丝不苟的画面。<br />
	　影片的剧情并不复杂，但126分钟下来，你却会发现，哪怕视线只是离开了银幕一秒钟，都会错过精彩的画面，而造成莫大的遗憾。<br />
	<br />
	　故事的背景舞台是19世纪中叶的英国，正是工业革命特别是蒸汽运用达到飞速发展的时代，而当时的英国，是引领着工业革命，召开第一届万国博览会，世界上最发达，发展最迅速的产业大国。<br />
	　影片中不仅完全参照英国曼彻斯特和伦敦的景致、风物人情，把19世界中叶的英国再次巨细无疑地呈现在银幕上，甚至还有维多利亚时代的伦敦大破坏。精致的画面再配上强烈的3D特效，让整部影片无懈可击，也让跌宕起伏的剧情更加饱满。结尾处大手笔的宏伟壮观的高潮段落，更让人佩服不愧是日本历史上制作最昂贵的动画电影。<br />
	--------------------------------------------------------------------------------<br />
	◆感动中的遗憾：思想深刻内容老套◆<br />
	<br />
	　同大友克洋震惊世界的上部作品《阿基拉》一样，《蒸汽男孩》也以反思科学发展所带来的正反两面的影响为主题，描写了人类在自己也控制不了的巨大能量中，被迫出卖灵魂或者奋起抗争的各种姿态。虽说耗资24亿日元，无论是画面的效果还是精致的程度，都远远超过了当年的《阿基拉》，但《蒸汽男孩》却总让人以为是上个世纪90年代初的作品的错觉，或许是影片的怀旧味道所致。相对于精致的画面，令人感叹的动画效果，故事情节就稍显老套了些。几乎都是平铺直叙毫无伏线的简单故事，直到最后都没能在情节上让人特别感动。而且台词陈旧显得相当幼稚。如果是普通动画片的话，这些也许只是小瑕疵，但既然是大友大师的作品就难免让人觉得失望了。<br />
	<br />
	　此外，除了上面被人诟病最多的情节老套以外，本片大胆起用普通演员而非专业声优配音这一点，在日本国内也有不少反对声浪，大呼配音糟糕令人失望的大有人在。不过在笔者这个外人听来，本片的声优其实还是非常值得称道的，尤其是给雷配音的铃木杏，不仅音色本身听起来非常舒服而且和人物的契合度也很完美。夸张地说，就算是在如今日本的专业声优界中，也算是非常棒的声音了。<br />
	&nbsp;</p>
<p>
	<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120521/13/17870980201205211324281095751329412_003.jpg" /><br />
	&nbsp;<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120521/13/17870980201205211324281095751329412_002.jpg" /><br />
	<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120521/13/17870980201205211324281095751329412_001.jpg" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaobajie.com" target="_blank">http://www.xiaobajie.com</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy241:piaohua@117.41.229.29:2030/飘花电影piaohua.com蒸汽少年BD1280高清国日双语.mkv">ftp://dy241:piaohua@117.41.229.29:2030/飘花电影piaohua.com蒸汽少年BD1280高清国日双语.mkv</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1BJ310-4F46.jpg{/dede:field}
