{dede:field name='keywords'}雷克斯海3D：史前世界BD中英双字{/dede:field}
{dede:field name='description'}雷克斯海3D：史前世界BD中英双字1280高清2010纪录片迅雷下载、免费下载，雷克斯海3D：史前世界BD中英双字1280高清2010纪录片Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}雷克斯海3D：史前世界BD中英双字1280高清2010纪录片{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-12-09{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://www.newmov.com/pic/divx/HD/2011/Sea.Rex.3D.Journey.To.A.Prehistoric.World.2010.1080p.BluRay.x264-AiHD.jpeg" style="width: 600px; height: 753px; cursor: pointer" /></p>
<p>
	【影片原名】Sea Rex 3D: Journey to a Prehistoric World<br />
	【中文译名】雷克斯海3D:史前世界<br />
	【出品年代】2010 年<br />
	【IMDB评分】7.3/10 (67 votes)<br />
	【国　　家】英国/法国<br />
	【类　　别】纪录片<br />
	【文件格式】Rmvb<br />
	【文件大小】482 MB<br />
	【视频尺寸】1280 x 720<br />
	【影片长度】40 Mins<br />
	【对白语言】英语<br />
	【字幕语言】中英双字幕<br />
	【导　　演】Ronan Chapalain<br />
	　　　　　　Pascal Vuong<br />
	【主　　演】Guillaume Denaiffe ....Conservatory assistant<br />
	　　　　　　Norbert Ferrer ....Jacques<br />
	　　　　　　Chloe Hollings ....Julie<br />
	　　　　　　Richard Rider ....Georges Cuvier<br />
	<br />
	【内容简介】<br />
	<br />
	跟着想像力丰富的Julie回到三叠纪、侏罗纪和白垩纪时期，发掘惊人的海底世界，一起看看力量强大的巨型滑齿龙、长颈的薄板龙和巨大的秀尼鱼龙如何在恐龙统治地球之前称霸海底王国。<br />
	<br />
	【影片截图】<br />
	<br />
	<img alt="" height="337" src="http://img.album.pchome.net/54/84/69/41/9f0fc43cd5dbcc597d32bd3f9a72f71e.jpg" style="cursor: pointer" width="600" /></p>
<p>
	<img alt="" height="337" src="http://img.album.pchome.net/54/84/69/41/2a13b74755a0265113490e223f58f559.jpg" style="cursor: pointer" width="600" /></p>
<p>
	<img alt="" height="337" src="http://img.album.pchome.net/54/84/69/41/e2172ed6895966815aa1a4965a456869.jpg" style="cursor: pointer" width="600" /></p>
<p>
	[下载地址]： <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2292/飘花电影piaohua.com雷克斯海3D：史前世界BD中英双字1280高清.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2292/飘花电影piaohua.com雷克斯海3D：史前世界BD中英双字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1C54110-54622.jpg{/dede:field}
