{dede:field name='keywords'}大侦探波洛之怪钟疑案高清迅雷下{/dede:field}
{dede:field name='description'}大侦探波洛之怪钟疑案高清迅雷下载、免费下载，大侦探波洛之怪钟疑案高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}大侦探波洛之怪钟疑案高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-20{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="/uploads/allimg/c120525/133O0a033Z-G539.jpg" style="width: 500px; height: 629px" /><img alt="" src="/uploads/allimg/c120525/133O0a04360-S0A.jpg" /></p>
<p>
	◎译　　名　怪钟疑案<br />
	◎片　　名　Poirot：The Clocks<br />
	◎年　　代　2009<br />
	◎国　　家　英国<br />
	◎类　　别　犯罪/剧情/惊悚<br />
	◎语　　言　英语<br />
	◎IMDB评分 &nbsp;7.8/10 (238 votes)<br />
	◎IMDB链接&nbsp; http://www.bluemv.com<br />
	◎文件格式　X264 + AC3<br />
	◎视频尺寸　1280 x 720<br />
	◎片　　长　93 Mins<br />
	◎导　　演　Charles Palmer<br />
	◎主　　演　David Suchet &nbsp;... &nbsp;Hercule Poirot<br />
	　　　　　　Olivia Grant &nbsp;... &nbsp;Annabel Larkin<br />
	　　　　　　Anna Skellern &nbsp;... &nbsp;Fiona Hanbury<br />
	　　　　　　Tom Burke &nbsp;... &nbsp;Lt. Colin Race &nbsp;<br />
	　　　　　　Andrew Havill &nbsp;... &nbsp;Sven Hjerson<br />
	　　　　　　Victoria Wicks &nbsp;... &nbsp;Mrs Swinburne<br />
	　　　　　　Jaime Winstone &nbsp;... &nbsp;Sheila Webb<br />
	　　　　　　Sinead Keenan &nbsp;... &nbsp;Nora Bren<br />
	<br />
	◎简　　介<br />
	<br />
	一座普通的临街公寓，一个被指定到那里发现尸体的年轻女孩，一具特地跑到那里被谋杀的身份不明的尸体，一个平凡孤单的年老盲女人以及四个突然冒出来的钟。其中一个，钟面上刻着：ROSEMARY。是在纪念谁？是在缅怀谁？还是在暗示着谁？<br />
	<br />
	一条弯月形被拆分成两段的街道，一个写着61的便条，一群举止怪异的住户，还有14只猫，以及烦乱复杂的邻里关系。到底弯月代表着什么？61号的住户隐藏着什么秘密？谁才是男主角真正要找的间谍？<br />
	<br />
	一个身份隐秘的年轻男人，一个身世不明的年轻女人，一次浪漫而又神奇的邂逅。凶杀案发生的时候，他们在同一条街上徘徊，然后相遇，然后相爱。对方是否就是道貌岸然的凶手，爱情在该于不该中举棋不定。是命中注定的悲哀，还是冥冥中上天的安排？</p>
<p>
	<img alt="" src="/uploads/allimg/c120525/133O0a0D10-9D63.jpg" style="width: 720px; height: 405px" /><img alt="" src="/uploads/allimg/c120525/133O0a0M60-10F37.jpg" style="width: 720px; height: 405px" /><br />
	&nbsp;</p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="/uploads/allimg/c120525/133O0T31310-42214.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy125:piaohua@dy125.piaohua.com:7123/飘花电影piaohua.com怪钟疑案BD中字1280高清.rmvb</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O0a0W10-115611.jpg{/dede:field}
