{dede:field name='keywords'}绿色地带/叛逆谍战/关键指令/绿{/dede:field}
{dede:field name='description'}绿色地带/叛逆谍战/关键指令/绿区[BD中英双字1280x720+1024x576高清版无水印]迅雷下载、免费下载，绿色地带/叛逆谍战/关键指令/绿区[BD中英双字1280x720+1024x576高清版无水印]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}绿色地带/叛逆谍战/关键指令/绿区[BD中英双字1280x720+1024x576高清版无水印]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2010-06-14{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://3e:3e@m1.3edyy.com:1495/【3E电影院www.eee4.cc】绿色地带DVD中字.rmvb" target=_blank>ftftp://3e:3e@m1.3edyy.com:1495/【3E电影院www.eee4.cc】绿色地带DVD中字.rmvb</A></TD></TR></TBODY></TABLE><FONT color=#ff0000 size=2><STRONG><BR>2010年欧美最新惊险战争动作大片《绿色地带/关键指令/绿区》BD中字1024x576高清版无水印 [下载地址]：<IMG border=0 src="httftp://www.3edyy.com/templets/img/down.jpg{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MP6195F-2P38.jpg{/dede:field}
