{dede:field name='keywords'}蝴蝶效应2BD中英双字1024/1280高{/dede:field}
{dede:field name='description'}蝴蝶效应2BD中英双字1024/1280高清迅雷下载、免费下载，蝴蝶效应2BD中英双字1024/1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}蝴蝶效应2BD中英双字1024/1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-12-01{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://eee4.com:8112@vip19.eee4.com:8112/[3E迅雷电影站www.eee4.com]蝴蝶效应2DVD中英双字幕CD1.rmvb" target="_blank{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MOb9450-44544.jpg{/dede:field}
