{dede:field name='keywords'}X档案1BD中英双字1024/1280高清{/dede:field}
{dede:field name='description'}X档案1BD中英双字1024/1280高清迅雷下载、免费下载，X档案1BD中英双字1024/1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}X档案1BD中英双字1024/1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-12-12{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://e12:e12@xl2.eee4.com:9219/[3E电影站www.eee4.com]X档案电影版[DVD中英双字1024x576高清版].rmvb" target="_blank{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MOT5110-310P.jpg{/dede:field}
