<?php
$z[0]=Array("field","X档案1BD中英双字1024/1280高清",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","X档案1BD中英双字1024/1280高清迅雷下载、免费下载，X档案1BD中英双字1024/1280高清Gvod高清在线播放，剧情介绍等。",72,224);
$z[1][4]['name']="description";
$z[2]=Array("field","X档案1BD中英双字1024/1280高清",226,293);
$z[2][4]['name']="title";
$z[3]=Array("field","",295,334);
$z[3][4]['name']="writer";
$z[4]=Array("field","",336,375);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-12-12",377,427);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",429,466);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://e12:e12@xl2.eee4.com:9219/[3E电影站www.eee4.com]X档案电影版[DVD中英双字1024x576高清版].rmvb\" target=\"_blank",468,620);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MOT5110-310P.jpg",622,704);
$z[8][4]['name']="litpic";

?>