{dede:field name='keywords'}地心游记BD1280高清迅雷下载，免{/dede:field}
{dede:field name='description'}地心游记BD1280高清迅雷下载、免费下载，地心游记BD1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}地心游记BD1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-01-23{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://farm4.static.flickr.com/3226/2991143145_29120f5b2c.jpg" style="width: 388px; height: 500px" /></p>
<p>
	◎译　　名　地心历险记<br />
	◎片　　名　Journey to the Center of the Earth<br />
	◎年　　代　2008<br />
	◎国　　家　美国<br />
	◎类　　别　动作/冒险/家庭/幻想/科幻/惊悚<br />
	◎语　　言　英语<br />
	◎IMDB评分 6.2/10(8,546 votes)<br />
	◎IMDB链接 <a href="http://www.imdb.com/title/tt0373051/" target="_blank">http://www.imdb.com/title/tt0373051/</a><br />
	◎片　　长　92 mins<br />
	◎导　　演　埃里克&middot;布雷维格 Eric Brevig<br />
	◎主　　演　布兰登&middot;弗莱瑟 Brendan Fraser ....Trevor Anderson<br />
	　　　　　　乔什&middot;哈切森 Josh Hutcherson ....Sean Anderson<br />
	　　　　　　安妮塔&middot;布里姆 Anita Briem ....Hannah &aacute;sgeirsson<br />
	　　　　　　Garth Gilker ....Sigurbj?rn &aacute;sgeirsson<br />
	　　　　　　Giancarlo Caltabiano ....Leonard<br />
	　　　　　　Kaniehtii<a href="http://www.anzhuo4.com/" style="color: rgb(0, 0, 0); text-decoration: none;">android</a>o Horn ....Gum-Chewing Girl<br />
	　　　　　　Seth Meyers ....Professor Alan Kitzens<br />
	　　　　　　Jean Michel Par&eacute; ....Max Anderson<br />
	　　　　　　Jane Wheeler ....Elizabeth<br />
	　　　　　　Frank Fontaine ....Old Man<br />
	<br />
	◎简　　介　<br />
	<br />
	　　特雷弗(布兰登&middot;弗莱瑟饰演)是大学的自然科学教授，却提出了一套与现有科学体系完全对立的理论认为凡尔纳的小说并非只是科幻而是确有其事。结果此事被学院传为笑料，几乎将特雷弗的学术名声毁于一旦。后来，特雷弗和侄子肖恩(乔什&middot;哈切森饰演)以及<a href="http://www.6dtaobao.com/" style="color: rgb(0, 0, 0); text-decoration: none;">淘宝网女装</a>美女汉娜(安妮塔&middot;布里姆饰演)在冰岛旅行时，意外的发现了一个洞穴。三个人沿着洞穴往里走，踏破了地上的薄冰跌入了无底的深渊，好在底下的大湖救了他们的命。三个人游出湖面后，发现自己进入了一个神秘的地心世界。在那里生存着各种稀奇古怪的生物，有着各种光怪陆离的景象。原来凡尔纳的著述竟真的确有其事。特雷弗也终于可以扬眉吐气了。不过，首先要解决的问题是，如何像凡尔纳当年一样找到另外一条出路，逃出生天&hellip;&hellip;<br />
	<img alt="" src="http://img165.poco.cn/mypoco/myphoto/20120122/20/62564813201201222052511695309718108_003.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img165.poco.cn/mypoco/myphoto/20120122/20/62564813201201222052511695309718108_002.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img165.poco.cn/mypoco/myphoto/20120122/20/62564813201201222052511695309718108_001.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img165.poco.cn/mypoco/myphoto/20120122/20/62564813201201222052511695309718108_000.jpg" style="width: 720px; height: 405px" /><br />
	&nbsp;</p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="
ftp://dy125:piaohua@dy125.piaohua.com:7528/飘花电影piaohua.com地心游记BD中字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:7528/飘花电影piaohua.com地心游记BD中字1280高清.rmvb </a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15910040-59418.jpg{/dede:field}
