{dede:field name='keywords'}狐狸与猎狗BD高清中英双字1024*5{/dede:field}
{dede:field name='description'}狐狸与猎狗BD高清中英双字1024*576迅雷下载、免费下载，狐狸与猎狗BD高清中英双字1024*576Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}狐狸与猎狗BD高清中英双字1024*576{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-08-31{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="/uploads/allimg/c120525/133O04CY0-164036.jpg" /></p>
<p>
	◎译　　名　狐狸与猎狗/狐狸与猎犬<br />
	◎片　　名　The Fox and the Hound<br />
	◎年　　代　1981<br />
	◎国　　家　美国<br />
	◎类　　别　动画/剧情/家庭<br />
	◎语　　言　英语<br />
	◎字　　幕　英文<br />
	◎IMDB评分　7.1/10 (13,973 votes)<br />
	◎IMDB链接　http://www.imdb.com/title/tt0082406/<br />
	◎文件大小　3/4 DVD<br />
	◎片　　长　01:22:55<br />
	◎导　　演　Ted Berman<br />
	　　　　　　Richard Rich<br />
	　　　　　　Art Stevens<br />
	◎主　　演　米基&middot;鲁尼 Mickey Rooney&nbsp;&nbsp;....Adult Tod (voice)<br />
	　　　　　　库尔特&middot;拉塞尔 Kurt Russell&nbsp;&nbsp;....Adult Copper (voice)<br />
	　　　　　　珀尔&middot;贝利 Pearl Bailey&nbsp;&nbsp;....Big Mama (voice)<br />
	　　　　　　杰克&middot;艾伯森 Jack Albertson&nbsp;&nbsp;....Hunter (Amos Slade) (voice)<br />
	　　　　　　Sandy Duncan&nbsp;&nbsp;....Vixey (voice)<br />
	　　　　　　Jeanette Nolan&nbsp;&nbsp;....Widow Tweed (voice)<br />
	　　　　　　Pat Buttram&nbsp;&nbsp;....Chief (voice)<br />
	　　　　　　约翰&middot;菲尔德 John Fiedler&nbsp;&nbsp;....Porcupine (voice)<br />
	　　　　　　约翰&middot;麦克因泰 John McIntire&nbsp;&nbsp;....Grumpy Badger (voice)<br />
	　　　　　　Richard Bakalyan&nbsp;&nbsp;....Dinky (voice)<br />
	　　　　　　保罗&middot;温切尔 Paul Winchell&nbsp;&nbsp;....Boomer (voice)<br />
	　　　　　　基斯&middot;库甘 Keith Coogan&nbsp;&nbsp;....Young Tod (voice) (as Keith Mitchell)<br />
	　　　　　　科里&middot;费尔德曼 Corey Feldman&nbsp;&nbsp;....Young Copper (voice)<br />
	<br />
	<br />
	◎简　　介<br />
	<br />
	<b>剧情</b><br />
	&nbsp; &nbsp;&nbsp; &nbsp; 小狐狸 Tod 与小猎狗 Copper 自幼即结成最好的朋友，他们一同玩耍嘻闹，过着无忧无虑的生活。但是当他们渐渐长大，也渐渐知道彼此是天敌的命运，一次意外 Tod 不小心害照顾 Copper 的老狗 Chief 摔断了腿，于是 Copper 的主人 Amos Slade 就带着 Copper 深山缉狐而来，他们过去真挚的情谊能否摆脱宿命的纠缠？<br />
	<br />
	<b>一句话评论</b><br />
	Two friends that didn&#39;t know they were supposed to be enemies.<br />
	<br />
	<b>幕后制作</b><br />
	&nbsp; &nbsp;&nbsp;&nbsp;影片开始由于人员不整而一拖再拖，直到一年后一批新鲜血液加盟Don Bluth工作室之后，影片才开始进入正轨。负责设计托德、卡普和熊之间斗争一场高潮戏的新人Glen Keane，觉得最初所设计的故事情节不够紧张刺激，于是他重画了整场戏。他还计划用碳笔而不是铅笔画战斗一场戏，但制片预算阻止了他。制片人Wolfgang Reitherman将他儿子饲养的宠物狐狸借给剧组作为模特，该狐狸亦因此成为托德的原型。起初，编剧设计老狗Chief由于托德的原因被火车撞伤，随后死去，以此作为卡普追捕托德的合理性理由。不过，出于和&ldquo;Trusty from Lady and the Tramp&rdquo; (1955)一样的原因，一些成员担心老狗Chief的死亡过于浓重、阴暗，对儿童心理不利，最后改为Chief生命垂危，不久后康复。本片也以细腻美好的情感深受观众喜爱，并获得德国金银幕最佳动画片奖。&nbsp;</p>
<p>
	<img alt="" src="/uploads/allimg/c120525/133O04D10Z-1K959.jpg" style="width: 640px; height: 360px" /><img alt="" src="/uploads/allimg/c120525/133O04D1P-1X3K.jpg" style="width: 640px; height: 360px" /><img alt="" src="/uploads/allimg/c120525/133O04D25F-1c401.jpg" style="width: 640px; height: 360px" /></p>
<p>
	[下载地址]： &nbsp;<img border="0" src="/uploads/allimg/c120524/133N2Z4FF-102231.jpg" /></p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy67:piaohua@dy67.piaohua.com:1062/飘花电影piaohua.com狐狸与猎狗BD高清中英双字1024分辨率.rmvb</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O04D31Z-20R60.jpg{/dede:field}
