{dede:field name='keywords'}皇家卫兵BD1280高清中字迅雷下载{/dede:field}
{dede:field name='description'}皇家卫兵BD1280高清中字迅雷下载、免费下载，皇家卫兵BD1280高清中字Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}皇家卫兵BD1280高清中字{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-21{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120520/23/17870980201205202321123973798574158_000.jpg" style="width: 500px; height: 724px" /></p>
<p>
	◎译　　名　皇家卫兵<br />
	◎片　　名　Eklavya<br />
	◎年　　代　2007<br />
	◎国　　家　印度<br />
	◎类　　别　剧情/惊悚/动作<br />
	◎语　　言　北印度语<br />
	◎片　　长　107 Min<br />
	◎导　　演　Vidhu Vinod Chopra<br />
	◎主　　演　Jackie Shroff .... Rana Jyotiwardhan<br />
	　　　　　　Vidya Balan .... Rajeshwari &#39;Rajjo&#39; Singh<br />
	　　　　　　Sanjay Dutt .... DSP Pannalal Chohaar<br />
	　　　　　　Saif Ali Khan .... Prince Harshwardhan<br />
	　　　　　　阿米塔布&middot;巴沙坎 Amitabh Bachchan .... Eklavya<br />
	　　　　　　Boman Irani .... Rana Jaywardhan<br />
	　　　　　　Jasjit Shergill .... Udaywardhan<br />
	　　　　　　Raima Sen .... Princess Nandinidevi<br />
	　　　　　　Sharmila Tagore .... Rani Suhasinidevi<br />
	　　　　　　Parikshat Sahni .... Omkar Singh<br />
	<br />
	◎简　　介　<br />
	<br />
	&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp;&nbsp;在现代印度，有一个坚固的堡垒，里面有一个早已覆灭的王朝，和一个失势的国王。<br />
	可是，埃克拉亚（Amitabh Bachchan扮演），王朝的守卫者，却生活在一个扭曲的时空里。他生活的唯一目的就是要保护那座城堡，那个王朝，和国王。埃克拉亚家族的九代人都在保保着Devigarh，一个位于拉贾斯坦帮的有着几百年历史的大本营。他的枪法很神。他的忠诚值得歌功。埃克拉亚花了他的毕生去守护着王室并保守他们的秘密，但是他现在老了，而且眼神也越来越差。因为受不了这里令人窒息的习俗，这个皇室的继承人Harshwardhan王子（Saif Ali Khan扮演）搬到了伦敦。但是因为Rani Suhasinideve王后（Sharmila Tagore扮演）的死，Harshwardhan王子不得不回到了这里。<br />
	&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp;&nbsp;王子的回归给这个死气沉沉的城堡突然充满了快乐。而他饱受精神压抑的双胞胎妹妹Nandini公主（Raima Sen）和他的儿时至爱Rajjo（Vidya Balan）见到他时也万分高兴。但是重逢的快乐没有维持多久。<br />
	&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp;&nbsp;因为王国中动荡不安：农民的土地正在被剥夺。而国王，Rana Jaywardhan（Boman Irani扮演），支持对无助的农民使用暴行。此时国王接到一个恐吓电话，于是来了一位不会尊重人的警官，Pannalal Chohar（Sanjay Dutt扮演）进行调查。但是他可能来得太晚了点。<br />
	王国里脆弱的和平被一阵枪击声被打碎了。于是，曾经严密守护的秘密逐渐浮出水面。<br />
	于是，发生在现代的一部充满戏剧性的令人正襟危坐的惊险大片开始了。该片由多名大腕联袂演出&mdash;部电影标志着VidhuVinod Chopra导演退出电影界七年后的复出。<br />
	&nbsp;<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120520/23/17870980201205202321123973798574158_004.jpg" style="width: 640px; height: 360px" /></p>
<p>
	<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120520/23/17870980201205202321123973798574158_003.jpg" /></p>
<p>
	<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120520/23/17870980201205202321123973798574158_002.jpg" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.net/" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy241:piaohua@117.41.229.29:2029/飘花电影piaohua.com皇家卫兵BD1280高清中字.rmvb">ftp://dy241:piaohua@117.41.229.29:2029/飘花电影piaohua.com皇家卫兵BD1280高清中字.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1600Z60-53062.jpg{/dede:field}
