{dede:field name='keywords'}生死朗读/朗读者/我原意为你朗读{/dede:field}
{dede:field name='description'}生死朗读/朗读者/我原意为你朗读BD中英双字1024/1280高清迅雷下载、免费下载，生死朗读/朗读者/我原意为你朗读BD中英双字1024/1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}生死朗读/朗读者/我原意为你朗读BD中英双字1024/1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-01-05{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://e33:e33@xl2.eee4.com:9916/[3E电影站www.eee4.com]生死朗读[修正]CD1.rmvb" target="_blank{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MOP2910-391R.jpg{/dede:field}
