<?php
$z[0]=Array("field","生死朗读/朗读者/我原意为你朗读",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","生死朗读/朗读者/我原意为你朗读BD中英双字1024/1280高清迅雷下载、免费下载，生死朗读/朗读者/我原意为你朗读BD中英双字1024/1280高清Gvod高清在线播放，剧情介绍等。",73,273);
$z[1][4]['name']="description";
$z[2]=Array("field","生死朗读/朗读者/我原意为你朗读BD中英双字1024/1280高清",275,366);
$z[2][4]['name']="title";
$z[3]=Array("field","",368,407);
$z[3][4]['name']="writer";
$z[4]=Array("field","",409,448);
$z[4][4]['name']="source";
$z[5]=Array("field","2012-01-05",450,500);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",502,539);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://e33:e33@xl2.eee4.com:9916/[3E电影站www.eee4.com]生死朗读[修正]CD1.rmvb\" target=\"_blank",541,672);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MOP2910-391R.jpg",674,756);
$z[8][4]['name']="litpic";

?>