{dede:field name='keywords'}冲天小子HD国语中字1280高清[DVD{/dede:field}
{dede:field name='description'}冲天小子HD国语中字1280高清[DVD国语＋粤语]迅雷下载、免费下载，冲天小子HD国语中字1280高清[DVD国语＋粤语]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}冲天小子HD国语中字1280高清[DVD国语＋粤语]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-10-28{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://3e:3e@www2.eee4.com:893/[3E电影站www.eee4.cn]冲天小子DVD国语.rmvb" target="_blank{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MQ2X640-59195.jpg{/dede:field}
