<?php
$z[0]=Array("field","冲天小子HD国语中字1280高清[DVD",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","冲天小子HD国语中字1280高清[DVD国语＋粤语]迅雷下载、免费下载，冲天小子HD国语中字1280高清[DVD国语＋粤语]Gvod高清在线播放，剧情介绍等。",73,249);
$z[1][4]['name']="description";
$z[2]=Array("field","冲天小子HD国语中字1280高清[DVD国语＋粤语]",251,330);
$z[2][4]['name']="title";
$z[3]=Array("field","",332,371);
$z[3][4]['name']="writer";
$z[4]=Array("field","",373,412);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-10-28",414,464);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",466,503);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://3e:3e@www2.eee4.com:893/[3E电影站www.eee4.cn]冲天小子DVD国语.rmvb\" target=\"_blank",505,631);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MQ2X640-59195.jpg",633,716);
$z[8][4]['name']="litpic";

?>