{dede:field name='keywords'}地域无门HD清晰版国语中字2012中{/dede:field}
{dede:field name='description'}地域无门HD清晰版国语中字2012中国动作迅雷下载、免费下载，地域无门HD清晰版国语中字2012中国动作Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}地域无门HD清晰版国语中字2012中国动作{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-16{/dede:field}
{dede:field name='body'}<p>
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120516/19/56643687201205161908252773251766241_005.jpg" /></p>
<p>
	&nbsp;<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120516/19/56643687201205161908252773251766241_004.jpg" /></p>
<p>
	导演: 吴耀权<br />
	编剧: 赵犇 / 郑懿<br />
	主演: 立威廉 / 陈紫函 / 谭耀文 / 牛萌萌 / 李兆基 / 石天琦 / 柳海龙 / 魏璐<br />
	类型: 犯罪 / 动作 / 惊悚<br />
	制片国家/地区: 中国大陆<br />
	语言: 汉语普通话<br />
	上映日期: 2012-05-16(中国大陆)<br />
	片长: 83分钟<br />
	又名: Death Zone</p>
<p>
	<br />
	剧情简介</p>
<p>
	　　刚刚硕士毕业的夏梦（陈紫函 饰）跟新婚丈夫常在（立威廉 饰）去泰国旅游，途中听说金沙谷很漂亮，身为记者的常在决定带着夏梦来一趟浪漫之旅。<br />
	　　在前往金沙谷的途中，夏梦看见了一张刀疤脸，受到惊吓，更莫名其妙被一辆越野车撞翻，险些丧命，接着常在又跌落陷阱里，幸得一个叫郑大林（谭耀文 饰）的年轻人相救。<br />
	　　夏梦觉得郑大林和他的恋人伊拉（牛萌萌 饰）关系微妙，身份可疑，提醒常在小心，但是常在却陶醉于美丽的风景之中。两队恋人决定搭伴而行，途中他们获知，山下有一对旅游者被杀，当地警方正在展开调查，他们在感叹当地社会治安差的同时，也对自己身处迷幻般的丛林心生不安！<br />
	　　一路上，他们遇到一个来去无踪的神秘性感女子；遇到了一对死于非命的年轻男女；还有那个一直尾随他们的刀疤脸......<br />
	　　随着旅程的深入，危机四伏，扑簌迷离，他们不知道自己到底卷入了什么样的境况中。猜忌、绝境、惊悚接踵而至，让人的肉体和精神一次又一次地接受考验，而这一切只是刚刚开始......　</p>
<p>
	<br />
	◎影片截图</p>
<p>
	&nbsp;&nbsp;<img src="http://img170.poco.cn/mypoco/myphoto/20120516/19/56643687201205161908252773251766241_003.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 338px; border-top: 0px solid; border-right: 0px solid" /></p>
<p>
	&nbsp;<img src="http://img170.poco.cn/mypoco/myphoto/20120516/19/56643687201205161908252773251766241_002.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 338px; border-top: 0px solid; border-right: 0px solid" /></p>
<p>
	&nbsp;<img src="http://img170.poco.cn/mypoco/myphoto/20120516/19/56643687201205161908252773251766241_000.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 338px; border-top: 0px solid; border-right: 0px solid" /></p>
<p>
	&nbsp;<img src="http://img170.poco.cn/mypoco/myphoto/20120516/19/56643687201205161908252773251766241_001.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 338px; border-top: 0px solid; border-right: 0px solid" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.net/" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3433/飘花电影piaohua.com地域无门HD清晰版国语中字.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3433/飘花电影piaohua.com地域无门HD清晰版国语中字.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1494c60-4LP.jpg{/dede:field}
