{dede:field name='keywords'}红猪BD国日双语中字1024高清经典{/dede:field}
{dede:field name='description'}红猪BD国日双语中字1024高清经典动画迅雷下载、免费下载，红猪BD国日双语中字1024高清经典动画Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}红猪BD国日双语中字1024高清经典动画{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-03-30{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://apollo.s.dpool.sina.com.cn/nd/dataent/moviepic/pics/150/moviepic_b1b36ad5ccff5c81187cebf83dde0ec9.jpg" /></p>

<p>
	◎译　　名　红猪/飞天红猪侠<br />
	◎片　　名　Crimson Pig<br />
	◎年　　代　1992<br />
	◎国　　家　日本<br />
	◎类　　别　动画<br />
	◎语　　言　日语/国语<br />
	◎字　　幕　中日双语字幕<br />
	◎文件格式　X264 + AAC<br />
	◎视频尺寸　1024 X 576<br />
	◎文件大小　1.4 G<br />
	◎片　　长　93 Min　<br />
	◎导　　演　宫崎骏 Miyazaki.Hayao<br />
	◎主　　演　Kurenai.No.Buta.(声/森山周一郎)<br />
	　　　　　　Jina.Sama.(声/加藤登纪子)<br />
	　　　　　　Pikkoro.Oyaji.(声/桂三枝)<br />
	　　　　　　Additional.(声/Greg.Ellis)<br />
	　　　　　　Manmayuto.No.Shach.(声/上条恒彦)<br />
	　　　　　　Fio.Pikkoro.(声/冈村明美)<br />
	　　　　　　Donarudo.Kachisu.(声/大冢明夫)<br />
	　　　　　　Ba.Chan.(声/关弘子)</p>
<p>
	◎简　　介　</p>
<p>
	　　片中的时代背景被设在第一次世界大战结束不久后的意大利。1920年代的亚德里亚海，一群无恶不作的空中海盗横行无忌，他们到处抢掠(除了一间酒吧)。前意大利空军英雄，一生挚爱飞行的波鲁克决意从人世的庸俗生活中脱身而出，自施魔法变成一头猪(虽然有些离谱，但也是宫崎骏的创作魅力所在)，凭借出色的技术驾驶红色飞艇孤身与横行在亚德里亚海的空中强盗周旋，以赚取赏金逍遥度日。海盗们为了对付波鲁克，从美国请来外援&quot;马面人&quot;卡奇斯(猪头对马面)。因为飞机出了问题，波鲁克被卡奇斯打败了。在17岁的飞艇设计师菲欧的精心设计下，一架全新高性能的飞机诞生了。</p>
<p>
	　　影片的高潮是波鲁克和卡奇斯之间展开的一场惊险而又滑稽的赌博。其实他们两人的争斗不仅仅是为了维护各自的名誉，同时也是围绕着两个女性的争夺。这两个女性，17岁的飞艇设计师菲欧，和亚德里亚海飞行员心目中的女神吉娜，都是改变主人翁波鲁克生活态度的至关重要的角色。影片在结尾处却一反宫崎骏其他剧作，保留了一个悬念不作答:主人翁波鲁克是否真正恢复了人形？他后来又在过怎样的一种生活？</p>
<p>
	　　带着激情在蓝天碧波间畅游，拥有名望和荣誉，却也有孤独和悔恨。这就是波鲁克&middot;罗梭，亚德里亚海上的&quot;红猪&quot;。</p>
<p>
	　　以动画大师宫崎骏最喜爱的天空做为故事进行的舞台，加上蔚蓝地中海上空令人目不暇接的飞行艇追逐、深具传奇色彩的人物描绘，&quot;红猪&quot;是您珍藏宫崎骏动画不容错过的经典之作！整部作品情节连贯、紧凑，张弛有度。几场空战的场面紧张激烈，多次利用镜头重迭的手法，以期让观众得到一种超越时间的速度感。结尾构思精巧，让人感觉多少有些意料之外，但细细一想却又在情理之中。一句典型带有宫崎风格的双关语巧妙地将沉浸在惆怅与感慨中的观众拉回现实，并给予他们一丝重获希望的悬念，确实是大师手笔。</p>
<p>
	　　正如宫崎骏的其他作品一样，这个故事也发生在充满魔幻色彩的世界里。&quot;魔幻&quot;往往被用作一个重要的道具，以发挥他超乎常人的想象力，打破常规，让一切不合理的成为合理，让观众在现实世界中形成的种种固定观念被逐一瓦解，把观众慢慢带入一个引人入胜的奇幻世界中，同时也让观众一次一次享受着以意外的方式打破这些观念所带来的刺激和惊喜。但是，宫崎骏的影片之所以没有变成单纯的魔幻片或儿童片，正是因为其中真实且细致的情感刻画。在他笔下，甚至连非人类的动物也展现出各种极具人性化的神态和动作。</p>
<p>
	[下载地址]： &nbsp;<img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" /></p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3106/飘花电影piaohua.com红猪BD国日双语中字1024高清.mkv">ftp://dy44:piaohua@dy44.piaohua.com:3106/飘花电影piaohua.com红猪BD国日双语中字1024高清.mkv</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O151V110-29118.jpg{/dede:field}
