<?php
$z[0]=Array("field","黎巴嫩[BD中字1024x576高清版]迅",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","黎巴嫩[BD中字1024x576高清版]迅雷下载、免费下载，黎巴嫩[BD中字1024x576高清版]Gvod高清在线播放，剧情介绍等。",73,223);
$z[1][4]['name']="description";
$z[2]=Array("field","黎巴嫩[BD中字1024x576高清版]",225,291);
$z[2][4]['name']="title";
$z[3]=Array("field","",293,332);
$z[3][4]['name']="writer";
$z[4]=Array("field","",334,373);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-08-31",375,425);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",427,464);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://5e:5e@m1.eee4.cc:1519/【3E电影院www.eee4.cc】黎巴嫩[DVD中英双字].rmvb\" target=_blank>ftftp://5e:5e@m1.eee4.cc:1519/【3E电影院www.eee4.cc】黎巴嫩[DVD中英双字].rmvb</A></TD></TR></TBODY></TABLE><BR><FONT color=#ff0000 size=2><STRONG>[下载地址]：<IMG border=0 src=\"httftp://www.3edyy.com/templets/img/down.jpg",466,817);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MP63MZ-5FP.jpg",819,899);
$z[8][4]['name']="litpic";

?>