{dede:field name='keywords'}黎巴嫩[BD中字1024x576高清版]迅{/dede:field}
{dede:field name='description'}黎巴嫩[BD中字1024x576高清版]迅雷下载、免费下载，黎巴嫩[BD中字1024x576高清版]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}黎巴嫩[BD中字1024x576高清版]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2010-08-31{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://5e:5e@m1.eee4.cc:1519/【3E电影院www.eee4.cc】黎巴嫩[DVD中英双字].rmvb" target=_blank>ftftp://5e:5e@m1.eee4.cc:1519/【3E电影院www.eee4.cc】黎巴嫩[DVD中英双字].rmvb</A></TD></TR></TBODY></TABLE><BR><FONT color=#ff0000 size=2><STRONG>[下载地址]：<IMG border=0 src="httftp://www.3edyy.com/templets/img/down.jpg{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MP63MZ-5FP.jpg{/dede:field}
