{dede:field name='keywords'}梁亮亮和谢小星的简单故事HD国语{/dede:field}
{dede:field name='description'}梁亮亮和谢小星的简单故事HD国语中英双字爱情2012迅雷下载、免费下载，梁亮亮和谢小星的简单故事HD国语中英双字爱情2012Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}梁亮亮和谢小星的简单故事HD国语中英双字爱情2012{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-02-29{/dede:field}
{dede:field name='body'}<p>
	<img border="0" src="http://img.xzz.cc/attachment/thumb/Mon_1202/6_271573_a39cf0fceefb237.jpg?101" style="max-width: 750px; max-height: 750px" title="点击查看原图" /></p>
<p>
	本片据说是&ldquo;第十二届北京大学生电影节&rdquo;电影短片，简单的故事便是如此的简单，没有波澜万丈，唯有水滴石穿。<br />
	评价<br />
	　　据闻拍摄单位为中国传媒大学南广学院艺术传播系，引用的男女演员亦为当地人士，讲的故事是遍布国内大学遍地可见的物质与精神与爱情的相互作用老套故事，借用网上某银的说法，&ldquo;此片为大学爱情的总结版&rdquo;。<br />
	编辑本段剧情<br />
	文字<br />
	　　很多人都会有那么一段充满欢笑又带着遗憾结束恋爱，没有大起大落没有天灾人祸，多年后回忆起来都会有些模糊，把一些不太清晰但又值得回味的片段拼接在一起，这就是《梁亮亮和谢小星的简单故事》。&lt;H3 bk-sidecatalog-title?&gt;影评<br />
	　　作为《老男孩》类似的题材片，我们从中又一次读出了80后为主力的逝旧情怀，相似的模样，相同的地方，相类的故事，相通的情感&hellip;&hellip;虽然每个银都想演绎不同的人生，但学生基数量超出我们预期的国情，还是让我们的学习和生活，存在着或多或少的相似交葛。那一首首老去的歌曲，那一次次挥别的激情，那一件件淡然的琐事，似一把把坚韧的钢锨，一回回地挖掘着埋藏心底的记忆，一遍遍勾起了尘封已久的回忆。</p>
<p>
	影评<br />
	　　作为《老男孩》类似的题材片，我们从中又一次读出了80后为主力的逝旧情怀，相似的模样，相同的地方，相类的故事，相通的情感&hellip;&hellip;虽然每个银都想演绎不同的人生，但学生基数量超出我们预期的国情，还是让我们的学习和生活，存在着或多或少的相似交葛。那一首首老去的歌曲，那一次次挥别的激情，那一件件淡然的琐事，似一把把坚韧的钢锨，一回回地挖掘着埋藏心底的记忆，一遍遍勾起了尘封已久的回忆。</p>

<p>
	<img alt="" src="http://pic.piaohua.com/0701pic/allimg/120229/1-120229153P9200.jpg" /></p>

<p>
	<img alt="" src="http://pic.piaohua.com/0701pic/allimg/120229/1-120229153QWb.jpg" /></p>

<p>
	<img alt="" src="http://pic.piaohua.com/0701pic/allimg/120229/1-120229153R3K3.jpg" /></p>
<p>
	[下载地址]： &nbsp;<img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" /></p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2920/飘花电影piaohua.com梁亮亮和谢小星的简单故事HD国语中英双字.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:2920/飘花电影piaohua.com梁亮亮和谢小星的简单故事HD国语中英双字.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2920/飘花电影piaohua.com梁亮亮和谢小星的简单故事HD国语中英双字.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15Q2010-25449.jpg{/dede:field}
