<?php
$z[0]=Array("field","2011韩国小姐HD中字迅雷下载，免",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","2011韩国小姐HD中字迅雷下载、免费下载，2011韩国小姐HD中字Gvod高清在线播放，剧情介绍等。",73,203);
$z[1][4]['name']="description";
$z[2]=Array("field","2011韩国小姐HD中字",205,261);
$z[2][4]['name']="title";
$z[3]=Array("field","",263,302);
$z[3][4]['name']="writer";
$z[4]=Array("field","",304,343);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-11-10",345,395);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>\r\n	<img alt=\"\" src=\"/uploads/allimg/c120524/133N493S920-13954.jpg\" /></p>\r\n<p>\r\n	&nbsp;<img alt=\"\" src=\"/uploads/allimg/c120524/133N493U2F-21334.jpg\" /></p>\r\n<p>\r\n	&nbsp;<img alt=\"\" src=\"/uploads/allimg/c120524/133N493V560-3G45.jpg\" /></p>\r\n<p>\r\n	8月4日电 &ldquo;首尔赛区冠军&rdquo;李成慧（Lee Seong-hye）摘得2011韩国小姐桂冠。3日晚7时，在首尔世宗路世宗文化会馆举行的2011韩国小姐选拔赛上，李成慧一举夺魁。金惠善、金艺瑟获选为亚军和季军。</p>\r\n<p>\r\n	&nbsp;</p>\r\n\r\n<p>\r\n	[下载地址]： &nbsp;<img border=\"0\" src=\"/uploads/allimg/c120524/133N2Z4FF-102231.jpg\" /></p>\r\n<table bgcolor=\"#ff8c00\" border=\"0\" cellpadding=\"5\" cellspacing=\"1\" width=\"100%\">\r\n	<tbody>\r\n		<tr>\r\n			<td bgcolor=\"#ffffbb\" style=\"line-height: 18px; word-break: break-all\" width=\"100%\">\r\n				&nbsp;ftp://dy44:piaohua@dy44.piaohua.com:2045/飘花电影piaohua.com2011韩国小姐HD中字.rmvb </td>\r\n		</tr>\r\n	</tbody>\r\n</table>",397,1319);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c120524/133N493W60-4E91.jpg",1321,1403);
$z[7][4]['name']="litpic";

?>