{dede:field name='keywords'}2011韩国小姐HD中字迅雷下载，免{/dede:field}
{dede:field name='description'}2011韩国小姐HD中字迅雷下载、免费下载，2011韩国小姐HD中字Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}2011韩国小姐HD中字{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-11-10{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="/uploads/allimg/c120524/133N493S920-13954.jpg" /></p>
<p>
	&nbsp;<img alt="" src="/uploads/allimg/c120524/133N493U2F-21334.jpg" /></p>
<p>
	&nbsp;<img alt="" src="/uploads/allimg/c120524/133N493V560-3G45.jpg" /></p>
<p>
	8月4日电 &ldquo;首尔赛区冠军&rdquo;李成慧（Lee Seong-hye）摘得2011韩国小姐桂冠。3日晚7时，在首尔世宗路世宗文化会馆举行的2011韩国小姐选拔赛上，李成慧一举夺魁。金惠善、金艺瑟获选为亚军和季军。</p>
<p>
	&nbsp;</p>

<p>
	[下载地址]： &nbsp;<img border="0" src="/uploads/allimg/c120524/133N2Z4FF-102231.jpg" /></p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				&nbsp;ftp://dy44:piaohua@dy44.piaohua.com:2045/飘花电影piaohua.com2011韩国小姐HD中字.rmvb </td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120524/133N493W60-4E91.jpg{/dede:field}
