{dede:field name='keywords'}《My,Girl》迅雷下载，免费下载{/dede:field}
{dede:field name='description'}《My Girl》迅雷下载、免费下载，《My Girl》Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}《My Girl》{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2006-08-04{/dede:field}
{dede:field name='body'}<P>播放后双击视频“全屏”</P> 

<object classid="CLSID:22d6f312-b0f6-11d0-94ab-0080c74c7e95" class="OBJECT" id="MediaPlayer" width="500" height="350" ><param name="ShowStatusBar" value="-1"><param name="Filename" value="http://222.77.177.220:88/Video/2006/03/13/Film0_1e25243a-63ed-44f2-bb89-b5a8fbe1269b_z.wmv"></embed></object><br/> 

<P>下载地址 <br>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120524/133N353DD0-2G248.gif{/dede:field}
