<?php
$z[0]=Array("field","《My,Girl》迅雷下载，免费下载",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","《My Girl》迅雷下载、免费下载，《My Girl》Gvod高清在线播放，剧情介绍等。",72,188);
$z[1][4]['name']="description";
$z[2]=Array("field","《My Girl》",190,239);
$z[2][4]['name']="title";
$z[3]=Array("field","",241,280);
$z[3][4]['name']="writer";
$z[4]=Array("field","",282,321);
$z[4][4]['name']="source";
$z[5]=Array("field","2006-08-04",323,373);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<P>播放后双击视频“全屏”</P> \r\n\n<object classid=\"CLSID:22d6f312-b0f6-11d0-94ab-0080c74c7e95\" class=\"OBJECT\" id=\"MediaPlayer\" width=\"500\" height=\"350\" ><param name=\"ShowStatusBar\" value=\"-1\"><param name=\"Filename\" value=\"http://222.77.177.220:88/Video/2006/03/13/Film0_1e25243a-63ed-44f2-bb89-b5a8fbe1269b_z.wmv\"></embed></object><br/> \r\n\n<P>下载地址 <br>",375,767);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c120524/133N353DD0-2G248.gif",769,852);
$z[7][4]['name']="litpic";

?>