{dede:field name='keywords'}绝世天劫/世界末日迅雷下载，免{/dede:field}
{dede:field name='description'}绝世天劫/世界末日迅雷下载、免费下载，绝世天劫/世界末日Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}绝世天劫/世界末日{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2008-12-20{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://eee4.com:8113@vip20.eee4.com:8113/[3E迅雷电影站www.eee4.com]绝世天劫DVD中英双字CD1.rmvb" target=_blank>ftftp://eee4.com:8113@vip20.eee4.com:8113/[3E迅雷电影站www.eee4.com]绝世天劫DVD中英双字CD1.rmvb</A></TD></TR></TBODY></TABLE>CD2：<BR>
<TABLE style="BORDER-RIGHT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; BORDER-BOTTOM: #cccccc 1px dotted" cellSpacing=0 cellPadding=6 width="95%" align=center border=0>
<TBODY>
<TR>
<TD style="WORD-WRAP: break-word" bgColor=#fdfddf><ANCHOR></ANCHOR><A href="ftftp://eee4.com:8113@vip20.eee4.com:8113/[3E迅雷电影站www.eee4.com]绝世天劫DVD中英双字CD2.rmvb" target=_blank>ftftp://eee4.com:8113@vip20.eee4.com:8113/[3E迅雷电影站www.eee4.com]绝世天劫DVD中英双字CD2.rmvb</A></TD></TR></TBODY></TABLE>CD3：<BR>
<TABLE style="BORDER-RIGHT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; BORDER-BOTTOM: #cccccc 1px dotted" cellSpacing=0 cellPadding=6 width="95%" align=center border=0>
<TBODY>
<TR>
<TD style="WORD-WRAP: break-word" bgColor=#fdfddf><ANCHOR></ANCHOR><A href="ftftp://eee4.com:8113@vip20.eee4.com:8113/[3E迅雷电影站www.eee4.com]绝世天劫DVD中英双字CD3.rmvb" target=_blank>ftftp://eee4.com:8113@vip20.eee4.com:8113/[3E迅雷电影站www.eee4.com]绝世天劫DVD中英双字CD3.rmvb</A></TD></TR></TBODY></TABLE></div><ul class="mmlist{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MPU63P-425Y.jpg{/dede:field}
