{dede:field name='keywords'}周慧敏入行25周年演唱会BD1280高{/dede:field}
{dede:field name='description'}周慧敏入行25周年演唱会BD1280高清迅雷下载、免费下载，周慧敏入行25周年演唱会BD1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}周慧敏入行25周年演唱会BD1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-03-13{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://www.hdstar.org/attachments/20120310/20120310111619ff8a74d5b3976aca9ec096aefb836f22.jpg.thumb.jpg" style="width: 650px; height: 432px" /><img alt="" src="http://www.hdstar.org/attachments/20120310/2012031011110206230779729da08ae96bae4b0e0642b0.jpg.thumb.jpg" style="width: 584px; height: 768px" /></p>
<p>
	日期: 2011年3月19~20日<br />
	<br />
	時間: 8:15pm<br />
	<br />
	地點: 香港體育館<br />
	<br />
	<b>简介</b><br />
	<br />
	&nbsp; &nbsp; &nbsp; &nbsp;踏進 2011年，已是周慧敏（ Vivian）入行第 25個年頭，她決定於明年 3月 19及 20日於紅館舉行兩場紀念演唱會慶祝，不過老公倪震事前極力反對，事關 5年前她為演唱會過度勞累，消瘦得只剩 98磅，身形慘變「飛機場」，但她今次仍會全力以赴，希望與 fans永遠記得這個日子。<br />
	<br />
	&nbsp; &nbsp; &nbsp; &nbsp;周慧敏，被称为&ldquo;玉女&rdquo;掌门人，生于香港，籍贯广东中山，是1990年代于香港乐坛当红的女歌手。除了歌唱事业外，周慧敏拍摄过电视剧及电影。<br />
	<br />
	&nbsp; &nbsp; &nbsp; &nbsp;如果你的年龄在25岁上下，你肯定记得那么一张笑脸和一种声音，她曾经集万千宠爱于一身，她也说不定曾经是你杂乱的宿舍床头唯一一张干净的贴画，你肯定知道现在这么多的&ldquo;玉女&rdquo;，都起源于那个名字－－周慧敏（Vivian Chow）。<br />
	<br />
	&nbsp; &nbsp; &nbsp; &nbsp;Vivian佩戴价值约2500万钻饰，穿着低裁裙亮相记者会，十分漂亮。大会安排数十粉丝到场支持偶像，他们将Vivian历年推出过的唱片封套做成相架送给她，讨得Vivian开心不已。<br />
	<br />
	&nbsp; &nbsp; &nbsp; &nbsp;由于Vivian佩戴过千万钻饰，她坦言压力很大。说到她此次个唱以Deep V为主题，问她到时是否真以全Deep V上阵？Vivian说：这个&ldquo;Deep&rdquo;是说和歌迷深情、深入及深交，希望了解她从未示人的另一面。有指她穿着Deep V正好可以配合主题？Vivian不讳言：健康性感都可以接受，总之会做些没做过的事。至于表演嘉宾方面？她说要先卖个关子，她会邀请一些从未在她个唱出现过的人，还有一些对她人生非常重要的人物。问她会否邀请旧情人如刘锡明上台？她指对方不是她的旧情人。至于陈德彰，Vivian坦言：是，但他们已经很少联络。<br />
	<br />
	&nbsp; &nbsp; &nbsp; &nbsp;已有五年没有开唱的Vivian坦言：有点不习惯，倪震也有啰嗦，说为何要再辛苦自己，幸好家人最后也体谅，现在她更有免死金牌，她明明说不想太瘦，但这个月竟瘦了四磅，因此老公也有煮宵夜给她吃。说到她突然开唱，会否怕惹来要她赚钱养家的闲言？Vivian表示：如果是真，她大可以拍广告，这样会更加轻松，她开唱真是为了歌迷，希望可以深情奉献<br />
	<br />
	&nbsp; &nbsp; &nbsp; &nbsp;97年下周慧敏完成大西洋城及拉斯维加斯各一场演唱会后，便正式告别娱乐圈，开始过其平淡的生活。在最近一个调查里显示，网友们最希望看到，最希望可以复出的女艺人，也就是周慧敏。理论上说来，周慧敏的声音实在很普通，而这种声音却和她的容貌刚刚好的搭配，令你不忍去批评，只有去聆听&hellip;&hellip;<br />
	<br />
	&nbsp; &nbsp; &nbsp; &nbsp;2010年9月28日，玉女周慧敏现身上海某活动，虽然与白歆惠、谢安琪等后辈同台，但她依旧是全场的焦点。身穿白色荷叶蛋糕裙的她，宛如仙子下凡，美艳无比。现场她还与爵士歌手劳拉费琪同台献唱开金嗓。<br />
	&nbsp; &nbsp; &nbsp; &nbsp;2011年3月19至20日，周慧敏将踏上香港红馆，2011年是周慧敏入行25周年，将与喜爱她的歌迷见面。<br />
	<br />
	&nbsp; &nbsp; &nbsp; &nbsp;都说自古美人如良将，不许人间见白头。坐在酒店沙发上想着久未谋面的周慧敏会不会已成文艺型欧巴桑，然而人在眼前，44岁的她淡妆、披肩长卷发，眼眸清澈，着白色雪纺及膝连身裙，实在找不到女人四十的熟态。巨星风范犹在，是镁光灯下生活多年的打磨，学不来。当真是，白云还在，青山一角。美人的架子还在，没塌，不由长吁一口气。<br />
	<br />
	&nbsp; &nbsp; &nbsp; &nbsp;如果你的年龄在30岁上下，你肯定记得那么一张笑脸和一种声音，她曾经集万千宠爱于一身，她也说不定曾经是你杂乱的宿舍床头唯一一张干净的贴画，你肯定知道现在这么多的&ldquo;玉女&rdquo;，都起源于那个名字&mdash;&mdash;周慧敏。自从1997年退出娱乐圈后，她一直跟娱乐圈若即若离。这一次，她作为嘉宾出席迪奥2012早春系列的广州大秀。秀前的独家专访安排在酒店套房，见面问候完的她第一句话便是：&ldquo;你可以听广东话，我可以听普通话，我们各自用最熟练的语言交流，如何？&rdquo;这份谦逊和体贴，实在让人无比舒服。<br />
	<br />
	&nbsp; &nbsp; &nbsp; &nbsp;<b>职业修炼&mdash;&mdash;做个兼职艺人</b><br />
	<br />
	&nbsp; &nbsp; &nbsp; &nbsp;&ldquo;刚开始那十年，我几乎每天都在工作，排山倒海，后来我发觉很多东西我都错过了，那时候的状态很崩溃。现在虽然还是艺人的身份，但主要做一些代言或慈善的工作。我现在是个兼职艺人。&rdquo;<br />
	<br />
	&nbsp; &nbsp; &nbsp; &nbsp;在1997年尾，周慧敏淡出娱乐圈，与倪震移民温哥华，此后醉心于画画，写作及美式台球。她曾以一幅《新疆老翁》为名的作品，荣获&ldquo;视艺新纪元奖&rdquo;；其后又凭作品《望过去，看将来》入围首届&ldquo;中国水彩人物画展&rdquo;，而2004年新书《我的猫儿子周慧豹》在香港热卖。周慧敏还是香港美式台球协会会员，曾经代表协会出赛夺取女子组第三名。近年来周慧敏不停参与慈善工作，曾成为宣明会、乐施会、进心会等团体的大使，随宣明会往老挝及刚果作探访，助养了多名贫困国家的小朋友；也随乐施会往云南了解当地助人自助计划后的成果。2006年5月25日到5月27日，周慧敏更以&ldquo;因为爱，所以回来&rdquo;为主题在香港红磡体育馆举行三场演唱会，将演唱会的所有酬劳都捐给香港非牟利兽医诊所。<br />
	<br />
	&nbsp; &nbsp; &nbsp; &nbsp;喜欢周慧敏的人，大多会给她打上&ldquo;玉女&rdquo;甚至是&ldquo;玉女派掌门人&rdquo;的标签，虽然听到赞她美貌，依旧会语带娇嗔：&ldquo;哎哟，我很开心啦。&rdquo;但是在周慧敏看来，&ldquo;玉女&rdquo;这两个字与她完全无关，再次听到也不会激动。&ldquo;这个称号虽然因我而起，但我从来没有把它看得多么重要。它就像是一个MSN或者QQ的一个网名，我从来没有认真对待过，只是多年来我和它一起并存而已。这个称号不会影响我的为人处世。&rdquo; 语气中的那种娇憨，只可能属于天真的人。<br />
	<br />
	　　 &nbsp; &nbsp;<b>个性修炼&mdash;&mdash;不再执著，学会享受</b><br />
	<br />
	&nbsp; &nbsp; &nbsp; &nbsp;&ldquo;我发觉在性格上最大的改变就是不再那么执著、不再用要求自己的准则去要求工作和生活中的伙伴。&rdquo;<br />
	<br />
	&nbsp; &nbsp; &nbsp; &nbsp;在人们心目中，周慧敏是&ldquo;玉女&rdquo;的完美原型，温顺、文雅、安静，需要男人的呵护，正因为综合了这些被视为传统女性美的气质，周慧敏当年备受粉丝追捧，特别是男性粉丝。但其实，真实的周慧敏说，这只是自己相貌给人的错觉，自己从小就独立自主，性格刚强。这种比较执著自我的性格在逐渐退隐之后才慢慢受到周围人、事、物的影响有所改变。今年3月份，周慧敏在淡出许久之后于红馆举行了Deep V.25演唱会，以纪念她入行25周年。整场演唱会的服装出自迪奥，都是设计师亲自为周慧敏挑选的，价值高达200万。此前也只有已故的百变天后梅艳芳有过这般待遇。试装过程中，周慧敏一改以往只要自己挑选服装搭配的做法，尝试着接受造型师的专业意见，效果出乎意料的好。她尤其喜欢当中一套类似内衣外穿搭配短裤的造型，直言如果是以前的自己，肯定不会选择这一套，但因为性情有了转变，所以不再像从前那么执著于自我，反而收到了意想不到的惊喜。<br />
	<br />
	　　 &nbsp; &nbsp;<b>爱情修炼&mdash;&mdash;承担是爱情的信心</b><br />
	<br />
	&nbsp; &nbsp; &nbsp; &nbsp;&ldquo;动摇过，才懂得坚定；失去过，才学会珍惜。一场风波，令我们更了解互相的爱，使我们更体会到彼此的不可分割。试炼成就了信心。&rdquo;<br />
	<br />
	&nbsp; &nbsp; &nbsp; &nbsp;于周慧敏，感情似是敏感问题。其实，关于倪公子种种，往事不堪重提，好似揪准线头一拉，整件华美锦袍便只剩蚤子，所谓爆八卦，大抵如是。一名女子的情史叫人好奇，皆因她是曾经的&ldquo;玉女&rdquo;周慧敏。<br />
	<br />
	&nbsp; &nbsp; &nbsp; &nbsp;对于爱情和婚姻，如今的周慧敏只说了一句话，却让人回味无穷：&ldquo;家庭对我来说很重要，我的工作也要跟家庭平衡之下再做选择。&rdquo;当年，周慧敏选择在事业的巅峰期全身而退，跟着当时还是男友的倪震移民加拿大，无非就是&mdash;&mdash;&ldquo;我想看看正常人的生活是怎么样的&rdquo;。自出道起，她的私生活就被暴露在强光下，浮沉都很醒目，终究是个女人，不过恰巧长得美。女人半生，总有些事不想再提，回避即是言说之一种&mdash;&mdash;过去的就让它过去吧。对她的轻轻避过无端有些敬意，说到底，倘无意言真相，则沉默总好过作伪，留白总好过粉饰。我们终其一生，在纷扰的尘世兜兜转转，寻觅着那么一个人，不过就是为了求得岁月静好，现世安稳。可时间那么长，谁能保证沧海桑田之后，良人依旧如斯。周慧敏自己曾经说过：&ldquo;从当年决定和不按常规行事的倪震谈恋爱，就知道是一场革命了，亦没有失望过。&hellip;&hellip;显微镜下看世界，任谁都难合格。&hellip;&hellip;我没枉费与倪震轰轰烈烈地爱过，永远刻骨铭心，此生无憾。&rdquo;爱情，不过是或如花火般绚烂在当下，或像细水般涓涓长流，而这个选择，我想，周慧敏自己应该知道答案。<br />
	<br />
	&nbsp; &nbsp; &nbsp; 经历了演艺生涯的高调10年，经历了爱情转折的是是非非，转往别处修炼的周慧敏，也别有一番天清气朗。这次的见面，她穿了自己最钟爱的白色，淡然而清净，令人惊动。借一个《红楼梦》里宝玉的说法，她这样的人都不配穿白色，谁配？<br />
	<br />
	<b>TrackList:</b><br />
	<br />
	01. 红河村OPENING<br />
	02. 天荒爱未老<br />
	03. 孤单的心痛<br />
	04. 感情的分礼<br />
	05. 流言 (苏永康合唱)<br />
	06. DANCE MEDLEY 1: 坏女孩 / 跳舞街 / 对你爱不完 / 自作心情<br />
	07. 此情只待追忆 (张敬轩合唱)<br />
	08. 秋樱<br />
	09. 再见我的爱人<br />
	10. 红叶落索的时候<br />
	11. 爱得太迟 (古巨基合唱)<br />
	12. DANCE MEDLEY 2: 假装 / 自动自觉 / 诅咒 / 借歪<br />
	13. C&#39;EST LA VIE<br />
	14. 情迷<br />
	15. 不要惊动爱情 (郑秀文合唱)<br />
	16. CLASSIC LOVE MEDLEY: 岁月的童话 / 爱你多过爱他 / 钢线之舞<br />
	17. 盆栽<br />
	18. 台下女主角<br />
	19. 美少女战士<br />
	20. 最爱 (柏原芳惠合唱)<br />
	21. 如果你知我苦衷<br />
	22. 留恋<br />
	23. 最爱<br />
	24. 为你<br />
	25. 天荒爱未老<br />
	BONUS TRACK:<br />
	26. 万千宠爱在一身 (李克勤合唱)<br />
	27. 流言 (张敬轩合唱)<br />
	28. 最爱 (柏原芳惠主唱/周慧敏伴奏<br />
	29. 尽管是春天 (柏原芳惠合唱)</p>
<p>
	<img alt="" src="http://thumbnails34.imagebam.com/17901/a6482b179009297.jpg" style="width: 350px; height: 197px" /><img alt="" src="http://thumbnails45.imagebam.com/17901/069768179009305.jpg" style="width: 350px; height: 197px" /><img alt="" src="http://thumbnails45.imagebam.com/17901/1b385c179009316.jpg" style="width: 350px; height: 197px" /><img alt="" src="http://thumbnails31.imagebam.com/17901/077c29179009332.jpg" style="width: 350px; height: 197px" /><img alt="" src="http://thumbnails31.imagebam.com/17901/47495a179009345.jpg" style="width: 350px; height: 197px" /><img alt="" src="http://thumbnails65.imagebam.com/17901/306ebe179009352.jpg" style="width: 350px; height: 197px" /><img alt="" src="http://thumbnails66.imagebam.com/17901/dcfa85179009356.jpg" style="width: 350px; height: 197px" /><img alt="" src="http://thumbnails28.imagebam.com/17901/7bf6bc179009365.jpg" style="width: 350px; height: 197px" /><br />
	&nbsp;</p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="&#13;&#10;ftp://dy125:piaohua@dy125.piaohua.com:7720/飘花电影piaohua.com周慧敏入行25周年演唱会BD1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:7720/飘花电影piaohua.com周慧敏入行25周年演唱会BD1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1D0210-12Q9.jpg{/dede:field}
