{dede:field name='keywords'}赏金猎人[于正版]国产剧2012热播{/dede:field}
{dede:field name='description'}赏金猎人[于正版]国产剧2012热播剧24【完】迅雷下载、免费下载，赏金猎人[于正版]国产剧2012热播剧24【完】Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}赏金猎人[于正版]国产剧2012热播剧24【完】{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-22{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://apollo.s.dpool.sina.com.cn/nd/dataent/tvpic/pics/117/tvpic_3fb907ae91e18a043234cc14fc6e33f2.jpg" /></p>
<p>
	<img alt="" src="http://apollo.s.dpool.sina.com.cn/nd/dataent/tvpic/pics/117/tvpic_9ce23adcb4f1c6938dd13fa2a3a4be4d.jpg" /></p>
<p>
	<img src="http://img.funshion.com/attachment/new_images/2012/02-22/22849942_1329897923_253.jpg" style="width: 600px; height: 308px" /></p>
<p>
	片　　名：<a href="http://www.bluemv.com/movie/19241.html">赏金猎人</a><br />
	地　　区：中国<br />
	年　　代：2012<br />
	导&nbsp;&nbsp;&nbsp; 演：成麟<br />
	&bull;演员：<br />
	钱泳辰 / 李易峰 / 江铠同 / 颖儿 / 薛佳凝 / 邵美琪 / 刘雪华 / 谭耀文 / 潘虹</p>
<p>
	&bull;类型：悬疑 / 爱情 / 古装</p>
<p>
	&bull;首映：2012年3月21日 中国</p>
<p>
	&bull;点评： 芒果打造&ldquo;最炫于正风&rdquo;,钱泳辰&quot;凹造型&quot;化身清装柯南--</p>
<p>
	&bull;剧情： 清朝末年，江南小镇的富商白老爷被人杀死，酿成地方大案。赏金猎人安聘远受命前往白沙镇侦破疑案，他慢慢发现白老爷是因为知道一个秘密而死的。白家的四位夫人、日本人、土匪纷纷浮出水面，都为这个秘密费尽心机。随着案情逐渐水落石出，安聘远发现原来自己父亲和白老爷之死，都是因为一张金矿地图。十三年前，日本青龙会出钱请父亲勘探地质，不料发现了大型金矿；安聘远父亲不愿把金矿图纸交出而惨遭毒手；白老爷亦是被日本青龙会的势力所害。安聘远凭借着聪慧勇敢，拨开重重迷雾，终于查出幕后的凶手，得到了金矿地图。面对日本人的威胁，安聘远把地图扔到火里，他坚信，只要这座金矿还在中国的大地上，迟早有一天我们的后代会找到它，它永远属于中国。</p>
<p>
	<br />
	&bull; 花絮： 古装巨制魔幻大戏《赏金猎人》近日首次在网上公布了片花。这是金牌编剧、制作人于正推出首部&ldquo;男人戏&rdquo;。摆脱了上《千山暮雪》中&ldquo;虐恋&rdquo;情节的颖儿在《赏金猎人》中依然难逃坎坷命运，除了与&ldquo;赏金猎人&rdquo;有一段相爱却不能相守的纯纯初恋外，更是被一段豪门阴谋所牵连，被逼至疯甚至险些丧命，颖儿也被称为&ldquo;虐恋剧专业户&rdquo;。<br />
	　　在《赏金猎人》中颖儿饰演的雨涵本是单纯善良的女孩，与青梅竹马的安聘远有一段清纯美好的感情，二人共同期许要给彼此一个美好的未来。可是，恋情遭到家庭的反对。痛失初恋的雨涵被迫嫁到白府，哪知新婚之夜丈夫却被杀害。雨涵被作为第一个被怀疑对象，遭到所有人的质疑和迫害，雨涵因受到巨大刺激，神经错乱变得疯癫。家族里的长辈却认为她在装疯，动用酷刑逼她招供，杖责、夹手指等各种酷刑都被用在雨涵的身上。<br />
	　　颖儿在《赏金猎人》中的虐恋情节比《千山暮雪》还严重，除了心理上受尽折磨外，身体上更是受尽了各种虐刑。颖儿坦言：&ldquo;《赏金猎人》是精神和身体极度受虐的戏，整个拍下来觉得人都要崩溃了。尤其上刑具的时候为了效果真实会或多或少的伤到身体，感觉像是真的受虐。&rdquo;当问及为何总是拍摄这种角色，颖儿开玩笑道：也许自己长的比较受欺负吧。导演总是让我演受虐的戏，而我自己也觉得演这种极端走向的角色会比较过瘾。</p>
<p>
	看点一：<br />
	清末版&ldquo;深宅谍影&rdquo; 钱泳辰变身柯南<br />
	同样是湖南卫视播出的《深宫谍影》(观剧)曾经掀起了一股古装探案热。在《赏金猎人》中，也不谋而合地上演了清末版&ldquo;深宅谍影&rdquo;。在首播当天的内容中，钱泳辰饰演的男一号安聘远因为为皇宫破案有功，被老佛爷钦封为&ldquo;赏金猎人&rdquo;，并被朝廷派往调查白家老爷离奇死亡一案，从而展开了江南深宅内外围绕一段藏宝传说而掀起的血雨腥风。<br />
	安聘远抽丝剥茧艰难调查，案情却越发纠缠&mdash;&mdash;白家大房和二房两对母子明争暗斗；三夫人与大少爷旧情复燃；昔日情人雨涵被逼发疯。每一个线索都会在他查访之前被掐断：而父亲的古琴竟在小镇上离奇出现，牵出了十三年前的一桩凶案，带来了这个伴随着血腥的秘密。然而，分别掌握着秘密关键的四个夫人都不肯将自己知道的诗句说出来，而知情人一个个被害，案情陷入了一个又一个的谜团中。</p>
<p>
	看点二：<br />
	琼女郎VS湘女郎VS于女郎 同剧对垒<br />
	除了剧情的别具看点，于正剧向来最核心的优势&mdash;&mdash;艺人搭配在《赏金猎人》中也得到淋漓尽致的体现。&ldquo;琼女郎&rdquo;刘雪华、&ldquo;湘女郎&rdquo;江铠同、&ldquo;于女郎&rdquo;颖儿、舒畅的纷纭登场，同剧对垒，也让这部清末探案大戏变得乱花迷人眼，养眼十足。<br />
	在《赏金猎人中》，舒畅出演的神秘女贼出场即与钱泳辰有一段旖旎接触。大清玉玺被盗，安聘远根据玉玺盒子上特殊的香味找到了女贼，准备押送其回宫复命，孰料女贼人骗至悬崖逃遁而去，留下疑云重重；新晋于女郎颖儿剧中饰演延续《千山暮雪》虐心戏码，大胆挑战演技。新婚首夜白老爷暴死洞房，刚成为四姨太的雨涵被指杀人凶手，前来负责查案的安聘远竟是自己青梅竹马的恋人&hellip;&hellip;遭遇指控的雨涵濒临崩溃，而协助安聘远查案的知县之女洛琴心（江铠同 饰）步步紧逼，希望找出真凶。面对与捕快毓泰（李易峰 饰）婚期渐近，在调查案件的过程中，洛琴心却逐渐爱上了风流倜傥的安聘远，两人关系也发送微妙变化。而&ldquo;琼女郎&rdquo;刘雪华此番剧中出演白家大夫人角色，与众多青年演员均有不少对手戏，女当家的气场范儿十足。</p>
<p>
	看点三：<br />
	华美制作打造荧屏&ldquo;最炫于正风&rdquo;<br />
	《赏金猎人》不可不提的一大特质就是其精致的制作，色彩极尽绚丽，画面极尽唯美，场景极尽浪漫，无处不散发出浓浓的于正个人风格。四季不谢的桃花成为当红不让的主角。慈禧宫中遇刺，一阵狂风刮来无数落英缤纷；安聘远夜出擒贼，女贼却在一片桃花林中安然沐浴，两人在月下花海中打斗，白练似雪，剑光如影，浓墨重彩的画面宛若电影质感。此外，《赏金猎人》也大胆突破于正固有风格，漫画感十足，势必为观众带来更多惊喜和视觉上的愉悦体验</p>
<p>
	&nbsp;</p>
<p>
	<img src="http://img.funshion.com/attachment/new_images/2012/02-22/22849942_1329897926_770.jpg" /></p>
<p>
	<img src="http://img.funshion.com/attachment/new_images/2012/02-22/22849942_1329897916_332.jpg" /></p>
<p>
	<img src="http://img.funshion.com/attachment/new_images/2012/02-22/22849942_1329897917_163.jpg" /></p>
<p>
	<img src="http://img.funshion.com/attachment/new_images/2012/02-22/22849942_1329897920_925.jpg" /></p>
<p>
	<img src="http://img.funshion.com/attachment/new_images/2012/02-22/22849942_1329897928_445.jpg" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.netftp//dy44:piaohua@dy44.piaohua.com:3142/" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3384/飘花电影piaohua.com赏金猎人01.HDTV.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3384/飘花电影piaohua.com赏金猎人01.HDTV.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3384/飘花电影piaohua.com赏金猎人02.HDTV.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3384/飘花电影piaohua.com赏金猎人02.HDTV.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3384/飘花电影piaohua.com赏金猎人03.HDTV.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3384/飘花电影piaohua.com赏金猎人03.HDTV.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3384/飘花电影piaohua.com赏金猎人04.HDTV.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3384/飘花电影piaohua.com赏金猎人04.HDTV.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3388/飘花电影piaohua.com赏金猎人05.HDTV.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3388/飘花电影piaohua.com赏金猎人05.HDTV.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3388/飘花电影piaohua.com赏金猎人06.HDTV.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3388/飘花电影piaohua.com赏金猎人06.HDTV.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3407/飘花电影piaohua.com赏金猎人07.HDTV.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3407/飘花电影piaohua.com赏金猎人07.HDTV.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3407/飘花电影piaohua.com赏金猎人08.HDTV.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3407/飘花电影piaohua.com赏金猎人08.HDTV.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3412/飘花电影piaohua.com赏金猎人09.HDTV.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3412/飘花电影piaohua.com赏金猎人09.HDTV.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3412/飘花电影piaohua.com赏金猎人10.HDTV.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3412/飘花电影piaohua.com赏金猎人10.HDTV.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3425/飘花电影piaohua.com赏金猎人11.HDTV.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3425/飘花电影piaohua.com赏金猎人11.HDTV.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3425/飘花电影piaohua.com赏金猎人12.HDTV.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3425/飘花电影piaohua.com赏金猎人12.HDTV.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3431/飘花电影piaohua.com赏金猎人13.HDTV.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3431/飘花电影piaohua.com赏金猎人13.HDTV.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3431/飘花电影piaohua.com赏金猎人14.HDTV.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3431/飘花电影piaohua.com赏金猎人14.HDTV.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3438/飘花电影piaohua.com赏金猎人15.HDTV.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3438/飘花电影piaohua.com赏金猎人15.HDTV.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3438/飘花电影piaohua.com赏金猎人16.HDTV.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3438/飘花电影piaohua.com赏金猎人16.HDTV.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3449/飘花电影piaohua.com赏金猎人17.HDTV.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3449/飘花电影piaohua.com赏金猎人17.HDTV.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3449/飘花电影piaohua.com赏金猎人18.HDTV.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3449/飘花电影piaohua.com赏金猎人18.HDTV.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3460/飘花电影piaohua.com赏金猎人19.HDTV.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3460/飘花电影piaohua.com赏金猎人19.HDTV.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3460/飘花电影piaohua.com赏金猎人20.HDTV.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3460/飘花电影piaohua.com赏金猎人20.HDTV.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3468/飘花电影piaohua.com赏金猎人21.HDTV.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3468/飘花电影piaohua.com赏金猎人21.HDTV.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3468/飘花电影piaohua.com赏金猎人22.HDTV.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3468/飘花电影piaohua.com赏金猎人22.HDTV.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3468/飘花电影piaohua.com赏金猎人23.HDTV.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3468/飘花电影piaohua.com赏金猎人23.HDTV.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3468/飘花电影piaohua.com赏金猎人24.HDTV.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3468/飘花电影piaohua.com赏金猎人24.HDTV.rmvb</a></td>
		</tr>
	</tbody>
</table>
<p>
	&nbsp;</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1ABX0-45300.jpg{/dede:field}
