<?php
$z[0]=Array("field","卓依婷《丰收年》2011贺岁专辑MV",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","卓依婷《丰收年》2011贺岁专辑MV迅雷下载、免费下载，卓依婷《丰收年》2011贺岁专辑MVGvod高清在线播放，剧情介绍等。",73,227);
$z[1][4]['name']="description";
$z[2]=Array("field","卓依婷《丰收年》2011贺岁专辑MV",229,297);
$z[2][4]['name']="title";
$z[3]=Array("field","",299,338);
$z[3][4]['name']="writer";
$z[4]=Array("field","",340,379);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-01-01",381,431);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",433,470);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://4e:4e@d8.3edyy.com:208/【3E看看www.3ekk.com】卓依婷《丰收年》.rmvb\" target=_blank>ftftp://4e:4e@d8.3edyy.com:208/【3E看看www.3ekk.com】卓依婷《丰收年》.rmvb</A></TD></TR></TBODY></TABLE></div><ul class=\"mmlist",472,726);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MQ453N0-34a1.jpg",728,810);
$z[8][4]['name']="litpic";

?>