{dede:field name='keywords'}风之谷BD1280国粤日三语中字迅雷{/dede:field}
{dede:field name='description'}风之谷BD1280国粤日三语中字迅雷下载、免费下载，风之谷BD1280国粤日三语中字Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}风之谷BD1280国粤日三语中字{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-15{/dede:field}
{dede:field name='body'}<p>
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('/uploads/allimg/c120525/133O10149110-19D58.jpg');" src="/uploads/allimg/c120525/133O10149110-19D58.jpg" /><br />
	<br />
	◎译　　名　风之谷<br />
	◎片　　名　Nausicaa of the Valley of the Winds<br />
	◎年　　代　1984<br />
	◎国　　家　日本<br />
	◎类　　别　动画/冒险/幻想/科幻<br />
	◎语　　言　日语<br />
	◎字　　幕　中字<br />
	◎IMDB评分 8.1/10 (19,675 votes)<br />
	◎文件格式　BD-RMVB<br />
	◎视频尺寸　1024 x 576<br />
	◎文件大小　1CD<br />
	◎片　　长　166 Mins<br />
	◎导　　演　宫崎骏 Hayao Miyazaki<br />
	◎主　　演　岛本须美 Sumi Shimamoto ....Nausica? (voice)<br />
	　　　　　　Mahito Tsujimura ....Jihl (voice)<br />
	　　　　　　京田尚子 Hisako Ky?da ....Oh-Baba (voice)<br />
	　　　　　　松田洋治 Y?ji Matsuda ....Asbel (voice)<br />
	　　　　　　麦人 Mugihito ....Mayor of Pejite (voice)<br />
	　　　　　　榊原良子 Yoshiko Sakakibara ....Kushana (voice)<br />
	　　　　　　裘蒂&middot;班森 Jodi Benson ....Lastelle&#39;s Mother (2004) (voice: English version)<br />
	　　　　　　保罗&middot;布切 Paul Butcher ....Children&#39;s Voices (2004) (voice: English version)<br />
	　　　　　　马克&middot;哈米尔 Mark Hamill ....Mayor of Pejite (2004) (voice: English version)<br />
	　　　　　　布里奇特&middot;霍夫曼 Bridget Hoffman ....Additional Voices (2004)<br />
	　　　　　　希亚&middot;拉博夫 Shia LaBeouf ....Prince Asbel (2004) (voice: English version)<br />
	　　　　　　艾莉森&middot;洛曼 Alison Lohman ....Nausica? (2004) (voice: English version)<br />
	　　　　　　爱德华&middot;詹姆斯&middot;奥莫斯 Edward James Olmos ....Mito (2004) (voice: English version)<br />
	　　　　　　克里斯&middot;萨兰登 Chris Sarandon ....Kurotawa (2004) (voice: English version)<br />
	　　　　　　帕特里克&middot;斯图尔特 Patrick Stewart ....Lord Yupa (voice: English version)<br />
	　　　　　　乌玛&middot;瑟曼 Uma Thurman ....Kushana (2004) (voice: English version)<br />
	　　　　　　弗兰克&middot;维尔克 Frank Welker ....Gol (2004) (voice: English version)<br />
	　　　　　　纳谷悟郎 Gor? Naya ....Yupa (voice)<br />
	　　　　　　永井一郎 Ichir? Nagai ....Mito (voice)<br />
	　　　　　　宫内幸平 K?hei Miyauchi ....Goru (voice)<br />
	　　　　　　八奈见乘儿 J?ji Yanami ....Gikkuri (voice)<br />
	　　　　　　矢田稔 Minoru Yada ....Niga (voice)<br />
	　　　　　　吉田理保子 Rihoko Yoshida ....Teto/Girl C (voice)<br />
	　　　　　　菅谷政子 Masako Sugaya ....Girl A (voice)<br />
	　　　　　　Takako Sasuga ....Girl B (voice)<br />
	　　　　　　坂本千夏 Chika Sakamoto ....Boy A (voice)<br />
	　　　　　　Tarako ....Boy B (voice)<br />
	　　　　　　富永美伊奈 M?na Tominaga ....Rastel (voice)<br />
	　　　　　　Akiko Tsuboi ....Rastel&#39;s mother (voice)<br />
	　　　　　　家弓家正 Iemasa Kayumi ....Kurotowa (voice)<br />
	　　　　　　水鸟铁夫 Tetsuo Mizutori ....Commando (voice)<br />
	　　　　　　Takeki Nakamura ....Pejite citizen (voice)<br />
	　　　　　　Takako ?ta ....Pejite girl (voice)<br />
	　　　　　　岛田敏 Bin Shimada ....Pejite citizen (voice)<br />
	　　　　　　野村信次 Shinji Nomura ....Torumekia soldier (voice)<br />
	　　　　　　Hisako Ayuhara ....Boy (voice)<br />
	　　　　　　大塚芳忠 YoSHEada Otsuka ....Torumekia soldier (voice)<br />
	　　　　　　Newell Alexander ....Additional voices (voice: English version)<br />
	<br />
	　　　　　　<br />
	◎简　　介　<br />
	<br />
	　　1000年后的人们，并不是生活在天堂里，而看上去美丽的景象，其实是危机四伏。在人类自我毁灭的浩劫后，以菌类为主的腐海森林，散发着有毒的气体，逐渐的侵蚀着人类的居住区，而生活在腐海中的王虫群，更是可以在瞬间毁灭辛苦建立起来的新的家园的恐怖生物。疲惫于战争的人群经历了艰难困苦，总算找到个可以暂时安居的地方，那里由于风的力量而没有受到腐海的侵袭，这个美丽的家园就是风之谷。风之谷是个不受腐海波及的地方，人们生活的很快乐，可是有野心的多米吉亚人，不惜发动战争，利用王虫荷母打击风之谷，在一个黑暗艰苦的时期，展开白鸟之翼的娜伍丝嘉，将会面临怎样的危机以及成长，将会怎样对待敌意和战争，最重要的是，背负着族人的期待，面对着疯狂的王虫，纤弱的身躯，是否能够承担起保护自己家园的重任？<br />
	<br />
	　　生存于风之谷的纯真少女娜乌西卡并非从一开始就背负着拯救世界的命运。虽然在电影下载残存的人类中流传有&ldquo;蓝衣的救世主&rdquo;&mdash;&mdash;使徒（ANGEL）将出现的预言，但每一个力图救世的强者最终都沦为破坏与绝望的奴隶。他们或曾是&ldquo;英明神圣的君主&rdquo;或曾是&ldquo;人民的领袖&rdquo;，但最终为自己所期待的强大力量扭曲，成为疯狂杀戮的机器。每一次对王虫的战争都以人类的惨败而告终&hellip;&hellip;<br />
	　　<br />
	　　当这世界全部的&ldquo;希望&rdquo;都只寄托在一个人的身上时，那么无论这个人是天使还是恶魔都无关紧要，因为这世界已陷入无底的深渊，再无其它可称之为&ldquo;希望&rdquo;的东西了。<br />
	　　<br />
	　　娜乌西卡是天使。她是希望的代表及化身，善于&ldquo;用心捕捉心灵的歌声&rdquo;，在人类与虫族之间架起&ldquo;心&rdquo;的桥梁。也是她发现了腐海的秘密：菌类森林并不是有毒物质的来源，相反是在净化土壤和空气中的有毒成分，使之结晶化为无毒无机尘粒。长久以来，王虫正是森林的守护者，一边与森林共同生存，一边阻止无知的人类破坏森林的净化程序，因而被人类视为天敌，誓不两立&hellip;&hellip;<br />
	　　<br />
	　　在&ldquo;虫&rdquo; 的新生世界中，人类是如此软弱与无助，科学或技巧都只会使人类的仇视与斯杀继续升级。娜乌西卡要怎样才能救人类呢？这里的答案是：只有依凭&ldquo;心&rdquo;的力量，尊重生命的价值，顺应自然的出路，人类才能得以与虫的世界共存&hellip;&hellip;<br />
	　　<br />
	　　电影版《风之谷》是日本动画巨匠宫崎骏先生的成名作，1984年全日本公映时引起轰动，剧中独特的世界观以及人性价值观深刻地影响了其后十余年日本动画的走向，女主角娜乌西卡更是连续十年占据历代动画片最佳人气角色排行榜冠军之位，选票通常超过第二名四五倍之多&mdash;&mdash;第二名分别曾为《蓝宝石之迷》的女主角娜迪娅以及《城市猎人》中的寒羽良等。宫崎骏也因此片而奠定了他在全球动画界无可替代的地位，迪斯尼将他尊称为动画界的黑泽明。<br />
	　　<br />
	　　84年的动画《风之谷》说到这里的确可以告一段落了，然而同时作为漫画家的宫崎骏并未就此停手，漫画版的《风之谷》在德间书店动画情报志《Animage》月刊上，从79年开始连载，历时13年，中间虽然中断了两年，但一直坚持到了94年底，终告完结。漫画版《风之谷》到底有什么不同呢？<br />
	　　<br />
	　　娜乌西卡是恶魔！事情原本应该是这样的：在&ldquo;火之七日&rdquo;之后，最后的科学者看到这世界已经无法在短时间内恢复其自然的状态，于是他们为这世界设计了一个长达数年的净化程序。<br />
	　　<br />
	　　虫类，人造生物，森林的守护者，以虫粮树为食，可以在有毒瘴气中生存，约在一千年内进化出位于其顶点的&ldquo;王虫&rdquo;，一种&ldquo;个体即群体&rdquo;智慧无限积累的种族，血液为蓝色。<br />
	　　<br />
	　　菌类，人造生物，净化者。在森林的最深处，是已净化了沉寂世界，菌类、虫类均不能生存在如此纯净的世界中。<br />
	　　<br />
	　　现存人类及动物，已接受生体改造之后裔，对&ldquo;毒&rdquo;有一定的适应能力，但也绝对不能在纯净的世界中生存，否则便会因这太过纯净的空气，肺底出血而死。<br />
	　　<br />
	　　陵墓主人，完整保存有地区原自然生存系统、原科技及艺术的基地，这世界全部被净化之后，神的乐园将再次降临在这一尘不染的洁净世界，从陵墓中孵化出新的人类，学习那些被保存下来的人类文化的精华，成为更优秀更完美的神的子民！<br />
	　　<br />
	　　然而娜乌西卡毁了这一切！她和一个尚未成熟的巨神兵奥玛来到这里，用死亡光线劈开了陵墓，所有的一切全被她淹没在蓝色的血液中！她说要救人类。几百年前有个少年，他听到世界的真相时，也说要救人类，他还带走了陵墓中的技术和不死的战士席得拉。几十年后，他成为那个&ldquo;神圣皇帝&rdquo;，世界在他的统治下更陷入了杀戮的地狱&hellip;&hellip;<br />
	　　<br />
	　　他无法战胜自己的&ldquo;心&rdquo;而被&ldquo;力量&rdquo;所吞噬。<br />
	　　<br />
	　　这就是人类，几百年来不断只是重复着着一切愚蠢的轮回！什么也不能改变他们注定灭亡的命运。<br />
	　　<br />
	　　娜乌西卡说不！她说生命自然有其出路，不需要靠设计好的程序来决定其命运。她摧毁了陵墓，对幸存的人们说&ldquo;恶&rdquo;的根源已经铲除，人民从此可以过幸福快乐的日子。那么就欺骗他们吧，直到他们发现这世界原已注定将他们抛弃，回归那令人喷血不止的纯净！<br />
	　　<br />
	　　漫画的《风之谷》并没有展现千年后的那纯净世界到底将会怎样。&ldquo;生命自有其出路&rdquo;，但在以百万年为单位的自然进化历程中，只有几千年时间的人类将如何面对这样残酷的进化呢？所有科技都已丢失，&ldquo;心&rdquo;的力量能否帮助人类渡过厄运？<br />
	　　<br />
	　　&ldquo;无论是多痛苦，一定要活下去&hellip;&hellip;&rdquo;<br />
	<br />
	一句话评论<br />
	<br />
	A band of young warriors on the wings of their greatest challenge! (USA 1986 &quot;Warriors of the Wind&quot;)<br />
	<br />
	幕后制作<br />
	<br />
	　　本片根据宫崎骏自己的同名漫画改编，是动画大师宫崎骏的成名之作。在本片中宫崎骏挥洒想象力构筑出一个神奇的幻想世界，各种奇异的生物以及机械都体现出不俗的匠心。影片的主角是一位纤弱善良的少女，面对侵略，她勇敢地背负起拯救家乡的使命。这位主人公处于人类各种势力以及人与自然这两层关系的核心，于是，她的冒险就成了影响整个世界未来的关键。宫崎骏在本片中展露出对大自然的关怀和对人类技术负面影响力的忧虑，这一主题在他以后的作品中反复再现。影片入选1984年电影旬报年度十佳影片榜。</p>
<p>
	【电影截图】：<br />
	<br />
	<img onclick="if(this.width&gt;screen.width-461) window.open('http://photo6.zxip.com/albums6/folder18/14186/20100701105143/20107211045542906.jpg');" src="/uploads/allimg/c120525/133O10150420-2062a.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 640px; height: 360px; border-top: 0px solid; border-right: 0px solid" />&nbsp;<br />
	<img onclick="if(this.width&gt;screen.width-461) window.open('http://photo6.zxip.com/albums6/folder18/14186/20100701105143/2010721104555880.jpg');" src="/uploads/allimg/c120525/133O10151030-215Y0.jpg" style="border-bottom: 0px solid; border-left: 0px solid; border-top: 0px solid; border-right: 0px solid" />&nbsp;<br />
	<img onclick="if(this.width&gt;screen.width-461) window.open('http://photo6.zxip.com/albums6/folder18/14186/20100701105143/20107211045554997.jpg');" src="/uploads/allimg/c120525/133O10151630-221250.jpg" style="border-bottom: 0px solid; border-left: 0px solid; border-top: 0px solid; border-right: 0px solid" /></p>
<br />
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="/uploads/allimg/c120525/133O0T31310-42214.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：http://www.xiaozhizhu.net</td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy241:piaohua@117.41.229.29:2020/飘花电影piaohua.com风之谷BD1280国粤日三语中字.mkv</td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				3e:3e@d8.3edyy.com:168/【3E电影院www.eee4.cc】风之谷BD中字1024x576高清版.rmvb</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O10152330-23F16.jpg{/dede:field}
