{dede:field name='keywords'}生化大蜘蛛迅雷下载，免费下载，{/dede:field}
{dede:field name='description'}生化大蜘蛛迅雷下载、免费下载，生化大蜘蛛Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}生化大蜘蛛{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2007-01-03{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://222.171.15.68:44588/最新电影/欧美专区/01.25生化大蜘蛛/01.rmvb" target="_blank{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MPSRP-3b41.jpg{/dede:field}
