{dede:field name='keywords'}噬血地道(城市探险者)DVD中字201{/dede:field}
{dede:field name='description'}噬血地道(城市探险者)DVD中字2011最新德国恐怖惊悚大片迅雷下载、免费下载，噬血地道(城市探险者)DVD中字2011最新德国恐怖惊悚大片Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}噬血地道(城市探险者)DVD中字2011最新德国恐怖惊悚大片{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-21{/dede:field}
{dede:field name='body'}<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120322/21/56643687201203222111561079588883357_005.jpg" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120322/21/56643687201203222111561079588883357_007.jpg" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120322/21/56643687201203222111561079588883357_006.jpg" /></p>
<p>
	◎译　　名　噬血地道/城市探险者<br />
	◎片　　名　Urban Explorer<br />
	◎年　　代　2011<br />
	◎国　　家　德国<br />
	◎类　　别　恐怖/惊悚<br />
	◎语　　言　英语<br />
	◎字　　幕　中文<br />
	◎IMDB评分 5.1/10(188 votes)<br />
	◎IMDB链接：<a href="http://www.bluemv.com" title="电影下载">http://www.bluemv.com</a><br />
	◎文件格式　DVD-RMVB<br />
	◎视频尺寸　672x288<br />
	◎文件大小　1CD 477MB<br />
	◎片　　长　01:34:50<br />
	◎导　　演　Andy Fetscher<br />
	◎主　　演　纳塔莉&middot;凯利 Nathalie Kelly ....Lucia<br />
	　　　　　　Brenda Koo ....Juna<br />
	　　　　　　马克思&middot;雷迈特 Max Riemelt ....Kris<br />
	　　　　　　Andreas Wisniewski ....Neo-Nazi<br />
	　　　　　　Nick Eversman ....Denis<br />
	　　　　　　Catherine de L&eacute;an ....Marie<br />
	　　　　　　Klaus Stiglmeier ....Armin<br />
	　　　　　　Johannes Klau?ner ....Man in the subway<br />
	　　　　　　Adolfo Assor ....Man in the subway station<br />
	　　　　　　Kai Michael Wolter ....Slimy Guy</p>
<p>
	◎简　　介</p>
<p>
	据说在现代的柏林城市地下有个神秘的地下世界，一群来自世界各地的人前来探险，结果发生了各种奇异的事件&hellip;&hellip;</p>
<p>
	<br />
	◎影片截图</p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120322/21/56643687201203222111561079588883357_002.jpg" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120322/21/56643687201203222111561079588883357_004.jpg" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120322/21/56643687201203222111561079588883357_001.jpg" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120322/21/56643687201203222111561079588883357_000.jpg" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120322/21/56643687201203222111561079588883357_003.jpg" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3057/飘花电影piaohua.com噬血地道(城市探险者)DVD中字.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3057/飘花电影piaohua.com噬血地道(城市探险者)DVD中字.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3057/飘花电影piaohua.com噬血地道(城市探险者)DVD中字.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15123960-1JN.jpg{/dede:field}
