{dede:field name='keywords'}绿色贝雷帽/绿色贝蕾帽[BD中英双{/dede:field}
{dede:field name='description'}绿色贝雷帽/绿色贝蕾帽[BD中英双字1280x720高清版]迅雷下载、免费下载，绿色贝雷帽/绿色贝蕾帽[BD中英双字1280x720高清版]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}绿色贝雷帽/绿色贝蕾帽[BD中英双字1280x720高清版]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2010-01-14{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://4e:4e@www2.3edyy.com:3848/【3E电影院www.3edyy.com】绿色贝雷帽BD中英双字1280x720高清版.rmvb" target=_blank>ftftp://4e:4e@www2.3edyy.com:3848/【3E电影院www.3edyy.com】绿色贝雷帽BD中英双字1280x720高清版.rmvb</A></TD></TR></TBODY></TABLE></div><ul class="mmlist{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MQ332L0-31947.jpg{/dede:field}
