{dede:field name='keywords'}X档案2：我要相信BD中英双字1024{/dede:field}
{dede:field name='description'}X档案2：我要相信BD中英双字1024/1280高清迅雷下载、免费下载，X档案2：我要相信BD中英双字1024/1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}X档案2：我要相信BD中英双字1024/1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-12-12{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://e64:e64@xl3.eee4.com:1004/[3E电影站www.eee4.com]X档案：我要相信CD1.rmvb" target="_blank{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MOT44F-21010.jpg{/dede:field}
