<?php
$z[0]=Array("field","X档案2：我要相信BD中英双字1024",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","X档案2：我要相信BD中英双字1024/1280高清迅雷下载、免费下载，X档案2：我要相信BD中英双字1024/1280高清Gvod高清在线播放，剧情介绍等。",73,245);
$z[1][4]['name']="description";
$z[2]=Array("field","X档案2：我要相信BD中英双字1024/1280高清",247,324);
$z[2][4]['name']="title";
$z[3]=Array("field","",326,365);
$z[3][4]['name']="writer";
$z[4]=Array("field","",367,406);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-12-12",408,458);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",460,497);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://e64:e64@xl3.eee4.com:1004/[3E电影站www.eee4.com]X档案：我要相信CD1.rmvb\" target=\"_blank",499,631);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MOT44F-21010.jpg",633,715);
$z[8][4]['name']="litpic";

?>