{dede:field name='keywords'}罗宾汉/诺丁汉/侠盗·骄雄[BD中{/dede:field}
{dede:field name='description'}罗宾汉/诺丁汉/侠盗·骄雄[BD中英双字1024x576高清版]迅雷下载、免费下载，罗宾汉/诺丁汉/侠盗·骄雄[BD中英双字1024x576高清版]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}罗宾汉/诺丁汉/侠盗·骄雄[BD中英双字1024x576高清版]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2010-09-08{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://3e:3e@d8.3edyy.com:180/【3E电影院www.eee4.cc】罗宾汉DVD中字.rmvb" target=_blank>ftftp://3e:3e@d8.3edyy.com:180/【3E电影院www.eee4.cc】罗宾汉DVD中字.rmvb</A></TD></TR></TBODY></TABLE><BR><FONT color=#ff0000 size=2><STRONG>[下载地址]：<IMG border=0 src="httftp://www.eee4.cc/templets/img/down.jpg{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MP640D0-29422.jpg{/dede:field}
