<?php
$z[0]=Array("field","罗宾汉/诺丁汉/侠盗·骄雄[BD中",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","罗宾汉/诺丁汉/侠盗·骄雄[BD中英双字1024x576高清版]迅雷下载、免费下载，罗宾汉/诺丁汉/侠盗·骄雄[BD中英双字1024x576高清版]Gvod高清在线播放，剧情介绍等。",72,266);
$z[1][4]['name']="description";
$z[2]=Array("field","罗宾汉/诺丁汉/侠盗·骄雄[BD中英双字1024x576高清版]",268,356);
$z[2][4]['name']="title";
$z[3]=Array("field","",358,397);
$z[3][4]['name']="writer";
$z[4]=Array("field","",399,438);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-09-08",440,490);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",492,529);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://3e:3e@d8.3edyy.com:180/【3E电影院www.eee4.cc】罗宾汉DVD中字.rmvb\" target=_blank>ftftp://3e:3e@d8.3edyy.com:180/【3E电影院www.eee4.cc】罗宾汉DVD中字.rmvb</A></TD></TR></TBODY></TABLE><BR><FONT color=#ff0000 size=2><STRONG>[下载地址]：<IMG border=0 src=\"httftp://www.eee4.cc/templets/img/down.jpg",531,870);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MP640D0-29422.jpg",872,955);
$z[8][4]['name']="litpic";

?>