{dede:field name='keywords'}冰与火之歌：权力的游戏第二季美{/dede:field}
{dede:field name='description'}冰与火之歌：权力的游戏第二季美剧8迅雷下载、免费下载，冰与火之歌：权力的游戏第二季美剧8Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}冰与火之歌：权力的游戏第二季美剧8{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-23{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://gb.cri.cn/mmsource/images/2012/03/22/eb1203220053.jpg" style="width: 600px; height: 887px" /></p>
<p>
	中文片名: 冰与火之歌：权力的游戏 第二季<br />
	英文片名: Game of Thrones Season 2<br />
	剧集分类: 动作<br />
	影片类型: 美剧<br />
	上影时间: 2012<br />
	导　演: Thomas McCarthy<br />
	主　演: 奇&middot;哈林顿 Kit Harington ...Jon Snow<br />
	彼特&middot;丁拉基 Peter Dinklage ...Tyrion Lannister<br />
	琳娜&middot;海蒂 Lena Headey ... Cersei Lannister<br />
	尼可拉&middot;科斯特-瓦尔道 Nikolaj Coster-Waldau ...Jaime Lannister<br />
	哈里&middot;劳埃德 Harry Lloyd ....Viserys Targaryen<br />
	介绍:<br />
	&quot;The cold winds are rising&quot;.&mdash;&mdash;寒风渐起...</p>
<p>
	备受关注的HBO史诗大作《冰与火之歌：权力的游戏》[/url]（Game of Thrones）第一季大获成功之后，关于第二季回归时间的讨论不绝于耳，今天在美国电视评论家协会（TCA）冬季媒体见面会上，这一谜题终于揭开，HBO官方宣布该剧第二季将于当地时间2012年4月1日回归。</p>
<p>
	<br />
	据悉，《冰火》第2季的实景拍摄工作已经全部完成。140天，3个国家，诸多外景地&hellip;&hellip;10个小时的故事盈满了电视制作人们的心血。时下正是音效、视效、配乐等后期制作团队忙碌的日子。</p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.net/" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3119/飘花电影piaohua.com冰与火之歌：权力的游戏.第二季.人物篇.丹妮莉丝·坦格利安1280高清.mkv">ftp://dy44:piaohua@dy44.piaohua.com:3119/飘花电影piaohua.com冰与火之歌：权力的游戏.第二季.人物篇.丹妮莉丝&middot;坦格利安1280高清.mkv</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3119/飘花电影piaohua.com冰与火之歌：权力的游戏.第二季.人物篇.乔佛里·拜拉席恩1280高清V2.mkv ">ftp://dy44:piaohua@dy44.piaohua.com:3119/飘花电影piaohua.com冰与火之歌：权力的游戏.第二季.人物篇.乔佛里&middot;拜拉席恩1280高清V2.mkv </a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3119/飘花电影piaohua.com冰与火之歌：权力的游戏.第二季.人物篇.琼恩·雪诺1280高清.mkv">ftp://dy44:piaohua@dy44.piaohua.com:3119/飘花电影piaohua.com冰与火之歌：权力的游戏.第二季.人物篇.琼恩&middot;雪诺1280高清.mkv</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3119/飘花电影piaohua.com冰冰与火之歌：权力的游戏.第二季.人物篇.蓝礼·拜拉席恩1280高清.mkv">ftp://dy44:piaohua@dy44.piaohua.com:3119/飘花电影piaohua.com冰冰与火之歌：权力的游戏.第二季.人物篇.蓝礼&middot;拜拉席恩1280高清.mkv</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#00ffff" style="line-height: 18px; word-break: break-all" width="100%">
				冰与火之歌：权力的游戏第二季美剧</td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3131/飘花电影piaohua.com冰与火之歌：权力的游戏第二季01.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3131/飘花电影piaohua.com冰与火之歌：权力的游戏第二季01.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3146/飘花电影piaohua.com冰与火之歌：权力的游戏第二季02.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3146/飘花电影piaohua.com冰与火之歌：权力的游戏第二季02.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3232/飘花电影piaohua.com冰与火之歌：权力的游戏第二季03.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3232/飘花电影piaohua.com冰与火之歌：权力的游戏第二季03.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3279/飘花电影piaohua.com冰与火之歌：权力的游戏第二季04.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3279/飘花电影piaohua.com冰与火之歌：权力的游戏第二季04.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3329/飘花电影piaohua.com冰与火之歌：权力的游戏第二季05.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3329/飘花电影piaohua.com冰与火之歌：权力的游戏第二季05.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3370/飘花电影piaohua.com冰与火之歌：权力的游戏第二季06.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3370/飘花电影piaohua.com冰与火之歌：权力的游戏第二季06.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3439/飘花电影piaohua.com冰与火之歌：权力的游戏第二季07.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3439/飘花电影piaohua.com冰与火之歌：权力的游戏第二季07.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3478/飘花电影piaohua.com冰与火之歌：权力的游戏第二季08.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3478/飘花电影piaohua.com冰与火之歌：权力的游戏第二季08.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#00ffff" style="line-height: 18px; word-break: break-all" width="100%">
				冰与火之歌：权力的游戏第二季美剧1024高清MKV</td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3132/飘花电影piaohua.com冰与火之歌：权力的游戏第二季1024高清.mkv">ftp://dy44:piaohua@dy44.piaohua.com:3132/飘花电影piaohua.com冰与火之歌：权力的游戏第二季1024高清.mkv</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3188/飘花电影piaohua.com冰与火之歌：权力的游戏第二季1024高清02.mkv">ftp://dy44:piaohua@dy44.piaohua.com:3188/飘花电影piaohua.com冰与火之歌：权力的游戏第二季1024高清02.mkv</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3243/飘花电影piaohua.com冰与火之歌：权力的游戏第二季1024高清03.mkv">ftp://dy44:piaohua@dy44.piaohua.com:3243/飘花电影piaohua.com冰与火之歌：权力的游戏第二季1024高清03.mkv</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3286/飘花电影piaohua.com冰与火之歌：权力的游戏第二季1024高清04.mkv">ftp://dy44:piaohua@dy44.piaohua.com:3286/飘花电影piaohua.com冰与火之歌：权力的游戏第二季1024高清04.mkv</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3329/飘花电影piaohua.com冰与火之歌：权力的游戏第二季1024高清05.mkv">ftp://dy44:piaohua@dy44.piaohua.com:3329/飘花电影piaohua.com冰与火之歌：权力的游戏第二季1024高清05.mkv</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3370/飘花电影piaohua.com冰与火之歌：权力的游戏第二季1024高清06.mkv">ftp://dy44:piaohua@dy44.piaohua.com:3370/飘花电影piaohua.com冰与火之歌：权力的游戏第二季1024高清06.mkv</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3424/飘花电影piaohua.com冰与火之歌：权力的游戏第二季1024高清07.mkv">ftp://dy44:piaohua@dy44.piaohua.com:3424/飘花电影piaohua.com冰与火之歌：权力的游戏第二季1024高清07.mkv</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3474/飘花电影piaohua.com冰与火之歌：权力的游戏第二季1024高清08.mkv">ftp://dy44:piaohua@dy44.piaohua.com:3474/飘花电影piaohua.com冰与火之歌：权力的游戏第二季1024高清08.mkv</a></td>
		</tr>
	</tbody>
</table>
<p>
	&nbsp;</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1AP130-232P.jpg{/dede:field}
