{dede:field name='keywords'}铁青/苍白BD1280高清迅雷下载，{/dede:field}
{dede:field name='description'}铁青/苍白BD1280高清迅雷下载、免费下载，铁青/苍白BD1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}铁青/苍白BD1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-21{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://i.imgur.com/AqB7a.jpg" style="width: 700px; height: 1038px" /><img alt="" src="http://i.imgur.com/y86b9.jpg" style="width: 700px; height: 882px" /></p>
<p>
	【影片原名】Livide<br />
	【中文译名】铁青 / 苍白<br />
	【出品公司】帝门影业公司<br />
	【出品年代】2011 年<br />
	【上映日期】2011年12月7日 &nbsp; 法国<br />
	【IMDB链接】<a href="http://www.xiaozhizhu.net/" target="_blank">http://www.xiaozhizhu.net/</a><br />
	【IMDB评分】5.8/10 (635 votes)<br />
	【国　　家】法国<br />
	【类　　别】惊悚 / 奇幻 &nbsp;/ &nbsp;恐怖<br />
	【导　　演】亚历山大&middot;布斯蒂罗 Alexandre Bustillo<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 朱利安&middot;莫利 Julien Maury<br />
	【主　　演】杰瑞米&middot;卡彭 J&eacute;r&eacute;my Kapone &nbsp;....Ben<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 卡瑟琳&middot;雅各布 Catherine Jacob &nbsp;....Wilson<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 玛丽-克劳德&middot;皮塔卡拉 Marie-Claude Pietragalla &nbsp;....Jessel<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Chlo&eacute; Coulloud &nbsp;....Lucie<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; F&eacute;lix Moati &nbsp;....William<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Chlo&eacute; Marcq &nbsp;....Anna<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Lo&iuml;c Berthezene &nbsp;....P&eacute;re Lucie<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Serge Cabon &nbsp;....P&egrave;re de William<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 碧翠斯&middot;黛尔 B&eacute;atrice Dalle &nbsp;....M&eacute;re Lucie<br />
	<br />
	<br />
	<b>【内容简介】</b><br />
	<br />
	&nbsp; &nbsp; 在最恐怖的万圣节夜晚，当三个年轻人决定到一个老太太的旧房子探险，但他们没想到，等待他们的并不是一间普通的房子&hellip;<br />
	<br />
	<br />
	<b>【简 评】</b><br />
	<br />
	★荒凉而不安...苍白的杰作！当爱丽丝梦游仙境遇见猛鬼追魂，血黑色的恐怖故事，黑暗和迷人的气氛，原始而令人震惊的不安。一个流派的一个里程碑。<br />
	－－《Deadline》杂志<br />
	<br />
	★原始、大气、大量的血腥！<br />
	－－Dreadcentral.com网站<br />
	<br />
	★嗜血飞蛾版的《爱丽丝梦游仙境》，情节倒不是多么的出彩，但视觉效果却是出奇的优雅美丽惊艳，你可以从中看到很多经典恐怖片的影子。这样一部以俗套恐怖片段子开始的电影最后直接陷入奇幻超现实主义的范畴，以现实的逻辑去看剧情看似硬伤，但这份超出预期的诡异离奇正是影片的魅力所在。</p>
<p>
	<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120521/00/62564813201205210006283893842009240_002.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120521/00/62564813201205210006283893842009240_001.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120521/00/62564813201205210006283893842009240_000.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120521/00/62564813201205210017582167912936403_000.jpg" style="width: 720px; height: 405px" /><br />
	<br />
	&nbsp;</p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.net" target="_blank">铁青BD在线观看</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy125:piaohua@dy125.piaohua.com:8086/飘花电影piaohua.com铁青BD中字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:8086/飘花电影piaohua.com铁青BD中字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1513D10-1F93.jpg{/dede:field}
