<?php
$z[0]=Array("field","破胆惊魂夜/破胆三次/狼人/群魔",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","破胆惊魂夜/破胆三次/狼人/群魔乱舞[BD中英双字1280x720高清版]迅雷下载、免费下载，破胆惊魂夜/破胆三次/狼人/群魔乱舞[BD中英双字1280x720高清版]Gvod高清在线播放，剧情介绍等。",72,284);
$z[1][4]['name']="description";
$z[2]=Array("field","破胆惊魂夜/破胆三次/狼人/群魔乱舞[BD中英双字1280x720高清版]",286,383);
$z[2][4]['name']="title";
$z[3]=Array("field","",385,424);
$z[3][4]['name']="writer";
$z[4]=Array("field","",426,465);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-06-14",467,517);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",519,556);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://3e:3e@d8.3edyy.com:165/【3E电影院www.eee4.cc】破胆惊魂夜BD中英双字1280x720高清版.rmvb\" target=\"_blank",558,704);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MQ3545F-4Ea.jpg",706,787);
$z[8][4]['name']="litpic";

?>