{dede:field name='keywords'}哈迪塞镇之战[BD中英双字1024x57{/dede:field}
{dede:field name='description'}哈迪塞镇之战[BD中英双字1024x576高清版无水印]迅雷下载、免费下载，哈迪塞镇之战[BD中英双字1024x576高清版无水印]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}哈迪塞镇之战[BD中英双字1024x576高清版无水印]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2010-01-24{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://3e:3e@www2.3edyy.com:3875/【3E电影院www.3edyy.com】哈迪塞镇之战BD中英双字1024x576高清版无水印.rmvb" target="_blank{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MP5a440-1MN.jpg{/dede:field}
