{dede:field name='keywords'}泰勒·斯威夫特2011现在说出来演{/dede:field}
{dede:field name='description'}泰勒·斯威夫特2011现在说出来演唱会BD高清迅雷下载、免费下载，泰勒·斯威夫特2011现在说出来演唱会BD高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}泰勒·斯威夫特2011现在说出来演唱会BD高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-03-28{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="/uploads/allimg/c120525/133O0b34320-133454.jpg" style="width: 500px; height: 500px" /></p>
<p>
	中文片名: 泰勒 史薇芙特 Speak Now World Tour Live 2011<br />
	英文片名: Taylor Swift Speak Now World Tour Live 2011<br />
	国家地区: 欧美<br />
	音乐类型: 演唱会<br />
	资源格式: BD-rmvb<br />
	发行时间: 2011/11/21<br />
	艺人团队: 泰勒 史薇芙特<br />
	<br />
	对白语言: 英语&nbsp;<br />
	字幕语种:&nbsp;&nbsp; 中英双字</p>
<p>
	美国乡村小天后泰勒&middot;斯威夫特（Taylor Swift）日前宣布将发行全新演唱会专辑《Speak Now World Tour - Live》，而这张专辑将记录了泰勒2011年&lsquo;现在说出来&rsquo;世界巡回演唱会(Taylor Swift Speak Now World Tour 2011)并计划在美国时间11月21日发行。<br />
	<br />
	　　据了解，这张全新专辑将以CD+DVD版本发行，DVD收录了泰勒在演唱会上演绎的17首热门作品，而CD则收录了长达75分钟的演唱会音乐实况。对此，泰勒在官网上发表声明表示道：&ldquo;我非常兴奋第一张演唱会专辑的面世，来不及和你们见面。&rdquo;<br />
	<br />
	Deluxe two disc (CD + DVD) live release from the Country/Pop crossover superstar. This set gives fans the complete Taylor Swift Speak Now concert experience, showcasing performances of all 17 songs from Taylor&#39;s Speak Now show plus additional bonus content. The CD contains over 75 minutes of music, including live versions of favorites from the Speak Now album.<br />
	<br />
	曲目:<br />
	1. Sparks Fly<br />
	2. Mine<br />
	3. The Story Of Us<br />
	4. Our Song<br />
	5. Mean<br />
	6. Back To December / Apologize / You&#39;re Not Sorry<br />
	7. Better Than Revenge<br />
	8. Speak Now<br />
	9. Fearless / I&#39;m Yours / Hey, Soul Sister<br />
	10. Last Kiss<br />
	11. Drops Of Jupiter<br />
	12. You Belong With Me<br />
	13. Dean John<br />
	14. Enchanted<br />
	15. Haunted<br />
	16. Long Live<br />
	17. Ours<br />
	18. Fifteen<br />
	19. Love Story<br />
	<br />
	<img alt="" src="/uploads/allimg/c120525/133O0b35620-1431I.jpg" style="width: 720px; height: 453px" /><br />
	<br />
	&nbsp;</p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="/uploads/allimg/c120525/133O0T31310-42214.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy125:piaohua@dy125.piaohua.com:7779/飘花电影piaohua.com泰勒斯威夫特2011现在说出来演唱会BD1280高清.rmvb</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O0b3R0-155046.jpg{/dede:field}
