<?php
$z[0]=Array("field","明星狗/闪电狗/老狗/霹雳战狗[DV",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","明星狗/闪电狗/老狗/霹雳战狗[DVD中英双字1024/1280高清版]迅雷下载、免费下载，明星狗/闪电狗/老狗/霹雳战狗[DVD中英双字1024/1280高清版]Gvod高清在线播放，剧情介绍等。",73,277);
$z[1][4]['name']="description";
$z[2]=Array("field","明星狗/闪电狗/老狗/霹雳战狗[DVD中英双字1024/1280高清版]",279,372);
$z[2][4]['name']="title";
$z[3]=Array("field","",374,413);
$z[3][4]['name']="writer";
$z[4]=Array("field","",415,454);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-11-15",456,506);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",508,545);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://e24:e24@xl2.eee4.com:9219/[3E电影站www.eee4.com]明星狗DVD中英双字.rmvb\" target=\"_blank",547,678);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MQ215310-29124.jpg",680,764);
$z[8][4]['name']="litpic";

?>