{dede:field name='keywords'}圣斗士星矢剧场版3：真红少年传{/dede:field}
{dede:field name='description'}圣斗士星矢剧场版3：真红少年传说BD国语中字1280高清迅雷下载、免费下载，圣斗士星矢剧场版3：真红少年传说BD国语中字1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}圣斗士星矢剧场版3：真红少年传说BD国语中字1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-01-15{/dede:field}
{dede:field name='body'}<p>
	<img alt="" border="0" src="http://img.album.pchome.net/54/85/02/67/0113e8daf8805843ec1fc93bdb302cba.jpg" /></p>
<p>
	◎译　　名　圣斗士星矢剧场版3：真红少年传说<br />
	◎片　　名　Shinku.no.shonen.densetsu<br />
	◎年　　代　1988<br />
	◎国　　家　日本<br />
	◎类　　别　动画/冒险/奇幻<br />
	◎语　　言　国日双语<br />
	◎字　　幕　中文<br />
	◎IMDB评分 7.7/10 (179 votes)<br />
	◎文件格式　1024 x 576<br />
	◎文件格式　x264 + AAC<br />
	◎文件大小　1CD<br />
	◎片　　长　1h:14m:46s<br />
	◎导　　演　山内重保 Shigeyasu Yamauchi<br />
	◎主　　演　古谷彻 Toru Furuya&nbsp; ....Seiya, Pegasus Bronze Saint (voice)<br />
	　　　　　　铃置洋孝 Hirotaka Suzuoki&nbsp; ....Shiryu, Dragon Bronze Saint (voice)<br />
	　　　　　　桥本晃一 Koichi Hashimoto&nbsp; ....Hyoga, Cygnus Bronze Saint (voice)<br />
	　　　　　　堀川亮 Ryo Horikawa&nbsp; ....Shun, Andromeda Bronze Saint (voice)<br />
	　　　　　　堀秀行 Hideyuki Hori&nbsp; ....Ikki, Phoenix Bronze Saint (voice)<br />
	　　　　　　潘惠子 Keiko Han&nbsp; ....Saori Kido (Athena) (voice)<br />
	　　　　　　古川登志夫 Toshio Furukawa&nbsp; ....Berenike (voice)<br />
	　　　　　　广川太一郎 Taichiro Hirokawa&nbsp; ....Abel (voice)<br />
	　　　　　　神谷明 Akira Kamiya&nbsp; ....Atlas (voice)<br />
	　　　　　　Katsuji Mori&nbsp; ....Jaow (voice)<br />
	　　　　　　难波圭一 Keiichi Nanba&nbsp; ....Aphrodite, Piscis Gold Saint (voice)<br />
	　　　　　　纳谷六朗 Rokuro Naya&nbsp; ....Camus, Aquarius Gold Saint (voice)<br />
	　　　　　　柴田由美子 Yumiko Shibata&nbsp; ....Shun-Rei (voice)<br />
	　　　　　　曾我部和行 Kazuyuki Sogabe&nbsp; ....Saga, Gemini Gold Saint (voice)<br />
	　　　　　　户谷公次 Koji Totani&nbsp; ....Shura, Capricorn Gold Saint (voice)<br />
	　　　　　　矢田耕司 Koji Yada&nbsp; ....Doukou (voice)<br />
	◎简　　介<br />
	&nbsp;<br />
	&nbsp; &nbsp; 经过了数千年，太阳神阿波罗再次复活，他带领着他的神斗士以及用神力使在十二宫中死去而复活的黄金圣斗士来到了陆地。他决心要发动大洪水，重新创造一个属于神的世界。他主动邀请雅典娜一起统治新的世界。沙织假装同意，但是伺机暗杀阿波罗，未果，反而被杀。修罗和卡妙首先发难，却被三名神斗士围攻，不敌而亡。<br />
	<br />
	&nbsp; &nbsp; 星矢知道雅典娜已死，于是，来太阳神殿找阿波罗算账，途中遇到了紫龙、冰河、瞬和一辉。终于在黄金圣斗士的帮助下，五人来到了阿波罗神殿，星矢穿上人马座黄金圣衣，而紫龙及冰河也分别穿上他们师父的天秤座及水瓶座黄金圣衣。但在阿波罗的攻击下，只有矢避开了。星矢虽然不能伤到阿波罗，但却以小宇宙的力量救回了雅典娜。星矢重新振作，发挥超越神的力量，一箭射倒了阿波罗。这颗巨大的太阳，最终也落下去了。<br />
	<br />
	<img alt="" border="0" src="http://img.album.pchome.net/54/85/07/05/326e4e09545fc3850f3589cbd224163e.jpg" /><br />
	<img alt="" border="0" src="http://img.album.pchome.net/54/85/07/05/83e2d1d1eb6f331033bf3f5ae257be1d.jpg" /></p>
<p>
	&nbsp;</p>

<p>
	[下载地址]： &nbsp;<img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2627/飘花电影piaohua.com圣斗士星矢剧场版3：真红少年传说BD国语中字1280高清.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:2627/飘花电影piaohua.com圣斗士星矢剧场版3：真红少年传说BD国语中字1280高清.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2627/飘花电影piaohua.com圣斗士星矢剧场版3：真红少年传说BD国语中字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1B0G0-24E4.jpg{/dede:field}
