{dede:field name='keywords'}倒带(回放)DVD中字2012最新美国{/dede:field}
{dede:field name='description'}倒带(回放)DVD中字2012最新美国恐怖惊悚大片迅雷下载、免费下载，倒带(回放)DVD中字2012最新美国恐怖惊悚大片Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}倒带(回放)DVD中字2012最新美国恐怖惊悚大片{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-21{/dede:field}
{dede:field name='body'}<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120322/18/56643687201203221811403359373908419_006.jpg" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120322/18/56643687201203221811403359373908419_005.jpg" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120322/18/56643687201203221811403359373908419_004.jpg" /></p>
<p>
	◎译　　名　倒带/回放<br />
	◎片　　名　Playback<br />
	◎年　　代　2012<br />
	◎国　　家　美国<br />
	◎类　　别　惊悚/恐怖<br />
	◎语　　言　英语<br />
	◎字　　幕　中字<br />
	◎IMDB评分 4.2/10 (379 votes)<br />
	◎IMDB链接：<a href="http://www.bluemv.com" title="电影下载">http://www.bluemv.com</a><br />
	◎文件格式　DVD-RMVB<br />
	◎视频尺寸　500 x 272<br />
	◎文件大小　1CD 498MB<br />
	◎片　　长　98 mins<br />
	◎导　　演　Michael A. Nickles<br />
	◎主　　演　Johnny Pacar ... Julian<br />
	Ambyr Childers ... Riley<br />
	克里斯汀&middot;史莱特 Christian Slater ... Frank Lyons<br />
	Jonathan Keltz ... Nate<br />
	Alessandra Torresani ... Brianna<br />
	Toby Hemingway ... Quinn<br />
	Jennifer Missoni ... Dee Dee<br />
	Daryl Mitchell ... Wylie<br />
	Mark Metcalf ... Chris Safford<br />
	Abe Larkin ... Student<br />
	Luke Bonczyk ... Harlan Diehl<br />
	Kenny Stevenson<br />
	Dorien Davies ... Ms. Milton<br />
	David Roetman ... Paramedic<br />
	Jana Veldheer ... Susie Diehl</p>
<p>
	◎简　　介　</p>
<p>
	一群高中生为了探索小镇曾经发生的凶杀案，却牵连出了一系列未知的谜团。<br />
	世界上第一部电影，代代相传的邪灵，《午夜凶铃》式的谋杀方法，毫无动机的屠杀，乱伦，附体，中间隐藏着多少鲜为人知的秘密呢？</p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120322/18/56643687201203221811403359373908419_003.jpg" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120322/18/56643687201203221811403359373908419_002.jpg" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120322/18/56643687201203221811403359373908419_000.jpg" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120322/18/56643687201203221811403359373908419_001.jpg" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3057/飘花电影piaohua.com倒带(回放)DVD中字.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3057/飘花电影piaohua.com倒带(回放)DVD中字.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3057/飘花电影piaohua.com倒带(回放)DVD中字.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15122230-52A4.jpg{/dede:field}
