<?php
$z[0]=Array("field","告白[DVD中字]迅雷下载，免费下",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","告白[DVD中字]迅雷下载、免费下载，告白[DVD中字]Gvod高清在线播放，剧情介绍等。",72,192);
$z[1][4]['name']="description";
$z[2]=Array("field","告白[DVD中字]",194,245);
$z[2][4]['name']="title";
$z[3]=Array("field","",247,286);
$z[3][4]['name']="writer";
$z[4]=Array("field","",288,327);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-01-22",329,379);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",381,418);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://4e:4e@d6.3edyy.com:615/【3E看看www.3ekk.com】告白[DVD中字].rmvb\" target=_blank>ftftp://4e:4e@d6.3edyy.com:615/【3E看看www.3ekk.com】告白[DVD中字].rmvb</A></TD></TR></TBODY></TABLE></div><ul class=\"mmlist",420,668);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MP359150-422F.jpg",670,753);
$z[8][4]['name']="litpic";

?>