<?php
$z[0]=Array("field","海云台[DVD中字]迅雷下载，免费",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","海云台[DVD中字]迅雷下载、免费下载，海云台[DVD中字]Gvod高清在线播放，剧情介绍等。",72,196);
$z[1][4]['name']="description";
$z[2]=Array("field","海云台[DVD中字]",198,251);
$z[2][4]['name']="title";
$z[3]=Array("field","",253,292);
$z[3][4]['name']="writer";
$z[4]=Array("field","",294,333);
$z[4][4]['name']="source";
$z[5]=Array("field","2009-09-03",335,385);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",387,424);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://4e:4e@www2.eee4.com:732/[www.eee4.cn提供]海云台DVD中字无水印.rmvb\" target=_blank>ftftp://4e:4e@www2.eee4.com:732/[www.eee4.cn提供]海云台DVD中字无水印.rmvb</A></TD></TR></TBODY></TABLE></div><ul class=\"mmlist",426,678);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MPW3O0-51553.jpg",680,762);
$z[8][4]['name']="litpic";

?>