{dede:field name='keywords'}冒险王HD高清迅雷下载，免费下载{/dede:field}
{dede:field name='description'}冒险王HD高清迅雷下载、免费下载，冒险王HD高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}冒险王HD高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-09-27{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img165.poco.cn/mypoco/myphoto/20110926/14/62564813201109261426561401291525265_000.jpg" style="width: 500px; height: 661px" /></p>
<p>
	◎译　　名　冒险王<br />
	◎片　　名　Mo him wong<br />
	◎年　　代　1996<br />
	◎地　　区　中国香港<br />
	◎类　　别　动作<br />
	◎语　　言　国语<br />
	◎字　　幕　中文<br />
	◎IMDB评分 5.9/10 (916 votes)<br />
	◎IMDB链接 <a href="http://www.imdb.com/title/tt0110463">http://www.imdb.com/title/tt0110463</a><br />
	◎文件格式　TS+AC3<br />
	◎视频尺寸　1024 x 576<br />
	◎文件大小　1.18G<br />
	◎片　　长　01:30:27<br />
	◎导　　演　程小东 (Siu-Tung Ching)<br />
	◎主　　演　周比利 (Billy Chow) ...... Chan/Japanese Embassy Guard<br />
	　　　　　　金城武 (Takeshi Kaneshiro) ...... Shing<br />
	　　　　　　江约诚 (Johnny Kong) ......<br />
	　　　　　　关之琳 (Rosamund Kwan) ...... Monica Kwan/Cammy<br />
	　　　　　　罗家英 (Kar-Ying Law) ...... Headmaster<br />
	　　　　　　李连杰 (Jet Li) ...... Chow Si-Kit<br />
	　　　　　　Sing Ngai ...... The Movie Star/Hung Sing<br />
	　　　　　　杨采妮 (Charlie Yeung) ...... Yvonne</p>
<p>
	<br />
	◎简　　介　</p>
<p>
	当年唐三藏往西天取得无字真经，谓可藉此改变世界，真经因而成为众人争夺的目标。民国初年，中国政府邀考古学家卫亦信（李连杰）及其徒包教晓（金城武）追查真经下落,免被日本人捷足先登，线索则在藏经木盒的表面，卫师徒混入日本领事馆，查找经盒，结果结识如风（关之琳）。<br />
	　　<br />
	卫追查线索到正义日报社，编辑英叔（罗家英）为了保护经盒，以办报作为掩护，卫打听到经盒情况后，电邀龙将军来上海主持大局，但此消息被如风得知，而如风的真实身份是日本特务，风决定赶往刺杀龙将军，并联络贼党倪霸（倪星）抢夺经盒。<br />
	　　<br />
	真经是否会落入倪霸手中，真经的秘密能否打开？卫也面临了一生以来最大的考验&hellip;</p>
<p>
	◎幕后制作</p>
<p>
	《冒险王》是李连杰多产时期的最后一部作品，风格与斯皮尔伯格的《印地安纳&middot;琼斯》系列十分相似。全片两条线索，一条是现实，另外一条则是由现实里的主人公写的一部小说。影片在现实与小说中切换，现实中的人物，感情，爱憎也都带到了小说中。本片导演是程小东，在影片中除了表现李连杰飘逸洒脱的功夫外，还融入了很多特技镜头，打造了一个奇幻的冒险之旅。拍摄本片时还出了点意外：拍了一半就把片场烧了，几十个煤气罐爆炸。李连杰至今想起来仍有些后怕，笑称是&ldquo;片名没起好&rdquo;。</p>
<p>
	&nbsp;<img alt="" src="http://img165.poco.cn/mypoco/myphoto/20110926/14/62564813201109261431484051277805589_001.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img165.poco.cn/mypoco/myphoto/20110926/14/62564813201109261431484051277805589_000.jpg" style="width: 720px; height: 405px" /></p>

<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="&#13;&#10;ftp://dy125:piaohua@dy125.piaohua.com:6003/飘花电影piaohua.com冒险王HD国语中字1024高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:6003/飘花电影piaohua.com冒险王HD国语中字1024高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15250Y0-42217.jpg{/dede:field}
