{dede:field name='keywords'}CCTV2012年元宵晚会HD1280高清迅{/dede:field}
{dede:field name='description'}CCTV2012年元宵晚会HD1280高清迅雷下载、免费下载，CCTV2012年元宵晚会HD1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}CCTV2012年元宵晚会HD1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-02-09{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="/uploads/allimg/c120524/133N4W52a0-A0N.jpg" style="width: 650px; height: 291px" /></p>
<p>
	2012年央视元宵晚会完整节目单：<br />
	<br />
	1.开场联唱<br />
	（1）《卖汤圆》 表演者：主持团<br />
	（2）《五哥放羊》 表演者：胡月、陆建民夫妇<br />
	（3）《绣荷包》 表演者：戴玉强家庭<br />
	（4）《放马山歌》 表演者：玖月奇迹及家庭<br />
	（5）《龙船调》 表演者：刘和刚夫妇<br />
	<br />
	2.歌曲《祝福歌》 表演者：MIC/I ME<br />
	<br />
	3.杂技音乐剧《团圆饭》 表演者：洪剑涛<br />
	<br />
	4.创意节目《彩云追月》 表演者：李云迪、沙溢<br />
	<br />
	5.相声《小合唱2》 表演者：周炜、刘大成、石头<br />
	<br />
	6.歌曲《因为爱情》 表演者：蔡明、廖昌永<br />
	<br />
	7.歌曲《月亮代表我的心》 表演者：冯绍峰<br />
	<br />
	8.歌曲《沂蒙山小调》 表演者：于文华、朱之文<br />
	<br />
	9.歌曲《逐梦令》 表演者：李玉刚<br />
	<br />
	10.儿童戏曲联唱《梨园新蕾》<br />
	（1）京剧《西厢记》选段 表演者：巴特尔<br />
	（2）黄梅戏《女驸马》选段 表演者：陈思妮<br />
	（3）豫剧《朝阳沟》选段 表演者：邓鸣贺<br />
	（4）越剧《红楼梦》选段 表演者：陈果、章晌旻朱<br />
	<br />
	11.杂技《抖空竹》 表演者：周天<br />
	<br />
	12.歌曲《心升明月》 表演者：李健<br />
	<br />
	13.相声《猜灯谜》 表演者：曹云金、刘云天<br />
	<br />
	14.舞蹈《万泉河水》<br />
	<br />
	15.歌舞《新采槟榔》 表演者：阿朵<br />
	<br />
	16.歌曲《带着爸妈去旅行》 表演者：徐子崴、王莉<br />
	<br />
	17.民俗节目《龙腾狮舞闹元宵》<br />
	<br />
	<img alt="" src="/uploads/allimg/c120524/133N4W54930-IV5.jpg" /><img alt="" src="/uploads/allimg/c120524/133N4W553F-T955.jpg" /><img alt="" src="/uploads/allimg/c120524/133N4W55P-a2J.jpg" style="width: 300px; height: 169px" /><img alt="" src="/uploads/allimg/c120524/133N4W56240-10L02.jpg" style="width: 300px; height: 169px" /><img alt="" src="/uploads/allimg/c120524/133N4W5BF-11B51.jpg" /><img alt="" src="/uploads/allimg/c120524/133N4W5F60-12b19.jpg" /><img alt="" src="/uploads/allimg/c120524/133N4W5K40-136335.jpg" /><img alt="" src="/uploads/allimg/c120524/133N4W5Q0-1461G.jpg" style="width: 300px; height: 169px" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="/uploads/allimg/c120524/133N2Z4FF-102231.jpg" />&nbsp;&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy125:piaohua@dy125.piaohua.com:7588/飘花电影piaohua.comCCTV2012元宵晚会HD1280高清.rmvb</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120524/133N4W5V40-15R53.jpg{/dede:field}
