{dede:field name='keywords'}冷血/冷血杀手BD高清中英双字102{/dede:field}
{dede:field name='description'}冷血/冷血杀手BD高清中英双字1024*576迅雷下载、免费下载，冷血/冷血杀手BD高清中英双字1024*576Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}冷血/冷血杀手BD高清中英双字1024*576{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-09-23{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img165.poco.cn/mypoco/myphoto/20110922/22/62564813201109222208383797516518553_000.jpg" style="width: 716px; height: 927px" /></p>
<p>
	◎译　　名　冷血/冷血杀手<br />
	◎片　　名　In Cold Blood<br />
	◎年　　代　1967<br />
	◎国　　家　美国<br />
	◎类　　别　剧情/犯罪<br />
	◎语　　言　英语<br />
	◎字　　幕　中英<br />
	◎IMDB评分&nbsp; 8.1/10 (8,667 votes)<br />
	◎IMDB链接&nbsp; <a href="http://www.imdb.com/title/tt0061809/">http://www.imdb.com/title/tt0061809/</a><br />
	◎导　　演&nbsp;&nbsp; 理查德&middot;布鲁克斯&nbsp;&nbsp; Richard Brooks&nbsp;&nbsp;<br />
	◎主　　演&nbsp;&nbsp; 罗伯特&middot;布莱克&nbsp;&nbsp; Robert Blake&nbsp;&nbsp; ....Perry Smith<br />
	　　　　　　斯科特&middot;威尔森 Scott Wilson&nbsp; ....Richard Hickock<br />
	　　　　　　约翰&middot;福赛思 John Forsythe&nbsp; ....Alvin Dewey<br />
	　　　　　　Paul Stewart&nbsp; ....Jensen<br />
	　　　　　　Gerald S. O&#39;Loughlin&nbsp; ....Harold Nye<br />
	　　　　　　Jeff Corey&nbsp; ....Mr. Hickock<br />
	　　　　　　John Gallaudet&nbsp; ....Roy Church<br />
	　　　　　　James Flavin&nbsp; ....Clarence Duntz<br />
	　　　　　　John Collins&nbsp; ....Judge Roland Tate<br />
	　　　　　　Charles McGraw&nbsp; ....Tex Smith<br />
	　　　　　　Will Geer&nbsp; ....Prosecutor<br />
	　　　　　　James Lantz&nbsp; ....Officer Rohleder<br />
	　　　　　　John McLiam&nbsp; ....Herbert Clutter<br />
	　　　　　　Brenda Currin&nbsp; ....Nancy Clutter<br />
	　　　　　　Ruth Storey&nbsp; ....Bonnie Clutter<br />
	　　　　　　Paul Hough&nbsp; ....Kenyon Clutter<br />
	　　　　　　Vaughn Taylor&nbsp; ....Good Samaritan<br />
	　　　　　　Duke Hobbie&nbsp; ....Young Reporter<br />
	　　　　　　Sheldon Allman&nbsp; ....Rev. Jim Post<br />
	　　　　　　Sammy Thurman&nbsp; ....Flo Smith<br />
	　　　　　　Raymond Hatton&nbsp; ....Elderly Hitchhiker<br />
	　　　　　　Sadie Truitt&nbsp; ....Herself<br />
	　　　　　　Myrtle Clare&nbsp; ....Herself<br />
	　　　　　　Ted Eccles&nbsp; ....Young Hitchhiker<br />
	　　　　　　Al Christy&nbsp; ....Sheriff<br />
	　　　　　　Don Sollars&nbsp; ....Luke Sharpe<br />
	　　　　　　Harriet Levitt&nbsp; ....Mrs. Hartman<br />
	　　　　　　Stan Levitt&nbsp; ....Insurance Man<br />
	　　　　　　Mary Linda Rapelye&nbsp; ....Susan Kidwell<br />
	　　　　　　Darlene Williams&nbsp; ....Little Girl on Bus (as Darlene Williams)<br />
	　　　　　　Odd Williams&nbsp; ....Defense Attorney<br />
	　　　　　　Nick Dimitri&nbsp; ....Las Vegas Cop (uncredited)<br />
	　　　　　　John Flinn&nbsp; ....Policeman (uncredited)<br />
	　　　　　　Paul Frees&nbsp; ....Radio announcer (uncredited)<br />
	　　　　　　Rhonda Fultz&nbsp; ....Nancy&#39;s Friend (uncredited)<br />
	　　　　　　Bobby Johnson&nbsp; ....Prison Guard (uncredited)<br />
	　　　　　　Richard Kelton&nbsp; ....Nancy&#39;s Boyfriend (uncredited)<br />
	　　　　　　Gerry Okuneff&nbsp; ....Policeman (uncredited)<br />
	　　　　　　Bowman Upchurch&nbsp; ....Andy (uncredited)<br />
	　　　　　　Guy Way&nbsp; ....Prison Guard (uncredited)</p>
<p>
	◎简　　介　&nbsp;&nbsp;&nbsp;<br />
	　　根据美国作家楚曼卡波堤著名的报告文学拍摄而成。导演采取黑白纪录片式的纪实手法，忠实地观察可以说是一个极其详尽和细腻的犯罪个案纪录。两名冷血罪犯如何在一个堪萨斯州的农家犯下冷血的灭门血案，直到两人被警方逮捕直至处刑。<br />
	幕后制作<br />
	　　由于全片风格高度写实而冷峻，让观众有身临现场的感觉，气氛的紧凑惊心令人不寒而栗，在情绪上亦会受到强烈的撞击。1996年重拍，更加注重背景的介绍。</p>
<p>
	&nbsp;<img alt="" src="http://img165.poco.cn/mypoco/myphoto/20110922/22/62564813201109222208383797516518553_002.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img165.poco.cn/mypoco/myphoto/20110922/22/62564813201109222208383797516518553_001.jpg" style="width: 720px; height: 405px" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="&#13;&#10;ftp://dy125:piaohua@dy125.piaohua.com:5019/飘花电影piaohua.com冷血杀手BD中英双字1024高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:5019/飘花电影piaohua.com冷血杀手BD中英双字1024高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O152500P-332G.jpg{/dede:field}
