<?php
$z[0]=Array("field","抢救切尔诺贝利[DVD中字]迅雷下",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","抢救切尔诺贝利[DVD中字]迅雷下载、免费下载，抢救切尔诺贝利[DVD中字]Gvod高清在线播放，剧情介绍等。",72,212);
$z[1][4]['name']="description";
$z[2]=Array("field","抢救切尔诺贝利[DVD中字]",214,275);
$z[2][4]['name']="title";
$z[3]=Array("field","",277,316);
$z[3][4]['name']="writer";
$z[4]=Array("field","",318,357);
$z[4][4]['name']="source";
$z[5]=Array("field","2009-02-27",359,409);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",411,448);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://e17:e17@xl2.eee4.com:9219/[3E电影站www.eee4.com]抢救切尔诺贝利.rmvb\" target=_blank>ftftp://e17:e17@xl2.eee4.com:9219/[3E电影站www.eee4.com]抢救切尔诺贝利.rmvb</A></TD></TR></TBODY></TABLE></div><ul class=\"mmlist",450,706);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MP4610F-34511.jpg",708,791);
$z[8][4]['name']="litpic";

?>