{dede:field name='keywords'}影子写手/枪手/代笔作家/影子灭{/dede:field}
{dede:field name='description'}影子写手/枪手/代笔作家/影子灭杀令[BD中英双字1024x576高清版]迅雷下载、免费下载，影子写手/枪手/代笔作家/影子灭杀令[BD中英双字1024x576高清版]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}影子写手/枪手/代笔作家/影子灭杀令[BD中英双字1024x576高清版]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2010-07-22{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://7e:7e@m1.eee4.cc:1511/【3e电影网www.eee4.cc】影子写手BD中英双字1024x576高清版.rmvb" target=_blank>ftftp://7e:7e@m1.eee4.cc:1511/【3e电影网www.eee4.cc】影子写手BD中英双字1024x576高清版.rmvb</A></TD></TR></TBODY></TABLE></div><ul class="mmlist{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MP323T0-292b.jpg{/dede:field}
