<?php
$z[0]=Array("field","影子写手/枪手/代笔作家/影子灭",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","影子写手/枪手/代笔作家/影子灭杀令[BD中英双字1024x576高清版]迅雷下载、免费下载，影子写手/枪手/代笔作家/影子灭杀令[BD中英双字1024x576高清版]Gvod高清在线播放，剧情介绍等。",72,284);
$z[1][4]['name']="description";
$z[2]=Array("field","影子写手/枪手/代笔作家/影子灭杀令[BD中英双字1024x576高清版]",286,383);
$z[2][4]['name']="title";
$z[3]=Array("field","",385,424);
$z[3][4]['name']="writer";
$z[4]=Array("field","",426,465);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-07-22",467,517);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",519,556);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://7e:7e@m1.eee4.cc:1511/【3e电影网www.eee4.cc】影子写手BD中英双字1024x576高清版.rmvb\" target=_blank>ftftp://7e:7e@m1.eee4.cc:1511/【3e电影网www.eee4.cc】影子写手BD中英双字1024x576高清版.rmvb</A></TD></TR></TBODY></TABLE></div><ul class=\"mmlist",558,844);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MP323T0-292b.jpg",846,928);
$z[8][4]['name']="litpic";

?>