{dede:field name='keywords'}纽约行动BD中英双字1024/1280高{/dede:field}
{dede:field name='description'}纽约行动BD中英双字1024/1280高清2012最新中国上映美国动作惊悚迅雷下载、免费下载，纽约行动BD中英双字1024/1280高清2012最新中国上映美国动作惊悚Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}纽约行动BD中英双字1024/1280高清2012最新中国上映美国动作惊悚{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-04-23{/dede:field}
{dede:field name='body'}<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120414/11/56643687201204141157481573770660529_004.jpg" /></p>
<p>
	导演: 艾萨克&middot;佛罗伦汀<br />
	编剧: 博兹&middot;大卫逊 / Michael Hurst<br />
	主演: 斯科特&middot;阿金斯 / 伊原刚志 / 肘井美佳 / 伊川东吾 / 迈尔斯&middot;安德森<br />
	类型: 动作 / 犯罪 / 剧情 / 惊悚<br />
	制片国家/地区: 美国<br />
	语言: 英语 / 日语 / 俄语 / 西班牙语<br />
	上映日期: 2009-09-01(美国) / 2012-04-13(中国大陆)<br />
	片长: 86分钟<br />
	又名: 忍者 / New York Assassination<br />
	IMDb链接: tt1182921</p>
<p>
	<br />
	剧情简介</p>
<p>
	　　在一个随时都在被人追杀的陌生国度，凯西（斯科特&middot;阿金斯 Scott Adkins 饰）得到师傅的重托带着传说中的神秘武器来到纽约。师傅最终惨遭杀害，为了替师报仇，也为了解开宝物的真相，凯西开始通过仅有的一点点线索去寻求幕后的黑手。当他一点点拨云见日，了解到了这个幕后黑手原来是一个国际化的地下暗杀组织，并且这个暗杀组织的得力杀手是他的同门师兄时，凯西惊愕使然，他不愿意面对眼前的这一切。他坚信师兄是被人利用，这个组织的背后肯定还隐藏着更大的阴谋&hellip;&hellip;</p>
<p>
	<br />
	◎影片截图</p>
<p>
	&nbsp;<img src="http://img170.poco.cn/mypoco/myphoto/20120414/11/56643687201204141157481573770660529_001.jpg" style="width: 600px; height: 338px" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120414/11/56643687201204141157481573770660529_000.jpg" style="width: 600px; height: 338px" />、</p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120414/11/56643687201204141157481573770660529_003.jpg" style="width: 600px; height: 338px" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120414/11/56643687201204141157481573770660529_002.jpg" style="width: 600px; height: 338px" /></p>
<p>
	<img alt="" file="http://img170.poco.cn/mypoco/myphoto/20120422/10/56643687201204221056184068418092424_000.jpg" height="337" lazyloaded="true" src="http://img170.poco.cn/mypoco/myphoto/20120422/10/56643687201204221056184068418092424_000.jpg" style="cursor: pointer" width="600" /></p>
<p>
	<img alt="" file="http://img170.poco.cn/mypoco/myphoto/20120422/10/56643687201204221056184068418092424_003.jpg" height="337" lazyloaded="true" src="http://img170.poco.cn/mypoco/myphoto/20120422/10/56643687201204221056184068418092424_003.jpg" style="cursor: pointer" width="600" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.netftp//dy44:piaohua@dy44.piaohua.com:3201/" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3218/飘花电影piaohua.com纽约行动HD国语版.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3218/飘花电影piaohua.com纽约行动HD国语版.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3275/飘花电影piaohua.com纽约行动BD中英双字1024高清.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3275/飘花电影piaohua.com纽约行动BD中英双字1024高清.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3275/飘花电影piaohua.com纽约行动BD中英双字1280高清.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3275/飘花电影piaohua.com纽约行动BD中英双字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15633L0-19464.jpg{/dede:field}
