{dede:field name='keywords'}后天II末日天火迅雷下载，免费下{/dede:field}
{dede:field name='description'}后天II末日天火迅雷下载、免费下载，后天II末日天火Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}后天II末日天火{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2007-01-03{/dede:field}
{dede:field name='body'}<P>片　名： 后天II末日天火<BR>影视类型：科幻片 <BR>地　区：欧美地区<BR>片　长：100 分钟 <BR>主要演员：詹娜&#8226;帕可拉、尼克&#8226;曼库索 <BR>影片简介： <BR>飞星撞击地球，人类难逃恐龙噩运……六千五百万年前，弗莱彻彗星的地球之行令恐龙灭绝并形成冰河时期。现在，它将再度出现。大的彗星群中更有两颗巨型陨石，它们正高速地飞向地球。人类顿时陷入前所未有的困境，笼罩在世界末日的阴影之下……无数飞星穿过大气层，变成火球，如同飞弹般射向人口密集的市区，一幢幢摩天大楼轰然倒塌，人们惊慌失措，由此引发的飓风、地震、火山爆发更是将人类逼入了绝境，究竟还有谁能拯救人类，使我们免遭如同恐龙灭绝的噩运</P>
下载地址：<IMG src="/templets/img/down.jpg" border=0><br>
CD1：<br><table style="BORDER-RIGHT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; BORDER-BOTTOM: #cccccc 1px dotted" cellspacing="0" cellpadding="6" width="95%" align="center" border="0">
    <tbody>
        <tr>
            <td style="WORD-WRAP: break-word" bgcolor="#fdfddf"><anchor></anchor><a href="http://vod.ykzj.cn/movie/动作片/港台/末日天火/1.rm" target="_blank">后天II末日天火CD1</a></td>
        </tr>
    </tbody>
</table>
CD2：<br><table style="BORDER-RIGHT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; BORDER-BOTTOM: #cccccc 1px dotted" cellspacing="0" cellpadding="6" width="95%" align="center" border="0">
    <tbody>
        <tr>
            <td style="WORD-WRAP: break-word" bgcolor="#fdfddf"><anchor></anchor><a href="http://vod.ykzj.cn/movie/动作片/港台/末日天火/2.rm" target="_blank">后天II末日天火CD2</a></td>
    </tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O164K510-22J7.jpg{/dede:field}
