<?php
$z[0]=Array("field","叛国者BD中英双字1024/1280高清",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","叛国者BD中英双字1024/1280高清迅雷下载、免费下载，叛国者BD中英双字1024/1280高清Gvod高清在线播放，剧情介绍等。",72,224);
$z[1][4]['name']="description";
$z[2]=Array("field","叛国者BD中英双字1024/1280高清",226,293);
$z[2][4]['name']="title";
$z[3]=Array("field","",295,334);
$z[3][4]['name']="writer";
$z[4]=Array("field","",336,375);
$z[4][4]['name']="source";
$z[5]=Array("field","2012-04-30",377,427);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",429,466);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://e65:e65@xl3.eee4.com:1004/[3E电影站www.eee4.com]叛国者DVD中英双字CD1.rmvb\" target=\"_blank",468,602);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MP305460-1LR.jpg",604,686);
$z[8][4]['name']="litpic";

?>