{dede:field name='keywords'}考拉小子：英雄的诞生DVD中字韩{/dede:field}
{dede:field name='description'}考拉小子：英雄的诞生DVD中字韩国2011动画迅雷下载、免费下载，考拉小子：英雄的诞生DVD中字韩国2011动画Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}考拉小子：英雄的诞生DVD中字韩国2011动画{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-03-08{/dede:field}
{dede:field name='body'}<p>
	<img alt="" height="1073" src="http://img2081.poco.cn/mypoco/myphoto/20120307/15/64486803201203071552599837625713423_012.jpg" width="750" /></p>
<p>
	◎中 文 名　考拉小子：英雄的诞生<br />
	◎英 文 名　The Outback<br />
	◎原　　名　&#53076;&#50508;&#46972; &#53412;&#46300; : &#50689;&#50885;&#51032; &#53444;&#49373;&nbsp;&nbsp;<br />
	◎年　　代　2012<br />
	◎国　　家　爱情/喜剧/恐怖&nbsp;&nbsp;<br />
	◎片　　长　85分钟<br />
	◎导　　演　李景浩 Gyeong-ho Lee&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br />
	◎配　　音　李顺圭 Sunny<br />
	&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp;&nbsp;李泰民 Tae-min Lee<br />
	&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp;&nbsp;尹多勋 Da-Hun Yun<br />
	&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp;&nbsp;郑恩星 En-Byeol Jeong<br />
	<br />
	◎剧&nbsp; &nbsp;&nbsp;&nbsp;情<br />
	<br />
	<br />
	&nbsp; &nbsp; 某日，孤单的马戏团考拉约翰尼因事故&ldquo;流落&rdquo;到澳洲的大自然，与贪婪的经理哈密逊和摄影师黑金斯偶然遇到了被鳄鱼普格一党欺负的动物们。约翰尼挺身而出拔刀相助，一时间成了神话般的英雄。约翰尼更结识了美貌考拉米兰达和可爱考拉夏洛克，成为亲密无间的朋友。哈密逊和黑金斯还将约翰尼的义举包装成表演，拍成宣传照广为传播，将这只罕见的白毛考拉打造成超级明星。然而，居心叵测的鳄鱼普格一党秘密将夏洛克绑架，再度造成恐慌。英雄考拉约翰尼再度出马，展开拯救行动&hellip;&hellip;<br />
	<br />
	<br />
	◎幕后/花絮<br />
	<br />
	<br />
	　　《考拉：英雄的诞生》是韩美合作的第二部动画片，首次合作是2006年的《海底大冒险》。随着技术的发展，和影圈国际化的磨合，《考拉》采用了全新3D效果拍摄，由执导《海底大冒险》《加菲猫：现实世界历险记》的动画导演李庆浩执筒，《丛林有情狼》的编剧Chris Denk提供剧本创意，2011年荣获学院短片记录音乐赏的好莱坞新人迈克&middot;叶泽斯基担纲音乐创作，更有来自好莱坞的制作班底加盟，实力不容小觑。<br />
	<br />
	　　影片尚未在韩国本土上映，其海外版权已卖至西班牙、意大利在内的15个国家，总计拷贝高达200万，从而再次印证韩国动画影片在外埠的优质口碑，巩固了韩国动画人自《鸡妈鸭仔》成功后的自信心与国际市场开拓精神。<br />
	<br />
	　　影片在人物设计和故事编排上也煞费了一番苦心，特别是勾勒了一只罕见的的白毛考拉&mdash;&mdash;约翰尼。正是由于外貌上的&ldquo;小众&rdquo;，约翰尼的内心世界相当敏感，并且缺乏自信，总怀疑自己是考拉群中的异类。因为一次偶然的义举，约翰尼成为受人崇拜的英雄，内心也日渐强大，并最终获得了灵魂上的升华。影片以浩瀚的澳洲大自然为背景，除了壮丽的风景，还涉及到袋鼠、袋熊、澳洲野犬等当地特有的动物，角色形象相当丰富，色彩渲染也极具土著风，异国强调一览无遗。<br />
	<br />
	　　幕后配音方面，片方也做了独具匠心的安排。由于影片的受众群主要集中在青少年中，因此特别请来流行组合SHINee中最受欢迎的泰民为主角约翰尼配音，一方面展现充满霸气的嗓音，一方面又流露出小心谨慎的内向性格。女子人气组合&ldquo;少女时代&rdquo;中的Sunny亦被选中为片中卓越的美女战士米兰达配音，彰显英姿飒爽的坚强气质。著名的甘草演员尹多勋为约翰尼的贪心鬼经纪人哈密逊配音，语调特别，在声音张力方面给了泰民和Sunny很多启迪<br />
	<br />
	　　&ldquo;英雄考拉&rdquo;约翰尼：由于白色皮毛的特殊外貌曾一度自卑，缺乏自信，偶然一次路见不平拔刀相助后，蹿红为英雄人物，获得了大家的爱戴。<br />
	<br />
	　　&ldquo;美女战士&rdquo;米兰达：拥有可人面孔和坚强性格，更身怀出神入化飞镖绝技，是约翰尼的得力助手兼红颜知己。<br />
	<br />
	　　贪婪鬼经理人哈密逊：自称业内高手，其实过气多时。处心积虑通过打造&ldquo;英雄考拉&rdquo;的形象成为嘉年华的主宰。<br />
	<br />
	　　澳洲大自然的&ldquo;土地爷&rdquo;昆德：在与鳄鱼普格一党的斗争中失去一条腿。为了捍卫家园和平，加入约翰尼一行，成为其重要的参谋。<br />
	<br />
	　　被绑架的夏洛克：米兰达的弟弟，崇拜英雄约翰尼，某日被鳄鱼普格一伙儿绑架。<br />
	<br />
	　　食神&mdash;&mdash;摄影师黑金斯：非常好胃口，是哈密逊的跟班。<br />
	<br />
	　　鳄鱼普格：多血质的万恶凶徒，易暴躁，拥有凶狠獠牙，欲意独吞澳洲大自然的丰美物资。</p>
<p>
	<img alt="" src="http://img165.poco.cn/mypoco/myphoto/20120307/16/64486803201203071626453178158168664_001.jpg" /><br />
	<img alt="" src="http://img165.poco.cn/mypoco/myphoto/20120307/16/64486803201203071626453178158168664_000.jpg" /><br />
	&nbsp;</p>
<p>
	[下载地址]： &nbsp;<img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" /></p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2975/飘花电影piaohua.com考拉小子：英雄的诞生DVD中字.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2975/飘花电影piaohua.com考拉小子：英雄的诞生DVD中字.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1B5040-3X47.jpg{/dede:field}
