{dede:field name='keywords'}爱到房倒屋塌/我的野蛮网友BD128{/dede:field}
{dede:field name='description'}爱到房倒屋塌/我的野蛮网友BD1280高清迅雷下载、免费下载，爱到房倒屋塌/我的野蛮网友BD1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}爱到房倒屋塌/我的野蛮网友BD1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-12{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://218.26.89.158/up/files/82/bringing.jpg" style="width: 577px; height: 718px" /></p>
<p>
	◎译　　名　爱到房倒屋塌/我的野蛮网友<br />
	◎片　　名　Bringing Down the House<br />
	◎年　　代　2003<br />
	◎国　　家　美国<br />
	◎类　　别　喜剧<br />
	◎语　　言　英语<br />
	◎字　　幕　中文<br />
	◎IMDB评分 &nbsp;5.4/10 (19,975 votes)<br />
	◎IMDB链接 &nbsp;<a href="http://www.imdb.com/title/tt0305669/" target="_blank">http://www.imdb.com/title/tt0305669/</a><br />
	◎片　　长　1h:45m:21s<br />
	◎导　　演　亚当&middot;山克曼 Adam Shankman<br />
	◎主　　演　史蒂夫&middot;马丁 Steve Martin .... Peter Sanderson<br />
	　　　　　　奎恩&middot;拉提法 Queen Latifah .... Charlene Morton<br />
	　　　　　　尤金&middot;列维 Eugene Levy .... Howie Rottman<br />
	　　　　　　琼&middot;普莱怀特 Joan Plowright .... Mrs. Arness<br />
	　　　　　　基恩&middot;斯马特 Jean Smart .... Kate Sanderson<br />
	　　　　　　凯布利&middot;布朗 Kimberly J. Brown .... Sarah Sanderson<br />
	　　　　　　安格斯&middot;琼斯 Angus T. Jones .... Georgey Sanderson<br />
	　　　　　　米茜&middot;派勒 Missi Pyle .... Ashley<br />
	　　　　　　麦克尔&middot;罗森巴尔 Michael Rosenbaum .... Todd Gendler<br />
	　　　　　　贝蒂&middot;怀特 Betty White .... Mrs. Kline<br />
	　　　　　　斯蒂夫&middot;哈里斯 Steve Harris .... Widow<br />
	　　　　　　<br />
	<br />
	◎简　　介<br />
	<br />
	　　 彼德&middot;森德逊是一位格守道德观念、处事严谨的律师，对工作非常认真，可以说是个工作狂，但因为做事为人太过正直古板，弄得自己的精神和生活都常常处于紧张的状态，手头更是往往非常拮据，勉强过着中产阶级的生活。但彼德&middot;森德逊十分顾家，也一直很爱自己的妻子凯特，对于他来说，能够拥有稳定的工作和波澜不惊的家庭生活就是最幸福的事情了。可是，最终他的妻子还是离开了他。彼德一直想不通，他到底做错了什么使妻子要离他而去。与此同时，执著的彼德&middot;森德逊还在继续寻找着他追求的人生的真谛。<br />
	<br />
	　　 徘徊于痛苦和无奈之中的彼德&middot;森德逊，继续过着自己清贫的单身工作狂生活，直到有一天，他在网上结识了&ldquo;女王&rdquo;&mdash;&mdash;一个头脑敏捷、思维火爆、多才多智、魅力无比的女律师，与她在网上聊天成了彼德&middot;森德逊生活中无法或缺的一部分。很快，彼德&middot;森德逊堕入了爱河。<br />
	<br />
	　　 这天，彼德&middot;森德逊精心做好了一切准备，迎接他的网络情人的到来。但是，当他打开家门和她面对面时，眼前的那个又黑又胖的女人让彼德&middot;森德逊惊呆了。在短暂的接触之后，彼德&middot;森德逊很快发现，她完全没有了网聊时的那般文雅，不但没有修养，更不是什么&ldquo;常青藤联盟大学&rdquo;的毕业生，当然更不是一个女律师。<br />
	<br />
	　　 事实上，这位名女子叫莎琳&middot;莫顿，是在一个在逃的女犯人，她声称自己是清白的，并希望彼德&middot;森德逊能帮助自己恢复名誉。<br />
	<br />
	　　 而此时的彼德&middot;森德逊早已是处于崩溃的边缘，他不想跟这个大嗓门、令人讨厌的女人有任何关系，更不想帮她任何忙。可问题是，死心塌地地跟着彼德&middot;森德逊的莎琳却无论如何也不肯离开，她打定主意要缠着彼德&middot;森德逊不放，直到他帮自己洗清了罪名。<br />
	<br />
	　　 莎琳的出现彻底将彼德&middot;森德逊舒适平静的生活闹了个底朝天，不仅将他为让前妻回心转意所做的一切努力化为乌有，还使他错过了拥有10亿家产的富婆阿妮斯夫人的追求。<br />
	<br />
	　　 然而，在许多超乎想象的事发生后，彼德&middot;森德逊和莎琳这看起来格格不入、不可能的一对，不知不觉中却似乎已经成了彼此生活里的一部分，直到他们最后令人无法意料地爱得房倒屋塌&hellip;&hellip;<br />
	<br />
	◎幕后制作<br />
	<br />
	　　 本片导演是曾执导过浪漫爱情剧《婚礼操办者》的亚当&middot;山克曼。有&ldquo;白头笑星&rdquo;之称的斯蒂夫&middot;马丁在片中饰演刻板、循规蹈矩的中产阶级男子。以在剧团中表演丑角入行的斯蒂夫&middot;马丁近年来不仅在喜剧片的表演上精益求精，更凭借一张机敏且充满幽默感的巧嘴成为热门电视节目&ldquo;周六夜现场&rdquo;的常客，也曾多次受邀主持奥斯卡电影奖与格莱美音乐奖颁奖典礼。2000年更迎来他事业的新高峰，由于风格另类而没有一部作品正式获得过奥斯卡承认的他，终于获得美国电影学院的奥斯卡终身成就奖(喜剧)。<br />
	<br />
	　　 在片中与斯蒂夫&middot;马丁演对手戏的奎恩&middot;拉提法是90年代最重量级的著名黑人饶舌歌手之一，但在看过这部影片之后，你会发现她的演技与她的音乐感染力相比，并不逊色。其实早在2000年，她就因在歌舞片《芝加哥》中饰演监狱女主管而声名大噪，并且获得了当年奥斯卡的最佳女配角提名。</p>
<p>
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120512/02/62564813201205120235223616912334546_003.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120512/02/62564813201205120235223616912334546_002.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120512/02/62564813201205120235223616912334546_001.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120512/02/62564813201205120235223616912334546_000.jpg" style="width: 720px; height: 405px" /><br />
	<br />
	&nbsp;</p>
<p>
	【下载地址】</p>
<table bgcolor="#0099cc" border="0" cellpadding="10" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.net" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy125:piaohua@dy125.piaohua.com:8055/飘花电影piaohua.com我的野蛮网友BD中字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:8055/飘花电影piaohua.com我的野蛮网友BD中字1280高清.rmvb</a></td>
		</tr>
		<tr>
		</tr>
	</tbody>
</table>
<br />{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15K5H0-1c49.jpg{/dede:field}
