{dede:field name='keywords'}黑暗面/镜中人BD1280高清迅雷下{/dede:field}
{dede:field name='description'}黑暗面/镜中人BD1280高清迅雷下载、免费下载，黑暗面/镜中人BD1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}黑暗面/镜中人BD1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-25{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="/uploads/allimg/c120525/133O0a1Z-205042.jpg" style="width: 650px; height: 942px" /><img alt="" src="/uploads/allimg/c120525/133O0a2W30-215H6.jpg" style="width: 650px; height: 929px" /></p>
<p>
	【影片原名】The Hidden Face / La cara oculta<br />
	【中文译名】黑暗面 / 镜中人<br />
	【出品公司】Fox International Productions (FIP)<br />
	【出品年代】2011 年<br />
	【上映日期】2011年9月16日 &nbsp; 西班牙<br />
	【IMDB链接】http://www.imdb.com/title/tt1772250<br />
	【IMDB评分】6.6/10 (1,022 votes)<br />
	【官方网站】www.lacaraoculta.es<br />
	【国　　家】哥伦比亚 &nbsp;/ &nbsp;西班牙<br />
	【类　　别】惊悚<br />
	【导　　演】安德雷斯&middot;拜兹 &nbsp; Andres Baiz &nbsp;<br />
	【主　　演】玛蒂娜&middot;加西亚 &nbsp; Martina Garc&iacute;a &nbsp; ....Fabiana<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 克拉拉&middot;拉戈 &nbsp; Clara Lago &nbsp; ....Bel&eacute;n<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 奎姆&middot;古铁雷兹 &nbsp; Quim Guti&eacute;rrez &nbsp; ....Adri&aacute;n<br />
	<br />
	【内容简介】<br />
	<br />
	&nbsp; &nbsp; 哥伦比亚与西班牙合拍的《黑暗面》是去年颇受好评的一部心理惊悚片，它的题材在常常描写毒品犯罪、卖淫这些社会内容的哥伦比亚电影中相当少见。影片由安德雷斯&middot;拜兹执导，这位新锐导演2007年的处女作《撒旦》一鸣惊人，在波哥大（哥伦比亚首府）电影节上摘得了当年最佳哥伦比亚电影。<br />
	<br />
	　　《黑暗面》的故事发生在波哥大一栋神秘的公寓。出演过《深蓝即是黑》的西班牙男星奎姆&middot;古铁雷兹饰演一名交响乐团指挥家亚德里安，一天，他的女友贝伦（克拉拉&middot;拉高《卡罗尔的旅程》）忽然&ldquo;不辞而被&rdquo;。没有多久，亚德里安就有了新的恋人法比安娜（玛蒂娜&middot;加西亚），他们的公寓却频频出现&ldquo;闹鬼&rdquo;症状，将法比安娜渐渐逼疯。其实，这一切的秘密都在公寓过去的主人所建造的密室之中，而密室的入口是一面镜子&hellip;&hellip;（如果不怕剧透的话请看下面的英文预告片）影片前五十分钟仿佛是一部灵异恐怖片，结局却笔锋一转，抖出一个让人意想不到却又在情理之中的结局。不得不说，安德雷斯&middot;拜兹是有野心的故事讲述者，而《黑暗面》也足够让你记住他。</p>
<p>
	&nbsp;&nbsp;=======原声预告片欣赏=======<br />
	<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,40,0" height="490" width="630"><param name="quality" value="high" /><param name="movie" value="/uploads/allimg/c120525/133O0a3V40-22YO.swf" /><param name="quality" value="high" /><param name="movie" value="/uploads/allimg/c120525/133O0a3V40-22YO.swf" /><embed height="490" pluginspage="http://www.macromedia.com/go/getflashplayer" quality="high" src="/uploads/allimg/c120525/133O0a3V40-22YO.swf" type="application/x-shockwave-flash" width="630"></embed></object></p>
<p>
	<img alt="" src="/uploads/allimg/c120525/133O0a3Y50-231218.jpg" style="width: 720px; height: 405px" /><img alt="" src="/uploads/allimg/c120525/133O0a3c0-245164.jpg" style="width: 720px; height: 405px" /><img alt="" src="/uploads/allimg/c120525/133O0a40T0-25P96.jpg" style="width: 720px; height: 405px" /><img alt="" src="/uploads/allimg/c120525/133O0a41G0-263156.jpg" style="width: 720px; height: 405px" /><br />
	&nbsp;</p>
<p>
	【下载地址】</p>
<table bgcolor="#0099cc" border="0" cellpadding="10" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：http://www.xiaobajie.com</td>
		</tr>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy125:piaohua@dy125.piaohua.com:8099/飘花电影piaohua.com黑暗面BD中字1280高清.rmvb</td>
		</tr>
		<tr>
		</tr>
	</tbody>
</table>
<br />{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O0a42A0-2J2J.jpg{/dede:field}
