{dede:field name='keywords'}拓本HD1280高清迅雷下载，免费下{/dede:field}
{dede:field name='description'}拓本HD1280高清迅雷下载、免费下载，拓本HD1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}拓本HD1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-24{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120523/22/62564813201205232249111398739308259_000.jpg" style="width: 200px; height: 286px" /></p>
<p>
	导演: 周军<br />
	编剧: 周刚<br />
	主演: 王双宝 / 龚娜 / 梁伯年<br />
	类型: 剧情<br />
	制片国家/地区: 中国大陆<br />
	语言: 汉语普通话<br />
	片长: 91分钟<br />
	剧情简介：<br />
	<br />
	　　张万社是个农民工，性格开朗，乐于助人。他每天在城里走街串巷以回收废品为业；张万社的儿子张俊文是在校大专生，放寒假时专心给父亲帮忙干活。独居老人吴天成是个有一定造诣的书法爱好者，他有一本珍贵的明代拓本。还有个把月就要过年了，吴天成让新来的保姆小卉把清理过的两摞旧报纸和杂志卖给收废品的，然而他误将拓本夹杂在其中随旧报纸杂志被张万社收走了。张俊文在整理旧报纸时发现了拓本，他觉得是个值钱的东西，收起来并到古玩城询价，胡老板告诉他拓本值十万。吴天成得知拓本被当旧报纸和杂志卖给收废品的了，心里火烧火燎，懊恼...<br />
	<br />
	<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120523/22/62564813201205232216413548917918250_002.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120523/22/62564813201205232216413548917918250_001.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120523/22/62564813201205232216413548917918250_000.jpg" style="width: 720px; height: 405px" /></p>
<p>
	【下载地址】</p>
<table bgcolor="#0099cc" border="0" cellpadding="10" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaobajie.com" target="_blank">http://www.xiaobajie.com</a></td>
		</tr>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy125:piaohua@dy125.piaohua.com:8095/飘花电影piaohua.com拓本HD国语中字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:8095/飘花电影piaohua.com拓本HD国语中字1280高清.rmvb</a></td>
		</tr>
		<tr>
		</tr>
	</tbody>
</table>
<br />{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O14aVF-14G1.jpg{/dede:field}
