<?php
$z[0]=Array("field","海底总动员/海底奇兵BD英国台粤",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","海底总动员/海底奇兵BD英国台粤四语1280高清迅雷下载、免费下载，海底总动员/海底奇兵BD英国台粤四语1280高清Gvod高清在线播放，剧情介绍等。",72,248);
$z[1][4]['name']="description";
$z[2]=Array("field","海底总动员/海底奇兵BD英国台粤四语1280高清",250,329);
$z[2][4]['name']="title";
$z[3]=Array("field","",331,370);
$z[3][4]['name']="writer";
$z[4]=Array("field","",372,411);
$z[4][4]['name']="source";
$z[5]=Array("field","2012-02-11",413,463);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",465,502);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://dy241:xiaobajie@222.187.221.241:2017/小八戒电影xiaobajie.com海底总动员英国台粤四语BD1280高清.mkv\" target=\"_blank",504,661);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MQ101c0-19145.jpg",663,746);
$z[8][4]['name']="litpic";

?>