{dede:field name='keywords'}理性与感性作品音乐会DVD中字李{/dede:field}
{dede:field name='description'}理性与感性作品音乐会DVD中字李宗盛迅雷下载、免费下载，理性与感性作品音乐会DVD中字李宗盛Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}理性与感性作品音乐会DVD中字李宗盛{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-07-20{/dede:field}
{dede:field name='body'}<p>
	<img alt="" height="844" src="/uploads/allimg/c120524/133N4OO2F-3FG.jpg" width="750" /></p>
<p>
	一首歌往往是伴随着人生的某个阶段。</p>
<p>
	许多年后，再听起时，总会不自主的想起&mdash;&mdash;当年听这着歌的时候我们在做些什么。</p>
<p>
	但是听老李的歌不同。</p>
<p>
	正如张艾嘉开场时所说&mdash;&mdash;每个人心中都有一首李宗盛。</p>
<p>
	在听他的歌时，我们也总会想起当年的某些时光。</p>
<p>
	但并不是听这些歌的那段，而是被这歌写中自身经历的那段。</p>
<p>
	这种感觉很奇妙。</p>
<p>
	我们总能在他的歌中找到自己的影子。</p>
<p>
	这是一场打着感性与理性幌子名副其实感性的一塌的音乐会。</p>
<p>
	《明明白白我的心》中向静茹吐露的心声</p>
<p>
	《梦醒时分》后在冗长的伴乐中屏幕上有他手写给淑桦的问候</p>
<p>
	《领悟》后他对辛晓琪的致敬</p>
<p>
	《铿锵玫瑰》前简单的对自己与SANDY之间的剖析</p>
<p>
	&hellip;&hellip;&hellip;&hellip;</p>
<p>
	他把所有的嘉宾逐个唱哭后</p>
<p>
	在终曲《爱的代价》哽咽断唱</p>
<p>
	看着老李在台上如老豆般唱着人生百味，心里很踏实。</p>
<p>
	只有，只有一点微感酸涩。</p>
<p>
	下半场《当爱已成往事》静茹跟他合作的时候，他脸上闪过的隐隐一丝&hellip;&hellip;我知怎么去形容，反正不是释怀的表情。</p>
<p>
	这是他和SANDY的经典，只是再没能重现。</p>
<p>
	我想他对此也是有着遗憾的吧&hellip;&hellip;<br />
	&nbsp;</p>
<p>
	专辑曲目:</p>

<p>
	DVD 1</p>
<p>
	01. 生命中的精灵<br />
	02. 风柜来的人+17岁女生的温柔<br />
	03. 没有人知道+爱情少尉<br />
	04. 如果你要离去<br />
	05. 寂寞难耐<br />
	06. 鬼迷心窍<br />
	07. 我终于失去了你<br />
	08. 明明白白我的心<br />
	09. 问<br />
	10. 梦醒时分<br />
	11. 领悟<br />
	12. 阴天<br />
	13. 铿锵玫瑰<br />
	14. 希望<br />
	15. 和自己赛跑的人<br />
	16. 凡人歌</p>
<p>
	DVD 2</p>
<p>
	01. 一个人<br />
	02. 爱情有什么道理<br />
	03. 你像个孩子似的<br />
	04. 飞<br />
	05. 阿宗三件事<br />
	06. 因为寂寞<br />
	07. 我是一只小小鸟<br />
	08. 我是真的爱你<br />
	09. 不必在乎我是谁<br />
	10. 当爱已成往事<br />
	11. 为你我受冷风吹<br />
	12. 诱惑的街<br />
	13. 十二楼<br />
	14. 伤心地铁<br />
	15. 远行<br />
	16. 真心英雄<br />
	17. 爱的代价</p>

<p>
	<img alt="" src="/uploads/allimg/c120524/133N4OQ610-492C.jpg" /></p>
<p>
	[下载地址]： &nbsp;<img border="0" src="/uploads/allimg/c120524/133N2Z4FF-102231.jpg" />
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:1056/飘花电影piaohua.com理性与感性作品音乐会DVD中字.rmvb</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120524/133N4OR3P-53D1.jpg{/dede:field}
