{dede:field name='keywords'}愿为你摘星揽月日韩剧12迅雷下载{/dede:field}
{dede:field name='description'}愿为你摘星揽月日韩剧12迅雷下载、免费下载，愿为你摘星揽月日韩剧12Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}愿为你摘星揽月日韩剧12{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-25{/dede:field}
{dede:field name='body'}<p>
	&nbsp;<img src="http://img.funshion.com/attachment/new_images/2012/05-10/32694648_1336639616_813.jpg" width="650" /></p>
<p>
	&nbsp;<img alt="" height="410" src="http://img.album.pchome.net/02/25/03/37/27e1d80d8431566f6f1806648a180c6b.jpg" width="600" /></p>
<p>
	[中文剧名]：愿为你摘星揽月<br />
	[韩文剧名]：&#48324;&#46020; &#45804;&#46020; &#46384;&#51460;&#44172;<br />
	[导&nbsp;&nbsp;&nbsp; 演]：全成勋<br />
	[编&nbsp;&nbsp;&nbsp; 剧]：洪英熙（代表作：《《美丽时节》《那女人的选择》《人生画报》《纯粹》《色彩》）<br />
	[主&nbsp;&nbsp;&nbsp; 演]：徐智慧 赵东赫 高世元 文宝玲<br />
	[放送机构]：韩国KBS<br />
	[类&nbsp;&nbsp;&nbsp; 型]：KBS1晚间日播剧<br />
	[播出时间]：2012年05月7日起每周一至周五晚8点25分（北京时间7点25分）<br />
	[集&nbsp;&nbsp;&nbsp; 数]：待定<br />
	[接档剧集]：只有你<br />
	[官方网站]: <a href="http://www.bluemv.com" title="电影下载">http://www.bluemv.com</a><br />
	[剧情简介]：因为家人之间的矛盾而各奔东西，最终发现在遭遇困难的时候守护自己的还是家族。<br />
	&nbsp;</p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.netftp//dy44:piaohua@dy44.piaohua.com:3125/" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3395/飘花电影piaohua.com愿为你摘星揽月EP01.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3395/飘花电影piaohua.com愿为你摘星揽月EP01.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3395/飘花电影piaohua.com愿为你摘星揽月EP02.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3395/飘花电影piaohua.com愿为你摘星揽月EP02.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3404/飘花电影piaohua.com愿为你摘星揽月EP03.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3404/飘花电影piaohua.com愿为你摘星揽月EP03.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3406/飘花电影piaohua.com愿为你摘星揽月EP04.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3406/飘花电影piaohua.com愿为你摘星揽月EP04.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3410/飘花电影piaohua.com愿为你摘星揽月EP05.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3410/飘花电影piaohua.com愿为你摘星揽月EP05.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3435/飘花电影piaohua.com愿为你摘星揽月EP06.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3435/飘花电影piaohua.com愿为你摘星揽月EP06.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3438/飘花电影piaohua.com愿为你摘星揽月EP07.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3438/飘花电影piaohua.com愿为你摘星揽月EP07.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3454/飘花电影piaohua.com愿为你摘星揽月EP08.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3454/飘花电影piaohua.com愿为你摘星揽月EP08.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3461/飘花电影piaohua.com愿为你摘星揽月EP09.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3461/飘花电影piaohua.com愿为你摘星揽月EP09.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3463/飘花电影piaohua.com愿为你摘星揽月EP10.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3463/飘花电影piaohua.com愿为你摘星揽月EP10.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3483/飘花电影piaohua.com愿为你摘星揽月EP11.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3483/飘花电影piaohua.com愿为你摘星揽月EP11.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3491/飘花电影piaohua.com愿为你摘星揽月EP12.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3491/飘花电影piaohua.com愿为你摘星揽月EP12.rmvb</a></td>
		</tr>
	</tbody>
</table>
<p>
	&nbsp;</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1A920-33R1.jpg{/dede:field}
