{dede:field name='keywords'}美女与野兽BD英国粤三语中英双字{/dede:field}
{dede:field name='description'}美女与野兽BD英国粤三语中英双字1024/1280高清迅雷下载、免费下载，美女与野兽BD英国粤三语中英双字1024/1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}美女与野兽BD英国粤三语中英双字1024/1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-04-09{/dede:field}
{dede:field name='body'}<p>
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://cdn3a.dvdempire.org/products/02/1531502h.jpg');" src="http://cdn3a.dvdempire.org/products/02/1531502h.jpg" /><br />
	<br />
	◎译　　名　美女与野兽<br />
	◎片　　名　Beauty And The Beast<br />
	◎年　　代　1991<br />
	◎国　　家　美国<br />
	◎类　　别　动画/家庭/幻想/音乐/爱情<br />
	◎语　　言　英语/普通话/粤语<br />
	◎字　　幕　中英字幕<br />
	◎IMDB评分&nbsp; 8.0/10 (69,181 votes)<br />
	◎文件格式　x264 + AAC<br />
	◎视频尺寸　1024 x 576<br />
	◎文件大小　1CD<br />
	◎片　　长　1h:31m:44s<br />
	◎导　　演　Gary Trousdale<br />
	　　　　　　Kirk Wise<br />
	◎主　　演　罗杰&middot;艾勒斯 Roger Allers .....story supervisor<br />
	　　　　　　凯利&middot;阿斯博瑞 Kelly Asbury .....story<br />
	　　　　　　Brenda Chapman .....story<br />
	　　　　　　Jeanne-Marie Leprince de Beaumont .....story (uncredited)<br />
	　　　　　　Tom Ellery .....story<br />
	　　　　　　Kevin Harkey .....story<br />
	　　　　　　Robert Lence .....story<br />
	　　　　　　Burny Mattinson .....story<br />
	　　　　　　Brian Pimental .....story<br />
	　　　　　　乔&middot;兰福特 Joe Ranft .....story<br />
	　　　　　　克里斯&middot;桑德斯 Chris Sanders .....story (as Christopher Sanders)<br />
	　　　　　　Bruce Woodside .....story<br />
	　　　　　　Linda Woolverton<br />
	　　　　　　<br />
	◎简　　介<br />
	<br />
	&nbsp; &nbsp; 很久很久以前，村庄内住着一位漂亮善良的姑娘贝儿，她为了解救被野兽囚禁的父亲，被迫与野兽同居于古堡中，他们相处得并不愉快。一次，野兽拼命从狼群中救回贝儿，令彼此间得到了解，野兽渐渐亦变得温柔，二人不但冰释前嫌互相体谅，更互生情愫。<br />
	<br />
	&nbsp; &nbsp; 怎知喜欢贝儿的大坏蛋柏加斯自以为是，突然前来袭击野兽，令其身受重伤，性命危在旦夕。深爱贝儿的野兽要她离去，不过贝儿并没有逃跑，反而<a href="http://www.3edyy.com/" target="_blank">电影下载</a>紧紧与野兽相拥到最后一刻&hellip;&hellip;<br />
	<br />
	◎幕后制作<br />
	　　<br />
	&nbsp; &nbsp; 这是第一部获得奥斯卡最佳影片提名的动画片，也是第一部票房超过一亿美元的动画片。该片为传统故事注入了新的生命，女主角不再出自卖弄纯真或性感的&ldquo;梦露&rdquo;模式，而是一个用知识武装自己、努力掌握自己命运的可爱女强人。1946年的法国原版乃不朽经典。1997年迪斯尼又发行了录影带《美女与野兽：贝儿的心愿》(Beauty and the Beast: The Enchanted Christmas)。<br />
	&nbsp;</p>
<p>
	【电影截图】：<br />
	<br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://photo5.zxip.com/albums5/folder10/7895/20101101143827/2010112513311568.jpg');" src="http://photo5.zxip.com/albums5/folder10/7895/20101101143827/2010112513311568.jpg" />&nbsp;<br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://photo5.zxip.com/albums5/folder10/7895/20101101143827/2010112513311361.jpg');" src="http://photo5.zxip.com/albums5/folder10/7895/20101101143827/2010112513311361.jpg" /><br />
	[下载地址]：<img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" /></p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://3e:3e@d3.3edyy.com:121/【3E电影院www.eee4.org】美女与野兽.1024x576.英国粤三语.中英字幕.mkv" target="_blank">ftp://3e:3e@d3.3edyy.com:121/【3E电影院www.eee4.org】美女与野兽.1024x576.英国粤三语.中英字幕.mkv</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3181/飘花电影piaohua.com美女与野兽BD中英双字1280高清.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3181/飘花电影piaohua.com美女与野兽BD中英双字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15T52Z-3V03.jpg{/dede:field}
