{dede:field name='keywords'}史酷比：鬼龙传说BD中英双字1280{/dede:field}
{dede:field name='description'}史酷比：鬼龙传说BD中英双字1280高清迅雷下载、免费下载，史酷比：鬼龙传说BD中英双字1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}史酷比：鬼龙传说BD中英双字1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-10-24{/dede:field}
{dede:field name='body'}<p>
	&nbsp;<img border="0" src="/uploads/allimg/c120525/133O04531930-13524.jpg" style="max-width: 750px; max-height: 750px" /></p>
<p>
	◎译　　名　史酷比：鬼龙传说/史酷比<br />
	◎片　　名　Scooby Doo Legend Of The Phantosaur<br />
	◎年　　代　2011<br />
	◎国　　家　美国<br />
	◎类　　别　动画<br />
	◎语　　言　英语<br />
	◎字　　幕　中英双字幕<br />
	◎IMDB评分 N/A<br />
	◎文件格式　Rmvb<br />
	◎视频尺寸　640 x 360<br />
	◎文件大小　304MB<br />
	◎片　　长　75 Mins<br />
	◎导　　演　Ethan Spaulding<br />
	◎主　　演　Frank Welker ...Scooby-Doo / Fred Jones / Bikers (voice)<br />
	　　　　　　Mindy Cohn ...Velma Dinkley (voice)<br />
	　　　　　　Grey DeLisle ...Daphne Blake (voice)<br />
	　　　　　　Matthew Lillard ...Shaggy Rogers / Shaky Joe (voice)<br />
	　　　　　　Cathy Cavadini ... Faith (voice)<br />
	　　　　　　Sumalee Montano ... (voice)<br />
	　　　　　　John Di Maggio ... Friz / GPS / Bikers (voice)<br />
	　　　　　　Vyvan Pham ... Emily (voice)<br />
	　　　　　　Michael Gough ... Mr. Babbit / Blair / Grad Student #1 / Bikers (voice)<br />
	　　　　　　Matthew Gray Gubler ... Winsor (voice)<br />
	　　　　　　Finola Hughes ... Professor Svankmajer (voice)<br />
	　　　　　　Colleen O&#39;Shaughnessey ... Cleo (voice)<br />
	　　　　　　Maulik Pancholy ... Doctor (voice)</p>
<p>
	◎简　　介　</p>
<p>
	　　史酷比和他的朋友们在一个又温泉的地方度假。但在这个极度放松的温泉里，发生了一个史前恐慌的事。史酷比和他的朋友们发现的可怕鬼龙。据说这是一个古老的传说。在神密地沙漠洞穴中为了保护宝藏。而设计的魔咒。史酷比为了保护这些宝藏不被那些五颜六色的犯罪嫌疑人抢走。他充当英雄的角色。对那些贪婪的企业投资者和过度热心的科学家们来说，史酷比是一个障碍，想出一切办法要除掉他。他们成功了吗？还是史酷比成了英雄？</p>
<p>
	◎影片截图</p>
<p>
	&nbsp;<img border="0" src="/uploads/allimg/c120525/133O04534110-2L28.jpg" style="max-width: 750px; max-height: 750px" /></p>
<p>
	&nbsp;<img border="0" src="/uploads/allimg/c120525/133O04534H0-32034.jpg" style="max-width: 750px; max-height: 750px" /></p>
<p>
	<img border="0" src="/uploads/allimg/c120525/133O045352P-45614.jpg" style="max-width: 750px; max-height: 750px" /></p>
<p>
	<img alt="" height="337" src="/uploads/allimg/c120525/133O04535V0-560P.jpg" style="cursor: pointer" width="600" /><br />
	<img alt="" height="337" src="/uploads/allimg/c120525/133O0453B50-62221.jpg" style="cursor: pointer" width="600" /><br />
	<img alt="" height="337" src="/uploads/allimg/c120525/133O0453IF-Ka4.jpg" style="cursor: pointer" width="600" /><br />
	&nbsp;</p>
<p>
	[下载地址]： &nbsp;<img border="0" src="/uploads/allimg/c120524/133N2Z4FF-102231.jpg" /></p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				&nbsp;ftp://dy44:piaohua@dy44.piaohua.com:1517/飘花电影piaohua.com史酷比：鬼龙传说DVD中英双字.rmvb</td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				&nbsp;ftp://dy44:piaohua@dy44.piaohua.com:1890/飘花电影piaohua.com史酷比：鬼龙传说1280高清.rmvb</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O0453Q30-S151.jpg{/dede:field}
