{dede:field name='keywords'}感人MTV迅雷下载，免费下载，Gvo{/dede:field}
{dede:field name='description'}感人MTV迅雷下载、免费下载，感人MTVGvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}感人MTV{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2006-09-14{/dede:field}
{dede:field name='body'}http://fmtv.uying.com/日韩MTV/审成勋_感人MV.wmv{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120524/133N353DD0-2G248.gif{/dede:field}
