<?php
$z[0]=Array("field","世界尽头的奇遇【中英双字[880分",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","世界尽头的奇遇【中英双字[880分辨率]】迅雷下载、免费下载，世界尽头的奇遇【中英双字[880分辨率]】Gvod高清在线播放，剧情介绍等。",73,241);
$z[1][4]['name']="description";
$z[2]=Array("field","世界尽头的奇遇【中英双字[880分辨率]】",243,318);
$z[2][4]['name']="title";
$z[3]=Array("field","",320,359);
$z[3][4]['name']="writer";
$z[4]=Array("field","",361,400);
$z[4][4]['name']="source";
$z[5]=Array("field","2012-05-22",402,452);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",454,491);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://e39:e39@xl2.eee4.com:9024/[3E电影站www.eee4.com]世界尽头的奇遇.rmvb\" target=\"_blank",493,621);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MP4G5Z-24195.jpg",623,705);
$z[8][4]['name']="litpic";

?>