{dede:field name='keywords'}千年女优BD1280高清中字迅雷下载{/dede:field}
{dede:field name='description'}千年女优BD1280高清中字迅雷下载、免费下载，千年女优BD1280高清中字Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}千年女优BD1280高清中字{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-24{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120525/00/17870980201205242359441611291414465_000.jpg" /></p>
<p>
	中文名: 千年女优<br />
	英文名: Millennium Actress<br />
	导演: 今敏<br />
	编剧: 村井贞行 / 今敏<br />
	主演: 小山茉美 / 饭冢昭三 / 折笠富美子 / 庄司美代子 / 小野坂昌也<br />
	类型: 动画 / 剧情 / 爱情<br />
	制片国家/地区: 日本<br />
	语言: 日语<br />
	上映日期: 2001-09-14(日本)<br />
	片长: 87 分钟<br />
	又名: Millennium Actress<br />
	IMDb链接: tt0291350<br />
	<br />
	千年**的剧情简介 &middot; &middot; &middot; &middot; &middot; &middot;<br />
	<br />
	　　60岁的立花源也和28岁的摄影师井田恭二不远千里跋山涉水上门去拜访隐居了三十年的一代影星藤原千代子，为了给她拍摄一生自传的纪录片。款款前来的千代子虽然已界75岁高龄，但仍然优雅美丽，左眼下标志性的小痣也仍然俏皮。立花双手递上一把钥匙，千代子深受震动，称这把钥匙是开启一个秘密的关键，当年她不慎丢失，今日竟还能再回手中。千代子的思绪飞到老远。<br />
	　　1926年9月1日，藤原千代子呱呱坠地，水灵清秀的她16岁就被星探发掘，然而直到遇上一个画家，她救他于乱世中，藏于自家仓库内，他赠她一把钥匙，说这是开启秘密的关键，并承诺再与她重逢时带她去看北海道的雪。然而次日千代子放学归家时画家已经因为逃开追捕逃离远去。<br />
	　　千代子自此进入电影圈，只因为画家最后说他会去满洲作战，而第一部电影承诺会去满洲取景。从此千代子的银幕生涯拉开，拍摄了代表日本战国、幕府、大正及昭和等四个不同时期...</p>
<p>
	<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120525/00/17870980201205242359441611291414465_004.jpg" /><br />
	<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120525/00/17870980201205242359441611291414465_003.jpg" /><br />
	<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120525/00/17870980201205242359441611291414465_002.jpg" style="width: 640px; height: 360px" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaobajie.com" target="_blank">http://www.xiaobajie.com</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy241:piaohua@117.41.229.29:2037/飘花电影piaohua.com千年女优BD1280高清中字.rmvb">ftp://dy241:piaohua@117.41.229.29:2037/飘花电影piaohua.com千年女优BD1280高清中字.rmvb</a></td>
		</tr>
	</tbody>
</table>
<p>
	&nbsp;</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1BK150-55c0.jpg{/dede:field}
