{dede:field name='keywords'}刘德华中国巡回演唱会-上海【128{/dede:field}
{dede:field name='description'}刘德华中国巡回演唱会-上海【1280X720无水印高清版】迅雷下载、免费下载，刘德华中国巡回演唱会-上海【1280X720无水印高清版】Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}刘德华中国巡回演唱会-上海【1280X720无水印高清版】{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2009-02-19{/dede:field}
{dede:field name='body'}<P><IMG onmouseover="function anonymous()&#13;&#10;{&#13;&#10;function anonymous()&#13;&#10;{&#13;&#10;attachimginfo(this, 'attach_100501', 1);attachimg(this, 'mouseover')&#13;&#10;}&#13;&#10;}" onmouseout="function anonymous()&#13;&#10;{&#13;&#10;function anonymous()&#13;&#10;{&#13;&#10;attachimginfo(this, 'attach_100501', 0, event)&#13;&#10;}&#13;&#10;}" src="/uploads/allimg/c120524/133N42630450-13NN.jpg" onload="attachimg(this, 'load')" border=0> <BR></P>
<P>《刘德华中国巡回演唱会-上海》1280X720无水印高清晰版<BR><BR>&nbsp;&nbsp;&nbsp; 华语歌坛天王刘德华，2007年8月于上海举行多场的《刘德华中国巡回演唱会-上海》以气势恢宏而著称，由一流的制作团队包办，呈现出完美的舞台、音响和灯光效果。刘德华的歌曲深入人心，演唱会以国语歌曲为主，快慢歌各半。《刘德华中国巡回演唱会.上海》电影下载以Blu-ray蓝光影碟发行，以至尊级高清系统摄制，碟内收录了30多首歌曲，包括了「中国人」、「浪人情歌」、「男人哭吧不是罪」、「谢谢你的爱」、「一」和「太想爱」等，另辑录了中国巡回演唱会制作特辑及幕后花絮。</P>
<DIV class=t_msgfont>延续07-08跨年《Wonderful World演唱会》，刘德华在中国巡回站演唱了经典的歌曲，且表演了令人炫目的舞蹈，为歌迷们带来了巨大的惊喜。 </DIV>
<DIV class=t_msgfont>超越想象的震撼 亲历8万人演唱会<BR>忘情水 / 冰雨 / 笨小孩 / 相思成灾 / 牧笛 / 练习 / 真永远 / 爱你一万年<BR><BR><BR><BR><BR>01. Overture<BR>02. 中國人<BR>03. 浪人情歌<BR>04. 男人哭吧不是罪<BR>05. 謝謝你的愛<BR>06. 霓裳天橋 (音樂)<BR>07. 一<BR>08. 太想愛<BR>09. 冰雨<BR>10. 忘情水<BR>11. 笨小孩<BR>12. 十全十美<BR>13. 超人<BR>14. 今天<BR>15. 心肝寶貝<BR>16. 再說一次&#8231;我愛你<BR>17. 沒有人可以像你<BR>18. 牧笛<BR>19. 來生緣<BR>20. 歸宿<BR>21. 相思成災<BR>22. 愛你一萬年<BR>23. 愛你一萬年Chaser<BR>24. Andox之倒數計時 (音樂)<BR>25. 最受歡迎男歌手<BR>26. 無間道<BR>27. 獨自去偷歡<BR>28. 開心的馬騮<BR>29. 我恨我痴心<BR>30. 我和我追逐的夢<BR>31. 練習<BR>32. 真永遠<BR>33. Everyone is No. 1<BR>34. Everyone is No. 1 Chaser</DIV>
<P><BR>【截图】：可点击</P><IMG src="/uploads/allimg/c120524/133N42631330-143R3.jpg" border=0>&nbsp;<BR><IMG src="/uploads/allimg/c120524/133N42631c0-1534a.jpg" border=0>&nbsp;<BR><IMG src="/uploads/allimg/c120524/133N42632X0-1E411.jpg" border=0>&nbsp;<BR><IMG src="/uploads/allimg/c120524/133N426335F-1II5.jpg" border=0>
<P>2009-02-19 12:35:12 开始连接......<BR>2009-02-19 12:35:12 开始搜索候选资源......<BR>2009-02-19 12:35:12 搜索到22个候选资源<BR>2009-02-19 12:35:12 使用候选资源进行连接......<BR>2009-02-19 12:35:13 搜索到41个候选资源<BR>2009-02-19 12:35:13 使用候选资源进行连接......<BR>2009-02-19 12:35:13 文件创建成功，开始下载数据......<BR>2009-02-19 12:35:16 用户取消下载&nbsp;&nbsp; 本文来自：www.eee4.com</P>（一律使用迅雷下载）<BR>《刘德华中国巡回演唱会-上海》1280X720无水印高清晰版 －来自[www.eee4.com]：<IMG src="/uploads/allimg/c120524/133N2ZL930-142957.jpg" border=0><BR>
<TABLE style="BORDER-RIGHT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; BORDER-BOTTOM: #cccccc 1px dotted" cellSpacing=0 cellPadding=6 width="95%" align=center border=0>
<TBODY>
<TR>
<TD style="WORD-WRAP: break-word" bgColor=#fdfddf>ftp://d92:d92@ftp.eee4.com:1501/[3E电影站www.eee4.com]刘德华中国巡回演唱会·上海.rmvb</TD></TR></TBODY></TABLE>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120524/133N42634410-1T934.jpg{/dede:field}
