{dede:field name='keywords'}黑金BD1280高清迅雷下载，免费下{/dede:field}
{dede:field name='description'}黑金BD1280高清迅雷下载、免费下载，黑金BD1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}黑金BD1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-04-16{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120416/01/62564813201204160112522976813530179_000.jpg" style="width: 650px" /></p>
<p>
	◎译　　名　黑金<br />
	◎片　　名　Black Gold<br />
	◎年　　代　2011<br />
	◎国　　家　法国/意大利 &nbsp;<br />
	◎类　　别　剧情<br />
	◎语　　言　英语<br />
	◎字　　幕　中字<br />
	◎IMDB评分 6.5/10 &nbsp;（726 votes）<br />
	◎IMDB链接 <a href="http://www.imdb.com/title/tt1701210/" target="_blank">http://www.imdb.com/title/tt1701210/</a><br />
	◎文件格式　Bluray<br />
	◎视频尺寸　1280 x 720<br />
	◎文件大小　1.40G</p>
<p>
	◎片　　长　2h 21mn<br />
	◎导　　演　让-雅克&middot;阿诺 &nbsp; Jean Jacques Annaud<br />
	◎主　　演　安东尼奥&middot;班德拉斯 Antonio Banderas &nbsp;....Nassib<br />
	　　　　　　塔哈&middot;拉希姆 Tahar Rahim &nbsp;....Prince Auda<br />
	　　　　　　芙蕾达&middot;平托 Freida Pinto &nbsp;....Princess Lallah<br />
	　　　　　　马克&middot;斯特朗 Mark Strong &nbsp;....Amar<br />
	　　　　　　里兹&middot;阿迈德 Riz Ahmed &nbsp;....Ali<br />
	　　　　　　克里&middot;约翰逊 Corey Johnson &nbsp;....Thurkettle<br />
	　　　　　　莉亚&middot;科贝德 Liya Kebede &nbsp;....Aicha<br />
	　　　　　　艾瑞克&middot;艾伯纳尼 Eriq Ebouaney &nbsp;....Hassan Dakhil<br />
	　　　　　　Jan Uddin &nbsp;....Ibn Idriss<br />
	　　　　　　Jamal Awar &nbsp;....Compagnon Khoz Ahmed#1<br />
	　　　　　　Akin Gazi &nbsp;....Saleeh<br />
	　　　　　　Driss Roukhe &nbsp;....Magroof<br />
	　　　　　　Ziad Ghaoui &nbsp;....Theologian<br />
	　　　　　　Mostafa Gaafar &nbsp;....Khoz Ahmed　　　　<br />
	　　　　　　<br />
	<br />
	◎简　　介　<br />
	<br />
	　　剧情设定在上个世纪30年代，当时阿拉伯国家正处在石油热的初期。故事讲述一个博览群书的年轻王子（Tahar Rahim饰）在保守的父亲（Mark Strong饰）与思想开放的岳父（Antonio Banderas饰）对于石油的不同态度之间的权衡与抉择，与此同时，他也在复杂的利益纠葛与权力纷争之中渐渐成熟...<br />
	<br />
	◎幕后制作<br />
	<br />
	《情人》导演让-雅克&middot;阿诺新作。影片全程在沙哈拉沙漠拍摄。<br />
	故事改编自Hans Ruesch的小说《心之南方：一部关于现代阿拉伯的小说》，讲述了30年代早期两大阿拉伯酋长之间的斗争。有人将本片形容为&ldquo;《阿拉伯的劳伦斯》+《血色将至》&rdquo;。<br />
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120416/01/62564813201204160114282817696154363_002.jpg" style="width: 650px; height: 366px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120416/01/62564813201204160114282817696154363_001.jpg" style="width: 650px; height: 366px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120416/01/62564813201204160114282817696154363_000.jpg" style="width: 650px; height: 366px" /><br />
	&nbsp;</p>
<p>
	【下载地址】</p>
<table bgcolor="#0099cc" border="0" cellpadding="10" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.net" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy125:piaohua@dy125.piaohua.com:7858/飘花电影piaohua.com黑金BD中字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:7858/飘花电影piaohua.com黑金BD中字1280高清.rmvb</a></td>
		</tr>
		<tr>
		</tr>
	</tbody>
</table>
<br />{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15615460-2Z33.jpg{/dede:field}
