{dede:field name='keywords'}恶童BD高清日语中字1280迅雷下载{/dede:field}
{dede:field name='description'}恶童BD高清日语中字1280迅雷下载、免费下载，恶童BD高清日语中字1280Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}恶童BD高清日语中字1280{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-02-13{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://www.zaslike.com/files/lsce4ndjwk6nt2x55d27.jpg" /></p>
<p>
	◎译　　名　恶童<br />
	◎片　　名　Tekkon kinkreet<br />
	◎年　　代　2006<br />
	◎国　　家　日本<br />
	◎类　　别　卡通<br />
	◎语　　言　日语<br />
	◎字　　幕　中文<br />
	◎IMDB评分 7.4/10 (173 votes)<br />
	◎IMDB链接 http://www.imdb.com/title/tt0831888<br />
	◎片　　长　100 min<br />
	◎导　　演　米高．艾里工斯(Michael Arias)<br />
	◎主　　演　二宫和也 Kazunari Ninomiya<br />
	　　　　　　苍井优 Aol Yu<br />
	　　　　　　伊势谷友介 Yusuke Iseya<br />
	　　　　　　宫藤官九郎 kudo kankuro<br />
	　　　　　　大森南朋 Nao Omori<br />
	　　　　　　冈田义徳 Okada Yoshinori<br />
	<br />
	◎简　　介　<br />
	　　漫画大师松本大洋的这部代表作由《黑客帝国动画版》的制作人迈克尔&middot;艾里亚斯(Michael Arias)与日本知名动画公司STUDIO 4℃携手搬上银幕，东西合作为本片带来了独树一帜的影像风格，而二宫和也与苍井优的配音更是令影片备受瞩目。<br />
	　　故事发生在破旧的老城&mdash;&mdash;宝町，在这里生活着小黑和小白二名少年。他们是孤儿，从小彼此相依为命，平日里以勒索和扒窃为生。一天，小黑遇到了重返宝町的黑道混混耗子，他从耗子的言行中察觉到会有重大的事情发生。于是，两人设法接近警察藤村和泽田，想要打听出确切的情报，不料却一无所获。<br />
	　　小黑的预感是正确的。原来，有个大型公司正准备开发宝町，在这里兴建度假村。该计划的幕后主使人是绰号为&ldquo;蛇&rdquo;的神秘男子。小黑和小白不愿意看到深爱的宝町受人利用变得面目全非，他们决心为了保卫自己的城市而战。然而此时，残酷的蛇已经将魔掌伸向了他们&hellip;&hellip;</p>
<p>
	<img alt="" src="http://www.zaslike.com/files/fbs127uhhhqhjebu8tkx.jpg" /><img alt="" src="http://www.zaslike.com/files/bgpr7zgh6wpe2u38mjpk.jpg" /><img alt="" src="http://www.zaslike.com/files/lrcxja0sv89nk6vn45y7.jpg" style="width: 640px; height: 360px" /></p>
<p>
	<br />
	&nbsp;</p>
<p>
	[下载地址]：<img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" /></p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy241:xiaobajie@222.187.221.241:2019/小八戒电影xiaobajie.com恶童高清中字BD1280.rmvb">ftp://dy241:xiaobajie@222.187.221.241:2019/小八戒电影xiaobajie.com恶童高清中字BD1280.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1B2K20-52044.jpg{/dede:field}
