{dede:field name='keywords'}热血新仔2僵尸危机DVD中字2011最{/dede:field}
{dede:field name='description'}热血新仔2僵尸危机DVD中字2011最新荷兰恐怖动作喜剧大片迅雷下载、免费下载，热血新仔2僵尸危机DVD中字2011最新荷兰恐怖动作喜剧大片Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}热血新仔2僵尸危机DVD中字2011最新荷兰恐怖动作喜剧大片{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-01{/dede:field}
{dede:field name='body'}<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120430/20/56643687201204302002491770810340648_003.jpg" /></p>
<p>
	◎译　　名　热血新仔2僵尸危机/超二小混混2<br />
	◎片　　名　New Kids Nitro<br />
	◎年　　代　2011<br />
	◎国　　家　荷兰<br />
	◎类　　别　喜剧/动作/恐怖<br />
	◎语　　言　荷兰语<br />
	◎字　　幕　中文<br />
	◎IMDB评分 6.2/10 (1133 votes)<br />
	◎文件格式　DVD-RMVB<br />
	◎视频尺寸　720 x 300<br />
	◎文件大小　1CD 377MB<br />
	◎片　　长　74 mins</p>
<p>
	<br />
	一颗陨石降落在了他们的小镇上，不过这似乎没有影响大家继续二逼的活着，除了电视台孜孜不倦的报道以外没人把这事儿放在心上。某天他们五个惹到了一个性格暴躁的混混，于是他们决定用一场真正的赛车来和混混们一决生死&hellip;&hellip;</p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120430/20/56643687201204302002491770810340648_002.jpg" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120430/20/56643687201204302002491770810340648_001.jpg" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120430/20/56643687201204302002491770810340648_000.jpg" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.net" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				&nbsp;<a href="ftp://dy44:piaohua@dy44.piaohua.com:3325/飘花电影piaohua.com热血新仔2僵尸危机DVD中字.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3325/飘花电影piaohua.com热血新仔2僵尸危机DVD中字.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O156461F-54118.jpg{/dede:field}
