{dede:field name='keywords'}拳王[TVB]港台剧粤语25国语25【{/dede:field}
{dede:field name='description'}拳王[TVB]港台剧粤语25国语25【完】迅雷下载、免费下载，拳王[TVB]港台剧粤语25国语25【完】Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}拳王[TVB]港台剧粤语25国语25【完】{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-17{/dede:field}
{dede:field name='body'}<p>
	<img src="http://img.funshion.com/attachment/new_images/2012/04-06/18395589_1333696271_895.jpg" /></p>
<p>
	<img alt="" src="http://pic.piaohua.com/0701pic/allimg/120417/1-12041F000124K.jpg" /></p>
<p>
	导演：罗永贤</p>
<p>
	&bull;演员：<br />
	郑嘉颖 / 黄浩然 / 李诗韵 / 唐诗咏 / 胡定欣 / 黄德斌</p>
<p>
	&bull;类型：爱情 / 偶像 / 都市<br />
	&bull;首映：2012年4月16日 中国香港</p>
<p>
	&bull;点评： 郑嘉颖黄浩然晒&ldquo;肌&rdquo;打擂台--</p>
<p>
	&bull; 剧情： 　唐拾一（郑嘉颖饰）醉心泰拳，与师兄高伟廷（黄德斌饰）远赴泰国习拳，因一时贪念走上黑拳之路，犯下令他痛苦一生的错误，回港后他决意忘记过去，退出拳坛，在一家体育用品公司任职保安，他的直言吸引了女上司齐柏晖（李诗韵饰）的注意，而拾一与办公室助理毕家成（黄浩然饰）亦在重重误会下化敌为友，对泰拳充满梦想的家成更重燃拾一对泰拳的热情，二人因拳击建立了深厚的师徒情谊，是一不单走出伤痛，更重返拳馆，培育家成及聋哑拳手丁恩慈（胡定欣饰）成为拳王，可是师兄伟廷却对拾一因妒成恨，并从中嗦摆家成，另拾一与家成的师徒关系面临决裂&hellip;&hellip;</p>
<p>
	<img src="http://img.funshion.com/attachment/new_images/2012/04-06/18395589_1333696305_57.jpg" /></p>
<p>
	<img src="http://img.funshion.com/attachment/new_images/2012/04-06/18395589_1333696298_287.jpg" /></p>
<p>
	<img src="http://img.funshion.com/attachment/new_images/2012/04-06/18395589_1333696293_863.jpg" /></p>
<p>
	&nbsp;<img src="http://img.funshion.com/attachment/new_images/2012/04-06/18395589_1333696291_115.jpg" /></p>
<p>
	&nbsp;<img src="http://img.funshion.com/attachment/new_images/2012/04-06/18395589_1333696289_166.jpg" /></p>
<p>
	&nbsp;<img src="http://img.funshion.com/attachment/new_images/2012/04-06/18395589_1333696302_82.jpg" style="width: 420px; height: 236px" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.netftp//dy44:piaohua@dy44.piaohua.com:3201/" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3236/飘花电影piaohua.com拳王粤语01.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3236/飘花电影piaohua.com拳王粤语01.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3240/飘花电影piaohua.com拳王粤语02.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3240/飘花电影piaohua.com拳王粤语02.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3247/飘花电影piaohua.com拳王粤语03.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3247/飘花电影piaohua.com拳王粤语03.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3257/飘花电影piaohua.com拳王粤语04.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3257/飘花电影piaohua.com拳王粤语04.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3263/飘花电影piaohua.com拳王粤语05.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3263/飘花电影piaohua.com拳王粤语05.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3293/飘花电影piaohua.com拳王粤语06.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3293/飘花电影piaohua.com拳王粤语06.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3287/飘花电影piaohua.com拳王粤语07.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3287/飘花电影piaohua.com拳王粤语07.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3294/飘花电影piaohua.com拳王粤语08.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3294/飘花电影piaohua.com拳王粤语08.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3301/飘花电影piaohua.com拳王粤语09.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3301/飘花电影piaohua.com拳王粤语09.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3310/飘花电影piaohua.com拳王粤语10.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3310/飘花电影piaohua.com拳王粤语10.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3326/飘花电影piaohua.com拳王粤语11.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3326/飘花电影piaohua.com拳王粤语11.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3332/飘花电影piaohua.com拳王粤语12.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3332/飘花电影piaohua.com拳王粤语12.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3335/飘花电影piaohua.com拳王粤语13.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3335/飘花电影piaohua.com拳王粤语13.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3342/飘花电影piaohua.com拳王粤语14.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3342/飘花电影piaohua.com拳王粤语14.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3349/飘花电影piaohua.com拳王粤语15.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3349/飘花电影piaohua.com拳王粤语15.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3369/飘花电影piaohua.com拳王粤语16.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3369/飘花电影piaohua.com拳王粤语16.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3375/飘花电影piaohua.com拳王粤语17.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3375/飘花电影piaohua.com拳王粤语17.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3379/飘花电影piaohua.com拳王粤语18.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3379/飘花电影piaohua.com拳王粤语18.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3387/飘花电影piaohua.com拳王粤语19.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3387/飘花电影piaohua.com拳王粤语19.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3399/飘花电影piaohua.com拳王粤语20.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3399/飘花电影piaohua.com拳王粤语20.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3419/飘花电影piaohua.com拳王粤语21.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3419/飘花电影piaohua.com拳王粤语21.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3427/飘花电影piaohua.com拳王粤语22.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3427/飘花电影piaohua.com拳王粤语22.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3434/飘花电影piaohua.com拳王粤语23.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3434/飘花电影piaohua.com拳王粤语23.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3443/飘花电影piaohua.com拳王粤语24.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3443/飘花电影piaohua.com拳王粤语24.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3443/飘花电影piaohua.com拳王粤语25.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3443/飘花电影piaohua.com拳王粤语25.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#00ffff" style="line-height: 18px; word-break: break-all" width="100%">
				国语</td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3240/飘花电影piaohua.com拳王国语01.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3240/飘花电影piaohua.com拳王国语01.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3246/飘花电影piaohua.com拳王国语02.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3246/飘花电影piaohua.com拳王国语02.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3253/飘花电影piaohua.com拳王国语03.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3253/飘花电影piaohua.com拳王国语03.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3260/飘花电影piaohua.com拳王国语04.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3260/飘花电影piaohua.com拳王国语04.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3264/飘花电影piaohua.com拳王国语05.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3264/飘花电影piaohua.com拳王国语05.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3281/飘花电影piaohua.com拳王国语06.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3281/飘花电影piaohua.com拳王国语06.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3289/飘花电影piaohua.com拳王国语07.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3289/飘花电影piaohua.com拳王国语07.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3298/飘花电影piaohua.com拳王国语08.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3298/飘花电影piaohua.com拳王国语08.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3306/飘花电影piaohua.com拳王国语09.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3306/飘花电影piaohua.com拳王国语09.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3313/飘花电影piaohua.com拳王国语10.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3313/飘花电影piaohua.com拳王国语10.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3328/飘花电影piaohua.com拳王国语11.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3328/飘花电影piaohua.com拳王国语11.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3333/飘花电影piaohua.com拳王国语12.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3333/飘花电影piaohua.com拳王国语12.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3342/飘花电影piaohua.com拳王国语13.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3342/飘花电影piaohua.com拳王国语13.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3346/飘花电影piaohua.com拳王国语14.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3346/飘花电影piaohua.com拳王国语14.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3355/飘花电影piaohua.com拳王国语15.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3355/飘花电影piaohua.com拳王国语15.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3370/飘花电影piaohua.com拳王国语16.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3370/飘花电影piaohua.com拳王国语16.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3377/飘花电影piaohua.com拳王国语17.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3377/飘花电影piaohua.com拳王国语17.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3381/飘花电影piaohua.com拳王国语18.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3381/飘花电影piaohua.com拳王国语18.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3389/飘花电影piaohua.com拳王国语19.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3389/飘花电影piaohua.com拳王国语19.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3401/飘花电影piaohua.com拳王国语20.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3401/飘花电影piaohua.com拳王国语20.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3424/飘花电影piaohua.com拳王国语21.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3424/飘花电影piaohua.com拳王国语21.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3431/飘花电影piaohua.com拳王国语22.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3431/飘花电影piaohua.com拳王国语22.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3439/飘花电影piaohua.com拳王国语23.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3439/飘花电影piaohua.com拳王国语23.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3442/飘花电影piaohua.com拳王国语24.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3442/飘花电影piaohua.com拳王国语24.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3443/飘花电影piaohua.com拳王国语25.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3443/飘花电影piaohua.com拳王国语25.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1A4L40-25215.jpg{/dede:field}
