<?php
$z[0]=Array("field","最后一场电影[BD中英双字1280x72",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最后一场电影[BD中英双字1280x720高清版]迅雷下载、免费下载，最后一场电影[BD中英双字1280x720高清版]Gvod高清在线播放，剧情介绍等。",73,243);
$z[1][4]['name']="description";
$z[2]=Array("field","最后一场电影[BD中英双字1280x720高清版]",245,321);
$z[2][4]['name']="title";
$z[3]=Array("field","",323,362);
$z[3][4]['name']="writer";
$z[4]=Array("field","",364,403);
$z[4][4]['name']="source";
$z[5]=Array("field","2009-12-05",405,455);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",457,494);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://3e:3e@www2.eee4.com:931/[3E电影站www.eee4.cn]最后一场电影BD中英双字1280x720高清版.rmvb\" target=_blank>ftftp://3e:3e@www2.eee4.com:931/[3E电影站www.eee4.cn]最后一场电影BD中英双字1280x720高清版.rmvb</A></TD></TR></TBODY></TABLE></div><ul class=\"mmlist",496,790);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MQ3210F-51356.jpg",792,875);
$z[8][4]['name']="litpic";

?>