{dede:field name='keywords'}超级大玩家BD字1280高清2012最新{/dede:field}
{dede:field name='description'}超级大玩家BD字1280高清2012最新印度恐怖动作惊悚大片迅雷下载、免费下载，超级大玩家BD字1280高清2012最新印度恐怖动作惊悚大片Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}超级大玩家BD字1280高清2012最新印度恐怖动作惊悚大片{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-21{/dede:field}
{dede:field name='body'}<p>
	<img src="/uploads/allimg/c120525/133O0Z3T30-193525.jpg" /></p>
<p>
	<img src="/uploads/allimg/c120525/133O0Z402Z-204456.jpg" />、</p>
<p>
	<img src="/uploads/allimg/c120525/133O0Z41H0-214426.jpg" /></p>
<p>
	◎译　　名　超级大玩家/偷天换日大玩家<br />
	◎片　　名　players<br />
	◎年　　代　2012<br />
	◎国　　家　印度<br />
	◎类　　别　动作/ 剧情/ 悬疑 / 惊悚 / 恐怖<br />
	◎语　　言　英语 / 印地语 Hindi<br />
	◎字　　幕　中文<br />
	◎IMDB评分 4.6/10 (651 votes)<br />
	◎IMDB链接：http://www.bluemv.com<br />
	◎文件格式　DVD-RMVB<br />
	◎文件大小　1CD 698MB<br />
	◎片　　长　150 Mins<br />
	◎导　　演　阿巴斯&middot;布玛瓦尔拉-姆斯坦&middot;布玛瓦尔拉Abbas-Mustan (Abbas Burmawalla &amp; Mustan Burmawalla)<br />
	◎主　　演　阿布舍克&middot;巴强Abhishek Bachchan as Charlie<br />
	碧帕莎&middot;芭素Bipasha Basu as Riya<br />
	尼尔&middot;尼汀&middot;穆科什Neil Nitin Mukesh as Spider<br />
	索娜姆&middot;卡普尔Sonam Kapoor as Naina<br />
	奥米&middot;瓦依达Omi Vaidya as Sunny<br />
	波比&middot;戴尔Bobby Deol as Ronnie<br />
	Sikander Kher as Bilal<br />
	Sumit Sarkar<br />
	Johny Lever Sag<br />
	维诺德&middot;坎纳Vinod Khanna<br />
	Tushar Jain<br />
	Vyacheslav Razbegaev <br />
	Aftab Shivdasani</p>
<p>
	　　　　　　</p>
<p>
	◎简　　介　</p>
<p>
	<br />
	两个小偷，一个魔术师，一个名为蜘蛛的电脑黑客，一个想成为演员的化妆师，一个半聋的爆破专家组成的顶级团队经过周密的计划完美的从俄国突击队手里盗出了黄金。然而正当大伙都在为胜利举杯时，故事突然出现了转折。电脑黑客蜘蛛事先更改了他们的撤离计划，面对同伴突然的反击，大家都措手不及，最后黄金被蜘蛛偷走，并对他们实行了残忍的杀害......</p>
<p>
	该片翻拍自1969年好莱坞的轰动一时的经典大片《偷天换日》，演员整容强大。最先定下的是男主角，在两位女主角的选角上破费周折。片方最先定下的是朴雅卡&middot;乔普拉和卡特莉娜&middot;卡芙，也曾有传言称之后变成了卡琳娜&middot;卡普尔和迪皮卡&middot;帕度柯妮，不过最终决定换由碧帕莎&middot;芭素和索娜姆&middot;卡普尔出演。该片穿越过多国拍摄，自2011年初起先后于印度的果阿、新西兰的惠林顿和奥克兰取景。之后又在俄罗斯境内的西伯利亚、圣彼得堡及印度的其他地区展开长时间拍摄。</p>
<p>
	<br />
	◎影片截图</p>
<p>
	<img src="/uploads/allimg/c120525/133O0Z43060-229154.jpg" /></p>
<p>
	<img src="/uploads/allimg/c120525/133O0Z435Z-23OB.jpg" /></p>
<p>
	<img src="/uploads/allimg/c120525/133O0Z44210-24c03.jpg" /></p>
<p>
	<img src="/uploads/allimg/c120525/133O0Z44J0-25H34.jpg" /></p>
<p>
	<img border="0" src="/uploads/allimg/c120525/133O0Z452F-261551.jpg" style="max-width: 750px; max-height: 750px" /></p>
<p>
	<img border="0" src="/uploads/allimg/c120525/133O0Z4B20-2K249.jpg" style="max-width: 750px; max-height: 750px" /></p>
<p>
	<img border="0" src="/uploads/allimg/c120525/133O0Z4N50-2V648.jpg" style="max-width: 750px; max-height: 750px" /></p>
<p>
	<img border="0" src="/uploads/allimg/c120525/133O0Z4Z10-2940R.jpg" style="max-width: 750px; max-height: 750px" /></p>
<p>
	[下载地址]： &nbsp;<img border="0" src="/uploads/allimg/c120525/133O0T31310-42214.jpg" /></p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:2872/飘花电影piaohua.com超级大玩家DVD中字.rmvb</td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:2963/飘花电影piaohua.com超级大玩家BD字1280高清.rmvb</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O0Z505F-30aV.jpg{/dede:field}
