{dede:field name='keywords'}阿尔及尔之战BD高清中字1024*576{/dede:field}
{dede:field name='description'}阿尔及尔之战BD高清中字1024*576迅雷下载、免费下载，阿尔及尔之战BD高清中字1024*576Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}阿尔及尔之战BD高清中字1024*576{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-08-29{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20110829/23/17870980201108292336371177360682335_002.jpg" style="width: 347px; height: 489px" /></p>
<p>
	◎译　　名　阿尔及尔之战/阿尔及尔战役<br />
	◎片　　名　The Battle of Algiers<br />
	◎年　　代　1966<br />
	◎国　　家　意大利/阿尔及利亚<br />
	◎类　　别　剧情/历史/战争<br />
	◎语　　言　意大利语/法语/英语/阿拉伯语<br />
	◎字　　幕　英文<br />
	◎IMDB评分　8.3/10 (16,604 votes) Top 250 #193<br />
	◎IMDB链接　http://www.imdb.com/title/tt1658851/<br />
	◎片　　长　122 mins<br />
	◎导　　演　吉洛&middot;彭特克沃 Gillo Pontecorvo<br />
	◎主　　演　让&middot;马丁 Jean Martin&nbsp; ....Col. Mathieu<br />
	　　　　　　Yacef Saadi&nbsp; ....Djafar (as Saadi Yacef)<br />
	　　　　　　Brahim Hadjadj&nbsp; ....Ali La Pointe (as Brahim Haggiag)<br />
	　　　　　　Samia Kerbash&nbsp; ....One of the girls<br />
	　　　　　　Ugo Paletti&nbsp; ....Captain<br />
	　　　　　　Fusia El Kader&nbsp; ....Halima<br />
	　　　　　　Omar<br />
	　　　　　　Mohamed Ben Kassen&nbsp; ....Petit Omar<br />
	　　　　　　Michele Kerbash&nbsp; ....Fathia (uncredited)<br />
	　　　　　　Franco Morici&nbsp; ....(uncredited)<br />
	　　　　　　Tommaso Neri&nbsp; ....Captain (uncredited)<br />
	　　　　　　Gene Wesson&nbsp; ....(uncredited)</p>
<p>
	◎简　　介<br />
	剧情<br />
	　　影片以阿尔及利亚争取独立为背景，讲述了在阿尔及尔这座城市里，地下运动组织&mdash;&mdash;民族解放阵线同法国人的战斗。<br />
	一句话评论<br />
	The Revolt that Stirred the World!<br />
	幕后制作<br />
	　　本片是曾获威尼斯金狮奖的半纪录影片，也是获得阿尔及利亚政府正式支持的独立抗&#1161;暴电影，完全利用当地民众拍摄而成，导演冷酷而不带偏袒地拍下双方的对抗情况，采取粗粒子新闻摄影般的美学，乍看之下会以为是部纪录片！该片在法国足足被禁了5年，到1970年才解禁。在美国和英国放映时也都修剪了15分钟。</p>
<p>
	<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20110829/23/17870980201108292336371177360682335_024.jpg" /><img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20110829/23/17870980201108292336371177360682335_023.jpg" style="width: 640px; height: 360px" /><img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20110829/23/17870980201108292336371177360682335_022.jpg" style="width: 640px; height: 360px" /></p>

<p>
	[下载地址]： &nbsp;<img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" /></p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy67:piaohua@dy67.piaohua.com:1060/飘花电影piaohua.com阿尔及尔之战BD高清中字1024分辨率.rmvb">ftp://dy67:piaohua@dy67.piaohua.com:1060/飘花电影piaohua.com阿尔及尔之战BD高清中字1024分辨率.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1621A60-51O1.jpg{/dede:field}
