{dede:field name='keywords'}关键投票BD中英双字1280高清迅雷{/dede:field}
{dede:field name='description'}关键投票BD中英双字1280高清迅雷下载、免费下载，关键投票BD中英双字1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}关键投票BD中英双字1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-03-17{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://d25:d25@dm.eee4.com:1205/[3E电影站www.eee4.com]关键投票CD1.rmvb" target="_blank{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MO635N0-51J2.jpg{/dede:field}
