{dede:field name='keywords'}齐达内：一幅21世纪的肖像BD高清{/dede:field}
{dede:field name='description'}齐达内：一幅21世纪的肖像BD高清1280迅雷下载、免费下载，齐达内：一幅21世纪的肖像BD高清1280Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}齐达内：一幅21世纪的肖像BD高清1280{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-02-18{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="/uploads/allimg/c120524/133N4W0Q40-126402.jpg" style="width: 640px; height: 826px" /></p>
<p>
	◎译　　名　齐达内：一幅21世纪的肖像<br />
	◎片　　名　Zidane A 21st Century Portrait<br />
	◎年　　代　2006<br />
	◎国　　家　法国/冰岛<br />
	◎类　　别　纪录/短片<br />
	◎语　　言　英语<br />
	◎字　　幕　无字幕<br />
	◎IMDB评分 6.1/10 (1,449 votes)<br />
	◎IMDB链接 http://www.imdb.com/title/tt0478337<br />
	◎豆瓣评分 7.8/10 (459 votes)<br />
	◎豆瓣链接 http://movie.douban.com/subject/1775614/<br />
	◎片　　长　91 Min<br />
	◎导　　演　道格拉斯&middot;戈登 / 飞利浦帕&middot;雷诺<br />
	◎主　　演　奇内丁&middot;齐达内 / 大卫&middot;贝克汉姆<br />
	◎官方网站 &nbsp;www.uipfrance.com/sites/zidane<br />
	◎获奖情况 2007年 法国凯撒奖(C&eacute;sar) Best Documentary (Meilleur film documentaire)(提名)<br />
	<br />
	◎简　　介　<br />
	<br />
	菲利普&middot;帕雷诺和道格拉斯&middot;戈登两位当代艺术家，在上一季西班牙足球锦标赛皇家马德里队对维拉雷阿尔队的决赛期间，大胆使用17部摄影机，混合几个不同的高清晰度超35厘米摄影镜头，对准皇家马德里队的明星球员齐达内的脸、脚、身体，拍下他在球场上奔驰运球的画面，然后在90分钟的实际时间内，不间断地用大镜头向观众展现齐达内奔跑、喘气、流汗、微笑、讲话、踢球的画面。这位足球明星以前从未以这样的方式显现在观众眼前。<br />
	<br />
	影片从头到尾拍摄齐达内05年为皇家马德里打的一场比赛，使用了17台不同的电影摄影机，全部锁定齐达内在赛场中的各种细节。你看不到整场比赛，看不到输赢，只能看到齐达内的个人表演。赛场的声音此起彼伏，但人们仍然能听到齐达内的喘息，他呼喊队友和吐口水的声音。Mogwai的配乐总是适时出现，为激烈的比赛场面增添抒情气息。整部影片仿如一场精神分析，致力于呈现齐达内的内心世界：<br />
	<br />
	&ldquo;关于比赛我的记忆总是破碎的。当我走进球场时，我常常感到比赛毫无必要，因为胜负早已注定，这只是一场剧本早已写好的表演。&hellip;&hellip;在观众的呼啸中，我能听到有些人的咳嗽，甚至有人向旁边的人耳语。&hellip;&hellip;所谓魔法，它有时几乎就是虚无。&rdquo;<br />
	<br />
	这些独白以字幕的形式出现，无声，仿如梦境。这部影片不是一般的传记片，它没有叙事，但充满华丽的影像和考究的声音设计。它还引用了同一场比赛的电视素材以及数段国际新闻资料（完全出于Douglas Gordon对&ldquo;时代影像&rdquo;的着迷，同时也为了呼应&ldquo;21世纪肖像&rdquo;的标题），故意放大电视荧幕的粗糙效果和现场解说的声音，与电影摄影的画面互相穿插，形成对比。非常录像艺术。片头由M/M设计，这几年来他们几乎包办了法国以及欧洲的艺术项目的平面工作。<br />
	<br />
	这部影片是少有的由当代艺术家拍摄而能在院线上映的电影。它曾在今年巴塞尔艺术博览会期间在当地的体育场放映，吸引超过四千名观众。</p>
<p>
	<em>传奇球星在赛场上的英姿尽收眼底 没有解说词，只有影像和音乐，却感动了无数人</em></p>
<p>
	<em><img alt="" src="/uploads/allimg/c120524/133N4W0c40-1341B.jpg" style="width: 640px; height: 360px" /><img alt="" src="/uploads/allimg/c120524/133N4W10630-14H52.jpg" /><img alt="" src="/uploads/allimg/c120524/133N4W13S0-151951.jpg" /></em></p>
<p>
	<br />
	&nbsp;</p>
<p>
	[下载地址]：<img border="0" src="/uploads/allimg/c120524/133N2Z4FF-102231.jpg" /></p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				ftp://dy241:xiaobajie@222.187.221.241:2029/小八戒xiaobajie.com齐达内：一幅21世纪的肖像BD高清1280.mkv</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120524/133N4W14540-1644V.jpg{/dede:field}
