{dede:field name='keywords'}快乐大脚/快乐的大脚/欢乐的大脚{/dede:field}
{dede:field name='description'}快乐大脚/快乐的大脚/欢乐的大脚BD国语配音中字1280高清迅雷下载、免费下载，快乐大脚/快乐的大脚/欢乐的大脚BD国语配音中字1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}快乐大脚/快乐的大脚/欢乐的大脚BD国语配音中字1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-01-18{/dede:field}
{dede:field name='body'}<p>
	<img src="http://image2.sina.com.cn/ent/d/2006-11-14/U105P28T3D1327205F326DT20061114115359.jpg" /></p>
<p>
	◎译　　名　《快乐大脚/快乐的大脚/欢乐的大脚》06美国票房过亿动画喜剧大片DVD中英字幕<br />
	◎片　　名　Happy Feet<br />
	◎年　　代　2006<br />
	◎国　　家　美国<br />
	◎类　　别　喜剧/冒险/音乐/动画/家庭<br />
	◎语　　言　英语<br />
	◎字　　幕　中英字幕<br />
	◎IMDB评分 6.8/10 (9,472 votes)<br />
	◎IMDB链接 http://www.imdb.com/title/tt0366548<br />
	◎文件格式　XviD + AC3<br />
	◎视频尺寸　800 x 452 (2.37 : 1)<br />
	◎文件大小　3CD 2 x 50 x 15MB<br />
	◎片　　长　108 Min<br />
	◎导　　演　乔治&middot;米勒 George Miller<br />
	◎主　　演　Carlos Alazraqui .... Nestor (voice)<br />
	　　　　　　Denise Blasor .... Additional Voices (voice)<br />
	　　　　　　伊丽莎白&middot;戴利 Elizabeth Daily .... Young Mumble (voice)<br />
	　　　　　　Khamani Griffin .... Young penguin (voice)<br />
	　　　　　　休&middot;杰克曼 Hugh Jackman .... Memphis (voice)<br />
	　　　　　　尼科尔&middot;基德曼 Nicole Kidman .... Norma Jean (voice)<br />
	　　　　　　布瑞特妮&middot;墨菲 Brittany Murphy .... Gloria (voice)<br />
	　　　　　　Zoe Raye .... Additional Voices (voice)<br />
	　　　　　　Alyssa Shafer .... Young Gloria (voice)<br />
	　　　　　　Alyssa Smith .... Additional Voices (voice)<br />
	　　　　　　马格达&middot;斯祖班斯基 Magda Szubanski .... Miss Viola (voice)<br />
	　　　　　　罗宾&middot;威廉斯 Robin Williams .... Ram&oacute;n/Lovelace/Cletus (voice)<br />
	　　　　　　伊利亚&middot;伍德 Elijah Wood .... Mumble (voice)<br />
	　　　　　　Kwesi Boakye .... Additional Voices (voice)<br />
	　　　　　　Michael Cornacchia .... Skua Bird (voice)<br />
	◎简　　介　<br />
	剧情简介<br />
	　　这是属于帝企鹅的伟大时代。它们占领者着南极洲的最深处，在这个家族里，只有一个办法能够让新生的小家伙得到大家的认可&mdash;&mdash;拥有一副动听的歌喉。不幸的是，马伯(伊利亚&middot;伍德配音)是整个家族里唱歌唱得最差的那个。但是，他却是一个天生的舞蹈家，街舞跳到出神入化。马伯的妈妈诺玛&middot;吉恩(妮可&middot;基德曼配音)，把马伯舞蹈天赋仅仅看成一个可爱的小爱好，但马伯的爸爸孟菲斯(休&middot;杰克曼配音)却认为，不会唱歌只会跳舞的马伯根本就不是企鹅。不过他们达成共识的是，没有一副好嗓子的巴伯，可能永远也找不到真爱了。<br />
	　　有趣的是，不会唱歌的马伯唯一的好朋友格洛丽亚(布兰特妮&middot;墨菲配音)，正好是整个家族当中最好的歌手。虽然他们俩自出生后就一直在一起，对彼此都有特殊的感觉，但格洛丽亚总是被马伯与众不同的节奏舞步困扰着。马伯与其他帝企鹅实在是太不一样了--特别是对于家族中最严厉的领导者诺亚(罗宾&middot;威廉姆斯配音)来说。虽然诺亚的独断专行导致他最后被家族所排斥，但他一贯不依不饶的态度迫使马伯产生了离开的念头。<br />
	　　第一次离开家的马伯，在路上碰到了一群企鹅朋友。他们不是帝企鹅，而是阿德兰企鹅，首领叫做罗曼。阿德兰们被马伯独特的舞步深深打动，邀请他去参加一个盛大的舞会。在阿德兰的地盘上，马伯用一块鹅卵石的代价，获得了一位头上长有奇怪羽毛，跳着摇滚舞步的流浪者的指引，他回答了马伯生命中的很多疑问&hellip;&hellip;<br />
	幕后花絮<br />
	　　今年的动画片竞争激烈，花招迭出。然而，自皮克斯的《汽车总动员》大放异彩之后，任凭《篱笆墙外》、《冲走小老鼠》、《怪兽屋》和《疯狂农场》找来一大群动物怎么吆喝，始终不能战胜&ldquo;人脸小汽车&rdquo;。但《快乐的大脚》应该是《汽车总动员》最大的竞争对手。首先，以企鹅作为主角的动画片几乎屈指可数，而且在今年尚属独一份。自当年《帝企鹅日记》打动无数人心之后，帝企鹅不仅是企鹅品种中人气最高的，当然也盖过诸如畸形奶牛以及憨厚大熊之类的老面孔。其次，影片的配音简直就是八星级阵容，除去本片之外，各路配音演员在今年的其他作品中都有上佳表现，这无疑对本片的人气起到了很大的助长作用。第三，本片以时下最流行的街舞做为基础，集合了Rap, R&amp;B, Rock等时尚音乐元素，把一部动画片生生拍成一部歌舞片。想想看，最可爱的帝企鹅随着节拍跳着街舞的负责舞步，有几个人不想去影院开心一回呢？<br />
	主创阵容<br />
	　　导演乔治&middot;米勒，以动作片起家，却奇迹般的在98年执导了大受欢迎的《小猪宝贝》电影，把一头聪明的小猪拍得人见人爱，让人见识到了米勒在暴力画面之外的童心。事实上米勒是一名非常有爱心的导演，在印尼海啸之后，他执导了一部名为《大海啸》的纪录片，并将票房收入全部捐给了赈灾机构。《快乐的大脚》是他执导的第二部儿童可以观看的影片，也是第一部动画片，米勒这次邀请众多大牌影星加盟，除了展现他的号召力之外，也能对他在这部片子上的雄心勃勃略见一斑。<br />
	　　伊利亚&middot;伍德，妮可&middot;基德曼，休&middot;杰克曼，布兰特妮&middot;墨菲，罗宾&middot;威廉姆斯，这几个名字无一不是如雷贯耳。近几年集中这么多明星给动画片配音，还真是非常少见。早在影片刚开拍的时候，上述大牌的粉丝们就开始津津乐道地等待片子出炉，并且猜测自己的偶像会给哪一只企鹅配音。想象一下自己偶像以一个帝企鹅的形象出现&hellip;&hellip;</p>

<p>
	【电影截图】：<br />
	电影来源：www.eee4.com<br />
	<img src="http://i3.6.cn/cvbnm/15/1c/1a/f2e5cee8204dc2939f44ae523efcbaee.jpg" />&nbsp;<br />
	<img src="http://i3.6.cn/cvbnm/a0/10/a6/2380a756611a0f3f7c8a17359c5d4c29.jpg" /></p>
<p>
	06美国票房过亿动画喜剧大片《快乐大脚》DVD中英字幕－来自[3E电影站eee4.com]：<img border="0" src="http://www.eee4.com/templets/img/down.jpg" /><br />
	&nbsp;</p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<anchor></anchor><a href="ftp://d22:d22@dm.eee4.com:1205/[3E电影站www.eee4.com]快乐的大脚DVD中英双字CD1.rmvb" target="_blank">ftp://d22:d22@dm.eee4.com:1205/[3E电影站www.eee4.com]快乐的大脚DVD中英双字CD1.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<anchor></anchor><a href="ftp://d22:d22@dm.eee4.com:1205/[3E电影站www.eee4.com]快乐的大脚DVD中英双字CD2.rmvb" target="_blank">ftp://d22:d22@dm.eee4.com:1205/[3E电影站www.eee4.com]快乐的大脚DVD中英双字CD2.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<anchor></anchor><a href="ftp://d22:d22@dm.eee4.com:1205/[3E电影站www.eee4.com]快乐的大脚DVD中英双字CD3.rmvb" target="_blank">ftp://d22:d22@dm.eee4.com:1205/[3E电影站www.eee4.com]快乐的大脚DVD中英双字CD3.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<anchor></anchor><a href="ftp://dy44:piaohua@dy44.piaohua.com:2654/飘花电影piaohua.com欢乐的大脚BD国语配音中字1280高清.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2654/飘花电影piaohua.com欢乐的大脚BD国语配音中字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1B205Z-12542.jpg{/dede:field}
