{dede:field name='keywords'}海神号迅雷下载，免费下载，Gvod{/dede:field}
{dede:field name='description'}海神号迅雷下载、免费下载，海神号Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}海神号{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2006-08-02{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://eee4.com:eee4@xl3.eee4.com:8448/海神号/[3E迅雷电影站www.eee4.com]海神号DVD完美中字.rmvb" target=_blank>ftftp://eee4.com:eee4@xl3.eee4.com:8448/海神号/[3E迅雷电影站www.eee4.com]海神号DVD完美中字.rmvb</A></TD></TR></TBODY></TABLE></div><ul class="mmlist{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MPZ410-23N7.jpg{/dede:field}
