<?php
$z[0]=Array("field","驱逐进化论/智慧设计论禁令[DVD",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","驱逐进化论/智慧设计论禁令[DVD中英双字]迅雷下载、免费下载，驱逐进化论/智慧设计论禁令[DVD中英双字]Gvod高清在线播放，剧情介绍等。",72,242);
$z[1][4]['name']="description";
$z[2]=Array("field","驱逐进化论/智慧设计论禁令[DVD中英双字]",244,320);
$z[2][4]['name']="title";
$z[3]=Array("field","",322,361);
$z[3][4]['name']="writer";
$z[4]=Array("field","",363,402);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-01-08",404,454);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",456,493);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://3e:3e@d3.3edyy.com:129/【3E看看www.3ekk.com】智慧设计论禁令[DVD中英双字].rmvb\" target=_blank>ftftp://3e:3e@d3.3edyy.com:129/【3E看看www.3ekk.com】智慧设计论禁令[DVD中英双字].rmvb</A></TD></TR></TBODY></TABLE></div><ul class=\"mmlist",495,771);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MQ454960-554T.jpg",773,856);
$z[8][4]['name']="litpic";

?>