{dede:field name='keywords'}鹿鼎记2部BD高清国粤双语迅雷下{/dede:field}
{dede:field name='description'}鹿鼎记2部BD高清国粤双语迅雷下载、免费下载，鹿鼎记2部BD高清国粤双语Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}鹿鼎记2部BD高清国粤双语{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-09-28{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img165.poco.cn/mypoco/myphoto/20110927/10/62564813201109271014471904189004618_001.jpg" /></p>
<p>
	【影片原名】Lu ding ji<br />
	【外文别名】Luk ting kei (Hong Kong: Cantonese title)<br />
	　　　　　　Royal Tramp (Hong Kong: English title)<br />
	【中文译名】鹿鼎记<br />
	【出品公司】20世纪福克斯家庭娱乐公司<br />
	【出品年代】1992 年<br />
	【影片级别】USA:R<br />
	【IMDB链接】<a href="http://www.imdb.com/title/tt0104770">http://www.imdb.com/title/tt0104770</a><br />
	【IMDB评分】7.0/10 (839 votes)<br />
	【国　　家】中国香港<br />
	【类　　别】动作/喜剧<br />
	【影片长度】110 Mins<br />
	【对白语言】粤语/普通话<br />
	【导　　演】程小东 Siu-Tung Ching<br />
	　　　　　　王晶 Jing Wong<br />
	　　　　　　陈嘉上 Gordon Chan....(uncredited)<br />
	【主　　演】周星驰 Stephen Chow....Wei Siu Bo<br />
	　　　　　　吴孟达 Man Tat Ng....Hoi Tai Fu<br />
	　　　　　　邱淑贞 Chingmy Yau....Princess Kim Ning<br />
	　　　　　　陈百祥 Pak-cheung Chan....Duran<br />
	　　　　　　陈德容 Vivian Chan....Shang&#39;er Twin<br />
	　　　　　　张敏 Sharla Cheung....Empress Dowanger/Lone-er<br />
	　　　　　　刘松仁 Damian Lau....Chan, Master of the Heaven &amp; Earth Society<br />
	　　　　　　林青霞 Brigitte Lin....Lone-er<br />
	　　　　　　吴君如 Sandra Ng....Sister Bond<br />
	　　　　　　徐锦江 Elvis Tsui....O&#39;Brian<br />
	　　　　　　温兆伦 Siu-Lun Wan....Prince Ning<br />
	　　　　　　袁洁莹 Fennie Yuen....Shang&#39;er Twin<br />
	　　　　　　秦沛 Paul Chun....Ng Sam Kwai</p>
<p>
	【内容简介】</p>
<p>
	　　清朝初年，奸臣鳌拜弄权，欺唐熙皇帝年幼，控制朝政，民生疾苦。『天地会』在首领陈近南指挥下，要韦小宝混入宫廷做卧底，偷取藏有清朝秘密大宝藏之四本四十二章经。</p>
<p>
	　　小宝刮了大笔油水，准备逃走，不料回丽春院却遇到在等他的陈近南。南送他两个孖生姊妹双儿为贴身侍婢，其实是监视他回皇宫，小宝唯有硬着头皮回去。</p>
<p>
	　　在宫内塔林遇陈近南与天地会高手，双方大战，太后亦出现要杀小宝，但御林军已包围，二人互揭阴私，但建宁公主发现被禁锢的真太后。假太后身怀绝世武功，腾空逃离险境。不久，皇帝再封小宝为更大的官，小宝自此权倾朝野，继续做他的边缘人。</p>
<p>
	<img alt="" src="http://img165.poco.cn/mypoco/myphoto/20110927/10/62564813201109271041512571305426295_001.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img165.poco.cn/mypoco/myphoto/20110927/10/62564813201109271041512571305426295_000.jpg" style="width: 720px; height: 405px" /></p>
<p>
	<img alt="" src="http://img165.poco.cn/mypoco/myphoto/20110927/10/62564813201109271014471904189004618_000.jpg" /></p>
<p>
	【影片原名】Lu ding ji II: Zhi shen long jiao<br />
	【外文别名】Luk ting kei II: Ji san lung gaau (Hong Kong: Cantonese title)<br />
	　　　　　　Royal Tramp II (Hong Kong: English title)<br />
	【中文译名】鹿鼎记II神龙教<br />
	【出品公司】Twentieth Century Fox Home Entertainment<br />
	【出品年代】1992 年<br />
	【影片级别】USA:R<br />
	【IMDB链接】<a href="http://www.imdb.com/title/tt0104771">http://www.imdb.com/title/tt0104771</a><br />
	【IMDB评分】6.9/10 (528 votes)<br />
	【国　　家】中国香港<br />
	【类　　别】喜剧<br />
	【导　　演】程小东 Siu-Tung Ching<br />
	　　　　　　王晶 Jing Wong<br />
	　　　　　　陈嘉上 Gordon Chan....6 (uncredited)<br />
	【主　　演】周星驰 Stephen Chow....Wei Siu Bo<br />
	　　　　　　张敏 Sharla Cheung....Lone-er (Cameo)<br />
	　　　　　　陈德容 Vivian Chan....Nam<br />
	　　　　　　陈百祥 Pak-cheung Chan....Duran<br />
	　　　　　　秦沛 Paul Chun....King Ng Sam Kwai<br />
	　　　　　　刘松仁 Damian Lau....Chan, Master of the Heaven &amp; Earth Society<br />
	　　　　　　罗兰 Lan Law....Single Hand Nun<br />
	　　　　　　林青霞 Brigitte Lin....Lone-er/Mr. Dragon No. One<br />
	　　　　　　吴君如 Sandra Ng....Sister Bond<br />
	　　　　　　李嘉欣 Michelle Lee....Shang&#39;er Twin<br />
	　　　　　　汤镇业 Ken Tong....Ng Ying Hung<br />
	　　　　　　温兆伦 Siu-Lun Wan....Emperor Ning<br />
	　　　　　　任世官 Yee Kwan Yan....Fung Shek Fan (as Yee-Kwan Yang)<br />
	　　　　　　邱淑贞 Chingmy Yau....Princess Kin Ning<br />
	　　　　　　袁洁莹 Fennie Yuen....Shang&#39;er Twin<br />
	　　　　　　郑家生 Ka Sang Cheung....Imperial Guard (as Ka-sung Cheng)<br />
	　　　　　　马海伦 Helen Ma<br />
	　　　　　　杨菁菁 Ching-Ching Yeung</p>
<p>
	【内容简介】</p>
<p>
	　　本片剧情延续上集，但加添了韦小宝与七个老婆之间的风流艳史，令到娱乐效果更加活色生香。美女林青霞饰演神龙教主，此外尚有李嘉欣、袁洁莹、邱淑贞、陈德容等联合主演。影片前半部描写韦小宝与神龙教主之间从原来互相敌对变成大被同眠的有趣经过，后半部则描写康熙皇帝将御妹建宁公主赐婚给一方之霸的吴三桂之子吴应熊，韦小宝奉命护送出嫁，使他备感苦恼，因为她肚中已怀了小宝的骨肉，所以他想尽办法阻挠这宗婚事。不料康熙终于知悉小宝与天地会正暗谋向朝廷造反，使君臣之间的关系发生歪变。</p>
<p>
	<img alt="" src="http://img165.poco.cn/mypoco/myphoto/20110927/12/62564813201109271251533902882165412_001.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img165.poco.cn/mypoco/myphoto/20110927/12/62564813201109271251533902882165412_000.jpg" style="width: 720px; height: 405px" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="&#13;&#10;ftp://dy125:piaohua@dy125.piaohua.com:6008/飘花电影piaohua.com鹿鼎记1BD国粤双语中字1024高清.mkv">ftp://dy125:piaohua@dy125.piaohua.com:6008/飘花电影piaohua.com鹿鼎记1BD国粤双语中字1024高清.mkv</a></td>
		</tr>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="&#13;&#10;ftp://dy125:piaohua@dy125.piaohua.com:6008/飘花电影piaohua.com鹿鼎记2BD国粤双语中字1024高清.mkv">ftp://dy125:piaohua@dy125.piaohua.com:6008/飘花电影piaohua.com鹿鼎记2BD国粤双语中字1024高清.mkv</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1C20230-21b6.jpg{/dede:field}
