{dede:field name='keywords'}格莫拉/俄摩拉城/罪恶之城娥摩拉{/dede:field}
{dede:field name='description'}格莫拉/俄摩拉城/罪恶之城娥摩拉BD中英双字1024/1280高清迅雷下载、免费下载，格莫拉/俄摩拉城/罪恶之城娥摩拉BD中英双字1024/1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}格莫拉/俄摩拉城/罪恶之城娥摩拉BD中英双字1024/1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-07{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://3e:3e@d3.3edyy.com:121/【3E电影院www.eee4.org】格莫拉BD中英双字1024x576高清版.rmvb" target="_blank{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MP05DP-523X.jpg{/dede:field}
