<?php
$z[0]=Array("field","靖国神社迅雷下载，免费下载，Gv",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","靖国神社迅雷下载、免费下载，靖国神社Gvod高清在线播放，剧情介绍等。",73,183);
$z[1][4]['name']="description";
$z[2]=Array("field","靖国神社",185,231);
$z[2][4]['name']="title";
$z[3]=Array("field","",233,272);
$z[3][4]['name']="writer";
$z[4]=Array("field","",274,313);
$z[4][4]['name']="source";
$z[5]=Array("field","2008-10-18",315,365);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",367,404);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://3e6:3e6@d5.eee4.com:925/[3E电影站www.eee4.com]靖国神社.rmvb\" target=_blank>ftftp://3e6:3e6@d5.eee4.com:925/[3E电影站www.eee4.com]靖国神社.rmvb</A></TD></TR></TBODY></TABLE></div><ul class=\"mmlist",406,646);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MP454210-5XV.jpg",648,730);
$z[8][4]['name']="litpic";

?>