{dede:field name='keywords'}周杰伦超时代演唱会(深藏版)(香{/dede:field}
{dede:field name='description'}周杰伦超时代演唱会(深藏版)(香港版)[DVD国语中字]迅雷下载、免费下载，周杰伦超时代演唱会(深藏版)(香港版)[DVD国语中字]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}周杰伦超时代演唱会(深藏版)(香港版)[DVD国语中字]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-01-27{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://5e:5e@d6.3edyy.com:616/【3E看看www.3ekk.com】周杰伦超时代演唱会[深藏版][香港版]CD1.rmvb" target=_blank>ftftp://5e:5e@d6.3edyy.com:616/【3E看看www.3ekk.com】周杰伦超时代演唱会[深藏版][香港版]CD1.rmvb</A></TD></TR></TBODY></TABLE>CD2：<BR>
<TABLE style="BORDER-BOTTOM: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-RIGHT: #cccccc 1px dotted" border=0 cellSpacing=0 cellPadding=6 width="95%" align=center>
<TBODY>
<TR>
<TD style="WORD-WRAP: break-word" bgColor=#fdfddf><A href="ftftp://5e:5e@d6.3edyy.com:616/【3E看看www.3ekk.com】周杰伦超时代演唱会[深藏版][香港版]CD2.rmvb" target=_blank>ftftp://5e:5e@d6.3edyy.com:616/【3E看看www.3ekk.com】周杰伦超时代演唱会[深藏版][香港版]CD2.rmvb</A></TD></TR></TBODY></TABLE></div><ul class="mmlist{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MQ464c0-45B1.jpg{/dede:field}
