<?php
$z[0]=Array("field","周杰伦超时代演唱会(深藏版)(香",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","周杰伦超时代演唱会(深藏版)(香港版)[DVD国语中字]迅雷下载、免费下载，周杰伦超时代演唱会(深藏版)(香港版)[DVD国语中字]Gvod高清在线播放，剧情介绍等。",72,260);
$z[1][4]['name']="description";
$z[2]=Array("field","周杰伦超时代演唱会(深藏版)(香港版)[DVD国语中字]",262,347);
$z[2][4]['name']="title";
$z[3]=Array("field","",349,388);
$z[3][4]['name']="writer";
$z[4]=Array("field","",390,429);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-01-27",431,481);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",483,520);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://5e:5e@d6.3edyy.com:616/【3E看看www.3ekk.com】周杰伦超时代演唱会[深藏版][香港版]CD1.rmvb\" target=_blank>ftftp://5e:5e@d6.3edyy.com:616/【3E看看www.3ekk.com】周杰伦超时代演唱会[深藏版][香港版]CD1.rmvb</A></TD></TR></TBODY></TABLE>CD2：<BR>\r\n<TABLE style=\"BORDER-BOTTOM: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-RIGHT: #cccccc 1px dotted\" border=0 cellSpacing=0 cellPadding=6 width=\"95%\" align=center>\r\n<TBODY>\r\n<TR>\r\n<TD style=\"WORD-WRAP: break-word\" bgColor=#fdfddf><A href=\"ftftp://5e:5e@d6.3edyy.com:616/【3E看看www.3ekk.com】周杰伦超时代演唱会[深藏版][香港版]CD2.rmvb\" target=_blank>ftftp://5e:5e@d6.3edyy.com:616/【3E看看www.3ekk.com】周杰伦超时代演唱会[深藏版][香港版]CD2.rmvb</A></TD></TR></TBODY></TABLE></div><ul class=\"mmlist",522,1372);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MQ464c0-45B1.jpg",1374,1456);
$z[8][4]['name']="litpic";

?>