{dede:field name='keywords'}科技反恐[DVD中字1024x576高清版{/dede:field}
{dede:field name='description'}科技反恐[DVD中字1024x576高清版]迅雷下载、免费下载，科技反恐[DVD中字1024x576高清版]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}科技反恐[DVD中字1024x576高清版]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-22{/dede:field}
{dede:field name='body'}<p>
	<img alt="" border="0" onload="attachimg(this, 'load')" src="/uploads/allimg/c120525/133O096301P-1H43.jpg" /></p>
<p>
	国家地理][科技反恐][720P.HDTV-RMVB][中文字幕] DVD中字1024x576高清版</p>
<p>
	恐怖主义，无时无刻都在威胁着你的安全。国家地理透过独家视角，向你展示目前世界上最先进的反恐装备。<br />
	<br />
	Terrorism. An enemy that can strike anytime, anywhere. Around the world, counter-terrorism experts race to develop new strategies to stay one step ahead of the enemy: jetliners that repel heat-seeking missiles, chemicals that make ordinary walls blast-proof devices that can rescue survivors from skyscrapers, robots that can detect and dismantle dirty bombs, and high-tech weapons and unmanned vehicles that can take out terrorists before they kill.</p>
<p>
	【电影截图】：<br />
	电影来源：http://www.bluemv.com<br />
	<img border="0" src="/uploads/allimg/c120525/133O096305F-2b21.jpg" />&nbsp;<br />
	<img border="0" src="/uploads/allimg/c120525/133O0963120-3Z34.jpg" />&nbsp;<br />
	<img border="0" src="/uploads/allimg/c120525/133O09631Y0-41A8.jpg" />&nbsp;<br />
	<img border="0" src="/uploads/allimg/c120525/133O09632Q0-56395.jpg" /></p>
<p>
	2009-02-01 09:32:12 开始连接......<br />
	2009-02-01 09:32:12 开始搜索候选资源......<br />
	2009-02-01 09:32:12 搜索到22个候选资源<br />
	2009-02-01 09:32:12 使用候选资源进行连接......<br />
	2009-02-01 09:32:13 搜索到41个候选资源<br />
	2009-02-01 09:32:13 使用候选资源进行连接......<br />
	2009-02-01 09:32:13 文件创建成功，开始下载数据......<br />
	2009-02-01 09:32:16 用户取消下载&nbsp;&nbsp; 本文来自：http://www.bluemv.com</p>
<p>
	（一律使用迅雷下载）<br />
	国家地理杂志《科技反恐》DVD中字1024x576高清版 －来自[3E电影站 eee4.com]：<img border="0" src="http://www.eee4.com/templets/img/down.jpg" /></p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				ftp://e25:e25@xl2.eee4.com:9916/[3E电影站www.eee4.com]科技反恐[DVD中字1024x576高清版].rmvb</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O09633X0-M161.jpg{/dede:field}
