<?php
$z[0]=Array("field","盛夏猎户座/盛夏的猎户座[DVD中",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","盛夏猎户座/盛夏的猎户座[DVD中字]迅雷下载、免费下载，盛夏猎户座/盛夏的猎户座[DVD中字]Gvod高清在线播放，剧情介绍等。",72,230);
$z[1][4]['name']="description";
$z[2]=Array("field","盛夏猎户座/盛夏的猎户座[DVD中字]",232,302);
$z[2][4]['name']="title";
$z[3]=Array("field","",304,343);
$z[3][4]['name']="writer";
$z[4]=Array("field","",345,384);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-04-08",386,436);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",438,475);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://4e:4e@m1.3edyy.com:1456/【3E电影院www.eee4.cc】盛夏猎户座.rmvb\" target=_blank>ftftp://4e:4e@m1.3edyy.com:1456/【3E电影院www.eee4.cc】盛夏猎户座.rmvb</A></TD></TR></TBODY></TABLE></div><ul class=\"mmlist",477,723);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MP611420-23O9.jpg",725,808);
$z[8][4]['name']="litpic";

?>