<?php
$z[0]=Array("field","监守自盗[BD中英双字1024x576高",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","监守自盗[BD中英双字1024x576高清版]迅雷下载、免费下载，监守自盗[BD中英双字1024x576高清版]Gvod高清在线播放，剧情介绍等。",72,234);
$z[1][4]['name']="description";
$z[2]=Array("field","监守自盗[BD中英双字1024x576高清版]",236,308);
$z[2][4]['name']="title";
$z[3]=Array("field","",310,349);
$z[3][4]['name']="writer";
$z[4]=Array("field","",351,390);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-03-11",392,442);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",444,481);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://4e:4e@m1.eee4.cc:1589/【3E看看www.3ekk.com】监守自盗[DVD中字].rmvb\" target=_blank>ftftp://4e:4e@m1.eee4.cc:1589/【3E看看www.3ekk.com】监守自盗[DVD中字].rmvb</A></TD></TR></TBODY></TABLE><STRONG><FONT color=#ff0000 size=2><BR>2011年奥斯卡最佳纪录片《监守自盗》BD中英双字1024x576高清版 [下载地址]：<IMG border=0 src=\"httftp://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg",483,911);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MQ4I050-22458.jpg",913,996);
$z[8][4]['name']="litpic";

?>