{dede:field name='keywords'}2007年TVB8金曲榜颁奖典礼迅雷下{/dede:field}
{dede:field name='description'}2007年TVB8金曲榜颁奖典礼迅雷下载、免费下载，2007年TVB8金曲榜颁奖典礼Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}2007年TVB8金曲榜颁奖典礼{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2007-12-18{/dede:field}
{dede:field name='body'}12月16日晚，“2007年TVB8金曲榜颁奖典礼”在将军澳电视广播城盛大举行。以下为完全获奖名单： 编辑来源　www.eee4.com
<P>金曲奖<BR>张靓颖《这该死的爱》<BR>潘玮柏《玩酷》<BR>陈奕迅《淘汰》<BR>张韶涵《不痛》<BR>黄义达《完整演出》<BR>曹格《SUPERMAN》<BR>Twins《飘零燕》<BR>何韵诗《木纹》<BR>水木年华《借我一生》<BR>容祖儿《小小》</P>
<P>最佳新人<BR>金奖：尚雯婕<BR>银奖：厉娜<BR>铜奖：陈柏宇</P>
<P>最佳唱作歌手<BR>金奖：曹格<BR>银奖：陈秋霞<BR>铜奖：方大同</P>
<P>最佳组合<BR>金奖：Twins<BR>银奖：水木年华<BR>铜奖：Krusty</P>
<P>全球观众最爱粤语歌曲&nbsp;&nbsp;&nbsp; 编辑来源　www.eee4.com<BR>容祖儿《心花怒放》<BR>张敬轩《酷爱》<BR>陈奕迅《富士山下》</P>
<P>最佳音乐录影带演绎：蔡依林《特务J》&nbsp;&nbsp; 编辑来源　www.eee4.com</P>
<P>最佳作曲<BR>曹格《SUPERMAN》　作曲： 曹格</P>
<P>最佳作词<BR>孙燕姿《我怀念的》　作词：姚若龙</P>
<P>最佳编曲<BR>陈奕迅《淘汰》　编曲：C.Y. Kong</P>
<P>最佳歌曲监制<BR>陈奕迅《淘汰》　监制：Davy Chan、C.Y. Kong、陈奕迅</P>
<P>内地观众最爱男歌手：潘玮柏 <BR>内地观众最爱女歌手：张靓颖</P>
<P>最受欢迎男歌手：陈奕迅 <BR>最受欢迎女歌手：张韶涵 </P>
<P>金曲金奖：潘玮柏《玩酷》&nbsp; 编辑来源　www.eee4.com</P>
<P><IMG height=145 alt="" src="http://pic.piaohua.com/0701pic/allimg/071218/0243460.jpg" width=560 border=0></P>
<P><IMG alt=图文：Twins现场演唱获奖金曲《飘零燕》 src="http://pic.piaohua.com/0701pic/allimg/071218/0243461.jpg" border=1><IMG alt=图文：TVB8金曲颁奖礼-潘玮柏举奖杯发表感言 src="http://pic.piaohua.com/0701pic/allimg/071218/0243462.jpg" border=1></P><p>2007-12-18 02:23:11 开始连接......<br>2007-12-18 02:23:13 开始搜索候选资源......<br>2007-12-18 02:23:14 搜索到31个候选资源<br>2007-12-18 02:23:16 使用候选资源进行连接......<br>2007-12-18 02:23:19 搜索到26个候选资源<br>2007-12-18 02:23:21 使用候选资源进行连接......<br>2007-12-18 02:23:23 文件创建成功，开始下载数据......<br>2007-12-18 02:23:25 用户取消下载&nbsp;&nbsp; 本文来自 www.eee4.com</p>
（直接可能无法下载，一律使用<a href="http://pstatic.xunlei.com/about/product/down_xl5.htm" target="_blank">迅雷下载</a>）<br>
《2007年TVB8金曲榜颁奖典礼》 下载地址：<IMG src="/templets/img/down.jpg" border=0><br>
<table style="BORDER-RIGHT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; BORDER-BOTTOM: #cccccc 1px dotted" cellspacing="0" cellpadding="6" width="95%" align="center" border="0">
    <tbody>
        <tr>
            <td style="WORD-WRAP: break-word" bgcolor="#fdfddf"><anchor></anchor><a href="ftp://eee4:eee4.com@xl.eee4.com/TVB8金曲榜/[3E迅雷电影站www.eee4.com]07年TVB8金曲榜颁奖典礼.rm" target="_blank">ftp://eee4:eee4.com@xl.eee4.com/TVB8金曲榜/[3E迅雷电影站www.eee4.com]07年TVB8金曲榜颁奖典礼.rm</a></td>
        </tr>
    </tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O16119250-31V5.jpg{/dede:field}
