{dede:field name='keywords'}X-man060723迅雷下载，免费下载{/dede:field}
{dede:field name='description'}X-man060723迅雷下载、免费下载，X-man060723Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}X-man060723{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2006-08-04{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://beautiful38.vicp.net/X-Man7-23/1.rmvb" target=_blank>ftftp://beautiful38.vicp.net/X-Man7-23/1.rmvb</A><BR><BR><FONT face=Verdana>2006-07-29 15:49:47 开始连接......<BR>2006-07-29 15:49:47 开始搜索候选资源......<BR>2006-07-29 15:49:49 原始资源连接成功，得到的文件长度： 360305194<BR>2006-07-29 15:49:49 开始创建文件......<BR>2006-07-29 15:49:49 文件创建成功，开始下载数据......<BR>2006-07-29 15:49:49 搜索到40个候选资源<BR>2006-07-29 15:50:14 用户取消下载<BR></FONT></SPAN> <br></div><ul class="mmlist{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MO60K30-35C0.gif{/dede:field}
