<?php
$z[0]=Array("field","X-man060723迅雷下载，免费下载",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","X-man060723迅雷下载、免费下载，X-man060723Gvod高清在线播放，剧情介绍等。",72,188);
$z[1][4]['name']="description";
$z[2]=Array("field","X-man060723",190,239);
$z[2][4]['name']="title";
$z[3]=Array("field","",241,280);
$z[3][4]['name']="writer";
$z[4]=Array("field","",282,321);
$z[4][4]['name']="source";
$z[5]=Array("field","2006-08-04",323,373);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",375,412);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://beautiful38.vicp.net/X-Man7-23/1.rmvb\" target=_blank>ftftp://beautiful38.vicp.net/X-Man7-23/1.rmvb</A><BR><BR><FONT face=Verdana>2006-07-29 15:49:47 开始连接......<BR>2006-07-29 15:49:47 开始搜索候选资源......<BR>2006-07-29 15:49:49 原始资源连接成功，得到的文件长度： 360305194<BR>2006-07-29 15:49:49 开始创建文件......<BR>2006-07-29 15:49:49 文件创建成功，开始下载数据......<BR>2006-07-29 15:49:49 搜索到40个候选资源<BR>2006-07-29 15:50:14 用户取消下载<BR></FONT></SPAN> <br></div><ul class=\"mmlist",414,958);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MO60K30-35C0.gif",960,1042);
$z[8][4]['name']="litpic";

?>