{dede:field name='keywords'}国家地理－迪拜神奇世界岛[DVD中{/dede:field}
{dede:field name='description'}国家地理－迪拜神奇世界岛[DVD中字1024x576高清版]迅雷下载、免费下载，国家地理－迪拜神奇世界岛[DVD中字1024x576高清版]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}国家地理－迪拜神奇世界岛[DVD中字1024x576高清版]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-22{/dede:field}
{dede:field name='body'}<p>
	【英文片名】National Geographic - Megastructures: World Island Wonder<br />
	【中文片名】《国家地理 - 迪拜神奇世界岛》国家地理伟大工程巡礼DVD中字1024x576高清版<br />
	【国　　家】美国<br />
	【类　　别】纪录<br />
	【片　　源】HDTV，1080i<br />
	【官方网站】：<a href="http://www.bluemv.com">http://www.bluemv.com</a><br />
	【画面尺寸】1024 x 576<br />
	【语　　言】英语<br />
	【字　　幕】简体中文<br />
	【时　　长】46m58s<br />
	<br />
	【内容简介】<br />
	　　迪拜正努力要成为全球顶尖的观光胜地,棕榈岛的兴建,把这个酋长国的海岸线几乎加长了三倍。棕榈岛是棕榈形的庞大海上城市,现在迪拜为了稳居世界舞台决定打造世界岛。这是在阿拉伯湾兴建的３百座人工岛，是有史以来最大的土地填筑工程，人类从来没有完成或尝试过规模如此宏大的工程。根据酋长的要求，世界岛必须只用自然元素兴建，而且必须对抗自然界最大的毁灭力量－－大海。</p>
<p>
	<img src="http://img.album.pchome.net/54/68/43/05/db1e28d24695d490b17eefb45bb352be.jpg" /></p>
<p>
	【电影截图】：<br />
	电影来源：www.eee4.com<br />
	<a href="http://img.album.pchome.net/54/68/43/05/5de77a225c860e26b1ae498881f79374.jpg" target="_blank"><img border="0" src="http://img.album.pchome.net/54/68/43/05/5de77a225c860e26b1ae498881f79374.jpg" /></a>&nbsp;<br />
	<a href="http://img.album.pchome.net/54/68/43/05/b0612739e4546c52351e5620b9fbc4df.jpg" target="_blank"><img border="0" src="http://img.album.pchome.net/54/68/43/05/b0612739e4546c52351e5620b9fbc4df.jpg" /></a>&nbsp;<br />
	<a href="http://img.album.pchome.net/54/68/43/05/f68059d4bf2810be56d5e1a86f89ba1b.jpg" target="_blank"><img border="0" src="http://img.album.pchome.net/54/68/43/05/f68059d4bf2810be56d5e1a86f89ba1b.jpg" /></a>&nbsp;<br />
	<a href="http://img.album.pchome.net/54/68/43/05/2cd0382b428335a37555aa9cc9ea31b5.jpg" target="_blank"><img border="0" src="http://img.album.pchome.net/54/68/43/05/2cd0382b428335a37555aa9cc9ea31b5.jpg" /></a></p>
<p>
	2009-01-12 07:21:12 开始连接......<br />
	2009-01-12 07:21:12 开始搜索候选资源......<br />
	2009-01-12 07:21:12 搜索到22个候选资源<br />
	2009-01-12 07:21:12 使用候选资源进行连接......<br />
	2009-01-12 07:21:13 搜索到41个候选资源<br />
	2009-01-12 07:21:13 使用候选资源进行连接......<br />
	2009-01-12 07:21:13 文件创建成功，开始下载数据......<br />
	2009-01-12 07:21:16 用户取消下载&nbsp;&nbsp; 本文来自：www.eee4.com</p>
<p>
	（一律使用<a href="http://www.eee4.com/soft.htm" target="_blank">迅雷下载</a>）<br />
	国家地理伟大工程巡礼《迪拜神奇世界岛》DVD中字1024x576高清版 －来自[3E电影站 eee4.com]：<img border="0" src="http://www.eee4.com/templets/img/down.jpg" /></p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://e19:e19@xl2.eee4.com:9916/[3E电影站www.eee4.com]迪拜神奇世界岛[DVD中字1024x576高清版].rmvb" target="_blank">ftp://e19:e19@xl2.eee4.com:9916/[3E电影站www.eee4.com]迪拜神奇世界岛[DVD中字1024x576高清版].rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O161DR0-31950.jpg{/dede:field}
