{dede:field name='keywords'}希林公主/雪馨[DVD中字]迅雷下载{/dede:field}
{dede:field name='description'}希林公主/雪馨[DVD中字]迅雷下载、免费下载，希林公主/雪馨[DVD中字]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}希林公主/雪馨[DVD中字]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2009-12-04{/dede:field}
{dede:field name='body'}<P><IMG src="/uploads/allimg/c120525/133O09339B0-22W28.jpg">&nbsp;<BR><IMG src="/uploads/allimg/c120525/133O093405P-23M46.jpg"></P>
<P><BR>◎ 译　　名：希林公主/雪馨<BR>◎ 片　　名：Copie conforme<BR>◎ 年　　份：2009<BR>◎ 类　　别：剧情<BR>◎ 地　　区：伊朗/法国/意大利<BR>◎ 对白语言：波斯语/法语<BR>◎ 字　　幕：中文字幕<BR>◎ 导　　演：阿巴斯&#8226;基亚罗斯塔米 Abbas Kiarostami3e<BR>◎ 编　　剧：阿巴斯&#8226;基亚罗斯塔米 Abbas Kiarostami<BR>◎ 主　　演：朱丽叶&#8226;比诺什 Juliette Binoche<BR>　　　　　　 萨米&#8226;弗雷 Sami Frey<BR>　　　　　 　William Shimell</P>
<P><BR>《生生长流》伊朗导演阿巴斯&#8231;奇亚洛斯塔米，请来茱莉叶毕诺许与112名伊朗女性一同观看电影，入选为威尼斯影展观摩电影。</P>
<P>◎ 简　　介：</P>
<P>　　伊朗电影大师阿巴斯新作。这是一部实验性极强的艺术电影，我们只可以听到这个故事中的对白和声响，却没有任何这个故事的画面出现，女演员的头发被稀薄的丝纱掩盖着，观看着眼前的影片。她们为眼前片中女主人公的命运和爱情所牵挂。她们的倾听，她们的反应，都以一个接一个的特写镜头显示在屏幕上，只在偶尔有两个一起或者三个一起的时候。但是，这并非一部纪录片，而女演员们也不是真的在看电影，她们只是盯着一片黑幕，倾听着古诗。基亚罗斯塔米在他的起居室里拍摄了整部电影，只用三把椅子作为全部布景。她们用手势、表情、皱眉和眼神，来表露她们发现被人观察的尴尬情绪的程度。</P>
<P>◎ 关于影片：</P>
<P>　　作为被给予了很多尊重的一个具有独特风格的现代导演，阿巴斯&#8226;基亚罗斯塔米的最新电影不可能被忽视。但是，《希林公主》这部怪诞的电影，说明基亚罗斯塔米已经抛弃了当下电影普遍的叙述方式，反而以一种冒险的实验性的电影语言作为代替。而且，导演一直关注的观众电影下载则成了影片主角。总之，该片没有考虑商业风险的打算。这是引人深思的一部电影，但不会是电影院中所能见到的大众电影。阿巴斯将12世纪波斯古诗《希林（Shirin）和考斯洛（Khosrow）》的历史传奇搬上大屏幕。特殊的是，我们只可以听到这个故事中的对白和声响，却没有任何这个故事的画面出现，甚至没有放映大屏幕的镜头闪现。只有阿巴斯邀请的 114名女演员，其中朱丽叶&#8226;比诺什有幸参与了该片的拍摄。这些女演员的头发被稀薄的丝纱掩盖着，观看着眼前的影片。她们为眼前片中女主人公的命运和爱情所牵挂。她们的倾听，她们的反应，都以一个接一个的特写镜头显示在屏幕上，只在偶尔有两个一起或者三个一起的时候。这部92分钟的电影，即使对于导演最忠实的粉丝来说也似乎有点过长，但是其中也有一些美妙的基亚罗斯塔米式的亮点——美丽而明亮的女人的眼睛和一些很熟悉的伊朗电影中的演员。她们表情的镇定沉着，传达给我们看到的不仅仅是一张面孔，而是一扇灵魂的窗。<BR></P>
<P>【电影截图】：<BR><BR><IMG onclick=zoom(this) alt="" src="/uploads/allimg/c120525/133O093411Z-24M64.jpg" onload="attachimg(this, 'load')" border=0>&nbsp;<BR><IMG onclick=zoom(this) alt="" src="/uploads/allimg/c120525/133O09342960-25X28.jpg" onload="attachimg(this, 'load')" border=0>&nbsp;<BR><IMG onclick=zoom(this) alt="" src="/uploads/allimg/c120525/133O093523P-2E156.jpg" onload="attachimg(this, 'load')" border=0>&nbsp;<BR><IMG onclick=zoom(this) alt="" src="/uploads/allimg/c120525/133O09354Y0-2G1D.jpg" onload="attachimg(this, 'load')" border=0><BR></P><br>  [下载地址]：<IMG src="http://www.eee4.com/templets/img/down.jpg" border=0><br>
<table style="BORDER-RIGHT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; BORDER-BOTTOM: #cccccc 1px dotted" cellspacing="0" cellpadding="6" width="95%" align="center" border="0">
    <tbody>
        <tr>
            <td style="WORD-WRAP: break-word" bgcolor="#fdfddf">ftp://3e:3e@www2.eee4.com:929/[3E电影站www.eee4.cn]希林公主.rmvb</td>
        </tr>
    </tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O09360420-296212.jpg{/dede:field}
