{dede:field name='keywords'}布列斯特要塞BD1280高清迅雷下载{/dede:field}
{dede:field name='description'}布列斯特要塞BD1280高清迅雷下载、免费下载，布列斯特要塞BD1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}布列斯特要塞BD1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-02-02{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://3e:3e@d3.3edyy.com:121/【3E电影院www.eee4.org】布列斯特要塞BD中字1024x576高清版.rmvb" target="_blank{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MP5Gb0-31008.jpg{/dede:field}
