{dede:field name='keywords'}夺命手术BD中英双字1024/1280高{/dede:field}
{dede:field name='description'}夺命手术BD中英双字1024/1280高清迅雷下载、免费下载，夺命手术BD中英双字1024/1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}夺命手术BD中英双字1024/1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-02-13{/dede:field}
{dede:field name='body'}<p>
	<img border="0" src="http://cdn3b.dvdempire.org/products/63/1388863h.jpg" style="max-width: 750px; max-height: 750px" /></p>
<p>
	◎译　　名　《夺命手术》惊悚犯罪大片DVD中英双字幕（高清版）<br />
	◎片　　名　Awake<br />
	◎年　　代　2007<br />
	◎国　　家　美国<br />
	◎类　　别　犯罪/惊悚<br />
	◎语　　言　英语<br />
	◎字　　幕　中英双字<br />
	◎IMDB评分 6.5/10&nbsp; 16,014 votes<br />
	◎IMDB链接 http://www.imdb.com/title/tt0211933<br />
	◎文件格式　X264 + AC3<br />
	◎视频尺寸　880 X 486<br />
	◎文件大小　1CD<br />
	◎片　　长　84 MiN<br />
	◎导　　演　Joby Harold<br />
	◎主　　演　海登&middot;克里斯滕森 Hayden Christensen .....Clay<br />
	　　　　　　莉娜&middot;奥琳 Lena Olin<br />
	　　　　　　杰西卡&middot;阿尔芭 Jessica Alba .....Sam<br />
	　　　　　　泰伦斯&middot;霍华德 Terrence Dashon Howard<br />
	　　　　　　斯特沃特&middot;萨默斯 Stewart Summers .....Extra (uncredited)<br />
	　　　　　　Steven Hinkle .....Young Clay<br />
	　　　　　　Poorna Jagannathan .....Neyer&#39;s nurse<br />
	　　　　　　Sam Robards<br />
	　　　　　　Court Young<br />
	　　　　　　Dennis Funny .....Subway thug (uncredited)<br />
	　　　　　　Charlie Hewson .....Brian the Orderly<br />
	　　　　　　Alexa Karter .....Tara LeCasa<br />
	　　　　　　Christopher Maggi .....Wiseguy<br />
	　　　　　　克里斯托弗&middot;麦克唐纳 Christopher McDonald .....Dr. Larry Lupin<br />
	　　　　　　Thomas A. McMahon .....Officer McMahon<br />
	　　　　　　Pedersen Jennifer Jennifer Pedersen .....Jennifer<br />
	　　　　　　Joshua Rollins .....Funeral Minister<br />
	　　　　　　Kae Shimizu .....Interpreter<br />
	　　　　　　Lee Wong .....Mr. Waturi<br />
	<br />
	◎简　　介　<br />
	<br />
	　　这里关注的是一种在医学上非常罕见的现象--麻醉觉醒，即病人被麻醉之后，在手术过程中恢复了知觉或感觉到了疼痛，但身体却不能动弹。根据个体差异，病人感觉到痛苦的程度也是完全不一样的，而这种情况在手术中发生的比例是千分之一或千分之二，是一种严重的全麻术里的并发症，会给病人造成无法弥补的巨大精神创伤。<br />
	<br />
	　　故事从一开始，就用滚动的字幕交待，这种&ldquo;麻醉觉醒&rdquo;，近期来在手术台上时有发生，至少比你预期得要多--每700人中就会产生一个病例。22岁的克莱顿&middot;比尔斯福德二世是金融界的新生力量，他靠着老爸留下的十亿家产，过着如鱼得水的富足生活，还被评为&ldquo;年度最受女性期待的男人&rdquo;，惟一美中不足的是，自从他的父亲死后，他的母亲莉莉丝就变成了一位典型的&ldquo;直升机母亲&rdquo;：　无所不在、无所不管，24小时监控着他，在他上空盘旋，介入他的一切。即使如此，克莱顿还是偷偷和私人助理萨曼塔私订终身。另外，克莱顿的身体状况也甚忧，他有严重的心脏病，惟一能够痊愈的方式就是做移植手术，可是全世界有多少像他一样的心脏病患者在翘首企盼着，提供器官捐赠的却是寥寥无几。<br />
	<br />
	　　命运的齿轮突然开始咬合起来，莉莉丝知道了克莱顿和萨曼塔之间的情事，她如预期的百般阻挠，如此做法反而让克莱顿决定与萨曼塔尽快完婚&hellip;&hellip;就在婚礼举行的当天晚上，克莱顿突然接到莉莉丝的电话，合适的心脏已经准备就位，马上可以做移植手术，但是她希望可以使用自己找来的世界级的外科医生，代替克莱顿的好友杰克&middot;哈珀医生，因为他已经有4宗医疗事故缠身。倔强的克莱顿却坚持让杰克给自己动手术，否则他就不进手术室，莉莉丝再次无奈地妥协了。<br />
	<br />
	　　麻醉生效，克莱顿被推进了手术室&hellip;&hellip;但是当克莱顿的胸腔完全被手术刀打开之后，他竟然苏醒了，严格地说来是意识和感觉恢复了，但身体仍然不能动弹，可怜的克莱顿成了700个人中的&ldquo;幸运儿&rdquo;，他感觉到了冰冷的利刃，钻心的痛楚，却没办法让别人知道。当手术刀在他的内脏上来回移动时，他发出了只有自己能够听得到的恐惧的尖叫声。<br />
	<br />
	　　除此之外，身体麻醉头脑清醒的克莱顿还听到了一些他平时绝对没办法知晓的秘密，医生与护士的闲谈中透露了太多信息，既有带有欺骗性的阴谋诡计，也让他知晓了一些他生命中最为肮脏污秽的事情，然而，要如何从手术中毫发无损地活过来，才是他真正需要担心的事&hellip;&hellip;最终，巨大的疼痛让克莱顿的意识开始和身体分离，然而他能做的，也只是眼睁睁地看着那热乎乎、跳动着的心脏被拿出自己的胸膛。</p>
<p>
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://images.dvdempire.com/gen/movies/1430916h.jpg');" src="http://images.dvdempire.com/gen/movies/1430916h.jpg" /></p>
<p>
	【电影截图】：<br />
	电影来源：www.eee4.com<br />
	<br />
	<br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://img.album.pchome.net/54/68/06/00/5a9b2199f8838180efa57758111b8eff.jpg');" src="http://img.album.pchome.net/54/68/06/00/5a9b2199f8838180efa57758111b8eff.jpg" />&nbsp;<br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://img.album.pchome.net/54/68/06/00/6164b1119828411091f99a2189a228f8.jpg');" src="http://img.album.pchome.net/54/68/06/00/6164b1119828411091f99a2189a228f8.jpg" />&nbsp;<br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://img.album.pchome.net/54/68/06/00/877b191a96e19dd65658e1fd3486eb77.jpg');" src="http://img.album.pchome.net/54/68/06/00/877b191a96e19dd65658e1fd3486eb77.jpg" />&nbsp;<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://img.album.pchome.net/54/68/06/00/31e695e513e0e8b93d4257efd67ce005.jpg');" src="http://img.album.pchome.net/54/68/06/00/31e695e513e0e8b93d4257efd67ce005.jpg" /></p>
<p>
	&nbsp;惊悚犯罪大片《夺命手术》DVD中英双字幕（高清版） </p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://d28:d28@dm.eee4.com:1205/[3E电影站www.eee4.com]夺命手术DVD中英双字.rmvb" target="_blank">ftp://d28:d28@dm.eee4.com:1205/[3E电影站www.eee4.com]夺命手术DVD中英双字.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				&nbsp;<a href="ftp://dy44:piaohua@dy44.piaohua.com:1502/飘花电影piaohua.com夺命手术1024高清.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:1502/飘花电影piaohua.com夺命手术1024高清.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2804/飘花电影piaohua.com夺命手术1280高清.rmvb">&nbsp;ftp://dy44:piaohua@dy44.piaohua.com:2804/飘花电影piaohua.com夺命手术1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1505C10-54496.jpg{/dede:field}
