{dede:field name='keywords'}超级直升机[DVD中字1024x576高清{/dede:field}
{dede:field name='description'}超级直升机[DVD中字1024x576高清版]迅雷下载、免费下载，超级直升机[DVD中字1024x576高清版]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}超级直升机[DVD中字1024x576高清版]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2009-04-06{/dede:field}
{dede:field name='body'}<P>【影片译名】国家地理.伟大工程巡.超级直升机 DVD中字1024x576高清版<BR>【影片名称】Ultimate.Structures.Super.Copter.720p<BR>【影片格式】1024 x 576<BR>【时长】51分钟<BR>【语言】英文<BR>【类型】记录片<BR>【字幕】简体中文</P>
<P>　　最新的「超级直升机」身为先进机具，飞得又快又安静，前往直升机以往到不了的地方，就连内太空也不例外。EH101 超级直升机被誉为科技成就的突破。EH101等新设计也将更能防御攻击，因为使用了克薇拉复合材料，不仅能增加机身强度，同时亦达成轻量化。通过真实行动、现场模拟、惊人的资料片以及先进的电脑动画，我们赞叹着今日「超级直升机」的诞生，它是二十一世纪出奇的多用途直升机。<BR></P>
<P>【电影截图】：<BR><BR><a href="http://img.album.pchome.net/54/68/81/51/8da73a5ce2b2726ab587a357041cbd59.jpg" target="_blank"><IMG src="http://img.album.pchome.net/54/68/81/51/8da73a5ce2b2726ab587a357041cbd59.jpg" border=0></a>&nbsp;<BR>
<a href="http://img.album.pchome.net/54/68/81/51/655ab1a49dfce257fcdb56c2354699ae.jpg" target="_blank"><IMG src="http://img.album.pchome.net/54/68/81/51/655ab1a49dfce257fcdb56c2354699ae.jpg" border=0></a></P><br>（一律使用<a href="http://www.eee4.com/soft.htm" target="_blank">迅雷下载</a>）<br>
国家地理.伟大工程巡《超级直升机》DVD中字1024x576高清版  －来自[www.eee4.com]：<IMG src="http://www.eee4.com/templets/img/down.jpg" border=0><br>
<table style="BORDER-RIGHT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; BORDER-BOTTOM: #cccccc 1px dotted" cellspacing="0" cellpadding="6" width="95%" align="center" border="0">
    <tbody>
        <tr>
            <td style="WORD-WRAP: break-word" bgcolor="#fdfddf"><a href="ftp://e10:e10@xl2.eee4.com:9306/[3E电影站www.eee4.com]超级直升机DVD中字1024x576高清版.rmvb" target="_blank">ftp://e10:e10@xl2.eee4.com:9306/[3E电影站www.eee4.com]超级直升机DVD中字1024x576高清版.rmvb</a></td>
        </tr>
    </tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1615450-15I9.jpg{/dede:field}
