{dede:field name='keywords'}窈窕淑女BD高清迅雷下载，免费下{/dede:field}
{dede:field name='description'}窈窕淑女BD高清迅雷下载、免费下载，窈窕淑女BD高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}窈窕淑女BD高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-12-01{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20111201/00/62564813201112010034592016389085121_000.jpg" style="width: 650px; height: 1011px" /></p>
<p>
	◎中文　名　窈窕淑女<br />
	◎片　　名　My Fair Lady<br />
	◎年　　代　1964<br />
	◎国　　家　美国<br />
	◎类　　别　喜剧/家庭/音乐/爱情/剧情<br />
	◎IMDB评分　7.8/10 (16,686 votes)<br />
	◎IMDB链接　<a href="http://www.imdb.com/title/tt0058385/" target="_blank">http://www.imdb.com/title/tt0058385/</a> 　<br />
	◎片　　长　170 Min<br />
	◎导　　演　乔治 丘克 (George Cukor)<br />
	◎主　　演　奥黛丽 赫本 (Audrey Hepburn)<br />
	　　　　　　雷克斯 哈里森 (Rex Harrison)<br />
	　　　　　　斯坦利 霍洛韦 (Stanley Holloway)<br />
	　　　　　　Wilfrid Hyde-White<br />
	◎简　　介　<br />
	<br />
	　　亨利.希金斯（Henry Higgins）是一名固执傲慢的语言学教授。有一天他遇到了言语粗俗的卖花女伊莉莎.多莉特（Eliza Doolittle），告诉她一个人的语音标志着这个人的社会地位，如果她改进发音就可能会有一份体面的工作。教授回家后，遇到了同行皮克林（Pickering）上校，他告诉上校他能在六个月内把一个下层社会的女子培养成为上流社会的淑女。上校与教授打赌此事不可能。第二天恰好伊莉莎来了，在上校的帮助下，她成了教授的学生。经过刻苦学习，她取得了巨大进步，变得谈吐高雅、仪态端庄。最后在一次大型舞会上，她被介绍给上层社会，赢得了众人的赞美，并被皇家语音专家认为是某国的公主。教授回家后，兴高采烈地向上校索要赌金，完全忽视了伊莉莎，伊莉莎一怒之下，忿然离去。此时若有所失的教授才感到伊莉莎已成为自己生活的一部分。</p>
<p>
	<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20111201/00/62564813201112010033081686953825974_003.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20111201/00/62564813201112010033081686953825974_002.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20111201/00/62564813201112010033081686953825974_001.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20111201/00/62564813201112010033081686953825974_000.jpg" style="width: 720px; height: 405px" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>


<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="&#13;&#10;ftp://dy125:piaohua@dy125.piaohua.com:7253/飘花电影piaohua.com窈窕淑女BD中英双字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:7253/飘花电影piaohua.com窈窕淑女BD中英双字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1C2V50-29E2.jpg{/dede:field}
