<?php
$z[0]=Array("spaceurl","",143,161);
$z[1]=Array("face","",190,203);
$z[2]=Array("spaceurl","",244,262);
$z[3]=Array("uname","",281,295);
$z[4]=Array("spaceurl","",332,350);
$z[5]=Array("spaceurl","",397,415);
$z[6]=Array("spaceurl","",475,493);
$z[7]=Array("rankname","",602,620);
$z[8]=Array("jointime","",678,730);
$z[8][4]['function']="MyDate('Y-m-d H:m',@me)";
$z[9]=Array("logintime","",788,841);
$z[9][4]['function']="MyDate('Y-m-d H:m',@me)";

?>