{dede:field name='keywords'}猫和老鼠：绿野仙踪BD中英双字12{/dede:field}
{dede:field name='description'}猫和老鼠：绿野仙踪BD中英双字1280高清/奇幻奥兹王国中的猫和老迅雷下载、免费下载，猫和老鼠：绿野仙踪BD中英双字1280高清/奇幻奥兹王国中的猫和老Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}猫和老鼠：绿野仙踪BD中英双字1280高清/奇幻奥兹王国中的猫和老{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-09-17{/dede:field}
{dede:field name='body'}<p>
	◎译　　名　猫和老鼠：绿野仙踪ZwM - <br />
	◎片　　名　Tom And Jerry The Wizard Of OzZwM - <br />
	◎年　　代　2011ZwM - <br />
	◎国　　家　美国ZwM - <br />
	◎类　　别　动画/家庭ZwM - <br />
	◎语　　言　英语ZwM - <br />
	◎字　　幕　中英双字幕ZwM - <br />
	◎IMDB评分 6.8/10 (52 votes)ZwM - <br />
	◎文件格式　 X264+DTSZwM - <br />
	◎视频尺寸　1280 x 720ZwM - <br />
	◎片　　长　59 minutesZwM - <br />
	◎导　　演　Spike BrandtZwM - <br />
	◎主　　演　Grey DelisleZwM - <br />
	　　　　　　Laraine NewmanZwM - <br />
	　　　　　　Kath SoucieZwM - <br />
	　　　　　　Todd StashwickZwM - <br />
	　　　　　　Rob PaulsenZwM - <br />
	　　　　　　Michael GoughZwM - <br />
	ZwM - <br />
	◎简　　介　ZwM - <br />
	ZwM - <br />
	华纳兄弟原创动画片将汉娜-巴伯拉公司的汤姆和杰瑞带入了L&middot;弗兰克&middot;保姆的奇幻奥兹王国中. 一同随行的还有多萝西, 她的狗图吐还有新发现的朋友, 胆小鬼狮子, 铁皮人和稻草人这三个经典动画形象.ZwM - <br />
	ZwM - <br />
	◎影片截图</p>
<p>
	<img alt="" src="/uploads/allimg/c120525/133O04C5630-124X9.jpg" style="width: 600px; height: 338px" /></p>
<p>
	<img alt="" src="/uploads/allimg/c120525/133O04CDZ-13ON.jpg" style="width: 600px; height: 338px" /></p>
<p>
	<img alt="" src="/uploads/allimg/c120525/133O04CL10-145649.jpg" style="width: 600px; height: 338px" /></p>
<p>
	[下载地址]： &nbsp;<img border="0" src="/uploads/allimg/c120524/133N2Z4FF-102231.jpg" />
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				</anchor>ftp://dy44:piaohua@dy44.piaohua.com:1583/飘花电影piaohua.com猫和老鼠：绿野仙踪BD中英双字1280高清.rmvb</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O04CSP-153A3.jpg{/dede:field}
