<?php
$z[0]=Array("field","圣斗士星矢剧场版4:,最终圣战的",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","圣斗士星矢剧场版4: 最终圣战的战士们BD国语中字1280高清迅雷下载、免费下载，圣斗士星矢剧场版4: 最终圣战的战士们BD国语中字1280高清Gvod高清在线播放，剧情介绍等。",72,272);
$z[1][4]['name']="description";
$z[2]=Array("field","圣斗士星矢剧场版4: 最终圣战的战士们BD国语中字1280高清",274,365);
$z[2][4]['name']="title";
$z[3]=Array("field","",367,406);
$z[3][4]['name']="writer";
$z[4]=Array("field","",408,447);
$z[4][4]['name']="source";
$z[5]=Array("field","2012-01-15",449,499);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",501,538);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://dy44:piaohua@dy44.piaohua.com:2627/飘花电影piaohua.com圣斗士星矢剧场版4最终圣战的战士们BD国语中字1280高清.rmvb",540,695);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MQ0XV0-51K1.jpg",697,778);
$z[8][4]['name']="litpic";

?>