{dede:field name='keywords'}至尊对决/现金BD中英双字1280高{/dede:field}
{dede:field name='description'}至尊对决/现金BD中英双字1280高清迅雷下载、免费下载，至尊对决/现金BD中英双字1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}至尊对决/现金BD中英双字1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-03-03{/dede:field}
{dede:field name='body'}<p>
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://photo9.zxip.com/albums9/folder18/14189/20081224134309/200812241433572344.jpg');" src="http://photo9.zxip.com/albums9/folder18/14189/20081224134309/200812241433572344.jpg" /></p>
<p>
	◎译　　名　《现金/至尊对决》08最新多明星票房大片DVD中英双字幕<br />
	◎片　　名　Ca$h<br />
	◎年　　代　2008<br />
	◎国　　家　法国<br />
	◎类　　别　犯罪/喜剧/惊悚<br />
	◎语　　言　法语<br />
	◎字　　幕　中字<br />
	◎IMDB评分&nbsp; 5.8/10&nbsp; 501 votes<br />
	◎IMDB链接&nbsp; http://www.imdb.com/title/tt1002966<br />
	◎文件格式　X264 + AC3<br />
	◎视频尺寸　880 X 464<br />
	◎文件大小　2CD<br />
	◎片　　长　102MiN<br />
	◎导　　演　Eric Besnard<br />
	◎主　　演　弗朗西斯&middot;贝尔兰德 Fran?ois Berl&eacute;and....Fran?ois<br />
	　　　　　　让&middot;雷诺 Jean Reno....Maxime - Dubreuil<br />
	　　　　　　阿丽斯&middot;塔格里奥妮 Alice Taglioni....Garance<br />
	　　　　　　艾瑞克&middot;艾伯纳尼 Eriq Ebouaney....Letallec<br />
	　　　　　　让&middot;杜雅赫丹 Jean Dujardin....Cash<br />
	　　　　　　Jocelyn Quivrin ....Lebrun<br />
	　　　　　　Samir Guesmi ....Fred<br />
	　　　　　　Mehdi Nebbou ....Vincent<br />
	　　　　　　Fran?oise Miquelis ....La femme curiste<br />
	　　　　　　Cyril Couton ....Mickey<br />
	　　　　　　Bernard Cheron ....Le jardinier<br />
	　　　　　　Julien Labigne ....Card Player<br />
	　　　　　　塞伦&middot;希德 Ciar&aacute;n Hinds....Barnes<br />
	　　　　　　瓦莱莉&middot;高利诺 Valeria Golino....Julia<br />
	　　　　　　Christian Hecq ....Lardier<br />
	　　　　　　克里斯朵夫&middot;罗西尼翁 Christophe Rossignon....Le r&eacute;ceptionniste<br />
	　　　　　　科洛维斯&middot;科尔尼拉 Clovis Cornillac....Solal<br />
	<br />
	◎简　　介　<br />
	<br />
	&nbsp; &nbsp; Cash（Jean Dujardin饰）是巴黎一流的骗子，以伪造艺术品来诈取钱财，但他的野心绝不只如此，他计划着到法国避暑胜地－里维耶拉偷取钻石。<br />
	<br />
	&nbsp; &nbsp; 同时，另一名骗术高手Maxime（尚雷诺饰）也悄悄接近，加上拥有致命吸引力的美女也牵扯其中，谁会是最后的赢家？<br />
	<br />
	&nbsp; &nbsp; 巴黎，一名于易容术的老千Solal，在一通神秘电话后，被闯空门的人枪杀。<br />
	<br />
	&nbsp; &nbsp; 十 八个月后，Solal的弟弟，一位帅气、谜样的老千，专用伪造物来赚钱的他，又要开始进行一场交易，他以精致的制版技术生产出大笔假钞，与 Lerallec进行交易。就在Leralle的检验师验证成功要交易的最后一刻，Cash神不知鬼不觉的将模板调换掉。美丽的女警Julia（薇拉莉葛 琳诺饰），则与Cash串通好以相机纪录着这一切。<br />
	<br />
	&nbsp; &nbsp; Cash原本要向女友Garance（艾丽斯泰里昂妮饰）求婚，却遇上被骗的 Lerallec前来寻仇，幸得Julia出手相救。Cash被迷人的Julia吸引，邀请她参加一场慈善拍卖，却赫然发现Garance的爸爸是老千界 的传奇人物，为了获得更多内幕，Julia试图接近勾引Cash借机暗中调查&hellip;&hellip;&hellip;。<br />
	<br />
	&nbsp; &nbsp; 步步为营的Julia却不知道自己已卷入了一场大骗 局，这次Cash的目标是价值一批价值百万美金的钻石。同时，另一名骗术高手Maxime（尚雷诺饰）也悄悄接近。法国避暑胜地-里维耶拉里的奢华的饭店 内，聚集了一群优秀的老千相互对峙着，充满着危险和性爱的游戏，真真假假难以捉摸，谁会是最后的赢家？<br />
	<br />
	&nbsp; &nbsp; 艾瑞克贝斯纳（Eric Besnard）编导，汇集了几位法国红星，包括尚雷诺、《巴黎换换爱》艾丽斯泰里昂妮与《玩命快递２》法兰柯波兰德。</p>

<p>
	【电影截图】：<br />
	电影来源：www.eee4.com<br />
	<br />
	<br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://img.album.pchome.net/54/68/23/16/49a270b1c169ae52f2070584942a4dcd.jpg');" src="http://img.album.pchome.net/54/68/23/16/49a270b1c169ae52f2070584942a4dcd.jpg" /><br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://img.album.pchome.net/54/68/23/16/3143dfdeb3b13ebab68bbb2970cd5680.jpg');" src="http://img.album.pchome.net/54/68/23/16/3143dfdeb3b13ebab68bbb2970cd5680.jpg" /><br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://img.album.pchome.net/54/68/23/16/c61a3e2649e05971e9ab8eca44c858b7.jpg');" src="http://img.album.pchome.net/54/68/23/16/c61a3e2649e05971e9ab8eca44c858b7.jpg" /><br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://img.album.pchome.net/54/68/23/16/884a3e5596b0410ee27e9393c02472d5.jpg');" src="http://img.album.pchome.net/54/68/23/16/884a3e5596b0410ee27e9393c02472d5.jpg" /><br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://img.album.pchome.net/54/68/23/16/5bc5a1300ca5a23637a380fce63cb7a1.jpg');" src="http://img.album.pchome.net/54/68/23/16/5bc5a1300ca5a23637a380fce63cb7a1.jpg" /></p>
	08最新多明星票房大片《至尊对决》DVD中英双字幕 －来自[3E电影站www.eee4.com]：<img border="0" src="http://www.eee4.com/templets/img/down.jpg" /><br />
	&nbsp;</p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<anchor></anchor><a href="ftp://e18:e18@dm.eee4.com:1216/[3E电影站www.eee4.com]至尊对决CD1.rmvb" target="_blank">ftp://e18:e18@dm.eee4.com:1216/[3E电影站www.eee4.com]至尊对决CD1.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<anchor></anchor><a href="ftp://e18:e18@dm.eee4.com:1216/[3E电影站www.eee4.com]至尊对决CD2.rmvb" target="_blank">ftp://e18:e18@dm.eee4.com:1216/[3E电影站www.eee4.com]至尊对决CD2.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<anchor></anchor><a href="ftp://dy44:piaohua@dy44.piaohua.com:2945/飘花电影piaohua.com现金BD中英双字1280高清.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2945/飘花电影piaohua.com现金BD中英双字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15059A0-36027.jpg{/dede:field}
