{dede:field name='keywords'}赌侠[HD粤语中字1024x576高清版]{/dede:field}
{dede:field name='description'}赌侠[HD粤语中字1024x576高清版]迅雷下载、免费下载，赌侠[HD粤语中字1024x576高清版]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}赌侠[HD粤语中字1024x576高清版]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2010-05-19{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://4e:4e@d8.3edyy.com:157/【3E电影院www.eee4.cc】赌侠HD粤语中字1024x576高清版.rmvb" target="_blank{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MQ34910-2L92.jpg{/dede:field}
