<?php
$z[0]=Array("field","赌侠[HD粤语中字1024x576高清版]",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","赌侠[HD粤语中字1024x576高清版]迅雷下载、免费下载，赌侠[HD粤语中字1024x576高清版]Gvod高清在线播放，剧情介绍等。",73,227);
$z[1][4]['name']="description";
$z[2]=Array("field","赌侠[HD粤语中字1024x576高清版]",229,297);
$z[2][4]['name']="title";
$z[3]=Array("field","",299,338);
$z[3][4]['name']="writer";
$z[4]=Array("field","",340,379);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-05-19",381,431);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",433,470);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://4e:4e@d8.3edyy.com:157/【3E电影院www.eee4.cc】赌侠HD粤语中字1024x576高清版.rmvb\" target=\"_blank",472,612);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MQ34910-2L92.jpg",614,696);
$z[8][4]['name']="litpic";

?>