{dede:field name='keywords'}阴影村DVD中字2010法国恐怖惊悚{/dede:field}
{dede:field name='description'}阴影村DVD中字2010法国恐怖惊悚大片迅雷下载、免费下载，阴影村DVD中字2010法国恐怖惊悚大片Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}阴影村DVD中字2010法国恐怖惊悚大片{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-03{/dede:field}
{dede:field name='body'}<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120503/15/56643687201205031505512598941985516_004.jpg" /></p>
<p>
	◎译　　名　阴影村<br />
	◎片　　名　The Village of Shadows<br />
	◎年　　代　2010<br />
	◎国　　家　法国<br />
	◎类　　别　惊悚/恐怖<br />
	◎语　　言　法语<br />
	◎字　　幕　中文<br />
	◎IMDB评分 4.4/10 (149 votes)<br />
	◎文件格式　DVD-RMVB<br />
	◎视频尺寸　640 x 272<br />
	◎文件大小　1CD 509MB<br />
	◎片　　长　99 mins<br />
	◎导　　演　Fouad Benhammou<br />
	◎主　　演　Barbara Goenaga .... Lila<br />
	Cyrille Thouvenin .... David<br />
	莎拉&middot;弗里斯蒂 Sara Forestier .... Emma<br />
	Nicolas Gob .... Lucas<br />
	G&eacute;rard Dessalles .... Thewithcar<br />
	Pascal Reneric .... Mathias<br />
	Lucia Bruxelle .... Katia<br />
	Haegele Jochen .... Klaus Froelich<br />
	Pierre-Marie Rochefort-Schneider .... Ulrich Wagner<br />
	Ornella Boul&eacute; .... Marion</p>
<p>
	◎简　　介　</p>
<p>
	　　九位年轻人, 一同出游到一个叫做法国乡间的鲁福瑞村去度假, 殊不知此村庄在上百年前的法国大革命时, 就已经受到死亡的诅咒, 每八年就会有惨案发生, 九位年轻人一到达村庄後, 便一个个消失, 这个神秘的村庄到底发生了什麽事?</p>
<p>
	<br />
	◎影片截图</p>

<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120503/15/56643687201205031505512598941985516_002.jpg" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120503/15/56643687201205031505512598941985516_003.jpg" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120503/15/56643687201205031505512598941985516_001.jpg" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.netftp//dy44:piaohua@dy44.piaohua.com:3142/" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				&nbsp;<a href="ftp://dy44:piaohua@dy44.piaohua.com:3345/飘花电影piaohua.com阴影村DVD中字.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3345/飘花电影piaohua.com阴影村DVD中字.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O16433210-22a6.jpg{/dede:field}
