{dede:field name='keywords'}河童之夏BD1280高清中字迅雷下载{/dede:field}
{dede:field name='description'}河童之夏BD1280高清中字迅雷下载、免费下载，河童之夏BD1280高清中字Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}河童之夏BD1280高清中字{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-01-22{/dede:field}
{dede:field name='body'}<p>
	【中文译名】《河童之夏》07最新精彩动画巨制BD1280中字<br />
	【片　　名】Kappa No Ku To Natsu Yasumi<br />
	【年　　代】2007<br />
	【国　　家】日本<br />
	【类　　别】动画<br />
	【语　　言】日语<br />
	【字　　幕】日文<br />
	【IMDB评分】8.6/10 (9 votes)<br />
	【片　　长】02:18:29<br />
	【导　　演】原惠一 Keiichi Hara<br />
	【主　　演】Futo Tomizawa&nbsp;<br />
	　　　　　　Naoki Tanaka&nbsp;<br />
	　　　　　　Naomi Nishida&nbsp;<br />
	　　　　　　Kenichi Nagira&nbsp;<br />
	　　　　　　Takahiro Yokoyama</p>
<p>
	【剧情简介】：</p>
<p>
	&nbsp;&nbsp;&nbsp; 就快放暑假了，小学生上原康一在放学回家的路上捡到一块大石头。他把石头带回了家，没想到用水一洗，里面竟跳出一只小河童来。小河童对他&ldquo;咕&rdquo;的叫了一声，于是康一就给它取名为&ldquo;小咕&rdquo;。<br />
	　　小咕会说人类的语言，几百年来他一直被埋在在地下。康一很快就和小咕成了好朋友，他们一起洗澡，一起吃饭，一起睡觉。而其它家庭成员也接受了小咕，小河童成了上原一家的秘密。<br />
	　　一天，小咕提出想回家和伙伴们在一起。康一为了让小咕了解外面的世界，悄悄把它带了出去。小咕发现环境已经面目全非，大吃了一惊，这个不适合就河童生存的地方根本就找不到伙伴。看到小咕难过，康一也不好受。他和小咕一起外出旅行，来到了还保存着河童传说的远野县。两人在美丽的大自然中找到了适合河童生活的地方，小咕愉快地在清澈的河里游了起来，康一也为它高兴。可是，在这里也怎么都找不到其它河童。康一听到村民们说&ldquo;抓住一只河童能得一千万呢！&rdquo;，赶忙带着小咕离开了那里。<br />
	　　回到家，康一讶异地撞见了一个小报记者。原来那人听说上原家养着一只河童，一定要拍照。小咕的秘密终于被大家知道了。康一的爸爸被公司勒令一定要让河童上电视。为了上原一家，小咕答应参加电视节目。然而在到场嘉宾里，它看到了一个长得很像杀父凶手的人。就在小咕被恐惧包围的时候，电视节目现场发生了意外。它拼命逃到了外面，然而无论跑到哪里都会看到黑压压的人群。3E迅雷<a href="/" target="_blank">电影下载</a>站<br />
	　　为了摆脱让它害怕的人类，小咕爬上了东京塔。夏季的烈日照得它精疲力竭。小咕俯瞰着城市，独自低语道：&ldquo;哪里都找不到一个安静的地方，这里是人类的窝。我已经不行了。我要去爸爸那里&hellip;&hellip;&rdquo;</p>
<p>
	<br />
	【花絮】：<br />
	&middot;《河童之夏》是由《蜡笔小新》系列电影导演原惠一，改编自日本儿童文学名家木暮正夫《河童大骚动》、《河童的惊奇之旅》等河童系列，耗费五年完成的动画片。</p>
<p>
	<img src="http://pic.piaohua.com/0701pic/allimg/080627/0602030.jpg" /></p>
<p>
	【电影截图】：<br />
	<img alt="" border="0" src="http://img2081.poco.cn/mypoco/myphoto/20120122/01/17870980201201220146421834269801679_000.jpg" /><img alt="" border="0" src="http://img2081.poco.cn/mypoco/myphoto/20120122/01/17870980201201220145513300108719225_003.jpg" /></p>
<p>
	07最新精彩动画巨制《河童之夏》BD1280中字 下载地址：<img border="0" src="/templets/img/down.jpg" /></p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<anchor></anchor><a href="ftp://dy241:xiaobajie@dy241.piaohua.com:2050/小八戒电影xiaobajie.com河童之夏日语中字720p.rmvb" target="_blank">ftp://dy241:xiaobajie@dy241.piaohua.com:2050/小八戒电影xiaobajie.com河童之夏日语中字720p.rmvb</a></td>
		</tr>
	</tbody>
</table>
<p>
	07最新精彩动画巨制《河童之夏》DVD中字 下载地址：<img border="0" src="/templets/img/down.jpg" /><br />
	CD1：</p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<anchor></anchor><a href="ftp://eee4.com:8113@vip20.eee4.com:8113/[3E迅雷电影站www.eee4.com]河童之夏DVD中字CD1.rmvb" target="_blank">ftp://eee4.com:8113@vip20.eee4.com:8113/[3E迅雷电影站www.eee4.com]河童之夏DVD中字CD1.rmvb</a></td>
		</tr>
	</tbody>
</table>
<p>
	CD2：</p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<anchor></anchor><a href="ftp://eee4.com:8113@vip20.eee4.com:8113/[3E迅雷电影站www.eee4.com]河童之夏DVD中字CD2.rmvb" target="_blank">ftp://eee4.com:8113@vip20.eee4.com:8113/[3E迅雷电影站www.eee4.com]河童之夏DVD中字CD2.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1B214Z-3T64.jpg{/dede:field}
