{dede:field name='keywords'}亲爱的，你完了DVD中英双字2011{/dede:field}
{dede:field name='description'}亲爱的，你完了DVD中英双字2011最新美国喜剧爱情大片迅雷下载、免费下载，亲爱的，你完了DVD中英双字2011最新美国喜剧爱情大片Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}亲爱的，你完了DVD中英双字2011最新美国喜剧爱情大片{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-14{/dede:field}
{dede:field name='body'}<p>
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120514/20/56643687201205142033271588406153461_004.jpg" /></p>
<p>
	<img alt="" height="360" src="http://img2081.poco.cn/mypoco/myphoto/20110821/00/56634212201108210014103756071456366_002.jpg" width="252" /></p>
<p>
	片名：亲爱的，你完了 　　<br />
	又名：爱情终结者 　　<br />
	主演：Riya Bamniyal Sreejita De Shraddha Kapoor Errol Marks 　　<br />
	导演：Bumpy 　　<br />
	类型：爱情 / 剧情 / 喜剧　<br />
	地区：美国 　　<br />
	语言：英语 　　<br />
	年代：2011年</p>
<p>
	　　<br />
	剧情介绍</p>
<p>
	　　《亲爱的，你完了》剧情讲述了女主人公好不容易考完了试，芮娅终于盼来了自己的18岁生日与期待已久的毕业派对。然而打击一个接一个袭来，先是精心安排欲和男友洛共度的甜蜜之夜由于家庭原因而被迫取消，再是与好友逛超市意外得知富二代男友的三心二意，更严重的是邻居告诉她，男友接近她根本就是一场富二代之间的攀比游戏。可怜又纯真的芮娅在好友索尼娅和婕格斯的支持下决定向落发出反击，给玩世不恭的富二代们一个教训</p>
<p>
	<br />
	◎影片截图</p>
<p>
	<img alt="" height="251" src="http://img2081.poco.cn/mypoco/myphoto/20110821/00/56634212201108210014103756071456366_001.jpg" style="cursor: pointer" width="600" /></p>
<p>
	<img alt="" height="251" src="http://img2081.poco.cn/mypoco/myphoto/20110821/00/56634212201108210014103756071456366_000.jpg" style="cursor: pointer" width="600" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:1355/飘花电影piaohua.com亲爱的，你完了DVD中英双字.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:1355/飘花电影piaohua.com亲爱的，你完了DVD中英双字.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1491DP-541L.jpg{/dede:field}
