{dede:field name='keywords'}七种人生高清1280版BD中字2012英{/dede:field}
{dede:field name='description'}七种人生高清1280版BD中字2012英国奇幻惊悚迅雷下载、免费下载，七种人生高清1280版BD中字2012英国奇幻惊悚Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}七种人生高清1280版BD中字2012英国奇幻惊悚{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-04-25{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://pic.piaohua.com/0701pic/allimg/120425/1-1204251T2332I.jpg" /></p>


<p>
	◎译　　名　七种人生/七条命<br />
	◎片　　名　7lives<br />
	◎年　　代　2011<br />
	◎国　　家　英国<br />
	◎类　　别　奇幻/惊悚<br />
	◎语　　言　英语<br />
	◎字　　幕　中文<br />
	◎IMDB评分 3.7/10 from 209 users<br />
	◎IMDB链接 <a href="http://www.imdb.com/title/tt1558246">http://www.imdb.com/title/tt1558246</a><br />
	◎文件格式　高清1280版BD-RMVB<br />
	◎视频尺寸　1280 x 720<br />
	◎文件大小　1CD 981MB<br />
	◎片　　长　99 Mins<br />
	◎导　　演　保罗-威尔金斯 Paul Wilkins<br />
	◎主　　演　丹尼&middot;戴尔 Danny Dyer ....Tom<br />
	　　　　　　凯特&middot;阿什菲尔德 Kate Ashfield ....Cynthia<br />
	　　　　　　马丁&middot;康普斯顿 Martin Compston ....Rory<br />
	　　　　　　汤姆&middot;古德曼-希尔 Tom Goodman-Hill ....Peter<br />
	　　　　　　安娜&middot;斯科莱姆 Anna Skellern ....Felicity<br />
	　　　　　　尼克&middot;布莱波尔 Nick Brimble ....Ted<br />
	　　　　　　Craig Conway ....Keith<br />
	　　　　　　Helen George ....Valerie<br />
	　　　　　　Theo Barklem-Biggs ....Kid<br />
	　　　　　　Tamzin Malleson ....Mary<br />
	　　　　　　詹妮&middot;雅克 Jennie Jacques ....Carol<br />
	　　　　　　Mary Stockley ....Michelle<br />
	　　　　　　查尔斯&middot;曼勒 Charles Mnene ....Ice<br />
	　　　　　　Layla Amir ....Nurse<br />
	　　　　　　Michael Elwyn ....Brian<br />
	　　　　　　Pete Lee-Wilson ....Kids Dad<br />
	　　　　　　尼克&middot;内维恩 Nick Nevern ....Detective Echo<br />
	　　　　　　Shaun Lucas ....Bouncer<br />
	　　　　　　Ricci McLeod ....Gabriel<br />
	　　　　　　Sam Palladio ....Calvin<br />
	　　　　　　Slinky Winfield ....Silas<br />
	　　　　　　Claire Perkins ....Kids Mum<br />
	　　　　　　Alex Warren ....Revron<br />
	　　　　　　Rebecca Todd ....Nurse<br />
	　　　　　　Michael Kofi ....Max<br />
	　　　　　　Alexia Healy ....Nurse<br />
	　　　　　　Anna Notarantonio ....Passer-by<br />
	　　　　　　Morgan Delle Piane ....Extra<br />
	　　　　　　Julien Ball ....Doctor<br />
	　　　　　　Marie-Claire Zeretzke ....Backstage Groupie<br />
	　　　　　　Stuart J. Prowse ....Record Company Boss<br />
	　　　　　　Craig Izzard ....Extra - Boxing Match (uncredited)<br />
	　　　　　　George Keywood ....Extra - police scene (uncredited)<br />
	　　　　　　Michelle Somerszaule ....Extra (uncredited)<br />
	　　　　　　</p>
<p>
	◎简　　介　</p>
<p>
	Tom, a married man with kids, is struggling at work when a client tries to seduce him with promises of a &#39;more exciting life&#39;. On his way home one night he gets attacked by a gang of hoodies and falls into a parallel world where he lives 5 other lives including a Rock-Star, a Homeless person and the &#39;hoody&#39; that attacked him. These lives help him to re-evaluate his priorities and values but in order to get home he must face some of his deepest desires and fears. Will he make it home or is the grass greener on the other side?　　</p>

<div id="trans-result-content">
	<p src="Tom, a married man with kids, is struggling at work when a client tries to seduce him with promises of a &amp;#39;more exciting life&amp;#39;. On his way home one night he gets attacked by a gang of hoodies and falls into a parallel world where he lives 5 other lives including a Rock-Star, a Homeless person and the &amp;#39;hoody&amp;#39; that attacked him. These lives help him to re-evaluate his priorities and values but in order to get home he must face some of his deepest desires and fears. Will he make it home or is the grass greener on the other side?">
		汤姆，一个已婚男人与孩子，努力在工作时，一个客户端试图勾引他承诺的一个更令人兴奋的生活。在回家的路上，一个晚上他会受到一群帽衫，掉进了一个平行的世界，他住在5生活包括一个摇滚明星，一个无家可归的人，和&#39;帽衫，攻击他。这些生活帮助他重新评估自己的优先事项和价值观，但为了回家，他必须面对他的一些内心深处的欲望和恐惧。他会让家里或草是另一边的绿？</p>
</div>

<p>
	◎影片截图</p>
<p>
	&nbsp;<img src="http://img170.poco.cn/mypoco/myphoto/20120425/12/56643687201204251254552524234418245_002.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 338px; border-top: 0px solid; border-right: 0px solid" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120425/12/56643687201204251254552524234418245_001.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 338px; border-top: 0px solid; border-right: 0px solid" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120425/12/56643687201204251254552524234418245_000.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 338px; border-top: 0px solid; border-right: 0px solid" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120425/12/56643687201204251254552524234418245_003.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 338px; border-top: 0px solid; border-right: 0px solid" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.netftp//dy44:piaohua@dy44.piaohua.com:3201/" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3291/飘花电影piaohua.com七种人生高清1280版BD中字.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3291/飘花电影piaohua.com七种人生高清1280版BD中字.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1563UP-1KW.jpg{/dede:field}
