{dede:field name='keywords'}大冒险家HD高清迅雷下载，免费下{/dede:field}
{dede:field name='description'}大冒险家HD高清迅雷下载、免费下载，大冒险家HD高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}大冒险家HD高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-10-28{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="/uploads/allimg/c120525/133O02P5040-224223.jpg" style="width: 387px; height: 550px" /></p>
<p>
	◎译　　名　大冒险家/挑战者<br />
	◎片　　名　Da mao xian jia<br />
	◎年　　代　1995<br />
	◎国　　家　香港<br />
	◎类　　别　动作/剧情<br />
	◎语　　言　国语<br />
	◎字　　幕　简体中文<br />
	◎IMDB评分 6.1/10 ( 175票 )<br />
	◎IMDB链接 http://www.imdb.com/title/tt0112772<br />
	◎制作公司　永盛娱乐有限公司 [香港]<br />
	　　　　　　 Win&amp;amp;#39;s Production<br />
	◎发行公司　永盛娱乐有限公司 [香港]<br />
	　　　　　　 中国星娱乐有限公司 [香港]<br />
	◎文件格式　X264 + AC3<br />
	◎视频尺寸　1280 x 720<br />
	◎文件大小　1.07G<br />
	◎片　　长　01:49:55.714<br />
	◎导　　演　林岭东Ringo Lam<br />
	◎编　　剧　林岭东Ringo Lam<br />
	　　　　　　 绍丽琼Sandy Shaw<br />
	　　　　　　 叶广荫Gong Yam Yip<br />
	◎主　　演　关之琳Rosamund Kwan....Mona<br />
	　　　　　　 刘德华Andy Lau....Wai Lok-yan/Mandy Chan<br />
	　　　　　　 吴倩莲Chien-lien Wu....Crystal Lui &amp;amp;#39;Chan&amp;amp;#39;<br />
	　　　　　　 姜大卫David Chiang....Uncle Shang<br />
	　　　　　　 程东John Ching....Lam, Ching &amp;amp;#39;Boder&amp;amp;#39;<br />
	　　　　　　 何家驹Ka-Kui Ho....General Buboei<br />
	　　　　　　 吴毅将Ben Ng....Dog<br />
	　　　　　　 黄锦江Kam-Kong Wong....Military Officer<br />
	　　　　　　 黄柏文Parkman Wong....Officer Cheng<br />
	　　　　　　 秦沛Paul Chun....Ray Lui<br />
	　　　　　　 高飞Phillip Ko....Wah<br />
	　　　　　　 谢贤Yin Tse<br />
	　　　　　　 Ron Yuan....Paul<br />
	　　　　　　 George Cheung....Tung<br />
	　　　　　　 Victor Wong....Uncle Nine<br />
	<br />
	◎简　　介<br />
	<br />
	这是导演林岭东赴美国发展前拍摄的最后一部港片，企图走国际动作片的娱乐路线，在大型枪战爆破场面的处理上拍出相当水准，可惜剧情的安排却具有过多巧合和情理不通之处。刘德华在片中饰演一名孤儿，童年时他的父母被结拜兄弟杀死。二十年后，刘成为泰国的空军飞行员希望为父母报仇，但却跟仇人的情妇关之琳发生了关系，因而被对方追杀。他逃到美国去向中央情报局求救。巧合的是他又救了仇人的女儿吴倩莲，并且跟她产生了真感情。在此情况下，刘藉机破坏仇家的生意，用经济手法来进行大报复。<br />
	<br />
	◎幕　　后<br />
	<br />
	进入娱乐圈后的刘德华凭着《皇上保重》等电视剧走红，但他在电影上的成绩却更加出色。尤其他在1988年拍摄的《旺角卡门》中的不羁浪子形象，简直令无数少女疯狂痴迷。其后的《至尊无上》、《赌神》、《天若有情》以及《神雕侠侣》(1991版)中的潇洒形象更成为了一个时代新好男人的固定模式。而《刀剑笑》、《暴走战士》、《天与地》、《挑战者》、《烽火佳人》等片上映时，票房收入之高更是令人咋舌。</p>
<p>
	<img alt="" src="/uploads/allimg/c120525/133O02PH30-23c07.jpg" style="width: 720px; height: 405px" /><img alt="" src="/uploads/allimg/c120525/133O02PR50-2413C.jpg" style="width: 720px; height: 405px" /></p>
<p>
	<br />
	<br />
	&nbsp;</p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="/uploads/allimg/c120524/133N2Z4FF-102231.jpg" />&nbsp;&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy125:piaohua@dy125.piaohua.com:7096/飘花电影piaohua.com大冒险家HD国语中字1280高清.rmvb</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O02P92Z-251528.jpg{/dede:field}
