<?php
$z[0]=Array("field","黑暗物质：黄金罗盘BD中英双字10",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","黑暗物质：黄金罗盘BD中英双字1024/1280高清迅雷下载、免费下载，黑暗物质：黄金罗盘BD中英双字1024/1280高清Gvod高清在线播放，剧情介绍等。",73,249);
$z[1][4]['name']="description";
$z[2]=Array("field","黑暗物质：黄金罗盘BD中英双字1024/1280高清",251,330);
$z[2][4]['name']="title";
$z[3]=Array("field","",332,371);
$z[3][4]['name']="writer";
$z[4]=Array("field","",373,412);
$z[4][4]['name']="source";
$z[5]=Array("field","2012-05-22",414,464);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",466,503);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://e25:e25@xl2.eee4.com:9916/[3E电影站www.eee4.com]黄金罗盘[DVD中英双字1024x560高清版]CD1.rmvb\" target=\"_blank",505,657);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MO9222F-41514.jpg",659,742);
$z[8][4]['name']="litpic";

?>