<?php
$z[0]=Array("field","启示录之七封印/世界末日的七种",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","启示录之七封印/世界末日的七种现象[DVD中字]迅雷下载、免费下载，启示录之七封印/世界末日的七种现象[DVD中字]Gvod高清在线播放，剧情介绍等。",72,250);
$z[1][4]['name']="description";
$z[2]=Array("field","启示录之七封印/世界末日的七种现象[DVD中字]",252,332);
$z[2][4]['name']="title";
$z[3]=Array("field","",334,373);
$z[3][4]['name']="writer";
$z[4]=Array("field","",375,414);
$z[4][4]['name']="source";
$z[5]=Array("field","2012-03-17",416,466);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",468,505);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://4e:4e@m1.eee4.cc:1518/【3E电影院www.eee4.cc】启示录之七封印[DVD中字].rmvb\" target=\"_blank",507,641);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MQ4403Z-49B3.jpg",643,725);
$z[8][4]['name']="litpic";

?>