<?php
$z[0]=Array("field","镖客三部曲3：黄金三镖客/黄金三",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","镖客三部曲3：黄金三镖客/黄金三镖客/独行侠勇破地狱门/黄昏三镖客[BD中英双字1024x57迅雷下载、免费下载，镖客三部曲3：黄金三镖客/黄金三镖客/独行侠勇破地狱门/黄昏三镖客[BD中英双字1024x57Gvod高清在线播放，剧情介绍等。",73,327);
$z[1][4]['name']="description";
$z[2]=Array("field","镖客三部曲3：黄金三镖客/黄金三镖客/独行侠勇破地狱门/黄昏三镖客[BD中英双字1024x57",329,447);
$z[2][4]['name']="title";
$z[3]=Array("field","",449,488);
$z[3][4]['name']="writer";
$z[4]=Array("field","",490,529);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-06-05",531,581);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",583,620);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://3e:3e@d8.3edyy.com:162/【3E电影院www.eee4.cc】黄金三镖客BD中英双字1024x576高清版.rmvb\" target=_blank>ftftp://3e:3e@d8.3edyy.com:162/【3E电影院www.eee4.cc】黄金三镖客BD中英双字1024x576高清版.rmvb</A></TD></TR></TBODY></TABLE></div><ul class=\"mmlist",622,914);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MQ351130-51P2.jpg",916,999);
$z[8][4]['name']="litpic";

?>