<?php
$z[0]=Array("field","爱情啊,爱情啊第11集韩剧迅雷下",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","爱情啊 爱情啊第11集韩剧迅雷下载、免费下载，爱情啊 爱情啊第11集韩剧Gvod高清在线播放，剧情介绍等。",72,212);
$z[1][4]['name']="description";
$z[2]=Array("field","爱情啊 爱情啊第11集韩剧",214,275);
$z[2][4]['name']="title";
$z[3]=Array("field","",277,316);
$z[3][4]['name']="writer";
$z[4]=Array("field","",318,357);
$z[4][4]['name']="source";
$z[5]=Array("field","2012-05-23",359,409);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",411,448);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://dy44:piaohua@dy44.piaohua.com:3387/飘花电影piaohua.com爱情啊 爱情啊EP01.rmvb",450,571);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MPc1T0-1a60.jpg",573,654);
$z[8][4]['name']="litpic";

?>