{dede:field name='keywords'}本拉登之死HD中英双字BBC纪录片{/dede:field}
{dede:field name='description'}本拉登之死HD中英双字BBC纪录片迅雷下载、免费下载，本拉登之死HD中英双字BBC纪录片Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}本拉登之死HD中英双字BBC纪录片{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-06-11{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="/uploads/allimg/c120524/133N4PC520-1335F.jpg" style="width: 494px; height: 455px" /></p>
<p>
	中文片名: BBC 本拉登之死<br />
	英文片名: BBC Panorama 2011 The Death of Bin Laden<br />
	剧集分类: 动作<br />
	影片类型: 纪录片<br />
	资源格式: HR-HDTV,RMVB<br />
	上影时间: 2011<br />
	对白语言: 英语&nbsp;<br />
	字幕语种: 中英<br />
	介绍:<br />
	十多年来，他被悬赏通缉、全力追捕。今晚本节目将全程剖析美国军方如何追踪并击毙其头号敌人。<br />
	这是一次史无前例的大胆突袭，美军海豹突击队直捣本&middot;拉登藏身之处。<br />
	在巴基斯坦军方眼皮底下，本&middot;拉登何以成功藏身长达五年？<br />
	拉登之死能否给我们带来些许安全？</p>

<p>
	<img alt="" src="/uploads/allimg/c120524/133N4PD340-146141.jpg" style="width: 681px; height: 372px" /></p>
<p>
	[下载地址]：</p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-right: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-left: #cccccc 1px dotted; border-bottom: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				ftp://dy46:piaohua@dy46.piaohua.com:617/飘花电影piaohua.com本拉登之死.rmvb</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120524/133N4PDa0-155b0.jpg{/dede:field}
