<?php
$z[0]=Array("field","小马精灵/小马王HD中英双字1024",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","小马精灵/小马王HD中英双字1024高清迅雷下载、免费下载，小马精灵/小马王HD中英双字1024高清Gvod高清在线播放，剧情介绍等。",72,232);
$z[1][4]['name']="description";
$z[2]=Array("field","小马精灵/小马王HD中英双字1024高清",234,305);
$z[2][4]['name']="title";
$z[3]=Array("field","",307,346);
$z[3][4]['name']="writer";
$z[4]=Array("field","",348,387);
$z[4][4]['name']="source";
$z[5]=Array("field","2012-03-12",389,439);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",441,478);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://3e:3e@www2.eee4.com:195/[3E电影站www.eee4.com]小马王DVD国语中字.rmvb\" target=\"_blank",480,609);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MQ125110-21062.jpg",611,695);
$z[8][4]['name']="litpic";

?>