{dede:field name='keywords'}毁灭种子/恐惧之下DVD中字2011加{/dede:field}
{dede:field name='description'}毁灭种子/恐惧之下DVD中字2011加拿大科幻恐怖迅雷下载、免费下载，毁灭种子/恐惧之下DVD中字2011加拿大科幻恐怖Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}毁灭种子/恐惧之下DVD中字2011加拿大科幻恐怖{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-24{/dede:field}
{dede:field name='body'}<p>
	<img src="http://img2081.poco.cn/mypoco/myphoto/20120523/15/56643687201205231517072251527135716_004.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 882px; border-top: 0px solid; border-right: 0px solid" /></p>
<p>
	&nbsp;</p>
<p>
	◎译　　名　毁灭种子/恐惧之下<br />
	◎片　　名　Seeds of Destruction/The Terror Beneath<br />
	◎年　　代　2011<br />
	◎国　　家　加拿大<br />
	◎类　　别　科幻/恐怖<br />
	◎语　　言　英语<br />
	◎字　　幕　中文<br />
	◎IMDB评分 4.2/10 from 114 users<br />
	◎IMDB链接 <a href="http://www.imdb.com/title/tt1706680">http://www.imdb.com/title/tt1706680</a><br />
	◎文件格式　DVD-RMVB<br />
	◎视频尺寸　720 x 404<br />
	◎文件大小　1CD 526MB<br />
	◎片　　长　1h 29mn<br />
	◎导　　演　Paul Ziller<br />
	◎主　　演　亚德里安&middot;帕斯达 Adrian Pasdar &hellip; Jack<br />
	　　　　 　 Jesse Moss &hellip; Joe<br />
	　　　　　　James Morrison &hellip; Frame<br />
	　　　　　　Stefanie von Pfetten &hellip; Jocelyn<br />
	　　　　　　Luisa D&rsquo;Oliveira &hellip; Kate<br />
	　　　　　　David Lewis &hellip; Principal<br />
	　　　　　　David Richmond-Peck &hellip; Wilson<br />
	　　　　　　Daniel Bacon &hellip; Noel</p>
<p>
	◎简　　介　</p>
<p>
	　　　美国政府的秘密实验失败导致一种植物迅速扩大并占领了美国大部分地区，一群科学家为了对抗这种怪物而孤军深入致命植物的核心&hellip;&hellip;</p>
<p>
	◎影片截图</p>
<p>
	&nbsp;<img border="0" src="http://img2081.poco.cn/mypoco/myphoto/20120523/15/56643687201205231517072251527135716_000.jpg" /></p>
<p>
	<img border="0" src="http://img2081.poco.cn/mypoco/myphoto/20120523/15/56643687201205231517072251527135716_002.jpg" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.netftp//dy44:piaohua@dy44.piaohua.com:3193/" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3485/飘花电影piaohua.com恐惧之下DVD中字.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3485/飘花电影piaohua.com恐惧之下DVD中字.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O164I030-44059.jpg{/dede:field}
