<?php
$z[0]=Array("field","未来空军揭秘迅雷下载，免费下载",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","未来空军揭秘迅雷下载、免费下载，未来空军揭秘Gvod高清在线播放，剧情介绍等。",73,191);
$z[1][4]['name']="description";
$z[2]=Array("field","未来空军揭秘",193,243);
$z[2][4]['name']="title";
$z[3]=Array("field","",245,284);
$z[3][4]['name']="writer";
$z[4]=Array("field","",286,325);
$z[4][4]['name']="source";
$z[5]=Array("field","2008-08-03",327,377);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",379,416);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://eee4.com:8114@vip11.eee4.com:8114/[3E迅雷电影站www.eee4.com]未来空军揭秘DVD中字.rmvb\" target=_blank>ftftp://eee4.com:8114@vip11.eee4.com:8114/[3E迅雷电影站www.eee4.com]未来空军揭秘DVD中字.rmvb</A></TD></TR></TBODY></TABLE></div><ul class=\"mmlist",418,708);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MP452620-36417.jpg",710,794);
$z[8][4]['name']="litpic";

?>