{dede:field name='keywords'}罗大佑-皇后大道东1920x1088现场{/dede:field}
{dede:field name='description'}罗大佑-皇后大道东1920x1088现场版MV迅雷下载、免费下载，罗大佑-皇后大道东1920x1088现场版MVGvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}罗大佑-皇后大道东1920x1088现场版MV{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-07-23{/dede:field}
{dede:field name='body'}<p>
	&nbsp;<br />
	作曲：罗大佑 作词：林夕<br />
	演唱：罗大佑</p>
<p>
	皇后大道西又皇后大道东<br />
	皇后大道东转皇后大道中</p>
<p>
	皇后大道东上为何无皇宫</p>
<p>
	皇后大道中人民如潮涌</p>

<p>
	有个贵族朋友在硬币背后</p>
<p>
	青春不变名字叫做皇后</p>
<p>
	每次买卖随我到处去奔走</p>
<p>
	面上没有表情却汇聚成就</p>

<p>
	知己一声拜拜远去这都市</p>
<p>
	要靠伟大同志搞搞新意思</p>
<p>
	照买照卖楼花处处有单位</p>
<p>
	但是旺角可能要换换名字</p>

<p>
	皇后大道西又皇后大道东</p>
<p>
	皇后大道东转皇后大道中</p>
<p>
	皇后大道东上为何无皇宫</p>
<p>
	皇后大道中人民如潮涌</p>

<p>
	这个正义朋友面善又友善</p>
<p>
	因此批准马匹一周跑两天</p>
<p>
	百姓也自然要斗快过终点</p>
<p>
	若做大国公民祗须身有钱</p>

<p>
	知己一声拜拜远去这都市</p>
<p>
	要靠伟大同志搞搞新意思</p>
<p>
	冷暖气候同样影响这都市</p>
<p>
	但是换季可能靠特异人士</p>

<p>
	空即是色 色即是空</p>
<p>
	空即是色即是色即是空</p>
<p>
	空即是色 色即是空</p>
<p>
	空即是色即是色即是空</p>

<p>
	皇后大道西又皇后大道东</p>
<p>
	皇后大道东转皇后大道中</p>
<p>
	皇后大道东上为何无皇宫</p>
<p>
	皇后大道中人民如潮涌</p>

<p>
	这个漂亮朋友道别亦漂亮</p>
<p>
	夜夜电视萤幕继续旧形象</p>
<p>
	到了那日同庆个个要鼓掌</p>
<p>
	硬币上那尊容变烈士铜像</p>

<p>
	知己一声拜拜远去这都市</p>
<p>
	要靠伟大同志搞搞新意思</p>
<p>
	会有铁路城巴也会有的士</p>
<p>
	但是路线可能要问问何事</p>

<p>
	▲皇后大道西又皇后大道东</p>
<p>
	皇后大道东转皇后大道中</p>
<p>
	皇后大道东上为何无皇宫</p>
<p>
	皇后大道中人民如潮涌</p>

<p>
	皇后大道西又皇后大道东</p>
<p>
	皇后大道东转皇后大道中</p>
<p>
	皇后大道东上为何无皇宫</p>
<p>
	皇后大道中人民如潮涌▲■</p>
<p>
	<img border="0" src="/uploads/allimg/c120524/133N423P140-13Y2.jpg" width="750" /></p>
<p>
	[下载地址]： &nbsp;<img border="0" src="/uploads/allimg/c120524/133N2Z4FF-102231.jpg" />
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy171:piaohua@dy171.piaohua.com:1065/飘花电影piaohua.com罗大佑-皇后大道东现场版MV.mkv</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120524/133N423R540-23096.jpg{/dede:field}
