{dede:field name='keywords'}错爱DVD粤语中字/HD国语1280高清{/dede:field}
{dede:field name='description'}错爱DVD粤语中字/HD国语1280高清迅雷下载、免费下载，错爱DVD粤语中字/HD国语1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}错爱DVD粤语中字/HD国语1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-11-20{/dede:field}
{dede:field name='body'}<p>
	<img border="0" src="http://pic.piaohua.com/0701pic/allimg/080128/0241320.jpg" /></p>
<p>
	【中文片名】《错爱/塚爱》DVD粤语中字<br />
	【译　　名】In Love With The Dead<br />
	【年　　代】2007<br />
	【国　　家】中国香港<br />
	【类　　别】恐怖<br />
	【语　　言】粤语<br />
	【字　　幕】中文<br />
	【IMDB评分】8.4/10 (14 votes)<br />
	【视频尺寸】624 x 352<br />
	【电影整理】3E迅雷电影下载站(www.eee4.com)<br />
	【文件大小】1CD 381MB<br />
	【片　　长】98 mins<br />
	【导　　演】彭发 Danny Pang<br />
	【主　　演】余文乐 Shawn Yue<br />
	　　　　　　邓丽欣 Stephy Tang<br />
	　　　　　　谭耀文 Patrick Tam<br />
	　　　　　　曹永廉 Wing Lim Cho</p>
<p>
	【剧情简介】：</p>
<p>
	&nbsp; 恩明和陆慧是一对同居蜜友。陆慧父母遗下妹妹陆萍给她照顾，陆萍是一个爱看灵异鬼怪书籍的小女孩。</p>
<p>
	　　陆慧不幸验出患了晚期胰脏癌，恩明因深爱她，故提议和陆慧结婚。陆慧决定辞掉工作接受化疗和好好享受</p>
<p>
	余下的人生，但陆慧的病情却不断的恶化。不久，恩明被公司裁了出来。恩明见新工作时，发现该公司的老板是</p>
<p>
	他和陆慧都认识的小学同学芳婷。二人聚旧闲谈间芳婷得知恩明和陆慧正在同居。而芳婷亦告知自己也快要结婚</p>
<p>
	，最后恩明顺利在此公司工作。电影整理：www.eee4.com</p>
<p>
	　　恩明和芳婷二人在一次一起出外工干时互诉真情，在酒精影响下发生了关系。及后恩明、芳婷的关系终给陆</p>
<p>
	慧发现，陆慧感到无助。一天，陆慧突然不见了踪影。恩明在家等了很久仍不见陆慧回来，心下一惊，便驾车出</p>
<p>
	外去找陆慧。迷惘间来到芳婷家里，芳婷告知恩明陆慧来过找她谈三人之间的事，但后来她们二人发生争执，陆</p>
<p>
	慧打晕芳婷后就走了。这时电台新闻报告说有一女子在尖东海旁跳海死亡，恩明心一慌，险与迎面而来的货车相</p>
<p>
	撞，恩明在回軚闪避中昏迷&hellip;</p>
<p>
	　　恩明回家见陆慧全身湿透木无表情地坐着。陆慧的行径自该日见过芳婷后开始古怪起来，她把全屋窗帘拉下</p>
<p>
	，不出外，不做化疗，还不停脱发，午夜在厅中行走。</p>
<p>
	　　一个午间，恩明在芳婷家里缠绵时感到见到陆慧如幽灵般站在床前看着他们。恩明驾车到加油站，加油员对</p>
<p>
	同事说恩明身上有一阵尸臭味传出。恩明开始亦感自己的生理产生不寻常变化，如陆慧一样脱发，他更口里吐出</p>
<p>
	尸虫。陆萍亦感到不安。传说有些人因心事未了，就算是死了仍会在人间行走一段时间，更有些人连自己死了也</p>
<p>
	不知&hellip;&hellip;</p>
<p>
	及后陆慧的病情出奇地受到控制，陆慧在医院里一直不见恩明来接出院，便带同陆萍一起去芳婷家找恩明、芳婷</p>
<p>
	。陆慧一入芳婷家内，便被厅里的情景吓呆，因她见到除芳婷布满尸虫的尸体在厅里外，还见到恩明吊颈死于厅</p>
<p>
	内&hellip;</p>
<p>
	到底恩明、陆慧、芳婷三人当中发生什么事？谁是人谁是鬼呢？ 电影整理：www.eee4.com</p>



<p>
	<img border="0" src="http://pic.piaohua.com/0701pic/allimg/080128/0241321.jpg" /><br />
	<img border="0" src="http://pic.piaohua.com/0701pic/allimg/080128/0241322.jpg" /><br />
	<img border="0" src="http://pic.piaohua.com/0701pic/allimg/080128/0241323.jpg" /><br />
	<img border="0" src="http://pic.piaohua.com/0701pic/allimg/080128/0241324.jpg" /><br />
	<img border="0" src="http://pic.piaohua.com/0701pic/allimg/080128/0241325.jpg" /></p>


<p>
	07最新恐怖大片《错爱》DVD粤语中字 －下载地址：<img border="0" src="/templets/img/down.jpg" /></p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<anchor></anchor><a href="ftp://eee4.com:4421@vip8.eee4.com:4421/错爱/[3E迅雷电影站www.eee4.com]错爱DVD粤语中字.rmvb" target="_blank">ftp://eee4.com:4421@vip8.eee4.com:4421/错爱/[3E迅雷电影站www.eee4.com]错爱DVD粤语中字.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<anchor></anchor>&nbsp;<a href="ftp://dy44:piaohua@dy44.piaohua.com:2132/飘花电影piaohua.com错爱HD国语1280高清.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2132/飘花电影piaohua.com错爱HD国语1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O16040630-261H.jpg{/dede:field}
