{dede:field name='keywords'}幽灵公主BD中字1280高清IMDB经典{/dede:field}
{dede:field name='description'}幽灵公主BD中字1280高清IMDB经典TOP119迅雷下载、免费下载，幽灵公主BD中字1280高清IMDB经典TOP119Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}幽灵公主BD中字1280高清IMDB经典TOP119{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-10-23{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="/uploads/allimg/c120525/133O0453W30-93T9.jpg" /></p>
<p>
	◆中文片名：幽灵公主<br />
	◆英文片名：Princess Mononoke<br />
	◆导　　演：宫崎骏 Hayao Miyazaki<br />
	◆编　　剧：宫崎骏 Hayao Miyazaki<br />
	　　　　　　Neil Gaiman<br />
	◆配　　音：Y?ji Matsuda .... Prince Ashitaka (voice)<br />
	　　　　　　Yuriko Ishida .... San, The Princess Mononoke (voice)<br />
	　　　　　　Y?ko Tanaka .... Eboshi-gozen (voice)<br />
	　　　　　　Kaoru Kobayashi .... Jiko-b? (voice)<br />
	　　　　　　Masahiko Nishimura .... Kouroku (voice)<br />
	　　　　　　Tsunehiko Kamij? .... Gonza (voice)<br />
	　　　　　　Sumi Shimamoto .... Toki (voice)<br />
	　　　　　　Tetsu Watanabe .... Yama-inu (voice)<br />
	　　　　　　Mitsuru Sat? .... Tatari-gami (voice)<br />
	　　　　　　Akira Nagoya .... Usi-kai (voice)<br />
	　　　　　　Akihiro Miwa .... Moro-no-kimi (voice)<br />
	　　　　　　Mitsuko Mori .... Hii-sama (voice)<br />
	　　　　　　Hisaya Morishige .... Okkoto-nusi (voice)<br />
	◆类　　型：动画/冒险<br />
	◆国　　别：日本<br />
	◆出品年份：1997<br />
	◆IMDB评分：8.3/10 (57,888 votes) Top 250: #128<br />
	◆影片长度：134 Min<br />
	◆对白语言：日语/英语/普通话<br />
	◆字幕语言：英文/中文</p>

<p>
	影片简介</p>
<p>
	　　《幽灵公主》自一公映，就一度占据着日本电影票房总收入的冠军位置。<br />
	　　<br />
	　　《幽》的背景是日本中世纪的室町时代，描述人神魔三者之间的斗争。影片给很多观众带来了震撼性的冲击，《幽》的剧本酝酿长达十六年之久，胶片总数多达13万5000张，这可以说是史无前例的，荧光巨人、魔崇神等也运用了CG数码合成技术(并不是象某动画片只是使用二维的动画和三维的背景勉强地拼凑起来)，片中也有宫崎骏电影中鲜有的残酷血腥的断头断臂镜头。虽然有着一系列视觉上的震撼，但主要的冲击还是来自精神上的。<br />
	　　<br />
	　　宫崎骏将&ldquo;人&rdquo;和&ldquo;自然&rdquo;视为永远不能相互妥协的两个极端，认为人必须破坏自然才能得到自身的生存，而在片中，阿席达卡为了协调两方和平共处一度在人神之间周旋，但最终也是悲剧性的结局，人和神两败俱伤。阿席达卡也说：&ldquo;我已经尽力阻止过了(指人神大战)，但最终还是失败了。&rdquo;但不管人与自然相互共存的问题能否得到解决，作为人类首要的是应该生存下去。<br />
	　　<br />
	　　影片最后猪神的死亡令万物得以重生，人们也得重新开始新的生活，阿席达卡对桑说：&ldquo;我们一齐要活下去！&rdquo;再次重申了全剧的主题。<br />
	　　<br />
	　　幽灵公主剧情简介<br />
	　　<br />
	　　古时遭受侵略而移居远方的虾夷族青年阿斯达卡，为了拯救遭受危险的村人，右手被凶煞神诅咒，为了寻找解除诅咒的方法，阿斯达卡决定离开亲人到西方去流浪。<br />
	　　<br />
	　　在旅行中他见到了一群由幻姬大人领导的贫穷人们。他们在麒鳞兽的森林开采铁矿，并在森林中建立炼铁厂。然而森林中的种种生物都视他们为敌，总是袭击人类。有着三百岁智慧的白狼神莫娜和被她养大的人类女孩&ldquo;幽灵公主&rdquo;桑更是时刻想杀死幻姬，毁灭人类的城市。阿斯达卡既被桑所深深的吸引，理解&ldquo;幽灵公主&rdquo;保护森林的心情，但同时又想帮助人类。在战斗的过程中阿斯达卡被麒鳞兽所救，立场更加摇摆不定。<br />
	　　<br />
	　　以疙瘩和尚为首的一批人受领主的命令来杀麒鳞兽，更利用幻姬的力量与反攻人类的大批山猪作战。幻姬以火枪杀死麒鳞兽，失去头颅的麒鳞兽为了夺回自己的头对森林造成了极大的破坏。阿斯达卡和桑合力将麒鳞兽的头颅从疙瘩和尚手里多回，并还给了愤怒的麒鳞兽，麒鳞兽的灵魂方才安息，被破坏的大自然又恢复了正常。<br />
	　　<br />
	　　由宫崎骏监督的这部作品着重描写了人类与自然界之间搏斗的经过，也道出了人类战争的残酷与无情。人类追求生存与幸福的本能，就是与自然中其它种族冲突的来源，尤其是在人类开始掌握了更高的科学技术以后。<br />
	　　<br />
	　　在宫崎骏大师的笔下，人与人、自然与人之间的关系被表现得淋漓尽致。<br />
	　　<br />
	　　幽灵公主的配乐依然是久石让所作，这次风格如同风之谷或天空之城的辽阔，但却融入了东方风格的调性，也有古代传说般的气氛。<br />
	　　<br />
	　　阿席达卡石记<br />
	　　本曲可算是全片的主题，由一开始凝重的前奏，引出气势磅礡的主旋律。在意念专辑中这首涵盖了全片所有有关的旋律，再全部编曲成一完整的整体，而原声带为了配合电影的分镜，只取最前部份，而更加强细微的气势（如最开头的两声鼓声)<br />
	　　<br />
	　　向西启程<br />
	　　阿席达卡离开故乡向西边启程，忧伤旋律再经由木笛吹奏后，有着送君一别不复返之感，但嘹亮的号角却催促着去寻找新的方向，而后配合电影辽阔优美的景色的壮丽管弦乐而去。<br />
	　　<br />
	　　祟神<br />
	　　由开头的充满怨恨的魔祟神，到人类以石火丈烧森林的情景<br />
	　　<br />
	　　妖精公主<br />
	　　配乐　电影主题曲　　<br />
	　　以这个曲调为主题曲，和阿席达卡的开头曲调同为主题，电影中以男高音米良美一主唱，而意念专辑则是少女藤泽麻衣的声调。<br />
	　　<br />
	　　木灵<br />
	　<br />
	　　炼铁厂女工的踏脚之歌<br />
	　　在电影中是炼铁厂女工排遣辛劳所唱之歌，也可看出宫崎骏的偏左思想。<br />
	　　<br />
	　　片尾森林复生</p>
<p>
	&nbsp;</p>
<p>
	<img alt="" src="/uploads/allimg/c120525/133O04540050-10D58.jpg" /></p>

<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="/uploads/allimg/c120524/133N2Z4FF-102231.jpg" />&nbsp;&nbsp;&nbsp;
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:1889/飘花电影piaohua.com幽灵公主BD中字1280高清.rmvb&nbsp;</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O04540I0-116006.jpg{/dede:field}
