{dede:field name='keywords'}超级直升机[DVD中字1024x576高清{/dede:field}
{dede:field name='description'}超级直升机[DVD中字1024x576高清版]迅雷下载、免费下载，超级直升机[DVD中字1024x576高清版]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}超级直升机[DVD中字1024x576高清版]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2009-04-06{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://e10:e10@xl2.eee4.com:9306/[3E电影站www.eee4.com]超级直升机DVD中字1024x576高清版.rmvb" target="_blank{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MP463a0-11342.jpg{/dede:field}
