<?php
$z[0]=Array("field","鼠胆熊威[DVD国语中字无水印]【",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","鼠胆熊威[DVD国语中字无水印]【声音修正】迅雷下载、免费下载，鼠胆熊威[DVD国语中字无水印]【声音修正】Gvod高清在线播放，剧情介绍等。",72,244);
$z[1][4]['name']="description";
$z[2]=Array("field","鼠胆熊威[DVD国语中字无水印]【声音修正】",246,323);
$z[2][4]['name']="title";
$z[3]=Array("field","",325,364);
$z[3][4]['name']="writer";
$z[4]=Array("field","",366,405);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-04-17",407,457);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",459,496);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://3e:3e@d8.3edyy.com:132/【3E电影院www.eee4.cc】鼠胆熊威DVD国语中字无水印[修正].rmvb\" target=_blank>ftftp://3e:3e@d8.3edyy.com:132/【3E电影院www.eee4.cc】鼠胆熊威DVD国语中字无水印[修正].rmvb</A></TD></TR></TBODY></TABLE></div><ul class=\"mmlist",498,784);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MP61230-3R09.jpg",786,868);
$z[8][4]['name']="litpic";

?>