{dede:field name='keywords'}丧尸侠(The,Revenant)DVD中字美{/dede:field}
{dede:field name='description'}丧尸侠(The Revenant)DVD中字美国恐怖2009迅雷下载、免费下载，丧尸侠(The Revenant)DVD中字美国恐怖2009Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}丧尸侠(The Revenant)DVD中字美国恐怖2009{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-03-29{/dede:field}
{dede:field name='body'}<p>
	<img src="http://attachment.yyets.com/attachment/201203/28/1439775_1332910780AHdI.jpg" /></p>

<p>
	◎译　　名　亡灵/丧尸侠<br />
	◎片　　名　The Revenant<br />
	◎年　　代　2009<br />
	◎国　　家　美国<br />
	◎类　　别　喜剧/恐怖<br />
	◎语　　言　英语<br />
	◎字　　幕　中字<br />
	◎IMDB评分 6.6/10 (1185 votes)<br />
	◎文件格式　DVD-MKV<br />
	◎视频尺寸　1280 x 544<br />
	◎IMB&nbsp; <a href="http://www.nod32jihuoma.cn/virus/fangchenmi.html">http://www.nod32jihuoma.cn/virus/fangchenmi.html</a><br />
	◎文件大小　1CD-1139mb<br />
	◎片　　长　118 mins<br />
	◎导　　演　D. Kerry Prior<br />
	◎主　　演　大卫&middot;安德斯 David Anders ....Bart<br />
	　　　　　　Senyo Amoaku ....Liquor Store Robber<br />
	　　　　　　Cathy Shim ....Sophia Chang<br />
	　　　　　　Louise Griffiths ....Janet<br />
	　　　　　　David Ury ....ATM robber<br />
	　　　　　　Mike Rad ....Shopping Cart Guy<br />
	　　　　　　Chris Wylde ....Joey<br />
	　　　　　　Jonathan Mangum ....Reporter<br />
	　　　　　　Jeff Rector ....Colonel Richards<br />
	　　　　　　Brooke Bickford ....Hollywood Girl<br />
	　　　　　　Clint Jung ....Marty<br />
	　　　　　　Amy Correa ....Latin Nurse<br />
	　　　　　　Mark Elias ....Silverlake Jake<br />
	　　　　　　Stacy Michelle Gold ....Nurse Julia<br />
	　　　　　　Braxton Honeycutt ....News anchor (as Braxton Honeycutt)<br />
	　　　　　　 Jennifer Holloway ....Reporter<br />
	　　　　　　Emilano Torres ....Miguel<br />
	　　　　　　Jacy Gross ....Mathilda<br />
	　　　　　　Michael J. Gonzalez ....Vampire<br />
	　　　　　　Wally White ....The Minister<br />
	　　　　　　Don Dunn ....Frightened Orderly<br />
	　　　　　　Bernardo Badillo ....Soldier #2<br />
	　　　　　　Twain Tyler ....ATM Patron<br />
	　　　　　　Zana Zefi ....Ms. Rahmanov<br />
	　　　　　　Suzan Averitt ....Wiccan Dancer</p>
<p>
	<br />
	◎简　　介　</p>
<p>
	　　军人Bart在一次枪战中不行身亡，尸体被运回本国安葬。几周后，Bart从棺材里复活了，他自己也不知道发生了什么，于是就来到了最好的朋友JOEY家中。经过观察发现Joey有着类似吸血鬼的体质，天一亮就变成尸体，一到晚上就会复活，并且需要吸人血维持生命，否则就会腐烂。于是在Joey的帮助下，两个人开始了寻找目标....</p>
<p>
	<img src="http://www.fckb.net/data/attachment/forum/201203/27/1323087lljouj1lylb0sjy.jpg" style="border-right: 0px solid; border-top: 0px solid; border-left: 0px solid; width: 600px; cursor: hand; border-bottom: 0px solid" title="看原大图" /></p>
<p>
	<img src="http://www.fckb.net/data/attachment/forum/201203/27/132311zurfznw8syg8rqje.jpg" style="border-right: 0px solid; border-top: 0px solid; border-left: 0px solid; width: 600px; cursor: hand; border-bottom: 0px solid" title="看原大图" /></p>
<p>
	<img src="http://www.fckb.net/data/attachment/forum/201203/27/132316amkhjmqs5s3jkjzo.jpg" style="border-right: 0px solid; border-top: 0px solid; border-left: 0px solid; width: 600px; cursor: hand; border-bottom: 0px solid" title="看原大图" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="word-break: break-all; line-height: 18px" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3099/飘花电影piaohua.com丧尸侠(The Revenant)DVD中字.mkv">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3099/飘花电影piaohua.com丧尸侠(The Revenant)DVD中字.mkv">ftp://dy44:piaohua@dy44.piaohua.com:3099/飘花电影piaohua.com丧尸侠(The Revenant)DVD中字.mkv</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O162X640-11H4.jpg{/dede:field}
