{dede:field name='keywords'}韩国巨星演唱会迅雷下载，免费下{/dede:field}
{dede:field name='description'}韩国巨星演唱会迅雷下载、免费下载，韩国巨星演唱会Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}韩国巨星演唱会{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2006-08-04{/dede:field}
{dede:field name='body'}<P>播放后双击视频“全屏”</P> 
<object classid="CLSID:22d6f312-b0f6-11d0-94ab-0080c74c7e95" class="OBJECT" id="MediaPlayer" width="500" height="350" ><param name="ShowStatusBar" value="-1"><param name="Filename" value="http://vod2.ytn.co.kr/ytnstar/special/mov/tower/2006/05/200605021244215603_s.wmv"></embed></object><br /> 
<P>下载地址<BR></P> <br>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120524/133N353DD0-2G248.gif{/dede:field}
