{dede:field name='keywords'}布鲁克斯先生BD1280高清迅雷下载{/dede:field}
{dede:field name='description'}布鲁克斯先生BD1280高清迅雷下载、免费下载，布鲁克斯先生BD1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}布鲁克斯先生BD1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-09{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://i292.photobucket.com/albums/mm22/Slicer42/Mr Brooks/MR-BROOKS.jpg" style="width: 691px; height: 1024px" /></p>
<p>
	◎译　　名　布鲁克斯先生<br />
	◎片　　名　Mr Brooks<br />
	◎年　　代　2007<br />
	◎国　　家　美国<br />
	◎类　　别　犯罪/剧情/惊悚<br />
	◎语　　言　英语<br />
	◎字　　幕　中文</p>
<p>
	◎IMDB评分 &nbsp;7.5/10 (49,575 votes)<br />
	◎IMDB链接 &nbsp;<a href="http://www.imdb.com/title/tt0780571" target="_blank">http://www.imdb.com/title/tt0780571</a><br />
	◎片　　长　2h:00m<br />
	◎导　　演　布鲁斯&middot;A&middot;埃文斯 Bruce A. Evans<br />
	◎主　　演　凯文&middot;科斯特纳 Kevin Costner .....Mr. Brooks<br />
	　　　　　　威廉&middot;赫特 William Hurt .....Marshall<br />
	　　　　　　黛咪&middot;摩尔 Demi Moore .....Tracy Atwood<br />
	　　　　　　戴恩&middot;库克 Dane Cook .....Mr. Smith<br />
	　　　　　　詹森&middot;刘易斯 Jason Lewis .....Jesse Vialo<br />
	　　　　　　Steve Coulter .....Roger<br />
	　　　　　　Stephen Michael Ayers .....Mr. Clifford<br />
	　　　　　　Laura Bailey .....Flight Attendant<br />
	　　　　　　Megan Brown .....Dance Couple (Woman)<br />
	　　　　　　　　　　　　<br />
	<br />
	◎简　　介<br />
	<br />
	&nbsp; &nbsp; &nbsp; 每一个人，都在天堂与地狱之间不停地徘徊，一步之差，就会万劫不复。<br />
	　　大多数时间里，我们呈现出来的都是一个极其正常的自我，有点小缺陷，也会犯点小错误，但总地来说，我们所做的一切都是可以宽恕的&hellip;&hellip;我们还会将那个时刻蠢蠢欲动的邪恶自我尘封起来，打上烙印，可能有的人一辈子都不敢确定自己是否真的存在着第二种人格，因为当习惯成自然之后，我们的行为和选择也就变得理所当然。<br />
	　　当然，这种生存的常态在布鲁克斯先生身上是不适用的，因为他远比普通人要成功得多：富有的商人、慷慨的慈善家、贴心的丈夫、可敬的父亲&hellip;&hellip;这些赞美的词语似乎仍然无法全面地概括出他的好。布鲁克斯先生还是自己所在社区一言九鼎的大家长，邻里有困难了，都会找他帮忙--是的，每一个人都说：他是完美的。<br />
	　　但是，恐怕任谁都想象不到，这样一个西装革履的翩翩君子，其实也窝藏着一个不为人知的险恶秘密--他的另一个身份是极度嗜血、声名狼藉的连环杀人犯，外号叫&ldquo;拇指纹杀手&rdquo;。他的手法利索、计划周密，即使是罪犯，也是最聪明的那种，直到现在，从没有人对布鲁克斯先生产生过哪怕一丁点的怀疑。<br />
	　　在布鲁克斯先生的主观意识里，其实还是非常渴望停止这种需求无度的杀人行为的，可是他那病态的强迫性的杀人冲动却一而再、再而三地占据了他整个身体，使布鲁克斯先生分裂出另一个人格--马歇尔，是这个世界上最狡猾、最邪恶的杀人凶手，布鲁克斯先生只能自欺欺人地将所有的罪过都归结在马歇尔的强势上。<br />
	　　当布鲁克斯先生再一次向有如毒瘾的杀人欲望屈服时，他杀死了一对夫妇，也犯下了生平第一次、也是最致命的一次错误--他作案的过程，被一个有偷窥欲的摄影师拍了下来&hellip;&hellip;然而，这位摄影师并没有选择报警，而是拿着这一沓相片勒索已经是社会名流的布鲁克斯先生。与此同时，女警探特蕾西也将怀疑的目光投射过来，布鲁克斯先生第一次置身于双重的危机之中，能否继续隐藏他的秘密身份，全看他最终的一搏是否能够奏效了。<br />
	<br />
	&nbsp;<br />
	&nbsp; &nbsp;<br />
	◎幕后制作<br />
	<br />
	&nbsp; &nbsp; &nbsp; &nbsp;<b>◇【故事简析】</b><br />
	　　《布鲁克斯先生》引出了一个让人非常不安的问题：某个充满人格魅力的人--可能是你的邻居、同事或家人，竟然是一个让社会产生恐慌的连环杀人犯，你会做出什么样的反应呢？也许你会说，这样的故事主题，在好莱坞已经不新鲜了，许多编剧和导演都已经通过各种各样的影片探索过这方面的问题了&hellip;&hellip;《布鲁克斯先生》确实可以归类到这种&ldquo;人格分裂&rdquo;的俗套领域中，但却是以一种全新的形式表现出来的，影片所展现的世界，是一个充满着无法解释的谜题的悬疑地带：一个人如何在成功人士和可怕罪犯之间找到一个生存的平衡点？布鲁克斯先生确实是那种会让你感到无比骄傲的朋友，可是他同时也是你最不愿意在漆黑的夜晚遭遇的恐怖杀人犯。<br />
	　　 导演布鲁斯&middot;A&middot;埃文斯(Bruce A. Evans)与他长久以来的编剧合作伙伴雷纳尔多&middot;吉迪恩(Raynold Gideon)共同为影片创作了剧本，埃文斯表示：&ldquo;布鲁克斯先生很可能与你认识的一个人非常相似--我们都有邪恶的一面，但绝不会像布鲁克斯先生这样将其发挥到极致。你可能认为他是那种连一只飞虫都不舍得伤害的善心人士，享受着生活，爱着他身边的每一个人，从各个角度衡量，他都拥有一个美妙的人生&hellip;&hellip;只除了一点，他的内心深处有着严重到无法控制的强迫性冲动。&rdquo;埃文斯和吉迪恩共同创作的最著名的本子，就是那部曾获得奥斯卡最佳编剧奖提名的《站在我这边》(Stand By Me)，另外，还有像《野蛮城市》(Jungle 2 Jungle)这种非常出众的喜剧以及科幻爱情片《外星恋》(Star Man)，如此看来，《布鲁克斯先生》是两人之前从未涉足过的电影类型。<br />
	　　 雷纳尔多&middot;吉迪恩说：&ldquo;我们通常都会创作那种家庭类的故事，但是黑暗一些的电影内容却是我们一直以来的心之所向。我和布鲁斯&middot;A&middot;埃文斯都认为&lsquo;上瘾成癖&rsquo;本身就是一个非常有趣的概念，于是我们就想了，这个世界上最可怕的癖好是什么呢？既不是酒瘾，也不是毒瘾，而是一个看似正常的男人，却对杀人有着无法抑制的冲动&hellip;&hellip;一旦有了第一次，就再也无法回头，即使他知道这种行为不仅将自己推向了深渊，还让他的家人陷入了危险之中。&rdquo;<br />
	<br />
	　　<b>◇【分裂人格所带来的双重人生】</b><br />
	　　布鲁克斯先生+马歇尔，形成了《布鲁克斯先生》的基本故事框架--马歇尔代表着布鲁克斯先生无法说出口的最可怕的想法，那是一种强迫性的欲望的具体体现，类似于那种邪恶版本的&ldquo;想象中的朋友&rdquo;。布鲁斯&middot;A&middot;埃文斯说：&ldquo;马歇尔就像是一种时常出现在脑海里的声音，&lsquo;继续，变得更坏，这太有意思了。&rsquo;这个角色给了我们将声音形体化的一个机会。&rdquo;<br />
	　　 我们可以说马歇尔其实就是一个普通人脑袋里不道德的疯狂，这种注解确实很有独创风格，布鲁斯&middot;A&middot;埃文斯和雷纳尔多&middot;吉迪恩所要做的，就是深入到布鲁克斯先生的血管中去，然后通过他的血液进入最糟糕的噩梦当中，尤其是在他发现自己正被一名警探和一个年轻的&lsquo;粉丝&rsquo;追踪时--布鲁克斯先生面对着自己最可怕的秘密最终会大白于天下的可能，不断地挣扎着、反抗着。<br />
	　　 大众化或者经典的电影，都曾无数次描绘过连环杀手在现实中可能会出现的样子--包括&ldquo;汉尼拔&rdquo;系列以及电影《十二宫》、《杀魂手》(The Boston Strangler)、《天才雷普利》、《火车怪客》(Strangers on a Train)、《七宗罪》、《1999惊魂记》(Psycho)等等，当然，这里还包括任何与&ldquo;开膛手杰克&rdquo;有关的杀人电影&hellip;&hellip;但布鲁斯&middot;A&middot;埃文斯和雷纳尔多&middot;吉迪恩却认为《布鲁克斯先生》有足够的能力可以突破至一个全新的故事领域，因为影片中的主角的犯罪手段是与众不同的：布鲁克斯先生对待进入他眼帘的牺牲品，就好像是在谈恋爱。他先是仔细地挑选，然后跟踪他们，甚至连他们的习惯和生活方式都了如指掌。最后，他会以一种纯粹、愉悦的心情，用一种非常可怕、但极有效率的杀人手段，为这段&ldquo;恋爱关系&rdquo;画上一个圆满的句号。埃文斯表示：&ldquo;布鲁克斯先生并非一个一流的连环杀手，却有着绝佳的洞察力，善于观察身边的人，所以他永远都是人群中最聪明的那个&hellip;&hellip;这是他能够成为一名成功的商人、一位完美的丈夫的根本原因，因为他总是能看透别人的想法--这也成了杀手必不可少的成功因素，他不仅能读懂死于他手中的受害者，还会洞悉负责调查案件的警察的思想，事事抢得先机。&rdquo;<br />
	　　 布鲁克斯先生也是他所在社区高尚和正义的代名词，即使新闻媒体在描述一个谋杀犯时，都会用类似&ldquo;他曾经是一个好人&rdquo;或&ldquo;他可能非常有魅力&rdquo;这样的字眼为人们敲响警钟，但却很少有人愿意相信自己所崇敬的人竟然是个杀人不眨眼的魔头。布鲁斯&middot;A&middot;埃文斯补充道：&ldquo;要知道那位被外人称为&lsquo;BTK杀手&rsquo;的丹尼斯&middot;雷德，他的真实身份就是一名教堂的执事，年逾60岁&hellip;&hellip;人们总会将他黑暗或邪恶的一面隐藏起来，而布鲁克斯先生所代表的，正是人心中不可避免的那一部分，只是被扩大到了极致而已。&rdquo;<br />
	　　 于是，这个围绕着布鲁克斯先生展开的故事就渐渐有了轮廓，就连两位编剧自己都对影片发展方向所带出来的疯狂曲线而感到吃惊。雷纳尔多&middot;吉迪恩说：&ldquo;我们倾向于将这种惊讶的心情保持住，然后以一种有机的方式写进剧本当中，想象一下，故事中的马歇尔是以一种非常突然的方式出现的，他说出了布鲁克斯先生不敢说出口的恐惧、幻觉、愤怒以及误解--这本身就是一种让人吓一跳的表现形式，却也是马歇尔残存的本能。&rdquo;<br />
	　　 而故事的基调也是朝着一个有机的方向发展的，既有黑色喜剧的特点，又包含了黑色电影的风格，布鲁斯&middot;A&middot;埃文斯表示：&ldquo;多么黑暗的故事，我和雷纳尔多&middot;吉迪恩都会为其注入一些喜剧元素，那是因为这本来就是我们看待生活的方式。也许你觉得生命的轨迹有时候就有如在深渊的边缘行走，一不小心就会永无出头之日&hellip;&hellip;但我要说的是，其实生活是非常有趣的，不管你曾经历过多么黑暗的过去，却总能被充满阳光的未来所吸引，继续前进。&rdquo;<br />
	　　 一旦布鲁克斯先生和马歇尔各就各位，故事就开始以快到无法再快的极限速度构架成功&hellip;&hellip;布鲁斯&middot;A&middot;埃文斯和雷纳尔多&middot;吉迪恩仅用了10周的时间，就完成了剧本。而他们在创作的过程中，顺便还挑出了饰演布鲁克斯先生的最完美演员人选，埃文斯对此的解释是：&ldquo;通常情况下，凯文&middot;科斯特纳总是以正面的男性形象示人，有的时候是甜蜜的爱人，有的时候又化身成为动作英雄--所以他突然而至的邪恶，更会让你感到无比地震惊。&rdquo;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</p>
<p>
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120507/13/62564813201205071316582468663602575_006.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120507/13/62564813201205071316582468663602575_005.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120507/13/62564813201205071316582468663602575_004.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120507/13/62564813201205071316582468663602575_003.jpg" style="width: 720px; height: 405px" /></p>
<p>
	【下载地址】</p>
<table bgcolor="#0099cc" border="0" cellpadding="10" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.net" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy125:piaohua@dy125.piaohua.com:8028/飘花电影piaohua.com布鲁克斯先生BD中字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:8028/飘花电影piaohua.com布鲁克斯先生BD中字1280高清.rmvb</a></td>
		</tr>
		<tr>
		</tr>
	</tbody>
</table>
<br />{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O159B640-14207.jpg{/dede:field}
