{dede:field name='keywords'}5大经典街球迅雷下载，免费下载{/dede:field}
{dede:field name='description'}5大经典街球迅雷下载、免费下载，5大经典街球Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}5大经典街球{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2006-09-14{/dede:field}
{dede:field name='body'}<embed name="MediaPlayer" pluginspage="http://www.microsoft.com/isapi/redir.dll?prd=windows&amp;sbp=mediaplayer&amp;ar=media&amp;sba=plugin&amp;" align="6" src="http://fmtv.uying.com/片断其他/5大经典街球.wmv" width="350" height="300" type="application/x-mplayer2" defaultframe="datawindow" invokeurls="1" clicktoplay="0" enablecontextmenu="1" allowscan="1" transparentatstart="0" animationatstart="0" autorewind="0" autostart="1" showcaptioning="0" showgotobar="0" autosize="0" showstatusbar="1" showdisplay="0" showtracker="1" showaudiocontrols="1" showpositioncontrols="0" showcontrols="1" border="0"></embed>&nbsp;{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120524/133N353DD0-2G248.gif{/dede:field}
