{dede:field name='keywords'}战争姐妹/修女的战争BD中英双字1{/dede:field}
{dede:field name='description'}战争姐妹/修女的战争BD中英双字1280高清2011最新剧情大片迅雷下载、免费下载，战争姐妹/修女的战争BD中英双字1280高清2011最新剧情大片Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}战争姐妹/修女的战争BD中英双字1280高清2011最新剧情大片{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-10-07{/dede:field}
{dede:field name='body'}<p>
	<img alt="" height="420" src="http://img2081.poco.cn/mypoco/myphoto/20110723/18/56634212201107231856452794689806147_006.jpg" width="300" /></p>
<p>
	◎译　　名　战争姐妹 / 修女的战争 / 澳大利亞二戰抗日友情的故事<br />
	◎片　　名　Sisters Of War<br />
	◎年　　代　2010<br />
	◎国　　家　澳大利亚<br />
	◎类　　别　剧情/战争<br />
	◎语　　言　英语<br />
	◎字　　幕　中文字幕<br />
	◎IMDB评分&nbsp; 8.2/10 (27 votes)<br />
	◎IMDB链接&nbsp; <a href="http://www.imdb.com/title/tt1633245">http://www.imdb.com/title/tt1633245</a><br />
	◎文件格式　DVD-RMVB<br />
	◎视频尺寸　624 x 352<br />
	◎文件大小　1CD 412MB<br />
	◎片　　长　95 Mins<br />
	◎导　　演　Brendan Maher<br />
	◎主　　演　Claire van der Boom ... Sister Berenice Twohill<br />
	　　　　　　Susie Porter ... Kay Parker<br />
	　　　　　　Byron J. Brochmann ... US Army Airborne<br />
	　　　　　　Gerald Lepkowski ... Leo Scharmach<br />
	　　　　　　Masa Yamaguchi ... Captain<br />
	　　　　　　Andy Minh Trieu<br />
	　　　　　　Sarah Snook ... Lorna Whyte<br />
	　　　　　　Emma Randall ... Joyce<br />
	　　　　　　Yutaka Izumihara<br />
	　　　　　　T. Maxwell Smith ... Burned Soldier 2 (as Tim Maxwell Otto Smith)<br />
	　　　　　　Ty Hungerford ... Major Bill Meanly<br />
	　　　　　　Helen Christinson ... Cal<br />
	　　　　　　Matthew Wollaston ... Len&#39;s Soldier<br />
	　　　　　　Glenn Chow ... Japanese soldier<br />
	　　　　　　Quentin Yung ... Japanese Soldier<br />
	　　　　　　</p>
<p>
	◎简　　介　</p>
<p>
	本片基于真实历史故事改编。1942年1月，日本战争机器的铁蹄席卷东南亚。在这里，有一个叫做新不列颠的岛屿上，有一座天主教传教站，这里的澳大利亚护士们克服种种困难的条件，悉心照顾手上的澳大利亚士兵。</p>
<p>
	<br />
	◎影片截图</p>

<p>
	<img alt="" height="338" src="http://img2081.poco.cn/mypoco/myphoto/20110723/18/56634212201107231856452794689806147_005.jpg" style="cursor: pointer" width="600" /></p>
<p>
	<img alt="" height="338" src="http://img2081.poco.cn/mypoco/myphoto/20110723/18/56634212201107231856452794689806147_004.jpg" style="cursor: pointer" width="600" /></p>
<p>
	<img alt="" height="338" src="http://img2081.poco.cn/mypoco/myphoto/20110723/18/56634212201107231856452794689806147_003.jpg" style="cursor: pointer" width="600" /></p>
<p>
	<img alt="" height="338" src="http://img2081.poco.cn/mypoco/myphoto/20110723/18/56634212201107231856452794689806147_000.jpg" style="cursor: pointer" width="600" /></p>
<p>
	<img alt="" height="338" src="http://img2081.poco.cn/mypoco/myphoto/20110723/18/56634212201107231856452794689806147_001.jpg" style="cursor: pointer" width="600" /></p>
<p>
	<img alt="" height="338" src="http://img2081.poco.cn/mypoco/myphoto/20110723/18/56634212201107231856452794689806147_002.jpg" style="cursor: pointer" width="600" /></p>
<p>
	[下载地址]： &nbsp;<img border="0" src="/images/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2005/飘花电影piaohua.com修女的战争DVD中字.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2005/飘花电影piaohua.com修女的战争DVD中字.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:1743/飘花电影piaohua.com修女的战争BD中英双字1280高清.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:1743/飘花电影piaohua.com修女的战争BD中英双字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O16253160-31640.jpg{/dede:field}
