{dede:field name='keywords'}追凶TC国语2012香港犯罪悬疑惊悚{/dede:field}
{dede:field name='description'}追凶TC国语2012香港犯罪悬疑惊悚大片迅雷下载、免费下载，追凶TC国语2012香港犯罪悬疑惊悚大片Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}追凶TC国语2012香港犯罪悬疑惊悚大片{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-21{/dede:field}
{dede:field name='body'}<p>
	&nbsp;<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120512/20/56643687201205122035482824811167745_002.jpg" /></p>
<p>
	&nbsp;<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120512/20/56643687201205122035482824811167745_001.jpg" /></p>
<p>
	&nbsp;<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120512/20/56643687201205122035482824811167745_000.jpg" /></p>
<p>
	导演: 彭发<br />
	编剧: 彭发 / 司徒锦源<br />
	主演: 刘青云 / 王宝强 / 江若琳 / 万绮雯<br />
	类型: 犯罪 / 悬疑 / 惊悚<br />
	制片国家/地区: 香港<br />
	语言: 粤语 / 汉语普通话<br />
	上映日期: 2012-05-11(中国大陆)<br />
	片长: 90分钟<br />
	又名: 索命童话 / 禁闭惊魂 / 完美童话 / Fairy Tale Killer<br />
	IMDB链接：<a href="http://www.bluemv.com">http://www.bluemv.com</a></p>
<p>
	<br />
	剧情简介</p>
<p>
	　　某晚，警察局来了一个不速之客军（王宝强 饰），他向当值探员报称自己杀了五个人，但他既说不出与受害者关系，又不能描述出受害者被杀过程或遇害地点。原来只是计划把五人杀死。探员在记下军的联络住址后便把他驱逐，在探员眼中，他只是一名无聊的精神不正常者。可是不久，督察汉（刘青云 饰）驻守的区域却发生了一件凶杀案：死者形状恐怖，汉认为这种处死方法带有不寻常的动机，不到一星期汉接手另一宗凶杀案，死者也是一名男子，死于一个废置的机械工场。他的死法十分残酷，死者的双脚被强行穿上细尺码的红色高跟鞋，脚面和两侧都钉上了十多口的铁钉。汉在翻查全港可疑人物和案例时，看到了当天军前来自首的记录。汉马上带队前往军的住所进行搜查，可是屋内空无一人，除了大量古旧童话书外，并无可疑之处。但这时候汉还不知道，一张被精密预设的大网张开了，而结局却更是匪夷所思，难以预料。</p>

<p>
	◎影片截图</p>
<p>
	&nbsp;<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120512/20/56643687201205122035482824811167745_003.jpg" /></p>
<p>
	&nbsp;<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120512/20/56643687201205122035482824811167745_005.jpg" /></p>
<p>
	&nbsp;<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120512/20/56643687201205122035482824811167745_004.jpg" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.net/movie/21387.html" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3409/飘花电影piaohua.com追凶TC国语.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3409/飘花电影piaohua.com追凶TC国语.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O16440c0-2W42.jpg{/dede:field}
