{dede:field name='keywords'}巴林世贸中心[DVD中字1024x576高{/dede:field}
{dede:field name='description'}巴林世贸中心[DVD中字1024x576高清版]迅雷下载、免费下载，巴林世贸中心[DVD中字1024x576高清版]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}巴林世贸中心[DVD中字1024x576高清版]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2009-02-27{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://e18:e18@xl2.eee4.com:9219/[3E电影站www.eee4.com]巴林世贸中心[DVD中字1024x576高清版].rmvb" target=_blank>ftftp://e18:e18@xl2.eee4.com:9219/[3E电影站www.eee4.com]巴林世贸中心[DVD中字1024x576高清版].rmvb</A></TD></TR></TBODY></TABLE></div><ul class="mmlist{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MP461530-45417.jpg{/dede:field}
