<?php
$z[0]=Array("field","巴林世贸中心[DVD中字1024x576高",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","巴林世贸中心[DVD中字1024x576高清版]迅雷下载、免费下载，巴林世贸中心[DVD中字1024x576高清版]Gvod高清在线播放，剧情介绍等。",73,237);
$z[1][4]['name']="description";
$z[2]=Array("field","巴林世贸中心[DVD中字1024x576高清版]",239,312);
$z[2][4]['name']="title";
$z[3]=Array("field","",314,353);
$z[3][4]['name']="writer";
$z[4]=Array("field","",355,394);
$z[4][4]['name']="source";
$z[5]=Array("field","2009-02-27",396,446);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",448,485);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://e18:e18@xl2.eee4.com:9219/[3E电影站www.eee4.com]巴林世贸中心[DVD中字1024x576高清版].rmvb\" target=_blank>ftftp://e18:e18@xl2.eee4.com:9219/[3E电影站www.eee4.com]巴林世贸中心[DVD中字1024x576高清版].rmvb</A></TD></TR></TBODY></TABLE></div><ul class=\"mmlist",487,785);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MP461530-45417.jpg",787,871);
$z[8][4]['name']="litpic";

?>