<?php
$z[0]=Array("field","猫和老鼠与福尔摩斯[1024/1280高",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","猫和老鼠与福尔摩斯[1024/1280高清]迅雷下载、免费下载，猫和老鼠与福尔摩斯[1024/1280高清]Gvod高清在线播放，剧情介绍等。",73,233);
$z[1][4]['name']="description";
$z[2]=Array("field","猫和老鼠与福尔摩斯[1024/1280高清]",235,306);
$z[2][4]['name']="title";
$z[3]=Array("field","",308,347);
$z[3][4]['name']="writer";
$z[4]=Array("field","",349,388);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-09-23",390,440);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",442,479);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://4e:4e@d8.3edyy.com:193/【3E电影院www.eee4.org】猫和老鼠与福尔摩斯DVD中字.rmvb\" target=\"_blank",481,619);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MQ1T230-2Ob.jpg",621,702);
$z[8][4]['name']="litpic";

?>