<?php
$z[0]=Array("field","1408幻影凶间/第1408号房间BD中",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","1408幻影凶间/第1408号房间BD中英双字1024高清迅雷下载、免费下载，1408幻影凶间/第1408号房间BD中英双字1024高清Gvod高清在线播放，剧情介绍等。",72,252);
$z[1][4]['name']="description";
$z[2]=Array("field","1408幻影凶间/第1408号房间BD中英双字1024高清",254,335);
$z[2][4]['name']="title";
$z[3]=Array("field","",337,376);
$z[3][4]['name']="writer";
$z[4]=Array("field","",378,417);
$z[4][4]['name']="source";
$z[5]=Array("field","2012-05-17",419,469);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",471,508);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://eee4.com:eee4@xl3.eee4.com:8448/1408幻影凶间/[3E迅雷电影站www.eee4.com]1408幻影凶间CD1.rmvb\" target=\"_blank",510,662);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MPGOF-462b.jpg",664,744);
$z[8][4]['name']="litpic";

?>