{dede:field name='keywords'}忍者乱太郎2011剧场版高清HD中字{/dede:field}
{dede:field name='description'}忍者乱太郎2011剧场版高清HD中字2011最新日本动画大片迅雷下载、免费下载，忍者乱太郎2011剧场版高清HD中字2011最新日本动画大片Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}忍者乱太郎2011剧场版高清HD中字2011最新日本动画大片{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-11-07{/dede:field}
{dede:field name='body'}<p>
	&nbsp;<img border="0" src="/uploads/allimg/c120525/133O044O4P-164393.jpg" style="max-width: 750px; max-height: 750px" /></p>
<p>
	导演: 藤森雅也<br />
	主演: 高山みなみ<br />
	类型: 动画<br />
	制片国家/地区: 日本<br />
	语言: 日语<br />
	上映日期: 2011-03<br />
	<br />
	<br />
	剧情简介<br />
	&nbsp; &nbsp;&nbsp; &nbsp;&nbsp;&nbsp;出生三流忍者家的乱太郎，在父母的期待下，进入忍术学院念书，并在那里交下雾丸、新兵卫两位好朋友。他们三个人无论是上课还是考试，总是一次又一次失败。一天，一名刺客想要杀害四年级的齐藤鹰丸，乱太郎一行人为了搭救朋友行动起来&hellip;&hellip;<br />
	<br />
	&nbsp; &nbsp;&nbsp; &nbsp;&nbsp;&nbsp;《忍者乱太郎》是一部日本的动画影集，改编自尼子骚兵卫原作的漫画《落第忍者乱太郎》。<br />
	<br />
	　　故事发生在战国时代。出生于普通忍者家庭的猪名寺 乱太郎为不负父母的厚望成为精英忍者而进入学忍术学校。在那里认识了富商的儿子福富 しんべヱ和战争中丧失父母的摄津の きり丸，并成为好友，组成了&ldquo;三人组&rdquo;。每集内容主要讲述三位&ldquo;忍蛋&rdquo;（小忍者）在忍者学校所发生的趣事。电视系列剧曾先后在中国大陆、台湾、香港播映。忍术学校的目的是培养小忍者。在忍术学校里有不同学科的教授，性格各异的老师 ，高年级的天才忍者，女忍者，还有忍犬ヘムヘム，古怪的校长大川 平次 涡正，非常之热闹！乱太郎们三人组在上课和考试中常常失败，并且总是在问为什么，但他们仍坚持着并立志成为一流的出色忍者。忍术学校的校长的变幻无常，总是作出奇奇怪怪的决定，因而发生了许多有趣的故事，乱太郎等也常卷入各种各样的事件。小忍者们充满正义感，面对任何困难都努力解决。<br />
	<br />
	<br />
	◎影片截图<br />
	<br />
	<img alt="" border="0" height="337" src="/uploads/allimg/c120525/133O044Q0P-1GJ1.jpg" width="600" /><br />
	<br />
	<img alt="" border="0" height="337" src="/uploads/allimg/c120525/133O044R160-1Y638.jpg" width="600" /><br />
	<br />
	<img alt="" border="0" height="337" src="/uploads/allimg/c120525/133O044S250-1a116.jpg" width="600" /><br />
	<br />
	<img alt="" border="0" height="337" src="/uploads/allimg/c120525/133O044T330-20H01.jpg" width="600" /><br />
	&nbsp;</p>
<p>
	[下载地址]： &nbsp;<img border="0" src="/uploads/allimg/c120524/133N2Z4FF-102231.jpg" />
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:2010/飘花电影piaohua.com忍者乱太郎2011剧场版HD中字.rmvb</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O044U410-211153.jpg{/dede:field}
