{dede:field name='keywords'}ﾅ､ﾇ嶹ﾄｴｺﾃﾎ/ﾕｲｵﾄｹﾊﾊﾂ/ｼﾄｹﾊﾊﾂ/{/dede:field}
{dede:field name='description'}ﾅ､ﾇ嶹ﾄｴｺﾃﾎ/ﾕｲｵﾄｹﾊﾊﾂ/ｼﾄｹﾊﾊﾂ/ﾉﾙﾅｮｵﾄﾐﾄﾁﾖ[DVDﾖﾐﾗﾖ]ﾑｸﾀﾗﾏﾂﾔﾘ｡｢ﾃ箙ﾑﾏﾂﾔﾘ｣ｬﾅ､ﾇ嶹ﾄｴｺﾃﾎ/ﾕｲｵﾄｹﾊﾊﾂ/ｼﾄｹﾊﾊﾂ/ﾉﾙﾅｮｵﾄﾐﾄﾁﾖ[DVDﾖﾐﾗﾖ]Gvodｸﾟﾇ袂ﾚﾏﾟｲ･ｷﾅ｣ｬｾ酩鮨鯔ﾜｵﾈ｡｣{/dede:field}
{dede:field name='title'}ﾅ､ﾇ嶹ﾄｴｺﾃﾎ/ﾕｲｵﾄｹﾊﾊﾂ/ｼﾄｹﾊﾊﾂ/ﾉﾙﾅｮｵﾄﾐﾄﾁﾖ[DVDﾖﾐﾗﾖ]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2009-11-24{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://4e:4e@www2.eee4.com:908/[3Eｵ醺ｰﾕｾwww.eee4.cn]ﾅ､ﾇ嶹ﾄｴｺﾃﾎ.rmvb" target=_blank>ftftp://4e:4e@www2.eee4.com:908/[3Eｵ醺ｰﾕｾwww.eee4.cn]ﾅ､ﾇ嶹ﾄｴｺﾃﾎ.rmvb</A></TD></TR></TBODY></TABLE></div><ul class="mmlist{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MP464430-2U20.jpg{/dede:field}
