<?php
$z[0]=Array("field","ﾅ､ﾇ嶹ﾄｴｺﾃﾎ/ﾕｲｵﾄｹﾊﾊﾂ/ｼﾄｹﾊﾊﾂ/",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","ﾅ､ﾇ嶹ﾄｴｺﾃﾎ/ﾕｲｵﾄｹﾊﾊﾂ/ｼﾄｹﾊﾊﾂ/ﾉﾙﾅｮｵﾄﾐﾄﾁﾖ[DVDﾖﾐﾗﾖ]ﾑｸﾀﾗﾏﾂﾔﾘ｡｢ﾃ箙ﾑﾏﾂﾔﾘ｣ｬﾅ､ﾇ嶹ﾄｴｺﾃﾎ/ﾕｲｵﾄｹﾊﾊﾂ/ｼﾄｹﾊﾊﾂ/ﾉﾙﾅｮｵﾄﾐﾄﾁﾖ[DVDﾖﾐﾗﾖ]Gvodｸﾟﾇ袂ﾚﾏﾟｲ･ｷﾅ｣ｬｾ酩鮨鯔ﾜｵﾈ｡｣",72,262);
$z[1][4]['name']="description";
$z[2]=Array("field","ﾅ､ﾇ嶹ﾄｴｺﾃﾎ/ﾕｲｵﾄｹﾊﾊﾂ/ｼﾄｹﾊﾊﾂ/ﾉﾙﾅｮｵﾄﾐﾄﾁﾖ[DVDﾖﾐﾗﾖ]",264,350);
$z[2][4]['name']="title";
$z[3]=Array("field","",352,391);
$z[3][4]['name']="writer";
$z[4]=Array("field","",393,432);
$z[4][4]['name']="source";
$z[5]=Array("field","2009-11-24",434,484);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",486,523);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://4e:4e@www2.eee4.com:908/[3Eｵ醺ｰﾕｾwww.eee4.cn]ﾅ､ﾇ嶹ﾄｴｺﾃﾎ.rmvb\" target=_blank>ftftp://4e:4e@www2.eee4.com:908/[3Eｵ醺ｰﾕｾwww.eee4.cn]ﾅ､ﾇ嶹ﾄｴｺﾃﾎ.rmvb</A></TD></TR></TBODY></TABLE></div><ul class=\"mmlist",525,767);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MP464430-2U20.jpg",769,852);
$z[8][4]['name']="litpic";

?>