{dede:field name='keywords'}悬赏缉拿HD1280迅雷下载，免费下{/dede:field}
{dede:field name='description'}悬赏缉拿HD1280迅雷下载、免费下载，悬赏缉拿HD1280Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}悬赏缉拿HD1280{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-21{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120519/23/17870980201205192313103267822341341_008.jpg" /></p>
<p>
	片名：悬赏缉拿<br />
	类型：剧情 　　<br />
	主演：赵小亮 　　<br />
	导演：王光利 　　<br />
	出品人：阎晓明 　　<br />
	总监制：岳扬 　　<br />
	编剧：汪奕升 　　<br />
	摄影：伍卫东 　　<br />
	美术：李大禹</p>
<p>
	<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120519/23/17870980201205192313103267822341341_007.jpg" /><br />
	<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120519/23/17870980201205192313103267822341341_005.jpg" /><br />
	&nbsp;<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120519/23/17870980201205192313103267822341341_004.jpg" style="width: 640px; height: 360px" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.net/" target="_blank">http://www.xiaozhizhu.net/</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy241:piaohua@117.41.229.29:2028/飘花电影piaohua.com悬赏缉拿HD1280.rmvb">ftp://dy241:piaohua@117.41.229.29:2028/飘花电影piaohua.com悬赏缉拿HD1280.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O16010c0-11K2.jpg{/dede:field}
