<?php
$z[0]=Array("field","刀锋战士/幽灵刺客3部BD中英双字",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","刀锋战士/幽灵刺客3部BD中英双字1024/1280高清迅雷下载、免费下载，刀锋战士/幽灵刺客3部BD中英双字1024/1280高清Gvod高清在线播放，剧情介绍等。",73,253);
$z[1][4]['name']="description";
$z[2]=Array("field","刀锋战士/幽灵刺客3部BD中英双字1024/1280高清",255,336);
$z[2][4]['name']="title";
$z[3]=Array("field","",338,377);
$z[3][4]['name']="writer";
$z[4]=Array("field","",379,418);
$z[4][4]['name']="source";
$z[5]=Array("field","2012-03-28",420,470);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",472,509);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://3e:3e@www2.eee4.com:309/[3E电影站www.eee4.com]刀锋战士DVD中英双字1280x720高清版.rmvb\" target=\"_blank",511,656);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MO523220-59D1.jpg",658,741);
$z[8][4]['name']="litpic";

?>