{dede:field name='keywords'}自然大事件HD中英双字1280高清BB{/dede:field}
{dede:field name='description'}自然大事件HD中英双字1280高清BBC纪录片迅雷下载、免费下载，自然大事件HD中英双字1280高清BBC纪录片Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}自然大事件HD中英双字1280高清BBC纪录片{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-12-26{/dede:field}
{dede:field name='body'}<p>
	<img alt="" border="0" onload_fckprotectedatt="%20onload%3D%22attachimg(this%2C%20'load')%22" src="http://img.album.pchome.net/54/69/39/44/aa0553e6f238e9e2818dbdbd20409ef0.jpg" /><br />
	【译　　名】自然大事件<br />
	【片　　名】Natures Great Events with Sir David Attenborough<br />
	【年　　代】2009<br />
	【国　　家】英国BBC<br />
	【类　　别】纪录片<br />
	【语　　言】英语<br />
	【字幕语言】中文/英文<br />
	【视频尺寸】1280&times;720<br />
	【文件格式】RMVB+AAC<br />
	<br />
	【简　　介】<br />
	<br />
	　　This fantastic series from the BBC&#39;s renowned Natural History Unit combines the epic scale of Planet Earth and the intimate, emotional stories of charismatic animals as they struggle to survive. Using state of the art HD technology, these amazing programmes capture the Earth&#39;s most dramatic and epic wildlife spectacles and the intimate stories of the animals caught up in them.<br />
	　　Every year, around the world, seasonal changes transform entire landscapes and draw in millions of creatures as these great events unfold.<br />
	<br />
	　　这套BBC人类史诗级巨献囊括了整个地球的生态环境，动物的生存情态.在HD高清技术的制作基础上,这些令人惊异的地球生态画面以及沉湎于动物之间的生活记事活生生地展现在我们眼前.<br />
	年复一年,纵观世界,四季的变化牵动着整个大地,我们即将揭开亿万生物隐藏在背后的大事件.<br />
	<br />
	<br />
	Part 1: Melt世纪大消融章<br />
	The Artic&#39;s Great Melt that finds polar bear families navigating their precarious way on ever-thining ice.<br />
	探索了北极熊家族&nbsp;&nbsp;如何在日渐变薄的冰层之上克服困难前行的奥秘<br />
	<img alt="" border="0" onclick_fckprotectedatt="%20onclick%3D%22zoom(this%2C%20this.src)%22" onload_fckprotectedatt="%20onload%3D%22attachimg(this%2C%20'load')%22" resized="true" src="http://img.album.pchome.net/54/69/34/85/8424ad1d34943a96195b6d9cb50704f0.jpg" style="cursor: pointer" width="1028" /><br />
	<img alt="" border="0" onclick_fckprotectedatt="%20onclick%3D%22zoom(this%2C%20this.src)%22" onload_fckprotectedatt="%20onload%3D%22attachimg(this%2C%20'load')%22" resized="true" src="http://img.album.pchome.net/54/69/34/85/7a3f766c5201d9b826e3f2c39c4f50b0.jpg" style="cursor: pointer" width="1028" /><br />
	<br />
	Part 2: Salmon Run 马哈鱼大逃亡<br />
	British Columbia&#39;s Great Salmon Run where grizzly bears use ingenuity and fancy footwork to collect their catch.<br />
	英国哥伦比亚大马哈鱼的逃亡 为以灵巧著称的大灰熊创造了集中狩猎的好时机<br />
	<img alt="" border="0" onclick_fckprotectedatt="%20onclick%3D%22zoom(this%2C%20this.src)%22" onload_fckprotectedatt="%20onload%3D%22attachimg(this%2C%20'load')%22" resized="true" src="http://img.album.pchome.net/54/69/39/44/d701fe87d50f76f0384bf23b52f5d329.jpg" style="cursor: pointer" width="1028" /><br />
	<img alt="" border="0" onclick_fckprotectedatt="%20onclick%3D%22zoom(this%2C%20this.src)%22" onload_fckprotectedatt="%20onload%3D%22attachimg(this%2C%20'load')%22" resized="true" src="http://img.album.pchome.net/54/69/39/44/d1855f51cc9cebf510cffe207d1c6425.jpg" style="cursor: pointer" width="1028" /><br />
	<br />
	Part 3: Migration 塞伦盖蒂平原大迁徙<br />
	The Great Migration of the Serengeti that tests the survival skills of a pride of lions with young cubs.<br />
	塞伦盖蒂平原的大迁徙检验了骄傲的狮群及其幼崽的生存技能<br />
	<img alt="" border="0" onclick_fckprotectedatt="%20onclick%3D%22zoom(this%2C%20this.src)%22" onload_fckprotectedatt="%20onload%3D%22attachimg(this%2C%20'load')%22" resized="true" src="http://img.album.pchome.net/54/69/39/44/230f2ceca8ffdf25ae4710ab54003bee.jpg" style="cursor: pointer" width="1028" /><br />
	<img alt="" border="0" onclick_fckprotectedatt="%20onclick%3D%22zoom(this%2C%20this.src)%22" onload_fckprotectedatt="%20onload%3D%22attachimg(this%2C%20'load')%22" resized="true" src="http://img.album.pchome.net/54/69/39/44/11eaabc4a5505cbac23b4a330d9380bf.jpg" style="cursor: pointer" width="1028" /><br />
	<br />
	Part 4: Tide 潮汐<br />
	The Great Tide of billions of sardines along South Africa&#39;s east coast creates an action-packed feeding frenzy of thousands of dolphins, sharks, whales, seals and gannets.<br />
	沿着南非的东海岸游走的沙丁鱼与以其为食的鲨鱼、海豚、布氏鲸等编织了世界上最宏大的海洋奇观。<br />
	[img]<img alt="" border="0" onclick_fckprotectedatt="%20onclick%3D%22zoom(this%2C%20this.src)%22" onload_fckprotectedatt="%20onload%3D%22attachimg(this%2C%20'load')%22" resized="true" src="http://img.album.pchome.net/54/69/39/44/9cbdd054a1d34c4f0c34f1fb0a9f5558.jpg" style="cursor: pointer" width="1028" />[/img]<br />
	<img alt="" border="0" onclick_fckprotectedatt="%20onclick%3D%22zoom(this%2C%20this.src)%22" onload_fckprotectedatt="%20onload%3D%22attachimg(this%2C%20'load')%22" resized="true" src="http://img.album.pchome.net/54/69/39/44/97248ae7c4a51d3010436e8579ccd0f4.jpg" style="cursor: pointer" width="1028" /><br />
	<br />
	Part 5: Flood 奥卡万戈大洪水<br />
	The Great Flood of the Okavango Delta in Botswana draws families of elephants, who undertake an epic trek to reach it.<br />
	成千上万的动物穿越喀拉哈里沙漠之时，也正是博茨瓦纳奥卡万戈三角洲一年一度的洪水到来之际。<br />
	<img alt="" border="0" onclick_fckprotectedatt="%20onclick%3D%22zoom(this%2C%20this.src)%22" onload_fckprotectedatt="%20onload%3D%22attachimg(this%2C%20'load')%22" resized="true" src="http://img.album.pchome.net/54/69/39/44/a799674e2d75ee92efc06fe3b527f367.jpg" style="cursor: pointer" width="1028" /><br />
	<img alt="" border="0" onclick_fckprotectedatt="%20onclick%3D%22zoom(this%2C%20this.src)%22" onload_fckprotectedatt="%20onload%3D%22attachimg(this%2C%20'load')%22" resized="true" src="http://img.album.pchome.net/54/69/39/44/063cfdfde42c1e9a95f697e6d604d36a.jpg" style="cursor: pointer" width="1028" /><br />
	<br />
	Part 6: Feast 阿拉斯加海岸盛宴<br />
	The plankton bloom of the Great Feast in Alaska&#39;s coastal waters attracts humpback whales and sea lions, who face the dangers of killer whales.<br />
	阿拉斯加海岸大量的浮游生物 吸引了一批批的驼背鲸和海狮,冒着被虎鲸猎杀的危险 来赴此盛宴<br />
	<img alt="" border="0" onclick_fckprotectedatt="%20onclick%3D%22zoom(this%2C%20this.src)%22" onload_fckprotectedatt="%20onload%3D%22attachimg(this%2C%20'load')%22" resized="true" src="http://img.album.pchome.net/54/69/39/44/fc858f3a86f31593b4238f2fae7992e3.jpg" style="cursor: pointer" width="1028" /><br />
	<img alt="" border="0" onclick_fckprotectedatt="%20onclick%3D%22zoom(this%2C%20this.src)%22" onload_fckprotectedatt="%20onload%3D%22attachimg(this%2C%20'load')%22" resized="true" src="http://img.album.pchome.net/54/69/39/44/1e60b424cdf0ee2dfe16fd1d0fe03974.jpg" style="cursor: pointer" width="1028" /></p>
<p>
	&nbsp;</p>
<p>
	[下载地址]：&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2443/飘花电影piaohua.com自然大事件HD中英双字1280高清1.rmvb ">ftp://dy44:piaohua@dy44.piaohua.com:2443/飘花电影piaohua.com自然大事件HD中英双字1280高清1.rmvb </a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2443/飘花电影piaohua.com自然大事件HD中英双字1280高清2.rmvb ">ftp://dy44:piaohua@dy44.piaohua.com:2443/飘花电影piaohua.com自然大事件HD中英双字1280高清2.rmvb </a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2444/飘花电影piaohua.com自然大事件HD中英双字1280高清3.rmvb ">ftp://dy44:piaohua@dy44.piaohua.com:2444/飘花电影piaohua.com自然大事件HD中英双字1280高清3.rmvb </a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2444/飘花电影piaohua.com自然大事件HD中英双字1280高清4.rmvb ">ftp://dy44:piaohua@dy44.piaohua.com:2444/飘花电影piaohua.com自然大事件HD中英双字1280高清4.rmvb </a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2444/飘花电影piaohua.com自然大事件HD中英双字1280高清5.rmvb ">ftp://dy44:piaohua@dy44.piaohua.com:2444/飘花电影piaohua.com自然大事件HD中英双字1280高清5.rmvb </a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2444/飘花电影piaohua.com自然大事件HD中英双字1280高清6.rmvb ">ftp://dy44:piaohua@dy44.piaohua.com:2444/飘花电影piaohua.com自然大事件HD中英双字1280高清6.rmvb </a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1C59210-4BP.jpg{/dede:field}
