{dede:field name='keywords'}狗城/狗镇/厄夜变奏曲HD中英双字{/dede:field}
{dede:field name='description'}狗城/狗镇/厄夜变奏曲HD中英双字1024高清迅雷下载、免费下载，狗城/狗镇/厄夜变奏曲HD中英双字1024高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}狗城/狗镇/厄夜变奏曲HD中英双字1024高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-12-07{/dede:field}
{dede:field name='body'}<p>
	【中文译名】《狗城/狗镇/厄夜变奏曲》性感美女尼科尔基德曼经典惊悚大片DVD中英双字幕<br />
	【片　　名】Dogville<br />
	【年　　代】2003<br />
	【国　　家】美国<br />
	【类　　别】剧情/惊悚<br />
	【语　　言】英语<br />
	【字　　幕】中英双字<br />
	【IMDB评分】7.9/10 (35,065 votes)<br />
	【文件格式】XviD + MP3<br />
	【视频尺寸】800 x 452<br />
	【电影整理】3E迅雷电影下载站(www.eee4.com)<br />
	【文件大小】3CD 583MB<br />
	【片　　长】177 min<br />
	【导　　演】拉斯&middot;冯&middot;特里尔 Lars von Trier<br />
	【主　　演】劳伦&middot;巴尔考 Lauren Bacall .... Ma Ginger<br />
	　　　　　　尼科尔&middot;基德曼 Nicole Kidman .... Grace Margaret Mulligan<br />
	　　　　　　约翰&middot;赫特 John Hurt .... Narrator (voice)<br />
	　　　　　　让-马克&middot;巴尔 Jean-Marc Barr .... The Man with the Big Hat<br />
	　　　　　　詹姆斯&middot;凯恩 James Caan .... The Big Man<br />
	　　　　　　杰瑞米&middot;戴维斯 Jeremy Davies .... Bill Henson<br />
	　　　　　　本&middot;吉扎拉 Ben Gazzara .... Jack McKay<br />
	　　　　　　飞利浦&middot;贝克&middot;霍尔 Philip Baker Hall .... Tom Edison Sr.<br />
	　　　　　　尤杜&middot;奇尔 Udo Kier .... The Man in the Coat<br />
	　　　　　　科洛&middot;塞维尼 Chlo? Sevigny .... Liz Henson<br />
	　　　　　　斯特兰&middot;斯卡斯加德 Stellan Skarsg?rd .... Chuck<br />
	　　　　　　布莱尔&middot;布朗 Blair Brown .... Mrs. Henson<br />
	　　　　　　哈里特&middot;安德森 Harriet Andersson .... Gloria<br />
	　　　　　　Ulf Andersson .... Additional Cast<br />
	　　　　　　保罗&middot;贝塔尼 Paul Bettany .... Tom Edison</p>
<p>
	【剧情简介】：</p>
<p>
	30年代经济大萧条时期，美国的洛基山地区。<br />
	　　美丽的女郎格蕾丝为了躲避一伙匪徒的追捕，逃进了一座偏僻的小镇道格维尔(狗镇)。汤姆自封为小镇的代表，在他的劝说下，这个小小的社区同意收留格蕾丝，同时格蕾丝答应为居民们工作以示回报。当匪徒们侵入小镇进行搜寻时，道格维尔的居民开始为他们保护格蕾丝所冒的风险索取更高的酬劳。格蕾丝逐渐意识到在这座镇上，善良其实只是相对的。<br />
	　　但她也隐藏了一个秘密，这个秘密非常危险。道格维尔将为他们的所作所为感到后悔&hellip;&hellip;<br />
	　　影片故事的灵感来源于布莱希特作品《三分钱歌剧》中的一首歌《海盗杰尼》。影片也表达了冯提尔对美国社会的一些看法，尽管他从未踏上美利坚的土地。《狗镇》是他继&ldquo;金心三部曲&rdquo;后推出的&ldquo;美国三部曲&rdquo;的第一部。&ldquo;我这一生一直在对美国社会提出批评，&mdash;&mdash;按照在我的观点中它所呈现的状况。我没有到过那里，但我对美国的理解是基于大量的信息和图像。和那些想拍丹麦，比如拍安徒生的美国人对丹麦的了解相比，要多得多。美国在我的意识中占有的部分，比丹麦在他们头脑中所占有的，大很多。&rdquo; 3E迅雷<a href="/" target="_blank">电影下载</a>站<br />
	　　冯提尔还不失时机地借影片发表了他的政治意见：&ldquo;年轻的时候我是共产主义者，直到现在我仍然觉得自己多少有些属于左翼。所以在某种意义上，影片是对于美国的批评，同时又不是，因为它与今日丹麦政治有着惊人的相似。这甚至与伊拉克战争也有平行关系，尽管这种联系不是有意为之，可我确实对那场战争非常反感。我为丹麦的参与感到耻辱，对这次战争不抱任何同情与尊敬。&rdquo;<br />
	　　电视剧也给影片带来关键性的灵感。冯提尔极其迷恋那种只使用一台摄影机、两个演员和一块灰色背景幕的拍摄方式。他采用这种刻意简化的拍法是为了与当代那些使用昂贵的布景和电影技术的影片加以鲜明区别。&ldquo;我是那么地钦佩像库布里克这样的导演，他可以为了光线合适的镜头在山里等上几个月。当你能够在一分半钟以内用电脑做成同样的事情时，我就不再感动。&rdquo;<br />
	　　冯提尔相信他的这种风格能够强化观众的观影体验：&ldquo;观众变成全身心地投入其中。&rdquo;空空的舞台作为一种装饰性设置，一种众所周知的固定形式，并没有太大意义。他的目的是要让观众聚精会神地完全把兴趣放在人物、演员和故事上。&ldquo;这种技术就像心理放大镜，更贴近人物。&rdquo;当然他对观众能否认同他的这一美学尝试没有太大把握。<br />
	　　虽然这是一次实验，还是引来了不少明星的加盟。从伯格曼的御用女演员哈里特&bull;安德森以及劳伦&bull;芭考尔这样的老一辈，到杰洛米&bull;戴维斯、切洛&bull;塞维妮这样的后起之秀，都不计戏份多寡的参加演出。当然最引人注目的还是妮科&bull;基德曼，她的名字已经为影片的销路提供了最大的保障。3E迅雷<a href="/" target="_blank">电影下载</a>站</p>
<p>
	<img src="http://pic.piaohua.com/0701pic/allimg/080623/0512010.jpg" /></p>
<p>
	【电影截图】：<br />
	电影来源：www.eee4.com<br />
	<img src="http://pic.piaohua.com/0701pic/allimg/080623/0511201.jpg" />&nbsp;<br />
	<img src="http://pic.piaohua.com/0701pic/allimg/080623/0512200.jpg" />&nbsp;<br />
	<img src="http://pic.piaohua.com/0701pic/allimg/080623/0512370.jpg" /></p>


<p>
	性感美女尼科尔基德曼经典惊悚大片《狗镇》DVD中英双字幕 下载地址：<img border="0" src="/templets/img/down.jpg" /><br />
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<anchor></anchor><a href="ftp://eee4.com:8113@vip20.eee4.com:8113/[3E迅雷电影站www.eee4.com]狗镇DVD中英双字幕CD1.rmvb" target="_blank">ftp://eee4.com:8113@vip20.eee4.com:8113/[3E迅雷电影站www.eee4.com]狗镇DVD中英双字幕CD1.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<anchor></anchor><a href="ftp://eee4.com:8113@vip20.eee4.com:8113/[3E迅雷电影站www.eee4.com]狗镇DVD中英双字幕CD2.rmvb" target="_blank">ftp://eee4.com:8113@vip20.eee4.com:8113/[3E迅雷电影站www.eee4.com]狗镇DVD中英双字幕CD2.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<anchor></anchor><a href="ftp://eee4.com:8113@vip20.eee4.com:8113/[3E迅雷电影站www.eee4.com]狗镇DVD中英双字幕CD3.rmvb" target="_blank">ftp://eee4.com:8113@vip20.eee4.com:8113/[3E迅雷电影站www.eee4.com]狗镇DVD中英双字幕CD3.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<anchor></anchor><a href="ftp://dy44:piaohua@dy44.piaohua.com:2282/飘花电影piaohua.com狗镇HD中英双字1024高清.mkv"><u>ftp://dy44:piaohua@dy44.piaohua.com:2282/飘花电影piaohua.com狗镇HD中英双字1024高清.mkv</u></a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O16043S0-15450.jpg{/dede:field}
