<?php
$z[0]=Array("field","绅士大盗/侠盗罗苹BD中英双字102",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","绅士大盗/侠盗罗苹BD中英双字1024/1280高清迅雷下载、免费下载，绅士大盗/侠盗罗苹BD中英双字1024/1280高清Gvod高清在线播放，剧情介绍等。",73,247);
$z[1][4]['name']="description";
$z[2]=Array("field","绅士大盗/侠盗罗苹BD中英双字1024/1280高清",249,327);
$z[2][4]['name']="title";
$z[3]=Array("field","",329,368);
$z[3][4]['name']="writer";
$z[4]=Array("field","",370,409);
$z[4][4]['name']="source";
$z[5]=Array("field","2012-04-15",411,461);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",463,500);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://3e:3e@www2.eee4.com:702/[www.eee4.cn提供]绅士大盗BD中英双字1024x556高清版.rmvb\" target=\"_blank",502,641);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MO39D20-1Oc.jpg",643,724);
$z[8][4]['name']="litpic";

?>