{dede:field name='keywords'}全金属外壳BD中英双字1024/1280{/dede:field}
{dede:field name='description'}全金属外壳BD中英双字1024/1280高清迅雷下载、免费下载，全金属外壳BD中英双字1024/1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}全金属外壳BD中英双字1024/1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-10-08{/dede:field}
{dede:field name='body'}<p>
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://images.dvdempire.com/gen/movies/1356937h.jpg');" src="http://images.dvdempire.com/gen/movies/1356937h.jpg" /><img alt="" src="http://www.bbb119.com/upload/1210531951335344.jpg" /><br />
	<br />
	<br />
	◎译　　名　《全金属外壳》高分大片BD中英双字幕1024分辨率高清收藏版<br />
	◎片　　名　Full Metal Jacket<br />
	◎年　　代　1987<br />
	◎国　　家　英国/美国<br />
	◎类　　别　动作/剧情/惊悚/战争<br />
	◎语　　言　英语<br />
	◎字　　幕　中英双字<br />
	◎IMDB评分 8.3/10 (99,195 votes)<br />
	◎IMDB链接 http://www.imdb.com/title/tt0093058<br />
	◎文件格式　BD-RMVB<br />
	◎视频尺寸　1024 X 576<br />
	◎文件大小　2CD<br />
	◎片　　长　116MiN<br />
	◎导　　演　斯坦利&middot;库布里克 Stanley Kubrick<br />
	◎主　　演　马修&middot;莫迪恩 Matthew Modine .....Private Joker<br />
	　　　　　　亚当&middot;鲍德温 Adam Baldwin .....Animal Mother<br />
	　　　　　　文森特&middot;诺费奥 Vincent D&#39;Onofrio .....Private Gomer Pyle<br />
	　　　　　　R&middot;李&middot;艾尔米 R. Lee Ermey .....Gunnery Sergeant Hartman (as Lee Ermey)<br />
	　　　　　　Dorian Harewood .....Eightball<br />
	　　　　　　Kevyn Major Howard .....Rafterman<br />
	　　　　　　Arliss Howard .....Private Cowboy<br />
	　　　　　　Ed O&#39;Ross .....Lieutenant Touchdown<br />
	　　　　　　John Terry .....Lieutenant Lockhart<br />
	　　　　　　Kieron Jecchinis .....Crazy Earl<br />
	　　　　　　Kirk Taylor .....Payback<br />
	　　　　　　Tim Colceri .....Doorgunner<br />
	　　　　　　Jon Stafford .....Doc Jay (as John Stafford)<br />
	　　　　　　Bruce Boa .....Poge Colonel<br />
	　　　　　　Ian Tyler .....Lieutenant Cleves<br />
	　　　　　　Sal Lopez .....T.H.E. Rock<br />
	　　　　　　Gary Landon Mills .....Donlon<br />
	　　　　　　Papillon Soo .....Da Nang Hooker (as Papillon Soo Soo)<br />
	　　　　　　Peter Edmund .....Snowball<br />
	　　　　　　Ngoc Le .....Vietcong Sniper<br />
	<br />
	◎简　　介　<br />
	<br />
	　　继《越战猎鹿人》、《现代启示录》、《前进高棉》之后的又一描写越战的杰作，它通过新兵训练的过程刻画了非理性的杀人狂热如何残酷摧残人的心灵，是一部内容和技巧俱佳的战争片。影片分两部分，上部分描写一群原来生龙活虎的新兵，在一名魔鬼黑人班长的引导下，训练成了一群嗜杀的机器人，观众一直能感觉到战斗逼近的紧张和刺激；后部分描写男主角（马修．莫迪恩饰）作为战地记者赴战场采访巷战经历，越南女孩在危楼中伏击美军是该片的高潮和经典镜头。此片曾获奥斯卡金像奖最佳改编剧本奖。<br />
	<br />
	　　越战期间，加入海军陆战队的一群年轻人被剃了光头，并分配寝位，负责训练他们的上校时常羞辱他们，还给他们取难听的外号，&ldquo;傻瓜比尔&quot;由于是胖子，动作老是出错，因此成为最经常被上校修理的人。班长&ldquo;小丑&quot;耐心照顾他。但傻瓜比尔再次的失误，令上校愤怒地惩罚全队，伙伴们终于忍无可忍，将傻瓜比尔痛揍了一顿。之后，傻瓜比尔开始对枪自言自语，他发挥了射击的才华，连上校也赞赏他终于可以成为伟大的&ldquo;杀人机器&quot;，就在出发前往越战战场的那晚，傻瓜比尔在他的M14装满&ldquo;全金属外壳子弹&quot;，一枪打死上校，然后自己也含枪自杀。<br />
	<br />
	　　选择编入新闻组的小丑，被长官派去前线采访，小丑看见年轻的士兵们已经麻木，在越共尸体旁饮酒、一面笑一面在直升机上扫射逃走的村民。他随众巡视，误入未扫荡的地区，大家遭到狙击手埋伏，牺牲了好几位同伴后，他们终于确定狙击手藏身的建筑物，小丑落单时忽然发现狙击手，对方原来是个非常年轻的少女！随他而来的摄影员开枪救了他，少女在地上痛苦的挣扎，一名士<br />
	<br />
	幕后/花絮<br />
	&middot;安东尼&middot;麦克尔&middot;豪原本定下出演士兵乔克，由于反对斯坦利&middot;库布里克追求完美主义的导演风格，他被解雇了，取而代之的是马修&middot;摩戴。<br />
	<br />
	&middot;前美国海军军事训练教官R.李&middot;厄梅被聘为顾问，指导如何以美国海军陆战队的方式训练。他在录像带中示范例子，在15分钟里用淫秽和侮辱性的词语骂人，没有停顿和重复，更没有一丝胆怯之意。导演斯坦利&middot;库布里克也被他打动，于是决定让厄梅来演炮兵教官哈特曼。<br />
	<br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://i3.6.cn/cvbnm/b1/37/24/313efbd095301237475f7facd4a4660a.jpg');" src="http://i3.6.cn/cvbnm/b1/37/24/313efbd095301237475f7facd4a4660a.jpg" />&nbsp;<br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://i3.6.cn/cvbnm/d1/f2/51/bf5170603e0c96a06f2812f69cd71647.jpg');" src="http://i3.6.cn/cvbnm/d1/f2/51/bf5170603e0c96a06f2812f69cd71647.jpg" /></p>
<p>
	高分大片《全金属外壳》BD中英双字幕1024分辨率收藏版</p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<anchor></anchor><a href="ftp://e63:e63@xl2.eee4.com:1003/[3E电影站www.eee4.com]全金属外壳[DVD中英双字1024x576高清版]CD1.rmvb" target="_blank">ftp://e63:e63@xl2.eee4.com:1003/[3E电影站www.eee4.com]全金属外壳[DVD中英双字1024x576高清版]CD1.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<anchor></anchor><a href="ftp://e63:e63@xl2.eee4.com:1003/[3E电影站www.eee4.com]全金属外壳[DVD中英双字1024x576高清版]CD2.rmvb" target="_blank">ftp://e63:e63@xl2.eee4.com:1003/[3E电影站www.eee4.com]全金属外壳[DVD中英双字1024x576高清版]CD2.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<anchor></anchor><a href="ftp://dy44:piaohua@dy44.piaohua.com:1765/飘花电影piaohua.com全金属外壳BD中英双字1280高清.rmvb"><u>ftp://dy44:piaohua@dy44.piaohua.com:1765/飘花电影piaohua.com全金属外壳BD中英双字1280高清.rmvb</u></a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O16254030-4a59.jpg{/dede:field}
