{dede:field name='keywords'}天龙八部之天山童姥HD高清1024*5{/dede:field}
{dede:field name='description'}天龙八部之天山童姥HD高清1024*576迅雷下载、免费下载，天龙八部之天山童姥HD高清1024*576Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}天龙八部之天山童姥HD高清1024*576{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-09-18{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img165.poco.cn/mypoco/myphoto/20110918/07/62564813201109180758533228556539228_000.jpg" /></p>
<p>
	电影年代较久，画质一般，不喜勿下</p>
<p>
	◎译　　名　 The Dragon Chronicles the Maidens of Heavenly Mountains<br />
	◎片　　名　 天龙八部之天山童姥<br />
	◎年　　代　 1994<br />
	◎国　　家　 香港/中国<br />
	◎类　　别　 武侠　<br />
	◎IMDB评分 5.7/10<br />
	◎IMDB链接 <a href="http://www.imdb.com/title/tt0111776/">http://www.imdb.com/title/tt0111776/</a><br />
	◎发行公司　 永盛电影制作有限公司 [香港]<br />
	　　　　　　 上海电影制片厂 [中国]<br />
	◎文件格式　 x264+AC3<br />
	◎视频尺寸　 1024 x 576<br />
	◎文件大小　 1.13G<br />
	◎片　　长　 01:36:43<br />
	◎导　　演　 钱永强 Andy Wing-Keung Chin....as Wing Keung Chien<br />
	◎编　　剧　 张炭 Cheung Tan<br />
	◎主　　演　 林青霞 Brigitte Lin....Li Chou-Shui/Li Chong-Hoi<br />
	　　　　　　 张敏 Sharla Cheung....Purple<br />
	　　　　　　 林文龙 Frankie Lam....Hui-Chok<br />
	　　　　　　 白石千 James Pax....Tai Hung<br />
	◎简　　介<br />
	相传武林中，武功最高为天棒山派。天山派常门人逍遥子不幸被逆徒星宿老仙丁春秋陷害所伤，避居飘渺峰，设下 玲珑棋局 等待有缘之士前来破棋，传予百年功力，替他清理门户。虚竹本性善良，佛性极深，终是有缘人，破解棋局，得逍遥子真传，武功俱增，后与丁春秋大战数回合，遂将其消灭。<br />
	◎幕　　后<br />
	《天龙启八部》的故事都改了个乱七八糟，也没有什么复杂的人性主题。林青霞已经被类似的角色搞得乌烟瘴气，如今又出来个巩俐，一样的银幕作风，差不多的表演风格，实在是令人倒足胃口。还有本来丑怪小和尚虚竹，最后竟然也成了武功高强的美少年，复杂的心理矛盾也简化为一个纯粹的 傻人有傻福 的市民故事。《天龙八部》，标志着新武侠电影的低谷，直到电脑特技更大幅度的加入，漫画新武侠才得以把新武侠电影重新推到一个高潮。这部电影可以说只重武不重侠，只重视觉效果不重故事主题，所以这个电影注定成不了经典。<br />
	<img alt="" src="http://img165.poco.cn/mypoco/myphoto/20110918/07/62564813201109180758533228556539228_001.jpg" /></p>
[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
<tbody>
<tr>
<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
<a href="
ftp://dy125:piaohua@dy125.piaohua.com:4037/飘花电影piaohua.com天龙八部之天山童姥HD高清1024分辨率.rmvb">
ftp://dy125:piaohua@dy125.piaohua.com:4037/飘花电影piaohua.com天龙八部之天山童姥HD高清1024分辨率.rmvb </a></td>
</tr>
</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1C1030-42X1.jpg{/dede:field}
