<?php
$z[0]=Array("field","义盖云天[BD国语+粤语中字1024x5",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","义盖云天[BD国语+粤语中字1024x576高清版]迅雷下载、免费下载，义盖云天[BD国语+粤语中字1024x576高清版]Gvod高清在线播放，剧情介绍等。",73,245);
$z[1][4]['name']="description";
$z[2]=Array("field","义盖云天[BD国语+粤语中字1024x576高清版]",247,324);
$z[2][4]['name']="title";
$z[3]=Array("field","",326,365);
$z[3][4]['name']="writer";
$z[4]=Array("field","",367,406);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-04-05",408,458);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",460,497);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://3e:3e@d6.3edyy.com:633/【3E看看www.3ekk.com】义盖云天.1024x560.国粤双语.中文字幕.mkv\" target=_blank>ftftp://3e:3e@d6.3edyy.com:633/【3E看看www.3ekk.com】义盖云天.1024x560.国粤双语.中文字幕.mkv</A></TD></TR></TBODY></TABLE></div><ul class=\"mmlist",499,789);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MQ2360F-54012.jpg",791,874);
$z[8][4]['name']="litpic";

?>