<?php
$z[0]=Array("field","毋亡我[DVD国语+粤语中字]迅雷下",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","毋亡我[DVD国语+粤语中字]迅雷下载、免费下载，毋亡我[DVD国语+粤语中字]Gvod高清在线播放，剧情介绍等。",73,215);
$z[1][4]['name']="description";
$z[2]=Array("field","毋亡我[DVD国语+粤语中字]",217,279);
$z[2][4]['name']="title";
$z[3]=Array("field","",281,320);
$z[3][4]['name']="writer";
$z[4]=Array("field","",322,361);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-11-22",363,413);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",415,452);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://5e:5e@m3.3edyy.com:505/【3E看看www.3ekk.com】毋亡我DVD粤语中字.rmvb\" target=_blank>ftftp://5e:5e@m3.3edyy.com:505/【3E看看www.3ekk.com】毋亡我DVD粤语中字.rmvb</A></TD></TR></TBODY></TABLE><BR><FONT color=#ff0000 size=2><STRONG>尔冬升监制2010年中国香港最新悬疑惊悚片《毋亡我》DVD<FONT color=#0909f7>国语</FONT>中字 [下载地址]：<IMG border=0 src=\"httftp://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg",454,912);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MP339E0-493K.jpg",914,996);
$z[8][4]['name']="litpic";

?>