<?php
$z[0]=Array("field","阴宅瓦德马尔/埃伦西亚·瓦尔德",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","阴宅瓦德马尔/埃伦西亚·瓦尔德马尔/瓦德马尔遗产案BD中英双字12迅雷下载、免费下载，阴宅瓦德马尔/埃伦西亚·瓦尔德马尔/瓦德马尔遗产案BD中英双字12Gvod高清在线播放，剧情介绍等。",72,286);
$z[1][4]['name']="description";
$z[2]=Array("field","阴宅瓦德马尔/埃伦西亚·瓦尔德马尔/瓦德马尔遗产案BD中英双字12",288,386);
$z[2][4]['name']="title";
$z[3]=Array("field","",388,427);
$z[3][4]['name']="writer";
$z[4]=Array("field","",429,468);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-12-20",470,520);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",522,559);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://4e:4e@m1.eee4.cc:1512/【3E电影院www.eee4.cc】阴宅瓦德马尔[DVD中英双字].rmvb\" target=\"_blank",561,697);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MPMLZ-11045.jpg",699,780);
$z[8][4]['name']="litpic";

?>