{dede:field name='keywords'}马尔亚之战BD1280高清迅雷下载，{/dede:field}
{dede:field name='description'}马尔亚之战BD1280高清迅雷下载、免费下载，马尔亚之战BD1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}马尔亚之战BD1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-10{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://boo.digitalchumps.com/images/stories/jreviews/_marjah1_1314594461.jpg" style="width: 700px; height: 887px" /></p>
<p>
	◎英 文 &nbsp;名　The Battle for Marjah<br />
	◎中 文 &nbsp;名　马尔亚之战 / HBO：马尔亚之战<br />
	◎导　　演　Anthony Wonke<br />
	◎年　　代　2010<br />
	◎国　　家　美国<br />
	◎语　　言　英语<br />
	◎IMDb评分 &nbsp;7.8/10 &nbsp;(103 users)<br />
	◎IMDb链接 &nbsp;<a class="faqlink" href="http://www.xiaozhizhu.net/">http://www.xiaozhizhu.net/</a><br />
	◎上映日期 &nbsp; 2011-2-17<br />
	◎片　　长　87 mins<br />
	◎类　　别　纪录片<br />
	◎发行公司 &nbsp; HBO Documentary Films<br />
	<br />
	<br />
	◎剧情简介<br />
	&nbsp;<br />
	&nbsp; &nbsp;纪录片《马尔亚之战》是一个关于美国海军陆战队解放阿富汗主要城市--马尔亚的惊心动魄的故事。<br />
	<br />
	&nbsp; &nbsp;这里是现代文明以外的荒漠，但又无法忽视它，因为这里可能会培养出开飞机去撞摩天大厦的疯子。</p>
<p>
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120508/13/62564813201205081302272062657672388_003.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120508/13/62564813201205081302272062657672388_002.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120508/13/62564813201205081302272062657672388_001.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120508/13/62564813201205081302272062657672388_000.jpg" style="width: 720px; height: 405px" /><br />
	<br />
	&nbsp;</p>
<p>
	【下载地址】</p>
<table bgcolor="#0099cc" border="0" cellpadding="10" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.net/movie/37876.html" target="_blank">http://www.xiaozhizhu.net/movie/37876.html</a></td>
		</tr>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy125:piaohua@dy125.piaohua.com:8036/飘花电影pioahua.com马尔亚之战BD中英双字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:8036/飘花电影pioahua.com马尔亚之战BD中英双字1280高清.rmvb</a></td>
		</tr>
		<tr>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15a54Z-12095.jpg{/dede:field}
