{dede:field name='keywords'}偷袭珍珠港/虎!虎!虎![BD中字102{/dede:field}
{dede:field name='description'}偷袭珍珠港/虎!虎!虎![BD中字1024x576＋1280x720高清版]迅雷下载、免费下载，偷袭珍珠港/虎!虎!虎![BD中字1024x576＋1280x720高清版]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}偷袭珍珠港/虎!虎!虎![BD中字1024x576＋1280x720高清版]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2010-02-11{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://3e:3e@www2.3edyy.com:948/【3E电影院www.3edyy.com】偷袭珍珠港BD中字1280x720高清版.rmvb" target=_blank>ftftp://3e:3e@www2.3edyy.com:948/【3E电影院www.3edyy.com】偷袭珍珠港BD中字1280x720高清版.rmvb</A></TD></TR></TBODY></TABLE><BR><FONT color=#ff0000 size=2><STRONG>[下载地址]：<IMG src="httftp://www.3edyy.com/templets/img/down.jpg" border=0></STRONG></FONT><BR>
<TABLE style="BORDER-RIGHT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; BORDER-BOTTOM: #cccccc 1px dotted" cellSpacing=0 cellPadding=6 width="95%" align=center border=0>
<TBODY>
<TR>
<TD style="WORD-WRAP: break-word" bgColor=#fdfddf><A href="ftftp://3e:3e@www2.3edyy.com:3935/【3E电影院www.3edyy.com】虎！虎！虎！BD中英双字1024x576高清版.rmvb" target=_blank>ftftp://3e:3e@www2.3edyy.com:3935/【3E电影院www.3edyy.com】虎！虎！虎！BD中英双字1024x576高清版.rmvb</A></TD></TR></TBODY></TABLE></div><ul class="mmlist{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MQ3245F-354T.jpg{/dede:field}
