<?php
$z[0]=Array("field","偷袭珍珠港/虎!虎!虎![BD中字102",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","偷袭珍珠港/虎!虎!虎![BD中字1024x576＋1280x720高清版]迅雷下载、免费下载，偷袭珍珠港/虎!虎!虎![BD中字1024x576＋1280x720高清版]Gvod高清在线播放，剧情介绍等。",73,271);
$z[1][4]['name']="description";
$z[2]=Array("field","偷袭珍珠港/虎!虎!虎![BD中字1024x576＋1280x720高清版]",273,363);
$z[2][4]['name']="title";
$z[3]=Array("field","",365,404);
$z[3][4]['name']="writer";
$z[4]=Array("field","",406,445);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-02-11",447,497);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",499,536);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://3e:3e@www2.3edyy.com:948/【3E电影院www.3edyy.com】偷袭珍珠港BD中字1280x720高清版.rmvb\" target=_blank>ftftp://3e:3e@www2.3edyy.com:948/【3E电影院www.3edyy.com】偷袭珍珠港BD中字1280x720高清版.rmvb</A></TD></TR></TBODY></TABLE><BR><FONT color=#ff0000 size=2><STRONG>[下载地址]：<IMG src=\"httftp://www.3edyy.com/templets/img/down.jpg\" border=0></STRONG></FONT><BR>\r\n<TABLE style=\"BORDER-RIGHT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; BORDER-BOTTOM: #cccccc 1px dotted\" cellSpacing=0 cellPadding=6 width=\"95%\" align=center border=0>\r\n<TBODY>\r\n<TR>\r\n<TD style=\"WORD-WRAP: break-word\" bgColor=#fdfddf><A href=\"ftftp://3e:3e@www2.3edyy.com:3935/【3E电影院www.3edyy.com】虎！虎！虎！BD中英双字1024x576高清版.rmvb\" target=_blank>ftftp://3e:3e@www2.3edyy.com:3935/【3E电影院www.3edyy.com】虎！虎！虎！BD中英双字1024x576高清版.rmvb</A></TD></TR></TBODY></TABLE></div><ul class=\"mmlist",538,1521);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MQ3245F-354T.jpg",1523,1605);
$z[8][4]['name']="litpic";

?>