{dede:field name='keywords'}霓虹肉身BD1280高清迅雷下载，免{/dede:field}
{dede:field name='description'}霓虹肉身BD1280高清迅雷下载、免费下载，霓虹肉身BD1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}霓虹肉身BD1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-14{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120514/00/62564813201205140016571941537677326_000.jpg" style="width: 436px; height: 550px" /></p>
<p>
	◎译　　名　霓虹肉身/ 灯红酒绿<br />
	◎片　　名　Neon Flesh<br />
	◎年　　代　2010<br />
	◎国　　家　西班牙/阿根廷/瑞典 &nbsp; &nbsp;<br />
	◎类　　别　喜剧 &nbsp;<br />
	◎语　　言　西班牙语 &nbsp;<br />
	◎IMDB评分 &nbsp;5.2/10 (311 votes)<br />
	◎IMDB链接 &nbsp;<a href="http://www.xiaozhizhu.net/" target="_blank" title="最新电影">http://www.xiaozhizhu.net/</a><br />
	◎片　　长　1h:38m:11s<br />
	◎导　　演　Paco Cabezas<br />
	◎主　　演　安吉拉&middot;摩琳娜 Angela Molina &nbsp;....Pura<br />
	　　　　　　Macarena Gomez &nbsp;....La Canija / Marga<br />
	　　　　　　Vicente Romero &nbsp;....Angelito<br />
	　　　　　　Carlos Vellido &nbsp;....Director<br />
	　　　　　　马里奥&middot;卡萨斯 Mario Casas &nbsp;....Ricky<br />
	　　　　　　Luciano Caceres &nbsp;....El Nino<br />
	　　　　　　Damaso Conde &nbsp;....La Infantita<br />
	　　　　　　达里奥&middot;葛兰帝内提 Dario Grandinetti<br />
	　　　　　　Charles Tyner &nbsp;....Robidoux<br />
	　　　　　　Matt Clark &nbsp;....Qualen<br />
	　　　　　　布兰卡&middot;苏亚雷兹 Blanca Suarez &nbsp;....Veronica　　　　　<br />
	<br />
	◎简　　介　<br />
	<br />
	　 　影片讲述了主人公为了讨老妈欢心，与自己两个没用的老友开了一家妓院做事业的喜剧故事。<br />
	<br />
	　　 里基Ricky（马里奥&middot;卡萨斯饰）在不到12岁时就混迹街头，生活上与妓女、皮条客和瘾君子们打成一片，并且与其保持着密切的关系。现在，为了讨刚刚出狱的老妈普拉Pura（安赫拉&middot;莫利纳饰）欢心，23岁的里基与自己两个没用的老友开了一家名为&ldquo;广岛俱乐部&rdquo;的妓院作为一份礼物让老妈把持。然而，这个快乐的想法是不那么容易实现的......<br />
	<br />
	　　 NEON FLESH 是一部高度犯罪惊悚片，具有独特风格及野性幽默。全片围绕Ricky和他所生活的地下世界展开。Pura，他的母亲，是个妓女，在他12岁就抛弃了他。如今，Ricky长大成人，他想在母亲出狱时开一家妓院孝敬她。他找了他的瘾君子女友帮他拉皮条，还招募了一个相信自己是皇家成员的变性人。但是当Ricky从医院把母亲接回来时，发现母亲已经对自己送的礼物非常腻味了，这让他非常失落。更糟的是，他妓院选址侵犯了无情的暴徒El Chino的领域。</p>
<p>
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120514/00/62564813201205140015491880916421436_003.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120514/00/62564813201205140015491880916421436_002.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120514/00/62564813201205140015491880916421436_001.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120514/00/62564813201205140015491880916421436_000.jpg" style="width: 720px; height: 405px" /><br />
	&nbsp;</p>
<p>
	【下载地址】</p>
<table bgcolor="#0099cc" border="0" cellpadding="10" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.net/movie/20543.html" target="_blank">http://www.xiaozhizhu.net/movie/20543.html</a></td>
		</tr>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy125:piaohua@dy125.piaohua.com:8065/飘花电影piaohua.com霓虹肉身BD中英双字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:8065/飘花电影piaohua.com霓虹肉身BD中英双字1280高清.rmvb</a></td>
		</tr>
		<tr>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1491W10-1SV.jpg{/dede:field}
