<?php
$z[0]=Array("field","洗黑钱DVD国语中字720P双语甄子",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","洗黑钱DVD国语中字720P双语甄子丹经典动作/高清迅雷下载、免费下载，洗黑钱DVD国语中字720P双语甄子丹经典动作/高清Gvod高清在线播放，剧情介绍等。",72,254);
$z[1][4]['name']="description";
$z[2]=Array("field","洗黑钱DVD国语中字720P双语甄子丹经典动作/高清",256,338);
$z[2][4]['name']="title";
$z[3]=Array("field","",340,379);
$z[3][4]['name']="writer";
$z[4]=Array("field","",381,420);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-07-28",422,472);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",474,511);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://e10:e10@xl2.eee4.com:9306/[3E电影站www.eee4.com]洗黑钱DVD国语中字.rmvb\" target=\"_blank",513,644);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MQ24420-2S10.jpg",646,728);
$z[8][4]['name']="litpic";

?>