{dede:field name='keywords'}安静的前哨DVD俄语中字2011最新{/dede:field}
{dede:field name='description'}安静的前哨DVD俄语中字2011最新战争大片迅雷下载、免费下载，安静的前哨DVD俄语中字2011最新战争大片Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}安静的前哨DVD俄语中字2011最新战争大片{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-08-31{/dede:field}
{dede:field name='body'}<p>
	<img border="0" src="http://am.img1001.com/uu_1108_6/kkf178_130_10_67aecff003a759c.jpg" style="max-width: 750px; max-height: 750px" /></p>
<p>
	【原名】: Тихая застава<br />
	【片长】: 90 分鐘<br />
	【制片国家/地区】: 俄羅斯<br />
	【编剧】: Сергей Маховиков<br />
	【导演】: Sergei Makhovikov<br />
	【简体中文名】: 安靜的前哨<br />
	【上映日期】: 2011-1-20(俄羅斯)<br />
	【又名】: Tikhaya zastava<br />
	【类型】: 剧情, 战争<br />
	【语言】: 俄語<br />
	【主演】: Андрей Чадов / Сергей Селин / Игорь Саво<br />
	【剧情】<br />
	　　 战斗在莫斯科边境的塔吉克斯坦共和国边防支队12日发生，1993年7月13日。阿富汗和塔吉克武装分子试图闯入这个国家的领土。 　<br />
	&nbsp;&nbsp; 　&nbsp; 俄罗斯军方11:00反应敌人的攻击，25人死亡的惨烈战斗之后，他们仅剩几名士兵。<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 情况万分危急........<br />
	【影片截图】<br />
	<img border="0" src="http://am.img1001.com/uu_1108_6/kkf178_130_10_fee1accf47f8bd0.jpg" style="max-width: 750px; max-height: 750px" /></p>
<p>
	<img border="0" src="http://am.img1001.com/uu_1108_6/kkf178_130_10_d6d2b5fa7a6355e.jpg" style="max-width: 750px; max-height: 750px" /></p>
<p>
	<img border="0" src="http://am.img1001.com/uu_1108_6/kkf178_130_10_193d9a3b52fa846.jpg" style="max-width: 750px; max-height: 750px" /></p>
<p>
	[下载地址]： &nbsp;<img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<anchor></anchor><a href="ftp://dy44:piaohua@dy44.piaohua.com:1453/飘花电影piaohua.com安静的前哨DVD俄语中字.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:1453/飘花电影piaohua.com安静的前哨DVD俄语中字.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O162212P-1H22.jpg{/dede:field}
