{dede:field name='keywords'}天地大冲撞/彗星撞地球/末日救未{/dede:field}
{dede:field name='description'}天地大冲撞/彗星撞地球/末日救未来[BD中英双字1024x576＋1280x720高清版]迅雷下载、免费下载，天地大冲撞/彗星撞地球/末日救未来[BD中英双字1024x576＋1280x720高清版]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}天地大冲撞/彗星撞地球/末日救未来[BD中英双字1024x576＋1280x720高清版]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2009-09-15{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://3e:3e@xl.eee4.com:210/[www.eee4.cn提供]天地大冲撞BD中英双字1280x720高清版.rmvb" target="_blank{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MPWI40-35A6.jpg{/dede:field}
