{dede:field name='keywords'}布列斯特要塞BD1280高清迅雷下载{/dede:field}
{dede:field name='description'}布列斯特要塞BD1280高清迅雷下载、免费下载，布列斯特要塞BD1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}布列斯特要塞BD1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-02-02{/dede:field}
{dede:field name='body'}<p>
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://photo4.zxip.com/albums4/folder18/14184/20110102135517/2011112142817406.jpg');" src="http://photo4.zxip.com/albums4/folder18/14184/20110102135517/2011112142817406.jpg" /><br />
	<br />
	◎译　　名　布列斯特要塞<br />
	◎片　　名　Brestskaya Krepost<br />
	◎年　　代　2010<br />
	◎国　　家　白俄罗斯/俄罗斯<br />
	◎类　　别　剧情/战争<br />
	◎语　　言　俄语<br />
	◎字　　幕　中文<br />
	◎IMDB评分 8.2/10&nbsp; (836 votes)<br />
	◎文件格式　BD-RMVB<br />
	◎视频尺寸　1024 x 576<br />
	◎文件大小　1CD<br />
	◎片　　长　02:18:15<br />
	◎导　　演　亚历山大&middot;科特 Alexander Kott<br />
	◎主　　演　安德烈&middot;马斯连基 Andrei Merzlikin&nbsp; ....Lieutenant Kizhevatov<br />
	　　　　　　Evgeniy Tsyganov&nbsp; ....Lieutenant Pochernikov<br />
	　　　　　　Pavel Derevyanko&nbsp; ....Yefim Fomin<br />
	　　　　　　Aleksandr Korshunov&nbsp; ....Petr Gavrilov<br />
	　　　　　　Yuri Anpilogov&nbsp; ....Koftun<br />
	　　　　　　Benik Arakelyan<br />
	　　　　　　Viktor Bogushevich<br />
	　　　　　　Kirill Boltayev&nbsp; ....Lieutenant Vinogradov<br />
	　　　　　　Yokhan Bott<br />
	　　　　　　Igor Denisov<br />
	　　　　　　Aleksey Dmitriyev<br />
	　　　　　　Madlen Dzhabrailova<br />
	　　　　　　Nodari Dzhanelidze<br />
	　　　　　　Pavel Gorodnitskiy<br />
	　　　　　　Renat Ibragimov<br />
	　　　　　　Valeri Ivakov<br />
	　　　　　　Igor Ivanov<br />
	　　　　　　Evgenie Ivkovich<br />
	　　　　　　Tatyana Kamina<br />
	　　　　　　Vladimir Kapustin<br />
	　　　　　　Aleksei Kopashov<br />
	　　　　　　Maksim Kostromykin<br />
	　　　　　　Anatoly Kot<br />
	　　　　　　Maksim Krechetov<br />
	　　　　　　Dmitri Kulichkov<br />
	　　　　　　Aleksandr Kuzmichyov<br />
	　　　　　　Maksim Litovchenko<br />
	　　　　　　Oleg Litvinov<br />
	　　　　　　Oleg Lopukhov<br />
	　　　　　　Ilya Mozgovoi<br />
	　　　　　　Veronika Nikonova<br />
	　　　　　　Kirill<a href="http://www.3edyy.com/" target="_blank">3e</a> Novitskiy<br />
	　　　　　　Mikhail Pavlik<br />
	　　　　　　Yegor Petaobaotrov<br />
	　　　　　　Yuliya Polubinskaya<br />
	　　　　　　Sergei Prokopich<br />
	　　　　　　Nikolai Ryabychin<br />
	　　　　　　Evgeniy Sangadzhiyev<br />
	　　　　　　Aleksandr Saptsov<br />
	　　　　　　Sergei Savenkov<br />
	　　　　　　Andrey Senkin<br />
	　　　　　　Matvey Shkuratov<br />
	　　　　　　Aleksandr Sirin<br />
	　　　　　　Anton Starovoytov<br />
	　　　　　　Viktor Strelchenko<br />
	　　　　　　Sergei Taramayev<br />
	　　　　　　Sergei Tsepov<br />
	　　　　　　Anna Tsukanova<br />
	　　　　　　Igor Vepshkovskiy<br />
	　　　　　　Sergei Vlasov<br />
	　　　　　　Dmitriy Yesenevich<br />
	　　　　　　Yana Yesipovich<br />
	　　　　　　Mikhail Yesman<br />
	　　　　　　Alexanser Korshunov&nbsp; ....Mayor Gavrilov<br />
	<br />
	◎简　　介　<br />
	<br />
	&nbsp; &nbsp; 苏德战争爆发，靠近波兰边境的白俄罗斯小城布列斯特要塞最先遭受德军炮火突袭，但守卫部队于弹丸之地牵制了数十倍于自己的德军兵力。战争进行到第30天，最初打响战斗的布列斯特守备部队仍在坚守，并一直向后方总部发出&ldquo;这里是要塞，正在战斗&rdquo;的讯息。在已经失守的布列斯特要塞的地道里坚持战斗一年多的最后一名苏军战士，被德国人发现时，他被德国人从地穴中押出来刺眼的阳光让他几乎失明。面对德国将军的审问，他的回答是： &ldquo;将军，现在您知道一俄里有多远了吧？&rdquo; （战前德军宣称这个距苏德边境仅一俄里的要塞一个冲锋就能拿下）本片就是取自这场战役中的真实故事改编。<br />
	&nbsp;</p>
<p>
	【电影截图】：<br />
	<br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://photo4.zxip.com/albums4/folder18/14184/20110102135517/20111121428212950.jpg');" src="http://photo4.zxip.com/albums4/folder18/14184/20110102135517/20111121428212950.jpg" /><br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://photo4.zxip.com/albums4/folder18/14184/20110102135517/2011112142822100.jpg');" src="http://photo4.zxip.com/albums4/folder18/14184/20110102135517/2011112142822100.jpg" /></p>
<br />
<p>
	[下载地址]：<img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" /></p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://3e:3e@d3.3edyy.com:121/【3E电影院www.eee4.org】布列斯特要塞BD中字1024x576高清版.rmvb" target="_blank">ftp://3e:3e@d3.3edyy.com:121/【3E电影院www.eee4.org】布列斯特要塞BD中字1024x576高清版.rmvb</a></td>
		</tr>
	</tbody>
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="&#13;&#10;ftp://dy125:piaohua@dy125.piaohua.com:7559/飘花电影piaohua.com布列斯特要塞BD中字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:7559/飘花电影piaohua.com布列斯特要塞BD中字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15153U0-2CO.jpg{/dede:field}
