{dede:field name='keywords'}疯狗强尼BD中英双字1024/1280高{/dede:field}
{dede:field name='description'}疯狗强尼BD中英双字1024/1280高清迅雷下载、免费下载，疯狗强尼BD中英双字1024/1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}疯狗强尼BD中英双字1024/1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-02-05{/dede:field}
{dede:field name='body'}<p>
	<img alt="" border="0" onclick="zoom(this, this.src)" onload="attachimg(this, 'load')" src="http://img.album.pchome.net/54/70/26/33/1a7ae10df9e7c6eb895f83df8bc6757b.jpg" /></p>
<p>
	◎译　　名　《疯狗强尼/非洲战火中的童子军》08法国最新战争剧情片DVD中英双字1280x720高清版<br />
	◎片　　名　Johnny Mad Dog<br />
	◎年　　代　2008<br />
	◎国　　家　法国/比利时/利比里亚<br />
	◎类　　别　剧情/战争<br />
	◎语　　言　法语<br />
	◎字　　幕　中英双字幕<br />
	◎IMDB评分 7.3/10&nbsp; 151 votes<br />
	◎IMDB链接 http://www.imdb.com/title/tt1042424/<br />
	◎文件格式　RMVB<br />
	◎视频尺寸　1280 x 720<br />
	◎文件大小　1.15G<br />
	◎片　　长　98 min 14 sec<br />
	◎导　　演　让-斯蒂芬&middot;萨瓦尔<br />
	◎主　　演　Christophe Minie &hellip;.<a href="http://www.eee4.com/gvod_help.htm" target="_blank">gvod</a>Johnny Mad Dog<br />
	　　　　　　Daisy Victoria Vandy &hellip;.Laokole<br />
	◎简　　介　</p>
<p>
	　　描述非洲某国娃娃兵的残酷人生。他们拿起卡拉什尼科夫冲锋枪如同职业军人，年纪轻轻就杀人如麻，还强奸妇女。本片叙述年仅15岁的叛军首领&ldquo;疯狗强尼&rdquo;当娃娃兵的历程，和13岁少女拉奥科蕾逃离残酷战乱的故事。《疯狗强尼》曾获戛纳电影节&ldquo;一种关注&rdquo;单元最具希望奖。12岁以下不宜。</p>
<p>
	幕后制作</p>
<p>
	　　《疯狗强尼》改编自艾曼纽埃耳&middot;东轧拉的作品，导演让-斯蒂芬&middot;萨瓦尔已经是一位知名的纪录片工作者。</p>

<p>
	【电影截图】：</p>
<p>
	<a href="http://img.album.pchome.net/54/70/24/30/1244460003f3ccdd27d2000e3f9255a7e3e2c48800.jpg" target="_blank"><img src="http://img.album.pchome.net/54/70/24/30/1244460003f3ccdd27d2000e3f9255a7e3e2c48800.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 338px; border-top: 0px solid; border-right: 0px solid" /></a>&nbsp;<br />
	<a href="http://img.album.pchome.net/54/70/24/30/1244460003799bad5a3b514f096e69bbc4a7896cd9.jpg" target="_blank"><img src="http://img.album.pchome.net/54/70/24/30/1244460003799bad5a3b514f096e69bbc4a7896cd9.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 338px; border-top: 0px solid; border-right: 0px solid" /></a>&nbsp;<br />
	<a href="http://img.album.pchome.net/54/70/24/30/1244460003d0096ec6c83575373e3a21d129ff8fef.jpg" target="_blank"><img src="http://img.album.pchome.net/54/70/24/30/1244460003d0096ec6c83575373e3a21d129ff8fef.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 338px; border-top: 0px solid; border-right: 0px solid" /></a></p>
	08法国最新战争剧情片《疯狗强尼》DVD中英双字1280x720高清版 ：<img border="0" src="http://www.eee4.com/templets/img/down.jpg" /></p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://3e:3e@www2.eee4.com:608/[3E电影站www.eee4.com]疯狗强尼DVD中英双字1280x720高清版.rmvb" target="_blank">ftp://3e:3e@www2.eee4.com:608/[3E电影站www.eee4.com]疯狗强尼DVD中英双字1280x720高清版.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				&nbsp;<a href="ftp://dy44:piaohua@dy44.piaohua.com:2748/飘花电影piaohua.com疯狗强尼BD中英双字1024高清.mkv">ftp://dy44:piaohua@dy44.piaohua.com:2748/飘花电影piaohua.com疯狗强尼BD中英双字1024高清.mkv</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O151554P-49637.jpg{/dede:field}
