<?php
$z[0]=Array("field","鱼狗[DVD国语中字无水印]迅雷下",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","鱼狗[DVD国语中字无水印]迅雷下载、免费下载，鱼狗[DVD国语中字无水印]Gvod高清在线播放，剧情介绍等。",72,212);
$z[1][4]['name']="description";
$z[2]=Array("field","鱼狗[DVD国语中字无水印]",214,275);
$z[2][4]['name']="title";
$z[3]=Array("field","",277,316);
$z[3][4]['name']="writer";
$z[4]=Array("field","",318,357);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-11-30",359,409);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",411,448);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://4e:4e@m1.3edyy.com:1567/【3E看看www.3ekk.com】鱼狗[DVD国语中字无水印].rmvb\" target=_blank>ftftp://4e:4e@m1.3edyy.com:1567/【3E看看www.3ekk.com】鱼狗[DVD国语中字无水印].rmvb</A></TD></TR></TBODY></TABLE></div><ul class=\"mmlist",450,720);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MP342W0-1F19.jpg",722,804);
$z[8][4]['name']="litpic";

?>