{dede:field name='keywords'}建筑学概论DVD中字韩国2012爱情{/dede:field}
{dede:field name='description'}建筑学概论DVD中字韩国2012爱情剧情迅雷下载、免费下载，建筑学概论DVD中字韩国2012爱情剧情Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}建筑学概论DVD中字韩国2012爱情剧情{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-17{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="/uploads/allimg/c120525/133O0V60320-1R55.jpg" /></p>
<p>
	◎译　　名　建筑学概论<br />
	◎片　　名　&#44148;&#52629;&#54617;&#44060;&#47200;/An.Introduction.to.Architecture/Architecture 101/Geon-chook-hak-gae-ron/Geonchukhakgaeron<br />
	◎年　　代　2012<br />
	◎国　　家　韩国<br />
	◎类　　别　爱情/剧情<br />
	◎语　　言　韩语<br />
	◎字　　幕　中字<br />
	◎IMDB评分&nbsp; 7.2/10 (9 votes)<br />
	◎文件格式　Xvid + AC3<br />
	◎视频尺寸　850 x 420<br />
	◎文件大小　1.41GB<br />
	◎片　　长　01:56:17<br />
	◎导　　演　李勇周 Young-su Lee<br />
	◎主　　演　韩佳人 Ga-in Han<br />
	　　　　　　严泰雄 Tae-woong Eom<br />
	　　　　　　李济勋 Je-hun Lee<br />
	　　　　　　裴秀智 Suzy<br />
	　　　　　　高俊熙 Jun-hee Go<br />
	　　　　　　刘延锡 Yeon-seok Yoo<br />
	　　　　　　金意成 Eui-sung Kim&nbsp; ....Professor Kang<br />
	　　　　　　Su-young Park&nbsp; ....Director Goo<br />
	　　　　　　Hyeon-cheol Jo&nbsp; ....Dong-goo<br />
	　　　　　　</p>

<p>
	◎简　　介　</p>
<p>
	<br />
	　　《建筑学概论》是讲述了在大学建筑学概论课堂上相识的一对男女在多年后以建筑师和客户的身份重逢而发生的一段爱情故事。 　　同是大学建筑学概论课学生的胜珉（李济勋饰）和舒妍（裴秀智饰）在课堂上相识并互生情愫，不过 这一段感情却因课堂结课而终止。在15年后的某天，已变身为建筑师的胜珉（严泰雄饰）偶遇到一位让他目光停留已久的客户，她正是那个让他难以忘怀的舒妍 （韩佳人饰），二人重拾过往的回忆一边微笑，这份感情是否能跨越时间延续？</p>
<p>
	幕后制作</p>
<p>
	　　曾执导《不信地狱》的李容周导演2012年带着浪漫爱情片《建筑学概论》回到影坛，这部影片单看名字完全和爱情挂不上钩，也完全不像是一部电影的名字，反 而吸引了更多观众注意。<br />
	　　当然最瞩目的还有四位主角，包括一直以各种角色活跃于影坛的严泰雄、8年没有接拍过电影的韩佳人、厉害新人裴秀智和知名度不俗的李济勋。<br />
	　　裴秀智和李济勋分别饰演严泰雄和韩佳人的年轻时期，影片穿梭15年前后见证一对有情人的爱情路。<br />
	　　严泰雄虽然有不少代表作品，但倾向于单纯爱情片的却少之又少，可以数出来的包括曾经火热的圣诞 片《我的爱》，他打造了一个可爱又执着的男子角色，让人感叹严泰雄也有如此温柔的一面，随后的《恋爱操作团》票房也不俗，到2012年1月搭档郑丽媛的 《永无结局的故事》是一部带着悲伤的故事，来到这部和韩佳人的《建筑学概论》才再展现出《我的爱》中纯纯爱情的感觉。<br />
	　　女主角韩佳人则是主要活跃于电视剧领域，电影作品除了2004年的《马粥街残酷史》外并无其他，足足时隔了8年才带着这部新作出现，十分让人期待。在 片中韩佳人展示出柔情的成熟女人韵味，十分符合她的形象。<br />
	　　饰演学生时期的男女主角裴秀智和李济勋也相当瞩目，在宣传的两款海报中，严泰雄和韩佳人明显是已经历沧桑的男女，表情尽显多年重复的复杂感。<br />
	　　裴秀智和李济勋这一对的海报则是浓浓的学生情怀，表情动作均流露着青春气息，两款海报给人的感觉对比相当强烈但都很温馨。<br />
	　　裴秀智是当红女子组合Miss A的成员之一，在2011年她通过大热剧集《Dream high》首次为自己演技磨刀，尽管当时初期表现太紧张但其后发挥越来越有演员风范并深得观众喜爱，这次的《建筑学概论》是她首次挑战电影的作品。<br />
	　　搭档她的李济勋则是个厉害的新人，2011年他在各大电影颁奖上可谓是大获全胜，凭《守望者》摘下了五个电影奖的最佳新人奖，风头无人能及，二人在片 中更有青涩的吻戏。<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 本片的导演是曾经辅佐过奉俊昊名导的李勇周导演，在曾经多指导暴力猛烈类型的电影后，他一改常态，此次导起了怀旧温情的纯爱电影。片名《建筑学概论》也来 自导演的奇思妙想，身为建筑学专业毕业的他惯性的将爱情比喻成建筑，两者同样都是从零到有一点点累积成型。与前段时间中国刮起的《那些年，我们一起追的女 孩》风潮相似，本片亦是探讨初恋的话题，15年前的初恋男女15年后再续情缘，这段长年的旧爱终究焕发新的面貌，再次谱出了新恋曲。韩国电影在打造纯爱类 型方面一直不遗余力，从2001年的《我的野蛮女友》开始，《我脑海中的橡皮擦》、《假如爱有天意》、《悲伤电影》等经典作品再到近几年如《我的爱在我身 边》、《永无结局的故事》&hellip;&hellip;或悲或喜的纯美爱恋片令观众总是一次次深陷。<br />
	　　好的剧本还需要优秀的演员，本次阵容也不容小觑，刚刚结束了国民剧《月亮拥抱太阳》演出的女主角韩佳人时隔8年后再次出演电影，聚集的人气也为本片带 来了不容忽视的力量，最近一直凭借国民综艺《两天一夜》活跃于电视荧屏的严泰雄人气搜索量居高不下，在本片上映的同时由他主演的电视剧《赤道的男人》也正 在热播。除了上述两位人气爆棚的演员外，近日正在发片打榜的偶像组合MissA主唱秀智则饰演了大学时代的女主角。 　　<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 影片最大的新意便是将&ldquo;建筑&rdquo;和&ldquo;爱情&rdquo;联系在一起。本身就是建筑学专业出身的导演李勇周表示，爱情和建筑之间存在很微妙的关联，二者都是从零到有，通过精心设计和搭建才能成就一个&ldquo;家&rdquo;，建筑成就的是住所，爱情成就的则是精神港湾。<br />
	　　就这样，两条鱼在辽阔的太平洋上的冒险使它们交到了形形色色的朋友，也遭遇了各式各样的危机。而鱼爸爸玛林也终于克服万难，与儿子团聚并安全地回到了自己的家乡。过去那个甚至连自己儿子都瞧不起的胆小鬼玛林，经过这次的考验后成为了儿子眼中真正的英雄！一场亲情团聚的大戏，就此在充满泪水的眼睛中落下了帷幕。</p>
<p>
	&nbsp;</p>
<p>
	&nbsp;<img alt="" src="/uploads/allimg/c120525/133O0V612Z-2YG.jpg" /></p>
<p>
	<img alt="" src="/uploads/allimg/c120525/133O0V623F-35232.jpg" /></p>
<p>
	&nbsp;<img alt="" src="/uploads/allimg/c120525/133O0V63420-453W.jpg" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="/uploads/allimg/c120525/133O0T31310-42214.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：http://www.xiaozhizhu.net</td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				&nbsp;ftp://dy44:piaohua@dy44.piaohua.com:3440/飘花电影piaohua.com建筑学概论DVD中字.rmvb</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O0V643Z-55296.jpg{/dede:field}
