<?php
$z[0]=Array("field","圣乔治射龙/圣乔治屠龙[DVD中英",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","圣乔治射龙/圣乔治屠龙[DVD中英双字]迅雷下载、免费下载，圣乔治射龙/圣乔治屠龙[DVD中英双字]Gvod高清在线播放，剧情介绍等。",72,234);
$z[1][4]['name']="description";
$z[2]=Array("field","圣乔治射龙/圣乔治屠龙[DVD中英双字]",236,308);
$z[2][4]['name']="title";
$z[3]=Array("field","",310,349);
$z[3][4]['name']="writer";
$z[4]=Array("field","",351,390);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-05-02",392,442);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",444,481);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://5e:5e@d8.3edyy.com:145/【3E电影院www.eee4.cc】圣乔治射龙DVD中英双字.rmvb\" target=_blank>ftftp://5e:5e@d8.3edyy.com:145/【3E电影院www.eee4.cc】圣乔治射龙DVD中英双字.rmvb</A></TD></TR></TBODY></TABLE></div><ul class=\"mmlist",483,749);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MP615150-1cI.jpg",751,833);
$z[8][4]['name']="litpic";

?>