<?php
$z[0]=Array("field","童眼3D[DVD国语中字]迅雷下载，",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","童眼3D[DVD国语中字]迅雷下载、免费下载，童眼3D[DVD国语中字]Gvod高清在线播放，剧情介绍等。",72,204);
$z[1][4]['name']="description";
$z[2]=Array("field","童眼3D[DVD国语中字]",206,263);
$z[2][4]['name']="title";
$z[3]=Array("field","",265,304);
$z[3][4]['name']="writer";
$z[4]=Array("field","",306,345);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-12-08",347,397);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",399,436);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://4e:4e@m1.3edyy.com:1569/【3E看看www.3ekk.com】童眼3D[DVD国语中字].rmvb\" target=_blank>ftftp://4e:4e@m1.3edyy.com:1569/【3E看看www.3ekk.com】童眼3D[DVD国语中字].rmvb</A></TD></TR></TBODY></TABLE><STRONG><FONT color=#ff0000 size=2><BR>杨丞琳、余文乐、江若琳2010年中国香港最新悬疑惊悚恐怖片《童眼3D》DVD<FONT color=#0909f7>粤语</FONT>中字 [下载地址]：<IMG border=0 src=\"httftp://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg",438,918);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MP34R30-5GZ.jpg",920,1001);
$z[8][4]['name']="litpic";

?>