{dede:field name='keywords'}四月物语迅雷下载，免费下载，Gv{/dede:field}
{dede:field name='description'}四月物语迅雷下载、免费下载，四月物语Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}四月物语{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-13{/dede:field}
{dede:field name='body'}<p>
	&nbsp;<img src="http://img.funshion.com/attachment/images/20080726/7/EC9C932C9FAF7280B1BD4DB8C8E229D9.jpg" /></p>
<p>
	&nbsp;<img src="http://img.funshion.com/attachment/images/20080726/2/2FEF4014BA7A72CCA0A19C4C80F05430.jpg" /></p>
<p>
	<img src="http://img.funshion.com/attachment/images/20080726/5/3CF070E545407D23AD6CABBEE258E0FD.jpg" /></p>
<p>
	<img src="http://img.funshion.com/attachment/images/20080726/2/F0A83681E283688A29A2F1ADE95938CB.jpg" /></p>
<p>
	<img src="http://img.funshion.com/attachment/images/20080726/0/EA755714EC88A986C8E89A94057BBA1E.jpg" /></p>
<p>
	<img src="http://img.funshion.com/attachment/images/20080726/6/4AB88CC08571467D188B7ACA73FBEA67.jpg" /></p>

<p>
	中文名： 四月物语<br />
	外文名： April Story<br />
	其它译名： Shigatsu monogatari<br />
	出品时间： 1998年<br />
	出品公司： Rockwell Eyes Inc.<br />
	制片地区： 日本<br />
	导演： 岩井俊二</p>
<p>
	编剧： 岩井俊二<br />
	主演： 松隆子， 田边诚一， 津田宽治<br />
	类型： 爱情<br />
	片长： 67 min<br />
	上映时间： 1998年3月14日 日本<br />
	对白语言： 日语<br />
	分级： Hong Kong:I</p>
<p>
	&bull;首映：1998年3月14日 日本<br />
	&bull;又名：Shigatsu monogatari</p>
<p>
	&bull;点评： 大雨中的那把歪斜的红伞，跟随步伐而来，带走我的心--</p>
<p>
	&bull;剧情：每年樱花飘飞的四月，是日本大学开学的日子。与父母家人告别后，北海道少女榆野卯月只身来到东京武藏野大学开始了新的生活。陌生的城市、崭新的环境以及新结识的同学和邻居都有点让她不知所措。班里组织新生作自我介绍，当被人问到为何选择武藏野大学时，榆野卯月突然表现得十分紧张。原来高中时代的榆野卯月一直暗恋着比自己大一届的同学山崎，正是由于山崎去年到武藏野大学上学，卯月才追随而来的。卯月经常怀着着份暗恋之情前往山崎打工的武藏野书店，最后她终于在一个雨天与山崎进行了交谈。离开书店后，卯月在雨中突然想到成绩不佳的自己竟然通过努力考到了著名的武藏野大学，这真堪称爱的奇迹。</p>
<p>
	&nbsp;&nbsp;<img src="http://img.funshion.com/attachment/images/20080726/4/7D53CCDC494449FB9B59E9153523ECD8.jpg" /></p>
<p>
	<img src="http://img.funshion.com/attachment/images/20080726/1/AD35880C9DFCFD9521FD83D71A1CDC42.jpg" /></p>
<p>
	&nbsp;<img src="http://img.funshion.com/attachment/images/20080726/6/95E25B93B086E84BF396EE78285F8294.jpg" /></p>
<p>
	&nbsp;<img src="http://img.funshion.com/attachment/images/20080726/3/5F3BAD74B97322DE61F912A290EECB56.jpg" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.net/movie/21387.html" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy125:piaohua@dy125.piaohua.com:8061/飘花电影piaohua.com四月物语HD中字.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:8061/飘花电影piaohua.com四月物语HD中字.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15b50F-55341.jpg{/dede:field}
