{dede:field name='keywords'}夺命双头鲨DVD中字2012动作科幻{/dede:field}
{dede:field name='description'}夺命双头鲨DVD中字2012动作科幻迅雷下载、免费下载，夺命双头鲨DVD中字2012动作科幻Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}夺命双头鲨DVD中字2012动作科幻{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-02-09{/dede:field}
{dede:field name='body'}<p>
	<img alt="" file="http://img2081.poco.cn/mypoco/myphoto/20120208/20/56643687201202082031124220401497275_005.jpg" height="600" src="http://img2081.poco.cn/mypoco/myphoto/20120208/20/56643687201202082031124220401497275_005.jpg" width="427" /></p>

<p>
	◎译　　名　夺命双头鲨<br />
	◎片　　名　2 Headed Shark Attack<br />
	◎年　　代　2012<br />
	◎国　　家　美国<br />
	◎类　　别　动作/科幻/恐怖<br />
	◎语　　言　英语<br />
	◎字　　幕　中文<br />
	◎IMDB评分&nbsp;&nbsp;5.3/10 (17 votes)<br />
	◎文件格式　DVD-RMVB<br />
	◎视频尺寸　680 &times; 384<br />
	◎文件大小　1CD<br />
	◎片　　长　86 mins<br />
	◎导　　演　Christopher Ray<br />
	◎主　　演　Carmen Electra ... Anne Babish<br />
	　　　　　　Charlie O&#39;Connell ... Professor Babish<br />
	　　　　　　Brooke Hogan ... Kate<br />
	　　　　　　Gerald Webb ... Han<br />
	　　　　　　David Gallegos ... Paul<br />
	　　　　　　Geoff Ward ... Cole<br />
	　　　　　　Mercedes Young ... Lyza (as Mercedes C. Young)<br />
	　　　　　　Shannan Stewart ... Lyndsey<br />
	　　　　　　Tihirah Taliaferro ... Michelle<br />
	　　　　　　Michael Dicarluccio ... Ethan<br />
	　　　　　　Lauren Vera ... Jamie<br />
	　　　　　　Marckenson Charles ... Ryan<br />
	　　　　　　Ashley Bissing ... Kristen (as Ashley F. Bissing)<br />
	　　　　　　Corinne Nobili ... Kirsten<br />
	　　　　　　Benjamin James ... Alex<br />
	<br />
	<br />
	<br />
	◎简　　介<br />
	<br />
	一艘在海上航行的船只，被一种变异的双头鲨鱼袭击。幸存者游到了一座荒岛上寻求庇护，但是噩梦远没有结束......<br />
	<br />
	<br />
	◎影片截图<br />
	<br />
	<img alt="" file="http://img2081.poco.cn/mypoco/myphoto/20120208/20/56643687201202082031124220401497275_000.jpg" height="340" lazyloaded="true" src="http://img2081.poco.cn/mypoco/myphoto/20120208/20/56643687201202082031124220401497275_000.jpg" style="cursor: pointer" width="600" /><br />
	<br />
	<img alt="" file="http://img2081.poco.cn/mypoco/myphoto/20120208/20/56643687201202082031124220401497275_003.jpg" height="340" lazyloaded="true" src="http://img2081.poco.cn/mypoco/myphoto/20120208/20/56643687201202082031124220401497275_003.jpg" style="cursor: pointer" width="600" /><br />
	<br />
	<img alt="" file="http://img2081.poco.cn/mypoco/myphoto/20120208/20/56643687201202082031124220401497275_004.jpg" height="340" lazyloaded="true" src="http://img2081.poco.cn/mypoco/myphoto/20120208/20/56643687201202082031124220401497275_004.jpg" style="cursor: pointer" width="600" /><br />
	<br />
	<img alt="" file="http://img2081.poco.cn/mypoco/myphoto/20120208/20/56643687201202082031124220401497275_001.jpg" height="340" lazyloaded="true" src="http://img2081.poco.cn/mypoco/myphoto/20120208/20/56643687201202082031124220401497275_001.jpg" style="cursor: pointer" width="600" /><br />
	[下载地址]：&nbsp;&nbsp;
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2779/飘花电影piaohua.com夺命双头鲨DVD中字.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:2779/飘花电影piaohua.com夺命双头鲨DVD中字.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2779/飘花电影piaohua.com夺命双头鲨DVD中字.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1591L10-1CB.jpg{/dede:field}
