<?php
$z[0]=Array("field","高海拔之恋2HD国语中字郑秀文,古",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","高海拔之恋2HD国语中字郑秀文 古天乐2012最新爱情迅雷下载、免费下载，高海拔之恋2HD国语中字郑秀文 古天乐2012最新爱情Gvod高清在线播放，剧情介绍等。",73,259);
$z[1][4]['name']="description";
$z[2]=Array("field","高海拔之恋2HD国语中字郑秀文 古天乐2012最新爱情",261,345);
$z[2][4]['name']="title";
$z[3]=Array("field","",347,386);
$z[3][4]['name']="writer";
$z[4]=Array("field","",388,427);
$z[4][4]['name']="source";
$z[5]=Array("field","2012-02-10",429,479);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",481,518);
$z[6][4]['name']="body";
$z[7]=Array("field","",520,559);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MOT1J0-5IL.jpg",561,641);
$z[8][4]['name']="litpic";

?>