{dede:field name='keywords'}悭钱家族HD1280高清迅雷下载，免{/dede:field}
{dede:field name='description'}悭钱家族HD1280高清迅雷下载、免费下载，悭钱家族HD1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}悭钱家族HD1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-18{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://218.26.89.158/up/files/77/20096121403781.jpg" style="width: 480px; height: 720px" /></p>
<p>
	◎译　　名　悭钱家族<br />
	◎片　　名　Frugal Game<br />
	◎年　　代　2002<br />
	◎国　　家　香港<br />
	◎类　　别　喜剧<br />
	◎语　　言　普通话<br />
	◎字　　幕　中文<br />
	◎IMDB评分 6.0/10(39votes)<br />
	◎IMDB链接 <a href="http://www.imdb.com/title/tt0368770" target="_blank">http://www.imdb.com/title/tt0368770</a><br />
	◎文件格式　MPEG2 + AC3<br />
	◎视频尺寸　1280x720<br />
	◎文件大小　0.99G<br />
	◎片　　长　101mins<br />
	◎导　　演　赵崇基 Sung Kee Chiu<br />
	◎主　　演　陈奕迅 Eason Chan .....Siu Hap (The Game Show Host)<br />
	　　　　　　郑裕玲 Carol Cheng .....Diana<br />
	　　　　　　杨千嬅 Miriam Yeung .....Wai Chin-Wah<br />
	　　　　　　曾志伟 Eric Tsang .....Wai Tai Hon<br />
	　　　　　　黎耀祥 Yiu-Cheung Lai .....Mr. Lai<br />
	　　　　　　胡樱汶 Ying Man Woo<br />
	　　　　　　何超仪 Josie Ho .....Mrs. Lai<br />
	　　　　　　狄龙 Lung Ti .....Himself<br />
	<br />
	◎简　　介　<br />
	<br />
	Diana希望有自己骄人的事业，更一直憧憬著有一个爱自己又有钱的好男人。社会经济自金融风暴后持续低迷，大小公司裁员「瘦身」，Diana 和酒店经理韦大汉亦不幸成为失业大军。电视台编导徐少侠、韦大汉以及其女儿千嬅期为了冲出困境，决定假扮夫妻参加比赛。「冒牌家族」一行四人到达电视台，悭钱生活开始。参赛家庭住进了电视台特别设计的「悭钱屋」，屋内设备齐全，可是每一个项目都要收费。七天的时限，各人出尽所有悭钱的技俩，到处试食医肚、到化妆品柜台化妆、到公众浴室洗澡。受尽折腾之下，有人偷偷花钱、有人爱子心切甘愿牺牲、有人年幼无知、有人紧守游戏规则，人性尽现。在游戏中，Diana 认识了韦大汉的另一面；徐少侠与千嬅从识英 雄重英雄进一步有所发展，可是事情却被节目监制利用，最后韦家排除万难，成为「悭钱家族」游戏的优胜家庭，不过司仪却宣布要耻夺他们的参赛资格&hellip;&hellip;<br />
	&nbsp;<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120503/18/62564813201205031848411506962200552_002.jpg" style="width: 650px; height: 366px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120503/18/62564813201205031848411506962200552_001.jpg" style="width: 650px; height: 366px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120503/18/62564813201205031848411506962200552_000.jpg" style="width: 650px; height: 366px" /></p>
<p>
	【下载地址】</p>
<table bgcolor="#0099cc" border="0" cellpadding="10" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.net" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy125:piaohua@dy125.piaohua.com:8011/飘花电影piaohua悭钱家族HD国语中字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:8011/飘花电影piaohua悭钱家族HD国语中字1280高清.rmvb</a></td>
		</tr>
		<tr>
		</tr>
	</tbody>
</table>
<br />{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O14924530-4G14.jpg{/dede:field}
