{dede:field name='keywords'}BBC,摧毁泰坦尼克号的冰山杀手迅{/dede:field}
{dede:field name='description'}BBC 摧毁泰坦尼克号的冰山杀手迅雷下载、免费下载，BBC 摧毁泰坦尼克号的冰山杀手Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}BBC 摧毁泰坦尼克号的冰山杀手{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2008-01-07{/dede:field}
{dede:field name='body'}<P>【译　　名】BBC 摧毁泰坦尼克号的冰山杀手<BR>【类　　型】科幻/记录<BR>【片　　长】50分钟<BR>【上　　映】2008年<BR>【国　　家】英国<BR>【语　　言】英语<BR>【字　　幕】中文<BR>【视频尺寸】640x352<BR>【来&nbsp;&nbsp;&nbsp; 源】3E迅雷电影站(www.eee4.com)<BR>【大　&nbsp; 小】1CD/179M</P>
<P>【内容简介】：</P>
<P>　　随着美国好莱坞大片"泰坦尼克号"的一炮走红,冰封多年世纪沉船悲剧重新进入人们的视野."泰坦尼克号"是本世纪初人类工业文明的大成之作,在其风光无限的处女航行时,不幸撞上了冰山,最后带着1500多遇难者沉入酷寒的北大西洋.本片正是向您介绍摧毁泰坦尼克号的杀手,最隐秘而恐怖的轮船客星--大冰山.冰山到底是怎么形成的,它们拥有怎样独特的物理特征外形特点,不可思议的海洋行程,以及最后什么样的结局,冰山如何远行几千公里与航行中"泰坦尼克号"在极其微小的概率下相撞,冰山到底拥有何等威力可以把好称"用不沉没"的钢铁巨船送进海底?相信本片将给您还原"泰坦尼克号"与冰山的世纪一撞的历史真相。电影来源：www.eee4.com</P>
<P>泰坦尼克号小资料(英文RMS Titanic). 电影来源：www.eee4.com</P>
<P>　　20世纪初英国制造的一艘在当时世界最大的豪华客轮，在当时被称为是“永不沉没的”，但却在1912年4月15日从南安普顿至纽约的处女航中，在北大西洋撞上冰山而沉没，由于缺少足够的救生艇，1500人葬生海底，造成了当时在和平时期最严重的一次航海事故，也是迄今为止最著名的一次。美国电影《泰坦尼克》就是根据这一真实的故事拍摄的。“泰坦尼克号”共耗资7500万英镑，吨位46328吨，长882.9英尺，宽92.5英尺，从龙骨到四个大烟囱的顶端有175英尺，高相当于11层楼。是当时一流的超豪华巨轮.2006年5月，最后一名见证事件的女性生还者逝世，终年99岁。目前尚有两名女生还者仍然存活，但她们在意外时还不到一岁，因此不会对事件有回忆。</P>
<P><IMG alt=BingShanShaShou.jpg src="http://pic.piaohua.com/0701pic/allimg/080107/0153530.jpg" border=0></P><p>2008-01-07 01:52:12 开始连接......<br>2008-01-07 01:52:14 开始搜索候选资源......<br>2008-01-07 01:52:15 搜索到31个候选资源<br>2008-01-07 01:52:17 使用候选资源进行连接......<br>2008-01-07 01:52:20 搜索到26个候选资源<br>2008-01-07 01:52:23 使用候选资源进行连接......<br>2008-01-07 01:52:24 文件创建成功，开始下载数据......<br>2008-01-07 01:52:26 用户取消下载&nbsp;&nbsp; 本文来自 <a href="/index.html" target="_blank">www.eee4.com</a></p>
（直接可能无法下载，一律使用<a href="http://pstatic.xunlei.com/about/product/down_xl5.htm" target="_blank">迅雷下载</a>）<br>
英国2008科幻记录大片《BBC 摧毁泰坦尼克号的冰山杀手》DVD中字 － 来自[3E迅雷电影站eee4.com]下载地址：<IMG src="/templets/img/down.jpg" border=0><br>
<table style="BORDER-RIGHT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; BORDER-BOTTOM: #cccccc 1px dotted" cellspacing="0" cellpadding="6" width="95%" align="center" border="0">
    <tbody>
        <tr>
            <td style="WORD-WRAP: break-word" bgcolor="#fdfddf"><anchor></anchor><a href="ftp://eee4.com:eee4@xl3.eee4.com:8448/冰山杀手/[3E迅雷电影站www.eee4.com]BBC摧毁泰坦尼克号的冰山杀手.rmvb" target="_blank">ftp://eee4.com:eee4@xl3.eee4.com:8448/冰山杀手/[3E迅雷电影站www.eee4.com]BBC摧毁泰坦尼克号的冰山杀手.rmvb</a></td>
        </tr>
    </tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O16122Q0-53J9.jpg{/dede:field}
