{dede:field name='keywords'}11点14分BD中英双字1024高清迅雷{/dede:field}
{dede:field name='description'}11点14分BD中英双字1024高清迅雷下载、免费下载，11点14分BD中英双字1024高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}11点14分BD中英双字1024高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-03-08{/dede:field}
{dede:field name='body'}<p>
	<img alt="" border="0" onclick="zoom(this)" onload="attachimg(this, 'load')" src="http://images.allocine.fr/medias/nmedia/18/35/47/73/18396886.jpg" /><br />
	<br />
	<br />
	◎ 译　　名：11点14分<br />
	◎ 片　　名：11:14<br />
	◎ 年　　份：2003<br />
	◎ 类　　别：喜剧/惊悚/犯罪<br />
	◎ 时　　长：86 min<br />
	◎ 地　　区：美国/加拿大<br />
	◎ 语　　言：英语<br />
	◎ IMDB评分：7.3/10 (17,439 votes)<br />
	◎ 上映日期：2003年5月16日 (法国，戛纳电影节)<br />
	◎ 获奖情况：http://www.imdb.com/title/tt0331811/awards<br />
	◎ 导　　演：Greg Marcks<br />
	◎ 编　　剧：Greg Marcks<br />
	◎ 主　　演：亨利&bull;托马斯 Henry Thomas&nbsp; ....Jack<br />
	　　　　　　Blake Heron&nbsp; ....Aaron<br />
	　　　　　　芭芭拉&bull;赫希 Barbara Hershey&nbsp; ....Norma<br />
	　　　　　　克拉克&bull;格雷格 Clark Gregg&nbsp; ....Officer Hannagan<br />
	　　　　　　希拉里&bull;斯万克 Hilary Swank&nbsp; ....Buzzy<br />
	　　　　　　肖恩&bull;海托西 Shawn Hatosy&nbsp; ....Duffy<br />
	　　　　　　斯塔克&bull;桑德斯 Stark Sands&nbsp; ....Tim<br />
	　　　　　　科林&bull;汉克斯 Colin Hanks&nbsp; ....Mark<br />
	　　　　　　本&bull;福斯特 Ben Foster&nbsp; ....Eddie<br />
	　　　　　　帕特里克&bull;斯威兹 Patrick<a href="http://www.eee4.cc/" target="_blank">3e</a> Swayze&nbsp; ....Frank<br />
	　　　　　　瑞切尔&bull;蕾&bull;库克 Rachael Leigh Cook&nbsp; ....Cheri<br />
	　　　　　　杰森&bull;席格尔 Jason Segel&nbsp; ....Leon (Paramedic #1)<br />
	　　　　　　里克&bull;高莫兹 Rick Gomez&nbsp; ....Kevin (Paramedic #2)</p>
<p>
	◎ 简　　介：</p>
<p>
	　　天大的灾难，总是由一连串毫不起眼的意外所引爆！希拉里史旺和瑞秋莱库克主演。</p>
<p>
	　　宁静的郊区小镇，一切看来安详无事，所有的人、事、物彷佛都将沉沉睡去。但当午夜逐渐逼近，时间来到11点14分，所有互不相干的命运突然转弯，彼此撞击，朝向不可知的方向疯狂加速...</p>
<p>
	Scene One<br />
	高速公路上，酩酊大醉的轿车驾驶杰克（亨利&#8231;托马斯Henry Thomas饰演）猛然撞上一个年轻的无名男性...</p>
<p>
	Scene Two<br />
	五百公尺外的便利商店里，爆发一桩枪击抢劫案，女店员芭芝（希拉里&#8231;史旺Hillary Swank饰演）左肩中枪，血流不止。但稍晚，她便被警方以嫌疑共犯的名义逮捕...</p>
<p>
	Scene Three<br />
	邻近镇上的墓园里，一位偏执顽固的父亲－法兰克（派屈克&#8231;史威兹Patrick Swayze饰演）正焦急掩盖一桩与他无关的离奇凶杀...</p>
<p>
	Scene Four<br />
	马路上，三个游手好闲的少年正漫不经心开<a href="http://www.3edyy.com/" target="_blank">电影</a>着休旅车四处瞎窜，朝经过的其他车辆乱砸东西，还往车窗外尿尿。但他们却不知道，这些恶毒混蛋的玩笑，将把自己，以及这个看似平静如常的夜晚，引向致命且具爆炸性的结局...</p>
<p>
	Scene Five<br />
	同时间，举镇闻名的波霸辣妹雪莉（瑞秋&#8231;莱&#8231;库克Rachael Leigh Cook饰演 ）正大玩劈腿游戏，设计引诱刚搭上的男友，帮她谋杀某人...</p>
<p>
	　　午夜结束前，两个年轻人将被一连串看似互不相关，却又紧紧交缠的荒谬、机缘、意外、巧合所牵引，迎向死亡。【11点14分】的故事以倒叙方式逐渐开展，在精彩绝伦的布局安排中，映照人性里细腻幽微的面向。命运的丝线已悄悄地蜿蜒而出，并将在今晚【11点14分】交织成无可抗拒的巨大蓝图。</p>
<p>
	【电影截图】：<br />
	<br />
	<img alt="" border="0" onclick="zoom(this)" onload="attachimg(this, 'load')" src="http://pic.qnpic.com:83/r.jsp?fn=//piaog/share/2010/5/16/06.jpg" />&nbsp;<br />
	<img alt="" border="0" onclick="zoom(this)" onload="attachimg(this, 'load')" src="http://pic.qnpic.com:83/r.jsp?fn=//piaog/share/2010/5/16/08.jpg" /></p>
<br />
<p>
	[下载地址]：<img border="0" src="http://www.3edyy.com/templets/img/down.jpg" /></p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://7e:7e@d8.3edyy.com:157/【3E电影院www.eee4.cc】11点14分.rmvb" target="_blank">ftp://7e:7e@d8.3edyy.com:157/【3E电影院www.eee4.cc】11点14分.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2972/飘花电影piaohua.com11点14分BD中英双字1024高清.mkv">ftp://dy44:piaohua@dy44.piaohua.com:2972/飘花电影piaohua.com11点14分BD中英双字1024高清.mkv</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15063150-1LW.jpg{/dede:field}
