{dede:field name='keywords'}谎言之躯/叛谍同谋/谎言对决BD中{/dede:field}
{dede:field name='description'}谎言之躯/叛谍同谋/谎言对决BD中英双字1024/1280高清迅雷下载、免费下载，谎言之躯/叛谍同谋/谎言对决BD中英双字1024/1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}谎言之躯/叛谍同谋/谎言对决BD中英双字1024/1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-10-31{/dede:field}
{dede:field name='body'}<p>
	◎译　　名　《谎言之躯/叛谍同谋/谎言对决》莱昂纳多08最新动作惊悚大片BD中英双字1024x556高清版<br />
	◎片　　名　Body of Lies<br />
	◎年　　代　2008<br />
	◎国　　家　美国<br />
	◎类　　别　动作/剧情/惊悚<br />
	◎语　　言　英语<br />
	◎字　　幕　中英双字<br />
	◎IMDB评分 7.4/10&nbsp; 15,934 votes<br />
	◎文件格式　BD-RMVB<br />
	◎视频尺寸　1024 x 556<br />
	◎文件大小　1CD<br />
	◎片　　长　128 mins<br />
	◎导　　演　雷德利&middot;斯科特 Ridley Scott<br />
	◎主　　演　莱昂纳多&middot;迪卡普里奥 Leonardo DiCaprio&nbsp; ....Roger Ferris<br />
	　　　　　　罗素&middot;克劳 Russell Crowe&nbsp; ....Ed Hoffman<br />
	　　　　　　卡里斯&middot;范&middot;侯登 Carice van Houten&nbsp; ....Gretchen Ferris<br />
	　　　　　　马克&middot;斯特朗 Mark Strong&nbsp; ....Hani<br />
	　　　　　　奥斯卡&middot;伊撒克 Oscar Isaac&nbsp; ....Bassam<br />
	　　　　　　文斯&middot;科洛斯莫 Vince Colosimo&nbsp; ....Skip<br />
	　　　　　　Michael Gaston&nbsp; ....Holiday<br />
	　　　　　　格什菲&middot;法拉哈尼 Golshifteh Farahani<br />
	　　　　　　西蒙&middot;迈克伯尼 Simon McBurney<br />
	　　　　　　Ali Suliman&nbsp; ....Omar Sadiki<br />
	　　　　　　Omar Berdouni&nbsp; ....Al- Saleen&#39;s LT<br />
	　　　　　　April Rouse&nbsp; ....Soccer Mom<br />
	　　　　　　Ben Youcef&nbsp; ....The Caller<br />
	　　　　　　Clara Khoury&nbsp; ....Bassam&#39;s Wife<br />
	　　　　　　Ali Khalil&nbsp; ....Zayed Ibishi<br />
	　　　　　　Lubna Azabal<br />
	　　　　　　Bijan Daneshmand&nbsp; ....Embassy Doctor<br />
	　　　　　　Alexander von Roon&nbsp; ....Dutch Chief of Police<br />
	<br />
	◎简　　介　<br />
	<br />
	　　本片根据《华盛顿邮报》的专栏作家大卫&middot;伊格纳修斯的同名小说改编而成。主人公法瑞斯是一名前记者，他在伊拉克的战争中受了伤，随后CIA委派给他一项特别任务&mdash;&mdash;去约旦调查一位恐怖分子头目。法瑞斯为了实现任务绞尽脑汁，他需要来自CIA官员埃德&middot;霍夫曼以及另一位约旦情报局头目的帮助，然而对方的老奸巨猾，总是让法瑞斯不太放心，法瑞斯能够信任他们吗？<br />
	<br />
	　　罗杰&middot;费瑞斯是美国情报机关内最顶尖的特务，是一位高度精密、独来独往的专业特工。但他也是一位没有自己身份的人，他把生命交托予秘密电话线上另一端的幕后策划者。<br />
	<br />
	　　美国中情局资深成员爱德&middot;霍夫曼，在市郊住所睡房的手提电脑上指挥大局，控制费瑞斯任何时间的一举一动。与此同时，恐怖组织领袖正密谋避过最精密的情报网，发动一次全球性的炸弹袭击。<br />
	&nbsp; &nbsp;<br />
	　为了引出恐怖组织领袖，费瑞斯将要闯进地下黑势力王国，打倒恐怖份子，并与约旦特种部队结盟。他将会为今次任务远赴伊拉克、约旦、华盛顿和杜拜，但就在他越来越接近目标人物的时候，他发现幕后竟然是敌我难分，一直信任的盟友竟变成最危险的敌人。</p>
<p>
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://images.dvdempire.com/gen/movies/1442176h.jpg');" src="http://images.dvdempire.com/gen/movies/1442176h.jpg" /><br />
	<br />
	◎剧　　照　<br />
	<br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://media.movieweb.com/img/u/Q/N/PHLZ1SQUNzKuQN_m.jpg');" src="http://media.movieweb.com/img/u/Q/N/PHLZ1SQUNzKuQN_m.jpg" /><br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://media.movieweb.com/img/4/i/h/PHfcNmkonT74ih_m.jpg');" src="http://media.movieweb.com/img/4/i/h/PHfcNmkonT74ih_m.jpg" /><br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://media.movieweb.com/img/Z/C/E/PHyByFDHSdfZCE_m.jpg');" src="http://media.movieweb.com/img/Z/C/E/PHyByFDHSdfZCE_m.jpg" /><br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://media.movieweb.com/img/e/A/z/PHxsgyCC5m7eAz_m.jpg');" src="http://media.movieweb.com/img/e/A/z/PHxsgyCC5m7eAz_m.jpg" /><br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://media.movieweb.com/img/H/B/x/PHxxrFAzoetHBx_m.jpg');" src="http://media.movieweb.com/img/H/B/x/PHxxrFAzoetHBx_m.jpg" /><br />
	<br />
	一句话评论<br />
	<br />
	在这场CIA与恐怖组织的对决中，真实的交火场面、不停的追逐与打斗、大约10分钟就有1次的大型爆炸场面和随处可以见到的剧情高潮成就了这部影片。<br />
	&mdash;&mdash;《综艺》<br />
	<br />
	幕后制作<br />
	<br />
	　　扣人心弦的情节<br />
	<br />
	　　当导演雷德利&middot;斯科特看到大卫&middot;伊格纳修斯的同名小说时，就被深深吸引。他认为，&ldquo;这部小说以不同寻常的视角深刻尖锐地反应了发生在战区前线的事，以及重现了战功赫赫的&lsquo;前线人员&rsquo;的惊险生活。情节很真实，是那种&lsquo;不确定性&rsquo;带来的真实性。&rdquo;<br />
	<br />
	　　制片人唐纳德&middot;德&middot;莱恩也很喜欢这部小说：&ldquo;大卫的小说非常精彩，并充满智慧和悬疑。书里描写了太多悬念十足又令人恐慌的关于&lsquo;间谍&rsquo;、&lsquo;情报员&rsquo;和&lsquo;侦察与反侦察&rsquo;的故事，层层推进直到高潮，并把这些扣人心弦的故事置于国家与国家的交锋中，文化与文化的碰撞中，以及敌我对峙的状态之下。读完小说后，我们认为这太具有可拍性了，这是一本极富感染力的书，完全是一部大制作电影的绝好剧本。&rdquo;<br />
	<br />
	　　如今暗不见光的谍报活动已成为世界各国彼此较量的主要阵地，一国之国力并不仅仅取决于武器是否先进，科技是否发达，更取决于谁先获得和掌握大量的核心信息。&ldquo;信息是底线，&rdquo;雷德利认为，&ldquo;但这就意味着在火药味十足的信息争夺战中，没有谁可以信赖，甚至是你最好的朋友。pps在线电影也许就在你转身的那一瞬间，你就成为了他手中的棋子，被他摆布和利用。如果受雇于国家机构，那唯一的信念便是国家利益高于一切，包括自己的生命。如果不以这样的准则作为自己的行为标准，那么在整个斗智斗勇的过程中，你将是脆弱和不堪一击的。&rdquo;<br />
	<br />
	　　曾获奥斯卡最佳编剧的威廉&middot;莫纳汉这次与斯科特并肩作战，在剧本的改编上也是不遗余力，把原本就精彩纷呈的小说改编得更具冲击力，将焦虑重重的国家安全部门、充满斗志且个性鲜明的情报人员描写得活灵活现。雷德利认为，&ldquo;剧本里充满了很多有趣的情节，可以说这个故事反应的情况是多维的。故事情节的发展以及人物性格的变化都使整个故事充满了神奇，看这个故事实际上就是一次激动之旅。&rdquo;唐纳德&middot;德&middot;莱恩表示，&ldquo;这个故事太引人入胜了，一旦看上以后，就不得不全身心投入到整个故事情节的跌宕起伏中。&rdquo;<br />
	<br />
	　　从《无间行者》就与威廉&middot;莫纳汉有过密切配合的男主角莱昂纳多&middot;迪卡普里奥认为自己能有出色的表现都应归功于威廉，&ldquo;他的剧本真是改写得太棒了，大量信息综合和多角度的呈现以及<a href="http://www.eee4.com/" target="_blank">迅雷电影下载</a>猫捉老鼠的游戏在他的笔下全面铺开，当然，这也对我们演员提出了高要求。&rdquo;埃德&middot;霍夫曼的扮演者罗素&middot;克劳说到剧本时也略显情不自禁，&ldquo;很明显，这是一部精彩的电影，尽管它是虚构的，但对于我们而言就是必须表演得真实，让观众在观影的那个阶段相信它是真实的，尤其是影片里有太多的欺骗、算计和斗智，还有跨文化的冲突。也许观众不得不动脑筋去梳理整个过程的来龙去脉，才能最终明白最后为什么会有那样的结局。&rdquo;<br />
	<br />
	&nbsp; &nbsp; &nbsp; &nbsp; 出色的表演和默契的合作<br />
	<br />
	&nbsp; &nbsp; &nbsp; &nbsp; 《谎言之躯》是导演雷德利&middot;斯科特第四次与罗素&middot;克劳合作，当说到这个老朋友兼老合作者时，雷德利说道：&ldquo;罗素可以扮演任何角色，他喜欢尝试变化，他自身的变化以及饰演的角色的变化。也正因为如此，我们很喜欢和他一起共事。我相信他是世界上不可多得的表演家，并且也是最好的。&rdquo;　当知道雷德利如此夸赞自己时，罗素高兴地笑着说，&ldquo;我是喜欢尝试变化，最开始雷德利找我出演埃德&middot;霍夫曼这个角色时，先问我愿意给自己增肥50磅吗？我答应了他&hellip;&hellip;&rdquo;。同时，罗素也表示，&ldquo;为了把这个角色演得更好，我和原作者大卫&middot;伊格纳修斯就埃德&middot;霍夫曼的角色性格和背景展开了讨论。&rdquo;而罗素的表现也深得大卫的好评，&ldquo;罗素将更多的率性、幽默赋予了埃德&middot;霍夫曼，并使埃德&middot;霍夫曼更像埃德&middot;霍夫曼，而这是我未曾想到的。&rdquo;<br />
	<br />
	　　为了演好罗杰&middot;费瑞斯这个角色，莱昂纳多&middot;迪卡普里奥可是做足了功课－－他不仅认真研读了大卫&middot;伊格纳修斯的原着并认真向作者咨询，以及与多位曾任前美国中央情报局CIA情报员的人进行交谈，&ldquo;我尝试着了解CIA更多的一些情况，比如机构是如何运行的，人们在里面的关系到底如何等等。通过和他们的交流使我认识到，情报局以小组制分工分派工作，一旦接到任务小组成员就会被分散到世界各个角落，并且不放过任何一条他们可能搜索到的信息。他们的工作非常危险也非常艰难，他们总是处于高度风险中，以看得见的现在去赌摸不着的未知。&rdquo;雷德利对莱昂纳多的表现十分满意，&ldquo;莱昂纳多是我所接触到的为数不多的有趣且值得合作的人，一是因为他很好相处、风趣幽默，二是因为他的专业、智慧，他的表演总是那么天衣无缝，出神入化。我总是被他饰演过的角色打动，而从我们合作的经历来看，他的表现总比我对他的期望更好！&rdquo;<br />
	<br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://img.album.pchome.net/54/68/92/27/96af34c7dcacb3d380d7da4424358884.jpg');" src="http://img.album.pchome.net/54/68/92/27/96af34c7dcacb3d380d7da4424358884.jpg" /><br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://img.album.pchome.net/54/68/92/27/d9fa5b9ae08742ba187ef9726014af06.jpg');" src="http://img.album.pchome.net/54/68/92/27/d9fa5b9ae08742ba187ef9726014af06.jpg" /></p>

<p>
	莱昂纳多08最新动作惊悚大片《谎言之躯》BD中英双字1024x556高清版 </p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://e60:e60@xl2.eee4.com:9306/[3E电影站www.eee4.com]谎言之躯BD中英双字1024x556高清版.rmvb" target="_blank">ftp://e60:e60@xl2.eee4.com:9306/[3E电影站www.eee4.com]谎言之躯BD中英双字1024x556高清版.rmvb</a></td>
		</tr>
	</tbody>
</table>
<br />
<p>
	莱昂纳多08最新动作惊悚大片《谎言之躯》DVD中字1024x576高清版 </p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://e60:e60@xl2.eee4.com:9306/[3E电影站www.eee4.com]谎言之躯DVD中字1024x576高清版无水印.rmvb" target="_blank">ftp://e60:e60@xl2.eee4.com:9306/[3E电影站www.eee4.com]谎言之躯DVD中字1024x576高清版无水印.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:1958/飘花电影piaohua.com谎言之躯1280高清.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:1958/飘花电影piaohua.com谎言之躯1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O160333Z-533M.jpg{/dede:field}
