{dede:field name='keywords'}我的野蛮女友BD1280高清迅雷下载{/dede:field}
{dede:field name='description'}我的野蛮女友BD1280高清迅雷下载、免费下载，我的野蛮女友BD1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}我的野蛮女友BD1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-04-14{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://cimg.163.com/movie/0108/06/yupgigirl.jpg" style="width: 428px; height: 615px" /></p>
<p>
	◎译　　名　我的野蛮女友/我的淘气女友<br />
	◎片　　名　My Sassy Girl<br />
	◎年　　代　2001<br />
	◎国　　家　韩国<br />
	◎类　　别　喜剧/剧情/爱情<br />
	◎语　　言　韩语<br />
	◎IMDB评分 8.1/10 (20,158 votes)<br />
	◎IMDB链接 <a class="faqlink" endcolor="FF6600" href="http://www.imdb.com/title/tt0293715" index="0" startcolor="0066ff" state="OFF" style="color: #0066ff">http://www.imdb.com/title/tt0293715</a><br />
	◎片　　长　123 mins<br />
	◎导　　演　郭在容Jae-young Kwak<br />
	◎主　　演　车太贤 Cha Tae Hyun .....Kyun-woo<br />
	　　　　　　全智贤 Jeon Ji Hyun .....The Girl<br />
	　　　　　　金仁文 In-mun Kim .....Kyun-woo&#39;s father<br />
	　　　　　　金太贤 Tae-hyeon Kim<br />
	　　　　　　李武英 Mu-yeong Lee<br />
	　　　　　　任豪 Im Ho .....A Man The Girl met as blind date<br />
	　　　　　　郭在容 Jae-young Kwak .....Covered Cart Bar Customer (uncredited)<br />
	　　　　　　Jin-hie Han .....The Girl&#39;s father<br />
	　　　　　　Sook-hee Hyun .....The Girl&#39;s mother<br />
	　　　　　　金一宇 Il-woo Kim .....Quintuplets<br />
	　　　　　　Dong-won Seo .....Deserter<br />
	　　　　　　Wok-suk Song .....Kyun-woo&#39;s mother<br />
	　　　　　　梁金锡 Geum-Seok Yang .....Kyun-woo&#39;s aunt<br />
	<br />
	<br />
	◎简　　介<br />
	<br />
	　　牵牛是个老实巴交的大好人，但他至今还是孑然一身，在一次跟朋友的聚会上，牵牛见到了他心目中的女友&mdash;&mdash;一个外表清脱俗的女孩子。碍着朋友的面子，他没有上去认识她。回家的时候，牵牛在地铁地车站再次见到了喝醉酒后神志不清的她。她竟在地上呼喝男乘客给她让座，又呕向另一名男乘客处，牵牛只好带她到旅馆借宿一宵。当他正在至洗澡时，警察突然入他的房间，一丝不挂的牵牛被带住警署。第二天，她约牵牛出来，盘问一番后，她又再喝醉，牵牛只好再次带她回旅馆过夜。就是如此，两人就开始了这个关系。<br />
	<br />
	　　牵牛希望改变她的行为，但每次却出乎意料──她简直不把牵牛当人看待。牵牛决要治疗她的伤痕。从此，他就犯贱地在挨骂受打的日子中享受恋爱的快乐&hellip;&hellip;<br />
	<br />
	<br />
	幕后制作：<br />
	<br />
	　　《我的野蛮女友》根据韩国一部颇为流行的网络小说改编的，一放映就引起了轰动，青年男女，趋之若鹜。而影片在中国也引发了观影热潮，大多数观众都是通过这部作品开始了解韩国电影，此后逐渐关注和喜爱韩国电影，足见这部影片成为韩片打入中国市场一块关键的敲门砖。影片中的经典场景和台词都被影迷们津津乐道。该片一改过去韩片中女主人公温柔贤淑的形象，美丽的女主角却野蛮起来比男人还粗鲁残忍，这对民风保守的韩国来说是对社会文化的一个极大突破，并掀起一股 &ldquo;野蛮风&rdquo;的热潮。女主角的扮演者全智贤也因此片成为亚洲炙手可热的一线女星，并且作为&ldquo;野蛮女性&rdquo;的形象代言人接拍了多个广告。<br />
	<br />
	<br />
	获奖记录：<br />
	<br />
	&middot;全智贤凭本片获得2002年度韩国大钟奖最佳女主角奖，并与车太贤双双当选最佳人气奖 　　<br />
	&middot;车太贤获青龙奖电影节最佳男新人 　　<br />
	&middot;刷新由《朋友》保持韩国电影史上最高预售纪录 　　<br />
	&middot;2001年度韩国十大卖座片亚军<br />
	<br />
	<br />
	精彩对白：<br />
	<br />
	第一、不要叫她温柔。<br />
	<br />
	第二、不要让她喝三杯以上，否则她会逢人就打；<br />
	<br />
	第三、在咖啡馆一定要喝咖啡、不要喝可乐或橙汁；<br />
	<br />
	第四、如果她打你 一定要装得很痛 如果真的很痛 那要装得没事<br />
	<br />
	第五、在你们认识的第一百天，一定要去她班上送一 支玫瑰， 她会非常喜欢；<br />
	<br />
	第六、你一定要学会击剑，打壁球；<br />
	<br />
	第七、要随时做好蹲监狱的思想准备；<br />
	<br />
	第八、如果她说她会杀了你，那不要当真，这样你会好 受些；<br />
	<br />
	第九、如果她的鞋穿着不舒服，一定要和她换鞋穿；<br />
	<br />
	第十、她喜欢写东西，要好好地鼓励她。<br />
	<br />
	<br />
	经典柔情场景之二：<br />
	<br />
	　　女友和牵牛在郊外，女友让牵牛去对面的山头，然后隔山大喊：牵牛，对不起，其实&hellip;&hellip;；然后满脸都是泪。 　　这一幕让人想起《情书》里渡边博子对着雪山向已经去世的男友哭喊着问好的一幕，也是满脸都是泪，也是无法挥别过去的疼痛。而本片中这一幕胜过《情书》的地方在于，对面山头的牵牛根本无法听清女友在喊些什么，这让每一个观众心急火燎感慨万千。<br />
	<br />
	<br />
	经典柔情场景之三：<br />
	<br />
	　　牵牛决定和&ldquo;她&rdquo;分手了，两人从山上下来，女友让牵牛先坐火车离开。牵牛在火车开动后突然跳下了火车想去再见女友一面，可是同样心理的女友却在同时跃上了火车，趴在地上的牵牛眼睁睁地看着女友和火车一起远去，用这样的方式，他们分手了。<br />
	<br />
	　　虽然说好了是要有两年时间再不相见，可是导演在这里还是上演了一幕失之交臂。错失永远是最让人痛心的，我们无法不想&ldquo;如果他们同时上了火车会怎样&rdquo;这样的问题，因为我们永远对在别处的生活有幻想。<br />
	<br />
	<br />
	经典柔情场景之四：<br />
	<br />
	　　全片最后一个镜头。姑妈一直想给牵牛介绍的女友、姑妈一直想给女友介绍的新男友，原来正是他俩。冥冥中的缘分早有安排，两人默默对视，悄悄地将手相连。画外音响起&mdash;&mdash;&mdash;&mdash;为你的爱建一座机会的桥。<br />
	<br />
	　　人生由无数个偶然组成，伴着申成勋《I　beˉlieve》（《我相信》）的主题音乐，影片结束部分的峰回路转，其实在前面已被多次暗示，不留痕迹的起承衔接间，如画似的风景和画中似的男女终于走到了桥的那头。命运就是在你和你爱的人之间架起一座桥，坚定地去爱，能有几人做到？爱情需要的从来就不是相遇的机会而是彼此敞开心扉交流的契机，带上你的他或她一起看看这个野蛮柔情的韩国故事吧，然后忠诚地对对方说一句：我爱你，直到永远。<br />
	<br />
	　　英国十九世的浪漫诗人柯勒治曾经说过：&ldquo;我看到的一切都是青春与春天&rdquo;，这也恰好可以描绘《我的野蛮女友》给我留下的愉悦感受。强烈推荐女权主义者及热恋中的情侣观看此片，我敢保证你们将会在电影院轻松愉快地度过两个多小时。</p>
<p>
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120414/01/62564813201204140129441728641880215_004.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120414/01/62564813201204140129441728641880215_003.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120414/01/62564813201204140129441728641880215_002.jpg" style="width: 720px; height: 405px" /><br />
	<br />
	&nbsp;</p>
<p>
	【下载地址】</p>
<table bgcolor="#0099cc" border="0" cellpadding="10" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.net" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy125:piaohua@dy125.piaohua.com:7843/飘花电影piaohua.com我的野蛮女友BD中字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:7843/飘花电影piaohua.com我的野蛮女友BD中字1280高清.rmvb</a></td>
		</tr>
		<tr>
		</tr>
	</tbody>
</table>
<br />{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15D45Z-33I3.jpg{/dede:field}
