{dede:field name='keywords'}初音未来2011东京演唱会BD1280高{/dede:field}
{dede:field name='description'}初音未来2011东京演唱会BD1280高清迅雷下载、免费下载，初音未来2011东京演唱会BD1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}初音未来2011东京演唱会BD1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-01-19{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="/uploads/allimg/c120524/133N492LQ0-2H910.jpg" style="width: 550px; height: 425px" /></p>
<p>
	【剧情简介】</p>
<p>
	由CRYPTON FUTURE MEDIA使用Vocaloid 2语音合成引擎为基础开发的虚拟女性歌手软件初音未来（初音ミク）是全球第一个拥有自己声音的虚拟动漫形象。<br />
	继2010年&ldquo;初音未来之日&rdquo;感谢祭演唱会大获成功之后，2011年再次举办了一场演唱会。<br />
	与2010年的透明屏幕所呈现的3D效果不同，2011年的舞台外形像一台电视机或者一个盒子，呈现出来的影像能够与现场的灯光、烟雾等完美配合，能表现出景深效果，更具立体感。美中不足是&ldquo;盒子&rdquo;里面全黑，没有背景，甚至看不出舞台地板。<br />
	整场演唱会依然有初音和作为嘉宾的巡音、镜音双子四人表演。初音多次变换淘宝网女装造型，并演唱了多首新歌。<br />
	已经在网上看过个性签名这场演唱会的在线代理观众大多对这场演唱会评论不佳。除了黑色虚空舞台的单调感和整场演唱会感觉过快的节奏外，主要是由于糟糕的摄像和剪辑，没能很好得表现出现场影像的3D效果，也没有表现出四人完美的舞姿。虽然如此，这声演唱会仍然值得期待。建议观看1280x720以上的高清晰版，效果会好一点儿，能够稍补摄像和剪辑的不足。<br />
	&nbsp;</p>
<p>
	--------------------------------<br />
	【概要】<br />
	タイトル：初音ミク ライブパーティー 2011 -39&rsquo;s LIVE IN TOKYO-<br />
	主催：5pb.<br />
	协力：クリプトン?フューチャー?メディア<br />
	SEGA<br />
	グッドスマイルカンパニー<br />
	AG-ONE<br />
	公式サイト：<br />
	开催日时：2011年3月9日 (水) 18:00 OPEN／19:00 START／21:30 CLOSE 予定<br />
	会场：ZeppTokyo 东京都江东区青海１丁目パレットタウン<br />
	チケット料金：￥5,390/税込１ドリンク别<br />
	ねんどろいどぷらす 初音ミク 桜バージョンチャーム付<br />
	チケット先行予约：<br />
	受付期间：2010/12/27(月) 12:00～2011/01/05(水) 18:00／イープラス<br />
	一般発売：2011年1月30日（予定）<br />
	<br />
	公演に関するお问い合わせ<br />
	株式会社ディスクガレージ 03-5436-9600 (平日12:00～18:00)<br />
	<br />
	「感谢祭」に来ていただいた方々も、「次は绝対行きたいっ！」って方々も<br />
	ぜひぜひチケットをゲットしてくださいませー！<br />
	＊関系者の皆さん、今回は主催ではありませんのでチケットよこせ、とか言われても<br />
	対応できかねますのでご容赦ください、はい。<br />
	<br />
	さらっと书いてますけど、桜バージョンチャームって？！<br />
	今后の详しい情报は5pb.さんの「ミクパ」公式サイトチェックですよ!！<br />
	<br />
	&mdash;&mdash;曲目信息&mdash;&mdash;<br />
	<br />
	【大妈&ldquo;救场&rdquo;】<br />
	Symphony/buzzG &amp; 相沢舞<br />
	かくれんぼ/buzzG &amp; 相沢舞<br />
	【开场】<br />
	Ievan Polkka - Otomania feat.初音ミク<br />
	こっち向いて Baby - ryo (supercell) feat.初音ミク<br />
	二息步行 - DECO*27 feat.初音ミク<br />
	アルビノ - buzzG feat.初音ミク<br />
	え？あぁ、そう。 - papiyon feat.初音ミク<br />
	ぽっぴっぽ - ラマーズP feat.初音ミク<br />
	トリノコシティ - 40mP feat.初音ミク<br />
	キャットフード - doriko feat.初音ミク<br />
	崩壊歌姫 -disruptive diva- - マチゲリータP feat.初音ミク<br />
	白い雪のプリンセスは - のぼる&uarr; feat.初音ミク<br />
	ワールズエンド?ダンスホール/wowaka feat.初音ミク＆巡音ルカ<br />
	ダブルラリアット - アゴアニキ feat.巡音ルカ<br />
	No Logic - ジミーサムP feat.巡音ルカ<br />
	RIP=RELEASE - minato(流星P) feat.巡音ルカ<br />
	Japanese Ninja No.1 - デッドボールP feat.巡音ルカ<br />
	ルカルカ★ナイトフィーバー - samfree feat.巡音ルカ<br />
	结ンデ开イテ罗刹ト骸 - ハチ feat.初音ミク<br />
	ローリンガール - wowaka feat.初音ミク<br />
	【30分钟休息广告】<br />
	trick and treat - OSTER project feat.镜音リン?镜音レン<br />
	悪ノ娘 - mothy_悪ノP feat.镜音リン<br />
	悪ノ召使 - mothy_悪ノP feat.镜音レン<br />
	いろは呗 - 银サク feat.镜音リン<br />
	炉心融解 - iroha(sasaki） feat.镜音リン<br />
	ココロ - トラボルタ feat.镜音リン<br />
	メランコリック - Junky feat.镜音リン<br />
	リンリンシグナル - Dios/シグナルP feat.镜音リン?镜音レン<br />
	SPICE! - minato(流星P) feat.镜音レン<br />
	Fire◎Flower - halyosy feat.镜音レン<br />
	Packaged - livetune feat.初音ミク<br />
	*ハロー、プラネット。 - sasakure.UK feat.初音ミク<br />
	マージナル - OSTER project feat.初音ミク<br />
	初音ミクの激唱 - cosMo（暴走P） feat.初音ミク<br />
	歌に形はないけれど - doriko feat.初音ミク<br />
	Yellow - livetune feat.初音ミク<br />
	タイムマシン - 1640mP feat.初音ミク<br />
	ARiA - とくP feat.初音ミク<br />
	【返场】<br />
	カラフル&times;メロディ - ちーむMOER feat.初音ミク<br />
	メルト - supercell feat.初音ミク<br />
	初めての恋が终わる时 - supercell feat.初音ミク<br />
	<img alt="" src="/uploads/allimg/c120524/133N492M260-2V335.jpg" /></p>
<p>
	<img alt="" src="/uploads/allimg/c120524/133N492M3Z-292311.jpg" style="width: 640px; height: 360px" /><br />
	[下载地址]：&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				</anchor>ftp://dy241:370kk@dy241.piaohua.com:2041/小八戒电影xiaobajie.com初音未来2011东京演唱会720p.rmvb</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120524/133N492M540-304531.jpg{/dede:field}
