{dede:field name='keywords'}不朽的名作第10集韩剧迅雷下载，{/dede:field}
{dede:field name='description'}不朽的名作第10集韩剧迅雷下载、免费下载，不朽的名作第10集韩剧Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}不朽的名作第10集韩剧{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-24{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img.album.pchome.net/02/25/03/37/0169aac88ac57f2b83cbccc3c5afa3ef.jpg" /></p>
<p>
	[剧 名]:不朽的名作 &#48520;&#54980;&#51032; &#47749;&#51089;<br />
	[播 送]:韩国channel A<br />
	[类 型]:channel A周末剧&nbsp;<br />
	[首 播]:2012年03月17日<br />
	[时 间]:每周六日晚北京时间19点30分播放一集<br />
	[导 演]:张亨一（野人时代 张吉山）<br />
	[编 剧]:金信惠<br />
	[主 演]:韩在石 朴善英 高斗心 李荷妮 高允厚<br />
	[集 数]:预计20集<br />
	&nbsp;</p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.net" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3142/飘花电影piaohua.com不朽的名作EP01.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3142/飘花电影piaohua.com不朽的名作EP01.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3188/飘花电影piaohua.com不朽的名作EP02.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3188/飘花电影piaohua.com不朽的名作EP02.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3259/飘花电影piaohua.com不朽的名作EP03.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3259/飘花电影piaohua.com不朽的名作EP03.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3259/飘花电影piaohua.com不朽的名作EP04.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3259/飘花电影piaohua.com不朽的名作EP04.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3289/飘花电影piaohua.com不朽的名作EP05.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3289/飘花电影piaohua.com不朽的名作EP05.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3465/飘花电影piaohua.com不朽的名作EP06.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3465/飘花电影piaohua.com不朽的名作EP06.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3465/飘花电影piaohua.com不朽的名作EP07.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3465/飘花电影piaohua.com不朽的名作EP07.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3465/飘花电影piaohua.com不朽的名作EP08.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3465/飘花电影piaohua.com不朽的名作EP08.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3487/飘花电影piaohua.com不朽的名作EP09.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3487/飘花电影piaohua.com不朽的名作EP09.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3487/飘花电影piaohua.com不朽的名作EP10.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3487/飘花电影piaohua.com不朽的名作EP10.rmvb</a></td>
		</tr>
	</tbody>
</table>
<p>
	&nbsp;</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15233430-31406.jpg{/dede:field}
