{dede:field name='keywords'}影子爱人1280版HD国语中字2012香{/dede:field}
{dede:field name='description'}影子爱人1280版HD国语中字2012香港喜剧爱情迅雷下载、免费下载，影子爱人1280版HD国语中字2012香港喜剧爱情Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}影子爱人1280版HD国语中字2012香港喜剧爱情{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-12{/dede:field}
{dede:field name='body'}<p>
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120511/17/56643687201205111725251614654013432_005.jpg" /></p>
<p>
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120511/17/56643687201205111725251614654013432_006.jpg" /></p>
<p>
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120511/17/56643687201205111725251614654013432_007.jpg" /></p>
<p>
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120511/17/56643687201205111725251614654013432_008.jpg" /></p>
<p>
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120511/17/56643687201205111725251614654013432_004.jpg" /></p>
<p>
	中文名： 《影子爱人》<br />
	外文名： Repeat I Love You / Shadows of Love<br />
	其它译名： 港译：影子情人 / 影子恋人 / 再说一次我爱你<br />
	出品时间： 2012年<br />
	出品公司： 中影集团，DMG传媒，蝴蝶传媒<br />
	制片地区： 中国<br />
	导演： 潘源良<br />
	制片人： 谭杰文<br />
	类型： 喜剧 / 爱情<br />
	主演： 张柏芝 / 权相宇 / 景甜 / 丁春诚 / 张韶涵 / 井柏然 / 成泰燊 / 恬妞 / 吴耀汉 / 鲁园<br />
	上映时间： 2012年5月11日<br />
	对白语言： 汉语普通话<br />
	监制： 关锦鹏<br />
	摄影师： 姜国民</p>
<p>
	<br />
	剧情简介</p>
<p>
	　　柯氏集团的继承人Paris（张柏芝 饰）神秘失踪后，Paris的恋人，总裁助理权正熏（权相宇 饰）为了保护她的继承权利益，策划了一个计谋，找到一个长相酷似Paris的女孩秦芯（张柏芝 饰）来代替她。在权正熏的指导下，秦芯搬进了柯氏大宅，接受作为企业女继承人的种种培训，掩 人耳目。而一心想篡夺Paris继承权的叔叔董傲年却伺机而动，企图揭穿秦芯的假面目。变成Paris的秦芯面临着多重考验，并在与权正熏的相处中暗生情愫，当她想要努力追求这段幸福时，真的Paris却又出现了&hellip;&hellip;</p>
<p>
	<br />
	◎影片截图</p>
<p>
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120511/17/56643687201205111725251614654013432_003.jpg" /></p>
<p>
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120511/17/56643687201205111725251614654013432_002.jpg" /></p>
<p>
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120511/17/56643687201205111725251614654013432_001.jpg" /></p>
<p>
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120511/17/56643687201205111725251614654013432_000.jpg" /></p>
<p>
	&nbsp;<img src="http://img170.poco.cn/mypoco/myphoto/20120512/10/56643687201205121030567959443702155_001.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 338px; border-top: 0px solid; border-right: 0px solid" /></p>
<p>
	&nbsp;<img src="http://img170.poco.cn/mypoco/myphoto/20120512/10/56643687201205121030567959443702155_002.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 338px; border-top: 0px solid; border-right: 0px solid" /></p>

<p>
	&nbsp;<img src="http://img170.poco.cn/mypoco/myphoto/20120512/10/56643687201205121030567959443702155_000.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 338px; border-top: 0px solid; border-right: 0px solid" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120512/10/56643687201205121030567959443702155_003.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 338px; border-top: 0px solid; border-right: 0px solid" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.netftp//dy44:piaohua@dy44.piaohua.com:3125/" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3396/飘花电影piaohua.com影子爱人DVD国语中字.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3396/飘花电影piaohua.com影子爱人DVD国语中字.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3405/飘花电影piaohua.com影子爱人1280版HD国语中字.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3405/飘花电影piaohua.com影子爱人1280版HD国语中字.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O14Z4550-5FF.jpg{/dede:field}
