<?php
$z[0]=Array("field","等待超人/超人，你在哪里？[DVD",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","等待超人/超人，你在哪里？[DVD中英双字]迅雷下载、免费下载，等待超人/超人，你在哪里？[DVD中英双字]Gvod高清在线播放，剧情介绍等。",72,242);
$z[1][4]['name']="description";
$z[2]=Array("field","等待超人/超人，你在哪里？[DVD中英双字]",244,320);
$z[2][4]['name']="title";
$z[3]=Array("field","",322,361);
$z[3][4]['name']="writer";
$z[4]=Array("field","",363,402);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-02-15",404,454);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",456,493);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://5e:5e@m3.3edyy.com:519/【3E看看www.3ekk.com】等待超人[DVD中英双字].rmvb\" target=_blank>ftftp://5e:5e@m3.3edyy.com:519/【3E看看www.3ekk.com】等待超人[DVD中英双字].rmvb</A></TD></TR></TBODY></TABLE></div><ul class=\"mmlist",495,759);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MQ4DX0-3A51.jpg",761,842);
$z[8][4]['name']="litpic";

?>