{dede:field name='keywords'}等待超人/超人，你在哪里？[DVD{/dede:field}
{dede:field name='description'}等待超人/超人，你在哪里？[DVD中英双字]迅雷下载、免费下载，等待超人/超人，你在哪里？[DVD中英双字]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}等待超人/超人，你在哪里？[DVD中英双字]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-02-15{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://5e:5e@m3.3edyy.com:519/【3E看看www.3ekk.com】等待超人[DVD中英双字].rmvb" target=_blank>ftftp://5e:5e@m3.3edyy.com:519/【3E看看www.3ekk.com】等待超人[DVD中英双字].rmvb</A></TD></TR></TBODY></TABLE></div><ul class="mmlist{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MQ4DX0-3A51.jpg{/dede:field}
