{dede:field name='keywords'}在这世界的角落中日双语字幕1024{/dede:field}
{dede:field name='description'}在这世界的角落中日双语字幕1024×576迅雷下载、免费下载，在这世界的角落中日双语字幕1024×576Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}在这世界的角落中日双语字幕1024×576{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-08-10{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://pic.piaohua.com/0701pic/allimg/110808/3-110PR306130-L.jpg" style="width: 640px; height: 434px" /></p>
<p>
	中文片名: 在这世界的角落<br />
	英文片名:<br />
	剧集分类: 战争<br />
	影片类型: 日剧<br />
	资源格式: RMVB<br />
	上影时间: 2011-08-05<br />
	导　演:<br />
	主　演: 北川景子 小出惠介 优香 速水重道 篠田三郎 市毛良枝 小西舞优 芦田爱菜</p>
<p>
	对白语言: 日语&nbsp;<br />
	字幕语种: 简&nbsp; 日&nbsp;</p>
<p>
	介绍:<br />
	太平洋战争中的广岛。<br />
	主人公丝丝是紫菜店的长女，一个喜欢画画的普通女孩子。<br />
	因为嫁给了小时候只见过一次却不记得长相的人，从广岛市搬到了吴市。</p>
<p>
	在对新的家庭，新的街道，新的世界不知所措的同时，天性开朗的丝丝愉快地过着每一天。<br />
	嫁入北条家以后，在忙碌的生活中，丝丝终于熟悉了吴市的街道。<br />
	某一天，丝丝交到了一个叫铃的朋友。丝丝迷路时，就是铃好心地给她指了路。<br />
	虽然铃是青楼女子，但丝丝仍然无所顾忌地和她来往着。<br />
	然而，铃其实是自己丈夫周作在婚前秘密交往的女子。<br />
	偶然之下，丝丝也渐渐察觉到了丈夫周作过去曾与铃之间发生的事。</p>
<p>
	自己对于丈夫来说可能只是铃的替身&hellip;&hellip;<br />
	丝丝怀抱着这个挥之不去的想法不敢说出口。<br />
	就在此时，丝丝在广岛的同班同学兼初恋情人的水原出现了。<br />
	水原在经历了战场之后，前来向丝丝表明心意。<br />
	然而丝丝的心早已倾向了现在的丈夫。<br />
	另一方面，看穿丝丝疑虑的铃意味深长地说了句，&ldquo;秘密只要还是秘密，就和没发生过没有两样&rdquo;，消失了。</p>
<p>
	与此同时，战况日益严峻，对物资匮乏的生活雪上加霜&hellip;&hellip;<br />
	在广岛的娘家，奔赴战场的哥哥回到家时已是一粒沙石。<br />
	随后1945年3月，终于吴市的街道也遭到了大规模的空袭。<br />
	碰巧带着外甥女看望公公的丝丝，从防空洞出来后遇到了定时炸弹爆炸。<br />
	卷入爆炸的丝丝右手被炸飞，而手上牵着的外甥女则失去了性命。</p>
<p>
	&ldquo;你个凶手，明明有你带着她，怎么就！&rdquo;丝丝遭到姐姐的责难。<br />
	&ldquo;别说了！丝丝还活着就好。&rdquo;婆婆帮忙劝说道。<br />
	（真的？真的好吗？对不起。对不起。对不起，我还活着。）<br />
	自此以后，丝丝眼中的世界变得扭曲了。<br />
	丝丝本想回去娘家，但是被从丧女之痛中恢复过来的姐姐劝说后改变了主意。</p>
<p>
	没过多久，原子弹落在了广岛，失去了娘家人的消息。<br />
	无情袭来的战争的恐惧。欺凌他人，又被人欺凌的祖国败下阵来。<br />
	丝丝在这世界的角落里生存下来，决心记录下生活的点滴</p>
<p>
	<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20110810/01/17870980201108100137343511966270632_000.jpg" style="width: 640px; height: 360px" /></p>
<p>
	<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20110810/01/17870980201108100137343511966270632_001.jpg" style="width: 640px; height: 360px" /></p>

<p>
	[下载地址]： &nbsp;<img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" /></p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy67:piaohua@dy67.piaohua.com:1031/飘花电影下载站www.xiaozhizhu.net在这世界的角落中日双语字幕1024分辨率.mkv">ftp://dy67:piaohua@dy67.piaohua.com:1031/飘花电影下载站www.xiaozhizhu.net在这世界的角落中日双语字幕1024分辨率.mkv</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:1229/飘花电影下载站www.xiaozhizhu.net在这世界的角落中日双语字幕1024分辨率.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:1229/飘花电影下载站www.xiaozhizhu.net在这世界的角落中日双语字幕1024分辨率.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O161c010-3b15.jpg{/dede:field}
