{dede:field name='keywords'}耀舞长安/耀武长安港台剧粤语19{/dede:field}
{dede:field name='description'}耀舞长安/耀武长安港台剧粤语19国语18迅雷下载、免费下载，耀舞长安/耀武长安港台剧粤语19国语18Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}耀舞长安/耀武长安港台剧粤语19国语18{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-25{/dede:field}
{dede:field name='body'}<p>
	&nbsp;<img onload="if(this.width&gt;650){this.width=650;};return false;" src="/uploads/allimg/c120525/133O10b2130-205216.jpg" /></p>
<p>
	&nbsp;<img onload="if(this.width&gt;650){this.width=650;};return false;" src="/uploads/allimg/c120525/133O10b25Z-219236.jpg" /></p>
<p>
	&nbsp;<img onload="if(this.width&gt;650){this.width=650;};return false;" src="/uploads/allimg/c120525/133O10b2L0-229361.jpg" /></p>
<p>
	&nbsp;<img onload="if(this.width&gt;650){this.width=650;};return false;" src="/uploads/allimg/c120525/133O10b2950-231R1.jpg" /></p>
<p>
	导演：张乾文 / 马先奎</p>
<p>
	&bull;演员：<br />
	欧阳震华 / 胡杏儿 / 钟嘉欣 / 麦长青 / 马赛 / 汤盈盈</p>
<p>
	&bull;类型：偶像 / 古装<br />
	&bull;首映：2012年4月30日 中国香港<br />
	&bull;又名：乐府藏龙</p>
<p>
	&bull;点评： 胡杏儿与钟嘉欣斗&quot;舞&quot;争艳--<br />
	&bull;剧情： 　　《耀舞长安》是以唐中业为时代背景， 歌舞升平，皇室重视舞乐技艺，是史上演艺事业最繁盛的时期。故事舞台为唐代官办教坊、长安三大教坊之一的&quot;永丽园&quot;。皇室为鼓励舞乐，将举办&quot;选花魁&quot;活动，得花魁者封为郡主或王妃。能训练花魁人才的教坊，将成为皇室御用的教坊，归入宫廷编制；该教坊的官员、导师将成为国师级人马，一登龙门，富贵荣华。<br />
	　　故事围绕两男两女的恩怨。舞乐教坊昶丽园都知大人乔步龙（欧阳震华）原名戴名钹，本是一名与家人流亡的街头乐师，为保家人性命，他找了乔步龙，即高仁（麦长青）作替死鬼，并取代了他的身份，成为乔步龙。高仁虽奇迹地没死去，但却失忆及毁容了。在命运安排下，步龙重遇高仁，并因欣赏他的音乐才华而收留他在身边，岂料此举却给自己日后埋下计时炸弹。另一边厢，高仁的未婚妻 &mdash; 首席舞优卞玉嫣(钟嘉欣)被步龙退婚后感到羞辱，但天意弄人，她因恨成爱，爱上了他，失忆了的高仁却又同时苦恋着她。而步龙却钟情于与他爱斗气的舞优利在山（胡杏儿）。因此，当玉嫣得悉步龙爱上在山后，心生妒意，决在花魁竞逐中打败在山，两者的姊妹情因此破裂。</p>
<p>
	&bull; 花絮： 《耀舞长安》是香港电视广播有限公司古装电视剧，由欧阳震华、胡杏儿、钟嘉欣及麦长青领衔主演，监制张乾文。本剧为2012无线节目巡礼剧集之一。</p>
<p>
	&nbsp;<img onload="if(this.width&gt;650){this.width=650;};return false;" src="/uploads/allimg/c120525/133O10b31F-249155.jpg" /></p>
<p>
	&nbsp;<img onload="if(this.width&gt;650){this.width=650;};return false;" src="/uploads/allimg/c120525/133O10b330-25L64.jpg" /></p>
<p>
	&nbsp;<img onload="if(this.width&gt;650){this.width=650;};return false;" src="/uploads/allimg/c120525/133O10b3440-2E0L.jpg" /></p>
<p>
	&nbsp;<img onload="if(this.width&gt;650){this.width=650;};return false;" src="/uploads/allimg/c120525/133O10b35F-2M5S.jpg" /></p>
<p>
	<img onload="if(this.width&gt;650){this.width=650;};return false;" src="/uploads/allimg/c120525/133O10b3G0-2R1D.jpg" /></p>
<p>
	<img onload="if(this.width&gt;650){this.width=650;};return false;" src="/uploads/allimg/c120525/133O10b3S0-2c047.jpg" /></p>
<p>
	<img onload="if(this.width&gt;650){this.width=650;};return false;" src="/uploads/allimg/c120525/133O10b40-30RA.jpg" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="/uploads/allimg/c120525/133O104261P-625N.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：http://www.xiaozhizhu.net</td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:3327/飘花电影piaohua.com耀武长安粤语01.rmvb</td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:3332/飘花电影piaohua.com耀武长安粤语02.rmvb</td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:3336/飘花电影piaohua.com耀武长安粤语03.rmvb</td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:3342/飘花电影piaohua.com耀武长安粤语04.rmvb</td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:3352/飘花电影piaohua.com耀武长安粤语05.rmvb</td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:3369/飘花电影piaohua.com耀武长安粤语06.rmvb</td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:3374/飘花电影piaohua.com耀武长安粤语07.rmvb</td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:3379/飘花电影piaohua.com耀武长安粤语08.rmvb</td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:3387/飘花电影piaohua.com耀武长安粤语09.rmvb</td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:3399/飘花电影piaohua.com耀武长安粤语10.rmvb</td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:3419/飘花电影piaohua.com耀武长安粤语11.rmvb</td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:3427/飘花电影piaohua.com耀武长安粤语12.rmvb</td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:3434/飘花电影piaohua.com耀武长安粤语13.rmvb</td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:3447/飘花电影piaohua.com耀武长安粤语14.rmvb</td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:3452/飘花电影piaohua.com耀武长安粤语15.rmvb</td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:3468/飘花电影piaohua.com耀武长安粤语16.rmvb</td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:3476/飘花电影piaohua.com耀武长安粤语17.rmvb</td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:3484/飘花电影piaohua.com耀武长安粤语18.rmvb</td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:3492/飘花电影piaohua.com耀武长安粤语19.rmvb</td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#00ffff" style="line-height: 18px; word-break: break-all" width="100%">
				国语</td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:3328/飘花电影piaohua.com耀武长安国语01.rmvb</td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:3334/飘花电影piaohua.com耀武长安国语02.rmvb</td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:3342/飘花电影piaohua.com耀武长安国语03.rmvb</td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:3347/飘花电影piaohua.com耀武长安国语04.rmvb</td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:3354/飘花电影piaohua.com耀武长安国语05.rmvb</td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:3370/飘花电影piaohua.com耀武长安国语06.rmvb</td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:3377/飘花电影piaohua.com耀武长安国语07.rmvb</td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:3421/飘花电影piaohua.com耀武长安国语08.rmvb</td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:3389/飘花电影piaohua.com耀武长安国语09.rmvb</td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:3401/飘花电影piaohua.com耀武长安国语10.rmvb</td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:3424/飘花电影piaohua.com耀武长安国语11.rmvb</td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:3431/飘花电影piaohua.com耀武长安国语12.rmvb</td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:3437/飘花电影piaohua.com耀武长安国语13.rmvb</td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:3449/飘花电影piaohua.com耀武长安国语14.rmvb</td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:3456/飘花电影piaohua.com耀武长安国语15.rmvb </td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:3475/飘花电影piaohua.com耀武长安国语16.rmvb </td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:3482/飘花电影piaohua.com耀武长安国语17.rmvb </td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:3488/飘花电影piaohua.com耀武长安国语18.rmvb </td>
		</tr>
	</tbody>
</table>
<p>
	&nbsp;</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O10b4140-314Q7.jpg{/dede:field}
