<?php
$z[0]=Array("field","第30届香港电影金像奖颁奖典礼迅",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","第30届香港电影金像奖颁奖典礼迅雷下载、免费下载，第30届香港电影金像奖颁奖典礼Gvod高清在线播放，剧情介绍等。",73,223);
$z[1][4]['name']="description";
$z[2]=Array("field","第30届香港电影金像奖颁奖典礼",225,291);
$z[2][4]['name']="title";
$z[3]=Array("field","",293,332);
$z[3][4]['name']="writer";
$z[4]=Array("field","",334,373);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-04-19",375,425);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",427,464);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://3e:3e@m3.3edyy.com:529/【3E看看www.3ekk.com】直击第三十届香港电影金像奖[红地毯].rmvb\" target=_blank>ftftp://3e:3e@m3.3edyy.com:529/【3E看看www.3ekk.com】直击第三十届香港电影金像奖[红地毯].rmvb</A></TD></TR></TBODY></TABLE><BR><FONT color=#ff0000 size=2><STRONG>[下载地址]：<IMG border=0 src=\"httftp://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg",466,871);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MQ4P1Z-1V59.jpg",873,954);
$z[8][4]['name']="litpic";

?>