{dede:field name='keywords'}第30届香港电影金像奖颁奖典礼迅{/dede:field}
{dede:field name='description'}第30届香港电影金像奖颁奖典礼迅雷下载、免费下载，第30届香港电影金像奖颁奖典礼Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}第30届香港电影金像奖颁奖典礼{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-04-19{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://3e:3e@m3.3edyy.com:529/【3E看看www.3ekk.com】直击第三十届香港电影金像奖[红地毯].rmvb" target=_blank>ftftp://3e:3e@m3.3edyy.com:529/【3E看看www.3ekk.com】直击第三十届香港电影金像奖[红地毯].rmvb</A></TD></TR></TBODY></TABLE><BR><FONT color=#ff0000 size=2><STRONG>[下载地址]：<IMG border=0 src="httftp://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MQ4P1Z-1V59.jpg{/dede:field}
