{dede:field name='keywords'}异教徒2DVD中字英国恐怖悬疑惊悚{/dede:field}
{dede:field name='description'}异教徒2DVD中字英国恐怖悬疑惊悚迅雷下载、免费下载，异教徒2DVD中字英国恐怖悬疑惊悚Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}异教徒2DVD中字英国恐怖悬疑惊悚{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-04-24{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://i.imgur.com/iDxSY.jpg" style="width: 498px; height: 640px" /></p>
<p>
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120424/19/56643687201204241941541140206333248_005.jpg" /></p>
<p>
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120424/19/56643687201204241941541140206333248_004.jpg" /></p>

<p>
	◎译　　名　异教徒2<br />
	◎片　　名　The Wicker Tree<br />
	◎年　　代　2010<br />
	◎国　　家　英国<br />
	◎类　　别　剧情/恐怖/悬疑/惊悚<br />
	◎语　　言　英语<br />
	◎字　　幕　中字<br />
	◎IMDB评分 4.6/10 (345 votes)<br />
	◎文件格式　DVD-RMVB<br />
	◎视频尺寸　720 x 304<br />
	◎文件大小　1CD 490MB<br />
	◎片　　长　96 mins<br />
	◎导　　演　Robin Hardy<br />
	◎主　　演　Christopher Lee ... Sir Lachlan Morrison<br />
	　　　　　　Kiera Chaplin<br />
	　　　　　　Susie Amy<br />
	　　　　　　Graham McTavish<br />
	　　　　　　Honeysuckle Weeks<br />
	　　　　　　Brittania Nicol</p>
<p>
	◎简　　介　</p>
<p>
	　　Robin Hardy 1973年的The Wicker Man的翻拍。<br />
	　　年轻的夫妇贝丝和史蒂夫，从德克萨斯刀苏格兰度假.此地的迷人风光和居民的热情好客,让他们不胜欣喜.然而,渐渐地,这个风光秀丽的小镇不为人知的狰狞面目渐渐破开迷雾,等待他们的,是一场不可想象的恐惧和灾难...</p>
<p>
	<br />
	◎影片截图</p>
<p>
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120424/19/56643687201204241941541140206333248_000.jpg" /></p>
<p>
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120424/19/56643687201204241941541140206333248_001.jpg" /></p>

<p>
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120424/19/56643687201204241941541140206333248_002.jpg" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.netftp//dy44:piaohua@dy44.piaohua.com:3201/" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3287/飘花电影piaohua.com异教徒2DVD中字.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3287/飘花电影piaohua.com异教徒2DVD中字.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O16429250-24S3.jpg{/dede:field}
