{dede:field name='keywords'}虫虫特攻队/虫虫危机/昆虫总动员{/dede:field}
{dede:field name='description'}虫虫特攻队/虫虫危机/昆虫总动员BD中英双字1024高清迅雷下载、免费下载，虫虫特攻队/虫虫危机/昆虫总动员BD中英双字1024高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}虫虫特攻队/虫虫危机/昆虫总动员BD中英双字1024高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-02-27{/dede:field}
{dede:field name='body'}<p>
	<img src="http://pic.piaohua.com/0701pic/allimg/080814/0510420.jpg" /></p>
<p>
	【译　　名】《虫虫危机/昆虫总动员/虫虫特攻队》全球历史票房3.5亿经典动画喜剧DVD中英双字<br />
	【片　　名】A Bugs Life<br />
	【年　　代】1998<br />
	【国　　家】美国<br />
	【类　　别】家庭/动画/喜剧/冒险<br />
	【语　　言】英语<br />
	【字　　幕】中英文<br />
	【IMDB评分】7.3/10 (29,608 votes)<br />
	【文件格式】DVDrip-RMVB<br />
	【视频尺寸】800 x 452<br />
	【电影整理】3E迅雷电影下载站(www.eee4.com)<br />
	【文件大小】3CD 563MB<br />
	【片　　长】96 Min<br />
	【导　　演】约翰&middot;雷斯特 John Lasseter<br />
	　　　　　　安德鲁&middot;斯坦顿 Andrew Stanton<br />
	【主　　演】凯文&middot;斯帕西 Kevin Spacey .... Hopper (voice)<br />
	　　　　　　朱丽娅&middot;路易斯-德莱弗斯 Julia Louis-Dreyfus .... Atta (voice)<br />
	　　　　　　邦尼&middot;亨特 Bonnie Hunt .... Rosie (voice)<br />
	　　　　　　大卫&middot;海德&middot;皮尔斯 David Hyde Pierce .... Slim (voice)<br />
	　　　　　　马德琳&middot;卡恩 Madeline Kahn .... Gypsy Moth (voice)<br />
	　　　　　　丹尼斯&middot;利里 Denis Leary .... Francis (voice)<br />
	　　　　　　Roddy McDowall .... Mr. Soil (voice)<br />
	　　　　　　约翰&middot;雷森博格 John Ratzenberger .... P.T. Flea (voice)<br />
	　　　　　　安德鲁&middot;斯坦顿 Andrew Stanton .... Additional Voices (voice)<br />
	　　　　　　雷切尔&middot;戴维 Rachel Davey .... Additional Voices (voice)<br />
	　　　　　　凯布利&middot;布朗 Kimberly J. Brown .... Additional Voices (voice)<br />
	　　　　　　戴夫&middot;弗雷 Dave Foley .... Flik (voice)<br />
	　　　　　　布拉德&middot;加瑞特 Brad Garrett .... Dim (voice)<br />
	　　　　　　约翰&middot;雷斯特 John Lasseter .... Additional Voices (voice)<br />
	　　　　　　David L. Lander .... Thumper (voice)</p>
<p>
	【简　　介】：</p>
<p>
	<br />
	　　本片灵感取材自伊索寓言《蚂蚁与蚱蜢》的故事，讲述一段昆虫世界的冒险之旅。<br />
	　　在一个美丽的蚂蚁王国，大家整日都在辛苦的工作。而有一只名叫飞力的蚂蚁有着自己的爱好&mdash;发明创造。不过尽管他辛辛苦苦法发明了一种&ldquo;收割机&rdquo;，但王国的统治者蚁后和公主还是看不起他和他的发明。<br />
	　　蚂蚁王国最大的威胁是一群蝗虫，这群蝗虫总是抢夺蚂蚁们的劳动成果&mdash;&mdash;粮食，他们是蚂蚁王国的一大块乌云。在一次蝗虫进行掠夺时，飞力为了保护他的发明把粮食碰到了悬崖下。恼火的蝗虫抓住了公主的妹妹小不点来出气。紧要关头，飞力挺身而出，怒斥蝗虫军团的头目霸王。为了得到更多的粮食，霸王放开了小不点，他威胁说如果他下次来得不到双倍的粮食他将血洗蚂蚁王国。<br />
	　　由于飞力把粮食都弄丢了，大家把心中的恐惧和不满都发泄在他的身上，蚂蚁王国决定驱逐飞力。为了留在自己的祖国，飞力提出了一项建议：他将去找比蝗虫更大的虫子来赶走蝗虫。由于没有什么更好的办法，蚂蚁王国给了飞力一次机会去兑现他的承诺。<br />
	　　飞力来到了城市，在这里他看到了一群昆虫打败了一群无赖的挑衅，这使得飞力对他们十分崇拜，认为他们就是能够打败蝗虫的&ldquo;大虫子&rdquo;。实际上这群昆虫是一群失业的马戏团演员，有甲虫、螳螂、蜘蛛等。他们正在找事作，于是便接受了飞力的邀请，来到了蚂蚁王国，但并没有说明他们的身份。蚂蚁们并不十分相信这些模样古怪的昆虫，并且昆虫们自己也有些害怕，打了退堂鼓，准备离开这里。虽然得知昆虫们的真实身份后飞力很失望，但他极力阻止昆虫们离开，否则他会被蚂蚁们认为是个大骗子。后来昆虫智斗小鸟，救出了飞力和小不点，得到了蚂蚁们的好感，也找回了自信心。由于飞力受到了小鸟的启发，决定做一支假鸟来吓退蝗虫。假鸟完成了，霸王也带着它的恶棍军团逼近了蚂蚁王国。<br />
	　　孰料这时马戏团的老板来找他的昆虫演员了。当蚂蚁们得知昆虫们是马戏团的演员时，失望万分。蚂蚁王国驱逐了飞力和昆虫们。恰恰这时，蝗虫军团来了。在小不点的劝说下，飞力和昆虫们决定一起迎战蝗虫。虽然假鸟开始吓住了蝗虫的进攻，但狡猾的霸王识破了飞力的假鸟，准备一举摧毁蚂蚁王国。不料出现了一只真鸟，而霸王以为这还是飞力的诡计，毫不退让，于是成了鸟儿的腹中餐。于是蝗虫们溃不成军。<br />
	　　又是一个春来到，公主当上了蚁后，飞力也受到了嘉奖。而昆虫们，回到了他们的城市。一个完美的结局。</p>
<p>
	<br />
	【幕后】：<br />
	　　本片是迪士尼与PIXAR公司一同合作拍摄的第二部3D电脑动画，前一部作品《玩具总动员》空前成功，这回他们则把背景换到昆虫的世界！本片迪士尼在宣传时宣称是一部&ldquo;史诗钜作&rdquo;。本片的导演John Lasseter继《玩具总动员》再度展现高度创意，并且也坦承有一幕大鸟著火的场景灵感是来自于日本动画大师宫崎骏作品《天空之城》。另外在本片的片尾，收录有一段特别制作的NG片段，由昆虫主角们假装在拍片时遇到吃螺丝、撞墙等状况，实在是十分暴笑！3E迅雷<a href="/" target="_blank">电影下载</a>站</p>

<p>
	【电影截图】：<br />
	电影来源：www.eee4.com<br />
	<img src="http://pic.piaohua.com/0701pic/allimg/080814/0510421.jpg" />&nbsp;<br />
	<img src="http://pic.piaohua.com/0701pic/allimg/080814/0510422.jpg" />&nbsp;<br />
	<img src="http://pic.piaohua.com/0701pic/allimg/080814/0510423.jpg" /></p>
<p>
	全球历史票房3.5亿经典动画喜剧《虫虫特工队》DVD中英双字 － 来自[3E迅雷电影站eee4.com]下载地址：<img border="0" src="/templets/img/down.jpg" /><br />
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<anchor></anchor><a href="ftp://eee4.com:8114@vip11.eee4.com:8114/[3E迅雷电影站www.eee4.com]虫虫特工队DVD中英双字CD1.rmvb" target="_blank">ftp://eee4.com:8114@vip11.eee4.com:8114/[3E迅雷电影站www.eee4.com]虫虫特工队DVD中英双字CD1.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<anchor></anchor><a href="ftp://eee4.com:8114@vip11.eee4.com:8114/[3E迅雷电影站www.eee4.com]虫虫特工队DVD中英双字CD2.rmvb" target="_blank">ftp://eee4.com:8114@vip11.eee4.com:8114/[3E迅雷电影站www.eee4.com]虫虫特工队DVD中英双字CD2.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<anchor></anchor><a href="ftp://eee4.com:8114@vip11.eee4.com:8114/[3E迅雷电影站www.eee4.com]虫虫特工队DVD中英双字CD3.rmvb" target="_blank">ftp://eee4.com:8114@vip11.eee4.com:8114/[3E迅雷电影站www.eee4.com]虫虫特工队DVD中英双字CD3.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<anchor></anchor><a href="ftp://dy44:piaohua@dy44.piaohua.com:2900/飘花电影piaohua.com虫总动员BD中英双字1024高清.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2900/飘花电影piaohua.com虫总动员BD中英双字1024高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1B42510-35K3.jpg{/dede:field}
