{dede:field name='keywords'}火柴人/火柴男人/种计BD中英双字{/dede:field}
{dede:field name='description'}火柴人/火柴男人/种计BD中英双字1280高清[DVD国语配音]迅雷下载、免费下载，火柴人/火柴男人/种计BD中英双字1280高清[DVD国语配音]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}火柴人/火柴男人/种计BD中英双字1280高清[DVD国语配音]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-11-02{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://apollo.s.dpool.sina.com.cn/nd/dataent/moviepic/pics/19/moviepic_9eb2f276fb1042b5d4b165142a89d285.jpg" /></p>
<p>
	片 名：《火柴人/火柴男人/种计》尼古拉斯.凯奇经典犯罪惊秫大片DVD国语配音<br />
	英文名:Matchstick Men<br />
	导 演：雷德利&middot;斯科特 Ridley Scott<br />
	主 演：尼古拉斯&middot;凯奇<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 米罗娜&middot;沃尔特斯<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 山姆&middot;洛克威尔<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 布鲁斯&middot;亚特曼<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 斯蒂夫&middot;伊斯丁<br />
	上 映：2003年09月12* ( 美国 )<br />
	地 区：美国 ( 拍摄地 ) <br />
	对 白：国语<br />
	评 分：7.4/10( 9523票 )<br />
	颜 色：彩色<br />
	时 长：116 分钟<br />
	类 型：犯罪 剧情 喜剧 惊秫 <br />
	分 级：阿根廷：13 德国：12 葡萄牙：M/12 澳大利亚：M 美国：PG-13 智利：14 瑞典：7 瑞士：12 <br />
	<br />
	剧 情：<br />
	　　罗伊(尼古拉斯&middot;凯奇)是一名患有精神强迫症的骗子，他和野心勃勃的搭档弗兰克(山姆&middot;洛克威尔)联手，经营着小打小闹的骗子生涯，依靠罗伊高明的骗术，屡屡有人受骗上当。这次哥儿俩又精心策划着一起新买卖，此时却有一个名叫安吉拉(艾丽森&middot;洛曼)的14岁少女闯入了他们的生活，并彻底搅乱了罗伊原本井井有条的世界。<br />
	　　安吉拉自称是罗伊失散多年的女儿，一直备受强迫症折磨的罗伊心里又惊又喜，他努力想成为一个平凡的好爸爸，弥补过往失落的亲情，但安吉拉的出现也让不习惯与人相处的罗伊，几度濒临抓狂边缘。更糟的还在后头，劲爆女儿发现父亲赖以维生的&ldquo;职业&rdquo;后，竟对骗徒生涯发生浓厚兴趣，她苦苦哀求父亲让她加入骗子行列，罗伊这下该如何是好？</p>

<p>
	【电影截图】：<br />
	电影来源：www.eee4.com<br />
	<br />
	<img border="0" onclick="if(!this.resized) {return true;} else {window.open(this.src);}" onload="if(this.width&gt;screen.width*0.7) {this.resized=true; this.width=screen.width*0.7; this.alt='点击在新窗口浏览图片\nCTRL+Mouse 滚轮可放大/缩小';}" onmouseover="function anonymous()&#13;&#10;{&#13;&#10;function anonymous()&#13;&#10;{&#13;&#10;if(this.width&gt;screen.width*0.7) {this.resized=true; this.width=screen.width*0.7; this.style.cursor='hand'; this.alt='点击在新窗口浏览图片\nCTRL+Mouse 滚轮可放大/缩小';}&#13;&#10;}&#13;&#10;}" onmousewheel="return imgzoom(this);" src="http://img.album.pchome.net/05/62/29/33/74a6ad451e0454de604214f113c3c1f6.jpg" />&nbsp;<br />
	<img border="0" onclick="if(!this.resized) {return true;} else {window.open(this.src);}" onload="if(this.width&gt;screen.width*0.7) {this.resized=true; this.width=screen.width*0.7; this.alt='点击在新窗口浏览图片\nCTRL+Mouse 滚轮可放大/缩小';}" onmouseover="function anonymous()&#13;&#10;{&#13;&#10;function anonymous()&#13;&#10;{&#13;&#10;if(this.width&gt;screen.width*0.7) {this.resized=true; this.width=screen.width*0.7; this.style.cursor='hand'; this.alt='点击在新窗口浏览图片\nCTRL+Mouse 滚轮可放大/缩小';}&#13;&#10;}&#13;&#10;}" onmousewheel="return imgzoom(this);" src="http://img.album.pchome.net/05/62/29/33/feee9e7b01126dad8d0c558921d50683.jpg" />&nbsp;<br />
	<img border="0" onclick="if(!this.resized) {return true;} else {window.open(this.src);}" onload="if(this.width&gt;screen.width*0.7) {this.resized=true; this.width=screen.width*0.7; this.alt='点击在新窗口浏览图片\nCTRL+Mouse 滚轮可放大/缩小';}" onmouseover="function anonymous()&#13;&#10;{&#13;&#10;function anonymous()&#13;&#10;{&#13;&#10;if(this.width&gt;screen.width*0.7) {this.resized=true; this.width=screen.width*0.7; this.style.cursor='hand'; this.alt='点击在新窗口浏览图片\nCTRL+Mouse 滚轮可放大/缩小';}&#13;&#10;}&#13;&#10;}" onmousewheel="return imgzoom(this);" src="http://img.album.pchome.net/05/62/29/33/26ffe5f4a35dfc218b15d67ec8b99dcb.jpg" />&nbsp;<br />
	<img border="0" onclick="if(!this.resized) {return true;} else {window.open(this.src);}" onload="if(this.width&gt;screen.width*0.7) {this.resized=true; this.width=screen.width*0.7; this.alt='点击在新窗口浏览图片\nCTRL+Mouse 滚轮可放大/缩小';}" onmouseover="function anonymous()&#13;&#10;{&#13;&#10;function anonymous()&#13;&#10;{&#13;&#10;if(this.width&gt;screen.width*0.7) {this.resized=true; this.width=screen.width*0.7; this.style.cursor='hand'; this.alt='点击在新窗口浏览图片\nCTRL+Mouse 滚轮可放大/缩小';}&#13;&#10;}&#13;&#10;}" onmousewheel="return imgzoom(this);" src="http://img.album.pchome.net/05/62/29/33/54a6e4f792703e2ad4292fe1ef998887.jpg" /></p>
<p>
	尼古拉斯.凯奇经典犯罪惊秫大片《火柴人》DVD国语配音 </p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://e13:e13@dm.eee4.com:1216/[3E电影站www.eee4.com]火柴人DVD国语配音.rmvb" target="_blank">ftp://e13:e13@dm.eee4.com:1216/[3E电影站www.eee4.com]火柴人DVD国语配音.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				&nbsp;<a href="ftp://dy44:piaohua@dy44.piaohua.com:1983/飘花电影piaohua.com火柴人BD中字1280高清.rmvb ">ftp://dy44:piaohua@dy44.piaohua.com:1983/飘花电影piaohua.com火柴人BD中字1280高清.rmvb </a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O16035110-14c9.jpg{/dede:field}
