<?php
$z[0]=Array("field","云下的日子HD国语中字1024高清迅",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","云下的日子HD国语中字1024高清迅雷下载、免费下载，云下的日子HD国语中字1024高清Gvod高清在线播放，剧情介绍等。",73,223);
$z[1][4]['name']="description";
$z[2]=Array("field","云下的日子HD国语中字1024高清",225,291);
$z[2][4]['name']="title";
$z[3]=Array("field","",293,332);
$z[3][4]['name']="writer";
$z[4]=Array("field","",334,373);
$z[4][4]['name']="source";
$z[5]=Array("field","2012-03-29",375,425);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",427,464);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://3e:3e@m3.3edyy.com:529/【3E看看www.3ekk.com】云下的日子.rmvb\" target=\"_blank",466,587);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MP191630-26422.jpg",589,673);
$z[8][4]['name']="litpic";

?>