{dede:field name='keywords'}红场特警/红色警探/魔鬼红星/冲{/dede:field}
{dede:field name='description'}红场特警/红色警探/魔鬼红星/冲出生死线[BD中英双字1280x720高清版]迅雷下载、免费下载，红场特警/红色警探/魔鬼红星/冲出生死线[BD中英双字1280x720高清版]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}红场特警/红色警探/魔鬼红星/冲出生死线[BD中英双字1280x720高清版]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2009-11-19{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://3e:3e@www2.eee4.com:896/[3E电影站www.eee4.cn]红场特警BD中英双字1280x720高清版.rmvb" target="_blank{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MQ31b10-3PU.jpg{/dede:field}
