<?php
$z[0]=Array("field","纵贯线2010台北演唱会：终点站[B",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","纵贯线2010台北演唱会：终点站[BD国语中字1024x576高清版]迅雷下载、免费下载，纵贯线2010台北演唱会：终点站[BD国语中字1024x576高清版]Gvod高清在线播放，剧情介绍等。",73,275);
$z[1][4]['name']="description";
$z[2]=Array("field","纵贯线2010台北演唱会：终点站[BD国语中字1024x576高清版]",277,369);
$z[2][4]['name']="title";
$z[3]=Array("field","",371,410);
$z[3][4]['name']="writer";
$z[4]=Array("field","",412,451);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-01-22",453,503);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",505,542);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://3e:3e@d3.3edyy.com:121/【3E电影院www.eee4.org】纵贯线2010台北演唱会：终点站.1024x576.国语中字.mkv\" target=_blank>ftftp://3e:3e@d3.3edyy.com:121/【3E电影院www.eee4.org】纵贯线2010台北演唱会：终点站.1024x576.国语中字.mkv</A></TD></TR></TBODY></TABLE></div><ul class=\"mmlist",544,860);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MQ463140-2YT.jpg",862,944);
$z[8][4]['name']="litpic";

?>