{dede:field name='keywords'}投名状BD国粤双语中字1280高清迅{/dede:field}
{dede:field name='description'}投名状BD国粤双语中字1280高清迅雷下载、免费下载，投名状BD国粤双语中字1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}投名状BD国粤双语中字1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-01{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20111118/15/62564813201111181537574215760881805_000.jpg" style="width: 686px; height: 1024px" /></p>
<p>
	◎译　　名　投名状<br />
	◎片　　名　The Warlords<br />
	◎年　　代　2007<br />
	◎国　　家　中国/中国香港<br />
	◎类　　别　剧情/动作/历史/战争<br />
	◎IMDB评分 7.3/10 (3,685 votes)<br />
	◎IMDB链接 <a href="http://www.imdb.com/title/tt0913968">http://www.imdb.com/title/tt0913968</a><br />
	◎片　　长　125 min<br />
	◎导　　演　陈可辛 Peter Chan<br />
	◎主　　演　李连杰 Jet Li .....庞青云<br />
	　　　　　　刘德华 Andy Lau .....赵二虎<br />
	　　　　　　金城武 Takeshi Kaneshiro .....姜午阳<br />
	　　　　　　徐静蕾 Jinglei Xu .....莲生<br />
	　　　　　　石兆琪 Zhaoqi Shi .....何魁<br />
	　　　　　　王奎荣 Kuirong Wang<br />
	　　　　　　郭晓冬 Xiaodong Guo .....黄文清<br />
	　　　　　　魏宗万 Zongwan Wei<br />
	　　　　　　顾宝明 Gu Baoming</p>
<p>
	◎简　　介</p>
<p>
	　　1870年秋，大哥(李连杰 饰演)一身官服，在城墙顶俯瞰自己的就职典礼舞台；充满理想、胸怀壮志的他，如果没有走上这条不归路，极可能是推翻腐败清庭的新中国革命者之一，创大事业名留青史，可惜&hellip;&hellip;</p>
<p>
	　　两个强盗和一个女人改变了他的一生，造就了他的成功，亦导致他最后的毁灭。这两个强盗是曾跟他矢誓生死与共的结拜兄弟：二哥(刘德华 饰演)和三弟(金城武 饰演)，而那个女人正是二哥的妻子莲生(徐静蕾 饰演)。</p>
<p>
	　　率性而为的二哥，乃一条光明磊落的好汉，在乱世中沦为强盗，带着几百人到处劫掠，他为人盗亦有道，就算打劫也&ldquo;劫七留三&rdquo;，留一条活路给被劫的村民，而劫掠所得就拿来分给和他同住一条山村的良民，所以深得众心。二哥一生人最爱两个人，一个是莲生，一个就是十三岁便跟了他做强盗的三弟，把自小成为孤儿的三弟视如亲弟。</p>
<p>
	　　三弟身上有一种独特的男人魅力，除了狼的野性和杀手的狠冷，更有着少年才有的天真浪漫；因此在他的生命中，同生共死的兄弟情义是他视如生命的永恒感情。自从在打劫太平军粮车的一役中，大哥这个陌生人为替他挡箭而受了伤，令他深感救命的恩情，天生的狂热使然，他对大哥的崇拜竟超过他对二哥的崇拜。</p>
<p>
	　　在二哥等人的山村被清军洗劫，付出伤亡惨重的代价后，三弟极力主张他们三人结拜为兄弟，由大哥带领他们投效清廷，二哥为了不想令三弟失望，也为了不想自己的一班同村兄弟陷入绝境，他不计较个人得失，将首领地位拱手让给大哥。</p>
<p>
	　　作为男人世界中的一个好兄弟，二哥在女人世界中却是一个失败的情人，一个不合格的丈夫，浓烈的大男人热血，令他少了那种迷住女人的浪漫魅力；他的妻子莲生却偏偏又是那种深信一见钟情的浪漫主义者。所以，尽管他当年救出被卖到扬州当雏妓的莲生，尽管他很努力的去关怀莲生，但目不识丁的他就是没有莲生所喜欢的文人书卷气，始终得不到她真心的爱。</p>
<p>
	　　为实现天下没有战争的太平盛世理想，大哥借助以二哥、三弟为首的一班兄弟的力量，成立&ldquo;山字营&rdquo;暂时为清廷效力，原来是要借助攻打太平天国结集军力；但是随着他大权在握，大哥变得越来越野心勃勃，令他要清除一切的障碍。他不惜和二哥决裂，屠杀被二哥劝降的太平军降兵，只为怕降兵造反。他利用三弟的狂热性格，说服他站向自己那一边。</p>
<p>
	　　本来，大哥距离成功已仅有一步之遥，但他的作为伤透了对他崇拜不已的三弟。就在就职大典上，就在权势如日中天的最辉煌时刻，大哥竟横死于刺客之手&hellip;</p>
<p>
	&nbsp;<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20111119/08/62564813201111190809551992741114356_004.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20111119/08/62564813201111190809551992741114356_003.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20111119/08/62564813201111190809551992741114356_002.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20111119/08/62564813201111190809551992741114356_001.jpg" style="width: 720px; height: 405px" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="&#13;&#10;ftp://dy125:piaohua@dy125.piaohua.com:7196/飘花电影piaohua.com投名状BD国语中字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:7196/飘花电影piaohua.com投名状BD国语中字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3330/飘花电影piaohua.com投名状BD国粤双语中字1280高清.mkv">ftp://dy44:piaohua@dy44.piaohua.com:3330/飘花电影piaohua.com投名状BD国粤双语中字1280高清.mkv</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1564R50-2CJ.jpg{/dede:field}
