{dede:field name='keywords'}2007年度十大劲歌金曲颁奖典礼迅{/dede:field}
{dede:field name='description'}2007年度十大劲歌金曲颁奖典礼迅雷下载、免费下载，2007年度十大劲歌金曲颁奖典礼Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}2007年度十大劲歌金曲颁奖典礼{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2008-01-14{/dede:field}
{dede:field name='body'}<P>【节目名称】《2007年度十大劲歌金曲颁奖典礼》<BR>【举行日期】2008年1月12日 <BR>【地&nbsp;&nbsp;&nbsp; 点】香港红磡体育馆 <BR>【时&nbsp;&nbsp;&nbsp; 间】8:30 p.m <BR>【电影来源】3E迅雷电影下载站(www.eee4.com)<BR>【文件大小】1CD 684MB<BR>【主办单位】香港无线电视广播有限公司 <BR>【转播媒体】无线电视翡翠台/高清翡翠台[现场直播] <BR>【直播时间】当晚8:30 p.m </P>
<P>【内容简介】：</P>
<P>&nbsp;&nbsp;&nbsp; 2007年度乐坛成绩的第三张成绩表,每年四大电子传媒颁奖礼里面是非最多,</P>
<P>&nbsp;&nbsp;&nbsp; 奖项机制最不透明,赛果最具争议的一个颁奖典礼,</P>
<P>&nbsp;&nbsp;&nbsp; 今年又给各大唱片公司和乐坛带来甚么冲击或者是惊喜?</P>
<P>&nbsp;&nbsp;&nbsp; 赛果又是否内定? 电影来源：www.eee4.com</P>
<P><IMG src="http://pic.piaohua.com/0701pic/allimg/080114/0320320.jpg"><BR><BR>&nbsp;&nbsp; TVB的2007年度十大劲歌金曲颁奖典礼于1月12日红馆圆满结束, 由赛果一如所料由陈奕迅及容祖儿夺得最受欢迎男女歌手, 陈奕迅更一人夺四奖, 包括亚太区最受欢迎男歌手。 亚太区最受欢迎女歌手由于陈慧琳一早宣报不拿奖, 出乎意料外由Twins夺得, 领奖时二人在台上狂哭。金曲金奖则由李克勤的花落谁家夺得。 </P>
<P>【附】：电影来源：www.eee4.com</P>
<P>《2007年度十大劲歌金曲颁奖典礼获奖名单》&nbsp; 电影来源：www.eee4.com<BR>&nbsp;&nbsp;&nbsp; 十大劲歌金曲奖</P>
<P>&nbsp;&nbsp;&nbsp; 张敬轩《酷爱》<BR>&nbsp;&nbsp;&nbsp; 吴雨霏《逼得太紧》<BR>&nbsp;&nbsp;&nbsp; 陈奕迅《富士山下》<BR>&nbsp;&nbsp;&nbsp; 杨千嬅《化》<BR>&nbsp;&nbsp;&nbsp; 李克勤《花落谁家》<BR>&nbsp;&nbsp;&nbsp; 古巨基《爱回家》<BR>&nbsp;&nbsp;&nbsp; 容祖儿《零时零分》<BR>&nbsp;&nbsp;&nbsp; 侧田《男人KTV》<BR>&nbsp;&nbsp;&nbsp; 泳儿《无心恋唱》<BR>&nbsp;&nbsp;&nbsp; 何韵诗《木纹》 </P>
<P>&nbsp;&nbsp;&nbsp; 最佳作曲<BR>&nbsp;&nbsp;&nbsp; 歌曲：富士山下　作曲：Christopher Chak　主唱：陈奕迅 </P>
<P>&nbsp;&nbsp;&nbsp; 最佳填词<BR>&nbsp;&nbsp;&nbsp; 歌曲：富士山下　填词：林夕　主唱：陈奕迅 </P>
<P>&nbsp;&nbsp;&nbsp; 最佳编曲<BR>&nbsp;&nbsp;&nbsp; 歌曲：富士山下　编曲：陈珀、C.Y. Kong　主唱：陈奕迅 </P>
<P>&nbsp;&nbsp;&nbsp; 最佳歌曲监制<BR>&nbsp;&nbsp;&nbsp; 歌曲：富士山下　监制：Alvin Leong　主唱：陈奕迅 </P>
<P>&nbsp;&nbsp;&nbsp; 最受欢迎华语歌曲奖<BR>&nbsp;&nbsp;&nbsp; 金奖：容祖儿《小小》<BR>&nbsp;&nbsp;&nbsp; 银奖：陈奕迅《淘汰》<BR>&nbsp;&nbsp;&nbsp; 铜奖：方大同、薛凯琪《四人游》 </P>
<P>&nbsp;&nbsp;&nbsp; 最受欢迎广告歌曲大奖<BR>&nbsp;&nbsp;&nbsp; 金奖：容祖儿《心花怒放》<BR>&nbsp;&nbsp;&nbsp; 银奖：陈柏宇《永久保存》<BR>&nbsp;&nbsp;&nbsp; 铜奖：HotCha《你的味道》 </P>
<P>&nbsp;&nbsp;&nbsp; 四台联颁音乐大奖－歌曲奖<BR>&nbsp;&nbsp;&nbsp; 歌曲：花落谁家　主唱：李克勤　作曲：Eric Kwok　填词：林若宁 </P>
<P>&nbsp;&nbsp;&nbsp; 最受欢迎组合奖<BR>&nbsp;&nbsp;&nbsp; 金奖：Twins　银奖：EO2　铜奖：HotCha </P>
<P>&nbsp;&nbsp;&nbsp; 2007年度杰出表现奖<BR>&nbsp;&nbsp;&nbsp; 金奖：张敬轩　银奖：关心妍　铜奖：邓健泓 </P>
<P>&nbsp;&nbsp;&nbsp; 新人荐场飙星奖：小肥 </P>
<P>&nbsp;&nbsp;&nbsp; 最受欢迎新人奖(男新人)<BR>&nbsp;&nbsp;&nbsp; 金奖：林峰　银奖：陈柏宇　铜奖：洪卓立 </P>
<P>&nbsp;&nbsp;&nbsp; 最受欢迎新人奖(女新人)<BR>&nbsp;&nbsp;&nbsp; 金奖：江若琳　银奖：裕美　铜奖：钟舒漫 </P>
<P>&nbsp;&nbsp;&nbsp; 最受欢迎唱作歌星<BR>&nbsp;&nbsp;&nbsp; 金奖：王菀之　银奖：孙耀威　铜奖：张继聪 </P>
<P>&nbsp;&nbsp;&nbsp; 最受欢迎女歌星：容祖儿 </P>
<P>&nbsp;&nbsp;&nbsp; 最受欢迎男歌星：陈奕迅 </P>
<P>&nbsp;&nbsp;&nbsp; 亚太区最受欢迎香港女歌星：Twins </P>
<P>&nbsp;&nbsp;&nbsp; 亚太区最受欢迎香港男歌星：陈奕迅 </P>
<P>&nbsp;&nbsp;&nbsp; 金曲金奖：李克勤《花落谁家》</P>
<P><IMG src="http://pic.piaohua.com/0701pic/allimg/080114/0320321.jpg"></P>
<P>2008-01-14 03:18:12 开始连接......<BR>2008-01-14 03:18:14 开始搜索候选资源......<BR>2008-01-14 03:18:15 搜索到31个候选资源<BR>2008-01-14 03:18:17 使用候选资源进行连接......<BR>2008-01-14 03:18:20 搜索到26个候选资源<BR>2008-01-14 03:18:23 使用候选资源进行连接......<BR>2008-01-14 03:18:24 文件创建成功，开始下载数据......<BR>2008-01-14 03:18:26 用户取消下载&nbsp;&nbsp; 本文来自 <A href="/index.html" target=_blank>www.eee4.com</A></P>（直接可能无法下载，一律使用<A href="http://pstatic.xunlei.com/about/product/down_xl5.htm" target=_blank>迅雷下载</A>）<BR>《2007年度十大劲歌金曲颁奖典礼》2008年1月12日 － 来自[3E迅雷电影站eee4.com]下载地址：<IMG src="/templets/img/down.jpg" border=0><BR>
<TABLE style="BORDER-RIGHT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; BORDER-BOTTOM: #cccccc 1px dotted" cellSpacing=0 cellPadding=6 width="95%" align=center border=0>
<TBODY>
<TR>
<TD style="WORD-WRAP: break-word" bgColor=#fdfddf><ANCHOR></ANCHOR><A href="ftp://eee4.com:eee4@xl3.eee4.com:8448/[3E迅雷电影站www.eee4.com]2007年度十大劲歌金曲颁奖典礼080112.rmvb" target=_blank>ftp://eee4.com:eee4@xl3.eee4.com:8448/[3E迅雷电影站www.eee4.com]2007年度十大劲歌金曲颁奖典礼080112.rmvb</A></TD></TR></TBODY></TABLE>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1612Q40-241E.jpg{/dede:field}
