{dede:field name='keywords'}枪王之王[DVD国语中字]迅雷下载{/dede:field}
{dede:field name='description'}枪王之王[DVD国语中字]迅雷下载、免费下载，枪王之王[DVD国语中字]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}枪王之王[DVD国语中字]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2010-07-08{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://6e:6e@m1.eee4.cc:1506/【3e电影网www.eee4.cc】枪王之王DVD国语中字.rmvb" target=_blank>ftftp://6e:6e@m1.eee4.cc:1506/【3e电影网www.eee4.cc】枪王之王DVD国语中字.rmvb</A></TD></TR></TBODY></TABLE></div><ul class="mmlist{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MP315250-4JX.jpg{/dede:field}
