{dede:field name='keywords'}世界尽头的奇遇【中英双字[880分{/dede:field}
{dede:field name='description'}世界尽头的奇遇【中英双字[880分辨率]】迅雷下载、免费下载，世界尽头的奇遇【中英双字[880分辨率]】Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}世界尽头的奇遇【中英双字[880分辨率]】{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-22{/dede:field}
{dede:field name='body'}<p>
	◎译　　名　《世界尽头的奇遇》08精彩记录片BD中英双字[880分辨率]<br />
	◎片　　名　Encounters At The End Of The World<br />
	◎年　　代　2008<br />
	◎国　　家　美国<br />
	◎类　　别　记录<br />
	◎语　　言　英语<br />
	◎字　　幕　中英双字<br />
	◎IMDB评分 7.9/10&nbsp; 1,793 votes<br />
	◎IMDB链接：<a href="http://www.bluemv.com">http://www.bluemv.com</a><br />
	◎文件格式　XviD + MP3<br />
	◎视频尺寸　880 x 492<br />
	◎文件大小　1CD<br />
	◎片　　长　99 min<br />
	◎导　　演　沃纳&middot;赫尔佐格 Werner Herzog<br />
	◎主　　演　Ryan Andrew Evans ...&nbsp; Himself - Production Cook<br />
	　　　　　　Werner Herzog ...&nbsp; Narrator<br />
	<br />
	◎简　　介　<br />
	<br />
	<br />
	　　赫尔佐格这次前往位于罗斯岛的麦克默多站进行拍摄，那里是南极洲最大的科学研究中心，由美国国家科学基金会南极计划部门运作。他们的多数居民（夏季大概能达到1100人左右）并不是科学家，而是作业、后勤、IT和维护等方面提供支援的成员。某种程度上可以说，他们的目的并不在于科研，而在于体验。除了麦克默多站的生活，赫尔佐格还拍摄了很多南极洲的壮丽景色，让人们领略到这块神奇大陆上的风光&hellip;&hellip;</p>
<p>
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://images.dvdempire.com/gen/movies/1424392h.jpg');" src="http://images.dvdempire.com/gen/movies/1424392h.jpg" /><br />
	<br />
	◎剧　　照　<br />
	<br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://farm4.static.flickr.com/3272/2569660506_5fb875db30_o.jpg');" src="http://farm4.static.flickr.com/3272/2569660506_5fb875db30_o.jpg" /><br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://farm4.static.flickr.com/3008/2569660512_fa52b08be3_o.jpg');" src="http://farm4.static.flickr.com/3008/2569660512_fa52b08be3_o.jpg" /><br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://farm4.static.flickr.com/3120/2569660514_7a513c38b7_o.jpg');" src="http://farm4.static.flickr.com/3120/2569660514_7a513c38b7_o.jpg" /><br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://farm4.static.flickr.com/3171/2569660516_933f56fd97_o.jpg');" src="http://farm4.static.flickr.com/3171/2569660516_933f56fd97_o.jpg" /><br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://farm4.static.flickr.com/3263/2569660520_b7088d24f3_o.jpg');" src="http://farm4.static.flickr.com/3263/2569660520_b7088d24f3_o.jpg" /><br />
	<br />
	<b>影片截图：</b><br />
	<br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://img.album.pchome.net/54/68/69/32/25be277c256a5e9439f92d9ab7ce32c9.jpg');" src="http://img.album.pchome.net/54/68/69/32/25be277c256a5e9439f92d9ab7ce32c9.jpg" />&nbsp;<br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://img.album.pchome.net/54/68/69/32/1b6fff4f925c73497fabb48ea2920eb0.jpg');" src="http://img.album.pchome.net/54/68/69/32/1b6fff4f925c73497fabb48ea2920eb0.jpg" />&nbsp;<br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://img.album.pchome.net/54/68/69/32/363b32e582b335fbf6adf0f19735e109.jpg');" src="http://img.album.pchome.net/54/68/69/32/363b32e582b335fbf6adf0f19735e109.jpg" /></p>
<p>
	2009-02-05 18:3212 开始连接......<br />
	2009-02-05 18:3212 开始搜索候选资源......<br />
	2009-02-05 18:3212 搜索到22个候选资源<br />
	2009-02-05 18:3212 使用候选资源进行连接......<br />
	2009-02-05 18:3213 搜索到41个候选资源<br />
	2009-02-05 18:3213 使用候选资源进行连接......<br />
	2009-02-05 18:3213 文件创建成功，开始下载数据......<br />
	2009-02-05 18:3216 用户取消下载&nbsp;&nbsp; 本文来自：www.eee4.com</p>
<p>
	（一律使用<a href="http://www.eee4.com/soft.htm" target="_blank">迅雷下载</a>）<br />
	08精彩记录片《世界尽头的奇遇》BD中英双字[880分辨率] －来自[3E电影站 eee4.com]：<img border="0" src="http://www.eee4.com/templets/img/down.jpg" /></p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://e39:e39@xl2.eee4.com:9024/[3E电影站www.eee4.com]世界尽头的奇遇.rmvb" target="_blank">ftp://e39:e39@xl2.eee4.com:9024/[3E电影站www.eee4.com]世界尽头的奇遇.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O161Cb0-24U1.jpg{/dede:field}
