{dede:field name='keywords'}李俊基-只有一句话迅雷下载，免{/dede:field}
{dede:field name='description'}李俊基-只有一句话迅雷下载、免费下载，李俊基-只有一句话Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}李俊基-只有一句话{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2006-09-14{/dede:field}
{dede:field name='body'}<p><embed name="MediaPlayer" pluginspage="http://www.microsoft.com/isapi/redir.dll?prd=windows&amp;sbp=mediaplayer&amp;ar=media&amp;sba=plugin&amp;" align="6" src="http://fmtv.uying.com/200606/0618/李俊基-只有一句话.wmv" width="350" height="300" type="application/x-mplayer2" defaultframe="datawindow" invokeurls="1" clicktoplay="0" enablecontextmenu="1" allowscan="1" transparentatstart="0" animationatstart="0" autorewind="0" autostart="1" showcaptioning="0" showgotobar="0" autosize="0" showstatusbar="1" showdisplay="0" showtracker="1" showaudiocontrols="1" showpositioncontrols="0" showcontrols="1" border="0"></embed>&nbsp;</p>
<p>http://fmtv.uying.com/200606/0618/李俊基-只有一句话.wmv</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120524/133N353DD0-2G248.gif{/dede:field}
