{dede:field name='keywords'}追逐繁星的孩子BD中字2011动画迅{/dede:field}
{dede:field name='description'}追逐繁星的孩子BD中字2011动画迅雷下载、免费下载，追逐繁星的孩子BD中字2011动画Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}追逐繁星的孩子BD中字2011动画{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-12-01{/dede:field}
{dede:field name='body'}<p>
	<img src="/uploads/allimg/c120525/133O04393110-2362Z.jpg" /></p>
<p>
	<img alt="" src="/uploads/allimg/c120525/133O04394530-243619.jpg" /></p>
<p>
	《追逐繁星的孩子》的故事而已确认为将会环绕著女主角明日菜而进行。自从与父亲离别后，明日菜便一直过著孤独寂寞的生活。有一天，透过从她爸爸留给她的水晶收音机遗物中，突然传出了不可思议的音乐，这首不可思议的音乐同时改变了她的日常生活。明日菜决定追寻著这把来自远方的声音而展开了新的冒险之旅，只为了再与一个生活在异国的男孩再聚。透过这次的旅程，明日菜将会认识到这个世界的美丽与残酷，同时也将会体验失去的真正意义。</p>
<p>
	新电影的故事就如新海诚之前描述般，将会以一名少女为主角，一名开朗、有乐观精神的少女将展开一场包含了动作、恋爱等丰富元素的冒险故事。而且和他以往的作品不同，《追逐繁星的孩子》不会再只著重于描写失去挚爱的主角，而是希望把这主题往前一推，为大家呈现出明日菜在失去了挚爱之后将会如何去克服，将如何去治愈心灵的创伤。</p>
<p>
	<br />
	人物介绍：</p>
<p>
	<br />
	渡赖明日菜（アスナ）<br />
	CV：金元寿子（かねもと ひさこ）<br />
	十一岁 。年幼的时候父亲去世 ，和母亲一起生活在山间的小镇上。擅长做菜，经常做好便当带到秘密基地去。好动，认真但又有些靠不住，和班里的同学相处的不太好。和瞬的相识也让她体会到失去重要的人的感受，为了能再次见到瞬，她开始了去往阿加尔塔的旅行。在结局时，因为和森崎以及真分开，感受到了无处可去的孤独感，但是她变得勇于面对。</p>
<p>
	<br />
	瞬&middot; 库阿农 &middot;布拉爱瑟斯（シュン ）<br />
	CV：入野自由（いりの みゆ）<br />
	幼时失去双亲，和真一起在加农村被抚养长大。性格稳重温柔，对地上的世界充满憧憬。从而打破规矩带着格拉维斯的能力，救下了被阿加尔塔的门卫茨阿鲁特鲁袭击的明日菜，并告诉她因为有无论如何都想见到的人和物所以才来到这个世界，因此和明日菜交心。</p>
<p>
	<br />
	真&middot; 库阿农&middot; 布拉爱瑟斯（シン）<br />
	CV：入野自由（いりの みゆ）<br />
	在阿加尔塔长大的少年。瞬的双生兄弟。为了回收哥哥留下的格拉维斯来到了地球，和明日菜相遇。率直，行动快于思考。有些爱钻牛角尖。和明日菜相比有时很极端，但是性格正直。自加农村的长老接到从地上人手中回收格拉维斯的命令一门心思想要完成任务。</p>
<p>
	<br />
	森崎竜司（モリサキ）<br />
	CV：井上和彦（いのうえ かずひこ）<br />
	明日菜学校的新老师。为了和十年前去世的妻子丽莎再见，他一直在寻找可以实现所有愿望的阿加尔塔。他是知晓阿加尔塔的组织，大天使的一员。他以可以复活死者的生死之门为目标想阿加尔塔前进了。总是很冷静，为了达到目的利用组织和明日菜。将心牢牢地封闭着。但是在旅途中渐渐地向明日菜敞开心扉。</p>
<p>
	丽莎<br />
	CV：岛本须美<br />
	森崎十年前去世的妻子。原本就体弱多病，在森..</p>
<p>
	<img border="0" src="/uploads/allimg/c120525/133O043950F-25aT.jpg" /></p>
<p>
	<img border="0" src="/uploads/allimg/c120525/133O0439A50-2EN6.jpg" /></p>
<p>
	<img border="0" src="/uploads/allimg/c120525/133O043aI0-2L558.jpg" /></p>
<p>
	<img border="0" src="/uploads/allimg/c120525/133O043b950-2Y344.jpg" /></p>

<p>
	[下载地址]： &nbsp;<img border="0" src="/uploads/allimg/c120524/133N2Z4FF-102231.jpg" /></p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				&nbsp;ftp://dy44:piaohua@dy44.piaohua.com:2208/飘花电影piaohua.com追逐繁星的孩子DVD中字.rmvb </td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O04400150-295I7.jpg{/dede:field}
