<?php
$z[0]=Array("field","成龙的特技迅雷下载，免费下载，",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","成龙的特技迅雷下载、免费下载，成龙的特技Gvod高清在线播放，剧情介绍等。",73,187);
$z[1][4]['name']="description";
$z[2]=Array("field","成龙的特技",189,237);
$z[2][4]['name']="title";
$z[3]=Array("field","",239,278);
$z[3][4]['name']="writer";
$z[4]=Array("field","",280,319);
$z[4][4]['name']="source";
$z[5]=Array("field","2008-01-09",321,371);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",373,410);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://eee4.com:eee4@xl3.eee4.com:8448/成龙的特技DVD/[3E迅雷电影站www.eee4.com]成龙的特技DVD.rmvb\" target=_blank>ftftp://eee4.com:eee4@xl3.eee4.com:8448/成龙的特技DVD/[3E迅雷电影站www.eee4.com]成龙的特技DVD.rmvb</A></TD></TR></TBODY></TABLE></div><ul class=\"mmlist",412,714);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MP440640-1G94.jpg",716,799);
$z[8][4]['name']="litpic";

?>