{dede:field name='keywords'}燃烧弹BD中英双字1024/1280高清{/dede:field}
{dede:field name='description'}燃烧弹BD中英双字1024/1280高清迅雷下载、免费下载，燃烧弹BD中英双字1024/1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}燃烧弹BD中英双字1024/1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-04-26{/dede:field}
{dede:field name='body'}<p>
	<img alt="" border="0" onload="attachimg(this, 'load')" src="http://img.album.pchome.net/54/68/85/60/9202262e36a8e81e0de00a35a32e21c3.jpg" /></p>
<p>
	◎译　　名　《燃烧弹》08年英国惊悚剧情DVD中英双字1024x576高清版<br />
	◎片　　名　Incendiary<br />
	◎年　　代　2008<br />
	◎国　　家　英国<br />
	◎类　　别　剧情/爱情/惊悚<br />
	◎语　　言　英语<br />
	◎字　　幕　中英文<br />
	◎IMDB评分 7.2/10 235 votes<br />
	◎IMDB链接 http://www.imdb.com/title/tt0984200<br />
	◎文件格式　DVDrip-RMVB<br />
	◎视频尺寸　640 x 272 / 1024 x 576<br />
	◎文件大小　1CD<br />
	◎片　　长　01:35:58<br />
	◎导　　演　沙朗&middot;马奎尔 Sharon Maguire<br />
	◎主　　演　米歇尔&middot;威廉姆斯 Michelle Williams<br />
	　　　　　　伊万&middot;麦克格雷格 Ewan McGregor<br />
	　　　　　　马修&middot;麦克费登 Matthew Macfadyen<br />
	　　　　　　Sidney Johnston ....The Boy<br />
	　　　　　　Nicholas Courtney ....Archbishop of Canterbury<br />
	　　　　　　Enzo Squillino Jr. ....Newsagent<br />
	　　　　　　Nicholas Gleaves ....Young Father<br />
	　　　　　　Sasha Behar ....Woman in hijab<br />
	　　　　　　Chris Mansfield ....Police Officer<br />
	　　　　　　Michael Thompson<br />
	　　　　　　Ricci McLeod<br />
	　　　　　　Gavin Brocker ....Detective Tony Jackson<br />
	　　　　　　Robin Berry ....Dazed Supporter<br />
	　　　　　　Brian Meggs ....Supporter<br />
	　　　　　　Joe Marshall ....Gary<br />
	　　　　　　Tola ....Football Player / Supporter<br />
	　　　　　　Edward Hughes ....Danny Walsh<br />
	　　　　　　Benjamin Wilkin ....Policeman<br />
	　　　　　　Thomas Meggs ....Supporter<br />
	　　　　　　Monty Fromant ....Security Guard<br />
	　　　　　　Satu Suominen<br />
	　　　　　　Julie Rochford ....Dazed Supporter<br />
	　　　　　　Jonathan Andrews ....Policeman<br />
	　　　　　　Simon Wilson ....Commuter on train<br />
	　　　　　　Ehti Aslam<br />
	　　　　　　Chris Ellis ....The Dead Son<br />
	　　　　　　Usman Khokhar ....Bomber&#39;s Son<br />
	　　　　　　Christopher Wilson ....CO19 Officer<br />
	<br />
	◎简　　介　<br />
	<br />
	本片从一个私生活混乱的漂亮妈妈的角度，讲述了恐怖主义带给普通人的伤痛。米歇尔&middot;威廉姆斯饰演的女主角（本片中她没有名字）和5岁的儿子、身为拆弹专家的丈夫生活在伦敦。她的生活看似完美但这一切都只是假象。<br />
	<br />
	<br />
	只因为米歇尔&middot;威廉姆斯是个坏女孩，婚姻的激情在她那已经荡然无存，她喜欢穿着短裙流连于各种俱乐部中间，当丈夫去执行拆弹任务时，她肆无忌惮的将男人带回家过夜。一天，她遇见了年轻帅气的加斯帕&middot;布莱克（伊万&middot;麦克格雷格　饰），当他们做爱正酣之际，电视中恐怖分子自杀式<a href="http://www.eee4.com/" target="_blank">电影下载</a>袭击足球场的新闻打断了他们&mdash;&mdash;米歇尔的丈夫和孩子都在里面&hellip;&hellip;</p>


<p>
	【电影截图】：<br />
	<br />
	<a href="http://img.album.pchome.net/54/70/21/51/ba02fea075ece89ae1fa8803d43db63c.jpg" target="_blank"><img src="http://img.album.pchome.net/54/70/21/51/ba02fea075ece89ae1fa8803d43db63c.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 338px; border-top: 0px solid; border-right: 0px solid" /></a>&nbsp;<br />
	<a href="http://img.album.pchome.net/54/70/21/51/9798552eb1443c935350bc530b2f50bf.jpg" target="_blank"><img src="http://img.album.pchome.net/54/70/21/51/9798552eb1443c935350bc530b2f50bf.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 338px; border-top: 0px solid; border-right: 0px solid" /></a></p>
<p>
	08年英国惊悚剧情《燃烧弹》DVD中英双字1024x576高清版 [下载地址]：<img border="0" src="http://www.eee4.com/templets/img/down.jpg" />
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://3e:3e@www2.eee4.com:315/[3E电影站www.eee4.com]燃烧弹DVD中英双字1024x576高清版.rmvb" target="_blank">ftp://3e:3e@www2.eee4.com:315/[3E电影站www.eee4.com]燃烧弹DVD中英双字1024x576高清版.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3296/飘花电影piaohua.com燃烧弹BD中英双字1280高清.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3296/飘花电影piaohua.com燃烧弹BD中英双字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://e26:e26@xl2.eee4.com:9219/[3E电影站www.eee4.com]燃烧弹.rmvb" target="_blank">ftp://e26:e26@xl2.eee4.com:9219/[3E电影站www.eee4.com]燃烧弹.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O160I10-334L.jpg{/dede:field}
