{dede:field name='keywords'}海底世界1024高清双语字幕美国]{/dede:field}
{dede:field name='description'}海底世界1024高清双语字幕美国]纪录迅雷下载、免费下载，海底世界1024高清双语字幕美国]纪录Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}海底世界1024高清双语字幕美国]纪录{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-09-11{/dede:field}
{dede:field name='body'}<p>
	&nbsp;<img border="0" src="/uploads/allimg/c120524/133N42H04Z-255012.jpg" style="max-width: 750px; max-height: 750px" /></p>
<p>
	◎译　　名　IMAX海底世界/海底世界2D<br />
	◎片　　名　Under the Sea<br />
	◎年　　代　2009<br />
	◎国　　家　美国/加拿大<br />
	◎类　　别　纪录片<br />
	◎语　　言　英语<br />
	◎字　　幕　中英双语字幕<br />
	◎IMDB评分 7.5/10 (176 votes)<br />
	◎IMDB链接 http://www.imdb.com/title/tt1020876/<br />
	◎文件格式　X264 + AC3<br />
	◎视频尺寸　1024x576<br />
	◎文件大小　696MB<br />
	◎片　　长　40 mins<br />
	◎导　　演　豪沃得&middot;豪尔 Howard Hall<br />
	◎主　　演　金&middot;凯瑞 Jim Carrey ....Narrator</p>
<p>
	◎2D版本</p>
<p>
	◎简　　介　</p>
<p>
	　　这部纪录片向我们展示了不同海域的不同风景，并探究了全球变暖对海洋的影响。</p>
<p>
	　　可以把《海底世界3D》看成是在2006年大获成功的3D纪录片《深海世界3D》的续集，这一次，水下摄影师们下潜到南澳大利亚和巴布亚新几内亚以及印度洋海域，拍摄到海洋中形形色色的珍奇生物，其中很多还是第一次被人类拍到，这部纪录片实际上是要告诉我们全球变暖对海洋生物圈的影响。</p>
<p>
	幕后制作</p>
<p>
	　　《海底世界3D》是华纳兄弟电影公司发行的第三部IMAX电影。这部纪录片也是华纳兄弟与总部设在加拿大的IMAX公司共同制作完成的。&ldquo;这部电影让我们异常兴奋&rdquo;，华纳兄弟的总裁兼首席运营官阿兰&middot;霍恩说：&ldquo;这部影片拍到的很多深海生物都是第一次被人类看到，除此之外，《海底世界3D》还认真地探索了全球气候变暖对海洋以及海洋生物的影响。能成为这部有足够魅力启迪和吸引观众的影片的出品方，我们非常自豪。&rdquo;</p>
<p>
	　　&ldquo;我们是在这部影片已经开拍的情况下加入的，这令我们非常激动，我们也为华纳的原创3DIMAX电影库的到扩充而感到高兴，尤其是这片子出自极有才干的《深海世界3D》的制作团队之手&rdquo;，华纳兄弟的国内发行部主席丹&middot;菲尔曼也有同感：&ldquo;即便现在，影迷仍在买票看《深海世界3D》，这也证明了把海洋题材和IMAX形式相加放在一起可以产生强大吸引力。&rdquo;</p>
<p>
	《海底世界3D》在很多方面都延续了上映于2006年的《深海世界3D》，那部影片的全球票房高达6000万，对一部纪录片来说，这是个惊人的数字，而且影片全部票房的40%以上来自IMAX影厅。令人称奇的是，《深海世界3D》在上映了100周之后还留在电影院里，仍不断有票房进账，这也证明了原创3DIMAX电影也能有极佳的口碑和强大的吸引力，这对建立起世界各地的放映商的信心来说极为重要。</p>
<p>
	　　&ldquo;年复一年，《深海世界3D》都在带给观众无与伦比的视觉体验，把更多的影迷拉到电影院里，所以我们希望能再来一部《深海世界3D》&rdquo;，IMAX制作娱乐公司主席、总裁格雷格&middot;福斯特说：&ldquo;结果我们遇到了老伙计，这真神奇，我们和华纳兄弟再次合作，我们有了电影业里最令人尊敬的拍摄团队。&rdquo;</p>
<p>
	【影片主创】</p>
<p>
	　　《海底世界3D》的导演是霍华德&middot;豪尔，他还兼任影片的摄影师，当然，对一部纪录片来说，导演和摄影师两职经常是合而为一的。霍华德&middot;豪尔曾在2006以《深海世界3D》获得了巨幕电影组织颁发的电影成就奖。《海底世界3D》的制片人是托尼&middot;梅尔斯，他的兼职更多，包括剪辑师和编剧，影片的执行制片人是格里姆&middot;弗格森。</p>
<p>
	　　三年前的那部《深海世界3D》就是出自这个三人组之手。实际上，早在1991年，三人组已经拍摄了第一部3DIMAX水下冒险纪录片《深海探奇》，那部影片的总票房更有7000万之多。值得一提的还有影片的解说，那就是喜剧明星金&middot;凯瑞，这显然对于影片的宣传相当有利。四年前，法国纪录片《帝企鹅日记》的英文版就找了摩根&middot;弗里曼解说，看来发行公司也知道，就连纪录片也需要借助一点明星效应。</p>
<p>
	◎截　　图</p>
<p>
	<img border="0" src="/uploads/allimg/c120524/133N42H3D0-263a0.jpg" style="max-width: 750px; max-height: 750px" /></p>
<p>
	<img border="0" src="/uploads/allimg/c120524/133N42HX60-2I526.jpg" style="max-width: 750px; max-height: 750px" /></p>
<p>
	<img border="0" src="/uploads/allimg/c120524/133N42I0Z-2Q0a.jpg" style="max-width: 750px; max-height: 750px" /></p>
<p>
	[下载地址]： &nbsp;<img border="0" src="/uploads/allimg/c120524/133N2Z4FF-102231.jpg" />
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				&nbsp;&nbsp;ftp://dy44:piaohua@dy44.piaohua.com:1521/飘花电影piaohua.com海底世界1024高清双语字幕.mkv</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120524/133N42I3540-2a392.jpg{/dede:field}
