{dede:field name='keywords'}智取威虎山高清HD版国语2011最新{/dede:field}
{dede:field name='description'}智取威虎山高清HD版国语2011最新上映中国动画历史大片迅雷下载、免费下载，智取威虎山高清HD版国语2011最新上映中国动画历史大片Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}智取威虎山高清HD版国语2011最新上映中国动画历史大片{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-01-03{/dede:field}
{dede:field name='body'}<p>
	<img src="/uploads/allimg/c120525/133O0431J40-15607.jpg" /></p>
<p>
	<img src="/uploads/allimg/c120525/133O0431W60-25645.jpg" /></p>
<p>
	片名: 智取威虎山<br />
	导演: 陈志宏<br />
	主演: 李扬<br />
	类型: 历史 / 动画<br />
	制片国家/地区: 中国大陆<br />
	语言: 汉语普通话<br />
	上映日期: 2011-12-30(中国大陆)<br />
	片长: 85分钟<br />
	又名: Taking Tiger Montain By Strategy</p>
<p>
	<br />
	剧情简介</p>
<p>
	　　解放军剿匪小分队在团参谋长少剑波的带领下，依靠地势绕过十八台天险，从鹰嘴山顶横越奶头山，奇袭匪巢。土匪小头目栾平趁乱仓皇出逃，侦察英雄杨子荣及时发现蛛丝马迹，在小松鼠&ldquo;大尾巴&rdquo;的帮助下，追踪抓获了栾平。<br />
	　　奶头山剿匪大获全胜。小分队的下一个剿匪目标是威虎山的顽匪座山雕。少剑波经过缜密思考，制定了新的作战计划。杨子荣受命化装成奶头山的漏网土匪，循着小分队故意放走的威虎山探子的足迹，进入莽莽丛林，迷途中勇斗猛虎。枪声引来了入山打猎的土匪&mdash;座山雕帐下八大金刚中的麻老六。杨子荣随麻老六进入威虎山匪窝，从容机智地应对座山雕的盘问，并献上了军事联络图。多疑的座山雕虽然留下了杨子荣，但对他仍存戒心。<br />
	　　少剑波在夹皮沟的一系列土改措施和小分队的爱民护民的一言一行让当地老百姓彻底接受了这支人民的军队。座山雕接到命令，制定计划伏击开往夹皮沟的运输火车。<br />
	　　杨子荣佯装打猎，想要偷偷下山把座山雕的计划传递给小分队，差一点因此暴露身份，幸亏&ldquo;大尾巴&rdquo;的过敏反应暴露了跟踪的土匪喽罗的行踪。杨子荣化险为夷，可消息无法传递出去的困境却让他如坐针毡。<br />
	　　故事就此展开&hellip;&hellip;<br />
	　　一本书《林海雪原》、一部戏《智取威虎山》，成为影响了几代中国人成长的红色经典。为了让这部脍炙人口的名篇名段在新的时代焕发出新的魅力，牡丹江新闻传媒集团大鹏盛艺影视动画有限公司买断《林海雪原》的动画电影改编权，与中国规模最大的美术电影制片基地&mdash;&mdash;上海美术电影制片厂联合摄制动画电影《智取威虎山》。　　</p>

<p>
	◎影片截图</p>

<p>
	<img src="/uploads/allimg/c120525/133O0431cZ-35J0.jpg" style="width: 600px; height: 338px" /></p>
<p>
	<img src="/uploads/allimg/c120525/133O04320940-41521.jpg" style="width: 600px; height: 338px" /></p>
<p>
	<img src="/uploads/allimg/c120525/133O04321b0-540M.jpg" style="width: 600px; height: 338px" /></p>
<p>
	<img src="/uploads/allimg/c120525/133O04322940-63038.jpg" style="width: 600px; height: 338px" /></p>
<p>
	[下载地址]： &nbsp;<img border="0" src="/uploads/allimg/c120524/133N2Z4FF-102231.jpg" /></p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				&nbsp;ftp://dy44:piaohua@dy44.piaohua.com:2503/飘花电影piaohua.com智取威虎山高清HD版国语.rmvb</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O04323Z-JS0.jpg{/dede:field}
