{dede:field name='keywords'}大破量子危机BD中英双字1024/128{/dede:field}
{dede:field name='description'}大破量子危机BD中英双字1024/1280高清迅雷下载、免费下载，大破量子危机BD中英双字1024/1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}大破量子危机BD中英双字1024/1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-10-28{/dede:field}
{dede:field name='body'}<p>
	<img alt="" border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://i1.sinaimg.cn/ent/d/2008-10-14/U93P28T3D2205446F326DT20081014185403.jpg');" src="http://i1.sinaimg.cn/ent/d/2008-10-14/U93P28T3D2205446F326DT20081014185403.jpg" /></p>
<p>
	◎译　　名　《007：大破量子危机》08冒险动作大片DVD中英双字1024x560高清版<br />
	◎片　　名　Quantum of Solace<br />
	◎年　　代　2008<br />
	◎国　　家　美国/英国<br />
	◎类　　别　动作/冒险/惊悚<br />
	◎语　　言　英语<br />
	◎字　　幕　中英双字<br />
	◎IMDB评分 7.1/10 (39,902 votes)<br />
	◎文件格式　XviD + MP3<br />
	◎视频尺寸　640 x 272<br />
	◎文件大小　2CD<br />
	◎片　　长　106 min<br />
	◎导　　演　马克&middot;福斯特 Marc Forster<br />
	◎主　　演　丹尼尔&middot;克雷格 Daniel Craig&nbsp; ....James Bond<br />
	　　　　　　欧嘉&middot;柯瑞兰寇 Olga Kurylenko&nbsp; ....Camille<br />
	　　　　　　杰玛&middot;阿特登 Gemma Arterton<br />
	　　　　　　朱迪&middot;丹奇 Judi Dench&nbsp; ....M<br />
	　　　　　　吉安卡罗&middot;吉安尼尼 Giancarlo Giannini&nbsp; ....Rene Mathis<br />
	　　　　　　加斯帕&middot;克里斯滕森 Jesper Christensen&nbsp; ....Mr. White<br />
	　　　　　　马修&middot;阿马立克 Mathieu Amalric&nbsp; ....(rumored)<br />
	　　　　　　杰弗里&middot;怀特 Jeffrey Wright&nbsp; ....Felix Leiter<br />
	　　　　　　Neil Jackson&nbsp; ....Mr. Slate<br />
	　　　　　　Tim Pigott-Smith&nbsp; ....British VIP (rumored)<br />
	　　　　　　乔昆&middot;科西欧 Joaqu&iacute;n Cosio&nbsp; ....General Medrano<br />
	　　　　　　Rory Kinnear&nbsp; ....Bill Tanner<br />
	　　　　　　费尔南多&middot;古林&middot;库弗 Fernando Guill&eacute;n Cuervo<br />
	　　　　　　David Harbour&nbsp; ....(rumored)<br />
	　　　　　　安纳托&middot;陶布曼 Anatole Taubman<br />
	　　　　　　蕾切尔&middot;麦克多瓦尔 Rachel McDowall&nbsp; ....Anna<br />
	　　　　　　Stana Katic&nbsp; ....Corinne Veneau<br />
	　　　　　　奥娜&middot;卓别林 Oona Chaplin&nbsp; ....Hotel Receptionist<br />
	　　　　　　Tracy Redington&nbsp; ....MI6 Agent<br />
	　　　　　　Lucrezia Lante della Rovere&nbsp; ....Gemma<br />
	　　　　　　David Decio&nbsp; ....MI6 Agent (uncredited)<br />
	　　　　　　Eddy Joseph&nbsp; ....M&#39;s Husband (uncredited)<br />
	　　　　　　<br />
	◎简　　介　<br />
	<br />
	　　邦德被他钟情的女子Vesper背叛，开始执行他的一下个任务。经过对一个叫怀特（加斯帕&middot;克里斯滕森饰）的男子的审讯，邦德和顶头上司M女士（仍由朱迪&middot;丹奇扮演）得到了一个曾经勒索过Vesper的犯罪组织的情报，这个组织非常复杂，危害程度超过任何人的想象。<br />
	<br />
	　　另一方面，英国情报人员在对军情六处的一个叛徒进行调查后，无意中发现了一个在海地设立的银行账户。在海地，邦德因为一件诡异的案子，结识了美女Camille。性感的Camille脾气不好，内心被外人所不知的复仇欲控制。<br />
	<br />
	　　通过Camille，邦德接触到一个叫Dominic Greene（马修&middot;阿马立克饰）的商人。他冷酷无情，背后操纵着一个强大的神秘组织。带着这些线索，邦德奔波于奥地利、意大利和南美等地。<br />
	<br />
	　　在调查的旅途中，邦德逐渐发现，Greene正在实施一个惊天动地的阴谋：联手产油国一位已被政府驱逐的Medrano将军（乔昆&middot;科西欧饰），达到全面控制该国一片富藏资源的土地的目的。<br />
	<br />
	　　但Greene是个硬角色，他不仅情报灵通，而且人脉极广，美国中央情报局和英国政府都与他有见不得光的肮脏交易。最为可怕的好似，Greene已向他的合作伙伴们做出推翻产油国当局政权承诺。<br />
	<br />
	　　在随时随地有可能遭遇背叛、谋杀和骗局的情势中，邦德与他在总部的老搭档一道，奋勇过关，逐渐逼近事实真相。而邦德发现，如果想成功破坏Greene的险恶计划，停止他的组织犯罪活动，最终挫败这个惊天阴谋，他不仅要比中央情报局、恐怖分子领先一步，而且在关键时刻，他还必须越过顶头上司M女士，独自行动&hellip;&hellip; </p>
<p>
	<br />
	<br />
	幕后制作<br />
	<br />
	　　丹尼尔&middot;克雷格的再次挑战<br />
	<br />
	　　2006年丹尼尔&middot;克雷格在《007：大战皇家赌场》中首次出演007就一炮而红，此次他再次化身代号007的特工詹姆斯&middot;邦德。他说&ldquo;感觉好像我从未离开剧组似的，这次的筹备时间长一些，在开拍前三个月我就开始为免费电影《007：大破量子危机》<a href="http://www.eee4.com/" target="_blank">迅雷电影下载</a>这部片子做准备。一部007电影就像一部大机器一样，需要很多动能和推动才能启动。圣诞节后我们马上开拍，一切都有条不紊地进行。&rdquo;同时，他对即将进行的拍摄丝毫不敢掉以轻心。&ldquo;我并不觉得这次会轻松一些，感觉甚至更困难。大家对我们有很高的期望，这就像一柄双刃剑，我们必须做到更好。人们都说《皇家赌场》对于邦德是个转折点，所以这一次我们必须再次突破。这次我们有两位重量级人物加盟，一位是马克&middot;福斯特，他擅长以影像讲故事；另一位是丹&middot;布拉德利，他导演了第二部分，他的特技和动作拍摄非常出彩。把他们俩的才能结合起来是我们成功的关键。要想拍摄一部最好的邦德电影，就要网罗最优秀的人才。每个人都很紧张，一想到要创作出一部非同一般的电影都很激动。故事是从上一部片子开始的，但是我们要探索的是全新的东西。马克对这部电影有独特的理解，我对此感到很兴奋。&rdquo;<br />
	<br />
	　　《007：大破量子危机》是詹姆斯&middot;邦德系列电影中的第一部真正的续集电影，克雷格解释道，&ldquo;我们要把《007：大战皇家赌场》中开放的结局收拢，告诉人们我们又回来了。对我来说，这部片子虽然自成一体，但是如果你把两部片子放在一起，就会有难以置信的体验，因为这是一个连贯的故事。&rdquo;<br />
	<br />
	　　尽管过程艰辛，或者正是由于其中的辛苦，克雷格谈起这部电影充满热情滔滔不绝。&ldquo;我对我们的工作感到非常兴奋，我们完成的工作让我都觉得十分惊讶。我们去了那么多外景地，这部电影棒极了，我觉得，事实上，应该说我知道我们创作出了一部非常特别的电影。&rdquo;<br />
	<br />
	　　新邦女郎欧嘉&middot;柯瑞兰寇<br />
	<br />
	　　欧嘉&middot;柯瑞兰寇谈起她在《007：大破量子危机》中的角色，说道：&ldquo;卡米丽是个有着悲惨过去的女孩子，在她小的时候亲眼目睹家人在她眼前被杀害。她经历了很多，也因此变得很坚强。她知道是谁杀了她的家人，她的动力就是复仇。&rdquo;&ldquo;卡米丽聪明、专注并且很有技巧。她有战斗的本领，但同时她也不惧于运用自己的女性魅力。事实上，正是因为她是个女孩子，所以没人怀疑她。&rdquo;<br />
	<br />
	　　&ldquo;当她最初遇到邦德的时候，她甚至都没注意到他的存在，因为她的全部注意力和意志都集中在自己的复仇使命上。但是，逐渐地，她明白他们是在朝同一方向进发，虽然他们的目标并不完全一致。&rdquo;<br />
	<br />
	　　&ldquo;我不认为卡米丽一个典型的邦女郎。她是唯一一位没有和邦德上过床的邦女郎！卡米丽这个角色有很强的个性，她知道自己要什么，她决心已定。&rdquo;</p>
<p>
	【1024分辨率版本截图】：</p>
<p>
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://img.album.pchome.net/54/68/92/27/09fedf8ebd3603ea27514b768c283919.jpg');" src="http://img.album.pchome.net/54/68/92/27/09fedf8ebd3603ea27514b768c283919.jpg" />&nbsp;<br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://img.album.pchome.net/54/68/92/27/f4cb8860a6c820c2805f1e091d28ddae.jpg');" src="http://img.album.pchome.net/54/68/92/27/f4cb8860a6c820c2805f1e091d28ddae.jpg" />&nbsp;<br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://img.album.pchome.net/54/68/92/27/d1cffb0b782b3c4d11986781a7283b5f.jpg');" src="http://img.album.pchome.net/54/68/92/27/d1cffb0b782b3c4d11986781a7283b5f.jpg" /><br />
	<br />
	640分辨率影片截图<br />
	<br />
	<img alt="" border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://img.album.pchome.net/54/68/92/29/2f7b0b2fbf8807a98c59eaec6a1f512e.jpg');" src="http://img.album.pchome.net/54/68/92/29/2f7b0b2fbf8807a98c59eaec6a1f512e.jpg" /><br />
	<img alt="" border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://img.album.pchome.net/54/68/92/29/85a052de62173343917737410e6ba22c.jpg');" src="http://img.album.pchome.net/54/68/92/29/85a052de62173343917737410e6ba22c.jpg" /><br />
	<img alt="" border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://img.album.pchome.net/54/68/92/29/344724250b552aa7581057f445fd4b94.jpg');" src="http://img.album.pchome.net/54/68/92/29/344724250b552aa7581057f445fd4b94.jpg" /><br />
	<img alt="" border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://img.album.pchome.net/54/68/92/29/4cff2c508b4050d6311959f85e2177cf.jpg');" src="http://img.album.pchome.net/54/68/92/29/4cff2c508b4050d6311959f85e2177cf.jpg" /><br />
	<img alt="" border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://img.album.pchome.net/54/68/92/29/88a80713436d9c0305d90eb492d9194f.jpg');" src="http://img.album.pchome.net/54/68/92/29/88a80713436d9c0305d90eb492d9194f.jpg" /></p>
<p>
	破量子危机》DVD中英双字</p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<anchor></anchor><a href="ftp://e25:e25@xl2.eee4.com:9219/[3E电影站www.eee4.com]007大破量子危DVD中英双字CD1.rmvb" target="_blank">ftp://e25:e25@xl2.eee4.com:9219/[3E电影站www.eee4.com]007大破量子危DVD中英双字CD1.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<anchor></anchor><a href="ftp://e25:e25@xl2.eee4.com:9219/[3E电影站www.eee4.com]007大破量子危DVD中英双字CD2.rmvb" target="_blank">ftp://e25:e25@xl2.eee4.com:9219/[3E电影站www.eee4.com]007大破量子危DVD中英双字CD2.rmvb</a></td>
		</tr>
	</tbody>
</table>
<br />
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://e63:e63@xl2.eee4.com:9306/[3E电影站www.eee4.com]007大破量子危机[DVD中英双字1024x560高清版].rmvb" target="_blank">ftp://e63:e63@xl2.eee4.com:9306/[3E电影站www.eee4.com]007大破量子危机[DVD中英双字1024x560高清版].rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:1932/飘花电影piaohua.com007大破量子危机1280高清.rmvb ">ftp://dy44:piaohua@dy44.piaohua.com:1932/飘花电影piaohua.com007大破量子危机1280高清.rmvb </a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O16032S0-43421.jpg{/dede:field}
