{dede:field name='keywords'}霓虹肉身/灯红酒绿DVD中字西班牙{/dede:field}
{dede:field name='description'}霓虹肉身/灯红酒绿DVD中字西班牙喜剧迅雷下载、免费下载，霓虹肉身/灯红酒绿DVD中字西班牙喜剧Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}霓虹肉身/灯红酒绿DVD中字西班牙喜剧{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-04-25{/dede:field}
{dede:field name='body'}<p>
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120425/15/56643687201204251501512601522856607_006.jpg" /></p>

<p>
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120425/15/56643687201204251501512601522856607_004.jpg" /></p>

<p>
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120425/15/56643687201204251501512601522856607_005.jpg" /></p>

<p>
	◎译　　名　霓虹肉身/灯红酒绿<br />
	◎片　　名　Neon Flesh<br />
	◎年　　代　2011<br />
	◎国　　家　西班牙/阿根廷/瑞典<br />
	◎类　　别　喜剧<br />
	◎语　　言　西班牙语<br />
	◎IMDB评分 5.2/10 (311 votes)<br />
	◎IMDB链接 <a href="http://6movie.org/topics/tt1259570/">http://6movie.org/topics/tt1259570/</a><br />
	◎片　　长　1h:41m<br />
	◎导　　演　Paco Cabezas<br />
	◎主　　演　安吉拉&middot;摩琳娜 Angela Molina ....Pura<br />
	　　　　　　Macarena Gomez ....La Canija / Marga<br />
	　　　　　　Vicente Romero ....Angelito<br />
	　　　　　　Carlos Vellido ....Director<br />
	　　　　　　马里奥&middot;卡萨斯 Mario Casas ....Ricky<br />
	　　　　　　Luciano Caceres ....El Nino<br />
	　　　　　　Damaso Conde ....La Infantita<br />
	　　　　　　达里奥&middot;葛兰帝内提 Dario Grandinetti<br />
	　　　　　　Charles Tyner ....Robidoux<br />
	　　　　　　Matt Clark ....Qualen<br />
	　　　　　　布兰卡&middot;苏亚雷兹 Blanca Suarez ....Veronica　　　　　</p>
<p>
	◎简　　介　</p>
<p>
	　 　影片讲述了主人公为了讨老妈欢心，与自己两个没用的老友开了一家妓院做事业的喜剧故事。</p>
<p>
	　　 里基Ricky（马里奥&middot;卡萨斯饰）在不到12岁时就混迹街头，生活上与妓女、皮条客和瘾君子们打成一片，并且与其保持着密切的关系。现在，为了讨刚刚出狱的老妈普拉Pura（安赫拉&middot;莫利纳饰）欢心，23岁的里基与自己两个没用的老友开了一家名为&ldquo;广岛俱乐部&rdquo;的妓院作为一份礼物让老妈把持。然而，这个快乐的想法是不那么容易实现的......</p>
<p>
	　　 NEON FLESH 是一部高度犯罪惊悚片，具有独特风格及野性幽默。全片围绕Ricky和他所生活的地下世界展开。Pura，他的母亲，是个妓女，在他12岁就抛弃了他。如今，Ricky长大成人，他想在母亲出狱时开一家妓院孝敬她。他找了他的瘾君子女友帮他拉皮条，还招募了一个相信自己是皇家成员的变性人。但是当Ricky从医院把母亲接回来时，发现母亲已经对自己送的礼物非常腻味了，这让他非常失落。更糟的是，他妓院选址侵犯了无情的暴徒El Chino的领域。</p>

<p>
	◎影片截图</p>
<p>
	&nbsp;<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120425/15/56643687201204251501512601522856607_001.jpg" /></p>
<p>
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120425/15/56643687201204251501512601522856607_003.jpg" /></p>
<p>
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120425/15/56643687201204251501512601522856607_000.jpg" /></p>
<p>
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120425/15/56643687201204251501512601522856607_002.jpg" /></p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.netftp//dy44:piaohua@dy44.piaohua.com:3201/" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3291/飘花电影piaohua.com灯红酒绿DVD中字.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3291/飘花电影piaohua.com灯红酒绿DVD中字.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15F1E0-3cT.jpg{/dede:field}
