<?php
$z[0]=Array("field","超级无敌掌门狗,系列4部BD中英双",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","超级无敌掌门狗 系列4部BD中英双字1024/1280高清迅雷下载、免费下载，超级无敌掌门狗 系列4部BD中英双字1024/1280高清Gvod高清在线播放，剧情介绍等。",73,257);
$z[1][4]['name']="description";
$z[2]=Array("field","超级无敌掌门狗 系列4部BD中英双字1024/1280高清",259,342);
$z[2][4]['name']="title";
$z[3]=Array("field","",344,383);
$z[3][4]['name']="writer";
$z[4]=Array("field","",385,424);
$z[4][4]['name']="source";
$z[5]=Array("field","2012-05-15",426,476);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",478,515);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://3e:3e@xl.eee4.com:221/[3E电影站www.eee4.cn]超级无敌掌门狗：月球野餐记.rmvb\" target=\"_blank",517,652);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MO5c1F-44I8.jpg",654,735);
$z[8][4]['name']="litpic";

?>