{dede:field name='keywords'}圣斗士星矢剧场版4:,最终圣战的{/dede:field}
{dede:field name='description'}圣斗士星矢剧场版4: 最终圣战的战士们BD国语中字1280高清迅雷下载、免费下载，圣斗士星矢剧场版4: 最终圣战的战士们BD国语中字1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}圣斗士星矢剧场版4: 最终圣战的战士们BD国语中字1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-01-15{/dede:field}
{dede:field name='body'}<p>
	<img alt="" border="0" src="http://img.album.pchome.net/54/85/02/67/0113e8daf8805843ec1fc93bdb302cba.jpg" /></p>
<p>
	◎译　　名　圣斗士星矢剧场版4: 最终圣战的战士们<br />
	◎片　　名　Saint.Seiya.Movie.4.Saishuseisen.no.senshitachi<br />
	◎年　　代　1989<br />
	◎国　　家　日本<br />
	◎类　　别　动画/冒险/奇幻<br />
	◎语　　言　国日双语<br />
	◎字　　幕　中文<br />
	◎IMDB评分 6.3/10 (123 votes)<br />
	◎文件格式　1024 x 576<br />
	◎文件格式　x264 + AAC<br />
	◎文件大小　1CD<br />
	◎片　　长　44m:53s<br />
	◎导　　演　Masayuki Akehi<br />
	◎主　　演　古谷彻 Toru Furuya&nbsp; ....Seiya, Pegasus Bronze Saint (voice)<br />
	　　　　　　铃置洋孝 Hirotaka Suzuoki&nbsp; ....Shiryo, Dragon Bronze Saint (voice)<br />
	　　　　　　桥本晃一 Koichi Hashimoto&nbsp; ....Hyoga, Cygnus Bronze Saint (voice)<br />
	　　　　　　堀川亮 Ryo Horikawa&nbsp; ....Shun, Andromeda Bronze Saint (voice)<br />
	　　　　　　堀秀行 Hideyuki Hori&nbsp; ....Ikki, Phoenix Bronze Saint (voice)<br />
	　　　　　　潘惠子 Keiko Han&nbsp; ....Saori Kido (Athena) (voice)<br />
	　　　　　　盐泽兼人 Kaneto Shiozawa&nbsp; ....Mo, A<a _fcksavedurl="http://www.anzhuo4.com/" href="http://www.anzhuo4.com/" style="color: rgb(0, 0, 0); text-decoration: none;">android</a>ries Gold Saint (voice)<br />
	　　　　　　坪井章子 Akiko Tsuboi&nbsp; ....Hyoga no haha (voice)<br />
	　　　　　　Katsuji Mori&nbsp; ....Beelzebub (voice)<br />
	　　　　　　难波圭一 Keiichi Nanba&nbsp; ....Astaroth (voice)<br />
	　　　　　　山口健 Ken Yamaguchi&nbsp; ....Eligor (voice)<br />
	　　　　　　古川登志夫 Toshio Furukawa&nbsp; ....Moa (voice)<br />
	　　　　　　平野正人 Masato Hirano&nbsp; ....Sen&#39;in-tachi (voice)<br />
	　　　　　　草尾毅 Takeshi Kusao&nbsp; ....Sen&#39;in-tachi (voice)<br />
	　　　　　　佐藤宽之 Hiroyuki Sato&nbsp; ....Sen&#39;in-tac<a _fcksavedurl="http://www.qqtmb.com/" href="http://www.qqtmb.com/" style="color: rgb(0, 0, 0); text-decoration: none;">qq</a>hi (voice)<br />
	　　　　　　挂川裕彦 Hirohiko Kakegawa&nbsp; ....Otoko (voice)<br />
	　　　　　　Michiko Abe&nbsp; ....Onna (voice)<br />
	　　　　　　津嘉山正种 Masatane Tsukayama&nbsp; ....Lucifer (voice)<br />
	　　　　　　<br />
	◎简　　介<br />
	<br />
	&nbsp; &nbsp; 不祥之夜，四道邪恶光芒侵入圣域，以迅雷不及掩耳的速度击倒多名黄金圣斗士。来者乃圣魔天使，是堕落天使路西法的手下。神话时代，路西法试图凌驾众神之上，最终被打入魔界。他怀着恐怖罪恶的念头复活，凭借堕入魔界的波塞冬、艾丽丝、阿波罗小宇宙的支持，路西法在世界各地掀起连番灾难，人类命运危在旦夕。为了拯救人类，纱织小姐<a _fcksavedurl="http://www.dailiv.com/" href="http://www.dailiv.com/" style="color: rgb(0, 0, 0); text-decoration: none;">在线代理</a>情愿献出圣血。面对实力强大的圣魔天使，星矢等人无力可施，只能眼睁睁地看着纱织被路西法带走。为了救回女神，青铜圣斗士们携手前往伏魔店，与邪恶而强大的路西法及圣魔天使展开对决&hellip;&hellip;<br />
	<br />
	<img alt="" border="0" src="http://img.album.pchome.net/54/85/07/05/debe9c828fa717589a535e9eb4a331b6.jpg" /><br />
	<img alt="" border="0" src="http://img.album.pchome.net/54/85/07/05/b654093bb7a0954d38880d92e9aad193.jpg" /></p>

<p>
	[下载地址]： &nbsp;<img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" /></p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2627/飘花电影piaohua.com圣斗士星矢剧场版4最终圣战的战士们BD国语中字1280高清.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:2627/飘花电影piaohua.com圣斗士星矢剧场版4最终圣战的战士们BD国语中字1280高清.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2627/飘花电影piaohua.com圣斗士星矢剧场版4最终圣战的战士们BD国语中字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1B13250-31Q0.jpg{/dede:field}
