<?php
$z[0]=Array("field","GP506/岗哨506BD中字1280高清迅",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","GP506/岗哨506BD中字1280高清迅雷下载、免费下载，GP506/岗哨506BD中字1280高清Gvod高清在线播放，剧情介绍等。",72,220);
$z[1][4]['name']="description";
$z[2]=Array("field","GP506/岗哨506BD中字1280高清",222,287);
$z[2][4]['name']="title";
$z[3]=Array("field","",289,328);
$z[3][4]['name']="writer";
$z[4]=Array("field","",330,369);
$z[4][4]['name']="source";
$z[5]=Array("field","2012-02-23",371,421);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",423,460);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://eee4.com:8113@vip20.eee4.com:8113/[3E迅雷电影站www.eee4.com]506号岗哨DVD中字CD1.rmvb\" target=\"_blank",462,607);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MPRE60-42238.jpg",609,691);
$z[8][4]['name']="litpic";

?>