{dede:field name='keywords'}GP506/岗哨506BD中字1280高清迅{/dede:field}
{dede:field name='description'}GP506/岗哨506BD中字1280高清迅雷下载、免费下载，GP506/岗哨506BD中字1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}GP506/岗哨506BD中字1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-02-23{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://eee4.com:8113@vip20.eee4.com:8113/[3E迅雷电影站www.eee4.com]506号岗哨DVD中字CD1.rmvb" target="_blank{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MPRE60-42238.jpg{/dede:field}
