{dede:field name='keywords'}尼姆计划/项目：尼姆DVD中英双字{/dede:field}
{dede:field name='description'}尼姆计划/项目：尼姆DVD中英双字2011纪录片迅雷下载、免费下载，尼姆计划/项目：尼姆DVD中英双字2011纪录片Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}尼姆计划/项目：尼姆DVD中英双字2011纪录片{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-01-16{/dede:field}
{dede:field name='body'}<p>
	<img alt="" height="819" src="http://images.screenrush.co.uk/r_760_x/medias/nmedia/18/83/00/21/19790358.jpg" width="550" /></p>
<p>
	◎译　　名　尼姆计划/项目：尼姆<br />
	◎片　　名　Project Nim<br />
	◎年　　代　2011<br />
	◎国　　家　英国/美国<br />
	◎类　　别　纪录片<br />
	◎语　　言　英语<br />
	◎字　　幕　中英双字幕<br />
	◎IMDB评分 7.3/10 from 779 users<br />
	◎文件格式　Rmvb<br />
	◎视频尺寸　640 x 360<br />
	◎文件大小　385MB<br />
	◎片　　长　95 Mins<br />
	◎导　　演　詹姆斯&middot;马什 James Marsh<br />
	◎主　　演　Bob Angelini ....Lab Tech<br />
	　　　　　　Bern Cohen ....Dr. William Lemmon<br />
	　　　　　　Reagan Leonard ....Stephanie LaFarge<br />
	　　　　　　Renne Falitz ....Herself<br />
	　　　　　　Bob Ingersoll ....Himself<br />
	　　　　　　Stephanie LaFarge ....Herself<br />
	　　　　　　Jenny Lee ....Herself<br />
	　　　　　　James Mahoney ....Himself<br />
	<br />
	◎简　　介　<br />
	<br />
	　　本片源于1970年代期间的一项动物实验，一只名叫尼姆的黑猩猩，出生后便离开了妈妈，然后开始被当<a href="http://www.dy131.com/" target="_blank">6v电影网</a>类一样去养育。尼姆首先被安排到曼哈顿区的一个家庭（曼哈顿区的家庭普遍十分富裕），然后开始学习手语并达到了能够交流的程度。但是，这项实验并没有按原计划一直继续下去，可是人类已经对尼姆产生了巨大的影响，尼姆也对人类有了自己的期望（或者已觉得自己就是人类）。尼姆的未来在哪里？<br />
	<br />
	◎影片截图<br />
	<br />
	<img alt="" height="337" src="http://img.album.pchome.net/54/84/69/41/13266194550e5ce41f832a1747f0434645c06331e4.jpg" style="cursor: pointer" width="600" /><br />
	<img alt="" height="337" src="http://img.album.pchome.net/54/84/69/41/1326619455212c78d690ecab32ee4d4b26e8767ccb.jpg" style="cursor: pointer" width="600" /><br />
	<img alt="" height="337" src="http://img.album.pchome.net/54/84/69/41/13266194558cb9588aa2a277a53a124ba4c17949db.jpg" style="cursor: pointer" width="600" /><br />
	&nbsp;</p>

<p>
	[下载地址]：&nbsp;&nbsp;
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				&nbsp;<a href="ftp://dy44:piaohua@dy44.piaohua.com:2636/飘花电影piaohua.com尼姆计划DVD中英双字.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2636/飘花电影piaohua.com尼姆计划DVD中英双字.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1CAB0-153U.jpg{/dede:field}
