{dede:field name='keywords'}南国医恋第一季22欧美剧迅雷下载{/dede:field}
{dede:field name='description'}南国医恋第一季22欧美剧迅雷下载、免费下载，南国医恋第一季22欧美剧Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}南国医恋第一季22欧美剧{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-17{/dede:field}
{dede:field name='body'}<p>
	<img src="http://img.funshion.com/attachment/new_images/2011/09-02/19508089_1314956695_746.jpg" /></p>
<p>
	&nbsp;<img src="http://img.funshion.com/attachment/new_images/2011/09-02/19508089_1314956689_243.jpg" /></p>
<p>
	<br />
	导演：Jason Ensler</p>
<p>
	&bull;演员：<br />
	蕾切尔&middot;比尔森 / 杰米&middot;金 / 斯科特&middot;波特 / 南希&middot;特拉维斯 / 克莱斯&middot;威廉 / McKaley Miller / Will Bethel</p>
<p>
	&bull;类型：医疗<br />
	&bull;首映：2011年9月26日 美国<br />
	&bull;又名：南方小镇医生</p>
<p>
	<br />
	&bull;点评： 《绯闻女孩》制片人合力新作,南国的男生女生配<br />
	&bull;剧情： 来自纽约的都市女孩Zoe Hart（Rachel Bilson扮演）正憧憬着自己的未来－－她以全班第一的优异成绩从医学院毕业，将继承父亲的衣钵当一名心胸外科医生。可是当Zoe的梦想破灭之后，她不得不接受性情古怪的Harley Wilkes医生的邀请，去他开办的小诊所工作。 离开喧嚣的都市，Zoe只身一人来到这座南方的海岸小...<br />
	&bull;花絮： 该剧是《绯闻女孩》（Gossip）的四名制片人－－Leila Gerstein、Josh Schwartz、Stephanie Savage和Jason Ensler－－合作打造的一部新作品。</p>
<p>
	[下载地址]： &nbsp;<img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" /></p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:1872/飘花电影piaohua.com南国医恋第一季EP01.rmvb ">&nbsp;ftp://dy44:piaohua@dy44.piaohua.com:1872/飘花电影piaohua.com南国医恋第一季EP01.rmvb </a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:1872/飘花电影piaohua.com南国医恋第一季EP02.rmvb ">&nbsp;ftp://dy44:piaohua@dy44.piaohua.com:1872/飘花电影piaohua.com南国医恋第一季EP02.rmvb </a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:1872/飘花电影piaohua.com南国医恋第一季EP03.rmvb ">&nbsp;ftp://dy44:piaohua@dy44.piaohua.com:1872/飘花电影piaohua.com南国医恋第一季EP03.rmvb </a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:1872/飘花电影piaohua.com南国医恋第一季EP04.rmvb ">&nbsp;ftp://dy44:piaohua@dy44.piaohua.com:1872/飘花电影piaohua.com南国医恋第一季EP04.rmvb </a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:1938/飘花电影piaohua.com南国医恋第一季EP05.rmvb ">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:1938/飘花电影piaohua.com南国医恋第一季EP05.rmvb ">ftp://dy44:piaohua@dy44.piaohua.com:1938/飘花电影piaohua.com南国医恋第一季EP05.rmvb </a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2051/飘花电影piaohua.com南国医恋第一季EP06.rmvb ">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:2051/飘花电影piaohua.com南国医恋第一季EP06.rmvb ">ftp://dy44:piaohua@dy44.piaohua.com:2051/飘花电影piaohua.com南国医恋第一季EP06.rmvb </a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2110/飘花电影piaohua.com南国医恋第一季EP07.rmvb ">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:2110/飘花电影piaohua.com南国医恋第一季EP07.rmvb ">ftp://dy44:piaohua@dy44.piaohua.com:2110/飘花电影piaohua.com南国医恋第一季EP07.rmvb </a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2233/飘花电影piaohua.com南国医恋第一季EP08.rmvb ">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:2233/飘花电影piaohua.com南国医恋第一季EP08.rmvb ">ftp://dy44:piaohua@dy44.piaohua.com:2233/飘花电影piaohua.com南国医恋第一季EP08.rmvb </a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2233/飘花电影piaohua.com南国医恋第一季EP09.rmvb ">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:2233/飘花电影piaohua.com南国医恋第一季EP09.rmvb ">ftp://dy44:piaohua@dy44.piaohua.com:2233/飘花电影piaohua.com南国医恋第一季EP09.rmvb </a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2302/飘花电影piaohua.com南国医恋第一季EP10.rmvb ">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:2302/飘花电影piaohua.com南国医恋第一季EP10.rmvb ">ftp://dy44:piaohua@dy44.piaohua.com:2302/飘花电影piaohua.com南国医恋第一季EP10.rmvb </a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2695/飘花电影piaohua.com南国医恋第一季EP11.rmvb ">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:2695/飘花电影piaohua.com南国医恋第一季EP11.rmvb ">ftp://dy44:piaohua@dy44.piaohua.com:2695/飘花电影piaohua.com南国医恋第一季EP11.rmvb </a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2755/飘花电影piaohua.com南国医恋第一季EP12.rmvb ">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:2755/飘花电影piaohua.com南国医恋第一季EP12.rmvb ">ftp://dy44:piaohua@dy44.piaohua.com:2755/飘花电影piaohua.com南国医恋第一季EP12.rmvb </a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2777/飘花电影piaohua.com南国医恋第一季EP13.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:2777/飘花电影piaohua.com南国医恋第一季EP13.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2777/飘花电影piaohua.com南国医恋第一季EP13.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2877/飘花电影piaohua.com南国医恋第一季EP14.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:2877/飘花电影piaohua.com南国医恋第一季EP14.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2877/飘花电影piaohua.com南国医恋第一季EP14.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2877/飘花电影piaohua.com南国医恋第一季EP15.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:2877/飘花电影piaohua.com南国医恋第一季EP15.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2877/飘花电影piaohua.com南国医恋第一季EP15.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2929/飘花电影piaohua.com南国医恋第一季EP16.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:2929/飘花电影piaohua.com南国医恋第一季EP16.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2929/飘花电影piaohua.com南国医恋第一季EP16.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3205/飘花电影piaohua.com南国医恋第一季EP17.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3205/飘花电影piaohua.com南国医恋第一季EP17.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3205/飘花电影piaohua.com南国医恋第一季EP17.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3299/飘花电影piaohua.com南国医恋第一季EP18.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3299/飘花电影piaohua.com南国医恋第一季EP18.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3299/飘花电影piaohua.com南国医恋第一季EP18.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3299/飘花电影piaohua.com南国医恋第一季EP19.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3299/飘花电影piaohua.com南国医恋第一季EP19.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3299/飘花电影piaohua.com南国医恋第一季EP19.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3355/飘花电影piaohua.com南国医恋第一季EP20.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3355/飘花电影piaohua.com南国医恋第一季EP20.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3355/飘花电影piaohua.com南国医恋第一季EP20.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3445/飘花电影piaohua.com南国医恋第一季EP21.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3445/飘花电影piaohua.com南国医恋第一季EP21.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3445/飘花电影piaohua.com南国医恋第一季EP21.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3445/飘花电影piaohua.com南国医恋第一季EP22.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3445/飘花电影piaohua.com南国医恋第一季EP22.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3445/飘花电影piaohua.com南国医恋第一季EP22.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1A4X20-4WT.jpg{/dede:field}
