<?php
$z[0]=Array("field","惊天动地[DVD国语中字]迅雷下载",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","惊天动地[DVD国语中字]迅雷下载、免费下载，惊天动地[DVD国语中字]Gvod高清在线播放，剧情介绍等。",72,208);
$z[1][4]['name']="description";
$z[2]=Array("field","惊天动地[DVD国语中字]",210,269);
$z[2][4]['name']="title";
$z[3]=Array("field","",271,310);
$z[3][4]['name']="writer";
$z[4]=Array("field","",312,351);
$z[4][4]['name']="source";
$z[5]=Array("field","2009-10-30",353,403);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",405,442);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://4e:4e@www2.eee4.com:839/[3E电影站www.eee4.cn]惊天动地DVD国语中字.rmvb\" target=_blank>ftftp://4e:4e@www2.eee4.com:839/[3E电影站www.eee4.cn]惊天动地DVD国语中字.rmvb</A></TD></TR></TBODY></TABLE></div><ul class=\"mmlist",444,704);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MPX3030-443D.jpg",706,788);
$z[8][4]['name']="litpic";

?>