{dede:field name='keywords'}人猿大战BD中英双字1280高清经典{/dede:field}
{dede:field name='description'}人猿大战BD中英双字1280高清经典科幻迅雷下载、免费下载，人猿大战BD中英双字1280高清经典科幻Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}人猿大战BD中英双字1280高清经典科幻{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-12-18{/dede:field}
{dede:field name='body'}<p>
	<img alt="" height="492" src="http://img165.poco.cn/mypoco/myphoto/20111213/23/57196343201112132259135894714691448_035.jpg" width="380" /><br />
	【影片原名】Battle for the Planet of the Apes<br />
	【中文译名】人猿大战/决战猩球<br />
	【出品公司】20世纪福克斯电影公司<br />
	【出品年代】1973<br />
	【上映日期】1973年6月15日&nbsp;&nbsp;美国&nbsp;&nbsp;<br />
	【影片级别】USA:G<br />
	【IMDB评分】4.9/10(4,825 votes)<br />
	【国　　家】美国<br />
	【字幕语言】中文/英文<br />
	【视频尺寸】1280&times;720<br />
	【文件格式】RMVB+AAC<br />
	【类　　别】动作/剧情/科幻<br />
	【导　　演】杰&middot;李&middot;汤姆逊 J. Lee Thompson<br />
	【主　　演】罗迪&middot;麦克道尔 Roddy McDowall ....Caesar<br />
	　　　　　　克劳德&middot;艾金斯 Claude Akins ....Gen. Aldo<br />
	　　　　　　刘&middot;艾尔斯 Lew Ayres ....Mandemus (keeper of the armory)<br />
	　　　　　　约翰&middot;兰迪斯 John Landis ....Jake&#39;s friend<br />
	　　　　　　约翰&middot;休斯顿 John Huston ....The Lawgiver<br />
	　　　　　　考林&middot;加普 Colleen Camp ....Julie (Lisa&#39;s servant) (uncredited)<br />
	　　　　　　Natalie Trundy ....Lisa (Caesar&#39;s wife)<br />
	　　　　　　Severn Darden ....Gov. Kolp<br />
	　　　　　　Paul Williams ....Virgil<br />
	　　　　　　Austin Stoker ....MacDonald<br />
	　　　　　　Noah Keen ....Abe (the teacher)<br />
	　　　　　　Richard Eastham ....Mutant captain<br />
	　　　　　　France Nuyen ....Alma<br />
	　　　　　　Paul Stevens ....Mendez<br />
	　　　　　　Heather Lowe ....Doctor<br />
	　　　　　　Bobby Porter ....Cornelius (son of Caesar)<br />
	　　　　　　Michael Stearns ....Jake<br />
	　　　　　　Cal Wilson ....Soldier (Sgt. York)<br />
	　　　　　　Pat Cardi ....Young chimp<br />
	　　　　　　Andy Knight ....Mutant on motorcycle<br />
	　　　　　　James Bacon ....Ape (uncredited)<br />
	【内容简介】<br />
	&nbsp; &nbsp;&nbsp; &nbsp;2678年，猿族教授在讲述凯撒当年的故事，那是在2015年，猿族中发生叛乱，大猩猩们在将军艾多（General Aldo）的带领下和一群发生变异的人类一同意图推翻凯撒的领导，决战开始了...<br />
	<img alt="" height="337" src="http://img165.poco.cn/mypoco/myphoto/20111213/23/57196343201112132259135894714691448_034.jpg" style="cursor: pointer" width="600" /><br />
	&nbsp;</p>

<p>
	[下载地址]： &nbsp;<img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2361/飘花电影piaohua.com人猿大战BD中英双字1280高清.rmvb ">&nbsp;ftp://dy44:piaohua@dy44.piaohua.com:2361/飘花电影piaohua.com人猿大战BD中英双字1280高清.rmvb </a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15X0220-14513.jpg{/dede:field}
