<?php
$z[0]=Array("field","摇摆的婚约/摇摆de婚约BD国语中",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","摇摆的婚约/摇摆de婚约BD国语中字1280高清迅雷下载、免费下载，摇摆的婚约/摇摆de婚约BD国语中字1280高清Gvod高清在线播放，剧情介绍等。",72,244);
$z[1][4]['name']="description";
$z[2]=Array("field","摇摆的婚约/摇摆de婚约BD国语中字1280高清",246,323);
$z[2][4]['name']="title";
$z[3]=Array("field","",325,364);
$z[3][4]['name']="writer";
$z[4]=Array("field","",366,405);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-11-15",407,457);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",459,496);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://7e:7e@d8.3edyy.com:167/【3E电影院www.eee4.cc】摇摆的婚约DVD国语中字.rmvb\" target=\"_blank",498,631);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MOKA50-2Z19.jpg",633,714);
$z[8][4]['name']="litpic";

?>