{dede:field name='keywords'}冰冻星球BD中英双字1280高清2011{/dede:field}
{dede:field name='description'}冰冻星球BD中英双字1280高清2011纪录片迅雷下载、免费下载，冰冻星球BD中英双字1280高清2011纪录片Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}冰冻星球BD中英双字1280高清2011纪录片{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-01-30{/dede:field}
{dede:field name='body'}<p>
	<img alt="" height="754" src="http://img.album.pchome.net/54/83/40/12/11d48bd5e800c8fe17767c7b8a4af703.jpg" width="540" /></p>
<p>
	◎译　　名　英国广播公司：冰冻星球<br />
	◎片　　名　BBC: Frozen Planet<br />
	◎年　　代　2011<br />
	◎国　　家　英国<br />
	◎类　　别　记录<br />
	◎语　　言　英语<br />
	◎字　　幕　中英双字幕<br />
	◎IMDB评分 9.5/10 (539votes)<br />
	◎文件格式&nbsp; &nbsp;Rmvb<br />
	◎视频尺寸　1280 x 720<br />
	◎文件大小　共4.8G<br />
	◎片　　长　60 minsx8<br />
	◎导　　演　Vanessa Berlowitz ....series producer (unknown episodes)<br />
	&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp;&nbsp;艾雷斯泰&middot;法瑟吉尔 Alastair Fothergill ....executive producer (unknown episodes)<br />
	◎主　　演　戴维&middot;爱丁保罗夫 David Attenborough ....Himself - Narrator (unknown episodes, 2011)<br />
	<br />
	◎简　　介　<br />
	<br />
	&nbsp; &nbsp;&nbsp;&nbsp;英国BBC电视台耗时5年制作的纪录片《冰冻地球》即将于近期推出。这部耗资巨大的纪录片用镜头真实的展现了正在逐渐溶解的地球两极，以及生活在这里的各种生物，片中种种景象让人叹为观止。<br />
	<br />
	&nbsp; &nbsp;&nbsp; &nbsp;纪录片的解说员大卫&middot;艾登堡（DavidAttenborough）爵士称，这可能是人类在地球气候产生剧烈变化前欣赏到这一景象的最后的机会了。现年85岁的艾登堡爵士说，&ldquo;这部纪录片捕捉了此前从未记录下来的很多行为和现象。随着时间的流逝，这些影像将会变得越来越珍贵，因为这很可能是我们最后的机会去记录下这些珍贵的场景。虽然在我们到达前的数百年甚至几千年前，地球两极的景象非常壮观，但是最近一个世纪以来，很多变化已经超过了人们的认识。&rdquo;<br />
	<br />
	&nbsp; &nbsp; 《冰冻地球》纪录片的摄制组采用了可以在低温下工作的特殊摄影机进行拍摄。这部耗时5年才问世的纪录片捕捉了很多珍贵的画面，表现出大自然神秘奇幻的一面：包括冰山崩塌，神秘的活火山喷发这些真实的自然现象，以及岩石峰，美轮美奂的融水湖和针叶林；此外，这些真实的图片也表现了大自然中残忍的一面，动物之间相互的角逐、厮杀，比如一头雄性北极熊勇敢击退多达10名情敌，身披血渍和伤痕，最终抱得美人归。这部纪录片还经常拍摄到一些生物是如何团结协作捕杀猎物的，比如虎鲸共同合作猎捕海豹等。借助高科技设备，摄制组还记录下了南极大陆中心地带广袤而荒芜的陆地，以及鲸鱼是迁徙到极地的过程。<br />
	<br />
	&nbsp; &nbsp; 整个纪录片是以季节的变化为主线的，记录了地球两极在一年内展现出的各种场景，从&ldquo;大融化&rdquo;的春天，到24小时都在光线照耀下的夏日，再到&ldquo;大冰封&rdquo;的秋天，最后以长夜漫漫的冬天结尾。纪录片最后还讲述了一些有趣的冒险经历，以及一些如何在极端寒冷和无法预知的恶劣的气候下生存的技巧。<br />
	<br />
	第1集 前往地球尽头<br />
	第2集 极地之春<br />
	第3集 极地之夏<br />
	第4集 极地之秋<br />
	第5集 极地之冬<br />
	第6集 最后的疆界<br />
	第7集 履于薄冰<br />
	第8集 世界尽头的科学<br />
	<br />
	<br />
	◎影片截图<br />
	<br />
	<img alt="" height="337" src="http://img.album.pchome.net/54/83/40/12/0f02304fadf64448a2a2c3447dd371c8.JPG" style="cursor: pointer" width="600" /><br />
	<img alt="" height="337" src="http://img.album.pchome.net/54/83/40/12/c47ca9e88b5f3225e702e85f41117508.JPG" style="cursor: pointer" width="600" /><br />
	<img alt="" height="337" src="http://img.album.pchome.net/54/83/40/12/8510620414921951a3d32b16b2f9b9e4.JPG" style="cursor: pointer" width="600" /><br />
	<img alt="" height="337" src="http://img.album.pchome.net/54/83/40/12/604236f54352a8f9b317aa136ddeaf81.jpg" style="cursor: pointer" width="600" /><br />
	&nbsp;</p>
<p>
	【下载地址】</p>
<p>
<table bgcolor="#0099cc" border="0" cellpadding="10" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				下载地址</td>
		</tr>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<anchor><a href="ftp://dy44:piaohua@dy44.piaohua.com:2715/飘花电影piaohua.com冰冻星球第1集：前往地球尽头BD中英双字1280高清.rmvb  ">ftp://dy44:piaohua@dy44.piaohua.com:2715/飘花电影piaohua.com冰冻星球第1集：前往地球尽头BD中英双字1280高清.rmvb&nbsp;&nbsp;</a></anchor></td>
		</tr>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<anchor><a href="ftp://dy44:piaohua@dy44.piaohua.com:2715/飘花电影piaohua.com冰冻星球第2集：极地之春BD中英双字1280高清.rmvb  ">ftp://dy44:piaohua@dy44.piaohua.com:2715/飘花电影piaohua.com冰冻星球第2集：极地之春BD中英双字1280高清.rmvb&nbsp;&nbsp;</a></anchor></td>
		</tr>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<anchor><a href="ftp://dy44:piaohua@dy44.piaohua.com:2715/飘花电影piaohua.com冰冻星球第3集：极地之夏BD中英双字1280高清.rmvb  ">ftp://dy44:piaohua@dy44.piaohua.com:2715/飘花电影piaohua.com冰冻星球第3集：极地之夏BD中英双字1280高清.rmvb&nbsp;&nbsp;</a></anchor></td>
		</tr>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<anchor><a href="ftp://dy44:piaohua@dy44.piaohua.com:2715/飘花电影piaohua.com冰冻星球第4集：极地之秋BD中英双字1280高清.rmvb  ">ftp://dy44:piaohua@dy44.piaohua.com:2715/飘花电影piaohua.com冰冻星球第4集：极地之秋BD中英双字1280高清.rmvb&nbsp;&nbsp;</a></anchor></td>
		</tr>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<anchor><a href="ftp://dy44:piaohua@dy44.piaohua.com:2715/飘花电影piaohua.com冰冻星球第5集：极地之冬BD中英双字1280高清.rmvb  ">ftp://dy44:piaohua@dy44.piaohua.com:2715/飘花电影piaohua.com冰冻星球第5集：极地之冬BD中英双字1280高清.rmvb&nbsp;&nbsp;</a></anchor></td>
		</tr>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<anchor><a href="ftp://dy44:piaohua@dy44.piaohua.com:2715/飘花电影piaohua.com冰冻星球第6集：最后的疆界BD中英双字1280高清.rmvb  ">ftp://dy44:piaohua@dy44.piaohua.com:2715/飘花电影piaohua.com冰冻星球第6集：最后的疆界BD中英双字1280高清.rmvb&nbsp;&nbsp;</a></anchor></td>
		</tr>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<anchor><a href="ftp://dy44:piaohua@dy44.piaohua.com:2715/飘花电影piaohua.com冰冻星球第7集：履于薄冰BD中英双字1280高清.rmvb  ">ftp://dy44:piaohua@dy44.piaohua.com:2715/飘花电影piaohua.com冰冻星球第7集：履于薄冰BD中英双字1280高清.rmvb&nbsp;&nbsp;</a></anchor></td>
		</tr>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<anchor><a href="ftp://dy44:piaohua@dy44.piaohua.com:2715/飘花电影piaohua.com冰冻星球第8集：世界尽头的科学BD中英双字1280高清.rmvb  ">ftp://dy44:piaohua@dy44.piaohua.com:2715/飘花电影piaohua.com冰冻星球第8集：世界尽头的科学BD中英双字1280高清.rmvb&nbsp;&nbsp;</a></anchor></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1CJc0-1QX.jpg{/dede:field}
