{dede:field name='keywords'}飙新力艺巨星演唱会迅雷下载，免{/dede:field}
{dede:field name='description'}飙新力艺巨星演唱会迅雷下载、免费下载，飙新力艺巨星演唱会Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}飙新力艺巨星演唱会{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-12-28{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="/uploads/allimg/c120525/133O0a5NF-164U2.jpg" style="width: 600px; height: 517px" /></p>
<p>
	<img alt="" src="/uploads/allimg/c120525/133O0a6010-1G3Z.jpg" style="width: 600px; height: 971px" /></p>
<p>
	庾澄庆．柯有纶．王力宏<br />
	游鸿明．李玟．黄义达<br />
	杨丞琳．蜜雪．吴建豪<br />
	周渝民．吴宗宪．康康<br />
	<br />
	24首天王天后经典成名曲完美演唱<br />
	超高画质HD全程收录<br />
	不可思议Live Blu-ray<br />
	<br />
	<br />
	专辑曲目：<br />
	<br />
	01. 热情的沙漠 (庾澄庆)<br />
	02. 情非得已 (庾澄庆 + 黄义达)<br />
	03. Reflection + 过完冬季 + 月光爱人 (李玟)<br />
	04. No Doubt (李玟)<br />
	05. 显微镜下的爱情 (黄义达)<br />
	06. 那女孩对我说 (黄义达)<br />
	07. 哭笑不得 (柯有纶)<br />
	08. 零 (柯有纶)<br />
	09. 笨小孩 (吴宗宪 + 柯有纶)<br />
	10. 小姐这是我的名片 (吴宗宪)<br />
	11. 爱斯基摩 (蜜雪)<br />
	12. 你不爱我 (康康)<br />
	13. 诗人的眼泪 (游鸿明)<br />
	14. 恋上一个人 + 一天一万年 (游鸿明)<br />
	15. 想象十个你 (吴建豪)<br />
	16. 我讨厌我自己 (吴建豪)<br />
	17. 暧昧 + 庆祝 (杨丞琳)<br />
	18. 过敏 (杨丞琳)<br />
	19. 遇上爱 (杨丞琳)<br />
	20. 妳的体温 (周渝民)<br />
	21. 忽然 (周渝民)<br />
	22. Kiss Goodbye (王力宏)<br />
	23. 盖世英雄 (王力宏)<br />
	24. We Are Family (新力巨星大合唱)<br />
	&nbsp;</p>


<p>
	[下载地址]： &nbsp;<img border="0" src="/uploads/allimg/c120525/133O0T31310-42214.jpg" />
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:2461/飘花电影piaohua.com飙新力艺巨星演唱会.rmvb</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O0a6030-1Y647.jpg{/dede:field}
