<?php
$z[0]=Array("field","火柴人/火柴男人/种计BD中英双字",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","火柴人/火柴男人/种计BD中英双字1280高清[DVD国语配音]迅雷下载、免费下载，火柴人/火柴男人/种计BD中英双字1280高清[DVD国语配音]Gvod高清在线播放，剧情介绍等。",73,269);
$z[1][4]['name']="description";
$z[2]=Array("field","火柴人/火柴男人/种计BD中英双字1280高清[DVD国语配音]",271,360);
$z[2][4]['name']="title";
$z[3]=Array("field","",362,401);
$z[3][4]['name']="writer";
$z[4]=Array("field","",403,442);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-11-02",444,494);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",496,533);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://e13:e13@dm.eee4.com:1216/[3E电影站www.eee4.com]火柴人DVD国语配音.rmvb\" target=\"_blank",535,665);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MP262330-35955.jpg",667,751);
$z[8][4]['name']="litpic";

?>