{dede:field name='keywords'}猎鹿人[BD中英双字1024x576高清{/dede:field}
{dede:field name='description'}猎鹿人[BD中英双字1024x576高清版]迅雷下载、免费下载，猎鹿人[BD中英双字1024x576高清版]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}猎鹿人[BD中英双字1024x576高清版]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2010-07-20{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://3e:3e@d8.3edyy.com:168/【3E电影院www.eee4.cc】猎鹿人BD中英双字1024x576高清版.rmvb" target="_blank{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MP625060-43Y0.jpg{/dede:field}
