<?php
$z[0]=Array("field","山路上的意外[DVD中字]迅雷下载",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","山路上的意外[DVD中字]迅雷下载、免费下载，山路上的意外[DVD中字]Gvod高清在线播放，剧情介绍等。",72,208);
$z[1][4]['name']="description";
$z[2]=Array("field","山路上的意外[DVD中字]",210,269);
$z[2][4]['name']="title";
$z[3]=Array("field","",271,310);
$z[3][4]['name']="writer";
$z[4]=Array("field","",312,351);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-03-16",353,403);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",405,442);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://3e:3e@www5.eee4.cc:1420/【3E电影院www.eee4.cc】山路上的意外DVD中字.rmvb\" target=_blank>ftftp://3e:3e@www5.eee4.cc:1420/【3E电影院www.eee4.cc】山路上的意外DVD中字.rmvb</A></TD></TR></TBODY></TABLE></div><ul class=\"mmlist",444,708);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MP60440-55916.jpg",710,793);
$z[8][4]['name']="litpic";

?>