{dede:field name='keywords'}2011年TVB万千星辉颁奖典礼迅雷{/dede:field}
{dede:field name='description'}2011年TVB万千星辉颁奖典礼迅雷下载、免费下载，2011年TVB万千星辉颁奖典礼Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}2011年TVB万千星辉颁奖典礼{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-12-06{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="/uploads/allimg/c120524/133N49352310-145495.jpg" /></p>
<p>
	2011年香港TVB万千星辉颁奖典礼将于12月5日举行，而今日(2011年11月10日)，各项大奖的提名已经全部公开，包括最佳男主角、最佳女主角、最佳男配角、最佳女配角、我最喜爱的电视男角色、我最喜爱的电视女角色、飞跃进步男艺员、飞跃进步女艺员、最佳节目主持、最佳剧集、最佳综艺节目、最佳信息节目等。和往年一样，各个剧提名平分秋色，一团和气。<br />
	完全提名名单如下：<br />
	&nbsp;</p>
<p>
	最佳男主角</p>
<p>
	<img alt="" src="/uploads/allimg/c120524/133N49352510-154F7.jpg" /></p>
<p>
	《鱼跃在花见》 张智霖(鱼至嬴)<br />
	《谁家灶头无烟火》 欧锦棠 (钟国栋)<br />
	《点解阿Sir系阿Sir》 陈豪(罗耀华)<br />
	《怒火街头》 郑嘉颖(罗力亚)<br />
	《团圆》 郭晋安(翁以进)<br />
	《团圆》 吴卓羲(翁以行)<br />
	《真相》 陈展鹏(刘思杰)<br />
	《紫禁惊雷》 马浚伟(聂多宝)<br />
	《紫禁惊雷》 马国明 (裕亲王)<br />
	《潜行狙击》 谢天华(梁笑棠)<br />
	《潜行狙击》 黄宗泽(苏星柏)<br />
	《不速之约》 欧阳震华(江东健)<br />
	《不速之约》 林峰(邰风)<br />
	《法证先锋3》 黎耀祥(布国栋)<br />
	《万凰之王》 陈锦鸿(道光帝)</p>

<p>
	<br />
	最佳女主角</p>
<p>
	<img alt="" src="/uploads/allimg/c120524/133N4935260-162022.jpg" /></p>
<p>
	《居家兵团》 汪明荃(黎嘉嘉)<br />
	《鱼跃在花见》 杨怡(赛思茏)<br />
	《Only You 只有您》 李司棋(庄思甜)<br />
	《Only You 只有您》 蒙嘉慧(麦一敏)<br />
	《谁家灶头无烟火》 田蕊妮(岑贝儿)<br />
	《点解阿Sir系阿Sir》 钟嘉欣(古嘉岚)<br />
	《花花世界花家姐》 佘诗曼(花丽珠)<br />
	《紫禁惊雷》 李诗韵(卓紫凝)<br />
	《潜行狙击》 陈法拉(周望晴)<br />
	《潜行狙击》 徐子珊(姚可可)<br />
	《九江十二坊》 薛家燕(梁关惠兰)<br />
	《九江十二坊》 江美仪(宋丁家碧)<br />
	《法证先锋3》 张可颐(锺学心)<br />
	《万凰之王》 宣萱(全妃)<br />
	《万凰之王》 胡杏儿(孝慎皇后)<br />
	&nbsp;</p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="/uploads/allimg/c120524/133N2Z4FF-102231.jpg" />&nbsp;&nbsp;&nbsp;
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:2272/飘花电影piaohua.com2011年TVB万千星辉颁奖典礼.rmvb</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120524/133N49352950-1I564.jpg{/dede:field}
