{dede:field name='keywords'}警察故事3/警察故事III:超级警察{/dede:field}
{dede:field name='description'}警察故事3/警察故事III:超级警察[BD中字1024x576高清版无水印]迅雷下载、免费下载，警察故事3/警察故事III:超级警察[BD中字1024x576高清版无水印]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}警察故事3/警察故事III:超级警察[BD中字1024x576高清版无水印]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2010-01-04{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://3e:3e@www2.3edyy.com:364/【3E电影院www.3edyy.com】警察故事3BD中字1024x576高清版无水印[国语].rmvb" target=_blank>ftftp://3e:3e@www2.3edyy.com:364/【3E电影院www.3edyy.com】警察故事3BD中字1024x576高清版无水印[国语].rmvb</A></TD></TR></TBODY></TABLE>粤语版本稍后更新<BR></div><ul class="mmlist{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MQ3292P-442X.jpg{/dede:field}
