{dede:field name='keywords'}正义联盟：毁灭/正义联盟：判决B{/dede:field}
{dede:field name='description'}正义联盟：毁灭/正义联盟：判决BD1280高清迅雷下载、免费下载，正义联盟：毁灭/正义联盟：判决BD1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}正义联盟：毁灭/正义联盟：判决BD1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-02-20{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120220/00/62564813201202200016341905393577176_000.jpg" style="width: 800px; height: 1085px" /></p>
<p>
	【影片原名】Justice League: Doom<br />
	【中文译名】正义联盟：毁灭/正义联盟：判决<br />
	【出品公司】华纳家庭视频公司<br />
	【出品年代】2012 年<br />
	【上映日期】2012 年 美国<br />
	【IMDB链接】<a href="http://www.imdb.com/title/tt2027128" target="_blank">http://www.imdb.com/title/tt2027128</a><br />
	【IMDB评分】NA<br />
	【国　　家】美国<br />
	【类　　别】动画 奇幻<br />
	【导　　演】Lauren Montgomery<br />
	【配 &nbsp; &nbsp; &nbsp;音】丹尼斯&middot;奎德 Dennis Quaid &nbsp;....Batman (rumored)<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;雷&middot;温斯顿 Ray Winstone &nbsp;....Aquaman (rumored)<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;凯文&middot;索伯 Kevin Sorbo &nbsp;....Superman (rumored)<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;蒂亚&middot;卡雷尔 Tia Carrere &nbsp;....Wonder Woman (rumored)<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;奥利薇亚&middot;阿波 Olivia d&#39;Abo &nbsp;....Carol Ferris / Star Sapphire<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Christopher Daniel Barnes &nbsp;....The Flash (rumored)<br />
	【内容简介】<br />
	<br />
	An adaptation of Mark Waid&#39;s &amp;quot;Tower of Babel&amp;quot; story from the JLA comic. Ra&#39;s al Ghul steals confidential files Batman has compiled on the members of the Justice League, and learns all their weaknesses.<br />
	　　Justice League Doom is a animated movie going to be partly based on the Justice League Tower of Babel series deals with Batman&#39;s perceived betrayal to the superhuman community by keeping records concerning the strengths and weaknesses of his allies in the JLA, including plans to neutralise his allies in a fight. His files are stolen by Ra&#39;s al Ghul, who uses them to defeat the League through a coordinated attack to prevent them from interfering with his latest scheme.</p>
<p>
	<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120220/00/62564813201202200016341905393577176_002.jpg" style="width: 640px; height: 360px" /><img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120220/00/62564813201202200016341905393577176_001.jpg" style="width: 640px; height: 360px" /></p>
<p>
	<br />
	<br />
	&nbsp;</p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>


<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="&#13;&#10;ftp://dy125:piaohua@dy125.piaohua.com:7626/飘花电影piaohua.com正义联盟毁灭BD中英双字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:7626/飘花电影piaohua.com正义联盟毁灭BD中英双字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1B31G0-45F1.jpg{/dede:field}
