<?php
$z[0]=Array("field","危情时速/煞破天劫/煞不住/不可",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","危情时速/煞破天劫/煞不住/不可阻挡/无可阻止[DVD中字]迅雷下载、免费下载，危情时速/煞破天劫/煞不住/不可阻挡/无可阻止[DVD中字]Gvod高清在线播放，剧情介绍等。",72,268);
$z[1][4]['name']="description";
$z[2]=Array("field","危情时速/煞破天劫/煞不住/不可阻挡/无可阻止[DVD中字]",270,359);
$z[2][4]['name']="title";
$z[3]=Array("field","",361,400);
$z[3][4]['name']="writer";
$z[4]=Array("field","",402,441);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-12-21",443,493);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",495,532);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://4e:4e@d8.3edyy.com:206/【3E看看www.3ekk.com】危情时速DVD中字.rmvb\" target=_blank>ftftp://4e:4e@d8.3edyy.com:206/【3E看看www.3ekk.com】危情时速DVD中字.rmvb</A></TD></TR></TBODY></TABLE></div><ul class=\"mmlist",534,786);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MPY4140-1F50.jpg",788,870);
$z[8][4]['name']="litpic";

?>