{dede:field name='keywords'}2012世界末日迅雷下载，免费下载{/dede:field}
{dede:field name='description'}2012世界末日迅雷下载、免费下载，2012世界末日Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}2012世界末日{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2005-08-14{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://3e:3e@xl.eee4.com:367/[3E电影站www.eee4.cn]2012世界末日R5中字CD1.rmvb" target="_blank{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MPZ3360-110K.jpg{/dede:field}
