{dede:field name='keywords'}直击要害/间接伤BD中英双字1024/{/dede:field}
{dede:field name='description'}直击要害/间接伤BD中英双字1024/1280高清迅雷下载、免费下载，直击要害/间接伤BD中英双字1024/1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}直击要害/间接伤BD中英双字1024/1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-03-05{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://e9:e9@xl2.eee4.com:9306/[3E电影站www.eee4.com]直击要害DVD中英双字1024x576高清版.rmvb" target="_blank{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MO4DS0-3b04.jpg{/dede:field}
