<?php
$z[0]=Array("field","直击要害/间接伤BD中英双字1024/",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","直击要害/间接伤BD中英双字1024/1280高清迅雷下载、免费下载，直击要害/间接伤BD中英双字1024/1280高清Gvod高清在线播放，剧情介绍等。",73,243);
$z[1][4]['name']="description";
$z[2]=Array("field","直击要害/间接伤BD中英双字1024/1280高清",245,321);
$z[2][4]['name']="title";
$z[3]=Array("field","",323,362);
$z[3][4]['name']="writer";
$z[4]=Array("field","",364,403);
$z[4][4]['name']="source";
$z[5]=Array("field","2012-03-05",405,455);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",457,494);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://e9:e9@xl2.eee4.com:9306/[3E电影站www.eee4.com]直击要害DVD中英双字1024x576高清版.rmvb\" target=\"_blank",496,641);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MO4DS0-3b04.jpg",643,724);
$z[8][4]['name']="litpic";

?>