{dede:field name='keywords'}红色机尾/红色尾翼/红尾巴BD1280{/dede:field}
{dede:field name='description'}红色机尾/红色尾翼/红尾巴BD1280高清迅雷下载、免费下载，红色机尾/红色尾翼/红尾巴BD1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}红色机尾/红色尾翼/红尾巴BD1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-07{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120504/23/62564813201205042320193438327740200_011.jpg" style="width: 700px; height: 883px" /></p>
<p>
	◎译　　名　红色机尾/红色尾翼/红尾巴<br />
	◎片　　名　Red Tails<br />
	◎年　　代　2012<br />
	◎国　　家　美国<br />
	◎类　　别　动作/战争/ 冒险/剧情<br />
	◎语　　言　英法西<br />
	◎字　　幕　中英双字<br />
	◎IMDB评分 &nbsp;5.8/10 (5,581 votes)<br />
	◎IMDB链接 &nbsp;<a href="http://www.xiaozhizhu.net/" target="_blank">http://www.xiaozhizhu.net/</a><br />
	◎片　　长　2h 5mn<br />
	◎导　　演　安东尼&middot;海明威 Anthony Hemingway<br />
	◎主　　演　小库珀&middot;古丁 Cuba Gooding Jr. &nbsp;....Major Emanuelle Stance<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 泰伦斯&middot;霍华德 Terrence Dashon Howard &nbsp;....Colonel A.J. Bullard<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 内特&middot;派克 Nate Parker &nbsp;....Marty &#39;Easy&#39; Julian<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 伊利亚&middot;凯利 Elijah Kelley &nbsp;....Samuel &#39;Joker&#39; George<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Leslie Odom Jr. &nbsp;....Declan &#39;Winky&#39; Hall<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Kevin Phillips &nbsp;....Leon &#39;Neon&#39; Edwards<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Method Man &nbsp;....Sticks (as Cliff Smith)<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 李&middot;特格森 Lee Tergesen &nbsp;....Colonel Jack Tomilson<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 丹妮拉&middot;鲁阿 Daniela Ruah &nbsp;....Sofia<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Matthew Marsh &nbsp;....Brigadier General Hauser<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Barnaby Kay &nbsp;....Commanding General Westlake<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 乔舒华&middot;达拉斯 Joshua Dallas &nbsp;....Ryan (as Joshua Dallas)<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Michael Lindley &nbsp;....Kellison<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Okezie Morro &nbsp;....Jammer<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Aml Ameen &nbsp;....Bag &#39;O Bones　<br />
	<br />
	◎简　　介　<br />
	<br />
	　　影片讲述了二战中，美国第一批黑人飞行员，克服当时制度和种族上的限制，组成了一支带有实验性质的特殊的轰炸机护卫队&mdash;&mdash;塔斯克基飞行员。他们的飞机上都画着&ldquo;红尾巴&rdquo;，于是这也成为了他们的绰号。&ldquo;红尾巴&rdquo;这支美国军事史上第一支由非裔美国人组成的飞行员编队，因为参加战争培训被派往阿拉巴马州随时准备迎战。在那里，他们经历了猖獗的种族主义和骚扰，他们的飞行和战斗能力曾饱受质疑，但&ldquo;红尾巴&rdquo;在空中卓越的表现，促使空军废除了种族隔离制度。他们在与意大利、德国的冲突中也起到了不可或缺的作用。<br />
	<br />
	　　A crew of African American pilots in the Tuskegee training program, having faced segregation while kept mostly on the ground during World War II, are called into duty under the guidance of Col. A.J. Bullard<br />
	<br />
	花絮<br />
	<br />
	&middot;本片是1994年以来卢卡斯影业打造的首部非《夺宝奇兵》及《星球大战》题材影片</p>
<p>
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120504/23/62564813201205042320193438327740200_009.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120504/23/62564813201205042320193438327740200_008.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120504/23/62564813201205042320193438327740200_007.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120504/23/62564813201205042320193438327740200_006.jpg" style="width: 720px; height: 405px" /><br />
	&nbsp;</p>
<p>
	【下载地址】</p>
<table bgcolor="#0099cc" border="0" cellpadding="10" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.net" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy125:piaohua@dy125.piaohua.com:8017/飘花电影piaohua.com红色机尾BD中英双字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:8017/飘花电影piaohua.com红色机尾BD中英双字1280高清.rmvb</a></td>
		</tr>
		<tr>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1493V20-5L08.jpg{/dede:field}
