<?php
$z[0]=Array("field","世界末日(自弹自唱)迅雷下载，免",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","世界末日(自弹自唱)迅雷下载、免费下载，世界末日(自弹自唱)Gvod高清在线播放，剧情介绍等。",73,203);
$z[1][4]['name']="description";
$z[2]=Array("field","世界末日(自弹自唱)",205,261);
$z[2][4]['name']="title";
$z[3]=Array("field","",263,302);
$z[3][4]['name']="writer";
$z[4]=Array("field","",304,343);
$z[4][4]['name']="source";
$z[5]=Array("field","2013-03-01",345,395);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>\r\n	播放后双击视频&ldquo;全屏&rdquo;</p>\r\n<p>\r\n	<object class=\"OBJECT\" classid=\"CLSID:22d6f312-b0f6-11d0-94ab-0080c74c7e95\" height=\"350\" id=\"MediaPlayer\" width=\"500\"><param name=\"ShowStatusBar\" value=\"-1\" /><param name=\"Filename\" value=\"http://www.fksz.com/song2/mtv/mm.asf\" /></object></p>\r\n<p>\r\n	下载地址</p>\r\n<br />",397,754);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c120524/133N353DD0-2G248.gif",756,839);
$z[7][4]['name']="litpic";

?>