{dede:field name='keywords'}少林三十六房BD高清迅雷下载，免{/dede:field}
{dede:field name='description'}少林三十六房BD高清迅雷下载、免费下载，少林三十六房BD高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}少林三十六房BD高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-10-03{/dede:field}
{dede:field name='body'}<p>
	<br />
	<img alt="" src="/uploads/allimg/c120525/133O02R0F-13514.jpg" /></p>
<p>
	◆原　　名：少林三十六房<br />
	◆译　　名：The.36th.Chamber.of.Shaolin<br />
	◆导　　演：刘家良<br />
	◆演　　员：刘家辉 罗烈 于洋 汪禹<br />
	◆类　　型：功夫<br />
	◆片　　长：110 分钟<br />
	◆上　　映：1978年<br />
	◆国　　家：香港<br />
	◆语　　言：中文<br />
	◆字　　幕：中文<br />
	◆文　　件：2CD 49 x 15MB x 2<br />
	◆文件格式：XviD + MP3<br />
	◆奖 项：1978年第24届亚洲影展 &mdash;&mdash; 最佳动作效果奖 (邵氏)<br />
	◆剧情简介:<br />
	　　此片为刘家班的少林武打经典之作，亦是1978年香港十大卖座电影；而同年更获亚洲影展最佳动作效果奖。刘家良师父执导下，由少林片系列代言人刘家辉当打演出，合演的还有70年代邵氏功夫明星，刘家荣、罗烈、汪禹、徐少强、袁小田及于洋等。刘家良导演坚持李小龙提倡的电影真实搏击风格，再加入传统国术的扎实功夫，鲜明地表现出华南武术文化传统精粹。此片不仅稳固了刘家良的导演地位，更令之成为一众同辈及后辈的武术指导争相仿效的对象。每一个镜头都是真打的，拍了120天，现在我们拍戏，10-20天就要拍完&nbsp;</p>
<p>
	<img alt="" src="/uploads/allimg/c120525/133O02R210-21953.jpg" style="width: 720px; height: 405px" /><img alt="" src="/uploads/allimg/c120525/133O02R2920-3E12.jpg" style="width: 720px; height: 405px" /></p>

<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="/uploads/allimg/c120524/133N2Z4FF-102231.jpg" />&nbsp;&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy125:piaohua@dy125.piaohua.com:6028/飘花电影piaohua.com少林三十六房BD国语中字1024高清.rmvb</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O02R3N0-4O13.jpg{/dede:field}
