{dede:field name='keywords'}梦宅诡影/凶宅藏私BD1280高清迅{/dede:field}
{dede:field name='description'}梦宅诡影/凶宅藏私BD1280高清迅雷下载、免费下载，梦宅诡影/凶宅藏私BD1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}梦宅诡影/凶宅藏私BD1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-01-16{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img165.poco.cn/mypoco/myphoto/20111216/08/62564813201112160820481859593649501_000.jpg" style="width: 500px; height: 582px" /></p>
<p>
	<img border="0" src="http://img165.poco.cn/mypoco/myphoto/20111216/20/56634212201112162033073936903403600_006.jpg" /></p>
<p>
	<img border="0" src="http://img165.poco.cn/mypoco/myphoto/20111216/20/56634212201112162033073936903403600_007.jpg" /></p>
<p>
	◎译　　名　梦宅诡影/梦宅/凶宅藏私(港)/灵异豪宅(台)<br />
	◎片　　名　Dream House<br />
	◎年　　代　2011<br />
	◎国　　家　美国<br />
	◎类　　别　剧情/神秘/惊悚<br />
	◎语　　言　英语<br />
	◎字　　幕　中字<br />
	◎IMDB评分 5.6/10 （3,440 votes）<br />
	◎IMDB链接 http://www.imdb.com/title/tt1462041/<br />
	◎文件格式　BD-RMVB<br />
	◎视频尺寸　1280 x 720<br />
	◎文件大小　1CD 979MB<br />
	◎片　　长　87 mins<br />
	◎导　　演　吉姆&middot;谢里丹 Jim Sheridan<br />
	◎主　　演　丹尼尔&middot;克雷格 Daniel Craig &hellip;.Will Atenton<br />
	　　　　　　蕾切尔&middot;薇姿 Rachel Weisz &hellip;.Libby Atenton<br />
	　　　　　　娜奥米&middot;沃茨 Naomi Watts &hellip;.Ann Patterson<br />
	　　　　　　马尔顿&middot;索克斯 Marton Csokas &hellip;.Jack Patterson<br />
	　　　　　　Claire Geare &hellip;.Dee Dee<br />
	　　　　　　泰勒&middot;吉蕾 Taylor Geare &hellip;.Trish<br />
	　　　　　　Rachel G. Fox &hellip;.Chloe Patterson<br />
	<br />
	<br />
	◎简　　介　<br />
	<br />
	　对某些人而言，一间好房子，会是他一生中许多美好回忆的地方。但对于出版商威尔（丹尼尔克雷格　饰）来说，这栋他即将搬去的豪宅，会是他一辈子挥之不去的恐怖梦魇&hellip;&hellip;<br />
	<br />
	　　事业有成的出版商威尔带着妻子（瑞秋怀兹　饰）与女儿搬到纽约郊区一栋被他视为是&lsquo;梦想住宅&rsquo;的豪宅居住，但他却未事先打探这间宅院的前身，在搬进去不久即发生连串光怪陆离的事情后，威尔才从邻居安（娜欧蜜华兹　饰）的口中得知，原来这是一栋发生过连续杀人惨案的凶宅，前一户家庭的妻女，在一夜之间惨遭虐杀，但男主人却在当晚人间蒸发，被疑为有重大罪嫌。<br />
	<br />
	　　当威尔一步步透过前一户人家遗留的物品，试图慢慢剖开这桩惨案的真相时，他也发现，在冥冥中似乎有人正盯着他。是失踪的前男主人又回来了吗？他们一家人会不会是下一个被杀戮的目标？<br />
	<br />
	<br />
	◎影片截图</p>
<p>
	<img alt="" src="http://img165.poco.cn/mypoco/myphoto/20111221/03/62564813201112210309413363345684624_002.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img165.poco.cn/mypoco/myphoto/20111221/03/62564813201112210309413363345684624_001.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img165.poco.cn/mypoco/myphoto/20111221/03/62564813201112210309413363345684624_000.jpg" style="width: 720px; height: 405px" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="&#13;&#10;ftp://dy125:piaohua@dy125.piaohua.com:7509/飘花电影piaohua.com梦宅诡影BD中字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:7509/飘花电影piaohua.com梦宅诡影BD中字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O16054330-41Y4.jpg{/dede:field}
