{dede:field name='keywords'}拯救大兵瑞恩BD国语配音中字经典{/dede:field}
{dede:field name='description'}拯救大兵瑞恩BD国语配音中字经典战争大片迅雷下载、免费下载，拯救大兵瑞恩BD国语配音中字经典战争大片Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}拯救大兵瑞恩BD国语配音中字经典战争大片{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-21{/dede:field}
{dede:field name='body'}<p>
	<img alt="Image" src="http://i3.6.cn/cvbnm/3e/47/a5/9f86e2ee3f713a6f586eb574b510c426.jpg" /></p>
<p>
	【译　　名】拯救大兵瑞恩/抢救雷恩大兵/雷霆救兵<br />
	【片　　名】Saving Private Ryan<br />
	【年　　代】1998<br />
	【国　　家】美国<br />
	【类　　别】动作/剧情/战争/历史<br />
	【语　　言】国语配音<br />
	【字　　幕】中字<br />
	【文件格式】RMVB+AAC<br />
	【IMDB评分】8.4/10 (162,078 votes) Top 250: #65<br />
	【片　　长】169 MiN<br />
	【导　　演】斯蒂文&middot;斯皮尔伯格 Steven Spielberg<br />
	【主　　演】汤姆&middot;汉克斯 Tom Hanks .....Captain John H. Miller<br />
	　　　　　　汤姆&middot;塞兹摩尔 Tom Sizemore .....Sergeant Mike Horvath<br />
	　　　　　　马特&middot;达蒙 Matt Damon .....Private James Francis Ryan<br />
	　　　　　　爱德华&middot;伯恩斯 Edward Burns .....Pvt. Richard Reiben<br />
	　　　　　　亚当&middot;戈德堡 Adam Goldberg .....Pvt. Stanley Mellish<br />
	　　　　　　范&middot;迪塞尔 Vin Diesel .....Private Adrian Caparzo<br />
	　　　　　　巴里&middot;佩珀 Barry Pepper .....Pvt. Daniel Jackson<br />
	　　　　　　吉奥瓦尼&middot;瑞比西 Giovanni Ribisi .....T-4 Medic Irwin Wade<br />
	　　　　　　杰瑞米&middot;戴维斯 Jeremy Davies .....Cpl. Timothy P. Upham<br />
	　　　　　　保罗&middot;吉亚玛提 Paul Giamatti .....Sergeant Hill<br />
	　　　　　　克里&middot;约翰逊 Corey Johnson .....Radioman<br />
	　　　　　　约翰&middot;沙拉恩 John Sharian .....Corporal<br />
	　　　　　　哈里逊&middot;杨 Harrison Young .....Ryan as Old Man<br />
	　　　　　　特德&middot;丹森 Ted Danson .....Captain Fred Hamill<br />
	【官方网站】：<a href="http://www.bluemv.com">http://www.bluemv.com</a><br />
	&nbsp;</p>
<p>
	【简　　介】</p>
<p>
	　　当百万大军登陆诺曼底海滩时，一小队由约翰&middot;米勒中尉（汤姆&middot;汉克斯饰演）率领的美军士兵却深入敌区，冒著生命危险拯救一名士兵詹姆斯&middot;雷恩（麦特&middot;戴蒙饰演）。詹姆斯&middot;雷恩是家中四兄弟的老幺，他的三名兄长都在这次战役中相继阵亡。美国作战总指挥部的将领为了不让这位不幸的母亲再承受丧子之痛，决定派一支特别小分队，将她仅存的儿子安全地救出战区。<br />
	　　当小分队的士兵们陷入敌区，面对随时降临的各种危险，他们逐渐怀疑这项任务的合理性：为什么这个士兵，就值得让八名士兵去冒死拯救？雷恩的一条命为何比他们的生命更有价值？但是，尽管他们心存疑惑，他们还是坚决执行上级的命令。<br />
	　　最后，雷恩活了下来，但那些去营救雷恩的八名士兵，全部壮烈牺牲。</p>
<p>
	[下载地址]： &nbsp;<img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" /></p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3019/飘花电影piaohua.com拯救大兵瑞恩BD国语配音中字.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3019/飘花电影piaohua.com拯救大兵瑞恩BD国语配音中字.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15032050-25S4.jpg{/dede:field}
