<?php
$z[0]=Array("field","滨崎步,HEAVEN(天堂)迅雷下载，",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","滨崎步 HEAVEN(天堂)迅雷下载、免费下载，滨崎步 HEAVEN(天堂)Gvod高清在线播放，剧情介绍等。",72,204);
$z[1][4]['name']="description";
$z[2]=Array("field","滨崎步 HEAVEN(天堂)",206,263);
$z[2][4]['name']="title";
$z[3]=Array("field","",265,304);
$z[3][4]['name']="writer";
$z[4]=Array("field","",306,345);
$z[4][4]['name']="source";
$z[5]=Array("field","2006-08-04",347,397);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<P>播放后双击视频“全屏”</P> \r\n\n<object classid=\"CLSID:22d6f312-b0f6-11d0-94ab-0080c74c7e95\" class=\"OBJECT\" id=\"MediaPlayer\" width=\"500\" height=\"350\" ><param name=\"ShowStatusBar\" value=\"-1\"><param name=\"Filename\" value=\"http://mp3.91.com/MP3Data/Start/TVShowWMA/tiantang.wmv\"></embed></object><br/> \r\n\n<P>下载地址 <br>",399,755);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c120524/133N353DD0-2G248.gif",757,840);
$z[7][4]['name']="litpic";

?>