{dede:field name='keywords'}滨崎步,HEAVEN(天堂)迅雷下载，{/dede:field}
{dede:field name='description'}滨崎步 HEAVEN(天堂)迅雷下载、免费下载，滨崎步 HEAVEN(天堂)Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}滨崎步 HEAVEN(天堂){/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2006-08-04{/dede:field}
{dede:field name='body'}<P>播放后双击视频“全屏”</P> 

<object classid="CLSID:22d6f312-b0f6-11d0-94ab-0080c74c7e95" class="OBJECT" id="MediaPlayer" width="500" height="350" ><param name="ShowStatusBar" value="-1"><param name="Filename" value="http://mp3.91.com/MP3Data/Start/TVShowWMA/tiantang.wmv"></embed></object><br/> 

<P>下载地址 <br>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120524/133N353DD0-2G248.gif{/dede:field}
