<?php
$z[0]=Array("field","10+10,DVD中字金马影展2012开幕",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","10+10 DVD中字金马影展2012开幕片迅雷下载、免费下载，10+10 DVD中字金马影展2012开幕片Gvod高清在线播放，剧情介绍等。",72,228);
$z[1][4]['name']="description";
$z[2]=Array("field","10+10 DVD中字金马影展2012开幕片",230,299);
$z[2][4]['name']="title";
$z[3]=Array("field","",301,340);
$z[3][4]['name']="writer";
$z[4]=Array("field","",342,381);
$z[4][4]['name']="source";
$z[5]=Array("field","2012-04-06",383,433);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",435,472);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://dy44:piaohua@dy44.piaohua.com:3153/飘花电影piaohua.com10+10 DVD中字金马影展2012开幕片.rmvb",474,609);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MQ442M0-16148.jpg",611,694);
$z[8][4]['name']="litpic";

?>