{dede:field name='keywords'}犯罪心理,第七季更新24集2011主{/dede:field}
{dede:field name='description'}犯罪心理 第七季更新24集2011主打美剧迅雷下载、免费下载，犯罪心理 第七季更新24集2011主打美剧Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}犯罪心理 第七季更新24集2011主打美剧{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-18{/dede:field}
{dede:field name='body'}<p>
	<a href="http://img.album.pchome.net/54/84/28/53/e2ffcc843a28c94f1871edb9971df9f4.jpg" target="_blank"><img alt="" border="0" heigth="400" src="http://img.album.pchome.net/54/84/28/53/e2ffcc843a28c94f1871edb9971df9f4.jpg" /></a></p>
<p>
	【译 &nbsp; &nbsp;　名】： 犯罪心理<br />
	【原 &nbsp; &nbsp;　名】： Criminal Minds<br />
	【年 &nbsp; &nbsp;　代】： 2005-2011<br />
	【国 &nbsp; &nbsp;　家】： 美国<br />
	【类 &nbsp; &nbsp;　别】： 动作|冒险|犯罪|剧情<br />
	【语 &nbsp; &nbsp;　言】： 英语<br />
	【首 &nbsp; &nbsp;　播】： 2005年9月22日|2010年9月22日（周三晚9点）<br />
	【电 &nbsp;视 &nbsp;台】： CBS 哥伦比亚广播公司(USA)<br />
	【IMDB评分】： 8.4/10 (14,902 人评价)<br />
	【集 &nbsp; &nbsp;　数】： 预计 24 集<br />
	【片 &nbsp; &nbsp;　长】： 平均 60 分钟<br />
	【导 &nbsp; &nbsp;　演】：&bull; F&eacute;lix Enr&iacute;quez Alcal&aacute; &nbsp;... &nbsp;(11集 2005-2009)<br />
	　　　　　　　 &bull; Edward Allen Bernero &nbsp;... &nbsp;(11集 2006-2010)<br />
	　　　　　　　 &bull; John E. Gallagher &nbsp;... &nbsp;(11集 2007-2011)<br />
	　　　　　　　 &bull; Guy Norman Bee &nbsp;... &nbsp;(10集 2005-2010)<br />
	　　　　　　　 &bull; Glenn Kershaw &nbsp;... &nbsp;(10集 2006-2010)<br />
	【编 &nbsp; &nbsp;　剧】：&bull; Jeff Davis &nbsp;... &nbsp;(135集 2005-2011)<br />
	　　　　　　　 &bull; Erica Messer &nbsp;... &nbsp;(19集 2005-2011)<br />
	　　　　　　　 &bull; Edward Allen Bernero &nbsp;... &nbsp;(15集 2005-2010)<br />
	　　　　　　　 &bull; Chris Mundy &nbsp;... &nbsp;(14集 2006-2010)<br />
	　　　　　　　 &bull; Simon Mirren &nbsp;... &nbsp;(13集 2005-2011)<br />
	　　　　　　　 &bull; Debra J. Fisher &nbsp;... &nbsp;(12集 2005-2009)<br />
	　　　　　　　 &bull; Andrew Wilder &nbsp;... &nbsp;(9集 2005-2009)<br />
	　　　　　　　 &bull; Jay Beattie &nbsp;... &nbsp;(8集 2007-2009)<br />
	　　　　　　　 &bull; Dan Dworkin &nbsp;... &nbsp;(8集 2007-2009)<br />
	【演 &nbsp; &nbsp;　员】：&bull; Shemar Moore &nbsp;饰演 &nbsp;Derek Morgan (136集 2005-2011)<br />
	　　　　　　　 &bull; Matthew Gray Gubler &nbsp;饰演 &nbsp;Dr. Spencer Reid (136集 2005-2011)<br />
	　　　　　　　 &bull; Thomas Gibson &nbsp;饰演 &nbsp;Aaron &#39;Hotch&#39; Hotchner (136集 2005-2011)<br />
	　　　　　　　 &bull; Kirsten Vangsness &nbsp;饰演 &nbsp;Penelope Garcia (134集 2005-2011)<br />
	　　　　　　　 &bull; A.J. Cook &nbsp;饰演 &nbsp;Jennifer &#39;JJ&#39; Jareau (115集 2005-2011)<br />
	　　　　　　　 &bull; Paget Brewster &nbsp;饰演 &nbsp;Emily Prentiss (101集 2006-2011)<br />
	　　　　　　　 &bull; Joe Mantegna &nbsp;饰演 &nbsp;David Rossi (86集 2007-2011)<br />
	　　　　　　　 &bull;<br />
	【简 &nbsp; &nbsp;　介】：<br />
	<img alt="" border="0" jquery1316835716484="3" src="http://i.imgur.com/KR1Xa.jpg" style="max-width: 780px" /><br />
	　　『Criminal Minds』是CBS电视台出品的一部反映美国FBI下属部门BAU（Behavioral Analysis Unit）中一组行为分析人员运用心理分析、侧写等方法破获一系列连环杀人案的剧集。每集独立成剧，被众多CM迷称为&ldquo;一集一电影&rdquo;，可见拍摄制作水平之高超。<br />
	<br />
	　　由资深行为分析专家Jason Gideon领军的这个小组拥有以律师身份加入FBI的Aaron Hotchner、专攻性侵害案件的女特工Elle Greenaway（因创伤后应激障碍，已离开小组）、擅长罪犯行为模拟的强制性犯罪行为专家Derek Morgan、年轻的天才&ldquo;百科全书&rdquo;Dr. Spencer Reid以及在第二季新加入小组的Emily Prentiss。<br />
	<br />
	　　该组专属的新闻发言官Jennifer Jareau和电脑天使Penelope Garcia也是破案中不可或缺的重要环节。<br />
	<br />
	　　在第一季中，一件又一件连环变态杀人案，带给我们的不仅是视觉和心理的冲击，更是心灵的震撼。在罪行中反思，让我们更好的调节心态面对生活。<br />
	<br />
	　　随着第一季的发展，我们也见识到了这组行为分析人员工作背后多姿多彩的生活面。<br />
	<br />
	　　本剧还有一大亮点就是每集都会出现几句名人名言，一般是在片头片尾，少数会出现在剧中。这一特色也成为了众多CM迷珍藏的经典。<br />
	<br />
	　　上季结尾，调查组一直在追踪一个连环杀手，但他们自己也面临危险。在新季中，Emily（Paget Brewster扮演）只会出现80%的时间，而JJ（AJ Cook扮演）仅出现两集。虽然AJ Cook已永远离开该剧，但剧组很快又填补了这个空缺：Kirsten Vangsness将同时演出该剧和该剧的衍生剧《犯罪心理：疑犯动机》（2011春季播出）。Kirsten Vangsness扮演的Penelope Garcia是个计算机技术专家，同时为这两个分析组服务。<br />
	<br />
	　　在新季首集中，连环杀手（Billy Flynn扮演）继续在洛杉矶大开杀戒，行为分析组越来越逼近他－－但是Spicer侦探的女儿仍然在他手上。</p>
<p>
	[下载地址]：&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:1760/飘花电影piaohua.com犯罪心理第七季01集[中英双字].rmvb">&nbsp;ftp://dy44:piaohua@dy44.piaohua.com:1760/飘花电影piaohua.com犯罪心理第七季01集[中英双字].rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:1760/飘花电影piaohua.com犯罪心理第七季02集[中英双字].rmvb">&nbsp;ftp://dy44:piaohua@dy44.piaohua.com:1760/飘花电影piaohua.com犯罪心理第七季02集[中英双字].rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:1760/飘花电影piaohua.com犯罪心理第七季03集[中英双字].rmvb">&nbsp;ftp://dy44:piaohua@dy44.piaohua.com:1760/飘花电影piaohua.com犯罪心理第七季03集[中英双字].rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:1812/飘花电影piaohua.com犯罪心理第七季04集[中英双字].rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:1812/飘花电影piaohua.com犯罪心理第七季04集[中英双字].rmvb">ftp://dy44:piaohua@dy44.piaohua.com:1812/飘花电影piaohua.com犯罪心理第七季04集[中英双字].rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:1993/飘花电影piaohua.com犯罪心理第七季05集[中英双字].rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:1993/飘花电影piaohua.com犯罪心理第七季05集[中英双字].rmvb">ftp://dy44:piaohua@dy44.piaohua.com:1993/飘花电影piaohua.com犯罪心理第七季05集[中英双字].rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:1993/飘花电影piaohua.com犯罪心理第七季06集[中英双字].rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:1993/飘花电影piaohua.com犯罪心理第七季06集[中英双字].rmvb">ftp://dy44:piaohua@dy44.piaohua.com:1993/飘花电影piaohua.com犯罪心理第七季06集[中英双字].rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2114/飘花电影piaohua.com犯罪心理第七季07.rmvb ">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:2114/飘花电影piaohua.com犯罪心理第七季07.rmvb ">ftp://dy44:piaohua@dy44.piaohua.com:2114/飘花电影piaohua.com犯罪心理第七季07.rmvb </a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2114/飘花电影piaohua.com犯罪心理第七季08.rmvb ">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:2114/飘花电影piaohua.com犯罪心理第七季08.rmvb ">ftp://dy44:piaohua@dy44.piaohua.com:2114/飘花电影piaohua.com犯罪心理第七季08.rmvb </a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2291/飘花电影piaohua.com犯罪心理第七季09.rmvb ">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:2291/飘花电影piaohua.com犯罪心理第七季09.rmvb ">ftp://dy44:piaohua@dy44.piaohua.com:2291/飘花电影piaohua.com犯罪心理第七季09.rmvb </a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2344/飘花电影piaohua.com犯罪心理第七季10.rmvb ">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:2344/飘花电影piaohua.com犯罪心理第七季10.rmvb ">ftp://dy44:piaohua@dy44.piaohua.com:2344/飘花电影piaohua.com犯罪心理第七季10.rmvb </a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2668/飘花电影piaohua.com犯罪心理第七季11.rmvb ">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:2668/飘花电影piaohua.com犯罪心理第七季11.rmvb ">ftp://dy44:piaohua@dy44.piaohua.com:2668/飘花电影piaohua.com犯罪心理第七季11.rmvb </a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2701/飘花电影piaohua.com犯罪心理第七季12.rmvb ">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:2701/飘花电影piaohua.com犯罪心理第七季12.rmvb ">ftp://dy44:piaohua@dy44.piaohua.com:2701/飘花电影piaohua.com犯罪心理第七季12.rmvb </a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2783/飘花电影piaohua.com犯罪心理第七季13.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:2783/飘花电影piaohua.com犯罪心理第七季13.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2783/飘花电影piaohua.com犯罪心理第七季13.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2834/飘花电影piaohua.com犯罪心理第七季14.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:2834/飘花电影piaohua.com犯罪心理第七季14.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2834/飘花电影piaohua.com犯罪心理第七季14.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2882/飘花电影piaohua.com犯罪心理第七季15.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:2882/飘花电影piaohua.com犯罪心理第七季15.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2882/飘花电影piaohua.com犯罪心理第七季15.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2935/飘花电影piaohua.com犯罪心理第七季16.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:2935/飘花电影piaohua.com犯罪心理第七季16.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2935/飘花电影piaohua.com犯罪心理第七季16.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3024/飘花电影piaohua.com犯罪心理第七季17.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3024/飘花电影piaohua.com犯罪心理第七季17.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3024/飘花电影piaohua.com犯罪心理第七季17.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3089/飘花电影piaohua.com犯罪心理第七季18.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3089/飘花电影piaohua.com犯罪心理第七季18.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3089/飘花电影piaohua.com犯罪心理第七季18.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3155/飘花电影piaohua.com犯罪心理第七季19.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3155/飘花电影piaohua.com犯罪心理第七季19.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3155/飘花电影piaohua.com犯罪心理第七季19.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3229/飘花电影piaohua.com犯罪心理第七季20.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3229/飘花电影piaohua.com犯罪心理第七季20.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3229/飘花电影piaohua.com犯罪心理第七季20.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3346/飘花电影piaohua.com犯罪心理第七季21.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3346/飘花电影piaohua.com犯罪心理第七季21.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3346/飘花电影piaohua.com犯罪心理第七季21.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3450/飘花电影piaohua.com犯罪心理第七季22.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3450/飘花电影piaohua.com犯罪心理第七季22.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3450/飘花电影piaohua.com犯罪心理第七季22.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3450/飘花电影piaohua.com犯罪心理第七季23-24.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3450/飘花电影piaohua.com犯罪心理第七季23-24.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3450/飘花电影piaohua.com犯罪心理第七季23-24.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1A521F-23352.jpg{/dede:field}
