{dede:field name='keywords'}突击2011DVD法语/中字迅雷下载，{/dede:field}
{dede:field name='description'}突击2011DVD法语/中字迅雷下载、免费下载，突击2011DVD法语/中字Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}突击2011DVD法语/中字{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-07-20{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://pic.piaohua.com/0701pic/allimg/110720/1-110H0145142312.jpg" style="width: 492px; height: 610px" /></p>
<p>
	&nbsp;<br />
	片名： 突击&nbsp; L&#39;assaut<br />
	导演： 朱莉安&middot;勒克莱克<br />
	主演： 樊尚&middot;埃尔巴兹 格雷戈里&middot;德朗杰尔 梅兰妮&middot;贝尔内尔<br />
	上映日期： 2011年3月9日&nbsp;&nbsp; 法国<br />
	国家/地区： 法国&nbsp;<br />
	类型： 惊悚&nbsp;<br />
	片长：95 min<br />
	对白语言： 法语&nbsp;</p>
<p>
	<br />
	影片简介</p>
<p>
	根据史上著名的&ldquo;法国航空8969号班机劫机事件&rdquo;改编。1994年12月24日上午，一架法国航空公司的空中客车飞机在阿尔及利亚首都阿尔及尔机场被4个伊斯 兰 武装分子劫持，机上265名乘客和12名机组人员被扣作人质。并在当晚将两名人质杀害。飞机上的乘客有阿尔及利亚人、阿法双重国籍人和法国驻阿使馆的外交官等，他们中的大多数人是回法国过圣诞节的。这架飞机是在临起飞前被劫持的。武装分子属于伊斯 兰拯救阵线的一个极端组织，他们已发出最后通牒，要求在25日格林尼治时间9时前释放两名被关押的伊斯 兰拯救阵线领导成员，否则将杀害更多人质。</p>
<p>
	<br />
	◎影片截图</p>
<p>
	<img alt="" src="http://pic.piaohua.com/0701pic/allimg/110720/1-110H0145223E8.jpg" style="width: 600px; height: 361px" /></p>
<p>
	<img alt="" src="http://pic.piaohua.com/0701pic/allimg/110720/1-110H0145230503.jpg" style="width: 600px; height: 375px" /></p>
<p>
	[下载地址]： &nbsp;<img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:1060/飘花电影piaohua.com突击2011DVD法语中字.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:1060/飘花电影piaohua.com突击2011DVD法语中字.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O161J0P-23502.jpg{/dede:field}
