{dede:field name='keywords'}盖茨堡之役720P,1280*720迅雷下{/dede:field}
{dede:field name='description'}盖茨堡之役720P 1280*720迅雷下载、免费下载，盖茨堡之役720P 1280*720Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}盖茨堡之役720P 1280*720{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-07-29{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img3.douban.com/view/photo/photo/public/p854705273.jpg" style="width: 439px; height: 600px" /></p>
<p>
	导演: Ronald F. Maxwell<br />
	编剧: Michael Shaara / Ronald F. Maxwell<br />
	主演: Martin Sheen / Stephen Lang / Jeff Daniels<br />
	类型: 剧情 / 历史 / 战争<br />
	制片国家/地区: 美国<br />
	语言: 英语<br />
	上映日期: 1993-10-08<br />
	片长: 261 分钟 / Sweden: 254 分钟 / UK: 259 分钟 / Netherlands: 244 分钟<br />
	又名: 美国战火 / 葛底斯堡</p>
<h2>
	盖茨堡之役的剧情简介 &middot; &middot; &middot; &middot; &middot; &middot;</h2>
<div class="indent">
	　　1863年7月1日，十五万名士兵在命运安排下，相会于美国的盖兹堡；他们各自为了理想中的民主政治抛头颅洒热血。结果，有三分之一的人倒于寂静的麦田中；他们的生命创造了南北战争的转折点，这场战役是历史上的盖兹堡大战。<br />
	&nbsp;</div>
<p>
	<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20110729/14/17870980201107291400529163435013853_019.jpg" style="width: 640px; height: 360px" /></p>
<p>
	<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20110729/14/17870980201107291400529163435013853_016.jpg" style="width: 640px; height: 360px" /><br />
	&nbsp;</p>
<p>
	[下载地址]： &nbsp;<img border="0" src="/images/1d5d785194cc53c388c37ac6d66c5bd3.jpg" /></p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy125:piaohua@dy125.piaohua.com:1030/飘花电影下载站www.xiaozhizhu.net盖茨堡之役720p.mkv">ftp://dy125:piaohua@dy125.piaohua.com:1030/飘花电影下载站www.xiaozhizhu.net盖茨堡之役720p.mkv</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O161M360-42547.jpg{/dede:field}
