{dede:field name='keywords'}天才冲冲冲-20110716迅雷下载，{/dede:field}
{dede:field name='description'}天才冲冲冲-20110716迅雷下载、免费下载，天才冲冲冲-20110716Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}天才冲冲冲-20110716{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-07-21{/dede:field}
{dede:field name='body'}<p>
	<img src="/uploads/allimg/c120524/133N4ON010-14B7.jpg" /></p>
<p>
	类型：综艺 / 港台综艺<br />
	首映：2006年5月12日 中国台湾</p>
<p>
	&nbsp;剧情：</p>
<p>
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 由《天才向前冲》改版而来。节目介绍：【給我TEMPO】這是一個造成社會流行、大家爭相學習的口語節奏遊戲。電視史上首創新穎的畫面、刺激的遊戲；讓所有藝人專心一致，考驗口條與機智反應的遊戲。藉著由慢而快的各種口語節奏遊戲，考驗著現場所有藝人的大腦瞬間反應，耳朵、手、嘴巴以及大腦之間的協調性絕對不是一般人可以做得到的！趣味橫生的全新世...</p>
<p>
	[下载地址]： &nbsp;<img border="0" src="/uploads/allimg/c120524/133N2Z4FF-102231.jpg" /></p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy171:piaohua@dy171.piaohua.com:1041/飘花电影piaohua.com天才冲冲冲-20110709.rmvb</td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy171:piaohua@dy171.piaohua.com:1041/飘花电影piaohua.com天才冲冲冲-20110716.rmvb</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120524/133N4ONK0-23638.jpg{/dede:field}
