{dede:field name='keywords'}憨豆先生的大灾难/憨豆先生BD中{/dede:field}
{dede:field name='description'}憨豆先生的大灾难/憨豆先生BD中英双字1024/1280高清迅雷下载、免费下载，憨豆先生的大灾难/憨豆先生BD中英双字1024/1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}憨豆先生的大灾难/憨豆先生BD中英双字1024/1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-16{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://3e:3e@d8.3edyy.com:190/【3E电影院www.eee4.org】憨豆先生的大灾难BD中英双字1024x576高清版.rmvb" target="_blank{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MO602140-25D0.jpg{/dede:field}
