<?php
$z[0]=Array("field","魔岛迷踪/铁[DVD中英双字]迅雷下",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","魔岛迷踪/铁[DVD中英双字]迅雷下载、免费下载，魔岛迷踪/铁[DVD中英双字]Gvod高清在线播放，剧情介绍等。",73,215);
$z[1][4]['name']="description";
$z[2]=Array("field","魔岛迷踪/铁[DVD中英双字]",217,279);
$z[2][4]['name']="title";
$z[3]=Array("field","",281,320);
$z[3][4]['name']="writer";
$z[4]=Array("field","",322,361);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-07-06",363,413);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",415,452);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://3e:3e@m1.eee4.cc:1506/【3e电影网www.eee4.cc】魔岛迷踪DVD中英双字.rmvb\" target=_blank>ftftp://3e:3e@m1.eee4.cc:1506/【3e电影网www.eee4.cc】魔岛迷踪DVD中英双字.rmvb</A></TD></TR></TBODY></TABLE></div><ul class=\"mmlist",454,714);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MP314610-34533.jpg",716,800);
$z[8][4]['name']="litpic";

?>