<?php
$z[0]=Array("field","海啸,(TSUNAMI)2006最新灾难片迅",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","海啸 (TSUNAMI)2006最新灾难片迅雷下载、免费下载，海啸 (TSUNAMI)2006最新灾难片Gvod高清在线播放，剧情介绍等。",73,223);
$z[1][4]['name']="description";
$z[2]=Array("field","海啸 (TSUNAMI)2006最新灾难片",225,291);
$z[2][4]['name']="title";
$z[3]=Array("field","",293,332);
$z[3][4]['name']="writer";
$z[4]=Array("field","",334,373);
$z[4][4]['name']="source";
$z[5]=Array("field","2006-08-02",375,425);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",427,464);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://61.175.222.10:2121/06",466,532);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MO60K30-35C0.gif",534,616);
$z[8][4]['name']="litpic";

?>