<?php
$z[0]=Array("field","CCTV央视2011兔年春节联欢晚会全",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","CCTV央视2011兔年春节联欢晚会全场完整版迅雷下载、免费下载，CCTV央视2011兔年春节联欢晚会全场完整版Gvod高清在线播放，剧情介绍等。",73,243);
$z[1][4]['name']="description";
$z[2]=Array("field","CCTV央视2011兔年春节联欢晚会全场完整版",245,321);
$z[2][4]['name']="title";
$z[3]=Array("field","",323,362);
$z[3][4]['name']="writer";
$z[4]=Array("field","",364,403);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-02-04",405,455);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",457,494);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://4e:4e@d6.3edyy.com:619/【3E看看www.3ekk.com】央视2011兔年春节联欢晚会.rmvb\" target=_blank>ftftp://4e:4e@d6.3edyy.com:619/【3E看看www.3ekk.com】央视2011兔年春节联欢晚会.rmvb</A></TD></TR></TBODY></TABLE></div><ul class=\"mmlist",496,766);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MQ4CF-1AP.jpg",768,847);
$z[8][4]['name']="litpic";

?>