{dede:field name='keywords'}辛普森一家/辛普森大电影/辛普森{/dede:field}
{dede:field name='description'}辛普森一家/辛普森大电影/辛普森家庭BD中英双字1280高清迅雷下载、免费下载，辛普森一家/辛普森大电影/辛普森家庭BD中英双字1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}辛普森一家/辛普森大电影/辛普森家庭BD中英双字1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-12-21{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="/uploads/allimg/c120525/133O043444F-24I29.jpg" /></p>
<p>
	◎中文片名：《辛普森一家/辛普森大电影/辛普森家庭》07美国动画大片DVD国语中字无水印<br />
	◎英文片名：The Simpsons Movie<br />
	◎出品年代：2007<br />
	◎国家地区：美国<br />
	◎类　　别：动画<br />
	◎对白语言：普通话<br />
	◎字　　幕：简体中文<br />
	◎文件格式：rmvb<br />
	◎文件大小：1CD 584M<br />
	◎视频大小：800 x 396(黑边60)<br />
	◎片　　长：01:26:44<br />
	◎导　　演：大卫&middot;西佛曼<br />
	◎主要演员：丹&middot;卡斯泰兰尼塔 朱莉&middot;凯夫纳 南希&middot;卡特怀特<br />
	◎简　　介：</p>
<p>
	　　本片是在美国连播18年TV动画的银幕版，原电视剧集的《辛普森一家》（又译《辛普森家庭》）电影下载讲述的是美国人辛普森一家的生活，父亲荷马是Springfield核能工厂的安全检查员，总体说来是一个善意的小丑。母亲马芝曾经是一个很有深度的女人，但渐渐地适应了主妇生活的定式。巴特，辛普森家的长子，经常惹麻烦。妹妹丽莎是一个很聪明的学生，素食主义者，佛教徒，爵士乐迷。幼女马姬是一个永远长不大的孩子，这一家庭面临着一个个普通家庭都会遇到的生活难题。此剧集用辛辣的讽刺展现了人类的生存状态，不过主要讽刺美国中部的生活模式，以致更广泛的美国文化。<br />
	　　这一次故事的主角是荷马，他惹出了天大的麻烦&mdash;&mdash;足以毁灭整个世界的大麻烦&hellip;&hellip;</p>
<p>
	<img alt="" border="0" onclick="zoom(this, 'attachments/20090531_a8596a1cafe195f91f8dtZljs2XYdxEH.jpg')" onload="attachimg(this, 'load')" onmouseout="attachimginfo(this, 'attach_122376', 0, event)" onmouseover="attachimginfo(this, 'attach_122376', 1);attachimg(this, 'mouseover')" src="http://bbs.3e-online.com/attachments/20090531_a8596a1cafe195f91f8dtZljs2XYdxEH.jpg" /></p>
<p>
	【电影截图】：<br />
	<br />
	&nbsp;<br />
	<img alt="" border="0" onclick="zoom(this, 'attachments/20090531_024629083df74d8d5e97KepKC6sa7hQL.jpg')" onload="attachimg(this, 'load')" onmouseout="attachimginfo(this, 'attach_122378', 0, event)" onmouseover="attachimginfo(this, 'attach_122378', 1);attachimg(this, 'mouseover')" src="http://bbs.3e-online.com/attachments/20090531_024629083df74d8d5e97KepKC6sa7hQL.jpg" /></p>
<br />
<p>

	07美国动画大片《辛普森一家》DVD国语中字无水印 ：<img border="0" src="http://www.eee4.com/templets/img/down.jpg" /></p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				ftp://3e:3e@www2.eee4.com:196/[3E电影站www.eee4.com]辛普森一家DVD国语中字无水印.rmvb</td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				&nbsp;ftp://dy44:piaohua@dy44.piaohua.com:2398/飘花电影piaohua.com辛普森家庭BD中英双字1280高清.rmvb</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O0434b40-2T603.jpg{/dede:field}
