<?php
$z[0]=Array("field","♂真实感情,♀,我没那种命迅雷下",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","♂真实感情 ♀ 我没那种命迅雷下载、免费下载，♂真实感情 ♀ 我没那种命Gvod高清在线播放，剧情介绍等。",73,215);
$z[1][4]['name']="description";
$z[2]=Array("field","♂真实感情 ♀ 我没那种命",217,279);
$z[2][4]['name']="title";
$z[3]=Array("field","",281,320);
$z[3][4]['name']="writer";
$z[4]=Array("field","",322,361);
$z[4][4]['name']="source";
$z[5]=Array("field","2006-08-04",363,413);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<P>播放后双击视频“全屏”</P> \n<object classid=\"CLSID:22d6f312-b0f6-11d0-94ab-0080c74c7e95\" class=\"OBJECT\" id=\"MediaPlayer\" width=\"500\" height=\"350\" ><param name=\"ShowStatusBar\" value=\"-1\"><param name=\"Filename\" value=\"http://wma.16165.com:8000/mtvfiles/mtv/1/cxc/cxc_mnzm.wmv\"></embed></object><br /> \n<P>下载地址<BR></P> <br>",415,779);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c120524/133N353DD0-2G248.gif",781,864);
$z[7][4]['name']="litpic";

?>