<?php
$z[0]=Array("field","地狱神探[DVD中英双字1024/1280",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","地狱神探[DVD中英双字1024/1280高清版]迅雷下载、免费下载，地狱神探[DVD中英双字1024/1280高清版]Gvod高清在线播放，剧情介绍等。",72,238);
$z[1][4]['name']="description";
$z[2]=Array("field","地狱神探[DVD中英双字1024/1280高清版]",240,314);
$z[2][4]['name']="title";
$z[3]=Array("field","",316,355);
$z[3][4]['name']="writer";
$z[4]=Array("field","",357,396);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-11-12",398,448);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",450,487);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://eee4.com:8114@vip11.eee4.com:8114/[3E迅雷电影站www.eee4.com]地狱神探DVD中英字幕1024x576高清版.rmvb\" target=\"_blank",489,648);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MOa3H0-36212.jpg",650,732);
$z[8][4]['name']="litpic";

?>