<?php
$z[0]=Array("field","笑傲江湖HD高清1024*576许冠杰",0,69);
$z[0][4]['name']="keywords";
$z[1]=Array("field","笑傲江湖HD高清1024*576许冠杰版粤语中字迅雷下载、免费下载， 笑傲江湖HD高清1024*576许冠杰版粤语中字Gvod高清在线播放，剧情介绍等。",71,242);
$z[1][4]['name']="description";
$z[2]=Array("field","笑傲江湖HD高清1024*576许冠杰版粤语中字",244,320);
$z[2][4]['name']="title";
$z[3]=Array("field","",322,361);
$z[3][4]['name']="writer";
$z[4]=Array("field","",363,402);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-08-19",404,454);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",456,493);
$z[6][4]['name']="body";
$z[7]=Array("field","",495,534);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MQ255130-39507.jpg",536,620);
$z[8][4]['name']="litpic";

?>