<?php
$z[0]=Array("field","危情时速/煞破天劫/煞不住/不可",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","危情时速/煞破天劫/煞不住/不可阻挡/无可阻止[BD中字1024x576高清版]迅雷下载、免费下载，危情时速/煞破天劫/煞不住/不可阻挡/无可阻止[BD中字1024x576高清版]Gvod高清在线播放，剧情介绍等。",72,294);
$z[1][4]['name']="description";
$z[2]=Array("field","危情时速/煞破天劫/煞不住/不可阻挡/无可阻止[BD中字1024x576高清版]",296,398);
$z[2][4]['name']="title";
$z[3]=Array("field","",400,439);
$z[3][4]['name']="writer";
$z[4]=Array("field","",441,480);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-01-24",482,532);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",534,571);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://3e:3e@d3.3edyy.com:131/【3E看看www.3ekk.com】危情时速[BD中字1024x576高清版].rmvb\" target=_blank>ftftp://3e:3e@d3.3edyy.com:131/【3E看看www.3ekk.com】危情时速[BD中字1024x576高清版].rmvb</A></TD></TR></TBODY></TABLE></P></div><ul class=\"mmlist",573,859);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MPY4140-1F50.jpg",861,943);
$z[8][4]['name']="litpic";

?>