<?php
$z[0]=Array("field","侏罗纪公园3BD中英双字1024/1280",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","侏罗纪公园3BD中英双字1024/1280高清迅雷下载、免费下载，侏罗纪公园3BD中英双字1024/1280高清Gvod高清在线播放，剧情介绍等。",73,235);
$z[1][4]['name']="description";
$z[2]=Array("field","侏罗纪公园3BD中英双字1024/1280高清",237,309);
$z[2][4]['name']="title";
$z[3]=Array("field","",311,350);
$z[3][4]['name']="writer";
$z[4]=Array("field","",352,391);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-11-01",393,443);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",445,482);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://e64:e64@xl2.eee4.com:9306/[3E电影站www.eee4.com]侏罗纪公园3HD中英字幕1280×720高清析版.rmvb\" target=\"_blank",484,636);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MO961a0-2C19.jpg",638,720);
$z[8][4]['name']="litpic";

?>