{dede:field name='keywords'}蝙蝠侠:第一年BD中英双字1024/12{/dede:field}
{dede:field name='description'}蝙蝠侠:第一年BD中英双字1024/1280高清2011动画迅雷下载、免费下载，蝙蝠侠:第一年BD中英双字1024/1280高清2011动画Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}蝙蝠侠:第一年BD中英双字1024/1280高清2011动画{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-11-04{/dede:field}
{dede:field name='body'}<p>
	&nbsp;<img alt="" height="748" src="/uploads/allimg/c120525/133O044Z610-2N5M.jpg" width="549" /></p>


<p>
	【影片原名】Batman: Year One<br />
	【中文译名】蝙蝠侠:第一年/蝙蝠侠:元年<br />
	【出品年代】2011 年<br />
	【IMDB评分】7.3/10 (1,024 votes)<br />
	【国　　家】美国<br />
	【类　　别】动画<br />
	【文件格式】Rmvb<br />
	【文件大小】691 MB<br />
	【视频尺寸】1280 x 720<br />
	【影片长度】64 Mins<br />
	【对白语言】英语/法语/西班牙语<br />
	【字幕语言】中英双字幕<br />
	【导　　演】Sam Liu ....(co-director)<br />
	　　　　　　Lauren Montgomery ....(co-director)<br />
	【主　　演】本杰明&middot;麦肯锡 Benjamin McKenzie ....Bruce Wayne / Batman (voice)<br />
	　　　　　　艾丽莎&middot;杜什库 Eliza Dushku ....Selina Kyle / Catwoman (voice)<br />
	　　　　　　布莱恩&middot;科兰斯顿 Bryan Cranston ....James Gordon (voice)<br />
	　　　　　　凯缇&middot;萨克霍夫 Katee Sackhoff ....Detective Sarah Essen (voice)<br />
	　　　　　　乔&middot;鲍里托 Jon Polito ....Commissioner Loeb (voice)<br />
	　　　　　　阿历克斯&middot;罗克 Alex Rocco ....Carmine Falcone (voice)<br />
	<br />
	【内容简介】<br />
	<br />
	　　此时的蝙蝠侠并不是无敌的英雄,只是一个初出茅庐的新手,只要踏错一步就意味着死亡;戈登也还没有当上警察局长,而要靠双手在已经从上到下彻底烂掉的警局打出自己的天下,同时他本人在道德上也并不完美。书中的其他人物也不再具有浪漫的传奇色彩,而是被抛到了无情的社会现实之中:邓特(后来的罪犯&ldquo;双面人&rdquo;)不是令人瞩目的青年才俊,而是屡败屡战的检察官;猫女不是上流社会的优雅贵妇,只是一名出身街头的穷妓女。在他们生存的哥谭市里,官员们同黑帮勾结,警察是罪犯的保护伞。新调来的警官詹姆斯&middot;戈登想在一个堕落的城市做一名好警察;刚刚回到故乡准备扫尽罪孽的布鲁斯&middot;韦恩则在流血中懂得,惟有让人恐惧才能叫人尊敬。这不是五彩的英雄世界,而是罪恶之城的蝙蝠版本;这不是神的传说,而是人的故事。<br />
	<br />
	【影片截图】<br />
	<br />
	<img alt="" height="337" src="/uploads/allimg/c120525/133O04491D0-2S034.jpg" style="cursor: pointer" width="600" /><br />
	<img alt="" height="337" src="/uploads/allimg/c120525/133O04492260-2bB2.jpg" style="cursor: pointer" width="600" /><br />
	<img alt="" height="337" src="/uploads/allimg/c120525/133O04492U0-306437.jpg" style="cursor: pointer" width="600" /><br />
	&nbsp;</p>

<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="/uploads/allimg/c120524/133N2Z4FF-102231.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				&nbsp;&nbsp;ftp://dy44:piaohua@dy44.piaohua.com:1943/飘花电影piaohua.com蝙蝠侠第一年BD中英双字1280高清.rmvb&nbsp;</td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				&nbsp;&nbsp;ftp://dy44:piaohua@dy44.piaohua.com:1990/飘花电影piaohua.com蝙蝠侠第一年BD中英双字1024高清.rmvb&nbsp;</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O04493430-313R6.jpg{/dede:field}
