{dede:field name='keywords'}床下有人HD1280高清迅雷下载，免{/dede:field}
{dede:field name='description'}床下有人HD1280高清迅雷下载、免费下载，床下有人HD1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}床下有人HD1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-04-14{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://p.dmdjz.com/uploads/2012/04/p1230923975.jpg" style="width: 428px; height: 600px" /></p>
<p>
	导演: 牛朝阳<br />
	编剧: 牛朝阳 / 牛朝杰<br />
	主演: 何可人 / 郭晓然 / 武文佳 / 葛红霖<br />
	类型: 惊悚 / 恐怖<br />
	制片国家/地区: 中国大陆<br />
	语言: 汉语普通话<br />
	上映日期: 2011-10-14(中国大陆)<br />
	片长: 100分钟<br />
	又名: Who Under The Bed<br />
	<br />
	床下有人的剧情简介 &middot; &middot; &middot; &middot; &middot; &middot;<br />
	　　多年前发生在云南的一场大火，让冰儿（何可人 饰）失去了恋人小明（葛红霖 饰），自此她不仅深陷痛失爱人的痛苦中无法自拔，甚至经常梦见在一间纯白的房间内，床下伸出一双惨白的手抓她。在和英俊的况宇（郭晓然 饰）结婚后，冰儿的情况已久没有好转。某天，夫妻俩来到某古城旅游，这曾是小明许诺带冰儿来的地方。令人难以置信的是，小明并没有死去，他全身烧成重伤，不愿出现在冰儿的面前，而独自隐居于此，并嘱托况宇照顾爱人。<br />
	　　夫妻俩下榻在由百年古宅改造的春秋客栈，可是每到夜晚，各种恐怖阴冷的事件就开始发生，惨白的女鬼从床下爬出，搅扰着生者与死者的神经&hellip;&hellip;<br />
	<img alt="" src="http://p.dmdjz.com/uploads/2012/04/thumbs20120412133138.jpg" style="width: 650px; height: 1507px" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.net/" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy125:piaohua@dy125.piaohua.com:7840/飘花电影piaohua.com床下有人HD国语中字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:7840/飘花电影piaohua.com床下有人HD国语中字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O16296160-4E36.jpg{/dede:field}
