{dede:field name='keywords'}无所畏惧Chris,Rock2004年HBO华{/dede:field}
{dede:field name='description'}无所畏惧Chris Rock2004年HBO华盛顿特区专场脱口秀迅雷下载、免费下载，无所畏惧Chris Rock2004年HBO华盛顿特区专场脱口秀Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}无所畏惧Chris Rock2004年HBO华盛顿特区专场脱口秀{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-04-03{/dede:field}
{dede:field name='body'}<p>
	<img alt="" height="1054" src="/uploads/allimg/c120524/133N4UFF-532Q.jpg" width="750" /></p>

<p>
	<img alt="" height="400" src="/uploads/allimg/c120524/133N4UHW0-E5E.jpg" width="528" /></p>

<p>
	<img alt="" height="400" src="/uploads/allimg/c120524/133N4UI50-NS3.jpg" width="528" /></p>
<p>

	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="/uploads/allimg/c120524/133N2Z4FF-102231.jpg" />&nbsp;&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：http://www.xiaozhizhu.net</td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:3134/飘花电影piaohua.com无所畏惧Chris Rock2004年HBO华盛顿特区专场脱口秀.rmvb</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120524/133N4UJ1P-W496.jpg{/dede:field}
