{dede:field name='keywords'}猫和老鼠：胡桃夹子的传奇HD中英{/dede:field}
{dede:field name='description'}猫和老鼠：胡桃夹子的传奇HD中英双字1024高清经典动画迅雷下载、免费下载，猫和老鼠：胡桃夹子的传奇HD中英双字1024高清经典动画Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}猫和老鼠：胡桃夹子的传奇HD中英双字1024高清经典动画{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-09-22{/dede:field}
{dede:field name='body'}<p>
	<img alt="" border="0" src="/uploads/allimg/c120525/133O04BA10-1c61.jpg" /></p>
<p>
	◎译　　名　猫和老鼠:胡桃夹子的传奇<br />
	◎片　　名　Tom And Jerry - A Nutcracker Tale<br />
	◎年　　代　2007<br />
	◎国　　家　美国<br />
	◎类　　别　动画<br />
	◎语　　言　英语<br />
	◎字　　幕　中英双字<br />
	◎文件格式　HDTV-RMVB<br />
	◎视频尺寸　1024 x 576<br />
	◎文件大小　1CD<br />
	◎片　　长　46 Mins<br />
	◎导　　演　Spike Brandt<br />
	　　　　　　Tony Cervone<br />
	◎主　　演　<br />
	　　　　　　</p>
<p>
	◎简　　介　</p>
<p>
	在这部《猫和老鼠》系列最新的原版影片中，圣诞节因汤姆和杰瑞的针锋相对、各展所长而变得格外热闹！</p>
<p>
	当心！它们又出现了，好莱坞最出名的猫鼠。50年来，它们曾赢得七届奥斯卡金像奖，破过无数的记录，当然还破过无数的碟子、座灯及安宁。本碟片画质高度清晰，好戏一个接一个，让你笑到捧腹！</p>
<p>
	在空无一人的剧院，杰瑞许下心愿，希望能有机会在这里演出，它的愿望竟然奇迹般地实现了。这只小老鼠不知不觉地来到一个迷人的国度，在那里，一切皆成为可能：糖果森林、会唱歌的雪花、甚至玩具也有了生命!在那里，杰瑞和新朋友们玩得很愉快，当它和一个音乐盒里的芭蕾舞女郎跳舞的时候，简直幸福极了。不幸的是，由汤姆率领的一群野猫破坏了这场派对，绑架了芭蕾舞女郎，还在这个假日王国中大肆掠夺。该杰瑞出手匡扶正义了!在老鼠塔飞和更多新朋友的协助下，杰瑞大获全胜！</p>

<p>
	<img alt="" border="0" src="/uploads/allimg/c120525/133O04BK50-250K.jpg" /></p>
<p>
	<img alt="" border="0" src="/uploads/allimg/c120525/133O04BPF-39448.jpg" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="/uploads/allimg/c120524/133N2Z4FF-102231.jpg" />&nbsp;&nbsp;&nbsp;</p>
<p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				&nbsp;&nbsp;ftp://dy44:piaohua@dy44.piaohua.com:1627/飘花电影piaohua.com猫和老鼠：胡桃夹子的传奇HD中英双字1024高清.rmvb</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O04BUZ-49104.jpg{/dede:field}
