{dede:field name='keywords'}快乐丧尸BD高清迅雷下载，免费下{/dede:field}
{dede:field name='description'}快乐丧尸BD高清迅雷下载、免费下载，快乐丧尸BD高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}快乐丧尸BD高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-04-26{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://i.imgur.com/GY83X.jpg" style="width: 650px; height: 818px" /></p>
<p>
	◎译　　名　快乐丧尸<br />
	◎片　　名　Deadheads<br />
	◎年　　代　2011<br />
	◎国　　家　美国<br />
	◎类　　别　冒险/喜剧/恐怖<br />
	◎语　　言　英语<br />
	◎IMDB评分 &nbsp;(awaiting 5 votes)<br />
	◎IMDB链接 &nbsp;<a href="http://www.imdb.com/title/tt1273207/" target="_blank">http://www.imdb.com/title/tt1273207/</a><br />
	◎文件格式　X264 + DTS<br />
	◎视频尺寸　1280 x 720<br />
	◎片　　长　95 Mins<br />
	◎导　　演　Brett Pierce,Drew T. Pierce<br />
	◎主　　演　Michael McKiddy ... Mike Kellerman<br />
	Ross Kidder ... Brent Guthrie<br />
	Markus Taylor ... Cheese<br />
	Thomas Galasso ... Thomas Jeremiah<br />
	Natalie Victoria ... Ellie Masterson<br />
	Eden Malyn ... Emily<br />
	Benjamin Webster ... McDinkle<br />
	Greg Dow ... Gillman<br />
	Harry Burkey ... Cliff<br />
	Leonard Kelly-Young ... Charles<br />
	<br />
	　　　　　　<br />
	◎简　　介　<br />
	<br />
	两具僵尸不可思议地先后复活 ,他们决定找回失去的爱。但是他们没有意识到有一家公司正在追踪他们...<br />
	<br />
	Two inexplicably coherent zombies awake amidst a zombie attack and decide to take a road trip to find the one&#39;s lost love, unaware they are being chased by the agents of a ruthless company with it&#39;s own agenda.<br />
	&nbsp;<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120426/02/62564813201204260238521688218047107_005.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120426/02/62564813201204260238521688218047107_004.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120426/02/62564813201204260238521688218047107_003.jpg" style="width: 720px; height: 405px" /></p>
<p>
	【下载地址】</p>
<table bgcolor="#0099cc" border="0" cellpadding="10" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.net" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy125:piaohua@dy125.piaohua.com:7890/飘花电影piaohua.com快乐丧尸BD中英双字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:7890/飘花电影piaohua.com快乐丧尸BD中英双字1280高清.rmvb</a></td>
		</tr>
		<tr>
		</tr>
	</tbody>
</table>
<br />{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15F4360-4G38.jpg{/dede:field}
