{dede:field name='keywords'}战争回忆BD1280高清迅雷下载，免{/dede:field}
{dede:field name='description'}战争回忆BD1280高清迅雷下载、免费下载，战争回忆BD1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}战争回忆BD1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-23{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="/uploads/allimg/c120525/133O0X42420-51Y2.jpg" style="width: 650px; height: 826px" /></p>
<p>
	【中文译名】战争回忆/纪念日<br />
	【影片原名】Memorial Day<br />
	【出品年代】2011 年<br />
	【影片级别】Australia:MA15+ | USA:R<br />
	【IMDB链接】http://www.imdb.com/title/tt1694118/<br />
	【IMDB评分】6.0/10 (75 votes)<br />
	【国　　家】美国<br />
	【影片长度】105 Mins<br />
	【对白语言】英语<br />
	【字幕语言】中英双字<br />
	【类　　别】动作/剧情/家庭/历史/战争<br />
	【导　　演】Sam Fischer<br />
	【主　　演】乔纳森&middot;本内特 Jonathan Bennett &nbsp;....SSGT. Kyle Vogel<br />
	　　　　　　詹姆斯&middot;克伦威尔 James Cromwell &nbsp;....Bud Vogel<br />
	　　　　　　John Cromwell &nbsp;....Lieutenant Bud Vogel<br />
	　　　　　　杰克逊&middot;邦德 Jackson Bond &nbsp;....Young Kyle Vogel<br />
	　　　　　　Mary Kay Fortier-Spalding &nbsp;....Betty Vogel<br />
	　　　　　　Emily Fradenburgh &nbsp;....Lt. Kelly Tripp<br />
	　　　　　　Charles Hubbell &nbsp;....Cpt. Tom Marshall<br />
	　　　　　　Corby Kelly &nbsp;....Derek Lodermeier<br />
	　　　　　　Chris LeFevere &nbsp;....Spc. Josh Berg<br />
	　　　　　　Steven Luke &nbsp;....Brandt (as Luke Schuetzle)<br />
	　　　　　　Jasper Morgan &nbsp;....Young German Soldier<br />
	　　　　　　Reed Sigmund &nbsp;....Gorski<br />
	　　　　　　Thomas Sellwood &nbsp;....PFC Nick Sullivan<br />
	　　　　　　Erin Traxler &nbsp;....Sarah Vogel<br />
	　　　　　　Armin Zadeh &nbsp;....Moises Aguilar<br />
	<br />
	【内容简介】<br />
	<br />
	Memorial Day, 1993. When 13-year-old Kyle Vogel discovers the World War II footlocker belonging to his grandfather, Bud, everyone tells Kyle to put it back. Luckily, he ignores them. Although Bud has never talked about the war, he finds himself striking a deal with his grandson: Kyle can pick any three souvenirs, and Bud will tell him the stories behind each one. Memorial Day not only takes us on a journey into Bud&#39;s complicated wartime past, but also into Kyle&#39;s wartime future. As the two men share parallel experiences in combat, they come to realize how that magical day on the porch shaped both of their lives.<br />
	&nbsp;=======原声预告片欣赏=======</p>
<p>
	<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,40,0" height="490" width="630"><param name="quality" value="high" /><param name="movie" value="/uploads/allimg/c120525/133O0X440Z-620O.swf" /><param name="quality" value="high" /><param name="movie" value="/uploads/allimg/c120525/133O0X440Z-620O.swf" /><embed height="490" pluginspage="http://www.macromedia.com/go/getflashplayer" quality="high" src="/uploads/allimg/c120525/133O0X440Z-620O.swf" type="application/x-shockwave-flash" width="630"></embed></object></p>
<p>
	<img alt="" src="/uploads/allimg/c120525/133O0X46010-K635.jpg" style="width: 720px; height: 405px" /><img alt="" src="/uploads/allimg/c120525/133O0X4F50-X1D.jpg" style="width: 720px; height: 405px" /><img alt="" src="/uploads/allimg/c120525/133O0X4O20-920Y.jpg" style="width: 720px; height: 405px" /><img alt="" src="/uploads/allimg/c120525/133O0X49140-101W3.jpg" style="width: 720px; height: 405px" /><br />
	&nbsp;</p>
<p>
	【下载地址】</p>
<table bgcolor="#0099cc" border="0" cellpadding="10" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：http://www.xiaobajie.com</td>
		</tr>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy125:piaohua@dy125.piaohua.com:8091/飘花电影piaohua.com战争回忆BD中英双字1280高清.rmvb</td>
		</tr>
		<tr>
		</tr>
	</tbody>
</table>
<br />{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O0X500Z-1144H.jpg{/dede:field}
