<?php
$z[0]=Array("field","富江,无限制(无限富江)DVD中字20",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","富江 无限制(无限富江)DVD中字2011最新日本恐怖大片迅雷下载、免费下载，富江 无限制(无限富江)DVD中字2011最新日本恐怖大片Gvod高清在线播放，剧情介绍等。",73,263);
$z[1][4]['name']="description";
$z[2]=Array("field","富江 无限制(无限富江)DVD中字2011最新日本恐怖大片",265,351);
$z[2][4]['name']="title";
$z[3]=Array("field","",353,392);
$z[3][4]['name']="writer";
$z[4]=Array("field","",394,433);
$z[4][4]['name']="source";
$z[5]=Array("field","2012-02-17",435,485);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",487,524);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://dy44:piaohua@dy44.piaohua.com:2838/飘花电影piaohua.com富江 无限制(无限富江)DVD中字.rmvb",526,658);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MPR4H0-1AF.jpg",660,740);
$z[8][4]['name']="litpic";

?>