<?php
$z[0]=Array("field","希林公主/雪馨[DVD中字]迅雷下载",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","希林公主/雪馨[DVD中字]迅雷下载、免费下载，希林公主/雪馨[DVD中字]Gvod高清在线播放，剧情介绍等。",73,211);
$z[1][4]['name']="description";
$z[2]=Array("field","希林公主/雪馨[DVD中字]",213,273);
$z[2][4]['name']="title";
$z[3]=Array("field","",275,314);
$z[3][4]['name']="writer";
$z[4]=Array("field","",316,355);
$z[4][4]['name']="source";
$z[5]=Array("field","2009-12-04",357,407);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",409,446);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://3e:3e@www2.eee4.com:929/[3E电影站www.eee4.cn]希林公主.rmvb\" target=\"_blank",448,567);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MP464960-35624.jpg",569,653);
$z[8][4]['name']="litpic";

?>