{dede:field name='keywords'}黑鹰坠落/黑鹰计划BD中英双字102{/dede:field}
{dede:field name='description'}黑鹰坠落/黑鹰计划BD中英双字1024/1280高清迅雷下载、免费下载，黑鹰坠落/黑鹰计划BD中英双字1024/1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}黑鹰坠落/黑鹰计划BD中英双字1024/1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-12-09{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://4e:4e@www2.eee4.com:339/[3E电影站www.eee4.com]黑鹰坠落DVD中英双字1024x576高清版.rmvb" target="_blank{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MP55b20-3D44.jpg{/dede:field}
