{dede:field name='keywords'}变脸/夺面双雄变脸BD中英双字102{/dede:field}
{dede:field name='description'}变脸/夺面双雄变脸BD中英双字1024/1280高清迅雷下载、免费下载，变脸/夺面双雄变脸BD中英双字1024/1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}变脸/夺面双雄变脸BD中英双字1024/1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-12-08{/dede:field}
{dede:field name='body'}<p>
	◎译　　名　《变脸/夺面双雄》1997年欧美票房过亿经典动作惊悚DVD中英双字1024x576高清版<br />
	◎片　　名　Face/Off<br />
	◎年　　代　1997<br />
	◎国　　家　美国<br />
	◎类　　别　动作/犯罪/剧情/爱情/科幻/惊悚<br />
	◎语　　言　英语<br />
	◎字　　幕　中英字幕<br />
	◎IMDB评分 7.2/10 (69,918 votes)<br />
	◎文件格式　BluRay-RMVB<br />
	◎视频尺寸　1024 x 576<br />
	◎文件大小　1CD<br />
	◎片　　长　138 min<br />
	◎导　　演　吴宇森 John Woo<br />
	◎主　　演　约翰&middot;特拉沃塔 John Travolta .....Sean Archer/Castor Troy<br />
	　　　　　　尼古拉斯&middot;凯奇 Nicolas Cage .....Castor Troy/Sean Archer<br />
	　　　　　　琼&middot;艾伦 Joan Allen .....Dr. Eve Archer<br />
	　　　　　　亚历桑德罗&middot;尼沃拉 Alessandro Nivola .....Pollux Troy<br />
	　　　　　　吉娜&middot;吉舍恩 Gina Gershon .....Sasha Hassler<br />
	　　　　　　多米尼克&middot;斯万 Dominique Swain .....Jamie Archer<br />
	　　　　　　尼克&middot;卡萨维茨 Nick Cassavetes .....Dietrich Hassler<br />
	　　　　　　Harve Presnell .....Victor Lazarro<br />
	　　　　　　Colm Feore .....Dr. Malcolm Walsh<br />
	　　　　　　约翰&middot;卡洛&middot;林奇 John Carroll Lynch .....Walton, Prison Guard<br />
	　　　　　　希&middot;庞德 CCH Pounder .....Dr. Holllis Miller<br />
	　　　　　　Robert Wisdom .....Tito Biondi<br />
	　　　　　　Margaret Cho .....Wanda<br />
	　　　　　　詹姆斯&middot;丹顿 Jamie Denton .....Buzz (as Jamie Denton)<br />
	　　　　　　Matt Ross .....Loomis<br />
	　　　　　　Chris Bauer .....Ivan Dubov<br />
	　　　　　　Myles Jeffrey .....Michael Archer<br />
	　　　　　　David McCurley .....Adam Hassler<br />
	　　　　　　托马斯&middot;简 Thomas Jane .....Burke Hicks<br />
	　　　　　　汤米&middot;弗拉纳根 Tommy Flanagan .....Leo (as Tommy J. Flanagan)<br />
	　　　　　　<br />
	<br />
	◎简　　介　<br />
	<br />
	　无恶不作的恐怖份子凯斯特洛伊刺杀FBI的高级探员尚&middot;亚瑟，却误杀其瑟独生子，让尚&middot;亚瑟发誓要亲手抓凯斯特洛伊入狱。在线人的密告之下，尚&middot;亚瑟终于有机会亲自逮捕他到案，趁着凯斯&middot;特洛伊与他弟弟搭机逃亡之前将他们绳之以法，枪战之后，凯斯&middot;特洛伊因负伤过重而昏迷不醒。<br />
	<br />
	　　亚瑟原本以为一切都结束了，没想到却从凯斯弟弟的口中得知，凯斯&middot;特洛伊在被捕之前已经将威力强大的毒气炸弹放在某个人潮众多的公共场合，无论警方如何逼问，凯斯的弟弟宁死都不愿说出炸弹地点。束手无策之际，亚瑟的长官提出透过高科技的整容手术，让亚瑟与凯斯&middot;特洛伊的容貌对换，再让假扮成凯斯&middot;特洛伊的亚瑟进入监狱中，让凯斯的弟弟以为哥哥复活，并说出炸弹地点。<br />
	<br />
	　　这项&ldquo;变脸&rdquo;计划为FBI的高度机密，只有主事的医师与三位FBI长官知情，刚开始一切都顺利进行，假扮的凯斯特洛伊混入监狱之中。但令人没想到的，原本昏迷中的凯斯特洛伊却清醒过来，狡猾的他决定将计就计，第一步先杀掉从事此项任务的医师与知情的FBI探员&hellip;&hellip;</p>
<p>
	<img src="http://img.album.pchome.net/54/68/75/05/c44bf764dc17e1c7445668783c3d18e4.jpg" /></p>
<p>
	<br />
	<br />
	幕后制作：<br />
	　　《变脸》是约翰&middot;特拉沃塔与尼古拉斯&middot;凯奇第一次同台飚戏，本片与以往的好莱坞同类影片不同，这两位当今世界影坛有口皆碑的伟大演员不仅要演绎善恶，还要交换身份，互相映衬彼此的演技。在吴宇森的早期作品中，很常见极度仇恨背景下的善恶之争，《变脸》则让这种主题更进一步。执行制片史蒂文&middot;鲁瑟(Steven Reuther)说：&ldquo;影片的叙事手法大胆而独特，而且角色完全具有着对称性。&rdquo;已经与吴宇森合作过18年的张家振补充说：&ldquo;《变脸》非常适合吴宇森来执导，因为这不止是一部动作片，还蕴涵着感人至深的情感故事，吴宇森从不会为了动作而动作。&rdquo;<br />
	<br />
	　　尼古拉斯&middot;凯奇说：&ldquo;剧本中的交换身份让约翰和我有机会揣摩对方的特质和风格，真是难得的集体表演经历。&rdquo;在片中扮演阿彻妻子的琼&middot;艾伦说：&ldquo;目睹约翰和尼克在肖恩&middot;阿彻和卡斯特&middot;特洛伊之间转换角色是令人难以置信的事，他们互相模仿彼此的肢体动作、手势和说话频率及风格的能力是惊人的。&rdquo;<br />
	<br />
	　　编剧麦克&middot;沃伯(Mike Werb)和迈克尔&middot;科拉里(Michael Colleary)早在1990年就完成了剧本初稿，两人将影片形容为看似动作片的心理惊悚片。当时两位编剧都没看过吴宇森的电影，他们从拉乌尔&middot;沃尔什的《歼匪喋血战》和约翰&middot;弗兰肯海默(John Frankenheimer)的《脱胎换骨》中获取了创作灵感。科拉里回忆说：&ldquo;当第一次看到吴宇森的《喋血双雄》时，我彻底惊呆了，那是我看过的最电影的电影，当时我们根本不知道吴宇森，也不熟悉他的作品，我意识到我们的剧本应该由他来执导。&rdquo;对于约翰&middot;特拉沃塔和尼古拉斯&middot;凯奇能够携手担纲，两位编剧坦言连做梦都没想过，而且两位演员的演绎完全超出了他们的想象。<br />
	<br />
	　　由于影片中充满了大量惊险场面，为了达到导演吴宇森要求的效果，在影片开拍的数月前，制片方就集合了幕后团队，执行制片史蒂文&middot;鲁瑟说：&ldquo;吴宇森的拍摄手法非常程式化，所以环境、空间、设计和效果的细节之处都务必到位，这样才能让吴宇森的风格得以完满体现。&rdquo;<br />
	<br />
	　　影片绝大部分是实景拍摄，只有个别场景在派拉蒙的摄影棚拍摄。制作设计师尼尔&middot;斯匹萨克(Neil Spisak)组建了由绘图师、布景师、模型制作师和建筑工人组成的制作团队来搭建布景。斯匹萨克说：&ldquo;影片的两位主人公互换身份，其他人根本不知情，影片的外观必须增强这种设置的可信度。阿彻的住所和办公室的设计需要反映出他生活的稳定，所以当卡斯特闯入阿彻生活中最隐私的角落时，才会让观众感知到可怕的侵害。&rdquo;完全相反的是黑帮和监狱中的场景，阿彻发现自己被囚禁的环境必须令人窒息和危险，这样才能表现出他的疏远孤立之感。<br />
	<br />
	　　片中迪特里希顶楼发生的枪战戏是在洛杉矶市区的一栋闲置建筑的第九和第十层拍摄的，五获奥斯卡提名的布景师加勒特&middot;刘易斯(Garrett Lewis)负责设计出房中华丽的背景，执行制片史蒂文&middot;鲁瑟说：&ldquo;顶楼的布景太棒了，足以表现出卡斯特黑帮世界的魔力和诱惑以及人物的阴暗面，巨大的空间让吴宇森的枪战戏得以充分发挥。&rdquo;为了打造激烈枪战的破坏效应，特效部门在房间的墙壁和家具上制造了5000多个子弹效果。制片人巴里&middot;奥斯本(Barrie Osborne)说：&ldquo;目睹吴宇森设计出一段场景很有趣，制作情节串联图板，确定在拍摄时镜头切换的位置，运用多部摄影机捕捉枪战画面，他是真正的动作片大师。&rdquo;<br />
	<br />
	　　从影20年的资深特技人布赖恩&middot;斯莫兹(Brian Smrz)组建了由50名特技演员组成的庞大特技团队，大量的枪战爆炸场景和时速60英里的快艇追逐令斯莫兹应接不暇，他说：&ldquo;吴宇森知道他想要什么，他了解动作，懂得如何去拍，很明确演员的位置，我的工作由此得心应手。&rdquo;<br />
	<br />
	　　尼古拉斯&middot;凯奇在影片拍摄中经历了惊险一幕，他必须站在距太平洋卡宾特利亚海滩3英里远的石油钻井平台的最高处，恐高的凯奇回忆说：&ldquo;当时我站在200英尺高的钻塔上，根本没有能抓得住的东西，那是我生命中最可怕的经历。&rdquo;在斯莫兹的周密安全保障下，凯奇显然有惊无险。<br />
	<br />
	　　武器专家罗克&middot;加洛蒂(Rock Galotti)同演员和特技人员密切合作，训练他们掌握各种武器的使用方法。加洛蒂参与了吴宇森在美国所有影片的拍摄，深知他的喜好：&ldquo;吴宇森的电影中需要大量武器，而且他喜欢火焰和枪声大的，贝瑞塔(Beretta)枪械一直出现在他的电影中。&rdquo;加洛蒂曾在军方和执法部门工作，对所有枪械了如指掌。他准确的为每个人物选择了武器，片中FBI特工和SWAT特警都装备了SIG手枪、MP-5冲锋枪及MP-5A29mm全自动微型冲锋枪，加洛蒂说：&ldquo;片中FBI使用的武器确实是精英部队和执法部门真正的制式装备，在黑帮方面，我们使用了在黑市上具有代表性的武器。&rdquo;<br />
	<br />
	　　曾为乔治空军基地的南加州国际机场为影片剧组提供了足够空间拍摄喷气机的追逐场景，封闭了10000英尺长的跑道。制片人巴里&middot;奥斯本说：&ldquo;吴宇森和我都不愿使用微缩模型和特效来拍摄，在这段场景中，我们使用了全尺寸的真实飞机，这架飞机由我们组装而成，为了避免使用绿屏，我们在拖车托拽的另一架飞机中拍摄了内景，所以，我们拍摄的画面相当真实。&rdquo;<br />
	<br />
	　　阿彻和卡斯特的快艇追逐场景是在圣佩德罗的洛杉矶港拍摄的，由于当地是全世界最繁忙的港口，所以要完成大量特效和特技的拍摄工作非常复杂，好在两位外景制片主任创造了用于剧组同港口管理机构、海岸警卫队、港口警方、消防部门和拖船公司取得联系的通讯系统。外景制片主任贾尼斯&middot;波利(Janice Polley)说：&ldquo;在影片拍摄区域及周围，有大量航运在进行，那些拖船和驳船从不会停歇片刻，体形巨大的邮轮速度很快，需要一英里才能停下来，所以为了保证我们船队的安全，就必须考虑周全，与多部门协作拍摄。&rdquo;</p>
<p>
	<a href="http://img.album.pchome.net/54/68/75/05/84998bc24b9b83b64d396f4e8f6a1577.jpg" target="_blank"><img border="0" src="http://img.album.pchome.net/54/68/75/05/84998bc24b9b83b64d396f4e8f6a1577.jpg" /></a>&nbsp;<br />
	<a href="http://img.album.pchome.net/54/68/75/05/af2bd92a30ca34c788dd7033ac105939.jpg" target="_blank"><img border="0" src="http://img.album.pchome.net/54/68/75/05/af2bd92a30ca34c788dd7033ac105939.jpg" /></a>&nbsp;<br />
	<a href="http://img.album.pchome.net/54/68/75/05/94f7a1a3316019af6be56751b3e4ea71.jpg" target="_blank"><img border="0" src="http://img.album.pchome.net/54/68/75/05/94f7a1a3316019af6be56751b3e4ea71.jpg" /></a></p>
	1997年欧美票房过亿经典动作惊悚《变脸》DVD中英双字1024x576高清版<img border="0" src="http://www.eee4.com/templets/img/down.jpg" /></p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://e49:e49@xl2.eee4.com:9024/[3E电影站www.eee4.com]变脸[DVD中英双字1024x576高清版].rmvb" target="_blank">ftp://e49:e49@xl2.eee4.com:9024/[3E电影站www.eee4.com]变脸[DVD中英双字1024x576高清版].rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2287/飘花电影piaohua.comcom变脸BD中英双字1280高清.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2287/飘花电影piaohua.comcom变脸BD中英双字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O16044410-2E48.jpg{/dede:field}
