{dede:field name='keywords'}圣斗士星矢剧场版1,:,邪神爱丽丝{/dede:field}
{dede:field name='description'}圣斗士星矢剧场版1 : 邪神爱丽丝HD国语中字1280高清迅雷下载、免费下载，圣斗士星矢剧场版1 : 邪神爱丽丝HD国语中字1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}圣斗士星矢剧场版1 : 邪神爱丽丝HD国语中字1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-01-08{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20110818/17/62649824201108181716322731127941306_001.jpg" /></p>
<p>
	◎译　　名　圣斗士星矢剧场版1 : 邪神爱丽丝/圣斗士星矢剧场版1：伊里逆司的再生 | 邪神爱丽丝 | 圣斗士星矢<br />
	◎原　　名&nbsp;&nbsp; 聖闘士星矢　邪神エリス<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Saint Seiya Gekij?ban<br />
	◎片　　名　Saint Seiya, Jashin Eris<br />
	◎年　　代　1987<br />
	◎国　　家　日本<br />
	◎类　　别　动画/冒险/奇幻<br />
	◎语　　言　国日双语<br />
	◎字　　幕　中文(简繁体)<br />
	◎IMDB评分&nbsp; 5.8/10 (309 votes)<br />
	◎片　　长　45m:46s<br />
	◎导　　演　森下孝三<br />
	◎主　　演　古谷彻 T?ru Furuya&nbsp; ....Seiya (voice)<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 铃置洋孝 Hirotaka Suzuoki&nbsp; ....Shiryu (Dragon) (voice)<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 桥本晃一 K?ichi Hashimoto&nbsp; ....Hyoga (Cygnus) (voice)<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 堀川亮 Ry? Horikawa&nbsp; ....Shun (Andromeda) (voice)<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 堀秀行 Hideyuki Hori&nbsp; ....Ikki (Phoenix) (voice)<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 潘惠子 Keiko Han&nbsp; ....Sayori Kido (Athena) (voice)<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 藤田淑子 Toshiko Fujita&nbsp; ....Eris (voice)<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 三矢雄二 Y?ji Mitsuya&nbsp; ....Orpheus (voice)<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 水岛裕 Y? Mizushima&nbsp; ....Jaguar (voice)<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 中尾隆圣 Ry?sei Nakao&nbsp; ....Christ (voice)<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 难波圭一 Keiichi Nanba&nbsp; ....Jan (voice)<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 柴田由美子 Yumiko Shibata&nbsp; ....Mimiko (voice)<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 田中秀幸 Hideyuki Tanaka&nbsp; ....Narration (voice)<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 冬马由美 Yumi T?ma&nbsp; ....Akira (voice)<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 上村典子 Noriko Uemura&nbsp; ....Makoto (voice)<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 柳泽三千代 Michiyo Yanagisawa<br />
	　　　　　　<br />
	◎简　　介</p>
<p>
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 一颗流星划过东京夜空，随它一同到来的还有希腊神话传说中的黄金苹果。善良的孤儿院女老师绘梨衣与孩子们过着平静的生活，但是她受到黄金苹果的召唤，化身为纠纷女神艾莉丝。为了实现毁灭世界的目的，她绑架了女神雅典娜，并用金苹果将其捆住。随同纠纷女神一同复活的还有矢座魔矢、竖琴座奥菲斯、南十字星古拉特、神盾座阿恩、奥利安座渣加等五位亡灵圣斗士。正享受和平生活的星矢、紫龙、瞬和冰河收到艾莉丝送来的挑战书，他们重新穿上圣衣前往女神被困所在。到达圣域的星矢众人遭遇亡灵五人组，随即陷入艰苦鏖战。女神危在旦夕&hellip;&hellip;</p>
<p>
	&nbsp;&nbsp;&nbsp;&nbsp; 本片为动画片《圣斗士星矢》第一部剧场版</p>

<p>
	下载地址：<img border="0" src="/templets/img/down.jpg" /><br />
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<anchor></anchor><a href="ftp://dy44:piaohua@dy44.piaohua.com:2547/飘花电影piaohua.com圣斗士星矢剧场版1邪神爱丽丝HD国语中字1280高清.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2547/飘花电影piaohua.com圣斗士星矢剧场版1邪神爱丽丝HD国语中字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1Ac5Z-23528.jpg{/dede:field}
