{dede:field name='keywords'}小红帽/血红帽/BD1280高清迅雷下{/dede:field}
{dede:field name='description'}小红帽/血红帽/BD1280高清迅雷下载、免费下载，小红帽/血红帽/BD1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}小红帽/血红帽/BD1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-21{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://www.newmov.com/pic/divx/2011/Red.Riding.Hood.DVDRip.XviD-DEFACED.jpg" style="width: 650px; height: 963px" /></p>
<p>
	【影片原名】Red Riding Hood<br />
	【中文译名】小红帽/血红帽(港)/血红帽(台)<br />
	【出品公司】Warner Bros. Pictures<br />
	【出品年代】2011 年<br />
	【上映日期】2011年3月11日 美国<br />
	【影片级别】USA:PG-13 (certificate #46624) | Malaysia:PG-13 | Canada:PG (Alberta/British Columbia/Manitoba/Ontario) | Singapore:PG | Canada:13+ (Quebec)<br />
	【官方网站】<a class="faqlink" endcolor="FF6600" href="http://redridinghood.warnerbros.com/" index="0" startcolor="0066ff" state="OFF" style="color: #0066ff">http://redridinghood.warnerbros.com/</a><br />
	【IMDB链接】<a class="faqlink" endcolor="FF6600" href="http://www.imdb.com/title/tt1486185/" index="0" startcolor="0066ff" state="OFF" style="color: #0066ff">http://www.imdb.com/title/tt1486185/</a><br />
	【IMDB评分】4.9/10 (7,280 votes)<br />
	【国　　家】美国/加拿大<br />
	【类　　别】奇幻/恐怖/悬疑/惊悚<br />
	【导　　演】凯瑟琳&middot;哈德威克 Catherine Hardwicke<br />
	【主　　演】阿曼达&middot;塞弗里德 Amanda Seyfried &nbsp;....Valerie<br />
	　　　　　　希罗&middot;弗南德兹 Shiloh Fernandez &nbsp;....Peter<br />
	　　　　　　麦克斯&middot;艾恩斯 Max Irons &nbsp;....Henry<br />
	　　　　　　加里&middot;奥德曼 Gary Oldman &nbsp;....Solomon<br />
	　　　　　　比利&middot;伯克 Billy Burke &nbsp;....Cesaire<br />
	　　　　　　维吉妮娅&middot;马德森 Virginia Madsen &nbsp;....Suzette<br />
	　　　　　　卢卡斯&middot;哈斯 Lukas Haas &nbsp;....Father Auguste<br />
	　　　　　　朱莉&middot;克里斯蒂 Julie Christie &nbsp;....Grandmother<br />
	　　　　　　Shauna Kain &nbsp;....Roxanne<br />
	　　　　　　Michael Hogan &nbsp;....The Reeve<br />
	　　　　　　Adrian Holmes &nbsp;....Captain<br />
	　　　　　　Cole Heppell &nbsp;....Claude<br />
	　　　　　　Christine Willes &nbsp;....Madame Lazar<br />
	　　　　　　迈克尔&middot;山克斯 Michael Shanks &nbsp;....Adrien Lazar<br />
	　　　　　　Kacey Rohl &nbsp;....Prudence<br />
	<br />
	【官方网站】：<a href="http://www.bluemv.com" title="电影下载">http://www.bluemv.com</a><br />
	【内容简介】<br />
	<br />
	　　几十年以来,剑角村(Daggerhorn)的村民一直和当地的一个狼人维持着岌岌可危的平安状态。每到月圆之时,狼人就会出没觅食。这个时候,村民为了换取自己的安全,就会给狼人祭献上一头牲畜。不过,在一个月圆之日,狼人打破了惯例,吃掉了一个村民。<br />
	<br />
	　　这个村民是瓦莱利的姐姐。瓦莱利是一个年轻、漂亮的女孩。她刚刚发现自己的父母已经为她私定了终生,要将她嫁给亨利。亨利是镇子上著名的富二代,他家是全镇最有钱有势的家庭。不过,瓦莱利却早已心有所属,她爱着彼得。彼得是一个穷光蛋,工作就是砍树。瓦莱利和彼得情感笃定,正决计这要逃跑私奔。不过, 吃了人的狼人打破了小镇的宁静和所有人的计划。事情全都乱了套。<br />
	<br />
	　　村民们渴望报复,于是便找来了著名的狼人猎手所罗门神父,希求他能为剑角村解决这个隐患。不过,所罗门的到来却引发了小镇更大的骚动。他告诉村民,狼人只有在月圆之时才会变身,平时完全是正常人的模样,而且很有可能就是一个普通的村民,全村人都脱离不了是&ldquo;披着人皮的狼&rdquo;的嫌疑。<br />
	<br />
	　　随着月圆之夜的再次逼近,小镇人民都生活在恐慌和不安之中。狼人的存在使得这个原本幸福安宁的小镇变得七零八落。但是瓦莱利却意外地发现自己同狼人竟然有着某种说不清道不明的心灵感应。这种心灵感应让她一方面对狼人的生活和本尊产生了好奇和疑虑,另一方面也让她成为了诱使狼人步入村民全套的诱饵。<br />
	<br />
	一句话评论<br />
	<br />
	　　一部有趣的童话故事在银幕上流血。 &mdash;&mdash;《纽约时报》<br />
	<br />
	　　优美的童话被恐怖的念头给破坏,恶劣的拍摄导致本片乏善可陈。 &mdash;&mdash;《洛杉矶时报》<br />
	<br />
	　　可怜的阿曼达&middot;塞弗里德,这位当今最活跃的、表现力最强的年轻女演员之一,她发现自己被两片毫无生气的木头给卡住了。 &mdash;&mdash;ReelViews<br />
	<br />
	幕后制作<br />
	<br />
	　　给经典童话正名<br />
	<br />
	　　提到《小红帽》,我们可能都会想起&ldquo;小红帽和狼外婆&rdquo;的经典童话故事。不过,这个童话的原始版本却并没有这么幼稚和讨人喜爱。原版的《小红帽》讲述了一个关于血腥、危险、欺骗和爱情的故事。它远没有改编之后的&ldquo;小红帽和狼外婆&rdquo;知名。<br />
	<br />
	　　不过,在导演凯瑟琳&middot;哈德威克看来,原版的《小红帽》因为自身的恐怖、血腥等特质,最适合改编成一部惊悚恐怖片。她说:&ldquo;我们大多数人都听过净化版的《小红帽》,不过原著的故事更加吸引人,也更具有黑暗元素。一个小姑娘走进了黑森林,一只狼跟踪她并和她说话。这种富有魅力的情节能激发人多个层面的想象力。小时候和成年之后,我们对这个故事的看法会截然不同。&rdquo;制片人詹妮弗&middot;戴维森说:&ldquo;这是一个经典的童话故事,虽然我们在不同的时候会听到不同的版本, 但是诸如大灰狼、小红帽、红色斗篷、谎言、恐惧等等是其中亘古不变的元素。令人向往,也令人海派。我很兴奋能有这种作品,能将这个故事改编成现代观众接受的故事。&rdquo;<br />
	<br />
	　　在这种要给故事&ldquo;正名&rdquo;的思维引导下,编剧又会把故事做出什么样的改写呢?编剧大卫&middot;约翰森说:&ldquo;我做过很多的研究,发现这个故事在不同时间、不同地点都有不同的版本。很早之前,故事的情节很简单,虽然有一些恐怖的情节,但是结尾没有什么新意。我的做法就是拓展故事最初的基础,加入更多的悬疑、冒险以及恐怖和危险的元素。&rdquo;对于大卫&middot;约翰森的改编,詹妮弗&middot;戴维森显然很是满意,她说:&ldquo;我觉得大卫的剧本非常出色,他深入到这个童话故事的内在,探寻了它流传这么久的原因,最后加入了自己的想象力,使得故事丰富了起来。&rdquo;<br />
	<br />
	　　狼人是谁<br />
	<br />
	　　很久之前,父母为了教育小孩子在这个纷乱的世界里学会保护自己,就会和他们说《小红帽》的故事。末了还要加上一句&ldquo;不要和陌生人说话&rdquo;以示警醒和点题。不过,如果狼人(陌生人)是一个你认识的人,甚至是你爱着的人呢?这部电影对于原著童话最大的改动就是,狼人在平时以村民的样子现身,直到满月才会变成狼人。所以,村庄中的任何一个人都有可能是狼人。<br />
	<br />
	　　凯瑟琳&middot;哈德威克说:&ldquo;我们有意识地设计了这个情节,也就是说所有人都有可能是狼人。大卫创造出了一个悬疑弥漫的剧本,每个人都可能是嫌疑犯。从这个角度上来说,这个童话故事被改写成了一个当代的警匪片。一个杀手,白天是正常人,但是到了某些日子就到处杀人。整个城市人心惶惶,最后一个女人发现杀手竟然是自己的爱人。&rdquo;不过,对于狼人是谁,詹妮弗&middot;戴维森有着自己的看法。她说:&ldquo;这个故事正是利用了人们的恐惧心理,确切地说就是人们对不可知的事情的恐惧。你最亲近的人的真面目是什么,你不知道;你更不知道那些恐怖的事情的始作俑者就是你的爱人。对我来说,狼人代表的就是人们在处理未知时候的焦躁和不安的情绪。实际上,这是从人的心理发出的一种求救信号和自我保护措施。恐惧和害怕都是正常的,就看你如何去处理这种情绪了。&rdquo;当然,这个成年人版本的《小红帽》里一定不能缺少爱情元素,倘若没有了爱情,那么剩下来的一切就是徒有恐惧、缺少吸引力。大卫&middot;约翰森说:&ldquo;剧本里有不少浪漫的元素,瓦莱利被两个英俊的小伙子追求。一个是青梅竹马的彼得,另一个是父母指定的亨利。不过,狼人和她之间的心灵感应才是让故事更加复杂的原因。&rdquo;<br />
	<br />
	　　大腕班底<br />
	<br />
	　　对于制片方而言,选择凯瑟琳&middot;哈德威克来执导影片是不二之选,因为她有能力打动年轻观众,这在她执导的《芳龄十三》和《暮光之城》中就已经显现出来了。詹妮弗&middot;戴维森说:&ldquo;哈德威克可以使得电影赢得更多的年轻观众的心。这样的导演并不多见,但是哈德威克的确是其中的佼佼者。她的电影从不哗众取宠、也不故作高深,当然也不刻板老套。她用真诚的态度去面对年轻的观众,表达出了年轻人的对世界的思考和想法。&rdquo;这个融合了青春爱情、古老童话以及血腥悬疑的故事从一开始就吸引住了哈德威克,她回忆说:&ldquo;我读剧本时就感到了莫名的兴奋,这是一个有爱情、有惊悚还有大转折的惊悚恐怖片。对于我来说就惊奇不断,随着剧情的深入,故事越来越复杂,越来越多的秘密和谎言得以揭露。&rdquo;<br />
	<br />
	　　凯瑟琳&middot;哈德威克的到来为影片加入了活力。在她的号召之下,老中青三代演员纷纷加盟剧组。加里&middot;奥德曼、阿曼达&middot;塞弗里德和朱莉&middot;克里斯蒂是其中最为大腕的三名演员。谈及和哈德威克的合作,朱莉&middot;克里斯蒂说:&ldquo;我认为凯瑟琳是整部电影的灵魂,她有惊人的活力,在拍摄电影的过程中,她会全身心地投入影片的制作和她合作充满了乐趣。&rdquo;加里&middot;奥德曼说:&ldquo;我曾经看过凯瑟琳的电影,我觉得和她一起拍电影会很有乐趣,这是吸引我来到《小红帽》剧组的原因。后来我和她见了面,通过合作,我很欣赏她对电影的热情和投入。&rdquo;在影片中扮演小红帽的阿曼达&middot;塞弗里德说:&ldquo;凯瑟琳给了我很多帮助,她热爱拍摄电影,也很有想象力。在前期制作阶段的时候,她给我看了很多她自己收集来的图画、视频和照片。那些东西对我塑造人物的帮助很大,使我渐渐了解到故事和人物的不同层次和侧面。她是我合作过的最有想象力的导演。&rdquo;<br />
	<br />
	　　在这些演员里,唯一一位和凯瑟琳&middot;哈德威克有过合作的是在《暮光之城》里扮演贝拉父亲的比利&middot;伯克。伯克说:&ldquo;凯瑟琳在我心中的地位很高。我从来没有见过这么一位具有无穷活力而且还能把这种欣喜和活力传递给别人的人。她就是有办法把一种目标和目的的感觉传递给片场的所有人。&rdquo;<br />
	<br />
	花絮<br />
	<br />
	　　&middot;《暮色》系列中的狼人扮演者泰勒&middot;洛特纳曾经是彼得的候选者。<br />
	<br />
	　　&middot;影片的发行方之一是亚壁古道公司(Appian Way),这是影星莱昂纳多&middot;迪卡普里奥创办的公司,所以迪卡普里奥也是影片的制片人之一。<br />
	<br />
	　　&middot;影片的外景地选择在了温哥华。<br />
	<br />
	　　&middot;影片的原名叫做《戴红帽的小女孩》(The Girl with the Red Riding Hood),后来改成了《小红帽》(Red Riding Hood)。</p>
<p>
	<img alt="" src="http://img165.poco.cn/mypoco/myphoto/20120216/03/62564813201202160310051384463859580_003.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img165.poco.cn/mypoco/myphoto/20120216/03/62564813201202160310051384463859580_002.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img165.poco.cn/mypoco/myphoto/20120216/03/62564813201202160310051384463859580_001.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img165.poco.cn/mypoco/myphoto/20120216/03/62564813201202160310051384463859580_000.jpg" style="width: 720px; height: 405px" /><br />
	&nbsp;</p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="
ftp://dy125:piaohua@dy125.piaohua.com:7612/飘花电影piaohua.com小红帽BD中字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:7612/飘花电影piaohua.com小红帽BD中字1280高清.rmvbb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15130D0-52W6.jpg{/dede:field}
