{dede:field name='keywords'}海洋BD中英双字1024/1280高清201{/dede:field}
{dede:field name='description'}海洋BD中英双字1024/1280高清2010纪录片迅雷下载、免费下载，海洋BD中英双字1024/1280高清2010纪录片Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}海洋BD中英双字1024/1280高清2010纪录片{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-08-28{/dede:field}
{dede:field name='body'}<p>
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://bbs.siluhd.com/attachments/day_100718/1007180217026c6cfcfb824602.jpg');" src="http://bbs.siluhd.com/attachments/day_100718/1007180217026c6cfcfb824602.jpg" /></p>

<p>
	<img alt="" src="/uploads/allimg/c120524/133N42K6040-343507.jpg" /><br />
	<br />
	◎译　　名　海洋<br />
	◎片　　名　OCEANS<br />
	◎年　　代　2010<br />
	◎国　　家　法国/瑞士/西班牙<br />
	◎类　　别　记录/剧情<br />
	◎语　　言　法语<br />
	◎字　　幕　中字<br />
	◎IMDB评分 7.6/10 (1,201 votes)<br />
	◎文件格式　BD-RMVB<br />
	◎视频尺寸　1024 x 576<br />
	◎文件大小　1CD<br />
	◎片　　长　104 Mins<br />
	◎导　　演　雅克&middot;贝汉 Jacques Perrin<br />
	　　　　　　雅克&middot;克鲁奥德 Jacques Cluzaud&nbsp; ....(co-director)<br />
	◎主　　演　雅克&middot;贝汉 Jacques Perrin&nbsp; ....Narrator (French version)<br />
	　　　　　　Lancelot Perrin&nbsp; ....Himself<br />
	　　　　　　宫泽理惠 Miyazawa Rie&nbsp; ....Narrator (Japanese)<br />
	　　　　　　皮尔斯&middot;布鲁斯南 Pierce Brosnan&nbsp; ....Narrator (English version)<br />
	　　　　　　阿尔多 Aldo&nbsp; ....Narrator (Italian version)<br />
	<br />
	◎简　　介　<br />
	<br />
	　　《海洋》聚焦于覆盖着地球表面的四分之三的&ldquo;蓝色领土&rdquo;。法国导演雅克?贝汉与雅克?克鲁佐德将深入探索这个幽深而富饶的神秘世界、完整地呈现海洋的壮美辽阔。<br />
	<br />
	《海洋》是一部以环保为主题的纪录片，由法国导演雅克&middot;贝汉执导，全片讲述了地球上有四分之三的陆地被海洋覆盖，雅克导演将深入探索这个幽深而富饶的神秘世界，完整地呈现海洋的壮美辽阔。该片制作费高达70亿日元(约合人民币5亿)，创下了迄今为止制作费用最高的纪录片。该片将于2010年1月22日在日本上映。<br />
	<br />
	人们常把地球描述成一个大水球，因为地球上陆地只占30%，而70%的面积都被海水覆盖。平静的海水下面是一个对人类来说非常陌生的世界，在这个世界中，各种奇特的生物都生活在一起。法国导演雅克-贝汉与雅克-克鲁佐德就深入探索了这个神秘的世界，带给您不一样的《海洋》。<br />
	<br />
	在影片中我们可以看到，一旦海洋世界受到保护时，就会生机盎然，充满各种各样的生命物种。所以人类在开发海洋资源的时候，最为重要的就是，如何才能做到合理分配、合理利用。<br />
	<br />
	<br />
	一句话评论<br />
	<br />
	这是一部令人心旷神怡、叹为观止的生态学纪录片。那种诗意的、形式感极强的、美到炫目的画面让人多多少少漠视了这部纪录片的故事和它所宣传的环保理念。<br />
	&mdash;&mdash;《好莱坞报道》<br />
	<br />
	了不起的海底纪录片很多，但本片为何如此出色？原因在于&mdash;&mdash;技术。<br />
	&mdash;&mdash;《娱乐周刊》<br />
	<br />
	一部感性的、振奋人的纪录片。<br />
	&mdash;&mdash;《纽约邮报》<br />
	<br />
	幕后制作<br />
	<br />
	【纪录片和&ldquo;故事性&rdquo;】<br />
	<br />
	　　总体而言，海洋这部生态学纪录片还是延续了雅克&middot;贝汉在《迁徙的鸟》一片中开创出来的诗意、唯美、形式感强烈的美学倾向。影片虽也不像《海豚湾》那样有着极强的指示性和政治性。但是和《迁徙的鸟》的纯粹的视觉上美感不同，雅克&middot;贝汉在电影下载《海洋》除了展示了动物之美和自然之美，更多地展开了一种&ldquo;故事性&rdquo;的叙述，他对环保问题的深入思索让我们多了一分对经济发展和环保问题的惦念。<br />
	<br />
	　　谈及影片的主题，雅克&middot;贝汉动情地说：&ldquo;毫无疑问，这部电影里的主角是那些海洋生物，鲨鱼和鲸类是影片的主角，而海洋则是整部影片的背景&mdash;&mdash;它们是这部电影的明星。除了动物之外，还有些渔民也出现在了电影里，他们是真正的渔民，是靠海吃海的人。和现代化的机械捕鱼不同，他们是手工作坊式的劳动者&mdash;&mdash;现代化的捕鱼根本不是渔业，而是对自然资源的掠夺。你能想象得出一艘140米长的大船拖着渔网掠过海地么？这么大的渔网的覆盖面积足足有4个足球场那么大。而且工业化捕鱼的渔网正在越变越大、放的位置也是越来越深。这种捕鱼方式对海地的资源是一种极大的损害。淘宝网除了展示海洋生物，渔民，我们还在影片里探讨了经济问题。不同的国家，由于自身经济发展的不一致，所以他们对海洋的依赖程度也就不一样。对于很多第三世界国家来说，首先要喂饱自己，其次才能谈得上考虑环境问题。如果保护环境的代价是唐自己的人民饿肚子，这种环保还有意义么？可是，这些渔民即使再浪费捕上来的鱼，也赶不上大型捕鱼船只的掠夺。这就是这部纪录片中所谓的&lsquo;故事性&rsquo;。我自己是一点也不喜欢带有故事性的纪录片，但是我希望这部纪录片能让人们正视经济和资源的协调问题。我想现在明白要保护海洋，还不算太晚。我们在电影里完整地展示了食物链，告诉人们整个海洋生态系统是如何运作的，也预测了如果食物链断裂，将会产生什么严重的后果。影片中出现的所有人和动物都和海洋息息相关，海洋中发生的事情和人类社会同样也是息息相关的。&rdquo;<br />
	<br />
	【团队和拍摄】<br />
	<br />
	　　早在精美绝伦的《迁徙的鸟》中，我们就得知了雅克&middot;贝汉为了拍摄那部电影，组建一支精英团队。可是那支在天空翱翔的团队没有办法直接拉到水下拍摄，所以雅克&middot;贝汉又重新组建了一支堪称业内精英的团队。这支水下摄影和探险团队中的大部分成员都是著名的雅克-伊夫&middot;库斯托（Jacques-Yves Coustea）团队中的成员，雅克-伊夫&middot;库斯托是法国著名著名的海洋探险家和摄影师，他和路易&middot;马勒合作的《寂静的世界》就曾拿下过第一座金棕榈大奖。说到这个团队，雅克&middot;贝汉显得自信满满，他说：&ldquo;库斯托的团队里的那些人绝对是精英，他们非常清楚在水下50米的地方该如何拍摄电影。这里面有些人，更是业内大名鼎鼎的专家，有了他们的参与，影片才能拍出来。更为幸运的是我们还得到了伯特兰&middot;皮卡特的帮助，他是去过10000米深海的探险家。当然，还有他的父亲，尊敬的雅克&middot;皮卡特先生，他在1960年就乘坐自己设计的潜艇潜到了11000米的深海。我们一共有三队人马在世界各地拍摄，这样的话，我们就不会错过太多的镜头。大自然提供给我们的拍摄的机会总是弥足珍贵的，有些难得一见的镜头真的是转瞬即逝。海洋变化无常，动物们也不会按照人类既定好的时间表出来觅食或者是听从命令地秀一下。我们只有做好万全的准备，<br />
	才不会因为错过了什么而后悔。&rdquo;<br />
	<br />
	即使做好了准备，即使在这之前已经有了很多不同的海洋生态纪录片，但是轮到自己拍摄，雅克&middot;贝汉还是被海洋浩瀚和神秘震慑住了。他说：&ldquo;我们要拍摄沙丁鱼的洄游，这真是群庞大的生物。整整30公里长，400米宽和50米深的水域都是它们的天下&mdash;&mdash;真的有百亿条沙丁鱼挤在一起。在那段水域，我们看到了壮观的捕食：鲨鱼、海豹、水鸟还有鲸鱼都在围追堵截沙丁鱼。海洋的伟大岂止这一点点？我们和抹香鲸一起潜到了2000米的深海，这里更让人惊叹：巨型的章鱼、深海鲨鱼、一些水螅、怪怪的水母都让人惊叹。虽然在这之前我曾经在不少纪录片里看到过这些生物，但是轮到自己电影下载亲眼所见的时候，还是会很惊叹。我正是想通过这部纪录片表现出两种截然不同的海洋&mdash;&mdash;一个是我们常见的、浅处的海洋；还有一个就是神秘的，深处的、不为人知的海洋。这两种形象在一起，才是一个完整的海洋。&rdquo;<br />
	<br />
	【经费和责任】<br />
	<br />
	　　这么一部具有宏大视角的影片，动用起来的经费和物资是令人咋舌的。影片一共耗资7500万美元才拍摄出来，而且一部纪录片不一定能收得回成本，那这么多钱和潜水物资，雅克&middot;贝汉又是怎么筹集来的呢？贝汉说：&ldquo;我用的方法很传统，就是游说。我的观点就是，要让我们的孩子能看到自然、看到自然中丰富的动物；为了让他们看到这一切，我们现在就应该行动起来保护环境。我把我的这个观点告诉给那些财团、基金和工厂中的高管，他们的反应都非常积极。最后，我们从美国著名的斯隆基金会（Sloan Foundation）那里得到了资助，那是一大笔资助，有了这些钱，我们才有机会下潜到水底拍摄。其实，有了钱，再找来那些专业的人士，设备的事情，他们自然能解决。&rdquo;<br />
	<br />
	　　从拍摄《迁徙的鸟》开始，雅克&middot;贝汉就把&ldquo;唯美&rdquo;放在了自己的影片里。当年影片上映的时候，全世界的媒体都给予了这部飞翔的影片一致的褒奖。8年之后，雅克&middot;贝汉带着这部同样唯美的《海洋》来到了世人的面前。雅克&middot;贝汉希望影片通过对&ldquo;美&rdquo;本身的展示，达到唤起世人关注环境、关注生物的目的。贝汉说：&ldquo;在这部影片里，我既想为自然唱一首颂歌，又想让人们意识到自己在利用海洋和被舆论所误导。人们总是会说，海洋于己无关，实际上，海洋正在深刻地影响着他们的生活，也正是我在电影中所想表现的。虽然说这不是部激进的电影，但是我希望这是部有观点的、能引起观众共鸣和思考的影片。虽然说海洋是属于全人类的财富，但这并不意味着我们可以随意糟蹋它。海洋首先是个渔业资源的宝库，但是它不仅仅是个仓库，而且这个仓库总有一天是会被取光的。在我的眼中，海洋是个生物的宝库。我们拍摄了各种各样的动物，用摄影机追踪捕捉下它们的每一个动作。我们可以跟着剑鱼游曳，也可以尾随鲨鱼觅食&mdash;&mdash;这一切只需要坐在一个带着发动机的舢板上就可以完成。真的来到了海洋上，才能体味到大自然的伟大和伟力。漂在海洋上，会感觉到整个人的心灵都被洗涤过了，身心得到的是无比欢愉，感觉到的是无比的畅快。<br />
	可能只有有过这种经历，才能老老实实地敬畏自然并且善待自然，才能真正地展开环保行动。&rdquo;<br />
	<br />
	花絮<br />
	<br />
	&middot;本片于2010年的世界地球日在美国上映。<br />
	<br />
	&middot;影片在美国开映的首周，每卖出一张电影票，迪士尼自然将捐出20美分用于环保事业。<br />
	<br />
	&middot;本片和另外一部讲述海洋的纪录片《海豚湾》都曾在东京国际电影节上放映，不过两部影片的待遇确实冰火两重天。本片得到了喜爱和善待，《海豚湾》却收获了日本人的嘘声和抵制。<br />
	<br />
	&middot;本片导演雅克&middot;贝汉曾是一位获得过威尼斯电影节最佳男演员的出色演员，不过近年来他把自己的注意力放在了拍摄生态学纪录片上。著名的纪录片《迁徙的鸟》就出自他的手中。同时，他还在《微观世界》和《深蓝》中担任了解说。<br />
	<br />
	&middot;本片的另一位导演雅克&middot;克鲁奥德，曾经和雅克&middot;贝汉合作拍摄了《迁徙的鸟》。<br />
	<br />
	&middot;影片的制作成本高达7500万美元，耗费了4年时间拍摄。<br />
	<br />
	&middot;影片中登场的海洋生物至少有100种。<br />
	<br />
	&middot;瑞士探险家伯特兰&middot;皮卡特(Bertrand Piccard) 参与到了影片的制作中，他是第一位乘坐热气球环游地球一周的探险家。他的父亲雅克&middot;皮卡特（Jacques Piccard），于2008年11月1日逝世。在逝世前，他也曾参与到了影片的制作中。雅克&middot;皮卡德曾在1960年乘坐自己设计的深海潜水器雅斯特号（Trieste）在太平洋马里亚纳海沟（Mariana Trench）潜入10,916米的深海。</p>
<p>
	【电影截图】：<br />
	<br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('/uploads/allimg/c120524/133N42KUZ-35B30.jpg');" src="/uploads/allimg/c120524/133N42KUZ-35B30.jpg" /><br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('/uploads/allimg/c120524/133N42K9310-3EB6.jpg');" src="/uploads/allimg/c120524/133N42K9310-3EB6.jpg" /><br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('/uploads/allimg/c120524/133N42L0220-3J541.jpg');" src="/uploads/allimg/c120524/133N42L0220-3J541.jpg" /></p>
<p>
	[下载地址]：<img border="0" src="/uploads/allimg/c120524/133N2ZL930-142957.jpg" /></p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				ftp://3e:3e@d8.3edyy.com:174/【3E电影院www.eee4.cc】海洋BD中字1024x576高清版.rmvb</td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				ftp://dy44:piaohua@dy44.piaohua.com:1419/飘花电影piaohua.com海洋BD中英双字1280高清.rmvb </td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120524/133N42L0c0-3Y2Z.jpg{/dede:field}
