{dede:field name='keywords'}梁静茹今天情人节2008演唱会迅雷{/dede:field}
{dede:field name='description'}梁静茹今天情人节2008演唱会迅雷下载、免费下载，梁静茹今天情人节2008演唱会Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}梁静茹今天情人节2008演唱会{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2009-02-15{/dede:field}
{dede:field name='body'}<P><IMG alt="IPB Image" src="/uploads/allimg/c120524/133N4263B0-1b33.jpg" border=0 name=post_img></P>
<P>&nbsp;</P>
<P>梁静茹今天情人节2008演唱会<BR><BR><BR><B>专辑介绍：</B><BR><BR>如果我们能在一起, 我会记得今天！就是情人节。<BR>2008/06/07臺北小巨蛋12067个座位, 没有一个空位<BR>今年最邱比特的那个晚上,<BR>妳(&amp;你)在第几排第几号找到爱?<BR>[场地座位图]#希望找到场地座位图填上一颗一颗手绘的心型当座位<BR><BR>梁静茹的情歌有一种力量, 力量大到可能改变两个人的一生<BR>那一夜之前,是你的上半生与我的上半生<BR>那一夜之后,是我们俩的一生…<BR>梁静茹[今天情人节]<BR>LIVE DVDx2+LOVE CDx1<BR>如果我们能在一电影下载起, 我会记得今天！就是情人节。<BR><BR>[我有妳]LIVE DVD x2<BR>2008/06/07臺北小巨蛋珍实LIVE全纪录<BR>36首我们从头到尾十指紧扣的微笑与眼泪<BR><BR><B>[我爱你]LOVE CD x1</B><BR>五首崭新恋曲+十三首深刻追忆<BR>18本我们从今以后日记彼此的灵魂与呼吸</P>
<P><IMG src="/uploads/allimg/c120524/133N4263J30-23057.jpg"></P>
<P>2009-02-15 13:42:12 开始连接......<BR>2009-02-15 13:42:12 开始搜索候选资源......<BR>2009-02-15 13:42:12 搜索到42个候选资源<BR>2009-02-15 13:42:12 使用候选资源进行连接......<BR>2009-02-15 13:42:13 搜索到21个候选资源<BR>2009-02-15 13:42:13 使用候选资源进行连接......<BR>2009-02-15 13:42:13 文件创建成功，开始下载数据......<BR>2009-02-15 13:42:16 用户取消下载&nbsp;&nbsp; 来自：www.eee4.com</P>（一律使用迅雷下载）<BR>梁静茹今天情人节2008演唱会 －来自[3E电影站www.eee4.com]：<IMG src="http://www.eee4.com/templets/img/down.jpg" border=0><BR>CD1：<BR>
<TABLE style="BORDER-RIGHT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; BORDER-BOTTOM: #cccccc 1px dotted" cellSpacing=0 cellPadding=6 width="95%" align=center border=0>
<TBODY>
<TR>
<TD style="WORD-WRAP: break-word" bgColor=#fdfddf></ANCHOR>ftp://e49:e49@xl2.eee4.com:9024/[3E电影站www.eee4.com]梁静茹今天情人节2008演唱会CD1.rmvb</TD></TR></TBODY></TABLE>CD2：<BR>
<TABLE style="BORDER-RIGHT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; BORDER-BOTTOM: #cccccc 1px dotted" cellSpacing=0 cellPadding=6 width="95%" align=center border=0>
<TBODY>
<TR>
<TD style="WORD-WRAP: break-word" bgColor=#fdfddf></ANCHOR>ftp://e49:e49@xl2.eee4.com:9024/[3E电影站www.eee4.com]梁静茹今天情人节2008演唱会CD2.rmvb</TD></TR></TBODY></TABLE>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120524/133N42641140-46426.jpg{/dede:field}
