{dede:field name='keywords'}小鱼历险记BD国语1280高清经典动{/dede:field}
{dede:field name='description'}小鱼历险记BD国语1280高清经典动画迅雷下载、免费下载，小鱼历险记BD国语1280高清经典动画Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}小鱼历险记BD国语1280高清经典动画{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-09-30{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="/uploads/allimg/c120525/133O04642610-109522.jpg" /></p>
<p>
	◎译　　名　小鱼历险记<br />
	◎片　　名　A Fish Tale<br />
	◎年　　代　2000<br />
	◎国　　家　德国/爱尔兰/丹麦<br />
	◎类　　别　动画<br />
	◎语　　言　国语<br />
	◎IMDB评分&nbsp; 5.8/10 from 1,532 users&nbsp;<br />
	◎片　　长　01:20:01<br />
	◎导　　演　Stefan Fieldmark<br />
	◎主　　演　Nis Bank-Mikkelsen&nbsp;&nbsp;&nbsp;<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 艾伦&middot;瑞克曼<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 特瑞&middot;琼斯<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; S&oslash;ren S&aelig;tter-Lassen<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Morten Kerrn Nielsen<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; sebastian Jessen<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Pil Neja</p>
<p>
	◎剧情简介</p>
<p>
	13岁的复莱个性顽皮，有一天趁父母外游、安娜阿姨睡着时，跟妹妹丝黛拉及堂兄弟初克外出钓鱼。当他们偶然进入马其儿教授的实验室时，一个让人毛骨悚然的经历开始了。马其儿教授相信，整个社会很快就会变得混乱，所以正试验把人类变成鱼。丝黛拉喝了把人变成海星的药剂，被毫不知情的复莱扔进了海里。为了救丝黛拉，两个男孩只能喝下药剂变成了鱼。他们只剩下48小时来找到丝黛拉，否则他们就会永远变成鱼。不幸的是解毒剂也掉在海里了，一条叫约翰的鱼喝了解毒剂之后，有了人的声音和智商。于是约翰计划成为海洋霸主。一条怪物鲨鱼成了它的助手，它还成立了一支军队来管理自己王国。为了找到药剂的电影下载，约翰把闯入王国之中的复莱、丝黛拉和初克抓起来了，他们该如何战胜约翰变回人类？</p>
<p>
	<img alt="" src="/uploads/allimg/c120525/133O04643330-114I5.jpg" /></p>
<p>
	[下载地址]： &nbsp;<img border="0" src="/uploads/allimg/c120524/133N2Z4FF-102231.jpg" /></p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:1692/飘花电影piaohua.com小鱼历险记BD国语1280高清.rmvb</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O04644020-123561.jpg{/dede:field}
