{dede:field name='keywords'}兵临城下之决战要塞高清1024版BD{/dede:field}
{dede:field name='description'}兵临城下之决战要塞高清1024版BD国语版2012最新战争动作大片迅雷下载、免费下载，兵临城下之决战要塞高清1024版BD国语版2012最新战争动作大片Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}兵临城下之决战要塞高清1024版BD国语版2012最新战争动作大片{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-21{/dede:field}
{dede:field name='body'}<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120317/19/56643687201203171912551195601398522_006.jpg" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120317/19/56643687201203171912551195601398522_005.jpg" /></p>
<p>
	导演: 亚历山大&middot;科特<br />
	编剧: Aleksey Dudarev / Ekaterina Tirdatova / Konstantin Vorobiov / Vladimir Yeryomin<br />
	主演: 安德烈&middot;马斯连基 / Evgeniy Tsyganov / 巴维尔&middot;捷列连科 / Anna Tsukanova / 阿列沙&middot;嘉博索夫 / Veronika Nikonova / Anatoly Kot<br />
	类型: 剧情 / 动作 / 历史 / 战争<br />
	官方网站: <a href="http://www.bluemv.com">http://www.bluemv.com</a><br />
	制片国家/地区: 俄罗斯 / 白俄罗斯<br />
	语言: 国语<br />
	上映日期: 2010-11-04(白俄罗斯) / 2012-03-16(中国大陆)<br />
	片长: 138分钟(白俄罗斯) / 116分钟(中国大陆)<br />
	又名: 兵临城下 / 布列斯特要塞 / The Brest Fortress / Fortress of War / Brestskaya krepost<br />
	IMDb链接: tt1343703</p>
<p>
	<br />
	剧情简介</p>
<p>
	　　1941年6月25日，位于白俄罗斯和波兰交界的布格河东岸：鸟儿在歌唱、军乐队演奏着欢快的乐曲，公园里正举行联欢的舞会，祥和中，人们谈情说爱，追逐嬉戏，各自享受恬静、幸福的时光&hellip;&hellip;突然，飞机的俯冲扫射伴着铺天盖地的炮击撕裂了低沉的天空，爆炸的气浪和飞起来的尘埃瓦砾将惊恐的人们推倒、掩埋&hellip;&hellip;<br />
	　　这就是根据第二次世界大战苏德战场最初的经典而残酷的战役改编成的电影《兵临城下之决战要塞》的开场。<br />
	　　布列斯特要塞是连接华沙-莫斯科的交通要道，具有重要的战略意义，在成群的坦克和装备精良的德军围攻中，8000名英勇的苏维埃红军在武器短缺、建制混杂、牺牲巨大的情形下，坚守信念、捍卫祖国，以血肉之躯于弹丸之地牵制了数十倍于自己的德军兵力达三十天直至全部阵亡。<br />
	　　战斗中，团长和政委身先士卒，在反击中沉着指挥，鼓舞惊慌中的士兵燃起斗志，将不同建制的士兵拼成战斗团队，顽强防御要塞阵地；另一侧，德军一队人突入要塞，在搜索前进中与红军中尉率领的边防军遭遇，红军战士们或是端着上了刺刀的步枪、或是舞着工兵锹、铁棒甚至菜刀与德军展开白刃肉搏混战，刀枪不全的苏军凭借大无畏精神杀得德军死伤遍地、落荒而逃。<br />
	　　导演亚力山大?考特以红军小学员的视角，向观众呈现了这场苏德战争史上交战时间之长、红军战士之勇敢顽强、战斗场面之为&ldquo;惨烈悲壮&rdquo;的真实场景！在烘托宏大主题内涵的同时，激战场面扣人心弦，空袭、爆炸、火炮、坦克重机枪、火焰喷射器，加之大量烟火、音效、特技的运用，战争大片所包含的元素精彩呈现，视听效果空前震撼！　　</p>
<p>
	<br />
	◎影片截图</p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120317/19/56643687201203171912551195601398522_001.jpg" style="width: 600px; height: 338px" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120317/19/56643687201203171912551195601398522_002.jpg" style="width: 600px; height: 338px" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120317/19/56643687201203171912551195601398522_004.jpg" style="width: 600px; height: 338px" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120317/19/56643687201203171912551195601398522_003.jpg" style="width: 600px; height: 338px" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120317/19/56643687201203171912551195601398522_000.jpg" style="width: 600px; height: 338px" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3035/飘花电影piaohua.com兵临城下之决战要塞高清1024版BD国语版.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3035/飘花电影piaohua.com兵临城下之决战要塞高清1024版BD国语版.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O162U460-2Q40.jpg{/dede:field}
