{dede:field name='keywords'}宇宙系列第1季：太阳的秘密/火星{/dede:field}
{dede:field name='description'}宇宙系列第1季：太阳的秘密/火星：红色行星【第五集】迅雷下载、免费下载，宇宙系列第1季：太阳的秘密/火星：红色行星【第五集】Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}宇宙系列第1季：太阳的秘密/火星：红色行星【第五集】{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-21{/dede:field}
{dede:field name='body'}<p>
	◎译　　名　宇宙系列第1季：太阳的秘密/火星：红色行星【美国记录大片】<br />
	◎片　　名　The Universe EP01 Secrets of the Sun<br />
	◎年　　代　2007<br />
	◎国　　家　美国<br />
	◎类　　别　记录<br />
	◎语　　言　英语<br />
	◎字　　幕　中英双字幕<br />
	◎IMDB评分 9.1/10&nbsp; &nbsp;16 votes<br />
	◎IMDB链接 <a href="http://www.bluemv.com">http://www.bluemv.com</a><br />
	◎文件格式　RMVB<br />
	◎视频尺寸　1200 x 672<br />
	◎文件大小　193MB<br />
	◎片　　长　44 Mins<br />
	◎导　　演　Douglas Cohen<br />
	◎主　　演　<br />
	◎简　　介　<br />
	历史频道最新系列纪录片《宇宙》囊括了宇宙的一切，从黑洞到我们的太阳，从未探索的太空到可能存在生命的星球...<br />
	《宇宙》这个专题已经被N多机构做过N多遍了，但历史频道做的非常出色，在讲述人类探索宇宙的历史故事的时候，严谨详实地叙说了人类对宇宙的不懈探索，同时将已经了解和尚未了解的宇宙奥秘一一展现出来，真的秉承了历史频道的传统。特别是《火星》不知道被做过多少次了，但历史频道做来，给人感觉耳目一新，里面介绍了2007年最新的资讯，要知道现在还在2007年里啊。<br />
	第一季第1集:太阳的秘密:<br />
	它是天上的火球,一个高热等离子沸腾运动的星球,爆炸着,喷发着.它的大小几乎无法想象--100万个地球刚好填放进去.在这里,激烈的反应产生的所有能量保证了地球的上所有的生存,然而,它的秘密现在才刚开始被了解.从太阳黑子到日食,从太阳耀斑到太阳风暴,从太阳的诞生到它的可能的结局,探索这颗产生地球生命的天体的科学和它背后的历史.<br />
	[第一季第1集花絮]当年里根总统访华时，空军一号就曾被太阳风暴乾扰，数小时内无法通讯，美国政府顿时群龙无首。<br />
	<br />
	◎影片截图　<br />
	<br />
	<img alt="" border="0" onload="attachimg(this, 'load')" src="http://img.album.pchome.net/54/68/56/67/123298084127fd89ee4e840987012e7f2d56ce09bf.jpg" tmooc_h="1" />&nbsp;<br />
	<img alt="" border="0" onload="attachimg(this, 'load')" src="http://img.album.pchome.net/54/68/56/67/12329808419864bccd4614902700fa7e19a7bf9875.jpg" tmooc_h="1" />&nbsp;<br />
	<img alt="" border="0" onload="attachimg(this, 'load')" src="http://img.album.pchome.net/54/68/56/67/123298084211b047f5b87ed49024918d0e7faae789.jpg" tmooc_h="1" />&nbsp;<br />
	<img alt="" border="0" onload="attachimg(this, 'load')" src="http://img.album.pchome.net/54/68/56/67/1232980842fb0f11b47b66f51adb77f72d57d27a2f.jpg" tmooc_h="1" />&nbsp;<br />
	<img alt="" border="0" onload="attachimg(this, 'load')" src="http://img.album.pchome.net/54/68/56/67/12329808428d7470d3d736ce24b5e403386ce7fa36.jpg" tmooc_h="1" />&nbsp;<br />
	<img alt="" border="0" onload="attachimg(this, 'load')" src="http://img.album.pchome.net/54/68/56/67/12329562089f2e3c8a4d493728c99ecd8d5c4b3c2c.jpg" tmooc_h="1" />&nbsp;<br />
	<img alt="" border="0" onload="attachimg(this, 'load')" src="http://img.album.pchome.net/54/68/56/67/1232956208c9f43dbbe5e28a1ad3a254da91103526.jpg" tmooc_h="1" />&nbsp;<br />
	<img alt="" border="0" onload="attachimg(this, 'load')" src="http://img.album.pchome.net/54/68/56/67/12329562089e6518fa00c120af8605d1fb4eb19757.jpg" tmooc_h="1" /></p>
<p>
	2009-02-02 12:32:12 开始连接......<br />
	2009-02-02 12:32:12 开始搜索候选资源......<br />
	2009-02-02 12:32:12 搜索到22个候选资源<br />
	2009-02-02 12:32:12 使用候选资源进行连接......<br />
	2009-02-02 12:32:13 搜索到41个候选资源<br />
	2009-02-02 12:32:13 使用候选资源进行连接......<br />
	2009-02-02 12:32:13 文件创建成功，开始下载数据......<br />
	2009-02-02 12:32:16 用户取消下载&nbsp;&nbsp; 本文来自：<a href="http://www.bluemv.com">http://www.bluemv.com</a></p>
<p>
	（一律使用<a href="http://www.eee4.com/soft.htm" target="_blank">迅雷下载</a>）<br />
	美国记录大片《宇宙系列第1季》太阳的秘密/火星：红色行星 －来自[3E电影站www.eee4.com]：<img border="0" src="http://www.eee4.com/templets/img/down.jpg" /><br />
	第01集－太阳的秘密：</p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="BORDER-RIGHT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; BORDER-BOTTOM: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="WORD-WRAP: break-word">
				<anchor></anchor><a href="ftp://e30:e30@xl2.eee4.com:9916/[3E电影站www.eee4.com]宇宙系列01-太阳的秘密.rmvb" target="_blank">ftp://e30:e30@xl2.eee4.com:9916/[3E电影站www.eee4.com]宇宙系列01-太阳的秘密.rmvb</a></td>
		</tr>
	</tbody>
</table>
<p>
	第02集－火星-红色行星：</p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="BORDER-RIGHT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; BORDER-BOTTOM: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="WORD-WRAP: break-word">
				<anchor></anchor><a href="ftp://e30:e30@xl2.eee4.com:9916/[3E电影站www.eee4.com]宇宙系列02-火星：红色行星.rmvb" target="_blank">ftp://e30:e30@xl2.eee4.com:9916/[3E电影站www.eee4.com]宇宙系列02-火星：红色行星.rmvb</a></td>
		</tr>
	</tbody>
</table>
<p>
	第03集－地球末日：来自太空深处的威胁：</p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="BORDER-RIGHT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; BORDER-BOTTOM: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="WORD-WRAP: break-word">
				<anchor></anchor><a href="ftp://e35:e35@xl2.eee4.com:9916/[3E电影站www.eee4.com]宇宙系列03-地球末日：来自太空深处的威胁.rmvb" target="_blank">ftp://e35:e35@xl2.eee4.com:9916/[3E电影站www.eee4.com]宇宙系列03-地球末日：来自太空深处的威胁.rmvb</a></td>
		</tr>
	</tbody>
</table>
<p>
	第04集－木星：巨型行星：</p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="BORDER-RIGHT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; BORDER-BOTTOM: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="WORD-WRAP: break-word">
				<anchor></anchor><a href="ftp://e35:e35@xl2.eee4.com:9916/[3E电影站www.eee4.com]宇宙系列04-木星：巨型行星.rmvb" target="_blank">ftp://e35:e35@xl2.eee4.com:9916/[3E电影站www.eee4.com]宇宙系列04-木星：巨型行星.rmvb</a></td>
		</tr>
	</tbody>
</table>
<p>
	第05集－月球：</p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="BORDER-RIGHT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; BORDER-BOTTOM: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="WORD-WRAP: break-word">
				<anchor></anchor><a href="ftp://e35:e35@xl2.eee4.com:9916/[3E电影站www.eee4.com]宇宙系列05-月球.rmvb" target="_blank">ftp://e35:e35@xl2.eee4.com:9916/[3E电影站www.eee4.com]宇宙系列05-月球.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O161642F-4J45.jpg{/dede:field}
