{dede:field name='keywords'}大闹天宫3D-1280完美版BD国语201{/dede:field}
{dede:field name='description'}大闹天宫3D-1280完美版BD国语2012最新上映中国奇幻动画大片迅雷下载、免费下载，大闹天宫3D-1280完美版BD国语2012最新上映中国奇幻动画大片Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}大闹天宫3D-1280完美版BD国语2012最新上映中国奇幻动画大片{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-02-23{/dede:field}
{dede:field name='body'}<p>
	<img src="http://img165.poco.cn/mypoco/myphoto/20120113/12/56643687201201131232041886575051140_001.jpg" /></p>
<p>
	<img src="http://img165.poco.cn/mypoco/myphoto/20120113/12/56643687201201131232041886575051140_000.jpg" /></p>
<p>
	导演: 万籁鸣 / 唐澄 / 速达 / 陈志宏<br />
	编剧: 李克弱 / 万籁鸣<br />
	主演: 李扬 / 陈凯歌 / 陈道明 / 张国立 / 刘烨 / 胡歌 / 周立波 / 何炅 / 陈佩斯 / 姚晨 / 刘晓庆 / 冯小刚<br />
	类型: 动画<br />
	制片国家/地区: 中国大陆<br />
	语言: 汉语普通话<br />
	上映日期: 2012-01-11(中国大陆)<br />
	片长: 90分钟<br />
	又名: The Monkey K<a _fcksavedurl="http://www.qqtmb.com/" href="http://www.qqtmb.com/" style="color: rgb(0,0,0); text-decoration: none">qq</a>ing 3D</p>
<p>
	<br />
	剧情简介</p>
<p>
	　　美丽的花果山有一位神通广大的美猴王，但苦于没有一件得心应手的兵器，一直无法施展自己的本领。为此，他来到东海龙宫觅宝。傲慢的龙王根本没把这个不起眼的小猴子放在眼里，同意无论什么兵器，只要他能拿得动，就可以借给他。不料，看似手无缚鸡之力的美猴王，居然将三万六千斤的定海神针&mdash;&mdash;如意金箍棒玩于股掌之中。他在摆弄这根超级&ldquo;神针&rdquo;时还能轻巧地摆出各种&ldquo;POSE&rdquo;，气得龙王的胡须翘得半天高。<br />
	　　气急败坏的龙王到天宫告状，诬告猴王抢走了定海神针。玉皇大帝在太白金星的计谋下，诱骗猴王上天，封为看管天马的&ldquo;弼马温&rdquo;，趁机将他软禁起来，由此息事宁人。毫无戒备的猴王悠哉悠哉地<a _fcksavedurl="http://www.dailiv.com/" href="http://www.dailiv.com/" style="color: rgb(0,0,0); text-decoration: none">在线代理</a>腾云驾雾上了天宫。生性无拘无束的猴王开始了他的捣乱行动，首先放开了天马，这下惹恼了<a _fcksavedurl="http://www.anzhuo4.com/" href="http://www.anzhuo4.com/" style="color: rgb(0,0,0); text-decoration: none">安卓</a>御马监的主管马天君。马天君对猴王冷嘲热讽，肆意责骂，盛怒之下，他砸烂了御马监，一个筋斗翻回了花果山，竖起&ldquo;齐天大圣&rdquo;的旗帜，蔑视天宫，对抗天庭。<br />
	　　玉帝大怒，命托塔李天王率天兵天将下来捉拿猴王，美猴王率训练有素的众猴奋力抵抗，花果山上&ldquo;齐天大圣&rdquo;显尽神威，天兵天将被打得落花流水，逃回了天宫。玉帝只能让太白金星施计企图<a _fcksavedurl="http://www.dailiv.com/" href="http://www.dailiv.com/" style="color: rgb(0,0,0); text-decoration: none">淘宝网女装</a>再次诱骗猴王进宫，正式封其为&ldquo;齐天大圣&rdquo;，让他掌管蟠桃园好以此降服他。无所畏惧又充满自信的猴王再次以云彩为梯跃入天宫。采桃的仙女耻笑他这个&ldquo;齐天大圣&rdquo;根本就是一个毫不起眼的小角色，王母蟠桃宴上也没有他的一席之座。美猴王再次小宇宙爆发，抡着金箍棒把王母娘娘的蟠桃宴闹得天翻地覆，又一口气吃光了太上老君为玉帝炼制的九转金丹。玉帝忍无可忍，倾天宫之兵花了九牛二虎之力将猴王拿下，太上老君将其关进炼丹炉，熊熊烈火非但没有将他烧死，反而练就了猴王的神功。他挣脱了炼丹炉，一路厮杀，越战越勇，把天宫砸得稀巴烂，玉帝的凌霄宝殿也在他的神针下沦为废墟。　　</p>
<p>
	<br />
	◎影片截图</p>

<p>
	<img src="http://img165.poco.cn/mypoco/myphoto/20120113/12/56643687201201131231362411466164496_001.jpg" style="width: 600px; height: 338px" /></p>
<p>
	<img src="http://img165.poco.cn/mypoco/myphoto/20120113/12/56643687201201131231362411466164496_002.jpg" style="width: 600px; height: 338px" /></p>
<p>
	<img src="http://img165.poco.cn/mypoco/myphoto/20120113/12/56643687201201131231362411466164496_003.jpg" style="width: 600px; height: 338px" /></p>

<p>
	<img src="http://img2081.poco.cn/mypoco/myphoto/20120223/01/56643687201202230135031671466467216_003.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 322px; border-top: 0px solid; border-right: 0px solid" /></p>

<p>
	<img src="http://img2081.poco.cn/mypoco/myphoto/20120223/01/56643687201202230135031671466467216_002.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 322px; border-top: 0px solid; border-right: 0px solid" /></p>
<p>
	<img src="http://img2081.poco.cn/mypoco/myphoto/20120223/01/56643687201202230135031671466467216_001.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 322px; border-top: 0px solid; border-right: 0px solid" /></p>
<p>
	&nbsp;<img src="http://img2081.poco.cn/mypoco/myphoto/20120223/01/56643687201202230135031671466467216_000.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 322px; border-top: 0px solid; border-right: 0px solid" /></p>
<p>
	[下载地址]： &nbsp;<img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" /></p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2610/飘花电影piaohua.com大闹天宫3D-HD高清版国语.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2610/飘花电影piaohua.com大闹天宫3D-HD高清版国语.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2872/飘花电影piaohua.com大闹天宫3D-1280完美版BD国语.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2872/飘花电影piaohua.com大闹天宫3D-1280完美版BD国语.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1B3W30-433C.jpg{/dede:field}
