{dede:field name='keywords'}笑傲江湖2之东方不败HD高清粤语{/dede:field}
{dede:field name='description'}笑傲江湖2之东方不败HD高清粤语中字1024*576迅雷下载、免费下载，笑傲江湖2之东方不败HD高清粤语中字1024*576Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}笑傲江湖2之东方不败HD高清粤语中字1024*576{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-08-27{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20110825/23/56605031201108252323011559444433609_000.jpg" style="width: 600px; height: 804px" /></p>
<p>
	◎片　　名　 笑傲江湖之东方不败<br />
	◎译　　名 Swordsman II / Xiao ao jiang hu zhi: Dong Fang Bu Bai<br />
	◎年　　代　 1992<br />
	◎国　　家　 中国香港<br />
	◎类　　别　 动作/奇幻<br />
	◎语　　言　 粤语<br />
	◎IMDB评分　7.2/10 (1,920 votes)<br />
	◎IMDB链接　<a href="http://www.imdb.com/title/tt0103295/" target="_blank">http://www.imdb.com/title/tt0103295/</a><br />
	◎制作公司　 电影工作室 [香港]<br />
	　　　　　　 金公主电影制作有限公司 [香港]<br />
	　　　　　　 龙祥影业香港有限公司 [香港]<br />
	◎发行公司　 e-m-s the DVD-Company [德国] 2005 Germany DVD<br />
	　　　　　　 帝门影业公司 [美国]<br />
	　　　　　　 米拉麦克斯影业公司 [美国]<br />
	　　　　　　 Optimum Releasing [英国] 2005 UK DVD<br />
	◎片　　长　 108Mins<br />
	◎导　　演　 程小东 Siu-Tung Ching<br />
	◎编　　剧　 金庸 Louis Cha....novel<br />
	　　　　　　 徐克 Hark Tsui<br />
	　　　　　　 Hanson Chan<br />
	　　　　　　 Jack Maeby....English version<br />
	　　　　　　 邓碧燕 Elsa Tang<br />
	◎主　　演　 李连杰 Jet Li....Ling Wu Chung<br />
	　　　　　　 林青霞 Brigitte Lin....Asia the Invincible (Dong Fang Bu Bai)<br />
	　　　　　　 李嘉欣 Michelle Lee....Kiddo<br />
	　　　　　　 关之琳 Rosamund Kwan.... Ren Ying Ying<br />
	　　　　　　 李子雄 Waise Lee....Hattori<br />
	　　　　　　 袁洁莹 Fennie Yuen....Blue Phoenix<br />
	　　　　　　 刘洵 Shun Lau....Zen<br />
	　　　　　　 余安安 On-on Yu....Cici<br />
	　　　　　　 Audrey Wasilewski....Blue Phoenix Voice<br />
	<br />
	◎简　　介<br />
	<br />
	令孤冲（李连杰）在一次与师兄弟下山办事的过程中，意外的发现东方不败（林青霞）与倭寇串通有谋反之意，便与任盈盈（关之琳）向问天及蓝凤凰（袁洁莹）等计划，准备救出任我行联手除掉东方不败，夺回日月神教。但令孤冲不认识东方不败，误把东方不败当成一位美貌少女，以至于使自已的同门尽皆死于东方不败之手。于是令孤冲、任盈盈、向问天、任我行等一同去找东方不败报仇。在一场激烈的打斗中令孤冲面部被划伤，任我行一只眼被刺瞎，向问天小腿受伤，而东方不败坠入山崖&hellip;&hellip;<br />
	<br />
	◎幕　　后<br />
	<br />
	《东方不败》一片的故事其实并不出色，但是由于精彩绝伦的动作场面、鲜明独特的人物形象和紧凑的节奏，以及林青霞在片中的超越本色的演出，使得觀众无暇顾及故事的合理与否。片中的动作场面也创造了香港武侠片的新高，程小东将自己擅长气氛与动作相结合的长处在几场动作戏中体现得淋漓尽致：浪人夜袭苗区、东方不败血洗野店、黑木崖大战等等，其中不乏惊人之笔。如吸星吸出喷天的血柱等等。东方不败是徐克相当苦心经营的一个角色，是一个源于金庸原作但是进行了丰富与充实的人物。他的自信与自负、自怜与自艾，构成了这个人物独特的心理活动轨迹，也令这个人物充满了奇彩。他脱胎于原着中失败的政治人物符号，被徐克赋予了更深刻更复杂的内心与情感。这也是《东方不败》一片的最大成功之处。但是，由于徐克那亘古不变重形式轻思想，人物流于描写表面化的缺点，令这个角色没有被深入地挖掘。这不能不说是一大憾事。 </p>
<p>
	<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20110826/15/62564813201108261544398275957025807_004.jpg" style="width: 1024px; height: 576px" /><img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20110826/15/62564813201108261544398275957025807_003.jpg" /><img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20110826/15/62564813201108261544398275957025807_002.jpg" /><img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20110826/15/62564813201108261544398275957025807_001.jpg" /><img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20110826/15/62564813201108261544398275957025807_000.jpg" /><br />
	&nbsp;</p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="word-break: break-all; line-height: 18px" width="100%">
				<a href="&#13;&#10;ftp://dy125:piaohua@dy125.piaohua.com:2064/飘花电影piaohua.com笑傲江湖2HD高清粤语中字1024分辨率.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:2064/飘花电影piaohua.com笑傲江湖2HD高清粤语中字1024分辨率.rmvb </a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1BcT0-23924.jpg{/dede:field}
