{dede:field name='keywords'}密室之不可靠岸HD高清迅雷下载，{/dede:field}
{dede:field name='description'}密室之不可靠岸HD高清迅雷下载、免费下载，密室之不可靠岸HD高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}密室之不可靠岸HD高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-11-19{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://www.luangh.com/up/files/61/00180804.jpg" style="width: 700px; height: 980px" /></p>
<p>
	◎译　　名　密室之不可靠岸/密室2<br />
	◎片　　名　Lost In Panic Cruise &nbsp;<br />
	◎年　　代　2011<br />
	◎国　　家　中国<br />
	◎类　　别　悬疑/惊悚 &nbsp;<br />
	◎语　　言　普通话<br />
	◎字　　幕　中文<br />
	◎片　　长　1h:38min:54s<br />
	◎IMDB评分 &nbsp;None<br />
	◎IMDB链接 &nbsp;<a href="http://www.imdb.com/title/" target="_blank">http://www.imdb.com/title/</a><br />
	◎导　　演　张番番 Fanfan Zhang<br />
	◎主　　演　苏有朋 Alec Su &nbsp;....柳飞云<br />
	　　　　　　杨坤 Yang Kun<br />
	　　　　　　倪虹洁 Hongjie Ni<br />
	　　　　　　周韦彤 Weitong Zhou<br />
	　　　　　　吴辰君 Annie Wu<br />
	　　　　　　毛俊杰 Junjie Mao<br />
	　　　　　　孙一理 Yi-li Sun<br />
	<br />
	<br />
	<br />
	◎简　　介　<br />
	<br />
	&nbsp; &nbsp; &nbsp; &nbsp;故事承接上一部《密室之不可告人》的结局。推理小说家柳飞云（苏有朋饰演）应邀携经纪人李晓峰（孙一理饰演）参加好友董磊（杨坤饰演）的豪华蜜月游轮游，在船上邂逅了甜美的新娘苏静静（倪虹洁饰演）和她美丽迷人的三个同事&mdash;&mdash;漂亮的肖扬（毛俊杰饰演）、性感的朱迪（周韦彤饰演）、优雅的韩菲菲（吴辰君饰演），一场充满了暧昧的性感之旅就此展开<br />
	。白日，游轮上，性感美女、佳酿、碧海、白云，仿若远离人世的极乐园；夜晚，销魂狂野的化妆舞会、暧昧的调情嬉戏、彻夜狂欢&hellip;&hellip;然而就在这纸醉金迷的华丽之下，却潜流着不可告人的黑暗阴谋。谁都未能料到，这一夜风流竟会是最后的狂欢&hellip;&hellip;<br />
	&nbsp; &nbsp; &nbsp; &nbsp;午夜，一具艳尸被发现在甲板上。不久后，又有一位美女在密室中暴毙&hellip;&hellip;黑漆漆远离海岸的大海上，如&ldquo;密室&rdquo;一般的游轮随波荡漾，人心惶惶，谁也不知这艘承载着欢乐和谋杀的游轮是否还能平安靠岸&hellip;&hellip;而柳飞云在种种蹊跷中剥茧抽丝，寻找线索，竟然挖掘出一个多年悬案的惊人相&hellip;&hellip;<br />
	<br />
	◎幕后制作<br />
	<br />
	&nbsp; &nbsp; &nbsp; &nbsp;<b>◇苏有朋&mdash;&mdash;我就是侦探，我就是柳飞云，这不只是嘴上说的一句话，而是内心绵延几个月的惊心动魄。</b><br />
	<br />
	　　 &ldquo;在《密室2》中，我真正找到了一种感觉，一种惊心动魄的感觉，我就是一个侦探，我就是柳飞云，这种惊心动魄不只是说在嘴上，而是落在心里，绵延了几个月，直到有一天，我告诉导演，可以了，咱们开始吧。&rdquo;<br />
	<br />
	&nbsp; &nbsp; &nbsp;<br />
	&nbsp; &nbsp; &nbsp; &nbsp;<b>◇杨坤&mdash;&mdash;有一种&ldquo;富二代&rdquo;与你形影不离（饰演富豪董磊）</b><br />
	<br />
	　　&ldquo;首次看到自己的形象搬上大银幕，简单、兴奋、期待未来&rdquo;<br />
	<br />
	&nbsp; &nbsp; &nbsp; &nbsp;<b>◇吴辰君&mdash;&mdash;&ldquo;宿命&rdquo;是这个女人摆脱不掉的&ldquo;梦魇&rdquo;（饰演韩菲菲） </b><br />
	<br />
	　　&ldquo;韩菲菲对于我而言就是一场宿命的轮回，当年的恋人成为自己闺蜜的未婚夫，而自己又鬼使神差的踏上了这条不可靠岸的游轮，当自己想醒过来的时候才发现，没有力气睁开眼睛。&rdquo;<br />
	<br />
	&nbsp; &nbsp; &nbsp; <b>◇周韦彤&mdash;&mdash;天使的面孔 &nbsp;魔鬼的身材 &nbsp;漂亮到底还是错（饰演朱迪） </b><br />
	<br />
	　　&ldquo;被自己的闺蜜偷，被自己的闺蜜算计，被自己的闺蜜胁迫，同时自己也这样对待闺蜜，这个拥有天使面孔魔鬼身材的女人，内心中的惶恐不安时时刻刻在影片中晃荡在观众眼前。&rdquo;<br />
	<br />
	&nbsp; &nbsp; &nbsp;<br />
	&nbsp; &nbsp; &nbsp; &nbsp;<b>◇倪虹洁&mdash;&mdash;爱情上受伤害可能是遗传（饰演苏静静） </b><br />
	<br />
	　　&ldquo;苏静静是一个温柔软弱善良的女孩，悲惨的身世一直让她觉得不安，嫁入豪门的愿望并不是她内心的真实渴望。&rdquo;<br />
	<br />
	&nbsp; &nbsp; &nbsp; &nbsp;<b>◇毛俊杰&mdash;&mdash;如果再来一次不再贪婪（饰演肖扬）</b><br />
	<br />
	　　&ldquo;如果还能留着童年的纯真，还能懂得友情的真正含义，如果再来一次，结果一定会不　同，可惜生命只有一次机会。&rdquo;<br />
	<br />
	&nbsp; &nbsp; &nbsp; &nbsp;<br />
	&nbsp; &nbsp; &nbsp; &nbsp;<b>◇孙一理&mdash;&mdash;&ldquo;福尔摩斯&rdquo;身边的华生（饰演李晓峰） </b><br />
	<br />
	　　 &ldquo;我永远不是主角，但是我永远是主角身边最信任的人，有的时候这可能是最大的谎言。&rdquo;<br />
	<br />
	&nbsp; &nbsp; &nbsp; &nbsp;<b>◇杨坤倪虹洁喝交杯酒 大谈床戏内幕</b><br />
	　　<br />
	&nbsp; &nbsp; &nbsp; &nbsp;影片中杨坤与倪虹洁的床戏照片，劲爆程度让两位主演都表示拍摄时现场都非常尴尬。杨坤自爆&ldquo;苦大仇深&rdquo;的历史，并表示是自己让倪虹洁慢慢的入戏。倪虹洁表示，拍摄床戏非常难，因为做的每一个动作都不是自然的，而是摆拍。倪虹洁透露说，剧本中关于床戏的部分其实只有一句话，有&ldquo;拥吻&rdquo;等词语，而在她现场的表现也遭到了杨坤的嘲笑：&ldquo;她是专业演员啊，竟然比我这不会演戏的人还难为情！&rdquo;杨坤表示，自己为了拍好这场戏，提前在家里抱着枕头练习了一晚上。在谈到未来是否进军电影圈时，杨坤称自己仅是玩票而已，并无长远打算。<br />
	<br />
	　　 &nbsp;<b>◇杨坤自称玩票 现场深情献唱主题曲</b><br />
	<br />
	&nbsp; &nbsp; &nbsp; &nbsp;去年的《密室之不可告人》主题曲由&ldquo;大侦探&rdquo;苏有朋亲自上阵演唱，此次，杨坤加盟《密室2》，创作了电影的主题曲《会不会》，并作为自己新专辑的主打歌曲。活动现场，杨坤伴着惊心动魄和唯美温暖的主题曲MV演唱了这首歌，赢得满场喝彩。说起演戏和唱歌，杨坤连称：&ldquo;演戏要辛苦得多，有一场戏，我和苏有朋在水里打斗，拍了整整12个小时，就一直在水里泡着，非常痛苦！&rdquo;<br />
	<br />
	　　&ldquo;会不会&rdquo;，本身这三个字就非常男人寻味，凶手会不会就是其中之一，推理的色彩结合惊心动魄的故事情节，相信这款MV一定能勾起大家观影的欲望。&ldquo;一杯黑咖啡 填不满空的胃 连续第几天晚睡 他们说的对何必那么累&rdquo;，歌词的寓意十分深刻，与电影的主题爱与恨罪与罚非常贴切。<br />
	<br />
	<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20111119/14/62564813201111191413198640068362797_003.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20111119/14/62564813201111191413198640068362797_002.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20111119/14/62564813201111191413198640068362797_001.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20111119/14/62564813201111191413198640068362797_000.jpg" style="width: 720px; height: 405px" /><br />
	&nbsp;</p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="&#13;&#10;ftp://dy125:piaohua@dy125.piaohua.com:7200/飘花电影piaohua.com密室之不可靠岸HD国语中字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:7200/飘花电影piaohua.com密室之不可靠岸HD国语中字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1603c50-1W38.jpg{/dede:field}
