{dede:field name='keywords'}国家地理世界致命动物：非洲HD中{/dede:field}
{dede:field name='description'}国家地理世界致命动物：非洲HD中字1024高清美国纪录片迅雷下载、免费下载，国家地理世界致命动物：非洲HD中字1024高清美国纪录片Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}国家地理世界致命动物：非洲HD中字1024高清美国纪录片{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-01-08{/dede:field}
{dede:field name='body'}<p>
	<img alt="" height="335" src="/uploads/allimg/c120524/133N492N40-313E9.jpg" width="600" /><br />
	◎片　　名　National.Geographic.World&#39;s Deadliest Animals：Africa<br />
	◎译　　名　国家地理.世界致命动物.非洲<br />
	◎年　　代　2008<br />
	◎影片类型　纪录片<br />
	◎片　　长　47 Mins<br />
	◎国　　家　美国<br />
	◎对白语言　英语<br />
	◎编　　码　720P.HDTV-RMVB<br />
	◎视频尺寸　1024 x 576<br />
	◎文件大小　992MB<br />
	◎简　　介　<br />
	<br />
	　　非洲的野生大地上住着各种奇异的动物，它们每天都要面对生死激战。这之中，又有十二种动物精英，个个身怀掠食绝技，出手不凡。从北边的撒哈拉沙漠、南边的苍翠平原，到浩瀚的尼罗河，这些动物到底有什么必杀本领？我们将一探究竟。我们不仅要探究这些动物如何在物竞天择的演化法则中生存下来，还会请亲身经历动物追杀的人现身说法。<br />
	　　非洲是野生动物的战场，古老的巨兽是潜行捕猎者，它们凶残无比地掠食动物，在此抗争和生存，但在这些物种当中，由十二种动物称霸，这些掠食动物敏捷、有力、凶残，准备和非洲十二凶煞面对面吗？国家地理频道的&ldquo;动物杀手：非洲篇&rdquo;将为您展现。动物也有黑社会，不信？看看&ldquo;十二凶煞&rdquo;是如何称霸非洲的吧。<br />
	<img alt="" height="337" src="/uploads/allimg/c120524/133N4929E0-1450A.jpg" style="cursor: pointer" width="600" /><br />
	<img alt="" height="337" src="/uploads/allimg/c120524/133N492a60-15C44.jpg" style="cursor: pointer" width="600" /><br />
	<img alt="" height="337" src="/uploads/allimg/c120524/133N492b30-163637.jpg" style="cursor: pointer" width="600" /></p>
<hr />
<p>
	[下载地址]： &nbsp;<img border="0" src="/uploads/allimg/c120524/133N2Z4FF-102231.jpg" />
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:2551/飘花电影piaohua.com国家地理世界致命动物非洲HD中字1024高清.rmvb</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120524/133N492c0P-1J206.jpg{/dede:field}
