<?php
$z[0]=Array("field","2OO9年央视春节联欢晚会迅雷下载",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","2OO9年央视春节联欢晚会迅雷下载、免费下载，2OO9年央视春节联欢晚会Gvod高清在线播放，剧情介绍等。",73,211);
$z[1][4]['name']="description";
$z[2]=Array("field","2OO9年央视春节联欢晚会",213,273);
$z[2][4]['name']="title";
$z[3]=Array("field","",275,314);
$z[3][4]['name']="writer";
$z[4]=Array("field","",316,355);
$z[4][4]['name']="source";
$z[5]=Array("field","2009-01-28",357,407);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",409,446);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://e30:e30@xl2.eee4.com:9916/[3E电影站www.eee4.com]2OO9年春节联欢晚会CD1.rmvb\" target=\"_blank",448,583);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MP460020-16324.jpg",585,669);
$z[8][4]['name']="litpic";

?>