{dede:field name='keywords'}歇斯底里/震动性世纪BD1280高清{/dede:field}
{dede:field name='description'}歇斯底里/震动性世纪BD1280高清迅雷下载、免费下载，歇斯底里/震动性世纪BD1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}歇斯底里/震动性世纪BD1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-04-17{/dede:field}
{dede:field name='body'}<p>
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120414/12/56643687201204141256384179763975973_005.jpg" /><br />
	<br />
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120414/12/56643687201204141256384179763975973_008.jpg" /><br />
	<br />
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120414/12/56643687201204141256384179763975973_007.jpg" /><br />
	<br />
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120414/12/56643687201204141256384179763975973_006.jpg" /><br />
	&nbsp;</p>
<p>
	◎译　　名　歇斯底里/震动性世纪(台)<br />
	◎片　　名　Hysteria<br />
	◎年　　代　2011<br />
	◎国　　家　英国/法国/德国<br />
	◎类　　别　喜剧/爱情<br />
	◎语　　言　英语<br />
	◎字　　幕　中文<br />
	◎IMDB评分 7.0/10 ( 1,662 votes)<br />
	◎IMDB链接 <a href="http://www.imdb.com/title/tt1435513/">http://www.imdb.com/title/tt1435513/</a><br />
	◎文件格式　高清1280版BD-RMVB<br />
	◎视频尺寸　1280X720<br />
	◎文件大小　1CD 488MB<br />
	◎片　　长　1h 39mn<br />
	◎导　　演　谭雅&middot;维克斯勒 Tanya Wexler<br />
	◎主　　演　玛吉&middot;吉伦哈尔 Maggie Gyllenhaal<br />
	　　　　　　休&middot;丹西 Hugh Dancy<br />
	　　　　　　菲丽希缇&middot;琼斯 Felicity Jones<br />
	　　　　　　鲁伯特&middot;艾弗雷特 Rupert Everett<br />
	　　　　　　乔纳森&middot;普雷斯 Jonathan Pryce<br />
	　　　　　　安娜&middot;钱斯勒 Anna Chancellor<br />
	　　　　　　盖玛&middot;琼斯 Gemma Jones<br />
	　　　　　　Tobias Menzies<br />
	　　　　　　Sheridan Smith<br />
	　　　　　　Kate Linder ....Lady Cherwill<br />
	　　　　　　David Ryall<br />
	　　　　　　多米尼克&middot;波雷里 Dominic Borrelli ....Man at Edwards<br />
	　　　　　　Georgie Glen<br />
	　　　　　　Malcolm Rennie<br />
	　　　　　　Jonathan Rhodes ....PC Fugate</p>
<p>
	<br />
	◎简　　介</p>
<p>
	这是一部关于维多利亚时代女性&ldquo;振动棒&rdquo;的发明以及爱情和下半身的电影。当然它并没有听上去那么下流，而是一部无公害的带有情趣用品发展史简介的爱情喜剧。</p>
<p>
	本片改编自真人真事,还原世上第一只电动按摩棒发明时不为人知的故事。时间回到社会礼仪繁复、而电力已非新鲜事的维多利亚时代,休丹希所饰演的医生莫提梅刚找到新工作,跟随一位「歇斯底里症专家」治疗「女性疾病」,而为了改善忧郁、焦虑的症状,他们发现手指按摩有着惊人的效果,每天为大排长龙的女病患按摩按到手抽筋。然而,成功总是要付出代价,他发现他的老板不再信任他,而女权斗士夏绿蒂则指控他是个大骗子。一则机智幽默的浪漫喜剧,不仅揭示史上第一个申请专利的电动按摩棒,在发明过程背后的启发与秘辛,也展现了女性追求自由与解放的动人过程。</p>
<p>
	一句话评论</p>
<p>
	影片并没有像它表现出来的那么无理和颠覆,但是庸俗的喜感和粗俗的活跃上,谭雅&middot;维克斯勒还是做到了&ldquo;无人能及&rdquo;。</p>
<p>
	很多人觉得这会是一部肮脏、下流的电影。其实不然,这只是一部无公害的带有历史影子和情趣用品发展史的爱情喜剧。</p>
<p>
	可以说这是一部亦庄亦谐的影片。在提供最原始和最身体化的笑料的同时,影片又给我们提出了一个最尖锐的问题&mdash;&mdash;关于欲望、身体、社会化的女性和文化认同的问题。</p>
<p>
	<br />
	幕后制作</p>
<p>
	　　女导演、女演员的女性故事</p>
<p>
	　　本片导演谭雅&middot;维克斯勒出道时间不长,也没有拍摄过着名作品,但是在得知了&ldquo;振动棒&rdquo;的发明历史之后,她还是义无反顾地投入到了这部电影的筹拍之中。筹拍的过程是漫长的,又找人写剧本,又要自己去拉投资,这部电影前前后后耗去了她五年的时间。谈及影片的灵感来源和史实与虚构的比例,谭雅&middot;维克斯勒说: &ldquo;当时我是在一个偶然的情况下得知的这个故事,我觉得这很适合被改编成一部电影&mdash;&mdash;当然是从积极和喜剧的方面。后来我查阅了一些资料,发现一共是有三个医生一起发明的这个按摩棒。然后我就在脑子里构思一个关于按摩棒、爱情和下半身的故事。那是在十九世纪末和二十世纪初,女性还是很羞于谈论下半身的问题的, 她们不会说自己的夫妻生活如何如何、自己丈夫的性能力如何如何,所以这个发明几乎就是拯救了她们的私人生活。换个角度说,这个发明还是一个解放了劳动力的东西。我觉得这很有趣,如果把另一个爱情故事放在这个发明出现的前前后后,那一定会是一部令人难以忘记的电影。所以,我在影片中就设置了一个交际花一样的女性,她和医生的交往就成了影片的线索。&rdquo;</p>
<p>
	　　当然,谭雅&middot;维克斯勒并没有把按摩棒和女性的欲望当作影片的主体来讲述,这两个东西不过是&ldquo;怡情的道具&rdquo;而已,她把自己的重点,放在了讲述女性是如何面对当时的社会、如何处理自己的爱情生活上的。谭雅&middot;维克斯勒说:&ldquo;我在影片中就设置了一个交际花一样的女性,她和医生的交往就成了影片的线索。当然,这些都是虚构的,因为在那个年代里,一个女人要是敢于寻找自己的爱情,那么她一定会被别人认为是不忠的、肮脏的。但是玛吉&middot;吉伦哈尔所扮演的那个角色,却是一个纯情的女性。她受的教育不多,但是善解人意,她搞不懂自己的爱人在做什么,但却懂得去维护自己的爱情。我觉得这是一个开放的、进步的、超前的角色。&rdquo; 说道自己的角色,玛吉&middot;吉伦哈尔说:&ldquo;从某些角度上来说,这是一个上天赐予人间的天使,她不受世俗的观点的羁绊,也明白自己的追求。也就是这种与众不同的特质,使她成为了影片中最为亮眼也最为抢戏的角色。我很喜欢这个人物,无论她是真实的还是虚构的,我都觉得这个角色很真诚,很像是一个现实里存在的人物。&rdquo;</p>
<p>
	　　这样的角色、这样的题材、这样拥有G点的故事,带给了谭雅&middot;维克斯勒很大的挑战。她说:&ldquo;要拿捏住下半身的笑话的分寸,是我遇到的最大的挑战。如果玩笑开的过火了,那就和这部电影的主旨与气氛不相符;如果太隔靴搔痒,那就会让观众失望。表现性高潮、表现女性的欲望和身体的快感,是重点也是难点。而且, 我仅仅有想法还不行,还需要有杰出的演员把这些内容表达出来。当然,影片里的那些&lsquo;性饥渴&rsquo;的演员们,做的都非常出色。而且,玛吉&middot;吉伦哈尔的表现非常出色,她完全展示出的我想赋予角色的那种特质和性格。应该说,是她和那一群出色的演员成就了这部电影。&rdquo;</p>
<p>
	花絮</p>
<p>
	&middot;影片的标题,Hysteria,指的是医学上的一种病症,通常情况下,这种病叫做&ldquo;兴奋过度症&rdquo;。也就是在影片背景的那段时间内,很多女性都被莫名其妙地临床诊断为&ldquo;兴奋过度症&rdquo;。</p>
<p>
	&middot;影片根据约瑟芬&middot;莫蒂墨&middot;格兰威尔博士的真实故事改编。格兰威尔博士在医学史上赫赫有名,他在1880年发明了第一根机电式震动棒。他原先只是想把这个设备当做单纯的缓解肌肉疼痛的按摩器,没想到这个按摩棒却成为了千万女性的治疗歇斯底里的&ldquo;情趣玩具&rdquo;。</p>

<p>
	◎影片截图</p>
<p>
	&nbsp;&nbsp;<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120414/12/56643687201204141256384179763975973_003.jpg" /></p>
<p>
	&nbsp;<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120414/12/56643687201204141256384179763975973_000.jpg" /></p>
<p>
	&nbsp;<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120414/12/56643687201204141256384179763975973_004.jpg" /></p>
<p>
	&nbsp;<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120414/12/56643687201204141256384179763975973_002.jpg" /></p>

<p>
	【下载地址】</p>
<table bgcolor="#0099cc" border="0" cellpadding="10" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.net" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy125:piaohua@dy125.piaohua.com:7859/飘花电影piaohua.com歇斯底里BD中字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:7859/飘花电影piaohua.com歇斯底里BD中字1280高清.rmvb</a></td>
		</tr>
		<tr>
		</tr>
	</tbody>
</table>
<br />{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15D9560-16339.jpg{/dede:field}
