{dede:field name='keywords'}绑架/连环局HD高清迅雷下载，免{/dede:field}
{dede:field name='description'}绑架/连环局HD高清迅雷下载、免费下载，绑架/连环局HD高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}绑架/连环局HD高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-10-07{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://imgly.net/di-I9FW.jpg" /></p>
<p>
	◎译　　名　绑架/连环局<br />
	◎片　　名　Kidnap/Bong ga<br />
	◎年　　代　2007<br />
	◎国　　家　中国香港<br />
	◎类　　别　惊悚<br />
	◎语　　言　普通话<br />
	◎字　　幕　繁体中文<br />
	◎IMDB评分 &nbsp;5.6/10 (203 votes)<br />
	◎IMDB链接 &nbsp;<a href="http://www.imdb.com/title/tt1045818" target="_blank">http://www.imdb.com/title/tt1045818</a><br />
	◎片　　长　100 Mins<br />
	◎导　　演　罗志良 Chi-Leung Law<br />
	◎主　　演　刘若英 Rene Liu<br />
	　　　　　　林嘉欣 Karena Lam<br />
	　　　　　　张智霖 Julian Cheung<br />
	　　　　　　郭涛 Tao Guo<br />
	　　　　　　张兆辉 Siu-Fai Cheung<br />
	　　　　　　官恩娜 Ella Koon<br />
	　　　　　　赵会南 Huinan Zhao<br />
	　　　　　　罗仲谦 Chung Him Law<br />
	　　　　　　<br />
	◎简　　介　<br />
	<br />
	三宗绑架案，将两个女人的命运纠缠交错；三年前，林晓阳(林嘉欣饰演)的弟弟被绑架，处理绑架案的正是女督察何婉真(刘若英饰演)；三年后，何婉真接手调查一宗绑架案，案件却阴差阳错引发另一宗绑架案发生，是次绑匪部署精细，成功避过了警方的追踪和监听，还懂得操控婉真的心理 &hellip;婉真尤如当年晓阳一样，一步一步走入跟绑匪的心理角力战&hellip;&hellip;<br />
	舞蹈教师林晓阳（林嘉欣饰）的弟弟突然被人绑架，高级督察何宛真（刘若英饰）和智叔（张兆辉饰）奉命解救人质，但是在抓捕过程中，两名却绑匪意外坠楼身亡，最后警察历经千辛万苦找到确实一具尸体，林晓阳也因此在心里埋下了怨恨，她将所有的责任都归咎于警察身上，也为三年后那一场惊天动地的绑架埋下了伏笔。<br />
	三年后，林晓阳似乎已经从那次的绑架事件的伤害中恢复过来了，并且与当年负责其弟绑架案的两名警察成为了好友，特别是智叔，更是成为了林晓阳夫妇的好友，两人从尼泊尔度假归来，还请来智叔来觀看林晓阳排演的新舞蹈。<br />
	然而，林晓阳的丈夫（赵会南饰）身患重病，急需马上出国动手术，手术费约一千万元，绑架案的策划由此展开。林嘉欣首先将富豪王森（郭涛饰）的所有消息搜集起来，并经过多日跟踪调查，在掌握了所有王森儿子的行踪之后才派出两名同伙前往学校进行绑架。但是，林晓阳没有想到的是，当时王森的儿子正好与高级督察何宛真的儿子在一起玩耍，两个孩子为了骗保姆，躲到厕所里互换服装和帽子，谁知竟被绑匪误撞，将何宛真的儿子绑走，王森的儿子目睹了这一切，却因为惊吓过度不敢回家，结果造成了极大的误会。林晓阳、何宛真、王森等都以为是王森的儿子被绑架，林晓阳利用高科技变声器给王森打电话勒索赎金，王森立刻向警察报案，而受理此案的正是当年受理林晓阳弟弟被绑架案的两位高级督察何宛真和智叔。警匪双方在连环绑架案中展开心理、情感、意志的较量&hellip;&hellip;<br />
	<br />
	幕后制作<br />
	<br />
	　　影后林嘉欣、刘若英飙戏<br />
	<br />
	林嘉欣首遇影后级对手刘若英。要做到知己知彼，电影开拍前，林嘉欣便四出打探对方过去。但经多月合作，林嘉欣刘若英不但&ldquo;生变熟&rdquo;，言谈间更发现彼此生活习惯、衣着品味相近，令二人不禁大叹相逢恨晚。<br />
	<br />
	林嘉欣笑说二人情同姊妹：&ldquo;我同刘若英关系真是很好，不单止大家喜好相似，想法都一样，好似曾经在同一场戏，就向导演罗志良发问同一个疑问，我好开心此次合作认识她。&rdquo;<br />
	<br />
	导演大爆两人一开拍就互相斗戏: &ldquo;两人都是认真演员，一开始嘉欣以为自己演的是刘若英角色，一个高级督察兼母亲角色，觉得发挥较大；可是当知道要演的是一个剧场老师的角色，她就不停翻看剧本，看了数遍后，摸透了所演角色的复杂性，就如角色上身，跟她合作第三次，这是我第一次见到嘉欣如此入戏的。&rdquo;<br />
	&nbsp;</p>
<p>
	<img alt="" src="http://img165.poco.cn/mypoco/myphoto/20111006/11/62564813201110061116533362196299105_001.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img165.poco.cn/mypoco/myphoto/20111006/11/62564813201110061116533362196299105_000.jpg" style="width: 720px; height: 405px" /><br />
	&nbsp;</p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="&#13;&#10;ftp://dy125:piaohua@dy125.piaohua.com:6073/飘花电影piaohua.com连环局HD国语中字1024高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:6073/飘花电影piaohua.com连环局HD国语中字1024高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1602Z30-51M2.jpg{/dede:field}
