{dede:field name='keywords'}翻译风波/致命译电[HD中英双字10{/dede:field}
{dede:field name='description'}翻译风波/致命译电[HD中英双字1024x576+1280x720高清版]迅雷下载、免费下载，翻译风波/致命译电[HD中英双字1024x576+1280x720高清版]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}翻译风波/致命译电[HD中英双字1024x576+1280x720高清版]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2010-08-17{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://3e:3e@d8.3edyy.com:168/【3E电影院www.eee4.cc】翻译风波HD中英双字1024x576高清版.rmvb" target=_blank>ftftp://3e:3e@d8.3edyy.com:168/【3E电影院www.eee4.cc】翻译风波HD中英双字1024x576高清版.rmvb</A></TD></TR></TBODY></TABLE><br><font color="#ff0000" size="2{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MP3233F-12923.jpg{/dede:field}
