{dede:field name='keywords'}谍网迷魂/满洲候选人/洗脑密令BD{/dede:field}
{dede:field name='description'}谍网迷魂/满洲候选人/洗脑密令BD中英双字1024/1280高清迅雷下载、免费下载，谍网迷魂/满洲候选人/洗脑密令BD中英双字1024/1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}谍网迷魂/满洲候选人/洗脑密令BD中英双字1024/1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-12-22{/dede:field}
{dede:field name='body'}<p>
	<img alt="" border="0" src="http://i3.6.cn/cvbnm/df/fb/42/852899d1920e12c59669dcb6c9637632.jpg" /></p>
<p>
	【中文译名】《谍网迷魂/2004谍网迷魂/满洲候选人/洗脑密令》经典惊悚大片DVD中英字幕1280&times;720高清版<br />
	【影片原名】The Manchurian Candidate<br />
	【出品公司】Paramount Home Entertainment<br />
	【上映日期】2004年7月22日 美国<br />
	【影片长度】129 min<br />
	【对白语言】英语<br />
	【字　　幕】中文/英文<br />
	【尺　　寸】1280&times;720<br />
	【文件格式】RMVB+AAC<br />
	【影片级别】USA:R<br />
	【IMDB评分】6.7/10 (28,852 votes)<br />
	【国　　家】美国<br />
	【类　　别】惊悚/剧情/科幻/悬疑/战争<br />
	【导　　演】乔纳森&middot;戴米 Jonathan Demme<br />
	【主　　演】丹泽尔&middot;华盛顿 Denzel Washington ....Ben Marco<br />
	　　　　　　杰弗里&middot;怀特 Jeffrey Wright ....Al Melvin<br />
	　　　　　　安东尼&middot;麦凯 Anthony Mackie ....Robert Baker<br />
	　　　　　　霍塞&middot;帕布罗&middot;坎蒂罗 Jose Pablo Cantillo ....Villalobos<br />
	　　　　　　梅丽尔&middot;斯特里普 Meryl Streep ....Eleanor Shaw<br />
	　　　　　　列维&middot;施瑞博尔 Liev Schreiber ....Raymond Shaw<br />
	　　　　　　强&middot;沃特 Jon Voight ....Senator Thomas Jordan<br />
	　　　　　　西蒙&middot;迈克伯尼 Simon McBurney ....Atticus Noyle<br />
	　　　　　　维拉&middot;法梅加 Vera Farmiga ....Jocelyne Jordan<br />
	　　　　　　祖德&middot;塞克利拉 Jude Ciccolella ....David Donovan<br />
	　　　　　　布鲁诺&middot;甘茨 Bruno Ganz ....Delp<br />
	　　　　　　西德尼&middot;吕美特 Sidney Lumet ....Political Pundit<br />
	　　　　　　雷吉&middot;奥斯汀 Reggie Austin ....Skid Row Resident #1 (uncredited)<br />
	<br />
	【内容简介】<br />
	<br />
	在热烈的掌声中，挂满勋章战斗英雄，前海军陆战队上校本&middot;马高(丹泽尔&middot;华盛顿 饰)登上纽约扬克威小学的讲台。他最近经常出现在各种各样的演讲和社交活动上，用熟练并且富有鼓动性地讲述自己在海湾战争的光荣经历：他的野战排如何遭到伏击，他的战友中士雷蒙德&middot;萧(利夫&middot;史列巴 饰)又是如何英勇地在关键时刻拯救了整个连队的战士。<br />
	　　但是到了晚上，马高开始面临内心复杂的心理冲突，那些神秘而凶险的回忆让无法安静入睡，让他不得安宁的不仅是战场上心灵和血肉的考验，更可怕的是，他的梦魇般的记忆碎片似乎拼凑出了一个和他从前记忆完全不同的经历。难道整个连队的战士真的被俘？难道自己真的被洗脑？难道雷蒙德&middot;萧的荣誉勋章和战争的光荣都是假的？难道他们真的都不是战斗英雄，而是被别人利用的破坏国家的定时炸弹？马高决定找到雷蒙德并且和他一起查明事情的真相。<br />
	　　事情的变化已经超出了马高的想像，雷蒙德&middot;萧已经成功地步上仕途，现为国会议员的他正在他的参议院母亲，伊丽娜(梅丽尔&middot;斯特里普 饰)的帮助下参加副总统的竞选，从民众的支持率来分析，战功卓著的他是最有希望获胜的。<br />
	　　随着调查的逐渐深入，阻力开始变得越来越大，伊丽娜为儿子安排了严密的安全小组，她不能让马高破坏即将到来的竞选成功，马高向军方说出了自己的怀疑，但却遭到了精神错乱的质疑。带着逐渐增强的疑虑，马高继续开展他的调查行动，不仅仅面临更多的压力，同时他的时间也不多了，他必须赶在雷蒙德竞选胜利之前揭露这个骇人听闻的真相&hellip;&hellip;<br />
	<br />
	◆挥之不去的梦魇，无可诋毁的真相◆<br />
	<br />
	　　美国陆军少校班尼特&middot;马可(丹泽尔&middot;华盛顿饰)总是辗转难眠。<br />
	　　十几年前的马可曾经是一名晓勇善战的悍将，科威特沙漠中命悬一线的滋味使其从军经历变得分外真实深刻。他的记忆中，似乎对因危难时刻只身拯救过自己所属作战排并因此获颁荣誉勋章的陆军军士雷蒙德&middot;萧(里夫&middot;施雷伯饰)的英雄故事还有着淡淡的痕迹。只是在夜里，马可那朦胧的记忆似乎总是不自然地回到了那片曾经硝烟惨烈的沙漠腹地，曾经军旅生涯噩梦般的回忆中绑架、谋杀、混沌不清的灵魂锁定是梦境的座上客，而雷蒙德的英雄形象似乎并没有那么高大。<br />
	　　十数年后的今天，雷蒙德&middot;萧也早已不是什么军士了。与之相关的是，他凭借着曾经显赫的军旅生涯以及家族在政坛的影响力，正一步步迈向权力的又一高峰--美国副总统的宝座。就在此时，马可那被蒙蔽的记忆也在慢慢开启。真的是战斗英雄还是险恶其中？马可提出了自己的异议，也触动了一张毫无声息的权力之网。辅佐白宫人选的正式确认之前，一切真相必须弄清，马可已经没有退路&hellip;&hellip;<br />
	<br />
	<br />
	◆演技派好莱坞的集体写真◆<br />
	<br />
	　　No.1 这里是当之无愧的丹泽尔&middot;华盛顿。五十岁的演技如日中天，最佳男配角、最佳男主角奥斯卡奖的双双收入囊中，把那些持有色眼睛审视他人的美国人噎得毫无非议可谈。他的领衔就是一种高姿态的定式。<br />
	　　No.2 故事中的女主角是雷蒙德&middot;萧的母亲，狡诈阴暗的政客埃莉诺&middot;萧。之前无人有勇气尝试这个角色，是由于曾经扮演过这个角色珍妮特&middot;李借此荣膺过奥斯卡最佳女配角奖，不过梅瑞尔&middot;斯特立普喜欢的就是这种挑战，这种向自己发起挑战的表演。<br />
	　　No.3 依靠在传记影片《RKO 281》扮演奥森&middot;威尔斯而一炮走红的里夫&middot;施雷伯有着1.88米的魁伟身形，这来自遗传。他的演技不逊于他的身高，这也来自遗传，但其中个人的努力占有绝大比重。<br />
	　　No.More 强&middot;沃特，杰弗里&middot;怀特，金伯利&middot;伊莉斯，一个个熟悉的面孔，起得却是锦上添花的作用，这就是优秀配角的魅力。<br />
	<br />
	<br />
	◆看不到的身影，看得见的艺术品味◆<br />
	<br />
	　　除去镜头前咄咄逼人的诸位影视大腕，镜头之外的各路高手也是云集在偏好刻画演技的导演乔纳森&middot;戴米周围。这其中不乏一些合作默契的伙伴：曾在《沉默的羔羊》中有过无缝配合的首席摄影藤本(Tak Fujimoto)，著名制作设计克里斯蒂&middot;齐娥，奥斯卡最佳剪辑奖提名的卡罗尔&middot;利特尔敦，以及奥斯卡作曲奖得主雷切尔&middot;波特曼等等诸公。两届奥斯卡服装设计得主阿尔波特&middot;沃尔斯基也参与了本片的制作，多达六次的合作经历使他与斯特立普存在着一种适应关系，一种能使衣着高贵与珠光宝气附着下的斯特立普更能凸现出美国政坛女士的风韵和气质。<br />
	　　为了再现主人公所亲身经历过的海湾战争，导演戴米和他的制作班底深入探究了其中拍摄的每一个细节，并邀请一些军事业内人士做专业顾问，以确保每一个场景的精确无误。不过，由于海湾局势的动荡不安，在科威特拍片确实安全得不到保证，因此剧组选择了新泽西州海洋郡撒哈拉沙漠区作为外景地之一，并在仅仅两周内就在这一地区重新调配了数吨的沙子以修建成功了剧情所需要的两条&quot;沙漠走廊&quot;。.同时，电影制作方为了表现出美国参议院真实的一面，还特以造访了参议员芭芭拉&middot;博克斯的官邸，力求精益求精。此外的纽约长岛近百年历史的维斯特伯雷庄园(Westbury Manor)、美国最大的维多利亚时代的玻璃大厅等等带有代表性特色的建筑都被制作方拉进了观众的视野当中。<br />
	　　惊悚片的定格也给了影片制作人一个完全自主的想象空间，尤其对剧中马可梦中返回科威特战场的回忆一节更是如此。制片设计克里斯蒂&middot;齐娥对这种挑战充满了渴望：&quot;突然，你占据了主人公的全部心灵空间，那里没有尺寸方圆、没有生活琐碎。正因为此，你可以尽情放飞梦想的翅膀，为所欲为。&quot;当然这种思想也要同摄影师藤本升华式的画面捕捉融会相通才能使影片的质地更上一层楼。制片人蒂娜是1962年版《满州候选人》中马可的扮演者弗兰克&middot;斯纳特拉的女儿，她对影片的定义为一部以人的灵魂挣扎为核心的作品。诚然如此，结果是要么解脱，要么就是灭亡。<br />
	◆点评◆<br />
	<br />
	　　本片是1962年约翰&middot;弗兰克海默的经典同名影片的翻拍版。剧情方面除去把战争历练地从朝鲜战场换成了第一次海湾战争的波斯湾以外，基本保持了原有的内容框架。剧情发展升华归纳了幻想怪论的超现实主义与藐视传统艺术的达达主义的特点，以复杂而严谨的映象式处理方式延续着紧张的故事脉络。把精神与意志力逼到了悬崖峭壁，这是希区科克所喜好的，也成了乔纳森&middot;戴米的伎俩之一。<br />
	　　如果说1962年版偏重了弗洛伊德式的精神分析、淡化了政治基调，那么2004年重拍版则要对海湾战争的是是非非发表一些自己的看法，最起码也是精神政治五五开。正值美国大选的多事之秋，《满州候选人》的登场多少带着倾向性的探究，但这只不过是一种无关紧要的撞车，真正值得观影者探究的是谁才是真正的演技派高手。</p>

<p>
	【电影截图】：（分辨率太大，可点击查看截图）<br />
	电影来源：www.eee4.com<br />
	<a href="http://i3.6.cn/cvbnm/12/d6/07/f81df925ddc064e43abf0f4a352891a1.jpg" target="_blank"><img border="0" src="http://i3.6.cn/cvbnm/12/d6/07/f81df925ddc064e43abf0f4a352891a1.jpg" /></a>&nbsp;<br />
	<a href="http://i3.6.cn/cvbnm/8d/52/52/3653370ae3dd7c169e6789469566e917.jpg" target="_blank"><img border="0" src="http://i3.6.cn/cvbnm/8d/52/52/3653370ae3dd7c169e6789469566e917.jpg" /></a></p>
<p>
	04丹泽尔&middot;华盛顿经典惊悚大片《谍网迷魂》DVD中英字幕1280&times;720高清版－来自[3E电影站eee4.com]：<img border="0" src="http://www.eee4.com/templets/img/down.jpg" /></p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://d80:d80@ftp.eee4.com:1501/[3E电影站www.eee4.com]谍网迷魂DVD中英字幕1280×720高清晰版.rmvb" target="_blank">ftp://d80:d80@ftp.eee4.com:1501/[3E电影站www.eee4.com]谍网迷魂DVD中英字幕1280&times;720高清晰版.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2415/飘花电影piaohua.com谍网迷魂BD中英双字1024高清.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2415/飘花电影piaohua.com谍网迷魂BD中英双字1024高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1604N60-21X3.jpg{/dede:field}
