{dede:field name='keywords'}第84届奥斯卡金像奖颁奖典礼高清{/dede:field}
{dede:field name='description'}第84届奥斯卡金像奖颁奖典礼高清1280版HD中字2012最新美国综艺迅雷下载、免费下载，第84届奥斯卡金像奖颁奖典礼高清1280版HD中字2012最新美国综艺Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}第84届奥斯卡金像奖颁奖典礼高清1280版HD中字2012最新美国综艺{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-02-29{/dede:field}
{dede:field name='body'}<p>
	<img src="http://img2081.poco.cn/mypoco/myphoto/20120228/15/56643687201202281531291442560671580_006.jpg" /></p>

<p>
	◎译　　名　第84届奥斯卡金像奖颁奖典礼<br />
	◎片　　名　The 84th Annual Academy Awards<br />
	◎年　　代　2012<br />
	◎国　　家　美国<br />
	◎类　　别　记录<br />
	◎语　　言　英语<br />
	◎字　　幕　中文<br />
	◎IMDB评分 N/A<br />
	◎IMDB链接 N/A<br />
	◎文件格式　高清1280版HD-RMVB<br />
	◎视频尺寸　1280x720<br />
	◎文件大小　1CD 2.15GB<br />
	◎片　　长　02:37:10<br />
	◎简　　介　</p>
<p>
	奥斯卡金像奖（Academy Award）即学院奖，由电影艺术与科学学院 （Academy of Motion Picture Arts and Sciences） 颁发。 1928年设立，每年一次在美国的好莱坞举行。半个多世纪来一直享有盛誉。它不仅反映美国电影艺术的发展进程而且对世界许多国家的电影艺术有着不可忽视的影响。</p>
<p>
	第84届奥斯卡金像奖颁奖典礼将于2012年2月26日（周日）在好莱坞柯达剧院举行。本次典礼直播将由ABC电视台承办，典礼之前依惯例将会有90分钟的红毯秀。</p>
<p>
	2011年12月1日（周四）：提交演职人员正式名单截止</p>
<p>
	2011年12月27日（周二）：提名选票寄出</p>
<p>
	2012年1月13日（周五）下午5点：提名选票截止</p>
<p>
	2012年1月24日（周二）下午5：30分：公布提名名单（塞缪尔&middot;高德温剧院）</p>
<p>
	2012年2月1日（周三）：最终选票寄出</p>
<p>
	2012年2月6日（周一）：提名者午餐会</p>
<p>
	2012年2月11日（周六）：奥斯卡科学技术奖颁奖典礼</p>
<p>
	2012年2月21日（周二）下午5点：最终选票截止</p>
<p>
	2012年2月26日（周日）：第84届奥斯卡颁奖典礼</p>

<p>
	第84届奥斯卡金像奖完全获奖名单</p>
<p>
	<br />
	最佳影片 《艺术家》（The Artist）<br />
	最佳导演 米歇尔&middot;哈扎纳维希乌斯《艺术家》<br />
	最佳男主角 让&middot;杜雅尔丹《艺术家》（Jean Dujardin, The Artist）<br />
	最佳女主角 梅丽尔&middot;斯特里普《铁娘子》（Meryl Streep, The Iron Lady）<br />
	最佳男配角 克里斯托弗&middot;普卢默《初学者》（Christopher Plummer, Beginners）<br />
	最佳女配角 奥克塔维亚&middot;斯宾瑟《帮助》（Octavia Spencer, The Help）<br />
	最佳动画长片 《兰戈》（Rango）<br />
	最佳外语片 《纳德和西敏：一次别离》（A Separation），伊朗<br />
	最佳化妆 《铁娘子》（The Iron Lady）<br />
	最佳配乐 《艺术家》（The Artist）<br />
	最佳歌曲 《Manor Muppet》，《布偶大电影》（The Muppets）<br />
	最佳动画短片 《莫里斯&middot;莱斯莫的神奇飞书》（The Fantastic Flying Books of Mr. Morris Lessmore）<br />
	最佳真人短片 《海岸》（The Shore）<br />
	最佳音效剪辑 《雨果》（Hugo）<br />
	最佳音响效果 《雨果》（Hugo）<br />
	最佳视觉效果 《雨果》（Hugo）<br />
	最佳改编剧本 《后人》（The Descendants）<br />
	最佳原创剧本 《午夜巴黎》（Midnight in Paris）<br />
	最佳美术指导 《雨果》（Hugo）<br />
	最佳摄影 《雨果》（Hugo）<br />
	最佳服装设计 《艺术家》（The Artist）<br />
	最佳剪辑 《龙纹身的女孩》（The Girl with the Dragon Tattoo）<br />
	最佳纪录长片 《不败》（Undefeated）<br />
	最佳纪录短片 《面子》（Saving Face）<br />
	终身成就奖 詹姆斯&middot;厄尔&middot;琼斯</p>

<p>
	<img src="http://img04.taobaocdn.com/imgextra/i4/229823360/T2HqSqXmFXXXXXXXXX_!!229823360.jpg" style="width: 600px; height: 338px" /></p>
<p>
	<img src="http://img03.taobaocdn.com/imgextra/i3/229823360/T2iWKqXX4aXXXXXXXX_!!229823360.jpg" style="width: 600px; height: 338px" /></p>

<p>
	<img src="http://img01.taobaocdn.com/imgextra/i1/229823360/T2KGOqXn0XXXXXXXXX_!!229823360.jpg" style="width: 600px; height: 338px" /></p>

<p>
	<img src="http://img01.taobaocdn.com/imgextra/i1/229823360/T2Vq5qXipXXXXXXXXX_!!229823360.jpg" style="width: 600px; height: 338px" /></p>

<p>
	<img src="http://img01.taobaocdn.com/imgextra/i1/229823360/T28GWqXkBXXXXXXXXX_!!229823360.jpg" style="width: 600px; height: 338px" /></p>
<p>
	[下载地址]： &nbsp;<img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2915/飘花电影piaohua.com第84届奥斯卡金像奖颁奖典礼高清1280版HD中字.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:2915/飘花电影piaohua.com第84届奥斯卡金像奖颁奖典礼高清1280版HD中字.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2915/飘花电影piaohua.com第84届奥斯卡金像奖颁奖典礼高清1280版HD中字.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1CcP-44950.jpg{/dede:field}
