{dede:field name='keywords'}蝴蝶Nabi迅雷下载，免费下载，Gv{/dede:field}
{dede:field name='description'}蝴蝶Nabi迅雷下载、免费下载，蝴蝶NabiGvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}蝴蝶Nabi{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2007-07-07{/dede:field}
{dede:field name='body'}<p>韩国经典科幻片《蝴蝶Nabi》DVD中字<br />导 演： 文胜旭<br />上 映： 韩国 2001年10月13日<br />地 区： 韩国<br />对 白： 朝鲜语<br />时 长： 110分钟<br />类 型： 科幻 文艺<br />分 级： 韩国：15<br />字 幕： 中英字幕</p>
<p>剧情简介：<br />在不久的将来，地球不断受到污染，造成大量酸雨，并引起了严重的水浸。城市内的旧屋抵受不了酸雨的侵蚀，而郊区则建满新的居所。那时，韩国更出现了一种特别的病毒，这种病毒可以令感染者忘记了大部份他们最痛苦的回忆。要捕捉这种病毒其实极为困难，大家祗好靠著一群白蝴蝶引路。然而，这种病毒出现后竟然振兴了韩国的旅游业，不少外国人都慕名而来寻找病毒。那时那地，有三个人走在一起。韩裔德国人Anna来到韩国，目的就是找寻病毒，令自己忘记过去心碎的经历。於孤儿院长大的年青的士司机Ｋ想尽一切办法，目的是要寻回自己的亲生父母和知道自己的过去。Yuki是一名十分可爱的怀孕少女。大家正惧怕她怀著未来恶梦的魔种。<br />本片获得：<br />2001年 <br />瑞士洛迦诺国际电影节最佳女演员 瑞士洛迦诺国际电影节最佳导演提名<br />2001年 Youth Jury Award: Environment is Quality of Life<img height="1" alt="" width="1" border="0" src="http://pic.piaohua.com/0701pic/allimg/20070501/BM018.jpg" /></p>
<p>&nbsp;<img alt="" onload="myHint.move(0, true);" border="0" src="http://pic.piaohua.com/0701pic/allimg/070707/0233530.jpg" /><br /><img alt="" onload="myHint.move(0, true);" border="0" src="http://pic.piaohua.com/0701pic/allimg/070707/0233531.jpg" /><br /><img alt="" onload="myHint.move(0, true);" border="0" src="http://pic.piaohua.com/0701pic/allimg/070707/0233532.jpg" /><br /></p>
<p><img alt="" onload="myHint.move(0, true);" border="0" src="http://pic.piaohua.com/0701pic/allimg/070707/0233533.jpg" /><br /></p>
<p>2007-07-07 11:12:11 开始连接......<br />2007-07-07 11:12:12 开始搜索候选资源......<br />2007-07-07 11:12:14 搜索到21个候选资源<br />2007-07-07 11:12:15 使用候选资源进行连接......<br />2007-07-07 11:12:20 搜索到14个候选资源<br />2007-07-07 11:12:21 使用候选资源进行连接......<br />2007-07-07 11:12:21 开始创建文件......<br />2007-07-07 11:12:23 文件创建成功，开始下载数据......<br />2007-07-07 11:12:26 用户取消下载&nbsp;&nbsp; 本文来自 www.eee4.com</p>
下载地址：<br />
<table style="BORDER-RIGHT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; BORDER-BOTTOM: #cccccc 1px dotted" cellspacing="0" cellpadding="6" width="95%" align="center" border="0">
    <tbody>
        <tr>
            <td style="WORD-WRAP: break-word" bgcolor="#fdfddf"><anchor></anchor>ftp://dygod1:dygod1@data5.dygod.net:9905/蝴蝶Nabi/蝴蝶Nabi[www.dygod.com电影天堂].rmvb</td>
        </tr>
    </tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O16105910-54618.jpg{/dede:field}
