<?php
$z[0]=Array("field","兄弟[DVD中英双字]迅雷下载，免",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","兄弟[DVD中英双字]迅雷下载、免费下载，兄弟[DVD中英双字]Gvod高清在线播放，剧情介绍等。",72,200);
$z[1][4]['name']="description";
$z[2]=Array("field","兄弟[DVD中英双字]",202,257);
$z[2][4]['name']="title";
$z[3]=Array("field","",259,298);
$z[3][4]['name']="writer";
$z[4]=Array("field","",300,339);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-03-14",341,391);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",393,430);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://3e:3e@www2.3edyy.com:362/【3E电影院www.3edyy.com】兄弟DVD中字.rmvb\" target=_blank>ftftp://3e:3e@www2.3edyy.com:362/【3E电影院www.3edyy.com】兄弟DVD中字.rmvb</A></TD></TR></TBODY></TABLE><BR><FONT color=#ff0000 size=2><STRONG>09年美国最新高分惊悚战争剧情大片《兄弟》DVD中英双字 [<FONT color=#0938f7 size=4>2010/03/14</FONT> 下载地址]：<IMG src=\"httftp://www.3edyy.com/templets/img/down.jpg\" border=0></STRONG></FONT><BR>\r\n<TABLE style=\"BORDER-RIGHT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; BORDER-BOTTOM: #cccccc 1px dotted\" cellSpacing=0 cellPadding=6 width=\"95%\" align=center border=0>\r\n<TBODY>\r\n<TR>\r\n<TD style=\"WORD-WRAP: break-word\" bgColor=#fdfddf><A href=\"ftftp://3e:3e@www2.3edyy.com:3985/【3E电影院www.eee4.cc】兄弟DVD中英双字.rmvb\" target=_blank>ftftp://3e:3e@www2.3edyy.com:3985/【3E电影院www.eee4.cc】兄弟DVD中英双字.rmvb</A></TD></TR></TBODY></TABLE></div><ul class=\"mmlist",432,1428);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MP603150-31Z3.jpg",1430,1513);
$z[8][4]['name']="litpic";

?>