{dede:field name='keywords'}兄弟[DVD中英双字]迅雷下载，免{/dede:field}
{dede:field name='description'}兄弟[DVD中英双字]迅雷下载、免费下载，兄弟[DVD中英双字]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}兄弟[DVD中英双字]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2010-03-14{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://3e:3e@www2.3edyy.com:362/【3E电影院www.3edyy.com】兄弟DVD中字.rmvb" target=_blank>ftftp://3e:3e@www2.3edyy.com:362/【3E电影院www.3edyy.com】兄弟DVD中字.rmvb</A></TD></TR></TBODY></TABLE><BR><FONT color=#ff0000 size=2><STRONG>09年美国最新高分惊悚战争剧情大片《兄弟》DVD中英双字 [<FONT color=#0938f7 size=4>2010/03/14</FONT> 下载地址]：<IMG src="httftp://www.3edyy.com/templets/img/down.jpg" border=0></STRONG></FONT><BR>
<TABLE style="BORDER-RIGHT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; BORDER-BOTTOM: #cccccc 1px dotted" cellSpacing=0 cellPadding=6 width="95%" align=center border=0>
<TBODY>
<TR>
<TD style="WORD-WRAP: break-word" bgColor=#fdfddf><A href="ftftp://3e:3e@www2.3edyy.com:3985/【3E电影院www.eee4.cc】兄弟DVD中英双字.rmvb" target=_blank>ftftp://3e:3e@www2.3edyy.com:3985/【3E电影院www.eee4.cc】兄弟DVD中英双字.rmvb</A></TD></TR></TBODY></TABLE></div><ul class="mmlist{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MP603150-31Z3.jpg{/dede:field}
