{dede:field name='keywords'}孙子从美国来HD1280高清迅雷下载{/dede:field}
{dede:field name='description'}孙子从美国来HD1280高清迅雷下载、免费下载，孙子从美国来HD1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}孙子从美国来HD1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-23{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://i1164.photobucket.com/albums/q571/victor198536/09fa513d269759eeaa2bc97db2fb43166d22df09.jpg" style="width: 431px; height: 276px" /></p>
<p>
	【片　　名】孙子从美国来<br />
	【英文译名】A Grandson From America<br />
	【年　　代】2012<br />
	【类　　型】剧情<br />
	【国家地区】中国<br />
	【语　　言】汉语普通话<br />
	【上映日期】2012年2月4日<br />
	【出品公司】国家广播电影电视总局电影卫星频道节目制作中心<br />
	【片　　长】88 min<br />
	【导　　演】曲江涛<br />
	【编　　剧】曲江涛<br />
	【主　　演】罗京民/刘天佐<br />
	　　　　　　<br />
	【剧情介绍】<br />
	<br />
	主人公华县皮影戏老艺人&mdash;&mdash;老杨头，崇拜中国传统文化中的孙悟空人物；另一主人公是美国的小男孩&mdash;&mdash;布鲁克斯，则崇拜西洋文化中的蜘蛛侠。其中一条主线是，布鲁克斯父母当作为志愿者赴西藏可可西里参加藏羚羊保护行动时，委托老杨头照顾小洋人布鲁克斯，期间老杨头和布鲁克斯在生活习惯、语言形式、行为思维以及文化观念等方面的相互排斥、对立，经过曲折的碰撞和相互之间的包容、接纳以及关爱；另一条主线是，镇文化站站长请缨老杨头出阵，以师带徒传承保护华县皮影戏，因老杨头曾在&ldquo;文革&rdquo;中受过冲击，回避担当此任，经过站长的苦口婆心努力和生动的典型说教，老杨头最终接受了任务，办起了皮影戏和皮影雕刻艺术短训班</p>
<p>
	<img alt="" src="http://i1164.photobucket.com/albums/q571/victor198536/CHCAGrandsonFromAmerica2012HDTV720pH264-CHDTV.jpg" style="width: 650px; height: 770px" /><br />
	<br />
	&nbsp;</p>
<p>
	【下载地址】</p>
<table bgcolor="#0099cc" border="0" cellpadding="10" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaobajie.com" target="_blank">http://www.xiaobajie.com</a></td>
		</tr>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy125:piaohua@dy125.piaohua.com:8088/飘花电影piaohua.com孙子从美国来HD国语中字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:8088/飘花电影piaohua.com孙子从美国来HD国语中字1280高清.rmvb</a></td>
		</tr>
		<tr>
		</tr>
	</tbody>
</table>
<br />{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O16015W0-3Y12.jpg{/dede:field}
