{dede:field name='keywords'}原样复制/合法副本[DVD中字]迅雷{/dede:field}
{dede:field name='description'}原样复制/合法副本[DVD中字]迅雷下载、免费下载，原样复制/合法副本[DVD中字]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}原样复制/合法副本[DVD中字]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-01-11{/dede:field}
{dede:field name='body'}<P><IMG src="/uploads/allimg/c120525/133O093611F-305Z6.jpg"><BR><BR><BR>◎译　　名　《原样复制/合法副本》2010年欧美最新高分文艺剧情片DVD中字<BR>◎片　　名　Copie Conforme<BR>◎年　　代　2010<BR>◎国　　家　法国/意大利/伊朗<BR>◎类　　别　文艺/剧情<BR>◎语　　言　法语/意大利语<BR>◎字　　幕　中文<BR>◎IMDB评分 7.3/10<BR>◎IMDB链接 http://www.imdb.com/title/tt1020773/<BR>◎文件格式　DVD-RMVB<BR>◎视频尺寸　688 x 368<BR>◎文件大小　1CD 407MB<BR>◎片　　长　102 分钟<BR>◎导　　演　Abbas Kiarostami<BR>◎主　　演　William Shimell<BR>　　　　　　Juliette Binoche<BR>　　　　　　Agathe Natanson<BR>　　　　　　Gianna Giachetti</P>
<P>◎简　　介　</P>
<P>　　伊朗电影大师阿巴斯新作。这是一部实验性极强的艺术电影，我们只可以听到这个故事中的对白和声响，却没有任何这个故事的画面出现，女演员的头发被稀薄的丝纱掩盖着，观看着眼前的影片。她们为眼前片中女主人公的命运和爱情所牵挂。但这并非一部纪录片，而女演员们也不是真的在看电影，她们只是盯着一片黑幕，倾听着古诗。基亚罗斯塔米在他的起居室里拍摄了整部电影，只用三把椅子作为全部布景。她们用手势、表情、皱眉和眼神，来表露她们发现被人观察的尴尬情绪的程度。<BR></P>
<P>【电影截图】：<BR><BR></P><IMG src="/uploads/allimg/c120525/133O09361920-3194Y.jpg">&nbsp;<BR><IMG src="/uploads/allimg/c120525/133O09362140-324a8.jpg">&nbsp;<BR><IMG src="/uploads/allimg/c120525/133O093623F-335525.jpg">&nbsp;<BR><IMG src="/uploads/allimg/c120525/133O093625Z-34V94.jpg">&nbsp;<BR><IMG src="/uploads/allimg/c120525/133O09363110-354O8.jpg"><BR><BR><BR><BR><BR><BR>【dbank网盘高速下载地址】:<BR>2010年欧美最新高分文艺剧情片《原样复制/合法副本》DVD中字<BR><BR>【115网盘高速下载地址】:<BR>2010年欧美最新高分文艺剧情片《原样复制/合法副本》DVD中字<BR><BR>2010年欧美最新高分文艺剧情片《原样复制/合法副本》DVD中字 [下载地址]：<IMG border=0 src="/uploads/allimg/c120525/133O0T31310-42214.jpg"><BR>
<TABLE style="BORDER-BOTTOM: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-RIGHT: #cccccc 1px dotted" border=0 cellSpacing=0 cellPadding=6 width="95%" align=center>
<TBODY>
<TR>
<TD style="WORD-WRAP: break-word" bgColor=#fdfddf>ftp://6e:6e@d6.3edyy.com:612/【3E看看www.3ekk.com】原样复制[DVD中字].rmvb</TD></TR></TBODY></TABLE>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O09363630-3A515.jpg{/dede:field}
