{dede:field name='keywords'}粉爱粉爱你第16集2012偶像剧迅雷{/dede:field}
{dede:field name='description'}粉爱粉爱你第16集2012偶像剧迅雷下载、免费下载，粉爱粉爱你第16集2012偶像剧Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}粉爱粉爱你第16集2012偶像剧{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-14{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img.album.pchome.net/02/25/03/37/8f5a9d5cfa746f6dc712e2de0f915a53.jpg" /></p>
<p>
	地区：台湾<br />
	导演：刘俊杰<br />
	演员：蓝正龙 / 周汤豪 / 邱翊橙 / 白梓轩 /<br />
	首播时间：2012年<br />
	电视台：华视<br />
	简介：《粉爱粉爱你》为台湾偶像剧，于2011年11月开拍。该剧由蓝正龙主演，刘俊杰执导。蓝正龙在新戏中将首度扮演彩妆师，片中他将开口演唱两首插曲，未来集结出原声带。 蓝正龙是台湾当红男艺人，因演出可口可乐广告，及在偶像剧《流星花园》中客串道明寺的表哥而被大众所知。随后与大S徐熙媛传出绯闻，二人交往至2005年分手。沉默不多话、内敛不张扬、真诚而坦荡是他的个性。看似冷酷的外表背后实则隐藏着一颗温暖、细腻的心。</p>
<p>
	[下载地址]：&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2717/飘花电影piaohua.com粉爱粉爱你01.rmvb ">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:2717/飘花电影piaohua.com粉爱粉爱你01.rmvb ">ftp://dy44:piaohua@dy44.piaohua.com:2717/飘花电影piaohua.com粉爱粉爱你01.rmvb </a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2761/飘花电影piaohua.com粉爱粉爱你02.rmvb ">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:2761/飘花电影piaohua.com粉爱粉爱你02.rmvb ">ftp://dy44:piaohua@dy44.piaohua.com:2761/飘花电影piaohua.com粉爱粉爱你02.rmvb </a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2808/飘花电影piaohua.com粉爱粉爱你03.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:2808/飘花电影piaohua.com粉爱粉爱你03.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2808/飘花电影piaohua.com粉爱粉爱你03.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2850/飘花电影piaohua.com粉爱粉爱你04.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:2850/飘花电影piaohua.com粉爱粉爱你04.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2850/飘花电影piaohua.com粉爱粉爱你04.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2898/飘花电影piaohua.com粉爱粉爱你05.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:2898/飘花电影piaohua.com粉爱粉爱你05.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2898/飘花电影piaohua.com粉爱粉爱你05.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2952/飘花电影piaohua.com粉爱粉爱你06.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:2952/飘花电影piaohua.com粉爱粉爱你06.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2952/飘花电影piaohua.com粉爱粉爱你06.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2996/飘花电影piaohua.com粉爱粉爱你07.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:2996/飘花电影piaohua.com粉爱粉爱你07.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2996/飘花电影piaohua.com粉爱粉爱你07.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3041/飘花电影piaohua.com粉爱粉爱你08.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3041/飘花电影piaohua.com粉爱粉爱你08.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3041/飘花电影piaohua.com粉爱粉爱你08.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3072/飘花电影piaohua.com粉爱粉爱你09.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3072/飘花电影piaohua.com粉爱粉爱你09.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3072/飘花电影piaohua.com粉爱粉爱你09.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3127/飘花电影piaohua.com粉爱粉爱你10.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3127/飘花电影piaohua.com粉爱粉爱你10.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3127/飘花电影piaohua.com粉爱粉爱你10.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3185/飘花电影piaohua.com粉爱粉爱你11.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3185/飘花电影piaohua.com粉爱粉爱你11.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3185/飘花电影piaohua.com粉爱粉爱你11.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3231/飘花电影piaohua.com粉爱粉爱你12.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3231/飘花电影piaohua.com粉爱粉爱你12.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3231/飘花电影piaohua.com粉爱粉爱你12.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3272/飘花电影piaohua.com粉爱粉爱你13.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3272/飘花电影piaohua.com粉爱粉爱你13.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3272/飘花电影piaohua.com粉爱粉爱你13.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3321/飘花电影piaohua.com粉爱粉爱你14.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3321/飘花电影piaohua.com粉爱粉爱你14.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3321/飘花电影piaohua.com粉爱粉爱你14.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3364/飘花电影piaohua.com粉爱粉爱你15.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3364/飘花电影piaohua.com粉爱粉爱你15.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3364/飘花电影piaohua.com粉爱粉爱你15.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3412/飘花电影piaohua.com粉爱粉爱你16.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3412/飘花电影piaohua.com粉爱粉爱你16.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3412/飘花电影piaohua.com粉爱粉爱你16.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1A3T30-23955.jpg{/dede:field}
