{dede:field name='keywords'}反恐疑云BD中英双字1024/1280高{/dede:field}
{dede:field name='description'}反恐疑云BD中英双字1024/1280高清迅雷下载、免费下载，反恐疑云BD中英双字1024/1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}反恐疑云BD中英双字1024/1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-01-30{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://eee4.com:eee4@xl3.eee4.com:8448/反恐疑云DVD完美中字/[3E迅雷电影站www.eee4.com]反恐疑云CD1.rmvb" target="_blank{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MP2W110-32049.jpg{/dede:field}
