<?php
$z[0]=Array("field","地球末日/地动山摇/美国大地震/",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","地球末日/地动山摇/美国大地震/山崩地裂2[DVD中字]迅雷下载、免费下载，地球末日/地动山摇/美国大地震/山崩地裂2[DVD中字]Gvod高清在线播放，剧情介绍等。",72,260);
$z[1][4]['name']="description";
$z[2]=Array("field","地球末日/地动山摇/美国大地震/山崩地裂2[DVD中字]",262,347);
$z[2][4]['name']="title";
$z[3]=Array("field","",349,388);
$z[3][4]['name']="writer";
$z[4]=Array("field","",390,429);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-06-18",431,481);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",483,520);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://3e:3e@m1.3edyy.com:1498/【3E电影院www.eee4.cc】地球末日DVD中字.rmvb\" target=_blank>ftftp://3e:3e@m1.3edyy.com:1498/【3E电影院www.eee4.cc】地球末日DVD中字.rmvb</A></TD></TR></TBODY></TABLE></div><ul class=\"mmlist",522,778);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MPY1460-2JS.jpg",780,861);
$z[8][4]['name']="litpic";

?>