<?php
$z[0]=Array("field","60号高地之下[DVD中英双字]迅雷",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","60号高地之下[DVD中英双字]迅雷下载、免费下载，60号高地之下[DVD中英双字]Gvod高清在线播放，剧情介绍等。",72,216);
$z[1][4]['name']="description";
$z[2]=Array("field","60号高地之下[DVD中英双字]",218,281);
$z[2][4]['name']="title";
$z[3]=Array("field","",283,322);
$z[3][4]['name']="writer";
$z[4]=Array("field","",324,363);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-09-04",365,415);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",417,454);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://4e:4e@m1.eee4.cc:1526/【3e电影网www.eee4.cc】60号高地之下DVD中英双字.rmvb\" target=_blank>ftftp://4e:4e@m1.eee4.cc:1526/【3e电影网www.eee4.cc】60号高地之下DVD中英双字.rmvb</A></TD></TR></TBODY></TABLE></div><ul class=\"mmlist",456,724);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MP639640-1BJ.jpg",726,808);
$z[8][4]['name']="litpic";

?>