<?php
$z[0]=Array("field","狂犬惊魂/疯噬/厄兆/凶狗古卓[BD",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","狂犬惊魂/疯噬/厄兆/凶狗古卓[BD中英双字1280x720高清版]迅雷下载、免费下载，狂犬惊魂/疯噬/厄兆/凶狗古卓[BD中英双字1280x720高清版]Gvod高清在线播放，剧情介绍等。",73,273);
$z[1][4]['name']="description";
$z[2]=Array("field","狂犬惊魂/疯噬/厄兆/凶狗古卓[BD中英双字1280x720高清版]",275,366);
$z[2][4]['name']="title";
$z[3]=Array("field","",368,407);
$z[3][4]['name']="writer";
$z[4]=Array("field","",409,448);
$z[4][4]['name']="source";
$z[5]=Array("field","2009-11-26",450,500);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",502,539);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://3e:3e@xl.eee4.com:348/[3E电影站www.eee4.cn]狂犬惊魂BD中英双字1280x720高清版.rmvb\" target=\"_blank",541,682);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MQ32050-4SV.jpg",684,765);
$z[8][4]['name']="litpic";

?>