{dede:field name='keywords'}骆驼蜘蛛高清迅雷下载，免费下载{/dede:field}
{dede:field name='description'}骆驼蜘蛛高清迅雷下载、免费下载，骆驼蜘蛛高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}骆驼蜘蛛高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-03-23{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://i.imgur.com/wwXol.jpg" style="width: 650px; height: 834px" /></p>
<p>
	◎译　　名　骆驼蜘蛛<br />
	◎片　　名　Camel Spiders &nbsp;<br />
	◎年　　代　2012<br />
	◎国　　家　美国<br />
	◎类　　别　科幻/惊悚<br />
	◎语　　言　英语<br />
	◎字　　幕　中字<br />
	◎IMDB评分 &nbsp;2.5/10 from 182 users<br />
	◎IMDB链接 <a href="http://www.6dtaobao.com/">http://www.6dtaobao.com</a><br />
	◎文件格式　X264 + AC3<br />
	◎视频尺寸　1280 x 720<br />
	◎文件大小　1CD 69 x 50 MB<br />
	◎片　　长　84 Mins<br />
	◎导　　演　吉姆&middot;温诺斯基 Jim Wynorski<br />
	◎主　　演　C&middot;托马斯&middot;豪威尔 C. Thomas Howell &nbsp;&hellip;.Sheriff Beaumont<br />
	　　　　　　Brian Krause &nbsp;&hellip;.Sturges<br />
	　　　　　　Frankie Cullen &nbsp;&hellip;.Schwalb<br />
	　　　　　　Melissa Brasselle &nbsp;&hellip;.Shelly Underwood<br />
	　　　　　　GiGi Erneta &nbsp;&hellip;.Reba<br />
	　　　　　　Matt Borlenghi &nbsp;&hellip;.Brad<br />
	　　　　　　Diana Terranova &nbsp;&hellip;.Patty<br />
	　　　　　　Paula LaBaredas &nbsp;&hellip;.Wendy<br />
	　　　　　　Steve Snyder &nbsp;&hellip;.Trent<br />
	　　　　　　Michael Swan &nbsp;&hellip;.McNeil<br />
	<br />
	<br />
	◎简　　介　<br />
	<br />
	&nbsp; &nbsp; 　　根据真实生物拍摄而成。叙述这种俗称&ldquo;骆驼蜘蛛&rdquo;的巨蛛，多年来折磨驻扎在中东的美军。如今他们大举入侵美国西南方的沙漠，只要被叮上一口就会瘫痪。究竟是否有天敌可以制服这群邪恶蜘蛛吗？</p>
<p>
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120319/08/62564813201203190837354017696526438_003.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120319/08/62564813201203190837354017696526438_002.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120319/08/62564813201203190837354017696526438_001.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120319/08/62564813201203190837354017696526438_000.jpg" style="width: 720px; height: 405px" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="
ftp://dy125:piaohua@dy125.piaohua.com:7745/飘花电影piaohua.com骆驼蜘蛛BD中字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:7745/飘花电影piaohua.com骆驼蜘蛛BD中字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15932930-14A8.jpg{/dede:field}
