{dede:field name='keywords'}情场战场/沉静的美国人BD高清102{/dede:field}
{dede:field name='description'}情场战场/沉静的美国人BD高清1024*576迅雷下载、免费下载，情场战场/沉静的美国人BD高清1024*576Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}情场战场/沉静的美国人BD高清1024*576{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-09-20{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img165.poco.cn/mypoco/myphoto/20110919/11/62564813201109191105037360545462990_000.jpg" style="width: 720px; height: 901px" /></p>
<p>
	◎译　　名　沉静的美国人/情场战场<br />
	◎片　　名　The Quiet American<br />
	◎年　　代　2002<br />
	◎国　　家　德国/美国/英国/澳大利亚/法国<br />
	◎类　　别　剧情/神秘/爱情/惊悚/战争<br />
	◎语　　言　英语/法语/越南语<br />
	◎字　　幕　中英<br />
	◎IMDB评分 7.2/10 (15,591 users)<br />
	◎IMDB链接 <a href="http://www.imdb.com/title/tt0258068/">http://www.imdb.com/title/tt0258068/</a><br />
	◎片　　长　01:40:55<br />
	◎导　　演　菲利普&middot;诺伊斯 Phillip Noyce<br />
	◎主　　演　迈克尔&middot;凯恩 Michael Caine ....Thomas Fowler<br />
	　　　　　　布兰登&middot;费舍 Brendan Fraser ....Alden Pyle<br />
	　　　　　　杜海严 Do Thi Hai Yen ....Phuong<br />
	　　　　　　拉德&middot;舍博德兹加 Rade Serbedzija ....Inspector Vigot<br />
	　　　　　　马志 Tzi Ma ....Hinh<br />
	　　　　　　Robert Stanton ....Joe Tunney<br />
	　　　　　　Quang Hai ....General Th&eacute;<br />
	　　　　　　Ferdinand Hoang ....Mr. Muoi<br />
	　　　　　　Pham Thi Mai Hoa ....Phuong&#39;s Sister<br />
	　　　　　　Mathias Mlekuz ....French Captain<br />
	　　　　　　Kevin Tran ....Watch Tower Soldier<br />
	　　　　　　Lap Phan ....Watch Tower Soldier<br />
	　　　　　　Tim Bennett ....American Photographer<br />
	　　　　　　Jeff Truman ....Dancing American<br />
	　　　　　　Hong Nhung ....House Of 500 Girls&#39; Singer<br />
	　　　　　　Ha Phong Nguyen ....Muoi&#39;s Henchman<br />
	　　　　　　Navia Nguyen ....House Of 500 Girls&#39; Woman<br />
	　　　　　　Lucia Noyce ....American Woman<br />
	　　　　　　Hiliary Douglas ....American Woman<br />
	　　　　　　Daniel Hung ....Assassin<br />
	　　　　　　Kim Hoan Nguyen ....Assassin<br />
	　　　　　　Mai Nguyen Trinh ....Assassin<br />
	　　　　　　Pham Trong ....Assassin<br />
	　　　　　　Tran Do Luc ....Vietnamese Policeman<br />
	　　　　　　Cong Ly Nguyen ....Vietnamese Guard<br />
	　　　　　　George Mangos ....French Soldier<br />
	　　　　　　Natasha Hunter ....French Singer<br />
	　　　　　　Martine Monroe ....French Singer<br />
	　　　　　　Jos&eacute; De la Vega ....Hotel Continental Maitre d&#39;<br />
	　　　　　　Roland Rohrer ....Vieux Moulin Maitre d&#39;<br />
	　　　　　　Susan Parry ....French Woman<br />
	　　　　　　Anh Dung Nguyen ....Mechanic In Muoi&#39;s Garage<br />
	　　　　　　Peter Holdsworth ....Pyle&#39;s Bodyguard<br />
	　　　　　　Ngoc Tuan Hoang ....L&#39;arc en Ciel Band<br />
	　　　　　　Trece Lambatan ....L&#39;arc en Ciel Band<br />
	　　　　　　Erwin Abarico ....L&#39;arc en Ciel Band<br />
	　　　　　　Jun Javier ....L&#39;arc en Ciel Band<br />
	　　　　　　Van Phuoc Nguyen ....L&#39;arc en Ciel Band<br />
	　　　　　　Mark Szeto ....L&#39;arc en Ciel Band<br />
	　　　　　　Askar Nurlanov ....L&#39;arc en Ciel Band<br />
	　　　　　　Douglas Gallagher ....L&#39;arc en Ciel Band<br />
	　　　　　　Nicholas Parry ....L&#39;arc en Ciel Band<br />
	　　　　　　Vov Dylan ....L&#39;arc en Ciel Band<br />
	　　　　　　Khoa Do ....Vietnamese Policeman (uncredited)<br />
	　　　　　　Holmes Osborne ....Bill Granger</p>
<p>
	<br />
	◎简　　介</p>
<p>
	剧情</p>
<p>
	　　1952年，英国的老记者托马斯享受着他在西贡悠闲的生活与美丽温柔的情妇、越南女人红。这个顺从的女人虽然明知他在英国已有家室，却别无所求。<br />
	　　一位英俊的美国青年艾登怀着理想主义的激情来到西贡，希望参加医疗援助，他的热情打动了托马斯。一直以来，托马斯都小心翼翼地保持着中立态度，仅仅不动声色地观察着，尽到自己新闻报道者的本分。很快他就发现艾登迷上了红，而伦敦的报社总部命令他停止在越南的活动回国。<br />
	　　托马斯决定去挖掘一桩大新闻，深入战争地带报道一起大屠杀，以使自己能够继续留在越南。艾登追随他潜入战场，并向他坦承对红的爱，表示将向她求婚。出人意料的是，红竟然拒绝了艾登的求婚。另一方面，托马斯逐渐发现艾登似乎并不像他看上去的那般单纯&hellip;&hellip;</p>
<p>
	一句话评论</p>
<p>
	In war, the most powerful weapon is seduction.</p>
<p>
	幕后制作</p>
<p>
	影片改编自Graham Greene的经典小说。本片的导演菲利浦&middot;诺伊斯早在1970年的学生时代，就阅读过原著。他自己怎样也没想到在20年后，他会将葛拉罕格林这部引人入胜的惊悚小说改编成电影。诺伊斯在1995年因为机缘巧合重读了《沉静的美国人》。这次重读令导演对于这个充满政治秘密、谋杀与罗曼史的复杂故事，有了不同的体认。&ldquo;我花时间与这些美国退伍军人相处，他们心中对于自己在越南所经历的转变，充满了悔恨，&rdquo;诺斯说道，&ldquo;他们当时在越南训练越南人对抗日本人，可是最后却是等于训练他们对抗美国人自己。&rdquo;如此种种，才有了我们今天所看到的《沉静的美国人》。</p>
<p>
	&nbsp;<img alt="" src="http://img165.poco.cn/mypoco/myphoto/20110919/14/62564813201109191415362819252614349_001.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img165.poco.cn/mypoco/myphoto/20110919/14/62564813201109191415362819252614349_000.jpg" style="width: 720px; height: 405px" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="&#13;&#10;ftp://dy125:piaohua@dy125.piaohua.com:4046/飘花电影piaohua.com情场战场BD中英双字1024高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:4046/飘花电影piaohua.com情场战场BD中英双字1024高清.rmvb </a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1602C10-22507.jpg{/dede:field}
