{dede:field name='keywords'}诸神之战/世纪对神榜/诸神恩仇录{/dede:field}
{dede:field name='description'}诸神之战/世纪对神榜/诸神恩仇录/魔岛屠龙/四巨头[BD中英双字1280x720高清版]迅雷下载、免费下载，诸神之战/世纪对神榜/诸神恩仇录/魔岛屠龙/四巨头[BD中英双字1280x720高清版]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}诸神之战/世纪对神榜/诸神恩仇录/魔岛屠龙/四巨头[BD中英双字1280x720高清版]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2010-03-06{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://4e:4e@m1.3edyy.com:1393/【3E电影院www.3edyy.com】诸神之战BD中英双字1280x720高清版.rmvb" target="_blank{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MQ33CZ-293T.jpg{/dede:field}
