<?php
$z[0]=Array("field","诸神之战/世纪对神榜/诸神恩仇录",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","诸神之战/世纪对神榜/诸神恩仇录/魔岛屠龙/四巨头[BD中英双字1280x720高清版]迅雷下载、免费下载，诸神之战/世纪对神榜/诸神恩仇录/魔岛屠龙/四巨头[BD中英双字1280x720高清版]Gvod高清在线播放，剧情介绍等。",73,311);
$z[1][4]['name']="description";
$z[2]=Array("field","诸神之战/世纪对神榜/诸神恩仇录/魔岛屠龙/四巨头[BD中英双字1280x720高清版]",313,423);
$z[2][4]['name']="title";
$z[3]=Array("field","",425,464);
$z[3][4]['name']="writer";
$z[4]=Array("field","",466,505);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-03-06",507,557);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",559,596);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://4e:4e@m1.3edyy.com:1393/【3E电影院www.3edyy.com】诸神之战BD中英双字1280x720高清版.rmvb\" target=\"_blank",598,745);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MQ33CZ-293T.jpg",747,828);
$z[8][4]['name']="litpic";

?>