{dede:field name='keywords'}背离BD中字1280高清2012最新英国{/dede:field}
{dede:field name='description'}背离BD中字1280高清2012最新英国惊悚大片迅雷下载、免费下载，背离BD中字1280高清2012最新英国惊悚大片Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}背离BD中字1280高清2012最新英国惊悚大片{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-21{/dede:field}
{dede:field name='body'}<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120323/14/56643687201203231418221155641919480_004.jpg" /></p>
<p>
	◎译　　名　背离<br />
	◎片　　名　Deviation<br />
	◎年　　代　2012<br />
	◎国　　家　英国<br />
	◎类　　别　惊悚<br />
	◎语　　言　英语<br />
	◎字　　幕　中文<br />
	◎IMDB评分 (awaiting 5 votes)<br />
	◎IMDB链接 <a href="http://www.bluemv.com" title="电影下载">http://www.bluemv.com</a><br />
	◎文件格式　DVD-RMVB<br />
	◎视频尺寸　640 x 272<br />
	◎文件大小　1CD 453MB<br />
	◎片　　长　90 Mins<br />
	◎导　　演　J.K. Amalou<br />
	◎主　　演　丹尼&middot;戴尔 Danny Dyer &hellip;Frankie<br />
	　　　　　　安娜&middot;沃尔顿 Anna Walton &hellip;Amber<br />
	　　　　　　James Doherty &hellip;Jono<br />
	　　　　　　David Fynn &hellip;Justin<br />
	　　　　　　Alan McKenna &hellip;Tough Cop<br />
	　　　　　　Roy Smiles &hellip;Brian<br />
	　　　　　　Ben Wigzell &hellip; Bob<br />
	　　　　　　Gabriel Cameron &hellip;Van Driver</p>
<p>
	◎简　　介　</p>
<p>
	讲诉了一个个令人恐惧的夜晚，《背离》将要带你进入富兰克诺顿的心灵经历一场惊险的旅程。富兰克诺顿是一个危险的患有精神分裂症的凶手，他逃离了布罗德莫尔医院并在伦敦像一头凶狠的猛虎一样开始屠杀。但当富兰克抓住一个人质之时，致命的猫捉老鼠的游戏真正开始。</p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120323/14/56643687201203231418221155641919480_000.jpg" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120323/14/56643687201203231418221155641919480_003.jpg" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120323/14/56643687201203231418221155641919480_001.jpg" /></p>
<p>
	<img alt="" file="http://img170.poco.cn/mypoco/myphoto/20120328/18/56643687201203281831381194211917187_001.jpg" height="337" lazyloaded="true" src="http://img170.poco.cn/mypoco/myphoto/20120328/18/56643687201203281831381194211917187_001.jpg" style="cursor: pointer" width="600" /></p>
<p>
	<img alt="" file="http://img170.poco.cn/mypoco/myphoto/20120328/18/56643687201203281831381194211917187_003.jpg" height="337" lazyloaded="true" src="http://img170.poco.cn/mypoco/myphoto/20120328/18/56643687201203281831381194211917187_003.jpg" style="cursor: pointer" width="600" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3058/飘花电影piaohua.com背离DVD中字.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3058/飘花电影piaohua.com背离DVD中字.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3058/飘花电影piaohua.com背离DVD中字.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3094/飘花电影piaohua.com背离BD中字1280高清.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3094/飘花电影piaohua.com背离BD中字1280高清.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3094/飘花电影piaohua.com背离BD中字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O16455260-25c9.jpg{/dede:field}
