{dede:field name='keywords'}人生/傲笑江湖BD1280高清中字迅{/dede:field}
{dede:field name='description'}人生/傲笑江湖BD1280高清中字迅雷下载、免费下载，人生/傲笑江湖BD1280高清中字Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}人生/傲笑江湖BD1280高清中字{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-23{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120523/22/17870980201205232231171684095110331_007.jpg" /></p>
<p>
	◎译　　名　人生/傲笑江湖<br />
	◎片　　名　Life<br />
	◎年　　代　1999<br />
	◎国　　家　美国<br />
	◎类　　别　喜剧/犯罪/剧情<br />
	◎IMDB评分&nbsp;&nbsp;6.2/10 from 20,344 users<br />
	◎IMDB链接&nbsp;&nbsp;<a href="http://www.imdb.com/title/tt0123964/" target="_blank">http://www.imdb.com/title/tt0123964/</a><br />
	◎语　　言　英语<br />
	◎字　　幕　<br />
	◎片　　长　108 mins 31 seconds<br />
	◎导　　演　泰德&middot;戴米 Ted Demme<br />
	◎主　　演　艾迪&middot;墨菲 Eddie Murphy ....Rayford Gibson<br />
	　　　　　　马丁&middot;劳伦斯 Martin Lawrence ....Claude Banks<br />
	　　　　　　Obba Babatund&eacute; ....Willie Long<br />
	　　　　　　尼克&middot;卡索维茨 Nick Cassavetes ....Sergeant Dillard<br />
	　　　　　　安东尼&middot;安德森 Anthony Anderson ....Cookie<br />
	　　　　　　Barry Shabaka Henley ....Pokerface<br />
	　　　　　　布赖特&middot;詹宁斯 Brent Jennings ....Hoppin&#39; Bob<br />
	　　　　　　伯尼&middot;麦克 Bernie Mac ....Jangle Leg<br />
	　　　　　　小米盖尔-A&middot;努耐兹 Miguel A. N&uacute;?ez Jr. ....Biscuit<br />
	　　　　　</p>
<p>
	◎简　　介<br />
	<br />
	　　故事发生在美国实行禁酒令的年代，小扒手雷（艾迪&middot;墨菲 饰）和爱小赌两把的准银行行员克劳（马丁&middot;劳伦斯 饰）在因缘际会的情况下，必须为史班吉（瑞克&middot;詹姆斯 饰）运送私酒。<br />
	<br />
	　　然而原本只是到密西西比买酒的两人却在坏心警长的陷害下，被诬告犯下谋杀罪而获判终生监禁；无辜入狱的雷和克劳两个人由原本一见面就吵架的对头冤家，在朝夕相处下渐渐培养出互相依赖的情谊，在漫长而无聊的牢狱生涯里，两人心中共同的希望便是有朝一日能脱离这座牢笼，因而想出无数次千奇百怪的越狱计划，却也在不知不觉间渡过了六十余年的牢狱生活&hellip;&hellip;<br />
	<br />
	<br />
	◎一句话评论<br />
	<br />
	Share it with someone you love.<br />
	<br />
	<br />
	◎幕后制作<br />
	<br />
	　　艾迪&middot;墨菲Eddie Murphy和马丁&middot;劳伦斯Martin Lawrence的第二次合作，饰演这两个倒霉透顶的家伙。当两位主角出场时，所有人都预期将会有令人捧腹大笑的场面出现，但本片并非直奔主题的喜剧片，事实上，伤感甚至痛苦的片段并不少见，但始终围绕着对生活的热爱和希望，这正是本品的珍贵之处。&nbsp;</p>
<p>
	<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120523/22/17870980201205232231171684095110331_006.jpg" style="width: 640px; height: 360px" /></p>
<p>
	<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120523/22/17870980201205232231171684095110331_000.jpg" /></p>
<p>
	<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120522/23/17870980201205222339583676526813135_006.jpg" style="width: 640px; height: 360px" /></p>
<p>
	&nbsp;</p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaobajie.com" target="_blank">http://www.xiaobajie.com</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy241:piaohua@117.41.229.29:2034/飘花电影piaohua.com人生BD1280高清中字.rmvb">ftp://dy241:piaohua@117.41.229.29:2034/飘花电影piaohua.com人生BD1280高清中字.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15NM60-41T1.jpg{/dede:field}
