{dede:field name='keywords'}天天向上迅雷下载，免费下载，Gv{/dede:field}
{dede:field name='description'}天天向上迅雷下载、免费下载，天天向上Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}天天向上{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-07-30{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="/uploads/allimg/c120524/133N4O4X10-1aC.jpg" style="width: 250px; height: 350px" /></p>
<p>
	<img src="/uploads/allimg/c120524/133N4O49460-22314.jpg" /></p>
<p>
	<img src="/uploads/allimg/c120524/133N4O5X60-33521.jpg" /></p>
<p>
	<img src="/uploads/allimg/c120524/133N4O59320-411E.jpg" /></p>
<p>
	主持：<br />
	小五 / 矢野浩二 / 俞灏明 / 钱枫 / 田源 / 欧弟 / 汪涵 更多&raquo;</p>
<p>
	&bull;类型：综艺 / 内地综艺 / 脱口秀<br />
	&bull;首映：2008年8月4日 中国<br />
	&nbsp;<br />
	&bull;点评： 老师教导我们说：&ldquo;好好学习天天向上。&rdquo;-<br />
	&bull;剧情： 《天天向上》是由湖南卫视打造的大型礼仪公德脱口秀节目，2008年8月4日首播。节目的主持阵容由汪涵、欧弟、田源、钱枫、俞灏明、矢野浩二、金恩圣（小五）七位组成。该节目采用全国第一支偶像男子团体的概念，用各种形式来传播中国千年礼仪之邦的礼仪文化。节目氛围欢快轻松幽默，受到广大观众的好评、有较高的收视率。另有同名歌曲、系列丛书《天天...更多&raquo;<br />
	&bull; 花絮： 《天天向上》是由湖南卫视推出的一档[1]大[2]型礼仪脱口秀节目。该节目以礼仪、公德为主题，分为歌舞、访谈、情景戏三段式，氛围欢快轻松幽默。该节目于2008年8月4日首播《天天向上前传》，8月7日正式播出，节目以传承中华礼仪，公德为主，也经常邀请一些明星、企业...</p>
<p>
	<img src="/uploads/allimg/c120524/133N4O5a20-54221.jpg" /></p>
<p>
	<img src="/uploads/allimg/c120524/133N4O60110-AO8.jpg" /></p>
<p>
	<img src="/uploads/allimg/c120524/133N4O60210-M3G.jpg" /></p>
<p>
	<img src="/uploads/allimg/c120524/133N4O60310-SF6.jpg" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="/uploads/allimg/c120524/133N2Z4FF-102231.jpg" />&nbsp;&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				&nbsp;&nbsp;&nbsp;天天向上20110603.rmvb</td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				&nbsp;&nbsp;&nbsp;天天向上20110610.rmvb</td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				&nbsp;&nbsp;&nbsp;天天向上20110617.rm</td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				&nbsp;&nbsp;&nbsp;天天向上20110624.rmvb</td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				&nbsp;&nbsp;&nbsp;天天向上20110701.rmvb </td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				&nbsp;&nbsp;&nbsp;天天向上20110708.rmvb</td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				&nbsp;&nbsp;&nbsp;天天向上20110715.rmvb </td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120524/133N4O4X10-1aC.jpg{/dede:field}
