<?php
$z[0]=Array("field","2011年春节联欢晚会迅雷下载，免",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","2011年春节联欢晚会迅雷下载、免费下载，2011年春节联欢晚会Gvod高清在线播放，剧情介绍等。",73,203);
$z[1][4]['name']="description";
$z[2]=Array("field","2011年春节联欢晚会",205,261);
$z[2][4]['name']="title";
$z[3]=Array("field","",263,302);
$z[3][4]['name']="writer";
$z[4]=Array("field","",304,343);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-07-30",345,395);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>\r\n	<img alt=\"2011年春节联欢晚会\" id=\"img_movie_250x350\" src=\"/uploads/allimg/c120524/133N4O60560-92194.jpg\" /></p>\r\n\r\n<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\r\n	<tbody>\r\n		<tr>\r\n			<td width=\"78\">\r\n				配音：</td>\r\n			<td width=\"406\">\r\n				周涛 朱军 董卿 李咏 张泽群 朱迅 中国 晚会典礼</td>\r\n		</tr>\r\n		<tr>\r\n			<td width=\"78\">\r\n				国家/地区：</td>\r\n			<td width=\"406\">\r\n				中国</td>\r\n		</tr>\r\n	</tbody>\r\n</table>\r\n<p>\r\n	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border=\"0\" src=\"/uploads/allimg/c120524/133N2Z4FF-102231.jpg\" />&nbsp;&nbsp;&nbsp;</p>\r\n\r\n<table bgcolor=\"#ff8c00\" border=\"0\" cellpadding=\"5\" cellspacing=\"1\" width=\"100%\">\r\n	<tbody>\r\n		<tr>\r\n			<td bgcolor=\"#ffffbb\" style=\"line-height: 18px; word-break: break-all\" width=\"100%\">\r\n				&nbsp;&nbsp;央视2011兔年春节联欢晚会全场完整版HDTV.rmvb</td>\r\n		</tr>\r\n	</tbody>\r\n</table>",397,1353);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c120524/133N4O61R0-105144.jpg",1355,1439);
$z[7][4]['name']="litpic";

?>