{dede:field name='keywords'}笑拳怪招HD高清国语中字1024*576{/dede:field}
{dede:field name='description'}笑拳怪招HD高清国语中字1024*576迅雷下载、免费下载，笑拳怪招HD高清国语中字1024*576Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}笑拳怪招HD高清国语中字1024*576{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-09-13{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="/uploads/allimg/c120525/133O02X4130-11Q06.jpg" /><img alt="" src="/uploads/allimg/c120525/133O02X5J0-129538.jpg" /></p>
<p>
	◎译　　名　笑拳怪招<br />
	◎片　　名　Fearless Hyena<br />
	◎年　　代　1979<br />
	◎地　　区　中国香港<br />
	◎类　　别　动作/喜剧<br />
	◎语　　言　普通话<br />
	◎字　　幕　中文<br />
	◎IMDB评分 5.8/10 (43 votes)<br />
	◎文件格式　XviD + AC3<br />
	◎视频尺寸　1024 x 576<br />
	◎文件大小　1.3G<br />
	◎片　　长　01：37：08 Min<br />
	◎导　　演　成龙 Jackie Chan<br />
	◎主　　演　成龙 Jackie Chan .....Shing Lung<br />
	　　　　　　田俊 James Tien .....Grandpa<br />
	　　　　　　石天 Tean Shek .....The Coffin Seller (as Shih Tien)<br />
	　　　　　　任细官 Sai-kun Yam .....Yen<br />
	　　　　　　程天赐 Tien-chi Cheng .....Willow Sword<br />
	　　　　　　陈慧楼 Wai Lau Chen .....The Unicorn<br />
	　　　　　　郑富雄 Fu Hung Cheng<br />
	　　　　　　马场 Cheung Ma</p>
<p>
	成龙首部自编自导作品 上映当年票房冠军</p>
<p>
	形意门大掌门人陈鹏飞（田俊 饰）因受清廷的迫害，与孙儿兴龙（成龙 饰）隐姓埋名，居于山间。惜龙喜四出惹事生非，无意中泄露身份，被清廷统带任天化（任世官 饰）追至。陈不敌任，惨被打死。龙亲眼目睹祖父被杀，决意发愤图强，拜祖父的好友八脚麒麟为师，苦练形意拳，誓为祖父报仇。究竟最后龙能否打败任呢？</p>
<p>
	<br />
	☆影片简评☆</p>
<p>
	成龙近年的作品大家耳熟能详，但他有不少早年作品均值得一看，《笑拳怪招》及其续集《龙腾虎跃》就是其中之一。《笑拳怪招》为成龙大哥初执导筒之作，同台演出还有田俊、石天等。成龙饰演一名为了报仇雪仇而苦练武功的少年。练武过程自然少不了眩目的功夫，而成龙与仇家的打斗更教人目不暇给。《笑拳怪招》并非一味暴力，而是充满喜剧元素，因而大受欢迎。电影于1979年上映，数周内收得超过五百万港元，以当时来说是非常可观的数字，更加打破了发行该片的院线的纪录。续集《龙腾虎跃》中，成龙与惠天赐饰演失散多年的兄弟，故事继续以报仇为主线，兄弟二人联手对付天地双煞，电影中当然亦少不了精彩武打场面，扣人心弦。</p>
<p>
	☆影片截图☆</p>
<p>
	&nbsp;<img alt="" src="/uploads/allimg/c120525/133O02XC40-131419.jpg" style="width: 720px; height: 405px" /><img alt="" src="/uploads/allimg/c120525/133O02XKP-143496.jpg" style="width: 720px; height: 405px" /><img alt="" src="/uploads/allimg/c120525/133O02XU0-15T35.jpg" style="width: 720px; height: 405px" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="/uploads/allimg/c120524/133N2Z4FF-102231.jpg" />&nbsp;&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy125:piaohua@dy125.piaohua.com:3022/飘花电影piaohua.com笑拳怪招HD高清国语中字1024分辨率.rmvb </td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O02X9540-1E1R.jpg{/dede:field}
