{dede:field name='keywords'}玻璃笼BD1280高清迅雷下载，免费{/dede:field}
{dede:field name='description'}玻璃笼BD1280高清迅雷下载、免费下载，玻璃笼BD1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}玻璃笼BD1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-04-11{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://i.imgur.com/s7I1D.jpg" style="width: 700px; height: 892px" /></p>
<p>
	◎译　　名　玻璃笼<br />
	◎片　　名　In a Glass Cage<br />
	◎年　　代　1987<br />
	◎国　　家　西班牙<br />
	◎类　　别　剧情/恐怖<br />
	◎语　　言　西班牙语<br />
	◎字　　幕　中字<br />
	◎IMDB评分 &nbsp; 7.0/10 (1,277 votes)<br />
	◎IMDB链接 &nbsp; <a class="faqlink" href="http://www.imdb.com/title/tt0090197/">http://www.imdb.com/title/tt0090197/</a><br />
	◎片　　长　112MiN<br />
	◎导　　演　奥古斯汀&middot;维拉罗伽 Agust&iacute;n Villaronga<br />
	◎主　　演　玛丽莎&middot;佩雷德斯 Marisa Paredes ....Griselda<br />
	　　　　　　G&uuml;nter Meisner ....Klaus<br />
	　　　　　　David Sust ....Angelo<br />
	　　　　　　Gis&egrave;le Echevarr&iacute;a ....Rena (as Gis&egrave;la Echevarr&iacute;a)<br />
	　　　　　　Imma Colomer ....Jornalera<br />
	　　　　　　Josue Guasch ....Ni?o Cantior<br />
	　　　　　　David Cuspinera ....Ni?o barracon<br />
	　　　　　　Ricardo Carcelero ....Angelo Ni?o<br />
	　　　　　　Alberto Manzano ....Ni?o gitano<br />
	<br />
	【文件格式】x264+AC3<br />
	【视频尺寸】1280 x 720<br />
	<br />
	<br />
	◎简　　介<br />
	<br />
	　　当年一名有恋童癖的纳粹军医受命处死很多小孩，却对其中一名男童关爱有加，两人产生不伦之恋。可是这名纳粹军医却因为杀害了很多小孩而倍感罪恶，从屋顶跳了下去，后来一直只能躺在人工呼吸器里生活。多年后，他的妻子逐渐厌恶这种生活，开始想谋害他。同时，依然深爱着他的那名男童长大了，并来到他家担任护士照顾他。<br />
	&nbsp;</p>
<p>
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120411/07/62564813201204110726101099863318251_002.jpg" style="width: 650px; height: 366px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120411/07/62564813201204110726101099863318251_001.jpg" style="width: 650px; height: 366px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120411/07/62564813201204110726101099863318251_000.jpg" style="width: 650px; height: 366px" /><br />
	&nbsp;</p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.net/" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy125:piaohua@dy125.piaohua.com:7831/飘花电影piaohua.com玻璃笼BD中字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:7831/飘花电影piaohua.com玻璃笼BD中字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O16294U0-23N9.jpg{/dede:field}
