{dede:field name='keywords'}亲密损友港台剧46迅雷下载，免费{/dede:field}
{dede:field name='description'}亲密损友港台剧46迅雷下载、免费下载，亲密损友港台剧46Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}亲密损友港台剧46{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-25{/dede:field}
{dede:field name='body'}<p>
	<img src="http://img.funshion.com/attachment/new_images/2012/03-23/18881305_1332472141_9.jpg" /></p>
<p>
	演员：</p>
<p>
	关楚耀 / 高皓正 / 赵硕之 / 尹蓁晞 / 谭杏蓝&nbsp;</p>
<p>
	&bull;类型：爱情 / 喜剧<br />
	&bull;首映：2012年3月20日 中国香港<br />
	&nbsp;<br />
	&bull;点评： 一夜情,离婚,失恋,好色亲密损友直逼辛辣话题--</p>
<p>
	&bull;剧情： 赵永汉（关楚耀饰）与江若宁（赵硕之饰）选择于2007年7月1日结婚，正是香港回归十周年的重要日子，意义在于要见证他们的感情50年不变，但最终婚姻却只维持了短短两年。 与大多数年轻人一样，他们的邂逅虽然平淡但热恋极为甜蜜，结婚是没有经过深思熟虑的决定，出问题之后，离婚成了唯一解脱的方法。 被背叛的若宁对永汉虽仍有一丝恨意，...</p>
<p>
	<img src="http://img.funshion.com/attachment/new_images/2012/03-23/18881305_1332472300_585.jpg" width="650" /></p>
<p>
	&nbsp;<img src="http://img.funshion.com/attachment/new_images/2012/03-23/18881305_1332472296_403.jpg" width="650" /></p>
<p>
	[下载地址]： &nbsp;<img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" /></p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3075/飘花电影piaohua.com亲密损友01.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3075/飘花电影piaohua.com亲密损友01.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3075/飘花电影piaohua.com亲密损友02.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3075/飘花电影piaohua.com亲密损友02.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3075/飘花电影piaohua.com亲密损友03.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3075/飘花电影piaohua.com亲密损友03.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3075/飘花电影piaohua.com亲密损友04.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3075/飘花电影piaohua.com亲密损友04.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3095/飘花电影piaohua.com亲密损友05.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3095/飘花电影piaohua.com亲密损友05.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3095/飘花电影piaohua.com亲密损友06.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3095/飘花电影piaohua.com亲密损友06.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3100/飘花电影piaohua.com亲密损友07.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3100/飘花电影piaohua.com亲密损友07.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3133/飘花电影piaohua.com亲密损友08.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3133/飘花电影piaohua.com亲密损友08.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3133/飘花电影piaohua.com亲密损友09.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3133/飘花电影piaohua.com亲密损友09.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3133/飘花电影piaohua.com亲密损友10.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3133/飘花电影piaohua.com亲密损友10.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3139/飘花电影piaohua.com亲密损友11.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3139/飘花电影piaohua.com亲密损友11.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3154/飘花电影piaohua.com亲密损友12.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3154/飘花电影piaohua.com亲密损友12.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3210/飘花电影piaohua.com亲密损友13.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3210/飘花电影piaohua.com亲密损友13.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3210/飘花电影piaohua.com亲密损友14.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3210/飘花电影piaohua.com亲密损友14.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3210/飘花电影piaohua.com亲密损友15.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3210/飘花电影piaohua.com亲密损友15.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3210/飘花电影piaohua.com亲密损友16.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3210/飘花电影piaohua.com亲密损友16.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3249/飘花电影piaohua.com亲密损友17.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3249/飘花电影piaohua.com亲密损友17.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3249/飘花电影piaohua.com亲密损友18.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3249/飘花电影piaohua.com亲密损友18.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3249/飘花电影piaohua.com亲密损友19.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3249/飘花电影piaohua.com亲密损友19.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3249/飘花电影piaohua.com亲密损友20.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3249/飘花电影piaohua.com亲密损友20.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3249/飘花电影piaohua.com亲密损友21.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3249/飘花电影piaohua.com亲密损友21.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3266/飘花电影piaohua.com亲密损友22.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3266/飘花电影piaohua.com亲密损友22.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3266/飘花电影piaohua.com亲密损友23.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3266/飘花电影piaohua.com亲密损友23.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3266/飘花电影piaohua.com亲密损友24.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3266/飘花电影piaohua.com亲密损友24.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3293/飘花电影piaohua.com亲密损友25.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3293/飘花电影piaohua.com亲密损友25.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3299/飘花电影piaohua.com亲密损友26.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3299/飘花电影piaohua.com亲密损友26.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3306/飘花电影piaohua.com亲密损友27.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3306/飘花电影piaohua.com亲密损友27.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3313/飘花电影piaohua.com亲密损友28.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3313/飘花电影piaohua.com亲密损友28.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3317/飘花电影piaohua.com亲密损友29.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3317/飘花电影piaohua.com亲密损友29.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3328/飘花电影piaohua.com亲密损友30.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3328/飘花电影piaohua.com亲密损友30.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3334/飘花电影piaohua.com亲密损友31.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3334/飘花电影piaohua.com亲密损友31.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3341/飘花电影piaohua.com亲密损友32.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3341/飘花电影piaohua.com亲密损友32.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3346/飘花电影piaohua.com亲密损友33.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3346/飘花电影piaohua.com亲密损友33.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3353/飘花电影piaohua.com亲密损友34.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3353/飘花电影piaohua.com亲密损友34.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3372/飘花电影piaohua.com亲密损友35.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3372/飘花电影piaohua.com亲密损友35.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3378/飘花电影piaohua.com亲密损友36.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3378/飘花电影piaohua.com亲密损友36.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3381/飘花电影piaohua.com亲密损友37.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3381/飘花电影piaohua.com亲密损友37.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3393/飘花电影piaohua.com亲密损友38.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3393/飘花电影piaohua.com亲密损友38.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3402/飘花电影piaohua.com亲密损友39.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3402/飘花电影piaohua.com亲密损友39.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3432/飘花电影piaohua.com亲密损友40.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3432/飘花电影piaohua.com亲密损友40.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3445/飘花电影piaohua.com亲密损友41.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3445/飘花电影piaohua.com亲密损友41.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3454/飘花电影piaohua.com亲密损友42.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3454/飘花电影piaohua.com亲密损友42.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3458/飘花电影piaohua.com亲密损友43.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3458/飘花电影piaohua.com亲密损友43.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3464/飘花电影piaohua.com亲密损友44.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3464/飘花电影piaohua.com亲密损友44.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3478/飘花电影piaohua.com亲密损友45.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3478/飘花电影piaohua.com亲密损友45.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3491/飘花电影piaohua.com亲密损友46.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3491/飘花电影piaohua.com亲密损友46.rmvb</a></td>
		</tr>
	</tbody>
</table>
<p>
	&nbsp;</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15244410-14221.jpg{/dede:field}
