{dede:field name='keywords'}奇幻精灵事件簿/奇幻精灵历险记B{/dede:field}
{dede:field name='description'}奇幻精灵事件簿/奇幻精灵历险记BD中英双字1024高清迅雷下载、免费下载，奇幻精灵事件簿/奇幻精灵历险记BD中英双字1024高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}奇幻精灵事件簿/奇幻精灵历险记BD中英双字1024高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-02-16{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://d24:d24@dm.eee4.com:1205/[3E电影站www.eee4.com]奇幻精灵事件簿DVD中英双字.rmvb" target="_blank{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MOX4230-4R31.jpg{/dede:field}
