<?php
$z[0]=Array("field","奇幻精灵事件簿/奇幻精灵历险记B",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","奇幻精灵事件簿/奇幻精灵历险记BD中英双字1024高清迅雷下载、免费下载，奇幻精灵事件簿/奇幻精灵历险记BD中英双字1024高清Gvod高清在线播放，剧情介绍等。",73,261);
$z[1][4]['name']="description";
$z[2]=Array("field","奇幻精灵事件簿/奇幻精灵历险记BD中英双字1024高清",263,348);
$z[2][4]['name']="title";
$z[3]=Array("field","",350,389);
$z[3][4]['name']="writer";
$z[4]=Array("field","",391,430);
$z[4][4]['name']="source";
$z[5]=Array("field","2012-02-16",432,482);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",484,521);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://d24:d24@dm.eee4.com:1205/[3E电影站www.eee4.com]奇幻精灵事件簿DVD中英双字.rmvb\" target=\"_blank",523,661);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MOX4230-4R31.jpg",663,745);
$z[8][4]['name']="litpic";

?>