{dede:field name='keywords'}行星地球特别版：沙漠狮BD中字10{/dede:field}
{dede:field name='description'}行星地球特别版：沙漠狮BD中字1024/1280高清纪录片迅雷下载、免费下载，行星地球特别版：沙漠狮BD中字1024/1280高清纪录片Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}行星地球特别版：沙漠狮BD中字1024/1280高清纪录片{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-01-28{/dede:field}
{dede:field name='body'}<p>
	◎译　　名　行星地球特别版：沙漠狮<br />
	◎片　　名　Planet Earth Bonus Desert Lions<br />
	◎年　　代　2006<br />
	◎国　　家　美国<br />
	◎类　　别　记录片<br />
	◎语　　言　英语<br />
	◎字　　幕　中字<br />
	◎IMDB评分&nbsp; 9.7/10 from 23,763 users<br />
	◎文件格式　BD-RMVB<br />
	◎视频尺寸　1024 x 576/1280x 720<br />
	◎文件大小　1CD<br />
	◎片　　长　49 mins 24 seconds<br />
	◎导　　演　艾雷斯泰&middot;法瑟吉尔 Alastair Fothergill ....(11 episodes, 2006)<br />
	◎编　　剧　大卫&middot;爱登堡 David Attenborough ....(5 episodes, 2006)<br />
	◎主　　演　大卫&middot;爱登堡 David Attenborough .... Narrator<br />
	<br />
	◎简　　介　　　　　　<br />
	<br />
	　　纳米布 - 地球上最古老的沙漠。在无情的，它是不容易理解。不稳定的水骷髅海岸近距离接触到沿其整个长度荒野。毫不奇怪，纳 米布以及保持他们的秘密。曾几何时，住着狮子。然而，人们喜欢他们的时候，我们却很少看到。然而，二十余年前，他们消失了。而今天，一个人决定挑战沙漠。他相信，最神奇的非洲狮子正在慢慢恢复... ...<br />
	<br />
	<br />
	◎获奖记录<br />
	<br />
	&nbsp; 2007艾美奖 非小说类杰出摄影/杰出音乐编曲/非小说类杰出连续剧/非小说类杰出音效剪辑。<br />
	<br />
	<img alt="" border="0" src="http://img.album.pchome.net/54/85/07/05/0cc97d07bc5f84f898bab099f3580dd0.jpg" /><br />
	<img alt="" border="0" src="http://img.album.pchome.net/54/85/07/05/fb112a65eca8e9797c60e9c3617c9eda.jpg" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2675/飘花电影piaohua.com行星地球特别版：沙漠狮BD中字1024高清.rmvb">&nbsp;ftp://dy44:piaohua@dy44.piaohua.com:2675/飘花电影piaohua.com行星地球特别版：沙漠狮BD中字1024高清.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy241:xiaobajie@dy241.piaohua.com:2052/小八戒电影xiaobajie.com行星地球特别版：沙漠狮中字720p.rmvb">&nbsp;ftp://dy241:xiaobajie@dy241.piaohua.com:2052/小八戒电影xiaobajie.com行星地球特别版：沙漠狮中字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1CI210-5U94.jpg{/dede:field}
