{dede:field name='keywords'}邵氏经典佛都有火DVD国语中字迅{/dede:field}
{dede:field name='description'}邵氏经典佛都有火DVD国语中字迅雷下载、免费下载，邵氏经典佛都有火DVD国语中字Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}邵氏经典佛都有火DVD国语中字{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-08-12{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="/uploads/allimg/c120525/133O03519150-125G8.jpg" /></p>
<p>
	◎片　　名　佛都有火&nbsp;<br />
	◎译　　名　The Boxer from the Temple&nbsp;<br />
	◎年　　代　2006<br />
	◎国　　家　香港<br />
	◎类　　别　动作<br />
	◎语　　言　国语<br />
	◎字　　幕　简体中文<br />
	◎文件格式　RVMB<br />
	◎视频尺寸　720 x 404<br />
	◎片　　长　92<br />
	◎导　　演　罗马<br />
	◎编&nbsp;&nbsp;&nbsp; 剧：吴元俊<br />
	◎主　　演　主演：吴元俊 王沙 林辉煌<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br />
	　　　　　<br />
	◎简　　介<br />
	　　&nbsp;&nbsp; 佛都有火讲述的是本片由罗马导演、倪匡编剧，拍于1980年，由着名武打红星吴元俊领衔主</p>
<p>
	演。故事讲述某寺青年僧人&ldquo;疯子&rdquo;吴元俊 饰，性格疯疯癫癫，行为全不符僧人规范。该寺主持玄</p>
<p>
	明方丈却认为&ldquo;疯子&rdquo;与佛有缘，并因应其性格与气质，授以&ldquo;癫罗汉拳&rdquo;。&ldquo;疯子&rdquo;有了武功后</p>
<p>
	，动辄出拳伤人，方丈只得将其逐出寺门&hellip;&hellip;</p>
<p>
	◎截　　图：</p>
<p>
	<img alt="" src="/uploads/allimg/c120525/133O035201F-1324E.jpg" /><img alt="" src="/uploads/allimg/c120525/133O03521050-149431.jpg" /><img alt="" src="/uploads/allimg/c120525/133O03521L0-15aZ.jpg" /></p>
<p>
	[佛都有火下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="/uploads/allimg/c120524/133N2Z4FF-102231.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy195:piaohua@dy195.piaohua.com:1023/飘花电影下载站www.xiaozhizhu.net佛都有火国语中字.rmvb </td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O035224F-1D009.jpg{/dede:field}
