{dede:field name='keywords'}蜜桃成熟时33D国粤双语BD1280高{/dede:field}
{dede:field name='description'}蜜桃成熟时33D国粤双语BD1280高清迅雷下载、免费下载，蜜桃成熟时33D国粤双语BD1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}蜜桃成熟时33D国粤双语BD1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-03-23{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img165.poco.cn/mypoco/myphoto/20120122/09/56643687201201220917233796578412109_004.jpg" style="width: 412px; height: 600px" /></p>
<p>
	◎译　　名　蜜桃成熟时33D<br />
	◎片　　名　The 33D Invader<br />
	◎年　　代　2011<br />
	◎国　　家　香港<br />
	◎类　　别　喜剧/科幻<br />
	◎语　　言　国语/粤语<br />
	◎字　　幕　无<br />
	◎IMDB评分 (awaiting 5 votes)<br />
	◎IMDB链接 <a href="http://www.qqtmb.com/">http://www.qqtmb.com/</a><br />
	◎文件格式　X264 + DTS<br />
	◎视频尺寸　1280 x 720<br />
	◎文件大小　1CD 888MB<br />
	◎片　　长　1hr 22mn<br />
	◎导　　演　钱文锜 Man Kei Chin<br />
	◎主　　演　吴晴晴 Wu Qing-Qing<br />
	　　　　　　加藤鹰 Akiho Yoshizawa<br />
	　　　　　　吉泽明步 Taka Kato<br />
	　　　　　　陈俊言 Jun-Yan Chen<br />
	　　　　　　林宜芝 Monna Lam<br />
	　　　　　　罗家英 Law Kar-ying<br />
	　　　　　　米亚<br />
	　　　　　　芝芝<br />
	<br />
	◎简　　介　<br />
	<br />
	　　 朗仔(陈俊言 饰) 、星爷(徐浩昌 饰) 、废柴(张建声 饰) 、蛋散(郭汉柱 饰)四个大学生在海边租了一间渡假屋温习应付毕业考试，发现四名美女同学千千(吉泽明步 饰)、西西(芝芝 饰)、珍珍(林宜芝 饰)与米亚(米亚 饰)搬到了隔壁。星爷、废柴、蛋散都是色鬼，用各种电子遥控装备去偷窥四美女跟占她们便宜。但四美女冰雪聪明，他们非但无法得手，还被狠狠整了一顿。<br />
	　　 但其中最美的校花千千，其实暗恋朗仔，但朗仔却无胆入情关，反而校中恶霸大哥成(梁焯满 饰)，却对千千死缠不休。<br />
	　　 朗仔回家睡觉，半夜忽然狂风大作，磁场混乱，在强压电流<a href="http://www.qqtmb.com/" style="color: rgb(0, 0, 0); text-decoration: none;">个性签名</a>中忽然出现一位全裸美少女，自称叫&ldquo;未来&rdquo; (吴晴晴 饰)，是从2046年经时光机回到2011年，找寻完美基因的，因为在2046年，外星人已用辐射令地球男女失去生殖能力，她是<a href="http://www.6dtaobao.com/" style="color: rgb(0, 0, 0); text-decoration: none;">淘宝网女装</a>罕有的健康适宜生育的女性，所以被派来带完美精子回去，延续人类后代。<br />
	　　 朗仔不信，以为未来是千千一党派来捉弄<a href="http://www.anzhuo4.com/" style="color: rgb(0, 0, 0); text-decoration: none;">安卓游戏</a>他们的人，要她离开。不料未来施展超能力，令朗仔等无法不信。未来一一检查各人体质，发现只有朗仔符合标准。但朗仔不愿意进行无爱情成分的性，只答应带她回学校找合适的基因。<br />
	　　 大哥成去酒吧吐闷气，发现<a href="http://www.dailiv.com/" style="color: rgb(0, 0, 0); text-decoration: none;">在线代理</a>后巷狂风大作，电磁波中出现两个外星人：Xucker 1 (加滕鹰 饰) 和Xucker 2 (晨晞 饰)，二人为追杀未来而至，要阻止她带完美基因回2046年。二人要大哥成带路去找&ldquo;未来&rdquo;。<br />
	　　 千千为抢爱郎，不惜用药令朗仔众人失去理智，朗仔与千千发生关系，未来见到伤心，因她已对朗仔生情素，黯然而去，反避过了大哥成带来的两个外星人。两外星人捉走千千，威胁众人要带未来交换。<br />
	　　 众人如何对付两个外星人？未来能否取得朗仔健康的基因回去未来？朗仔最终爱的是未来还是千千？<br />
	◎影片截图<br />
	<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120122/10/56643687201201221045063057858176480_000.jpg" style="width: 720px; height: 306px" /><img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120122/10/56643687201201221044119782373351783_000.jpg" style="width: 720px; height: 306px" /><img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120122/10/56643687201201221044119782373351783_001.jpg" style="width: 720px; height: 306px" /><img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120122/10/56643687201201221044119782373351783_002.jpg" style="width: 720px; height: 306px" /><br />
	&nbsp;</p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="
ftp://dy125:piaohua@dy125.piaohua.com:7529/飘花电影piaohua.com蜜桃成熟时33DBD国语无字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:7529/飘花电影piaohua.com蜜桃成熟时33DBD国语无字1280高清.rmvb </a></td>
		</tr>
	</tbody>
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="
ftp://dy125:piaohua@dy125.piaohua.com:7529/飘花电影piaohua.com蜜桃成熟时33DBD粤语无字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:7529/飘花电影piaohua.com蜜桃成熟时33DBD粤语无字1280高清.rmvb </a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15931250-59106.jpg{/dede:field}
