{dede:field name='keywords'}兄弟[BD中英双字1024x576＋1280x{/dede:field}
{dede:field name='description'}兄弟[BD中英双字1024x576＋1280x720高清版]迅雷下载、免费下载，兄弟[BD中英双字1024x576＋1280x720高清版]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}兄弟[BD中英双字1024x576＋1280x720高清版]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2010-03-16{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://3e:3e@www5.eee4.cc:1419/【3E电影院www.eee4.cc】兄弟BD中英双字1280x720高清版.rmvb" target=_blank>ftftp://3e:3e@www5.eee4.cc:1419/【3E电影院www.eee4.cc】兄弟BD中英双字1280x720高清版.rmvb</A></TD></TR></TBODY></TABLE><STRONG><FONT color=#ff0000 size=2><BR>09年美国最新高分惊悚战争剧情大片《兄弟》DVD中英双字 [</FONT><FONT color=#ff0000 size=2>下载地址]：<IMG src="httftp://www.3edyy.com/templets/img/down.jpg" border=0><BR></FONT></STRONG>
<TABLE style="BORDER-RIGHT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; BORDER-BOTTOM: #cccccc 1px dotted" cellSpacing=0 cellPadding=6 width="95%" align=center border=0>
<TBODY>
<TR>
<TD style="WORD-WRAP: break-word" bgColor=#fdfddf><A href="ftftp://3e:3e@www2.3edyy.com:3985/【3E电影院www.eee4.cc】兄弟DVD中英双字.rmvb" target=_blank><FONT color=#0058b0>ftftp://3e:3e@www2.3edyy.com:3985/【3E电影院www.eee4.cc】兄弟DVD中英双字.rmvb</FONT></A></TD></TR></TBODY></TABLE><br><font color="#ff0000" size="2{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MP603T0-4Y35.jpg{/dede:field}
