{dede:field name='keywords'}皮娜BD高清迅雷下载，免费下载，{/dede:field}
{dede:field name='description'}皮娜BD高清迅雷下载、免费下载，皮娜BD高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}皮娜BD高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-10-20{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img165.poco.cn/mypoco/myphoto/20111020/08/62564813201110200824041537995635299_000.jpg" style="width: 500px; height: 714px" /><img alt="" src="http://img165.poco.cn/mypoco/myphoto/20111020/08/62564813201110200824041537995635299_001.jpg" style="width: 500px; height: 707px" /></p>
<p>
	【影片原名】Pina<br />
	【中文译名】皮娜/皮娜&middot;鲍什/翩娜(港)<br />
	【出品公司】Neue Road Movies<br />
	【出品年代】2011 年<br />
	【上映日期】2011年2月24日 德国<br />
	【影片级别】Germany:o.Al. | Switzerland:7 (canton of Geneva) | Switzerland:7 (canton of Vaud) | Ireland:G | Portugal:M/6 (Qualidade)<br />
	【官方网站】<a href="http://www.pina-film.de/">http://www.pina-film.de/</a><br />
	【IMDB链接】<a href="http://www.imdb.com/title/tt1440266/">http://www.imdb.com/title/tt1440266/</a><br />
	【IMDB评分】8.0/10 (1,300 votes)<br />
	【国　　家】德国/法国/英国<br />
	【类　　别】歌舞<br />
	【导　　演】维姆&middot;文德斯 Wim Wenders<br />
	【主　　演】皮娜&middot;鲍什 Pina Bausch&nbsp; ....Herself<br />
	　　　　　　玛洛&middot;艾劳多 Malou Airaudo&nbsp; ....Herself - Dancer<br />
	　　　　　　Regina Advento&nbsp; ....Herself - Dancer<br />
	　　　　　　Ruth Amarante&nbsp; ....Herself - Dancer<br />
	　　　　　　Rainer Behr&nbsp; ....Himself - Dancer<br />
	　　　　　　Andrey Berezin&nbsp; ....Himself - Dancer<br />
	　　　　　　Damiano Ottavio Bigi&nbsp; ....Himself - Dancer<br />
	　　　　　　B&eacute;n&eacute;dicte Billet&nbsp; ....Herself - Dancer<br />
	　　　　　　Ales Cucek&nbsp; ....Himself - Dancer<br />
	　　　　　　Clementine Deluy&nbsp; ....Herself - Dancer<br />
	　　　　　　Josephine Ann Endicott&nbsp; ....Herself - Dancer<br />
	　　　　　　Lutz F?rster&nbsp; ....Himself - Dancer<br />
	　　　　　　Pablo Aran Gimeno&nbsp; ....Himself - Dancer<br />
	　　　　　　Mechthild Grossmann&nbsp; ....Herself - Dancer<br />
	　　　　　　Silvia Farias Heredia&nbsp; ....Herself - Dancer</p>

<p>
	【内容简介】</p>
<p>
	　　这部影片预计会收录三段皮娜的舞蹈:《穆勒咖啡馆》(1978)、《春之祭》(1975)和《月圆》(2006)。2009年去世的皮娜&middot;鲍什是当今世界舞坛最富创意的舞蹈家之一。她开创了&ldquo;舞蹈剧场&rdquo;的演出形式,擅长在作品中融合悲伤与幽默,她的作品常以男人女人间的相互作用为主题。</p>
<p>
	<br />
	一句话评论</p>
<p>
	　　影片并没强行把电影假装成舞台,但《春之祭》、《穆勒咖啡馆》诡异又迷人的舞蹈用这种方法展现得充满力量,让人浮想联翩。 &mdash;&mdash;《好莱坞报道》</p>

<p>
	幕后制作</p>
<p>
	　　维姆&middot;文德斯很早就想与皮娜&middot;鲍什合作,但苦于找不到合适的表现媒介,而近年3D电影技术的发展为文德斯提供了恰当的条件,他认为3D可以&ldquo;让观众直接身处舞台&rdquo;。他表示:&ldquo;无论是在情绪上还是从美学上,二维的电影银幕无法捕捉到皮娜&middot;鲍什的舞蹈精髓。当我25年前第一次看见她的舞蹈时,深深地被感动了。我从这全新的艺术形式里感受到了人类运动、姿势的美感。而当年那种美妙的魅力正是我想通过银幕表达给观众的感觉。&rdquo;</p>
<p>
	　　《皮娜》是一部歌舞片,该片收录三段皮娜的舞蹈:《穆勒咖啡馆》(1978)、《春之祭》(1975)和《月圆》(2006)。2009年去世的皮娜&middot;鲍什是当今世界舞坛最富创意的舞蹈家之一。她开创了&ldquo;舞蹈剧场&rdquo;的演出形式,擅长在作品中融合悲伤与幽默,她的作品常以男人女人间的相互作用为主题。文德斯曾表示:&ldquo;无论是在情绪上还是从美学上,二维的电影银幕无法捕捉到皮娜&middot;鲍什的舞蹈精髓。当我25年前第一次看见她的舞蹈时,深深地被感动了。我从这全新的艺术形式里感受到了人类运动、姿势的美感。而当年那种美妙的魅力正是我想通过银幕表达给观众的感觉。&rdquo;</p>
<p>
	　　<br />
	&nbsp;&nbsp;&nbsp; 【舞蹈的力量】</p>
<p>
	　　《皮娜》是大师对大师的追思曲,文德斯在著名现代舞先驱皮娜&middot;鲍什去世后,重整二人最初的合作理念,用3D技术把皮娜生前在乌塔帕尔舞蹈剧团创作的四部经典舞剧重现于银幕;它在第61届柏林电影节的三部3D片中赢得最多赞赏,其中一大部分要归功于皮娜&middot;鲍什舞蹈自身的力量。即使这股力量强大到只能追随,文德斯仍然在服从之下,以银幕视作舞台和窗口,在空间上塑造现场观看的氛围,但观众又能突破舞台的距离,任意接近舞蹈现场或者跳脱到室外。06年U2的3D版演唱会电影在戛纳上映,让文德斯找到了把皮娜&middot;鲍什的舞蹈搬上银幕的最佳手段,&ldquo;3D技术确实拓宽了视觉空间。&rdquo;文德斯在采访中如是说。</p>
<p>
	　　<br />
	&nbsp;&nbsp;&nbsp; 【欧洲第一部3D电影】</p>
<p>
	　　《皮娜》严格意义上是欧洲的第一部3D电影,同样也是影史上首部艺术电影,制片人Gian-Piero Ringel 为这些记录接受了很大的挑战:&ldquo;不管是3D技术还是舞蹈题材,我们都走进了一个未知的领域,连找有经验的技术人员都非常困难&hellip;&hellip;很多导演现在仍不敢接受这种新的手段,因为过去没有成功的同类作品可以借鉴。&rdquo;</p>
<p>
	　　文德斯06年得到了拍摄技术上的灵感,但直到09年才宣布会用3D来为皮娜&middot;鲍什立传。[詹姆斯&middot;卡梅隆]为3D技术成熟等了十二年,文德斯在这两年里做着差不多的事情,&ldquo;早前的3D技术没办法与这个题材匹配,&ldquo;第一次试拍的结果很可怕,我们意识到2D拍摄会出现的问题会在3D版里放大,比如,如果摄像机对着运动中的舞者,画面会出现奇怪的重影,用2D拍摄的话我们只需要慢点摇镜头;但用3D机拍摄这种办法就没用了。舞者做任何动作都让他们在画面里变成三头六臂的怪物。&rdquo;而目前3D格式并不允许用50或60那样的高帧速拍摄。</p>
<p>
	　　《阿凡达》变成了文德斯的教材,但《皮娜》是完全的实景拍摄,加上舞蹈本身对速度和走位的特殊要求,文德斯和他的制作团队花了近两年的时间去打通让技术与艺术共存的通道。而&ldquo;文德斯+皮娜&middot;鲍什&rdquo;这种级别的组合并不常见,名气不大或者题材陌生的电影在融资时就会撞上冰山。米歇尔&middot;欧斯洛对此表示&ldquo;3D电影会让融资变得更困难,无论对制片人还是观众来说,它都太贵了。&rdquo;</p>
<p>
	　　</p>
<p>
	　　【险些夭折的创作】</p>
<p>
	　　《皮娜》由文德斯与乌帕塔尔舞蹈剧团的舞者合作完成,影片本该是文德斯与现代舞大师皮娜&middot;鲍什联袂之作,却因为她在09年罹患肺癌突然去世而险些夭折。因此,影片也从一部人物传记转变为向皮娜&middot;鲍什及其舞蹈致敬的影像实验品。文德斯表示,在皮娜去世前,两人已经确定一些拍摄理念和细节:&ldquo;我们一起商量了这部电影的概念,她影片的中心人物,拍摄时候她也要求在我身边监视,预览3D的效果,对很多曲目进行排练,我们还设定好了两个外景地,一部分在南美洲完成,一部分在亚洲。&rdquo;文德斯在09年五月宣布要以3D形式拍摄这部电影,不料在六月,皮娜&middot;鲍什被确诊患有肺癌五天后去世,&ldquo;这(电影)是我们曾经梦想要一同完成的作品。在她去世后,我差点想砍掉这个计划。可是我总觉得她并没有离开,还在哪个角落用她灼灼的眼神看着我们,我有时感觉到她就站在我的身后,我想问她,我是不是该继续走下去?我是不是许下了一个太大的誓言?我们深知这是一部为她而生的作品,对怎么用3D技术拍电影我们都不太熟悉,幸而得到了乌帕塔尔的编舞师、美术总监等许多人的帮忙。&rdquo;</p>
<p>
	　　曾经为文德斯多部电影担任制片的Gian-Piero Ringel很早开始游说投资商、电影基金会等为这部影片融资:&ldquo;我们在两年前决定使用3D技术,那时候它还不是很成熟、被广泛利用的技术,要说服别人参与,只要提及文德斯和皮娜,就像给他们打了一剂强心针。但她的死对我们是极大的挫败,我们几乎放弃了;在她去世几个月后,我们和她的儿子所罗门碰头,我说不如好好利用这个机会完成这个计划,实际上是她布下了这一切。&rdquo;</p>
<p>
	　　【影片制作】</p>
<p>
	　　影片拣选了《穆勒咖啡馆》、《月圆》、《春之祭》、《交际场》等皮娜&middot;鲍什代表作,由她生前所领导的乌帕塔尔舞蹈剧团的舞者重新排演,而表演的场地从剧场一直延伸到铁道、工厂、马路和山岗,立体化的影像让银幕变成了一个深远的剧场,观众的视野也打破了硬件上的隔断,游离于多重空间。在拍摄《皮娜&middot;鲍什》之前,文德斯与他的3D团队对这种技术知之甚少,记者们也好奇舞蹈家该如何适应在硕大的3D摄影机面前表演。和皮娜&middot;鲍什合作22年的Julie Shanahan表示:&ldquo;对我来说这事没那么复杂,皮娜一直跟我说,跳舞的时候要自我倾注,所以即使要面对镜头跳舞,我仍在沉浸在自己的世界。文德斯创造了很棒的舞蹈氛围,虽然摄像机很大,我们也渐渐适应它的存在。&rdquo;文德斯也接过话笑称&ldquo;因为要拍成3D电影,现场有两台摄影机,但大家都非常熟悉舞步了,没有人会跳着跳着撞机子上。&rdquo;</p>
<p>
	　　整部影片都在乌帕塔尔市拍摄,这里是皮娜&middot;鲍什舞蹈世界的中心,选择在这里取景,因为&ldquo;她在这个城市工作、教人跳舞,她作品的想象力几乎都来源于这里的人和物,她在这里工作了快四十年,每一年都创作了一部作品,除了1990年,那年她导演了自己的电影《皇后的悲歌》。我想,要向她致敬,这座城市也必须成为影片的一个角色,和她的舞者们一起,用他们的记忆来解答我对她提出的各种问题。&rdquo;</p>
<p>
	花絮</p>
<p>
	&middot;影片入围第61届柏林电影节竞赛单元;</p>
<p>
	&middot;影片在柏林电影节首映礼引来了德国总理默克尔、德国总统伍尔夫、文化部长诺伊曼等人的亲自到场,可谓声势浩大。</p>
<p>
	&middot;文德斯的新片在亮相第61届柏林电影节的三部3D片中赢得最多赞赏,其中一大部分要归功于皮娜&middot;鲍什舞蹈自身的力量。</p>
<p>
	<img alt="" src="http://img165.poco.cn/mypoco/myphoto/20111020/01/62564813201110200133252723830583508_002.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img165.poco.cn/mypoco/myphoto/20111020/01/62564813201110200133252723830583508_001.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img165.poco.cn/mypoco/myphoto/20111020/01/62564813201110200133252723830583508_000.jpg" style="width: 720px; height: 405px" /></p>

<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="&#13;&#10;ftp://dy125:piaohua@dy125.piaohua.com:7051/飘花电影piaohua.com皮娜BD中字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:7051/飘花电影piaohua.com皮娜BD中字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O16162060-14B3.jpg{/dede:field}
