{dede:field name='keywords'}倾城之泪高清1280版BD国语中字20{/dede:field}
{dede:field name='description'}倾城之泪高清1280版BD国语中字2011最新上映爱情大片迅雷下载、免费下载，倾城之泪高清1280版BD国语中字2011最新上映爱情大片Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}倾城之泪高清1280版BD国语中字2011最新上映爱情大片{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-03-03{/dede:field}
{dede:field name='body'}<p>
	<img src="http://img165.poco.cn/mypoco/myphoto/20111223/11/56643687201112231138452471768182350_008.jpg" /></p>
<p>
	<img src="http://img165.poco.cn/mypoco/myphoto/20111223/11/56643687201112231138452471768182350_007.jpg" /></p>
<p>
	<img src="http://img165.poco.cn/mypoco/myphoto/20111223/11/56643687201112231138452471768182350_006.jpg" /></p>
<p>
	<img src="http://img165.poco.cn/mypoco/myphoto/20111223/11/56643687201112231138452471768182350_005.jpg" /></p>
<p>
	中文名： 倾城之泪/全城绝恋<br />
	外文名： the tears/The Allure of Tears<br />
	出品时间： 2011年<br />
	出品公司： 福建恒业电影发行、上海凯羿影视<br />
	制片地区： 中国大陆、香港、台湾<br />
	导演： 黄真真<br />
	编剧： 郑丹瑞<br />
	制片人： 冯凯帅<br />
	类型： 爱情<br />
	主演： 李治廷，周冬雨，任贤齐，梁咏琪，窦骁，陈乔恩<br />
	片长： 108分钟<br />
	上映时间： 2011年12月22日<br />
	对白语言： 普通话<br />
	监制： 冯凯帅<br />
	剪辑： 麦子善<br />
	音乐： 赵增熹<br />
	摄影： 余静萍</p>
<p>
	<br />
	剧情简介</p>
<p>
	　　《倾城之泪》由三颗泪滴组成。三对恋人分别讲述了爱有时间界限、重拾爱情梦想和当爱遭遇生离死别的三段凄美爱情故事。故事的主角对爱都坚信不移， 他们各以不同的形式诠释着爱，演绎人生的悲欢离合。<br />
	　　第一滴泪（血之泪）：游乐是个缺乏生活情趣的工作狂，却突然被查出患有重病。在医院里，自暴自弃的他遇见了那些让他无法理解的乐天病人，见识到他们那些不可能实现的美丽梦想。直至游乐遇见给力妹，在她的鼓励下，他终于开始渐渐走出阴霾，重拾阳光。而他和她之间，也因为许许多多感动，而渐生好感，成为相濡以沫的恋人。然而，在他们许下山盟海誓的诺言，相约好一同<a href="http://www.dailiv.com/" style="color: rgb(0,0,0); text-decoration: none">在线代理</a>慨然赴死之时，她却突然背叛盟约，要去做一个贪生怕死的人，想谋求生的机会&hellip;&hellip;<br />
	　　第二滴泪（梦之泪）：濒临破产的信义音乐学院，是陈校长一生的<a href="http://www.anzhuo4.com/" style="color: rgb(0,0,0); text-decoration: none">安卓</a>事业，亦是已故的陈师母惦念不忘的牵挂。事到如今，也只有找到以前的弟子&mdash;&mdash;已经是国际知名音乐人杨琳，开一场音乐会，来拯救学校。为了劝她出山，曾经的信义四虎纷纷出山，各显神通，特别是杨琳过去的绯闻男友丁大可，用尽浑身解数。让人意想不到的是，杨琳因发生事故而导致听力障碍，她根本演奏不了琴。最终在小提琴天后姚珏的帮助下，终于将杨琳请出山来。然而，接踵而来的困难却让风雨飘摇的信义步履蹒跚，杨琳与丁大可的爱情也在这重重阻碍中不断磨砺着。他们的音乐梦想到底能否实现<a href="http://www.dailiv.com/" style="color: rgb(0,0,0); text-decoration: none">在线代理</a>？这段夹杂着梦想与责任的爱情又将走向何方？<br />
	　　第三滴泪（雨之泪）：上海滩著名公关公司老总陈升，在拍完婚纱照的当天，遭遇歹徒抢劫，痛失爱人。没有人知道陈升到底如何发迹，也没有人知道他的妻子是怎样的一个人。而当陈升宣布将如期举行婚礼之时，更是震惊整个上海滩，原来一切有内情&hellip;&hellip;　</p>
<p>
	<br />
	◎影片截图</p>

<p>
	<img src="http://img165.poco.cn/mypoco/myphoto/20111223/11/56643687201112231138452471768182350_001.jpg" style="width: 600px; height: 375px" /></p>
<p>
	<img src="http://img165.poco.cn/mypoco/myphoto/20111223/11/56643687201112231138452471768182350_004.jpg" style="width: 600px; height: 375px" /></p>
<p>
	<img src="http://img165.poco.cn/mypoco/myphoto/20111223/11/56643687201112231138452471768182350_000.jpg" style="width: 600px; height: 375px" /></p>
<p>
	<img src="http://img165.poco.cn/mypoco/myphoto/20111223/11/56643687201112231138452471768182350_002.jpg" style="width: 600px; height: 375px" /></p>
<p>
	<img src="http://img165.poco.cn/mypoco/myphoto/20111223/11/56643687201112231138452471768182350_003.jpg" style="width: 600px; height: 375px" /></p>
<p>
	&nbsp;<img src="http://img165.poco.cn/mypoco/myphoto/20120302/21/56643687201203022154262381358788565_001.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 254px; border-top: 0px solid; border-right: 0px solid" /></p>
<p>
	<img src="http://img165.poco.cn/mypoco/myphoto/20120302/21/56643687201203022154262381358788565_000.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 254px; border-top: 0px solid; border-right: 0px solid" /></p>
<p>
	<img src="http://img165.poco.cn/mypoco/myphoto/20120302/21/56643687201203022154262381358788565_002.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 254px; border-top: 0px solid; border-right: 0px solid" /></p>
<p>
	<img src="http://img165.poco.cn/mypoco/myphoto/20120302/21/56643687201203022154262381358788565_003.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 254px; border-top: 0px solid; border-right: 0px solid" /></p>


<p>
	下载地址：</p>
<table bgcolor="#0099cc" border="0" cellpadding="7" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<anchor></anchor><a href="ftp://dy44:piaohua@dy44.piaohua.com:2421/飘花电影piaohua.com倾城之泪高清BD国语中字.rmvb ">ftp://dy44:piaohua@dy44.piaohua.com:2421/飘花电影piaohua.com倾城之泪高清BD国语中字.rmvb </a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#0099cc" border="0" cellpadding="7" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<anchor></anchor><a href="ftp://dy44:piaohua@dy44.piaohua.com:2943/飘花电影piaohua.com倾城之泪高清1280版BD国语中字.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2943/飘花电影piaohua.com倾城之泪高清1280版BD国语中字.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15Q5T0-13339.jpg{/dede:field}
