<?php
$z[0]=Array("field","驯龙记/驯龙高手[BD中英双字1024",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","驯龙记/驯龙高手[BD中英双字1024/1280高清高清版]迅雷下载、免费下载，驯龙记/驯龙高手[BD中英双字1024/1280高清高清版]Gvod高清在线播放，剧情介绍等。",73,259);
$z[1][4]['name']="description";
$z[2]=Array("field","驯龙记/驯龙高手[BD中英双字1024/1280高清高清版]",261,345);
$z[2][4]['name']="title";
$z[3]=Array("field","",347,386);
$z[3][4]['name']="writer";
$z[4]=Array("field","",388,427);
$z[4][4]['name']="source";
$z[5]=Array("field","2012-04-05",429,479);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",481,518);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://6e:6e@m1.eee4.cc:1552/【3E电影院www.eee4.org】驯龙高手DVD中英双字.rmvb\" target=\"_blank",520,651);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MOB9430-19229.jpg",653,736);
$z[8][4]['name']="litpic";

?>