{dede:field name='keywords'}杀妻二人组HD高清国语中字1024/1{/dede:field}
{dede:field name='description'}杀妻二人组HD高清国语中字1024/1280高清迅雷下载、免费下载，杀妻二人组HD高清国语中字1024/1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}杀妻二人组HD高清国语中字1024/1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-09-12{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20110910/16/62564813201109101608427532476832903_000.jpg" style="width: 450px; height: 640px" /></p>
<p>
	◎译　　名　杀妻二人组<br />
	◎片　　名　100 Ways To Murder Your Wife<br />
	◎年　　代　1986<br />
	◎地　　区　中国香港<br />
	◎类　　别　喜剧<br />
	◎语　　言　普通话<br />
	◎字　　幕　中文<br />
	◎IMDB评分 5.8/10 (43 votes)<br />
	◎文件格式　XviD + AC3<br />
	◎视频尺寸　1024 x 576<br />
	◎文件大小　1.3G<br />
	◎片　　长　91 Min<br />
	◎导　　演　钟镇涛 Kenny Bee<br />
	◎主　　演　钟镇涛 Kenny Bee .....阿B Roberto<br />
	　　　　　　周润发 Yun-Fat Chow .....阿发 Football Fat (as Chow Yun Fat)<br />
	　　　　　　王祖贤 Joey Wong .....阿发太太 Hsiao Hsien<br />
	　　　　　　梅艳芳 Anita Mui .....阿B太太 Fang<br />
	　　　　　　王晶 Jing Wong .....Fat<br />
	　　　　　　午马 Ma Wu .....Ma<br />
	　　　　　　陈友 Anthony Chan .....Chen Chih-Tao<br />
	　　　　　　成奎安 Fui-On Shing .....Soccer Player</p>
<p>
	<br />
	&nbsp;</p>

<p>
	<br />
	◎简　　介　</p>

<p>
	<br />
	　　阿B（钟镇涛）、阿发（周润发）都是足球好手。阿发来自大马，有个美丽的太太（王祖贤），阿B的太太（梅艳芳）则是个脾气暴燥的女人，她时常埋怨阿B没有出息，而且还常常当众奚落他，使阿B面子尽失，自尊心受到伤害。一次阿B受可太太的气，到酒吧饮闷酒，遇到由大马来港的阿发，阿发也是不满太太对其他的男人太热情，还怀疑她红杏出墙。阿B、阿发互吐心事后，更觉同病相怜，大家酒醉后竟然发起杀妻之念，二人更密谋出不同的杀妻方法，其中尽情地发挥了小气男人的妒忌妻子的梦幻式惩治杀妻方法，可谓洋洋大观，笑话连篇&hellip;&hellip;</p>
<p>
	幕后：<br />
	　　乍一看本片的演员阵容，确实是无限强劲，然而事实上本片却是一个实实在在的票友戏，是由当年的戏剧红小生万梓良编剧，并由兼任男主角的钟镇涛执导，剧情夸张而疯癫，笑料不断，倒也算是拼出个热闹场面。全片走的喜剧风格并无新意，只是几位当红艺人的跨刀行为却让人好奇，所以也吸引了众多观者入场，一上映倒也还算成功，拿下了一千四百多万的票房。故事以略带夸张的尖刻手法嘲讽小丈夫的矛盾心理，迎合了八十年代中期都市狂想的大潮流，是八十年代中期城市喜剧中的从众之作，算是不功不过。</p>
<p>
	&nbsp;<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20110911/23/62564813201109112348363571118514181_002.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20110911/23/62564813201109112348363571118514181_001.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20110911/23/62564813201109112348363571118514181_000.jpg" style="width: 720px; height: 405px" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="&#13;&#10;ftp://dy125:piaohua@dy125.piaohua.com:3016/飘花电影piaohua.com杀妻二人组HD高清国语中字1024分辨率.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:3016/飘花电影piaohua.com杀妻二人组HD高清国语中字1024分辨率.rmvb </a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:1535/飘花电影piaohua.com杀妻二人组HD国语中字1280高清.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:1535/飘花电影piaohua.com杀妻二人组HD国语中字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1C0R0-11M9.jpg{/dede:field}
