{dede:field name='keywords'}雷斯特雷波【BD中英双字1024x576{/dede:field}
{dede:field name='description'}雷斯特雷波【BD中英双字1024x576高清版】迅雷下载、免费下载，雷斯特雷波【BD中英双字1024x576高清版】Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}雷斯特雷波【BD中英双字1024x576高清版】{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2010-12-11{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://5e:5e@m1.3edyy.com:1568/【3E看看www.3ekk.com】雷斯特雷波DVD中英双字.rmvb" target=_blank><FONT color=#0058b0>ftftp://5e:5e@m1.3edyy.com:1568/【3E看看www.3ekk.com】雷斯特雷波DVD中英双字.rmvb</FONT></A></TD></TR></TBODY></TABLE><BR><FONT color=#ff0000 size=2><STRONG>[下载地址]：<IMG border=0 src="httftp://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MP645950-230T.jpg{/dede:field}
