{dede:field name='keywords'}日瓦戈医生[BD中英双字1280x720{/dede:field}
{dede:field name='description'}日瓦戈医生[BD中英双字1280x720高清版]迅雷下载、免费下载，日瓦戈医生[BD中英双字1280x720高清版]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}日瓦戈医生[BD中英双字1280x720高清版]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2010-05-14{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://5e:5e@d8.3edyy.com:157/【3E电影院www.eee4.cc】日瓦戈医生BD中英双字1280x720高清版.rmvb" target="_blank{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MQ344b0-12Z4.jpg{/dede:field}
