<?php
$z[0]=Array("field","日瓦戈医生[BD中英双字1280x720",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","日瓦戈医生[BD中英双字1280x720高清版]迅雷下载、免费下载，日瓦戈医生[BD中英双字1280x720高清版]Gvod高清在线播放，剧情介绍等。",72,238);
$z[1][4]['name']="description";
$z[2]=Array("field","日瓦戈医生[BD中英双字1280x720高清版]",240,314);
$z[2][4]['name']="title";
$z[3]=Array("field","",316,355);
$z[3][4]['name']="writer";
$z[4]=Array("field","",357,396);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-05-14",398,448);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",450,487);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://5e:5e@d8.3edyy.com:157/【3E电影院www.eee4.cc】日瓦戈医生BD中英双字1280x720高清版.rmvb\" target=\"_blank",489,635);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MQ344b0-12Z4.jpg",637,719);
$z[8][4]['name']="litpic";

?>