{dede:field name='keywords'}同一天的生活/浮生一日BD中英双{/dede:field}
{dede:field name='description'}同一天的生活/浮生一日BD中英双字1280高清2011纪录片迅雷下载、免费下载，同一天的生活/浮生一日BD中英双字1280高清2011纪录片Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}同一天的生活/浮生一日BD中英双字1280高清2011纪录片{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-11-13{/dede:field}
{dede:field name='body'}<p>
	<img alt="" height="888" src="http://www.hotimg.com/direct/UYXyTAy.jpg" style="cursor: pointer" width="600" /><br />
	<br />
	◎译　　名　同一天的生活/浮生一日/一日人生(港)/活在这一天(台)<br />
	◎片　　名　Life in a Day<br />
	◎年　　代　2011<br />
	◎国　　家　美国/英国<br />
	◎类　　别　纪录片/剧情<br />
	◎语　　言　英语<br />
	◎字　　幕　中英双字幕<br />
	◎IMDB评分 8.1/10 (1,642 votes)<br />
	◎文件格式　Rmvb<br />
	◎视频尺寸　1280 x 720<br />
	◎文件大小　1.07GB<br />
	◎片　　长　91 Mins<br />
	◎导　　演　凯文&middot;麦克唐纳 Kevin Macdonald<br />
	　　　　　　Natalia Andreadis ....(collaborating director)<br />
	　　　　　　Joseph Michael ....(co-director)<br />
	◎主　　演　Cindy Baer ....Herself<br />
	　　　　　　Moica ....Herself (as Mojca Brecelj)<br />
	　　　　　　Caryn Waechter ....Herself<br />
	　　　　　　Hiroaki Aikawa ....Himself<br />
	　　　　　　Drake Shannon ....Himself<br />
	　　　　　　David Jacques ....Himself<br />
	　　　　　　Bob Liginski Jr. ....Himself<br />
	　　　　　　Cec Marquez ....Himself<br />
	　　　　　　Ayman El Gazwy ....Himself<br />
	　　　　　　Ranja Kamal ....Herself<br />
	　　　　　　Ashley Meeks ....Herself<br />
	<br />
	◎简　　介　<br />
	<br />
	　　两位奥斯卡金像级大导演联同全球最大影片分享网站YouTube破天荒合作,并得全球网民掌镜,在2010年7月24日,以&ldquo;爱&rdquo;和&ldquo;恐惧&rdquo;为题,集体创作了愈80,000段,共4,500小时的影片。当中影片来自世界各地、人、事,并演绎了不同的人活在2010.7.24这一天,那许多满载悲喜、失落与幸褔的故事:从繁华的大城巿到素被世人遗忘的乡野,从驾名车的富豪到街边的擦鞋童,从寄人篱下的生活到色彩缤纷的狂欢世界,影像情感丰富,极具感染力。<br />
	<br />
	　　这万千来自五大洋七大洲的创作,经过金像班底的鬼斧神工,如今终于跃上大银幕,让全人类乘着八万多个趣味盎然的镜头,见证这时间囊里的一日人生。<br />
	<br />
	一句话评论<br />
	<br />
	　　每个观众都能从中看到自己的生活细节。 &mdash;&mdash;《名利场》<br />
	<br />
	　　这部被评为PG-13的纪录片和我们的生活一样,有洗脸刷牙,也有不堪面对的生与死。 &mdash;&mdash;《纽约时报》<br />
	<br />
	◎影片截图<br />
	<br />
	<img alt="" height="337" src="http://img.album.pchome.net/54/83/85/75/1321037937903910db8b1dcee6c48ffcb9abe79c24.jpg" style="cursor: pointer" width="600" /><br />
	<img alt="" height="337" src="http://img.album.pchome.net/54/83/85/75/13210379378a3760e540089a846230e69ba1175884.jpg" style="cursor: pointer" width="600" /><br />
	<img alt="" height="337" src="http://img.album.pchome.net/54/83/85/75/1321037937696b3c1ed7c8c63bf284cec1791e1270.jpg" style="cursor: pointer" width="600" /><br />
	&nbsp;</p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2067/飘花电影piaohua.com浮生一日BD中英双字1280高清.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2067/飘花电影piaohua.com浮生一日BD中英双字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1C4H60-142J.jpg{/dede:field}
