{dede:field name='keywords'}天崩地裂/烈焰狂峰/山崩地裂/但{/dede:field}
{dede:field name='description'}天崩地裂/烈焰狂峰/山崩地裂/但丁峰迅雷下载、免费下载，天崩地裂/烈焰狂峰/山崩地裂/但丁峰Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}天崩地裂/烈焰狂峰/山崩地裂/但丁峰{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2008-11-29{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://d86:d86@ftp.eee4.com:1501/[3E电影站www.eee4.com]天崩地裂CD1.rmvb" target="_blank{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MPV2640-19301.jpg{/dede:field}
