{dede:field name='keywords'}第32届十大中文金曲颁奖音乐会迅{/dede:field}
{dede:field name='description'}第32届十大中文金曲颁奖音乐会迅雷下载、免费下载，第32届十大中文金曲颁奖音乐会Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}第32届十大中文金曲颁奖音乐会{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2010-02-01{/dede:field}
{dede:field name='body'}<P><IMG src="/uploads/allimg/c120524/133N425433F-20Y55.jpg"></P>
<P>&nbsp;　　作为年度四大颁奖典礼，十大中文金曲最后出场，却依然未能逃过之前被唾骂的命运，一场众星云集的颁奖盛典却还是逃不开无线自己的小打小闹，对“自家人”过分宠爱已经完全降低了颁奖礼的公信力，此次收官之盛典也同样落得个画蛇添足。只是前几次缺席的方大同意外获奖，似乎让无线电影与四大唱片公司间的版税风波在最后这场颁奖礼上有了和缓之意；而在上一场“十大劲歌金曲颁奖”中颗粒无收的陈奕迅尽管不负众望拿到五个不同奖项，但之前已对“传媒大奖”意兴阑珊的陈奕迅今晚依然败在容祖儿的石榴裙下，不知双手已经捧不了奖杯的他对于耿耿于怀的最终大奖是否能真的释怀？</P>
<P align=center><IMG style="CURSOR: hand" alt=点击浏览下一张 src="/uploads/allimg/c120524/133N42545120-212S3.jpg" OLDSRC="W020100131503475191160.jpg/"></P>
<P class=pictext align=center>陈奕迅从张学友手上接过奖项，表现兴奋</P>
<P>　　第三十二届十大中文金曲颁奖典礼完满落幕。当最后的“传媒大奖”，从原来的大热人选陈奕迅的手上，溜到了容祖儿的手中。</P>
<P>　　以下是获奖名单：</P>
<P>　　十大中文金曲</P>
<P>　　容祖儿《搜神记》</P>
<P>　　陈奕迅《七百年后》</P>
<P>　　陈柏宇《你瞒我瞒》</P>
<P>　　海鸣威泳儿《我的回忆不是我的》</P>
<P>　　杨千嬅《原来过得很快乐》</P>
<P>　　王菀之《月亮说》</P>
<P>　　卫兰《就算世界无童话》</P>
<P>　　谢安琪《年度之歌》</P>
<P>　　古巨基《地球很危险》</P>
<P>　　MR.《如果我是陈奕迅》</P>
<P>　　优秀流行国语歌曲</P>
<P>　　方大同《三人游》</P>
<P>　　优秀流行歌手大奖</P>
<P>　　古巨基、王菀之、容祖儿、陈奕迅、张敬轩、谢安琪、蔡卓妍、卫兰、G.E.M.、林峰、杨千嬅、方大同、Mr.</P>
<P>　　最优秀流行男歌手</P>
<P>　　陈奕迅</P>
<P>　　最优秀流行女歌手</P>
<P>　　容祖儿</P>
<P>　　全国最佳歌手奖</P>
<P>　　组合：苏打绿</P>
<P>　　男歌手：陈奕迅</P>
<P>　　女歌手：容祖儿</P>
<P>　　Cash最佳创作歌手奖</P>
<P>　　侧田</P>
<P>　　全年最佳进步奖</P>
<P>　　金奖: g.e.m</P>
<P>　　银奖: 钟舒漫</P>
<P>　　铜奖: rubber band</P>
<P>　　全年最高销量女歌手</P>
<P>　　容祖儿</P>
<P>　　全年最高销量男歌手</P>
<P>　　陈奕迅</P>
<P>　　全年最高销量组合</P>
<P>　　Mr.</P>
<P>　　全国最佳中文歌曲奖</P>
<P>　　张敬轩《yes and no》</P>
<P>　　最有前途新人奖</P>
<P>　　金奖: 徐子珊</P>
<P>　　银奖: 周子扬</P>
<P>　　铜奖: 王子轩</P>
<P>　　全球华人至尊金曲奖</P>
<P>　　陈奕迅《七百年后》</P>
<P>　　四台联颁大奖 传媒大奖</P>
<P>　　歌手：容祖儿</P>
<P>　　作曲: 柳重言 雷颂德</P>
<P>　　作词: 林夕</P>
<P>　　金针奖</P>
<P>　　陈百强</P><BR><BR>[下载地址]：<IMG src="/uploads/allimg/c120524/133N295542P-105L6.jpg" border=0><BR>
<TABLE style="BORDER-RIGHT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; BORDER-BOTTOM: #cccccc 1px dotted" cellSpacing=0 cellPadding=6 width="95%" align=center border=0>
<TBODY>
<TR>
<TD style="WORD-WRAP: break-word" bgColor=#fdfddf>ftp://3e:3e@www2.3edyy.com:3901/【3E电影院www.3edyy.com】第32届十大中文金曲颁奖音乐会.rmvb</TD></TR></TBODY></TABLE>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120524/133N42545510-2224c.jpg{/dede:field}
