{dede:field name='keywords'}纳瑞宣国王传奇上下合集BD1280高{/dede:field}
{dede:field name='description'}纳瑞宣国王传奇上下合集BD1280高清迅雷下载、免费下载，纳瑞宣国王传奇上下合集BD1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}纳瑞宣国王传奇上下合集BD1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-16{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://disk.cmct.cc/UpLoadFiles/2012/5/12/14/hdcmct2011201251214296ne11S.jpg" style="width: 700px; height: 879px" /><img alt="" src="http://disk.cmct.cc/UpLoadFiles/2012/5/12/14/hdcmct20112012512142942PH228.jpg" style="width: 700px; height: 880px" /></p>
<p>
	◎译　　名　纳瑞宣国王传奇/纳雷宋国王/泰王纳黎萱<br />
	◎片　　名　Legend of King Naresuan: Hostage of Hongsawadi<br />
	◎年　　代　2007<br />
	◎国　　家　泰国<br />
	◎类　　别　动作/战争/剧情/历史<br />
	◎IMDB评分 &nbsp;7.2/10 from 222 users<br />
	◎IMDB链接 &nbsp;<a class="faqlink" href="http://www.imdb.com/title/tt0817940/">http://www.imdb.com/title/tt0817940/</a><br />
	◎语　　言　泰语 &nbsp;<br />
	◎导　　演　查崔查勒姆&middot;尧克尔 Chatrichalerm Yukol<br />
	◎主　　演　Wanchana Sawatdee &nbsp;....King Naresuan<br />
	　　　　　　加亚纳马&middot;诺帕柴 Jayanama Nopachai<br />
	　　　　　　Thaksawn Phaksukjaroen<br />
	　　　　　　Intira Jaroenpura &nbsp;....Lerkin<br />
	　　　　　　索拉朋&middot;切特里 Sorapong Chatree<br />
	　　　　　　Sompob Benjathikul &nbsp;....Burengnong<br />
	　　　　　　察猜 Chatchai Plengpanich<br />
	　　　　　　Jukrit Ammarat &nbsp;....Nonthabureng<br />
	　　　　　　Winthai Suvaree<br />
	　　　　　　Prapadon Suwannabang<br />
	　　　　　　Komgrit Intrasawan<br />
	　　　　　　Kowit Wattanakul<br />
	　　　　　　Supakorn Srisawat &nbsp;....Khun Det<br />
	　　　　　　Chumphorn Thepphithak<br />
	　　　　　　Suchada Chekly<br />
	　　　　　　Jirayu La-ongmanee<br />
	　　　　　　Napatkorn Mitr-em<br />
	　　　　　　Ampha Phoosit<br />
	　　　　　　Aphiradee Phuaphutanont<br />
	　　　　　　Khwannapa Reuangsri<br />
	　　　　<br />
	◎简　　介　<br />
	<br />
	　　本片描写了泰国最具传奇色彩的国王纳瑞宣的一生故事，从1555年出生开始，到1605年他的统治结束。他1592年在素攀武里进行的的那次卓越的战斗中，杀死了缅甸王子，摆脱缅甸人的统治。泰国人民为了纪念他的丰功伟绩，在阿犹他亚Ayutthaya(泰国古都，也称大城，曼谷北部，相当于泰国的&ldquo;长安&rdquo;)建立了72米高的佛塔。<br />
	<br />
	<br />
	◎幕　　后<br />
	<br />
	　　泰国片近几年很想进取，可由于制作方的乏力，一些类似《生还者》之流的烂恐怖片与及&ldquo;托尼假&rdquo;动作系列，都只注重形式，而在剧本方面溃败不堪，这部号称史诗的大片，战争场面宏大，一点也不次于【赤壁】。泰国能拍出这种场面的电影来，还是叫人刮目相看的。</p>

<p>
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120514/20/62564813201205142056013562968494364_003.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120514/20/62564813201205142056013562968494364_002.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120514/20/62564813201205142056013562968494364_001.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120514/20/62564813201205142056013562968494364_000.jpg" style="width: 720px; height: 405px" /></p>
<p>
	<br />
	<br />
	&nbsp;</p>
<p>
	【下载地址】</p>
<table bgcolor="#0099cc" border="0" cellpadding="10" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.net" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy125:piaohua@dy125.piaohua.com:8067/飘花电影pioahua.com纳瑞宣国王传奇上BD中字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:8067/飘花电影pioahua.com纳瑞宣国王传奇上BD中字1280高清.rmvb</a></td>
		</tr>
		<tr>
		</tr>
	</tbody>
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy125:piaohua@dy125.piaohua.com:8070/飘花电影piaohua.com纳瑞宣国王传奇下BD中字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:8070/飘花电影piaohua.com纳瑞宣国王传奇下BD中字1280高清.rmvb</a></td>
		</tr>
		<tr>
		</tr>
	</tbody>
</table>
<br />{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1494Y50-225V.jpg{/dede:field}
