{dede:field name='keywords'}机动战士高达：F91BD高清迅雷下{/dede:field}
{dede:field name='description'}机动战士高达：F91BD高清迅雷下载、免费下载，机动战士高达：F91BD高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}机动战士高达：F91BD高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-10-05{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="/uploads/allimg/c120525/133O0461H20-T394.jpg" style="width: 400px; height: 529px" /></p>
<p>
	中文名： 机动战士高达：F91<br />
	英文名： Mobile Suit Gundam F91<br />
	导&nbsp;&nbsp; 演： Yoshiyuki Tomino<br />
	类&nbsp;&nbsp; 型： 动画<br />
	地&nbsp;&nbsp; 区： 日韩<br />
	发&nbsp;&nbsp; 行： 1991<br />
	评&nbsp;&nbsp; 分：&nbsp; 7.20<br />
	规&nbsp;&nbsp; 格： 1024*576</p>
<p>
	<br />
	U.C.0106年，在使地球圈的混乱局面终于平息下来后，联邦政府决定再度开始新殖民卫星的建设。这时，由宇宙住民中政坛与商界名门所鼓吹的宇宙贵族主义，开始在殖民卫星中出现。0112年原型机型GUNDAM RX-F91高达正式完成。<br />
	　　U.C.0123年，殖民卫星Frontier Side遭到自称C.V.(死亡先锋)的谜之MS部队袭击，在避难的人群中有GUNDAM F91开发者之一莫妮卡&middot;阿诺博士的一对子女西布克、莉丝，以及罗纳家族的次女贝拉&middot;罗纳，又名塞茜莉&middot;费亚查尔德，罗纳家族是C.V.的领导者，提倡贵族主义并欲统一殖民卫星，建立「宇宙巴比伦空中花园」。<br />
	&nbsp; 详细介绍...</p>
<p>
	U.C.0106年，在使地球圈的混乱局面终于平息下来后，联邦政府决定再度开始新殖民卫星的建设。这时，由宇宙住民中政坛与商界名门所鼓吹的宇宙贵族主义，开始在殖民卫星中出现。0112年原型机型GUNDAM RX-F91高达正式完成。<br />
	　　U.C.0123年，殖民卫星Frontier Side遭到自称C.V.(死亡先锋)的谜之MS部队袭击，在避难的人群中有GUNDAM F91开发者之一莫妮卡&middot;阿诺博士的一对子女西布克、莉丝，以及罗纳家族的次女贝拉&middot;罗纳，又名塞茜莉&middot;费亚查尔德，罗纳家族是C.V.的领导者，提倡贵族主义并欲统一殖民卫星，建立「宇宙巴比伦空中花园」。<br />
	　　C.V.开始进攻Frontier 2、3并将其制压。因为缺少人手，西布克他们被拉人联邦军帮忙，也因此发现其母亲开发的F91亦在此方舟内(采用了生物电脑的F91，事实上是专为NEW TYPE设计的)。莉丝还替机械师解答了母亲在F91生物电脑中留下的谜题，这使得每启动一次就会出故障的F91终于被完成了，又因&ldquo;宇宙方舟&rdquo;上只得比路基德一名驾驶员，故西布克被推上F91的驾驶舱，他的NEW TYPE能力也开始渐渐地觉醒了。另一方面，回到罗纳家的塞茜莉受到祖父迈兹亚的热烈欢迎，并想让她成为宇宙巴比伦空中花园的女王。被祖父一番剖白打动的塞茜莉剪去长发打算留在罗纳家，并开始学习驾驶MS，教她驾驶MS的萨比尼是 C.V.中最强的&ldquo;黑之部队&rdquo;队长，她亦发现塞茜莉也是NEW TYPE。<br />
	　　C.V.的最指挥官铁假面，其真面目是塞茜莉的父亲，原名卡罗佐，乃是强化人类，他在Frontier 4发表宇宙巴比伦宣言。而西布克亦趁机潜入罗纳家的别墅，欲带走塞茜莉未果，反而连累了自己的父亲。回到&ldquo;宇宙方舟，和其分别多时的母亲相遇，不免责怪其母抛下他和莉丝埋头于工作中。当西布克和他的母亲尽释前嫌时，塞茜莉的母亲娜蒂娅亦逼着希奥带她去见自己的女儿，并要塞茜莉离开罗纳家。不听母亲劝告的塞茜莉扬长而去，此时娜蒂娅发现站在她身后的希奥己被铁假面所杀，紧接着自己也被C.V.的士兵抓了起来。<br />
	　　不知情的塞茜莉与萨比尼一起奉命佯攻Frontier I，而铁假面则带着他的舰队占领Frontier I的能量供应装置替其秘密武器&ldquo;巴库&rdquo;提供能源。萨比尼的部下安娜玛丽因嫉妒其上司对塞茜莉的过分关怀而倒戈，投奔&ldquo;宇宙方舟&rdquo;，和西布克等人一同迎击C.V.的&ldquo;黑之部队&rdquo;。当安娜玛丽的MS被萨比尼击败后，西布克亦与塞西莉的MS交锋，最后两人认出了对方，塞茜莉回到西布克的身边。&ldquo;黑之部队&rdquo;撤退后不久，铁假面的母舰上便放出大量&ldquo;巴库&rdquo;进入殖民卫星中。&ldquo;巴库（BUG）&rdquo;是一种专门用来杀人的兵器，它能感应人的波长而上天入地将卫星中的居民全部杀死!西布克，塞茜莉和比路基德三人奋力抵抗&ldquo;巴库&rdquo;，却没有见效，比路基德当场阵亡。西布克和塞茜莉设法将&ldquo;巴库&rdquo;吸引到狭窄的通道中令其相撞。回到母舰上的萨比尼，知晓铁假面瞒着他和总帅迈兹亚制造了&ldquo;巴库&rdquo;并企图以此将月球和地球的居民全都抹杀之事后，立刻将铁假面的副官处弄，并令余下的C．V部队撤离Frontier I。<br />
	　　察觉到塞茜莉背叛的铁假面恼羞成怒，驾驶着最新的MA「拉普雷西亚」追击塞茜莉和西布克。F91和塞茜莉驾驶的比基纳&middot;基纳在拉普雷西亚的强大力量下毫无还手之力，比基纳&middot;基纳被击毁、塞茜莉被铁假面抓出驾驶舱抛向茫茫的宇宙。愤怒的西布克发挥出F91真正的力量，使出有质量的残像&ldquo;分身&rdquo;将铁面打打倒。战斗结束后，及时逃出Frontier I 的宇宙方舟缓缓驶向F91，萨比尼见宇宙方舟上搭载着大量的难民、又目睹到西布克失魂落魄地四处寻找塞茜莉的样子，便放过他们带着自己的部下悄悄离去了。西布克在其母亲的指点下，运用NEW TYPE的感知能力，最终寻回了在无尽空间中飘荡的塞茜莉。</p>
<p>
	<br />
	<img alt="" src="/uploads/allimg/c120525/133O0461X50-a013.jpg" style="width: 720px; height: 405px" /><img alt="" src="/uploads/allimg/c120525/133O0461b60-105154.jpg" style="width: 720px; height: 405px" /><img alt="" src="/uploads/allimg/c120525/133O04620P-11b40.jpg" style="width: 720px; height: 405px" />&nbsp;</p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="/uploads/allimg/c120524/133N2Z4FF-102231.jpg" />&nbsp;&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy125:piaohua@dy125.piaohua.com:6041/飘花电影piaohua.com机动战士高达F91BD中字1024高清.rmvb</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O04621T0-1239E.jpg{/dede:field}
