<?php
$z[0]=Array("field","绿区/绿色地带/关键指令/翡翠城",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","绿区/绿色地带/关键指令/翡翠城的皇家生活迅雷下载、免费下载，绿区/绿色地带/关键指令/翡翠城的皇家生活Gvod高清在线播放，剧情介绍等。",72,244);
$z[1][4]['name']="description";
$z[2]=Array("field","绿区/绿色地带/关键指令/翡翠城的皇家生活",246,323);
$z[2][4]['name']="title";
$z[3]=Array("field","",325,364);
$z[3][4]['name']="writer";
$z[4]=Array("field","",366,405);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-04-02",407,457);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",459,496);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://3e:3e@m1.3edyy.com:1495/【3E电影院www.eee4.cc】绿色地带DVD中字.rmvb\" target=_blank>ftftp://3e:3e@m1.3edyy.com:1495/【3E电影院www.eee4.cc】绿色地带DVD中字.rmvb</A></TD></TR></TBODY></TABLE><FONT color=#ff0000 size=2><STRONG><BR>2010年欧美最新惊险战争动作大片《绿色地带/关键指令/绿区》BD中字1024x576高清版无水印 [下载地址]：<IMG border=0 src=\"httftp://www.3edyy.com/templets/img/down.jpg",498,928);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MP610610-14059.jpg",930,1014);
$z[8][4]['name']="litpic";

?>