<?php
$z[0]=Array("field","盖茨堡之役720P,1280*720迅雷下",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","盖茨堡之役720P 1280*720迅雷下载、免费下载，盖茨堡之役720P 1280*720Gvod高清在线播放，剧情介绍等。",72,212);
$z[1][4]['name']="description";
$z[2]=Array("field","盖茨堡之役720P 1280*720",214,275);
$z[2][4]['name']="title";
$z[3]=Array("field","",277,316);
$z[3][4]['name']="writer";
$z[4]=Array("field","",318,357);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-07-29",359,409);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",411,448);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://dy125:piaohua@dy125.piaohua.com:1030/飘花电影下载站www.piaohua.com盖茨堡之役720p.mkv",450,579);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MP511Q0-4K63.jpg",581,663);
$z[8][4]['name']="litpic";

?>