{dede:field name='keywords'}晚秋HD高清迅雷下载，免费下载，{/dede:field}
{dede:field name='description'}晚秋HD高清迅雷下载、免费下载，晚秋HD高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}晚秋HD高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-03-27{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://i.minus.com/iNqSMuTSwwWiI.jpg" style="width: 678px; height: 971px" /></p>
<p>
	◎片　　 名　晚秋 &#47564;&#52628;<br />
	◎译　 　名　Late Autumn / Full Autumn<br />
	◎上 &nbsp; &nbsp; &nbsp; 映 &nbsp; 2011-02-17(韩国) / 2011-06-17(美国) / 2012-03-23(中国大陆)<br />
	◎国　　 家　韩国 / 美国 / 香港<br />
	◎类　　 别　剧情 / 爱情<br />
	◎语　　 言　英语 / 韩语 / 汉语普通话<br />
	◎IMDB评分 &nbsp; 7.0/10 (128 votes)<br />
	◎IMDB链接 &nbsp; <a href="http://www.imdb.com/title/tt1542482" target="_blank">http://www.imdb.com/title/tt1542482</a><br />
	◎片　　 长　115 Min<br />
	◎编 &nbsp; &nbsp; &nbsp; 剧 &nbsp; 金泰勇<br />
	◎导　 　演　金泰勇<br />
	◎主　　 演 &nbsp; 玄 &nbsp; 彬<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 汤 &nbsp; 唯<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 金俊成<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 詹姆斯&middot;C&middot;伯恩斯<br />
	◎简 &nbsp; &nbsp; &nbsp; 介<br />
	<br />
	&nbsp; &nbsp; &nbsp;《晚秋》根据李满熙导演1966年的同名电影改编而成，影片以美国西雅图为背景，讲述两名男女在异国他乡的爱情故事。本在监狱服刑的安娜（汤唯 Wei Tang 饰）因母亲过世获得三天假期，七年来首次踏上归家之路，并于长途汽车上邂逅了勋（玄彬 Bin Hyeon 饰）。不够车钱的勋用手表做抵押借了安娜的钱，约定到西雅图再见......</p>
<p>
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120326/15/62564813201203261530381081630757344_002.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120326/15/62564813201203261530381081630757344_001.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120326/15/62564813201203261530381081630757344_000.jpg" style="width: 720px; height: 405px" /><br />
	<br />
	&nbsp;</p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="&#13;&#10;ftp://dy125:piaohua@dy125.piaohua.com:7775/飘花电影piaohua.com晚秋HD中字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:7775/飘花电影piaohua.com晚秋HD中字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15SbP-1O52.jpg{/dede:field}
