{dede:field name='keywords'}赌侠III之上海滩赌圣HD中字1280/{/dede:field}
{dede:field name='description'}赌侠III之上海滩赌圣HD中字1280/1024高清版迅雷下载、免费下载，赌侠III之上海滩赌圣HD中字1280/1024高清版Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}赌侠III之上海滩赌圣HD中字1280/1024高清版{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-02-23{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://dy241:xiaobajie@222.187.221.241:2040/小八戒电影xiaobajie.com赌侠III之上海滩赌圣国粤双语中字1280高清.mkv" target="_blank{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MQ2b020-11095.jpg{/dede:field}
