{dede:field name='keywords'}黎巴嫩[DVD中英双字]迅雷下载，{/dede:field}
{dede:field name='description'}黎巴嫩[DVD中英双字]迅雷下载、免费下载，黎巴嫩[DVD中英双字]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}黎巴嫩[DVD中英双字]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2010-08-16{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://5e:5e@m1.eee4.cc:1519/【3E电影院www.eee4.cc】黎巴嫩[DVD中英双字].rmvb" target=_blank>ftftp://5e:5e@m1.eee4.cc:1519/【3E电影院www.eee4.cc】黎巴嫩[DVD中英双字].rmvb</A></TD></TR></TBODY></TABLE></div><ul class="mmlist{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MP631J0-11923.jpg{/dede:field}
