{dede:field name='keywords'}穿靴子的猫之萌猫三剑客高清1280{/dede:field}
{dede:field name='description'}穿靴子的猫之萌猫三剑客高清1280版BD中字2012最新美国动画喜剧大迅雷下载、免费下载，穿靴子的猫之萌猫三剑客高清1280版BD中字2012最新美国动画喜剧大Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}穿靴子的猫之萌猫三剑客高清1280版BD中字2012最新美国动画喜剧大{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-02-22{/dede:field}
{dede:field name='body'}<p>
	<img src="http://img2081.poco.cn/mypoco/myphoto/20120222/14/56643687201202221445561797403617315_004.jpg" /></p>

<p>
	<img src="http://img2081.poco.cn/mypoco/myphoto/20120222/14/56643687201202221445561797403617315_005.jpg" /></p>
<p>
	片名：穿靴子的猫之萌猫三剑客/穿靴子的猫番外篇/鞋貓劍客 番外篇<br />
	推出日期：19-02-2012<br />
	来源：蓝光<br />
	大小：1CD 149MB<br />
	类型：动作、喜剧、犯罪、动画<br />
	视频：1280&times;720 | 5963<br />
	音频：英语| DTS 1510 Kbps的<br />
	字幕：中文<br />
	导演：克里斯&middot;米勒<br />
	主演：安东尼奥&middot;班德拉斯，萨尔玛&middot;海耶克和扎克加利菲亚纳基斯</p>
<p>
	<br />
	剧情介绍</p>
<p>
	一个绝望的公主聘请穿靴子的猫找回她被盗的红宝石。穿靴子的猫不情愿地与三只小猫合作。</p>
<p>
	<br />
	◎影片截图</p>
<p>
	<img src="http://img2081.poco.cn/mypoco/myphoto/20120222/14/56643687201202221445561797403617315_003.jpg" style="width: 600px; height: 338px" /></p>
<p>
	<img src="http://img2081.poco.cn/mypoco/myphoto/20120222/14/56643687201202221445561797403617315_002.jpg" style="width: 600px; height: 338px" /></p>
<p>
	<img src="http://img2081.poco.cn/mypoco/myphoto/20120222/14/56643687201202221445561797403617315_001.jpg" style="width: 600px; height: 338px" /></p>
<p>
	<img src="http://img2081.poco.cn/mypoco/myphoto/20120222/14/56643687201202221445561797403617315_000.jpg" style="width: 600px; height: 338px" /></p>

<p>
	[下载地址]： <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" /></p>


<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2865/飘花电影piaohua.com穿靴子的猫之萌猫三剑客高清1280版BD中字.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2865/飘花电影piaohua.com穿靴子的猫之萌猫三剑客高清1280版BD中字.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1B3Q30-35A8.jpg{/dede:field}
