{dede:field name='keywords'}未来空军揭秘迅雷下载，免费下载{/dede:field}
{dede:field name='description'}未来空军揭秘迅雷下载、免费下载，未来空军揭秘Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}未来空军揭秘{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2008-08-03{/dede:field}
{dede:field name='body'}<P>【译　　名】《未来空军揭秘》精品收藏记录片DVD中字<BR>【片　　名】Discovery Secrets of Future Air Power<BR>【年　　代】2003<BR>【国　　家】美国<BR>【类　　别】记录/短片<BR>【语　　言】英语<BR>【字　　幕】中文<BR>【文件格式】X264 + AC3<BR>【视频尺寸】800 x 452<BR>【电影整理】3E迅雷电影下载站(www.eee4.com)<BR>【文件大小】1CD 265MB<BR>【片　　长】44 mins<BR>【导　　演】James Cross (writer)<BR>【主　　演】John W. Armbrust ...&nbsp; Test Pilot <BR>【简　　介】</P>
<P>&nbsp;&nbsp;&nbsp; 本片将带你进入一个秘密世界，在那最离奇的技术被用于实际。这些技术包括粒子光线流武器，静音超音速飞行，磁悬浮，超高速巡航等等。所有这些技术使非来那些突破常规的飞机成为可能。</P>
<P>&nbsp;&nbsp;&nbsp; 未来的战场将变的更加危险，陆战及海战依旧存在。不过如果缺乏空中优势，将无法获胜。欢迎来到21世纪的战场，这里充满无可匹敌的操控，优势武器及准确度更胜以往。匿踪科技横行，这些是未来空武之迷....3E迅雷<A href="/" target=_blank>电影下载</A>站.</P>
<P>【电影截图】：<BR>电影来源：www.eee4.com<BR><IMG src="http://pic.piaohua.com/0701pic/allimg/080803/0452230.jpg">&nbsp;<BR><IMG src="http://pic.piaohua.com/0701pic/allimg/080803/0451451.jpg">&nbsp;<BR><IMG src="http://pic.piaohua.com/0701pic/allimg/080803/0452161.jpg">&nbsp;<BR><IMG src="http://pic.piaohua.com/0701pic/allimg/080803/0452320.jpg">&nbsp;<BR><IMG src="http://pic.piaohua.com/0701pic/allimg/080803/0452321.jpg">&nbsp;<BR><IMG src="http://pic.piaohua.com/0701pic/allimg/080803/0452164.jpg"></P>
<P>2008-08-03 00:58:12 开始连接......<BR>2008-08-03 00:58:12 开始搜索候选资源......<BR>2008-08-03 00:58:12 搜索到52个候选资源<BR>2008-08-03 00:58:12 使用候选资源进行连接......<BR>2008-08-03 00:58:13 搜索到121个候选资源<BR>2008-08-03 00:58:13 使用候选资源进行连接......<BR>2008-08-03 00:58:13 文件创建成功，开始下载数据......<BR>2008-08-03 00:58:16 用户取消下载&nbsp;&nbsp; 本文来自 <A href="/index.html" target=_blank>www.eee4.com</A></P>（直接可能无法下载，一律使用<A href="/soft.htm" target=_blank>迅雷下载</A>）<BR>精品收藏记录片《未来空军揭秘》DVD中字 －来自[3E迅雷电影站eee4.com]下载地址：<IMG src="/templets/img/down.jpg" border=0><BR>
<TABLE style="BORDER-RIGHT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; BORDER-BOTTOM: #cccccc 1px dotted" cellSpacing=0 cellPadding=6 width="95%" align=center border=0>
<TBODY>
<TR>
<TD style="WORD-WRAP: break-word" bgColor=#fdfddf><ANCHOR></ANCHOR><A href="ftp://eee4.com:8114@vip11.eee4.com:8114/[3E迅雷电影站www.eee4.com]未来空军揭秘DVD中字.rmvb" target=_blank>ftp://eee4.com:8114@vip11.eee4.com:8114/[3E迅雷电影站www.eee4.com]未来空军揭秘DVD中字.rmvb</A></TD></TR></TBODY></TABLE>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O16142350-34H5.jpg{/dede:field}
