{dede:field name='keywords'}星尘/星尘传奇HD中英双字1024高{/dede:field}
{dede:field name='description'}星尘/星尘传奇HD中英双字1024高清迅雷下载、免费下载，星尘/星尘传奇HD中英双字1024高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}星尘/星尘传奇HD中英双字1024高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-03-06{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://e13:e13@xl2.eee4.com:1003/[3E电影站www.eee4.com]星尘DVD中英双字.rmvb" target="_blank{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MOER30-423J.jpg{/dede:field}
