{dede:field name='keywords'}变脸/夺面双雄变脸BD中英双字102{/dede:field}
{dede:field name='description'}变脸/夺面双雄变脸BD中英双字1024/1280高清迅雷下载、免费下载，变脸/夺面双雄变脸BD中英双字1024/1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}变脸/夺面双雄变脸BD中英双字1024/1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-12-08{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://e49:e49@xl2.eee4.com:9024/[3E电影站www.eee4.com]变脸[DVD中英双字1024x576高清版].rmvb" target="_blank{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MP2J130-2XT.jpg{/dede:field}
