{dede:field name='keywords'}午夜巴塞罗那/情遇巴塞隆纳BD中{/dede:field}
{dede:field name='description'}午夜巴塞罗那/情遇巴塞隆纳BD中英双字1024/1280高清版迅雷下载、免费下载，午夜巴塞罗那/情遇巴塞隆纳BD中英双字1024/1280高清版Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}午夜巴塞罗那/情遇巴塞隆纳BD中英双字1024/1280高清版{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-05{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://3e:3e@www2.eee4.com:665/[www.eee4.cn提供]午夜巴塞罗那BD中英双字1024x480高清版.rmvb" target="_blank{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MOJ110-24058.jpg{/dede:field}
