<?php
$z[0]=Array("field","午夜巴塞罗那/情遇巴塞隆纳BD中",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","午夜巴塞罗那/情遇巴塞隆纳BD中英双字1024/1280高清版迅雷下载、免费下载，午夜巴塞罗那/情遇巴塞隆纳BD中英双字1024/1280高清版Gvod高清在线播放，剧情介绍等。",72,266);
$z[1][4]['name']="description";
$z[2]=Array("field","午夜巴塞罗那/情遇巴塞隆纳BD中英双字1024/1280高清版",268,356);
$z[2][4]['name']="title";
$z[3]=Array("field","",358,397);
$z[3][4]['name']="writer";
$z[4]=Array("field","",399,438);
$z[4][4]['name']="source";
$z[5]=Array("field","2012-05-05",440,490);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",492,529);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://3e:3e@www2.eee4.com:665/[www.eee4.cn提供]午夜巴塞罗那BD中英双字1024x480高清版.rmvb\" target=\"_blank",531,674);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MOJ110-24058.jpg",676,758);
$z[8][4]['name']="litpic";

?>