{dede:field name='keywords'}阿帕鲁萨镇/种马BD中英双字1024{/dede:field}
{dede:field name='description'}阿帕鲁萨镇/种马BD中英双字1024高清迅雷下载、免费下载，阿帕鲁萨镇/种马BD中英双字1024高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}阿帕鲁萨镇/种马BD中英双字1024高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-07{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://apollo.s.dpool.sina.com.cn/nd/dataent/moviepic/pics/120/moviepic_2c8d31a0e2b78015742c62f415b635c4.jpg" /></p>
<p>
	◎译　　名　《阿帕鲁萨镇/种马(台)》08最新西部大片高清BD中英双字幕<br />
	◎片　　名　Appaloosa<br />
	◎年　　代　2008<br />
	◎国　　家　美国<br />
	◎类　　别　剧情/犯罪/西部<br />
	◎语　　言　英语<br />
	◎字　　幕　BD-RMVB<br />
	◎IMDB评分&nbsp; 7.2/10 (4,490 votes)<br />
	◎导　　演　艾德&middot;哈里斯 Ed Harris<br />
	◎主　　演　维果&middot;莫特森 Viggo Mortensen&nbsp; ....Everett Hitch<br />
	　　　　　　芮妮&middot;齐薇格 Ren&eacute;e Zellweger&nbsp; ....Allie<br />
	　　　　　　艾德&middot;哈里斯 Ed Harris&nbsp; ....Virgil Cole<br />
	　　　　　　Robert Knott&nbsp; ....Vince<br />
	　　　　　　杰瑞米&middot;艾恩斯 Jeremy Irons&nbsp; ....Randall Bragg<br />
	　　　　　　兰斯&middot;亨利克森 Lance Henriksen<br />
	　　　　　　Rex Linn&nbsp; ....Sheriff Stringer<br />
	　　　　　　格拉德&middot;斯万 Girard Swan&nbsp; ....Bragg&#39;s Man<br />
	　　　　　　艾妮安娜&middot;姬儿 Ariadna Gil&nbsp; ....Katie<br />
	　　　　　　Gabriel Marantz&nbsp; ....Joe Whittfield<br />
	　　　　　　Corby Griesenbeck&nbsp; ....Charlie Tewksbury<br />
	　　　　　　Cassie Kinchen&nbsp; ....Mexican girl<br />
	　　　　　　Michael A. Lente&nbsp; ....Hotel Desk Clerk<br />
	　　　　　　Bob L. Harris&nbsp; ....Judge Elias Callison<br />
	<br />
	◎简　　介　<br />
	<br />
	　　这是一部根据Robert B. Parker的同名原着改编的西部片，由艾德&middot;哈里斯自导自演。电影讲述了维吉尔（艾德&middot;哈里斯）和埃弗雷特（维果&middot;莫特森）在一个偏远的小镇当警察，他们发现在这个小镇法律不起作用。农场主兰德尔（杰里米&middot;艾恩斯）是当地势力最大的人，控制着镇上的物资、马匹和女人，维吉尔和埃弗雷特打算行使自己的职责，向兰德尔交涉。但一个颇具魅力的寡妇（芮妮&middot;齐薇格）的到来打乱了他们的计划。<br />
	<br />
	　　荒蛮西部，无法可依，两位警官拍档阿弗雷特（维果&middot;莫特森饰）和维吉尔（艾德&middot;哈里斯饰）在阿帕鲁萨镇依靠枪_支来维护和平，两人之间虽然话不多但彼此却非常了解。阿弗雷特在西点军校毕业后为了寻找全新的生活而独闯西部，而当时维吉尔正苦于没有能够帮助自己的帮手。一次偶然的机会，阿弗雷特救了维吉尔的性命，维吉尔就邀请他和自己组成搭档来维护小镇秩序。在之后的12年里，两人惺惺相惜，合作默契。<br />
	<br />
	　　凶狠的农场主兰德尔（杰里米&middot;艾恩斯饰）是阿帕鲁萨镇势力最大的人，控制着镇上的物资、马匹和女人。他经常纵容自己的雇工在当地作威作福，并最终导致惨剧的发生&mdash;&mdash;镇上三个居民惨遭横死、居民妻子被强暴。惯于忍耐的民众这一次再也忍无可忍。<br />
	<br />
	　　小镇惨剧发生之后，原本打算向兰德尔交涉的阿弗雷特和维吉尔两人，却面临了新的挑战，美丽的寡妇埃里森（芮妮&middot;齐薇格饰）的神秘到来，使得阿帕鲁萨镇一切都不复往昔...<br />
	<br />
	幕后制作<br />
	<br />
	　　阿帕鲁萨镇&mdash;&mdash;重现蛮荒西部<br />
	<br />
	　　许多年来，艾德&middot;哈里斯一直想拍摄一个发生在新墨西哥的蓝天荒漠之中的故事，寻寻觅觅却一直未果。直到他读到了罗伯特&middot;B&middot;帕克的小说。哈里斯说，&ldquo;我一直爱着新墨西哥，我想帕克的故事适于这个地方。&rdquo;出于对小说由衷的喜爱，哈里斯决定要亲自将它搬上银幕，西部片的漫漫黄沙、天高云淡，以及充满男性气息的骑马奔驰、纵横枪战江湖的场面也得以再次展现在观众面前。<br />
	<br />
	　　哈里斯与帕克开始合作改编《阿帕鲁萨镇》之后，制片公司曾考察过多处外景地，最终还是决定以新墨西哥北部为主要拍摄地。不仅是此地的原始风貌让人惊心动魄，令创作者幻想出无数拓荒者的故事，更重要的是，新墨西哥就是一个绝佳的电影拍摄地，当地良好的设施和配合吸引了众多的电影制作团队。哈里斯说，&ldquo;这里对拍摄电影非常方便有利，你所要做的只是到这里然后体验它&mdash;&mdash;开阔的天空，山脉，沙漠，以及静默&rdquo;。由此在影片中我们可以看到一个充满情感、梦想与期待的阿帕鲁蕯镇。<br />
	<br />
	　　无论是出于导演对新墨西哥的热爱，亦或是西部片本身的类型需求，摄影都是影片中非常重要的一部分。《阿帕鲁萨镇》的摄影师迪恩&middot;萨摩可以说深谙此道。在此之前，他有过六次在新墨西哥拍摄的经验。他与这片土地的熟悉程度可见一斑，&ldquo;这里对拍摄西部片来说再理想不过了。&rdquo;　萨摩如是说。在这部电影中，他选择了特别的方式来表现阿帕鲁萨镇的景和人，他的拍摄运用了变形镜头，以及大量广角镜头。为的是捕捉到广大西南部的大全景，&ldquo;我用了很多优美的固定镜头拍摄景物和其中的人物，所以我们与环境并非隔绝的，我们融入其中。&rdquo;迪恩&middot;萨摩认为，阿帕鲁萨镇之所以美。并不仅仅是自然风光。而是与其处于一体的人。人点缀了风景，与风景密不可分。<br />
	<br />
	　　细节之美&mdash;&mdash;考究的建筑、道具和服装<br />
	<br />
	　　与新墨西哥丰富的色彩相对的是影片独特的建筑再现。艺术指导瓦德梅&middot;加林维斯基与哈里斯紧密合作，在银幕上给我们展现了一个真实的阿帕鲁萨镇。加林维斯基说，&ldquo;阿帕鲁萨镇的经济经历了低潮，因此我们要考虑它原本是什么样的。从一开始我们就进行了详尽的考察，它不仅仅是一个位于西部中心的小镇，还是一个以煤矿闻名的小镇。&rdquo;基于对阿帕鲁萨镇的此点认识，加林维斯基的小组用了西南部最自然的材料木头、砖头和土坯重建了阿帕鲁萨镇。大部分建筑都是用木头建造的，只有一些基本建筑用了砖头，银行表面用的是石头，煤矿公司和教堂用的是土坯。加里维斯基说，波士顿家庭旅馆和酒吧间的内墙还用了英国设计师威廉姆&middot;莫里斯（William Morris）的新墙纸，&ldquo;这个墙纸非常合适当时的场景，并且在视觉上让人感觉回到了自然，而人们喜欢自然的东西。我们的墙纸是在英国制作，然后海运过来的&rdquo;。<br />
	<br />
	　　除此之外，对于影片另一重要道具&mdash;&mdash;枪_支，创作者也力图还原真实。在电影中最引人注目的枪是阿弗雷特使用的非常少见的8寸口径枪，也被称为&ldquo;悬空球枪&rdquo;。它50英尺长，重量超过11磅，是非常具有威胁性的武器。从技术上讲，8寸口径的枪更接近于**而不是步枪，杀伤力很强。而维吉尔则钟情于一款产于1873年的手枪。手柄由骨头制成，很夺人眼球。<br />
	<br />
	　　对于一部追求完美的电影，《阿帕鲁萨镇》中演员的服装也颇为考究。大卫&middot;罗宾逊负责为本片的角色设计服装。他特意去寻找旧照片和西部的一些古董，来了解当时人们的衣着特点。他发现当今的男性服装与之前的服装有很多相似之处，&ldquo;举个例子，你要穿一个很硬的颈巾，为了防止脖子不被擦伤，你势必会再穿一件背心在里面。&rdquo;大卫&middot;罗宾逊还表示，设计本片服装的目的在于在时尚与现实之间寻找突破，&ldquo;摄影在那会儿是新发明，那些要照相的人的衣着肯定和他们平时不同，要更正式。&rdquo;<br />
	<br />
	　　刻画人性&mdash;&mdash;两位主角的再次合作<br />
	<br />
	　　艾德&middot;哈里斯与维果&middot;莫特森曾在《暴力史》中有过合作，在《暴力史》在多伦多电影节展映时，哈里斯就给了维果《阿帕鲁萨镇》的小说影印本，让他考虑是否参演。维果读过之后，即被小说中独具特色的人物性格及两位主角之间的深厚情谊所吸引，特别是两位主人公非常特别的&ldquo;无话的同事关系&rdquo;。维果说，&ldquo;尽管两人性格差异很大，但他们了解彼此。我无法想象这种友情该如何定义。&rdquo;对于西部片这个类型，维果说，&ldquo;我喜欢骑马，我喜欢西部，但是那里有很多坏蛋，要在那里生活下去，主人公必须小心谨慎地处理危机。&rdquo;为了更好地塑造角色，维果看了许多描述西部的照片及老电影，以此了解枪战场面的人物姿势。<br />
	<br />
	　　当下拍一部西部片对主创人员充满了挑战，毕竟太多珠玉在前。影片的制片人就表示两位主人公&ldquo;策马入镇&rdquo;的形象是传统西部片的人物，但两人的具体行为却与以往的电影人物有所不同。&ldquo;他们两个人打算拨乱反正，听起来虽然有点老套，但是他们最终明白要在如此细微而复杂的处境中完成任务，就一定要在某些方面做出妥协。&rdquo;影片不再是正邪势不两立的纯粹二元对立格局，也不再是单纯的英雄主义宣扬。西部的英雄卸下光环，还原成普通人。<br />
	<br />
	　　维果评价电影表现的不是一个传统意义上的西部，&ldquo;这不是我们经常看到的只是回到1882年、没有新意的表演。那时候人们的行为评价标准非常不同，从某种程度上来讲，他们对文雅和骑士精神有着更高的要求，但从另外一些方面看，人们对待彼此又更直接和粗鲁。同时，作为主人公的我和哈里斯的工作都不能在这个故事中证明以暴制暴是正确的，或让我们的形象比他们更接近英雄。&rdquo;<br />
	<br />
	　　哈里斯说，他们在改编时最大程度地保留了原作者的意图，&ldquo;我们努力让每个人物的个性和他们之间的关系都能得到真实表现。尽管影片发生在在19世纪，但人性依旧支配着人们相互间的行为。友情和矛盾、忠诚和背叛的主题在今天依然值得探讨。在一个如此棒的团队中看到全部这些，我真的是别无所求了，这真的是一次非常有价值的经历&rdquo;。</p>

<p>
	【电影截图】：<br />
	电影来源：www.eee4.com<br />
	<br />
	<br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://img.album.pchome.net/54/68/31/42/321bb28de50947601f2f70ee93fead88.jpg');" src="http://img.album.pchome.net/54/68/31/42/321bb28de50947601f2f70ee93fead88.jpg" /><br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://img.album.pchome.net/54/68/31/42/e0e731523d842a02959604445ace1215.jpg');" src="http://img.album.pchome.net/54/68/31/42/e0e731523d842a02959604445ace1215.jpg" /><br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://img.album.pchome.net/54/68/31/42/e8bd69af5b8a95544db6e4583f115766.jpg');" src="http://img.album.pchome.net/54/68/31/42/e8bd69af5b8a95544db6e4583f115766.jpg" /><br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://img.album.pchome.net/54/68/31/42/931da79d42786d2999ac1ed1d0fcfe11.jpg');" src="http://img.album.pchome.net/54/68/31/42/931da79d42786d2999ac1ed1d0fcfe11.jpg" /></p>
	08最新西部大片《阿帕鲁萨镇》高清BD中英双字幕 －来自[3E电影站www.eee4.com]：<img border="0" src="http://www.eee4.com/templets/img/down.jpg" /><br />
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<anchor></anchor><a href="ftp://d11:d11@xl.eee4.com:9914/[3E电影站www.eee4.com]阿帕鲁萨镇DVD中英双字高清版CD1.rmvb" target="_blank">ftp://d11:d11@xl.eee4.com:9914/[3E电影站www.eee4.com]阿帕鲁萨镇DVD中英双字高清版CD1.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<anchor></anchor><a href="ftp://d11:d11@xl.eee4.com:9914/[3E电影站www.eee4.com]阿帕鲁萨镇DVD中英双字高清版CD2.rmvb" target="_blank">ftp://d11:d11@xl.eee4.com:9914/[3E电影站www.eee4.com]阿帕鲁萨镇DVD中英双字高清版CD2.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<anchor></anchor><a href="ftp://dy44:piaohua@dy44.piaohua.com:3364/飘花电影piaohua.com种马BD中英双字1024高清.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3364/飘花电影piaohua.com种马BD中英双字1024高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15962Y0-2Kb.jpg{/dede:field}
