{dede:field name='keywords'}十八，十九DVD中字2012最新韩国{/dede:field}
{dede:field name='description'}十八，十九DVD中字2012最新韩国剧情爱情大片迅雷下载、免费下载，十八，十九DVD中字2012最新韩国剧情爱情大片Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}十八，十九DVD中字2012最新韩国剧情爱情大片{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-04-24{/dede:field}
{dede:field name='body'}<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120424/18/56643687201204241802253545582670311_005.jpg" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120424/18/56643687201204241802253545582670311_004.jpg" /></p>
<p>
	◎中 文 名　十八，十九<br />
	◎英 文 名　Eighteen.Ninteen<br />
	◎年　　代　2012<br />
	◎国　　家　爱情/剧情<br />
	◎片　　长　94分钟<br />
	◎导　　演　裴光秀 Kuang-su Pea<br />
	◎主　　演　刘延锡 Yeon-seok Yoo<br />
	白珍熙 Jin-hee Baek</p>
<p>
	◎剧 情</p>
<p>
	一对异卵双胞胎在成为成人的最后一个冬季里发生的青春故事。<br />
	　　妹妹瑞雅突然向哥哥浩亚表明心迹，令后者不知所措，索性和同班女生斗美交往，而瑞雅也因冲动使然，和全校女生的梦中情人&mdash;&mdash;拳击部前辈日康走到一起，当然，很快分手了。难以言语的感情纠葛将四个少男少女萦系在一起。为了摆脱困扰，浩亚开始拳击训练。经过一段紧锣密鼓的培训，浩亚站到了新人锦标赛的拳台，而他所面对的正是人气爆棚的日康&hellip;&hellip;</p>
<p>
	<br />
	◎影片截图</p>
<p>
	&nbsp;<img src="http://img170.poco.cn/mypoco/myphoto/20120424/18/56643687201204241802253545582670311_000.jpg" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120424/18/56643687201204241802253545582670311_002.jpg" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120424/18/56643687201204241802253545582670311_003.jpg" /></p>
<p>
	&nbsp;<img src="http://img170.poco.cn/mypoco/myphoto/20120424/18/56643687201204241802253545582670311_001.jpg" /></p>

<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.netftp//dy44:piaohua@dy44.piaohua.com:3201/" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3284/飘花电影piaohua.com十八十九DVD中字.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3284/飘花电影piaohua.com十八十九DVD中字.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15014520-59414.jpg{/dede:field}
