{dede:field name='keywords'}人猿泰山1-2HD中英双字1280高清{/dede:field}
{dede:field name='description'}人猿泰山1-2HD中英双字1280高清经典动画迅雷下载、免费下载，人猿泰山1-2HD中英双字1280高清经典动画Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}人猿泰山1-2HD中英双字1280高清经典动画{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-11{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img.album.pchome.net/04/31/02/85/380368cb079c1f94e80d6b072243fbaf.jpg" /></p>
<p>
	【片　　名】　Tarzan<br />
	【年　　代】　1999<br />
	【国　　家】　美国<br />
	【类　　别】　动画/家庭<br />
	【语　　言】　英语/普通话/粤语<br />
	【字　　幕】　中文/英文<br />
	【字幕语言】 中文/英文<br />
	【视频尺寸】 1280&times;720<br />
	【文件格式】 RMVB+AAC<br />
	【IMDB评分】 6.9/10 (24,662 votes)<br />
	【片　　长】　88 Min<br />
	【导　　演】　克里斯&middot;巴克 Chris Buck<br />
	　　　　　　凯文&middot;利马 Kevin Lima<br />
	【主　　演】　布赖恩&middot;布莱斯德 Brian Blessed .... Clayton (voice)<br />
	　　　　　　格伦&middot;克洛斯 Glenn Close .... Kala (voice)<br />
	　　　　　　明妮&middot;德瑞弗 Minnie Driver .... Jane Porter (voice)<br />
	　　　　　　兰斯&middot;亨利克森 Lance Henriksen .... Kerchak (voice)<br />
	　　　　　　托尼&middot;高德温 Tony Goldwyn .... Tarzan (voice)<br />
	　　　　　　奈杰尔&middot;霍华霍内 Nigel Hawthorne .... Porter (voice)<br />
	　　　　　　韦恩&middot;奈特 Wayne Knight .... Tantor (voice)</p>
<p>
	【内容介绍】<br />
	之前 Tarzan 的故事早已被多次搬上银幕，这次迪士尼首度以动画方式呈现，故事则较多着墨在 Tarzan 少年时代的成长过程。在电影一开始，母猩猩 Kala 发现了与父母失散的小男婴，便收养了他并取名为 Tarzan ，但是 Tarzan 从小就被猩猩养父 Kerchak 和其他猩猩排斥，Tarzan 也对自己与众不同的外型感到困扰，只有母猩猩 Terk 和大象 Tantor 与他成为最好的朋友。直到 Tarzan 长大后见到随父亲来森林观察猩猩生态的女孩 Jane，他才知道自己原来跟他们同样是人类，不料同行的猎人 Clayton 心怀不轨计画要猎捕猩猩运回英国拍卖，Tarzan 的养父 Kerchak 也因此受到重创，Tarzan 最后该如何抉择？是要选择与猩猩们一同留在森林？还是与 Jane 回到人类文明的世界？本片采用最新的&ldquo;景深效果&rdquo;技术，使得片中森林场景颇具3D立体感，至於主角人物则依旧还是用迪士尼传统手绘，负责主角 Tarzan 的动画家是迪士尼目前首席动画大师 Glen Keane ，他由他那酷爱滑板、溜冰&hellip;等运动的儿子身上得到灵感，创造出在林间快速穿梭飞跃又酷又帅的泰山！<br />
	【关联作品】<br />
	2005 - 泰山2（Tarzan 2）《影音产品首映》</p>
<p>
	【制作编导】<br />
	本片由 Bonnie Arnold 担任制片，由 Chris Buck 和 Kevin Lima 共同执导，由 Tab Murphy 、Bob Tzudiker 、Noni White 共同编剧。</p>
<p>
	【配音演员】<br />
	由 Alex D. Linz 和 Tony Goldwyn 分别负责主角 Tarzan 童年和成年，女主角 Jane 则由演过【心灵捕手】的 Minnie Driver 担任，另外，曾演过【101真狗】、【空军一号】的 Glenn Close 帮抚养泰山长大的人猿妈妈 Kala 配音，至於猩猩爸爸 Kerchak 由 Lauce Henrickson 负责，Tarzan 的猩猩好友 Terk 则由 Rosie O&#39;Donnell 担任。</p>
<p>
	【音乐制作】<br />
	本片配乐是由 Mark Mancina 所负责，片中歌曲的作曲、作词则是由英国摇滚歌手 Phil Collins 所担任， Phil Collins 并且还为本片演唱英语、法语、德语、义大利语和西班牙语五种语言版本的歌曲！电影片尾的两首流行版主题曲分别是&ldquo;You&#39;ll Be in My Heart&rdquo;和&ldquo;Two Worlds&rdquo;，都是由 Phil Collins 所演唱，他还与超级男孩（&#39;N Sync）演唱了一首流行版的&ldquo;Trashin&#39; the Camp&rdquo;，收录於原声带里。</p>
<p>
	【歌曲名称】<br />
	1. Two Worlds<br />
	2. You&#39;ll Be in My Heart<br />
	3. Son of Man<br />
	4. Trashin&#39; the Camp<br />
	5. Strangers Like Me</p>
<p>
	【奥斯卡纪录】<br />
	获得奥斯卡最佳歌曲（&ldquo;You&#39;ll Be in My Heart&rdquo;）</p>
<p>
	【相关发行】<br />
	电影原声带在美国1999年5月就已发行，迪士尼唱片在美国迪士尼专卖店还发行一限量版原声带，CD封面图片会动，这个特别版本只有在专卖店预购才买得到，预购还送一只送不卖的&ldquo;You&#39;ll Be in My Heart&rdquo;单曲。本片的录影带及一区DVD则是在2000年的2月初发行。本片后来迪士尼还改拍成电视卡通影集，另外，1999年迪士尼乐园还计画将已开幕三十多年的『鲁宾逊家庭树屋』设施（出自电影【海角一乐园】）移除，把这大树推出新的『泰山树屋』设施。佛罗里达的迪士尼世界动物王国、巴黎迪士尼乐园都推出过【泰山】的相关表演。</p>
<p>
	<img alt="" border="0" height="418" src="http://img.album.pchome.net/54/82/30/32/129478852173ecd91a71230e7c551ece29b8a8da1e.jpg" width="600" /></p>
<p>
	&nbsp;<img alt="" src="http://img.album.pchome.net/04/31/02/85/07ef7111afb8d092f66e78b6cab3a220.jpg" style="width: 600px; height: 348px" /></p>
<p>
	<img alt="" src="http://img.album.pchome.net/04/31/02/85/b87a280675ea281e9cfb54da9f563cc6.jpg" style="width: 600px; height: 348px" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.netftp//dy44:piaohua@dy44.piaohua.com:3125/" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3394/飘花电影piaohua.com人猿泰山DVD国语配音CD1.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3394/飘花电影piaohua.com人猿泰山DVD国语配音CD1.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3394/飘花电影piaohua.com人猿泰山DVD国语配音CD2.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3394/飘花电影piaohua.com人猿泰山DVD国语配音CD2.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3394/飘花电影piaohua.com人猿泰山2DVD国语配音CD1.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3394/飘花电影piaohua.com人猿泰山2DVD国语配音CD1.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3394/飘花电影piaohua.com人猿泰山2DVD国语配音CD2.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3394/飘花电影piaohua.com人猿泰山2DVD国语配音CD2.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3395/飘花电影piaohua.com人猿泰山1HD中英双字1280高清.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3395/飘花电影piaohua.com人猿泰山1HD中英双字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O152061F-3H47.jpg{/dede:field}
