<?php
$z[0]=Array("field","地球湮没之惊涛大历险/明天过后2",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","地球湮没之惊涛大历险/明天过后2/后天2/超级飓风之世界末日[DVD中字]迅雷下载、免费下载，地球湮没之惊涛大历险/明天过后2/后天2/超级飓风之世界末日[DVD中字]Gvod高清在线播放，剧情介绍等。",73,295);
$z[1][4]['name']="description";
$z[2]=Array("field","地球湮没之惊涛大历险/明天过后2/后天2/超级飓风之世界末日[DVD中字]",297,399);
$z[2][4]['name']="title";
$z[3]=Array("field","",401,440);
$z[3][4]['name']="writer";
$z[4]=Array("field","",442,481);
$z[4][4]['name']="source";
$z[5]=Array("field","2009-09-03",483,533);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",535,572);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://4e:4e@www2.eee4.com:675/[www.eee4.cn提供]地球湮没之惊涛大历险BD中英双字1280x720高清版.rmvb\" target=_blank>ftftp://4e:4e@www2.eee4.com:675/[www.eee4.cn提供]地球湮没之惊涛大历险BD中英双字1280x720高清版.rmvb</A></TD></TR></TBODY></TABLE><BR><FONT color=#ff0000 size=2><STRONG>美国经典灾难动作片《地球湮没之惊涛大历险》DVD中字【640x480分辨率】 [<FONT color=#0909f7 size=4>2009/09/02</FONT>下载地址]：<IMG src=\"httftp://www.eee4.com/templets/img/down.jpg\" border=0></STRONG></FONT><BR>\r\n<TABLE style=\"BORDER-RIGHT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; BORDER-BOTTOM: #cccccc 1px dotted\" cellSpacing=0 cellPadding=6 width=\"95%\" align=center border=0>\r\n<TBODY>\r\n<TR>\r\n<TD style=\"WORD-WRAP: break-word\" bgColor=#fdfddf><A href=\"ftftp://4e:4e@www2.eee4.com:719/[www.eee4.cn提供]惊涛大历险DVD中字.rmvb\" target=_blank>ftftp://4e:4e@www2.eee4.com:719/[www.eee4.cn提供]惊涛大历险DVD中字.rmvb</A></TD></TR></TBODY></TABLE></div><ul class=\"mmlist",574,1619);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MPW6060-12E8.jpg",1621,1703);
$z[8][4]['name']="litpic";

?>