{dede:field name='keywords'}301角斗士/301壮士BD1280高清迅{/dede:field}
{dede:field name='description'}301角斗士/301壮士BD1280高清迅雷下载、免费下载，301角斗士/301壮士BD1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}301角斗士/301壮士BD1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-07{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://cdn3a.dvdempire.org/products/68/1606168h.jpg" style="width: 500px; height: 647px" /></p>
<p>
	◎译　　名　301壮士<br />
	◎片　　名　The Legend of Awesomest Maximus<br />
	◎年　　代　2011<br />
	◎国　　家　美国<br />
	◎类　　别　喜剧<br />
	◎语　　言　英语<br />
	◎字　　幕　中字<br />
	◎IMDB评分 &nbsp; 3.9/10 (839 votes)<br />
	◎IMDB链接 &nbsp; <a class="faqlink" endcolor="FF6600" href="http://www.xiaozhizhu.net/" index="0" startcolor="0066ff" state="OFF" style="color: #0066ff">http://www.xiaozhizhu.net/</a><br />
	◎片　　长　90 mins<br />
	◎导　　演　Jeff Kanew<br />
	◎主　　演　克里斯塔娜&middot;洛肯 Kristanna Loken ....Hottessa<br />
	　　　　　　威尔&middot;萨索 Will Sasso ....Awesomest Maximus<br />
	　　　　　　雷普&middot;汤恩 Rip Torn ....King Looney<br />
	　　　　　　苏菲&middot;蒙克 Sophie Monk ....Princess Ellen<br />
	　　　　　　伊恩&middot;齐林 Ian Ziering ....Testiclees<br />
	　　　　　　Adam DeVine ....Ephor 1<br />
	　　　　　　托尼&middot;考克斯 Tony Cox ....Minoritees<br />
	　　　　　　Russell Peters ....Pervius<br />
	　　　　　　Deon Richmond ....Jamal<br />
	　　　　　　Dennis Haskins ....Father Jay<br />
	　　　　　　Jason Sklar ....Bill<br />
	　　　　　　Khary Payton ....King Erotic<br />
	　　　　　　Randy Sklar ....Jeff<br />
	　　　　　　Edward Barbanell ....Testiclees Little Cousin<br />
	　　　　　　Michelle Money ....Attendant<br />
	　　　　　　Eddie Pepitone ....Approximo<br />
	　　　　　　Nathalie Walker ....Oracle<br />
	　　　　　　艾哈迈德&middot;艾哈迈德 Ahmed Ahmed ....Slick Slave Trader<br />
	　　　　　　蒂凡妮&middot;克劳丝 Tiffany Claus ....Milfia<br />
	　　　　　　Sarah Mitchell ....Looney Girl #2<br />
	　　　　　　Gary Lundy ....Orlando<br />
	　　　　　　Stephanie Reibel ....Looney Girl #1<br />
	　　　　　　Michael O&#39;Connell ....Janitorius<br />
	　　　　　　Peter D&#39;Alessio ....Giuseppe<br />
	　　　　　　Taggart Hurtubise ....Son<br />
	　　　　　　Nelson Frazier Jr. ....Ginormous<br />
	　　　　　　Shalaina Fotheringham ....Loony&#39;s Girl (as Shalaina Fotheringham)<br />
	　　　　　　Kevin Linehan ....Quantas<br />
	　　　　　　Minnie Gupta ....Bathhouse Handmaiden<br />
	　　　　　　James C. Morris ....Ephor 2<br />
	　　　　　　Tod Huntington ....Greek Soldier #3<br />
	　　　　　　Bob Lanoue ....Pushy crowd member<br />
	　　　　　　Devin Barry ....Stassenius<br />
	　　　　　　Tye Nelson ....Greek Soldier #2<br />
	　　　　　　Oscar A. Diaz ....Crowd member #4<br />
	　　　　　　Robyn Adamson ....Dyke Girl In Crowd<br />
	　　　　　　Barby Garcia ....Mistress<br />
	　　　　　　Nenetzi Scott ....Masseuse<br />
	　　　　　　Dennis Luciani ....Accoutant<br />
	　　　　　　Robin Westover ....Fat Peasant Woman<br />
	　　　　　　Ben Naccarato ....Trojan Soldier<br />
	　　　　　　Thadeus Welch ....Background artist - various characters<br />
	　　　　　　Larry Filion ....King Loony&#39;s guard<br />
	　　　　　　John Hinckley ....Musician #2<br />
	　　　　　　Rafael Perez ....Greek Soldier<br />
	　　　　　　Mike Hardy ....Beer guy<br />
	　　　　　　Christopher Brick Johnson ....Greek Soldier<br />
	　　　　　　Bijan J. Hosseini ....Scalper<br />
	　　　　　　Blake Anderson ....Greek Soldier #1 (uncredited)<br />
	　　　　　　Tony Knight ....Man In Crowd (uncredited)<br />
	<br />
	<br />
	<br />
	◎简　　介<br />
	<br />
	&nbsp; &nbsp;曾经成功推出Animal House的国家讽刺文社(National Lampoon)近日决定开拍讽刺好莱坞史诗电影300壮士的电影-National Lampoon&#39;s 301: The Legend of Awesomest Maximus Wallace Leonidas，另外从片名你可以看出这部电影会将三百斯巴达勇士,特洛依等其他好莱坞史诗电影一起恶搞，据悉影片是叙述最厉害的普洛泰戈这名身材走样的斯巴达将军变成传奇人物的过程中遭遇许多挫折的故事。<br />
	<br />
	&nbsp; &nbsp;国家讽刺文社是美国大学生一直最爱的刊物之一，在1978年首部电影作品Animal House讲述大学男生大闹笑话的故事，由於贴近其真实生活在当年以黑马之姿成为最卖座的电影并进入了百部经典喜剧片的行列，从此衍生了一系列冠入国家讽刺文社(National Lampoon)名字的喜剧片。<br />
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120505/00/62564813201205050051023407736045345_003.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120505/00/62564813201205050051023407736045345_002.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120505/00/62564813201205050051023407736045345_001.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120505/00/62564813201205050051023407736045345_000.jpg" style="width: 720px; height: 405px" /><br />
	&nbsp;</p>
<p>
	【下载地址】</p>
<table bgcolor="#0099cc" border="0" cellpadding="10" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.net" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy125:piaohua@dy125.piaohua.com:8015/飘花电影piaohua.com301角斗士BD中字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:8015/飘花电影piaohua.com301角斗士BD中字1280高清.rmvb</a></td>
		</tr>
		<tr>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15J11F-25916.jpg{/dede:field}
