<?php
$z[0]=Array("field","教父1[BD中英双字1024/1280高清",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","教父1[BD中英双字1024/1280高清版]迅雷下载、免费下载，教父1[BD中英双字1024/1280高清版]Gvod高清在线播放，剧情介绍等。",72,230);
$z[1][4]['name']="description";
$z[2]=Array("field","教父1[BD中英双字1024/1280高清版]",232,302);
$z[2][4]['name']="title";
$z[3]=Array("field","",304,343);
$z[3][4]['name']="writer";
$z[4]=Array("field","",345,384);
$z[4][4]['name']="source";
$z[5]=Array("field","2012-01-18",386,436);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",438,475);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://eee4.com:1001@xl2.eee4.com:1001/[3E电影站www.eee4.com]教父[DVD中英双字1024x576高清版]CD1.rmvb\" target=\"_blank",477,631);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MQ295H0-32511.jpg",633,716);
$z[8][4]['name']="litpic";

?>