{dede:field name='keywords'}武状元苏乞儿BD高清国粤双语1024{/dede:field}
{dede:field name='description'}武状元苏乞儿BD高清国粤双语1024*576迅雷下载、免费下载，武状元苏乞儿BD高清国粤双语1024*576Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}武状元苏乞儿BD高清国粤双语1024*576{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-09-09{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="/uploads/allimg/c120525/133O02915920-112938.jpg" /></p>
<p>
	◎译　　名　武状元苏乞儿<br />
	◎片　　名　King of Beggars<br />
	◎年　　代　1992<br />
	◎地　　区　香港<br />
	◎类　　别　动作/喜剧/剧情<br />
	◎语　　言　粤语/普通话<br />
	◎字　　幕　中英<br />
	◎IMDB评分　6.8/10 (813 votes)<br />
	◎IMDB链接　http://www.imdb.com/title/tt0100963/<br />
	◎文件格式　X264 + AC3<br />
	◎视频尺寸　1024 x 576<br />
	◎文件大小　5/4 DVD<br />
	◎片　　长　1h:40m:02s<br />
	◎导　　演　陈嘉上 Gordon Chan<br />
	　　　　　　林德禄 David Lam<br />
	◎主　　演　周星驰 Stephen Chow&nbsp; ....So Chan/So Hat Yi<br />
	　　　　　　吴孟达 Man Tat Ng&nbsp; ....General of Canton<br />
	　　　　　　张敏 Sharla Cheung&nbsp; ....Yu-Shang<br />
	　　　　　　徐少强 Norman Chu&nbsp; ....Chiu<br />
	　　　　　　林威 Wai Lam&nbsp; ....Seng Ko Lin-Chin<br />
	　　　　　　黎彼得 Peter Lai&nbsp; ....Uncle Cheng<br />
	　　　　　　苑琼丹 King-Tan Yuen&nbsp; ....Madam Pimp<br />
	　　　　　　陈百祥 Pak-cheung Chan&nbsp; ....Minister of Justice<br />
	　　　　　　郑丹瑞 Lawrence Cheng&nbsp; ....Professor<br />
	　　　　　　袁祥仁 Cheung-Yan Yuen&nbsp; ....Hung Yat-San<br />
	　　　　　　秦沛 Paul Chun<br />
	　　　　　　王钟 Chung Wang<br />
	　　　　　　李健仁 Kin-Yan Lee</p>
<p>
	◎简　　介<br />
	剧情<br />
	　　苏乞儿原名苏灿，虽然武功盖世，但舞文弄墨一概不晓。苏为了搏得心上人如霜垂青，便投考武状元，更买通所有考官以为可以瞒天过海，但却遭人陷害，沦为乞儿。一日被丐帮长老选中为帮主，传以打狗棒法，他便藉此对付反政权分子天理教。<br />
	幕后制作<br />
	　　当年《武状元苏乞儿》上映时最使人好奇的，是周星驰与陈嘉上在食老本的《逃学威龙2》之后再度合作，会否擦出新火花？事实证明这回确有新的尝试，便是一改周尽情搞笑的作风，惹笑之处更表现他演技的一面，是周对悲喜剧的初步尝试，无厘头风格迈向深层次。连一向夸张的吴孟达与周星驰的几场父子情对手戏也丝丝入扣，显出了二人纯熟的默契并不止于搞笑而已。但严格说来，周星驰这次戏路上的自我突破也未算一击奏功，原因也是多方面的。剧本对角色际遇大起大落的过程转折描写欠细腻是其一，造型未够讨好是其二，但最重要的是为顾及观众反应，开首不能不以招牌形象和戏路出现。这固然可能使观众较易接受其后的转变，但也显得这次尝试小心翼翼。无论如何，周星驰能谨慎地踏出拓阔戏路的一步，总比重复剥削自己好。由陈嘉上掌舵，使本片的趣味也干净一些，制作认真之余还有点角色&ldquo;成长&rdquo;的主题，不至一味插科打诨。<img alt="" src="/uploads/allimg/c120525/133O0291H20-123512.jpg" style="width: 720px; height: 405px" /><img alt="" src="/uploads/allimg/c120525/133O0291RZ-139538.jpg" style="width: 720px; height: 405px" /><img alt="" src="/uploads/allimg/c120525/133O029193Z-144600.jpg" style="width: 720px; height: 405px" /></p>

<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="/uploads/allimg/c120524/133N2Z4FF-102231.jpg" />&nbsp;&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy67:piaohua@dy67.piaohua.com:1077/飘花电影piaohua.com武状元苏乞儿BD高清国粤双语1024分辨率.mkv </td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O02920430-152M1.jpg{/dede:field}
