{dede:field name='keywords'}13猛鬼/幽灵世界BD1280高清迅雷{/dede:field}
{dede:field name='description'}13猛鬼/幽灵世界BD1280高清迅雷下载、免费下载，13猛鬼/幽灵世界BD1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}13猛鬼/幽灵世界BD1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-21{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://hdmag.cz/files/covers/thir13en-ghosts-blu-ray_0.jpg" style="width: 541px; height: 696px" /></p>
<p>
	【影片原名】Thir13en Ghosts<br />
	【外文别名】Thir13en Ghosts<br />
	　　　　　　13 fant mes<br />
	　　　　　　13 Ghosts<br />
	　　　　　　13 fant mes<br />
	【中文译名】13猛鬼/幽灵世界<br />
	【出品公司】华纳兄弟公司<br />
	【出品年代】2001 年<br />
	【上映日期】2001年10月23日 美国 &nbsp;<br />
	【影片级别】Rated R for horror violence/gore, nudity and some language.<br />
	【官方网站】<a class="faqlink" href="http://www.13ghosts.com/">http://www.13ghosts.com/</a><br />
	【IMDB链接】<a href="http://www.bluemv.com">http://www.bluemv.com</a><br />
	【IMDB评分】5.0/10 (17,044 votes)<br />
	【国　　家】美国/加拿大<br />
	【类　　别】恐怖/惊悚<br />
	【导　　演】Steve Beck<br />
	【主　　演】托尼?夏尔赫布 Tony Shalhoub .....Arthur Kriticos<br />
	　　　　　　艾伯丝?戴维兹 Embeth Davidtz .....Kalina Oretzia<br />
	　　　　　　Matthew Lillard .....Dennis Rafkin<br />
	　　　　　　莎诺?伊丽莎白 Shannon Elizabeth .....Kathy Kriticos<br />
	　　　　　　Alec Roberts .....Robert &#39;Bobby&#39; Kriticos<br />
	　　　　　　JR?波恩 JR Bourne .....Benjamin Moss<br />
	　　　　　　Rah Digga .....Maggie Bess<br />
	　　　　　　F?莫里?亚伯拉罕 F. Murray Abraham .....Cyrus Kriticos<br />
	　　　　　　马修?哈里逊 Matthew Harrison .....Damon<br />
	　　　　　　Jacob Rupp .....Cyrus&#39; Assistant<br />
	　　　　　　Mike Crestejo .....Team Member<br />
	　　　　　　Aubrey Culp .....Team Member (as Aubrey Lee Culp)<br />
	　　　　　　Charles Andre .....Team Member<br />
	　　　　　　Mikhael Speidel .....Billy Michaels, The First Born Son<br />
	　　　　　　Daniel Wesley .....Jimmy &#39;The Gambler&#39; Gambino, The Torso<br />
	　　　　　　Laura Mennell .....Susan LeGrow, The Bound Woman<br />
	　　　　　　Kathryn Anderson .....Jean Kriticos, The Withered Lover<br />
	　　　　　　Craig Olejnik .....Royce Clayton, The Torn Prince<br />
	　　　　　　Shawna Loyer .....Dana Newman, The Angry Princess<br />
	　　　　　　Xantha Radley .....Isabella Smith, The Pilgrimess<br />
	　　　　　　C. Ernst Harth .....Harold Shelburne, The Great Child<br />
	　　　　　　Laurie Soper .....Margaret Shelburne, The Dire Mother<br />
	　　　　　　Herbert Duncanson .....George Markley, The Hammer<br />
	　　　　　　Shayne Wyler .....Ryan Kuhn, The Jackal<br />
	　　　　　　John DeSantis .....Breaker Mahoney, The Juggernaut<br />
	<br />
	<br />
	【内容简介】<br />
	<br />
	&nbsp; &nbsp; 过着平静生活的亚瑟（托尼?谢尔侯伯饰）一家，在某天接到了一个意外的通知：他们家一位疏离已久的远房叔父过世了，这位生性古怪孤僻的老人在临死前把自己的一幢大宅子作为遗产留给了他们。得到这笔遗产的亚瑟一家生活并不宽余，如今自然是喜出望外，于是一家人浩浩荡荡开赴那座古老的宅子。等他们看到这座宏伟的宅院时简直不敢相信自己的好运气。然而，亚瑟的大女儿、天生敏感的凯西（沙隆?伊丽莎白饰）开始隐约觉得这个大宅子似乎有些蹊跷。她的不祥预感一开始受到其他人的嘲笑，然而没过多久，一系列怪事发生在亚瑟家的成员身边。这座大房子果然蕴藏着某种诡异的力量，原来亚瑟那位的叔父生前有一个怪癖的嗜好―― 收集鬼魂，确切地说是冤魂，他把用毕生精力收集到的13个鬼魂用特殊的方法禁锢在这座大宅子的13间特制的玻璃房子里，而屋子里的所有房间也都是在星体运行变换的规律控制下不停地改变着结构&hellip;&hellip;冥冥中，是谁在操控着一切？在那些错落曲折的房间里，又隐藏着什么样的秘密？<br />
	<br />
	幕后制作：<br />
	<br />
	&nbsp; &nbsp; 刚开始看电影的海报，着实让人吓人一跳，其实一切都是有着怪癖嗜好的叔叔设的局，他企图让男主角亚瑟充当第13个鬼魂，从而启动时间机器去到未来。影片的镜头运用非常妥贴，处处埋下伏笔，快慢控制得很好，将观众的目光牢牢吸引住，惊吓度非常高。影片翻拍自恐怖电影界的大师级导演威廉?卡斯托（William Castle）摄制于20世纪60年的同名经典恐怖片《13 Ghosts》，制作公司Dark Castle成立于1999年初，目标就是重新推出类似卡斯托在20世纪50和60年代拍摄的中等成本的恐怖电影。1999年的《鬼屋惊魂》（House on Haunted Hill，老版摄于1958年）是该公司的开山之作，《13猛鬼》是第2部。<br />
	<br />
	&nbsp;稍后补图：</p>

<p>
	【下载地址】</p>
<table bgcolor="#0099cc" border="0" cellpadding="10" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.net" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy125:piaohua@dy125.piaohua.com:8025/飘花电影pioahua.com十三猛鬼BD中英双字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:8025/飘花电影pioahua.com十三猛鬼BD中英双字1280高清.rmvb</a></td>
		</tr>
		<tr>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1644620-291X.jpg{/dede:field}
