{dede:field name='keywords'}唐伯虎点秋香2之四大才子BD国粤{/dede:field}
{dede:field name='description'}唐伯虎点秋香2之四大才子BD国粤双语中字1024高清迅雷下载、免费下载，唐伯虎点秋香2之四大才子BD国粤双语中字1024高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}唐伯虎点秋香2之四大才子BD国粤双语中字1024高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-03-21{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://3e:3e@m1.eee4.cc:1510/【3e电影网www.eee4.cc】唐伯虎点秋香2之四大才子DVD国语中字.rmvb" target="_blank{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MO6443Z-3bB.jpg{/dede:field}
