{dede:field name='keywords'}星河舰队3：掠夺者/星河战队3BD{/dede:field}
{dede:field name='description'}星河舰队3：掠夺者/星河战队3BD中英双字1024/1280高清迅雷下载、免费下载，星河舰队3：掠夺者/星河战队3BD中英双字1024/1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}星河舰队3：掠夺者/星河战队3BD中英双字1024/1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-01-07{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://3e:3e@d8.3edyy.com:162/【3E电影院www.eee4.cc】星河战队3[BD中英双字1024x576高清版].rmvb" target="_blank{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MOV1210-54561.jpg{/dede:field}
