{dede:field name='keywords'}帕斯尚尔战役BD1280高清迅雷下载{/dede:field}
{dede:field name='description'}帕斯尚尔战役BD1280高清迅雷下载、免费下载，帕斯尚尔战役BD1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}帕斯尚尔战役BD1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-01-03{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://www.luangh.com/up/files/35/Passchendaele end 1.png" style="width: 441px; height: 573px" /></p>
<p>
	【影片原名】Passchendaele<br />
	【中文译名】帕斯尚尔战役<br />
	【出品年代】2008<br />
	【上映日期】2008年9月4日 &nbsp;加拿大<br />
	【类　　别】剧情/战争<br />
	【影片长度】114 Mins<br />
	【语 &nbsp; &nbsp; &nbsp;言】英语<br />
	【字 &nbsp; &nbsp; &nbsp;幕】中文<br />
	【IMDB评分】6.9/10 &nbsp; (2,983 votes)<br />
	【IMDB链接】<a href="http://www.imdb.com/title/tt1092082/" target="_blank">http://www.imdb.com/title/tt1092082/</a><br />
	<br />
	<b>※※※※※※※　影片简介　※※※※※※※</b><br />
	<br />
	【导　　演】保罗?格罗斯 Paul Gross<br />
	【主要演员】卡洛琳?达芙娜 Caroline Dhavernas....Sarah Mann<br />
	　　　　　　保罗?格罗斯 Paul Gross....Michael Dunne<br />
	　　　　　　吉尔?贝罗斯 Gil Bellows....Royster<br />
	　　　　　　Michael Greyeyes ....Highway<br />
	　　　　　　Adam Harrington ....Colonel Ormand<br />
	　　　　　　Tom Carey ....Witchell<br />
	　　　　　　Landon Liboiron ....Young German Soldier<br />
	　　　　　　David Brown ....Dr. Nigel Bernard<br />
	　　　　　　David Haysom ....Officer<br />
	　　　　　　Chris Ippolito ....Miles<br />
	　　　　　　Brian Jensen ....Major Bingham<br />
	　　　　　　Jayson Therrien ....MP<br />
	<br />
	【内容简介】<br />
	&nbsp; &nbsp; &nbsp;<br />
	&nbsp; &nbsp; &nbsp; &nbsp; Passchendaele战役，是一战最著名的战役，持续时间非常长，从1917年7月31日开始，到11月6日结束。负责指挥的英军统帅当时希望率领部队攻占比利时Passchendaele，摧毁德军的潜水艇基地。这不仅是严酷的战争，也是最血腥的战争，盟军有325000人伤亡，德军有260000人伤亡。不计其他破坏，这场战役的死亡人数为整个二次大战里美军总死亡人数的三分之一。战争最后以英军和加拿大军队攻占。Passchendaele而告结束。<br />
	　　 影片借一对恋人书信展现这一历史著名战役，宏大的场面揭露了战争的惨烈、残酷，及动荡时期人们渴望的爱与和平。</p>
<p>
	<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120102/18/62564813201201021832586452922993964_007.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120102/18/62564813201201021832586452922993964_006.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120102/18/62564813201201021832586452922993964_005.jpg" style="width: 720px; height: 405px" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="&#13;&#10;ftp://dy241:piaohua@dy241.piaohua.com:2020/飘花电影piaohua.com帕斯尚尔战役BD中字1280高清.rmvb">ftp://dy241:piaohua@dy241.piaohua.com:2020/飘花电影piaohua.com帕斯尚尔战役BD中字1280高清.rmvb </a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1514W50-23Q4.jpg{/dede:field}
