{dede:field name='keywords'}狗牙/犬齿之家BD1280高清迅雷下{/dede:field}
{dede:field name='description'}狗牙/犬齿之家BD1280高清迅雷下载、免费下载，狗牙/犬齿之家BD1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}狗牙/犬齿之家BD1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-25{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://www.highbd.net/file/75773/Kynodontas.png" style="width: 600px; height: 800px" /></p>
<p>
	◎译　　名　狗牙/犬齿之家(台)<br />
	◎片　　名　Dogtooth<br />
	◎年　　代　2009<br />
	◎国　　家　希腊<br />
	◎类　　别　喜剧/剧情<br />
	◎语　　言　希腊语<br />
	◎IMDB评分 7.5/10 (2,751 votes)<br />
	◎IMDB链接 <a class="faqlink" endcolor="FF6600" href="http://www.imdb.com/title/tt1379182" index="0" startcolor="0066ff" state="OFF" style="color: #0066ff">http://www.imdb.com/title/tt1379182</a><br />
	◎片　　长　93 Mins<br />
	◎导　　演　欧格斯&middot;兰斯莫斯 Yorgos Lanthimos<br />
	◎主　　演　Christos Stergioglou &nbsp;....Father<br />
	　　　　　　Michele Valley &nbsp;....Mother<br />
	　　　　　　Aggeliki Papoulia &nbsp;....Older Daughter<br />
	　　　　　　Mary Tsoni &nbsp;....Younger Daughter<br />
	　　　　　　Hristos Passalis &nbsp;....Son<br />
	　　　　　　Anna Kalaitzidou &nbsp;....Christina<br />
	　　　　　　Alexander Voulgaris &nbsp;....Dog trainer<br />
	　　　　　　<br />
	◎简　　介　<br />
	　　影片讲述了一个与外界切断来源的疯狂畸形的家庭，过着隐居的生活，家里的三个孩子为父亲所强迫别无选择，唯一能够进入这个家庭的人是父亲公司的员工克丽丝汀娜，她来到这里是为了满足儿子的欲望&hellip;&hellip;<br />
	幕后制作<br />
	　　希腊导演欧格斯&middot;兰斯莫斯自1995年开始从事影视制作，《狗牙》是他继《吉尼塔》之后的第二部长片作品。<br />
	　　从小到大，三兄妹住在围墙之内的美丽别墅，从未踏出一步。他们活在被建构的完美世界里，像是外星人，只绕着父母的逻辑旋转。父亲请来公司女职员，固定与儿子做爱，只是没料到她还私下传授性知识，搅乱平衡的家庭关系&hellip;&hellip;全片充满怪诞、荒谬与人性的扭曲，让人从冷笑渐渐转为恐惧，戛纳电影节首映引发全场极大争议。</p>
<p>
	<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120524/20/62564813201205242019017405027424335_004.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120524/20/62564813201205242019017405027424335_003.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120524/20/62564813201205242019017405027424335_000.jpg" style="width: 720px; height: 405px" /><br />
	<br />
	&nbsp;</p>
<p>
	【下载地址】</p>
<table bgcolor="#0099cc" border="0" cellpadding="10" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaobajie.com" target="_blank">http://www.xiaobajie.com</a></td>
		</tr>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy125:piaohua@dy125.piaohua.com:8098/飘花电影piaohua.com狗牙BD中字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:8098/飘花电影piaohua.com狗牙BD中字1280高清.rmvb</a></td>
		</tr>
		<tr>
		</tr>
	</tbody>
</table>
<br />{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O16022550-22544.jpg{/dede:field}
