<?php
$z[0]=Array("field","深海寻宝_碧海追踪迅雷下载，免",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","深海寻宝_碧海追踪迅雷下载、免费下载，深海寻宝_碧海追踪Gvod高清在线播放，剧情介绍等。",72,200);
$z[1][4]['name']="description";
$z[2]=Array("field","深海寻宝_碧海追踪",202,257);
$z[2][4]['name']="title";
$z[3]=Array("field","",259,298);
$z[3][4]['name']="writer";
$z[4]=Array("field","",300,339);
$z[4][4]['name']="source";
$z[5]=Array("field","2007-12-20",341,391);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",393,430);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://eee4.com:eee4@xl2.eee4.com:8881/深海寻宝/[3E迅雷电影站www.eee4.com]深海寻宝A.rmvb\" target=_blank>ftftp://eee4.com:eee4@xl2.eee4.com:8881/深海寻宝/[3E迅雷电影站www.eee4.com]深海寻宝A.rmvb</A></TD></TR></TBODY></TABLE>CD2:<BR>\r\n<TABLE style=\"BORDER-RIGHT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; BORDER-BOTTOM: #cccccc 1px dotted\" cellSpacing=0 cellPadding=6 width=\"95%\" align=center border=0>\r\n<TBODY>\r\n<TR>\r\n<TD style=\"WORD-WRAP: break-word\" bgColor=#fdfddf><ANCHOR></ANCHOR><A href=\"ftftp://eee4.com:eee4@xl2.eee4.com:8881/深海寻宝/[3E迅雷电影站www.eee4.com]深海寻宝B.rmvb\" target=_blank>ftftp://eee4.com:eee4@xl2.eee4.com:8881/深海寻宝/[3E迅雷电影站www.eee4.com]深海寻宝B.rmvb</A></TD></TR></TBODY></TABLE></div><ul class=\"mmlist",432,1274);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MPU15F-3N13.jpg",1276,1357);
$z[8][4]['name']="litpic";

?>