{dede:field name='keywords'}致命接触：美国禽流感[DVD中字]{/dede:field}
{dede:field name='description'}致命接触：美国禽流感[DVD中字]迅雷下载、免费下载，致命接触：美国禽流感[DVD中字]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}致命接触：美国禽流感[DVD中字]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2009-06-08{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://4e:4e@www2.eee4.com:607/[3E电影站www.eee4.com]致命接触：美国禽流感.rmvb" target="_blank{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MPVS30-32227.jpg{/dede:field}
