{dede:field name='keywords'}沉默的15分钟BD中字1024/1280高{/dede:field}
{dede:field name='description'}沉默的15分钟BD中字1024/1280高清2011最新名侦探柯南剧场版15迅雷下载、免费下载，沉默的15分钟BD中字1024/1280高清2011最新名侦探柯南剧场版15Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}沉默的15分钟BD中字1024/1280高清2011最新名侦探柯南剧场版15{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-12-05{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="/uploads/allimg/c120525/133O043S260-12BX.jpg" /></p>
<p>
	<img alt="" src="/uploads/allimg/c120525/133O043T020-133615.jpg" /></p>
<p>
	片名：名侦探柯南剧场版15：沉默的15分钟<br />
	类型：剧场版 / 推理&nbsp;<br />
	地区：日本<br />
	导演：山本泰一郎&nbsp;&nbsp;&nbsp;<br />
	编剧：古内一成&nbsp;&nbsp;&nbsp;<br />
	原作：青山刚昌<br />
	配音：高山南 / 山崎和佳奈 / 小山力也 / 林原惠美 / 大谷育江 /<br />
	动画制作：东宝映画&nbsp;&nbsp;&nbsp;<br />
	首播时间：2011年04月16日</p>
<p>
	【内容介绍】</p>
<p>
	「针对你这4年傲慢无礼的执政期，在此施下天理不容的警告。我等对你这个奸臣的死刑，早已万事具备只欠东风。朝仓知事的生杀大权，早已在我等手中。」<br />
	　　<br />
	12月的某一天，获得连任的朝仓东京都知事接到了谜一般的恐吓信。信中扬言将于次日在刚刚开通的都营新地铁隧道中实行爆炸！而多亏了从毛利小五郎那里了解到恐吓信之事的柯南，才在无人伤亡的情况下,避免了这一重大惨案的发生&hellip;&hellip;<br />
	　　<br />
	是怨恨朝仓的家伙预谋已久的犯罪吗？为了追查不惜造成巨大惨案的危险罪犯，而朝仓知事在出任国土交通大臣期间建造北泽水力发电站的相关者中，难道没有人充满怨恨吗？柯南等人前往大坝的建造地新潟县&hellip;&hellip;<br />
	　　<br />
	在庆祝北泽村迁移5周年的纪念典礼上人山人海，呈现了一副热闹繁华的景象。果然，犯人就藏匿在其中。在柯南正要开始调查的时候，竟然在雪原上发现了死因不明的尸体！这和地铁爆炸事件有什么联系吗？8年前的事故给村民们带来了怎样的心魔&hellip;&hellip;&ldquo;悲剧&rdquo; 牵出错综复杂的关系，如今灾难向人们袭来！！</p>

<p>
	<img alt="" src="/uploads/allimg/c120525/133O043U240-1435E.jpg" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="/uploads/allimg/c120524/133N2Z4FF-102231.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:1826/飘花电影piaohua.com沉默的15分钟DVD中字.rmvb</td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:2270/飘花电影piaohua.com沉默的15分钟BD中英双字1280高清.rmvb</td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:2279/飘花电影piaohua.com沉默的15分钟BD中英双字1024高清.rmvb</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O043V060-15B37.jpg{/dede:field}
