<?php
$z[0]=Array("field","唐山大地震/余震[BD国语+粤语中",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","唐山大地震/余震[BD国语+粤语中字1024x576+1280x720高清版]迅雷下载、免费下载，唐山大地震/余震[BD国语+粤语中字1024x576+1280x720高清版]Gvod高清在线播放，剧情介绍等。",72,276);
$z[1][4]['name']="description";
$z[2]=Array("field","唐山大地震/余震[BD国语+粤语中字1024x576+1280x720高清版]",278,371);
$z[2][4]['name']="title";
$z[3]=Array("field","",373,412);
$z[3][4]['name']="writer";
$z[4]=Array("field","",414,453);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-09-23",455,505);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",507,544);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://3e:3e@d8.3edyy.com:182/【3E看看www.3ekk.com】唐山大地震[真正DVD国语中字].rmvb\" target=_blank><FONT color=#0058b0>ftftp://3e:3e@d8.3edyy.com:182/【3E看看www.3ekk.com】唐山大地震[真正DVD国语中字].rmvb</FONT></A></TD></TR></TBODY></TABLE><BR><FONT color=#ff0000 size=2><STRONG>[下载地址]：<IMG border=0 src=\"httftp://www.eee4.cc/templets/img/down.jpg",546,938);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MPY20P-34923.jpg",940,1022);
$z[8][4]['name']="litpic";

?>