{dede:field name='keywords'}白雪公主：一个致命的夏天DVD中{/dede:field}
{dede:field name='description'}白雪公主：一个致命的夏天DVD中字2012最新美国恐怖大片迅雷下载、免费下载，白雪公主：一个致命的夏天DVD中字2012最新美国恐怖大片Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}白雪公主：一个致命的夏天DVD中字2012最新美国恐怖大片{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-21{/dede:field}
{dede:field name='body'}<p>
	&nbsp;<img src="http://img170.poco.cn/mypoco/myphoto/20120403/15/56643687201204031532411606475033588_004.jpg" /></p>
<p>
	◎译　　名　白雪公主：一个致命的夏天<br />
	◎片　　名　Snow White a Deadly Summer<br />
	◎年　　代　2012<br />
	◎国　　家　美国<br />
	◎类　　别　恐怖<br />
	◎语　　言　英语<br />
	◎字　　幕　中字<br />
	◎IMDB评分 4.9/10 (7 votes)<br />
	◎IMDB链接：<a href="http://www.bluemv.com" title="电影下载">http://www.bluemv.com</a><br />
	◎文件格式　DVD-RMVB<br />
	◎视频尺寸　720 x 400<br />
	◎文件大小　1CD 423MB<br />
	◎片　　长　83 mins<br />
	◎导　　演　David DeCoteau<br />
	◎主　　演　Shanley Caswell ... Snow<br />
	　　　　　　Maureen McCormick ... Eve<br />
	　　　　　　Eric Roberts ... Grant<br />
	　　　　　　Tim Abell ... Hunter<br />
	　　　　　　R.J. Cantu ... Bob</p>
<p>
	<br />
	◎简　　介　</p>
<p>
	　　这是个令人不安的恐怖故事。白雪是一个痛失母亲的叛逆少女, 当继母入门後, 一直把白雪当成眼中钉,於是怂恿白雪的父亲, 把她送去一个残酷的夏日训练营, 猎人们（营区长官们）也极力的欺压她们.她总相信有人企图要谋害她, 後来发现自己陷进了一个谎言和欺诈的圈套。七个救了她的小矮人（营队裡的朋友）离奇的一个个死去，白雪必须在自己成为下一个受害者前，揭露出这个黑暗而扭曲的秘密。</p>
<p>
	◎影片截图</p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120403/15/56643687201204031532411606475033588_000.jpg" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120403/15/56643687201204031532411606475033588_003.jpg" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120403/15/56643687201204031532411606475033588_002.jpg" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120403/15/56643687201204031532411606475033588_001.jpg" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.netftp://dy44:piaohua@dy44.piaohua.com:3132/" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3135/飘花电影piaohua.com白雪公主：一个致命的夏天DVD中字.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3135/飘花电影piaohua.com白雪公主：一个致命的夏天DVD中字.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O16450030-114B.jpg{/dede:field}
