{dede:field name='keywords'}蜜蜂总动员/蜜蜂电影[DVD中英双{/dede:field}
{dede:field name='description'}蜜蜂总动员/蜜蜂电影[DVD中英双字1024/1280高清版无水印]迅雷下载、免费下载，蜜蜂总动员/蜜蜂电影[DVD中英双字1024/1280高清版无水印]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}蜜蜂总动员/蜜蜂电影[DVD中英双字1024/1280高清版无水印]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-08-23{/dede:field}
{dede:field name='body'}<p>
	&nbsp;<img border="0" src="/uploads/allimg/c120525/133O04H13Z-1B095.jpg" style="max-width: 750px; max-height: 750px" /></p>
<p>
	◎译　　名　《蜜蜂电影/蜜蜂总动员》07美国票房过亿热门动画喜剧大片DVD中英双字1280x720高清版无水印<br />
	◎片　　名　Bee Movie<br />
	◎年　　代　2007<br />
	◎国　　家　美国/美国<br />
	◎类　　别　动画/喜剧/家庭/奇幻<br />
	◎语　　言　英语<br />
	◎字　　幕　中英字幕<br />
	◎IMDB评分 6.5/10 (7,426 votes)<br />
	◎IMDB链接 http://www.imdb.com/title/tt0389790<br />
	◎文件格式　XviD + AC3<br />
	◎视频尺寸　1280 x 720<br />
	◎文件大小　1CD 49 x 15MB<br />
	◎片　　长　90 Min<br />
	◎导　　演　史蒂夫&middot;希克纳 Steve Hickner<br />
	　　　　　　西蒙&middot;J&middot;史密斯 Simon J. Smith<br />
	◎主　　演　杰瑞&middot;宋飞 Jerry Seinfeld .....Barry B. Benson (voice)<br />
	　　　　　　芮妮&middot;齐薇格 Ren&eacute;e Zellweger .....Vanessa Bloome (voice)<br />
	　　　　　　马修&middot;布罗德里克 Matthew Broderick .....Adam Flayman (voice)<br />
	　　　　　　约翰&middot;古德曼 John Goodman .....Layton T. Montgomery (voice)<br />
	　　　　　　克里斯&middot;洛克 Chris Rock .....Mooseblood (voice)<br />
	　　　　　　帕特里克&middot;沃伯顿 Patrick Warburton .....Ken (voice)<br />
	　　　　　　凯西&middot;贝茨 Kathy Bates .....Janet Benson (voice)<br />
	　　　　　　Megan Mullally .....Trudy (voice)<br />
	　　　　　　雷普&middot;汤恩 Rip Torn .....Lou Lo Duca (voice)<br />
	　　　　　　拉里&middot;米勒 Larry Miller .....gvodBuzzwell (voice)<br />
	　　　　　　巴瑞&middot;莱文森 Barry Levinson .....Martin Benson (voice)<br />
	　　　　　　David Herman .....Buzz / Bob Bumble / Gammel / Pilot (voice)<br />
	　　　　　　Tom Papa .....Splitz / Klauss Vanderhayden<br />
	　　　　　　莱瑞&middot;金 Larry King .....Bee Larry King (voice)<br />
	　　　　　　 雷&middot;利奥塔 Ray Liotta .....Ray Liotta (voice)<br />
	<br />
	◎简　　介　<br />
	<br />
	　　怎么说呢？任何族群里都会出现那么一两个异类，即便是整日劳作的小蜜蜂，也有走出蜂箱看世界的时候。相信你在看过了这部极具颠覆意义的影片之后，将会改变自己最初对蜜蜂的那些约定俗成的观念&hellip;&hellip;巴瑞&middot;B&middot;拜森与他的蜜蜂伙伴们有那么一点不一样，虽然同样很勤劳，但他的想象力就有些出格了。从蜜蜂学校正式毕业之后，巴瑞不想从事那份早在他出生的时候就安排好的工作--像其他小蜜蜂那样整日忙进忙出，以一只工蜂的身份制造蜂蜜。</p>

<p>
	【电影截图】：<br />
	<br />
	&nbsp;<img border="0" src="/uploads/allimg/c120525/133O04H3B0-1J963.jpg" style="max-width: 750px; max-height: 750px" /></p>
<p>
	<img border="0" src="/uploads/allimg/c120525/133O04H42P-1T053.jpg" style="max-width: 750px; max-height: 750px" /></p>
<p>
	07美国票房过亿热门动画喜剧大片《蜜蜂总动员》DVD中英双字1280x720高清版无水印 ：<img border="0" src="http://www.eee4.com/templets/img/down.jpg" /></p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				ftp://3e:3e@www2.eee4.com:604/[3E电影站www.eee4.com]蜜蜂总动员DVD中英双字1280x720高清版无水印.rmvb</td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				ftp://dy44:piaohua@dy44.piaohua.com:1379/飘花电影piaohua.com蜜蜂总动员1024高清.rmvb</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O04H6040-206400.jpg{/dede:field}
