{dede:field name='keywords'}日本2011年恶整大赏HD日语中字12{/dede:field}
{dede:field name='description'}日本2011年恶整大赏HD日语中字1280高清超级爆笑整人游戏综艺迅雷下载、免费下载，日本2011年恶整大赏HD日语中字1280高清超级爆笑整人游戏综艺Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}日本2011年恶整大赏HD日语中字1280高清超级爆笑整人游戏综艺{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-02-23{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img165.poco.cn/mypoco/myphoto/20120223/23/1787098020120223235912019.jpg" style="width: 640px; height: 360px" /></p>
<p>
	影片简介：<br />
	&nbsp; &nbsp;&nbsp; &nbsp; 2011年日韩综艺《日本2011年恶整大赏》超级爆笑整人游戏综艺。</p>
<p>
	<img alt="" src="http://img165.poco.cn/mypoco/myphoto/20120223/23/17870980201202232336293693413617343_021.jpg" style="width: 640px; height: 360px" /><img alt="" src="http://img165.poco.cn/mypoco/myphoto/20120223/23/17870980201202232336293693413617343_016.jpg" style="width: 640px; height: 360px" /><img alt="" src="http://img165.poco.cn/mypoco/myphoto/20120223/23/17870980201202232336293693413617343_015.jpg" style="width: 640px; height: 360px" /></p>

<p>
	[下载地址]：<img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" /></p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy241:xiaobajie@222.187.221.241:2041/小八戒电影xiaobajie.com日本2011年恶整大赏HD日语中字1280高清.rmvb">ftp://dy241:xiaobajie@222.187.221.241:2041/小八戒电影xiaobajie.com日本2011年恶整大赏HD日语中字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1C9320-51138.jpg{/dede:field}
