{dede:field name='keywords'}公主日记/麻雀变公主BD中英双字1{/dede:field}
{dede:field name='description'}公主日记/麻雀变公主BD中英双字1024高清迅雷下载、免费下载，公主日记/麻雀变公主BD中英双字1024高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}公主日记/麻雀变公主BD中英双字1024高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-14{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://e7:e7@xl2.eee4.com:9306/[3E电影站www.eee4.com]公主日记DVD中英双字CD1.rmvb" target="_blank{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MO593M0-42211.jpg{/dede:field}
