<?php
$z[0]=Array("field","黑眼圈迅雷下载，免费下载，Gvod",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","黑眼圈迅雷下载、免费下载，黑眼圈Gvod高清在线播放，剧情介绍等。",73,179);
$z[1][4]['name']="description";
$z[2]=Array("field","黑眼圈",181,225);
$z[2][4]['name']="title";
$z[3]=Array("field","",227,266);
$z[3][4]['name']="writer";
$z[4]=Array("field","",268,307);
$z[4][4]['name']="source";
$z[5]=Array("field","2008-03-25",309,359);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",361,398);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://eee4.com:8044@vip11.eee4.com:8044/黑眼圈/[3E迅雷电影站www.eee4.com]黑眼圈.rmvb\" target=_blank>ftftp://eee4.com:8044@vip11.eee4.com:8044/黑眼圈/[3E迅雷电影站www.eee4.com]黑眼圈.rmvb</A></TD></TR></TBODY></TABLE></div><ul class=\"mmlist",400,678);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MP445320-1T54.jpg",680,763);
$z[8][4]['name']="litpic";

?>