{dede:field name='keywords'}笑傲江湖HD高清1024*576许冠杰{/dede:field}
{dede:field name='description'}笑傲江湖HD高清1024*576许冠杰版粤语中字迅雷下载、免费下载， 笑傲江湖HD高清1024*576许冠杰版粤语中字Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}笑傲江湖HD高清1024*576许冠杰版粤语中字{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-08-19{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20110819/10/62564813201108191026592485206248273_005.jpg" /><img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20110819/10/62564813201108191026592485206248273_004.jpg" /></p>
<p>
	文名： 笑傲江湖 粤语<br />
	英文名： Swordsman<br />
	导&nbsp;&nbsp; 演： 程小东 胡金铨<br />
	主&nbsp;&nbsp; 演： 许冠杰 张敏 叶童<br />
	类&nbsp;&nbsp; 型： 动作<br />
	地&nbsp;&nbsp; 区： 港台<br />
	发&nbsp;&nbsp; 行： 1990<br />
	评&nbsp;&nbsp; 分：&nbsp; 6.90<br />
	规&nbsp;&nbsp; 格： 1024x576<br />
	禁宫武功秘籍《葵花宝典》被盗，锦衣卫大太监古金福疑林震南为内奸，下令年轻太监欧阳全截杀林氏父子。林震南不敌，临终前托华山派弟子令孤冲将宝典所在之处转告其子平之。欧阳全假扮平之混入华山，华山派掌门岳不群与其狼狈为奸，引令孤冲说出宝典所在，令孤冲得知岳不群为人，一场争夺《葵花宝典》随即展开&hellip;&hellip;</p>

<p>
	截图：<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20110819/10/62564813201108191026592485206248273_002.jpg" /><img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20110819/10/62564813201108191026592485206248273_003.jpg" style="width: 1024px; height: 576px" /><img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20110819/10/62564813201108191026592485206248273_001.jpg" /><img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20110819/10/62564813201108191026592485206248273_000.jpg" /></p>

[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
<tbody>
<tr>
<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
<a href="
ftp://dy125:piaohua@dy125.piaohua.com:2027/飘花电影piaohua.com笑傲江湖HD高清1024分辨率.rmvb">
ftp://dy125:piaohua@dy125.piaohua.com:2027/飘花电影piaohua.com笑傲江湖HD高清1024分辨率.rmvb </a></td>
</tr>
</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1B95310-25338.jpg{/dede:field}
