{dede:field name='keywords'}圣斗士星矢剧场版5：天界篇序奏B{/dede:field}
{dede:field name='description'}圣斗士星矢剧场版5：天界篇序奏BD国语中字1024/1280高清迅雷下载、免费下载，圣斗士星矢剧场版5：天界篇序奏BD国语中字1024/1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}圣斗士星矢剧场版5：天界篇序奏BD国语中字1024/1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-01-18{/dede:field}
{dede:field name='body'}<p>
	<img alt="" border="0" src="http://img.album.pchome.net/54/85/02/67/0113e8daf8805843ec1fc93bdb302cba.jpg" /></p>
<p>
	◎译　　名　圣斗士星矢剧场版5：天界篇序奏<br />
	◎片　　名　Saint Seiya: The Heaven Chapter - Overture<br />
	◎年　　代　2004<br />
	◎国　　家　日本<br />
	◎类　　别　动画/奇幻<br />
	◎语　　言　国日双语<br />
	◎字　　幕　中文<br />
	◎IMDB评分&nbsp; 7.1/10 (210&nbsp; votes)<br />
	◎文件格式　1024 x 576<br />
	◎文件格式　x264 + AAC<br />
	◎文件大小　1CD<br />
	◎片　　长　1h:23m:30s<br />
	◎导　　演　山内重保&nbsp; Shigeyasu Yamauchi<br />
	◎主　　演　古谷彻 T?ru Furuya&nbsp; ....Seiya (voice)<br />
	　　　　　　铃置洋孝 Hirotaka Suzuoki&nbsp; ....Shiryu (Dragon) (voice)<br />
	　　　　　　桥本晃一 K?ichi Hashimoto&nbsp; ....Hyoga (Cygnus) (voice)<br />
	　　　　　　堀川亮 Ry? Horikawa&nbsp; ....Shun (Andromeda) (voice)<br />
	　　　　　　堀秀行 Hideyuki Hori&nbsp; ....Ikki (Phoenix) (voice)<br />
	　　　　　　潘惠子 Keiko Han&nbsp; ....Sayori Kido (Athena) (voice)<br />
	　　　　　　乡里大辅 Daisuke G?ri&nbsp; ....Man (voice)<br />
	◎简　　介<br />
	<br />
	&nbsp; &nbsp; 与冥王哈迪斯惨烈战斗终于结束，世界再次回到光明之中。但对于圣斗士来说，却伤亡何其惨重。黄金圣斗士全部阵亡，星矢虽然在最后的决战中侥幸逃生，却落得五感尽失，形同废人。<br />
	<br />
	&nbsp; &nbsp; 然而，这来之不易的和平却无法持续太久，在经历了撒加叛乱、海神波塞冬、冥王哈迪斯等危机之后，另一支邪恶之手也向人类世界伸来。这便是月神阿尔特弥斯。她此番带领神斗士前来，企图将人类消灭。对于雅典娜及其麾下的圣斗士来说，这是前所未有的大危机&hellip;&hellip;&nbsp; &nbsp;<br />
	<br />
	<img alt="" border="0" src="http://img.album.pchome.net/54/85/07/05/bc4baf41d6013eda464bf138d4e40458.jpg" /><br />
	<img alt="" border="0" src="http://img.album.pchome.net/54/85/07/05/03043efdbfbfda53a892e3b3feb3b0ca.jpg" /></p>


<p>
	[下载地址]： &nbsp;<img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" /></p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2653/飘花电影piaohua.com圣斗士星矢剧场版5：天界篇序奏BD国语中字1024高清.mkv">ftp://dy44:piaohua@dy44.piaohua.com:2653/飘花电影piaohua.com圣斗士星矢剧场版5：天界篇序奏BD国语中字1024高清.mkv</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2653/飘花电影piaohua.com圣斗士星矢剧场版5：天界篇序奏BD国语中字1280高清.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2653/飘花电影piaohua.com圣斗士星矢剧场版5：天界篇序奏BD国语中字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1B1NZ-4XP.jpg{/dede:field}
