<?php
$z[0]=Array("field","铁门高清720P,1280*720迅雷下载",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","铁门高清720P 1280*720迅雷下载、免费下载，铁门高清720P 1280*720Gvod高清在线播放，剧情介绍等。",72,208);
$z[1][4]['name']="description";
$z[2]=Array("field","铁门高清720P 1280*720",210,269);
$z[2][4]['name']="title";
$z[3]=Array("field","",271,310);
$z[3][4]['name']="writer";
$z[4]=Array("field","",312,351);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-07-31",353,403);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",405,442);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://dy195:piaohua@dy195.piaohua.com:1003/飘花电影下载站www.piaohua.com铁门720p.mkv",444,567);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MP3M350-14523.jpg",569,652);
$z[8][4]['name']="litpic";

?>