{dede:field name='keywords'}原样复制/合法副本[DVD中字]迅雷{/dede:field}
{dede:field name='description'}原样复制/合法副本[DVD中字]迅雷下载、免费下载，原样复制/合法副本[DVD中字]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}原样复制/合法副本[DVD中字]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-01-11{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://6e:6e@d6.3edyy.com:612/【3E看看www.3ekk.com】原样复制[DVD中字].rmvb" target=_blank>ftftp://6e:6e@d6.3edyy.com:612/【3E看看www.3ekk.com】原样复制[DVD中字].rmvb</A></TD></TR></TBODY></TABLE></div><ul class="mmlist{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MP4A530-4F06.jpg{/dede:field}
