{dede:field name='keywords'}天与地HD高清修正迅雷下载，免费{/dede:field}
{dede:field name='description'}天与地HD高清修正迅雷下载、免费下载，天与地HD高清修正Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}天与地HD高清修正{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-10-28{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://www.luangh.com/up/files/34/td_thumb.jpg" /></p>
<p>
	中文： 天与地<br />
	英文： Chinese Untouchables，Tian Di，Heaven and Earth<br />
	类别： 剧情/动作/战争 &nbsp;<br />
	<br />
	主演： 刘德华，Andy Lau，刘松仁<br />
	公司： 华纳兄弟公司<br />
	发行： 1994年2月11日<br />
	地区： 香港，美国<br />
	语言： 国语<br />
	颜色： 彩色<br />
	等级： Germany:18，Spain:18<br />
	简介:<br />
	<br />
	海报 张一鹏（刘德华）由于获得了一笔奖学金而到法国深造。受西方文化和价值观的熏陶，他十分崇尚西方的法律体系和社会秩序。当他回到中国后，他被任命为禁止鸦片的第一专员。为了取缔所有的非法鸦片贸易，他偕同妻子（陈少霞）来到了上海。警察署长倪（顾宝明）和黑手党头子戴（刘松仁）是拜把兄弟，一起控制着上海所有的非法交易，在数次向张行贿失败后，他们竟残忍的将张的妻子杀死，然而，所有这一切却更加坚定了张铲除恶势力的决心&hellip;&hellip;<br />
	<br />
	评价:<br />
	<br />
	片名为《天与地》的电影大家熟悉应该有两部，一部是奥利弗斯通的，一部便是黎大炜的。对于后者的印象是很深刻的，当年一直在努力收藏齐刘德华的一百多部电影，于是从最初的录像带，到VCD，再到现在的DVD，依然没有齐集他所有的作品，虽可惜，不过在收集过程中，看了很多他的电影，《天与地》便是其中我比较喜欢的早期电影。在这部电影的投资是他本人，出品人里很明显的看了刘德华的名字，也许他才那么卖力的出演，从今天看来，他始终都努力的走在这个圈子里。<br />
	<br />
	一部关于禁毒的电影，年轻的禁毒专员在强权前面，不畏不惧；他不妥协乱世的苟且与堕落；他不知道上海这个地方的可怕，十里洋场，都是勾结，在种种的勾结下，他失去了妻儿，失去了战友，失去了朋友。于是他破釜沉舟，在精心安排下，以为可以了结一切恩怨，快意恩仇，做一个终结；可惜，结局的悲惨的，对不起，是你生不逢时；他还是倒在勾结之下。熟悉的歌曲想起，一曲《忘情水》带起片尾字幕。<br />
	<br />
	演员方面，刘德华的出演一向都是努力的；陈少霞还少在电影里出现，表演也很熟练；刘松仁把坏人演得很极致，动作，表情，每句台词都很老道；金世杰和俞飞鸿，两位应该是台湾的吧。金世杰跟刘德华后来在《黑金》里也有一段合作。</p>
<p>
	<img alt="" src="http://img165.poco.cn/mypoco/myphoto/20111028/08/62564813201110280816102160733568183_002.jpg" style="width: 650px; height: 366px" /><img alt="" src="http://img165.poco.cn/mypoco/myphoto/20111028/08/62564813201110280816102160733568183_001.jpg" style="width: 650px; height: 366px" /><img alt="" src="http://img165.poco.cn/mypoco/myphoto/20111028/08/62564813201110280816102160733568183_000.jpg" style="width: 650px; height: 366px" /><br />
	&nbsp;</p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="&#13;&#10;ftp://dy125:piaohua@dy125.piaohua.com:7102/飘花电影piaohua.com天与地HD国语中字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:7102/飘花电影piaohua.com天与地HD国语中字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1C251Z-322J.jpg{/dede:field}
