<?php
$z[0]=Array("field","向着炮火/七十一/到炮火中去[BD",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","向着炮火/七十一/到炮火中去[BD中字1024x576+1280x720高清版]迅雷下载、免费下载，向着炮火/七十一/到炮火中去[BD中字1024x576+1280x720高清版]Gvod高清在线播放，剧情介绍等。",72,280);
$z[1][4]['name']="description";
$z[2]=Array("field","向着炮火/七十一/到炮火中去[BD中字1024x576+1280x720高清版]",282,377);
$z[2][4]['name']="title";
$z[3]=Array("field","",379,418);
$z[3][4]['name']="writer";
$z[4]=Array("field","",420,459);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-03-27",461,511);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",513,550);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://7e:7e@m1.eee4.cc:1521/【3e电影网www.eee4.cc】向着炮火DVD中字.rmvb\" target=_blank>ftftp://7e:7e@m1.eee4.cc:1521/【3e电影网www.eee4.cc】向着炮火DVD中字.rmvb</A></TD></TR></TBODY></TABLE><BR><FONT color=#ff0000 size=2><STRONG>[下载地址]：<IMG border=0 src=\"httftp://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg",552,919);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MP6351F-13V3.jpg",921,1003);
$z[8][4]['name']="litpic";

?>