{dede:field name='keywords'}超人归来BD中英双字1024/1280高{/dede:field}
{dede:field name='description'}超人归来BD中英双字1024/1280高清迅雷下载、免费下载，超人归来BD中英双字1024/1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}超人归来BD中英双字1024/1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-11-02{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://e16:e16@xl2.eee4.com:1003/[3E电影站www.eee4.com]超人归来DVD中英双字.rmvb" target="_blank{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MO96340-5M62.jpg{/dede:field}
