{dede:field name='keywords'}義起守住欢乐2012跨年晚会迅雷下{/dede:field}
{dede:field name='description'}義起守住欢乐2012跨年晚会迅雷下载、免费下载，義起守住欢乐2012跨年晚会Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}義起守住欢乐2012跨年晚会{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-01-03{/dede:field}
{dede:field name='body'}<p>
	<img alt="" border="0" src="/uploads/allimg/c120525/133O0aR960-I9B.jpg" /></p>
<p>
	<img alt="" border="0" src="/uploads/allimg/c120525/133O0aTR0-S113.jpg" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				&nbsp;ftp://dy44:piaohua@dy44.piaohua.com:2496/飘花电影piaohua.com一起守住欢乐2012跨年晚会CD1.rmvb </td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				&nbsp;ftp://dy44:piaohua@dy44.piaohua.com:2496/飘花电影piaohua.com一起守住欢乐2012跨年晚会CD2.rmvb </td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O0aV050-c0E.jpg{/dede:field}
