{dede:field name='keywords'}时代精神3/时代精神：维纳斯计划{/dede:field}
{dede:field name='description'}时代精神3/时代精神：维纳斯计划[DVD中英双字]迅雷下载、免费下载，时代精神3/时代精神：维纳斯计划[DVD中英双字]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}时代精神3/时代精神：维纳斯计划[DVD中英双字]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-03-16{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://3e:3e@d6.3edyy.com:630/【3E看看www.3ekk.com】时代精神3：迈步向前[DVD中英双字].rmvb" target=_blank>ftftp://3e:3e@d6.3edyy.com:630/【3E看看www.3ekk.com】时代精神3：迈步向前[DVD中英双字].rmvb</A></TD></TR></TBODY></TABLE></div><ul class="mmlist{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MQ4L1Z-1K15.jpg{/dede:field}
