<?php
$z[0]=Array("field","马利和我BD中英双字1024/1280高",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","马利和我BD中英双字1024/1280高清迅雷下载、免费下载，马利和我BD中英双字1024/1280高清Gvod高清在线播放，剧情介绍等。",72,228);
$z[1][4]['name']="description";
$z[2]=Array("field","马利和我BD中英双字1024/1280高清",230,299);
$z[2][4]['name']="title";
$z[3]=Array("field","",301,340);
$z[3][4]['name']="writer";
$z[4]=Array("field","",342,381);
$z[4][4]['name']="source";
$z[5]=Array("field","2012-05-21",383,433);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",435,472);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://e6:e6@xl2.eee4.com:9306/[3E电影站www.eee4.com]马利和我DVD中英双字CD1.rmvb\" target=\"_blank",474,608);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MOK0950-32306.jpg",610,693);
$z[8][4]['name']="litpic";

?>