{dede:field name='keywords'}隔绝高清迅雷下载，免费下载，Gv{/dede:field}
{dede:field name='description'}隔绝高清迅雷下载、免费下载，隔绝高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}隔绝高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-21{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120330/08/62564813201203300825093683850873379_000.jpg" style="width: 650px; height: 835px" /></p>
<p>
	【影片原名】The Divide<br />
	【中文译名】隔绝<br />
	【出品公司】Anchor Bay Films<br />
	【出品年代】2011 年<br />
	【上映日期】2012年01月23日 美国<br />
	【影片级别】USA: PG<br />
	【官方网站】<a href="http://www.thedividethemovie.com/" target="_blank">http://www.thedividethemovie.com/</a><br />
	【IMDB链接】<a href="http://www.bluemv.com" title="电影下载">http://www.bluemv.com</a><br />
	【IMDB评分】6.9/10 &nbsp;(655 votes)<br />
	【国　　家】美国/德国/英国<br />
	【类　　别】科幻/惊悚/悬疑<br />
	【导　　演】泽维尔&middot;吉恩斯<br />
	【主　　演】劳伦&middot;日尔曼 Lauren German &nbsp;....Eva<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 米洛&middot;文堤米利亚 Milo Ventimiglia &nbsp;....Josh<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 迈克尔&middot;比恩 Michael Biehn &nbsp;....Mickey<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 迈克尔&middot;艾克朗德 Michael Eklund &nbsp;....Bobby<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 罗姗娜&middot;阿奎特 Rosanna Arquette &nbsp;....Marilyn<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 考特尼&middot;万斯 Courtney B. Vance &nbsp;....Delvin<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Iv&aacute;n Gonz&aacute;lez &nbsp;....Sam<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 艾什顿&middot;霍尔姆斯 Ashton Holmes &nbsp;....Adrien<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Jennifer Blanc &nbsp;....Liz<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Abbey Thickson &nbsp;....Wendy<br />
	<br />
	【剧情简介】<br />
	<br />
	&nbsp; &nbsp; &nbsp; 影片讲述纽约市一场灾难性的爆炸后，8个陌生人躲进了一座公寓大楼的地下室中。地下室由三个相连的房间组成，幸运的是里面有食物和水储备着，8个幸存者于是开始等待救援&hellip;&hellip;直到一个身着核生化防护服的男子出现&hellip;&hellip;他是来寻找什么的？是什么让他如此残忍冷酷？当生化防护服的一小队人马暂时退去，更糟的情况来了，幽闭恐惧症让这次从避难所变成了牢笼&hellip;&hellip;误解及羁绊又如何化解？<br />
	<br />
	【幕后制作】<br />
	<br />
	&nbsp; &nbsp;由《杀手：代号47》（Hitman）导演Xavier Gens执导的科幻惊悚片《隔绝》（The Divide）讲述了末日之后的纽约，8个幸存者在地下掩体里，等待救援的同时展开相互攻歼。<br />
	　　影片主演有米洛&middot;文堤米利亚（Milo Ventimiglia）、迈克尔&middot;比恩（Michael Biehn）、罗姗娜&middot;阿奎特（Rosanna Arquette）等.<br />
	&nbsp;<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120330/08/62564813201203300821073721602833361_011.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120330/08/62564813201203300821073721602833361_009.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120330/08/62564813201203300821073721602833361_008.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120330/08/62564813201203300821073721602833361_006.jpg" style="width: 720px; height: 405px" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="
ftp://dy125:piaohua@dy125.piaohua.com:7789/飘花电影piaohua.com隔绝BD中英双字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:7789/飘花电影piaohua.com隔绝BD中英双字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O16452Z-54511.jpg{/dede:field}
