{dede:field name='keywords'}李赛凤绝版末路狂花迅雷下载，免{/dede:field}
{dede:field name='description'}李赛凤绝版末路狂花迅雷下载、免费下载，李赛凤绝版末路狂花Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}李赛凤绝版末路狂花{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-07-31{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="/uploads/allimg/c120525/133O042I5P-142534.jpg" style="width: 400px; height: 657px" /></p>
<p>
	◎译　　名　末路狂花<br />
	◎年　　代　1992<br />
	◎国　　家　中国香港<br />
	◎类　　型　喜剧<br />
	◎片　　源　DVD<br />
	◎视　　频　576 x 432<br />
	◎音　　频　普通话<br />
	◎体　　积　1CD<br />
	◎时　　间　103 Mins<br />
	◎字　　幕　中英（内嵌）<br />
	◎IMDB评分　N/A<br />
	◎IMDB链接　N/A<br />
	◎导　　演　赖建国<br />
	◎演　　员　丽菁/李赛凤/李子雄/大岛由加利<br />
	◎剧　　情　<br />
	文箐与阿美是对行影不离的好朋友二人同在警界供职又同时爱上了警官江威臣，但已与阿美同居了</p>
<p>
	很久的江却突然宣布要与文菁结婚并移民美国，阿美极力想劝江回心转意但江执意不愿阿美经受不</p>
<p>
	了打击精神崩溃了，狂怒之下意开枪打死了江极度惊恐龙之中的阿美将此事告诉了同事张少基心怀</p>
<p>
	叵测的张指控文箐杀害了江转眼之间文青成了被警方通缉的杀人犯，为了澄清罪责，文青四处寻找</p>
<p>
	阿美阿美也欲除掉文青以绝后患，昔日的好友成了不共戴天的仇人。</p>
<p>
	◎截　　图：</p>
<p>
	<img alt="" src="/uploads/allimg/c120525/133O042J2P-154246.jpg" /><img alt="" src="/uploads/allimg/c120525/133O042J910-1A431.jpg" /><img alt="" src="/uploads/allimg/c120525/133O042K530-1H218.jpg" /><img alt="" src="/uploads/allimg/c120525/133O042L240-1X954.jpg" style="width: 576px; height: 432px" /></p>
<p>
	[末路狂花下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="/uploads/allimg/c120524/133N2Z4FF-102231.jpg" />&nbsp;&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="word-break: break-all; line-height: 18px" width="100%">
				ftp://dy195:piaohua@dy195.piaohua.com:1000/飘花电影下载站www.xiaozhizhu.net末路狂花国语中字.rmvb </td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O042LW0-1aR4.jpg{/dede:field}
