{dede:field name='keywords'}倚天屠龙记之魔教教主HD高清双语{/dede:field}
{dede:field name='description'}倚天屠龙记之魔教教主HD高清双语1024*576迅雷下载、免费下载，倚天屠龙记之魔教教主HD高清双语1024*576Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}倚天屠龙记之魔教教主HD高清双语1024*576{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-09-10{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20110909/15/62564813201109091515103113038254532_000.jpg" /></p>
<p>
	【片 名】：《倚天屠龙记之魔教教主》<br />
	【外文名】：The Kung Fu Cult Master<br />
	【类 型】：古装/武侠/动作<br />
	【语 言】：国粤双语<br />
	【片 长】：103分钟<br />
	【地 区】：中国香港<br />
	【上映时间】：1993年12月18日</p>
<p>
	<br />
	演员表：<br />
	李连杰 饰 张无忌<br />
	　　邱淑贞 饰 小　昭<br />
	　　张 敏 饰 赵敏、殷素素<br />
	　　洪金宝 饰 张三丰<br />
	　　黎 姿 饰 周芷若<br />
	　　梁家仁 饰 鹿杖客<br />
	　　吴耀汉 饰 青翼蝠王<br />
	　　孙梦泉 饰 灭绝师太<br />
	　　邹兆龙 饰 宋青书<br />
	　　吴镇宇 饰 张翠山<br />
	　　张春仲 饰 鹤笔翁<br />
	　　曹 荣 饰 少林和尚（龙爪手）<br />
	　　马子俊 饰 少林方丈<br />
	　　田启文 饰 华山二老之一（红十字会的...）<br />
	　　闫怀礼 饰 金毛狮王</p>
<p>
	◎简　　介</p>
<p>
	　　武当掌门张三丰（洪金宝）为存弟子一点血脉，用毕生功力替无忌将寒毒驱除，结果惹来接班人宋青书妒忌，并联同峨眉女弟子周芷若（黎姿）对付无忌。直到明教圣女小昭（邱淑贞）的出现，张无忌终于摆脱自己的命运，先在断崖遇上高人授予&ldquo;九阳神功&rdquo;，随后在明教禁地练得&ldquo;乾坤大挪移心法&rdquo;。六大派为了歼灭明教，围攻光明顶，无忌得悉蒙古郡主赵敏（张敏）合谋各派以残杀明教之奸计，遂立即前往光明顶，奋不顾身拯救明教。论功行赏，无忌暂代明教教主一职。在迎接四大法王之一的金毛狮王（徐锦江）出任教主途中，无忌遇上另一次考验，同时更发现了武林中的惊人秘密&hellip;&hellip;　</p>
<p>
	　　张翠山和他妻子殷素素、儿子张无忌刚从孤岛回来为他师父祝百岁大寿，途中无忌被玄冥神掌所伤。在武当山各大门派逼迫张翠山说出金毛狮王谢逊的下落，张翠山和他妻子被逼自杀。身受玄冥神掌之毒的张无忌不能练习武功，靠张三丰每日用真气才得以活下来。一日张无忌被师兄弟欺负，与帮助他的一女子小昭掉下悬崖，恰好遇上火头陀，治好了体内的寒毒并学会了九成九阳神功。后揭破了朝廷歼灭几大门的阴谋，救出了他外公和师祖。</p>
<p>
	　　话说&ldquo;倚天剑&rdquo;、&ldquo;屠龙刀&rdquo;乃郭靖、黄蓉将神鵰大侠杨过之玄铁宝剑，加天下精金铸造而成，郭大侠更把名将岳飞之兵法谱及天下第一武功秘籍九阴真经藏于刀剑之中，成为武林中人争夺之两件宝物，因而掀起江湖中无数腥风血雨，而张无忌亲眼目睹双亲被六大派逼死，虽然无能为力，但心理上蒙上了阴影，立誓要替父母报仇。凭借高人传授「九阳神功」及在明教禁地练成「乾坤大挪移心法」于光明顶一役救明教有功，而奉为教主。</p>
<p>
	　　武当弟子张翠山与魔教妖女殷素素结为夫妻，并生下一子张无忌。因为倚天剑和屠龙刀，张无忌的父母被六大门派迫害致死，年幼的张无忌立志要为父母报仇。但他自己身患寒毒，痛不欲生，幸而得到祖师爷张三丰的疼爱，才长大~~。后来，张无忌无意中得到高人传授《九明真功》，自此功力大增，不可匹敌；他又练成《乾坤大挪移心法》，在光明顶成功拯救明教后，张无忌被奉为教主&hellip;&hellip;</p>
<p>
	<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20110909/15/62564813201109091536139715605735226_000.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20110909/15/62564813201109091536139715605735226_001.jpg" style="width: 720px; height: 405px" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="&#13;&#10;ftp://dy67:piaohua@dy67.piaohua.com:1078/飘花电影piaohua.com倚天屠龙记之魔教教主HD高清国粤双语.mkv">ftp://dy67:piaohua@dy67.piaohua.com:1078/飘花电影piaohua.com倚天屠龙记之魔教教主HD高清国粤双语.mkv </a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1C05310-32V0.jpg{/dede:field}
