<?php
$z[0]=Array("field","我去世的吃醋女友BD中字1280终极",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","我去世的吃醋女友BD中字1280终极收藏版迅雷下载、免费下载，我去世的吃醋女友BD中字1280终极收藏版Gvod高清在线播放，剧情介绍等。",73,239);
$z[1][4]['name']="description";
$z[2]=Array("field","我去世的吃醋女友BD中字1280终极收藏版",241,315);
$z[2][4]['name']="title";
$z[3]=Array("field","",317,356);
$z[3][4]['name']="writer";
$z[4]=Array("field","",358,397);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-11-16",399,449);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",451,488);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://eee4.com:8077@vip14.eee4.com:8077/我去世的吃醋女友/[3E迅雷电影站www.eee4.com]我去世的吃醋女友.rmvb\" target=\"_blank",490,649);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MOL1J0-2OJ.jpg",651,731);
$z[8][4]['name']="litpic";

?>