{dede:field name='keywords'}怒火青春/仇恨/恨BD1280高清迅雷{/dede:field}
{dede:field name='description'}怒火青春/仇恨/恨BD1280高清迅雷下载、免费下载，怒火青春/仇恨/恨BD1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}怒火青春/仇恨/恨BD1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-23{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="/uploads/allimg/c120525/133O0T424P-960R.jpg" style="width: 348px; height: 490px" /></p>
<p>
	◎译　　名　怒火青春/仇恨/恨<br />
	◎片　　名　The Hate<br />
	◎年　　代　1995<br />
	◎国　　家　法国<br />
	◎类　　别　犯罪/剧情<br />
	◎语　　言　法语<br />
	◎字　　幕　中英双字<br />
	◎IMDB评分 8.1/10 22,543 votes<br />
	◎IMDB链接 http://www.imdb.com/title/tt0113247<br />
	◎导　　演　马修&middot;卡索维茨 Mathieu Kassovitz<br />
	◎主　　演　文森特&middot;卡塞尔 Vincent Cassel ....Vinz<br />
	　　　　　　哈勃&middot;孔黛 Hubert Kound&eacute;? ....Hubert<br />
	　　　　　　伯努瓦&middot;马吉梅 Beno t Magimel ....Beno t<br />
	　　　　　　萨伊德&middot;塔格马奥 Sa d Taghmaoui ....Sa d<br />
	　　　　　　爱德华&middot;蒙多特 Edouard Montoute ....Darty<br />
	　　　　　　嘉莲&middot;维雅 Karin Viard ....Gallerly girl<br />
	　　　　　　文森特&middot;林顿 Vincent Lindon ....&#39;Really&#39; drunk man<br />
	　　　　　　马修&middot;卡索维茨 Mathieu Kassovitz ....Young skinhead<br />
	　　　　　　马克&middot;迪莱特 Marc Duret ....Inspector &#39;Notre Dame&#39;<br />
	　　　　　<br />
	◎简　　介　<br />
	<br />
	剧情<br />
	<br />
	　　廿四小时的愤怒实录。<br />
	<br />
	　　巴黎的街头，四处充满了暴力和邪恶。一个男孩阿伯德被警察打成重伤，住进了医院，他的一个朋友死去。<br />
	<br />
	　　10点38分，男孩塞伊德到好友文兹家里找到文兹，两人谈论了一会有关街上暴乱的事情后，一起去找另一个好友赫伯特，三人随后又到一幢房屋的楼顶去见他们的老大。<br />
	<br />
	　　12点43分，警察到来，把聚集在楼顶的人赶走了。三人在街上遇到电视记者采访，满腹不满的三人打跑了唠叨不停的记者。三人接着到一个朋友家里玩耍，并眼见朋友停在楼下的车被一群人砸坏。<br />
	<br />
	　　14点12分，文兹把塞伊德和赫伯特带到一处隐秘的地方，拿出一把真枪给两人炫耀。<br />
	<br />
	　　15点47分，三人到医院看望阿伯德，被警察拒之门外。恼怒的文兹按耐不住情绪，仗着自己有枪，和警察争执起来，结果，塞伊德被警察带走。塞伊德的一个警察朋友带着文兹和赫伯特赶到警局，把塞伊德保释了出来。赫伯特不满文兹的行为，独自回到家里，并在电视新闻上看到警察正在寻找一名警察丢失的枪支。<br />
	<br />
	　　17点04分，文兹和塞伊德在街头观看霹雳舞时，又遇到赫伯特。这时，不远处携带枪支的两个年轻人和警察起了冲突，三人和其他街头混混上前和警察理论，眼看局势不能控制时，大批警察赶到，三人跟随其他人一哄而散。文兹掏出手枪，想要打死一名追赶他们的警察，赫伯特及时制止了他。<br />
	<br />
	　　18点22分，三人坐地铁到城市的另一个地方，三人在卫生间为刚才的事情争论不休，一个矮小的老头出现，把他年轻时因犯错被流放的艰苦经历讲给了他们听。塞伊德带着文兹和赫伯特，到一所高档公寓找一个朋友要钱，不想，钱没有要到，文兹还和那人因枪的事，打了起来。三人从公寓出来，遇到警察，塞伊德和赫伯特被警察拘禁，文兹侥幸逃脱。<br />
	<br />
	　　20点17分，塞伊德和赫伯特在警局受尽警察的折磨。<br />
	<br />
	　　22点08分，文兹去看拳击，和其他几个朋友遇到一起，并亲眼目睹了其中一个朋友开枪打死了一个门卫。<br />
	<br />
	　　00点33分，塞伊德和赫伯特从警局出来，没有能赶上最后一班回家的火车，并又遇到了文兹。三人闯入一家私人聚会，寻机挑衅，结果，被人赶了出来。三人随后又去偷车，当他们正在手忙脚乱时，一个酒鬼出现，并热情地教他们怎么偷车。车刚发动，警车突然到来，酒鬼引开警察的注意，三人趁机逃跑了。<br />
	<br />
	　　02点57分，三人闲逛到地铁，并在地铁的电视上看到了阿伯德的死讯。<br />
	<br />
	　　04点27分，文兹仇恨地看着一名警察，想象开枪杀死他的情形。塞伊德和赫伯特对文兹的做法很反感，两人离文兹而去。塞伊德和赫伯特在接头遇到另一群混混，双方一言不和，打了起来。文兹这时及时出现，掏出枪压制住了那些人，并把他们的老大带到了一个僻静的地方。当文兹用枪对着那人的头时，赫伯特在他耳边一个劲地叫文兹杀死那人，文兹犹豫半天后，终于放下了手中的枪。<br />
	<br />
	　　06点00分，三人回到自己熟悉的街头，赫伯特和文兹、塞伊德告别回家时，文兹把他的枪给了赫伯特。赫伯特刚走不远，就看见文兹和塞伊德被警察抓住，赫伯特赶上前去，正好目睹一名警察失手开枪打死了文兹。<br />
	<br />
	　　06点01分，赫伯特手中的枪对准了那名开枪打死文兹的警察的头，那名警察的枪也颤抖地对准了赫伯特的头，这时，随着一声枪响，影片结束。<br />
	<br />
	一句话评论<br />
	<br />
	Three Young Friends... One Last Chance.<br />
	<br />
	幕后制作<br />
	<br />
	这是一部讲法国&ldquo;新世代&rdquo;的作品，如同《阳光灿烂的日子》一样，富有青春期的不安和骚动气息。影片反映了在种族混杂的地方，友谊跨越种族要比跨越阶级更容易。影片中的世界非常美国化，也许他们模仿美国青年的举动是对法国主流社会的一种抵抗。导演明显有效仿斯派克&middot;李的企图，本片是他的第二部作品，也是将他带入名导行列的成名作，在戛纳影展夺得最佳导演奖并赢得凯撒奖最佳电影的桂冠。<br />
	<br />
	<b>本片荣获奖项:<br />
	1995年戛纳电影节最佳导演奖<br />
	恺撒奖最佳影片<br />
	最佳剪辑大奖</b><br />
	<img alt="" src="/uploads/allimg/c120525/133O0T45530-102K0.jpg" style="width: 720px; height: 405px" /><img alt="" src="/uploads/allimg/c120525/133O0T4B60-115453.jpg" style="width: 720px; height: 405px" /><img alt="" src="/uploads/allimg/c120525/133O0T4M0-123258.jpg" style="width: 720px; height: 405px" /><img alt="" src="/uploads/allimg/c120525/133O0T4W40-133647.jpg" style="width: 720px; height: 405px" /><br />
	&nbsp;</p>
<p>
	【下载地址】</p>
<table bgcolor="#0099cc" border="0" cellpadding="10" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：http://www.xiaobajie.com</td>
		</tr>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy125:piaohua@dy125.piaohua.com:8092/飘花电影piaohua.com怒火青春BD中英双字1280高清.rmvb</td>
		</tr>
		<tr>
		</tr>
	</tbody>
</table>
<br />{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O0T4aP-141643.jpg{/dede:field}
