{dede:field name='keywords'}龙卷风BD中英双字1024/1280高清{/dede:field}
{dede:field name='description'}龙卷风BD中英双字1024/1280高清迅雷下载、免费下载，龙卷风BD中英双字1024/1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}龙卷风BD中英双字1024/1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-11{/dede:field}
{dede:field name='body'}<p>
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://image-7.verycd.com/ee229956e9d1d3a8ef6a9212e1678c4f114694(600x)/thumb.jpg');" src="http://image-7.verycd.com/ee229956e9d1d3a8ef6a9212e1678c4f114694(600x)/thumb.jpg" /><br />
	<br />
	<br />
	◎译　　名　《龙卷风》1996年美国经典惊悚大片BD中英双字1024x560高清版（附国语版）<br />
	◎片　　名　Twister<br />
	◎年　　代　1996<br />
	◎国　　家　美国<br />
	◎类　　别　剧情/惊秫/动作/灾难<br />
	◎语　　言　中英双字<br />
	◎IMDB评分 5.9/10 (46,847 votes)<br />
	◎文件格式　BD-RMVB<br />
	◎视频尺寸　1024 x 560<br />
	◎文件大小　1CD<br />
	◎片　　长　113 mins<br />
	◎导　　演　简&middot;德&middot;邦特 Jan de Bont<br />
	◎主　　演　海伦&middot;亨特 Helen Hunt .... Dr. Jo Harding<br />
	　　　　　　比尔&middot;帕克斯顿 Bill Paxton .... Bill Harding<br />
	　　　　　　加利&middot;艾尔维斯 Cary Elwes .... Dr. Jonas Miller<br />
	　　　　　　Jami Gertz .... Dr. Melissa Reeves<br />
	　　　　　　菲利普&middot;塞莫尔&middot;霍夫曼 Philip Seymour Hoffman .... Dustin Davis<br />
	　　　　　　Lois Smith .... Meg Greene<br />
	　　　　　　阿兰&middot;卢克 Alan Ruck .... Robert &#39;Rabbit&#39; Nurick<br />
	　　　　　　Sean Whalen .... Allan Sanders<br />
	　　　　　　Scott Thomson .... Jason &#39;Preacher&#39; Rowe<br />
	　　　　　　托德&middot;菲尔德 Todd Field .... Tim &#39;Beltzer&#39; Lewis<br />
	　　　　　　佐伊&middot;斯洛尼克 Joey Slotnick .... Joey<br />
	　　　　　　Wendle Josepher .... Haynes<br />
	　　　　　　杰瑞米&middot;戴维斯 Jeremy Davies .... Laurence<br />
	　　　　　　扎克&middot;格雷尼尔 Zach Grenier .... Eddie<br />
	　　　　　　Gregory Sporleder .... Willie<br />
	<br />
	◎简　　介<br />
	<br />
	　　美国60年代，一场恐怖的龙卷风暴袭击了乔．哈汀 一家，乔的父亲为了保护家人而被风暴卷走。幼年的经历促使乔长大后成了一名专业研究龙卷风的气象专家。<br />
	　　时至九十年代，乔的丈夫比尔．哈汀带着女友美丽莎前来找乔在离婚证书上签字。比尔也曾经是追逐龙卷风的气象专家。在乔的追风队中，乔告诉他他以前设计的龙卷风探测仪&ldquo;多罗茜&rdquo;已经制造成功了；比尔十分高兴，终于决定再一次追风。<br />
	　　在追风的路程中，另一支由裘纳斯带领的车队超过了他们。裘纳斯取得了大公司的赞助，拥有先进的仪器设备，他还盗取了比尔和乔的研究成果，想借此成名。在乔和比尔与龙卷风的交锋中，两只&ldquo;多罗茜&rdquo;由于设计不全面而报废；而美丽莎却因无法忍受这种惊险、动荡的生活而与比尔分手，她认为乔更适合他。<br />
	　　又一个大型龙卷风袭来，乔和比尔赶到，及时救出了乔的妈妈；同时，两人受到风铃的启发，改进了探测仪。龙卷风暴再次袭来，裘纳斯不听劝告而被龙卷风将车队一扫而空。比尔下定决心亲自涉险，终于成功地放飞了最后一只&ldquo;多罗茜&rdquo;，通过成千上万的小探测器，追风队终于收到了完整的风暴中心的资料，他们终于成功了。比尔和乔也凭借机智和勇敢躲避开死神的袭击。龙卷风过后，共同的历险又使爱意在两人的心底复燃了。<br />
	<br />
	幕后制作<br />
	<br />
	龙卷风是此片的真正主角。人类受好奇心驱使，如果此剧中的灾难是狂风暴雨，恐怕观众就会兴趣骤减。但见过下冰雹的人就少多了，何况有几个人见过天上下牛、下房子、下大货车呢？为了支撑<a href="http://www.eee4.com/" target="_blank">电影下载</a>如此单薄的故事情节，编剧为她增加了一个闹离婚的丈夫，甚至丈夫还带来了新女友。也许是预感到观众对主人公追逐龙卷风的怪僻不能理解，编导调制了少许通俗心理学，为她安排了一个父亲被龙卷风卷走的理由。影片的节奏把握非常准，也非常程式化。演员的表演算是称职，只要你身材结实，穿上背心，让飓风吹动长发，那情景一定很上相。<br />
	<br />
	<img onclick="if(this.width&gt;screen.width-461) window.open('http://img.album.pchome.net/54/71/22/70/9729dfaa1dac1bd9fab2fb548862f47b.jpg');" src="http://img.album.pchome.net/54/71/22/70/9729dfaa1dac1bd9fab2fb548862f47b.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 329px; border-top: 0px solid; border-right: 0px solid" /><br />
	<img onclick="if(this.width&gt;screen.width-461) window.open('http://img.album.pchome.net/54/71/22/70/28af7de4cf6aa01ea9b02f63dfba9b3a.jpg');" src="http://img.album.pchome.net/54/71/22/70/28af7de4cf6aa01ea9b02f63dfba9b3a.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 329px; border-top: 0px solid; border-right: 0px solid" /><br />
	<br />
	<br />
	1996年美国经典惊悚大片《龙卷风》BD中英双字1024x560高清版 [2009/08/26下载地址]：<img border="0" src="http://www.eee4.com/templets/img/down.jpg" /></p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://3e:3e@www2.eee4.com:702/[www.eee4.cn提供]龙卷风BD中英双字1024x560高清版.rmvb" target="_blank">ftp://3e:3e@www2.eee4.com:702/[www.eee4.cn提供]龙卷风BD中英双字1024x560高清版.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://d21:d21@xl2.eee4.com:1105/[3E电影站www.eee4.com]龙卷风DVD国语配音版.rmvb" target="_blank">ftp://d21:d21@xl2.eee4.com:1105/[3E电影站www.eee4.com]龙卷风DVD国语配音版.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3389/飘花电影piaohua.com龙卷风BD中英双字1280高清.mkv">ftp://dy44:piaohua@dy44.piaohua.com:3389/飘花电影piaohua.com龙卷风BD中英双字1280高清.mkv</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O14944530-13538.jpg{/dede:field}
