{dede:field name='keywords'}巨浪/怒海骄阳BD1280高清迅雷下{/dede:field}
{dede:field name='description'}巨浪/怒海骄阳BD1280高清迅雷下载、免费下载，巨浪/怒海骄阳BD1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}巨浪/怒海骄阳BD1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-18{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://i.imgur.com/sH5jv.jpg" style="width: 700px; height: 985px" /></p>
<p>
	◎译　　名　巨浪/怒海骄阳<br />
	◎片　　名　White Squall<br />
	◎年　　代　1996<br />
	◎国　　家　美国<br />
	◎类　　别　冒险/剧情<br />
	◎语　　言　英语/丹麦语/西班牙语<br />
	◎字　　幕　中字<br />
	◎IMDB评分 &nbsp; 6.4/10 (11,034 votes)<br />
	◎IMDB链接 &nbsp; <a href="http://www.imdb.com/title/tt0118158/" target="_blank">http://www.imdb.com/title/tt0118158/</a><br />
	◎文件格式　x264 + DTS<br />
	◎视频尺寸　1280 x 720<br />
	◎文件大小　5/4 DVD<br />
	◎片　　长　129 mins<br />
	◎导　　演　雷德利&middot;斯科特 Ridley Scott<br />
	◎主　　演　杰夫&middot;布里吉斯 Jeff Bridges ....Captain Christopher &#39;Skipper&#39; Sheldon<br />
	　　　　　　卡罗琳&middot;古道 Caroline Goodall ....Dr. Alice Sheldon<br />
	　　　　　　约翰&middot;萨维奇 John Savage ....McCrea, Albatross Crewman/English Teacher<br />
	　　　　　　斯考特&middot;沃夫 Scott Wolf ....Charles &#39;Chuck&#39; Gieg/Narrator<br />
	　　　　　　杰瑞米&middot;西斯托 Jeremy Sisto ....Frank Beaumont<br />
	　　　　　　瑞恩&middot;菲利普 Ryan Phillippe ....Gil Martin<br />
	　　　　　　David Lascher ....Robert March<br />
	　　　　　　Eric Michael Cole ....Dean Preston<br />
	　　　　　　Jason Marsden ....Shay Jennings, Albatross First Mate<br />
	　　　　　　David Selby ....Francis Beaumont<br />
	　　　　　　Julio Oscar Mechoso ....Girard Pascal, Albatross Cook (as Julio Mechoso)<br />
	　　　　　　齐杰洛&middot;艾文克 Zeljko Ivanek ....Coast Guard Capt. Sanders<br />
	　　　　　　巴萨扎&middot;盖提 Balthazar Getty ....Tod Johnstone<br />
	　　　　　　伊桑&middot;恩布里 Ethan Embry ....Tracy Lapchick<br />
	　　　　　　Jordan Clarke ....Charles Gieg<br />
	　　　　　　Lizbeth MacKay ....Middy Gieg<br />
	　　　　　　Jill Larson ....Peggy Beaumont<br />
	　　　　　　James Medina ....Cuban Patrol Boat Commander<br />
	　　　　　　詹姆斯&middot;瑞布霍恩 James Rebhorn ....Tyler<br />
	　　　　　　Nicole Ann Samuel ....Girl in Brothel<br />
	　　　　　　Becky Ann Baker ....Ms. Boyde<br />
	　　　　　　Camilla Overbye Roos ....Bregitta<br />
	　　　　　　Nathaniel Ives ....Relief Bo&#39;sun<br />
	　　　　　　Chris Condon ....Crew Member<br />
	　　　　　　Andrew Hartley ....Crew Member<br />
	　　　　　　Peyton Thomas ....Crew Member<br />
	　　　　　　乔丹&middot;斯科特 Jordan Scott ....Dutch School Girl<br />
	　　　　　　Anja Clausen ....Dutch School Girl<br />
	　　　　　　Nynne Christiansen ....Dutch School Girl<br />
	　　　　　　Anita Weider ....Dutch School Girl<br />
	　　　　　　Charlotte Anderson ....Dutch School Girl<br />
	　　　　　　Emily Chittell ....Dutch School Girl<br />
	　　　　　　Lene Kristensen ....Dutch School Girl<br />
	　　　　　　Mette Hocke ....Dutch School Girl<br />
	<br />
	<br />
	<br />
	◎简　　介<br />
	<br />
	剧情<br />
	<br />
	　　&ldquo;信天翁号&rdquo;这次要从百慕大的圣乔治港出发，预计八个月后抵达加拉帕戈斯群岛。船上的14位乘客是来自海洋学院的学生。他们的国籍不同，家庭出身背景也不一样，但在船长谢尔顿的带领下，很快学会海上生存必须的本领以及自律和相处的能力，而这一切与船长的榜样力量是分不开的。然而就在航程即将结束的时候，他们遭遇到所有海员都闻之色变的无形暴风&mdash;&mdash;一秒钟内风速增加十几米。在白色的巨浪中，存活率据说只有万分之一&hellip;&hellip;<br />
	<br />
	一句话评论<br />
	<br />
	The strongest force in nature is the will to survive.<br />
	<br />
	The Adventure Of a Lifetime Turns Into the Ultimate Challenge of Survival!<br />
	<br />
	幕后制作<br />
	<br />
	　　本片探讨的话题非常深刻：在医学实验&mdash;&mdash;乃至所有科学实验&mdash;&mdash;其目的与手段之间如何权衡。Hugh Grant摆脱了其以往的公子哥儿或温柔小生形象，在本片中饰演一位坚持职业道德的医生。本片好评如潮，但亦有批评认为其过分拖沓，在最后提出的中心问题并没有充分展开。<br />
	&nbsp;<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120517/22/62564813201205172226321158319918123_000.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120517/22/62564813201205172222223015681133118_001.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120517/22/62564813201205172222223015681133118_000.jpg" style="width: 720px; height: 405px" /></p>
<p>
	【下载地址】</p>
<table bgcolor="#0099cc" border="0" cellpadding="10" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.net" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy125:piaohua@dy125.piaohua.com:8075/飘花电影piaohua.com怒海骄阳BD中字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:8075/飘花电影piaohua.com怒海骄阳BD中字1280高清.rmvb</a></td>
		</tr>
		<tr>
		</tr>
	</tbody>
</table>
<br />{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15cY0-5T14.jpg{/dede:field}
