{dede:field name='keywords'}海神号/新海神号历险记/海神波塞{/dede:field}
{dede:field name='description'}海神号/新海神号历险记/海神波塞冬号[BD中英双字1024x576＋1280x720高清版]迅雷下载、免费下载，海神号/新海神号历险记/海神波塞冬号[BD中英双字1024x576＋1280x720高清版]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}海神号/新海神号历险记/海神波塞冬号[BD中英双字1024x576＋1280x720高清版]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2010-04-16{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://4e:4e@d8.3edyy.com:131/【3E电影院www.eee4.cc】海神号BD中英双字1024x576高清版.rmvb" target=_blank>ftftp://4e:4e@d8.3edyy.com:131/【3E电影院www.eee4.cc】海神号BD中英双字1024x576高清版.rmvb</A></TD></TR></TBODY></TABLE><br><font color="#ff0000" size="2{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MPXSZ-43122.jpg{/dede:field}
