{dede:field name='keywords'}美丽中国/锦绣中华/野性中国迅雷{/dede:field}
{dede:field name='description'}美丽中国/锦绣中华/野性中国迅雷下载、免费下载，美丽中国/锦绣中华/野性中国Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}美丽中国/锦绣中华/野性中国{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2008-07-04{/dede:field}
{dede:field name='body'}<P>【中文片名】《美丽中国/锦绣中华/野性中国》08最新不可错过大片DVD中字<BR>【译　　名】BBC Wild China<BR>【年　　代】2008<BR>【国　　家】英国<BR>【类　　别】记录<BR>【语　　言】英语<BR>【字　　幕】中文<BR>【文件格式】X264 + AC3<BR>【视频尺寸】800 x 450<BR>【片　　长】300MiNs<BR>　<BR>【内容简介】：　</P>
<P>美丽中国：龙之心 Heart of the Dragon <BR>美丽中国：香格里拉 Shangri-La <BR>美丽中国：万里长城的塞外风光 Beyond the Great Wall <BR>美丽中国：熊猫之地 Land of the Panda <BR>美丽中国：潮汐更迭 Tides of Change </P>
<P>&nbsp;&nbsp;&nbsp; 《美丽中国》是由中英联合摄制小组拍摄的一部关于中国野生动物和自然风光的系列记录片，其中有些野生动物和风景的镜头从未在银幕上出现过。</P>
<P>&nbsp;&nbsp;&nbsp; 这部系列片将成为中英两国联合电视制作的一个里程碑，片名为《美丽中国》，在北京的一个典礼上上映，现场观众有幸对这一将成为经典之作的记录片投以惊鸿一瞥。</P>
<P>&nbsp;&nbsp;&nbsp; 《美丽中国》由世界闻名的英国BBC自然历史制作小组和中央电视台影视制作主力——中视传媒——合作制作。该片也是BBC和中国电视台的首次合作。3E迅雷<A href="/" target=_blank>电影下载</A>站</P>
<P>&nbsp;&nbsp;&nbsp; 《美丽中国》将全部以高清晰度方式拍摄，将使观众置身于中国的多彩风光中，包括汉代宫殿、蒙古草原和维吾尔的沙漠、丝绸之路、青藏高原。影片还包括罕见的大熊猫和一种珍稀的中国特有的食鱼蝙蝠的珍贵生活记录。</P>
<P>&nbsp;&nbsp;&nbsp; BBC环球公司已经授权全球超过25个国家可播放《美丽中国》系列片，今后这一数字还将扩大。</P>
<P>&nbsp;&nbsp;&nbsp; 英国驻华大使欧威廉爵士在谈到这一系列片对中英两国关系的重要性时说：“《美丽中国》是一部具有空前雄心壮志的自然历史系列片。该片的成功拍摄及制作不仅是两国电视节目制作合作的成功，也是中英两国创意产业领域的一次成功合作。”</P>
<P><IMG src="http://pic.piaohua.com/0701pic/allimg/080704/0619080.jpg"></P>
<P>【电影截图】：<BR>电影来源：www.eee4.com<BR><IMG src="http://pic.piaohua.com/0701pic/allimg/080704/0619081.jpg">&nbsp;<BR><IMG src="http://pic.piaohua.com/0701pic/allimg/080704/0619082.jpg">&nbsp;<BR><IMG src="http://pic.piaohua.com/0701pic/allimg/080704/0619480.jpg">&nbsp;<BR><IMG src="http://pic.piaohua.com/0701pic/allimg/080704/0619084.jpg">&nbsp;<BR><IMG src="http://pic.piaohua.com/0701pic/allimg/080704/0619085.jpg">&nbsp;<BR><IMG src="http://pic.piaohua.com/0701pic/allimg/080704/0619431.jpg"></P>
<P>2008-07-04 02:04:12 开始连接......<BR>2008-07-04 02:04:14 开始搜索候选资源......<BR>2008-07-04 02:04:15 搜索到57个候选资源<BR>2008-07-04 02:04:17 使用候选资源进行连接......<BR>2008-07-04 02:04:20 搜索到159个候选资源<BR>2008-07-04 02:04:23 使用候选资源进行连接......<BR>2008-07-04 02:04:24 文件创建成功，开始下载数据......<BR>2008-07-04 02:04:26 用户取消下载&nbsp;&nbsp; 本文来自 <A href="/index.html" target=_blank>www.eee4.com</A></P>（直接可能无法下载，一律使用<A href="/soft.htm" target=_blank>迅雷下载</A>）<BR>08最新不可错过大片《美丽中国/锦绣中华》DVD中字 － 来自[3E迅雷电影站eee4.com]下载地址：<IMG src="/templets/img/down.jpg" border=0><BR>美丽中国：潮汐更迭：<BR>
<TABLE style="BORDER-RIGHT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; BORDER-BOTTOM: #cccccc 1px dotted" cellSpacing=0 cellPadding=6 width="95%" align=center border=0>
<TBODY>
<TR>
<TD style="WORD-WRAP: break-word" bgColor=#fdfddf><ANCHOR></ANCHOR><A href="ftp://eee4.com:8113@vip20.eee4.com:8113/[3E迅雷电影站www.eee4.com]美丽中国：潮汐更迭.rmvb" target=_blank>ftp://eee4.com:8113@vip20.eee4.com:8113/[3E迅雷电影站www.eee4.com]美丽中国：潮汐更迭.rmvb</A></TD></TR></TBODY></TABLE>美丽中国：龙之心：<BR>
<TABLE style="BORDER-RIGHT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; BORDER-BOTTOM: #cccccc 1px dotted" cellSpacing=0 cellPadding=6 width="95%" align=center border=0>
<TBODY>
<TR>
<TD style="WORD-WRAP: break-word" bgColor=#fdfddf><ANCHOR></ANCHOR><A href="ftp://eee4.com:8113@vip20.eee4.com:8113/[3E迅雷电影站www.eee4.com]美丽中国：龙之心.rmvb" target=_blank>ftp://eee4.com:8113@vip20.eee4.com:8113/[3E迅雷电影站www.eee4.com]美丽中国：龙之心.rmvb</A></TD></TR></TBODY></TABLE>美丽中国：万里长城的塞外风光：<BR>
<TABLE style="BORDER-RIGHT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; BORDER-BOTTOM: #cccccc 1px dotted" cellSpacing=0 cellPadding=6 width="95%" align=center border=0>
<TBODY>
<TR>
<TD style="WORD-WRAP: break-word" bgColor=#fdfddf><ANCHOR></ANCHOR><A href="ftp://eee4.com:8113@vip20.eee4.com:8113/[3E迅雷电影站www.eee4.com]美丽中国：万里长城的塞外风光.rmvb" target=_blank>ftp://eee4.com:8113@vip20.eee4.com:8113/[3E迅雷电影站www.eee4.com]美丽中国：万里长城的塞外风光.rmvb</A></TD></TR></TBODY></TABLE>美丽中国：香格里拉：<BR>
<TABLE style="BORDER-RIGHT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; BORDER-BOTTOM: #cccccc 1px dotted" cellSpacing=0 cellPadding=6 width="95%" align=center border=0>
<TBODY>
<TR>
<TD style="WORD-WRAP: break-word" bgColor=#fdfddf><ANCHOR></ANCHOR><A href="ftp://eee4.com:8113@vip20.eee4.com:8113/[3E迅雷电影站www.eee4.com]美丽中国：香格里拉.rmvb" target=_blank>ftp://eee4.com:8113@vip20.eee4.com:8113/[3E迅雷电影站www.eee4.com]美丽中国：香格里拉.rmvb</A></TD></TR></TBODY></TABLE>美丽中国：熊猫之地：<BR>
<TABLE style="BORDER-RIGHT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; BORDER-BOTTOM: #cccccc 1px dotted" cellSpacing=0 cellPadding=6 width="95%" align=center border=0>
<TBODY>
<TR>
<TD style="WORD-WRAP: break-word" bgColor=#fdfddf><ANCHOR></ANCHOR><A href="ftp://eee4.com:8113@vip20.eee4.com:8113/[3E迅雷电影站www.eee4.com]美丽中国：熊猫之地.rmvb" target=_blank>ftp://eee4.com:8113@vip20.eee4.com:8113/[3E迅雷电影站www.eee4.com]美丽中国：熊猫之地.rmvb</A></TD></TR></TBODY></TABLE>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O16135430-35a8.jpg{/dede:field}
