{dede:field name='keywords'}燃烧弹BD中英双字1024/1280高清{/dede:field}
{dede:field name='description'}燃烧弹BD中英双字1024/1280高清迅雷下载、免费下载，燃烧弹BD中英双字1024/1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}燃烧弹BD中英双字1024/1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-04-26{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://3e:3e@www2.eee4.com:315/[3E电影站www.eee4.com]燃烧弹DVD中英双字1024x576高清版.rmvb" target="_blank{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MP2422P-34T5.jpg{/dede:field}
