{dede:field name='keywords'}风中奇缘2BD1280高清中英双字迅{/dede:field}
{dede:field name='description'}风中奇缘2BD1280高清中英双字迅雷下载、免费下载，风中奇缘2BD1280高清中英双字Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}风中奇缘2BD1280高清中英双字{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-17{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120517/01/17870980201205170102263875561269381_000.jpg" style="width: 640px" /></p>
<p>
	◎译　　名　风中奇缘2<br />
	◎片　　名　Pocahontas II: Journey to a New World<br />
	◎年　　代　1998<br />
	◎国　　家　美国&nbsp;&nbsp;<br />
	◎类　　别　动画/家庭/歌舞<br />
	◎IMDB评分&nbsp;&nbsp;4.8/10 from 2,911 users<br />
	◎IMDB链接&nbsp;&nbsp;<a href="http://www.imdb.com/title/tt0143808/" target="_blank">http://www.imdb.com/title/tt0143808/</a><br />
	◎语　　言　英语&nbsp;&nbsp;<br />
	◎字　　幕　见链接&nbsp;&nbsp;<br />
	◎片　　长　73 mins 10 seconds　　　<br />
	◎导　　演　Tom Ellery<br />
	&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp;&nbsp;布拉德利&middot;雷蒙德 Bradley Raymond<br />
	◎主　　演　艾琳&middot;贝达 Irene Bedard&nbsp;&nbsp;....Pocahontas (voice)<br />
	　　　　　　吉姆&middot;库宁斯 Jim Cummings&nbsp;&nbsp;....King James (voice)<br />
	　　　　　　Donal Gibson&nbsp;&nbsp;....John Smith (voice)<br />
	　　　　　　Finola Hughes&nbsp;&nbsp;....Additional voices (voice)<br />
	　　　　　　琳达&middot;亨特 Linda Hunt&nbsp;&nbsp;....Grandmother Willow (voice)<br />
	　　　　　　Judy Kuhn&nbsp;&nbsp;....Pocahontas (singing voice)<br />
	　　　　　　拉塞尔&middot;敏斯 Russell Means&nbsp;&nbsp;....Powhatan (voice)<br />
	　　　　　　Jean Stapleton&nbsp;&nbsp;....Mrs. Jenkins (voice)<br />
	　　　　　　大卫&middot;奥根&middot;斯提尔斯 David Ogden Stiers&nbsp;&nbsp;....Ratcliffe (voice)<br />
	　　　　　　比利&middot;赞恩 Billy Zane&nbsp;&nbsp;....John Rolfe (voice)<br />
	　　　　　　Jeff Bennett&nbsp;&nbsp;....Additional voices (voice)<br />
	　　　　　　Bob Bergen&nbsp;&nbsp;....Additional voices (voice) (as Robert Bergen)<br />
	　　　　　　Mark S. Brien&nbsp;&nbsp;....Additional voices (voice) (as Mark Steven Brien)<br />
	　　　　　　Rodger Bumpass&nbsp;&nbsp;....Additional voices (voice)<br />
	　　　　　　弗兰克&middot;维尔克 Frank Welker&nbsp;&nbsp;....Flit (voice)<br />
	　　　　　　Hugo Becker&nbsp;&nbsp;....L&#39;auto-stoppeur (rumored)<br />
	　　　　　　Mary Jo Catlett&nbsp;&nbsp;....Additional voices (voice)<br />
	　　　　　　德比&middot;戴瑞巴里 Debi Derryberry&nbsp;&nbsp;....Additional voices (voice)<br />
	　　　　　　Paul Eiding&nbsp;&nbsp;....Additional voices (voice)<br />
	　　　　　　布拉德&middot;加内特 Brad Garrett&nbsp;&nbsp;....Additional voices (voice)<br />
	　　　　　　米凯&middot;麦高万 Mickie McGowan&nbsp;&nbsp;....Additional voices (voice)<br />
	　　　　　　约翰&middot;卡西尔 John Kassir&nbsp;&nbsp;....Meeko<br />
	　　　<br />
	<br />
	◎简　　介　<br />
	<br />
	　　本片故事时代回到公元1612年，话说后来波卡洪塔斯Pocahontas 听到约翰&middot;史密斯John Smith 死讯的传言，不禁又开始迟疑自己当初所作的决定到底是对是错。后来她为了谋求她的族人与英国移民之间的和平关系，公主决定远赴伦敦，展开和平外交。她就随着一位年轻有为的英国外交官约翰&middot;罗尔夫John Rolfe 远渡重洋来到英国伦敦，展开一次前所未有的新世界之旅！那三只小动物浣熊米高Meeko 、Percy 和小蜂鸟菲莉Flit 也跟着偷渡过洋！<br />
	<br />
	　　当波卡洪塔斯Pocahontas 踏上英国伦敦打算到白金汉宫面见英国国王时，不料又遇到大坏蛋雷利夫Ratcliffe 正准备重回新大陆捞金，要发动战舰去消灭印地安人。于是波卡洪塔斯Pocahontas 又开始为族人的自由而努力以赴，片中她还穿着欧式的礼服到白金汉宫面见英国的国王与皇后，在英国异乡也终于见到许久都没音讯的约翰&middot;史密斯John Smith，但是波卡洪塔斯Pocahontas 最后还是选择了跟约翰&middot;史密斯John Smith 分别，与英国外交官约翰&middot;罗尔夫John Rolfe 返回美洲大陆，结束了这趟难忘的新世界之旅。<br />
	<br />
	<br />
	◎幕后制作<br />
	<br />
	波卡洪塔斯的真实历史<br />
	<br />
	　　波卡洪塔斯（Pocahontas ）的真名是 Matoaka ，波卡洪塔斯其实是她的绰号，意思为&ldquo;嬉戏的&rdquo;、&ldquo;顽皮的&rdquo;。她是波瓦坦（Powhatan ）最爱的一位女儿，波瓦坦是生活于美国弗吉尼亚州的亚尔冈京印地安人（Algonquian Indians，即波瓦坦人）的一位重要酋长。<br />
	<br />
	　　波卡洪塔斯只有10岁大时，她的人生被永远的改变了。英国殖民者远渡海洋，并在弗吉尼亚州插上了英国国旗，又以英王的名字命名其新的殖民地为詹姆士镇（Jamestown）。外来殖民者在外观及行为上都不同于原住民。对此，当地的波瓦坦部落自然心存疑惧，一些族人都很害怕或甚至痛恨这些与自己相貌、装束不同的陌生人。但是这位酋长的女儿却满心好奇并友善的想了解新移民的事情，她的温和天性及天生的好奇心得到英国人的喜爱及信任。其中殖民领袖约翰&middot;史密斯（John Smith ，即片中的庄迈斯）上尉则指出她的外表、智慧及友好个性都&ldquo;远远超过了其他的波瓦坦人。&rdquo;<br />
	<br />
	　　然而不是所有的波瓦坦人都如波卡洪塔斯一般，1607年11月，史密斯遭捕并被囚禁在酋长波瓦坦的首都威尔沃科莫科村(Werowocomoco)。在史密斯日後的传记故事中，最被人称道的便是波卡洪塔斯救了他的性命，据说当时她不顾自身安危挡在史密斯及行刑者之间，说服她的父亲释放他。但这只是波卡洪塔斯帮助英国朋友的诸多事件中的一件，她常会带食物及礼物给殖民地居民，1608年时，年仅12岁的她经过协调，殖民者同意释放波瓦坦囚犯。接下来的两年，她持续的来回奔波在她的父亲及族人之间，并致力于保护殖民地居民。可是尽管她尽了最大的努力，波瓦坦人及英国人之间的紧张局势仍不停升级，因为原住民对英国人持续夺取他们土地之事忍无可忍。最後，双方终于开战，并展开长达五年的冲突。<br />
	<br />
	　　1613年，波卡洪塔斯遭英国人囚禁，英方确信她的父亲会赎回他的女儿并结束战争，但是波瓦坦却没有支付，这使得波卡洪塔斯被当作人质长达一年之久。这是父亲确信英国人不会亏待自己女儿下的考虑，而事实也正是如此，波卡洪塔斯在囚禁期间却倍受礼待，并深受殖民者的喜爱及尊敬。也就是在这段时间，殖民者说服她改信基督教，她因此接受洗礼改名为蕾贝卡（Rebecca）。1614年4月，波卡洪塔斯嫁给詹姆士镇的一位殖民约翰&middot;罗尔夫（John Rolfe ，即《风中奇缘2：伦敦之旅》中的罗强恩），两人于詹姆斯敦的教堂举行婚礼，一年之後更是生有一子，取名为托马斯&middot;罗尔夫（Thomas Rolfe ，片中的汤姆斯便是由此得来）。英国方面希望这段婚姻有助于结束波瓦坦人及殖民之间的战争，而她改变信仰能有助于说服剩馀族人一起改信基督教。<br />
	<br />
	　　1616年，两人带着儿子乘船返回英国。在英国两人应邀参加了一个不同寻常的假面舞会，而这场舞会的主人就是詹姆斯国王（King James I ，即片中的詹姆国王一世）和王後（相似情节被应用到《风中奇缘2：伦敦之旅》中）。波卡洪塔斯在英国期间有幸与史密斯上尉再次见面，此时距离他们上次见面已有七年。但正当她准备启程回到弗吉尼亚州时，却身染重病。临终前，她没有哀伤，反而安慰丈夫说：&ldquo;所有人都是要死的，只要孩子活着就够了。&rdquo;她死于1617年3月，一生短暂（死于肺炎，终年22岁），下葬于英国葛文森的圣&middot;乔治教堂（Church of St. George）。身处两个&ldquo;世界&rdquo;的朋友及家人都深感悲痛，而她在英国的早逝也意味着波瓦坦人及殖民之间的永续和平机会的丧失。</p>
<p>
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120517/00/17870980201205170049294294052987594_000.jpg" style="width: 640px; height: 360px" /></p>
<p>
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120517/00/17870980201205170049294294052987594_002.jpg" style="width: 640px; height: 360px" /></p>
<p>
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120517/00/17870980201205170049294294052987594_003.jpg" style="width: 640px; height: 360px" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.net" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy241:piaohua@117.41.229.29:2023/飘花电影piaohua.com风中奇缘2BD1280高清中英双字.rmvb">ftp://dy241:piaohua@117.41.229.29:2023/飘花电影piaohua.com风中奇缘2BD1280高清中英双字.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1BEN0-4K37.jpg{/dede:field}
