{dede:field name='keywords'}溃堤决坝999-3D版DVD中字印度201{/dede:field}
{dede:field name='description'}溃堤决坝999-3D版DVD中字印度20111科幻迅雷下载、免费下载，溃堤决坝999-3D版DVD中字印度20111科幻Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}溃堤决坝999-3D版DVD中字印度20111科幻{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-02-15{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://www4.chuantu.info/tupianshangchuan/77/1328700305x-954498909.jpg" /></p>

<p>
	◎译　　名　溃堤决坝999<br />
	◎片　　名　Dam999<br />
	◎年　　代　2011<br />
	◎国　　家　印度<br />
	◎类　　别　灾难/科幻<br />
	◎语　　言　北印度语<br />
	◎字　　幕　中字<br />
	◎IMDB评分 5.1/10 from 538 users<br />
	◎文件格式　XviD + MP3<br />
	◎文件大小　1CD<br />
	◎片　　长　108 Mins<br />
	◎导　　演　Sohan Roy<br />
	◎主　　演　&nbsp;&nbsp;&nbsp;&nbsp; 乔舒华&middot;费雷迪克&middot;史密斯 Joshua Fredric Smith&nbsp; ....Fredrick Brown<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Vinay&nbsp; ....Vinay<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Megha Burman&nbsp; ....Raziya<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Jaala Pickering&nbsp; ....Maria<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Linda Arsenio&nbsp; ....Sandra<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Vimala Raman&nbsp; ....Meera<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Ashish Vidyarthi&nbsp; ....Durai</p>

<p>
	◎简　　介　</p>
<p>
	在海上航行多年，两个水手返回自己的家园。然而等候他们的不是一个新开始，而是即将发生的巨大灾难：一个水坝，始建于100多年前的英国殖民统治时期，潜在的崩塌威胁即将打破。显然，这场灾难并不是不可避免的....</p>
<p>
	故事围绕电影中的中心建筑：一座英国于殖民时期在印度修建的拥有百年历史的大坝进行。如&ldquo;大坝&rdquo;一般，电影中的每个角色都因着各种各样的理由隐瞒了自己的情感，最终，伴随着&ldquo;大坝&rdquo;的决堤，角色们也将观众的情绪带入了扣人心弦的高潮。翻开印度做为英国殖民地的史页，999这个数字有着非常重要的意义。故事揭示了隐藏在印度古老神话和科学背后的真相。(文：深影字幕组@娃娃仔）</p>

<p>
	<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120209/19/64608184201202091934227270398572446_014.jpg" /></p>
<p>
	<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120209/19/64608184201202091934227270398572446_011.jpg" /></p>
<p>
	<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120209/19/64608184201202091934227270398572446_010.jpg" /></p>
<p>
	<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120209/19/64608184201202091934227270398572446_009.jpg" /></p>
<p>
	<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120209/19/64608184201202091934227270398572446_008.jpg" /></p>
<p>
	<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120209/19/64608184201202091934227270398572446_007.jpg" /></p>
<p>
	[下载地址]： &nbsp;<img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" /></p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2816/飘花电影piaohua.com溃堤决坝999-3D版DVD中字.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2816/飘花电影piaohua.com溃堤决坝999-3D版DVD中字.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1591Y20-34256.jpg{/dede:field}
