{dede:field name='keywords'}坦克大决战BD高清,二战经典迅雷{/dede:field}
{dede:field name='description'}坦克大决战BD高清 二战经典迅雷下载、免费下载，坦克大决战BD高清 二战经典Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}坦克大决战BD高清 二战经典{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-12-16{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://ec3.images-amazon.com/images/P/B0007TKNGA.01._SCLZZZZZZZ_V1111034379_.jpg" style="width: 426px; height: 500px" /></p>
<p>
	◎译　　名　坦克大决战<br />
	◎片　　名　Battle of the Bulge<br />
	◎年　　代　1965<br />
	◎国　　家　美国<br />
	◎类　　别　战争/动作/剧情<br />
	◎语　　言　英语<br />
	◎字　　幕　中文<br />
	◎IMDB评分 &nbsp;6.7/10 (3,788 votes)<br />
	◎IMDB链接 &nbsp;<a href="http://www.imdb.com/title/tt0058947/" target="_blank">http://www.imdb.com/title/tt0058947/</a><br />
	◎片　　长　02:49:39<br />
	◎导　　演　Ken Annakin<br />
	◎主　　演　Henry Fonda .... Lt. Col. Daniel Kiley<br />
	　　　　　　Robert Shaw .... Col. Martin Hessler<br />
	　　　　　　Robert Ryan .... Gen. Grey<br />
	　　　　　　Dana Andrews .... Col. Pritchard<br />
	　　　　　　George Montgomery .... Sgt. Duquesne<br />
	　　　　　　Ty Hardin .... Lt. Schumacher (fake MP)<br />
	　　　　　　Pier Angeli .... Louise<br />
	　　　　　　Barbara Werle .... Elena (prostitute)<br />
	　　　　　　Charles Bronson .... Maj. Wolenski<br />
	　　　　　　Hans Christian Blech .... Cpl. Conrad<br />
	　　　　　　Werner Peters .... Gen. Kohler<br />
	　　　　　　James MacArthur .... Lt. Weaver<br />
	　　　　　　Karl-Otto Alberty .... Maj. von Diepel (as Karl Otto Alberty)<br />
	　　　　　　Telly Savalas .... Sgt. Guffy<br />
	　　　　　　Steve Rowland .... Eddy (Sgt. Guffy&lsquo;s gunner)<br />
	<br />
	◎简　　介　<br />
	<br />
	<br />
	描述二次世界大战期间盟军与德军的一场坦克大战，德军由罗伯特．萧饰演的希斯将军率领，企图在圣诞前夕对盟军作全面反击，但计划功败垂成，被亨利．方达饰演的凯晨将军发现，因而双方发生殊死战。原来的宽银幕电影颇能表现出这部巨制的战争气势，在小荧幕上播映当然大打折扣。不过，导演肯．安纳金的叙事手法仍算流畅，加上一群老牌演员罗伯特．瑞安，查理斯．布朗森等也演出卖力，使影片维持了相当的娱乐性。</p>
<p>
	<img alt="" src="http://img165.poco.cn/mypoco/myphoto/20111215/21/62564813201112152130503197807465568_003.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img165.poco.cn/mypoco/myphoto/20111215/21/62564813201112152130503197807465568_002.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img165.poco.cn/mypoco/myphoto/20111215/21/62564813201112152130503197807465568_001.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img165.poco.cn/mypoco/myphoto/20111215/21/62564813201112152130503197807465568_000.jpg" style="width: 720px; height: 405px" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="&#13;&#10;ftp://dy125:piaohua@dy125.piaohua.com:7302/飘花电影piaohua.com坦克大决战BD中字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:7302/飘花电影piaohua.com坦克大决战BD中字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O16263440-5T37.jpg{/dede:field}
