{dede:field name='keywords'}大话三国之校园大战迅雷下载，免{/dede:field}
{dede:field name='description'}大话三国之校园大战迅雷下载、免费下载，大话三国之校园大战Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}大话三国之校园大战{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2007-07-11{/dede:field}
{dede:field name='body'}<p>《大话三国之校园大战》 国语DVD(2007校园喜剧大片)<br />《大话三国之校园大战》<br />　　经过紧张激烈的角逐，十六名来自武汉大专院校的学生从上千名应征者中脱颖而出，入选《大话三国之校园大战》主要演员阵容，成为了万众期待的幸运儿。在参加完四月份武术基础培训后，将正式踏上三国征旅，开赴杀场，一场校园大战一触即发。主要演员入选名单如下：</p>
<p>何婷（校园影后、湖北省幼师）&mdash;&mdash;饰小乔后代<br />高锐（校园影帝、武汉大学）&mdash;&mdash;饰周瑜后代<br />韩菲（武汉大学）&mdash;&mdash;饰蔡文姬后代<br />岳民亮（湖北工业大学）&mdash;&mdash;饰黄忠后代<br />覃文静（武汉大学）&mdash;&mdash;饰大乔后代<br />刘苏（武汉大学）&mdash;&mdash;饰冰凌<br />李烈（湖北大学）&mdash;&mdash;饰刁婵后代<br />潘杰（武汉模特学院）&mdash;&mdash;饰吕布后代<br />姚瑶（湖北工业大学）&mdash;&mdash;饰甄宓后代<br />田原（武汉大学）&mdash;&mdash;饰赵云后代<br />姜吉峰（武汉大学）&mdash;&mdash;饰曹操后代<br />张瑞（华中师范大学）&mdash;&mdash;饰马超后代<br />汪念（武汉大学）&mdash;&mdash;饰诸葛亮后代<br />胡文玲（武汉理工大学）&mdash;&mdash;饰关羽后代<br />周永久（武汉音乐学院）&mdash;&mdash;饰张飞<br />康淑琴（武汉大学）&mdash;&mdash;饰祝融夫人后代<img height="1" alt="" width="2" border="0" src="http://pic.piaohua.com/0701pic/allimg/20070501/BM018.jpg" /><br /></p>
<p><img alt="DaHuaSanGuo.jpg" border="0" src="http://pic.piaohua.com/0701pic/allimg/070711/0516540.jpg" /><br /><img alt="DaHuaSanGuo1.jpg" border="0" src="http://pic.piaohua.com/0701pic/allimg/070711/0516541.jpg" /><br /><img alt="DaHuaSanGuo2.jpg" border="0" src="http://pic.piaohua.com/0701pic/allimg/070711/0516542.jpg" /><br /><img alt="DaHuaSanGuo3.jpg" border="0" src="http://pic.piaohua.com/0701pic/allimg/070711/0516543.jpg" /><br /><img alt="DaHuaSanGuo4.jpg" border="0" src="http://pic.piaohua.com/0701pic/allimg/070711/0516544.jpg" /><br /><img alt="DaHuaSanGuo5.jpg" border="0" src="http://pic.piaohua.com/0701pic/allimg/070711/0516545.jpg" /></p>
<p>2007-07-11 14:12:12 开始搜索候选资源......<br />2007-07-11 14:12:14 搜索到20个候选资源<br />2007-07-11 14:12:15 使用候选资源进行连接......<br />2007-07-11 14:12:20 搜索到15个候选资源<br />2007-07-11 14:12:21 使用候选资源进行连接......<br />2007-07-11 14:12:21 开始创建文件......<br />2007-07-11 14:12:23 文件创建成功，开始下载数据......<br />2007-07-11 14:12:26 用户取消下载&nbsp;&nbsp; 本文来自 www.eee4.com</p>
(右击选择迅雷下载)：
<table style="BORDER-RIGHT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; BORDER-BOTTOM: #cccccc 1px dotted" cellspacing="0" cellpadding="6" width="95%" align="center" border="0">
    <tbody>
        <tr>
            <td style="WORD-WRAP: break-word" bgcolor="#fdfddf"><anchor></anchor><a href="thunder://QUFmdHA6Ly8wNTQyOTo5OUAyMjIuMTczLjcyLjc0L1vQwtG4wNfPwtTYzfgtd3d3LnhpbnhsLmNvbV0ttPO7sMj9ufot0KPUsLTz1b0ucm12Ylpa/">《大话三国之校园大战》 国语DVD(2007校园喜剧大片)</a> </td>
        </tr>
    </tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1610N20-11T6.jpg{/dede:field}
