{dede:field name='keywords'}冲天小子HD国语中字1280高清[DVD{/dede:field}
{dede:field name='description'}冲天小子HD国语中字1280高清[DVD国语＋粤语]迅雷下载、免费下载，冲天小子HD国语中字1280高清[DVD国语＋粤语]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}冲天小子HD国语中字1280高清[DVD国语＋粤语]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-10-28{/dede:field}
{dede:field name='body'}<p>
	<img alt="" border="0" class="topic" oldblock="inline" src="http://w.gokuai.com/w/Sc41L02U220t6PpB/20106161462144.jpg" style="width: 450px; display: inline; height: 640px" /></p>
<p>
	<br />
	◎译　　名　《冲天小子》香港多明星经典犯罪动作片DVD国语＋粤语<br />
	◎片　　名　Path of Glory<br />
	◎年　　代　1989<br />
	◎国　　家　中国<br />
	◎类　　别　动作/剧情<br />
	◎语　　言　普通话/粤语<br />
	◎字　　幕　N/A<br />
	◎IMDB评分 awaiting 5 votes<br />
	◎IMDB链接 http://www.imdb.com/title/tt0097060<br />
	◎文件格式　DVD-RMVB<br />
	◎视频尺寸　704 x 384<br />
	◎文件大小　423MB<br />
	◎片　　长　01:38:31<br />
	◎导　　演　杨以和<br />
	◎主　　演　林俊贤<br />
	　　　　　　莫少聪<br />
	　　　　　　郑少秋<br />
	　　　　　　周慧敏<br />
	　　　　　　卢敏仪<br />
	<br />
	◎简　　介　<br />
	<br />
	　　张柏伦原是警校的好学生，被派去当卧底四年，现调回警官原校受训。他和同学招家宝等甚为友好。<br />
	　　招家宝开设的店铺被黑社会捣乱，家宝被打伤。柏伦带领同学们把黑社会中人痛惩。此事犯了校规，教官林Sir不愿他们被革退替他们代罪，因此受到提前退职处分。柏伦等感到很内疚。<br />
	　　林Sir退职后被四大天王匪帮杀死，柏伦等十分悲愤。毕业后他们都当了<a href="http://www.eee4.com/" target="_blank">电影</a>警察，他和家宝都和心爱的人结了婚。<br />
	　　三年后他们得知四大天王的行踪，他们集中去围捕，在围捕中柏伦受了伤，四大天王都被他们亲手杀死，替休Sir报了仇。</p>
<p>
	【电影截图】：<br />
	<br />
	<img src="http://img.album.pchome.net/54/72/05/62/02e695bb63a0f9ba45371e2acf46ab40.jpg" />&nbsp;<br />
	&nbsp;<br />
	<img src="http://img.album.pchome.net/54/72/05/62/e28bd73ba417b112e6809d8e472f49f1.jpg" />&nbsp;<br />
	<img src="http://img.album.pchome.net/54/72/05/62/7c5244cad186c870ac6408f0e6b5e7c7.jpg" />&nbsp;<br />
	<img src="http://img.album.pchome.net/54/72/05/62/88e0b06e004330fea3e189e5e8331e62.jpg" />&nbsp;<br />
	<img src="http://img.album.pchome.net/54/72/05/62/f3121c9148f750ecfd88abd66ff60198.jpg" />&nbsp;<br />
	<img src="http://img.album.pchome.net/54/72/05/62/071b2c4f395e2a3ecc6b3f34bbaa3aaf.jpg" />&nbsp;<br />
	<img src="http://img.album.pchome.net/54/72/05/62/7fa2e852121e4f5f4541d3f0c46c265a.jpg" />&nbsp;<br />
	&nbsp;</p>
<p>
	<img alt="" border="0" class="topic" jquery1319737294109="26" oldblock="inline" src="http://w.gokuai.com/w/08y2O3O0Zu1u7aK9/3.png" style="width: 600px; display: inline; height: 337px; cursor: pointer" /></p>
<p>
	<img alt="" border="0" class="topic" jquery1319737294109="22" oldblock="inline" src="http://w.gokuai.com/w/35Cm128Hr153456B/4.png" style="width: 600px; display: inline; height: 337px; cursor: pointer" /></p>

<p>
	香港多明星经典犯罪动作片《冲天小子》 [下载地址]：</p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://3e:3e@www2.eee4.com:893/[3E电影站www.eee4.cn]冲天小子DVD国语.rmvb" target="_blank">ftp://3e:3e@www2.eee4.com:893/[3E电影站www.eee4.cn]冲天小子DVD国语.rmvb</a></td>
		</tr>
	</tbody>
</table>
<br />
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://3e:3e@www2.eee4.com:893/[3E电影站www.eee4.cn]冲天小子DVD粤语.rmvb" target="_blank">ftp://3e:3e@www2.eee4.com:893/[3E电影站www.eee4.cn]冲天小子DVD粤语.rmvb</a></td>
		</tr>
	</tbody>
</table>
	[下载地址]： &nbsp;<img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" /></p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				&nbsp;<a href="ftp://dy44:piaohua@dy44.piaohua.com:1937/飘花电影piaohua.com冲天小子HD国语中字1280高清.rmvb ">ftp://dy44:piaohua@dy44.piaohua.com:1937/飘花电影piaohua.com冲天小子HD国语中字1280高清.rmvb </a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1525X0-29363.jpg{/dede:field}
