{dede:field name='keywords'}杨丞琳-台北跨年晚会HDTV720P高{/dede:field}
{dede:field name='description'}杨丞琳-台北跨年晚会HDTV720P高清现场版MV迅雷下载、免费下载，杨丞琳-台北跨年晚会HDTV720P高清现场版MVGvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}杨丞琳-台北跨年晚会HDTV720P高清现场版MV{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-07-23{/dede:field}
{dede:field name='body'}<p>
	<img border="0" src="/uploads/allimg/c120524/133N423S10-395L.jpg" width="750" /></p>
<p>
	[下载地址]： &nbsp;<img border="0" src="/uploads/allimg/c120524/133N2Z4FF-102231.jpg" />
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy171:piaohua@dy171.piaohua.com:1064/飘花电影piaohua.com杨丞琳-台北跨年晚会HDTV720P高清现场版.mkv</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120524/133N42404320-4N32.jpg{/dede:field}
