<?php
$z[0]=Array("field","杨丞琳-台北跨年晚会HDTV720P高",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","杨丞琳-台北跨年晚会HDTV720P高清现场版MV迅雷下载、免费下载，杨丞琳-台北跨年晚会HDTV720P高清现场版MVGvod高清在线播放，剧情介绍等。",72,244);
$z[1][4]['name']="description";
$z[2]=Array("field","杨丞琳-台北跨年晚会HDTV720P高清现场版MV",246,323);
$z[2][4]['name']="title";
$z[3]=Array("field","",325,364);
$z[3][4]['name']="writer";
$z[4]=Array("field","",366,405);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-07-23",407,457);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>\r\n	<img border=\"0\" src=\"/uploads/allimg/c120524/133N423S10-395L.jpg\" width=\"750\" /></p>\r\n<p>\r\n	[下载地址]： &nbsp;<img border=\"0\" src=\"/uploads/allimg/c120524/133N2Z4FF-102231.jpg\" />\r\n<table bgcolor=\"#ff8c00\" border=\"0\" cellpadding=\"5\" cellspacing=\"1\" width=\"100%\">\r\n	<tbody>\r\n		<tr>\r\n			<td bgcolor=\"#ffffbb\" style=\"line-height: 18px; word-break: break-all\" width=\"100%\">\r\n				ftp://dy171:piaohua@dy171.piaohua.com:1064/飘花电影piaohua.com杨丞琳-台北跨年晚会HDTV720P高清现场版.mkv</td>\r\n		</tr>\r\n	</tbody>\r\n</table>",459,1016);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c120524/133N42404320-4N32.jpg",1018,1102);
$z[7][4]['name']="litpic";

?>