{dede:field name='keywords'}五虎屠龙[BD国语无字1280x720高{/dede:field}
{dede:field name='description'}五虎屠龙[BD国语无字1280x720高清版]迅雷下载、免费下载，五虎屠龙[BD国语无字1280x720高清版]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}五虎屠龙[BD国语无字1280x720高清版]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2010-05-14{/dede:field}
{dede:field name='body'}<P><IMG alt="" src="/uploads/allimg/c120524/133NC420910-14b55.jpg" onload=thumbImg(this)><BR><BR>【片&nbsp; &nbsp;&nbsp;&nbsp;名】五虎屠龙<BR>【导&nbsp; &nbsp;&nbsp;&nbsp;演】罗维<BR>【编&nbsp; &nbsp;&nbsp;&nbsp;剧】倪匡 / 罗维<BR>【主&nbsp; &nbsp;&nbsp;&nbsp;演】郑佩佩 / 金汉 / 岳华 / 张翼 / 罗烈<BR>【字幕语言】无<BR>【视频尺寸】1280×720<BR>【文件格式】RMVB+AAC<BR>【国家/地区】香港<BR>【上映 日期】1970-03-26<BR><BR>【剧情 简介】<BR><BR>　　本武侠片由罗维导演，倪匡编剧，郑佩佩、金汉、岳华及罗烈等主演。故事讲述高氏五兄弟，少时家遭巨变，流离失散，长大后，各有际遇，学成惊人武艺；惟五兄弟俱不相识，更不知大仇人就是电影无恶不作的腾龙庄主龙振风(田丰 饰)。侠女燕来(郑佩佩饰)乃高氏兄弟父亲世交之女，奉严父遗命，找寻高家五兄弟，并交出「五虎齐心」武功秘笈，要五兄弟加以苦练，便可战胜龙振风……</P>
<P>【电影截图】：<BR><BR><IMG alt="" src="/uploads/allimg/c120524/133NC421Q0-156405.jpg" onload=thumbImg(this)>&nbsp;<BR><IMG alt="" src="/uploads/allimg/c120524/133NC422E0-1A225.jpg" onload=thumbImg(this)>&nbsp;</P><br>  [下载地址]：<IMG src="/uploads/allimg/c120524/133N2ZL930-142957.jpg" border=0><br>
<table style="BORDER-RIGHT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; BORDER-BOTTOM: #cccccc 1px dotted" cellspacing="0" cellpadding="6" width="95%" align="center" border="0">
    <tbody>
        <tr>
            <td style="WORD-WRAP: break-word" bgcolor="#fdfddf">ftp://5e:5e@d8.3edyy.com:157/【3E电影院www.eee4.cc】五虎屠龙BD国语无字1280x720高清版.rmvb</td>
        </tr>
    </tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120524/133NC424320-1G305.jpg{/dede:field}
