{dede:field name='keywords'}2011韩国梦想演唱会完整版1024高{/dede:field}
{dede:field name='description'}2011韩国梦想演唱会完整版1024高清迅雷下载、免费下载，2011韩国梦想演唱会完整版1024高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}2011韩国梦想演唱会完整版1024高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-07-19{/dede:field}
{dede:field name='body'}<p>
	<img alt="" height="422" src="/uploads/allimg/c120524/133N42404X0-5BW.png" width="750" /></p>
<p>
	Dream Concert（即，梦想演唱会）是由韩国文化体育观光部，韩国演艺人制作者协会（KEPA）等机构携手在1995年创办，旨在让韩国青少年们拥有更多梦想和希望。</p>
<p>
	DreamConcert每年都会举办一次，而且全部免费观看，且出演艺人皆为韩国时下最当红歌手，是每年不可错过的音乐盛宴。<br />
	第十七届2011年<br />
	　　</p>
<p>
	MC：金希澈、具荷拉、宋钟基 　　出演：东方神起/ 2PM/ F(x)/ 金秀炫/ BEAST/ F.T.Island/ SHINee/ Kara/ MISS A/ After School/ IU/ 　</p>
<p>
	T-ara/4Minute/ Sistar/ 5dolls/ Rainbow/ Jewelry/ 4men/ k.will/U-KISS/G.NA/徐仁国/金泰宇。</p>
<p>
	<img alt="" height="422" src="/uploads/allimg/c120524/133N4240GZ-D0V.png" width="750" /></p>
<p>
	<img alt="" height="422" src="/uploads/allimg/c120524/133N4240Y50-M096.png" width="750" /></p>
<p>
	<img alt="" height="422" src="/uploads/allimg/c120524/133N42410410-X4D.png" width="750" /></p>
<p>
	<img alt="" height="422" src="/uploads/allimg/c120524/133N424123F-91044.png" width="750" /></p>
<p>
	[下载地址]： &nbsp;<img border="0" src="/uploads/allimg/c120524/133N2Z4FF-102231.jpg" />
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:1023/飘花电影piaohua.com2011韩国梦想演唱会完整版1024高清.rmvb </td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120524/133N424145F-101120.jpg{/dede:field}
