{dede:field name='keywords'}贱民BD1280高清迅雷下载，免费下{/dede:field}
{dede:field name='description'}贱民BD1280高清迅雷下载、免费下载，贱民BD1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}贱民BD1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-11{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://i.imgur.com/1iAN6.jpg" style="width: 580px; height: 741px" /></p>
<p>
	◎译　　名　贱民<br />
	◎片　　名　Pariah<br />
	◎年　　代　2011<br />
	◎国　　家　美国<br />
	◎类　　别　剧情<br />
	◎语　　言　英语<br />
	◎IMDB评分 &nbsp; 7.0/10 (633 votes)<br />
	◎IMDB链接 &nbsp; <a href="http://www.imdb.com/title/tt1233334/" target="_blank">http://www.imdb.com/title/tt1233334/</a><br />
	◎片　　长　86分钟<br />
	◎导　　演　Dee Rees<br />
	◎编　　剧　Dee Rees<br />
	◎主　　演　阿德佩罗&middot;奥杜耶 Adepero Oduye &nbsp;....Alike<br />
	　　　　　　Kim Wayans &nbsp;....Audrey<br />
	　　　　　　Aasha Davis &nbsp;....Bina<br />
	　　　　　　Charles Parnell &nbsp;....Arthur<br />
	　　　　　　Shamika Cotton &nbsp;....Candace<br />
	　　　　　　Nina Daniels &nbsp;....Gina<br />
	　　　　　　Joey Auzenne &nbsp;....Math Teacher<br />
	　　　　　　Natalie Carter &nbsp;....Rowdy Co-Worker #1<br />
	　　　　　　Afton Williamson &nbsp;....Mika<br />
	　　　　　　Zabryna Guevara &nbsp;....Mrs. Alvarado<br />
	　　　　　　Raymond Anthony Thomas &nbsp;....Mack<br />
	　　　　　　Sahra Mellesse &nbsp;....Sharonda<br />
	　　　　　　Kim Sykes &nbsp;....Mrs. Singletary<br />
	　　　　　　Rob Morgan &nbsp;....Sock<br />
	　　　　　　Pernell Walker &nbsp;....Laura<br />
	　　　　　　Loren Hankin &nbsp;....Personal Cheerleader<br />
	　　　　　　Kinya Shakur Rector &nbsp;....Hospital Clerk<br />
	　　　　　　Chant&eacute; Lewis &nbsp;....Fast Girl #1<br />
	　　　　　　Alaina Dunn &nbsp;....Pier Girl #2<br />
	　　　　　　Ozzie Stewart &nbsp;....Mrs. Campbell<br />
	　　　　　　Jeremie Harris &nbsp;....Bina&#39;s Boyfriend<br />
	　　　　　　Donei Hall &nbsp;....Rowdy Co-Worker #2<br />
	　　　　　　Kymbali Craig &nbsp;....Pier Girl #1<br />
	　　　　　　Olithea Anglin &nbsp;....Fast Girl #2<br />
	　　　　　　Andrea Smith &nbsp;....Pier Girl #3<br />
	　　　　　　Stephanie Andujar &nbsp;....Pier Girl<br />
	　　　　　　Maine Anders &nbsp;....Go Go Dancer<br />
	<br />
	<br />
	◎简　　介<br />
	<br />
	　　影片的女主角是一个叫做艾立凯的17岁黑人少女，她和自己的父母以及妹妹住在布鲁克林。艾立凯是一个很聪明的学生，她很平静，但同时也是很坚定地接受了自己是一个同性恋的事实。在好朋友劳拉的支持和鼓励下，她开始为自己寻找一个女朋友。于是，在自己的坚持和朋友的支持下，艾立凯开始用优雅、幽默和坚韧的态度来度过自己的青春期。<br />
	&nbsp;<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120510/19/62564813201205101942569859621444258_002.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120510/19/62564813201205101942569859621444258_001.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120510/19/62564813201205101942569859621444258_000.jpg" style="width: 720px; height: 405px" /></p>
<p>
	【下载地址】</p>
<table bgcolor="#0099cc" border="0" cellpadding="10" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.net" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy125:piaohua@dy125.piaohua.com:8040/飘花电影piaohua.com贱民BD中英双字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:8040/飘花电影piaohua.com贱民BD中英双字1280高清.rmvb</a></td>
		</tr>
		<tr>
		</tr>
	</tbody>
</table>
<br />{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15K2220-35094.jpg{/dede:field}
