{dede:field name='keywords'}泰坦尼克号/铁达尼号[HD中英双字{/dede:field}
{dede:field name='description'}泰坦尼克号/铁达尼号[HD中英双字1024x576高清版＋国语版[终极收藏版含花絮]]迅雷下载、免费下载，泰坦尼克号/铁达尼号[HD中英双字1024x576高清版＋国语版[终极收藏版含花絮]]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}泰坦尼克号/铁达尼号[HD中英双字1024x576高清版＋国语版[终极收藏版含花絮]]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2009-11-27{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://3e:3e@xl.eee4.com:350/[3E电影站www.eee4.cn]泰坦尼克号BD中字1280x720高清版.rmvb" target=_blank>ftftp://3e:3e@xl.eee4.com:350/[3E电影站www.eee4.cn]泰坦尼克号BD中字1280x720高清版.rmvb</A></TD></TR></TBODY></TABLE><BR><FONT color=#ff0000 size=2><STRONG>经典奥斯卡灾难大片《泰坦尼克号》HD中英双字1024x576高清版 [下载地址]：<IMG src="httftp://www.eee4.com/templets/img/down.jpg" border=0></STRONG></FONT><BR>
<TABLE style="BORDER-RIGHT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; BORDER-BOTTOM: #cccccc 1px dotted" cellSpacing=0 cellPadding=6 width="95%" align=center border=0>
<TBODY>
<TR>
<TD style="WORD-WRAP: break-word" bgColor=#fdfddf><A href="ftftp://3e:3e@www2.eee4.com:654/[www.eee4.cn提供]泰坦尼克号HD中英双字1024x576高清版.rmvb" target=_blank>ftftp://3e:3e@www2.eee4.com:654/[www.eee4.cn提供]泰坦尼克号HD中英双字1024x576高清版.rmvb</A></TD></TR></TBODY></TABLE><BR><FONT color=#ff0000 size=2><STRONG>经典奥斯卡灾难大片《泰坦尼克号》DVD高清国语中字[终极收藏版含花絮] － 来自[3E迅雷电影站eee4.com]下载地址：<IMG src="httftp://www.eee4.com/templets/img/down.jpg" border=0></STRONG></FONT><BR>CD1：<BR>
<TABLE style="BORDER-RIGHT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; BORDER-BOTTOM: #cccccc 1px dotted" cellSpacing=0 cellPadding=6 width="95%" align=center border=0>
<TBODY>
<TR>
<TD style="WORD-WRAP: break-word" bgColor=#fdfddf><ANCHOR></ANCHOR><A href="ftftp://eee4.com:8077@vip14.eee4.com:8077/铁达尼号/[3E迅雷电影站www.eee4.com]泰坦尼克号[DVD国语中字]CD1.rmvb" target=_blank>ftftp://eee4.com:8077@vip14.eee4.com:8077/铁达尼号/[3E迅雷电影站www.eee4.com]泰坦尼克号[DVD国语中字]CD1.rmvb</A></TD></TR></TBODY></TABLE>CD2：<BR>
<TABLE style="BORDER-RIGHT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; BORDER-BOTTOM: #cccccc 1px dotted" cellSpacing=0 cellPadding=6 width="95%" align=center border=0>
<TBODY>
<TR>
<TD style="WORD-WRAP: break-word" bgColor=#fdfddf><ANCHOR></ANCHOR><A href="ftftp://eee4.com:8077@vip14.eee4.com:8077/铁达尼号/[3E迅雷电影站www.eee4.com]泰坦尼克号[DVD国语中字]CD2.rmvb" target=_blank>ftftp://eee4.com:8077@vip14.eee4.com:8077/铁达尼号/[3E迅雷电影站www.eee4.com]泰坦尼克号[DVD国语中字]CD2.rmvb</A></TD></TR></TBODY></TABLE>扩展花絮：<BR>
<TABLE style="BORDER-RIGHT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; BORDER-BOTTOM: #cccccc 1px dotted" cellSpacing=0 cellPadding=6 width="95%" align=center border=0>
<TBODY>
<TR>
<TD style="WORD-WRAP: break-word" bgColor=#fdfddf><ANCHOR></ANCHOR><A href="ftftp://eee4.com:8077@vip14.eee4.com:8077/铁达尼号/[3E迅雷电影站www.eee4.com]泰坦尼克号-扩展花絮-英语.rmvb" target=_blank>ftftp://eee4.com:8077@vip14.eee4.com:8077/铁达尼号/[3E迅雷电影站www.eee4.com]泰坦尼克号-扩展花絮-英语.rmvb</A></TD></TR></TBODY></TABLE></div><ul class="mmlist{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MPW1930-25114.jpg{/dede:field}
