<?php
$z[0]=Array("field","百夫长/世纪战魂[DVD中英双字无",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","百夫长/世纪战魂[DVD中英双字无水印]迅雷下载、免费下载，百夫长/世纪战魂[DVD中英双字无水印]Gvod高清在线播放，剧情介绍等。",72,234);
$z[1][4]['name']="description";
$z[2]=Array("field","百夫长/世纪战魂[DVD中英双字无水印]",236,308);
$z[2][4]['name']="title";
$z[3]=Array("field","",310,349);
$z[3][4]['name']="writer";
$z[4]=Array("field","",351,390);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-08-13",392,442);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",444,481);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://6e:6e@m1.eee4.cc:1518/【3e电影网www.eee4.cc】世纪战魂DVD中英双字无水印.rmvb\" target=_blank>ftftp://6e:6e@m1.eee4.cc:1518/【3e电影网www.eee4.cc】世纪战魂DVD中英双字无水印.rmvb</A></TD></TR></TBODY></TABLE></div><ul class=\"mmlist",483,755);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MP62M20-214U.jpg",757,839);
$z[8][4]['name']="litpic";

?>