{dede:field name='keywords'}伦敦上空的鹰/不列顛之战BD中英{/dede:field}
{dede:field name='description'}伦敦上空的鹰/不列顛之战BD中英双字1280高清战争大片迅雷下载、免费下载，伦敦上空的鹰/不列顛之战BD中英双字1280高清战争大片Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}伦敦上空的鹰/不列顛之战BD中英双字1280高清战争大片{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-07-27{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://images.blu-ray.com/movies/covers/324_front.jpg" /></p>
<p>
	◎译　　名　伦敦上空的鹰/不列顛之战<br />
	◎片　　名　Eagles Over London<br />
	◎年　　代　1969<br />
	◎国　　家　意大利/法国/西班牙<br />
	◎类　　别　剧情/战争<br />
	◎语　　言　英语<br />
	◎字　　幕　中字<br />
	◎IMDB评分 5.7/10&nbsp; 141 votes<br />
	◎文件格式　BD-RMVB<br />
	◎视频尺寸　1024 x 576<br />
	◎文件大小　1CD<br />
	◎片　　长　111 MiN<br />
	◎导　　演　恩佐&middot;卡斯提拉里 Enzo G. Castellari<br />
	◎主　　演　弗朗西斯科&middot;拉瓦尔 Francisco Rabal&nbsp; ....Martin<br />
	　　　　　　特雷莎&middot;希梅拉 Teresa Gimpera&nbsp; ....Sheila<br />
	　　　　　　Frederick Stafford&nbsp; ....Captain Paul Stevens<br />
	　　　　　　范&middot;强生 Van Johnson&nbsp; ....Air Marshal George Taylor<br />
	　　　　　　Ida Galli&nbsp; ....Meg (as Evelyn Stewart)<br />
	　　　　　　Luigi Pistilli&nbsp; ....Maj. Krueger<br />
	　　　　　　Renzo Palmer&nbsp; ....Sgt. Donald Mulligan<br />
	　　　　　　刘易斯&middot;达维拉 Luis D&aacute;vila&nbsp; ....Jacques<br />
	　　　　　　Christian Hay&nbsp; ....Gastonuusee<br />
	　　　　　　Jacques Berthier&nbsp; ....British officer<br />
	　　　　　　Ugo Adinolfi<br />
	　　　　　　Umberto Di Grazia<br />
	　　　　　　Eduardo Fajardo&nbsp; ....German officer<br />
	　　　　　　Georges Rigaud&nbsp; ....British general<br />
	　　　　　　Edy Biagetti&nbsp; ....Karl (uncredited)<br />
	　　　　　　Ricardo Valle</p>
<p>
	◎简　　介　</p>
<p>
	　　二战爆发不久，希特勒妄图与英国媾和的建议得到了英国首相丘吉尔的断然拒绝。于是，德国决定对英国实施&ldquo;海狮行动计划&quot;，即入侵英国本土。然而，英国研究发明的雷达系统使德国空军惶恐不安。要进攻英国，必须掌握制空权，摧毁英国的雷达系统和空军基地指挥部。为此，德国趁英国远征军在法国敦刻尔克撤退的混乱之际，派遣了一个特工队打入英国部队。</p>
<p>
	　　英军陆军上尉保尔接到上级的撤退命令后，便吩咐手下一部分人先撤出阵地前往约定地点汇合。但他赶到地点时，却不见自己人。于是，他焦急地返回查明情况，原来自己的部下均已遭遇不测，他们的身份证件全部被人取走。保尔断定，德国特工人员可能冒充英国士兵，随撤退人马去英国了。回到英国后，他奉命搜捕已经潜入英国的德国特工。为了迅速捕获这些德国人，英军立即更换了证件。</p>
<p>
	　　德国特工人员在克鲁格率领下，在英国展开了秘密福缘官网活动。他们主要的目标是掌握英军的雷达站及空军基地指挥部情况。为得到新证件，德国特工开始动手谋杀一个又一个英军士兵。保尔终于在朴茨茅斯雷达站与这伙德国人短兵相接，并将其歼灭，为皇家空军赢得空战的胜利铺平了道路。</p>
<p>
	幕后制作</p>
<p>
	　　影片以记录戏剧的风格描写德国纳粹在1940年空袭英国人口密集大都市，使英国损失惨重，但也激起了英国人民同仇敌忾&hellip;&hellip;</p>
<p>
	<img alt="" src="http://img.album.pchome.net/54/83/23/24/e45b1de13255361c567b106da4d580f4.of" /></p>
<p>
	<img alt="" src="http://img.album.pchome.net/54/83/23/24/e290b2bd8363ae6a3e57bb4b63c718d1.of" /></p>
<p>
	<img alt="" src="http://img.album.pchome.net/54/83/23/24/a66f3fa2a813e243431a195dbc1d44d8.of" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:1135/飘花电影piaohua.com不列顛之战BD中英双字1280高清.rmvb">&nbsp;ftp://dy44:piaohua@dy44.piaohua.com:1135/飘花电影piaohua.com不列顛之战BD中英双字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://3e:3e@m3.3edyy.com:133/【3E电影院www.3edyy.com】伦敦上空的鹰BD中字1024x576高清版无水印.rmvb">&nbsp;</a><a href="ftp://3e:3e@m3.3edyy.com:133/【3E电影院www.3edyy.com】伦敦上空的鹰BD中字1024x576高清版无水印.rmvb">ftp://3e:3e@m3.3edyy.com:133/【3E电影院www.3edyy.com】伦敦上空的鹰BD中字1024x576高清版无水印.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O161KP-34227.jpg{/dede:field}
