{dede:field name='keywords'}堡垒/野兽特警BD1280高清迅雷下{/dede:field}
{dede:field name='description'}堡垒/野兽特警BD1280高清迅雷下载、免费下载，堡垒/野兽特警BD1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}堡垒/野兽特警BD1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-04{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120504/00/62564813201205040101228034114564502_000.jpg" style="width: 700px; height: 1000px" /></p>
<p>
	◎译　　名　堡垒/野兽特警(台)<br />
	◎片　　名 &nbsp; Rampart<br />
	◎年　　代 &nbsp; 2011<br />
	◎国　　家　美国<br />
	◎类　　别　犯罪/剧情<br />
	◎语　　言　英语<br />
	◎字　　幕　中字<br />
	◎IMDB评分 &nbsp; 6.1/10 (3,897 votes)<br />
	◎IMDB链接 &nbsp; <a href="http://www.imdb.com/title/tt1640548/" target="_blank">http://www.imdb.com/title/tt1640548/</a><br />
	◎导　　演　奥伦&middot;穆弗门 Oren Moverman<br />
	◎主　　演　伍迪&middot;哈里森 Woody Harrelson ....David Douglas Brown<br />
	　　　　　　乔&middot;博恩瑟 Jon Bernthal ....Dan Morone<br />
	　　　　　　乔恩&middot;福斯特 Jon Foster ....Michael Whittaker<br />
	　　　　　　斯黛拉&middot;施纳贝尔 Stella Schnabel ....Jane<br />
	　　　　　　本&middot;福斯特 Ben Foster ....General Terry<br />
	　　　　　　Ruben Garfias ....Pharmacy Security Guard<br />
	　　　　　　Deadlee ....Pharmacy Punk<br />
	　　　　　　Dominic Flores ....Latino Detective<br />
	　　　　　　Matt McTighe ....30-Year-Old Cop<br />
	　　　　　　辛西娅&middot;尼克松 Cynthia Nixon ....Barbara<br />
	　　　　　　安&middot;海切 Anne Heche ....Catherine<br />
	　　　　　　布丽&middot;拉尔森 Brie Larson ....Helen<br />
	　　　　　　Samantha Boyarsky ....Margaret<br />
	　　　　　　Billy Hough ....Piano Player<br />
	　　　　　　奥德拉&middot;麦当娜 Audra McDonald ....Sarah<br />
	　　　　　　Keith Woulard ....Shondell Parmallee<br />
	　　　　　　史蒂夫&middot;布西密 Steve Buscemi ....Bill Blago<br />
	　　　　　　Harriet Sansom Harris ....Stacy Cranston<br />
	　　　　　　Robert Wisdom ....Captain<br />
	　　　　　　西格妮&middot;韦弗 Sigourney Weaver ....Joan Confrey<br />
	　　　　　　Leonard Kelly-Young ....Cal Woodward<br />
	　　　　　　罗宾&middot;怀特 Robin Wright ....Linda Fentress<br />
	　　　　　　尼德&middot;巴蒂 Ned Beatty ....Hartshorn<br />
	　　　　　　Ashley Nikkole Thompson ....Captain&#39;s Daughter (as Ashley Thompson)<br />
	　　　　　　Don Creech ....Head Shark Lawyer<br />
	　　　　　　Chuti Tiu ....Shark Lawyer #1<br />
	　　　　　　Sophie Kargman ....Helen&#39;s Girlfriend<br />
	　　　　　　Angelita Macias ....Flamenco Dancer #1<br />
	　　　　　　Assieh Ghassemi ....Flamenco Dancer #2<br />
	　　　　　　Mike Deldicobo ....Singer<br />
	　　　　　　Borislov Solakov ....Guitar Player<br />
	　　　　　　弗朗西斯&middot;卡普拉 Francis Capra ....Seize Chasco<br />
	　　　　　　Jim O&#39;Hagen ....Hotel Concierge<br />
	　　　　　　Tim Russ ....Command Staff Member #1<br />
	　　　　　　Bryan Rasmussen ....Command Staff Member #2<br />
	　　　　　　艾斯&middot;库珀 Ice Cube ....Kyle Timkins<br />
	　　　　　　William Paul Clark ....Barbara&#39;s Boyfriend<br />
	<br />
	<br />
	<br />
	◎简　　介<br />
	<br />
	剧情<br />
	<br />
	　　一部典型90年代洛杉矶警察家庭剧流派的电影。《堡垒》剖视了一成不变的洛杉矶警察灵魂的阴暗面和不幸遭遇。因为一场波及整个部门的腐败丑闻使伍迪&middot;哈里森饰演的这位警察的过去终于被显露了出来。为了证明自己的清白，他不得不和自己的亲人朋友对抗，包括与自己相处不融洽的女儿，两任前妻，紧咬不放的副检察官，追踪他的调查员，无家可归的目击证人，他年迈的导师和一个谜一般的，立场不定的情人。<br />
	<br />
	一句话评论<br />
	<br />
	《堡垒》也许并不适合所有人去欣赏，但是这依然是一部非常优秀的电影。影片对于惊悚氛围的把握很到位。<br />
	<br />
	&mdash;&mdash;《娱乐周刊》<br />
	<br />
	虽然令人心情悸动，但是影片却单调而乏味。这不是一出丰富的音乐会，而只是一个技巧无懈可击的贝斯的solo。<br />
	<br />
	&mdash;&mdash;《纽约邮报》<br />
	<br />
	简单来说，《堡垒》这部电影展示的只是演技--尤其是伍迪&middot;哈里森那充满说服力和权威性的表演。<br />
	<br />
	&mdash;&mdash;Newark Star-Ledger<br />
	<br />
	幕后制作<br />
	<br />
	　　警察，非我所欲也<br />
	　　伍迪&middot;哈里森在无数的电影里塑造了无数令人难忘的角色，尤其是《天生杀人狂》中的脱线杀人凶手，为他赢得了极大的赞誉和全世界影迷的目光。可以这么说，无论哈里森扮演什么角色，都是值得我们期待的，只不过，在一部电影里扮演警察，这似乎有点超越影迷对哈里森的&ldquo;想象&rdquo;了。<br />
	　　其实对于这个洛杉矶警局的恶棍警察的角色，哈里森本人是一丁点都不喜欢，说得严重些，他甚至&ldquo;憎恨&rdquo;这个角色。哈里森说：&ldquo;我不相信有什么演员愿意说自己不想扮演一个角色，但是我还是要说，我真心不喜欢、也不想演这个角色。这并不是我计划内的角色。但是我依然很希望人们可以去看一看这部电影，这是一部很奇特，很任性的带你呀，它带来的观影感受绝对是与众不同的。让我演一个警察，这实在是有些勉强，我还记得去片场的第一天，工作人员帮我换上制服、带上帽子和警徽后，我的那种别扭劲。他们给我拍了一张定妆照，然后给我看，我当时是一点都不喜欢这个造型，而且我觉得自己穿着警服很怪。可是奥伦&middot;穆弗门看了一眼之后，却说很好。于是我就这么被定了下来。&rdquo;<br />
	　　其实哈里森并不是反感这个角色本身，而是他对这么一个暴虐的故事心有抵触。导演穆弗门说：&ldquo;哈里森一开始不喜欢影片的剧本，他觉得影片的剧本太黑暗、太无所顾忌。所以我在拍摄的时候会时不时地修改一下剧本，并让哈里森参与到影片的编剧和剪辑的创作之中。随着我们工作的渐渐展开，影片的慢慢上道，哈里森也不再那么抵制这个角色了。&rdquo;影片剪辑出来之后，哈里森对自己的表演还是很不放心，因为警察并非是他想扮演的角色。可是在看了电影之后，哈里森渐渐喜欢上了这部电影。他说：&ldquo;我坐下来，静下心来看这部电影。最终的电影和我最先看到的剧本有很大的区别，这些修改还是很好的。5分钟过去、20分钟过去，影片并没有出现任何的问题。看完之后，我发现自己彻底地喜爱上了这部电影，它和我脑子里胡思乱想的根本不是一个样子。后来，我看到穆弗门，向他道了歉，因为这真的是一部不错的电影，我之前对它的评价是错误的。&rdquo;<br />
	　　&ldquo;洛城档案&rdquo;<br />
	　　其实，从一开始吸引穆弗门参与到这部电影之中的，是影片的剧本。穆弗门说：&ldquo;当时是在一家叫做LifeStream的制片公司中，与我合作的《信使》的一个制片人正好在那。他看到到剧本之后，觉得不错，然后他就把剧本带给了我。那个时候我还是很闲的，所以就看了这个一点也不简单的。看完之后，我深深折服，很快就决定要来执导这部电影。&rdquo;<br />
	　　这个不简单的剧本、里面的不简单的故事情节和人物设置，来自于传奇的小说作家詹姆斯&middot;艾罗瑞。他名下最著名的小说是&ldquo;洛城四部曲&rdquo;，第三部《洛城机密》是其中最富盛名的小说，该小说曾经被搬上过银幕，这就是那部著名的《洛城机密》。詹姆斯&middot;艾罗瑞的小说一向气度恢弘、故事强大而且情节难以预料、头绪纷繁复杂。同样的特点出现在了本片之中。奥伦&middot;穆弗门说：&ldquo;艾罗瑞的这个故事非常复杂，而且涉及到的人和事极其广泛，令人难以置信。我被带入到了他的剧本之中。但是为了拍摄的顺利，我还是对剧本进行了一些简化处理。即使是这样，影片中展示的那些洛杉矶的里里外外、前前后后还是有着异常丰富的信息量的，可以说，这简直就是洛杉矶的档案一般。我应该承认，能得到这么好的一个剧本，并且有机会来执导他，是一个导演最为梦寐以求的机会。而且这个故事还很有戏剧性，人物也很立体，对于我来说，这是一个绝好的题材。&rdquo;<br />
	　　对于影片的故事和主演，与哈里森有过合作并在影片中与其有对手戏的本&middot;福斯特说：&ldquo;这个剧本真的是宏大而又复杂，里面有很多很多细节和线索。整个故事的覆盖面非常广，涉及到了很多以往的事例。可以说，这是一部很写实、很真诚的剧本。当我看到剧本的时候，我就确信，哈里森是扮演戴夫的唯一人选，因为无论从气质、性格、形象还是以往塑造的人物带给我们的感觉，他都是最合适、最贴切的。当然，哈里森也在影片中做了很伟大的表演。&rdquo;<br />
	<br />
	花絮<br />
	<br />
	&middot;这是在《信使》一片之后，导演奥伦&middot;穆弗门、演员伍迪&middot;哈里森、本&middot;福斯特和史蒂夫&middot;布西密的第二次合作。<br />
	&middot;伍迪&middot;哈里森在影片中扮演的是一个越战的退伍老兵，他在片中对另一个退伍老兵说自己不是圣诞老人，那个老兵的扮演者是本&middot;福斯特。而在他们合作的那部《信使》中，他们扮演的也都是退伍老兵，也在接到伤亡通知的时候也说了关于圣诞老人的这个笑话。<br />
	&middot;为了扮演好洛杉矶警察这个角色，伍迪&middot;哈里森特意到洛杉矶警局里体验了生活，并且和两个警察一起巡逻、出警了一段时间。<br />
	&middot;影片中的撒旦俱乐部的镜头是在洛杉矶商业区的一个废弃的屠宰场里拍摄的。</p>
<p>
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120504/00/62564813201205040101228034114564502_003.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120504/00/62564813201205040101228034114564502_002.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120504/00/62564813201205040101228034114564502_001.jpg" style="width: 720px; height: 405px" /><br />
	<br />
	&nbsp;</p>
<p>
	【下载地址】</p>
<table bgcolor="#0099cc" border="0" cellpadding="10" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.net" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy125:piaohua@dy125.piaohua.com:8012/飘花电影piaohua.com堡垒野兽特警BD中英双字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:8012/飘花电影piaohua.com堡垒野兽特警BD中英双字1280高清.rmvb</a></td>
		</tr>
		<tr>
		</tr>
	</tbody>
</table>
<br />{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15A2950-31607.jpg{/dede:field}
