<?php
$z[0]=Array("field","猎杀大行动高清720P,1280*720迅",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","猎杀大行动高清720P 1280*720迅雷下载、免费下载，猎杀大行动高清720P 1280*720Gvod高清在线播放，剧情介绍等。",72,220);
$z[1][4]['name']="description";
$z[2]=Array("field","猎杀大行动高清720P 1280*720",222,287);
$z[2][4]['name']="title";
$z[3]=Array("field","",289,328);
$z[3][4]['name']="writer";
$z[4]=Array("field","",330,369);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-07-31",371,421);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",423,460);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://dy125:piaohua@dy125.piaohua.com:1034/飘花电影下载站www.piaohua.com猎杀大行动720p.mkv",462,591);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MP3K3Z-51242.jpg",593,675);
$z[8][4]['name']="litpic";

?>