{dede:field name='keywords'}决战帝国/豺狼帝国BD1280高清迅{/dede:field}
{dede:field name='description'}决战帝国/豺狼帝国BD1280高清迅雷下载、免费下载，决战帝国/豺狼帝国BD1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}决战帝国/豺狼帝国BD1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-17{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="/uploads/allimg/c120525/133O0W95340-2E341.jpg" style="width: 450px; height: 600px" /></p>
<p>
	◎译　　名　决战帝国/豺狼帝国/残骸密码<br />
	◎片　　名　Empire Of The Wolves<br />
	◎年　　代　2005<br />
	◎国　　家　法国<br />
	◎类　　别　剧情/惊悚/动作<br />
	◎语　　言　法语<br />
	◎字　　幕　中字<br />
	◎IMDB评分 5.2/10 (768 votes)<br />
	◎文件格式　BD-RMVB<br />
	◎视频尺寸　1280 x 720<br />
	◎文件大小　1CD<br />
	◎片　　长　123 Min<br />
	◎导　　演　克里斯&middot;纳汉 Chris Nahon<br />
	◎主　　演　让&middot;雷诺 Jean Reno .....Jean-Louis Schiffer<br />
	　　　　　　Arly Jover .....Anna Heymes<br />
	　　　　　　Jocelyn Quivrin .....Paul Nerteaux<br />
	　　　　　　劳拉&middot;莫瑞特 Laura Morante .....Mathilde Wilcrau<br />
	　　　　　　菲力普&middot;巴斯 Philippe Bas .....Laurent<br />
	　　　　　　David Kammenos .....Ackerman<br />
	　　　　　　Didier Sauvegrain .....Dr. Ackerman<br />
	　　　　　　Patrick Floersheim .....Charlier<br />
	　　　　　　伊什尼&middot;齐科特 Etienne Chicot .....Amien<br />
	　　　　　　Albert Dray .....Le lieutenant<br />
	　　　　　　Vernon Dobtcheff .....Kudseyi<br />
	　　　　　　艾乐蒂&middot;纳菲 Elodie Navarre .....La fliquette<br />
	　　　　　　Philippe Du Janerand .....Le l&eacute;giste<br />
	　　　　　　Jean-Pierre Martins .....Professeur Ravi<br />
	　　　　　　Jean-Marc Huber .....Gurdilek<br />
	　　　　　　Donatienne Dupont .....Clothilde<br />
	　　　　　　Jean-Michel Tinivelli .....Caraccili<br />
	　　　　　　Sandra Moreno .....Marie-Sophie<br />
	　　　　　　Laurence Gormezano .....Chantal<br />
	　　　　　　Vincent Grass .....Marius<br />
	　　　　　　Corentin Koskas .....L&#39;interne<br />
	　　　　　　Guillaume Lamant .....Lacroux (as Guillaume Lamant-Deboudt)<br />
	　　　　　　Emmanuelle Escourrou .....Gozar<br />
	　　　　　　Akim Colour .....L&#39;ouvrier<br />
	　　　　　　G&eacute;rard Touratier .....Gruss<br />
	　　　　　　Aur&eacute;lie Meriel .....La secr&eacute;taire<br />
	　　　　　　Emre Kinay .....Le policier<br />
	　　　　　　Arnaud Dul&eacute;ry .....Un flic m&eacute;dico-l&eacute;gal (uncredited)</p>
<p>
	◎简　　介　</p>
<p>
	　　安娜（雅怡乔维亚饰演）是某位政府高官的夫人。一个月来，她经常产生幻觉、失忆等现象，更严重的是，她开始不认得她的高官老公了，她怀疑自己有精神分裂症，于是找上心理医生做诊断，不经意的她发现了一本整形的书，她开始怀疑她的丈夫整形过了&hellip;&hellip;又或者，是她自己被整形了？！</p>
<p>
	　　在此同时，巴黎发生了三宗连续杀人案，死者都是在地下工厂打工的土耳其妇女，她们的尸体残缺不全，死前受到极残酷的虐待！警官保罗（乔瑟林奇维翰饰演）觉得三宗案件背后并不单纯，为了了解土耳其的背后组织，他必须寻求最熟悉土耳其圈子的奇佛（尚雷诺饰演）来帮忙。在追查幕后真相的同时，他们发现安娜的身分竟然是命案的重要线索&hellip;&hellip;</p>
<p>
	幕后制作：</p>
<p>
	　　影片改变自法国畅销惊险小说作者让-克里斯托夫&middot;戈兰杰（电影《暗流》的原作小说作者）的同名小说，导演是曾执导过李连杰主演的《龙之吻》的克里斯&middot;纳隆。这部集合了动作、惊悚、悬疑、警匪的影片耗资2000万欧元的电影拍摄。影片刻意营造诡异而黑暗的气氛，在大多数情况下都笼罩在巴黎阴郁的大雨之中。镜头的运用和后期的剪辑让影片节奏感非常强，剪辑与声效的电影下载配合也很突出。影片由法国著名影星让&middot;雷诺出演。</p>
<p>
	&nbsp;&nbsp;&nbsp; 作为一部惊悚动作片，《豺狼帝国》有扑朔迷离的故事情节，惊心动魄的动作场面，吊诡多端的镜头运动，恰如其分的音乐，让&middot;雷诺领衔主演，导演是曾指导李连杰《龙之吻》的克里斯&middot;纳昂（Chris Nahon），而编剧更是因电影《暗流》而名声鹊起的法国悬疑小说家让-克里斯多夫&middot;格朗内（Jean-Christopher Grang&eacute;）。</p>
<p>
	　　影片一直是两条线索单独展开：一方面，巴黎相继发现了三具土耳其非法移民的女尸，死者都受到严重伤害，嘴唇被割下，全身上下都被特殊利器割伤，年轻干探保罗为了破案，不得不找到在这个地区很有经验、门路广阔的警官施费尔（让&middot;雷诺），一起调查案件；另一方面，在一家巧克力店工作的女职员安娜突然失去记忆，她竟然想不起自己结婚8年的丈夫，她甚至怀疑丈夫做了变脸手术，终日惶恐不安，夜不能眠，但她的怀疑毫无结果。在一次洗浴过后，她突然发现，原来自己的脸被别人换掉了，于是她逃了出去，开始调查这件事。没想到安娜看起来是受害人，后来竟然成为凶手，她在变脸手术后记忆被反恐组织提取，她在回复记忆之后，便开始了她邪教组织的祭祀之旅。</p>
<p>
	　　影片几乎都笼罩在一种潮湿的恐惧中，连绵不断的大雨几乎贯穿整个电影，完全套用经典惊悚片的手法，比如《七宗罪》。影片里出现了几个很有特色的镜头，以前还从未见过。</p>
<p>
	【电影截图】：</p>
<p>
	<img alt="" src="/uploads/allimg/c120525/133O0Wb3F-2GP0.jpg" style="width: 720px; height: 405px" /><img alt="" src="/uploads/allimg/c120525/133O0Wc3Z-2XO9.jpg" style="width: 720px; height: 405px" /><img alt="" src="/uploads/allimg/c120525/133O0X0040-2b961.jpg" style="width: 720px; height: 405px" /></p>

<p>
	【下载地址】</p>
<table bgcolor="#0099cc" border="0" cellpadding="10" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：http://www.xiaozhizhu.net</td>
		</tr>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy125:piaohua@dy125.piaohua.com:8071/飘花电影piaohua.com豺狼帝国BD中字1280高清.rmvb</td>
		</tr>
		<tr>
		</tr>
	</tbody>
</table>
<br />{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O0X01330-30G91.jpg{/dede:field}
