{dede:field name='keywords'}小夫妻时代/双核时代国产剧32[完{/dede:field}
{dede:field name='description'}小夫妻时代/双核时代国产剧32[完]迅雷下载、免费下载，小夫妻时代/双核时代国产剧32[完]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}小夫妻时代/双核时代国产剧32[完]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-15{/dede:field}
{dede:field name='body'}<p>
	<img src="http://img.funshion.com/attachment/new_images/2012/04-06/22849942_1333697179_425.jpg" /></p>
<p>
	<img src="http://img.funshion.com/attachment/new_images/2012/04-06/22849942_1333697177_315.jpg" /></p>
<p>
	<img src="http://img.funshion.com/attachment/new_images/2012/04-06/22849942_1333697174_449.jpg" /></p>
<p>
	<img src="http://img.funshion.com/attachment/new_images/2012/04-06/22849942_1333697172_8.jpg" /></p>
<p>
	<img src="http://img.funshion.com/attachment/new_images/2012/04-06/22849942_1333697169_141.jpg" /></p>
<p>
	<img src="http://img.funshion.com/attachment/new_images/2012/04-06/22849942_1333697145_550.jpg" /></p>
<p>
	【片　　名】：小夫妻时代<br />
	【地　　区】：中国<br />
	【年　　代】：2012<br />
	【类　　型】：现代 家庭 轻喜剧<br />
	【集　　数】：待定<br />
	【语　　言】：普通话<br />
	【字　　幕】：简体中文<br />
	【导　　演】：<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 李　骏<br />
	【主要角色】：<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 马　苏　朱雨辰　隋俊波</p>
<p>
	【剧情简介】：<br />
	&nbsp; 该剧讲述了两对80后独生子女恋爱、结婚生子、经营家庭和在社会上打拼的故事。当红小生朱雨辰在剧中饰演&ldquo;草根&rdquo;徐航，马苏饰演&ldquo;小康女&rdquo;戴可可<br />
	，潘泰名饰演&ldquo;IT男&rdquo;李楠，隋俊波饰演&ldquo;经济适用女&rdquo;叶莹。四人均为80后独生子女，徐航与可可、李楠与叶莹先后步入婚姻的殿堂，随着&ldquo;双核家庭&rdquo;的<br />
	运转，一系列的摩擦和冲突开始显现。</p>
<p>
	&nbsp;</p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.netftp//dy44:piaohua@dy44.piaohua.com:3142/" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3305/飘花电影piaohua.com小夫妻时代01.HDTV.rmvb ">ftp://dy44:piaohua@dy44.piaohua.com:3305/飘花电影piaohua.com小夫妻时代01.HDTV.rmvb </a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3305/飘花电影piaohua.com小夫妻时代02.HDTV.rmvb ">ftp://dy44:piaohua@dy44.piaohua.com:3305/飘花电影piaohua.com小夫妻时代02.HDTV.rmvb </a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3305/飘花电影piaohua.com小夫妻时代03.HDTV.rmvb ">ftp://dy44:piaohua@dy44.piaohua.com:3305/飘花电影piaohua.com小夫妻时代03.HDTV.rmvb </a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3305/飘花电影piaohua.com小夫妻时代04.HDTV.rmvb ">ftp://dy44:piaohua@dy44.piaohua.com:3305/飘花电影piaohua.com小夫妻时代04.HDTV.rmvb </a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3309/飘花电影piaohua.com小夫妻时代05.HDTV.rmvb ">ftp://dy44:piaohua@dy44.piaohua.com:3309/飘花电影piaohua.com小夫妻时代05.HDTV.rmvb </a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3317/飘花电影piaohua.com小夫妻时代06.HDTV.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3317/飘花电影piaohua.com小夫妻时代06.HDTV.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3317/飘花电影piaohua.com小夫妻时代07.HDTV.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3317/飘花电影piaohua.com小夫妻时代07.HDTV.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3317/飘花电影piaohua.com小夫妻时代08.HDTV.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3317/飘花电影piaohua.com小夫妻时代08.HDTV.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3328/飘花电影piaohua.com小夫妻时代09.HDTV.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3328/飘花电影piaohua.com小夫妻时代09.HDTV.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3328/飘花电影piaohua.com小夫妻时代10.HDTV.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3328/飘花电影piaohua.com小夫妻时代10.HDTV.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3331/飘花电影piaohua.com小夫妻时代11.HDTV.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3331/飘花电影piaohua.com小夫妻时代11.HDTV.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3331/飘花电影piaohua.com小夫妻时代12.HDTV.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3331/飘花电影piaohua.com小夫妻时代12.HDTV.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3336/飘花电影piaohua.com小夫妻时代13.HDTV.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3336/飘花电影piaohua.com小夫妻时代13.HDTV.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3336/飘花电影piaohua.com小夫妻时代14.HDTV.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3336/飘花电影piaohua.com小夫妻时代14.HDTV.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3341/飘花电影piaohua.com小夫妻时代15.HDTV.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3341/飘花电影piaohua.com小夫妻时代15.HDTV.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3347/飘花电影piaohua.com小夫妻时代16.HDTV.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3347/飘花电影piaohua.com小夫妻时代16.HDTV.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3350/飘花电影piaohua.com小夫妻时代17.HDTV.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3350/飘花电影piaohua.com小夫妻时代17.HDTV.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3356/飘花电影piaohua.com小夫妻时代18.HDTV.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3356/飘花电影piaohua.com小夫妻时代18.HDTV.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3369/飘花电影piaohua.com小夫妻时代19.HDTV.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3369/飘花电影piaohua.com小夫妻时代19.HDTV.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3369/飘花电影piaohua.com小夫妻时代20.HDTV.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3369/飘花电影piaohua.com小夫妻时代20.HDTV.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3374/飘花电影piaohua.com小夫妻时代21.HDTV.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3374/飘花电影piaohua.com小夫妻时代21.HDTV.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3374/飘花电影piaohua.com小夫妻时代22.HDTV.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3374/飘花电影piaohua.com小夫妻时代22.HDTV.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3397/飘花电影piaohua.com小夫妻时代23.HDTV.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3397/飘花电影piaohua.com小夫妻时代23.HDTV.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3397/飘花电影piaohua.com小夫妻时代24.HDTV.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3397/飘花电影piaohua.com小夫妻时代24.HDTV.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3397/飘花电影piaohua.com小夫妻时代25.HDTV.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3397/飘花电影piaohua.com小夫妻时代25.HDTV.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3397/飘花电影piaohua.com小夫妻时代26.HDTV.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3397/飘花电影piaohua.com小夫妻时代26.HDTV.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3400/飘花电影piaohua.com小夫妻时代27.HDTV.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3400/飘花电影piaohua.com小夫妻时代27.HDTV.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3411/飘花电影piaohua.com小夫妻时代28.HDTV.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3411/飘花电影piaohua.com小夫妻时代28.HDTV.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3411/飘花电影piaohua.com小夫妻时代29.HDTV.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3411/飘花电影piaohua.com小夫妻时代29.HDTV.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3411/飘花电影piaohua.com小夫妻时代30.HDTV.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3411/飘花电影piaohua.com小夫妻时代30.HDTV.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3424/飘花电影piaohua.com小夫妻时代31.HDTV.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3424/飘花电影piaohua.com小夫妻时代31.HDTV.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3424/飘花电影piaohua.com小夫妻时代32.HDTV.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3424/飘花电影piaohua.com小夫妻时代32.HDTV.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1A422P-1J57.jpg{/dede:field}
