{dede:field name='keywords'}豪斯医生第八季22美剧迅雷下载，{/dede:field}
{dede:field name='description'}豪斯医生第八季22美剧迅雷下载、免费下载，豪斯医生第八季22美剧Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}豪斯医生第八季22美剧{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-23{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://pic.piaohua.com/0701pic/allimg/111006/1-1110061IF0627.jpg" /></p>
<p>
	【译 &nbsp; &nbsp;　名】： 豪斯医生<br />
	【原 &nbsp; &nbsp;　名】： House M.D.<br />
	【年 &nbsp; &nbsp;　代】： 2010<br />
	【国 &nbsp; &nbsp;　家】： 美国<br />
	【类 &nbsp; &nbsp;　别】： 医务<br />
	【语 &nbsp; &nbsp;　言】： 英语<br />
	【首 &nbsp; &nbsp;　播】： 2004年11月16日|2010年09月20日<br />
	【电 &nbsp;视 &nbsp;台】： FOX<br />
	【IMDB评分】： 8.9/10 (13,721 人评价)<br />
	【集 &nbsp; &nbsp;　数】： 未知<br />
	【片 &nbsp; &nbsp;　长】： 平均40分钟<br />
	【导 &nbsp; &nbsp;　演】：&bull; Greg Yaitanes &nbsp; (23集 2004-2011)<br />
	　　　　　　　 &bull; Deran Sarafian &nbsp; (22集 2005-2009)<br />
	　　　　　　　 &bull; David Straiton &nbsp; (14集 2007-2011)<br />
	　　　　　　　 &bull; Daniel Attias &nbsp; (7集 2005-2010)<br />
	　　　　　　　 &bull; Daniel Sackheim &nbsp; (7集 2005-2007)<br />
	　　　　　　　 &bull; David Platt &nbsp; (5集 2006-2011)<br />
	　　　　　　　 &bull; Juan Jos&eacute; Campanella &nbsp; (5集 2007-2010)<br />
	　　　　　　　 &bull; Katie Jacobs &nbsp; (5集 2007-2009)<br />
	　　　　　　　 &bull; Andrew Bernstein &nbsp; (5集 2008-2010)<br />
	　　　　　　　 &bull; Peter O&#39;Fallon &nbsp; (4集 2004-2007)<br />
	　　　　　　　 &bull; Matt Shakman &nbsp; (4集 2007-2011)<br />
	　　　　　　　 &bull; Fred Gerber &nbsp; (3集 2005-2006)<br />
	　　　　　　　 &bull; David Semel &nbsp; (3集 2005-2006)<br />
	　　　　　　　 &bull; Lesli Linka Glatter &nbsp; (3集 2007-2009)<br />
	　　　　　　　 &bull; Sanford Bookstaver &nbsp; (3集 2010-2011)<br />
	　　　　　　　 &bull; Newton Thomas Sigel &nbsp; (2集 2004-2006)<br />
	　　　　　　　 &bull; Bryan Spicer &nbsp; (2集 2004-2005)<br />
	　　　　　　　 &bull; Bryan Singer &nbsp; (2集 2004)<br />
	　　　　　　　 &bull; Frederick King Keller &nbsp; (2集 2005)<br />
	　　　　　　　 &bull; James Hayman &nbsp; (2集 2006-2008)<br />
	　　　　　　　 &bull; Martha Mitchell &nbsp; (2集 2006-2007)<br />
	　　　　　　　 &bull; Tucker Gates &nbsp; (2集 2010-2011)<br />
	　　　　　　　 &bull; Miguel Sapochnik &nbsp; (2集 2011)<br />
	【编 &nbsp; &nbsp;　剧】：&bull; David Shore &nbsp; (151集 2004-2011)<br />
	　　　　　　　 &bull; Lawrence Kaplow &nbsp; (20集 2004-2011)<br />
	　　　　　　　 &bull; Peter Blake &nbsp; (19集 2004-2011)<br />
	　　　　　　　 &bull; Thomas L. Moran &nbsp; (16集 2004-2011)<br />
	　　　　　　　 &bull; David Foster &nbsp; (16集 2005-2010)<br />
	　　　　　　　 &bull; Russel Friend &nbsp; (15集 2005-2010)<br />
	　　　　　　　 &bull; Garrett Lerner &nbsp; (15集 2005-2010)<br />
	　　　　　　　 &bull; Doris Egan &nbsp; (15集 2006-2010)<br />
	　　　　　　　 &bull; Liz Friedman &nbsp; (14集 2005-2011)<br />
	　　　　　　　 &bull; Sara Hess &nbsp; (14集 2005-2011)<br />
	　　　　　　　 &bull; David Hoselton &nbsp; (10集 2006-2011)<br />
	　　　　　　　 &bull; Eli Attie &nbsp; (8集 2007-2010)<br />
	　　　　　　　 &bull; Pam Davis &nbsp; (6集 2006-2009)<br />
	　　　　　　　 &bull; Leonard Dick &nbsp; (6集 2007-2009)<br />
	　　　　　　　 &bull; John Mankiewicz &nbsp; (5集 2004-2006)<br />
	　　　　　　　 &bull; Matt Witten &nbsp; (5集 2005-2006)<br />
	　　　　　　　 &bull; Matthew V. Lewis &nbsp; (5集 2006-2009)<br />
	　　　　　　　 &bull; John C. Kelley &nbsp; (4集 2010-2011)<br />
	　　　　　　　 &bull; Sara B. Cooper &nbsp; (2集 2004-2005)<br />
	【演 &nbsp; &nbsp;　员】：&bull; Hugh Laurie &nbsp;饰演 &nbsp;Dr. Gregory House (150集 2004-2011) &nbsp;<br />
	　　　　　　　 &bull; Robert Sean Leonard &nbsp;饰演 &nbsp;Dr. James Wilson (150集 2004-2011) &nbsp;<br />
	　　　　　　　 &bull; Lisa Edelstein &nbsp;饰演 &nbsp;Dr. Lisa Cuddy (149集 2004-2011) &nbsp;<br />
	　　　　　　　 &bull; Omar Epps &nbsp;饰演 &nbsp;Dr. Eric Foreman (149集 2004-2011) &nbsp;<br />
	　　　　　　　 &bull; Jesse Spencer &nbsp;饰演 &nbsp;Dr. Robert Chase (149集 2004-2011) &nbsp;<br />
	　　　　　　　 &bull; Jennifer Morrison &nbsp;饰演 &nbsp;Dr. Allison Cameron (129集 2004-2010) &nbsp;<br />
	　　　　　　　 &bull; Bobbin Bergstrom &nbsp;饰演 &nbsp;Nurse (107集 2005-2011) &nbsp;<br />
	　　　　　　　 &bull; Peter Jacobson &nbsp;饰演 &nbsp;Dr. Chris Taub (74集 2007-2011) &nbsp;<br />
	　　　　　　　 &bull; Olivia Wilde &nbsp;饰演 &nbsp;Dr. Remy &#39;Thirteen&#39; Hadley (74集 2007-2011) &nbsp;<br />
	<br />
	【简 &nbsp; &nbsp;　介】：<br />
	<img alt="" border="0" jquery1317742517875="3" src="http://i.imgur.com/yCTpo.jpg" style="max-width: 780px" /><br />
	<br />
	　　《豪斯医生》（英文：House M.D），又译《怪医豪斯》，是一部美国电视医务剧，由大卫萧尔（David Shore）创作和执行制片，首季第一集并特别邀请电影《X战警》导演布莱恩&middot;辛格（Bryan Singer）执导。该片于2004年11月16日在福克斯电视网首次播放，并获得多项皮博迪奖和艾美奖。本片现时也是福克斯电视网收视观众最多的电视节目。本剧由英国演员休&middot;劳瑞饰演主角格里高利&middot;豪斯医生，这一角色使他获得2006年和2007年金球奖，和2007年影视演员协会奖电视剧最佳男演员奖。目前本剧正在播出第七季。<br />
	<br />
	　　在新季首集中，House和Cuddy为上季结尾时的&ldquo;表白&rdquo;继续努力－－他们希望他们的关<br />
	系能维持下去。与此同时，普林斯顿教学医院知名的神经外科医生患上疾病，不得不缺席多场手术，威胁到医院作为一级急救中心的信誉。为了尽快治好这名同事，豪斯的医疗组想了很多办法。但他们发现这名同事的问题并不仅仅是疾病，还有深层次的原因。他们向豪斯求助，但豪斯一如既往地不予理睬，让他们自己去处理。</p>
<p>
	[下载地址]： &nbsp;<img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" /></p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:1739/飘花电影piaohua.com豪斯医生第八季01.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:1739/飘花电影piaohua.com豪斯医生第八季01.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:1796/飘花电影piaohua.com豪斯医生第八季02.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:1796/飘花电影piaohua.com豪斯医生第八季02.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:1850/飘花电影piaohua.com豪斯医生第八季03.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:1850/飘花电影piaohua.com豪斯医生第八季03.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:1974/飘花电影piaohua.com豪斯医生第八季04.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:1974/飘花电影piaohua.com豪斯医生第八季04.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2074/飘花电影piaohua.com豪斯医生第八季05.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2074/飘花电影piaohua.com豪斯医生第八季05.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2144/飘花电影piaohua.com豪斯医生第八季06.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2144/飘花电影piaohua.com豪斯医生第八季06.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2144/飘花电影piaohua.com豪斯医生第八季07.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2144/飘花电影piaohua.com豪斯医生第八季07.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2212/飘花电影piaohua.com豪斯医生第八季08.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2212/飘花电影piaohua.com豪斯医生第八季08.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2707/飘花电影piaohua.com豪斯医生第八季09.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2707/飘花电影piaohua.com豪斯医生第八季09.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2730/飘花电影piaohua.com豪斯医生第八季10.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2730/飘花电影piaohua.com豪斯医生第八季10.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2773/飘花电影piaohua.com豪斯医生第八季11.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2773/飘花电影piaohua.com豪斯医生第八季11.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2812/飘花电影piaohua.com豪斯医生第八季12.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2812/飘花电影piaohua.com豪斯医生第八季12.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2862/飘花电影piaohua.com豪斯医生第八季13.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2862/飘花电影piaohua.com豪斯医生第八季13.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2916/飘花电影piaohua.com豪斯医生第八季14.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2916/飘花电影piaohua.com豪斯医生第八季14.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3140/飘花电影piaohua.com豪斯医生第八季15.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3140/飘花电影piaohua.com豪斯医生第八季15.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3198/飘花电影piaohua.com豪斯医生第八季16.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3198/飘花电影piaohua.com豪斯医生第八季16.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3240/飘花电影piaohua.com豪斯医生第八季17.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3240/飘花电影piaohua.com豪斯医生第八季17.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3286/飘花电影piaohua.com豪斯医生第八季18.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3286/飘花电影piaohua.com豪斯医生第八季18.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3331/飘花电影piaohua.com豪斯医生第八季19.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3331/飘花电影piaohua.com豪斯医生第八季19.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3373/飘花电影piaohua.com豪斯医生第八季20.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3373/飘花电影piaohua.com豪斯医生第八季20.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3429/飘花电影piaohua.com豪斯医生第八季21.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3429/飘花电影piaohua.com豪斯医生第八季21.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3477/飘花电影piaohua.com豪斯医生第八季22.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3477/飘花电影piaohua.com豪斯医生第八季22.rmvb</a></td>
		</tr>
	</tbody>
</table>
<p>
	&nbsp;</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1AO560-1J42.jpg{/dede:field}
