<dl>
					<dt>
					<a class="img" href="[field:arcurl/]" target="_blank">
					<img alt="[field:title/]" border="0" height="150" src="[field:litpic/]" width="120"></a></dt>
					<dd><strong><a href="[field:arcurl/]">[field:title/]</a></strong><p>
					[field:description/]...</p>
					<span>更新时间：[field:pubdate function="GetDateMK(@me)"/]&nbsp;&nbsp;
					<a href="[field:arcurl/]">点击下载</a></span></dd>
				</dl>