{dede:field name='keywords'}韩半岛日韩剧6迅雷下载，免费下{/dede:field}
{dede:field name='description'}韩半岛日韩剧6迅雷下载、免费下载，韩半岛日韩剧6Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}韩半岛日韩剧6{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-21{/dede:field}
{dede:field name='body'}<p>
	&nbsp;<img src="http://img.funshion.com/attachment/new_images/2012/03-16/31453754_1331892216_188.jpg" width="650" /></p>
<p>
	<img src="http://img.funshion.com/attachment/new_images/2012/03-16/31453754_1331872577_810.jpg" /></p>
<p>
	<img src="http://img.funshion.com/attachment/new_images/2012/03-16/31453754_1331893320_943.jpg" width="650" /></p>
<p>
	<img src="http://img.funshion.com/attachment/new_images/2012/03-16/31453754_1331893325_637.jpg" width="650" /></p>
<p>
	[剧 名]:韩半岛<br />
	[播 送]:韩国TV朝鲜<br />
	[类 型]:TV朝鲜月火剧&nbsp;<br />
	[首 播]:2012年02月06日<br />
	[时 间]:每周一、二晚韩国时间8:55分各播放一集<br />
	[导 演]:李衡民（《坏男人》）<br />
	[编 剧]:尹珠善（《黄真伊》《世宗大王》）<br />
	[主 演]:黄正民 金廷恩 赵成夏 李顺宰<br />
	[集 数]:预计20集<br />
	[主 演]:<a href="http://www.bluemv.com" title="电影下载">http://www.bluemv.com</a>
	点评： 百亿投资大戏,韩版《潜伏》,跟一回不一样的韩剧吧--</p>
<p>
	但愿爱情能跨越一切,成为化解朝、韩矛盾的润滑剂!爱没有国界!--</p>
<p>
	wow 終於在風行看到這部了 劇情超有張力 劇本寫的很好 希望中文字幕可以出快一點 韓國12集了我好想看後面唷 -</p>
<p>
	剧情： 《韩半岛》讲述了黄正民和金廷恩饰演的男女主人公因韩国和朝鲜的新能源开发计划相遇并相恋的故事。</p>
<p>
	<br />
	&nbsp;花絮： 《韩半岛》100亿韩元的制作费准备企划、制作了4年时间的超大型大片连续剧直升机和海洋数中信等雄壮的场面亮相。演员黄正民(韩国科学家徐明俊)和金贞恩(北韩科学家林珍在)有着超现实感的演技,获得了这样的评价。 当天播放的韩半岛第一集中明俊(黄正民饰)和珍在(金正恩饰)在俄罗斯留学时期的恋人,但分裂伊朗壁垒面前分手南北科学家中再次重逢的样子。 &nbsp;</p>
<p>
	<img src="http://img.funshion.com/attachment/new_images/2012/03-19/31453754_1332150475_54.jpg" /></p>
<p>
	<img src="http://img.funshion.com/attachment/new_images/2012/03-19/31453754_1332150474_847.jpg" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.net/">http://www.xiaozhizhu.net</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3446/飘花电影piaohua.com韩半岛EP01.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3446/飘花电影piaohua.com韩半岛EP01.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3446/飘花电影piaohua.com韩半岛EP02.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3446/飘花电影piaohua.com韩半岛EP02.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3446/飘花电影piaohua.com韩半岛EP03.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3446/飘花电影piaohua.com韩半岛EP03.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3446/飘花电影piaohua.com韩半岛EP04.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3446/飘花电影piaohua.com韩半岛EP04.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3446/飘花电影piaohua.com韩半岛EP05.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3446/飘花电影piaohua.com韩半岛EP05.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3446/飘花电影piaohua.com韩半岛EP06.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3446/飘花电影piaohua.com韩半岛EP06.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1AB4F-3D33.jpg{/dede:field}
