<?php
$z[0]=Array("field","rain,的首场演唱会迅雷下载，免",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","rain 的首场演唱会迅雷下载、免费下载，rain 的首场演唱会Gvod高清在线播放，剧情介绍等。",72,200);
$z[1][4]['name']="description";
$z[2]=Array("field","rain 的首场演唱会",202,257);
$z[2][4]['name']="title";
$z[3]=Array("field","",259,298);
$z[3][4]['name']="writer";
$z[4]=Array("field","",300,339);
$z[4][4]['name']="source";
$z[5]=Array("field","2006-08-17",341,391);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",393,430);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://218.12.197.145:9898/diskE/1002/Rain\" target=_blank>ftftp://218.12.197.145:9898/diskE/1002/Rain</A>首次现场演唱会/01.rmvb<BR><A href=\"ftftp://218.12.197.145:9898/diskE/1002/Rain\" target=_blank>ftftp://218.12.197.145:9898/diskE/1002/Rain</A>首次现场演唱会/02.rmvb<BR><BR>2006-07-31 17:28:40 开始连接......<BR>2006-07-31 17:28:40 开始搜索候选资源......<BR>2006-07-31 17:28:42 搜索到40个候选资源<BR>2006-07-31 17:28:42 使用候选资源进行连接......<BR>2006-07-31 17:28:44 开始创建文件......<BR>2006-07-31 17:28:44 文件创建成功，开始下载数据......<BR>2006-07-31 17:29:05 用户取消下载<BR></FONT> <br></div><ul class=\"mmlist",432,1091);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MO60K30-35C0.gif",1093,1175);
$z[8][4]['name']="litpic";

?>