{dede:field name='keywords'}rain,的首场演唱会迅雷下载，免{/dede:field}
{dede:field name='description'}rain 的首场演唱会迅雷下载、免费下载，rain 的首场演唱会Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}rain 的首场演唱会{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2006-08-17{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://218.12.197.145:9898/diskE/1002/Rain" target=_blank>ftftp://218.12.197.145:9898/diskE/1002/Rain</A>首次现场演唱会/01.rmvb<BR><A href="ftftp://218.12.197.145:9898/diskE/1002/Rain" target=_blank>ftftp://218.12.197.145:9898/diskE/1002/Rain</A>首次现场演唱会/02.rmvb<BR><BR>2006-07-31 17:28:40 开始连接......<BR>2006-07-31 17:28:40 开始搜索候选资源......<BR>2006-07-31 17:28:42 搜索到40个候选资源<BR>2006-07-31 17:28:42 使用候选资源进行连接......<BR>2006-07-31 17:28:44 开始创建文件......<BR>2006-07-31 17:28:44 文件创建成功，开始下载数据......<BR>2006-07-31 17:29:05 用户取消下载<BR></FONT> <br></div><ul class="mmlist{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MO60K30-35C0.gif{/dede:field}
