{dede:field name='keywords'}特工维诺德DVD中英双字印度2012{/dede:field}
{dede:field name='description'}特工维诺德DVD中英双字印度2012动作迅雷下载、免费下载，特工维诺德DVD中英双字印度2012动作Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}特工维诺德DVD中英双字印度2012动作{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-12{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://bbs.25pp.com/data/attachment/forum/201205/08/1115222ezxw97wk72zlgdy.jpg" /></p>
<p>
	【影片原名】Agent Vinod<br />
	【中文译名】特工维诺德<br />
	【出品公司】Golden Village Pictures<br />
	【出品年代】2012 年<br />
	【上映日期】2012年3月23日 印度<br />
	【IMDB评分】Ratings: 5.2/10 from 1,794 users<br />
	【国　　家】印度<br />
	【类　　别】动作<br />
	【文件格式】X264+AAC<br />
	【文件大小】896MB<br />
	【视频尺寸】720X400<br />
	【影片长度】102 Mins<br />
	【对白语言】北印度语<br />
	【导　　演】Sriram Raghavan<br />
	【主　　演】卡琳娜&middot;卡普 Kareena Kapoor ....Iram Parveen Billal / Dr. Tanya Ruby<br />
	　　　　　　赛尔夫&middot;阿里&middot;汗 Saif Ali Khan ....Agent Vinod<br />
	　　　　　　Malika Haydon ....Item Number<br />
	　　　　　　古尔沙恩&middot;格鲁维尔 Gulshan Grover ....Tehmur Pasha<br />
	　　　　　　Maryam Zakaria ....Mujra Girl<br />
	　　　　　　拉姆&middot;卡普尔 Ram Kapur ....Abu Nazer<br />
	　　　　　　Prem Chopra ....Kazaan<br />
	　　　　　　Leeann Roberts<br />
	　　　　　　Adil Hussain ....Colonel<br />
	　　　　　　Vasilisa Petina<br />
	　　　　　　Shahbaaz Khan ....Huzefa Lokha<br />
	　　　　　　Ravi Kishan ....Rajan (as Ravi Kissen)<br />
	　　　　　　Anshuman Singh ....Jimmy<br />
	　　　　　　Babu Antony ....Colonel<br />
	　　　　　　Dhiru Dwivedi ....Paan wala</p>
<p>
	【内容简介】<br />
	在权力角逐的中东地区上演着惊心动魄的谍对谍。由宝莱坞帅哥赛尔夫?阿里?汗领衔主演的特工Vinod受上头之托<br />
	准备铲除恐怖组织在地势力，精彩的爆破画面加上对打情节堪称&ldquo;印度版的007&rdquo;。<br />
	片中特工Vinod在调查自己搭档死因时，意外牵扯进一个神秘的组织，并揭发该组织试图引爆核爆的重大阴谋，也因为如此让他陷入了危机，<br />
	在生命受到威胁的情况下，特工Vinod又会做出怎样的绝地大反击，而事件背后到底隐藏着怎样的巨大阴谋？让人拭目以待</p>
<p>
	<img alt="" border="0" src="http://img170.poco.cn/mypoco/myphoto/20120510/15/56209934201205101520272263552685636_005.jpg" style="cursor: hand" title="看原大图" width="500" /></p>
<p>
	&nbsp;<img alt="" border="0" src="http://img170.poco.cn/mypoco/myphoto/20120510/15/56209934201205101520272263552685636_003.jpg" style="cursor: hand" title="看原大图" width="500" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.netftp//dy44:piaohua@dy44.piaohua.com:3125/" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3401/飘花电影piaohua.com特工维诺德DVD中英双字.mp4">ftp://dy44:piaohua@dy44.piaohua.com:3401/飘花电影piaohua.com特工维诺德DVD中英双字.mp4</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15B50Z-21648.jpg{/dede:field}
