<?php
$z[0]=Array("field","鲶鱼/猫鱼[DVD+BD中英双字1024x5",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","鲶鱼/猫鱼[DVD+BD中英双字1024x576高清版]迅雷下载、免费下载，鲶鱼/猫鱼[DVD+BD中英双字1024x576高清版]Gvod高清在线播放，剧情介绍等。",73,245);
$z[1][4]['name']="description";
$z[2]=Array("field","鲶鱼/猫鱼[DVD+BD中英双字1024x576高清版]",247,324);
$z[2][4]['name']="title";
$z[3]=Array("field","",326,365);
$z[3][4]['name']="writer";
$z[4]=Array("field","",367,406);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-02-14",408,458);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",460,497);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://3e:3e@d8.3edyy.com:216/【3E看看www.3ekk.com】猫鱼[DVD中英双字].rmvb\" target=_blank>ftftp://3e:3e@d8.3edyy.com:216/【3E看看www.3ekk.com】猫鱼[DVD中英双字].rmvb</A></TD></TR></TBODY></TABLE><BR><FONT color=#ff0000 size=2><STRONG> [下载地址]：<IMG border=0 src=\"httftp://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg",499,871);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MQ4Ac0-59227.jpg",873,955);
$z[8][4]['name']="litpic";

?>