<?php
$z[0]=Array("field","走进约翰·凯泽尔[DVD中英双字]",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","走进约翰·凯泽尔[DVD中英双字]迅雷下载、免费下载，走进约翰·凯泽尔[DVD中英双字]Gvod高清在线播放，剧情介绍等。",72,224);
$z[1][4]['name']="description";
$z[2]=Array("field","走进约翰·凯泽尔[DVD中英双字]",226,293);
$z[2][4]['name']="title";
$z[3]=Array("field","",295,334);
$z[3][4]['name']="writer";
$z[4]=Array("field","",336,375);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-12-19",377,427);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",429,466);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://5e:5e@d8.3edyy.com:205/【3E看看www.3ekk.com】走进约翰·凯泽尔DVD中英双字.rmvb\" target=_blank>ftftp://5e:5e@d8.3edyy.com:205/【3E看看www.3ekk.com】走进约翰·凯泽尔DVD中英双字.rmvb</A></TD></TR></TBODY></TABLE></div><ul class=\"mmlist",468,744);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MQ453030-21K1.jpg",746,829);
$z[8][4]['name']="litpic";

?>