{dede:field name='keywords'}我是中国人DVD国语中字2012中国{/dede:field}
{dede:field name='description'}我是中国人DVD国语中字2012中国战争迅雷下载、免费下载，我是中国人DVD国语中字2012中国战争Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}我是中国人DVD国语中字2012中国战争{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-21{/dede:field}
{dede:field name='body'}<p>
	&nbsp;<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120420/00/56643687201204200020432681227347148_007.jpg" /></p>
<p>
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120420/00/56643687201204200020432681227347148_006.jpg" /></p>
<p>
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120420/00/56643687201204200020432681227347148_005.jpg" /></p>
<p>
	片名: 我是中国人<br />
	导演: 刘观伟<br />
	编剧: 吴文 / 郭思遥<br />
	主演: 李乾铭 / 颜丹晨 / 黄一飞<br />
	类型: 剧情 / 战争<br />
	制片国家/地区: 中国大陆<br />
	语言: 汉语普通话<br />
	上映日期: 2012-04-19(中国大陆)<br />
	片长: 92分钟<br />
	又名: I am Chinese<br />
	官方网站：<a href="http://www.bluemv.com">http://www.bluemv.com</a></p>
<p>
	剧情简介</p>
<p>
	　　来自台湾的青年海生（李乾铭 饰）深受二战时期日本军国主义思想的影响，满腔热忱的加入了日本特别纵队奔赴大陆参战。但是，当他亲眼目睹了日军残杀中国平民的暴行后，他却一心只想逃回家乡。在回乡的路上，海生遇到宁毓（颜丹晨 饰）等四个女孩 。迫于无奈，海生答应送她们去已被占领的南京城。一路上，海生不仅要保护着宁毓四人，还要躲避特别纵队队长山本一郎的追杀，最后，四个女孩中只有有着日本血统的樱子活了下来。当樱子也看清了日本军人的真实面目后，海生决定奋力掩护樱子突出日军的重围&hellip;&hellip;</p>
<p>
	◎影片截图</p>
<p>
	&nbsp;<img src="http://img170.poco.cn/mypoco/myphoto/20120420/00/56643687201204200020432681227347148_000.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 338px; border-top: 0px solid; border-right: 0px solid" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120420/00/56643687201204200020432681227347148_004.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 338px; border-top: 0px solid; border-right: 0px solid" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120420/00/56643687201204200020432681227347148_002.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 338px; border-top: 0px solid; border-right: 0px solid" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120420/00/56643687201204200020432681227347148_003.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 338px; border-top: 0px solid; border-right: 0px solid" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120420/00/56643687201204200020432681227347148_001.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 338px; border-top: 0px solid; border-right: 0px solid" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.netftp//dy44:piaohua@dy44.piaohua.com:3142/" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3258/飘花电影piaohua.com我是中国人DVD国语中字.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3258/飘花电影piaohua.com我是中国人DVD国语中字.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O162R950-44508.jpg{/dede:field}
