{dede:field name='keywords'}漫游火星美国纪录片BD中英双字10{/dede:field}
{dede:field name='description'}漫游火星美国纪录片BD中英双字1024/1280高清迅雷下载、免费下载，漫游火星美国纪录片BD中英双字1024/1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}漫游火星美国纪录片BD中英双字1024/1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-12-26{/dede:field}
{dede:field name='body'}<p>
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://cdn3a.dvdempire.org/products/82/1326882h.jpg');" src="http://cdn3a.dvdempire.org/products/82/1326882h.jpg" /><br />
	<br />
	◎译　　名　漫游火星<br />
	◎片　　名　Roving Mars<br />
	◎年　　代　2006<br />
	◎国　　家　美国<br />
	◎类　　别　记录<br />
	◎语　　言　英语<br />
	◎字　　幕　中英双字<br />
	◎IMDB评分&nbsp; 7.3/10 (508 votes)<br />
	◎文件格式　BD-RMVB<br />
	◎视频尺寸　1024 x 576<br />
	◎文件大小　1CD<br />
	◎片　　长　0:39:55<br />
	◎导　　演　George Butler<br />
	◎主　　演　保罗&middot;纽曼 Paul Newman<br />
	　　　　　　Stephen Squyres<br />
	　　　　　　Rob Manning<br />
	　　　　　　Dr. Charles Elachi<br />
	　　　　　　Wayne Lee<br />
	◎简　　介　<br />
	<br />
	　　漫游火星(Roving Mars)是由迪斯尼和Sassoon<a href="http://www.3edyy.com/" target="_blank">3e</a> Film Design共同合作推出的作品，内容就是纪录2004年美国太空总署『精神号』(Spirit)以及『机会号』(Opportunity)两辆人造探测车在火星上的种种发现。当初『精神号』和『机会号』是在2004年1月上旬和下旬先后登陆火星，分别在星表面的两端登陆，两辆探测车登陆后立刻在火星的表面展开漫游探勘，并将所发现的图片传回地球。借着这次全球瞩目的火星任务，太空学家希望能揭开火星神秘的面纱，深入探讨火星的奥妙，以及引起众人揣测的火星上生命之谜。</p>
<p>
	【电影截图】：<br />
	<br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://photo7.zxip.com/albums7/folder18/14187/20100801111147/2010813112130100.jpg');" src="http://photo7.zxip.com/albums7/folder18/14187/20100801111147/2010813112130100.jpg" /><br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://photo7.zxip.com/albums7/folder18/14187/20100801111147/20108131121301443.jpg');" src="http://photo7.zxip.com/albums7/folder18/14187/20100801111147/20108131121301443.jpg" /><br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://photo7.zxip.com/albums7/folder18/14187/20100801111147/20108131121313174.jpg');" src="http://photo7.zxip.com/albums7/folder18/14187/20100801111147/20108131121313174.jpg" /></p>
<p>
	[下载地址]：<img border="0" src="/templets/img/down.jpg" /></p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://3e:3e@d8.3edyy.com:174/【3E电影院www.eee4.cc】漫游火星BD中英双字1024x576高清版.rmvb" target="_blank">ftp://3e:3e@d8.3edyy.com:174/【3E电影院www.eee4.cc】漫游火星BD中英双字1024x576高清版.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2436/飘花电影piaohua.com漫游火星BD中英双字1280高清.rmvb ">ftp://dy44:piaohua@dy44.piaohua.com:2436/飘花电影piaohua.com漫游火星BD中英双字1280高清.rmvb </a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1C5RZ-32R6.jpg{/dede:field}
