{dede:field name='keywords'}雌雄莫辨/变装男侍BD1280高清迅{/dede:field}
{dede:field name='description'}雌雄莫辨/变装男侍BD1280高清迅雷下载、免费下载，雌雄莫辨/变装男侍BD1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}雌雄莫辨/变装男侍BD1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-08{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://i.imgur.com/UKYrp.jpg" style="width: 700px; height: 879px" /></p>
<p>
	◎译　　名　雌雄莫辨/变装男侍(台)/阿尔伯特&middot;诺伯斯/奇异人生<br />
	◎片　　名　Albert Nobbs<br />
	◎年　　代　2011<br />
	◎国　　家　英国/爱尔兰<br />
	◎类　　别　剧情<br />
	◎语　　言　英语<br />
	◎字　　幕　中字<br />
	◎IMDB评分 &nbsp;6.6/10 from 5,019 users<br />
	◎IMDB链接 &nbsp;<a href="http://www.imdb.com/title/tt1602098" target="_blank">http://www.imdb.com/title/tt1602098</a><br />
	◎文件格式　X264 + DTS<br />
	◎视频尺寸　1280 x 544<br />
	◎文件大小　1.37 GB<br />
	◎片　　长　113 Mins<br />
	◎导　　演　罗德里格&middot;加西亚 Rodrigo Garc&iacute;a<br />
	◎主　　演　格伦&middot;克洛斯 Glenn Close &nbsp;....Albert Nobbs<br />
	　　　　　　米娅&middot;华希科沃斯卡 Mia Wasikowska &nbsp;....Helen<br />
	　　　　　　珍妮&middot;麦克蒂尔 Janet McTeer &nbsp;....Hubert Page<br />
	　　　　　　安东尼娅&middot;坎贝尔-休斯 Antonia Campbell-Hughes &nbsp;....Emmy<br />
	　　　　　　宝林&middot;科林斯 Pauline Collins &nbsp;....Mrs. Baker<br />
	　　　　　　玛利亚&middot;多耶&middot;肯尼迪 Maria Doyle Kennedy &nbsp;....Mary<br />
	　　　　　　马克&middot;威廉姆斯 Mark Williams &nbsp;....Sean<br />
	　　　　　　James Greene &nbsp;....Patrick<br />
	　　　　　　Serena Brabazon &nbsp;....Mrs. Moore<br />
	　　　　　　迈克尔&middot;麦克埃尔哈顿 Michael McElhatton &nbsp;....Mr. Moore<br />
	　　　　　　Dolores Mullally &nbsp;....Milady<br />
	　　　　　　Bonnie McCormack &nbsp;....Miss Shaw<br />
	　　　　　　菲丽达&middot;劳 Phyllida Law &nbsp;....Mrs. Cavendish<br />
	　　　　　　布莱丹&middot;格里森 Brendan Gleeson &nbsp;....Dr. Holloran<br />
	　　　　　　肯尼斯&middot;克拉德 Kenneth Collard &nbsp;....M. Pigot<br />
	　　　　　　Judy Donovan &nbsp;....Mme. Pigot<br />
	　　　　　　乔纳森&middot;莱斯&middot;梅耶斯 Jonathan Rhys Meyers &nbsp;....Viscount Yarrell<br />
	　　　　　　Phoebe Waller-Bridge &nbsp;....Viscountess Yarrell<br />
	　　　　　　Emerald Fennell &nbsp;....Mrs. Smythe-Willard<br />
	　　　　　　约翰&middot;莱特 John Light &nbsp;....Mr. Smythe-Willard<br />
	　　　　　　Daniel Costello &nbsp;....Mr. Sweeney<br />
	　　　　　　Angeline Ball &nbsp;....Mrs. Gilligan<br />
	　　　　　　Philip O&lsquo;Sullivan &nbsp;....Mr. Gilligan<br />
	　　　　　　亚伦&middot;约翰逊 Aaron Johnson &nbsp;....Joe<br />
	　　　　　　布兰达&middot;弗里克 Brenda Fricker &nbsp;....Polly<br />
	　　　　　　Katie Long &nbsp;....Young Kitchen Maid<br />
	　　　　　　Katie O&lsquo;Brien &nbsp;....Older Kitchen Maid<br />
	　　　　　　Mark Doherty &nbsp;....Porter<br />
	　　　　　　Rhys Burke &nbsp;....George Moore<br />
	　　　　　　Lauren Kinsella &nbsp;....Milly Moore<br />
	　　　　　　Katie Ann McDonough &nbsp;....Laundry Maid<br />
	　　　　　　Kathleen Warner &nbsp;....Laundry Maid<br />
	　　　　　　Cate MacGabhan &nbsp;....Laundry Maid<br />
	　　　　　　Bronagh Gallagher &nbsp;....Cathleen<br />
	　　　　　　Antoinette Healy &nbsp;....Woman on Landau<br />
	　　　　　　Annie Starke &nbsp;....Chocolate Shop Waitress<br />
	　　　　　　Cathy White &nbsp;....Nanny<br />
	　　　　　　Malcolm Blacow &nbsp;....Health Official<br />
	　　　　　　Lily Melcher &nbsp;....Country Girl<br />
	　　　　　　Lucie Melcher &nbsp;....Country Girl<br />
	　　　　　　Raul Riva &nbsp;....Baby<br />
	　　　　　　Juno &nbsp;....Polly&lsquo;s Dog<br />
	　　　　　　<br />
	　　　　　　<br />
	◎简　　介　<br />
	<br />
	　　《阿尔伯特&middot;诺伯斯》讲述了19世纪的爱尔兰，一名女子为了活命不得不把自己化装成男人的故事。<br />
	<br />
	　　阿尔伯特&middot;诺伯斯生活在19世纪的爱尔兰，在都柏林最豪华的酒店工作。这个酒店专门给上层人士提供寻欢作乐的场所。而阿尔伯特&middot;诺伯斯就生活和工作在这里。这是一个生性害羞的仆役长，虽然生活和工作都很忙碌，但是阿尔伯特&middot;诺伯斯还是乐在其中。更重要的是，阿尔伯特为自己保留着一个秘密&mdash;&mdash;&ldquo;他&rdquo;其实是一个女人。<br />
	<br />
	　　在19世纪的爱尔兰，一个女人要在外工作养家糊口是一件非常困难的事情。为了让自己远离贫困和低贱的生活，阿尔伯特&middot;诺伯斯整整女扮男装了20年。起码到现在为止，还没有人能识破她变装和易容的诡计。可是随着酒店里入住了一位英俊、帅气而又年轻的画家之后，一切都变了。<br />
	<br />
	　　动了春心的阿尔伯特&middot;诺伯斯正在蠢蠢欲动，她想把自己带了20年的男性的面具摘掉，而与此同时，她又想保护酒店里的年轻的女佣海伦。而海伦这个时候已经陷入了对酒店的一个年轻的零杂工的爱慕之中&hellip;&hellip;<br />
	<br />
	一句话评论<br />
	<br />
	格伦&middot;克洛斯在影片中送上的精妙绝伦、无与伦比的表演。而这部影片 ，亦被罗德里格&middot;加西亚拍摄得优雅而又稳重。<br />
	&mdash;&mdash;卫报<br />
	<br />
	这部影片应该能算得上是格伦&middot;克洛斯演艺生涯中的丰碑了，但是影片本身却乏善可称，拖拖踏踏，几乎毁掉了格伦&middot;克洛斯的表演。<br />
	&mdash;&mdash;综艺<br />
	<br />
	除了格伦&middot;克洛斯的表演，珍妮&middot;麦克蒂尔的发挥也是可圈可点的。应该说，是演员们的演技撑起了这部讲述19世纪都柏林故事的影片。<br />
	&mdash;&mdash;好莱坞报道者<br />
	<br />
	没有什么能比格伦&middot;克洛斯的演技更耀眼的了。<br />
	&mdash;&mdash;Reel Film Reviews<br />
	<br />
	影片最大的问题就是太虚假，即使在化妆的帮助下，穿上了男人衣服的格伦&middot;克洛斯也一点都不像一个男人，难道电影里的人都看不出来么？<br />
	&mdash;&mdash;AV Club<br />
	<br />
	幕后制作<br />
	<br />
	　　多年的夙愿<br />
	<br />
	　　对于格伦&middot;克洛斯来说，在银幕上扮演这个叫做阿尔伯特&middot;诺伯斯的女扮男装的爱尔兰人，是多年的夙愿。1982年，她第一次被叫去为一出叫做《阿尔伯特&middot;诺伯斯的简单生活》（The Singular Life of Albert Nobbs）的舞台剧试镜，随后，这个角色就扎根在了格伦&middot;克洛斯的脑子里，她一直想把这个故事改编上银幕。其实，不仅仅是主演，格伦&middot;克洛斯还是这部影片的编剧。在她的剧本中，阿尔伯特&middot;诺伯斯被塑造成了一个隐忍、害羞、淡泊而又充满激情的女性。<br />
	<br />
	　　格伦&middot;克洛斯说：&ldquo;我感觉这部电影有那么些超现实，因为从1982年到现在，过去了那么长的时间，这么多人都在为这部电影工作，这令我感到非比寻常。每天早晨，我来到片场，看到那么多忙忙碌碌的工作人员，我都会觉得恍若隔世一般。在我个人看来，拍摄这部电影是有风险的，因为我究竟要如何去塑造阿尔伯特&middot;诺伯斯呢？我需要在脸上展示多少表情和内容呢？因为在她的脸上，往往是没有表情的。其实，诺伯斯是一个幻想家，她常常幻想着自己有朝一日能赚到足够的钱，开一家小店铺，或者是居住在海边。这是一个很奇特的故事，因为电影会让人们在欣赏的同时去幻想小说的内容。所以，我觉得这是一个非常出色色的电影，而且它很值得我们为之工作、付出努力。&rdquo;<br />
	<br />
	　　阿尔伯特&middot;诺伯斯这个人物，简单来说很像是&ldquo;灵魂出窍&rdquo;的人，她并不是她所表现出来的人，她一直都是带着面具生活的。克洛斯说：&ldquo;她的灵魂和她的身体是相分离的。当她穿上男人的衣服，她会觉得自在；但是当穿上女人衣服的时候，她就会无所适从。我要表现的就是这个一点，而这也是一个难点。所以乔治&middot;摩尔称她为一个中性人。&rdquo;<br />
	<br />
	　　想象和现实<br />
	<br />
	　　影片的导演是哥伦比亚人罗德里格&middot;加西亚，他是大名鼎鼎的加西亚&middot;马尔克斯的儿子。因为有老爹这棵大树的庇护，加西亚从小就能在自己加的客厅里接触到很多大导演，比如布努埃尔等等。在自己家庭的影响下，加西亚很早就走上了文艺创作的道路，而且在他的作品中，女性形象一直占据着重要的比重。加西亚说：&ldquo;在这部电影里，我着重刻画的是女性的形象。我常常会幻想自己就是那个女主角，然后会设计很多镜头和故事之类。令我高兴的是，很多人都觉得我的想法挺不错。我把自己生活中的很多熟知的女性形象放到了影片的角色身上。不过，我这并不是表示说，我需要这个角色怎么样怎么样，而是用了一种幻想和真实的方式来创作这个人物。&rdquo;<br />
	<br />
	　　谈及和格伦&middot;克洛斯以及米娅&middot;华希科沃斯卡这样的老演员和新演员的合作，加西亚说：&ldquo;和格伦&middot;克洛斯一起工作的时候，你会觉得演戏是一件非常简答的事情，格伦&middot;克洛斯总是能很轻松地就完成所有的事情。克洛斯是一个很有趣的人，她时时刻刻地都在关注人们的生活和近况，然后会聊出自己的想法。所以，那些和他有过接触的人都曾经遭受过她的&lsquo;审问和质询&rsquo;。年轻的米娅是一个很有才华的演员，她工作很努力，也很认真。我觉得她已经有了成为一线明星的实力了。我看过她演出的《简&middot;爱》，那是一部很棒的电影，简&middot;爱是一个非常难以扮演的角色。在这部电影里，米娅的表演非常稳重。我觉得，她这两年，真正从一个女孩子变成了一个女演员。&rdquo;<br />
	<br />
	花絮<br />
	<br />
	&middot;影片改编自乔治&middot;摩尔（George Moore）的短篇小说《阿尔伯特&middot;诺伯斯的奇异生活》（The Singular Life of Albert Nobbs）。<br />
	<br />
	&middot;阿曼达&middot;塞弗里德和奥兰多&middot;布鲁姆原本都是本片的演员，但是由于档期冲突，最终出现在影片中的是米娅&middot;华希科沃斯卡和亚伦&middot;约翰逊。<br />
	<br />
	&middot;影片在2000年前后曾经进入过制作周期，当时确定的导演是伊斯特凡&middot;萨博，不过这个项目最终未能成行。</p>
<p>
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120508/00/62564813201205080046219830564092958_007.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120508/00/62564813201205080046219830564092958_006.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120508/00/62564813201205080046219830564092958_005.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120508/00/62564813201205080046219830564092958_004.jpg" style="width: 720px; height: 405px" /><br />
	&nbsp;</p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.net/" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy125:piaohua@dy125.piaohua.com:8030/飘花电影piaohua.com雌雄莫辨BD中英双字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:8030/飘花电影piaohua.com雌雄莫辨BD中英双字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15964030-4L54.jpg{/dede:field}
