{dede:field name='keywords'}致命武装DVD中字2011最新美国悬{/dede:field}
{dede:field name='description'}致命武装DVD中字2011最新美国悬疑惊悚大片迅雷下载、免费下载，致命武装DVD中字2011最新美国悬疑惊悚大片Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}致命武装DVD中字2011最新美国悬疑惊悚大片{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-21{/dede:field}
{dede:field name='body'}<p>
	<img src="http://img165.poco.cn/mypoco/myphoto/20120221/11/56643687201202211119001854185430605_004.jpg" /></p>
<p>
	【影片原名】Armed and Deadly<br />
	【中文译名】致命武装<br />
	【出品公司】DeVere Films<br />
	【出品年代】2011 年<br />
	【影片级别】USA:PG-13<br />
	【IMDB链接】<a href="http://www.bluemv.com" title="电影下载">http://www.bluemv.com</a><br />
	【IMDB评分】4.0/10 (24 votes)<br />
	【国　　家】美国<br />
	【类　　别】剧情/悬疑/惊悚<br />
	【导　　演】Andrzej Mrotek<br />
	【主　　演】Lisa Varga ... Janis McKenzie<br />
	　　　　　　Audrey Landers ... Audrey Landers<br />
	　　　　　　Diane Ford ... Diane Ford<br />
	　　　　　　Toni Ann Rossi ... Carol Dodd<br />
	　　　　　　Ken Stellingwerf ... Jamey McKenzie<br />
	　　　　　　David Angers ... Prisoner<br />
	　　　　　　Sava Anthony<br />
	　　　　　　Seva Anthony ... Marie Barbeau<br />
	　　　　　　Donald Ashcraft ... Tattooed Prisoner<br />
	　　　　　　Vance Askins ... Medical Doctor (as Dr. Vance Askins)<br />
	　　　　　　Jim Barnacz ... Soldier<br />
	　　　　　　Bruce Blauer ... Abe Rabinowicz<br />
	　　　　　　Clifford Cespedes ... Mickey Crass<br />
	　　　　　　Phillips Daugherty ... Prison Guard</p>
<p>
	【文件格式】DVD-RMVB<br />
	【文件大小】1CD 436MB<br />
	【视频尺寸】624 x 352<br />
	【影片长度】98 Mins<br />
	【对白语言】英语<br />
	【字幕语言】中文<br />
	【内容简介】</p>
<p>
	JAIN目击自己的孪生兄弟杀害了自己的父母，二十年后，她等待着自己的兄弟来杀自己。二十年来，她一直接受武术的训练已准备这个会面。</p>
<p>
	<br />
	◎影片截图</p>
<p>
	<img src="http://img165.poco.cn/mypoco/myphoto/20120221/11/56643687201202211119001854185430605_001.jpg" /></p>
<p>
	<img src="http://img165.poco.cn/mypoco/myphoto/20120221/11/56643687201202211119001854185430605_000.jpg" /></p>
<p>
	<img src="http://img165.poco.cn/mypoco/myphoto/20120221/11/56643687201202211119001854185430605_003.jpg" /></p>
<p>
	<img src="http://img165.poco.cn/mypoco/myphoto/20120221/11/56643687201202211119001854185430605_002.jpg" /></p>
<p>
	[下载地址]： <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" /></p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2864/飘花电影piaohua.com致命武装DVD中字.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2864/飘花电影piaohua.com致命武装DVD中字.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1512Y40-21020.jpg{/dede:field}
