{dede:field name='keywords'}饥饿游戏抢先版中英双字2012最新{/dede:field}
{dede:field name='description'}饥饿游戏抢先版中英双字2012最新美国科幻动作大片迅雷下载、免费下载，饥饿游戏抢先版中英双字2012最新美国科幻动作大片Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}饥饿游戏抢先版中英双字2012最新美国科幻动作大片{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-04-13{/dede:field}
{dede:field name='body'}<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120413/21/56643687201204132131022874802454106_009.jpg" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120413/21/56643687201204132131022874802454106_006.jpg" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120413/21/56643687201204132131022874802454106_005.jpg" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120413/21/56643687201204132131022874802454106_007.jpg" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120413/21/56643687201204132131022874802454106_008.jpg" /></p>
<p>
	【影片原名】The Hunger Games<br />
	【中文译名】饥饿游戏<br />
	【出品公司】ColorForce<br />
	【出品年代】2012 年<br />
	【上映日期】2012年3月23日 美国<br />
	【影片级别】NewZealand:M | Ireland:12A | Germany:12 | Norway:11 | UK:12A<br />
	【IMDB链接】<a href="http://www.imdb.com/title/tt1392170/">http://www.imdb.com/title/tt1392170/</a><br />
	【IMDB评分】8.0/10 (23,090 votes)<br />
	【国　　家】美国<br />
	【类　　别】动作/剧情/科幻/惊悚</p>
<p>
	<br />
	◎影片截图</p>
<p>
	&nbsp;<img src="http://img170.poco.cn/mypoco/myphoto/20120413/21/56643687201204132131022874802454106_004.jpg" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120413/21/56643687201204132131022874802454106_002.jpg" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120413/21/56643687201204132131022874802454106_003.jpg" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120413/21/56643687201204132131022874802454106_000.jpg" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.netftp//dy44:piaohua@dy44.piaohua.com:3201/" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3215/飘花电影piaohua.com饥饿游戏抢先版中英双字.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3215/飘花电影piaohua.com饥饿游戏抢先版中英双字.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O14cAP-312Q.jpg{/dede:field}
