{dede:field name='keywords'}变种异煞/千钧一发/特卡BD中英双{/dede:field}
{dede:field name='description'}变种异煞/千钧一发/特卡BD中英双字1280高清迅雷下载、免费下载，变种异煞/千钧一发/特卡BD中英双字1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}变种异煞/千钧一发/特卡BD中英双字1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-01-03{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://eee4.com:8116@vip13.eee4.com:8116/[3E迅雷电影站www.eee4.com]千钧一发DVD中英双字CD1.rmvb" target="_blank{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MOUU10-24448.jpg{/dede:field}
