{dede:field name='keywords'}星河战队2:联邦英雄BD中英双字10{/dede:field}
{dede:field name='description'}星河战队2:联邦英雄BD中英双字1024/1280高清迅雷下载、免费下载，星河战队2:联邦英雄BD中英双字1024/1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}星河战队2:联邦英雄BD中英双字1024/1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-01-07{/dede:field}
{dede:field name='body'}<p>
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://images.dvdempire.com/gen/movies/1409089h.jpg');" src="http://images.dvdempire.com/gen/movies/1409089h.jpg" /></p>
<p>
	<img alt="" src="http://www.dylele.com/juzhao/2010-9-23/6383494826.jpg" /><br />
	<br />
	◎译　　名　星河战队2:联邦英雄<br />
	◎片　　名　Starship Troopers 2 Hero of the Federation<br />
	◎年　　代　2004<br />
	◎国　　家　美国<br />
	◎类　　别　恐怖/动作/冒险/科幻<br />
	◎语　　言　英语<br />
	◎字　　幕　中英双字<br />
	◎文件格式　BD-RMVB<br />
	◎视频尺寸　1024 x 576<br />
	◎文件大小　1CD<br />
	◎片　　长　1:31:36<br />
	◎导　　演　菲尔&middot;迪彼特 Phil Tippett<br />
	◎主　　演　理查德&middot;布基 Richard Burgi .....Captain V.J. Dax<br />
	　　　　　　凯莉&middot;卡尔森 Kelly Carlson .....Pvt. Charlie Soda<br />
	　　　　　　Cy Carter .....Pvt. Billie Otter<br />
	　　　　　　Bill Brown .....Pvt. Ottis Brick (as Billy Brown)<br />
	　　　　　　Tim Conlon .....Fleet Pilot (as Tim Conlin)<br />
	　　　　　　Sandrine Holt .....Pvt. Jill Sandee<br />
	　　　　　　Bobby C. King .....Smiling Lieutenant (as Robby C. King)<br />
	　　　　　　Ed Lauter .....Gen. J. G. Shepherd<br />
	　　　　　　J.P. Manoux .....TSgt. Ari Peck<br />
	　　　　　　Lawrence Monoson .....Lt. Pavlov Dill<br />
	　　　　　　Colleen Porch .....Pvt. Lei Sahara<br />
	　　　　　　Drew Powell .....Pvt. Kipper Tor<br />
	　　　　　　Ed Quinn .....Pvt. Joe Griff<br />
	　　　　　　Jason-Shane Scott .....Pvt. Duff Horton<br />
	　　　　　　Stephen Stanton .....FedNet (voice)<br />
	　　　　　　Brenda Strong .....Sgt. Dede Rake<br />
	　　　　　　布莱恩&middot;泰 Brian Tee .....Cpl. Thom Kobe<br />
	　　　　　　David Wells .....Recruiting Sargeant<br />
	　　　　　　Jon Davison .....Outpost (voice) (uncredited)<br />
	　　　　　　Jesse Grce .....Handsome<a href="http://www.eee4.cc/" target="_blank">3e</a> Trooper (in photograph) (uncredited)<br />
	　　　　　　Elizabeth Keller .....Trooper #3 (uncredited)<br />
	　　　　　　Oliver Keller .....Trooper #2 (uncredited)<br />
	　　　　　　Jonathan Passow .....Lt. Spears, General&#39;s Guard (uncredited)<br />
	　　　　　　Ty Williams .....Trooper (uncredited)<br />
	<br />
	◎简　　介　<br />
	<br />
	&nbsp; &nbsp; 续集内容虽然同是谈及与外星虫族的交战，但故事则讲述另一边的战场 - Zulu Angel 前线哨站。一小队由 Shepherd 将军率领的机动部兵，为了修复已被弃置的前线哨站而到达该地，在那里，他们除了发现唯一的生还者 Dax 上尉外，还要跟由四面八方而来的外星虫族作战&hellip;&hellip;</p>
<p>
	【电影截图】：<br />
	<br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://photo4.zxip.com/albums4/folder18/14184/20100310154516/20105291121573000.jpg');" src="http://photo4.zxip.com/albums4/folder18/14184/20100310154516/20105291121573000.jpg" />&nbsp;<br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://photo4.zxip.com/albums4/folder18/14184/20100310154516/2010529112157672.jpg');" src="http://photo4.zxip.com/albums4/folder18/14184/20100310154516/2010529112157672.jpg" /></p>
<p>
	[下载地址]：<img border="0" src="/templets/img/down.jpg" /></p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://3e:3e@d8.3edyy.com:162/【3E电影院www.eee4.cc】星河战队2[BD中英双字1024x576高清版].rmvb" target="_blank">ftp://3e:3e@d8.3edyy.com:162/【3E电影院www.eee4.cc】星河战队2[BD中英双字1024x576高清版].rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2539/飘花电影piaohua.com星河战队2BD中英双字1280高清.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2539/飘花电影piaohua.com星河战队2BD中英双字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15ZK60-15396.jpg{/dede:field}
