{dede:field name='keywords'}第45届美国乡村音乐协会奖颁奖典{/dede:field}
{dede:field name='description'}第45届美国乡村音乐协会奖颁奖典礼HD中字迅雷下载、免费下载，第45届美国乡村音乐协会奖颁奖典礼HD中字Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}第45届美国乡村音乐协会奖颁奖典礼HD中字{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-11-13{/dede:field}
{dede:field name='body'}<p>
	中文片名: 第45届美国乡村音乐协会奖颁奖典礼<br />
	英文片名: 45th Annual Country Music Association Awards [CMAs]<br />
	剧集分类: 纪录<br />
	影片类型: 美剧<br />
	资源格式: RMVB<br />
	上影时间: 2011<br />
	对白语言: 英语&nbsp;<br />
	字幕语种: 中字</p>
<p>
	介绍:<br />
	第45届美国乡村音乐协会奖11月9日在美国乡村音乐之都 Nashville 举行颁奖典礼，提名名单揭晓，乡村小天后 Taylor Swift、Jason Aldean、Brad Paisley 以及Blake Shelton 均以五项提名领跑今年乡村音乐奖。</p>
<p>
	此外，Zac Brown Band乐团 以及三人组合 The Band Perry 分别4项音乐提名紧随其后，而去年的大赢家 Miranda Lambert 这次则只获得最佳女歌手以及年度音乐事件两项提名。</p>
<p>
	2011年美国乡村音乐协会奖将由 Carrie Underwood 和 Brad Paisley 搭档主持，这也将是两人第四次共同主持。音乐颁奖礼于今年的11月9日在美国乡村音乐之都 Nashville 举行，由ABC电视台转播。</p>
<p>
	第45届美国乡村音乐协会奖得奖及提名名单如下：</p>
<p>
	年度最佳艺人Entertainer of the Year<br />
	杰森-阿尔丁Jason Aldean<br />
	布拉德-派斯利Brad Paisley<br />
	布莱克-谢尔顿Blake Shelton<br />
	泰勒-斯威夫特Taylor Swift<br />
	凯斯-厄本Keith Urban</p>
<p>
	年度最佳新人New Artist of the Year<br />
	The Band Perry乐队<br />
	卢克-布莱恩Luke Bryan<br />
	埃里克-丘奇Eric Church<br />
	Thompson Square乐队<br />
	克里斯-杨Chris Young</p>
<p>
	年度最佳女歌手Female Vocalist of the Year<br />
	莎拉-埃文斯Sara Evans<br />
	米兰达-兰伯特Miranda Lambert<br />
	马丁娜-麦克布莱德Martina McBride<br />
	泰勒-斯威夫特Taylor Swift<br />
	凯莉-安德伍德Carrie Underwood</p>
<p>
	年度最佳男歌手Male Vocalist of the Year<br />
	杰森-阿尔丁Jason Aldean<br />
	肯尼-切斯尼Kenny Chesney<br />
	布拉德-派斯利Brad Paisley<br />
	布莱克-谢尔顿Blake Shelton<br />
	凯斯-厄本Keith Urban</p>
<p>
	年度最佳组合Vocal Group of the Year<br />
	The Band Perry<br />
	Lady Antebellum<br />
	Little Big Town<br />
	Rascal Flatts<br />
	Zac Brown Band</p>
<p>
	年度最佳二重唱Vocal Duo of the Year<br />
	The Civil Wars<br />
	Montgomery Gentry<br />
	Steel Magnolia<br />
	Sugarland<br />
	Thompson Square</p>
<p>
	年度最佳专辑Album of the Year<br />
	&lsquo;All About Tonight,&rsquo; Blake Shelton<br />
	&lsquo;My Kinda Party,&rsquo; Jason Aldean<br />
	&lsquo;Speak Now,&rsquo; Taylor Swift<br />
	&lsquo;This is Country Music,&rsquo; Brad Paisley<br />
	&lsquo;You Get What You Give,&rsquo; Zac Brown Band</p>
<p>
	年度最佳单曲(艺人和制作人类)Single of the Year (Award goes to artist and producer)<br />
	&lsquo;A Little Bit Stronger,&rsquo; Sara Evans<br />
	&lsquo;Colder Weather,&rsquo; Zac Brown Band<br />
	&lsquo;Don&rsquo;t You Wanna Stay,&rsquo; Jason Aldean Feat. Kelly Clarkson<br />
	&lsquo;Honey Bee,&rsquo; Blake Shelton<br />
	&lsquo;If I Die Young,&rsquo; The Band Perry</p>
<p>
	年度最佳歌曲(创作者类)Song of the Year (Award goes to songwriters)<br />
	&lsquo;Colder Weather,&rsquo; Zac Brown, Wyatt Durrette, Levi Lowrey, and Coy Bowles<br />
	&lsquo;Dirt Road Anthem,&rsquo; Brantley Gilbert, Colt Ford<br />
	&lsquo;If I Die Young,&rsquo; Kimberly Perry<br />
	&lsquo;Mean,&rsquo; Taylor Swift<br />
	&lsquo;You and Tequilla,&rsquo; Matraca Berg and Deanna Carter</p>
<p>
	年度最佳音乐瞬间Musical Event of the Year<br />
	&lsquo;As She&rsquo;s Walking Away,&rsquo; Zac Brown Band Feat. Alan Jackson<br />
	&lsquo;Coal Miner&rsquo;s Daughter,&rsquo; Lorettay Lynn, Sheryl Crow and Miranda Lambert<br />
	&lsquo;Don&rsquo;t You Wanna&rsquo; Stay,&rsquo; Jason Aldean Feat. Kelly Clarkson<br />
	&lsquo;Old Alabama,&rsquo; Brad Paisley Feat. Alabama<br />
	&lsquo;You and Tequilla,&rsquo; Kenny Chesney Feat. Grace Potter</p>
<p>
	年度最佳音乐电视Music Video of the Year<br />
	&lsquo;Honey Bee,&rsquo; Blake Shelton<br />
	&lsquo;If I Die Young,&rsquo; The Band Perry<br />
	&lsquo;Mean,&rsquo; Taylor Swift<br />
	&lsquo;Old Alabama,&rsquo; Brad Paisley Feat. Alabama<br />
	&lsquo;You and Tequilla,&rsquo; Kenny Chesney Feat. Grace Potter</p>
<p>
	年度最佳乐手Musician of the Year<br />
	Sam Bush &ndash; Mandolin<br />
	Jerry Douglas &ndash; Dobro<br />
	Paul Franklin &ndash; Steel guitar<br />
	Dann Huff &ndash; Guitar<br />
	Mac McAnally &ndash; Guitar</p>
<p>
	本届乡村音乐协会奖获奖名单：</p>
<p>
	年度娱乐人物：Taylor Swift</p>
<p>
	年度最佳男歌手：Blake Shelton</p>
<p>
	年度最佳女歌手：Miranda Lambert</p>
<p>
	年度最佳二人组：Sugarland</p>
<p>
	年度最佳组合：Lady Antebellum</p>
<p>
	年度最佳专辑：Jason Aldean《My Kinda Party》</p>
<p>
	年度最佳单曲：The Band Perry《If I Die Young》</p>
<p>
	年度最佳歌曲：The Band Perry《If I Die Young》</p>
<p>
	年度最佳新人：The Band Perry</p>
<p>
	年度音乐事件：Jason Aldean &amp; Kelly Clarkson《Don&#39;t You Wanna Stay》</p>
<p>
	年度最佳音乐录影带：Kenny Chesney &amp; Grace Potter《You and Tequila》</p>

<p>
	下载地址：<img border="0" src="/uploads/allimg/c120524/133N2ZL930-142957.jpg" /></p>

<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				</anchor>&nbsp;ftp://dy44:piaohua@dy44.piaohua.com:2076/飘花电影piaohua.com第45届美国乡村音乐协会奖颁奖典礼HD中字.rmvb</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120524/133N493I250-N152.jpg{/dede:field}
