{dede:field name='keywords'}霸王花BD国粤双语中字1024/1280{/dede:field}
{dede:field name='description'}霸王花BD国粤双语中字1024/1280高清经典动作喜剧迅雷下载、免费下载，霸王花BD国粤双语中字1024/1280高清经典动作喜剧Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}霸王花BD国粤双语中字1024/1280高清经典动作喜剧{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-08-28{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="/uploads/allimg/c120525/133O03460J0-LF7.jpg" /></p>
<p>
	中文名： 霸王花<br />
	英文名： Lady Enforcers<br />
	导&nbsp;&nbsp; 演： 钱升玮<br />
	主&nbsp;&nbsp; 演： 惠英红 胡慧中 罗芙洛<br />
	类&nbsp;&nbsp; 型： 动作<br />
	地&nbsp;&nbsp; 区： 港台<br />
	发&nbsp;&nbsp; 行： 1988<br />
	字　 幕　&nbsp;&nbsp; 无<br />
	规&nbsp;&nbsp; 格： 720P<br />
	语　 言　 国语</p>
<p>
	剧情主要描述新成立的女飞虎队经过严格的训练后，人个成为英勇善战的女豪杰，并在追捕毒贩的实战中表现优异，成为突出的霸王花队伍。影片在强烈而艰苦的训练中，也安排了女队员与男队员之间的争斗和感情纠结，增添了温馨的气氛。</p>
<p>
	&nbsp;&nbsp; &ldquo;霸王花&rdquo;这一商业概念脱胎于《五福星》电影，最初是胡慧中经典的警女形象而独享的一个称谓。在1988年，《五福星》经典电影拍档相继分崩离析之后，其中的诸多商业卖点都被电影圈一抢而空，不只是王晶接连以《精装追女仔2福星俏佳人》、《最佳损友》、《最佳损友闯情关》连续掠料，而成龙则更是巧取了其中&ldquo;霸王花&rdquo;这一卖点大肆炒卖。&nbsp; 详细介绍...</p>
<p>
	剧情主要描述新成立的女飞虎队经过严格的训练后，人个成为英勇善战的女豪杰，并在追捕毒贩的实战中表现优异，成为突出的霸王花队伍。影片在强烈而艰苦的训练中，也安排了女队员与男队员之间的争斗和感情纠结，增添了温馨的气氛。</p>
<p>
	&nbsp;&nbsp; &ldquo;霸王花&rdquo;这一商业概念脱胎于《五福星》电影，最初是胡慧中经典的警女形象而独享的一个称谓。在1988年，《五福星》经典电影拍档相继分崩离析之后，其中的诸多商业卖点都被电影圈一抢而空，不只是王晶接连以《精装追女仔2福星俏佳人》、《最佳损友》、《最佳损友闯情关》连续掠料，而成龙则更是巧取了其中&ldquo;霸王花&rdquo;这一卖点大肆炒卖。影片以身手出众的女警官作为主推，胡慧中、惠英红、罗芺洛这样的金牌打女终于有了用武之地，在影片中大展中国功夫。冯淬帆、许冠英、吴君如、成奎安、董骠等人的加入，更为影片提供了连篇累牍的笑料，影片虽说情节较为简单，也没有超级雄厚的资金投入，但以上这些元素已经足以令其在市场上回收成本。本片在1988年获得了一千六百万的票房，算是中上，但以影片主推新人的阵容来看，这一点收益已经是极为难得。</p>
<p>
	截　　图：</p>
<p>
	<img alt="" src="/uploads/allimg/c120525/133O03462260-X439.jpg" style="width: 600px; height: 338px" /></p>
<p>
	<img alt="" src="/uploads/allimg/c120525/133O034634P-93094.jpg" style="width: 600px; height: 338px" /></p>
<p>
	<img alt="" src="/uploads/allimg/c120525/133O034643F-101923.jpg" style="width: 600px; height: 338px" /></p>
<p>
	<img alt="" src="/uploads/allimg/c120525/133O034A3F-116052.jpg" style="width: 600px; height: 338px" /></p>
<p>
	[霸王花720P下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="/uploads/allimg/c120524/133N2Z4FF-102231.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy195:piaohua@dy195.piaohua.com:1012/飘花电影下载站www.xiaozhizhu.net霸王花720P.rmvb </td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:1416/飘花电影piaohua.com霸王花BD国粤双语1024高清.mkv</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O034B510-124244.png{/dede:field}
