{dede:field name='keywords'}金属风暴BD高清迅雷下载，免费下{/dede:field}
{dede:field name='description'}金属风暴BD高清迅雷下载、免费下载，金属风暴BD高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}金属风暴BD高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-03-07{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://i.imgur.com/M6zfK.jpgg" style="width: 500px; height: 809px" /></p>
<p>
	◎译　　名　金属风暴<br />
	◎片　　名　Metal Tornado<br />
	◎年　　代　2011<br />
	◎国　　家　加拿大<br />
	◎类　　别　动作/科幻<br />
	◎语　　言　英语<br />
	◎字　　幕　N/A<br />
	◎IMDB评分 &nbsp; 3.3/10 (77 votes)<br />
	◎IMDB链接 &nbsp; <a href="http://www.imdb.com/title/tt1688653/" target="_blank">http://www.imdb.com/title/tt1688653/</a><br />
	◎文件格式　X264 + DTS<br />
	◎视频尺寸　1280 x 720<br />
	◎文件大小　1 DVD<br />
	◎片　　长　1h 30min<br />
	◎导　　演　Gordon Yang<br />
	◎主　　演　格雷格&middot;艾维甘 Greg Evigan ....Jonathan<br />
	　　　　　　Sophie Gendron ....Allysa<br />
	　　　　　　John Maclaren ....Ron<br />
	　　　　　　Alexis Maitland ....Megan<br />
	　　　　　　Cinthia Burke ....Lisa<br />
	　　　　　　Victor Cornfoot ....Police Officer<br />
	　　　　　　妮可&middot;德波儿 Nicole de Boer ....Rebecca<br />
	　　　　　　Kate Drummond ....Wendy<br />
	　　　　　　J.F. Dufault ....Patient<br />
	　　　　　　Jack Eyamie ....Hank<br />
	　　　　　　Tim Finnigan ....Young Farmer<br />
	　　　　　　Terry Green ....Air Force General<br />
	　　　　　　Landon Hicks ....Trail Bike Rider<br />
	　　　　　　Claudia Jurt ....Sheriff Barker<br />
	　　　　　　Henry Kwok ....Detective<br />
	　　　　　　Teri Loretto ....Marjorie<br />
	　　　　　　Stephen MacDonald ....Nick Edwards<br />
	　　　　　　Geoff McBride ....Mr. Whelan<br />
	　　　　　　Jon McLaren ....Shane<br />
	　　　　　　Claude Naubert ....Jacques<br />
	　　　　　　卢&middot;戴蒙德&middot;菲利普斯 Lou Diamond Phillips ....Michael Edwards<br />
	　　　　　　Paul Rainville ....Paul<br />
	　　　　　　Caroline Redekopp ....TV Reporter<br />
	　　　　　　Robert Reynolds ....Stan Brooks<br />
	　　　　　　Frank Schorpion<br />
	　　　　　　Daniel Simpson ....Kevin<br />
	　　　　　　Mark Slacke ....Woodsman<br />
	　　　　　　卡蜜尔&middot;索拉瑞 Camille Solari ....Melissa<br />
	　　　　　　Oliver Soul ....Deputy<br />
	　　　　　　Rob Stewart<br />
	　　　　　　Daniell Thompson ....Patient<br />
	　　　　　　Sean Tucker ....Sheriff Joe Riley<br />
	　　　　　　Stephen Winters ....Todd Duckworth<br />
	　　　　　　Chris Wylie ....Albert<br />
	　　　　　　Christopher Wyllie ....Albert<br />
	　　　　　　Paul Finnigan ....Dr. Crawford (uncredited)<br />
	　　　　　　Jolanta Mojsej ....Corporate Executive (uncredited)<br />
	　　　　　　Simon Seline ....Scientist (uncredited)<br />
	<br />
	<br />
	<br />
	◎简 &nbsp;　 介<br />
	<br />
	&nbsp; &nbsp; &nbsp;塞缪尔普朗克负责的Helios项目是负责存储源源不绝的太阳光线并将其转换成可再生能源的高科技设施。 经过多年的研究及数百万美元的投入，现在是时候来测试系统。 最初按计划进行， 但是当该设施无法控制大量的未来能源时，欢呼声转向惨叫。 带电粒子开始纷飞在自己的周围，形成一个巨大的磁场旋涡，迅速成为地球上的第一个磁龙卷风！<br />
	<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120307/08/62564813201203070820202402266333467_002.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120307/08/62564813201203070820202402266333467_001.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120307/08/62564813201203070820202402266333467_000.jpg" style="width: 720px; height: 405px" /><br />
	&nbsp;</p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="&#13;&#10;ftp://dy125:piaohua@dy125.piaohua.com:7698/飘花电影piaohua.com金属风暴BD中字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:7698/飘花电影piaohua.com金属风暴BD中字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1592A30-22415.jpg{/dede:field}
