{dede:field name='keywords'}大有前途抢先版国语中字方中信{/dede:field}
{dede:field name='description'}大有前途抢先版国语中字方中信 王宝强迅雷下载、免费下载，大有前途抢先版国语中字方中信 王宝强Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}大有前途抢先版国语中字方中信 王宝强{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-18{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://apollo.s.dpool.sina.com.cn/nd/dataent/moviepic/pics/106/moviepic_3b578b933a94ef94534c6124685fb8ea.jpg" /></p>
<p>
	导演: 邓炽垣<br />
	编剧: 杜鹏 / 苏竞元 / 张珊珊 / 邓炽垣<br />
	主演: 方中信 / 王宝强 / 刘桦 / 李彧 / 戎祥 / 林苑 / 张达明 / 童爱玲 / 王迅<br />
	制片国家/地区: 中国大陆<br />
	语言: 汉语普通话<br />
	剧情简介</p>
<p>
	　　《大有前途》将故事背景置于当下热门话题&ldquo;经济危机&rdquo;中，讲述空有大量资源闲置却苦于经济压力无从发展的&ldquo;大有村&rdquo;，在各路人等乌龙百出的&ldquo;努力&rdquo;下重新走上美好前途的故事。商场失意的台商蔡竹强（戎祥饰）欲离开大有村，心急火燎的村长李彪（李彧饰）病急乱投医之下，派出村民阿昆（王宝强饰）进城寻找靠山；然而不得要领的阿昆丝毫没有来钱的门路，四处&ldquo;碰瓷&rdquo;之下反遭揭穿，幸遇喜好隐身于市井的企业CEO方向阳伸出援手，却又被阿昆&ldquo;不以为耻反以为荣&rdquo;地讹诈一番。阴差阳错，方向阳来到大有村落脚，发现其发展潜力与自己的目标不谋而合，原本有眼不识泰山的李彪和阿昆顿时对&ldquo;贵人&rdquo;方向阳前倨后恭。为扩大知名度，大有村请来&ldquo;国际级导演&rdquo;刘艺风（刘桦饰）拍起了宣传片，方向阳和刘艺风之间，却因为女主角选用过气女星娜娜（童爱玲饰）还是本地村姑小雨（林苑饰）冲突日渐升级。正乱成一锅粥之际，痴迷影像的DV怪客（张达明饰）忽然出现，&ldquo;因陋就简&rdquo;的宣传片竟然大受欢迎，非但令大有村名噪一时，更使一群乌合之众得以鸡犬升天&hellip;&hellip;</p>
<p>
	<br />
	◎影片截图</p>

<p>
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120516/12/56643687201205161230581092607095917_000.jpg" /></p>
<p>
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120516/12/56643687201205161230581092607095917_002.jpg" /></p>
<p>
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120516/12/56643687201205161230581092607095917_001.jpg" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3448/飘花电影piaohua.com大有前途抢先版国语中字.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3448/飘花电影piaohua.com大有前途抢先版国语中字.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3448/飘花电影piaohua.com大有前途抢先版国语中字.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O16001310-252H.jpg{/dede:field}
