<?php
$z[0]=Array("field","生活多美好/风云人物[BD中英双字",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","生活多美好/风云人物[BD中英双字960x720高清版]迅雷下载、免费下载，生活多美好/风云人物[BD中英双字960x720高清版]Gvod高清在线播放，剧情介绍等。",73,255);
$z[1][4]['name']="description";
$z[2]=Array("field","生活多美好/风云人物[BD中英双字960x720高清版]",257,339);
$z[2][4]['name']="title";
$z[3]=Array("field","",341,380);
$z[3][4]['name']="writer";
$z[4]=Array("field","",382,421);
$z[4][4]['name']="source";
$z[5]=Array("field","2009-11-11",423,473);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",475,512);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://3e:3e@xl.eee4.com:320/[3E电影站www.eee4.cn]生活多美好BD中英双字960x720高清版.rmvb\" target=\"_blank",514,656);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MQ305450-39113.jpg",658,742);
$z[8][4]['name']="litpic";

?>