{dede:field name='keywords'}生活多美好/风云人物[BD中英双字{/dede:field}
{dede:field name='description'}生活多美好/风云人物[BD中英双字960x720高清版]迅雷下载、免费下载，生活多美好/风云人物[BD中英双字960x720高清版]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}生活多美好/风云人物[BD中英双字960x720高清版]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2009-11-11{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://3e:3e@xl.eee4.com:320/[3E电影站www.eee4.cn]生活多美好BD中英双字960x720高清版.rmvb" target="_blank{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MQ305450-39113.jpg{/dede:field}
