<?php
$z[0]=Array("field","望夫成龙国粤双语BD高清中字1280",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","望夫成龙国粤双语BD高清中字1280迅雷下载、免费下载，望夫成龙国粤双语BD高清中字1280Gvod高清在线播放，剧情介绍等。",73,227);
$z[1][4]['name']="description";
$z[2]=Array("field","望夫成龙国粤双语BD高清中字1280",229,297);
$z[2][4]['name']="title";
$z[3]=Array("field","",299,338);
$z[3][4]['name']="writer";
$z[4]=Array("field","",340,379);
$z[4][4]['name']="source";
$z[5]=Array("field","2012-02-15",381,431);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",433,470);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://dy241:xiaobajie@222.187.221.241:2021/小八戒电影xiaobajie.com望夫成龙国粤双语高清中字1280.mkv\" target=\"_blank",472,625);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MQ296240-455V.jpg",627,710);
$z[8][4]['name']="litpic";

?>