{dede:field name='keywords'}危险巨星/超级明星BD1280高清迅{/dede:field}
{dede:field name='description'}危险巨星/超级明星BD1280高清迅雷下载、免费下载，危险巨星/超级明星BD1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}危险巨星/超级明星BD1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-24{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://i.imgur.com/IcF3k.jpg" style="width: 300px; height: 237px" /></p>
<p>
	导演： Robert La Force<br />
	主演： Monthol Jira Bongkoj Khongmalai Nirut Sirijunya<br />
	类型： 惊悚上映日期： 2010年7月15日 &nbsp; 泰国<br />
	国家/地区： 泰国<br />
	类型： 惊悚<br />
	片长：90 min<br />
	对白语言： 泰语<br />
	发行公司： Sahamongkol Film International Co. Ltd.<br />
	【文件格式】x264+AC3<br />
	【视频尺寸】1280 x720<br />
	【字 &nbsp; &nbsp;幕】内嵌中文字幕<br />
	剧情：<br />
	讲述泰国明星娱乐圈里的各种囧事。看泰国明星是如何杀人掩尸~~~~~</p>
<p>
	<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120523/22/62564813201205232216413548917918250_006.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120523/22/62564813201205232216413548917918250_005.jpg" style="width: 720px; height: 405px" /><br />
	<br />
	&nbsp;</p>
<p>
	&nbsp;</p>
<p>
	【下载地址】</p>
<table bgcolor="#0099cc" border="0" cellpadding="10" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaobajie.com" target="_blank">http://www.xiaobajie.com</a></td>
		</tr>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy125:piaohua@dy125.piaohua.com:8096/飘花电影piaohua.com危险巨星BD中字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:8096/飘花电影piaohua.com危险巨星BD中字1280高清.rmvb</a></td>
		</tr>
		<tr>
		</tr>
	</tbody>
</table>
<br />{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O160P960-43134.jpg{/dede:field}
