{dede:field name='keywords'}妙想天开BD1280高清迅雷下载，免{/dede:field}
{dede:field name='description'}妙想天开BD1280高清迅雷下载、免费下载，妙想天开BD1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}妙想天开BD1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-03-02{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img165.poco.cn/mypoco/myphoto/20120302/00/62564813201203020100273107120796650_000.jpg" style="width: 400px; height: 493px" /></p>
<p>
	◎译　　名　妙想天开/巴西(台)<br />
	◎片　　名　Brazil<br />
	◎年　　代　1985<br />
	◎国　　家　英國<br />
	◎类　　别　剧情 / 科幻<br />
	◎语　　言　英语<br />
	◎IMDB评分 &nbsp;8.0<br />
	◎IMDB链接 &nbsp;<a class="faqlink" endcolor="FF6600" href="http://www.imdb.com/title/tt0088846" index="0" startcolor="0066ff" state="OFF" style="color: #0066ff">http://www.imdb.com/title/tt0088846</a><br />
	◎片　　长　 &nbsp;2:23:20.633 (h:m:s)<br />
	◎导　　演 &nbsp;Terry Gilliam 泰瑞吉廉<br />
	◎主　　演　<br />
	&nbsp; &nbsp; &nbsp;<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Jonathan Pryce &nbsp; &nbsp; &nbsp; 強納森普萊斯<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Michael Palin<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Kim Greist<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Robert De Niro &nbsp; &nbsp; &nbsp; 勞勃狄尼洛<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Katherine Helmond<br />
	<br />
	◎简　　介　<br />
	<br />
	剧情介绍：<br />
	未来，英国进入一个资讯管控的时代，每个人的一举一动都遭到监视。因为被认定为恐怖分子，巴托在家中被捕，而且逮捕过程严格按照流程。这个案件引起了档案局职员山姆?劳伊（乔纳森?普雷斯 Jonathan Pryce 饰）的兴趣。随后，他遵从母命，进入资讯管理局工作，得以进一步调查此事。<br />
	　　山姆家的空调坏了，在他求助无望之际，电气修理工达脱（罗伯特?德尼罗 Robert De Niro 饰）不请自来。他那一身武器装备，让山姆感到如临大敌。原来，达脱是资讯管理局通缉的要犯，他被指控的理由便是不遵守作业程序。随后，山姆发现资讯管理局对巴托案件存在不可告人的疑点，同事杰克（迈克尔?帕林 Michael Palin 饰）对此闪烁其词。于是，山姆决定一探究竟，其间他邂逅了梦中情人&mdash;&mdash;吉尔?莱顿（金?格雷斯特 Kim Greist 饰），两个人并肩作战，发现了一个巨大的阴谋&hellip;&hellip;　　<br />
	<br />
	◎豆瓣引用：<br />
	　　这是一部1985年的科幻电影，故事的背景不是一望无垠的未来，而是20世纪的某一圣诞节。导演Terry Gilliamd的高明之处就在于，可以在时间负半轴的一个点上创造出了讽喻双关的未来世界。<br />
	　　<br />
	　　【关键词一：脏科幻】<br />
	　　<br />
	　　对科幻故事比较流行的分类是硬科幻和软科幻。《妙想天开》明显属于后者，因为它更关注的是社会体制、心理哲学方面的问题。<br />
	　　<br />
	　　<br />
	　　我则喜欢把科幻电影分为：净科幻和脏科幻（瞎取的名字，请意会=.=!)。<br />
	　　<br />
	　　<br />
	　　净科幻，顾名思义，很无菌的样子。&mdash;&mdash;以黑白强烈的对比度和锃亮锃亮的金属质感来表现未来的冰冷和漠然，例子很多，如：立方体系列、黑客帝国、以及n多太空片。<br />
	　　<br />
	　　<br />
	　　另一类是脏科幻，David Cronenberg是这流派的杰出代表。此类科幻片没有精雕细琢的唯美情结，而是以近似B级片的邋遢和血腥来展示未来世界的模型。<br />
	　　<br />
	　　净科幻所探讨的通常是人类伴随着科技发展而产生的生存困境和精神危机；而脏科幻更乐于借一些超现实主义的大胆想象来讽喻当下的体制弊病和意识形态残障。<br />
	　　<br />
	　　<br />
	　　《妙想天开》是一部典型的脏科幻。在影片中，你看不到精密的仪器、看不到包装得比外科医生还严实的科学家、看不到飞来飞去的车子&hellip;&hellip;《妙想天开》的布景老得掉牙，全然是上世纪初老式公寓的玩意儿：老式的铁拉门电梯、老式电话改装的通讯设备、老式打字机加玻璃组合而成的电脑，连主人公Sam的妈妈拉皮用的铁夹也很老式&hellip;&hellip;Terry乐此不彼地设置着这些新旧组合，调侃着自动化的愚昧，构造出一个带着浓厚的20世纪风情的科幻世界。<br />
	　　<br />
	　　【关键词二：反乌托邦】<br />
	　　<br />
	　　<br />
	　　都说《妙想天开》是一部反乌托邦的电影。乌托邦本就是一个理想主义的空物，所以把之分解为反集权、反官僚、反教条、反主流文化更具现实意义。<br />
	　　<br />
	　　<br />
	　　<br />
	　　<br />
	　　Terry幽默辩证地看待政府与恐怖分子的关系。&mdash;&mdash;大块瓷砖下的掩盖下的一团团皮管，就宛如城市在国家臃肿的体制下扭结不畅的肠道，而愚蠢低效的官方修理员除了把这些搞得更糟便没有更大的作为；相反，Robert De Niro 扮演的恐怖分子倒是快刀斩乱麻，成为了肮脏城市的清道夫。人们对恐怖袭击亦是习以为常，只需一个华丽屏风遮挡便可在硝烟滚滚的餐馆继续享用&ldquo;美餐&rdquo;；倒是政府的反恐精英们更让人毛骨悚然，戴着伪善的笑脸面具，拿着残酷的刑具，清理掉一个个揭体制伤疤的&ldquo;恐怖分子&rdquo;。<br />
	　　<br />
	　　【关键词三：梦中人】<br />
	　　<br />
	　　《妙想天开》的一条重要线索是Sam的梦。我还真佩服他每次睡着都能接着梦。现实中略显瘦弱的小小公务员，却做着一个英雄救美的童话梦。<br />
	　　<br />
	　　<br />
	　　<br />
	　　看着心爱的梦中情人关在笼子里如断线的风筝般飘走，他奋力追赶，并最终战胜了强大的面具男；当他摘下对手的面具时，心一抽，竟是自己。这是全片最意味深长的镜头。&mdash;&mdash;在病态的体制下，反抗者最终会发现自己其实也是体制中的一个组成部分；而镇压者或许也会觉悟，自己用暴政所巩固的是一条灭亡之路。<br />
	　　<br />
	　　【关键词四：预 言】<br />
	　　<br />
	　　<br />
	　　Terry在片尾献上了一具精美的粉色的棺材，这是他敬献给20世纪的豪华礼盒。无底的坠落仿佛一个黑色的预言。<br />
	　　<br />
	　　Jack看着被整成植物人的Sam说：他走了。Sam的确走了，在自己的乌托邦世界中与恋人幸福生活；但是Terry所讽刺的病态体制还没走，它分解成一块块的小碎片，黏附在世界各地，轻松地跨进了21世纪。<br />
	　　<br />
	　　有的科幻片会刻意地拉开审美距离，Terry的《妙想天开》却如影随形，触手可及。<br />
	　　<br />
	　　<br />
	　　有的科幻片预言诞生，有的科幻片预言毁灭，Terry则预言一个持续不醒的噩梦，没有什么比这更绝望&hellip;&hellip;</p>
<p>
	<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120302/00/62564813201203020046484074933859374_006.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120302/00/62564813201203020046484074933859374_005.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120302/00/62564813201203020046484074933859374_004.jpg" style="width: 720px; height: 405px" /><br />
	&nbsp;</p>
[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
<tbody>
<tr>
<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
<a href="
ftp://dy125:piaohua@dy125.piaohua.com:7678/飘花电影piaohua.com妙想天开BD中英双字1280高清.rmvb">
ftp://dy125:piaohua@dy125.piaohua.com:7678/飘花电影piaohua.com妙想天开BD中英双字1280高清.rmvb</a></td>
</tr>
</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15925V0-15151.jpg{/dede:field}
