{dede:field name='keywords'}荒野生存迅雷下载，免费下载，Gv{/dede:field}
{dede:field name='description'}荒野生存迅雷下载、免费下载，荒野生存Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}荒野生存{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2008-02-11{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://eee4.com:4421@vip8.eee4.com:4421/荒野生存DVD/[3E迅雷电影站www.eee4.com]荒野生存cd1.rmvb" target="_blank{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MPU25P-52408.jpg{/dede:field}
