<?php
$z[0]=Array("field","荒野生存迅雷下载，免费下载，Gv",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","荒野生存迅雷下载、免费下载，荒野生存Gvod高清在线播放，剧情介绍等。",73,183);
$z[1][4]['name']="description";
$z[2]=Array("field","荒野生存",185,231);
$z[2][4]['name']="title";
$z[3]=Array("field","",233,272);
$z[3][4]['name']="writer";
$z[4]=Array("field","",274,313);
$z[4][4]['name']="source";
$z[5]=Array("field","2008-02-11",315,365);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",367,404);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://eee4.com:4421@vip8.eee4.com:4421/荒野生存DVD/[3E迅雷电影站www.eee4.com]荒野生存cd1.rmvb\" target=\"_blank",406,554);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MPU25P-52408.jpg",556,638);
$z[8][4]['name']="litpic";

?>