{dede:field name='keywords'}丁丁历险记DVD中字/中英双字动画{/dede:field}
{dede:field name='description'}丁丁历险记DVD中字/中英双字动画/家庭/冒险/悬疑/动作2011迅雷下载、免费下载，丁丁历险记DVD中字/中英双字动画/家庭/冒险/悬疑/动作2011Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}丁丁历险记DVD中字/中英双字动画/家庭/冒险/悬疑/动作2011{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-02-22{/dede:field}
{dede:field name='body'}<p>
	&nbsp;<img src="http://img.funshion.com/attachment/new_images/2011/07-05/25353441_1309854630_754.jpg" /></p>


<p>
	<img src="http://img.funshion.com/attachment/new_images/2011/07-05/25353441_1309851122_228.jpg" /></p>
<p>
	◎译　　名　丁丁历险记/丁丁历险记：独角兽号的秘密<br />
	◎片　　名　The Adventures of Tintin<br />
	◎年　　代　2011<br />
	◎国　　家　美国/新西兰<br />
	◎类　　别　动画/冒险/家庭/悬疑<br />
	◎语　　言　英语<br />
	◎字　　幕　中英双字<br />
	◎IMDB评分 7.8/10 from 6,461 users<br />
	◎文件格式　TS-RMVB<br />
	◎视频尺寸　720 x 304<br />
	◎文件大小　1CD 451MB<br />
	◎片　　长　107 min<br />
	◎导　　演　史蒂文&middot;斯皮尔伯格&nbsp;&nbsp; Steven Spielberg<br />
	◎主　　演　杰米&middot;贝尔 Jamie Bell&nbsp; ....Tintin<br />
	安迪&middot;瑟金斯 Andy Serkis&nbsp; ....Captain Haddock<br />
	西蒙&middot;佩吉 Simon Pegg&nbsp; ....Inspector Thompson<br />
	尼克&middot;弗罗斯特 Nick Frost&nbsp; ....Thomson<br />
	丹尼尔&middot;克雷格 Daniel Craig&nbsp; ....Red Rackham<br />
	托比&middot;琼斯 Toby Jones&nbsp; ....Silk<br />
	加利&middot;艾尔维斯 Cary Elwes&nbsp; ....Pilot<br />
	丹尼尔&middot;梅斯 Daniel Mays&nbsp; ....Allan<br />
	托尼&middot;库兰 Tony Curran&nbsp; ....Lt. Delcourt<br />
	麦肯锡&middot;克鲁克 Mackenzie Crook&nbsp; ....Ernie<br />
	Sebastian Roch&eacute;&nbsp; ....Pedro<br />
	马克&middot;伊瓦涅 Mark Ivanir&nbsp; ....Afgar Outpost Soldier<br />
	菲利普&middot;莱斯 Phillip Rhys&nbsp; ....Co-pilot<br />
	加德&middot;艾尔马莱 Gad Elmaleh&nbsp; ....Ben Salaad<br />
	Sana Etoile&nbsp; ....Moroccan Reporter<br />
	Jacquie Barnbrook&nbsp; ....Lady in the Phonebox / Old Lady<br />
	Sonje Fortag&nbsp; ....Mrs. Finch<br />
	Enn Reitel&nbsp; ....Mr. Crabtree<br />
	乔&middot;史达 Joe Starr&nbsp; ....Barnaby<br />
	Ron Bottitta&nbsp; ....Unicorn Lookout<br />
	Kim Stengel&nbsp; ....Bianca Castafiore<br />
	Ian Bonar&nbsp; ....Market Artist<br />
	Mohamed Ibrahim Elkest&nbsp; ....Soldier #4<br />
	Martin D. Dew&nbsp; ....Park Stroller (uncredited)<br />
	Alex Hyde-White&nbsp; ....Stallholder (uncredited)<br />
	Sophia Elisabeth&nbsp; ....Woman at the Opera (uncredited)</p>
<p>
	<br />
	◎简　　介</p>
<p>
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 《丁丁历险记：独角兽的秘密》是《海盗失宝》的姐妹篇前篇。讲述的是一天丁丁买了一只古老的船模送给船长作为礼物，于是又一次惊险的历险开始了。从一本古老的日记本上他们知道了这艘古老船模的历史。独角兽号隐藏着一个海盗和财宝的故事。在他们的朋友杜邦侦探的帮助下，丁丁，白雪和船长开始去揭开独角兽号的秘密。尽管困难重重，丁丁还是成功了，并出发去寻找红色拉克姆的财宝。<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 故事跟随着一个充满好奇心的年轻记者丁丁（杰米&middot;贝尔 饰）和他忠心无比的狗狗白雪，他们发现一艘藏有惊爆秘密的模型船，于是丁丁受到这个流传几世纪的秘密吸引，并引起残暴恶棍萨卡林（丹尼尔&middot;克雷格 饰）的注意，因为萨卡林相信丁丁偷了跟红色拉克姆有关的无价宝藏，不过由于狗狗白雪、坏脾气的航海家阿道克船长（安迪&middot;瑟金斯 饰）及笨手笨脚的侦探搭挡杜庞与杜邦（西蒙&middot;佩吉和尼&middot;克弗斯特 饰）的帮助，丁丁将会游历半个地球，智取并赶过他的敌人，热切地寻找船舰独角兽号的最后落脚处，因为那正关键着一艘失事船的庞大财富&hellip;&hellip;以及一则古老的诅咒。</p>
<p>
	◎电影截图</p>
<p>
	&nbsp;<img src="http://img.funshion.com/attachment/new_images/2011/09-29/13099337_1317287672_114.jpg" />、</p>
<p>
	<img src="http://img.funshion.com/attachment/new_images/2011/09-29/13099337_1317287666_315.jpg" /></p>
<p>
	&nbsp;<img src="http://img.funshion.com/attachment/new_images/2011/09-29/13099337_1317287669_709.jpg" />、</p>
<p>
	&nbsp;<img src="http://img.funshion.com/attachment/new_images/2011/09-29/13099337_1317287663_130.jpg" /></p>
<p>
	<img border="0" src="http://img2081.poco.cn/mypoco/myphoto/20120221/17/56643687201202211758222647433530545_003.jpg" /><br />
	<br />
	<img border="0" src="http://img2081.poco.cn/mypoco/myphoto/20120221/17/56643687201202211758222647433530545_001.jpg" /><br />
	<br />
	<img border="0" src="http://img2081.poco.cn/mypoco/myphoto/20120221/17/56643687201202211758222647433530545_000.jpg" /><br />
	<br />
	<img border="0" src="http://img2081.poco.cn/mypoco/myphoto/20120221/17/56643687201202211758222647433530545_002.jpg" /><br />
	<br />
	&nbsp;</p>

<p>
	[下载地址]： <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" /></p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2173/飘花电影piaohua.com丁丁历险记抢先英语中字.rmvb ">ftp://dy44:piaohua@dy44.piaohua.com:2173/飘花电影piaohua.com丁丁历险记抢先英语中字.rmvb </a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2326/飘花电影piaohua.com丁丁历险记TC中字.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2326/飘花电影piaohua.com丁丁历险记TC中字.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2864/飘花电影piaohua.com丁丁历险记DVD中字.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2864/飘花电影piaohua.com丁丁历险记DVD中字.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1B3F40-23P0.jpg{/dede:field}
