<?php
$z[0]=Array("field","异形2/异形续集[BD中英双字1024x",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","异形2/异形续集[BD中英双字1024x576高清版]迅雷下载、免费下载，异形2/异形续集[BD中英双字1024x576高清版]Gvod高清在线播放，剧情介绍等。",73,247);
$z[1][4]['name']="description";
$z[2]=Array("field","异形2/异形续集[BD中英双字1024x576高清版]",249,327);
$z[2][4]['name']="title";
$z[3]=Array("field","",329,368);
$z[3][4]['name']="writer";
$z[4]=Array("field","",370,409);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-03-24",411,461);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",463,500);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://3e:3e@www5.eee4.cc:1439/【3E电影院www.eee4.cc】异形2[BD中英双字1024x576高清版].rmvb\" target=\"_blank",502,646);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MQ33Z60-55433.jpg",648,731);
$z[8][4]['name']="litpic";

?>