{dede:field name='keywords'}南方传奇BD中英双字1024/1280高{/dede:field}
{dede:field name='description'}南方传奇BD中英双字1024/1280高清迅雷下载、免费下载，南方传奇BD中英双字1024/1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}南方传奇BD中英双字1024/1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-01-05{/dede:field}
{dede:field name='body'}<p>
	<img src="http://pic.piaohua.com/0701pic/allimg/080718/1559230.jpg" /></p>
<p>
	<img alt="" onload="attachimg(this, 'load')" src="http://img.album.pchome.net/54/68/25/39/4134815eb4ca64a18269954f8af5bb97.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 776px; border-top: 0px solid; border-right: 0px solid" /></p>
<p>
	【译　　名】《南方传奇》06巨石强森经典科幻喜剧大片DVD中英双字<br />
	【片　　名】Southland Tales<br />
	【年　　代】2006<br />
	【国　　家】德国/美国/法国<br />
	【类　　别】喜剧/剧情/科幻/惊悚<br />
	【语　　言】英语<br />
	【字　　幕】中英文<br />
	【IMDB评分】6.6/10 (2,656 votes)<br />
	【文件格式】DVDrip-RMVB<br />
	【视频尺寸】800 x 336<br />
	【电影整理】3E迅雷电影下载站(www.eee4.com)<br />
	【文件大小】1CD 813MB<br />
	【片　　长】02:24:32<br />
	【导　　演】理查德&middot;凯利 Richard Kelly<br />
	【主　　演】巨石 The Rock .....Boxer Santaros/Jericho Kane<br />
	　　　　　　西恩&middot;威廉&middot;斯科特 Seann William Scott .....<br />
	　　　　　　莎拉&middot;米歇尔&middot;盖拉 Sarah Michelle Gellar .....<br />
	　　　　　　曼迪&middot;摩尔 Mandy Moore<br />
	　　　　　　米兰达&middot;理查森 Miranda Richardson<br />
	　　　　　　凯文&middot;史密斯 Kevin Smith .....Simon Thiery<br />
	　　　　　　白灵 Ling Bai .....(as Bai Ling)<br />
	　　　　　　詹尼安&middot;吉劳法罗 Janeane Garofalo .....General Teena MacArthur<br />
	　　　　　　迈克尔&middot;吉尔顿 Michael Gilden .....Mini UPU<br />
	　　　　　　贝丝&middot;格兰特 Beth Grant<br />
	　　　　　　克里斯多夫&middot;兰伯特 Christopher Lambert .....Walter Mung<br />
	　　　　　　艾米&middot;波哈尔 Amy Poehler<br />
	　　　　　　华莱士&middot;肖恩 Wallace Shawn .....Baron Von Westphalen<br />
	　　　　　　贾斯丁&middot;汀波莱克 Justin Timberlake</p>
<p>
	【简　　介】</p>
<p>
	　　故事发生在 2008 年 7 月美国独立日前夕的洛衫矶。影片的男主人公鲍克瑟&middot;桑塔罗斯是一位事业成功的动作片明星，身体壮硕的他却患有失忆症。女主人公克里斯塔&middot;诺是因出演色情电影而小有名气的艳星，正在开始尝试制作自己的电视节目。两人的生活由于偶然出现交点，随着故事的展开，负责荷尔摩沙海滩治安的警官罗纳德成为执掌惊天阴谋的关键人物。</p>
<p>
	　　随着一次预谋已久的绑架案突然失控，越来越多的人被牵扯进诡秘异常的阴谋，冲突矛盾逐渐激化，整个世界近乎疯狂，种族暴乱无可避免。在喧闹的歌舞和梦幻般场景的映衬中，惊悚的触角开始四处蔓延&hellip;&hellip;3E迅雷<a href="/" target="_blank">电影下载</a>站</p>

<p>
	【电影截图】：<br />
	电影来源：www.eee4.com<br />
	<img src="http://pic.piaohua.com/0701pic/allimg/080718/1559231.jpg" />&nbsp;<br />
	<img src="http://pic.piaohua.com/0701pic/allimg/080718/1559232.jpg" /></p>
	06巨石强森经典科幻喜剧大片《南方传奇》DVD中英双字 下载地址：<img border="0" src="/templets/img/down.jpg" /></p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<anchor></anchor><a href="ftp://eee4.com:8113@vip20.eee4.com:8113/[3E迅雷电影站www.eee4.com]南方传奇DVD中英双字.rmvb" target="_blank">ftp://eee4.com:8113@vip20.eee4.com:8113/[3E迅雷电影站www.eee4.com]南方传奇DVD中英双字.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<anchor></anchor><a href="ftp://dy44:piaohua@dy44.piaohua.com:2527/飘花电影piaohua.com南方传奇BD中英双字1024高清.rmvb ">ftp://dy44:piaohua@dy44.piaohua.com:2527/飘花电影piaohua.com南方传奇BD中英双字1024高清.rmvb </a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<anchor></anchor><a href="ftp://dy44:piaohua@dy44.piaohua.com:2527/飘花电影piaohua.com南方传奇BD中英双字1280高清.rmvb ">ftp://dy44:piaohua@dy44.piaohua.com:2527/飘花电影piaohua.com南方传奇BD中英双字1280高清.rmvb </a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15Z1b0-49457.jpg{/dede:field}
