{dede:field name='keywords'}恋爱假期/休闲时光/缘分精华游/{/dede:field}
{dede:field name='description'}恋爱假期/休闲时光/缘分精华游/恋爱没有假期BD中英双字1024/1280迅雷下载、免费下载，恋爱假期/休闲时光/缘分精华游/恋爱没有假期BD中英双字1024/1280Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}恋爱假期/休闲时光/缘分精华游/恋爱没有假期BD中英双字1024/1280{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-02-15{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://3e:3e@d8.3edyy.com:174/【3E电影院www.eee4.cc】恋爱假期BD中英双字1024x576高清版.rmvb" target="_blank{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MODO10-25a1.jpg{/dede:field}
