{dede:field name='keywords'}黑马王子HD高清1024*576国语中字{/dede:field}
{dede:field name='description'}黑马王子HD高清1024*576国语中字迅雷下载、免费下载，黑马王子HD高清1024*576国语中字Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}黑马王子HD高清1024*576国语中字{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-08-21{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="/uploads/allimg/c120525/133O034W4F-61510.jpg" /></p>
<p>
	中文名： 黑马王子<br />
	英文名： Prince Charming<br />
	导&nbsp;&nbsp; 演： 王晶<br />
	主&nbsp;&nbsp; 演： 李嘉欣 刘德华 张敏<br />
	类&nbsp;&nbsp; 型： 爱情<br />
	地&nbsp;&nbsp; 区： 港台<br />
	发&nbsp;&nbsp; 行： 1999<br />
	规&nbsp;&nbsp; 格： 1024x576</p>
<p>
	<br />
	故事讲述上海企业家薄定国的女儿薄冰随父到港，寻找十几年前在港失踪的母亲，她认识了绰号&ldquo;黑马王子&quot;的邮递员华弟，华弟帮她寻。。。。</p>
<p>
	<img alt="" src="/uploads/allimg/c120525/133O034X5F-K928.jpg" /><img alt="" src="/uploads/allimg/c120525/133O034Y320-Y520.jpg" /><img alt="" src="/uploads/allimg/c120525/133O034Z10-931C.jpg" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="/uploads/allimg/c120524/133N2Z4FF-102231.jpg" />&nbsp;&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="word-break: break-all; line-height: 18px" width="100%">
				ftp://dy125:piaohua@dy125.piaohua.com:2036/飘花电影piaohua.com黑马王子HD高清1024分辨率.rmvb </td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O034ZW0-103S9.jpg{/dede:field}
