{dede:field name='keywords'}西蒙妮/虚拟情人BD1280高清中英{/dede:field}
{dede:field name='description'}西蒙妮/虚拟情人BD1280高清中英双字迅雷下载、免费下载，西蒙妮/虚拟情人BD1280高清中英双字Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}西蒙妮/虚拟情人BD1280高清中英双字{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-07{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120506/00/17870980201205060019081187476919495_009.jpg" /></p>
<p>
	◆ 片 &nbsp;名：西蒙妮 / 英文：S1m0ne / 港译：虚拟索女郎<br />
	◆ 导 &nbsp;演：安德鲁&middot;尼库尔（Andrew Niccol）<br />
	◆ 编 &nbsp;剧：安德鲁&middot;尼库尔（Andrew Niccol）<br />
	◆ 主 &nbsp;演：阿尔&middot;帕西诺（Al Pacino） 瑞切尔&middot;罗伯兹（Rachel Roberts）<br />
	维诺娜&middot;赖德（Winona Ryder） 凯瑟琳&middot;基纳（Catherine Keener）<br />
	本杰明&middot;索尔兹伯里（Benjamin Salisbury） 杰&middot;摩尔（Jay Mohr）<br />
	艾万&middot;蕾切尔&middot;伍德（Evan Rachel Wood）<br />
	◆ 类 &nbsp;型：喜剧（Comedy） 科幻（Sci-Fi） 剧情（Drama）<br />
	◆ 国家地区：美国 &nbsp;<br />
	◆ 语 &nbsp;言：英语<br />
	◆ 发行公司：新线（New Line） &nbsp;<br />
	◆ 首映日期：2002年8月23日<br />
	◆ 制作公司：新线（New Line） &nbsp;<br />
	◆ 首映票房：$3,813,463.00 (单位：美元)<br />
	◆ MPAA定级：PG-13 级<br />
	◆ 全美票房：$9,688,676.00 (单位：美元)<br />
	<br />
	剧情介绍：<br />
	&nbsp; &nbsp; &nbsp; &nbsp;维克多（阿尔帕西诺）是一位过气的好莱坞导演，虽然他执导的影片曾经获过奥斯卡奖的提名，但现在他可是倒霉的可以，先是大牌女明星尼科安德丝一气之下退出他的新戏《日出日落》的演出，接着又被前妻&mdash;&mdash;电影公司总裁伊莲克莉丝汀炒了鱿鱼，可就在这时，计算机天才汉克艾列诺出现了，他送给维克多一套可以设计出完美而且高度逼真的三维动画虚拟人物的软件。借助这一程序，维克多创造出了一个&ldquo;无可挑剔的女人&rdquo;。因为程序名称叫&ldquo;虚拟一号&rdquo;(Simulate One)，于是他便用其缩写&ldquo;Simone&rdquo;来给自己的女演员命名。<br />
	&nbsp; &nbsp; &nbsp; 维克多的电影顺利地完成了，并获得了巨大的成功。&ldquo;西蒙妮&rdquo;一夜之间成为了大众偶像，拥有了无数疯狂崇拜者。而维克多也再次品尝到了成功带来的的喜悦，全球最受欢迎的明星就被他控制在股掌之间。但是事情可能没有想象中的简单......</p>
<p>
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120507/22/17870980201205072224421282121355673_023.jpg" /></p>
<p>
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120507/22/17870980201205072224421282121355673_022.jpg" /></p>
<p>
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120507/22/17870980201205072224421282121355673_018.jpg" style="width: 640px; height: 360px" /></p>

<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.net" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy241:piaohua@117.41.229.29:2006/飘花电影piaohua.com西蒙妮BD1280高清中英双字.rmvb">ftp://dy241:piaohua@117.41.229.29:2006/飘花电影piaohua.com西蒙妮BD1280高清中英双字.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15J42Z-49212.jpg{/dede:field}
