{dede:field name='keywords'}新海神号遇险记迅雷下载，免费下{/dede:field}
{dede:field name='description'}新海神号遇险记迅雷下载、免费下载，新海神号遇险记Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}新海神号遇险记{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2006-08-02{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://eee4.com:eee4@xl3.eee4.com:8448/海神号/[3E迅雷电影站www.eee4.com]海神号DVD完美中字.rmvb" target=_blank>ftftp://eee4.com:eee4@xl3.eee4.com:8448/海神号/[3E迅雷电影站www.eee4.com]海神号DVD完美中字.rmvb</A></TD></TR></TBODY></TABLE></div><ul class="mmlist{/dede:field}
{dede:field name='litpic'}http://pic.piaohua.com/0701pic/allimg/080117/0352076_lit.jpgalt=新海神号遇险记width=120height=150border=0{/dede:field}
