{dede:field name='keywords'}完美的爱DVD国语中字中国大陆剧{/dede:field}
{dede:field name='description'}完美的爱DVD国语中字中国大陆剧情迅雷下载、免费下载，完美的爱DVD国语中字中国大陆剧情Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}完美的爱DVD国语中字中国大陆剧情{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-24{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="/uploads/allimg/c120525/133O0VPK0-11200.jpg" /></p>
<p>
	<img alt="" src="/uploads/allimg/c120525/133O0VR150-29496.jpg" /></p>
<p>
	导演: 王立新<br />
	编剧: 王立新<br />
	主演: 徐啸力 / 杨杏<br />
	制片国家/地区: 中国大陆<br />
	语言: 汉语普通话<br />
	上映日期: 2011.06.12<br />
	又名: Yellow Rose</p>
<p>
	电影简介：</p>
<p>
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 出租车司机马龙来自偏远山区的民族家庭，男女青年在婚前一定要保持绝对的纯真是他们的民族传统。当他和美丽善良的乡村姑娘小芳相爱时，因车祸眼角膜被火灼伤面临终身失明的危险，为了能使马龙早日康复，小芳牺牲贞洁为马龙赢得了延缓失明的经济来源，使马龙双眼康复，马龙面对民族传统的观念和相爱的小芳陷入深深的矛盾和痛苦中。</p>
<p>
	一部探讨贞洁观与爱情题材的电影《完美的爱》由王立新执导，《红樱桃》、《天安门》主演徐啸力、新人杨杏出演主演，该片要探讨贞洁观与现代爱情之间的冲突。导演王立新透露，该片完成后将参加国际电影节，他还劝诫那些沉浸在爱河中的男女青年，以及幸福的年轻家庭不要观看这部电影。讲述了一对情侣之间的爱情故事，最终男主角还为爱殉情。男女主角在片中有不少激吻镜头，而女一号还裸背出镜，成为一大看点。</p>
<p>
	<br />
	电影花絮：<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 徐啸力拍摄此片时数次被自己扮演的角色感动落泪。</p>
<p>
	<br />
	电影截图：</p>
<p>
	<img src="/uploads/allimg/c120525/133O0VRR0-3E40.jpg" /></p>
<p>
	<img src="/uploads/allimg/c120525/133O0VS450-43553.jpg" /></p>
<p>
	<img src="/uploads/allimg/c120525/133O0VSZ-55145.jpg" /></p>
<p>
	<img border="0" src="/uploads/allimg/c120525/133O0VT220-D291.jpg" /></p>
<p>
	<img border="0" src="/uploads/allimg/c120525/133O0VTT0-I337.jpg" /></p>
<p>
	<img border="0" src="/uploads/allimg/c120525/133O0VU460-W147.jpg" /></p>
<p>
	<img border="0" src="/uploads/allimg/c120525/133O0VV110-9DP.jpg" /></p>
<p>
	[下载地址]： &nbsp;<img border="0" src="/uploads/allimg/c120525/133O0T31310-42214.jpg" /></p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:1465/飘花电影piaohua.com完美的爱国语中英双字A.mp4</td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:1465/飘花电影piaohua.com完美的爱国语中英双字B.mp4</td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:3485/飘花电影piaohua.com完美的爱DVD国语中字.rmvb</td>
		</tr>
	</tbody>
</table>
<p>
	&nbsp;</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O0VPK0-11200.jpg{/dede:field}
