{dede:field name='keywords'}千人斩,国语无字迅雷下载，免费{/dede:field}
{dede:field name='description'}千人斩 国语无字迅雷下载、免费下载，千人斩 国语无字Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}千人斩 国语无字{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-08-13{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="/uploads/allimg/c120525/133O0350aF-1DJ.jpg" /></p>
<p>
	◎译　　名　千人斩<br />
	◎片　　名　The Beheaded 1000<br />
	◎年　　代　1993<br />
	◎国　　家　中国<br />
	◎类　　别　动作<br />
	◎语　　言　普通话<br />
	◎字　　幕　英文<br />
	◎IMDB评分 6.3/10 (34 votes)<br />
	◎IMDB链接 http://www.imdb.com/title/tt0121103<br />
	◎文件格式　XviD + MP3<br />
	◎视频尺寸　576*304<br />
	◎文件大小　1CD 49 x 15MB<br />
	◎片　　长　101m 36s<br />
	◎导　　演　丁善玺 Shan-si Ting<br />
	　　　　　　王羽 Yu Wang<br />
	◎主　　演　Xiao-Lao Gian<br />
	　　　　　　Wo Lei<br />
	　　　　　　王羽 Yu Wang<br />
	　　　　　　王祖贤 Joey Wong .....Blood Lotus<br />
	◎简　　介　<br />
	刽子手袁德泰, 金刀斩囚九百九十九人, 远近悍匪, 闻之丧胆. 至是年, 告老歇业, 旧居为小酒店, 卖酒营生, 开张后血灾连连, 客不上门,德泰夫妇与女巧银, 徙二五, 日坐愁境. 某夕, 有八客治席, 德泰待如上, 客俱恶形恶状,颈部各见刀痕, 德泰惊, 来者江南大盗鬼八仙, 八人首级皆德泰一刀下矣!客来索命, 器械尽出, 危机四伏, 袁妻死, 二五携巧银避祸, 德泰磨刀应战, 力拒八鬼. 月黑风高, 众人行刑, 俨如阴界法场. 德泰自府必死. 荐二五充刽子手, 以取其首级, 二五提刀而栗. 泪下如雨, 举刀千斤, 适狱帝判官钟馗嫁妹出阁,知德泰有难, 乃告以『人刀合一』之道.....</p>
<p>
	&nbsp;<img alt="" src="/uploads/allimg/c120525/133O03510920-24157.jpg" /><img alt="" src="/uploads/allimg/c120525/133O03511620-3P31.jpg" /><img alt="" src="/uploads/allimg/c120525/133O03512230-49504.jpg" /></p>

<p>
	[千人斩下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="/uploads/allimg/c120524/133N2Z4FF-102231.jpg" />&nbsp;&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="word-break: break-all; line-height: 18px" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:1280/飘花电影下载站www.xiaozhizhu.net千人斩[国语无字].rmvb </td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O03512T0-54K7.jpg{/dede:field}
