{dede:field name='keywords'}长大后/湖景宅/中坑同学会BD1280{/dede:field}
{dede:field name='description'}长大后/湖景宅/中坑同学会BD1280高清迅雷下载、免费下载，长大后/湖景宅/中坑同学会BD1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}长大后/湖景宅/中坑同学会BD1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-13{/dede:field}
{dede:field name='body'}<p>
	<img alt="" border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://cdn3a.dvdempire.org/products/86/1547886h.jpg');" src="http://cdn3a.dvdempire.org/products/86/1547886h.jpg" /><br />
	<br />
	◎译　　名　长大后/中坑同学会(港)/亚当等大人(台)/湖景宅<br />
	◎片　　名　Grown Ups<br />
	◎年　　代　2010<br />
	◎国　　家　美国<br />
	◎类　　别　喜剧<br />
	◎语　　言　英语<br />
	◎字　　幕　中英双字<br />
	◎IMDB评分 5.8/10 (15,034 votes)<br />
	◎文件格式　BD-RMVB<br />
	◎视频尺寸　1024 x 560<br />
	◎文件大小　1CD<br />
	◎片　　长　102 Mins<br />
	◎导　　演　丹尼斯&middot;杜根 Dennis Dugan<br />
	◎主　　演　亚当&middot;桑德勒 Adam Sandler&nbsp; ....Lenny Feder<br />
	　　　　　　凯文&middot;詹姆斯 Kevin James&nbsp; ....Eric Lamonsoff<br />
	　　　　　　克里斯&middot;洛克 Chris Rock&nbsp; ....Kurt McKenzie<br />
	　　　　　　大卫&middot;斯佩德 David Spade&nbsp; ....Marcus Higgins<br />
	　　　　　　罗伯&middot;施奈德 Rob Schneider&nbsp; ....Rob Hilliard<br />
	　　　　　　萨尔玛&middot;海耶克 Salma Hayek&nbsp; ....Roxanne Chase-Feder (as Salma Hayek Pinault)<br />
	　　　　　　玛丽亚&middot;贝罗 Maria Bello&nbsp; ....Sally Lamonsoff<br />
	　　　　　　玛娅&middot;鲁道夫 Maya Rudolph&nbsp; ....Deanne McKenzie<br />
	　　　　　　乔伊丝&middot;冯&middot;派特 Joyce Van Patten&nbsp; ....Gloria<br />
	　　　　　　Ebony Jo-Ann&nbsp; ....Mama Ronzoni<br />
	　　　　　　Di Quon&nbsp; ....Rita<br />
	　　　　　　史蒂夫&middot;布西密 Steve Buscemi&nbsp; ....Wiley<br />
	　　　　　　Colin Quinn&nbsp; ....Dickie Bailey<br />
	　　　　　　蒂姆&middot;麦道斯 Tim Meadows&nbsp; ....Malcolm<br />
	　　　　　　玛迪森&middot;蕾利 Madison Riley&nbsp; ....Jasmine Hilliard<br />
	　　　　　　杰米&middot;钟 Jamie Chung&nbsp; ....Amber Hilliard<br />
	　　　　　　Ashley Loren&nbsp; ....Bridget Hilliard<br />
	　　　　　　Jake Goldberg&nbsp; ....Greg Feder<br />
	　　　　　　卡梅隆&middot;伯艾斯 Cameron Boyce&nbsp; ....Keithie Feder<br />
	　　　　　　Alexys Nycole Sanchez&nbsp; ....Becky Feder<br />
	　　　　　　Ada-nicole Sanger&nbsp; ....Donna Lamonsoff<br />
	　　　　　　Frank Gingerich&nbsp; ....Bean Lamonsoff<br />
	　　　　　　Morgan Gingerich&nbsp; ....Bean Lamonsoff<br />
	　　　　　　Nadji Jeter&nbsp; ....Andre McKenzie<br />
	　　　　　　琪娜&middot;安妮&middot;麦克兰 China Anne McClain&nbsp; ....Charlotte McKenzie<br />
	　　　　　　Dan Patrick&nbsp; ....Norby the Ride Guy<br />
	　　　　　　Tim Herlihy&nbsp; ....Pastor<br />
	　　　　　　布莱克&middot;克拉克 Blake Clark&nbsp; ....Bobby &#39;Buzzer&#39; Ferdinando<br />
	　　　　　　诺姆&middot;麦克唐纳德 Norm Macdonald&nbsp; ....Geezer<br />
	　　　　　　Jonathan Loughran&nbsp; ....Robideaux<br />
	　　　　　　Kevin Grady&nbsp; ....Muzby<br />
	　　　　　　Richie Minervini&nbsp; ....Tardio<br />
	　　　　　　杰姬&middot;桑德勒 Jackie Sandler&nbsp; ....Tardio&#39;s Wife<br />
	　　　　　　Sadie Sandler&nbsp; ....Tardio&#39;s Daughter<br />
	　　　　　　Sunny Sandler&nbsp; ....Tardio&#39;s Daughter<br />
	　　　　　　丹尼斯&middot;杜根 Dennis Dugan&nbsp; ....Referee<br />
	　　　　　　Lisa M. Francis&nbsp; ....Bailey&#39;s Wife<br />
	　　　　　　Berkeley Holman&nbsp; ....Bailey&#39;s Son<br />
	<br />
	◎简　　介　<br />
	<br />
	　　高中毕业三十年之后的这个国家独立日假日，五位曾经的好朋友终于找到机会重新聚到了一起。<br />
	<br />
	　　30年前，一个篮球队中的五个队员兼好朋友拿到了篮球赛的冠军。30年后的一天，他们当时的教练过世，这五个当年的好朋友重新聚到了一起，在国家独立日的假日里和自己的家人坐到了一起，共叙友情。他们在一栋别墅里消遣、玩乐&mdash;&mdash;当然也闹出了不少笑话。<br />
	<br />
	一句话评论<br />
	<br />
	亚当&middot;桑德勒又在暑期档和大家见面了，这是本片最有趣的一点。<br />
	&mdash;&mdash;Reelviews<br />
	<br />
	亚当&middot;桑德勒的及格作品，这部电影还是能给观众带去欢乐。<br />
	&mdash;&mdash;《娱乐周刊》<br />
	<br />
	◎剧　　照　<br />
	<br />
	<img alt="" border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://c0181321.cdn.cloudfiles.rackspacecloud.com/PHzadHBzvZF9Dz_1_m.jpg');" src="http://c0181321.cdn.cloudfiles.rackspacecloud.com/PHzadHBzvZF9Dz_1_m.jpg" /><br />
	<br />
	<img alt="" border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://c0181321.cdn.cloudfiles.rackspacecloud.com/PHr8IztrUK7duz_1_m.jpg');" src="http://c0181321.cdn.cloudfiles.rackspacecloud.com/PHr8IztrUK7duz_1_m.jpg" /><br />
	<br />
	<img alt="" border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://c0181321.cdn.cloudfiles.rackspacecloud.com/PHAECICAYRDlEJ_1_m.jpg');" src="http://c0181321.cdn.cloudfiles.rackspacecloud.com/PHAECICAYRDlEJ_1_m.jpg" /><br />
	<br />
	<img alt="" border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://c0181321.cdn.cloudfiles.rackspacecloud.com/PHb7yjdbgVPeed_1_m.jpg');" src="http://c0181321.cdn.cloudfiles.rackspacecloud.com/PHb7yjdbgVPeed_1_m.jpg" /><br />
	<br />
	<img alt="" border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://c0181321.cdn.cloudfiles.rackspacecloud.com/PHqfKysqbpXHuq_1_m.jpg');" src="http://c0181321.cdn.cloudfiles.rackspacecloud.com/PHqfKysqbpXHuq_1_m.jpg" /><br />
	<br />
	<img alt="" border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://c0181321.cdn.cloudfiles.rackspacecloud.com/PHqG3ysqdkFctt_1_m.jpg');" src="http://c0181321.cdn.cloudfiles.rackspacecloud.com/PHqG3ysqdkFctt_1_m.jpg" /><br />
	<br />
	<img alt="" border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://c0181321.cdn.cloudfiles.rackspacecloud.com/PH9jxhb9pr5Gbi_1_m.jpg');" src="http://c0181321.cdn.cloudfiles.rackspacecloud.com/PH9jxhb9pr5Gbi_1_m.jpg" /><br />
	<br />
	<img alt="" border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://c0181321.cdn.cloudfiles.rackspacecloud.com/PHjVUrljSaE4nj_1_m.jpg');" src="http://c0181321.cdn.cloudfiles.rackspacecloud.com/PHjVUrljSaE4nj_1_m.jpg" /><br />
	<br />
	<img alt="" border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://c0181321.cdn.cloudfiles.rackspacecloud.com/PHvCMDxv0gCWzx_1_m.jpg');" src="http://c0181321.cdn.cloudfiles.rackspacecloud.com/PHvCMDxv0gCWzx_1_m.jpg" /><br />
	<br />
	幕后制作<br />
	<br />
	　　关于成长的笑料<br />
	<br />
	　　30年前，几个小伙伴拿到了篮球赛的冠军；30年后，他们重新在母校聚首共度假期。如果这个题材交给文艺片导演来拍，或许又能拍出一个关于成长、关于自我、关于反思的深刻隽永的小故事，可能又能打动很多30、40岁即将步入中年的观众。可是这部电影的却是以喜剧闻名的丹尼斯&middot;杜根，主演则是他长期的合作伙伴亚当&middot;桑德勒，甚至连编剧也都是亚当&middot;桑德勒本人。看到这样的阵容，谁都会从心底里发出被逗笑的声音来。<br />
	<br />
	　　的确，这是一部喜剧，甚至从亚当&middot;桑德勒动笔写它之前，他就是一部喜剧了。桑德勒说：&ldquo;当那个老朋友几十年之后再聚首的故事冒到我的脑海里之后，我就给几个主要人物归了归类。克里斯&middot;洛克、凯文&middot;詹姆斯和大卫&middot;斯佩德这样几个人一下子就蹦到了我的脑子里。然后我就以这几个好朋友的样子为模板，写了一个好笑的故事。整个故事的主题发生在一间度假别墅里，几个好朋友来到这里消遣。他们不仅仅是共叙旧情，更多的是谈论自己现在的生活。过去了这么多年，大家的人生走上了不同的轨迹。有人发了财，有人穷困潦倒，还有人娶了老太太做老婆。可是说这是好笑的地方，也可以说这就是生活给我们开的玩笑。只不过生活的玩笑要比人们互相开的玩笑更难以接受。&rdquo;<br />
	<br />
	　　对于这个故事导演丹尼斯&middot;杜根显然很喜欢，因为比较起他前面拍摄的一些喜剧片而言，最新电影《长大后》的故事显得更自然、更亲切，也更合适桑德勒的年龄。他说：&ldquo;儿时的玩伴在长大后相聚的这个创意实在是非常惊艳，因为不同的成长经历会让人发生质的改变。所以，在这样的背景下，无论出现多么奇怪的人、出现多么奇怪的事都不足为奇了。如果硬要在<a href="http://www.3edyy.com/" target="_blank">电影下载</a>影片中制造笑料，则会显得太不自然。而且桑德勒也不再适合演初出茅庐的青年人了，观众可能也已经看厌了他在银幕上&lsquo;制造笑料&rsquo;；可以说，在这部电影里桑德勒是在展示笑料。真是因为如此，这部电影才显得更加真诚和好玩。而且我们还拍摄了一些&lsquo;儿童时代&rsquo;的篮球赛镜头，更加彻底地说明了成长这个主题。&rdquo;<br />
	<br />
	　　好伙伴的故事<br />
	<br />
	　　桑德勒在剧本中写的是伙伴的故事，在演员的选择上，他一样找来了自己的好朋友。克里斯&middot;洛克、凯文&middot;詹姆斯都是和桑德勒有过合作的同事兼伙伴。和伙伴在一起工作，自然会特别开心，也特别&ldquo;放得开&rdquo;。<br />
	<br />
	　　大卫&middot;斯佩德说：&ldquo;这个故事的确让我很感动，关于友情的情节让我感触颇深。因为把话说回来，我自己还是个心理上的孩子，自己的好伙伴永远是儿时的那些玩伴。我会经常打电话给他们聊天、诉苦或者是抱怨几句。所以对于影片中表现的那些儿时结下的成年人的情感，我很能理解淘宝网。&rdquo;凯文&middot;詹姆斯有了自己的孩子，所以，他对于影片中小孩子的情谊有着自己的感受，他说：&ldquo;我有自己的孩子，也经常带他一起打篮球什么的。当拍摄那场篮球赛的时候，我特别有感触，因为孩子们的友情非常简单：你对我好，我也对你好；你给我传球，我也给你传球。当然，他们翻脸与和好的速度也让人称奇。我站在篮球场上的时候，根本感觉不到我是个已经长大的成年人。&rdquo;<br />
	<br />
	　　相对于自己的朋友都说自己没有长大，亚当&middot;桑德勒则表现出了&ldquo;成年人&rdquo;的态度，他说：&ldquo;当我和孩子在一起的时候，我确确实实地感到自己长大了，因为他们都听你的，你是领导者。每个做了父母的人都会回想起自己还是小孩子的时候，自己的父母的做法，这个时候才能理解到做父母有多么艰难。我从小在一个教会联盟的篮球队打球，在我构思这部电影的时候，我曾想过要把故事安排在高中，但是我后来放弃了这个想法。如果去拍教会学校的小孩子打篮球会容易得多，而且有点年龄的父母看到小孩子就会回想起自己的孩子和自己小时候。如果拍高中的篮球赛，总会让人觉得有些遗憾，因为毕竟不是所有人都能进高中篮球队的，这个故事也就无法引起广泛的共鸣。&rdquo;<br />
	<br />
	花絮<br />
	<br />
	&middot;影片中出现在独立日游行队伍中的那些矮种马都是从现实生活中找来的。它们是亨特的天堂农场喂养的动物。<br />
	<br />
	&middot;影片中篮球赛的&ldquo;闪回镜头&rdquo;在波士顿的一间运动馆里拍摄。这个运动馆<a href="http://www.eee4.cc/" target="_blank">电影下载</a>没有空调，而拍摄当天的温度高达华氏95度（约和35摄氏度），所有的演员，包括临时演员穿的都是符合当年的面料制作的衣服－－涤纶面料。在整个拍摄过程中亚当&middot;桑德勒和导演丹尼斯&middot;杜根一直在片场执导那些小家伙打球，让拉拉队保持兴奋&mdash;&mdash;这场篮球赛拍了15个小时。<br />
	<br />
	&middot;亚当&middot;桑德勒在影片穿了一件印着UHN（University of New Hampshier，新汉普希尔大学）的T恤。桑德勒虽然出生在纽约，但却是在新汉普希尔长大的。<br />
	<br />
	&middot;亚当&middot;桑德勒是本片的编剧之一。<br />
	<br />
	精彩对白<br />
	<br />
	Lenny Feder: Higgy!<br />
	Marcus Higgins: Hey, what&#39;s up, Lenny? Buddy, I thought you were gonna start working out.<br />
	Lenny Feder: What does that mean?<br />
	Marcus Higgins: Um... you&#39;re fat.<br />
	Lenny Feder: No!<br />
	伦尼&middot;法德：嗨，老兄！<br />
	马库斯&middot;希金斯：嗨，怎么了，伦尼？哥们，我还以为你把老大难问题解决了呢。<br />
	伦尼&middot;法德：你这话什么意思？<br />
	马库斯&middot;希金斯：呃，你太胖了。<br />
	伦尼&middot;法德：胡扯！<br />
	<br />
	Roxanne Chase-Feder: [an old woman approaches them] And this must be your mother.<br />
	Rob Hilliard: My wife.<br />
	Roxanne Chase-Feder: I&#39;m sorry!<br />
	Rob Hilliard: I&#39;m not.<br />
	[kisses his wife]<br />
	Marcus Higgins: [onlooking] Oh, grody.<br />
	洛克珊&middot;齐斯-法德：（一个老太太走向他们）这个一定是你的母亲啦。<br />
	罗布&middot;希拉利德：是我太太。<br />
	洛克珊&middot;齐斯-法德：哦，太抱歉了。我没看出来。<br />
	罗布&middot;希拉利德：没关系，我不在意。<br />
	（吻他的妻子）<br />
	马库斯&middot;希金斯：（看到这一切）嗷，这太恶了。<br />
	<br />
	Bean Lamonsoff: Mommy, I want some milk.<br />
	Sally Lamonsoff: Come here. I&#39;ll give you a little something.<br />
	[starts breastfeeding Bean]<br />
	Roxanne Chase-Feder: Your son is so cute. How old is he?<br />
	Eric Lamonsoff: 48 months.<br />
	Kurt McKenzie: [pause] That&#39;s 4.<br />
	Eric Lamonsoff: [pause] Yeah.<br />
	比恩&middot;兰摩恩索夫：妈妈，我想喝牛奶。<br />
	塞利&middot;兰摩恩索夫：过来，我给你点其他的东西。<br />
	（开始&quot;人乳喂养&quot;比恩）<br />
	洛克珊&middot;齐斯-法德：你的儿子太可爱了，他今年多大了？<br />
	埃里克&middot;兰摩恩索夫：48个月了。<br />
	科特&middot;麦肯齐：（停顿了一下）那就是4岁？<br />
	埃里克&middot;兰摩恩索夫：（停顿了一下）是的。</p>
<p>
	【电影截图】：<br />
	<br />
	<img alt="" border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://photo9.zxip.com/albums9/folder18/14189/20101005102441/20101019115551540.jpg');" src="http://photo9.zxip.com/albums9/folder18/14189/20101005102441/20101019115551540.jpg" />&nbsp;<br />
	<img alt="" border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://photo9.zxip.com/albums9/folder18/14189/20101005102441/20101019115563626.jpg');" src="http://photo9.zxip.com/albums9/folder18/14189/20101005102441/20101019115563626.jpg" />&nbsp;<br />
	<img alt="" border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://photo9.zxip.com/albums9/folder18/14189/20101005102441/20101019115563700.jpg');" src="http://photo9.zxip.com/albums9/folder18/14189/20101005102441/20101019115563700.jpg" /></p>
<br />

<p>
	【下载地址】</p>
<table bgcolor="#0099cc" border="0" cellpadding="10" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.net" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy125:piaohua@dy125.piaohua.com:8051/飘花电影piaohua.com长大后BD中英双字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:8051/飘花电影piaohua.com长大后BD中英双字1280高清.rmvb</a></td>
		</tr>
		<tr>
		</tr>
	</tbody>
</table>
<br />{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O14913030-51015.jpg{/dede:field}
