<?php
$z[0]=Array("field","酒干倘卖无..MTV迅雷下载，免费",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","酒干倘卖无..MTV迅雷下载、免费下载，酒干倘卖无..MTVGvod高清在线播放，剧情介绍等。",72,196);
$z[1][4]['name']="description";
$z[2]=Array("field","酒干倘卖无..MTV",198,251);
$z[2][4]['name']="title";
$z[3]=Array("field","",253,292);
$z[3][4]['name']="writer";
$z[4]=Array("field","",294,333);
$z[4][4]['name']="source";
$z[5]=Array("field","2006-08-04",335,385);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<object classid=\"CLSID:22d6f312-b0f6-11d0-94ab-0080c74c7e95\" class=\"OBJECT\" id=\"MediaPlayer\" width=\"500\" height=\"350\" ><param name=\"ShowStatusBar\" value=\"-1\"><param name=\"Filename\" value=\"http://www.20530.com/UUAuth/06/05.wmv\"> \n</embed></object><br /> \n<P>下载地址<BR></P> <br>",387,702);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c120524/133N353DD0-2G248.gif",704,787);
$z[7][4]['name']="litpic";

?>