{dede:field name='keywords'}女巫布莱尔BD中英双字1280高清经{/dede:field}
{dede:field name='description'}女巫布莱尔BD中英双字1280高清经典恐怖惊悚迅雷下载、免费下载，女巫布莱尔BD中英双字1280高清经典恐怖惊悚Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}女巫布莱尔BD中英双字1280高清经典恐怖惊悚{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-14{/dede:field}
{dede:field name='body'}<p>
	&nbsp;<img alt="" src="http://apollo.s.dpool.sina.com.cn/nd/dataent/moviepic/pics/93/moviepic_a6e5a1b2461ea981cbcba7cbc4c14367.jpg" /></p>

<p>
	◎译　　名　女巫布莱尔/厄夜丛林(台)/死亡习作(港)<br />
	◎片　　名　The Blair Witch Project<br />
	◎年　　代　1999年01月25日<br />
	◎国　　家　美国<br />
	◎类　　别　恐怖 惊秫 神秘<br />
	◎语　　言　英语<br />
	◎字　　幕　中英双字幕<br />
	◎IMDB评分 6.2/10&nbsp;&nbsp; 87,325 votes<br />
	◎文件格式　RMVB<br />
	◎视频尺寸　1280x720<br />
	◎文件大小　939M<br />
	◎片　　长　01:21:24<br />
	◎导　　演　丹尼尔&middot;米瑞克 Daniel Myrick<br />
	◎主　　演<br />
	◎IMB <a title="最新电影" href="http://www.xiaozhizhu.net/">http://www.xiaozhizhu.net/</a>　<br />
	帕特丽霞&middot;迪考 Patricia DeCou<br />
	希德.多纳休 Heather Donahue<br />
	罗伯&middot;格里芬 Bob Griffin Jackie Hallex<br />
	吉姆&middot;金 Jim King<br />
	约束亚&middot;兰纳德 Joshua Leonard Mark Mason<br />
	埃德&middot;斯瓦森 Ed Swanson</p>
<p>
	◎简　　介　</p>
<p>
	《布莱尔女巫》无疑是1999年夏天好莱坞最大的黑马，这部投资仅仅100万美金的低成本影片，已经给工匠公司带来了上千万的回报。确切这部影片应该算是一部恐怖记录片，片中的主人公做梦也没有想到他们会在5年后会成为卖座&ldquo;明星&rdquo;，不过他们的代价实在太大了&hellip;&hellip;<br />
	　　1994年10月三个学电影的学生哈兹，迈克威廉姆斯 李昂哈德，带上了电影拍摄器材，来到了布尔镇，准备调查当地关于布尔女巫的传说，他们为了找寻布尔女巫来到了黑山林，但不久他们就消失了，5天后人们开始寻找他们，美国ZF为了找寻他们调用了100多人，同时使用了直升机甚至卫星，但10天过后一点结果也没有，于是只好放弃搜寻工作，但1年以后几个马里兰洲立大学的学生在山林的一个非常隐蔽的小木屋里发现了一个包裹，里面装有哈兹的日记和一个已经剪接好的电影拷贝盘，里面记载了三个人1年前失踪时所发生的所有恐怖事件，本部影片便是根据95年发现的拷贝盘，改编加工而成的</p>
<p>
	◎影片截图</p>
<p>
	&nbsp;&nbsp;<img alt="" border="0" height="337" src="http://img.album.pchome.net/54/82/07/19/93444cb56b0056f38a341056ec0a3fe3.JPG" width="600" /></p>
<p>
	&nbsp;<img alt="" border="0" height="337" src="http://img.album.pchome.net/54/82/07/19/7b490c89c00cbd0ac78b0b79b9e6fd5f.JPG" width="600" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.net/movie/34495.html" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3415/飘花电影piaohua.com女巫布莱尔BD中英双字1280高清.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3415/飘花电影piaohua.com女巫布莱尔BD中英双字1280高清.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3415/飘花电影piaohua.com女巫布莱尔BD中英双字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15bJ0-25403.jpg{/dede:field}
