<?php
$z[0]=Array("field","如何众叛亲离BD中英双字1024高清",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","如何众叛亲离BD中英双字1024高清迅雷下载、免费下载，如何众叛亲离BD中英双字1024高清Gvod高清在线播放，剧情介绍等。",73,227);
$z[1][4]['name']="description";
$z[2]=Array("field","如何众叛亲离BD中英双字1024高清",229,297);
$z[2][4]['name']="title";
$z[3]=Array("field","",299,338);
$z[3][4]['name']="writer";
$z[4]=Array("field","",340,379);
$z[4][4]['name']="source";
$z[5]=Array("field","2012-03-09",381,431);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",433,470);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://d31:d31@ftp.eee4.com:1103/[3E电影站www.eee4.com]如何众叛亲离DVD中字.rmvb\" target=\"_blank",472,605);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MO6312Z-4U62.jpg",607,689);
$z[8][4]['name']="litpic";

?>