{dede:field name='keywords'}李宇春2011WhyMe武汉演唱会1024{/dede:field}
{dede:field name='description'}李宇春2011WhyMe武汉演唱会1024高清迅雷下载、免费下载，李宇春2011WhyMe武汉演唱会1024高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}李宇春2011WhyMe武汉演唱会1024高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-06-28{/dede:field}
{dede:field name='body'}<p>
	<img src="/uploads/allimg/c120524/133N4P0L50-14C09.jpg" style="width: 450px; height: 675px" /></p>
<p>
	&nbsp;<img src="/uploads/allimg/c120524/133N4P0R60-155336.jpg" style="width: 450px; height: 675px" /></p>
<p>
	&nbsp;<img src="/uploads/allimg/c120524/133N4P1L30-162620.jpg" style="width: 450px; height: 675px" /></p>
<p>
	&nbsp;<img src="/uploads/allimg/c120524/133N4P44040-1L3M.jpg" style="width: 450px; height: 675px" /></p>
<p>
	<img src="/uploads/allimg/c120524/133N4P4L40-1S514.jpg"  style="width: 450px; height: 675px" /></p>
<p>
	2011年3月26日，李宇春&ldquo;2011WhyMe武汉演唱会&rdquo;在武汉体育中心盛大开唱。作为与歌迷共享音乐的欢聚庆典，每一年的&ldquo;WhyMe&rdquo;李宇春都贴心设置了歌迷互动环节。本场演唱会互动环节再次升级，名为&ldquo;与春春约会，秀秀你的鼓&rdquo;， 进入演唱会现场的歌迷早已准备好了铃鼓。</p>
<p>
	李宇春的演唱会不仅有金曲舞步，豪华的舞美制作同样不可缺少，换上印度造型服装，现场大跳肚皮舞。《Let&rsquo;s Get Loud》、《舞》、《来跳舞吧》、《来吧，吉米》等经典舞曲点燃全场观众内心跳动的火焰。在春春大鼓的带领下，全场皆是摇响的铃鼓，已然成为欢庆的铃鼓Party。</p>
<p>
	而为了达到最好的舞台效果，主办方更是耗资千万重金打造具有4D魔幻感的LED组屏，让舞台有着瀑布群般的视觉冲击。</p>
<p>
	&nbsp;<img src="/uploads/allimg/c120524/133N4P4P50-1b537.jpg" style="width: 550px; height: 366px" /></p>
<p>
	<img src="/uploads/allimg/c120524/133N4P4T40-20bU.jpg"style="width: 550px; height: 366px"  /></p>
<p>
	<img src="/uploads/allimg/c120524/133N4P4YF-211c1.jpg" style="width: 550px; height: 366px" /></p>

<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="/uploads/allimg/c120524/133N2Z4FF-102231.jpg" /> &nbsp;
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy444:piaohua@dy444.piaohua.com:419/飘花电影piaohua.com李宇春2011WhyMe武汉演唱会.rmvb </td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120524/133N4P49510-22JH.jpg{/dede:field}
