{dede:field name='keywords'}高地战BD高清迅雷下载，免费下载{/dede:field}
{dede:field name='description'}高地战BD高清迅雷下载、免费下载，高地战BD高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}高地战BD高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-10-06{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img165.poco.cn/mypoco/myphoto/20110927/09/62564813201109270949391151970348374_000.jpg" /></p>
<p>
	高地战The Front Line (2011)<br />
	国家/地区： 韩国<br />
	类型： 战争 / 剧情<br />
	片长：133分钟<br />
	分级： South Korea:15<br />
	对白语言： 韩语<br />
	发行公司： Showbox<br />
	官方网站： <a href="http://www.frontline.co.kr/">http://www.frontline.co.kr/</a><br />
	更多外文名：<br />
	???<br />
	导演： 张勋<br />
	主演： 高修 申河均 金玉彬 更多&gt;&gt;<br />
	类型： 战争 / 剧情<br />
	上映日期： 2011年7月20日 韩国</p>
<p>
	剧情<br />
	《义兄弟》导演新作延续&ldquo;双雄片&rdquo;模式，并携手《共同警备区JSA》的作家朴相彦，高修与申河均在炮火纷飞中体会男人的背叛与成长。</p>
<p>
	幕后花絮</p>
<p>
	&middot;影片2010年9月建组，成员们放弃了中秋节长假，于10月在全州正式开拍。<br />
	&middot;剧组在结束了四个多月的拍摄后在拍摄地韩国庆尚南道咸阳郡百岩山展开了绿化植树工作，以挽回拍摄战争戏对山地绿化造成的破坏。<br />
	&middot;该片编剧朴相彦也是《JSA共同警备区》原小说作者，近期编剧代表作为《善德女王》。<br />
	&middot;影片在实现战争场面时破费不小，共投入14000人（其中特技演员500人）、枪支45000部左右。仅一个爆破场面就动用了真枪</p>
<p>
	<img alt="" src="http://img165.poco.cn/mypoco/myphoto/20111006/01/62564813201110060136431060181095387_002.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img165.poco.cn/mypoco/myphoto/20111006/01/62564813201110060136431060181095387_001.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img165.poco.cn/mypoco/myphoto/20111006/01/62564813201110060136431060181095387_000.jpg" style="width: 720px; height: 405px" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="&#13;&#10;ftp://dy125:piaohua@dy125.piaohua.com:6070/飘花电影piaohua.com高地战BD中字1024高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:6070/飘花电影piaohua.com高地战BD中字1024高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O16251N0-22531.jpg{/dede:field}
