{dede:field name='keywords'}竞雄女侠秋瑾DVD国语中字2011迅{/dede:field}
{dede:field name='description'}竞雄女侠秋瑾DVD国语中字2011迅雷下载、免费下载，竞雄女侠秋瑾DVD国语中字2011Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}竞雄女侠秋瑾DVD国语中字2011{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-10-16{/dede:field}
{dede:field name='body'}<p>
	<img border="0" src="http://img165.poco.cn/mypoco/myphoto/20111013/13/56634212201110131318382249983031194_004.jpg" style="max-width: 750px; max-height: 750px" /></p>
<p>
	&nbsp;<img border="0" src="http://img165.poco.cn/mypoco/myphoto/20111013/13/56634212201110131318382249983031194_003.jpg" style="max-width: 750px; max-height: 750px" /></p>
<p>
	<img border="0" src="http://img165.poco.cn/mypoco/myphoto/20111013/13/56634212201110131318382249983031194_002.jpg" style="max-width: 750px; max-height: 750px" /></p>
<p>
	中文名： 竞雄女侠秋瑾<br />
	英文名： The Woman Knight of Mirror Lake<br />
	导演： 邱礼涛<br />
	主演： 黄奕 / 杜宇航 / 黄秋生 / 郑嘉颖 / 陈嘉桓 / 夏文汐 / 熊欣欣 / 林雪 / 刘兆铭 / 徐天佑 / 黄又南 / 刘俊纬 / 阎清<br />
	上映日期： 2011年10月13日&nbsp;&nbsp; 中国<br />
	国家/地区： 中国&nbsp; /&nbsp; 中国香港&nbsp;<br />
	类型： 剧情&nbsp; /&nbsp; 传记&nbsp; /&nbsp; 动作&nbsp;<br />
	片长：120分钟<br />
	对白语言： 汉语普通话</p>
<p>
	<br />
	剧情简介</p>
<p>
	　　「雙腳再小也沒用，根本走不動。難道女子一生只為找個好歸宿，並無其它前途？」巾幗夏雪出身書香世代，性格剛强、有主見，年纪小小便反對纏足。她愛與男子相比，騎馬射箭、吟詩作對，無一不通；要比男子漢走出更大的步、更遠的路。天生聰颖，深得父亲疼愛，自小跟隨父亲遊遍大江南北，不受規限的夏雪經常女扮男裝遊山玩水，最愛河山之美，最痛恨洋人来瓜分祖國土地。夏雪二十歲時，在父母安排下嫁纨绔子弟黄達君，但二人性格、思想不合，婚姻並不和諧，而且夏雪無法接受夫君在國難當前仍沉溺享樂。當夏雪看到八國聯軍在京城燒殺擄掠，四處民不聊生，滿目瘡痍，恨極朝廷的腐敗，埋下她日後立志推翻朝廷的心。救國救民迫在眉睫，夏雪主張教育救國，她毅然變賣華衣首飾到日本留學，擴大眼光；在東京認識了一群志同道合的女權倡導者和愛國者，發起解放婦女和愛國的運動，進一步踏上民族女。回國後，夏雪加入秘密革命组織，... (展开全部) 　　「雙腳再小也沒用，根本走不動。難道女子一生只為找個好歸宿，並無其它前途？」巾幗夏雪出身書香世代，性格剛强、有主見，年纪小小便反對纏足。她愛與男子相比，騎馬射箭、吟詩作對，無一不通；要比男子漢走出更大的步、更遠的路。天生聰颖，深得父亲疼愛，自小跟隨父亲遊遍大江南北，不受規限的夏雪經常女扮男裝遊山玩水，最愛河山之美，最痛恨洋人来瓜分祖國土地。夏雪二十歲時，在父母安排下嫁纨绔子弟黄達君，但二人性格、思想不合，婚姻並不和諧，而且夏雪無法接受夫君在國難當前仍沉溺享樂。當夏雪看到八國聯軍在京城燒殺擄掠，四處民不聊生，滿目瘡痍，恨極朝廷的腐敗，埋下她日後立志推翻朝廷的心。救國救民迫在眉睫，夏雪主張教育救國，她毅然變賣華衣首飾到日本留學，擴大眼光；在東京認識了一群志同道合的女權倡導者和愛國者，發起解放婦女和愛國的運動，進一步踏上民族女。回國後，夏雪加入秘密革命组織，與亦師亦友的同鄉秦兆隆一起策動革命活動，二人辦報、辦學，排除萬難。秦兆隆捐官滲入清廷，夏雪已擬定軍事計，無奈事與願違，秦兆隆刺殺清廷官史的行動失敗，當場被捕，壯烈犧牲。當夏雪得悉噩耗，悲恸不已，但她並沒有選擇退縮，而是舉起槍頭，帶領學生對抗敵人。可惜，夏雪亦難逃厄運，公堂之上不斷被用刑，迫她供出同黨，夏雪義薄雲天，寧死不屈，從容就義。亂世出英雄，一場轟烈的起義牽動了不少愛國心&hellip;&hellip;</p>
<p>
	&nbsp;<img border="0" src="http://img165.poco.cn/mypoco/myphoto/20111015/16/56634212201110151643002989856710156_004.jpg" style="max-width: 750px; max-height: 750px" /><br />
	<br />
	<img border="0" src="http://img165.poco.cn/mypoco/myphoto/20111015/16/56634212201110151643002989856710156_003.jpg" style="max-width: 750px; max-height: 750px" /><br />
	<br />
	<img border="0" src="http://img165.poco.cn/mypoco/myphoto/20111015/16/56634212201110151643002989856710156_002.jpg" style="max-width: 750px; max-height: 750px" /><br />
	<br />
	<img border="0" src="http://img165.poco.cn/mypoco/myphoto/20111015/16/56634212201110151643002989856710156_001.jpg" style="max-width: 750px; max-height: 750px" /><br />
	<br />
	<img border="0" src="http://img165.poco.cn/mypoco/myphoto/20111015/16/56634212201110151643002989856710156_000.jpg" style="max-width: 750px; max-height: 750px" /><br />
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:1828/飘花电影piaohua.com竞雄女侠秋瑾DVD-SCR国语中字.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:1828/飘花电影piaohua.com竞雄女侠秋瑾DVD-SCR国语中字.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:1830/飘花电影piaohua.com竞雄女侠秋瑾DVD国语中字.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:1830/飘花电影piaohua.com竞雄女侠秋瑾DVD国语中字.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1625F60-2K13.jpg{/dede:field}
