{dede:field name='keywords'}开关高清BD1280迅雷下载，免费下{/dede:field}
{dede:field name='description'}开关高清BD1280迅雷下载、免费下载，开关高清BD1280Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}开关高清BD1280{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-04-18{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120418/08/62564813201204180832413300330231197_000.jpg" style="width: 650px" /></p>
<p>
	◎译　　名　开关<br />
	◎片　　名　switch<br />
	◎年　　代　2011<br />
	◎国　　家　法国<br />
	◎类　　别　犯罪/喜剧<br />
	◎语　　言　法语<br />
	◎字　　幕　中字<br />
	◎IMDB评分 &nbsp;6.3/10 from 187 users<br />
	◎IMDB链接 &nbsp;<a href="http://www.imdb.com/title/tt1401636/" target="_blank">http://www.imdb.com/title/tt1401636/</a><br />
	◎文件格式　BD<br />
	◎视频尺寸　1280 x 720<br />
	◎文件大小　1.09G<br />
	◎片　　长　1h 44min<br />
	◎导　　演　弗雷德里克&middot;施恩多弗<br />
	◎主　　演　卡琳&middot;瓦纳斯 Karine Vanasse &nbsp;....Sophie Malaterre<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;埃里克&middot;坎通纳 Eric Cantona &nbsp;....Damien Forgeat<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Mehdi Nebbou &nbsp;....St&eacute;phane Defers<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;奥雷利安&middot;雷克因 Aur&eacute;lien Recoing &nbsp;....Delors<br />
	　　　　　　<br />
	<br />
	◎简　　介　<br />
	<br />
	&nbsp; 前曼联球星，外号&ldquo;国王&rdquo;的埃里克.坎通纳1997年退役后，踏足娱乐圈，先后出演《饭局》、《寻找埃里克》等电影，但大多是些小角色，可是坎通纳显然将足球场上的才华带到了片场，每个人物都显得桀骜不驯，有着自己独特的生命力。这次在《开关》中，坎通纳终于有机会出演主角，和他搭档的是曾出演《午夜巴黎》的女演员卡琳.瓦纳斯。影片描述了一位25岁女网友在交友网站与一位男子结识，相约见面后的第二天，隔壁出现一具尸体，为洗脱自己的嫌疑，她必须和时间赛跑......</p>
<p>
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120418/08/62564813201204180817431024947134352_005.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120418/08/62564813201204180817431024947134352_004.jpg" style="width: 720px; height: 405px" /><br />
	<br />
	&nbsp;</p>
<p>
	【下载地址】</p>
<table bgcolor="#0099cc" border="0" cellpadding="10" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.net" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy125:piaohua@dy125.piaohua.com:7866/飘花电影piaohua.com开关BD中英双字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:7866/飘花电影piaohua.com开关BD中英双字1280高清.rmvb</a></td>
		</tr>
		<tr>
		</tr>
	</tbody>
</table>
<br />{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15621020-1H40.jpg{/dede:field}
