<?php
$z[0]=Array("field","我们曾是战士/勇士们/军天壮志/",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","我们曾是战士/勇士们/军天壮志/征战岁月[BD中英双字1280x720高清版]迅雷下载、免费下载，我们曾是战士/勇士们/军天壮志/征战岁月[BD中英双字1280x720高清版]Gvod高清在线播放，剧情介绍等。",72,292);
$z[1][4]['name']="description";
$z[2]=Array("field","我们曾是战士/勇士们/军天壮志/征战岁月[BD中英双字1280x720高清版]",294,395);
$z[2][4]['name']="title";
$z[3]=Array("field","",397,436);
$z[3][4]['name']="writer";
$z[4]=Array("field","",438,477);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-08-27",479,529);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",531,568);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://4e:4e@d8.3edyy.com:177/【3E电影院www.eee4.cc】我们曾经是战士BD中英双字1280x720高清版.rmvb\" target=\"_blank",570,720);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MP63F50-42612.jpg",722,805);
$z[8][4]['name']="litpic";

?>