{dede:field name='keywords'}驯龙记/驯龙高手[BD中英双字1024{/dede:field}
{dede:field name='description'}驯龙记/驯龙高手[BD中英双字1024/1280高清高清版]迅雷下载、免费下载，驯龙记/驯龙高手[BD中英双字1024/1280高清高清版]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}驯龙记/驯龙高手[BD中英双字1024/1280高清高清版]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-04-05{/dede:field}
{dede:field name='body'}<p>
	<img src="http://www.4dshijue.com/uploads/allimg/100508/1_100508130025_1.jpg" /><br />
	&nbsp;<br />
	<img alt="" border="0" onclick="zoom(this)" onload="attachimg(this, 'load')" src="http://cdn3a.dvdempire.org/products/38/1543738h.jpg" /></p>
<p>
	<br />
	<br />
	<br />
	◎译　　名　《驯龙记/驯龙/驯龙高手》2010年美国最新票房冠军超高分3D动画喜剧大片BD中英双字1024x576高清版<br />
	◎片　　名　How To Train Your Dragon<br />
	◎年　　代　2010<br />
	◎国　　家　美国<br />
	◎类　　别　动画/冒险/喜剧/家庭/幻想<br />
	◎语　　言　英语<br />
	◎字　　幕　英文/法文/西班牙文<br />
	◎IMDB评分 8.2/10 (29,190 votes)<br />
	◎IMDB链接 http://www.imdb.com/title/tt0892769<br />
	◎文件格式　BD-RMVB<br />
	◎视频尺寸　640 x 360+1024x576 1280&times;720<br />
	◎文件大小　1CD 49 x 15MB<br />
	◎片　　长　98 Mins<br />
	◎导　　演　迪恩&middot;德布洛斯 Dean DeBlois<br />
	　　　　　　克里斯&middot;桑德斯 Chris Sanders<br />
	◎主　　演　杰伊&middot;巴鲁切尔 Jay Baruchel&nbsp;&nbsp;....Hiccup (voice)<br />
	　　　　　　杰拉德&middot;巴特勒 Gerard Butler&nbsp;&nbsp;....Stoick (voice)<br />
	　　　　　　亚美莉卡&middot;费雷拉 America Ferrera&nbsp;&nbsp;....Astrid (voice)<br />
	　　　　　　克雷格&middot;费格森 Craig Ferguson&nbsp;&nbsp;....Gobber (voice)<br />
	　　　　　　乔纳&middot;希尔 Jonah Hill&nbsp;&nbsp;....Snotlout (voice)<br />
	　　　　　　克里斯托夫&middot;梅兹-普莱瑟 Christopher Mintz-Plasse&nbsp;&nbsp;....Fishlegs (voice)<br />
	　　　　　　克里斯汀&middot;韦格 Kristen Wiig&nbsp;&nbsp;....Ruffnut (voice)<br />
	　　　　　　T&middot;J&middot;米勒 T.J. Miller&nbsp;&nbsp;....Tuffnut (voice)<br />
	　　　　　　Kieron Elliott&nbsp;&nbsp;....Viking (uncredited)<br />
	　　　　　　Robin Atkin Downes&nbsp;&nbsp;....Ack<br />
	　　　　　　Philip McGrade&nbsp;&nbsp;....Starkard (voice)<br />
	　　　　　　阿什丽&middot;詹森 Ashley Jensen&nbsp;&nbsp;....Phlegma the Fierce (voice)<br />
	　　　　　　Peter Aude&nbsp;&nbsp;....Havblik den V?ldige (voice: Danish Version)<br />
	　　　　　　Rasmus Ellersgaard&nbsp;&nbsp;....Fiskeben (voice: Danish Version)<br />
	　　　　　　罗伯特&middot;汉森 Robert Hansen&nbsp;&nbsp;....Hikke (voice: Danish Version)<br />
	　　　　　　Julian Eliot Kellerman&nbsp;&nbsp;....Stenknold Thorskal (voice: Danish Version)<br />
	　　　　　　Sasia M?lgaard&nbsp;&nbsp;....Benknold (voice: Danish Version)<br />
	　　　　　　Niclas Mortensen&nbsp;&nbsp;....Snotfj?s (voice: Danish Version)<br />
	　　　　　　Niels Olsen&nbsp;&nbsp;....Gobert (voice: Danish Version)<br />
	<br />
	<br />
	◎简　　介　<br />
	<br />
	本片改编自葛蕾熙达&middot;柯维尔（Cressida Cowell）的同名儿童图书。<br />
	<br />
	话说在一个遥远的国度里，海上有着一群神出鬼没的维京海盗，而统治这群海盗的，则是名叫&quot;Hiccup二世&quot;的首领，而他的儿子，自然就是&quot;Hiccup Horrendous Haddock三世&quot;（杰伊&middot;柿巴鲁切尔饰）。Hiccup二世对自己的儿子寄予厚望，一直要把他培养成一个接班人，但Hiccup三世最擅长做的事却是睡懒觉和无所事事，父亲给他向安排的种种战斗训练几乎都被他搪塞过去，一日一天一天的这么过下去，终于要到了Hiccup成年的日子。<br />
	<br />
	　　根据维京海盗的&quot;盗规&quot;，凡是年满18岁的首领继承人，必须要通过维京海盗的考验，才有成为首领的资格。而这份考验就是：捉到一条残暴凶狠的龙，并且顺服它，使它成为自己的宠物。压根就没好好学过功夫的Hiccup三世硬着头皮踏上了寻龙的历程，可不想却偏偏让他撞上了这么一条龙：一个刚刚出生，乳臭未干的小龙崽！望着这头连牙都没长出来的小龙，Hiccup三世决定驯服它然后起程回家，不过他所不知道的是，整个冒险才刚刚开始而已&hellip;&hellip;<br />
	<br />
	一句话评论<br />
	<br />
	动画技术非常华丽，而最吸引观众的则是精彩的故事！<br />
	<br />
	--《综艺》<br />
	<br />
	◎剧　　照　<br />
	<br />
	<img alt="" border="0" onclick="zoom(this)" onload="attachimg(this, 'load')" src="http://images.rottentomatoes.com/images/movie/gallery/1194522/photo_27_hires.jpg" />&nbsp;<br />
	<img alt="" border="0" onclick="zoom(this)" onload="attachimg(this, 'load')" src="http://images.rottentomatoes.com/images/movie/gallery/1194522/photo_26_hires.jpg" />&nbsp;<br />
	<img alt="" border="0" onclick="zoom(this)" onload="attachimg(this, 'load')" src="http://images.rottentomatoes.com/images/movie/gallery/1194522/photo_25_hires.jpg" />&nbsp;<br />
	<img alt="" border="0" onclick="zoom(this)" onload="attachimg(this, 'load')" src="http://images.rottentomatoes.com/images/movie/gallery/1194522/photo_24_hires.jpg" />&nbsp;<br />
	<img alt="" border="0" onclick="zoom(this)" onload="attachimg(this, 'load')" src="http://images.rottentomatoes.com/images/movie/gallery/1194522/photo_05_hires.jpg" />&nbsp;<br />
	<img alt="" border="0" onclick="zoom(this)" onload="attachimg(this, 'load')" src="http://images.rottentomatoes.com/images/movie/gallery/1194522/photo_06_hires.jpg" /><br />
	<br />
	幕后制作<br />
	<br />
	　　一年一度的梦工厂<br />
	<br />
	　　梦工厂的动画向来都是以欢乐闹腾的喜剧题材为主心骨，例如《怪物史莱克》或者《功夫熊猫》都是令人捧腹不已的卖座动画片。在去年的《大战外星人》乱炖了外星人进攻、地球怪物变异等经典科幻情节之后，今年梦工厂推出的是这部改编自畅销文学作品的《驯龙记》。对于这部动画片的制作缘起，监制邦尼&middot;阿诺德说：&quot;我们最初定下的计划是以一本读者很多的小说作为原著来改写它，当时我们参考了市面上许多的儿童文学，其中就有这部《驯龙记》。我们在一堆图书里发现了它，很快就感到它具有极强的影像化，观众们应该会感到很有兴趣，因为《驯龙记》里的神龙形象颠覆了过去我们常常见到的那些龙的特征，实际上这是一头很没有战斗力和威慑力的小龙，观众可以随着影片一起见证它的成长，龙的成长过程，就是电影要表达的重点。我想观众很会喜欢看到这种题材，《驯龙记》是一个典型的冒险故事，也符合梦工厂一贯的动画风格，所以我们很快就开始和原作者洽谈，进入动画的筹备阶段。&quot;<br />
	<br />
	　　担任《驯龙记》导演一职的，是迪恩&middot;德布洛斯与克里斯&middot;桑德斯，两者起初是在2002年的迪斯尼动画片《星际宝贝》里合作而认识，对于这部新作，克里斯&middot;桑德斯说：&quot;《驯龙记》<a href="http://www.3edyy.com/" target="_blank">电影下载</a>是一部较之梦工厂过去的作品有一些风格区别的电影，我们在制作的过程里参考了许多中世纪的书籍和电影，想把这部电影的奇幻色彩做得不那么卡通化，也就是说观众也许会感到，《驯龙记》有些像《加勒比海盗》或者《指环王》，但不会像《怪物史莱克》。我们按照制作一部真人奇幻电影的心态来制作这部《驯龙记》，当然喜剧色彩并未衰退，剧本依然有很多让人大笑不已的桥段，只是在整部动画的表达层面上变得更加真实而已。&quot;<br />
	<br />
	为什么会以&quot;真实&quot;作为影片的制作标准呢？对于这一点，克里斯&middot;桑德斯说：&quot;这是一部讲述年轻海盗小伙如何征服一条神龙的故事，龙是存在于各国神话故事里的生物，它的传奇色彩很浓，相反我们却对海盗感到很亲切，而除了龙之外，整个《驯龙记》的故事都是和真实的历史较为接近的，所以我们在创作的时候确立了这么一点，要让观众觉得故事很真实，龙的出现是故事在真实和奇幻中的一个连接桥梁，能够让观众觉得，我们的历史上也曾经出现了这么一个拐点，如果能达到这个效果，说明我们的念头做成功了。制作《驯龙记》的时候，制作人员找来了大量中世纪时期海盗的资料，整个工作室里满墙都是这些玩意，每天让我走进工作室的时候，我都会意识到，我们是在讲述历史，不过是用动画的方式来表达而已。瞧，我们自己都把自己给瞒住了。&quot;<br />
	<br />
	　　本片还在冬奥会期间特别制作了七段和奥运会有关的短片，对于这个短片的由来，导演克里斯&middot;桑德斯说：&quot;一开始我们就想制作一些有趣的短片，来让大家明白本片的魅力，而后就有了冬奥会的这几个片段。我们的灵感来源于本届冬奥会的北欧元素，这部电影所讲述的也是北欧的故事，而片中跟运动有关的素材也很多，所以就产生了这样几段11世纪的&#39;维京冬奥会&#39;短片。&quot;<br />
	<br />
	　　与小龙一起成长<br />
	<br />
	　　梦工厂制作的动画的一大特色就是，以大牌演员做声优，这次《驯龙记》请到了杰伊&middot;巴鲁切尔、杰拉德&middot;巴特勒和&quot;丑女贝蒂&quot;亚美莉卡&middot;费雷拉等明星。为本片男主角海卡普配音的是杰伊&middot;巴鲁切尔，这位来自加拿大的年轻演员新路颇顺，在多部影片中展现了其不俗的喜剧功力，前不久还主演了《我配不上她》。这次首度为动画献声，杰伊&middot;巴鲁切尔说：&quot;我比这部动画里配音的角色要大十岁，但是我却不觉得和他有代沟，这个角色其实是所有人年轻时候的一个投影，他有严厉的父亲，有惰性，当他面临责任和危机的时候，他才会真正的成长起来。表面上看《驯龙记》<a href="http://www.eee4.cc/" target="_blank">3E电影院</a>讲述的是海卡普的小龙成长的过程，其实，也是海卡普自己的成长，我想这些人人都曾经经历过的故事，会引起大家的共鸣吧。&quot;<br />
	<br />
	本片里当仁不让的明星角色，自然就是这条连牙都没长齐的小龙了，向来不按牌理出牌的梦工厂，将宝都押在这条小龙上自然是信心十足，对于这个角色的刻画，导演克里斯&middot;桑德斯说：&quot;这部电影讲述的不是一个英雄如何征服世界，而是一个普通人如何被世界所改变。影片或多或少借鉴了一些《功夫熊猫》的概念，《功夫熊猫》观众可以很明白的感受到影片里那只熊猫是如何成长的，同样，在《驯龙记》里，观众也可以随主角海卡普一起见证龙的成长。这条龙的外形集合了大家的智慧，它要足够可爱，要让观众觉得亲切，小孩子看见也会想去抱一抱&hellip;&hellip;就像《功夫熊猫》的阿宝一样。&quot;<br />
	<br />
	花絮<br />
	<br />
	&middot;影片改编迁自克蕾熙达&middot;柯维尔的同名儿童图书。<br />
	<br />
	&middot;本片导演克里斯&middot;桑德斯在2006年末因为在《闪电狗》创作上与《闪电狗》的监制约翰&middot;拉塞特产生分歧而离开迪士尼动画部，后来改投梦工厂，本片是他在梦工厂的第一部导演作品。<br />
	<br />
	&middot;影片里的无齿龙的角色设定，部分灵感来源于2002年的《星际宝贝》，而这部动画片的导演正是《驯龙记》的导演克里斯&middot;桑德斯。<br />
	<br />
	精彩对白<br />
	<br />
	Hiccup: Thank you for nothing, you useless reptile.<br />
	<br />
	海卡普：&quot;感谢个啥啊，你真是条没用的爬行动物。&quot;</p>
<p>
	【电影截图】：<br />
	<br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://img.album.pchome.net/54/74/10/83/17b71c871fd2fe36d648cd23b63d9e10.jpg');" src="http://img.album.pchome.net/54/74/10/83/17b71c871fd2fe36d648cd23b63d9e10.jpg" />&nbsp;<br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://img.album.pchome.net/54/74/10/83/ff065d3a1bd393fe116edbd5accca3df.jpg');" src="http://img.album.pchome.net/54/74/10/83/ff065d3a1bd393fe116edbd5accca3df.jpg" /><br />
	<br />
	&nbsp;</p>
	&nbsp;2010年美国最新票房冠军超高分3D动画喜剧大片《驯龙记》真正DVD中英双字 [下载地址]：<img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" /></p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://6e:6e@m1.eee4.cc:1552/【3E电影院www.eee4.org】驯龙高手DVD中英双字.rmvb" target="_blank">ftp://6e:6e@m1.eee4.cc:1552/【3E电影院www.eee4.org】驯龙高手DVD中英双字.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://3e:3e@d8.3edyy.com:190/【3E电影院www.eee4.org】驯龙高手BD中英双字1024x576高清版.rmvb" target="_blank">ftp://3e:3e@d8.3edyy.com:190/【3E电影院www.eee4.org】驯龙高手BD中英双字1024x576高清版.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:1434/飘花电影piaohua.com驯龙高手1280高清.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:1434/飘花电影piaohua.com驯龙高手1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3208/飘花电影piaohua.com驯龙高手BD国语配音中字1024高清.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3208/飘花电影piaohua.com驯龙高手BD国语配音中字1024高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1B5X40-41W1.jpg{/dede:field}
