<?php
$z[0]=Array("field","今晚80后说相声HD国语中字1024高",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","今晚80后说相声HD国语中字1024高清迅雷下载、免费下载，今晚80后说相声HD国语中字1024高清Gvod高清在线播放，剧情介绍等。",73,231);
$z[1][4]['name']="description";
$z[2]=Array("field","今晚80后说相声HD国语中字1024高清",233,303);
$z[2][4]['name']="title";
$z[3]=Array("field","",305,344);
$z[3][4]['name']="writer";
$z[4]=Array("field","",346,385);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-10-03",387,437);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>\r\n	<img alt=\"\" src=\"http://pic.piaohua.com/0701pic/allimg/111003/1-1110031I505434.jpg\" /></p>\r\n<p>\r\n	[下载地址]：<img border=\"0\" src=\"/templets/img/down.jpg\" /></p>\r\n\r\n\r\n<table align=\"center\" border=\"0\" cellpadding=\"6\" cellspacing=\"0\" style=\"border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted\" width=\"95%\">\r\n	<tbody>\r\n		<tr>\r\n			<td bgcolor=\"#fdfddf\" style=\"word-wrap: break-word\">\r\n				<a href=\"ftp://dy44:piaohua@dy44.piaohua.com:1716/飘花电影piaohua.com今晚80后说相声HD国语中字1024高清.rmvb\">ftp://dy44:piaohua@dy44.piaohua.com:1716/飘花电影piaohua.com今晚80后说相声HD国语中字1024高清.rmvb</a></td>\r\n		</tr>\r\n	</tbody>\r\n</table>",439,1213);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c120525/133O1C41P-1A09.jpg",1215,1296);
$z[7][4]['name']="litpic";

?>