{dede:field name='keywords'}玉蝎子的魔咒/爱情魔咒高清迅雷{/dede:field}
{dede:field name='description'}玉蝎子的魔咒/爱情魔咒高清迅雷下载、免费下载，玉蝎子的魔咒/爱情魔咒高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}玉蝎子的魔咒/爱情魔咒高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-10-11{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img165.poco.cn/mypoco/myphoto/20111008/09/62564813201110081006062711323843545_000.jpg" /></p>
<p>
	◎译　　名　玉蝎子的魔咒/爱情魔咒/玉蝎子的咒语<br />
	◎片　　名　The Curse of the Jade Scorpion<br />
	◎年　　代　2001<br />
	◎国　　家　美国/德国<br />
	◎类　　别　喜剧/犯罪/神秘<br />
	◎语　　言　英语<br />
	◎字　　幕　中字<br />
	◎IMDB评分 &nbsp; 6.7/10 (17,552 votes)<br />
	◎IMDB链接 &nbsp; <a href="http://www.imdb.com/title/tt0256524/" target="_blank">http://www.imdb.com/title/tt0256524/</a><br />
	◎文件格式　X264 + AC3<br />
	◎视频尺寸　1280 x 720<br />
	◎文件大小　1 DVD<br />
	◎片　　长　1h 41min<br />
	◎导　　演　伍迪&middot;艾伦 Woody Allen<br />
	◎主　　演　伍迪&middot;艾伦 Woody Allen ....C.W. Briggs<br />
	　　　　　　伊丽莎白&middot;伯克利 Elizabeth Berkley ....Jill<br />
	　　　　　　查理兹&middot;塞隆 Charlize Theron ....Laura Kensington<br />
	　　　　　　华莱士&middot;肖恩 Wallace Shawn ....George Bond<br />
	　　　　　　丹&middot;艾克罗伊德 Dan Aykroyd ....Chris Magruder<br />
	　　　　　　肯尼斯&middot;艾德森 Kenneth Edelson ....Voltan&#39;s Participant<br />
	　　　　　　阿瑟&middot;J&middot;纳斯加勒拉 Arthur J. Nascarella ....Tom, Detective (as Arthur Nascarella)<br />
	　　　　　　John Tormey ....Sam<br />
	　　　　　　John Schuck ....Mize<br />
	　　　　　　Kaili Vernoff ....Rosie<br />
	　　　　　　Brian Markinson ....Al<br />
	　　　　　　Maurice Sonnenberg ....Office Worker<br />
	　　　　　　John Doumanian ....Office Worker<br />
	　　　　　　Peter Gerety ....Ned<br />
	　　　　　　Kevin Cahoon ....Lunch Delivery Man<br />
	　　　　　　Philip Levy ....Rocky&#39;s Waiter (as Phil Levy)<br />
	　　　　　　Vince Giordano ....Rainbow Room All Star<br />
	　　　　　　Howard Alden ....Rainbow Room All Star<br />
	　　　　　　Ted Sommer ....Rainbow Room All Star<br />
	　　　　　　Randy Sandke ....Rainbow Room All Star<br />
	　　　　　　Peter Ecklund ....Rainbow Room All Star<br />
	　　　　　　Joel Helleny ....Rainbow Room All Star<br />
	　　　　　　Chuck Wilson ....Rainbow Room All Star<br />
	　　　　　　Raymond Beckenstein ....Rainbow Room All Star (as Ray Beckenstein)<br />
	　　　　　　Lawrence Feldman ....Rainbow Room All Star<br />
	　　　　　　Ken Peplowski ....Rainbow Room All Star<br />
	　　　　　　Dick Hyman ....Band Leader<br />
	　　　　　　大卫&middot;奥根&middot;斯提尔斯 David Ogden Stiers ....Voltan Polgar<br />
	　　　　　　Carole Bayeux ....Voltan&#39;s Assistant<br />
	　　　　　　Brian McConnachie ....Voltan&#39;s Participant<br />
	　　　　　　Judy Gold ....Voltan&#39;s Participant<br />
	　　　　　　Herb Lovelle ....Night Guard<br />
	　　　　　　Carmen ....Rose Kensington<br />
	　　　　　　Patrick Horgan ....Kensington Guest<br />
	　　　　　　Howard Erskine ....Kensington Guest<br />
	　　　　　　Ira Wheeler ....Kensington Guest<br />
	　　　　　　Tina Sloan ....Kensington Guest<br />
	　　　　　　Ramsey Faragallah ....Fingerprint Detective<br />
	　　　　　　Bob Dorian ....Mike, Detective<br />
	　　　　　　Trude Klein ....Lottie, Kensington Maid<br />
	　　　　　　Irwin Corey ....Charlie (as Professor Irwin Corey)<br />
	　　　　　　Michael Mulheren ....Herb Coopersmith<br />
	　　　　　　Peter Linari ....Joe Coopersmith<br />
	　　　　　　Ray Garvey ....Police Station Cop<br />
	　　　　　　Bruce Brown ....Radio Announcer<br />
	　　　　　　Dan Moran ....Briggs&#39; Street Contact<br />
	　　　　　　Fabrizio Fante ....Sam&#39;s Co-Worker (uncredited)<br />
	　　　　　　Greg Stebner ....Cop (uncredited)<br />
	　　　　　　Noah Weisberg ....Rainbow Room Dancer (uncredited)<br />
	　　　　　　海伦&middot;亨特 Helen Hunt ....Betty Ann Fitzgerald<br />
	<br />
	<br />
	<br />
	◎简　　介<br />
	<br />
	　　伍迪艾伦带你回到四○年代，他在片中饰演保险公司调查员，和海伦杭特饰演的效率专家，是彼此看不顺眼的同事，却因为一次催眠的关系而慢慢起了化学变化。伍迪艾伦被坏人利用盗宝而不自知，结果自己查自己，成了棘手案件的头号嫌疑犯，更夸张的是他竟然爱上了恨之入骨的海伦杭特。伍迪艾伦不仅纯熟地把玩怀旧的类型游戏，也利用催眠释放了人们压抑的爱情欲望与犯罪欲念，展现高明的戏谑功力。</p>
<p>
	<img alt="" src="http://img165.poco.cn/mypoco/myphoto/20111010/14/62564813201110101423342775756236422_002.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img165.poco.cn/mypoco/myphoto/20111010/14/62564813201110101423342775756236422_001.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img165.poco.cn/mypoco/myphoto/20111010/14/62564813201110101423342775756236422_000.jpg" style="width: 720px; height: 405px" /><br />
	<br />
	<br />
	&nbsp;</p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="&#13;&#10;ftp://dy125:piaohua@dy125.piaohua.com:6089/飘花电影piaohua.com玉蝎子的魔咒BD中字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:6089/飘花电影piaohua.com玉蝎子的魔咒BD中字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O16030V0-11347.jpg{/dede:field}
