{dede:field name='keywords'}地心末日/地心浩劫/地心抢险记迅{/dede:field}
{dede:field name='description'}地心末日/地心浩劫/地心抢险记迅雷下载、免费下载，地心末日/地心浩劫/地心抢险记Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}地心末日/地心浩劫/地心抢险记{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2008-09-22{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://3e:1001@xl2.eee4.com:1001/[3E迅雷电影站www.eee4.com]地心末日DVD中英双字CD1.rmvb" target=_blank>ftftp://3e:1001@xl2.eee4.com:1001/[3E迅雷电影站www.eee4.com]地心末日DVD中英双字CD1.rmvb</A></TD></TR></TBODY></TABLE>CD2：<BR>
<TABLE style="BORDER-RIGHT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; BORDER-BOTTOM: #cccccc 1px dotted" cellSpacing=0 cellPadding=6 width="95%" align=center border=0>
<TBODY>
<TR>
<TD style="WORD-WRAP: break-word" bgColor=#fdfddf><ANCHOR></ANCHOR><A href="ftftp://3e:1001@xl2.eee4.com:1001/[3E迅雷电影站www.eee4.com]地心末日DVD中英双字CD2.rmvb" target=_blank>ftftp://3e:1001@xl2.eee4.com:1001/[3E迅雷电影站www.eee4.com]地心末日DVD中英双字CD2.rmvb</A></TD></TR></TBODY></TABLE>CD3：<BR>
<TABLE style="BORDER-RIGHT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; BORDER-BOTTOM: #cccccc 1px dotted" cellSpacing=0 cellPadding=6 width="95%" align=center border=0>
<TBODY>
<TR>
<TD style="WORD-WRAP: break-word" bgColor=#fdfddf><ANCHOR></ANCHOR><A href="ftftp://3e:1001@xl2.eee4.com:1001/[3E迅雷电影站www.eee4.com]地心末日DVD中英双字CD3.rmvb" target=_blank>ftftp://3e:1001@xl2.eee4.com:1001/[3E迅雷电影站www.eee4.com]地心末日DVD中英双字CD3.rmvb</A></TD></TR></TBODY></TABLE></div><ul class="mmlist{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MPUE30-5L23.jpg{/dede:field}
