{dede:field name='keywords'}惊爆十三天/惊爆13天BD1280高清{/dede:field}
{dede:field name='description'}惊爆十三天/惊爆13天BD1280高清中字迅雷下载、免费下载，惊爆十三天/惊爆13天BD1280高清中字Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}惊爆十三天/惊爆13天BD1280高清中字{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-10{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120508/23/17870980201205082310021573325782264_012.jpg" style="width: 413px; height: 499px" /></p>
<p>
	◎译　　名　惊爆十三天/惊爆13天/惊天13日<br />
	◎片　　名　Thirteen Days<br />
	◎年　　代　2000<br />
	◎国　　家　美国<br />
	◎类　　别　剧情/历史/惊悚<br />
	◎语　　言　英语/俄语/西班牙语/罗马尼亚语<br />
	◎字　　幕　N/A<br />
	◎IMDB评分 7.2/10 (28,990 votes)<br />
	◎IMDB链接 <a href="http://www.xiaozhizhu.net/" target="_blank">http://www.imdb.com/title/tt0146309/</a><br />
	◎文件格式 x264 + DTS<br />
	◎视频尺寸　1280 x 696<br />
	◎文件大小　1.5 DVD<br />
	◎片　　长　02:25:33<br />
	◎导　　演　罗杰&middot;唐纳森 Roger Donaldson<br />
	◎主　　演　凯文&middot;科斯特纳 Kevin Costner ....Kenny O&#39;Donnell, Special Assistant to the President<br />
	　　　　　　布鲁斯&middot;格林伍德 Bruce Greenwood ....President John F. Kennedy<br />
	　　　　　　斯蒂文&middot;卡普 Steven Culp ....Atty. Gen. Robert F. Kennedy<br />
	　　　　　　迪伦&middot;贝克 Dylan Baker ....Robert McNamara, Secretary of Defense<br />
	　　　　　　迈克尔&middot;费尔曼 Michael Fairman ....Adlai Stevenson, US Ambassador to the UN<br />
	◎简　　介　<br />
	<br />
	　　古巴飞弹危机是发生于1962年10月14日，美国U2轰炸机发现苏联，在距离佛罗里达不到150公里的古巴境内部署核子飞弹，这些飞弹能够瞄准全美各大都市并且造成重大伤亡，这项消息当然立刻震惊华府。美、苏两强的对峙，情势也急遽升高，核战危机一触即发。<br />
	<br />
	　　一边是苏联极具挑釁的行动；而华府内部的声音，主战的鹰派要蛮干决一死战，也叫总统甘乃迪头痛不已。全世界最危险的13天，甘乃迪总统和他的幕僚该如何用勇气和智慧化解这一场危机呢？<br />
	<br />
	一句话评论<br />
	<br />
	You&#39;ll Never Believe How Close We Came<br />
	<br />
	幕后制作<br />
	<br />
	　　影片描写美国总统肯尼迪和其弟罗伯特应付这场危机的整个过程，包括跟苏联的台前幕后交易以及跟保守党的抗争。影片叙事性强，条理清晰，悬念叠起。寇斯特纳扮演总统的心腹。<br />
	&nbsp;</p>
<p>
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120508/23/17870980201205082310021573325782264_005.jpg" style="width: 640px; height: 360px" /></p>
<p>
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120508/23/17870980201205082310021573325782264_003.jpg" style="width: 640px; height: 360px" /></p>
<p>
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120508/23/17870980201205082310021573325782264_002.jpg" style="width: 640px; height: 360px" /><br />
	&nbsp;</p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.net/movie/33434.html" target="_blank">http://www.xiaozhizhu.net/movie/33434.html</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy241:piaohua@117.41.229.29:2009/飘花电影piaohua.com惊爆十三天BD1280高清中字.rmvb">ftp://dy241:piaohua@117.41.229.29:2009/飘花电影piaohua.com惊爆十三天BD1280高清中字.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15aBF-3M95.jpg{/dede:field}
