<?php
$z[0]=Array("field","虎口脱险[BD国语中字1024x576高",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","虎口脱险[BD国语中字1024x576高清版]迅雷下载、免费下载，虎口脱险[BD国语中字1024x576高清版]Gvod高清在线播放，剧情介绍等。",72,234);
$z[1][4]['name']="description";
$z[2]=Array("field","虎口脱险[BD国语中字1024x576高清版]",236,308);
$z[2][4]['name']="title";
$z[3]=Array("field","",310,349);
$z[3][4]['name']="writer";
$z[4]=Array("field","",351,390);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-05-17",392,442);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",444,481);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://4e:4e@d8.3edyy.com:157/【3E电影院www.eee4.cc】虎口脱险BD国语中字1024x576高清版.rmvb\" \r\n\r\ntarget=\"_blank",483,631);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MP61620-34092.jpg",633,716);
$z[8][4]['name']="litpic";

?>