{dede:field name='keywords'}TT3D:触摸极限BD中英双字1280高{/dede:field}
{dede:field name='description'}TT3D:触摸极限BD中英双字1280高清2011纪录片迅雷下载、免费下载，TT3D:触摸极限BD中英双字1280高清2011纪录片Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}TT3D:触摸极限BD中英双字1280高清2011纪录片{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-12-11{/dede:field}
{dede:field name='body'}<p>
	<img alt="" height="773" src="/uploads/allimg/c120524/133N4933H20-231c8.jpg" style="cursor: pointer" width="600" /><br />
	<br />
	【影片原名】TT3D: Closer to the Edge<br />
	【中文译名】TT3D:触摸极限<br />
	【出品年代】2011 年<br />
	【IMDB评分】8.2/10 (742 votes)<br />
	【国　　家】英国<br />
	【类　　别】纪录片<br />
	【文件格式】Rmvb<br />
	【文件大小】1.17 GB<br />
	【视频尺寸】1280 x 720<br />
	【影片长度】103 Mins<br />
	【对白语言】英语<br />
	【字幕语言】中英双字幕<br />
	【导　　演】Richard De Aragues<br />
	【主　　演】杰瑞德&middot;莱托 Jared Leto ....Narrator (voice)<br />
	　　　　　　Guy Martin ....Himself<br />
	　　　　　　Ian Hutchinson ....Himself<br />
	　　　　　　John McGuinness ....Himself<br />
	　　　　　　Michael Dunlop ....Himself<br />
	　　　　　　Keith Amor ....Himself<br />
	<br />
	【内容简介】<br />
	<br />
	　　欧洲的低调纪录片《TT3D：触摸极限》讲述极速摩托车界的真实故事，以主观视角拍摄的亡命赛事－－英国曼岛TT摩托车大赛，任何形式关于世界赛车运动影像的巅峰之作！观众观看时都要戴上专制的赛车头盔（配套3D眼镜），且至少看两遍以上，头一遍可感受亲自作为赛车手的彪速刺激，第二遍领略沿途的美丽风光。<br />
	<br />
	　　曼岛赛是世界三大TT赛中唯一没有奖金的，也是历史最悠久与最危险的（平均一年死一人），绝对是勇敢者的游戏。同时又是机车赛最长的封闭赛道，也是风景最优美的。有许多个人身份与小品牌厂商参赛，偶而也会有老车游行。<br />
	<br />
	　　人岛TT The Isle of Man TT<br />
	<br />
	　　人岛位於英格兰和爱尔兰之间的小岛，人岛TT赛在每年6月份在这岛上举行。比赛的赛道是围绕岛外围的公路，全长60公里，弯位有200个以上，是全世界最长的赛道。赛道穿过市街地、山路等，十分多元化。由於比赛的时间十分长，参赛者的耐力和集中力相当重要。世界知名的人岛TT摩托车赛自1907年首届在人岛举办(比MOTOGP要早很多).<br />
	<br />
	　　曼岛TT摩托车大赛可以称为世上最搏命的赛车比赛<br />
	<br />
	　　曼岛的赛车历史可追朔到1904年的汽车比赛，当时是只有限制汽车才能参加的比赛，而在2轮世界中著名的曼岛TT则是在1907开始的，曼岛位於英格兰和爱尔兰之间的小岛，曼岛TT赛事每年都会在这岛上举行。比赛的赛道是围绕曼岛外围的公路，全长共60公里，弯道约有226个，是全世界最长的赛道。赛道穿过市街地、山路等，十分多元化，由於比赛的时间很长，赛道的挑战性更是赛车界属一属二的，因此参赛者的耐力和集中力相当重要。因为赛道的挑战难度很高，所以也发生了许多的伤亡意外事故，累计从1907年开跑到现在(2007年)，共有224位车手不幸丧生，而这数据中还包括了一些因为利益关系被杀害的车手人数。不过由於整个赛事的可看性非常高，因此每年都吸引了世界各国的车迷来到这个小岛，观赏世界著名的曼岛TT(The Isle of Man TT)赛事。<br />
	<br />
	　　曼岛TT的速度目前是由纽西兰车手Bruce Anstey骑著改装的GSX-R1000赛车，在进行Superbik级别赛事的时候所创下的206英哩 (331.5公里/小时)，这项纪录是在Sulby Straight的一英哩长直线跑出来的.<br />
	<br />
	【影片截图】<br />
	<br />
	<img alt="" height="337" src="/uploads/allimg/c120524/133N4933U60-242K1.jpg" style="cursor: pointer" width="600" /><br />
	<img alt="" height="337" src="/uploads/allimg/c120524/133N49339360-255211.jpg" style="cursor: pointer" width="600" /><br />
	<img alt="" height="337" src="/uploads/allimg/c120524/133N49340310-2Da9.jpg" style="cursor: pointer" width="600" /><br />
	[下载地址]： &nbsp;<img border="0" src="/uploads/allimg/c120524/133N2Z4FF-102231.jpg" /></p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:2304/飘花电影piaohua.comTT3D触摸极限BD中英双字1280高清2011纪录片.rmvb </td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120524/133N493410Z-2JO4.jpg{/dede:field}
