<?php
$z[0]=Array("field","快乐大脚/快乐的大脚/欢乐的大脚",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","快乐大脚/快乐的大脚/欢乐的大脚BD国语配音中字1280高清迅雷下载、免费下载，快乐大脚/快乐的大脚/欢乐的大脚BD国语配音中字1280高清Gvod高清在线播放，剧情介绍等。",73,271);
$z[1][4]['name']="description";
$z[2]=Array("field","快乐大脚/快乐的大脚/欢乐的大脚BD国语配音中字1280高清",273,363);
$z[2][4]['name']="title";
$z[3]=Array("field","",365,404);
$z[3][4]['name']="writer";
$z[4]=Array("field","",406,445);
$z[4][4]['name']="source";
$z[5]=Array("field","2012-01-18",447,497);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",499,536);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://d22:d22@dm.eee4.com:1205/[3E电影站www.eee4.com]快乐的大脚DVD中英双字CD1.rmvb\" target=\"_blank",538,675);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MQ092360-3CY.jpg",677,759);
$z[8][4]['name']="litpic";

?>