{dede:field name='keywords'}畅销书[DVD中字]迅雷下载，免费{/dede:field}
{dede:field name='description'}畅销书[DVD中字]迅雷下载、免费下载，畅销书[DVD中字]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}畅销书[DVD中字]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2010-07-12{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://3e:3e@d8.3edyy.com:170/【3E电影院www.eee4.cc】畅销书.rmvb" target="_blank{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MP31XP-12964.jpg{/dede:field}
