<?php
$z[0]=Array("field","科学小怪蛋/伊戈尔/异想天开BD中",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","科学小怪蛋/伊戈尔/异想天开BD中英双字1024/1280高清迅雷下载、免费下载，科学小怪蛋/伊戈尔/异想天开BD中英双字1024/1280高清Gvod高清在线播放，剧情介绍等。",73,265);
$z[1][4]['name']="description";
$z[2]=Array("field","科学小怪蛋/伊戈尔/异想天开BD中英双字1024/1280高清",267,354);
$z[2][4]['name']="title";
$z[3]=Array("field","",356,395);
$z[3][4]['name']="writer";
$z[4]=Array("field","",397,436);
$z[4][4]['name']="source";
$z[5]=Array("field","2012-04-30",438,488);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",490,527);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://e20:e20@xl2.eee4.com:9916/[3E电影站www.eee4.com]科学小怪蛋BD中英双字高清版.rmvb\" target=\"_blank",529,669);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MO5AS0-2W55.jpg",671,752);
$z[8][4]['name']="litpic";

?>