{dede:field name='keywords'}科学小怪蛋/伊戈尔/异想天开BD中{/dede:field}
{dede:field name='description'}科学小怪蛋/伊戈尔/异想天开BD中英双字1024/1280高清迅雷下载、免费下载，科学小怪蛋/伊戈尔/异想天开BD中英双字1024/1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}科学小怪蛋/伊戈尔/异想天开BD中英双字1024/1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-04-30{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://e20:e20@xl2.eee4.com:9916/[3E电影站www.eee4.com]科学小怪蛋BD中英双字高清版.rmvb" target="_blank{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MO5AS0-2W55.jpg{/dede:field}
