{dede:field name='keywords'}怒海争锋：极地远征1280高清迅雷{/dede:field}
{dede:field name='description'}怒海争锋：极地远征1280高清迅雷下载、免费下载，怒海争锋：极地远征1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}怒海争锋：极地远征1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-02-05{/dede:field}
{dede:field name='body'}<p>
	<img src="http://i0.6.cn/tu.6.cn/1f/dc/30/9e782e9c8761c50008b6d563fe163441.jpg" /></p>
<p>
	<br />
	【中文译名】《怒海争锋/怒海争锋：极地远征》美国超级火暴战争动作大片<br />
	【片　　名】Master and Commander<br />
	【年　　代】2003<br />
	【国　　家】美国<br />
	【类　　别】动作/冒险/剧情/战争<br />
	【语　　言】英语<br />
	【字　　幕】中文/英文<br />
	【IMDB评分】7.5/10 (29,706 votes)<br />
	【视频尺寸】1024 x 576<br />
	【电影整理】3E迅雷电影下载站(www.eee4.com)<br />
	【文件大小】3CD 530MB<br />
	【片　　长】02:18:21<br />
	【导　　演】彼得&middot;威尔Peter Weir<br />
	【主　　演】拉塞尔&middot;克劳 Russell Crowe .... Capt. Jack Aubrey<br />
	　　　　　　保罗&middot;贝塔尼 Paul Bettany .... Dr. Stephen Maturin, Surgeon<br />
	　　　　　　James D&#39;Arcy .... 1st Lt. Tom Pullings<br />
	　　　　　　Edward Woodall .... 2nd Lt. William Mowett<br />
	　　　　　　Chris Larkin .... Capt. Howard, Royal Marines<br />
	　　　　　　Max Pirkis .... Blakeney, Midshipman<br />
	　　　　　　Jack Randall .... Boyle, Midshipman<br />
	　　　　　　Max Benitz .... Calamy, Midshipman<br />
	　　　　　　Lee Ingleby .... Hollom, Midshipman<br />
	　　　　　　Richard Pates .... Williamson, Midshipman<br />
	　　　　　　Robert Pugh .... Mr. Allen, Master<br />
	　　　　　　理查德&middot;迈克卡比 Richard McCabe .... Mr. Higgins, Surgeon&#39;s Mate<br />
	　　　　　　Ian Mercer .... Mr. Hollar, Boatswain<br />
	　　　　　　Tony Dolan .... Mr. Lamb, Carpenter<br />
	　　　　　　David Threlfall .... Preserved Killick, Captain&#39;s Steward<br />
	　<br />
	【剧情简介】：</p>
<p>
	　　故事发生在1812年，当时的法国正处在拿破仑战役时代，为了扩张自己的海上霸权，法国人的战舰频频发动战争。号称&ldquo;幸运船长&rdquo;的杰克&middot;奥伯瑞(罗素&middot;克洛)，是英军新任的舰长，他结识了外科军医斯蒂芬&middot;马突林之后，邀请对方和他一起同船出海，做第一次远征，探索世界的奥秘和无尽的财富。<br />
	　　年轻气盛的杰克行事素来强悍，踏上海洋征途后，一路带着船员经受了海上风暴的考验，更多次沿途痛打法国和西班牙的战舰。这两个国家的海军强权势力勾结在一起，企图把杰克和他的&ldquo;奇迹&rdquo;号赶尽杀绝。<br />
	　　就在船在开往巴西的时候，杰克他们遭到西班牙大型炮舰的猛烈攻击，由于对方武器实在太先进了，&ldquo;奇迹&rdquo;遭到了重创。更让人担心的是，杰克不仅要对抗西班牙战舰的追击，还要面临意见不一的军医斯蒂芬为争权而引发的内讧。<br />
	　　为了捍卫国家的尊严，更为了取得战争胜利的先机，杰克做出了一项非常冒险的决定，不再躲避追击，而是异守为攻，穿越大西洋和太平洋两大洋，去追踪重创他们的敌舰，与对方展开殊死一搏。这样一来，不仅国家的命运和荣誉悬于一线，所有船员更有可能全部陷入有去无回的境地。<br />
	　　在弥漫着硝烟与炮声的冒险旅程中，杰克见识到了一个他前所未見的新世界。最后，一个由勇气缔造的奇迹，从不可思议的想法变成了名垂青史的现实，他们成功地虏获了全部敌人&hellip;&hellip;&nbsp;&nbsp;</p>
<p>
	<br />
	【影片幕后】：<br />
	　　《怒海争锋：极地远征》是根据畅销小说改编的，英文的原名直译过来是《主人与指挥官：世界的另一端》。从1969年开始，作者派翠克&middot;欧布莱恩就用杰克&middot;奥伯瑞船长为主角创作系列小说《主人与指挥官》，一共有20部。《怒海争锋：极地远征》采用的是这个系列中的第10部中记录的一场发生在拿破仑时代的真实故事，这场战争也是历史上以少胜多的典范。<br />
	　　本片导演彼得&middot;威尔，多年前一部《绿卡》让他成为了影坛家喻户晓的人物，《楚门的世界》更引发出人们对传媒道德的深思。对于情感戏的细腻把握一直是他的强项，因此，在处理文戏与武戏的结合点时，他自然把影片的核心落在了前者，所有火爆、刺激的战争打斗场面，都是作为情绪的一种延伸和衬托。<br />
	　　福克斯公司为这部影片所作的投资创出了历史新高，拍摄成本高达1.35亿美元。最初计划采用实景拍摄，终因预算实在太庞大而作罢，改在墨西哥北部的巴加摄影棚拍摄，这个摄影棚是20世纪福克斯公司为拍摄影片《泰坦尼克号》所建造的，当年那些水上布景让这次拍摄节省了不少费用。参与影片的特技制作人员，曾经先后参与《魅影奇侠》、《王牌对王牌》、《蜻蜓》等许多影片的特技制作。经过他们的精心设计，在摄影棚内完成的场面惊心动魄，首次在大银幕上再现了19世纪初期海战的盛况，给人带来身临其境的震撼效果。&nbsp;&nbsp;<br />
	　　为了能够加大这部影片的影响与票房，制片方选择了全球同步发行的方式，从11月14日起在世界各地放映。而官方更用多语言方式制作网站，务求让不同地区的观众都能尽早了解到这部史诗作品。曾经有分析家认为，《怒海争锋》一旦成功，很可能引发改编《主人与指挥官》系列小说的热潮，影片公司的花园里从此又要多一颗&ldquo;摇钱树&rdquo;了。</p>

<p>
	【关于演员】：<br />
	　　作为一部海上战争题材的影片，本片的演员阵容中男性占了绝大多数。在该片官方网站的故事介绍前，不仅刻意打出了主演罗素&middot;克洛的奥斯卡影帝头衔，就连导演彼得&middot;威尔三度获得奥斯卡提名的历史，也被翻出来作为宣传噱头。很明显，制片方希望借这部<a href="http://www.3edyy.com/" target="_blank">电影下载</a>影片冲击明年的小金人。首当其冲的自然是一号男主角罗素&middot;克洛，自《美丽心灵》拿下奥斯卡影帝后，克洛再次回归《角斗士》的英雄路线，扮演传奇主人公杰克船长，他在影片中有不少亲自上阵的危险演出，这多少也反映出他本人对再得小金人的渴望。<br />
	　　在《美丽心灵》中，主人公约翰&middot;纳什精神分裂中想象出的室友，曾经给影片增色不少。这个角色的扮演者保罗&middot;贝塔尼此次再次和罗素&middot;克洛携手，在这部年底的大作中扮演戏份吃重的军医斯蒂芬一角，今年才32岁的他前途颇为看好。片中，贝塔尼除了医生身份之外还是秘密间谍，和罗素&middot;克洛扮演的杰克船长由立场相对到惺惺相惜，有不少火花四射的&ldquo;冲突&rdquo;戏。<br />
	　　保罗&middot;贝塔尼出生于英国的戏剧世家，父母都是演员，承继了双亲的艺术天赋的保罗自小便开始登台演出，美国观众熟悉他是从2001年那部《圣战骑士》开始，尽管希思&middot;莱杰是头号男主角，但贝塔尼一出场就抢尽风头，之后的《美丽心灵》虽没像罗素&middot;克洛那样大红大紫，却给他捞到娇妻一名&mdash;&mdash;他把女主角詹妮弗&middot;康纳利娶回了家，今年8月詹妮弗刚刚生下两人的爱情结晶。&nbsp;&nbsp;<br />
	　　和《拯救大兵瑞恩》一样，《怒海争锋》中，不仅主角棱角分明，配角们也是栩栩如生。象优柔寡断的见习官霍伦、杰克的冒失仆人奇里克、感性的诗人莫维、憨直的水手长霍拉等等，都给人留下深刻的印象。尤其是年仅13岁的童星麦克斯&middot;本尼斯(Max Benitz)扮演的见习官，和一众成年演员相比，其清新可爱的表演就象是原著中的主人公复活。</p>

<p>
	【1024 &times; 576分辨率 版本截图】：（点击查看原图）<br />
	<br />
	<a href="http://i3.6.cn/cvbnm/72/04/08/cd53c373729c3a6a7c406be6f5d8b4fe.jpg" target="_blank"><img border="0" src="http://i3.6.cn/cvbnm/72/04/08/cd53c373729c3a6a7c406be6f5d8b4fe.jpg" /></a>&nbsp;<br />
	<a href="http://i3.6.cn/cvbnm/9d/0f/66/767c9ac73af221e946097c45c209a9b7.jpg" target="_blank"><img border="0" src="http://i3.6.cn/cvbnm/9d/0f/66/767c9ac73af221e946097c45c209a9b7.jpg" /></a>&nbsp;<br />
	<a href="http://i3.6.cn/cvbnm/41/a6/d5/d4c8fef3217fdb7dd783508862ec8d0b.jpg" target="_blank"><img border="0" src="http://i3.6.cn/cvbnm/41/a6/d5/d4c8fef3217fdb7dd783508862ec8d0b.jpg" /></a></p>
<br />
<p>
	美国超级火暴战争动作大片《怒海争锋》DVD中英字幕【800 x 336分辨率】－ 来自[3E电影站eee4.com]下载地址：<img border="0" src="/templets/img/down.jpg" /><br />
	CD1：</p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<anchor></anchor><a href="ftp://eee4.com:8077@vip14.eee4.com:8077/怒海争锋/[3E迅雷电影站www.eee4.com]怒海争锋CD1.rmvb" target="_blank">ftp://eee4.com:8077@vip14.eee4.com:8077/怒海争锋/[3E迅雷电影站www.eee4.com]怒海争锋CD1.rmvb</a></td>
		</tr>
	</tbody>
</table>
<p>
	CD2：</p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<anchor></anchor><a href="ftp://eee4.com:8077@vip14.eee4.com:8077/怒海争锋/[3E迅雷电影站www.eee4.com]怒海争锋CD2.rmvb" target="_blank">ftp://eee4.com:8077@vip14.eee4.com:8077/怒海争锋/[3E迅雷电影站www.eee4.com]怒海争锋CD2.rmvb</a></td>
		</tr>
	</tbody>
</table>
<p>
	CD3：</p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<anchor></anchor><a href="ftp://eee4.com:8077@vip14.eee4.com:8077/怒海争锋/[3E迅雷电影站www.eee4.com]怒海争锋CD3.rmvb" target="_blank">ftp://eee4.com:8077@vip14.eee4.com:8077/怒海争锋/[3E迅雷电影站www.eee4.com]怒海争锋CD3.rmvb</a></td>
		</tr>
	</tbody>
</table>
<br />
<p>
	美国超级火暴战争动作大片《怒海争锋》DVD中英字幕【1024 &times; 576分辨率】－来自[3E电影站eee4.cn]：<img border="0" src="/templets/img/down.jpg" /></p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://e73:e73@xl3.eee4.com:1004/[3E电影站www.eee4.com]怒海争锋[DVD中英双字1024x576高清版].rmvb" target="_blank">ftp://e73:e73@xl3.eee4.com:1004/[3E电影站www.eee4.com]怒海争锋[DVD中英双字1024x576高清版].rmvb</a></td>
		</tr>
	</tbody>
</table>
<br />
<p>
	2010/02/19 [下载地址]：<img border="0" src="/templets/img/down.jpg" /><br />
	CD1：</p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://3e:3e@m1.3edyy.com:129/【3E电影院www.3edyy.com】怒海争锋：极地远征BD中英双字1024x576高清版CD1.rmvb" target="_blank">ftp://3e:3e@m1.3edyy.com:129/【3E电影院www.3edyy.com】怒海争锋：极地远征BD中英双字1024x576高清版CD1.rmvb</a></td>
		</tr>
	</tbody>
</table>
<p>
	CD2：</p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://3e:3e@m1.3edyy.com:129/【3E电影院www.3edyy.com】怒海争锋：极地远征BD中英双字1024x576高清版CD2.rmvb" target="_blank">ftp://3e:3e@m1.3edyy.com:129/【3E电影院www.3edyy.com】怒海争锋：极地远征BD中英双字1024x576高清版CD2.rmvb</a></td>
		</tr>
	</tbody>
</table>
<p>
	CD3：</p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://3e:3e@m1.3edyy.com:129/【3E电影院www.3edyy.com】怒海争锋：极地远征BD中英双字1024x576高清版CD3.rmvb" target="_blank">ftp://3e:3e@m1.3edyy.com:129/【3E电影院www.3edyy.com】怒海争锋：极地远征BD中英双字1024x576高清版CD3.rmvb</a></td>
		</tr>
	</tbody>
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="&#13;&#10;ftp://dy125:piaohua@dy125.piaohua.com:7568/飘花电影piaohua.com怒海争锋BD中字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:7568/飘花电影piaohua.com怒海争锋BD中字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O151562Z-55039.jpg{/dede:field}
