{dede:field name='keywords'}非常小特务4BD中英双字1024/1280{/dede:field}
{dede:field name='description'}非常小特务4BD中英双字1024/1280高清2011动作科幻迅雷下载、免费下载，非常小特务4BD中英双字1024/1280高清2011动作科幻Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}非常小特务4BD中英双字1024/1280高清2011动作科幻{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-03-10{/dede:field}
{dede:field name='body'}<p>
	<img alt="" border="0" src="http://img.album.pchome.net/54/84/49/21/b9cf1882b88382ed32b5b0a2492f41e2.jpg" /></p>

<p>
	◎译　　名　非常小特务4/特工神童4/非常小特务决战锁时狂魔4D(港)<br />
	◎片　　名　Spy Kids All the Time in the World<br />
	◎年　　代　2011<br />
	◎国　　家　美国<br />
	◎类　　别　动作/冒险/喜剧/家庭/科幻<br />
	◎语　　言　英语<br />
	◎字　　幕　中英双字<br />
	◎IMDB评分 2.8/10 (2，761 votes)<br />
	◎文件格式　BD-RMVB<br />
	◎视频尺寸　1024 x 576<br />
	◎文件大小　1CD<br />
	◎片　　长　87 Mins<br />
	◎导　　演　罗伯特&middot;罗德里格兹 Robert Rodriguez<br />
	◎主　　演　杰西卡&middot;阿尔芭 Jessica Alba ....Marissa Wilson<br />
	　　　　　　乔尔&middot;麦克哈尔 Joel McHale ....Wilbur Wilson<br />
	　　　　　　杰里米&middot;皮文 Jeremy Piven<br />
	　　　　　　Rowan Blanchard ....Rebecca WilsonMason<br />
	　　　　　　Cook ....Cecil Wilson<br />
	　　　　　　阿丽夏&middot;维加 Alexa Vega ....Carmen Cortez<br />
	　　　　　　达里尔&middot;沙巴拉 Daryl Sabara ....Juni Cortez<br />
	　　　　　　丹尼&middot;特乔 Danny Trejo ....Uncle Machete<br />
	　　　　　　Belle Solorzano ....Spy Baby<br />
	　　　　　　Genny Solorzano ....Spy Baby<br />
	　　　　　　瑞奇&middot;热维斯 Ricky Gervais<br />
	<br />
	◎简　　介　<br />
	<br />
	　　一转眼，距离《非常小特务3》已经过去了7年的时间。《非常小特务4》是对旧系列的重新诠释，阿尔芭饰演一个被重新起用的退休间谍，有一个小宝宝，还带着两个十来岁的继子女一起生活。这两个大孩子就是新的&ldquo;特务&rdquo;。她们将合力对付一个号称时间守护者的恶棍(杰里米&middot;皮文饰)，他的目标是让时间停滞不前。<br />
	<br />
	幕后制作<br />
	<br />
	　　罗德里格兹在拍摄《弯刀》的时候，就开始构思《特工神童》第四部的故事。这一回，罗德里格兹结束了与安东尼奥&middot;班德拉斯和卡拉&middot;古奇诺长达三部的合作，请来曾在《罪恶之城》中有过亮眼表现的女星杰西卡&middot;阿尔巴担任电影的女主角。因为正是杰西卡给了他故事的灵感。当时，杰西卡刚好抱着自己一岁的大女儿奥娜&middot;玛丽&middot;华伦出现在《弯刀》的片场，并且遭遇了奥娜的尿布&ldquo;爆炸&rdquo;事件。看着杰西卡细心地为女儿换尿布，并防止脏东西粘到身上的样子，罗德里格兹就想&ldquo;为何不拍一个间谍妈妈的故事&rdquo;。于是，在2009年9月25日，距离上一部《特工神童》电影下载六年之后，这个系列最新一部的电影宣布开拍。<br />
	<br />
	　　对于再次启动这个系列，并彻底更换了演员班底，罗德里格兹自有想法：&ldquo;我觉得我不得不启动这个新片计划，尤其是为了那些没有看过这个系列的观众。为了配合时代的发展，我们会有一个全新的家庭，不过他们依然会和过去的家庭有所联系，这是为那些老影迷而特意设计的，希望能尽可能减少更换班底带来的情感落差。对我来说这倒是很有趣，找出哪些是为老影迷设计的，哪些是为新影迷设计的。说到最难的部分，应该是那些稀奇古怪的小器械，因为我已经在前三部里实现了许多构想，感觉像是用完了所有脑子里有趣的东西。&rdquo;说到自《杀人三部曲》的暴力美学系列后这个轻松愉快的系列片，罗德里格兹表示这其实是意料之外的产物。当他做第一部的时候，由于剧本包含了太多的东西，他不得不把故事分成两部来讲，但是第三部和第四部全都是&ldquo;想都没想过的事儿&rdquo;。做到第四部的时候，他面临的很大挑战来自于&ldquo;如何使这个故事不断升级，就像做终结篇一样来尽力完成它。&rdquo;不过，新片里面还会有一些第一部剧本里的东西&mdash;&mdash;也就是由于预算和时间问题，在前几部里都没能出现的。比如那只非常惹眼的机器狗......<br />
	<br />
	花絮<br />
	<br />
	&middot;《非常小特务4》投资4000万，为四部里投资最高的一作。<br />
	<br />
	&middot;2001年到2003年，《非常小特务》连续三年拍摄三部，而第四部却相隔前作八年。<br />
	<br />
	&middot;《非常小特务4》是系列首度3D化。<br />
	<br />
	&middot;《非常小特务4》原名《Spy Kids 4: Armageddon》，后来导演罗伯特&middot;罗德里格兹觉得副标题与迈克尔&middot;贝1998年的电影《绝世天劫》同名，而更名为现在的《Spy Kids 4: All the Time in the World》<br />
	<br />
	<img alt="" border="0" src="http://img.album.pchome.net/54/84/49/21/1b741f81877144c5077e7529138b7331.jpg" /><br />
	<img alt="" border="0" src="http://img.album.pchome.net/54/84/49/21/5ee0798e70d36f35c67986829aa09f1f.jpg" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2985/飘花电影piaohua.com非常小特务4BD中英双字1024高清.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:2985/飘花电影piaohua.com非常小特务4BD中英双字1024高清.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2985/飘花电影piaohua.com非常小特务4BD中英双字1024高清.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2985/飘花电影piaohua.com非常小特务4BD中英双字1280高清.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:2985/飘花电影piaohua.com非常小特务4BD中英双字1280高清.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2985/飘花电影piaohua.com非常小特务4BD中英双字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1592F10-35D5.jpg{/dede:field}
