{dede:field name='keywords'}美国派4：美国重逢清晰TS中字201{/dede:field}
{dede:field name='description'}美国派4：美国重逢清晰TS中字2012美国喜剧迅雷下载、免费下载，美国派4：美国重逢清晰TS中字2012美国喜剧Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}美国派4：美国重逢清晰TS中字2012美国喜剧{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-04-20{/dede:field}
{dede:field name='body'}<p>
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120420/15/56643687201204201519463478053130526_006.jpg" /></p>
<p>
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120420/15/56643687201204201519463478053130526_005.jpg" /></p>
<p>
	【影片原名】American Reunion<br />
	【外文别名】&quot;American Pie: Reunion&quot; - Australia (promotional title), Singapore (English title) (alternative title)<br />
	【中文译名】美国派4:美国重逢/美国重逢/美国派4/美国处男之孔雀开屏(港)/美国派:高潮再起(台)<br />
	【出品公司】Universal Pictures<br />
	【出品年代】2012 年<br />
	【上映日期】2012年4月6日 美国<br />
	【影片级别】Canada:18A (Alberta/British Columbia/Manitoba) | USA:R | Canada:14A (Ontario) | Australia:MA15+ | Singapore:M18<br />
	【IMDB链接】<a href="http://www.imdb.com/title/tt1605630/">http://www.imdb.com/title/tt1605630/</a><br />
	【IMDB评分】7.3/10 (1,537 votes)<br />
	【国　　家】美国<br />
	【类　　别】喜剧<br />
	【导　　演】乔恩&middot;赫维兹 Jon Hurwitz<br />
	　　　　　　海登&middot;施拉兹伯格 Hayden Schlossberg<br />
	【主　　演】贾森&middot;比格斯 Jason Biggs ....Jim<br />
	　　　　　　艾丽森&middot;汉妮根 Alyson Hannigan ....Michelle Flaherty-Levenstein<br />
	　　　　　　西恩&middot;威廉&middot;斯科特 Seann William Scott ....Steve Stifler<br />
	　　　　　　米娜&middot;苏瓦丽 Mena Suvari ....Heather<br />
	　　　　　　莎诺&middot;伊丽莎白 Shannon Elizabeth ....Nadia<br />
	　　　　　　卡特里娜&middot;宝登 Katrina Bowden ....Mia<br />
	　　　　　　约翰&middot;赵 John Cho ....MILF Guy #2<br />
	　　　　　　塔拉&middot;雷德 Tara Reid ....Vicky Lathum<br />
	　　　　　　詹妮佛&middot;库里奇 Jennifer Coolidge ....Stifler&#39;s Mom<br />
	　　　　　　克里斯&middot;克莱因 Chris Klein ....Oz<br />
	　　　　　　娜塔莎&middot;雷昂 Natasha Lyonne ....Jessica<br />
	　　　　　　丹妮亚&middot;拉米雷兹 Dania Ramirez ....Selena<br />
	　　　　　　尤金&middot;列维 Eugene Levy ....Jim&#39;s Dad<br />
	　　　　　　艾迪&middot;凯伊&middot;托马斯 Eddie Kaye Thomas ....Finch<br />
	　　　　　　托马斯&middot;伊恩&middot;尼古拉斯 Thomas Ian Nicholas ....Kevin Myers</p>
<p>
	【文件格式】清晰TS-RMVB<br />
	【文件大小】1CD 458MB<br />
	【视频尺寸】720 x 288<br />
	【影片长度】90 Mins<br />
	【对白语言】英语<br />
	【字幕语言】中文<br />
	【内容简介】</p>
<p>
	在《美国派4》中,老友们将因为高中同学会而重聚,在这个难得的周末假期,他们将发现彼此的变化和没有改变的品性,也证明了距离不会打破他们的友谊。1999年的夏天,四个高中生吉姆(Jim)、凯文(Kevin)、芬奇(Finch)和欧兹(Oz)约好在毕业舞会当晚要告别他们的处男生涯。这么多年过去了,吉姆和米歇尔结了婚,凯文和薇姬已经分手,芬奇依旧对Stifler的母亲充满渴望。如今几位老友聚在一起,共同追忆他们那充满荷尔蒙气味的搞笑时代。</p>
<p>
	幕后制作</p>
<p>
	　　重返美国派</p>
<p>
	　　自从《美国派》系列电影成为了流行文化的一部以来,影片的制片人查尔斯&middot;摩尔等人就一直希望能用一种另外的方式,去带领观众重新回到&ldquo;美国派的世界里&rdquo;,去看一看当年还是高中生的那群主角,如今的生活。查尔斯&middot;摩尔说:&ldquo;六年前,我开始去环球公司放映《美国派》,每6个月或者是9个月放映一次。后来,我就萌生了要拍摄《美国重聚》的想法,让人们看看当年的那些人,现在的生活是什么样子。制片方很同意我的想法,给我们开了绿灯。&rdquo;&ldquo;这样的影片,其魅力一直在增加,&rdquo;影片的制片人克雷格&middot;佩里说:&ldquo;人们会从中发现自己生活的片段,自己的过往和自己的影子。所以,《美国派》能聚集到越来越多的粉丝,越来越多的受众群体。&rdquo;</p>
<p>
	《美国派4》拍摄于2012年,这时候距离《美国派3》的上映已经过去了几乎10年时间。这十年时间里,贾森&middot;比格斯、艾丽森&middot;汉妮根和西恩&middot;威廉&middot;斯科特这样的主角基本都在好莱坞开创了自己的事业,他们有时间来参演《美国派4》么?环球同意拍摄《美国派4》,有一个附加条件,那就是要让所有的原版电影的演员回到剧组。查尔斯&middot;摩尔说:&ldquo;把那些演员都找回来,这的确是有难度的,因为时间已经很久远了,而且这些演员也未必会愿意回来拍摄这第三部续集。&rdquo;幸运的是,《美国派》的影响力在过去是十几年时间里有增无减。而且,这些年的《宿醉》、《伴娘》等R级喜剧再次掀起了R级性喜剧的热潮。而作为该种喜剧的&ldquo;前辈&rdquo;,《美国派》系列总是会被人拿出来讨论和研究。在这样的背景之下,原版演员也乐意回来重新扮演一遍自己已经扮演了三遍的角色。查尔斯&middot;摩尔说:&ldquo;这些角色第一次登上银幕的时候,他们的形象就已经被固定了下来,观众就认可了他们。换人来扮演这样的角色,显然是不明智的。所幸的是,原版的演员都很愿意回来出演这部电影,这令我们很感动。因为爱着这部电影的,不止是观众,还有这些演员。&rdquo;贾森&middot;比格斯说:&ldquo;能回到《美国派4》是一件很棒的事情,因为这套电影承载了太多的我们的故事。回到了片场,我就好像回到了自己的青葱岁月,那些发生在片场和生活里的事情还是历历在目。&rdquo;</p>
<p>
	　　依然是R级喜剧</p>
<p>
	如果要把《美国派4》拍摄成当下流行的PG-13级喜剧的话,可能全世界的影迷都会不高兴了。因为R级,是《美国派》系列的招牌,也是这套性喜剧电影的赖以生存的法宝。那么,找到合适的、而且愿意拍摄这部电影的编导,就成为了关键。好在,《美国派》系列的粉丝遍布全美,环球公司很快就找到了乔恩&middot;赫维兹和海登&middot;施拉兹伯格前来编写剧本,并执导电影。熟悉美国R级喜剧的人,对这两位电影不会陌生,就是他们编写出了《寻堡奇遇》系列的剧本,而且还指导来了第二部。对于这个任务,这两位常年混迹在R级喜剧里的电影自信满满。</p>
<p>
	　　对于影片的R级,海登&middot;施拉兹伯格说:&ldquo;现在有很多关于年轻人故事的喜剧,都是PG-13级的,这看起来很没有意思。我和赫维兹一直以来都很喜欢那种犀利、直接、过瘾的喜剧。《美国派》,对于我们这一代人来说,是我们所接触到的第一部标准意义上的性喜剧,那种纯粹的荷尔蒙的味道让我们很是过瘾。我们非常喜欢这个片子。&rdquo;乔恩&middot;赫维兹说:&ldquo;影片里的那些情节,我们在高中也曾经做过。它就好像是我们的一面镜子,我们总是能从中看到自己。所以,在这部电影里,我们还是会回到高中时的感觉,拍摄一部原汁原味,但是绝对与原版电影不同的《美国派》。&rdquo;施拉兹伯格说:&ldquo;我们会在影片里加入很多的小细节,用来怀念以前的《美国派》。但是在这部电影中,主角们都已经成长为成年人了,所以笑料的设置也不会和以前的《美国派》完全一样。如果笑料都一样的话,那么还有什么必要拍这部电影呢?在我和赫维兹编写的剧本中,我们就很重视喜剧效果的展现。总体上来说,这部电影会是一部完全不一样的,但是还带有《美国派》影子的R级喜剧。&rdquo;</p>
<p>
	　　对于影片的笑料,以及和前作的联系,查尔斯&middot;摩尔说:&ldquo;我觉得这两个导演做的很不错,因为我们需要的是一部新的《美国派》,而不是一部全新的电影。他们把以往的笑料加工了之后放在了这部电影中,看上去效果很不错。而且,他们为影片增加了新的笑料和感受。这一切,都使得《美国派4》看起来非常真实而且可信。我觉得,这就是《美国派》系列的魅力所在,它来源于生活本身。也正是因为如此,《美国派》才能从上映之初,一直被人追捧到现在,并成为青春性喜剧的经典。&rdquo;</p>
<p>
	花絮</p>
<p>
	　　&middot;影片的故事发生在2009年,而第一部《美国派》的故事发生在十年前,也就是1999年。</p>
<p>
	　　&middot;前三部中的众主演贾森&middot;比格斯、西恩&middot;威廉&middot;斯科特、尤金&middot;列维、艾丽森&middot;汉妮根等都悉数回归。</p>
<p>
	　　&middot;算上本片,目前一共有八部&ldquo;美国派&rdquo;影片问世,其中05年到09年的四部直接发行了DVD而未在影院上映,它们被官方算为系列中的衍生篇,所以这也是为何此次汇聚前三部众主演的新作被称为《美国派4》的原因,因为这才是正经八百的原作续集。</p>
<p>
	　　&middot;这是米娜&middot;苏瓦丽出演过的第五部片名中带有American(美国)的影片。前四部是《美国派》、《美国派2》、《美国丽人》和《美国处女》。</p>
<p>
	　　&middot;影片在佐治亚拍摄。剧中老友重聚的派对的拍摄地点被选在了科文顿市的牛顿高中。剧组就在该学校的体育场里拍摄了这个情节,使用了200个群众演员。租用这片场地并不是免费的,剧组支付给了当地的教育系统一万美金的租金。</p>
<p>
	　　&middot;为了拍摄一个湖滨的场景,剧组租下了一小块湖滨用于拍摄。一周的租金为2.3万美金。</p>
<p>
	精彩对白</p>
<p>
	　　Steve Stifler: Ladies, you&#39;d better be working hard - you weren&#39;t hired for your looks. Actually you were. Not you.<br />
	　　史蒂夫&middot;斯蒂夫勒:女士们,你们最好卖力些,因为把你们雇来可不是为了当花瓶看的--其实你们都是花瓶,只有你不是。</p>
<p>
	<br />
	◎影片截图</p>

<p>
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120420/15/56643687201204201519463478053130526_001.jpg" /></p>
<p>
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120420/15/56643687201204201519463478053130526_002.jpg" /></p>
<p>
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120420/15/56643687201204201519463478053130526_003.jpg" /></p>
<p>
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120420/15/56643687201204201519463478053130526_000.jpg" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.netftp//dy44:piaohua@dy44.piaohua.com:3142/" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3261/飘花电影piaohua.com美国派4：美国重逢清晰TS中字.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3261/飘花电影piaohua.com美国派4：美国重逢清晰TS中字.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15E1T0-36231.jpg{/dede:field}
