<?php
$z[0]=Array("field","国家地理－迪拜神奇世界岛[DVD中",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","国家地理－迪拜神奇世界岛[DVD中字1024x576高清版]迅雷下载、免费下载，国家地理－迪拜神奇世界岛[DVD中字1024x576高清版]Gvod高清在线播放，剧情介绍等。",73,261);
$z[1][4]['name']="description";
$z[2]=Array("field","国家地理－迪拜神奇世界岛[DVD中字1024x576高清版]",263,348);
$z[2][4]['name']="title";
$z[3]=Array("field","",350,389);
$z[3][4]['name']="writer";
$z[4]=Array("field","",391,430);
$z[4][4]['name']="source";
$z[5]=Array("field","2012-05-22",432,482);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",484,521);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://e19:e19@xl2.eee4.com:9916/[3E电影站www.eee4.com]迪拜神奇世界岛[DVD中字1024x576高清版].rmvb\" target=\"_blank",523,674);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MP4Gc0-33911.jpg",676,758);
$z[8][4]['name']="litpic";

?>