<?php
$z[0]=Array("field","美国往事/四海兄弟/义薄云天[BD",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","美国往事/四海兄弟/义薄云天[BD中英双字1024x576高清版]迅雷下载、免费下载，美国往事/四海兄弟/义薄云天[BD中英双字1024x576高清版]Gvod高清在线播放，剧情介绍等。",72,270);
$z[1][4]['name']="description";
$z[2]=Array("field","美国往事/四海兄弟/义薄云天[BD中英双字1024x576高清版]",272,362);
$z[2][4]['name']="title";
$z[3]=Array("field","",364,403);
$z[3][4]['name']="writer";
$z[4]=Array("field","",405,444);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-01-02",446,496);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",498,535);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://3e:3e@d3.3edyy.com:121/【3E电影院www.eee4.org】美国往事BD中英双字1024x576高清版.rmvb\" target=_blank>ftftp://3e:3e@d3.3edyy.com:121/【3E电影院www.eee4.org】美国往事BD中英双字1024x576高清版.rmvb</A></TD></TR></TBODY></TABLE></div><ul class=\"mmlist",537,827);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MQ3G3Z-523S.jpg",829,910);
$z[8][4]['name']="litpic";

?>