{dede:field name='keywords'}美国往事/四海兄弟/义薄云天[BD{/dede:field}
{dede:field name='description'}美国往事/四海兄弟/义薄云天[BD中英双字1024x576高清版]迅雷下载、免费下载，美国往事/四海兄弟/义薄云天[BD中英双字1024x576高清版]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}美国往事/四海兄弟/义薄云天[BD中英双字1024x576高清版]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-01-02{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://3e:3e@d3.3edyy.com:121/【3E电影院www.eee4.org】美国往事BD中英双字1024x576高清版.rmvb" target=_blank>ftftp://3e:3e@d3.3edyy.com:121/【3E电影院www.eee4.org】美国往事BD中英双字1024x576高清版.rmvb</A></TD></TR></TBODY></TABLE></div><ul class="mmlist{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MQ3G3Z-523S.jpg{/dede:field}
