{dede:field name='keywords'}地火危城/火山爆发/活火熔城迅雷{/dede:field}
{dede:field name='description'}地火危城/火山爆发/活火熔城迅雷下载、免费下载，地火危城/火山爆发/活火熔城Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}地火危城/火山爆发/活火熔城{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2008-02-21{/dede:field}
{dede:field name='body'}<P>【中文译名】《地火危城/火山爆发/活火熔城/火山》<BR>【片　　名】Meet the Spartans<BR>【年　　代】1997年<BR>【国　　家】美国<BR>【类　　别】动作/惊悚/剧情 <BR>【语　　言】英语 <BR>【字　　幕】中文字幕<BR>【视频尺寸】624x336<BR>【电影整理】3E迅雷电影下载站(www.eee4.com)<BR>【文件大小】1CD 399MB<BR>【片　　长】102 Mins<BR>【导　　演】Mick Jackson<BR>【主　　演】汤米.里.琼斯（Tommy Lee Jones） /安妮.海切（Anne Heche）</P>
<P>【剧情简介】：</P>
<P>&nbsp;&nbsp;&nbsp; 一次大地震使深藏在洛杉矶地下深处的火山喷发，炽热的岩浆流向天使之城的人口密集区，眼看一场城毁人亡的悲剧就要发生。担任处理这次危机总指挥的迈克，先是不相信会有火山喷发，后在地质学家埃米博士的劝告下，还是采取了撤离措施。但突如其来的灾难还是在民众中引发极大的恐慌。路上流动的岩浆被堵住了，但它们实际上是流进了隧道，贯入地铁后，还会从地铁的出站口流入城市。迈克采取最后一招：炸毁一栋大楼，迫使岩浆流入大海...... </P>
<P>&nbsp;&nbsp;&nbsp; 都知道洛杉矶是个火热的城市，这不仅仅指它充满娱乐性，原来它根本就坐在一个睡火山上面。当火山苏醒过来，这西岸大都市就倒足了大霉。滚烫的熔岩在地上和地下横冲直撞所向披，何止是如入无人之境，简直要将整个洛杉矶变成无人之境。通过这部电影，许多人第一次知道美国大城市有个“危机处理中心”，那里的官员处变不惊、指挥若定，带领军民齐心协力对付空前大灾难，其间还涌现了许多好人好事。最后美国人一举将熔岩排入了太平洋，过程就好像拉一下抽水马桶那么干脆利落。</P>
<P>&nbsp;&nbsp;&nbsp; 火山爆发，炙热的熔岩喷涌而出，千百万市民惊惶逃亡……，类似好莱坞灾难片的情节，可能在现实生活中重演。英国科学家近日发出警告，位于大西洋东部的加那利群岛的一座危险火山可能喷发，掀起巨大的海啸，直扑美国东海岸人口密集的城市，导致数千万人丧生以及纽约华盛顿这两大都市的毁灭。</P>
<P>&nbsp;&nbsp;&nbsp; 能量等于全美半年所耗电力<BR>&nbsp;&nbsp;&nbsp; 1997年上映的好莱坞大片《活火熔城》的场面可能“活生生”出现在美国东海岸城市。英国《独立报》8月10日报道说，科学家认为位于加那利群岛的康伯利维亚火山确实存在爆发的可能性，若康伯利维亚火山爆发，将会是人类有史以来最毁灭性的灾难。它将激起百米巨浪海啸，令纽约、波士顿、华盛顿及迈阿密等美国东岸城市瞬间消失。</P>
<P>&nbsp;&nbsp;&nbsp; 康伯利维亚火山早在1949年爆发时就引起了科学家的注意，目前这座火山的西侧非常不稳定。康伯利维亚火山一旦爆发，将能撼动近500立方公里大的巨石，巨石冲入海里所释放的能量相当于全美6个月所消耗的电力。整座岛屿将在90秒左右的时间内完全崩塌，并引发巨大的海啸。</P>
<P>&nbsp;&nbsp;&nbsp; 海啸9小时到美国东海岸<BR>&nbsp;&nbsp;&nbsp; 计算机模拟结果显示，灾难一旦发生，高达100米的巨浪首先就将以超过喷气式飞机的速度扑向附近的加拿利群岛岛屿，几小时后到达非洲西海岸。大约在火山爆发后的9至12小时，20米至50米高的巨浪就将涌向加勒比海岛屿以及美国、加拿大的东海岸。届时这些地区的港口将率先受到毁灭性打击，造成的生命以及财产损失将无法估量。英国也不能幸免，火山爆发后的4-5小时左右英国南海岸也将受到10米大浪的袭击，将会对海岸度假胜地以及港口产生影响。</P>
<P>&nbsp;&nbsp;&nbsp; 康伯利维亚火山的板块自1949年火山爆发后以每年一厘米的速度下沉。该火山每隔25至200年爆发一次，而上一次则于1972年爆发。</P>
<P>&nbsp;&nbsp;&nbsp; 无法提前数周测灾难信息<BR>&nbsp;&nbsp;&nbsp; “《活火熔城》现实版”的提出者——伦敦大学学院本菲尔德·格雷风险研究中心主管比尔·麦克贾尔教授说，尽管人们已经在数十年前就意识到了这个潜在的威胁，但是还没有人对这座火山进行适当的、连续性的关注。麦克贾尔指出，用两到三个地震仪或许能够监测到岩石运动情况，但却无法提前数周探测到火山即将喷发的信息。</P>
<P>&nbsp;&nbsp;&nbsp; 科学家呼吁通过国际合作的方式在岛屿上安装更多的传感器，并借助全球卫星定位系统来监测岛上岩石散落海水的速度。</P>
<P>&nbsp;&nbsp;&nbsp; 这样的自然灾难是很罕见的，平均每1万年才会出现一次，但是这座火山爆发的时间将会大大提前，在未来1000年中随时可能再次爆发。科学家说：“据我们所知，这座火山目前正处于运动中。”电影整理：www.eee4.com</P>
<P><IMG alt="" src="http://pic.piaohua.com/0701pic/allimg/080221/0051360.jpg" onload="attachimg(this, 'load')" border=0></P>
<P>【电影截图】：<BR>电影来源：www.eee4.com<BR><IMG alt="" src="http://pic.piaohua.com/0701pic/allimg/080221/0051361.jpg" onload="attachimg(this, 'load')" border=0><BR><IMG alt="" src="http://pic.piaohua.com/0701pic/allimg/080221/0051362.jpg" onload="attachimg(this, 'load')" border=0><BR><IMG alt="" src="http://pic.piaohua.com/0701pic/allimg/080221/0051363.jpg" onload="attachimg(this, 'load')" border=0><BR><IMG alt="" src="http://pic.piaohua.com/0701pic/allimg/080221/0051364.jpg" onload="attachimg(this, 'load')" border=0></P><p>2008-02-21 00:37:12 开始连接......<br>2008-02-21 00:37:14 开始搜索候选资源......<br>2008-02-21 00:37:15 搜索到31个候选资源<br>2008-02-21 00:37:17 使用候选资源进行

连接......<br>2008-02-21 00:37:20 搜索到26个候选资源<br>2008-02-21 00:37:23 使用候选资源进行连接......<br>2008-02-21 00:37:24 文件创建成功，开始下载数

据......<br>2008-02-21 00:37:26 用户取消下载&nbsp;&nbsp; 本文来自 <a href="/index.html" target="_blank">www.eee4.com</a></p>
（直接可能无法下载，一律使用<a href="http://pstatic.xunlei.com/about/product/down_xl5.htm" target="_blank">迅雷下载</a>）<br>
经典灾难大片《活火熔城》DVD中字 － 来自[3E迅雷电影站eee4.com]下载地址：<IMG src="/templets/img/down.jpg" 

border=0><br>
<table style="BORDER-RIGHT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; BORDER-BOTTOM: #cccccc 1px 

dotted" cellspacing="0" cellpadding="6" width="95%" align="center" border="0">
    <tbody>
        <tr>
            <td style="WORD-WRAP: break-word" bgcolor="#fdfddf"><anchor></anchor><a href="ftp://eee4.com:8011@vip6.eee4.com:8011/活火熔城/[3E迅雷电影站www.eee4.com]活火熔城DVD.rmvb" target="_blank">ftp://eee4.com:8011@vip6.eee4.com:8011/活火熔城/[3E迅雷电影站www.eee4.com]活火熔城DVD.rmvb</a></td>
        </tr>
    </tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1A00450-11X6.jpg{/dede:field}
