{dede:field name='keywords'}劲舞团（帅录像）迅雷下载，免费{/dede:field}
{dede:field name='description'}劲舞团（帅录像）迅雷下载、免费下载，劲舞团（帅录像）Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}劲舞团（帅录像）{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2006-08-04{/dede:field}
{dede:field name='body'}<object classid="CLSID:22d6f312-b0f6-11d0-94ab-0080c74c7e95" class="OBJECT" id="MediaPlayer" width="500" height="350" ><param name="ShowStatusBar" value="-1"><param name="Filename" value="mms://video.17173.com/17173_radio/film/wanjia_jw/jw5819.wmv"> 
</embed></object><br /> 
<P>下载地址<BR></P> <br>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120524/133N353DD0-2G248.gif{/dede:field}
