
    {dede:addurls}{/dede:addurls}
    {dede:batchrule}[(#)=>http://www.piaohua.com/html/dongzuo/list_(*).html; (*)=>1-10; typeid=>1] 
[(#)=>http://www.piaohua.com/html/xiju/list_(*).html; (*)=>1-10; typeid=>2] 
[(#)=>http://www.piaohua.com/html/aiqing/list_(*).html; (*)=>1-10; typeid=>3]
[(#)=>http://www.piaohua.com/html/kehuan/list_(*).html; (*)=>1-10; typeid=>4]
[(#)=>http://www.piaohua.com/html/juqing/list_(*).html; (*)=>1-10; typeid=>5]
[(#)=>http://www.piaohua.com/html/xuannian/list_(*).html; (*)=>1-10; typeid=>6]
[(#)=>http://www.piaohua.com/html/wenyi/list_(*).html; (*)=>1-10; typeid=>7]
[(#)=>http://www.piaohua.com/html/zhanzheng/list_(*).html; (*)=>1-10; typeid=>8]
[(#)=>http://www.piaohua.com/html/kongbu/list_(*).html; (*)=>1-10; typeid=>9]
[(#)=>http://www.piaohua.com/html/zainan/list_(*).html; (*)=>1-10; typeid=>10]
[(#)=>http://www.piaohua.com/html/lianxuju/list_(*).html; (*)=>1-10; typeid=>11]
[(#)=>http://www.piaohua.com/html/dongman/list_(*).html; (*)=>1-10; typeid=>12]
[(#)=>http://www.piaohua.com/html/huaijiu/list_(*).html; (*)=>1-10;typeid=>13]
[(#)=>http://www.piaohua.com/html/zongyijiemu/list_(*).html; (*)=>1-10; typeid=>14]
{/dede:batchrule}
    {dede:regxrule}{/dede:regxrule}
    {dede:areastart}{/dede:areastart}
    {dede:areaend}{/dede:areaend}
