{dede:field name='keywords'}捉贼记BD中英双字1280高清希区柯{/dede:field}
{dede:field name='description'}捉贼记BD中英双字1280高清希区柯克经典迅雷下载、免费下载，捉贼记BD中英双字1280高清希区柯克经典Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}捉贼记BD中英双字1280高清希区柯克经典{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-03-01{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img.funshion.com/attachment/images3/49/nosense/2003125132830.6736195.jpg" /></p>
<p>
	【译　　名】　捉贼记<br />
	【片　　名】　To Catch a Thief<br />
	【年　　代】　1955<br />
	【国　　家】　美国<br />
	【字幕语言】 中文/英文<br />
	【视频尺寸】 1280&times;720<br />
	【文件格式】 RMVB+AAC<br />
	【类　　别】　犯罪/神秘/爱情/惊悚<br />
	【语　　言】　英语/法语<br />
	【IMDB评分】&nbsp; &nbsp;7.5/10 (23,041 votes)<br />
	【片　　长】　102 mins<br />
	【导　　演】　阿尔弗雷德&middot;希区柯克 Alfred Hitchcock<br />
	【主　　演】　加里&middot;格兰特 Cary Grant ....John Robie<br />
	　　　　　　格蕾丝&middot;凯利 Grace Kelly ....Frances Stevens<br />
	　　　　　　约翰&middot;威廉姆斯 John Williams ....H. H. Hughson<br />
	　　　　　　查尔斯&middot;文恩 Charles Vanel ....Bertani<br />
	　　　　　　阿尔弗雷德&middot;希区柯克 Alfred Hitchcock ....Man sitting next to John Robie on bus (uncredited)<br />
	　　　　　　洁茜&middot;罗伊丝&middot;兰迪斯 Jessie Royce Landis ....Jessie Stevens<br />
	　　　　　　Brigitte Auber ....Danielle Foussard<br />
	　　　　　　Jean Martinelli ....Foussard<br />
	　　　　　　Georgette Anys ....Germaine<br />
	　　　　　　George Adrian ....Detective (uncredited)<br />
	　　　　　　John Alderson ....Detective at the costume ball (uncredited)<br />
	　<br />
	<br />
	<br />
	【简　　介】<br />
	<br />
	剧情<br />
	<br />
	　　以风景如画的法国Riviera为背景，描写一个重新做人的窃贼，有重操旧业之嫌，并且连女主角的心也一块偷走。深夜，一只黑猫在屋顶上出没；屋子里，一双戴着手套的手正在翻弄着箱子里的珠宝钻石；第二天早上则是丢失珠宝的尖叫声。曾经外号&ldquo;黑猫&rdquo;的约翰?罗比正和心爱的黑猫在自己风景优美的乡间别墅里过着悠闲的生活，曾以偷窃而闻名一时的他，后来在战争中参加了抵抗组织，成为战功赫赫的英雄，早已放弃了偷窃的行当，警察却因为接连的珠宝失窃案找上门来。约翰轻松地摆脱了警察的追踪，决定自己亲自调查是谁用自己的手法做的案&hellip;&hellip;<br />
	<br />
	一句话评论<br />
	<br />
	For a moment he forgets he&#39;s a thief--and she forgets she&#39;s a lady!<br />
	<br />
	格蕾丝&middot;凯莉赋予了人物难以置信的闪亮魅力。<br />
	<br />
	&mdash;&mdash;《阿波罗导报》<br />
	<br />
	幕后制作<br />
	<br />
	　　节奏明快、诙谐风趣的浪漫惊险片，这部希区柯克作品更多的是以幽默元素和浪漫爱情取胜的。项围红丝巾的约翰&middot;罗比，简直就是约翰&middot;韦恩西部游侠的欧洲化身，这个超凡的角色从一开始就得到观众的认可，飞檐走壁如履平地，戏弄警察如戏顽童，悬念已经无可非议地让位给爱情。凯莉在戛纳宣传本片时，结识未来的王子丈夫，嫁入摩纳哥王室。<br />
	<br />
	花絮<br />
	<br />
	&middot;希区柯克曾出现在片中，在巴士上坐在约翰&middot;罗比身边。<br />
	&middot;弗朗西丝的轿车是Sunbeam Marque Talbot Alpine跑车。<br />
	&middot;在罗比同保险业务员交谈的画面中，两人谈到了厨师的手异常灵敏，影片的德语版本与英语版本明显不同。在英语版本中，罗比说她曾悄无声息的用手掐死一名德国军官，而在德语版本中，罗比说她曾赤手捉住从马戏团逃跑的狮子。<br />
	&middot;1982年9月13日，格蕾丝&middot;凯莉带着16岁的女儿斯蒂芬妮驾车出行，途中心脏病突发，失控的罗孚3500坠下45英尺高的山崖。第二天，终未从昏迷中复苏的格蕾丝永辞人世，时年52岁。车祸的事发地点，正是她在《捉贼记》中飞车的那段公路，而且同她与片中罗比野餐的地点不远。也许一切都是宿命，和她同车的女儿性命无忧，而两年前，格蕾丝就曾预言自己将死在摩纳哥的公路。<br />
	<br />
	穿帮镜头<br />
	<br />
	&middot;罗比曾说要将衣服留给丹妮尔，但在花市的场景中，罗比还穿着同一套服装。<br />
	&middot;当汽车从别墅驶出到开始野餐前，车身上映出了照明器材。<br />
	<br />
	<img alt="" height="337" src="http://img165.poco.cn/mypoco/myphoto/20120227/23/64417096201202272300293160492791283_002.jpg" style="cursor: pointer" width="600" /><br />
	<br />
	<img alt="" height="337" src="http://img165.poco.cn/mypoco/myphoto/20120227/23/64417096201202272300293160492791283_001.jpg" style="cursor: pointer" width="600" /><br />
	<br />
	<img alt="" height="337" src="http://img165.poco.cn/mypoco/myphoto/20120227/23/64417096201202272300293160492791283_000.jpg" style="cursor: pointer" width="600" /><br />
	&nbsp;</p>
<p>
	[下载地址]：&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2927/飘花电影piaohua.com捉贼记BD中英双字1280高清.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:2927/飘花电影piaohua.com捉贼记BD中英双字1280高清.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2927/飘花电影piaohua.com捉贼记BD中英双字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15Q3310-4M21.jpg{/dede:field}
