{dede:field name='keywords'}编年史(超能失控)DVD中字2012最{/dede:field}
{dede:field name='description'}编年史(超能失控)DVD中字2012最新上映美国科幻动作惊悚大片迅雷下载、免费下载，编年史(超能失控)DVD中字2012最新上映美国科幻动作惊悚大片Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}编年史(超能失控)DVD中字2012最新上映美国科幻动作惊悚大片{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-04-27{/dede:field}
{dede:field name='body'}<p>
	&nbsp;</p>
<p>
	<img src="http://img2081.poco.cn/mypoco/myphoto/20120216/20/56643687201202162053523967967030446_006.jpg" /></p>
<p>
	<img src="http://img2081.poco.cn/mypoco/myphoto/20120216/20/56643687201202162053523967967030446_004.jpg" /></p>
<p>
	◎译　　名　编年史/夺命异能(港)/超能失控(台)/失控的超能少年/超能力纪事<br />
	◎片　　名　Chronicle<br />
	◎年　　代　2012<br />
	◎国　　家　英国/美国<br />
	◎类　　别　剧情/动作/科幻/惊悚<br />
	◎语　　言　英语<br />
	◎字　　幕　中文<br />
	◎IMDB评分 7.6/10 from 12,625 users<br />
	◎IMDB链接 http://www.imdb.com/title/tt1706593<br />
	◎文件格式　清晰TS-RMVB<br />
	◎视频尺寸　640 x 272<br />
	◎文件大小　1CD 382MB<br />
	◎片　　长　75 Mins<br />
	<br />
	<br />
	<br />
	◎影片截图<br />
	<br />
	&nbsp;</p>
<p>
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120427/14/56643687201204271449592875658252502_001.jpg" /></p>
<p>
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120427/14/56643687201204271449592875658252502_003.jpg" /></p>
<p>
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120427/14/56643687201204271449592875658252502_000.jpg" /></p>
<p>
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120427/14/56643687201204271449592875658252502_002.jpg" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2835/飘花电影piaohua.com编年史(超能失控)抢先中字.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:2835/飘花电影piaohua.com编年史(超能失控)抢先中字.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2835/飘花电影piaohua.com编年史(超能失控)抢先中字.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3307/飘花电影piaohua.com编年史(超能失控)DVD中字.rmvb">&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3307/飘花电影piaohua.com编年史(超能失控)DVD中字.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3307/飘花电影piaohua.com编年史(超能失控)DVD中字.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O14c950-24061.jpg{/dede:field}
