{dede:field name='keywords'}DUO:陈奕迅2010演唱会[DVD中字]+{/dede:field}
{dede:field name='description'}DUO:陈奕迅2010演唱会[DVD中字]+陈奕迅红馆演唱会迅雷下载、免费下载，DUO:陈奕迅2010演唱会[DVD中字]+陈奕迅红馆演唱会Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}DUO:陈奕迅2010演唱会[DVD中字]+陈奕迅红馆演唱会{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-07-31{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://5e:5e@m1.eee4.cc:1511/【3E电影院www.eee4.cc】DUO：陈奕迅2010演唱会CD1.rmvb" target="_blank{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MQ500040-2cS.jpg{/dede:field}
