<?php
$z[0]=Array("field","DUO:陈奕迅2010演唱会[DVD中字]+",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","DUO:陈奕迅2010演唱会[DVD中字]+陈奕迅红馆演唱会迅雷下载、免费下载，DUO:陈奕迅2010演唱会[DVD中字]+陈奕迅红馆演唱会Gvod高清在线播放，剧情介绍等。",73,259);
$z[1][4]['name']="description";
$z[2]=Array("field","DUO:陈奕迅2010演唱会[DVD中字]+陈奕迅红馆演唱会",261,345);
$z[2][4]['name']="title";
$z[3]=Array("field","",347,386);
$z[3][4]['name']="writer";
$z[4]=Array("field","",388,427);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-07-31",429,479);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",481,518);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://5e:5e@m1.eee4.cc:1511/【3E电影院www.eee4.cc】DUO：陈奕迅2010演唱会CD1.rmvb\" target=\"_blank",520,655);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MQ500040-2cS.jpg",657,739);
$z[8][4]['name']="litpic";

?>