{dede:field name='keywords'}藏獒多吉BD高清迅雷下载，免费下{/dede:field}
{dede:field name='description'}藏獒多吉BD高清迅雷下载、免费下载，藏獒多吉BD高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}藏獒多吉BD高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-11-04{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://www.luangh.com/up/files/73/PEKING-BD-rip-aaa 1 1.jpg" /></p>
<p>
	◎译　　名　藏獒多吉<br />
	◎片　　名　The Tibetan Dog<br />
	◎年　　代　2011<br />
	◎国　　家　大陆/日本<br />
	◎类　　别　动画<br />
	◎语　　言　普通话<br />
	◎字　　幕　中文<br />
	◎IMDB评分 &nbsp;<br />
	◎IMDB链接 &nbsp;<br />
	◎片　　长　1h:30m:44s<br />
	◎导　　演　小岛正幸 / 浦泽直树<br />
	◎主　　演　刘婧荦 &nbsp;<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 阿 &nbsp;兰<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 徐 &nbsp;涛<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 茫 &nbsp;来<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 赵 &nbsp;岭<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 周志强<br />
	　　　　　　<br />
	◎简　　介<br />
	<br />
	&nbsp; &nbsp; &nbsp; 少年田劲的父母早年为了将西医带入藏地做出了无数的牺牲，由于无法适应高原的生活，田劲的妈妈带着尚在襁褓中的儿子返回内地，爸爸拉格巴则在高原继续着他的事业。数年过后，妈妈病故，无依无靠的田劲来到高原寻找爸爸，然而心中却藏着无数的怨恨。拉格巴终日忙碌行医，任凭儿子自行学习牧羊。某天，田劲遭到狗熊的威胁，幸亏一只金色的藏獒相助，后来更因种种机缘让他与这只名叫多吉的藏獒成为最亲密的朋友。与此同时，草原上出现了专门残害生灵的恶魔，牧民的平静生活被彻底打破&hellip;&hellip;<br />
	<br />
	◎幕后制作<br />
	<br />
	　　本片根据杨志军的小说《藏獒》改编，由中日两国联合制作，日本著名漫画家浦泽直树还担任了人设和导演的工作。</p>
<p>
	<img alt="" src="/uploads/allimg/c120525/133O044V260-23C91.jpg" style="width: 720px; height: 405px" /><img alt="" src="/uploads/allimg/c120525/133O044W910-244V1.jpg" style="width: 720px; height: 405px" /><img alt="" src="/uploads/allimg/c120525/133O044X920-25c32.jpg" style="width: 720px; height: 405px" /><br />
	&nbsp;</p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="/uploads/allimg/c120524/133N2Z4FF-102231.jpg" />&nbsp;&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy125:piaohua@dy125.piaohua.com:7132/飘花电影piaohua.com藏獒多吉BD国语中字1280高清.rmvb </td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O044YU0-2C153.jpg{/dede:field}
