{dede:field name='keywords'}密室之不可靠岸/密室2/DVDscr迅{/dede:field}
{dede:field name='description'}密室之不可靠岸/密室2/DVDscr迅雷下载、免费下载，密室之不可靠岸/密室2/DVDscrGvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}密室之不可靠岸/密室2/DVDscr{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-11-10{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img165.poco.cn/mypoco/myphoto/20111109/17/5488623520111109170752083.jpg" /></p>
<p>
	◎中 文 名　密室之不可靠岸/密室2<br />
	◎片　　名　Lost In Panic Cruise<br />
	◎年　　代　2011<br />
	◎国　　家　中国<br />
	◎类　　别　悬疑/惊悚<br />
	◎语　　言　国语<br />
	◎字　　幕　中文<br />
	◎IMDB评分 N/A<br />
	◎IMDB链接 N/A<br />
	◎文件格式　XviD + MP3<br />
	◎视频尺寸　640 x 356<br />
	◎文件大小　1CD 705MB<br />
	◎片　　长　98分钟<br />
	◎导　　演　张番番 Fanfan Zhang<br />
	◎主　　演　苏有朋 Alec Su&nbsp; &hellip;.柳飞云<br />
	　　　　　　杨坤 Yang Kun<br />
	　　　　　　倪虹洁 Hongjie Ni<br />
	　　　　　　周韦彤 Weitong Zhou<br />
	　　　　　　吴辰君 Annie Wu<br />
	　　　　　　毛俊杰 Junjie Mao<br />
	　　　　　　孙一理 Yi-li Sun</p>

<p>
	◎简　　介</p>
<p>
	故事承接上一部《密室之不可告人》的结局。推理小说家柳飞云（苏有朋饰演）应邀携经纪人李晓峰（孙一理饰演）参加好友董磊（杨坤饰演）的豪华蜜月游轮游，在船上邂逅了甜美的新娘苏静静（倪虹洁饰演）和她美丽迷人的三个同事&mdash;&mdash;漂亮的肖扬（毛俊杰饰演）、性感的朱迪（周韦彤饰演）、优雅的韩菲菲（吴辰君饰演），一场充满了暧昧的性感之旅就此展开。白日，游轮上，性感美女、佳酿、碧海、白云，仿若远离人世的极乐园；夜晚，销魂狂野的化妆舞会、暧昧的调情嬉戏、彻夜狂欢&hellip;&hellip;然而就在这纸醉金迷的华丽之下，却潜流着不可告人的黑暗阴谋。谁都未能料到，这一夜风流竟会是最后的狂欢&hellip;&hellip;<br />
	　　午夜，一具艳尸被发现在甲板上。不久后，又有一位美女在密室中暴毙&hellip;&hellip;黑漆漆远离海岸的大海上，如&ldquo;密室&rdquo;一般的游轮随波荡漾，人心惶惶，谁也不知这艘承载着欢乐和谋杀的游轮是否还能平安靠岸&hellip;&hellip;而柳飞云在种种蹊跷中剥茧抽丝，寻找线索，竟然挖掘出一个多年悬案的惊人真相&hellip;&hellip;</p>
<p>
	<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20111110/00/62564813201111100013557689967824059_002.jpg" /><img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20111110/00/62564813201111100013557689967824059_001.jpg" style="width: 640px; height: 356px" /><img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20111110/00/62564813201111100013557689967824059_000.jpg" style="width: 640px; height: 356px" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>


<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="&#13;&#10;ftp://dy125:piaohua@dy125.piaohua.com:7157/飘花电影piaohua.com密室之不可靠岸DVDscr国语中字.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:7157/飘花电影piaohua.com密室之不可靠岸DVDscr国语中字.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O16036150-3S57.jpg{/dede:field}
