<?php
$z[0]=Array("field","龙卷风[DVD国语配音]迅雷下载，",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","龙卷风[DVD国语配音]迅雷下载、免费下载，龙卷风[DVD国语配音]Gvod高清在线播放，剧情介绍等。",72,204);
$z[1][4]['name']="description";
$z[2]=Array("field","龙卷风[DVD国语配音]",206,263);
$z[2][4]['name']="title";
$z[3]=Array("field","",265,304);
$z[3][4]['name']="writer";
$z[4]=Array("field","",306,345);
$z[4][4]['name']="source";
$z[5]=Array("field","2008-11-14",347,397);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",399,436);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://d21:d21@xl2.eee4.com:1105/[3E电影站www.eee4.com]龙卷风DVD国语配音版.rmvb\" target=_blank>ftftp://d21:d21@xl2.eee4.com:1105/[3E电影站www.eee4.com]龙卷风DVD国语配音版.rmvb</A></TD></TR></TBODY></TABLE></div><ul class=\"mmlist",438,704);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MPV0910-52019.jpg",706,789);
$z[8][4]['name']="litpic";

?>