{dede:field name='keywords'}第一大总统(国父孙中山)DVD国语{/dede:field}
{dede:field name='description'}第一大总统(国父孙中山)DVD国语中字2011最新上映中国历传记史大迅雷下载、免费下载，第一大总统(国父孙中山)DVD国语中字2011最新上映中国历传记史大Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}第一大总统(国父孙中山)DVD国语中字2011最新上映中国历传记史大{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-10-03{/dede:field}
{dede:field name='body'}<p>
	<img src="http://img165.poco.cn/mypoco/myphoto/20111003/13/56634212201110031305142447462419138_005.jpg" /></p>
<p>
	<img src="http://img165.poco.cn/mypoco/myphoto/20111003/13/56634212201110031305142447462419138_004.jpg" /></p>
<p>
	中文名： 第一大总统/国父孙中山<br />
	英文名： Di Yi Da Zong Tong<br />
	导演： 王才涛<br />
	主演： 邱心志 / 韩庚 / 张峻宁 / 聂玫 / 田亮 / 秦昊 / 李晟 / 何洁 / 刘劲 / 曹炳琨 / 江平 / 王艳 / 熊乃瑾 / 句号 / 邹兆龙 / 周一围 / 谭耀文 / 王姬 / 居文沛 / 胡彦斌 / 于娜 / 凌潇肃 / 刘羽琦 / 张颂文<br />
	上映日期： 2011年9月30日 中国<br />
	国家/地区： 中国<br />
	类型： 剧情 / 历史 / 传记<br />
	片长：114分钟<br />
	对白语言： 汉语普通话</p>
<p>
	<br />
	剧情简介</p>
<p>
	　　《国父孙中山》以1912年孙中山就任中华民国临时大总统开场，历述宋教仁遇刺，孙中山发动二次革命，流亡日本，与宋庆龄相爱结婚，袁世凯复辟，孙中山北伐，陈炯明叛变，陆军军官学校创立，直至1925年3月孙中山因病在北京逝世等一系列对历史走向产生重大影响的事件，对辛亥革命后孙中山先生的人生轨迹进行了一次全景式展现。在历史事件之外，电影将着重展示伟人感性的一面，孙中山和宋庆龄的相遇、相知、相爱、相伴的爱情故事将在电影中得到表现。剧本中有宋家反对宋庆龄和孙中山在一起，宋庆龄用绳子从窗口逃出，和孙中山相会的情节；也有孙中山与原配离婚，和宋再婚的情节；甚至有陈炯明叛变时，宋庆龄在逃亡路上流产的细节，这些都是其他同类题材电影中未曾着力表现过的。</p>

<p>
	◎影片截图</p>
<p>
	&nbsp;<img src="http://img165.poco.cn/mypoco/myphoto/20111003/15/56634212201110031522563484103790111_003.jpg" /></p>
<p>
	<img src="http://img165.poco.cn/mypoco/myphoto/20111003/15/56634212201110031522563484103790111_002.jpg" /></p>
<p>
	<img src="http://img165.poco.cn/mypoco/myphoto/20111003/15/56634212201110031522563484103790111_001.jpg" /></p>
<p>
	<img src="http://img165.poco.cn/mypoco/myphoto/20111003/15/56634212201110031522563484103790111_000.jpg" /></p>
<p>
	[下载地址]：<img border="0" src="/templets/img/down.jpg" /></p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:1715/飘花电影piaohua.com第一大总统(国父孙中山)DVD国语中字.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:1715/飘花电影piaohua.com第一大总统(国父孙中山)DVD国语中字.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1624cP-13338.jpg{/dede:field}
