{dede:field name='keywords'}黄家驹经典演唱会完整版迅雷下载{/dede:field}
{dede:field name='description'}黄家驹经典演唱会完整版迅雷下载、免费下载，黄家驹经典演唱会完整版Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}黄家驹经典演唱会完整版{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2006-08-04{/dede:field}
{dede:field name='body'}<P>播放后双击视频“全屏”</P> 
<object classid="CLSID:22d6f312-b0f6-11d0-94ab-0080c74c7e95" class="OBJECT" id="MediaPlayer" width="500" height="350" ><param name="ShowStatusBar" value="-1"><param name="Filename" value="http://218.23.23.67:100/D:/演唱会/港台演唱会/1992光辉岁月演唱会/1992光辉岁月演唱会上.wmv"></embed></object><br /> 
<P>下载地址<BR></P> <br>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120524/133N353DD0-2G248.gif{/dede:field}
