<?php
$z[0]=Array("field","决战猩球/猿人争霸战/人猿星球10",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","决战猩球/猿人争霸战/人猿星球1024x576高清版迅雷下载、免费下载，决战猩球/猿人争霸战/人猿星球1024x576高清版Gvod高清在线播放，剧情介绍等。",73,251);
$z[1][4]['name']="description";
$z[2]=Array("field","决战猩球/猿人争霸战/人猿星球1024x576高清版",253,333);
$z[2][4]['name']="title";
$z[3]=Array("field","",335,374);
$z[3][4]['name']="writer";
$z[4]=Array("field","",376,415);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-11-06",417,467);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",469,506);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://eee4.com:8033@vip10.eee4.com:8033/决战猩球/[3E迅雷电影站www.eee4.com]决战猩球CD1.rmvb\" target=\"_blank",508,654);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MO9B420-3ME.jpg",656,737);
$z[8][4]['name']="litpic";

?>