{dede:field name='keywords'}决战猩球/猿人争霸战/人猿星球10{/dede:field}
{dede:field name='description'}决战猩球/猿人争霸战/人猿星球1024x576高清版迅雷下载、免费下载，决战猩球/猿人争霸战/人猿星球1024x576高清版Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}决战猩球/猿人争霸战/人猿星球1024x576高清版{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-11-06{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://eee4.com:8033@vip10.eee4.com:8033/决战猩球/[3E迅雷电影站www.eee4.com]决战猩球CD1.rmvb" target="_blank{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MO9B420-3ME.jpg{/dede:field}
