{dede:field name='keywords'}月色狰狞HD国语中字1024/1280高{/dede:field}
{dede:field name='description'}月色狰狞HD国语中字1024/1280高清2012最新动作惊悚迅雷下载、免费下载，月色狰狞HD国语中字1024/1280高清2012最新动作惊悚Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}月色狰狞HD国语中字1024/1280高清2012最新动作惊悚{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-06{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://apollo.s.dpool.sina.com.cn/nd/dataent/moviepic/pics/237/moviepic_2db9fd482affc940e5d90517d639682c.jpg" /></p>
<p>
	片名: 月色狰狞<br />
	又名: 非常盗 / A Mystery Fobber<br />
	导演: 张力<br />
	编剧: 王连生<br />
	主演: 邢佳栋 / 姚橹 / 矢野浩二 / 李彧<br />
	类型: 动作 / 悬疑<br />
	制片国家/地区: 中国大陆<br />
	语言: 汉语普通话<br />
	片长: 84分钟<br />
	月色狰狞的剧情简介 &middot; &middot; &middot; &middot; &middot; &middot;<br />
	　　地矿学家李教授带学生莫天良（邢佳栋 饰）和女儿月儿探寻矿源，获绘有金矿地势的羊皮图。盗匪赵无奇一路追杀，李教授中弹，临终前将图一分为二交给两个年轻人。莫天良摔下百丈悬崖，所带半张图被赵夺走。<br />
	　　月儿被孟瑞救下并收留。他把月儿的半张羊皮图弄到手欲送从日本留学回来的孪生 兄弟孟哲（姚橹 饰），想开金矿发大财。日本军方为研发新武器派山崎（矢野浩二 饰）到中国寻找稀有金属。孟瑞离奇死去，脸上盖有一张赵无奇的面具。 接着土匪鹰老大尸体上也有赵无奇的面具。<br />
	　　手下曹双林决意为鹰老大报仇。孟哲、山崎、曹双林三路人来到福禄客栈寻找线索，一夜间发生了一场惊心动魂的打斗与拼杀&hellip;&hellip;&nbsp;</p>
<p>
	影片截图<br />
	&nbsp;</p>
<p>
	&nbsp;</p>
<p>
	<img alt="" height="338" src="http://img.sceper.eu/images/vM7k.jpg" width="600" /></p>
<p>
	&nbsp;<img alt="" height="338" src="http://img.sceper.eu/images/X9BGq.jpg" width="600" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.net/">http://www.xiaozhizhu.net</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3357/飘花电影piaohua.com月色狰狞HD国语中字1024高清.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3357/飘花电影piaohua.com月色狰狞HD国语中字1024高清.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3357/飘花电影piaohua.com月色狰狞HD国语中字1280高清.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3357/飘花电影piaohua.com月色狰狞HD国语中字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1493Q60-45G7.jpg{/dede:field}
