{dede:field name='keywords'}帝企鹅日记BD1280法/国/台/粤/纯{/dede:field}
{dede:field name='description'}帝企鹅日记BD1280法/国/台/粤/纯音乐五音轨迅雷下载、免费下载，帝企鹅日记BD1280法/国/台/粤/纯音乐五音轨Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}帝企鹅日记BD1280法/国/台/粤/纯音乐五音轨{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-15{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120516/00/17870980201205160003262386583510549_000.jpg" style="width: 566px; height: 755px" /></p>
<p>
	◎译　　名　帝企鹅日记<br />
	◎片　　名　March of the Penguins<br />
	◎年　　代　2005<br />
	◎国　　家　法国<br />
	◎类　　别　记录<br />
	◎语　　言　法/国/台/粤/纯音乐<br />
	◎字　　幕　简体中文<br />
	◎IMDB评分 7.8/10 (18,192 votes)<br />
	◎IMDB链接 <a href="http://www.imdb.com/title/tt0428803" target="_blank">http://www.imdb.com/title/tt0428803</a><br />
	◎文件格式　X264 + AC3<br />
	◎视频尺寸　1280x720<br />
	◎片　　长　80 mins(美国)<br />
	◎导　　演　吕克&middot;雅克特 Luc Jacquet<br />
	◎主　　演　夏尔&middot;贝尔林 Charles Berling .... Narrator - Penguin Father (voice: French version)<br />
	　　　　　　罗迈尼&middot;博林格 Romane Bohringer .... Narrator - Penguin Mother (voice: French version)<br />
	　　　　　　Jules Sitruk .... Narrator - Penguin Baby (voice: French version)<br />
	　　　　　　G?sta Ekman .... Narrator (voice: Swedish version)<br />
	　　　　　　Fiorello .... Narrator (voice: Italian version)<br />
	　　　　　　摩根&middot;弗里曼 Morgan Freeman .... Narrator (voice: English version)<br />
	　　　　　　Sofie Gr?b?l .... Narrator (voice: Danish version)<br />
	　　　　　　石田光 Hikari Ishida .... Haha-Penguin (voice: Japanese version)<br />
	　　　　　　神木隆之介 Ryunosuke Kamiki .... Ko-Penguin (voice: Japanese version)<br />
	　　　　　　大泽隆夫 Takao Osawa .... Chichi-Penguin (voice: Japanese version)<br />
	<br />
	◎简　　介　<br />
	<br />
	　　每年冬天，在一片冰川、荒凉孤寂的南极洲上，生存着一群不畏寒冷的族类：皇帝企鹅。南极洲是一个终年寒冷的地方，它每年三月便开始进入寒冬，并将持续九个月的时间。于是每年的三月，成千上万的皇帝企鹅离开它们的海洋家园，以轻巧的动作跃上岸，一开始以圆滚滚的肚皮在地面滑行数十公尺，最终用蹒跚的双脚在冰面上行走。为了寻找一个安全的环境，以便繁衍后代、延续种族生存，企鹅们不得不放弃海里的悠然生活，冒着昏天黑地的冰风暴，踉踉跄跄、如婴儿学步一般地开始一段漫长而艰辛的旅程。<br />
	　　由天性和南十字星座的引导，它们准确无误地向着自己的出生地前进。伴随着一系列难以理解的舞蹈、和嘶鸣一种令人入迷的不和谐音调，企鹅们开始了求爱仪式，很快它们就会形成一对一对的&ldquo;夫妇&rdquo;。<br />
	　　白天越来越短，气候也越来越恶劣，雌性企鹅会停下来一段时间生蛋。之后，精疲力尽的它还不能休息，必须要立即启程继续赶路，返回大海以恢复体力并寻找食物。旅途并不是一帆风顺的，贪婪的海豹无时不刻在对它们虎视眈眈，于是企鹅爸爸就会留下来保护那些珍贵的企鹅蛋，它们将蛋孵在自己的脚掌上面以保持温暖&hellip;&hellip;<br />
	<br />
	导演阐述<br />
	　　在严酷的冰雪暴侵袭下，皇帝企鹅们举步维艰地迈着步伐，在广阔的冰面迷宫上产蛋。在它们的周围，白茫茫一片，四处都是浮冰，但勇敢的企鹅们从不屈服，在如此恶劣的困境下傲然生存。在这片没有其他生物胆敢涉足的区域，皇帝企鹅仍旧持续它们浪漫的约会。随着冬季来临的群体迁徙，《企鹅的三月》给我们讲述了一个传奇的族类，描绘了一个神奇、特别、而又富有感情的动物，影片是一个充满勇气、幽默和神秘的故事。<br />
	　　我的目标是从一个全新的角度深度发掘，给大家讲述一个真实却非凡的故事。它虽然已经延续了几百年甚至几千年的寒冬，但却从未有人类将它记载和遗传下来，因为在过去的几千年中从未有人类在南极居住。直到一个世纪前，企鹅们才第一次&ldquo;撞&rdquo;上了人类。1950年，当试验性基地在南极建成，科学观测数据才取代了人们口述的传奇&hellip;&hellip;<br />
	<br />
	影片简评<br />
	　　皇帝企鹅的繁衍方式是特别的，它结合了爱、勇气、冒险与戏剧化的元素，而这一切的一切都是发生在南极洲--地球上最孤立和险峻的地方。导演吕克&middot;雅克特带我们一同走过了这场真实感人的历程，为了能拍到这些珍贵的镜头，他甘愿在恶劣的南极气候环境下，与三名组员呆了十三个月，真实地再现了这个奇妙族类的迁徙全过程。好莱坞著名影星摩根&middot;弗里曼(Morgan Freeman)也参与此片，甘当配角为企鹅们解说，看来这帮黑白相间、笨拙可爱的小家伙还真是面子不小呢。影片是美妙惊奇的，但同时也是发人深省的，随着环境恶化、地球两极变暖，这群美丽无辜的的种族也受到了威胁，让我们携起手来，共同保护这个人类和企鹅的家园吧。<br />
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120516/00/17870980201205160003262386583510549_018.jpg" /></p>
<p>
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120516/00/17870980201205160003262386583510549_016.jpg" /></p>
<p>
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120516/00/17870980201205160003262386583510549_015.jpg" style="width: 640px; height: 360px" /><br />
	&nbsp;</p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.net" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy241:piaohua@117.41.229.29:2021/飘花电影piaohua.com帝企鹅日记BD1280.mkv">ftp://dy241:piaohua@117.41.229.29:2021/飘花电影piaohua.com帝企鹅日记BD1280.mkv</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15c3260-26306.jpg{/dede:field}
