{dede:field name='keywords'}这不是斯巴达/300撞士BD1280高清{/dede:field}
{dede:field name='description'}这不是斯巴达/300撞士BD1280高清中英双字迅雷下载、免费下载，这不是斯巴达/300撞士BD1280高清中英双字Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}这不是斯巴达/300撞士BD1280高清中英双字{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-19{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="/uploads/allimg/c120525/133O0W1C30-1R20.jpg" /></p>
<p>
	◎译　　名　300撞士/这不是斯巴达<br />
	◎片　　名　Meet The Spartans<br />
	◎年　　代　2008<br />
	◎国　　家　美国<br />
	◎类　　别　喜剧<br />
	◎语　　言　英语<br />
	◎IMDB评分 2.3/10 (23,067 votes)<br />
	◎IMDB链接 http://www.imdb.com/title/tt1073498<br />
	◎片　　长　84 Min<br />
	◎导　　演　杰森&middot;弗莱德博格 Jason Friedberg<br />
	　　　　　　艾隆&middot;塞尔泽 Aaron Seltzer<br />
	◎主　　演　Diedrich Bader .....Traitoro<br />
	　　　　　　Kevin Sorbo .....Captain<br />
	　　　　　　Travis Van Winkle .....Sonio (attached)<br />
	　　　　　　Sean Maguire .....Leonidas<br />
	　　　　　　Method Man .....Persian Emissary<br />
	　　　　　　Jim Piddock .....Loyalist<br />
	　　　　　　Greg Ellis .....Shrek<br />
	　　　　　　Crista Flanagan .....Ugly Betty / Spartan Girl<br />
	　　　　　　蒂姆&middot;康诺利 Tim Connolly .....Spartan Soldier<br />
	　　　　　　Tony Yalda .....Sanjaya<br />
	　　　　　　Ike Barinholtz .....Prophet #1<br />
	　　　　　　Jareb Dauplaise .....Actor<br />
	　　　　　　Zachary Dylan Smith .....Leonidas @ 10<br />
	　　　　　　Emily Wilson .....Lindsay Lohan<br />
	　　　　　　Nick Steele .....K-Fed<br />
	　　　　　　Kim Kindrick .....Harem<br />
	　　　　　　Nate Haden .....Ryan Seacrest<br />
	<br />
	◎简　　介<br />
	<br />
	　　公元前480年，波斯王薛西斯率50万铁骑攻向希腊。数月之战，希腊已沦陷过半，骁勇善战的斯巴达国王列奥尼达，被众城邦选出担任守军统帅。英明神武的他力排众议，亲率300斯巴达勇士死守希腊中部的门户&mdash;&mdash;温泉关&hellip;&hellip;<br />
	　　当薛西斯的大军慢慢逼近了关口，将拔弩张的战场早已是未血绸缪&hellip;&hellip;这时战场上响起了音乐声，强烈的HipHop节奏下，300勇士与敌军展开了激烈的斗舞，空转、机器人、头转等绝招被300勇士耍的有模有样，先输一阵的薛西斯王怒不可遏，招来了素有&ldquo;快乐的大脚&rdquo;之称的企鹅巨兽波波向关口发起猛攻，快节奏的踢踏果然让300勇士一时无从招架，且看300人将如何面对地方轮番的挑衅&hellip;&hellip;&nbsp;</p>
<p>
	<img alt="" src="/uploads/allimg/c120525/133O0W1R20-22395.jpg" style="width: 640px; height: 360px" /></p>
<p>
	<img alt="" src="/uploads/allimg/c120525/133O0W1YZ-314V.jpg" /></p>
<p>
	<img alt="" src="/uploads/allimg/c120525/133O0W19D0-4M94.jpg" style="width: 640px; height: 360px" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="/uploads/allimg/c120525/133O0T31310-42214.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：http://www.xiaozhizhu.net</td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy241:piaohua@117.41.229.29:2026/这不是斯巴达BD1280高清中英双字.rmvb</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O0W203P-52K6.jpg{/dede:field}
