{dede:field name='keywords'}狮子王2/狮子王3/两部BD高清1024{/dede:field}
{dede:field name='description'}狮子王2/狮子王3/两部BD高清1024*576迅雷下载、免费下载，狮子王2/狮子王3/两部BD高清1024*576Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}狮子王2/狮子王3/两部BD高清1024*576{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-09-29{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="/uploads/allimg/c120525/133O04644D0-13I09.jpg" style="width: 500px; height: 661px" /></p>
<p>
	◎译　　名　 狮子王2：辛巴的荣耀<br />
	◎片　　名　 The.Lion.King.II.Simbas.Pride<br />
	◎年　　代　 1998年<br />
	◎国　　家　 美国<br />
	◎类　　别　 爱情 / 动画 / 家庭 / 冒险 / 歌舞 / 喜剧<br />
	◎IMDB评分　5.8/10&nbsp;&nbsp; 6,702 votes<br />
	◎IMDB链接　http://www.imdb.com/title/tt0120131/<br />
	◎制作公司　 Walt Disney Animation Australia[澳大利亚]<br />
	　　　　　　 华特迪士尼动画公司[美国]<br />
	　　　　　　 华特?迪士尼影片公司[美国]<br />
	◎发行公司　 Buena Vista Home Video (BVHV)[美国]<br />
	　　　　　　 Walt Disney Home Video[美国]<br />
	◎导　　演　 Darrell Rooney<br />
	　　　　　　 Rob LaDuca&nbsp; .... (co-director)<br />
	◎编　　剧　 Jonathan Cuba&nbsp;&nbsp;<br />
	　　　　　　 Flip Kobler&nbsp;&nbsp;<br />
	　　　　　　 Cindy Marcus&nbsp;&nbsp;<br />
	　　　　　　 Mark McCorkle&nbsp;&nbsp;<br />
	　　　　　　 Bill Motz&nbsp;&nbsp;<br />
	　　　　　　 Gregory Poirier&nbsp;&nbsp;<br />
	　　　　　　 Bob Roth&nbsp;&nbsp;<br />
	　　　　　　 Robert Schooley&nbsp;&nbsp;<br />
	　　　　　　 Linda Voorhees&nbsp;&nbsp;<br />
	　　　　　　 Jenny Wingfield&nbsp;&nbsp;<br />
	◎主　　演　 马修?布鲁德里克 Matthew Broderick&nbsp; ...... Simba (voice)<br />
	　　　　　　 莫伊拉?凯利 Moira Kelly&nbsp; ...... Nala (voice)<br />
	　　　　　　 妮芙?坎贝尔 Neve Campbell&nbsp; ...... Adult Kiara (voice)<br />
	　　　　　　 Liz Callaway&nbsp; ...... Adult Kiara (singing voice)<br />
	　　　　　　 米歇尔?霍恩 Michelle Horn&nbsp; ...... Young Kiara (voice)<br />
	　　　　　　 阿丽莎?米拉诺 Ashley Edner&nbsp; ...... Young Kiara (lion growls)<br />
	　　　　　　 Charity Sanoy&nbsp; ...... Young Kiara (singing) (singing voice)<br />
	　　　　　　 苏姗妮?普赖西特 Suzanne Pleshette&nbsp; ...... Zira (voice)<br />
	　　　　　　 安迪?迪克 Andy Dick&nbsp; ...... Nuka (voice)<br />
	　　　　　　 Ryan O&#39;Donohue&nbsp; ...... Young Kovu (voice)<br />
	　　　　　　 Jason Marsden&nbsp; ...... Adult Kovu (voice)<br />
	　　　　　　 Gene Miller&nbsp; ...... Adult Kovu (singing) (voice)<br />
	　　　　　　 莱西?沙伯特 Lacey Chabert&nbsp; ...... Young Vitani (voice)<br />
	　　　　　　 Crysta Macalush&nbsp; ...... Young Vitani (singing voice)<br />
	　　　　　　 詹尼弗?丽恩 Jennifer Lien&nbsp; ...... Adult Vitani (voice)<br />
	　　　　　　 Ernie Sabella&nbsp; ...... Pumbaa (voice)<br />
	　　　　　　 内森?莱恩 Nathan Lane&nbsp; ...... Timon (voice)<br />
	　　　　　　 罗伯特?吉尔劳姆 Robert Guillaume&nbsp; ...... Rafiki (voice)<br />
	　　　　　　 詹姆斯?厄尔?琼斯 James Earl Jones&nbsp; ...... Mufasa (voice)<br />
	　　　　　　 Edward Hibbert&nbsp; ...... Zazu (voice)<br />
	　　　　　　 Vanessa Theme Ament&nbsp; ...... Additional Voices (voice) (as Vanessa De La Rocha)<br />
	　　　　　　 Carmen Carter&nbsp; ...... Off Camera Singer<br />
	　　　　　　 Cam Clarke&nbsp; ...... Simba (singing voice)<br />
	　　　　　　 杰姆?库明斯 Jim Cummings&nbsp; ...... Additional Voices (voice)<br />
	　　　　　　 Robin Frizzell&nbsp; ...... Additional Voices (voice)<br />
	　　　　　　 Adrienne Hampton&nbsp; ...... Additional Voices (voice)<br />
	　　　　　　 Seth Isler&nbsp; ...... Additional Voices (voice)<br />
	　　　　　　 Zoe Leader&nbsp; ......&nbsp;<br />
	　　　　　　 Lisa Long&nbsp; ...... Additional Voices (voice)<br />
	　　　　　　 Meredith Scott Lynn&nbsp; ...... Additional Voices (voice)<br />
	　　　　　　 Joel Moffett&nbsp; ...... Additional Voices (voice)<br />
	　　　　　　 Pete Renaday&nbsp; ...... Additional Voices (voice) (as Pete Renaday)<br />
	　　　　　　 Richard Sinclair&nbsp; ...... Additional Voices (voice)<br />
	◎格　　式　x264 + AC3<br />
	◎视频尺寸　1024 x 576<br />
	◎文件大小　2.05 GB<br />
	◎片　　长　80 Mins<br />
	<br />
	◎简　　介　</p>
<p>
	　　本片的故事紧接上集，讲述辛巴与娜娜的女儿琪雅偷偷闯进王国外面的世界，途中遇上由邪恶敌人一手培育的接班人――孤儿小狮高夫，背景不同却患难与共的两个孩子能否共创未来&hellip;&hellip;</p>
<p>
	　　本片的故事剧情接续【狮子王】电影，剧情内容叙述在 Scar 死后，他的余党 Zira 决定向 Simba 展开复仇，於是她灌溉坏思想给一只年轻狮子 Kovu ，计画把他培养成 Scar 的接班人，准备开始一场权位争夺战，夺取荣耀王国的统治权！不料后来 Simba 的女儿 Kiara 居然爱上了 Kovu ，两人必须要化解上一代的恩怨，他们的爱情才会有好果。然而在一连串误会当中，却使得 Kiara 与 Kovu 逃离荣耀石，而双方的战争却迫在眉睫、一触及发。Simba 必须化消上一代的恩怨，才能化解父女关系的考验，并让荣耀王国恢复和平。本片内容十分具有正面启发的意义，藉着 Kiara 的成长故事，强调唯有宽恕与包容，才是化解仇恨对立的最佳良药。</p>
<p>
	◎幕　　后&nbsp;</p>
<p>
	　　本片是94年创下迪斯尼有史以来最高票房的著名动画片《狮子王》的续集，但却没有在大银幕上放映，发行公司选择了以家庭观赏为主的录像带和影碟市场。</p>
<p>
	　　本片的风格与原来电影类似，是由迪士尼在澳洲的ＴＶ动画部门所制作，动员了一百七十五位动画师、费时两年余才完成这部动画作品。</p>
<p>
	　　本片原来角色的配音由电影的原班人马担任，至於新角色 Simba 的女儿 Kiara 由演过【五口之家】、【惊声尖叫】&hellip;等片的 Neve Campbell 担任，成年 Kovu 则由 Jason Marsden 担任，他之前还曾经在迪士尼电影版卡通【高飞狗】中帮 Goofy 的儿子 Max 配音。</p>
<p>
	◎一句话评论</p>
<p>
	The Circle of Life Continues...</p>
<p>
	<img alt="" src="/uploads/allimg/c120525/133O0464630-144J0.jpg" style="width: 720px; height: 405px" /><img alt="" src="/uploads/allimg/c120525/133O0464H50-15Q38.jpg" style="width: 720px; height: 405px" /><img alt="" src="/uploads/allimg/c120525/133O0464R10-162X3.jpg" style="width: 720px; height: 405px" /></p>
<p>
	&nbsp;<img alt="" src="/uploads/allimg/c120525/133O04649160-1HZ6.jpg" style="width: 500px; height: 661px" /></p>
<p>
	【原 片 名】The Lion King III: Hakuna Matata<br />
	【中 文 名】狮子王3<br />
	【出品年代】2004<br />
	【首映日期】2004年02月10日 ( 美国 )<br />
	【IMDB链接】http://www.imdb.com/title/tt0318403/<br />
	【IMDB评分】6.5/10 (1,266 votes)<br />
	【国　　家】美国<br />
	【类　　别】喜剧/冒险/音乐/动画/家庭<br />
	【导　　演】布拉德利?雷蒙德 Bradley Raymond<br />
	【主　　演】马修?布鲁德里克 Matthew Broderick&nbsp; ....&nbsp; Simba (voice)<br />
	　　　　　　乌比?戈德堡 Whoopi Goldberg&nbsp; ....&nbsp; Shenzi (voice)<br />
	　　　　　　Julie Kavner&nbsp; ....&nbsp; Mom (voice)<br />
	　　　　　　内森?莱恩 Nathan Lane&nbsp; ....&nbsp; Timon (voice)<br />
	　　　　　　Cheech Marin&nbsp; ....&nbsp; Banzai (voice)<br />
	　　　　　　杰里?斯蒂勒 Jerry Stiller&nbsp; ....&nbsp; Uncle Max (voice)<br />
	　　　　　　Tony Anselmo&nbsp; ....&nbsp; Donald Duck (voice)<br />
	　　　　　　Jeff Bennett&nbsp; ....&nbsp; Additional Voices (voice)<br />
	　　　　　　柯瑞?伯顿 Corey Burton&nbsp; ....&nbsp; Grumpy, Additional Voices (voice)<br />
	　　　　　　Cam Clarke&nbsp; ....&nbsp; Additional Voices (voice)<br />
	　　　　　　杰姆?库明斯 Jim Cummings&nbsp; ....&nbsp; Ed (voice)<br />
	　　　　　　Bill Farmer&nbsp; ....&nbsp; Goofy (voice)<br />
	　　　　　　肖恩?弗雷明 Shaun Flemming&nbsp; ....&nbsp; The Lost Boys, Additional Voices (voice)<br />
	　　　　　　罗伯特?吉尔劳姆 Robert Guillaume&nbsp; ....&nbsp; Rafiki (voice)<br />
	　　　　　　Edward Hibbert&nbsp; ....&nbsp; Zazu (voice)</p>
<p>
	<br />
	【内容简介】<br />
	　&nbsp;&nbsp; 想知道狮子王的最佳拍档彭彭与丁满这对活宝是怎么不打不相识的么？他们又是如何闯入狮子王的家族，甚至改写了小狮王辛巴的传奇一生？现在，迪士尼全新动画电影[狮子王3]将带您回到故事的最开头，让彭彭和丁满一一揭开[狮子王]故事里所有鲜为人知的秘密！特别是当时发生在小狮王辛巴身上几个重要事件的内幕；其中包括当动物们一步步走向荣耀石跪下来祝贺小狮王辛巴的诞生，在那令人感动的伟大时刻，竟然发生了一件让众人跌破眼镜的爆笑事件！还有更多更多的惊人发现，等您来一探究竟！继[狮子王]后，流行乐天王艾尔顿?约翰（Elton John）和提姆?莱斯（Tim Rice）再度合作为[狮子王3]打造一首动听歌曲&ldquo;That&#39;;s All I Need&rdquo;，在欢乐的歌声中，添加彭彭与丁满的行列，完全掌握[狮子王]故事里的许多秘密，喜爱[狮子王]的您，绝不能错过[狮子王3]的疯狂魅力。</p>
<p>
	<img alt="" src="/uploads/allimg/c120525/133O04A0610-1W530.jpg" style="width: 720px; height: 405px" /><img alt="" src="/uploads/allimg/c120525/133O04A1430-1cX6.jpg" style="width: 720px; height: 405px" /><img alt="" src="/uploads/allimg/c120525/133O04A2260-20J56.jpg" style="width: 720px; height: 405px" /></p>


<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="/uploads/allimg/c120524/133N2Z4FF-102231.jpg" />&nbsp;&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy125:piaohua@dy125.piaohua.com:6011/飘花电影piaohua.com狮子王2BD中英双字1024高清.rmvb</td>
		</tr>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy125:piaohua@dy125.piaohua.com:6011/飘花电影piaohua.com狮子王3BD中英双字1024高清.rmvb</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O04A31Z-21E92.jpg{/dede:field}
