{dede:field name='keywords'}星河舰队3：掠夺者/星河战队3BD{/dede:field}
{dede:field name='description'}星河舰队3：掠夺者/星河战队3BD中英双字1024/1280高清迅雷下载、免费下载，星河舰队3：掠夺者/星河战队3BD中英双字1024/1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}星河舰队3：掠夺者/星河战队3BD中英双字1024/1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-01-07{/dede:field}
{dede:field name='body'}<p>
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://cdn3b.dvdempire.org/products/87/1409087h.jpg');" src="http://cdn3b.dvdempire.org/products/87/1409087h.jpg" /><br />
	<br />
	◎译　　名　星河舰队3：掠夺者/星河战队3<br />
	◎片　　名　Starship Troopers 3 Marauder<br />
	◎年　　代　2008<br />
	◎国　　家　美国<br />
	◎类　　别　动作/冒险/喜剧/剧情/幻想/恐怖/科幻/惊悚/西部<br />
	◎语　　言　英语<br />
	◎字　　幕　中英双字<br />
	◎文件格式　BD-RMVB<br />
	◎视频尺寸　1024 x 576<br />
	◎文件大小　1CD<br />
	◎片　　长　105 Min<br />
	◎导　　演　爱德华&middot;纽梅尔 Edward Neumeier<br />
	◎主　　演　卡斯帕&middot;凡&middot;迪恩 Casper Van Dien .....Johnny Rico<br />
	　　　　　　乔琳纳&middot;布拉洛克 Jolene Blalock .....Lola Beck<br />
	　　　　　　Catherine Oxenberg .....Technician #1<br />
	　　　　　　Boris Kodjoe .....Dix Hauzer<br />
	　　　　　　Marne Patterson .....Holly<br />
	　　　　　　Amanda Donohoe .....Admiral Enolo Phid<br />
	　　　　　　C&eacute;cile Breccia .....Link Manion<br />
	　　　　　　Garth Breytenbach .....Slug Skinner<br />
	　　　　　　Stelio Savante .....Bull Brittles<br />
	　　　　　　Stephen Hogan .....Sky Marshall Anoke<br />
	　　　　　　Jon Falkow .....Jingo (as Jon Falkow)<br />
	　　　　　　Tanya van Graan<br />
	　　　　　　Jose Vaz .....Elmo Goniff<br />
	　　　　　　Anthony Bishop .....Sergeant Rye<br />
	　　　　　　Magic<a href="http://www.3edyy.com/" target="_blank">3e</a> J. Ellingson .....Puppateer<br />
	<br />
	◎简　　介　<br />
	<br />
	　　《星河战队3：掠夺者》中，卡斯派&middot;范&middot;戴恩扮演的约翰尼又重新回到战队，不过这次他已经成为一名将军，并将接受新的任务，消灭更加凶残的虫族&hellip;&hellip;<br />
	　　在本集中，与异形的战斗仍在继续。一架联盟军的星舰因为意外事故，紧急降落在遥远的OM-1星球上。包括负责人斯盖&middot;马歇尔、飞行员罗拉&middot;贝克等人在内，都被困在星球上无法脱身。主人公约翰尼&middot;瑞科临危受命，带领一队战士，前往该星球进行营救任务&hellip;&hellip;</p>
<p>
	【电影截图】：<br />
	<br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://photo4.zxip.com/albums4/folder18/14184/20100310154516/20105291121581475.jpg');" src="http://photo4.zxip.com/albums4/folder18/14184/20100310154516/20105291121581475.jpg" />&nbsp;<br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://photo4.zxip.com/albums4/folder18/14184/20100310154516/20105291121581825.jpg');" src="http://photo4.zxip.com/albums4/folder18/14184/20100310154516/20105291121581825.jpg" /></p>
<br />
<p>
	[下载地址]：<img border="0" src="/templets/img/down.jpg" />
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://3e:3e@d8.3edyy.com:162/【3E电影院www.eee4.cc】星河战队3[BD中英双字1024x576高清版].rmvb" target="_blank">ftp://3e:3e@d8.3edyy.com:162/【3E电影院www.eee4.cc】星河战队3[BD中英双字1024x576高清版].rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				&nbsp;<a href="ftp://dy44:piaohua@dy44.piaohua.com:2536/飘花电影piaohua.com星河战队3BD中英双字1280高清.rmvb ">ftp://dy44:piaohua@dy44.piaohua.com:2536/飘花电影piaohua.com星河战队3BD中英双字1280高清.rmvb </a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15Z5B0-524H.jpg{/dede:field}
