<?php
$z[0]=Array("field","战时冬天[DVD中字]迅雷下载，免",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","战时冬天[DVD中字]迅雷下载、免费下载，战时冬天[DVD中字]Gvod高清在线播放，剧情介绍等。",72,200);
$z[1][4]['name']="description";
$z[2]=Array("field","战时冬天[DVD中字]",202,257);
$z[2][4]['name']="title";
$z[3]=Array("field","",259,298);
$z[3][4]['name']="writer";
$z[4]=Array("field","",300,339);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-05-08",341,391);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",393,430);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://4e:4e@d8.3edyy.com:151/【3E电影院www.eee4.cc】战时冬天.rmvb\" target=\"_blank",432,552);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MP615A0-2J95.jpg",554,636);
$z[8][4]['name']="litpic";

?>