{dede:field name='keywords'}活死人黎明（78版）[BD中字1024x{/dede:field}
{dede:field name='description'}活死人黎明（78版）[BD中字1024x576高清版无水印]迅雷下载、免费下载，活死人黎明（78版）[BD中字1024x576高清版无水印]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}活死人黎明（78版）[BD中字1024x576高清版无水印]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2010-01-31{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://3e:3e@www2.3edyy.com:3895/【3E电影院www.3edyy.com】活死人黎明BD中字1024x576高清版无水印.rmvb" target="_blank{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MQ335G0-150U.jpg{/dede:field}
