{dede:field name='keywords'}制胜一击/即刻反击BD1280高清迅{/dede:field}
{dede:field name='description'}制胜一击/即刻反击BD1280高清迅雷下载、免费下载，制胜一击/即刻反击BD1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}制胜一击/即刻反击BD1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-04-20{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://whysoblu.com/wp-content/uploads/2012/02/Haywire-Blu-ray.jpg" style="width: 596px; height: 749px" /></p>
<p>
	◎译　　名　制胜一击/ 即刻反击(台) / 狙煞特攻(港)<br />
	◎片　　名　Haywire<br />
	◎年　　代　2012<br />
	◎国　　家　美国<br />
	◎类　　别　动作/惊悚<br />
	◎语　　言　英语<br />
	◎字　　幕　中字<br />
	◎IMDB评分 &nbsp;6.3/10 from 10,857 users<br />
	◎IMDB链接 &nbsp;<a href="http://www.imdb.com/title/tt1506999/" target="_blank">http://www.imdb.com/title/tt1506999/</a><br />
	◎文件格式　X264 + DTS<br />
	◎视频尺寸　1280 x 528<br />
	◎文件大小　1DVD 0.97GB<br />
	◎片　　长　92 Mins<br />
	◎导　　演　史蒂文&middot;索德伯格 Steven Soderbergh<br />
	◎主　　演　吉娜&middot;卡拉诺 Gina Carano ....Mallory Kane<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;查宁&middot;塔图姆 Channing Tatum ....Aaron<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;迈克尔&middot;法斯宾德 Michael Fassbender ....Paul<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;伊万&middot;麦克格雷格 Ewan McGregor ....Kenneth<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;迈克尔&middot;道格拉斯 Michael Douglas ....Coblenz<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;安东尼奥&middot;班德拉斯 Antonio Banderas ....Rodrigo<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;迈克尔&middot;安格拉诺 Michael Angarano ....Scott<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;比尔&middot;帕克斯顿 Bill Paxton ....John Kane<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;马修&middot;卡索维茨 Mathieu Kassovitz<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Eddie J. Fernandez ....Barroso<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Anthony Wong ....Jiang<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;蒂姆&middot;康诺利 Tim Connolly ....Jason<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Maximino Arciniega ....Gomez<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Aaron Cohen ....Jamie<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Natascha Berg ....Liliana<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Julian Alcaraz ....Terrence<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Edward A. Duran ....Armed man #1<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Francisco Alarc&oacute;n ....Extra (uncredited)<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;彼得&middot;康博伊 Peter Conboy ....Man in pub (uncredited)<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;James Flynn ....Hotel Clerk (uncredited)<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Eriks Alfons Hausmanis ....Staff Member (uncredited)<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Seth Mossman ....Dinner Patron (uncredited)<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Amanda Fresquez ....Senator<br />
	<br />
	◎简　　介<br />
	<br />
	&nbsp; &nbsp;影片女主角Mallory Kane是一位中情局特工，并领导着自己的一支团队，却被同伴陷害，她必须要找出那个出卖她的人，并将一切导入正轨。<br />
	<br />
	&nbsp; &nbsp;漂亮的玛洛里在表面上是一个自由职业者，可是在暗地里，她还有一个不为人知的身份：一个执行特殊任务的专门性人才。通过自己的中间人，玛洛里接到了各种各样的活计，或是救人于水火之中，或是杀人于无形之中。不管这些是什么任务，它们都有一个共同的特色：政府不方便出面授权、官方无法介入。交到玛洛里的手中，她可以神不知鬼不觉地完成任务。<br />
	　　<br />
	&nbsp; 在顺利完成解救巴塞罗那人质的任务之后，玛洛里被紧急派到了都柏林。可是都柏林的任务执行的并不顺利。玛洛里发现自己被欺骗和背叛了，随之而来的是一场国际性的大围剿。为了保命，玛洛里只有使出浑身解数，在都柏林东躲西藏。最后，她找到了几个可以信任的老朋友，在他们的帮助下逃回了美国。回到了美国的她更是生命岌岌可危，她除了需要保护自己的家人和自己的性命之外，还要把幕后陷害她的罪魁祸首找出来。<br />
	　　<br />
	&nbsp;一场复仇女神的好戏，即将上演&hellip;&hellip;<br />
	<br />
	<br />
	幕后制作<br />
	<br />
	　　反伯恩的动作戏<br />
	<br />
	　　拍摄了《毒品网络》、《性、谎言和录像带》的史蒂文&middot;索德伯格也要拍摄动作电影了，这个消息会让很多喜欢索德伯格的影迷吃惊，因为一个偏向文艺口味的导演拍摄起动作戏来，令人颇有些摸不着头脑。但是有了&ldquo;罗汉系列&rdquo;打底，索德伯格对拍摄这一部堪称&ldquo;女版《谍影重重》&rdquo;的《制胜一击》自信满满。索德伯格说，自己被吸引到这个影片中的来的原因在于一个女性的强者角色，这样的人物在好莱坞的确是太少了，所以曾经拍摄了同样讲述女性故事的《应召女友》的他，才愿意来拍这部电影。索德伯格说：&ldquo;这个故事很棒，尤其是其中传递出来的那种女强人的信息，也令我欣喜不已。在一个男性作为主导力量的社会里，能有这么出色的一个剧本，这很令我心动。而且，我还知道有一个很出色的女性MMA运动员，她很适合来扮演这个角色，于是我就接下了这部戏。&rdquo;<br />
	<br />
	　　对于《制胜一击》来说，复仇的故事情节并不是重点，那些动作场面才是。因为女主角吉娜&middot;卡拉诺是科班出身的MMA运动员，所以在拍摄上，索德伯格选择了更为传统的固定机位的拍摄手法。这种拍摄手法，被他称为&ldquo;反伯恩风格&rdquo;。索德伯格说：&ldquo;我们放弃了手持式拍摄、放弃了快速的剪辑。我们展示的一切都是真功夫的实战。我想，作为观众，肯定想看到搏击的场面是如何完成的，所以我决定要全景式地展示每个动作和每次出击。而不是伯恩的那种快速剪辑的方式。而且，为了凸显出这种搏击场面的惨烈，我没有在这些镜头后面配乐，能听到的只有打斗、断骨的声音－－这的确很让人振奋。当然，吉娜&middot;卡拉诺的出拳很厉害，为了避免事故，我们都给那些和她有打戏的演员们穿上了防护服，像是法斯宾德、麦克格雷格这样的非动作片演员都穿上了防护服。拍摄动作场面的时候，我没有绘制什么故事板，更没有给出什么设计，很多内容都是由吉娜&middot;卡拉诺自己完成的。然后我们根据她的招式来设计镜头。这样的拍摄，我觉得更自然，因为每一招都是实实在在的，根本不是花拳绣腿。我想观众一定会很过瘾。&rdquo;<br />
	<br />
	　　好男配打女<br />
	<br />
	　　影片有一个了不得的配角阵容：查宁&middot;塔图姆、迈克尔&middot;法斯宾德、伊万&middot;麦克格雷格、迈克尔&middot;道格拉斯、安东尼奥&middot;班德拉斯、马修&middot;卡索维茨等等男演员都是能够独当一面的好手，可是在这部电影里，他们的存在却都只是为了衬托一个并不出名的女演员：吉娜&middot;卡拉诺。索德伯格说：&ldquo;的确，他们在影片中的作用就是为吉娜提供更大的发挥的空间，就好像是重星捧月一般，把一个人烘托出来。这其实是一种冒险，因为谁也不知道吉娜会发挥成什么样子，谁也不知道这样的组合会有多少看点。&rdquo;索德伯格是在看电视的时候发现吉娜&middot;卡拉诺的，当时索德伯格看到是一档电视真人秀节目，他看到了吉娜的功夫，随后就给她打了一个电话，并希望能寻觅到一个合适的剧本。正巧，和索德伯格合作过《卡夫卡》与《菩提树下》的莱姆&middot;多布斯酝酿了一个关于女特工的剧本，两厢综合，索德伯格就找来了吉娜拍摄这部电影。<br />
	<br />
	　　对于自己能出演索德伯格的电影，而且还是被一票明星烘托的女主角，吉娜显得有些&ldquo;被好运冲晕的头脑&rdquo;，她说：&ldquo;我根本没有想到能有这么好的机会和这么一群杰出的电影人合作，而且还是一个主角。导演希望我能展示出MMA的所有特点来，这其实并不是什么难事，而我也很擅长这个。索德伯格是一个很有才华、很天才的导演。他明白该如何展示出MMA的魅力，他选择了固定的机位、用最少的剪辑，保留表演和动作的最大的特色，我觉得这是他最有远见的决定。其他的演员也都很出色，从他们的身上，我学到了很多东西。拍完电影之后，我才觉得我刚刚入门，摸到了一点拍电影的门道。&rdquo;<br />
	<br />
	<br />
	花絮<br />
	<br />
	&middot;本片的女主角吉娜&middot;卡拉诺是一个很出色的女性MMA运动员，她以前曾出现在纪录片《擂台上的女孩》以及《搏击女孩》、《美国角斗士》等电视真人秀中，擅长综合搏击，导演史蒂文&middot;索德伯格是在一个综合搏击巡回表演上发现的她。<br />
	<br />
	&middot;影片2009年就进入了筹拍阶段，当时影片的名字叫做《击倒》（Knockout）。在实际开拍前才改成了《制胜一击》（Haywire）<br />
	<br />
	&middot;按照影片剧本的设定，《制胜一击》的大部分摄制工作都在爱尔兰完成。剧组在2010年的2月2日到3月25日在爱尔兰摄制影片，摄制期间为当地提供了超过100个临时的工作岗位。<br />
	<br />
	&middot;丹尼斯&middot;奎德原本是要在这部电影中扮演约翰&middot;坎恩一角的，但是他当时要出演《灵魂冲浪》一片，时间上有了冲突。所以只能放弃。后来，这个角色被交到了比尔&middot;帕克斯顿的手上。<br />
	&nbsp;<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120420/08/62564813201204200814043910314479452_006.jpg" style="width: 650px; height: 366px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120420/08/62564813201204200814043910314479452_005.jpg" style="width: 650px; height: 366px" /></p>
<p>
	【下载地址】</p>
<table bgcolor="#0099cc" border="0" cellpadding="10" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.net" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy125:piaohua@dy125.piaohua.com:7875/飘花电影piaohua.com制胜一击BD中字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:7875/飘花电影piaohua.com制胜一击BD中字1280高清.rmvb</a></td>
		</tr>
		<tr>
		</tr>
	</tbody>
</table>
<br />{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15626330-1L03.jpg{/dede:field}
