<?php
$z[0]=Array("field","验伤[BD中字1024x576高清版+DVD",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","验伤[BD中字1024x576高清版+DVD版本]迅雷下载、免费下载，验伤[BD中字1024x576高清版+DVD版本]Gvod高清在线播放，剧情介绍等。",72,234);
$z[1][4]['name']="description";
$z[2]=Array("field","验伤[BD中字1024x576高清版+DVD版本]",236,308);
$z[2][4]['name']="title";
$z[3]=Array("field","",310,349);
$z[3][4]['name']="writer";
$z[4]=Array("field","",351,390);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-08-19",392,442);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",444,481);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://3e:3e@m1.eee4.cc:1520/【3e电影网www.eee4.cc】验伤BD中字.rmvb\" target=_blank>ftftp://3e:3e@m1.eee4.cc:1520/【3e电影网www.eee4.cc】验伤BD中字.rmvb</A></TD></TR></TBODY></TABLE><BR><FONT color=#ff0000 size=2><STRONG>09年欧美最新小说改编悬疑战争剧情片《验伤》BD中字1024x576高清版 [下载地址]：<IMG border=0 src=\"httftp://www.3edyy.com/templets/img/down.jpg",483,879);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MP632H0-32109.jpg",881,964);
$z[8][4]['name']="litpic";

?>