{dede:field name='keywords'}自然：超级鱼类BD中字1024高清美{/dede:field}
{dede:field name='description'}自然：超级鱼类BD中字1024高清美国纪录片迅雷下载、免费下载，自然：超级鱼类BD中字1024高清美国纪录片Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}自然：超级鱼类BD中字1024高清美国纪录片{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-09-03{/dede:field}
{dede:field name='body'}<p>
	&nbsp;<img border="0" src="/uploads/allimg/c120524/133N42IH60-459D.jpg" style="max-width: 750px; max-height: 750px" /></p>
<p>
	◎译　　名　自然：超级鱼类<br />
	◎片　　名　The Natural World Superfish<br />
	◎年　　代　2008<br />
	◎国　　家　美国<br />
	◎类　　别　记录<br />
	◎语　　言　英语<br />
	◎字　　幕　中字<br />
	◎文件格式　BD-RMVB<br />
	◎视频尺寸　1024 x 576<br />
	◎文件大小　1CD<br />
	◎片　　长　0:50:10 (h:m:s)<br />
	◎导　　演　<br />
	◎主　　演　</p>
<p>
	◎简　　介　</p>
<p>
	&nbsp;&nbsp;&nbsp; 尖嘴鱼类是最大，最快，最危险的海洋物种。人类试图记录这些海洋生物，无论是曼妙的旗鱼，剑鱼和这些鱼类的王后--因海明威的《老人与海》而不朽的马林鱼。海洋生物学家和电影制作人里克罗森塔尔穿越三大洋把它们捕捉到胶片上，并藉此希望激发人类保护这种濒危物种的热情。</p>
<p>
	<img alt="" border="0" src="/uploads/allimg/c120524/133N42IaF-55635.jpg" /></p>
<p>
	<img alt="" border="0" src="/uploads/allimg/c120524/133N42J0010-B3Y.jpg" /></p>

<p>
	[下载地址]： &nbsp;<img border="0" src="/uploads/allimg/c120524/133N2Z4FF-102231.jpg" />
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:1476/飘花电影piaohua.com自然：超级鱼类BD中字1024高清.rmvb</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120524/133N42J3110-K2L.jpg{/dede:field}
