{dede:field name='keywords'}亲密HD1280高清迅雷下载，免费下{/dede:field}
{dede:field name='description'}亲密HD1280高清迅雷下载、免费下载，亲密HD1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}亲密HD1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-03-17{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://gb.cri.cn/mmsource/images/2009/03/02/eo090301919.jpg" style="width: 500px; height: 683px" /></p>
<p>
	导演: 岸西<br />
	编剧: 岸西<br />
	主演: 林嘉欣 / 郑伊健 / 骆应钧 / 许志安 / 曾国祥 / 曾志伟<br />
	类型: 剧情 / 爱情<br />
	制片国家/地区: 香港<br />
	语言: 普通话<br />
	上映日期: 2009-02-12<br />
	片长: 100 分钟<br />
	又名: 花非花 / Claustrophobia<br />
	IMDb链接: tt1303846<br />
	<br />
	　　影片《亲密》剧情<br />
	<br />
	　　爱情有如过滤性病毒，无声潜伏，借势蔓延。它偏爱狭小而挤逼的空间，例如大城市的办公室。<br />
	<br />
	　　故事的主角阿佩正深受其扰，独身的她不幸地对已婚的上司汤少产生不能自拔的爱意。他们这一支五人市务推广小组，每周五至六天每天八至十小时挨鼻子挨眼睛地干活。下班后，佩与其它三人：贪玩风骚的珠珠、木讷讷的松仔、及资历最老的球叔，总坐上汤少的顺风车回家。汤少无疑是照顾下属的好上司，但他温文和气的外表下，也许藏着一颗摸不透的心。<br />
	<br />
	　　&ldquo;这真是爱情吗？&rdquo;佩左思右想，忐忑不安。汤少即或对她有感觉，却从不表态，疑幻疑真。原本普通的同事关系，究竟是如何开始变质了？如今她该怎么办？这太磨人了！<br />
	<br />
	　　出乎意外地，她的疑难倒由汤少大刀阔斧地解决掉。也许他也感到事情正在不妙地变化。他推荐佩转职到别家公司。深感伤害的佩冷言拒绝，让汤干脆辞退她。两人的关系，遂以对峙告终。<br />
	<br />
	　　借着八场戏的篇幅，本片以结局为始，倒叙回溯这段乍隐乍现情缘的起承转合。最令人感到无奈的是，这种爱情故事多么普通、多么耳熟能详！每一天，每间办公室里，总有大同小异的故事在上演。办公室里头的人要不斗个你死我活，要不爱至两败俱伤。<br />
	<br />
	　　笔触细腻，近年屡获殊荣的编剧岸西首执导筒，剖析都市中的爱情心事。《亲密》像一首轻轻的旋律，淡淡的来，却萦绕不退。</p>
<p>
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120316/00/62564813201203160038591296198372094_001.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120316/00/62564813201203160038591296198372094_000.jpg" style="width: 720px; height: 405px" /><br />
	<br />
	&nbsp;</p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="&#13;&#10;ftp://dy125:piaohua@dy125.piaohua.com:7730/飘花电影piaohua.com亲密HD国语中字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:7730/飘花电影piaohua.com亲密HD国语中字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15R62Z-430D.jpg{/dede:field}
