{dede:field name='keywords'}南京/南京大屠杀迅雷下载，免费{/dede:field}
{dede:field name='description'}南京/南京大屠杀迅雷下载、免费下载，南京/南京大屠杀Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}南京/南京大屠杀{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2007-11-25{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://dygod1:dygod1@m18.dygod.com:8821/南京大屠杀/[电影天堂www.dygod.com]南京大屠杀.rmvb" target=_blank>ftftp://dygod1:dygod1@m18.dygod.com:8821/南京大屠杀/[电影天堂www.dygod.com]南京大屠杀.rmvb</A></TD></TR></TBODY></TABLE></div><ul class="mmlist{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MP434540-5V93.jpg{/dede:field}
