{dede:field name='keywords'}对某飞行员的追忆高清迅雷下载，{/dede:field}
{dede:field name='description'}对某飞行员的追忆高清迅雷下载、免费下载，对某飞行员的追忆高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}对某飞行员的追忆高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-03-19{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://ec2.images-amazon.com/images/I/51UNXqRcOHL.jpg" style="width: 392px; height: 500px" /></p>
<p>
	◎译　　名　对某飞行员的追忆<br />
	◎日文片名　とある飛空士への追憶<br />
	◎英文片名　The Recollections of a Certain Pilot/To Aru Hikuushi e no Tsuioku<br />
	◎年　　代　2011<br />
	◎国　　家　日本<br />
	◎类　　别　动画<br />
	◎语　　言　日语<br />
	◎IMDB评分 7.0/10 (16 votes)<br />
	◎IMDB链接 <a class="faqlink" endcolor="FF6600" href="http://www.imdb.com/title/tt2113091" index="0" startcolor="0066ff" state="OFF" style="color: #0066ff">http://www.imdb.com/title/tt2113091</a><br />
	◎片　　长　99 mins<br />
	◎导　　演　宍户淳<br />
	◎出　　演　神木隆之介...狩乃夏鲁鲁<br />
	　　　　　　竹富圣花...法娜<br />
	　　　　　　<br />
	<br />
	◎简　　介<br />
	<br />
	　　故事主要以一个架空的世界作为舞台，世界由中央海被分割成西方大陆与东方大陆，支配西方大陆的是神圣列凡姆皇国，支配东方大陆的是帝政天上皇国，两国不断进行战争。由德尔&bull;莫拉尔家实质掌管的列凡姆自治区桑&bull;马鲁蒂亚遭到敌国战斗机的袭击，统治者公爵狄艾古&bull;德尔&bull;莫拉尔被杀害。列凡姆皇国皇子卡尔罗&bull;列凡姆为了夺回与自己有婚约的狄艾古的女儿，组成第八特务舰队派遣前往东方，但移动迟缓的飞空舰艇无法突破对方的防御网，遭到全灭。</p>
<p>
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120319/08/62564813201203190829469613411116172_002.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120319/08/62564813201203190829469613411116172_001.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120319/08/62564813201203190829469613411116172_000.jpg" style="width: 720px; height: 405px" /><br />
	<br />
	&nbsp;</p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="&#13;&#10;ftp://dy125:piaohua@dy125.piaohua.com:7741/飘花电影piaohua.com对某飞行员的追忆BD中字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:7741/飘花电影piaohua.com对某飞行员的追忆BD中字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1B543Z-3CN.jpg{/dede:field}
