{dede:field name='keywords'}温馨家庭/亲子关系BD1280高清中{/dede:field}
{dede:field name='description'}温馨家庭/亲子关系BD1280高清中字迅雷下载、免费下载，温馨家庭/亲子关系BD1280高清中字Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}温馨家庭/亲子关系BD1280高清中字{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-10{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120509/23/17870980201205092329552115442951616_000.jpg" style="width: 600px; height: 751px" /></p>
<p>
	◎译　　名&nbsp;&nbsp;温馨家庭/亲子关系/温馨家族<br />
	◎片　　名&nbsp;&nbsp;Parenthood<br />
	◎年　　代　1989<br />
	◎国　　家　美国<br />
	◎类　　别　喜剧/剧情<br />
	◎语　　言　英语<br />
	◎字　　幕　英文<br />
	◎IMDB评分&nbsp;&nbsp;6.9/10 (21,681 votes)<br />
	◎IMDB链接&nbsp;&nbsp;<a href="http://www.imdb.com/title/tt0098067/" target="_blank">http://www.imdb.com/title/tt0098067/</a><br />
	◎片　　长　124 mins<br />
	◎导　　演　朗&middot;霍华德 Ron Howard<br />
	◎主　　演　史蒂夫&middot;马丁 Steve Martin ....Gil Buckman<br />
	　　　　　　玛丽&middot;斯汀伯根 Mary Steenburgen ....Karen Buckman<br />
	　　　　　　黛安娜&middot;维斯特 Dianne Wiest ....Helen Buckman<br />
	　　　　　　杰森&middot;罗巴兹 Jason Robards ....Frank Buckman<br />
	　　　　　　里克&middot;莫拉尼斯 Rick Moranis ....Nathan Huffner<br />
	　　　　　　汤姆&middot;休斯克 Tom Hulce ....Larry Buckman<br />
	　　　　　　玛莎&middot;普林顿 Martha Plimpton ....Julie Buckman<br />
	　　　　　　基努&middot;李维斯 Keanu Reeves ....Tod Higgins<br />
	　　　　　　Harley Jane Kozak ....Susan Buckman (as Harley Kozak)<br />
	　　　　　　丹尼斯&middot;杜根 Dennis Dugan ....David Brodsky<br />
	　　　　　　杰昆&middot;菲尼克斯 Joaquin Phoenix ....Garry Buckman-Lampkin (as Leaf Phoenix)<br />
	　　　　　　Eileen Ryan ....Marilyn Buckman<br />
	　　　　　　Helen Shaw ....Grandma<br />
	　　　　　　Jasen Fisher ....Kevin Buckman<br />
	　　　　　　Paul Linke ....George Bowman<br />
	　　　　　　Alisan Porter ....Taylor Buckman<br />
	　　　　　　Zachary La Voy ....Justin Buckman (as Zachary Lavoy)<br />
	　　　　　　Ivyann Schwan ....Patty Huffner<br />
	　　　　　　Alex Burrall ....Cool Buckman<br />
	　　　　　　Lowell Ganz ....Stan<br />
	　　　　　　Rance Howard ....Dean at College<br />
	　　　　　　Max Elliott Slade ....Young Gil Buckman<br />
	　　　　　　克林特&middot;霍华德 Clint Howard ....Lou<br />
	　　　　　　Lamont Lofton ....Fotomat Clerk<br />
	　　　　　　Erika Rafuls ....Amy<br />
	　　　　　　Steve Zurk ....Highway Policeman<br />
	　　　　　　Emil Felski ....Doctor at Hospital<br />
	　　　　　　Charmin Talbert ....Nurse at Hospital<br />
	　　　　　　Julie Lander ....Student in Hallway<br />
	　　　　　　Janet Moore ....Irate Woman in Audience<br />
	　　　　　　Connie Adams ....Cindy<br />
	　　　　　　布莱丝&middot;达拉斯&middot;霍华德 Bryce Dallas Howard ....Redheaded Girl in Audience (unconfirmed)<br />
	　　　　　　Matt Baylis ....Child in Auditorium (uncredited)<br />
	　　　　　　Howie Dorough ....Kid in Classroom (uncredited)<br />
	　　　　　　Jill Gable ....Baseball Fan (uncredited)<br />
	　　　　　　Robert Ghost ....Baseball Fan (uncredited)<br />
	<br />
	◎简　　介<br />
	<br />
	　　家家有本难念的经，而父亲正是维持和谐最重要的定音鼓。但在生活中就充斥着各式各样的家庭状况：有大学没念完就等着待产做妈妈的，也有一心过雅痞生活却未必满足的，当然，模范夫妻之间，也会有失调跟重新整理关系的时候&hellip;&hellip;然而重点是无论你有多背、多迷惘，家总在那里。　<br />
	<br />
	　　吉尔的生活就面临着这种情况，三个孩子的家庭本已经一团糟，此时却收到九岁儿子凯文老师的邀请。究竟发生了什么事？吉尔与妻子来到学校才知道，平时看起来略显内向的儿子已经无法与正常的孩子一起读书了。这下可急坏了吉尔，因为从小没有得到父亲足够的爱，他曾经发誓自己一定要做一个好父亲。面对这种情况，一场挽救儿子的行动开始了。　<br />
	<br />
	　　为了克服儿子的自卑心理，吉尔舍弃工作时间陪儿子打棒球，在生日会上扮牛仔逗儿子和他的小朋友们开心。一番折腾下来，本以为奏效的吉尔却发现这对凯文似乎丝毫没有帮助，这样他失望极了。而倒霉的事也接二连三地降临在他的头上，本来属于他的晋升机会突然被别人夺走了，一气之下，吉尔辞了职，此时妻子却告诉他已经怀上了第四个孩子，吉尔几乎陷入崩溃的边缘。　<br />
	<br />
	　　吉尔的妹夫&mdash;&mdash;科学家内森培养孩子的方式却完全不同，他早料到了吉尔过度放松的教育方式会产生不好的结果。虽然女儿只有四岁，但内森的目标是把她培养成天才。高等数学、西班牙语、柔道，缺了哪样也不行。还像吉尔的小儿子一样在地上打转转玩，那是绝对不行的，天才孩子要学会成熟。内森的这套教育方式不仅禁锢了小女儿的童心，更逼走了受到冷落的妻子，他要怎样挽救这个即将分裂的家庭呢？　<br />
	<br />
	　　当然对于教育这个问题，发愁的不仅只有爸爸，还有妈妈。单身妈妈巴克曼女士面对叛逆的女儿和儿子不知所措。女儿大学还没毕业就结了婚，还有了孩子，而儿子更是因为没办法得到正常的父爱，变得沉默寡言。　<br />
	<br />
	　　可怜天下父母心，他们能解决各自的家庭问题吗？到底怎样的教育方式才是正确的呢？在欢笑中，我们将得到答案。<br />
	<br />
	◎一句话评论<br />
	<br />
	It could happen to you.<br />
	<br />
	The director of &quot;Splash,&quot; &quot;Willow&quot; and &quot;Cocoon&quot; brings you a comedy about life, love and the gentle art of raising children.<br />
	<br />
	◎幕后制作<br />
	<br />
	　　在总结了自己的长处和短处后，著名导演朗&middot;霍华德决定继续回到自己擅长的平凡的故事中来，于是在1989年，他执导的《温馨家庭》中，霍华德将有趣的吉尔一家通过欢笑和亲情展现在观众面前，在笑声中理解&ldquo;家&rdquo;的含义。此片上映后极为卖座，一举拿下了1亿多的票房，并荣获了1990年第62届奥斯卡奖最佳女配角和最佳原创歌两项提名。&nbsp;</p>
<p>
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120509/23/17870980201205092303583099363208401_009.jpg" style="width: 640px; height: 360px" /></p>
<p>
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120509/23/17870980201205092303583099363208401_008.jpg" style="width: 640px; height: 360px" /></p>
<p>
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120509/23/17870980201205092303583099363208401_006.jpg" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.net" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy241:piaohua@117.41.229.29:2010/飘花电影piaohua.com温馨家庭BD1280高清中字.rmvb">ftp://dy241:piaohua@117.41.229.29:2010/飘花电影piaohua.com温馨家庭BD1280高清中字.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O159EF-42G7.jpg{/dede:field}
