{dede:field name='keywords'}快乐天堂：滚石30演唱会HD中字10{/dede:field}
{dede:field name='description'}快乐天堂：滚石30演唱会HD中字1024高清迅雷下载、免费下载，快乐天堂：滚石30演唱会HD中字1024高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}快乐天堂：滚石30演唱会HD中字1024高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-08-02{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="/uploads/allimg/c120524/133N42355060-132092.jpg" /></p>
<p>
	<img alt="点击查看下一张" border="0" src="/uploads/allimg/c120524/133N42355H0-14S15.gif" style="background-image: url(http://img2081.poco.cn/mypoco/myphoto/20110808/01/62821378201108080111223110531587302_001_640.jpg); width: 400px; height: 564px" /></p>
<p>
	<img alt="点击查看下一张" border="0" src="/uploads/allimg/c120524/133N42355H0-14S15.gif" style="background-image: url(http://img2081.poco.cn/mypoco/myphoto/20110808/01/62821378201108080111223110531587302_000_640.jpg); width: 750px; height: 529px" /></p>

<p>
	&#10026;片&nbsp;&nbsp;&nbsp; 名：快乐天堂滚石30演唱会<br />
	&#10026;歌&nbsp;&nbsp;&nbsp; 手：张震岳、杜德伟、邰肇玫、马宜中、王海玲、李丽芬、曹启泰、李正帆、辛晓琪、赵咏华、李度、赵之璧、曹兰、黄嘉千、马念先、杨芳仪、刚泽斌、卓文萱、Mc HotDog、林凡、黄鸿升(小鬼)、吴楚楚、郁可唯、潘嘉丽、泰武国小合唱团<br />
	&#10026;时&nbsp;&nbsp;&nbsp; 间：约90分<br />
	&#10026;IMDB评分：N/A&nbsp;<br />
	&#10026;IMDB链接：N/A</p>
<p>
	【简介】：</p>
<p>
	千呼万唤始出来！《快乐天堂 滚石30演唱会》11/27、28两日将在台北小巨蛋盛大举办。超大阵仗演出名单终于出炉，全新制作、众星云集，共计超过60组、超过80位艺人上台表演，八班班长卯足全力紧鑼密鼓展开秘密会议，是他们从来没有曝光过的演出内容，堪称全新制作的演出；近30位乐手阵容、演出曲数超过百首，挑战小巨蛋舞台、音响、灯光、硬体等多项专业纪录，制作预算不断追加再追加！相信这场演唱会绝对会让歌迷们流连忘返，回味无穷！</p>
<p>
	滚石30年来，陪伴着所有人的成长、爱情与梦想，网路上对于曲目的讨论，也不亚于对歌手名单的关切。从滚石创业第一张专辑《三人展》(1981)，吴楚楚、潘越云、李丽芬演唱，从潘越云的「我的思念」开启华语乐坛的美好盛世，30年来无数经典歌曲，歌迷们都如数家珍，希望透过最后精选出的一百首曲目，带给4、5、6、7年级，甚至更多不同世代的你们，除了现场的热情、奔放、宣泄，更有满满的温暖与回甘。</p>
<p>
	【演唱曲目】：</p>
<p>
	01.泰武国小12人&#10154;快乐天堂<br />
	02.张震岳&#10006;MC Hot Dog&#10154;我爱台妹<br />
	03.杜德伟&#10006;张震岳&#10154;锺爱一生<br />
	04.杜德伟&#10006;张震岳&#10154;爱我别走<br />
	05.马念先&#10154;跆拳道<br />
	06.张震岳&#10154;爱的初体验<br />
	07.MC Hot Dog&#10154;海海人生<br />
	08.吴楚楚&#10154;你的歌<br />
	09.邰肇玫&#10154;如果<br />
	10.马宜中&#10154;风中的早晨<br />
	11.杨芳仪&#10154;秋蝉<br />
	12.王海玲&#10154;忘了我是谁<br />
	13.卓文萱&#10154;一句话<br />
	14.黄鸿升&#10154;不屑<br />
	15.卓文萱&#10006;黄鸿升&#10154;爱的主旋律<br />
	16.刚泽斌&#10154;你在他乡<br />
	17.辛晓琪&#10154;承认<br />
	18.辛晓琪&#10154;最爱<br />
	19.赵咏华&#10154;玫瑰香<br />
	20.赵咏华&#10154;欢颜<br />
	21.李&nbsp; 度&#10154;尘缘<br />
	22.李&nbsp; 度&#10154;鬼迷心窍<br />
	23.林&nbsp; 凡&#10006;郁可唯&#10006;潘嘉丽&#10154;新不了情<br />
	24.李丽芬&#10154;得意的笑<br />
	25.周华健&#10154;黎明不要来 (粤语)<br />
	26.周华健&#10154;追 (粤语)<br />
	27.赵之璧&#10154;在你和天空之间<br />
	28.陈&nbsp; 升&#10154;拥挤的乐园<br />
	29.陈　升&#10006;曹启泰&#10154;秀我还是要上<br />
	30.郁可唯&#10006;李正帆&#10154;宁夏<br />
	31.陈&nbsp; 升&#10006;郁可唯&#10154;One Night in Beijing<br />
	32.陈&nbsp; 升&#10154;把悲伤留给自己<br />
	33.陈&nbsp; 升&#10006;曹启泰&#10154;Summer<br />
	&nbsp;</p>
<p>
	&nbsp;</p>
<p>
	<img alt="" height="422" src="http://pic.phyrefile.com/j/jo/jojoma/2011/07/27/0005.jpg" width="750" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="/uploads/allimg/c120524/133N2Z4FF-102231.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				&nbsp;&nbsp;ftp://dy44:piaohua@dy44.piaohua.com:1323/飘花电影piaohua.com快乐天堂：滚石30演唱会HD中字1024高清.rmvb</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120524/133N42355060-132092.jpg{/dede:field}
