{dede:field name='keywords'}赛德克·巴莱上/下2部BD1280高清{/dede:field}
{dede:field name='description'}赛德克·巴莱上/下2部BD1280高清迅雷下载、免费下载，赛德克·巴莱上/下2部BD1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}赛德克·巴莱上/下2部BD1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-21{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="/uploads/allimg/c120525/133O09230310-4T142.jpg" style="width: 650px" /><img alt="" src="/uploads/allimg/c120525/133O09231960-4cS3.jpg" style="width: 650px" /></p>
<p>
	译　　名　赛德克&middot;巴莱（上）太阳旗 （下）彩虹桥<br />
	片　　名　Warriors Of The Rainbow：Seediq Bale<br />
	年　　代　2011<br />
	地　　区　台湾<br />
	片　　长　274 Mins<br />
	类　　别　剧情 / 战争 / 历史<br />
	语　　言　赛德克语 / 日语 / 台语<br />
	IMDB评分 &nbsp;7.5/10 (1,062 votes)<br />
	IMDB链接 &nbsp;http://www.bluemv.com<br />
	导　　演　魏德圣 Te-Sheng Wei<br />
	主　　演　林庆台 Qing-tai Lin &hellip; 中年莫那鲁道<br />
	　　　　　游大庆 Da-qing You &hellip; 青年莫那鲁道<br />
	　　　　　马志翔 Zhixiang Ma &hellip; 铁木瓦利斯<br />
	　　　　　徐若瑄 Vivian Hsu &hellip; 高山初子<br />
	　　　　　安藤政信 Masanobu Ando &hellip; 小岛源治<br />
	　　　　　田中千绘 Chie Tanaka &nbsp;&hellip; 小岛源治妻<br />
	　　　　　河原佐武 Sabu Kawahara &hellip; 鎌田弥彦<br />
	　　　　　温岚 Landy Wen &hellip; 马红<br />
	　　　　　罗美玲 Lo Mei-Ling &hellip; 川野花子<br />
	　　　　　马如龙 Ju-Lung Ma &hellip; 汉人交易所头人 &nbsp;<br />
	　　　　　郑志伟 &hellip; 巫金墩<br />
	　　　　　吴朋奉 Pong-Fong Wu &hellip; 起义汉人<br />
	　　　　　苏达 Soda Voyu &hellip; 花岗二郎<br />
	　　　　　徐诣帆 Yi-Fan Hsu &hellip; 花岗一郎<br />
	　　　　　林源杰 Yuan-Jie Lin &hellip; 巴万&middot;那威<br />
	<br />
	简　　介<br />
	<br />
	　　　　　从前从前&hellip;在遥远的台湾山地里，有一支信仰彩虹的民族。 有一天他们遇见了来自北方一个信仰太阳的民族， 他们为了彼此的信仰而互相战争&hellip; 可是他们却忘了，原来他们信仰的是同一片天空&hellip; 赛德克，一个位于台湾山区、信仰彩虹的民族，他们居住在山岚缭绕的世外桃源，过着生态平衡的生活，族里马赫坡社出了一位英雄人物&#65112;马赫坡社头目之子莫那鲁道，首度&ldquo;出草&rdquo;猎回异族人头而声名大噪，自此各部落间无人不晓这个名字。但好景不长，日治时代的来临，赛德克族被迫改变原本生活，多数族里男人搬木服劳役，而女人沦为帮佣，眼看祖先辛苦建立的家园和猎场，在日方统治下逐渐消失，感到痛心的莫那鲁道，内心深信祖灵训示，唯有在自己的猎场，通过重重的试炼，在脸上纹上骄傲的印记，成为真正的赛德克人，在死后才能走上让祖灵认同的彩虹桥。 一九三○年，马赫坡社新来的日警因误会和族人起冲突，自此马赫坡社便活在恐遭日警报复的阴霾里，赛德克年轻人群聚要求战斗总头目莫那鲁道带领他们反击日本人，莫那清楚知道这是场必输的战役，更将赌上灭族危机，但他明白唯有挺身为民族尊严反击，才能成为&ldquo;真正骄傲的赛德克人&rdquo;，于是率领族内年轻人血祭祖灵，准备夺回属于他们的猎场。短时间内各部落纷纷起义，所有族人集合前往雾社公学校的运动会，三百个头绑白布起义的族人，发起为民族尊严而战的公学校大战&hellip;。 附加资料可能由生产商、供应商或第三者提供，并可能只有原文内容。<br />
	<br />
	上集：太阳旗<br />
	<br />
	　　其中，上集以象征日本的〈太阳旗〉为名，由1895年日军占领台湾开始，演至1930年雾社冲突，并酝酿着眼于雾社公学校事件爆发前后的描述。<br />
	<br />
	　　昭和5年10月27日（西元1930年），台湾总督府为纪念北白川宫能久亲王薨去，而举行台湾神社祭，雾社地区则照例举行联合运动会。当联合运动会开幕，所有日人、警察及其眷属齐聚公学校之际，赛德克雾社群之马赫坡、荷戈、波亚伦、斯库、罗多夫、塔罗湾等六部落赛德克族人，由雾社群马赫坡社头目莫那&middot;鲁道率领发难。<br />
	<br />
	　　当日清晨，雾社公学校（现今台电万大电厂雾社分部）运动会，由能高郡守小笠敬太郎主持开幕典礼，其他日本人都前来观礼，这时候预先埋伏的塞德克勇士，在莫那&middot;鲁道攻击号令下，立刻展开猛烈的突袭，在一阵毫无预警的混战中，将运动场内134位日人一一撂倒砍杀。<br />
	<br />
	　　另一方面，莫那&middot;鲁道命令次子巴索&middot;莫那（Baso Mona）潜入马赫坡山取材地、袭击日警，并命长子达多&middot;莫那（Tado Mona）潜入马赫坡社警察驻在所，亦将日警及其眷属全数格毙。后分成数队，切断日人对外的所有电话线路，陆续袭击各部落之警察驻在所，掳护弹药、枪械。藉此向雾社地区的各个部落宣告，反暴统治之圣战已经开打，终致纷纷群起向应。<br />
	<br />
	　　在震惊愤怒之余，日军旋即调度派遣驻扎台中、花莲的步兵与警力，区分两路向雾社方面挺进；莫那&middot;鲁道率领族人抗敌缠斗、辗转退守马赫坡石窟。一场双方分别为了资源与报复围剿、祖灵与灵魂尊严的异族战端，就此揭开序幕&hellip;&hellip;<br />
	<br />
	下集：彩虹桥<br />
	<br />
	　　下集〈彩虹桥〉则进一步描述日军大队兵力进犯，与莫那&middot;鲁道带领赛德克族浴血抵抗的过程，并深入刻画族人从容牺牲后，越过彩虹桥回归祖灵的故事。<br />
	<br />
	　　接续上集赛德克族发动公学校冲突事件，致使日人遭遇殖民占领以来最大的统治危机后，日本驻台陆军少将鎌田弥彦衔命调动高达三千名以上的军警，挟以山炮、机枪等优势武力，联合前往雾社讨伐。<br />
	<br />
	　　另一方面，原先对部落友善的巡查小岛源治，也因自己的妻儿在运动场上死于非命，愤怒痛苦地完全失去理智，而强迫莫那&middot;鲁道的世仇、屯巴拉社头目铁木&middot;瓦力斯出兵，协助日人打这场毫不擅长的山区游击战。<br />
	<br />
	　　然而，世代山居的赛德克族熟悉当地绝壁地势，导致增援的日军部队始终久攻不下，伤亡无数。眼看清剿不力，日军于是改以派遣飞机投掷毒气弹，形成了原住民以猎枪、柴刀、木棍等原始武器，对抗飞机、大炮的局势。经过近一个月的激烈对峙，抗日族人死伤惨重；赛德克妇女此时也为了使自己孩子、丈夫无后顾之忧，于是纷纷先行上吊自缢；残存的男人们则在脸孔纹上赛德克记号，誓死抵抗、宁死不屈。<br />
	<br />
	　　原本发誓要一天拿下雾社的鎌田弥彦，至此也不得不衷心佩服莫那&middot;鲁道的骁勇善战，深深感叹：&ldquo;三百名战士抵抗数千名大军，不战死便自尽&hellip;&hellip;为何我会在这遥远的台湾山区见到我们已经消失百年的武士精神？&hellip;&hellip;是这里的樱花开得太艳红了吗？&rdquo;<br />
	<br />
	　　为了灵魂自由，不惧牺牲战死的赛德克族人与勇士，越过彩虹桥、回归祖灵的旅程也于焉展开&hellip;&hellip;</p>
<p>
	<img alt="" src="/uploads/allimg/c120525/133O092330P-503S9.jpg" style="width: 720px; height: 405px" /><img alt="" src="/uploads/allimg/c120525/133O09234110-512011.jpg" style="width: 720px; height: 405px" /><br />
	<br />
	&nbsp;</p>
<p>
	【下载地址】</p>
<table bgcolor="#0099cc" border="0" cellpadding="10" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：http://www.xiaozhizhu.net</td>
		</tr>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy125:piaohua@dy125.piaohua.com:7876/飘花电影piaohua.com赛德克&middot;巴莱上(太阳旗)BD中字1280高清.rmvb</td>
		</tr>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy125:piaohua@dy125.piaohua.com:7876/飘花电影piaohua.com赛德克&middot;巴莱下(彩虹桥)BD中字1280高清.rmvb</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O09235150-52P54.jpg{/dede:field}
