{dede:field name='keywords'}多啦A梦剧场版-伸太的恐龙2006BD{/dede:field}
{dede:field name='description'}多啦A梦剧场版-伸太的恐龙2006BD1280高清迅雷下载、免费下载，多啦A梦剧场版-伸太的恐龙2006BD1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}多啦A梦剧场版-伸太的恐龙2006BD1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-18{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://nl0.upanh.com/b5.s28.d1/ac492d736e1f85fcbc6dfa91f98e7f63_43887160.a11112704vote0.jpg" style="width: 423px; height: 599px" /></p>
<p>
	【译　　名】　多啦A夢-大雄的恐龍/哆啦A梦-大雄的恐龙<br />
	<br />
	【片　　名】　Doraemon Nobita&#39;s Dinosaur<br />
	<br />
	【年　　代】　2006<br />
	<br />
	【语　　言】　日语<br />
	<br />
	【字　　幕】　 簡<br />
	<br />
	<br />
	<br />
	【概要】<br />
	<br />
	&nbsp; &nbsp; &nbsp; 《大雄的恐龙》（日语：のび太の恐竜，英文：Nobita&#39;s Dinosaur）），是藤子&middot;F&middot;不二雄的科幻漫画哆啦A梦中的第一部大长篇漫画作品，也是第一部哆啦A梦的动画电影。<br />
	最初在1975年，先有前身的短篇的漫画，刊登于增刊的周刊少年Sunday中，内容仅到第一次送哔龙回上古时代。1980年时，扩充原本的短篇内容，1980年3月15日公映，监督为福富博，在日本票房达15亿6000万日圆、观众数320万人。2006年又重新改编为大雄的恐龙2006的电影动画。<br />
	<br />
	【故事內容】<br />
	<br />
	&nbsp; &nbsp; &nbsp; 小夫炫耀自己家的暴龙趾骨化石。大雄眼红并信口开河表要找大整架恐龙化石，否则便用鼻子吃意大利粉。于是，他便前往图书馆借了些有关恐龙化石的书籍。后来他在附近的断层挖到一枚恐龙蛋的化石，并以时光布还原之后得到一只双叶颈龙，并以叫声将之命名为&ldquo;皮助（香港无线版：B仔）&rdquo;。很快大雄和它成为好朋友，但因它越长越大且被人发现，故大雄决定将他送回白垩纪时代。可是，后来却发现将它错送到上古的北美洲。于是，大雄一行人乘时光机再次回到恐龙时代，但途被欲抢皮助的神秘人追击，时光机因而故障，使大家必须靠自己沿着古陆块回到日本。<br />
	经过长时间的冒险，神秘人物再度出现希望获得皮助，原来是未来的违法恐龙猎人，要获得皮助卖钱，要大雄一行以交出皮助为条件，换取将他们用时光机送回家。大雄最后决定则想办法夺取时光机，但途中被发现而使静香、小夫、胖虎被抓，哆啦A梦和大雄赶往援救却进入陷阱，他们被放在基地中的恐龙竞技场中，恐龙猎人放出恐龙，在可能被吃的千钧一发下，原来该恐龙是吃过桃太郎饭团的恐龙，因此恐龙的协助在反败为胜，又配合赶到的时光巡逻队打败了恐龙猎人。最后在时光巡逻队的帮助下，将皮助带回它的故乡，同时也将众人送返20世纪。<br />
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120512/21/62564813201205122120183242160293446_003.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120512/21/62564813201205122120183242160293446_002.jpg" style="width: 720px; height: 404px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120512/21/62564813201205122120183242160293446_001.jpg" style="width: 720px; height: 404px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120512/21/62564813201205122120183242160293446_000.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120512/21/62564813201205122120183242160293446_000.jpg" style="width: 720px; height: 405px" /><br />
	&nbsp;</p>
<p>
	【下载地址】</p>
<table bgcolor="#0099cc" border="0" cellpadding="10" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.net" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy125:piaohua@dy125.piaohua.com:8058/飘花电影piaohua.com多啦A梦剧场版-伸太的恐龙BD中字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:8058/飘花电影piaohua.com多啦A梦剧场版-伸太的恐龙BD中字1280高清.rmvb</a></td>
		</tr>
		<tr>
		</tr>
	</tbody>
</table>
<br />{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1BH330-1R41.jpg{/dede:field}
