{dede:field name='keywords'}寻求庇护/躲避/存身BD中英双字12{/dede:field}
{dede:field name='description'}寻求庇护/躲避/存身BD中英双字1280高清迅雷下载、免费下载，寻求庇护/躲避/存身BD中英双字1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}寻求庇护/躲避/存身BD中英双字1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-02-07{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img165.poco.cn/mypoco/myphoto/20120128/20/5488623520120128204812056.jpg" style="width: 402px; height: 600px" /></p>
<p>
	◎译　　名　寻求庇护/躲避/存身<br />
	◎片　　名　Take Shelter<br />
	◎年　　代　2011<br />
	◎国　　家　美国/澳大利亚/墨西哥<br />
	◎类　　别　幻想/恐怖/惊悚<br />
	◎语　　言　英语<br />
	◎字　　幕　中字</p>
<p>
	◎IMDB评分 5.7/10 from 12,940 users<br />
	◎IMDB链接 <a href="http://www.imdb.com/title/tt1270761" target="_blank">http://www.imdb.com/title/tt1270761</a><br />
	◎文件格式　XviD + AC3<br />
	◎视频尺寸　640 x 272<br />
	◎文件大小　2CD 2 x 50 x 15MB<br />
	◎片　　长　122 Min<br />
	◎导　　演　杰夫&middot;尼科尔斯 Jeff Nichols<br />
	◎主　　演　迈克尔&middot;珊农 Michael Shannon&nbsp; &hellip;.Curtis<br />
	　　　　　　杰西卡&middot;查斯坦 Jessica Chastain&nbsp; &hellip;.Samantha<br />
	　　　　　　凯蒂&middot;米克松 Katy Mixon&nbsp; &hellip;.Nat<br />
	　　　　　　希亚&middot;温汉 Shea Whigham&nbsp; &hellip;.Dewart<br />
	　　　　　　Kathy Baker&nbsp; &hellip;.Sarah<br />
	　　　　　　雷&middot;迈克金农 Ray McKinnon&nbsp; &hellip;.Kyle<br />
	　　　　　　丽莎&middot;盖伊&middot;汉密尔顿 Lisa Gay Hamilton&nbsp; &hellip;.Kendra<br />
	　　　　　　Robert Longstreet&nbsp; &hellip;.Jim<br />
	　　　　　　Guy Van Swearingen&nbsp; &hellip;.Myers<br />
	◎简　　介　</p>
<p>
	　　《寻求庇护》聚焦的是柯蒂斯这个工薪阶层人物,他是一位好丈夫、好父亲,可是他却被一系列恐怖的噩梦所困扰。对他来说,那些噩梦和幻觉是一种末日启示,他感到一场巨大的毁灭性的风暴即将来临,这将威胁到他珍视的现实生活。柯蒂斯表面上是非常坚强的,他全力以赴地保护自己的家庭,包括他的妻子萨曼莎,以及六岁大的听力有障碍的女儿汉娜。所有的问题在于,柯蒂斯真正对抗的是风暴还是他自己的内心?</p>
<p>
	一句话评论</p>
<p>
	模这睬部扼电劲影焉的幽雅陪魅师力来自于隐主角珊迹农先生超凡谣的鞭演绎鸿。淫他使鹤得颐这妄个院角惊色漱具备搪扭莲曲藻的啃大毅男喧子邢主义哉却伤又忻极寂好枪的区别景于仗一辨名胰粗鲁的便蓝煮领渴。 &mdash;&mdash;Critic&rsquo;s Notebook</p>
<p>
	弓《章寻渝求宏庇护》宜很好地概反嘻映爱了属于美国永中西璃部的乡妈愁讹,新那些困颈扰浸主袒角的噩梦使缩这殖部影栗片蔗具脏备乍修正主义风泥格。 &mdash;&mdash;A Film Canon</p>
<p>
	《葱寻小求庇护纯》相摇比用尼跃克框尔森痕的第一治部迎作品,蓉是更昂上胸一层楼了,这是粮一惨部非常刷好梳的释个人化的电影息,彰显铜了导眯演非标凡的构舷筑焙紧张铀气氛驳的酞能力辕,他捕邢捉到士了绎人崖际交道流春中篙的骤细微私末徐节。 &mdash;&mdash;Bitchin&rsquo; Film Reviews</p>
<p>
	幕后制作</p>
<p>
	　　岩导演心瘩声别:</p>
<p>
	　　涸　埂　关仰于盾电赠影的创作背溶景徒,众年绩轻导梯演逻杰束夫&middot;施尼克尔森这损样荣说久道椰:野&ldquo;2008灾年的夏天校,蠢我烃开珠始写和《圾寻求汕庇焕护农》实,当军时徐我结婚睁未满垃一年表。鹏虽说那个时仲候,我轨的事业和个人生活都在塔朝积极沼的诌一面至发展铡,可是对于这个营世短界吊我总有囚种不安的感淫觉,操觉银得莹它将爆陷选入材一灸种擦可泥怕逢的危叫机之榨中氟。这薄种斋飘啦忽不定悄的焦业虑跳,沂一部球分货来自金开融危螟机的影响,一部分汞来韵自妊我个人成长必的执烦恼,久最主要冒的署原嘘因是狱我害怕失木去我价生踢命盂中最轩宝贵怀的东西狞。所诽有饭这燕一切不安硝定的情绪都宦被赔直雪接渗入到鞋《寻求延庇护》芭这已部睦电影瑶的人傈物塑锐造咆中吻。罢&rdquo;</p>
<p>
	　　筑　　关嫉于癣剧艰本者的醒创作初肛衷,尼谊克嚣尔椭森痢这样泽说道:悠&ldquo;我祟写雍《芍寻杆求柒庇护》狡是因为噶,漾我地相信站这世界上祷存廊在窄某植种类续似悉心射理暗示一样的潭能翻感知的页东造西钵。在我甘的谜生蓖活中衬,锁那样靡令廉人紧张律不蕊安域的锌感觉惠经枕常发真生而且是辉真乙真切切俺的,我先总穆觉宇得很多两美憎国孩人僻甚捏至桅是汁全婶世裴界的柔人都和泳我有郝类似爆的吃&ldquo;兄错觉&rdquo;栅,这不容梯否决树。邯这淡部电毫影是我奄抒芝发茹这种蒸情感的一旭种方式词,忠我橙试图用它婪来侦阐释那冲种没疆来消由的恐捧惧翻与春忧虑翌。运我急扦切地想突让我自己,让所屑有手观猜众方在影锤片荧的结彰尾处患找到仲应方有瘴的解答。可以移说真,刑我们整个摄制恬组就是在唁寻觅这个恳忽隐粳忽捻现的答颈案,这絮个娱初绚衷统也让撕我彦们更成团结。鸯&rdquo;</p>
<p>
	　　迈　　嗡关宇于独饵立电影厘的溶制作,尼克尔嘿森曾胰坦骆言:&ldquo;我写的晾剧本比都非常仔细枷,肃甚至有视醒觉效径果辕的判样图,这四可脂不像那些没有头脑棵的舵独喂立嘱电影噪脚本绝。抬虽样然像画图歉纸互这样的靛事敏情缉很樟麻镣烦兄,可站是我就赊想猫亲馅力亲吓为众。术在第降一部的挫折之皱后汗,风我还是对久拍五摄一部刹成本在200恭到500翱万美元愉之螺间的独立伍电影充筋满希冀,琅我体觉得派独立申电影不洁会柜且永远以不憎会屑死雨。&rdquo;</p>
<p>
	花絮</p>
<p>
	&middot;本家片主演茶迈克&middot;依珊农曾全凭借2008年淮的吼影彦片主《革悍命之路》提甄名脓奥斯卡孽。</p>
<p>
	&middot;灰《善寻洋求佑庇护》获戛纳电噪影节魏影躬评哆人如周粉大画奖 Critics Week Grand Prize,和潦最乘佳剧本像奖SACD Award。</p>
<p>
	<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120130/08/62564813201201300844552421805612401_002.jpg" style="width: 640px; height: 360px" /></p>
<p>
	<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120130/08/62564813201201300844552421805612401_001.jpg" style="width: 640px; height: 360px" /></p>
<p>
	<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120130/08/62564813201201300844552421805612401_000.jpg" style="width: 640px; height: 360px" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="&#13;&#10;ftp://dy125:piaohua@dy125.piaohua.com:7556/飘花电影piaohua.com寻求庇护DVD中字CD1.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:7556/飘花电影piaohua.com寻求庇护DVD中字CD1.rmvb</a></td>
		</tr>
	</tbody>
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="&#13;&#10;ftp://dy125:piaohua@dy125.piaohua.com:7556/飘花电影piaohua.com寻求庇护DVD中字CD2.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:7556/飘花电影piaohua.com寻求庇护DVD中字CD2.rmvb</a></td>
		</tr>
	</tbody>
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2768/飘花电影piaohua.com存身BD中英双字1280高清.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2768/飘花电影piaohua.com存身BD中英双字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1605SP-4P49.jpg{/dede:field}
