{dede:field name='keywords'}星际传奇2/漆黑一片2/超世纪战警{/dede:field}
{dede:field name='description'}星际传奇2/漆黑一片2/超世纪战警BD中英双字1024高清迅雷下载、免费下载，星际传奇2/漆黑一片2/超世纪战警BD中英双字1024高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}星际传奇2/漆黑一片2/超世纪战警BD中英双字1024高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-23{/dede:field}
{dede:field name='body'}<p>
	&nbsp;<img src="/uploads/allimg/c120525/133O0UY040-11K20.jpg" /></p>
<p>
	【中文片名】《星际传奇2/漆黑一片2/超世纪战警/天域战士》欧美超刺激动作科幻冒险大片DVD中英双字<br />
	【译　　名】The Chronicles of Riddick<br />
	【年　　代】2004年<br />
	【地　　区】美国<br />
	【类　　别】冒险/惊悚/科幻/动作<br />
	【语　　言】英语<br />
	【字　　幕】中英字幕<br />
	【IMDB评分】6.3/10 (33,732 votes)<br />
	【文件格式】DVDrip-RMVB<br />
	【视频尺寸】848 x 480<br />
	【电影整理】3E迅雷电影下载站(www.eee4.com)<br />
	【文件大小】3CD 374MB<br />
	【片　　长】119 Min<br />
	【导　　演】大卫&middot;杜西 David Twohy<br />
	【主　　演】范&middot;迪塞尔 （Vin Diesel）<br />
	　　　　　　范&middot;迪塞尔 （Vin Diesel）<br />
	　　　　　　柯姆&middot;菲尔 (Colm Feore)</p>
<p>
	【简　　介】：</p>
<p>
	　　故事接着上一集的5年之后，在未来的星际世界，经过降落酷热星球上的劫难后，喜欢在星际冒险的李迪克(文&middot;迪塞尔 饰)虽然摆脱了黑暗的控制，暂时逃脱了赏金猎手的追捕，却惊恐地发现自己陷入了一场声势浩大的星际大战之中。他自己也被一个宗教恶势力抓获，这个26世纪宗教战队&ldquo;第10十字军&rdquo;的头目，就是被称为&ldquo;星际之王&rdquo;的大恶棍洛德?马歇尔(科姆&middot;菲尔 饰)，也正是他发起了一系列的星际大战。<br />
	　　被俘虏后度过了一段黑暗的日子，李迪克幸得&ldquo;第四元素&rdquo;种族的大使亚伦(朱迪&middot;丹奇 饰)救出，并帮助他找回了身世之迷。一次意外的遭遇，使李迪克再次被困在一座地下监狱里，在那里他见到了上一集在酷热星球上认识的那个女孩&mdash;&mdash;基拉&mdash;&mdash;现在已经长成个大女孩了(艾莉莎&middot;黛娃洛丝 饰)。<br />
	　　此时，整个宇宙星际正笼罩在马歇尔的黑暗统治下，他的&ldquo;第10十字军&rdquo;军团在各个星系各个星球间横行霸道，笼络更多的魔鬼士兵，要吞噬掉星际间所有的正义和光明。马歇尔制造了庞大的机器战机队，配合&ldquo;坟墓&rdquo;号到处攻城侵地，他手下的士兵一个个更像怪物一般，似乎收买了所有的星际恶棍。<br />
	　　经过一翻努力后，李迪克终于带着基拉从地下监狱里逃了出来。在亚伦的帮助下，他们攻进了马歇尔的战舰&mdash;&mdash;&ldquo;坟墓&rdquo;号旗舰。与&ldquo;坟墓&rdquo;号旗舰的指挥官瓦寇(卡尔&middot;俄本 饰)发生一场大战后，李迪克终于夺下了这艘星际间最大的战舰，现在，他要面对的敌人是星际之王洛德，为了所有生活在星球上的活着和死去的生命，李迪克必须勇敢地继续他的战斗彻底地打败敌人&hellip;&hellip;3E迅雷电影下载站</p>
	【电影截图】：<br />
	电影来源：www.eee4.com<br />
	<img src="/uploads/allimg/c120525/133O0UZ120-1212T.jpg" />&nbsp;<br />
	<img src="/uploads/allimg/c120525/133O0UZD0-13Y91.jpg" />&nbsp;<br />
	<img src="/uploads/allimg/c120525/133O0U911P-14S41.jpg" /></p>
	欧美超刺激动作科幻冒险大片《星际传奇2》DVD中英双字 － 来自[3E迅雷电影站eee4.com]下载地址：<img border="0" src="/uploads/allimg/c120525/133O0U345P-1W926.jpg" /><br />
	&nbsp;</p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				</anchor>ftp://eee4.com:eee4@xl2.eee4.com:8801/[3E迅雷电影站www.eee4.com]星际传奇2[DVD中英双字]CD1.rmvb</td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				</anchor>ftp://eee4.com:eee4@xl2.eee4.com:8801/[3E迅雷电影站www.eee4.com]星际传奇2[DVD中英双字]CD2.rmvb</td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				</anchor>ftp://eee4.com:eee4@xl2.eee4.com:8801/[3E迅雷电影站www.eee4.com]星际传奇2[DVD中英双字]CD3.rmvb</td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				</anchor>ftp://dy44:piaohua@dy44.piaohua.com:3479/飘花电影piaohua.com星际传奇2BD中英双字1024高清.rmvb</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O0U91N0-159A8.jpg{/dede:field}
