{dede:field name='keywords'}星尘/星尘情缘BD1280高清迅雷下{/dede:field}
{dede:field name='description'}星尘/星尘情缘BD1280高清迅雷下载、免费下载，星尘/星尘情缘BD1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}星尘/星尘情缘BD1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-21{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://i.imagehost.org/0731/stardust.jpg" style="width: 600px; height: 885px" /></p>
<p>
	◎译　　名　星尘<br />
	◎片　　名　Stardust<br />
	◎年　　代　2007<br />
	◎国　　家　美国<br />
	◎类　　别　冒险/幻想/爱情<br />
	◎语　　言　英语/普通话<br />
	◎IMDB评分 8.1/10 (27,878 votes)<br />
	◎IMDB链接 <a class="faqlink" href="http://www.xiaozhizhu.net/">http://www.xiaozhizhu.net/</a><br />
	◎片　　长　128Mins<br />
	◎导　　演　马修&middot;沃恩 Matthew Vaughn<br />
	◎主　　演　米歇尔&middot;菲佛 Michelle Pfeiffer .....Lamia<br />
	　　　　　　查理&middot;考克斯 Charlie Cox .....Tristran<br />
	　　　　　　克莱尔&middot;丹尼斯 Claire Danes .....Yvaine<br />
	　　　　　　罗伯特&middot;德尼罗 Robert De Niro .....Captain Shakespeare<br />
	　　　　　　莎拉&middot;亚历山大 Sarah Alexander .....Empusa<br />
	　　　　　　本&middot;巴恩斯 Ben Barnes .....Young Dunstan Thorne<br />
	　　　　　　马克&middot;伯恩斯 Mark Burns .....New Bishop<br />
	　　　　　　Adam Buxton .....Sextmus<br />
	　　　　　　亨利&middot;卡维尔 Henry Cavill .....Humphrey<br />
	　　　　　　Jake Curran .....Bernard<br />
	　　　　　　Elwin &#39;Chopper&#39; David .....Pirate<br />
	　　　　　　Frank Ellis .....Mr. Monday<br />
	　　　　　　鲁伯特&middot;艾弗雷特 Rupert Everett .....Secondus<br />
	　　　　　　德克斯特&middot;弗莱彻 Dexter Fletcher .....Skinny Pirate<br />
	　　　　　　Adam Fogerty .....Pirate<br />
	　　　　　　Ricky Gervais .....Ferdy the Fence<br />
	　　　　　　Peter Goodall .....Tristian&#39;s Son<br />
	　　　　　　Olivia Grant .....Girl Bernard<br />
	　　　　　　Melanie Hill .....Ditchwater Sal<br />
	　　　　　　David Kelly .....Old Guard<br />
	　　　　　　Jordan Long .....Pirate<br />
	　　　　　　Kate Magowan .....Una<br />
	　　　　　　伊安&middot;麦克莱恩 Ian McKellen .....Narrator<br />
	　　　　　　Terry Murphy .....Very Old Pirate<br />
	　　　　　　彼德&middot;奥图 Peter O&#39;Toole .....King Of Stormhold<br />
	　　　　　　Nathaniel Parker .....Dunstan Thorne<br />
	　　　　　　Josie Rees .....Xenia<br />
	　　　　　　Joanna Scanlan .....Mormo<br />
	　　　　　　马克&middot;斯特朗 Mark Strong .....Septimus<br />
	　　　　　　Fuschia Sumner .....Victoria&#39;s Friend<br />
	　　　　　　Billie Whitelaw<br />
	　　　　　　马克&middot;威廉姆斯 Mark Williams<br />
	　　　　　　杰森&middot;弗莱明 Jason Flemyng .....Primus<br />
	　　　　　　西耶娜&middot;米勒 Sienna Miller .....Victoria<br />
	<br />
	<br />
	※※※※※※※　资料信息　※※※※※※※<br />
	<br />
	◎简　　介　<br />
	<br />
	　　不要向流星许愿，否则它就会变成女人&hellip;&hellip;故事开始于一个平静到让人昏昏欲睡的小村庄，由于村庄被一个鹅卵石城墙所包围，所以它也叫&ldquo;围墙村&rdquo;。虽然只是薄薄的一面城墙，却世世代代地保护着这里的村民，因为一墙之隔的外面世界，是一个平行宇宙，那里充满了魔幻与超自然的生物。生活在&ldquo;围墙村&rdquo;的特里斯坦&middot;索恩和所有的年轻人一样，对村里最美丽的姑娘维多利亚一见倾心，为了能够得到她的爱，他甚至许下了这个世界上最不可能完成的诺言：带回天上落下的星星。<br />
	<br />
	<br />
	　　为了能够完成许诺，特里斯坦不得不鼓足勇气穿越那道象征着禁忌的城墙，进入另一个世界--&ldquo;暴风之所&rdquo;，那是一个神秘的国度，到处都是永恒的魔法和流动的传奇，很快，特里斯坦就会完全融进这个独特的地域，成为其中的一个组成部分。<br />
	<br />
	<br />
	　　当特里斯坦走进&ldquo;暴风之所&rdquo;，最终找到了流星下落的位置时，他发现自己看到的不是预期中的陨石，而是一个美丽、勇敢的女人&hellip;&hellip;在进入大气层之时，&ldquo;流星&rdquo;不小心崴了脚，然而这只是一切不幸的开始而已，打从她脚落地开始，就有一系列的陷井在等着她，这个自称伊凡娜的&ldquo;<a href="http://www.qqtmb.com/cewangsu/" style="color: rgb(0,0,0); text-decoration: none">网速测试</a> <a href="http://www.qqtmb.com/sfz/" style="color: rgb(0,0,0); text-decoration: none">身份证号码和姓名</a> <a href="http://www.xiaozhizhu.net/" style="color: rgb(0,0,0); text-decoration: none">最新电影</a>流星女&rdquo;成了所有野心家围捕的猎物。特里斯坦就不用说了，即使没有陨石，他仍然要把伊凡娜带到维多利亚面前。除此之外，还有野蛮、残忍、邪恶的女巫，她想得到&ldquo;流星&rdquo;让青春永驻；国王的几个诡计多端的儿子，对于他们来说，得到&ldquo;流星&rdquo;，就等于得到王位。当然，这个过程中还有魔法师、小妖精以及一个会飞的海盗，他们因为各种各样的原因--有善意的，也有邪恶的，但他们的目的却只有一个，那就是伊凡娜的心脏。<br />
	<br />
	<br />
	　　特里斯坦为了自己那不可告人的小秘密，决定保护伊凡娜，虽然他不知道这场旅程会带来多少不可思议的遭遇，但被爱情冲昏了头脑的他已经顾不得许多了。如果特里斯坦能够在如此大规模的围追堵截中运用智慧活下来，他就会发现，自己对维多利亚的感情，只是一种对美的期待，并不是真正的爱情。而他的&ldquo;新欢&rdquo;伊凡娜强大的力量，不仅是一切混乱的根源，也是开启他身份之谜的关键钥匙。<br />
	<br />
	&nbsp;<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120516/15/62564813201205161527052366095934436_001.jpg" style="width: 650px; height: 366px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120516/15/62564813201205161527052366095934436_000.jpg" style="width: 650px; height: 366px" /></p>
<p>
	【下载地址】</p>
<table bgcolor="#0099cc" border="0" cellpadding="10" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.net/" target="_blank">http://www.xiaozhizhu.net/</a></td>
		</tr>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy125:piaohua@dy125.piaohua.com:8073/飘花电影piaohua星尘BD中英双字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:8073/飘花电影piaohua星尘BD中英双字1280高清.rmvb</a></td>
		</tr>
		<tr>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1594RF-31J2.jpg{/dede:field}
