{dede:field name='keywords'}钻石夜总会-20110918迅雷下载，{/dede:field}
{dede:field name='description'}钻石夜总会-20110918迅雷下载、免费下载，钻石夜总会-20110918Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}钻石夜总会-20110918{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-09-19{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="/uploads/allimg/c120524/133N42F2430-1VJ6.jpg" style="width: 600px; height: 445px" /></p>
<p>
	<img alt="" src="/uploads/allimg/c120524/133N42F360-1b121.jpg" style="width: 600px; height: 445px" /></p>

<p>
	节目介绍　　</p>
<p>
	《钻石夜总会》(英语：Diamond Club)是薛圣棻带领友松传播制作、利菁主持，台湾电视公司（台视）监制、旗下的综艺节目，节目口号是：&ldquo;《钻石夜总会》，奖金满天飞！&rdquo;节目内容完全找素人或职业特技者来表演，参赛者可获得奖金，每组参赛者最高奖金为原12000元，现10000元(新台币，以下皆同)。</p>
<p>
	&nbsp;<br />
	&nbsp;播出时间<br />
	台湾<br />
	　　星空传媒 STAR卫视中文台 台湾版（首播）</p>
<p>
	&nbsp;<br />
	　　首播：原来：每周六19:00~21:00</p>
<p>
	&nbsp;<br />
	　　改版后：每周六18:00~20:00</p>
<p>
	&nbsp;<br />
	　　重播：每周日18:00~20:00</p>
<p>
	&nbsp;<br />
	　　台视主频道（重播）</p>
<p>
	&nbsp;<br />
	　　每周日19:57~22:00</p>
<p>
	中国内地<br />
	　　星空卫视 中国台（不同步转播）</p>
<p>
	&nbsp;<br />
	　　首播：每周六19:00~21:00</p>
<p>
	&nbsp;<br />
	　　重播：每周日上午4:30~6:30</p>
<p>
	&nbsp;<br />
	&nbsp;规则<br />
	　　参赛者条件：不限年龄、性别、国籍。</p>
<p>
	&nbsp;<br />
	　　表演模式：不限才艺。</p>
<p>
	&nbsp;<br />
	　　表演时间：每组2分钟。</p>
<p>
	&nbsp;<br />
	　　每集有六位评审，每位评审桌上皆有&ldquo;加分钮&rdquo;与&ldquo;扣分钮&rdquo;。参赛者表演时，在该组表演时间内(2分钟)，每位评审依照各组表演内容，可从100元开始按加分钮或扣分钮以增加或扣除金额。每位评审最高可增加金额至2000元。</p>
<p>
	&nbsp;<br />
	　　五位评审给的金额之总和，即为该参赛者当周的得分。一组参赛者表演结束时所得的总金额，就是该组的奖励金，上限为10000元（原12000元）。评审上方屏幕将显示该组参赛者之奖励金。奖励金最高之组别，即为当周的卫冕者。</p>
<p>
	[下载地址]： &nbsp;<img border="0" src="/uploads/allimg/c120524/133N2Z4FF-102231.jpg" /></p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:1040/飘花电影piaohua.com钻石夜总会-20110605.rmvb</td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:1040/飘花电影piaohua.com钻石夜总会-20110612.rmvb</td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:1040/飘花电影piaohua.com钻石夜总会-20110619.rmvb</td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:1040/飘花电影piaohua.com钻石夜总会-20110626.rmvb</td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:1040/飘花电影piaohua.com钻石夜总会-20110703.rmvb</td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:1040/飘花电影piaohua.com钻石夜总会-20110717.rmvb</td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:1111/飘花电影piaohua.com钻石夜总会-20110724.rmvb</td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:1174/飘花电影piaohua.com钻石夜总会-20110731.rmvb</td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:1365/飘花电影piaohua.com钻石夜总会-20110821.rmvb</td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:1600/飘花电影piaohua.com钻石夜总会-20110918.rmvb</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120524/133N42F4450-205S9.jpg{/dede:field}
