{dede:field name='keywords'}古巨基.惊奇世界2011演唱会BD128{/dede:field}
{dede:field name='description'}古巨基.惊奇世界2011演唱会BD1280高清迅雷下载、免费下载，古巨基.惊奇世界2011演唱会BD1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}古巨基.惊奇世界2011演唱会BD1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-02-19{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="/uploads/allimg/c120525/133O0aa640-16191.jpg" style="width: 650px; height: 814px" /></p>
<p>
	古巨基以「Amazing World」作為主題概念，將紅館化身成主題樂園，與樂迷進入一個最多姿多彩、最「Amazing」的世界。<br />
	<br />
	發燒試機天碟&#8231;<br />
	1920 x1080i Full HD&#8231;<br />
	DTS- HD 96khz/24bit&#8231;<br />
	Dolby Digital Stereo&#8231;<br />
	<br />
	01. Welcome To Amazing World<br />
	02. 花灑<br />
	03. 年年有今日<br />
	04. 眼睛不能沒眼淚<br />
	05. Beauty And The Prince<br />
	06. 大雄<br />
	07. Once Upon A Time<br />
	08. 愛回家<br />
	09. The Lonely Pirate<br />
	10. 大師作品<br />
	11. 獨男<br />
	12. 傷追人<br />
	13. 必殺技<br />
	14. Flying With The Music<br />
	15. 歡樂今宵<br />
	16. 愛與誠<br />
	17. 心跳回憶/ 漂流教室/一生何求<br />
	18. 藍天與白雲<br />
	19. Hea<br />
	20. Space Fighter<br />
	21. 爆了<br />
	22. 勁歌金曲 3 - Party King<br />
	23. 地球很危險<br />
	24. 下次再見<br />
	25. 2012!?<br />
	26. 以你為榮<br />
	27. 時代<br />
	28. 義海豪情<br />
	29. 重複犯錯<br />
	30. What Is Amazing World?<br />
	31. 愛得太遲<br />
	32. 友共情<br />
	33. 第二最愛<br />
	34. Surprise!<br />
	35. 愛的解釋<br />
	36. The Story Behind<br />
	- My Theme Park<br />
	- Music Fairy<br />
	- I Got The Power<br />
	- Boom! Boom! Dance!<br />
	- Love Is Amazing<br />
	Screen:<br />
	<img alt="" src="/uploads/allimg/c120525/133O0b00I0-292a.jpg" /><img alt="" src="/uploads/allimg/c120525/133O0b05N0-34436.jpg" style="width: 350px; height: 197px" /><img alt="" src="/uploads/allimg/c120525/133O0b0W30-4Z49.jpg" style="width: 350px; height: 197px" /><img alt="" src="/uploads/allimg/c120525/133O0b1Y10-55K5.jpg" /><img alt="" src="/uploads/allimg/c120525/133O0b22160-C917.jpg" /><img alt="" src="/uploads/allimg/c120525/133O0b25330-NS4.jpg" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="/uploads/allimg/c120525/133O0T31310-42214.jpg" />&nbsp;&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy125:piaohua@dy125.piaohua.com:7622/飘花电影piaohua.com古巨基惊奇世界2011演唱会BD1280高清.rmvb</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O0b302P-TO4.jpg{/dede:field}
