{dede:field name='keywords'}摩天悍将/终极速度BD1280高清迅{/dede:field}
{dede:field name='description'}摩天悍将/终极速度BD1280高清迅雷下载、免费下载，摩天悍将/终极速度BD1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}摩天悍将/终极速度BD1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-15{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://attach.siluhd.com/data/attachment/forum/201205/08/141228i767442f11lh2b44.jpg.thumb.jpg" style="width: 700px; height: 917px" /></p>
<p>
	译　　名：摩天悍将/终极速度<br />
	原　　名：Terminal.Velocity<br />
	类　　型：动作<br />
	片　　长：102 分钟<br />
	上　　映：1994年<br />
	国　　家：美国<br />
	语　　言：英语<br />
	字　　幕：中字<br />
	链　　接：http://www.imdb.com/title/tt0111400/<br />
	评　　分：5.3/10 (2,079 votes)<br />
	导　　演：德兰 萨拉菲安Deran Sarafian<br />
	演　　员：查利 希恩Charlie Sheen<br />
	　　　　　　娜斯塔加 金斯基Nastassja Kinski<br />
	　　　　　　詹姆斯 甘多弗尼James Gandolfini<br />
	<br />
	简　　介：<br />
	　　跳伞教练迪奇.布罗迪新收了一名美女克里丝做学员，结果却卷入一场国际间谍事件。在一次跳伞练习时，克里丝的伞包没有打开，从高空直接坠落地面死亡。有关权威部门将这次意外事故的责任归咎于迪奇。万般无奈的情况下，迪奇只好靠自己的力量调查事情的真相，因为有迹象表明克里丝并没有死亡，而且她的身份很可能就是克格勃的间谍，任务是把一帮叛徒偷运到美国再把转往第三国的黄金追回。迪奇不但参与了这场间谍战，最后还爱上了克里丝......</p>
<p>
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120514/21/62564813201205142111551715161774377_002.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120514/21/62564813201205142111551715161774377_001.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120514/21/62564813201205142111551715161774377_000.jpg" style="width: 720px; height: 405px" /></p>
<p>
	<br />
	<br />
	&nbsp;</p>
<p>
	【下载地址】</p>
<table bgcolor="#0099cc" border="0" cellpadding="10" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.net" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy125:piaohua@dy125.piaohua.com:8060/飘花电影piaohua.com摩天悍将BD中字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:8060/飘花电影piaohua.com摩天悍将BD中字1280高清.rmvb</a></td>
		</tr>
		<tr>
		</tr>
	</tbody>
</table>
<br />{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15BFP-5W36.jpg{/dede:field}
