{dede:field name='keywords'}无畏上将高尔察克/海军上将高尔{/dede:field}
{dede:field name='description'}无畏上将高尔察克/海军上将高尔察克BD中英双字1024/1280高清迅雷下载、免费下载，无畏上将高尔察克/海军上将高尔察克BD中英双字1024/1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}无畏上将高尔察克/海军上将高尔察克BD中英双字1024/1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-16{/dede:field}
{dede:field name='body'}<p>
	<img alt="" border="0" onload="attachimg(this, 'load')" src="/uploads/allimg/c120525/133O091X440-221130.jpg" /></p>
<p>
	◎译　　名　《无畏上将高尔察克/海军上将高尔察克》08年俄罗斯大受好评战争历史<br />
	◎片　　名　Admiral<br />
	◎年　　代　2008<br />
	◎国　　家　俄国<br />
	◎类　　别　剧情/历史/战争<br />
	◎语　　言　俄语<br />
	◎字　　幕　简体中文<br />
	◎IMDB评分 7.2/10 (611 votes)<br />
	◎IMDB链接 http://www.imdb.com/title/tt1101026<br />
	◎文件格式　Bluray-RMVB<br />
	◎视频尺寸　1024 x 576、800x<br />
	◎文件大小　1CD<br />
	◎片　　长　124 Mins<br />
	◎导　　演　安德烈&middot;克拉夫库克 Andrei Kravchuk<br />
	◎主　　演　康斯坦丁&middot;哈宾斯基 Konstantin Khabensky ....Admiral Kolchak<br />
	　　　　　　丽扎&middot; 波亚尔斯卡娅 Liza Boyarskaya ....Anna Timireva<br />
	　　　　　　Sergei Bezrukov ....General Kappel<br />
	　　　　　　Anna Kovalchuk ....Sofia Kolchak<br />
	　　　　　　Yegor Beroyev ....Mikhail Smirnov<br />
	　　　　　　理查德&middot;波林热 Richard Bohringer ....General Janin<br />
	　　　　　　维克多&middot;维尔比斯基 Viktor Verzhbitsky ....Kerensky<br />
	　　　　　　Nikolai Burlyayev ....Nikolai II<br />
	　　　　　　费多尔&middot;邦达尔丘克 Fyodor Bondarchuk ....Director<br />
	　　　　　　Robert Dawson ....Senator Elihu Root<br />
	　　　　　　Vladislav Vetrov ....Sergey Timirev<br />
	　　　　　　巴巴拉&middot;布雷尔斯卡 Barbara Brylska ....Nanny of young Kolchak<br />
	<br />
	◎简　　介　<br />
	<br />
	高尔察克是和邓尼金齐名的白军著名将领，曾在日俄战争中与日本作战。第一次世界大战期间他任俄罗斯黑海舰队的司令。俄罗斯二月革命后他曾逃亡，后支持临时ZF，回到俄罗斯。在十月革命以后（1917年），他率领俄罗斯白军与苏联GCD领导的红军作战。他得到同盟国承认的俄国临时ZF的首领地位（1918年-1920年），后来被布尔什维克俘虏并处决。</p>
<p>
	<br />
	<br />
	幕后制作<br />
	<br />
	　　影片由安德烈&middot;克拉夫库克导演，他2005年的电影《寻找幸福的起点》获得了第55届柏林国际影展暨第28届儿童电影节最佳儿童电影及迅雷电影下载儿童评审团奖。主演是俄罗斯当红性格男星康斯坦丁&middot;哈宾斯基，他的《守夜人》、《守日人》在欧美电影圈有极高名气，他在好莱坞的新作《通缉令》最近也获得了不错的票房。<br />
	　　由Fox International发行的《无畏上将高尔察克》于10月9日刚刚上映，上周末在俄罗斯和乌克兰便一共获得了1280万美元的票房收入，初亮相便成为这两国的票房冠军。</p>
<p>
	【电影截图】：<br />
	<br />
	<img border="0" src="/uploads/allimg/c120525/133O091Y2Z-23M50.jpg" />&nbsp;<br />
	<img border="0" src="/uploads/allimg/c120525/133O091YV0-246209.jpg" />&nbsp;<br />
	<img border="0" src="/uploads/allimg/c120525/133O091Z420-25PA.jpg" /></p>

<p>
	【800分辨率版本截图】：<br />
	<br />
	<br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('/uploads/allimg/c120525/133O09191040-264061.jpg');" src="/uploads/allimg/c120525/133O09191040-264061.jpg" />&nbsp;<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('/uploads/allimg/c120525/133O091914P-2I4b.jpg');" src="/uploads/allimg/c120525/133O091914P-2I4b.jpg" />&nbsp;<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('/uploads/allimg/c120525/133O09191920-2U1T.jpg');" src="/uploads/allimg/c120525/133O09191920-2U1T.jpg" />&nbsp;<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('/uploads/allimg/c120525/133O09192240-2952D.jpg');" src="/uploads/allimg/c120525/133O09192240-2952D.jpg" />&nbsp;<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('/uploads/allimg/c120525/133O091925F-3034L.jpg');" src="/uploads/allimg/c120525/133O091925F-3034L.jpg" /></p>
	08年俄罗斯大受好评战争历史《无畏上将高尔察克》DVD中字1024x576高清版 －来自[www.eee4.cc]：<img border="0" src="/uploads/allimg/c120525/133O0U345P-1W926.jpg" /></p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				ftp://e17:e17@xl2.eee4.com:9306/[3E电影站www.eee4.com]无畏上将高尔察克DVD中字1024x576高清版.rmvb</td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				</anchor>ftp://d80:d80@ftp.eee4.com:1501/[3E迅雷电影站www.eee4.com]海军上将高尔察克DVD中字CD1.rmvb</td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				</anchor>ftp://d80:d80@ftp.eee4.com:1501/[3E迅雷电影站www.eee4.com]海军上将高尔察克DVD中字CD2.rmvb</td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				ftp://3e:3e@m1.3edyy.com:133/【3E电影院www.3edyy.com】海军上将高尔察克BD中字1024x432高清版.rmvb</td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				ftp://dy44:piaohua@dy44.piaohua.com:3430/飘花电影piaohua.com海军上将高尔察克BD中字1280高清.rmvb</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O09192960-319626.jpg{/dede:field}
