{dede:field name='keywords'}山海台湾迅雷下载，免费下载，Gv{/dede:field}
{dede:field name='description'}山海台湾迅雷下载、免费下载，山海台湾Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}山海台湾{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-03-12{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="/uploads/allimg/c120524/133N4V32K0-164b.jpg" style="width: 600px; height: 753px" /></p>
<p>
	◎片　　名　山海台湾<br />
	◎译　　名　Taiwan Where Mountains Meet The Sea<br />
	◎年　　代　2011<br />
	◎地　　区　台湾<br />
	◎类　　别　纪录/风光/音乐<br />
	◎IMDB评分&nbsp; N/A<br />
	◎IMDB链接&nbsp; N/A<br />
	◎语　　言　普通话<br />
	◎字　　幕　<br />
	◎片　　长　47 mins 39 seconds<br />
	◎导　　演　吴明达 Martin Wu<br />
	◎演奏乐团　长荣交响乐团 EVERGREEN SYMPHONY ORCHESTRA</p>
<p>
	◎简　　介　</p>
<p>
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 吴明达，一个坚持用最真诚的 手法表现最美好台湾的影片导演，一路走来宛如影音真理的行者，一直是主张创作反对抄袭瞟窃的坚持者！</p>
<p>
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 坚持原汁原味，坚持对大自然的敬畏！十年来，穿越了这块3万6千平方公里、成长600万年的土地---台湾。</p>
<p>
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 用最神圣最虔诚也最环保的地球心 带领觀众进入一个最诚真的美丽宝岛！ 计画每5年向喜爱这块土地的朋友做一次详尽的巡礼与报告。</p>
<p>
	<br />
	演奏曲目</p>
<p>
	序曲: 布农八部合音(片头) Bunun eight-part harmonic singing (Opening)</p>
<p>
	01. 望春风(Adolescent Longing)<br />
	02. 补破网(Mending the Fishnet)<br />
	03. 马兰情歌(Maiden of Malan)<br />
	04. 四季红(Loving the Year Round)<br />
	05. 望你早归(Longing for Your Return)<br />
	06. 青春岭(Mountain of Youth)<br />
	07. 河边春梦(Spring Dream at Riverside)<br />
	08. 高山组曲(Mountain Dances)<br />
	09. 桃花过渡(Tide Over with Romance)<br />
	10. 六月茉莉(Jasmine in June)<br />
	11. 秋风夜雨(Wind &amp; Rain in Autumn Night)<br />
	12. 采茶谣(The Ballad of Picking Tea Leaves)</p>
<p>
	片尾: 布农八部合音(片尾) Bunun eight-part harmonic singing (Ending)</p>
<p>
	特别收录: 阿里山火车进行曲 The Steam Train of Ali Muntain</p>
<p>
	<img alt="" src="/uploads/allimg/c120524/133N4V3360-211H.jpg" style="width: 720px; height: 405px" /><img alt="" src="/uploads/allimg/c120524/133N4V35230-31207.jpg" style="width: 720px; height: 405px" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="/uploads/allimg/c120524/133N2Z4FF-102231.jpg" />&nbsp;&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy125:piaohua@dy125.piaohua.com:7718/飘花电影piaohua.com山海台湾BD国语中字1280高清.mkv</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120524/133N4V362P-45400.jpg{/dede:field}
