{dede:field name='keywords'}传染病/世纪战疫/全境扩散BD1280{/dede:field}
{dede:field name='description'}传染病/世纪战疫/全境扩散BD1280高清迅雷下载、免费下载，传染病/世纪战疫/全境扩散BD1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}传染病/世纪战疫/全境扩散BD1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-12-19{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://t.williamgates.net/image-EA48_4EEC08F4.jpg" style="width: 650px; height: 822px" /></p>
<p>
	◎译　　名　传染病/世纪战疫(港)/全境扩散(台)<br />
	◎片　　名　Contagion<br />
	◎年　　代　2011<br />
	◎国　　家　美国/阿拉伯联合酋长国<br />
	◎类　　别　剧情/科幻/惊悚<br />
	◎语　　言　英语/普通话(部分对白)/粤语(部分对白)<br />
	◎字　　幕　英文/法文/西班牙文<br />
	◎IMDB评分 7.0/10 from 23,432 users<br />
	◎IMDB链接 <a href="http://www.imdb.com/title/tt1598778" target="_blank">http://www.imdb.com/title/tt1598778</a><br />
	◎文件格式　XviD + MP3<br />
	◎视频尺寸　624 x 352<br />
	◎文件大小　1CD 49 x 15MB<br />
	◎片　　长　107 MIns<br />
	◎导　　演　史蒂文&middot;索德伯格 Steven Soderbergh<br />
	◎主　　演　马特&middot;达蒙 Matt Damon&nbsp; &hellip;.Thomas Emhoff<br />
	　　　　　　玛丽昂&middot;歌迪亚 Marion Cotillard&nbsp; &hellip;.Dr. Leonora Orantes<br />
	　　　　　　凯特&middot;温丝莱特 Kate Winslet&nbsp; &hellip;.Dr. Erin Mears<br />
	　　　　　　裘德&middot;洛 Jude Law&nbsp; &hellip;.Alan Kru<a href="http://www.qqtmb.com/" style="color: rgb(0, 0, 0); text-decoration: none;">qq</a>mwiede<br />
	　　　　　　格温妮丝&middot;帕特洛 Gwyneth Paltrow&nbsp; &hellip;.Beth Emhoff<br />
	　　　　　　布莱恩&middot;科兰斯顿 Bryan Cranston&nbsp; &hellip;.Haggerty</p>
<p>
	<br />
	◎简　　介　</p>
<p>
	　　一个出国旅行者正准备把信用卡递到酒吧侍者的手上,一个商务会议在一片握手和问好中开始,一个男人在公交车上咳嗽&hellip;&hellip;</p>
<p>
	　　这些本没有关联的事情被一种传染病联系在了一起。</p>
<p>
	　　贝丝&middot;埃姆霍夫从香港出差回到明尼阿波利斯,身体不适,她觉得这只是坐飞机时间太久的结果。可是不料,两天之后她却死在了急诊室。医生告诉她悲痛的丈夫,这个女人的死因不明。</p>
<p>
	　　很快,相似的病例相继出现:现实剧烈的咳嗽、随后是高烧不退,接着是昏迷、脑出血,最后就是死亡。更为可怕的是,这种症状的患者正在全世界范围内出现,明尼阿波利斯、芝加哥、纽约、伦敦、巴黎、东京、香港都出现了<a href="http://www.anzhuo4.com/" style="color: rgb(0, 0, 0); text-decoration: none;">安卓</a>病例。这种传染病以不可预知的速度传播着,2个人、4个人、16个人,随后就是成百上千上亿人。医学无法解释和治疗这种新出现的病症,只能任由其肆无忌惮地传播。</p>
<p>
	　　全球性的恐慌开始产生。</p>
<p>
	　　在美国疾控中心,研究员们被动员起来对这种病毒进行研究,希望能破解出它的生物学密码,并以此为契机制作到治疗疾病的药物。部门主管齐弗博士为了能尽快找到攻克病毒的方法,不惜将年轻的女医生派往第一线工作。而与此同时,他在世界卫生组织的医学家们正在全力制作防疫疾病的疫苗。</p>
<p>
	　　死亡的人数越来越多,病菌更加肆虐,一种末世的情绪笼罩在了人们的心头。人们开始歇斯底里地要保住自己和家人的性命,治安一步一步变得混乱。一个活跃的专栏作家声称政府在这件事情上消极应对,而且没有告诉人们病毒背后的真相。</p>
<p>
	　　对传染病的恐惧开始变得和病毒一样可怕,并且传播得更快&ndash;在这种情况下,人类要何去何从呢?</p>
<p>
	<img alt="" src="http://img165.poco.cn/mypoco/myphoto/20111219/14/62564813201112191422542405817877124_003.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img165.poco.cn/mypoco/myphoto/20111219/14/62564813201112191422542405817877124_002.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img165.poco.cn/mypoco/myphoto/20111219/14/62564813201112191422542405817877124_001.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img165.poco.cn/mypoco/myphoto/20111219/14/62564813201112191422542405817877124_000.jpg" style="width: 720px; height: 405px" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="
ftp://dy125:piaohua@dy125.piaohua.com:7316/飘花电影piaohua.com传染病BD中英双字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:7316/飘花电影piaohua.com传染病BD中英双字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15X3910-15204.jpg{/dede:field}
