{dede:field name='keywords'}迷城/远雷HD国语中字1280高清迅{/dede:field}
{dede:field name='description'}迷城/远雷HD国语中字1280高清迅雷下载、免费下载，迷城/远雷HD国语中字1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}迷城/远雷HD国语中字1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-12-24{/dede:field}
{dede:field name='body'}<p>
	<img alt="" border="0" onclick="zoom(this)" onload="attachimg(this, 'load')" src="http://www.filmsh.com.cn/upload_show/5da6018c1e1b4c628d.jpg" /><br />
	<br />
	<img alt="" border="0" onclick="zoom(this)" onload="attachimg(this, 'load')" src="http://www.filmsh.com.cn/upload_show/69f160563b134232a5.jpg" /><br />
	<br />
	<br />
	<br />
	<br />
	◎译　　名　《迷城/远雷》霍思燕2010年国产最新爱情悬疑片DVD国语中字无水印<br />
	◎片　　名　Distant Thunder<br />
	◎年　　代　2010<br />
	◎国　　家　中国<br />
	◎类　　别　剧情/悬疑<br />
	◎语　　言　普通话<br />
	◎字　　幕　中文<br />
	◎文件格式　XviD + MP3<br />
	◎视频尺寸　624 x 352<br />
	◎文件大小　1CD 50 x 15MB<br />
	◎片　　长　96 Min<br />
	◎导　　演　章家瑞 Jiarui Zhang<br />
	◎主　　演　霍思燕 Siyan Huo....甘秀<br />
	　　　　　　郭晓然 Xiaoran Guo....赵坡<br />
	　　　　　　葛思然 Siran Ge....殷琪<br />
	　　　　　　唐以诺 Yinuo Tang....杜永庆<br />
	　　　　　　赵志刚 Zhigang Zhao....何昌兴<br />
	<br />
	◎简　　介　<br />
	<br />
	剧情简介<br />
	<br />
	　　《迷城》由一场迷幻的爱情开始，铺开一幕悬念迭起并引人深思的故事。贫困大学生赵坡(郭晓然 饰)暗恋上美貌的富家女大学生殷琪(葛思然 饰)，可是身份差异使他自卑不敢表达。一次偶遇，使他认识了清纯的发廊洗头妹甘秀(霍思燕 饰)，两人同病相怜渐生情愫。不久后，在一次同乡组织的游玩中，赵坡目睹甘秀被同乡侮辱后神秘失踪，神经大受刺激，内心懦弱的他便开始了一段漫长的梦魇&hellip;&hellip;<br />
	<br />
	◎剧　　照　<br />
	<br />
	<img alt="" border="0" onclick="zoom(this)" onload="attachimg(this, 'load')" src="http://www.filmsh.com.cn/upload_photo/5049bfac8fa44bc98f.jpg" /><br />
	<br />
	<img alt="" border="0" onclick="zoom(this)" onload="attachimg(this, 'load')" src="http://www.filmsh.com.cn/upload_photo/92681bf3a9c7449591.jpg" /><br />
	<br />
	<img alt="" border="0" onclick="zoom(this)" onload="attachimg(this, 'load')" src="http://www.filmsh.com.cn/upload_photo/763f8b9b49ae411c9f.jpg" /><br />
	<br />
	<img alt="" border="0" onclick="zoom(this)" onload="attachimg(this, 'load')" src="http://www.filmsh.com.cn/upload_photo/41f2ee01949347a9bf.jpg" /><br />
	<br />
	<img alt="" border="0" onclick="zoom(this)" onload="attachimg(this, 'load')" src="http://www.filmsh.com.cn/upload_photo/6b2f9f6a6ca0450f8b.jpg" /><br />
	<br />
	<img alt="" border="0" onclick="zoom(this)" onload="attachimg(this, 'load')" src="http://www.filmsh.com.cn/upload_photo/56f8b9f4d6d94aa18a.jpg" /><br />
	<br />
	幕后制作<br />
	<br />
	影片更名原因<br />
	<br />
	　　《迷城》原名《远雷》，寓址意&quot;远处的雷鸯声&quot;，通过讲述农村大学生赵坡(郭晓然饰)与发廊洗头妹甘秀(霍思燕饰)、富家学生殷琪(葛思然饰)之间，及赵破与民工杜永庆(唐以诺饰)之间错综离奇的故事情节，揭露社会底层人物的内心纠葛与灵橱魂救赎。 导演章家瑞表示，影片更名原因有三：一是&quot;远雷&quot;太抽象，难以吸引观众；二是&quot;迷城&quot;更富思想内涵，与影片主题更吻合：故事发生在重庆，是一个新兴城市，数不清的新生代民工和农村出身的大学生在城市里拼搏，有很多人成功了，但也有人在灯红酒绿之中陷入困境，在城市迷失了自我，因此叫《迷城》；另外，&quot;迷&quot;与&quot;谜&quot;同音，意指结局如何也是谜。<br />
	<br />
	为角色做出的努力<br />
	<br />
	　　开拍之前，为了贴近片中人物，几位男女主角都长时间地去体验生活：霍思燕前往发廊打工，葛思然在四川大学上课，郭晓然则在一个小山村里跟农民们一起挑粪、养猪、喂鸭子。<br />
	<br />
	　　《迷城》<a href="http://www.3edyy.com/" target="_blank">电影下载</a>是导演章家瑞的又一次大胆尝试，他把希区柯克式的惊悚悬疑和对社会底层小人物的关怀完美融合起来，通过贫困大学生赵坡(郭晓然饰)、发廊女甘秀(霍思燕饰)和富家校花殷琪(葛思然饰)之间的感情纠葛，真实而直接地描述出当下社会中小人物的生存状态。值得一提的是，在开拍之前，几位男女主角都长时间地去体验生活，其中，霍思燕就曾在洗头房里打工一个半月之久，有意思的是，因为霍思燕洗头技术过硬，所以不断有客人点名找她，霍思燕透露，&quot;甚至还有人非要点我不可，把我吓着了，不得不给章导演打电话&#39;求救&#39;。&quot;<br />
	<br />
	　　而葛思然为了让自己更具学生气息，开拍前她特意前往四川大学上学，吃在学校食堂，住在女生宿舍，上课时则在不同的班级和教室之间跑来跑去。《迷城》在大学生电影节上结束放映后，有观众表示，葛思然饰演的殷琪清纯而又善良，异常的真实。<br />
	<br />
	　　除了两位女主角外，男主角郭晓然和饰演两位民工的唐以诺与赵志刚，同样花了2个多月的时间去体验生活。据郭晓然透露，开机前他曾经被导演送到重庆巴南的一个小山村里，跟农民们一起挑粪、养猪、喂鸭子，活生生把自己的皮肤晒成了酱油色。唐以诺和赵志刚更是把自己弄得跟真正的&quot;力巴哥&quot;几乎没有区别，衣服是从&quot;力巴哥&quot;身上买来，鞋子竟然是道具师从垃圾堆里捡的，以至于两位演员时常被工作人员当成真正的&quot;力巴哥&quot;拦在片场外。<br />
	<br />
	花絮<br />
	<br />
	&middot;片中霍思燕有长达2分钟的全裸镜头，不过章家瑞透露审查后只保留了30秒。<br />
	<br />
	&middot;影片《迷城》全片都需要用重庆话对白，北京女孩霍思燕称为了学好重庆话自己练了一个多月，并找了一位语言老师时刻纠正自己的发音。<br />
	<br />
	&middot;霍思燕称为了更好的诠释&quot;洗头妹&quot;，自己被导演送到发廊培训。<br />
	<br />
	幕后故事<br />
	<br />
	　　由著名导演章家瑞指导，新晋力量葛思然、郭晓然、霍思燕（去她博客看看）联袂主演的悬疑惊悚大戏《迷城》(评论)将于10月22日登陆全国大荧幕，近日该电影多款海报曝光，其中，葛思然血染白裙，女鬼形象出镜的一款海报让人看后毛骨悚然，恐怖氛围升级，更增想一探究竟的欲望，而葛思然看到<a href="http://www.3ekk.com/" target="_blank">3e看看</a>海报后则称自己都被吓到，还是头一次以这种形象亮相。<br />
	<br />
	　　在惊悚、悬疑、恐怖及于一身的电影《迷城》即将上映之即，多款电影海报也随之曝光，而海报的出炉更是让恐怖氛围升级，葛思然身穿白色衣裙，沾染血迹，表情麻木的造型令人吓破胆，更让喜欢恐怖电影的观众增加一探究竟的欲望，而&quot;不带异性朋友别看&quot;的广告词也看出章家瑞导演对于影片恐怖程度的足够期许，对于首度参与进惊悚电影的葛思然称自己很害怕看恐怖电影，刚看到自己的这款海报时也着实被自己的形象吓了一跳，没想到效果会如此的逼真。<br />
	<br />
	　　《迷城》由一场凄美的爱情开始，铺开一幕悬念迭起并引人深思的故事。贫穷的大学生赵坡(郭晓然 饰)暗恋上美貌和智慧并存的富家女大学生殷琪(葛思然 饰)，可是身份差异使他自卑不敢表达。一次偶遇，使他认识了清纯的发廊洗头妹甘秀(霍思燕 饰)，两人同病相怜渐生情愫。不久后，在一次同乡组织的游玩中，赵坡目睹甘秀被同乡侮辱后神秘失踪，神经大受刺激，内心懦弱的他便开始了一段漫长的赎罪之旅&hellip;&hellip;据了解，该片内涵深刻、悬疑迭起。而为了制造心理惊悚效果，导演章家瑞与编剧邱刚健在影片中设计出&quot;救赎之谜&quot;、&quot;失踪之谜&quot;、&quot;结局之谜&quot;等一系列连环谜团，让观众在猜测中期待故事发展、在惊恐中联想故事结局。<br />
	<br />
	　　有影评家看完《迷城》后感触很深， 认为影片有着丰富的细节，错综复杂的情节设置，能够将观众带入一个潜意识的迷宫。在难分真假的世界里，《迷城》的主人公承受着梦和现实混淆不清的困惑，在表达现实与非现实，真实与虚幻的多套层结构与《盗梦空间》有许多相似之处。尤其是甘秀失踪后与男主角人鬼对话的桥段，和《盗梦空间》中多姆-科布(莱昂纳多-迪卡普里奥饰)的妻子死后变身为鬼侵入他梦中的情景有异曲同工之妙。<br />
	&nbsp;</p>
<p>
	【电影截图】：<br />
	<br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://photo5.zxip.com/albums5/folder10/7895/20101101143827/20101191252481902.jpg');" src="http://photo5.zxip.com/albums5/folder10/7895/20101101143827/20101191252481902.jpg" /><br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://photo5.zxip.com/albums5/folder10/7895/20101101143827/20101191252494995.jpg');" src="http://photo5.zxip.com/albums5/folder10/7895/20101101143827/20101191252494995.jpg" /><br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://photo5.zxip.com/albums5/folder10/7895/20101101143827/20101191252501519.jpg');" src="http://photo5.zxip.com/albums5/folder10/7895/20101101143827/20101191252501519.jpg" /></p>
<p>
	霍思燕2010年国产最新爱情悬疑片《迷城/远雷》DVD国语中字无水印 [下载地址]：<img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://3e:3e@m1.3edyy.com:1564/【3E看看www.3ekk.com】迷城[DVD国语中字无水印].rmvb" target="_blank">ftp://3e:3e@m1.3edyy.com:1564/【3E看看www.3ekk.com】迷城[DVD国语中字无水印].rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2426/飘花电影piaohua.com远雷HD国语中字1280高清.rmvb ">ftp://dy44:piaohua@dy44.piaohua.com:2426/飘花电影piaohua.com远雷HD国语中字1280高清.rmvb </a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1604S50-35308.jpg{/dede:field}
