{dede:field name='keywords'}穿靴子的猫/鞋猫剑客DVD中字2011{/dede:field}
{dede:field name='description'}穿靴子的猫/鞋猫剑客DVD中字2011美国奇幻冒险动画喜剧迅雷下载、免费下载，穿靴子的猫/鞋猫剑客DVD中字2011美国奇幻冒险动画喜剧Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}穿靴子的猫/鞋猫剑客DVD中字2011美国奇幻冒险动画喜剧{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-01-11{/dede:field}
{dede:field name='body'}<p>
	&nbsp;<img border="0" src="http://img2081.poco.cn/mypoco/myphoto/20111105/23/56634212201111052341193481680302229_000.jpg" /></p>
<p>
	<img border="0" src="http://img2081.poco.cn/mypoco/myphoto/20111105/23/56634212201111052341193481680302229_003.jpg" /></p>
<p>
	<img border="0" src="http://img2081.poco.cn/mypoco/myphoto/20111105/23/56634212201111052341193481680302229_002.jpg" /></p>
<p>
	<img border="0" src="http://img2081.poco.cn/mypoco/myphoto/20111105/23/56634212201111052341193481680302229_001.jpg" /></p>
<p>
	中文名：&nbsp;穿靴子的猫&nbsp;/&nbsp;靴猫外传&nbsp;/&nbsp;鞋猫剑客(台)&nbsp;/&nbsp;无敌猫剑客(港)<br />
	英文名：&nbsp;Puss&nbsp;in&nbsp;Boots&nbsp;<br />
	导演：&nbsp;克里斯&middot;米勒&nbsp;<br />
	主演：&nbsp;安东尼奥&middot;班德拉斯&nbsp;萨尔玛&middot;海耶克&nbsp;扎克&middot;加利费安纳基斯<br />
	上映日期：&nbsp;2011年10月28日&nbsp;&nbsp;&nbsp;美国<br />
	国家/地区：&nbsp;美国&nbsp;&nbsp;<br />
	类型：&nbsp;奇幻&nbsp;&nbsp;/&nbsp;&nbsp;冒险&nbsp;&nbsp;/&nbsp;&nbsp;动画&nbsp;&nbsp;/&nbsp;&nbsp;喜剧&nbsp;&nbsp;<br />
	片长：90&nbsp;分钟&nbsp;<br />
	分级：&nbsp;USA:PG&nbsp;<br />
	对白语言：&nbsp;英语&nbsp;&nbsp;<br />
	发行公司：&nbsp;派拉蒙影业公司<br />
	<br />
	<br />
	剧情简介<br />
	<br />
	　　其实和《怪物史莱克》中很多角色一样，&ldquo;穿靴子的猫&rdquo;也是来自经典童话里的著名角色，只不过在《怪物史莱克》中被小小的无厘头恶搞了一下。&ldquo;穿靴子的猫&rdquo;原来的童话故事说的是一个磨坊主的小儿子从父亲那里继承了一只聪明的猫，这只猫穿上靴子帮助磨坊主的儿子得到了国王的赏识，并促成了他和公主的婚姻。<br />
	　　不过在梦工厂版本的《穿靴子的猫》里，原本的童话可能会变得面目全非。安东尼奥&middot;班德拉斯说他看过剧本了，他很喜欢这个剧本，而且他透露整个故事是原创的，将从&ldquo;靴子猫&rdquo;小时候讲起，观众会看到他为什么要当杀手、他是如何成为杀手的，以及他又为什么放弃了这个行当。影片和《怪物史莱克》充满对流行文化的恶搞不同，将走另一条路，有点史诗，有时还会非常感人。<br />
	　　安东尼奥&middot;班德拉斯还透露《穿靴子的猫》的剧本前后一共创作了3年，他相信观众看到影片会大吃一惊的，因为这和他们期待的完全不同。<br />
	<br />
	<br />
	◎影片截图<br />
	<br />
	<img border="0" src="http://img2081.poco.cn/mypoco/myphoto/20111105/23/56634212201111052341193481680302229_007.jpg" /><br />
	<br />
	<img border="0" src="http://img2081.poco.cn/mypoco/myphoto/20111105/23/56634212201111052341193481680302229_006.jpg" /><br />
	<br />
	<img border="0" src="http://img2081.poco.cn/mypoco/myphoto/20111105/23/56634212201111052341193481680302229_005.jpg" /><br />
	<br />
	<img border="0" src="http://img2081.poco.cn/mypoco/myphoto/20111105/23/56634212201111052341193481680302229_004.jpg" /><br />
	&nbsp;<img border="0" src="http://img165.poco.cn/mypoco/myphoto/20120111/10/56643687201201111021131923167789133_001.jpg" /></p>
<p>
	<img border="0" src="http://img165.poco.cn/mypoco/myphoto/20120111/10/56643687201201111021131923167789133_002.jpg" /></p>
<p>
	<img border="0" src="http://img165.poco.cn/mypoco/myphoto/20120111/10/56643687201201111021131923167789133_003.jpg" /></p>
<p>
	<img border="0" src="http://img165.poco.cn/mypoco/myphoto/20120111/10/56643687201201111021131923167789133_000.jpg" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				&nbsp;<a href="ftp://dy44:piaohua@dy44.piaohua.com:2007/飘花电影piaohua.com穿靴子的猫TS中字.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2007/飘花电影piaohua.com穿靴子的猫TS中字.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2589/飘花电影piaohua.com鞋猫剑客DVD中字.rmvb">&nbsp;ftp://dy44:piaohua@dy44.piaohua.com:2589/飘花电影piaohua.com鞋猫剑客DVD中字.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1B00O0-46435.jpg{/dede:field}
