{dede:field name='keywords'}英雄本色3：夕阳之歌高清迅雷下{/dede:field}
{dede:field name='description'}英雄本色3：夕阳之歌高清迅雷下载、免费下载，英雄本色3：夕阳之歌高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}英雄本色3：夕阳之歌高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-08-12{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20110812/00/62564813201108120022291207845471365_000.jpg" /></p>
<p>
	◎中文　名　英雄本色3：夕阳之歌<br />
	◎片　　名　A Better Tommorrow III<br />
	◎年　　代　1989<br />
	◎地　　区　中国香港<br />
	◎类　　别　动作<br />
	◎语　　言　国语<br />
	◎字　　幕　中文<br />
	◎IMDB评分　5.7/10 (725 votes)<br />
	◎IMDB链接　<a href="http://www.imdb.com/title/tt0098691">http://www.imdb.com/title/tt0098691</a><br />
	◎文件格式　RMVB<br />
	◎视频尺寸　720P<br />
	◎文件大小　1.92G<br />
	◎片　　长　119 Min<br />
	◎导　　演　徐克 Hark Tsui<br />
	◎主　　演　周润发 Yun-Fat Chow .....Mark Gor (as Chow Yun Fat)<br />
	　　　　　　梁家辉 Tony Leung .....Cheung Chi Mun<br />
	　　　　　　梅艳芳 Anita Mui .....Chow Ying Kit<br />
	　　　　　　石坚 Jian Shi .....Pat<br />
	　　　　　　时任三郎 Sabur? Tokit? .....Ho Cheung Ching/Tanaka<br />
	　　　　　　Wai Lun Cheng<br />
	　　　　　　张可颐 Maggie Cheung<br />
	　　　　　　金杨桦 Andrew Kam<br />
	　　　　　　Ling Nam Lam</p>
<p>
	<br />
	◎简　　介　<br />
	　　越战时期，小马与堂弟志民在港任职修理技工，正值越南局势动荡，他们为筹款帮助志民父亲松叔离开西贡来香港，不惜铤而走险，联络当地大扩家周英杰，欲走私美金。不料遭丧邦的伏击，幸得周英杰相救。杰与小马在相识过程中惺惺相惜，暗生情愫。志民此时也对杰产生爱慕之情，三人在西贡渡过了一段美好的时光。不久，小马、志民与松叔返回香港，由于途中携带了一大笔冒着生命危险得来的美金，遭到越南海关人员的非难。幸亏周英杰在暗中帮助，才得已顺利返回香港。小马与志民回港后，开了一家汽车修理厂。其间不停打听杰的消息。一天，周英杰突然出现他们的面前，经历了生死与共，三人都欣喜若狂。但小马为避免兄弟二人同爱一女的尴尬境地，故意放纵自己，让杰十分伤心。杰的旧男友何长青失踪多时，此时突然出现。何长青了解到小马、志民与杰的关系后，想杀二人，却误将松叔杀害，还逼迫二人离开香港。志民深知杰内心所爱之人是小马，极力撮合二人远走高飞。但杰却认为此事皆因自己而起，决心与何长青作一了断。何长青为把在越南的产业转移到香港，与杰重返西贡。小马为寻找杰，也与志民冒着生命危险来到西贡。志民在和杰交谈中，与越南军人发生冲突，下落不明。小马误以为志民因杰而死，盛怒之中与杰不欢而散。死里逃生、身受重伤的志民向小马说明事实真相后，小马身怀爱恨情仇去找何长青了断恩怨。此时，丧邦在与何长青交易中双方发生火拼，杰自制炸弹，本想与何长青同归于尽，却被何长青发觉。乱战中，杰身受重伤，何长青也被丧邦杀死。最终，小马将丧邦除掉。此时，西贡陷入越共手中，小马、志民抱着身受重伤的杰冒着枪林弹雨逃往机场，离开西贡，在夕阳的照耀下，杰死在小马怀里。</p>
<p>
	幕后制作：<br />
	《英雄本色》是香港电影史上一个重大里程碑，承载着重大的文化及电影意义。它不仅以近三千五百万票房，打破香港票房纪录，更开创了一个新的电影类型英雄片。吴宇森凭此吐气扬眉，荣获金马奖最佳导演，成为日后进军好莱坞的踏脚石；周润发、狄龙、张国荣亦攀上事业另一高峰。其后，《英雄本色》接连拍成三部曲，每部票房均过千万。吴宇森亦树立了其独特的暴力美学风格，为香港电影制定了更高的美学标准。而身兼监制及导演的徐克，在《英雄本色III》中更能承先启后，将枪战的浪漫主义发挥至极点，影响及其深远，连带好莱坞导演都纷纷效尤。</p>
<p>
	<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20110812/00/62564813201108120022291207845471365_004.jpg" style="width: 600px; height: 338px" /></p>
<p>
	<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20110812/00/62564813201108120022291207845471365_003.jpg" style="width: 600px; height: 338px" /></p>

<p>
	<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20110812/00/62564813201108120022291207845471365_001.jpg" style="width: 600px; height: 338px" /></p>
<p>
	[英雄本色3：夕阳之歌下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="&#13;&#10;ftp://dy195:piaohua@dy195.piaohua.com:1027/飘花电影下载站www.xiaozhizhu.net英雄本色3：夕阳之歌.mkv">ftp://dy195:piaohua@dy195.piaohua.com:1027/飘花电影下载站www.xiaozhizhu.net英雄本色3：夕阳之歌.mkv </a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1BZJ0-24911.jpg{/dede:field}
