{dede:field name='keywords'}黑客帝国1BD中英双字1024/1280高{/dede:field}
{dede:field name='description'}黑客帝国1BD中英双字1024/1280高清迅雷下载、免费下载，黑客帝国1BD中英双字1024/1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}黑客帝国1BD中英双字1024/1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-03-24{/dede:field}
{dede:field name='body'}<p>
	<img border="0" src="http://www.eee4.com/0701pic/allimg/081023/001.jpg" /></p>
<p>
	<img alt="" src="http://i3.6.cn/cvbnm/a2/28/9b/562218b9f0d8e723cd2a07ba176941a0.jpg" /></p>
<p>
	<img alt="" src="http://i3.6.cn/cvbnm/00/21/11/a690771c553909ae5d96de49355282db.jpg" /><br />
	<br />
	◎译　　名　《黑客帝国1》经典动作大片科幻DVD中英双字1024x554版<br />
	◎片　　名　The Matrix<br />
	◎年　　代　1999<br />
	◎国　　家　美国<br />
	◎类　　别　动作/惊悚/科幻/冒险<br />
	◎语　　言　英语<br />
	◎字　　幕　中英双字<br />
	◎IMDB评分 8.6/10&nbsp; (296,454 votes)<br />
	◎IMDB链接 http://www.imdb.com/title/tt0133093/<br />
	◎文件格式　BD-RMVB<br />
	◎视频尺寸　1024 x 554<br />
	◎电影整理　3E电影下载站(www.eee4.com)<br />
	◎文件大小　3CD 856M<br />
	◎片　　长　136 min<br />
	◎导　　演　安迪&middot;沃卓斯基 Andy Wachowski<br />
	　　　　　　拉里&middot;沃卓斯基 Larry Wachowski<br />
	◎主　　演　基努&middot;李维斯 Keanu Reeves&nbsp; ....Neo<br />
	　　　　　　凯瑞-安&middot;莫斯 Carrie-Anne Moss&nbsp; ....Trinity<br />
	　　　　　　劳伦斯&middot;菲什伯恩 Laurence Fishburne&nbsp; ....Morpheus<br />
	　　　　　　雨果&middot;维文 Hugo Weaving&nbsp; ....Agent Smith<br />
	　　　　　　乔&middot;潘托里亚诺 Joe Pantoliano&nbsp; ....Cypher<br />
	　　　　　　格洛丽亚&middot;福斯特 Gloria Foster&nbsp; ....Oracle<br />
	　　　　　　Marcus Chong&nbsp; ....Tank<br />
	　　　　　　Julian Arahanga&nbsp; ....Apoc<br />
	　　　　　　Matt Doran&nbsp; ....Mouse<br />
	　　　　　　Belinda McClory&nbsp; ....Switch<br />
	　　　　　　Anthony Ray Parker&nbsp; ....Dozer<br />
	　　　　　　Paul Goddard&nbsp; ....Agent Brown<br />
	　　　　　　Robert Taylor&nbsp; ....Agent Jones<br />
	　　　　　　David Aston&nbsp; ....Rhineheart<br />
	　　　　　　Marc Gray&nbsp; ....Choi (as Marc Gray)<br />
	<br />
	◎简　　介　<br />
	<br />
	　　二十一世纪的某日，人类社会沦为电脑AI智能主体(MATRIX)的寄生物。一群电脑病毒似的幸存人类聚集在一起，试图颠覆由强大的电脑所建立的虚拟世界，然而MATRIX派出的电脑特警成为这一行动的最大死敌，人类的所有希望只有等待一位救世主的苏醒&mdash;&mdash;骇客&ldquo;尼欧&rdquo;！但这个被人们当作&ldquo;尼欧&rdquo;的人从未知道他所生活的世界其实是个幻境，难道他真的是尼欧么？请各位坐好，欢迎来到真实世界&hellip;&hellip;</p>
<p>
	【分辨率太大，请点击查看电影截图】：<br />
	<br />
	<img alt="" onclick="if(this.width&gt;screen.width-461) window.open('http://i3.6.cn/cvbnm/12/47/71/d002df9b80beb5748556f20c7c7db989.jpg');" src="http://i3.6.cn/cvbnm/12/47/71/d002df9b80beb5748556f20c7c7db989.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 325px; border-top: 0px solid; border-right: 0px solid" /></p>
<p>
	&nbsp;<img alt="" onclick="if(this.width&gt;screen.width-461) window.open('http://i3.6.cn/cvbnm/49/6e/22/1cd67b396a5d71fb06ea593c205c3865.jpg');" src="http://i3.6.cn/cvbnm/49/6e/22/1cd67b396a5d71fb06ea593c205c3865.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 325px; border-top: 0px solid; border-right: 0px solid" /></p>
<p>
	经典动作大片《黑客帝国》DVD中英双字1024x554版</p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<anchor></anchor><a href="ftp://e24:e24@xl2.eee4.com:1003/[3E电影站www.eee4.com]黑客帝国1[DVD中英双字1024x554版]CD1.rmvb" target="_blank">ftp://e24:e24@xl2.eee4.com:1003/[3E电影站www.eee4.com]黑客帝国1[DVD中英双字1024x554版]CD1.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<anchor></anchor><a href="ftp://e24:e24@xl2.eee4.com:1003/[3E电影站www.eee4.com]黑客帝国1[DVD中英双字1024x554版]CD2.rmvb" target="_blank">ftp://e24:e24@xl2.eee4.com:1003/[3E电影站www.eee4.com]黑客帝国1[DVD中英双字1024x554版]CD2.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<anchor></anchor><a href="ftp://e24:e24@xl2.eee4.com:1003/[3E电影站www.eee4.com]黑客帝国1[DVD中英双字1024x554版]CD3.rmvb" target="_blank">ftp://e24:e24@xl2.eee4.com:1003/[3E电影站www.eee4.com]黑客帝国1[DVD中英双字1024x554版]CD3.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<anchor></anchor><a href="ftp://dy44:piaohua@dy44.piaohua.com:1967/飘花电影piaohua.com黑客帝国1BD中英双字1024高清.rmvb "><u>ftp://dy44:piaohua@dy44.piaohua.com:1967/飘花电影piaohua.com黑客帝国1BD中英双字1024高清.rmvb </u></a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<anchor></anchor><a href="ftp://dy44:piaohua@dy44.piaohua.com:3070/飘花电影piaohua.com黑客帝国1BD中英双字1280高清.rmvb"><u>ftp://dy44:piaohua@dy44.piaohua.com:3070/飘花电影piaohua.com黑客帝国1BD中英双字1280高清.rmvb</u></a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O14c2350-3B45.jpg{/dede:field}
