{dede:field name='keywords'}交涉人：电影版/谈判专家电影版[{/dede:field}
{dede:field name='description'}交涉人：电影版/谈判专家电影版[DVD中字]迅雷下载、免费下载，交涉人：电影版/谈判专家电影版[DVD中字]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}交涉人：电影版/谈判专家电影版[DVD中字]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2010-10-06{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://5e:5e@m1.eee4.cc:1553/【3E电影院www.eee4.org】交涉人电影版[DVD中字].rmvb" target=_blank>ftftp://5e:5e@m1.eee4.cc:1553/【3E电影院www.eee4.org】交涉人电影版[DVD中字].rmvb</A></TD></TR></TBODY></TABLE></div><ul class="mmlist{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MP333630-51P2.jpg{/dede:field}
