<?php
$z[0]=Array("field","温柔的慈悲港台剧15迅雷下载，免",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","温柔的慈悲港台剧15迅雷下载、免费下载，温柔的慈悲港台剧15Gvod高清在线播放，剧情介绍等。",73,203);
$z[1][4]['name']="description";
$z[2]=Array("field","温柔的慈悲港台剧15",205,261);
$z[2][4]['name']="title";
$z[3]=Array("field","",263,302);
$z[3][4]['name']="writer";
$z[4]=Array("field","",304,343);
$z[4][4]['name']="source";
$z[5]=Array("field","2012-05-06",345,395);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",397,434);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://dy44:piaohua@dy44.piaohua.com:3162/飘花电影piaohua.com 温柔的慈悲EP01.rmvb",436,555);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MQ0E430-39326.jpg",557,640);
$z[8][4]['name']="litpic";

?>