<?php
$z[0]=Array("field","特种部队：眼镜蛇的崛起/百战英",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","特种部队：眼镜蛇的崛起/百战英雄/义勇群英之毒蛇风暴[TC国语＋迅雷下载、免费下载，特种部队：眼镜蛇的崛起/百战英雄/义勇群英之毒蛇风暴[TC国语＋Gvod高清在线播放，剧情介绍等。",72,284);
$z[1][4]['name']="description";
$z[2]=Array("field","特种部队：眼镜蛇的崛起/百战英雄/义勇群英之毒蛇风暴[TC国语＋",286,383);
$z[2][4]['name']="title";
$z[3]=Array("field","",385,424);
$z[3][4]['name']="writer";
$z[4]=Array("field","",426,465);
$z[4][4]['name']="source";
$z[5]=Array("field","2012-03-01",467,517);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",519,556);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://3e:3e@www2.eee4.com:775/[3E电影站www.eee4.cn]特种部队DVD中英双字CD1.rmvb\" target=\"_blank",558,691);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MOXX40-51535.jpg",693,775);
$z[8][4]['name']="litpic";

?>