{dede:field name='keywords'}至尊对决/现金BD中英双字1280高{/dede:field}
{dede:field name='description'}至尊对决/现金BD中英双字1280高清迅雷下载、免费下载，至尊对决/现金BD中英双字1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}至尊对决/现金BD中英双字1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-03-03{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://e18:e18@dm.eee4.com:1216/[3E电影站www.eee4.com]至尊对决CD1.rmvb" target="_blank{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MO620450-32601.jpg{/dede:field}
