{dede:field name='keywords'}叶问/一代宗师·叶问BD国语中字1{/dede:field}
{dede:field name='description'}叶问/一代宗师·叶问BD国语中字1024/1280高清迅雷下载、免费下载，叶问/一代宗师·叶问BD国语中字1024/1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}叶问/一代宗师·叶问BD国语中字1024/1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-02{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://e22:e22@dm.eee4.com:1216/[3E电影站www.eee4.com]叶问DVD国语中字高清晰版CD1.rmvb" target="_blank{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MO430620-192N.jpg{/dede:field}
