<?php
$z[0]=Array("field","叶问/一代宗师·叶问BD国语中字1",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","叶问/一代宗师·叶问BD国语中字1024/1280高清迅雷下载、免费下载，叶问/一代宗师·叶问BD国语中字1024/1280高清Gvod高清在线播放，剧情介绍等。",73,251);
$z[1][4]['name']="description";
$z[2]=Array("field","叶问/一代宗师·叶问BD国语中字1024/1280高清",253,333);
$z[2][4]['name']="title";
$z[3]=Array("field","",335,374);
$z[3][4]['name']="writer";
$z[4]=Array("field","",376,415);
$z[4][4]['name']="source";
$z[5]=Array("field","2012-05-02",417,467);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",469,506);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://e22:e22@dm.eee4.com:1216/[3E电影站www.eee4.com]叶问DVD国语中字高清晰版CD1.rmvb\" target=\"_blank",508,647);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MO430620-192N.jpg",649,732);
$z[8][4]['name']="litpic";

?>