<?php
$z[0]=Array("field","谷歌：时代精神2011.一年回顾高",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","谷歌：时代精神2011.一年回顾高清中英双字BD1280迅雷下载、免费下载，谷歌：时代精神2011.一年回顾高清中英双字BD1280Gvod高清在线播放，剧情介绍等。",72,256);
$z[1][4]['name']="description";
$z[2]=Array("field","谷歌：时代精神2011.一年回顾高清中英双字BD1280",258,341);
$z[2][4]['name']="title";
$z[3]=Array("field","",343,382);
$z[3][4]['name']="writer";
$z[4]=Array("field","",384,423);
$z[4][4]['name']="source";
$z[5]=Array("field","2012-02-07",425,475);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",477,514);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://dy241:xiaobajie@222.187.221.241:2009/小八戒电影xiaobajie.com谷歌：时代精神2011 一年回顾高清中英双字BD1280.rmvb",516,671);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MQ413520-4WB.jpg",673,755);
$z[8][4]['name']="litpic";

?>