<?php
$z[0]=Array("field","北京我的爱迅雷下载，免费下载，",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","北京我的爱迅雷下载、免费下载，北京我的爱Gvod高清在线播放，剧情介绍等。",73,187);
$z[1][4]['name']="description";
$z[2]=Array("field","北京我的爱",189,237);
$z[2][4]['name']="title";
$z[3]=Array("field","",239,278);
$z[3][4]['name']="writer";
$z[4]=Array("field","",280,319);
$z[4][4]['name']="source";
$z[5]=Array("field","2006-08-04",321,371);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<P>播放后双击视频“全屏”</P> \n<object classid=\"CLSID:22d6f312-b0f6-11d0-94ab-0080c74c7e95\" class=\"OBJECT\" id=\"MediaPlayer\" width=\"500\" height=\"350\" ><param name=\"ShowStatusBar\" value=\"-1\"><param name=\"Filename\" value=\"http://www.joykorea.com.cn/star/mv/beijingwodeai.asf\"></embed></object><br /> \n<P>下载地址<BR></P> <br>",373,732);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c120524/133N353DD0-2G248.gif",734,817);
$z[7][4]['name']="litpic";

?>