{dede:field name='keywords'}香水：一个谋杀犯的故事BD中英双{/dede:field}
{dede:field name='description'}香水：一个谋杀犯的故事BD中英双字1024/1280高清迅雷下载、免费下载，香水：一个谋杀犯的故事BD中英双字1024/1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}香水：一个谋杀犯的故事BD中英双字1024/1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-17{/dede:field}
{dede:field name='body'}<p>
	<img alt="Click here to open new window&#13;&#10;CTRL+Mouse wheel to zoom in/out" border="0" onclick="if(!this.resized) {return true;} else {window.open('/0701pic/2006-11-15/231107_02_771.jpg');}" onload="if(this.width&gt;screen.width*0.7) {this.resized=true; this.width=screen.width*0.7; this.alt='Click here to open new window\nCTRL+Mouse wheel to zoom in/out';}" onmouseover="if(this.width&gt;screen.width*0.7) {this.resized=true; this.width=screen.width*0.7; this.style.cursor='hand'; this.alt='Click here to open new window\nCTRL+Mouse wheel to zoom in/out';}" onmousewheel="return imgzoom(this);" pop="Click here to open new window&#13;&#10;CTRL+Mouse wheel to zoom in/out" resized="resized" src="/0701pic/2006-11-15/231107_02_771.jpg" style="cursor: hand" width="716" /><br />
	◎译　　名　杀手故事/香水/香水：一个谋杀犯的故事<br />
	◎片　　名　Perfume The Story of a Murderer<br />
	◎年　　代　2006<br />
	◎国　　家　德国/法国/西班牙<br />
	◎类　　别　惊悚/剧情<br />
	◎语　　言　英语<br />
	◎字　　幕　中文字幕<br />
	◎文件格式　DVD-RMVB<br />
	◎视频尺寸　640x256<br />
	◎文件大小　2CD/494MB<br />
	◎片　　长　2:15:35<br />
	◎导　　演　汤姆&middot;泰克维尔 Tom Tykwer<br />
	◎主　　演　达斯丁&middot;霍夫曼 Dustin Hoffman .... Guiseppe Baldini<br />
	　　　　　　艾伦&middot;里克曼 Alan Rickman .... Antoine<br />
	　　　　　　山姆&middot;道格拉斯 Sam Douglas ....<br />
	　　　　　　Paul Berrondo ....<br />
	　　　　　　Carmen Contreras ....<br />
	　　　　　　Corinna Harfouch .... Madame Arnulfi<br />
	　　　　　　Karoline Herfurth ....<br />
	　　　　　　Andr&eacute;s Herrera ....<br />
	　　　　　　Birgit Minichmayr ....<br />
	　　　　　　Jessica Schwarz ....<br />
	　　　　　　Sian Thomas ....<br />
	　　　　　　Ben Whishaw .... Jean-Baptiste Grenouille<br />
	　　　　　　雷切尔&middot;霍伍德 Rachel Hurd-Wood .... Laure Richis<br />
	　　　　　　Sara Forestier ....<br />
	　　　　　　Reg Wilson .... Customer, fish market<br />
	这将是最完美的香水。 以少女的绝妙体香为基底，含苞待放的芬芳为主干， 他将用这瓶香水，把她们的美永永远远地收藏&hellip;&hellip;<br />
	一个从出生身上就完全没有味道的男子葛奴乙，却是个嗅觉天才，他能制造出全世界最独一无二的杰出香水，这些香水的制作方式和一般的并无不同，唯一差别之处，是他所使用原料&mdash;处女的体香，只要是葛奴乙挑选中的女子，他便不计一切代价将她杀害，将新鲜的尸体身上的香味用来作成香水的材料，让这个香味永远只专属他一个人&hellip;&hellip;</p>
<p>
	花絮：<br />
	&middot;影片《欲望大酒店》（Rossini）　的原型就是S&uuml;skind和制片人Bernd Eichinger及众多迫切想把小说拍成电影的人，电影剧本由S&uuml;skind所写。片中古怪的Jakob Windisch就是他本人，Oskar Reiter的角色原型是Bernd Eichinger，众人争夺的是一部关于女妖Loreley的传奇小说的改编权，其他角色则是对慕尼黑媒体讽刺的写照。</p>
<p>
	<br />
	thunder://QUFmdHA6Ly8xMTAzMTU6OTlAMjE5LjE0Ny4xNy4xODgvybHK1rnKysJhLnJtdmJaWg==<br />
	thunder://QUFmdHA6Ly8xMTAzMTY6OTlAMjE5LjE0Ny4xNy4xODgvybHK1rnKysJiLnJtdmJaWg==2006-11-08</p>

<p>
	<img alt="" height="337" src="http://img.hdbird.com/cqlz/2010/06/29/5.jpg" style="cursor: pointer" width="600" /></p>
<p>
	<img alt="" height="337" src="http://img.hdbird.com/cqlz/2010/06/29/6.jpg" style="cursor: pointer" width="600" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.netftp//dy44:piaohua@dy44.piaohua.com:3142/" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3441/飘花电影piaohua.com香水：一个谋杀犯的故事BD中英双字1024高清.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3441/飘花电影piaohua.com香水：一个谋杀犯的故事BD中英双字1024高清.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3442/飘花电影piaohua.com香水：一个谋杀犯的故事BD中英双字1280高清.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3442/飘花电影piaohua.com香水：一个谋杀犯的故事BD中英双字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15C2a0-23491.jpg{/dede:field}
