{dede:field name='keywords'}沉默的羔羊BD中英双字1024/1280{/dede:field}
{dede:field name='description'}沉默的羔羊BD中英双字1024/1280高清迅雷下载、免费下载，沉默的羔羊BD中英双字1024/1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}沉默的羔羊BD中英双字1024/1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-09-29{/dede:field}
{dede:field name='body'}<p>
	<img alt="" height="708" src="http://img.album.pchome.net/54/68/89/49/b4460d18f379beda045ef89794ca3344.jpg" width="565" /><br />
	&nbsp;</p>
<p>
	◎译　　名　沉默的羔羊<br />
	◎片　　名　The Silence of the Lambs<br />
	◎年　　代　1991<br />
	◎国　　家　美国<br />
	◎类　　别　犯罪/惊悚<br />
	◎语　　言　英语<br />
	◎字　　幕　简体中英文<br />
	◎IMDB评分 8.7/10&nbsp; 207,926 votes Top 250: #24<br />
	◎文件格式　Bluray-RMVB<br />
	◎视频尺寸　1024 x 576<br />
	◎文件大小　1CD<br />
	◎片　　长　119 Mins<br />
	◎导　　演　乔纳森&middot;戴米 Jonathan Demme<br />
	◎主　　演　朱迪&middot;福斯特 Jodie Foster&nbsp; .... Clarice Starling<br />
	　　　　　　安东尼&middot;霍普金斯 Anthony Hopkins&nbsp; .... Dr. Hannibal Lecter<br />
	　　　　　　斯科特&middot;格伦 Scott Glenn&nbsp; .... Jack Crawford<br />
	　　　　　　安东尼&middot;哈德 Anthony Heald&nbsp; .... Dr. Frederick Chilton<br />
	　　　　　　泰德&middot;莱韦尼 Ted Levine&nbsp; .... Jame &#39;Buffalo Bill&#39; Gumb<br />
	　　　　　　弗兰奇&middot;费森 Frankie Faison&nbsp; .... Barney Matthews<br />
	　　　　　　卡西&middot;莱蒙斯 Kasi Lemmons&nbsp; .... Ardelia Mapp<br />
	　　　　　　Brooke Smith&nbsp; .... Catherine Martin<br />
	　　　　　　Paul Lazar&nbsp; .... Pilcher<br />
	　　　　　　丹&middot;巴特勒 Dan Butler&nbsp; .... Roden<br />
	　　　　　　Lawrence T. Wrentz&nbsp; .... Agent Burroughs<br />
	　　　　　　Don Brockett&nbsp; .... Friendly Psychopath in Cell<br />
	　　　　　　Frank Seals Jr.&nbsp; .... Brooding Psychopath in Cell<br />
	　　　　　　Stuart Rudin&nbsp; .... Miggs<br />
	　　　　　　Masha Skorobogatov&nbsp; .... Young Clarice Starling<br />
	　　　　　　Jeffrie Lane&nbsp; .... Clarice&#39;s Father<br />
	　　　　　　Leib Lensky&nbsp; .... Mr. Lang, Storage Manager<br />
	　　　　　　George &#39;Red&#39; Schwartz&nbsp; .... Mr. Lang&#39;s Driver (as Red Schwartz)<br />
	　　　　　　Jim Roche&nbsp; .... TV Evangelist<br />
	　　　　　　James B. Howard&nbsp; .... Boxing Instructor</p>
<p>
	◎简　　介　</p>
<p>
	剧情介绍<br />
	　　年轻的联邦调查局官员克拉丽斯&middot;斯达林接受了一项任务：帮助寻找一个失踪的妇女，而这个妇女正受到一个把受害者的皮剥下来的变态系列杀手的威胁。汉尼伯&middot;莱克特以前是位受人尊敬的精神病医生，现在却成精神变态者。克拉丽斯想通过与汉尼伯谈话来了解心理变态杀手的扭曲的心灵。联邦调查局警官杰克&middot;克劳福特认为汉尼伯非常聪明机智，通过与他谈话有助于发现案犯。克拉丽斯必须在汉尼伯透露任何情况之前努力赢得他的信任。</p>
<p>
	　　看点：1992年3月30日在第64届奥斯卡金像奖颁奖揭晓中，经过一番激烈地角逐，《沉默的羔羊》获得最佳影片奖，乔纳森.德默获最佳导演奖，男主角安东尼.霍普金斯获得最佳男主角奖，女主角朱迪.福斯特获最佳女主角奖，特德.塔利获最佳编剧奖。</p>
<p>
	　　《沉默的羔羊》一片影响持久不衰，引起了公众对社会犯罪、恐怖以及邪恶势力的憎恶和谴责。该片中联邦调查局的特工以及罪犯多数取自生活原型。拍摄前，主要创作人员全部到联邦调查局实地体验生活，女主角克拉丽斯的扮演者朱迪.福斯特在那里会见了她的原型，联邦特工玛丽.克劳斯；而朱迪.福斯特本人是曾刺杀里根的凶手欣克利追逐的目标。由于对犯罪的痛恨以及杰出的演技，朱迪成功地塑造了一个不畏强暴,勇敢而不失温柔经得住考验的女特工形象。</p>
<p>
	　　在《沉默的羔羊》这部影片里，最使人惊心动魄的场面是汉尼巴尔的扮演者安东尼.霍甫金斯的表演，他不愧是一位杰出的演员，其表演才能让人惊叹不已。在谈到《沉默的羔羊》时霍甫金斯说：&quot;我的方法十分简单，我记住对白，然后分析、思考角色，当我找准了角色的基调时一切都迎刃而解了。&quot;当朱迪.福斯特扮演的联邦局特工克拉丽斯第二次去精神病院见汉尼巴尔时，只见汉尼巴尔沉静地坐在铁栏后面，目光呆滞而深远地久久凝视着前方。突然他伸出舌头，口头发出&quot;嘶噜嘶噜&quot;的声音，仿佛在舔食着什么美味。这段表演既无对白也几乎没有动作，却产生了令人毛骨耸然的强烈效果。在《沉默的羔羊》中，霍甫金斯凭藉只有三十分钟却令人着迷的表演，把汉尼巴尔这个智商极高、思维敏捷、患有精神分裂症的食人魔的形象刻画得非常出色。这是个颇具挑战性的角色，非一般演员所能驾驭。霍甫金斯之所以如此成功，完全得益于他与生俱来的一个伟大演员所必需具有的艺术禀赋和几十年的舞台经验。</p>
<p>
	　　该片上映后连续5周居票房第一，仅第一周的票房收入就达1500万美元。即便这样，也无法扭转奥利安(Orion）公司破产的厄运。《沉默的羔羊》是该公司正式宣告破产前拍摄的最后一部影片，我们以后再也不会看到奥利安(Orion）的名字了。</p>
<p>
	<img alt="" height="323" src="http://img.album.pchome.net/54/71/45/14/3087fe33d506bebcdc9edeca937aadf7.jpg" style="cursor: pointer" width="600" /></p>
<p>
	<img alt="" height="323" src="http://img.album.pchome.net/54/71/45/14/8b794d813eb0911bc902ee5d2dfb09f6.jpg" style="cursor: pointer" width="600" /></p>
<p>
	<img alt="" height="323" src="http://img.album.pchome.net/54/71/45/14/6b3289c4790348beefc7491277be9b5a.jpg" style="cursor: pointer" width="600" /></p>
<p>
	[下载地址]： &nbsp;<img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" /></p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:1682/飘花电影piaohua.com沉默的羔羊BD中英双字1024高清.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:1682/飘花电影piaohua.com沉默的羔羊BD中英双字1024高清.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:1682/飘花电影piaohua.com沉默的羔羊BD中英双字1280高清.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:1682/飘花电影piaohua.com沉默的羔羊BD中英双字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1602M60-31522.jpg{/dede:field}
