<?php
$z[0]=Array("field","惊魂记/精神病患者[BD中英双字12",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","惊魂记/精神病患者[BD中英双字1280x720高清版]迅雷下载、免费下载，惊魂记/精神病患者[BD中英双字1280x720高清版]Gvod高清在线播放，剧情介绍等。",73,253);
$z[1][4]['name']="description";
$z[2]=Array("field","惊魂记/精神病患者[BD中英双字1280x720高清版]",255,336);
$z[2][4]['name']="title";
$z[3]=Array("field","",338,377);
$z[3][4]['name']="writer";
$z[4]=Array("field","",379,418);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-09-10",420,470);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",472,509);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://3e:3e@d8.3edyy.com:184/【3E电影院www.eee4.cc】精神病患者BD中英双字1280x720高清版.rmvb\" target=\"_blank",511,657);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MQ364M0-34010.jpg",659,742);
$z[8][4]['name']="litpic";

?>