{dede:field name='keywords'}星际十大经典迅雷下载，免费下载{/dede:field}
{dede:field name='description'}星际十大经典迅雷下载、免费下载，星际十大经典Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}星际十大经典{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2006-09-14{/dede:field}
{dede:field name='body'}http://fmtv.uying.com/游戏视频/星际十大经典.wmv{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120524/133N353DD0-2G248.gif{/dede:field}
