{dede:field name='keywords'}人性污点BD中英双字1280高清经典{/dede:field}
{dede:field name='description'}人性污点BD中英双字1280高清经典爱情惊悚迅雷下载、免费下载，人性污点BD中英双字1280高清经典爱情惊悚Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}人性污点BD中英双字1280高清经典爱情惊悚{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-03-27{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://apollo.s.dpool.sina.com.cn/nd/dataent/moviepic/pics/20/moviepic_1849143a259aa48797aa5be623b6adf1.jpg" /></p>
<p>
	【译　　名】　人性的污点/人性本色<br />
	【片　　名】　The Human Stain<br />
	【年　　代】　2003<br />
	【国　　家】　美国/德国/法国<br />
	【字幕语言】 中文/英文<br />
	【视频尺寸】 1280&times;720<br />
	【文件格式】 RMVB+AAC<br />
	【类　　别】　剧情/爱情/惊悚<br />
	【语　　言】　英语中英双字<br />
	【IMDB评分】&nbsp;&nbsp; 6.3/10 (15,718 votes)<br />
	【片　　长】　108 Mins<br />
	【导　　演】　罗伯特&middot;本顿 Robert Benton<br />
	【主　　演】　安东尼&middot;霍普金斯 Anthony Hopkins ....Coleman Silk<br />
	　　　　　　妮可&middot;基德曼 Nicole Kidman ....Faunia Farley<br />
	　　　　　　艾德&middot;哈里斯 Ed Harris ....Lester Farley<br />
	　　　　　　加里&middot;西尼斯 Gary Sinise ....Nathan Zuckerman<br />
	　　　　　　文特沃斯&middot;米勒 Wentworth Miller ....Young Coleman Silk<br />
	　　　　　　杰茜达&middot;芭瑞特 Jacinda Barrett ....Steena Paulsson<br />
	　　　　　　Harry J. Lennix ....Mr. Silk<br />
	　　　　　　克拉克&middot;格雷格 Clark Gregg ....Nelson Primus<br />
	　　　　　　Anna Deavere Smith ....Mrs. Silk<br />
	　　　　　　Lizan Mitchell ....Ernestine<br />
	　　　　　　凯丽&middot;华盛顿 Kerry Washington ....Ellie<br />
	　　　　　　Phyllis Newman ....Iris Silk<br />
	　　　　　　玛格&middot;马丁戴尔 Margo Martindale ....Psychologist<br />
	　　　　　　Ron Canada ....Herb Keble<br />
	　　　　　　米莉&middot;阿威塔尔 Mili Avital ....Young Iris<br />
	　　　　　　Danny Blanco ....Walter (as Danny Blanco)<br />
	　　　　　　Kristen Blevins ....Young Ernestine (as Kristen Blevins)<br />
	　　　　　　安妮&middot;达德克 Anne Dudek ....Lisa Silk<br />
	　　　　　　Mimi Kuzyk ....Professor Delphine Roux<br />
	　　　　　　John Finn ....Louie Borero<br />
	　　　　　　Jessica Winterstern ....Student<br />
	　　　　　　杰夫&middot;帕里 Jeff Perry ....Tennis Player<br />
	　　　　　　Rick Snyder ....Tennis Player<br />
	　　　　　　Danny Stone ....Tennis Player<br />
	　　　　　　Vito DeFilippo ....Mark Silk<br />
	　　　　　　Robert Higden ....Jeff Silk<br />
	　　　　　　Vlasta Vrana ....Solly Tabak<br />
	　　　　　　Richard Mawe ....Doc Chizner<br />
	　　　　　　Tom Rack ....Bobcat<br />
	　　　　　　Bill Rowat ....Swift<br />
	　　　　　　理查德&middot;拉索 Richard Russo ....Faculty Committee Member<br />
	　　　　　　Andrew Forge ....Faculty Committee Member<br />
	　　　　　　Stella Arroyave ....Faculty Committee Member<br />
	　　　　　　Jude Beny ....Sally<br />
	　　　　　　Peter Cunningham ....Boxer</p>
<p>
	<br />
	【简　　介】</p>
<p>
	剧情</p>
<p>
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 犹太教授科尔曼因骂学生而被指责是种族主义者，随后他的婚外情也被发现，在一连串打击之后终于发现是好友祖克曼在整他&hellip;&hellip;</p>
<p>
	一句话评论</p>
<p>
	How far would you go to escape the past?</p>
<p>
	幕后制作</p>
<p>
	　　影片以希尔克的朋友内森为叙述人，倒叙的方式展开。根据普利策文学奖获得者菲利普&middot;罗斯2000年出版的畅销小说改编，幕前幕后有着标准的奥斯卡级阵容。编剧尼古拉斯&middot;梅耶代表作是话题性影片《致命的诱惑》和《星际旅行》系列。摄影师让-伊夫&middot;艾索夫曾给《坏血》、《新桥恋人》、《心灵捕手》等片掌机，王家卫正在拍的《2046》也有他的参与。</p>
<p>
	　　导演罗伯特&middot;本顿虽然对大部分人来说还是个陌生的名字，但提起他的作品可都是赫赫有名。这位有个性的电影人尽管没有同时代的科波拉、斯科西斯那般崇高地位，但他在主流电影中所取得的成功并不逊色。本顿原是纽约《绅士》杂志编辑，在那里他遇到了此后合作多年的搭档大卫&middot;纽曼，10年后他们共同编剧《邦妮与克莱德》，这部被20位导演拒绝、直到亚瑟&middot;佩恩才接下导筒的剧本，最终如石破天惊般宣告了新好莱坞电影浪潮的汹涌袭来。那种挑战秩序、自由不羁的精神使之成为一代青年热烈追捧的经典。</p>
<p>
	　　1972年，本顿执导了自己的处女作西部犯罪片《坏伙伴》，反响平平。1979年的《克莱默夫妇》才真正让他作为一位导演声名鹊起，细腻温和的家庭剧开80年代此类保守题材之先河，也为他赢得了奥斯卡最佳导演和最佳改编剧本。80年代后他以创作低成本影片为主，偶尔有受到瞩目的佳片如给萨莉&middot;菲尔德带来影后殊荣的《我心深处》、让保罗&middot;纽曼大显演技的《大智若愚》(Nobody&#39;s Fool)等，产量不高但保持一定水准。</p>
<p>
	　　奥斯卡影帝影后携手无疑是此片最大的看点，尤其是米拉麦克斯公司不断爆出安东尼&middot;霍普金斯与妮可&middot;基德曼在片中将有大量激情戏。以霍普金斯的高龄要做此类表演，实在有些让人怀疑，但他本人倒是很有信心，认为自己的年龄并不是什么问题。而妮可因在其中演出一名邋遢的粗俗女人也被作为一个卖点大肆鼓吹。</p>
<p>
	　　事实上，抛开电影公司这些宣传策略不说，原著是一本相当严肃深刻的小说。菲利普&middot;罗斯一直致力于反思美国公众生活与私人生活之间的关系，而这本小说依旧围绕这一主题，对90年代的道德与政治环境进行了考察。整个故事的背景就是克林顿的性丑闻与被弹劾案，无论是克林顿事件亦或男主角的遭遇皆是从不同层面反映了美国90年代社会表面的虚伪自由与开放，实际上一种紧张的道德关系始终存在。罗斯通过缜密的结构布局以最后揭开的秘密令这个故事产生了巨大的反讽意味，对美国社会的弱点作出了有力的抨击，完全超越了个人悲剧的层次。究竟&ldquo;人性的污点&rdquo;是什么？显然并非简单的种族主义所能完全概括的。要改编后的电影达到同样的深度，似乎是过高要求了。</p>

<p>
	<img alt="" height="337" src="http://img170.poco.cn/mypoco/myphoto/20120319/12/63310092012031912020705.jpg" style="cursor: pointer" width="600" /></p>
<p>
	<img alt="" height="337" src="http://img170.poco.cn/mypoco/myphoto/20120319/12/633100920120319120136046.jpg" style="cursor: pointer" width="600" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;<img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" /></p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3079/飘花电影piaohua.com人性污点BD中英双字1280高清.rmvb">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</a><a href="ftp://dy44:piaohua@dy44.piaohua.com:3079/飘花电影piaohua.com人性污点BD中英双字1280高清.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3079/飘花电影piaohua.com人性污点BD中英双字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15SO10-525R.jpg{/dede:field}
