<?php
$z[0]=Array("field","生活大爆炸,第五季更新24集[中英",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","生活大爆炸 第五季更新24集[中英双字]2011主打美剧迅雷下载、免费下载，生活大爆炸 第五季更新24集[中英双字]2011主打美剧Gvod高清在线播放，剧情介绍等。",73,261);
$z[1][4]['name']="description";
$z[2]=Array("field","生活大爆炸 第五季更新24集[中英双字]2011主打美剧",263,348);
$z[2][4]['name']="title";
$z[3]=Array("field","",350,389);
$z[3][4]['name']="writer";
$z[4]=Array("field","",391,430);
$z[4][4]['name']="source";
$z[5]=Array("field","2012-05-14",432,482);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",484,521);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://dy44:piaohua@dy44.piaohua.com:2926/飘花电影piaohua.com生活大爆炸第五季01.rmvb",523,645);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MP922950-23Z7.jpg",647,730);
$z[8][4]['name']="litpic";

?>