{dede:field name='keywords'}狂犬病DVD中英双字欧美恐怖惊悚{/dede:field}
{dede:field name='description'}狂犬病DVD中英双字欧美恐怖惊悚迅雷下载、免费下载，狂犬病DVD中英双字欧美恐怖惊悚Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}狂犬病DVD中英双字欧美恐怖惊悚{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-04-09{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120324/08/56209934201203240826111879872955455_000.jpg" style="width: 600px; height: 852px" /></p>
<p>
	◎中 文 名：狂犬病<br />
	◎外 文 名：Rabies、Kalevet<br />
	◎年&nbsp;&nbsp;&nbsp; 份：2010年12月12日<br />
	◎国&nbsp;&nbsp;&nbsp; 家：以色列<br />
	◎IMDB评分：6.0/10 from 453 users&nbsp;&nbsp;<br />
	◎文件格式：RMVB + MKV<br />
	◎视频尺寸：640X352/480p<br />
	◎语&nbsp;&nbsp;&nbsp; 言：希伯来语<br />
	◎字&nbsp;&nbsp;&nbsp; 幕：中文字幕<br />
	◎类&nbsp;&nbsp;&nbsp; 型：惊悚/恐怖<br />
	◎片&nbsp;&nbsp;&nbsp; 长：90 min<br />
	◎导&nbsp;&nbsp;&nbsp; 演：亚伦&middot;凯莎莱斯 Aharon Keshales<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 纳沃特&middot;帕普莎多 Navot Papushado<br />
	◎编&nbsp;&nbsp;&nbsp; 剧：亚伦&middot;凯莎莱斯 Aharon Keshales&nbsp; ....writer<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 纳沃特&middot;帕普莎多 Navot Papushado&nbsp; ....writer<br />
	◎演&nbsp;&nbsp;&nbsp; 员：利奥&middot;阿什肯纳兹 Lior Ashkenazi&nbsp; ....Danny<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 丹尼&middot;吉瓦 Danny Geva&nbsp; ....Yuval<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 阿妮亚&middot;布克斯坦 Ania Bukstein&nbsp; ....Adi<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 梅纳什&middot;诺伊 Menashe Noy&nbsp; ....Menashe<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 阮&middot;丹克 Ran Danker&nbsp; ....Mikey<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Henry David&nbsp; ....Ofer<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Ofer Shechter&nbsp; ....Pini<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Liat Harlev&nbsp; ....Tali<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Yael Grobglas&nbsp; ....Shir<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Efrat Boimold&nbsp; ....Rona</p>
<p>
	<br />
	◎简&nbsp;&nbsp;&nbsp; 介：<br />
	　&nbsp;&nbsp; 这是以色列电影史上的破天荒的第一部恐怖片，给人留下了深刻的印象。影片讲述一群前往网球比赛网的年轻人被困在了狂暴的森林中。<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 一对离家出走的兄妹在一个荒芜的自然保护区寻找避难所。当妹妹掉进了一个心理变态杀手所设的陷阱之后，哥哥为了寻求帮助而争分夺秒。命运开始扭转，不知不觉间，营救妹妹的行动与一群年轻的网球运动员的生命交织在了一起，同时被牵涉进来的还有森林管理员与他的狗，以及一队警察......<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 影片故事中充满了转折并且要到结尾之后才能将其脉络梳理清楚，在加上适度的血腥而不过度，这当让两位两位新人导演的掌控力可见一斑。此外养眼的女主角也显然给影片加分不少。&nbsp;</p>

<p>
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120324/08/56209934201203240832272215879552176_003.jpg" /></p>
<p>
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120324/08/56209934201203240832272215879552176_004.jpg" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.net" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3176/飘花电影piaohua.com狂犬病DVD中英双字.mkv">ftp://dy44:piaohua@dy44.piaohua.com:3176/飘花电影piaohua.com狂犬病DVD中英双字.mkv</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3182/飘花电影piaohua.com狂犬病DVD中英双字.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3182/飘花电影piaohua.com狂犬病DVD中英双字.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O16293a0-1D57.jpg{/dede:field}
