{dede:field name='keywords'}初到东京高清1024/1280版HD中英{/dede:field}
{dede:field name='description'}初到东京高清1024/1280版HD中英双字2012最新上映中日合拍爱情大迅雷下载、免费下载，初到东京高清1024/1280版HD中英双字2012最新上映中日合拍爱情大Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}初到东京高清1024/1280版HD中英双字2012最新上映中日合拍爱情大{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-03-26{/dede:field}
{dede:field name='body'}<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120323/23/56643687201203232311541280209374327_005.jpg" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120323/23/56643687201203232311541280209374327_006.jpg" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120323/23/56643687201203232311541280209374327_008.jpg" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120323/23/56643687201203232311541280209374327_007.jpg" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120323/23/56643687201203232311541280209374327_004.jpg" /></p>
<p>
	中文名： 初到东京<br />
	外文名： Tokyo Newcomer<br />
	其它译名： 东京に来たばかり<br />
	出品时间： 2012年<br />
	类型： 爱情，励志<br />
	主演： 秦昊，倍赏千惠子，中泉英雄，张钧甯，田原<br />
	上映时间： 2012年3月23日(中国大陆)<br />
	制片国家/地区： 中国大陆 / 日本<br />
	对白语言： 中文，日语<br />
	片长： 100分钟<br />
	IMDb链接： tt1909830</p>
<p>
	<br />
	剧情简介</p>
<p>
	　　围棋手吉流（秦昊 饰）初到东京留学，陷入生活迷茫困境，在去千叶的列车上，他与背着蔬菜进京的五十岚婆（倍赏千惠子 饰）有了一次奇特的偶遇，从此他的生活进入了一个奇异的圈子，他与五十岚婆的孙子翔一（中泉英雄 饰），与翔一的女友奈菜子（张钧甯 饰），与旅店的服务员内藤加美（田原 饰）， 开始有了剪不断理还乱的关系。躁动的青春，异国的少女，不移的围棋梦想，在苦闷激情的年华里冰火交融。</p>

<p>
	<br />
	◎影片截图</p>

<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120323/23/56643687201203232311541280209374327_003.jpg" style="width: 600px; height: 338px" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120323/23/56643687201203232311541280209374327_002.jpg" style="width: 600px; height: 338px" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120323/23/56643687201203232311541280209374327_001.jpg" style="width: 600px; height: 338px" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120323/23/56643687201203232311541280209374327_000.jpg" style="width: 600px; height: 338px" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120325/20/56643687201203252010155156527175080_003.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 351px; border-top: 0px solid; border-right: 0px solid" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120325/20/56643687201203252010155156527175080_001.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 351px; border-top: 0px solid; border-right: 0px solid" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120325/20/56643687201203252010155156527175080_000.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 351px; border-top: 0px solid; border-right: 0px solid" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120325/20/56643687201203252010155156527175080_002.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 351px; border-top: 0px solid; border-right: 0px solid" /></p>

<p>
	[下载地址]： &nbsp;<img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" /></p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3062/飘花电影piaohua.com初到东京高清1024版HD中英双字.rmvb ">ftp://dy44:piaohua@dy44.piaohua.com:3062/飘花电影piaohua.com初到东京高清1024版HD中英双字.rmvb </a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3074/飘花电影piaohua.com初到东京高清1280版HD中英双字.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3074/飘花电影piaohua.com初到东京高清1280版HD中英双字.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15S5X0-26047.jpg{/dede:field}
