{dede:field name='keywords'}穿越美国/窈窕老爸BD1280高清中{/dede:field}
{dede:field name='description'}穿越美国/窈窕老爸BD1280高清中字迅雷下载、免费下载，穿越美国/窈窕老爸BD1280高清中字Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}穿越美国/窈窕老爸BD1280高清中字{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-23{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://brain.pan.e-merchant.com/6/2/11940026/l_11940026.jpg" style="width: 600px; height: 532px" /></p>
<p>
	◎译　　名　穿越美国/窈窕老爸<br />
	◎片　　名　Transamerica<br />
	◎年　　代　2005<br />
	◎国　　家　美国<br />
	◎类　　别　冒险/喜剧/剧情<br />
	◎语　　言　英语/西班牙语<br />
	◎字　　幕　英文<br />
	◎IMDB评分 &nbsp; 7.4/10 (24,678 votes)<br />
	◎IMDB链接 &nbsp; <a href="http://www.imdb.com/title/tt0384929/" target="_blank">http://www.imdb.com/title/tt0384929/</a><br />
	◎文件格式　x264 + AC3<br />
	◎视频尺寸　1280 x 696<br />
	◎文件大小　1 DVD<br />
	◎片　　长　01:43:16<br />
	◎导　　演　邓肯&middot;塔克 Duncan Tucker<br />
	◎主　　演　菲丽西提&middot;霍夫曼 Felicity Huffman ....Bree Osbourne<br />
	　　　　　　菲奥纽拉&middot;弗拉纳根 Fionnula Flanagan ....Elizabeth<br />
	　　　　　　格雷厄姆&middot;格林 Graham Greene ....Calvin<br />
	　　　　　　凯文&middot;席格斯 Kevin Zegers ....Toby<br />
	　　　　　　伊丽莎白&middot;佩纳 Elizabeth Pe?a ....Margaret<br />
	　　　　　　波特&middot;杨 Burt Young ....Murray<br />
	　　　　　　Carrie Preston ....Sydney<br />
	　　　　　　Venida Evans ....Arletty<br />
	　　　　　　Jon Budinoff ....Alex<br />
	　　　　　　Raynor Scheine ....Bobby Jensen<br />
	　　　　　　Grant Monohon ....Hitchhiker<br />
	　　　　　　Bianca Leigh ....Mary Ellen<br />
	　　　　　　Danny Burstein ....Dr. Spikowsky<br />
	　　　　　　Craig Bockhorn ....Police Sergeant<br />
	　　　　　　Cecy ....Nurse<br />
	　　　　　　Andrea James ....Voice Coach<br />
	　　　　　　Maurice Orozco ....Fernando<br />
	　　　　　　Paul Borghese ....NYC Cop<br />
	　　　　　　Kate Bayley ....Tennessee Waitress<br />
	　　　　　　斯黛拉&middot;麦薇 Stella Maeve ....Taylor<br />
	　　　　　　Teala Dunn ....Little Girl<br />
	　　　　　　Jim Frangione ....Taylor&#39;s Father<br />
	　　　　　　Kelly O&#39;Connell ....Kelly<br />
	　　　　　　Calpernia Addams ....Calpernia<br />
	　　　　　　Sandi Alexander ....Sandi<br />
	　　　　　　Melissa Sklarz ....Melissa<br />
	　　　　　　Felicia Kittles ....Felicia<br />
	　　　　　　David Harrison ....David<br />
	　　　　　　Forrie J. Smith ....Sammy (as Forrie Smith)<br />
	　　　　　　Elayne Stein ....Phoenix Lady<br />
	　　　　　　Amy Povich ....Phoenix Cop<br />
	　　　　　　Burton Ellis ....Male Nurse<br />
	　　　　　　Matt Young ....Wayne<br />
	　　　　　　Barbara Barron ....Ms. Swallow (as Barbara Hubbard Barron)<br />
	　　　　　　Wesley Norton ....Trucker<br />
	　　　　　　Richard Poe ....John<br />
	　　　　　　Kelly O&#39;Donnell ....Kelly<br />
	　　　　　　Lynn Laurino ....Lady in Pink<br />
	　　　　　　Steve Hurwitz ....Harvey<br />
	　　　　　　Stephen D. Goodman ....Restaurant Patron (uncredited)<br />
	<br />
	<br />
	◎简　　介<br />
	<br />
	剧情<br />
	<br />
	　　布莉，洛杉矶，变性人，满心期待接受去势手术后，&ldquo;她&rdquo;就能拥有幸福人生，却突然发现自己原来有个儿子被拘留在警局。陶比，纽约，性别界线模糊青年，母亲自杀，继父施暴，他最大梦想是前往西岸成为A片明星并寻找生父。当陶比误以为保释自己的大婶是位虔诚的传教士，在横跨内陆的旅途中频频摆出撩人姿态挑逗，布莉为了逃避过往，只好将错就错，难道父子乱伦戏码真要就此上演？<br />
	<br />
	一句话评论<br />
	<br />
	Life is more than the sum of its parts.<br />
	<br />
	Life is a journey. Bring an open mind.<br />
	<br />
	幕后制作<br />
	<br />
	　　《穿越美国》是一部关于&ldquo;变性&rdquo;题材的喜剧公路片，讲述了一个有变性癖、正在筹钱做变性手术并准备变成女人的&ldquo;男人&rdquo;的故事。本片值得青睐的绝不仅于它略带轻松的氛围，而是在举重若轻的节奏里，对变性这一冲击社会正统伦理观的敏感话题做出了充满尊严而又幽默的诠释，让人在笑声中不由得为之深深感动。本片的亮点集中于扮演变性人的女星菲丽西提&middot;霍夫曼身上。女主角菲丽西提&middot;霍夫曼也是热门剧集《疯狂主妇》的女主演之一。现年43岁的霍夫曼在影视道路上也经历了不少坎坷，《穿越美国》是她第一次在影片中获得的重要主角。从霍夫曼在片中的表演来看，无论体态、表情还是心理，都刻画得入木三分。如果没有她自毁形象，压低嗓音的出色演绎，这部片子很难成功。在不久前落幕的第63届美国电影电视金球奖上，菲丽西提&middot;霍夫曼(Felicity Huffman)凭着她在《穿越美国》(Transamerica)中的精湛演技，一举夺得剧情类电影最佳女主角小金人。<br />
	<br />
	花絮<br />
	<br />
	&middot;影片最初的灵感来自本片编导Duncan Tucker和变性女演员Katherine Connella之间的一次谈话。那时他们在好莱坞合租一间房子，一次在讨论男性与女性意识时，Tucker非常惊异地发现Connella是被当作男孩养大的。<br />
	&middot;Felicity Huffman不得不赶在《绝望主妇》的档期前拍摄完自己的镜头。而《绝望主妇》里也有一位女主角叫Bree。<br />
	&middot;在没有预料到影片将受到如此好评的情况下，影片结束拍摄后，道具服装大部分都给了慈善组织和廉价商店。</p>
<p>
	<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120523/12/17870980201205231203551802384047323_008.jpg" /></p>
<p>
	<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120523/12/17870980201205231203551802384047323_007.jpg" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaobajie.com" target="_blank">http://www.xiaobajie.com</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy241:piaohua@117.41.229.29:2033/飘花电影piaohua.com穿越美国BD1280高清中字.rmvb">ftp://dy241:piaohua@117.41.229.29:2033/飘花电影piaohua.com穿越美国BD1280高清中字.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1601R20-11P6.jpg{/dede:field}
