{dede:field name='keywords'}蝴蝶效应1BD中英双字1024/1280高{/dede:field}
{dede:field name='description'}蝴蝶效应1BD中英双字1024/1280高清迅雷下载、免费下载，蝴蝶效应1BD中英双字1024/1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}蝴蝶效应1BD中英双字1024/1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-12-01{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://e15:e15@xl2.eee4.com:9219/[3E电影站www.eee4.com]蝴蝶效应[DVD中英双字1024x576高清版].rmvb" target="_blank{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MObV40-36309.jpg{/dede:field}
