{dede:field name='keywords'}龙卷风2迅雷下载，免费下载，Gvo{/dede:field}
{dede:field name='description'}龙卷风2迅雷下载、免费下载，龙卷风2Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}龙卷风2{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2007-01-17{/dede:field}
{dede:field name='body'}<p>玛娜尔是个&ldquo;暴风雨追逐者&rdquo;，她在一次飞机事故中失去了丈夫，从此便全身心投入到工作之中，一次他被派到科罗拉多去调查龙卷风的起因，遭遇了联邦紧急救援中心的维力，一天晚上，当他们正在检查暴风雨情况时，一场个球形雷击击中了他的周围树木，维力飞身掩护玛娜尔，他们拥抱在一起并热吻起来&hellip;&hellip;</p>
<p>http://220.165.60.123:6666///Aaa/f/灾难片/龙卷风2/龙卷风2.rm</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O164O120-24931.jpg{/dede:field}
