{dede:field name='keywords'}我为喜剧狂/摇滚30//超级制作人{/dede:field}
{dede:field name='description'}我为喜剧狂/摇滚30//超级制作人第六季22迅雷下载、免费下载，我为喜剧狂/摇滚30//超级制作人第六季22Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}我为喜剧狂/摇滚30//超级制作人第六季22{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-23{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://pic.piaohua.com/0701pic/allimg/120118/1-12011Q42949328.jpg" /></p>
<p>
	<img alt="" src="http://pic.piaohua.com/0701pic/allimg/120118/1-12011Q4295XT.jpg" /></p>
<p>
	导演: Tina Fey<br />
	编剧: 蒂娜&middot;菲 / Jack Burditt / Robert Carlock / John Riggi<br />
	主演: 蒂娜&middot;菲 / 亚历克&middot;鲍德温 / 简&middot;科拉克斯基 / 杰克&middot;麦克布瑞尔<br />
	类型: 喜剧<br />
	官方网站: <a href="http://www.nbc.com/30_Rock/">http://www.nbc.com/30_Rock/</a><br />
	制片国家/地区: 美国<br />
	语言: 英语<br />
	首播日期: 2006-10-11<br />
	集数: 21<br />
	单集片长: 30 分钟<br />
	又名: 摇滚30<br />
	剧情简介 &middot; &middot; &middot; &middot; &middot; &middot;<br />
	　　Liz Lemon, played by Saturday Night Live&#39;s Tina Fey, is the head writer of the fictional TV show, &#39;The Girlie Show.&#39; When her old boss dies and a new boss comes in, Liz must try to run a successful TV show without losing her mind. 30 Rock is produced by NBC Studios in association with Broadway Video and distributed by the NBC Television Network. The series has been given a 13 e...</p>
<p>
	[下载地址]： &nbsp;<img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" /></p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2652/飘花电影piaohua.com超级制作人第六季1.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2652/飘花电影piaohua.com超级制作人第六季1.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2689/飘花电影piaohua.com超级制作人第六季2.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2689/飘花电影piaohua.com超级制作人第六季2.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2820/飘花电影piaohua.com超级制作人第六季3.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2820/飘花电影piaohua.com超级制作人第六季3.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2820/飘花电影piaohua.com超级制作人第六季4.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2820/飘花电影piaohua.com超级制作人第六季4.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2820/飘花电影piaohua.com超级制作人第六季5.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2820/飘花电影piaohua.com超级制作人第六季5.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2820/飘花电影piaohua.com超级制作人第六季6-7.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2820/飘花电影piaohua.com超级制作人第六季6-7.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2859/飘花电影piaohua.com超级制作人第六季8.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2859/飘花电影piaohua.com超级制作人第六季8.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2899/飘花电影piaohua.com超级制作人第六季9.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2899/飘花电影piaohua.com超级制作人第六季9.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2962/飘花电影piaohua.com超级制作人第六季10.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2962/飘花电影piaohua.com超级制作人第六季10.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3004/飘花电影piaohua.com超级制作人第六季11.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3004/飘花电影piaohua.com超级制作人第六季11.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3043/飘花电影piaohua.com超级制作人第六季12.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3043/飘花电影piaohua.com超级制作人第六季12.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3077/飘花电影piaohua.com超级制作人第六季13.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3077/飘花电影piaohua.com超级制作人第六季13.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3080/飘花电影piaohua.com超级制作人第六季14.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3080/飘花电影piaohua.com超级制作人第六季14.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3137/飘花电影piaohua.com超级制作人第六季15.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3137/飘花电影piaohua.com超级制作人第六季15.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3181/飘花电影piaohua.com超级制作人第六季16.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3181/飘花电影piaohua.com超级制作人第六季16.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3233/飘花电影piaohua.com超级制作人第六季17.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3233/飘花电影piaohua.com超级制作人第六季17.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3279/飘花电影piaohua.com超级制作人第六季18.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3279/飘花电影piaohua.com超级制作人第六季18.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3333/飘花电影piaohua.com超级制作人第六季19.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3333/飘花电影piaohua.com超级制作人第六季19.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3372/飘花电影piaohua.com超级制作人第六季20.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3372/飘花电影piaohua.com超级制作人第六季20.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3372/飘花电影piaohua.com超级制作人第六季20.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3372/飘花电影piaohua.com超级制作人第六季20.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3477/飘花电影piaohua.com超级制作人第六季21.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3477/飘花电影piaohua.com超级制作人第六季21.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3477/飘花电影piaohua.com超级制作人第六季22.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3477/飘花电影piaohua.com超级制作人第六季22.rmvb</a></td>
		</tr>
	</tbody>
</table>
<p>
	&nbsp;</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1AMS0-5Z46.jpg{/dede:field}
