<?php
$z[0]=Array("field","别在伤口撒盐,{以后的我是个陌生",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","别在伤口撒盐 {以后的我是个陌生人}迅雷下载、免费下载，别在伤口撒盐 {以后的我是个陌生人}Gvod高清在线播放，剧情介绍等。",73,233);
$z[1][4]['name']="description";
$z[2]=Array("field","别在伤口撒盐 {以后的我是个陌生人}",235,306);
$z[2][4]['name']="title";
$z[3]=Array("field","",308,347);
$z[3][4]['name']="writer";
$z[4]=Array("field","",349,388);
$z[4][4]['name']="source";
$z[5]=Array("field","2006-08-04",390,440);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<P>播放后双击视频“全屏”</P> \n<object classid=\"CLSID:22d6f312-b0f6-11d0-94ab-0080c74c7e95\" class=\"OBJECT\" id=\"MediaPlayer\" width=\"500\" height=\"350\" ><param name=\"ShowStatusBar\" value=\"-1\"><param name=\"Filename\" value=\"http://60.191.249.22:4561/A000053.wmv\"></embed></object><br /> \n<P>下载地址<BR></P> <br>",442,786);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c120524/133N353DD0-2G248.gif",788,871);
$z[7][4]['name']="litpic";

?>