{dede:field name='keywords'}Rain-《Sad_Tango》迅雷下载，免{/dede:field}
{dede:field name='description'}Rain-《Sad_Tango》迅雷下载、免费下载，Rain-《Sad_Tango》Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}Rain-《Sad_Tango》{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2006-08-04{/dede:field}
{dede:field name='body'}<P>播放后双击视频“全屏”</P> 

<object classid="CLSID:22d6f312-b0f6-11d0-94ab-0080c74c7e95" class="OBJECT" id="MediaPlayer" width="500" height="350" ><param name="ShowStatusBar" value="-1"><param name="Filename" value="mms://vod.phoenixtv.com/2006/free/060221music.asf"></embed></object><br/> 

<P>下载地址 <br>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120524/133N353DD0-2G248.gif{/dede:field}
