{dede:field name='keywords'}你和我/追寻塔图女孩DVD中英双字{/dede:field}
{dede:field name='description'}你和我/追寻塔图女孩DVD中英双字2011最新剧情迅雷下载、免费下载，你和我/追寻塔图女孩DVD中英双字2011最新剧情Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}你和我/追寻塔图女孩DVD中英双字2011最新剧情{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-04-07{/dede:field}
{dede:field name='body'}<p>
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120407/00/56643687201204070026573082341122412_006.jpg" /></p>
<p>
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120407/00/56643687201204070026573082341122412_004.jpg" /></p>
<p>
	<img alt="" src="http://st.kinopoisk.ru/im/poster/1/4/2/kinopoisk.ru-You-and-I-1426346.jpg" style="width: 600px; height: 848px" /></p>

<p>
	◎译　　名　你和我/寻找t.A.T.u./发现t.A.T.u/追寻塔图女孩<br />
	◎片　　名　You And I<br />
	◎年　　代　2011<br />
	◎国　　家　美国/俄罗斯<br />
	◎类　　别　惊悚<br />
	◎语　　言　英语<br />
	◎字　　幕　中英双字<br />
	◎IMDB评分 5.5/10 from 803 users<br />
	◎文件格式　XviD + MP3<br />
	◎视频尺寸　640 x 360<br />
	◎文件大小　1CD<br />
	◎片　　长　101 Mins<br />
	◎导　　演　罗兰&middot;约菲 Roland Joff&eacute;<br />
	◎主　　演　米莎&middot;巴顿 Mischa Barton ....Lana Starkova<br />
	　　　　　　安东&middot;尤金 Anton Yelchin ....Edvard Nikitin<br />
	　　　　　　珊特尔&middot;范圣滕 Shantel VanSanten ....Janie Sawyer<br />
	　　　　　　阿莱克斯&middot;卡鲁兹斯凯 Alex Kaluzhsky ....Dima<br />
	　　　　　　Charlie Creed-Miles ....Ian<br />
	　　　　　　Igor Desyatnikov ....Ivan<br />
	　　　　　　Aleksandr Byelonogov ....Max, t.A.T.u. producer<br />
	　　　　　　Lena Katina ....Herself<br />
	　　　　　　Julia Volkova ....Herself<br />
	　　　　　　Dominika Wolski ....Russian supermodel (as Dominika Wolski)<br />
	　　　　　　Evgeny Koryakovsky ....Aleksei<br />
	　　　　　　Grigory Levakov ....Face Control (as Grigory Levakov)<br />
	　　　　　　Troy MacCubbin ....Himself - Guitarist, t.A.T.u band<br />
	　　　　　　Yekaterina Malikova ....Marina<br />
	　　　　　　Sven Martin ....Himself - Keyboardist, t.A.T.u band<br />
	　　　　　　海伦娜&middot;马特森 Helena Mattsson ....Kira<br />
	　　　　　　Seth William Meier ....Seth<br />
	　　　　　　Aleksei Mitrofanov ....Himself<br />
	　　　　　　布朗森&middot;平丘 Bronson Pinchot ....Tarrino<br />
	　　　　　　Aleksander Semchev ....Leonid (as Alexander Semchev)<br />
	　　　　　　Alika Smekhova ....Lana&#39;s mother<br />
	　　　　　　Olesya Sudzilovskaya ....Janie&#39;s mother</p>
<p>
	◎简　　介　</p>
<p>
	　　90年代末千禧年之初，俄罗斯出现了一股流行新势力，俩个teenager女孩，天秤座的Lana和水瓶座的Janie，她们都号称有着魔鬼的身材和天使的面庞，她们高呼着禁忌女同旗号从掀起俄罗斯旋风迅速席卷全球流行歌坛，还曾经远赴英国剑桥演讲，该片由Roland Joff&eacute;指导改编自关于她们组合t.A.T.u.的传记小说，追寻两个少女偶像的真实生活。</p>


<p>
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120407/00/56643687201204070026573082341122412_002.jpg" /></p>
<p>
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120407/00/56643687201204070026573082341122412_000.jpg" /></p>
<p>
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120407/00/56643687201204070026573082341122412_001.jpg" /></p>
<p>
	<img alt="" src="http://img011.photo.21cn.com/photos/mark/20120406/o/3E10EAE76A5B5E425BC8B6D2BDBFA64C.jpg" /></p>
<p>
	<img alt="" src="http://img011.photo.21cn.com/photos/mark/20120406/o/2472B8CD7A9E5B3E78F7E16E6372D171.jpg" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.net" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3159/飘花电影piaohua.com追寻塔图女孩DVD中英双字.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3159/飘花电影piaohua.com追寻塔图女孩DVD中英双字.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O162Z430-39556.jpg{/dede:field}
