<?php
$z[0]=Array("field","小姐弟荒原历险/澳洲奇谈/流浪生",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","小姐弟荒原历险/澳洲奇谈/流浪生活[BD中英双字1280x720高清版]迅雷下载、免费下载，小姐弟荒原历险/澳洲奇谈/流浪生活[BD中英双字1280x720高清版]Gvod高清在线播放，剧情介绍等。",73,283);
$z[1][4]['name']="description";
$z[2]=Array("field","小姐弟荒原历险/澳洲奇谈/流浪生活[BD中英双字1280x720高清版]",285,381);
$z[2][4]['name']="title";
$z[3]=Array("field","",383,422);
$z[3][4]['name']="writer";
$z[4]=Array("field","",424,463);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-07-12",465,515);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",517,554);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://3e:3e@d8.3edyy.com:170/【3E电影院www.eee4.cc】小姐弟荒原历险BD中英双字1280x720高清版.rmvb\" target=\"_blank",556,706);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MQ35DZ-13047.jpg",708,790);
$z[8][4]['name']="litpic";

?>