{dede:field name='keywords'}爱情啊,爱情啊第12集韩剧迅雷下{/dede:field}
{dede:field name='description'}爱情啊 爱情啊第12集韩剧迅雷下载、免费下载，爱情啊 爱情啊第12集韩剧Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}爱情啊 爱情啊第12集韩剧{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-25{/dede:field}
{dede:field name='body'}<p>
	&nbsp;<img alt="" height="367" src="http://img.album.pchome.net/02/25/03/37/16fcce8221274135af330f716aa60dc0.jpg" width="600" /></p>
<p>
	[中文剧名]：爱情啊 爱情啊<br />
	[韩文剧名]：&#49324;&#46993;&#50500; &#49324;&#46993;&#50500;<br />
	[导&nbsp;&nbsp;&nbsp; 演]：李德健<br />
	[编&nbsp;&nbsp;&nbsp; 剧]：郑延敏<br />
	[主&nbsp;&nbsp;&nbsp; 演]：黄善熙 宋旻晶 吴彰锡 金山镐 金英玉<br />
	[放送机构]：韩国KBS<br />
	[类&nbsp;&nbsp;&nbsp; 型]：KBS2晨间日播剧<br />
	[播出时间]：2012年5月7日起每周一至周五早8点（北京时间7点）播出<br />
	[集&nbsp;&nbsp;&nbsp; 数]：预计120集<br />
	[官方网站]：<a href="http://www.bluemv.com" title="电影下载">http://www.bluemv.com</a><br />
	[接档剧集]：福熙姐姐<br />
	郑仁河（张东健饰）是一个刚从瑞士回来的导游，刚回国的仁河在学长金俊哲（李英霞饰）家中盥洗时刚好碰到学长的女友韩莹智（金美淑饰），莹智误认仁河是闯入家中的坏人，恰巧俊哲打电话回来..&nbsp;&nbsp;</p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.netftp//dy44:piaohua@dy44.piaohua.com:3142/" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3387/飘花电影piaohua.com爱情啊 爱情啊EP01.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3387/飘花电影piaohua.com爱情啊 爱情啊EP01.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3387/飘花电影piaohua.com爱情啊 爱情啊EP02.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3387/飘花电影piaohua.com爱情啊 爱情啊EP02.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3399/飘花电影piaohua.com爱情啊 爱情啊EP03.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3399/飘花电影piaohua.com爱情啊 爱情啊EP03.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3407/飘花电影piaohua.com爱情啊 爱情啊EP04.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3407/飘花电影piaohua.com爱情啊 爱情啊EP04.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3410/飘花电影piaohua.com爱情啊 爱情啊EP05.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3410/飘花电影piaohua.com爱情啊 爱情啊EP05.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3435/飘花电影piaohua.com爱情啊 爱情啊EP06.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3435/飘花电影piaohua.com爱情啊 爱情啊EP06.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3438/飘花电影piaohua.com爱情啊 爱情啊EP07.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3438/飘花电影piaohua.com爱情啊 爱情啊EP07.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3454/飘花电影piaohua.com爱情啊 爱情啊EP08.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3454/飘花电影piaohua.com爱情啊 爱情啊EP08.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3460/飘花电影piaohua.com爱情啊 爱情啊EP09.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3460/飘花电影piaohua.com爱情啊 爱情啊EP09.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3463/飘花电影piaohua.com爱情啊 爱情啊EP10.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3463/飘花电影piaohua.com爱情啊 爱情啊EP10.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3483/飘花电影piaohua.com爱情啊 爱情啊EP11.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3483/飘花电影piaohua.com爱情啊 爱情啊EP11.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3490/飘花电影piaohua.com爱情啊 爱情啊EP12.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3490/飘花电影piaohua.com爱情啊 爱情啊EP12.rmvb</a></td>
		</tr>
	</tbody>
</table>
<p>
	&nbsp;</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1AY360-56030.jpg{/dede:field}
