{dede:field name='keywords'}孤男寡女BD国粤双语中字1024/128{/dede:field}
{dede:field name='description'}孤男寡女BD国粤双语中字1024/1280高清迅雷下载、免费下载，孤男寡女BD国粤双语中字1024/1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}孤男寡女BD国粤双语中字1024/1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-12-21{/dede:field}
{dede:field name='body'}<p>
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('/uploads/allimg/c120525/133O10053330-139A6.jpg');" src="/uploads/allimg/c120525/133O10053330-139A6.jpg" /><br />
	<br />
	◎译　　名　孤男寡女<br />
	◎片　　名　Needing You<br />
	◎年　　代　2000<br />
	◎地　　区　中国香港<br />
	◎类　　别　爱情/喜剧<br />
	◎语　　言　普通话/粤语<br />
	◎字　　幕　中文<br />
	◎IMDB评分&nbsp; 7.1/10 (351 votes)<br />
	◎文件格式　x264 + AAC<br />
	◎视频尺寸　1024 x 576<br />
	◎文件大小　1CD<br />
	◎片　　长　01h:44m:12s<br />
	◎导　　演　杜琪峰 Johnny To<br />
	　　　　　　韦家辉 Ka-Fai Wai<br />
	◎主　　演　郑秀文 Sammi Cheng .....Kinki Kwok<br />
	　　　　　　刘德华 Andy Lau .....Andy Cheung<br />
	　　　　　　林雪 Suet Lam .....Martin<br />
	　　　　　　许绍雄 Shiu Hung Hui .....Ronald<br />
	　　　　　　黄浩然 Ho-Yin Wong .....Roger Young (as Raymond Wong)<br />
	　　　　　　黄卓菱 Ruby Wong<br />
	　　　　　　郭少芸 Florence Kwok .....Kitty<br />
	　　　　　　海俊杰 Gabriel Harrison .....(as Chun-kit Hoi)<br />
	　　　　　　黎森森 Sylvia Lai .....Roger&#39;s mum<br />
	　　　　　　梁艺龄 Fiona Leung .....Fiona<br />
	　　　　　　于洋 Henry Yue .....Roger&#39;s dad<br />
	<br />
	◎简　　介　<br />
	<br />
	　　 张华绍（刘德华饰）是一家电脑公司的经理，他英俊潇洒、事业有成，是许多年轻女孩子心中的白马王子，自己也总是恋爱不断，女友频繁。Kinki（郑秀文饰）与张华绍同一家公司，为人尽忠职守，最终理想就是找个好归宿，却在感情路上坎坷不断。kinki被调做华绍的助理，开始时与他相处并不融洽，而且总是有些神经质，她好心替同事帮忙，却因工作上的差错而惹上麻烦；她只身赴深圳为公司挽回损失，却又被出租车司机骗了&hellip;&hellip;华绍作为她的上司，给予了kinki同情和帮助，两人在逐渐交往的过程红产生了微妙的感情。但kinki的前男友突然又来找她，而华绍的旧女友也试图与其重归如好，当她发现kinki的存在后还特意为其介绍了另一个帅气潇洒的美国巨富roger，roger 也对kinki一见倾心。但这二人的交往，却深深地刺激了华绍，他不得不承认自己已经不知不觉地爱上了天真烂漫的kinki！但kinki与roger就要在开往美国阿密迈州的豪华邮轮上结婚了，于是华绍闻风而至，却只能远远的电影网看着游轮离港，不过爱情永远还是爱情，当华绍失去了所有的时候，kinki最后终究还是回来了。<br />
	<br />
	◎幕后制作<br />
	<br />
	　　1999年的《枪火》使杜琪峰获得了2000年的香港电影金像奖，而其后推出的这部作品与他以前导演的电影作品在风格上的确是有点大相径庭。回顾这几年他导演或监制的作品如《个字头的诞生》、《暗花》、《暗战》、《枪火》等每一部都充满了阳刚之气，爱情和女性因素基本是点缀的身份。而这部突然出现的爱情片必然会使观众产生出许多饶有兴趣的猜想。整部电影沿袭了香港&ldquo;写字楼爱情&rdquo;的传统；刘德华与郑秀文也是第一次合作，很有新鲜感，此后刘德华于他的日记中提到很喜欢这部电影，不过凭借杜琪峰和刘德华第五次合作的默契，这部电影应当说绝对不仅仅是&ldquo;爆米花&rdquo;电影，还是很有看头的。</p>
<p>
	【电影截图】：<br />
	<br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('/uploads/allimg/c120525/133O1005440-1492U.jpg');" src="/uploads/allimg/c120525/133O1005440-1492U.jpg" />&nbsp;<br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('/uploads/allimg/c120525/133O1005520-15X44.jpg');" src="/uploads/allimg/c120525/133O1005520-15X44.jpg" /><br />
	<br />
	<br />
	&nbsp;</p>
<br />
<p>
	[下载地址]：<img border="0" src="/uploads/allimg/c120525/133O0T31310-42214.jpg" /></p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				ftp://3e:3e@d3.3edyy.com:121/【3E电影院www.eee4.org】孤男寡女.1024x576.国粤双语.中文字幕.mkv</td>
		</tr>
	</tbody>
</table>
<p>
	[下载地址]：<img border="0" src="/uploads/allimg/c120525/133O0T31310-42214.jpg" /></p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				ftp://dy44:piaohua@dy44.piaohua.com:2401/飘花电影piaohua.com孤男寡女BD国语1280高清中字.rmvb&nbsp;</td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				ftp://dy44:piaohua@dy44.piaohua.com:2401/飘花电影piaohua.com孤男寡女BD粤语1280高清中字.rmvb&nbsp;</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O10055940-163F1.jpg{/dede:field}
