{dede:field name='keywords'}爱在那一天DVD高清中英双字2012{/dede:field}
{dede:field name='description'}爱在那一天DVD高清中英双字2012中国爱情迅雷下载、免费下载，爱在那一天DVD高清中英双字2012中国爱情Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}爱在那一天DVD高清中英双字2012中国爱情{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-04-17{/dede:field}
{dede:field name='body'}<p>
	&nbsp;<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120416/23/56643687201204162304152270681529282_009.jpg" /></p>

<p>
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120416/23/56643687201204162304152270681529282_007.jpg" /></p>
<p>
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120416/23/56643687201204162304152270681529282_008.jpg" /></p>
<p>
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120416/23/56643687201204162304152270681529282_005.jpg" /></p>
<p>
	&nbsp;<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120416/23/56643687201204162304152270681529282_004.jpg" /></p>
<p>
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120416/23/56643687201204162304152270681529282_006.jpg" /></p>
<p>
	中文名: 爱在那一天<br />
	导演: 朱少宇<br />
	主演: 马里奥&middot;毛瑞尔 / 武艺 / 叶青 / 阚清子<br />
	类型: 剧情 / 爱情<br />
	制片国家/地区: 中国大陆<br />
	语言: 汉语普通话<br />
	上映日期: 2012-04-13(中国大陆)<br />
	片长: 95分钟<br />
	又名: Love on that Day</p>
<p>
	<br />
	剧情简介</p>
<p>
	　　在海港城有一家 &ldquo;心时光客栈&rdquo; ，这个小客栈有一个小小的营销方式，只要是情侣在这里住店，共同写一封信给对方，在两年后凭卡可以取出对方写给自己的信，还可获赠免费客房，小雅（叶青 饰）、安姨、阿福叔就是这家客栈的主人，小雅在海港还有两个好朋友，电台的音乐DJ阿伦（武艺 饰）和 酸奶屋的小美女唐果（阚清子 饰）。<br />
	　　一天 ，客栈住进来了一个神秘客人&mdash;&mdash;马丁（马里奥&middot;毛瑞尔 饰），这个帅气阳光的大男孩，有着迷人的眼神，还有和他的外形不协调的大胃和超强大的力气。<br />
	　　小雅、唐果、阿伦和住在客栈的马丁成了好朋友，知道了马丁来客栈的目的，原来马丁带着母亲二十年前留下的 &ldquo;时光卡&rdquo; 想到客栈取当年父母的信，知道自己的父亲是谁，可这封二十年前的信早就不在了。<br />
	　　小雅喜欢上了这个随时都可能离开的马丁，为了帮马丁找出父母的真相，小雅和唐果展开了行动。<br />
	　　意想不到的结果出现在大家的面前，阿福叔和马丁是什么关系？<br />
	　　马丁和小雅相爱却又觉得对方不适合自己，最后他们能在一起吗？　</p>

<p>
	<br />
	◎影片截图</p>
<p>
	&nbsp;&nbsp;<img src="http://img170.poco.cn/mypoco/myphoto/20120416/23/56643687201204162304152270681529282_000.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 338px; border-top: 0px solid; border-right: 0px solid" /></p>
<p>
	&nbsp;<img src="http://img170.poco.cn/mypoco/myphoto/20120416/23/56643687201204162304152270681529282_001.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 338px; border-top: 0px solid; border-right: 0px solid" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120416/23/56643687201204162304152270681529282_002.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 338px; border-top: 0px solid; border-right: 0px solid" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120416/23/56643687201204162304152270681529282_003.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 338px; border-top: 0px solid; border-right: 0px solid" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.net/aiqingpian/18249/">http://www.xiaozhizhu.net/aiqingpian/18249/</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3237/飘花电影piaohua.com爱在那一天DVD高清BD中英双字.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3237/飘花电影piaohua.com爱在那一天DVD高清BD中英双字.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1500KF-363H.jpg{/dede:field}
