{dede:field name='keywords'}失落的战场BD高清迅雷下载，免费{/dede:field}
{dede:field name='description'}失落的战场BD高清迅雷下载、免费下载，失落的战场BD高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}失落的战场BD高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-12-15{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img165.poco.cn/mypoco/myphoto/20111213/00/62564813201112130023544149588447390_000.jpg" style="width: 700px; height: 883px" /></p>
<p>
	◎译　　名　失落的战场<br />
	◎片　　名　The Lost Battalion<br />
	◎年　　代　2001<br />
	◎国　　家　美国/卢森堡<br />
	◎类　　别　动作/剧情/战争<br />
	◎语　　言　英语/德语<br />
	◎字　　幕　N/A<br />
	◎IMDB评分&nbsp; 7.0/10 (2,992 votes)<br />
	◎IMDB链接&nbsp; <a href="http://www.imdb.com/title/tt0287535/">http://www.imdb.com/title/tt0287535/</a><br />
	◎片　　长　92 Mins<br />
	◎导　　演　拉塞尔&middot;穆卡希 Russell Mulcahy<br />
	◎主　　演　瑞克&middot;斯克路德 Rick Schroder ....Maj. Charles White Whittlesey<br />
	　　　　　　Phil McKee ....Capt. George McMurtry<br />
	　　　　　　Jamie Harris ....Sgt. Gaedeke<br />
	　　　　　　Jay Rodan ....Lt. Leak<br />
	　　　　　　Adam James ....Capt. Nelson Holderman, Co. K 307 th<br />
	　　　　　　Daniel Caltagirone ....Pvt. Phillip Cepeglia<br />
	　　　　　　Michael Goldstrom ....Pvt. Jacob Rosen<br />
	　　　　　　Andr&eacute; Vippolis ....Pvt. Lipasti<br />
	　　　　　　Rhys Miles Thomas ....Pvt. Bob Yoder (sharpshooter)<br />
	　　　　　　Arthur Kremer ....Pvt. Abraham Krotoshinsky (runner)<br />
	　　　　　　Adam Kotz ....Col. Johnson<br />
	　　　　　　Justin Scot ....Pvt. Omer Richards (carrier pigeons)<br />
	　　　　　　Anthony Azizi ....Pvt. Nat Henchman<br />
	　　　　　　George Calil ....Pvt. Lowell R. Hollingshead<br />
	　　　　　　Wolf Kahler ....Gen. von Sybel<br />
	　　　　　　Joachim Paul Assb?ck ....Maj. Henrich Prinz<br />
	　　　　　　Michael Brandon ....Gen. Robert Alexander<br />
	　　　　　　Paul Courtenay Hyu ....Pvt. Stanley Chinn<br />
	　　　　　　乔什&middot;科恩 Josh Cohen ....Pvt. Isidore Swerskу<br />
	　　　　　　蒂姆&middot;马修斯 Tim Matthews ....Lt. Schenck<br />
	　　　　　　Finbar Lynch ....Pvt. Ferguson<br />
	　　　　　　休&middot;弗拉瑟 Hugh Fraser ....Gen. DeCoppet<br />
	　　　　　　Ben Andrews ....Lt. Harold Goettler<br />
	　　　　　　Derek Kueter ....Maj. Wanvig<br />
	　　　　　　Nicolas de Pruyssenaere ....Blind Man (uncredited)<br />
	　　　　　　Jamie Treacher ....The Unknown Soldier (uncredited)</p>
<p>
	◎简　　介</p>
<p>
	&nbsp;&nbsp; 1918年第一次世界大战末期，美国军队进入被德国占领的法国。在法国和英国盟军的打击下，德军一些残余部队隐藏在法国阿尔贡森林中。美国第77师一营800名士兵被命令不惜一切代价，在阿尔</p>
<p>
	贡森林，将德军全部歼灭，这将是非常艰苦的战斗......这是一个真实的一次大战故事。这是一场大规模自杀性攻击。 在没有支援，通讯，侧翼退路，食物，水，枪弹，医药，以及在被德军包围的情</p>
<p>
	况下，经过5天的顽固坚守，只有200人活了下来。</p>
<p>
	此片获得包括艾米奖的多个奖项。&nbsp;</p>
<p>
	<img alt="" src="http://img165.poco.cn/mypoco/myphoto/20111215/08/62564813201112150850134167386895577_002.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img165.poco.cn/mypoco/myphoto/20111215/08/62564813201112150850134167386895577_001.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img165.poco.cn/mypoco/myphoto/20111215/08/62564813201112150850134167386895577_000.jpg" style="width: 720px; height: 405px" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="&#13;&#10;ftp://dy125:piaohua@dy125.piaohua.com:7301/飘花电影piaohua.com失落的战场BD中字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:7301/飘花电影piaohua.com失落的战场BD中字1280高清.rmvb </a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O16262A0-45339.jpg{/dede:field}
