{dede:field name='keywords'}漫长的丝绸之路铁道:横跨中国260{/dede:field}
{dede:field name='description'}漫长的丝绸之路铁道:横跨中国2600公里之旅高清中字1280迅雷下载、免费下载，漫长的丝绸之路铁道:横跨中国2600公里之旅高清中字1280Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}漫长的丝绸之路铁道:横跨中国2600公里之旅高清中字1280{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-02-19{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="/uploads/allimg/c120524/133N4W00V0-O631.jpg" /></p>
<p>
	【中文剧名】：漫长的丝绸之路铁道～横跨中国2600公里之旅～<br />
	【日文剧名】：はるかなるシルクロード鉄道～中国横断2600キロの旅～<br />
	【电视台】：bs-asahi<br />
	【首　播】：2012-02-12<br />
	【回　数】：全一回<br />
	【演　员】：速水重道<br />
	【旁 白】：斋藤茂一<br />
	【格　式】：mkv<br />
	【语　言】：日语<br />
	【字　幕】：中文字幕<br />
	【剧情简介】：</p>
<p>
	为了纪念中日邦交40周年，BS朝日电视台特别推出了这档节目，由速水重道带领大家横跨中国西部地区，途径西安，兰州，嘉峪关，敦煌，吐鲁番，乌鲁木齐，感受其文化和人文风情。&nbsp;。。。。。。。，，，，，，</p>
<p>
	<img alt="" src="/uploads/allimg/c120524/133N4W05H0-WY6.jpg" style="width: 640px; height: 360px" /><img alt="" src="/uploads/allimg/c120524/133N4W06410-920W.jpg" style="width: 640px; height: 360px" /><img alt="" src="/uploads/allimg/c120524/133N4W0G20-105041.jpg" style="width: 640px; height: 360px" /></p>

<p>
	[下载地址]：<img border="0" src="/uploads/allimg/c120524/133N2Z4FF-102231.jpg" /></p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				ftp://dy241:xiaobajie@222.187.221.241:2030/小八戒电影xiaobajie.com漫长的丝绸之路铁道高清中字1280.mkv</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120524/133N4W0M30-1161O.jpg{/dede:field}
