<?php
$z[0]=Array("field","细细的红线/狂林战曲/红色警戒线",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","细细的红线/狂林战曲/红色警戒线[HD中英双字1024x576高清版]迅雷下载、免费下载，细细的红线/狂林战曲/红色警戒线[HD中英双字1024x576高清版]Gvod高清在线播放，剧情介绍等。",73,279);
$z[1][4]['name']="description";
$z[2]=Array("field","细细的红线/狂林战曲/红色警戒线[HD中英双字1024x576高清版]",281,375);
$z[2][4]['name']="title";
$z[3]=Array("field","",377,416);
$z[3][4]['name']="writer";
$z[4]=Array("field","",418,457);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-08-24",459,509);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",511,548);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://3e:3e@d8.3edyy.com:174/【3E电影院www.eee4.cc】细细的红线HD中英双字1024x576高清版.rmvb\" target=\"_blank",550,696);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MP636230-3GM.jpg",698,780);
$z[8][4]['name']="litpic";

?>