{dede:field name='keywords'}世贸中心[DVD中英字幕1024x576高{/dede:field}
{dede:field name='description'}世贸中心[DVD中英字幕1024x576高清版]迅雷下载、免费下载，世贸中心[DVD中英字幕1024x576高清版]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}世贸中心[DVD中英字幕1024x576高清版]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2009-01-08{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://e42:e42@xl2.eee4.com:1002/[3E电影站www.eee4.com]世贸中心[DVD中英双字1024x576版].rmvb" target=_blank>ftftp://e42:e42@xl2.eee4.com:1002/[3E电影站www.eee4.com]世贸中心[DVD中英双字1024x576版].rmvb</A></TD></TR></TBODY></TABLE><BR><FONT color=#ff0000 size=2><STRONG>尼古拉斯凯奇票房过亿经典历史灾难大片《世贸中心》DVD中英字幕【<FONT color=#0909f7>880分辨率</FONT>】 －来自[3E电影站www.eee4.com]：<IMG src="httftp://www.eee4.com/templets/img/down.jpg" border=0></STRONG></FONT><BR>CD1：<BR>
<TABLE style="BORDER-RIGHT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; BORDER-BOTTOM: #cccccc 1px dotted" cellSpacing=0 cellPadding=6 width="95%" align=center border=0>
<TBODY>
<TR>
<TD style="WORD-WRAP: break-word" bgColor=#fdfddf><ANCHOR></ANCHOR><A href="ftftp://e13:e13@xl2.eee4.com:9916/[3E电影站www.eee4.com]世贸中心DVD中英双字CD1.rmvb" target=_blank>ftftp://e13:e13@xl2.eee4.com:9916/[3E电影站www.eee4.com]世贸中心DVD中英双字CD1.rmvb</A></TD></TR></TBODY></TABLE>CD2：<BR>
<TABLE style="BORDER-RIGHT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; BORDER-BOTTOM: #cccccc 1px dotted" cellSpacing=0 cellPadding=6 width="95%" align=center border=0>
<TBODY>
<TR>
<TD style="WORD-WRAP: break-word" bgColor=#fdfddf><ANCHOR></ANCHOR><A href="ftftp://e13:e13@xl2.eee4.com:9916/[3E电影站www.eee4.com]世贸中心DVD中英双字CD2.rmvb" target=_blank>ftftp://e13:e13@xl2.eee4.com:9916/[3E电影站www.eee4.com]世贸中心DVD中英双字CD2.rmvb</A></TD></TR></TBODY></TABLE></div><ul class="mmlist{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MPU920-21T4.jpg{/dede:field}
