<?php
$z[0]=Array("field","宇宙系列第1季：太阳的秘密/火星",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","宇宙系列第1季：太阳的秘密/火星：红色行星【第五集】迅雷下载、免费下载，宇宙系列第1季：太阳的秘密/火星：红色行星【第五集】Gvod高清在线播放，剧情介绍等。",73,267);
$z[1][4]['name']="description";
$z[2]=Array("field","宇宙系列第1季：太阳的秘密/火星：红色行星【第五集】",269,357);
$z[2][4]['name']="title";
$z[3]=Array("field","",359,398);
$z[3][4]['name']="writer";
$z[4]=Array("field","",400,439);
$z[4][4]['name']="source";
$z[5]=Array("field","2012-05-21",441,491);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",493,530);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://e30:e30@xl2.eee4.com:9916/[3E电影站www.eee4.com]宇宙系列01-太阳的秘密.rmvb\" target=\"_blank",532,667);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MP4E0Z-4S95.jpg",669,750);
$z[8][4]['name']="litpic";

?>