<?php
$z[0]=Array("field","漂亮的MTV-梦入桃花源-陈思思MTV",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","漂亮的MTV-梦入桃花源-陈思思MTV音乐迅雷下载、免费下载，漂亮的MTV-梦入桃花源-陈思思MTV音乐Gvod高清在线播放，剧情介绍等。",73,235);
$z[1][4]['name']="description";
$z[2]=Array("field","漂亮的MTV-梦入桃花源-陈思思MTV音乐",237,309);
$z[2][4]['name']="title";
$z[3]=Array("field","",311,350);
$z[3][4]['name']="writer";
$z[4]=Array("field","",352,391);
$z[4][4]['name']="source";
$z[5]=Array("field","2006-08-04",393,443);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<P>播放后双击视频“全屏”</P> \n<object classid=\"CLSID:22d6f312-b0f6-11d0-94ab-0080c74c7e95\" class=\"OBJECT\" id=\"MediaPlayer\" width=\"500\" height=\"350\" ><param name=\"ShowStatusBar\" value=\"-1\"><param name=\"Filename\" value=\"http://www.cwaol.gov.cn/cdnylm/zxj/flash/thy.wmv\"></embed></object><br /> \n<P>下载地址<BR></P> <br>",445,800);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c120524/133N353DD0-2G248.gif",802,885);
$z[7][4]['name']="litpic";

?>