<?php
$z[0]=Array("field","地火危城/火山爆发/活火熔城迅雷",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","地火危城/火山爆发/活火熔城迅雷下载、免费下载，地火危城/火山爆发/活火熔城Gvod高清在线播放，剧情介绍等。",73,219);
$z[1][4]['name']="description";
$z[2]=Array("field","地火危城/火山爆发/活火熔城",221,285);
$z[2][4]['name']="title";
$z[3]=Array("field","",287,326);
$z[3][4]['name']="writer";
$z[4]=Array("field","",328,367);
$z[4][4]['name']="source";
$z[5]=Array("field","2008-02-21",369,419);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",421,458);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://eee4.com:8011@vip6.eee4.com:8011/活火熔城/[3E迅雷电影站www.eee4.com]活火熔城DVD.rmvb\" target=\"_blank",460,605);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MPU4240-14519.jpg",607,690);
$z[8][4]['name']="litpic";

?>