{dede:field name='keywords'}非诚勿扰20120513期迅雷下载，免{/dede:field}
{dede:field name='description'}非诚勿扰20120513期迅雷下载、免费下载，非诚勿扰20120513期Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}非诚勿扰20120513期{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-14{/dede:field}
{dede:field name='body'}<p>
	&nbsp;<img src="/uploads/allimg/c120524/133N4U53W0-212444.jpg" /></p>
<p>
	<img src="/uploads/allimg/c120524/133N4OUL0-11B45.jpg" /></p>
<p>
	<img src="/uploads/allimg/c120524/133N4U542P-22SX.jpg" /></p>
<p>
	&nbsp;<img src="/uploads/allimg/c120524/133N4U54560-232306.jpg" /></p>
<p>
	&nbsp;<img src="/uploads/allimg/c120524/133N4U54H0-246122.jpg" /></p>
<p>
	<img src="/uploads/allimg/c120524/133N4U550-2594X.jpg" /></p>
<p>
	近些年，电视荧屏几乎都是唱歌、跳舞类节目一统天下，婚恋交友类节目的风行还是在十年前。谈及此次《非诚勿扰》节目的创作，节目制片人王刚介绍，&ldquo;绝对是办公室里的剩男剩女太多激发了我们的创作灵感。平时大家总是一边加班一边抱怨找不到对象，同时我们也了解到现在社会竞争压力下，剩男剩女已经成为社会现象和话题，这种现象其实也掩藏着很多社会问题，对于婚姻和感情缺乏信任是很多年轻人难以解开的心结，解决此问题就成了《非诚勿扰》的创意来源！&rdquo; </p>
<p>
	10年前，以《非常男女》、《相约星期六》为代表的男女婚恋交友类节目曾风靡一时，此次江苏卫视再推此类型节目，是否还是过去节目的翻版或克隆？对此，王刚介绍道，新节目的互动形式将完全突破过去举牌、表白、亲友团意见等传统交友的方式，完全体现新时代男女的爱情观。现在男女都追求一个&ldquo;第一眼印象&rdquo;，所以我们每期节目将有若干男生依次上台与现场的20位女生进行互动，有可能只要5分钟时间，我们的男生就可以自己做主成功牵手女生开始他们的爱情。&nbsp;</p>
<table bgcolor="#0099cc" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
			<td bgcolor="#00ffff" style="line-height: 18px; word-break: break-all" width="100%">
				&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2010年非诚勿扰</td>
		</tr>
	</tbody>
	<tbody>
		<tr>
			<td bgcolor="#00ffff" style="line-height: 18px; word-break: break-all" width="100%">
				&nbsp;&nbsp;&nbsp;&nbsp; 2011年非诚勿扰</td>
		</tr>
	</tbody>
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:2508/飘花电影piaohua.com非诚勿扰20120101期.rmvb</td>
		</tr>
	</tbody>
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:2508/飘花电影piaohua.com非诚勿扰20120102期.rmvb</td>
		</tr>
	</tbody>
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:2566/飘花电影piaohua.com非诚勿扰20120107期.rmvb</td>
		</tr>
	</tbody>
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:2566/飘花电影piaohua.com非诚勿扰20120108期.rmvb</td>
		</tr>
	</tbody>
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:2634/飘花电影piaohua.com非诚勿扰20120114期.rmvb</td>
		</tr>
	</tbody>
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:2634/飘花电影piaohua.com非诚勿扰20120115期.rmvb</td>
		</tr>
	</tbody>
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:2716/飘花电影piaohua.com非诚勿扰20120120期.rmvb </td>
		</tr>
	</tbody>
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:2716/飘花电影piaohua.com非诚勿扰20120121期.rmvb </td>
		</tr>
	</tbody>
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:2716/飘花电影piaohua.com非诚勿扰20120128期.rmvb </td>
		</tr>
	</tbody>
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:2716/飘花电影piaohua.com非诚勿扰20120129期.rmvb </td>
		</tr>
	</tbody>
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:2760/飘花电影piaohua.com非诚勿扰20120204期.rmvb </td>
		</tr>
	</tbody>
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:2760/飘花电影piaohua.com非诚勿扰20120205期.rmvb </td>
		</tr>
	</tbody>
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:2784/飘花电影piaohua.com非诚勿扰20120211期.rmvb</td>
		</tr>
	</tbody>
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:2784/飘花电影piaohua.com非诚勿扰20120212期.rmvb</td>
		</tr>
	</tbody>
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:2848/飘花电影piaohua.com非诚勿扰20120218期.rmvb</td>
		</tr>
	</tbody>
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:2853/飘花电影piaohua.com非诚勿扰20120219期.rmvb</td>
		</tr>
	</tbody>
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:2891/飘花电影piaohua.com非诚勿扰20120225期.rmvb</td>
		</tr>
	</tbody>
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:2896/飘花电影piaohua.com非诚勿扰20120226期.rmvb</td>
		</tr>
	</tbody>
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:2954/飘花电影piaohua.com非诚勿扰20120303期.rmvb</td>
		</tr>
	</tbody>
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:2954/飘花电影piaohua.com非诚勿扰20120304期.rmvb</td>
		</tr>
	</tbody>
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:2993/飘花电影piaohua.com非诚勿扰20120310期.rmvb</td>
		</tr>
	</tbody>
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:2998/飘花电影piaohua.com非诚勿扰20120311期.rmvb</td>
		</tr>
	</tbody>
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:3039/飘花电影piaohua.com非诚勿扰20120317期.rmvb</td>
		</tr>
	</tbody>
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:3040/飘花电影piaohua.com非诚勿扰20120318期.rmvb</td>
		</tr>
	</tbody>
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:3076/飘花电影piaohua.com非诚勿扰20120324期.rmvb</td>
		</tr>
	</tbody>
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:3074/飘花电影piaohua.com非诚勿扰20120325期.rmvb</td>
		</tr>
	</tbody>
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:3127/飘花电影piaohua.com非诚勿扰20120331期.rmvb</td>
		</tr>
	</tbody>
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:3127/飘花电影piaohua.com非诚勿扰20120401期.rmvb</td>
		</tr>
	</tbody>
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:3186/飘花电影piaohua.com非诚勿扰20120407期.rmvb</td>
		</tr>
	</tbody>
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:3186/飘花电影piaohua.com非诚勿扰20120408期.rmvb</td>
		</tr>
	</tbody>
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:3230/飘花电影piaohua.com非诚勿扰20120414期.rmvb</td>
		</tr>
	</tbody>
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:3230/飘花电影piaohua.com非诚勿扰20120415期.rmvb</td>
		</tr>
	</tbody>
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:3276/飘花电影piaohua.com非诚勿扰20120421期.rmvb</td>
		</tr>
	</tbody>
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:3276/飘花电影piaohua.com非诚勿扰20120422期.rmvb</td>
		</tr>
	</tbody>
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:3324/飘花电影piaohua.com非诚勿扰20120428期.rmvb</td>
		</tr>
	</tbody>
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:3324/飘花电影piaohua.com非诚勿扰20120429期.rmvb</td>
		</tr>
	</tbody>
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:3365/飘花电影piaohua.com非诚勿扰20120505期.rmvb</td>
		</tr>
	</tbody>
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:3365/飘花电影piaohua.com非诚勿扰20120506期.rmvb</td>
		</tr>
	</tbody>
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:3415/飘花电影piaohua.com非诚勿扰20120512期.rmvb</td>
		</tr>
	</tbody>
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:3415/飘花电影piaohua.com非诚勿扰20120513期.rmvb</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120524/133N4U55260-2D358.jpg{/dede:field}
