{dede:field name='keywords'}猛男军中鬼故事DVD国语中字2011{/dede:field}
{dede:field name='description'}猛男军中鬼故事DVD国语中字2011新加坡恐怖迅雷下载、免费下载，猛男军中鬼故事DVD国语中字2011新加坡恐怖Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}猛男军中鬼故事DVD国语中字2011新加坡恐怖{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-21{/dede:field}
{dede:field name='body'}<p>
	&nbsp;<img border="0" src="http://www.ys3344.com/files/post/20120505083915791.jpg" /></p>
<p>
	◎译　　名&nbsp;&nbsp; 猛男军中鬼故事<br />
	◎片　　名　23:59&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br />
	◎年　　代　2011<br />
	◎国　　家　新加坡<br />
	◎类　　别　恐怖/惊悚<br />
	◎语　　言　国语<br />
	◎字　　幕　中文/英文<br />
	◎IMDB评分&nbsp; N/A&nbsp;&nbsp;<br />
	◎IMDB链接&nbsp; <a href="http://www.bluemv.com">http://www.bluemv.com</a><br />
	◎片　　长　78 Mins<br />
	◎导　　演　陈启全 Gilbert Chan<br />
	◎主　　演　Tedd Chan&nbsp; &hellip;.Tan&nbsp;&nbsp;<br />
	　　　　　　Stella Chung&nbsp; &hellip;.Shirley<br />
	　　　　　　Henley Hii&nbsp; &hellip;.Jeremy<br />
	　　　　　　Lawrence Koh&nbsp; &hellip;.Dragon&nbsp;&nbsp;<br />
	　　　　　　Tommy Kuan&nbsp; &hellip;.Lim&nbsp;&nbsp;<br />
	　　　　　　Josh Lai&nbsp; &hellip;.Chester&nbsp;&nbsp;<br />
	　　　　　　Mark Lee&nbsp; &hellip;.Sergeant Kuah<br />
	　　　　　　Susan Leong&nbsp; &hellip;.Yi Gu&nbsp;&nbsp;&nbsp;&nbsp;<br />
	　　　　　　Benjamin Lim&nbsp; &hellip;.Captain Hong</p>
<p>
	<br />
	◎简　　介　</p>
<p>
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 　　　传言中午夜是一天中最邪恶的时刻，若有人在此刻死亡，灵魂将永不超生。 1983年一处新加坡训练营，岛上传言有位疯癫妇人于午夜23:59离奇身亡。新兵Tan个性内向孤僻，总觉得自己将是下一个被女鬼缠上的目标。他尝试向好友Jeremy倾诉女鬼每晚都会来缠着他918ys。在ㄧ次军队24公里长途行军中，军队必须穿越丛林，Tan在此次行军中离奇死亡，被发现时四肢以一种奇怪的方式扭曲着。身为好友的Jeremy坚信Tan的死不是意外，并决定展开调查。</p>

<p>
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120505/08/6436927420120505084557012.jpg" width="700" /></p>
<p>
	&nbsp;<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120505/08/6436927420120505084525063.jpg" width="700" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.net/">http://www.xiaozhizhu.net</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3360/飘花电影piaohua.com猛男军中鬼故事DVD国语中字.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3360/飘花电影piaohua.com猛男军中鬼故事DVD国语中字.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O16445340-1A95.jpg{/dede:field}
