{dede:field name='keywords'}赛车总动员2BD高清/国粤台英语港{/dede:field}
{dede:field name='description'}赛车总动员2BD高清/国粤台英语港版中文化界面迅雷下载、免费下载，赛车总动员2BD高清/国粤台英语港版中文化界面Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}赛车总动员2BD高清/国粤台英语港版中文化界面{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-11-15{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="/uploads/allimg/c120525/133O04462J0-1NM.jpg" style="width: 700px; height: 882px" /></p>
<p>
	◎译　　名　赛车总动员2/汽车总动员2/3D反斗車王2(港)/Cars2：世界大赛(台)<br />
	◎片　　名　Cars 2<br />
	◎年　　代　2011<br />
	◎国　　家　美国<br />
	◎类　　别　动画/冒险/喜剧/家庭<br />
	◎语　　言　英语/日语/意大利语/法语<br />
	◎字　　幕　中英双字<br />
	◎IMDB评分 &nbsp; 6.5/10 (13,097 votes)<br />
	◎IMDB链接 &nbsp; http://www.imdb.com/title/tt1216475/<br />
	◎文件格式　X264 + DTS<br />
	◎片　　长　01:47:01<br />
	◎导　　演　约翰&middot;拉塞特 John Lasseter<br />
	　　　　　　布拉德&middot;刘易斯 Brad Lewis ....(co-director)<br />
	◎主　　演　欧文&middot;威尔逊 Owen Wilson ....Lightning McQueen (voice)<br />
	　　　　　　王牌接线员拉里 Larry The Cable Guy ....Mater (voice)<br />
	　　　　　　迈克尔&middot;凯恩 Michael Caine ....Finn McMissile (voice)<br />
	　　　　　　艾米莉&middot;莫迪默 Emily Mortimer ....Holley Shiftwell (voice)<br />
	　　　　　　艾迪&middot;伊扎德 Eddie Izzard ....Sir Miles Axlerod (voice)<br />
	　　　　　　约翰&middot;特托罗 John Turturro ....Francesco Bernoulli (voice)<br />
	　　　　　　Brent Musburger ....Brent Mustangburger (voice)<br />
	　　　　　　乔&middot;曼特纳 Joe Mantegna ....Grem (voice)<br />
	　　　　　　托马斯&middot;克莱舒曼 Thomas Kretschmann ....Professor Z (voice)<br />
	　　　　　　彼得&middot;雅各布森 Peter Jacobson ....Acer (voice)<br />
	　　　　　　邦尼&middot;亨特 Bonnie Hunt ....Sally (voice)<br />
	　　　　　　Darrell Waltrip ....Darrell Cartrip (voice)<br />
	　　　　　　弗兰科&middot;尼罗 Franco Nero ....Uncle Topolino (voice)<br />
	　　　　　　David Hobbs ....David Hobbscap (voice)<br />
	　　　　　　Patrick Walker ....Mel Dorado (voice)<br />
	　　　　　　托尼&middot;夏尔赫布 Tony Shalhoub ....Luigi (voice)<br />
	　　　　　　杰夫&middot;格尔林 Jeff Garlin ....Otis (voice)<br />
	　　　　　　Michel Michelis ....Tomber (voice)<br />
	　　　　　　詹森&middot;艾萨克 Jason Isaacs ....Siddeley &amp;amp;amp; Leland Turbo (voice)<br />
	　　　　　　Lloyd Sherr ....Fillmore &amp;amp;amp; Combat Ship (voice)<br />
	　　　　　　布鲁斯&middot;坎贝尔 Bruce Campbell ....Rod &#39;Torque&#39; Redline (voice)<br />
	　　　　　　Teresa Gallagher ....Mater&#39;s Computer (voice)<br />
	　　　　　　詹妮弗&middot;路易斯 Jenifer Lewis ....Flo (voice)<br />
	　　　　　　Stanley Townsend ....Victor Hugo / Vladimir Trunkov / Ivan the Tow Truck (voice)<br />
	　　　　　　Velibor Topic ....Alexander Hugo (voice)<br />
	　　　　　　Sig Hansen ....Crabby (voice)<br />
	　　　　　　Guido Quaroni ....Guido (voice)<br />
	　　　　　　瓦妮莎&middot;雷德格瑞夫 Vanessa Redgrave ....The Queen / Mama Topolino (voice)<br />
	　　　　　　John Mainieri ....J. Curby Gremlin (voice)<br />
	　　　　　　布拉德&middot;刘易斯 Brad Lewis ....Tubbs Pacer (voice)<br />
	　　　　　　切奇&middot;马林 Cheech Marin ....Ramone (voice)<br />
	　　　　　　Jeff Gordon ....Jeff Gorvette (voice)<br />
	　　　　　　Lewis Hamilton ....Lewis Hamilton (voice)<br />
	　　　　　　Paul Dooley ....Sarge (voice)<br />
	　　　　　　Edie McClurg ....Minny (voice)<br />
	　　　　　　理查德&middot;坎德 Richard Kind ....Van (voice)<br />
	　　　　　　Katherine Helmond ....Lizzie (voice)<br />
	　　　　　　约翰&middot;拉岑贝格 John Ratzenberger ....Mack (voice)<br />
	　　　　　　Michael Wallis ....Sheriff (voice)<br />
	　　　　　　杰斯&middot;哈梅尔 Jess Harnell ....Additional Voices (voice)<br />
	　　　　　　约翰&middot;拉塞特 John Lasseter ....John Lassetire (voice)<br />
	　　　　　　Colleen O&#39;Shaughnessey ....Additional Voices (voice)<br />
	　　　　　　Fernando Alonso ....Fernando Alonso (voice: Spanish release)<br />
	　　　　　　Konishi Sonoko ....Japanese toilet assistant voice (voice)<br />
	　　　　　　Jan Nilsson ....Flash (voice: Swedish release)<br />
	　　　　　　Vitaly Petrov ....Vitaly Petrov (voice: Russian release)<br />
	　　　　　　Memo Rojas ....Memo Rojas (voice: Latin American release)<br />
	　　　　　　Sebastian Vettel ....Sebastian Schnell (voice: German release)<br />
	　　　　　　Mark Winterbottom ....Frosty (voice: Australian release)<br />
	　　　　　　黄磊 Lei Huang ....闪电麦昆（中文配音）<br />
	　　　　　　范伟 Wei Fan ....拖车板牙（中文配音）<br />
	　　　　　　姚晨 Chen Yao ....荷莉（中文配音）<br />
	<br />
	<br />
	<br />
	◎简 &nbsp;　 介<br />
	<br />
	剧情<br />
	<br />
	&nbsp; &nbsp; 《赛车总动员2》主要讲述了闪电麦坤和板牙在世界各地的精彩遭遇。为了决出谁是世界上最快的赛车，他们参加了&ldquo;世界杯大赛&rdquo;。<br />
	<br />
	一句话评论<br />
	<br />
	一部包含了许多元素还令人无比欢乐的动画片！<br />
	<br />
	&mdash;&mdash;《芝加哥太阳时报》<br />
	<br />
	这部续集给观众的热情远远超出了第一集.<br />
	<br />
	&mdash;&mdash;《滚石》<br />
	<br />
	比第一集的视野更加广阔，讲述的内容也更加的丰富多彩.<br />
	<br />
	&mdash;&mdash;《旧金山记事报》<br />
	<br />
	幕后制作<br />
	<br />
	　　风格延续 享受比赛<br />
	　　2006年，一部名为《赛车总动员》的动画片面世，这部由皮克斯制作的动画片破天荒的将汽车拟人化，制造出有各种表情的汽车，在全球获得4.6亿的票房成绩。事隔五年，本片的续集终于也来到观众面前。谈及这部卖座动画片的续集情况，系列导演约翰&middot;拉塞特说道：&ldquo;这部电影的续集计划很早就已经定下来，并且很快就进入了制作阶段。其实一开始，我们还有疑虑，那就是这部动画片比我们想象的要简单，一开始我们设计了许多故事，世界观很大，但最后很多都没有采用。那么在续集里，我们应该怎么去设定整个故事呢，是否还要做成像第一集这样，以小见大，在某个小镇上延续故事。这当然是不太现实的，因为观众一定乐意见到输掉比赛的麦昆在未来如何绽放光彩，所以在续集的故事里，我们将由麦昆带着去世界各国飙车，大家会看到一部视野更加广阔的《赛车总动员2》。&rdquo;<br />
	　　在第一集《赛车总动员》里，传达出这么一个理念，那就是费尽心机去争第一并不重要，关键是要享受比赛的过程。有意思的是，在次年的奥斯卡之争里，《赛车总动员》也最终输给了《欢乐的大脚》。对于影片的这个主题，同时兼任本片编剧的约翰&middot;拉塞特说道：&ldquo;每一部动画片，都应该告诉小孩子们一个道理，同时这个道理也对大人适用，这是我制作动画片的一个理念。《赛车总动员》是一部以竞赛的故事为主线的电影，但观众看完之后回明白，这部电影并不是要教育人们去争输赢，而是通过电影来希望大家能够不要太执着于一场比赛的胜负，如何在比赛里拿到对自己有用的东西，那才是最重要的。所以在第二集里，闪电麦昆会将这个理念发扬光大，观众能看到他的心态更加平和，更加不在乎输赢，享受比赛的过程，反倒是这样，他变得更加的不可战胜。&rdquo;<br />
	　　不再据守西部小镇做社工，那么在这一集《赛车总动员2》里，故事还会有什么样的发展与变化呢？对此，给闪电麦昆配音的欧文&middot;威尔逊说道：&ldquo;这一集里的闪电麦昆会非常神奇，他依然是赛车界的超级明星，而且将在很多国家遇到许多强劲的对手，故事有很大部分都在欧洲展开，大家可以跟着麦昆一起领略欧洲的风情。同时麦昆和他在小镇上的朋友们也会有许多互动，例如和板牙的故事，也是这一集的重点。当然还有他的情感生活，这一集里我们的麦昆谈起了恋爱&hellip;&hellip;比较起第一集，在这一集中他的性格会更加立体，做的事情也更多，整部电影很有动作片的气势&hellip;&hellip;当然，也为第三集做了足够的铺垫。我相信这部电影能收到比上一集更多的好评。享受它！&rdquo;<br />
	　　技术上的再进一步<br />
	　　五年前的《赛车总动员》曾让大家惊叹，原来死板的钢铁机器，也可以被皮克斯拟人得如此栩栩如生；五年后，《赛车总动员2》会在技术上呈现出什么不一样的效果呢？对此，影片导演约翰&middot;拉塞特说道：&ldquo;本片和第一集最大的不同之处在于它的3D化，这部电影的制作时间在《玩具总动员3》之后，所以我们在《玩具总动员3》的成功基础上有了经验，在《赛车总动员2》里有一个优势，那就是本片的赛车段落，用3D来呈现，是剧情与技术的一个很好的结合。所以这部电影在3D方面会有一个极其精彩的呈现，值得大家好好欣赏。观众们应该注意到本片最后的赛车段落，那是本片的压轴大戏，所以在3D效果的展现上我们花了很多时间去分析准备，这一段值得观众留意。&rdquo;<br />
	　　两次倾情配音界的大明星&ldquo;闪电麦昆&rdquo;，欧文&middot;威尔逊坦言了对这个角色的喜爱：&ldquo;麦昆是一个很特别的角色，它是一辆车，还会说话，做出那么多可爱的表情。这部电影颠覆了我对动画片的认识，原来3D动画还会有这么多可能性。第一集里的麦昆是一个骄横的赛车手，它太自信而自负，所以他遭受了挫折，小镇改变了他，他也改变了小镇。到了第二集里，他会带领小镇的居民一起走向世界，展开各种冒险，故事更加复杂，而麦昆也向观众展现出他勇敢无畏的一面。当然，我更喜欢它的是，我会和它一起在各国参加比赛，观众们如果在上一集因为赛车戏份过少而没有感到满足，在《赛车总动员2》里一定会大呼过瘾！&rdquo;<br />
	<br />
	花絮<br />
	<br />
	&middot;在第一集里为道克&middot;哈德森配音的保罗&middot;纽曼于2008年去世。制作组为了表示对保罗&middot;纽曼的悼念，哈德森没有出现在本片当中。<br />
	&middot;本片是第一部约翰&middot;拉塞特执导的电影而没有兰迪&middot;纽曼配音的作品。<br />
	&middot;约翰&middot;拉塞特还在欧洲宣传第一集的时候，就已经在构思续集的故事。<br />
	&middot;本片是皮克斯继《玩具总动员》之后，第二部制作续集的动画片。</p>
<p>
	<img alt="" src="/uploads/allimg/c120525/133O044BY0-21b1.jpg" style="width: 720px; height: 405px" /><img alt="" src="/uploads/allimg/c120525/133O044D020-34329.jpg" style="width: 720px; height: 405px" /><img alt="" src="/uploads/allimg/c120525/133O044E210-46339.jpg" style="width: 720px; height: 405px" /><img alt="" src="/uploads/allimg/c120525/133O044F40-5NO.jpg" style="width: 720px; height: 405px" /><br />
	&nbsp;</p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="/uploads/allimg/c120524/133N2Z4FF-102231.jpg" />&nbsp;&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy125:piaohua@dy125.piaohua.com:7175/飘花电影piaohua.com汽车总动员2BD国粤台英4语中英双字1280高清.mkv</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O044G440-64296.jpg{/dede:field}
