{dede:field name='keywords'}小马精灵/小马王HD中英双字1024{/dede:field}
{dede:field name='description'}小马精灵/小马王HD中英双字1024高清迅雷下载、免费下载，小马精灵/小马王HD中英双字1024高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}小马精灵/小马王HD中英双字1024高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-03-12{/dede:field}
{dede:field name='body'}<p>
	◎中文片名：《小马精灵/小马王》2002年美国经典动画大片DVD国语中字<br />
	◎英文片名：SPIRIT<br />
	◎出品年代：2002<br />
	◎国家地区：美国<br />
	◎类　　别：动画<br />
	◎对白语言：普通话<br />
	◎字　　幕：中文字幕<br />
	◎文件格式：rmvb<br />
	◎文件大小：1CD 257M<br />
	◎视频大小：800 x 444<br />
	◎片　　长：01:23:26<br />
	◎导　　演：凯利&middot;阿斯波利 罗娜&middot;库克<br />
	◎主要演员：马特&middot;达蒙 丹尼尔&middot;斯塔蒂 詹姆斯&middot;克伦威尔<br />
	◎简　　介：</p>
<p>
	　　原始的美国西部，一个原始、野蛮但同时也是充满了自由空气的理想国度。而我们的主人公，一匹充满野性的不驯的小马，就出生在这个美丽的地方。斯比尔特，它的名字，象征着向往自由的灵魂，象征着一切不肯屈服的灵魂。它是生来要成为领导者的，它是群落里的希望与未来之星。所以它的成长道路上，也将与所有为成功而奋斗的生命一样，面对无尽的磨难。但是，尽管需要时刻提防着在邪恶的角落里准备征服和占有它的骑士团上校（詹姆斯&middot;克伦威尔配音），尽管要分心去追逐自己心中的&ldquo;爱人&rdquo;雨，但是在它的印第安人朋友克里克（丹尼尔&middot;斯塔蒂配音）的帮助和自己顽强的努力下，在那遥远的美丽的西部，又一个伟大的英雄，从此诞生。</p>
<p>
	<img alt="" border="0" onclick="zoom(this, 'attachments/20090416_b7179fce43b58e42917bIgSbsYbyScg5.jpg')" onload="attachimg(this, 'load')" onmouseout="attachimginfo(this, 'attach_118000', 0, event)" onmouseover="attachimginfo(this, 'attach_118000', 1);attachimg(this, 'mouseover')" src="http://www.eee4.com/0701pic/allimg/090601/1638350.jpg" /></p>
<p>
	◎打破传统：</p>
<p>
	　　《小马精灵》是一部成功结合了2D与3D技术的动画片，而它的镜头从三维场景切换到二维并再此切换回三维的过程中，你将感受不到视觉的差异。虽然现在的潮流是呼唤更多三维技术的运用，但是正像梦工厂三巨头之一、担任本片制片的杰弗瑞&middot;卡森伯格所说，科技再成熟，鼠标也永远取代不了人类的双手和他们手中的铅笔。有一种神韵，是需要用传统的绘画手法所表现的。正像电子游戏的一个经典《轩辕剑-天之痕》，背景与人物完全采用中国传统的水墨工笔绘制，但那富有表现力的唯美的境界，使它成为武侠游戏中的一个里程碑。</p>
<p>
	　　而最重要的是，这次，不同于其它同类动画片，片中的动物们将不再开口说话。卡森伯格说，如果我们让动物说话，那么无论你再作任何努力，这都将使本片更像是一部滑稽的喜剧。这与他所竭力想表现的主题，无疑是冲突的。所以，梦工厂接受了挑战，一个没有语言的主人公，将通过它的神情、简单的旁白和适时的音乐来展现它的内心世界。</p>
<p>
	◎寻找马的灵魂：</p>
<p>
	　　马是一种有灵性的动物，它聪明、忠诚。它外形俊美，行动敏捷。动画制作者詹姆斯&middot;巴克思特知道这次他面临一个巨大的挑战。他在自己的工作室外面挂上请勿打扰的牌子，全心投入到没日没夜的钻研中。他和他的团队，从临摹真实中的骏马开始，从观察它们每一个细微动作入手，甚至，为了更好的了解马的习性，梦工厂还专门聘请了两位资深&ldquo;马&rdquo;学专家来帮助制作小组读懂马的内心世界，从而使动画的形象更为传神。</p>
<p>
	　　而真实中也的确有一个斯皮尔特的原型，从这匹真实的小马身上，绘画者受益菲浅。</p>
<p>
	◎语言和音乐：</p>
<p>
	　　这是一个没有多少人类语言的影片，因为主角是我们的小马。但所有的对话与旁白，都是精心编写的。而在表现上，尤其是旁白，在马特&middot;达蒙的简练而富有魅力的描述下，我们仿佛亲身走进了那亦真亦幻的动画世界中。凭借《心灵捕手》（Good Will Hunting）一片，马特&middot;达蒙曾获得奥斯卡和金球奖的最佳男演员提名，并最终获得奥斯卡及金球奖最佳剧本大奖。他出演的知名影片还包括斯皮尔伯格的《拯救大兵瑞恩》和近期全明星阵容的《十一罗汉》（Ocean&quot;s Eleven）。</p>
<p>
	　　最为关键的音乐部分，动用了金牌音乐制作人汉斯&middot;基墨（Hans Zimmer）和著名歌手布莱恩&middot;亚当斯（Bryan Adams），使得这部影片的音乐充满了惊喜。前者七度获得奥斯卡最佳音乐提名，94年的《狮子王》获得奥斯卡及金球奖的两项最佳配乐大奖，最近的作品包括去年的《角斗士》和今年的《珍珠港》。布莱恩&middot;亚当斯也是成绩显赫之辈，凭借《（Everything I Do）I Do It for You》、《Have You Ever Really Loved a Woman》和《I&quot;ve Finally Found Someone》等在影片插曲，这位加拿大人获得了三次奥斯卡提名和三次金球奖提名，并且在美加的许多资深音乐大奖上屡有斩获。&ldquo;音乐反映了一个生命的灵魂。&rdquo;我们对这句话能否在这部影片中完美体现，应该已毫无怀疑。</p>
<p>
	◎西部的精神：</p>
<p>
	　　什么是西部的精神？至少在导演凯利&middot;阿斯波利的心中，会有他自己的解释。凯利似乎是为导演动画而生的。19年来，他先后执导了多部经典卡通片，例如《美女与野兽》、《玩具总动员》、《埃及王子》、《小鸡快跑》和最近的《怪物史莱克》。给人一种感觉，似乎所有我们看过的美国好的卡通，都是他的手笔。：）</p>
<p>
	　　那么本片是如何来理解西部的精神的呢？首先它应该是一种自由，一种平等。在美国西进运动的前后，西部是完全不同的景象。而导演正是试图通过一匹马的眼光，来从新审视这其中的巨大变化。这时候马的心态，和面对外来者的疯狂洗劫的印第安部落，应该是一致的。本片也正是借助动物的反抗，来表现人的反抗。可见这种尝试，已经从主题上面超越了过去那种童话似的动画片模式，已经试图接近严肃的一些东西。</p>
<p>
	　　其实通过卡通手段表现成熟的主题已不是什么太新颖的事情。至少日本的卡通作者很早就开始这种尝试了。动画大师宫崎骏的著名动画《幽灵公主》和近期的《千与千寻》作为剧场版动画早已经把眼光对准成人世界了的观众了。而现在美国也已经开始这方面的尝试，就连台湾地区的漫画家也早就有非常成功的面对非儿童的武侠漫画出现。那么我们国内这些幼稚的幼儿动画，又何时能有一个质的飞跃与改变呢？这相信，是所有卡通爱好者共同的疑问与期待吧。随着我们的长大，难道注定卡通就要成为儿时的玩具一样，离我们而去么？</p>
<p>
	2002年美国经典动画大片《小马精灵》DVD国语中字 ：<img border="0" src="http://www.eee4.com/templets/img/down.jpg" /></p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://3e:3e@www2.eee4.com:195/[3E电影站www.eee4.com]小马王DVD国语中字.rmvb" target="_blank">ftp://3e:3e@www2.eee4.com:195/[3E电影站www.eee4.com]小马王DVD国语中字.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2999/飘花电影piaohua.com小马王HD中英双字1024高清.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2999/飘花电影piaohua.com小马王HD中英双字1024高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1B51R0-53451.jpg{/dede:field}
