<?php
$z[0]=Array("field","兵人[DVD中英双字1024/1280高清]",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","兵人[DVD中英双字1024/1280高清]迅雷下载、免费下载，兵人[DVD中英双字1024/1280高清]Gvod高清在线播放，剧情介绍等。",73,227);
$z[1][4]['name']="description";
$z[2]=Array("field","兵人[DVD中英双字1024/1280高清]",229,297);
$z[2][4]['name']="title";
$z[3]=Array("field","",299,338);
$z[3][4]['name']="writer";
$z[4]=Array("field","",340,379);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-09-02",381,431);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",433,470);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://e13:e13@xl2.eee4.com:1003/[3E电影站www.eee4.com]兵人DVD中英双字CD1.rmvb\" target=\"_blank",472,604);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MO92H30-41M1.jpg",606,688);
$z[8][4]['name']="litpic";

?>