{dede:field name='keywords'}兵人[DVD中英双字1024/1280高清]{/dede:field}
{dede:field name='description'}兵人[DVD中英双字1024/1280高清]迅雷下载、免费下载，兵人[DVD中英双字1024/1280高清]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}兵人[DVD中英双字1024/1280高清]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-09-02{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://e13:e13@xl2.eee4.com:1003/[3E电影站www.eee4.com]兵人DVD中英双字CD1.rmvb" target="_blank{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MO92H30-41M1.jpg{/dede:field}
