<?php
$z[0]=Array("field","拆弹部队[DVD中字1280x688高清版",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","拆弹部队[DVD中字1280x688高清版无水印+1024x550]迅雷下载、免费下载，拆弹部队[DVD中字1280x688高清版无水印+1024x550]Gvod高清在线播放，剧情介绍等。",73,259);
$z[1][4]['name']="description";
$z[2]=Array("field","拆弹部队[DVD中字1280x688高清版无水印+1024x550]",261,345);
$z[2][4]['name']="title";
$z[3]=Array("field","",347,386);
$z[3][4]['name']="writer";
$z[4]=Array("field","",388,427);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-08-04",429,479);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",481,518);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://e44:e44@xl2.eee4.com:9024/[3E电影站www.eee4.com]拆弹部队DVD中字1280x688无水印.rmvb\" target=\"_blank",520,663);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MP520L0-33a6.jpg",665,747);
$z[8][4]['name']="litpic";

?>