{dede:field name='keywords'}我仍然知道你去年夏天干了什么/{/dede:field}
{dede:field name='description'}我仍然知道你去年夏天干了什么/到底是谁搞的鬼/旧年暑假仲有鬼[BD中英双字1024x576高清版]迅雷下载、免费下载，我仍然知道你去年夏天干了什么/到底是谁搞的鬼/旧年暑假仲有鬼[BD中英双字1024x576高清版]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}我仍然知道你去年夏天干了什么/到底是谁搞的鬼/旧年暑假仲有鬼[BD中英双字1024x576高清版]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-02-23{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://3e:3e@d3.3edyy.com:121/【3E电影院www.eee4.org】我仍然知道你去年夏天干了什么BD中英双字1024x576高清版.rmvb" target=_blank>ftftp://3e:3e@d3.3edyy.com:121/【3E电影院www.eee4.org】我仍然知道你去年夏天干了什么BD中英双字1024x576高清版.rmvb</A></TD></TR></TBODY></TABLE></div><ul class="mmlist{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MP363O0-45149.jpg{/dede:field}
