{dede:field name='keywords'}三十姑娘一朵花/女孩梦三十BD中{/dede:field}
{dede:field name='description'}三十姑娘一朵花/女孩梦三十BD中英双字1024/1280高清迅雷下载、免费下载，三十姑娘一朵花/女孩梦三十BD中英双字1024/1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}三十姑娘一朵花/女孩梦三十BD中英双字1024/1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-03{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img.album.pchome.net/54/68/49/45/23e83ee8650a20fe77eb40d2104ea05e.jpg" /></p>
<p>
	◎译　　名　《女孩梦三十/昨天13，今天30/三十姑娘一朵花/女大13变》近亿票房喜剧大片BD中英双字[880分辨率]<br />
	◎片　　名　13 Going On 30<br />
	◎年　　代　2004<br />
	◎国　　家　美国<br />
	◎类　　别　喜剧/爱情/奇幻/剧情&nbsp; &nbsp; &nbsp;<br />
	◎语　　言　英语<br />
	◎字　　幕　中英双字<br />
	◎IMDB评分&nbsp; 6.1/10 (25,866 votes)<br />
	◎视频尺寸　880 x 476<br />
	<br />
	Domestic:&nbsp; $57,231,747&nbsp; &nbsp; 59.3%<br />
	+ Foreign:&nbsp; $39,223,950&nbsp; &nbsp; 40.7%<br />
	--------------------------------------------------------------------------------<br />
	= Worldwide:&nbsp; $96,455,697<br />
	<br />
	◎导　　演　盖瑞&middot;温尼克 Gary Winick<br />
	◎主　　演　珍妮弗&middot;加纳 Jennifer Garner&nbsp; ....Jenna Rink<br />
	　　　　　　马克&middot;鲁弗洛 Mark Ruffalo&nbsp; ....Matt Flamhaff<br />
	　　　　　　安迪&middot;瑟金斯 Andy Serkis&nbsp; ....Richard Kneeland<br />
	　　　　　　朱迪&middot;格雷尔 Judy Greer&nbsp; ....Lucy Wyman<br />
	　　　　　　琳恩&middot;柯林斯 Lynn Collins&nbsp; ....Wendy<br />
	　　　　　　布瑞&middot;拉尔森 Brie Larson&nbsp; ....Six Chick<br />
	　　　　　　斯特沃特&middot;萨默斯 Stewart Summers&nbsp; ....Extra (uncredited)<br />
	　　　　　　Phil Reeves&nbsp; ....Wayne Rink<br />
	　　　　　　Samuel Ball&nbsp; ....Alex Carlson<br />
	　　　　　　Christa B. Allen&nbsp; ....Young Jenna<br />
	　　　　　　Sean Marquette&nbsp; ....Young Matt<br />
	　　　　　　Kiersten Warren&nbsp; ....Trish Sackett<br />
	　　　　　　Joe Grifasi&nbsp; ....Mr. Flamhaff<br />
	　　　　　　Mary Pat Gleason&nbsp; ....Mrs. Flamhaff<br />
	　　　　　　George Hine&nbsp; ....Grandy&#39;s Friend<br />
	<br />
	◎简　　介　<br />
	<br />
	&nbsp; &nbsp; &nbsp; 这个奇妙的故事发生在1987年。13岁的少女吉娜&middot;琳克(莎娜&middot;道兹威尔饰)已开始发育了。不过，吉娜远远不能满足，她一直梦想着自己成为真正魅力四射的性感女人。她希望吸引学校里那些帅哥的注意，可是他们似乎对她这个小女孩没有兴趣。<br />
	<br />
	　　吉娜平时最喜欢的，就是和她的好友、邻居家的男孩马特(马克&middot;鲁法罗饰)一起玩，她大胆的邀请他参加自己13岁的生日派对。在派对上，几个朋友们玩起了&ldquo;七分钟在天堂&rdquo;游戏，在吉娜藏进壁厨里时，她的朋友们却羞辱了她，于是她暗暗许下一个愿望，愿意以生命里的任何东西去换取自己立刻长大成人。第二天，吉娜从壁厨里走出来时，已是2004年，而她也长成了30岁的大姑娘(珍妮佛&middot;嘉纳饰)<br />
	<br />
	　　吉娜还惊讶的发现，她现在是个成功的事业女性，有一份非常棒的工作，住在好莱坞林阴路的豪华公寓里。她唯一的困惑是自己似乎没有身份，不知如何来到了这里。但新生活的魅力深深吸引了吉娜，她很快由惊讶变得迷上了现在的一切，只是感到似乎缺少了什么。<br />
	<br />
	　　当吉娜回过头来想了想，才发现她缺少的是&mdash;&mdash;马特&mdash;&mdash;13岁时爱慕的邻家男孩。为弥补新生活唯一的缺陷，吉娜想办法找到了马特，但马特此时已和别的女人结婚。吉娜感到一阵失望，她终于明白很多事情是无法完美的，现在她最想做的就是，回到自己的13岁，找回那场美妙青涩的初恋&hellip;&hellip;<br />
	<br />
	珍妮弗&middot;加纳的表演会牢牢吸引你的眼球。<br />
	<br />
	&mdash;&mdash;《达拉斯新闻早报》<br />
	<br />
	凭借《女孩梦三十》，珍妮弗&middot;加纳从电视动作偶像一跃成为魅力四射的成熟演员。<br />
	<br />
	&mdash;&mdash;《综艺》 </p>
<p>
	<br />
	<br />
	幕后制作<br />
	<br />
	　　当编剧凯斯&middot;尤斯帕(Cathy Yuspa)和乔什&middot;戈德史密斯(Josh Goldsmith)最初向制片人吉娜&middot;马修斯(Gina Matthews)提出《女孩梦三十》的想法时，马修斯就立即看中了两人的构思。&ldquo;凯斯和乔什总能将有趣的概念同深刻的主题结合到一起，当你和他们坐在一起时，总会听到欢闹搞笑的故事，而且对观众而言，这种故事显然很有吸引力。&rdquo;在本片之前，两位编剧就曾与马修斯合作过梅尔&middot;吉布森的《男人百分百》。<br />
	<br />
	　　在谈到影片主题时，马修斯说：&ldquo;这是一部有关选择的电影，会让我们想起在人生中做过的种种选择，这些选择总是很轻易便偏离轨迹。当你清晨醒来，扪心自问，你对自己的处境满意吗？影片讲述的正是如愿以偿和第二次选择的故事。&rdquo;<br />
	<br />
	　　《这个杀手将有难》和《美国甜心》的制片人唐娜&middot;罗斯(Donna Roth)和苏珊&middot;阿诺德(Susan Arnold)在看到剧本初稿时就深深喜欢上了故事的主人公吉娜。&ldquo;吉娜这个困惑的女子会让我们联想到自己，&rdquo;罗斯说，&ldquo;13岁是棘手的年龄，因为正处在人生选择的边缘，在这段时期，你既不是成人也不是孩子。&rdquo;<br />
	<br />
	　　作为曾与朱莉娅&middot;罗伯茨和桑德拉&middot;布洛克合作过的资深制片搭档，唐娜&middot;罗斯和苏珊&middot;阿诺德意识到吉娜应该由一位特别的女演员来扮演，这位演员必须集脆弱、勇敢和幽默于一身，她们物色到了凭《双面女间谍》赢得金球奖的珍妮弗&middot;加纳。<br />
	　　加纳本人非常高兴转换戏路，从身手矫健的女特工摇身一变成为稚气未脱的白领女孩。她说：&ldquo;我喜欢重返13岁，不过剧本最优秀的地方在于第二次机遇，不仅是爱情，还有同父母的关系，由此得以让生活发生转变。&rdquo;<br />
	<br />
	　　罗斯说：&ldquo;在《女孩梦三十》中，珍妮弗显现出了我们未曾发现的另一面，她很有喜剧天赋，和她相处一阵或者在电视访谈中，你都会发现她很风趣。&rdquo;<br />
	<br />
	　　确定了主演之后，制片人开始寻求适合本片的新锐导演，最终独立电影导演、曾凭2002年的《诱惑我小妈》荣获圣丹斯电影节最佳导演奖的盖瑞&middot;温尼克成为了执导本片的最佳人选。&ldquo;在《诱惑我小妈》之后，我接到了很多爱情喜剧的邀请，我之所以选择了《女孩梦三十》是因为这个故事的内涵丰富，&rdquo;温尼克说，&ldquo;当你得到曾经想要的一切时，却发现这一切并不能让你快乐，于是需要做出第二次选择，一次正确的选择，这就是影片的主题。&rdquo;另外，珍妮弗&middot;加纳的加盟也是温尼克选择本片的重要原因，而且加纳的表演完全超出了他的预期。<br />
	<br />
	　　为了能够将吉娜这个角色演绎得惟妙惟肖，詹妮弗&middot;加纳着实做了一番细致的调查。她开始接触13岁女孩，努力记住这个年龄段的特别之处。&ldquo;幸运的是，我有个好友玛德琳，当时12岁的她已经和我相识了5、6年，&rdquo;加纳说，&ldquo;她时常会像大人一样处事，这提醒着我她已经是个大孩子了。13岁的孩子就像小大人，但那是具有欺骗性的，他们脆弱敏感、容易激动而且稚气未脱，在这之间找到平衡正是我所面临的挑战。&rdquo;<br />
	<br />
	　　另外，加纳还要深入体会13岁的孩子如何进行沟通，她找到了两位制片人唐娜&middot;罗斯和苏珊&middot;阿诺德，要求两人出借她们的女儿汉娜和朱丽娅参加通宵派对。&ldquo;汉娜和朱丽娅请来了一些朋友，我们整晚都在一起，我尽可能的呆到最晚，我必须承认，并不是很晚。在凌晨4点，我睁开惺忪的睡眼，因为我觉得正是时候，当我拖着双腿来到厨房时，他们仍在聊天，我竭尽全力克服睡意，保持清醒，集中注意力。不过很不幸，我还是记不清都发生了什么，后来汉娜和朱丽娅告诉我，那天我蹒跚的走进来，吃了点东西，然后回去倒头便睡，那感觉就像又回到了13岁，&rdquo;加纳笑着说。<br />
	<br />
	　　尽管加纳努力和孩子们打成一片，但也有要划清界限的地方，特别是在睡觉的安排上，她不会像这些小家伙一样钻进睡袋，而是独占沙发，她会说：&ldquo;嗨，我已经30岁了，我年龄最大，所以我可以选择在沙发上睡。&rdquo;<br />
	<br />
	　　在影片中，幸运的少女吉娜梦想成真，她逾越了青春期的挑战，发现自己已经长大，可以享受成人的果实。在排练期间，影片的演员们齐聚一堂。共同分享成长的欢喜与快乐，他们都记得曾对前程充满恐惧，而且当时的逆反心理让他们一心向往独立，远离任何人的指手画脚，即使他们自知缺乏准备。加纳回忆说：&ldquo;那时候我参加了学校的军乐团，从未穿过时髦衣服，戴着大眼镜，我想长大，希望戴上隐形眼镜，真的很渴望交流。&rdquo;马克&middot;鲁弗洛说：&ldquo;那时和很多同龄人一样，我总是希望改变自己的身份和处境，现在，当我看着自己少年时期的照片时，我想当时还不赖。&rdquo;而对于朱迪&middot;格雷尔来说，那是段被焦虑所折磨的岁月，这种焦虑完全源自同龄人的压力，她说：&ldquo;那时我认为我找不到属于自己的地方，在那个年岁，会认为同俊男靓女搭帮结伙是很重要的事，然而当你长大之后，才会发现那些根本无关紧要。&rdquo;相比之下，安迪&middot;瑟金斯13岁时的梦想最简单，就是能一睹斯蒂芬&middot;斯皮尔伯格的《大白鲨》：&ldquo;当时我很愤怒，因为姐姐能看而我却不能，于是我借了双增高鞋，用姐姐的睫毛膏画上两撇小胡，竭力让自己看上去大一点，能够蒙混过关混进影院，可结果还是被挡在了门外。&rdquo;<br />
	<br />
	　　片中吉娜随着迈克尔&middot;杰克逊《Thriller》的强劲旋律倾情热舞的场景显然会勾起80年代的怀旧情结，当参加派对的人们陷入冷场之时，吉娜挺身而出，往昔的音乐和舞姿唤醒了众人，大家纷纷跟随着吉娜舞动起来。&ldquo;有一盘磁带伴随着我的成长，那就是《Thriller》，&rdquo;加纳说，&ldquo;所以排练和完成这段舞蹈是我最有趣的经历之一。&rdquo;格雷尔相当喜欢这段经历，她称赞舞蹈酷毙了，学舞的过程非常开心，陶醉其中的她还曾把脚扭伤了。鲁弗洛则对这段场景有些犯怵，他说：&ldquo;那时候我们这个年龄的每个人都在听《Thriller》，但我真的很紧张，因为我从不跳舞，我们必须接受训练。&rdquo;同鲁弗洛一样，瑟金斯也对舞蹈心存畏惧，他回忆说：&ldquo;我在伦敦接到电话，他们想要我走&lsquo;太空步&rsquo;，于是我请教了一位舞蹈教练。当我来到片场，发现排练第一天其他人就很熟练了，我害怕极了，生怕应付不来。&rdquo;<br />
	<br />
	　　可想而知，舞蹈的排练现场非常有感染力，以至制片人吉娜&middot;马修斯也情不自禁的加入舞动的人群，甚至还在摄影机前一展舞姿。&ldquo;和每个人一样，我对《Thriller》也很着迷，那时我会等到半夜去看ABC的首播，而且我录了下来，记得每个动作，当我们开始排练时，所有动作都重又出现在我的脑海中，&rdquo;马修斯说。<br />
	<br />
	<img onclick="if(this.width&gt;screen.width-461) window.open('http://img.album.pchome.net/54/68/59/08/52190a89ec5f6afc6a833271e5ada57b.jpg');" src="http://img.album.pchome.net/54/68/59/08/52190a89ec5f6afc6a833271e5ada57b.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 325px; border-top: 0px solid; border-right: 0px solid" />&nbsp;<br />
	<img onclick="if(this.width&gt;screen.width-461) window.open('http://img.album.pchome.net/54/68/59/08/e668f410055083081d4b80a1b5e3ef8a.jpg');" src="http://img.album.pchome.net/54/68/59/08/e668f410055083081d4b80a1b5e3ef8a.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 325px; border-top: 0px solid; border-right: 0px solid" /></p>
<p>
	近亿票房喜剧大片《三十姑娘一朵花》BD中英双字[880分辨率高清版] －来自[3E电影站 eee4.com]：<img border="0" src="http://www.eee4.com/templets/img/down.jpg" /></p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://e37:e37@xl2.eee4.com:9024/[3E电影站www.eee4.com]三十姑娘一朵花BD中英双字.rmvb" target="_blank">ftp://e37:e37@xl2.eee4.com:9024/[3E电影站www.eee4.com]三十姑娘一朵花BD中英双字.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3339/飘花电影piaohua.com女孩梦三十BD中英双字1024高清.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3339/飘花电影piaohua.com女孩梦三十BD中英双字1024高清.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3340/飘花电影piaohua.com女孩梦三十BD中英双字1280高清.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3340/飘花电影piaohua.com女孩梦三十BD中英双字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15V1F-34B2.jpg{/dede:field}
