{dede:field name='keywords'}第31届十大中文金曲颁奖音乐会迅{/dede:field}
{dede:field name='description'}第31届十大中文金曲颁奖音乐会迅雷下载、免费下载，第31届十大中文金曲颁奖音乐会Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}第31届十大中文金曲颁奖音乐会{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2009-01-28{/dede:field}
{dede:field name='body'}<P>第31屆十大中文金曲頒獎音樂會 TV-RMVB</P>
<P>【檔案大小】 : 655MB<BR>【影片格式】 : RMVB<BR>【發音語言】 : 粵語<BR>【字幕語言】 :中文字幕</P>
<P><IMG src="/uploads/allimg/c120524/133N42642E0-G113.jpg">&nbsp;<BR><IMG src="/uploads/allimg/c120524/133N42643L0-Y4Y.jpg">&nbsp;<BR><IMG src="/uploads/allimg/c120524/133N42644430-95560.jpg">&nbsp;<BR><IMG src="/uploads/allimg/c120524/133N42645060-105W7.jpg">&nbsp;<BR><IMG src="/uploads/allimg/c120524/133N42645H0-11FI.jpg"></P>
<DIV class=article_info>&nbsp;</DIV>
<DIV class=article_body id=article_body>
<CENTER>
<TABLE style="BORDER-RIGHT: #ffacac 2px solid; BORDER-TOP: #ffacac 2px solid; BORDER-LEFT: #ffacac 2px solid; BORDER-BOTTOM: #ffacac 2px solid; BORDER-COLLAPSE: collapse" cellSpacing=0 width=550 align=left>
<TBODY>
<TR bgColor=#fff5f0>
<TD style="BORDER-RIGHT: #ffacac 1px solid; BORDER-TOP: #ffacac 1px solid; BORDER-LEFT: #ffacac 1px solid; BORDER-BOTTOM: #ffacac 2px solid" colSpan=2>
<DIV style="BORDER-RIGHT: #fff5f0 1px solid; BORDER-TOP: #fff5f0 1px solid; BORDER-LEFT: #fff5f0 1px solid; BORDER-BOTTOM: #fff5f0 1px solid" align=left>&nbsp;&nbsp;&nbsp;&nbsp;第31届十大中文金曲颁奖音乐会于2009年1月18日晚上7时30分在香港仔运动场举行，出席歌手包括陈奕迅、容祖儿、谢安琪、张敬轩、阿Sa等。 <BR></DIV></TD></TR>
<TR bgColor=#fff5f0>
<TD style="BORDER-RIGHT: #ffacac 1px solid; BORDER-TOP: #ffacac 1px solid; BORDER-LEFT: #ffacac 1px solid; BORDER-BOTTOM: #ffacac 1px solid" colSpan=2>
<DIV style="BORDER-RIGHT: #fff5f0 1px solid; BORDER-TOP: #fff5f0 1px solid; BORDER-LEFT: #fff5f0 1px solid; BORDER-BOTTOM: #fff5f0 1px solid" align=center>获奖名单 </DIV></TD></TR>
<TR bgColor=#ffffff>
<TD style="BORDER-RIGHT: #ffacac 1px solid; BORDER-TOP: #ffacac 1px solid; BORDER-LEFT: #ffacac 1px solid; BORDER-BOTTOM: #ffacac 1px solid" height=40>
<DIV align=left><IMG style="BORDER-TOP-WIDTH: 0px; BORDER-LEFT-WIDTH: 0px; BORDER-BOTTOM-WIDTH: 0px; BORDER-RIGHT-WIDTH: 0px" alt=第31届十大中文金曲颁奖礼获奖名单 src="/uploads/allimg/c120524/133N4264BZ-12Oa.gif"> 金针奖<BR></DIV></TD>
<TD style="BORDER-RIGHT: #ffacac 1px solid; BORDER-TOP: #ffacac 1px solid; BORDER-LEFT: #ffacac 1px solid; WIDTH: 250px; BORDER-BOTTOM: #ffacac 1px solid">林夕&nbsp;</TD></TR>
<TR bgColor=#ffffff>
<TD style="BORDER-RIGHT: #ffacac 1px solid; BORDER-TOP: #ffacac 1px solid; BORDER-LEFT: #ffacac 1px solid; BORDER-BOTTOM: #ffacac 1px solid" height=40>
<DIV align=left><IMG style="BORDER-TOP-WIDTH: 0px; BORDER-LEFT-WIDTH: 0px; BORDER-BOTTOM-WIDTH: 0px; BORDER-RIGHT-WIDTH: 0px" alt=第31届十大中文金曲颁奖礼获奖名单 src="/uploads/allimg/c120524/133N4264BZ-12Oa.gif"> 全国最佳歌手奖(男歌手)</DIV></TD>
<TD style="BORDER-RIGHT: #ffacac 1px solid; BORDER-TOP: #ffacac 1px solid; BORDER-LEFT: #ffacac 1px solid; BORDER-BOTTOM: #ffacac 1px solid">&nbsp; 陈奕迅</TD></TR>
<TR bgColor=#ffffff>
<TD style="BORDER-RIGHT: #ffacac 1px solid; BORDER-TOP: #ffacac 1px solid; BORDER-LEFT: #ffacac 1px solid; BORDER-BOTTOM: #ffacac 1px solid" height=40>
<DIV align=left><IMG style="BORDER-TOP-WIDTH: 0px; BORDER-LEFT-WIDTH: 0px; BORDER-BOTTOM-WIDTH: 0px; BORDER-RIGHT-WIDTH: 0px" alt=第31届十大中文金曲颁奖礼获奖名单 src="/uploads/allimg/c120524/133N4264BZ-12Oa.gif"> 全国最佳歌手奖(女歌手)</DIV></TD>
<TD style="BORDER-RIGHT: #ffacac 1px solid; BORDER-TOP: #ffacac 1px solid; BORDER-LEFT: #ffacac 1px solid; BORDER-BOTTOM: #ffacac 1px solid">&nbsp; 容祖儿</TD></TR>
<TR bgColor=#ffffff>
<TD style="BORDER-RIGHT: #ffacac 1px solid; BORDER-TOP: #ffacac 1px solid; BORDER-LEFT: #ffacac 1px solid; BORDER-BOTTOM: #ffacac 1px solid" height=40>
<DIV align=left><IMG style="BORDER-TOP-WIDTH: 0px; BORDER-LEFT-WIDTH: 0px; BORDER-BOTTOM-WIDTH: 0px; BORDER-RIGHT-WIDTH: 0px" alt=第31届十大中文金曲颁奖礼获奖名单 src="/uploads/allimg/c120524/133N4264BZ-12Oa.gif"> 全国最佳歌手奖(组合)</DIV></TD>
<TD style="BORDER-RIGHT: #ffacac 1px solid; BORDER-TOP: #ffacac 1px solid; BORDER-LEFT: #ffacac 1px solid; BORDER-BOTTOM: #ffacac 1px solid">&nbsp;S.H.E</TD></TR>
<TR bgColor=#ffffff>
<TD style="BORDER-RIGHT: #ffacac 1px solid; BORDER-TOP: #ffacac 1px solid; BORDER-LEFT: #ffacac 1px solid; BORDER-BOTTOM: #ffacac 1px solid" height=40>
<DIV align=left><IMG style="BORDER-TOP-WIDTH: 0px; BORDER-LEFT-WIDTH: 0px; BORDER-BOTTOM-WIDTH: 0px; BORDER-RIGHT-WIDTH: 0px" alt=第31届十大中文金曲颁奖礼获奖名单 src="/uploads/allimg/c120524/133N4264BZ-12Oa.gif"> 最有前途新人奖(金奖)</DIV></TD>
<TD style="BORDER-RIGHT: #ffacac 1px solid; BORDER-TOP: #ffacac 1px solid; BORDER-LEFT: #ffacac 1px solid; BORDER-BOTTOM: #ffacac 1px solid">陈伟霆&nbsp;</TD></TR>
<TR bgColor=#ffffff>
<TD style="BORDER-RIGHT: #ffacac 1px solid; BORDER-TOP: #ffacac 1px solid; BORDER-LEFT: #ffacac 1px solid; BORDER-BOTTOM: #ffacac 1px solid" height=40>
<DIV align=left><IMG style="BORDER-TOP-WIDTH: 0px; BORDER-LEFT-WIDTH: 0px; BORDER-BOTTOM-WIDTH: 0px; BORDER-RIGHT-WIDTH: 0px" alt=第31届十大中文金曲颁奖礼获奖名单 src="/uploads/allimg/c120524/133N4264BZ-12Oa.gif"> 最有前途新人奖(银奖)</DIV></TD>
<TD style="BORDER-RIGHT: #ffacac 1px solid; BORDER-TOP: #ffacac 1px solid; BORDER-LEFT: #ffacac 1px solid; BORDER-BOTTOM: #ffacac 1px solid">g.e.m </TD></TR>
<TR bgColor=#ffffff>
<TD style="BORDER-RIGHT: #ffacac 1px solid; BORDER-TOP: #ffacac 1px solid; BORDER-LEFT: #ffacac 1px solid; BORDER-BOTTOM: #ffacac 1px solid" height=40>
<DIV align=left><IMG style="BORDER-TOP-WIDTH: 0px; BORDER-LEFT-WIDTH: 0px; BORDER-BOTTOM-WIDTH: 0px; BORDER-RIGHT-WIDTH: 0px" alt=第31届十大中文金曲颁奖礼获奖名单 src="/uploads/allimg/c120524/133N4264BZ-12Oa.gif"> 最有前途新人奖(铜奖)</DIV></TD>
<TD style="BORDER-RIGHT: #ffacac 1px solid; BORDER-TOP: #ffacac 1px solid; BORDER-LEFT: #ffacac 1px solid; BORDER-BOTTOM: #ffacac 1px solid">王祖藍</TD></TR>
<TR bgColor=#ffffff>
<TD style="BORDER-RIGHT: #ffacac 1px solid; BORDER-TOP: #ffacac 1px solid; BORDER-LEFT: #ffacac 1px solid; BORDER-BOTTOM: #ffacac 1px solid" height=40>
<DIV align=left><IMG style="BORDER-TOP-WIDTH: 0px; BORDER-LEFT-WIDTH: 0px; BORDER-BOTTOM-WIDTH: 0px; BORDER-RIGHT-WIDTH: 0px" alt=第31届十大中文金曲颁奖礼获奖名单 src="/uploads/allimg/c120524/133N4264BZ-12Oa.gif"> 最有前途新人奖(优异奖)</DIV></TD>
<TD style="BORDER-RIGHT: #ffacac 1px solid; BORDER-TOP: #ffacac 1px solid; BORDER-LEFT: #ffacac 1px solid; BORDER-BOTTOM: #ffacac 1px solid">钟嘉欣、胡杏儿、萧敬腾 </TD></TR>
<TR bgColor=#ffffff>
<TD style="BORDER-RIGHT: #ffacac 1px solid; BORDER-TOP: #ffacac 1px solid; BORDER-LEFT: #ffacac 1px solid; BORDER-BOTTOM: #ffacac 1px solid" height=40>
<DIV align=left><IMG style="BORDER-TOP-WIDTH: 0px; BORDER-LEFT-WIDTH: 0px; BORDER-BOTTOM-WIDTH: 0px; BORDER-RIGHT-WIDTH: 0px" alt=第31届十大中文金曲颁奖礼获奖名单 src="/uploads/allimg/c120524/133N4264BZ-12Oa.gif"> 全国最佳中文歌曲奖</DIV></TD>
<TD style="BORDER-RIGHT: #ffacac 1px solid; BORDER-TOP: #ffacac 1px solid; BORDER-LEFT: #ffacac 1px solid; BORDER-BOTTOM: #ffacac 1px solid">林俊杰、阿sa《小酒窩》&nbsp;</TD></TR>
<TR bgColor=#ffffff>
<TD style="BORDER-RIGHT: #ffacac 1px solid; BORDER-TOP: #ffacac 1px solid; BORDER-LEFT: #ffacac 1px solid; BORDER-BOTTOM: #ffacac 1px solid" height=40>
<DIV align=left><IMG style="BORDER-TOP-WIDTH: 0px; BORDER-LEFT-WIDTH: 0px; BORDER-BOTTOM-WIDTH: 0px; BORDER-RIGHT-WIDTH: 0px" alt=第31届十大中文金曲颁奖礼获奖名单 src="/uploads/allimg/c120524/133N4264BZ-12Oa.gif">&nbsp;优秀流行歌手大奖</DIV></TD>
<TD style="BORDER-RIGHT: #ffacac 1px solid; BORDER-TOP: #ffacac 1px solid; BORDER-LEFT: #ffacac 1px solid; BORDER-BOTTOM: #ffacac 1px solid">李克勤、杨千嬅、王菀之、古巨基、陈奕迅、<BR>容祖儿、刘德华、侧田、谢安琪、张敬轩</TD></TR>
<TR bgColor=#ffffff>
<TD style="BORDER-RIGHT: #ffacac 1px solid; BORDER-TOP: #ffacac 1px solid; BORDER-LEFT: #ffacac 1px solid; BORDER-BOTTOM: #ffacac 1px solid" height=40>
<DIV align=left><IMG style="BORDER-TOP-WIDTH: 0px; BORDER-LEFT-WIDTH: 0px; BORDER-BOTTOM-WIDTH: 0px; BORDER-RIGHT-WIDTH: 0px" alt=第31届十大中文金曲颁奖礼获奖名单 src="/uploads/allimg/c120524/133N4264BZ-12Oa.gif"> 全年最高銷量男歌手大奖</DIV></TD>
<TD style="BORDER-RIGHT: #ffacac 1px solid; BORDER-TOP: #ffacac 1px solid; BORDER-LEFT: #ffacac 1px solid; BORDER-BOTTOM: #ffacac 1px solid">陈奕迅</TD></TR>
<TR bgColor=#ffffff>
<TD style="BORDER-RIGHT: #ffacac 1px solid; BORDER-TOP: #ffacac 1px solid; BORDER-LEFT: #ffacac 1px solid; BORDER-BOTTOM: #ffacac 1px solid" height=40>
<DIV align=left><IMG style="BORDER-TOP-WIDTH: 0px; BORDER-LEFT-WIDTH: 0px; BORDER-BOTTOM-WIDTH: 0px; BORDER-RIGHT-WIDTH: 0px" alt=第31届十大中文金曲颁奖礼获奖名单 src="/uploads/allimg/c120524/133N4264BZ-12Oa.gif">&nbsp;全年最高銷量女歌手大奖</DIV></TD>
<TD style="BORDER-RIGHT: #ffacac 1px solid; BORDER-TOP: #ffacac 1px solid; BORDER-LEFT: #ffacac 1px solid; BORDER-BOTTOM: #ffacac 1px solid">容祖儿</TD></TR>
<TR bgColor=#ffffff>
<TD style="BORDER-RIGHT: #ffacac 1px solid; BORDER-TOP: #ffacac 1px solid; BORDER-LEFT: #ffacac 1px solid; BORDER-BOTTOM: #ffacac 1px solid" height=40>
<DIV align=left><IMG style="BORDER-TOP-WIDTH: 0px; BORDER-LEFT-WIDTH: 0px; BORDER-BOTTOM-WIDTH: 0px; BORDER-RIGHT-WIDTH: 0px" alt=第31届十大中文金曲颁奖礼获奖名单 src="/uploads/allimg/c120524/133N4264BZ-12Oa.gif">&nbsp;全年最高銷量组合大奖</DIV></TD>
<TD style="BORDER-RIGHT: #ffacac 1px solid; BORDER-TOP: #ffacac 1px solid; BORDER-LEFT: #ffacac 1px solid; BORDER-BOTTOM: #ffacac 1px solid">飞轮海</TD></TR>
<TR bgColor=#ffffff>
<TD style="BORDER-RIGHT: #ffacac 1px solid; BORDER-TOP: #ffacac 1px solid; BORDER-LEFT: #ffacac 1px solid; BORDER-BOTTOM: #ffacac 1px solid" height=40>
<DIV align=left><IMG style="BORDER-TOP-WIDTH: 0px; BORDER-LEFT-WIDTH: 0px; BORDER-BOTTOM-WIDTH: 0px; BORDER-RIGHT-WIDTH: 0px" alt=第31届十大中文金曲颁奖礼获奖名单 src="/uploads/allimg/c120524/133N4264BZ-12Oa.gif"> 全年最佳进步奖</DIV></TD>
<TD style="BORDER-RIGHT: #ffacac 1px solid; BORDER-TOP: #ffacac 1px solid; BORDER-LEFT: #ffacac 1px solid; BORDER-BOTTOM: #ffacac 1px solid">E02&nbsp;</TD></TR>
<TR bgColor=#ffffff>
<TD style="BORDER-RIGHT: #ffacac 1px solid; BORDER-TOP: #ffacac 1px solid; BORDER-LEFT: #ffacac 1px solid; BORDER-BOTTOM: #ffacac 1px solid" height=40>
<DIV align=left><IMG style="BORDER-TOP-WIDTH: 0px; BORDER-LEFT-WIDTH: 0px; BORDER-BOTTOM-WIDTH: 0px; BORDER-RIGHT-WIDTH: 0px" alt=第31届十大中文金曲颁奖礼获奖名单 src="/uploads/allimg/c120524/133N4264BZ-12Oa.gif">&nbsp;十大中文金曲</DIV></TD>
<TD style="BORDER-RIGHT: #ffacac 1px solid; BORDER-TOP: #ffacac 1px solid; BORDER-LEFT: #ffacac 1px solid; BORDER-BOTTOM: #ffacac 1px solid">容祖儿《陪我长大》&nbsp;</TD></TR>
<TR bgColor=#ffffff>
<TD style="BORDER-RIGHT: #ffacac 1px solid; BORDER-TOP: #ffacac 1px solid; BORDER-LEFT: #ffacac 1px solid; BORDER-BOTTOM: #ffacac 1px solid" height=40>
<DIV align=left><IMG style="BORDER-TOP-WIDTH: 0px; BORDER-LEFT-WIDTH: 0px; BORDER-BOTTOM-WIDTH: 0px; BORDER-RIGHT-WIDTH: 0px" alt=第31届十大中文金曲颁奖礼获奖名单 src="/uploads/allimg/c120524/133N4264BZ-12Oa.gif">&nbsp;</DIV></TD>
<TD style="BORDER-RIGHT: #ffacac 1px solid; BORDER-TOP: #ffacac 1px solid; BORDER-LEFT: #ffacac 1px solid; BORDER-BOTTOM: #ffacac 1px solid">谢安琪《囍帖街》</TD></TR>
<TR bgColor=#ffffff>
<TD style="BORDER-RIGHT: #ffacac 1px solid; BORDER-TOP: #ffacac 1px solid; BORDER-LEFT: #ffacac 1px solid; BORDER-BOTTOM: #ffacac 1px solid" height=40>
<DIV align=left><IMG style="BORDER-TOP-WIDTH: 0px; BORDER-LEFT-WIDTH: 0px; BORDER-BOTTOM-WIDTH: 0px; BORDER-RIGHT-WIDTH: 0px" alt=第31届十大中文金曲颁奖礼获奖名单 src="/uploads/allimg/c120524/133N4264BZ-12Oa.gif">&nbsp;</DIV></TD>
<TD style="BORDER-RIGHT: #ffacac 1px solid; BORDER-TOP: #ffacac 1px solid; BORDER-LEFT: #ffacac 1px solid; BORDER-BOTTOM: #ffacac 1px solid">郑融周柏豪《一事无成》&nbsp;</TD></TR>
<TR bgColor=#ffffff>
<TD style="BORDER-RIGHT: #ffacac 1px solid; BORDER-TOP: #ffacac 1px solid; BORDER-LEFT: #ffacac 1px solid; BORDER-BOTTOM: #ffacac 1px solid" height=40>
<DIV align=left><IMG style="BORDER-TOP-WIDTH: 0px; BORDER-LEFT-WIDTH: 0px; BORDER-BOTTOM-WIDTH: 0px; BORDER-RIGHT-WIDTH: 0px" alt=第31届十大中文金曲颁奖礼获奖名单 src="/uploads/allimg/c120524/133N4264BZ-12Oa.gif">&nbsp;</DIV></TD>
<TD style="BORDER-RIGHT: #ffacac 1px solid; BORDER-TOP: #ffacac 1px solid; BORDER-LEFT: #ffacac 1px solid; BORDER-BOTTOM: #ffacac 1px solid">杨千嬅《捞月亮的人》&nbsp;</TD></TR>
<TR bgColor=#ffffff>
<TD style="BORDER-RIGHT: #ffacac 1px solid; BORDER-TOP: #ffacac 1px solid; BORDER-LEFT: #ffacac 1px solid; BORDER-BOTTOM: #ffacac 1px solid" height=40>
<DIV align=left><IMG style="BORDER-TOP-WIDTH: 0px; BORDER-LEFT-WIDTH: 0px; BORDER-BOTTOM-WIDTH: 0px; BORDER-RIGHT-WIDTH: 0px" alt=第31届十大中文金曲颁奖礼获奖名单 src="/uploads/allimg/c120524/133N4264BZ-12Oa.gif">&nbsp;</DIV></TD>
<TD style="BORDER-RIGHT: #ffacac 1px solid; BORDER-TOP: #ffacac 1px solid; BORDER-LEFT: #ffacac 1px solid; BORDER-BOTTOM: #ffacac 1px solid">陈柏宇《i miss you》&nbsp;</TD></TR>
<TR bgColor=#ffffff>
<TD style="BORDER-RIGHT: #ffacac 1px solid; BORDER-TOP: #ffacac 1px solid; BORDER-LEFT: #ffacac 1px solid; BORDER-BOTTOM: #ffacac 1px solid" height=40>
<DIV align=left><IMG style="BORDER-TOP-WIDTH: 0px; BORDER-LEFT-WIDTH: 0px; BORDER-BOTTOM-WIDTH: 0px; BORDER-RIGHT-WIDTH: 0px" alt=第31届十大中文金曲颁奖礼获奖名单 src="/uploads/allimg/c120524/133N4264BZ-12Oa.gif">&nbsp;</DIV></TD>
<TD style="BORDER-RIGHT: #ffacac 1px solid; BORDER-TOP: #ffacac 1px solid; BORDER-LEFT: #ffacac 1px solid; BORDER-BOTTOM: #ffacac 1px solid">农夫《全民皆估》&nbsp;</TD></TR>
<TR bgColor=#ffffff>
<TD style="BORDER-RIGHT: #ffacac 1px solid; BORDER-TOP: #ffacac 1px solid; BORDER-LEFT: #ffacac 1px solid; BORDER-BOTTOM: #ffacac 1px solid" height=40>
<DIV align=left><IMG style="BORDER-TOP-WIDTH: 0px; BORDER-LEFT-WIDTH: 0px; BORDER-BOTTOM-WIDTH: 0px; BORDER-RIGHT-WIDTH: 0px" alt=第31届十大中文金曲颁奖礼获奖名单 src="/uploads/allimg/c120524/133N4264BZ-12Oa.gif">&nbsp;</DIV></TD>
<TD style="BORDER-RIGHT: #ffacac 1px solid; BORDER-TOP: #ffacac 1px solid; BORDER-LEFT: #ffacac 1px solid; BORDER-BOTTOM: #ffacac 1px solid">张敬轩《樱花树下》&nbsp;</TD></TR>
<TR bgColor=#ffffff>
<TD style="BORDER-RIGHT: #ffacac 1px solid; BORDER-TOP: #ffacac 1px solid; BORDER-LEFT: #ffacac 1px solid; BORDER-BOTTOM: #ffacac 1px solid" height=40>
<DIV align=left><IMG style="BORDER-TOP-WIDTH: 0px; BORDER-LEFT-WIDTH: 0px; BORDER-BOTTOM-WIDTH: 0px; BORDER-RIGHT-WIDTH: 0px" alt=第31届十大中文金曲颁奖礼获奖名单 src="/uploads/allimg/c120524/133N4264BZ-12Oa.gif">&nbsp;</DIV></TD>
<TD style="BORDER-RIGHT: #ffacac 1px solid; BORDER-TOP: #ffacac 1px solid; BORDER-LEFT: #ffacac 1px solid; BORDER-BOTTOM: #ffacac 1px solid">林峰《爱不疚》&nbsp;</TD></TR>
<TR bgColor=#ffffff>
<TD style="BORDER-RIGHT: #ffacac 1px solid; BORDER-TOP: #ffacac 1px solid; BORDER-LEFT: #ffacac 1px solid; BORDER-BOTTOM: #ffacac 1px solid" height=40>
<DIV align=left><IMG style="BORDER-TOP-WIDTH: 0px; BORDER-LEFT-WIDTH: 0px; BORDER-BOTTOM-WIDTH: 0px; BORDER-RIGHT-WIDTH: 0px" alt=第31届十大中文金曲颁奖礼获奖名单 src="/uploads/allimg/c120524/133N4264BZ-12Oa.gif">&nbsp;</DIV></TD>
<TD style="BORDER-RIGHT: #ffacac 1px solid; BORDER-TOP: #ffacac 1px solid; BORDER-LEFT: #ffacac 1px solid; BORDER-BOTTOM: #ffacac 1px solid">吳雨霏《分手要狠》&nbsp;</TD></TR>
<TR bgColor=#ffffff>
<TD style="BORDER-RIGHT: #ffacac 1px solid; BORDER-TOP: #ffacac 1px solid; BORDER-LEFT: #ffacac 1px solid; BORDER-BOTTOM: #ffacac 1px solid" height=40>
<DIV align=left><IMG style="BORDER-TOP-WIDTH: 0px; BORDER-LEFT-WIDTH: 0px; BORDER-BOTTOM-WIDTH: 0px; BORDER-RIGHT-WIDTH: 0px" alt=第31届十大中文金曲颁奖礼获奖名单 src="/uploads/allimg/c120524/133N4264BZ-12Oa.gif">&nbsp;</DIV></TD>
<TD style="BORDER-RIGHT: #ffacac 1px solid; BORDER-TOP: #ffacac 1px solid; BORDER-LEFT: #ffacac 1px solid; BORDER-BOTTOM: #ffacac 1px solid">古巨基《眼睛不能沒眼泪》&nbsp;</TD></TR>
<TR bgColor=#ffffff>
<TD style="BORDER-RIGHT: #ffacac 1px solid; BORDER-TOP: #ffacac 1px solid; BORDER-LEFT: #ffacac 1px solid; BORDER-BOTTOM: #ffacac 1px solid" height=40>
<DIV align=left><IMG style="BORDER-TOP-WIDTH: 0px; BORDER-LEFT-WIDTH: 0px; BORDER-BOTTOM-WIDTH: 0px; BORDER-RIGHT-WIDTH: 0px" alt=第31届十大中文金曲颁奖礼获奖名单 src="/uploads/allimg/c120524/133N4264BZ-12Oa.gif">&nbsp;优秀流行国语歌曲</DIV></TD>
<TD style="BORDER-RIGHT: #ffacac 1px solid; BORDER-TOP: #ffacac 1px solid; BORDER-LEFT: #ffacac 1px solid; BORDER-BOTTOM: #ffacac 1px solid">泳儿《喜欢一个人好累》&nbsp;</TD></TR>
<TR bgColor=#ffffff>
<TD style="BORDER-RIGHT: #ffacac 1px solid; BORDER-TOP: #ffacac 1px solid; BORDER-LEFT: #ffacac 1px solid; BORDER-BOTTOM: #ffacac 1px solid" height=40>
<DIV align=left><IMG style="BORDER-TOP-WIDTH: 0px; BORDER-LEFT-WIDTH: 0px; BORDER-BOTTOM-WIDTH: 0px; BORDER-RIGHT-WIDTH: 0px" alt=第31届十大中文金曲颁奖礼获奖名单 src="/uploads/allimg/c120524/133N4264BZ-12Oa.gif">&nbsp;</DIV></TD>
<TD style="BORDER-RIGHT: #ffacac 1px solid; BORDER-TOP: #ffacac 1px solid; BORDER-LEFT: #ffacac 1px solid; BORDER-BOTTOM: #ffacac 1px solid">陈奕迅《路...一直都在》</TD></TR>
<TR bgColor=#ffffff>
<TD style="BORDER-RIGHT: #ffacac 1px solid; BORDER-TOP: #ffacac 1px solid; BORDER-LEFT: #ffacac 1px solid; BORDER-BOTTOM: #ffacac 1px solid" height=40>
<DIV align=left><IMG style="BORDER-TOP-WIDTH: 0px; BORDER-LEFT-WIDTH: 0px; BORDER-BOTTOM-WIDTH: 0px; BORDER-RIGHT-WIDTH: 0px" alt=第31届十大中文金曲颁奖礼获奖名单 src="/uploads/allimg/c120524/133N4264BZ-12Oa.gif">&nbsp;最佳创作歌手奖</DIV></TD>
<TD style="BORDER-RIGHT: #ffacac 1px solid; BORDER-TOP: #ffacac 1px solid; BORDER-LEFT: #ffacac 1px solid; BORDER-BOTTOM: #ffacac 1px solid">方大同</TD></TR>
<TR bgColor=#ffffff>
<TD style="BORDER-RIGHT: #ffacac 1px solid; BORDER-TOP: #ffacac 1px solid; BORDER-LEFT: #ffacac 1px solid; BORDER-BOTTOM: #ffacac 1px solid" height=40>
<DIV align=left><IMG style="BORDER-TOP-WIDTH: 0px; BORDER-LEFT-WIDTH: 0px; BORDER-BOTTOM-WIDTH: 0px; BORDER-RIGHT-WIDTH: 0px" alt=第31届十大中文金曲颁奖礼获奖名单 src="/uploads/allimg/c120524/133N4264BZ-12Oa.gif">&nbsp;全球华语至尊金曲奖</DIV></TD>
<TD style="BORDER-RIGHT: #ffacac 1px solid; BORDER-TOP: #ffacac 1px solid; BORDER-LEFT: #ffacac 1px solid; BORDER-BOTTOM: #ffacac 1px solid">谢安琪《喜帖街》</TD></TR>
<TR bgColor=#ffffff>
<TD style="BORDER-RIGHT: #ffacac 1px solid; BORDER-TOP: #ffacac 1px solid; BORDER-LEFT: #ffacac 1px solid; BORDER-BOTTOM: #ffacac 1px solid" height=40>
<DIV align=left><IMG style="BORDER-TOP-WIDTH: 0px; BORDER-LEFT-WIDTH: 0px; BORDER-BOTTOM-WIDTH: 0px; BORDER-RIGHT-WIDTH: 0px" alt=第31届十大中文金曲颁奖礼获奖名单 src="/uploads/allimg/c120524/133N4264BZ-12Oa.gif">&nbsp;最优秀流行男歌手</DIV></TD>
<TD style="BORDER-RIGHT: #ffacac 1px solid; BORDER-TOP: #ffacac 1px solid; BORDER-LEFT: #ffacac 1px solid; BORDER-BOTTOM: #ffacac 1px solid">陈奕迅</TD></TR>
<TR bgColor=#ffffff>
<TD style="BORDER-RIGHT: #ffacac 1px solid; BORDER-TOP: #ffacac 1px solid; BORDER-LEFT: #ffacac 1px solid; BORDER-BOTTOM: #ffacac 1px solid" height=40>
<DIV align=left><IMG style="BORDER-TOP-WIDTH: 0px; BORDER-LEFT-WIDTH: 0px; BORDER-BOTTOM-WIDTH: 0px; BORDER-RIGHT-WIDTH: 0px" alt=第31届十大中文金曲颁奖礼获奖名单 src="/uploads/allimg/c120524/133N4264BZ-12Oa.gif">&nbsp;最优秀流行女歌手</DIV></TD>
<TD style="BORDER-RIGHT: #ffacac 1px solid; BORDER-TOP: #ffacac 1px solid; BORDER-LEFT: #ffacac 1px solid; BORDER-BOTTOM: #ffacac 1px solid">容祖儿</TD></TR>
<TR bgColor=#ffffff>
<TD style="BORDER-RIGHT: #ffacac 1px solid; BORDER-TOP: #ffacac 1px solid; BORDER-LEFT: #ffacac 1px solid; BORDER-BOTTOM: #ffacac 1px solid" height=40>
<DIV align=left><IMG style="BORDER-TOP-WIDTH: 0px; BORDER-LEFT-WIDTH: 0px; BORDER-BOTTOM-WIDTH: 0px; BORDER-RIGHT-WIDTH: 0px" alt=第31届十大中文金曲颁奖礼获奖名单 src="/uploads/allimg/c120524/133N4264BZ-12Oa.gif">&nbsp;四台联播传媒大奖 传媒大奖</DIV></TD>
<TD style="BORDER-RIGHT: #ffacac 1px solid; BORDER-TOP: #ffacac 1px solid; BORDER-LEFT: #ffacac 1px solid; BORDER-BOTTOM: #ffacac 1px solid">谢安琪《喜帖街》</TD></TR></TBODY></TABLE></CENTER></DIV><BR>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>2009-01-27 14:32:12 开始连接......<BR>2009-01-27 14:32:12 开始搜索候选资源......<BR>2009-01-27 14:32:12 搜索到22个候选资源<BR>2009-01-27 14:32:12 使用候选资源进行连接......<BR>2009-01-27 14:32:13 搜索到41个候选资源<BR>2009-01-27 14:32:13 使用候选资源进行连接......<BR>2009-01-27 14:32:13 文件创建成功，开始下载数据......<BR>2009-01-27 14:32:16 用户取消下载&nbsp;&nbsp; 本文来自：www.eee4.com</P>（一律使用迅雷下载）<BR>第31届十大中文金曲颁奖音乐会 －来自[3E电影站 eee4.com]：<IMG src="http://www.eee4.com/templets/img/down.jpg" border=0><BR>
<TABLE style="BORDER-RIGHT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; BORDER-BOTTOM: #cccccc 1px dotted" cellSpacing=0 cellPadding=6 width="95%" align=center border=0>
<TBODY>
<TR>
<TD style="WORD-WRAP: break-word" bgColor=#fdfddf>ftp://e30:e30@xl2.eee4.com:9916/[3E电影站www.eee4.com]第31届十大中文金曲颁奖礼.rmvb</TD></TR></TBODY></TABLE>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120524/133N4264IF-1492C.jpg{/dede:field}
