{dede:field name='keywords'}重案组[BD国语+粤语中字1024x576{/dede:field}
{dede:field name='description'}重案组[BD国语+粤语中字1024x576高清版]迅雷下载、免费下载，重案组[BD国语+粤语中字1024x576高清版]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}重案组[BD国语+粤语中字1024x576高清版]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-03-21{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://3e:3e@d3.3edyy.com:121/【3E电影院www.eee4.org】重案组.1024x548.国粤双语.中文字幕.mkv" target=_blank>ftftp://3e:3e@d3.3edyy.com:121/【3E电影院www.eee4.org】重案组.1024x548.国粤双语.中文字幕.mkv</A></TD></TR></TBODY></TABLE></div><ul class="mmlist{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MQ3M540-1E50.jpg{/dede:field}
