<?php
$z[0]=Array("field","我仍在这里：杰昆·菲尼克斯不为",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","我仍在这里：杰昆·菲尼克斯不为人知的岁月[DVD中英双字]迅雷下载、免费下载，我仍在这里：杰昆·菲尼克斯不为人知的岁月[DVD中英双字]Gvod高清在线播放，剧情介绍等。",73,273);
$z[1][4]['name']="description";
$z[2]=Array("field","我仍在这里：杰昆·菲尼克斯不为人知的岁月[DVD中英双字]",275,366);
$z[2][4]['name']="title";
$z[3]=Array("field","",368,407);
$z[3][4]['name']="writer";
$z[4]=Array("field","",409,448);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-01-16",450,500);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",502,539);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://4e:4e@m1.3edyy.com:1579/【3E看看www.3ekk.com】我仍在这里[DVD中英双字].rmvb\" target=_blank>ftftp://4e:4e@m1.3edyy.com:1579/【3E看看www.3ekk.com】我仍在这里[DVD中英双字].rmvb</A></TD></TR></TBODY></TABLE></div><ul class=\"mmlist",541,811);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MQ45S20-33E2.jpg",813,895);
$z[8][4]['name']="litpic";

?>