{dede:field name='keywords'}雨夜花港台剧7迅雷下载，免费下{/dede:field}
{dede:field name='description'}雨夜花港台剧7迅雷下载、免费下载，雨夜花港台剧7Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}雨夜花港台剧7{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-20{/dede:field}
{dede:field name='body'}<p>
	<img src="http://img.funshion.com/attachment/new_images/2012/04-12/18881305_1334213490_287.jpg" /></p>
<p>
	演员：</p>
<p>
	黄品源 / 张本渝 / 孙淑媚 / 林昕阳</p>
<p>
	&bull;类型：爱情<br />
	&bull;首映：2012年4月6日 中国台湾</p>
<p>
	&bull;点评： 好男人黄品源演绎黑道马仔,为梦想出卖女友初夜-<br />
	&bull; 剧情： 「雨夜花」是台湾民谣之父邓雨贤于民国23年所创作，内容描述一名纯朴的乡下女孩为追求爱情沦落风尘的悲惨故事，本剧取名「雨夜花」，正由于剧中女主角王贵珠（张本瑜饰演）和柳月桂（孙淑媚饰演），有着和歌曲中女子相同的境遇，两个女人本应互相惜花，偏偏却爱上同一个男人NOBU大仔（黄品源饰演）。这一段女人何苦为难女人的故事，也扭转了地方角头...</p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.netftp//dy44:piaohua@dy44.piaohua.com:3125/" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3221/飘花电影piaohua.com雨夜花1.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3221/飘花电影piaohua.com雨夜花1.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3221/飘花电影piaohua.com雨夜花2.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3221/飘花电影piaohua.com雨夜花2.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3266/飘花电影piaohua.com雨夜花3.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3266/飘花电影piaohua.com雨夜花3.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3314/飘花电影piaohua.com雨夜花4.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3314/飘花电影piaohua.com雨夜花4.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3356/飘花电影piaohua.com雨夜花5.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3356/飘花电影piaohua.com雨夜花5.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3402/飘花电影piaohua.com雨夜花6.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3402/飘花电影piaohua.com雨夜花6.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3464/飘花电影piaohua.com雨夜花7.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3464/飘花电影piaohua.com雨夜花7.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1A62550-42316.jpg{/dede:field}
