{dede:field name='keywords'}不义之财BD1280高清迅雷下载，免{/dede:field}
{dede:field name='description'}不义之财BD1280高清迅雷下载、免费下载，不义之财BD1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}不义之财BD1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-04-23{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://images.weltrecords.de/img/cover/000/001/089/000001089809.jpg" style="width: 700px; height: 985px" /></p>
<p>
	◎译　　名　不义之财<br />
	◎片　　名　Snabba Cash<br />
	◎导　　演　丹尼尔&middot;伊斯皮诺萨 Daniel Espinosa<br />
	◎主　　演　乔尔&middot;金纳曼 Joel Kinnaman ... Johan &#39;JW&#39; Westlund<br />
	　　　　　　丽莎&middot;亨尼 Lisa Henni ... Sophie<br />
	　　　　　　法瑞斯&middot;法瑞斯 Fares Fares ... Mahmoud<br />
	　　　　　　Matias Padin ... Jorge<br />
	　　　　　　Dragomir Mrsic ... Mrado<br />
	　　　　　　Mahmut Suvakci ... Abdulkarim<br />
	　　　　　　Jones Danko ... Fahdi<br />
	　　　　　　Lea Stojanov ... Lovisa<br />
	◎年　　代　2010<br />
	◎国　　家　瑞典<br />
	◎类　　别　罪案/剧情/惊悚<br />
	◎IMDB评分 &nbsp;6.6/10 &nbsp; (4,058 votes)<br />
	◎IMDB链接 &nbsp;<a href="http://www.imdb.com/title/tt1291652" target="_blank">http://www.imdb.com/title/tt1291652</a><br />
	◎对白语言　瑞典语<br />
	◎片　　长　124 mins<br />
	<br />
	<br />
	<br />
	<b>◎简　　介　</b><br />
	<br />
	&nbsp; &nbsp; &nbsp;讲述三个生活在斯德哥尔摩的边缘人物：一个从小就从智利移民到瑞典从事毒品买卖，在斯德哥尔摩市没有人比他更有人脉，另一个人则过着双重的生活，一边跟有钱有势的朋友交往一边贩卖毒品，还有一个是南斯拉夫帮派下的得力助手，主要是帮帮派老大收取俱乐部跟酒吧的保护费。当这些人从事毒品买卖或犯罪行为的过程中，因为钱太容易赚到，即使想过要回去那领着实在薪水平凡过活，可能社会无法接受他们，又或者那容易钱诱惑太大，结果往往总是又回到以前犯罪生活。<br />
	<br />
	&nbsp; &nbsp; &nbsp;剧情是典型的黑帮电影，瑞典小帅哥为了跻身上流社会而为黑帮分子卖命，白天上学读书、晚上挣黑道的钱过纸醉金迷的生活。渐行渐远的理想与正义的路让他迷失了自己，直到他全盘托出最新一笔交易的时间、地点给了一位杀手，终于迎来了自我救赎的结局。<br />
	&nbsp;<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120423/02/62564813201204230227262326198313193_002.jpg" style="width: 660px; height: 371px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120423/02/62564813201204230227262326198313193_001.jpg" style="width: 660px; height: 371px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120423/02/62564813201204230227262326198313193_000.jpg" style="width: 660px; height: 371px" /></p>
<p>
	【下载地址】</p>
<table bgcolor="#0099cc" border="0" cellpadding="10" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.net" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy125:piaohua@dy125.piaohua.com:7879/飘花电影piaohua.com不义之财BD中字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:7879/飘花电影piaohua.com不义之财BD中字1280高清.rmvb</a></td>
		</tr>
		<tr>
		</tr>
	</tbody>
</table>
<br />{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15631U0-593P.jpg{/dede:field}
