<?php
$z[0]=Array("field","冒牌天神2BD中英双字1024/1280高",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","冒牌天神2BD中英双字1024/1280高清经典喜剧迅雷下载、免费下载，冒牌天神2BD中英双字1024/1280高清经典喜剧Gvod高清在线播放，剧情介绍等。",73,247);
$z[1][4]['name']="description";
$z[2]=Array("field","冒牌天神2BD中英双字1024/1280高清经典喜剧",249,327);
$z[2][4]['name']="title";
$z[3]=Array("field","",329,368);
$z[3][4]['name']="writer";
$z[4]=Array("field","",370,409);
$z[4][4]['name']="source";
$z[5]=Array("field","2012-01-17",411,461);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",463,500);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://eee4.com:8033@vip10.eee4.com:8033/冒牌天神2/[3E迅雷电影站www.eee4.com]冒牌天神2-CD1.rmvb\" target=\"_blank",502,651);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MOV3O0-24438.jpg",653,735);
$z[8][4]['name']="litpic";

?>