<?php
$z[0]=Array("field","西北偏北/谍影疑云/北西北/夺魄",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","西北偏北/谍影疑云/北西北/夺魄惊魂[BD中英双字1280x720高清版]迅雷下载、免费下载，西北偏北/谍影疑云/北西北/夺魄惊魂[BD中英双字1280x720高清版]Gvod高清在线播放，剧情介绍等。",72,284);
$z[1][4]['name']="description";
$z[2]=Array("field","西北偏北/谍影疑云/北西北/夺魄惊魂[BD中英双字1280x720高清版]",286,383);
$z[2][4]['name']="title";
$z[3]=Array("field","",385,424);
$z[3][4]['name']="writer";
$z[4]=Array("field","",426,465);
$z[4][4]['name']="source";
$z[5]=Array("field","2009-11-16",467,517);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",519,556);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://4e:4e@xl.eee4.com:331/[3E电影站www.eee4.cn]西北偏北BD中英双字1280x720高清版.rmvb\" target=\"_blank",558,699);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MQ31O10-11527.jpg",701,784);
$z[8][4]['name']="litpic";

?>