<?php
$z[0]=Array("field","奥巴马胜选演说DVD中英字幕完整",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","奥巴马胜选演说DVD中英字幕完整版迅雷下载、免费下载，奥巴马胜选演说DVD中英字幕完整版Gvod高清在线播放，剧情介绍等。",72,228);
$z[1][4]['name']="description";
$z[2]=Array("field","奥巴马胜选演说DVD中英字幕完整版",230,299);
$z[2][4]['name']="title";
$z[3]=Array("field","",301,340);
$z[3][4]['name']="writer";
$z[4]=Array("field","",342,381);
$z[4][4]['name']="source";
$z[5]=Array("field","2008-11-07",383,433);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",435,472);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://e69:e69@xl3.eee4.com:1004/[3E电影站www.eee4.com]奥巴马胜选演说(完整版)中英双语字幕.rmvb\" target=\"_blank",474,622);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MP455950-1c27.jpg",624,707);
$z[8][4]['name']="litpic";

?>