{dede:field name='keywords'}奥巴马胜选演说DVD中英字幕完整{/dede:field}
{dede:field name='description'}奥巴马胜选演说DVD中英字幕完整版迅雷下载、免费下载，奥巴马胜选演说DVD中英字幕完整版Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}奥巴马胜选演说DVD中英字幕完整版{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2008-11-07{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://e69:e69@xl3.eee4.com:1004/[3E电影站www.eee4.com]奥巴马胜选演说(完整版)中英双语字幕.rmvb" target="_blank{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MP455950-1c27.jpg{/dede:field}
