{dede:field name='keywords'}精装追女仔III狼之一族BD1280高{/dede:field}
{dede:field name='description'}精装追女仔III狼之一族BD1280高清粤语迅雷下载、免费下载，精装追女仔III狼之一族BD1280高清粤语Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}精装追女仔III狼之一族BD1280高清粤语{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-23{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120523/22/17870980201205232231171684095110331_008.jpg" /></p>
<p>
	◎译　　名　精装追女仔III 狼之一族<br />
	◎片　　名　The Romancing Star 3<br />
	◎年　　代　1989<br />
	◎国　　家　中国香港<br />
	◎类　　别　喜剧<br />
	◎语　　言　国粤双语<br />
	◎字　　幕　中文<br />
	<br />
	◎导　　演　王晶 Jing Wong<br />
	◎主　　演　刘德华 Andy Lau<br />
	　　　　　　冯淬帆 Shui-Fan Fung<br />
	　　　　　　黄霑 James Wong<br />
	　　　　　　王晶 Jing Wong<br />
	　　　　　　张敏 Sharla Cheung<br />
	　　　　　　郑丹瑞 Lawrence Cheng<br />
	　　　　　　邱淑贞 Chingmy Yau<br />
	　　　　　　成奎安 Fui-On Shing<br />
	　　　　　　周慧敏 Vivian Chow<br />
	　　　　　　Sam Christopher Chow<br />
	　　　　　　<br />
	<br />
	◎简　　介　<br />
	<br />
	　　两车房老板坚及沾因旧仇及私利互相斗气。坚之4名猛男伙计与沾之4名美女帮手，在互斗中发生爱意。其后两伙人更成为好朋友互助脱离移民公司的谋财卖猪仔骗局&hellip;&hellip;<br />
	<br />
	　　八十年代的新艺城喜剧开始，港片便在这个题材上乐此不疲。在首集中难得的是具有影帝影后级演技的周润发和张曼玉，演出这种电影时也高高兴兴地与众同乐，同样表现出职业水准，故事亦是典型的旧酒，修车厂小弟在槟城邂逅美容中心的小妹，双方都要面子，一个假扮富可敌国的名流公子，另一个则伪装名门望族的千金小姐，双方周旋了一阵之后拆穿了西洋镜，引来连串爱情风波。在美人美景和轻松笑料的包装下，本片颇能满足凡夫俗子的浮华梦，在同类作品中算是相当好看的。第二集则以刘德华、陈百祥为主打，剧情也相差无几。<br />
	<br />
	　　早在邵氏电影公司时期，王晶便以《花心大少》、《青蛙王子》开始经营他的&ldquo;沟女片 &rdquo;。尽管王晶并非&ldquo;沟女片&rdquo;的开创者，却是最成功者，《精装追女仔》系列便是明证。在王晶的&ldquo;沟女片&rdquo;中，被追的女仔不是重要的，只当是个花瓶。沟女的男人才是绝对主角。至于&ldquo;沟女片&rdquo;中充满世俗智慧的市井男性形象（以刘德华、陈百祥为代表）亦是王晶时装商业片中几乎所有男主角的共同特征。他们总处于麻烦的中心，时常被整蛊得逼入绝境，却总能以妙计（桥段）化险为夷，最后抱得美人归&mdash;&mdash;这类情节充分满足了市民阶层观众的通俗心理。而对于女孩子来说，看男人用各种浪漫有趣的手段讨女孩的欢心，心情也自然贴得多。<br />
	<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120523/22/17870980201205232231171684095110331_005.jpg" /><br />
	<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120523/22/17870980201205232231171684095110331_003.jpg" /><br />
	<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120523/22/17870980201205232231171684095110331_002.jpg" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaobajie.com" target="_blank">http://www.xiaobajie.com</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy241:piaohua@117.41.229.29:2035/飘花电影piaohua.com精装追女仔III狼之一族BD1280高清粤语.rmvb">ftp://dy241:piaohua@117.41.229.29:2035/飘花电影piaohua.com精装追女仔III狼之一族BD1280高清粤语.rmvb</a></td>
		</tr>
	</tbody>
</table>
<p>
	&nbsp;</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15O0L0-51C0.jpg{/dede:field}
