<?php
$z[0]=Array("field","宗教的荒谬[DVD中字无水印]迅雷",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","宗教的荒谬[DVD中字无水印]迅雷下载、免费下载，宗教的荒谬[DVD中字无水印]Gvod高清在线播放，剧情介绍等。",72,216);
$z[1][4]['name']="description";
$z[2]=Array("field","宗教的荒谬[DVD中字无水印]",218,281);
$z[2][4]['name']="title";
$z[3]=Array("field","",283,322);
$z[3][4]['name']="writer";
$z[4]=Array("field","",324,363);
$z[4][4]['name']="source";
$z[5]=Array("field","2012-05-22",365,415);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",417,454);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://e53:e53@xl2.eee4.com:9024/[3E电影站www.eee4.com]宗教的荒谬.rmvb\" target=\"_blank",456,580);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MP4G20-1BF.jpg",582,662);
$z[8][4]['name']="litpic";

?>