{dede:field name='keywords'}恋恋凡花BD1280高清中字迅雷下载{/dede:field}
{dede:field name='description'}恋恋凡花BD1280高清中字迅雷下载、免费下载，恋恋凡花BD1280高清中字Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}恋恋凡花BD1280高清中字{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-09{/dede:field}
{dede:field name='body'}<p>
	　　<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120508/23/17870980201205082310021573325782264_009.jpg" style="width: 640px; height: 711px" /></p>
<p>
	　　片名：恋恋凡花<br />
	<br />
	　　英文名：Flowers<br />
	<br />
	　　导演：小泉德宏<br />
	<br />
	　　主演：苍井优、铃木京香、竹内结子、田中丽奈、仲间由纪惠、广末凉子<br />
	<br />
	　　上映日期：2010年6月12日<br />
	<br />
	　　发行时间：2011年4月8日<br />
	<br />
	　　影片长度：110分钟<br />
	<br />
	　　分级：PG12（日本）<br />
	<br />
	剧情介绍　　影片讲述有着血缘关系的三代六位普通日本女性的爱情生活，生活在1936年春天的凛渴望自由恋爱但又生活在父母的传统婚姻家庭里，试图追寻自己的幸福又饱受压力，婚后的三个女儿在六七十年代时又分别的谈婚论嫁，大女儿与深爱的人结婚却又遭遇了意外，二女儿试图平衡爱情与事业的关系但又矛盾重重，而三女儿遇上相爱的人生了两个女儿奏与佳，二十多年后奏与佳又遭遇了不同的爱情或事业&hellip;&hellip;<br />
	<br />
	相关影评　　影片就像是一幅横跨七十年的日本浮世绘，导演通过人物的造型、故事、人物与人物之间的关系（如苍井优扮演的凛那一段，折射出当时日本的男尊女卑的现象，而田中丽奈扮演的翠，则通过她的遭遇表现六十年代末时日本女性虽然可以走上社会有自己的事业但不时的遭到男性的歧视眼光）、日常生活的道具（电视机与电视里播放的节目）等，再加上影片里的春夏秋冬的四季流转变化，以非常自然、诗意的方式展示出来。</p>
<p>
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120509/23/17870980201205092352001356404195203_003.jpg" style="width: 640px; height: 360px" /></p>
<p>
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120509/23/17870980201205092352001356404195203_001.jpg" style="width: 640px; height: 360px" /></p>
<p>
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120509/23/17870980201205092352001356404195203_000.jpg" /><br />
	<br />
	&nbsp;</p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.net" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy241:piaohua@117.41.229.29:2011/飘花电影piaohua.com恋恋凡花BD1280高清中字.rmvb">ftp://dy241:piaohua@117.41.229.29:2011/飘花电影piaohua.com恋恋凡花BD1280高清中字.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O159D4P-33344.jpg{/dede:field}
