{dede:field name='keywords'}提姆和艾瑞克的十亿美元大电影BD{/dede:field}
{dede:field name='description'}提姆和艾瑞克的十亿美元大电影BD中字1024高清2012喜剧迅雷下载、免费下载，提姆和艾瑞克的十亿美元大电影BD中字1024高清2012喜剧Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}提姆和艾瑞克的十亿美元大电影BD中字1024高清2012喜剧{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-04-30{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://apollo.s.dpool.sina.com.cn/nd/dataent/moviepic/pics/145/moviepic_ce2f6696b2da7fd5d311e99a3ae552df.jpg" /></p>

<p>
	◎译　　名　提姆和艾瑞克的十亿美元大电影<br />
	◎片　　名　Tim and Erics Billion Dollar Movie<br />
	◎年　　代　2012<br />
	◎国　　家　美国<br />
	◎类　　别　喜剧<br />
	◎语　　言　英语<br />
	◎字　　幕　中文<br />
	◎IMDB评分&nbsp; 5.4/10 from 2,431 users<br />
	◎文件格式　高清1024版BD-RMVB<br />
	◎视频尺寸　1024 x 576<br />
	◎文件大小　1CD 594MB<br />
	◎片　　长　133 Mins<br />
	◎导　　演　Tim Heidecker<br />
	　　　　　　Eric Wareheim<br />
	◎主　　演　Eric Wareheim<br />
	　　　　　　Tim Heidecker<br />
	　　　　　　约翰&middot;C&middot;赖利 John C. Reilly&nbsp; ....Taquito<br />
	　　　　　　威尔&middot;法瑞尔 Will Ferrell<br />
	　　　　　　扎克&middot;加利费安纳基斯 Zach Galifianakis&nbsp; ....Jim Joe Kelly<br />
	　　　　　　杰夫&middot;高布伦 Jeff Goldblum<br />
	　　　　　　埃莉卡&middot;杜兰斯 Erica Durance&nbsp; ....French waitress<br />
	　　　　　　罗伯特&middot;劳吉亚 Robert Loggia<br />
	　　　　　　威尔&middot;福特 Will Forte&nbsp; ....Allen Bishopman<br />
	　　　　　　雷&middot;怀斯 Ray Wise&nbsp; ....(rumored)<br />
	　　　　　　科斯塔斯&middot;曼迪勒 Costas Mandylor<br />
	　　　　　　威廉&middot;阿瑟东 William Atherton<br />
	　　　　　　吐温克&middot;卡潘 Twink Caplan&nbsp; ....Katie<br />
	　　　　　　米切尔&middot;格罗斯 Michael Gross&nbsp; ....Narrator<br />
	　　　　　　A.D. Miles&nbsp; ....(rumored)<br />
	　　　　　　马克&middot;库班 Mark Cuban<br />
	　　　　　　Jean-Michel Richaud&nbsp; ....Marc<br />
	　　　　　　Nancy Stelmaszczyk&nbsp; ....Paris Woman<br />
	　　　　　　Ron Lynch&nbsp; ....(rumored)<br />
	　　　　　　Michael Q. Schmidt&nbsp; ....(rumored)<br />
	　　　　　　Dita de Leon&nbsp; ....Cocaine girl<br />
	　　　　　　Matt O&#39;Toole&nbsp; ....Reggie<br />
	　　　　　　Bob Ross&nbsp; ....(rumored)<br />
	　　　　　　James Quall&nbsp; ....(rumored)<br />
	　　　　　　Ron Stark&nbsp; ....(rumored)<br />
	　　　　　　托德&middot;瓦格纳 Todd Wagner<br />
	　　　　　　David Hart&nbsp; ....(rumored) (as David Liebehart)<br />
	　　　　　　Calvin Dean&nbsp; ....French Solicitor Reynolds<br />
	　　　　　　Doug Lussenhop&nbsp; ....(rumored)<br />
	　　　　　　Palmer Scott&nbsp; ....(rumored)<br />
	　　　　　　Kazu Nagahama&nbsp; ....(rumored)<br />
	　　　　　　Frank Slaten&nbsp; ....Popcorn Seat Guy<br />
	　　　　　　Ron Austar&nbsp; ....(rumored)<br />
	　　　　　　Tanese Gray&nbsp; ....(rumored)<br />
	　　　　　　Ronnie Rodriguez&nbsp; ....Diamond Jim<br />
	　　　　　　Warren Stearns&nbsp; ....(rumored)<br />
	　　　　　　Azmyth Kaminski&nbsp; ....Dreadlocks<br />
	　　　　　　Christopher Guckenberger&nbsp; ....Demetris<br />
	　　　　　　Bob Druwing&nbsp; ....(rumored)<br />
	　　　　　　Chuck Spitler&nbsp; ....(rumored)<br />
	　　　　　　Sire&nbsp; ....(rumored)<br />
	　　　　　　Carol Kraft&nbsp; ....(rumored)<br />
	　　　　　　Noah Spencer&nbsp; ....Jeffery<br />
	　　　　　　Doug Foster&nbsp; ....(rumored)<br />
	　　　　　　Kirk Diedrich&nbsp; ....Scary Man (uncredited)<br />
	　　　　　　John Downey III&nbsp; ....Cornell (uncredited)<br />
	　　　　　　Kimberly Ables Jindra&nbsp; ....Birthing Woman (uncredited)<br />
	　　　　　　Mobin Khan&nbsp; ....Rudy (uncredited)<br />
	　　　　　　Patricia Olivia Nangkal&nbsp; ....Cocaine Girl #1 (uncredited)<br />
	　　　　　　Samuel Proof&nbsp; ....Raz (uncredited)<br />
	　　　　　　Howie Slater&nbsp; ....Steven Spielberg (uncredited)<br />
	　　　　　　Andy Spencer&nbsp; ....Schlaaang Executive (uncredited)<br />
	　　　　　　Jesse Woodrow&nbsp; ....Vespa Scooter Driver (uncredited)</p>
<p>
	◎简　　介　</p>
<p>
	　　美国喜剧界有Tim Heidecker和Eric Wareheim这两位不大不小的明星，在《提姆和埃里克精彩秀，伟大的工作（Tim and Eric Awesome Show, Great Job!）》之后，二位打起了更大的算盘，于是就有个这部名字更气派的新片&mdash;&mdash;《提姆和艾瑞克的十亿美元大电影》。</p>
<p>
	　　影片故事讲述两个男人如何在一部电影上花掉十亿美元，并号称请来约翰&middot;C&middot;赖利、扎克&middot;加利费安纳基斯、威尔&middot;法瑞尔、威尔&middot;福特等等一干喜剧明星联合主演。</p>
<p>
	&nbsp;&nbsp;&nbsp; 喜剧谐星Tim Heidecker与Eric Wareheim联手出击，一干喜剧明星也热情捧场客串。故事讲述两个男人如何在一部电影上能耗费十亿美元，恶搞指数破表！</p>
<p>
	&nbsp;&nbsp;&nbsp; 两个家伙得到一亿美元拍电影，却只能看着自己的梦想越走越偏....&quot; Tim和Eric的十亿美元的电影&ldquo;是一部由Heidecker和埃里克Wareheim制作的明星云集的喜剧，剧中将出现众多名人客串，扮演观众喜闻乐见的普通角色。</p>
<p>

	◎影片截图</p>

	<img alt="" height="394" src="http://img170.poco.cn/mypoco/myphoto/20120429/11/56643687201204291132191259561294114_000.jpg" width="700" /></p>
<p>
	<img alt="" height="394" src="http://img170.poco.cn/mypoco/myphoto/20120429/11/56643687201204291132191259561294114_003.jpg" width="700" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.netftp://dy44:piaohua@dy44.piaohua.com:3187/" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3318/飘花电影piaohua.com提姆和艾瑞克的十亿美元大电影BD中字1024高清.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3318/飘花电影piaohua.com提姆和艾瑞克的十亿美元大电影BD中字1024高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15H6130-163a.jpg{/dede:field}
