{dede:field name='keywords'}大雄的发条都市冒险记DVD国语中{/dede:field}
{dede:field name='description'}大雄的发条都市冒险记DVD国语中字哆啦A梦剧场版迅雷下载、免费下载，大雄的发条都市冒险记DVD国语中字哆啦A梦剧场版Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}大雄的发条都市冒险记DVD国语中字哆啦A梦剧场版{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-08-21{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="/uploads/allimg/c120525/133O04N0U0-1450J.jpg" /></p>
<p>
	【内容介绍】<br />
	<br />
	　　哆啦A梦去未来世界时得到一些小行星奖券，因大雄报错奖券号码，他们无意中来到了一个天堂般的星球。大家开心地把各自的玩具都拿到那个星球上，并用生命之匙赋予了它们生命。玩具们就在那个星球上建造了自己的城市&mdash;&mdash;发条都市。此时，凶恶的罪犯熊虎鬼五郎逃入大雄的房间，无意间通过任意门也来到了发条都市，并用玩具们的复制装置复制了自己，企图占领发条都市。一场正义与邪恶的较量由此展开了！&hellip;&hellip;<br />
	　　这是藤子不二雄在96年就构思的作品，不过未完成便去世了，这部大长篇可说是他的大长篇遗作。这也是个「让玩具变成有生命」的故事，有点类似白金迷宫的感决。饰演反派的鬼五郎有很多分身，在故事中扮演非常好笑，如丑角般的角色，让整部大长篇更有趣。<br />
	<img alt="" src="/uploads/allimg/c120525/133O04N1110-15W64.jpg" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="/uploads/allimg/c120524/133N2Z4FF-102231.jpg" />&nbsp;&nbsp;&nbsp;
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				&nbsp;ftp://dy44:piaohua@dy44.piaohua.com:1360/飘花电影piaohua.com大雄的发条都市冒险记DVD国语中字.rmvb</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O04N1V0-1E056.jpg{/dede:field}
