{dede:field name='keywords'}怪形/突变第三型[DVD中英双字128{/dede:field}
{dede:field name='description'}怪形/突变第三型[DVD中英双字1280x720高清版]迅雷下载、免费下载，怪形/突变第三型[DVD中英双字1280x720高清版]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}怪形/突变第三型[DVD中英双字1280x720高清版]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-11-27{/dede:field}
{dede:field name='body'}<p>
	◎译　　名　《怪形/突变第三型》美国经典R级科幻惊栗大片DVD中英双字1280x720高清版<br />
	◎片　　名　The Thing<br />
	◎年　　代　1982<br />
	◎国　　家　美国<br />
	◎类　　别　恐怖/神秘/科幻/惊悚<br />
	◎语　　言　英语<br />
	◎字　　幕　中英双字<br />
	◎IMDB评分&nbsp; 8.1/10&nbsp; 57,581 votes<br />
	◎文件格式　BD-RMVB<br />
	◎视频尺寸　1280x720<br />
	◎文件大小　1CD<br />
	◎片　　长　109MiN<br />
	◎导　　演　约翰&middot;卡彭特 John Carpenter<br />
	◎主　　演　库特&middot;拉塞尔 Kurt Russell&nbsp; ....&nbsp; R.J. MacReady<br />
	　　　　　　威尔福德&middot;布雷姆利 Wilford Brimley&nbsp; ....&nbsp; Dr. Blair (as A. Wilford Brimley)<br />
	　　　　　　T&middot;K&middot;卡特 T.K. Carter&nbsp; ....&nbsp; Nauls<br />
	　　　　　　大卫&middot;克莱隆 David Clennon&nbsp; ....&nbsp; Palmer<br />
	　　　　　　基思&middot;大卫 Keith David&nbsp; ....&nbsp; Childs<br />
	　　　　　　理查德&middot;A&middot;戴萨特 Richard A. Dysart&nbsp; ....&nbsp; Dr. Copper (as Richard Dysart)<br />
	　　　　　　查尔斯&middot;霍拉汉 Charles Hallahan&nbsp; ....&nbsp; Vance Norris<br />
	　　　　　　彼得&middot;马隆尼 Peter Maloney&nbsp; ....&nbsp; George Bennings<br />
	　　　　　　理查德&middot;马舒尔 Richard Masur&nbsp; ....&nbsp; Clark<br />
	　　　　　　唐纳德&middot;莫法特 Donald Moffat&nbsp; ....&nbsp; Garry<br />
	　　　　　　乔伊&middot;波利斯 Joel Polis&nbsp; ....&nbsp; Fuchs<br />
	　　　　　　Thomas G. Waites&nbsp; ....&nbsp; Windows (as Thomas Waites)<br />
	　　　　　　Norbert Weisser&nbsp; ....&nbsp; Norwegian<br />
	　　　　　　Larry J. Franco&nbsp; ....&nbsp; Norwegian Passenger with Rifle (as Larry Franco)<br />
	　　　　　　Nate Irwin&nbsp; ....&nbsp; Helicopter Pilot<br />
	<br />
	◎简　　介　<br />
	<br />
	&nbsp; &nbsp; 一群美国科学探险队征到南极地，途中遇到挪威人正在追捕一只爱斯基摩犬，他们对这怪异的围捕行动感到好奇；当天晚上，几个队员和狗儿们遭受那爱斯基摩犬的突击，其他的队员才警觉有不明物体附身在同行的伙伴身上，只是没有人分辨的出谁是正常的...<br />
	<br />
	&nbsp; &nbsp; 库特&middot;拉塞尔在片中扮演一名前往南极探险的美国科学家，他发现研究站的全体人员离奇死亡，经化验后证明被不明来历的异物袭击，乃设法用火攻来对付这些外星异物...</p>
<p>
	<img alt="" border="0" onload="attachimg(this, 'load')" src="http://img.album.pchome.net/54/68/40/56/2a408d9ec33f727e2161b9731e23965e.jpg" /></p>
<p>
	【电影截图】：<br />
	电影来源：www.eee4.com</p>
<p>
	<a href="http://img.album.pchome.net/54/68/40/56/dc508851a6622d9d34e7e91694d13855.jpg" target="_blank"><img src="http://img.album.pchome.net/54/68/40/56/dc508851a6622d9d34e7e91694d13855.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 338px; border-top: 0px solid; border-right: 0px solid" /></a>&nbsp;<br />
	<a href="http://img.album.pchome.net/54/68/40/56/48bcac53c622f111695f1fe9ffcceac4.jpg" target="_blank"><img src="http://img.album.pchome.net/54/68/40/56/48bcac53c622f111695f1fe9ffcceac4.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 338px; border-top: 0px solid; border-right: 0px solid" /></a></p>
	美国经典R级科幻惊栗大片《突变第三型》DVD中英双字1280x720高清版 </p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://e21:e21@xl2.eee4.com:9916/[3E电影站www.eee4.com]突变第三型[DVD中英双字1280x720高清版].rmvb" target="_blank">ftp://e21:e21@xl2.eee4.com:9916/[3E电影站www.eee4.com]突变第三型[DVD中英双字1280x720高清版].rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2192/飘花电影piaohua.com突变第三型中英双字1280高清.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2192/飘花电影piaohua.com突变第三型中英双字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>
	&nbsp;</p>
	美国经典R级科幻惊栗大片《突变第三型》DVD中英双字【880分辨率版】 </p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<anchor></anchor><a href="ftp://e21:e21@xl2.eee4.com:9916/[3E电影站www.eee4.com]突变第三型DVD中英双字CD1.rmvb" target="_blank">ftp://e21:e21@xl2.eee4.com:9916/[3E电影站www.eee4.com]突变第三型DVD中英双字CD1.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<anchor></anchor><a href="ftp://e21:e21@xl2.eee4.com:9916/[3E电影站www.eee4.com]突变第三型DVD中英双字CD2.rmvb" target="_blank">ftp://e21:e21@xl2.eee4.com:9916/[3E电影站www.eee4.com]突变第三型DVD中英双字CD2.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O160415F-45Y7.jpg{/dede:field}
