{dede:field name='keywords'}合法入侵/湖景水坝/湖边的梯田10{/dede:field}
{dede:field name='description'}合法入侵/湖景水坝/湖边的梯田1024/1280高清版迅雷下载、免费下载，合法入侵/湖景水坝/湖边的梯田1024/1280高清版Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}合法入侵/湖景水坝/湖边的梯田1024/1280高清版{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-05{/dede:field}
{dede:field name='body'}<p>
	&nbsp;<img alt="" border="0" height="838" onclick="if(this.width&gt;screen.width-461) window.open('http://i0.sinaimg.cn/ent/d/2008-09-17/U105P28T3D2172525F326DT20080917162347.jpg');" src="http://i0.sinaimg.cn/ent/d/2008-09-17/U105P28T3D2172525F326DT20080917162347.jpg" width="541" /></p>
<p>
	◎译　　名　《湖景水坝/湖边的梯田/合法入侵》08年塞缪尔杰克逊惊悚剧情片BD中英双字800分辨率＋1024x576高清版<br />
	◎片　　名　Lakeview Terrace<br />
	◎年　　代　2008<br />
	◎国　　家　美国<br />
	◎类　　别　剧情/惊悚<br />
	◎语　　言　英语<br />
	◎字　　幕　中英文<br />
	◎IMDB评分 6.4/10 4,616 votes<br />
	◎IMDB链接 http://www.imdb.com/title/tt0947802<br />
	◎文件格式　Bluray-RMVB<br />
	◎视频尺寸　1024 x 576 、800x336 1280&times;720<br />
	◎文件大小　1CD<br />
	◎片　　长　01:50:27<br />
	◎导　　演　尼尔&middot;拉布特 Neil LaBute<br />
	◎主　　演　塞缪尔&middot;杰克逊 Samuel L. Jackson....Abel Turner<br />
	　　　　　　帕特里克&middot;威尔森 Patrick Wilson....Chris Mattson<br />
	　　　　　　凯丽&middot;华盛顿 Kerry Washington....Lisa Mattson<br />
	　　　　　　罗恩&middot;格拉斯 Ron Glass....Harold Perreau<br />
	　　　　　　贾斯汀&middot;钱伯斯 Justin Chambers....Donnie Eaton<br />
	　　　　　　杰伊&middot;赫尔南德兹 Jay Hernandez....Javier Villareal<br />
	　　　　　　Regine Nehy ....Celia Turner<br />
	　　　　　　Jaishon Fisher ....Marcus Turner<br />
	　　　　　　罗伯特&middot;派恩 Robert Pine....Captain Wentworth<br />
	　　　　　　Keith Loneker ....Clarence Darlington<br />
	　　　　　　Caleeb Pinkett ....Damon Richards<br />
	　　　　　　Robert Dahey ....Jung Lee Pak<br />
	　　　　　　Ho-Jung ....Sang Hee Pak<br />
	<br />
	◎简　　介　<br />
	<br />
	剧情<br />
	<br />
	当迈特森夫妇（帕特里克&middot;威尔森、凯莉&middot;华盛顿饰）移居到他们梦想的家园&ldquo;湖景水坝&rdquo;时。因为他们两人是不同种族间的婚姻，被他们的隔壁邻居亚伯&middot;特纳给&ldquo;盯&rdquo;上了。亚伯&middot;特纳（塞缪尔&middot;杰克逊饰）是一位洛杉矶警局的警官，一位严厉、刻板的单身父亲。他自诩为小区的保护者，却因为痛恨跨种族的婚姻，而对新搬迁至此的新邻居怀有敌意，并想方设法地想要逼走他们。也许他整晚的巡逻和过分的监视行为会让一些人感到安全感，但对这对新婚夫妇来说，他持续的&ldquo;越界&rdquo;行为、对他们无止境的骚扰越来越令他们难以忍受，甚至成了他们生活中的一大灾难，并最终使这对年轻的夫妻走上了回击之路。</p>

<p>
	&nbsp;<br />
	<br />
	<br />
	一句话评论<br />
	<br />
	《湖景水坝》紧张的节奏和引人入胜的故事情节打破了惊悚片的惯用形式，塞缪尔&middot;杰克逊摇身变为惊悚的源头&mdash;&mdash;人们都不愿意接近的&ldquo;邻居&rdquo;。<br />
	<br />
	&mdash;&mdash;《综艺》<br />
	<br />
	幕后制作<br />
	<br />
	<br />
	　　种族主义与惊悚真相的&ldquo;较劲&rdquo;<br />
	<br />
	　　《湖景水坝》这部惊悚片将时常容易混淆的法律问题和种族身份问题置于一个更加显著的境地&mdash;&mdash;一部看似带有种族主义问题的影片里的主角拥有着黑色的肤色。塞缪尔&middot;杰克逊相信，在这部分级为PG－13的电影里，种族问题将会将这部片子置于评论风暴的中心，因为种族问题会伴随社会的发展而延续下去，&ldquo;正如人们在票选奥巴马时那样，尽管他们或许已经给他投了一票，但是嘴上依然会说因为他的肤色问题而不会给他投票。&rdquo;这位影片<a href="http://www.eee4.cn/" target="_blank">电影下载</a>中的男一号说道，&ldquo;也许你拒绝谈论种族问题，但这个问题存在于每个人的脑子里。&rdquo;<br />
	<br />
	　　影片在宣传的预告片和海报里并没有给&ldquo;种族主义&rdquo;问题以任何篇幅，倒是大肆地宣传了片里的各位好莱坞演员和赫赫有名的明星导演&mdash;&mdash;尼尔&middot;拉布特。&ldquo;其实在预告片里能看到跨种族婚姻的影子，只是我们没有以此为噱头来宣传这部影片，当然也没必要提醒潜在的观众群体注意这件事情。&rdquo;尼尔&middot;拉布特解释道。<br />
	<br />
	　　&ldquo;我相信所有的人在看过这部影片之后就会知道是什么使亚伯&middot;特纳变成一个厌恨跨种族婚姻的人，同时也会明白为什么他会成为一个严厉的单身爸爸。&rdquo;　塞缪尔&middot;杰克逊说道。当塞缪尔第一次拿到这部影片的剧本时，&ldquo;我感觉这部影片更应该归属于&lsquo;限制级（R级）&rsquo;&hellip;&hellip;只要导演尼尔与编剧一起谈剧本，他们俩就会将更多的政治性和角色的符号化意义注入其中，并使其显得很突出。在拍摄过程中，只要尼尔觉得不够味儿，就会随时喊停，他不会将这部电影拍成&lsquo;为了震撼效果而任意将疯狂的素材杂糅在一起的影片&rsquo;，是的，他绝不会是那样的导演。&rdquo;　塞缪尔&middot;杰克逊说道。<br />
	<br />
	　　拉布特认为坏人并不一定是黑人，&ldquo;我们也曾经考虑过让汤米&middot;李&middot;琼斯或者爱德华&middot;詹姆斯&middot;奥莫斯出演这个角色，但我们的想法和常年处理这些案件以及阅人无数的洛杉矶警察的建议出现分歧，当我们再联想到什么人会对一对不同肤色的夫妇产生如此强烈的反应时，我们便有了自己的决定。&rdquo;<br />
	<br />
	　　&ldquo;这是一部现代恐怖电影，而恐怖的来源在于给你制造恐惧感、每天都不放过你的并不是拿着电锯在森林里疯狂追寻你的电锯狂人，而是时时刻刻在你旁边为你提供安全防护的的人－－警察。&rdquo;拉布特如是说，&ldquo;这部片子吸引你们的地方应该在于超越对种族主义的关注，而在于当你需要保护的时候，前来保护你的人&mdash;&mdash;你的唯一希望居然是和你势不两立、矛盾很深的那个人，这种恐惧是会让人不寒而栗的。&rdquo;<br />
	<br />
	　　反思婚姻和爱情<br />
	<br />
	　　电影的故事由黑人警察亚伯&middot;特纳看不惯新搬来邻居的跨种族婚姻而引发，因此对<a href="http://www.eee4.cn/" target="_blank">迅雷电影下载</a>于这种在现实生活中依然存在的恋情和导演本人对这种婚姻的看法就成了媒体尽相发难的焦点。<br />
	<br />
	　　尼尔&middot;布莱特说道，&ldquo;现实生活中有太多的爱情，两个拥有俊秀外表的男女在一起非常的融洽，你也许就想知道除了俊朗的外表互相吸引之外，到底还有什么会让他们相处得如此舒适自在？同样，我也不得不思考这个问题，并且在片中一直设下这个悬念。&rdquo;<br />
	<br />
	　　他表示，&ldquo;为什么亚伯&middot;特纳会如此的讨厌这对年轻夫妇？亚伯&middot;特纳从见到他们的那一刻开始就拒他们于千里之外。首先是他不愿意自己的孩子看到和接触这种跨种族的婚姻，其次是他亲眼看到这对年轻夫妇在游泳池里的亲昵性行为暴露在他的孩子们面前。我认为这其实已经超出了种族问题，因为哪个孩子的父母都不愿意孩子看到这些。&rdquo;<br />
	<br />
	　　当被问及如何看待一些舆论批评电影《湖景水坝》对女性不够重视甚至是反女性时，尼尔&middot;布莱特说道，&ldquo;我认为他们的这种批评是失当的，至少在我的这部影片中并不存在反女性的思想。我想有此舆论主要是建立在之前我导演的《异教徒》之上，在那部片子里我给了人们一个女人的世界，在那个女权至上的岛屿上，统治者全都是女性，外表温柔美丽的女人们却有着蛇蝎一样的心肠，男人在她们心中只是劳作生育的工具，为了更突显自己的主导地位，这些极端的女性甚至割下了自己丈夫的舌头。观众应该可以从中读得出我的讽刺语调，其实我想说明的是那只是乌托邦而已。&rdquo;<br />
	<br />
	　　严苛的导演<br />
	<br />
	　　尼尔&middot;莱布特是一个很有个性、而且很严厉苛责的导演和编剧。因此，在剧组里每天开会讨论研究剧情是家常便饭，演员也经常被要求在正式开拍之前面对镜头排演，剧组人员也时常更换。作为男一号的塞缪尔&middot;杰克逊认为这样的排演非常有意思，尽管也许其他的演员并不这么想，但正因为这样的排演，使他即兴创作了不少台词，对扮演那位跨种族婚姻带有歧视色彩的黑人警察更加得心应手。同时，这也能提高拍摄的进度，排演的时候，只需要把摄像机放在能记录下所有片段的地方，排演的情形将会被全过程地拍摄下来，然后由演员自己去发现问题从而改进。如果不进行排演，一个片段一个场景的拍，会NG无数次而反反复复。剧组几乎所有的人到后来都保持着同一个步调，大家都知道互相在做什么，对导演也因为有了更深刻的理解而心生敬佩。</p>
<p>
	【效果截图】：<br />
	<br />
	<a href="http://img.album.pchome.net/54/70/57/88/ab55214edf81d85004b57396da513411.jpg" target="_blank"><img border="0" src="http://img.album.pchome.net/54/70/57/88/ab55214edf81d85004b57396da513411.jpg" /></a>&nbsp;<br />
	<a href="http://img.album.pchome.net/54/70/57/88/da59ee2d56b01df2494fa7e6afef2745.jpg" target="_blank"><img border="0" src="http://img.album.pchome.net/54/70/57/88/da59ee2d56b01df2494fa7e6afef2745.jpg" /></a>&nbsp;<br />
	<a href="http://img.album.pchome.net/54/70/57/88/7da1639fbdc2ee06534371840fcc8af8.jpg" target="_blank"><img border="0" src="http://img.album.pchome.net/54/70/57/88/7da1639fbdc2ee06534371840fcc8af8.jpg" /></a></p>
<p>
	08年塞缪尔杰克逊惊悚剧情片《合法入侵》BD中英双字1024x576高清版 [2009/07/14下载地址]：<img border="0" src="http://www.eee4.com/templets/img/down.jpg" /></p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://3e:3e@vip.eee4.cn:620/[www.eee4.cn提供]合法入侵BD中英双字1024x576高清版.rmvb" target="_blank">ftp://3e:3e@vip.eee4.cn:620/[www.eee4.cn提供]合法入侵BD中英双字1024x576高清版.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<anchor></anchor><a href="ftp://dy44:piaohua@dy44.piaohua.com:3352/飘花电影piaohua.com合法入侵BD中英双字1280高清.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3352/飘花电影piaohua.com合法入侵BD中英双字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<anchor></anchor><a href="ftp://e23:e23@dm.eee4.com:1216/[3E电影站www.eee4.com]合法入侵DVD中英双字高清版CD1.rmvb" target="_blank">ftp://e23:e23@dm.eee4.com:1216/[3E电影站www.eee4.com]合法入侵DVD中英双字高清版CD1.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<anchor></anchor><a href="ftp://e23:e23@dm.eee4.com:1216/[3E电影站www.eee4.com]合法入侵DVD中英双字高清版CD2.rmvb" target="_blank">ftp://e23:e23@dm.eee4.com:1216/[3E电影站www.eee4.com]合法入侵DVD中英双字高清版CD2.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15955Z-45N0.jpg{/dede:field}
