{dede:field name='keywords'}七种人生BD1280高清迅雷下载，免{/dede:field}
{dede:field name='description'}七种人生BD1280高清迅雷下载、免费下载，七种人生BD1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}七种人生BD1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-04-20{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120420/08/62564813201204200814043910314479452_007.jpg" style="width: 650px; height: 996px" /></p>
<p>
	◎译　　名　七种人生<br />
	◎片　　名　7 lives<br />
	◎年　　代　2011<br />
	◎国　　家　英国<br />
	◎类　　别　奇幻/惊悚<br />
	◎语　　言　英语<br />
	◎字　　幕　中字<br />
	◎IMDB评分 &nbsp; (awaiting 5 votes)<br />
	◎IMDB链接 &nbsp; <a href="http://www.imdb.com/title/tt1558246/" target="_blank">http://www.imdb.com/title/tt1558246/</a><br />
	◎文件格式　X264 + DTS<br />
	◎视频尺寸　1280 x 720<br />
	◎文件大小　1 DVD<br />
	◎片　　长　90 mins<br />
	◎导　　演　保罗-威尔金斯 Paul Wilkins<br />
	◎主　　演　丹尼&middot;戴尔 Danny Dyer ....Tom<br />
	　　　　　　凯特&middot;阿什菲尔德 Kate Ashfield ....Cynthia<br />
	　　　　　　马丁&middot;康普斯顿 Martin Compston ....Rory<br />
	　　　　　　汤姆&middot;古德曼-希尔 Tom Goodman-Hill ....Peter<br />
	　　　　　　安娜&middot;斯科莱姆 Anna Skellern ....Felicity<br />
	　　　　　　尼克&middot;布莱波尔 Nick Brimble ....Ted<br />
	　　　　　　Craig Conway ....Keith<br />
	　　　　　　Helen George ....Valerie<br />
	　　　　　　Theo Barklem-Biggs ....Kid<br />
	　　　　　　Tamzin Malleson ....Mary<br />
	　　　　　　詹妮&middot;雅克 Jennie Jacques ....Carol<br />
	　　　　　　Mary Stockley ....Michelle<br />
	　　　　　　查尔斯&middot;曼勒 Charles Mnene ....Ice<br />
	　　　　　　Layla Amir ....Nurse<br />
	　　　　　　Michael Elwyn ....Brian<br />
	　　　　　　Pete Lee-Wilson ....Kids Dad<br />
	　　　　　　尼克&middot;内维恩 Nick Nevern ....Detective Echo<br />
	　　　　　　Shaun Lucas ....Bouncer<br />
	　　　　　　Ricci McLeod ....Gabriel<br />
	　　　　　　Sam Palladio ....Calvin<br />
	　　　　　　Slinky Winfield ....Silas<br />
	　　　　　　Claire Perkins ....Kids Mum<br />
	　　　　　　Alex Warren ....Revron<br />
	　　　　　　Rebecca Todd ....Nurse<br />
	　　　　　　Michael Kofi ....Max<br />
	　　　　　　Alexia Healy ....Nurse<br />
	　　　　　　Anna Notarantonio ....Passer-by<br />
	　　　　　　Morgan Delle Piane ....Extra<br />
	　　　　　　Julien Ball ....Doctor<br />
	　　　　　　Marie-Claire Zeretzke ....Backstage Groupie<br />
	　　　　　　Stuart J. Prowse ....Record Company Boss<br />
	　　　　　　Craig Izzard ....Extra - Boxing Match (uncredited)<br />
	　　　　　　George Keywood ....Extra - police scene (uncredited)<br />
	　　　　　　Michelle Somerszaule ....Extra (uncredited)<br />
	<br />
	<br />
	<br />
	◎简 &nbsp;　 介<br />
	<br />
	&nbsp; &nbsp; &nbsp;Tom, a married man with kids, is struggling at work when a client tries to seduce him with promises of a &#39;more exciting life&#39;. On his way home one night he gets attacked by a gang of hoodies and falls into a parallel world where he lives 5 other lives including a Rock-Star, a Homeless person and the &#39;hoody&#39; that attacked him. These lives help him to re-evaluate his priorities and values but in order to get home he must face some of his deepest desires and fears. Will he make it home or is the grass greener on the other side?</p>
<p>
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120420/08/62564813201204200814043910314479452_004.jpg" style="width: 650px; height: 366px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120420/08/62564813201204200814043910314479452_003.jpg" style="width: 650px; height: 366px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120420/08/62564813201204200814043910314479452_002.jpg" style="width: 650px; height: 366px" /><br />
	<br />
	&nbsp;</p>
<p>
	【下载地址】</p>
<table bgcolor="#0099cc" border="0" cellpadding="10" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.net" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy125:piaohua@dy125.piaohua.com:7870/飘花电影piaohua.com七种人生BD中字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:7870/飘花电影piaohua.com七种人生BD中字1280高清.rmvb</a></td>
		</tr>
		<tr>
		</tr>
	</tbody>
</table>
<br />{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O16300b0-35501.jpg{/dede:field}
