{dede:field name='keywords'}逃离猩球BD中英双字1280高清经典{/dede:field}
{dede:field name='description'}逃离猩球BD中英双字1280高清经典科幻迅雷下载、免费下载，逃离猩球BD中英双字1280高清经典科幻Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}逃离猩球BD中英双字1280高清经典科幻{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-12-18{/dede:field}
{dede:field name='body'}<p>
	<img alt="" height="659" src="http://img165.poco.cn/mypoco/myphoto/20111213/23/57196343201112132259135894714691448_043.jpg" width="500" /></p>
<p>
	【影片原名】Escape from the Planet of the Apes<br />
	【中文译名】逃离猩球<br />
	【出品公司】20世纪福克斯电影公司<br />
	【出品年代】1971<br />
	【上映日期】1971年5月21日&nbsp;&nbsp;美国&nbsp;&nbsp;<br />
	【影片级别】USA:G<br />
	【IMDB评分】6.1/10 (6,055 votes)<br />
	【国　　家】美国<br />
	【字幕语言】中文/英文<br />
	【视频尺寸】1280&times;720<br />
	【文件格式】RMVB+AAC<br />
	【类　　别】动作/剧情/科幻<br />
	【导　　演】Don Taylor<br />
	【主　　演】罗迪?麦克道尔 Roddy McDowall&nbsp;&nbsp;....Cornelius<br />
	　　　　　　金?亨特 Kim Hunter&nbsp;&nbsp;....Dr. Zira<br />
	　　　　　　Bradford Dillman&nbsp;&nbsp;....Dr. Lewis Dixon<br />
	　　　　　　Natalie Trundy&nbsp;&nbsp;....Dr. Stephanie Branton/Stevie<br />
	　　　　　　Eric Braeden&nbsp;&nbsp;....Dr. Otto Hasslein<br />
	　　　　　　William Windom&nbsp;&nbsp;....The President<br />
	　　　　　　萨尔?米涅奥 Sal Mineo&nbsp;&nbsp;....Dr. Milo<br />
	　　　　　　Albert Salmi&nbsp;&nbsp;....E-1<br />
	　　　　　　Jason Evers&nbsp;&nbsp;....E-2<br />
	　　　　　　John Randolph&nbsp;&nbsp;....Chairman of the President&#39;s Committee of Inquiry<br />
	【内容简介】<br />
	&nbsp; &nbsp;&nbsp; &nbsp; 帮助人类的猿族夫妇兹瑞和考尼斯这回自身难保，他们的飞船坠毁在1973年的地球，人类发现了未来猿族将要统治人类，瑞兹肚里的小猿孩能存活吗？人们将怎么对待他们这对会说话的猿族？<br />
	<img alt="" height="337" src="http://img165.poco.cn/mypoco/myphoto/20111213/23/57196343201112132259135894714691448_042.jpg" style="cursor: pointer" width="600" /><br />
	&nbsp;</p>
<p>
	[下载地址]： &nbsp;<img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2362/飘花电影piaohua.com逃离猩球BD中英双字1280高清.rmvb ">ftp://dy44:piaohua@dy44.piaohua.com:2362/飘花电影piaohua.com逃离猩球BD中英双字1280高清.rmvb </a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15X0I0-224G.jpg{/dede:field}
