{dede:field name='keywords'}义海雄风/军官与魔鬼/好人寥寥[B{/dede:field}
{dede:field name='description'}义海雄风/军官与魔鬼/好人寥寥[BD中英双字1024x576高清版]迅雷下载、免费下载，义海雄风/军官与魔鬼/好人寥寥[BD中英双字1024x576高清版]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}义海雄风/军官与魔鬼/好人寥寥[BD中英双字1024x576高清版]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2010-08-10{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://3e:3e@d8.3edyy.com:174/【3E电影院www.eee4.cc】义海雄风BD中英双字1024x576高清版.rmvb" target="_blank{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MP325330-45043.jpg{/dede:field}
