{dede:field name='keywords'}曼哈顿女佣BD迅雷下载，免费下载{/dede:field}
{dede:field name='description'}曼哈顿女佣BD迅雷下载、免费下载，曼哈顿女佣BDGvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}曼哈顿女佣BD{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-19{/dede:field}
{dede:field name='body'}<p>
	<br />
	&nbsp;<br />
	◆原　　名：Maid In Manhattan<br />
	◆译　　名：曼哈顿女佣<br />
	◆导　　演：王颖(Wayne Wang)<br />
	◆演　　员：珍妮芙-洛佩兹(Jennifer Lopez)<br />
	　　　　　　拉尔夫-费恩斯(Ralph Fiennes)<br />
	　　　　　　泰勒-波西(Tyler Posey)<br />
	　　　　　　娜塔莎-理查森(Natasha Richardson)<br />
	◆类　　型：爱情/喜剧片<br />
	◆片　　长：105 分钟<br />
	◆上　　映：2002年<br />
	◆国　　家：美国<br />
	◆语　　言：英语<br />
	◆链　　接：<a href="http://www.bluemv.com" target="_blank">http://www.bluemv.com</a><br />
	◆简　　介：<br />
	<br />
	　　这是一个发生在现代纽约社会里灰姑娘般的梦幻爱情故事。<br />
	　　珍妮芙-洛佩兹(Jennifer Lopez)在片中饰演的玛丽莎-文图拉(Marisa Ventura)是一位精明、无拘无束的单身母亲，她与儿子泰-文图拉(Ty Ventura，泰勒-波西饰，Tyler Posey)居住在布鲁克斯区(Bronx)。玛丽莎是最豪华的曼哈顿旅馆(Manhattan hotel)的女服务员，成天梦想着能过上更好的日子，当然是要靠她自己的努力而获得。<br />
	　　克里斯托弗-霍尔(Christopher Hall，拉尔夫-费恩斯饰，Ralph Fiennes)英俊、温文尔雅，是美国政坛中最有前途的响当当的人物。克里斯托弗来到纽约参加一个为期一周的活动，包括与大人物一起参加晚会等，他恰巧住在了玛丽莎工作的酒店。造化弄人，二人邂逅后，克里斯托弗误认为她是上流社会的淑女，并堕入了情网。玛丽莎不久发现自己深深地卷入了这个本来会冷眼相看的男人生活中。当一切真相大白、她的真正身份表明后，二人发现他们的生活是如此的不般配。这个童话故事最终能有结果吗？</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O14929120-31503.gif{/dede:field}
