{dede:field name='keywords'}野战排/前进高棉/杀戮战场[BD中{/dede:field}
{dede:field name='description'}野战排/前进高棉/杀戮战场[BD中英双字1280x720高清版]迅雷下载、免费下载，野战排/前进高棉/杀戮战场[BD中英双字1280x720高清版]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}野战排/前进高棉/杀戮战场[BD中英双字1280x720高清版]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2010-07-12{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://3e:3e@d8.3edyy.com:170/【3E电影院www.eee4.cc】野战排BD中英双字1280x720高清版.rmvb" target=_blank>ftftp://3e:3e@d8.3edyy.com:170/【3E电影院www.eee4.cc】野战排BD中英双字1280x720高清版.rmvb</A></TD></TR></TBODY></TABLE></div><ul class="mmlist{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MQ35IF-24G5.jpg{/dede:field}
