{dede:field name='keywords'}纳尼亚传奇2：凯斯宾王子BD中英{/dede:field}
{dede:field name='description'}纳尼亚传奇2：凯斯宾王子BD中英双字1024/1280高清迅雷下载、免费下载，纳尼亚传奇2：凯斯宾王子BD中英双字1024/1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}纳尼亚传奇2：凯斯宾王子BD中英双字1024/1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-12-02{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://d21:d21@xl2.eee4.com:1105/[3E电影站www.eee4.com]纳尼亚传奇2[DVD中英双字1024x554高清版]CD1.rmvb" target="_blank{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MOc21P-14943.jpg{/dede:field}
