{dede:field name='keywords'}黄金大劫案HD国语中字1024高清20{/dede:field}
{dede:field name='description'}黄金大劫案HD国语中字1024高清2012最新上映中国战争动作喜剧大片迅雷下载、免费下载，黄金大劫案HD国语中字1024高清2012最新上映中国战争动作喜剧大片Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}黄金大劫案HD国语中字1024高清2012最新上映中国战争动作喜剧大片{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-12{/dede:field}
{dede:field name='body'}<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120422/09/56643687201204220955587224260145699_008.jpg" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120422/09/56643687201204220955587224260145699_006.jpg" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120422/09/56643687201204220955587224260145699_009.jpg" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120422/09/56643687201204220955587224260145699_007.jpg" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120422/09/56643687201204220955587224260145699_005.jpg" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120422/09/56643687201204220955587224260145699_004.jpg" /></p>
<p>
	导演: 宁浩<br />
	编剧: 宁浩 / 邢爱娜 / 岳小军<br />
	主演: 雷佳音 / 陶虹 / 程媛媛 / 山崎敬一 / 郭涛 / 范伟 / 孙淳 / 刘桦 / 黄渤 / 岳小军<br />
	类型: 剧情 / 喜剧 / 动作 / 历史 / 爱情 / 战争<br />
	制片国家/地区: 中国大陆<br />
	语言: 汉语普通话 / 东北话<br />
	上映日期: 2012-04-23(中国大陆)<br />
	片长: 108分钟<br />
	又名: 黄金谜案 / Guns and Roses</p>
<p>
	<br />
	剧情简介</p>
<p>
	　　一个小混混在阴差阳错间卷进一桩劫金大案，生死命悬一线，疯狂一触即发??<br />
	　　为了八吨神秘黄金，混世小太岁、金镖十三郎、满洲第一影后、代庖神父、富家千金，各类人物粉墨登场； 日本侵略军、外国公使、野鸡军团、神秘剧组、黑心包租婆，各方势力虎视眈眈。谁敌谁友？谁明谁暗？谁生谁死？ 在一个重兵把守，炮弹都炸不开的金库里，八吨黄金如何被劫走，成为最大悬念。</p>
<p>
	<br />
	◎影片截图</p>
<p>
	&nbsp;<img src="http://img170.poco.cn/mypoco/myphoto/20120426/13/56643687201204261334304437267259485_004.jpg" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120426/13/56643687201204261334304437267259485_003.jpg" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120426/13/56643687201204261334304437267259485_002.jpg" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120426/13/56643687201204261334304437267259485_000.jpg" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120426/13/56643687201204261334304437267259485_001.jpg" /></p>
<p>
	&nbsp;<img alt="" height="338" src="http://img011.photo.21cn.com/photos/mark/20120512/o/6CE15F13000EFD82C7ED3C1CFA9DE418.jpg" width="600" /></p>
<p>
	&nbsp;<img alt="" height="338" src="http://img011.photo.21cn.com/photos/mark/20120512/o/0E729160C10415267577C00597BB2D9E.jpg" width="600" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.netftp//dy44:piaohua@dy44.piaohua.com:3142/" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3297/飘花电影piaohua.com黄金大劫案TC国语中字.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3297/飘花电影piaohua.com黄金大劫案TC国语中字.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3405/飘花电影piaohua.com黄金大劫案HD国语中字1024高清.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3405/飘花电影piaohua.com黄金大劫案HD国语中字1024高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15K63F-24V2.jpg{/dede:field}
