<?php
$z[0]=Array("field","进攻列宁格勒/列宁格勒/列宁格勒",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","进攻列宁格勒/列宁格勒/列宁格勒袭击[DVD中字+1024x576高清版]迅雷下载、免费下载，进攻列宁格勒/列宁格勒/列宁格勒袭击[DVD中字+1024x576高清版]Gvod高清在线播放，剧情介绍等。",73,283);
$z[1][4]['name']="description";
$z[2]=Array("field","进攻列宁格勒/列宁格勒/列宁格勒袭击[DVD中字+1024x576高清版]",285,381);
$z[2][4]['name']="title";
$z[3]=Array("field","",383,422);
$z[3][4]['name']="writer";
$z[4]=Array("field","",424,463);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-05-18",465,515);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",517,554);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://5e:5e@m1.3edyy.com:1486/【3E电影院www.eee4.cc】列宁格勒袭击DVD中字.rmvb\" target=_blank>ftftp://5e:5e@m1.3edyy.com:1486/【3E电影院www.eee4.cc】列宁格勒袭击DVD中字.rmvb</A></TD></TR></TBODY></TABLE><BR><FONT color=#ff0000 size=2><STRONG>[下载地址]：<IMG border=0 src=\"httftp://www.3edyy.com/templets/img/down.jpg",556,911);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MP61C10-44U9.jpg",913,995);
$z[8][4]['name']="litpic";

?>