{dede:field name='keywords'}僵尸先生3/灵幻先生HD高清1280高{/dede:field}
{dede:field name='description'}僵尸先生3/灵幻先生HD高清1280高清迅雷下载、免费下载，僵尸先生3/灵幻先生HD高清1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}僵尸先生3/灵幻先生HD高清1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-09-13{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20110911/21/62564813201109112144112652830190444_000.jpg" /></p>
<p>
	◎中文　名　僵尸先生3/灵幻先生<br />
	◎片　　名　Mr Vampire 3<br />
	◎年　　代　1987<br />
	◎地　　区　中国香港<br />
	◎类　　别　恐怖<br />
	◎语　　言　普通话<br />
	◎字　　幕　中文<br />
	◎IMDB评分　6.8/10(63votes)<br />
	◎IMDB链接　<a href="http://www.imdb.com/title/tt0093422">http://www.imdb.com/title/tt0093422</a><br />
	◎文件格式　X264 + AAC<br />
	◎视频尺寸　1024 x 576<br />
	◎文件大小　1CD 49 x 15MB<br />
	◎片　　长　88 Min<br />
	◎导　　演　刘观伟 Ricky Lau<br />
	◎主　　演　林正英 Ching-Ying Lam .....The Master<br />
	　　　　　　楼南光 Billy Lau .....Chiang<br />
	　　　　　　吕方 Fong Liu .....Ta Pao<br />
	　　　　　　吴耀汉 Richard Ng .....Mao Ming<br />
	　　　　　　午马 Ma Wu .....Party Guest<br />
	　　　　　　叶荣祖 Wing-Cho Yip .....Party Guest<br />
	　　　　　　元奎 Corey Yuen .....Party Guest<br />
	　　　　　　洪金宝 Sammo Hung .....Hung (uncredited)<br />
	◎简　　介　<br />
	月黑风高之夜，悍匪之一的王婆在行劫后，利用茅山术而侥幸逃脱。半桶水茅山道士吴耀汉途经此镇，又以茅山小术呃饮呃食，结果被令吴当夜入黑前离开富贵镇。因擒获头号通缉犯，可得赏金，众保安队员皆雀跃不已，而落泊道士吴耀汉及其同谋之小鬼吕方，获悉后，便潜入监仓欲救出劫匪，但结果失败。 当晚，吴与小鬼在酒楼食饭，遇上楼南光，小鬼吕方整蛊楼，楼之师父林正英乃茅山道士，及时发觉楼被小鬼整蛊，出手将小鬼收入萌芦之内，吴向林求情，道出与小鬼之表兄弟关系，求林放过吕，林教训美人鬼不能同途合作搵食，否则徒费精力，楼更迫吴向天始天尊神位发毒誓，最后林允释放吕，但二人必须分道扬镖&hellip;&hellip;<br />
	<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20110913/15/62564813201109131554463090640053543_002.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20110913/15/62564813201109131554463090640053543_001.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20110913/15/62564813201109131554463090640053543_000.jpg" style="width: 720px; height: 405px" /><br />
	&nbsp;&nbsp;<br />
	&nbsp;<br />
	&nbsp;</p>
<p>
	[下载地址]： &nbsp;<img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" /></p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:1536/飘花电影piaohua.com灵幻先生HD高清1280高清.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:1536/飘花电影piaohua.com灵幻先生HD高清1280高清.rmvb</a></td>
		</tr>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy125:piaohua@dy125.piaohua.com:3021/飘花电影piaohua.com灵幻先生HD高清1024分辨率.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:3021/飘花电影piaohua.com灵幻先生HD高清1024分辨率.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1C0Z50-29452.jpg{/dede:field}
