<?php
$z[0]=Array("field","周杰伦.費玉清-千里之外,MTV迅雷",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","周杰伦.費玉清-千里之外 MTV迅雷下载、免费下载，周杰伦.費玉清-千里之外 MTVGvod高清在线播放，剧情介绍等。",73,219);
$z[1][4]['name']="description";
$z[2]=Array("field","周杰伦.費玉清-千里之外 MTV",221,285);
$z[2][4]['name']="title";
$z[3]=Array("field","",287,326);
$z[3][4]['name']="writer";
$z[4]=Array("field","",328,367);
$z[4][4]['name']="source";
$z[5]=Array("field","2006-09-14",369,419);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p><embed name=\"MediaPlayer\" pluginspage=\"http://www.microsoft.com/isapi/redir.dll?prd=windows&amp;sbp=mediaplayer&amp;ar=media&amp;sba=plugin&amp;\" align=\"6\" src=\"http://fmtv.uying.com/200608/0825/周杰伦.費玉清-千里之外(完整版).wmv\" width=\"350\" height=\"300\" type=\"application/x-mplayer2\" defaultframe=\"datawindow\" invokeurls=\"1\" clicktoplay=\"0\" enablecontextmenu=\"1\" allowscan=\"1\" transparentatstart=\"0\" animationatstart=\"0\" autorewind=\"0\" autostart=\"1\" showcaptioning=\"0\" showgotobar=\"0\" autosize=\"0\" showstatusbar=\"1\" showdisplay=\"0\" showtracker=\"1\" showaudiocontrols=\"1\" showpositioncontrols=\"0\" showcontrols=\"1\" border=\"0\"></embed>&nbsp;</p>\r\n<p>http://fmtv.uying.com/200608/0825/周杰伦.費玉清-千里之外(完整版).wmv</p>",421,1181);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c120524/133N353DD0-2G248.gif",1183,1266);
$z[7][4]['name']="litpic";

?>