<?php
$z[0]=Array("field","非常人贩3/玩命快递3BD中英双字1",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","非常人贩3/玩命快递3BD中英双字1024/1280高清迅雷下载、免费下载，非常人贩3/玩命快递3BD中英双字1024/1280高清Gvod高清在线播放，剧情介绍等。",73,251);
$z[1][4]['name']="description";
$z[2]=Array("field","非常人贩3/玩命快递3BD中英双字1024/1280高清",253,333);
$z[2][4]['name']="title";
$z[3]=Array("field","",335,374);
$z[3][4]['name']="writer";
$z[4]=Array("field","",376,415);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-12-10",417,467);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",469,506);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://e16:e16@xl2.eee4.com:9219/[3E电影站www.eee4.com]非常人贩3DVD中字.rmvb\" target=\"_blank",508,638);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MP2J960-34122.jpg",640,723);
$z[8][4]['name']="litpic";

?>