{dede:field name='keywords'}恐怖实验/病毒禁区BD1280高清迅{/dede:field}
{dede:field name='description'}恐怖实验/病毒禁区BD1280高清迅雷下载、免费下载，恐怖实验/病毒禁区BD1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}恐怖实验/病毒禁区BD1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-04-18{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://i.imgur.com/OQkkh.jpg" /></p>
<p>
	◎译　　名　恐怖实验/病毒禁区(台)<br />
	◎片　　名　The Terror Experiment<br />
	◎年　　代　2011<br />
	◎国　　家　美国<br />
	◎类　　别　动作/惊悚<br />
	◎语　　言　英语<br />
	◎字　　幕　中字<br />
	◎IMDB评分 &nbsp; 4.0/10 (92 votes)<br />
	◎IMDB链接 &nbsp; <a href="http://www.imdb.com/title/tt1323917/" target="_blank">http://www.imdb.com/title/tt1323917/</a><br />
	◎文件格式　X264 + AC3<br />
	◎视频尺寸　1280 x 720<br />
	◎文件大小　3/4 DVD<br />
	◎片　　长　82 MINS<br />
	◎导　　演　George Mendeluk<br />
	◎主　　演　C&middot;托马斯&middot;豪威尔 C. Thomas Howell ....Chief Grasso<br />
	　　　　　　贾德&middot;尼尔森 Judd Nelson ....Agent Wilson<br />
	　　　　　　罗伯特&middot;卡拉丁 Robert Carradine ....Dr. Wexler<br />
	　　　　　　杰森&middot;伦敦 Jason London ....Cale<br />
	　　　　　　Lochlyn Munro ....Loham<br />
	　　　　　　莎拉&middot;莱恩 Sarah Laine ....Carol Milner<br />
	　　　　　　Alicia Leigh Willis ....Mandy<br />
	　　　　　　Edrick Browne ....Marine Tony<br />
	　　　　　　Darcel White Moreno ....Anne<br />
	　　　　　　Chuck Bush ....Detective Leary<br />
	　　　　　　Mike Mayhall ....Davis - Haz-Mat<br />
	　　　　　　Dunbar Merrill ....Eric<br />
	　　　　　　Alexander Mendeluk ....Ryan<br />
	　　　　　　泰德&middot;弗格森 Ted Ferguson ....The Old Accountant<br />
	　　　　　　George Mendeluk ....The Old Accountant<br />
	　　　　　　Zachariah Jay ....Doctor #1<br />
	　　　　　　Patty Yu ....June<br />
	　　　　　　Johnny Rock ....George<br />
	　　　　　　R.D. Miller Jr. ....News Anchor<br />
	　　　　　　Nikki Hester ....Woman<br />
	　　　　　　Jerry Leggio ....Dr. Andzari<br />
	　　　　　　Henry Boger ....Helicopter Pilot<br />
	　　　　　　Brett Beoubay ....Elevator Passenger<br />
	　　　　　　Mia Allen ....Infected<br />
	　　　　　　Dominick LaBanca ....Security Guard<br />
	　　　　　　Arielle Stephens ....Allie<br />
	　　　　　　Jeff Jonas ....Officer Burnes<br />
	　　　　　　Lee D. Potter ....Infected<br />
	　　　　　　John Chambers ....Williams<br />
	　　　　　　Lauren Roehm ....Shay<br />
	　　　　　　Ira Kortum ....Homeless Drunk<br />
	　　　　　　C. Erica Potter ....Infected<br />
	　　　　　　Jamie Mallory ....Infected<br />
	　　　　　　Brandon Duracher ....Agent Riley<br />
	　　　　　　Ismail Abdur-Rahman ....Infected<br />
	　　　　　　Darren Arnaud ....S.W.A.T. guy<br />
	　　　　　　Raymond Hebert ....Businessman<br />
	　　　　　　Seth Duhy ....S.W.A.T Guy<br />
	　　　　　　Kale Arndt ....Infected<br />
	　　　　　　Aaron Phillip Stark ....Dispatcher (voice)<br />
	　　　　　　Paul Boger ....Thomas Rouge<br />
	　　　　　　Chandler Adams ....Infected<br />
	<br />
	<br />
	<br />
	◎简　　介<br />
	<br />
	　　恐怖分子在联邦大厦内制造了大爆炸，爆炸释放出的有毒气体通过通风系统传播。而他们的目的是：揭露政府的秘密生物武器，那是一种致命的病毒。它能立即攻击人的肾上腺系统，使吸入这种有毒气体的人具有超越常人能力，但他们将不再是人因为这种气体让他们失去理智，成为了杀人工具.....</p>
<p>
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120418/08/62564813201204180817431024947134352_003.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120418/08/62564813201204180817431024947134352_002.jpg" style="width: 720px; height: 405px" /></p>
<p>
	【下载地址】</p>
<table bgcolor="#0099cc" border="0" cellpadding="10" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.net" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy125:piaohua@dy125.piaohua.com:7867/飘花电影piaohua.com病毒禁区BD中字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:7867/飘花电影piaohua.com病毒禁区BD中字1280高清.rmvb</a></td>
		</tr>
		<tr>
		</tr>
	</tbody>
</table>
<br />{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1561S40-53238.jpg{/dede:field}
