<?php
$z[0]=Array("field","开拓者：陌生的兄弟连高清720P,1",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","开拓者：陌生的兄弟连高清720P 1280*720迅雷下载、免费下载，开拓者：陌生的兄弟连高清720P 1280*720Gvod高清在线播放，剧情介绍等。",73,241);
$z[1][4]['name']="description";
$z[2]=Array("field","开拓者：陌生的兄弟连高清720P 1280*720",243,318);
$z[2][4]['name']="title";
$z[3]=Array("field","",320,359);
$z[3][4]['name']="writer";
$z[4]=Array("field","",361,400);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-08-03",402,452);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",454,491);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://dy195:piaohua@dy195.piaohua.com:1005/飘花电影下载站www.piaohua.com陌生的兄弟连720p.mkv",493,624);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MP51bP-29428.jpg",626,708);
$z[8][4]['name']="litpic";

?>