{dede:field name='keywords'}埃及的十项伟大发现BD中字1024高{/dede:field}
{dede:field name='description'}埃及的十项伟大发现BD中字1024高清美国纪录片迅雷下载、免费下载，埃及的十项伟大发现BD中字1024高清美国纪录片Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}埃及的十项伟大发现BD中字1024高清美国纪录片{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-06-13{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="/uploads/allimg/c120524/133N4P61130-52094.jpg" /></p>
<p>
	◎中文片名　埃及的十项伟大发现<br />
	◎英文片名　Egypt&#39;s Ten Greatest Discoveries<br />
	◎频　　道　Discovery Channel<br />
	◎发行时间　2008<br />
	◎地　　区　美国<br />
	◎类　　别　纪录片<br />
	◎语　　言　英语<br />
	◎字　　幕　中文<br />
	◎文件格式　BD-RMVB<br />
	◎视频尺寸　1024 x 576<br />
	◎文件大小　1CD<br />
	◎时　　长　87 分钟<br />
	◎导　　演　<br />
	◎主　　演　</p>
<p>
	<br />
	◎影片介绍　</p>
<p>
	　　埃及高级考古专家Zahi Hawass和他的探索小队挑选出了在埃及所有发现中10种最重要的.在前期对这些巨大建筑的考察中,这些发现揭秘了埃及法老王,埃及艳後以及普通侍从的惊人逸事,踏上这趟绝妙旅程,一起到尼罗河去探寻,追溯埃及许许多多遗失已久的未知谜团.</p>
<p>
	<img alt="" src="/uploads/allimg/c120524/133N4P62230-61C7.jpg" style="width: 728px; height: 410px" /></p>
<p>
	<img alt="" src="/uploads/allimg/c120524/133N4P62S0-M4M.jpg" style="width: 728px; height: 410px" /></p>

<p>
	[下载地址]：</p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				ftp://dy47:piaohua@dy47.piaohua.com:702/飘花电影piaohua.com埃及的十项伟大发现.rmvb</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120524/133N4P633P-X421.jpg{/dede:field}
