<?php
$z[0]=Array("field","伦敦上空的鹰/不列顛之战[BD中字",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","伦敦上空的鹰/不列顛之战[BD中字1024x576高清版无水印]迅雷下载、免费下载，伦敦上空的鹰/不列顛之战[BD中字1024x576高清版无水印]Gvod高清在线播放，剧情介绍等。",73,269);
$z[1][4]['name']="description";
$z[2]=Array("field","伦敦上空的鹰/不列顛之战[BD中字1024x576高清版无水印]",271,360);
$z[2][4]['name']="title";
$z[3]=Array("field","",362,401);
$z[3][4]['name']="writer";
$z[4]=Array("field","",403,442);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-02-05",444,494);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",496,533);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://3e:3e@m3.3edyy.com:133/【3E电影院www.3edyy.com】伦敦上空的鹰BD中字1024x576高清版无水印.rmvb\" target=\"_blank",535,687);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MP5bV0-3O32.jpg",689,770);
$z[8][4]['name']="litpic";

?>