{dede:field name='keywords'}杨千嬅世界巡回演唱会2010香港站{/dede:field}
{dede:field name='description'}杨千嬅世界巡回演唱会2010香港站【DVD粤语】迅雷下载、免费下载，杨千嬅世界巡回演唱会2010香港站【DVD粤语】Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}杨千嬅世界巡回演唱会2010香港站【DVD粤语】{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-01-25{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://4e:4e@d6.3edyy.com:616/【3E看看www.3ekk.com】杨千华世界巡回演唱会2010香港站CD1.rmvb" target=_blank>ftftp://4e:4e@d6.3edyy.com:616/【3E看看www.3ekk.com】杨千华世界巡回演唱会2010香港站CD1.rmvb</A></TD></TR></TBODY></TABLE>CD2：<BR>
<TABLE style="BORDER-BOTTOM: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-RIGHT: #cccccc 1px dotted" border=0 cellSpacing=0 cellPadding=6 width="95%" align=center>
<TBODY>
<TR>
<TD style="WORD-WRAP: break-word" bgColor=#fdfddf><A href="ftftp://4e:4e@d6.3edyy.com:616/【3E看看www.3ekk.com】杨千华世界巡回演唱会2010香港站CD2.rmvb" target=_blank>ftftp://4e:4e@d6.3edyy.com:616/【3E看看www.3ekk.com】杨千华世界巡回演唱会2010香港站CD2.rmvb</A></TD></TR></TBODY></TABLE>CD3：<BR>
<TABLE style="BORDER-BOTTOM: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-RIGHT: #cccccc 1px dotted" border=0 cellSpacing=0 cellPadding=6 width="95%" align=center>
<TBODY>
<TR>
<TD style="WORD-WRAP: break-word" bgColor=#fdfddf><A href="ftftp://4e:4e@d6.3edyy.com:616/【3E看看www.3ekk.com】杨千华世界巡回演唱会2010香港站CD3.rmvb" target=_blank>ftftp://4e:4e@d6.3edyy.com:616/【3E看看www.3ekk.com】杨千华世界巡回演唱会2010香港站CD3.rmvb</A></TD></TR></TBODY></TABLE>CD4：<BR>
<TABLE style="BORDER-BOTTOM: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-RIGHT: #cccccc 1px dotted" border=0 cellSpacing=0 cellPadding=6 width="95%" align=center>
<TBODY>
<TR>
<TD style="WORD-WRAP: break-word" bgColor=#fdfddf><A href="ftftp://4e:4e@d6.3edyy.com:616/【3E看看www.3ekk.com】杨千华世界巡回演唱会2010香港站CD4.rmvb" target=_blank>ftftp://4e:4e@d6.3edyy.com:616/【3E看看www.3ekk.com】杨千华世界巡回演唱会2010香港站CD4.rmvb</A></TD></TR></TBODY></TABLE></div><ul class="mmlist{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MQ464250-33204.jpg{/dede:field}
