{dede:field name='keywords'}轰天炮/致命武器系列（4部)[BD中{/dede:field}
{dede:field name='description'}轰天炮/致命武器系列（4部)[BD中字1024/1280高清版]迅雷下载、免费下载，轰天炮/致命武器系列（4部)[BD中字1024/1280高清版]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}轰天炮/致命武器系列（4部)[BD中字1024/1280高清版]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-03-31{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://3e:3e@d3.3edyy.com:121/【3E电影院www.eee4.org】轰天炮[BD中字1024x576高清版].rmvb" target="_blank{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MO5262Z-39301.jpg{/dede:field}
