{dede:field name='keywords'}红线/超时空甩尾DVD中英双字2010{/dede:field}
{dede:field name='description'}红线/超时空甩尾DVD中英双字2010最新动画迅雷下载、免费下载，红线/超时空甩尾DVD中英双字2010最新动画Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}红线/超时空甩尾DVD中英双字2010最新动画{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-08-24{/dede:field}
{dede:field name='body'}<p>
	<img alt="" border="0" class="topic" jquery1314172436609="22" oldblock="inline" src="http://kiddtic.files.wordpress.com/2011/06/redline_poster.jpg" style="width: 600px; display: inline; height: 450px; cursor: pointer" /></p>
<p>
	【译名】红线 | 超时空甩尾<br />
	【片名】Redline<br />
	【年代】2010<br />
	【国家】日本<br />
	【类型】动画 | 动作 | 科幻<br />
	【时间】102 Mins<br />
	【IMDB评分】7.3<br />
	【导演】小池健<br />
	【演员】木村拓哉 | 苍井优 | 浅野忠信 | 津田宽治 | 冈田义德 | 森下能幸</p>
<p>
	【作品情报】<br />
	　　剧场版《REDLINE》<br />
	　　2010年10月9日 日本全国公映<br />
	　　<br />
	【故事简介】<br />
	　　这是一个关于遥远未来的故事。<br />
	　　五年一度的宇宙速度对决&ldquo;REDLINE&rdquo;马上就要开幕！<br />
	　　表面上看起来很酷，梳着飞机头身穿夹克的JP实际上是一个非常害羞的男性，为了得到初恋女孩索诺西的眷顾，JP参加了&ldquo;REDLINE&rdquo;的速度盛宴。&ldquo;REDLINE&rdquo;的比赛没有规则，为了取得胜利参赛者可以随身装载武器，这是一场赌上性命的对决。最糟的还不仅于此，这次比赛的举办场地竟然是号称史上最恶的军事国家罗伯瓦尔特（机器人世界），参赛者得知消息后纷纷退出比赛。然而，JP和他心仪的女孩索诺西毅然决定参加比赛。在比赛当天，JP的儿时玩伴天才机械师弗里斯彼为JP准备了最棒的跑车。但是跑车上却被安装了炸弹。弗里斯彼因为某个原因与人合谋了这场比赛。知道真相的JP毅然决然踩下了跑车的油门。这个时候，罗伯瓦尔特下达了阻止&ldquo;REDLINE&rdquo;开赛的出击命令。对索诺西的爱恋，与弗里斯彼的纠葛以及罗伯瓦尔特的妨碍。JP要如何打破这纠缠交错的命运！</p>
<p>
	<img alt="" src="/uploads/allimg/c120525/133O04GS10-132Y7.jpg" /></p>
<p>
	<img alt="" src="/uploads/allimg/c120525/133O04G9550-149210.jpg" /></p>
<p>
	[下载地址]： &nbsp;<img border="0" src="/uploads/allimg/c120524/133N2Z4FF-102231.jpg" />
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:1389/飘花电影piaohua.com超时空甩尾DVD中英双字.rmvb</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O04H0F-153Q6.jpg{/dede:field}
