{dede:field name='keywords'}混蛋DVD中字2012最新美国R级动作{/dede:field}
{dede:field name='description'}混蛋DVD中字2012最新美国R级动作大片迅雷下载、免费下载，混蛋DVD中字2012最新美国R级动作大片Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}混蛋DVD中字2012最新美国R级动作大片{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-04-24{/dede:field}
{dede:field name='body'}<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120424/13/56643687201204241331111055652627548_005.jpg" /></p>

<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120424/13/56643687201204241331111055652627548_004.jpg" /></p>

<p>
	◎译　　名 混蛋<br />
	◎片　　名　Bad Ass<br />
	◎年　　代　2012<br />
	◎国　　家　美国<br />
	◎类　　别　动作<br />
	◎语　　言　英语<br />
	◎字　　幕　中文<br />
	◎IMDB评分 Awaiting 5 votes<br />
	◎IMDB链接 <a href="http://www.imdb.com/title/tt1928330">http://www.imdb.com/title/tt1928330</a><br />
	◎文件格式　DVD-RMVB<br />
	◎视频尺寸　720 x 404<br />
	◎文件大小　1CD 457MB<br />
	◎片　　长　1h 30mn<br />
	◎导　　演　克雷格&middot;莫斯 Craig Moss<br />
	◎主　　演　丹尼&middot;特乔 Danny Trejo &hellip;.Frank Vega<br />
	　　　　　　查尔斯&middot;达顿 Charles Dutton &hellip;.Panther<br />
	　　　　　　朗&middot;普尔曼 Ron Perlman &hellip;.Mayor Williams<br />
	　　　　　　Joyful Drake &hellip;.Amber Lamps<br />
	　　　　　　帕特里克&middot;法比安 Patrick Fabian &hellip;.Office Malark<br />
	　　　　　　雯特&middot;艾娃&middot;佐莉 Winter Ave Zoli &hellip;.Tatiana<br />
	　　　　　　Danny Woodburn &hellip;.Sluggy Korn-nuts<br />
	　　　　　　Donzaleigh Abernathy &hellip;.Mother</p>
<p>
	<br />
	◎简　　介　</p>
<p>
	《混蛋》中，丹尼&middot;特乔饰演一名当年的越战老兵，退役之后他一直混得很是凄惨。直到在一场巴士事故中救下了一位老黑人，他成了当地的英雄。不过，好运并没有就此到来，他发现自己最好的朋友被谋杀而警察却并不打算过问此事&hellip;&hellip;</p>

<p>
	◎影片截图</p>
<p>
	&nbsp;</p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120424/13/56643687201204241331111055652627548_000.jpg" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120424/13/56643687201204241331111055652627548_003.jpg" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120424/13/56643687201204241331111055652627548_002.jpg" /></p>

<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.netftp//dy44:piaohua@dy44.piaohua.com:3201/" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3284/飘花电影piaohua.com混蛋DVD中字.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3284/飘花电影piaohua.com混蛋DVD中字.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O156352P-36146.jpg{/dede:field}
