{dede:field name='keywords'}生化大蜘蛛迅雷下载，免费下载，{/dede:field}
{dede:field name='description'}生化大蜘蛛迅雷下载、免费下载，生化大蜘蛛Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}生化大蜘蛛{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2007-01-03{/dede:field}
{dede:field name='body'}<P>美國軍方以蜘蛛作為實驗對象，意圖製造出一種戰爭用的生物武器，但是違背大自然的結果卻是，創造出了連人類都無法控制的大蜘蛛，一次意外造成了便種蜘蛛肆虐了整個好萊塢，最後雖然消滅了大蜘蛛，卻也使得好萊塢毀於一旦，然而危機還沒有結束，因為還有一箱的變種蜘蛛流落到一間錄音室中，在錄音師史帝夫不小心開啟箱子之後，蜘蛛又悄悄地開始毀天滅地....<BR><BR>下载地址（一）：<IMG src="/templets/img/down.jpg" border=0><br>
CD1：<br><table style="BORDER-RIGHT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; BORDER-BOTTOM: #cccccc 1px dotted" cellspacing="0" cellpadding="6" width="95%" align="center" border="0">
    <tbody>
        <tr>
            <td style="WORD-WRAP: break-word" bgcolor="#fdfddf"><anchor></anchor><a href="ftp://222.171.15.68:44588/最新电影/欧美专区/01.25生化大蜘蛛/01.rmvb" target="_blank">生化大蜘蛛CD1</a></td>
        </tr>
    </tbody>
</table>
CD2：<br><table style="BORDER-RIGHT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; BORDER-BOTTOM: #cccccc 1px dotted" cellspacing="0" cellpadding="6" width="95%" align="center" border="0">
    <tbody>
        <tr>
            <td style="WORD-WRAP: break-word" bgcolor="#fdfddf"><anchor></anchor><a href="ftp://222.171.15.68:44588/最新电影/欧美专区/01.25生化大蜘蛛/02.rmvb" target="_blank">生化大蜘蛛CD2</a></td>
    </tbody>
</table><br><br><br>
下载地址（二）：<IMG src="/templets/img/down.jpg" border=0><br>
CD1：<br><table style="BORDER-RIGHT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; BORDER-BOTTOM: #cccccc 1px dotted" cellspacing="0" cellpadding="6" width="95%" align="center" border="0">
    <tbody>
        <tr>
            <td style="WORD-WRAP: break-word" bgcolor="#fdfddf"><anchor></anchor><a href="ftp://218.28.86.244/新片专区/01.25生化大蜘蛛/01.rmvb" target="_blank">生化大蜘蛛CD1</a></td>
        </tr>
    </tbody>
</table>
CD2：<br><table style="BORDER-RIGHT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; BORDER-BOTTOM: #cccccc 1px dotted" cellspacing="0" cellpadding="6" width="95%" align="center" border="0">
    <tbody>
        <tr>
            <td style="WORD-WRAP: break-word" bgcolor="#fdfddf"><anchor></anchor><a href="ftp://218.28.86.244/新片专区/01.25生化大蜘蛛/02.rmvb" target="_blank">生化大蜘蛛CD2</a></td>
    </tbody>
</table><br><br><br>
下载地址（三）：<IMG src="/templets/img/down.jpg" border=0><br>
CD1：<br><table style="BORDER-RIGHT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; BORDER-BOTTOM: #cccccc 1px dotted" cellspacing="0" cellpadding="6" width="95%" align="center" border="0">
    <tbody>
        <tr>
            <td style="WORD-WRAP: break-word" bgcolor="#fdfddf"><anchor></anchor><a href="ftp://ftp.55525.com/新片专区/01.25生化大蜘蛛/01.rmvb" target="_blank">生化大蜘蛛CD1</a></td>
        </tr>
    </tbody>
</table>
CD2：<br><table style="BORDER-RIGHT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; BORDER-BOTTOM: #cccccc 1px dotted" cellspacing="0" cellpadding="6" width="95%" align="center" border="0">
    <tbody>
        <tr>
            <td style="WORD-WRAP: break-word" bgcolor="#fdfddf"><anchor></anchor><a href="ftp://ftp.55525.com/新片专区/01.25生化大蜘蛛/02.rmvb" target="_blank">生化大蜘蛛CD2</a></td>
    </tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O164L040-353B.jpg{/dede:field}
