{dede:field name='keywords'}地海战记BD中字1280高清[DVD国语{/dede:field}
{dede:field name='description'}地海战记BD中字1280高清[DVD国语中字无水印]迅雷下载、免费下载，地海战记BD中字1280高清[DVD国语中字无水印]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}地海战记BD中字1280高清[DVD国语中字无水印]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-11-24{/dede:field}
{dede:field name='body'}<p>
	&nbsp;<img alt="" height="645" src="/uploads/allimg/c120525/133O04406460-4O39.jpg" width="500" /></p>
<p>
	◎中文片名：《地海战记》06日本动画大片DVD国语中字无水印<br />
	◎英文片名：Tales From Earthsea<br />
	◎出品年代：2006<br />
	◎国家地区：日本<br />
	◎类　　别：动画<br />
	◎对白语言：普通话<br />
	◎字　　幕：简体中文<br />
	◎文件格式：rmvb<br />
	◎文件大小：1CD 417M<br />
	◎视频大小：816 x 432<br />
	◎片　　长：01:55:30<br />
	◎导　　演：宫崎吾郎<br />
	◎主要演员：冈田准一 手嶌葵 田中裕子 香川照之 倍赏美津子<br />
	◎简　　介：</p>
<p>
	　　从前，人跟龙是生活在同一个世界的，但是后来，人选择了大地跟海洋，留在东方的大地；龙则选择了风和火，迁居西域。　有一天，一直居住在西域的龙突然出现在东方的大地，随之而来发生的，就是各地农作物以及家畜的枯坏病死。</p>
<p>
	　　世界的均衡开始崩坏。大贤人（地海）为了要找出原因，展开了旅程。途中遇到了王子亚伦，他是一位舍弃了自己国家的王子。王子的心中一直感受到有一股黑暗的力量在操控他，而他也一直被一个不知名的黑影追逐着。两人到了首都后，发现整个城市隐藏着一股堕落且不真实的气氛。在这里，到处电影下载可以看到人口贩卖或是毒品贩卖，所有在市场上贩卖的货品都是一些使人堕落或是禁卖的商品。</p>
<p>
	　　到底为什么世界会失去平衡，又人心为什么会堕落到这种地步？地海和亚伦必须要将答案找出来，并与之战斗&hellip;&hellip;</p>
<p>
	<img alt="" border="0" onclick="zoom(this, 'attachments/20090531_3ad44562662e373497fa1ZWHQVWSwpw4.jpg')" onload="attachimg(this, 'load')" onmouseout="attachimginfo(this, 'attach_122358', 0, event)" onmouseover="attachimginfo(this, 'attach_122358', 1);attachimg(this, 'mouseover')" src="http://bbs.3e-online.com/attachments/20090531_3ad44562662e373497fa1ZWHQVWSwpw4.jpg" /></p>
<p>
	【电影截图】：<br />
	<br />
	&nbsp;<br />
	<img alt="" height="337" src="/uploads/allimg/c120525/133O0440I30-E304.jpg" style="cursor: pointer" width="600" /></p>
<p>
	<img alt="" height="337" src="/uploads/allimg/c120525/133O0440Q10-K543.jpg" style="cursor: pointer" width="600" /></p>
<p>
	<img alt="" height="337" src="/uploads/allimg/c120525/133O0440Z60-SI3.jpg" style="cursor: pointer" width="600" /></p>
<br />

<p>
	06日本动画大片《地海战记》DVD国语中字无水印 ：<img border="0" src="http://www.eee4.com/templets/img/down.jpg" /></p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				ftp://3e:3e@www2.eee4.com:196/[3E电影站www.eee4.com]地海战记DVD国语中字无水印.rmvb</td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				ftp://dy44:piaohua@dy44.piaohua.com:2162/飘花电影piaohua.com地海战记BD中字1280高清.rmvb</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O0442560-10MZ.jpg{/dede:field}
