{dede:field name='keywords'}新海神号历险记/海神号迅雷下载{/dede:field}
{dede:field name='description'}新海神号历险记/海神号迅雷下载、免费下载，新海神号历险记/海神号Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}新海神号历险记/海神号{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2008-01-17{/dede:field}
{dede:field name='body'}<P>【中文译名】《新海神号历险记/海神号/海神波塞冬号》<BR>【片　　名】Poseidon<BR>【年　　代】2006<BR>【国　　家】美国<BR>【类　　别】灾难/动作/冒险<BR>【语　　言】英语<BR>【字　　幕】中文字幕<BR>【视频尺寸】640x256<BR>【电影来源】3E迅雷电影下载站(www.eee4.com)<BR>【文件大小】1CD 412MB<BR>【片　　长】99 Min<BR>【导　　演】沃夫冈·彼得森 Wolfgang Petersen <BR>【主　　演】乔什·卢卡斯 Josh Lucas .... John Dylan <BR>　　　　　　库尔特·拉塞尔 Kurt Russell .... Robert Ramsey <BR>　　　　　　杰辛达·巴莱特 Jacinda Barrett .... Maggie James <BR>　　　　　　理查德·德莱弗斯 Richard Dreyfuss .... Richard Nelson <BR>　　　　　　Jimmy Bennett .... Conor James <BR>　　　　　　艾美·罗萨姆 Emmy Rossum .... Jennifer Ramsey <BR>　　　　　　迈克·沃格尔 Mike Vogel .... Christian <BR>　　　　　　Mía Maestro .... Elena Gonzalez <BR>　　　　　　安德烈·布拉格 Andre Braugher .... Captain Michael Bradford <BR>　　　　　　凯文·狄龙 Kevin Dillon .... Lucky Larry </P>
<P>【剧情简介】：</P>
<P>　　◇ 剧情：豪华游轮遇难记 </P>
<P>　　新年前夜，超豪华游轮“海神号”再次从北大西洋出航。在这艘20层楼高、13层甲板、800个房间的巨大游轮上，船长<BR>正在主持新年舞会，灯红酒绿的庆祝显得格外热闹。然而，正当宾客们聚集在大厅等待新年钟声敲响，让人沉醉的香槟一一<BR>倾倒，一道数百英尺的滔天巨浪却席卷而来，巨大的冲击力几乎将游轮打了个底朝天！</P>
<P>　　瞬间，船上所有人员全变成自由落体，不是被撞向废墟便是被涌入的海水拖入深海，船梁崩塌、管道损毁、吊灯撞碎、<BR>火花四溅，船身顿时陷入一片漆黑和混乱。幸而坚固的舞会大厅还勉强维持形状，近百名幸存者算是侥幸逃过冲击大难，尽<BR>力维持镇定的船长发令让他们呆在船舱等待救援。</P>
<P>　　船舱不断下陷、海水一直涌入，与其坐以待毙不如主动出击，职业赌徒迪伦·琼斯决意赌一把，自己寻找出路。本想偷<BR>偷溜走，一个九岁小男孩康纳却哀求迪伦带上自己和母亲一起逃生，而前消防队员罗伯特·兰姆森为了寻找失散的女儿和女<BR>婿也要求和他一起上路。虽然不愿意被人拖累，迪伦还是不情愿地成了临时领导。要么在黑夜的大海和破碎的残骸中逃出生<BR>天，要么成为海神的祭品，他们已经没有多少时间！！</P>
<P>--------------------------&nbsp; 电影来源：www.eee4.com&nbsp;&nbsp; -------------------------------------</P>
<P>　　◇ 看点：海难加强版《泰坦尼克号》 </P>
<P>　　超豪华游轮、滔天灾难、生死一线之间，以海难名义击出重拳，难免让人扯到水下的泰坦尼克。然而对拥有特殊大片兼<BR>海洋情结的德国导演沃尔夫冈·彼特森来说，詹姆斯·卡梅隆在《泰坦尼克号》里表现的海难却实在有些太简单，凄凄美美<BR>的“你跳，我跳”显然不是他中意的题材。从开场后10分钟就进入壮烈船难场面的《海神号》，俨然是删去了荡气回肠爱情<BR>剧码的《泰坦尼克号》，磅礴的灾难效果和死命逃出生天的历险才是它的主题。</P>
<P>　　《海神号》的壮观沉没其实已经不是第一次，早在特技技术远不如今的24年前，被巨浪吞噬的同名巨轮就已经轰动一时<BR>，不仅成为影迷心中的海难片之冠，还获得8项奥斯卡提名。如今沉船再次航行在大西洋海面，由《完美风暴》的导演和幕<BR>后特效团队再度扬帆上船斗巨浪，1亿5千万美元投资幕后支持，轻车熟路之余，一场海难逃生的宏大视觉盛宴必然更加震撼<BR>人心！</P>
<P>--------------------------&nbsp; 电影来源：www.eee4.com&nbsp;&nbsp; -------------------------------------</P>
<P>　　◇点评：海神号风云再起 </P>
<P>　　每年夏天，好莱坞的大片雄心都会积极酝酿，可在经历了去年让制片公司摸不着头脑的观众走向之后，各大佬们也多少<BR>有点忐忑不安，为保险起见，他们对续集、翻拍搭卖明星和耗资高昂的电脑特效开始情有独钟，希望复兴之战可以换回远离<BR>电影院的观众热情。曾惊天地泣鬼神的《海神号》遇险，携船难风云榜首之位，自然也不能逃过再次劫难。</P>
<P>　　虽然布莱德·彼得的肌肉和绝世美人海伦的名声也没能拯救《特洛伊》，但导演沃尔夫冈·彼得森还是大片情结痴心不<BR>改，陆上艰险不如改走海路，至少曾经靠另一部海难片《完美风暴》达到事业顶峰的他，驾驭海中巨轮的能力不容置疑！配<BR>上几位甘愿在海水中摸爬滚打的演员，海神号完美巨浪计划就顺利出炉。</P>
<P>　　选取实景开拍的场面，自然能感受到更震撼人心的海难逃生效果；而为求切合现实中遇难的情况，尽量减少没必要的对<BR>白，单刀直入开始救人逃难的设置，也给予了影片更多呈现紧张视效的机会。问题是已经疲倦了视觉轰炸的观众们，还愿意<BR>进电影院看另一艘巨轮的震撼沉没么？！</P>
<P><IMG src="http://pic.piaohua.com/0701pic/allimg/080117/0352070.jpg" border=0></P>
<P>【电影截图】：<BR>电影来源：www.eee4.com<BR><IMG src="http://pic.piaohua.com/0701pic/allimg/080117/0352071.jpg" border=0><BR><IMG src="http://pic.piaohua.com/0701pic/allimg/080117/0352072.jpg" border=0><BR><IMG src="http://pic.piaohua.com/0701pic/allimg/080117/0352073.jpg" border=0><BR><IMG src="http://pic.piaohua.com/0701pic/allimg/080117/0352074.jpg" border=0><BR><IMG src="http://pic.piaohua.com/0701pic/allimg/080117/0352075.jpg" border=0><BR><IMG src="http://pic.piaohua.com/0701pic/allimg/080117/0352076.jpg" border=0></P><p>2008-01-17 03:48:12 开始连接......<br>2008-01-17 03:48:14 开始搜索候选资源......<br>2008-01-17 03:48:15 搜索到31个候选资源<br>2008-01-17 03:48:17 使用候选资源进行连接......<br>2008-01-17 03:48:20 搜索到26个候选资源<br>2008-01-17 03:48:23 使用候选资源进行连接......<br>2008-01-17 03:48:24 文件创建成功，开始下载数据......<br>2008-01-17 03:48:26 用户取消下载&nbsp;&nbsp; 本文来自 <a href="/index.html" target="_blank">www.eee4.com</a></p>
（直接可能无法下载，一律使用<a href="http://pstatic.xunlei.com/about/product/down_xl5.htm" target="_blank">迅雷下载</a>）<br>
真正DVD/2006票房灾难大片《海神号》DVD中字 － 来自[3E迅雷电影站eee4.com]下载地址：<IMG src="/templets/img/down.jpg" border=0><br>
<table style="BORDER-RIGHT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; BORDER-BOTTOM: #cccccc 1px dotted" cellspacing="0" cellpadding="6" width="95%" align="center" border="0">
    <tbody>
        <tr>
            <td style="WORD-WRAP: break-word" bgcolor="#fdfddf"><anchor></anchor><a href="ftp://eee4.com:eee4@xl3.eee4.com:8448/海神号/[3E迅雷电影站www.eee4.com]海神号DVD完美中字.rmvb" target="_blank">ftp://eee4.com:eee4@xl3.eee4.com:8448/海神号/[3E迅雷电影站www.eee4.com]海神号DVD完美中字.rmvb</a></td>
        </tr>
    </tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O164b2Z-4P36.jpg{/dede:field}
