{dede:field name='keywords'}72小时魔鬼追杀令BD1280高清中字{/dede:field}
{dede:field name='description'}72小时魔鬼追杀令BD1280高清中字迅雷下载、免费下载，72小时魔鬼追杀令BD1280高清中字Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}72小时魔鬼追杀令BD1280高清中字{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-10{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120508/23/17870980201205082310021573325782264_011.jpg" style="width: 600px" /></p>
<p>
	◎译　　名　72小时生死线<br />
	◎片　　名　The Crossing Guard<br />
	◎导　　演　西恩&middot;潘 Sean Penn<br />
	◎主　　演　杰克&middot;尼科尔森 Jack Nicholson ....Freddy Gale<br />
	　　　　　　大卫&middot;摩斯 David Morse ....John Booth<br />
	　　　　　　安杰丽卡&middot;休斯顿 Anjelica Huston ....Mary<br />
	　　　　　　罗宾&middot;怀特 Robin Wright ....Jojo (as Robin Wright)<br />
	　　　　　　派珀&middot;劳瑞 Piper Laurie ....Helen Booth<br />
	　　　　　　约翰&middot;萨维奇 John Savage ....Bobby<br />
	　　　　　　卡瑞&middot;伍尔 Kari Wuhrer ....Mia<br />
	　　　　　　石桥凌 Ryo Ishibashi ....Jefferey (as Ryo Ishabashi)<br />
	　　　　　　Richard Bradford ....Stuart Booth<br />
	　　　　　　普瑞斯西拉&middot;巴恩斯 Priscilla Barnes ....Verna<br />
	◎年　　代　1995<br />
	◎国　　家　美国<br />
	◎类　　别　剧情<br />
	◎语　　言　英语<br />
	◎IMDB评分&nbsp;&nbsp;6.3/10 (6,809 votes)<br />
	◎IMDB链接&nbsp;&nbsp;<a href="http://www.xiaozhizhu.net/" target="_blank">http://www.xiaozhizhu.net/</a><br />
	◎片　　长　118 mins 21 seconds<br />
	<br />
	◎简　　介　<br />
	<br />
	　　因酒醉驾车撞死一个小女孩，被判六年刑期的约翰&middot;布恩出狱了。从他跨出监狱大门的那一刻起，小女孩的父亲弗莱迪复仇的眼睛就盯上了他。六年前那悲惨的一幕无法从弗莱迪的记忆中抹去。他开着一家珠宝店，但大部分时间是在办公室里喝酒，晚上则出入色情场所，烂醉中与一些连名字都不知道的女人鬼混。就在这种恶性循环中他失去了妻子，幼儿，房子以致生活的勇气。现在他只想亲自动手，杀了肇事者出气。而约翰&middot;布恩也并未因服了六年刑而减轻罪恶感，他想的不是出狱后开始新生活，而是琢磨自己的生命还有什么价值。从某种意义上讲，他与弗莱迪是一体的两面。<br />
	&nbsp;</p>
<p>
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120508/23/17870980201205082310021573325782264_007.jpg" /></p>
<p>
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120508/23/17870980201205082310021573325782264_006.jpg" /></p>
<p>
	<br />
	&nbsp;</p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.net/movie/41667.html" target="_blank">http://www.xiaozhizhu.net/movie/41667.html</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy241:piaohua@117.41.229.29:2008/飘花电影piaohua.com72小时生死线BD1280高清中字.rmvb">ftp://dy241:piaohua@117.41.229.29:2008/飘花电影piaohua.com72小时生死线BD1280高清中字.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15a60F-2AH.jpg{/dede:field}
