{dede:field name='keywords'}镖客三部曲1：荒野大镖客BD中英{/dede:field}
{dede:field name='description'}镖客三部曲1：荒野大镖客BD中英双字1024/1280高清迅雷下载、免费下载，镖客三部曲1：荒野大镖客BD中英双字1024/1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}镖客三部曲1：荒野大镖客BD中英双字1024/1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-02-29{/dede:field}
{dede:field name='body'}<p>
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('/uploads/allimg/c120525/133O100XB0-102611.jpg');" src="/uploads/allimg/c120525/133O100XB0-102611.jpg" /><br />
	<br />
	◎译　　名　镖客三部曲1：荒野大镖客/独行侠连环夺命枪港<br />
	◎片　　名　Per un pugno di dollari<br />
	◎年　　代　1964<br />
	◎国　　家　意大利 西班牙 西德<br />
	◎类　　别　动作 西部<br />
	◎语　　言　英语<br />
	◎字　　幕　中英双字<br />
	◎IMDB评分 8.0/10 ( 33123票 )<br />
	◎IMDB链接 http://www.imdb.com/title/tt0058461<br />
	◎制作公司　Constantin Film Produktion GmbH [德国]<br />
	　　　　　　 Jolly Film [意大利]<br />
	　　　　　　 Ocean Films [西班牙]<br />
	◎文件格式　BD-RMVB<br />
	◎视频尺寸　1024 x 576<br />
	◎文件大小　1CD<br />
	◎片　　长　 01:39:54.411<br />
	◎导　　演　赛尔乔&middot;莱翁 Sergio Leone....European prints as Bob Robertson<br />
	　　　　　　 蒙特&middot;赫尔曼Monte Hellman....4new footage shot for American TV uncredited<br />
	◎编　　剧　菊岛隆三Ryuzo Kikushima....screenplay Yojimbo uncredited &amp;<br />
	　　　　　　 黑泽明Akira Kurosawa....screenplay Yojimbo uncredited<br />
	　　　　　　 赛尔乔&middot;莱翁Sergio Leone....story<br />
	　　　　　　 克林特&middot;伊斯特伍德Clint Eastwood<br />
	◎主　　演　克林特&middot;伊斯特伍德Clint Eastwood....Joe<br />
	　　　　　　 吉昂&middot;马利亚&middot;沃隆特Gian Maria Volont&eacute;....Ram&oacute;n Rojo as Johnny Wels<br />
	　　　　　　 玛丽安妮&middot;柯奇Marianne Koch....Marisol<br />
	　　　　　　 恩里克&middot;马里亚&middot;萨勒诺Enrico Maria Salerno....Italian-dubbed voice of Joe uncredited<br />
	　　　　　　 哈利&middot;戴恩&middot;斯坦通Harry Dean3e Stanton....Sheriff uncredited<br />
	<br />
	◎简　　介<br />
	<br />
	&nbsp; &nbsp; 本片讲述发生在墨西哥小镇上的故事，一位大镖客来到该镇，看到镇上的居民被两个大私枭，一个贩卖私械，一个贩卖私酒，弄得妻离子散，家破人亡。出于正义，他终于以其身手，弄得两派火并，把镇上的恶势力一网打尽，使镇上的居民回复了平静。克林特．伊斯特伍德扮演大镖客，演出极其精彩。导演瑟吉欧．莱昂内运用拍摄西部片贯用的手法执导此片，成为西部片中的经典之作。其风格承袭若干美式西部经典如＜日正当中＞的神采，但显然更受日本名导黑泽明的影响（将日本武士变身成西部枪手），不过整部作品的故事影像与音乐格调的原创色彩仍相当强烈。</p>
<p>
	【电影截图】：<br />
	<br />
	<br />
	<img alt="" src="/uploads/allimg/c120525/133O100YQ0-115119.jpg" /></p>
<p>
	<img alt="" src="/uploads/allimg/c120525/133O100Z560-125I1.jpg" /></p>
<br />
<p>
	[下载地址]：<img border="0" src="/uploads/allimg/c120525/133O0U345P-1W926.jpg" /></p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				ftp://3e:3e@d8.3edyy.com:162/【3E电影院www.eee4.cc】荒野大镖客BD中英双字1024x576高清版.rmvb</td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				ftp://dy44:piaohua@dy44.piaohua.com:2920/飘花电影piaohua.com荒野大镖客BD中英双字1280高清.rmvb</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O100914F-139133.jpg{/dede:field}
