<?php
$z[0]=Array("noteinfo","",0,161);
$z[0][4]['notename']="11,12";
$z[0][4]['channelid']="1";
$z[0][4]['macthtype']="string";
$z[0][4]['refurl']="http://";
$z[0][4]['sourcelang']="gb2312";
$z[0][4]['cosort']="asc";
$z[0][4]['isref']="no";
$z[0][4]['exptime']="10";
$z[0][4]['usemore']="1";
$z[1]=Array("listrule","\r\n    {dede:addurls}{/dede:addurls}\r\n    {dede:batchrule}[(#)=>http://www.piaohua.com/html/lianxuju/list_(*).html; (*)=>1-1; typeid=>11]\r\n[(#)=>http://www.piaohua.com/html/dongman/list_(*).html; (*)=>1-1; typeid=>12]\r\n{/dede:batchrule}\r\n    {dede:regxrule}{/dede:regxrule}\r\n    {dede:areastart}<div id=\"list\">{/dede:areastart}\r\n    {dede:areaend}</div>{/dede:areaend}\r\n",163,706);
$z[1][4]['sourcetype']="batch";
$z[1][4]['rssurl']="http://";
$z[1][4]['regxurl']="(#)";
$z[1][4]['startid']="1";
$z[1][4]['endid']="";
$z[1][4]['addv']="1";
$z[1][4]['urlrule']="area";
$z[1][4]['musthas']="";
$z[1][4]['nothas']="";
$z[1][4]['listpic']="1";
$z[1][4]['usemore']="1";

?>