<?php
$z[0]=Array("field","虎阵战地/猛虎营/老虎连[BD中字1",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","虎阵战地/猛虎营/老虎连[BD中字1024x576高清版]迅雷下载、免费下载，虎阵战地/猛虎营/老虎连[BD中字1024x576高清版]Gvod高清在线播放，剧情介绍等。",73,255);
$z[1][4]['name']="description";
$z[2]=Array("field","虎阵战地/猛虎营/老虎连[BD中字1024x576高清版]",257,339);
$z[2][4]['name']="title";
$z[3]=Array("field","",341,380);
$z[3][4]['name']="writer";
$z[4]=Array("field","",382,421);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-05-12",423,473);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",475,512);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://3e:3e@m3.3edyy.com:529/【3E看看www.3ekk.com】虎阵战地BD中字1024x576高清版.rmvb\" target=_blank>ftftp://3e:3e@m3.3edyy.com:529/【3E看看www.3ekk.com】虎阵战地BD中字1024x576高清版.rmvb</A></TD></TR></TBODY></TABLE></div><ul class=\"mmlist",514,792);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MP64R30-1R53.jpg",794,876);
$z[8][4]['name']="litpic";

?>