<?php
$z[0]=Array("field","毕业生迅雷下载，免费下载，Gvod",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","毕业生迅雷下载、免费下载，毕业生Gvod高清在线播放，剧情介绍等。",73,179);
$z[1][4]['name']="description";
$z[2]=Array("field","毕业生",181,225);
$z[2][4]['name']="title";
$z[3]=Array("field","",227,266);
$z[3][4]['name']="writer";
$z[4]=Array("field","",268,307);
$z[4][4]['name']="source";
$z[5]=Array("field","2007-01-03",309,359);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","导　　演：迈克&middot;尼科尔斯 Mike Nichols<br />主　　演：达斯丁&middot;霍夫曼 Dustin Hoffman<br />　　 　　 安妮&middot;班克罗夫特 Anne Bancroft<br />　　 　　 凯瑟琳&middot;罗斯 Katharine Ross<br />　　 　　 威廉&middot;丹尼尔斯 William Daniels<br />　　 　　 默里&middot;汉密尔顿 Murray Hamilton<br />类　　型：剧情/喜剧/爱情<br />片　　长：105分钟<br />年　　代：1967年<br />国　　家：美国<br />&ldquo;说它让人印象深刻还不够，也许有人认为它影响了整整一代人的说法更准确，这是个奇迹。&rdquo;<br />http://ebook.nbtvu.net.cn/dlib/dlib/movie/content/临时电影/故事片/毕业生/毕业生1.rm<br />http://ebook.nbtvu.net.cn/dlib/dlib/movie/content/临时电影/故事片/毕业生/毕业生2.rm<br />2006-12-15 21:22:59 开始连接......<br />2006-12-15 21:22:59 开始搜索候选资源......<br />2006-12-15 21:23:04 搜索到51个候选资源<br />2006-12-15 21:23:04 使用候选资源进行连接......<br />2006-12-15 21:24:03 使用候选资源进行连接......<br />2006-12-15 21:24:25 开始下载数据......",361,1350);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c120525/133O160c20-21058.jpg",1352,1435);
$z[7][4]['name']="litpic";

?>