{dede:field name='keywords'}POWER星期天-20110821下载迅雷下{/dede:field}
{dede:field name='description'}POWER星期天-20110821下载迅雷下载、免费下载，POWER星期天-20110821下载Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}POWER星期天-20110821下载{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-08-22{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="/uploads/allimg/c120524/133N42L1M0-3b349.jpg" /></p>

<p>
	　《Power星期天/Power Sunday》 是2008-07-20开始第一期，由吴宗宪主持的新节目。</p>
<p>
	&nbsp;<br />
	　　英文名称：Power Sunday</p>
<p>
	&nbsp;<br />
	　　首播时间：2008年7月20日</p>
<p>
	&nbsp;<br />
	　　电视台：华视</p>
<p>
	&nbsp;<br />
	　　主持人：吴宗宪</p>
<p>
	&nbsp;<br />
	　　地区：台湾</p>
<p>
	&nbsp;<br />
	　　语言：普通话</p>
<p>
	&nbsp;<br />
	节目单元<br />
	　　节目共分两个单元,</p>
<p>
	&nbsp;<br />
	　　one. 案发现场</p>
<p>
	&nbsp;<br />
	　　〈案发现场〉是开放家庭报名的游戏单元，副标题为〈躲猫猫〉。</p>
<p>
	&nbsp;<br />
	　　报名者与制作单位联手，於报名者所在的住所范围内「设计」好8个「找碴题」，以前会在没人注意的地方隐匿三位成员，现在已取消，全部变成疑点。总计8个疑点；另外，还</p>
<p>
	<br />
	会额外增加一些大头娃娃来干扰参赛者。</p>
<p>
	&nbsp;<br />
	　　每次邀请两位艺人或一个艺人团体参赛，参赛者称为「探员」。只要参赛者能够於三十分钟内没有完全找到这8个疑点，</p>
<p>
	&nbsp;<br />
	　　该家庭或公司行号即可获得制作单位准备的奖金新台币六万元。</p>
<p>
	&nbsp;<br />
	　　参赛者宣称发现疑点时，无论是否真的找到疑点，助理主持人都要暂停计时，直到主持人宣布继续计时；</p>
<p>
	&nbsp;<br />
	　　此时参赛者必须明确说明可疑之处何在，答错者会被主持人以警棍打屁股。每找到一个疑点，都可称为「破案」。</p>
<p>
	&nbsp;<br />
	　　报名者（被隐匿的成员除外）要坐在住所内的特定位置，这个位置称</p>
<p>
	<br />
	为「基地台」，基地台内绝对不会存在任何疑点。(明道和蒋怡那一集有例外，有一名男人装成女人）</p>
<p>
	&nbsp;<br />
	　　two.</p>
<p>
	&nbsp;<br />
	　　这部分是又几个明星家庭来完成一些任务,也就是进 行几项游戏,而且赢的家庭会得到奖金,因为有宪哥和可 爱的柯以柔，增加了可看性</p>
<p>
	[下载地址]： &nbsp;<img border="0" src="/uploads/allimg/c120524/133N2Z4FF-102231.jpg" /></p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy171:piaohua@dy171.piaohua.com:1022/飘花电影piaohua.comPOWER星期天-20110703.rmvb</td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy171:piaohua@dy171.piaohua.com:1022/飘花电影piaohua.comPOWER星期天-20110710.rmvb</td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy171:piaohua@dy171.piaohua.com:1022/飘花电影piaohua.comPOWER星期天-20110717.rmvb</td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:1110/飘花电影piaohua.comPOWER星期天-20110724.rmvb</td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:1174/飘花电影piaohua.comPOWER星期天-20110731.rmvb</td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:1363/飘花电影piaohua.comPOWER星期天-20110821.rmvb</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120524/133N42L3250-40JA.jpg{/dede:field}
