<?php
$z[0]=Array("field","田馥甄《Love!,To,Hebe》音乐会[",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","田馥甄《Love! To Hebe》音乐会[无水印]迅雷下载、免费下载，田馥甄《Love! To Hebe》音乐会[无水印]Gvod高清在线播放，剧情介绍等。",73,241);
$z[1][4]['name']="description";
$z[2]=Array("field","田馥甄《Love! To Hebe》音乐会[无水印]",243,318);
$z[2][4]['name']="title";
$z[3]=Array("field","",320,359);
$z[3][4]['name']="writer";
$z[4]=Array("field","",361,400);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-12-10",402,452);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",454,491);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://5e:5e@d6.3edyy.com:604/【3E看看www.3ekk.com】田馥甄《Love!%20To%20Hebe》音乐会[无水印]CD1.rmvb\" target=_blank>ftftp://5e:5e@d6.3edyy.com:604/【3E看看www.3ekk.com】田馥甄《Love! To Hebe》音乐会[无水印]CD1.rmvb</A></TD></TR></TBODY></TABLE>CD2：<BR>\r\n<TABLE style=\"BORDER-BOTTOM: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-RIGHT: #cccccc 1px dotted\" border=0 cellSpacing=0 cellPadding=6 width=\"95%\" align=center>\r\n<TBODY>\r\n<TR>\r\n<TD style=\"WORD-WRAP: break-word\" bgColor=#fdfddf><A href=\"ftftp://5e:5e@d6.3edyy.com:604/【3E看看www.3ekk.com】田馥甄《Love!%20To%20Hebe》音乐会[无水印]CD2.rmvb\" target=_blank>ftftp://5e:5e@d6.3edyy.com:604/【3E看看www.3ekk.com】田馥甄《Love! To Hebe》音乐会[无水印]CD2.rmvb</A></TD></TR></TBODY></TABLE></div><ul class=\"mmlist",493,1363);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MQ450060-35438.jpg",1365,1449);
$z[8][4]['name']="litpic";

?>