<?php
$z[0]=Array("field","洪吉童2084,HD中字1024高清最新",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","洪吉童2084 HD中字1024高清最新韩国动画冒险大片迅雷下载、免费下载，洪吉童2084 HD中字1024高清最新韩国动画冒险大片Gvod高清在线播放，剧情介绍等。",72,256);
$z[1][4]['name']="description";
$z[2]=Array("field","洪吉童2084 HD中字1024高清最新韩国动画冒险大片",258,341);
$z[2][4]['name']="title";
$z[3]=Array("field","",343,382);
$z[3][4]['name']="writer";
$z[4]=Array("field","",384,423);
$z[4][4]['name']="source";
$z[5]=Array("field","2012-04-06",425,475);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",477,514);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://dy44:piaohua@dy44.piaohua.com:3154/飘花电影piaohua.com洪吉童2084 DVD中字.rmvb",516,638);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MQ132Y0-114D.jpg",640,722);
$z[8][4]['name']="litpic";

?>