{dede:field name='keywords'}匹夫/匹夫们的战争TC清晰版国语{/dede:field}
{dede:field name='description'}匹夫/匹夫们的战争TC清晰版国语中字2012中国战争迅雷下载、免费下载，匹夫/匹夫们的战争TC清晰版国语中字2012中国战争Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}匹夫/匹夫们的战争TC清晰版国语中字2012中国战争{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-21{/dede:field}
{dede:field name='body'}<p>
	<img border="0" src="/uploads/allimg/c120525/133O092043F-141J7.jpg" /></p>
<p>
	<img border="0" src="/uploads/allimg/c120525/133O09205640-153953.jpg" /></p>
<p>
	<img border="0" src="/uploads/allimg/c120525/133O0920BF-1Ba3.jpg" /></p>
<p>
	<img border="0" src="/uploads/allimg/c120525/133O0920L10-1MQ1.jpg" /></p>
<p>
	<img border="0" src="/uploads/allimg/c120525/133O0920V30-1R408.jpg" /></p>
<p>
	<img border="0" src="/uploads/allimg/c120525/133O092095F-1941D.jpg" /></p>
<p>
	导演: 杨树鹏<br />
	编剧: 杨树鹏 / 张小北 / 老晃<br />
	主演: 黄晓明 / 张译 / 张歆艺 / 王烈 / 包小柏 / 倪景阳 / 马志明 / 孙磊 / 张粤 / 高群书 / 梁静 / 江珊 / 李子雄<br />
	类型: 剧情 / 战争 / 西部<br />
	制片国家/地区: 中国大陆<br />
	语言: 汉语普通话<br />
	上映日期: 2012-04-23(中国大陆)<br />
	片长: 105分钟<br />
	又名: 匹夫们的战争 / 匹夫有责 / An Inaccurate Memoir<br />
	官方网站：http://www.bluemv.com<br />
	<br />
	<br />
	剧情简介<br />
	<br />
	　　匪帮首领方有望（黄晓明 饰）绑架了一个新郎官高栋梁（张译 饰），高栋梁的铁血顽强打动了匪帮的&ldquo;小姑奶奶&rdquo;方梓珍（张歆艺 饰），可是，没有人知道，高栋梁不仅仅是一个肉票那么简单&hellip;&hellip;<br />
	<br />
	<br />
	◎影片剧照</p>
<p>
	<img border="0" src="/uploads/allimg/c120525/133O09210520-20KT.jpg" /><br />
	<br />
	<img border="0" src="/uploads/allimg/c120525/133O092114F-212200.jpg" /><br />
	<br />
	<img border="0" src="/uploads/allimg/c120525/133O09212440-2259B.jpg" /><br />
	<br />
	<img border="0" src="/uploads/allimg/c120525/133O09213310-23B52.jpg" /><br />
	<br />
	<img border="0" src="/uploads/allimg/c120525/133O092141F-24Y15.jpg" /><br />
	<br />
	<img border="0" src="/uploads/allimg/c120525/133O09215120-25P16.jpg" /><br />
	<br />
	<img border="0" src="/uploads/allimg/c120525/133O09215910-2DC8.jpg" /><br />
	&nbsp;</p>
<p>
	&nbsp;<img border="0" src="/uploads/allimg/c120525/133O0921CF-2M1L.jpg" /></p>
<p>
	<img border="0" src="/uploads/allimg/c120525/133O0921J0-2QR0.jpg" /></p>
<p>
	<img border="0" src="/uploads/allimg/c120525/133O0921O50-2a562.jpg" /></p>
<p>
	<img border="0" src="/uploads/allimg/c120525/133O0921TZ-3045F.jpg" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="/uploads/allimg/c120525/133O0T31310-42214.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：http://www.xiaozhizhu.net</td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:3280/飘花电影piaohua.com匹夫们的战争TS国语中字.rmvb</td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:3297/飘花电影piaohua.com匹夫们的战争TC清晰版国语中字.rmvb</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O09219130-311Y7.jpg{/dede:field}
