<?php
$z[0]=Array("field","全金属外壳BD中英双字1024/1280",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","全金属外壳BD中英双字1024/1280高清迅雷下载、免费下载，全金属外壳BD中英双字1024/1280高清Gvod高清在线播放，剧情介绍等。",72,232);
$z[1][4]['name']="description";
$z[2]=Array("field","全金属外壳BD中英双字1024/1280高清",234,305);
$z[2][4]['name']="title";
$z[3]=Array("field","",307,346);
$z[3][4]['name']="writer";
$z[4]=Array("field","",348,387);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-10-08",389,439);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",441,478);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://e63:e63@xl2.eee4.com:1003/[3E电影站www.eee4.com]全金属外壳[DVD中英双字1024x576高清版]CD1.rmvb\" target=\"_blank",480,634);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MP5511F-4H57.jpg",636,718);
$z[8][4]['name']="litpic";

?>