{dede:field name='keywords'}全金属外壳BD中英双字1024/1280{/dede:field}
{dede:field name='description'}全金属外壳BD中英双字1024/1280高清迅雷下载、免费下载，全金属外壳BD中英双字1024/1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}全金属外壳BD中英双字1024/1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-10-08{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://e63:e63@xl2.eee4.com:1003/[3E电影站www.eee4.com]全金属外壳[DVD中英双字1024x576高清版]CD1.rmvb" target="_blank{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MP5511F-4H57.jpg{/dede:field}
