{dede:field name='keywords'}如果723/谨以此纪念7.23温州动车{/dede:field}
{dede:field name='description'}如果723/谨以此纪念7.23温州动车事故中的遇难者迅雷下载、免费下载，如果723/谨以此纪念7.23温州动车事故中的遇难者Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}如果723/谨以此纪念7.23温州动车事故中的遇难者{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-09-17{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img165.poco.cn/mypoco/myphoto/20110916/12/62564813201109161212446298315793901_000.jpg" style="width: 400px; height: 565px" /></p>
<p>
	谨以此纪念2011.7.23温州动车事故中的遇难者</p>
<p>
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 出品人：张华<br />
	　　监　制：阚迪<br />
	　　导　演：蓝海涛<br />
	　　演员表：徐若琪、王婧、郭冰菱、黄诗杰、马媛、郭延滨、熊亮、阚迪、马汉毅、喻引娣、李卉<br />
	　　制片人：吴瑕、阚迪<br />
	　　编　剧：阚迪<br />
	　　摄　影：彭斯博<br />
	　　美术指导：吴海羽<br />
	　　统　筹：何志东、刘津津<br />
	　　剪　辑：杨创强、李晶<br />
	　　网络企宣：洪叶<br />
	　　公映时间：2011年9月9日尾七祭奠<br />
	故事介绍<br />
	　　这是一场天道的浩劫，这是一场悲痛的记忆，一个大众永远无法忘怀的黑色星期六&mdash;2011年7月23日。<br />
	　　《如果723》是一部为了祭奠2011年7月23日温州动车追尾事件受难者以及其家属的网络微电影，为祭奠痛苦离世的罹难者，根据真人真事就地取材改编成的网络微电影，用最真实的情感、粉碎混乱的现场纪录惨痛悲戚的无可奈何，带着感恩与珍惜的启示，用画面沉重悼念罹难人群。那些泣不成声的悲痛，那些双膝跪地的苦苦央求，那些时光无法倒流的&hellip;&hellip;如果！<br />
	剧中歌曲<br />
	　　主题曲：《如果723》<br />
	　　作　曲：罗中旭<br />
	　　演　唱：罗中旭　吴 瑕<br />
	　　片尾曲：《如果可以重来》<br />
	　　词　曲：黄诗杰<br />
	　　演　唱：黄诗杰 珊 子<br />
	我们不用眼泪动容，我们来用画面祭奠<br />
	　　本剧由出品人张华先生独立投资，澳亚卫视主持人阚迪小姐联手广东卫视主持人吴瑕小姐总制片，嘻嘻tv视频工作室团队联袂打造，用我们的行动来为公益慈善事业做出一份微薄的贡献，借以此片祭奠723事件。<br />
	　　集合新加坡、中国内地，香港地区、台湾地区等地的影视新星黄诗杰、延斌、邵伟轩，华娱卫视、澳亚卫视各大知名电视媒体主持人联袂出演，零片酬的纯公益慈善微电影于2011年8月10日在广州开机，在出品人张华先生和总制片阚迪以及吴瑕小姐的带领下，剧组全身心投注最真挚的情感倾力打造，必将为观众呈现一部充满爱的网络微电影《如果723》。</p>
<p>
	<img alt="" src="http://img165.poco.cn/mypoco/myphoto/20110917/08/62564813201109170838246155214866217_001.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img165.poco.cn/mypoco/myphoto/20110917/08/62564813201109170838246155214866217_000.jpg" style="width: 720px; height: 405px" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="&#13;&#10;ftp://dy125:piaohua@dy125.piaohua.com:3046/飘花电影piaohua.com如果723HD高清国语中字720P.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:3046/飘花电影piaohua.com如果723HD高清国语中字720P.rmvb </a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15115B0-23101.jpg{/dede:field}
