{dede:field name='keywords'}杀生DVD国语中字2012最新上映黄{/dede:field}
{dede:field name='description'}杀生DVD国语中字2012最新上映黄渤、苏有朋、任达华悬疑喜剧大片迅雷下载、免费下载，杀生DVD国语中字2012最新上映黄渤、苏有朋、任达华悬疑喜剧大片Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}杀生DVD国语中字2012最新上映黄渤、苏有朋、任达华悬疑喜剧大片{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-01{/dede:field}
{dede:field name='body'}<p>
	&nbsp;<img src="http://img170.poco.cn/mypoco/myphoto/20120428/09/56643687201204280946302350222329734_006.jpg" /></p>

<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120428/09/56643687201204280946302350222329734_005.jpg" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120428/09/56643687201204280946302350222329734_004.jpg" /></p>
<p>
	导演: 管虎<br />
	编剧: 管虎<br />
	主演: 黄渤 / 苏有朋 / 余男 / 任达华 / 马精武 / 梁静 / 王迅<br />
	类型: 剧情 / 喜剧 / 悬疑 / 惊悚<br />
	制片国家/地区: 中国大陆<br />
	语言: 汉语普通话 / 四川话<br />
	上映日期: 2012-04-28(中国大陆)<br />
	片长: 109分钟<br />
	又名: Design Of Death<br />
	IMDb链接: tt2290645</p>
<p>
	<br />
	剧情简介</p>
<p>
	　　中国西南、与世隔绝、群山环抱中有个寨子，是个人皆长寿、规矩自成之地，清时皇帝赐名&ldquo;长寿镇&rdquo;。某日突爆传染病，地方官派医生（任达华 饰）前往诊治，他在镇子外发现奄奄一息的牛结实（黄渤 饰）。进寨后，往日温厚的村民一反常态，不仅对牛结实拒施援手、避若瘟疫，更迁怒于医生多管闲事，老镇长（马精武 饰）亲自带着长寿镇医生（苏有朋 饰）和接生婆（梁静 饰）、油漆匠，老族长等人千万百计的阻挠医生对牛结实的救援，牛结实最终没能被救活，医生也找不到此人暴毙的原因。镇民们对医生的不欢迎不合作态度，令医生很沮丧，正当他准备离开的时候，无意中发现了一个被全镇民众一起隐藏在山崖上的一个秘密，带着重重疑惑医生决定暗中走访长寿镇，直到他偶遇一个男孩，长寿镇迷案的真相才一步步揭开&hellip;&hellip;<br />
	　　该片改编自陈铁军的中篇小说《设计死亡》。</p>
<p>
	<br />
	◎影片截图</p>
<p>
	&nbsp;</p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120430/18/56643687201204301819201921330019718_000.jpg" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120430/18/56643687201204301819201921330019718_003.jpg" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120430/18/56643687201204301819201921330019718_001.jpg" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120430/18/56643687201204301819201921330019718_002.jpg" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.netftp://dy44:piaohua@dy44.piaohua.com:3251/" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3325/飘花电影piaohua.com杀生DVD国语中字.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3325/飘花电影piaohua.com杀生DVD国语中字.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15HR50-3G56.jpg{/dede:field}
