{dede:field name='keywords'}春娇与志明/志明与春娇2粤语高清{/dede:field}
{dede:field name='description'}春娇与志明/志明与春娇2粤语高清迅雷下载、免费下载，春娇与志明/志明与春娇2粤语高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}春娇与志明/志明与春娇2粤语高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-04-24{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://i.imgur.com/HFoH6.jpg" style="width: 700px; height: 985px" /></p>
<p>
	导演: 彭浩翔<br />
	编剧: 彭浩翔 / 陆以心<br />
	主演: 杨千嬅 / 余文乐 / 杨幂 / 徐峥 / 谷德昭 / 郑伊健 / 陈逸宁 / 司徒慧焯 / 黄晓明 / 詹瑞文 / 田蕊妮 / 王馨平 / 郝蕾 / 谷祖琳 / 王太利 / 邵音音 / 曾国祥 / 尹志文 / 彭浩翔 / 魏雨琦 / 林兆霞<br />
	类型: 剧情 / 喜剧 / 爱情<br />
	官方网站: www.mediaasia.com/loveinthebuff<br />
	制片国家/地区: 香港 / 中国大陆<br />
	语言: 粤语 / 汉语普通话<br />
	上映日期: 2012-03-29(香港) / 2012-03-30(中国大陆)<br />
	片长: 111分钟<br />
	<br />
	又名: 志明与春娇2 / Love in The Buff<br />
	IMDb链接: tt2238839<br />
	<br />
	春娇与志明的剧情简介 &nbsp; &middot; &middot; &middot; &middot; &middot; &middot;<br />
	　　张志明（余文乐 饰）与余春娇（杨千嬅 饰）在一起后，恋情也不可避免由热烈转向平淡，几番龃龉过后，二人平平淡淡、不知不觉地分手了。在此之后，志明接受前老板的邀请，和公公前往北京发展，他很快结识了美丽温柔的空姐尚优优（杨幂 饰），一段新的恋情由此展开。另一方面，春娇的化妆品牌决定关掉香港分店，于是她也和娥姐转战北京。曾经的恋人相见自是几多尴尬，而原以为早已平淡和忘却的情感竟在见面的一刻复萌。虽然志明有优优陪伴，春娇也意外邂逅了体贴稳重的SAM（徐峥 饰），但是他们仍然瞒着另一半偷偷见面，他们小心地保持着距离，心又不由自主地向对方靠近。<br />
	　　已是从香港转战北京的爱情，将如何收场&hellip;&hellip;</p>
<p>
	<img alt="" src="http://i.imgur.com/YDJKg.jpg" style="width: 650px; height: 366px" /><img alt="" src="http://i.imgur.com/neuXN.jpg" style="width: 650px; height: 366px" /><img alt="" src="http://i.imgur.com/6kYdf.jpg" style="width: 650px; height: 366px" /><br />
	<br />
	&nbsp;</p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.net/" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy125:piaohua@dy125.piaohua.com:7885/飘花电影piaohua.com春娇与志明HD粤语中字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:7885/飘花电影piaohua.com春娇与志明HD粤语中字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15U52P-49326.jpg{/dede:field}
