<?php
$z[0]=Array("field","地动天摇[DVD中英双字]迅雷下载",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","地动天摇[DVD中英双字]迅雷下载、免费下载，地动天摇[DVD中英双字]Gvod高清在线播放，剧情介绍等。",72,208);
$z[1][4]['name']="description";
$z[2]=Array("field","地动天摇[DVD中英双字]",210,269);
$z[2][4]['name']="title";
$z[3]=Array("field","",271,310);
$z[3][4]['name']="writer";
$z[4]=Array("field","",312,351);
$z[4][4]['name']="source";
$z[5]=Array("field","2009-07-30",353,403);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",405,442);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://4e:4e@www2.eee4.com:643/[www.eee4.cn提供]地动天摇DVD中英双字.rmvb\" target=\"_blank",444,570);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MPW1340-14919.jpg",572,655);
$z[8][4]['name']="litpic";

?>