{dede:field name='keywords'}绑架/在劫难逃/喋血新世纪BD1280{/dede:field}
{dede:field name='description'}绑架/在劫难逃/喋血新世纪BD1280高清迅雷下载、免费下载，绑架/在劫难逃/喋血新世纪BD1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}绑架/在劫难逃/喋血新世纪BD1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-23{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://t.williamgates.net/image-3390_4EEC4C4D.jpg" style="width: 395px; height: 499px" /></p>
<p>
	◎译　　名　绑架<br style="word-wrap: break-word" />
	◎片　　名　Abduction&nbsp;<br style="word-wrap: break-word" />
	◎年　　代　2011<br style="word-wrap: break-word" />
	◎国　　家　美国<br style="word-wrap: break-word" />
	◎类　　别　动作/剧情/神秘/惊悚<br style="word-wrap: break-word" />
	◎语　　言　英语<br style="word-wrap: break-word" />
	◎IMDB评分　4.2/10 (9,636 votes)<br style="word-wrap: break-word" />
	◎IMDB链接　<a href="http://www.imdb.com/title/tt1600195/" style="word-wrap: break-word; color: rgb(51,102,153); text-decoration: underline" target="_blank">http://www.imdb.com/title/tt1600195/</a><br style="word-wrap: break-word" />
	◎片　　长　97 mins<br style="word-wrap: break-word" />
	◎导　　演　约翰&middot;辛格顿 John Singleton<br style="word-wrap: break-word" />
	◎主　　演　泰勒&middot;洛特纳 Taylor Lautner ....Nathan<br style="word-wrap: break-word" />
	　　　　　　莉莉&middot;科林斯 Lily Collins ....Karen<br style="word-wrap: break-word" />
	　　　　　　阿尔弗雷德&middot;莫里纳 Alfred Molina ....Frank Burton<br style="word-wrap: break-word" />
	　　　　　　詹森&middot;艾萨克 Jason Isaacs ....Kevin<br style="word-wrap: break-word" />
	　　　　　　玛丽亚&middot;贝罗 Maria Bello ....Mara<br style="word-wrap: break-word" />
	　　　　　　迈克尔&middot;恩奎斯特 Michael Nyqvist ....Kozlow<br style="word-wrap: break-word" />
	　　　　　　西格妮&middot;韦弗 Sigourney Weaver ....Dr. Bennett<br style="word-wrap: break-word" />
	　　　　　　Antonique Smith ....Sandra Burns<br style="word-wrap: break-word" />
	　　　　　　丹泽尔&middot;惠特克 Denzel Whitaker ....Gilly<br style="word-wrap: break-word" />
	　　　　　　Nickola Shreli ....Alec<br style="word-wrap: break-word" />
	　　　　　　Allen Williamson ....Billy<br style="word-wrap: break-word" />
	　　　　　　William Peltz ....Jake<br style="word-wrap: break-word" />
	　　　　　　伊丽莎白&middot;罗姆 Elisabeth Rohm ....Lautner<br style="word-wrap: break-word" />
	　　　　　　Roger Guenveur Smith ....Mr. Miles<br style="word-wrap: break-word" />
	　　　　　　Monica Ciszczon ....International Traveler at London Airport<br style="word-wrap: break-word" />
	　　　　　　Bryan Friday ....Brighton Beach<br style="word-wrap: break-word" />
	　　　　　　Jack Erdie ....Short Sleeves<br style="word-wrap: break-word" />
	　　　　　　David Barckhoff ....Train Passenger<br style="word-wrap: break-word" />
	　　　　　　Jeffrey Jones ....Police Officer<br style="word-wrap: break-word" />
	　　　　　　Ken Arnold ....Thermal<br style="word-wrap: break-word" />
	　　　　　　Kirk Kelly ....Student<br style="word-wrap: break-word" />
	　　　　　　Robert Brown ....CIA Agent Brendan Webb<br style="word-wrap: break-word" />
	　　　　　　Mark Nearing ....Brighton Beach 1<br style="word-wrap: break-word" />
	　　　　　　Radick Cembrzynski ....Kozlow&#39;s Tech<br style="word-wrap: break-word" />
	　　　　　　Doug Michaels ....Party Boy<br style="word-wrap: break-word" />
	　　　　　　Adam Stanley ....CIA SWAT Team Leader<br style="word-wrap: break-word" />
	　　　　　　Andre Flixx ....Student<br style="word-wrap: break-word" />
	<br style="word-wrap: break-word" />
	影片介绍<br style="word-wrap: break-word" />
	<br style="word-wrap: break-word" />
	　　20岁出头的年轻人尼敦（泰勒&middot;洛特纳饰）拥有一个看上去颇为完美的家庭，从小他生活在一个幸福的环境当中，不过自懂事起，尼敦总觉得自己过着形同虚设的生活，直到有一天他无意在失踪人口的网页里看到有人在寻找自己，盯着显示器里自己幼年的照片，尼敦才明白自己朝夕相处的&ldquo;双亲&rdquo;，竟然另有特殊身份，尼敦这才明白原来20多年来，自己一直活在一个精心编织的谎言当中。<br style="word-wrap: break-word" />
	<br style="word-wrap: break-word" />
	　　尼敦准备查明真相，他清楚自己所谓的&ldquo;父母&rdquo;根本信不过，于是他只能将这一切告诉邻居凯伦（莉莉&middot;科林斯饰）。正当尼敦和凯伦想搞清楚这是怎么一回事时，却意外的遭遇了职业杀手的追杀，他的&ldquo;父母&rdquo;在自己的眼前被害，警察把他当成凶手来追捕，于是尼敦和凯伦只能开始了惊心动魄的逃亡生涯，而他也在逃亡当中，离真相越来越近&hellip;&hellip;<br style="word-wrap: break-word" />
	<br style="word-wrap: break-word" />
	幕后制作<br style="word-wrap: break-word" />
	<br style="word-wrap: break-word" />
	　　寻找迷失的身份<br style="word-wrap: break-word" />
	<br style="word-wrap: break-word" />
	　　《绑架》拥有一个听上去并不起眼的片名，不过内里的故事倒还算得上是吸引观众：一个家境优越的年轻人，突然有一天发现自己的照片竟然出现在寻找失踪人口的网站上，原来自己并且父母亲生，而一切真相都隐藏着一个巨大的阴谋后面&hellip;&hellip;这个听上去有些像是《楚门的世界》＋《谍影重重》的青春偶像版的故事，谈及创作初衷，编剧肖恩&middot;克里斯汀森说道：&ldquo;其实这个故事源自于有一天我在一个寻找失踪人口的网站上浏览，这是我无意点击进去的一个网站，我本来只是想随便看看，但看下去之后，感觉非常震惊。我没有想到会有那么多失踪的人，他们的父母、亲人是如此的焦急，对每个失踪对象的描述，那样的细致入微。我觉得每张照片背后，都有一段故事，所以从那个时候开始，我就开始构思一个从失踪人口网站引发的悬疑故事。而一年多以后，《绑架》的剧本终于写完了，这个故事和我起初设想的已经有了很大的区别，但是和失踪人口网站有关的这一点元素并没有改变，整个故事都是因为主角登陆了网站而开始，随后，发生了很多主角无法控制的事情，他会发觉，原来自己一直生活在一个谎言里，于是他要开始和对抗这个谎言，并寻找自己真实的身份，故事也就展开了。&rdquo;<br style="word-wrap: break-word" />
	<br style="word-wrap: break-word" />
	　　执导《绑架》的约翰&middot;辛格顿外形是一个不折不扣的黑人硬汉，而他执导的电影也多是以标榜男性的热血为主，他曾执导过《速度与激情2》《四兄弟》等动作片，谈及这次执导的新作《绑架》，约翰&middot;辛格顿说道：&ldquo;这是一部悬疑元素为主、动作元素为辅的电影，吸引我执导这部电影的是因为本片的故事，它在同类型的电影里显得有些特别。《绑架》的主角是一个年轻人，他生活在一个看上去非常优越舒适的中产家庭里，看上去这个年轻人和当下其他的小伙子并没有什么特别的，但当他打开一个失踪人口网站的时候，他的命运发生了天翻地覆的变化，随后他开始卷进一桩巨大的阴谋里，接二连三的动作场面在他追寻真相的过程里呈现。这是一个普通人和命运抗争的故事，在前半段，我特地融入了一些青春偶像电影的套路，但在后半段，整个故事变成了传统的悬疑动作类型片，这种反差会比较有趣，也显得更加的戏剧化。整体而言，我希望这部电影能够在这类类型片里做出一些不同的尝试，让观众感觉到一些新意，并且让观众看完之后会问自己，&lsquo;如果你的一生活在一个谎言里，当你发现之后，你会有勇气去战斗，去抗争吗？&rsquo;影片里的主人公给出了他的答案，而我相信观众们也会有自己的选择。&rdquo;<br style="word-wrap: break-word" />
	<br style="word-wrap: break-word" />
	　　本片在风格上很容易让人想起《谍影重重》等走冷硬写实路线的动作片，那么《绑架》是否在风格上刻意的贴近这类电影呢？对于这一点，称得上是动作片专业户的约翰&middot;辛格顿并不讳言：&ldquo;我本身是非常喜欢动作片的，我曾经拍摄过许多动作电影，我希望在每部动作片里，都能带给观众一些新的感觉。《谍影重重》系列对于每一个喜欢动作片的观众并不会陌生，这是一部值得影迷反复观看的佳作，而我觉得《谍影重重》的确能给我许多宝贵的经验。《绑架》的故事很严肃，《谍影重重》也很严肃，两者都有一个主题，就是主角在找寻自己的真实身份。所以，如果说《绑架》和《谍影重重》在某些元素上是类似的，这一点的确如此。但两者还是有不小的区别。《谍影重重》的主角是一个身怀绝技的特工，但《绑架》的主角却是一个什么都不懂的年轻人，他面对危险，并不想马特&middot;达蒙那样从容不迫，这样也使得《绑架》的男主角一直处在普通人都会遭遇的危险当中，也更能让观众感同身受。另外，《绑架》的主要目的还是逃亡，主角一直处在追杀当中，他并没有那么强大的能力去对抗阴谋组织，所以他其实是在逃亡的过程里见缝插针的寻找自己的身份，他善于掌握机会，才能最终反败为胜。&rdquo;<br style="word-wrap: break-word" />
	<br style="word-wrap: break-word" />
	　　青春偶像的大逃亡<br style="word-wrap: break-word" />
	<br style="word-wrap: break-word" />
	　　在《绑架》中担当男主角的，是近年来因为参演《暮色》系列而走红的&ldquo;狼人&rdquo;泰勒&middot;洛特纳。谈及这部让自己大展拳脚的动作片，泰勒&middot;洛特纳说道：&ldquo;我在《绑架》里扮演的角色是一个20岁出头的年轻人，他的父母对他很好，但他总是感觉有些什么不对劲，这种不对劲直到他浏览了一个失踪人口的网站之后才明白了是怎么一回事，但当他正想质问自己父母的时候，他们却死在自己眼前，一群看起来像是杀手的人开始追杀自己。他的整个生活被完全破坏了，他一直在练拳击，喜欢隔壁邻居家的姑娘，积极的工作，但接着他的命运变成了不停的逃亡，躲避上天入地的追杀。尼敦是一个生活原本普普通通的年轻人，结果当他知道自己的身份原本并非如此之后，他开始找寻自己真正的身份，在这个过程里，他付出了很多代价，于是他开始带着他的邻居一起步上逃亡的旅程，他要为自己的养父母报仇，要讨回自己被遗弃了多年的时光，更要让幕后的组织血债血偿。在《绑架》里我有很多动作戏，很多的奔跑，每天我都要跑很多的路，这对我来说也是一个巨大的挑战，因为在不停的奔跑里，我还必须要完成相应的动作戏份，有一些是比较危险的&hellip;&hellip;例如像有一段在公车上的逃亡戏，我需要在公车爆炸之前跳车，虽然导演建议我用替身，但我觉得亲自出演这样的电影会更加有意义，于是在这段戏里，我做了很多准备的功课，希望能够一次拍摄完成&hellip;&hellip;最后的效果很好，也很惊险，这是让我难忘的拍摄时光。&rdquo;<br style="word-wrap: break-word" />
	<br style="word-wrap: break-word" />
	　　谈及对片中尼敦这个角色的塑造和泰勒&middot;洛特纳的出演，导演约翰&middot;辛格顿说道：&ldquo;尼敦是整部电影最重要的角色，他的成功与否，直接影响到观众是否认可这部电影。对于尼敦的性格，我和编剧、泰勒&middot;洛特纳曾经一起探讨过，我们一致认为这个男人应该是传统意义上的&lsquo;Good Boy&rsquo;，他尊师重道，是一个好好先生。不过，为了他接下来要在电影里要应付一个小时的动作戏，为了给他娴熟的动作提供一个可信的基础，我们让他有了一个爱好，那就是拳击。拳击也是他和父亲沟通的桥梁。基于这一点上，观众不会对他在逃亡路上所展现出的惊人魄力感到吃惊。我想大家对泰勒&middot;洛特纳的认识，更多的是来源于《暮色》，在这部电影里，泰勒&middot;洛特纳很遗憾的并没有太多发挥他动作的地方，很多时候是被特效代替了，而他本身很希望能饰演一个充满热血的年轻人，所以在《绑架》里，我们有许多没有用替身和特效的实拍动作戏份，这些都是泰勒&middot;洛特纳非常认真去对待的段落，所以我觉得他对于尼敦这个角色的演绎是成功的。&rdquo;<br style="word-wrap: break-word" />
	<br style="word-wrap: break-word" />
	幕后花絮<br style="word-wrap: break-word" />
	<br style="word-wrap: break-word" />
	&middot;本片是肖恩&middot;克里斯汀森的编剧处女作。<br style="word-wrap: break-word" />
	&middot;本片曾考虑在2011年春季档公映，但最后延期至半年后的秋季档。<br style="word-wrap: break-word" />
	&middot;本片的片名为《Abduction》，因为重名电影太多，在制作期间本片曾经多次考虑过更名，但最后还是依然保持这个名字。<br style="word-wrap: break-word" />
	&middot;本片于2010年7月12日开机，进行了为期两月的拍摄和三个月的后期制作。</p>
<p>
	<img alt="" src="http://img165.poco.cn/mypoco/myphoto/20111225/00/62564813201112250042428405985765905_002.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img165.poco.cn/mypoco/myphoto/20111225/00/62564813201112250042428405985765905_001.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img165.poco.cn/mypoco/myphoto/20111225/00/62564813201112250042428405985765905_000.jpg" style="width: 720px; height: 405px" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="http://www.xiaozhizhu.net/">本影片已删除 观看正版 请去电影院观看 </a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15CcZ-41U8.jpg{/dede:field}
