{dede:field name='keywords'}顶级猫/猫老大BD中英双字1024高{/dede:field}
{dede:field name='description'}顶级猫/猫老大BD中英双字1024高清2011动画迅雷下载、免费下载，顶级猫/猫老大BD中英双字1024高清2011动画Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}顶级猫/猫老大BD中英双字1024高清2011动画{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-03-08{/dede:field}
{dede:field name='body'}<p>
	<img alt="" height="1062" src="http://thecitylovesyou.com/cinerex/wp-content/uploads/2011/08/cartel.jpg" width="750" /></p>
<p>
	◎译　　名　顶级猫/猫老大<br />
	◎片　　名　Top Cat The Movie<br />
	◎年　　代　2011<br />
	◎国　　家　墨西哥/阿根廷<br />
	◎类　　别　动画<br />
	◎语　　言　英语<br />
	◎字　　幕　中英双字<br />
	◎IMDB评分 5.8/10 from 239 users<br />
	◎文件格式　X264 + AAC<br />
	◎视频尺寸　1024 x 576<br />
	◎文件大小　1CD<br />
	◎片　　长　1h 30mn<br />
	◎导　　演　Alberto Mar<br />
	◎主　　演　R&aacute;ul Anaya ... Don Gato (voice)<br />
	　　　　　　Jorge Arvizu ... Benito / Cucho (voice)<br />
	　　　　　　Mario Casta?eda Partido ... Lucas Buenrostro (voice)<br />
	　　　　　　Jim Conroy ... Additional Voices (voice)<br />
	　　　　　　Rolando de Castro ... Juez de la corte (voice)<br />
	　　　　　　Ben Diskin ... Spook (voice: English version)<br />
	　　　　　　Melissa Disney ... Trixie (voice: English version)<br />
	　　　　　　Chris Edgerly ... Benny (voice: English version)<br />
	　　　　　　Eduardo Garza ... Panza (voice)<br />
	　　　　　　Jason Harris ... Top Cat / Griswald / Strickland / Choo Choo / Brain / Big Gus (voice)<br />
	　　　　　　Guzm&aacute;n Jes&uacute;s ... Dem&oacute;stenes (voice)<br />
	　　　　　　Bob Kaliban ... Judge / Police Chief / Mayor (voice)<br />
	　　</p>
<p>
	◎简　　介　</p>
<p>
	　　Top Cat and the gang face a new police chief, who is not at all happy with the poor officer Dribble&#39;s performance trying to prevent Top Cat&#39;s scams. Strickland, the new police chief, has a wealth of technological resources and their real intention is to take the city, imposing ridiculous laws. Will test the Don Gato and all members of the gang, as well as the proper officer Dribble in a film full of adventure, action and lots of fun.　</p>

<div id="trans-result-content">
	<p src="　Top Cat and the gang face a new police chief, who is not at all happy with the poor officer Dribble&amp;#39;s performance trying to prevent Top Cat&amp;#39;s scams. Strickland, the new police chief, has a wealth of technological resources and their real intention is to take the city, imposing ridiculous laws. Will test the Don Gato and all members of the gang, as well as the proper officer Dribble in a film full of adventure, action and lots of fun.">
		顶部猫和帮派面临一个新的警察局长，谁是不满意的差官运球的表现，试图阻止的顶级猫的骗局。斯特里克兰，新的警察局长，有丰富的技术资源和他们的真正目的是取城，对荒谬的法律。将测试不加托和所有成员，以及适当的军官运球电影充满冒险，行动和许多乐趣。</p>
</div>

<p>
	<img alt="" src="http://img.album.pchome.net/48/32/32/45/f46ca355bbf7b213729e0bb84d02b3ab.Top" /></p>
<p>
	<img alt="" src="http://img.album.pchome.net/48/32/32/45/c9d62478e133831e7c6ffcffaa2e5d99.Top" /></p>
	[下载地址]： &nbsp;<img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" /></p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2975/飘花电影piaohua.com猫老大BD中英双字1024高清.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2975/飘花电影piaohua.com猫老大BD中英双字1024高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1B51210-49634.jpg{/dede:field}
