<?php
$z[0]=Array("field","Loreena,McKennitt,-,THE,MUMMER",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","Loreena McKennitt - THE MUMMERS DANCE迅雷下载、免费下载，Loreena McKennitt - THE MUMMERS DANCEGvod高清在线播放，剧情介绍等。",73,241);
$z[1][4]['name']="description";
$z[2]=Array("field","Loreena McKennitt - THE MUMMERS DANCE",243,318);
$z[2][4]['name']="title";
$z[3]=Array("field","",320,359);
$z[3][4]['name']="writer";
$z[4]=Array("field","",361,400);
$z[4][4]['name']="source";
$z[5]=Array("field","2006-08-04",402,452);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<P>播放后双击视频“全屏”</P> \n<object classid=\"CLSID:22d6f312-b0f6-11d0-94ab-0080c74c7e95\" class=\"OBJECT\" id=\"MediaPlayer\" width=\"500\" height=\"350\" ><param name=\"ShowStatusBar\" value=\"-1\"><param name=\"Filename\" value=\"http://web1.to.fastvibe.com/quinlan-road/wm/mummers_100k.asx\"></embed></object><br /> \n<P>下载地址<BR></P> <br>",454,821);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c120524/133N353DD0-2G248.gif",823,906);
$z[7][4]['name']="litpic";

?>