<?php
$z[0]=Array("field","旅社/客栈/人皮客栈1-2BD中英双",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","旅社/客栈/人皮客栈1-2BD中英双字1024/1280高清版迅雷下载、免费下载，旅社/客栈/人皮客栈1-2BD中英双字1024/1280高清版Gvod高清在线播放，剧情介绍等。",72,258);
$z[1][4]['name']="description";
$z[2]=Array("field","旅社/客栈/人皮客栈1-2BD中英双字1024/1280高清版",260,344);
$z[2][4]['name']="title";
$z[3]=Array("field","",346,385);
$z[3][4]['name']="writer";
$z[4]=Array("field","",387,426);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-12-16",428,478);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",480,517);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://3e:3e@www2.eee4.com:656/[www.eee4.cn提供]人皮客栈BD中英双字1024x434高清版.rmvb\" target=\"_blank",519,658);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MPM51P-42206.jpg",660,742);
$z[8][4]['name']="litpic";

?>