{dede:field name='keywords'}世贸中心[DVD中英字幕]迅雷下载{/dede:field}
{dede:field name='description'}世贸中心[DVD中英字幕]迅雷下载、免费下载，世贸中心[DVD中英字幕]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}世贸中心[DVD中英字幕]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2006-08-21{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://e13:e13@xl2.eee4.com:9916/[3E电影站www.eee4.com]世贸中心DVD中英双字CD1.rmvb" target="_blank{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MP913Y0-2P17.jpg{/dede:field}
