{dede:field name='keywords'}想飞的钢琴少年迅雷下载，免费下{/dede:field}
{dede:field name='description'}想飞的钢琴少年迅雷下载、免费下载，想飞的钢琴少年Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}想飞的钢琴少年{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2007-11-29{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://eee4:eee4.com@xl.eee4.com/想飞的钢琴少年/[3E迅雷电影站www.eee4.com]想飞的钢琴少年cd1.rmvb" target="_blank{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MP4364P-13309.jpg{/dede:field}
