<?php
$z[0]=Array("field","想飞的钢琴少年迅雷下载，免费下",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","想飞的钢琴少年迅雷下载、免费下载，想飞的钢琴少年Gvod高清在线播放，剧情介绍等。",73,195);
$z[1][4]['name']="description";
$z[2]=Array("field","想飞的钢琴少年",197,249);
$z[2][4]['name']="title";
$z[3]=Array("field","",251,290);
$z[3][4]['name']="writer";
$z[4]=Array("field","",292,331);
$z[4][4]['name']="source";
$z[5]=Array("field","2007-11-29",333,383);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",385,422);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://eee4:eee4.com@xl.eee4.com/想飞的钢琴少年/[3E迅雷电影站www.eee4.com]想飞的钢琴少年cd1.rmvb\" target=\"_blank",424,574);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MP4364P-13309.jpg",576,659);
$z[8][4]['name']="litpic";

?>