{dede:field name='keywords'}卡廷惨案/爱在波兰战火时BD中英{/dede:field}
{dede:field name='description'}卡廷惨案/爱在波兰战火时BD中英双字1024/1280高清迅雷下载、免费下载，卡廷惨案/爱在波兰战火时BD中英双字1024/1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}卡廷惨案/爱在波兰战火时BD中英双字1024/1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-04-30{/dede:field}
{dede:field name='body'}<p>
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://image-3.verycd.com/acc3245892cfeaf281246bc62d740984300440(600x)/thumb.jpg');" src="http://image-3.verycd.com/acc3245892cfeaf281246bc62d740984300440(600x)/thumb.jpg" /></p>
<p>
	◎译　　名　《卡廷惨案/爱在波兰战火时》07波兰剧情战争片DVD中英双字1024x576高清版<br />
	◎片　　名　Katyn<br />
	◎年　　代　2007<br />
	◎国　　家　波兰<br />
	◎类　　别　剧情/历史/战争<br />
	◎语　　言　波兰语<br />
	◎字　　幕　中英双字<br />
	◎IMDB评分 7.2/10 (637 votes)<br />
	◎文件格式　BD-RMVB<br />
	◎视频尺寸　1024 X 576<br />
	◎文件大小　1CD<br />
	◎导　　演　安杰依&middot;瓦依达 Andrzej Wajda<br />
	◎主　　演　Pawel Malaszynski .....Pawel<br />
	　　　　　　Joachim Paul Assb ck .....Sturmbannfuehrer Mueller<br />
	　　　　　　Magdalena Cielecka .....Magda<br />
	　　　　　　Danuta Stenka .....Danuta<br />
	　　　　　　Andrzej Chyra<br />
	　　　　　　玛雅&middot;歌摩劳斯嘉 Maja Komorowska .....Maja<br />
	　　　　　　Wladyslaw Kowalski .....Wladyslaw<br />
	　　　　　　Artur Zmijewski .....Artur<br />
	　　　　　　Maja Ostaszewska .....Maja<br />
	　　　　　　Stanislawa Celinska .....Stasia<br />
	　　　　　　安娜&middot;拉德旺 Anna Radwan .....Anna<br />
	　　　　　　Agnieszka Kawiorska .....Young Joanna<br />
	　　　　　　Andrzej Mlynarczyk<br />
	　　　　　　Antoni Pawlicki .....Antoni<br />
	　　　　　　Wiktoria Gasiewska .....Wiktoria<br />
	　　　　　　Joanna Kawiorska .....Joanna<br />
	　　　　　　Agnieszka Glinska .....Agnieszka<br />
	<br />
	<br />
	◎简　　介　<br />
	<br />
	　卡廷惨案描述的是一代人的悲剧。电影讲述的是四个波兰家庭所遭遇的悲欢离合的故事。第二次世界大战开始之时，一大批波兰的战士，他们也是身为他人的父亲、丈夫和兄弟，他们落入了苏联军队的掌控，最后被残忍地杀害了，成为了&ldquo;斯大林主义&rdquo;的牺牲品。电影也展现了二战前后的波兰所处的国内外复杂情况。</p>
<p>
	<br />
	<br />
	幕后制作：<br />
	<br />
	【关于卡廷事件】<br />
	<br />
	　　卡廷事件是第二次世界大战期间波兰军官战俘被集体屠杀的事件。波兰导演瓦依达在《卡廷惨案》中保持其一贯敢于解决尖锐问题的作风，对这个隐秘的历史事件从一个侧面进行了描述。<br />
	<br />
	　　1939年9月1日，纳粹德国对波兰发动闪击战，占领波兰西部地区。9月17日，苏联从东部进入波兰，占领寇松线以东的全部波兰领土，俘虏约25万名波兰军队官兵。苏联随后将波兰官兵分别关押在一些新建的战俘营。其中的斯塔罗别利斯克、科泽利斯克和奥斯塔什科夫3个战俘营，关押着包括9000名军官在内的共约1.5万名波兰战俘。<br />
	<br />
	　　1943年4月13日，攻入苏联境内的纳粹德国军方宣布，在德军占领的苏联斯摩棱斯克市附近的卡廷森林地区发现被苏联军方屠杀的波兰军人万人坑。4月15日，苏联发表公报，对此予以断然否认，宣称这些波兰战俘在德军入侵苏联之后落入德军手中，是被德军所杀害的。此后，苏联和德国均组织调查团前往卡廷进行实地调查，但都没有没有取得明确的结果。战后，纽伦堡国际军事法庭在审讯纳粹德国战犯时也回避对卡廷事件的明确表态，从而使之成为一桩未了的迷案。<br />
	<br />
	　　此后，波兰方面和国际社会针对苏联政府的说法多次提出怀疑并展开激烈争论，但苏联政府始终坚持既定的立场。1985年戈尔巴乔夫成为苏联党和国家领导人之后，苏联和波兰组成由历史学家参加的联合委员会，对涉及此次事件的大量文件进行深入细致的研究。1990年4月13日，在波兰总统雅鲁泽尔斯基访问苏联之际，苏联正式承认对卡廷事件负全部责任。<br />
	<br />
	业经披露的卡廷事件的基本情况是这样的。苏联政府认为波兰战俘是一个大包袱（一方面，苏联在紧张的备战中为其要消耗宝贵的人力和物力；另一方面，波兰战俘可能随时反抗苏军的监禁），遂决定先处理掉波兰战俘中的军官。除掉了军官，其余的士兵就会处于群龙无首的境地。苏联有关方面认为，最好的办法是从肉体上将他们消灭掉。1940年3月5日，苏联内务人民委员（内务部长）贝利亚专门就对2万余名以波兰军官为主的战俘和犯人实施枪决一事写出报告上交斯大林和联共（布）中央审批，随即获得批准。<br />
	<br />
	　　1940年4月初，处决波兰战俘的行动正式开始。数百名被俘的波兰军官被从上述三个战俘营带上汽车，秘密运往行刑地卡廷森林。行刑人员站在波兰战俘身后，用手枪对着他们的后脑开枪。掩埋之后，苏方人员在上面铺上了厚厚一层土。不久，第二批战俘又被运到该地被同样处理。直至当年5月中旬，苏联方面在卡廷森林共处决波兰战俘4421人。他们被分别埋入8个大坑，上面铺满松树和白烨树。除卡廷森林外，苏联方面还在斯塔罗别利斯克战俘营枪决了3820人，奥斯塔什科夫集中营枪决了6311人，西乌克兰和西白俄罗斯的其他战俘营和监狱枪决了7305人。加上卡廷森林枪决的4421人，共计21857人，其中包括约1.5万名波兰官兵俘虏。<br />
	<br />
	【穿越时空的回归与重逢】<br />
	<br />
	　　卡廷是一个能在所有波兰人心中引起共鸣的地名。1940年苏联军队在这里及另外两处地方，枪杀了<a href="http://www.eee4.com/" target="_blank">电影下载</a>二万多名波兰人。波兰在被苏联占领45年时间里，这是一个高度禁忌的话题，尽管几十年来官方一直在宣传谴责德军犯下的罪行，但大多数波兰人依然十分清楚此事的真相。而在当时的电影审查制度下，要制作一部关于卡廷大屠杀的电影几乎是不可能的。<br />
	<br />
	　　即使在国家获得新生，于1989年解放之后，波兰电影导演、如今81岁高龄的安杰依?瓦依达也花了17年的时间才终于找到一个令他满意的剧本。他最终选择了波兰最具有影响力的剧作家之一AndrzejMularczyk的剧本。《卡廷惨案》于2007年9月17日即二次大战苏联入侵波兰东部68周年纪念日在首都华沙作全球首映。在波兰国内的每一家电影院的宣传栏里，都张贴了一张沉重的海报，上面是四名波兰军官灰色的脸，同时也预示出该片在波兰电影史上将会是票房成绩最好的影片。<br />
	<br />
	　　导演瓦依达的父亲是一名军官，后来成为卡廷惨案中被杀害的牺牲者中的一个。上尉贾库布?瓦依达被苏联内务人民委员会（NKVD）的秘密警察从背后开枪打死，然后与其他成千上万的战友一起被堆积在了一个坟墓里。瓦依达把这段缠绕他一生的伤痛经历拍成了电影，他认为&ldquo;这部电影一定能唤起每一个人沉睡的心灵&rdquo;。<br />
	<br />
	　　2000年奥斯卡荣誉奖获得者，瓦依达的创作生涯开始于1950年代，拍摄了关于二战的三部曲很快招致的后果就是被没收，分别是《一代人》（1955）、《地下水道》（1958）、《灰烬与钻石》（1958）。在这些电影中，被评论界公认是他最出色的作品，瓦依达对于波兰长期以来的英雄主义传统持有怀疑态度，传统观念认为英雄就应该为光荣事业献身而不能屈辱地活着。在《卡廷惨案》中瓦依达重新回归到这一主题。<br />
	<br />
	　　&ldquo;在某种意义上，我把这部电影看成是那个时代波兰电影学院的验尸报告。它是这些主题的终结者。我也是最后的一位导演，这部电影也是我最后一批影片中的一部，&rdquo;说这番话的时候，瓦依达正坐在华沙的博罗尼亚宫酒店里喝着一边茶，这里也是波兰首府中心在战争中幸存下来的唯一几处建筑之一。他接着说道：&ldquo;这部电影是对我在1950年拍摄的那些电影的一次遥远的重逢。&rdquo;<br />
	<br />
	【不能忘记的历史和人们】<br />
	<br />
	　　苏联和德国在1939年秘密达成协议，共同瓜分波兰。苏联逮捕了数千名政府官员，以及律师、警察和土地所有者等等，将这些人分别关押在苏联西部的 Kozielsk、Ostashkov和Starobielsk三个集中营里。瓦依达的父亲就是在这时期被捕的。根据斯大林个人发布的一道命令，在 1943年春天大约有两万两千名波兰人被执行死刑。此事由纳粹德军于1943年在卡廷发现一座波兰人的万人冢而被揭发。瓦依达在影片中展现了德军占领下的波兰，人们正在浏览报纸上死者的名字，观看着一部关于发掘死者的宣传片。当苏联横扫西方在后一年重新占领卡廷之后，他们试图把大屠杀的罪行归咎于德军，用了一些德军的胶片来拍摄自己的宣传片。西方同盟军意识到苏联有可能应承担责任，但为了能击败纳粹分子，他们不想分裂同盟军。<br />
	<br />
	　　波兰的双重灾难&mdash;&mdash;同时被纳粹德军和苏联军队控制，组成了本片的开场。然而这<a href="http://www.eee4.com/" target="_blank">迅雷电影下载</a>部预算成本为四百万欧元的波兰电影，并不是这起屠杀时间的历史统计表，反而着眼于四个家庭，正在等待和期望他们的男人的回家。瓦依达提出的问题是：&ldquo;我要制作一部关于自己的父亲还是母亲的电影？&rdquo;他后来决定站在母亲这一边。瓦依达的解释是：&ldquo;这是一部政治片，但是关于我母亲的故事是心理上的。她坐在那里等待，给红十字会和伦敦写信，总是在期待他能活着回来。&rdquo;由于电影是要讲述四个等待的家庭的故事，它反复面临着同样的遭遇，是否应该投降，忍辱负重与波兰的敌人合作，或者是坚守信仰勇敢去面对监狱甚至是死亡的结局。<br />
	<br />
	　　影片结尾的时候是一个漫长而详细地描绘了军官被一个接一个从卡车里拉出来，由两个苏联内务人民委员会的士兵架着，然后他们被第三个士兵开枪打死。瓦依达认为：&ldquo;我必须把那些残害了这么多人的杀人机器展现出来。&rdquo;看完了这场杀人游戏之后，在华沙一场比较早的试映会上所有观众都静静地坐着，直到字幕出现后的五分钟时间里都是如此，没有一个人说一个字或者在他们的位子上动一下。<br />
	<br />
	瓦依达这次在《卡廷惨案》中保持其一贯敢于解决尖锐问题的作风，对这个隐秘的历史事件从另一个侧面进行了描述。卡廷在所有波兰人心中是一个引起共鸣的地名，1940年苏联军队在这里及另外两处地方，枪杀了二万多名波兰人。波兰在被苏联占领45年时间里，这是一个高度禁忌的话题，尽管几十年来官方一直在宣传谴责德军犯下的罪行，但大多数波兰人依然十分清楚真相。但在当时的电影审查制度下，要制作一部关于卡廷大屠杀的电影几乎是不可能的。<br />
	<br />
	已经81岁高龄的安杰依&middot;瓦依达花了17年的时间才找到令他满意的剧本，《卡廷惨案》已于2007年9月17日即二次大战苏联入侵波兰东部68周年纪念日在首都华沙作全球首映。在波兰国内的每一家电影院的宣传栏里，都张贴了一张沉重的海报，上面是四名波兰军官灰色的脸，瓦依达认为：&ldquo;我必须把那些残害了这么多人的杀人机器展现出来。在某种意义上，我把这部电影看成是那个时代波兰电影学院的验尸报告。它是这些主题的终结者。我也是最后的一位导演，这部电影也是我最后一批影片中的一部。&rdquo;<br />
	<br />
	幕后/花絮<br />
	&middot;本片被波兰选送角逐2008年第80届奥斯卡金像奖最佳外语片。<br />
	<br />
	<img onclick="if(this.width&gt;screen.width-461) window.open('http://img.album.pchome.net/54/68/92/29/87d864802f4ad89af09b2bb401439928.jpg');" src="http://img.album.pchome.net/54/68/92/29/87d864802f4ad89af09b2bb401439928.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 338px; border-top: 0px solid; border-right: 0px solid" /><br />
	<img onclick="if(this.width&gt;screen.width-461) window.open('http://img.album.pchome.net/54/68/92/29/db9242eb159643761795984e0e371803.jpg');" src="http://img.album.pchome.net/54/68/92/29/db9242eb159643761795984e0e371803.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 338px; border-top: 0px solid; border-right: 0px solid" /><br />
	<img onclick="if(this.width&gt;screen.width-461) window.open('http://img.album.pchome.net/54/68/92/29/46849c3f82f63393648725c004baaee8.jpg');" src="http://img.album.pchome.net/54/68/92/29/46849c3f82f63393648725c004baaee8.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 338px; border-top: 0px solid; border-right: 0px solid" /></p>
<p>
	07波兰剧情战争片《卡廷惨案》DVD中英双字1024x576高清版 [下载地址]：<img border="0" src="http://www.eee4.com/templets/img/down.jpg" /></p>

<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://3e:3e@www2.eee4.com:307/[3E电影站www.eee4.com]卡廷惨案DVD中英双字1024x576高清版.rmvb" target="_blank">ftp://3e:3e@www2.eee4.com:307/[3E电影站www.eee4.com]卡廷惨案DVD中英双字1024x576高清版.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3321/飘花电影piaohua.com爱在波兰战火时BD中英双字1280高清.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3321/飘花电影piaohua.com爱在波兰战火时BD中英双字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15023160-19118.jpg{/dede:field}
