{dede:field name='keywords'}甜蜜咖啡屋/发达咖啡室/巴格达咖{/dede:field}
{dede:field name='description'}甜蜜咖啡屋/发达咖啡室/巴格达咖啡馆[BD中英双字1280x720高清版]迅雷下载、免费下载，甜蜜咖啡屋/发达咖啡室/巴格达咖啡馆[BD中英双字1280x720高清版]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}甜蜜咖啡屋/发达咖啡室/巴格达咖啡馆[BD中英双字1280x720高清版]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2009-11-09{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://3e:3e@www2.eee4.com:866/[3E电影站www.eee4.cn]甜蜜咖啡屋BD中英双字1280x720高清版.rmvb" target="_blank{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MQ304950-22U7.jpg{/dede:field}
