{dede:field name='keywords'}女杰6_第六期_SJ基范,韩庚迅雷下{/dede:field}
{dede:field name='description'}女杰6_第六期_SJ基范,韩庚迅雷下载、免费下载，女杰6_第六期_SJ基范,韩庚Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}女杰6_第六期_SJ基范,韩庚{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2006-08-17{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://ftp.upplay.com/" target=_blank>ftftp://ftp.upplay.com/</A>加勒比社区荣誉出品Happy.Sunday.E91.060806.SDTV.girl6.KO_CN.rmvb<BR><BR>2006-08-09 11:23:46 开始连接<FONT face=Verdana>@更多请到:u199.com</FONT>......<BR>2006-08-09 11:23:46 开始搜索候选资源......<BR>2006-08-09 11:23:47 搜索到40个候选资源<BR>2006-08-09 11:23:47 使用候选资源进行连接......<BR>2006-08-09 11:23:47 开始创建文件......<BR>2006-08-09 11:24:09 文件创建成功，开始下载数据......</SPAN> <br></div><ul class="mmlist{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MO60K30-35C0.gif{/dede:field}
