<?php
$z[0]=Array("field","女杰6_第六期_SJ基范,韩庚迅雷下",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","女杰6_第六期_SJ基范,韩庚迅雷下载、免费下载，女杰6_第六期_SJ基范,韩庚Gvod高清在线播放，剧情介绍等。",73,215);
$z[1][4]['name']="description";
$z[2]=Array("field","女杰6_第六期_SJ基范,韩庚",217,279);
$z[2][4]['name']="title";
$z[3]=Array("field","",281,320);
$z[3][4]['name']="writer";
$z[4]=Array("field","",322,361);
$z[4][4]['name']="source";
$z[5]=Array("field","2006-08-17",363,413);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",415,452);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://ftp.upplay.com/\" target=_blank>ftftp://ftp.upplay.com/</A>加勒比社区荣誉出品Happy.Sunday.E91.060806.SDTV.girl6.KO_CN.rmvb<BR><BR>2006-08-09 11:23:46 开始连接<FONT face=Verdana>@更多请到:u199.com</FONT>......<BR>2006-08-09 11:23:46 开始搜索候选资源......<BR>2006-08-09 11:23:47 搜索到40个候选资源<BR>2006-08-09 11:23:47 使用候选资源进行连接......<BR>2006-08-09 11:23:47 开始创建文件......<BR>2006-08-09 11:24:09 文件创建成功，开始下载数据......</SPAN> <br></div><ul class=\"mmlist",454,977);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MO60K30-35C0.gif",979,1061);
$z[8][4]['name']="litpic";

?>