{dede:field name='keywords'}七个以下BD1280高清迅雷下载，免{/dede:field}
{dede:field name='description'}七个以下BD1280高清迅雷下载、免费下载，七个以下BD1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}七个以下BD1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-04-19{/dede:field}
{dede:field name='body'}<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120413/11/56643687201204131117233973977483176_004.jpg" /></p>
<p>
	◎译　　名　七个以下<br />
	◎片　　名　Seven Below<br />
	◎年　　代　2012<br />
	◎国　　家　美国<br />
	◎类　　别　惊悚/恐怖<br />
	◎语　　言　英语<br />
	◎字　　幕　中文<br />
	◎IMDB评分 Awaiting 5 votes<br />
	◎IMDB链接 <a href="http://www.imdb.com/title/tt1988781">http://www.imdb.com/title/tt1988781</a><br />
	◎文件格式　高清BDRIP-RMVB<br />
	◎视频尺寸　720 x 340<br />
	◎文件大小　1CD 478MB<br />
	◎片　　长　92 Mins<br />
	◎导　　演　Kevin Carraway<br />
	◎主　　演　方&middot;基默 Val Kilmer &hellip;.McCormick<br />
	　　　　　　文&middot;瑞姆斯 Ving Rhames &hellip;.Jack<br />
	　　　　　　鲁克&middot;高斯 Luke Goss &hellip;.Issac<br />
	　　　　　　Bonnie Somerville &hellip;.Brooklyn<br />
	　　　　　　马特&middot;巴尔 Matt Barr &hellip;.Adam<br />
	　　　　　　Christian Baha &hellip;.Dr. Lipski<br />
	　　　　　　Brianna Lee Johnson &hellip;.Elizabeth<br />
	　　　　　　Rebecca Da Costa &hellip;.Courtney</p>
<p>
	<br />
	◎简　　介　</p>
<p>
	The story centers on a group of strangers trapped in a time warp house where a terrible event transpired exactly 100 years prior.</p>
<div id="trans-result-content">
	<p src="The story centers on a group of strangers trapped in a time warp house where a terrible event transpired exactly 100 years prior.">
		故事围绕着一群陌生人被困在一个扭曲的时间里可怕的事件发生的100年前。</p>
</div>

<p>
	<br />
	◎影片截图</p>
<p>
	&nbsp;<img src="http://img170.poco.cn/mypoco/myphoto/20120413/11/56643687201204131117233973977483176_003.jpg" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120413/11/56643687201204131117233973977483176_002.jpg" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120413/11/56643687201204131117233973977483176_001.jpg" />、<img src="http://img170.poco.cn/mypoco/myphoto/20120413/11/56643687201204131117233973977483176_000.jpg" /></p>

<p>
	【下载地址】</p>
<table bgcolor="#0099cc" border="0" cellpadding="10" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.net" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3213/飘花电影piaohua.com七个以下高清DVD中字.rmvb &#13;&#10;">ftp://dy44:piaohua@dy44.piaohua.com:3213/飘花电影piaohua.com七个以下高清DVD中字.rmvb </a></td>
		</tr>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy125:piaohua@dy125.piaohua.com:7869/飘花电影piaohua.com七个以下BD中字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:7869/飘花电影piaohua.com七个以下BD中字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>
<br />{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15623440-4QC.jpg{/dede:field}
