<?php
$z[0]=Array("field","世界上最棒的汽车节目：启示录/",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","世界上最棒的汽车节目：启示录/疯狂汽车秀/车迷大本营[BD中字1024x576高清版]迅雷下载、免费下载，世界上最棒的汽车节目：启示录/疯狂汽车秀/车迷大本营[BD中字1024x576高清版]Gvod高清在线播放，剧情介绍等。",72,310);
$z[1][4]['name']="description";
$z[2]=Array("field","世界上最棒的汽车节目：启示录/疯狂汽车秀/车迷大本营[BD中字1024x576高清版]",312,422);
$z[2][4]['name']="title";
$z[3]=Array("field","",424,463);
$z[3][4]['name']="writer";
$z[4]=Array("field","",465,504);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-12-17",506,556);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",558,595);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://4e:4e@d6.3edyy.com:607/【3E看看www.3ekk.com】世界上最棒的汽车节目：启示录BD中字1024x576高清版.rmvb\" target=_blank>ftftp://4e:4e@d6.3edyy.com:607/【3E看看www.3ekk.com】世界上最棒的汽车节目：启示录BD中字1024x576高清版.rmvb</A></TD></TR></TBODY></TABLE></div><ul class=\"mmlist",597,915);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MQ452160-12316.jpg",917,1001);
$z[8][4]['name']="litpic";

?>