{dede:field name='keywords'}铁甲钢拳DVD中英双字2011动作科{/dede:field}
{dede:field name='description'}铁甲钢拳DVD中英双字2011动作科幻迅雷下载、免费下载，铁甲钢拳DVD中英双字2011动作科幻Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}铁甲钢拳DVD中英双字2011动作科幻{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-01-04{/dede:field}
{dede:field name='body'}<p>
	&nbsp;<img alt="" src="http://img165.poco.cn/mypoco/myphoto/20120104/10/56643687201201041051133986872131413_005.jpg" /></p>


<p>
	◎片　　名　铁甲钢拳/钢铁擂台(台)<br />
	◎又&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 名&nbsp;&nbsp; Real Steel<br />
	◎年　　代　2011<br />
	◎国　　家　美国<br />
	◎类　　别　剧情 / 动作 / 科幻<br />
	◎语　　言　英语<br />
	◎字　　幕　中字<br />
	◎IMDB评分&nbsp; 7.3/10 from 746 users<br />
	◎文件格式&nbsp; TS-RMVB<br />
	◎视频尺寸&nbsp; 720 x 304<br />
	◎文件大小&nbsp; 1CD 702MB<br />
	◎片　　长&nbsp; 104 Mins<br />
	◎导　　演&nbsp;&nbsp; 肖恩&middot;列维<br />
	◎演&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 员&nbsp; 休&middot;杰克曼 / Dakota Goyo / 凯文&middot;杜兰 / 安东尼&middot;麦凯 / 伊万杰琳&middot;莉莉 / 霍普&middot;戴维斯 / 詹姆斯&middot;瑞布霍恩 / Olga Fonda</p>
<p>
	◎简　　介<br />
	影片讲述了在不远的未来，类拳击被取缔，只有机器人的拳击赛才合法。休&middot;杰克曼在片中出演一位前拳击手，他在长时间的沉睡之后醒来，发现人类已经不能参与拳击运动了，而且自己还有一个11岁的儿子，于是决定成为拳击经纪人。在寻找中他发现了一个求胜心很强，却已经被弃用的机器人，于是他和儿子一起努力让它成为冠军。<br />
	&nbsp;</p>
<p>
	<img alt="" src="http://pic.piaohua.com/0701pic/allimg/111011/1-1110111T35K14.jpg" /></p>
<p>
	<img alt="" height="340" src="http://img165.poco.cn/mypoco/myphoto/20120104/10/56643687201201041051133986872131413_003.jpg" style="cursor: pointer" width="600" /></p>
<p>
	<img alt="" height="340" src="http://img165.poco.cn/mypoco/myphoto/20120104/10/56643687201201041051133986872131413_004.jpg" style="cursor: pointer" width="600" /></p>
<p>
	<img alt="" height="340" src="http://img165.poco.cn/mypoco/myphoto/20120104/10/56643687201201041051133986872131413_000.jpg" style="cursor: pointer" width="600" /></p>
<p>
	<img alt="" height="340" src="http://img165.poco.cn/mypoco/myphoto/20120104/10/56643687201201041051133986872131413_001.jpg" style="cursor: pointer" width="600" /></p>
<p>
	<img alt="" height="340" src="http://img165.poco.cn/mypoco/myphoto/20120104/10/56643687201201041051133986872131413_002.jpg" style="cursor: pointer" width="600" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:1795/飘花电影piaohua.com铁甲钢拳抢先版.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:1795/飘花电影piaohua.com铁甲钢拳抢先版.rmvb</a>&nbsp;</td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2214/飘花电影piaohua.com铁甲钢拳DVDscr清晰版.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2214/飘花电影piaohua.com铁甲钢拳DVDscr清晰版.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2515/飘花电影piaohua.com铁甲钢拳DVD中英双字.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2515/飘花电影piaohua.com铁甲钢拳DVD中英双字.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15Z1140-36422.jpg{/dede:field}
