{dede:field name='keywords'}S.H.E：爱而为一演唱会影音馆迅{/dede:field}
{dede:field name='description'}S.H.E：爱而为一演唱会影音馆迅雷下载、免费下载，S.H.E：爱而为一演唱会影音馆Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}S.H.E：爱而为一演唱会影音馆{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-03-14{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://6e:6e@d6.3edyy.com:628/【3E看看www.3ekk.com】S.H.E：爱而为一演唱会影音馆CD1.rmvb" target=_blank>ftftp://6e:6e@d6.3edyy.com:628/【3E看看www.3ekk.com】S.H.E：爱而为一演唱会影音馆CD1.rmvb</A></TD></TR></TBODY></TABLE>CD2：<BR>
<TABLE style="BORDER-BOTTOM: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-RIGHT: #cccccc 1px dotted" border=0 cellSpacing=0 cellPadding=6 width="95%" align=center>
<TBODY>
<TR>
<TD style="WORD-WRAP: break-word" bgColor=#fdfddf><A href="ftftp://7e:7e@d6.3edyy.com:628/【3E看看www.3ekk.com】S.H.E：爱而为一演唱会影音馆CD2.rmvb" target=_blank>ftftp://7e:7e@d6.3edyy.com:628/【3E看看www.3ekk.com】S.H.E：爱而为一演唱会影音馆CD2.rmvb</A></TD></TR></TBODY></TABLE>CD3：<BR>
<TABLE style="BORDER-BOTTOM: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-RIGHT: #cccccc 1px dotted" border=0 cellSpacing=0 cellPadding=6 width="95%" align=center>
<TBODY>
<TR>
<TD style="WORD-WRAP: break-word" bgColor=#fdfddf><A href="ftftp://8e:8e@d6.3edyy.com:628/【3E看看www.3ekk.com】S.H.E：爱而为一演唱会影音馆CD3.rmvb" target=_blank>ftftp://8e:8e@d6.3edyy.com:628/【3E看看www.3ekk.com】S.H.E：爱而为一演唱会影音馆CD3.rmvb</A></TD></TR></TBODY></TABLE></div><ul class="mmlist{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MQ4J340-4XS.jpg{/dede:field}
