{dede:field name='keywords'}小猪历险记/宠物猪猪电影版国英{/dede:field}
{dede:field name='description'}小猪历险记/宠物猪猪电影版国英双语BD1280高清迅雷下载、免费下载，小猪历险记/宠物猪猪电影版国英双语BD1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}小猪历险记/宠物猪猪电影版国英双语BD1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-02-22{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://www.zaslike.com/files/zjxfx37kl244rg0335jd.jpg" /></p>
<p>
	◎译　　名　&quot;小猪&quot;历险记/宠物猪猪电影版<br />
	◎片　　名　Quest for Zhu<br />
	◎导　　演　Bob Doucette<br />
	◎年　　代　2011<br />
	◎国　　家　美国<br />
	◎类　　别　动画<br />
	◎语　　言　国英双语<br />
	◎IMDB评分&nbsp;&nbsp;6.7/10 (37 votes)<br />
	◎IMDB链接&nbsp;&nbsp;<a href="http://www.imdb.com/title/tt2073154/" target="_blank">http://www.imdb.com/title/tt2073154/</a><br />
	◎片　　长　1hrs 12mins<br />
	<br />
	◎简 　 介<br />
	<br />
	&nbsp; &nbsp;&nbsp; &nbsp;这是一个关于四只活泼、年轻的小仓鼠寻找朱宫的感人故事，在那里他们相信自己的梦想会成真。同争强好胜又可爱的Pipsqueak先生、Squiggles, Chunk, Num Nums, 和小臭鼬一起探索Zhuniverse。<br />
	<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120219/23/17870980201202192313165030956764418_002.jpg" style="width: 640px; height: 360px" /><img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120219/23/17870980201202192313165030956764418_000.jpg" style="width: 640px; height: 360px" /></p>
<p>
	<br />
	&nbsp;</p>

<p>
	[下载地址]：<img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-right: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-left: #cccccc 1px dotted; border-bottom: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy241:xiaobajie@222.187.221.241:2037/小八戒电影xiaobajie.com小猪历险记国英双语BD1280高清.mkv">ftp://dy241:xiaobajie@222.187.221.241:2037/小八戒电影xiaobajie.com小猪历险记国英双语BD1280高清.mkv</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1B34550-1S03.jpg{/dede:field}
