{dede:field name='keywords'}未来时速/思绪的速度BD高清迅雷{/dede:field}
{dede:field name='description'}未来时速/思绪的速度BD高清迅雷下载、免费下载，未来时速/思绪的速度BD高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}未来时速/思绪的速度BD高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-10-23{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img165.poco.cn/mypoco/myphoto/20111022/17/62564813201110221719442507596261515_000.jpg" style="width: 700px; height: 901px" /></p>
<p>
	◎译　　名　未来时速/思绪的速度<br />
	◎片　　名　The Speed Of Thought<br />
	◎年　　代　2011<br />
	◎国　　家　美国<br />
	◎类　　别　惊悚<br />
	◎语　　言　英语<br />
	◎IMDB评分 &nbsp;(awaiting 5 votes)<br />
	◎IMDB链接 &nbsp;<a href="http://www.imdb.com/title/tt0847825/" target="_blank">http://www.imdb.com/title/tt0847825/</a><br />
	◎文件格式　X264 + DTS<br />
	◎视频尺寸　1280 x 720<br />
	◎片　　长　94 Mins<br />
	◎导　　演　Evan Oppenheimer<br />
	◎主　　演　尼克&middot;斯塔尔 Nick Stahl ....Joshua Lazarus<br />
	　　　　　　米亚&middot;梅塞德斯 M&iacute;a Maestro ....Anna Manheim<br />
	　　　　　　塔恩&middot;曼宁 Taryn Manning ....Kira<br />
	　　　　　　华莱士&middot;肖恩 Wallace Shawn ....Sandy<br />
	　　　　　　Blair Brown ....Bridger<br />
	　　　　　　Erik Palladino ....Butler<br />
	　　　　　　Alan Cox ....Alexei<br />
	　　　　　　<br />
	◎简　　介　<br />
	<br />
	Joshua具有一个特殊的能力，他可以读出别人的思想。 　　<br />
	<br />
	约书亚拉扎勒斯是一个寄养家庭长大的孩子，他拥有精神感应的能力。他使用他的超能力帮助政府。政府告诉他，他的精神感应能力来自威德曼氏症的副作用，他最终会因为此病而精神错乱乃至死亡。然而一天，拉扎勒斯遇到了一位具有相似能力的女子，这位女子却没有任何该病的征兆，拉扎勒斯于是鼓起勇气去揭露政府的谎言。<br />
	<br />
	Joshua Lazarus (Nick Stahl) possesses a special gift that enables him to read people&#39;s minds, and the government has trained him to use his ability for deadly missions involving national defense, all while telling him that it will ultimately destroy him --- but will it? When Joshua falls in love with Anna (M&iacute;a Maestro), another telepathic &amp;quot;scoper,&amp;quot; he and his friend, Kira (Taryn Manning), must find a cure for their gift and expose the lies.<br />
	<img alt="" src="http://img165.poco.cn/mypoco/myphoto/20111022/20/62564813201110222047583068347371194_003.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img165.poco.cn/mypoco/myphoto/20111022/20/62564813201110222047583068347371194_002.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img165.poco.cn/mypoco/myphoto/20111022/20/62564813201110222047583068347371194_001.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img165.poco.cn/mypoco/myphoto/20111022/20/62564813201110222047583068347371194_000.jpg" style="width: 720px; height: 405px" /><br />
	<br />
	&nbsp;</p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="&#13;&#10;ftp://dy125:piaohua@dy125.piaohua.com:7065/飘花电影piaohua.com未来时速BD中字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:7065/飘花电影piaohua.com未来时速BD中字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O160321F-3Qa.jpg{/dede:field}
