<?php
$z[0]=Array("field","神枪手与咖喱鸡[DVD国语中字无水",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","神枪手与咖喱鸡[DVD国语中字无水印]迅雷下载、免费下载，神枪手与咖喱鸡[DVD国语中字无水印]Gvod高清在线播放，剧情介绍等。",73,233);
$z[1][4]['name']="description";
$z[2]=Array("field","神枪手与咖喱鸡[DVD国语中字无水印]",235,306);
$z[2][4]['name']="title";
$z[3]=Array("field","",308,347);
$z[3][4]['name']="writer";
$z[4]=Array("field","",349,388);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-01-18",390,440);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",442,479);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://4e:4e@www2.3edyy.com:3860/【3E电影院www.3edyy.com】神枪手与咖喱鸡DVD国语中字无水印.rmvb\" target=\"_blank",481,629);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MQ33330-4X47.jpg",631,713);
$z[8][4]['name']="litpic";

?>