{dede:field name='keywords'}李克勤香港小交响乐团演奏厅2011{/dede:field}
{dede:field name='description'}李克勤香港小交响乐团演奏厅2011演唱会BD1280高清迅雷下载、免费下载，李克勤香港小交响乐团演奏厅2011演唱会BD1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}李克勤香港小交响乐团演奏厅2011演唱会BD1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-01-21{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="/uploads/allimg/c120524/133N49123N0-11I95.jpg" style="width: 429px; height: 539px" /></p>
<p>
	【影片简介】</p>
<p>
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 李克勤的歌唱演绎一向有「零瑕疵」的美誉，继2001年的《港乐．克勤Live》演唱会后，再与名指挥家叶咏诗合作，十年后在香港红馆举行一连六场的《李克勤．香港小交响乐团演奏厅》演唱会，以30多首好歌和最新单曲「天河」会知音人，演唱会绝无虚席、好评如潮。<br />
	<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 此次演唱会由赵增熹担任音乐总监，由叶咏诗指挥小交乐手演奏柴可夫斯基、布拉姆斯、Khachaturian等序曲，还有国宝级三弦大师赵太生和英皇口琴大师助阵，加上耳熟能详的流行曲改编成古典乐章，再配合克勤的唱功，古乐流行曲雅俗共赏，令人听出耳油。</p>
<p>
	<img alt="" border="0" height="384" src="/uploads/allimg/c120524/133N49124C0-125051.jpg" width="576" /><img alt="" border="0" height="384" src="/uploads/allimg/c120524/133N49125330-132594.jpg" width="576" /><!--sizeo:3--><br />
	<br />
	<!--/sizeo-->曲目：<br />
	　　01. Tchaikovsky - The Sleeping Beauty : Waltz (香港小交响乐团)<br />
	　　02. Brahms - Hungarian Dance No. 5 in G minor (香港小交响乐团)<br />
	　　03. Brahms - Hungarian Dance No. 5 in G minor (香港小交响乐团 + Rhythm Band)<br />
	　　04. 我不会唱歌<br />
	　　05. 天水&middot;围城<br />
	　　06. 天河<br />
	　　07. 罪人<br />
	　　08. Khachaturian - Sabre Dance (英皇口琴五重奏)<br />
	　　09. 嫲嫲<br />
	　　10. 蓝月亮<br />
	　　11. 深深深<br />
	　　12. 一个人飞<br />
	　　13. 十八板 (赵太生 三弦)<br />
	　　14. 回首<br />
	　　15. 希望<br />
	　　16. 护花使者<br />
	　　17. Medley : 荣誉勋章 / 爱不释手<br />
	　　18. 梦如欢旧 - 旧欢如梦<br />
	　　19. Eduardo di Capua - O Sole Mio (Opus 3)<br />
	　　20. 飞花<br />
	　　21. Bizet - Carmen: Les Tar&eacute;adors (香港小交响乐团)<br />
	　　22. 合久必婚<br />
	　　23. 只想你会意<br />
	　　24. 九月中的陌生人<br />
	　　25. 一生不变<br />
	　　26. 红日<br />
	　　27. 新闻Medley :<br />
	　　i) 萨拉热窝的罗密欧与茱丽叶<br />
	　　ii) 几分钟约会<br />
	　　iii) 最佳位置<br />
	　　iv) 我为何让你走<br />
	　　28. 月半小夜曲<br />
	　　29. 纸婚<br />
	　　30. 大会堂演奏厅<br />
	　　31. 再见穿梭机<br />
	　　32. 花落谁家<br />
	　　33. 好戏之人<br />
	　　34. 再见演奏厅<br />
	　　35. 在我身边<br />
	　　Bonus Tracks:<br />
	　　36. 高妹<br />
	　　37. 告别校园时<br />
	&nbsp;</p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="/uploads/allimg/c120524/133N2Z4FF-102231.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy241:xiaobajie@dy241.piaohua.com:2048/小八戒电影xiaobajie.com李克勤2011年香港小交响乐团演奏厅演唱会720p.rmvb</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120524/133N491260P-14S26.jpg{/dede:field}
