<?php
$z[0]=Array("field","荣耀三九年/烽火家族情/一九三九",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","荣耀三九年/烽火家族情/一九三九[DVD中英双字无水印]迅雷下载、免费下载，荣耀三九年/烽火家族情/一九三九[DVD中英双字无水印]Gvod高清在线播放，剧情介绍等。",73,265);
$z[1][4]['name']="description";
$z[2]=Array("field","荣耀三九年/烽火家族情/一九三九[DVD中英双字无水印]",267,354);
$z[2][4]['name']="title";
$z[3]=Array("field","",356,395);
$z[3][4]['name']="writer";
$z[4]=Array("field","",397,436);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-04-01",438,488);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",490,527);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://3e:3e@m1.3edyy.com:1441/【3E电影院www.eee4.cc】烽火家族情.rmvb\" target=_blank>ftftp://3e:3e@m1.3edyy.com:1441/【3E电影院www.eee4.cc】烽火家族情.rmvb</A></TD></TR></TBODY></TABLE><BR><FONT color=#ff0000 size=2><STRONG>09年英国惊悚爱情战争剧情片《荣耀三九年》DVD中英双字<FONT color=#0938f7>无水印</FONT> [<FONT color=#0968f7 size=4>2010/03/31</FONT>下载地址]：<IMG src=\"httftp://www.3edyy.com/templets/img/down.jpg\" border=0></STRONG></FONT><BR>\r\n<TABLE style=\"BORDER-RIGHT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; BORDER-BOTTOM: #cccccc 1px dotted\" cellSpacing=0 cellPadding=6 width=\"95%\" align=center border=0>\r\n<TBODY>\r\n<TR>\r\n<TD style=\"WORD-WRAP: break-word\" bgColor=#fdfddf><A href=\"ftftp://3e:3e@xl.3edyy.com:3994/【3E电影院www.eee4.cc】荣耀三九年DVD中英双字无水印.rmvb\" target=_blank>ftftp://3e:3e@xl.3edyy.com:3994/【3E电影院www.eee4.cc】荣耀三九年DVD中英双字无水印.rmvb</A></TD></TR></TBODY></TABLE></div><ul class=\"mmlist",529,1569);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MP60L50-39424.jpg",1571,1654);
$z[8][4]['name']="litpic";

?>