{dede:field name='keywords'}第十九届东方风云榜颁奖典礼HD12{/dede:field}
{dede:field name='description'}第十九届东方风云榜颁奖典礼HD1280高清迅雷下载、免费下载，第十九届东方风云榜颁奖典礼HD1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}第十九届东方风云榜颁奖典礼HD1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-04-10{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="/uploads/allimg/c120525/133O0b5G0-1553Y.jpg" style="width: 549px; height: 280px" /></p>
<p>
	&nbsp;4月7日下午3点，&ldquo;第19届东方风云榜颁奖盛典&rdquo;通过动感101及东方风云榜官方网站公布今年部分奖项归属。许嵩、刘惜君（微博）、汪峰（微博）、丁当、严艺丹、牛奶咖啡、胡彦斌、薛之谦、付辛博等歌手的作品获得年度十大金曲；周笔畅凭借《黑&middot;择&middot;明》获得年度专辑大奖；李宇春获全能艺人奖。<br />
	<br />
	&nbsp; &nbsp; &nbsp;今晚，第19届东方风云榜颁奖盛典将在上海梅赛德斯-奔驰文化中心携手30余组艺人，上演华语歌坛年度终极盛典，引爆上万歌迷的大狂欢。现场还将揭晓本年度最佳男女歌手、华语五强、年度风云歌手以及最佳作词、最佳作曲奖。<br />
	<br />
	&nbsp; &nbsp; &nbsp;首次在颁奖盛典前公布部分奖项，这在东方风云榜近20年的历史上也是第一次。主办方表示，与往年在颁奖盛典现场揭晓奖项归属不同，今年提前公布部分奖项的方式，是为了呈现一场完整、流畅的群星盛典秀。事实上，国际上如格莱美颁奖礼等音乐奖项，都会提前公布奖项归属，而将精彩的歌手表演留到盛典现场。<br />
	<br />
	&nbsp; &nbsp; &nbsp;今年东方风云榜上榜歌曲甄选范围从2011年1月15日至2012年1月15日。年度十大金曲从2月8日起启动评选，截止到4月5日。在此期间，88首歌曲通过动感101各档节目滚动播出，并通过开通网络投票，由歌迷、DJ以及东方风云榜评审团综合评分，并最终从88首金曲中决出年度10大金曲。<br />
	<br />
	&nbsp; &nbsp; &nbsp;每年东方风云榜十大金曲以及各大奖项归属，都是当年内地原创流行歌坛的重要成绩表之一，而东方风云榜颁奖盛典，也成为一年一度的乐坛盛事。今晚，颁奖盛典将通过东方卫视向全球播出，展现华语歌坛的最炫风采。<br />
	<br />
	<br />
	<b>第19届东方风云榜部分奖项名单:</b><br />
	<br />
	<b>【年度十大金曲】</b><br />
	<br />
	《怎么唱情歌》-刘惜君<br />
	<br />
	《想象之中》-许嵩<br />
	<br />
	《存在》-汪峰<br />
	<br />
	《冷血动物》-丁当<br />
	<br />
	《三寸天堂》-严艺丹<br />
	<br />
	《明天，你好》-牛奶咖啡<br />
	<br />
	《一万光年》-胡彦斌<br />
	<br />
	《我终于成了别人的女人》-薛之谦<br />
	<br />
	《我，一个人》-付辛博<br />
	<br />
	《故意》-王啸坤<br />
	<br />
	<br />
	<b>【年度专辑】</b><br />
	<br />
	《黑&middot;择&middot;明》-周笔畅<br />
	<br />
	<br />
	<b>【最佳年度飞跃】</b><br />
	<br />
	刘惜君 付辛博<br />
	<br />
	<br />
	<b>【最佳唱作人】</b><br />
	<br />
	许嵩<br />
	<br />
	<br />
	<b>【传媒推荐大奖】</b><br />
	<br />
	丁当 胡彦斌<br />
	<br />
	<br />
	<b>【最佳组合】</b><br />
	<br />
	牛奶咖啡<br />
	<br />
	<br />
	<b>【全能艺人】</b><br />
	<br />
	李宇春<br />
	<br />
	<br />
	<b>【最佳乐队】</b><br />
	<br />
	果味VC<br />
	<br />
	<br />
	<b>【东方新人】</b><br />
	<br />
	陈翔 张超 王野<br />
	<br />
	<br />
	<b>【年度对唱歌曲】</b><br />
	<br />
	《Love Surrounds Me》-毛方圆 蔡岫勍</p>
<p>
	<img alt="" src="/uploads/allimg/c120525/133O0b5X20-161F4.jpg" style="width: 720px; height: 405px" /><img alt="" src="/uploads/allimg/c120525/133O0b5c50-1G436.jpg" style="width: 720px; height: 405px" /><img alt="" src="/uploads/allimg/c120525/133O0b61230-1Q052.jpg" style="width: 720px; height: 405px" /><br />
	&nbsp;</p>
<p>
	【下载地址】</p>
<table bgcolor="#0099cc" border="0" cellpadding="10" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：http://www.xiaozhizhu.net</td>
		</tr>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy125:piaohua@dy125.piaohua.com:7826/飘花电影piaohua.com第十九届东方风云榜颁奖典礼HD1280高清.rmvb</td>
		</tr>
		<tr>
		</tr>
	</tbody>
</table>
<br />{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O0b62340-193X4.jpg{/dede:field}
