{dede:field name='keywords'}2012元旦晚会湖南卫视2012跨年演{/dede:field}
{dede:field name='description'}2012元旦晚会湖南卫视2012跨年演唱会迅雷下载、免费下载，2012元旦晚会湖南卫视2012跨年演唱会Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}2012元旦晚会湖南卫视2012跨年演唱会{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-01-02{/dede:field}
{dede:field name='body'}<p>
	<img alt="" border="0" height="566" src="/uploads/allimg/c120525/133O0a60R0-193H6.jpg" width="400" /></p>
<p>
	2012快乐中国湖南卫视跨年演唱会</p>
<p>
	时间：2011年12月31日19：30</p>
<p>
	地点：广州国际体育演艺中心</p>
<p>
	2012湖南卫视跨年演唱会主持人：李湘 何炅 谢娜 吴昕 杜海涛 李维嘉 汪涵</p>
<p>
	<br />
	&nbsp;</p>
<p>
	2012湖南卫视跨年演唱会（专题）节目单</p>
<p>
	1、开场秀及主题曲，表演艺人：出场嘉宾 主持人　高清图<br />
	2、魏晨《破晓》、魏晨+赵靓《goodbye goodbye》　高清图<br />
	3、吴建豪《is it all》、《说爱就爱》　高清图<br />
	4、莫文蔚《宝贝》《如果没有你》《打起手鼓唱起歌》　高清图<br />
	5、洪辰、李佳璐《无法原谅》　高清图<br />
	6、蔡国庆、李斯丹妮、李菲儿《三百五十六个祝福》高清图<br />
	7、魔术连线,韩国连线<br />
	8、范琪玮《最重要的决定》《那些花儿》　高清图<br />
	9、至上励合、李斯丹妮《奋斗》<br />
	10、筷子兄弟、刘忻《老男孩》　高清图<br />
	11、陈翔《如果遇见你》　高清图<br />
	12、陶喆《黑色柳丁》《小镇姑娘》《就是爱你》《普通朋友》《Susan 说》《爱很简单》《找自己》　高清图<br />
	13、龚琳娜、赵守镇、阮明园《帅女人》　高清图<br />
	14、刘心、武艺、谭杰希、王野、姜潮HIGH歌《脱掉》<br />
	15、谭维维《HOLD不住》　高清图<br />
	16、江映蓉《热门花招》　高清图<br />
	17、余文乐《给我一杯》　高清图<br />
	18、萧亚轩《潇洒小姐》《我爱我》《最熟悉的陌生人》　高清图<br />
	19、段林希、洪辰、刘忻、苏妙玲《Show time》<br />
	20、慕容晓晓、姜潮、王野、谭杰希《爱情买卖》　高清图<br />
	21、苏醒《思念》<br />
	22、李炜《绿叶对根的情谊》<br />
	23、毛阿敏《love the way you lie》、苏醒《让梦冬眠》、毛阿敏、李炜《Hey jude》 高清图<br />
	24、吴奇隆《祝你一路顺风》、吴奇隆+刘诗诗《等你的季节》　高清图<br />
	25、梁静茹《可惜不是你》《分手快乐》《勇气》《宁夏》《情歌》　高清图<br />
	26、张杰《火鸟》《让你依靠》《第一夫人》　高清图<br />
	27、蔡依林 《七上八下》《看我七十二变》《舞娘》《美人计》《日不落》 高清图<br />
	28、李宇春 《对不起，只是忽然很想你》《下个路口见》《皇后与梦想》《会跳舞的文艺青年》 高清图<br />
	29、丁建中 魔术《穿越小蛮腰》<br />
	30、王菲 《愿》 高清图<br />
	31、曾轶可《baby sister》、严艺丹《三寸天堂》、郁可唯+杨洋《听你说》、至上励合《咬耳朵》<br />
	32、唐笑《calling it off》、MIC《get it hot》<br />
	33、段林希《我相信》、武艺+苏妙玲《红日》、刘心+李霄云《离开地球表面》<br />
	34、结束曲《一起来心跳》</p>
<p>
	<br />
	--------------------------------------------------------------------------------</p>
<p>
	[下载地址]：&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				&nbsp;ftp://dy44:piaohua@dy44.piaohua.com:2494/飘花电影piaohua.com湖南卫视跨年演唱会CD1.rmvb</td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				&nbsp;ftp://dy44:piaohua@dy44.piaohua.com:2494/飘花电影piaohua.com湖南卫视跨年演唱会CD2.rmvb</td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				&nbsp;ftp://dy44:piaohua@dy44.piaohua.com:2494/飘花电影piaohua.com湖南卫视跨年演唱会CD3.rmvb</td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				&nbsp;ftp://dy44:piaohua@dy44.piaohua.com:2494/飘花电影piaohua.com湖南卫视跨年演唱会CD4.rmvb</td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				&nbsp;ftp://dy44:piaohua@dy44.piaohua.com:2495/飘花电影piaohua.comCCTV-2012元旦晚会CD1.rmvb</td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				&nbsp;ftp://dy44:piaohua@dy44.piaohua.com:2495/飘花电影piaohua.comCCTV-2012元旦晚会CD2.rmvb</td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				&nbsp;ftp://dy44:piaohua@dy44.piaohua.com:2495/飘花电影piaohua.comCCTV-2012元旦晚会CD3.rmvb</td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				&nbsp;ftp://dy44:piaohua@dy44.piaohua.com:2495/飘花电影piaohua.comCCTV-2012元旦晚会CD4.rmvb</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O0a61510-2035H.jpg{/dede:field}
