{dede:field name='keywords'}面引子DVD国语中字2011台湾剧情{/dede:field}
{dede:field name='description'}面引子DVD国语中字2011台湾剧情迅雷下载、免费下载，面引子DVD国语中字2011台湾剧情Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}面引子DVD国语中字2011台湾剧情{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-25{/dede:field}
{dede:field name='body'}<p>
	<img src="http://img2081.poco.cn/mypoco/myphoto/20120524/14/56643687201205241430252880392008185_004.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 858px; border-top: 0px solid; border-right: 0px solid" /></p>
<p>
	◎译　　名　面引子<br />
	◎片　　名　Four hands/Mian Yin Zi<br />
	◎年　　代　2011<br />
	◎国　　家　中国台湾<br />
	◎类　　别　剧情<br />
	◎语　　言　普通话<br />
	◎字　　幕　中文<br />
	◎IMDB评分 N/A<br />
	◎IMDB链接 N/A<br />
	◎文件格式　DVD-RMVB<br />
	◎视频尺寸　720 x 416<br />
	◎文件大小　1CD 567MB<br />
	◎片　　长　1hr 51mn<br />
	◎导　　演　李佑宁 Youning Li<br />
	◎主　　演　吴兴国 Wu Hsing-Kuo<br />
	　　　　　　叶全真 Chuan Chen Yeh<br />
	　　　　　　耿乐 Le Geng<br />
	　　　　　　赵仕瑾 Shijin Zhao<br />
	　　　　　　张雁名 Enson<br />
	　　　　　　李宗翰 Zonghan Li<br />
	　　　　　　李天柱 Tianzhu Li<br />
	　　　　　　夏靖庭 Ching-ting Hsia<br />
	　　　　　　</p>
<p>
	◎简　　介　</p>
<p>
	　　一部以全新的视角诠释两岸关系和两岸探亲题材的电影，它以&ldquo;少小离家&rdquo;、客居台湾六十年的老兵们对故乡和亲人的无限思念、&ldquo;老大归&rdquo;却又&ldquo;近乡情怯&rdquo;的特殊心情为主线，讲述了那一特殊历史大环境下的时代变迁、战争的洗礼对&ldquo;独在异乡为异客&rdquo;的人们、对家庭造成的难以磨灭的影响，和两岸几十年割舍不断的情感。</p>
<p>
	<br />
	◎影片截图</p>
<p>
	&nbsp;</p>
<p>
	<img border="0" src="http://img2081.poco.cn/mypoco/myphoto/20120524/14/56643687201205241430252880392008185_002.jpg" /></p>
<p>
	<img border="0" src="http://img2081.poco.cn/mypoco/myphoto/20120524/14/56643687201205241430252880392008185_003.jpg" /></p>
<p>
	<img border="0" src="http://img2081.poco.cn/mypoco/myphoto/20120524/14/56643687201205241430252880392008185_000.jpg" /></p>
<p>
	<img border="0" src="http://img2081.poco.cn/mypoco/myphoto/20120524/14/56643687201205241430252880392008185_001.jpg" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.netftp//dy44:piaohua@dy44.piaohua.com:3193/" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3493/飘花电影piaohua.com面引子DVD国语中字.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3493/飘花电影piaohua.com面引子DVD国语中字.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O14b3C0-3J95.jpg{/dede:field}
