{dede:field name='keywords'}关键一击DVD中字韩国2011喜剧迅{/dede:field}
{dede:field name='description'}关键一击DVD中字韩国2011喜剧迅雷下载、免费下载，关键一击DVD中字韩国2011喜剧Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}关键一击DVD中字韩国2011喜剧{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-04-19{/dede:field}
{dede:field name='body'}<p>
	<img alt="" height="1081" src="http://img170.poco.cn/mypoco/myphoto/20120416/15/64486803201204161557094171027764362_010.jpg" width="760" /></p>
<p>
	◎中 文 名　关键一击<br />
	◎英 文 名　Punch.Line<br />
	◎原　　名　&#44208;&#51221;&#51201; &#54620;&#48169;&nbsp;<br />
	◎年　　代　2011<br />
	◎国　　家　剧情/喜剧&nbsp;&nbsp;&nbsp;<br />
	◎片　　长　100分钟<br />
	◎导　　演　朴重九&nbsp;&nbsp; Jung-gu Park&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br />
	◎主　　演　柳东根&nbsp;&nbsp; Dong-geun Yun&nbsp;&nbsp;<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 金祯勋&nbsp;&nbsp; Jeong-hun Kim&nbsp;&nbsp;<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 尹珍瑞&nbsp;&nbsp; Jin-seo Yun&nbsp;&nbsp;&nbsp;<br />
	◎剧&nbsp;&nbsp;&nbsp;&nbsp; 情</p>
<p>
	<br />
	&nbsp;&nbsp; 　　《关键人物》是由朴重九导演执导的一部喜剧电影，影片讲述的是清廉刚正的新任长官一心想要打造自己的清廉政治人生，在上任之后克服种种困难反贪腐的过程，此外还将展现他在私下作为一个父亲的日常生活。<br />
	　　<br />
	　　尹珍瑞在片中扮演的是被新任长官任命的辅佐官&ldquo;夏英&rdquo;一角。在影片中她是一个充满了激情的新生代精英辅佐官，在上班时间绝对是一个拼命工作的热血公务员，然而到了下班时间后她却成为一个徘徊在寻找幸福道路上的剩女，是一个性格十分可爱明朗的角色。</p>
<p>
	◎截&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 图</p>

<p>
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120416/15/54726759201204161541332661997315988_000.jpg" /></p>
<p>
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120416/15/54726759201204161541332661997315988_001.jpg" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.netftp//dy44:piaohua@dy44.piaohua.com:3193/" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3254/飘花电影piaohua.com关键一击DVD中字.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3254/飘花电影piaohua.com关键一击DVD中字.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15E120-2TD.jpg{/dede:field}
