<?php
$z[0]=Array("field","七磅/七生有幸/七重天BD中英双字",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","七磅/七生有幸/七重天BD中英双字1024/1280高清迅雷下载、免费下载，七磅/七生有幸/七重天BD中英双字1024/1280高清Gvod高清在线播放，剧情介绍等。",73,253);
$z[1][4]['name']="description";
$z[2]=Array("field","七磅/七生有幸/七重天BD中英双字1024/1280高清",255,336);
$z[2][4]['name']="title";
$z[3]=Array("field","",338,377);
$z[3][4]['name']="writer";
$z[4]=Array("field","",379,418);
$z[4][4]['name']="source";
$z[5]=Array("field","2012-03-28",420,470);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",472,509);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://e15:e15@xl2.eee4.com:9219/[3E电影站www.eee4.com]七磅[DVD中英双字1024x576高清版].rmvb\" target=\"_blank",511,656);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MP1V2F-2a57.jpg",658,739);
$z[8][4]['name']="litpic";

?>