{dede:field name='keywords'}蔚蓝深海/深海迷情BD1280高清迅{/dede:field}
{dede:field name='description'}蔚蓝深海/深海迷情BD1280高清迅雷下载、免费下载，蔚蓝深海/深海迷情BD1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}蔚蓝深海/深海迷情BD1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-04-19{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120419/08/62564813201204190825227720490304191_000.jpg" style="width: 700px" /></p>
<p>
	◎译　　名　蔚蓝深海/深海迷情(台)<br />
	◎片　　名　The Deep Blue Sea<br />
	◎年　　代　2011<br />
	◎国　　家　美国/英国<br />
	◎类　　别　剧情/爱情<br />
	◎语　　言　英语<br />
	◎字　　幕　中字<br />
	◎IMDB评分 &nbsp; 6.1/10 (847 votes)<br />
	◎IMDB链接 &nbsp; <a href="http://www.imdb.com/title/tt1700844" target="_blank">http://www.imdb.com/title/tt1700844</a><br />
	◎文件格式　x264 + DTS<br />
	◎片　　长　98 mins<br />
	◎导　　演　特伦斯&middot;戴维斯 Terence Davies<br />
	◎主　　演　蕾切尔&middot;薇姿 Rachel Weisz ....Hester Collyer<br />
	　　　　　　汤姆&middot;希德勒斯顿 Tom Hiddleston ....Freddie Page<br />
	　　　　　　西蒙&middot;拉塞尔&middot;比尔 Simon Russell Beale ....William Collyer<br />
	　　　　　　Karl Johnson ....Miller<br />
	　　　　　　Ann Mitchell ....Mrs. Elton<br />
	　　　　　　Harry Hadden-Paton ....Jackie Jackson<br />
	　　　　　　Sarah Kants ....Liz Jackson<br />
	　　　　　　Jolyon Coy ....Philip Welch<br />
	　　　　　　Elisha Stimson ....Aldwych evacuee (uncredited)<br />
	　　　　　　Barbara Jefford ....Mrs. Collyer<br />
	　　　　　　Danny de Warren ....Aldwych evacuee (uncredited)<br />
	<br />
	<b>◎简　　介</b><br />
	<br />
	<br />
	<b>剧情</b><br />
	<br />
	&nbsp; &nbsp; &nbsp;影片改编自特伦斯&middot;拉提恩的同名话剧作品，曾由费雯丽主演搬上过银幕，讲述了一名高级法官妻子同一名军官之间的外遇事件。<br />
	<br />
	&nbsp; &nbsp; &nbsp;影片的主角是海斯特&middot;克莱尔夫人，她是一位英国律师的妻子，过着波澜不惊的婚姻生活，内心的空虚与日俱增。随之对邻家男子&mdash;&mdash;前皇家空军飞行员弗莱迪（汤姆&middot;希德勒斯顿扮演，旧版中由英国名角肯尼斯&middot;摩尔扮演）展开一场飞蛾扑火般的绝望爱恋。让刚刚经历了感情挫折的薇姿来演出克莱尔夫人这个角色，虽然残酷，却也更加贴切。而两人在镜头前欲言又止的暧昧神态也令人神伤。<br />
	<br />
	&nbsp; &nbsp; &nbsp;《蔚蓝深海》背景设置在上世纪五十年代。女主人公赫斯特&middot;科尔耶是高等法官科尔耶爵士的妻子，她比丈夫年轻很多。赫斯特爱上了一名年轻英俊的空军飞行员，名叫弗雷迪&middot;佩吉，后者因为战争中的记忆而备受折磨。<br />
	<br />
	　　影片的大部分场景发生在赫斯特的公寓内。那天，她打算亲手结束自己的生命并并未成功。我们通过她的回忆了解到了她的外遇以及婚姻。赫斯特同爵士之间，虽然相敬如宾互相爱慕但缺少激情。<br />
	<br />
	　　赫斯特与佛莱迪的外遇被人发现之后，她与过去舒适的生活告别搬进了伦敦一件狭小的公寓，打算同佛莱迪重新开始。然而，弗雷迪尽管能给与她想要的激情，却不能像她的丈夫一样给她爱和安全感。赫斯特处在进退两难的境地中。<br />
	<br />
	<br />
	<br />
	<b>一句话评论</b><br />
	<br />
	<br />
	无论是蕾切尔&middot;薇姿还是汤姆&middot;希德勒斯顿的表演都无懈可击。<br />
	<br />
	片中的镜头和镜头中的阴影无时不刻地在提醒着我们，这一切情感和欲望，都是冰冷而残酷的。<br />
	<br />
	影片中的女主角做出了抉择，她放弃了舒适的生活，走入了简单的生活。她追随的不是爱情，而是欲望。<br />
	<br />
	影片在浪漫情绪和紧张氛围中找到了平衡点。<br />
	<br />
	从故事角度上说，影片具有局限性，但是蕾切尔&middot;薇姿的那张纠结与充满了内心戏的脸，却让这部电影跨越了时间的沟壑。<br />
	<br />
	<br />
	<br />
	<b>幕后制作</b><br />
	<br />
	<br />
	　　《蔚蓝深海》由特伦斯&middot;戴维斯改编自Terence Rattigan发表于50年代的同名经典戏剧，讲述的是关于性爱、通奸和罪恶感的故事。影片在多伦多电影节上映之后反响颇佳，有人将之形容为&ldquo;美丽、心碎、令人眩晕&rdquo;，蕾切尔&middot;薇姿的演技也颇受好评。费雯&middot;丽在1955年曾主演过旧版，不过属于其演艺生涯后期的作品，反响平平，剧中角色被普遍认为并不适合由她演出。<br />
	<br />
	　　<b>改编剧本</b><br />
	<br />
	　　对于这部电影来说，改编一个可以和原版剧作相提并论的剧本是重中之重，不过，这个工作对于导演特伦斯&middot;戴维斯来说，却是充满了挑战的。他说：&ldquo;我从来没有改编过什么话剧作品，但是制片人西恩&middot;奥康纳却鼓励我说，让我试试可以改编下特伦斯&middot;拉提恩的作品。于是，我看了他的所有话剧，然后决定可以试试改编《蔚蓝深海》。在《蔚蓝深海》中，拉提恩把所有的情感冲突、个性展示以及人物关系的表达都放在了第一幕中，不巧的是，我很不喜欢第一幕。当然，我很欣赏而且尊敬拉提恩的戏剧水准和技巧。只是这一幕太具有拉提恩的风格了。在改编的过程中，我一直在脑海中保持着女主角，也就是海斯特的情感，我是站在她的角度，来改编剧本的。在我的印象里，我为这部电影重新写了不少台词，全都是为了展示海斯特的心理而创作的。也就是说，在这部电影里，海斯特不仅仅是主角，更是影片的线索和灵魂。&rdquo;<br />
	<br />
	　　关于影片的剧本，蕾切尔&middot;薇姿说：&ldquo;我从来没有看过特伦斯&middot;拉提恩的原著，但是戴维斯却非常优美，它淋漓尽致地刻画了一个女人的心理。那些台词和独白，就像是诗歌一样动人而且美妙。所以，在看到这个剧本之后，我就决定要在影片里扮演海斯特一角了。我觉得，一个被编剧塑造得这么完整而且有深度的角色，是每个演员可遇而不可求的。<br />
	<br />
	　　<b>反时代剧</b><br />
	<br />
	　　影片的故事发生在1950年代，正值冷战时期。所以，在原著话剧里，那种冷峻、慌张、一触即发的感受比比皆是。可是到了电影中，冷战的痕迹非常浅淡，取而代之的是一种人性之间的不确定和慌张感。对于这样的改编，制片人西恩&middot;奥康纳将其称之为&ldquo;反时代剧&rdquo;。 特伦斯&middot;戴维斯说：&ldquo;这是对原作最大的改编，因为我只是很简单地喜欢一个女人，一个人，静静地站在窗台前的镜头。所以，这部电影都是由情而生的。关于时代、冷战或者是当时社会环境的那些元素，我不是很有兴趣。&rdquo;<br />
	<br />
	　　谈及这些，蕾切尔&middot;薇姿也表示说，自己是看中了影片的内在而不是社会意义才来参演的。她说：&ldquo;我对故事里的那种社会背景方面的事情并不是太重视。影片、剧本所吸引我的是那些关于人性，爱情、欲望和生活本身的描绘。因为这些内容是持久且永恒的。我觉得，这部电影讲述的是一个关于发现自己的故事。我扮演的海斯特从来没有感受到爱、欲望和激情。但是在出轨之后，她却感受到了做一个女人的感受。于是她的内心开始转变，发现了自己的欲望和需求，于是便抛弃了自己的生活。可是，在找到这些并有了觉醒的同时，她的一切也都破碎了，无论是家庭还是社会地位，都不复存在。我觉得，这就是这部电影最大的魅力&mdash;&mdash;它展示出了那些我们不曾面对的东西。&rdquo;<br />
	<br />
	<br />
	<br />
	<b>花絮</b><br />
	<br />
	&middot;影片2010年底开拍，2011年在英国上映，当时正好是原作者Terence Rattigan的诞辰一百周年。<br />
	&middot;影片在2011年9月加拿大多伦多电影节上举行全球首映。<br />
	&middot;影片导演特伦斯&middot;戴维斯是在看了《碧海奇缘》这部电影后才发现蕾切尔&middot;薇姿有着惊人的表演才华的。于是他找来自己的经纪人，希望能请蕾切尔&middot;薇姿来出演这部电影。当时，特伦斯&middot;戴维斯并不知道蕾切尔&middot;薇姿是谁，所以他问经纪人是不是知道&ldquo;这么一个女演员的存在&rdquo;。他的经纪人半开玩笑地说：&ldquo;这个女演员拿过奥斯卡&rdquo;。后来，蕾切尔&middot;薇姿知道了这件事，她也半开玩笑地说：&ldquo;看来特伦斯&middot;戴维斯对非黑白电影的女演员并不是那么熟悉。&rdquo;（蕾切尔&middot;薇姿说这句话的原因是，特伦斯&middot;戴维斯拍摄了很多黑白电影。）<br />
	&middot;本片是芭芭拉&middot;杰福特（Barbara Jefford）在《第九道门》之后出演的第一部电影。这中间，整整过去了十二年。</p>
<p>
	<img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120419/08/62564813201204190812194184831656636_002.jpg" style="width: 650px; height: 366px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120419/08/62564813201204190812194184831656636_001.jpg" style="width: 650px; height: 366px" /><img alt="" src="http://img170.poco.cn/mypoco/myphoto/20120419/08/62564813201204190812194184831656636_000.jpg" style="width: 650px; height: 366px" /><br />
	<br />
	&nbsp;</p>
<p>
	【下载地址】</p>
<table bgcolor="#0099cc" border="0" cellpadding="10" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.net" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy125:piaohua@dy125.piaohua.com:7873/飘花电影piaohua.com蔚蓝深海BD中字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:7873/飘花电影piaohua.com蔚蓝深海BD中字1280高清.rmvb</a></td>
		</tr>
		<tr>
		</tr>
	</tbody>
</table>
<br />{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15U3R0-1Y29.jpg{/dede:field}
