{dede:field name='keywords'}台湾惊点2D版BD1280高清迅雷下载{/dede:field}
{dede:field name='description'}台湾惊点2D版BD1280高清迅雷下载、免费下载，台湾惊点2D版BD1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}台湾惊点2D版BD1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-02-24{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="/uploads/allimg/c120524/133N4V52350-193528.jpg" style="width: 383px; height: 489px" /></p>
<p>
	◎译　　名　台灣驚點<br />
	◎片　　名　Timeless - Taiwan 2010<br />
	◎年　　代　2010<br />
	◎地　　区　台湾<br />
	◎类　　别　风光/记录<br />
	◎语　　言　国语<br />
	◎字　　幕　中文<br />
	◎IMDB评分<br />
	◎IMDB链接<br />
	◎片　　长　42 mins 3 seconds<br />
	<br />
	◎简　　介<br />
	<br />
	　　描绘台湾之美的【3D世纪台湾：惊艳福尔摩沙】，内容台湾在地风景民俗 , 也是影碟国片市场上第一个用3D方式为咱们台湾写自传的作品。<br />
	这种逼真的立体影像出现在台湾各地的名胜古迹、自然风景中，透过3D摄影机的拍摄，古迹跳出一种以前从来没有看过的风貌，尤其是太鲁阁峡谷、苏花公路清水断崖等场景，画面能呈现出极为壮魄的气势，3D效果创造出大景深的画面魅力，海、天、山等都能呈现出带有距离感的效果，现场感很真实。<br />
	<br />
	　　用3D画面来看台湾知名建筑物也别有一番风味，国父纪念馆、101 大楼、中正纪念堂、赤崁楼、孔庙、鹅銮鼻灯塔、龙山寺&#8943;建物都能呈现出边缘锐利、画质清晰的逼真的立体感！<br />
	<br />
	<br />
	01. 台北_国父纪念馆<br />
	02. 台北_二二八和平纪念公园<br />
	03. 台北_故宫<br />
	04. 台北_圆山饭店<br />
	05. 台北_中正纪念堂<br />
	06. 北投_温泉博物馆<br />
	07. 艋舺_龙山寺<br />
	08. 高雄_爱河<br />
	09. 台北_平溪_天灯<br />
	10. 高雄_爱河<br />
	11. 台北 灯节<br />
	12. 台北_平溪_十分寮瀑布<br />
	13. 花莲_太鲁阁<br />
	14. 台北_野柳_女王头<br />
	15. 垦丁_龙坑生态保护区<br />
	16. 苏花公路_清水断崖<br />
	17. 台南_亿载金城<br />
	18. 台南_赤崁楼<br />
	19. 水里蛇窑<br />
	20. 台北_忠烈祠<br />
	21. 传统民俗_官将首<br />
	22. 高雄_寿山公园<br />
	23. 台南_白河_莲花<br />
	24. 台湾花卉_蝴蝶兰<br />
	25. 宜兰_大湖<br />
	26. 南投 赛德克族<br />
	27. 垦丁_鹅銮鼻灯塔<br />
	28. 台北_中正纪念堂<br />
	<br />
	<img alt="" src="/uploads/allimg/c120524/133N4V53220-2013P.jpg" style="width: 640px; height: 360px" /><img alt="" src="/uploads/allimg/c120524/133N4V54020-216062.jpg" /><img alt="" src="/uploads/allimg/c120524/133N4V54O0-22NQ.jpg" style="width: 640px; height: 360px" /></p>

<p>
	[下载地址]：<img border="0" src="/uploads/allimg/c120524/133N2Z4FF-102231.jpg" />
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-right: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-left: #cccccc 1px dotted; border-bottom: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				ftp://dy241:xiaobajie@222.187.221.241:2042/小八戒电影xiaobajie.com台湾惊点2D版BD1280高清.rmvb</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120524/133N4V5550-235516.jpg{/dede:field}
