<?php
$z[0]=Array("field","虫虫特攻队/虫虫危机/昆虫总动员",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","虫虫特攻队/虫虫危机/昆虫总动员BD中英双字1024高清迅雷下载、免费下载，虫虫特攻队/虫虫危机/昆虫总动员BD中英双字1024高清Gvod高清在线播放，剧情介绍等。",73,263);
$z[1][4]['name']="description";
$z[2]=Array("field","虫虫特攻队/虫虫危机/昆虫总动员BD中英双字1024高清",265,351);
$z[2][4]['name']="title";
$z[3]=Array("field","",353,392);
$z[3][4]['name']="writer";
$z[4]=Array("field","",394,433);
$z[4][4]['name']="source";
$z[5]=Array("field","2012-02-27",435,485);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",487,524);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://eee4.com:8114@vip11.eee4.com:8114/[3E迅雷电影站www.eee4.com]虫虫特工队DVD中英双字CD1.rmvb\" target=\"_blank",526,676);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MQ11L10-59146.jpg",678,761);
$z[8][4]['name']="litpic";

?>