{dede:field name='keywords'}巴厘岛-世界上最美丽的地方[1024{/dede:field}
{dede:field name='description'}巴厘岛-世界上最美丽的地方[1024x576高清版]迅雷下载、免费下载，巴厘岛-世界上最美丽的地方[1024x576高清版]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}巴厘岛-世界上最美丽的地方[1024x576高清版]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2009-01-08{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://e13:e13@xl2.eee4.com:9916/[3E电影站www.eee4.com]巴厘岛.rmvb" target="_blank{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MP45L60-4V05.jpg{/dede:field}
