{dede:field name='keywords'}2012年央视春节联欢晚会迅雷下载{/dede:field}
{dede:field name='description'}2012年央视春节联欢晚会迅雷下载、免费下载，2012年央视春节联欢晚会Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}2012年央视春节联欢晚会{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-01-27{/dede:field}
{dede:field name='body'}<p>
	<img alt="" border="0" class="topic" jquery1327297428671="16" oldblock="inline" src="http://www.sinaimg.cn/dy/slidenews/4_img/2012_03/703_558342_995414.jpg" style="width: 600px; display: inline; height: 848px; cursor: pointer" /></p>
<p>
	节目单如下：</p>
<p>
	　　1.开场童谣(表演者：邓鸣贺)</p>
<p>
	　　2.《东西南北大拜年》</p>
<p>
	　　(1)《欢乐中国年》(表演者：李谷一、王珞丹(微博)、冯绍峰(微博)、蔡卓妍(微博)、主持人)</p>
<p>
	　　(2)《闹秧歌》(表演者：胡宝善、胡军(微博)一家)</p>
<p>
	　　(3)《小拜年》(表演者：胡海泉(微博)一家、陈羽凡(微博)、白百何(微博)夫妇)</p>
<p>
	　　(4)《采茶舞曲》(表演者：沙溢(微博)、胡可夫妇)</p>
<p>
	　　(5)《祝福你》(表演者：张卫健(<a href="http://www.anzhuo4.com/" style="color: rgb(0, 0, 0); text-decoration: none;">安卓游戏</a>微博)、张茜(微博)夫妇)</p>
<p>
	　　3.绛州鼓乐《鼓韵龙腾》(表演者：山西绛州鼓乐团、河南登封少林塔沟武术学校)</p>
<p>
	　　4.群口相声《小合唱》(表演者：周炜、<a href="http://www.dailiv.com/" style="color: rgb(0, 0, 0); text-decoration: none;">在线代理</a>佟铁鑫、吕继宏、王宏伟、刘和刚(微博))</p>
<p>
	　　5.创意钢琴《金蛇狂舞》+ 歌曲《龙的传人》(表演者：王力宏(微博)、李云迪(微博))</p>
<p>
	　　6.创意儿童节目《除夕的传说》(表演者：韩庚(微博))</p>
<p>
	　　7.歌曲《万物生》(表演者：萨顶顶(微博))</p>
<p>
	　　8.小品《天网恢恢》(表演者：蔡明(微博)、王宁、常远、郭丰周)</p>
<p>
	　　9.舞蹈《龙凤呈祥》(领舞：李倩(微博)、张傲月)</p>
<p>
	　　10.短片《回家过年》</p>
<p>
	　　11.歌曲《好久没回家》(表演者：陈坤(微博))</p>
<p>
	　　12.歌曲《叫一声爸妈》(表演者：)</p>
<p>
	　　13.小品《荆轲刺秦》(表演者：黄宏、邵峰、沙溢)</p>
<p>
	　　14.杂技《空山竹语》(表演者：李振宇、左朝峰、袁飞)</p>
<p>
	　　15.民族歌舞《追爱》(表演者：雷佳(微博)、沙呷俊男<a href="http://www.6dtaobao.com/" style="color: rgb(0, 0, 0); text-decoration: none;">淘宝网女装</a>、湖南魅力湘西歌舞团、中国邮政艺术团)</p>
<p>
	　　16.小品《今天的幸福》(表演者：沈腾、黄杨、艾伦)</p>
<p>
	　　17.歌曲《因为爱情》(表演者：王菲、陈奕迅(微博))</p>
<p>
	　　18.《魔术》(表演者：刘谦(微博))</p>
<p>
	　　19.现代芭蕾《天鹅湖》(表演者：俄罗斯TODES舞团)</p>
<p>
	　　20.相声剧《爱的代驾》(表演者：冯巩、牛莉(微博)、闫学晶(微博))</p>
<p>
	　　21.歌曲《把幸福给你》(表演者：孙楠(<a href="http://www.qqtmb.com/" style="color: rgb(0, 0, 0); text-decoration: none;">个性签名</a>微博))</p>
<p>
	　　22.小品《面试》 (表演者：郭冬临、魏积安、傅浚琪、何军(微博))</p>
<p>
	　　23.儿童节目《玩具总动员》(哈尔滨工业大学机器人创新基地)</p>
<p>
	　　24.戏曲节目《戏迷一家亲》(表演者：刘佩琦、李明启、高长志、张杰(微博)、李沛泽、李泽林)</p>
<p>
	　　25.相声《奋斗》(表演者：曹云金(微博)、刘云天(微博))</p>
<p>
	　　26.歌曲《新贵妃醉酒》(表演者：李玉刚(微博))</p>
<p>
	　　27.短片《春晚记忆》</p>
<p>
	　　28.歌曲《致敬30年》</p>
<p>
	　　(1)《冬天里的一把火》(表演者：金美儿)</p>
<p>
	　　(2)《故乡的云》(表演者：费翔)</p>
<p>
	　　(3)《爱的奉献》(表演者：韦唯、吴秀波(微博))</p>
<p>
	　　(4)《常回家看看》(表演者：蔡国庆、王珞丹)</p>
<p>
	　　(5)《前门情思大碗茶》(表演者：李谷一)</p>
<p>
	　　(6)《我的中国心》(表演者：张明敏)</p>
<p>
	　　29.舞蹈《雀之恋》(表演者：杨丽萍、王迪)</p>
<p>
	　　30.歌曲《大爱》(表演者：刘欢)</p>
<p>
	　　31.歌曲《我要回家》(表演者：朱之文)</p>
<p>
	　　32.舞蹈《老妈妈》(表演者：四川广元老妈妈艺术团)</p>
<p>
	　　33.歌曲《好人就在身边》(表演者：谭晶(微博))</p>
<p>
	　　34.舞蹈《舞动冰凌》(表演者：吉林省歌舞团)</p>
<p>
	　　35.歌曲《思乡曲》(表演者：蒋大为)</p>
<p>
	　　36.歌曲《远方的家》(表演者：张也)</p>
<p>
	　　37.歌舞《中国美》(表演者：玖月奇迹(微博)、玉米提、万玛尖措、薛一村子、赛娜、柴森森、李杨、苏宁)</p>
<p>
	　　38.舞蹈《眷恋》(表演者：胡启志)</p>
<p>
	　　39.歌曲《天下一家》(表演者：王莉、廖昌永)</p>

<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="word-wrap: break-word">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2686/飘花电影piaohua.com-2012年央视春节联欢晚会CD1.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2686/飘花电影piaohua.com-2012年央视春节联欢晚会CD1.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="word-wrap: break-word">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2686/飘花电影piaohua.com-2012年央视春节联欢晚会CD2.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2686/飘花电影piaohua.com-2012年央视春节联欢晚会CD2.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="word-wrap: break-word">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2686/飘花电影piaohua.com-2012年央视春节联欢晚会CD3.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2686/飘花电影piaohua.com-2012年央视春节联欢晚会CD3.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1CH20-31J4.jpg{/dede:field}
