{dede:field name='keywords'}方大同2011香港演唱会BD高清中字{/dede:field}
{dede:field name='description'}方大同2011香港演唱会BD高清中字1280迅雷下载、免费下载，方大同2011香港演唱会BD高清中字1280Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}方大同2011香港演唱会BD高清中字1280{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-02-16{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img165.poco.cn/mypoco/myphoto/20120215/23/17870980201202152331043897667959259_013.jpg" /></p>
<p>
	2011年8月方大同在香港会议展览中心举行三场大型演唱会，为其最新创作专辑《15》的世界巡迴演唱会打响头炮。在多达三十位来自世界各地的顶尖乐手组成的庞大乐团协力下，这位型格创作歌手亲携吉他上阵，气派十足的献唱三十首给他重新改编的新旧歌曲，令乐迷如痴如醉。没有华丽特效，没有浮夸服饰，音乐挂帅的方大同纯粹以歌会友。《15香港演唱会2011》现推出Blu-ray，让你高清重温这场精彩难忘的音乐盛宴！<br />
	<br />
	超过30位音乐精英 合力完成一场超乎完美的音乐演出！<br />
	方大同 KHALIL FONG - [15] LIVE IN HONG KONG 2011一致好评！<br />
	<br />
	方大同15 香港演唱会2011于湾仔会展举行了叁场精彩绝伦的完美演唱会，<br />
	方大同超乎完美的音乐，征服了现场观众！演唱会BLURAY收录方大同精彩演出实录！<br />
	<br />
	&nbsp;</p>
<p>
	专辑曲目:&nbsp;<!--Wrap-head begin--></p>
<p class="inner_content">
<!--Wrap-head end-->	01. 张永成<br />
	02. Come Together<br />
	03. 无菇朋友<br />
	04. 二人游<br />
	05. Over<br />
	06. Take me<br />
	07. Gotta Make a Change<br />
	08. 情胜策略<br />
	09. 自以为<br />
	10. 因为你<br />
	11. 昙花<br />
	12. 认识你<br />
	13. 十九八七<br />
	14. 三人游<br />
	15. 四人游 (feat. Fiona Sit)<br />
	16. 小小虫<br />
	17. 100种表情<br />
	18. 爱在<br />
	19. 黑洞里<br />
	20. Singalongsong<br />
	21. 忘了美丽<br />
	22. 南音<br />
	23. 手拖手<br />
	24. 够不够<br />
	25. 玩乐<br />
	26. Rosy<br />
	27. 爱爱爱<br />
	28. Love Song<br />
	29. 好不容易<br />
	bonus track:<br />
	30. Wonderful Tonight <!--Wrap-tail begin--></p>
<p>
<!--Wrap-tail end-->	<img alt="" src="http://img165.poco.cn/mypoco/myphoto/20120215/23/17870980201202152331043897667959259_002.jpg" style="width: 640px; height: 360px" /><img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120215/23/17870980201202152338012742523486274_001.jpg" style="width: 640px; height: 360px" /><img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120215/23/17870980201202152338012742523486274_002.jpg" style="width: 640px; height: 360px" /></p>
<p>
	[下载地址]：<img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" /></p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy241:xiaobajie@222.187.221.241:2024/小八戒电影xiaobajie.com方大同2011香港演唱会BD高清中字1280.mkv">ftp://dy241:xiaobajie@222.187.221.241:2024/小八戒电影xiaobajie.com方大同2011香港演唱会BD高清中字1280.mkv</a></td>
		</tr>
	</tbody>
</table>
<p>
	若以上地址无法下载，请使用以下备用下载地址：<img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" /></p>

<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy241:xiaobajie@222.187.221.241:2027/小八戒电影xiaobajie.com方大同2011香港演唱会BD高清中字1280.mkv">ftp://dy241:xiaobajie@222.187.221.241:2027/小八戒电影xiaobajie.com方大同2011香港演唱会BD高清中字1280.mkv</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1CQ1P-2V35.jpg{/dede:field}
