{dede:field name='keywords'}张达明2011栋笃笑：一于做坏旦({/dede:field}
{dede:field name='description'}张达明2011栋笃笑：一于做坏旦(消暑加料红馆版)中字高清1280迅雷下载、免费下载，张达明2011栋笃笑：一于做坏旦(消暑加料红馆版)中字高清1280Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}张达明2011栋笃笑：一于做坏旦(消暑加料红馆版)中字高清1280{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-02-10{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://www.zaslike.com/files/f90lnozyf1z2gzq17iz.jpg" /></p>
<p>
	张达明发挥自己独有的舞台化栋笃笑演出。笑笃新世代。尽玩娱乐圈，掲露两性、爱情、工作、生存绝技,赞口不绝&hellip;<br />
	【档案名称】：张达明全新栋笃笑: 一於做坏旦 (消暑加料红馆版)<br />
	【英文译名】：Cheung Tat Ming Stand Up Comedy: Be a Bad Guy<br />
	【影片年代】：2011<br />
	【国家地区】：香港<br />
	【档案大小】：1.88G<br />
	【视频尺寸】：1280*720<br />
	【档案格式】：BD-RMVB<br />
	【影片时间】：02:18:46<br />
	【语言字幕】：粤语 / 简体字幕<br />
	【主要演员】：张达明 | 黄秋生 | 谷德昭</p>
<p>
	【剧情简介】：<br />
	特别收录:<br />
	1. 3D片段<br />
	2.宣传片段TVC<br />
	3.坏蛋making of<br />
	4.好蛋，坏蛋<br />
	5.我好好<br />
	6.特别嘉宾(谷德昭) (黄秋生)<br />
	7. Show time 15年<br />
	<br />
	<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 张达明十年回归伊利沙伯体育馆，将於2011年3月8-10日(星期二至四)举行张达明栋笃笑细路教坏系列之《一於做坏旦》。张达明发挥自己独有的舞台化栋笃笑，演出以栋笃笑经典人物，配合型体动作加上意想不到的视觉特技与观众互动，创造出栋笃笑笃新世代，不论你是名人、艺人、政客都无人幸免，保证令你拍案叫绝、笑到变哨牙！) 既然坏旦当道，3月8日起一连三天，於香港伊利沙伯体育馆，让坏旦飞！</p>
<p>
	<img alt="" src="http://www.zaslike.com/files/ha27d9g4s2w7dyk0mrkr.jpg" /><img alt="" src="http://www.zaslike.com/files/2q6xswi385qp2hwkddyf.jpg" /><img alt="" src="http://www.zaslike.com/files/aap70izaujidv8pwydl.jpg" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy241:xiaobajie@222.187.221.241:2013/小八戒电影xiaobajie.com张达明栋笃笑一于做坏旦中字高清BD1280.rmvb">ftp://dy241:xiaobajie@222.187.221.241:2013/小八戒电影xiaobajie.com张达明栋笃笑一于做坏旦中字高清BD1280.rmvb&nbsp;&nbsp;</a>&nbsp;&nbsp;</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1CMY0-521T.jpg{/dede:field}
