<?php
$z[0]=Array("field","疑犯追踪,第一季更新22集[中英双",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","疑犯追踪 第一季更新22集[中英双字]2012主打美剧迅雷下载、免费下载，疑犯追踪 第一季更新22集[中英双字]2012主打美剧Gvod高清在线播放，剧情介绍等。",73,257);
$z[1][4]['name']="description";
$z[2]=Array("field","疑犯追踪 第一季更新22集[中英双字]2012主打美剧",259,342);
$z[2][4]['name']="title";
$z[3]=Array("field","",344,383);
$z[3][4]['name']="writer";
$z[4]=Array("field","",385,424);
$z[4][4]['name']="source";
$z[5]=Array("field","2012-05-13",426,476);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",478,515);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://dy44:piaohua@dy44.piaohua.com:2751/飘花电影piaohua.com疑犯追踪第一季01集[中英双字].rmvb",517,649);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MQ0Qb0-12306.jpg",651,733);
$z[8][4]['name']="litpic";

?>