<?php
$z[0]=Array("field","魔鬼经济学/怪诞经济学[DVD中英",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","魔鬼经济学/怪诞经济学[DVD中英双字]迅雷下载、免费下载，魔鬼经济学/怪诞经济学[DVD中英双字]Gvod高清在线播放，剧情介绍等。",72,234);
$z[1][4]['name']="description";
$z[2]=Array("field","魔鬼经济学/怪诞经济学[DVD中英双字]",236,308);
$z[2][4]['name']="title";
$z[3]=Array("field","",310,349);
$z[3][4]['name']="writer";
$z[4]=Array("field","",351,390);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-03-23",392,442);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",444,481);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://3e:3e@d3.3edyy.com:142/【3E看看www.3ekk.com】魔鬼经济学[DVD中英双字].rmvb\" target=_blank>ftftp://3e:3e@d3.3edyy.com:142/【3E看看www.3ekk.com】魔鬼经济学[DVD中英双字].rmvb</A></TD></TR></TBODY></TABLE></div><ul class=\"mmlist",483,751);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MQ4M20-39252.jpg",753,835);
$z[8][4]['name']="litpic";

?>