{dede:field name='keywords'}一年级生/我的八十后同学高清128{/dede:field}
{dede:field name='description'}一年级生/我的八十后同学高清1280版BD中英双字2011英国传记迅雷下载、免费下载，一年级生/我的八十后同学高清1280版BD中英双字2011英国传记Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}一年级生/我的八十后同学高清1280版BD中英双字2011英国传记{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-06{/dede:field}
{dede:field name='body'}<p>
	&nbsp;<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120502/18/56643687201205021814214288458000580_004.jpg" /></p>
<p>
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120502/18/56643687201205021814214288458000580_005.jpg" /></p>
<p>
	<img border="0" src="http://img170.poco.cn/mypoco/myphoto/20120502/18/56643687201205021814214288458000580_006.jpg" /></p>
<p>
	◎译　　名　一年级生/我的八十后同学(港)<br />
	◎片　　名　The First Grader<br />
	◎年　　代　2011<br />
	◎国　　家　英国/美国/肯尼亚<br />
	◎类　　别　传记/剧情<br />
	◎语　　言　英语<br />
	◎字　　幕　中文<br />
	◎IMDB评分 7.0/10 (695 votes)<br />
	◎IMDB链接 <a href="http://www.imdb.com/title/tt790663/">http://www.imdb.com/title/tt790663/</a><br />
	◎文件格式　高清1280版BD-RMVB<br />
	◎视频尺寸　1280 x 720<br />
	◎文件大小　1CD 992MB<br />
	◎片　　长　1h 43mn<br />
	◎导　　演　贾斯汀&middot;查德维克 Justin Chadwick<br />
	◎主　　演　托尼&middot;戈罗奇 Tony Kgoroge ....Charles Obinchu<br />
	　　　　　　娜奥米&middot;哈里斯 Naomie Harris ....Jane Obinchu<br />
	　　　　　　Sam Feuer ....American Journalist<br />
	　　　　　　Shoki Mokgapa ....Teacher Elizabeth<br />
	　　　　　　Nick Reding ....Officer Johnson<br />
	　　　　　　Vusi Kunene ....Mr. Kipruto<br />
	　　　　　　Israel Makoe ....David Chege<br />
	　　　　　　Dan &#39;Churchill&#39; Ndambuki ....DJ Masha<br />
	　　　　　　Oliver Litondo ....Kimani N&#39;gan&#39;ga Maruge<br />
	　　　　　　Mumbi Kaigwa ....Education Secretary<br />
	　　　　　　John Sibi-Okumu ....Chairman of Education<br />
	　　　　　　Alfred Munyua ....Teacher Alfred<br />
	　　　　　　Ainea Ojiambo ....Education Officer<br />
	　　　　　　Gilbert K. Lukalia ....Mr. Mutahi / Politician<br />
	　　　　　　Lydia Gitachu ....CNN Journalist<br />
	　　　　　　Jeannette Elsworth ....Plantation Owner&#39;s Wife<br />
	　　　　　　Abubakar Mwenda ....Boie<br />
	　　　　　　Melvin Alusa ....Mr. Mutahi&#39;s Aide<br />
	　　　　　　John Kimani ....Maruge&#39;s Baby Son<br />
	　　　　　　Hannah Wacera ....Maruge&#39;s Daughter<br />
	　　　　　　Emily Njoki ....Young Maruge&#39;s wife<br />
	　　　　　　Peter Marias ....Peter<br />
	　　　　　　Zingaro Percussions ....Mau Mau Warriors<br />
	　　　　　　Eunice Tekero ....Village Woman<br />
	　　　　　　Macharia Kamau ....DJ&#39;s PA<br />
	　　　　　　Mary Mbirua ....Stall Owner<br />
	　　　　　　Irene Kariuki ....Mrs. Muthumba<br />
	　　　　　　Lwanda Jawar ....Young Maruge<br />
	　　　　　　Charles Ouda ....Adult School Teacher<br />
	　　　　　　Rosemary Nyambura ....Jacquie - PA to the Chairman<br />
	　　　　　　Jackie Musimbi ....Village Girl<br />
	　　　　　　Kathyline Ndogori ....Teacher Katherine<br />
	　　　　　　Mwenga Matilika ....Old Codger<br />
	　　　　　　Peter Emera Pious ....Jonas<br />
	　　　　　　Rachel Jones ....BBC Journalist<br />
	　　　　　　Tom Gitau ....Old Codger<br />
	　　　　　　Susan Sisian ....Young Mother<br />
	　　　　　　Kamau Mbaya ....Kamau Chege<br />
	　　　　　　Nick Ndichu ....Giver - Mau Mau Oath<br />
	　　　　　　Shirlen Wanjari ....Mother Wanjiku<br />
	　　　　　　Catherine Njiru ....Stall Owner<br />
	　　　　　　Joel Rempesa ....Joel<br />
	　　　　　　Michael Oyier ....Newsreader<br />
	　　　　　　Watson Mbirua ....Old Codger<br />
	　　　　　　Benta Ochieng ....Mother Benta<br />
	　　　　　　Paul Mbogo ....Leader - Mau Mau<br />
	　　　　　　Agnes Simaloi ....Agnes<br />
	　　　　　　Shadrack Murimi Gachuhi ....Old Codger<br />
	　　　　　　Kamau Ndungu ....John Gambe<br />
	　　　　　　Kurenda Ole Kureya ....Masai Store Owner</p>
<p>
	◎简　　介</p>
<p>
	<br />
	　　影片根据真人真事改编，讲述了一位曾是独立运动武装斗士的84岁肯尼亚老人，为自己从未得到过的入学读书的权利而斗争的故事。</p>
<p>
	花絮</p>
<p>
	&middot;荣获2010年第二届多哈电影节最佳剧情片奖。</p>
<p>
	<br />
	◎影片截图</p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120506/00/17870980201205060039292243376469427_017.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 640px; height: 360px; border-top: 0px solid; border-right: 0px solid" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120506/00/17870980201205060039292243376469427_015.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 640px; height: 360px; border-top: 0px solid; border-right: 0px solid" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120506/00/17870980201205060039292243376469427_014.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 640px; height: 360px; border-top: 0px solid; border-right: 0px solid" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120506/00/17870980201205060039292243376469427_013.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 640px; height: 360px; border-top: 0px solid; border-right: 0px solid" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.net">http://www.xiaozhizhu.net</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy241:piaohua@117.41.229.29:2003/飘花电影piaohua.com一年级生高清1280版BD中英双字.rmvb">ftp://dy241:piaohua@117.41.229.29:2003/飘花电影piaohua.com一年级生高清1280版BD中英双字.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15956360-53421.jpg{/dede:field}
