{dede:field name='keywords'}戴夫号飞船/大卫特大号BD中英双{/dede:field}
{dede:field name='description'}戴夫号飞船/大卫特大号BD中英双字1024/1280高清迅雷下载、免费下载，戴夫号飞船/大卫特大号BD中英双字1024/1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}戴夫号飞船/大卫特大号BD中英双字1024/1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-04-27{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://eee4.com:8114@vip11.eee4.com:8114/[3E迅雷电影站www.eee4.com]戴夫号飞船DVD中字.rmvb" target="_blank{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MO561560-24913.jpg{/dede:field}
