<?php
$z[0]=Array("field","戴夫号飞船/大卫特大号BD中英双",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","戴夫号飞船/大卫特大号BD中英双字1024/1280高清迅雷下载、免费下载，戴夫号飞船/大卫特大号BD中英双字1024/1280高清Gvod高清在线播放，剧情介绍等。",72,254);
$z[1][4]['name']="description";
$z[2]=Array("field","戴夫号飞船/大卫特大号BD中英双字1024/1280高清",256,338);
$z[2][4]['name']="title";
$z[3]=Array("field","",340,379);
$z[3][4]['name']="writer";
$z[4]=Array("field","",381,420);
$z[4][4]['name']="source";
$z[5]=Array("field","2012-04-27",422,472);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",474,511);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://eee4.com:8114@vip11.eee4.com:8114/[3E迅雷电影站www.eee4.com]戴夫号飞船DVD中字.rmvb\" target=\"_blank",513,656);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MO561560-24913.jpg",658,742);
$z[8][4]['name']="litpic";

?>