{dede:field name='keywords'}深深的海洋BD1280国粤英三语中字{/dede:field}
{dede:field name='description'}深深的海洋BD1280国粤英三语中字迅雷下载、免费下载，深深的海洋BD1280国粤英三语中字Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}深深的海洋BD1280国粤英三语中字{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-02-22{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120222/00/17870980201202220033262603792071319_014.jpg" style="width: 619px; height: 782px" /></p>
<p>
	◎译　　名　深深的海洋<br />
	◎片　　名　Deep Sea<br />
	◎导　　演　Howard Hall<br />
	◎主　　演　Johnny Depp ... Narration<br />
	　　　　　　Kate Winslet ... Narration<br />
	◎年　　代　2006<br />
	◎国　　家　加拿大<br />
	◎类　　别　纪录<br />
	◎语　　言　国粤英<br />
	◎IMDB评分&nbsp;&nbsp;7.7/10 (865 votes)<br />
	◎IMDB链接&nbsp;&nbsp;<a href="http://www.imdb.com/title/tt0424942" target="_blank">http://www.imdb.com/title/tt0424942</a><br />
	◎片&nbsp; &nbsp;&nbsp; &nbsp;&nbsp;&nbsp;长 0:40:50 (h:m:s)<br />
	<br />
	◎简　　介　<br />
	<br />
	&nbsp; &nbsp;&nbsp;&nbsp;在1973年人类意外地发现，在完全没有阳光的深海热泉口旁与管虫共生的细菌旺盛地生活着，有些是我们至今所知最古老的物种，意味着这里可能是远古时期生命起源的地方。本片内容将在海怪号以及水螅号两艘潜艇带领下，深入海底与世隔绝的地方，探访远古时期生命起源的所在。<br />
	<br />
	　　深海大进击影片内容，首先潜艇将带领我们下潜600公尺深海域，进入永远处于黑暗中的世界，全程追踪观察地球上最大肉食动物抹香鲸，追捕地球上最大无脊椎动物大王鱿鱼等等难得一见的精彩猎食过程。接着潜艇更将带领我们下潜超过1500公尺深的海底，在水温接近冰点及潜艇表面承受压力超过每平方公分 218公斤下，惊险进入海底热泉喷口严峻环境处，饱览超热海水由海底裂缝涌出的惊险画面，以及一旁大型管虫、热泉蟹等等颠覆传统思维的生态体系，这些都是世人从未见过的景像。最后，潜艇巧遇抹香鲸追捕大王鱿鱼群，在一阵惊险混乱碰撞中，潜艇船长实时起动自动快速上升情景中，惊险结束刺激的深海潜航之旅程。<br />
	<br />
	　　本片在精彩特效和惊险画面背后，蕴含着生活在深海热泉丰富生物生态知识，例如抹香鲸拥有全世界最大的脑 ( 9公斤重 )、最深的潜水者 ( 超过3000公尺 )、最长的憋气者 ( 超过1小时 )、最大声的动物 ( 236分贝/相当于雷声 ) 并且是地球上最大的肉食动物，以及大王鱿鱼拥有全世界最大的眼睛( 超过30公分 )、无脊椎动物中最大的脑、每一条臂上多达300个锋利牙圈围绕着吸盘、他是地球上最大的无脊椎动物 ( 超过12公尺长 ) ，千胃动物、大型管虫、安康鱼、热泉蟹等等深海生物知识介绍，是一部值得合家共同观赏的海洋生物知识性影片。<br />
	<br />
	&nbsp; &nbsp;&nbsp; &nbsp; howard hall 导演的3d电影《 深海探宝》(deep sea) 将在全世界imax 影院上映，该片将给观众提供在地球上最奇异地方的逼真体验，从热带雨林的裸鳃亚目动物到中太平洋的章鱼。凯特和强尼&middot;迪普出演两位大无畏的探险者，探索着海底世界的&ldquo;星球大战&rdquo;。<br />
	<br />
	&nbsp;<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120222/00/17870980201202220033262603792071319_013.jpg" style="width: 640px; height: 360px" /><img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120222/00/17870980201202220033262603792071319_011.jpg" style="width: 640px; height: 360px" /><img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120222/00/17870980201202220033262603792071319_010.jpg" style="width: 640px; height: 360px" /></p>
<p>
	[下载地址]：<img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" /></p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy241:xiaobajie@222.187.221.241:2037/小八戒电影xiaobajie.com深深的海洋BD1280国粤英三语中字.mkv">ftp://dy241:xiaobajie@222.187.221.241:2037/小八戒电影xiaobajie.com深深的海洋BD1280国粤英三语中字.mkv</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1C91250-4Q30.jpg{/dede:field}
