{dede:field name='keywords'}枪神剧场版：陌生荒漠大乱斗DVD{/dede:field}
{dede:field name='description'}枪神剧场版：陌生荒漠大乱斗DVD中字迅雷下载、免费下载，枪神剧场版：陌生荒漠大乱斗DVD中字Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}枪神剧场版：陌生荒漠大乱斗DVD中字{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-12-14{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="/uploads/allimg/c120525/133O043B940-203256.jpg" /></p>
<p>
	中文片名： 枪神剧场版：陌生荒漠大乱斗<br />
	英文片名： Trigun The Movie:Badlands Rumble<br />
	导演： 西村聪<br />
	主演： 小野坂昌也 速水奖 鹤广美<br />
	制片国家/地区： 日本<br />
	类型： 动作 / 科幻<br />
	上映日期： 2010年4月24日 日本<br />
	片长：90分钟<br />
	对白语言： 日语<br />
	对白字幕： 中文<br />
	资源格式： DVD-RMVB</p>
<p>
	【原作介绍】</p>
<p>
	内藤泰弘创作的SF漫画「TRIGUN枪神」，以其拉风的人设、精彩紧凑的剧情博得众多读者的好评，该作曾于1998年推出全26话的TV动画，而早在去年就预定2009年内公开的剧场版却是至今仍未见踪影。在众FANS纠结于剧场版是否永不面世之际，日前官方终于再度敲定剧场版的公开期为2010年春。「TRIGUN THE MOVIE」是以正篇中的设定为框架的原创故事，并继续由TV版的制作会社MAD HOUSE操刀。</p>
<p>
	<br />
	【MOVIE STORY】</p>
<p>
	　　枪神The Moive中，传说中的大强盗加斯帕克（ガスバック）以流沙荒漠所包围的某个城市为目标，要报20年前的一箭之仇，为此市长从各处招募大量勇士聚集在城中，来的人中赫然有传说中的法修?德?斯坦比特，以及与加斯帕克似乎有着某种关系的阿梅莉亚，围绕这座城市，异常激烈的冲突即将展开。</p>
<p>
	一句话简介：传说中不变老XD...打不死XD...的男人强势介入强盗的家庭纠纷的各种闹剧...</p>
<p>
	<img alt="" src="/uploads/allimg/c120525/133O043C550-219392.jpg" /></p>
<p>
	<img alt="" src="/uploads/allimg/c120525/133O043D030-2241R.jpg" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="/uploads/allimg/c120524/133N2Z4FF-102231.jpg" />&nbsp;&nbsp;&nbsp;
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				&nbsp;&nbsp;ftp://dy44:piaohua@dy44.piaohua.com:2335/飘花电影piaohua.com枪神剧场版：陌生荒漠大乱斗DVD中字.rmvb</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O043D540-239231.jpg{/dede:field}
