{dede:field name='keywords'}赛车总动员：拖线狂想曲/汽车闯{/dede:field}
{dede:field name='description'}赛车总动员：拖线狂想曲/汽车闯天关BD中英双字迅雷下载、免费下载，赛车总动员：拖线狂想曲/汽车闯天关BD中英双字Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}赛车总动员：拖线狂想曲/汽车闯天关BD中英双字{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-10-20{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="/uploads/allimg/c120525/133O0455U40-14Ib.jpg" /></p>
<p>
	◎译　　名　汽车总动员：拖线狂想曲<br />
	◎片　　名　Cars Toon Maters Tall Tales<br />
	◎年　　代　2008<br />
	◎国　　家　美国<br />
	◎类　　别　动画<br />
	◎语　　言　英语<br />
	◎字　　幕　中英双字幕<br />
	◎IMDB评分 7.2/10 (230 votes)<br />
	◎下载链接 http://www.xiaozhizhu.net<br />
	◎文件格式　Rmvb<br />
	◎视频尺寸　1280 x 720<br />
	◎文件大小　418MB<br />
	◎片　　长　36 Mins<br />
	◎导　　演　<br />
	◎主　　演　Larry the Cable Guy ... Mater (7 episodes, 2008-2010)<br />
	　　　　　　Keith Ferguson ... Lightning McQueen (7 episodes, 2008-2010)</p>
<p>
	◎简　　介　</p>
<p>
	　　让人喜爱的拖线先生 将在剧中无厘头精彩登场！</p>
<p>
	　　拖线来说故事咯！ 他说的故事不但精彩，更让你分不清是真的还是吹牛:一下说自己是特技天王；一下说是西班牙有名的斗牛士；又说他以前是超级大侦探；还曾经在东京甩尾...每个人都听的雾煞煞，到底是他瞎编的？还是真有其事？哈！你永远不会知道！</p>
<p>
	　　皮克斯动画团队继《汽车总动员》之后，再度发挥创意巧思，制作一系列【Cars闯天关】短篇作品，让拖线带大家畅游天马行空的汽车世界！本片共收录九段精彩绝伦的影片，其中还包括两段从未曝光的新作品，让我们一同进入拖线的奇想世界中，看他如何帮我们大家实现梦想！</p>
<p>
	◎影片截图</p>
<p>
	&nbsp;<img alt="" src="/uploads/allimg/c120525/133O045593F-152041.jpg" style="width: 600px; height: 338px" /></p>
<p>
	<img alt="" src="/uploads/allimg/c120525/133O0456010-1D4Z.jpg" style="width: 600px; height: 338px" /></p>
<p>
	<img alt="" src="/uploads/allimg/c120525/133O04560Q0-1G146.jpg" style="width: 600px; height: 338px" /></p>
<p>
	[下载地址]： &nbsp;<img border="0" src="/uploads/allimg/c120524/133N2Z4FF-102231.jpg" />
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:1858/飘花电影piaohua.com汽车闯天关BD中英双字.rmvb</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120524/133N353DD0-2G248.gif{/dede:field}
