{dede:field name='keywords'}堵车高清HD国语中字吴镇宇、吕丽{/dede:field}
{dede:field name='description'}堵车高清HD国语中字吴镇宇、吕丽萍奇幻动作大片迅雷下载、免费下载，堵车高清HD国语中字吴镇宇、吕丽萍奇幻动作大片Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}堵车高清HD国语中字吴镇宇、吕丽萍奇幻动作大片{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-17{/dede:field}
{dede:field name='body'}<p>
	<img src="http://img165.poco.cn/mypoco/myphoto/20111015/15/56634212201110151537195015421240501_006.jpg" /></p>
<p>
	<img src="http://img165.poco.cn/mypoco/myphoto/20111015/15/56634212201110151537195015421240501_005.jpg" /></p>
<p>
	<img src="http://img165.poco.cn/mypoco/myphoto/20111015/15/56634212201110151537195015421240501_004.jpg" /></p>
<p>
	中文名： 堵车<br />
	英文名： Love Never Dies<br />
	导演： 阿年<br />
	主演： 吴镇宇 / 倪大红 / 吕丽萍 / 孙海英 / 陈志朋 / 吴俊余 / 葛思然 / 巴哈古丽<br />
	上映日期： 2011年10月14日 中国<br />
	国家/地区： 中国<br />
	类型： 动作 / 奇幻 / 悬疑 / 爱情<br />
	片长：86分钟<br />
	对白语言： 汉语普通话<br />
	发行公司： 北京紫禁城影业有限责任公司<br />
	<br />
	<br />
	剧情简介<br />
	<br />
	　　《堵车》是一部集爱情、动作、奇幻、悬疑和黑色幽默于一体的都市电影，由一起堵车事件道出了贩毒者罗生门（吴镇宇 饰）、发条（陈志朋 饰）、一休（吴俊余 饰）、橙子（巴哈古丽 饰）等一群&ldquo;堵心&rdquo;人之间的命运交织，讲述了一个悬念迭起、凄美苍凉的故事。《堵车》&mdash;&mdash;由堵心而生。<br />
	　　三年前，&ldquo;富二代&rdquo;发条、先天心脏病患者一休和制毒贩毒者罗生门三个人同时都爱上了少女橙子。<br />
	　　三年后，又为了同一个目标，所有人的命运再次交织在一起。<br />
	　　&ldquo;&cap;&rdquo;型摩天大楼就是罗生门的终点，是天堂的大门，也是宿命的象征。在荆轲的枪口下，罗生门用绿藻酒结束了自己的生命。手机视频中，发条生命垂危，说：如果我死了，请把我的心脏移植给一休。完成了橙子的愿望，也表达他对橙子的爱。<br />
	<br />
	<br />
	◎影片截图<br />
	<br />
	&nbsp;<img src="http://img170.poco.cn/mypoco/myphoto/20120517/18/56643687201205171803553357299415287_001.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 253px; border-top: 0px solid; border-right: 0px solid" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120517/18/56643687201205171803553357299415287_000.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 253px; border-top: 0px solid; border-right: 0px solid" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120517/18/56643687201205171803553357299415287_002.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 253px; border-top: 0px solid; border-right: 0px solid" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120517/18/56643687201205171803553357299415287_003.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 253px; border-top: 0px solid; border-right: 0px solid" /><br />
	[下载地址]： &nbsp;<img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" /></p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<anchor><a href="ftp://dy44:piaohua@dy44.piaohua.com:1825/飘花电影piaohua.com堵车DVD国语中字.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:1825/飘花电影piaohua.com堵车DVD国语中字.rmvb</a></anchor></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<anchor><a href="ftp://dy44:piaohua@dy44.piaohua.com:3444/飘花电影piaohua.com堵车高清HD国语中字.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3444/飘花电影piaohua.com堵车高清HD国语中字.rmvb</a></anchor></td>
		</tr>
	</tbody>
</table>
<p>
	<anchor>
	<p>
		&nbsp;</p>
	</anchor></p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15C3310-3GT.jpg{/dede:field}
