{dede:field name='keywords'}康熙来了-20120216迅雷下载，免{/dede:field}
{dede:field name='description'}康熙来了-20120216迅雷下载、免费下载，康熙来了-20120216Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}康熙来了-20120216{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-02-19{/dede:field}
{dede:field name='body'}<p>
	<img src="http://img.funshion.com/attachment/2007/06-07/22.jpg" /></p>
<p>
	<img src="http://img.funshion.com/attachment/new_images/2010/05-19/18519345_1274237603_501.jpg" /></p>
<p>
	<img src="http://img.funshion.com/attachment/images/2007-01-05/200701051167985274932.jpg" /></p>
<p>
	<img src="http://img.funshion.com/attachment/images/2007-01-05/200701051167985274915.jpg" /></p>
<p>
	<img src="http://img.funshion.com/attachment/images/2007-01-05/200701051167985274950.jpg" /></p>
<p>
	&bull;主持：<br />
	徐熙娣 / 蔡康永</p>
<p>
	&bull;类型：脱口秀<br />
	&bull;首映：2004年11月8日 中国台湾<br />
	&bull;<br />
	&bull;&bull;点评： 看了之后真的有种所有烦恼一扫而空的感觉!--<br />
	&bull;你超劲爆新闻可以有，幽默爆笑这个真的有！--<br />
	&bull;剧情： 节目介绍： 《康熙来了》取自蔡康永与小S徐熙娣名字的一个字而拼成。每晚收视率为1.2%-1.3%，每周吸引了超过500万观看人次，是台湾收视率最高有线电视台综艺节目综艺谈话类节目,邀请台湾当红明星来到节目当中,通过期间访谈让你了解艺人不为人知的一面,多才多艺的小S,加上知识渊博的蔡康永,除了穿插期间不少的搞笑元素外,在知性与理性...<br />
	&bull;花絮： 08年6月10日红遍两岸的综艺节目《康熙来了》，欢喜进棚录制开棚以来第一千集，在的特别节目中，特别邀请李妍瑾、斯容、小钟、王彩桦、蝴蝶姊姊、梁赫群、小甜甜、黄国伦等八位上过节目且有极佳评价的艺人，一起在今天共同缔造收视巅峰，而几位艺人也在现场回顾当初上节目的画...</p>
<p>
	<img src="http://img.funshion.com/attachment/new_images/2010/11-10/19594367_1289372525_937.jpg" width="650" /></p>
<p>
	<img src="http://img.funshion.com/attachment/new_images/2010/11-10/19594367_1289372511_886.jpg" /></p>
<p>
	<img src="http://img.funshion.com/attachment/new_images/2010/11-10/19594367_1289372520_354.jpg" /></p>
<p>
	[下载地址]： &nbsp;<img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" /></p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy171:piaohua@dy171.piaohua.com:1041/飘花电影piaohua.com康熙来了-20110715.rmvb">ftp://dy171:piaohua@dy171.piaohua.com:1041/飘花电影piaohua.com康熙来了-20110715.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy171:piaohua@dy171.piaohua.com:1068/飘花电影piaohua.com康熙来了-20110718.rmvb">ftp://dy171:piaohua@dy171.piaohua.com:1068/飘花电影piaohua.com康熙来了-20110718.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy171:piaohua@dy171.piaohua.com:1068/飘花电影piaohua.com康熙来了-20110719.rmvb">ftp://dy171:piaohua@dy171.piaohua.com:1068/飘花电影piaohua.com康熙来了-20110719.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy171:piaohua@dy171.piaohua.com:1068/飘花电影piaohua.com康熙来了-20110720.rmvb">ftp://dy171:piaohua@dy171.piaohua.com:1068/飘花电影piaohua.com康熙来了-20110720.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy171:piaohua@dy171.piaohua.com:1068/飘花电影piaohua.com康熙来了-20110721.rmvb">ftp://dy171:piaohua@dy171.piaohua.com:1068/飘花电影piaohua.com康熙来了-20110721.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy171:piaohua@dy171.piaohua.com:1077/飘花电影piaohua.com康熙来了-20110722.rmvb">ftp://dy171:piaohua@dy171.piaohua.com:1077/飘花电影piaohua.com康熙来了-20110722.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:1138/飘花电影piaohua.com康熙来了-20110726.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:1138/飘花电影piaohua.com康熙来了-20110726.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:1159/飘花电影piaohua.com康熙来了-20110729.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:1159/飘花电影piaohua.com康熙来了-20110729.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:1169/飘花电影piaohua.com康熙来了-20110801.rmvb ">ftp://dy44:piaohua@dy44.piaohua.com:1169/飘花电影piaohua.com康熙来了-20110801.rmvb </a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:1180/飘花电影piaohua.com康熙来了-20110802.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:1180/飘花电影piaohua.com康熙来了-20110802.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:1191/康熙来了20110803.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:1191/康熙来了20110803.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:1207/飘花电影piaohua.com康熙来了-20110805.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:1207/飘花电影piaohua.com康熙来了-20110805.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:1346/飘花电影piaohua.com康熙来了-20110818.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:1346/飘花电影piaohua.com康熙来了-20110818.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:1378/飘花电影piaohua.com康熙来了-20110822.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:1378/飘花电影piaohua.com康熙来了-20110822.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:1406/飘花电影piaohua.com康熙来了-20110825.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:1406/飘花电影piaohua.com康熙来了-20110825.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:1570/飘花电影piaohua.com康熙来了-20110913.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:1570/飘花电影piaohua.com康熙来了-20110913.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:1570/飘花电影piaohua.com康熙来了-20110914.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:1570/飘花电影piaohua.com康熙来了-20110914.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:1618/飘花电影piaohua.com康熙来了-20110920.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:1618/飘花电影piaohua.com康熙来了-20110920.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:1643/飘花电影piaohua.com康熙来了-20110922.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:1643/飘花电影piaohua.com康熙来了-20110922.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:1698/飘花电影piaohua.com康熙来了-20110928.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:1698/飘花电影piaohua.com康熙来了-20110928.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:1746/飘花电影piaohua.com康熙来了-20111006.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:1746/飘花电影piaohua.com康熙来了-20111006.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:1837/飘花电影piaohua.com康熙来了-20111014.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:1837/飘花电影piaohua.com康熙来了-20111014.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:1878/飘花电影piaohua.com康熙来了-20111020.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:1878/飘花电影piaohua.com康熙来了-20111020.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:1919/飘花电影piaohua.com康熙来了-20111025.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:1919/飘花电影piaohua.com康熙来了-20111025.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2035/飘花电影piaohua.com康熙来了-20111108.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2035/飘花电影piaohua.com康熙来了-20111108.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2165/飘花电影piaohua.com康熙来了-20111123.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2165/飘花电影piaohua.com康熙来了-20111123.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2267/飘花电影piaohua.com康熙来了-20111202.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2267/飘花电影piaohua.com康熙来了-20111202.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2296/飘花电影piaohua.com康熙来了-20111207.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2296/飘花电影piaohua.com康熙来了-20111207.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2581/飘花电影piaohua.com康熙来了-20120109.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2581/飘花电影piaohua.com康熙来了-20120109.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2796/飘花电影piaohua.com康熙来了-20120209.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2796/飘花电影piaohua.com康熙来了-20120209.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2847/飘花电影piaohua.com康熙来了-20120216.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2847/飘花电影piaohua.com康熙来了-20120216.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1CY2F-2NS.jpg{/dede:field}
