<?php
$z[0]=Array("field","游龙戏凤/星梦奇缘1280高清[DVD",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","游龙戏凤/星梦奇缘1280高清[DVD国语中字+粤语中英双字] [双版本]迅雷下载、免费下载，游龙戏凤/星梦奇缘1280高清[DVD国语中字+粤语中英双字] [双版本]Gvod高清在线播放，剧情介绍等。",72,286);
$z[1][4]['name']="description";
$z[2]=Array("field","游龙戏凤/星梦奇缘1280高清[DVD国语中字+粤语中英双字] [双版本]",288,386);
$z[2][4]['name']="title";
$z[3]=Array("field","",388,427);
$z[3][4]['name']="writer";
$z[4]=Array("field","",429,468);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-11-15",470,520);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",522,559);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://e63:e63@xl2.eee4.com:9306/[3E电影站www.eee4.com]游龙戏凤DVD中英双字CD1.rmvb\" target=\"_blank",561,697);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MOKI0-3A06.jpg",699,779);
$z[8][4]['name']="litpic";

?>