{dede:field name='keywords'}骆驼客高清1024版BD国语中字2012{/dede:field}
{dede:field name='description'}骆驼客高清1024版BD国语中字2012最新上映中国动作冒险爱情大片迅雷下载、免费下载，骆驼客高清1024版BD国语中字2012最新上映中国动作冒险爱情大片Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}骆驼客高清1024版BD国语中字2012最新上映中国动作冒险爱情大片{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-04-28{/dede:field}
{dede:field name='body'}<p>
	&nbsp;<img src="http://img170.poco.cn/mypoco/myphoto/20120427/18/56643687201204271845101868152910708_006.jpg" /></p>

<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120427/18/56643687201204271845101868152910708_005.jpg" /></p>
<p>
	&nbsp;<img src="http://img170.poco.cn/mypoco/myphoto/20120427/18/56643687201204271845101868152910708_004.jpg" /></p>
<p>
	导演: 高峰<br />
	编剧: 高峰 / 陈锐<br />
	主演: 刘小宁 / 陈旭竹 / 张玉龙 / 安启虎<br />
	类型: 动作 / 爱情 / 冒险<br />
	制片国家/地区: 中国大陆<br />
	语言: 汉语普通话<br />
	上映日期: 2012-04-27(中国大陆)<br />
	片长: 90分钟<br />
	又名: Camel Caravan</p>
<p>
	<br />
	剧情简介</p>
<p>
	　　在西域有一群身怀绝技的人，他们从事着古老而神秘的职业，用骆驼护送货物辗转各地，被称为骆驼客。戈师傅（刘小宁 饰）拥有过人的弓箭技巧，是当地最负盛名的驼队首领，这次，他的驼队刚刚踏上古老驼道，就遭遇到一场惊心动魄的疯狂追杀。心怀鬼胎的队友，女儿（陈旭竹 饰）与徒弟（张玉龙 饰）之间的意乱情迷，危机重重之际，他们走上的很可能是一条不归路。忠诚与背叛，他们能否坚守侠客的信义？在箭与枪的交锋中，谁成为最后的赢家？</p>
<p>
	<br />
	◎影片截图</p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120427/18/56643687201204271845101868152910708_002.jpg" style="width: 600px; height: 338px" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120427/18/56643687201204271845101868152910708_003.jpg" style="width: 600px; height: 338px" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120427/18/56643687201204271845101868152910708_001.jpg" style="width: 600px; height: 338px" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120427/18/56643687201204271845101868152910708_000.jpg" style="width: 600px; height: 338px" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.net" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3308/飘花电影piaohua.com骆驼客高清1024版BD国语中字.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3308/飘花电影piaohua.com骆驼客高清1024版BD国语中字.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1564040-39635.jpg{/dede:field}
