<?php
$z[0]=Array("field","杰西警探犯罪档案：无悔追踪[DVD",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","杰西警探犯罪档案：无悔追踪[DVD中英双字]迅雷下载、免费下载，杰西警探犯罪档案：无悔追踪[DVD中英双字]Gvod高清在线播放，剧情介绍等。",73,245);
$z[1][4]['name']="description";
$z[2]=Array("field","杰西警探犯罪档案：无悔追踪[DVD中英双字]",247,324);
$z[2][4]['name']="title";
$z[3]=Array("field","",326,365);
$z[3][4]['name']="writer";
$z[4]=Array("field","",367,406);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-09-25",408,458);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",460,497);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://6e:6e@m1.eee4.cc:1550/【3E电影院www.eee4.org】杰西警探犯罪档案：无悔追踪DVD中英双字.rmvb\" target=_blank>ftftp://6e:6e@m1.eee4.cc:1550/【3E电影院www.eee4.org】杰西警探犯罪档案：无悔追踪DVD中英双字.rmvb</A></TD></TR></TBODY></TABLE></div><ul class=\"mmlist",499,797);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MP332E0-44I6.jpg",799,881);
$z[8][4]['name']="litpic";

?>