{dede:field name='keywords'}嘿·店HD1280高清迅雷下载，免费{/dede:field}
{dede:field name='description'}嘿·店HD1280高清迅雷下载、免费下载，嘿·店HD1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}嘿·店HD1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-10{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://p.dmdjz.com/uploads/2012/05/p1265401735.jpg" style="width: 424px; height: 600px" /></p>
<p>
	导演: 姬棹馨<br />
	主演: 朱茵 / 张达明 / 李菲儿 / 廖健 / 周觅 / 于婷婷<br />
	类型: 喜剧 / 惊悚<br />
	制片国家/地区: 中国大陆<br />
	语言: 汉语普通话<br />
	上映日期: 2011-10-21(中国大陆)<br />
	片长: 90分钟<br />
	官方小站:http://www.xiaozhizhu.net/<br />
	<br />
	嘿店的剧情简介 &middot; &middot; &middot; &middot; &middot; &middot;<br />
	　　为生活所迫的杨小明（廖健饰）走投无路，终于鼓足勇气向老板讨薪却意外被卷入抢劫案。被带到阴森超市的杨小明苏醒后竟发现周围满是令人寒毛卓竖的僵尸，他惊恐万分却无路可逃。在超市杨小明与不着调的经纪人（张达明饰）、成名已久的女演员惠子（朱茵饰）机缘偶遇。临危之际杨小明终于发现了真相并对经纪人和女演员有了深入了解。恍然大悟的杨小明打算离开超市，才发现自己并没有那么容易脱身&hellip;&hellip;<br />
	<br />
	<img alt="" src="http://p.dmdjz.com/uploads/2012/05/thumbs20120509145814.jpg" style="width: 650px; height: 1507px" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.net/movie/27621.html" target="_blank" title="嘿店在线观看">嘿店在线观看</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy125:piaohua@dy125.piaohua.com:8039/飘花电影piaohua.com嘿店HD国语1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:8039/飘花电影piaohua.com嘿店HD国语1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15K1430-2EK.jpg{/dede:field}
