{dede:field name='keywords'}遥远的桥HD高清迅雷下载，免费下{/dede:field}
{dede:field name='description'}遥远的桥HD高清迅雷下载、免费下载，遥远的桥HD高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}遥远的桥HD高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-10-27{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img165.poco.cn/mypoco/myphoto/20111017/12/62564813201110171248141325452838487_000.jpg" style="width: 448px; height: 600px" /></p>
<p>
	◎译　　名　遥远的桥/夺桥遗恨/英雄冢/鹰掠战士<br />
	◎片　　名　A Bridge Too Far<br />
	◎年　　代　1977<br />
	◎国　　家　美国/英国<br />
	◎类　　别　动作/剧情/历史/战争<br />
	◎语　　言　英语<br />
	◎字　　幕　<br />
	◎IMDB评分 7.3/10 &nbsp; 14,513 votes<br />
	◎IMDB链接 <a href="http://www.imdb.com/title/tt0075784" target="_blank">http://www.imdb.com/title/tt0075784</a><br />
	◎导　　演　理查德&middot;阿滕伯勒 Richard Attenborough<br />
	◎主　　演　德克&middot;博加德 Dirk Bogarde .... Lt. Gen. Browning<br />
	　　　　　　詹姆斯&middot;凯恩 James Caan .... SSgt. Eddie Dohun<br />
	　　　　　　迈克尔&middot;凯恩 Michael Caine .... Lt. Col. J.O.E. Vandeleur<br />
	　　　　　　肖恩&middot;康纳利 Sean Connery .... Maj. Gen. Roy Urquhart<br />
	　　　　　　爱德华&middot;福克斯 Edward Fox .... Lt. Gen. Brian Horrocks<br />
	　　　　　　埃利奥特&middot;古尔德 Elliott Gould .... Col. Robert Stout<br />
	　　　　　　吉恩&middot;哈克曼 Gene Hackman .... Maj. Gen. Stanislaw Sosabowski<br />
	　　　　　　安东尼&middot;霍普金斯 Anthony Hopkins .... Lt. Col. John Frost<br />
	　　　　　　Hardy Kr&uuml;ger .... Maj. Gen. Ludwig<br />
	　　　　　　Ryan O&#39;Neal .... Brig. Gen. James Gavin<br />
	　　　　　　劳伦斯&middot;奥利弗 Laurence Olivier .... Dr. Jan Spaander<br />
	　　　　　　罗伯特&middot;雷德福 Robert Redford .... Maj. Julian Cook<br />
	　　　　　　Maximilian Schell .... Lt. Gen. Wilhelm Bittrich<br />
	　　　　　　莉芙&middot;厄尔曼 Liv Ullmann .... Kate Ter Horst<br />
	　　　　　　Denholm Elliott .... RAF meteorologist officer<br />
	<br />
	◎简　　介　<br />
	<br />
	　　本片描述一九四四年，欧战已近尾声，各地盟军将领认为只要一番猛攻，便可打开通路提早直捣柏林，结束战争。于是盟军采取大规模的空降行动降落荷兰，不料遭遇德军的顽强抵抗，以致行动遭到惨败。<br />
	<br />
	Genre: Action,Drama,History,War<br />
	<br />
	Plot<br />
	An historic telling of the failed attempt to capture several bridges<br />
	to Germany in World War II in a campaign called Operation Market-Garden.</p>
<p>
	<img alt="" src="http://img165.poco.cn/mypoco/myphoto/20111019/12/62564813201110191239032123430904548_001.jpg" style="width: 640px; height: 360px" /><img alt="" src="http://img165.poco.cn/mypoco/myphoto/20111019/12/62564813201110191239032123430904548_000.jpg" style="width: 640px; height: 360px" /><br />
	<br />
	&nbsp;</p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="&#13;&#10;ftp://dy125:piaohua@dy125.piaohua.com:7041/飘花电影piaohua.com遥远的桥BD中字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:7041/飘花电影piaohua.com遥远的桥BD中字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1625L20-3GU.jpg{/dede:field}
