{dede:field name='keywords'}完美风暴[DVD中英字幕]迅雷下载{/dede:field}
{dede:field name='description'}完美风暴[DVD中英字幕]迅雷下载、免费下载，完美风暴[DVD中英字幕]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}完美风暴[DVD中英字幕]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2007-09-04{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://e34:e34@xl2.eee4.com:1002/[3E电影站www.eee4.com]完美风暴DVD中英双字CD1.rmvb" target=_blank>ftftp://e34:e34@xl2.eee4.com:1002/[3E电影站www.eee4.com]完美风暴DVD中英双字CD1.rmvb</A></TD></TR></TBODY></TABLE>CD2：<BR>
<TABLE style="BORDER-RIGHT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; BORDER-BOTTOM: #cccccc 1px dotted" cellSpacing=0 cellPadding=6 width="95%" align=center border=0>
<TBODY>
<TR>
<TD style="WORD-WRAP: break-word" bgColor=#fdfddf><ANCHOR></ANCHOR><A href="ftftp://e34:e34@xl2.eee4.com:1002/[3E电影站www.eee4.com]完美风暴DVD中英双字CD2.rmvb" target=_blank>ftftp://e34:e34@xl2.eee4.com:1002/[3E电影站www.eee4.com]完美风暴DVD中英双字CD2.rmvb</A></TD></TR></TBODY></TABLE></div><ul class="mmlist{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MPTFZ-3Wb.jpg{/dede:field}
