{dede:field name='keywords'}救世主/宇宙追缉令/平行歼灭战/{/dede:field}
{dede:field name='description'}救世主/宇宙追缉令/平行歼灭战/最后一强BD中英双字1024/1280高清迅雷下载、免费下载，救世主/宇宙追缉令/平行歼灭战/最后一强BD中英双字1024/1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}救世主/宇宙追缉令/平行歼灭战/最后一强BD中英双字1024/1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-02-13{/dede:field}
{dede:field name='body'}<p>
	&nbsp;<img alt="" src="http://img.album.pchome.net/54/69/60/23/cf9a02609df9ed9c68d40512faaed0cd.jpg" /></p>
<p>
	◎译　　名　《救世主/宇宙追缉令/平行歼灭战/最后一强》2001年李连杰科幻动作大片BD中英双字1024x560高清版<br />
	◎片　　名　The One<br />
	◎年　　代　2001<br />
	◎国　　家　美国<br />
	◎类　　别　动作/惊悚/科幻&nbsp;<br />
	◎语　　言　英语<br />
	◎字　　幕　中英双字<br />
	◎IMDB评分&nbsp; 5.5/10 (20,143 votes)<br />
	◎文件格式　BD-RMVB<br />
	◎视频尺寸　1024 x 560<br />
	◎文件大小　1CD<br />
	◎导　　演&nbsp; 黄毅瑜 James Wong<br />
	◎主　　演&nbsp; 李连杰 Jet Li&nbsp; ....Gabe Law/Gabriel Yulaw/Lawless&nbsp;<br />
	　　　　　　戴尔里&middot;林多 Delroy Lindo&nbsp; ....MVA Agent Harry Roedecker/Gas Station Attendant<br />
	　　　　　　卡拉&middot;古奇诺 Carla Gugino&nbsp; ....T.K. Law/Massie Walsh<br />
	　　　　　　杰森&middot;斯坦森 Jason Statham&nbsp; ....MVA Agent Evan Funsch<br />
	　　　　　　James Morrison&nbsp; ....LAPD Officer Bobby Aldrich<br />
	　　　　　　Richard Steinmetz&nbsp; ....D&#39;Antoni<br />
	　　　　　　Steve Rankin&nbsp; ....MVA Supervisor<br />
	　　　　　　Tucker Smallwood&nbsp; ....Prison Warden<br />
	　　　　　　Harriet Sansom Harris&nbsp; ....Nurse Besson<br />
	　　　　　　David Keats&nbsp; ....MRI Technician<br />
	　　　　　　Joel Stoffer&nbsp; ....Dr. Franklin<br />
	　　　　　　Kim McKamy&nbsp; ....Dr. Hamilton (as Kimberly Patton)<br />
	　　　　　　Denney Pierce&nbsp; ....ER Security Guard<br />
	　　　　　　Boots Southerland&nbsp; ....ER Security Guard<br />
	　　　　　　Peter McKernan&nbsp; ....Helicopter Pilot<br />
	　　　　　　Alan D. Purwin&nbsp; ....Helicopter Pilot (as Alan Purwin)<br />
	　　　　　　Matt Birman&nbsp; ....Pursuit Cop (uncredited)<br />
	　　　　　　乔治&middot;W&middot; 布什 George W. Bush&nbsp; ....Himself (archive footage) (uncredited)<br />
	　　　　　　Darrell Geer&nbsp; ....Prison Guard (uncredited)<br />
	　　　　　　阿尔&middot;戈尔 Al Gore&nbsp; ....Himself (archive footage) (uncredited)<br />
	　　　　　　Karl J. Martin&nbsp; ....Happyland Bicyclist (uncredited)<br />
	　　　　　　Brandon Molale&nbsp; ....Stygian Prisoner (uncredited)<br />
	　　　　　　Cynthia Pinot&nbsp; ....Girl In Subway (uncredited)<br />
	　　　　　　道格&middot;萨文特 Doug Savant&nbsp; ....Cop (uncredited)<br />
	<br />
	◎简　　介　&nbsp; &nbsp;<br />
	<br />
	　　故事发生在遥远的未来世界，加布利尔&middot;尤兰（李连杰）是一名与世无争的平凡人，他拥有一个美满的家，有美丽温柔的妻子与一条爱狗，小日子过得实在而安定。然而灾难还是到来了。<br />
	<br />
	　　一天尤兰突然发现自己的生活发生了翻天覆地的变化&mdash;&mdash;平凡的他不知为什么拥有了超能力，力大无穷，轻描淡写的一脚踢出就能废掉一根金属电线杆，而且身体的灵敏性和速度也大增，奔跑起来简直如风驰电掣.原来，来自另外一个平行空间的复制体、和他一模一样的&ldquo;坏尤兰&rdquo;已经非法潜伏到这个空间，这个坏尤兰已经杀死了其他数个空间的复制体，每杀掉一个自己，其他复制体的功力就会增长，现在，&ldquo;坏尤兰&rdquo;的目标正是惟一幸存的尤兰，伺机要将他致之死地&hellip;&hellip;<br />
	&nbsp;<br />
	幕后制作<br />
	<br />
	　　其实光看影片的<a href="http://www.eee4.com/" target="_blank">迅雷电影下载</a>名字（The One），就已经让人想起那部让人过目不忘的《骇客帝国》，里面那个外刚内柔的女骇客一直在絮叨着尼奥到底是不是&ldquo;The One&rdquo;，而据说《平行歼灭战》里李连杰的角色有一个慢镜头弯腰躲子弹和360度定格拍摄的镜头，这一切都让观众几乎以为自己要看的是《骇客帝国》续集。再看剧情，N多的相似情节一下涌了出来&mdash;&mdash;《越时空特警》、《挑战者》、《第六日》&hellip;&hellip;不过情节好象并不太重要，因为就如前面介绍的重点，李连杰的身手才是最大最亮的卖点。</p>

<p>
	【电影截图】：<br />
	<br />
	<br />
	<img onclick="if(this.width&gt;screen.width-461) window.open('http://img.album.pchome.net/54/68/92/28/19a1a75da46feb4f5d82adb2a809038c.jpg');" src="http://img.album.pchome.net/54/68/92/28/19a1a75da46feb4f5d82adb2a809038c.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 328px; border-top: 0px solid; border-right: 0px solid" />&nbsp;<br />
	<img onclick="if(this.width&gt;screen.width-461) window.open('http://img.album.pchome.net/54/68/92/28/2bbdcfddd049eac7aa21a2421946e32d.jpg');" src="http://img.album.pchome.net/54/68/92/28/2bbdcfddd049eac7aa21a2421946e32d.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 328px; border-top: 0px solid; border-right: 0px solid" /></p>
<br />
<p>
	2001年李连杰科幻动作大片《救世主令》BD中英双字1024x560高清版 －来自[www.eee4.com]：<img border="0" src="http://www.eee4.com/templets/img/down.jpg" /></p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://e7:e7@xl2.eee4.com:9306/[3E电影站www.eee4.com]救世主BD中英双字1024x560高清版.rmvb" target="_blank">ftp://e7:e7@xl2.eee4.com:9306/[3E电影站www.eee4.com]救世主BD中英双字1024x560高清版.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2804/飘花电影piaohua.com救世主BD中英双字1280高清.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2804/飘花电影piaohua.com救世主BD中英双字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1591T50-2LL.jpg{/dede:field}
