<?php
$z[0]=Array("field","星河战队/星舰战将/太空战士BD国",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","星河战队/星舰战将/太空战士BD国语配音中字1024高清迅雷下载、免费下载，星河战队/星舰战将/太空战士BD国语配音中字1024高清Gvod高清在线播放，剧情介绍等。",73,263);
$z[1][4]['name']="description";
$z[2]=Array("field","星河战队/星舰战将/太空战士BD国语配音中字1024高清",265,351);
$z[2][4]['name']="title";
$z[3]=Array("field","",353,392);
$z[3][4]['name']="writer";
$z[4]=Array("field","",394,433);
$z[4][4]['name']="source";
$z[5]=Array("field","2012-01-21",435,485);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",487,524);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://eee4.com:8116@vip13.eee4.com:8116/[3E迅雷电影站www.eee4.com]星河战队DVD中字.rmvb\" target=\"_blank",526,667);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MOV4I0-45G6.jpg",669,750);
$z[8][4]['name']="litpic";

?>