{dede:field name='keywords'}星河战队/星舰战将/太空战士BD国{/dede:field}
{dede:field name='description'}星河战队/星舰战将/太空战士BD国语配音中字1024高清迅雷下载、免费下载，星河战队/星舰战将/太空战士BD国语配音中字1024高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}星河战队/星舰战将/太空战士BD国语配音中字1024高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-01-21{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://eee4.com:8116@vip13.eee4.com:8116/[3E迅雷电影站www.eee4.com]星河战队DVD中字.rmvb" target="_blank{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MOV4I0-45G6.jpg{/dede:field}
