{dede:field name='keywords'}选举/校园风云BD中英双字1280高{/dede:field}
{dede:field name='description'}选举/校园风云BD中英双字1280高清经典高分喜剧迅雷下载、免费下载，选举/校园风云BD中英双字1280高清经典高分喜剧Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}选举/校园风云BD中英双字1280高清经典高分喜剧{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-06{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img.album.pchome.net/54/68/57/25/525a433bd4b94c9e753105fa3d7aab0c.jpg" /></p>
<p>
	【中文名称】选举 校园风云 大选之夜<br />
	【英文名称】Election<br />
	【年　　代】1999<br />
	【地　　区】美国<br />
	【类　　型】喜剧<br />
	【字幕语言】中文/英文<br />
	【视频尺寸】1280&times;720<br />
	【文件格式】RMVB+AAC<br />
	【片　　长】105 min&nbsp;<br />
	【IMDB评分】7.5/10(11,864 votes)<br />
	【导　　演】Alexander Payne&nbsp;<br />
	【编　　剧】Alexander Payne / Alexander Payne (Jim Taylor (III)) / Tom Perrotta&nbsp;<br />
	【主要演员】里斯 威瑟斯庞<br />
	　　　　　　马修 布罗德里克<br />
	　　　　　　克里斯 克莱恩<br />
	　　　　　　可琳坎普<br />
	　　　　　　马特 马洛伊</p>
<p>
	【剧情简介】</p>
<p>
	　　吉米&middot;麦卡里斯特(马修&middot;勃德瑞克饰)是一名深受学生喜爱的老师。在乔治华盛顿卡沃中学任教的12年中，由于业绩突出，吉米曾三次荣获&ldquo;最佳年度教师奖&rdquo;。但是最近他的生活将面临巨大改变，过去的一切荣誉，过去所从事的事业都将随着一场选举的展开而发生变化。<br />
	翠西&middot;弗丽克(瑞斯&middot;威泽斯普恩饰)是学校中最为雄心勃勃的女教师。她十分能干又极有上进心，但她总想把学校当成她日后成就大事业的跳板。平日，翠西时常奔忙于学校的俱乐部或委员会之间，处理各项事务。在她的观念中，只有不断努力的人才能在机会来临时大显身手。老天不负有心人，翠西等待的机会终于来到了，那就是竞选学生管理委员会的主席。<br />
	当选此职对翠西来说是天经地义之事，因为在侯选人中没有能对她构成威胁，可是事情并没按她设想的样子发展下去，这都是因为吉米也决定参加竞选。<br />
	就在吉米与翠西展开两人激烈竞争的时候，苔米(杰希卡&middot;坎贝尔饰)又横插进来。她是校橄榄球队明星保罗(克莱斯&middot;克雷饰)的妹妹。在这场竞选中，她的角色与吉米和翠西截然相反，她的任务不是当选主席之职，而是要取消学生管理委员这个机构，取消管理学生的制度。很自然她的竞选得到了许多学生的支持，他们组成所谓的学生&ldquo;十字军&rdquo;，向其他候选人发起猛烈进攻。<br />
	竞选的气氛越来越紧张，人们的热情也越来越高涨，但是哪方是正确的，哪方是错误的，已越来越无法让人分辨清楚。吉米的生活在竞选的强大冲击下已经变得无法控制，无论是在校内还是校外，他都开始感到困惑。竞选已不再是单纯的竞选，而是一场对人们的道德观、伦理观、爱情、事业及欲望的考验。</p>
<p>
	<img alt="" height="338" src="http://img.album.pchome.net/54/68/57/25/3735991712b91a9fe2a5b4caed5cb8b6.jpg" width="600" /></p>
<p>
	<img alt="" height="338" src="http://img.album.pchome.net/54/68/57/25/8e28e631be06332d86a942791a05df8d.jpg" width="600" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.net" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3350/飘花电影piaohua.com校园风云BD中英双字1280高清经.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3350/飘花电影piaohua.com校园风云BD中英双字1280高清经.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15I5P-4M57.jpg{/dede:field}
