{dede:field name='keywords'}妖魔大闹唐人街/妖魔大闹小神洲B{/dede:field}
{dede:field name='description'}妖魔大闹唐人街/妖魔大闹小神洲BD中英双字1024/1280高清迅雷下载、免费下载，妖魔大闹唐人街/妖魔大闹小神洲BD中英双字1024/1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}妖魔大闹唐人街/妖魔大闹小神洲BD中英双字1024/1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-04-22{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="/uploads/allimg/c120525/133O10104460-54O9.jpg" /></p>
<p>
	◎译　　名　《妖魔大闹唐人街/妖魔大闹小神洲》美国动作喜剧片DVD中字1280x720高清版<br />
	◎片　　名　Big Trouble in Little China<br />
	◎年　　代　1986<br />
	◎国　　家　美国<br />
	◎类　　别　动作/冒险/喜剧/幻想/爱情<br />
	◎语　　言　英语<br />
	◎字　　幕　中文字幕<br />
	◎IMDB评分&nbsp;&nbsp;7.1/10 (29,266 votes)<br />
	◎文件格式　RMVB<br />
	◎视频尺寸　1920 x 544<br />
	◎文件大小　1.12GB<br />
	◎片　　长　99 Mins<br />
	◎导　　演&nbsp; &nbsp;约翰&middot;卡朋特&nbsp; &nbsp;John Carpenter&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp;&nbsp;<br />
	◎主　　演&nbsp; &nbsp;库尔特&middot;拉塞尔&nbsp; &nbsp;Kurt Russell&nbsp; &nbsp;....Jack Burton<br />
	　　　　　　金&middot;凯特罗尔&nbsp; &nbsp;Kim Cattrall&nbsp; &nbsp;....Gracie Law&nbsp;&nbsp;<br />
	　　　　　　Dennis Dun&nbsp;&nbsp;....Wang Chi<br />
	　　　　　　詹姆斯&middot;洪 James Hong&nbsp;&nbsp;....David Lo Pan<br />
	　　　　　　Victor Wong&nbsp;&nbsp;....Egg Shen<br />
	　　　　　　凯特&middot;伯顿 Kate Burton&nbsp;&nbsp;....Margo<br />
	　　　　　　Donald Li&nbsp;&nbsp;....Eddie Lee<br />
	　　　　　　黄家达 Carter Wong&nbsp;&nbsp;....Thunder<br />
	　　　　　　Peter Kwong&nbsp;&nbsp;....Rain<br />
	　　　　　　白石千 James Pax&nbsp;&nbsp;....Lightning<br />
	　　　　　　suzee Pai&nbsp;&nbsp;....Miao Yin<br />
	　　　　　　Chao Li Chi&nbsp;&nbsp;....Uncle Chu<br />
	　　　　　　Jeff Imada&nbsp;&nbsp;....Needles<br />
	　　　　　　Rummel Mor&nbsp;&nbsp;....Joe Lucky<br />
	　　　　　　Craig Ng&nbsp;&nbsp;....One Ear<br />
	　　　　　　June Kyoto Lu&nbsp;&nbsp;....White Tiger (as June Kim)<br />
	　　　　　　Noel Toy&nbsp;&nbsp;....Mrs. O&#39;Toole<br />
	　　　　　　Jade Go&nbsp;&nbsp;....Chinese Girl in White Tiger<br />
	　　　　　　Jerry Hardin&nbsp;&nbsp;....Pinstripe Lawyer<br />
	　　　　　　James Lew&nbsp;&nbsp;....Chang Sing #1<br />
	　　　　　　Jim Lau&nbsp;&nbsp;....Chang Sing #2<br />
	　　　　　　Kenny Endoso&nbsp;&nbsp;....Chang Sing #3<br />
	　　　　　　Stuart Quan&nbsp;&nbsp;....Chang Sing #4<br />
	　　　　　　Gary Toy&nbsp;&nbsp;....Chang Sing #5<br />
	　　　　　　George Cheung&nbsp;&nbsp;....Chang Sing #6<br />
	　　　　　　Noble Craig&nbsp;&nbsp;....Sewer Monster<br />
	　　　　　　Danny Kwan&nbsp;&nbsp;....Chinese Guard<br />
	　　　　　　Min Luong&nbsp;&nbsp;....Tara<br />
	　　　　　　Paul J.Q. Lee&nbsp;&nbsp;....Chinese Gambler (as Paul Lee)<br />
	　　　　　　Al Leong&nbsp;&nbsp;....Wing Kong Hatchet Man<br />
	　　　　　　Gerald Okamura&nbsp;&nbsp;....Wing Kong Hatchet Man<br />
	　　　　　　Willie Wong&nbsp;&nbsp;....Wing Kong Hatchet Man<br />
	　　　　　　Eric Lee&nbsp;&nbsp;....Wing Kong Hatchet Man<br />
	　　　　　　Yukio G. Collins&nbsp;&nbsp;....Wing Kong Hatchet Man<br />
	　　　　　　Bill M. Ryusaki&nbsp;&nbsp;....Wing Kong Hatchet Man<br />
	　　　　　　Brian Imada&nbsp;&nbsp;....Wing Kong Hatchet Man<br />
	　　　　　　Nathan Jung&nbsp;&nbsp;....Wing Kong Hatchet Man<br />
	　　　　　　Dan Inosanto&nbsp;&nbsp;....Wing Kong Hatchet Man<br />
	　　　　　　Vernon Rieta&nbsp;&nbsp;....Wing Kong Hatchet Man<br />
	　　　　　　Daniel Wong&nbsp;&nbsp;....Wing Kong Security Guard<br />
	　　　　　　Daniel Lee&nbsp;&nbsp;....Wing Kong Security Guard<br />
	　　　　　　Lia Chang&nbsp;&nbsp;....Female Wing Kong Guard<br />
	　　　　　　Diana Tanaka&nbsp;&nbsp;....Female Wing Kong Guard<br />
	　　　　　　Donna L. Noguschi&nbsp;&nbsp;....Female Wing Kong Guard<br />
	　　　　　　Shinko Isobe&nbsp;&nbsp;....Female Wing Kong Guard<br />
	　　　　　　William B. Snider&nbsp;&nbsp;....Customs Agent (scenes deleted)<br />
	　　　　　　约翰&middot;卡朋特 John Carpenter&nbsp;&nbsp;....Worker in Chinatown (uncredited)<br />
	<br />
	◎简　　介　</p>
<p>
	<br />
	　　肉食品工Jack Burton，饮食店年轻老板王池，旅游车司机Egg Shen组成了一个追逐幽灵的小组，因王池的未婚妻在机场被拐骗，他们开始了在恶魔世界的大冒险，漂亮的女律师Gracie Law也参与进来，一同来到中国城与对手展开了激烈的斗争。此时，能呼风唤雨、发动雷鸣电闪使用妖术的&ldquo;暴风雨三人组&rdquo;头戴斗笠从天而降，前来助战，Jack等人顿感力量倍增。在魔窟里，妖怪的首领Lo Pan大施妖术，经过一番激烈较量，Gracie Law被抓走。最终，争议战胜邪魔，两位姑娘回到心上人身边。</p>

<p>
	<br />
	幕后制作<br />
	　　香港功夫动作片到底对好莱坞的影响有多深？本片是较早期的一个例证。这是一部模仿香港片的美国片，故事发生在唐人街的地底下，从故事情节、场景布置、演员数量以至武打镜头设计，均大量移植港片，结合了喜剧和动作的元素，场面颇为热闹，而且还加入了一丝美国式的讽刺。有多位华人演员参与演出。打斗设计电影下载属于早期模仿风格。只不过导演约翰．卡彭特始终是美国人，虽然他卖力地想拍一部纯娱乐性的东方版《魔宫传奇》，仍不免会让中国观众觉得有点非骡非马，但如将它视为用美国电影技术拍摄的中国功夫片则会发现不少好玩之处。</p>
<p>
	【电影截图】：<br />
	<br />
	<img src="/uploads/allimg/c120525/133O10105330-EX1.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 338px; border-top: 0px solid; border-right: 0px solid" />&nbsp;<br />
	<img src="/uploads/allimg/c120525/133O10106060-I291.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 338px; border-top: 0px solid; border-right: 0px solid" />&nbsp;<br />
	<img src="/uploads/allimg/c120525/133O1010CZ-RX5.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 338px; border-top: 0px solid; border-right: 0px solid" /></p>
	美国动作喜剧片《妖魔大闹唐人街》DVD中字1280x720高清版 －来自[www.eee4.com]：<img border="0" src="http://www.eee4.com/templets/img/down.jpg" /></p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				ftp://e3:e3@xl2.eee4.com:507/[3E电影站www.eee4.com]妖魔大闹唐人街DVD中字1280x720高清版.rmvb</td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				ftp://dy44:piaohua@dy44.piaohua.com:3268/飘花电影piaohua.com妖魔大闹唐人街1024高清版.rmvb</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1010S20-101054.jpg{/dede:field}
