{dede:field name='keywords'}魔王DVD中英双字2011动作科幻迅{/dede:field}
{dede:field name='description'}魔王DVD中英双字2011动作科幻迅雷下载、免费下载，魔王DVD中英双字2011动作科幻Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}魔王DVD中英双字2011动作科幻{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-01-02{/dede:field}
{dede:field name='body'}<p>
	<img alt="" height="900" src="http://www.fitbbs.com:81/attachment/Mon_1112/33_9849_e03420bb22a57b0.jpg" style="cursor: pointer" width="600" /></p>
<p>
	<img alt="" height="877" src="http://www.aceshowbiz.com/images/still/ra-one-poster01.jpg" style="cursor: pointer" width="600" /></p>
<p>
	◎译　　名　魔王/随机存取:版本1<br />
	◎片　　名　Ra One<br />
	◎年　　代　2011<br />
	◎国　　家　美国/印度<br />
	◎类　　别　动作/冒险/科幻<br />
	◎语　　言　北印度语<br />
	◎字　　幕　中英双字幕<br />
	◎IMDB评分 4.9/10 (from 8,893 users)<br />
	◎文件格式　Rmvb<br />
	◎视频尺寸　640 x 360<br />
	◎文件大小　631MB<br />
	◎片　　长　156 Mins<br />
	◎导　　演　安布汗&middot;辛哈 Anubhav Sinha<br />
	◎主　　演　沙鲁克&middot;罕 Shahrukh Khan ....Shekhar / G.One<br />
	　　　　　　卡琳娜&middot;卡普 Kareena Kapoor ....Sonia Subramanium<br />
	　　　　　　阿俊&middot;拉姆鲍 Arjun Rampal ....PiBi 2 / RA. One<br />
	　　　　　　莎哈娜&middot;高斯瓦米 Shahana Goswami ....Jenny Nayar<br />
	　　　　　　达里普&middot;塔西尔 Dalip Tahil ....The Baron<br />
	　　　　　　桑杰&middot;达特 Sanjay Dutt ....Special Appearance<br />
	　　　　　　朴雅卡&middot;乔普拉 Priyanka Chopra<br />
	　　　　　　拉吉尼坎塔 Rajnikanth<br />
	<br />
	◎简　　介　<br />
	<br />
	　　片名中的&ldquo;RA. &rdquo;是Random Access的缩写，意思是&ldquo;随机存取&rdquo;，男主角是一位超级英雄，故事讲述他在科学家的帮助下，与恶势力对抗，以拯救人类为己任。<br />
	<br />
	幕后制作<br />
	<br />
	片中将出现大量特效场景，因此邀请了好莱坞特效团队参与了制作，这也是继《贫民窟的百万富翁》、《我的名字叫可汗》等片之后，宝莱坞与好莱坞又一次亲密接触。<br />
	<br />
	◎影片截图<br />
	<br />
	<img alt="" height="337" src="http://img.album.pchome.net/54/84/69/41/1325421110ae91736f29aaf15448804bb567b89ce1.jpg" style="cursor: pointer" width="600" /><br />
	<img alt="" height="337" src="http://img.album.pchome.net/54/84/69/41/1325421110526bc5ac86ce7c6d262931b698babb4f.jpg" style="cursor: pointer" width="600" /><br />
	<img alt="" height="337" src="http://img.album.pchome.net/54/84/69/41/13254211108c9873dd891f45e7671189d700ef7d2f.jpg" style="cursor: pointer" width="600" /><br />
	&nbsp;</p>

<p>
	[下载地址]： &nbsp;<img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" /></p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2503/飘花电影piaohua.com魔王DVD中英双字.rmvb">&nbsp;ftp://dy44:piaohua@dy44.piaohua.com:2503/飘花电影piaohua.com魔王DVD中英双字.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15XLP-19420.jpg{/dede:field}
