{dede:field name='keywords'}猎人之夜BD中英双字1024高清迅雷{/dede:field}
{dede:field name='description'}猎人之夜BD中英双字1024高清迅雷下载、免费下载，猎人之夜BD中英双字1024高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}猎人之夜BD中英双字1024高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-24{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="/uploads/allimg/c120525/133O0TT320-1Va5.jpg" /></p>
<p>
	◎译　　名　猎人之夜/猎人的夜晚/雾夜惊魂/暗夜寻宝<br />
	◎片　　名　The Night Of The Hunter<br />
	◎年　　代　1955<br />
	◎国　　家　美国<br />
	◎类　　别　剧情/黑色/惊悚<br />
	◎语　　言　英语<br />
	◎字　　幕　中英双语字幕<br />
	◎IMDB评分 8.2/10 ( 34056票 )&nbsp; Top 250: #189<br />
	◎片　　长　88 Min<br />
	◎导　　演　查尔斯&middot;劳顿 Charles Laughton<br />
	◎主　　演　罗伯特&middot;米彻姆 Robert Mitchum&nbsp; ....Harry Powell<br />
	　　　　　　谢利&middot;温特斯 Shelley Winters&nbsp; ....Willa Harper<br />
	　　　　　　丽莲&middot;吉许 Lillian Gish&nbsp; ....Rachel Cooper<br />
	　　　　　　James Gleason&nbsp; ....Birdie Steptoe<br />
	　　　　　　Evelyn Varden&nbsp; ....Icey Spoon<br />
	　　　　　　Peter Graves&nbsp; ....Ben Harper<br />
	　　　　　　Don Beddoe&nbsp; ....Walt Spoon<br />
	　　　　　　Billy Chapin&nbsp; ....John Harper<br />
	　　　　　　Sally Jane Bruce&nbsp; ....Pearl Harper<br />
	　　　　　　Gloria Castillo&nbsp; ....Ruby (as Gloria Castilo)<br />
	　　　　　　George Wallace<br />
	　　　　　　科里&middot;艾伦 Corey Allen&nbsp; ....Macijah Blake, young man in town (uncredited)<br />
	　　　　　　Paul Bryar&nbsp; ....Bart, prison guard (uncredited)<br />
	　　　　　　Cheryl Callaway&nbsp; ....Mary (uncredited)<br />
	　　　　　　Michael Chapin&nbsp; ....Ruby&#39;s boyfriend (uncredited)<br />
	　　　　　　Mary Ellen Clemons&nbsp; ....Clary (uncredited)<br />
	　　　　　　Kathy Garver&nbsp; ....Child (uncredited)<br />
	　　　　　　John Hamilton&nbsp; ....Townsman who greets Rachel (uncredited)<br />
	　　　　　　Gloria Pall&nbsp; ....Dancer (uncredited)</p>
<p>
	&nbsp;</p>
<p>
	◎简　　介　</p>
<p>
	　　约翰的父亲为了一万块钱杀人。他藏好钱，然后嘱咐两个孩子不要告诉任何人，包括他们的母亲薇拉。立即赶来的警察抓住了约翰的父亲，并判了他死刑。他死后，一个神秘男子出现在薇拉身边，娶了薇拉，原来他是曾与本同房的囚犯。</p>
<p>
	　　这是一部完全不同于好莱坞模式的影片，描写一个变态的假传教士本&middot;哈勃，左手刺着&ldquo;恨&rdquo;，右手刺着&ldquo;爱&rdquo;。他跟一个带着两个孩子的寡妇薇拉结婚，目的是为了找到她前夫盗得的财宝。大人们信任他，而孩子们反而离他远远的。</p>
<p>
	◎一句话评论</p>
<p>
	The wedding night, the anticipation, the kiss, the knife, BUT ABOVE ALL... THE SUSPENSE!</p>
<p>
	The Hands Of ROBERT MITCHUM in &quot;The Night of the Hunter&quot;</p>
<p>
	查尔斯&middot;劳顿的《猎人之夜》是最伟大的美国电影之一，但是，因为缺乏合适的包装，没有获得应有的关注。</p>
<p>
	&mdash;&mdash;芝加哥太阳时报</p>
<p>
	《猎人之夜》揭示了这个世界上最真实纯粹的邪恶。</p>
<p>
	&mdash;&mdash;视觉周刊</p>
<p>
	《猎人之夜》，一个恐怖的寓言。</p>
<p>
	&mdash;&mdash;旧金山编年史</p>
<p>
	如果看《猎人之夜》时你还太小，那么，你的余生可能就要不断的做恶梦了。</p>
<p>
	&mdash;&mdash;国际电影杂志</p>
<p>
	◎幕后制作</p>
<p>
	　　1955年，查尔斯&middot;劳顿拍摄了电影《猎人之夜》，这是他一生中导演的唯一一部电影。电影上映后，评论界态度并不友好，票房也是惨败，于是，恼羞成怒的劳顿发誓再也不执导任何一部电影。但颇具讽刺意味的是，仅仅过了几年，这部电影就再次上映，引发了重看的热潮。现在，这部电影被誉为美国20世纪50年代最伟大的作品。时间为劳顿带来了公正，再次给了那些可笑的评论家一记响亮的耳光。</p>
<p>
	◎截　　图</p>
<p>
	&nbsp;<img alt="" height="359" src="/uploads/allimg/c120525/133O0TU5F-192F1.jpg" style="cursor: pointer" width="600" /></p>
<p>
	<img alt="" height="359" src="/uploads/allimg/c120525/133O0TV640-203E7.jpg" style="cursor: pointer" width="600" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="/uploads/allimg/c120525/133O0T31310-42214.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：http://www.xiaozhizhu.net</td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				ftp://dy44:piaohua@dy44.piaohua.com:3489/飘花电影piaohua.com猎人之夜BD中英双字1024高清.mkv</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O0TWH0-211593.jpg{/dede:field}
