{dede:field name='keywords'}侏罗纪公园1BD中英双字1024/1280{/dede:field}
{dede:field name='description'}侏罗纪公园1BD中英双字1024/1280高清迅雷下载、免费下载，侏罗纪公园1BD中英双字1024/1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}侏罗纪公园1BD中英双字1024/1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-11-01{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://e20:e20@xl2.eee4.com:9219/[3E电影站www.eee4.com]侏罗纪公园1[DVD中英双字1280x720高清版].rmvb" target="_blank{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MO95V30-44235.jpg{/dede:field}
