{dede:field name='keywords'}心灵实验DVD中字2011最新美国科{/dede:field}
{dede:field name='description'}心灵实验DVD中字2011最新美国科幻恐怖大片迅雷下载、免费下载，心灵实验DVD中字2011最新美国科幻恐怖大片Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}心灵实验DVD中字2011最新美国科幻恐怖大片{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-12-30{/dede:field}
{dede:field name='body'}<p>
	<img src="http://img165.poco.cn/mypoco/myphoto/20111230/11/56643687201112301118241615035827377_004.jpg" /></p>
<p>
	◎译　　名　心灵实验<br />
	◎片　　名　Psychic Experiment<br />
	◎年　　代　2010<br />
	◎国　　家　美国<br />
	◎类　　别　恐怖/科幻<br />
	◎语　　言　英语<br />
	◎字　　幕　中文<br />
	◎IMDB评分 5.3/10 (from 105 users)<br />
	◎IMDB链接 <a href="http://www.imdb.com/title/tt1245111">http://www.imdb.com/title/tt1245111</a><br />
	◎文件格式　DVD-RMVB<br />
	◎视频尺寸　624 x 352<br />
	◎文件大小　1CD 540MB<br />
	◎片　　长　93 Mins<br />
	◎导　　演　Mel House<br />
	◎主　　演　凯蒂&middot;菲德斯通 Katie Featherston ... Elspeth Thompson<br />
	　　　　　　格伦&middot;莫肖尔 Glenn Morshower ...Mr. Anderson<br />
	　　　　　　Debbie Rochon ... Marie Gray<br />
	　　　　　　Reggie Bannister ... Joseph Webber<br />
	　　　　　　Adrienne King ... Louise Strack<br />
	　　　　　　凯茜&middot;拉姆金 Kathy Lamkin ... Mrs. Anderson<br />
	　　　　　　娜塔丽&middot;琼斯 Natalie Jones ... Julie Dylan (as Natali Jones)<br />
	　　　　　　Shannon Lark ... Jennifer Crusel<br />
	　　　　　　埃琳&middot;布鲁克 Eryn Brooke ... Tracie Johnson<br />
	　　　　　　Brandi Price ... Amanda Saxon<br />
	　　　　　　Mel House ... Dr. Lantz<br />
	　　　　　　Krystn Caldwell ... Creature<br />
	　　　　　　Brady Hender ... Young Cole<br />
	　　　　　　Melanie Donihoo ... Lisa Stanton<br />
	　　　　　　Denton Blane Everett ... Cole Gray</p>
<p>
	◎简　　介　</p>
<p>
	这是一个很小的，能自给自足的田园诗般的社区 。 从表面上看，这里似乎像是一个完美的居住地。 你需要的一切可能就近在咫尺 。 但社区的外表下隐藏着黑暗的过去和一个更黑暗的秘密。 一个医生在病人的大脑植入芯片，命令并控制他们杀死每一个人。</p>

<p>
	◎影片截图</p>

<p>
	<img src="http://img165.poco.cn/mypoco/myphoto/20111230/11/56643687201112301118241615035827377_000.jpg" /></p>
<p>
	<img src="http://img165.poco.cn/mypoco/myphoto/20111230/11/56643687201112301118241615035827377_002.jpg" /></p>
<p>
	<img src="http://img165.poco.cn/mypoco/myphoto/20111230/11/56643687201112301118241615035827377_001.jpg" /></p>

<p>
	[下载地址]： &nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2477/飘花电影piaohua.com心灵实验DVD中字.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2477/飘花电影piaohua.com心灵实验DVD中字.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15X5920-5I52.jpg{/dede:field}
