{dede:field name='keywords'}灵异第六感/第六感/鬼眼BD中英双{/dede:field}
{dede:field name='description'}灵异第六感/第六感/鬼眼BD中英双字1024/1280高清迅雷下载、免费下载，灵异第六感/第六感/鬼眼BD中英双字1024/1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}灵异第六感/第六感/鬼眼BD中英双字1024/1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-11-27{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://e20:e20@xl2.eee4.com:9306/[3E电影站www.eee4.com]灵异第六感DVD中英双字1024x576高清版.rmvb" target="_blank{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MP2E430-53K1.jpg{/dede:field}
