{dede:field name='keywords'}黑色大丽花[BD中英双字1024x576{/dede:field}
{dede:field name='description'}黑色大丽花[BD中英双字1024x576高清版]迅雷下载、免费下载，黑色大丽花[BD中英双字1024x576高清版]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}黑色大丽花[BD中英双字1024x576高清版]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2010-06-29{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://3e:3e@d8.3edyy.com:168/【3E电影院www.eee4.cc】黑色大丽花BD中英双字1024x576高清版.rmvb" target="_blank{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MP313610-13100.jpg{/dede:field}
