{dede:field name='keywords'}雨果/雨果的秘密BD1280高清迅雷{/dede:field}
{dede:field name='description'}雨果/雨果的秘密BD1280高清迅雷下载、免费下载，雨果/雨果的秘密BD1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}雨果/雨果的秘密BD1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-02-19{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://www.bluraywire.com/wp-content/uploads/2012/02/hugobluray.jpg" style="width: 650px; height: 823px" /></p>
<p>
	◎译　　名　雨果/雨果&middot;卡布里特/雨果&middot;卡布里特的发明/发明男孩雨果/雨果&middot;卡贝特的发明/雨果的冒险(台)<br />
	◎片　　名　Hugo<br />
	◎年　　代　2011<br />
	◎国　　家　美国<br />
	◎类　　别　冒险/剧情/家庭/神秘<br />
	◎语　　言　英语<br />
	◎字　　幕　中英双字<br />
	◎IMDB评分 &nbsp; 8.2/10 (24,747 votes) Top 250 #200<br />
	◎IMDB链接 &nbsp; <a href="http://www.imdb.com/title/tt0970179/" target="_blank">http://www.imdb.com/title/tt0970179/</a><br />
	◎文件格式　x264 + DTS<br />
	◎视频尺寸　1280 x 720<br />
	◎文件大小　5/4 DVD<br />
	◎片　　长　02:06:21<br />
	◎导　　演　马丁&middot;斯科塞斯 Martin Scorsese<br />
	◎主　　演　阿沙&middot;巴特菲尔德 Asa Butterfield ....Hugo Cabret<br />
	　　　　　　科洛&middot;莫瑞兹 Chloe Moretz ....Isabelle<br />
	　　　　　　本&middot;金斯利 Ben Kingsley ....Georges M&eacute;li&egrave;s<br />
	　　　　　　萨莎&middot;拜伦&middot;科恩 Sacha Baron Cohen ....Station inspector<br />
	　　　　　　雷&middot;温斯顿 Ray Winstone ....Uncle Claude<br />
	　　　　　　艾米莉&middot;莫迪默 Emily Mortimer ....Lisette<br />
	　　　　　　克里斯托弗&middot;李 Christopher Lee ....Monsieur Labisseqq<br />
	　　　　　　海伦&middot;麦克洛瑞 Helen McCrory ....Mama Jeanne<br />
	　　　　　　迈克尔&middot;斯图巴 Michael Stuhlbarg ....Rene Tabard<br />
	　　　　　　弗朗西斯&middot;德&middot;拉&middot;图瓦 Frances de la Tour ....Madame Emilie<br />
	　　　　　　理查德&middot;格雷弗斯 Richard Griffiths ....Monsieur Frick<br />
	　　　　　　裘德&middot;洛 Jude Law ....Hugo&#39;s Father<br />
	　　　　　　凯文&middot;艾尔东 Kevin Eldon ....Policeman<br />
	　　　　　　Gulliver McGrath ....Young Tabard<br />
	　　　　　　Shaun Aylward ....Street Kid<br />
	　　　　　　Emil Lager ....Django Reinhardt<br />
	　　　　　　Angus Barnett ....Theatre Manager<br />
	　　　　　　Edmund Kingsley ....Camera Technician<br />
	　　　　　　Max Wrottesley ....Train Engineer<br />
	　　　　　　Marco Aponte ....Train Engineer Assistant<br />
	　　　　　　Ben Addis ....Salvador Dali<br />
	　　　　　　Robert Gill ....James Joyce<br />
	　　　　　　爱德&middot;山德斯 Ed Sanders ....Young Tabard&#39;s Brother<br />
	　　　　　　Terence Frisch ....Circus Barker<br />
	　　　　　　Max Cane ....Circus Barker<br />
	　　　　　　Frank Bourke ....Gendarme<br />
	　　　　　　Stephen Box ....Gendarme<br />
	　　　　　　Kostas Katsikis ....Business Man (uncredited)<br />
	　　　　　　Mihai Arsene ....French Fisherman<br />
	　　　　　　Eric Haldezos ....Policeman<br />
	　　　　　　Graham Curry ....Railway Porteur 71 (uncredited)<br />
	　　　　　　Amanda Dyar ....Train Station Pedestrian (uncredited)<br />
	　　　　　　Hugo Malpeyre ....Theater Guest (uncredited)<br />
	　　　　　　布莱恩&middot;瑟兹尼克 Brian Selznick ....Eager Student (uncredited)<br />
	　　　　　　马丁&middot;斯科塞斯 Martin Scorsese ....Photographer<br />
	　　　　　　Catherine Balavage ....Parisian Cafe Women (uncredited)<br />
	　　　　　　Ed Pearce ....Business Man (uncredited)<br />
	　　　　　　Gino Picciano ....Worker (uncredited)<br />
	　　　　　　查理&middot;卓别林 Charles Chaplin ....A Tramp (archive footage) (uncredited)<br />
	　　　　　　道格拉斯&middot;范朋克 Douglas Fairbanks ....The Thief of Bagdad (archive footage) (uncredited)<br />
	　　　　　　巴斯特&middot;基顿 Buster Keaton ....Johnny Gray (archive footage) (uncredited)<br />
	　　　　　　哈罗德&middot;劳埃德 Harold Lloyd ....The Boy (archive footage) (uncredited)<br />
	　　　　　　Alexandra Metaxa ....American Tourist<br />
	<br />
	<br />
	◎简　　介<br />
	<br />
	剧情<br />
	<br />
	　　故事发生在上世纪30年代末巴黎一个繁忙火车站，主人公12岁孤儿雨果藏匿与墙壁后的暗窄通道里，会在每个夜晚的烛光下给火车站的27座时钟一丝不苟地上油、校准；死去的父亲给他留下的唯一遗产便是神秘笔记和一台旁人眼中完全是垃圾的机器人，雨果从一本木刻书得知这个机器人可以写字作画&mdash;&mdash;如果有天他能把它修好。<br />
	　　影片其他主要角色包括车站玩具店的老板乔治斯、他的孙女伊莎贝拉，以及另外一个有钱人家的小女孩。雨果为了得到修理机器人的零件到玩具店偷东西，最终发现古怪老板原来就是隐姓埋名的乔治&middot;梅里耶，他的《月球旅行记》是雨果父亲生前最喜欢的电影。<br />
	<br />
	一句话评论<br />
	<br />
	斯科塞斯给出了自詹姆斯&middot;卡梅隆的《阿凡达》之后最引人入胜的3D电影。<br />
	<br />
	&mdash;&mdash;Deadline.com<br />
	<br />
	影片结合了身体喜剧元素（这显然来自于默片的影响）以及成年人的感动，当然，还有对电影本身动情高歌出的热爱。<br />
	<br />
	&mdash;&mdash;CinemaBlend.com<br />
	<br />
	这是一部诚心奉献出的视觉盛宴，不过它可能会在颁奖季丧失一些机会&mdash;&mdash;由于其不够令人满意的情节以及对默片的迷恋可能会令不少观众疏远本片。<br />
	<br />
	&mdash;&mdash;IndieWire.com<br />
	<br />
	幕后制作<br />
	<br />
	　　女儿的睡前故事<br />
	<br />
	　　作家布莱恩&middot;瑟兹尼克创作的以儿童为主角的非儿童读物《雨果&middot;卡布里特》是一本充满了玄妙和魔幻色彩的读物。在获得了2007年的鹅毛笔大奖之后就成为了热门读物。其实，这本书本不会引起马丁&middot;斯科塞斯的注意，而且一个以儿童为主角的魔幻故事，并不是马丁所擅长的&ldquo;社会剧&rdquo;。只不过，在马丁那位11岁的小女儿的催化下，机缘就这么巧合般地碰在了一起。<br />
	<br />
	　　马丁&middot;斯科塞斯每天晚上都要给自己的11岁女儿说一个睡前故事，好哄她睡觉。在连续几年的阅读儿童读物之后，斯科塞斯渐渐产生了要制作一部以儿童为主角的影片的念头。他说：&ldquo;在读了很多年的儿童读物之后，我觉得自己是不是能制作一部儿童电影。其实，远离名人传记、犯罪故事，来塑造一个儿童的世界，也挺好玩的。主角之间没有枪战，只有换牙的经历，这不是很好么？&rdquo;斯科塞斯说做就做，他从自己阅读的那些儿童读物里找了一本最适合改编上银幕的，这就是《雨果&middot;卡布里特》。斯科塞斯说：&ldquo;首先我的女儿非常喜欢这个故事，其次这本书给我留下了很深刻的印象，而且整个故事的电影性也很强。最重要的是，故事中出现了梅里爱和《月球旅行记》这样的电影的鼻祖。所以，它像是童话，但又与现实有很强烈的联系，所以我看好了这本书，并希望把它搬上银幕。&rdquo;<br />
	<br />
	　　对于斯科塞斯要改编自己的作品，小说的原作者布莱恩&middot;瑟兹尼克显得非常受用，他说：&ldquo;斯科塞斯是一个非常杰出的电影作者，他愿意改编我的作品，我也非常高兴。这个故事和电影史有关，也许会非常符合斯科塞斯的心意。最重要的是，斯科塞斯将用3D的模式拍这部电影，我想这才是斯科塞斯的真实用意吧。&rdquo;<br />
	<br />
	　　老导演的3D尝试<br />
	<br />
	　　和很多文艺片导演不同，斯科塞斯不仅不反对3D电影，他还很想执导一部3D作品。他说：&ldquo;我们就生活在一个3D的世界里，看到的、使用的、接触的都是3D。那么为什么不拍摄一部3D作品呢？&rdquo;<br />
	<br />
	　　《雨果&middot;卡布里特》讲述了一个发生在1920年代的巴黎的故事，那是一个发明大爆炸的年代，各式各样的机器和发明鳞次栉比地出现在这个世界上。而布莱恩&middot;瑟兹尼克则把这些新潮的玩具和人类的情感联系了起来，斯科塞斯说：&ldquo;瑟兹尼克的这个作品，既不是小说、也不是绘本，更不是什么配图童话之类的东西，而是一本综合了很多元素的故事书。在这个故事里，巴黎的质感是非常重要的。在我的电影里，影片的主题变调成了一种关联，一种老巴黎的调调和质感成为了影片氛围。除了电影，我还在影片中展示了其他的多种关联，譬如说两个小孩之间的关联、他和父辈之间的关联、和梅里爱之间的关联、和电影本身的关联，机器与发明与人们之间的关联。我想在电影中展示出一种真实感，那种像是在现实生活中的可以触摸的3D的感受。所以我觉得现在的3D是一种最好的表达手段。&rdquo;<br />
	<br />
	　　拍摄3D电影，对斯科塞斯这样的老导演来说，其实并不是一件容易的事情，除了技术上的难题要克服之外，更重要的是导演的拍摄习惯上的改变。斯科塞斯说：&ldquo;拍摄3D电影并不像我之前想象得那么容易，每个地方都有一些问题需要克服。但是最重要的是，我必须得时时刻刻提醒自己是在拍摄3D电影。在拍摄的过程中，我每拍一个镜头都要想是在重新思考电影一般。我觉得这是必要的，因为3D不仅仅是一个噱头，更是一种说故事的维度。在这种拍摄的前提下，我们必须重新设计机位、重新设计镜头、重新考虑电影拍摄中的一切元素。&rdquo;<br />
	<br />
	　　闪耀的英伦班底<br />
	<br />
	　　在离开了迪卡普里奥之后，斯科塞斯为自己这部备受瞩目的3D影片找来了一个光辉璀璨的演员班底。在主要演员阵容中，除了科洛&middot;莫瑞兹来自美国外，其他的大部分演员都来自英伦半岛。这其中有另一个小演员阿沙&middot;巴特菲尔德、克里斯托弗&middot;李、萨莎&middot;拜伦&middot;科恩、雷&middot;温斯顿、艾米莉&middot;莫迪默和本&middot;金斯利。<br />
	<br />
	　　因出演《海扁王》而蹿红的Hit－Girl科洛&middot;莫瑞兹对于能和马丁这样大级别的导演合作，说：&ldquo;和我之前合作的很多导演不同，斯科塞斯是一个很有个人魅力和特色的导演。他不需要太多的意见，自己就可以拍摄出极为杰出的镜头－－要知道那可是一个带有斯科塞斯风格的镜头。而且，为了拍摄3D，他似乎是重新思索了电影的拍摄方法，拍摄出了这么一部极为完美的电影。他的工作方法，我没有办法解释，可能只有你呆在现场，才能了解他是怎么工作的。对于我来说，斯科塞斯就像是一个父亲一样，他总是很关心我和阿沙&middot;巴特菲尔德。&rdquo;<br />
	<br />
	　　对于片中&ldquo;挑大梁&rdquo;的英伦演员，斯科塞斯说：&ldquo;国籍并不是我选择演员时考虑的因素，我觉得这样的演员适合这个角色，就找来了他。就是这么自然，这部影片中汇集了很多英国的杰出的演员。他们在电影中的表现非常出色，给这部电影提供了无与伦比的细节与质感。&rdquo;<br />
	<br />
	花絮<br />
	<br />
	&middot;本片是著名导演马丁&middot;斯科塞斯的首部3D力作。<br />
	&middot;本片根据布莱恩&middot;瑟兹尼克的同名畅销小说改编。原著于07年曾获得鹅毛笔大奖，并一度在美国《纽约时报》畅销书排行榜名列前茅，甚至被业内视作《哈利&middot;波特》之后最好的儿童魔幻作品。<br />
	&middot;这是马丁&middot;斯科塞斯近7年以来，第一部不是莱昂纳多&middot;迪卡普里奥主演的故事片。<br />
	&middot;这是马丁&middot;斯科塞斯近18年内拍摄的第一部PG级电影。<br />
	&middot;影片参加了2011年的纽约电影节，当时影片还没有制作完成，是以半成品的身份来参展的。这是该电影节历史上的第二部半成品。第一部是1991年的《美女与野兽》。</p>
<p>
	<img alt="" src="http://img.album.pchome.net/48/32/32/45/dcda76bf1bce96d18d0ccdf033d8ab62.2011" style="width: 696px; height: 392px" /><img alt="" src="http://img.album.pchome.net/48/32/32/45/9eb36e45ff364dfbe93671dc29b3e025.2011" style="width: 696px; height: 392px" /><img alt="" src="http://img.album.pchome.net/48/32/32/45/0c2d7f2b83b08e3cee94ba6e603cd3a2.2011" style="width: 696px; height: 392px" /><img alt="" src="http://img.album.pchome.net/48/32/32/45/c48285c9fe4582e19824e62a79da53fd.2011" style="width: 696px; height: 392px" /><br />
	&nbsp;</p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="&#13;&#10;ftp://dy125:piaohua@dy125.piaohua.com:7621/飘花电影piaohua.com雨果的秘密BD中英双字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:7621/飘花电影piaohua.com雨果的秘密BD中英双字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15922630-244E.jpg{/dede:field}
