{dede:field name='keywords'}失婴记DVD中字IMDB经典TOP230迅{/dede:field}
{dede:field name='description'}失婴记DVD中字IMDB经典TOP230迅雷下载、免费下载，失婴记DVD中字IMDB经典TOP230Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}失婴记DVD中字IMDB经典TOP230{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-21{/dede:field}
{dede:field name='body'}<p>
	◎译　　名　失婴记/罗丝玛丽的婴儿/魔鬼怪婴/魔鬼圣婴<br />
	◎片　　名　Rosemarys Baby<br />
	◎年　　代　1968<br />
	◎国　　家　美国<br />
	◎类　　别　剧情/恐怖<br />
	◎语　　言　英语<br />
	◎IMDB评分 8.0/10 (18,312 votes)&nbsp;&nbsp;top 250: #230<br />
	◎IMDB链接：<a href="http://www.bluemv.com" title="电影下载">http://www.bluemv.com</a><br />
	◎文件格式　HDRIP-RMVB<br />
	◎视频尺寸　832 x 448<br />
	◎文件大小　3CD<br />
	◎片　　长　136 Min<br />
	◎导　　演　罗曼&middot;波兰斯基 Roman Polanski<br />
	◎主　　演　Mia Farrow .... Rosemary Woodhouse<br />
	　　　　　　John Cassavetes .... Guy Woodhouse<br />
	　　　　　　Ruth Gordon .... Minnie Castevet<br />
	　　　　　　Sidney Blackmer .... Roman Castevet<br />
	　　　　　　Maurice Evans .... Edward &#39;Hutch&#39; Hutchins<br />
	　　　　　　Ralph Bellamy .... Dr. Abraham Sapirstein<br />
	　　　　　　Victoria Vetri .... Terry Gionoffrio (as Angela Dorian)<br />
	　　　　　　Patsy Kelly .... Laura-Louise<br />
	　　　　　　Elisha Cook Jr. .... Mr. Nicklas (as Elisha Cook)<br />
	　　　　　　Emmaline Henry .... Elise Dunstan<br />
	　　　　　　Charles Grodin .... Dr. C.C. Hill<br />
	　　　　　　Hanna Landy .... Grace Cardiff<br />
	　　　　　　Phil Leeds .... Dr. Shand (as Philip Leeds)<br />
	　　　　　　D&#39;Urville Martin .... Diego<br />
	　　　　　　Hope Summers .... Mrs. Gilmore<br />
	<br />
	<br />
	<br />
	◎简　　介　<br />
	<br />
	剧情简介：<br />
	　　这是一部现代恐怖怪谈片，内容讲述纽约一个籍籍无名的演员凯与妻子罗丝玛丽搬到曼哈顿一间古老的会寓定居，之前有过这间公寓的种种不祥之谈，但他们没有放在心上。而他们的邻居住着的老太太的养女不明原因自杀身亡了。因此罗丝玛丽不大愿意与他们交往，相反丈夫与他们相处得甚是融洽。就在此时，由于其他演员连续发生事故，使得凯有机会在演出方面被安排一个极佳的角色。一天晚上，凯告诉罗丝说希望能生个孩子，当天晚上罗丝做了一个恶梦，梦见混身满长毛的怪侵犯她，不久她即告怀身孕。隔壁老太米妮热心的照顾着她，她却日益消瘦。后来罗丝在死去的朋友处获得了一本书，发现丈夫和隔壁的老太全家竟有点像书中所说的魔鬼家族。后来她产下的婴儿也没有瞳孔，她想杀死她，却看见她脸上浮现出属于母亲特有的笑容，难道她也成为魔鬼的一族了吗？<br />
	<br />
	影片花絮：<br />
	&middot;曼哈顿上西区的达科他大楼在本片中重新命名为布莱姆渡(The Bramford)。<br />
	&middot;在拍摄该片期间，米娅o法洛收到了她当时的丈夫弗兰克&middot;西纳塔的离婚协议。<br />
	&middot;阿尔弗雷德&middot;西区柯克原定是该片的导演。<br />
	&middot;当时盛传一个谣言，说撒旦教会的创始人安东&middot;拉维为电影提供...<br />
	<br />
	电影相关：<br />
	　　罗曼波兰斯基在1968年的作品，是其代表作之一。基于艾拉-莱文(Ira Levin)的同名女性题材恐怖小说改编</p>
<p>
	<img alt="" src="http://pic.piaohua.com/0701pic/allimg/120305/1-120305193606454.jpg" /></p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<anchor></anchor><a href="ftp://dy44:piaohua@dy44.piaohua.com:2961/飘花电影piaohua.com失婴记DVD中字CD1.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2961/飘花电影piaohua.com失婴记DVD中字CD1.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<anchor></anchor><a href="ftp://dy44:piaohua@dy44.piaohua.com:2961/飘花电影piaohua.com失婴记DVD中字CD2.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2961/飘花电影piaohua.com失婴记DVD中字CD2.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<anchor></anchor><a href="ftp://dy44:piaohua@dy44.piaohua.com:2961/飘花电影piaohua.com失婴记DVD中字CD3.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2961/飘花电影piaohua.com失婴记DVD中字CD3.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O16460P-43I6.jpg{/dede:field}
