{dede:field name='keywords'}我人生的甘雨第35集韩剧迅雷下载{/dede:field}
{dede:field name='description'}我人生的甘雨第35集韩剧迅雷下载、免费下载，我人生的甘雨第35集韩剧Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}我人生的甘雨第35集韩剧{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-22{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img.album.pchome.net/02/25/03/37/29796b23db66a2f43a865d05bff7d859.jpg" /></p>
<p>
	<img onload="if(this.width&gt;650){this.width=650;};return false;" src="http://img.funshion.com/attachment/new_images/2012/03-30/18395589_1333090905_397.jpg" /></p>
<p>
	[中文剧名]：我人生的甘雨<br />
	[韩文剧名]：&#45236; &#51064;&#49373;&#51032; &#45800;&#48708;<br />
	[类&nbsp;&nbsp; 型]：SBS晨间日播剧<br />
	[播出时间]：2012年4月2日起每周一至五早8点40分（北京时间7点40分）<br />
	[导&nbsp;&nbsp;&nbsp; 演]：&#48149;&#50857;&#49692;<br />
	[编&nbsp;&nbsp;&nbsp; 剧]：&#44256;&#48393;&#54889;<br />
	[主&nbsp;&nbsp;&nbsp; 演]：李多熙 沈亨泽 柳尚旭 申珠雅 金海仁<br />
	[集&nbsp;&nbsp;&nbsp; 数]：预计120集<br />
	[接&nbsp;&nbsp;&nbsp; 档]：太阳的新娘<br />
	[官&nbsp;&nbsp;&nbsp; 网]：<br />
	[剧情简介]：讲述一个女孩的明星父亲，因脑出血而病倒，而就在此时父亲过去的妻子和隐藏的恋人一一出现，与父亲的家族发生了一些列纠葛的故事。</p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.net" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3142/飘花电影piaohua.com我人生的甘雨EP01.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3142/飘花电影piaohua.com我人生的甘雨EP01.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3142/飘花电影piaohua.com我人生的甘雨EP02.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3142/飘花电影piaohua.com我人生的甘雨EP02.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3142/飘花电影piaohua.com我人生的甘雨EP03.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3142/飘花电影piaohua.com我人生的甘雨EP03.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3152/飘花电影piaohua.com我人生的甘雨EP04.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3152/飘花电影piaohua.com我人生的甘雨EP04.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3165/飘花电影piaohua.com我人生的甘雨EP05.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3165/飘花电影piaohua.com我人生的甘雨EP05.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3188/飘花电影piaohua.com我人生的甘雨EP06.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3188/飘花电影piaohua.com我人生的甘雨EP06.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3195/飘花电影piaohua.com我人生的甘雨EP07.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3195/飘花电影piaohua.com我人生的甘雨EP07.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3202/飘花电影piaohua.com我人生的甘雨EP08.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3202/飘花电影piaohua.com我人生的甘雨EP08.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3206/飘花电影piaohua.com我人生的甘雨EP09.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3206/飘花电影piaohua.com我人生的甘雨EP09.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3231/飘花电影piaohua.com我人生的甘雨EP10.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3231/飘花电影piaohua.com我人生的甘雨EP10.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3238/飘花电影piaohua.com我人生的甘雨EP11.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3238/飘花电影piaohua.com我人生的甘雨EP11.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3245/飘花电影piaohua.com我人生的甘雨EP12.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3245/飘花电影piaohua.com我人生的甘雨EP12.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3262/飘花电影piaohua.com我人生的甘雨EP13.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3262/飘花电影piaohua.com我人生的甘雨EP13.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3262/飘花电影piaohua.com我人生的甘雨EP14.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3262/飘花电影piaohua.com我人生的甘雨EP14.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3285/飘花电影piaohua.com我人生的甘雨EP15.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3285/飘花电影piaohua.com我人生的甘雨EP15.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3285/飘花电影piaohua.com我人生的甘雨EP16.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3285/飘花电影piaohua.com我人生的甘雨EP16.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3293/飘花电影piaohua.com我人生的甘雨EP17.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3293/飘花电影piaohua.com我人生的甘雨EP17.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3299/飘花电影piaohua.com我人生的甘雨EP18.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3299/飘花电影piaohua.com我人生的甘雨EP18.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3307/飘花电影piaohua.com我人生的甘雨EP19.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3307/飘花电影piaohua.com我人生的甘雨EP19.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3329/飘花电影piaohua.com我人生的甘雨EP20.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3329/飘花电影piaohua.com我人生的甘雨EP20.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3329/飘花电影piaohua.com我人生的甘雨EP21.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3329/飘花电影piaohua.com我人生的甘雨EP21.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3333/飘花电影piaohua.com我人生的甘雨EP22.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3333/飘花电影piaohua.com我人生的甘雨EP22.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3341/飘花电影piaohua.com我人生的甘雨EP23.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3341/飘花电影piaohua.com我人生的甘雨EP23.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3368/飘花电影piaohua.com我人生的甘雨EP24.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3368/飘花电影piaohua.com我人生的甘雨EP24.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3368/飘花电影piaohua.com我人生的甘雨EP25.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3368/飘花电影piaohua.com我人生的甘雨EP25.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3374/飘花电影piaohua.com我人生的甘雨EP26.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3374/飘花电影piaohua.com我人生的甘雨EP26.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3379/飘花电影piaohua.com我人生的甘雨EP27.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3379/飘花电影piaohua.com我人生的甘雨EP27.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3400/飘花电影piaohua.com我人生的甘雨EP28.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3400/飘花电影piaohua.com我人生的甘雨EP28.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3400/飘花电影piaohua.com我人生的甘雨EP29.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3400/飘花电影piaohua.com我人生的甘雨EP29.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3421/飘花电影piaohua.com我人生的甘雨EP30.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3421/飘花电影piaohua.com我人生的甘雨EP30.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3427/飘花电影piaohua.com我人生的甘雨EP31.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3427/飘花电影piaohua.com我人生的甘雨EP31.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3442/飘花电影piaohua.com我人生的甘雨EP32.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3442/飘花电影piaohua.com我人生的甘雨EP32.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3443/飘花电影piaohua.com我人生的甘雨EP33.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3443/飘花电影piaohua.com我人生的甘雨EP33.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3454/飘花电影piaohua.com我人生的甘雨EP34.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3454/飘花电影piaohua.com我人生的甘雨EP34.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3470/飘花电影piaohua.com我人生的甘雨EP35.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3470/飘花电影piaohua.com我人生的甘雨EP35.rmvb</a></td>
		</tr>
	</tbody>
</table>
<p>
	&nbsp;</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1AE240-160A.jpg{/dede:field}
