{dede:field name='keywords'}曾几何时/爱情我做主BD中字1280{/dede:field}
{dede:field name='description'}曾几何时/爱情我做主BD中字1280高清2011喜剧迅雷下载、免费下载，曾几何时/爱情我做主BD中字1280高清2011喜剧Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}曾几何时/爱情我做主BD中字1280高清2011喜剧{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-04-29{/dede:field}
{dede:field name='body'}<p>
	<img alt="" border="0" height="927" src="http://www.videowithlyrics.com/wp-content/uploads/Always-Kabhi-Kabhi.jpg" width="600" /></p>
<p>
	◎译　　名　曾几何时/爱情我做主<br />
	◎片　　名　Always Kabhi Kabhi<br />
	◎年　　代　2011<br />
	◎国　　家　印度<br />
	◎类　　别　喜剧/犯罪/剧情/爱情<br />
	◎语　　言　北印度语<br />
	◎字　　幕　中英双字<br />
	◎IMDB评分 4.9/10 (77 votes)<br />
	◎文件格式　XviD + MP3<br />
	◎视频尺寸　640 x 272<br />
	◎文件大小　1CD<br />
	◎片　　长　127 Mins<br />
	◎导　　演　Roshan Abbas<br />
	◎主　　演　Lillete Dubey ... Ms. Das<br />
	　　　　　　Satyajeet Dubey ... Tariq Naqvi<br />
	　　　　　　Ali Fazal ... Sameer A. Khanna / Sammy<br />
	　　　　　　Manoj Joshi ... Police Inspector<br />
	　　　　　　Shah Rukh Khan ... Dancer / Singer<br />
	　　　　　　Akash Khurana ... Principal Elton Phillips<br />
	　　　　　　Giselli Monteiro ... Aishwarya Dhawan<br />
	　　　　　　Zoa Morani ... Nandini Oberoi<br />
	　　　　　　Ashwin Mushran ... Rahul Ghosh<br />
	　　　　　　Navneet Nishan ... Mrs. Dhawan<br />
	　　　　　　Vijay Raaz ... Professor Agarwal urf Agro<br />
	　　　　　　Satish Shah ... Agent<br />
	　　　　　　Mukesh Tiwari ... Police Inspector<br />
	　　　　　　</p>
<p>
	<br />
	◎简　　介　</p>
<p>
	本片讲述的是四个高中生如何渡过他们在圣马克思学校的最后一学期，萨米尔，一个酷男孩，爱上了即将成为宝莱坞女星的艾西瓦娅，艾西瓦娅是新来的学生，第一天就帮助了萨米尔。两人一见钟情。学校的莎士比亚戏剧，艾西瓦娅自然而然的获得了朱丽叶的角色。萨米尔努力背诵罗密欧的台词，试图打动达斯女士从而获得罗密欧的角色，最后成功了。另外两个朋友塔里格和南迪尼总喜欢互相打架，争吵。但他们却没有发现彼此爱着对方。四个朋友对各自的家庭都有心结。南迪尼的父母总是外出，从不待在她的身边，因此她每天去非法俱乐部，花钱如流水。塔里格背负着父亲的期望，上麻省理工大学。萨米尔因为警察勒索而偷了家里的钱。但父亲却不愿听任何解释。艾西瓦娅并不想当明星。他们要如何告诉自己的父母自己真实的想法，做回真实的自己呢。&nbsp;</p>
<p>
	<img alt="" height="393" src="http://img170.poco.cn/mypoco/myphoto/20120428/18/56643687201204281837482945735806490_001.jpg" width="700" /></p>
<p>
	<img alt="" height="393" src="http://img170.poco.cn/mypoco/myphoto/20120428/18/56643687201204281837482945735806490_000.jpg" width="700" /></p>
<p>
	[下载地址]： <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" /></p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="word-break: break-all; line-height: 18px" width="100%">
				&nbsp;<a href="ftp://dy44:piaohua@dy44.piaohua.com:2089/飘花电影piaohua.com爱情我做主DVD中英双字.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2089/飘花电影piaohua.com爱情我做主DVD中英双字.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="word-break: break-all; line-height: 18px" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3316/飘花电影piaohua.com爱情我做主BD中字1280高清.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3316/飘花电影piaohua.com爱情我做主BD中字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15GT30-23436.jpg{/dede:field}
