{dede:field name='keywords'}探索频道解码世界末日[HD中字102{/dede:field}
{dede:field name='description'}探索频道解码世界末日[HD中字1024x576高清版]迅雷下载、免费下载，探索频道解码世界末日[HD中字1024x576高清版]Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}探索频道解码世界末日[HD中字1024x576高清版]{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-03-17{/dede:field}
{dede:field name='body'}<p>
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('/uploads/allimg/c120525/133O0b3X40-164195.jpg');" src="/uploads/allimg/c120525/133O0b3X40-164195.jpg" /><br />
	<br />
	【中 文 名】探索频道解码世界末日2012<br />
	【国　　家】美国<br />
	【类　　别】纪录片<br />
	【片　　长】45分钟<br />
	【语　　言】英语<br />
	【字　　幕】中字<br />
	【分 辨 率】1024x576<br />
	【内容简介】<br />
	<br />
	&nbsp; &nbsp; 世界各地的预言家们似乎都有一个共同的预言：2012年12月21日将是世界末日。来自古玛雅的历法，中世纪的预言，以及中国的易经都指出这个日子是文明的终结日。一种叫做&quot;Web-Bot Project&quot;新计算机技术也预示了这个可怕的日子.....<br />
	<br />
	&nbsp; &nbsp; 虽然有怀疑者电影指出历史上有许多所谓的&ldquo;世界末日&rdquo;并未发生，但历史上的确有许多预言成功的预告了许多大事件的发生。随着2012年的临近，我们是否有理由相信这些预言者们的话呢...<br />
	<br />
	There are prophecies and oracles from around the world that all seem to point to December 21, 2012 as doomsday. The ancient Mayan Calendar, the medieval predictions of Merlin, the Book of Revelation and the Chinese oracle of the I Ching all point to this specific date as the end of civilization. A new technology called &quot;The Web-Bot Project&quot; makes massive scans of the internet as a means of forecasting the future... and has turned up the same dreaded date: 2012. Skeptics point to a long history of &quot;Failed Doomsdays&quot;, but many oracles of doom throughout history have a disturbingly accurate track record. As the year 2012 ticks ever closer we&#39;ll speculate if there are any reasons to believe these doomsayers.</p>
<p>
	【电影截图】：<br />
	<br />
	<img border="0" src="/uploads/allimg/c120525/133O0b39630-1N327.jpg" />&nbsp;<br />
	<img border="0" src="/uploads/allimg/c120525/133O0b40240-1Y5b.jpg" /></p>
<br />
<p>
	[下载地址]：<img border="0" src="http://www.eee4.com/templets/img/down.jpg" /></p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				ftp://3e:3e@www2.eee4.com:923/[3E电影站www.eee4.cn]探索频道解码世界末日2012.rmvb</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O0b45Z-202426.jpg{/dede:field}
