<?php
$z[0]=Array("field","赌神3之少年赌神[HD中字1024x576",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","赌神3之少年赌神[HD中字1024x576高清版]迅雷下载、免费下载，赌神3之少年赌神[HD中字1024x576高清版]Gvod高清在线播放，剧情介绍等。",73,241);
$z[1][4]['name']="description";
$z[2]=Array("field","赌神3之少年赌神[HD中字1024x576高清版]",243,318);
$z[2][4]['name']="title";
$z[3]=Array("field","",320,359);
$z[3][4]['name']="writer";
$z[4]=Array("field","",361,400);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-05-13",402,452);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",454,491);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://4e:4e@d8.3edyy.com:157/【3E电影院www.eee4.cc】赌神3之少年赌神HD中字1024x576高清版.rmvb\" target=\"_blank",493,640);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MQ343260-5C32.jpg",642,725);
$z[8][4]['name']="litpic";

?>