<?php
$z[0]=Array("field","牧人的性玩偶高清720P,1280*720",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","牧人的性玩偶高清720P 1280*720迅雷下载、免费下载，牧人的性玩偶高清720P 1280*720Gvod高清在线播放，剧情介绍等。",72,224);
$z[1][4]['name']="description";
$z[2]=Array("field","牧人的性玩偶高清720P 1280*720",226,293);
$z[2][4]['name']="title";
$z[3]=Array("field","",295,334);
$z[3][4]['name']="writer";
$z[4]=Array("field","",336,375);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-07-30",377,427);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",429,466);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://dy125:piaohua@dy125.piaohua.com:1031/飘花电影下载站www.piaohua.com牧人的性玩偶720p.mkv",468,599);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MP3J540-4E49.jpg",601,683);
$z[8][4]['name']="litpic";

?>