{dede:field name='keywords'}廉政英雄更新第35集2011台湾电视{/dede:field}
{dede:field name='description'}廉政英雄更新第35集2011台湾电视剧迅雷下载、免费下载，廉政英雄更新第35集2011台湾电视剧Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}廉政英雄更新第35集2011台湾电视剧{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-19{/dede:field}
{dede:field name='body'}<p>
	<img alt="" border="0" height="629" src="http://img.album.pchome.net/02/25/03/37/996de81bcb03fb08781a957819d7f005.jpg" style="width: 593px; height: 419px" width="712" /></p>
<p>
	中文名： 廉政英雄<br />
	外文名： Independent Heroes<br />
	其它译名： 廉政先锋<br />
	出品时间： 2011年7月21日<br />
	制片地区： 中国台湾<br />
	导演： 孙树培<br />
	主演： 李政颖、姚元浩、周孝安、江祖平、刘香慈、尹崇珍<br />
	集数： 未知<br />
	类型： 爱情，警匪<br />
	上映时间： 2011年9月23日<br />
	语言： 国语<br />
	制作人： 郝孝祖<br />
	制作公司 ： 民间全民电视公司<br />
	接档： 新兵日记之特战英雄<br />
	首播频道： 民视无线台 </p>
<p>
	<br />
	&nbsp;&nbsp;&nbsp; 　《廉政英雄》，是2011年台湾电视剧，由民视与法务部共同合作制作。该剧由《包青天》《还珠格格》第一，二部的导演孙树培掌镜， 李政颖、江祖平、姚元浩、刘香慈、周孝安与尹崇珍主演。于2011年6月28日举行开镜仪式，7月初正式开拍，将接档《新兵日记之特战英雄》播出 (民视周五10点档，每周一集)。 　　《廉政英雄》剧每集制作费高达200万，采用单元剧方式制作，以主要演员贯穿全剧，并配合单元将加入许多重量级演员演出。而剧中预计会将当年震惊社会的白晓燕命案搬上台面。 　　《廉政英雄》叙述警匪对峙的情节，该剧以检察官侦破社会重大案件的经过为主。法务部目前已搜集67个案件、27个检察官故事，其中有多个曾轰动一时的真实重大刑案。 　　民视节目部经理赵善意说，故事具社会教化意义，爱情元素也不会少，传达每个人都需要将心比心及尊重别人。他表示，《廉政英雄》比《新兵日记》拍摄难度更高，尤其是追逐、爆破、枪战场面都需要专业和相关配合，例如枪战戏的原则是，开枪、枪枝、被打伤的人不能特写入镜，大场面戏得拍得乱中有序，考验导演调度实力。他说，观众看惯好莱坞片，但看到最后往往仅是用钱砸出来的特效而已，台湾的警匪剧用情感堆砌。 　　「廉」剧6月28日正式开镜，首集单元选择在高雄取景，对於角色设定被联想到「痞子英雄」，赵善意说：「绝对不一样，我们会走出自己的路。」「廉」剧这回和法务部合作，首集将以中南部「飙车」议题为主，赵善意说：「我们将用电影手法呈现出豪华感，会出动重型机车追逐、直升机空拍。」民视初估该集预算将破千万。</p>
<p>
	[下载地址]： &nbsp;<img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" /></p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:1770/飘花电影piaohua.com廉政英雄-01.rmvb ">ftp://dy44:piaohua@dy44.piaohua.com:1770/飘花电影piaohua.com廉政英雄-01.rmvb </a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:1770/飘花电影piaohua.com廉政英雄-02.rmvb ">ftp://dy44:piaohua@dy44.piaohua.com:1770/飘花电影piaohua.com廉政英雄-02.rmvb </a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:1770/飘花电影piaohua.com廉政英雄-03.rmvb ">ftp://dy44:piaohua@dy44.piaohua.com:1770/飘花电影piaohua.com廉政英雄-03.rmvb </a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:1824/飘花电影piaohua.com廉政英雄-04.rmvb ">ftp://dy44:piaohua@dy44.piaohua.com:1824/飘花电影piaohua.com廉政英雄-04.rmvb </a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:1885/飘花电影piaohua.com廉政英雄-05.rmvb ">ftp://dy44:piaohua@dy44.piaohua.com:1885/飘花电影piaohua.com廉政英雄-05.rmvb </a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:1949/飘花电影piaohua.com廉政英雄-06.rmvb ">ftp://dy44:piaohua@dy44.piaohua.com:1949/飘花电影piaohua.com廉政英雄-06.rmvb </a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2003/飘花电影piaohua.com廉政英雄-07.rmvb ">ftp://dy44:piaohua@dy44.piaohua.com:2003/飘花电影piaohua.com廉政英雄-07.rmvb </a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2074/飘花电影piaohua.com廉政英雄-08.rmvb ">ftp://dy44:piaohua@dy44.piaohua.com:2074/飘花电影piaohua.com廉政英雄-08.rmvb </a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2322/飘花电影piaohua.com廉政英雄-09.rmvb ">ftp://dy44:piaohua@dy44.piaohua.com:2322/飘花电影piaohua.com廉政英雄-09.rmvb </a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2182/飘花电影piaohua.com廉政英雄-10.rmvb ">ftp://dy44:piaohua@dy44.piaohua.com:2182/飘花电影piaohua.com廉政英雄-10.rmvb </a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2241/飘花电影piaohua.com廉政英雄-11.rmvb ">ftp://dy44:piaohua@dy44.piaohua.com:2241/飘花电影piaohua.com廉政英雄-11.rmvb </a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2302/飘花电影piaohua.com廉政英雄-12.rmvb ">ftp://dy44:piaohua@dy44.piaohua.com:2302/飘花电影piaohua.com廉政英雄-12.rmvb </a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2356/飘花电影piaohua.com廉政英雄-13.rmvb ">ftp://dy44:piaohua@dy44.piaohua.com:2356/飘花电影piaohua.com廉政英雄-13.rmvb </a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2429/飘花电影piaohua.com廉政英雄-14.rmvb ">ftp://dy44:piaohua@dy44.piaohua.com:2429/飘花电影piaohua.com廉政英雄-14.rmvb </a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2484/飘花电影piaohua.com廉政英雄-15.rmvb ">ftp://dy44:piaohua@dy44.piaohua.com:2484/飘花电影piaohua.com廉政英雄-15.rmvb </a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2534/飘花电影piaohua.com廉政英雄-16.rmvb ">ftp://dy44:piaohua@dy44.piaohua.com:2534/飘花电影piaohua.com廉政英雄-16.rmvb </a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2617/飘花电影piaohua.com廉政英雄-17.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2617/飘花电影piaohua.com廉政英雄-17.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2679/飘花电影piaohua.com廉政英雄-18.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2679/飘花电影piaohua.com廉政英雄-18.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2746/飘花电影piaohua.com廉政英雄-19.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2746/飘花电影piaohua.com廉政英雄-19.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2746/飘花电影piaohua.com廉政英雄-20.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2746/飘花电影piaohua.com廉政英雄-20.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2795/飘花电影piaohua.com廉政英雄-21.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2795/飘花电影piaohua.com廉政英雄-21.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2840/飘花电影piaohua.com廉政英雄-22.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2840/飘花电影piaohua.com廉政英雄-22.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3141/飘花电影piaohua.com廉政英雄-23.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3141/飘花电影piaohua.com廉政英雄-23.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2941/飘花电影piaohua.com廉政英雄-24.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2941/飘花电影piaohua.com廉政英雄-24.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:2990/飘花电影piaohua.com廉政英雄-25.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:2990/飘花电影piaohua.com廉政英雄-25.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3027/飘花电影piaohua.com廉政英雄-26.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3027/飘花电影piaohua.com廉政英雄-26.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3063/飘花电影piaohua.com廉政英雄-27.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3063/飘花电影piaohua.com廉政英雄-27.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3141/飘花电影piaohua.com廉政英雄-28.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3141/飘花电影piaohua.com廉政英雄-28.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3191/飘花电影piaohua.com廉政英雄-29.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3191/飘花电影piaohua.com廉政英雄-29.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3221/飘花电影piaohua.com廉政英雄-30.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3221/飘花电影piaohua.com廉政英雄-30.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3264/飘花电影piaohua.com廉政英雄-31.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3264/飘花电影piaohua.com廉政英雄-31.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3310/飘花电影piaohua.com廉政英雄-32.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3310/飘花电影piaohua.com廉政英雄-32.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3354/飘花电影piaohua.com廉政英雄-33.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3354/飘花电影piaohua.com廉政英雄-33.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3404/飘花电影piaohua.com廉政英雄-34.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3404/飘花电影piaohua.com廉政英雄-34.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3456/飘花电影piaohua.com廉政英雄-35.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3456/飘花电影piaohua.com廉政英雄-35.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1A5E50-25645.jpg{/dede:field}
