<?php
$z[0]=Array("field","圣斗士星矢剧场版1,:,邪神爱丽丝",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","圣斗士星矢剧场版1 : 邪神爱丽丝HD国语中字1280高清迅雷下载、免费下载，圣斗士星矢剧场版1 : 邪神爱丽丝HD国语中字1280高清Gvod高清在线播放，剧情介绍等。",73,263);
$z[1][4]['name']="description";
$z[2]=Array("field","圣斗士星矢剧场版1 : 邪神爱丽丝HD国语中字1280高清",265,351);
$z[2][4]['name']="title";
$z[3]=Array("field","",353,392);
$z[3][4]['name']="writer";
$z[4]=Array("field","",394,433);
$z[4][4]['name']="source";
$z[5]=Array("field","2012-01-08",435,485);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",487,524);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://dy44:piaohua@dy44.piaohua.com:2547/飘花电影piaohua.com圣斗士星矢剧场版1邪神爱丽丝HD国语中字1280高清.rmvb",526,675);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MQ0SG0-4T94.jpg",677,758);
$z[8][4]['name']="litpic";

?>