{dede:field name='keywords'}麦兜响当当【BD中字1280x720高清{/dede:field}
{dede:field name='description'}麦兜响当当【BD中字1280x720高清版[粤语＋国语]】迅雷下载、免费下载，麦兜响当当【BD中字1280x720高清版[粤语＋国语]】Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}麦兜响当当【BD中字1280x720高清版[粤语＋国语]】{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-08-26{/dede:field}
{dede:field name='body'}<p>
	<img alt="" border="0" onclick="if(this.width&gt;screen.width-461) window.open('/uploads/allimg/c120525/133O04F4050-1X29.jpg');" src="/uploads/allimg/c120525/133O04F4050-1X29.jpg" />&nbsp;</p>
<p>
	<br />
	◎译　　名　《麦兜响当当》09最新国产喜剧动画大片BD中字1280x720高清版[粤语＋国语]<br />
	◎片　　名　McDull Kung Fu Kindergarten<br />
	◎年　　代　2009<br />
	◎国　　家　中国/日本<br />
	◎类　　别　动画/喜剧<br />
	◎语　　言　普通话&nbsp;/ 粤语<br />
	◎字　　幕　简体中文<br />
	◎IMDB评分 6.6/10 (44 votes)<br />
	◎文件格式　Rmvb<br />
	◎视频尺寸　1280 x 720 1024 x 576<br />
	◎文件大小　1CD 784MB<br />
	◎片　　长　77 Mins<br />
	◎导　　演　谢立文 Brian Tse<br />
	<br />
	◎粤语配音　吴君如 Sandra Ng<br />
	　　　　　　黄秋生 Anthony Wong<br />
	　　　　　　尹光 Gwong Wan<br />
	　　　　　　詹瑞文 Sui-man Chim<br />
	　　　　　　<br />
	◎国语配音　黄渤<br />
	　　　　　　宋丹丹<br />
	　　　　　　邵夷贝<br />
	<br />
	◎简　　介　<br />
	<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&ldquo;麦兜麦兜响当当&rdquo;集结了两岸三地明星为其配音。粤语版中，香港影帝黄秋生将再度为校长扮演的道长配音、喜剧女王吴君如这回依旧当着她最爱扮演的&ldquo;麦太&rdquo;。而在国语版中，&ldquo;疯狂的明星&rdquo;黄渤将用其独特的搞笑方式讲述麦兜的故事，&ldquo;活力母亲&rdquo;宋丹丹首度尝试为着生活努力打拼，并且要照顾儿子麦兜的坚强女人麦太， &ldquo;蓝天幼儿园乐队&rdquo;主唱，著有《大龄文艺女青年之歌》的民谣歌手邵夷贝将自己的配音处女作也奉献给了《麦兜响当当》中的道姐，同时她亲自为影片编写了主题曲《麦兜兜响当当》。<br />
	<br />
	　　《麦兜响当当》作为麦兜系列动画电影第四部，依旧秉承着其一贯的温情、无厘头的搞笑风格，快乐中带着淡淡的忧伤。故事从麦兜灰色的幸福开始讲述&mdash;&mdash;暑假，当小朋友都到新西兰滑雪、到北京大学学普通话、到剑桥学英文的时候，家境贫寒的麦兜因为妈妈北上武汉做食肆生意，只好被送上武当山学习太极拳。武当山上没有电视、没有空调，在孤单的夜晚里，麦兜忍不住寂寞，常常独自落泪。但他仍然坚持勤学苦练，终于以一套又闷又慢的太极拳参加&ldquo;打遍天下无敌手世界幼儿园武术大赛&rdquo;，与李小麟（不知道为什么不用小龙的名字）、袁和平等人的弟子对擂&hellip;&hellip;该片较前三部影片，融入了更多纯正的港式幽默，慢性子的麦兜耍功夫，更是令人值得期待。<br />
	<br />
	　　整个故事围绕着麦兜的习武经历展开。&ldquo;世界幼儿园武术大赛&rdquo;即将举行，&rdquo;太乙春花门&ldquo;小朋友软手软脚，看来只有挨揍的份儿。同时，道长发现祖传炼丹炉竟有方便面碎片，震怒之下，重罚麦兜。小同学四散，麦兜也偷偷下山打电话，希望麦太把他接走。山下，麦兜无意间得知道长的一段往事&mdash;&mdash;年轻时道长曾跟电影下载国际武术巨星李小麟相约罗湖大战！决战后，道长闭关苦思，终于明白要把太极拳革新的重要，同时把这一重任寄托在新生的一代。原来一直鼓励着麦兜的熊宝弟弟，竟是道长扮的！麦兜的之后，大为感动，决定回到山上，好好跟道长学习推手。<br />
	<br />
	　　&ldquo;世界幼儿园武术大赛&rdquo;，麦兜迎战各地好打小朋友。这是，麦兜子总麦仲肥的巨物突然当当当的响起。原来是一个一年等于一秒，每三千六百年才报一次时的大钟。大成若缺，大器晚成。麦兜忽然悟出太极拳，以至自己生命的道理。<br />
	当然，尽管悟到了，但是&hellip;&hellip;<br />
	<br />
	　　&ldquo;麦兜&rdquo;之父，《麦兜响当当》导演兼编剧谢立文介绍说，自2006年推出的《春田花花同学会》之后，麦兜就一直没有很大的动作。这次推出《麦兜响当当》，可以说是在人们的无数期待中孕育而生的，历经两年时间，几易其稿。与以往几部不同的是，《麦兜响当当》高清电影下载让麦兜走出了香港，同时更升华了麦兜的 &ldquo;草根精神&rdquo;。谢立文透露，这次让慢性子的麦兜上武当打太极，里面是有故事的。麦兜其实很有太极天赋，他的祖宗麦子仲肥是一个发明家，曾经发明过一个超慢的钟。当麦兜赴战的一刻，这只古钟忽然发出当当巨响，而麦兜猛然一醒，似乎已掌握了太极的奥妙。谢立文希望，观众看《麦兜响当当》时能从头笑到尾，虽然这个故事有苦有泪。<br />
	<br />
	　　　&ldquo;麦兜&rdquo;诞生20多年来，无论是漫画，还是电视、电影，一直秉承着自己的创作理念，走着一条属于麦兜自己的&ldquo;人生道路&rdquo;。从《麦兜故事》、《麦兜菠萝油王子》，到真人加动画的《春田花花同学会》，麦兜以其独特的&ldquo;麦氏幽默&rdquo;，培育了一大批超级&ldquo;麦粉&rdquo;，遍布全球，这只粉嘟嘟的小猪着实令人钟情有加，无限期待。</p>
<p>
	【电影截图】：<br />
	<br />
	<img src="/uploads/allimg/c120525/133O04F5920-23008.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 338px; border-top: 0px solid; border-right: 0px solid" />&nbsp;<br />
	<img src="/uploads/allimg/c120525/133O04FB0-332S.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 338px; border-top: 0px solid; border-right: 0px solid" />&nbsp;<br />
	<img src="/uploads/allimg/c120525/133O04FI0-44126.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 338px; border-top: 0px solid; border-right: 0px solid" />&nbsp;<br />
	<img src="/uploads/allimg/c120525/133O04FP-54M2.jpg" style="border-bottom: 0px solid; border-left: 0px solid; width: 600px; height: 338px; border-top: 0px solid; border-right: 0px solid" /></p>
<p>
	[下载地址]：
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				ftp://3e:3e@www2.eee4.com:781/[3E电影站www.eee4.cn]麦兜响当当BD中字1280x720高清版[国语].rmvb</td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				ftp://3e:3e@www2.eee4.com:781/[3E电影站www.eee4.cn]麦兜响当当BD中字1280x720高清版[粤语].rmvb</td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				ftp://dy44:piaohua@dy44.piaohua.com:1401/飘花电影piaohua.com麦兜响当当1024高清.rmvb</td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O04FVF-BB2.jpg{/dede:field}
