{dede:field name='keywords'}刀的哲学DVDRip无字剧情记录片迅{/dede:field}
{dede:field name='description'}刀的哲学DVDRip无字剧情记录片迅雷下载、免费下载，刀的哲学DVDRip无字剧情记录片Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}刀的哲学DVDRip无字剧情记录片{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-07-13{/dede:field}
{dede:field name='body'}<p>
	<img border="0" onclick="if(this.parentNode.tagName!='A'&amp;&amp;this.width&gt;=750) window.open('http://www.ys3344.com/files/post/20110326230007244.jpg');" onload="if(this.offsetWidth&gt;'750')this.width='750';" src="http://www.ys3344.com/files/post/20110326230007244.jpg" /></p>
<p>
	导演及影片简介：</p>
<p>
	20世纪上半叶，战争的阴影笼罩全球，久久不退。生命的价值日渐低微，众生被迫成为利益集团的牺牲品与实验品。东亚一隅，明治维新后的日本不断壮大，其向外扩张的野心也不断膨胀。数次对俄战争的胜利，让这个民族变得愈发狂热。然而随着战争规模的扩大，资源短缺成为了限制日军继续扩张的首要难题。时德、苏等国的科学家不断开发生化武器，陆军中将石井四郎相风而动，提议建立生化部队，这便是日后臭名昭著的满洲731部队。在抗日战争期间，这支魔鬼部队对战俘、当地百姓进行了无数灭绝人性的实验，时至今日，鬼魂的哀号仍在满洲上空久久回荡&hellip;&hellip;</p>
<p>
	　　本片采取剧情和记录的手法制作，素材来自前苏联军事翻译人员Anatoliy Protasov。该片发行前夕曾受俄国联邦安全局调查。</p>
<p>
	Andrey Iskanov，俄罗斯新晋导演，来自于远东地区Khabarovsk市。2007年，Andrey拍摄出超现实电影Philosophy of a knife，电影以日本关东军驻满洲731部队在当地的一系列*****为背景，以黑白基调大量描写*****的细节，比起日本80年代的豚鼠系列实验派电影集有过之而无不及。影片对于*****描写过于细致，片中的场景比起当年发生的只会还要血腥，还要恐怖。</p>
<p>
	<br />
	电影是关于日本731部队的*****的 比黑太阳731还要着真实得多!!!!!</p>
<p>
	<br />
	刀的哲学<br />
	导演 Director：<br />
	Andrey Iskanov<br />
	编剧 Writer：<br />
	Andrey Iskanov<br />
	演员 Actor：<br />
	Andrey Iskanov .....The amputation surgeon<br />
	Manoush .....Japanese nurse (voice)<br />
	Victor Ludchenko .....The decompression experiment man<br />
	Irina Nikitina .....The pregnant girl<br />
	Victor Silkin .....The old surgeon<br />
	Svyatoslav Iliyasov .....The male nurse<br />
	Irina Zenkina .....The syphilis experiment girl<br />
	Artem Seleznyov .....The frostbite experiment man<br />
	Stephen Tipton .....Historical commentary (voice)<br />
	Yukari Fujimoto .....The female nurse #1<br />
	Dmitriy Skripnik .....The captured airplane pilot<br />
	Tatyana Kopeykina .....The blond girl with toy bear<br />
	Vladimir Kucherenko .....The radioactivity experiment man<br />
	Tetsuro Sakagami .....The officer #1<br />
	Anna Subbotina .....The insect experiment girl<br />
	Alyona Strebkova .....The dental torture girl<br />
	Masaki Kitagava .....The female nurse #3<br />
	Yumiko Fujiwara .....The female nurse #2<br />
	Veronika Leonova .....The brunette girl<br />
	Tomoya Okamoto .....The officer #2<br />
	Reiko Niakawa .....The female nurse #4<br />
	Elena Probatova .....The favorite girl<br />
	Anatoly Protasov .....Himself<br />
	制作人 Produced by：<br />
	Steven Biro .....producer: Unearthed Films<br />
	Andrey Iskanov .....producer<br />
	原创音乐 Original Music：<br />
	Alexander Shevchenko<br />
	摄影 Cinematography：<br />
	Andrey Iskanov<br />
	剪辑 Film Editing：<br />
	Andrey Iskanov<br />
	艺术指导 Production Designer：<br />
	Andrey Iskanov</p>
<p>
	<img src="file:///C:/Documents%20and%20Settings/Administrator/Local%20Settings/Temporary%20Internet%20Files/Content.IE5/7JVBDIMU/35a8dae0e99b07f917574c76accfccde[1].jpg" /></p>
<p>
	[下载地址]： &nbsp;<img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" /></p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy445:piaohua@dy445.piaohua.com:504/飘花电影piaohua.com刀的哲学DVDRip无字CD1.avi">ftp://dy445:piaohua@dy445.piaohua.com:504/飘花电影piaohua.com刀的哲学DVDRip无字CD1.avi</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy445:piaohua@dy445.piaohua.com:504/飘花电影piaohua.com刀的哲学DVDRip无字CD2.avi">ftp://dy445:piaohua@dy445.piaohua.com:504/飘花电影piaohua.com刀的哲学DVDRip无字CD2.avi</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1BR1P-4E18.jpg{/dede:field}
