{dede:field name='keywords'}智人迅雷下载，免费下载，Gvod高{/dede:field}
{dede:field name='description'}智人迅雷下载、免费下载，智人Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}智人{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2008-03-19{/dede:field}
{dede:field name='body'}<P>【中文译名】《智人》轰动经典/不可错过DVD中字<BR>【片　　名】Homo Sapiens<BR>【年　　代】2005<BR>【国　　家】法国<BR>【类　　别】记录/历史<BR>【语　　言】法语<BR>【字　　幕】中文<BR>【IMDB评分】8.2/10 (42 votes)<BR>【视频尺寸】640 x 352<BR>【电影整理】3E迅雷电影下载站(www.eee4.com)<BR>【文件大小】2CD 376MB<BR>【片　　长】94 Min</P>
<P><BR>【剧情简介】：</P>
<P>　　四十万年以前，一个非凡的种群加入到了这个世界，他们是智人，我们的祖先。他们翻山越岭，不断改变自己以适应环境的每一处细微变化。一次又一次地他们失去了一切，然而他们总是可以超越自己的极限并最终幸存下来。他们学会了种植农作物、驯化动物，修建村庄，改善环境，人类成为动物王国中最强大的种群，他们在想象的世界中遨游，并在这个过程中发现了美术和梦幻的能力。但种群又是怎样出现的，从哪里来的呢？</P>
<P>　　八百万年以前，这个星球突然变冷，水被冻结在地球两极，巨大的冰盖覆盖了整个欧亚大陆。在北方生命必需开始适应寒冷。热带地区，生命要和干旱进行绝望的斗争。而在非洲大陆人类发现他们的森林正在逐渐消失。他们中的奥瑞恩和图梅逐渐适应了大草原的生活，并学会了直立行走。四百万年前，他们消失了，进化成一种更具适应性的新族群——南方古猿。他们的后代继续直立行走，并靠着食用耐寒的植物生存了下来，但最终他们还是灭绝了，他们无法抵抗强大的肉食动物。</P>
<P>　　接下来出场的是哈比利斯人，事实上这个灵巧的人种才可以称得上真正意义上的人类代表。他们学会了使用工具，并开始了对整个地球的探索，他们发展成了一个新的人种——直立人。这些会站着的人发现了火，他们完成了一个伟大的飞跃，直立人开始了他们征服世界的旅途。他们离开非洲，来到了欧亚大陆。在不知不觉中，一小部分男人和女人已经为现代人的形成做好了准备。而此时，生存了一百多万年的直立人也逐渐地消失了。</P>
<P>　　类现代人的时代到来了，经历了上百万年，他们的身体逐渐苗条，前额变平，大脑容量逐渐变大，结构逐渐复杂。而类现代人的探索也来到了中东地区，他们开始穿衣服，进化成新的人种。智人发现了亚洲大陆，在迁徙途中，他们的外貌有了很大变化，并与直立人融合，组成了亚洲人。一万两千年前，全球温度开始升高，各个大陆逐渐呈现现在看到的情况，类现代人开始定居生活。他们学会饲养家畜，史前文明结束了。</P>
<P><BR>　　【精彩视点】：</P>
<P>　　《智人》是2003年法国第三电视台播出的电影《人类进化史》的第二部曲，本剧在2005年1月首播立即创下了极高的收视率。超过九百万的法国人都守在电视前面观赏这部巨作，创下法国电视史上最高的收视率。随后发行的原声带和DVD更是造成轰动，单单法国一地便狂卖了数十万张。<BR>　　《智人》是导演雅克·马拉特继《人类进化史》之后，再次用镜头记录人类世界的发展过程的经典之作。影片的拍摄周期长达13个月，素材影像超过120个小时。而在这之前，导演雅克·马拉特用了几年的时间进行筹备，了解有关人类发展的专业知识。据介绍，智人是人类演化过程中最重要的一个阶段之一。影片《智人》用搬演的方法，记录了人类在演化过程中必须面对的许多艰难与危险。运用旁白的方式，片中由智人其中一员“开口”介绍他们的生活，也使观众接近智人的生活，为风雪中找不到避难所就冻死的部落成员而难过；会为失去了自己爱人的部落女孩悉心照顾他人之子的做法而动容。电影整理：(www.eee4.com)</P>
<P><IMG src="http://pic.piaohua.com/0701pic/allimg/080319/0614440.jpg" border=0></P>
<P>【电影截图】：<BR>电影来源：www.eee4.com<BR><IMG src="http://pic.piaohua.com/0701pic/allimg/080319/0615060.jpg" border=0><BR><IMG src="http://pic.piaohua.com/0701pic/allimg/080319/0615460.jpg" border=0><BR><IMG src="http://pic.piaohua.com/0701pic/allimg/080319/0615301.jpg" border=0><BR><IMG src="http://pic.piaohua.com/0701pic/allimg/080319/0615102.jpg" border=0></P>
<P>2008-03-19 05:25:12 开始连接......<BR>2008-03-19 05:25:14 开始搜索候选资源......<BR>2008-03-19 05:25:15 搜索到19个候选资源<BR>2008-03-19 05:25:17 使用候选资源进行连接......<BR>2008-03-19 05:25:20 搜索到29个候选资源<BR>2008-03-19 05:25:23 使用候选资源进行连接......<BR>2008-03-19 05:25:24 文件创建成功，开始下载数据......<BR>2008-03-19 05:25:26 用户取消下载&nbsp;&nbsp; 本文来自 <A href="/index.html" target=_blank>www.eee4.com</A></P>（直接可能无法下载，一律使用<A href="http://pstatic.xunlei.com/about/product/down_xl5.htm" target=_blank>迅雷下载</A>）<BR>轰动经典/不可错过《智人》DVD中字 － 来自[3E迅雷电影站eee4.com]下载地址：<IMG src="/templets/img/down.jpg" border=0><BR>CD1：<BR>
<TABLE style="BORDER-RIGHT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; BORDER-BOTTOM: #cccccc 1px dotted" cellSpacing=0 cellPadding=6 width="95%" align=center border=0>
<TBODY>
<TR>
<TD style="WORD-WRAP: break-word" bgColor=#fdfddf><ANCHOR></ANCHOR><A href="ftp://eee4.com:8055@vip12.eee4.com:8055/智人/[3E迅雷电影站www.eee4.com]智人CD1.rmvb" target=_blank>ftp://eee4.com:8055@vip12.eee4.com:8055/智人/[3E迅雷电影站www.eee4.com]智人CD1.rmvb</A></TD></TR></TBODY></TABLE>CD2：<BR>
<TABLE style="BORDER-RIGHT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; BORDER-BOTTOM: #cccccc 1px dotted" cellSpacing=0 cellPadding=6 width="95%" align=center border=0>
<TBODY>
<TR>
<TD style="WORD-WRAP: break-word" bgColor=#fdfddf><ANCHOR></ANCHOR><A href="ftp://eee4.com:8055@vip12.eee4.com:8055/智人/[3E迅雷电影站www.eee4.com]智人CD2.rmvb" target=_blank>ftp://eee4.com:8055@vip12.eee4.com:8055/智人/[3E迅雷电影站www.eee4.com]智人CD2.rmvb</A></TD></TR></TBODY></TABLE>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O161314P-51W2.jpg{/dede:field}
