{dede:field name='keywords'}韩国舞王Rain和舞后李孝利性感热{/dede:field}
{dede:field name='description'}韩国舞王Rain和舞后李孝利性感热舞迅雷下载、免费下载，韩国舞王Rain和舞后李孝利性感热舞Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}韩国舞王Rain和舞后李孝利性感热舞{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2006-08-04{/dede:field}
{dede:field name='body'}<P>播放后双击视频“全屏”</P> 
<object classid="CLSID:22d6f312-b0f6-11d0-94ab-0080c74c7e95" class="OBJECT" id="MediaPlayer" width="500" height="350" ><param name="ShowStatusBar" value="-1"><param name="Filename" value="http://www.5830.com/mv1/fm214.com_rain-leehyori_dance.asf"></embed></object><br /> 
<P>下载地址<BR></P> <br>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120524/133N353DD0-2G248.gif{/dede:field}
