<?php
$z[0]=Array("field","韩国舞王Rain和舞后李孝利性感热",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","韩国舞王Rain和舞后李孝利性感热舞迅雷下载、免费下载，韩国舞王Rain和舞后李孝利性感热舞Gvod高清在线播放，剧情介绍等。",73,231);
$z[1][4]['name']="description";
$z[2]=Array("field","韩国舞王Rain和舞后李孝利性感热舞",233,303);
$z[2][4]['name']="title";
$z[3]=Array("field","",305,344);
$z[3][4]['name']="writer";
$z[4]=Array("field","",346,385);
$z[4][4]['name']="source";
$z[5]=Array("field","2006-08-04",387,437);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<P>播放后双击视频“全屏”</P> \n<object classid=\"CLSID:22d6f312-b0f6-11d0-94ab-0080c74c7e95\" class=\"OBJECT\" id=\"MediaPlayer\" width=\"500\" height=\"350\" ><param name=\"ShowStatusBar\" value=\"-1\"><param name=\"Filename\" value=\"http://www.5830.com/mv1/fm214.com_rain-leehyori_dance.asf\"></embed></object><br /> \n<P>下载地址<BR></P> <br>",439,803);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c120524/133N353DD0-2G248.gif",805,888);
$z[7][4]['name']="litpic";

?>