{dede:field name='keywords'}力王永恒的经典HD高清国语中字10{/dede:field}
{dede:field name='description'}力王永恒的经典HD高清国语中字1024*576迅雷下载、免费下载，力王永恒的经典HD高清国语中字1024*576Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}力王永恒的经典HD高清国语中字1024*576{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-08-26{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20110825/21/62564813201108252115201758135531806_003.jpg" /></p>
<p>
	◎片　　名　力王<br />
	◎译　　名　Story Of Ricky / Lik Wong<br />
	◎年　　代　1991<br />
	◎国　　家　香港/日本<br />
	◎类　　别　动作/犯罪/幻想/惊悚<br />
	◎语　　言　普通话<br />
	◎字　　幕　中文<br />
	◎IMDB链接 <a href="http://www.imdb.com/title/tt0102293/">http://www.imdb.com/title/tt0102293/</a><br />
	◎IMDB评分 7.0/10((5,182 votes)<br />
	◎片　　长　83 Mins<br />
	◎导　　演　蓝乃才 Ngai Kai Lam<br />
	◎主　　演　樊少皇 Siu-Wong Fan .... Riki-Oh Saiga<br />
	　　　　　　樊梅生 Mui Sang Fan .... Assistant Warden (as Faan Mooi Saang)<br />
	　　　　　　何家驹 Ka-Kui Ho .... The Warden<br />
	　　　　　　大岛由加利 Yukari ?shima .... Yomi (Huang Chaun)<br />
	　　　　　　Frankie Chin .... Narumi (Hai)<br />
	　　　　　　丹波哲郎 Tetsuro Tamba .... Rikis Master<br />
	　　　　　　叶蕴仪 Gloria Yip .... Keiko (Rikis girlfriend)<br />
	　　　　　　郭振锋 Philip Kwok .... Lin Hung<br />
	　　　　　　林雪 Suet Lam ....<br />
	　　　　　　Daan Bob Chit Long ....<br />
	　　　　　　黄智强 Ji Keung Wong ....<br />
	　　　　　　Cheng Chuen Yam .... Wildcat</p>
<p>
	<br />
	【内容简介】<br />
	　<br />
	　　 漫画《力王》根据漫画改编，力王（樊少皇）为挽救其女友莹莹（叶蕴仪）脱离魔掌，发怒杀死一群坏人而被判入国分监狱，可惜莹莹仍伤重不治。这私营监狱大狂魔狱长（何家驹）是身体能膨胀的巨人且常迫害囚犯。力王在狱中被单眼蛇（樊梅生）迫害，替溽弱但心地善良的老囚犯老马伸张正义，力王屡挫屡战的打不死精神，吓退单眼蛇。于是单眼蛇纠合狱中东南西北四仓之四大天王联合起来陷害对抗力王&hellip;&hellip;</p>
<p>
	影评</p>
<p>
	　　血腥</p>
<p>
	　　通常，血浆卖多了或者导演想象过于疯狂会让恐怖片产生强烈的搞笑效果，因为观众提醒自己&ldquo;这是电影、这不是真的、红色的液体只是番茄酱&rdquo;的过程就是否定&ldquo;银幕真实&rdquo;的过程，着力渲染血腥的结果只能是观众更加坚定了&ldquo;不信&rdquo;立场，如此，即使是《群尸玩过界》那样血雨滂沱、烂肉横飞的电影看起来也无异于闹剧一场吓唬吓唬小孩儿罢了--塑胶破裂、粘液流淌、番茄酱成吨，不管有多少人为此发抖，理性多点的观众看到这些东西往往嘴角含笑，一边感叹任何时代的恐怖电影都会有技术缺陷，一边怀疑：这个世界上到底有没有能令自己捂上眼睛不敢看的电影？</p>
<p>
	　　迄今为止我真正害怕的是用手术刀杀人的汉尼拔博士（《沉默的羔羊2》），感觉《沉默的羔羊前传》中汉尼拔刺伤联邦调查局特工威尔&middot;格雷厄姆的小刀比《人玩鬼》男主角砍掉女友脑袋的铁锹吓人多了，这一刀所选择的位置、刺出的力度有医生做手术一样的精确，肉体将会遭受怎样的痛楚，不敢想象！《纽约黑帮》，屠夫比尔教导后辈阿姆斯特丹如何刺中肝脏，他的杀人方法较比中国功夫片里武林前辈传授给门徒的各种招数简单实用、真实可信，所以这短短几组镜头比用几十分钟的长度描述某某十年如一日苦练武功然后下山报仇的情节更有震撼性--只有那些了解动物身体组织结构的人干起杀人勾当才最令人害怕。</p>
<p>
	　　《魔戒》中的勇士们杀敌成百上千，我们非但不怕还觉赏心悦目，因为死的是妖魔鬼怪。人怕杀人。如果电影讲杀人故事逼真到你不能不信的程度，真正的恐怖感就来临了！个人以为《魔界追魂》、《午夜凶铃2》、《沉默的羔羊》系列的恐怖展览成就最高，这些电影解剖人体兴趣之浓厚，法医看了都要给电检处写信。</p>
<p>
	<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20110825/21/62564813201108252115201758135531806_000.jpg" /><img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20110825/21/62564813201108252115201758135531806_001.jpg" /><img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20110825/21/62564813201108252115201758135531806_002.jpg" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="word-break: break-all; line-height: 18px" width="100%">
				<a href="&#13;&#10;ftp://dy125:piaohua@dy125.piaohua.com:2060/飘花电影piaohua.com力王HD高清1024分辨率.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:2060/飘花电影piaohua.com力王HD高清1024分辨率.rmvb </a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1Bc2F-12632.jpg{/dede:field}
