<?php
$z[0]=Array("field","On,Call,36小时粤语25国语25TVB",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","On Call 36小时粤语25国语25TVB时装医务迅雷下载、免费下载，On Call 36小时粤语25国语25TVB时装医务Gvod高清在线播放，剧情介绍等。",72,240);
$z[1][4]['name']="description";
$z[2]=Array("field","On Call 36小时粤语25国语25TVB时装医务",242,317);
$z[2][4]['name']="title";
$z[3]=Array("field","",319,358);
$z[3][4]['name']="writer";
$z[4]=Array("field","",360,399);
$z[4][4]['name']="source";
$z[5]=Array("field","2012-03-17",401,451);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",453,490);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://dy44:piaohua@dy44.piaohua.com:2809/飘花电影piaohua.com-On Call 36小时粤语01.rmvb",492,617);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MQ00010-44S9.jpg",619,701);
$z[8][4]['name']="litpic";

?>