{dede:field name='keywords'}超级无敌掌门狗,系列4部BD中英双{/dede:field}
{dede:field name='description'}超级无敌掌门狗 系列4部BD中英双字1024/1280高清迅雷下载、免费下载，超级无敌掌门狗 系列4部BD中英双字1024/1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}超级无敌掌门狗 系列4部BD中英双字1024/1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-15{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://pic.yesky.com/imagelist/09/01/11278513_m_11278515_2036.bmp" /><br />
	<br />
	◎译　　名　超级无敌掌门狗：月球野餐记/月球野餐记<br />
	◎片　　名　A Grand Day Out with Wallace and Gromit<br />
	◎年　　代　1989<br />
	◎国　　家　英国<br />
	◎类　　别　动画/短片/冒险/喜剧/家庭<br />
	◎语　　言　英语<br />
	◎字　　幕　中字<br />
	◎IMDB评分 7.8/10 (10,319 votes)<br />
	◎文件格式　BD-RMVB<br />
	◎视频尺寸　800 x 480<br />
	◎文件大小　1CD<br />
	◎片　　长　23 min 57 sec<br />
	◎导　　演　尼克&middot;帕克 Nick Park<br />
	◎主　　演　彼得&middot;萨利斯 Peter Sallis ... Wallace (voice)<br />
	<br />
	◎简　　介<br />
	<br />
	　　掌门狗Gromit与主人Wall<a href="http://www.5156rj.com/ie.html" target="_blank">ie</a>到月球去旅行，错把月球表面的凹凸当起司削来吃&hellip;&hellip;表现了丰富的想象力与温馨的幽默感，是一部老少皆宜的作品。<br />
	<br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://img.album.pchome.net/54/71/54/43/e2292d01991d3b652ae4ead757d93e93.jpg');" src="http://img.album.pchome.net/54/71/54/43/e2292d01991d3b652ae4ead757d93e93.jpg" /><br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://img.album.pchome.net/54/71/54/43/4e0f877f93f8bfe04f47474354fc3c8b.jpg');" src="http://img.album.pchome.net/54/71/54/43/4e0f877f93f8bfe04f47474354fc3c8b.jpg" /></p>
<hr />

<p>
	◎译　　名　超级无敌掌门狗：神奇太空衣/酷狗宝贝：神奇太空衣/引鹅入室/不合适的裤子/超级无敌掌门狗：着错裤(港)<br />
	◎片　　名　Wallace &amp; Gromit in The Wrong Trousers<br />
	◎年　　代　1993<br />
	◎国　　家　英国<br />
	◎类　　别　动画/短片/喜剧/犯罪/家庭<br />
	◎语　　言　英语<br />
	◎字　　幕　<b>中字</b><br />
	◎IMDB评分 <b>8.6/10 (23,257 votes)</b><br />
	◎文件格式　BD-RMVB<br />
	◎视频尺寸　800 x 480<br />
	◎文件大小　1CD<br />
	◎片　　长　30 min 19 sec<br />
	◎导　　演　尼克&middot;帕克 Nick Park<br />
	◎主　　演　彼得&middot;萨利斯 Peter Sall<a href="http://www.5156rj.com/ie.html" target="_blank">ie</a> ... Wallace (voice)<br />
	<br />
	◎简　　介<br />
	<br />
	　　这场闹剧是由一条能动的怪裤子和一只邪恶的<a href="http://www.eee4.com/" target="_blank">迅雷电影下载</a>企鹅引起的。Wallace的来访者企鹅其实是一个坏蛋，他阴谋策划妄图将不知情的Wallace拉下水，而Wallace的新发明机器裤子成了企鹅盗取钻石珠宝的工具。坏人的阴谋当然不会得逞&hellip;&hellip;<br />
	<br />
	花絮<br />
	<br />
	&middot;该片获得1993奥斯卡最佳动画短片奖。<br />
	<br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://img.album.pchome.net/54/71/54/43/8318c19e06b064a1c707b4f2ac921f76.jpg');" src="http://img.album.pchome.net/54/71/54/43/8318c19e06b064a1c707b4f2ac921f76.jpg" /><br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://img.album.pchome.net/54/71/54/43/eed0eb6dddeb3ac6bebccef723d3ae31.jpg');" src="http://img.album.pchome.net/54/71/54/43/eed0eb6dddeb3ac6bebccef723d3ae31.jpg" /></p>
<hr />

<p>
	◎译　　名　超级无敌掌门狗：剃刀边缘/九死一生/剃刀边缘<br />
	◎片　　名　Wallace and Gromit in A Close Shave<br />
	◎年　　代　1995<br />
	◎国　　家　英国<br />
	◎类　　别　动画/短片/喜剧/犯罪/家庭<br />
	◎语　　言　英语<br />
	◎字　　幕　中字<br />
	◎IMDB评分 8.4/10 (16,116 votes)<br />
	◎文件格式　BD-RMVB<br />
	◎视频尺寸　800 x 480<br />
	◎文件大小　1CD<br />
	◎片　　长　31 min 25 sec<br />
	◎导　　演　尼克&middot;帕克 <a href="http://www.taobao13.com/Nike.htm" target="_blank">Nike</a> Park<br />
	◎主　　演　彼得&middot;萨利斯 Peter Sallis ... Wallace (voice)<br />
	　　　　　　Anne Reid ... Wendolene Ramsbottom (voice)　　　　　　<br />
	<br />
	◎简　　介<br />
	<br />
	　　掌门狗葛罗米特和主人华莱士牵涉在一件偷羊案里深陷冤狱，险些性命不保，幸好最后翻案雪冤，非但大难不死，还撮合了华莱士与羊毛店老板娘的美好姻缘。<br />
	<br />
	幕后花絮<br />
	<br />
	&middot;本片获得1995年奥斯卡金像奖最佳动画短片。<br />
	<br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://img.album.pchome.net/54/71/54/43/f4e31f5f63828d3391daa67a526076ef.jpg');" src="http://img.album.pchome.net/54/71/54/43/f4e31f5f63828d3391daa67a526076ef.jpg" /><br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://img.album.pchome.net/54/71/54/43/4ce68bf8f20317abac236d434971152c.jpg');" src="http://img.album.pchome.net/54/71/54/43/4ce68bf8f20317abac236d434971152c.jpg" /></p>
<hr />

<p align="left">
	【译　　名】《超级无敌掌门狗：面包和死亡事件》美国08最新喜剧动画DVD中英双字1280x720高清版<br />
	【其他译名】酷狗宝贝：面包和死亡事件/华莱士与葛罗米特：面包和死亡事件<br />
	【片　　名】Wallace and Gromit in &#39;A Matter of Loaf and Death&#39;<br />
	【出品年代】2008<br />
	【影片长度】28分钟<br />
	【国　　家】英国<br />
	【类　　别】喜剧 动画 家庭<br />
	【语　　言】英语<br />
	【字　　幕】中文字幕<br />
	【IMDB评分】7.8/10 440 votes<br />
	【视频尺寸】880&times;492<br />
	【IMDB链接】http://www.imdb.com/title/tt1118511/<br />
	【导　　演】Nick Park Bob Barker</p>
<p align="left">
	　　&ldquo;酷狗宝贝&rdquo;黏土动画是英国动画公司Aardman的代表名作，以特殊的英国风格，轻松幽默的人物刻划，精致的拍摄品质著称，因此&ldquo;酷狗宝贝&rdquo;一推出，即成为全球注目的焦点。第一部动 画&ldquo;月球野餐记&rdquo;(A Grand Day Out&rdquo;在电视首次播放时，即掀起观众热烈回响，并获得奥斯卡金像奖的提名。再度推出的系列作品&ldquo;引鹅入室&rdquo;(The Wrong Trousers)及&ldquo;剃刀边缘&rdquo;(A Close Shave)两部动 画，也分别得到当年奥斯卡最佳短片大奖。<br />
	　　至今，酷狗宝贝已成为英国文化的重要代表，在英国，80%的人<a href="http://www.eee4.com/" target="_blank">电影下载</a>都认得它。酷狗宝贝还因此被英国旅游指南推荐为游客不可不认识的英国人物之一。</p>
<p align="left">
	<br />
	　　改行做起面包店老板的Wallace和Gromit再次遭遇神秘事件！话说这二位在家中建起一座超级自动化的面包房，但在生意红火之际，Gromit警觉的发现身边的面包店老板竟然一个个地消失。不过他的主人Wallace正沐浴在爱河对一切毫无察觉，此时我们的小狗又将担起重任&hellip;&hellip;</p>
<p align="left">
	【截图】：</p>
<p align="left">
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://img.album.pchome.net/54/68/92/28/e912ab10e46db6607ca126487055710b.jpg');" src="http://img.album.pchome.net/54/68/92/28/e912ab10e46db6607ca126487055710b.jpg" /><br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://img.album.pchome.net/54/68/92/28/1a4e7ebf34ae24f03d38188c615e8478.jpg');" src="http://img.album.pchome.net/54/68/92/28/1a4e7ebf34ae24f03d38188c615e8478.jpg" /><br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://img.album.pchome.net/54/68/92/28/510c7a45d30b657f62155f8543e2713b.jpg');" src="http://img.album.pchome.net/54/68/92/28/510c7a45d30b657f62155f8543e2713b.jpg" /></p>
<br />
<p>
	英国经典精彩高分喜剧短片《超级无敌掌门狗 【系列4部】》BD中字 [下载地址]：<img border="0" src="http://www.eee4.com/templets/img/down.jpg" /></p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://3e:3e@xl.eee4.com:221/[3E电影站www.eee4.cn]超级无敌掌门狗：月球野餐记.rmvb" target="_blank">ftp://3e:3e@xl.eee4.com:221/[3E电影站www.eee4.cn]超级无敌掌门狗：月球野餐记.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://3e:3e@xl.eee4.com:221/[3E电影站www.eee4.cn]超级无敌掌门狗：神奇太空衣.rmvb" target="_blank">ftp://3e:3e@xl.eee4.com:221/[3E电影站www.eee4.cn]超级无敌掌门狗：神奇太空衣.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://3e:3e@xl.eee4.com:221/[3E电影站www.eee4.cn]超级无敌掌门狗：剃刀边缘.rmvb" target="_blank">ftp://3e:3e@xl.eee4.com:221/[3E电影站www.eee4.cn]超级无敌掌门狗：剃刀边缘.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://e8:e8@xl2.eee4.com:9306/[3E电影站www.eee4.com]酷狗宝贝：面包和死亡事件BD中英双字.rmvb" target="_blank">ftp://e8:e8@xl2.eee4.com:9306/[3E电影站www.eee4.com]酷狗宝贝：面包和死亡事件BD中英双字.rmvb</a></td>
		</tr>
	</tbody>
</table>
<p>
	美国08最新动画《超级无敌掌门狗》DVD中英双字1280x720高清版</p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://e8:e8@xl2.eee4.com:9306/[3E电影站www.eee4.com]超级无敌掌门狗：面包和死亡事件.rmvb" target="_blank">ftp://e8:e8@xl2.eee4.com:9306/[3E电影站www.eee4.com]超级无敌掌门狗：面包和死亡事件1280.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3426/飘花电影piaohua.com超级无敌掌门狗：神奇太空衣BD中英双字1280高清.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3426/飘花电影piaohua.com超级无敌掌门狗：神奇太空衣BD中英双字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3426/飘花电影piaohua.com超级无敌掌门狗：剃刀边缘BD中英双字1280高清.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3426/飘花电影piaohua.com超级无敌掌门狗：剃刀边缘BD中英双字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3426/飘花电影piaohua.com超级无敌掌门狗：月球野餐记BD中英双字1280高清.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3426/飘花电影piaohua.com超级无敌掌门狗：月球野餐记BD中英双字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3426/飘花电影piaohua.com超级无敌掌门狗：月球野餐记BD中英双字1024高清.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3426/飘花电影piaohua.com超级无敌掌门狗：月球野餐记BD中英双字1024高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15LZ50-223X.jpg{/dede:field}
