{dede:field name='keywords'}一夜成名BD国语中字1024/1280高{/dede:field}
{dede:field name='description'}一夜成名BD国语中字1024/1280高清2012中国喜剧音乐大片迅雷下载、免费下载，一夜成名BD国语中字1024/1280高清2012中国喜剧音乐大片Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}一夜成名BD国语中字1024/1280高清2012中国喜剧音乐大片{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-04-14{/dede:field}
{dede:field name='body'}<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120413/21/56643687201204132104143783913910357_006.jpg" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120413/21/56643687201204132104143783913910357_005.jpg" /></p>
<p>
	导演: 石磊<br />
	编剧: 郑长明 / 王磊<br />
	主演: 维塔斯 / 黄圣依 / 卡门&middot;玛索拉 / 田娃 / 刘桦 / 王思懿<br />
	类型: 剧情 / 喜剧 / 音乐<br />
	制片国家/地区: 中国大陆<br />
	语言: 汉语普通话<br />
	上映日期: 2012-04-13(中国大陆)<br />
	片长: 93分钟<br />
	又名: One Night To Be Star</p>
<p>
	<br />
	剧情简介</p>
<p>
	　　放羊娃铁柱（田娃 饰）在中国时尚达人秀节目中脱颖而出。被人和演艺公司总裁范娱乐（刘桦 饰）看中并着力培养，且送他出国深造。铁柱在音乐学博士隋晓菲（黄圣依 饰）的引荐下，得到英国著名音乐教授的指导。同时，他与隋晓菲也建立起了一种奇妙的感情。学成归国后的铁柱将有机会和世界巨星VITAS（维塔斯 Vitas 饰）及意大利版苏珊大妈玛索拉（卡门&middot;玛索拉 Carmen Masola 饰）同台献艺，但是他质朴的情怀却和娱乐圈格格不入，使得他走上了一条极为坎坷的成名之路&hellip;&hellip;</p>

<p>
	◎影片截图</p>
<p>
	&nbsp;<img src="http://img170.poco.cn/mypoco/myphoto/20120413/21/56643687201204132104143783913910357_000.jpg" style="width: 600px; height: 338px" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120413/21/56643687201204132104143783913910357_001.jpg" style="width: 600px; height: 338px" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120413/21/56643687201204132104143783913910357_002.jpg" style="width: 600px; height: 338px" /></p>
<p>
	&nbsp;<img src="http://img170.poco.cn/mypoco/myphoto/20120413/21/56643687201204132104143783913910357_003.jpg" style="width: 600px; height: 338px" /></p>
<p>
	<img src="http://img170.poco.cn/mypoco/myphoto/20120413/21/56643687201204132104143783913910357_004.jpg" style="width: 600px; height: 338px" /></p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.netftp//dy44:piaohua@dy44.piaohua.com:3201/" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3215/飘花电影piaohua.com一夜成名高清DVD国语中字.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3215/飘花电影piaohua.com一夜成名高清DVD国语中字.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3224/飘花电影piaohua.com一夜成名BD国语中字1024高清.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3224/飘花电影piaohua.com一夜成名BD国语中字1024高清.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3224/飘花电影piaohua.com一夜成名BD国语中字1280高清.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3224/飘花电影piaohua.com一夜成名BD国语中字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O15D5M0-4YG.jpg{/dede:field}
