{dede:field name='keywords'}白夜行BD中字1280高清迅雷下载，{/dede:field}
{dede:field name='description'}白夜行BD中字1280高清迅雷下载、免费下载，白夜行BD中字1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}白夜行BD中字1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-05-24{/dede:field}
{dede:field name='body'}<p>
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://i2.sinaimg.cn/ent/x/2009-09-28/1254115875_UswkwM.jpg');" src="http://i2.sinaimg.cn/ent/x/2009-09-28/1254115875_UswkwM.jpg" /><br />
	<br />
	◎译　　名　《白夜行》孙艺珍、韩石圭09年最新小说改编神秘爱情大片DVD中字无水印<br />
	◎片　　名　White Night<br />
	◎年　　代　2009<br />
	◎国　　家　韩国<br />
	◎类　　别　剧情/神秘/爱情<br />
	◎语　　言　韩语<br />
	◎字　　幕　中文<br />
	◎IMDB评分 6.1/10&nbsp; 7 votes<br />
	◎文件格式　DVD-RMVB<br />
	◎视频尺寸　640 x 360<br />
	◎文件大小　2CD<br />
	◎片　　长　125 Min<br />
	◎导　　演　朴信宇 Shin-woo Park<br />
	◎主　　演　孙艺珍 Ye-jin Son<br />
	　　　　　　韩石圭 Suk-kyu Han<br />
	　　　　　　高修 Soo Go<br />
	　　　　　　李敏贞 Min-jung Lee<br />
	　　　　　　朱多英 Ta-yeong Ju<br />
	　　　　　　崔秦豪 Jin-ho<a href="http://www.eee4.org/" target="_blank">3e</a> Choi<br />
	　　　　　　李宗元 Jong-won Lee....Seung-jo<br />
	　　　　　　Seong-Woong Park<br />
	　　　　　　Ye-won Han<br />
	　　　　　　Kook-jin Han<br />
	　　　　　　Cheol-woo Han<br />
	<br />
	◎简　　介　<br />
	<br />
	&nbsp; 改编自日本著名推理小说家东野圭吾的同名作品，之前绫濑遥、山田孝之主演的日剧版曾大获成功。孙艺珍在片中扮演唯一的愿望就是在太阳下和恋人手牵手，却因为小时候发生的悲惨事件，只能孤独度日的女主角。制作方提出邀请孙艺珍主演的理由是：&ldquo;拥有能够把寂寞的美和内心阴暗面表现出来的演技，又有一双会说话的眼睛的女演员，非孙艺珍莫属。&rdquo; 高修则是为了保护心爱的女孩孙艺珍牺牲自己一切的男主人公，这同时也是他阔别五年之久重返大银幕的全新力作。片中韩石圭扮演重新调查15年前如同迷宫般的杀人案，并且是唯一理解主角男女灰暗过去的刑警韩东秀。<br />
	<br />
	&nbsp; 影片改编自日本同名小说《白夜行》，讲述一对年轻恋人不幸的经历。<br />
	<br />
	&nbsp; 14年前，发生了一起恶性的杀人事件，死者分别是少男有汉的父亲和少女美皓的母亲。其实凶手正是这对青<br />
	<br />
	涩的少年。生活窘迫的母亲一直威逼年少的美皓卖淫，对象正是有汉的父亲。有汉目睹了父亲的暴行，忍无可忍下亲手杀死了兽性的父亲，而美皓为了庇护有汉亦将知晓内情的母亲杀死。法律对案子追查期是15年。为了逃避法律制裁，两个孩子决定在此后的15年内像陌生人一样生活，直到有一天两个人可以手牵着手，在阳光下一同散步。<br />
	<br />
	&nbsp; &nbsp; 然而，就在他们各自平静的生活了几年之后，他们发现居然还有人在追查这个案子&hellip;&hellip;而此时，美皓已出落成完美的成熟女郎，身份是某财阀的未婚妻，她和有汉的神秘往来，也引起了采伐秘书诗贞的怀疑。有汉和美皓这对苦命鸳鸯的将会迎来怎样的命运？<br />
	<br />
	幕后制作<br />
	<br />
	&nbsp; 全新的改编视角<br />
	<br />
	&nbsp; 由影后孙艺珍和退伍归来的高修主演的《白夜行》，阵容上首先就备受关注。影片改编自日本殿堂级推理大师东野圭吾的里程碑作品《白夜行》。自1985年登上文坛以来，东野奎吾发表的60多部作品中有14部被改编为电影或电视剧，而2000年《白夜行》出版后，四周蝉联畅销书榜首，更被拍成电视剧，一举捧红了现在的山田孝之和绫濑遥。此次，韩国电影版的《白夜行》请来了曾创作热门剧《恋爱时代》和电影《我的野蛮女老师》的著名编剧朴延善操刀，对原有人物性格进行了重新润色，并获得了原作者东野奎吾的盛赞，认为是一部相当出色的&ldquo;电影化&rdquo;改编。与电视剧本版不一样的是，电影叙述将以第三者的视角展开，即所有关于男女角的行动、表情、心理变化都是通过&ldquo;第三者&rdquo;刑警东修和财阀秘书诗贞的所见所闻表现出来的。这种新颖的间接表现方式与影片所要展现的悬疑感完美结合，形成了一种贯彻始终的神秘感，是观众的窥探欲得到了极大的足。而这个第三是由演技派男星韩石圭出演，他扮演的追查凶杀案的警官是片中唯一可以理解男女主人公心路历程的重线索人物。<br />
	<br />
	&nbsp; 新人导演的美学态度<br />
	<br />
	&nbsp; 导演部分则由毕业于弘益大学视觉设计专业的朴信宇担任。虽是首次执导剧情长片（此前有短篇作品《未成年人不可观赏》），朴信宇却经验老到，曾和人气影片《追击者》的导演罗宏镇成为韩国第四届Mise-en-scene&#39;s短片电影节上最受瞩目的新人导演。在《白夜行》<a href="http://www.3edyy.com/" target="_blank">电影下载</a>中，朴信宇重返发挥了自己专业所长，用视觉美感来丰富整部作品的内涵和感受。在朴信宇眼中所有道具都是充满灵魂的，甚至是一张桌子、一把椅子都可以表达无限的深意。因此，他精心安排片中四位主要人物的交错关系，在复杂的人物视线重叠中刻画他们各自不同的心理变化和性格走向。而从窗户、门、墙壁，小到演员们的着装、配饰都体现出了别有用心的设计，用来辅助人刻画人物内心的需求。<br />
	<br />
	&nbsp; 奇妙的色彩构图<br />
	<br />
	&nbsp; 《白夜行》的故事是残酷的，色调是灰暗的，情愫是阴郁的。为了实现人物的性格明朗化，导演采用了新颖的色觉构图，即将故事中的主要人物的用不同的颜色表现出来，如美皓的&ldquo;白&rdquo;、有汉的&ldquo;黑&rdquo;、东修的&ldquo;绿&rdquo;，以及诗贞的&ldquo;黄&rdquo;。对于美皓和有汉来说，这个世界是没有颜色的，她身上的白意味着明媚的美貌，但内心没有色彩，而有汉则为了保护心爱的美皓，一直做着充满罪恶的凶事。美皓和有汉的白与黑有时是对立的，有时又是可以置换的，但归根结蒂地是对比出了这个世界的残酷。东修的&ldquo;绿&rdquo;来自对那对苦命男女的理解以及对现实残酷的无奈。诗贞的&ldquo;黄&rdquo;则是一种衔接的色彩，它把人物的过去和现在有机地结合在一起，从中品味出不同的意境。这些假想的颜色将通过灯光、布景等效果展现出来，是一次全新的尝试。<br />
	<br />
	&nbsp; 顶级幕后团队助阵<br />
	<br />
	&nbsp; 本片的监制也是韩国影坛大名鼎鼎的导演康佑硕。这位曾经将萎靡的韩国电影带向振兴富强的电影人2009年的头等大事就是完成《白夜行》的拍摄计划，除了请来擅长言情题材的编剧朴延善，还请来了《追击者》的副导演李昌宰加盟剧组，主要负责影片中过去与现在时空交错的视觉编排，力图呈现出一种于众不同的视觉感受。此外，还有参与过《密阳》、《家族的诞生》等片的照明师秋仁植；打造《苹果》、《罗宾先生追求记》的美术指导宋惠珍；为《蝙蝠》、《卑劣的街头》、《老男孩》<a href="http://www.eee4.cc/" target="_blank">3E电影院</a>等片谱曲的作曲家赵英旭等人纷纷加入幕后军团，影片的成功奠定了坚实的基础。<br />
	<br />
	花絮<br />
	<br />
	&middot;孙艺珍是影片筹拍前就内定的女主角，从投资方到导演所有人都认定只有她的气质可以胜任外表温存内心复杂的美皓。就在孙艺珍进入剧组的这天，意想不到的事情发生了。原来导演朴信宇竟是孙艺珍在大邱高中时期的学，两人经常在图书馆一起看书。后来孙艺珍来到首尔发展，就再也没有联系到那位学长，没想到几年后，两人竟是已导演和演员的身份重逢，彼此都惊喜不已。<br />
	<br />
	&middot;让韩石圭出演刑警东修一角费了一些周折。其实，在朴信宇心目中，韩石奎是最适合这一角色的演员，但对于首次执导长片的新人导演来说，邀请顶级明星加盟几乎是不可能的事情。于是，朴信宇亲笔给韩石圭写了一信，阐明了自己的诚意和这个角色非其莫属的理由，最终感动了韩石圭。<br />
	<br />
	&middot;剧组走遍全国，寻找最合适的拍摄场所。剧本中，男女主人公成长的过程中，需要一间咖啡屋充当重点叙述场景。就为了这么一个方寸之间，剧组花了进六个月的时间甄选，终于找到了一个非常理想的咖啡店。谁知，就在拍摄前两周，原本空空荡荡的咖啡店却突然开始了意大利餐厅风格的装修。此时，剧组已经没有时间再去寻找别的场所，美工部门索性在咖啡店内部人工置景，搭了一个和原来咖啡店风格近乎吻合的场景。</p>
<p>
	【电影截图】：<br />
	<br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://photo5.zxip.com/albums5/folder10/7895/20100303224157/20103232125334393.jpg');" src="http://photo5.zxip.com/albums5/folder10/7895/20100303224157/20103232125334393.jpg" /><br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://photo5.zxip.com/albums5/folder10/7895/20100303224157/20103232125345709.jpg');" src="http://photo5.zxip.com/albums5/folder10/7895/20100303224157/20103232125345709.jpg" /><br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://photo5.zxip.com/albums5/folder10/7895/20100303224157/20103232125344888.jpg');" src="http://photo5.zxip.com/albums5/folder10/7895/20100303224157/20103232125344888.jpg" /><br />
	<img border="0" onclick="if(this.width&gt;screen.width-461) window.open('http://photo5.zxip.com/albums5/folder10/7895/20100303224157/20103232125353655.jpg');" src="http://photo5.zxip.com/albums5/folder10/7895/20100303224157/20103232125353655.jpg" /></p>
	<img alt="" height="337" src="http://img170.poco.cn/mypoco/myphoto/20120516/20/57196343201205162049492717770632607_001.jpg" style="cursor: pointer" width="600" /><br />
	<img alt="" height="337" src="http://img170.poco.cn/mypoco/myphoto/20120516/20/57196343201205162049492717770632607_000.jpg" style="cursor: pointer" width="600" /></p>
	[下载地址]：<img border="0" src="http://www.3edyy.com/templets/img/down.jpg" /><br />
	&nbsp;</p>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://3e:3e@www5.eee4.cc:1439/【3E电影院www.eee4.cc】白夜行CD1.rmvb" target="_blank">ftp://3e:3e@www5.eee4.cc:1439/【3E电影院www.eee4.cc】白夜行CD1.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://3e:3e@www5.eee4.cc:1439/【3E电影院www.eee4.cc】白夜行CD2.rmvb" target="_blank">ftp://3e:3e@www5.eee4.cc:1439/【3E电影院www.eee4.cc】白夜行CD2.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://3e:3e@m1.3edyy.com:1455/【3E电影院www.eee4.cc】白夜行DVD中字无水印.rmvb" target="_blank">ftp://3e:3e@m1.3edyy.com:1455/【3E电影院www.eee4.cc】白夜行DVD中字无水印.rmvb</a></td>
		</tr>
	</tbody>
</table>
<table align="center" border="0" cellpadding="6" cellspacing="0" style="border-bottom: #cccccc 1px dotted; border-left: #cccccc 1px dotted; table-layout: fixed; border-top: #cccccc 1px dotted; border-right: #cccccc 1px dotted" width="95%">
	<tbody>
		<tr>
			<td bgcolor="#fdfddf" style="word-wrap: break-word">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3485/飘花电影piaohua.com白夜行BD中字1280高清.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3485/飘花电影piaohua.com白夜行BD中字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O14912620-41T7.jpg{/dede:field}
