<?php
$z[0]=Array("field","《咪咁扮嘢》王祖蓝演嘢会/演唱",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","《咪咁扮嘢》王祖蓝演嘢会/演唱会[DVD粤语中字]迅雷下载、免费下载，《咪咁扮嘢》王祖蓝演嘢会/演唱会[DVD粤语中字]Gvod高清在线播放，剧情介绍等。",72,254);
$z[1][4]['name']="description";
$z[2]=Array("field","《咪咁扮嘢》王祖蓝演嘢会/演唱会[DVD粤语中字]",256,338);
$z[2][4]['name']="title";
$z[3]=Array("field","",340,379);
$z[3][4]['name']="writer";
$z[4]=Array("field","",381,420);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-01-16",422,472);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",474,511);
$z[6][4]['name']="body";
$z[7]=Array("field","ftp://5e:5e@m1.3edyy.com:1578/【3E看看www.3ekk.com】王祖蓝演唱会[DVD中字].rmvb\" target=_blank>ftftp://5e:5e@m1.3edyy.com:1578/【3E看看www.3ekk.com】王祖蓝演唱会[DVD中字].rmvb</A></TD></TR></TBODY></TABLE></div><ul class=\"mmlist",513,779);
$z[7][4]['name']="xiazai";
$z[8]=Array("field","/uploads/allimg/c120523/133MQ4594F-41432.jpg",781,864);
$z[8][4]['name']="litpic";

?>