{dede:field name='keywords'}八脚怪/近蛛者杀BD中英双字1280{/dede:field}
{dede:field name='description'}八脚怪/近蛛者杀BD中英双字1280高清经典恐怖惊悚迅雷下载、免费下载，八脚怪/近蛛者杀BD中英双字1280高清经典恐怖惊悚Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}八脚怪/近蛛者杀BD中英双字1280高清经典恐怖惊悚{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-04-28{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://apollo.s.dpool.sina.com.cn/nd/dataent/moviepic/pics/97/moviepic_aaa99a8b079c73da6ce53d070a45f716.jpg" /></p>

<p>
	八脚怪 Eight Legged Freaks (2002)<br />
	别　名：近蛛者杀<br />
	导　演：艾洛伊&middot;艾克汉姆 Ellory Elkayem<br />
	主　演：大卫&middot;艾奎特 David Arquette 凯莉&middot;沃洛尔 Kari Wuhrer 汤姆&middot;诺南 Tom Noonan Ryan C. Benson Matt Czuchry 道格&middot;E&middot;道格 Doug E. Doug John Ennis Roy Gaintner<br />
	上　映：2002年05月30日 ( 瑞士 )<br />
	地　区：美国 ( 拍摄地 )<br />
	对　白：英语中英双字<br />
	评　分：5.6/10( 5289票 )<br />
	颜　色：彩色<br />
	时　长：99 分钟<br />
	类　型：科幻 恐怖 喜剧 动作<br />
	演员表：<br />
	大卫&middot;艾奎特 David Arquette .... Chris McCormick<br />
	凯莉&middot;沃洛尔 Kari Wuhrer .... Sheriff Samantha Parker<br />
	斯科特&middot;泰拉 Scott Terra .... Mike Parker<br />
	斯嘉丽&middot;约翰森 Scarlett Johansson .... Ashley Parker<br />
	道格&middot;E&middot;道格 Doug E. Doug .... Harlan Griffith<br />
	瑞克&middot;埃弗顿 Rick Overton .... Deputy Pete Willis<br />
	莱昂&middot;李佩 Leon Rippy .... Wade<br />
	Matt Czuchry .... Bret<br />
	Jay Arlen Jones .... Leon<br />
	艾琳&middot;赖安 Eileen Ryan .... Gladys<br />
	瑞莉&middot;史密斯 Riley Smith .... Randy<br />
	Matt Holwick .... Larry<br />
	Jane Edith Wilson .... Emma<br />
	Jack Moore .... Amos<br />
	Roy Gaintner .... Floyd<br />
	剧　情：<br />
	　　故事发生在美国的一个偏远小镇，这里的人们与世无争，过着平静的生活，但是灾难却在一夜之间降临到他们的头上。由于有毒化学废料发生了外泄事故，成千上万的小蜘蛛在一夜之间变得硕大无比、嗜血如命。它们潜入了小镇的角角落落，准备在把这里变间炼狱，而在此过程中，只有镇长的小儿子麦可觉察到了这一切，但是整个小镇只有采矿工程师克里斯密相信他的话，二人正准备说服小镇上的人们一起消灭这些怪物，却发现他们已经被满山遍野的&ldquo;八脚怪&rdquo;给包围了......</p>

	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				在线观看地址：<a href="http://www.xiaozhizhu.net" target="_blank">http://www.xiaozhizhu.net</a></td>
		</tr>
	</tbody>
</table>
<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="ftp://dy44:piaohua@dy44.piaohua.com:3311/飘花电影piaohua.com近蛛者杀BD中英双字1280高清.rmvb">ftp://dy44:piaohua@dy44.piaohua.com:3311/飘花电影piaohua.com近蛛者杀BD中英双字1280高清.rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1642bF-3E52.jpg{/dede:field}
