{dede:field name='keywords'}换心HD1280高清迅雷下载，免费下{/dede:field}
{dede:field name='description'}换心HD1280高清迅雷下载、免费下载，换心HD1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}换心HD1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-02-11{/dede:field}
{dede:field name='body'}<p>
	片名：换心<br />
	　　时间：2011年11月18日<br />
	　　主演：肖雨雨、刘妍希、董妮娜、赵静沛、孙仲加、徐帅、关欣<br />
	演员表<br />
	　　肖雨雨饰 陈水墨/四太太锦瑶<br />
	　　刘妍希饰 凤宣娇<br />
	　　孙仲加 饰 许 开<br />
	　　赵静沛 饰 红 果<br />
	　　董妮娜 饰 兰 子<br />
	　　徐 帅 饰 黄静云<br />
	　　关 欣 饰 盛书娴<br />
	　　王国刚饰 林孝堂<br />
	剧情简介<br />
	　　陈水墨是某大学美术系的学生，在乡下写生时机缘巧合结识了林老爷，两人相谈甚欢，林老爷力邀水墨到府上做家教。然而当陈水墨跨进林家大门的一瞬间，她的心脏就非常难受，不得不服药缓解。原来水墨曾因心脏不好，一年前换了一颗心，换给她心的人正是因杀人被枪决的林家四姨太锦瑶。在林家，水墨总被一种说不出的异样感觉笼罩，她的心在日夜哀嚎，似乎有冤情，为此水墨开始重新调查四姨太杀人的案件。<br />
	　　那么，四姨太是冤死的吗？案件背后有着怎样的隐情？</p>
<p>
	<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120211/01/62564813201202110134571579415944113_006.jpg" style="width: 720px; height: 405px" /><img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20120211/01/62564813201202110134571579415944113_005.jpg" style="width: 720px; height: 405px" /></p>
<p>
	<br />
	<br />
	&nbsp;</p>
<p>
	[下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="line-height: 18px; word-break: break-all" width="100%">
				<a href="&#13;&#10;ftp://dy125:piaohua@dy125.piaohua.com:7595/飘花电影piaohua.com换心HD国语中字1280高清.rmvb">ftp://dy125:piaohua@dy125.piaohua.com:7595/飘花电影piaohua.com换心HD国语中字1280高清.rmvb </a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O16061530-2K61.jpg{/dede:field}
