{dede:field name='keywords'}经典怀旧DVD狂情杀手迅雷下载，{/dede:field}
{dede:field name='description'}经典怀旧DVD狂情杀手迅雷下载、免费下载，经典怀旧DVD狂情杀手Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}经典怀旧DVD狂情杀手{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2011-08-06{/dede:field}
{dede:field name='body'}<p>
	<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20110806/18/62564813201108061806433075726579377_000.jpg" style="width: 400px; height: 358px" /></p>
<p>
	◎片　　名　狂情杀手<br />
	◎译　　名　Kuang qing sha shou<br />
	◎年　　代　1995<br />
	◎国　　家　中国香港<br />
	◎类　　别　动作 剧情<br />
	◎语　　言　国语<br />
	◎字　　幕　中文<br />
	◎IMDB评分 6.3/10 ( 32票 )<br />
	◎IMDB链接 <a href="http://www.7176.com/title/tt0094857">http://www.7176.com/title/tt0094857</a><br />
	◎制作公司　Regent Film Limited [香港]<br />
	◎发行公司　Regent Film Limited [香港]<br />
	◎文件格式　RMVB<br />
	◎视频尺寸　640 x 352<br />
	◎片　　长　01:28:25.467<br />
	◎导　　演　刘永 Tony Liu<br />
	◎编　　剧　阮继志 Kai-Chi Yun<br />
	◎主　　演　任达华 Simon Yam<br />
	　　　　　　刘永 Tony Liu&nbsp; ....(as Anthony Lau)<br />
	　　　　　　张敏 Sharla Cheung&nbsp; ....林苗<br />
	　　　　　　李元霸 Yuanba Li<br />
	　　　　　　黄锦江 Kam-Kong Wong<br />
	　　　　　　唐丽球 Joan Tong<br />
	◎简　　介<br />
	　　&nbsp;&nbsp; 人蛇刘文龙千里迢迢来到美国与太太团聚，为了留在美国，唯有充当福青帮头目马良祺之杀手，刘先后刺杀黑手党大头目及国会人蛇调查小组之议员。警方派中国籍探员Billy协助Roy追缉刘。与此同时，马与黑手党达成协议将刘出卖，受到夹击的刘情况危机，妻子更惨遭杀害，刘誓要为妻报仇，同时，马与黑手党正在为他安排耳了陷阱&hellip;&hellip;</p>

<p>
	◎截　　图：</p>
<p>
	&nbsp;<img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20110806/18/62564813201108061806433075726579377_005.jpg" /><img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20110806/18/62564813201108061806433075726579377_004.jpg" /><img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20110806/18/62564813201108061806433075726579377_003.jpg" /><img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20110806/18/62564813201108061806433075726579377_002.jpg" /><img alt="" src="http://img2081.poco.cn/mypoco/myphoto/20110806/18/62564813201108061806433075726579377_001.jpg" /></p>

<p>
	[狂情杀手下载地址]：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img border="0" src="http://i3.6.cn/cvbnm/c1/f4/cd/1d5d785194cc53c388c37ac6d66c5bd3.jpg" />&nbsp;&nbsp;&nbsp;</p>

<table bgcolor="#ff8c00" border="0" cellpadding="5" cellspacing="1" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#ffffbb" style="word-break: break-all; line-height: 18px" width="100%">
				<a href="&#13;&#10;ftp://dy195:piaohua@dy195.piaohua.com:1011/飘花电影下载站www.xiaozhizhu.net狂情杀手[国语中字].rmvb">ftp://dy195:piaohua@dy195.piaohua.com:1011/飘花电影下载站www.xiaozhizhu.net狂情杀手[国语中字].rmvb</a></td>
		</tr>
	</tbody>
</table>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120525/133O1BW950-5W61.jpg{/dede:field}
