{dede:field name='keywords'}2008春节联欢晚会迅雷下载，免费{/dede:field}
{dede:field name='description'}2008春节联欢晚会迅雷下载、免费下载，2008春节联欢晚会Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}2008春节联欢晚会{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2008-02-11{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://eee4.com:4421@vip8.eee4.com:4421/2008春晚/[3E迅雷电影站www.eee4.com]2008年央视春节联欢晚会01.rmvb" target=_blank>ftftp://eee4.com:4421@vip8.eee4.com:4421/2008春晚/[3E迅雷电影站www.eee4.com]2008年央视春节联欢晚会01.rmvb</A></TD></TR></TBODY></TABLE>CD2:<BR>
<TABLE style="BORDER-RIGHT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; BORDER-BOTTOM: #cccccc 1px dotted" cellSpacing=0 cellPadding=6 width="95%" align=center border=0>
<TBODY>
<TR>
<TD style="WORD-WRAP: break-word" bgColor=#fdfddf><ANCHOR></ANCHOR><A href="ftftp://eee4.com:4421@vip8.eee4.com:4421/2008春晚/[3E迅雷电影站www.eee4.com]2008年央视春节联欢晚会02.rmvb" target=_blank>ftftp://eee4.com:4421@vip8.eee4.com:4421/2008春晚/[3E迅雷电影站www.eee4.com]2008年央视春节联欢晚会02.rmvb</A></TD></TR></TBODY></TABLE>CD3:<BR>
<TABLE style="BORDER-RIGHT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; BORDER-BOTTOM: #cccccc 1px dotted" cellSpacing=0 cellPadding=6 width="95%" align=center border=0>
<TBODY>
<TR>
<TD style="WORD-WRAP: break-word" bgColor=#fdfddf><ANCHOR></ANCHOR><A href="ftftp://eee4.com:4421@vip8.eee4.com:4421/2008春晚/[3E迅雷电影站www.eee4.com]2008年央视春节联欢晚会03.rmvb" target=_blank>ftftp://eee4.com:4421@vip8.eee4.com:4421/2008春晚/[3E迅雷电影站www.eee4.com]2008年央视春节联欢晚会03.rmvb</A></TD></TR></TBODY></TABLE>CD4:<BR>
<TABLE style="BORDER-RIGHT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; BORDER-BOTTOM: #cccccc 1px dotted" cellSpacing=0 cellPadding=6 width="95%" align=center border=0>
<TBODY>
<TR>
<TD style="WORD-WRAP: break-word" bgColor=#fdfddf><ANCHOR></ANCHOR><A href="ftftp://eee4.com:4421@vip8.eee4.com:4421/2008春晚/[3E迅雷电影站www.eee4.com]2008年央视春节联欢晚会04.rmvb" target=_blank>ftftp://eee4.com:4421@vip8.eee4.com:4421/2008春晚/[3E迅雷电影站www.eee4.com]2008年央视春节联欢晚会04.rmvb</A></TD></TR></TBODY></TABLE>CD5:<BR>
<TABLE style="BORDER-RIGHT: #cccccc 1px dotted; TABLE-LAYOUT: fixed; BORDER-TOP: #cccccc 1px dotted; BORDER-LEFT: #cccccc 1px dotted; BORDER-BOTTOM: #cccccc 1px dotted" cellSpacing=0 cellPadding=6 width="95%" align=center border=0>
<TBODY>
<TR>
<TD style="WORD-WRAP: break-word" bgColor=#fdfddf><ANCHOR></ANCHOR><A href="ftftp://eee4.com:4421@vip8.eee4.com:4421/2008春晚/[3E迅雷电影站www.eee4.com]2008年央视春节联欢晚会05.rmvb" target=_blank>ftftp://eee4.com:4421@vip8.eee4.com:4421/2008春晚/[3E迅雷电影站www.eee4.com]2008年央视春节联欢晚会05.rmvb</A></TD></TR></TBODY></TABLE></div><ul class="mmlist{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MP44220-3R33.jpg{/dede:field}
