{dede:field name='keywords'}疯狗强尼BD中英双字1024/1280高{/dede:field}
{dede:field name='description'}疯狗强尼BD中英双字1024/1280高清迅雷下载、免费下载，疯狗强尼BD中英双字1024/1280高清Gvod高清在线播放，剧情介绍等。{/dede:field}
{dede:field name='title'}疯狗强尼BD中英双字1024/1280高清{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2012-02-05{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='xiazai'}ftp://3e:3e@www2.eee4.com:608/[3E电影站www.eee4.com]疯狗强尼DVD中英双字1280x720高清版.rmvb" target="_blank{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120523/133MP5I5P-5Na.jpg{/dede:field}
